{1}{}{Rope@@@@PID_PART_OF_ROPE 2@@PID_ROPE 1@exp 10 }
{2}{}{Pice Of Rope@@@@PID_FIBERS 4@@PID_PART_OF_ROPE 1@exp 5 }
{3}{}{Good Quality Iron Ore@@@SK_SCIENCE 80@PID_BIG_CHUNK_OF_IRON_ORE_CHUNK 1@PID_PICKAXE 1@PID_SMALL_CHUNK_OF_IRON_ORE 2@}
{4}{}{Cigarettes@@@@PID_TOBACCO 4@@PID_CIGARETTES 1@exp 5 }
{5}{}{Premitive Tool@@@@PID_FLINT 4@@PID_PRIMITIVETOOL 1@exp 5 }
{6}{}{Leather Jacket@@@@PID_BRAHMIN_SKIN 2&PID_PART_OF_ROPE 1@PID_KNIFE_DE 1&PID_WORK_BENCH_I 1@PID_LEATHER_JACKET_DE 1@exp 40 }
{7}{}{Desert Robe@@@@PID_BRAHMIN_SKIN 3&PID_PART_OF_ROPE 2@PID_KNIFE_DE 1&PID_WORK_BENCH_I 1@PID_ROBE_D_DE 1@exp 40 }
{8}{}{Pink Robe@@@@PID_BRAHMIN_SKIN 2&PID_PART_OF_ROPE 1@PID_KNIFE_DE 1&PID_WORK_BENCH_I 1@PID_ROBE_3_DE 1@exp 40 }
{9}{}{Antidote@@@@PID_SCORPION_TAIL 5@@PID_ANTIDOTE 1@exp 25 }
{10}{}{Knife@@@@PID_RUSTED_METAL_PARTS 1&PID_WOOD 1@@PID_KNIFE_DE 3@exp 20 }
{11}{}{Pickaxe@@@@PID_RUSTED_METAL_PARTS 1&PID_WOOD 1@PID_BLACKSMITH_FURNANCE_I 1@PID_PICKAXE 1@exp 20 }
{12}{}{Hatchet@@@@PID_RUSTED_METAL_PARTS 1&PID_WOOD 1@PID_BLACKSMITH_FURNANCE_I 1@PID_AXE 1@exp 20 }
{13}{}{Shovel@@@@PID_RUSTED_METAL_PARTS 1&PID_WOOD 1@PID_BLACKSMITH_FURNANCE_I 1@PID_SHOVEL 1@exp 20 }
{14}{}{Tool@@@@PID_RUSTED_METAL_PARTS 2@PID_BLACKSMITH_FURNANCE_I 1@PID_MULTI_TOOL 1@exp 20 }
{15}{}{Screwdriver Cross@@@@PID_RUSTED_METAL_PARTS 2@PID_BLACKSMITH_FURNANCE_I 1@PID_SCREWDRIVER_CROSS1 1@exp 20 }
{16}{}{Screwdriver Flat@@@@PID_RUSTED_METAL_PARTS 2@PID_BLACKSMITH_FURNANCE_I 1@PID_SCREWDRIVER_FLAT1 1@exp 20 }
{17}{}{Key Package@@@@PID_GOOD_METAL_PARTS 2@PID_BLACKSMITH_FURNANCE_I 1@PID_KEY_PACKAGE 1@exp 20 }
{18}{}{Etended Key Pack@@@@PID_HIGHT_QUALITY_METAL_PARTS 2@PID_BLACKSMITH_FURNANCE_I 1@PID_EZTENDED_KEY_PACK 1@exp 20 }
{19}{}{Rusted Metal Parts@@@@PID_IRON_ORE 2&PID_COAL 1@PID_BLACKSMITH_FURNANCE_I 1@PID_RUSTED_METAL_PARTS 1@}
{20}{}{Rusted Metal Parts@@@@PID_IRON_ORE 10&PID_COAL 5@PID_BLACKSMITH_FURNANCE_I 1@PID_RUSTED_METAL_PARTS 5@}
{21}{}{Good Metal Parts@@@SK_SCIENCE 60@PID_SMALL_CHUNK_OF_IRON_ORE 2&PID_COAL 1@PID_BLACKSMITH_FURNANCE_I 1@PID_GOOD_METAL_PARTS 1@}
{22}{}{Good Metal Parts@@@SK_SCIENCE 60@PID_SMALL_CHUNK_OF_IRON_ORE 10&PID_COAL 5@PID_BLACKSMITH_FURNANCE_I 1@PID_GOOD_METAL_PARTS 5@}
{23}{}{HQ Metal Parts@@@SK_SCIENCE 100@PID_GOOD_QUALITY_IRON_ORE_CHUNK 2&PID_COAL 1@PID_BLACKSMITH_FURNANCE_I 1@PID_HIGHT_QUALITY_METAL_PARTS 1@}
{24}{}{HQ Metal Parts@@@SK_SCIENCE 100@PID_GOOD_QUALITY_IRON_ORE_CHUNK 10&PID_COAL 5@PID_BLACKSMITH_FURNANCE_I 1@PID_HIGHT_QUALITY_METAL_PARTS 5@}
{25}{}{Rare Metal Parts@@@SK_SCIENCE 140@PID_RARE_IRON_ORE 2&PID_COAL 3@PID_BLACKSMITH_FURNANCE_I 1@PID_RARE_METAL_PARTS 1@}
{26}{}{Rare Metal Parts@@@SK_SCIENCE 140@PID_RARE_IRON_ORE 10&PID_COAL 15@PID_BLACKSMITH_FURNANCE_I 1@PID_RARE_METAL_PARTS 5@}
{27}{}{Good Metal Alloy@@@@PID_IRON_ORE 1&PID_MINERAL_SULFUR 1&PID_COAL 1@PID_BLACKSMITH_FURNANCE_I 1@PID_GOOD_METAL_ALLOY 1@}
{28}{}{Good Metal Alloy@@@@PID_IRON_ORE 5&PID_MINERAL_SULFUR 5&PID_COAL 5@PID_BLACKSMITH_FURNANCE_I 1@PID_GOOD_METAL_ALLOY 5@}
{29}{}{Purified Metal Alloy@@@SK_SCIENCE 60@PID_SMALL_CHUNK_OF_IRON_ORE 1&PID_MINERAL_SULFUR 1&PID_COAL 1@PID_BLACKSMITH_FURNANCE_I 1@PID_PURIFIED_METAL_ALLOY 1@}
{30}{}{Purified Metal Alloy@@@SK_SCIENCE 60@PID_SMALL_CHUNK_OF_IRON_ORE 5&PID_MINERAL_SULFUR 5&PID_COAL 5@PID_BLACKSMITH_FURNANCE_I 1@PID_PURIFIED_METAL_ALLOY 5@}
{31}{}{HQ Metal Alloy@@@SK_SCIENCE 100@PID_GOOD_QUALITY_IRON_ORE_CHUNK 1&PID_HIGHT_QUALITY_MINERAL 1&PID_COAL 1@PID_BLACKSMITH_FURNANCE_I 1@PID_HIGHT_QUALITY_METAL_ALLOY 1@}
{32}{}{HQ Metal Alloy@@@SK_SCIENCE 100@PID_GOOD_QUALITY_IRON_ORE_CHUNK 5&PID_HIGHT_QUALITY_MINERAL 5&PID_COAL 5@PID_BLACKSMITH_FURNANCE_I 1@PID_HIGHT_QUALITY_METAL_ALLOY 5@}
{33}{}{Rare Metal Alloy@@@SK_SCIENCE 140@PID_RARE_IRON_ORE 1&PID_RARE_MINERAL 1&PID_COAL 1@PID_BLACKSMITH_FURNANCE_I 1@PID_RARE_METAL_ALLOY 1@}
{34}{}{Rare Metal Alloy@@@SK_SCIENCE 140@PID_RARE_IRON_ORE 5&PID_RARE_MINERAL 5&PID_COAL 5@PID_BLACKSMITH_FURNANCE_I 1@PID_RARE_METAL_ALLOY 5@}
{35}{}{Tube@@@SK_SCIENCE 50@PID_RUSTED_METAL_PARTS 1&PID_COAL 1@PID_BLACKSMITH_FURNANCE_I 1@PID_TUBE1 1@}
{36}{}{Polished Tube@@@SK_SCIENCE 80@PID_GOOD_METAL_PARTS 1&PID_COAL 1@PID_BLACKSMITH_FURNANCE_I 1@PID_TUBE2 1@}
{37}{}{Tube Package@@@SK_SCIENCE 100@PID_HIGHT_QUALITY_METAL_PARTS 1&PID_COAL 1@PID_BLACKSMITH_FURNANCE_I 1@PID_TUBE3 1@}
{38}{}{Gunpowder Class 1@@@@PID_MINERAL_SULFUR 1@PID_WORK_BENCH_V 1@PID_GUNPOWDER_CLASS_I 1@}
{39}{}{Gunpowder Class 2@@@SK_SCIENCE 60@PID_MINERAL_SULFUR 2@PID_WORK_BENCH_V 1@PID_GUNPOWDER_CLASS_II 1@}
{40}{}{Gunpowder Class 3@@@SK_SCIENCE 100@PID_MINERAL_SULFUR 1&PID_HIGHT_QUALITY_MINERAL 1@PID_WORK_BENCH_V 1@PID_GUNPOWDER_CLASS_III 1@}
{41}{}{Scope@@@@PID_RUSTED_METAL_PARTS 1&PID_GOOD_METAL_ALLOY 1&PID_SCREWS 1@PID_WORK_BENCH_I 1@PID_SCOPE 1@}
{42}{}{Small Scope@@@SK_SCIENCE 80@PID_GOOD_METAL_PARTS 1&PID_PURIFIED_METAL_ALLOY 1&PID_SCREWS 2@PID_WORK_BENCH_I 1@PID_SMALL_SCOPE 1@}
{43}{}{Strong Scope@@S@SK_SCIENCE 100@PID_HIGHT_QUALITY_METAL_PARTS 1&PID_HIGHT_QUALITY_METAL_ALLOY 1&PID_SCREWS 3@PID_WORK_BENCH_I 1@PID_STRONG_SCOPE 2@}
{44}{}{Barel@@@@PID_GOOD_METAL_ALLOY 2&PID_SCREWS 1@PID_WORK_BENCH_I 1@PID_BARREL 1@}
{45}{}{Zip Gun@@@@PID_RUSTED_METAL_PARTS 1&PID_WOOD 1@@PID_ZIP_GUN_DE 1@exp 10 }
{46}{}{10mm Pistol@@@@PID_RUSTED_METAL_PARTS 1&PID_GOOD_METAL_ALLOY 1&PID_SCRAP 1&PID_PACKAGE_OF_PARTS 1@PID_WORK_BENCH_I 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_10MM_PISTOL_DE 1@exp 15 }
{47}{}{9mm Mauser@@@@PID_RUSTED_METAL_PARTS 2&PID_SCRAP 1&PID_WOOD 1@PID_WORK_BENCH_I 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_9MM_MAUSER_DE 1@exp 10 }
{48}{}{9mm Mauser Smg@@@@PID_9MM_MAUSER_DE 1&PID_GOOD_METAL_ALLOY 1@PID_WORK_BENCH_I 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_MAUSER_SMG_DE 1@exp 20 }
{49}{}{10mm Smg@@@SK_SMALL_GUNS 60&SK_SCIENCE 60@PID_RUSTED_METAL_PARTS 2&PID_GOOD_METAL_ALLOY 1&PID_SCRAP 2&PID_PACKAGE_OF_PARTS 1&PID_SCREWS 1@PID_WORK_BENCH_I 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_10MM_SMG_DE 1@exp 25 }
{50}{}{Desert Eagle@@@SK_SMALL_GUNS 60&SK_SCIENCE 60@PID_RUSTED_METAL_PARTS 2&PID_GOOD_METAL_ALLOY 2&PID_PACKAGE_OF_PARTS 1&PID_SCREWS 1@PID_WORK_BENCH_I 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_DESERT_EAGLE_DE 1@exp 25 }
{51}{}{Desert Eagle Exp Mag@@@SK_SMALL_GUNS 60&SK_SCIENCE 60@PID_DESERT_EAGLE_DE 1&PID_RUSTED_METAL_PARTS 1&PID_GOOD_METAL_ALLOY 1&PID_COMPENSATING_SPRING 1@PID_WORK_BENCH_I 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_DESERT_EAGLE_EXT_MAG_DE 1@exp 25 }
{52}{}{44 Magnum@@@SK_SMALL_GUNS 60&SK_SCIENCE 60@PID_RUSTED_METAL_PARTS 2&PID_GOOD_METAL_ALLOY 2&PID_PACKAGE_OF_PARTS 1&PID_SCREWS 1@PID_WORK_BENCH_I 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_44_MAGNUM_REVOLVER_DE 1@exp 25 }
{53}{}{44 Magnum Speed@@@SK_SMALL_GUNS 60&SK_SCIENCE 60@PID_44_MAGNUM_REVOLVER_DE 1&PID_BARREL 1&PID_COMPENSATING_SPRING 1@PID_WORK_BENCH_I 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_44_MAGNUM_SPEEDLOADER_DE 1@exp 25 }
{54}{}{Hunting Rifle@@@SK_SMALL_GUNS 60&SK_SCIENCE 60@PID_RUSTED_METAL_PARTS 2&PID_GOOD_METAL_ALLOY 2&PID_COMPENSATING_SPRING 1&PID_TUBE1 1@PID_WORK_BENCH_I 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_HUNTING_RIFLE_DE 1@exp 30 }
{55}{}{Scoped Hunting Rifle@@@SK_SMALL_GUNS 60&SK_SCIENCE 60@PID_HUNTING_RIFLE_DE 1&PID_SCOPE 1@PID_WORK_BENCH_I 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_SCOPED_HUNTING_RIFLE_DE 1@exp 30 }
{56}{}{Shotgun@@@SK_SMALL_GUNS 60&SK_SCIENCE 60@PID_RUSTED_METAL_PARTS 1&PID_SCRAP 1&PID_WOOD 1&PID_TUBE1 2@PID_WORK_BENCH_I 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_SHOTGUN_DE 1@exp 30 }
{57}{}{Red BB Gun@@@SK_SMALL_GUNS 40&SK_SCIENCE 40@PID_RUSTED_METAL_PARTS 1&PID_SCRAP 1&PID_TUBE1 1&PID_WOOD 1@PID_WORK_BENCH_I 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_RED_RYDER_BB_GUN_DE 1@exp 30 }
{58}{}{Pipe Rifle@@@@PID_SCRAP 1&PID_TUBE1 1&PID_WOOD 1@PID_WORK_BENCH_I 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_SPRINGER_RIFLE_DE 1@exp 10 }
{59}{}{Sawed Off Shotgun@@@SK_SMALL_GUNS 60&SK_SCIENCE 60@PID_RUSTED_METAL_PARTS 1&PID_WOOD 1&PID_SCRAP 1&PID_TUBE1 2&PID_COMPENSATING_SPRING 1@PID_WORK_BENCH_I 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_SAWED_OFF_SHOTGUN_DE 1@exp 30 }
{60}{}{Colt M1911@@@SK_SMALL_GUNS 60&SK_SCIENCE 60@PID_RUSTED_METAL_PARTS 2&PID_GOOD_METAL_ALLOY 2&PID_SCRAP 2&PID_SCREWS 1@PID_WORK_BENCH_I 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_COLT1_DE 1@exp 30 }
{61}{}{14mm Pistol@@@SK_SMALL_GUNS 80&SK_SCIENCE 80@PID_GOOD_METAL_PARTS 4&PID_PURIFIED_METAL_ALLOY 3&PID_SCRAP 2&PID_SCREWS 2&PID_PACKAGE_OF_PARTS 2@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_14MM_PISTOL_DE 1@exp 50 }
{62}{}{Thompson M1928@@@SK_SMALL_GUNS 80&SK_SCIENCE 80@PID_GOOD_METAL_PARTS 2&PID_GOOD_METAL_ALLOY 1&PID_SCREWS 2&PID_SCRAP 2&PID_PACKAGE_OF_PARTS 1@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_TOMMY_GUN_DE 1@exp 50 }
{63}{}{Grease Gun@@@SK_SMALL_GUNS 80&SK_SCIENCE 80@PID_GOOD_METAL_PARTS 3&PID_PURIFIED_METAL_ALLOY 1&PID_SCREWS 2&PID_SCRAP 2&PID_PACKAGE_OF_PARTS 1@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_GREASE_GUN_DE 1@exp 50 }
{64}{}{Needler Pistol@@@SK_SMALL_GUNS 80&SK_SCIENCE 80@PID_GOOD_METAL_PARTS 3&PID_PURIFIED_METAL_ALLOY 3&PID_SCREWS 2&PID_SCRAP 2&PID_PACKAGE_OF_PARTS 1@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_NEEDLER_PISTOL_DE 1@exp 50 }
{65}{}{Assault Rifle@@@SK_SMALL_GUNS 80&SK_SCIENCE 80@PID_GOOD_METAL_PARTS 4&PID_TUBE2 1&PID_SCREWS 2&PID_PACKAGE_OF_PARTS 1@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_ASSAULT_RIFLE_DE 1@exp 60 }
{66}{}{Assault Rifle Ext Mag@@@SK_SMALL_GUNS 80&SK_SCIENCE 80@PID_ASSAULT_RIFLE_DE 1&PID_PURIFIED_METAL_ALLOY 1&PID_PACKAGE_OF_PARTS 1&PID_COMPENSATING_SPRING 1@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_ASSAULT_RIFLE_EXT_MAG_DE 1@exp 60 }
{67}{}{Fn Fal@@@SK_SMALL_GUNS 110&SK_SCIENCE 100@PID_GOOD_METAL_PARTS 4&PID_PURIFIED_METAL_ALLOY 2&PID_TUBE2 1&PID_SCREWS 2&PID_PACKAGE_OF_PARTS 2@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_FN_FAL_DE 1@exp 100 }
{68}{}{Combat Shotgun@@@SK_SMALL_GUNS 110&SK_SCIENCE 100@PID_GOOD_METAL_PARTS 2&PID_PURIFIED_METAL_ALLOY 2&PID_TUBE2 1&PID_SCREWS 1&PID_COMPENSATING_SPRING 2@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_COMBAT_SHOTGUN_DE 1@exp 80 }
{69}{}{H&K CAWS@@@SK_SMALL_GUNS 110&SK_SCIENCE 100@PID_GOOD_METAL_PARTS 3&PID_PURIFIED_METAL_ALLOY 3&PID_TUBE2 1&PID_COMPENSATING_SPRING 3&PID_SCREWS 2@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_HK_CAWS_DE 1@exp 90 }
{70}{}{XL70E3@@@SK_SMALL_GUNS 110&SK_SCIENCE 100@PID_SMALL_SCOPE 1&PID_GOOD_METAL_PARTS 4&PID_PURIFIED_METAL_ALLOY 3&PID_TUBE2 1&PID_SCREWS 2&PID_PACKAGE_OF_PARTS 2@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_INDEPENDENT_DE 1@exp 100 }
{71}{}{Ak47@@@SK_SMALL_GUNS 110&SK_SCIENCE 100@PID_GOOD_METAL_PARTS 3&PID_PURIFIED_METAL_ALLOY 3&PID_TUBE2 1&PID_WOOD 2&PID_PACKAGE_OF_PARTS 2@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_AK47_NORMAL1_DE 1@exp 100 }
{72}{}{MP5@@@SK_SMALL_GUNS 110&SK_SCIENCE 100@PID_GOOD_METAL_PARTS 2&PID_PURIFIED_METAL_ALLOY 2&PID_SCREWS 2&PID_SCRAP 2&PID_PACKAGE_OF_PARTS 2@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_MP5_DE 1@exp 100 }
{73}{}{M16@@@SK_SMALL_GUNS 160&SK_SCIENCE 160@PID_GOOD_METAL_PARTS 3&PID_PURIFIED_METAL_ALLOY 3&PID_HIGHT_QUALITY_METAL_ALLOY 1&PID_TUBE2 1&PID_PACKAGE_OF_PARTS 2@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_M16_DE 1@exp 120 }
{74}{}{M32@@@SK_SMALL_GUNS 160&SK_SCIENCE 160@PID_GOOD_METAL_PARTS 3&PID_HIGHT_QUALITY_METAL_PARTS 2&PID_PURIFIED_METAL_ALLOY 5&PID_TUBE3 1&PID_COMPENSATING_SPRING 3@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_M32_DE 1@exp 120 }
{75}{}{HK P90c@@@SK_SMALL_GUNS 200&SK_SCIENCE 180@PID_HIGHT_QUALITY_METAL_PARTS 4&PID_HIGHT_QUALITY_METAL_ALLOY 3&PID_RARE_METAL_ALLOY 2&PID_SCREWS 2&PID_PACKAGE_OF_PARTS 2@PID_PRODUCTION_MACHINE_II 1&PID_EZTENDED_KEY_PACK 1@PID_HK_P90C_DE 1@exp 200 }
{76}{}{223 Pistol@@@SK_SMALL_GUNS 200&SK_SCIENCE 180@PID_HIGHT_QUALITY_METAL_PARTS 3&PID_HIGHT_QUALITY_METAL_ALLOY 2&PID_SCREWS 3&PID_PACKAGE_OF_PARTS 2&PID_COMPENSATING_SPRING 1@PID_PRODUCTION_MACHINE_II 1&PID_EZTENDED_KEY_PACK 1@PID_223_PISTOL_DE 1@exp 170 }
{77}{}{Pancor Jackhammer@@@SK_SMALL_GUNS 200&SK_SCIENCE 180@PID_HIGHT_QUALITY_METAL_PARTS 4&PID_HIGHT_QUALITY_METAL_ALLOY 4&PID_TUBE3 1&PID_SCREWS 2&PID_COMPENSATING_SPRING 3@PID_PRODUCTION_MACHINE_II 1&PID_EZTENDED_KEY_PACK 1@PID_PANCOR_JACKHAMMER_DE 1@exp 150 }
{78}{}{Sniper Rifle@@@SK_SMALL_GUNS 240&SK_SCIENCE 180@PID_HIGHT_QUALITY_METAL_PARTS 5&PID_RARE_METAL_PARTS 1&PID_RARE_METAL_ALLOY 1&PID_COMPENSATING_SPRING 1&PID_STRONG_SCOPE 1&PID_TUBE3 1@PID_PRODUCTION_MACHINE_II 1&PID_EZTENDED_KEY_PACK 1@PID_SNIPER_RIFLE_DE 1@exp 300 }
{79}{}{Ak47 Scope@@@SK_SMALL_GUNS 200&SK_SCIENCE 180@PID_AK47_NORMAL1_DE 1&PID_HIGHT_QUALITY_METAL_ALLOY 1&PID_STRONG_SCOPE 1&PID_COMPENSATING_SPRING 2@PID_PRODUCTION_MACHINE_II 1&PID_EZTENDED_KEY_PACK 1@PID_AK47_TACTICAL3_DE 1@exp 50 }
{80}{}{Flamethrower@@@SK_BIG_GUNS 40&SK_SCIENCE 40@PID_RUSTED_METAL_PARTS 4&PID_GOOD_METAL_ALLOY 2&PID_SCREWS 4&PID_SCRAP 3&PID_PACKAGE_OF_PARTS 2&PID_TUBE1 1@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_FLAMER_DE 1@exp 50 }
{81}{}{IMP Flamethrower@@@SK_BIG_GUNS 60&SK_SCIENCE 60@PID_FLAMER_DE 1&PID_GOOD_METAL_PARTS 1&PID_PURIFIED_METAL_ALLOY 1&PID_PACKAGE_OF_PARTS 2@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_IMPROVED_FLAMETHROWER_DE 1@exp 50 }
{82}{}{Minigun@@@SK_BIG_GUNS 80&SK_SCIENCE 80@PID_RUSTED_METAL_PARTS 4&PID_GOOD_METAL_ALLOY 4&PID_SCRAP 4&PID_TUBE1 3&PID_SCREWS 4&PID_PACKAGE_OF_PARTS 4@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_MINIGUN_DE 1@exp 70 }
{83}{}{m60@@@SK_BIG_GUNS 120&SK_SCIENCE 100@PID_GOOD_METAL_PARTS 5&PID_PURIFIED_METAL_ALLOY 5&PID_TUBE2 2&PID_SCREWS 2&PID_SCRAP 2&PID_COMPENSATING_SPRING 2@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_M60_DE 1@exp 100 }
{84}{}{Ave Minigun@@@SK_BIG_GUNS 160&SK_SCIENCE 120@PID_MINIGUN_DE 1&PID_GOOD_METAL_PARTS 3&PID_PURIFIED_METAL_ALLOY 2&PID_PACKAGE_OF_PARTS 4&PID_SCREWS 3@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_AVENGER_MINIGUN_DE 1@exp 130 }
{85}{}{Napalm Blaster@@@SK_BIG_GUNS 160&SK_SCIENCE 120@PID_GOOD_METAL_PARTS 5&PID_PURIFIED_METAL_ALLOY 5&PID_TUBE2 2&PID_SCREWS 2&PID_COMPENSATING_SPRING 2@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_FLAMERN_DE 1@exp 130 }
{86}{}{Rocket Launcher@@@SK_BIG_GUNS 180&SK_SCIENCE 150@PID_HIGHT_QUALITY_METAL_PARTS 4&PID_HIGHT_QUALITY_METAL_ALLOY 3&PID_TUBE3 2&PID_SCREWS 2&PID_PACKAGE_OF_PARTS 4@PID_PRODUCTION_MACHINE_III 1&PID_EZTENDED_KEY_PACK 1@PID_ROCKET_LAUNCHER_DE 1@exp 150 }
{87}{}{LSW@@@SK_BIG_GUNS 180&SK_SCIENCE 150@PID_HIGHT_QUALITY_METAL_PARTS 6&PID_HIGHT_QUALITY_METAL_ALLOY 4&PID_TUBE3 1&PID_COMPENSATING_SPRING 4&PID_PACKAGE_OF_PARTS 3@PID_PRODUCTION_MACHINE_III 1&PID_EZTENDED_KEY_PACK 1@PID_LIGHT_SUPPORT_WEAPON_DE 1@exp 150 }
{88}{}{M240@@@SK_BIG_GUNS 200&SK_SCIENCE 180@PID_HIGHT_QUALITY_METAL_PARTS 5&PID_RARE_METAL_ALLOY 2&PID_TUBE3 1&PID_COMPENSATING_SPRING 3&PID_PACKAGE_OF_PARTS 2@PID_PRODUCTION_MACHINE_III 1&PID_EZTENDED_KEY_PACK 1@PID_M240_DE 1@exp 200 }
{89}{}{UKM 200p@@@SK_BIG_GUNS 200&SK_SCIENCE 180@PID_RARE_METAL_PARTS 3&PID_HIGHT_QUALITY_METAL_ALLOY 4&PID_TUBE3 1&PID_SCREWS 4&PID_PACKAGE_OF_PARTS 3@PID_PRODUCTION_MACHINE_III 1&PID_EZTENDED_KEY_PACK 1@PID_UKM_DE 1@exp 200 }
{90}{}{PKPKS@@@SK_BIG_GUNS 200&SK_SCIENCE 180@PID_HIGHT_QUALITY_METAL_PARTS 4&PID_HIGHT_QUALITY_METAL_ALLOY 7&PID_TUBE3 1&PID_COMPENSATING_SPRING 4&PID_SCREWS 6@PID_PRODUCTION_MACHINE_III 1&PID_EZTENDED_KEY_PACK 1@PID_PKS_DE 1@exp 200 }
{91}{}{Laser Pistol@@@@PID_RUSTED_METAL_PARTS 1&PID_GOOD_METAL_ALLOY 1&PID_FUSE 2&PID_ELECTRONIC_PACKAGE 1&PID_ELECTRONIC_PARTS 3@PID_WORK_BENCH_I 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_LASER_PISTOL_DE 1@exp 25 }
{92}{}{Magneto Laser Pistol@@@SK_ENERGY_WEAPONS 60&SK_SCIENCE 60@PID_LASER_PISTOL_DE 1&PID_ELECTRONIC_PARTS 4&PID_BLUE_CHIP 1@PID_WORK_BENCH_I 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_MAGNETO_LASER_PISTOL_DE 1@exp 30 }
{93}{}{Laser Rifle@@@SK_ENERGY_WEAPONS 100&SK_SCIENCE 80@PID_GOOD_METAL_PARTS 3&PID_PURIFIED_METAL_ALLOY 2&PID_ELECTRONIC_PARTS 4&PID_SCRAP 2&PID_ELECTRONIC_PACKAGE 1&PID_SCREWS 1@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_LASER_RIFLE_DE 1@exp 80 }
{94}{}{Laser Rifle Ext Cap@@@SK_ENERGY_WEAPONS 120&SK_SCIENCE 100@PID_LASER_RIFLE_DE 1&PID_PURIFIED_METAL_ALLOY 1&PID_ELECTRONIC_PARTS 2&PID_FUSE 2&PID_BLUE_CHIP 1@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_LASER_RIFLE_EXT_CAP_DE 1@exp 50 }
{95}{}{Plasma Pistol@@@SK_ENERGY_WEAPONS 120&SK_SCIENCE 100@PID_GOOD_METAL_PARTS 4&PID_HIGHT_QUALITY_METAL_PARTS 2&PID_PURIFIED_METAL_ALLOY 2&PID_ELECTRONIC_PARTS 4&PID_PLASMA_DIFFUSER 1&PID_ELECTRONIC_PACKAGE 1@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_PLASMA_PISTOL_DE 1@exp 100 }
{96}{}{Plasma Pistol Ext Cap@@@SK_ENERGY_WEAPONS 120&SK_SCIENCE 100@PID_PLASMA_PISTOL_DE 1&PID_GOOD_METAL_PARTS 2&PID_ELECTRONIC_PARTS 2&PID_BLUE_CHIP 1&PID_ELECTRONIC_PACKAGE 1@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_PLASMA_PISTOL_EXT_CART_DE 1@exp 50 }
{97}{}{Plasma Rifle@@@SK_ENERGY_WEAPONS 160&SK_SCIENCE 140@PID_PLASMA_DIFFUSER 2&PID_PURIFIED_METAL_ALLOY 3&PID_ELECTRONIC_PACKAGE 2&PID_SCRAP 3&PID_GOOD_METAL_PARTS 4&PID_GOOD_METAL_PARTS 4&PID_HIGHT_QUALITY_METAL_PARTS 3&PID_HIGHT_QUALITY_METAL_ALLOY 2&PID_RARE_METAL_PARTS 1@PID_PRODUCTION_MACHINE_IV 1&PID_EZTENDED_KEY_PACK 1@PID_PLASMA_RIFLE_DE 1@exp 200 }
{98}{}{SDG@@@SK_ENERGY_WEAPONS 200&SK_SCIENCE 160@PID_GOOD_METAL_PARTS 4&PID_PURIFIED_METAL_ALLOY 4&PID_ELECTRONIC_PARTS 4&PID_FUSE 2&PID_ELECTRONIC_PACKAGE 2&PID_GOLD 2&PID_SCREWS 1@PID_PRODUCTION_MACHINE_V 1&PID_EZTENDED_KEY_PACK 1@PID_DAMPISTOL_DE 1@exp 200 }
{99}{}{Electro RL@@@SK_ENERGY_WEAPONS 200&SK_SCIENCE 160@PID_ROCKET_LAUNCHER_DE 1&PID_HIGHT_QUALITY_METAL_PARTS 5&PID_HIGHT_QUALITY_METAL_ALLOY 2&PID_ELECTRONIC_PARTS 3&PID_GOLD 2&PID_BLUE_CHIP 2&PID_ELECTRONIC_PACKAGE 3@PID_PRODUCTION_MACHINE_V 1&PID_EZTENDED_KEY_PACK 1@PID_ROCKETELE_DE 1@exp 300 }
{100}{}{Dam Rifle@@@SK_ENERGY_WEAPONS 200&SK_SCIENCE 160@PID_HIGHT_QUALITY_METAL_PARTS 4&PID_HIGHT_QUALITY_METAL_ALLOY 5&PID_GOLD 4&PID_FUSE 2&PID_ELECTRONIC_PARTS 2&PID_ELECTRONIC_PACKAGE 3@PID_PRODUCTION_MACHINE_V 1&PID_EZTENDED_KEY_PACK 1@PID_DAMRIFLE_DE 1@exp 250 }
{101}{}{SRG@@@SK_ENERGY_WEAPONS 200&SK_SCIENCE 160@PID_GOOD_METAL_PARTS 4&PID_PURIFIED_METAL_ALLOY 4&PID_ELECTRONIC_PARTS 4&PID_FUSE 2&PID_ELECTRONIC_PACKAGE 2&PID_GOLD 2&PID_SCREWS 1@PID_PRODUCTION_MACHINE_VI 1&PID_EZTENDED_KEY_PACK 1@PID_RADPISTOL_DE 1@exp 200 }
{102}{}{RAD RL@@@SK_ENERGY_WEAPONS 200&SK_SCIENCE 160@PID_ROCKET_LAUNCHER_DE 1&PID_HIGHT_QUALITY_METAL_PARTS 5&PID_HIGHT_QUALITY_METAL_ALLOY 4&PID_ELECTRONIC_PARTS 5&PID_GOLD 2&PID_BLUE_CHIP 2&PID_ELECTRONIC_PACKAGE 3@PID_PRODUCTION_MACHINE_VI 1&PID_EZTENDED_KEY_PACK 1@PID_ROCKETRAD_DE 1@exp 300 }
{103}{}{Rad Rifle@@@SK_ENERGY_WEAPONS 200&SK_SCIENCE 160@PID_HIGHT_QUALITY_METAL_PARTS 4&PID_HIGHT_QUALITY_METAL_ALLOY 5&PID_GOLD 4&PID_FUSE 4&PID_ELECTRONIC_PARTS 4&PID_ELECTRONIC_PACKAGE 4@PID_PRODUCTION_MACHINE_VI 1&PID_EZTENDED_KEY_PACK 1@PID_RADRIFLE_DE 1@exp 250 }
{104}{}{10mm JPH@@@@PID_RUSTED_METAL_PARTS 1&PID_GUNPOWDER_CLASS_I 4@PID_WORK_BENCH_V 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_10MM_JHP_DE 100@exp 50 }
{105}{}{10mm JPH@@@@PID_RUSTED_METAL_PARTS 10&PID_GUNPOWDER_CLASS_I 40@PID_WORK_BENCH_V 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_10MM_JHP_DE 1000@exp 500 }
{106}{}{10mm AP@@@@PID_RUSTED_METAL_PARTS 1&PID_GUNPOWDER_CLASS_II 4@PID_WORK_BENCH_V 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_10MM_AP_DE 100@exp 70 }
{107}{}{10mm AP@@@@PID_RUSTED_METAL_PARTS 10&PID_GUNPOWDER_CLASS_II 40@PID_WORK_BENCH_V 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_10MM_AP_DE 1000@exp 700 }
{108}{}{44 JPH@@@@PID_RUSTED_METAL_PARTS 1&PID_GUNPOWDER_CLASS_I 4@PID_WORK_BENCH_V 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_44_MAGNUM_JHP_DE 100@exp 50 }
{109}{}{44 JPH@@@@PID_RUSTED_METAL_PARTS 10&PID_GUNPOWDER_CLASS_I 40@PID_WORK_BENCH_V 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_44_MAGNUM_JHP_DE 1000@exp 500 }
{110}{}{44 AP@@@@PID_RUSTED_METAL_PARTS 1&PID_GUNPOWDER_CLASS_II 4@PID_WORK_BENCH_V 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_44_FMJ_MAGNUM_DE 100@exp 70 }
{111}{}{44 AP@@@@PID_RUSTED_METAL_PARTS 10&PID_GUNPOWDER_CLASS_II 40@PID_WORK_BENCH_V 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_44_FMJ_MAGNUM_DE 1000@exp 700 }
{112}{}{5mm JPH@@@@PID_RUSTED_METAL_PARTS 1&PID_SCRAP 1&PID_GUNPOWDER_CLASS_I 5@PID_WORK_BENCH_V 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_5MM_JHP_DE 100@exp 50 }
{113}{}{5mm JPH@@@@PID_RUSTED_METAL_PARTS 10&PID_SCRAP 1&PID_GUNPOWDER_CLASS_I 50@PID_WORK_BENCH_V 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_5MM_JHP_DE 1000@exp 500 }
{114}{}{5mm AP@@@@PID_GOOD_METAL_PARTS 1&PID_SCRAP 1&PID_GUNPOWDER_CLASS_II 5@PID_WORK_BENCH_V 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_5MM_AP_DE 100@exp 70 }
{115}{}{5mm AP@@@@PID_GOOD_METAL_PARTS 10&PID_SCRAP 10&PID_GUNPOWDER_CLASS_II 50@PID_WORK_BENCH_V 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_5MM_AP_DE 1000@exp 700 }
{116}{}{9mm JPH@@@@PID_RUSTED_METAL_PARTS 1&PID_GUNPOWDER_CLASS_I 5@PID_WORK_BENCH_V 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_9JHP_DE 100@exp 50 }
{117}{}{9mm JPH@@@@PID_RUSTED_METAL_PARTS 10&PID_GUNPOWDER_CLASS_I 50@PID_WORK_BENCH_V 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_9JHP_DE 1000@exp 500 }
{118}{}{9mm AP@@@@PID_RUSTED_METAL_PARTS 1&PID_GUNPOWDER_CLASS_II 5@PID_WORK_BENCH_V 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_9AP_DE 100@exp 70 }
{119}{}{9mm PAR@@@@PID_RUSTED_METAL_PARTS 1&PID_GUNPOWDER_CLASS_I 5@PID_WORK_BENCH_V 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_9MM_BALL_DE 100@exp 50 }
{120}{}{9mm PAR@@@@PID_RUSTED_METAL_PARTS 10&PID_GUNPOWDER_CLASS_I 50@PID_WORK_BENCH_V 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_9MM_BALL_DE 1000@exp 500 }
{121}{}{9mm @@@@PID_RUSTED_METAL_PARTS 1&PID_GUNPOWDER_CLASS_I 4@PID_WORK_BENCH_V 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_9MM_AMMO_DE 100@exp 50 }
{122}{}{9mm @@@@PID_RUSTED_METAL_PARTS 10&PID_GUNPOWDER_CLASS_I 40@PID_WORK_BENCH_V 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_9MM_AMMO_DE 1000@exp 500 }
{123}{}{45 Cal@@@@PID_RUSTED_METAL_PARTS 1&PID_SCRAP 1&PID_GUNPOWDER_CLASS_I 6@PID_WORK_BENCH_V 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_45_ACP_DE 100@exp 50 }
{124}{}{45 Cal@@@@PID_RUSTED_METAL_PARTS 10&PID_SCRAP 10&PID_GUNPOWDER_CLASS_I 60@PID_WORK_BENCH_V 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_45_ACP_DE 1000@exp 500 }
{125}{}{45 Cal 2@@@@PID_RUSTED_METAL_PARTS 1&PID_SCRAP 1&PID_GUNPOWDER_CLASS_I 5@PID_WORK_BENCH_V 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_45_CALIBER_AMMO_DE 100@exp 50 }
{126}{}{45 Cal 2@@@@PID_RUSTED_METAL_PARTS 10&PID_SCRAP 10&PID_GUNPOWDER_CLASS_I 50@PID_WORK_BENCH_V 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_45_CALIBER_AMMO_DE 1000@exp 500 }
{127}{}{12 ga@@@@PID_RUSTED_METAL_PARTS 1&PID_GUNPOWDER_CLASS_I 6@PID_WORK_BENCH_V 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_SHOTGUN_SHELLS_DE 100@exp 50 }
{128}{}{12 ga@@@@PID_RUSTED_METAL_PARTS 10&PID_GUNPOWDER_CLASS_I 60@PID_WORK_BENCH_V 1&PID_SCREWDRIVER_CROSS1 1|PID_SCREWDRIVER_FLAT1 1@PID_SHOTGUN_SHELLS_DE 1000@exp 500 }
{129}{}{223@@@@PID_GOOD_METAL_PARTS 1&PID_SCRAP 1&PID_GUNPOWDER_CLASS_III 2&PID_GUNPOWDER_CLASS_II 4@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_223_FMJ_DE 100@exp 100 }
{130}{}{223@@@@PID_GOOD_METAL_PARTS 5&PID_SCRAP 5&PID_GUNPOWDER_CLASS_III 10&PID_GUNPOWDER_CLASS_II 20@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_223_FMJ_DE 500@exp 500 }
{131}{}{14mm@@@@PID_GOOD_METAL_PARTS 1&PID_SCRAP 1&PID_GUNPOWDER_CLASS_I 5@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_14MM_AP_DE 100@exp 100 }
{132}{}{14mm@@@@PID_GOOD_METAL_PARTS 10&PID_SCRAP 10&PID_GUNPOWDER_CLASS_I 50@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_14MM_AP_DE 1000@exp 1000 }
{133}{}{762x39mm@@@SK_SCIENCE 100@PID_GOOD_METAL_PARTS 1&PID_SCRAP 1&PID_GUNPOWDER_CLASS_II 5@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_762X39_DE 100@exp 100 }
{134}{}{762x39mm@@@SK_SCIENCE 100@PID_GOOD_METAL_PARTS 5&PID_SCRAP 5&PID_GUNPOWDER_CLASS_II 25@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_762X39_DE 500@exp 500 }
{135}{}{762x51mm@@@SK_SCIENCE 100@PID_GOOD_METAL_PARTS 1&PID_SCRAP 1&PID_GUNPOWDER_CLASS_II 4&PID_GUNPOWDER_CLASS_III 2@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_762x51_DE 100@exp 100 }
{136}{}{762x51mm@@@SK_SCIENCE 100@PID_GOOD_METAL_PARTS 5&PID_SCRAP 5&PID_GUNPOWDER_CLASS_II 20&PID_GUNPOWDER_CLASS_III 10@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_762x51_DE 500@exp 500 }
{137}{}{762x54mm@@@SK_SCIENCE 100@PID_GOOD_METAL_PARTS 1&PID_SCRAP 1&PID_GUNPOWDER_CLASS_II 4&PID_GUNPOWDER_CLASS_III 1@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_762X54_DE 100@exp 100 }
{138}{}{762x54mm@@@SK_SCIENCE 100@PID_GOOD_METAL_PARTS 5&PID_SCRAP 5&PID_GUNPOWDER_CLASS_II 20&PID_GUNPOWDER_CLASS_III 5@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_762X54_DE 500@exp 500 }
{139}{}{40x46mm@@@SK_SCIENCE 100@PID_HIGHT_QUALITY_METAL_PARTS 1&PID_SCRAP 1&PID_GUNPOWDER_CLASS_III 5&PID_GUNPOWDER_CLASS_II 4@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_40x46_DE 40@exp 100 }
{140}{}{40x46mm@@@SK_SCIENCE 100@PID_HIGHT_QUALITY_METAL_PARTS 5&PID_SCRAP 5&PID_GUNPOWDER_CLASS_III 25&PID_GUNPOWDER_CLASS_II 20@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_40x46_DE 200@exp 500 }
{141}{}{nedler JPH@@@SK_SCIENCE 100@PID_GOOD_METAL_PARTS 1&PID_SCRAP 1&PID_GUNPOWDER_CLASS_II 4@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_HN_NEEDLER_CARTRIDGE_DE 100@exp 100 }
{142}{}{nedler JPH@@@SK_SCIENCE 100@PID_GOOD_METAL_PARTS 10&PID_SCRAP 10&PID_GUNPOWDER_CLASS_II 40@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_HN_NEEDLER_CARTRIDGE_DE 1000@exp 1000 }
{143}{}{nedler AP@@@SK_SCIENCE 100@PID_HIGHT_QUALITY_METAL_PARTS 1&PID_SCRAP 1&PID_GUNPOWDER_CLASS_II 4&PID_GUNPOWDER_CLASS_III 1@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_HN_AP_NEEDLER_CARTRIDGE_DE 100@exp 100 }
{144}{}{BB Ammo@@@@PID_RUSTED_METAL_PARTS 4@PID_WORK_BENCH_V 1@PID_BBS_DE 100@exp 10 }
{145}{}{BB Ammo@@@@PID_RUSTED_METAL_PARTS 40@PID_WORK_BENCH_V 1@PID_BBS_DE 1000@exp 100 }
{146}{}{2mmEC@@@SK_SCIENCE 150@PID_RARE_METAL_PARTS 1&PID_RARE_METAL_ALLOY 1&PID_GUNPOWDER_CLASS_III 5@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_4_7MM_CASELESS_DE 25@exp 200 }
{147}{}{2mmEC@@@SK_SCIENCE 150@PID_RARE_METAL_PARTS 5&PID_RARE_METAL_ALLOY 5&PID_GUNPOWDER_CLASS_III 25@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_4_7MM_CASELESS_DE 125@exp 1000 }
{148}{}{SEC@@@@PID_RUSTED_METAL_PARTS 2&PID_FUSE 5&PID_GUNPOWDER_CLASS_I 4&PID_ELECTRONIC_PARTS 2@PID_WORK_BENCH_V 1@PID_SMALL_ENERGY_CELL_DE 100@exp 50 }
{149}{}{SEC@@@@PID_RUSTED_METAL_PARTS 10&PID_FUSE 25&PID_GUNPOWDER_CLASS_I 20&PID_ELECTRONIC_PARTS 10@PID_WORK_BENCH_V 1@PID_SMALL_ENERGY_CELL_DE 500@exp 250 }
{150}{}{MFC@@@SK_SCIENCE 120@PID_REFINED_URANIUM 5&PID_GOLD 2&PID_FUSE 5&PID_GOOD_METAL_PARTS 2&PID_ELECTRONIC_PARTS 2@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_MICRO_FUSION_CELL_DE 100@exp 120 }
{151}{}{MFC@@@SK_SCIENCE 120@PID_REFINED_URANIUM 25&PID_GOLD 10&PID_FUSE 25&PID_GOOD_METAL_PARTS 10&PID_ELECTRONIC_PARTS 10@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_MICRO_FUSION_CELL_DE 500@exp 600 }
{152}{}{RAD Ammo@@@SK_SCIENCE 120@PID_REFINED_URANIUM 5&PID_GOLD 2&PID_FUSE 5&PID_GOOD_METAL_PARTS 2&PID_ELECTRONIC_PARTS 2@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_RADAMMO_DE 100@exp 120 }
{153}{}{RAD Ammo@@@SK_SCIENCE 120@PID_REFINED_URANIUM 25&PID_GOLD 10&PID_FUSE 25&PID_GOOD_METAL_PARTS 10&PID_ELECTRONIC_PARTS 10@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_RADAMMO_DE 500@exp 600 }
{154}{}{Ene Ammo@@@SK_SCIENCE 120@PID_REFINED_URANIUM 5&PID_GOLD 2&PID_FUSE 5&PID_GOOD_METAL_PARTS 2&PID_ELECTRONIC_PARTS 2@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_ENEAMMO_DE 100@exp 120 }
{155}{}{Ene Ammo@@@SK_SCIENCE 120@PID_REFINED_URANIUM 25&PID_GOLD 10&PID_FUSE 25&PID_GOOD_METAL_PARTS 10&PID_ELECTRONIC_PARTS 10@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_ENEAMMO_DE 500@exp 600 }
{156}{}{Exp Rocket@@@SK_SCIENCE 120@PID_RUSTED_METAL_PARTS 5&PID_GUNPOWDER_CLASS_I 5&PID_FUSE 4&PID_SCRAP 4&PID_ELECTRONIC_PARTS 3@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_EXPLOSIVE_ROCKET_DE 10@exp 80 }
{157}{}{Rocket AP@@@SK_SCIENCE 120@PID_GOOD_METAL_PARTS 5&PID_GUNPOWDER_CLASS_II 6&PID_FUSE 4&PID_SCRAP 4&PID_ELECTRONIC_PARTS 3@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_ROCKET_AP_DE 10@exp 80 }
{158}{}{RAD Rocket@@@SK_SCIENCE 160@PID_HIGHT_QUALITY_METAL_PARTS 2&PID_GUNPOWDER_CLASS_III 5&PID_REFINED_URANIUM 5&PID_ELECTRONIC_PARTS 5@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_RRAD 10@exp 120 }
{159}{}{Ele Rocket@@@SK_SCIENCE 160@PID_HIGHT_QUALITY_METAL_PARTS 2&PID_GUNPOWDER_CLASS_III 5&PID_REFINED_URANIUM 5&PID_ELECTRONIC_PARTS 5@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_RELE 10@exp 120 }
{160}{}{Flamethrower Fuel@@@SK_BIG_GUNS 40&SK_SCIENCE 40@PID_RUSTED_METAL_PARTS 2&PID_SCREWS 1&PID_SCRAP 1&PID_ROENTGEN_RUM 2@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_FLAMETHROWER_FUEL_DE 50@exp 30 }
{161}{}{Flamethrower Fuel MK2@@@SK_BIG_GUNS 100&SK_SCIENCE 80@PID_GOOD_METAL_PARTS 2&PID_SCREWS 2&PID_SCRAP 2&PID_ROENTGEN_RUM 1&PID_FUELF 1@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_FLAMETHROWER_FUEL_MK_II_DE 50@exp 60 }
{162}{}{Combat LJ@@@SK_SCIENCE 70&SK_REPAIR 70@PID_LEATHER_JACKET_DE 1&PID_BRAHMIN_SKIN 1&PID_GECKO_LEATHER 1&PID_PART_OF_ROPE 2@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_CURED_LEATHER_ARMOR_DE 1@exp 70 }
{163}{}{Leather Armor@@@SK_SCIENCE 70&SK_REPAIR 70@PID_GECKO_LEATHER 3&PID_BRAHMIN_SKIN 2&PID_PART_OF_ROPE 4@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_LEATHER_ARMOR_DE 1@exp 70 }
{164}{}{Leather Armor Mk2@@@SK_SCIENCE 100&SK_REPAIR 100@PID_LEATHER_ARMOR_DE 1&PID_GOLDEN_GECKO_SKIN 2&PID_GECKO_LEATHER 2&PID_PART_OF_ROPE 2@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_LEATHER_ARMOR_MK_II_DE 1@exp 50 }
{165}{}{Leather Armor Gecko@@@SK_SCIENCE 100&SK_REPAIR 100@PID_LEATHER_ARMOR_DE 1&PID_FIRE_GECKO_LEATHER 4&PID_GOLDEN_GECKO_SKIN 2&PID_PART_OF_ROPE 2@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_LEATHER_GECKO_DE 1@exp 50 }
{166}{}{Metal Armor@@@SK_SCIENCE 100&SK_REPAIR 140@PID_SCRAP 4&PID_HIGHT_QUALITY_METAL_PARTS 4@PID_BLACKSMITH_FURNANCE_I 1&PID_KEY_PACKAGE 1@PID_METAL_ARMOR_DE 1@exp 100 }
{167}{}{Metal Armor Mk2@@@SK_SCIENCE 100&SK_REPAIR 140@PID_METAL_ARMOR_DE 1&PID_SCRAP 2&PID_HIGHT_QUALITY_METAL_PARTS 2&PID_PACKAGE_OF_PARTS 2@PID_BLACKSMITH_FURNANCE_I 1&PID_KEY_PACKAGE 1@PID_METAL_ARMOR_MK_II_DE 1@exp 50 }
{168}{}{Tesla Armor@@@SK_SCIENCE 100&SK_REPAIR 160@PID_METAL_ARMOR_DE 1&PID_ELECTRONIC_PARTS 5&PID_HIGHT_QUALITY_METAL_PARTS 2&PID_ELECTRONIC_PACKAGE 2&PID_GOLD 2@PID_PRODUCTION_MACHINE_I 1&PID_KEY_PACKAGE 1@PID_TESLA_ARMOR_DE 1@exp 50 }
{169}{}{Combat Armor@@@SK_SCIENCE 120&SK_REPAIR 180@PID_HIGHT_QUALITY_METAL_PARTS 3&PID_HIGHT_QUALITY_METAL_ALLOY 4&PID_FIRE_GECKO_LEATHER 4&PID_FIBERS 4@PID_PRODUCTION_MACHINE_I 1&PID_EZTENDED_KEY_PACK 1@PID_CA_1 1@exp 400 }
{170}{}{Combat Armor mk2@@@SK_SCIENCE 120&SK_REPAIR 200@PID_RARE_METAL_PARTS 2&PID_RARE_METAL_ALLOY 2&PID_FIRE_GECKO_LEATHER 1&PID_FIBERS 2&PID_CA_1 1@PID_PRODUCTION_MACHINE_I 1&PID_EZTENDED_KEY_PACK 1@PID_CAMKII_1 1@exp 500 }
{171}{}{Bludgeon@@@@PID_RUSTED_METAL_PARTS 1@PID_BLACKSMITH_FURNANCE_I 1@PID_CLUB_DE 1@exp 5 }
{172}{}{CrowBar@@@@PID_RUSTED_METAL_PARTS 1@PID_BLACKSMITH_FURNANCE_I 1@PID_CROWBAR_DE 1@exp 5 }
{173}{}{Switchblade@@@@PID_RUSTED_METAL_PARTS 1@PID_BLACKSMITH_FURNANCE_I 1@PID_SWITCHBLADE_DE 1@exp 5 }
{174}{}{Sharpened stake@@@@PID_WOOD 1@PID_KNIFE_DE 1@PID_SHARPENED_POLE_DE 1@exp 5 }
{175}{}{Knuckle-duster@@@@PID_RUSTED_METAL_PARTS 1@PID_BLACKSMITH_FURNANCE_I 1@PID_BRASS_KNUCKLES_DE 1@exp 5 }
{176}{}{Boxing Gloves@@@SK_UNARMED 70@PID_BRAHMIN_SKIN 1&PID_PART_OF_ROPE 2@PID_WORK_BENCH_I 1@PID_BOXING_GLOVES_DE 1@exp 20 }
{177}{}{Plated Boxing Gloves@@@SK_UNARMED 70@PID_BOXING_GLOVES_DE 1&PID_GOOD_METAL_PARTS 1@PID_WORK_BENCH_I 1@PID_PLATED_BOXING_GLOVES_DE 1@exp 20 }
{178}{}{Combat Knife@@@SK_UNARMED 60@PID_GOOD_METAL_PARTS 1&PID_WOOD 1@PID_WORK_BENCH_I 1@PID_COMBAT_KNIFE_DE 1@exp 20 }
{179}{}{Wakizashi Blade@@@SK_UNARMED 90&SK_SCIENCE 60@PID_HIGHT_QUALITY_METAL_PARTS 2@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_WAKIZASHI_BLADE_DE 1@exp 30 }
{180}{}{Spear@@@SK_UNARMED 60@PID_SHARPENED_POLE_DE 2&PID_RUSTED_METAL_PARTS 1@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_SPEAR_DE 1@exp 20 }
{181}{}{Sharp Spear@@@SK_UNARMED 60&SK_SCIENCE 60@PID_SPEAR_DE 1&PID_FLINT 1@PID_KNIFE_DE 1@PID_SHARP_SPEAR_DE 1@exp 5 }
{182}{}{Bat@@@SK_UNARMED 60&SK_SCIENCE 60@PID_WOOD 2@PID_KNIFE_DE 1@PID_LOUISVILLE_SLUGGER_DE 1@exp 5 }
{183}{}{Spiked Knuckle-duster@@@SK_UNARMED 90&SK_SCIENCE 60@PID_BRASS_KNUCKLES_DE 1&PID_HIGHT_QUALITY_METAL_PARTS 1@PID_BLACKSMITH_FURNANCE_I 1&PID_KEY_PACKAGE 1@PID_SPIKED_KNUCKLES_DE 1@exp 30 }
{184}{}{Power Fist@@@SK_UNARMED 120&SK_SCIENCE 80@PID_HIGHT_QUALITY_METAL_PARTS 2&PID_ELECTRONIC_PACKAGE 2&PID_ELECTRONIC_PARTS 3@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_POWER_FIST_DE 1@exp 100 }
{185}{}{Frag Grenade@@@SK_THROWING 120&SK_SCIENCE 80@PID_GUNPOWDER_CLASS_II 5&PID_GOOD_METAL_PARTS 5&PID_PACKAGE_OF_PARTS 1&PID_SCRAP 5@PID_WORK_BENCH_I 1&PID_KEY_PACKAGE 1@PID_FRAG_GRENADE_DE 15@exp 50 }
{186}{}{Throwing Knife@@@SK_THROWING 60&SK_SCIENCE 60@PID_RUSTED_METAL_PARTS 5@PID_BLACKSMITH_FURNANCE_I 1@PID_THROWING_KNIFE_DE 10@exp 20 }
{187}{}{Ripper@@@SK_UNARMED 120&SK_SCIENCE 100@PID_HIGHT_QUALITY_METAL_PARTS 4&PID_PURIFIED_METAL_ALLOY 4&PID_ELECTRONIC_PARTS 4&PID_ELECTRONIC_PACKAGE 2@PID_WORK_BENCH_I 1&PID_EZTENDED_KEY_PACK 1@PID_RIPPER_DE 1@exp 100 }
{188}{}{Cattle Prod@@@SK_UNARMED 120&SK_SCIENCE 100@PID_PURIFIED_METAL_ALLOY 4&PID_ELECTRONIC_PARTS 4&PID_ELECTRONIC_PACKAGE 2&PID_TUBE2 2@PID_WORK_BENCH_I 1&PID_EZTENDED_KEY_PACK 1@PID_CATTLE_PROD_DE 1@exp 100 }
{189}{}{Super Cattle Prod@@@SK_UNARMED 120&SK_SCIENCE 100@PID_CATTLE_PROD_DE 1&PID_BLUE_CHIP 1&PID_ELECTRONIC_PACKAGE 2@PID_WORK_BENCH_I 1&PID_EZTENDED_KEY_PACK 1@PID_SUPER_CATTLE_PROD_DE 1@exp 20 }
{190}{}{Plasma Grenade@@@SK_THROWING 160&SK_SCIENCE 140@PID_MICRO_FUSION_CELL_DE 15&PID_HIGHT_QUALITY_METAL_ALLOY 5&PID_ELECTRONIC_PARTS 5&PID_GUNPOWDER_CLASS_II 15@PID_PRODUCTION_MACHINE_IV 1&PID_EZTENDED_KEY_PACK 1@PID_PLASMA_GRENADE_DE 15@exp 150 }
{191}{}{Pulse Grenade@@@SK_THROWING 190&SK_SCIENCE 180@PID_MICRO_FUSION_CELL_DE 20&PID_RARE_METAL_ALLOY 3&PID_ELECTRONIC_PARTS 5&PID_GUNPOWDER_CLASS_III 15&PID_GOLD 5@PID_PRODUCTION_MACHINE_IV 1&PID_EZTENDED_KEY_PACK 1@PID_PULSE_GRENADE_DE 15@exp 200 }
{192}{}{Lockpick Set@@@@PID_BRAHMIN_SKIN 3&PID_GOOD_METAL_PARTS 2&PID_SCRAP 2@PID_WORK_BENCH_I 1@PID_LOCKPICKS 1@exp 50 }
{193}{}{Exp.Lockpick Set @@@@PID_GOOD_METAL_PARTS 2&PID_SCREWS 5&PID_LOCKPICKS 1@PID_WORK_BENCH_I 1@PID_EXP_LOCKPICK_SET 1@exp 60 }
{194}{}{Super Stimpak@@@SK_DOCTOR 120&SK_FIRST_AID 180@PID_STIMPAK 1&PID_BIO_GEL 1&PID_WHITE_FLOWER 1&PID_YELLOWFLOWER 1@PID_WORK_BENCH_I 1@PID_SUPER_STIMPAK 1@exp 20 }
{195}{}{Stimpak@@@@PID_BIO_GEL 5&PID_XANDER_ROOT 10&PID_BROC_FLOWER 10&PID_HYPODERMIC_NEEDLE 5@PID_WORK_BENCH_I 1@PID_STIMPAK 5@exp 50 }
{196}{}{Package of parts@@@SK_SCIENCE 100@PID_SCRAP 5&PID_GOOD_METAL_PARTS 2@PID_KEY_PACKAGE 1@PID_PACKAGE_OF_PARTS 1@exp 5 }
{197}{}{Bio Medic Gel@@@SK_DOCTOR 50&SK_FIRST_AID 50@PID_WHITE_FLOWER 5&PID_YELLOWFLOWER 5&PID_HIGHT_QUALITY_MINERAL 1@@PID_BIO_GEL 10@exp 50 }
{198}{}{Healing Powder@@@SK_DOCTOR 25&SK_FIRST_AID 25@PID_XANDER_ROOT 3&PID_BROC_FLOWER 3@@PID_HEALING_POWDER 3@exp 50 }
{199}{}{Super slage @@@SK_UNARMED 150&SK_SCIENCE 150@PID_SLEDGEHAMMER_DE 1&PID_BLUE_CHIP 3&PID_ELECTRONIC_PACKAGE 4&PID_GOOD_METAL_ALLOY 3&PID_RARE_METAL_PARTS 2&PID_PACKAGE_OF_PARTS 3@PID_KEY_PACKAGE 1@PID_SUPER_SLEDGE_DE 1@exp 150 }
{200}{}{slagehammer @@@SK_UNARMED 70&SK_SCIENCE 70@PID_RUSTED_METAL_PARTS 2&PID_WOOD 2@PID_KEY_PACKAGE 1@PID_SLEDGEHAMMER_DE 1@exp 150 }
{201}{}{Gunpowder Class 1 X10@@@@PID_MINERAL_SULFUR 10@PID_WORK_BENCH_V 1@PID_GUNPOWDER_CLASS_I 10@exp 500 }
{202}{}{Gunpowder Class 2 X10@@@SK_SCIENCE 60@PID_MINERAL_SULFUR 20@PID_WORK_BENCH_V 1@PID_GUNPOWDER_CLASS_II 10@exp 500 }
{203}{}{Gunpowder Class 3 X10@@@SK_SCIENCE 100@PID_MINERAL_SULFUR 10&PID_HIGHT_QUALITY_MINERAL 10@PID_WORK_BENCH_V 1@PID_GUNPOWDER_CLASS_III 10@exp 500 }
{204}{}{Rusted Metal Parts x5@@@@PID_IRON_ORE 10&PID_COAL 5@PID_BLACKSMITH_FURNANCE_I 1@PID_RUSTED_METAL_PARTS 5@exp 500 }
{205}{}{Gatling Laser@@@SK_ENERGY_WEAPONS 240&SK_SCIENCE 200&ST_LEVEL 30@PID_MINIGUN_DE 1&PID_ELECTRONIC_PACKAGE 5&PID_HIGHT_QUALITY_METAL_PARTS 3&PID_HIGHT_QUALITY_METAL_ALLOY 6&PID_RARE_METAL_PARTS 4&PID_FUSE 6@PID_PRODUCTION_MACHINE_IV 1&PID_EZTENDED_KEY_PACK 1@PID_GATLING_LASER_DE 1@exp 200 }
{206}{}{Dynamite@@@SK_TRAPS 140&SK_SCIENCE 140@PID_PACKAGE_OF_PARTS 3&PID_GUNPOWDER_CLASS_II 10@PID_WORK_BENCH_I 1@PID_DYNAMITE 1@exp 50 }
{207}{}{Plastic@@@SK_SCIENCE 180&SK_TRAPS 200@PID_PACKAGE_OF_PARTS 3&PID_GUNPOWDER_CLASS_III 10&PID_BLUE_CHIP 1&PID_COAL 2&PID_RARE_MINERAL 1@PID_WORK_BENCH_I 1@PID_PLASTIC_EXPLOSIVES 1@exp 100 }
{208}{}{Fire Barrel@@@SK_REPAIR 40&SK_SCIENCE 30@PID_GOOD_METAL_ALLOY 5&PID_SCREWS 5@PID_BLACKSMITH_FURNANCE_I 1&PID_SLEDGEHAMMER_DE 1@PID_FIREBARREL 1@exp 50 }
{209}{}{Smoke Granade@@@SK_THROWING 120&SK_SCIENCE 140@PID_RUSTED_METAL_PARTS 5&PID_COMPENSATING_SPRING 5&PID_GUNPOWDER_CLASS_I 5&PID_HIGHT_QUALITY_MINERAL 5@PID_WORK_BENCH_V 1@PID_SMOKE_GRENADE 5@exp 250 }
{210}{}{Mustard Gas Granade@@@SK_THROWING 120&SK_SCIENCE 140@PID_RUSTED_METAL_PARTS 5&PID_COMPENSATING_SPRING 5&PID_GUNPOWDER_CLASS_I 5&PID_MINERAL_SULFUR 10&PID_HIGHT_QUALITY_MINERAL 5&PID_ROENTGEN_RUM 5@PID_WORK_BENCH_V 1@PID_MUSTARD_GAS_GRENADE 5@exp 500 }
{211}{}{Fuse@@@SK_SCIENCE 60@PID_GOOD_METAL_PARTS 1&PID_ELECTRONIC_PARTS 1@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_FUSE 1@exp 20 }
{212}{}{Fuse x10@@@SK_SCIENCE 60@PID_GOOD_METAL_PARTS 10&PID_ELECTRONIC_PARTS 10@PID_WORK_BENCH_V 1&PID_KEY_PACKAGE 1@PID_FUSE 10@exp 200 }
{213}{}{Screws x20@@@SK_SCIENCE 60@PID_RUSTED_METAL_PARTS 10@PID_WORK_BENCH_V 1@PID_SCREWS 20@exp 50 }
{214}{}{Compenstating springs x10@@@SK_SCIENCE 60@PID_SCRAP 10@PID_WORK_BENCH_V 1@PID_COMPENSATING_SPRING 10@exp 100 }
{215}{}{Defibtrilator@A defibrilator to reanimate dead critters.@@PLAYER_PROFESSION 3@PID_GOOD_METAL_PARTS 2&PID_HIGHT_QUALITY_METAL_ALLOY 1&PID_SCREWS 1&PID_PACKAGE_OF_PARTS 2&PID_ELECTRONIC_PACKAGE 1&PID_FUSE 1@PID_SCREWDRIVER_CROSS2 1&PID_WORK_BENCH_I 1@PID_DEFIBRIL 1@exp 200 }
{216}{}{Sandbag @@@SK_SCIENCE 40&ST_STRENGTH 3@PID_BRAHMIN_SKIN 1@PID_SHOVEL 1@PID_WOREK_Z_PIASKIEM 1@exp 1 }