{100}{}{Widzisz mê¿czyznê w skórzanej zbroi.}
{101}{}{To Kaga.}
{102}{}{Jest ubrany w skórzan¹ zbrojê i ma denerwuj¹cy zwyczaj mówienia o sobie w trzeciej osobie.}
{103}{}{To ju¿ twoje ostatnie spotkanie z Kag¹.}
{104}{}{Jak ju¿ Kaga ciê zabije, pójdzie zrównaæ z ziemi¹ ca³e Arroyo.}
{105}{}{Poczuj gniew Kagi!}
{106}{}{Jestem Kaga Wspania³y!}
{107}{}{Kaga budzi strach w sercach wrogów.}
{108}{}{Kaga zrobi sobie z twojej g³owy trofeum.}
{109}{}{Poddaj siê, a umrzesz szybk¹ œmierci¹.}
{110}{}{Kaga jeszcze wróci!}
{111}{}{Wielkiego Kagi nie mo¿na zabiæ!}
{112}{}{Masz szczêœcie, ¿e Kaga musi siê teraz czymœ zaj¹æ.}
{113}{}{Kaga jeszcze ciê znajdzie.}
