{100}{}{Widzisz mê¿czyznê w pancerzu wspomaganym MKII. Nie wygl¹da na przyjaŸnie nastawionego.}
{101}{}{To Kaga we wspomaganym pancerzu MKII.}
{102}{}{Chodz¹cy czo³g.}
{103}{}{Mam ju¿ doœæ tego poœcigu. Pora to skoñczyæ.}
{104}{}{To ju¿ ostatnie twoje spotkanie z Kag¹.}
{105}{}{Nie masz szans z Kag¹.}
{106}{}{Przygotuj siê na pobyt w zaœwiatach.}
{107}{}{To by³a wspania³a walka.}
{108}{}{Na pustkowiach jest tylko miejsce dla Kagi.}
{109}{}{Kiedy ciê zabijê, to ja bêdê najgroŸniejsz¹ osob¹ w tej czêœci pustkowi.}
{110}{}{Nie mogê siê ju¿ doczekaæ powrotu do Arroyo... i wymordowania wszystkich mieszkañców}
{111}{}{Po twojej œmierci Kaga bêdzie s³awny.}
