{100}{}{Widzisz mê¿czyznê w stalowej zbroi.}
{101}{}{To Kaga.}
{102}{}{Tak, to Kaga Niezbyt-Wspania³y. Ma stalow¹ zbrojê i oczywiœcie chce ciê zabiæ.}
{103}{}{Znowu ty!}
{104}{}{Mam ju¿ doœæ ci¹g³ego wpadania na ciebie.}
{105}{}{Dziecko Przeznaczenia - niech ciê szlag!}
{106}{}{Pora wreszcie to skoñczyæ.}
{107}{}{Po¿a³ujesz, ¿e Kaga stan¹³ na twojej drodze!}
{108}{}{Moje umiejêtnoœci wzros³y od naszego ostatniego spotkania.}
{109}{}{To ju¿ chyba jakaœ ponura tradycja.}
{110}{}{Kaga musi jeszcze trochê poæwiczyæ.}
{111}{}{Kaga jeszcze ciê znajdzie.}
