{100}{}{Widzisz mê¿czyznê w pancerzu bojowym.}
{101}{}{Widzisz Kagê w pancerzu bojowym.}
{102}{}{Ma na sobie pancerz bojowy i zdaje siê byæ nieŸle uzbrojony.}
{103}{}{Tym razem jestem przygotowany na spotkanie z tob¹.}
{104}{}{Dziecko Przeznaczenia nigdy ju¿ nie wróci do Arroyo!}
{105}{}{Kaga ciê zmia¿d¿y!}
{106}{}{Kaga nie lêka siê nikogo!}
{107}{}{Stój w miejscu, Kaga chce dobrze wycelowaæ.}
{108}{}{Jeszcze siê spotkamy!}
{109}{}{Kaga nigdy nie da ci spokoju.}
{110}{}{Kaga musi jeszcze trochê poæwiczyæ.}
