{100}{}{Widzisz sk¹po odzianego mê¿czyznê.}
{101}{}{To Kaga.}
{103}{}{Ma na sobie spodnie i chyba pochodzi z któregoœ z tutejszych plemion.}
{104}{}{To ja powinienem byæ Dzieckiem Przeznaczenia!}
{105}{}{Jak Arroyo œmia³o skazaæ mnie na wygnanie?!}
{106}{}{Zemszczê siê na TOBIE!}
{107}{}{Kaga wyœle ciê na œcie¿kê œmierci.}
{108}{}{Jeszcze siê spotkamy!}
{109}{}{Jestem niepokonany!}
{110}{}{Zrobiê wszystko, ¿eby tylko zobaczyæ twój upadek.}
