#Tenhle soubor pøeloil Birdman, Birdman@post.cz, http://www.mujweb.cz/www/birdman, 0604 540689
# 
# FALLOUT BATTLECRIES
# When the Bomb Drops, the real fun begins - So let's get to Work!!!
#
# Version 1.0  May 13, 1997  Scott Bennie
#         1.1  May 14, 1997  Chris Taylor (edits and line number change)
#         1.2  June 19, 1997 Leonard, Jason, Chris (edits)
#
# Version 2.0 July 29, 1998 Feargus Urquhart - modified for Fallout 2, most text has been rearranged, however some lines were still authored by the above people.
#
#  READ THIS!! READ THIS!! READ THIS!! READ THIS!!
#
#  This new file is different than the old one in that body locations are listed in a generic fashion first and are only listed for particular types of characters.  This is followed by a list of generic characters, which is then followed by the more specific taunts and party member taunts.
#
#
####################################################################################
#
#                    Generic Body Parts
#
####################################################################################
#                     
#                     Notes
#                     
#                     00-09 Hit in Head
#                     10-19 Hit in Left Arm
#                     20-29 Hit in Right Arm
#                     30-59 Hit in Torso (Generic Non-Called Shot Hit)
#                     60-69 Hit in Right Leg
#                     70-79 Hit in Left Leg
#                     80-89 Hit in Eyes
#                     90-99 Hit in Groin
#
#                     1000 Wimpy Person
#                     1100 Normal Person
#                     1200 Tough Person
#                     1300 Berserk Person
#                     1400 Robot
#                     1500 Primitive
#                     1600 Ghoul
#                     1700 Raider (Khan)
#                     1800 Junkie
#
####################################################################################
#
#
############################################
# 1000 Wimpy Person
############################################
#
# target hit in head
#
{1000}{}{Mùj oblièej! Mùj oblièej!}
{1001}{}{Au! To bolí!}
{1002}{}{Jauvajs!! Potøebuju ledovı obklad}
#
# target hit in left arm
#
{1010}{}{Au, moje ruka}
{1011}{}{Au!}
{1012}{}{Zlomili mi ruku!}
#
# target hit in right arm
#
{1020}{}{Au, moje ruka}
{1021}{}{Ahhhh!}
{1022}{}{Mùj boe! Moje ruka!}
#
# target hit in torso
#
{1030}{}{Au! To fakt bolí!}
{1031}{}{Asi omdlím...}
{1032}{}{Au!}
{1033}{}{Uf!}
{1034}{}{To bolí!}
{1035}{}{Nech mì bıt!}
{1036}{}{Ohhh, bolest!}
#
# target hit in right leg
#
{1060}{}{Au, moje noha!}
{1061}{}{Moje koleno!}
{1062}{}{Au!}
#
# target hit in left leg
#
{1070}{}{Au, moje noha!}
{1071}{}{Moje koleno!}
{1072}{}{Aaaarrrrggghhh!}
#
# target hit in eyes
#
{1080}{}{Au!! Moje oèi!}
{1081}{}{Mùj oblièej! Moje oèi! Arrrrgh!}
{1082}{}{Moje oèi!}
#
# target hit in groin
#
{1090}{}{Ooooooooo, mùj rozkrok! Ooooooo...}
{1091}{}{Aùùù...To bolí!!!}
{1092}{}{Urp!}
{1093}{}{Urp! jaùùùùù...}
{1094}{}{Nemùu...dıchat...}
{1095}{}{Bolí, bolí...}
#
############################################
# 1100 Normal Person
############################################
#
# target hit in head
#
{1100}{}{Zatracenì!}
{1101}{}{Moje lebka, au!}
{1102}{}{Mùj oblièej! Mùj oblièej!}
#
# target hit in left arm
#
{1110}{}{Aggghhh! Moje ruka}
{1111}{}{Moje ruka!}
{1112}{}{Sakra, to bolí!}
#
# target hit in right arm
#
{1120}{}{Aggghhh! Moje ruka}
{1121}{}{Moje ruka!}
{1122}{}{}
#
# target hit in torso
#
{1130}{}{}
{1131}{}{Uf!}
{1132}{}{Jauvajs!}
{1133}{}{Uf! Mám zlomenı ebro!}
{1134}{}{Ugh! To bolí!}
{1135}{}{Zatracenì! Proklínám tì!}
{1136}{}{Argh!}
{1138}{}{Oh, moje ebra!}
{1139}{}{Au!!!}
{1140}{}{Uf!}
#
# target hit in right leg
#
{1160}{}{Aggghhh! Moje noha}
{1161}{}{Moje noha!}
{1162}{}{A koleno je v prdeli}
#
# target hit in left leg
#
{1170}{}{Aggghhh! Moje noha}
{1171}{}{Moje noha!}
{1172}{}{A koleno je v prdeli}
#
# target hit in eyes
#
{1180}{}{Aggghhh! Jsem slepı!}
{1181}{}{Moje oèi! Moje oèi!}
{1182}{}{Moje oko! Za to mi zaplatíš!}
#
# target hit in groin
#
{1190}{}{Oooooo, mùj rozkrok!}
{1191}{}{Oooooooooo!}
{1192}{}{Nemùu...dıchat...}
{1193}{}{Erg! Pøímo do rodinnejch pokladù!}
{1194}{}{Bolí, bolí...}
{1195}{}{Zatracenì! To bolí!}
#
############################################
# 1200 Tough Person
############################################
#
# target hit in head
#
{1200}{}{Au! Ty zmrde!}
{1201}{}{Mám zlomenej nos!}
{1202}{}{Utrhnu ti hlavu!}
#
# target hit in left arm
#
{1210}{}{Au, moje ruka}
{1211}{}{Tady nìkdo udìlal nejvìtší chybu svıho mizernıho ivota!}
{1212}{}{Moje ruka!}
#
# target hit in right arm
#
{1220}{}{Au, moje ruka}
{1221}{}{Tady nìkdo udìlal nejvìtší chybu svıho mizernıho ivota!}
{1222}{}{Moje ruka!}
#
# target hit in torso
#
{1230}{}{Urp!}
{1231}{}{Uf!}
{1232}{}{Jauvajs!}
{1233}{}{}
{1234}{}{Ugh! To bolí!}
{1235}{}{Jauvajs!}
{1236}{}{Argh!}
{1237}{}{Oh, asi mám zlomenı ebro!}
{1238}{}{Au!!! Moje bøicho!}
{1239}{}{Uf!}
#
# target hit in right leg
#
{1260}{}{Au, moje noha!}
{1261}{}{Klidnì mùu sedìt, stejnì tì zabiju!}
{1262}{}{Moje koleno!}
#
# target hit in left leg
#
{1270}{}{Au, moje noha!}
{1271}{}{Klidnì mùu sedìt, stejnì tì zabiju!}
{1272}{}{Moje koleno!}
#
# target hit in eyes
#
{1280}{}{Nevidím!}
{1281}{}{Tahle bitka špatnì dopadne. Pro tebe.}
{1282}{}{Tak tohle byla fakt sprostá rána. O nièem.}
#
# target hit in groin
#
{1290}{}{Oooooo, mùj rozkrok!}
{1291}{}{To ucítím tak pozítøí, jestli vùbec.}
{1292}{}{}
{1293}{}{Urp!}
{1294}{}{}
{1295}{}{}
#
############################################
# 1300 Berserk Person
############################################
#
# target hit in head
#
{1300}{}{Ha! To bude jizvièka! Díky.}
{1301}{}{Hladina nasranosti roste, tady si to nìkdo krutì odskáèe...}
{1302}{}{Zkus to znovu, prase!}
#
# target hit in left arm
#
{1310}{}{Moje ruka? Jo, byla to moje ruka... nepotøebuju ji.}
{1311}{}{}
{1312}{}{Já mám zlomenou ruku, ale tobì zlomím krk, ty mrtvolo.}
#
# target hit in right arm
#
{1320}{}{}
{1321}{}{Jenom škrábnutí...}
{1322}{}{Já mám sice zlomenou ruku, ale tobì zlomím krk.}
#
# target hit in torso
#
{1330}{}{Trocha krve, to nic není.}
{1331}{}{Uf! Za to ti vytrhnu støeva a uškrtím tì s nima!}
{1332}{}{Au!}
{1333}{}{Mám rád, kdy to bolí!}
{1334}{}{Miluju ten zvuk, co vydávaj praskající ebírka!}
{1335}{}{To nic není!}
{1336}{}{Arg!}
#
# target hit in right leg
#
{1360}{}{Miluju zvuk praskajících kostí.}
{1361}{}{}
{1362}{}{Já mám zlomenou nohu, ale tobì zlomím krk.}
#
# target hit in left leg
#
{1370}{}{Miluju zvuk praskajících kostí.}
{1371}{}{}
{1372}{}{Já mám zlomenou nohu, ale tobì zlomím krk, ty mrtvolo.}
#
# target hit in eyes
#
{1380}{}{Hej, nevidím?!}
{1381}{}{Nevidím. No, aspoò to bude fér boj.}
{1382}{}{Moje oèi, do prdele. Kampak se zakutálely?}
#
# target hit in groin
#
{1390}{}{Oof, mùj rozkrok!}
{1391}{}{Tak to nebylo hezkı, hajzle.}
{1392}{}{}
{1393}{}{}
{1394}{}{No jestli to chceš takhle, tak pojï.}
{1395}{}{Jaúú!}
#
############################################
# 1400 Robot 
############################################
#
# target hit in CPU
#
{1400}{}{Pozor, zaregistrováno selhání CPU!}
{1401}{}{Pozor! CPU poškozeno! Vıkon procesoru nedostateènı!}
{1402}{}{Pozor! CPU poškozeno! Zapojuji záloní procesory!}
#
# target hit in left manipulator
#
{1410}{}{Zaregistrována porucha manipulátoru!}
{1411}{}{Jednotka zasaena do levého manipulátoru. Vyhodnocuji poškození...}
{1412}{}{Zásah manipulátoru. Škody minimální, funkènost na 97%.}
#
# target hit in right manipulator
#
{1420}{}{Zaregistrována porucha manipulátoru!}
{1421}{}{Jednotka zasaena do pravého manipulátoru. Vyhodnocuji poškození...}
{1422}{}{Zásah manipulátoru. Škody minimální, funkènost na 97%.}
#
# target hit in frame
#
{1430}{}{Zásah trupu. Pøepoèítávám parametry poškození...}
{1431}{}{Zásah trupu. Interní opravnı systém aktivován...}
{1432}{}{Hlavní struktura pod útokem}
{1433}{}{Pancíø proraen.}
{1434}{}{Hlavní struktura pod útokem. Opravuji}
{1435}{}{Jednotka pod útokem.}
{1436}{}{Provést bojovı manévr.}
{1437}{}{Brzzt!}
{1438}{}{Minimální poškození.}
{1439}{}{Brzzt!}
#
# target hit in right motivator
#
{1460}{}{Zaregistrována porucha motivátoru!}
{1462}{}{Jednotka zasaena do pravého motivátoru. Vyhodnocuji poškození...}
{1463}{}{Zásah motivátoru. Škody minimální, funkènost na 97%.}
#
# target hit in left motivator
#
{1470}{}{Zaregistrována porucha motivátoru!}
{1471}{}{Jednotka zasaena do levého motivátoru. Vyhodnocuji poškození...}
{1472}{}{Zásah motivátoru. Škody minimální, funkènost na 97%.}
#
# target hit in sensors
#
{1480}{}{Senzory zasaeny! Senzory zasaeny!}
{1481}{}{Porucha senzorù! Porucha senzorù!}
{1482}{}{Senzorickı subsystém poškozen, záloní systém nefunkèní...}
#
# target hit in regulator
#
{1490}{}{Regulátor zasaen! Porucha!}
{1491}{}{Regulátor poškozen! Regulátor mimo provoz!}
{1492}{}{Regulátor poškozen! Pøevádím funkci...}
#
#
############################################
# 1500 Primitive
############################################
#
# target hit in head
#
{1500}{}{V moje hlava moc moc zlejch duchù.}
{1501}{}{Já slyším mé pøedky, oni volají mnì. }
{1502}{}{To bude hezká jizva.}
{1503}{}{Jaùùùvajsss!}
{1504}{}{Moje hlava hoøet!}
{1505}{}{To pálí! To pálí!}
{1506}{}{Bolest!}
{1507}{}{Tvoje kouzlo silné.}
{1508}{}{Ty mnì neukradneš duši. Takhle ne.}
{1509}{}{Tvoje magie mnì nezabiješ.}
#
# target hit in left arm
#
{1510}{}{Pouiju na tebe pravou ruku.}
{1511}{}{Jedna ruka mi na tebe staèit!}
{1512}{}{Tvoje bolest bıt ještì vìtší!}
{1513}{}{Já stejnì tolik prstù nepotøebuju.}
{1514}{}{Ta ruka byla stejnì moc dlouhá.}
{1515}{}{Ale ty pøijdeš o obì ruce, slibuju na svı pøedky.}
{1516}{}{Za tohle tì budu zabíjet pomalu.}
{1517}{}{Jau!}
{1518}{}{Tolik krve!}
{1519}{}{Aspoò se mám doma èím pochlubit.}
#
# target hit in right arm
#
{1520}{}{Zabiju tì levou rukou!}
{1521}{}{To máš tak mizernou mušku?}
{1522}{}{Jedna ruka mi na tebe staèí!}
{1523}{}{Já stejnì tolik prstù nepotøebuju.}
{1524}{}{Za tohle tì budu zabíjet pomalu.}
{1525}{}{Ale ty pøijdeš o obì ruce, slibuju na svı pøedky.}
{1526}{}{Ty moji ruku, já tvoji hlavu!}
{1527}{}{Chceš mì ochromit?}
{1528}{}{Za to si zatancuju na tvém hrobì.}
{1529}{}{Budeš umírat dlouho, dlouho.}
#
# target hit in torso
#
{1530}{}{Awwwwwg!}
{1531}{}{Mé vnitønosti hoøí!}
{1532}{}{Bolí mì bøicho!}
{1533}{}{Mí duchové mì opouštìjí.}
{1534}{}{Roztrhli mnì!}
{1535}{}{A iju dost dlouho na to, abych tì mohl zabít.}
{1536}{}{Pøedkové mí, pøicházím!}
{1537}{}{U nikdy neuvidím svou rodnou vesnici...}
{1538}{}{Zemøu hrdì.}
{1539}{}{Mí bratøi mì pomstí!}
{1540}{}{Uff, mám... uff... vyraenı...uff...dech.}
{1541}{}{Vzali mi duši!}
{1542}{}{Tak ty mi chceš ubliovat?!}
{1543}{}{Jsem vykuchanı jako brahmína!}
{1544}{}{Cítím se nedobøe...}
{1545}{}{Necítím nohy... ještì e tak.}
{1546}{}{Uaaaam. Já bych spal.}
{1547}{}{Errrggggg!}
{1548}{}{Au! kch kch uff.}
{1549}{}{Musím dál, musím zabít nepøítele...}
{1550}{}{Temnota mì obchází...}
{1551}{}{Hodina mé smrti se blíí.}
{1552}{}{Šaman mìl pravdu. U se nevrátím.}
{1553}{}{Cizák mì zabil...}
{1554}{}{Jsem mrtvá liška.}
{1555}{}{Mé vnitønosti! Vrate se!}
{1556}{}{Nesmím ztratit èest ani ve chvíli smrti.}
{1557}{}{Proklínám tì! To nemùeš!}
{1558}{}{Hele, podívejte. Tohle jsem mìl k snídani...}
{1559}{}{Uf uf, kam se podìl... uf... všechen vzduch?}
#
# target hit in right leg
#
{1560}{}{Budu se plazit, ale stejnì tì zabiju.}
{1561}{}{Musím zùstat na nohou, musím...}
{1562}{}{Stejnì mi neuteèeš!}
{1563}{}{Ty mì chceš zchromit, zbabìlèe?}
{1564}{}{Awwwwgg!}
{1565}{}{Kost? Tak bílá...}
{1566}{}{Proè nemùu chodit?}
{1567}{}{Arrrrrrgh.}
{1568}{}{Unnhhh.}
{1569}{}{Noha bolí, auauau. AU!}
#
# target hit in left leg
#
{1570}{}{Budu se plazit, ale stejnì tì zabiju.}
{1571}{}{Musím zùstat na nohou, musím...}
{1572}{}{Stejnì mi neuteèeš!}
{1573}{}{Ty mì chceš zchromit, zbabìlèe?}
{1574}{}{Awwwwgg!}
{1575}{}{Kost? Tak bílá...}
{1576}{}{Nemùu chodit... Oh, to bolí!}
{1577}{}{Za to ti seeru tvoji nohu!}
{1578}{}{Jáááùùùùùùùù!}
{1579}{}{Noha pálí jako v ohni.}
#
# target hit in eyes
#
{1580}{}{Temnota je všude kolem mne.}
{1581}{}{Kde jsi?}
{1582}{}{Pomoc, pomozte mi!}
{1583}{}{Ještì tì slyším!}
{1584}{}{Chceš mì oslepit? Zbabìlèe!}
{1585}{}{Mùj zrak byl ukraden!}
{1586}{}{Mùeš mi vzít oèi, ale ne mou odvahu!}
{1587}{}{Pojï blí, a na tebe vidím!}
{1588}{}{Temnota, temnota! ÁÁÁ!}
{1589}{}{Kde mám oko, kde je?!?!!!!}
#
# target hit in groin
#
{1590}{}{U mám stejnì dost mladıch...}
{1591}{}{Nemáš ádnou èest!}
{1592}{}{Stejnì to nepouívám.}
{1593}{}{Svatı duchu, svìt vybuchnul v bolesti!}
{1594}{}{Fuj! To bolelo! Ty zbabìlèe!}
{1595}{}{Vysokım, pískavım hláskem--Jauvajs!}
{1596}{}{Uh, asi si na chvilku sednu...}
{1597}{}{Ty bastarde - za to tì zabiju pomalu, pomalounku.}
{1598}{}{Tady nìkdo nemá zdání o cti, co?}
{1599}{}{Za to tì rozsekám na malinkaté kousíèky, které potom obìtuju duchùm pouštì.}
#
#
############################################
# 1600 Ghoul
############################################ 
#
# target hit in head
#
{1600}{}{Oh, mùj krásnı oblièej}
{1601}{}{Bolí mì mozek.}
{1602}{}{Teï vypadám jako Van Gogh.}
{1603}{}{Sakra, nos je pryè.}
{1604}{}{Hej! To byl mùj poslední zub!}
{1605}{}{Oskalpovali mnì!}
{1606}{}{Radši bych si dal flašku.}
{1607}{}{Dám ti kousek své mysli. Doslova, jenom si utøu ten kousek mozku z košile.}
{1608}{}{Sakra, moje oko. Grrrr.}
{1609}{}{A mi vyhrkly slzy do oka.}
#
# target hit in left arm
#
{1610}{}{Jsem odzbrojenej!}
{1611}{}{ÓÓÓ, bolest, bolí bolí.}
{1612}{}{Ještì mi pár prstù zbıvá.}
{1613}{}{Na *tebe* mi jeden prst staèí.}
{1614}{}{Hmm, tak mám dojem, e ti asi podám ruku.}
{1615}{}{Asi mám vykloubenı rameno. Mùe mi ho dát nìkdo zpátky?}
{1616}{}{Tak, a tenisová kariéra je v háji. Hmm. Sbohem Wimbledone.}
{1617}{}{Zmlátím tì svım pahılem, lumpe!}
{1618}{}{Hej, kde mám prsty? Kde jsou?}
{1619}{}{Øíkejte mi kapitán Hák. Jenom si ještì musím nìjakı sehnat.}
#
# target hit in right arm
#
{1620}{}{Mìl jsem uskoèit doleva.}
{1621}{}{Zlomili mi ruku!}
{1622}{}{Toho budeš litovat! Do støehu!}
{1623}{}{Bijou mì! Bijou mì! A jde jim to!}
{1624}{}{Sbohem Wimbledone. Dám se na šachy.}
{1625}{}{Sieg H... á, radši nic.}
{1626}{}{Jsem odzbrojenej!}
{1627}{}{Na *tebe* mi jeden prst staèí.}
{1628}{}{Hmm, tak tì xmrti dokopu.}
{1629}{}{Ta rukavice stála osmdesát babek! To mi zaplatíš!}
#
# target hit in torso
#
{1630}{}{To jsou *moje* játra! Vra mi je!}
{1631}{}{Ještì kousek doprava, ahhh, to je lepší.}
{1632}{}{Gerrk!}
{1633}{}{Co to tady tak smrdí? Aha, moje støeva.}
{1634}{}{Dík za tracheotomii, hned se mi líp dıchá.}
{1635}{}{./~ ...nechal jsem své srdce.../~}
{1636}{}{Na ebrech jsem lechtivej, nech toho.}
{1633}{}{Slepı støevo stejnì na nic není.}
{1634}{}{Au, øíkal jste, e to akorát trochu píchne, doktore?}
{1635}{}{Arrrgggggh, moje páteø! Vra mi ten obratel!}
{1636}{}{Moje noha, necítím nohy... ještì e tak.}
{1637}{}{Šlo to do bøicha, serante. Nechte mì tady....}
{1638}{}{Plíce jsou pro sráèe.}
{1639}{}{Hej, já mám ebra! Zatím!}
#
# target hit in right leg
#
{1660}{}{Au, moje noha!}
{1661}{}{Za to zaplatíš!}
{1662}{}{Argh! Ty mì nohu, já tobì krk!}
{1663}{}{Zatracenì, a mám po taneèních.}
{1664}{}{A prsty v hajzlu.}
{1665}{}{Inzerát do avíza: Koupím kvalitní nohu, pøípadnì vymìním za znaènì opotøebovanou.}
{1666}{}{Moje boty! Jsou celı od krve! GRRRRRRRRRRR!}
{1667}{}{Hele, mám ostøíhanı nehty.}
{1668}{}{A to jsem si je pøed hodinkou oholil.}
{1669}{}{Za to ti ukousnu koleno!}
#
# target hit in left leg
#
{1670}{}{Moje noha!}
{1671}{}{Mám zmasakrovanou achilovku!}
{1672}{}{Jauvajs! Hej! To byla rána pod pás!}
{1673}{}{Jau, to bolí! Jak by se ti to líbilo, kdybych ti to udìlal já?!}
{1674}{}{Naplácej mi, maminko. Byl jsem škaredej kluk.}
{1675}{}{To se zajizví.}
{1676}{}{Hmm, to je moje krev? Prodám krev, nulka, asi dva litry!}
{1677}{}{Maršal Malinovskij! Maršal Malinovskij!}
{1678}{}{Sakra, budu muset kulhat i na druhou nohu.}
{1679}{}{Ajajajajajáááá jááá mááám nóóóóhùùù v prdeli.}
#
# target hit in eyes
#
{1680}{}{Mám krev v oèích, do psí díry!}
{1681}{}{Moje oko! Za to mi zaplatíš!}
{1682}{}{Bastarde!}
{1683}{}{Kdo zhasnul?}
{1684}{}{Hahaha! To oko bylo sklenìnı!}
{1685}{}{Prasklo jako pøezrálá tøešnièka, co?}
{1686}{}{Hele oko! A sakra, to je moje....}
{1687}{}{Dokáu se orientovat jenom podle zvuku!}
{1688}{}{Jejky! Moje oko! Moje oko! Dej ho sem!}
{1689}{}{Oslepili mì. Asi se mì bojí.}
#
# target hit in groin
#
{1690}{}{Rytíøskı jednání. Fakt.}
{1691}{}{Jáááááááááááááááááááùùùùùùùùùùùù!!!!!!!!!!!}
{1692}{}{Uhhhhhhhhh. Uf.}
{1693}{}{Asi si na chvilku lehnu.}
{1694}{}{Suspenzor. Musím si poøídit suspenzor.}
{1695}{}{Hmm, a s mım spoleèenskım ivotem je konec.}
{1693}{}{Musím si na chvíli sednout. Tak na rok, dva.}
{1694}{}{Kdyby byly nìjakı ghoulky, byly by na tebe pìknì nasranı.}
{1695}{}{Ooooh. To bolelo. Dost.}
{1696}{}{Hele, nebylo to do... Jo, bylo. ÁÁÁ!}
{1697}{}{Hele, co se to tu kutálí za koule? Moje koule...}
{1698}{}{Ghoulí varlata, nedá si nìkdo?}
{1699}{}{U se do snìhu nepodepíšu. Hmm.}
#
############################################
# 1700 Raider (Khan)
############################################
#
# target hit in head
#
{1700}{}{Ne do zasranı hlavy, ty kurvo.}
{1701}{}{Moje... hlava... nìjak... se... motá...}
{1702}{}{Ugnnn!}
{1703}{}{Do oblièeje ne! Do oblièeje ne!}
#
# target hit in left arm
#
{1710}{}{Zmlátím tì i jednou ruko, chcípáku!}
{1711}{}{Doktor! Mám ruku v pièi! Teda, obraznì øeèeno.}
{1712}{}{Jau. Ještì e dokáu pouívat obì paøáty.}
#
# target hit in right arm
#
{1720}{}{Zlomili mi ruku! Teï je to aspoò fér boj!}
{1721}{}{Doktor! Mám ruku v pièi! Teda, obraznì øeèeno.}
{1722}{}{Aby sis zachránil prdel, budeš ze mì muset oddìlat víc kouskù ne jenom ruku.}
#
# target hit in torso
#
{1730}{}{Ahhg! Do bøicha!}
{1731}{}{Hnrgggg! Nemùu...dıchat...}
{1732}{}{Mám zlomenı ebro! Za to ti vyrvu tvı! To je fér, ne?}
{1733}{}{Za...to...zaplatíš...ty...pomrdaná...}
{1734}{}{Boe tohle nesnáším...}
{1735}{}{Nggg! Solar plexus!}
#
# target hit in right leg
#
{1760}{}{Zatracenì! Moje noha!}
{1761}{}{Na to, abych ti zkopal prdel, nepotøebuju obì nohy.}
{1762}{}{Na tu nohu budu potøebovat stimpak...}
{1763}{}{Urggg...noha ... v prdeli...}
#
# target hit in left leg
#
{1770}{}{Zatracenì! Moje noha!}
{1771}{}{*Ergg* Z toho budu kulhat, do hajzlu...}
{1772}{}{Na tu nohu budu potøebovat stimpak...}
{1773}{}{Urggg...noha ... v prdeli...}
#
# target hit in eyes
#
{1780}{}{Kurva! Pøímo do oka!}
{1781}{}{Chceš mi znièit prostorovı vidìní, svinì?}
{1782}{}{Nevidím... krev... krev v oèích..}
{1783}{}{Nemusím tì vidìt, najdu si tì po smradu!}
#
# target hit in groin
#
{1790}{}{Co si o sobì sakra myslíš? e seš v americkım akèním filmu?}
{1791}{}{Moje koule! Moje ubohı koule! Pojï sem a uvidíme, jak se to bude líbit tvejm.}
{1792}{}{A moje koule se kutálí....}
{1793}{}{Dej mi chvilku pokoj, a mùu v klidu umøít.}
{1794}{}{Skvìlı. Mám je na placku.}
{1795}{}{Dej mi chvilku, hned se seberu a urvu ti tvı koule.}
{1796}{}{Sakra! No nic, dìcka sem stejnak neplánoval.}
#
############################################
# 1800 Junkie
############################################
#
# target hit in head
#
{1800}{}{Uau. Nìco mì trefilo do kebule.}
{1801}{}{Praštilo mì nìco do hlavy?}
{1802}{}{Ngggg}
{1803}{}{Eštì e sem plnej Jetu. Jinak by to asi bolelo.}
{1804}{}{Aùùù! Dejte mi nìkdo stimpak! Nebo radši Jet!}
#
# target hit in left arm
#
{1810}{}{Hej! Nìkdo mì trefil do ruky!}
{1811}{}{Hele, moje ruka je jenom pro jehly. Mla do nìèeho jinıho.}
{1812}{}{Nggggg}
{1813}{}{Aùùù! Dejte mi nìkdo stimpak! Nebo radši Jet!}
#
# target hit in right arm
#
{1820}{}{Hej! Nìkdo mì trefil do ruky!}
{1821}{}{Hele, moje ruka je jenom pro jehly. Mla do nìèeho jinıho.}
{1822}{}{Nggggg}
{1823}{}{Aùùù! Dejte mi nìkdo stimpak! Nebo radši Jet!}
#
# target hit in torso
#
{1830}{}{Moje bøicho!}
{1831}{}{Au! Aùù, moje blbı bøicho! Au!}
{1832}{}{Hej! Proè mì biješ do bøicha, blbèe?}
{1833}{}{Okamitì mì pøestaò mlátit do bøicha! Nebo tì pobliju!}
{1834}{}{Uau. Moje bøicho. Dostalo zásah. Super.}
{1835}{}{Nrgggg}
{1836}{}{*hfff*}
{1837}{}{Aùùù! Dejte mi nìkdo stimpak! Nebo radši Jet!}
#
# target hit in right leg
#
{1860}{}{Hej! Nìkdo mì trefil do nohy!}
{1861}{}{Hej! S tou nohou ještì chodím!}
{1862}{}{Aùùù! Dejte mi nìkdo stimpak! Nebo radši Jet!}
#
# target hit in left leg
#
{1870}{}{Hej! Nìkdo mì trefil do nohy!}
{1871}{}{Hej! S tou nohou ještì chodím!}
{1872}{}{Aùùù! Dejte mi nìkdo stimpak! Nebo radši Jet!}
#
# target hit in eyes
#
{1880}{}{Hmm, to asi nebyla jehla, co mì trefilo do oka...}
{1881}{}{Hej! S tím okem se koukám!}
{1882}{}{Moje oèi! Moje oèi! Bolí mì oèi!}
#
# target hit in groin
#
{1890}{}{Jsem tak vysoko, e to ani necítím. Oh, sakra... cítím!! Au!}
{1891}{}{*Hurhkkkk*}
{1892}{}{Kopni mì ještì jednou, okej?}
{1893}{}{Nghhhhh!}
{1894}{}{Do rozkroku ne!}
{1895}{}{Moje genitálie! Moje genitálie!}
{1896}{}{Mám rád, dy to bolí...}
{1897}{}{To...bolelo..HODNÌ.}
{1898}{}{Mùj rozkrok? Dy tam nic nemám?}
#
####################################################################################
#
#                    Generic People
#
####################################################################################
#                     
#                     Notes
#                     
#                     00-19 Running Away
#                     20-39 Moving in to Attack
#                     40-59 Attacking
#                     60-79 Target being Missed.
#
#                     2000 Wimpy Person
#                     2100 Normal Person
#                     2200 Tough Person
#                     2300 Berserk Person
#                     2400 Guard (Normal)
#                     2500 Guard (Tough)
#                     2600 Primitive
#                     2700 Soldier
#                     2800 Leader
#                     2900 Raider (Khan)
#                     3000 Robot
#                     3100 Ghoul
#                     3200 Junkie
#
####################################################################################
#
#
############################################
# 2000 Wimpy Person
############################################
#
#  running away
#
{2000}{}{Smilování!}
{2001}{}{Pomote mi nìkdo!}
{2002}{}{Prosím, pøestaò! Máš bıt pøece kladná postava!}
{2003}{}{Zabili Kennyho, parchanti!}
{2004}{}{Aaaaahhhh!}
{2005}{}{Slituj se!}
#
# moving in to attack
#
{2020}{}{Hmm, nechceš si to radši rozmyslet?}
{2021}{}{Nemám tì rád..}
{2022}{}{No, mohli jsme se tomu vyhnout, ale kdy jinak nedáš...}
{2023}{}{Asi se budu muset bránit}
{2024}{}{Asi se budu muset bránit}
{2025}{}{No, mohli jsme se tomu vyhnout, ale kdy jinak nedáš...}
#
# attacking
#
{2040}{}{Tumáš!}
{2041}{}{Pøíštì si nezaèínej!}
{2042}{}{Dobøe ti tak, lumpe.}
{2043}{}{Jak se ti to líbí?}
{2044}{}{}
{2045}{}{Ty bestie!}
{2046}{}{Já to nechci, ale musím...}
{2047}{}{}
{2048}{}{Nechci se rvát, ale...}
{2049}{}{Ty! Ty.... ty!}
#
# target being missed
#
{2060}{}{}
{2061}{}{Vedle!}
{2062}{}{Uff, to mohlo bolet!}
{2063}{}{Fjùùù. Ještì iju!}
{2064}{}{Hej, to mohlo bolet!}
{2065}{}{Fjùùù. Ještì iju!}
#
############################################
# 2100 Normal Person
############################################
#
#  running away
#
{2100}{}{Zaútoè na nìkoho jiného, prosím!}
{2101}{}{Slituj se nade mnou!}
{2102}{}{Pomote mi nìkdo!}
{2103}{}{Prosím, pøestaò! Máš bıt pøece kladná postava!}
{2104}{}{}
{2105}{}{Kvùli tomu pøece neumøu!}
#
# moving in to attack
#
{2120}{}{Jen poèkej...}
{2121}{}{}
{2122}{}{Hej ty!}
{2123}{}{Nikdo tì sem nezval}
{2124}{}{Tady bordel dìlat nebudeš.}
{2125}{}{Co si o sobì myslíš?}
#
# attacking
#
{2140}{}{Tos nemìl dìlat...}
{2141}{}{Starej se pøíštì o sebe}
{2142}{}{Tohle u nás dìláme chuligánùm!}
{2143}{}{Ty mutante!}
{2144}{}{Ty bastarde!}
{2145}{}{Bude z tebe rádlo pro psy.}
{2146}{}{To tì nauèí!}
{2147}{}{Fajn. Kdo chce kam, pomozme mu tam.}
{2148}{}{Ty zvíøe!}
{2149}{}{Zaslouil sis to!}
#
# target being missed
#
{2160}{}{Jsem dobrej, co?}
{2161}{}{Vidìl jsem brahmíny chytøejší, ne jseš ty...}
{2162}{}{Fjù!}
{2163}{}{Vedle jak ta jedle!}
{2164}{}{Díky, boe.}
{2165}{}{Vedle! Haha!}
#
############################################
# 2200 Tough Person
############################################
#
#  running away
#
{2200}{}{Tohle nemá cenu!}
{2201}{}{Zabili Kennyho! Parchanti!}
{2202}{}{Pomote mi nìkdo!}
{2203}{}{Pøíštì, hade.}
{2204}{}{Ještì se uvidíme!}
{2205}{}{Kvùli tomu pøece neumøu!}
#
# moving in to attack
#
{2220}{}{U mi neuteèeš!}
{2221}{}{Kdo tì sem pustil?}
{2222}{}{Zabte Kennyho!}
{2223}{}{Takovı jako ty tu nemáme rádi!}
{2224}{}{Tady bordel dìlat nebudeš.}
{2225}{}{Co si o sobì myslíš?}
#
# attacking
#
{2240}{}{Tumáš!}
{2241}{}{Jak se ti to líbí?}
{2242}{}{Tohle u nás dìláme chuligánùm!}
{2243}{}{Tohle je pro tebe! Uij si to!}
{2244}{}{Sbohem!}
{2245}{}{Tak pojï!}
{2246}{}{Problémovej sráèi!}
{2247}{}{Zmlátím tì jak malı dìcko...}
{2248}{}{Ty zvíøe!}
{2249}{}{Budeš litovat, e tì tvoje máma nepotratila!}
#
# target being missed
#
{2260}{}{Nic moc. Umím to líp.}
{2261}{}{O nièem.}
{2262}{}{Jseš obyèejnej sráè.}
{2263}{}{No teda nic moc, èekal jsem víc.}
{2264}{}{Mì nedostaneš.}
{2265}{}{To byl tvùj poslední omyl.}
#
############################################
# 2300 Berserk Person
############################################
#
#  running away
#
{2300}{}{Prásknul jsem do bot. Radši bych do tebe, ale...}
{2301}{}{Já se vrátím! A se mnou pøijde... }
{2302}{}{Pozdìji, blbe!}
{2303}{}{Byla to sranda, ale já jdu jinam!}
{2304}{}{Za to zaplatíš! Pozítøí!}
{2305}{}{Pøíštì si dáme odvetu!}
#
# moving in to attack
#
{2320}{}{Utrhnu ti hlavu a naseru ti do krku!}
{2321}{}{Èerstvı maso!}
{2322}{}{Cvièná støelba!}
{2323}{}{Ušukám tì xmrti!}
{2324}{}{Utrhnu ti hlavu a naseru ti do krku!}
{2325}{}{U teï seš mrtvá liška!}
#
# attacking
#
{2340}{}{Mám tì, zmrde!}
{2341}{}{Èas na útok! Kamikadze!}
{2342}{}{Neebrej o ivot. Anebo jo. Stejnì tì zabiju.}
{2343}{}{Doufám, e chcípneš pomalu.}
{2344}{}{Nìjakı poslední pøání?}
{2345}{}{Tumáš!}
{2346}{}{Chcípni!  Chcípni!  Chcípni!  Chcípni!  Chcípni! }
{2347}{}{Chcípni! }
{2348}{}{Trochu si tì otevøu a podívám se dovnitø!}
{2349}{}{Jseš mrtvá liška!}
#
# target being missed
#
{2360}{}{Hele, já jsem tady, slepoune!}
{2361}{}{Uam. Nudíš mì xmrti.}
{2362}{}{No tak, pøedveï nìco lepšího.}
{2363}{}{Líp to neumíš?}
{2364}{}{Kup si brejle, hovado!}
{2365}{}{Bude to lehèí, ne by si jeden myslel...}
#
############################################
# 2400 Guard (Normal)
############################################
#
#  running away
#
{2400}{}{Já mizím!}
{2401}{}{Tohle byl dost blbej nápad...}
{2402}{}{Zaútoè si na nìkoho jinıho, okej?}
{2403}{}{Sakrapes! Baj baj!}
{2404}{}{Kvùli tomu pøece neumøu!}
{2405}{}{To je na mnì kapku moc...}
#
# moving in to attack
#
{2420}{}{Hej ty!}
{2421}{}{Nauèím tì, jak se chovat ve spoleènosti...}
{2422}{}{Takovı jako ty tu nemáme rádi!}
{2423}{}{Èeká tì lekce spoleèenského chování!}
{2424}{}{Èas zaslouit si old...}
{2425}{}{Jen poèkej...}
{2426}{}{Proè tady vùbec vopruzuješ? Si myslíš, e seš Madmax nebo co?}
{2427}{}{Dycinky se najdou kreténi jako ty, co mi poserou celou šichtu...}
#
# attacking
#
{2440}{}{Tumáš!}
{2441}{}{Je ti fajn, co?}
{2442}{}{Radši práskni do bot, dokavad mùeš!}
{2443}{}{Jak se ti to líbí?}
{2444}{}{Bì za maminkou!}
{2445}{}{Vem si to! Všechno! }
{2446}{}{Uvidíme, z jakejch sraèek seš...}
{2447}{}{Hovado}
{2448}{}{Sráèi!}
{2449}{}{Bude od tebe klid.}
#
# target being missed
#
{2460}{}{To tì nauèila maminka, tenhleten útok?}
{2461}{}{Posero! Nemáš na to!}
{2462}{}{Seš vo nièem, uboáku...}
{2463}{}{To byl tvùj poslední omyl.}
{2464}{}{Amatére}
{2465}{}{To tì nauèili v mateøskı školce, ne?}
#
############################################
# 2500 Guard (Tough)
############################################
#
#  running away
#
{2500}{}{Musím zmizet!}
{2501}{}{Já se vrátím...A se mnou pøijde Bruce Willis!}
{2502}{}{Dneska mì nezabiješ!}
{2503}{}{Pozdìji, blbe!}
{2504}{}{Ještì se uvidíme, nádhero!}
{2505}{}{Za to zaplatíš! Pozdìji!}
#
# moving in to attack
#
{2520}{}{Seš historie! Mizerná historie!}
{2521}{}{Èerstvı maso. A brzo mrtvı maso...}
{2522}{}{Zatancuju si kozáèka na tvım hrobì!}
{2523}{}{Hej všichni! Cviènı støelby!}
{2524}{}{Seeru ti játra!}
{2525}{}{Tohleto si uiju...}
#
# attacking
#
{2540}{}{Vem si to! Všechno! !!}
{2541}{}{Nemusíš se vobtìovat prošením vo slitování. Ale jestli na tom trváš...}
{2542}{}{Tohle mì dycky bavilo...}
{2543}{}{Chceš ještì? No? Chceš? Ne? Tak tumáš!!!!}
{2544}{}{Bude z tebe rádlo pro psy.}
{2545}{}{Pøíštì nezaèínej, co nedokonèíš... Dost pouèování, teï dokonèím já tebe!}
{2546}{}{Doufám, e budeš chcípat pomalu...}
{2547}{}{Jenom jeden z nás ocaï vodejde po svejch...}
{2548}{}{Chcípni! }
{2549}{}{Takovı sráèe jako ty si dávám dva tøi xnídani.}
{2550}{}{Nakrmím s tebou svoji ještìrku. Doufám, e se jí neudìlá blbì...}
{2551}{}{Poslední vìc, co uvidíš, bude mùj úsmìv...}
{2552}{}{Tohle je moje oblíbená...}
#
# target being missed
#
{2560}{}{Srandisto...}
{2561}{}{Líp to neumíš?}
{2562}{}{Dìláš to moc jednoduchı!}
{2563}{}{Loaduj, kámo. Nic jinıho tì nezachrání.}
{2564}{}{Pomalı, vole.}
{2565}{}{Blbèe tupèe omezenèe...}
#
############################################
# 2600 Primitive
############################################
#
#  running away
#
{2600}{}{Utíkám od Prokletého!}
{2601}{}{Duchové mi naøídili utéct...}
{2602}{}{Nepøítel pouívá silnou magii! Utíkáme! Musíme pro šamana!}
{2603}{}{Temní duchové oni silní tady. Smrt chodí kolem!}
{2604}{}{Temnota je tady! Pryè!}
{2605}{}{Temnota mì pøišla pohltit! Pryè! Má duše utíká a já za ní!}
{2606}{}{Aiiieeeee!!}
#
# moving in to attack
#
{2620}{}{Pøedkové, veïte mé zbranì do vnitøností mıch nepøátel!}
{2621}{}{Tvá síla bude brzy má!}
{2622}{}{Velká bude má sláva u táborovıch ohòù!}
{2623}{}{Znectím tebe i tvou rodinu!}
{2624}{}{Jáh! Nabataluk!}
{2625}{}{Duchové buïte se mnou!}
{2626}{}{Pojï, zkøííme své zbranì.}
{2627}{}{Zaènìme!}
{2628}{}{Ú-Sutóóóó!}
{2629}{}{Duchové jsou se mnou! A tvùj duch se k nim brzy pøidá!}
#
# attacking
#
{2640}{}{Tví pøedkové tì opustili.}
{2641}{}{Tvá poráka mi pøinese velkou èest. Má magie nezná poráku!}
{2642}{}{Vzdej se hned a já nesním tvé srdce.}
{2643}{}{Bojuješ odvánì - sním tvou odvahu. Šaman bude zpívat o mém vítìzství.}
{2644}{}{Vykoupu se v tvé krvi!}
{2645}{}{Nebojím se tì!}
{2646}{}{Pøináším ti mír, ztracenı...}
{2647}{}{Brzy se pøipojíš ke svım pøedkùm. Ucti je a zemøi hrdì.}
{2648}{}{Temnota se blíí k tvé duši...}
{2649}{}{Mí pøedkové u èekají na tvou duši!}
{2650}{}{Má zbraò se napije tvé krve!}
{2651}{}{Napijme se z poháru bitvy!}
#
# target being missed
#
{2660}{}{ Tvé oèi jsou zaslepeny nenávistí.}
{2661}{}{ Tví duchové tì opustili. Nedivím se jim.}
{2662}{}{ Má magie je silnìjší ne tvoje!}
{2663}{}{ Díky své magii jsem nesmrtelnı!}
{2664}{}{ Tvá ivotní síla slábne!}
{2665}{}{ Strach zabíjí mysl. Tvá je u mrtvá.}
{2666}{}{ Má váleèná píseò mì ochrání!}
{2667}{}{ Naše dìti znají umìní boje lépe!}
{2668}{}{ iješ v míru pøíliš dlouho, neznáš váleèná umìní.}
{2669}{}{ Všichni tvého kmene jsou takoví slaboši?}
#
############################################
# 2700 Soldier
############################################
#
#  running away
#
{2700}{}{Posily? Kde jsou posily?!!!}
{2701}{}{Z tohohle bude váleènı soud, ale...}
{2702}{}{Doktora!}
{2703}{}{Ústup! Ústup!}
{2704}{}{Stáhnìte se! Strategickı ústup!}
{2705}{}{Jedna vyhraná bitva neznamená vyhranou válku, take pøíštì...}
#
# moving in to attack
#
{2720}{}{Tak pojï!}
{2721}{}{Kupøedu! Bij zabij!}
{2722}{}{Nauèím tì, jak se chovat ve spoleènosti...}
{2723}{}{Seš historie! Mizerná historie!}
{2724}{}{Do útoku!}
{2725}{}{Sundejte toho sráèe!}
{2726}{}{K palbì pøipravit!}
{2727}{}{Zabte je všechny, však si je bùh vytøídí!}
#
# attacking
#
{2740}{}{Tumáš!}
{2741}{}{A teï tì mám!}
{2742}{}{A teï chcípneš!}
{2743}{}{Jak se ti to líbí?}
{2744}{}{Trochu se pobavíme...}
{2745}{}{Pøíštì nezaèínej, co nedokonèíš... Dost pouèování, teï dokonèím já tebe!}
{2746}{}{Pomodli se!}
{2747}{}{Seš mrtvá liška, kámo. Do boje!}
{2748}{}{Jak se ti líbí?}
{2749}{}{Uvidíme se v pekle...}
#
# target being missed
#
{2760}{}{Potøebuješ trochu potrénovat... hmm, spíš víc ne míò.}
{2761}{}{Líp to neumíš?}
{2762}{}{No tak, sráèi. Sna se trochu, a to nemám tak lehkı...}
{2763}{}{Pøíštì zkus míøit...}
{2764}{}{Civilista...}
{2765}{}{Pøíštì to nechej na profesionálech...}
#
############################################
# 2800 Leader
############################################
#
#  running away
#
{2800}{}{}
{2801}{}{}
{2802}{}{}
{2803}{}{}
{2804}{}{}
{2805}{}{}
#
# moving in to attack
#
{2820}{}{}
{2821}{}{}
{2822}{}{}
{2823}{}{}
{2824}{}{}
{2825}{}{}
{2826}{}{}
{2828}{}{}
#
# attacking
#
{2840}{}{}
{2841}{}{}
{2842}{}{}
{2843}{}{}
{2844}{}{}
{2845}{}{}
{2846}{}{}
{2847}{}{}
{2848}{}{}
{2849}{}{}
#
# target being missed
#
{2860}{}{}
{2861}{}{}
{2862}{}{}
{2863}{}{}
{2864}{}{}
{2865}{}{}
#
############################################
# 2900 Raider
############################################
#
#  running away
#
{2900}{}{Zdrháme! Zdrháme! }
{2901}{}{Ústup!}
{2902}{}{Pøeskupte se!}
{2903}{}{Ustupte! Ustupte!}
{2904}{}{Stáhnìte se!}
{2905}{}{Aaaaghhh!}
#
# moving in to attack
#
{2920}{}{Zabte to, a je to co je to...}
{2921}{}{Èerstvı maso. A brzo mrtvı maso...}
{2922}{}{Zabte je všechny, však si je bùh protøídí...}
{2923}{}{Ten je mùj!}
{2924}{}{Ahhhhhhh!}
{2925}{}{Do útoku!}
#
# attacking
#
{2940}{}{Uij si poslední sekundy svıho mizernıho ivota...}
{2941}{}{Krev! Krev! Krev!}
{2942}{}{Seeru ti srdce!}
{2943}{}{RAAAAAAARRRR!!}
{2944}{}{Tvoje zbranì si povìsím na stìnu a z tebe budu mít pøedloku k posteli!}
{2945}{}{Smrt!}
{2946}{}{Zabiju si tì! Tìš se!}
{2947}{}{Z tvı lebky si udìlám krıgl!}
{2948}{}{Ma-so! Ma-so! Ma-so! Ma-so! Ma-so! Ma-so! }
{2949}{}{YAAAAAAAAAAAAH!}
{2950}{}{Provrtám tì, parchante!}
#
# target being missed
#
{2960}{}{Zbyteèná námaha!}
{2961}{}{Hmm, a já se tak tìšil...}
{2962}{}{Na mì nemáš, ty hovado!}
{2963}{}{Já iju dál!}
{2964}{}{Tvı tìlo je slabouèkı, nehodí se ani do polívky. O tvım mozku si radši ani nebudeme povídat...}
#
############################################
# 3000 Robot
############################################
#
#  running away
#
{3000}{}{Zmìna programu: nahrát program ústup}
{3001}{}{Taktickı plán: Ustoupit. Parametry: Rychle!}
{3002}{}{Bojová efektivita 1,2 %. Doporuèen ústup.}
{3003}{}{Taktická analıza hotova. Doporuèen ústup.}
{3004}{}{Nahrávám únikovı program...}
{3005}{}{Ústupová sekvence aktivována...}
#
# moving in to attack
#
{3020}{}{Cíl zamìøen!}
{3021}{}{Znièit! Znièit!}
{3022}{}{Humanoid nesmí uniknout!}
{3023}{}{Znièit vetøelce!}
{3024}{}{Bojová sekvence aktivována!}
{3025}{}{Nahrávám bojovı program!}
#
# attacking
#
{3040}{}{Bojová sekvence aktivována!}
{3041}{}{Útoèím na cíl!}
{3042}{}{Zahajuji útoènou sekvenci...}
{3043}{}{Narušitel musí bıt deaktivován!}
{3044}{}{Taktickı rozbor hotovı. Útok!}
{3045}{}{Zahajuji útok!}
{3046}{}{Cíl bude znièen.}
{3047}{}{Pravdìpodobnost znièení cíle 87,4576%.}
{3048}{}{Cíl musí bıt eliminován!}
{3049}{}{Ofenzivní program maximální priorita.}
#
# target being missed
#
{3060}{}{Analıza. Defenzivní program úspìšnı.}
{3061}{}{Analıza. Útok cíle neefektivní.}
{3062}{}{Cíl zaútoèil neúspìšnì. }
{3063}{}{Jednotka nezasaena, útok neúspìšnı...}
{3064}{}{Útoèné schopnosti cíle pøecenìny, pøepoèítávám...}
{3065}{}{Analıza. Cíl neúspìšnı ve svém útoku. Sníit bojovou prioritu pro danı cíl...}
#
############################################ 
# 3100 Ghoul
############################################ 
#
#  running away
#
{3100}{}{Musím odtud vypadnout!}
{3101}{}{Já se vrátím... A se mnou pøijde Bruce Willis!}
{3102}{}{Dneska mì nezabiješ!}
{3103}{}{Tak pøíštì, normále!}
{3104}{}{Ještì o mì uslyšíš!}
{3105}{}{Za to zaplatíš! Pozdìji!}
{3106}{}{Podruhı umírat nebudu, u poprvı to bylo o nièem!}
{3107}{}{Noièky zdrhejte! Nesmíte mì zklamat!}
{3108}{}{To je jenom doèasnej ústup, tak si o sobì moc nemysli.}
{3109}{}{Uh uh. Èas pro taktickej ústup.}
{3110}{}{Nìkdy pøíštì... }
{3111}{}{Zkus si mì chytit, bejval sem šampión na 100 metrù!}
{3112}{}{Jeiš, tolik hodin! Já u musím bìet, mìj se.}
{3113}{}{Pryè!}
{3114}{}{Musím si jít pøišít pár odpadlej kouskù, ale pak se vrátím...}
{3115}{}{Moje starı kosti u toho maj dost.}
{3116}{}{Na tohle jsem u moc starej.}
{3117}{}{Matka pøíroda je sviòa, ale ty si vìtší. Èau!}
{3118}{}{No mì u to staèilo, najdi si nìkoho jinıho.}
{3119}{}{Hej, neutíkej pøede mnou!}
#
# moving in to attack
#
{3120}{}{Seš historie! Mizerná historie!}
{3121}{}{Ma-so! Ma-so! Ma-so! Ma-so! Ma-so! Ma-so!}
{3122}{}{Seš mrtvı maso!}
{3123}{}{Mozkıııı...mozkııı....}
{3124}{}{Plivni si na místo, kde chceš mít hrob.}
{3125}{}{Doufám, e ti hlava zùstane v kuse...}
{3126}{}{Chceš mozkıııı...mozkııı....dej mozkııı}
{3127}{}{Doufám, e nejseš policajt. Chci mozeèek!}
{3128}{}{Budeš potøebovat posily!}
{3129}{}{Hodilo by se mi pár novejch souèástek. Levá ruka u je nìjak plesnivá...}
{3130}{}{Bude Tatarskej biftek!}
{3131}{}{Tak pojï ty sráèi!}
{3132}{}{Udìlám si z tebe košili!}
{3133}{}{Vepøovı? Kde je vepøovı? Támhle je ta svinì!}
{3134}{}{Mmmm, miluju lidi. Trochu potøít èesnekem a pak podusit...}
{3135}{}{Vidìls nìjakej film o zombiích? Teï ho zaiješ! Mozkı.....}
{3136}{}{U je obìd? Támhle jde hlavní chod!}
{3137}{}{Dej sem mozek!}
{3138}{}{Náhradní díly se hodí. Zbytek se seere.}
{3139}{}{Hele, novej dárce orgánù!}
#
# attacking
#
{3140}{}{Seš na øadì!}
{3141}{}{Nemusíš se vobtìovat prošením vo slitování. Ale jestli na tom trváš...}
{3142}{}{To si vychutnám!}
{3143}{}{Ohh, to bude bolet!}
{3144}{}{Èas na sváèu, co?}
{3145}{}{Seeru ti játra! Doufám, e moc nechlastáš...}
{3146}{}{Doufám, e budeš chcípat pomalu...}
{3147}{}{Veèeøe!}
{3148}{}{Chcípni! }
{3149}{}{Takovı sráèe jako ty si dávám dva tøi xnídani, nìkdy i k obìdu.}
{3150}{}{Mòam. Dej mi kousek!}
{3151}{}{Dej mi kousnout!}
{3152}{}{Pojï k tatínkovi!}
{3153}{}{Mám tu nìco pro tebe!}
{3154}{}{Nehejbej se! Nebude to bolet!}
{3155}{}{Bude z tebe tajemství šéfkuchaøe!}
{3156}{}{Chutnáš tak dobøe, jako vypadáš?}
{3157}{}{Chutnı&vıivnı! Doufám.}
{3158}{}{Zastav si krvácení, a z tebe nevyteèe všechna šáva.}
{3159}{}{Poèkej, odkrojím si øízek...}
#
# target being missed
#
{3160}{}{Mnì nemùeš ublíit!}
{3161}{}{A pak e *Ghoulové* sou pomalı...}
{3162}{}{Vedle, normáku!}
{3163}{}{Vedle, normáku!}
{3164}{}{Nemùeš mì zabít, nejdøív se musíš trefit...}
{3165}{}{Pomalı, vole.}
{3166}{}{Fajn, a teï si to zkusíme na ostro, okej?}
{3167}{}{Hele, a šla ta rána vùbec na mnì?}
{3168}{}{Co to bylo?}
{3169}{}{Tohle není šaráda...}
{3170}{}{Na boj se musíš soustøedit.}
{3171}{}{Blbe! Tady jsem! Kam to míøíš?}
{3172}{}{Díváš se na mnì?}
{3173}{}{Zkusíme to ještì jednou?}
{3174}{}{Ne, ne, ne! Musíš míøit sem!}
{3175}{}{Na co míøíš, teda jestli vùbec míøíš?}
{3176}{}{Co je, ty to neumíš?}
{3177}{}{Dneska to dìlaš poprvı, co?}
{3178}{}{A teï já! Jenome já se trefím!}
{3179}{}{Líp to neumíš? Tak to seš v tìkım prùseru!}
#
############################################
# 3200 Junkie
############################################
#
#  running away
#
{3200}{}{Uau! Musím pro èerstvı zásoby...}
{3201}{}{Já se vrátím...A se mnou pøijde Bruce Willis!}
{3202}{}{Hmm, málo buffautu.}
{3203}{}{Nemùu se nafetovat, kdy tady chcípnu. Take pryè...}
{3204}{}{Aj! Nebij mì! Nebij mì!}
{3205}{}{Tahle halucinace na mì zaèíná bıt trochu moc silná...}
#
# moving in to attack
#
{3220}{}{Seer to!}
{3221}{}{V tvım vlastním zájmu doufám, e máš nìjakı stimpaky. Nebo Jet!}
{3222}{}{Za tvoji zdechlinu dostanu aspoò deset dávek Jetu!}
{3223}{}{A...tì...chytim...tak...tì...snim...}
{3224}{}{Moná dy tì zabiju, e mi bude líp? Uvidíme...}
{3225}{}{Zabiju! Zabiju! Zabiju! Zabiju! Tebe!}
{3226}{}{Tvoje vrada, to bude jako další dávka!}
#
# attacking
#
{3240}{}{Seer to!}
{3241}{}{Zabiju! Zabiju! Zabiju! Zabiju! Tebe!}
{3242}{}{Chceš? Tumáš!!}
{3243}{}{Nrrrg}
{3244}{}{Hajáááá}
{3245}{}{Zabiju tì pomalu....}
{3246}{}{Dostanu tì jako dvojbabkovou kurvu...}
#
# target being missed
#
{3260}{}{Blízko, ale vedle. Dej si Jet, pude to líp.}
{3261}{}{Sem tak vysoko, e se mnì ani nedotkneš!}
{3262}{}{Kerej z vás to byl?}
{3263}{}{Uau. Skoro.}
{3264}{}{Seš víc pod fetem ne já...}
{3265}{}{Na drogovou halucinaci se biješ pìknì mizernì...}
#
####################################################################################
#
#                   Area People
#
####################################################################################
#                     
#
#                     4000  Arroyo
#                     6000  The Den
#                     8000  Modoc
#                     10000  Klamath
#                     12000  Vault City / Raiders
#                     14000  Gecko
#                     16000 Broken Hills
#                     18000 New Reno
#                     20000 Sierra Army Depot
#                     22000 Redding
#                     24000 NCR
#                     26000 V13 / V15
#                     28000 Military Base
#                     30000 Navarro
#                     32000 San Fransisco
#                     34000 The Enclave
#                     36000 Special (Encounters and Created)
#
#                     Note : Some of these people will just have run away, moving to attack, attacking, and getting
#                                missed.  Others will also have cataloged hit locations.
#
####################################################################################
#
####################################################################################
#
# 4000 Arroyo
#
#                   4000 The Elder
#                   4100 Hakunin
#                   4200 Standing Fist
#
####################################################################################
#
#
####################################################################################
#
# 12000 Vault City / Raiders
#
#                   12000 Raider Mercs
#                   12100 Raider Captain
#                   12200 Gangster
#                   12300 Raider (Hit Locations)
#
####################################################################################
#
############################################
# 12000 Raider Mercs
############################################
#
#  running away
#
{12000}{}{Tady nezùstanu ani za zlatı hovno...}
{12001}{}{Ústup!}
{12002}{}{Èas prásknout do bot...}
{12003}{}{Rozestupte se!}
{12004}{}{Ustupte! Ustupte!}
{12005}{}{Poèkám si na tebe ve Falloutu 3!}
{12006}{}{Bishop si mùe svoje prachy narvat do prdele...}
#
# moving in to attack
#
{12020}{}{Cíl zamìøen!}
{12021}{}{Kryjte mì nìkdo!}
{12022}{}{Hur-hur-hur! Hur-hur-hur!}
{12023}{}{Zabte Kennyho!}
{12024}{}{KRLEŠ! KRLEŠ! KRLEŠ!}
{12025}{}{Dej svı prdeli pusu na rozlouèenou a pojï sem.}
{12026}{}{Èas sundat dalšího zkurvence...}
{12027}{}{Nabij, pal!}
{12028}{}{Rokenrol!}
{12029}{}{Heleho! Podívejte se, co za buzíka se nám courá po støelnici! Pal!}
{12030}{}{Doufám, e máš nìjakı stimpaky, mrtvá liško...}
{12031}{}{Kontakt!}
{12032}{}{Narušitel! Narušte ho!}
{12033}{}{Máme tady narušitele, bando! Natrhnem mu prdel!}
{12034}{}{Do boje, bando! Zabte tu kurvu!}
{12035}{}{Bijem a zabijem! Na nì!}
{12036}{}{Po øadì, chlapci, po øadì! Ten je mùj!}
{12037}{}{Pozor! Nabít a pal!}
{12038}{}{Pokropte je trochu!}
#
# attacking
#
{12040}{}{Sundejte je!}
{12041}{}{Seš v prdeli, vole.}
{12042}{}{Kopnu tì do prdele tak, e moji leštìnku na boty budeš cítit v krku ještì pøíští tejden.}
{12043}{}{::Tak dem! Tak dem! Všechno to tu rozbijem! ::}

{12044}{}{Dostaneš kritickej!}
{12045}{}{Chceš? Tumáš!! CHCEŠ TROCHU? TUMÁŠ MOC!}
{12046}{}{Hajááááá!!!}
{12047}{}{Dej si!}
{12048}{}{Doufám, e máš nìjakı stimpaky, mrtvá liško...}
{12049}{}{Dej svı prdeli pusu na rozlouèenou a pojï sem.}
#
# target being missed
#
{12060}{}{Biješ se jako uøíznutej kokot.}
{12061}{}{Ha! Vedle, ty psí kundo.}
{12062}{}{Sem na tebe moc rychlej, blbe?}
{12063}{}{S takovou brzo zdechneš...}
{12064}{}{Vo nièem...}
{12065}{}{Slabej *A* pomalej, jak vidim.}
#
############################################
# 12100 Raider Captain
############################################
#
#  running away
#
{12100}{}{Musím zmizet!}
{12101}{}{Já se vrátím...A se mnou pøijde Bruce Willis!}
{12102}{}{Dneska mì nezabiješ!}
{12103}{}{Pøíštì, hajzle!}
{12104}{}{Ještì o mì uslyšíš!}
{12105}{}{Za to zaplatíš! Pozdìji!}
#
# moving in to attack
#
{12120}{}{Seš historie! Mizerná historie!}
{12121}{}{Èerstvı maso. A brzo mrtvı maso...}
{12122}{}{Roztrhám tì na úplnì malinkatı kousíèky!}
{12123}{}{Všichni do útoku!}
{12124}{}{Plivni si, kde chceš mít hrob.}
{12125}{}{Zabte je všechny!}
#
# attacking
#
{12140}{}{Seš na øadì!}
{12141}{}{Nemusíš se vobtìovat prošením vo slitování. Ale jestli na tom trváš...}
{12142}{}{To si vychutnám!}
{12143}{}{Ohh, to bude bolet!}
{12144}{}{}
{12145}{}{Seeru ti játra! Doufám, e moc nechlastáš...}
{12146}{}{Doufám, e budeš chcípat pomalu...}
{12147}{}{Zabiju!}
{12148}{}{Chytej!}
{12149}{}{Takovı sráèe jako ty si dávám dva tøi xnídani, nìkdy i k obìdu.}
#
# target being missed
#
{12160}{}{Mì nemùeš ublíit!}
{12161}{}{}
{12162}{}{Na tos nikdy nemìl, kriple!}
{12163}{}{Zkus to ještì jednou, ty hovado.}
{12164}{}{Nemùeš mì zabít, nejdøív se musíš trefit...}
{12165}{}{Pomalı, vole.}
#
############################################
# 12200 Gangster (Combat Messages)
############################################
#
#  running away
#
{12200}{}{Uf, tahle sraèka na mnì zaèíná bejt kapku moc...}
{12201}{}{Èas zajít pro zbytek rodiny, na mnì je toho moc...}
{12202}{}{Dostanu tì pøíštì!}
{12203}{}{Máš štìstí, e mi došly stimpaky...}
{12204}{}{Mizim, mìj se tu fajn.}
{12205}{}{Musím rychle sehnat òákı stimpaky...}
#
# moving in to attack
#
{12220}{}{Škoda, e nejsme u moøe, nasadil bych ti betonovı botky...}
{12221}{}{A sem mìl fíling, e dneska nikoho nezabiju...}
{12222}{}{Golgota dostane dalšího vobyvatele...}
{12223}{}{Asi to budeme muset udìlat po zlym.}
{12224}{}{Vybiju ti zuby a udìlám si z nich hrací kostky...}

{12225}{}{Nìkdo si tady hraje se ivotem a mì nìco øíká, e brzo prohraje...}
{12226}{}{Zabije tebe, tvoji rodinu, psa i zlatı rybièky!}
{12227}{}{Musím vynıst vodpadky...}
{12228}{}{Ach jo, to zas bude robota, kopat ti hrob...}
#
# attacking
#
{12240}{}{Kopnu tì do prdele tak, e ji budeš nosit jako klobouk...}
{12241}{}{Štìstìna s tebou dneska není, ejo?}
{12242}{}{Budu tì mlátit tak dlouho, a budeš eštì hnusnìjší.}
{12243}{}{Tvoje prdel pude do hrobu. Zbytek ji bude následovat chvilku potom.}
{12244}{}{Vykopnu ti srdce a pak ho rozšlapu. Tìšíš se?}
{12245}{}{Škoda e nejni èas. Tvoje kebule by se sqìle vyjímala v mı sbírce. No nic, vemu si aspoò uši...}
{12246}{}{Ukáu ti, co tady v okolí dìláme z vodpadkama..}
{12247}{}{Fláknu ti tak, e si budeš myslet, e je zemìtøesení....}
{12248}{}{U mì nebavíš. Zdechni.}
{12249}{}{Pozdrav vode mne satanáše...}
#
# target being missed
#
{12260}{}{Zaèni se snait, nebo skonèíš v nemocnici. V lepším pøípadì...}
{12261}{}{Biješ se jako dìvka. Mrtvá dìvka.}
{12262}{}{Hezkı. Hned ti ukáu, jak se to má dìlat správnì.}
{12263}{}{Seš slepej nebo blbej? Vobojí co?}
{12264}{}{Seš na jetu nebo co?}
{12265}{}{Takhle netrefíš ani vrata vod stodoly...}
{12266}{}{Nebij do vzduchu, bij do mnì!}
#
############################################
# 12300 Raider (Hit Locations)
############################################
#
# target hit in head
#
{12300}{}{Ngggg}
{12301}{}{Moje... hlava... nìjak... se... motá...}
{12302}{}{Ugnnn!}
{12303}{}{Do oblièeje ne! Do oblièeje ne!}
#
# target hit in left arm
#
{12310}{}{Moje...ruka...moje...krásná...ruka.}
{12311}{}{Doktor! Mám ruku v pièi! Teda, obraznì øeèeno.}
{12312}{}{*hffff*}
#
# target hit in right arm
#
{12320}{}{Prsten? Ustøelili mi prsten!}

{12321}{}{Doktor! Mám ruku v pièi! Teda, obraznì øeèeno.}
{12322}{}{No, s touhle rukou u baby asi vošahávat nebudu.}
#
# target hit in torso
#
{12330}{}{Moje bøicho!}
{12331}{}{Hnrgggg}
{12332}{}{*hff*}
{12333}{}{Za...to...zaplatíš...ty...pomrdaná...}
{12334}{}{*Ooooof*}
{12335}{}{Nggg! Solar plexus!}
#
# target hit in right leg
#
{12360}{}{Zatracenì! Moje noha!}
{12361}{}{*Ergg*}
{12362}{}{Na tu nohu budu potøebovat stimpak...}
{12363}{}{Urggg...noha ... v prdeli...}
#
# target hit in left leg
#
{12370}{}{Zatracenì! Moje noha!}
{12371}{}{*Ergg*}
{12372}{}{Na tu nohu budu potøebovat stimpak...}
{12373}{}{Urggg...noha ... v prdeli...}
#
# target hit in eyes
#
{12380}{}{Moje oko! Moje krásnı voko!}
{12381}{}{Chceš mi znièit prostorovı vidìní, svinì?}
{12382}{}{Nevidím... krev... krev v oèích..}
#
# target hit in groin
#
{12390}{}{Co si o sobì sakra myslíš? e seš v americkım akèním filmu?}
{12391}{}{Já nechci bejt tenor! Vyser se na to!}
{12392}{}{A moje koule se kutálí....}
{12393}{}{Dej mi chvilku pokoj, a mùu v klidu umøít.}
{12394}{}{Koule! Moje koule! Do koulí nééé!}
{12395}{}{Dej mi chvilku, hned se seberu a urvu ti tvı koule.}
{12396}{}{Blbèe!}
#
####################################################################################
#
# 26000         V13/V15
#
#                    26000  Normal Khan
#                    26100  Tough Khan
#
####################################################################################
#
############################################
# 26000 Khan - Normal
############################################
#
#  running away
{26000}{}{Zdrháme! Zdrháme!}
{26001}{}{Ústup!}
{26002}{}{Pøeskupte se!}
{26003}{}{Ustupte! Ustupte!}
{26004}{}{Stáhnìte se!}
{26005}{}{Já mizím!}
#
# moving in to attack
#
{26020}{}{Zabte to, a je to, co je to...}
{26021}{}{U teï seš mrtvej, ty mrtvá liško...}
{26022}{}{Umrdám tì xmrti!}
{26023}{}{Ten je mùj!}
{26024}{}{Berte je!}
{26025}{}{Ty uši se mi líbí. Povìsím si je na krk.}
#
# attacking
#
{26040}{}{Uij si poslední sekundy svıho mizernıho ivota...}
{26041}{}{Krev! Krev! Krev!}
{26042}{}{Seeru ti srdce!}
{26043}{}{Tohle prostì eru!}
{26044}{}{Tvoje zbranì si povìsím na stìnu a z tebe budu mít pøedloku k posteli!}
{26045}{}{Jako hraní dùma nebo kvejka. Akorát lehèí!}
{26046}{}{Zabiju si tì! Tìš se!}
{26047}{}{Z tvı lebky si udìlám krıgl!}
{26048}{}{Ma-so! Ma-so! Ma-so! Ma-so! Ma-so! Ma-so! }
{26049}{}{Voberu tvou mrtvolu a pak ji hodím na hnojištì!}
{26050}{}{Provrtám tì, parchante!}
#
############################################
# 26100 Khan - Tough
############################################
#
#  running away
#
{26100}{}{Krejte mì, bando!}
{26101}{}{Ústup!}
{26102}{}{Pøeskupte se!}
{26103}{}{Ustupte! Ustupte!}
{26104}{}{Stáhnìte se!}
{26105}{}{Ustupte, musíme se dát dohromady!}
#
# moving in to attack
#
{26106}{}{A bitka zaèíná! Neperte to do nich!}
{26107}{}{Hele, cviènej cíl!}
{26108}{}{Neèekej slitování. My sme zkrátka krveíznivı postavièky z poèítaèovı hry.}
{26109}{}{Ten je mùj!}
{26110}{}{Do útoku! Kamikadze!}
{26111}{}{Sranda zaèíná! A ty konèíš!}
{26111}{}{Zabte ho nìkdo! Nebo e bych to udìlal sám....}
#
# attacking
#
{26112}{}{Khanové bijou!}
{26113}{}{Khans rulz, vole! Sme elita!}
{26114}{}{Sem dokonalej! Ty taky, jenome dokonalı hovno.}
{26115}{}{Khanové vládnou!}
{26116}{}{Sme neporazitelní! }
{26117}{}{Neutíkej! Nevzdávej se! Zabijem tì!}
{26118}{}{Zabiju si tì! Tìš se!}
{26119}{}{Z tvejch zubù bude fajn náhrdelník.}
{26120}{}{Ma-so! Ma-so! Ma-so! Ma-so! Ma-so! Ma-so! }
{26121}{}{Tvım skaplem si utøu prdel!}
#
# target being missed
#
{26122}{}{Hezká finta. Eštì se trefit...}
{26123}{}{Pøíštì zkus míøit na mnì, ne nìkam do prdele...}
{26124}{}{Sem neznièitelnej!}
{26125}{}{Na mì nemáš, ty hovado!}
{26126}{}{Hele, tady ten by potøeboval pauzu, aby se nauèil, jak s tím zacházet...}
{26127}{}{S tímhle hovadem se bít nebudu! Bije se jak malı dìcko. Mrtvı.}
{26128}{}{Proè se s tebou tak seru?}
#
####################################################################################
#
# 32000        San Fransisco
#
#                    32000  Shi Hit Location Messages
#                    32100  The Dragon
#                    32200  Lo Pan
#                    32300  Chip
#                    32400  Badger
#                    32500  Ryan
#                    32600  Shi Guards
#                    32700  Elron Hit Locations
#                    32800  Elron Guards
#                    32900  Ron Cruz/Nikki Goldman
#                    33000  OZ-9
#                    33100  OZ-7
#                    33200  Hovado (Hit Locations)
#
####################################################################################
#
############################################
# 32000 Shi Hit Locations
############################################
#
# target hit in head
#
{32000}{}{Mùj oblièej! Mùj oblièej!}
{32001}{}{Mùj skalp!}
{32002}{}{oooh... moje uši...}
#
# target hit in left arm
#
{32010}{}{Au, moje ruka!}
{32011}{}{Au!}
{32012}{}{Zlomili mi ruku!}
#
# target hit in right arm
#
{32020}{}{Au, moje ruka!}
{32021}{}{Wahhhh!}
{32022}{}{Mùj boe! Moje ruka!}
#
# target hit in torso
#
{32030}{}{JAU!}
{32031}{}{Asi omdlím......}
{32032}{}{Hej! Moje bøicho!}
{32033}{}{Uffffff!}
{32034}{}{To bolí!}
{32035}{}{Zásah do bøicha...}
{32036}{}{Ohhh, bolest!}
#
# target hit in right leg
#
{32060}{}{Au, moje noha!}
{32061}{}{Moje koleno!}
{32062}{}{Pøímo do artérie!}
#
# target hit in left leg
#
{32070}{}{Au, moje noha!}
{32071}{}{::hop... hop::}
{32072}{}{Aaaarrrrggghhh!}
#
# target hit in eyes
#
{32080}{}{Nevidím! Ty bastarde!}
{32081}{}{Mùj oblièej! Moje oèi! Arrrrgh!}
{32082}{}{Kde jsi? Pomóc!}
#
# target hit in groin
#
{32090}{}{Ooooooooo, mùj rozkrok! Ooooooo...}
{32091}{}{Já...já...jau...}
{32092}{}{::krèí se::}
{32093}{}{::zvrací::}
{32094}{}{Nemùu...dıchat...}
{32095}{}{Bolí, bolí...}
#
############################################
# 32100 The Dragon
############################################
#
#  running away
#
{32100}{}{Tvoje kung-fu je lepší ne moje!}
{32101}{}{Jsi mocnı. Sbohem.}
{32102}{}{ÁÁ! Zlo triumfuje!}
{32103}{}{Oh ne...}
{32104}{}{Zklamal jsem.}
{32105}{}{Jsem zneuctìn.}
#
# moving in to attack
#
{32120}{}{Bolí mì to, ale musím na tebe zaútoèit...}
{32121}{}{Radím ti, uprchni.}
{32122}{}{Jenom zbabìlci pouívají zbranì.}
{32123}{}{Uteè dokud mùeš...}
{32124}{}{Pøiprav se, špatná osobo.}
{32125}{}{Uteè a já ti neublíím.}
{32126}{}{Kdy trváš na boji...}
{32128}{}{Ty si myslíš, e mì mùeš porazit?}
#
# attacking
#
{32140}{}{Haiiiiiiii-YA!}
{32141}{}{Banzai!}
{32142}{}{Kjai! }
{32143}{}{Haj!}
{32144}{}{Huh!}
{32145}{}{Haj áááá!}
{32146}{}{Hai - ah!}
{32147}{}{Uka se!}
{32148}{}{Mongole!}
{32149}{}{Kop do oka!}
#
# target being missed
#
{32160}{}{Jenom zbabìlci pouívají zbranì.}
{32161}{}{Bojíš se opravdového bojovníka?}
{32162}{}{Tvoje kung-fu je slabé.}
{32163}{}{Vzdej se!}
{32164}{}{Tomu øíkáš boj?}
{32165}{}{Hıbeš se jako tìhotná koala.}
#
############################################
# 32200 Lo Pan
############################################
#
#  running away
#
{32200}{}{Hledám holku se zelenıma oèima, nevidìl ji nìkdo?}
{32201}{}{Ano pane...šek je v poštì.}
{32202}{}{Mám dùleitou schùzku...}
{32203}{}{Dobøe, prohrál jsem!}
{32204}{}{Vzdávám se!}
{32205}{}{Tvoje kung-fu je silnìjší ne moje.}
#
# moving in to attack
#
{32220}{}{Blesku! Hrome! Zabíjejte pro mnì!}
{32221}{}{Tvé síly jsou slabé!}
{32222}{}{Tvé kungfu mi neublíí!}
{32223}{}{Jsem neporazitelnı!}
{32224}{}{Jsem lepší, ne kdy byl Bruce-Lee!}
{32225}{}{ene se na tebe bouøe!}
{32226}{}{Uteè, zbabìlèe! Nebo zemøi!}
{32228}{}{Zabiju tì jedinım úderem!}
#
# attacking
#
{32240}{}{Kdo je Jack Burton?}
{32241}{}{Chtìl bych po tobì moc, kdybych si pøál tvoji smrt?}
{32242}{}{Nezùstaly po tobì doufám ádné dluhy.}
{32243}{}{Máš problém s oblièejem.}
{32244}{}{Vytrhnu ti srdce!}
{32245}{}{Peklo u na tebe èeká!}
{32246}{}{Pozdrav za mne své pøedky!}
{32247}{}{Jsem nesmrtelnı!}
{32248}{}{Bán-cai!}
{32249}{}{Hai-YA!}
#
# target being missed
#
{32260}{}{Cítím se nesmrtelnı!}
{32261}{}{Sna se víc. Stejnì to nepomùe...}
{32262}{}{Uf, au, jau. Ta bolest! U mì nebij, prosím!}
{32263}{}{Ty se vánì neumíš bít!}
{32264}{}{Tomu øíkáš boj?}
{32265}{}{::zív::}
#
############################################
# 32300 Chip
############################################
#
#  running away
#
{32300}{}{Mám enu a dìti!}
{32301}{}{Ne! Vdy mám narozeniny!}
{32302}{}{Jau...moje bøicho...}
{32303}{}{Zpátky do nemocnice...}
{32304}{}{Musím...dret tu tepnu... nebo vykrvácím...}
{32305}{}{Ah, moje játra. Bolí, bolí.}
#
# moving in to attack
#
{32320}{}{Budu tì muset rozpárat kapesním noíkem.}
{32321}{}{Zmlátím tì jak malı dìcko...}
{32322}{}{Snídáš hovna, nebo ti tak z huby smrdí od pøírody?}
{32323}{}{Nakopu ti prdel, a ti vobìd vycáká ušima.}
{32324}{}{Rozpáøu tì!}
{32325}{}{Tak to je konec, kámo. Umøeš.}
#
# attacking
#
{32340}{}{BUM!}
{32341}{}{Nakopu ti prdel!}
{32342}{}{OU JÉÉ!}
{32343}{}{Jo, bajby, jóóó!}
{32344}{}{Chceš? Tumáš!}
{32345}{}{Nehejbej se!}
{32346}{}{Promíchat, potøepat a zapíchnout!}
{32347}{}{Hele, to je tvùj ksicht? Hnusnej!}
{32348}{}{Tak hnusnej ksicht sem eštì nevidìl. Hned s ním nìco udìlám.}
#
# target being missed
#
{32360}{}{Vedle jak ten smrèek! Ha ha ha}
{32361}{}{Smrdíš!}

{32362}{}{Ha Ha! Jsem bùh!}
{32363}{}{Dej mi pusu, zlatíèko, to ti moná pùjde líp.}
{32364}{}{Musíš míøit! Jinak se do mnì netrefíš!}
{32365}{}{Rozpáøu tì!}
#
############################################
# 32400 Badger
############################################
#
#  running away
#
{32400}{}{Oblièej! Do oblièeje ne!}
{32401}{}{Mám znièenej úèes, ty parchante!}
{32402}{}{Bastarde! Za to tì sexuálnì zneuiju, e si tejden nesedneš!}
{32403}{}{Potøebuju vìtší kvér!}
{32404}{}{Waaaaaaaaaaa!!!}
{32405}{}{ÁÁÁ! Dostal sem to do prdele!}
#
# moving in to attack
#
{32420}{}{Budeš si pøát, aby tì tvùj tatík nastøíkal mámì na bøicho!}
{32421}{}{Ty máš prdel tam nahoøe? Jo sorry, to je tvùj ksicht.}
{32422}{}{Tak se pøedveï, ty kuse škorpioního hovna!}
{32423}{}{Nenaser si do kalhot, jinak je ode mì nikdo nekoupí.}
{32424}{}{Za Shane!}
{32425}{}{Udìlám to tak, aby tì to bolelo, jak nejvíc to pùjde!}
{32426}{}{Mùu ti nejdøív utrhnout koleno?}
{32428}{}{Tak pojï, holèièko. Uka, co máš!}
#
# attacking
#
{32440}{}{Doufám, e tu ruku nebudeš potøebovat!}
{32441}{}{Jau, to muselo bolet, co?}
{32442}{}{Auè tájm!}
{32443}{}{Miluju ranní vùni krve...}
{32444}{}{Teèe z tebe krve jak z prasete...}
{32445}{}{Bu bu bu ty malá píèo!}
{32446}{}{Co to z tebe èouhá? }
{32447}{}{Je to na cestì!}
{32448}{}{Seer to!!}
#
# target being missed
#
{32460}{}{Støílíš hùø ne moje máma, a to je u dva roky mrtvá!}
{32461}{}{Sráèi. Fuj!}
{32462}{}{Vra se do LA, ty hovne!}
{32463}{}{Mám se chvíli nehejbat?}
{32464}{}{::::prrrrrd::::}
{32465}{}{Uau, to bylo dobrı...}
#
############################################
# 32500 Ryan
############################################
#
#  running away
#
{32500}{}{Kdo uteèe, vyhraje!}
{32501}{}{La la la ... Pomóc!}
{32502}{}{Ha ha OW!}
{32503}{}{AT! AT! At at at at at!}
{32504}{}{Karrramba!}
{32505}{}{Pomóóóóóc!}
#
# moving in to attack
#
{32520}{}{Tohle nechceš, ale já ti stejnì dám...}
{32521}{}{Pojï si, dostaneš!}
{32522}{}{Chceš? Tumáš! Huh? Huh?}
{32523}{}{Pojï sem! Znásilním tì!}
{32524}{}{Seš ÚPLNÌ mrtvá liška!}
{32525}{}{Poslední chyba v tvım ivotì!}
{32526}{}{Nìco pro tebe tady mám!}
#
# attacking
#
{32540}{}{Doufám, e se vod tebe nezašpinim...}
{32541}{}{::dy da dy da dy dáá dy da dy da dááá la la diskotéka::}
{32542}{}{Aáj uil áluajs láv jùùùùùùùùùùùù}
{32543}{}{Nechceš to zabalit?}
{32544}{}{Seš ÚPLNÌ mrtvá liška!}
{32545}{}{Ohni se na chvilku...}
{32546}{}{Mám pro tebe dáreèek...}
{32547}{}{Chceš kousek?}
{32548}{}{Støílí... a zasahuje!}
{32549}{}{Co takhle trochu lásky?}
#
# target being missed
#
{32560}{}{Jó jó jó!}
{32561}{}{Tak je to správnı!}
{32562}{}{Ha ha ha!}
{32563}{}{Bude to nìkdy lepší?}
{32564}{}{Nìjak ti to nejde!}
{32565}{}{Au! Jau! Haha, dìlám si srandu...}
#
############################################
# 32600 Shi Guards
############################################
#
#  running away
#
{32600}{}{Aiee!}
{32601}{}{Další øada! Vystøídejte nás!}
{32602}{}{Ustupte! Ustupte!}
{32603}{}{Zdrháme! Zdrháme! }
{32604}{}{Uteète!}
#
# moving in to attack
#
{32620}{}{Pøiprav se na zneuctìní...}
{32621}{}{Pilíøe nebes se otøásají...}
{32622}{}{Pilíøe nebes se otøásají...}
{32623}{}{Sekaná Expres pøichází...}
{32624}{}{Varovali jsme tì!}
{32625}{}{Jeden ex Gajdin do odpadkù!}
{32626}{}{Sbohem, mrtvolo...}
#
# attacking
#
{32640}{}{Nìco pro tebe...}
{32641}{}{... za maminku ....}
{32642}{}{... za tatínka ....}
{32643}{}{... za sestøièku ....}
{32644}{}{... za babièku!!!}
{32645}{}{Zmizni!}
{32646}{}{Chcípni! }
{32647}{}{Buï sbohem!}
{32648}{}{Nech mì, a znièím tvou èest!}
{32649}{}{Tvá pøítomnost mì uráí.}
#
# target being missed
#
{32660}{}{Záleí na reflexech!}
{32661}{}{Gajdin! Fuj!}
{32662}{}{::ach::: Kdy budeme bojovat s nìkım SCHOPNİM?}
{32663}{}{Uam. Nuda, nuda.}
{32664}{}{Kdy mì zaèneš bít?}
{32665}{}{Zaèínám mì to nudit...}
#
############################################
# 32700 Elron Hit Locations
############################################
#
# target hit in head
#
{32700}{}{Mùj oblièej! Mùj oblièej!}
{32701}{}{Hvìzdnı otèe! Uzdrav mì!}
{32702}{}{Jauvajs! Potøebuju studenı obklad!}
#
# target hit in left arm
#
{32710}{}{Au, moje ruka}
{32711}{}{Au!}
{32712}{}{Zlomili mi ruku!}
#
# target hit in right arm
#
{32720}{}{Au, moje ruka}
{32721}{}{Wahhhh!}
{32722}{}{U Elrona! Moje ruka!}
#
# target hit in torso
#
{32730}{}{Au! To fakt bolí!}
{32731}{}{Asi omdlím...}
{32732}{}{Jauvajs!}
{32733}{}{Hvìzdnı Otèe! Pomoz mi!}
{32734}{}{To bolí!}
{32735}{}{Nech mì bıt!}
{32736}{}{Ohhh, bolest!}
#
# target hit in right leg
#
{32760}{}{Au, moje noha!!}
{32761}{}{Moje koleno!}
{32762}{}{Au!}
#
# target hit in left leg
#
{32770}{}{Jau! Moje koleno!}
{32771}{}{Moje koleno!}
{32772}{}{Aaaarrrrggghhh!}
#
# target hit in eyes
#
{32780}{}{Au!! Moje oèi!}
{32781}{}{Mùj oblièej! Moje oèi! Arrrrgh!}
{32782}{}{Moje oèi!}
#
# target hit in groin
#
{32790}{}{Ooooooooo, mùj rozkrok! Ooooooo...}
{32791}{}{Aùùù... To bolí!!!}
{32792}{}{Urp!}
{32793}{}{::gasp::}
{32794}{}{Nemùu...dıchat...}
{32795}{}{...dobøe...e...u...jsem...sterilní...}
#
############################################
# 32800 Elron Guards
############################################
#
#  running away
#
{32800}{}{Hvìzdnı Otèe! Pomo nám!}
{32801}{}{Hvìzdnı Otèe! Proè jsi nám nepomohl?}
{32802}{}{Chci ít, a uvidím Quetzel!}
{32803}{}{Eeek!}
{32804}{}{Spaste své duše!}
{32805}{}{OZ-9! Pomo nám!}
#
# moving in to attack
#
{32820}{}{"Upravím" tì tak silnì, e ...}
{32821}{}{Budu rád, a se zbavíme takovıch jako ty...}
{32822}{}{Škoda e nezaiješ naši záønou budoucnost...}
{32823}{}{Nikdy neodmítej Hvìzdného Otce.}
{32824}{}{Elron tì rozdrtí!}
{32825}{}{Jsme Ozbrojená pìst Hvìzdného Otce!}
{32826}{}{Smrt nezasvìcenım!}
{32828}{}{Ber to jako prohlídku u doktora. Trochu tì proklepu...}
#
# attacking
#
{32840}{}{Jsi neèisté prase!}
{32841}{}{Za Hvìzdného Otce!}
{32842}{}{Za Elrona!}
{32843}{}{Za Quetzel!}
{32844}{}{Za OZ-9!}
{32845}{}{Zemøi, neèistá osobo!}
{32846}{}{Znesvìcuješ nás svou pøítomností!}
{32847}{}{To je za OZ-9!}
#
# target being missed
#
{32860}{}{Tvoje energie je nezamìøená!}
{32861}{}{Kdybys byl jedním z nás, zasáhl bys mnì!}
{32862}{}{Tvá energie je neèistá!}
{32863}{}{Nepokoušej se zasáhnout pravého vìøícího!}
{32864}{}{Neschopnost, kam se jenom podíváš. Pouze my jsme vyvolení...}
{32865}{}{Neèistı!}
#
############################################
# 32900 Ron Cruz/Nikki Goldman
############################################
#
#  running away
#
{32900}{}{Já jsem pøece filmová hvìzda!}
{32901}{}{Celebrita prochází, rozejdìte se!}
{32902}{}{Tohleto ve scénáøi nebylo!}
{32903}{}{Hvìzdnı otèe! Pomoz!}
{32904}{}{Ale já jsem slavná osobnost!}
#
############################################
# 33000 OZ-9
############################################
#
#  running away
#
{33000}{}{Hvìzdnı Otèe! Pomoz mi!}
{33001}{}{Ne! Mì ne!}
{33002}{}{Prosím, zabíjej chvíli nìkoho jiného!}
{33003}{}{Nezabíjej mì! Já jsem OZ-9!}
{33004}{}{Stráe! Pomozte mi!}
{33005}{}{Nemùeš mì zabít! Jsem pøíliš dùleitá osobnost!}
#
# moving in to attack
#
{33020}{}{Mohls bıt jedním z nás, hlupèe.}
{33021}{}{Hlupací vdy útoèí na lepší lidi, slepí jsou ve své závisti...}
{33022}{}{Tvoje neèistost pøímo záøí!}
{33023}{}{Škoda, e nejsi jedním z nás...Tak tì musíme zabít!}
{33024}{}{Hvìzdnı Otec tì srazí na kolena!}
{33025}{}{Nikdy neuvidíš planetu Quetzel.}
{33026}{}{Jsi zrádce lidské evoluce!}
{33028}{}{Nehodnı a neèistı!}
#
# attacking
#
{33040}{}{Mùj dotek tì oèistí!}
{33041}{}{Dotknu se tì a ty zemøeš!}
{33042}{}{Ve jménu Elrona!}
{33043}{}{Pro vìtší slávu Hvìzdného Otce!}
{33044}{}{Poci zlost Elrona Velkolepého, nevìøící!}
{33045}{}{Tohle tì zoptimalizuje!}
#
# target being missed
#
{33060}{}{Hvìzdnı Otec mì zachránil!}
{33061}{}{Elron mì ochraòuje, jsem neporazitelnı!}
{33062}{}{Jsi neschopnı dùkaz, e evoluce je nutná. Pøidej se k nám! Nebo radìji zemøi!}
{33063}{}{Tvoje energie je špatná.}
{33064}{}{Nedokáeš se soustøedit?}
#
############################################
# 33100 OZ-7
############################################
#
#  running away
#
{33100}{}{Hvìzdnı Otèe! Pomoz mi!}
{33101}{}{Radši bych byl na Quetzelu!}
{33102}{}{Mì ne! Nezabíjej mì!}
{33103}{}{Já jsem malá ryba, nech mì bıt!}
{33104}{}{Já nerozhoduju, já jenom poslouchám rozkazy!}
{33105}{}{Já nejsem ten, co ho hledáš, já ne!}
#
# moving in to attack
#
{33120}{}{Radši bych to nedìlal, ale...}
{33121}{}{Nechceš se radìji vzdát?}

{33122}{}{Nemùeme se nìjak domluvit?}
{33123}{}{Kdy OZ-í øíká, e jsi špatná osoba, pak to musí bıt pravda...}
{33124}{}{Za...um... vìtší slávu Elronovu!}
{33125}{}{Boj je špatnı, ale v tomhle pøípadì je asi nutnı...}
{33126}{}{Nejsem moc dobrı ve vyhroování a èlovìk, co mi píše texty, je momentálnì po opici, take: ZHYÒ!}
{33128}{}{Omlouvám se, kdybych ti snad ublíil, ale je to nutné!}
#
# attacking
#
{33140}{}{Pozor!}
{33141}{}{::zavøel oèi a se zamraèenım vırazem v oblièeji útoèí::}
{33142}{}{Další útok, u aby to skonèilo...}
{33143}{}{Kdy uteèeš, budeme to mít všichni jednodušší...}
{33144}{}{No tak! Uteè!}
{33145}{}{Kšá! Kšá!}
{33146}{}{Pøestaò bojovat!}
{33147}{}{Bu bu bu!}
{33148}{}{Voníš jako kvìtina!}
{33149}{}{Pøece se nìjak dohodneme?}
#
# target being missed
#
{33160}{}{Proè mi chceš ublíit?}
{33161}{}{Co jsem ti udìlal?}
{33162}{}{Nemusíme bojovat!}
{33163}{}{Nechci ti ublíit, prosím pøestaò!}
{33164}{}{Neubliuj mi! Já ti taky nechci ublíit!}
{33165}{}{Jsme rozumní dospìlí lidé, nemùeme se nìjak dohodnout?}

############################################
# 33200 Hovado Hit Locations
############################################
#
# target hit in head
#
{33200}{}{Mám zlomenou èelist!}
{33201}{}{Moje tváø! Au au!}
{33202}{}{Potom bude jizva, hrome...}
#
# target hit in left arm
#
{33210}{}{Moje ruka! S tou píšu!}
{33211}{}{Mùj loket!}
{33212}{}{Hej! Dávej pozor!}
#
# target hit in right arm
#
{33220}{}{Ahhh! Aiee! Ahh!}
{33221}{}{Wahhhh!}
{33222}{}{Au!  Moje zápìstí!}
#
# target hit in torso
#
{33230}{}{Dostal jsem to do ledviny!}
{33231}{}{Mùj ... solar! Nemùu... dıchat!}
{33232}{}{::kymácí se::}
{33233}{}{Uffffff!}
{33234}{}{Tohle opravdu není nutné...}
{33235}{}{Okej, tohle bolelo.}

{33236}{}{Ohhh... owwww}
#
# target hit in right leg
#
{33260}{}{Mùj kotník!}
{33261}{}{Moje koleno!}
{33262}{}{Au!}
#
# target hit in left leg
#
{33270}{}{Oh, moje achilovka! Je pøetrená!}
{33271}{}{Moje koleno!}
{33272}{}{Budu kulhat...}
#
# target hit in eyes
#
{33280}{}{Moje rohovka! Mám ji z oka odtrenou!}
{33281}{}{Moje oko! Mám znièené oko! Uvìdomuješ si, co to znamená?!}
{33282}{}{Nevidím! Jsem slepı!}
#
# target hit in groin
#
{33290}{}{To...je...ta...nejvìtší...bolest...kterou...}
{33291}{}{Matko....}
{33292}{}{::drí se za rozkrok a úpí::}
{33293}{}{Svatá Matko BOÍ!}
{33294}{}{Hmmm. Au. Hmmm.}
{33295}{}{Za chvíli budu v šoku....teï! ÁÁÁ!}
#
####################################################################################
#
# 36000        Special Encounters (Randoms)
#
#                   36000 Kaga (Hit Locations)
#                   36100 Kaga (Combat Messages - Area 1)
#                   36200 Kaga (Combat Messages - Area 2)
#                   36300 Kaga (Combat Messages - Area 3)
#                   36400 Kaga (Combat Messages - Area 4)
#                   36500 Kaga (Combat Messages - Area 5)
#                   36600 Super Mutant (Master Army) - Hit Locations
#                   36700 Super Mutant (Master Army) - Combat Messages
#                   36800 Bounty Hunters - Combat Messages
#
####################################################################################
#
############################################
# 36000 Kaga (Hit Locations)
############################################
#
# target hit in head
#
{36000}{}{Hoho! Do Kagovy hlavy nìco narazilo!}
{36001}{}{Au! Hlava bolí mì!}
{36002}{}{Uf! Kagova hlava jako v ohni jest!}
#
# target hit in left arm
#
{36010}{}{Moje ruka!}
{36011}{}{Au! Ještì e je Kaga pravák!}
{36012}{}{Au!!}
#
# target hit in right arm
#
{36020}{}{Au, moje ruka}
{36021}{}{Zlomili mi ruku!}
{36022}{}{Toho budeš litovat! Do støehu!}
#
# target hit in torso
#
{36030}{}{(Br...)}
{36031}{}{Jenom škrábnutí!}
{36032}{}{Grrr!}
{36033}{}{Toho budeš litovat! Do støehu!}
{36034}{}{Nechej toho, dokud se ti daøí!}
{36035}{}{Dobrá rána. Teï já...}
#
# target hit in right leg
#
{36060}{}{Au, moje noha!}
{36061}{}{Za to zaplatíš!}
{36062}{}{Ah! MOJE NOHA!}
#
# target hit in left leg
#
{36070}{}{Moje noha!}
{36071}{}{Unh. Míøíš nìjak nízko!}
{36072}{}{Do nohy? No to snad ne? Co si o sobì myslíš?}
#
# target hit in eyes
#
{36080}{}{Mám krev v oèích, do psí díry!}
{36081}{}{Moje oko! Za to mi zaplatíš!}
{36082}{}{Bastarde!}
#
# target hit in groin
#
{36090}{}{Ooooo! Pøestávka, musím si nìco zvednout...}
{36091}{}{OOOO! Kaga se tenhle útok taky nauèí a pak uvidíš!}
{36092}{}{Urg! Hej kámo, ty tam dole v gatích? Okej?}
{36093}{}{To.... vzzzzz. bolelo!}
{36094}{}{Urp!}
{36095}{}{Polk!}
#
############################################
# 36100 Kaga (Combat Messages) Area 1
# Check for pre attack floats See Kaga.doc
############################################
#
#  running away
#
{36100}{}{Ještì se uvidíme!}
{36101}{}{Já se vrátím...A se mnou pøijde Bruce Willis!}
{36102}{}{To je poprvé, co mì nìkdo porazil!}
{36103}{}{Mám nového koníèka! Dostat tì!}
{36104}{}{Ještì o mì uslyšíš!}
{36105}{}{Za to zaplatíš! Pozdìji!}
#
# moving in to attack
#
{36120}{}{Já mìl bıt Vyvolenı! Ne ty!}
{36121}{}{Arroyo bude litovat, e mì vyhnali!}
{36122}{}{Pomsta bude MÁ!}
{36123}{}{Kaga tì pošle do dalšího ivota!}
{36124}{}{Další Vyvolenı na zabití!}
#
# attacking
#
{36140}{}{Tvoje maminka ti nepomùe...}
{36141}{}{To si vychutnám!}
{36142}{}{Oooo, to muselo bolet!}
{36143}{}{Tvoji hlavu vezmu zpátky ke Starší!}
{36144}{}{Seeru ti játra! Doufám, e moc nechlastáš...}
{36145}{}{Doufám, e nezemøeš tak rychle jako ostatní!}
{36146}{}{Další Vyvolenı na zabití!}
{36147}{}{Chcípni! }
{36148}{}{Øvi. Øvi pro mì.}
#
# target being missed
#
{36160}{}{Mnì nemùeš ublíit!}
{36161}{}{Duchové mì ochraòují!}
{36162}{}{Doufám, e to nebyla tvoje nejlepší rána.}
{36163}{}{Hahahahaha. Kaga se nemusel ani sehnout!}
{36164}{}{Nemùeš mì zabít, nejdøív se musíš trefit...}
{36165}{}{Pomalı, vole.}
#
############################################
# 36200 Kaga (Combat Messages) Area 2
# Check for pre attack floats See Kaga.doc
############################################
#
#  running away
#
{36200}{}{Ještì se uvidíme!}
{36201}{}{Já se vrátím...A se mnou pøijde Bruce Willis!}
{36202}{}{Nemùeš zabít Kagu Velkolepého!}
{36203}{}{Máš štìstí! Kaga má ještì další kšeftíky, take pøíštì...}
{36204}{}{Ty a Kaga se ještì setkáte...}
{36205}{}{Za to zaplatíš! Pozdìji!}
#
# moving in to attack
#
{36220}{}{A tì zabiju, spálím Arroyo na popel!}
{36221}{}{Všichni se mì bojí. I ty budeš.}
{36222}{}{Kaga si tvoji hlavu nechá jako trofej.}
{36223}{}{Vzdej se a Kaga ti daruje rychlou smrt.}
#
# attacking
#
{36240}{}{Pocítíš zlost Kagy Ohromného!}
{36241}{}{Kaga tì zabije!}
{36242}{}{To si vychutnám!}
{36243}{}{OO, Kaga tì skoro lituje...}
{36244}{}{Tvoji hlavu vezmu zpátky ke Starší!}
{36245}{}{Vytrhnu ti srdce kapesním noíkem a seeru ho pøed tvıma chladnoucíma oèima!}
{36246}{}{Doufám, e nezemøeš tak rychle jako ostatní!}
{36247}{}{Další Vyvolenı na zabití!}
{36248}{}{Chcípni! }
{36249}{}{Øvi. Øvi pro mì.}
#
# target being missed
#
{36260}{}{Mnì nemùeš ublíit!}
{36261}{}{Duchové mì ochraòují!}
{36262}{}{Doufám, e to nebyla tvoje nejlepší rána.}
{36263}{}{Hahahahaha. Kaga se nemusel ani sehnout!}
{36264}{}{Nemùeš mì zabít, nejdøív se musíš trefit...}
{36265}{}{Pomalı, vole.}
#
############################################
# 36300 Kaga (Combat Messages) Area 3
# Check for pre attack floats See Kaga.doc
############################################
#
#  running away
#
{36300}{}{Tohle zaèíná bıt nepøíjemnı zlozvyk...}
{36301}{}{Kaga potøebuje ještì trochu potrénovat, tak tøi ètyøi levely...}
{36302}{}{Já se vrátím. A pak tì zabiju, jako e se Kaga Dokonalı jmenuju!}
{36303}{}{Máš štìstí! Kaga má ještì další kšeftíky, take pøíštì...}
{36304}{}{Ty a Kaga se ještì setkáte...}
{36305}{}{Za to zaplatíš! Pozdìji!}
#
# moving in to attack
#
{36320}{}{Kaga a Vyvolenı se opìt setkávají...}
{36321}{}{Skonèeme to...}
{36322}{}{Budeš litovat, e tvá ubohá tìlesná schránka vùbec zaslechla jméno Kaga!}
{36323}{}{Mé schopnosti se od našeho posledního setkání znìkolikanásobily!}
#
# attacking
#
{36340}{}{Poci zlost Kagy Ohromného!}
{36341}{}{To si vychutnám!}
{36342}{}{OO, Kaga tì skoro lituje...}
{36343}{}{Tvoji hlavu vezmu zpátky ke Starší!}
{36344}{}{Vytrhnu ti srdce kapesním noíkem a seeru ho pøed tvıma chladnoucíma oèima!}
{36345}{}{Doufám, e nezemøeš tak rychle jako ostatní!}
{36346}{}{Další Vyvolenı na zabití!}
{36347}{}{Chcípni! }
{36348}{}{Øvi. Øvi pro mì.}
#
# target being missed
#
{36360}{}{Mnì nemùeš ublíit!}
{36361}{}{Duchové mì ochraòují!}
{36362}{}{Doufám, e to nebyla tvoje nejlepší rána.}
{36363}{}{Hahahahaha. Kaga se nemusel ani sehnout!}
{36364}{}{Nemùeš mì zabít, nejdøív se musíš trefit...}
{36365}{}{Pomalı, vole.}
#
############################################
# 36400 Kaga (Combat Messages) Area 4
# Check for pre attack floats See Kaga.doc
############################################
#
#  running away
#
{36400}{}{Tohle zaèíná bıt nepøíjemnı zlozvyk...}
{36401}{}{Kaga potøebuje ještì trochu potrénovat, tak tøi ètyøi levely...}
{36402}{}{Tohle není naposled, co vidíš Kaga!}
{36403}{}{Máš štìstí! Kaga má ještì další kšeftíky, take pøíštì...}
{36404}{}{Ty a Kaga se ještì setkáte...}
{36405}{}{Za to zaplatíš! Pozdìji!}
#
# moving in to attack
#
{36420}{}{Vyvolenı se nikdy nevrátí do Arroya!}
{36421}{}{Kaga tì rozdrtí!}
{36422}{}{Kaga necítí strach!}
{36423}{}{Kaga tì nauèí nové triky, které zná...}
#
# attacking
#
{36440}{}{Poci zlost Kagy Ohromného!}
{36441}{}{Nehıbej se, a se Kaga trefí kriticky.}
{36442}{}{To si vychutnám!}
{36443}{}{OO, Kaga tì skoro lituje...}
{36444}{}{Tvoji hlavu vezmu zpátky ke Starší!}
{36445}{}{Vytrhnu ti srdce kapesním noíkem a seeru ho pøed tvıma chladnoucíma oèima!}
{36446}{}{Doufám, e nezemøeš tak rychle jako ostatní!}
{36447}{}{Další Vyvolenı na zabití!}
{36448}{}{Chcípni! }
{36449}{}{Øvi. Øvi pro mì.}
#
# target being missed
#
{36460}{}{Mnì nemùeš ublíit!}
{36461}{}{Duchové mì ochraòují!}
{36462}{}{Doufám, e to nebyla tvoje nejlepší rána.}
{36463}{}{Hahahahaha. Kaga se nemusel ani sehnout!}
{36464}{}{Nemùeš mì zabít, nejdøív se musíš trefit...}
{36465}{}{Pomalı, vole.}
#
############################################
# 36500 Kaga (Combat Messages) Area 5
# Check for pre attack floats See Kaga.doc
############################################
#
#  running away
#
{36500}{}{}
{36501}{}{}
{36502}{}{}
{36503}{}{}
{36504}{}{}
{36505}{}{}
#
# moving in to attack
#
{36520}{}{Kaga u je pøipravenı. Zemøeš, Vyvolenı.}
{36521}{}{Pro Kagu nejsi protivník.}
{36522}{}{Kaga ukonèí tvou pou.}
{36523}{}{Budeš Kagovi chybìt.}
#
# attacking
#
{36540}{}{Poci zlost Kagy Ohromného!}
{36541}{}{Kaga bude slavnı, tvá smrt ho proslaví v celé zemi...}
{36542}{}{To si vychutnám!}
{36543}{}{OO, Kaga tì skoro lituje...}
{36544}{}{Tvoji hlavu vezmu zpátky ke Starší!}
{36545}{}{A zde konèí Vyvolenı...}
{36546}{}{Kaga tì teï musí zabít...}
{36547}{}{Chcípni! }
{36548}{}{Øvi. Øvi pro mì.}
#
# target being missed
#
{36560}{}{Mnì nemùeš ublíit!}
{36561}{}{Duchové mì ochraòují!}
{36562}{}{Doufám, e to nebyla tvoje nejlepší rána.}
{36563}{}{Hahahahaha. Kaga se nemusel ani sehnout!}
{36564}{}{Nemùeš mì zabít, nejdøív se musíš trefit...}
{36565}{}{Pomalı, vole.}
#
#
############################################
# 36600 Super Mutant (Master Army) - Hit Locations
############################################
#
# target hit in head
#
{36600}{}{Ahhhgh! Mùj oblièej!}
{36601}{}{Mùj oblièej! Budeš trpìt!}
{36602}{}{Ahhhgh! Roztrhám tì na kousky!}
#
# target hit in left arm
#
{36610}{}{Ahhhgh!}
{36611}{}{Au! Málem jsi mì poranil!}
{36612}{}{Ahhhgh! Za to ti zlomím krk!}
#
# target hit in right arm
#
{36620}{}{Ahhhgh!}
{36621}{}{Au! Málem jsi mì poranil!}
{36622}{}{Ahhhgh! Za to ti zlomím krk!}
#
# target hit in torso
#
{36630}{}{Uf!}
{36631}{}{Grrr!}
{36632}{}{Za to tì zabiju!}
{36633}{}{Nemùeš mi ublíit, kdy z tebe bude mrtvola!}
{36634}{}{Smìju se tvım slabouèkım útokùm!}
{36635}{}{Oh!}
{36636}{}{Zabiju! }
{36637}{}{Grrr! Zaèínáš mì zlobit!}
{36638}{}{Agh!}
{36639}{}{Tohle ti vrátím i s úroky!}
{36640}{}{Uf!}
{36641}{}{Jauvajs!}
{36642}{}{Hmm, s tebou budou problémy...}
{36643}{}{Grr! Na tvoji smrt se u tìším!}
{36644}{}{Mùeš mì zranit, ale vyhrát nemùeš!}
{36645}{}{Au! Nebyl dobrı nápad dotıkat se mì!}
#
# target hit in right leg
#
{36660}{}{Ahhhgh! Moje noha}
{36661}{}{Tomu øíkáš bolest? Smìju se!}
{36662}{}{Ahhhgh! Za to ti zlomím krk!}
#
# target hit in left leg
#
{36670}{}{Ahhhgh! Moje noha}
{36671}{}{Tomu øíkáš bolest? Smìju se!}
{36672}{}{Ahhhgh! Za to ti zlomím krk jako vìtvièku!}
#
# target hit in eyes
#
{36680}{}{Ahhhgh! Mizernı èlovìku! Jsem slepı!}
{36681}{}{Ahhhgh! Bolest! Bolest! Já ji nemohu cítit!}
{36682}{}{Ahhhgh! Budu tì muèit mnoho dnù!}
#
# target hit in groin
#
{36690}{}{To je lidská slabost!}
{36691}{}{Tomu øíkáš bolest? Smìju se!}
{36692}{}{Jsi idiot, èlovìèe! My jsme nadøazená rasa!}
{36693}{}{Proè mì mlátíš na tomhle místì?}
{36694}{}{Budu ti ubliovat a muèit tì, dlouho, dlouho...}
{36695}{}{Proè mì mlátíš na tomhle místì?}
#
############################################
# 36600 Super Mutant (Master Army) - Combat Messages
############################################
#
#  running away
#
{36700}{}{Uteète!}
{36701}{}{Mì nezabiješ!}
{36702}{}{Já se vrátím!}
{36703}{}{Mí pøátelé tì dostanou!}
{36704}{}{Za to zaplatíš! Zítra!}
{36705}{}{My jsme Vyvolení, nadøazená rasa! Ty zhyneš!}
#
# moving in to attack
#
{36720}{}{Tvá smrt pøichází!}
{36721}{}{Ti, kdo obtìují Vyvolené, u nikoho obtìovat nebudou!}
{36722}{}{Lidské zbranì mi neublíí! Já jsem nadøazenı, ty lidskı èerve!}
{36723}{}{Budeš trpìt! Trpìt! Moc!}
{36724}{}{Kdy bojuju, zabíjím! Tebe zabiju pomalu!}
{36725}{}{Kdo je tak pitomı, e nás chce obtìovat? Zemøi!}
{36726}{}{Vidím nepøítele! Zdrtím je ve své pìsti!}
{36727}{}{Budeš trpìt! Trpìt! Moc!}
#
# attacking
#
{36740}{}{Nyní zemøeš, èerve!}
{36741}{}{U tì nikdo nezachrání!}
{36742}{}{Dám ti bolest! Dám ti jí mnoho! Budeš trpìt dokonce ivota, celou hodinu!}
{36743}{}{Nyní zemøeš, èerve! Bolestivou smrtí!}
{36744}{}{Zemøi, lidskı èerve! Zemøi!}
{36745}{}{Nyní zemøeš, èerve! Zemøeš bolestivou smrtí!}
{36746}{}{Uij si bolest, nic jiného ti nezùstane!}
{36747}{}{Rozdrtím tì!}
{36748}{}{S Vyvolenımi bojovat nemùeš! Rozdrtíme tì jako komára!}
{36749}{}{Zemøi, èlovìèe! Zemøi, dokud mùeš!}
#
# target being missed
#
{36760}{}{Proè se snaíš? Odpor je zbyteènı!}
{36761}{}{Lidé jsou slaboši!}
{36762}{}{Nemáš ádnou sílu!}
{36763}{}{Ha ha! Chceš, abych zemøel smíchy, èerve?}
{36764}{}{To byl útok?}
{36765}{}{My jsme Vyvolení, èerve!}
#
####################################################################################
#
#                    Party Members
#
####################################################################################
#                     
#                     Notes
#                     
#                     00-09 Hit in Head
#                     10-19 Hit in Left Arm
#                     20-29 Hit in Right Arm
#                     30-59 Hit in Torso (Generic Non-Called Shot Hit)
#                     60-69 Hit in Right Leg
#                     70-79 Hit in Left Leg
#                     80-89 Hit in Eyes
#                     90-99 Hit in Groin
#                     00-19 Running Away
#                     20-39 Moving in to Attack
#                     40-59 Attacking
#                     60-79 Target being Missed
#
#                     40000 Sulik *
#                     40400 Vic
#                     40800 MacRae *
#                     41200 Lenny *
#                     41600 Marcus *
#                     42000 Myron *
#                     42400 Davin
#                     42800 Miria
#                     43200 Laddie
#                     43600 Cyberdog
#                     44000 Robo-Brain (Idiot/Chimp) *
#                     44400 Robo-Brain (Human/Cybernetic) *
#                     44800 Goris **
#
####################################################################################
#
############################################
# 44800 Goris
############################################
#
# target hit in head
#
{44800}{}{Mám tvrdou lebku, ale stejnì to bolelo.}
{44801}{}{Mám to ale zatracenì silnou kocovinu.}
{44802}{}{Umph. Do hlavy né, blbe!}
{44803}{}{Já tì asi taky zaènu mlátit do hlavy!}
{44804}{}{Arrrgh! Zemìtøesení?}
#
# target hit in left arm
#
{44810}{}{Zabiju tì druhou rukou!}
{44811}{}{Na to, abych ti zkazil plány na veèer, nepotøebuju obì ruce!}
{44812}{}{Tuhle ruku stejnì nepouívám.}
{44813}{}{Au! Hodil by se kousek obvazu...}
{44814}{}{Jedna ruka dole, druhá do boje!}
#
# target hit in right arm
#
{44820}{}{Hej, teï jsem tì s touhle rukou chtìl vykuchat!}
{44821}{}{Zatracená paøáta, bolí...}
{44822}{}{Takové tıpky, jako seš ty, zvládám jedinou rukou.}
{44823}{}{Pravá ruka... arrgh!}
{44824}{}{Trefils mì do ruky. A já ti tvoji urvu!}
#
# target hit in torso
#
{44830}{}{Umf...nemùu...dıchat...}
{44831}{}{Hmmm, mám pocit, e mi chybí pár eber...}
{44832}{}{Jau! Nesnáším rány do bøicha...}
{44833}{}{Arg! Bolí mì hrudník!}
{44834}{}{Na kozy mi nešahej!}
{44835}{}{To je boj, nebo se jenom snaíš upoutat moji pozornost?}
{44836}{}{Nezapomeò mì upozornit, kdy by to mìlo bolet, a nezapomenu øvát...}
{44837}{}{To tì nauèila maminka, co?}
{44838}{}{Oh, ta bolest (zív). Prosím, nebij mì u.}
{44839}{}{Tomu øíkáš zasah? Já ti ukáu, jak se to má dìlat!}
{44840}{}{Za to ti zkopu prdel do krychlièky!}
{44841}{}{Uau! To píchlo! Jako u doktora!}
{44842}{}{Kvùli tomuhle jsem odešel z Vaultu?}
{44843}{}{Uaaaam. Asi budu potøebovatdovolenou, zaèínáš mì unavovat...}
{44844}{}{Jau! To bolelo, ty idiote.}
{44845}{}{Ani jsem to necítil...}
{44846}{}{Kde je stimpak, kdy ho potøebuju? No nic, napiju se aspoò tvojí krve...}
{44847}{}{Jakmile se zase budu moct hıbat, dostaneš pár facek...}
{44848}{}{Na mì bolest nepùsobí! Já jsem deathclaw, Dráp smrti!}
{44849}{}{Tvùj ksicht bude brzo vypadat jako místo, kde nìjakou dobu táboøili medvìdi...}
#
# target hit in right leg
#
{44860}{}{Skvìlı. Budu jedinej kulhající deathclaw na svìte...}
{44861}{}{Jauvajs! Moje noha...}
{44862}{}{Za tohle ti utrhnu tvoji nohu...}
{44863}{}{Ta noha mi bude chybìt...}
{44864}{}{Nepotøebuju obì nohy na to, abych z tebe udìlal tatarskı biftek...}
#
# target hit in left leg
#
{44870}{}{Sqìlı. Do nohy. Auau. Máš radost?}
{44871}{}{Zatracenì! Noha...}
{44872}{}{Do nohy ne, u tak nemùu poøádnì bìhat...}
{44873}{}{Já mám chromou nohu, ale z tebe bude úplnı kripl, a s tebou skonèím!}
{44874}{}{Arrgh! To koleno bolí!}
#
# target hit in eyes
#
{44880}{}{Nevidím!}
{44881}{}{Do oèí ne!}
{44882}{}{Krev...v oèích... nevidím!}
{44883}{}{Nevidím tì, ale smrdíš dost na to, abych se mohl orientovat jenom po èichu...}
{44884}{}{Hmm, kde mám ty brejle...}
#
# target hit in groin
#
{44890}{}{Do koulí, to je dost zbabìlı úder. Ještì, e nejsem èlovìk!}
{44891}{}{ádnı...rány...pod...pás!}
{44892}{}{Tohle je pìknì sprostı! Co kdybych ti to udìlal já?}
{44893}{}{NESNÁŠÍM! Tohle zkrátka nesnáším!}
{44894}{}{Jau jau. Ještì e moje pohlavní orgány jen tak nepoškodíš. Ale tebe já poškodím hned!}
#
#  running away
#
{44900}{}{Berem roha!}
{44901}{}{Jdu pryè!}
{44902}{}{Ústup!}
{44903}{}{Ustupte! Ustupte!}
{44904}{}{Mizím pryè!}
{44905}{}{Noièky, nezklamte mì!}
{44906}{}{Uhnìte, já beru roha!}
{44907}{}{Já neutíkam, to je strategickı ústup!}
{44908}{}{U mì to tu sere! Mìním vzduch!}
{44909}{}{Musím se odsud dostat!}
#
# moving in to attack
#
{44920}{}{Pojï sem, a ti mùu jednu fláknout!}
{44921}{}{Seš moje nová hraèka!}
{44922}{}{Buï ty nebo já... a já hlasuju pro tebe!}
{44923}{}{To je tvùj pohøeb, srágoro!}
{44924}{}{Pojï sem a jednu slízneš!}
{44925}{}{Pøiprav se potkat svoji zkázu!}
{44926}{}{Rozluè se se ivotem. Jdu ukonèit tvoji mizérii.}
{44927}{}{Bude tì to bolet! U se tìšíš?}
{44928}{}{Sranda zaèíná! A ty konèíš!}
{44929}{}{Do boje! Krleš!}
{44930}{}{Bij zabij!}
{44931}{}{Èas natáhnou pracku a pøitáhnout si novou hraèku...}
{44932}{}{Do boje! Anihilujte je!}
{44933}{}{Spadnu na tebe jako tuna tìch hranatejch vìci, co si z nich dìlají lidi domy!}
{44934}{}{Rozcvièka? To jsem si pøál!}
{44935}{}{Jdeme na to osobnì, ne? Krleš!!!!!}
{44936}{}{Velkej hajzl jde do boje!}
{44937}{}{Útoèím!}
{44938}{}{Zamìøeno na cíl! Urrrráááááááááá!}
{44939}{}{Jako blesk, kámo, jako blesk! Urráááááá!}
#
# attacking
#
{44940}{}{Ublíím ti...moc!}
{44941}{}{Tohle tì bude bolet mnohem víc ne mì!}
{44942}{}{Nedìlej ostatním, co nechceš, aby dìlali tobì!}
{44943}{}{Jestli máš nìjakej kousek, kterı tìještì nebolí, tak ten bude další!}
{44944}{}{Kontaktní sporty. Miluju je!}
{44945}{}{Jak se jmenuješ? A mùu navštívit tvoji rodinu...}
{44946}{}{Víš co v angliètinì znamená to slovo 'death'? SMRT!}
{44947}{}{Je lepší dávat ne brát!}
{44948}{}{Doufám, e si to uívaš aspoò tak jako já!}
{44949}{}{Bolelo to? Jestli ne, tak se postarám, aby pøíštì ano!}
{44950}{}{Ajajaj! Nìco z tebe teèe!}
{44951}{}{Budeš potøebovat víc ne hromadu stimpakù, a s tebou skonèím!}
{44952}{}{Doufám, e máš zdravotní pojištìní. Budeš ho potøebovat!}
{44953}{}{Tady bum, támhle bum, všude je to bumbumbum!}
{44954}{}{Nezajímá mì, kdo si zaèal. Já to dokonèím!}
{44955}{}{Miluju zvuk, co vydává maso, dy ho trháš na kousíèky. Ty ne?}
{44956}{}{Jenom se procvièuju, to poøádnı teprv pøijde!}
{44957}{}{Jenom si brousím drápy. Nevadí ti to, doufám?}
{44958}{}{Hups! Doufám, e tenhle kousek nepotøebuješ!}
{44959}{}{Kdy padneš na zem a zaèneš prosit, moná tì nechám bıt!}
#
# target being missed
#
{44960}{}{Pøestaò tady poskakovat, a ti mùu jednu poøádnou fláknout!}
{44961}{}{Brejle. Fakt by se ti nìjakı hodily.}
{44962}{}{Nesmìj se! A se trefím já, bude tì to bolet!}
{44963}{}{Arrg! Grng! Ghrr! Thpt! (Deathclawí sprostá slova)}
{44964}{}{Zapomeò na bojovou kariéru. Nemáš na to!}
{44965}{}{Jak mùeš minout nìco tak velkıho, jako jsem já?}
{44966}{}{Jakmile se dostanu k tobì, seš v pìknım prùseru, brácho...}
{44967}{}{Seš malej pohyblivej kousek hovínka.}
{44968}{}{Jsem rád, e tohleto nevidìla moje maminka.}
{44969}{}{Hm hm hm. No nic moc.}
{44970}{}{To je teda hrùza. Radši o tom nikomu neøíkej.}
{44971}{}{To mì fakt sere!}
{44972}{}{Ok ok. To se mùe stát kadımu.}
{44973}{}{Pøíštì!}
{44974}{}{Jen tak dál!}
{44975}{}{Tohle byla nádherná ukázka pøesnıho minutí cíle!}
{44976}{}{Uam. Zaèínám stárnout, nebo co. Nìjak to nejde co?}
{44977}{}{Uau. To je zajímavı. Jak se ti to povedlo?}
{44978}{}{Jenom vzdoušek, hmm.}
{44979}{}{Hele, vedle!}
#
