#tento soubor pøeloil Somnambulus...somnambulus@hotmail.com
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#
# Text labels and messages used by EDITOR.C
#
# (These MUST match "text message" enumeration on the top of EDITOR.C)
#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#
#
{100}{}{OK}
{101}{}{VOLBY}
{102}{}{ZRUŠIT}
{103}{}{EXPORT}
{104}{}{VÌK}
{105}{}{POHLAVÍ}
{106}{}{JMÉNO}
{107}{}{MU}
{108}{}{ENA}
{109}{}{PERKY}
{110}{}{KARMA}
{111}{}{ZÁØEZY}
{112}{}{DOVED. BODY}
{113}{}{Úroveò:}
{114}{}{Zkuš:}
{115}{}{Další úroveò:}
{116}{}{CHAR. BODY}
{117}{}{DOVEDNOSTI}
{118}{}{Pøed zapoèetím hry musí postava vyuít} # 1
{119}{}{všechny charakterové body!}         # 2
#
{120}{}{Charakterové body}
{121}{}{Mnoství bodù, které se dají pøidat k nìkteré ze základních vlastností.}
{122}{}{Další úroveò}
{123}{}{Mnoství zkušenostních bodù, které potøebuješ k postupu na další úroveò.}
{124}{}{Perky}
{125}{}{Karma}
{126}{}{Záøezy}
{127}{}{Speciální schopnosti. Novı perk získáš kadou tøetí úroveò.}
{128}{}{Vliv tvıch rozhodnutí uèinìnıch bìhem hry.}
{129}{}{Poèítadlo zaznamenávající typ a poèet stvoøení, která zemøela v tvé blízkosti nebo byla tebou zabita.}
{130}{}{Dovednostní body}
{131}{}{Volné dovednostní body mùeš pouít ke zvıšení úrovnì nìkteré ze schopností.  Jak se bude tvá postava postupnì zdokonalovat, bude tì i kadé nové procento stát více dovednostních bodù.}
#
{132}{}{Na maximální úrovni.}        # 1
{133}{}{Nelze navıšit.}  # 2
{134}{}{Na minimální úrovni.}        # 1
{135}{}{Nelze sníit.}  # 2
{136}{}{Nemáš dost dovednostních bodù.}
{137}{}{Základ:}
{138}{}{TALENTY}
{139}{}{CHARAKTEROVÉ RYSY}
{140}{}{Tvá postava mùe mít maximálnì} # 1
{141}{}{tøi talenty!}               # 2
{142}{}{Pøed zaèátkem hry musíš vybrat}  # 1
{143}{}{všechny talenty!}       # 2
{144}{}{Talenty}
{145}{}{Talenty jsou schopnosti, na které se tvá postava specializuje.  U kadého talentu získá postava do zaèátku bonus +20% a zároveò se v nìm zdokonaluje dvojnásobnì rychle.  Musíš vybrat tøi.}
{146}{}{Charakterové rysy}
{147}{}{Charakterové rysy popisují tvou postavu do vìtších podrobností.  Kadı z nich má pozitivní i negativní efekt. Bìhem tvorby postavy si musíš zvolit dva.}
{148}{}{Tvá postava mùe mít maximálnì} # 1
{149}{}{dva charakterové rysy!}                     # 2
{150}{}{Dovednosti}
{151}{}{Dovednosti jsou vytrénované schopnosti. Dovednosti se zlepšují zkušenostmi nebo speciálními událostmi bìhem hry. Èím je dovednost vyšší, tím je tvá postava v daném oboru lepší.}
#
{152}{}{VYBER SI PERK}
{153}{}{VYBER SI RYS}
{154}{}{ZRUŠ RYS}
{155}{}{VYBER SI TALENT}
{156}{}{RYSY}
#
{157}{}{Pøed zaèátkem hry musí bıt všechny} # 1
{158}{}{vlastnosti v rozmezí 1 a 10!}          # 2
# Fallout 2:
{160}{}{Upozornìní: Nezmìnil jsi jméno postavy.} # 1
{161}{}{Chceš ji opravdu pouít?}        # 2

{175}{}{Další úroveò:}  # Short for Level:


#
# Abbreviated basic stat levels
#
{200}{}{Chudák}  # Terrible
{201}{}{Ubohé}    # Bad
{202}{}{Špatné}   # Poor
{203}{}{Ujde}   # Fair
{204}{}{Prùmìr}   # Average
{205}{}{Dobré}   # Good
{206}{}{Bezva} # Very Good
{207}{}{Skvìlé}  # Great
{208}{}{Úas} # Excellent
{209}{}{Super} # Heroic

#
# Abbreviated Derived/Non Derived stat names
#
{300}{}{Hit body}
{301}{}{Akèní body}
{302}{}{Tøída zbroje}
{303}{}{Boj beze zbranì}
{304}{}{Boj zblízka}
{305}{}{Odol. v. zásahu}
{306}{}{Odol. v. jedu}
{307}{}{Odol. v. radiaci}
{308}{}{Postøeh}
{309}{}{Uzdravování}
{310}{}{Kritickı zásah}
{311}{}{Nosnost}
{312}{}{Otrava}
{313}{}{Ozáøení}
{314}{}{Poškozenı zrak}
{315}{}{Zranìná pravá ruka}
{316}{}{Zranìná levá ruka}
{317}{}{Zranìná pravá noha}
{318}{}{Zranìná levá noha}

#
# Damage info texts
#
# Poisoned
{400}{}{Tvá postava byla otrávena. Dokud se nevyléèí, bude ji jed v závislosti na stupni otravy v pravidelnıch intervalech zraòovat.}
# Radiation
{401}{}{Tvá postava trpí nemocí z ozáøení. Èím vìtší dávku radiace jsi dostal, tím smrtelnìjší je efekt.}
# Eye Damage
{402}{}{Tvá postava byla vánì zasaena do oèí, a to bohuel ponìkud sníí tvé VNÍMÁNÍ.}
# Crippled right arm
{403}{}{Tvá pravá ruka je vánì zranìna - nemùeš s ní normálnì pohybovat. Pokud je zranìna jen jedna ruka, nemùeš pouívat obouruèní zbranì. Pokud obì, nemùeš pouívat vùbec ádnou zbraò.}
# Crippled left arm
{404}{}{Tvá levá ruka je vánì zranìna - nemùeš s ní normálnì pohybovat. Pokud je zranìna jen jedna ruka, nemùeš pouívat obouruèní zbranì. Pokud obì, nemùeš pouívat vùbec ádnou zbraò.}
# Crippled right leg
{405}{}{Tvá postava má vánì zranìnou pravou nohu.}
# Crippled left leg
{406}{}{Tvá postava má vánì zranìnou levou nohu.}

# Month strings
{500}{}{Leden}
{501}{}{Únor}
{502}{}{Bøezen}
{503}{}{Duben}
{504}{}{Kvìten}
{505}{}{Èerven}
{506}{}{Èervenec}
{507}{}{Srpen}
{508}{}{Záøí}
{509}{}{Øíjen}
{510}{}{Listopad}
{511}{}{Prosinec}

#
# Option menu text
#
{600}{}{ULOIT}
{601}{}{NAHRÁT}
{602}{}{EXPORT}
{603}{}{VYMAZAT}
{604}{}{OK}
{605}{}{Opravdu chceš tuto}      # line 1
{606}{}{postavu vymazat?}                 # line 2
{607}{}{ byla úspìšnì uloena.}
{608}{}{ byla úspìšnì nahrána.}
{609}{}{u existuje.}
{610}{}{Chceš ji pøepsat?}
{611}{}{Chyba ukládání }
{612}{}{Chyba nahrávání }
{613}{}{Soubor s postavou je vadnı.}
{614}{}{Data postavy jsou vadná.}
{615}{}{Chyba pøi ètení seznamu souborù!}
{616}{}{TISK}
{617}{}{HRÁÈ}
{618}{}{BLANK.GCD}

#
# ASCII text file printing text
#
{620}{}{FALLOUT 2}                   # Title line 1
{621}{}{OSOBNÍ ZÁZNAMY VAULTU-13} # Title line 2
{622}{}{hodiny} # Title line 3
# -
# -
#{000}{}{          Síla: 00          Hit body: 000/000           Postøeh: 00}
#{000}{}{       Vnímání: 00      Tøída zbroje: 000           Uzdravování: 00}
#{000}{}{      Odolnost: 00        Akèní body: 000        Kritickı zásah: 000%}
#{000}{}{      Charisma: 00     Boj na blízko: 000               Nosnost: 000 lbs.}
#{000}{}{   Inteligence: 00     Odol. zranìní: 000%}
#{000}{}{       Hbitost: 00     Odol. radiace: 000%}
#{000}{}{        Štìstí: 00         Odol. jed: 000%}
#
{623}{}{ ::: Statistika :::}
{624}{}{       Síla:}
{625}{}{        Hit body:}
{626}{}{        Postøeh:}
# -
{627}{}{     Vnímání:}
{628}{}{       Tøída zbroje:}
{629}{}{        Uzdravování:}
# -
{630}{}{      Odolnost:}
{631}{}{     Akèní body:}
{632}{}{      Kritickı zásah:}
# -
{633}{}{       Charisma:}
{634}{}{       Boj na blízko:}
{635}{}{         Nosnost:}
# -
{636}{}{   Inteligence:}
{637}{}{       Odol. zranìní:}
# -
{638}{}{        Hbitost:}
{639}{}{    Odol. radiace:}
# -
{640}{}{           Štìstí:}
{641}{}{       Odol. jed:}
# -
# -
#{000}{}{ Jméno: 01234567890        Vìk: 00        Pohlaví: ena}
{642}{}{  Jméno:}
{643}{}{Vìk:}
{644}{}{               Pohlaví:}
{645}{}{Mu}
{646}{}{ena}
#-
#{000}{}{ Level: 00                 Zkuš.: 000,000    Další úroveò: 000,000}
{647}{}{ Úroveò:}
{648}{}{                Zkuš.:}
{649}{}{Další úroveò:}
#-
{650}{}{ ::: Rysy :::}
{651}{}{ ::: Perky :::}
{652}{}{ ::: Karma :::}

#-
{653}{}{ ::: Dovednosti :::                ::: Záøezy :::}
#-
{654}{}{  ::: Inventáø :::}
#-
{655}{}{                                      Celková váha:}
{656}{}{ ::: Závislosti :::}
{657}{}{   ::: Reputace :::}

#
# Karma name strings
#
{1000}{}{Reputace (Obecnì) }
{1001}{}{Berserk}
{1002}{}{Šampión}
{1003}{}{Vrah dìtí}
{1004}{}{Závislost na Nuka Cole}
{1005}{}{Závislost na Buffoutu}
{1006}{}{Závislost na Mentatu}
{1007}{}{Závislost na Psycho}
{1008}{}{Závislost na RadAway}
{1009}{}{Závislost na alkoholu}
{1010}{}{Závislost na Jetu}
{1011}{}{Závislost na høe}
{1012}{}{THIS GOES WITH THE TEMPORARY ONE FOR DESCRIPTIONS #1112: DON'T TRANSLATE THIS}
{1013}{}{Sexpert}
{1014}{}{Vítìz ringu}
{1015}{}{Gigolo}
{1016}{}{Vylupovaè hrobù}
{1017}{}{Èlen klanu Salvatore}
{1018}{}{Manel(ka)}
{1019}{}{Pornohvìzda}
{1020}{}{Otrokáø}
{1021}{}{Pouštní panic}
{1022}{}{Èlen klanu Bishopù}
{1023}{}{Èlen klanu Mordino}
{1024}{}{Èlen klanu Wrightù}
{1025}{}{Rozvedenı(á)}

#
# Karma description strings
#
{1100}{}{Tato poloka reprezentuje tvoji obecnou reputaci. Èím je èíslo vyšší, tím jsi známìjší a uznávanìjší. Pokud je tvá reputace negativní, lidé tì nenávidí pro tvé zloèiny.}
{1101}{}{Zabil jsi spoustu lidí. A to není moc dobrı zpùsob, jak se proslavit. Lidé z podsvìtí si tì ale váí a respektují tì.}
{1102}{}{Tvé èiny z tebe udìlali šampióna. Tvùj boj se zlem a hanebností je všeobecnì známı. Èestní lidé si tì váí a uznávají tì.}
{1103}{}{Co ti k tomu mám øíct? Zabíjíš nevinné a neozbrojené dìti. Chceš opravdu slyšet, co si o tobì myslíme?}
{1104}{}{Umíš si dùkladnì vychutnat Nuka-Colu, nealko-nápoj postnukleárního svìta. Moná a moc dùkladnì.}
{1105}{}{Jsi závislı na chemikálii zvané Buffout. Musíš ho pravidelnì brát, nebo pocítíš nepøíjemné následky abstinenèních pøíznakù.}
{1106}{}{Stal ses závislım na pilulkách Mentat.  Musíš je brát, nebo máš velice nepøíjemnı absák.}
{1107}{}{Jsi feák. Pokud pravidelnì nebereš svoje Psycho, trpíš. Pokud ano, trpí ostatní.}
{1108}{}{Tvoje tìlo potøebuje stálı pøísun chemikálie Radaway. Nijak tì to sice neohrouje na ivotì, nicménì ji musíš brát pravidelnì.}
{1109}{}{Máš menší problém s alkoholem. No, vlastnì je to spíš vìtší problém.}
{1110}{}{Jsi závislı na droze zvané Jet. Musíš ho pravidelnì brát, nebo pocítíš nepøíjemné následky abstinenèních pøíznakù.}
{1111}{}{Bohuel, u je to tak. Jsi závislı na karetní høe "Tragic the Garnering". Cítíš neustálé nutkání shánìt nové a nové sady karet.}
{1112}{}{TEMPORARY - What is this?}
{1113}{}{Jsi dobrı v posteli. Zvláš pøedehra je tvou silnou stránkou. Víš, jak potìšit pøíslušníka opaèného pohlaví a vzbudit v nìm touhu si to s tebou zopakovat.}
{1114}{}{Jsi šampiónem Severní Kalifornie v tìké váze. Získal sis slávu, obdiv i lásku tisícù fanouškù... a taky bonus ke své odolnosti a dovednosti "boj zblízka".}
{1115}{}{Buï k sobì upøímnı: Jsi ochotnı spát s èímkoli, co má dvì nohy. A èas od èasu ti poèet dolních konèetin pøijde jako nechutnì diskriminující faktor.}
{1116}{}{"Mrtvı prd ví" je tvé heslo. Vykopávání mrtvol je pro tebe u nìèím víc ne jen koníèkem.}
{1117}{}{Jsi váenım èlenem Rodiny Salvatore. Kadı tì zná, kadı tì respektuje a v tom klobouku vypadáš opravdu sexy.}
{1118}{}{Nechal ses dotáhnout k oltáøi. Nekoukej se tak, to je tvùj problém, ne náš.}
{1119}{}{Jsi veliká a záøivá hvìzda domácího videa. Tvoje sexuální vıkony plus tvar a velikost tvıch pohlavních orgánù jsou známé v celém New Reno.}
{1120}{}{Byl jsi oznaèen jako èlen Gildy otrokáøù. Máš na èele tetování a tak kadı, kdo tì potká, ví hned, s kım má tu èest.}
{1121}{}{No, opravdu by sis mìl nìkteré vìci asi trochu víc procvièit. Tvoje sexuální vıkony byly mírnì øeèeno... neuspokojivé.}
{1122}{}{Jsi váenım èlenem Rodiny Bishopù. Kadı tì zná, kadı tì respektuje a v tom klobouku vypadáš opravdu sexy.}
{1123}{}{Jsi váenım èlenem Rodiny Mordino. Kadı tì zná, kadı tì respektuje a v tom klobouku vypadáš opravdu sexy.}
{1124}{}{Jsi váenım èlenem Rodiny Wrightù. Kadı tì zná, kadı tì respektuje a v tom klobouku vypadáš opravdu sexy.}
{1125}{}{Tvá drahá polovièka je u navdy pryè. Snad teï budeš šastnìjší.}

#
# Town reputations
#
{2000}{}{Idol}
{2001}{}{Oblíbenı}
{2002}{}{Uznávanı}
{2003}{}{Neutrál}
{2004}{}{Neoblíbenı}
{2005}{}{Nenávidìnı}
{2006}{}{Nepøítel è.1}

{2100}{}{Tady by se ti chtìl kadı podobat. Jsi miláèkem mìsta a pro všechny záønım pøíkladem a ukázkou toho, jak vypadá opravdovı hrdina.}
{2101}{}{Lidé tì vítají a oslavují, kdykoliv jen vejdeš na toto místo. Všichni  o tobì slyšeli a všem se to, co slyšeli, moc líbilo.}
{2102}{}{Aèkoliv nejsi vítán pøímo s otevøenou náruèí, vìtšina lidí ti v tomto místì na pozdrav odpoví. Nejsi pro nì nièím zvláš vıjimeènım.}
{2103}{}{Aèkoliv jsou obvykle vùèi cizincùm podezøívaví, proti tobì lidé na tomto místì nic nemají. Zatím.}
{2104}{}{Pro lidi v tomhle místì jsi jen dalším cizincem. Nutno dodat, e nijak zvláš vítanım.}
{2105}{}{Lidem na tomto místì jsi dokázal, e jejich poèáteèní odpor vùèi tobì, byl víc ne oprávnìnı. Všichni zmlknou, kdy se k nim pøiblííš. U tì znají.}
{2106}{}{Kdy kráèíš ulicí, všichni zmlknou a s nenávistí a strachem tì pozorují. Kadı se ti snaí vyhnout. Všichni ví, e ty jsi ta nejhorší vìc, která kdy vkroèila na toto místo.}

#
# Karma status strings
#
{3000}{}{Ochránce Zatracenıch}
{3001}{}{Stráce Pouštì}
{3002}{}{Štít Nadìje}
{3003}{}{Obránce}
{3004}{}{Poutník}
{3005}{}{Zrádce}
{3006}{}{Meè Zoufalství}
{3007}{}{Metla Pouštì}
{3008}{}{Ïáblùv spratek}

#
# Karma section titles.
#
{4000}{}{Reputace}
{4001}{}{Závislosti}

#
# Karma section descriptions.
#
{4100}{}{Tato poloka reprezentuje tvou povìst v rùznıch lokacích.}
{4101}{}{Vìci, na kterıch ses stal závislı.}

#
# Special Demo version only text
#
{5000}{}{Litujeme, ale svou postavu mùeš}   # 1
{5001}{}{exportovat pouze v plné verzi hry.}   # 2
{5002}{}{Litujeme, ale pozici mùeš uloit}    # 1
{5003}{}{pouze v plné verzi hry.}   # 2
{5004}{}{Litujeme, ale pozici mùeš nahrát} # 1
{5005}{}{pouze v plné verzi hry.}   # 2
{5006}{}{CHEAT MÓD}
{5007}{}{V demu není k dispozici.}