#tento soubor pøeložil Somnambulus...somnambulus@hotmail.com
#   Messages from skilldex.c
#
{100}{}{POUŽIJ}
{101}{}{ZRUŠIT}
{102}{}{PLÍŽIT}
{103}{}{PAKLÍÈ}
{104}{}{UKRÁST}
{105}{}{PAST}
{106}{}{1. POMOC}
{107}{}{DOKTOR}
{108}{}{VÌDA}
{109}{}{OPRAVA}

