{100}{}{Du siehst ein Computerterminal.}
{101}{}{Du siehst das Bibliotheks-Computerterminal.}
{102}{}{Du siehst ein normales Computerterminal. Es scheint zu funktionieren und eingabebereit zu sein.}
{103}{}{Du verschaffst dir Zugang zum Computer und überfliegst schnell alle verfügbaren Dateien. Du findest den Standort von Bunker 13 und kopierst ihn auf deinen PIPBoy.}
{104}{}{Du hast Schwierigkeiten, auf die Dateien zuzugreifen.}
{106}{}{Außer dem Standort von Bunker 13 enthält der Computer keine nützlichen Daten.}
