{100}{}{Ich muß Lynette warnen!}
{101}{}{Ich muß Bunkerstadt warnen!}
{102}{}{Außenweltler-Abschaum...}
{103}{}{Degenerierter Dreck...}
{104}{}{Zeit, mehr Außenweltler-Dreck zu vernichten... Sterbt, Außenweltler!}
{105}{}{Was machst du denn hier vor Bunkerstadt?}
{106}{}{Was treibst du hier in der Nähe von Bunkerstadt?}
{107}{}{Dieses Gebiet gehört zu Bunkerstadt.}
{108}{}{Paß bloß auf.}
{109}{}{Bunkerstadt ist keine Zufluchtsstätte für *jedermann*. Also zieh Leine.}
{110}{}{Leute wie du gehören nach Den.}
{111}{}{Am besten begibst du dich direkt dorthin.}
{112}{}{Hallo, Bürger.}
{113}{}{Können wir irgendwas für dich tun, Bürger?}
{114}{}{Soll dich jemand nach Bunkerstadt bringen?}
{115}{}{Was treibst du hier, Bürger, so weit von Bunkerstadt entfernt?}
{116}{}{Wir haben uns schon Sorgen gemacht, du könntest verletzt sein, Bürger.}
