{100}{}{Du siehst einen alten Ghul.}
{101}{}{Du siehst Typhon, den Sohn von Set.}
{102}{}{Du siehst einen alten Ghul, dessen Augen Intelligenz ausstrahlen.}
{103}{}{Na, wie geht's, Kindchen, willkommen im alten Ghul Haus!}
{104}{}{Was für'n Ghul?}
{105}{}{Altes Ghul Haus?}
{106}{}{Wer bist Du?}
{107}{}{Hey, schon mal vom GECK gehört?}
{108}{}{Tschüß.}
{109}{}{Noch so ein Wüsten-Baby, he? Hey, Kid, willst Du ein Geheimnis wissen?}
{110}{}{Ja!}
{111}{}{Nö.}
{112}{}{Damals, in meinen Lauf-Zeiten, hab ich ein paar Rennen gewonnen, hab ne ganze Stange Geld
 verdient. Lange her, hab die ganze Knete nicht weit von hier verbuddelt. Wenn mir jemand den
 ein oder anderen Gefallen tut, würde ich vielleicht verraten, wo meine Reichtümer verborgen
 sind.}
{113}{}{Schieß los!}
{114}{}{Kein Bedarf.}
{115}{}{Was für Reichtümer?}
{116}{}{Was für Gefallen?}
{117}{}{Ich hab andere Fragen.}
{118}{}{Tschüß!}
{119}{}{Ha. Also gut. Ich hab nichts für dich. Zieh Leine, Kind.}
{120}{}{Tschüß.}
{121}{}{Kid, zuerst mußt Du mir einen Gefallen tun.}
{122}{}{Okay!}
{123}{}{Nö!}
{124}{}{Was denn?}
{125}{}{Vergiß es.}
{126}{}{Ich bin ein alter Mann und ich habe nicht sehr viel. Hab nicht viel Abwechslung, weißt
 Du? Deshalb hätte ich gerne die Zeitschrift Cat's Paw. Finde eine für mich.}
{127}{}{Hier! [Du gibst Cat's Paw zu Typhon]}
{128}{}{Okay!}
{129}{}{Nö!}
{130}{}{Hier hast Du sie. [Du gibst Cat's Paw zu Typhon]}
{131}{}{In Ordnung. Ich komme wieder.}
{132}{}{Vergiß es.}
{133}{}{Danke für die Zeitung, Kid. Ich komme in einer Stunde oder so zu Dir zurück.}
{134}{}{Okay!}
{135}{}{Ich bin noch nicht fertig, Kid! Pssst! Kann ein alter Ghul nicht seine Ruhe haben?}
{136}{}{-Fertig-}
{137}{}{Was für Reichtümer? Kohle, Kid, ein Haufen Kohle. Genug, um jeden normalen Menschen zu
 befriedigen.}
{138}{}{Wo ist der Haken?}
{139}{}{Ich brauche kein Geld.}
{140}{}{Du bist wieder da, he? Du willst was über den Schatz wissen, was Kid?}
{141}{}{Genau!}
{142}{}{Nö.}
{143}{}{Was für ein Schatz ist das?}
{144}{}{Ja, erzähl mal.}
{145}{}{Ich habe zuerst noch andere Fragen an Dich.}
{146}{}{Nö.}
{147}{}{Die wären?}
{148}{}{Ist das das alte Ghul Haus?}
{149}{}{Hast Du schon mal was vom GECK gehört?}
{150}{}{Wer bist Du?}
{151}{}{Noch etwas, was du mir erzählen könntest?}
{152}{}{Es ist eine Art Witz. Es gibt außer alten Ghuls keine Ghuls. Wir sind alle sterilisiert,
 aber haben eine lange Lebensdauer, verstehst Du. Wir sind die erste und letzte Generation von
 Ghuls. Dieser Ort hier ist für diejenigen von uns, die sich ein wenig ausruhen wollen.}
{153}{}{Ich verstehe. Ich habe andere Fragen.}
{154}{}{Verstanden. Tschüß.}
{155}{}{Ich bin Typhon. Schon mal was von Set gehört? Er hat die Stadt Necropolis in den alten
 Zeiten geschmissen. Ich bin sein Sohn. Wurde geboren, bevor die radioaktive Verstrahlung uns
 getroffen hat, deshalb bin ich mutiert aufgewachsen.. Hat für mich nie einen anderen Weg gegeben.}
{156}{}{Erzähl mir über Set.}
{157}{}{Set? Ich habe gehört, er war ein totaler Bastard!}
{158}{}{Ich verstehe. Ich habe andere Fragen.}
{159}{}{Verstanden. Tschüß.}
{160}{}{Ja. Hatte mal welche, aber all diese hochgeborenen Menschenwesen haben sie gestohlen, um
 ihr eigenes kleines Paradies zu schaffen. Bunkerstadt ist wahrscheinlich der beste Ort, um
 welche zu finden. Entweder dort oder im Süden der Neuen Kalifornischen Republik .} 
{161}{}{Verdammt. Okay, ich habe weitere Fragen.}
{162}{}{Verdammt. Wiedersehen.}
{163}{}{"Alter Bastard" wäre eine gute Bezeichnung für den alten Mann. Daß er durch die
 radioaktive Verstrahlung in einen Ghul verwandelt worden ist, hat seinem Sinn für Humor und
 Autorität nicht viel geholfen, soviel steht fest. Klar, es hat alle etwas verwirrt in der Birne
 gemacht. Ich glaube, es war für mich eine Erleichterung, daß ich als Ghul aufgewachsen bin.}
{164}{}{Ich verstehe. Ich habe weitere Fragen.}
{165}{}{Danke. Tschüß.}
{166}{}{Und? Hast Du mir schon ein Cat's Paw Magazin besorgt?}
{167}{}{Ja. [Du gibst das Cat's Paw Magazin zu Typhon]}
{168}{}{Äh, nö.}
{169}{}{Jau. Hier ist es. [Du gibst das Cat's Paw Magazin an Typhon]}
{170}{}{Noch nicht. Ich habe noch weitere Fragen.}
{171}{}{Nö.}
{172}{}{Na, dann beeil Dich mal! Ich bin eine uralter Ghul und ich kann Dir versichern, ich habe
 viel Sitzfleisch! Also los, geh, geh, geh!}
{173}{}{-Fertig-}
{174}{}{Kid, das Magazin hat meine alten Säfte wieder aufgemischt und ich finde, daß Du mir für
 den Schatz, von dem ich Dir erzählt habe, ruhig noch ein paar Dinge mehr besorgen kannst. Hol
 mir eine aufblasbare Puppe. Du kannst wahrscheinlich eine in New Reno auftreiben.}
{175}{}{Okay! Tschüß!}
{176}{}{Äh, nö!}
{177}{}{Da hast Du sie! [Du gibst Typhon eine aufblasbare Puppe]}
{178}{}{In Ordnung. Ich habe weitere Fragen.}
{179}{}{In Ordnung. Tschüß.}
{180}{}{Vergiß es.}
{181}{}{Da ist sie. [Du gibst Typhon die aufblasbare Puppe]}
{182}{}{Das hier, Kid, wird der Knüller. Gib mir ein paar Stündchen, dann reden wir weiter. Los,
 geh. [er beäugt die Puppe lüstern]}
{183}{}{-Fertig-}
{184}{}{Kann man nicht ein bißchen Privatsphäre haben! Hau ab! Los! Verschwinde!}
{185}{}{-Fertig-}
{186}{}{Ich bin jetzt völlig erledigt. Bring mir ein paar faule Gedärme, dann können wir über den
 Schatz reden. Phil, der Barkeeper, wird für Dich darauf aufpassen.}
{187}{}{Klar! Tschüß!}
{188}{}{Nö!}
{189}{}{Da, nimm! [Du gibst Typhon faule Gedärme]}
{190}{}{Hab es schon. Hier. [Du gibst Typhon faule Gedärme]}
{191}{}{War's das dann?}
{192}{}{In Ordnung. Tschüß.}
{193}{}{Vergiß es.}
{194}{}{Ich möchte vielleicht... oh, noch eine Sache. Ich verrate Dir, was es ist, wenn Du mir
 ein paar faule Gedärme bringst, O.K.?}
{195}{}{Na gut, ich besorge Dir welche.}
{196}{}{Vergiß es.}
{197}{}{Das war echt ein Knüller, Kid. Ich wollte Dich eigentlich noch um eine Pflanze bitten,
 aber, hey, ich gönne Dir eine Pause.}
{198}{}{Danke!}
{199}{}{Danke. Ich habe noch weitere Fragen.}
{200}{}{Das ist zwar nicht gerade präzise, aber danke. Bis später}
{201}{}{Hast Du den Schatz schon gefunden, Kid?}
{202}{}{Äh, nö.}
{203}{}{Noch nicht.}
{204}{}{Nee. Ich habe ein paar Fragen.}
{205}{}{Nee. Tschüß.}
{206}{}{Na, dann such mal weiter. Du wirst ihn ganz bestimmt bald finden.}
{207}{}{Okay.}
{208}{}{Ich hoffe. Tschüß.}
{209}{}{Was macht der Schatz, Kid?}
{210}{}{Zu dumm! Korken!}
{211}{}{Lauter Flaschenkorken! Völlig wertlos!}
{212}{}{Ha ha. Sehr lustig. Ich habe ein paar Fragen.}
{213}{}{Vergiß es.}
{214}{}{Puh! Tschüß.}
{215}{}{Was, benutzt man denn Korken heutzutage nicht mehr als Zahlungsmittel? Willst Du damit
 sagen, daß ich diesen ganzen Aufwand und die ganzen Sorgen darüber, daß jemand meinen Schatz
 finden könnte, umsonst gemacht habe? Verdammter Mist! Tut mir echt leid, Kid, daß ich Dich
 umsonst habe herumhetzen lassen. Wenn ich das gewußt hätte...}
{216}{}{Schon okay. Tschüß!}
{217}{}{Tja, das war dann wohl Dein letzter Fehler, alter Ghul. Zeit zu sterben.}
{218}{}{Kann ja jedem mal passieren. Ich habe ein paar Fragen.}
{219}{}{Jaja, sicher. Tschüß.}
{220}{}{Schätze, daß war keine böse Absicht. Tschüß.}
{221}{}{Gut, wo ist die Kohle?}
{222}{}{Mann, Typhon. Du bist so rücksichtsvoll. Also, wo ist die Kohle?}
{223}{}{In Ordnung. Ich erinnere mich, daß ich das Geld irgendwo in der Stadt verbuddelt habe.
 Das liegt aber schon  viele Jahr zurück und in der Zwischenzeit sind die Häuser dort so oft
 auf- und abgebaut worden, daß ich nicht mehr genau weiß, wo der Platz ist. Falls das irgendwie
 weiterhilft, ich weiß noch, wie ich damals versucht habe, einen Ort zu finden, der abgerissen
 oder niedergewalzt werden kann. Ein unzerstörbarer Platz, sozusagen, weißt Du? Also, viel Glück
 für Dich.}
{224}{}{Du hast Typhon endlich soweit bekommen, mehr Infos über die versteckte Beute auszuspucken.}

# Typhon/Seymour Floats.
{300}{}{Aber Hegels Dialektik zieht nicht in Betracht, daß...}
{301}{}{Hegel, Hegel, Hegel! Was hast Du bloß mit Deinem Hegel!}
{302}{}{Und dann sagt die Frau, "Herr Pfarrer, das ist doch kein Hase!"}
{303}{}{Ha ha ha ha!}
{304}{}{Darauf sagt das erste Proton, "Stimmt, ich bin positiv!"}
{305}{}{[stöhn] Ich verwelke, das ist wirklich zu schlimm.}
{306}{}{Es ist halt nicht leicht, grün zu sein.}
{307}{}{Erzähl mir davon.}
{308}{}{Aber es ist doch ganz offensichtlich, daß das aus philosophischer Sicht in eine Sackgasse
 führt!}
{309}{}{Das liegt aber nur daran, weil Du nicht alle Verzweigungen berücksichtigt hast. Also,
 wenn Du...}
{310}{}{Möchtest Du etwas Obst?}
{311}{}{Fütter mich, Seymour.}
{312}{}{Gehiiirn...Hiiiirn...Tschuldigung, alte Gewohnheit.}
{313}{}{Ist schon in Ordnung. Ich habe keines, Du erinnerst Dich?}
{314}{}{Naja, sicher ist düngen eine gute Methode, aber es geht doch nichts über einen
 verottenden Körper als Kompost.}
{315}{}{Ach, deswegen wolltest Du hier her ziehen! Leichte Beute.}
{316}{}{Das kannst Du mir glauben, es geht nichts über einen guten, schnellen Lauf.}
{317}{}{Du fühlst, wie Dir der Wind durchs Haar bläst, oder?}
{318}{}{Ich bin schon seit Jahren nicht mehr bestäubt worden!}
{319}{}{Stell Dir mal vor, Du wärst in DIESEM Körper gefangen! Keine Action! Kein bißchen Action!}
{320}{}{Vielleicht solltest Du der Photosynthese mal eine Chance geben...}
{321}{}{Ich kann nichts für meine evolutionären Wurzeln, Du grüner Bastard!}
{322}{}{Hoppla! Ich hoffe, daß Du den biologischen Prozeß vorantreiben kannst!}
{323}{}{Mein Blätter! Meine armen Blätter! Aaaaah!}
{324}{}{Mir gefällt es hier. Ich überlege mir, hier Wurzeln zu schlagen.}
{325}{}{Okay, genug Pflanzenwitze für heute, Kumpel.}
{326}{}{Ich frage mich, wie es meinen Cousins in Arroyo geht? Ich hoffe, sie blühen.}
{327}{}{Klar, was sonst! Es sei denn, ein paar von diesen Rattenbastarden haben sie erledigt.}
{328}{}{Ähm, ich glaube, ich öffne mal die Tür oder so...}
{329}{}{Ich glaube, ich leide unter Stempelneid.}
{330}{}{Nicht, daß wir uns hier auf einen Ast begeben...}
{331}{}{Aaaaaaaaaaaaaah! Bitte keine Pflanzenwitze mehr!}
{332}{}{Schau Dir mal die Körner von der Ähre da an! Hohooo!}
{333}{}{Komm runter, Junge! Ich glaube nicht, daß Du das schaffst.}
{334}{}{Soll ich eine Geschichte vorlesen?}
{335}{}{Wie wäre es mit Jack und die Riesenbohne? Oder der Prinzessin auf der Erbse? Oder das
 Schlingpflanzenmonster?}
{336}{}{Ein GECK? Jau, da war so ein Typ, der...}
{337}{}{Psst! Psst! Jemand hört zu!}
{338}{}{Es ist der Zyklus des Lebens, weißt Du...das eine Lebewesen lebt vom anderen und immer so
 weiter...}
{339}{}{Aha. Aber DU ißt noch immer Dünger. Blödsinn... Pflanzenphilosophie...}
{340}{}{Kann ich mal irgendwann mit Deiner Powerrüstung spielen?}
{341}{}{Sprichst Du von diesem alten Anzug, den ich in der Abstellkammer habe? Hihi...}
{342}{}{Ja, ich habe mich mit Planzenkreuzung befaßt.}
{343}{}{Nicht, daß etwas damit nicht in Ordnung wäre.}

