{100}{}{"Zaius, Marcus tut nichts gegen diesen Mutanten-Hasser Jacob und seine verdammten
 Verschwörer. Erst machen sie den Luftreiniger kaputt...und was kommt als nächstes? Ich hab die
 geheimen Tunnel entdeckt, die sie als Treffpunkt verwenden. Wenn man da unten ein oder zwei
 Leichen plaziert, könnte man das Jacob anhängen. Laß mich wissen, wenn du mitmachen willst. Und
 verbrenn um Gottes Willen diesmal den Zettel!" - Unterschrift, Francis}
{101}{}{Oh mein Gott! Wenn ich Marcus von diesem Zettel erzähle, geht die ganze Stadt in Flammen
 aus. Ich spreche besser mit Zaius oder Francis darüber.... und bekomme einige Antworten.}
