{100}{}{Du siehst einen Destillator.}
{101}{}{Du siehst einen Destillator. Sieht so aus, als ob er funktioniert.}

{110}{}{Hört sich so an, als ob der Schnaps jetzt gut destilliert wird. Du gewinnst }
{111}{}{ Erfahrungspunkte für das anfeuern des Destillators.}
{120}{}{Nichts geschieht.}
{130}{}{Der Destillator läuft, doch der Whiskey schmeckt irgendwie, als wenn er schlecht
 geworden wäre.}
{140}{}{Im Destillator ist für Feuerholt kein Platz mehr.}
