{100}{}{Die Wände dieser Höhle bestehen zu einem Teil aus natürlichem Gestein, zum anderen sind sie von Menschenhand
 angefertigt. Es scheint so, als habe eine schwere Explosion vor langer Zeit ihre Struktur beschädigt.}

