# QUICK LOOK
{100}{}{Du siehst einen von Mordinos Männern.}
# RAMIREZ
{101}{}{Du siehst Ramirez.}

# LOOK
{150}{}{Du siehst einen braungebrannten Mann mit Bartstoppeln und schuppiger Haut. Er blickt nervös umher.}
{151}{}{Du siehst einen von Mordinos Männern.}
{152}{}{Du siehst einen von Mordinos Männern. Er sieht etwas schreckhaft aus.}
{153}{}{Du siehst einen von Mordinos Männern. Er sieht nervös aus.}
{154}{}{Du siehst einen von Mordinos Männern. Er sieht aus, als hätte er länger nicht geschlafen.}
# RAMIREZ
{160}{}{Du siehst einen zwielichtig aussehenden Mann mit stachligen, schwarzen Haaren. Er blickt nervös umher.}

# 1. FLOAT [ENCLAVE DESTROYED]
{200}{}{He! }
{201}{}{Verflucht und zugenäht, }

# 2. FLOAT [POWER ARMOR]
{205}{}{Wie gehst du denn mit diesem Ding pinkeln?}

# 3. FLOAT/CLICK [MADE MAN, SAME FAM, ARMED
{210}{}{Nettes Stück hast du da, }

# 4. FLOAT/CLICK [MADE MAN, SAME FAMILY, SNEAK]
{215}{}{Was schnüffelst du hier herum, hä, }

# 5. FLOAT [MADE MAN, SAME FAMILY]
{220}{}{Hast du Jet dabei, Typ?}

# 7. FLOAT [MADE MAN, NOT SAME FAMILY]
{230}{}{He! Cabron! Suchst du den Todesengel? Hau ab!}
{231}{}{He! Puta! Suchst du den Todesengel? Hau ab!}

# 9. FLOAT [MALE, ARMED, RESPECTFUL]
{235}{}{He! Tut mir leid, Hombre, das kannst du hier nicht mit dir rumtragen.}

# 10. FLOAT [FEMALE, ARMED, RESPECTFUL]
{240}{}{He! Chica, das kannst du hier nicht mit dir rumtragen.}

# 11. FLOAT [MALE, SNEAK, PRIZEFIGHTER]
{245}{}{Was zum Teufel schnüffelst du hier herum, }

# 12. FLOAT [FEMALE, SNEAK, PRIZEFIGHTER]
{250}{}{Was schleichst du hier herum, Chica? Du solltest wirklich aufrecht gehen.}

# 13. FLOAT/CLICK [PRIZEFIGHTER]
{264}{}{Der letzte Kampf war etwas aus 'nem Epos, Hombre.}
{265}{}{Hab dich im Ring kämpfen sehen, }
{266}{}{Wie groß bist du, }

# 15. FLOAT/CLICK [ARMED, PORN STAR, FEMALE]
{280}{}{Hey, hey, hey! Chica, soll ich die Waffe für dich beiseite schaffen?}

# 16. FLOAT [MALE, SNEAK, PORN STAR]
{285}{}{Was zum Teufel schnüffelst du hier herum, }

# 17. FLOAT/CLICK [SNEAK, PORN STAR, FEMALE]
{290}{}{Mit der Figur schleichst du so schnell an keinem Mordino vorbei, Chica.}

# 18. FLOAT [PORN STAR]
{295}{}{Dein Film war nicht schlecht, aber offensichtlich brauchst du noch ein paar Tips von mir.}
{296}{}{Brauchst du Jet? Ich kann dich in Form bringen, Chica.}

# 20. FLOAT/CLICK [ARMED, SLAVER]
{315}{}{Zeig hier dein Eisen nicht rum, Freundchen. Steck es weg.}

# 21. FLOAT/CLICK [SNEAK, SLAVER]
{320}{}{Du brauchst hier nicht rumzuschleichen, Sklavenhändler, klar? Du bist unter Freunden.}

# 22. FLOAT/CLICK [ARMED, NO REP]
{325}{}{He! Biste schwer von Begriff oder was? Steck das Ding weg, oder du kannst was erleben.}

# 24. FLOAT/CLICK [SNEAK, MALE, NO REP]
{330}{}{Was zum Teufel schnüffelst du hier herum? Willst du erschossen werden?}

# 25. FLOAT/CLICK [SNEAK, FEMALE, NO REP]
{335}{}{Was zum Teufel schnüffelst du herum, Chica? Willste erschossen werden?}

# 26. FLOAT/CLICK [COMPANION: ROBOBRAIN]
{342}{}{Dieser Roboter kann ins Altmetall, wenn er hierbleibt.}

# 27. FLOAT/CLICK [COMPANION: MARCUS]
{347}{}{Will dieser Mutant zur Zielscheibe werden? Wenn er hierbleibt, wird er seinen Willen bekommen.}

# 28. FLOAT/CLICK [COMPANION: LENNY]
{352}{}{Wenn dieser Ghul hier nich' in 'ner Minute draußen is', isser noch toter als jetz' schon.}

# 29. FLOAT [ENCLAVE DESTROYED]
{362}{}{Mann, diese Enklavenbastarde können von Glück reden, daß sie sich nicht mit den Mordinos angelegt haben.}

# 30. FLOAT [MADE MAN, SAME FAMILY]
{373}{}{Schön, dich zu sehen, }

# 32. CLICK [MADE MAN, NOT SAME FAMILY]
{406}{}{::Spuckt dir vor die Füße::}
{407}{}{Glaubst du, du kannst einfach ankommen und mit einem Mordino reden, ihn anquatschen? Hau ab.}
{408}{}{Sprich mich noch einmal an und ich werde deine Familie, deinen Hund und dann dich töten. Zweimal.}

# 34. CLICK [SLAVER]
{420}{}{Nöö, wenn's um Sklaven geht, bin ich nicht der Richtige...sprich mal Lil' Jesus.}
{421}{}{Wann bringst du endlich ein paar gutaussehende Sklaven an? Schlechter Ertrag letzte Saison, Sklavenhändler. Schäbig.}

# 35. CLICK [MALE/FEMALE, NO REP, GOOD REACTION]
{430}{}{Suchst Arbeit, hä? Red mit Lil' Jesus.}

# 36. CLICK [NO REP, BAD REACTION]
{437}{}{Verzieh dich, Wilder.}
{438}{}{Ich hab jetzt keine ZEIT für dich.}
{439}{}{Raus hier.}
{440}{}{Raus.}

# RAMIREZ UNIQUE DIALOG
# 37. CLICK [DELIVERY = ASSIGNED] (WTG)
{460}{}{(Schaut auf, während du näherkommst, grinst.) Suchst du Streit, Hombre?}
{461}{}{(Schaut auf, während du näherkommst, grinst.) Suchst du Streit, Chica?}
{462}{}{Ramirez? Big Jesus hat mir dieses Paket für dich gegeben.}
{463}{}{Kein Problem. Ich geh.}

# 38. CLICK [DELIVERY = ASSIGNED] (37)
{470}{}{(Nimmt die Schachtel.) War auch langsam Zeit. Wir ham schon fast kein Jet mehr. (Schnieft, hustet leicht.) Kannst dir nicht' vorstellen, wo das alles bleibt...hm?}
{471}{}{Jaja, mach's mal gut -...}
{472}{}{Wenn ich mir deinen Jet-Husten so anhöre und sehe, wie du deine Nase reibst, kann ich mir wirklich nicht vorstellen, wo das ganze gelieferte Jet bleibt.}

# 39. CLICK [DELIVERY = ASSIGNED] (38)
{473}{}{Big J, weißte, der kümmert sich um uns. Erst letzte Woche hab ich drei Sklaven gefangen, die dumm genug war'n abzuhauen. Also krieg ich 'ne Belohnung, klar? Heh. Und du kriegst nix. Du bist nur 'n Laufbursche. Ich, ich bin 'ne WACHE.}
{474}{}{Ja, großartig. Mach's gut.}
{475}{}{Ich frage mich, ob Big Jesus sich wohl denkt, wie diese drei Sklaven direkt vor der NASE von derart scharfsinnigen, Jet nehmenden Wachen wie dir entkommen konnten.}
{476}{}{Ramirez...paß auf, was du zu mir sagst, OK? Paß auf, daß dein Maul deinen Hintern nicht in Schwierigkeiten bringt.}

# 40. CLICK [DELIVERY = ASSIGNED] (39)
{480}{}{(Blinzelt.) Hä...? Was sagst du?}
{481}{}{Nichts, was du verstehst oder was ich jetzt noch mal wiederhole. Mach's gut, okay?}
{482}{}{Ich sagte, "Ich frage mich, ob Big Jesus sich wohl denkt, wie diese drei Sklaven direkt vor der NASE von derart scharfsinnigen, Jet nehmenden Wachen wie dir entkommen konnten".}

# 41. CLICK [DELIVERY = ASSIGNED] (40)
{490}{}{(Blinzelt, lächelt verwirrt.) Hä? Ja, ja. Ich bin scharf, weißt du,...scharf-sinnig...Ich bin 'ne WACHE, klar?}
{491}{}{Ja, das hast du bereits erwähnt. An deiner Stelle, Ramirez, würde ich der Menschheit eine Gunst erweisen und das ganze Paket Jet auf einmal nehmen. Bis dann.}
{492}{}{Junge, bin ich froh, daß einer so klug war, euch allen automatische Waffen zu geben. Gibt mir ein Gefühl der Sicherheit. Bis dann, Ramirez.}

# 42. CLICK [DELIVERY = ASSIGNED] (39)
{493}{}{(Blinzelt.) Hä...? Was sagst du?}
{494}{}{Vergiß es. Hock dich an 'ne Feuerwaffe und drück ab, OK?}
{495}{}{Nichts. An deiner Stelle, Ramirez, würde ich der Menschheit einen Gefallen erweisen und das ganze Paket Jet auf einmal nehmen. Bis später.}
{496}{}{(Geh weg.)}

# 43. CLICK [DELIVERY = ASSIGNED] (39, 40, 41, 42)
{500}{}{(Als du dich wegdrehst knurrt Ramirez.) Hey! Die Schachtel wurde geöffnet! }
{501}{}{Haste was rausgenommen, Hombre?}
{502}{}{Haste was rausgenommen, Chica? }
{503}{}{Keiner legt sich mit Ramirez an, hast du verstanden?!}
{504}{}{Ja, ich verstehe. Aber nicht mehr lange.}
{505}{}{Das sind beschissene letzte Worte, Ramirez.}

# delivered box
{600}{}{Du hast Ramirez das Paket von Big Jesus gebracht.}

# END OF LINES
{1200}{}{! Was 'ne Art, der Enklave eins überzuziehen!}
{1201}{}{, den Enklavenbastarden mußte mal gezeigt werden, wie die Dinge HIER erledigt werden.}
{1210}{}{.}
{1215}{}{? Mordinos gehen stolz und aufrecht.}
{1245}{}{? Du solltest wirklich aufrecht gehen.}
{1265}{}{. Du hast diesen Kerl FERTIGGEMACHT.}
{1266}{}{?}
{1285}{}{? Komm schon, Schultern zurück.}
{1373}{}{. Wo warst du?}