# QUICK LOOK
{100}{}{Du siehst einen kränklich wirkenden Sklaven.}
{101}{}{Du siehst einen unter Jet stehenden Sklaven.}
{102}{}{Du siehst einen Sklaven.}

# EXAMINES
# 1. [SICKLY MALE SLAVE]
{150}{}{Du siehst einen gebrochen aussehenden Mann. Seine Augen irren in der Gegend umher, als ob sie einem unsichtbaren Insekt folgten.}
{151}{}{Du siehst einen kränklich wirkenden Sklaven. Er sieht völlig verschreckt aus und kann seinen Blick offenbar nicht auf dich konzentrieren.}
{152}{}{Du siehst einen kränklich wirkenden Sklaven. Seine Kleidung besteht nur noch aus Fetzen und die Haut schlottert um ihn herum.}
{153}{}{Du siehst einen kränklich wirkenden Sklaven. Er hat einen starken Husten und sein zerschlissenes Hemd ist blutbefleckt.}
{154}{}{Du siehst einen kränklich wirkenden Sklaven. Ein Geruch nach getrocknetem Urin und Kot geht von ihm aus.}
{155}{}{Du siehst einen kränklich wirkenden Sklaven. Seine Zähne sind ausgefallen und seine Augen blutunterlaufen.}
{156}{}{Du siehst einen kränklich wirkenden Sklaven. Sein Gesicht und Hals sind von einer Art Ausschlag bedeckt und er kratzt sich von Zeit zu Zeit daran.}
# 2. [SICKLY FEMALE SLAVE]
{160}{}{Du siehst eine gebrochen wirkende Frau. Sie stiert auf den Boden, als habe sie Angst, aufzuschauen.}
{161}{}{Du siehst eine kränklich wirkende Sklavin. Sie sieht völlig verschreckt aus und kann ihren Blick offenbar nicht auf dich konzentrieren.}
{162}{}{Du siehst eine kränklich wirkende Sklavin. Die Schmeißfliegen auf ihrem Gesicht und ihren Armen scheint sie nicht zu bemerken.}
{163}{}{Du siehst eine kränklich wirkende Sklavin. Ihre Kleidung besteht nur noch aus Fetzen und die Haut schlottert um sie herum.}
{164}{}{Du siehst eine kränklich wirkende Sklavin. Sie zieht die Luft bei jedem Atemzug pfeifend ein und aus ihrer Nase läuft Schleim.}
{165}{}{Du siehst eine kränklich wirkende Sklavin. Ein Geruch nach getrocknetem Urin und Kot geht von ihr aus.}
{166}{}{Du siehst eine kränklich wirkende Sklavin. Sie kratzt an einer Art Ausschlag auf ihrem Gesicht und Hals herum.}
{167}{}{Du siehst eine kränklich wirkende Sklavin. Sie sieht aus, als wolle sie weinen, hat aber keine Tränen.}
# 3. [MALE SLAVE, DRUGGED]
{170}{}{Du siehst einen träge wirkenden Mann. Er stiert mit leerem Gesichtsausdruck vor sich hin.}
{171}{}{Du siehst einen unter Jet stehenden Sklaven. Seine Augen irren in der Gegend umher, ohne etwas wahrzunehmen.}
{172}{}{Du siehst einen unter Jet stehenden Sklaven. Während du zusiehst, beißt er in seinen Unterarm, zieht etwas Haut mit den Zähnen ab und beginnt langsam darauf zu kauen.}
{173}{}{Du siehst einen unter Jet stehenden Sklaven. Er hat ein leichtes Lächeln im Gesicht, aber seine Augen sind verschleiert und leer.}
{174}{}{Du siehst einen unter Jet stehenden Sklaven. Er stiert ins Leere und aus seinem Mund rinnt der Speichel.}
{175}{}{Du siehst einen unter Jet stehenden Sklaven. Als er dich wahrnimmt, zuckt er zusammen und lächelt verzerrt, als schmerze dein Anblick.}
4. [DRUGGED FEMALE SLAVE]
{180}{}{Du siehst eine zitternde Frau. Sie stiert auf den Boden vor sich, als habe sie Angst, er könne verschwinden, sobald sie den Blick abwendet.}
{181}{}{Du siehst eine unter Jet stehende Sklavin. Sie kichert vor sich hin und an ihren Mundwinkeln sind Reste von Blut zu erkennen.}
{182}{}{Du siehst eine unter Jet stehende Sklavin. Auf ihrem Arm befinden sich blaue Flecken und die Spuren von Peitschenhieben.}
{183}{}{Du siehst eine unter Jet stehende Sklavin. Sie blinzelt schnell, als seien ihre Augen zu trocken.}
{184}{}{Du siehst eine unter Jet stehende Sklavin. Sie kratzt so heftig ihre Handrücken, daß die Haut reißt.}
{185}{}{Du siehst eine unter Jet stehende Sklavin. Auf ihrem Hemd befinden sich Flecken von Erbrochenem und sie riecht schwach nach Terpentin.}
# 5. [MALE SLAVE, BEATEN]
{190}{}{Du siehst einen dünnen Mann. Sein Körper ist mit den Malen von Peitschenhieben bedeckt. Er stiert dumpf zu Boden, als erwarte er Befehle.}
{191}{}{Du siehst einen Sklaven, der verprügelt wurde.}
{192}{}{Du siehst einen dünnen Sklaven. Sein Körper ist mit den Malen von Peitschenhieben bedeckt. Er stiert dumpf zu Boden, als erwarte er Befehle.}
# 6. [DRUGGED FEMALE SLAVE]
{195}{}{Du siehst eine zitternde Frau. Ihr Körper ist mit den Malen von Peitschenhieben bedeckt und ihre Kleider sind nur noch Fetzen.}
{196}{}{Du siehst eine Sklavin.}
{197}{}{Du siehst eine Sklavin. Sie zittert leicht und ihr Körper ist mit den Malen von Peitschenhieben bedeckt.}

# FLOAT:
# 7. [SICKLY SLAVE]
{201}{}{::Hahhhhk::}
{202}{}{::Hustet::}
# 8. [DRUGGED SLAVE]
{213}{}{Hie hiiieee hiee...hie...}
{214}{}{IeeeIIIeeeeIIIII}

# CLICK:
# 9. [SICKLY SLAVE]
{220}{}{::Stiert dich mit leerem Blick an::}
{221}{}{Rrrarrr..rr..::Hustet::}
# 10. [DRUGGED SLAVE]
{240}{}{::Reibt sich die Augen::}
{241}{}{Hie hiiieee hiee...hie...}
{242}{}{IeeeIIIeeeeIIIII}
# 11. [BEATEN SLAVE vs. SLAVER]
{261}{}{Laß mich bitte in Ruhe. Ich gehöre bereits jemand anderem.}
{262}{}{Bitte geh weg, Sklavenhändler. Ich will keinen Ärger.}

# 12. [BEATEN AND/OR GENERIC SLAVE]
{280}{}{Wenn sie mich erwischen, wie ich mit dir rede, testen sie Jet an mir.}
{282}{}{Sie testen neues Jet an uns. Manches davon ist giftig.}
{281}{}{Bitte laß mich...ich darf nicht mit dir sprechen.}