{100}{}{Du siehst eine Todeskralle.}
{101}{}{Du siehst eine Todeskrallenwache.}
{102}{}{Du siehst eine typische Todeskralle. Die Kreatur ist riesig, sie hat einen kräftigen Körper, scharfe Zähne und lange Klauen.}
{103}{}{Hallo.}
{104}{}{Hallo. Kann nicht reden. Haben Wache.}
{105}{}{Feinde von Rudel müssen sterben!}
