{100}{}{Du siehst einen kleinen, fettverschmierten Typen.}
{101}{}{Vor dir steht Buster, der Kerl mit der Knarre.}
{102}{}{Seine Kleider sind zerschlissen und seine Hände, seine Arme und sein Gesicht sind mit Waffenfett verschmiert. Trotzdem scheint er ziemlich gutgelaunt zu sein.}
{103}{}{Willkommen in Busters Waffenemporium, dem besten Haus am Platze! Ich bin Buster und sonst ist hier keiner. Ich habe einige nette Sachen auf Lager. Sieh es dir an. Ich bin für jedes Geschäft zu haben.}
{104}{}{Schon wieder hier? Was kann ich für dich tun?}
{105}{}{Noch irgendwas?}
{106}{}{Will Bum-Bum.}
{107}{}{Was hast du zu bieten?}
{108}{}{Kannst du mir vielleicht was ganz Spezielles besorgen?}
{109}{}{Ich hab da ein paar Fragen}
{110}{}{Goodbye.}
{111}{}{Eine gute Wahl!}
{112}{}{Du hast da ein echtes Schnäppchen geschlagen, Partner.}
{113}{}{Ich will ja nicht drängeln, Fremdling, aber ich habe noch zu tun.}
{114}{}{Klar, Fremdling, was möchtest du wissen?}
{115}{}{Erzähl mir was über die NKR.}
{116}{}{Wie ist das mit Merk?}
{117}{}{Was weißt du über Frank Westin?}
{118}{}{Ich möchte mich mit dem alten Carlson treffen. Kennst du jemand, der mir dabei helfen kann?}
{119}{}{Hast du ein GEEK?}
{120}{}{Schön für dich, Fremdling, aber ich bin nicht die Wohlfahrt.}
{121}{}{Schon möglich. Ich hätte da eventuell ein Zielfernrohr, Modell Triveld x10 - eignet sich ideal für Jagdgewehre, wenn das jemanden interessiert. Ich mach ein Sonderangebot: 500 Dollar.}
{122}{}{Hey, du hast mich doch schon ausgenommen.}
{123}{}{Ja, das geht klar.}
{124}{}{Nein, danke.}
{125}{}{Das ist die Neue Kalifornische Republik. Präsidentin Tandi und ihre Leute sagen, sie wollen, daß alles wieder so wird wie in der guten alten Zeit. Ich glaub ja eher, sie wollen vor allem so viel abgreifen, wie sie nur können. Was soll's, mich juckt's nicht, die gute alte Zeit war vor meiner Zeit. Sind allerdings ziemlich prüde, diese Gesellen - haben was gegen Sklaverei und Glücksspiel und was sonst noch. Darum hab ich meinen Laden hier draußen. Ich mag keine Regeln - hatte schon immer was dagegen.}
{126}{}{I see.}
{127}{}{Bis dann}
{128}{}{Ich will nichts mit Merk zu schaffen haben und es bringt nichts, über ihn zu schwatzen. Wenn du Fragen hast, dann frag im "Rawhide" nach ihm.}
{129}{}{I see.}
{130}{}{Bis dann}
{131}{}{Frank Westin - du meinst den Typen aus dem Kongreß? Hat 'ne Ranch draußen vor der Stadt, im Westen. Brahminzüchter - großes Tier im Viehzüchter-Verband. Falls du Arbeit suchst - der kann immer Leute gebrauchen.}
{132}{}{I see.}
{133}{}{Bis dann}
{134}{}{Komische Frage nach dem, was mit Frank Westin passiert ist. Ich weiß da nicht Bescheid, aber drunten im "Rawhide" gibt's einen Knaben - Merk heißt er -, der kann dir vielleicht weiterhelfen.}
{135}{}{I see.}
{136}{}{Bis dann}
{137}{}{So einen von den Vorkriegsimporten? Laß mich raten, mit 14-mm-Munition? Ist nicht, hab ich nicht.}
{138}{}{I see.}
{139}{}{Bis dann}
{140}{}{Das geht nur bei Jagdgewehren, glaub's mir. Das liegt an der Befestigung, verstehst du?}
{141}{}{I see.}
{142}{}{Bis dann}
{143}{}{Der Laden ist dicht. Zisch ab.}
{144}{}{Meine Güte! Komm zu 'ner vernünftigen Zeit wieder her.}
{145}{}{Komm wieder her, wenn geöffnet ist - und mach das Zelt hinter dir zu.}
{146}{}{Hier ist geschlossen.}
{147}{}{Raus hier, sonst wird Meister Kaliber 45 sehr unglücklich!}
{148}{}{Dumm gelaufen, Fremdling.}
{149}{}{In dem Regal da ist alles, was ich habe. Solltest du etwas anderes brauchen, dann such
 in den anderen Regalen danach.}
