{100}{}{Du siehst einen schmutzigen Mann, der aber sehr kräftig aussieht.}
{101}{}{Du siehst Connar.}
{102}{}{He, du! Was tust du da?}
{103}{}{Bleib erst mal da stehen, Wanderer. Was willst du hier?}
{104}{}{Ich jage Monster. }
{105}{}{Was juckt's dich?}
{106}{}{Geht dich nichts an.}
{107}{}{Ich möchte wetten, die Bastarde aus Bunkerstadt haben dich geschickt. Am besten
 verschwindest du und läßt alle am Leben.}
{108}{}{Dafür ist's ein bißchen zu spät.}
{109}{}{Warum?}
{110}{}{Tut mir leid, habe einen Auftrag zu erledigen.}
{111}{}{Diese Kreaturen sind das einzige, das Bunkerstadt davon abhält, uns zu ihren sogenannten
 Dienern zu machen.}
{112}{}{Die bezahlen mich dafür, ihnen die Monster vom Hals zu schaffen und genau das mache ich.}
{113}{}{Das hat mir niemand gesagt.}
{114}{}{Die bezahlen mich dafür, ihnen die Monster vom Hals zu schaffen und das mache ich.}
{115}{}{Du Idiot! Warum machst du sowas, verdammt noch mal.}
{116}{}{Ich brauche das Geld.}
{117}{}{Die werden kommen und uns holen, wenn du das machst.}
{118}{}{Nicht mein Problem.}
{119}{}{Hoffentlich erstickst du dran. Die werden schon sehr bald hier auftauchen und uns
 abschleppen.}
{120}{}{Ich wußte nicht, daß die mir deshalb den Auftrag gegeben haben.}
{121}{}{Mag schon sein. Aber ich laß mir von Gesocks wie dir trotzdem nichts sagen.}
{122}{}{Wir können das nicht zulassen.}
{123}{}{Tu, was du nicht lassen kannst.}
{124}{}{Du hast denen das einfach so geglaubt? Da mußt du aber noch einiges über das Leben
 lernen, mein Freund.}
{125}{}{Kann ich euch denn irgendwie helfen?}
{126}{}{Die Jungs aus Bunkerstadt sind ziemliche Feiglinge. Wenn du denen ein bißchen Angst
 einjagst, rennen die wie die Karnickel. Mit ein paar Gewehren könnten wir sie uns bestimmt
 vom Leib halten.}
{127}{}{Was für Gewehre?}
{128}{}{Naja, ich bin ganz gut mit der Schrotflinte und ein paar von unseren Leuten können mit
 Gewehren umgehen. Ich denke drei davon würden reichen.}
{129}{}{Ich werde mir das mal anschauen.}
{130}{}{Du bist hier unerwünscht. Los verschwinde.}
{131}{}{Ich hab's mir anders überlegt. Wie kann ich euch helfen?}
{132}{}{Hör zu, die wirst hier trotzdem gleich verschwinden.}
{133}{}{Du kannst mich mal.}
{134}{}{Da bist du ja wieder! Hast du die Gewehre mitgebracht?}
{135}{}{Was sollte ich noch mal mitbringen?}
{136}{}{Ja. Hier sind sie.}
{137}{}{Wir brauchen drei Gewehre und eine Schrotflinte. Je schneller du sie uns bringst, desto
 besser.}
{138}{}{OK.}
{139}{}{Damit können wir im Lauf der nächsten Monate was aus diesem Ort machen. Wenn du dich mal
 häuslich niederlassen möchtest, bei uns bist du immer willkommen.}
{140}{}{Gern geschehen.}
{141}{}{Willkommen, da bist du ja wieder. Bei uns läuft's gut. Wir erweitern gerade das Dorf.}
{142}{}{Hallo, da bist du ja wieder! Hier bei uns ist es gut vorangegangen, wie du siehst. Schau
 dich mal um, wenn du 'n bißchen Zeit hast.}
{143}{}{Wir sind dauernd am Bauen. Wir hoffen, daß wir bis nächsten Monat das Dorf wieder ein
 Stück erweitert haben.}
{144}{}{Willkommen! Das Dorf ist noch ein Stück gewachsen, genau, wie wir gehofft hatten. Wie
 immer bist du hier willkommen.}
{145}{}{Jetzt haben wir von Bunkerstadt nichts mehr zu befürchten und können hier endlich in
 Frieden leben. Nochmals vielen Dank, Wanderndes Wesen.}
{146}{}{Hör einfach auf, da draußen irgendwas zu töten, du Einfaltspinsel.}
