{100}{}{Ein Computerterminal}
{101}{}{Darauf klebt ein kleiner Aufkleber, auf dem steht: "I*tel inside".}
{102}{}{[Du kannst nicht lesen, was auf dem Monitor steht.]}
{103}{}{Steuerungsterminal\n                                                       Projekt: Experiment zur Organ-Roboter-Synthese}
{104}{}{}
{105}{}{Systeme werden überprüft.}
{106}{}{Roboter aktivieren}
{107}{}{Beenden}
{108}{}{Hä?}
{109}{}{[Du kannst nicht lesen, was auf dem Monitor steht.]}
{110}{}{Programm beenden}
{111}{}{Beenden}
{112}{}{Ug}
{113}{}{Bitte warten... Roboterträgerstruktur - OK. Behälter für Bio-Gel - Vollständig befüllt.
 Organaufbewahrungsanlage - Reagiert. Bereit zum Aktivieren.}
{114}{}{Bitte warten... Roboterträgerstruktur - OK. Behälter für Bio-Gel - Nachfüllen
 erforderlich. Organaufbewahrungsanlage - Nicht vorhanden. Aktivierung nicht empfohlen.}
{115}{}{Bitte warten... Roboterträgerstruktur - Motivator austauschen. Behälter für Bio-Gel -
 OK. Organaufbewahrungsanlage - Reagiert. Aktivierung nicht empfohlen.}
{116}{}{Bitte warten... Roboterträgerstruktur - OK. Behälter für Bio-Gel - Nachfüllen erforderlich\n                                       Organaufbewahrungsanlage - Nicht vorhanden\n                   Aktivierung nicht empfohlen}
{117}{}{Bitte warten... Roboterträgerstruktur - OK. Behälter für Bio-Gel - Nachfüllen erforderlich\n                                       Organaufbewahrungsanlage - Reagiert\n                    Aktivierung nicht empfohlen}
{118}{}{Bitte warten... Roboterträgerstruktur - OK. Behälter für Bio-Gel - Nachfüllen erforderlich\n                                       Organaufbewahrungsanlage - Nicht vorhanden\n                    Aktivierung nicht empfohlen}
{119}{}{Bitte warten... Roboterträgerstruktur - Motivator austauschen. Behälter für Bio-Gel -
 Nachfüllen erforderlich. Organaufbewahrungsanlage - Reagiert. Aktivierung nicht empfohlen.}
{120}{}{Bitte warten... Roboterträgerstruktur - Motivator austauschen. Behälter für Bio-Gel -
 Nachfüllen erforderlich. Organaufbewahrungsanlage - Nicht vorhanden. Aktivierung nicht empfohlen}
{121}{}{}
{122}{}{}
{124}{}{}
{153}{}{Startsequenz einleiten}
{154}{}{Beenden}
{155}{}{Ausfallsicherheit deaktiviert. Gerät in Betrieb.}
{156}{}{}
{157}{}{}
{158}{}{}
{159}{}{}
{160}{}{}
{161}{}{}
{162}{}{}
{163}{}{}
{164}{}{Anlaufsequenz initialisieren}
{165}{}{Leistungspegel - Sollwerte}
{166}{}{Synchronisationsverhältnis - 75%}
{167}{}{Gerät ist betriebsbereit}
{170}{}{Synchronisationsverhältnis - 50%}
{174}{}{Synchronisationsverhältnis - 10%}
{176}{}{Beenden}
{200}{}{ kann nicht lesen, was auf dem Monitor steht.}
{300}{}{Der Computer scheint mit einer Art Abwehrmechanismus ausgestattet zu sein.}
{500}{}{Anlaufsequenz initialisieren. Leistungspegel - Sollwerte. Programm unterbrochen.
 Ladevorgang... Programm fortsetzen. Synchronisationsverhältnis - 100%. Gerät ist betriebsbereit}
