#tento soubor pøeloil Miskot...mhoferek@telecom.cz
#############################################################
#  Message File: ACMynoc.msg                                #
#                                                           #
#       Body Type:  NMPRIM                                  #
#       Combat AI: Berzerker                                #
#       Weapons: Sledgehammer[in hand]                      #
#       HP: 75                                              #
#       Skills to note: 80% Throwing                        #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: December 01, 1997                               #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################

{100}{}{Vidíš stráce mostu.}
{101}{}{Vidíš Mynoca, stráce mostu.}

#############################################################
#  The following lines are for the dialog which the NPC     #
#  says. This will be disorganized because of the Design    #
#  Tool.                                                    #
#############################################################

{150}{}{Pøed tebou stojí slavnı váleèník tvého kmene. V ruce drí kopí.}
{151}{}{[MLUVIT]}
{152}{}{Ahoj, Vyvolenı. Jdeš hledat GECK?}
{153}{}{Ano.}
{154}{}{Ano. A pøedtím, ne odejdu, se tì chci na nìco zeptat.}
{155}{}{Ne, zatím ne. Musím se tu ještì trošku porozhlédnout.}
{156}{}{No, a tì tedy bohové ochraòují.}
{157}{}{Díky a sbohem.}
{158}{}{Co chceš vìdìt?}
{159}{}{Co mi mùeš øíct o lidech, kteøí obchodují s naší vesnicí?}
{160}{}{Co mi mùeš povìdìt o tomhle pøedmìtu, kterı prı pochází z Vaultu?}
{161}{}{Nic, zapomeò na to.}
{162}{}{Tak dobrá, ale neztrácej tu zbyteènì moc èasu. Bez GECKu jsme všichni ztraceni.}
{163}{}{Já vím, nemìj strach - mám všechno pod kontrolou.}
{164}{}{Proè?}
{165}{}{Musím jít. Sbohem.}
{166}{}{Obchodníci? Zhruba kadé dva mìsíce sem pøicházejí z Klamathu. U víc ne mìsíc tu sice ádnı nebyl, ale Klamath je odsud jenom pár dnù cesty smìrem na vıchod.}
{167}{}{Dìkuji ti. Sbohem.}
{168}{}{Co mi mùeš øíci o tomhle pøedmìtu, kterı údajnì pochází ze svatého Vaultu?}
{169}{}{Vypadá to jako láhev na vodu. Moná nám ji Vault posílá jako znamení.}
{170}{}{Mùeš mi øíct, kdo ji k nám do vesnice pøinesl?}
{171}{}{Dìkuji ti. Musím jít. Sbohem.}
{172}{}{Sbohem.}
{173}{}{Kvùli tvému sobectví a pıše tu všichni trpíme! Sbohem!}
{174}{}{Sbohem.}
{175}{}{Proè? Rozhlédni se okolo - naše vesnice umírá. Zahrady chøadnou a kadı den se zhroutí nìjaké dítì nebo nìkdo ze starších. Musíš nám pøinést Ráj, dokud je ještì èas!}
{176}{}{Postarám se o to. Sbohem.}
{177}{}{Já jsem Vyvolenı - "musím" dìlat jen to, co se mi líbí. Sbohem.}
{178}{}{Nevzpomínám si na jeho jméno. Vím jen, e byl starı a hluènı - pøíliš hluènı na rozumné jednání - ale zato hodnì chytrı. Byl z Klamathu. To je na vıchod odsud, jak u jsem øekl.}
{179}{}{Dìkuju ti. Sbohem.}
{180}{}{Ty jsi poøád ještì tady? Musíš jít hledat GECK. Takhle nám nepomùeš!}
{181}{}{Tenhle most je to jedinı, co tì má zajímat, pøíteli. Já se o sebe umím postarat.}
{182}{}{Právì jsem na odchodu. Sbohem, pøíteli.}
{183}{}{Nebudu s tebou mluvit, ty vzpurnı prase!}
{184}{}{Chci ti ještì poloit pár otázek.}
{185}{}{To bylo rychlé! A co svatı Vault 13? U víš kde leí?}
{186}{}{Ano.}
{187}{}{Ne, ještì ne.}
{188}{}{Opravdu? To je skvìlé! A máš pro nás GECK?}
{189}{}{Ne.}
{190}{}{Ne. Ještì na to s lidmi ve Vaultu nepøišla øeè.}
{191}{}{Myslím, e to není tvoje starost, pøíteli.}
{192}{}{Ne? Vyvolenı od té doby, co jsi pryè, zemøeli u tøi ze starších obyvatel vesnice. Nesmíš ztrácet èas.}
{193}{}{Najdu to, nemìj strach.}
{194}{}{Z toho tvıho neustálého sekırování se mi u dìlá blbì.}
{195}{}{No, tak proè mluvíš se mnou? Promluv si s nimi a pøines nám GECK.}
{196}{}{Najdu to -- všechno bude v poøádku, pøíteli.}
{197}{}{Z toho tvıho sekırování se mi u dìlá blbì.}
{198}{}{Co nového o GECKu, Vyvolenı?}
{199}{}{U vím, kde je Vault!}
{200}{}{Nemùu ten Vault 13 poøád najít.}
{201}{}{Podívejte se, to je Vyvolenı.}
{202}{}{Ahoj.}
{203}{}{Dr hubu.}
{204}{}{Mùu se tì na nìco zeptat?}
{205}{}{Ne, nemám na tebe èas.}
{206}{}{Tak si polib. Sbohem.}
{207}{}{No dobøe. Ještì se uvidíme.}
{208}{}{Chcípni!}
{209}{}{Zdravím, trotlíku! Vidíš tenhle most? Ty pøejít - opatrnì! Most nebezpeènı. Ty nechtít spadnout. Nebo ano?}
{210}{}{Hmm... búm?}
{211}{}{Ty svinì! Jsi zrádce naší vesnice!}
{212}{}{Jsi zrádce. Za to zemøeš!}
{213}{}{Jsi zrádce vlastních lidí.}
{214}{}{Proè tohle dìláš?}
{215}{}{Starší se zmılila. Ty jsi zlo.}

{300}{}{Mùj otec mì nauèil vyrábìt mnohem ostøejší hroty, ne mají ostatní kopí. Dones mi kousek pazourku a upravím i tvoje kopí. V divoèinì se ti to bude hodit.}
{301}{}{Kde se dá takovı pazourek sehnat?}
{302}{}{Myslím, e tvá teta Morlis ho u sebe má. Je ale tak nevrlá, e se s ní nikdo neodváí promluvit. Ta èarodìjnice bude urèitì chtít nìco na oplátku.}
{303}{}{Dìkuju ti. Sbohem.}
{304}{}{Co ten pazourek? Máš ho?}
{305}{}{Ano, tady je.}
{306}{}{Zatím ne.}
{307}{}{Ano, to je dobrı kousek. Podej mi svoje kopí.}
{308}{}{Tady ho máš.}
{309}{}{Já... já ádné nemám.}
{310}{}{A teï se dáme do práce...}
{311}{}{Vyvolenı a nemá kopí? No, budu muset pouít jedno z mıch. A teï se dáme do práce...}
{312}{}{Tady máš svoje nové kopí.}
{313}{}{Dìkuji ti, mùj pøíteli -- tohle mi hodnì pomùe.}
{314}{}{No, zaujalo mì tvoje kopí. Vypadá trochu jinak ne ta ostatní.}


# added in for time limit
{400}{}{Vítej doma, Vyvolenı! Co svatı Vault? Máš pro nás GECK?}
{401}{}{Já nenajít ... zatím.}
{402}{}{Ne, zatím mi štìstí nepøálo.}
{403}{}{Nemám teï zrovna náladu na tvoje vyptávání. Sbohem.}
{404}{}{Vìci se nevyvíjejí dobøe, Vyvolenı. Je velké sucho a naše úroda je na tom zle. Snaíme se dìlat, co je v našich silách, ale je to poøád horší a horší.}
{405}{}{Proè ne obchod s jiná vesnice?}
{406}{}{Já snait se moc. Já najít GECK. Já vrátit.}
{407}{}{Proè neobchodujeme s ostatními vesnicemi? Myslím, e by nám potøebné potraviny dodaly.}
{408}{}{Snaím se ze všech sil. A najdu GECK, vrátím se s ním.}
{409}{}{Jsme jen obyèejní lidé a nemáme co nabídnout. Tìch nìkolik málo mìst, která jsme poádali, neprojevilo ani špetku zájmu pomoci nám.}
{410}{}{Já vidìt.}
{411}{}{Rozumím.}
{412}{}{Jsi naše nadìje, Vyvolenı. Prosím, nezklam nás!}
{413}{}{Je dobré, e tì vidím, Vyvolenı. Jak se ti daøí ve tvém poslání?}
{414}{}{Hledat.}
{415}{}{Stále hledám a hledám.}
{416}{}{Nechci o tom mluvit.}
{417}{}{Musíš si pospíšit. Tady doma je to èím dál horší. Brzy nebudeme mít ádné jídlo a Starší mluví o zavedení pøídìlù. Bojím se budoucnosti. Bojím se o Arroyo.}
{418}{}{Vyvolenı! Prosím øekni mi, e u jsi dokonèil své poslání. Naše vesnice umírá, lidé jsou na tom moc špatnì.}
{419}{}{Ne, stále hledám.}
{420}{}{Bohuel zatím ne. Ale fakt se snaím.}
{421}{}{Jak je to s vámi?}
{422}{}{Je mi to líto, Vyvolenı, ale pomalu v tebe pøestávám vìøit. ivoty našich lidí jsou ve tvıch rukou. Prosím najdi Svatı Tøináct a pøines nám GECK!}
{423}{}{Naše úroda vadne, brahmíny hynou, všichni hladoví. Náøek dìtí v noci nikomu nedovolí spát. Jsme zoufalí.}
{424}{}{Budu snait dívat.}
{425}{}{Udìlám, co je v mıch silách.}
{426}{}{Opìt se k nám navracíš, Vyvolenı. Doufám, e ne s prázdnou?}
{427}{}{Já líto, nenajít GECK ještì.}
{428}{}{Je mi líto, ale stále nemohu GECK najít.}
{429}{}{U toho mám dost.}
{430}{}{Lidé tady umírají, zatímco ty se touláš svìtem. Co takhle zkusit hledat nìkde jinde, namísto vracení se sem.}
{500}{}{U s tebou mluvila Starší?}

#############################################################
#  TELL - ME - ABOUTS                                       #
#############################################################
{1000}{}{Starsi}
{1001}{}{Zakladatel}
{1002}{}{Obyvatel Vaultu}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Vault}
{1006}{}{Vyvoleny}
{1007}{}{Saman}
{1008}{}{Hakunin}
{1009}{}{Lecivy prasek}
{1010}{}{Most}
{1011}{}{Mynoc}

{1100}{}{Starší je naším vùdcem i naší matkou zároveò.}
{1101}{}{Náš velkı pøedek, od kterého pochází všechno naše vìdìní.}
{1102}{}{Ten první, kdo porazil chaos.}
{1103}{}{To je pøece naše krásná vesnièka.}
{1104}{}{To je obchodní stanice nìkolik dnù cesty smìrem na vıchod.}
{1105}{}{Vault je nebe.}
{1106}{}{Ty jsi Vyvolenı.}
{1107}{}{Léèí nás pomocí bylin a magie. Bydlí v severní èásti vesnice.}
{1108}{}{Léèí nás pomocí bylin a magie. Bydlí v severní èásti vesnice.}
{1109}{}{To je kouzelnı prášek, kterı èlovìka dokáe uzdravit, ale zpùsobuje ospalost.}
{1110}{}{Velkı most je jedinım vstupem do naší vesnice.}
{1111}{}{To bych mìl bıt já.}