#tento soubor pøeložil Miskot...mhoferek@telecom.cz
#############################################################
#  Message File: ACSporPL.msg                               #
#                                                           #
#       Body Type:  Spore Plant(Plant with Dark Soul)       #
#       Combat AI: ?                                        #
#       Weapons: ?                                          #
#       HP: ?                                               #
#       Skills to note: None                                #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: December 01, 1997                               #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{Vidíš masožravý plevel.}
{101}{}{Tenhle plevel není jen tak obyèejný porost. Mùže útoèit na
 èlovìka a jiná živá stvoøení.}
{102}{}{Ten ïábelský plevel je zvláštní mutace. A nevypadá to, že by
 zmutoval vlivem pøirozených podmínek.}
{103}{}{Nevidíš na tom plevelu nic zvláštního - tedy až na to, že útoèí na èlovìka.}

#############################################################
#  The following lines are for the dialog which the NPC     #
#  says. This will be disorganized because of the Design    #
#  Tool.                                                    #
#############################################################
{150}{}{Zahrada byla zbavena všech tìch ïábelských rostlin.}