#tento soubor pøeloil Somnambulus...somnambulus@hotmail.com
{100}{}{Pøed tebou stojí Hakunin, šaman tvého kmene. Jako obvykle máš pocit, e tìlem je sice tady, ale jeho duch bloudí nìkde po svìtech, které zná jen on sám...}
{101}{}{Vídíš Hakunina. Leí tìce zranìnı na zemi.}
{102}{}{Vídíš Hakunina. Umírá.}
{103}{}{Hakunin je ošklivì popálenı. Vypadá jak biftek, kterı nìkdo zapomnìl nad ohnìm, a stejnì tak i páchne. Vùbec nedokáeš pochopit, jak dokázal tak dlouho pøeít.}
{104}{hak001}{Vítej, Vyvolenı. Proè má pùda mé chıše potìšení ohøát se dotekem tvıch krokù?}
{105}{}{He?}
{106}{}{Jdu ti øíct sbohem. Odcházím splnit svùj svatı úkol.}
{107}{}{Chystám se odejít. A napadlo mì, e snad pøi té pøíleitosti budeš koneènì jednou mluvit jako normální èlovìk. Jak vidím, byla to marná nadìje.}
{108}{}{Nemìl bys to s tìma drogama tak pøehánìt. Mìj se.}
{109}{}{Mám zranìní. Dokáeš mì uzdravit?}
{110}{}{Na zahrádce ti vyrostl nìjakej švajneraj. Ale buï v klidu, u to tam máš vypletı.}
{111}{hak001a}{Odhal prosím zamlenım oèím starce dùvod svého pøíchodu.}
{112}{}{Bléh?}
{113}{}{Jdu ti øíct sbohem. Odcházím splnit svùj svatı úkol.}
{114}{}{Chystám se odejít. A napadlo mì, e snad pøi té pøíleitosti budeš koneènì jednou mluvit jako normální èlovìk. Jak vidím, byla to marná nadìje.}
{115}{}{Nemìl bys to s tím fetováním tak pøehánìt. Mìj se.}
{116}{}{Na zahrádce ti vyrostl nìjakej švajneraj. Ale buï v klidu, u je to tam vypletı.}
{117}{hak002}{Matka Zemì zpívá o novém šampiónovi, kterého smí nosit.... Ale moná e døíve, ne odejdeš sbírat ivotní zkušenosti, chtìlo by se ti vykonat malou laskavost.}
{118}{}{Jistì. Co potøebuješ?}
{119}{}{To záleí na spoustì okolností. A ta nejdùleitìjší je - co za to?}
{120}{hak002a}{Tváøe tohoto svìta a pohledy na nìj mohou bıt velmi rùznorodé - to je ostatnì lekce, kterou se brzy nauèíš.... Ale moná by ti døíve, ne odejdeš, získávat ivotní zkušenosti, nevadilo vykonat dobrı skutek...}
{121}{}{Chceš po mì nìjakou laskavost? Ale jistì, co by ne.}
{122}{}{No, nìco pro tebe asi udìlat mùu. Ale protoe mì strašnì namáhá u jen porozumìt ti, bude tì to nìco stát.}
{123}{hak003}{ehnám ti, nebo ty jsi opravdové dítì Matky Pøírody. Mùeš prosím, pouít svoje schopnosti a zbavit mou zahradu rostlin s temnou duší?}
{124}{}{Uh-huh.}
{125}{}{Tııı. Dej. Já mít bebí. *smrk*}
{126}{hak004}{Ké mì znovu poctí záøe tvé aury a... Och, vejdi zpìt do mıch dveøí, a s tím skonèíš, a já ti dám nìco velmi uiteèného.}
{127}{}{Urgh.}
{128}{hak005}{Mou zahradu znovu napadly rostliny s temnou duší, Vyvolenı. Mnoho let u se dotklo mıch kostí a já jsem pro ten vìènı boj s pøírodou pøíliš slabı. ádám tì tedy: vybojuj ho za mne.}
{129}{}{To asi nepùjde. Musím se hned vydat na cestu za svım svatım úkolem.}
{130}{}{Já vím, e to se mnou myslíš dobøe. Ale dneska mì hroznì bolí hlava, take si to potìšení budu muset odepøít.}
{131}{}{Na to zapomeò. Jsem budoucí vùdce tohoto kmene a nehodlám se tu shazovat tím, e budu makat u tebe na zahradì.}
{132}{}{Bude mi ctí, svatı mui.}
{133}{}{Ptal ses mì, jestli ti vypleju zahradu? V tom pøípadì ano.}
{134}{}{Zadarmo ani kuøe nehrabe.}
{135}{hak006}{ádá-li nìkdo odmìnu za dobrı skutek, zjistí nakonec, e jeho dar byl bezcennı. Ale já ti pøesto nìco dám a navíc ti pøidám pouèení o sebeklamu.}
{136}{}{To by šlo. Kde je ta zahrada?}
{137}{}{Ten nejlepší dárek, kterı bys mi mohl dát, by bylo, kdybys koneènì zaèal mluvit ÈESKY!}
{138}{}{Hmm... a co kdybys teï dostal lekci o zklamání ty? A to tím, e se na tebe zvysoka vykašlu. Mìj se.}
{139}{}{No, kdy to bereš takhle... myslím, e nemám zájem. Sbohem.}
{140}{hak006a}{Myslíš, e pokud øíkáme stejná slova, myslíme jimi i stejné vìci? Je moné se pomocí pouhıch slov dotknout duše toho druhého?}
{141}{}{Aha, no jo. Tak to jo. A lekce, kterou jsi mì dneska nauèil je, e mám sklapnout a zeptat se tì, kde je ta zahrada.}
{142}{}{No teï se schválnì vyzkouším dotknout tvı duše slovíèkem "sbohem". Jinımi slovy to znamená, e mizím.}
{143}{hak007}{Jak si jistì dobøe pamatuješ, je to na severovıchodì, ó bláhovı.}
{144}{}{Díky za pomoc.}
{145}{}{Díky. Tomu koneènì rozumím.}
{146}{}{Uráíš mì? Hmm... to si to s tou pomocí ještì rozmyslím. }
{147}{}{Brzy si tedy pøijdu pro svou odmìnu.}
{148}{hak008}{To bøímì, které teï neseš na svıch ramenou, se èasem stane ještì tìším.}
{149}{hak009}{Ké bohové ehnají tvému úsilí, Vyvolenı. A a bude zemì opìt èistì a volnì dıchat, potom nech tvá aura poctí mou pøítomnost.}
{150}{}{Beru to tak, e a s tím skonèím, tak bys mì rád znovu vidìl... ale tohle se snad dalo øíct i normálnì.}
{151}{}{Sbohem.}
{152}{hak010}{Vıbornì! ije v tobì duch našeho Zakladatele. Dovolíš-li mu vyrùst, prostoupí tì a tvımi prsty se znovu dotkne tváøe tohoto svìta. Ale samozøejmì odmìnou dostaneš víc ne jen toto ponauèení.}
{153}{}{To zní dobøe. A s tím skonèím, vrátím se k tobì.}
{154}{}{Take to dostanu nìco opravdu cenného. To mi staèí. Uvidíme se pozdìji.}
{155}{}{Zdá se, e tentokrát jsi to s tím tvım zájmem o šlechtitelství trochu pøepískl. A protoe nechci dopadnout jako ty, radši si najdu jinı hobby ne zrovna zahrádkaøení.}
{156}{hak011}{Èas mùe bıt buï ztracen nebo ušetøen - rozhodnout však o tom musíme vdy ihned. A chıše našeho ivota je zbudována z èinù, Vyvolenı.}
{157}{}{No jo. Hele, já u fakt musím. Sbohem. }
{158}{}{Víš, kdy si tu tak s tebou povídám, napadá mì, e èas by se fakt nemìl zbùhdarma utrácet. Mìj se. }
{159}{}{Ké by kadı z nás mìl trochu tvé moudrosti, ó velikı. Omlouvám se - samozøejmì se o to hned postarám.}
{160}{hak012}{I kdy si oblékneš pláš Vyvoleného, tvá temná duše jím bude vdy prosvítat.}
{161}{}{ádám o odpuštìní, svatı mui. Jak mùu oèistit svou duši?}
{162}{}{Pøesnì tak, staøíku. A udìláš dobøe, kdy si to dobøe zapamatuješ.}
{163}{}{U mì z tìch tvıch vástù bolí hlava. Mìj se.}
{164}{}{(Nevíš, co øíct, tak aspoò nahlas prdíš)}
{165}{hak013}{Svou duši nejlépe oèistíš tím, kdy vymıtíš démony z mé zahrady.}
{166}{}{Jako by se stalo, ó moudrı. A s tím skonèím, pøijdu si pro tvé odpuštìní.}
{167}{}{Snaíš se mi touhle litanií øíct, e kdy ti vypleju zahradu, tak to bude dobrı pro mojí nesmrtelnou duši? No dobøe, zkusím to.}
{168}{}{Mì se moje duše líbí taková, jaká je. Sbohem.}
{169}{}{To víš, e jo. U se na to tøesu. Mìj se.}
{170}{hak014}{Vítám tì, Vyvolenı. Tvá pøítomnost je poehnáním pro tuto zemi.}
{171}{}{Dík.}
{172}{}{Myslíš jako, e jsem na tom teï líp, jo?}
{173}{hak015}{Stálé opakování jedné èinnosti ti vštípí smysl pro dokonalost. Tohle musíš pochopit, Vyvolenı.}
{174}{}{Poèkej, neøíkej mi to. Mnì je lépe a tobì to taky udìlalo dobøe. Je to tak? Díky.}
{175}{}{Jsi moudrı a laskavı, Svatı mui.}
{176}{hak017}{Vítej, Sémì Zakladatelovo. Jak se mohu dotknout vyvolené duše?}
{177}{}{Uh, kde pøesnì leí ta tvoje zahrada?}
{178}{}{Mám nìjaká poranìní. Dokáeš mì vyléèit?}
{179}{}{Ale nic. Sbohem.}
{180}{hak018}{Ach. Vynesl jsi na svìtlo ducha našeho Zakladatele a na tváø starého mue vracíš úsmìv. Za odmìnu ti dám léèivı prášek. A pamatuj si: stejnì jako léèí tìlo, zamluje i mysl.}
{181}{}{Díky.}
{182}{hak018a}{A kdykoliv mi pøineseš kvìtinu Broc a koøen Xander, namíchám ti z nich léèivı prášek. A vdy kráèíš po pravıch cestách a tvé srdce nech následuje Zakladatelùv odìv.}
{183}{}{A kde tyhle dvì vìci najdu?}
{184}{}{Díky.}
{185}{}{Skoro je mi líto, e u budu muset jít. Zrovna tvá slova zaèínala bıt rozumná. Mìj se.}
{186}{hak019}{Ach, Vyvolenı má zahrada u je v poøádku - a co tvá?}
{187}{}{Jsem v pohodì.}
{188}{}{Potøebuju uzdravit.}
{189}{}{Kde jsi øíkal, e najdu ty kytky?}
{190}{}{Ale já pøece nemám ádnou zahradu - o èem to tu doprèic zase meleš?}
{191}{}{Mùeš mi udìlat trochu léèivého prášku?}
{192}{}{Zapomeò na to. U musím padat.}
{193}{}{He?}
{194}{}{(Krkáš)}
{195}{hak020}{Tvá slova mì naplòují radostí. Bìda, bohové u mi šeptají do uší. Sbohem.}
{196}{}{Sbohem.}
{197}{}{Poøád mícháme bylinky? Nashle.}
{198}{hak021}{Kadı z nás má svou zahradu. Ké nikdy neztratíš z oèí svùj cíl. A teï sbohem. Nesmím se opozdit na schùzku s bohy.}
{199}{}{Mìj se.}
{200}{}{Vsadím se, e si ty své bohy nosíš poøád s sebou. Sbohem.}
{201}{hak022}{Pohlédni k severu, Vyvolenı, a cesta se ti otevøe.}
{202}{}{Oukej. Díky.}
{203}{hak023}{Je mi ctí poslouit Vyvolenému.}
{204}{hak024}{Je to stejné jako se ivotem. Ze dvou vznikne tøetí. Pro vırobu léèivého prášku potøebuješ obojí, kvìtinu Broc i koøen Xander.}
{205}{}{Aha. Díky}
{206}{}{Pú. Méïa.}
{207}{hak025}{Pøeji ti, a ho nikdy nepotøebuješ.}
{208}{}{Oukej. Díky.}
{209}{}{Uch!}
{210}{hak026}{Jsi v poøádku.}
{211}{}{Díky.}
{212}{}{ádné pouèky? ádné nesrozumitelné vásty? Jsi v poøádku?}
{213}{hak027}{Vítej, Vyvolenı. Potìš nás zprávou, e posvátnı GECK bude brzy nalezen. Naše vesnice strádá, naše potøeby jsou velké a náš èas se krátí.}
{214}{}{Òuòu.}
{215}{}{A tvoje schopnost mluvit normálnì je zanedbatelná. Poøád na tom dìlám.}
{216}{}{Pracuju na tom. }
{217}{}{Dej mi pokoj, starouši. Dìlám co mùu.}
{218}{}{Stále ho hledám, ó Svatı. Doufám, e GECK brzo získám.}
{219}{hak028a}{Nech se zemì stane poduškou pro tvé kroky.}
{220}{hak028b}{Nech voda uhladí tvou cestu.}
{221}{hak028c}{Nech tì vítr vede k tvému cíli.}
{222}{hak028d}{A nech ti oheò pøipaluje zadek, dokud nesplníš svùj úkol.}
{223}{}{Díky.}
{224}{}{Co jsi to øíkal?!}
{225}{}{Uh.}
{226}{}{Huh?!}
{227}{hak029}{Vítej zpìt, Vyvolenı. Na tvé tváøi vidím, e spásnı GECK nám stále ještì nepatøí. Mìj vytrvalost mravence nebo naše zásoby tají jako sníh na slunci. Jsi naše poslední nadìje.}
{228}{}{Uh-hu.}
{229}{}{Snaím se. A rád bych vidìl mravence, kterı ušel tolik kilometrù jako já.}
{230}{}{Dìlám co mùu.}
{231}{}{Zdvojnásobím své úsilí svatosti. Nenechám vás padnout.}
{232}{}{No jo. U mì nudí tohleto poslouchat.}
{233}{hak030}{Vyvolenı - naše vesnice je zoufalá. Dìti u tıden nejedly. Prosím, u moc dlouho nevydríme.}
{234}{}{Uh-huh.}
{235}{}{Snaím se. Já se snaím! Dejte mi pokoj!}
{236}{}{Já GECK najdu, svatosti. Máš moje slovo.}
{237}{}{Udìlám všechno, abych GECK našel.}
{238}{hak031}{Vyvolenı, v hodinách èasu zbıvá u jen nìkolik zrníèek. Prosím. Pøines nám rychle GECK a dej naší vesnici tolik budoucnosti, jako je písku na plái u oceánu. Spìchej, dokud nespadlo poslední zrnko.}
{239}{}{Uh-huh.}
{240}{}{Jasnì. Jdu ho hledat.}
{241}{}{ivot je jak plá, huh?}
{242}{}{Já GECK najdu, svatosti. Nenechám náš lid padnout.}
{243}{hak032}{Vyvolenı, duchové našich pøedkù mì pøivedli do svìta snù, odkud se mohu dotknout tvé mysli. Naše vesnice strádá bez svatého GECKu. Tak jako otec bdí nad svımi dìtmi, i ty tøímáš ve svıch rukou naše ivoty.}
{244}{hak033}{Znovu se tì mùj duch dotıká z prázdnoty, Vyvolenı. Naše úroda vadne, naše zásoby mizí. Vra se k nám a pøines GECK. Tvùj neúspìch je naším ztracenım svìtlem.}
{245}{hak034}{Vyvolenı. Vesnice hyne. Je stále tìší dotknout se tvıch snù. Musíš si pospíšit, jinak my všichni...}
{246}{hak035}{Vyvolenı? Vyvolenı? Slyšíš mì? Vesnice umírá. Celá naše budoucnost umírá s ní. Zbıvá nám u jen málo èasu. Spìchej. Spìchej...}
{247}{hak101}{Vyvolenı - stíny z hlubin temnot dorazily pøed tebou.}
{248}{}{Oúúú!}
{249}{}{Co se stalo?}
{250}{}{Vypadáš špatnì. Nech mì, a ti pomohu.}
{251}{hak102}{Dítì Pøírody, jak jsme jen mohli naloit takové bøímì na tvá ramena? (povzdech) Tvoji lidé byli uneseni.}
{252}{}{Pyè?}
{253}{hak103}{Ano. Jsou pryè. Mnoho temnıch duší sem pøišlo, pøilétly na eleznıch ptácích jak hejno hladovıch kobylek. Své zlo skryly pod lesklou kùí. }
{254}{}{Jú! Lesklé. Hezké!}
{255}{hak104}{Ne! Lesklé nebıt hezké! Unesli naše lidi a odvezli je nìkam na jihozápad.}
{256}{}{Jù.}
{257}{hak105}{Ano. Velkı smutek a bolest. Proto jsem zùstal mezi dvìma svìty, Vyvolenı. Zachraò naše lidi.}
{258}{}{Hé?}
{259}{hak106}{Vyvolenı, dovol, prosím, mım slovùm, a se dotknou tvé duše. Jdi na jihozápad. Jih a západ. Zachraò naše lidi. Zachraò je.}
{260}{}{Ah-ha..}
{261}{hak107}{Díkybohu. Teï se má duše mùe koneènì pøipojit k vìèné písni èasu. Dobrou cestu, Vyvolenı.}
{262}{}{Mám jít?}
{263}{hak108}{Jdi u, prosím tì! Debile...}
{264}{}{Mìj se.}
{265}{hak109}{Temní pøišli. Všechny zajali.}
{266}{}{Temní? Koho tím myslíš?}
{267}{hak110}{Nejdøív pøišla vìtrná bouøe. A z ní vylétli ohromní elezní draci, kteøí plivali oheò. Z bøicha tìch oblud pak vylezli zlí mui a pøinesli smrt našim bojovníkùm.}
{268}{}{Naši bojovníci je nedokázali zastavit?}
{269}{hak112}{Náš duch byl silnı, ale naše kopí byla slabá. A ti ïáblové spálili naše bojovníky strašlivım pekelnım svìtlem.}
{270}{}{Zabili všechny?}
{271}{hak113}{Všichni jsou buï mrtví, nebo byli odvleèeni. Moje duše se vrátila do tohoto tìla jen proto, abych mohl zjevit pravdu Vyvolenému.}
{272}{}{Co se stalo s tìmi, které odvedli?}
{273}{hak114}{elezní draci je spolkli, a potom se vrátili do vìtrù.}
{274}{}{Hmm...a kterım smìrem odletìly ty vìtry, ve kterıch zmizeli ti draci?}
{275}{hak115}{Copak jsi mì nikdy neposlouchal, kdy jsem tì kadoroènì uèil tanec vìtrnıch duchù? Na jih, samozøejmì.}
{276}{}{Tvoje líèení byla tak ivá a mocná, velkı Hakunine, e jsem èasto zùstal stát zkoprnìlı údivem nad hloubkou a moudrostí tvıch slov.}
{277}{}{Aha, tyhle vìtry. No jasnì. }
{278}{hak116}{Ano, odlétli s jiním vìtrem. Vyslechl jsem rozhovor tìch temnıch duší. Chystali se nechat své elezné draky odpoèinout na místì zvaném Navarro døíve, ne pøekroèí velkou mísu slz naší Matky Zemì.}
{279}{}{Co mám udìlat?}
{280}{}{Mísu slz?}
{281}{hak117}{Pro mì u nic. Vyvolenı, ty musíš najít sídlo temnıch duší a zachránit naše lidi.}
{282}{}{Zkusím to.}
{283}{hak118}{Ty jsi Vyvolenı. Musíš to dokázat.}
{284}{}{Hakunine?}
{285}{}{To je poprvé, co rozumím tomu, co jsi øekl.}
{286}{hak120}{Oceán slz, které Matka Zemì vyplakala pro své dìti.}
{287}{}{Aha, tenhle oceán. Ale co mám tedy udìlat?}
{288}{hak121}{Podivná mlha jim ukradla jejich mysl a poslala je do øíše Spánku. Zlí pak chodili mezi spáèi, kteøí spali, ale nesnili.}
{289}{}{A potom?}
{290}{hak122}{Pøíliš mnoho let a pøíliš mnoho zranìní, Vyvolenı. Teï mì musíš poslouchat.}
{291}{}{Dobøe.}