#tento soubor pøeloil Raptor...xraptor.@email.cz
{100}{}{Vidíš mladou enu.}
{101}{}{Vidíš Chrissy, Rebecèinu dceru.}
{102}{}{Vidíš hezkou mladou enu. Vypadá sebejistì a bojovnì.}
{103}{}{Jestli mì pøicházíš znásilnit, natáhnu ti ho jak kravatu. Je ti to jasnı?}
{104}{}{Nech mì hádat. Kámoši u jsou utahaní z toho, jak jsem je nakopala mezi nohy, tak poslali tebe, a to na mì zkusíš zas ty. Dobrá, dopadneš stejnì jako oni. Jen budu muset kopat trošku vıš. Je ti to jasnı?}
{105}{}{Kravatu?}
{106}{}{}
{107}{}{Co se tu dìje? Kdo jsi?}
{108}{}{}
{109}{}{Chci jen vìdìt, kdo jsi a co se tady dìje.}
{110}{}{No jo. To je taková pestrá ozdoba na krk. Vypadá to trochu jako šátek, ale jen pro mue. A teï si pøedstav, jak tì nakopnu TAK, e se ti tvoje ozdoba omotá okolo krku. Máš zájem?}
{111}{}{Rozumìt. Ty neubliovat mi.}
{112}{}{Dovedu si to ivì pøedstavit; prosím, neubliuj mi.}
{113}{}{Ok, tak proè jsi tady?}
{114}{}{}
{115}{}{Já chtít vìdìt, o co tu jít? Kdo ty?}
{116}{}{}
{117}{}{Chci jen vìdìt, kdo jsi a co se tady dìje.}
{118}{}{Opravdu? Skvìlé! Tak jdeme.}
{119}{}{Ok.}
{120}{}{V krátkosti: Jmenuju se Chrissy a jsem ze Squatu. Byla jsem minulı tıden venku na prùzkumu a našla jsem nìjakı vchod. Myslela jsem si, ze by to mohl bıt tøeba starı opuštìnı dùl nebo nìco takového. Tak jsem se to vydala zjistit. A není to dùl; je to tajnı vstup do Vaultu 15. Vault je pouíván jako základna pro bandity, kteøí si øíkají Khanové. Chytili mì a jejich velitel, Darion, mì tady zamkl.}
{121}{}{Ok. Já vzít tì domù.}
{122}{}{V poøádku, vezmu tì domù.}
{123}{}{Dìkuju. Dneska je mùj šastnı den. Jsem ráda, e tì opìt vidím. Jak se ti odmìním?}
{124}{}{}
{125}{}{Co se tu dìje? Kdo jsi?}
{126}{}{}
{127}{}{Chci jen vìdìt, kdo jsi a co se tady dìje.}
{128}{}{Prosím, vezmi mì k mojí matce, Rebecce.}
{129}{}{Mùj rytíø v lesklém brnìní se vrátil. A svítilo by ještì víc, kdybys ho obèas pøeleštil. Jo a taky by neškodilo se nìkdy vykoupat. Tak co pro tebe mùu udìlat?}
{130}{}{Já jen tebe pozdravit. Teï jít.}
{131}{}{Jdu tì jen pozdravit. U musím jít.}
{132}{}{Hele, já vím, e nejsem moc dobrı øeèník. Ale chci, abys vìdìl, e jsem ti opravdu moc vdìèná za svou záchranu. Díky mnohokrát!}
{133}{}{Nebıt zaè.}
{134}{}{Rádo se stalo.}
{135}{}{Lidé ze Squatu jsou tìmi lidmi chránìni za to, e pomáhají dret Vault v tajnosti. Ale oni nevìdí, co se tam dole doopravdy dìje. Darion nám øekl, ze a se Vault opraví, budeme mít my všichni bezpeèné místo k ivotu a spoustu vody a jídla. Ale to všechno jsou li. Byla jsem tam a všechno jsem vidìla. Vault je mrtvı a stroje na vırobu jídla a vody jsou rozbité. Naše jídlo a voda pocházejí z pøepadenıch karavan a loupeí.}
{136}{}{Podívej, já teï pùjdu domù a budu všechny varovat. Nemùeme tìm zrùdám u dál pomáhat. Vezmeš mì domù?}