#tento soubor pøeložil Raptor...xraptor.@email.cz
{100}{}{Vidíš mladou ženu v rozedraných šatech.}
{101}{}{Vidíš Daliu.}
{102}{}{Vidíš mladou ženu v rozedraných šatech. Vypadá vyplašenì a obezøetnì se rozhlíží kolem.}
{103}{}{Ahoj. Jsem Dalia. S èím ti mùžu pomoci?}
{104}{}{S nièím, jen tì zdravím.}
{105}{}{Uh, kdo jsi?}
{106}{}{Co tady dìláš?}
{107}{}{Vypadáš jako nìjaká hlídaèka.}
{108}{}{Už pùjdu.}
{109}{}{Jen tì zdravím.}
{110}{}{Kdo jsi ty?}
{111}{}{Co tu dìláš?}
{112}{}{Vypadáš jako bys hlídala tuhle cestu.}
{113}{}{Už pùjdu.}
{114}{}{I já tì zdravím. Promiò, ale radìji bìž pryè.}
{115}{}{Chci promluvit s ty.}
{116}{}{OK, jdu.}
{117}{}{Chci si s tebou promluvit.}
{118}{}{Sbohem.}
{119}{}{Jak už jsem øekla, jmenuju se Dalia. Podívej se, nechci být nezdvoøilá, ale nechci teï s nikým mluvit. OK?}
{120}{}{OK, sbohem.}
{121}{}{Jen ještì nìco.}
{122}{}{Tak tì teda opustím.}
{123}{}{Chci se tì jen na nìco zeptat.}
{124}{}{Mám ráda èerstvý vzduch a stromy, tak tady stojím. Máš snad nìco proti tomu?}
{125}{}{Promiò, já jít.}
{126}{}{Ne, nemít. Nìco se zeptat.}
{127}{}{Ne nemám, ale nìco mì zajímá.}
{128}{}{Promiò, tak já už pùjdu.}
{129}{}{Ne, samozøejmì, že nehlídám tuhle cestu. V téhle díøe ani není co hlídat. Øekla jsem ti, mám prostì ráda èerstvý vzduch. A už bìž.}
{130}{}{Ty hezky mluvit. Øíkat víc.}
{131}{}{Omluvit že já obtìžovat ty. Odcházet.}
{132}{}{Ale když si tu tak hezky a nezávaznì konverzujeme, tak proè konèit?}
{133}{}{Myslím, že je èas odejít.}
{134}{}{Bože ne, už zase ty? Podívej, nemám ti co øíct. Zmiz!}
{135}{}{}
{136}{}{}
{137}{}{Nechci se s tebou hádat. Nech mì na pokoji.}
{138}{}{}
{139}{}{}
{140}{}{Ahoj. Já jsem Dalia. S èím ti mohu pomoci?}
{141}{}{Èlovìk jít tudy? Spìchat?}
{142}{}{S nièím.}
{143}{}{S nièím.}
{144}{}{Vidìla jsi tudy nìkoho utíkat?}
{145}{}{Tudy èasto nìkdo prochází. Nestarám se o to.}
{146}{}{Nemít èas na tvoje kecy.}
{147}{}{Aha, no tak dobøe.}
{148}{}{Holka být v nebezpeèí. Mladá holka. Nìèí céra. Ty pomoct, prosím?}
{149}{}{Na ty tvoje kecy nemám èas.}
{150}{}{Tak fajn. Sbohem.}
{151}{}{Podívej, jde tu o život mladého dìvèete. Její matka se o ní bojí. Pomùžeš mi?}
{152}{}{Promiò, to jsem nechtìla. Jenom mì najali na hlídání téhle cesty. Nevím, o co tu jde. Já... taky jsem kdysi mìla dceru a... ano, nìjaký muž tudy prošel. Nechala jsem ho projít, protože znal heslo. Hmm, ale ty jsi vlastnì to heslo znal taky. Bìž dál. A já odsud odejdu.}
{153}{}{Díky. Já nezapomenout na to, Dalia.}
{154}{}{Díky. Nezapomenu ti to, Dalio.}
{155}{}{Tak táhni k èertu a nech mì být!}
{156}{}{OK.}
{157}{}{Tak táhni k èertu a nech mì na pokoji!}
{158}{}{OK.}