#tento soubor pøeložil Raptor...xraptor.@email.cz
{100}{}{Vidíš starého muže.}
{101}{}{Vidíš Dariona, vùdce bandy Nových Khanù.}
{102}{}{Vidíš starého muže s øídkými šedivými vlasy. Vypadá, že je na svùj vìk ve skvìlé kondici.}
{103}{}{Tak koneènì jsi tady. Náš spasitel ubožákù, ochránce práva a symbol nadìje lidstva. Taková blbost! Dobrá, ještì než zaèneš s tìma otravnýma žvástama, chci ti øíct, že ti na nì seru. Stejnì jsi jen žrádlo pro mýho psa. Vem si ho, Èerte!}
{104}{}{OK.}
