#tento soubor pøeložil Raptor...xraptor.@email.cz
{100}{}{Vidíš èlena Khanù.}
{101}{}{Vidíš èlenku Khanù.}
{102}{}{Vidíš drsnì vyhlížející osobu v brnìní, ozbrojenou až po zuby a s tvrïáckým pohledem. Tohle musí být Khan.}
#node1
{103}{}{Co to sakra... tebe neznám. Kdo k èertu jsi?}
#responses 1
{104}{}{Tady máš mùj obèanskej prùkaz!}
{105}{}{Jmenuju se... ehm... Pat. Jsem tu nováèek.}
{110}{}{Chcípni!}

#node 2
{106}{}{Chytrá prdelka. A teï pøedveï, jak umíš støílet.}

#node 3
#made skill check
{107}{}{No jasnì. Promiò, že jsem tì nepoznal. Pokraèuj dál.}
{108}{}{Hej, já nejsem takovej blbec, za jakýho mì máš.}

#node 4
{109}{}{Ty ještì nejsi po smrti? Zatracenì.}

#idle talking messages
#BLOCK 1
{110}{}{Hergot, za tohle nudný nicnedìlání mi Darion nikdy dost nezaplatí.}
{111}{}{Obèas si sednu a vùbec na nic nemyslím.}
{112}{}{Mnì je úpnì fuk, na co myslej ostatní.}
{113}{}{Ignorance je ráj... aspoò si to teda myslím.}
{114}{}{Kdy už tudy pùjde další karavana? Hodilo by se trochu zábavy.}
{115}{}{Šikla by se pøestávka.}

#BLOCK 2
{116}{}{Sakra, furt mì bolí to místo, kam mì kopla ta dìvka Chrissy.}
{117}{}{Ani nevím, že bychom nìkoho pøibírali.}
{118}{}{Kdy už koneènì vypadneme z tohohle pitomýho místa?}
{119}{}{Sice tì neznám, ale na to sere pes.}
{120}{}{To je nuda, když kolem není nic k zabíjení.}
{121}{}{Kde je tu proklatì koupelna?}

#BLOCK 3
{122}{}{Hej, už dlouho jsme se trochu nepovyrazili. To tu nikde není nìjakej šerif nebo tak nìco?}
{123}{}{Mìli bysme zaèít vládnout. Jak za starých èasù.}
{124}{}{Èlovìèe, jaký to asi je bejt prezidentem?}
{125}{}{Vsadím se, že ty dokážeš všechno. Tøeba i být prezidentem.}
{126}{}{Myslím, že dneska by na mì byl táta pyšnej. Možná to byla chyba, oddìlat ho.}
{127}{}{NENÁVIDÍM KRYSY! NENÁVIDÍM, NENÁVIDÍM, NENÁVIDÍM!}

#BLOCK 4
{128}{}{Hej, to je nìjakej novej druh brnìní, co máš na sobì? Kde se to dá splašit?}
{129}{}{Tenhle Vault smrdí. No øekni, není hnusnej?}
{130}{}{Hej, na koho že to vlastnì máme dávat bacha?}
{131}{}{Musím tu poøád stát jak idiot. Jen tu stojím a stojím.}
{132}{}{Myslím, že bychom se mìli na ty nahoøe vykašlat a øíct tomuhle blbýmu místu sbohem.}
{133}{}{Máš snad nìjakej problém s krysama?}

#BLOCK 5
{134}{}{Není nad to prokopnout kryse hlavu. Zkus si to nìkdy.}
{135}{}{Miluju zbranì! ZBRANÌ SE MI HROZNÌ LÍBÍ! OPRAVDU, OPRAVDU JE MILUJU!}
{136}{}{Hej, poslouchá mì nìkdo?}
{137}{}{No tak dobøe. Mluvím si pro sebe, aby mi tu z toho nepøeskoèilo.}
{138}{}{Hej, pamatuje si tu nìkdo, jaký to bylo v tý hospodì "U ztracený šance"?}
{139}{}{Jo vodka, rum, tequila a k tomu tøi panáky Nuka Coly.}

#Lights on
{140}{}{Hej, koukni se -- svítí svìtla. Co se to sakra...}
{141}{}{Darion øíkal, ze nechá ty pitomý svìtla spravit.}
{142}{}{Nevypadá to, že by se generátor opravil sám, co?}
{143}{}{To je divný; teï najednou nìjak líp vidím. Ježiš, tohle místo vypadá hnusnì!}
{144}{}{Jú, koneènì je jasno. Kde byl ten vypínaè?}