#tento soubor pøeloil Raptor...xraptor.@email.cz
{100}{}{Vidíš malého mue s knihou v ruce.}
{101}{}{Vidíš doktora Jonese.}
{102}{}{Vidíš malého mue. V ruce drí knihu "Doktorem snadno a rychle."}
{103}{}{Ahoj, já jsem doktor Jones. Mùeš mi øíkat Jon. S èím ti mohu pomoci?}
{104}{}{Mám bebí. Pofoukáš?}
{105}{}{Bolet bøíško. Vyléèíš?}
{106}{}{Mít velké bebí, spravíš?}
{107}{}{Mít otázky. Oukej?}
{108}{}{Promiò, já jít.}
{109}{}{Mám zranìní. Mùeš mi pomoci?}
{110}{}{Cítím se nemocnı. Mùeš mi pomoci?}
{111}{}{Podaøilo se mi zmrzaèit se. Mùeš mi pomoci?}
{112}{}{Chci ti poloit pár otázek.}
{113}{}{Jen tì chci pozdravit.}
{114}{}{Samozøejmì. Tady, dám ti injekci tohohle -- trošku to štípne -- teï ještì obvaz a jsi zas jako ze škatulky.}
{115}{}{Já díky. Sbohem.}
{116}{}{Díky, doktore. Cítím se mnohem líp.}
{117}{}{Samozøejmì. Musíš vypít tohle -- všechno. Vím, chutná to hroznì. A teï si tady lehni na postel a já tì ráno vzbudím.}
{118}{}{Já cítit se dobøe. Sbohem.}
{119}{}{Díky doktore, to byla prima finta.}
{120}{}{Promiò, ale nemám tu vhodné nástroje k provádìní chirurgickıch zákrokù. Doporuèuju ti, abys zašel do nìkterého vìtšího mìsta a vyhledal chirurga. Zkus Vault City. Je to na sever odsud.}
{121}{}{OK. Sbohem}
{122}{}{V poøádku. Dìkuju ti i tak.}
{123}{}{Co chceš vìdìt?}
{124}{}{Tvùj šéf bıt Darion?}
{125}{}{Ty smìt odsud odejít?}
{126}{}{Co ty vìdìt o Darion?}
{127}{}{Bıt to tady príma ?}
{128}{}{Øíkáš, e Darion má pejska??}
{129}{}{Já jít.}
{130}{}{Pracuješ pro Dariona?}
{131}{}{Mùeš odsud odejít, kdykoliv chceš?}
{132}{}{Co mi mùeš øíct o Darionovi?}
{133}{}{Jak jsi se sem dostal?}
{134}{}{Neøíkal's náhodou, e Darion má psa?}
{135}{}{Díky za informace. U pùjdu.}
{136}{}{No vlastnì ano i ne. Nevybral jsem si to. Jsem tu vìzeò. Darion je tu u dlouho a potøebuje nìjakého doktora. Khanové mì tu drí pro svou potøebu. Ale radìji bych pracoval pro lidi z té komunity nahoøe. Nemají tam ádnou lékaøskou péèi a je dost vìcí, které bych pro nì mohl udìlat.}
{137}{}{OK. Potøebuju vìdìt víc.}
{138}{}{Díky. Sbohem.}
{139}{}{To je od tebe velice šlechetné.}
{140}{}{Jasnì. U musím jít.}
{141}{}{Jsou to jen bezdomovci! A si klidnì chcípnou. Ty radši starej o svùj vlastní krk.}
{142}{}{Ne. Jsem tady vìznìm. Nemùu odejít ani kvùli doplnìní zásob lékù. Darion mi posílá pro všechno, co potøebuju.}
{143}{}{Já chápat. Vyvolenı u muset jít.}
{144}{}{Vyvolenı chtít vìdìt víc.}
{145}{}{Øekl bych, e nejsi natolik dùvìryhodná osoba, aby tì tu nechali volnì potulovat.}
{146}{}{Rozumím. Promiò, ale u musím jít.}
{147}{}{Je mi líto, e to slyším.}
{148}{}{Darion je zvláštní pøípad. Má v hlavì víc vrtochù ne jeho pes blech v koichu. Jestli tomu dobøe rozumím, tak kdysi dávno byl èlenem nìjakého gangu, kterı si øíkal Khani. Ti unesli Tandi, dnešní prezidentku NCR. Tenkrát to byla ovšem ještì mladá dívka. Dreli ji pod zámkem kvùli vıkupnému. Její otec si to ale nenechal líbit a najal si nìkoho, aby mu jí našel a pøivedl zpátky. Darion byl jedinı z Khanù, kterı ten masakr pøeil.}
{149}{}{Uh... co jsi to øíkal.}
{150}{}{Musím jít.}
{151}{}{Hmm...hmmm. No u budu muset jít.}
{152}{}{Nó, musím øíct, e tvoje vìdomosti jsou opravdu pozoruhodné.}
{153}{}{Ten chlapík je pøesnì mùj typ.}
{154}{}{Byl jsem unesen. Cestoval jsem z Vault City do New Reno na dovolenou. Jednou veèer jsem si šel lehnout a ráno jsem se probudil spoutanı a s roubíkem v puse. A za tıden nebo dva u jsem byl tady. Od té doby tu jsem zavøenı.}
{155}{}{Uch.}
{156}{}{Díky. Vyvolenı se louèit.}
{157}{}{Slabí se èasto stávají koøistí silnıch. To je ivot, pøíteli.}
{158}{}{To je mi líto. Upøímnou soustrast. Jsem v duchu s tebou.}
{159}{}{Zajímavá story, ale u musím bìet.}
{160}{}{Jo, má psa. Osobnì si myslím, e je to ta nejhnusnìjší a nejodpornìjší bestie na celém širém svìtì. Ale na druhé stranì to vypadá, e Dariona má docela rád, tak to s ním snad nebude zase a tak špatnı.}
{162}{}{Uh, sbohem.}
{163}{}{Jasnì. Dobrá, díky za upozornìní.}
{164}{}{Aha. No, u musím jít.}
{165}{}{Nebudu pomáhat nìkomu, jako jsi ty. Zmiz odsud.}
{166}{}{OK, no tak se opatruj a vra se, kdy budeš nìco potøebovat.}
{167}{}{OK.}
{168}{}{Teï je z nìj paranoik. Vìøí tomu, e ho Tandi chce zabít. Je posedlı pomstou a chce, aby Tandi zemøela. Cítí se vinen za to, e se schoval a pøeil, místo aby zemøel spolu se svım gangem... a tak dále, a tak dále, ten seznam jeho obsedantních vizí by byl ještì dlouhı.}