#tento soubor pøeložil Raptor...xraptor.@email.cz
{100}{}{Vidíš bezdomovce.}
{101}{}{Vidíš Johna, bezdomovce.}
{102}{}{Vidíš muže støedního vìku ve starých, obnošených šatech.}
{103}{}{Promiò, cizinèe, nemám na tebe èas.}
{104}{}{Proè nechceš mluvit?}
{105}{}{Oukej.}
{106}{}{V poøádku, uvidíme se.}
{107}{}{Poèkej minutku. Proè se mnou nechceš mluvit?}
{108}{}{Jsme velmi uzavøené spoleèenství a nechceme tu žádné problémy ani zásahy z okolního svìta. Prosím, nech nás být.}
{109}{}{OK.}
{110}{}{Ahoj... a sbohem.}
{111}{}{Díky za všechno, co jsi pro nás udìlal. Omlouvám se za svoje pøedešlé chování.}
{112}{}{Seru na tebe ty parchante!}
{113}{}{Sakra. Nesnáším, když se tohle stane.}
{114}{}{Tumáš! Tohle tì nauèí.}
