#tento soubor pøeložil Raptor...xraptor.@email.cz
{100}{}{Vidíš banditu z gangu Khanù.}
{101}{}{Vidíš Phila, strážce z bandy Khanù.}
{102}{}{Vidíš drsnì vypadajícího mladíka v kovovém brnìní. Je tìžce ozbrojen.}
{103}{}{Mìl bych tì hned odstøelit, ale jsem docela zvìdavej, jestli mi máš co øíct.}
{104}{}{Já hledat špeha. On jít tudy.}
{105}{}{Vyvolený hledat ztracená holka. Ty vìdìt kde ona?}
{106}{}{Já zabloudit. To náhoda. Vyvolený jít pryè.}
{107}{}{Už mì sereš. Já tì teï odprásknout. Ty být mrtvý a já mít svatý klid.}
{108}{}{Uh, ty nevìøíš na lásku na první pohled?}
{109}{}{Hledám zvìda, který tudy šel.}
{110}{}{Hledám jedno ztracené dìvèe. Nevidìl jsi ji?}
{111}{}{Promiò, spletl jsem si cestu. Radši už pùjdu.}
{112}{}{Pracky nahoru a hoï se do klídku, ty sráèi.}
{113}{}{Snad si mùžeme promluvit v klidu jako dva civilizovaní lidé.}
{114}{}{Aha, tak to bych mohl být já. A teï když jsi mì našel, co s tím jako hodláš dìlat?}
{115}{}{Proè ty špehovat Rebecca?}
{116}{}{Vyvolený teï vìdìt, že nezastøelit nesprávná osoba. Dìkuju!}
{117}{}{Nic, já jít.}
{118}{}{Proè sleduješ Rebeccu?}
{119}{}{Chtìl jsem se jen ujistit, že zastøelím tu správnou osobu. Díky a pøeji krásný den!}
{120}{}{Hmm. Nic. Myslím, že už pùjdu.}
{121}{}{Nechce se mi vìøit, že si myslíš, že sem mùžeš jen tak nakráèet a já že ti budu odpovídat na tvoje otázky! Ale co, stejnì tak jako tak chcípneš a já mám dneska sklony ke šlechetnosti. Máme vzadu zamèenou její holku a trošku tam s ní laškujeme. Ta dìvka Rebecca jí furt hledá, tak si musíme dávat bacha, aby ses tu necourala moc blízko.}
{122}{}{Ty mít nemocnou hlavu. Vyvolený opravit to. Odstranit tu hlavu.}
{123}{}{Co myslíš tím "laškováním"?}
{124}{}{Oh, to dobré vysvìtlení. Já teï jít.}
{125}{}{Ty jsi nemocnej, chudinko malá. Zazpívám ti ukolébavku. Zaruèenì tì uspí. Navìky.}
{126}{}{Fajn. Tak si to užijte a já zas pùjdu.}
{127}{}{Nechte to dìvèe na pokoji a budete žít.}
{128}{}{Pøemýšlej o tom po smrti, blázne.}
{129}{}{}
{130}{}{}
{131}{}{Proè bych to sakra mìl udìlat?}
{132}{}{Je to dobré pro tvojí nesmrtelnou duši.}
{133}{}{Protože já jsem ta nejhorší vìc, která tì v životì potkala. Nechte to dìvèe na pokoji, nebo to bude to poslední, èeho budete v životì litovat.}
{134}{}{Protože jestli budeme bojovat, jeden z nás zemøe. Já nechci zemøít o nic víc než ty, takže to ukonèeme v míru. OK?}
{135}{}{Pøestaò žvanit.}
{136}{}{}
{137}{}{}
{138}{}{To zní skoro jako výzva. Pøijímám jí.}
{139}{}{}
{140}{}{}
{141}{}{Hmm... já... no tak jo. Oukej. Tady máš klíè od její cely. Ta holka je v zadní èásti pøístøešku. Seber jí a zmizte, ale nevracej se. Jestli se ještì nìkdy potkáme, uvidíme, kdo z nás bude žít a kdo zemøe.}
{142}{}{Tak do toho. Pøesvìdèíme se, kdo z nás dvou pøežije.}
{143}{}{Díky, udìlal jsi správnou vìc.}
{144}{}{Jediná cesta, jak se odtud mùžeš dostat, je nohama napøed. V døevìný truhle.}
{145}{}{}
{146}{}{}
{147}{}{Myslíš tu, kterou máme zamèenou vzadu a se kterou si užíváme? Tak tu jsem nevidìl.}
{148}{}{Ty mít nemocnou hlavu. Vyvolený opravit to. Odstranit tu hlavu.}
{149}{}{Co ty myslel tím užívat si s tou holkou?}
{150}{}{Oh. Vyvolený už odejít.}
{151}{}{Ty jsi nemocnej, chudinko malá. Zazpívám ti ukolébavku. Zaruèenì tì uspí. Navìky.}
{152}{}{Fajn. Tak si to užijte a já zas pùjdu.}
{153}{}{Nechte to dìvèe na pokoji a budete žít.}
{154}{}{Takže ty ses vrátil. No, vyzkoušíme, kdo z nás to pøežije.}
{155}{}{Zabili jsme tu dìvku Chrissy, a teï jsi na øadì ty!}
