#tento soubor pøeložil Raptor...xraptor.@email.cz
{100}{}{Vidíš starší ženu.}
{101}{}{Vidíš Rebeccu.}
{102}{}{Vidíš starší ženu. I když vypadá, že mìla tìžký život, neubralo jí to na jejím pøirozeném pùvabu.}
{103}{}{Ahoj, já jsem Rebecca. Mùžeme si promluvit nìkde v soukromí, prosím?}
{104}{}{Mluvit o èem?}
{105}{}{Proè chtít mluvit v soukromí?}
{106}{}{Oukej.}
{107}{}{Ne. Odcházím.}
{108}{}{Promiò, nemám zájem.}
{109}{}{O èem to chceš se mnou mluvit?}
{110}{}{Jistì. Kde mùžeme mít soukromí?}
{111}{}{Proè je potøeba to soukromí?}
{112}{}{(šeptá) Moje dcera se ztratila a já potøebuji pomoc. Tady o tom nemùžu mluvit. Mùžeme jít nìkam stranou?}
{113}{}{OK.}
{114}{}{Proè potøebuješ mluvit v soukromí?}
{115}{}{Ne, už musím.}
{116}{}{V poøádku, pojïme.}
{117}{}{Proè chtít mluvit v soukromí?}
{118}{}{Dìkuju, ne. Nechci se do nièeho zaplést.}
{119}{}{(šeptá) Možná si o mnì budeš myslet, že jsem blázen, ale mám takový pocit, že mì poøád sledují. Je to znepokojující a já jsem z toho nervózní.}
{120}{}{OK, my jít nìkam jinam.}
{121}{}{Nemít èas nemocné s hlavou.}
{122}{}{V poøádku. Kde si mùžeme v klidu promluvit?}
{123}{}{Promiò, ale tohle se mi nìjak nelíbí.}
{124}{}{Díky. Mùžeme jít do mého stanu.}
{125}{}{OK.}
{126}{}{Tady snad mùžeme nerušenì mluvit.}
{127}{}{OK, tak v èem je problém?}
{128}{}{Vyvolený mít nejdøív pár otázek.}
{129}{}{OK, tak co je to ta veledùležitá vìc?}
{130}{}{Nejdøív se chci na pár vìcí zeptat.}
{131}{}{Mám dceru, jmenuje se Chrissy. Je to trochu uliènice. Ráda se toulá, objevuje nové vìci a všude strká nos. Ale jinak je to hodné dítì, opravdu. Nejsou s ní problémy, vrací se domù vèas a i jinak se chová jako zodpovìdná dívka. Minulý týden se ale Chrissy nevrátila domù. Vyptávala jsem se všude kolem, ale nikdo jí nevidìl, ani o ní neslyšel. Zkoušela jsem jí hledat sama, ale Zeke, on je tu... nìco jako náš vùdce, mì nenechal. Øekl, že pro mnì není bezpeèné, abych venku pátrala na vlastní pìst a že pošle nìkolik mužù. Ale oni jí nenašli a øíkají, že ji možná chytili otrokáøi.}
{132}{}{Ne, nechtít se zaplést.}
{133}{}{Potøebovat si to rozmyslet.}
{134}{}{OK, vyvolený být tvùj hrdina.}
{135}{}{Promiò, nemám zájem.}
{136}{}{Musím si to rozmyslet.}
{137}{}{Dobøe, Rebecco. Pokusím se ti pomoci.}
{138}{}{A když ti pomùžu, co z toho budu mít?}
{139}{}{Co chceš vìdìt?}
{140}{}{Co se tady dìje?}
{141}{}{Kdo šéf?}
{142}{}{Vyvolený hledat Vault 13. Víš, kde je?}
{143}{}{Mluv o Vaultu.}
{144}{}{Mluv o Darion.}
{145}{}{Díky. My mluvit, ty mít problém?}
{146}{}{Co se to tu dìje?}
{147}{}{Kdo to tady vede?}
{148}{}{Hledám Vault 13. Víš, o nìm nìco?}
{149}{}{Øekni mi nìco o Vaultu.}
{150}{}{Tak mi povìz o Darionovi.}
{151}{}{Dìkuji ti, Rebecco. A teï si promluvíme o tvém problému.}
{152}{}{Øíkáme tomuhle místu 'Squat', protože bylo osídleno bezdomovci z mnoha mìst. Není nic moc, ale je to všechno co máme. Na západ odsud leží mìsto, které se jmenuje NCR. Vìdí o nás už dlouhou dobu, ale nikdy nám nenabídli žádnou pomoc. A teï si najednou nárokují tohle místo, prohlašují, že je to jejich dávný domov, a chtìjí ho zpìt.}
{153}{}{OK.}
{154}{}{Co tu chtìjí?}
{155}{}{Rozumím.}
{156}{}{Co je tady tak dùležitého, že to chtìjí?}
{157}{}{No... je tady starý Vault. Myslím, že je to èíslo 15. Chtìjí ho vydrancovat a ukrást odtamtud všechny staré technologie, které tam stále ještì mùžou být.}
{158}{}{Aha. Rozumím.}
{159}{}{Já vìdìl, že tu musí být ještì nìco jinýho než jen pár hladových otrapù.}
{160}{}{Rozumím.}
{161}{}{Tím se hodnì vysvìtluje. Moc jsi mi pomohla. Ale potøebuju znát odpovìï ještì na pár otázek.}
{162}{}{To by mohl být Zeke. On to tady všechno vede. Mùžeš ho najít v tamté budovì. ::ukazuje na severo-východ::}
{163}{}{Díky. Další otázky.}
{164}{}{Díky. Potøebuju se tì ještì na pár vìcí zeptat.}
{165}{}{Promiò, ale nic mì nenapadá. Mùžu se na to zeptat v NCR. Poslední dobou projevují o tenhle Vault velký zájem.}
{166}{}{OK, Vyvolený udìlat to.}
{167}{}{V poøádku, jdu na to.}
{168}{}{Dobrá... nemáme o tom sice s nikým mluvit, ale protože potøebuji tvou pomoc... Darion opravuje Vault. On je náš dobrodinec. Jakmile bude Vault plnì funkèní, nastìhujeme se dovnitø a koneènì budeme v bezpeèí pøed bandity a otrokáøi. Hned jakmile budou v poøádku systémy na výrobu jídla a vody.}
{169}{}{Rozumìt. Chtít vìdìt víc.}
{170}{}{Potøebuji vìdìt víc.}
{171}{}{Už není co øíct, opravdu. Darion nikdy neopouští Vault. Jestliže nám chce nìco øíct, vzkáže to po Zekeovi. Potkala jsem ho jen jednou, a vypadal jako hodný chlapík.}
{172}{}{OK.}
{173}{}{Hodní chlapci moc dlouho nepøežijí. A jakto, že on to tu vede?}
{174}{}{Rozumím.}
{175}{}{To je OK. Moc jsi mi pomohla.}
{176}{}{Nemám nic, co bych ti dala. Jen svùj vdìk.}
{177}{}{To je víc než dost. Pomùžu ti.}
{178}{}{Na to, aby sis koupila mojí pomoc, budeš potøebovat trochu víc.}
{179}{}{Do pekel, pomùžu ti.}
{180}{}{Mnohokrát ti dìkuji. Nikdy ti za to nepøestanu být vdìèná. Poèkám tady, dokud jí nepøivedeš... Hej, nìkdo nás venku poslouchal! Vidìla jsem jeho stín na stìnì stanu. Teï utíká tamtudy! ::ukazuje na severo-východ:: Musel to všechno slyšet!}
{181}{}{Já zùstat, nikam nejít!}
{182}{}{Ty nebát se, Vyvolený tvou dceru najít.}
{183}{}{Jejda.}
{184}{}{Zkusím ho dohonit.}
{185}{}{To mì neodradí. Já tvojí dceru najdu.}
{186}{}{No dobøe. Sakra.}
{187}{}{Prosím, odejdi.}
{188}{}{Už to máš promyšlené?}
{189}{}{Já se na nìco zeptat.}
{190}{}{Ne, stále pøemýšlet.}
{191}{}{Ne, stále to zvažuji.}
{192}{}{Chci se tì na pár vìcí zeptat.}
{193}{}{Rozmyslel sis to? Pomùžeš mi?}
{194}{}{Promiò, ale ne.}
{195}{}{Pomùžu.}
{196}{}{Ano, pomùžu ti.}
{197}{}{Ty musíš být ten èlovìk, který mi zachránil dceru. Nikdy ti za to nepøestanu být vdìèná. Dìkuji ti. Prosím, poèkej chvíli, promluvím si s Chrissy, a potom bych ráda mluvila s tebou.}
{198}{}{Zachránil jsi mi dceru. Nikdy ti za to nepøestanu být vdìèná. Dìkuji ti. Prosím, poèkej chvíli, promluvím si s Chrissy, a potom bych ráda mluvila s tebou.}
{199}{}{OK.}
{200}{}{Moje dcera mi všechno øekla. Tìžko uvìøit, že Darion je takové monstrum, po tom všem, co pro nás udìlal. A to pomyšlení, že jsme mu pomáhali krýt ty jeho loupeže. Slibuji ti, že to tak nezùstane. Mluvila jsem se Zekem a on tì chce vidìt. Mìl bys za ním zajít.}
{201}{}{Tìžko uvìøit, že Darion je takové monstrum, po tom všem, co pro nás udìlal. A to že my jsme mu pomáhali krýt ty jeho loupeže. Slibuju ti, že je s tím konec. Promluvím si se Zekem a všechno mu vysvìtlím. Urèitì tì taky bude chtít vidìt. Mìl by ses za ním pak zastavit.}
{202}{}{Dìkuju ti.}
{203}{}{Doufám, že Chrissy brzy najdeš.}
{204}{}{Hledám.}
{205}{}{Pokraèuju v pátrání.}
{206}{}{Díky za všechno, co jsi pro mnì udìlal.}
{207}{}{Neumím vysvìtlit proè, ale myslím si, že otrokáøi jí neunesli. Mám takový pocit, že je za tím nìco jiného. Ten pocit mám od té doby, co jsem o Chrissy mluvila se Zekem. Potøebuji nìkoho, kdo mi jí pomùže vypátrat. Pomùžeš mi, prosím?}
{208}{}{Poøád sem posílají lidi, kteøí nás pøesvìdèují, abychom odsud odešli. Ale oni nechápou, že nemáme kam jinam jít. Jinde nedokážeme pøežít.}
{209}{}{Víš, je docela legraèní, že ve Vaultu už prý opravili kdeco, ale ne svìtla. To zatracené místo je poøád ještì osvìtleno pochodnìmi. A Darion nechce, aby nìkdo vìdìl, co se dole ve Vaultu dìje. Bojí, že kdyby na to nìkdo pøišel, tak nám všechno seberou. A tak nám øekl, abychom se nebavili s nikým novým, kdo se tu objeví -- hlavnì s nikým z NCR.}
