#tento soubor pøeložil Raptor...xraptor.@email.cz
{100}{}{Vidíš bezdomovce.}
{101}{}{Vidíš Robertu, bezdomovce.}
{102}{}{Vidíš ženu støedního vìku ve starých obnošených šatech.}
{103}{}{Oh mùj Bože. Promiò, ale nemám ti co øíct. Odejdi prosím.}
{104}{}{Prosím jdi pryè. Nechci být vyrušována.}
{105}{}{Díky za pomoc Rebecce. Spletla jsem se v tobì. Omlouvám se.}
{106}{}{Nejsem pro tebe hrozba. Nezabíjej mì.}