#tento soubor pøeložil Raptor...xraptor.@email.cz
{100}{}{Vidíš bezdomovce.}
{101}{}{Vidíš Sáru, bezdomovce.}
{102}{}{Vidíš ženu støedního vìku ve starých obnošených šatech.}
{103}{}{Prosím, neobtìžuj mì; mám teï práci.}
{104}{}{Prosím odejdi. Tady pro tebe nic není.}
{105}{}{Diky za to, že jsi pomohl Rebecce. To od tebe bylo moc ušlechtilé, cizinèe.}
{106}{}{Nic jsem ti neudìlala. Prosím, nezabíjej mì.}
