#tento soubor pøeloil Raptor...xraptor.@email.cz
{100}{}{Vidíš postaršího bezdomovce.}
{101}{}{Vidíš Zekea, bezdomovce.}
{102}{}{Vidíš staršího mue s bílımi proøídlımi vlasy.}
{103}{}{Jmenuji se Zeke, cizinèe. Promiò, ale nemám teï èas se s tebou bavit -- a nemyslím si, e by v tomhle mìstì bylo pro tebe cokoliv zajímavého. Mìl bys odejít.}
{104}{}{Uh, oukej.}
{105}{}{Mít otázky.}
{106}{}{V poøádku. Já vypadnu.}
{107}{}{Chci ti jen poloit pár otázek.}
{108}{}{A já myslím, e brzy zjistíš, e u nám došly odpovìdi. Proè se nevrátíš, a dostaneme další zásilku?}
{109}{}{Hotovo.}
{110}{}{Vítej zpìt. Stále pro tebe nemám ádnou odpovìï, cizinèe. Proè nedáš na mou radu a nepøestaneš tu ztrácet svùj èas?}
{111}{}{OK.}
{112}{}{Rebecca mi øekla, co jsi pro ní udìlal. Chci se ti omluvit za to, jak jsme se k tobì chovali. Nezaslouíš si to. Jak ti tedy mohu pomoci?}
{113}{}{Mít otázky.}
{114}{}{Nic. Já jít.}
{115}{}{Mám na tebe pár otázek.}
{116}{}{Zatím nic, díky.}
{117}{}{Co chceš vìdìt?}
{118}{}{Darion bıt tvùj šéf?}
{119}{}{Co ty mít s bandity?}
{120}{}{Kde dveøe do Vaultu?}
{121}{}{Co se tu dít?}
{122}{}{Já jít.}
{123}{}{Pracuješ pro Dariona?}
{124}{}{Co chcete dìlat s tìmi lupièi?}
{125}{}{Kde je vstup do Vaultu?}
{126}{}{Dìje se tu nìco, co bych mìl vìdìt?}
{127}{}{Myslím, e to tak je. U pùjdu.}
{128}{}{Ano. Jsem spojka mezi ním a zdejšími lidmi. A nejsem z toho zvláš šastnı, speciálnì teï kdy vím, co je zaè.}
{129}{}{OK.}
{130}{}{Rozumím.}
{131}{}{Nic. Mají zbranì, kontrolují zásoby vody i jídla. To znamená, e jsou ve vıhodì. Nejsme bez nìj nic. Jak se proti nìmu mùeme obrátit? ijeme z jeho milosti.}
{132}{}{Hmm. Já myslet, e rozumìt.}
{133}{}{Hmm. Rozumím.}
{134}{}{Je tamhle za tìmi dveømi, ale je to zamèeno z druhé strany a je tam i past. Nemám ponìtí, jak se to otevírá... Ale poèkej chvilku. Pøed èasem jsem našel tuhle kartu a nevím, k èemu je. Rebecca mi øekla, e jsi našel nìjaké dveøe nedaleko místa, kde dreli Chrissy. Moná, e tahle karta je otevøe. Vezmi si ji.}
{135}{}{Vyvolenı ti dìkovat.}
{136}{}{Díky. Zkusím to.}
{137}{}{Na západ odsud je mìsto zvané NCR. Uplatòují na Vault 15 nárok, e prı je to jejich dávnı domov, a chtìjí ho zpìt. Posílali sem lidi, kteøí nás mìli pøesvìdèit, abychom odsud odtáhli, ale my jsme na to nepøistoupili. Tohle je ten jedinı domov, kterı máme.}
{138}{}{A proè ne vy s NCR jednat?}
{139}{}{A nepøemıšleli jste o vzájemné dohodì s NCR?}
{140}{}{To je tìká vìc. Co máš pøesnì na mysli?}
{141}{}{Pøipojit se ke kmenu NCR. Uèit se od jeho Starších. Povolit NCR pøístup do Vaultu. Pak všichni spokojení.}
{142}{}{Staòte se obèany NCR, nechte je, a tohle území pøipojí ke své republice a povolte jim pøístup do Vaultu. A oni vás na oplátku nauèí, jak samostatnì pøeít, a poskytnou vám svou ochranu.}
{143}{}{To nezní špatnì... Líbí se mi to. Kdy to dokáeš s NCR domluvit, budeme ti moc zavázáni. Ale... taky by se nìkdo mìl postarat o Dariona a jeho kamarády. A mìlo by se to udìlat hned, døív ne zjistí, co se stalo a pøipraví se na útok. A proè to s Darionem neskoncovat teï hned? Budeš mít na své stranì moment pøekvapení.}
{144}{}{Ty mít pravdu. Vyvolenı to zaøídit.}
{145}{}{Nebıt si jistı.}
{146}{}{Jo, to by se asi mìlo udìlat.}
{147}{}{Ty si mi dobrej. Nìjak ti nevím.}
{148}{}{Excelentní. Mnoho štìstí a díky.}
{149}{}{OK.}
{150}{}{No popøemıšlej o tom, ale pochop -- dokud je tu Darion, nemám na vıbìr. Musím všechno udrovat tak jak to je. Je to kvùli bezpeènosti nás všech. To znamená ádnou dohodu a ty jsi stále persona non grata. Rozumíš?}
{151}{}{Oukej.}
{152}{}{Ahoj. Stále èekám na koneèné vyøešení našeho problému. Jinımi slovy, nakopej Darionovi prdel!}
{153}{}{OK.}
{154}{}{Tys to dokázal pøíteli! U nejsme pod Darionovım bièem. Díky ti! Jsem teï pøipraven jednat s NCR. Staèí, aby sem poslali nìkterého ze svıch lidí, a uzavøeme s nimi dohodu.}
{155}{}{OK.}
{156}{}{Díky za šanci k novému ivotu. Jsme tvımi dluníky.}
{157}{}{Odejdi. Nemám ti co øíct.}
{158}{}{Ještì poèkej ne pùjdeš... Našel jsem tuhle kartu, a nevím k èemu je. Rebecca øíkala, e jsi našel nìjaké dveøe nedaleko od místa, kde dreli Chrissy. Moná, e je tahle karta otevøe. Tady, vezmi si ji.}
{159}{}{Díky.}
{160}{}{S èím ti mohu pomoci?}
{161}{}{Jen ty problémy s NCR, ale myslím e dohoda, kterou jsi navrhl, to vyøeší.}
{162}{}{Tys to dokázal pøíteli! U nejsme pod Darionovım bièem. Díky!}
{163}{}{Teï kdy je Darion pryè, nemáme jak získat jídlo. Urèitì všichni zahyneme! Mockrát díky.}
