#tento soubor pøeložil Raptor...xraptor.@email.cz
{100}{}{Vidíš poèítaèový terminál.}
{101}{}{Vidíš terminál energetického zdroje.}
{102}{}{Vidíš standardní poèítaèový terminál. Zdá se být funkèní a pøipraven pro zadání vstupních dat.}
{103}{}{Tenhle terminál kontroluje generátor. Ukazuje, že všechno bìží normálnì.}
{104}{}{Tenhle terminál kontroluje generátor. Ukazuje, že zdroj je mimo provoz v dùsledku nefunkènosti nìjaké jeho èásti.}
{105}{}{OK.}
