#tento soubor pøeložil Raptor...xraptor.@email.cz
{100}{}{Vidíš poèítaèový terminál.}
{101}{}{Vidíš bezpeènostní poèítaèový terminál.}
{102}{}{Vidíš standardní poèítaèový terminál. Zdá se být funkèní a pøipraven pro zadání vstupních dat.}
{103}{}{Tenhle terminál monitoruje èinnost generátoru silového pole. Ukazuje, ze všechno funguje normálnì.}
{104}{}{Tenhle terminál monitoruje èinnost generátoru silového pole. Ukazuje, ze jednotka je mimo provoz v dùsledku nedostatku energie.}
{105}{}{Vypnout silové pole.}
{106}{}{Zapnout silové pole.}
{107}{}{OK.}
{108}{}{Dal jsi pøíkaz k deaktivaci silového pole.}
{109}{}{Nedokážeš proniknout pøes bezpeènostní kódy, abys mohl deaktivovat silové pole.}
{110}{}{OK.}
{111}{}{Dal jsi pøíkaz k aktivaci silového pole.}
{112}{}{Nedokážeš proniknout pøes bezpeènostní kódy, abys mohl aktivovat silové pole.}
{113}{}{Hotovo.}
{114}{}{Tenhle terminál monitoruje èinnost generátoru silového pole. Ukazuje, ze silové pole je vypnuté.}
{115}{}{Tenhle terminál monitoruje èinnost generátoru silového pole. Ukazuje, ze silové pole je doèasnì vypnuto.}
{116}{}{Tenhle terminál monitoruje èinnost generátoru silového pole. Ukazuje, ze silové pole bylo zrušeno.}
