#tento soubor pøeložil Raptor...xraptor.@email.cz
{100}{}{Vidíš poèítaèový terminál.}
{101}{}{Vidíš terminál kontrolního centra.}
{102}{}{Vidíš standardní poèítaèový terminál. Zdá se být funkèní a pøipraven pro zadání vstupních dat.}
{103}{}{Terminál indikuje, že bezpeènostní silové pole na vstupu Vaultu bylo po obnovení dodávky energie aktivováno.}
{104}{}{Terminál indikuje, že všechny bezpeènostní systémy Vaultu jsou mimo provoz v dùsledku nedostatku energie.}
{105}{}{Vypnout silové pole.}
{106}{}{Zapnout silové pole.}
{107}{}{OK.}
{108}{}{Dal jsi pøíkaz k deaktivaci silového pole.}
{109}{}{OK.}
{110}{}{Dal jsi pøíkaz k aktivování silového pole.}
{111}{}{OK.}
{112}{}{Terminál indikuje, že silové pole bylo vypnuto ruènì.}
{113}{}{Terminál indikuje, že silové pole bylo zrušeno.}
{114}{}{Terminál indikuje, že silové pole je vypnuto.}