#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
#############################################################
#  Message File: Door.msg                                   #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the information      #
#           concerning doors in a locked state, trapped     #
#           state, locked and trapped state.                #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#       April 19,1998 nbk: added message line to be used    #
#                          for doors opened with keys.      #
#                                                           #
#  Created: September 26, 1997                              #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for description of the door. The #
#  first lines, line 100-1, are for the look_at_proc. The   #
#  remainder until the next block are for description_proc  #
#  based one skill and perception success.                  #
#############################################################

# look_at_proc
{100}{}{Vidíš døevìné dveøe.}
{101}{}{Vidíš železné dveøe.}

# description_proc

# Perception Check Critical Success
{102}{}{Vidíš pevné dveøe se zámkem, odemykatelným pomocí paklíèù, a s vysoce výbušnou pastí umístìnou na zárubni dveøí, kterou se mùžeš pokusit odstranit.}
{103}{}{Vidíš pevné dveøe se zámkem a vysoce výbušnou pastí umístìnou na zárubni dveøí, kterou se mùžeš pokusit odstranit.}
{104}{}{Vidíš pevné dveøe bez zjevného zamykacího zaøízení a vysoce výbušnou pastí umístìnou na zárubni dveøí, kterou se mùžeš pokusit odstranit.}
{105}{}{Vidíš pevné dveøe se starým, rezavým zámkem a vysoce výbušnou pastí umístìnou na zárubni dveøí, kterou se mùžeš pokusit odstranit.}

{106}{}{Vidíš pevné dveøe se zámkem (mùže být odemèen pomocí paklíèù) a pastí umístìnou na zárubni dveøí, kterou se mùžeš pokusit odstranit.}
{107}{}{Vidíš pevné dveøe se zámkem a pastí umístìnou na zárubni dveøí, kterou se mùžeš pokusit odstranit.}
{108}{}{Vidíš pevné dveøe bez zjevného zamykacího zaøízení a pastí umístìnou na zárubni dveøí, kterou se mùžeš pokusit odstranit.}
{109}{}{Vidíš pevné dveøe se starým, rezavým zámkem a pastí umístìnou na zárubni dveøí, kterou se mùžeš pokusit odstranit.}

{110}{}{Vidíš pevné dveøe se zámkem, odemykatelným sadou paklíèù, a kousek drátku, jenž èouhá ze zárubnì dveøí. Mùžeš se pokusit je vypáèit.}
{111}{}{Vidíš pevné dveøe se zámkem a kousek drátku, jenž èouhá ze zárubnì dveøí. Mùžeš se pokusit je vypáèit.}
{112}{}{Vidíš pevné dveøe bez zjevného zamykacího zaøízení a kousek drátku, jenž èouhá ze zárubnì dveøí. Mùžeš se pokusit je vypáèit.}
{113}{}{Vidíš pevné dveøe se starým, rezavým zámkem a kousek drátku, jenž èouhá ze zárubnì dveøí. Mùžeš se pokusit je vypáèit.}

{114}{}{Vidíš pevné dveøe se zámkem (odemykatelným sadou paklíèù), které se mùžeš pokusit vypáèit.}
{115}{}{Vidíš pevné dveøe se zámkem, které se mùžeš pokusit vypáèit.}
{116}{}{Vidíš pevné dveøe bez zjevného zamykacího zaøízení, které se mùžeš pokusit vypáèit.}
{117}{}{Vidíš pevné dveøe se starým, rezavým zámkem, které se mùžeš pokusit vypáèit.}

# Perception Check Success

{118}{}{Vidíš pevné dveøe se zámkem, odemykatelným pomocí paklíèù, a vysoce výbušnou pastí umístìnou na zárubni dveøí.}
{119}{}{Vidíš pevné dveøe se zámkem a vysoce výbušnou pastí umístìnou na zárubni dveøí.}
{120}{}{Vidíš pevné dveøe bez zjevného zamykacího zaøízení a vysoce výbušnou pastí umístìnou na zárubni dveøí.}
{121}{}{Vidíš pevné dveøe se starým, rezavým zámkem a vysoce výbušnou pastí umístìnou na zárubni dveøí.}

{122}{}{Vidíš pevné dveøe se zámkem (odemykatelným sadou paklíèù) a pastí umístìnou na zárubni dveøí.}
{123}{}{Vidíš pevné dveøe se zámkem a pastí umístìnou na zárubni dveøí.}
{124}{}{Vidíš pevné dveøe bez zjevného zamykacího zaøízení a pastí umístìnou na zárubni dveøí.}
{125}{}{Vidíš pevné dveøe se starým a rezavým zámkem a pastí umístìnou na zárubni dveøí.}

{126}{}{Vidíš pevné dveøe se zámkem (odemykatelné pomocí paklíèù) a kousek drátku, jenž èouhá ze zárubnì dveøí.}
{127}{}{Vidíš pevné dveøe se zámkem a kousek drátku, jenž èouhá ze zárubnì dveøí.}
{128}{}{Vidíš pevné dveøe bez zjevného zamykacího zaøízení a kousek drátku, jenž èouhá ze zárubnì dveøí.}
{129}{}{Vidíš pevné dveøe se starým, rezavým zámkem a kousek drátku, jenž èouhá ze zárubnì dveøí.}

{130}{}{Vidíš pevné dveøe se zámkem, které mùžeš odemknout pomocí paklíèù.}
{131}{}{Vidíš pevné dveøe se zámkem.}
{132}{}{Vidíš pevné dveøe bez zjevného odemykacího zaøízení.}
{133}{}{Vidíš pevné dveøe se starým, rezavým zámkem.}

# Perception Check Critical Failure

{134}{}{Vidíš ponièené dveøe se zámkem, které mùžeš odemknout pomocí paklíèù, a vysoce výbušnou pastí umístìnou na zárubni dveøí.}
{135}{}{Vidíš ponièené dveøe se zámkem a vysoce výbušnou pastí umístìnou na zárubni dveøí.}
{136}{}{Vidíš ponièené dveøe bez zjevného odemykacího zaøízení a vysoce výbušnou pastí umístìnou na zárubni dveøí.}
{137}{}{Vidíš ponièené dveøe se starým, rezavým zámkem a vysoce výbušnou pastí umístìnou na zárubni dveøí.}

{138}{}{Vidíš ponièené dveøe se zámkem, které mùžeš odemknout pomocí paklíèù, a pastí umístìnou na zárubni dveøí.}
{139}{}{Vidíš ponièené dveøe se zámkem a pastí umístìnou na zárubni dveøí.}
{140}{}{Vidíš ponièené dveøe bez zjevného odemykacího zaøízení a pastí umístìnou na zárubni dveøí.}
{141}{}{Vidíš ponièené dveøe se starým, rezavým zámkem a pastí umístìnou na zárubni dveøí.}

{142}{}{Vidíš ponièené dveøe se zámkem, které mùžeš odemknout pomocí paklíèù, a kousek drátku, jenž èouhá ze zárubnì dveøí.}
{143}{}{Vidíš ponièené dveøe se zámkem a kousek drátku, jenž èouhá ze zárubnì dveøí.}
{144}{}{Vidíš ponièené dveøe bez zjevného odemykacího zaøízení a kousek drátku, jenž èouhá ze zárubnì dveøí.}
{145}{}{Vidíš ponièené dveøe se starým, rezavým zámkem a kousek drátku, jenž èouhá ze zárubnì dveøí.}

{146}{}{Vidíš ponièené dveøe se zámkem, které mùžeš odemknout pomocí paklíèù.}
{147}{}{Vidíš ponièené dveøe se zámkem.}
{148}{}{Vidíš ponièené dveøe bez zjevného odemykacího zaøízení.}
{149}{}{Vidíš ponièené dveøe se starým, rezavým zámkem.}

# Perception Check Failure

{150}{}{Vidíš staré dveøe se zámkem, které mùžeš odemknout pomocí paklíèù, a vysoce výbušnou pastí umístìnou na zárubni dveøí.}
{151}{}{Vidíš staré dveøe se zámkem a vysoce výbušnou pastí umístìnou na zárubni dveøí.}
{152}{}{Vidíš staré dveøe bez zjevného odemykacího zaøízení a vysoce výbušnou pastí umístìnou na zárubni dveøí.}
{153}{}{Vidíš staré dveøe se starým, rezavým zámkem a vysoce výbušnou pastí umístìnou na zárubni dveøí.}

{154}{}{Vidíš staré dveøe se zámkem, které mùžeš odemknout pomocí paklíèù, a pastí umístìnou na zárubni dveøí.}
{155}{}{Vidíš staré dveøe se zámkem a pastí umístìnou na zárubni dveøí.}
{156}{}{Vidíš staré dveøe bez zjevného odemykacího zaøízení a pastí umístìnou na zárubni dveøí.}
{157}{}{Vidíš staré dveøe se starým, rezavým zámkem a pastí umístìnou na zárubni dveøí.}

{158}{}{Vidíš staré dveøe se zámkem, které mùžeš odemknout pomocí paklíèù, a kousek drátku, jenž èouhá ze zárubnì dveøí.}
{159}{}{Vidíš staré dveøe se zámkem a kousek drátku, jenž èouhá ze zárubnì dveøí.}
{160}{}{Vidíš staré dveøe bez zjevného odemykacího zaøízení a kousek drátku, jenž èouhá ze zárubnì dveøí.}
{161}{}{Vidíš staré dveøe se starým, rezavým zámkem a kousek drátku, jenž èouhá ze zárubnì dveøí.}

{162}{}{Vidíš staré dveøe se zámkem, které mùžeš odemknout pomocí paklíèù.}
{163}{}{Vidíš staré dveøe se zámkem.}
{164}{}{Vidíš staré dveøe bez zjevného odemykacího zaøízení.}
{165}{}{Vidíš staré dveøe se starým, rezavým zámkem.}

#############################################################
#  The following lines are for damage done to the player or #
#  critter who tried to open the door, or failed a traps    #
#  roll.                                                    #
#############################################################

# The following sets of lines are to be translated as:
# You set off the trap and were hit for [x] points of damage.
# NPC sets of the trap and was hit for [x] points of damage.

# Player sets off the trap
{166}{}{Zneškodnil jsi past a byl jsi zasažen za }
{167}{}{ bodù poškození.}

# NPC sets off the trap
{168}{}{ zneškodnil past a byl zasažen za }
{169}{}{ bodù poškození.}

#############################################################
#  The following lines are for when the player uses skills  #
#  on the door.                                             #
#############################################################

# Player uses a skill on the door
# Unlock Door
{170}{}{Úspìšnì odemykáš zámek na dveøích.}
{171}{}{Díky své nešikovnosti se zámek dveøí zasekl.}
{172}{}{Dveøe se ti nepovedlo odemknout.}

# Lock Door
{189}{}{Úspìšnì si zamkl dveøe.}
{190}{}{Dveøe se ti nepovedlo zamknout.}

# Find Trap on the Door
{194}{}{Našel jsi na dveøích past.}
{195}{}{Nepovedlo se ti najít past na tìchto dveøích.}

# Disarm the Trap on the Door
{196}{}{Zkušenì zneškodòuješ past na dveøích.}
{198}{}{Nepovedlo se ti zneškodnit past na dveøích.}

# NPC uses a skill on the door
# The following lines are appended with the NPC's name

# Unlock Door
{173}{}{ úspìšnì odemkl zámek dveøí.}
{174}{}{ nezkušenost zpùsobila zaseknutí zámku dveøí.}
{175}{}{ se nepovedlo dveøe zamknout.}

# Lock Door
{191}{}{ úspìšnì zamkl dveøe.}
{192}{}{ se nepovedlo dveøe zamknout.}

# Find Trap on the Door
{199}{}{ našel na dveøích past.}
{200}{}{ se nepovedlo najít na dveøích past.}

# Disarm the Trap on the Door
{201}{}{ zkušenì zneškodnil past na dveøích.}
{202}{}{ se nepovedlo zneškodnit past na dveøích.}

# Using a key on the door.
{400}{}{Odemkl jsi dveøe.}

#############################################################
#  The following lines are for when the player tries to     #
#  use items on the door which are not lockpicks.           #
#############################################################

# Player uses an item on the door
{176}{}{Vypáèil jsi zámek u dveøí.}
{177}{}{Když ses pokoušel vypáèit zámek, poranil sis záda, a to ti zpùsobilo jeden bod poškození.}

# The following set of lines is to be translated as:
# While trying to bust the lock, you strain your back and
# take [x] points of damage.

{178}{}{Když ses pokoušel vypáèit zámek, poranil sis záda, což ti zpùsobilo poškození za }
{179}{}{ bodù.}
{180}{}{Na to, abys vypáèil tento zámek, jsi pøíliš slabý.}

# NPC uses an item on the door
# The following lines are prepended by the NPC's name
{181}{}{ vypáèil zámek u dveøí.}
{182}{}{ si poranil záda, když se pokoušel vypáèit zámek, což mu zpùsobilo jeden bod poškození.}

# The following line set of lines is to be translated as:
# NPC strains his back while trying to bust the lock and
# takes [x] points of damage

{183}{}{ si poranil záda, když se pokoušel vypáèit zámek, což mu zpùsobilo poškození za }
{184}{}{ bodù.}

{185}{}{ je na vypáèení zámku pøíliš slabá.}
{186}{}{ si poranila záda, když se pokoušela vypáèit tento zámek, což jí zpùsobilo jeden bod poškození.}

# The following line set of lines is to be translated as:
# NPC strains her back while trying to bust the lock and
# takes [x] points of damage

{187}{}{ si poranila záda, když se pokoušela vypáèit tento zámek, zpùsobilo poškození za }
{188}{}{ bodù.}

#############################################################
#  Damage done to the door due to explosives.               #
#############################################################

{193}{}{Výbuch na tìch dveøích neudìlal ani škrábanec.}

#############################################################
#  Reporting Door Status should it be used.                 #
#############################################################

{203}{}{Dveøe se zdají být zamèené. Vypadá to, že tyhle jako klíè vyžadují nìjakou tenkou kartu.}
{204}{}{Slyšíš tiché praskání elektrických výbojù probíhajících dveømi.}

# NPC finds trap
# The following line is to be translated as:
# NPC notices a trap in the door jamb.

{205}{}{ oznamuje, že slyší tiché praskání elektrických výbojù probíhajících dveømi.}

#############################################################
#  Setting traps on a door and whether the door is open or  #
#  closed to set the trap.                                  #
#############################################################

# Player tries to set a trap on an open door
{206}{}{Na ty dveøe nejsi schopen umístit past, protože jsou otevøené.}

# NPC tries to set a trap on an open door
{207}{}{ není schopen na ty dveøe umístit past, protože jsou otevøené.}

# Player tries to set a trap on a closed door
{208}{}{Zkušenì jsi na rám dveøí umístil past.}
{209}{}{Nepovedlo se ti umístit past na rám dveøí.}

# NPC tries to set a trap on a closed door
{210}{}{ zkušenì umístil past na rám dveøí.}
{211}{}{ nedokázal umístit past rám dveøí.}

{300}{}{Odemkl jsi dveøe.}
{301}{}{Zamkl jsi dveøe.}
{302}{}{Dokud jsou ty dveøe otevøené nemùžeš je zamknout.}
{303}{}{Tenhle klíè do toho zámku nepasuje.}

# for broken doors
{320}{}{Neexistuje žádný zpùsob, jak zamknout tyhle dveøe.}

{500}{}{Neexistuje žádný zpùsob, jak zneškodnit past na tìchto dveøích.}
