#tento soubor pøeložil Somnambulus...somnambulus@hotmail.com
{100}{}{Generátor funguje normálnì. Výroba energie je na optimální úrovni.}
{101}{}{Generátor je v nouzovém pohotovostním režimu. Výroba energie je na technologickém minimu.}
{102}{}{Zkus zjistit, v èem je problém.}
{103}{}{No dobrá. Musíme jít.}
{104}{}{V systému musel kdysi nastat zkrat. Nouzový obvod vyhodil pojistky, ale ty se roztavily v blokovací poloze. Možná je mùžeš zkusit uvolnit, a obnovit tak dodávku proudu.}
{105}{}{Nedokážeš zjistit, co je špatnì. Prostì to jen nefunguje.}
{106}{}{Zkus to opravit.}
{107}{}{Èas vypadnout.}
{108}{}{Podaøilo se ti oèistit kontakty a obnovit dodávku energie!}
{109}{}{Zatracenì. Jde to hùø, než se na první pohled zdálo.}
{110}{}{OK.}
