#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš nìkoho ve vojenské uniformì.}
{101}{}{Vidíš nìkoho ve vojenské uniformì.}
{102}{}{Vidíš nìkoho ve vojenské uniformì, ale vypadá spíše jako technik než jako voják.}

{103}{}{Nazdar. Jak se vede?}
{104}{}{Rozumím a beru na vìdomí -- promiò, ale teï mì neruš. Mám tu nìco rozdìlaný.}
{105}{}{Teï s tebou nemùžu mluvit.}
{106}{}{Klidnì se podívej, ale nedotýkej se toho.}

{107}{}{Blázníš? Chodit tady bez uniformy... koukej se rychle pøevléct!}
{108}{}{Jestli tì seržant chytí bez uniformy, nakope ti prdel.}
{109}{}{Proè nemáš uniformu? }

{110}{}{Sakra! Byli jsme napadeni! Poplach!}
{111}{}{Vetøelci! Zavolejte stráže!}
{112}{}{Stráže! Vetøelci v navigaèním støedisku!}

{113}{}{Co se dìje? Byli jsme napadeni?}
{114}{}{Proè ten poplach? Co se stalo?}
{115}{}{Co se k èertu zase dìje?}