#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš technika.}
{101}{}{Vidíš technika z Enklávy.}
{102}{}{Vidíš nìkoho v laboratorním plášti. Vypadá spolehlivì a sebejistì.}

{103}{}{Ano, vojáku?}
{104}{}{Já tu být nový. Mít pár otázek.}
{105}{}{Jen tì zdravit. Už muset jít.}
{106}{}{Jsem tu nový a snažím se seznámit se základnou. Mùžu ti položit nìkolik otázek?}
{107}{}{Nashle. Uvidíme se pozdìji.}

{108}{}{Jistì. Pár minut mùžu obìtovat.}
{109}{}{S èím ti mùžu pomoci?}
{110}{}{Co být tohle za místo ?}
{111}{}{Co máš za práci?}
{112}{}{Kde základna Enklávy?}
{113}{}{Hledám plán pro vertibirda. Kde najít je?}
{117}{}{Vyvolený už jít.}
{118}{}{Co je tohle za místo?}
{119}{}{Jakou tady máš práci?}
{120}{}{Kde bych našel hlavní základnu Enklávy?}
{121}{}{Potøebuju se mrknout na plány vertibirdù. Kde bych je našel?}
{125}{}{No nic. Už musím jít.}

{126}{}{Tohle je øídící a navigaèní centrum vzdušné dopravy. Odtud mùžeme monitorovat a ovládat všechny pohyby vertibirdù.}
{127}{}{Aha. Ještì se zeptat.}
{128}{}{Rozumím. Ještì nìkolik otázek.}

{129}{}{Jsem poèítaèový technik první tøídy. Dohlížím na centrální poèítaè tam dole.}
{130}{}{Hmm... jasnì.}
{131}{}{Dobøe. Nenech se rušit.}

{132}{}{Nepøicházíš náhodou tam odtud?}
{133}{}{Eee... ne, Vyvolený pøijít ze severu.}
{134}{}{Ne to opravdu ne, já jsem ze severu.}

{135}{}{Aha... Ani jsem nevìdìl, že tam máme základnu. No naše hlavní báze je poblíž pobøeží kousek od San Francisco.}
{136}{}{Jak se tam dostat?}
{137}{}{Dobøe... a jak se tam mùžu dostat?}

{138}{}{Vertibirdem, samozøejmì. Jinak se to nedá, leda kdybys mìl loï. Na to abys tam doplaval, je to pøece jen moc daleko.}
{139}{}{Dík.}
{140}{}{Díky.}

{141}{}{Plány vertibirdu... Nevidím dùvod, proè bys o nich mìl nìco vìdìt. Ale zkus se zeptat vedle na údržbì.}
{142}{}{Oukej.}
{143}{}{Rozumím.}

{153}{}{Blázníš? Chodit tady bez uniformy... koukej se rychle pøevléct!}
{154}{}{Jestli tì seržant chytí bez uniformy, nakope ti prdel.}
{155}{}{Proè nemáš uniformu? }

{156}{}{Do prdele! Byli jsme napadeni! Poplach!}
{157}{}{Vetøelci! Zavolejte stráže!}
{158}{}{Stráže! Vetøelci v komunikaèním centru!}

{159}{}{Co se dìje? Jsme napadeni?}
{160}{}{Proè ten poplach? Co se stalo?}
{161}{}{Co se k èertu zase dìje?}

{162}{}{Jsem jen technik! Nestøílejte!}
{163}{}{Já nejsem voják, vyznám se jen v technice!}
{164}{}{Tohle je laboratorní oblek, ne brnìní! Já tu jen pracuju!}
