#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš kuchaøe.}
{101}{}{Vidíš Cookieho, kuchaøe.}
{102}{}{Vidíš mue s kuchaøskou èapkou a zástìrou.}

{103}{}{Ahoj vojáku. Hledáš nìco na zub nebo si chceš je pokecat?}
{104}{}{Vyvolenı chtít jídlo.}
{105}{}{Vyvolenı chtít mluvit.}
{106}{}{No nìco bych zdlábl.}
{107}{}{Na chvilku hodíme øeè.}

{108}{}{Mnooo, co bych ti tak dal. Mám tu ještì nìjakı "hovna na šindeli". A "sníh" a "mušince" si mùeš vzít tamhle. Ještì nìco?}
{109}{}{Co ty to chtít abych já jedl?}
{110}{}{Hovna? Sníh? Co je tohle do prdele za jídlo?}

{111}{}{Promiò, ty tu musíš bıt asi novej. Nièeho se nedìs, to je jen naše místní pøezdívka pro nìkterı jídla. "Hovno na šindeli" je smaenej biftek s toustem. A "sníh" a "mušince" jsou sùl a pepø.}
{112}{}{Ehe... dík. Budeme mluvit, a já jíst pøitom.}
{113}{}{Aha... jo, to je fakt srandovní. Pokecáme si u jídla.}

{114}{}{O èem si chceš pokecat?}
{115}{}{Jak to tu chodit?}
{116}{}{Kde plány vertibirdù?}
{118}{}{Kde hlavní základna?}
{119}{}{Vyvolenı muset do sluby. Díky.}
{120}{}{Tak jak tu chodí?}
{121}{}{Zajímám se o vertibirdy. Kdybych se chtìl podívat na jejich plány, kde bych je mohl najít?}
{123}{}{Kde se nachází hlavní základna Enklávy?}
{124}{}{Díky. Musím se vrátit zpátky do sluby.}

{125}{}{Zajímají tì nìjaké drby? Mùu ti øíct poslední novinky z údrby, z lékaøské laboratoøe nebo nìco o vojácích.}
{126}{}{Co chceš slyšet?}
{127}{}{A co ty øíct o údrbì?}
{128}{}{A co ty øíct o lékaøské laboratoøi?}
{129}{}{A co ty øíct o vojácích?}
{130}{}{Ještì nìco?}
{131}{}{U slyšet dost.}
{132}{}{Co se dìje na údrbì?}
{133}{}{Co mi mùeš øíct o té lékaøské laboratoøi?}
{134}{}{A co o nás vojácích?}
{135}{}{Stalo se ještì nìco dalšího?}
{136}{}{Myslím, e u jsem slyšel dost.}

{137}{}{Raul, mechanik vertibirdù, se nesnáší s Quincym, vedoucím údrby. Ti dva se vdycky pohádají. Ale nemyslím, e je to otázka profesionální rivality. Raul je prostì arogantní parchant, kdeto Quincy je správnı chlapík. Doufám, e to nakonec vyhraje.}
{138}{}{Oukej.}
{139}{}{Jo, to je zajímavá novinka.}

{140}{}{Lékaøskou laboratoø pøevzal nìjakej chlápek z hlavní báze, kterej se jmenuje Schreber. Je to pìknej zkurvysyn; nestará se o nic a o nikoho. Dìlá tam dole nìjaké experimenty na deathclawech, nevím pøesnì jakı. Ale byly tam odtud slyšet tak hroznı zvuky, e veliteli došla trpìlivost a naøídil tu místnost udìlat zvukotìsnou.}
{141}{}{Hmm, rozumìt.}
{142}{}{To je zajímavé. }

{143}{}{Haha! Máme tu románek, kámo. Vypadá to, e se jeden z tìch poèítaèovıch hòupù zabouchl do stráné co hlídá lékaøskou laboratoø. Dokonce jí dal takovou mazlivou pøezdívku. Øíká jí myslím "Snookie".}
{144}{}{To je roztomilı.}

{145}{}{No a to je asi tak všechno co se tu poslední dobou událo. Kdybych zaslechl nìco dalšího, tak ti dám vìdìt. Rád o tìchhle vìcech mluvím, stejnì jako si rád poslechnu nìco nového!}
{146}{}{Díky.}

{147}{}{Proè tì zrovna tohle zajímá? No dobøe, to je fuk. Myslím, e Quincy má nìjaké na údrbì. }
{148}{}{Oukej.}
{149}{}{Kde to je?}
{150}{}{Mrknu se tam.}
{151}{}{Kde to je?}

{152}{}{V severovıchodní èásti základny, kámo. Nemùeš to minout.}
{153}{}{Oukej. Díky ti moc.}

{156}{}{Pøekvapuje mì, e to nevíš, hádám, e ty musíš bıt z místního náboru. No naše hlavní základna je uprostøed toho zatracenıho oceánu. No moná, e ne pøímo uprostøed, ale na tom prd záleí. Jediná cesta jak se tam dostat, je buï na lodi nebo pomocí vertibirdu. Ale ta blbá loï je zablokovaná. Musel bys mít FOB, abys tu mrchu rozhejbal.}
{157}{}{FOB?}

{158}{}{Jo, to je nìco jako klíè. Velitel ho má ve svım kanclu. Bez nìj nemáš k nìkterım místùm na tankeru pøístup. Tak je loï chránìná pøed tím aby na citlivı místa lezli ty místní trhani ze San Francisca.}
{159}{}{Dobrej nápad.}
{160}{}{Kde je kanceláø velitele?}
{161}{}{To je dobrej nápad.}
{162}{}{A kde je kanceláø velitele?}

{163}{}{Sjeï vıtahem ve vedlejší místnosti, projdi chodbou a k hlavní køiovatce a pokraèuj rovnì.}
{164}{}{Díky.}

{165}{}{Nazdar, vojáku. Rád tì zase vidím. Chceš se najíst nebo zase pokecat?}
{166}{}{Jídlo.}
{167}{}{Pokec.}
{168}{}{Tak nazdar.}
{169}{}{Ani jedno, jenom tì chci pozdravit.}

{170}{}{Tady máš. Je to mrtvı, uvaøenı a nedá se to identifikovat. Hahaha. Dobrou chu.}
{171}{}{Joo... Díky.}

{172}{}{Synu, podle toho smradu soudím, e na sobì nemáš Energo brnìní. Jestli tì serant naèapá bez uniformy, tak to máš spoèítanı. Radši nebudu mluvit o tom, co by ti udìlal. Radím ti, zapadni dolù a vyfasuj si poøádnej vohoz.}
{173}{}{Sleèinko, podle tı tvı vùnì soudím, e na sobì nemáš Energo brnìní. Jestli tì serant naèapá bez uniformy, tak to máš spoèítanı. Radši nebudu mluvit o tom, co by ti udìlal. Radím ti zapadni dolù a vyfasuj si poøádnej vohoz.}
{174}{}{Kde to je?}
{175}{}{Oukej.}
{176}{}{Kde to je?}
{177}{}{Jo to radši udìlám.}

{178}{}{Sjeï vıtahem ve vedlejší místnosti, projdi chodbou a k hlavní køiovatce, dej se vlevo a jsou to první dveøe nalevo. A teï u jdi.}
{179}{}{Díky.}

{180}{}{Sakra! Sem jen kuchaø... tyhle vìci mì nezajímaj. Nikdy sem tudy ádnıho vetøelce projít nevidìl.}
{181}{}{Díky.}

{182}{}{Zatracenı alarmy. To je vdycky bengál, kdy se spustí.}
{183}{}{Proè se ta zatracená vìc zase spustila, ksakru?}
{184}{}{Hroznì bych si pøál, abychom pouívali tichı alarmy, z tìchhle zatracenejch vìcí mì vdycky hroznì bolí hlava.}

{185}{}{Usmaím si tvojí prdel a naservíruju ti jí na støíbrnım podnosu.}
{186}{}{Peèená husa pro váenıho hosta je hotová. Ha! Dìlal jsem si srandu!}
{187}{}{Pryè od hrncù a pánví a vzhùru do boje.}
