#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš technika.}
{101}{}{Vidíš poèítaèového technika.}
{102}{}{Vidíš nìkoho v laboratorním obleku s kapsou plnou propisek.}

{103}{}{Dobrı den vojáku.}
{104}{}{Prosím nedotıkej se nièeho.}
{105}{}{Ti tví kumpáni tu nemají co dìlat.}

{106}{}{Nemáš na sobì uniformu. }
{107}{}{Radìji by ses mìl pøevléct. Zbrojnice je dole. Nalevo v hale.}
{108}{}{Je tu velká šance, e tì vyhodí, kdy na sobì nemáš uniformu. Radši by sis jí mìl vyfasovat.}

{109}{}{Kdo k èertu jste chlapi... Poplach! Vetøelci!}
{110}{}{Byli jsme napadeni! Poplach!}
{111}{}{Nìkolik vetøelcù! Spuste alarm!}

{112}{}{Sakra! Rychle spuste zálohování.}
{113}{}{Ukonèete všechny probíhající operace.}
{114}{}{Spuste ochranu systému a aktivujte všechna ochranná hesla.}

{115}{}{Já jsem vìdec, ne voják!}
{116}{}{Zamiø tím svítícím koncem navádìcí diody na nepøítele. Pak zmáèkni kohoutek.}
{117}{}{Pomoc! Pomoc! Rychle do poèítaèového centra!}
