#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš vìdce.}
{101}{}{Vidíš doktora Schrebera.}
{102}{}{Vidíš plešatého mue v laboratorním obleku.}

{103}{}{Doufám, e máš zatracenì dobrı dùvod pøerušovat mojí práci, vojáku.}
{104}{}{Chci se ptát.}
{105}{}{Ne ještì ne. Vrátit se pozdìji.}

{106}{}{No dobøe. Kdy u tu musím s vámi vojáky ít, tak proè bych s tebou nemohl prohodit pár slov.}
{107}{}{Co chceš vìdìt?}
{108}{}{Kdo ty bıt?}
{109}{}{Co tu dìlat?}
{110}{}{Co bıt tohle za místo?}
{111}{}{Proè tahle místnost nedìlat ádnı zvuk?}
{112}{}{Proè ten deathclaw ve vedlejší místnosti?}
{113}{}{Proè se ten pejsek u dveøí nehıbat? Nedìlat nic?}
{114}{}{Muset jít.}
{115}{}{Kdo jste?}
{116}{}{Co tu dìláte?}
{117}{}{Co je tohle za místo?}
{118}{}{Proè je tahle místnost zvukotìsná?}
{119}{}{Proè je ve vedlejší místnosti ten deathclaw?}
{120}{}{Co je s tou sochou psa u dveøí?}
{121}{}{U musím jít.}

{122}{}{Jmenuji se Schreber. Doktor Schreber. Mezi jinımi jsem i lékaøem téhle základny. Se svım jménem se ani neobtìuj, vojáku. Vy pìšáci stejnì všichni vypadáte v tìch vašich brnìních úplnì stejnì.}
{123}{}{Oukej.}
{124}{}{Rozumím.}

{125}{}{Pracuju tu sice jako lékaø, ale to je jen bokovka. Ve skuteènosti jsem genetik.}
{126}{}{Co to je?}
{127}{}{Co to je genetik?}

{128}{}{Opravdu si nemyslím, e bys mohl se svojí inteligencí pochopit mojí práci, vojáku. No, øeknìme, e mùu 'vylepšovat' lidi nebo zvíøata.}
{129}{}{Joo... jasnì.}
{130}{}{Hmm... Chci se ještì na pár vìcí zeptat.}

{131}{}{Tohle døív bıvala laboratoø pro lékaøské úèely. Nicménì, cítil jsem, e mé experimenty mají pøednost pøed, beztak minimálními, vojenskımi potøebami, tak jsem to tady zmìnil v laboratoø pro své pokusy.}
{132}{}{Jak ... hezké.}
{133}{}{To je ušlechtilé. Tak mi prosím øeknìte ještì nìco.}

{134}{}{Proè tahle místnost nedìlat ádnı zvuk? Jo, ty myslíš zvukotìsnost! Provádìl jsem tu pár... experimentù. A obèas byly testovací subjekty bìhem mıch pokusù trochu hluènìjší. Velitel základny usoudil, e ty zvuky ruší chod základny a nechal tu instalovat zvukotìsné obloení.}
{135}{}{Provádìl jsem tu pár... experimentù. A obèas byly testovací subjekty bìhem mıch pokusù trochu hluènìjší. Velitel základny usoudil, e ty zvuky ruší chod základny a nechal tu instalovat zvukotìsné obloení.}
{136}{}{Aha...}
{137}{}{Ach tak.}

{138}{}{Ten velkı, hnìdı, a ohavnı? To je experiment, kterı jsem právì dokonèil. Je urèen k likvidaci.}
{139}{}{Jaké likvidaci?}
{140}{}{Proè ho chcete zabít?}

{141}{}{Mùj Boe... ty jsi jeden z tìch bystrejch co? Dokonèit. Zabít, oddìlat, poslat ho do vìènıch loviš, skonèit to s ním. Rozumíš?}
{142}{}{Hmm. Proè chcete zabít ten deathclaw?}

{143}{}{Enkláva hledá levné a snadno postradatelné vojenské síly. Zajímáme se o deathclawy, protoe jsou od pøírody docela dobøe vybaveni pøirozenım brnìním i zbranìmi a hlavnì jsou velice agresivní. Jen by potøebovali bıt trochu chytøejší aby lépe porozumìli rozkazùm. Ale zas aby nebyli natolik chytøí, e by mìli svojí vlastní vùli. Rozumíš?}
{144}{}{Jo... Jasnì.}
{145}{}{Jo. Rozumím vám moc dobøe.}

{146}{}{A uspìli jsme! Nakonec jsme dokázali vylepšit jejich inteligenci. Ale asi jsme zašli a moc daleko. Jsou asi mnohem chytøejší ne se nám doposud jevili. Take kdy jsem sem byl pøemístìn, vzal jsem si jednoho deathclawa s sebou abych si mohl vyzkoušet svojí teorii v praxi.}
{147}{}{A?}

{148}{}{Mìl jsem pravdu! Deathclawové si podle všeho hráli na blbce, èekali na svou pøíleitost a hlavnì se snaili od nás lidí nauèit co nejvíce. Dokonce jsou schopní nauèit se lidskou øeè! S tím tvorem ve vedlejší místnosti jsem sám mluvil.}
{149}{}{V kadém pøípadì u sám fakt, e jsou schopní sestavit takovıto plán a svojí inteligenci zámìrnì maskovat, ukazuje na jejich extrémní nebezpeènost.}
{150}{}{A co teï plánovat udìlat?}
{151}{}{A co teï plánujete udìlat?}

{152}{}{Právì se chystám sepsat hlášení o mıch objevech a musím ho neprodlenì poslat na hlavní bázi. A samozøejmì budu muset doporuèit kompletní likvidaci deathclawù. Jsou pøíliš velkou hrozbou.}
{153}{}{Rozumìt. Potøebovat se ještì na nìco zeptat.}
{154}{}{Jasnì... opravdu tahle místnost nic zvuk?}
{155}{}{Chtít pro tebe zabít toho deathclawa!}
{156}{}{Hele, mùu pro vás zabít toho deathclawa?}
{157}{}{Zajímavé. Mùu se zeptat ještì na nìco?}
{158}{}{Øeknìte mi doktore, jste si jist, e je tahle místnost zvukotìsná?}

{159}{}{Jistì, e sem si jist. Velitel to nechal udìlat. Proè tì to zajímá?}
{160}{}{Jen tak.}
{161}{}{Vyvolenı nechtít aby slyšet tvùj køik a on tì zabíjet!}
{162}{}{Jen ze zvìdavosti.}
{163}{}{Nechci, aby nìkdo slyšel vaše vıkøiky a budu na vás dìlat já ty svoje experimenty.}

{164}{}{Zase zpátky? Co pro tebe mùu udìlat tentokrát?}
{165}{}{Opravdu tahle místnost nic zvuk?}
{166}{}{Mít další otázky.}
{167}{}{Nic. Øíkat sbohem.}
{168}{}{Jste si jistı, e je tahle místnost zvukotìsná?}
{169}{}{Chtìl sem se vás ještì na nìco zeptat.}
{170}{}{Nic. Tak zase nìkdy nashle.}

{171}{}{Samozøejmì, e sem si jistej. Velitel to nechal dodìlat. Proè se ptáš ?}
{172}{}{Není dùvod.}
{173}{}{Nechci, aby nìkdo slyšel vaše vıkøiky, a vás budu zabíjet!}
{174}{}{Byl jsem jenom zvìdavı.}
{175}{}{Nechci, aby nìkdo slyšel vaše vıkøiky a budu na vás dìlat svoje experimenty.}

{176}{}{Máš monost. Je ve vedlejší místnosti.}
{177}{}{Díky!}

{178}{}{To je K-9, mùj pes. Rozhodl jsem se zjistit, jestli mùu kybernetickou cestou vylepšit jeho inteligenci. Fungovalo to, ale mìl nìjak špatnì vyvinutou morálku. Rozhodl se, e se mu nelíbím já ani moje práce a poøád mì kousal do nohy.}
{179}{}{Za trest jsem mu vypnul pohon nohou, ale jinak ho nechal plnì funkèního. Teï tam musí sedìt a dívat se na všechny ty vìci, co se mu tak hnusily.}
{180}{}{Ech...}
{181}{}{On dá se opravit?}
{182}{}{Aha.}
{183}{}{Dá se opravit?}

{184}{}{Ale jistì. Jen jsem mu vyndal obvod motivátoru a dal ho Raulovi z údrby. Vdycky se mùe zamontovat zpátky....moná to nìkdy udìlám, abych zjistil jestli vùèi mì zmìnil názor.}
{185}{}{Oukej.}
{186}{}{Rozumím.}

{187}{}{Ty jsi civilista?}
{188}{}{Tohle je lékaøská laboratoø. Zbrojnice je dole v hale nalevo.}
{189}{}{Proè nemáš uniformu?}

{190}{}{Do prdele! Byli jsme napadeni! Poplach!}
{191}{}{Vetøelci! Zavolejte stráe!}
{192}{}{Stráe! Vetøelci v lékaøské laboratoøi!}

{193}{}{Co je? Byli jsme napadeni?}
{194}{}{Proè ten poplach? Co se stalo?}
{195}{}{Co se to tu do hajzlu zase dìje?}

{196}{}{Já nejsem nepøítel, nezabíjej mì.}
{197}{}{Nejsem ádnı voják, tak mì nech bıt.}
{198}{}{Zatracenì! Já jsem doktor, ne voják!}

{200}{}{[Více]}
{201}{}{Chtìl sem se vás zeptat na nìkolik otázek.}
{202}{}{Teï ne. Promiòte, e jsemn vás obtìoval.}

{800}{}{Zabil jsi doktora Schrebera.}
