#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš postavu v kevlarovém brnìní.}
{101}{}{Vidíš strá u dveøí velitele.}
{102}{}{Vidíš nìkoho v kevlarovém brnìní. Na prsou má znak, kterı ti kupodivu vùbec nic neøíká.}

{103}{}{Vojíne! Co tu hledáte?}
{104}{}{Co je tohle za místo?}
{105}{}{Uh... já tu novı.}
{106}{}{Já tu uklidit.}
{107}{}{Vyvolenı si nepamatovat. Jít pryè.}
{108}{}{Co je tohle za místo?}
{109}{}{Ahoj, já sem tu novej.}
{110}{}{Jsem tady, abych uklidil velitelovu kanceláø.}
{111}{}{Ale nic.}

{112}{}{Tohle je kanceláø velitele základny. Do této místnosti smí vstoupit pouze autorizovanı personál. Musím vás poádat, abyste odešel, vojíne.}
{113}{}{Mít obchod s velitel.}
{114}{}{Fajn.}
{115}{}{Mám s velitelem nìjakı obchod.}
{116}{}{Provedu.}

{117}{}{Co je to za obchod, vojíne?}
{118}{}{Uh...}
{119}{}{Sakra. U mì to sere...}
{120}{}{Ale nic. Jít pryè}
{121}{}{No...}
{122}{}{Uh, dostali jsme hlášení z hlavní základny. Vypadá to, e mají starost o klíè k tankeru, bojí se, aby se nedostal do nesprávnıch rukou. Musíme ho nìkam zamknout.}
{123}{}{Odcházím.}

{124}{}{Vojíne, tohle je poslední varování. Musím vás poádat, abyste opustil tuto zónu.}
{125}{}{Oukej.}
{126}{}{Oh... Srát na tebe. Prostøílet si cestu dovnitø.}
{127}{}{Seru na tebe. kdy to nejde po dobrım, tak si cestu prostøílím.}

{128}{}{Co? Jo tak, u rozumím. Nìco jsi posral a tak ti Dornan pøidìlil rajóny.}
{129}{}{Jo... já neposlouchat... on se zlobit... a teï muset uklízet ee vìci!}

{130}{}{(mluví do mikrofonu) Dejte mi velitele. Je tu jenotka na úklid pane. (pauza) Rozumím. (dívá se na tebe) Tak to proveïte.}
{131}{}{Díky.}

{132}{}{(mluví do mikrofonu) Je zde bezpeènostní problém pane. Hlavní základna poaduje zabezpeèení karty k tankeru. (pauza) Rozumím pane. (dívá se na tebe) Tak to proveïte.}
{133}{}{Chci vidìt tvùj pøíkaz.}
{134}{}{Díky.}
{135}{}{Oh, nemám ho zrovna sebou.}

{136}{}{(potichu) Ty jsi musel zabloudit. Tohle je kanceláø velitele základny. Nikdo sem nesmí pokud pro nìj náš starej neposlal.}
{137}{}{Nikdo sem nechodit? Nikdy?}
{138}{}{Nikdo za ním nesmí?}

{139}{}{(potichu) Nikdo. Jen úklidová jednotka. Mìli by pøijít za hodinku nebo dvì. Pro všechny ostatní je tahle zóna zakázaná. A ty u radši taky vypadni.}
{140}{}{Oukej.}

{141}{}{mluví do mikrofonu) Dejte mi velitele. Je tu jednotka na úklid pane. (pauza) Rozumím. (dívá se na tebe) Tak to proveïte.}
{142}{}{Jsi tu moc brzo. Pøijï pozdìji.}
{143}{}{Oukej.}

{144}{}{Pak tedy jdi do velitelského centra a nech si tam vytisknout ten pøíkaz.}
{145}{}{Oukej.}

{146}{}{Ty urèitì hledáš zbrojní sklad. Jdi zpátky tou chodbou, odboè vpravo, a jsou to první dveøe nalevo. Tam vyfasuješ svojí vızbroj.}
{147}{}{Díky.}

{148}{}{Kdo k èertu jste chlapi... Poplach! Vetøelci!}
{149}{}{Byli jsme napadeni! Poplach!}
{150}{}{Vetøelci! Spuste alarm!}

{151}{}{Poplach! Braòte základnu!}
{152}{}{Zabezpeète všechny stanice! Máme poplach}
{153}{}{Poplach! Èervenı kód!}

{154}{}{My tì zlikvidujeme!}
{155}{}{Enkláva povládne svìtu!}
{156}{}{Ty chcípneš, Enkláva zvítìzí!}

{160}{}{Zase zpìt? Pøinesl sis ten pøíkaz ohlednì FOBu?}
{161}{}{Ne, ještì ne. Ale seenu ho.}

{162}{}{Jo, jasnì. Já jsem ti øekl, e do velitelovy kanceláøe mùe jen úklidová jednotka a ty ses jako zázrakem stal jedním z nich. Hele já tì moc dobøe sleduju. Myslíš si, e sem nìjakej zasranej blbec? Padej vodsud!}
