#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš strá. }
{101}{}{Vidíš strá u vchodu.}
{102}{}{Vidíš nìkoho v Enego zbroji nezvyklého vzhledu. Na prsou má znak, kterı ti nic neøíká.}

{103}{sgnt1a}{Vítej v táboøe Navarro... to je civil! Jak se k sakru mùe civilista dostat do tıhle základny! Asi si tu nìkoho pìknì podám! Vyhoïte toho civila z vládní zóny.}
{104}{sgnt1b}{Vítej v táboøe Navarro... to jsou civilové! Jak se k sakru mùou civilisti dostat do tıhle základny! Asi si tu nìkoho pìknì podám! Vyhoïte ty civily z vládní zóny.}
{105}{}{Poèkej. Já...}

{106}{sgnt2a}{Ale u zaèínám bejt nasranej. Nechal jsem tì vyhodit ze základny a ty jsi tu zase. Nemyslím si, e budeš jen tak obyèejnej civil. Spíše jsi špeh! Spuste alarm a sejmìte tohohle èerva!}
{107}{sgnt2b}{Ale u zaèínám bejt nasranej. Nechal jsem vás vyhodit ze základny a vy jste tu zase. Nemyslím si, e budete jen tak obyèejnı civilové. Spíše jste špehové! Spuste alarm a sejmìte ty èervy!}

{108}{sgnt3}{Vítej v táboøe Navarro. Take ty jsi ta posila, co nám slíbili. Jak se jmenuješ, vojíne?}
{109}{}{Uh... já }
{110}{}{Já jsem }

{111}{sgnt4}{No, vıbornì. Poslali mi sem debila. Poslouchej pozornì. Budeš mít strá u hangáru. To bude tvùj strání post. Teï tam pùjdeš a zùstaneš tam na strái, dokud ti neøeknu jinak. A teï hejbni svım zadkem, vojáku!}
{112}{}{Já jít.}

{113}{sgnt5}{Co to bylo? Nezapomnìl jsi na nìco, èerve?}
{114}{}{Jmenuji se }

{115}{sgnt6}{Nejsem ádnı pán. Budeš mi øíkat serante nebo serante Dornane. Rozumìls?! }
{116}{}{Ano serante!}
{117}{}{Jistì sero. Jasná páka.}

{118}{sgnt7}{Vıbornì. Teï pùjdeš k hangáru, kde vystøídáš strá a budeš mít slubu. A koukej sekat latinu. Pochopils to?}
{119}{}{Co tam budu hlídat, serante?}
{120}{}{Provedu serante!}

{121}{sgnt8}{Ty blbe, na moje pøíkazy se nebudeš ptát! Kdy ti øeknu "skoè", tak skoèíš! Kdy ti øeknu "bojuj", tak budeš bojovat! Kdy ti øeknu, abys umøel pro svou vlast, tak pro ni umøeš! Kapišto?}
{122}{}{Ano serante!}

{123}{sgnt9}{Vítej v táboøe Navarro. Take ty jsi ta posila, co nám slíbili... nemáš uniformu, vojáku! Kde máš svoje energo brnìní?}
{124}{}{Uh... nemít.}
{125}{}{Na základnì jsem ádnı nevyfasoval. Øekli mi, e ho dostanu tady.}
{126}{}{Uh... nedostal jsem ádnı.}
{127}{}{Ve vteøince ho budu mít... sundám si ho z tvıho mrtvého tìla!}

{128}{sgnt10}{Nemáš ádnı? Èekáš, e ti to seeru, èerve? Pravdou je, e jsi ztratil drahou èást vojenského vybavení. To brnìní ti budeme strhávat ze oldu a zùstaneš v armádì a dokud ti nebude 510 let. To je toti pøesnì ten poèet let za kterej budeš schopnej cenu Energo brnìní Mark II, které jsi ztratil, splatit! A teï se pøihlaš se ve zbrojním skladu, vyfasuj nové vybavení a pak se mi tu zase zahlásíš, vojíne! Odchod!}
{129}{}{Oukej. Jít si pro obleèení.}
{130}{}{Rozkaz serante!}

{131}{sgnt11}{Ty zasranı ouøadové! Jak mám k èertu øídit tuhle jednotku, kdy mì takhle okrádají o zásoby! Jdi do zbrojního skaldu a nafasuj tam nové vybavení. A pak se mi zase zahlásíš. Odchod!}
{132}{}{Oukej.}
{133}{}{Provedu serante!}

{134}{sgnt12}{Kdy se mi budeš líbit, mùeš mi klidnì øíkat Sero. Ale víš co? Nelíbíš se mi! Je ti to jasnı?}
{135}{}{Ano serante!}

{136}{sgnt13}{Vıbornì! Teï kdy jsi koneènì v uniformì, dám ti jedineènou pøíleitost. Zaèneme zase znovu, jako kdybych tu tvojí prdel nikdy nevidìl. Spokojen vojáku?}
{137}{}{Ano uh... serante!}
{138}{}{Ne! Vyvolenému to jedno. Nakopat tvou prdel.}
{139}{}{Ano, serante!}
{140}{}{Náš vzájemnej vztah je mi úplnì fuk. Zvláš teï, kdy mám na sobì tohle pìknı brnìní. Protoe teï ti mùu nakopat prdel.}

{141}{sgnt14a}{Vojíne poøád na sobì nemáš uniformu. Dal jsem ti pøímı rozkaz abys ses hlásil ve skladu a vyfasoval všechno potøebné vybavení. A teï mi zmiz z oèí a nevracej se dokud nebudeš vypadat jako voják!}
{142}{sgnt14b}{Tohle je u podruhé co jsi sem pøišel bez uniformy, vojáku. ádné potøetí u nebude!}
{143}{}{Oukej! Oukej! U jít.}
{144}{}{Sklapni. Vyvolenı bıt z tvıch øeèí unavenı.}
{145}{}{Rozkaz serante! U jdu.}
{146}{}{Já ti na to prdím. Na tohle nejsem stavìnej.}

{147}{sgnt15a}{Vojáku, co tu dìláš? Vra se zpátky na svùj post!}
{148}{sgnt15b}{De-bi-le. Jestli ještì jednou uvidím, e nejsi na svém místì, bude to nejsmutnìjší den tvıho krátkého ivota!}
{149}{sgnt15c}{Všechny nás svou blbostí ohrouješ. To teï skonèí.}

{150}{sgnt16}{Tato základna je pøísnì støeenım místem a tebe neznám. Uka mi svoje doklady vojáku.}
{151}{}{Nemít papíry teï u sebe.}
{152}{}{Vyvolenı nepotøebovat ádné papíry!}
{153}{}{Nemám ty papíry sebou. Mám je ve skøíòce.}
{154}{}{Doklady? S tìma tvıma papírama jsem si utøel prdel!}

{155}{sgnt17}{Špatná odpovìï, èerve. Svoje doklady musíš mít poøád u sebe a mìl bys to vìdìt!}
{156}{}{A do prdele...}

{157}{}{Zùstaò bdìlı, vojáku!}
{158}{}{Dobøe. Velmi dobøe. Jen tak dál!}
{159}{}{Jak vidím, všechno v poøádku. Zùstaò na svém místì.}
{160}{}{Jestli nìkoho z vás nachytám jak spí, buïte si jistí, e u se neprobudí!}

{161}{}{Dobøe! Našel jsi správnì svùj post!}
{162}{}{Zùstaò na svém místì, dokud nebudeš vystøídán, vojáku!}
{163}{}{Na svém postu a bdìlı. Vıbornì!}
{164}{}{Buï bdìlı, buï ostraitı a zùstaneš naivu!}

{165}{}{Poplach! Vetøelci na základnì!}
{166}{}{Stráe! Vetøelci!}
{167}{}{Kdo k èertu pustil tyhle bastardy dovnitø? Stráe!}
{168}{}{Poplach! Špiclové v komplexu!}

{169}{}{Kde je sakra ten zatracenej voják?!}

{200}{}{.}
{201}{}{, pane!}

{300}{}{Øíkal jsem ti, e se sem nemáš vracet bez uniformy!}
