#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš strá.}
{101}{}{Vidíš strá v Energo brnìní.}
{102}{}{Vidíš nìkoho v Energo brnìní nezvyklého vzhledu. Na prsou má znak, kterı ti nic neøíká.}

{103}{}{Pokraèuj.}
{104}{}{Mám strá. Nemám èas se tady s tebou vybavovat.}
{105}{}{Pokraèuj v cestì. Vchod je támhle.}

{106}{}{Jdi si po své práci.}
{107}{}{Moc se tu okolo nepromenáduj bez uniformy.}
{108}{}{Teï jsi v armádì. Dej si bacha a tì nechytí bez uniformy.}

{109}{}{Vetøelci u hlavní brány!}
{110}{}{Spuste alarm! Vetøelci!}
{111}{}{Pošlete zálohy k hlavní bránì. Máme tu nezvanou návštìvu!}

{112}{}{Pohotovost u hlavní brány!}
{113}{}{Zajistìte všechny stanice! Hlavní vchod byl napaden!}
{114}{}{Poplach u hlavní brány! Èervenı kód!}

{115}{}{My tì dostaneme!}
{116}{}{Enkláva bude vládnout svìtu!}
{117}{}{Ty chcípneš, Enkláva zvítìzí!}
