#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš strá.}
{101}{}{Vidíš strá v Energo zbroji.}
{102}{}{Vidíš nìkoho v Energo zbroji nezvyklého vzhledu. Na prsou má znak, kterı ti nic neøíká.}

{103}{}{Po dobu mé sluby se nic zvláštního nestalo.}
{104}{}{U mnì se nic novıho a co u tebe?}
{105}{}{Nemìl bys stát na svém postu vojáku? Tady se nesmíš jen tak promenádovat.}

{106}{}{Jsi bez uniformy.}
{107}{}{Radši se ohlaš serovi a pøevleè se.}
{108}{}{Máš slušnou šanci, e tì vykopnou z armády, kdy na sobì nemáš uniformu. Radši si jí vyfasuj.}

{109}{}{Kdo k èertu jste chlapi... Poplach! Vetøelci!}
{110}{}{Byli jsme napadeni! Poplach!}
{111}{}{Vetøelci! Spuste alarm!}

{112}{}{Poplach! Chraòte základnu!}
{113}{}{Zajistìte všechny stanice! Máme tu poplach!}
{114}{}{Poplach! Èervenı kód!}

{115}{}{Za tohle zaplatíš!}
{116}{}{Svìtu bude vládnout Enkláva!}
{117}{}{Enkláva zvítìzí a ty tu teï chcípneš!}

{200}{}{...parchant jeden...}
{201}{}{...jo, radši vodsaï zmiz...}
{202}{}{...kretén jeden podìlanej...}
{203}{}{...ano, pane! Bastard jeden zasranej!...}
