#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš mue v záøivém obleku.}
{101}{}{Voják v Energo zbroji.}
{102}{}{Zdá se, e ten voják má na sobì nìjakı novı typ Energo brnìní.}

{103}{}{No vìøil bys tomu? U zase mám mít slubu v kuchyni!}
{104}{}{Øíká se, e nás starouš chce pøestìhovat do San Franciska!}
{105}{}{To èekání mì pìknì prudí. Já øíkám, a všechny ty primitivy jednoduše vybombardujeme a bude tu poøádek.}
{106}{}{Nemáš zapalovaè? Ne poèkej, u je to dobrı. U jsem ho našel.}
{107}{}{Dneska veèer se vzadu za hangárem hraje. Ale dávej bacha, a se to nedomákne velitel.}

{108}{}{Kdo sakra--? <zzzt> Máme tu vetøelce!}
{109}{}{Ty tam! Stát!}
{110}{}{Vetøelec na základnì!}

{111}{}{Hej ty! Co tu...? Ale co, dlabu na to... }
{112}{}{Hele radši nos svoje ID. Z tìch falešnejch poplachù u máme všichni nervy v kıblu.}
{113}{}{Ty na základnu patøíš, e jo? Zatracenì, tyhle falešnı poplachy mi jdou na nervy!}

{114}{}{Máme tu vetøelce! Sejmìte je!}
{115}{}{Tamhle je vetøelec!}
{116}{}{Tamhle! Nenechte je zdrhnout!}

{117}{}{Byli jsme napadeni. Pošlete posily!}
{118}{}{Nenechte ty vetøelce utéct!}
{119}{}{Chcípni parchante!}
