#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš kyberpsa.}
{101}{}{Vidíš K-9.}
{102}{}{Vidíš kyberpsa. Je to napùl pes a napùl stroj.}
{103}{}{Životní funkce mého pána byly ukonèeny. Ty jsi mùj nový pán?}
{104}{}{Ooo... hafík umí mluvit?}
{105}{}{Oukej. Vyvolenému se hafík líbit.}
{106}{}{Ne. Nechci pejsánka.}
{107}{}{Ha! Mluvící èokl.}
{108}{}{Zaprvé: Jsem pes. Za druhé: Komunikuji s tebou pøes hlasový výstup a k tomu úèelu používám èeský jazyk. Lze tedy pøedpokládat, že jsem 'mluvící pes.' A teï, hodláš mi odpovìdìt na otázku, kterou jsem ti dal pøed chvílí?}
{109}{}{Zaprvé: Jsem pes. Za druhé: Komunikuji s tebou pøes hlasový výstup a k tomu úèelu používám èeský jazyk. Lze tedy pøedpokládat, že jsem 'mluvící pes.' A teï, hodláš mi odpovìdìt na otázku, kterou jsem ti dal pøed chvílí?}
{110}{}{Promiò, Vyvolený tu otázku už zapomenout.}
{111}{}{Ano.}
{112}{}{Ne.}
{113}{}{(povzdech) Dávej pozor. Zkoncentruj se. Podívej se mi do oèí. Jsi pøipraven?}
{114}{}{Pøipraven na co?}
{115}{}{Ano. Vždy pøipraven.}
{116}{}{I... Kdybych nevìdìl, že tvoje IQ je menší než moje výška v kohoutku, myslel bych si, že se mì pokoušíš rozèílit. Teï zmlkni. Dávej pozor. Zkoncentruj se. Podívej se mi do oèí. Chci ti položit otázku.}
{117}{}{Tak ji polož. Kdo ti v tom brání hafane?}
{118}{}{Životní funkce mého pána byly ukonèeny. Ty jsi mùj nový pán?}
{119}{}{Uh... pejsánek mluvit?}
{120}{}{Ano. Chci pejsánka.}
{121}{}{Ne díky.}
{122}{}{To zní dobøe.}
{123}{}{Ne díky.}
{124}{}{Já... já to s tebou odmítám znovu procházet! Kdybych se mohl hýbat, roztrhal bych na malé kousíèky zadní èást tvého tìla obecnì známou jako...}
{125}{}{...prdel. Vyvolený vìdìt co je prdel. Nebýt blbec. Jen si dìlat legraci.}
{126}{}{Aha, legrace. Takže jsi mùj nový pán nebo ne?}
{127}{}{Oukej. Mám rád pejsky.}
{128}{}{Ne, nechtít žádného pejska.}
{129}{}{Výbornì. Potøebuji opravu, pane. Moje motivaèní jednotka byla odstranìna. Prosím, najdi jí, nainstaluj mi jí zpátky a já tì budu následovat.}
{130}{}{Uh... Kde jí najít?}
{131}{}{Napadá tì, kde by ta souèástka mohla být?}
{132}{}{Nejsem si jistý, pane. Zkusil bych údržbu. Musíš jít po schodech nahoru a nachází se v severovýchodní èásti základny.}
{133}{}{Oukej. Už jít.}
{134}{}{Zkusím to tam. Jestli jí nenajdu, podívám se ještì nìkde jinde.}
{135}{}{Tak mì nech na pokoji.}
{136}{}{Oukej.}
{137}{}{Jak chceš.}
{138}{}{Opìt tì zdravím. Životní funkce mého pána byly ukonèeny. Ty jsi mùj nový pán?}
{139}{}{Oukej.}
{140}{}{Ne.}
{141}{}{Dobrá.}
{142}{}{Ne díky.}
{143}{}{Ty nejsi mùj pán. Nemùžu s tebou mluvit. Sbohem.}
{144}{}{Oukej.}
{145}{}{Ahoj pane. Našel jsi už mùj motivátor?}
{146}{}{Ne, muset ještì hledat.}
{147}{}{Jo. Já najít.}
{148}{}{Ne, poøád ho ještì hledám.}
{149}{}{Mám ho pøímo tady.}
{150}{}{Budu tu èekat, než se vrátíš, mùj pane.}
{151}{}{Oukej.}
{152}{}{Tak mi prosím tu souèástku nainstaluj, pane! Prosím!}
{153}{}{Oukej. Uklidni se.}
{154}{}{Nyní jsem plnì funkèní, mùj pane. Mùžu se k tobì pøidat?}
{155}{}{Tam to nepatøí, mùj pane. Jsi si jistý, že víš, co dìláš?}
{156}{}{Oukej. Hafík jít se mnou.}
{157}{}{Vyvolený vìdìt co dìlat! Zkusit to znovu.}
{158}{}{OK. Tak pojï se mnou.}
{159}{}{Hej, už sem opravil mnohem složitìjší vìci, než je ta tvoje prašivá prdel. Drž tlamu a já to zkusím znova.}
{160}{}{Jdi pryè. Nechci tì jako svého pána.}
{161}{}{Nech mì být.}
{162}{}{Nemám tì rád. Jdi pryè.}
{163}{}{Ukonèím tvoje životní funkce.}
{164}{}{Zamìøuji zbranì na cíl. Pøiprav se na útok.}
{165}{}{Budeš znièen.}

{166}{}{Ano, pane?}
{167}{}{Oprav se.}
{168}{}{Ty èekat tady. Já hned zpátky.}
{169}{}{Uh... dej zbraò pryè. Oukej?}
{170}{}{Zùstaò poblíž.}
{171}{}{Nechodit daleko.}
{172}{}{Ty moc blízko. Vìtší rozestup.}
{173}{}{Mùžeme jít.}
{174}{}{Už nic.}
{175}{}{Teï je èas aby ses opravil.}
{176}{}{Potøebuji, abys tu poèkal dokud se nevrátím.}
{177}{}{Dej svoji zbraò pryè, oukej?}
{178}{}{Zùstaò mi nablízku.}
{179}{}{Nechoï moc daleko.}
{180}{}{Mìli bychom mít vìtší rozestupy.}
{181}{}{Pojïme.}
{182}{}{To je pro tuto chvíli vše.}
{183}{}{Všechny mé systémy fungují stoprocentnì, pane.}
{184}{}{Všechny mé systémy fungují na témìø plnou kapacitu, pane.}
{185}{}{Opravil jsem, co jsem mohl, pane, ale budu potøebovat odbornìjší pomoc.}
{186}{}{Opravil jsem, co jsem mohl, pane, ale bez další pomoci hrozí selhání systému.}
{187}{}{Ty èekat tady. Já hned zpátky.}
{188}{}{Uh... dej zbraò pryè. Oukej?}
{189}{}{Zùstaò poblíž.}
{190}{}{Nechodit daleko.}
{191}{}{Ty moc blízko. Vìtší rozestup.}
{192}{}{Mùžeme jít.}
{193}{}{Už nic.}
{194}{}{Potøebuji, abys tu poèkal dokud se nevrátím.}
{195}{}{Dej tu zbraò pryè.}
{196}{}{Zùstaò mi nablízku.}
{197}{}{Nechoï moc daleko.}
{198}{}{Mìli bychom mít vìtší rozestupy.}
{199}{}{Pojïme.}
{200}{}{To je pro tuto chvíli vše.}
{201}{}{Poèkám tady než se vrátíš, mùj pane.}
{202}{}{Oprav se.}
{203}{}{Uh... dát tu zbraò pryè. Oukej?}
{204}{}{Zùstat nablízku.}
{205}{}{Nechodit daleko.}
{206}{}{Ty moc blízko. Vìtší rozestup.}
{207}{}{Mùžeme jít.}
{208}{}{Už nic.}
{209}{}{Teï je èas aby ses opravil.}
{210}{}{Dej tu zbraò pryè.}
{211}{}{Zùstaò mi nablízku.}
{212}{}{Nechoï moc daleko.}
{213}{}{Mìli bychom se trochu roztáhnout.}
{214}{}{Pojïme.}
{215}{}{To je pro tuto chvíli všechno.}
{216}{}{Zatahuji zbraò, pane.}
{217}{}{Ty opravit se.}
{218}{}{Ty èekat tady. Já hned zpátky.}
{219}{}{Zùstat nablízku.}
{220}{}{Nechodit daleko.}
{221}{}{Ty moc blízko. Vìtší rozestup.}
{222}{}{Teï jít.}
{223}{}{Už nic.}
{224}{}{Teï je èas abys opravil.}
{225}{}{Potøebuji, abys tu poèkal, dokud se nevrátím.}
{226}{}{Zùstaò mi nablízku.}
{227}{}{Nechoï moc daleko.}
{228}{}{Mìli bychom se trochu víc roztáhnout.}
{229}{}{Pojïme.}
{230}{}{To je pro tuto chvíli všechno.}
{231}{}{Zužuji rozestup, pane.}
{232}{}{Ty opravit se.}
{233}{}{Poèkat tady. Já hned zpátky.}
{234}{}{Uh... dát tu zbraò pryè. Oukej?}
{235}{}{Nechodit daleko.}
{236}{}{Ty moc blízko. Vìtší rozestup.}
{237}{}{Mùžeme pùjdeme.}
{238}{}{Už nic.}
{239}{}{Teï by ses mìl opravit.}
{240}{}{Potøebuji, abys tu poèkal, dokud se nevrátím.}
{241}{}{Dej tu zbraò pryè.}
{242}{}{Nechoï moc daleko.}
{243}{}{Mìli bychom se trochu roztáhnout.}
{244}{}{Pojïme.}
{245}{}{To je pro tuto chvíli vše.}
{246}{}{Zvìtšuji rozestup mezi námi, pane.}
{247}{}{Oprav se.}
{248}{}{Poèkat tady. Já hned vrátit se.}
{249}{}{Uh... dát tu zbraò pryè. Oukej?}
{250}{}{Zùstat nablízku.}
{251}{}{Ty moc blízko. Vìtší rozestup.}
{252}{}{A teï my jít.}
{253}{}{Už nic.}
{254}{}{Mìl by ses teï opravit.}
{255}{}{Potøebuji, abys tu poèkal, dokud se nevrátím.}
{256}{}{Dej tu zbraò pryè.}
{257}{}{Zùstaò mi nablízku.}
{258}{}{Mìli bychom se trochu roztáhnout.}
{259}{}{Pojïme.}
{260}{}{To je pro tuto chvíli vše.}
{261}{}{Zvìtšuji rozestup na maximum, pane.}
{262}{}{Uzdravit se.}
{263}{}{Poèkat tady. Já hned zpátky.}
{264}{}{Uh... dát tu zbraò pryè. Oukej?}
{265}{}{Zùstat nablízku.}
{266}{}{Nechodit daleko.}
{267}{}{Teï my jít.}
{268}{}{Už nic.}
{269}{}{Teï by ses mìl opravit.}
{270}{}{Potøebuji, abys tu zùstal, dokud se nevrátím.}
{271}{}{Dej tu zbraò pryè.}
{272}{}{Zùstaò mi nablízku.}
{273}{}{Nechoï moc daleko.}
{274}{}{Pojïme.}
{275}{}{To je pro tuto chvíli vše.}
{276}{}{Promiò, pane, ale vypadá to, že se do vaší skupiny už nevmìstnám. Poèkám tady, dokud pro mì nebudeš mít místo.}
{277}{}{Jak pøikazuješ, pane.}
{278}{}{Oprav se.}
{279}{}{Poèkat tady. Hned se vrátit.}
{280}{}{Uh... dát tu zbraò pryè. Oukej?}
{281}{}{Zùstat nablízku.}
{282}{}{Nechodit daleko.}
{283}{}{Ty moc blízko. Vìtší rozestupy.}
{284}{}{Už nic.}
{285}{}{Teï by ses mìl opravit.}
{286}{}{Potøebuji, abys tu zùstal, dokud se pro tebe nevrátím.}
{287}{}{Dej tu zbraò pryè.}
{288}{}{Zùstaò mi nablízku.}
{289}{}{Nechoï moc daleko.}
{290}{}{Mìli bychom se trochu roztáhnout.}
{291}{}{To je pro tuto chvíli vše.}
{292}{}{Jistì. Vypadáš jako správnej pes.}
{293}{}{Ne, díky.}

{300}{}{Já smutný. Neumìt tì opravit.}
{301}{}{Promiò, ale nedokážu tì opravit.}

{400}{}{Vypadá to, že ti chybí nìjaká souèástka.}
{410}{}{To nedìlá nic.}
{420}{}{Tohle nepasuje.}

{800}{}{Opravil jsi K9.}

{1000}{}{Ano, pane?}

{1100}{}{Všechny mé systémy fungují stoprocentnì, pane.}
{1200}{}{Všechny mé systémy fungují témìø na plnou kapacitu, mùj pane.}
{1300}{}{Opravil jsem, co jsem mohl, pane, ale budu potøebovat odbornou pomoc.}
{1400}{}{Opravil jsem, co jsem mohl, pane, ale bez další pomoci hrozí selhání systému.}

{1500}{}{Budu oèekávat tvùj návrat, mùj pane.}

{1600}{}{Oèekáváš, že spolknu svoje zuby, pane?}

{1700}{}{Budu chodit ve tvých stopách, pane.}
{1800}{}{Budu se od tebe pohybovat ve støední vzdálenosti, pane.}
{1900}{}{Budu se od tebe pohybovat v nejvìtší pøijatelné vzdálenosti, pane.}

{2000}{}{Promiò, pane, ale vypadá to, že se do vaší skupinì už nevmìstnám. Poèkám tady, dokud pro mì nebudeš mít místo.}
{2200}{}{Jak pøikazuješ, pane.}
{2300}{}{Mám jen svùj kožich, pane. Nenosím nic jiného.}
{2400}{}{Netoužím sundat si svùj kožich, pane.}
{2500}{}{Zuby, pane. To jsou ty bílé ostré vìci v mé tlamì.}

{2700}{}{Jsi vìtší hajzl než Schreber. Nepùjdu s tebou nikam.}
{2800}{}{Velmi dobøe mùj pane. Jsem ti k službám.}
{2900}{}{Ty jsi ale kus kreténa. Nikam s tebou nepùjdu. Jdi pryè.}
