#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš mechanika.}
{101}{}{Vidíš Kevina, mechanika.}
{102}{}{Vidíš mue ve vojenské uniformì. Podle mastnıch skvrn usuzuješ, e je to spíš mechanik ne voják.}

{200}{}{Teï s tebou nemùu mluvit. Jdi za Quincym.}
{201}{}{Quincy to tu má na starosti. Jdi za ním.}
{202}{}{Sem tady jen malá ryba. Promluv si spíš s Quincym.}

{300}{}{Jsi bez uniformy.}
{301}{}{Radši by ses mìl pøevléct vojáku.}
{302}{}{Máš slušnou šanci, e tì vyrazí z armády, kdy na sobì nemáš uniformu. Radši by sis mìl nìjakou vyfasovat.}

{400}{}{Kdo k èertu jste chlapi... Poplach! Vetøelci!}
{401}{}{Byli jsme napadeni! Poplach!}
{402}{}{Vetøelci! Spuste sirény!}

{500}{}{Sakra! Rychle zapnìte zálohy.}
{501}{}{Ukonèete všechny probíhající operace.}
{502}{}{Spuste ochranu systému a aktivujte všechna ochranná hesla.}

{600}{}{Jsem mechanik a ne voják!}
{601}{}{Zamiø tou navádìcí laserovou diodou na nepøítele. Pak zmáèkni kohoutek.}
{602}{}{Pomóc! Pomóc! Rychle do údrby!}