#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš strá.}
{101}{}{Vidíš strá v kevlarové zbroji .}
{102}{}{Vidíš nìkoho v kevlarové zbroji nezvyklého vzhledu. Na prsou má znak, kterı ti nic neøíká.}

{103}{}{Po dobu mé sluby se nic zvláštního nestalo.}
{104}{}{U mì se nic novıho a co u tebe?}
{105}{}{Nemìl bys stát na svém postu, vojáku? Tady se nesmíš jen tak poflakovat.}

{106}{}{Jsi bez uniformy.}
{107}{}{Mìl by ses zahlásit u seri a pøevlíknout se.}
{108}{}{Máš velkou šanci, e pùjdeš k raportu, kdy na sobì nemáš uniformu. Radši si nìjakou vyfasuj.}

{109}{}{Kdo k èertu jste chlapi... Poplach! Vetøelci!}
{110}{}{Byli jsme napadeni! Poplach!}
{111}{}{Vetøelci! Spuste alarm!}

{112}{}{Poplach! Chraòte základnu!}
{113}{}{Zajistìte všechny stanice! Máme tu poplach}
{114}{}{Poplach! Èervenı kód!}

{115}{}{Chcípneš!}
{116}{}{Enkláva bude vládnou svìtu!}
{117}{}{Ty zhebneš, Enkláva bude ít dál!}

{118}{}{Promiò vojáku. Tahle zóna je pouze pro vyhrazenı personál. Musím tì poádat, abys odešel.}
{119}{}{Doktor chtít, abych já zabít deathclaw. Nechtít to udìlat sám.}
{120}{}{Oukej, já jít.}
{121}{}{Doktor po mnì chce, abych pro nìj zabil to zvíøe. Sám si na to netroufá.}

{122}{}{Vím, e ten bastard na to nemá aludek, aby to udìlal sám. A tu špinavou práci musíme vdycky udìlat my. (povzdech) No dobøe. Jdi dál a hodnì štìstí, vojáku.}
{123}{}{Díky.}

{124}{}{Proè na mì tak zíráš, vojáku?}
{125}{}{Vyvolenı slyšet tobì øíkat Snookie. To hezké.}
{126}{}{Prı se ti tu øíká Snookie. Myslím, e to je velmi roztomilé.}

{127}{}{Coe... Tohle ti øekl on? A mi skonèí sluba, tak mu nakopu zadek... Jdi si po svém vojáku. A vyma si ten debilní úsmìv z oblièeje!}
{128}{}{OK.}
