#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš technika.}
{101}{}{Vidíš poèítaèového technika.}
{102}{}{Vidíš nìkoho v laboratorním plášti s kapsou plnou propisek.}

{103}{}{Dobrı den vojáku.}
{104}{}{Nièeho se tu prosím nedotıkej.}
{105}{}{Tví kumpáni tu nemají co pohledávat.}

{106}{}{Jsi bez uniformy. }
{107}{}{Radìji by ses mìl pøevléct. Zbrojnice je v hale dole nalevo.}
{108}{}{Je tu velká šance, e pøijdeš o práci, kdy se tu potloukáš bez uniformy. Radši by sis mìl nìjakou vyfasovat.}

{109}{}{Kdo k èertu jste chlapi... Poplach! Vetøelci!}
{110}{}{Byli jsme napadeni! Poplach!}
{111}{}{Vetøelci! Spuste alarm!}

{112}{}{Sakra! Rychle zapnìte zálohování.}
{113}{}{Ukonèete všechny probíhající operace.}
{114}{}{Spuste ochranu systému a aktivujte všechna ochranná hesla.}

{115}{}{Jsem vìdec, ne bojovník!}
{116}{}{Nasmìruj laserovı paprsek na nepøítele. Pak zmáèkni spouš.}
{117}{}{Pomóc! Pomóc! Rychle do poèítaèového centra!}