#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš technika.}
{101}{}{Vidíš technika Enklávy.}
{102}{}{Vidíš nìkoho v laboratorním obleku. Vypadá dùvìryhodnì a sebejistì.}

{103}{}{Ano, vojáku?}
{104}{}{Co bıt tohle za místo?}
{105}{}{Mìj se. Muset u jít.}
{106}{}{Co je tohle místo?}
{107}{}{Tak se mìj. Uvidíme se pozdìji.}

{108}{}{Tohle je poèítaèové centrum. Tamhle je hlavní poèítaè, vstupní terminál je hned vedle nìj a tyhle vìcièky jsou jednotky pro ukládání dat na holodisky. Jsou nejnovìjší a nejvìtší.}
{109}{}{Ehe. Co ty dìlat?}
{110}{}{No a co máš ty za práci?}

{111}{}{Jsem hlavní poèítaèovı analytik. Hlavnì mám na starosti všechno tohle vybavení.}
{112}{}{Mùe Vyvolenı pouít poèítaè?}
{113}{}{Já nechápat nic. Já jdu.}
{114}{}{Poslyš, mùu na minutku k poèítaèi? Chci si ten systém trošku omrknout?}
{115}{}{Pìknì se mi s tebou kecalo. Uvidíme se pozdìji.}

{116}{}{No... Tohle zaøízení smí pouívat jen vyškolenı personál. Pochop, všechny ty pøístroje jsou hodnì sloité a citlivé.}
{117}{}{Prosím. Já nic nerozbít.}
{118}{}{Slibuju ti, e nic nepoškodím.}

{119}{}{No tak dobøe. Do systému se mùes nalogovat tamhle z toho terminálu. Ale buï opatrnı, prosím. Kdybys tu mašinu poškodil, zastøelili by nás oba. Jo a pøístupové heslo je 'Snookie.'}
{120}{}{Promiò, ale to nepøichází v úvahu. Nesmím nikomu nepovolanému dovolit aby pouíval naše vybavení.}
{121}{}{Snookie? Co znamená 'Snookie'?}
{122}{}{Oukej. Rozumìt.}
{123}{}{Snookie? Co to k èertu znamená 'Snookie'?}
{124}{}{Jasnì. Rozumím.}

{125}{}{'Snookie' je pøezdívka mojí pøítelkynì. Myslím, e je to roztomilé jméno. Mimochodem to je ta dívka venku v hale. Je jednou ze stráí.}
{126}{}{Oukej, fajn. Díky.}
{127}{}{Jo... je fakt roztomilá. Díky.}

{128}{}{Jsi bez uniformy. }
{129}{}{Radìji by ses mìl pøevléct. Zbrojnice je dole v hale nalevo.}
{130}{}{Máš slušnou šanci, e dostaneš padáka, kdy na sobì nemáš uniformu. Radši by sis mìl nìjakou vyfasovat.}

{131}{}{Kdo k èertu jste chlapi... Poplach! Vetøelci!}
{132}{}{Byli jsme napadeni! Poplach!}
{133}{}{Vetøelci! Spuste alarm!}

{134}{}{Sakra! Rychle spuste zálohování.}
{135}{}{Ukonèete všechny probíhající operace.}
{136}{}{Spuste ochranu systému a aktivujte všechna ochranná hesla.}

{137}{}{Já jsem vìdec, ne voják!}
{138}{}{Zamiø tím svítícím koncem navádìcí diody na nepøítele. Pak zmáèkni spouš.}
{139}{}{Pomoc! Pomoc! Rychle do poèítaèového centra!}
