#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš nìkoho v Energo brnìní.}
{101}{}{Vidíš ubytovatele.}
{102}{}{Vidíš nìkoho v Energo brnìní nezvyklého vzhledu. Na prsou má znak, kterı ti nic neøíká.}

{103}{}{Kdo k èertu jste chlapi... Poplach! Vetøelci na základnì!}
{104}{}{Kdo mì zase... aaa vím, proè jsi tady. Samozøejmì se chceš zbavit toho zastaralého obleku, co máš na sobì.}
{105}{}{Proè jste bez uniformy, vojáku?}
{106}{}{Chcípni!}
{107}{}{Hmm, jo...}
{108}{}{Hmm...}
{109}{}{Já tu novı.}
{110}{}{Já ne jeden z vojákù!}
{111}{}{Uh, no...}
{112}{}{Jsem tu novı.}
{113}{}{Nejsem jeden z vašich vojákù!}

{114}{}{Coe? Doufám, e pro to budeš mít dobrou omluvu? Èekám, vojáku!}
{115}{}{Ještì nemít uniformu.}
{116}{}{Ještì ádnou uniformu nemám.}

{117}{}{Jsi v myšlìní trochu pomalejší, co? (povzdech) No nic, ty za to nemùeš. Mám bratra, kterı se ti trochu podobá. Take jsi tu novej? Nevzpomínám si, e bych tì tu nìkdy vidìl.}
{118}{}{Jsi tu novı? Nevzpomínám si, e bych tì tu nìkdy pøedtím vidìl.}
{119}{}{Ano! Já tu novı!}
{120}{}{Ano, jsem tu novı.}

{121}{}{Dobøe, pak tedy budeš potøebovat standardní vybavení. Jdi do zbrojnice, pøevlékni se a dostaneš pøidìlenou svojí zbraò. A potom se ohlas u seranta.}
{122}{}{Díky!}

{123}{}{Není zaè. A teï se odsud ztra. Mám ještì hodnì práce a nechci bıt rušen.}

{124}{}{Teï mám moc práce. Pøijï pozdìji.}

{125}{}{Nazdar, rekrute. Pøed chvílí volal tvùj serant. Øíkal, e se tu máš pøevléci a pak, e tì mám poslat zpátky k nìmu. Je to tak?}
{126}{}{Ano.}

{127}{}{Tahle základna má poplach a já tì neznám. Uka mi svoje doklady, vojáku.}
{128}{}{Nemít doklady u sebe.}
{129}{}{Nepotøebovat doklady!}
{130}{}{Nemám mí papíry zrovna s sebou. Jsou v mé skøíòce.}
{131}{}{Doklady? Mám ty tvı doklady pøímo tady!}

{132}{}{Špatná odpovìï. Svoje doklady máš mít vdycky u sebe!}
{133}{}{A sakra.}
