#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš mue ve vojenské uniformì.}
{101}{}{Vidíš mechanika Quincyho.}
{102}{}{Vidíš mue ve vojenské uniformì. Soudì podle mastnıch skvrn na uniformì hádáš, e je to spíš mechanik ne voják.}

{103}{}{Jmenuju se Quincy, vojáku. Proè mi klepeš na rameno? Ztratil ses?}
{104}{}{Potøebovat se na nìco zeptat.}
{105}{}{Ale nic.}
{106}{}{Zdravím. Potøebuju se tì na nìco zeptat.}
{107}{}{Zapomeò na to.}

{108}{}{No tak dobøe, ale ptej se rychle. Musím ještì dodìlat inventury.}
{109}{}{Co potøebuješ vìdìt?}
{110}{}{Co tohle za místo?}
{111}{}{Vyvolenı hledat plány od vertibird. Kde je najít?}
{112}{}{Technik øíct mi, e plány od vertibird bıt nìkde tady.}
{113}{}{U muset jít.}
{114}{}{Co je tohle za místo?}
{115}{}{Hledám plány k vertibirdùm. Nevíš, kde bych je mohl najít?}
{116}{}{Technik mi øekl, e bych tu mohl najít plány k vertibirdùm.}
{117}{}{No, u musím jít.}

{118}{}{Tady je údrba. Opravujeme tu všechno s vıjimkou vertibirdù.}
{119}{}{Kde se opravovat vertibird ?}
{120}{}{Kde se opravujou ty vertibirdy?}

{121}{}{Kvùli svojí velikostí se vejdou jen do hangáru nebo ven. Rozumíš?}
{122}{}{Hmm... jo.}
{123}{}{Hmm, jasnì. Jo rozumím.}

{124}{}{Hmm... no já sice mám kopie tìch plánù, ale nemùu je dávat kdejakımu pobudovi, kterej si o nì øekne. Na co je chceš?}
{125}{}{Mít na jihu pøátele, kteøí je hroznì moc potøebovat.}
{126}{}{Hmm... no...}
{127}{}{Mám dole na jihu pár pøátel, kteøí po nich moc touí.}
{128}{}{Sera mi øekl, e mu je mám pøinést.}

{129}{}{Tak dole na jihu... Do prdele! Máme tu špeha! Stráe! Poplach!}
{130}{}{A do prdele.}
{131}{}{A do prdele. Tak tohle se mi nepovedlo.}

{132}{}{Ty jsi asi trochu pomalejší, e jo? No neøíkají vám poskokové bez dùvodu. Podívej, Einsteine, nemùu ti ty plány dát jen tak na ksicht. Rozumíš? Tak se vra zpátky za tím papalášem, co tì sem poslal a pìknì si od nìj pøines písemnı potvrzení.}
{133}{}{Podívej, Einsteine, nemùu ti dát ty plány bez povolení, je ti to doufám jasnı? Take se vra za tím šefíkem, kterej tì sem poslal a seeò si od nìj na písemnı potvrzení.}
{134}{}{OK, já jít.}
{135}{}{Ne, zaprvé já tì zastøelit, za druhé najít plány a pak... k sakru, co následovat po dvojce?}
{136}{}{Hej, to máš teda recht.}
{137}{}{Ne, myslím, e jednodušší bude kdy tì zastøelím a zatímco budeš na zemi tiše krvácet, já si ty plány najdu.}

{138}{}{Technik øíkáš... myslíš Raula? On tì poslal?}
{139}{}{Uh, no jo.}
{140}{}{Uh, ne.}
{141}{}{Jo, právì tenhle chlapík.}
{142}{}{Ne, nemyslím, e se jmenoval Raul.}

{143}{}{Zatracenì! Víš, Raul by ztratil i svojí hlavu kdyby mu jí tak pevnì nepøišili k prdeli. Sráè jeden! To je u potøetí v tomhle ètvrtletí kdy ty plány ztratil! A teï dokonce nemá ani tolik odvahy aby ke mnì pøišel a øekl si o nì sám? Fajn, plány jsou tamhle ve skøíni. Jo a a mu je odneseš, øekni tomu sráèovi, e bych ho rád vidìl.}
{144}{}{Díky.}

{145}{}{Take zase zpátky. Máš u to potvrzení?}
{146}{}{Zase ty? Co to bude tentokrát?}
{147}{}{Vyvolenı mít plazmovou pušku. To mu úplnì staèit!}
{148}{}{Ne, ještì ne.}
{149}{}{Jo, mám zvláštní povolení, velikou zasranou bouchaèku. Ta mi bude úplnì staèit, starouši!}
{150}{}{Ne, ještì ne.}
{151}{}{Chtít se na nìco zeptat.}
{152}{}{Chtít tì jen pozdravit.}
{153}{}{Potøebuji se tì na nìco zeptat.}
{154}{}{Nic, jen jsem tì chtìl pozdravit.}

{155}{}{Jsi blázen? Chodit tu bez uniformy? Rychle se pøevleè!}
{156}{}{Kdy tì serant naèapá bez uniformy, nakope ti prdel.}
{157}{}{Proè na sobì nemáš uniformu?}

{158}{}{Zatracenì! Byli jsme napadeni! Poplach!}
{159}{}{Vetøelci! Zavolejte stráe!}
{160}{}{Stráe! Vetøelci na údrbì!}

{161}{}{Co se dìje? Jsme napadeni?}
{162}{}{Proè ten poplach? Co se stalo?}
{163}{}{Co se k èertu zase dìje?}

{164}{}{Hej! Nešourej se v tìch zásuvkách.}
{165}{}{Øíkal jsem ti, e se nemáš hrabat v mıch vìcech! Stráe!}
{200}{}{Aha. No, nevìø všemu, co nìkde zaslechneš.}
{201}{}{Kdo ti to øíkal? Protoe on bude po tobì hned ten další, komu to ruènì vysvìtlím.}
{300}{}{Nevidíš, e nemám èas?}
{301}{}{Hej! Nešourej se v tìch zásuvkách!}
{302}{}{Øíkal jsem ti, e se nemáš hrabat v mıch vìcech! Stráe!}
