#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš mechanika.}
{101}{}{Vidíš Raula, mechanika.}
{102}{}{Vidíš muže ve špinavé vojenské uniformì. Soudì podle tìch mastných flekù to bude spíše mechanik než voják.}

{103}{}{Promiò, chlape, ale teï nemám èas se tu s tebou vybavovat. Musím zprovoznit tady toho vertibirda.}
{104}{}{Doktor chtít opravit svùj pes K-9. On øíkat, že ty mít k nìmu souèástku.}
{105}{}{Jo... jasnì.}
{106}{}{Uh, Quincy tì chtít vidìt. Já mít za úkol ti to vyøídit.}
{107}{}{Doktor chce opravit svého psa. Posílá mì pro tu chybìjící souèástku.}
{108}{}{Fajn. Nazdar.}
{109}{}{Raule, Quincy tì chce vidìt.}

{110}{}{Quincy? Jo, ale Raul nechce vidìt jeho. Raul má už dost tìch jeho blbejch kecù, víš?}
{111}{}{Oukej.}
{112}{}{Quincy øíkat, že ty být velký posera.}
{113}{}{Fajn.}
{114}{}{Quincy øíkal, že jsi sráè a že nemáš odvahu za ním pøijít.}

{115}{}{Hele ty chytráku, Raul se od nikoho nenechá urážet. Už jsi nìkdy vidìl Quincyho dìlat tady na tìch vertibirdech? Ani náhodou. Na tìchhle mašinkách mùže makat jenom Raul. Víš proè? Protože Quincy by to nikdy nezvládl, tak to je!}
{116}{}{Uh...}
{117}{}{Dobøe...}

{118}{}{Sorry, omlouvám se. Raul na tebe nechtìl køièet, víš? To není tvoje chyba, tys mi tu zprávu jen pøedal. Hele, máš teï hodnì práce?}
{119}{}{Ne, nemít co dìlat. Proè?}
{120}{}{Ne, ani bych neøekl. Proè?}

{121}{}{Hele podívej, chlape. Raul pùjde Quincymu oplatit jeho návštìvu, víš? Raul mu pùjde ukázat zaè je toho loket. Poèkáš tady a budeš hlídat vertibirdy. Oukej?}
{122}{}{Já pohlídat je.}
{123}{}{Jistì Raule. Pro nikoho jiného bych to neudìlal, ale pro tebe to udìlám rád.}

{124}{}{Hej, díky, chlape. Raul ti bude dlužen službièku! Hlavnì nechoï nikam pryè a hele chlape, kdyby se tu potloukal u vertibirdu nìkdo, kdo tu nemá co dìlat, tak mu ustøel prdel. Oukej?}
{125}{}{Jasan.}

{126}{}{Hej, co si myslíš, že dìláš? Táhni od toho vertibirdu pryè, chlape! Raul už má tak dost problémù i bez tebe, víš? Staèí co s nima vyvádí ti zatracení piloti!}
{127}{}{Hej, chlape, Raul ti už øíkal, abys k sakru táhnul pryè od toho vertibirdu. Teï tì Raul nauèí poslouchat. Pojï sem ty prde. Sundej si to posraný brnìní a rozdáme si to jako chlap s chlapem.}
{128}{}{Ne, to si nemyslet.}
{129}{}{Ty jít k èertu, Raul. Už teï ty být mrtvý!}
{130}{}{Ne díky, seš na mì moc ostrej chlapík, kámo.}
{131}{}{Proè bych si o tebe mìl otloukat pìsti, když mám tak skvìlou bouchaèku?}

{132}{}{Tak táhni od Raulovo vertibirdù! Zmiz vodsaï!}
{133}{}{Oukej.}

{134}{}{Raul si myslí, že musíš být blázen, když se tu couráš bez uniformy.}
{135}{}{Hej, chlape, jestli tì tu seržant chytí bez uniformy, tak ti rozkope prdel.}
{136}{}{Chlape, proè na sobì nemáš uniformu?}

{137}{}{Zatracenì! Byli jsme napadeni! Poplach!}
{138}{}{Vetøelci! Zavolejte stráže!}
{139}{}{Stráže! Vetøelci v hangáru!}

{140}{}{Hej, èlovìèe, co se dìje? Jsme napadeni?}
{141}{}{Proè ten poplach? Co se stalo?}
{142}{}{Co se to k èertu zase dìje?}

{143}{}{Raul tì teï pošle do nemocnice za doktorem Sovou, blbe.}
{144}{}{Hej, trotle, mìl by ses zaèít modlit!}
{145}{}{Raul ti teï nakope prdel!}

{146}{}{Hej, chlape, je to tamhle ve skøíòce. Vezmi si ho a øekni doktorovi, že ho Raul pozdravuje.}
{147}{}{Díky.}

{150}{}{Hej, chlape! Raul nemá rád, když se mu cizí lidi motají do jeho záležitostí. Táhni odsud.}
{151}{}{Raul ti øíkal, že nemáš lézt do jeho vìcí! Stráže!}
{200}{}{Raul slyšel, že si ho zase pomlouval.}
{201}{}{Tak tohle bylo naposled, sráèi. Raul ti teï zmaluje zadek.}
{300}{}{Nevidíš, že na tebe Raul nemá èas?}
