#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Voják ve sluební uniformì.}
{101}{}{Nìjakej Nìèeho-Technik, hodnost X.}
{102}{}{Má na sobì sice vojenskou uniformu, ale pøesto tenhle chlapík vypadá spíše jako technik.}

{103}{}{Hele, kolikrát ti to mám øíkat ty hòupe? Nestùj mi v cestì!}
{104}{}{Nemáš na co støílet?}
{105}{}{Zdravím, vojáku.}

{106}{}{Kdo jsi? Stráe!}
{107}{}{Co je k èertu zase tohle? Vetøelec na základnì!}
{108}{}{Zatracenì! Kde mám svojí pistoli!}

{109}{}{Hele, u to tu celı prohledali a nic tu nenašli.}
{110}{}{Jeiši, tyhle falešnı poplachy mì jednou zabijou.}
{111}{}{Skvìle, další falešnej poplach. Teï budeme muset shodit celej náš systém a zase ho nahodit zpátky.}

{112}{}{Zatracenì! Tamhle! Chyte toho špeha!}
{113}{}{Sakra, to je útok! Kde mám bouchaèku?}
{114}{}{Støílení? Nikdo neøíkal, e by se tu mìlo støílet!}

{115}{}{Kdo k èertu jsi? Stráe!}
{116}{}{Ty nejsi z Enklávy! Stráe!}
{117}{}{Vetøelci! Sabotéøi! Tamhle!}

{118}{}{Hej, neple se mi do tìch plánù. Já tu pracuju.}
{119}{}{Kde je, doprèic, ta èást gyroskopu?}
{120}{}{Zatracenı piloti. Vdycky ty mašiny roflákaj.}

{121}{}{Rozumím a beru na vìdomí -- a teï mì neruš, mám práci.}
{122}{}{Hele, ádnı osobní hovory nejsou dovolenı, vojáku.}
{123}{}{Promiò, ale teï ti nemùu pomoci.}

{124}{}{Máš tu dole nìco na práci? Jestli ne, tak mi uhni z cesty.}
{125}{}{Tohle je zakázaná zóna, vojáku.}
{126}{}{Uhni mi s cesty vojáku.}

{127}{}{Co se k èertu dìje? Co se to zas do prdele dìje?}
{128}{}{Sakra! Dostali se dovnitø!}
{129}{}{Šašci! To je urèitì zas jen další falešnej poplach.}
