#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš technika.}
{101}{}{Vidíš technika z Enklávy.}
{102}{}{Vidíš nìkoho v laboratorním plášti s kapsami plnými propisek. Je trochu zmatený tím, že vidí v práci nìkoho nového.}

{103}{}{Ano, pane?}
{104}{}{Já tu nový. Potøebovat se na nìco zeptat.}
{105}{}{Tak nashle. Už muset jít.}
{106}{}{Jsem tu nový. Potøeboval bych se zeptat na nìjaké vìci, abych se lépe seznámil se základnou.}
{107}{}{Omlouvám se že otravuju. Chtìl jsem tì jenom pozdravit.}

{108}{}{Nedìlám tu dlouho, pane. Nevím, jestli vám budu moci zodpovìdìt všechny dotazy, ale pokusím se.}
{109}{}{S èím ti mùžu pomoct?}
{110}{}{Co být tohle za místo?}
{111}{}{Co je tvoje práce?}
{112}{}{Kde být hlavní základna Enkláva?}
{113}{}{Hledat plány k vertibird. Kde je najít?}
{117}{}{Vyvolený muset jít.}
{118}{}{Co je tohle za místo?}
{119}{}{Jakou tu máš práci?}
{120}{}{Kde se nachází hlavní základna Enklávy?}
{121}{}{Potøebuju se podívat na plány vertibirdu. Kde jsou?}
{125}{}{Nic. Už musím jít.}

{126}{}{Toto je komunikaèní centrum. Navazujeme odtud všechny kontakty s hlavní základnou.}
{127}{}{Aha. Ještì se zeptat.}
{128}{}{Rozumím. Ještì mám pár otázek.}

{129}{}{Jsem technik komunikaèního centra druhé tøídy. Spojuji všechny hovory s hlavní základnou a zaøizuji potøebné vybavení.}
{130}{}{Hmm... jo tak.}
{131}{}{Výbornì. Pøeju hodnì pracovních úspìchù.}

{132}{}{Vy si ze mì dìláte srandu, že jo? }
{133}{}{Beze srandy. Kde být základna?}
{134}{}{Vypadám snad, že si dìlám legraci?}

{135}{}{Hlavní základna se nachází na pobøeží Pacifiku blízko mìsta San Francisco. Mùžu se zeptat, proè vás to zajímá?}
{136}{}{Ne. Vojenské tajemství. Jak se na tu základnu Vyvolený mùže dostat?}
{137}{}{Ne. To je vojenské tajemství. No a kolik znáš zpùsobù jak se na tu základnu dostat?}

{138}{}{Dobøe... tak nejspíš asi vertibirdem, což je samozøejmì nejlepší možnost. Pak je tu možnost použít ten tanker, co kotví dole v San Franciscu. A pak už byste to musel jedinì pøeplavat.}
{139}{}{Díky.}
{140}{}{Díky.}

{141}{}{Mìly by se nacházet v údržbì, hned vedle centra øízení dopravy.}
{142}{}{Oukej.}
{143}{}{Jo už vím.}

{153}{}{Jsi normální, courat se tady okolo bez uniformy? Padej se rychle pøevlíct!}
{154}{}{Jestli tì seržant chytí bez uniformy, nakope ti prdel.}
{155}{}{Proè jsi bez uniformy? }

{156}{}{Do prdele! Byli jsme napadeni! Poplach!}
{157}{}{Vetøelci! Zavolejte stráže!}
{158}{}{Stráže! Vetøelci v komunikaèním centru!}

{159}{}{Co je? Byli jsme napadeni?}
{160}{}{Proè je poplach? Co se stalo?}
{161}{}{Co se tu k èertu zase dìje?}

{162}{}{Jsem jenom technik, nezabíjej mì!}
{163}{}{Nejsem voják, jsem civilní osoba!}
{164}{}{Tohle je jen laboratorní oblek, ne brnìní! Já tu jen pracuju!}
