#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš technika.}
{101}{}{Vidíš technika z Enklávy.}
{102}{}{Vidíš nìkoho v laboratorním plášti. Vypadá dùležitì a sebejistì.}

{103}{}{Ano, pane?}
{104}{}{Být tu nový. Potøebovat se na nìco zeptat.}
{105}{}{Jen tì zdravit. Už muset jít.}
{106}{}{Jsem tu novej a chci se trochu seznámit se základnou. Mùžeš mi odpovìdìt na pár otázek?}
{107}{}{Tak se tu mìj. Uvidíme se pozdìji.}

{108}{}{Zajisté, vojáku.}
{109}{}{S èím mùžu pomoct?}
{110}{}{Co být tohle za místo?}
{111}{}{Jakou ty tu mít práci?}
{112}{}{Kde hlavní základna Enklávy?}
{113}{}{Hledat plány od vertibirdu. Kde je Vyvolený moci najít?}
{117}{}{Muset jít.}
{118}{}{Co je tohle za místo?}
{119}{}{Jaká je tvoje práce?}
{120}{}{Kde se nachází hlavní základna Enklávy?}
{121}{}{Potøebuju se podívat na plány vertibirdu. Kde jsou?}
{125}{}{Nic. Už musím jít.}

{126}{}{Tohle je komunikaèní centrum. Odsud navazujeme všechny kontakty s hlavní základnou i všemi ostatními opìrnými bázemi.}
{127}{}{Aha. Ještì se zeptat.}
{128}{}{Rozumím. Ještì mám pár dotazù.}

{129}{}{Jsem technik komunikaèního centra první tøídy. Dohlížím na všechny ostatní techniky. Hlavnì dávám pozor, aby se tu neflákal nikdo nepovolaný.}
{130}{}{Hmm... aha.}
{131}{}{Dobøe. Pøeju hodnì pracovních úspìchù.}

{132}{}{Vojáku, tahle informace je pøísnì tajná. Jestliže ji neznáte, znamená to, že ji ani nepotøebujete znát.}
{133}{}{Oukej.}
{134}{}{Ale no tak, já pøece nejsem žádný buran nebo nìco takového. Jsme pøece všichni na stejný lodi; copak sis nevšiml znaku na mým brnìní?}
{135}{}{Rozumím.}

{136}{}{Ano, pane. Hlavní základna se nachází na pobøeží Tichého oceánu nedaleko San Francisca. Mùžu se dotázat, proè vás to zajímá pane?}
{137}{}{Vojáku, øíkal jsem vám, že tahle informace je pøísnì tajná.}
{138}{}{Z bezpeènostních dùvodù kontroluji stupeò informovanosti mezi pracovníky základny. Takže mi teï øeknìte, pokud to víte, jakými zpùsoby se lze dostat na hlavní základnu.}
{139}{}{Rozumím.}

{140}{}{Ano, pane. Zaprvé: primární možnost jak se lze dostat na základnu je pomocí vertibirdù. Z dùvodu jejich složitého ovládání je vylouèeno, že by je mohl ovládat nìjaký primitiv. Za druhé: v pøístavu v San Franciscu je v provozuschopném stavu ropný tanker. Loï byla ale zablokována a k jejímu odblokování je tøeba klíè. Tento klíè má ve svém držení velitel základny. No a za tøetí: s vhodným vybavením lze samozøejmì k hlavní základnì i doplavat. Pravdìpodobnost pøežití se ale rovná nule.}
{141}{}{Dík.}
{142}{}{Díky.}

{143}{}{Mìly by se nacházet v údržbì, hned vedle centra øízení dopravy.}
{144}{}{Oukej.}
{145}{}{Jo už vím.}

{155}{}{Jsi normální, chodit tady okolo bez uniformy? Padej se rychle pøevléct!}
{156}{}{Jestli tì seržant chytí bez uniformy, tak ti nakope prdel.}
{157}{}{Proè jsi bez uniformy?}

{158}{}{Do prdele! Byli jsme napadeni! Poplach!}
{159}{}{Vetøelci! Zavolejte stráže!}
{160}{}{Stráže! Vetøelci v komunikaèním centru!}

{161}{}{Co je? Byli jsme napadeni?}
{162}{}{Proè je poplach? Co se stalo?}
{163}{}{Co se to tu k èertu zase dìje?}

{164}{}{Jsem jenom technik, nestøílej po mì!}
{165}{}{Mùj úkolem není bojovat, jsem jen civilní technik!}
{166}{}{Tohle je laboratorní oblek a ne brnìní! Já k vojákùm nepatøím!}
