#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vítej èlovìèe. Jsem bojovník Xarn. Ty mì máš popravit?}
{101}{}{Ano.}
{102}{}{Ne, já bıt tady tì zachránit.}
{103}{}{Nevím. Vyvolenı chtít vìdìt proè ty tady.}
{104}{}{Ano, proto jsem tady.}
{105}{}{Ne, jsem tu, abych tì zachránil.}
{106}{}{Ještì nevím. Nejdøív chci vìdìt proè jsi tady.}

{107}{}{Nech se tedy stane to, co se musí stát. Ale nehodlám dát svùj ivot lacino. Tuhle bitvu si budeš pamatovat!}
{108}{}{Oukej.}
{109}{}{Poèkej. Vyvolenı si to rozmyslet. Proè ty tady?}
{110}{}{Jsem pøipraven. Skonèeme to.}
{111}{}{Poèkej minutku. Proè jsi tu?}

{112}{}{Tìko mùu uvìøit tomu, e voják Enklávy je tu proto, aby mì zachránil. Mnohem pravdìpodobnìjší je, e jsi pøišel, abys mi nejdøív dal nadìji a potom ji v miku rozprášil.}
{113}{}{Ne. Vyvolenı tì pøijít zachránit. Vìø.}
{114}{}{Vìø mi, opravdu tì pøicházím zachránit!}

{115}{}{Jsi má poslední nadìje. Tamhle ty dveøe vedou do ventilaèní šachty, která konèí v lese. Myslím, e bych zvládl vylézt tou šachtou nahoru a dostat se tak na svobodu, ale bohuel jsou ty dveøe zamèené a k jejich otevøení potøebuji klíè. Najdi klíè, odemkni ty dveøe a tím mi dáš svobodu.}
{116}{}{Oukej, já udìlat to.}
{117}{}{Vyvolenı o tom muset pøemıšlet.}
{118}{}{Jasnì, udìlám to.}
{119}{}{Budu o tom pøemıšlet.}

{120}{}{(Xarn se na tebe na chvíli upøenì zahledìl) No dobøe. Enkláva mì i mé lidi stvoøila jakoto rasu bojovnıch otrokù. Snaili se vylepšit naše intelektuální schopnosti tak, abychom byli schopni porozumìt jejich rozkazùm, ale abychom ještì nepoznali, e jsme otroci. Ale nepodaøilo se jim to. Jsme mnohem inteligentnìjší ne oèekávali.}
{121}{}{Rozhodli jsme se pøedstírat hlupáky, dokud se nám nenaskytne šance získat svobodu. A ta šance pøišla, kdy se Enkláva rozhodla nás otestovat tady na pevninì. Doktor Schreber byl sice proti tomuto rozhodnutí, ale byl pøehlasován.}
{122}{}{Schreber se s tím rozhodnutím nesmíøil a rozhodl se odjet na tuto základnu. Unesl mì a zaèal experimentovat a zkoumat moje opravdové vlastnosti. A byl úspìšnı. Jestlie oznámí Enklávì vısledky svého vızkumu, moji lidé budou pronásledováni a vyhubeni. Musím co nejdøíve utéct a varovat je.}
{123}{}{(Xarn se na tebe na chvíli upøenì zahledìl) Nemám, co bych ti øekl, èlovìèe. Ve tvé duši cítím zlo a tmu.}
{124}{}{Kdy doktor taková hrozba, proè ty ho nezabil?}
{125}{}{Táhni do horoucích pekel. Vyvolenı ti ustøelit prdel.}
{126}{}{Kdy je doktor pro tebe taková hrozba, proè jsi ho ještì nezabil?}
{127}{}{A je tedy po tvém. Chcípni, deathclawe.}

{128}{}{(povzdechnutí) Nakonec jsem se rozhodl to udìlat, i kdy si v zabíjení nelibuji. Ale profesor to zøejmì poznal a pøestal mì navštìvovat osobnì. Tu šanci jsem tedy propásl.}
{129}{}{Ty nebát se. Doktor po smrti. U nepodat ádnı hlášení.}
{130}{}{Díky za tvùj pøíbìh.}
{131}{}{U se nemusíš bát. Doktor je mrtvı a u nikomu ádné hlášení nepodá.}
{132}{}{Díky za ten pøíbìh. Bylo to zajímavé.}

{133}{}{Je mi líto, e zemøel ale asi je to tak lepší. Chci se tì zeptat jestli mi pomùeš utéct z tohohle místa. Ano?}
{134}{}{Ano, Vyvolenı ti pomoci.}
{135}{}{Bude o tom pøemıšlet.}
{136}{}{Ne, to neudìlat.}
{137}{}{Jo, udìlám to.}
{138}{}{Zatím ne, ale budu o tom pøemıšlet.}
{139}{}{Ne. Myslím, e se na tebe radši vybodnu.}

{140}{}{No dobøe... Poèkám tu dokud se nerozhodneš.}
{141}{}{OK.}

{142}{}{Dobøe... Nemám z tvého rozhodnutí radost, ale je to tvá volba. Kdyby sis to rozmyslel, budu tady èekat.}
{143}{}{Ahoj.}
{144}{}{Nashle.}

{145}{}{Chci se tì na nìco zeptat. Pomùeš mi odtud utéct?}
{146}{}{Jo, Vyvolenı ti pomoct.}
{147}{}{Budu pøemıšlet.}
{148}{}{Ne, to neudìlat.}
{149}{}{Ano, udìlám to.}
{150}{}{Ne, ale budu o tom pøemıšlet.}
{151}{}{Ne, to si nemyslím.}

{152}{}{Vítám tì. Jsi pøipraven na náš boj?}
{153}{}{Nechtít bojovat, chtít slyšet tvùj pøíbìh.}
{154}{}{Nechtít bojovat. Já tady, tì zachránit.}
{155}{}{Ne. Muset jít.}
{156}{}{Jo. Jsem pøipravenej.}
{157}{}{Opravdu nechci bojovat. Mùeš mi povìdìt tvùj pøíbìh?}
{158}{}{Jsem tady, abych tì zachránil, ne abych s tebou bojoval.}
{159}{}{Ne. Musím jít.}
{160}{}{V poøádku. Skonèeme to.}

{161}{}{Rád tì zase vidím. Zmìnil jsi názor? Pomùeš mi?}
{162}{}{Ano.}
{163}{}{Ne.}

{164}{}{Rád tì zase vidím. Zmìnil jsi názor? Pomùeš mi?}
{165}{}{Ano.}
{166}{}{Ne. Poøád o tom pøemıšlet.}
{167}{}{Ne. Nepomoct ti.}
{168}{}{Ne, poøád o tom pøemıšlím.}
{169}{}{Ne, nechci ti pomoct.}

{170}{}{Rád tì znovu vidím. Našel jsi klíè k tìm dveøím?}
{171}{}{Ano, hned ti otevøít.}
{172}{}{Ne, stále ho hledat.}
{173}{}{Jo našel jsem ho. Hned ti ty dveøe otevøu.}
{174}{}{Stále ho ještì hledám.}

{175}{}{Díky. Tohle ti nikdy nezapomenu.}
{176}{}{To bıt v poøádku.}
{177}{}{Není zaè.}

{178}{}{Ještì jednou díky, pøíteli. Jsem tvım dluníkem.}

{179}{}{Zdravím tì, èlovìèe. Základna spustila poplach. To jsi zpùsobil ty?}
{180}{}{Znovu tì zdravím. Základna spustila poplach. To je kvùli tobì?}
{181}{}{Jo, to zpùsobit Vyvolenı. Kdo ty a proè to chtít vìdìt?}
{182}{}{Jo, já bıt ta pøíèina. Proè ty se ptát?}

{183}{}{Jsem Xarn, bojovník. Dovol mi, abych se k tobì pøidal a po tvém boku bojoval za svobodu. Spolu máme šanci, ale sami... kdo ví?}
{184}{}{Pak mi tedy dovol, abych stál v boji po tvém boku. Spolu snad mùeme dosáhnout naší svobody. Ale sami... kdo ví?}
{185}{}{Ne se Vyvolenı rozhodnout, ty øíct mi proè ty tu?}
{186}{}{Hmm... tak jo. Ty jít se mnou. My bojovat spolu.}
{187}{}{Ty muset bojovat sám za sebe. Já odtud vypadnout.}
{188}{}{Ještì pøedtím, ne se rozhodnu, chci vìdìt, proè jsi tady?}
{189}{}{Dobøe. Teï jsme v tom spolu. Pøiprav si svoje paøáty a jdeme jim nakopat zadky!}
{190}{}{Kadı sám za sebe, jen Bùh za všechny. Já odsud padám.}

{191}{}{Hmm... no dobøe. Ty jít se mnou. My bojovat spolu.}
{192}{}{Ty bojovat sám za sebe. Já odtud pryè.}
{193}{}{Fajn. Jsme v tom spoleènì. Nabrus si svoje paøáty a jdeme jim nakopat zadky!}
{194}{}{Jsi v tom sám bráško. Já odsud mizím.}

{195}{}{Díky èlovìèe. Roztrháme Enklávu na kusy! A ije Grutharùv rod! Grrrrrrr!}
{196}{}{Oukej.}

{200}{}{[Více]}
{201}{}{Ano. Kdo jsi?}
{202}{}{Ano. Proè?}
{300}{}{No dobøe. Enkláva vytvoøila z mé rasy bojující otroky. Snaili se vylepšit naše intelektuální schopnosti tak, abychom byli schopni porozumìt jejich rozkazùm, ale abychom ještì nepoznali, e jsme otroci. Ale nepodaøilo se jim to. Jsme mnohem inteligentnìjší ne oèekávali.}
{301}{}{Rozhodli jsme se pøedstírat hlupáky, dokud se nám nenaskytne šance získat svobodu. A ta šance pøišla, kdy se Enkláva rozhodla nás otestovat tady na pevninì. Doktor Schreber byl sice proti tomuto rozhodnutí, ale byl pøehlasován.}
{302}{}{Schreber se s tím rozhodnutím nesmíøil a rozhodl se odjet na tuto základnu. Unesl mì a zaèal experimentovat a zkoumat moje opravdové vlastnosti. A byl úspìšnı. Jestlie oznámí Enklávì vısledky svého vızkumu, moji lidé budou pronásledováni a vyhubeni. Musím co nejdøíve utéct a varovat je.}

{500}{}{Jsi opravdovı pøítel našeho rodu. Snad se potkáme v klidnìjších dobách. Ale teï u musím jít a pøipravit svùj lid na válku.}
{501}{}{Utrhnu ti tvoje ruce a umlátím tì s nima.}
{502}{}{Chcípni, zrádnı èerve!}
{503}{}{Tohle tì bude zatracenì bolet.}

{600}{}{Spolu porazíme naše nepøátele.}
{601}{}{Ty mi je ukáeš a já je roztrhám.}
{602}{}{Je èas dát nìkomu po papuli.}

{700}{}{Vidíš deathclawa. Sleduje tì podivuhodnì inteligentníma oèima.}
{701}{}{Vidíš Xarna, deathclawa.}
{702}{}{Vidíš obyèejného deathclawa. Je to mohutnı tvor s ostrımi zuby a dlouhımi paøáty.}

{800}{}{Zabil jsi Xarna.}
{810}{}{Osvobodil jsi Xarna.}
{820}{}{Xarn se k tobì pøidal.}
