#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
# 0. Look
{100}{}{Vidíš závisláka.}
{101}{}{Tahle osoba je tìžce zdrogovaná.}
{102}{}{Zdá se, že v tìch drogách pìknì lítá.}
{103}{}{Zdá se, že v tìch drogách pìknì lítá.}
{104}{}{Vypadá pìknì blbì. Obáváš se, že nekomunikuje díky nìjaké droze.}
{105}{}{Už mìla lepší dny. Vypadá, jako když má všechno na salámu.}
{106}{}{Tenhle závislák vypadá jako žijící mrtvola.}
{107}{}{Vypadá to, že se ten závislák chystá vrhnout šavli.}

# 1. CF: Attacked by PC
{150}{}{Ta svìtla mì nièí!}
{151}{}{Všude zrùdy!}
{152}{}{Co to bylo?}
{153}{}{Krvácím?}
{154}{}{To snad nemùže být pravda.}
{155}{}{Pøestaò, èlovìèe!}
{156}{}{Tak pomùže mi nìkdo?}
{157}{}{Pomoc!}
{158}{}{Vypadni!}
{159}{}{Hlava mi tøeští!}
{160}{}{Nech mì o samotì.}

# 2. CF: Normal
{200}{}{Jéje, ty tak divnì temnì žhneš.}
{201}{}{Teda, ty jsi ale velký mládì.}
{202}{}{Neøíkej jim, co víme, tady ne.}
{203}{}{Ahhh...}
{204}{}{Vidíš mì?}
{205}{}{Buï velmi, velmi potichu. Lovím králíky.}
{206}{}{Jak si našel cestu odsud?}
{207}{}{Pssst, schovávám se.}
{208}{}{Bìžím rychleji než vlk!}
{209}{}{Cítím se jako živý!}
{210}{}{Rve mi to žíly...}
{211}{}{Pøímo tam, mládì.}
{212}{}{Oooohhh, cítíš tu sílu?}
{213}{}{Jéje, ty žhneš...}
{214}{}{Miluju tì, èlovìèe!}
{215}{}{Život byl ke mì tak laskavej. K tobì taky?}
{216}{}{Mròous lítá v noci.}
{217}{}{Pozdrav se s mým malým pøítelem.}
{218}{}{Chlapèe, jsem ospalý...}
{219}{}{Už jsi vidìl mého psa?}
{220}{}{Pssst, je právì za tebou...}
{221}{}{Moje!}
{222}{}{Oooh, moje hlava.}
{223}{}{Všechno mì bolí.}
{224}{}{Dostávám zimnici.}
{225}{}{Oh, potøebuju nìco víc.}
{226}{}{Potøebuju nìjaký povzbuzovadlo.}
{227}{}{Nemùžu èekat, potøebuju to hned.}
{228}{}{Tak ty jsi mi na to skoèil?}
{229}{}{Ah, nech mì o samotì.}
{230}{}{Dostal jsem tøes, èlovìèe.}
{231}{}{Nesnáším tuhle èást.}
{232}{}{Chci jen umøít.}
{233}{}{Nemáš nìjaký svinstvo?}
{234}{}{Nemùžu to moc dlouho vydržet.}
{235}{}{Myslím, že mám horeèku.}
{236}{}{Myslím, že hodím šavli.}
{237}{}{Možná kdybych jen spal...}
{238}{}{Dostal jsem tøes, dámo.}

# 3. BGF: Hostile
{300}{}{Je to krev?}
{301}{}{Ach! Krvácím? Necítím nic!}
{302}{}{To štípe.}
{303}{}{Kdo to udìlal?}
{304}{}{Co se dìje?}
{305}{}{Krvácím... Myslím.}
{306}{}{Oh, ta bolest.}
{307}{}{Teï opravdu potøebuju nìjaký povzbuzovadlo.}
{308}{}{Nech mì umøít.}

# 4. BGF: Normal
{350}{}{Ahhhh...}
{351}{}{Já se vznáším...}
{352}{}{Mám sílu!}
{353}{}{Zdravím, pane Kytièko.}
{354}{}{Všechny barvy...}
{355}{}{Mnohem vyšší pøítel vidìt to nebe?}
{356}{}{Oni neposlouchaj..}
{357}{}{Kde to jsem?}
{358}{}{Tady to je!}
{359}{}{Ne proboha! Stùjte! Poèkejte...! Ok, jdìte dál.}
{360}{}{Tam, tam... ahhh...}
{361}{}{Yea, baby!}
{362}{}{Co to bylo?}
{363}{}{Sasha? Kde jsi Sasho?}
{364}{}{Barvy blednou!}
{365}{}{Mami?}
{366}{}{Hej! Vypadni ode mì! Oh...}
{367}{}{Nedìlej to!}
{368}{}{Nevidím... zase.}
{369}{}{Potøebovat...}
{370}{}{Dostat víc...}
{371}{}{Tam? Ne.}
{372}{}{Ne. Nemohu to najít.}
{373}{}{Zastav to.}
{374}{}{Ugh.}
{375}{}{Oh, ta bolest.}
{376}{}{<kašel> <kašel> <kašel>}
{377}{}{Ooh, moje hlava!}
{378}{}{Kam jsem položil mojí tajnou skøíòku?}

# 5. Self Initiated: Attacking Player
{400}{}{Démon!}
{401}{}{Nepøítel jde na nás!}
{402}{}{Ty vrahu! Jsi zavraždìn svým synem!}
{403}{}{Zrùda! Zabij to!}
{404}{}{Ah! Pargasraka!}
{405}{}{Ty nohy vod krysy chodí! Ahhh!}
{406}{}{Nesejmeš to ze mì!}
{407}{}{Dej to zpátky!}
{408}{}{Ne!!!}
{409}{}{Moje rodina!}
