#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš ducha!}
{101}{}{Vidíš Annu, ducha.}

{150}{}{Je to duch. Nic, co bys mohl vidìt každý den.}
{151}{}{Vypadá trochu utrápenì.}
{152}{}{[Mluv]}
{153}{}{Oh, ta bolest! To tak pálí!}
{154}{}{Co se dìje?}
{155}{}{Kdo jsi?}
{156}{}{Táhni, ty hnusný duchu!}
{157}{}{Zastavím a klepu na každé dveøe, ale nikdo nepøichází, nikdo neslyší.}
{158}{}{Já tì slyším. Co se dìje?}
{159}{}{Myslím, že byste mìla vypnout svùj Mizík, madam.}
{160}{}{Kde to je? Nemohu to najít! Jsem ztracena! Ach...}
{161}{}{Co hledáš? Tøeba ti mohu pomoci.}
{162}{}{Mìla bys koneènì pøestat kvièet a naøíkat, a zaèít dìlat nìco rozumného.}
{163}{}{Mùj amulet! Je pryè. Zlodìj! Zlodìj!}
{164}{}{Já? Jen tu tak stojím. Já za to nemùžu.}
{165}{}{Mohu ti pomoct ho najít?}
{166}{}{Oh, krutý osud.}
{167}{}{Neslyšíš mì, že ne?}
{168}{}{Pozdìji, duchu.}
{169}{}{Nashle. Pokusím se ti pomoci.}
{170}{}{Mùj amulet! Dej mi ho!!! Oh!!!!}
{171}{}{V žádném pøípadì! Táhni do pekel. Já ho našel døív.}
{172}{}{OK. Tady je.}
{173}{}{Tady. Mùžeš odpoèívat v pokoji.}
{174}{}{OK.}
{175}{}{Ne.}
{176}{}{Mùj amulet, mùj amulet! Už jdu, tatínku! Už jdu!}
{177}{}{Sbohem.}
{178}{}{Poèkej! Nechoï!}
{179}{}{Jdi ke svìtlu.}

{200}{}{Kde to jen mùže být?}
{201}{}{Ohhh.}
{202}{}{Mami? Tati? Kde jste?}
{203}{}{Nemùžu ho najít!}

{500}{}{Mami... Tati... už jdu...}
{501}{}{Je to tak jasné...}
{502}{}{Babi já tì vidím...}
{503}{}{Oh, to je milý  Mr. Cain. Je skvìlé vás zase vidìt...}

{550}{}{Tento dùm je opìt èistý.}

{560}{}{Krotitel duchù!}
{561}{}{Ug.}