#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš malıho chlápka s mohutnım knírem.}
{101}{}{Vidíš Velkého Ananiase.}
{102}{}{Vidíš malého kníratého mue, kterı se snaí bıt nenápadnı.}
{103}{}{Ty! Co chceš bıvalému Velkému Ananiasovi?}
{104}{}{Vypadni odtud!}
{105}{}{Jdi nièit obchody nìkomu jinému.}
{106}{}{Zkoušej to na nìkoho jiného.}
{107}{}{U jsi mi uškodil, jak jsi jen mohl.}
{108}{}{Tak jdi pryè, u jsi mi nadìlal dost škody.}
{109}{}{Mám hlad jako herec.}
{110}{}{Jak teï uivím svojí rodinu?}
{111}{}{Narodil jsi se s pøíliš malım srdcem.}
{112}{}{Ne, mùj pøíteli, MUMIE! Pøímo ze starobylého Egypta do Pustıch pískù! Exkluzivnì pro tebe, abys vìdìl!}
{113}{}{OK, pøijímám. Kolik jsi vidìl vysušenıch mrtvol?}
{114}{}{(pro sebe) Hmm, popisuje tu mumii, jako by popisoval ghoula. Oukej, rád se na to podívám -- kolik?}
{115}{}{U jsem vidìl dost mrtvol. Nashle.}
{116}{}{Dobrı den, vítej, zdravím! Jsem Velkı Ananias (lehce se uklání, provázejíce to rozmáchlım gestem). Pøináším záhady od blízkého i vzdáleného pøítele. Záhady ze svìta leícího za naším svìtem... záhady Podsvìtí.}
{117}{}{Vrame se zpìt k poznání záhad Podsvìtí Velkého Ananiase, ano?}
{118}{}{Jakıch záhad?}
{119}{}{Á, rád vás poznávám pane Velkı Anál... nìco.}
{120}{}{Hmm, záhady mì dost unavují, radìji pùjdu. Sbohem.}
{121}{}{Zva to!}

{127}{}{Dnes mám u sebe v pokoji nìco moc zajímavého. Jenom pro tebe... nefalšovaná egyptská mumie!}
{128}{}{Mumie?}
{129}{}{Mumie? Hmm, divil bych se, kdyby mohla bıt... Ne, nikdo není pøece tak hloupı.}
{130}{}{Takovı druh vìcí není pro mì to pravé oøechové. Z mrtvol mi bìhá mráz po zádech.}
{131}{}{Mimo to, blokuješ platící zákazníky.}
{132}{}{Nemyslím, e je toto pro tebe.}
{133}{}{Proè jsi nevzal svùj malı kmen nìkam jinam?}
{134}{}{To opravdu není pro tebe.}
{135}{}{Aha, hmmm, co takhle (ukazuje prstem) vypadnout?}
{136}{}{Èlovìku tvé úrovnì velmi rád ukáu tento unikátní a historickı vzorek za pouhıch 25 dolarù.}
{137}{}{OK, vykašlu se na ghoula. A teï... mi uka mumii!}
{138}{}{Nechci tolik utrácet. Myslím, e to pøeiju, kdy tu vìc neuvidím.}
{139}{}{Jednoduše otevøi víko sarkofágu a ta nádherná mumie se ti ukáe ve své starobylé slávì. Ale, prosím, nedotıkej se jí a nefo s bleskem.}
{140}{}{Vıbornì.}
{141}{}{Jdi tam! MUMIE! (dveøe sarkofágu se otevírají, aby se ukázala vysušená mrtvola, která vypadá jako obyèejnı ghoul, stojící v chudì zdobeném, otluèeném a popraskaném papírovém sarkofágu.)}
{142}{}{Jdi tam! Pøedstavuje se MUMIE (dveøe rakve se zaskøípìním otevírají a odkrıvají pravou egyptskou mumii, stojící v sarkofágu, vypadajícím jako z èistého zlata!)}
{143}{}{Hej, poèkej minutku. To není mumie. Je to ghoul. WOODY! Hej WOODY! Jsi to ty?}
{144}{}{Pøipomíná mi ghoula.}
{145}{}{Tohle e je mumie? Nemùu uvìøit, e uvidìt šest stop vysokı kus pitomce mì stálo 25 babek. Sbohem.}
{146}{}{Ach, to je fantastické... Myslím. (na chvíli se díváš na Mumii velmi soustøedìnì). Uh, dík, sbohem.}
{147}{}{(Mumie, funí, malátnì se protahuje, a potom na tebe kouká ospalım pohledem) Dobrı den. (øíká ospale)}
{148}{}{A do prdele! To je Woody! Bì Woody, bì pro to! Dobrá, uh, dokulhej pro to pøeci! Jdi Woody jdi!}
{149}{}{Ujišuji tì, e je to mumie fakticky, opravdová.}
{150}{}{Nemyslím, e ti vìøím. Poèkej, nìco zkusím. WOODY! Hej WOODY! Jsi to ty?}
{151}{}{Dobrá, kdy to øíkáš. Ale myslím si, e to urèitì vypadá jako obyèejnı ghoul. Sbohem.}
{152}{}{(Woody -- tohle je ve skuteènosti Woody a ne mumie, kdo tu teï stojí pøed tebou -- protrhl stìnu papírového sarkofágu, zavøískl a vystøelil ze dveøí, zanechávajíc po sobì jen spìšné Díky cizinèe!" a útrky toaletního papíru, kterım byl omotanı.)}
{153}{}{Ha! To jsem vìdìl!
 V tomhle mìstì si vyøízenej. U nejsi ádnej Velkej Ananis, ale jen další hovno.}
{154}{}{Ale bì Woody! Aha! Je mi to jasnı }
{155}{}{(Velkı Ananias krèí rameny) Vìdìl jsem, e bych mìl místo toho vyzvednout jednohlavıho intelektuála. Tak, zpátky ke kreslícímu prknu.}
{156}{}{Jedno-hlavı intelektuál? Jistì, kdo by tomu kdy uvìøil! Sbohem, ty Šarlatáne.}
{157}{}{Vzbudil si Woodyho, ghoula a osvobodil si ho ze zakletí mumifikace.}
{158}{}{Myslím, e bych si radìji vyslechl duchaøskou historku.}

{200}{}{Obyèejnému smrtelníkovi není souzeno, aby znal vìci, které znám já. Aiiieeee! Nyarloth... Oh, promiòte (heh, heh). Byl jsem chvíli myšlenkami nìkde jinde. Znám pøíbìhy o Duchovi, kterı to strašení bere pìknì od podlahy, stejnì tak jako tahle nefalšovaná Egypt-s-ká mumie, kterou vidíš pøímo tady v tomto nádherném sarkofágu.}
{201}{}{Vyprávìj o té mumii. Umírám nedoèkavostí, dovìdìt se o ní nìco víc.}
{202}{}{S chutí si tu duchaøskou báchorku poslechnu. Uh, smím k tomu prosit šálek dobrého horkého kakaa?}
{203}{}{Nemyslím, e mùu ztrácet èas èímkoliv, co mi nabízíš na prodej.}

{300}{}{Tak, podívej se, (blíí se k tobì) jednou tam byla mocná královna, která vládla všem okolním mìstùm. Udrovala svùj trùn pomocí síly zvláštního amuletu, kterı stále nosila kolem krku. Skvìlá vìc, ne?}
{301}{}{Uh, ano. Samozøejmì. Tak ta princezna mìla *magickı* amulet. Oh, tak pokraèuj. Jen nemohu u déle vydret takové napìtí (zív).}
{302}{}{OK. Myslím, e víc u toho slyšet nemusím. Sbohem.}

{400}{}{Tak, budu pokraèovat ve vyprávìní. Tak, zlı kouzelník otrávil mladou princeznu a vzal jí amulet. Od té doby se vdy v hodinu duchù prochází po vedlejší místnosti. Proto nechávám dveøe zamknuté. Pìknì strašidelné, co?}
{401}{}{Duch princezny bez amuletu ve vedlejší zaneøádìné místnosti? Jen tak? Nemohu uvìøit, e to je jen pøíbìh.
 Radìji mi povìzte o té pitomé mumii, kterou, jak se zdá, tady máte.}
{402}{}{OK. Myslím, e jsem ji slyšel dost. Nashle.}
