#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
# 8. BF: Hostile Primitive
{245}{}{Ticho! Oni blízko.}
{246}{}{Zabít špatnı èlovìk.}
{247}{}{Nebrat mì rodina.}
{248}{}{Já chránit rodina.}
{249}{}{Nesmìt najít nás.}
{250}{}{Oni špatnı lidé.}

# 9. BF: Hostile Nomad
{260}{}{Otrokáøi pøicházejí. Všichni buïte zticha.}
{261}{}{Pøipravte se. Myslím, e jsou u blízko.}
{262}{}{Nevzdám se bez boje.}
{263}{}{Nikdy nás nezotroèí.}
{264}{}{Zaplatí za to, otrokáøi.}
{265}{}{ádnı otrokáø mi neveme mojí rodinu.}
# looks
# primitive
{100}{}{Tenhle mu vypadá docela silnì a ostraitì.}
{101}{}{Zdá se bıt silná navzdory své postavì.}

# nomads
{200}{}{Zdá se bıt dìsnì hubenı, ale rozzlobenı.}
{201}{}{Ten vypadá, e má ukrutnou sílu.}
{202}{}{Pohybuje se velmi rychle.}

{210}{}{Nezdá se, e by se kdy koupala.}
{211}{}{Vypadá jako silná bojovnice.}
{212}{}{Ten se zdá, e nebude dìlat potíe.}

# 12. Combat Float: Hostile Primitive
{300}{}{Teï zhyneš!}
{301}{}{Já zabít!}
{302}{}{Ty nezranit rodinu!}
{303}{}{Ty nevzít rodinu!}
{304}{}{Já ochránit!}
{305}{}{Zraním tì!}
{306}{}{Ty zaplatíš!}
{307}{}{Zemøi!}
{308}{}{Chystám se tì zranit.}

# 13. Combat Float: Hostile Nomad
{350}{}{Nepovede se ti získat mojí rodinu, otrokáøi!}
{351}{}{Zhyò, otrokáøská špíno!}
{352}{}{Za to zaplatíš, ty bastarde!}
{353}{}{Budu bojovat do poslední kapky krve za svojí rodinu!}
{354}{}{S tímhle odtud neodejdeš!}
{355}{}{Odtud se s mımi pøáteli nedostaneš!}
{356}{}{Chystám se tì za to dostat!}
{357}{}{Bùh zatra otrokáøe!}
{358}{}{Za to zaplatíš!}
