#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš patrona Díry.}

{150}{}{Tenhle chlápek není moc atraktivní.}
{151}{}{Tenhle chlapík má jen jeden zub.}
{152}{}{[MLUVIT]}
{153}{}{Tvoje žena je jistì pìkná!}
{154}{}{Vypadni odtud.}
{155}{}{Líbí se ti, huh?}
{156}{}{Ano líbí.}
{157}{}{Ju.}
{158}{}{Urèitì bych jí rád dostal.}
{159}{}{Jdi rovnou za nosem.}
{160}{}{OK. Bude to $50.}
{161}{}{Jistì, ale bude tì to stát .}
{162}{}{V žádným pøípadì! Vypadni odtud!}
{163}{}{OK.}
{164}{}{Ne.}
{165}{}{Dobrá! Tìï jdi s Billym, zlato.}
{166}{}{Teï odejdi.}
{167}{}{Díky. Sbohem.}
{168}{}{Sbohem.}
{169}{}{Ou, sakra.}
{170}{}{[hotovo]}
{171}{}{Jsem pøímo nejlepší ze všech.}
{172}{}{Vrátím se.}
{173}{}{OK.}
{174}{}{Jsi hodnì pìkná holka.}
{175}{}{Dej mi pokoj.}
{176}{}{Dej mi $200 a mùžeš se mnou strávit nìjaký èas.}
{177}{}{Stojím $50, Macu.}
{178}{}{He, he. Díky.}
{179}{}{Nemám dost penìz.}
{180}{}{Ok, tak teda $50.}
{181}{}{Pro tebe dost špatný.}
{182}{}{Nìkde tady kolem se potkáme.}
{183}{}{Neotravuj mì. Vyhlížím nìjakou fajnovou kùstku.}
{184}{}{Hodnì štìstí. Budeš ho potøebovat.}
{185}{}{Co si myslíš že jsem, sekaný játra?}
{186}{}{Sbohem.}
{187}{}{Oooh. OK. Sbohem.}
{188}{}{(prohlíží si tì odzhora dolù) Ne. Mám rád sekaný játra.}
{189}{}{To nemuselo být!}
{190}{}{Promiò, už musím jít.}
{191}{}{Škoda. Jsi rozkošný.}


{203}{}{Chci svoje peníze zpátky.}
{204}{}{Nedám ti nic, leda tak kulku mezi oèi.}
{205}{}{OK, tak dìlej.}
{225}{}{Nemám to.}

{206}{}{Hej.}
# Oh come on, give (player_name) another chance here.
{207}{}{No tak, dej }
{208}{}{ ještì šanci.}
{209}{}{Vidím, že už mi nic nechceš tak odcházím.}

{210}{}{Dal jsem ti šanci, ale ty jsi jí zahodil.}
{211}{}{Oukej, tak mi dej ještì jednu.}
{212}{}{To je mùj chlapec.}
{213}{}{Pøesto tì musím zabít.}

{220}{}{Hej, Frankie, chci se jenom na chvíli vypùjèit zadní pokoj.}
{221}{}{Hej, Frankie, koukni co jsem urval.}
{222}{}{Uh, Frankie, když mì nìkdo... uh... bude hledat, budu vzadu.}

{223}{}{Následuj mì.}
{224}{}{Bude to muset poèkat. Pohovoøíme si pozdìji.}


# 10.
{300}{}{Sakra, já jsem ale zasranej odpad.}
{301}{}{A jéje.}
{302}{}{Bylo to... bylo... hezký!!!}
{303}{}{Mohl sis poøádnì zavaøit.}
{304}{}{Sakra, udìlalo mi to pìšinku ve vlasech -- a to jich mám jen pár.}
{305}{}{S Davem to jistì trochu tøíská.}

# 11.
{320}{}{To není špatné... To není špatné...}
{321}{}{Mohl bych dokonce za to zaplatit ještì jednou.}
{322}{}{Mmmm...}
{323}{}{Není to špatné, vùbec to není špatné.}
{324}{}{Budeme to muset udìlat ještì jednou a zapracovat na naší... pružnosti.}

# 12.
{350}{}{Vypadá to, že znovu získávám Handy.}
{351}{}{Nenech si cestou ven nakopat svojí VYSCHLOU PRDEL!}
{352}{}{Je èas ukonèit to, co jsi dokonce ještì nemohl zaèít!}

# 13.
{370}{}{Oh, je to pìkné.}
{371}{}{Billymu se to líbí.}
{372}{}{Ou jé.}
{373}{}{Hezké.}
{374}{}{Jeezus a ramona.}
{375}{}{Dobrý bože.}
{376}{}{Mìl bych zabalit krabici tkaniny.}
{377}{}{Hmmm, koho si teï mám pøedstavit.}

# 14.
{390}{}{Hej, copak nevidíš, že mám plno práce?}
{391}{}{Hej, vypadni.}
{392}{}{Hej, ty to za mì neudìláš, tak neotravuj.}
{393}{}{Mùžeš mi dát mop a vrátit v 5?}

{400}{}{Billy, bude lepší, když nebudeš znovu dìlat zmatky v téhle záležitosti!}
{401}{}{Hej Billy, potøebuješ mop?}
{402}{}{Billy, tvùj chcípák ti zase nestojí. ZNOVU!}
{403}{}{Jo Billy, nezapomeò si vymìnit spodky.}
{404}{}{Billy, už jsi jedl koláèky?}

{410}{}{Uhhh.}
{411}{}{Sakra}
{412}{}{Jooo}
{413}{}{On, on, onnn...}
{414}{}{Huh?}

{500}{}{*Probodnout, probodnout* Eccchhhh...}

{510}{}{Hej kamarádíèku, máš zájem pronajmout si jednoho fajn hošu?}
{511}{}{Nemùže to poèkat? Dal bych si panáka.}
{512}{}{Dobrá, jestli chceš se mnou mluvit, budu v Díøe.}
{513}{}{Co takhle se setkat v Díøe, tam tì pozvu na panáka?}

{520}{}{Promiò, ale pospíchám domù. Pravì jsem sehnal nové porno.}
{523}{}{Jsem, uhhh, unavený, nechte mì, prosím, jít domù a spát...}
{522}{}{Zajdu k Davovi. Má u sebe celé pornografické køídlo!}

{530}{}{Uhhh, ne díky. Nemám peníze na to, abych je za to zase vyhodil.}

{540}{}{Nu dobrá, zkusím to znovu.}