#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš èlena Cechu otrokáøù.}

{150}{}{Vidíš Metzgera, šéfa Cechu otrokáøù.}
{151}{}{[MLUVIT]}
{152}{}{Stráe! Zakroète!}
{153}{}{[hotovo]}
{154}{}{Vrate se ráno, zatracenì! Pracuju pøes den.}
{155}{}{[hotovo]}
{156}{}{Co je? Zaèínáš mì pìknì štvát.}
{157}{}{Rád bych se omluvil.}
{158}{}{Promiòte, pøedtím jsem byl zdrogovanej. Nemyslel jsem to tak.}
{159}{}{Tak, co máš za problém?}
{160}{}{Rád bych se vás na nìco zeptal.}
{161}{}{Zøejmì mám. Nashle.}
{162}{}{Blé.}
{163}{}{Je na to u pøíliš pozdì. Vypadni.}
{164}{}{Prosím, prosím, prosím, omlouvám se.}
{165}{}{Oh dobrá, zkusil jsem to.}
{166}{}{Já ti ukáu!}
{167}{}{Dobrá, dobrá. Omluva se pøijímá.}
{168}{}{Skvìlé. Mohu vám poloit nìkolik otázek?}
{169}{}{Jsem rád, e jsme to vyøídili. Uvidíme se pozdìji.}
{170}{}{Dobrı den. Rád tì vidím.}
{171}{}{Ahoj Metzgere. Musíme si promluvit.}
{172}{}{Ty taky. Sbohem.}
{173}{}{Blurp.}
{174}{}{Jsem Metzger, šéf Cechu otrokáøù. Co potøebuješ?}
{175}{}{Ano, mám nìkolik otázek.}
{176}{}{Ne díky. U pùjdu.}
{177}{}{Swavuh???}
{178}{}{Odejdi prosím. Hned.}
{179}{}{Nebo co?}
{180}{}{Dobrá. Ale vrátím se!}
{181}{}{OK. Sbohem.}
{182}{}{Co bys rád vìdìl?}
{183}{}{Nìco o obchodníkovi Vicovi...}
{184}{}{Mohu se pøipojit k Cechu otrokáøù?}
{185}{}{Ráda bych prodala mého manela do otroctví.}
{186}{}{Rád bych prodal svou enu. Kolik?}
{187}{}{Rád bych prodal tady jednoho z mıch pøátel.}
{188}{}{Øekni mi nìco o Cechu.}
{189}{}{Jaká mìsta kupují vaše otroky?}
{190}{}{Rád bych koupil otroka.}
{191}{}{Hledám Vault 13. Slyšel jsi o nìm?}
{192}{}{Metzger? To zvláštní jméno.}
{193}{}{Nic. Musím jít.}
{195}{}{Pochází ze starého jazyka, z doby pøedváleèné nebo tak nìjak.}
{196}{}{Metzger znamená øezník. Trefné, co myslíš?}
{197}{}{To bylo jméno mého pradìda. On pocházel odnìkud z vıchodu. Pøes velkou loui.}
{198}{}{Èetl jsem nìjakou knihu o Metzgerovi. Byl prezidentem, nebo co.}
{199}{}{Podívejme kdopak to mluví.}
{200}{}{Je to Germen, German, Garmen, nebo co. Starobylı jazyk, z doby dávno minulé.}
{201}{}{I ty, Brute?}
{202}{}{Aha. Mám ještì otázku.}
{203}{}{To je ta nejblbìjší vìc, co jsem kdy slyšel.}
{204}{}{Fascinující. Pùjdu.}
{205}{}{Naše mise poskytuje spolehlivou a vysoce kvalitní pracovní sílu, aby uspokojila stále rostoucí poptávku ve vìtších mìstech. Chtìl by ses pøidat?}
{206}{}{Jistì. Zní to skvìle.}
{207}{}{V ádném pøípadì.}
{208}{}{Vrátím se k tomu. Jaká mìsta kupují vaše otroky?}
{209}{}{Promiò, ale to je interní záleitost.}
{210}{}{OK. Naverbuj mì.}
{211}{}{Ne! Vy chlapi jste nemocní lidé!}
{212}{}{Uváím to. Mám ještì nìkolik otázek.}
{213}{}{Hmm, vrátím se pozdìji.}
{214}{}{Musíme ti udìlat malou znaèku na tvém pøedloktí, aby byla jasná tvoje pøíslušnost k cechu. Jsi pøipraven?}
{215}{}{Zní to skvìle! Udìlejte to!}
{216}{}{Rozmyslel jsem si to. Mùu se zeptat na nìco jiného?}
{217}{}{Teï nemám èas. Musím jít.}
{218}{}{Vítej v Cechu!}
{219}{}{Skvìle, mám otázky!}
{220}{}{OK, díky. Vrátím se.}
{221}{}{Vault 13? Ne. Poèkej... Myslím Vic je z Vault City. Moná, e on nìco ví.}
{222}{}{Ano a kde to je?}
{223}{}{Ne. Aèkoliv mám jinou otázku.}
{224}{}{Ne, nevadí.}
{225}{}{Prodáváme vìtšinu našich otrokù do Vault City a do New Reno. New Reno je
 jihovıchodnì odtud a vìtšina Denù s ním obchoduje.}
{226}{}{Kde je Vault City?}
{227}{}{Mám víc otázek.}
{228}{}{Díky, u musím jít.}
{229}{}{Vault City je vıchodnì odtud, a potom trochu na jih. Vic je odtamtud.}
{230}{}{Mám ještì otázky.}
{231}{}{Díky; u jdu.}
# Hmm, looks like a healthy slave. I'll give you [x] coins.
{232}{}{Hmm, vypadá jako zdravı otrok. Dám ti }
{233}{}{ mincí.}
{234}{}{OK! Je ujednáno.}
{235}{}{Uh, nevadí.}
{236}{}{V ádném pøípadì! Chci dvojnásobek!}
{237}{}{Jsi pìknej vydøiduch. Tady jsou tvoje peníze!}
{238}{}{Díky. Chci se ještì zeptat.}
{239}{}{Díky. Sbohem.}
{240}{}{Ještì nìco?}
{241}{}{Ano, mám dotaz.}
{242}{}{Urèitì ne. Sbohem.}
{243}{}{Kterého "pøítele" prodáváš?}
{244}{}{Um, to je jedno.}
# Interesting. I'll give you [x] coins.
{245}{}{Zajímavé. Dám ti }
{246}{}{ mincí.}
{247}{}{Prodáno!}
{248}{}{Ne, díky.}
{249}{}{Chci víc penìz!}
# Alright, I'll give you [x] but no more!
{250}{}{Dobrá, dám ti }
{251}{}{ , ale ne více!}
{252}{}{Prodáno!}
{253}{}{Není to dost dobrı.}
{254}{}{Je to moc málo. Odcházím.}
{255}{}{Co chceš Vicovi? Je to teï mùj majetek. Nemìl se mnou vydrbat.}
{256}{}{Rád bych ho koupil.}
{257}{}{Proè ho tady dríš?}
{258}{}{Nic. Nevadí.}
{259}{}{U není na prodej.}
{260}{}{Proè ne?}
{261}{}{Oh, ok.}
{262}{}{Bude stát $2000.}
{263}{}{Tady jsou tvoje peníze.}
{264}{}{To je moc. Moná pozdìji.}
{265}{}{Cena je $1000.}
{266}{}{Tady jsou tvoje peníze.}
{267}{}{Teï nemám tolik u sebe. Sbohem.}
{268}{}{Naše rádio je rozbité a on je schopen ho opravit.}
{269}{}{Aha.}
{270}{}{Nemáš peníze!}
{271}{}{To je pro mì zlé. Mùu se tì na nìco zeptat?}
{272}{}{Promiò, já se vrátím.}
{307}{}{Jak se odvauješ pøijít znovu poté co jsi osvobodil své bratry bìhem Honu na otroky! Stráe! Zatknìte ho!}
{308}{}{[hotovo]}
{309}{}{Vıbornì! Cestování tam a zpìt ti mùe trvat nìkolik dní. Jsi pøipraven vyrazit?}
{310}{}{Ne. Vrátím se.}
{311}{}{Ano jsem pøipraven. Pojïme.}
{312}{}{Aaa, jsi zpìt z Honu na otroky. Podívej se, jak se ti vedlo...}
{313}{}{[více]}
{314}{}{[více]}
{315}{}{Zabil jsi potencionální otroky! Mrtví mu nám nepøinese ádné pøíjmy! Zabíjej jenom ty, kteøí jsou hrozbou, ti ostatní jsou neškodní.}
{316}{}{[více]}
{317}{}{Nepøivedl jsi skoro ádnı otroky! Co to s tebou k èertu je? Tady se snaíme peníze vydìlat, ne prodìlat.}
{318}{}{[více]}
{319}{}{Pøese všechno, vedl sis dobøe. Pracuj i nadále dobøe a já tì tu udrím.}
{320}{}{Díky. Budu.}
{321}{}{Nevím, jestli se mi to tolik líbí.}
{322}{}{Potøebuješ zlepšit svojí techniku získávání otrokù.}
{323}{}{Pokusím se.}
{324}{}{Omlouvám se za své nevalné vystoupení.}
{325}{}{Domnívám se, e jsem dost dobrı.}
{326}{}{Zatracenì! Vedl jsi si otøesnì. Snaíš se mì zruinovat? Pøíštì si dej vìtší pozor.
 Nemusíš je všechny pobít! Pobij jenom ty vzpurnı. Ty bezbrannı nechej do sbírky.}
{327}{}{Omlouvám se, Metzgere.}
{328}{}{Hej, je to fuška, bıt Otrokáøem!}
{329}{}{Rád bych vidìl, e si vedeš líp.}
{330}{}{Rád bych pokraèoval v honu na otroky.}
{331}{}{Zatracenì! Nesnáším, kdy ztratím nìjakého èlena cechu bìhem nájezdu. Pokuste se krıt si záda!}
{332}{}{Pøesto jste si vedli dobøe. Tady je $}
{333}{}{ jako stimul, abyste i nadále odvádìli dobrou práci.}