#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš stráž.}

{150}{}{Tato stráž hlídá starý kostel.}
{151}{}{[MLUVIT]}
{152}{}{Jak se ještì odvažuješ tady ukázat svùj ksicht!}
{153}{}{[Hotovo]}
{154}{}{Ho! Nikdo v noci nevstoupí do skladu rodiny Wrightových!}
{155}{}{Pan Wright mì sám poslal na pochùzku. Jestli o tom nevíš, tak je to špatný.}
{156}{}{Vrátím se zítra.}
{157}{}{Potøebuju se tam teï dostat.}
{158}{}{(Dívá se nervóznì) Promiòte... já nevím. Máte nìjaké dokumenty?}
{159}{}{Prosím! Umíte èíst?}
{160}{}{Ne, žádné mi nedal.}
{161}{}{Nechal jsem je tam spolu s mou stráží. Jdu je vyzvednout.}
{162}{}{Nemùžete tam bez dokumentù.}
{163}{}{Zde je má autorizace! Útok!}
{164}{}{Já se vrátím.}
{165}{}{(Rozpaèitì) Ne...um...v poøádku, jen pokraèujte...}
{166}{}{Díky.}
{167}{}{To je dost.}
{168}{}{Co vy lidi chcete?}
{169}{}{Potøebujeme jít dovnitø.}
{170}{}{Poslal nás sem šéf.}
{171}{}{Byl bych o tom musel nìco slyšet, kdyby sem byla poslaná skupina. Jdìte pryè!}
{172}{}{Jdìte, nebo budete o hlavu kratší!}
{173}{}{Oukej, oukej; už jdeme.}
{174}{}{Co tu pohledáváš?}
{175}{}{Potøebuju se dostat dovnitø.}
{176}{}{Poslal mì sem šéf s oficiálním posláním. Stùj stranou!}
{177}{}{Nebo ti useknu hlavu.}
{178}{}{Promiòte, to je omyl.}
{179}{}{Ještì jednou dobrý den. Mùžete jít.}
{180}{}{Díky.}
{181}{}{Hej, vypadni od tìch dveøí!}
{182}{}{Nedotýkej se tìch dveøí, jestli nechceš mít problémy.}
{183}{}{Ještì tì uvidím u tìch dveøí a vpálím ti kulku mezi oèi.}
{184}{}{Hej, co si vlastnì myslíš, že dìláš?}
{185}{}{Mám tì až po krk.}
{186}{}{Promiò, mùžu tì pustit dál, ale tví pøátelé budou muset poèkat venku.}
{187}{}{Jen jeden z vás mùže jít dovnitø.}

{200}{}{Dobrý veèer.}
{201}{}{Dobré odpoledne.}
{202}{}{Dobré ráno.}
{203}{}{Jen dokonèi svùj úkol, díky.}

{250}{}{Víš kamaráde, už jsi mì neuvìøitelnì sral!}
{251}{}{Víš dìvko, už jsi mì neuvìøitelnì srala!}
{252}{}{[KONEC]}
