#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
# 0. Look
{100}{}{Vidíš obèana Denu.}
{101}{}{Vidíš Dereka.}

{150}{}{Vypadá docela èile.}

# 1.  Night (From Where to go)
{200}{}{Obejdi mì.}
{201}{}{Jsem moc unavenı na to, abych si povídal.}
{202}{}{Odejdi z mého území.}
{203}{}{Najdi si svoje místo na spaní.}
{204}{}{Pøestaò mì otravovat.}
{205}{}{Jsem utahanı.}
{206}{}{Doh!}
{207}{}{Hej, co tu dìláš?}

# 2. Floats before Quest 2 (From Where to go)
{220}{}{Vyhni se Metzgerovi, køováku.}
{221}{}{Proè je poøád takové zatracené horko?}
{222}{}{Proè ijem v poušti?}
{223}{}{Jsem dobrı kuchaø.}
{224}{}{Jednou si otevøu svou vlastní restauraci.}
{225}{}{Ké bych tak mìl opravdovou kuchyò.}
{226}{}{Proè stále tahám za ten kratší konec ivota?}
{227}{}{Lidé si ze mì poøád utahují.}
{228}{}{Fred je snílek -- mistr plánování.}

# 3. Floats after Job 2, and having talk to him (From Where to go)
{240}{}{Shhhh! Jsou všude.}
{241}{}{Zastav je!}
{242}{}{Tak jsi našel tu zatracenou knihu?}
{243}{}{Nevím, proè si mì Becky nechce najmout.}
{244}{}{Nezblázním se!}
{245}{}{Dostal jsem svou ètvrtinu!}
{246}{}{Vycházejí pøevánì v noci.}
{247}{}{Mám rád brambory!}
{248}{}{Nechoï po tom zeleném bez bot!}
{249}{}{Jen to obra na ruby.}
{250}{}{Oh, pìknì mì bolí hlava.}
{251}{}{Jsem šéfkuchaø!}
{252}{}{Nikdy bych neotrávil nováèkùm jídlo.}

# 4. 1st Time, On Job (From Where to go)
{260}{}{Hej hledáš nìjakı èerstvì upeèenı chléb?}
{261}{}{Ano.}
{262}{}{Hledám Beckyinu knihu.}
{263}{}{Ne, sbohem.}

# 5. Next Times (From Where to go)
{270}{}{Oh, vítej ještì jednou.}
{271}{}{Tak kde je Beckyina kniha?}
{272}{}{Hej, co takhle kousek toho chleba?}
{273}{}{Nashle.}

# 6. Bread (From 4)
{280}{}{Ha! Já taky. U jsem ti øíkal, jakı jsem vynikající kuchaø? Becky mì ale z nìjakého dùvodu nechce pøijmout. Øekla, e jsem prı nestálı.}
{281}{}{Má pravdìpodobnì pravdu.}
{282}{}{Hledám Beckyinu knihu.}
{283}{}{To je skvìlı. U, uh..., musím jít.}

# 7. She's right (From 6)
{290}{}{Co? Ty! Nato ti kašlu, kamaráde! Já nejsem... A do prdele.}
{291}{}{Co? Ty! Nato ti prdím, dámo! Nejsem... A do prdele.}
{292}{}{Zatracenì.}
{293}{}{Nuf øekl.}

# 8. Looking for Book (From 4-6)
{300}{}{Jo tahle. Nemám to rád. Samı líbání. Hodil jsem to do kouta této budovy... ne tahle budova... ne... byla to budova? Moná jsem jí vyhodil nìkde jinde... nebo vyhodil jsem jí vùbec? Jau! Moje hlava!}
{301}{}{Kniha? Oh, tahle kniha. Kdo tì poslal? Nejsem si jist, zda je to ta pravá strana. Nezapomeò tu tkaninu.}
{302}{}{Nemùu! Oni jsou... a do hajzlu... Máš ten sır? Schovej se!}
{303}{}{Hej! To není mùj problém. Co jsem vlastnì pøedpokládal, e udìlám? Bojovat s nimi? Malí zelení muíci, velké zuby! Do prdele! Ouch! Pøestaò!}
{304}{}{Bolí mì hlava! Co... kdo to øekl?}
{305}{}{To hodnì pomáhá.}
{306}{}{Uh.}

# 9. More bread (From 5)
{310}{}{Co? Posmíváte se mi! Táhnìte k èertu! Nejsem nestálı! Umím vaøit! Nemám ádné hlasy v mé hlavì!}
{311}{}{Chystám se -- hovno! Do prdele! Zatracenì! Pøestaò s tím. Buï ticho! Co?... Ok.}
{312}{}{Hej! Pøe -- dìlat... do prdele.}
{313}{}{Nashle.}
{314}{}{Nic.}

# 10. Dumb Floats (From Where to go)
{320}{}{Hej! Vypadni ode mne!}
{321}{}{Nedotıkej se mne!}
