#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
# 0. Look
{100}{}{Vidíš hubeného, oplzle vyhlížejícího muže.}

{150}{}{Vidíš Flicka, který podrobuje svá varlata dùkladnému podrbání.}
{151}{}{Vidíš špinavého chlápka s odporným výrazem v oblièeji.}

# 1. Low Intelligence (WtG)
{200}{}{Jdi do nìkam, ty debile.}
{201}{}{Hej ty masová koule! Jó, ty. Vypadni heeya.}
{202}{}{Jsi hromada šrotu nebo èo?}
{203}{}{Co máš za probléma, no?}
{204}{}{Jdi k èertu heeya.}

# 2. Hello (WtG, 3,4,6,7,911,12,13)
{220}{}{Hej der, já jsem Flick. Co k sakru chceš, huh?}
{221}{}{Tak co? Zdržuješ mì heeya.}
{222}{}{Co to je za praštìný pøízvuk, Flicku?}
{223}{}{Co tu k èertu dìláš?}
{224}{}{Hledám Vault - oh a taky jednoho obchodníka jménem Vic. Víš kde by mohli být?}
{225}{}{Rád bych s tebou udìlal obchod.}

# 3. After Barter (2,3,9)
{240}{}{Je nìco, co pro tebe mùžu udìlat, kamaráde?}
{241}{}{Vlastnì bych se rád ještì podíval na tvoje zboží, jestli mùžu.}
{242}{}{Vlastnì bych se rád na nìco zeptal.}
{243}{}{Tak ujednáno. Uvidíme se u Flicka.}

# 4. What do you do here (2)
{260}{}{Jsem snad nìjakej zatracenej chlebodárce, co myslíš? Jsem jako dobrý  Samurai-itan.}
{261}{}{Co øíkáš?}
{262}{}{Jo, uh, dobrá...dovol mi, abych se ještì na nìco zeptal.}
{263}{}{Uh, oh. OK. Nashle, Flicku.}

# 5. You do what? (4)
{280}{}{Poskytuju malý paina.}
{281}{}{Poskytuješ malá piana?}

# 6. Pianos?(5)
{290}{}{Pai-na, víš, dìti. Moje dìti.}
{291}{}{Tvoje dìti?}
{292}{}{Dobrá, já nestojím o hodiny hudby pro dìti. Dovol, abych se zeptal na nìco jiného.}

# 7. Your kids? (6)
{300}{}{Jo, nu dobrá, oni pro mì pracujou. Nosí mi vìci. Malé vìci. Víš.}
{301}{}{Uh, ne.}
{302}{}{Oh, OK. Tak mi dovol, abych se zeptal na nìco jiného.}
{303}{}{Ah, aha. Dobøe, nechci ochromit tvùj, uh, styl. Nashle.}

# 8. They bring you things? (7)
{315}{}{Pøinášejí mi materiál, který najdou. Malé, malièké vìci. Materiál, který už nikdo nepoužije. Jinými slovy, starám se o nì.}
{316}{}{Zní to jako dobrá organizace.}

# 9. Nice arrangement (8)
{325}{}{(Flick pokrèí rameny) Jsem oukej.}
{326}{}{Dovol, abych se zeptal na nìco jiného.}
{327}{}{Museli ti pøinést nìjaké zajímavé vìcièky. Ukaž, prosím, co všechno máš.}
{328}{}{Jen se dívám. Tak nashle Flicku.}

# 10. Wacky accent? (2)
{340}{}{O èem to mluvíš? Myslíš si, že jsem nìjakej posranej blbej pirla? Nìjakej debilní filio di puttana? Myslíž, že jsem nìjakej šašek? Jsem tu snad pro srandu králíkùm, nebo co?}
{341}{}{Uh, ne. Promiò, byl jsem jenom zvìdavý. Dovol, abych se zeptal na nìco jiného.}
{342}{}{Jo, to je pravda, ty hlavo sraèek. A nic mì nepobaví víc, tak jako tvoje smrt v bolestech.}
{343}{}{Dobøe, když seš takovej nedùtklivej, tak odcházím.}

# 11. Vic & Vault (2)
{360}{}{Vault huh? Možná Máma o tom ví, protože já vùbec netuším. Ale ten chlapík Vic - toho znám. Metzger má toho porca pistola.}
{361}{}{Vic? Není s tebou? Ty biota. Ale Mámu, tu znám.}
{362}{}{Kdo je Metzger?}
{363}{}{Kdo je Máma?}
{364}{}{Díky. Dovolte, abych se vás zeptal na nìco jiného.}
{365}{}{Díky, to je všechno, co potøebuju vìdìt. Nashle.}

# 12. Who's Momma? (11,13)
{380}{}{Máma provozuje jídelnu ve Východní èásti mìsta. Hned za høbitovem. Hezké místo, vaøí tam dobré tìstoviny, Mama mia.}
{381}{}{Díky, co ten chlápek Metzger, co má Vica?}
{382}{}{Díky. Ještì bych se rád zeptal na nìco jiného.}
{383}{}{Díky, to je všechno, co jsem potøeboval vìdìt. Sbohem.}

# 13. Who's Metzger? (11,12)
{400}{}{To je pravda. Metzger, je štronzo, je mrtvej. Nevím co se stalo s Vickem.}
{401}{}{Ten Metzger, to je skuteènì prase. Provozuje Cech otrokáøù. Na východì mìsta, hned na sever od Mámy. V každém pøípadì, má Vica, to vím.}
{402}{}{Díky, a co teï nìco o Mámì?}
{403}{}{Díky. Mùžu se vás ještì na nìco zeptat.}
{404}{}{Díky, to je všechno, co jsem potøeboval vìdìt. Sbohem.}
