#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš majitele Díry.}
{101}{}{Vidíš Frankieho, majitele Díry.}

{150}{}{Ukazuje se, jako majitel tohoto místa.}
{151}{}{To je Frankie. Je vlastníkem tohoto podniku.}
{152}{}{[MLUVIT]}
{153}{}{Já jsem Frankie a ty se nacházíš v Díøe. Zatracenì nejlepší bar na míle daleko! Kadı se doplazí do Díry, kdy je èas na poøádnı odvaz.
 A ne aby kvùli tobì byly nìjaké potíe, slyšíš??}
{154}{}{Slyším tì.}
{155}{}{Jo, oukej. Cokoliv.}
{156}{}{U je mi jasnı, proè øíkáš tomuhle místu "Díra".}
{157}{}{Huh?}
{158}{}{Co tì dokáe potìšit?}
{159}{}{Whiskey.}
{160}{}{eny.}
{161}{}{Mui.}
{162}{}{Informace.}
{163}{}{Dneska nic. Nashle.}
{164}{}{Hee hee.}
{165}{}{Hej! Mìl by si radši zavøít tu svou tlamu!}
{166}{}{Nebo co?}
{167}{}{Starej se o sebe a dej mi panáka.}
{168}{}{Místo toho jen odejdu.}
{169}{}{Whiskey je za $}
{170}{}{ sklenka.}
{171}{}{Tady jsou peníze.}
{172}{}{V ádnım pøípadì! To je pøíliš mnoho!}
{173}{}{Proè tvoje whiskey stojí o hodnì víc ne U Becky?}
{174}{}{Ne díky.}
{175}{}{Ještì nìco jiného?}
{176}{}{Ano.}
{177}{}{Urèitì ne, Díky.}
{178}{}{Nemáš dost penìz! Tohle není ádná charitativní organizace!}
{179}{}{Oh, promiò. Jsem na dnì.}
{180}{}{Já se vrátím.}
{181}{}{Co chceš?}
{182}{}{Whiskey.}
{183}{}{Nic. Právì odcházím.}
{184}{}{Wahdo a peedee!}
{185}{}{A nevracej se!}
{186}{}{[konec]}
{187}{}{Nerad vidím lidi, jako jsi ty, na mojem místì. Vypadni!}
{188}{}{Dobrá, u jdu.}
{189}{}{Wah.}
{190}{}{Tyhle rodiny New Reno jsou schopnı ti naúètovat klidnì ruku nebo nohu za svùj chlast. Nevím jak to dìlá!}
{191}{}{Mìl bys to zkusit zjistit.}
{192}{}{Mohl bych to zjistit.}
{193}{}{Vím jak to dìlá.}
{194}{}{Pùjdu a koupím od ní whiskey.}
{195}{}{Jestli zjistíš, jak získává svùj chlast, zaplatím ti $100.}
{196}{}{Oukej, já na to pøijdu.}
{197}{}{Jistì, e ne, ádnı zájem.}
{198}{}{Tak, jak to Becky dìlá? Jak to, e prodává svùj chlast tak levnì?}
{199}{}{Má destilaèní pøístroj.}
{200}{}{Ještì nevím. Vrátím se.}
{201}{}{Co? Destilaèní pøístroj? Zatracenì. Tady máš $100, a zaplatím ti dalších $500, kdy ho pro mì znièíš. Mùeš na to pouít moje páèidlo, které najdeš támhle v zadní místnosti. To udìlá konec s jejím pitomım malım destilaèním pøístrojem!}
{202}{}{U jsem si ho vzal.}
{203}{}{OK, znièím to.}
{204}{}{V ádnım pøípadì. To je moc. Mám informaci. Vymìním ji.}
{205}{}{Ne, mám lepší nápad.}
{206}{}{Tak, je ten destilaèní pøístroj znièen? Jak jsem øekl, pouij na to moje páèidlo. To s tím opravdu udìlá krátkı proces.}
{207}{}{Ano, to ano.}
{208}{}{Mám lepší nápad.}
{209}{}{Urèitì ne. Dám ti vìdìt, a to bude.}
{210}{}{Tak tady je tìch $500. Díky.}
{211}{}{Je pøíjemné s tebou obchodovat.}
{212}{}{Víš, Frankie, ona se chystá postavit novı.}
{213}{}{Díky, sbohem.}
{214}{}{Zatracenì! Dobrá, ale nìjakou dobu nebude mít ádnı chlast.}
{215}{}{Proè s ní bojuješ, Frankie? Spoj se s ní.}
{216}{}{Mysli. Kde jinde mùeš dostat alkohol?}
{217}{}{Co tím myslíš?}
{218}{}{Kupuj od ní alkohol. Je to levnìjší, ne od New Reno, a taky vydìláš víc penìz.}
{219}{}{Nechci.}
{220}{}{Nevadí.}
{221}{}{Podívej, chci jen znièit ten její destilátor. Udìláš to?}
{222}{}{Dobrá, udìlám to.}
{223}{}{Ne, nechci. Na shledanou.}
{224}{}{Moná máš pravdu. Promluvím s ní. Díky.}
{225}{}{Na co by jinak byli pøátelé?}
{226}{}{Nashle.}
{227}{}{Nemám informaci.}
{228}{}{Opravdu? A proè jsou U Becky drinky o tolik levnìjší ne ty tvoje?}
{229}{}{Myslel jsem, e barmani vìdí všechno.}
{230}{}{Tak jsem asi na špatném místì. Sbohem.}
{231}{}{Hoï øeè se Sheilou. Hej, Sheilo, máš zákazníka!}
{232}{}{Poèkej, to není to, co já chci!}
{233}{}{Díky. Sbohem.}
{234}{}{Yeah, vsadím se. Trvá ti to asi zatracenì dlouho dostat chlapa. Zkus štìstí nìkde jinde, sestro. Nejsem ádnı samaritán.}
{235}{}{Fajn! Tak tedy nìco jiného.}
{236}{}{Proè, malièká...}
{237}{}{Nepotøebuju to od tebe!}
{238}{}{Mám támhle pokoj. Ty a já ho mùeme pouít.}
{239}{}{Oukej.}
{240}{}{Ne, to jsem nemyslel!}

{242}{}{Ani ty ne.}
{243}{}{Mohl bych zkusit, jestli víš, jak uspokojit enu.}
{244}{}{Jsi ta nejlepší co jsem kdy mìl. Opravdu. Myslím to vánì.}
{245}{}{Musím se najíst a bìet, ale...}
{246}{}{Uvidíme se pozdìji.}
{247}{}{Sbohem.}

{248}{}{Jo, cokoliv. Jen si to po sobì teï umej, ano?}
{249}{}{Hej, všichni! Dojdeme pro Billyho. Nìjakı urèitì má!}
{250}{}{Potøebuješ mop?}
{251}{}{Uvidíme se v Pìtce.}
{252}{}{Sheilo! Dohlédni na bar!}
{253}{}{Hej, Billy, jdi odtud pryè!}
{254}{}{Kde jsi teï byl?}
{255}{}{Kde jsi, enská?}
{256}{}{Pøišla by´s sem?}
{257}{}{Pojï, bejby.}
{258}{}{Pojï se mnou.}
{259}{}{ádná enská mi neodolá. Vypadni, k èertu!}
{260}{}{Fajn.}
{261}{}{Zapomnìl jsem; chtìl jsem nìco jiného, musel jsem bıt úplnì mimo. Odpus mi, bejby.}
{262}{}{Rozhodl jsem se, e pøeci nechci spát s tou tvojí hnusnou prdelí.}
{263}{}{Máš štìstí, jsem hodnı chlápek. Ale u to na mì nezkoušej.}
{264}{}{Nechci, bejby, slibuju.}
{265}{}{enská, asi tì nakopnu!}
{266}{}{Nikdo se mnou takle ještì nemluvil! Chcípni!}
{267}{}{Mìla jsi tolik, které jsem ti dal. Teï vypadni.}
{268}{}{S tímhle smetím do mého zadního pokoje nepùjdeš!}

{300}{}{Hej, neøíkal jsem kurva, e bych ti zaplatil, kdybys tu dìvku zabil. Vypadni do prdele vodsaï!}

{350}{}{Ty vole! To bylo úasnı.}
{351}{}{Zatracenì, byla jsi dost dobrá bejby.}
{352}{}{Díky, byla to paráda. Teï odejdi.}
{353}{}{Byl jsi, uhhh... Nevadí, odejdi.}
{354}{}{Nikdy jsem nemìl(a) horší, ne tohle.}

{400}{}{Víš bejby, mùeš bıt havá a všechno, ale musíš se ještì moc a moc uèit.}
{410}{}{Bejby, dám si tu práci, tì uèit. Nebudu tady stát celı den na místì a nic nedìlat. Tak dobrá, co kdy to udìlám? To je to, proè tady jsem.}
