#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
# 0. Look
{100}{}{Vidíš obèana Denu.}
{101}{}{Vidíš Freda.}
{102}{}{Vidíš Freda ve velmi pìkném obleèení.}

{150}{}{Vypadá, e o nìèem usilovnì pøemıšlí.}
{151}{}{Vypadá velice spokojenì ve svém novém ohozu.}

# 1.  Fred B4 Becky's Job (From Where to go)
{200}{}{Jednou to tady roztoèím.}
{201}{}{Nech mì bıt. Nemám èas.}
{202}{}{Mistrovskı plán...}
{203}{}{Já na to nìkdy pøijdu...}
{204}{}{Proè poøád prohrávám?}
{205}{}{Musí to vypadat k svìtu.}
{206}{}{Jo, jednou budu ve svım vlastním.}
{207}{}{Seenu si nìco hezkıho na sebe.}

# 2. Night (From Where to go)
{220}{}{Sakra! U je pozdì. Nech mì na pokoji.}
{221}{}{Ne, fakt nepotøebuju spoleènost.}
{222}{}{Víš kolik je hodin?}
{223}{}{Nic nemám.}
{224}{}{Pøijï otravovat a ráno. Chce se mi spát.}
{225}{}{Vodprejskni.}
{226}{}{Nemám èas.}
{227}{}{Nechce se mi povídat. U jdu spát.}
{228}{}{Hele, sleèno! U je pozdì. Nech mì na pokoji.}

# 3. Paid, Broke Floats (From Where to go)
{240}{}{U ádnı prachy! Nech mì na pokoji.}
{241}{}{Není ádná práce. Co budu dìlat?}
{242}{}{Neøíkej mi, e nìkomu dluím! Ahh!}
{243}{}{Vypadá to, e to moc neroztoèím.}
{244}{}{Jsem úplnì švorc.}
{245}{}{Sakra, potøebuju nìjakı prachy.}
{246}{}{Novı hadry na sebe si asi hned tak nekoupím.}
{247}{}{Chce to novej plán...}

# 4. Covered, Floats (From Where to go)
{260}{}{Dík, es mì zaloil!}
{261}{}{Dík za záchranu.}
{262}{}{U brzo budu mít pro tebe ty prachy.}
{263}{}{U brzo musím vyhrát!}
{264}{}{Jsi první za kım pùjdu a vyhraju.}

# 5. Covered and Loaned, Floats (From Where to go)
{275}{}{Rozbìhnul jsem mistrovskej plán!}
{276}{}{Díky za pùjèku! Tvoje prachy jsou v dobrıch rukou!}
{277}{}{Není to nic lehkıho, ale nemìj strach.}
{278}{}{Jednou vyhraju hlavní cenu, a to díky tobì.}
{279}{}{U to bude kadou chvíli! U to cítím.}
{280}{}{Opravdu ti to všechno splatím, slibuju!}
{281}{}{U brzo vyhraju hlavní. Visí to ve vzduchu.}

# 6. 1st Time on Job 1 (From Where to go)
{295}{}{Coe? My se známe? Co chceš?}
{296}{}{Proè mì poøád otravuješ? Já tì ani neznám. Jdi prudit jinam.}
{297}{}{Jdu vybrat nìjakı peníze, co nìkomu dluíš.}
{298}{}{Kašli na to.}
{299}{}{Uk!}
{300}{}{Èau.}

# 7. Won It BIG! (From Where to go)
{310}{}{HEJ! Tady jsi! Všude jsem tì hledal! Mrkni na ty hadry!}
{311}{}{Ještì jednou díky.}
{312}{}{Vypadá to moc pìknì.}
{313}{}{Vypadáš jako debil!}
{314}{}{Fuj!}
{315}{}{Ug.}

# 8. Look nice (From 7)
{320}{}{Díky moc! Díky tobì mám ještì ètvery takovı!}
{321}{}{Take se ti to nakonec povedlo?}
{322}{}{Tak, kde jsou moje peníze?}

# 9. Look bad (From 7)
{330}{}{Tobì se moje hadry nelíbí? Víš, asi máš pravdu. Mnì se vlastnì taky nelíbí. Koupím si jinı -- mùu si to teï dovolit!}
{331}{}{Take se ti to nakonec povedlo?}
{332}{}{A co moje peníze?}
{333}{}{Hmph.}

# 10. Give me money 1 (From 8, 9)
{340}{}{U jsem se k tomu dostával! Ani mì nenecháš uít si slávy? Dlouho jsem na to èekal, dy víš.}
{341}{}{Já vím, uívej si.}
{342}{}{Kašlu na to. Kde jsou ty prachy ode mnì?}
{343}{}{Na to ti seru. Kde sou moje prachy?}

# 11. Give me money 2 (From 10)
{350}{}{Tak jo. Tady je máš. [Fred ti dává $500] Je tam nìco navíc za to, es mi vìøil. Tak zase nìkdy. A ještì jednou dík.}
{351}{}{Dík!}
{352}{}{Aby ne.}

# 12. Covered 1 (From 8-10)
{360}{}{Dík es mì zaloil. Fakt to pro mì hodnì znamenalo, e mi nìkdo úplnì cizí vìøil. Nìco ti dám.}
{361}{}{Dobøe.}
{362}{}{To nemusíš.}
{363}{}{Uh.}

# 13. Loaned 1 (From 8-10)
{370}{}{Hodnì ti dluím. Vìøil jsi mi, kdy mi všechno padalo na hlavu. Jako malı projev vdìènosti pro tebe nìco mám.}
{371}{}{Dobøe.}
{372}{}{To nemusíš.}
{373}{}{Uh.}

# 14. Covered 2 (From 12)
{380}{}{Tady. (Fred ti dává $1000.) Doufám e to pomùe. Jsem si jistı, e u budeš vìdìt co s tím.}
{381}{}{Sorry, ale tolik si nemùu vzít.}
{382}{}{Díky.}
{383}{}{Zatím nevím, ale vezmu si to.}
{384}{}{Mlask.}

# 15. Loan 2 (From 13)
{390}{}{Ber. (Fred ti dává $2000, 5 Fusion Cells, 5 Energy Cells a plasmovı granát.) Doufám e ti to aspoò trochu pomùe.}
{391}{}{Sorry, ale tolik si toho nemùu vzít.}
{392}{}{Díky moc.}
{393}{}{Ani ne, ale beru to.}
{394}{}{Mlask.}

# 16. Refused reward (From 15)
{400}{}{Coe? Tak dobøe, kdy na tom trváš. Opravdu ti moc dìkuju. Dávej na sebe pozor.}
{401}{}{Zatím.}

# 17. Dumb, beat it (From 6)
{410}{}{Co? Jsi na nìjakıch drogách? Nevypadáš na feáka. Táhni ode mnì, magore.}
{411}{}{Vypadni!}
{412}{}{Ug.}

# 18. Here to collect (From 6)
{420}{}{O èem to meleš? Nikomu nic nedluím. O kom to sakra mluvíš?}
{421}{}{Jo, to jsi u pøedtím øíkal. O èem to tady poøád mluvíš? Jake se ta vymyšlená osoba jmenovala?}
{422}{}{Becky øíkala, e jí dluíš 500 babek.}
{423}{}{Poslala mì Becky.}
{424}{}{Rebecca øíká, e ti pùjèila 200 dolarù.}

# 19. Sure she lent me $200 (From 18)
{430}{}{No jo, správnì. Rebecca mi pùjèila 200 dolarù... Oh, poèkej. Moná - ummm...}
{431}{}{Øekla mi, e ti mám urvat hlavu jestli nezaplatíš.}
{432}{}{Naval ty prachy.}

# 20. Owe $500 (From 18)
{440}{}{Aha, to urèitì. Tolik penìz pohromadì jsem v ivotì nevidìl.}
{441}{}{Hmmm.}
{442}{}{Oh.}

# 21. Becky Swear or Pissed (From 19)
{450}{}{Aha! To ti tak budu vìøit. Becky by neublíila ani mouše.}
{451}{}{Tak to se pleteš, sráèi.}
{452}{}{Moná to byl nìkdo jinı.}

# 22. Remembers money (From 19, 33-35)
{460}{}{Sakra. Myslím e máš pravdu, ale -- jsem skoro švorc. Tolik penìz si nemùu dovolit! Musím taky jíst, víš?}
{461}{}{To mì mrzí.}
{462}{}{Smùla.}

# 23. Tuff Luck (From 22)
{470}{}{Oh, sakra. Stìí si mùu dovolit 100. Mùeš mi pùjèit pùlku? Slibuju e ti to vrátím!}
{471}{}{Ne, promiò.}
{472}{}{Ale no tak. Zapla všechno!}
{473}{}{Tak dobøe.}

# 24. Will pay 200 (From 23, 37)
{480}{}{Sakra. To mì zruinuje! Tak dobøe, tady to máš. Ale teï jsem úplnì švorc.}
{481}{}{Tak dobøe. Zaloím tì.}
{482}{}{Dík. Pøíštì se o prachy líp starej.}
{483}{}{Bylo mi potìšením spolupracovat.}

# 25. Failed Speech for Full amount (From 23, 37)
{490}{}{Øíkal jsem ti! Nemùu! Umøel bych hlady. No tak, nemùeš mi pomoct?}
{491}{}{Tak dobøe. Pùjèím ti pùlku.}
{492}{}{Ne sorry. Taky nemám peníze.}
{493}{}{Ještì se vrátím.}

# 26. PC will Cover (From 23-25, 29, 37)
{500}{}{Co? Opravdu? Jo, díky moc, èlovìèe! Tady je 100 babek. Tu stovku vrátím co nejdøív!}
{501}{}{Co? Opravdu? Jo, díky moc, sleèno! Tady je 100 babek. Tu stovku vrátím co nejdøív!}
{502}{}{Bez problémù.}
{503}{}{To bys opravdu mìl.}

# 27. Better pay PC back! (From 26)
{510}{}{No tak, neboj se. Fakt! Máš moje slovo, e tentokrát nezapomenu!}
{511}{}{Oukej.}

# 28. Fred asks for Loan (From 26-27)
{520}{}{Hele, víš co? Ta stovka hm...trochu pomùe. Myslíš e bys mi mohl ještì trochu pùjèit?}
{521}{}{Kolik?}
{522}{}{Na to zapomeò.}

# 29. Wait I know... (From 25)
{530}{}{Poèkej! U vím. Udìláme to takhle. Já ti dám $100, ty mi $100 pùjèíš a vrátíme to Becky. Brzo ti to splatím.}
{531}{}{To by snad šlo.}
{532}{}{Na to rychle zapomeò.}

# 30. Amount of Loan (From 28)
{540}{}{Jenom pade. Prosím! Všechno je to souèást mistrovského plánu!}
{541}{}{Tak dobøe.}
{542}{}{Ale to budu mít jenom $50 abych zaplatil tvùj dluh $200.}
{543}{}{Ne.}

# 31. PC gave Loan (From 30)
{550}{}{Co - uh... Sakra! Toho nebudeš litovat! Fakt se ti to vyplatí!}
{551}{}{Bez problémù.}

# 32. Clarification of amount of loan (From 30)
{560}{}{No, to jo. Vidím e poèítat umíš. Prosím! Pro tebe to zase tolik není, ale pro mnì je to strašnì moc.}
{561}{}{Oukej.}
{562}{}{Ne.}

# 33. Becky sent PC (From 18)
{570}{}{Jo, to urèitì. Kadı ví, e tohle jméno nenávidí. Nedìlej si srandu!}
{571}{}{Nic jí nedluím.}
{572}{}{Øíkala, e jsi nìjak zapomìtlivı.}
{573}{}{Podívej se, na tohle nemám èas. Naval prachy!}
{574}{}{Rebecca øíkala, e ti pùjèila u døív.}

# 34. Forgetful (From 33)
{580}{}{Ne, to nejsem! Já... poèkej. Asi máš pravdu. Já jsem to ještì nevrátil? Já myslel e jo...}
{581}{}{Ne, to jsi teda nevrátil. Proto poslala mnì.}
{582}{}{Prostì zapla a u mùu vypadnout.}

# 35. Don't quite remember (From 33)
{590}{}{Nevzpomínám si... ale Becky mnì a mım pøátelùm pomáhala, to jo.}
{591}{}{Naval 200 babek.}
{592}{}{Prostì mi dej ty peníze.}

# 36. Get out of here (From 33)
{600}{}{Nech mì bıt.}
{601}{}{Jak chceš.}
{602}{}{Oukej.}

# 37. Remembers (From Where to go)
{610}{}{Ehm. Nazdar. Tak, ehm, Pøedpokládám e chceš peníze. Myslíš e bys mì moh zaloit? Asi tak pùlku?}
{611}{}{Ne nemohl, promiò.}
{612}{}{Jestli ti pùjèila 200 babek, tak je zaplatíš.}
{613}{}{No tak dobøe.}
