#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
# 0. Look
{100}{}{Vidíš stráe.}

{150}{}{Je to jeden z Tylerovıch støácù.}

# 1. Hostile
{200}{}{Ty stále ivı?}

# 2. CF: Gang 2 Defeated
{210}{}{Ukázali jsme jim, e jo?}
{211}{}{Nikdo si na nás nepøijde.}
{212}{}{Natrhli jsme jim prdel.}
{213}{}{Vyøídili jsme je za chvíli.}
{214}{}{Nemùu zapomenout na ten vıraz v jeho tváøi. Bylo to skvìlı.}
{215}{}{Jsem pøekvapen, e se Metzger nepochcal.}
{216}{}{Zajímalo by mì, proè Metzger nezakroèil.}

# 3. ELSE
{225}{}{Nevím na co nás Metzger poslal hlídat tohle hovno.}
{226}{}{Kdo by se pokusil ukrást tuhle sraèku?}
{227}{}{Tohle je práce na hovno.}
{228}{}{Nikdo si na nás nepøijde.}
{229}{}{Myslím, e ta vìc pocházela z Vaultu nebo tak nìjak.}
{230}{}{Co tedy hledáš?}
{231}{}{Nic tu není, jen my, myši.}
{232}{}{Neplıtvej èasem, u jsme tu vìc provìøili milionkrát.}

# 4. SET
{233}{}{Dnes v noci bude noc.}
{234}{}{Nenávidím èekání.}
{235}{}{Pro to se kdykoliv vzdám panáka.}
{236}{}{Je u èas? Tìko mohu èekat.}
{237}{}{Myslím, e zabiju jako první.}
{238}{}{Proè èekali a do teï, aby nás zmátli?}
{239}{}{Zaèíná to bıt zajímavé.}

# 5. NOSHOW
{240}{}{Je to špatnı, vùbec jsme si neuili ádnou akci.}
{241}{}{Zajímalo by mì, proè se rozmysleli.}
{242}{}{Tolik èekání pro nic.}
{243}{}{Co všechno se muselo stát, abyste nám pomáhali nastrait tuhle past?}
{244}{}{Co se stalo tu další noc?}
{245}{}{Je dost špatnı, e ty zbabìlci vzali do zajeèích. Mìl jsem takovou chu vyøídit je.}
{246}{}{Nemùu uvìøit tomu, e ty bastardi se nás pokusili pøepadnout.}
