#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
# 0. Look
{100}{}{Vidíš gangstera.}

{150}{}{Zdá se, e je to jeden z Laøinıho gangu.}
{151}{}{Zdá se, e je to jedna z Laøinıho gangu.}

# 1. Hostile
{200}{}{Chytrı chlápek.}
{201}{}{Tady jsi.}
{202}{}{Vra mi to.}
{203}{}{Pojï sem.}
{204}{}{Nejsem s tebou hotov.}
{205}{}{Dìvko.}

# 2. Metzger's Dead
{225}{}{Zajímalo by mì, co by se tu stalo po Metzgerovì smrti?}
{226}{}{Tak, Metzger je koneènì mrtvı?}
{227}{}{Byla to tvoje prácièka?}
{228}{}{Den nikdy nebude to, èím bıval.}

# 3. 2Won
{240}{}{Nemohu uvìøit, e jsme je fakt porazili!}
{241}{}{Metzger nám teï bude muset dokázat svou sílu.}
{242}{}{To jsme jim to ukázali.}
{243}{}{Ukázali jsme jim naše vlastní pojetí spravedlnosti.}
{244}{}{Nebyli bychom to dokázali bez vás!}
{245}{}{Díky za vaší pomoc!}
{246}{}{Dokázali jsme to!}

# 4. NO SHOW
{247}{}{Zaèínáš nato dlabat?}
{248}{}{Lepší sledovat tvé kroky.}
{249}{}{Lara je jedinım dùvodem, e tì teï neobìsíme.}
{250}{}{Co jsi se snail táhnout?}

# 5. COWARD
{251}{}{Zbabìlec.}
{252}{}{Je mi z tebe na blití.}
{253}{}{Ztra se}
{254}{}{Obejdi to.}

# 6. FIGHT
{255}{}{My jsme pøipraveni, kdy jsi ty.}
{256}{}{Je to otázka èasu, kdy jim to vrátíme.}
{257}{}{Nenávidím èekání.}
{258}{}{Pojïme u.}
{259}{}{U jsi pøipraven?}
{260}{}{Dej Laøe vìdìt, a bude èas.}

# 7. NO
{270}{}{Chceš se pøipojit?}
{271}{}{Musíš bıt tady, abys vidìl Laru.}
{272}{}{Jak to jde?}
{273}{}{Lara je osoba, s kterou bys mìl pohovoøit.}
{274}{}{Èau.}
{275}{}{Jsi tu za Larou?}

# 8. Else
{300}{}{Èau.}
{301}{}{Jak to jde?}
{302}{}{Doufám, e se daøí dobøe.}
{303}{}{Mìl by si bıt schopen nám helfnout, ne?}
{304}{}{Rád tì vidím.}
{305}{}{Tylerovi to brzo vrátíme...}
{306}{}{Nìjaké nové zdokonalení?}

# 9. Lara Dead
{310}{}{Díky za pomoc. Mrzí mì to s tou Larou.}
{311}{}{Nakonec jsme je dostali!}
{312}{}{Nebyli bychom schopni to dokázat bez vás.}
{313}{}{Lara alespoò padla v boji.}
{314}{}{Nemohu uvìøit, e to Lara nepøeila.}
{315}{}{Metzgerovi jsme ukázali, kdo je nejlepší.}
{316}{}{Metzger se nám radìji neukázal.}

# 10. Running to fight
{350}{}{Øekl jsi to!}
{351}{}{Jsou z nich mrtvoly!}
{352}{}{Jdeme jim natrhnout prdel!}
