#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
# 0. Look
{100}{}{Vidíš gamblera.}
{101}{}{Tomuhle gamblerovi, zdá se, se dost neobyèejnì daøí.}
{102}{}{Zdá se, že vyhrává, ale všechny jeho peníze jsou na hracím stole.}
{103}{}{Zdá se, že vyhrává, ale všechny její peníze jsou na hracím stole.}
{104}{}{Tato osoba se zdá, že ani nevyhrává ani neprohrává.}
{105}{}{Tato osoba už dlouho nevyhrála.}
{106}{}{Vypadá, že bude plakat a zdá se, že je skoro bez halíøe.}
{107}{}{Vypadá dost naštvanì a zdá se, že prohrál velkou èástku.}

# 1. PC Killed Becky, NPC are still around (From Where to go)
{200}{}{Neubližujte mi!}
{201}{}{Nestøílejte!}
{202}{}{Nemám žádné peníze!}
{203}{}{Proè jsi zavraždil nebohou Becky?}
{204}{}{Co ti kdy udìlala?}
{205}{}{Já jsem nic neudìlal!}
{206}{}{Jdi prosím, nechce se mi mluvit.}

# 2. CF: Gambling (From Where to go)
{300}{}{Ano! Kostky mì mají rády!}
{301}{}{Oh, to bylo tìsnì.}
{302}{}{Nevyrušujte mì. Pøerušíte mi vítìznou šòùru.}
{303}{}{Je mi horko!}
{304}{}{Prachy, prachy, prachy!}
{305}{}{Miluju tuhle hru!}
{306}{}{No vidíš! Jo!}
{307}{}{Rouletta je hra her!}
{308}{}{Daøí se mi celkem dobøe, a co ty, jak jsi na tom?}
{309}{}{Daøí se mi lépe, než obyèejnì.}
{310}{}{Skvìlé místo, nemyslíš?}
{311}{}{Beckyny hrací stoly jsou lepší než ty v New Renu.}
{312}{}{Líbí se ti ta hra? Je to skvìlá zábava.}
{313}{}{Nemìl jsem ještì dobrou hru.}
{314}{}{Potøebuju dobrou hru.}
{315}{}{Aspoò, že neprohrávám.}
{316}{}{Nikam nejdu.}
{317}{}{Neprodìlávám.}
{318}{}{Máš hrát na èísla.}
{319}{}{Vsázet jen na èervenou nebo èernou je špatný.}
{320}{}{Kostky mi nejdou.}
{321}{}{Jsem na dnì a nevypadá to dobøe.}
{322}{}{Doufám, že se ti daøí lépe než mì.}
{323}{}{Už jsem mìl lepší dny.}
{324}{}{Vím jak hrát, poctivì.}
{325}{}{Kulièka mì dneska vùbec neposlouchá.}
{326}{}{Další výplatní den nadobro ztracen.}
{327}{}{Jsem témìø znièen!}
{328}{}{Zatracenì. K èertu s tím.}
{329}{}{Proè se to vždycky stane mì?}
{330}{}{Nemùžu vyhrát.}
{331}{}{Nenávidím tuhle hru.}

# 3. BGF: Becky Dead (From Where to go)
{400}{}{Zatracenì, U Becky bylo široko daleko jediné místo, kde se mohlo hrát!}
{401}{}{Nepøibližujte se.}
{402}{}{Nestøílejte!}
{403}{}{Nechejte nás o samotì, prosím.}

# 4. BGF: Gambling (From Where to go)
{500}{}{Nezastavujte se tam.}
{501}{}{Pokraèujte v cestì.}
{502}{}{PØIJÏ sedmièko!}
{503}{}{Ano!}
{504}{}{Nezastavujte se!}
{505}{}{Becky! Dnes se chystám vzít ti všechny tvoje peníze!}
{506}{}{Jeheeee! Vítìz!}
{507}{}{Dej mi další dobrou ránu!}
{508}{}{Ano!}
{509}{}{V poøádku!}
{510}{}{Znovu, jen se na to podívej znovu.}
{511}{}{Pojï.}
{512}{}{To je to, co chci.}
{513}{}{Skoro.}
{514}{}{Není to špatné.}
{515}{}{Jak se to stalo?}
{516}{}{Ups.}
{517}{}{Tak mi tam padni, dìleeej. Stoop!}
{518}{}{Tahle hra si zaslouží své jméno.}
{519}{}{Potøebuji jen jednu velkou výhru.}
{520}{}{Èísla!}
{521}{}{Znovu?}
{522}{}{To nevypadá dobøe.}
{523}{}{Zatracená ruleta!}
{524}{}{Becky! Tvoje hrací stoly mì zabíjí!}
{525}{}{Je to tìmito kostkami nebo co?}
{526}{}{Už ne!}
{527}{}{Proè já?}
{528}{}{Zatracenì! Tak tìsnì!}
{529}{}{Oh dobrý, dobrý Bože, ZAB MÌ!}
{530}{}{Nenávidím tuhle hru!}
{531}{}{Zatracenì! To bylo moje èíslo v posledním otoèení!}
{532}{}{Znovu na èernou!?!?}

# 5. CF: Hostile (From Where to go)
{600}{}{Vypadni!}
{601}{}{Proè jsi to udìlal?}
{602}{}{Vypadni!}
{603}{}{Pøestaò s tím, jsem køehká (ý).}
{604}{}{Neudìlal bych to, co ty.}
