#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš zabijáka.}
{101}{}{Vidíš Joeye.}

{150}{}{Tenhle chlapík nevypadá pøíliš pøátelsky.}
{151}{}{[MLUVIT]}

# 1.
{152}{}{Chystám se tì rozøezat sráèi!}
{153}{}{Jo? Tak pojï a zkus to.}
{154}{}{Hej, poèkej minutku!}
{155}{}{Kdybych byl tebou, tak bych si to poøádnì rozmyslel.}

# 2.
{156}{}{Co chceš? Proè bych tì nemìl teï zabít za to, co jsi udìlal, místo toho, abych poslouchal ty tvoje vásty?}
{157}{}{Chci s tebou mluvit o duchovi, kterej se tu v noci promenáduje.}
{158}{}{Vzal jsi ze strašidelného domu amulet?}
{159}{}{Nevadí. Místo toho ti nakopu tu tvojí prdel.}
{160}{}{Nic. Jen procházím.}

# 3.
{161}{}{O èem to sakra mluvíš?}
{162}{}{Ukradl jsi z toho strašidelného domu amulet?}
{163}{}{No nic. Nevadí.}
{164}{}{Zapomeò na to. Teï tì zabiju a pozdìji naporcuju.}

# 4.
{165}{}{Já... já nevím, o èem to mluvíš.}
{166}{}{Ale myslím, e víš! Ukradl jsi té mrtvé dívce amulet a teï její duch nemùe odpoèívat v pokoji.}
{167}{}{Dobrá vezmu si to tedy násilím.}

# 5.
{168}{}{To... to je zatracenì šílenı! Nn-emáš v sso-bì nìjakou ttu Tubb-yho ssra-èku? Já-já jsem n-nikdy n-nevidìl d-ducha, k-kdy jsem t-tam byl, to nebylo skuteèné.}
{169}{}{Podívej, koupím to od tebe.}
{170}{}{Dej mi to, nebo se k ní mùeš pøipojit.}
{171}{}{Kdy to teï nevrátíš, ona za tebou pøijde. A jí nikdo nezastaví.}

# 6.
{172}{}{Huh? No jistì, jistì. Na to vezmi jed. Budeš muset vypláznout pár babek. Zadarmo to nedostaneš! $50 nebo nech bejt!}
{173}{}{Ok, tady jsou peníze.}
{174}{}{Vezmi $20 a buï šastnı, e ti je nevezmu.}
{175}{}{No, rozmyslel jsem si to. Uvidíme se.}
{176}{}{Dej mi to, nebo tì za to zabiju.}

# 7.
{177}{}{Hele. Teï mì nechej na pokoji.}
{178}{}{Nechám.}
{179}{}{A u se to znovu neopakuje!}

# 8.
{180}{}{He.. hej! Ty nemáš peníze! Vem tì èert!}
{181}{}{Sakra. Vrátím se.}
{182}{}{Potom tì, myslím, budu muset zabít.}

# 9.
{183}{}{Hej. Jak to jde?}
{184}{}{V pohodì. A tobì?}
{185}{}{Moc dobøe ne.}
{186}{}{Vzal jsi z toho domu amulet?}
{187}{}{Co víš o tom duchovi, kterej se tam v noci promenáduje?}

# 10.
{188}{}{Hej, chlape, já jsem Joey. Co pohledáváš na mém drnu?}
{189}{}{Tvém drnu? Nemyslím, e je tvùj.}
{190}{}{Moná tì hledám.}
{191}{}{U jdu pryè. Sbohem.}
{192}{}{Sháním informaci.}

# 11.
{193}{}{Hej, ty suchare. Ty hledáš Joeyho? Tady jsem.}
{194}{}{Ne. Jdi pryè.}
{195}{}{Moná. Co mi nabídneš?}
{196}{}{Chci jednu informaci.}
{197}{}{Ne, promiò. Musím u jít.}

# 12.
{198}{}{Hej, mám Jet. Je to vynikající matroš pøímo z New Reno. Chceš nìjakej?}
{199}{}{V ádnım pøípadì!}
{200}{}{Kolik?}
{201}{}{Ne, chci informaci.}
{202}{}{Musím jít. Nashle.}

# 13.
{203}{}{Co ty a já spolu? Jdeme na to?}
{204}{}{Ok.}
{205}{}{Ne, i kdybys byl poslední nezmutovanı èlovìk na planetì.}
{206}{}{Er, no... To si nemyslím. Potøebuju nìco jiného.}

# 14.
{207}{}{Ty se vrátíš.}
{208}{}{Moná.}
{209}{}{S tím nepoèítej.}
{210}{}{Poèkej! Mùu se tì na nìco zeptat?}

# 15.
{211}{}{Takovım zpùsobem se mnou ještì nikdo nemluvil!}
{212}{}{Já ano. Umíš ještì nìco jiného ne mluvit?}
{213}{}{Cokoliv. Prodáváš nìco, nebo jenom mluvíš?}
{214}{}{Omlouvám se. Jen se dívám kolem a neznám tuto oblast.}

# 16.
{215}{}{Co chceš?}
{216}{}{Hledám amulet.}
{217}{}{Potøebuju víc informací o tom strašidelném domì.}
{218}{}{Co je ujednáno s tím starım kostelem a tìmi stráemi?}
{219}{}{Nic, co mùeš obstarat.}
{220}{}{Slyšel jsi u o Vaultu 13?}
{221}{}{Um, nevadí. Uvidíme se.}

# 17. The Church
{222}{}{Oh, ty myslíš Tylera a jeho gang? Hlídají kadı hovno, kterı pøichází z Vault City. Velkı zasranı dopravní klece. Jednou  za èas je vidíš, jak je karavany smìøující do New Reno vyzvednou.}
{223}{}{Mùete mi o nich øíct víc?}
{224}{}{Mùu se zeptat na nìco jiného?}
{225}{}{OK, díky. Sbohem.}

# 18.
{226}{}{Co chceš ještì vìdìt?}
{227}{}{Kdo je Tyler?}
{228}{}{Kde je New Reno?}
{229}{}{Tak, co hlídají?}
{230}{}{Chci se tì zeptat na nìco jiného.}
{231}{}{To je všechno. Sbohem.}

# 19 Who's Tyler?
{232}{}{Tyler je jeden hajzlík, kterı nás ostatní, díky tomu svému kšeftíku s Metzgerem, pøipravil o vıdìlek, ale seru na nìj! U je mi to zatracenì jedno. Aèkoliv bych mohl nakopat tu jeho posranou prdel.
 Lara a on se poøád hádají. Má to nìco spoleèného s Tylerem a jejím bratrem.}
{233}{}{To by mohlo bıt uiteèné. Mùeš mi øíct o nich nìco víc?}
{234}{}{Mùu se zeptat ještì na nìco jiného?}
{235}{}{OK, díky. Sbohem.}

# 20. New Reno?
{236}{}{New Reno je daleko dole na jihu, a potom trochu na vıchod. Je tam hodnì rušno, ale taky zatracenì nebezpeèno. Bıt tebou, tak tam nelezu. Ale mùu ti to ukázat na tı tvojí podivnı vìci s obrazovkou.}
{237}{}{Myslím, e teï u to najdu. Mùeš mi o nich øíct nìco víc?}
{238}{}{Mùu se ještì na nìco zeptat?}
{239}{}{OK, díky. Sbohem.}

# 21. Contents?
{240}{}{Peklo, pokud vím.}
{241}{}{Zajímavé. Mùu se tì ještì na nìco zeptat?}
{242}{}{Mùu se tì ještì na nìco zeptat?}
{243}{}{OK, díky. Sbohem.}

# 22.
{244}{}{e jsi to ty, prodám ti Jet za $500.}
{245}{}{Ne, díky. Sbohem.}
{246}{}{Ne, díky, ale rád bych se tì na nìco zeptal.}
{247}{}{To je moc!}
{248}{}{OK, koupím to.}

# 23.
{249}{}{Jestli nemáš peníze, tak pøijï, a si to budeš moct dovolit. Ne abych tì vidìl, e kupuješ od nìkoho jiného, nebo ti nakopu tu tvojí zasranou prdel. Já jedinej mám èistı neøíznutı svinstvo, dodanı pøímo z New Rena.}
{250}{}{Poèkej, koupím to.}
{251}{}{Mùu se tì na nìco zeptat?}
{252}{}{Sbohem.}

# 24.
{253}{}{OK, sníím cenu na $350, ale to je maximum! To je moje koneèná nabídka. Platíš velkı dolary za dobrı svinstvo. Nekupuj od Tubbyho nebo od jinıch, jemu podobnıch, zoufalcù. Ti svoje svinstvo øeout. Já jsem jedinej na míle daleko, kterej mùe nabídnout ten nejlepší materiál.}
{254}{}{Zapomeò na to. Mùu se na nìco zeptat?}
{255}{}{OK, koupím to.}
{256}{}{Nevadí. Sbohem.}

# 25
{257}{}{Vault... Vault... Vault 13? Urèitì jsem o tom nikdy neslyšel. Neøíkej mi, e pøišli s další novou drogou! Nic nemùe bıt lepší ne Jet!}
{258}{}{Ne, ty debile.}
{259}{}{Ne, to je místo. Mùu se na nìco zeptat?}
{260}{}{Ano, skvìlá droga.}
{261}{}{Ne, sbohem.}

# ??Don't know what this is for.
{262}{}{Joey, tady toho není mnoho k rozhovoru.}

# 4. extra
{300}{}{Pravdìpodobnì, ne. Sbohem.}

# Addition for Node 17
{350}{}{Spíš nebo co? Vyšlo najevo, e Lara je pøeci malá dìvka. Ona odpráskla Tylera. Slyšel jsem, e v tom má prsty Metzger. Radìji se vrátím do práce.}
{351}{}{Spíš nebo co? Vyšlo najevo, e Lara pøeci byla malá dìvka -- je špatnı, e je mrtvá. Zametla s Tylerovou grupou. Co jsem naposled slyšel, její gang teï támhle øádí.}
