#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
# 0. Look
{100}{}{Vidíš Laru.}

{150}{}{Je to vùdce tohohle gangu.}

# 1. Start (From Where to go)
{200}{}{Jmenuju se Lara. Vedu tenhle gang. Doufám e nebudeš dìlat ádnı problémy nebo si tì pìknì podáme.}
{201}{}{Nazdar znovu. Potøebuješ nìco?}
{202}{}{Máš nìjakou práci?}
{203}{}{Jenom se rozhlíím.}
{204}{}{Hledám obchodníka co si øíká Vic.}
{205}{}{Aruh.}
{206}{}{Rara.}

# 2. Dumb, bye (From 1, 26)
{220}{}{Ve mìstì nemáme ádnıho doktora. Nemùu ti pomoct.}
{221}{}{Sorry, poøád nerozumím.}
{222}{}{Ack.}

# 3. Vic (From 1)
{230}{}{Na to jméno si nevzpomínám, ale lidi pøichází a odchází. Já je nehlídám. Zkus to u Becky. Tam se ukáou skoro všichni. Tøeba nìco ví.}
{231}{}{Máš nìjakou práci?}
{232}{}{Díky. Zatím.}

# 4. Looking around (From 1)
{240}{}{Jestli jsi do Denu pøišel jenom tak, kvùli nièemu, tak bys mìl jít zase dál. Není to tady moc bezpeènı.}
{241}{}{Jo, dobøe.}
{242}{}{Máš nìjakou práci?}
{243}{}{Dokáu se o sebe postarat.}
{244}{}{Dobøe, dík.}

# 5. Handle (From 4)
{250}{}{O tom nepochybuju. Jinak by ses sem asi ivı nedostal.}
{251}{}{Jo, to u vím. U jsem to slyšel.}
{252}{}{Máš nìjaku práci?}
{253}{}{Oukej, dík.}

# 6. Got work? (From 1, 3-5)
{260}{}{Záleí na tom, k èemu se hodíš. Je tu nìco co mì zajímá. Jestli se ti to podaøí, nìco ti z toho kápne.}
{261}{}{Jak jsem øíkala, sháním o nìèem... nebo o nìkom nìjaké informace. Samozøejmì zaplatím.}
{262}{}{Jasnì. O co jde?}
{263}{}{Moná pozdìji.}

# 7. Bye, let me know if mind changes (From 6)
{270}{}{Kdy si to rozmyslíš, dej vìdìt.}
{271}{}{Dobøe.}

# 8. Setting Crates (From 6)
{280}{}{Tak, na vıchod odtud je kostel. A u je uvnitø cokoliv, Metzgerovi lidi to velice dobøe hlídají. Zjisti co to je a máš u mnì $200.}
{281}{}{To je jednoduchı. To u dávno vím.}
{282}{}{Jasnì.}
{283}{}{Uvidím co se dá dìlat.}

# 9. Thanks (From 8)
{290}{}{Díky. Nezamíchej se do bitky... zatím. Mám plán.}
{291}{}{ádnı problém.}
{292}{}{Hned se vrátím.}

# 10. Crates Answered (From 8)
{300}{}{Tak co tam je?}
{301}{}{Èisté chemické slouèeniny ve velkıch baleních.}
{302}{}{Nìjakı chemikálie ve velkıch kontejnerech.}
{303}{}{Ještì se na to radši mrknu.}

# 11. Crates Answered (From 10, 18)
{310}{}{Hmm. To dává smysl. Díky. Tady máš peníze.}
{311}{}{Co dává smysl?}
{312}{}{ádnej problém. Zatím.}

# 12. Makes Sense? (From 11)
{320}{}{Vidìli jsme pøijídìt karavany z Vault City a pak nìco pøekládali do karavan z New Reno.}
{321}{}{Jo? A co to znamená?}
{322}{}{Oh.}

# 13. Makes Sense, Bye (From 12)
{340}{}{New Reno je hlavní drogové mìsto. Odnìkud musí získávat materiál, ze kterého dìlají drogy a léky, jasnı? Vypadá to, e nìco nebo všechno berou z Vault City.}
{341}{}{Kde je New Reno?}
{342}{}{Oukej, díky.}

# 14. Located? (From 13)
{350}{}{Pøesnì to nevím. Nìkde na jihu, myslím. Nikdy jsem tam nebyla, jenom vidím, jak se tu jednou za èas zastaví karavany pro zásoby -- jednou za dlouhı èas.}
{351}{}{Oh, dobøe. Díky.}

# 15. (From 11-14)
{360}{}{Nehodily by se ještì rychle peníze? $50. Snadnı prachy.}
{361}{}{Jasnì.}
{362}{}{Ale rychle.}

# 16. Set Ask (From 15)
{370}{}{Potøebuju zjistit od Metzgera, jestli mu nebude vadit, kdy si s Tylerem vyøídím nìjakou starší záleitost. On u bude vìdìt.}
{371}{}{Proè se mám jít zeptat já?}
{372}{}{Mùu to zkusit}
{373}{}{Oukej.}

# 17. Why PC ask Metzger (From 16)
{380}{}{Protoe nechci, aby Tyler vidìl nìkoho z mıch lidí chodit kolem Metzgera. Nechci, aby se to profláklo.}
{381}{}{Ty to nechápeš? Jestli mì Tyler uvidí, jak se najednou bavím s Metzgerem mùe mu dojít, e se nìco pøipravuje.}
{382}{}{Uvidíme.}
{383}{}{Oukej.}

# 18. On Crate Quest (From WTG)
{390}{}{Tak co, u víš, co tam je?}
{391}{}{Èisté chemické slouèeniny ve velkıch baleních.}
{392}{}{Nìjakı chemikálie ve velkıch kontejnerech.}
{393}{}{Ještì ne.}

# 19. Ask/Permission (From WTG)
{400}{}{Tak co? Domluveno? Co øíkal?}
{401}{}{Není proti. Jestli vyhraješ, mùeš mít jejich dob, jako pøedtím.}
{402}{}{Ee.}

# 20. Permission Done (From 19)
{410}{}{Super. V to jsem doufala. Slyšela jsem, e si na nìj v poslední dobì stìoval. Tady jsou prachy.}
{411}{}{Pøedpokládám, e teï máš ještì nìco?}
{412}{}{Díky. Zatím.}

# 21. Wait, need info... (From 20)
{420}{}{Mám pro tebe ještì jednu práci. Nejsem si jistá jak to udìláš, ale kdy u ses dostal dovnitø, moná ti vìøí.}
{421}{}{Dovnitø jsem se proplíil.}
{422}{}{O co jde?}

# 22. Snuck (From 21)
{430}{}{Jsem si jistá, e nìco vymyslíš.}
{431}{}{Dobøe, o co jde?}

# 23. Setting Find (From 20-22)
{440}{}{Pøi téhle síle na nì nemáme. Mají víc prostøedkù a dokonce je jich víc ne nás. Kdyby se podaøilo najít nìjakou slabinu, pomohlo by nám to vyrovnat pøevahu. Nebo nìco, èeho by se dalo vyuít...}
{441}{}{Huh? Najít slabinu? A jak to mám asi udìlat?}
{442}{}{Kolik?}
{443}{}{Jako by to u bylo hotovı.}

# 24. How Much? (From 23)
{450}{}{Dáme ti $150. Nemùeme se dostat dost blízko, abychom na to pøišli sami.}
{451}{}{Kdy bude pøíleitost, zkusím to.}
{452}{}{Oukej.}

# 25. Weakness??? (From 23)
{460}{}{Nevím. Proto tì ádám o pomoc.}
{461}{}{Zkusím to.}
{462}{}{Tohle nemá cenu.}

# 26. Find/Weakness report (From WTG)
{470}{}{Tak co? Jak to vypadá?}
{471}{}{Mám to. Dnes v noci budou mít párty.}
{472}{}{Ještì nevím. Dám vìdìt.}
{473}{}{Gra.}
{474}{}{Na.}

# 27. Skeleton crew(From 4)
{480}{}{Vıbornì! Urèitì tam nechají jenom základní ostrahu. Na ty máme férovı šance. A a udìláme kostel, sejmeme ty ostatní na párty.}
{481}{}{A moje peníze?}

# 28. Money ? (From WTG & 27)
{490}{}{Ještì ne. Jestli chceš peníze, musíš do toho s námi. Nebudeš muset bojovat, ale budeme si jistí, e to není past. Dáme ti potom $300.}
{491}{}{Jdem na to?}
{492}{}{Dobøe, tak do toho.}
{493}{}{Dejte mi chvilku, musím se pøipravit.}
{494}{}{Ani za nic. Nechejte si ty prachy!}

# 29. Wait to fight. (From 28, 30)
{500}{}{Fajn, ale musíme se do toho pustit brzy, take a ti to netrvá moc dlouho. Tohle je naše šance.}
{501}{}{Oukej.}

# 30. Coward (From WTG & 28)
{510}{}{Nemusíš bojovat. Snadnı prachy.}
{511}{}{Tak co, rozmyslel sis to?}
{512}{}{Tak jdeme. Jsem pøipraven.}
{513}{}{Oukej, hned se vrátím.}
{514}{}{Ne.}
{515}{}{Uk}

# 31. CF: No Show (From WTG)
{520}{}{Kvùli tobì jsme prošvihli naši šanci.}
{521}{}{Zbabìlèe!}
{522}{}{Nic nedostaneš.}
{523}{}{Asi to byla past.}
{524}{}{Sorry, nejsi spolehlivı partner.}
{525}{}{Nemùu ti vìøit.}

# 32. CF: 2 Won (From WTG)
{530}{}{Dokázali jsme to!}
{531}{}{Díky za pomoc.}
{532}{}{Zvláš tobì díky!}
{533}{}{Koneènì jsem Tylerovi oplatila, co udìlal mému bráchovi.}
{534}{}{Ještì jednou dík.}

# 33. CF: Metzger Dead (From WTG)
{540}{}{Teï kdy Metzger skapal, nevím co se stane.}
{541}{}{Moná bychom to mìli zabalit.}
{542}{}{U se ti doneslo, e Metzger je mrtvej? Nevím co budu dìlat.}
{543}{}{Co se tu v Denu stane? Moná se nìco zlepší.}
{544}{}{Vlastnì by se to teï mìlo zlepšit.}

# 34. CF: Hostile (From WTG)
{550}{}{Bastarde!}
{551}{}{Dìvko!}

# 35. CF:  Reward (From WTG)
{560}{}{Díky. Tady máš prachy a $100 navrch.}

# 36. Gang Dead (From WTG)
{570}{}{Tyler a jeho stráe jsou mrtví? A jak to teï dokáeme Metzgerovi? Teï se s náma u nebude bavit. To byla naše jediná šance.}
{571}{}{Nemáme ádnou práci. Nìkdo sejmul Metzgerovy stráe a on s námi nemluví. Myslí si, e jsme to byli my. Ach jo.}
{572}{}{To mì mrzí.}
{573}{}{To je blbı.}
{574}{}{To jsem byl já, a hádej kdo je na øadì teï.}
{575}{}{Oh. Dobøe, zatím.}
{576}{}{Uhr?}
{577}{}{Ug.}

# 37. Gang Dead Cont. (From 36)
{590}{}{Øekla jsem ti, e pùjdeme a spolu. Protoe to tam teï nikdo nehlídal, nìkdo to vyloupil a Metzger se fakticky nasral.}
{591}{}{Øekla jsem ti najdi slabinu, ne sejmi je! Protoe to tam teï nikdo nehlídal, nìkdo to vyloupil a Metzger se fakticky nasral.}
{592}{}{Do hajzlu! Øekla jsem promluv s Metzgerem a ne sejmi je! Protoe to tam teï nikdo nehlídal, nìkdo to vyloupil a Metzger se fakticky nasral.}
{593}{}{Do hajzlu! Øekla jsem bez bitky! Protoe to tam teï nikdo nehlídal, nìkdo to vyloupil a Metzger se fakticky nasral.}
{594}{}{Ehm, no, u musím jít.}
{595}{}{To je ale smùla.}
{596}{}{Teï jsi na øadì ty, dìvko.}
{597}{}{Hmph!}
{598}{}{Ty další.}

# 38. CF: Next times Gang Dead (From WTG)
{610}{}{Ty fakt umíš vìci poøádnì podìlat, víš to?}
{611}{}{U tvoji pomoc nebudeme potøebovat.}
{612}{}{Bì otravovat jinam.}
{613}{}{Snad proti nám Metzger nic nepodnikne.}
{614}{}{Je mi líto. Nemùu ti pomoct.}
{615}{}{Nemùu mluvit. Snaím se vymyslet, co teï.}
{616}{}{Doufám e si Metzger nemyslí, e za to mùeme my.}
{617}{}{Co teï budeme dìlat?}
{618}{}{Radši bychom mìli vypadnout, kdyby si Metzger myslel, e jsme mu sejmuli stráe.}
{619}{}{U jsi byl v New Reno? Moná tam zamíøíme -- nebo na sever.}

# 39. Running to Fight
{650}{}{Dobøe! Jde se na to! Všichni za mnou!}
