#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
# 0. Look
{100}{}{Vidíš stráž.}
{101}{}{Vidíš Marca, strážce.}
{102}{}{Vidíš Marca, jednoho z Tylerových stráží.}

# 1. Door opened
{150}{}{Jo, Tyler!}

# 2. Hostile
{200}{}{Co...?}

# 3. Gang 1 Won War
{225}{}{Vìdìl jsem, že jsme mohli ty kundy sebrat.}
{226}{}{Díky za výlet. Byla to dobrá hlína.}
{227}{}{Dost blbý, že jsme je všechny zabili. Co teï budeme dìlat?}
{228}{}{Jsme skvìlý?}
{229}{}{Jsme dobrý.}
{230}{}{Pìknì jsme jim natrhli prdel!}

# 4. TRAP NO
{250}{}{Tyler je ten, s kým mùžete mluvit, dámo, ne se mnou.}
{251}{}{Co se dìje. Jestliže nìco potøebujete, promluvte si tady s Tylerem.}
{252}{}{Na co koukáte?}
{253}{}{Tyler je ten, s kým mùžete mluvit, chlape. Ne se mnou.}

# 5. TRAP SET
{255}{}{Dnes v noci se chystáme nìkomu natrhnout prdel!}
{256}{}{Dnes bude noc s velkým N!}
{257}{}{Tuhle noc si budeme pamatovat.}
{258}{}{Neøíkej mi pøece, že jsou posraný strachem.}
{259}{}{Doufám, že nìco pøedvedou.}

# 6. TRAP NOSHOW
{260}{}{Vìdìl jsem, že ty mrchy nic nepøedvedou.}
{261}{}{Mìli jsem jim natrhnout prdel, jen proto, aby si nemysleli, že nás pobijou.}
{262}{}{Kdyby se bývali ukázali, rozprášili bychom je.}
{263}{}{Mohl jsem je porazit sám.}
{264}{}{Tyler a já bychom jim natrhli prdel.}
