#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš majitelku saloonu.}
{101}{}{Vidíš Becky.}

{150}{}{Vypadá to, e jí to tu všechno patøí.}
{151}{}{To je Becky, majitelka tohoto místa}
{152}{}{[MLUVIT]}
{153}{}{Dobrı den, cizinèe, a vítej v mém saloonu. Já jsem Becky.}
{154}{}{Dobrı den, já jsem }
{155}{}{. Co se dá tady v okolí dìlat?}
{156}{}{Ahoj, já jsem }
{157}{}{. Mohu vám poloit nìkolik otázek?}
{158}{}{Máma?}
{159}{}{Mag gah.}
{160}{}{Bì jinam. Nepotøebuju tì tady.}
{161}{}{Mmmm...}
{162}{}{Kašlu na tebe.}
{163}{}{Jdu.}
{164}{}{Promiòte, nemyslel jsem to tak. Mùu se na nìco zeptat?}
{165}{}{Panák whiskey je za $5 a hrací stoly jsou pøímo támhle. Uijte si je.}
{166}{}{Mùu se na nìco zeptat?}
{167}{}{Dám si panáka!}
{168}{}{Hmm, tyhle drinky jsou docela levné. Zkusme jeden.}
{169}{}{Díky. Sbohem.}
{170}{}{Vault 13? Urèitì jsem o tom neslyšela.}
{171}{}{Hmm, mohu se vás ještì na nìco zeptat?}
{172}{}{Zatracenì, musím to najít. Nashle.}
{173}{}{Co by´s rád vìdìl?}
{174}{}{Kde se dá dobøe najíst?}
{175}{}{Víš, kde je Vault 13?}
{176}{}{Proè jsou tvoje drinky tak levné?}
{177}{}{Nic. Sbohem.}
{178}{}{Máma provozuje malou restauraci za mìstem.}
{179}{}{Mámo! Mámo!}
{180}{}{Ještì jeden dotaz.}
{181}{}{Díky. Nashle.}
{182}{}{Obejdi to.}
{183}{}{Gwah.}
{184}{}{Dám ti nìco, èím to obejdeš.}
{185}{}{Nejdøíve rychlá otázka?}
{186}{}{Sbohem.}
{187}{}{Panák whiskey je za $5. Zapla pøedem.}
{188}{}{Huh?}
{189}{}{Tady jsou peníze.}
{190}{}{Rozmyslel jsem si to.}
{191}{}{Mám málo hotovosti. Mohu dostat stùl?}
{192}{}{Mohu se zeptat?}
{193}{}{Asi pùjdu.}
{194}{}{Tady je ten drink. Ještì nìco jiného?}
{195}{}{Otázku?}
{196}{}{Jo, co takhle ty a já...}
{197}{}{To urèitì ne.}
{198}{}{Hej, na ten drink nemáš dost penìz. Jsi chudší, ne tihle notoøi!}
{199}{}{Je mi líto.}
{200}{}{Hmm, vrátím se tam, odkud jsem pøišel.}
{201}{}{Hmm. Poèkej skoèím pro nìkoho, kdo mi pohlídá bar. Ty a já mùeme jít do zadního pokoje a zahrát si hru, které øíkám "První útok". Jestli budeš dobrı, tak potom bude následovat "Hladké Pøistání."}
{202}{}{Oukej!}
{203}{}{Er...uh...Musím jít.}
{205}{}{Byl jsi skvìlej.}
{206}{}{Pøíštì si zahrajeme "Do áru." Ale teï...}
{207}{}{Mùeš pro mì nìco udìlat?}
{208}{}{Musím jít, ale já se vrátím.}
{209}{}{Co pro tebe mohu udìlat, puso?}
{210}{}{Potøebuji ještì víc lásky.}
{211}{}{Mám nìkolik otázek.}
{212}{}{Jak mùeš prodávat svoje drinky tak levnì?}
{213}{}{Co takhle panáka?}
{214}{}{U pobìím. Mìj se.}
{215}{}{Teï ne. Moná pozdìji, o trochu pozdìji.}
{216}{}{Mùu se zeptat?}
{217}{}{Tak pozdìji.}
{218}{}{Destilaèní zaøízení mám v pøízemí. Udìlala jsem si ho sama. Nebudu pøece tìm gangsterùm z New Rena platit tøikrát tolik.}
{219}{}{Chytrá holka! To mám rád!}
{220}{}{Hmm, musím jít. Uvidíme se pozdìji.}
{221}{}{Proè? Proè jsi znièil moje destilaèní zaøízení? Ty bastarde!}
{222}{}{Nic osobního. Dostal jsem za to zaplaceno.}
{223}{}{Je mi líto.}
{224}{}{Sbohem.}
{225}{}{Udìlám si jínı, aby´s vìdìl.}
{226}{}{Já vím.}
{227}{}{Tak je to správné.}
{228}{}{Sbohem.}
{232}{}{Proè? Proè jsi znièila moje destilaèní zaøízení? Ty dìvko!}

{233}{}{Kde jsi, miláèku?}
{234}{}{U jdeš?}
{235}{}{Já èekám.}
{236}{}{Jsem tu, miláèku.}

{237}{}{Mám tady bar...}
{238}{}{Pojï za mnou, cukroušku.}

{240}{}{Jak jsi ... to udìlal... Uhhh...}
{241}{}{Je to Oukej, velikost nerozhoduje.}
{242}{}{Bylo to, ummm, hezkı -- myslím.}
{243}{}{Díky cukroušku; byla to zábava.}
