#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
# 0. Look
{100}{}{Vidíš chlapa, co má blbou náladu.}
{101}{}{To je Metzger, mistr otrokáø.}

{150}{}{Metzger je hlava otrokáøského cechu.}

# 1. CF: Hostile (From WTG)
{200}{}{Za to mi zaplatíš.}

# 2. 1st Time, Self Initiated (From 2-WTG)
{210}{}{Co tu kurva chceš? Tohle je Cech otrokáøù a ne nìjakej útulek
 pro vás, posranı feáky.}
{211}{}{Co tu sakra chceš, hnusná kurvo? Tohle je Cech otrokáøù
 a ne posranej bordel.}
{212}{}{Co tu sakra chceš, kurvo? Tohle je Cech ortokáøù
 a ne posranej bordel.}
{213}{}{Zaèínáš mì srát. Co hergot chceš teï?}
{214}{}{Co teï, sakra?}
{215}{}{Co?}
{216}{}{Hm, vyøiï to rychle.}
{217}{}{Jdeš pracovat za pár posranejch drobákù?}
{218}{}{Zaèínám si na tu tvoji hnusnou drku zvykat. Tak... máš dùvod e tu seš?}
{219}{}{Vypadám, jako tvùj posranej fotr nebo co? Kurva doufám, e ne. Tak to vyblej, co chceš?}
{220}{}{Ale podívejme, kdo je tady. Myslíš, e seš nìco extra, nebo co? Spus, nebo kurva vypadni.}
{221}{}{Co chceš teï, otrokáøi?}
{222}{}{To tam budeš furt stát, nebo taky nìco øekneš?}
{223}{}{Mluv. Na tyhle sraèky nemám celej den.}

# 3. Selling NPC (From 5, 13)
{230}{}{Oh, a 'kdo' to bude? Doufám e neèekáš, e ho ještì nìkdy uvidíš...}
{231}{}{Nemáš nikoho, o koho bych mìl zájem. Zajímají mì jenom lidi --
 ti normální, jasnı?}
{232}{}{Ty posranej kreténe, co si myslíš, e sem? Zasranej sklad nebo co? Jestli seeneš otroka na prodej, dej mi vìdìt. Jestli chceš prodat nìco jinıho, jdi do posranıho obchodu.}
{233}{}{Miria}
{234}{}{Davin}
{235}{}{Vic}
{236}{}{Myron}
{237}{}{MacRae}
{238}{}{Sulik}
{239}{}{Mohl bych se ještì na nìco zeptat?}
{240}{}{Rozmyslel jsem si to. Zatím.}

# 4. Before PC responses (From ?Everywhere?)
{245}{}{Tak do toho.}
{246}{}{Jo?}
{247}{}{Nejsem tvùj posranej sluha, tak zrychli.}
{248}{}{Tak co je? Nemám celej den.}
{249}{}{Mluv.}
{250}{}{Moná.}

# 5. Main body, yes? (From 3)
{255}{}{Mám nìco, co bych rád prodal.}
{256}{}{Co se tıká Vica...}
{257}{}{Hledám obchodníka.}
{258}{}{Lara si to chce vyøídit s Tylerem.}
{259}{}{Mùu se pøidat k cechu?}
{260}{}{Co mi mùeš øíct o cechu?}
{261}{}{Chci jít na hon na otroky.}
{262}{}{Ale nic. Zatím.}
{263}{}{ chce do cechu.}
{264}{}{Na.}

# 6. Want to join slaver's guild? (From 5, 7, 8)
{270}{}{Myslíš, e to zvládneš? Neberu hned tak nìkoho... Sakra. jestli nìco posereš, tak tì prostì prodám. Musíš si nechat vytetovat na èelo, e jsi u otrokáøù, aby to kadı poznal. Je to navdy, tak bacha na to.}
{271}{}{Tak, naše roztomilá kvìtinka, holèièka se vrátila... Tak co, pùjdeš do toho? Necháš se nakonec potetovat?}
{272}{}{Jo, snad to pùjde... K tomu jít na lov moc mozek nepotøebuješ. A jestli nìco zkurvíš, tak tì prostì prodám. Jestli myslíš, e to zvládneš, musíš si nechat vytetovat na èelo, e si u otrokáøù, aby to všichni vìdìli.}
{273}{}{Jdu do toho.}
{274}{}{Musím si to rozmyslet. Ještì pøijdu zpátky.}
{275}{}{Asi ne. Zatím.}
{276}{}{Uya! (kıvnutí)}
{277}{}{Ne, ne, ne, ne a ne!}

# 7. Tell me about Guild (From 4)
{285}{}{Co kurva si myslíš? Tohle je otrokáøskı cech. Kupuju a prodávám otroky.}
{286}{}{Kde berete otroky?}
{287}{}{Chci se pøipojit.}
{288}{}{Ještì další otázku.}
{289}{}{Oh, dobøe. Zatím.}

# 8. Slaves from? (From 7)
{300}{}{Jo, tady a taky tam. Vìtšinou sbíráme primitivy a nomády, kdy na nì narazíme.}
{301}{}{To mùe bıt sranda. Jak se k tomu mùu dostat?}
{302}{}{Mám další otázku.}
{303}{}{Oh, oukej. Nashle.}

# 9. Self Initiated, Just got Tattoo (From WTG)
{310}{}{Tak vidíš, ani to tak nebolelo. Jsem na tebe tak pyšnej... vlastnì to tetování ti fakt sluší. A budeš chtít na svùj první hon na otroky, dej vìdìt.}
{311}{}{Dík. Zatím.}
{312}{}{Jdeme na to teï.}
{313}{}{Já zabíjet TEÏ!}
{314}{}{Fajn.}

# 10. Slave Run (From 9)
{320}{}{Dva moji chlapi tì zavedou dost blízko k cílùm. Tvùj plat bude záviset na poètu otrokù kterı pøivedeš, ale dávej si bacha. Jestli nìkdo zaklepe beèkorama, strhnu ti to z platu, e se budeš divit.}
{321}{}{Sakra, u tu nikdo není. Musíme poèkat, a se do oblasti zase nastìhujou nìjací primitivové. Moná bychom je mìli zaèít pìstovat.}
{322}{}{Sorry, ale ty se mi nevyplatíš. Velkı ztráty a tohle je obchod. Potøebuju vydìlávat peníze, ne je ztrácet.}
{323}{}{Dobøe. Jsou pøipravení.}
{324}{}{Fajn, teï mùeš jít.}
{325}{}{Tak jdi na to.}
{326}{}{Dobøe. A skonèíš, zastav se u mnì.}
{327}{}{Oukej.}
{328}{}{Uh.}

# 11. Slave Run Description (From 10)
{340}{}{Prostì zabij všechny agresivní. Jestli zaútoèí, zab je. Nechci s nima u nic mít, mám i tak hodnì posranejch potíí. A skonèíš, ostatní otrokáøi seenou zbytek dohromady a oznaèkujou je.}
{341}{}{Jasnì.}
{342}{}{Oh.}

# 12. Slave Run Description 2 (From 11)
{350}{}{Jak zaènou otroky znaèkovat, mùeš se vrátit jestli chceš. Je na to potøeba speciální vıcvik, tak se do toho radši nemontuj. Mùeš dìlat cokoliv budeš chtít, jenom nesmíš poškodit zboí.}
{351}{}{Jasnì.}
{352}{}{Ehm, aha.}

# 13. Selling other NPCs (From 3)
{360}{}{Ah, jasnì. Je celkem hezká. Dám ti za ni $}
{1360}{}{. Co ty na to?}
{361}{}{Je v poøádku. Moná bych ho od tebe vzal za, hmm, øeknìme $}
{1361}{}{?}
{362}{}{Posranej idiote. Proè si kurva myslíš, e chci toho debila zpátky? Dy mu trvalo
 vìènost ne spravil to blbı rádio! Rádio! Vra si ho nìkam. Nechci aby tu zase nìco rozbil.}
{363}{}{Nevím, vypadá moc vychrtle... je alespoò chytrej? To by mohlo mít cenu. Dám ti $}
{1363}{}{.}
{364}{}{Tenhle vypadá, e by mohl bojovat opravdu dobøe. Hmm... $}
{1364}{}{.}
{365}{}{Další primitiv. Ten je z domu hrùzy. Ale vypadá silnì. To by mohlo vynést nìco navíc. Co $}
{1365}{}{?}
{366}{}{A co nìkdo jinej?}
{367}{}{Tak, ještì se tì na nìco zeptám.}
{368}{}{Oukej.}
{369}{}{Fajn.}
{370}{}{Oukej.}
{371}{}{To nemá ádnou cenu.}
{372}{}{Ne.}

# 14. NPC Sold SPECIAL DIALOG (From 13)
{380}{}{Tak dobøe, chlapi, strète ho do ohrady.}
{381}{}{Tak dobøe, chlapi, strète ji do ohrady.}
{382}{}{Jasnì, šéfe.}

# 15. Turned down Selling NPC (From 13)
{390}{}{Tak sakra neotravuj. Jestli dostaneš nìco, o co bych mìl zájem,
 pøijï se ukázat.}
{391}{}{Mám další otázku.}
{392}{}{Oukej. Zatím.}

# 16. Permission (From 5)
{400}{}{Co to do ní kurva tak najednou vjelo? U sem té èubce jednu šanci dal. Nemyslel jsem si, e bude mít aludek na tohle.}
{401}{}{O èem to mluvíš?}
{402}{}{Take je to v poøádku?}

# 17. What kind of outfit... (From 16)
{410}{}{Ale no tak, nedìlej ze sebe blbce. Vím pøesnì co chce udìlat. U jsem jí dal šanci a nemìla na to, ale jestli si myslí, e to teï zvládne...}
{411}{}{Tak, je to v poøádku?}

# 18. So it's okay? (From 17)
{420}{}{No, øek sem e nabídka bude platit. Jestli si myslí, e mu nakope prdel a bude líp hlídat moje vìci...}
{421}{}{Tak?}
{422}{}{Take to znamená ano?}

# 19. Permission Granted (From 18)
{430}{}{Podívej, je mi u prdele, kdo to hlídá. Dokud bude moje zboí v bezpeèí, je mi to jedno.}
{431}{}{Ještì otázku, prosím.}
{432}{}{Fajn, dík.}

# 20. I'm looking for a Merchant (From 5, 20)
{440}{}{Tak co kurva lezeš za mnou? Vypadám snad jako nìjakej posranej... oh, poèkej. Ty hledáš Vica, e jo?}
{441}{}{To je ten co se 'specializuje' na vault technologii, nebo jak tomu øíká. On je teï mùj. Nikam nepùjde.}
{442}{}{Co je s ním?}
{443}{}{Jo, to je on.}
{444}{}{Mùu ho navštívit?}
{445}{}{Proè ho tady dríš?}
{446}{}{Dobøe, díky. Zatím.}

# 21. Radio Fix/Not Fixed (From 20)
{455}{}{Ten malej kokot -- prodal mi rádio a øíkal, e na nìm chytnu nìjakı pøenosy. Ale nešlo. Chytil sem ho za prdel, jak se snail proklouznout z mìsta, ne na to pøijdu. Chyba. Se mnou nikdo takhle nevyjebe. Má štìstí, e je ještì ivej.}
{456}{}{U jsem øekl. Musí napøed nìco spravit. Potom uvidíme.}
{457}{}{No, koneènì to rádio zprovoznil, ale to neznamená, e ho nechám jít tak lehce.}
{458}{}{Poøád mì zkoušel pøechcat.}
{459}{}{Mùu ho vidìt?}
{460}{}{O jakıch pøenosech to mluvíš?}
{461}{}{Oukej, díky.}
{462}{}{Moná by to spravily nìjakı prachy?}
{463}{}{O jakıch pøenosech jsi to pøedtím mluvil?}

# 22. Set See Vic is Okay (From 20-21)
{475}{}{Proè? Ale, kurva, proè ne. Hlavnì ho nezdruj od práce na tom podìlanım rádiu -- mìl by hejbnout kostrou. Zaèíná mì štvát, e si ho tu vydruju.}
{476}{}{Proè ho tady dríš?}
{477}{}{Díky.}

# 23. Transmissions (From 21)
{485}{}{Enclave a New... hej. Co se hergot staráš? To je obchod. Potøebuju si bejt jistej, e se mnou nechce nikdo vyjebat. Víc vìdìt nepotøebuješ.}
{486}{}{Hleï si svıho.}
{487}{}{Dobøe.}

# 24. Pay for Vic (From 21, 23)
{495}{}{Jasnì, ale bude tì stát $}
{496}{}{$}
{1496}{}{.}
{497}{}{Nemùeme nìco vymyslet?}
{498}{}{Fajn. Tady.}
{499}{}{Mùu se tì napøed na nìco zeptat?}
{500}{}{Sorry, tolik si zatím nemùu dovolit.}

# 25. Bought Vic (From 24)
{510}{}{Dobøe, je tvùj, ale a rychle vypadne, ne si to rozmyslím a narvu mu do tı jeho posrané hlavy spoustu olova.}
{511}{}{Mùu se tì napøed na nìco zeptat?}
{512}{}{Díky.}

# 26. Female Sex (From 24)
{520}{}{Ale, ano. Mùeme všechno pìknì a èistì urovnat... Polovinu ti slevím, kdy to s tebou bude stát za to...}
{521}{}{Radši mì pøestaò drádit, kocoure. Nemám moc trpìlivosti.}
{522}{}{Jenom, jestli na mì budeš hodnej.}
{523}{}{Jasnì, proè ne.}
{524}{}{Moná pozdìji.}

# 27. Good to me (From 26)
{530}{}{Oh, vìø tomu.}
{531}{}{Dobøe.}

# 28. Paying for Run (From WTG)
{540}{}{Tady je $}
{1540}{}{. Kurevsky pìkná prácièka.}
{2540}{}{.}
{541}{}{Tady je $}
{1541}{}{. To se fakt povedlo. Vydr.}
{542}{}{Dobrá práce tam venku. Tady je $.}
{1542}{}{.}
{543}{}{Tady máš svoje prachy .}
{1543}{}{, $.}
{2543}{}{.}
{544}{}{$.}
{1544}{}{ není nic èemu by se dalo smát, ale mùeš si vydìlat daleko víc.}
{545}{}{Tak tentokrát to bude $}
{1545}{}{. Dost dobrá práce.}
{546}{}{Nebylo to tak zlı, e ne? Pøíštì ádnı chyby. Tady je $.}
{1546}{}{.}
{547}{}{$}
{1547}{}{? Nebylo to špatnı.}
{548}{}{No tak! $.}
{1548}{}{? Jde to udìlat i líp.}
{549}{}{Pamatuj si, dávej bacha a zabíjej jenom agresivní otroky. Tady je $.}
{1549}{}{.}
{550}{}{Jenom $.}
{1550}{}{! To bylo sakra slabı! Zlepši to, nebo ti nakopu prdel.}
{551}{}{Chceš vydìlávat prachy nebo ne? Sereš mì. Dy to kurva není tak tìkı. Teï si vem svıch $.}
{1551}{}{ a vypadni.}
{552}{}{Do hajzlu, v èem je problém? Nevydìláš si ani hovno. Jsme tu kvùli penìzùm, ne kvùli onanování.}
{553}{}{Pøíštì to bude lepší.}
{554}{}{Dík za nic.}
{555}{}{Dík}
{556}{}{Ug.}

# 29. (From WTG)
{570}{}{Sakra kurvo, to bylo poprvı? To není monı, e tohle nebylo poprvı.}
{571}{}{Sakra krávo, tohle bylo poprvı?}
{572}{}{Dost dobrı, myslím.}
{573}{}{Hodnì dobrı, moná bychom si mohli nìkdy zase skoèit.}
{574}{}{Sakra! To bylo... velice dobøe utracené peníze.}
{575}{}{Sakra! Bylas nejlepší kost jakou sem kdy mìl, a mìl sem jich fakt dost.}

# 43. Abandon Slave Run
{600}{}{JSI POSRANEJ DEBIL! Jak ses odváil nechat tam venku kámoše? (Plive ti do oblièeje) ZABTE HO!}
{601}{}{Ale já...}
{602}{}{Tak jo, dem na to.}

# 30. Returned from run, attacked slaver and lived to tell about it. (From WTG)
{620}{}{No, je hezkı vìdìt, e si tu zpátky.}
{621}{}{Jo, byl to drsnej hon.}
{622}{}{Díky. Tam venku se vìci trochu pøiostøily.}
{623}{}{Agra Moo ne!}

# 31. Dumb hostile run (From 30)
{630}{}{Oh, ty chceš peníze? Ty chceš vıplatu?}
{631}{}{Joj.}
{632}{}{Ugh.}

# 32. Dumb 2 (From 31)
{640}{}{Samozøejmì MOC RÁD bych ti nìco dal... ale je tu malı problém... nìco o útoku na jednoho z našich.}
{641}{}{Sorry! Já sem nechtìl -- já nechtìl... Ug?}
{642}{}{Uh, oh.}

# 33. Dumb 3 (From 32)
{650}{}{Oh, neboj se. Ze srdce rád ti vyplatím -- vlastnì oplatím. Chlapi, je vıplata.}
{651}{}{Oh, neboj se. Ze srdce rád ti vyplatím -- vlastnì oplatím. Chlapi, sejmìte tu èubku.}
{652}{}{Oops.}
{653}{}{Garaka!}
{654}{}{Uh... Tank?}

# 34. Tough run, hostile (From 30)
{670}{}{Jo, to u vím. Tenhle druh obchodu není nic jednoduchıho. Je tøeba dùvìra a loajalita. Dáváme bacha jeden na druhıho. Dobrı zásady, nemyslíš?}
{671}{}{Myslím, e jo.}
{672}{}{Uh, co se dìje?}
{673}{}{Urèitì.}

# 35. I guess (From 34)
{680}{}{Ty myslíš? Neèekal jsem, e ti myšlení tak pùjde. Fakt jsi pìknej debil.
 [Metzger na tebe chvíli èumí, pak se podívá na stráe a mávne rukou tvojím smìrem.]}
{681}{}{Akce?}
{682}{}{Co?}

# 36. What's going on? (From 34)
{690}{}{Ja, tak ze sebe nedìlej takovıho vola. Je to pod úroveò. Vidíš, mám nìjaké dilema. Nìkdo zaútoèil na moje mue.}
{691}{}{Opravdu?}
{692}{}{To byla nehoda!}

# 37. Definitely (From 34)
{700}{}{Opravdu? Jsem rád, e souhlasíš. A co máme dìlat, kdy nìkdo ztratí naši dùvìru?}
{701}{}{Asi, dát jim vıstrahu?}
{702}{}{Tohle. Ukáu vám to. [zaútoèit]}
{703}{}{Nechat je zaplatit.}

# 38. Trust, warn? (From 37)
{710}{}{Myslíš? Opravdu? Já nevím. Já jsem pøemıšlel o nìèem trochu... trvalejším. (Metzger se škaredì zašklebí, podívá se na stráe a kıvne.)}
{711}{}{Co?}
{712}{}{A sakra...}

# 39. Trust Pay? (From 37)
{720}{}{Jsem rád, e se shodneme. (Metzger se podívá na stráe.) Chlapi, vıplata.}
{721}{}{Uh...}

# 40. Really? (From 36)
{730}{}{Ano. Opravdu ostuda. Ta osoba si to neuvìdomuje, ale oni jo.
 (Vidíš, jak Metzger dìlá malé gesto rukou ke svım gorilám.) Zábava.}
{731}{}{Opravdu?}
{732}{}{Uh oh.}

# 41. Accident? (From 36)
{740}{}{Ano, obávám se, e nehody se tu stávají dost èasto. Vlastnì se bojím, e tu brzo bude další. (Metzger se usmìje a kıvne smìrem ke svım gorilám.)}
{741}{}{Tak jdem na to!}
{742}{}{Z tohohle se nedostanu, nebo jo?}

# 42. Getting out? (From 41)
{750}{}{Oh, ale bude to zábava. Vìø mi.}
{751}{}{Jdi do prdele.}
{752}{}{Uh, tak jo.}

{800}{}{Zabil jsi vùdce Cechu otrokáøù.}
