#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
# 0. Look
{100}{}{Vidíš pøísného otrokáøe ve støedních letech.}
{101}{}{Vidíš pìknì rostlého otrokáøe.}

{150}{}{Jedná se o otrokáøe, který vypadá, že ho jeho práce baví.}
{151}{}{Tento otrokáø vypadá, že je velmi silný, ale ne moc chytrý.}

# 1. Metzger's Bedroom Guard (2nd Time = Hostile)
{200}{}{Vypadni sakra od tìch dveøí.}
{201}{}{Co to sakra dìláš?}
{202}{}{Metzger dostane tvojí hlavu. Drž se zpátky, èlovìèe.}
{203}{}{Hej, dìvko, vypadni od tìch dveøí.}
{204}{}{Žádná dìvka nevstoupí do Metzgerova pokoje. Odstup.}
{205}{}{Odstup, dìvko. Otrokáø nebo ne, Metzgerùv pokoj je nepøístupný.}

# 2. CF: Generic
{250}{}{Promluv si s Metzgerem, ne se mnou, budulínku.}
{251}{}{Pøicházíš, aby ses pøidal k cechu?}
{252}{}{Èlenství ve spoleèenstvu pøináší pìkný prachy.}
{253}{}{V cechu zažiješ spoustu akcí.}
{254}{}{Promluvte si s Metzgerem, ne se mnou, paní.}
{255}{}{Metzger si nenajme dìvku, to zapomeò.}
{256}{}{Na to zapomeò.}
{257}{}{Hej, èlovìèe.}
{258}{}{Máš štìstí, ty musíš jenom úèastnit se nájezdù.}
{259}{}{Být stráží u dveøí je nudný život.}
{260}{}{Jak je to možné?}
{261}{}{Jsi první ženská, kterou si kdy Metzger najal.}
{262}{}{Metzger musí mít pro tebe slabost.}
{263}{}{Jsi široko daleko jediná malá lady.}
{264}{}{Ženská otrokáøem... Nikdy jsem si nemyslel, že to nìkdy uvidím.}
