#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
# 0. Look
{100}{}{Vidíš pøíjemnì vyhlíející, starší enu.}

{150}{}{Vidíš Mámu, která právì vaøí a uklízí.}
{151}{}{Vidíš robustní starší enu s povzbuzujícím úsmìvem ve tváøi.}

# 1. Low Intelligence (WtG)
{200}{}{Vy tam, dobrı den, jsem Máma. Nikdy pøed tím jsem vás tu nevidìla.}
{201}{}{Ještì jednou vám pøeju dobrı den. Co pro vás mùe Máma udìlat?}
{202}{}{Já .}
{203}{}{Mmmm. Ook? Nashle, nashle, Mámo.}

# 2. Low IQ more (1)
{220}{}{U jsi mì skoro vyjedl. Proè sis nenašel nìjaké jiné místo, kde by ses mohl flákat? U jsi toho tady dneska snìdl dost.}
{221}{}{Dobrá.}
{222}{}{  vánì se umíš podívat, i kdy vypadáš vyplašenì. Nenávidím, kdy nìkdo trpí jako zvíøe. Co takhle nìco k jídlu?}
{223}{}{Mám dost. Mámo, jídlo bylo dobré. Nashle, Mámo.}
{224}{}{Zaplatím?}
{225}{}{Jdu. Nashle, Mámo.}

# 3. Pay? (2)
{240}{}{Tak dobrá. Co máš? (Máma se pøibliuje k tvé penìence)}
{241}{}{Mámo? (podáváš svojí penìenku)}
{242}{}{No! Jdu. Nashle, Mámo.}

# 4. No, not really (7,9)
{250}{}{Ne, ne tak docela. Omlouvám se. Máme krysí koláè, krysí sekanou a špagety.}
{251}{}{Co to dneska bude?}
{252}{}{Není tam nìco, kde by nebylo tolik té krysy??}
{253}{}{Myslím, e si dám krysí sekanou.}
{254}{}{Myslím, e si dám krysí koláè.}

# 5. Not so much rat in it (4)
{270}{}{Doporuèuji vám špagety. V nich není tolik krys -- jenom omáèka, to je všechno.}
{271}{}{Tak dobøe, myslím, e si dám špagety s krysí omáèkou.}

# 6. Here's your food (4,5)
{280}{}{Dám ti dobrou cenu. Bude to $10.}
{281}{}{Teï právì nemám dost penìz. Mùu se místo toho na nìco zeptat.}
{282}{}{$10 za krysu? Vy jste se musela zbláznit. Vdy v okolí vesnice úètují mnohem ménì za ty šavnaté.}
{283}{}{Nu dobrá. Tady jsou peníze.}
{284}{}{Myslím, e nebudu. Rád bych se ale místo toho na nìco optal.}
{285}{}{Myslím, e se pozdìji vrátím. Nashle.}

# 7.  Thanks Mom (6,20)
{300}{}{Máte docela dobrı apetit. Ráda vidím zdravé strávníky. Bude vám to staèit?}
{301}{}{Ani náhodou, Mámo. Chci další.}
{302}{}{Jistì bude. Mùu se tì na nìco zeptat, Mámo.}
{303}{}{To je u všechno. Nashle, Mámo.}

# 8. What's there to do here? (13)
{320}{}{Nutnì potøebuju nìkoho, aby dodal jídlo Smittymu. Je to na vıchod odtud na smetišti. Udìláš to pro mì? Kdy to udìláš dám ti jídlo zadarmo.}
{321}{}{Jistì, ádnı problém.}
{322}{}{Nech mì, a si to rozmyslím. Mezitím se tì zeptám na nìco jiného.}
{323}{}{Uh, promiò, Mámo. Nemùu. Nashle.}

# 9. Random Food item list (13)
{340}{}{Máš štìstí. Máme dušené škorpiony.}
{341}{}{Máme dušeného praso-potkana.}
{342}{}{Dušené škorpiony servírujeme spolu s taenım máslem.}
{343}{}{Zelòaèka je všechno co vám v tuhle chvíli mohu nabídnout.}
{344}{}{Èerstvı smaenı brahmíní kotlet!}
{345}{}{Pipinovo teplej koláè z geckona. }
{346}{}{Flank steak.}
{347}{}{Pìknì vypasenıho krtèího potkana.}
{348}{}{Osmaenıho floatera.}
{349}{}{Filet mignon.}
{350}{}{Medailonky z grilovaného geckona.}
{351}{}{Mantis marsala.}
{352}{}{Krtèí potkan manicotti.}
{353}{}{Brahmína ala brochette.}
{354}{}{Radškorpión ala croute.}
{355}{}{Je to bašta!}
{356}{}{Uh, nejsem si jist, ale chutná to jako kuøe.}
{357}{}{Kotleta z kentaura, moje specialita.}
{358}{}{To je pøekvapení.}
{359}{}{Nemohu prozradit mé tajné recepty!}
{360}{}{Opravdu?}

# 10. Low IQ hand food (3)
{375}{}{Tady jsi. Vypadáš docela hladovì. (Máma ti dává velkı kouøící talíø pikantnì vonícího jídla.)}
{376}{}{Díky, Mámo.}

# 11. Low IQ fed (10)
{385}{}{Tady máš. Vím, e ti to bude chutnat.}
{386}{}{Mmm, òam òam. Nashle, Mámo.}

# 12. Sure I'll deliver it (8)
{395}{}{Díky moc. Udìlala bych to sama, ale nemám tu nikoho, aby mi to tady pohlídal, zatím co jsem pryè. Tady je jídlo pro Smittyho. Kdybych mu ho nepøinesla, jsem si jistá, e by zapomnìl jíst.}
{396}{}{Já mu to odnesu.}

# 13. Hello (WtG, 6,7,8,15,18)
{405}{}{Jsem s tebou tak nespokojená. Chudák Smitty musel pøijít pro svoje vlastní jídlo. Co teï chceš?}
{406}{}{Ahoj ty tam, jmenuju se Máma a vedu tenhle podnik. Mám nejlepší jídlo severnì od New Rena.}
{407}{}{O èem chceš s Mámou mluvit?}
{408}{}{Nejsi má máma.}
{409}{}{U jsi slyšela o Vault nebo o nìkom jménem Vic?}
{410}{}{Co se dá tady ve mìstì podniknout?}
{411}{}{Co si tady dáš?}

# 14. I'm not your mom (13)
{425}{}{Já vím. Ale kadı mi tak øíká. Vdy se starám o lidi, jako by byli moje dìti, pokud dodrují má pravidla.}
{426}{}{Pravidla?}

# 15. Rules? (14)
{435}{}{Tak jest. ádné okrádání, ádné klení a ádné rvaèky -- ne v mém obchodì. Protoe, kdy nìco z toho porušíš, pùjdeš pryè. Mám ráda klid.}
{436}{}{Aha. Mùu se zeptat na nìco jiného.}
{437}{}{To dává smysl. Uvidíme se pozdìji, Mámo.}

# 16. Vic or Vault? (13)
{445}{}{Tak tedy, tamhle je Vault City, vıchodnì a potom trochu severnì odtud. A Vic, hmm, poèkej, nech mì pøemıšlet.}
{446}{}{Doufám, e víš, kde je Vic. Je to obchodník.}
{447}{}{Díky, ale to je všechno, co potøebuji vìdìt. Sbohem, Mámo.}

# 17. Trader Vic (16)
{455}{}{Obchodník Vic? Teï se mi rozsvítilo. Ano, myslím, e ho drí z nìjakého dùvodu Metzger.}
{456}{}{Kdo je Metzger a kde ho mùu najít?}
{457}{}{To je skvìlé, Mámo. Díky.}

# 18. Who's Metzger (17)
{465}{}{Metzger je šéfem místního Cechu otrokáøù. Má pod zámkem všechny druhy lidí. Je to pøímo nad touto ulicí, severnì odtud.}
{466}{}{Metzger bıval šéfem místního Spoleèenství otrokáøù. Mìl pod zámkem všechny druhy lidí. Ale teï nevím - slyšel jsem, e byl zabit.}
{467}{}{Díky za informaci. Dovol, abych se zeptal na nìco jiného, Mámo.}
{468}{}{Potøebuju odejít, abych si ještì nìco zaøídil. Díky, Mámo.}

# 19. Smitty's meal in progress (WtG)
{475}{}{Jen jdi a vezmi to jídlo Smittymu.}
{476}{}{Nepomùu ti, jestli nedodríš slovo.}
{477}{}{Pospìš si.}
{478}{}{Jdi a vezmi Smittymu jeho jídlo. Pospìš.}
{479}{}{Pøestaò se flákat a odnes to jídlo Smittymu.}

# 20. Reward (WtG)
{485}{}{Dobrá práce. Muselo ti vyhládnout.
 Jako odmìnu ti poskutnu veškerou péèi. Kombinovanı talíø toho nejlepšího jídla co tu mám, jen pro tebe.}
{486}{}{To zní skvìle! Sem s tím!}
{487}{}{Jeíši, Mámo. Nemyslím, e teï mùu jíst, ale stejnì dìkuju. Nashle.}

# 21. What do you know about that haunted house? (13)
{500}{}{Hmm, moc o tom nevím. Nìkdo si tam pravdìpodobnì trochu uívá, to je všechno.}
{501}{}{A chodí tam èasto, ten nìkdo?}
{502}{}{Pouívá vùbec nìkdo ten dùm?}
{503}{}{Souhlasím. Nashle.}

# 22. Started 2 years back... (21)
{520}{}{Zaèalo to pøed dvìma lety. Slyšela jsem sténání, vidìla duchy a tak.
 Sama tomu však pøíliš nevìøím.}
{521}{}{Dva roky, jo? A nikdo u tam pak nepøebıval?}
{522}{}{Já taky ne. Díky.}

# 23. Anyone used it then? (21-22)
{540}{}{No, jeden z místních chlapcù tam spával. Je to pár let. Moná on nìco ví.}
{541}{}{Kdo?}
{542}{}{Pravdìpodobnì ne. Sbohem.}

# 24. Who? (23)
{560}{}{Pøicházel a snail se dát vìci do zástavy. Pøevánì šperky. Pamatuju si malı zlatı amulet, kterı si nechal.}
{561}{}{Pamatuješ jsi jeho jméno?}
{562}{}{Amulet? Podivné. Kdo to byl?}
{563}{}{Dovolte... mùu se ještì zeptat?}
{564}{}{Díky, nashle.}

# 25. Name? (24)
{580}{}{Nejsem si jista. Myslím, e to byl Joseph, Joel nebo tak nìjak. Je mu teï asi skoro 19
 .... Ostuda, skuteènì. Vìøím, e je ve spolku nìjakıch místních chuligánù.}
{581}{}{Díky. Mám na vás ještì jednu otázku.}
{582}{}{Díky, nashle.}

# 13b. PC Responce line added to node 13
{600}{}{Co víš o tom strašidelném domì?}
