#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
# 0. Look
{100}{}{Vidíš otrokáøe.}

{150}{}{Vypadá velmi ostražitì.}

# 1. Messed with Door 2nd Time
{200}{}{Dotkni se toho ještì jednou a pøijdeš o ruku.}
{201}{}{Tak jest!}

# 2. CF: Not Slaver
{210}{}{Nic, ale otroci jsou zpátky.}
{211}{}{Otroci nemají návštìvy.}
{212}{}{Jen èlenové mohou projít tìmito dveømi.}
{213}{}{Hledáte otroka? Promluvte si s Metzgerem.}
{214}{}{Promluvte s Metzgerem. Ohrady pro otroky jsou neomezené.}
{215}{}{Co se tu poflakuješ?.}
{216}{}{Kurva. Otroci nemají nárok na návštìvy.}

# 3. CF: Slaver
{230}{}{Jak to jde, budulínku?}
{231}{}{Dneska se to vleèe.}
{232}{}{Doufám, že se ti cech líbí.}
{233}{}{Tvoje tetování vypadá celkem dobøe.}
{234}{}{Pokraèovali jste v tom pøi poslední akci?}
{235}{}{Ahoj.}
{236}{}{Jste mùj typ.}
{237}{}{Ženská otrokáø - mám respekt.}
{238}{}{Èau.}
{239}{}{Vypadá dobøe.}
