#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
#############################################################
#                                                           #
#  Message File: dcPetey.msg                                #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the dialog for a     #
#           new character from which is used by the         #
#           design tool. It will be updated using the       #
#           the tool. This is just a tool file, and not     #
#           meant to be used in the game.                   #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#                                                           #
#  Created: January 12, 1998                                #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the item when     #
#  glanced and examined.                                    #
#############################################################

{100}{}{Vidíš drogovì závislého.}
{101}{}{Vidíš Peteye.}

{150}{}{Je to chudı feák.}
{151}{}{Petey tady vypadá jako by mu bylo pomoci.}
{152}{}{[hovoøí]}
{155}{}{(zakašlání, zakašlání) Nìjaké drobné navíc pro Peteye?}
{156}{}{Jistì, tady jsou.}
{157}{}{Ne, vypadni ode mì.}
{158}{}{Peewee?}
{159}{}{Jsi na tom hùø ne já (zakašlání) Kadopádnì díky.}
{160}{}{Promiò, sbohem.}
{161}{}{Duh, není zaè, uh-huh, jé.}
{162}{}{Moná pøíštì. Kadopádnì díky [zakašlání}
{163}{}{[hotovo]}
{164}{}{Diky moc. [zakašlání] mo, moc.}
{165}{}{Nemáš zaè.}
{166}{}{Yeah, yeah.}
{167}{}{Pane, (zakašlání) mùete pomoct uboákovi, kterı je na dnì?}
{168}{}{Tady máte $5.}
{169}{}{ Dneska ne.}
{170}{}{Jdi makat.}
{171}{}{Paní, buïte tak laskavá a pomozte prosím (zakašlání) hladovìjícímu chudákovi, kterı je tak nemocnı, e nemùe pracovat.}
{172}{}{Ty chudinko, tu máš $5.}
{173}{}{ebrákùm ze zásady peníze nedávám.}
{174}{}{Ne.}

{200}{}{Haló, pane, dáte mi nìjaké peníze?}
{201}{}{Staèí nìjaké drobné, dobrı pane.}
{202}{}{Haló, mùete mi vypomoct pár doláèi?}
{203}{}{Myslíte, e byste mi mohl pomoci nìkolika dolary?}
{204}{}{Co myslíte mohl byste mi pùjèit nìco málo dolláèù?}
{205}{}{Nìjakı drobnı, dobrá paní?}
{206}{}{Haló, paní, nìjaké peníze?}

{220}{}{Prosím pomozte mi, pane.}
{221}{}{Ahhh, to bolí.}
{222}{}{Potøebuju pomoc. Strašnì to bolí.}
{223}{}{Lady, mùete mi nìjak pomoct?}

{225}{}{Strašnì si toho váím.}
{226}{}{Haló, co to dìláte?}

{230}{}{Cítí se tak dobøe.}
{231}{}{Uhhh...}
{232}{}{(giggle)}
{233}{}{Hej...}

#dealer dead messages
#tubby dead
{300}{}{Ahhh, zavradil nìjakej zasran Tubbyho?}
{301}{}{Co se kurva stalo Tubbymu?}
{302}{}{Oh sakru, Tubby je...}
#generic
{303}{}{Ahhh...}
{304}{}{Kadopádnì jsem ten prdelní otvor nemìl rád.}
#flick dead
{305}{}{Flick je mrtvej? Hrùza.}
{306}{}{Co se stalo Flickovi?}
{307}{}{Flick...}

#dealer far, ask for assistance
#ask tubby
{310}{}{Hej Tubby, já, ehh, potøebuju pomoc.}
{311}{}{HEJ TUBBY!}
#ask any
{312}{}{Dobrı den.}
{313}{}{HEJ!}
#ask flick
{314}{}{Hej Flicku, já, ehh, potøebuju pomoc.}
{315}{}{HEJ FLICKU!}

#ask dealer for drug messages
#from tubby
{320}{}{Hej Tubby, mùeš mì z toho dostat? Mám prachy.}
{321}{}{Ummm, Tubby, mám nìjakı peníze.}
#from any
{322}{}{Uhhh...}
{323}{}{Potøebuju ivotabudiè.}
#from flick
{324}{}{Hey, Flicku; mùeš mì z toho dostat? Mám prachy.}
{325}{}{Ummm, Flicku, mám nìjakı peníze.}

#thank dealer for drugs messages
#thank tubby
{330}{}{Uhhh... Tubby, dík ještì jednou.}
{331}{}{Jsi kámoš, Tubby.}
#thank generic
{332}{}{Pøísahám. Zejtra bych asi natáh baèkory.}
{333}{}{Seš kámoš.}
#thank flick
{334}{}{Uhhh... Ještì jednou díky, Flicku.}
{335}{}{Jsi kámoš, Flicku.}
