#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
# 0. Look
{100}{}{Vidíš velmi atraktivní mladou dámu.}
{101}{}{Vidíš Rebeccu.}

{150}{}{Vidíš Rebeccu, majitelku Beckyina Casino Baru.}

# 1. Greetings (From WTG)
{200}{}{Vítejte, já jsem Rebecca. Mohu vám nìco nalít? Jistì máte po takovém vıletì pustinou ízeò.}
{201}{}{Hej! Chcete drink, nebo jste myslí nìkde jinde?}
{202}{}{Ahoj! Jsem ráda, e jste zpátky. Máte nìjaké otázky, nebo jste pøišel na sklenku vynikající whiskey?}
{203}{}{Opravdu jsem rád, e vás vidím. Jak to jde? Potøebujete nìco?}
{204}{}{Doufám, e moji oblíbení hosté jsou spokojeni! Co pro vás dnes mùeme udìlat?}
{205}{}{Dobrı den!}
{206}{}{Pokadé jsem rád, e vás opìt vidím.}
{207}{}{Ahoj! Dáte si drink? Nejlepší whiskey v zemi!}
{208}{}{Vítejte!}
{209}{}{To jste vy! No, ano. Co takhle panáka, cukrouši?}
{210}{}{Vrátil jste se kvùli Rebeèinì talentu bavit hosty nebo kvùli svìtoznámé whiskey?}
{211}{}{Vítejte zpìt v Rebeèinì Baru a Casinu. Jak vám mohu pomoci?}
{212}{}{Dobrej, jak vám mùeme pomoci?}
{213}{}{Dáte si dneska nìco? Co takhle drink?}
{214}{}{Máte chu na drink nebo nìco jiného?}
{215}{}{Èím poslouím?}
{216}{}{Zdravím. Mùeme pro vás nìco udìlat?}
{217}{}{Potøebujete nìco?}
{218}{}{Fajn, e vás zase vidím. Jak vám dnes mùu pomoct?}
{219}{}{Co?}
{220}{}{Ano?}
{221}{}{Tak co?}
{222}{}{Prosím struènì. Dneska mám nároènı den. Co potøebujete?}
{223}{}{Co pro vás mohu udìlat? Mám opravdu hodnì práce.}
{224}{}{Pøišel jste na drink? Stoly jsou támhle.}
{225}{}{Vánì nemám náladu. Co tedy?}
{226}{}{U jste zpátky? Hádám, e si pøeci jen dáte drink?}

# 2. Prelude to questions (From ?)
{240}{}{Jistì, díky.}
{241}{}{Co byste rád vìdìl?}
{242}{}{Byl bych šastnı.}
{243}{}{Ale samozøejmì.}
{244}{}{Jistì.}
{245}{}{Nevadí mi to.}
{246}{}{Pomohu, pokud budu moct.}
{247}{}{Samozøejmì, nevymıšlej hlouposti.}
{248}{}{Cokoliv. O co se jedná?}
{249}{}{Udìlám všechno pro to, abych vám pomohla. Co potøebujete vìdìt?}
{250}{}{Ptejte se.}
{251}{}{Kdy na tom trváte.}
{252}{}{Ano trvám.}
{253}{}{Zkrate to. Mám ještì nìco na práci.}
{254}{}{Tak dobøe. Co to je?}
{255}{}{Domnívám se.}
{256}{}{Co?}
{257}{}{Ne, promiòte.}
{258}{}{Ne teï ne.}

# 3. Questions (From 1-2)
{270}{}{Potøebuju drink.}
{271}{}{Hledám obchodníka, kterı prodává Vault vybavení.}
{272}{}{Hledám obchodníka jménem Vic.}
{273}{}{Máte nìjakou práci?}
{274}{}{Co se tıèe té prácièky...}
{275}{}{Máte pro mì nìjakou další práci?}
{276}{}{Ne nic. Nashle.}
{277}{}{Wekee.}
{278}{}{Ruh ruh?}
{279}{}{Iho shasha.}
{280}{}{dy.}
{281}{}{Ruh ruh?}

# 4. Whiskey (From 3)
{300}{}{Whiskey je moje specialita. V rodinì Dyerù je to témìø tradice. Úètuju velmi nízkou cenu -- jenom $5.}
{301}{}{Pití stojí stále $5 a Dyerova rodina dìlá nejlepší pití na celém svìtì.}
{302}{}{Jste Oukej? Chcete whiskey? Jen 5 doláèù.}
{303}{}{Dám si drink.}
{304}{}{Proè je vaše pití tak levné?}
{305}{}{Dyer?}
{306}{}{Mùu se na nìco zeptat?}
{307}{}{Nashle.}
{308}{}{Wekee}
{309}{}{Urka.}

# 5. Dyer (From 4)
{320}{}{Oh, to je rodinné jméno. Jméno Dyer je v barovém businessu u léta -- ještì v pøedváleèné dobì, samozøejmì.}
{321}{}{Jak jsem øekla, je to mé rodné pøíjmení. Po celém svìtì jste mohl najít Dyerovy hospody, saloony atd.}
{322}{}{Dám si drink.}
{323}{}{Mùu se ještì na nìco zeptat?}
{324}{}{Nashle.}

# 6. Why drinks are so cheap (From 5)
{330}{}{Dobøe, protoe jste tak dobrı zákazník, svìøím vám toto malé tajemství.
 Je to opravdu jednoduché. Mám destilaèní pøístroj a pøítel ze sousední vesnice mì nauèil, jak whiskey pálit. Tak, dáte si ještì jednu?}
{331}{}{Promiòte je to obchodní tajemství a navíc vás zas tak dobøe neznám. Nechtìla bych Frankieho prozradit. Má u beztak dost problémù. Chtìl jste ještì jednu? Opravdu se trefili do èerného.}
{332}{}{Jistì, dám si jednu.}
{333}{}{Mùu se ještì na nìco zeptat?}
{334}{}{Ok, díky.}

# 7. Drinking (From 4-6)
{340}{}{Tady je. Díky moc.}
{341}{}{Dík. Mùu se zeptat?}
{342}{}{Ok, díky.}
{343}{}{Dìkuji aaach....}
{344}{}{Nopey nopey.}

# 8. (From )
{350}{}{Promiòte, ale nesouhlasím.}
{351}{}{Fred mi dluí $200. Jestlie to nìjak seenete, uvidíme co se dá dìlat.}
{352}{}{Stále mám tenhle dluh, kterı potøebuju splatit.}
{353}{}{Derek si nedávno pùjèil jednu mojí kníku. Zaplatím 80 babek, kdy mi ji vrátíte.}
{354}{}{Stále hledám tu mojí kníku.}
{355}{}{V èem je háèek?}
{356}{}{Øeknìte mi víc.}
{357}{}{Mohu se na nìco zeptat?}
{358}{}{Nashle.}

# 9. Job 1 & 2 Introductions (From 8)
{370}{}{Háèek? Oh, Neznáte Freda, proto nechápete. Dluí mi peníze u pìknì dlouho. Odepsala jsem to jako ztrátu, ale pokud to z nìho dostanete, budu pøekvapená... a vdìèná. Jsem si jista, e je nìkde ve mìstì.}
{371}{}{Ta kniha se jmenovala "Levandule". Derek by se mìl vyskytovat nìkde u Mámy ve vıchodní èásti.}
{372}{}{Uvidím co se dá dìlat.}
{373}{}{Jistì zní to jednoduše.}
{374}{}{Tohle u mám vyøešeno.}
{375}{}{Musím se k vám vrátit.}

# 10. (From 3, )
{385}{}{Podaøilo se to z nìj vymámit? Divila bych se, kdyby ano.}
{386}{}{Páni, podaøilo se vám najít moji knihu?! Proè jsem to Derekovi jenom dávala do rukou.}
{387}{}{Ano, podaøilo.}
{388}{}{Je mi líto. Je mrtvı.}
{389}{}{Sorry, ale je také mrtvı.}
{390}{}{Je mi líto, ale je mrtvı.}
{391}{}{Ano. Tady to je.}
{392}{}{Ne, promiòte.}

# 11. Finished Job 1 or 2 (From 10)
{400}{}{Nemohu tomu uvìøit. Jak jste to udìlal? Ale nevadí. Jsem jen ohromena, to je všechno. Abych ukázala, jak jsem vám vdìèná, rozdìlím se s vámi fifty fifty. Ještì jednou dìkuji, bylo to od vás velmi šlechetné.}
{401}{}{Oh, jsem tak ráda, e se našla... Zde jsou vaše peníze. Dìkuji mnohokrát.}
{402}{}{Není zaè.}

# 12. Deaths (From 10)
{410}{}{Nemohu uvìøit tomu, e jsou oba mrtví. Promiòte. Dìkuji vám, e jste to pro mì vyhledal. Omluvte mì...}
{411}{}{Nevìøím, e je mrtvı... po tìch všech letech.}
{412}{}{Jistì.}

# 13. Vic (From 3)
{420}{}{Jé, já vím, kdo to je. Je to Vic -- chlápek, kterého Metzger uvìznil.}
{421}{}{Ano, já znám Vica. Metzger ho strèil pod zámek. Nejsem si jistá proè vlastnì.}
{422}{}{Kdo je Metzger?}
{423}{}{Mám další otázku.}
{424}{}{Vıbornì! Nashle.}

# 14. Who's Metzger (From 13)
{430}{}{Pøicházíte do Denu a nevíte, kdo je to Metzger? Je to známı otrokáø. Sídlí ve vıchodní èásti mìsta. Nemùete to minout.}
{431}{}{Mám další dotaz.}
{432}{}{Díky.}

# 15. CF: Hostile & Childkiller (From WTG)
{440}{}{Vrahu!}
{441}{}{Vrahu dìtí!}
{442}{}{Odejdìte prosím.}
{443}{}{Nebudu s vámi jednat v rukavièkách.}
{444}{}{Nedostanete mì bez boje!}

# 16. Buffy 1 (From WTG)
{450}{}{Buffy! Jsi to ty? Jak se ti vede? Je to u dlouhá doba!}
{451}{}{Huh?}
{452}{}{Huh?}

# 17. Buffy 2 (From 16)
{460}{}{Dave vás pozdravuje. Pøál by si pozdravit se s vámi, ale musel nìkam odbìhnout.}
{461}{}{Kam?}

# 18. Buffy 3 (From 17)
{470}{}{Nìco kvùli komandu... nebo, moná šel za komandem. Nevím. Kvùli nìèemu takovému.}
{471}{}{Oh.}

# 19. Buffy 4 (From 18)
{480}{}{Oh, øekl, e vám mám tohle dát. Je to dar od rodu Hendee. To by se vám mohlo k nìèemu hodit.}
{481}{}{Co to je?}

# 20. Buffy 5 (From 19)
{490}{}{Oh, jen nìkolik cetek. Tady máte. (Becky ti odkazuje $1000, 5 stimpakù,
 kovovou zbroj, Uzi, 5 zásobníkù støeliva, plazmovı granát a kvìtinu)}
{491}{}{Díky!}

# 21. Buffy 6 (From 20)
{500}{}{To nic. Jen jsem to pro vás opatroval. Tak, radìji abych se vrátil do práce.}
{501}{}{Díky, nashle.}

# 22. Metzger's Dead! (From WTG)
{510}{}{Copak jsi neslyšel! Je mrtvı! Oh, vím, e bych nemìl bıt rád, ale on byl velmi zlı èlovìk.}
{511}{}{Pøedvedl jistì velmi dobrı zápas.}
{512}{}{Mám dotaz.}
{513}{}{Ano, pøedvedl. Nashledanou.}
{514}{}{ Zabít!}

# 23. Metzger's dead 2 (From 22)
{520}{}{Co? Ty? Já... nevím co øíct. Byl to takovı krutı èlovìk...}
{521}{}{Podìkování by staèilo.}
{522}{}{Humph.}

# 24. Metzger Reward (From 23)
{530}{}{Oh, dík by staèil. Vím, e to není to pravé, ale... tady, vemte si ty peníze. (Becky ti dává 1000 dolarù)}
{531}{}{Nechte si ty peníze, Rebecco.}
{532}{}{Mockrát dìkuji.}
{533}{}{Díky!}
{534}{}{Ug! Perdy lady.}

# 25. Metzger's Dead No reward, Gain Karma (From 24)
{540}{}{Jste úasnı mu. I kdy vám nemohu prominout vaše èiny, dìláte svìtu velkou slubu.}
{541}{}{Jste úasná ena. I kdy vám nemohu prominout vaše èiny, dìláte svìtu velkou slubu.}
{542}{}{Díky.}

# 26. Still destroyed, after talk (From WTG)
{550}{}{Nejste tu vítán. Prosím, odejdìte.}
{551}{}{Odejdìte prosím.}

# 27. Still destroyed (From WTG)
{560}{}{Proè jste znièil mùj destilaèní pøístroj? Co jsem vám kdy udìlala?}
{561}{}{Dostal jsem zaplaceno, abych to udìlal.}
{562}{}{Nemusím se nikomu zpovídat.}
{563}{}{Nevím, o èem to mluvíte.}
{564}{}{O èemkoliv.}
{565}{}{Ooba gooba.}

# 28. Still 2 (From 27)
{570}{}{Opravdu? To ten špinavec Frankie vás do toho navezl, jsem si tím jistá. Ale já si udìlám novı, víte?}
{571}{}{Nevadí. Dostal jsem zaplaceno.}
{572}{}{Tak.}
{573}{}{Nepøekvapilo by mì to.}

# 29. Still 3(From 28)
{580}{}{Tak, vy jste také zbabìlec?.}
{581}{}{...}
