#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
#0. Look
{100}{}{Vidíš strá.}
{101}{}{Vidíš strá z Beckyina Casino Baru.}
{150}{}{Vypadá jako by v davu vyhlíel zlodìje.}
{151}{}{Ona jako by pozornì sledovala kadého v místnosti.}

#1. Hostile
{200}{}{Teï to dostaneš.}
{201}{}{Teï se nedostaneš ven.}

#2. CF: Generic
{210}{}{Sorry, Becky nás nepøijme, protoe se vìnuje zákazníkùm.}
{211}{}{Doufám, e se bavíte.}
{212}{}{Ujišuji vás, e máme nulovou toleranci pro okrádání.}
{213}{}{Za tìmito zdmi jste v bezpeèí.}
{214}{}{Rebecca má ty nejlepší drinky.}
{215}{}{Rebecca je ten nejlepší šéf, jakého jsem kdy mìl.}
{216}{}{Cítíte, e máte dnes štìstí? Blackjack je moje hra.}
{217}{}{Becky je právì támhle, jestli nìco potøebujete.}
{218}{}{Rebeèiny karty jsou poctivé, tak zkuste své štìstí.}

#3. Self: Caught Stealing
{230}{}{Tohle tu netolerujeme.}
