#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
#0. Look
{100}{}{Vidíš stráž.}
{101}{}{Vidíš stráž z Beckyina Casino Baru.}
{150}{}{Zdá se, že peèlivì pozoruje tyto dveøe.}

#1. CF: Hostile
{200}{}{Tak snadno se odtud nedostaneš.}

#2. CF: Generic
{210}{}{Ty vedou do Rebeèina pokoje. Nikdo tam nesmí.}
{211}{}{Doufám, že se bavíte.}
{212}{}{Hledáte Becky? Je právì támhle.}
{213}{}{Ahoj.}
{214}{}{Užijte si stolní hry.}
{215}{}{Becky má ty nejlevnìjší drinky ve mìstì.}

#3. Self Initiated: Door tampered with
{230}{}{Okamžitì vypadni od tìch dveøí.}
{231}{}{Už se jich pøíštì nedotýkej.}
{232}{}{Drž se od nich dál!}
{233}{}{Nech je na pokoji.}
{234}{}{Co si myslíš, že dìláš?}

#4. Self Initiated: Door opened
{240}{}{Zlodìj!}

#5. Self Initiated: Caught Stealing.
{250}{}{To u nás netolerujeme.}

# left post message
{300}{}{Máš nìco po práci, bejby?}
{301}{}{Jako obvykle vypadáš skvìle.}
{302}{}{Bejby, ty opravdu víš, jak provozovat stolní hry.}
{303}{}{Hej miláèku, mùžeš hodit ty kostky ještì jednou? Zbožòuju zpùsob, jakým se pohybuješ.}
{304}{}{No. Jak to vypadá, zlato?}
{305}{}{Tak... ty a já... po práci?}
{306}{}{Becky by mi mohla dát zítra volno, pokud jsi ... k mání.}
{307}{}{Už jsem ti nìkdy øekl, že máš krásné oèi?}

# leaving message
{350}{}{Ty mì máš zase na salámu. Tuto hru mùžou hrát jen dva.}
{351}{}{Co? Poøád na mì kašleš?}
{352}{}{Odvádíš, uf, dobrou práci... pokraèuj v ní...}
{353}{}{Co? Zase mì ignoruješ?}
{354}{}{Jsi zaneprázdnìn... rozumím. Pokecáme pozdìji.}
{355}{}{Èlovìèe, ty urèitì víš, jak tìžké je takovou hru hrát.}
{356}{}{Tak si... uf, promluvíme pozdìji.}
{357}{}{Taky s tebou rád hovoøím... potom se k tomu vrátím.}

# door open
{375}{}{A, do prdele...}
