#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
# examines
{100}{}{Vidíš nepoddajného otroka ve støedních letech.}
{101}{}{Vidíš otroka s velkou jizvou ve tváøi.}
{102}{}{Vidíš poøádnì robustního otroka.}

{150}{}{Jedná se o otroka, který vypadá, že ho jeho práce baví.}
{151}{}{Tento otrok se zdá být velmi silný, ale ne chytrý.}
{152}{}{Tento otrok je poøádnì udìlaný, jako ostatní.}

# 1. CF: Hostile Not Done - no kills
{225}{}{Jdem na nì.}
{226}{}{Zabít jen ty vzpurný.}
{227}{}{Držte tempo, jsme hned za vámi.}
{228}{}{Vyøiïte jen ty vzpurný, ostatní jsou naše koøist.}
{229}{}{Jsem pøipraven rozmlátit nìjaký hlavy.}
{230}{}{Kde jsou? Vidíš je?}

# 2. CF: Hostile Not Done - have kills
{235}{}{Už není èas na ústup.}
{236}{}{Dostaòte poslední z tìch vzpurných.}
{237}{}{Nechejte být ty bezbranný. Dostaòte ty ostatní.}
{238}{}{Èeká nás ještì víc krveprolití.}

# 3. CF: Done with run - Poor
{245}{}{To je pøíšerná akce.}
{246}{}{Jen ztìží se to vyplatilo.. Dostali jsme akorát tak velký hovno.}
{247}{}{Pøíštì odstranit jen ty vzpurný. Není to žádná sranda ani hra.}
{248}{}{Metzger se asi pochèije.}

# 4. CF: Done with run - Average
{255}{}{Celkem dobrý -- ale pøíštì nechejte na pokoji ty bezbranný, jestli chcete, aby se nám to vyplatilo.}
{256}{}{To nebylo tím. Ušetøili jsme nìkolik slušných otrokù.}
{257}{}{Myslím, že na tom nakonec vydìláme.}

# 5. CF: Done with run - Good
{265}{}{Hej, zadaøilo se nám docela dobøe. Témìø jsme je dostali všechny.}
{266}{}{Díky za vaší pomoc.}
{267}{}{Dobrá práce. Výdìlek za tuto akci by mìl být dost dobrý.}
{268}{}{Byla to zábava a ještì bychom mìli z toho nìco vytøískat.}

# 6. CF: Done with run - Perfect
{275}{}{Zatracenì dobøe se nám zadaøilo. Metzger nám urèitì zvýší podíl.}
{276}{}{Bylo to skvìlý! Dneska si poøádnì ožeru držku.}
{277}{}{Kurva, to jsme jim ale nakopali prdel.}
{278}{}{Tak se to má dìlat.}

# 7. BF: Hostile Not Done - no kills
{285}{}{Kde jsou?}
{286}{}{Já asi dostanu mladý.}
{287}{}{Vsadím se, že jich zabiju mnohem víc než ty.}
{288}{}{Nech toho, sám víš moc dobøe, že to jsou jen kecy.}

# 8. BF: Hostile Not Done - have kills
{295}{}{Zbytek vašich je po smrti, vy to ale ještì nevíte.}
{296}{}{Pøed námi se neschováte!}
{297}{}{Vylezte, nebo vám provìtrám ty vaše zasraný hlavy.}
{298}{}{Jo, to bylo dobrý! Kde je zbytek vašich?}

# 9. BF: Done with run - Poor
{305}{}{Do prdele.}
{306}{}{To smrdí.}
{307}{}{Zatracenì.}
{308}{}{Radìji to nebudeme dìlat znovu.}
{309}{}{Sakra... a já jsem se dneska veèer chystal ožrat si držku.}
{310}{}{Vypadneme odtud. Zkurvenì jsem naletìli.}

# 10. BF: Done with run - Average
{320}{}{Docela dobrý.}
{321}{}{Doufejme, že jsme jich dostali dost, potøebuju znovu naplnit moje tryskový zásobníky.}
{322}{}{Padáme.}
{323}{}{Vidím to jinak, ale prachy jsou prachy.}
{324}{}{Metzger by mìl z nich mít radost.}

# 11. BF: Done with run - Good
{325}{}{Velmi dobøe.}
{326}{}{Hejbnìte zadkem. Praštíme do toho.}
{327}{}{To by mìlo být v pohodì.}
{328}{}{Skvìlý tah.}
{329}{}{Padáme. Chci svoje prachy.}

# 12. BF: Done with run - Perfect
{335}{}{Skvìlý èas!}
{336}{}{Paráda.}
{337}{}{Sežeòte je dohromady a vyrazíme.}
{338}{}{Pøestaòte se flákat. Padáme.}
{339}{}{Sakra, tahle akce se fakt povedla.}
