#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
# looks
# primitive
{100}{}{Vidíš velkého muže s vizáží primitiva.}
{101}{}{Vidíš štíhlou primitivní ženu.}

# nomads
{200}{}{Vidíš podivnì vyhlížejícího muže.}
{201}{}{Vidíš drsnì vypadajícího muže.}
{202}{}{Vidíš muže v rozedraných šatech.}

{210}{}{Vidíš velmi odpudivou ženu.}
{211}{}{Vidíš pìknì špinavou ženu.}
{212}{}{Vidíš šlachovitou ženu.}

# 10. BF: Fleeing Primitive
{270}{}{Oni mì nenajít.}
{271}{}{Muset schovat. Muset schovat.}
{272}{}{Proè oni chtít zranit?}
{273}{}{Já bát se.}
{274}{}{Já nebojovat.}
{275}{}{Já chtít žít.}
{276}{}{Nezranit rodinu.}

# 11. BF: Fleeing Nomad
{280}{}{Do prdele!}
{281}{}{Proè to dìlají?}
{282}{}{A co moje rodina?}
{283}{}{Nechci umøít.}
{284}{}{Nechci být otrok.}
{285}{}{Zasloužím se nìco lepšího, než je tohle.}

# 14. Fleeing Primitive
{300}{}{Ahhh!}
{301}{}{Nezabít! Nezabít!}
{302}{}{Stop!}
{303}{}{Pomóóóóc!}
{304}{}{Bìž!}
{305}{}{Nechat na pokoji!}
{306}{}{Nezranit!}
{307}{}{Nezranit tebe!}
{308}{}{Já nebojovat!}

# 15. Fleeing Nomad
{350}{}{Utíkej jako o život!}
{351}{}{Nenechej se od nich chytit!}
{352}{}{Otroci! Bìžte pro to!}
{353}{}{Pomozte nìkdo! Prosím!}
{354}{}{Bìž pro to, Marty!}
{355}{}{Ahhh!}
{356}{}{Zastavte to šílenctví!}
{357}{}{Pøece jsme nic neudìlali! Nechte nás na pokoji!}
{358}{}{Poznávám to tetování!}
{359}{}{Ne, prosím!}
{360}{}{Prosím nezabíjejte mì!}
{361}{}{Nebudu bojovat, nezabíjejte mì!}
{362}{}{Prosím já nechci zemøít!}
{363}{}{Jsi otrok, že jo? O Bože.}
