#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš prostitutku.}

{150}{}{Je to tvoje obvyklá prostitutka.}

{152}{}{[MLUVIT]}
{153}{}{Hej, já se s nikım nevykecávám!}
{154}{}{Cokoliv.}
{155}{}{Promiò.}
{156}{}{Mami?}
{157}{}{Hej, chlapeèku bude to draší, jestli se se mnou budeš vykecávat.}
{158}{}{Hej, oni jdou se mnou.}
{159}{}{Chci je mít s sebou.}
{160}{}{Vrátím se.}
{161}{}{Mami?}
{162}{}{Ale fešáku, kde jsi byl celou tu dobu?}
{163}{}{Zrovna tady, bejby.}
{164}{}{Kolik, sestro?}
{165}{}{Ach jo, musím jít. Sbohem.}
{166}{}{Jehee!}
{167}{}{Mám je rád velkı.}
{168}{}{To jsem já!}
{169}{}{Joo!}
{170}{}{Ale. Ne. Sbohem.}
{171}{}{Jakej je z tebe velkej chlap!}
{172}{}{Tak jak to máš rád.}
{173}{}{Ano, madam.}
{174}{}{Musím jít.}
{176}{}{Oukej!}
{177}{}{Ne. Sbohem.}
{178}{}{Ty se vrátíš.}
{179}{}{Uvidíme.}
{180}{}{Ne.}
{181}{}{[slintat]}
{182}{}{Máš málo. Ztra se, zlato.}
{183}{}{Vrátím se.}
{184}{}{Nemáš takovou cenu, zlato.}
{185}{}{Ehh!}
{186}{}{Byl si ohromnej!}
{187}{}{Vdycky, zlato.}
{188}{}{Cokoliv.}
{189}{}{Ty u jsi byl.}
{190}{}{Jsem jedlá!}
{191}{}{Byl jsi ohromnej!}
{192}{}{Díky. Ty taky.}
{193}{}{Hmm.}
{194}{}{Jooo.}
{195}{}{Super!}
{196}{}{OK, jsme hotovı. Sbohem.}
{197}{}{To je ono?}
{198}{}{Oukej. Sbohem.}
{199}{}{Bylo to dobrı.}
{200}{}{Na shledanou.}
{201}{}{Bylo to k nezaplacení.}
{202}{}{V kadém pøípadì to nebylo takovı, jako kdyby si za to chtìla peníze.}
{203}{}{Budu ti chybìt.}
{204}{}{Sbohem.}
{205}{}{Mám odejít?}
{206}{}{Vra se kdykoliv.}
{207}{}{Oukej. Sbohem.}
{208}{}{Joo, dobøe.}
{209}{}{Jehee!}
{210}{}{Nazdar.}
{211}{}{Sbohem.}
{212}{}{Na shledanou.}
# It will cost $(amount) for a session. Pay first.
{213}{}{Stojí to $}
{214}{}{ za èíslo. Nejdøív zapla.}
{215}{}{Pojï za mnou.}
{216}{}{Èekám tady.}
{217}{}{Nehodlám v téhle studené díøe stát celı den.}
{218}{}{Mohl by sis pospíšit?}
{219}{}{Poslední šance.}
{220}{}{Fajn. Nebudu èekat ani o chvilku déle.}
{221}{}{Pojï, pojï.}
{222}{}{Seš nìjakej vyplašenej èi co?}
{223}{}{Pojï za mnou.}
{224}{}{Hej, kámo, dej ty pracky dál.}
{225}{}{Ruce pryè! Nejsem ádná hraèka se kterou si mùeš hrát.}

{230}{}{Ehmm...? To bylo poprvé?}
