#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
# 0. Look Primitive
{100}{}{Vidíš velkého, primitivnì vyhlíejícího mue.}
{125}{}{Má šrámy a modøiny po celém tìle.}

{150}{}{Vidíš slabou, primitivní enu.}
{175}{}{Vypadá jako by ji nìkdo zmlátil.}

# 1. Look Nomad
{200}{}{Vidíš otrhaného mue.}
{225}{}{Nevypadá pøíliš zdravì.}

{250}{}{Vidíš zajatou enu.}
{275}{}{Je špinavá a vypadá podvyivenì.}

# 2. CF: Freed
{300}{}{Neubliuj mi, prosím!}
{301}{}{U jdeme?}
{302}{}{ádnı øeèi. Musíš bìet.}
{303}{}{Díky za pomoc.}
{304}{}{Dìkuji mnohokrát!}
{305}{}{Jsi svatej.}
{306}{}{Co dìláš? Mìli bysme jít.}
{307}{}{Pomoz nám utéct.}

# 3. CF: PC is Slaver
{320}{}{Ty bestie!}
{321}{}{Nemluvíme s tebou.}
{322}{}{Uteèeme.}
{323}{}{Nezadríš nás.}
{324}{}{Ty otrokáøi!}
{325}{}{Proè to vy otrokáøi dìláte?}
{326}{}{Jak mùete dìlat pro tyhle lidi?}
{327}{}{Nejsme primitivové!}
{328}{}{Nemáte ádnou morálku?}
{329}{}{Co s námi bude?}
{330}{}{Co jsme udìlali špatnì?}
{331}{}{Nech nás o samotì, otrokáøi!}
{332}{}{Neubliuj mi!}
{333}{}{Vypadni ode mì!}

# 4. CF: PC is Not Slaver
{350}{}{Kdo jsi?}
{351}{}{Ty nejsi otrokáø.}
{352}{}{Nic nám neudìláš?}
{353}{}{Kamarád?}
{354}{}{Ty pomáháš?}
{355}{}{Co s námi bude?}
{356}{}{Taky tì chytli?}
{357}{}{Nejsme primitivové!}
{358}{}{Co si o sobì tihle lidi myslí?}
{359}{}{Pomoz nám prosím!}
{360}{}{Dostaòte mne odsud.}

# 5. BGF: Not Free
{380}{}{Neudríš nás tady!}
{381}{}{Nemáš pravdu!}
{382}{}{Nejsme špatní!}
{383}{}{Pomáháme?}
{384}{}{Pus nás!}
{385}{}{Ne.}
{386}{}{Špatnı místo.}
{387}{}{Proè tohle zlí lidi dìlaj?}
{388}{}{Nejsme otroci!}
{389}{}{Nedìláme nic špatnıho.}
{390}{}{Jdeme!}
{391}{}{Co se dìje?}
{392}{}{Co je to za hluk?}
{393}{}{Kdo bojuje?}
{394}{}{Co se dìje?}
{395}{}{Nìco se stalo?}
{396}{}{Pomozte nám nìkdo!}
{397}{}{Hej! Slyší mì nìkdo?}
{398}{}{To je zlı!}
{399}{}{Nic jsme neudìlali!}
{400}{}{Dostaò nás odsud!}
{401}{}{Dostaòte nás nìkdo odsud!}
{402}{}{Co jsme udìlali?}
{403}{}{Neudìlali jsme nic.}
{404}{}{Tohle jsme si nezaslouili.}
{405}{}{Ty bastardi!}
{406}{}{Pomozte nám!}
{407}{}{Dejte mi pokoj!}
{408}{}{Nejsme otroci!}
{409}{}{Nejsme primitivové! Dostaò nás odsud!}
{410}{}{Co se dìje?}
{411}{}{Je tady nìkdo kdo nás zachrání?}
{412}{}{Tamhle!}
{413}{}{Pomoc! Neopouštìj nás!}
{414}{}{Co to bylo za støelbu?}
{415}{}{Co se dìje?}

# 7. BGF: Fleeing
{420}{}{Ahhh!}
{421}{}{Ug!}
{422}{}{Nezastavuj!}
{423}{}{Jasnì!}
{424}{}{Utíkám z tohohle místa tak rychle jak mùu.}
{425}{}{Vydr!}
{426}{}{Svoboda! Koneènì volní!}

# 8. Metzger is Dead (From Where to go)
{440}{}{Nìjaká hlasitá støelba? Co chceš?}
{441}{}{Hey! Co to bylo za støelbu? Jsou otrokáøi mrtví?}
{442}{}{Hey! Co to bylo za støelbu? Co se dìje?}
{443}{}{To byla Metzgerova èepice na spaní.}
{444}{}{Ale, nic. Jenom vás kontroluju. Sbohem.}
{445}{}{Jste volní, mùete jít. Metzger je mrtev.}
{446}{}{Jste volní.}
{447}{}{ kamarád. Zabil Metzgera. Teï jdìte.}
{448}{}{ kamarádka. Zabila Metzgera. Teï jdìte.}

# 9. Metzger is Dead (From 8)
{460}{}{Je mrtvı? Dìkuji ti! Jdeme rychle. Sbohem. Kamaráde.}
{461}{}{Coe? Metzger je mrtvej? Oh, mockrát dìkujem! Mìli bychom radìji zmizet ne se objeví ostatní. Ještì jednou dìkujeme.}
{462}{}{Není zaè. Teï u odtud radìji zmizte.}
{463}{}{Starej se.}
{464}{}{Není zaè.}

# 10. Metzger Dead, Next Times (From Where to go)
{480}{}{Co chceš?}
{481}{}{Co chceš?}
{482}{}{Oh, nic.}

# 11. Bullet (From 8)
{500}{}{Huh?}
{501}{}{Nevadí. Jste volnı, mùete jít. Metzger je mrtvej.}

# 12. You Free (From 8)
{510}{}{Jak volnı? Zlej mu je pryè? Padáme! Dìkujeme ti. Kamaráde! Sbohem!}
{511}{}{Volnı? Coe? Všechny jsi je zabil? Tak ti moc dìkujeme! Radìji zmizíme dokud mùeme. Ještì jednou dìkujeme, jsi svatej!}

# 13. NPC Sold to Slavery (From WTG)
{520}{}{K èertu s tebou!}
{521}{}{Sma se v pekle!}
{522}{}{Za to zaplatíš.}
{523}{}{Proè na mnì poøád mluvíš?}
{524}{}{Nechej mì o samotì.}
{525}{}{Nechci se s tebou bavit.}
{526}{}{Jak si mohl?!}
{527}{}{U tì nechci nikdy vidìt.}
{528}{}{Nevypadá to, e se nìco zmìní.}
{529}{}{Pùjdu svou cestou, jestli ti to nevadí.}
{530}{}{Prosím, jen mì nechej jít.}
{531}{}{Jen mì nechej jít svou cestou.}
{532}{}{Poøád se s tebou nechci bavit.}
{533}{}{Nechej mì bıt.}
{534}{}{Bez šance.}
{535}{}{Myslel sis, e to takhle bude lepší?}

# 6. BGF: Just Freed
{600}{}{Jdeme?}
{601}{}{ádná bolest?}
{602}{}{Jdi!}
{603}{}{Domù!}
{604}{}{Volnı?}
{605}{}{Huh?}
{606}{}{Coe?}
{607}{}{Øekl jsi "volnı"?}
{608}{}{U jsem pryè!}
{609}{}{Pojïme!}
{610}{}{Všichni! Jsme volnı!}
{611}{}{Jooooooooo!}

{700}{}{Osvobodil jsi otroky z jejich kotce.}
