#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
# 0. Male Look - Primitive
{100}{}{Vidíš velkého, primitivnì vypadajícího muže.}
{101}{}{Vypadá skuteènì silný a nebezpeèný.}

# 1. Female Look - Primitive
{110}{}{Vidíš primitivní ženu.}
{111}{}{Vypadá na svojí výšku dost silná.}

# 2. Male Look - Nomad
{120}{}{Vidíš nebezpeènì vypadajícího muže.}
{121}{}{Vypadá skuteènì silný.}

{130}{}{Vidíš udìlanýho chlápka.}
{131}{}{Tenhle vypadá opravdu silnì.}

{140}{}{Vidíš chlápka v otrhaných šatech.}
{141}{}{Pohybuje se celkem rychle.}

# 3. Female Look - Nomad
{150}{}{Vidíš velmi grimasní ženskou.}
{151}{}{Nevypadá, že by nìkdy vidìla koupelnu.}

{160}{}{Vidíš tlustší ženskou.}
{161}{}{Vypadá jako silný bojovník.}

{170}{}{Vidíš vychrtlou ženu.}
{171}{}{Tahle nevypadá, že by kladla velký odpor.}

# 4. CF: Hostile Primitive
{200}{}{Chcípni!}
{201}{}{Byl jsi tam?}
{202}{}{Ublížím ti.}

# 5. CF: Hostile Nomad
{210}{}{Chystám se tì dostat!}
{211}{}{Zkurvený otrokáøi!}
{212}{}{Za to zaplatíš!}

# 6. CF: Fleeing Primitive
{220}{}{Nech mì být!}
{221}{}{Nech toho!}
{222}{}{Nechci ti nic udìlat!}
{223}{}{Nebojuju!}

# 7. CF: Fleeing Nomad
{230}{}{Poznávám tohle tetování!}
{231}{}{Ne, prosím!}
{232}{}{Prosím nezabíjej mì!}
{233}{}{Nechci bojovat; nezabíjej mì!}
{234}{}{Prosím, nechci umøít!}
{235}{}{Jste otrokáøi, ne? Oh, bože.}

# 8. BF: Hostile Primitive
{245}{}{Tiše! Jsou blízko.}
{246}{}{Zabij je, parchanty.}
{247}{}{Neber mi rodinu.}
{248}{}{Chráním rodinu.}
{249}{}{Nesmí nás najít.}
{250}{}{Ti zlí.}

# 9. BF: Hostile Nomad
{260}{}{Otrokáøi jdou. Všichni ticho.}
{261}{}{Pøipravte se; Myslím, že už jsou blízko.}
{262}{}{Nezemøu bez boje.}
{263}{}{Nikdy nás nezotroèí.}
{264}{}{Zaplatí za to.}
{265}{}{Žádnej otrokáø mi nebude sahat na rodinu.}

# 10. BF: Fleeing Primitive
{270}{}{Nenajdou mì.}
{271}{}{Musím se schovat.}
{272}{}{Proè mi chtìjí ublížit.}
{273}{}{Já ubohý.}
{274}{}{Nebojuju.}
{275}{}{Chci žít.}
{276}{}{Neubližuj mojí rodinì.}

# 11. BF: Fleeing Nomad
{280}{}{Oh, do prdele!}
{281}{}{Proè to dìlají?}
{282}{}{Co je s mojí rodinou?}
{283}{}{Nechci zemøít.}
{284}{}{Nechci být otrok.}
{285}{}{Zasloužil bych si nìco lepšího než tohle.}

# 12. Combat Float: Hostile Primitive
{290}{}{Teï zemøeš!}
{291}{}{Zabij mì!}
{292}{}{Mou rodinu nech bejt!}
{293}{}{Neber mi rodinu!}
{294}{}{Budu ji chránit!}
{295}{}{Ublížím ti!}
{296}{}{Za to zaplatíš!}

# 13. Combat Float: Hostile Nomad
{300}{}{Rodinu mi nevezmeš, bastarde!}
{301}{}{Zemøi, otrokáøskej èerve!}
{302}{}{Za to zaplatíš, bastarde!}
{303}{}{Budu bojovat až do smrti za svoji rodinu!}
{304}{}{Odtud se nedostaneš!}
{305}{}{S mými pøáteli neodejdeš!}

# 14. Combat Float: Fleeing Primitive
{310}{}{Ahhh!}
{311}{}{Nezabíjej!}
{312}{}{Stop!}
{313}{}{Pomóóóóc!}
{314}{}{Bìž!}
{315}{}{Nedìlej to!}

# 15. Combat Float: Fleeing Nomad
{320}{}{Zachraòte se, uteète!}
{321}{}{Nenech je aby tì dostali!}
{322}{}{Otrokáøi! Utíkej!}
{323}{}{Pomozte mi nìkdo! Prosím!}
{324}{}{Utíkej, Marty!}
{325}{}{Ahhh!}
{326}{}{Zastavte to šílenství!}
{327}{}{Nemùžeme nic dìlat! Nechávejte nás tady!}
