#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
# 0. Look
{100}{}{Vidíš otrokáøe.}
{000}{}{Vidíš otrokáøe jménem Aidan.}

{150}{}{Vypadá že se o sebe v boji umí dobøe postarat.}

# 1. First Time - Self Initiated (From Where to go)
{200}{}{Ach, èerstvý maso.... Vítej v cechu Otrokáøù. Jmenuji se Aidan. Jsi tady obchodnì? Bylo by to pro tebe lepší!}
{201}{}{Co vlastnì pøesnì váš Cech dìlá?}
{202}{}{Otrokáøský Cech?}
{203}{}{Cejchu otrokáøù?}
{204}{}{Aruk kun sung?}

# 2. Yes, join (From 4)
{215}{}{(Aidan si tì prohlíží od hlavy k patì.) Dobrá , vypadá to že tam chceš rovnou vpadnout, bobíku, ale nejdøív si musíš promluvit s Metzgerem. Pøímo za tìma zadníma dveøma.}
{216}{}{(Aidan si tì prohlíží od hlavy k patì.) Nevypadáš na to, že to zvládneš, ale já do toho nemám co kecat. Jdi si promluvit s Metzgerem. Jdi tìmi zadními dveømi.}
{217}{}{Øekl sem ti, že musíš mluvit s Metzgerem. Jsi jenom hluchej nebo tak blbej?}
{218}{}{Kdo je Metzger?}
{219}{}{Další otázky pøíštì.}
{220}{}{Díky, budu.}
{221}{}{Medger}
{222}{}{Uh... dobøe.}

# 3. Hostile, Start Combat. (From Where to go)
{230}{}{Teï chcípneš.}

# 4. (From Where to go, 1-2, 6, 10-11, 16-18)
{240}{}{Nechtìj mì nasrat! Chytáme a prodáváme otroky. To je dùvod proè si tady, mám pravdu?
 Hledáš nìjakou akci?}
{241}{}{Nechtìj mì nasrat! Chytáme a prodáváme otroky. Pokud tady nejsi kvùli tomu, tak co chceš?} # Intentional errors, please do not change.
{242}{}{Tak, pøiprav se. Mùže to být zajímavé. Pokud máš rád akci, si tady na správné adrese. Pokud ne, dlouho nepøežiješ.}
{243}{}{Nikdy sem si nemyslel, že uvidím tohle tetování na ženì. Vypadá to dobøe. To Metzgera pøekvapí... k èertu s tím. Tak co potøebuješ?}
{244}{}{Co chceš? Ztratil si nìco?}
{245}{}{Ahoj, malá lady. Co potøebuješ?}
{246}{}{Co?}
{247}{}{Hledám zábavu.}
{248}{}{Kde berete vaše otroky?}
{249}{}{Chci nìjaké koupit.}
{250}{}{Znáš muže jménem Vic?}
{251}{}{Hledám Obchodníka.}
{252}{}{Slyšel si nìkdy o Vault 13?}
{253}{}{Sbohem.}
{254}{}{Práce.}
{255}{}{Jídlo.}
{256}{}{Vražda.}
{257}{}{Ug.}

# 5. Dumb Kill (From 4)
{270}{}{Ach, krvežíznivec. Dobrá... Promluv si s bossem. Možná budeme mít pro tebe místo. Jdi tìmi zadními dveømi.}
{271}{}{Metzger nikdy nemìl dìvku jako otrokáøku, ale pokud si opravdu tak krvežíznivá, promluv si s ním. Je pøímo za tìmahle dveøma.}
{272}{}{Oukej.}
{273}{}{Uh.}
{274}{}{Krook}

# 6. Buy slaves (From 4)
{280}{}{Promluv s Metzgerem. Normálnì veøejnosti neprodává. Má mnoho... velkých zákazníkù.}
{281}{}{Kdo je Metzger?}
{282}{}{Mùžu chtít nìco jinýho?}
{283}{}{Oukej, sbohem.}
{284}{}{Co je s Vicem?}

# 7. Dumb Exit (From 1, 4)
{290}{}{Nic neøíkej. Udeø!}
{291}{}{Blbá dìvka.}
{292}{}{Oook?}
{293}{}{Hmph.}

# 8. What about buying Vic (From 6, 19)
{300}{}{Tak to pochybuju. Ten zasranej blb Vic nasral Metzgera s nìjakým rádiem, nebo co. Nevím jestli ti ho prodá. Musíš si s nim promluvit sám.}
{301}{}{Dobrá, slyšel jsem, že zkurvil rádio. Mìl by ses zeptat Metzgera. Není teï moc použitelnej, není moc dobrý kvality.}
{302}{}{Kdo je Metzger?}
{303}{}{Kde je Metzger?}
{304}{}{Oukej, díky. Sbohem.}

# 9. Where's Metzger (From 8)
{310}{}{Je v zadní místnosti, pøímo za tìmahle dveøma.}
{311}{}{Hraješ si se mnou? Je pøímo tamhle vzadu. Projdi tìmahle dveøma.}
{312}{}{Oukej.}
{313}{}{Díky.}

# 10. Who's Metzger? (From 2, 8, 16)
{320}{}{Hlupáku, ty neznáš Metzgera? Co dìláš v tomhle mìstì, když ho nechceš vidìt? Je hlava obchodu s otroky.}
{321}{}{Kolikrát ti to mám øíkat? On je šéf otrokù. Øídí tohle mìsto.}
{322}{}{Mùžu se ještì na nìco zeptat?}
{323}{}{Oukej, díky.}

# 11. Where do you get slaves from? (From 4)
{330}{}{Nemám o tom s nikým mluvit. Metzger by mi dal. Nechtìli bychom potom venku potkat nìjakou konkurenci.}
{331}{}{Už sem øek. Nebudu o tom mluvit.}
{332}{}{Øekni mi to pøedtím, než ti udìlám díru do hlavy.}
{333}{}{Rozumím. Další otázky?}
{334}{}{Oukej, sbohem.}

# 12. Threatened life (From 11)
{340}{}{Poslouchej, ty malej posránku, nepokoušej se vyhrožovat mì nebo nìkomu jinému v našem cechu nebo jsi mrtvej. Rozumíš? Mrtvej.}
{341}{}{Poslouchej, ty kozomrde. Nepokoušej se vyhrožovat mì nebo nìkomu jinému v našem cechu nebo jsi mrtvej. Rozumíš? Mrtvej.}
{342}{}{Teï chcípneš.}
{343}{}{Zašlápnu tì jako hada.}
{344}{}{Promiò, prosím neubližujte mi.}
{345}{}{Jasnì, cokoliv. Nechám tì tentokrát naživu.}

# 13. Threaten back (From 12)
{350}{}{Oh, opravdu? Možná ti udìlám díru do hlavy tady a teï. Co myslíš, horká støelo?}
{351}{}{Tak vystøel nejlíp jak umíš.}
{352}{}{Nechtìj mì rozesmát.}
{353}{}{Jenom jsem si dìlal srandu.}
{354}{}{Omlouvám se. Zkoušel jsem si vás pøedstavit.}

# 14. Run along (From 12, 13)
{360}{}{Utíkej, než si to rozmyslím.}
{361}{}{Oukej.}

# 15. Food? (From 4)
{370}{}{Cože? Oh, ty musíš hledat Mámu. Jsi o jednu budovu vedle.  Je v budovì pøímo na jih. J-i-h. Tudy. (Aidan ukazuje na dveøe.)}
{371}{}{Huh? Uh... Oh.}

# 16. Yes, join - Female (From 4)
{380}{}{Vypadáš, že bys mohla jít dovnitø, ale Metzger nikdy nenajímá ženskou. Nejsem si jist proè, ale pochybuju, že by teï zaèal.}
{381}{}{Nevypadáš jako ten typ. Sakra, Metzger nikdy nenajímal ženský. Nevím jisté proè, ale pochybuju, že by teï s tím zaèal.} # Error intentional, please do not remove.
{382}{}{Øekl jsem, že musíš mluvit s Metzgerem.}
{383}{}{Kdo Metzger?}
{384}{}{Jinou otázku.}
{385}{}{Díky, budu.}
{386}{}{Medger}
{387}{}{Uh... kay.}

# 17. Vault 13? (From 4)
{400}{}{Ne, ale bejt tebou tak se zeptám šéfa. On byl pravdìpodobnì všude v tomhle zkurveným svìtì.}
{401}{}{Další otázka.}
{402}{}{Oukej, díky. Sbohem.}

# 18. Vic/Merchant? (From 4)
{410}{}{Obchodníka? Joo, ty myslíš Vica, ten co prodává vìci ze starých Vaultù. Je v prdeli. Metzger s nim pìknì vyjebal.}
{411}{}{ooo, Vic... ten obchodník, že jo? Ten co prodává starý vìci z Vaultù. Je v prdeli. Metzger s nim pìknì vyjebal.}
{412}{}{Kolikrát se mì na to chceš ještì ptát? Metzger ho dostal.}
{413}{}{Kdo je Metzger?}
{414}{}{Mùžu se zeptat na nìco jinýho?}
{415}{}{Je na prodej?}
{416}{}{Oukej, díky.}

# 19. Float Greeting (From WTG)
{430}{}{Hej, hoši, kouknìte kdo je vzadu.}
{431}{}{Utíkejte, to je otrokáø! To je k popukání.}
{432}{}{Zpátky kvùli akci?}
{433}{}{Znáš cestu.}
{434}{}{Pojïme.}
{435}{}{Èeká na tebe.}
{436}{}{Co teï?}
{437}{}{Znám ten oblièej.}
{438}{}{Jak to jde?}
{439}{}{Jsi zpátky. Jdeš se zabavit?}
