#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
# 0. Look
{100}{}{Vidíš otrokáøe.}

{150}{}{Vypadá, že to je jeden z Metzgerových osobních strážcù.}

# 1. CF: Hostile
{200}{}{Tady jsi.}
{201}{}{Teï chcípneš.}

# 2. CF: Normal
{300}{}{Chceš vidìt šéfa? Jdi dovnitø.}
{301}{}{Metzger je ten s kým chceš mluvit, ne já.}
{302}{}{Jdi dál.}
{303}{}{Chovej se slušnì.}
{304}{}{Metzger je pøímo za tìmahle dveøma.}
{305}{}{Hlavnì Metzgera nenaser.}
{306}{}{Pokud chceš tohle, tak to není na prodej.}
{307}{}{Stále nepotøebujeme žádné ženské otrokáøky.}
{308}{}{Je to pìkný, že jdeš s námi.}
{309}{}{Ahoj. Jak to jde?}
{310}{}{Hledal jsi teï nìjaký otroky?}
{311}{}{Ahoj.}
{312}{}{Jdeš na pøíští hon?}
{313}{}{Hodnì se zmìnilo.}
{314}{}{Kdy pùjdeme do akce?}
{315}{}{Nemùžu jít na hon otrokù. Zatracený strážení.}
{316}{}{Hony otrokù jsou bomba.}
{317}{}{Hej, kámo, jsem rád že jsi tu s náma.}
