#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
# 0. Look
{100}{}{Vidíš umaštìného starého chlápka.}

{150}{}{Vidíš Smittyho, mechanika.}
{151}{}{Vidíš umaštìného starého chlápka ve špinavıch montérkách.}

# 1. Get out floats (WtG)
{200}{}{Varuju tì! Vypadni odsud, ne ti dám po rypáku!}
{201}{}{Vypadni z mého místa!}
{202}{}{Zmiz z mého pozemku!}
{203}{}{Varuju tì, zmiz odsud.}
{204}{}{Sakra, jdi ode mì.}

# 2. Low Intelligence (WtG)
{220}{}{Hej, zmiz z mého pozemku.}
{221}{}{Ty tam, pitomèe, vypadni odsud.}
{222}{}{Zmiz, jdi, zmiz!}
{223}{}{Nemám na tebe èas.}
{224}{}{Promiò, myslím, e neumím mluvit imbecilštinou.}

# 3. Hello (WtG, 4,5,11, 17,20,25)
{240}{}{Nazdárek, èlovìèe. Co pro tebe mùe starej Smitty udìlat?}
{241}{}{Nazdar. Co pro tebe mùe starej Smitty udìlat?}
{242}{}{Tááke... co pro tebe mùu udìlat?}
{243}{}{Hej ty, pochutnal sem si na jídle od Mámy. Díky. Co pro tebe mùe starej Smitty udìlat?}
{244}{}{Jen mì zajímá co tady dìláš?}
{245}{}{Øíkám chlapèe, mám tuhle vìc tady z Gecka....}
{246}{}{Hele Smitty... zajímá mì to auto, co tu prodáváš.}
{247}{}{Nesu ti jídlo od Mámy.}
{248}{}{Øíkám ti, chlapèe, mám tuhle vìc tady z Klamathu....}
{249}{}{Jen se tak trochu rozhlíím. Nashle pozdìji, Smitty.}

# 4. Thing from Gecko (3)
{260}{}{Nech starıho Smittyho a se na to podívá.}
{261}{}{Jistì, tady to je.}
{262}{}{Vteøinku, nech mì zeptat se na nìco jinıho.}
{263}{}{Moná jindy. Sbohem, Smitty.}

# 5. Thing from Klamath (3)
{280}{}{Nech starıho Smittyho, a se na to podívá.}
{281}{}{Jistì, tady je to.}
{282}{}{Vteøinku, nech mì zeptat se na nìco jinıho.}
{283}{}{Moná jindy. Sbohem, Smitty.}

# 6. Use Controller? (4)
{300}{}{Dobrá, to vypadá jako starı kontroler pøívodu energie. Hmm, vsadím se, e kdy tohle pouiju na starıho Highwaymana, bude potom pøíst jako koèka.}
{301}{}{He?}

# 7. Use Regulator? (5)
{310}{}{Hmm, tohle vypadá pøesnì jako regulátor pøívodu energie. Kdybych mìl funkèní auto, tak by tahle vìcièka urèitì zvıšila poèet ujetıch kilometrù.}
{311}{}{Heh?}

# 8. Meal from Mom's delivered (3,18)
{320}{}{To od tebe bylo velice šlechetnı. Díky moc, kámo. Tady máš nìco malıho, abych se ti aspoò trošku revanšoval. Bude se ti to v tıhle èásti zemì urèitì hodit. (Podává ti Stimpak.)}
{321}{}{Díky, Smitty. ádnej problém. Uvidíme se.}
{322}{}{Dobrá, uhhh... díky, ale já u sem si pro jídlo skoèil k Mámì, take u to nebudu potøebovat.}
{323}{}{Sakra, já nejsem normální roznašeè jídla. Ten je nemocnej a já za nìj zaskakuju. Mùu pøesto dostat aspoò nìjaké zkušenostní body?}
{324}{}{Oukej, omlouvám se, e sem to popletl. Doufám, e mì Máma zato nevyhodí! Opravdu tuhle práci potøebuju.}
{325}{}{Hele, nerad bych 24 hodin nìkam nesl jídlo zbyteènì, to není zadarmo, jasnı?}
{326}{}{Dobrá, moná e to sním pozdìji.}
{327}{}{Máma z toho nebude mít moc velkou radost.}

# 9. Tell about car (6,7)
{330}{}{Dobrá, vidíš, mám tohle auto, Chrysalis Motors Highwayman. Je to kráska. Øíkávalo se, e "Nic nemùe zastavit Highwaymana." Dobøe stavìnı, to teda opravdu byly.}
{331}{}{Jo, a co to má dìlat se mnou?}

# 10. Car-Controller (9)
{340}{}{Mnoo, vidíš, myslel jsem, e potøebuju novou baterku, ale co opravdu potøebujuje, je kontroler pøívodu energie. U to zaèalo bıt moc špatnı.}
{341}{}{Noo, já tu mám jeden.}

# 11. I've got one of those (10)
{350}{}{ake... Udìlám ti nabídku. Ty mi dáš $2,000 a já ti prodám auto. Hernajs dokonce ti tam namontuju i ten kontroler pøívodu energie. Pobìí to jako novı. Nabiju ho pomocí nìkolika speciálních mikrofúzních baterií, které mám.}
{351}{}{To zní dobøe. Tady sou prachy a ta souèástka.}
{352}{}{Nemyslím, e to chci provést právì teï. Zeptám se tì na nìco jiného, Smitty.}
{353}{}{Dej mi èas na rozmyšlenou. Podívám se zatím okolo, Smitty.}

# 12. Here's the car (12)
{370}{}{Dávej na nìj pozor, aby se nepøehøálo.}
{371}{}{Oukej, budu. Díky, Smitty.}

# 13. Car-Regulator (9)
{380}{}{Dobrá, je to hodnì ale ne moc.}
{381}{}{Huh?}

# 14. What? (13)
{390}{}{Øíkám, e mít regulátor je sice hezkı, ale ty potøebuješ kontroler pøívodu energie.}
{391}{}{K èemu?}

# 15. Why? (14)
{400}{}{Protoe kdybys mìl kontroler a $2,000, mohl bych opravit Chrysalis Motors Highwaymana, kterıho tady mám a ty bys mohl stylovì odjet.}
{401}{}{Opravdu? Kde bych mohl najít ten kontroler pøívodu energie?}

# 16. Where do I find one of those? (15)
{410}{}{To je hloupá otázka. Nemyslíš si e to vím, protoe jinak bych tu u dávno jezdil autem?}
{411}{}{Jo. Budu se muset po nìjakém podívat.}

# 17. Look for one (16)
{420}{}{Dobrej nápad. A nìjakej najdeš tak se vra. Jo, a nezapomeò $2,000.}
{421}{}{Zní to jako dobrej plán, Smitty. Hej, chtìl bych se zeptat ještì na nìco.}
{422}{}{Jdu se teï po nìjakém podívat. Sbohem.}

# 18. Player bought car (WtG)
{430}{}{Hej ty tam, jak ti to auto jezdí?}
{431}{}{Velmi dobøe, Smitty, Ale našel jsem tohle a nevím co s tím mám dìlat.}
{432}{}{Skvìle, Smitty, perfektní. Hej, pøines sem ti jídlo. Zlatá Máma.}
{433}{}{Opravdu dobrı, Smitty, opravdu dobrı. Díky. Jedu dál. Sbohem.}

# 19. Have regulator (18)
{450}{}{Dobrá, tady je kontroler pøívodu energie. Teï ujedeš s kadou baterií více kilometrù. Mùu ti to tam namontovat, kdy mi dáš øeknìme $750 za práci.}
{451}{}{Vypadá to jako nabídka, Smitty. Tady to máš i s prachama.}
{452}{}{Budu o tom pøemıšlet, Smitty. Zatím sbohem.}

# 20. What do you do here? (3)
{460}{}{Vìtšinou jen dohlíím na tohle staré harampádí. Je tu jen jedna vìc, která za nìco stojí.}
{461}{}{Co je to?}
{462}{}{Jo to mi došlo. Zeptám se na nìco jiného.}

# 21. What's worth anything? (20)
{470}{}{Protoe není jinı tak dobrı auto ne tenhle Chrysalis Motors Highwayman. Øíká se "Nic nemùe zastavit Highwayman." je perfektnì stavìnı, zato ti ruèím.}
{471}{}{Hezkıı, bìí to?}

# 22. Does it run? (21)
{480}{}{Pokud by to bìelo, myslíš e bych byl stále v tıhle zasranı èásti mìsta?}
{481}{}{Uh, ano.}
{482}{}{Nemyslím.}

# 23. Yes (22)
{490}{}{Dobrá, asi máš pravdu. U sem se tu usadil.}
{491}{}{Já vím.}

# 24. No (22)
{500}{}{Dobrá, tak znovu, já moná taky. Mám tady veškerı pohodlí.}
{501}{}{Rozumím.}

# 25. Got car (23,24 )
{510}{}{Nemyslím, e bych to auto prodal. Jestli mi nìkdo pøinese baterky - tak ani nápad, hmm, myslím, e budu potøebovat kontroler pøívodu energie. Joo, pokud ho neseenu, prodám auto za $2,000. Kdy nainstaluju kontroler, pobìí dobøe.}
{511}{}{To zní zajímavì. Vrátím se, jestli seenu ten kontroler pøívodu energie. Ještì se chci na nìco zeptat.}
{512}{}{Kdy ho najdu, vrátím se. Sbohem, Smitty.}

# 26. Regulator installed  (19)
{520}{}{Tam jdi. Jako novej. Take a ti šlape dobøe.}
{521}{}{Budu. Díky, Smitty. Sbohem.}

{600}{}{JDI SAKRA PRYÈ VOD MİHO AUÁKU!}

{650}{}{Nechtìj, abych tì ještì jednou chytil, jak se touláš okolo mého auta.}
{651}{}{Nebudeš.}
{652}{}{Uggg-K}
