#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš barmanku.}
{101}{}{Vidíš Leannu.}
{102}{}{Je velmi krásná, ale vypadá zamyšlenì.}
{103}{}{Pøestaò!}
{104}{}{Proè to dìláš?}
{105}{}{Nech mì být!}
{106}{}{Prosím pøestaò!}
{107}{}{Ty vrahu!}
{108}{}{Jak si to mohl Becky udìlat!}
{109}{}{Co ti udìlala?}
{110}{}{Budeš se smažit v pekle.}
{111}{}{Promiò, žádný pøíbìhy nemám.}
{112}{}{Dìkuji za pití.}
{113}{}{Je pøíjemné mluvit s tebou.}
{114}{}{Díky žes mì vyslechl.}
{115}{}{Ráda tì zase vidím.}
{116}{}{Bezpeèné cestování.}
{117}{}{Ahoj! Je fajn vidìt tady nový oblièej. Mé jméno je Leanna. Jak se máš, sedneš si?}
{118}{}{Ahoj. Daøí se dobøe, doufám?}
{119}{}{Tak, øekni mi co víš o Vùdci.}
{120}{}{Ohromný. Jak se daøí tobì?}
{121}{}{Velmi dobøe.}
{122}{}{Nemùže teï mluvit. Sbohem.}
{123}{}{Igsby?}
{124}{}{Bgy.}

# Node005 removed.

{131}{}{Oh, omlouvám se. Nerozumím. Nemìl bys tolik pít.}
{132}{}{Ugra.}
{133}{}{Fegi.}
{134}{}{Oh, velmi dobøe. Díky za optání. Becky má zajímavej rodinnej pøíbìh. Máš taky?}
{135}{}{Stále to jde, díky. Kde jsme to skonšili? Myslím že jsme mluvili trochu o historii tvojí rodiny?}
{136}{}{Ano. Jsem ten Vyvolený. Mùj pøedek zachránil svìt pøed nìjakým Vùdcem.}
{137}{}{Jo. Mùj pøedek zachránil svìt pøed nìjakým Vùdcem.}
{138}{}{Musím jít.}
{139}{}{Dobrá. Ráda jsem tì poznala Vyvolený... Opravdu. Nìco jsem o tom Vùdcovi kdysi už slyšela.}
{140}{}{Jak zajímavé. To mi pøipomíná jeden starej pøíbìh, který jsem slyšela. Nìco o Vùdci.}
{141}{}{Opravdu? Co to bylo?}
{142}{}{Øekni.}
{143}{}{Oh, oukej. Sbohem.}
{144}{}{Zabere to chvilku. Buï gentleman a kup mi drink, koupíš? Ne whiskey, Nuka-Colu prosím.}
{145}{}{Zabere to chvilku. Buï gentleman a kup mi drink, koupíš? Ne whiskey, Nuka-Colu prosím.}
{146}{}{Mùžeme zaèít? Pamatuji si to docela dobøe.}
{147}{}{Jistì.}
{148}{}{Sorry, Nemám teï zrovna $5.}
{149}{}{Díky. Tak poslyš... pamatuji si, jak mi máma vyprávìla o té velké migraci, která se stala pøed 70 nebo 80 lety...}
{150}{}{Pokraèuj prosím.}
{151}{}{Opravdu velký ozbrojení mutanti vysocí jako já a ty pøišli z jihu. Máma øíkala, že to vypadalo jako velká migrace.}
{152}{}{Kolik?}
{153}{}{Nevím, ale byly jich velký skupiny. Nìkteøí šli na sever, jiní na východ. Nikdo nevìdìl kam jdou.}
{154}{}{Pokraèuj.}
{155}{}{Byli celkem rozrušení a vypadalo to, že pøed nìèím utíkali.}
{156}{}{Opravdu?}
{157}{}{Joo, byli špinaví, v roztrhaných šatech... Mluvili o tom, že Vùdce je mrtev...}
{158}{}{Zajímavé.}
{159}{}{Nìkteøí z nich dokonce tady pøímo ve mìstì spáchali sebevraždu!}
{160}{}{Cože?}
{161}{}{Mluvili o Vùdci, kterého tvùj pøedek zabil.}
{162}{}{Díky za pøíbìh.}
{163}{}{Dobrá, už je pozdì. Sbohem.}
{164}{}{Bylo mi potìšením. Sbohem.}
{165}{}{Sbohem.}
{166}{}{Už nic.}
{167}{}{Leanne ti øekla pøíbìh o Vùdci.}
