#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš barmana.}
{101}{}{Vidíš Stacy.}
{102}{}{Vypadá trochu usedle.}
{103}{}{Pøestaò!}
{104}{}{Jak mùžeš?}
{105}{}{Jdi ode mì pryè!}
{106}{}{Proè?}
{107}{}{Pøestaò prosím!}
{108}{}{Ty vrahu!}
{109}{}{Chudák Máma! Za to zaplatíš!}
{110}{}{Mami...}
{111}{}{Byla ke všem tak milá...}
{112}{}{Sorry, nemùžu myslet na nic jiného.}
{113}{}{Mùj mozek je celej vyschlej.}
{114}{}{To je ono.}
{115}{}{Ahoj.}
{116}{}{Už si pozdravil Mámu?}
{117}{}{Oh, ahoj.}
{118}{}{Oh, zase ty.}
{119}{}{Povìz mi o tvojí koèce.}
{120}{}{Tak proè ten zasmušilý oblièej?}
{121}{}{Chodíš sem èasto?}
{122}{}{Najdu si tì pozdìji. Sbohem.}
{123}{}{Oukej?}
{124}{}{Ug.}

# Node 005 removed

{131}{}{Prosím nech mì být. Nemám zrovna dobrou náladu.}
{132}{}{Ugra.}
{133}{}{Fegi.}
{134}{}{Oh, skuteènì nic. Jenom obèas pøemýšlím o mámì a mojí koèce. Obì mi chybí.}
{135}{}{Koèce?}
{136}{}{Promiò že jsem poslouchal. Sbohem.}
{137}{}{Joo, ochoèila jsem jí. Byla to sladká koèka. Nemám náladu o tom mluvit... pokud mi nechceš koupit drink. To by pomohlo.}
{138}{}{Jak sem øekla, nechci o tom teï mluvit. Pokud mi nechceš koupit drink. To by pomohlo.}
{139}{}{Samozøejmì že chci. Chci to slyšet.}
{140}{}{Jistì.}
{141}{}{Promiò, nemám zrovna $10.}
{142}{}{Jasòaèka.}
{143}{}{Myslíš, že jsi vtipnej? Polepši se.}
{144}{}{Tak proè se tak mraèíš?}
{145}{}{No jo, sbohem.}
{146}{}{Slyšel jsem, že tu byli nìjací, co byli velký asi tak jako já nebo ty. Zbaštili zvíøata velký jako jsou brahmíny na posezení. A teï není co žrát.}
{147}{}{To nic.}
{148}{}{Joo, to je.}
{149}{}{To stvoøení, o kterém mluvím, je malé pøíjemné zvíøátko, vìtší než krysa, ale menší než pes. Nìkteré jsou hodnì chlupatá, jako moje Cuddles, ale jiné zase mají krátkou srst.}
{150}{}{Opravdu?}
{151}{}{Mùžou být taky domácím zvíøetem jako jsou tøeba psi, ale koèky dìlají takový krásný vrnivý uklidòující zvuk, když je hladíš.}
{152}{}{Strašný.}
{153}{}{Cuddles mi vždycky v noci pomáhala jít spát. Myslím na ní každou noc, když se nemùžu dostat do postele.}
{154}{}{To zní pìknì.}
{155}{}{Pokraèuj.}
{156}{}{Mìla jsem ji když jsem byla dítì. Nevím co se s ní potom stalo, byla jsem moc mladá.}
{157}{}{Proè?}
{158}{}{Dobrá, Bylo málo jídla, a lidi potøebovali jíst. To je øeèeno dost jasnì...}
{159}{}{Co?}
{160}{}{Lidi je loví, protože je to snadná koøist. Díky tomu už tady v okolí taky na žádnou nenarazíš.}
{161}{}{Do prdele!}
{162}{}{Nemùžu to pochopit.}
{163}{}{Ovšem tyhle jsou divoké, ta moje nebyla a už sem si jistá co se s ní stalo. Už vím, proè se Máma na ní poøád tak divnì dívala.}
{164}{}{Jak øíkáš.}
{165}{}{Je mi to líto.}
{166}{}{Oh...}
{167}{}{Bolí mì srdce, když si na to vzpomenu...}
{168}{}{Sbohem.}
{169}{}{Stacy ti povìdìla pøíbìh o její sladké koèce Cuddles.}
