#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš rváèe.}

{150}{}{Rváè vypadá pìknì tvrïácky.}
{151}{}{Zmizni mi z oèí.}
{152}{}{Øíkáš si o problémy?}
{153}{}{Pokraèuj v chùzi.}
{154}{}{Nemám zájem.}
{155}{}{Jdi pryè.}

{200}{}{Hej pankáèi.}
{201}{}{Máš problém?}
{202}{}{Pojï sem, slaïouši.}
{203}{}{Nechtìj, abych k tobì šel a nakopal ti prdel.}
{204}{}{Mluvíš se mnou?}
{205}{}{Chceš nìco takového?}
{206}{}{Hej bejby, pojï sem.}
{207}{}{Hej, máš rád to co vidíš?}
