#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
# LOOKS
{100}{}{Vidíš feáka.}

{110}{}{Vidíš prodavaèe drog.}
{111}{}{Vidíš jednoho z Tybbyho prodavaèù drog.}

# EXAMINES
{150}{}{Je to asi Tubbyho kamarád.}

{160}{}{Vypadá e je extrémnì sjetej.}
{161}{}{Vypadá jako by projel velkej vodopád.}

# 1. CF: Tubby's Dead
{200}{}{Jo, chlape, kam teï do prdele pùjdeme?}
{201}{}{Proè si Tubbyho zabil?}
{202}{}{Chlape, to je v prdeli.}
{203}{}{Co teï budeme dìlat?}
{204}{}{Chlape...}
{205}{}{Hej, to není fér.}
{206}{}{Nech nás, nic neøekneme.}

# 2. CF: Standard
# LOW KARMA
{220}{}{Joo, vypadáš dobøe.}
# HIGH KARMA
{221}{}{Hej, jsi skuteènì krásnej chlap. U ti to nìkdo øek?}
{222}{}{Hej, jsi skuteènì krásnej chlap. U ti to nìkdo øek?}
# GENERIC
{223}{}{Jsme Tubbyho strá.}
{224}{}{Nemotej se tady. Tohle je Tubbyho místo.}
{225}{}{Hlupáku, cítím se dobøe.}
{226}{}{Vìøíš e jsme strá? Dobrı, ne.}
{227}{}{To je ohromnı.}
{228}{}{Oh, necítím nohy.}
{229}{}{Tubby je náš kámoš.}
{230}{}{Tubby nás dìlá šastnımi.}
{231}{}{Oh, ooh, ooooh... Zavøi mi oèi.}
# SLAVER
{232}{}{Hey, chlape, si otrokáø? Joo...}
{233}{}{Bolelo to tetování?}
{234}{}{Vy otrokáøi jste jistì ostøí hoši.}
{235}{}{Není nebezpeèné bıt otrokáø?}
# METZGER DEAD
{236}{}{Hej, slyšel jsem, e váš boss byl zastøelen, nebo co.}
{237}{}{Hej, slyšíš? Metzger je prej mrtvej, nebo co.}
{238}{}{Joo, nìkdo vyøídil Metzgera Øezníka.}
{239}{}{Doufám e Tubby zùstane ve kšeftì.}

# 3. BGF: Tubby Dead (From Where to go)
{250}{}{Joo. Zabil Tubbyho.}
{251}{}{Myslím e to stálo za hovno.}
{252}{}{Co se dìje?}
{253}{}{Co to bylo za hluk?}
{254}{}{Dangu, to nic nebylo.}
{255}{}{Joo, èlovìèe. Ona zabila Tubbyho.}

# 4. BGF: Standard
{260}{}{Ooooohhyaaa... Dobrej materiál.}
{261}{}{Co je to?}
{262}{}{Oh, jeee, já lítám.}
{263}{}{Oh, je to horkı.}
{264}{}{Ona je tak krásná.}
{265}{}{Oh, do prdele, nic nevidím.}

# 5. Conversation
# CONVERSATION 1
{270}{}{Joo, vidìl si to?}
{271}{}{Jasnì, víš co to bylo?}
{272}{}{Myslím e to byl pták.}
{273}{}{Ne, pes.}
{274}{}{Ale to byl lítající chlap.}
{275}{}{Není moné -- pøibliovalo se to k zemi.}
{276}{}{Noo, to se ti zdálo.}
{277}{}{Ne, ne. Bylo to skuteèné.}
{278}{}{Cokoliv.}
{279}{}{Ohhhh u je to tu zas. Ach.}

# CONVERSATION 2
{290}{}{Pìknı svìtla.}
{291}{}{Spoustu svìtel.}
{292}{}{Jsou horkı.}
{293}{}{A stromy.}
{294}{}{Kde jsou enskı?}
{295}{}{Tak zelenı a krásnı.}
{296}{}{Mám rád brambory.}
{297}{}{Stromy jsou ze døeva.}
{298}{}{Mám rád enskı a brambory.}
{299}{}{Kdy hoøí, tak se z nich kouøí.}
{300}{}{Ale ne dohromady.}
{301}{}{Na stromech ijí zvíøata.}
{302}{}{Ne, ne eny a stromy, enskı a brambory.}
{303}{}{Mùu na strom vylézt.}
{304}{}{enská lezoucí na strom a jí brambory? Jsi pitomec.}
{305}{}{Odkud se vzaly stromy?}
{306}{}{Nemùeš lézt na strom a jíst brambory.}
{307}{}{Taky mám rád buše.}
{308}{}{Dobrá, není to moc lehkı.}
{309}{}{Protoe jsou zelenı.}
{310}{}{Brambory nejsou zelenı.}
{311}{}{Ohhh, krásnı svìtla.}
{312}{}{Oh, bolí mì hlava...}

# 6. CF: Hostile
{320}{}{Nemluv na mì chlape. Bolí mì hlava.}
{321}{}{Nikomu to neøeknu.}
{322}{}{Nech mì.}
{323}{}{Nic jsem neudìlal.}
{324}{}{Nic sem nevidìl.}
{325}{}{Nic jsem neslyšel.}
{326}{}{Prosím, jdi u.}
{327}{}{Sleèno, necítím se dobøe, kdy mluvím. Ta moje zjebaná hlava mì zabíjí.}

# 7. BGF: Hostile
{340}{}{Chlape, jdi do prdele.}
{341}{}{Jak jsi se dokázal takhle zøídit?}
{342}{}{Hej, to bolí!}
{343}{}{Co je kurva?}
{344}{}{Jak se to mohlo stát?}

# CRACH WHORES
#8. Click Floats
{400}{}{Tubby je skvìlej.}
{401}{}{Drogy ze mì dìlají velikána.}
{402}{}{Tubby ví, jak se postarat o svoje enskı!}
{403}{}{Není Tubby skvìlej?}
{404}{}{Joo, bejby -- poèkej! Ty nejsi Tubby.}
{405}{}{Kde je náš velkej chlap?}
{406}{}{Nedìlá ti to takovı chvìní po kùi?}
{407}{}{Tubby má nejlepší vìci ve mìstì.}
{408}{}{Cítím se tak ivì!}

{420}{}{Neslyšel jsi nìco?}
{421}{}{Nevidìl jsem Tubbyho u chvíli.}
{422}{}{Kde je Tubby?}
{423}{}{Vidìl jsi Tubbyho?}

{440}{}{Oh, moje hlava!}
{441}{}{Kde je Tubby! Myslím, e umøu!}
{442}{}{U to nemùu dál brát.}
{443}{}{Oh, ta bolest je èím dál tím horší.}
{444}{}{Tubby nám teï ádnı nedá. Kde je?}
{445}{}{Mám suchı rty.}
{446}{}{Necítím svı prsty.}

#9. Hostile
{460}{}{Nech mì!}
{461}{}{Prosím, nedìlej to!}
{462}{}{Nevzal jsem to!}
{463}{}{To jsem nebyl já!}
{464}{}{Nech mì!}
{465}{}{Nevìdìl jsem e je to tvoje!}
