#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš majitele obchodu.}
{101}{}{Vidíš Tubbyho.}

{150}{}{Je to majitel obchodu.}
{151}{}{To je Tubby, majitel obchodu.}
{152}{}{[Mluvit]}
{153}{}{Radši bych byl, kdybys obchodoval nìkde jinde.}
{154}{}{Jsi obchodník, tak pojïme nìco smìnit.}
{155}{}{Mùžu se na nìco zeptat?}
{156}{}{Sbohem.}
{157}{}{Jsem rád, že tì zase vidím. Co pro tebe mùžu udìlat?}
{158}{}{Pojïme obchodovat.}
{159}{}{Mùžu se na nìco zeptat?}
{160}{}{Teï nic. Sbohem.}
{161}{}{Hello, pane, a vítejte u Tubbyho. Jsem majitel. Mùžu vám pomoct?}
{162}{}{Ano, jdem na to.}
{163}{}{Potøebuju nìjaké informace.}
{164}{}{Sbohem.}
{165}{}{Dobrý den, madam. Mé jméno je mezi pøáteli Tubby a vítám vás ve svém obchodì. Jak vám mohu pomoci?}
{166}{}{Chci nìco koupit.}
{167}{}{Potøebuji nìjaké informace.}
{168}{}{Sbohem.}
{169}{}{Budu radìji, když odejdeš.}
{170}{}{Sbohem.}
{171}{}{Máte zájem o nìjaké informace?}
{172}{}{Kdo vládne tomuhle mìstu?}
{173}{}{Proè všichni prodávají drogy?}
{174}{}{Víte kde je Vault?}
{175}{}{Rád bych nìco vymìnil.}
{176}{}{Nevadí. Sbohem}
{177}{}{Nemùžu øíct, že bychom mìli problém s komunikací. Øeknìte, jestli máte nìjaký zboží na obchod.}
{178}{}{[kývnout]}
{179}{}{Sbohem.}
{180}{}{Nikdo, bohužel. Den je místo anarchistù a je zde velmi nebezbeèno. Zde pøežijí pouze nejsilnìjší, nejrychlejší a nejchytøejší. Jsem si jist, že tu najdete nìjaké bezpeèné místo.}
{181}{}{Jo, díky.}
{182}{}{OK. Drogy jsou základem ekonomiky tohohle mìsta, tak jako jinde obilí nebo zlato.}
{183}{}{Díky.}
{184}{}{Slyšel jsem o místì zvaném Vault City. Ale bohužel, nepomùžu vám se smìrem. Víte, velmi málo z našich mìst mùže nabídnout tak rozsáhlou škálu lékaøských služeb, jaké poskytují tady, takže vìtšina z nás tam nikdy nebyla.}
{185}{}{OK. Díky.}
{186}{}{Tohle není typ informace, kterou bych øekl komukoliv.}
{187}{}{Zmìní sto babek váš názor?}
{188}{}{Co takhle $50.}
{189}{}{Co vy na to, buï mi øeknete tu informaci, a nebo budete mít díru v hlavì.}
{190}{}{Nevadí.}
{191}{}{Dobrá, Mùžu se ještì na nìco zeptat?}
{192}{}{Jistì, Tyhle prachy by mohli pomoct zmìnit názor. Ale vy je nemáte!}
{193}{}{Musel jsem je nìkde ztratit, jdu se podívat kde.}
{194}{}{Nemyslím, že to bude dost.}

#tell petey to hold on messages
{500}{}{Jistì Petey. Budu tam ve vteøinì.}
{501}{}{Vydrž, Petey!}
{502}{}{Už jdu, Už jdu.}

#sell petey drug messages
{510}{}{Tady jsi, Petey.}
{511}{}{Víš, Petey, mùžeš mi políbit prdel.}
{512}{}{Vesmi si tohle, a táhni do pekel, Petey.}
