#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
# 0. Look
{100}{}{Vidíš Tylera.}
{101}{}{Vidíš Tylera, hlavu gangu.}

{150}{}{Vypadá opravdu silnì.}

# 1. Messed with door.
{200}{}{Hej, nesahej na ty zkurvenı dveøe.}
{201}{}{Blbèe.}

# 2. Hostile
{210}{}{Teï to skonèíme.}

# 3. CF: Gang 1 Won.
{220}{}{Øíkal jsem ti, e to bude nìco.}
{221}{}{Bylo to jako by si vedl jehnì na poráku.}
{222}{}{Ta zkurvená dìvka je koneènì mrtvá!}
{223}{}{Díky za tip, bylo to skvìlı.}

# 4. CF: No Show
{230}{}{Kde jsi sakra byl?}
{231}{}{Polib mi prdel! Zasranej lháøi.}
{232}{}{Mohl bych ti hned jednu vrazit.}
{233}{}{Moc plánù, do prdele.}
{234}{}{Radši se mì nepokoušej nasrat.}
{235}{}{Jak jsi to moh posrat?}

# 5. CF: Trap Set
{240}{}{Pøivedl si sem ty pitomı bastardy a mi je zato pøibijeme ke zdi.}
{241}{}{Èekáme.}
{242}{}{Nemùeme èekat celou noc.}
{243}{}{Na co èekáme? Jsem pøipravenej na krev.}
{244}{}{Tak u dìlej! Nedovol, aby tì podezírali.}
{245}{}{Rychle, u to zaèíná.}

# 6. Trap = No (From WTG)
{250}{}{Kdo do prdele si a co chceš?}
{251}{}{Tak co chceš?}
{252}{}{Metzger mì posílá.}
{253}{}{Jsem tady na kontrole kostela.}
{254}{}{Vrátím se.}
{255}{}{Já }
{1255}{}{!}
{256}{}{Jooo?}

# 7. Metzger sent me (From 6)
{260}{}{Proè do prdele? Poøád kecá do všeho.}
{261}{}{To hovno ještì ani nikam nevylezlo s tou svojí tlustou prdelí.}
{262}{}{Jo, jasnì. Jsi teï otrokáø? Tak co chce? No moc to nejde - ne tak jak by mìlo.}
{263}{}{Chce to zkontrolovat.}
{264}{}{Dobrá, chce mít jistotu.}
{265}{}{No nic.}

# 8. Failed 1st speech roll for entrance (From 7)
{270}{}{Jistì, e jo. Nikdy jsem tì tu pøedtím nevidìl. Take vypadni.}
{271}{}{Nech mì jít dovnitø, ne ti jednu vrazím!}
{272}{}{Podívej, mìl jsem jít do mìsta, abych zkontroloval jeho materiál.}
{273}{}{Oukej.}

# 9. Whatever, go in (From 7, 8)
{280}{}{Cokoliv, otrokáøi. Tak jdi dovnitø. Myslí si, e s tím zboím snad zdrhneme? Co si ten blbec vùbec chce?}
{281}{}{Já na to seru. Tak dìlej. Myslí si, e snad s tím zboím zdrhneme? Co do prdele ten blbec zase chce?}
{282}{}{Sbohem.}

# 10. Don't care. (From 8)
{290}{}{Oukej, kurva. Jako kdybys vìdìl, co s tím budem dìlat.}
{291}{}{Grrrr.}
{292}{}{Díky.}

# 11. Threaten, failed (From 8)
{300}{}{Vypadni chlapèe, ne mì nasereš.}
{301}{}{Vypadni, dìvko. Metzger by nemìl posílat enskı, tak u vystøel.}
{302}{}{Dìvka? Ukáu ti, co ta dìvka umí.}
{303}{}{Jdi do prdele.}
{304}{}{[Odejít]}

# 12. Door = Never (From WTG)
{310}{}{Vypadni.}

# 13. Me Name (From 6)
{320}{}{Je to krásnı. Já jsem Tyler. Já jdu, sbohem.}
{321}{}{Ur.}
{322}{}{Uh...}

# 14. Dumb (From 6, 18)
{330}{}{Vypadni frajere.}
{331}{}{Sakryš!}
{332}{}{Kuuva!}

# 15. Enter, no. (From 8, 16)
{340}{}{Nemyslím si. Teï vypadni.}
{341}{}{Oukej.}
{342}{}{Ale!}
{343}{}{Dobøe.}

# 16. Metzger Not Known, Search Church (From 6)
{350}{}{Mnoo. Kdo tì poslal?}
{351}{}{Joo, to u si øíkal, kdo tì poslal?}
{352}{}{Kdo myslíš, e jsi blbèe? Teï pøestaò kecat a pus mì dál.}
{353}{}{Rùovı panter.}
{354}{}{Oukej, toho budeš litovat.}

# 17. Pink panther (From 16)
{360}{}{Coe? Vypadni!}
{361}{}{Ale...}
{362}{}{Dobøe.}

# 18. Find (From WTG)
{370}{}{Co zase zatracenì šéf chce, do prdele? Další zkurvená inspekce?}
{371}{}{Ano?}
{372}{}{Co teï?}
{373}{}{Jak to jde?}
{374}{}{Sorry, u jdu.}
{375}{}{OK.}
{376}{}{A co?}

# 19. Charisma Good (From 18)
{380}{}{To je fakt skvìlı! Skoro jsem zapomnìl -- jeden mùj kamarád vyhrál v hernì velkı prachy a rád by se podìlil o svoje bohatství, jestli mi rozumíš.}
{381}{}{Pìknì nudnı. Nenávidím stráit -- ale, no, není to zas tak hroznı. Skoro jsem zapomnìl -- jeden mùj kamarád vyhrál v hernì velkı prachy a rád by se podìlil o svoje bohatství, jestli mi rozumíš.}
{382}{}{Velkı plány, a potom?}
{383}{}{Zní to jako sranda.}

# 20. (From 18)
{390}{}{Jooo, poøádá dneska veèer party, mohlo by to bejt dobrı.}
{391}{}{Jooo, poøádá dneska veèer party, mohlo by to bejt dobrı. Pozval bych tì, ale je to jenom pro jeho nejbliší pøátele.}
{392}{}{Dej si za mì pár piv.}
{393}{}{Rozumím, díky. Uij si to.}
{394}{}{Uvidíme se.}

# 21. Have fun. (From 20)
{400}{}{Radši tomu fakt vìø! Zlijeme se do nìmoty!}
{401}{}{Sbohem.}

# 22. Failed, how are you (From 18)
{410}{}{Co se do prdele staráš. Vypadni.}
{411}{}{Jasnì, e tak.}
{412}{}{Snaíš se mì nasrat?}
{413}{}{Není špatná.}
{414}{}{Jsem unavenej.}
{415}{}{Oukej.}
{416}{}{Vypadni.}
{417}{}{Bejvalo líp.}
{418}{}{Oh.}

# 23. CF: Weakness is still set (From WTG)
{430}{}{Nemùu se doèkat veèírku. Doufám, e tam bude mít zase nìjakı dìvky.}
{431}{}{Mùj šéf ví, jak rozjet veèírek.}
{432}{}{U je èas.}
{433}{}{Veèírek! Ké bych tam byl.}

# 24. Gang War = Fight (From WTG)
{440}{}{Hej, co se dìje? U je èas na veèírek.}
{441}{}{Co je?}
{442}{}{Mám nìjaké informace, kterı by tì mohly zajímat.}
{443}{}{Nic.}
{444}{}{Ehm.}
{445}{}{Urseco?}

# 25. Dumb, Gang War = Fight (From 24)
{450}{}{Co se to s tebou dneska dìje? Pøestaò s tìma drogama.}
{451}{}{Drogy jsou pro tebe špatnı, chlapèe.}
{452}{}{Drogy jsou pro tebe špatnı, holèièko.}
{453}{}{[Reptat]}

# 26. Information (From 24)
{460}{}{Oh, jooo? Co je to?}
{461}{}{Za to budeš platit.}
{462}{}{Lara plánuje to místo dneska veèer napadnout.}
{463}{}{Poèkej chvíli.}

# 27. Float reward (From WTG)
{470}{}{Tvoje vejplata. Tady máš prachy. U jsem to chtìl s nimi skonèit.}

# 28. It'll cost you (From 26)
{480}{}{Jee, jdi do prdele. Záleí na tom, o co jde. Øekni, potom se rozhodnu, jestli ti za to zaplatím.}
{481}{}{Lara plánuje, e to tady veèer pøepadne.}
{482}{}{Ne, promiò.}

# 29. Lara's plan (From 26, 28)
{490}{}{Skuteènì? Ta dìvka má ještì nìjakı prachy, po tom všem? Dobrá, bude to $100.}
{491}{}{Díky.}

# 30. Plan 2 (From 29)
{500}{}{Ne tak rychle. Poèkáme a do konce.
 Tøeba mi leš. Nejdøív se ujistím a potom zaplatím.}
{501}{}{Ale já jsem milovník, ne bojovník.}
{502}{}{To zní dobøe.}

# 31. Lover (From 30)
{510}{}{Podívej, nevím kdo si. Nedám ti ani dolar, dokud se neukáou. Budeme bojovat, ale radìji, a se ukáou.}
{511}{}{Oukej.}

# 32. CF: Can go through door (From WTG)
{600}{}{Tak, ty jsi ten novej šéfùv poskok?}
{601}{}{Co chceš?}
{602}{}{Co je s Metzgerem? U nám nevìøí?}
{603}{}{U si to zkontroloval?}
{604}{}{Øíkal jsem ti, e Metzger nikam svojí prdel nevytáhne.}
{605}{}{Tak to dokonèíš, nebo co?}
{606}{}{Jsem si jist, e tì Metzger na nìco potøebuje. Proè se nepøesvìdèíš sám?}
{607}{}{Co je, do prdelele, s Metzgerem? My ho nehlídáme...}
{608}{}{Ještì jsi tady? Máš snad nìco, co bys prásknul Metzgerovi?}
{609}{}{Take ty jsi ta šéfovo nová koèièka?}

# 12. Additional Never Floats
{700}{}{Nemám náladu.}
{701}{}{Teï ne.}
{702}{}{Nemám èas.}

# New Node 33
{710}{}{Ta chytrá prdelka se vrátila! Opravdu sem chceš jít? Proè? Není tady nic, co by tì mohlo zajímat.}
{711}{}{Tak co kurva chceš?}
{712}{}{Vidíš tu znaèku na mojí hlavì? Pus mì tam. Teï!}
{713}{}{Jsem jeho nová dìvka, tak proto! Pokud mì tam teï nepustíš, ujišuju tì, e se objevíš na jeho seznamu nahoøe.}
{714}{}{Podívej. Metzger mì zabije, jestli to nezkontroluju všechno co nejdøív. Víš jakej je.}
{715}{}{Jestli to šéf chce zkontrolovat, tak to musím udìlat. Na nic se neptám.}
{716}{}{Nevadí.}
{717}{}{Shaka?}
