#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš otroka.}
{101}{}{Vidíš Vica.}

{150}{}{Tenhle otrok vypadá, e je pod pøísnou kontrolou.}
{151}{}{Tohle je Vic.}
{152}{}{[MLUVIT]}

# Node 1
{153}{}{Øekni mu, e tohle ne... poèkat. Kdo jsi? Ty nejsi otrokáø.
 Co tady dìláš?}
{154}{}{Jmenuji se }
{155}{}{. Chci ti pomoct dostat se ven.}
{156}{}{Jsem }
{157}{}{, ale proè jsi zamèenı v téhle místnosti?}
{158}{}{Mùeš mi øíct, kde je Vault 13?}
{159}{}{Jsem }
{160}{}{. Hned se vrátím.}
{161}{}{Dubba iba }
{162}{}{.}

# Node 2
{163}{}{Metzger je na mì poøád naštvanı, i kdy jsme spravili to jeho podìlanı rádio.
 Vyhrouje, e mì prodá! Jestli mì odsud dokáeš dostat, udìlám co budeš chtít.}
{164}{}{OK, udìlám to.}
{165}{}{Je mi líto, ale to nemùu.}
{166}{}{Hou.}

# Node 3
{167}{}{Nazdar, zase ty? Tohle blbı rádio se samo neopraví. Jak si myslí, e to spravím?}
{168}{}{Kde mùu sehnat náhradní díly?}
{169}{}{Moná to mùu opravit.}
{170}{}{Mám u sebe tohle rádio. Mùeš ho pouít?}
{171}{}{Uvidím co s tím dokáu udìlat.}
{172}{}{Spa pa?}

# Node 4
{173}{}{Vím e to zvládnu. Potøebuju jenom nìjaké náhradní díly. V mojí chatì v Klamathu
 je rádio, kterı má pøesnì to, co potøebuju. Znáš to u Duntona?
 Moje chata je... vlastnì, byla na vıchod odtamtud.}
{174}{}{Myslíš tohle rádio?}
{175}{}{Pùjdu se po pot podívat.}
{176}{}{Hmmm...  vrátím se.}

# Node 4b
{206}{}{Je to pøímo tady. (ukazuje na mapu)}

# Node 5
{177}{}{To je perfektní! Hned to rádio opravím.}
{178}{}{Dobøe, promluvím si s Metzgerem.}

# Node 6
{179}{}{Díky.}
{180}{}{Zatím.}

# Node 7
{181}{}{Coe? Je mi líto, ale nerozumím.}
{182}{}{Hurm.}

# Node 8
{183}{}{Dìkuji mockrát! Jsem navìky tvım dluníkem. Jak ti to mohu oplatit?}
{184}{}{Øekni mi, kde je Vault 13.}
{186}{}{Pojï se mnou, pomoc se hodí vdycky.}
{187}{}{To nic nebylo. Nashle.}
{188}{}{Bombón?}

# Node 9
{189}{}{Vault 13? Na vıchod odtud je Vault City. Nìkdy tam obchoduju.}
{190}{}{Chceš tam jít se mnou?}
{191}{}{Díky. Èau.}

# Node 10
{192}{}{S radostí, rád se pøidám! Tenhle staroch je vdycky pro nìjakı dobrodruství.
 Tím jsem si jistı! A taky umím opravit hodnì vìcí, a si Metzger øíká co chce.}
{193}{}{Vıbornì, mùeme vyrazit.}
{194}{}{Vítej na palubì.}
{195}{}{Kdy myslíš.}
{196}{}{Vic je mùj nejlepèí kámoš.}

# Node 11
{197}{}{Chceš se pøidat pøi hledání?}
{198}{}{Super! Díky.}

# Node 12 OLD IF IN PARTY. REMOVED NODE. Lines 199, 200, 202 (Don't know where 201 is)

# Node 13
{203}{}{Vault City je vıchodnì odsud. Ukáu ti to na tvojí mapì.}
{204}{}{Díky.}

# Node 14
{220}{}{Sakra. To je skoro ono, ale potøebuju rádio z mojí chaty v Klamathu. Vím e má èásti, které potøebuju.}

# used in node 12 REMOVED 230 that was here. Node 12, removed. was What else do you need to know?

# Node 15
{300}{}{Jasnì, asi ti mùu pomoct, ale nejdøív mì odsud musíš dostat.}
{301}{}{Øekl jsem ti. Jestli mì odsud dostaneš, pomùu ti s èím budeš chtít.}
{302}{}{Jak to udìláme?}
{303}{}{Tak to máš smùlu.}
{304}{}{Tak dobøe, podívám se co mùu dìlat.}

# Node 2b
{350}{}{Myslíš e mi odsud mùeš pomoct?}
{351}{}{Metzger mì poøád nechce nechat jít.}
{352}{}{U to moc dlouho nevydrím.}
{353}{}{Udìlám pro tebe cokoliv, jestli mi pomùeš.}
{354}{}{Všechny vıdaje, které budeš mít, ti splatím!}

# 3b
{400}{}{Ještì jsi na té chatì nebyl, co? Já to rádio fakt potøebuju,
 Metzger je èím dál tím víc netrpìlivı.}

# water flask question, Question used in Node 9 and Node 1010
{450}{}{Jak jsi pøišel k téhle lahvi na vodu?}
{451}{}{Na mojí lahvi na vodu byla velká lutá 13. Pamatuješ se, jak si k ní pøišel?}

# Additions to Node 11
{500}{}{Jo, jo. To si pamatuju. Tu jsem koupil od Eda. To je obchodník s dobytkem ve Vault City.}
{501}{}{Lahev na vodu? Jo, poèkej. Jasnì, mìl jsem jich mraky. A dobøe jsem je prodal. Mìl jsem je od Eda. To je obchodník s dobytkem ve Vault City.}
{502}{}{Vault City?}

# Node 1000, if said Boss many times.
{550}{}{A pøestaò mi øíkat šéfe!}

# Node 16
{600}{}{Jistì, veliteli!}
{601}{}{Myslím to vánì. PØESTAÒ!}
{602}{}{Mám pocit, e tohle musí staèit.}

# Node 17
{650}{}{Máš to.}
{651}{}{Uggg!}

{700}{}{Buï mùj pøítel.}

# Node 1b - Added a line to node 1 for Vic
{710}{}{Øekni mu, e bez náhradních dílù to nespravím. Nevím... poèkat.
 Kdo jsi? Zase nìjakı nováèek? Neposlal tì, abys mì zase zmáèknul, e ne?
 Tím se nic nezmìní. Tady to opravit nemùu.}

# 20. Here to get you out. (From 1)
{750}{}{Joo?! Dostaneš mì z tıhle kaše? Udìlám všechno, jestli mì z tohohle vytáhneš. Jedinı problém je, e mne sem Metzger zamkl, dokud mu nespravím tohle rádio a já potøebuju náhradní díly.}
{753}{}{Kde se dá sehnat co potøebuješ?}
{754}{}{Uvidím co se dá dìlat.}

# 21. Why in this room? (From 1)
{760}{}{To by byla dlouhá story. Kadopádnì Metzger mì tu drí dokud mu nespravím to
 blbı rádio. Krystal vyhoøel a já nemám náhradní. Jak si asi myslí, e to opravím?}
{761}{}{Dobøe, pomùu ti dostat se ven.}
{764}{}{Tak to nevím. Uij si to.}

# 22. How do we do that?
{800}{}{Tohle rádio musím opravit. Kdy mi pomùeš to udìlat, moná se s ním domluvíme.}
{801}{}{Kde seenu náhradní díly?}
{803}{}{Tak to pochybuju. Hodnì štìstí.}

# 23. In Mom's, never joined party. (From WTG)
{810}{}{Proè jsi zabil Mámu... Moná jsi mìl svoje dùvody... Sorry, šéfe. Já tu nejsem od toho, abych se ptal. Tohle je hodnì blbı mìsto. Myslím e udìlala nìco hodnì škaredıho.}
{811}{}{Hej, šéfe. Dík es mì dostal ven od Metzgera. Nepotøebuješ nìco? Máma byla hodná a dávala mi jídlo kdy jsi byl pryè. Já jí tu pomáhám...}
{812}{}{Zatím.}
{813}{}{Oooh.}
{814}{}{Èaaauua.}

# Additions to Node 9
{823}{}{Kde je tvùj pøítel Ed?}

# Additions to Node 10
{830}{}{To bych mohl, ale ty prostì nevypadáš dobøe. Byl bych jenom na obtí. Teï kdy je po Mámì, myslím e prostì pùjdu pryè. Zatím nevím kam... moná se ještì nìkdy potkáme. Díky za všechno, co jsi pro mnì udìlal.}
{831}{}{To bych mohl, ale ty prostì nevypadáš dobøe. Vypadá to, e sotva zvládneš postarat se o sebe. Já bych byl jenom na obtí. Já prostì zùstanu tady, Mámino vaøení mi pøipomíná moji bıvalou...}
{832}{}{Mohl bych, opravdu. Pro tebe bych udìlal skoro cokoliv. Ale teï nevypadáš ve formì, e bys mohl nìkoho vést. Já bych byl jenom pøítì. Já teï pùjdu k Mámì... dokud se vìci trochu neusadí. Její domácí jídlo mi u dlouho chybí.}
{833}{}{Sorry, šéfe. Vypadá to, e u jsi ve velkı partì. Teï, kdy je Máma pryè, tak myslím, e prostì odejdu. Nevím kam... moná se ještì nìkdy potkáme. Díky za všechno, co jsi pro mì udìlal.}
{834}{}{Vypadá to, e u je vás dost, šéfe. Poèkám tu na tebe, dokud s vìcma trochu nepohneš. Mámino vaøení mi pøipomíná moji bıvalou... jenom si nejsem jistı, jestli je to dobøe nebo špatnì.}
{835}{}{To bych hroznì rád, šéfe. Ale vypadá to, e u nemáš ádnı místo. Já prostì pùjdu k Mámì. U jsem tam dlouho nebyl. Jestli pro mì najdeš místeèko, tak se tam pro mì zastav.}

# Additions to Node 11
{840}{}{Ed je ve Vault City. Obchoduje tam s dobytkem. Byl jedním z mnoha mıch dodavatelù. Vault City odtud není daleko.}

# Additions to Node 13
{845}{}{Øíkal jsem ti u e je to tady. (Vic ukazuje místo na tvém PIP Boyi 2000.)}

{900}{}{Dozvìdìl ses, e Vic je taky obchodník.}

# 1000 in party dialog
{1000}{}{Na nìco se tì musím zeptat.}

# 1001 After healing
{1100}{}{Jsem úplnì v pohodì, šéfe. Ještì nìco?}
{1200}{}{Skoro úplnì v pohodì, šéfe.}
{1300}{}{Ale jo, jde to, šéfe, ale u mi bylo líp.}
{1400}{}{No, šéfe, ne e by to bylo super. Ale stejnì se budu snait.}

# 1002 I need you to wait here until I come back
{1500}{}{Cokoliv øekneš, šéfe.}
{1501}{}{Tady? Zrovna tady? Okej, ty jsi tady šéf.}
{1502}{}{Dobøe. Poèkám tu, dokud se pro mnì nevrátíš, šéfe. Vrátíš se, e jo?}
{1503}{}{Jak dlouho budeš chtít. Nikam nepùjdu.}
{1504}{}{Jasnì, šéfe.}

# 1003 Put your weapon away.
{1600}{}{Kdy to øíkáš.}
{1601}{}{Jasnì šéfe.}
{1602}{}{Bezva nápad, šéfe.}
{1603}{}{Jasnì, šéfe. Ještì nìco?}
{1604}{}{U je pryè, šéfe.}
{1605}{}{Bez problémù, šéfe.}
{1606}{}{Hotovo, šéfe.}

# 1004 Stay close to me
{1700}{}{Jasnì, šéfe.}
{1701}{}{U jsem blízko, šéfe.}
{1702}{}{Ty to víš nejlíp, šéfe.}
{1703}{}{Jsem pøímo za tebou, šéfe.}
{1704}{}{Jako lepidlo, šéfe.}
{1705}{}{Kdy to øíkáš, šéfe.}
{1706}{}{Oh. Oukej, šéfe.}

# 1005 Don't get too far away.
{1800}{}{Oukej, budu se dret dál, ale ne moc daleko, šéfe.}
{1801}{}{Oukej, nebudu, šéfe.}
{1802}{}{Budu se dret trošku dál, šéfe.}
{1803}{}{Jasnì, šéfe.}

# 1006 We should spread out a bit
{1900}{}{Jasnì šéfe. Budu se dret dál.}
{1901}{}{Cokoliv øekneš, šéfe.}
{1902}{}{Jasòaèka, šéfe.}
{1903}{}{Jdu dál, šéfe.}
{1904}{}{Trochu ustoupím, šéfe.}
{1905}{}{Rozptılíme se, šéfe.}
{1906}{}{Oukej, šéfe.}

# 1100a Rejoin: Crowded
{2000}{}{Uh, šéfe? Vypadá to, e je vás u moc. Ještì tu na tebe poèkám.}

# 1100b Rejoin: Additional NPC response, PC Charisma 1
{2100}{}{Vypadáš jako strašidlo, šéfe. Co se ti stalo? Vypadáš... no,
 pøíšernì. Myslím e tu radši ještì chvilku zùstanu...}

# 1100c Rejoin:
{2200}{}{tak to se vsaï, šéfe!}
{2201}{}{Sakra hned, šéfe.}
{2202}{}{Jasná páka, šéfe.}
{2203}{}{Vdy pøipraven, šéfe.}
{2204}{}{Vıbornì! Tak jdeme.}
{2205}{}{Vıbornì!}
{2206}{}{Jsi nejlepší, šéfe!}
{2207}{}{Nebudeš litovat. U ádné chyby!}
{2208}{}{Tentokrát budu opatrnı, nemusíš se bát!}
{2209}{}{Vìdìl jsem e mi to odpustíš... hm. Tak, uh, šéfe. Jakı je plán?}
{2210}{}{Pøece tì nenechám v reji, šéfe!}
{2211}{}{Jsi super, šéfe!}
{2212}{}{Vìdìl jsem e na to nejsem tak starı. To byli jenom podivíni! e jo, šéfe?}

# 1007 Vault 13 Flask?
{2300}{}{Od Eda. To je obchodník s dobytkem ve Vault City. U to tam znáš?
 Ukáu ti to na mapì.}

# 1008 Where's Ed again? Not Marked
{2305}{}{Vault City. Tady. Ukáu ti to na té tvojí pøepychové mapovací vìcièce.}

# 1009 Where's Ed again?
{2310}{}{Mìl by tady nìkde kolem bıt.}
{2311}{}{Vault City. Mrkni se do svojí mapovací vìcièky.}

# 1010 Other Questions
{2403}{}{Kde jsi získal tu láhev na vodu z Vault 13?}
{2404}{}{Ale, nic.}

# 1011 Other questions greeting (From 1000)
{2500}{}{Jasnì, šéfe.}
{2501}{}{Zeptej se na cokoliv, šéfe.}
{2502}{}{Kdy mùu, pomùu, šéfe.}
{2503}{}{Nejsem v prùseru, e ne, šéfe?}
{2504}{}{Udìlal jsem nìco špatnì, šéfe?}
{2505}{}{Samozøejmì.}

# 1012 Standard Greeting, (WTG) Moved From Node 1000
{2600}{}{A co teï, šéfe?}
{2601}{}{Jakı je plán, šéfe?}
{2602}{}{Snaím se, šéfe.}
{2603}{}{Co pro tebe mùu udìlat, šéfe?}
{2604}{}{Zmìna plánu, šéfe?}
{2605}{}{Jiná strategie, šéfe?}

# 1013 Crippled
{2700}{}{Šéfe, dostali mnì. Musíš mì dostat k doktorovi. Nevím, jestli tì mùu dál krıt.}
{2701}{}{Potøebuju doktora, šéfe. Jsem v hajzlu. Nevím jestli mùu bojovat dál.}
{2702}{}{Šéfe, jsem na tom dost blbì. Mìl by se na mì podívat Lenny.}

# 1014 Waiting
{2800}{}{Hej, šéfe. Chceš, abych se k tobì pøidal, e jo?}
{2801}{}{Hej, šéfe. Nevadí mi èekání. Jsem opravdu trpìlivı èlovìk.}
{2802}{}{Zase se setkáváme, šéfe? Budu se snait víc.}
{2803}{}{Bál jsem se jestli se vrátíš. Rád tì zase vidím, šéfe.}
{2804}{}{Zase sháníš spoleènost?}
{2805}{}{Pøipraven na cestu, šéfe.}
{2806}{}{Vìdìl jsem, e mì tu nenecháš.}
{2807}{}{Potøebuješ nìkoho na obranu?}
{2808}{}{Potøebuješ nìco spravit, e jo? Jsem tvùj èlovìk, šéfe!}
{2809}{}{Neboj se, šéfe. Se Sulikem nìjak vyjdeme, vánì.}
{2810}{}{Tak jdeme.}
{2811}{}{Zùstaò tady. Hned budu zpátky.}
{2812}{}{Já jdu.}

# 1017 Remove armor: Yes
{3100}{}{Coe? Uh... tak dobøe, šéfe. Kdy to øíkáš.}
{3101}{}{Mùu na sebe natáhnout nìco jinıho, šéfe? Mám trochu obavy.}
{3102}{}{Dobøe... ale nenecháš mnì tu... e ne, šéfe?}
{3103}{}{Ale... myslím... Tak jo, šéfe. U je to.}

# 1018 Best Weapon
{3200}{}{No, šéfe..., s menšíma zbranìma jsem fakt dobrej. Poradím si skoro s kadou puškou, brokovnicí a vìtšinou malıch a støedních pistolí. 'Mùu' pouívat i noe. Taky umím docela házet, ale moje muška není nejlepší na svìtì... vlastnì je pìknì blbá. Sorry, šéfe. Fakt se to pokusím zlepšit.}
{3201}{}{Jak jsem øíkal, šéfe, mám radši menší zbranì. Zvládnu skoro kakou pušku, brokovnici, a vìtšinu tìch malıch nebo støedních pistolí. Jestli budeme fakt v prùseru, mùu zkusit pouít nù nebo dokonce vrhací zbraò.}

# 1019 Other weapons he can use.
{3300}{}{Mùu pouívat noe a taky docela dobøe házím, ale... ale moje muška není nejlepší na svìtì. Vlastnì je pìknì blbá. Sorry, šéfe. Fakt se pokusím to zlepšit.}
{3301}{}{Jak jsem øíkal, šéfe. Noe a umím taky dobøe házet... jenom èasto nic netrefím.}

# 1020 Hostile
{3400}{}{A u toho mám a po krk!}
{3401}{}{Utrhnu ti tu tvoji podìlanou kebuli! Nikdo nebude ubliovat mojí rodinì!}

# 1101 Vic's being Pushed
{4000}{}{Sem?}
{4001}{}{Je to lepší, šéfe?}
{4002}{}{Co tøeba tady?}
{4003}{}{Jo, šéfe.}
{4004}{}{Coe?}
{4005}{}{Kam jdeme?}
{4006}{}{Odcházíme, šéfe?}
{4007}{}{U zvedám svùj zadek.}
{4008}{}{Sorry šéfe.}
{4009}{}{Lepší?}
{4010}{}{Ufffff.}
{4011}{}{A co tohle, šéfe?}
{4012}{}{Já budu stát tady.}
{4013}{}{Teï se jenom posunu sem.}

# 1102 BGF: Crippled
{4100}{}{Šéfe! Není mi zrovna fajn.}
{4101}{}{Potøebuju doktora.}
{4102}{}{A sakra. Tohle fakt bolí.}
{4103}{}{Au!}
{4104}{}{Jauuu.}
{4105}{}{Aaaa.}
{4106}{}{Medika?}
{4107}{}{Vydrím to... sotva.}

# 1103 Removed

# 1104 BGF: Random on Specific Map
{4200}{}{Nikdy se mi tu nelíbilo.}
{4201}{}{Proè je tu tak èisto?}
{4202}{}{Necítíš nìco, šéfe?}
{4203}{}{Víš, šéfe. Nemyslím, e se sem potom nìkdy vrátím. U tomu nemùu øíkat domov.}
{4204}{}{Urèitì je to tu hnusnìjší ne to pamatuju.}
{4205}{}{Nezùstaneme tu dlouho, e ne šéfe?}
{4206}{}{Tohle místo se nikdy nezmìní.}
{4207}{}{Šéfe, Tohle místo mi nebude chybìt.}
{4208}{}{Dík, es mì dostal ven, šéfe.}
{4209}{}{Fakt ti nìco dluím, šéfe.}
{4210}{}{Joo, tohle se urèitì zmìnilo.}
{4211}{}{Tady jsem nebyl roky.}
{4212}{}{Sem pùjdu do dùchodu.}
{4213}{}{Tady bych si mohl dokonce otevøít dílnu.}

# 1105 BGF: for specific area on a map
{4300}{}{Ah, odpoèinek pro bolavé oèi. Tohle je... bylo moje místeèko, ale to u myslím víš. e jo, šéfe?}

# 1106 Removed

# 1107 BGF: with Specific NPC
{4400}{}{Suliku, nedívej se na mnì takhle.}
{4401}{}{Šéfe, Sulik na mnì u zase divnì èumí.}
{4402}{}{Hezkı pudlík.}

# 1108. BGF: Level Up, Not to be Placed in MSG file

# 1109. BGF: Waiting
{4500}{}{La de da...}
{4501}{}{Ho hum.}
{4502}{}{Èekám na šéfa...}
{4503}{}{Já èekám na šéfa.}
{4504}{}{Prostì èekám.}
{4505}{}{Šéf mì tu urèitì nenechá...}
{4506}{}{Klepy klep... kdo je tam... poèkat. Jak to jenom bylo...}
{4507}{}{Poøád èekám.}
{4508}{}{Co to tu smrdí?}
{4509}{}{Nedá se tu v okolí nìco opravit?}
{4510}{}{Tady jsem... èekám na šéfa.}
{4511}{}{Starı mu jako já a mrhá svım talentem, jenom tu tak stojí.}
{4512}{}{Mít tak kousek vıkaèky... to u je dávno.}
{4513}{}{Mìl bych nechat toho obchodování se staroitnostmi... jenom samé potíe.}
{4514}{}{Proè je èekání tak únavné...}

# 1110. PC used Healing on PC
{4600}{}{Uh, díky, šéfe.}
{4601}{}{Díky.}
{4602}{}{Víš urèitì co dìláš?}
{4603}{}{Nemohli bychom si radši jenom odpoèinout?}
{4604}{}{Nepostavíme tábor?}
{4605}{}{To vypadám opravdu tak blbì?}

# 1111. PC used Drugs on NPC
{4700}{}{Jenom trošku, šéfe.}
{4701}{}{Kdy na tom trváš, šéfe.}
{4702}{}{Šéfe, nevybouchne mi hlava, e ne?}
{4703}{}{Šéfe, zaèíná se mi to líbit.}
{4704}{}{Cítím se tak nìjak srandovnì, šéfe.}
{4705}{}{Opravdu toho máš tolik, e se mùeš rozdìlit?}
{4706}{}{Jasnì, šéfe. Nìco si vezmu.}
{4707}{}{Díky, šéfe.}
{4708}{}{Není to špatnı.}
