#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
# 0. Look
{100}{}{Vidíš otrokáøe.}

{150}{}{Vypadá to, že dává pozor na dveøe vedle sebe.}

# 1. Self Initiated Floats
{200}{}{Hej! Ruce pryè.}
{201}{}{To je ono!}

# 2. Open Door 1 - Self Initiated Floats
{210}{}{Problémy?}
{211}{}{Procvièuješ se?}
{212}{}{Hmmm.}

# 3. Open Door 2 - Self Initiated Floats (From 9, 16)
{220}{}{A je to tady.}

# 4. Starting Node (From Where to go)
{230}{}{Hej, tak jak to jde?}
{231}{}{Hej, takže ses pøidal, co? Supr. Doufám že se ještì nìkdy potkáme.}
{232}{}{Tak, o èem si chceš popovídat?}
{233}{}{Tak, kdo je tam?}
{234}{}{O Vicovi...}
{235}{}{Dobøe, dík.}
{236}{}{Už musím.}
{237}{}{Práce?}
{238}{}{Meko veek?}
{239}{}{Ugruk.}
{240}{}{Ruru!}

# 5. Who's that? & About Vic... (From 4)
{250}{}{Jmenuje se Vic -- nìjakej obchodník, co rozbil nìco mému šéfovi, nebo tak nìco. Nejsem si moc jistej.}
{251}{}{Jmenuje se Vic -- nìjakej obchodník, co rozbil nìco šéfovi, nebo tak nìco. Nejsem si moc jistej.}
{252}{}{Tohle? Jo, nìjakej obchodník. Myslím, že nìco rozbil, ale jistej si nejsem. Proè? Ty ho znáš?}
{253}{}{Tohle? Jo, nìjakej obchodník. Myslím, že nìco rozbil, ale jistej si nejsem. Proè? Ty ho znáš?}
{254}{}{Jo?}
{255}{}{Proè ho hlídáš?}
{256}{}{Kdo je tvùj šéf?}
{257}{}{Mùžu se na nìj podívat?}
{258}{}{No, celkem dobøe umím opravovat vìci. Snad mohu nìjak pomoct?}
{259}{}{No, vyznám se ve spoustì vìcí, možná mùžu nìjak pomoct?}
{260}{}{Je zamèeno. Mùžeš to otevøít?}
{261}{}{Dík.}

# 6. Guard Will let PC see Vic. (From 18)
{275}{}{Dík za prachy. Nechám tì s ním promluvit. Žádný blbosti. Nesmí odejít z té místnosti bez Metzgerova souhlasu.}
{276}{}{Takže, nechám tì s ním promluvit, jasný? Žádný blbosti. Nesmí odejít z té místnosti bez Metzgerova souhlasu.}
{277}{}{Oukej.}

# 7. Why guarding Vic (From 5)
{285}{}{Aby ho nikdo neotravoval, když dìlá na nìèem pro šéfa, ale hlavnì aby nezdrhnul.}
{286}{}{Abych si byl jistej, že nezdrhne, myslím. Nìjak to rádio spravil.}
{287}{}{Kdo je tvùj šéf?}
{288}{}{Mùžu se na nìj podívat?}
{289}{}{Mùžu se na nìj podívat?}
{290}{}{Oukej, dík.}

# 8. Can I see him - Slaver (From 7)
{295}{}{No, jasnì. Nemyslel jsem že mùžeš, ale když jsi teï ten otrokáø a vùbec.}
{296}{}{No, jasnì. Myslím že jo. Nemá nic na práci a nikam nejde, takže se nic nemùže stát.}
{297}{}{Tak, mùžeš teda otevøít ty dveøe?}
{298}{}{Oukej, dík.}

# 9. Unlock door, Okay to see (From 5, 8)
{305}{}{Samo. Nevìdìl jsem, že s ním chceš mluvit hned teï. Jsem si myslel, že jsi jenom zvìdavej nebo tak nìco.}
{306}{}{Díky.}

# 10. Who's your boss? (From 5, 7, 18)
{310}{}{He? Máš ve zvyku poøád se motat tam, kde to neznáš? Tohle je cech otrokáøù.}
{311}{}{Oh, to znamená, že tvùj šéf se jmenuje... }
{312}{}{Co? Tam že jsem? Já myslel, že jsem v Kansasu.}
{313}{}{Oukej, dík.}

# 11. Kansas (From 10)
{320}{}{Kde? Ne, o tom jsem nikdy neslyšel. Tohle je Den. Tím místem si nejsem moc jistý, ale ven se moc nedostanu. Sorry.}
{321}{}{Kreténe.}
{322}{}{Uh, oukej. Díky.}

# 12. Don't know Boss? (From 10)
{330}{}{Sakra, chlape. Metzger je mistr otrokáø. On to tady vede.}
{331}{}{Sakra, dámo. Tohle je poslední místo, kde by dáma jako vy chtìla být. Metzger je mistr otrokáø.}
{332}{}{Oh, kde je jeho kanceláø?}
{333}{}{Tak, zatím.}

# 13. Where's his office? (From 12)
{340}{}{Támhle ty dveøe vzadu.}
{341}{}{Díky.}

# 14. Dumb Exit (From 4, 15, 20)
{350}{}{Sorry, nerozumím.}
{351}{}{Hmph.}

# 15. Dumb Vic ? (From 4)
{360}{}{Sorry, Vic nemá povolený návštìvy.}
{361}{}{Jasnì, to je Vic.}
{362}{}{Seve?}
{363}{}{Fakt?}
{364}{}{Gaw.}

# 16. Dumb Can See Vic (From 15)
{370}{}{Jasnì, mùžeš ho navštívit.}
{371}{}{Jasnì, mùžeš ho navštívit. Odemknu ti.}
{372}{}{Tank.}

# 17. Repair or Science skills (From 5)
{380}{}{Opravdu? Šéf to urèitì ocení. Ale on zùstane tady. Nechceme aby znovu zdrhnul.}
{381}{}{Díky.}

# 18. Can I see Vic? (From 5, 7)
{390}{}{Ne, sorry. Má plný ruce práce. Dìlá nìco pro šéfa.}
{391}{}{Sorry, ale to nejde. Pøíkazy pøímo od šéfa.}
{392}{}{No, máš 'moje' peníze?}
{393}{}{Jenom se ho na pár vìcí zeptám.}
{394}{}{Ale, no tak. Jenom si s ním rychle pokecám.}
{395}{}{Ano. Tady.}
{396}{}{Ne. Ještì pøijdu zpátky.}
{397}{}{Kdo je tvùj šéf?}
{398}{}{Ale nic. Èau.}

# 19. See Vic is Never (From )
{410}{}{Pøestaò mì otravovat. Jdi za Metzgerem. On je tu šéf.}
{411}{}{Nech mì být! Poøád máš nìjaký problémy!}
{412}{}{Øekl jsem jdi za Metzgerem!}
{413}{}{Oukej, dobøe! Tak si s ním promluv! Ale z té místnosti nevystrèí ani nos. Jasný? A teï odpal!}
{414}{}{Oukej.}
{415}{}{Díky!}

# 20. Wuk? (From 4)
{430}{}{Jasnì, promluv si s Metzgerem. Urèitì bude mít nìjakou práci. Myslím že øíkal, že potøebuje dalšího chlapa.}
{431}{}{Jasnì, promluv si s Metzgerem. Urèitì bude mít nìjakou práci. Øíkal že potøebuje dalšího chlapa... a ty to urèitì zvládneš.}
{432}{}{Promluv si s Metzgerem.}
{433}{}{Ruru?}
{434}{}{Uh?}
{435}{}{Oh.}

# 21. Hostile (From Where to go)
{450}{}{Chlapi, na nìj!}
{451}{}{Chlapi, na ní!}

# 22. Just a few questions. (From 18)
{460}{}{Má plno práce.}
{461}{}{Prosím, nehne se z té místnosti. Slibuji.}
{462}{}{Nevymyslíme nìco -- možná finance?}
{463}{}{Oukej, zatím.}

# 23. Bribe 1 (From 22)
{470}{}{Tak, no... já nevím. Myslím že se nic nestane, když si s ním jenom popovídáš. Dej tøi kila a pustím tì dovnitø.}
{471}{}{Jsi magor. To je moc!}
{472}{}{Jdi do hajzlu, kámo!}
{473}{}{Jasnì.}
{474}{}{Sorry, to si nemùžu dovolit.}

# 24. Fine. (From 22)
{480}{}{Fajn, mùžeme to zkusit.}
{481}{}{Oukej.}
{482}{}{Fajn.}

# 25. No. (From 23)
{490}{}{Ne, sorry.}
{491}{}{Øekl jsem ne. A teï vypadni. Musíš si promluvit s Metzgerem.}
{492}{}{Oukej.}

# 26. Vic Free (From Where to go)
{500}{}{Blbý že ses k nám nepøidal.}
{501}{}{Mìl by ses pøidat k cechu.}
{502}{}{Tak nìjak hlídám.}
{503}{}{Doufám že Vic dìlá pro tebe.}
{504}{}{Vic by mìl pro tebe radši tvrdì makat.}
{505}{}{Možná se ještì uvidíme na honu.}
{506}{}{Jak to jde?}
{507}{}{Zdar, zase.}
