#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
# 0. Look
{100}{}{Vidíš nástìnku.}

{150}{}{Vypadá to, že na nástìnce je nìkolik zpráv.}

# 1. Main Page
{200}{}{Nástìnka: Provozovaná Rebeèiným Casino Barem, kde seženete nejlepší drinky v okolí. }
{201}{}{Nástìnka: Provozovaná Rebeèiným Casino Barem...}
{202}{}{[Nìkdo tu na okraj téhle zprávy nìco naèmáral.]}
{203}{}{[Všiml sis, že tady byla èást zprávy odtržena.]}
{204}{}{Otrokáøský cech}
{205}{}{Bary & Herny}
{206}{}{Jídlo}
{207}{}{Obchody}

# 2. Slaver's Guild
{225}{}{Otrokáøský cech je nejlepší a jediný dodavatel otrokù v divoèinì.}

# 3. Slaver's - Continue
{250}{}{Kvùli zamìstnání, prodeji nebo koupi otrokù, navštivte mistra otrokáøe Metzgera.}

# 4. Slaver's - Directions
{275}{}{Otrokáøský cech je na východní stranì mìsta, za Rebeèiným casinem a Frankieho barem.}

# 5. Slaver's - Not selling
{300}{}{Kvùli zvýšené poptávce nyní otroky široké veøejnosti neprodáváme.}

# 6. Bars and Gambling
{325}{}{[Jsou tady vypsaná dvì místa.]}

# 7. Becky's Casino Bar
{350}{}{V Rebeèinì Casino Baru si mùžete zahrát a vychutnat si vynikající drink.}

# 8. Becky's Directions.
{375}{}{Sídlíme východnì odtud. Jsme první budova po levé stranì, když vejdete do mìsta. Urèitì nás pøijïte navštívit!}

# 9. Frankie's Message
{400}{}{Rebeka je kurfa kerá øedí chlast! Je to potvodnice a lháøka! (Písmo je skoro neèitelné.)}
{401}{}{(Zpráva která byla tady, je peèlivì odtržená.)}

# 10. Dumb Board
{425}{}{Slova slova... u... slova... Baru... slova... v Denu.}
{426}{}{Je to tak hroznej zmatek, že tì z toho zaèala bolet hlava.}

# 11. Frankie's
{450}{}{Frankie provozuje bar, hospodu, a 'zábavní' podnik ve východní èásti mìsta.}

# 12. Dining
{475}{}{Mámina restaurace je jediná v Denu. Je ve východní èásti mìsta, kousek jižnì od Otrokáøského cechu.}

# 13. Becky Dead
{500}{}{(Vypadá to, že se to nìkdo snažil zapálit. Nemùžeš rozluštit žádné zprávy.)}

# 14. Shops
{525}{}{[Jsou tu tøi zprávy.]}

# 15. Tubby's
{550}{}{Tubby prodává všechno možné, ale hlavnì drogistické zboží a støelivo.}

# 16. Tubby's Directions
{575}{}{Tubby sídlí na západ od téhle nástìnky. Je to první budova po pravé stranì, když vejdeš do mìsta.}

# 17. Flick
{600}{}{Flick prodává rùzné pøedmìty ve své 'kanceláøi' v obytné budovì na jih odsud a pøímo pod Rebeèiným Casino Barem.}

# 18. Smitty
{625}{}{Smitty je místní mechanik. Obèas má pár vìcí na prodej.}

# 19. Smitty Directions
{650}{}{Smitty sídlí na smetišti v jihozápadní èásti mìsta.}

# MENU OPTIONS
{1000}{}{Pokraèovat}
{1010}{}{Smìry:}
{1020}{}{Východ}
{1030}{}{Flick}
{1040}{}{Frankieho Bar}
{1050}{}{Rebeèin Casino Bar}
{1060}{}{Zpìt na hlavní stranu}
{1070}{}{Smitty}
{1080}{}{Speciální poznámka:}
{1090}{}{Tubbyho obchod}
