#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
#############################################################
#  Message File: diDiary.msg                                #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the dialog for a     #
#           new character from which is used by the         #
#           design tool. It will be updated using the       #
#           the tool. This is just a tool file, and not     #
#           meant to be used in the game.                   #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#                                                           #
#  Created: January 13,1998                                 #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the item when     #
#  glanced and and examined.                                #
#############################################################

{100}{}{Vidíš starý diáø.}
{101}{}{Diáø je moc rozpadlý na listování. Informace byly pøehrány
 do Pip-Boye.}
{102}{}{Diáø je uložen v Pip-Boyi.}
