#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Mu v tìké zbroji.}
{101}{}{Arthur, syn Uthera Pendragona.}
{102}{}{Má sklopené hledí.}
{103}{}{Buïte zdrávi, pocestní. Jmenuji se  Arthur, syn Uthera Pendragona, z Bratrstva oceli. Jsme na vıpravì za svatım granátem z Antiochu. Nevidìl jsi ho nìkde?}
{104}{}{Svatı co a koho?}
{105}{}{Odpovìï hráèe}
{106}{}{Unga.}
{107}{}{Nemáme èas mluvit. Jsme na vıpravì.}
{108}{}{Hledáme Svatı granát z Antiochu.}
{109}{}{Pro Bratrstvo oceli!}
{110}{}{Hmm... africká, nebo evropská vlaštovka?}
{111}{}{Hej, poèkat! To není tvoje nebo snad jo?}
{112}{}{Varuju tì. Dr ty ruce zpátky.}
{113}{}{Tak u dost. Èeho je moc, toho je pøíliš.}
{114}{}{Svatı granát z Antiochu? Je to nejlepší ruèní protipìchotní zbraò svého druhu.}
{115}{}{K èemu hledáte tak strašnou zbraò?}
{116}{}{My z Bratrstva oceli usilujeme o nalezení této nejnièivìjší zbranì našich pøedkù, a její zajištìní pøed tìmi, kteøí by zneuili nièivé síly Svatého granátu z Antiochu.}
{117}{}{Proè?}
{118}{}{Zkrátka proto, e Bratrstvo oceli chrání slabé a bezbranné; a tahle vìc by skuteènì mohla nìkomu ublíit.}
{119}{}{Proè?}
{120}{}{Hmm... protoe to je jediná správná a morální vìc.}
{121}{}{Proè?}
{122}{}{No... tak... Podívej, skuteènì máme dost práce. Hodláš nám pomoci nebo ne? Vidìl u jsi nìkdy Svatı granát z Antiochu nebo ne?}
{123}{}{Ano.}
{124}{}{Ne.}
{125}{}{Tak proè jsi to neøekl hned? Staèí nám povìdìt kde, my vyrazíme a ty se mùeš vrátit ke své práci a u to bylo cokoliv.}
{126}{}{(Ukáeš libovolnım smìrem.)}
{127}{}{Dobrá tedy. Díky za pomoc. Nìco za tvou slubu.}
{128}{}{Poèkat! Taky nìco hledám. Pátrám po svatém GECKu. Nevidìli jste ho?}
{129}{}{Dobrá tedy, u nemá smysl dál pokraèovat v tomto rozhovoru. Odcházíme.}
{130}{}{[KONEC]}
{131}{}{Zatracenı hlupák!}
{132}{}{[KONEC]}
{133}{}{GECK, øíkáš? Ano, máme dva. Další u nepotøebujeme. Kadopádnì díky.}
{134}{}{Kdy máte dva, snad byste mi mohli jeden dát.}
{135}{}{Ne. Ne. To nemùeme udìlat. To by byl pøíliš snadnı konec tvého hledání. Nìjaké další jsou tamtím smìrem. Najdi si svùj vlastní. (Ukazuje pøiblinì stejnım smìrem, jako jsi ukázal pøed chvílí ty, kdy jsi jim ukazoval, kde je svatı granát z Antiochu.)}
{136}{}{[KONEC]}

{200}{}{Mluvíš královskım jazykem?}
{201}{}{Buï póózdraven.}
{202}{}{Hej, tady jsem.}
{203}{}{Mìl bys chvilièku ze svého drahocenného èasu?}
{204}{}{Ehm.}
{205}{}{Neignoruj mì.}
{206}{}{Prosíííím! Potøebuju se tì na nìco hroznì dùleitého zeptat.}

{207}{}{Take, my musíme pokraèovat v hledání svatého granátu z Antiochu. Pojï, Patsy.}
