#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš obrovského chlapa.}
{101}{}{Vidíš obrovského chlapa.}
{102}{}{Je to fakt obr a takové, jako jsi ty, si zøejmì dává k snídani.}
{103}{}{Starouši. Pùjdeš s námi.}
{104}{}{Nechej nás na pokoji. Nikdy nepodpoøím vaše nadøízené.}
{105}{}{U ti to nebudu víckrát opakovat. Pojï nebo z tebe udìláme odstrašující pøíklad.}
{106}{}{S tím, co vím, bych se radìji vidìl v hrobì.}
{107}{}{A je po tvém. Zabijte je všechny.}
{108}{}{To není tvoje starost. Otoè se a jdi pryè.}
{109}{}{Zdá se, e urèité lidi potkáváš v nesprávnou dobu na nesprávném místì.}
