#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Muž v tìžké zbroji.}
{101}{}{Sir Bedemir.}
{102}{}{Zdá se, že usilovnì pøemýšlí.}
{103}{}{Sir Bedemir k vašim službám.}
{104}{}{...a proto víme, že Zemì má tvar banánu.}
{105}{}{Rád bych ti vysvìtlil, jak se dá použít ovèího mìchýøe pøi prevenci proti zemìtøesení.}
{106}{}{Potøebuji nìjaký èas k pøemýšlení. Bìž obtìžovat nìkoho jiného, prosím.}

{200}{}{Teï! Máš úplnì zmrzlé ruce!}
{201}{}{To ti nepatøí.}
{202}{}{Hej, to jsou moje vìci!}
