#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš velký kamenný monument. Zdá se, že... si pro sebe nìco mumlá?}
{101}{}{Vidíš kamenný monument v podobì hlavy Zakladatele. Podoba je docela vìrná i když pochybuješ, že jeho hlava byla tak velká.}
{102}{}{Vidíš velký kamenný monument.}
{103}{}{Vidíš kamenný monument v podobì hlavy Zakladatele. Podoba je docela vìrná i když pochybuješ, že jeho hlava byla tak velká.}
{104}{}{Zatracení turisti...}
{105}{}{"Jsem Vyvolený"}
{106}{}{Být tebou, Vyvolený, zmizel bych odsud.}
{107}{}{Zzzzzz Zzzzzz Zzzzzzzzzz}
{108}{}{ZZZZZZZzzzzzzzz}
{109}{}{Zsnzzz...*chrr*...zzzzsZZZZZ}
{110}{}{Zzzzznnnnnzzzzz}
{111}{}{ZZZZzzzzzZZZZZ}
{112}{}{Pøál bych si, abys vidìl, co je za mnou.}
{113}{}{Kdyby tak nìkdo pøišel a vykopal mì celého...}
{114}{}{Ti kamenožraví mravenci tady jistì každou chvíli budou a sežerou mì.}
{115}{}{"Buï velkou kamennou hlavou! Dívej se na svìt!" Jaké kecy.}
{116}{}{Je to pro mì záhada jak jsem se ocitl tady uprostøed pouštì.}
{117}{}{Poøád nevím, proè musím sedìt tady uprostøed pouštì, zatímco druhá hlava je ve vesnici.}
{118}{}{Chci øíct, že je uctívána, èištìna a lidé se k ní modlí....a já mùžu jenom celý den èuèet jenom na písek.}
{119}{}{Slyšel jsem, že ti na Východních ostrovech to mají docela dobrý.}
{120}{}{Myslím, že Stonehenge má vìtší návštìvnost než já.}
{121}{}{Hrnnfff...uh-uh, Mami...dnes se do školy nejde...Zsnzzzzz}
{122}{}{Zzzsnnnzzzz...ještì nechci vstávat....Zzznnsss}
{123}{}{Zzsssccs...eh?}
{124}{}{Co--?}
{125}{}{DEJ TY ZATRACENÝ PRACKY PRYÈ!}
{126}{}{Hráè se musí obrátit, odstoupit o nìkolik krokù a znovu se otoèit èelem k monumentu.}
{127}{}{*Ehm*}
{128}{}{KDO SE OPOVAŽUJE PØISTOUPIT K POSVÁTNé HLAVÌ ZAKLADATELE?!}
{129}{}{Já, Vyvolený.}
{130}{}{HA HA HA HA HA HA!}
{131}{}{*TY*?! VYVOLENÝ?!}
{132}{}{NEJSI VÌTŠÍ NEŽ MÙJ PRST!}
{133}{}{TY NEJSI VYVOLENÝ.}
{134}{}{Ano jsem.}
{135}{}{NE, NEJSI.}
{136}{}{Ano, jsem.}
{137}{}{UH-UH.}
{138}{}{Uh-huh.}
{139}{}{UH-UH.}
{140}{}{Uh-huh.}
{141}{}{UH...UH...}
{142}{}{Uh...huh...}
{143}{}{UH...DOST! NECHEJ TOHO!}
{144}{}{VELMI DOBØE! PØESVÌDÈIL JSI MÌ!}
{145}{}{TY *JSI* TEN VYVOLENÝ!}
{146}{}{VEM SI TOHLE!}
{147}{}{TEÏ MÌ NECHEJ!}
{148}{}{Hej, díky!}
{149}{}{JO. JAK CHCEŠ. TEÏ JDI PRYÈ.}
{150}{}{ZATRACENÍ TURISTI.}
{151}{}{UŽ JSEM TI DAL DÁREK.}
{152}{}{ZMIZ!}
{153}{}{Idiote.}
{154}{}{CO?! TY MÌ CHCEŠ OKRÁST?!}
{155}{}{ZEMØI!}
{156}{}{Rozlož hráèe pomocí animace plazmové smrti.}

{200}{}{(o 12 hodin pozdìji)}