#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš... èerného hrdinu.}
{101}{}{Vidíš svalnatého èernocha v overalu Vaultu 13. Nasupenì tì sleduje.}
{102}{}{Vidíš èernocha. Nasupenì tì sleduje.}
{103}{}{Vidíš èernocha. Nasupenì tì sleduje.}
{104}{}{Pùvodnì byl jedním z hrdinù pro Fallout 1.}
{105}{}{Samozøejmì jsem ve finální verzi chybìl.}
{106}{}{Tvrdili, že by to bylo moc animací. Pøíliš obrázkù, øíkali.}
{107}{}{Jsem èernej. Zbytek si domysli sám.}
{108}{}{Pokaždé, když už si zaèínáš myslet, že se dostaneš nahoru, pøijde nìjakej bílej a zmìní pravidla.}
{109}{}{Chtìl bych toho hajzla dostat do rukou...}
