#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš mýtného od Mostu Smrti.}
{101}{}{Vidíš muže s divokým pohledem, s rozcuchaným plnovousem a chraplavým hlasem. Levé oko jako by mu už už mìlo vypadnout z dùlku.}
{102}{}{Vidíš mýtného od Mostu Smrti.}
{103}{}{Vidíš muže s divokým pohledem, s rozcuchaným plnovousem a chraplavým hlasem. Levé oko jako by mu už už mìlo vypadnout z dùlku.}
{104}{}{Stùj! Kdo chce pøekroèit Most Smrti musí znát odpovìï na mé tøi otázky.}
{105}{}{Céé...Dééé...Eéé...efff...Gééé}
{106}{}{Vysmahni.}
{107}{}{Velmi dobøe.}
{108}{}{Ptej se, mýtný. Nebojím se.}
{109}{}{Asi pøijdu pozdìji.}
{110}{}{Jak se jmenuješ?}
{111}{}{Háá....Iíí...Jéé...Káá...ell...}
{112}{}{?}
{113}{}{Já } #continue at 172
{114}{}{Neøíkej.}
{115}{}{z Arroya.}
{116}{}{Harry}
{117}{}{Hakuin}
{118}{}{Testocles}
{119}{}{Richard Grey}
{120}{}{Seymour Heine}
{121}{}{Vyvolený!}
{122}{}{Asi pøijdu pozdìji.}
{123}{}{Co je smyslem tvé výpravy?}
{124}{}{emm....ennn....oóó...péé}
{125}{}{GEK. Arro-yo}
{126}{}{(Neøíkej)}
{127}{}{Najít svatý GECK.}
{128}{}{Najít zpùsob jak zachránit moji vesnici.}
{129}{}{Najít svùj unesený kmen.}
{130}{}{Opravit rozbitý tanker.}
{131}{}{Uh... výpravy?}
{132}{}{Snad bych mìl pøijít, až se budeš cítit trochu lépe.}
{133}{}{Která postava z Falloutu 1 pøežila a objevuje se v pokraèování, pøestože je už asi velmi stará?}
{134}{}{Která postava z Falloutu 1 pøežila a objevuje se v pokraèování?}
{135}{}{Jak stará?}
{136}{}{Pokraèování?}
{137}{}{(Neøíkej)}
{138}{}{Co -- ?! To teda nevím!}
{139}{}{Uh... Ian?}
{140}{}{Uh... pes?}
{141}{}{Uh... Tandi?}
{142}{}{Uh... Tycho?}
{143}{}{Uh... Harold?}
{144}{}{Co máš na mysli? Poèítáš do toho i náhodná setkání nebo je považuješ za zvláštní události?}
{145}{}{Co máš na mysli? Spojence nebo nepøátele?}
{146}{}{Kolik unese èlovìk s perkem Silná záda 6?}
{147}{}{To fakt nevím.}
{148}{}{Uh... 200 liber?}
{149}{}{Uh... 225 liber?}
{150}{}{Uh... 250 liber?}
{151}{}{Uh... 275 liber?}
{152}{}{Uh... 300 liber?}
{153}{}{Uh... 325 liber?}
{154}{}{Kolikátého mùže èlovìk dosáhnout levelu perku Silná záda?}
{155}{}{Jaké jsou minimální požadavky na perk Puntièkáø?}
{156}{}{To fakt nevím.}
{157}{}{Uh... sílu pìt?}
{158}{}{Uh... hbitost pìt?}
{159}{}{Uh... hbitost šest?}
{160}{}{Uh... level tøi?}
{161}{}{Uh... level šest?}
{162}{}{Uh... level devìt?}
{163}{}{Co máš na mysli? Statistiku nebo požadavky na novou úroveò?}
{164}{}{Dobrá. Už bìž.}
{165}{}{Dík}
{166}{}{Bezva}
{167}{}{Oh díky. Díky moc.}
{168}{}{To teda nevím!}
{169}{}{Hráè je totálnì rozhozenej.}
{170}{}{Heh-heh.}
{171}{}{Z nìjakého dùvodu si myslím, že bych si mìl uložit hru na nové pozici.}

{172}{}{jak ti øíkaj?}

{173}{}{Nikdy se nedostanu k tomu, abych položil vhodné otázky.}
{174}{}{O tom si promluvím se svým agentem.}
{175}{}{Už jsem mu øíkal stokrát, aby nechal tìch ksichtù.}
{176}{}{Jak si mùžu zasloužit respekt, když si zasloužím být jenom ve filmech a videohrách s nízkým rozpoètem.}
{177}{}{Hmmm... Myslím, že bych se mìl dát na opravování aut.}
{178}{}{Slyšel jsem, že dneska se v tom dají vydìlat peníze.}

{200}{}{AAAAAAAHHHHHHHHhhhhhh!}