#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš strážného.}
{101}{}{Vidíš jednoho ze strážných, kteøí ti pomáhají s karavanou.}

{200}{}{Vidíš honáka od karavany.}
{201}{}{Vidíš jednoho z honákù, kteøí ti pomáhají s karavanou.}


{300}{}{Doufám, že na naší cestì už moc srážek s nepøítelem nezažijeme.}
{301}{}{Bude fajn dostat na konci cesty šek.}
{302}{}{Doufám, že bude v baru otevøeno až tam dorazíme.}
{303}{}{Bude fajn zase nìco poøádného sníst.}
{304}{}{Vždycky jsem chtìl cestovat. Myslím, že to co dìlám má k cestování nejblíže.}
{305}{}{Hroznì mì bolí nohy. Kéž by ty pitomý brahmíny trošku zrychlily.}
{306}{}{Slyšel jsem, že do konce cesty už moc nezbývá.}
