#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš zle vypadajícího psa.}
{101}{}{Vidíš psa.}
{102}{}{Vidíš psisko.}
{103}{}{Pes hluboce zakòuèí, když vidí obleèení z vaultu. Zdá se, že chce jít s tebou.}
{104}{}{Písk}
{105}{}{Mohl bys se mnou až budu mít víc místa.}
{106}{}{Uh-uh, pejsku. Zùstaò.}
{107}{}{No tak hochu. Je èas na nìjakou neplechu.}
{108}{}{Bez starosti hochu. Pøijdu si pro tebe až budu mít víc místa.}
{109}{}{Promiò hafane. Tentokrát ne.}
{110}{}{Pes chamtivì zhltne leguána na špejli a pak se na tebe zadívá v oèekávání.}
{111}{}{Písk}
{112}{}{Mohl bys se mnou, až budu mít víc místa.}
{113}{}{Uh-uh, pejsku. Zùstaò.}
{114}{}{No tak hochu. Je èas na nìjakou neplechu.}
{115}{}{Bez starosti hochu. Pøijdu si pro tebe až budu mít víc místa.}
{116}{}{Promiò pejsku. Tentokrát ne.}
{117}{}{Vidíš zle vypadajícího psa.}
{118}{}{Písk}
{119}{}{Moh bys se mnou až budu mít víc místa.}
{120}{}{Stùj pejsku. Ani se nehni.}
{121}{}{Odplazí se.}
{122}{}{No tak hochu. Je èas na nìjakou neplechu.}
{123}{}{Bez starosti hochu. Pøijdu si pro tebe až budu mít víc místa.}
{124}{}{Drž se pøi mnì. Jasný hochu?}
{125}{}{Drž se v pøimìøené vzdálenosti, pejsku.}
{126}{}{Zùstaò daleko ode mne, pejsku. Hlídej mi záda.}
{127}{}{Zùstaò, pejsku. Zùstaò!}
{128}{}{Myslím, že toho psa nechám na pokoji.}
{129}{}{Ps ostøe vyštìkne a slabì zavrèí.}
{130}{}{Drž se pøi mnì. Jasný hochu?}
{131}{}{Drž se v pøimìøené vzdálenosti, pejsku.}
{132}{}{Zùstaò daleko ode mne, hafíku. Hlídej mi záda.}
{133}{}{Zùstaò, pejsku. Zùstaò!}
{134}{}{Díky, pejsku. Teï bìž.}
{135}{}{Auuuuuuuuuuuu}
{136}{}{Auuuuuuuuuuuu}
{137}{}{Eee kámo, zahráváš si se mnou.}
{138}{}{Grrrrr....}
{139}{}{(Rád bych vìdìl jestli mùžu pøimìt toho psa, aby mì následoval jiným zpùsobem.)}