#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš èlena Enklávské patroly.}

# Floats if PC is male
{200}{}{Jsi neoprávnìnì na území Enklávy. Podle vyhlášky èíslo 312 máme naøízeno støílet bez výstrahy. Sorry hochu!}
{201}{}{Je to špión mutantù! Sundejte ho!}
{202}{}{Jako oddaný voják Enklávy jsem dostal rozkaz tì zastøelit. Doufám, že ti to nevadí.}
{203}{}{Základno, v sektoru 3 máme narušitele; èekám na další rozkazy.... Zabít? Rozumím, základno.}
{204}{}{Teï mi urèitì budeš chtít tvrdit, že tady jenom hledáš vodní èip. Myslíš, že jsem blbec? Dostaòte ho!}
{205}{}{Chcípni, špíno z pustiny!}
{206}{}{Ty! Tobì podobní znièili náš, kdysi mocný, národ. Ty za to zaplatíš!}
{207}{}{Hej, Louie! Už jsi vidìl co dokážou tyhle vèelièky na tìle? Tak sleduj!}

# (Floats if PC is female)
{300}{}{Ježííš, nesnáším, když musím zabít ženskou. Udìlejme to teda rychle, jo?}
{301}{}{Poplach! Poplach!}
{302}{}{Zdá se, že jsi urazila takovou dálku pro nic za nic, dámo.}
{303}{}{Jako oddaný voják Enklávy jsem dostal rozkaz tì zastøelit. Doufám, že ti to nevadí.}
{304}{}{Ty! Tobì podobní znièili náš, kdysi mocný, národ. Ty za to zaplatíš!}
{305}{}{Neboj. Je to jenom nìjaká ženská z pustiny. Ta se nezmùže na nìjaký vìtší odpor.}
{306}{}{Je škoda, že jsme se nemohli setkat za jiných okolností.}
{307}{}{Nemluv na mì. Já nepodlehnu tvým ženským svodùm. Zemøi!}
