#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš štíhlého, opáleného muže.}
{200}{}{Vidíš štíhlou, opálenou ženu.}
# male
{101}{}{Vidíš farmáøe.}
# female
{201}{}{Vidíš farmáøku.}
{102}{}{Všímáš si, že je opálený jako farmáø.}
{202}{}{Všímáš si, že je opálená jako farmáøka.}
{103}{}{Deus ex machina - jsi tu právì vèas. Kdyby nebylo tebe... díkybohu, že jsi tu. Moc toho nemáme, ale pøijmi to prosím jako odmìnu za tvou pomoc. (Nìco ti podává.)}
{104}{}{Dìkuji.}
{105}{}{Ug.}
{106}{}{Ještì jednou dìkuji za pomoc.}
{107}{}{}
{108}{}{}
{109}{}{Jen ty ruce drž tak, aby na nì bylo vidìt. V poslední dobì se nás dost natrápili banditi a ty vypadáš, jako nìkdo toho typu. Co chceš?}
{110}{}{Chci jenom vymìnit nìjaké zásoby.}
{111}{}{Jenom tudy procházím. Brzy odejdu.}
{112}{}{Ug.}
{113}{}{Myslím, že z toho žádné nebezpeèí nehrozí. Tady je moje nabídka.}
{114}{}{[Smlouvání]}
{115}{}{OK, teï bìž!}
{116}{}{[Smlouvání]}
{117}{}{Øekl jsem bìž!}
{118}{}{}
{119}{}{(Trochu se uklidòuje.) Na banditu jsi pøíliš velký hlupáèek. Potøebuješ zásoby?}
{120}{}{Uh huh.}
{121}{}{Eh eh.}
{122}{}{Dobrá tedy, nedohodli jsme se. Tak tedy pokraèuj.}
{123}{}{[KONEC]}
{124}{}{Odejdìte z mé farmy!}
{125}{}{Nikdo mi mùj domov nevezme.}
{126}{}{Špinaví banditi.}
{127}{}{Zmizte z mé pùdy.}
{128}{}{Dnes už nemùžeš vìøit nikomu.}
{129}{}{Zatracení banditi.}
{130}{}{Pøíliš tvrdì jsem pracoval na to, abych to teï vzdal.}
{131}{}{Asi budu farmaøit jinde.}
{132}{}{Jsem jen chudý farmáø.}
{133}{}{Prosím nevypaluj moji farmu.}
{134}{}{Stejnì jsem to farmaøení nesnášel.}
{135}{}{Já se vrátím.}
{136}{}{Vezmìte si moji ženu -- prosím...}