#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{To je mùj dùm.}
{101}{}{Zatracení banditi.}
{102}{}{Nechej nás na pokoji!}
{103}{}{Nenávidím bandity.}
{104}{}{Nemáme nic, co bys mohl ukrást.}
{105}{}{Nezabíjej mì.}
{106}{}{Už toho mám dost.}
{107}{}{Vezmi si co chceš.}
{108}{}{Prosím, nezabíjej mì.}
{109}{}{Stejnì nenávidím farmaøení.}
{110}{}{Prosím, nevypaluj mi mùj dùm.}