#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Rybáø.}
{101}{}{Pøišel jsi právì vèas, aby ses stal svìdkem poehnání Bohynì moøe.}
{102}{}{[Více]}
{103}{}{}
{104}{}{Tìsnì pøed velkou bouøí vrhneme své harpuny do moøe, abychom prokázali svou odvahu pøed ivly. Pokud prokáeme, e jsme toho hodni, Bohynì nás odmìní svımi plody.}
{105}{}{Kdy pøijde období bouøí, házíme bìhem pøílivu kvìtiny Broca na moøe. Bohynì je svımi kouzly pøemìní na vzácnı koøen Xander.}
{106}{}{Kadı rok vzdáváme hold Bohyni moøe koøenem Xander. Pokud bohynì usoudí, e jsme toho hodni, promìní koøen Xander na kvìty Broa. }
{107}{}{Po vydatné sklizni, vzdáváme hold bohyni moøe, aby nás ochraòovala a opatrovala. Kadı rok odmìòuje naši poslušnost tak, e nám s pøílivem pošle harpuny jako symbol, e nad námi drí ochrannou ruku.}
{108}{}{Mohl bych vidìt, co vám bohynì vìnovala?}
{109}{}{Ug.}
{110}{}{Tady je, co nám velká bohynì seslala tento rok. Rádi se s tebou za nìjakou  úplatu o její poehnané dary rozdìlíme.}
{111}{}{Haraburdí [10]}
{112}{}{Laserová pistole [$10000]}
{113}{}{Zaostøené klacky [40]}
{114}{}{Ovoce [5]}
{115}{}{koøen Xanderu [20]}
{116}{}{Kvìt Brocy [10]}
{117}{}{Sbohem.}
{118}{}{(Ukazuje smìrem na moøe.) Pokraèuj v chùzi. Bohynì si pøeje setkat se s tebou osobnì.}
{119}{}{[Konec]}
{120}{}{A ti bohynì moøe na tvé cestì poehná.}
{121}{}{[Konec]}
{122}{}{(Mraèí se na tebe protoe nemáš dostatek penìz.) Snad nìkdy jindy.}
{123}{}{[Konec]}