#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Muž v tìžké zbroji.}
{101}{}{Sir Galahad.}
{102}{}{Èervená se, když zjistí, že na nìj civíš.}
{103}{}{Sir Galahad, k službám!}
{104}{}{Kdysi jsem byl vìznìm v zámku Anthrax.}
{105}{}{Sir Launcelot mì zachránil. K èertu s ním!}
{106}{}{Mohl jsem být vìznìm.. (Popotahuje)}

{200}{}{Máš ruce jako led!}
{201}{}{To ti nepatøí.}
{202}{}{Hej, to jsou moje vìci!}