#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Myšièko myš, pojï ke mnì blíž.}
{101}{}{Grundel tì potøebuje na peèínku.}
{102}{}{Pojï sem, myško.}
{103}{}{Hodný Grundel ti neublížit.}
{104}{}{Malièké, chutòouèké.}
{105}{}{Pojï, pojï myšièko. Mám hlad.}
{106}{}{Písk, písk. PÍÍÍÍSK!}
{107}{}{Dobrá, dobrá, já lhát. Já tì teï sníst.}

{110}{}{Oooh! Ty velká myška. Být dobrá veèeøe pro Grundla.}