#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš poustevníka.}
{101}{}{Vidíš poustevníka.}
{102}{}{Vypadá, že se už léta nemyl.}
{103}{}{Chceš vìdìt proè poustevník? [Zdá se, že už léta s nikým nepromluvil.]}
{104}{}{Proè?}
{105}{}{Jenom tudy procházím.}
{106}{}{Ug.}
{107}{}{Já chtít být nechat o samotì.}
{108}{}{Když už jsem tady mohli bychom udìlat nìjaký obchod. Urèitì mám nìco, co bys mohl potøebovat.}
{109}{}{Pak tì nechám na pokoji.}
{110}{}{Obchod. Pak ty budeš odchodit.}
{111}{}{Dobøe, tady je moje nabídka}
{112}{}{Já nejlíp odchodit.}
{113}{}{Odejdi.}
{114}{}{Už pùjdu.}
{115}{}{Hmm... Líbíš se. Nechtít mluvit. Zùstaò a obchoduj ty a já.}
{116}{}{K'}
{117}{}{Já chodím.}
{118}{}{Dobrá øeè. Teï choï. Jsem já unavený.}
{119}{}{KONEC]}
{120}{}{Øeè dìlá bolest hlavy. Choï.}
{121}{}{Skonèil já øeè s tebou.}
{122}{}{Neøíkat nic. Choï.}
{123}{}{Bìž pryè!}
{124}{}{Odejdi z domu!}
{125}{}{Jak odvážil ses útok na mì!}
{126}{}{Nech na pokoji mì.}
{127}{}{Já jít...}
