#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Jídlo!}
{101}{}{Dejte nám jídlo!}
{102}{}{Máme hlad!}
{103}{}{Nìjaké peníze pro ty ménì šastné.}
{104}{}{Pomozte nám!}
{105}{}{Jídlo!}
{106}{}{Mám hroznı hlad.}
{107}{}{Moje dìti hladoví.}
{108}{}{Nikdo o nás nemá zájem.}
{109}{}{Nezabíjejte mì!}
{110}{}{Chtìl jsem jenom nìco k jídlu.}
{111}{}{Odpuste mi.}
{112}{}{ebrák bere pøedmìt.}
