#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš lovce.}
{101}{}{Jsi tady vítán, Vyvolenı.}
{102}{}{U jsi našel svatı GECK?}
{103}{}{Vra se brzy i s GECKem.}
{104}{}{A jsou tvé cesty bez bolesti.}
{105}{}{Vra nám to co je nám dlueno.}
{106}{}{Musíš si pospíšit, Vyvolenı.}
{107}{}{Naše modlitby jsou s tebou, Vyvolenı.}
