#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Muž brnká na loutnu.}
{101}{}{Joshua.}
{102}{}{Potulný pìvec.}

{103}{}{Hrdinný Sir Robin utekl...}
{104}{}{Hrdinnì z boje utekl...}
{105}{}{Když nebezpeèí ukázalo svoji hnusnou tváø, hrdinnì stáhl ocas mezi nohy a utekl...}
{106}{}{Ano, je to tak. Hrdina Sir Robin se otoèil...}
{107}{}{A galantnì se vypaøil. Hrdinnì práskl do bot...}
{108}{}{Hrdinnì troubil na ústup...}
{109}{}{Oh, Hrdinný Sir Robin.}