#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš muže v MKII tìžké zbroji. Nevypadá pøátelsky.}
{101}{}{Vidíš Kagu v MKII tìžké zbroji.}
{102}{}{Obrovský kus železa s rukama a zbranìmi.}
{103}{}{Už jsem z toho pronásledování unavený. Skonèeme to.}
{104}{}{To je naposled, kdy potkáváš Kagu.}
{105}{}{Kagovi se nemùžeš rovnat.}
{106}{}{Tìším se jak tì pošlu na onen svìt.}
{107}{}{Byl jsi dobrým soupeøem.}
{108}{}{V této èásti pustiny není potøeba dobráka, jako jsi ty.}
{109}{}{Až tì zabiju, budu nejobávanìjším èlovìkem v této èásti pustiny.}
{110}{}{Tìším se domù do Arroya -- abych ho vypálil.}
{111}{}{Kaga se proslaví tím, že tì zabije.}