#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš polonahého muže.}
{101}{}{Vidíš Kagu.}
{103}{}{Má na sobì kalhoty a vypadá jako by pocházel z nìjakého kmene.}
{104}{}{Já jsem mìl být tím Vyvoleným!}
{105}{}{Jak se mohl Arroyo opovážit vyhnat mì z kmene.}
{106}{}{Vykonám svou pomstu na tobì!}
{107}{}{Kaga tì pošle na onen svìt.}
{108}{}{Ještì se uvidíme!}
{109}{}{Ještì nikdy jsem nebyl zbit!}
{110}{}{Obìtuji se, abych tì znièil.}