#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš muže v plechové zbroji.}
{101}{}{Vidíš Kagu.}
{102}{}{Jo, je to Kaga, ne-až-tak-velký. Má plechovou zbroj a chce tì zabít.}
{103}{}{Zase ty!}
{104}{}{Už mì ta stálá setkání zaèínají unavovat.}
{105}{}{Vyvolený - hmm!}
{106}{}{Pojïme to skoncovat.}
{107}{}{Bude tì mrzet, že jsi kdy slyšel jméno Kaga!}
{108}{}{Mé dovednosti doznaly velkého zlepšení od té doby, co jsme se naposled setkali.}
{109}{}{Stává se z toho zlozvyk.}
{110}{}{Kaga musí ještì trochu trénovat.}
{111}{}{Kaga se vrátí.}
