#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš malé mrnì.}
{101}{}{Vidíš Melchiora juniora.}

{150}{}{Je to usmìvavý, okatý kluk.}

{200}{}{Ahoj! Jsem Melchior mladší.}
{201}{}{Táta je horník. Jmenuje se stejnì jako já, Melchior.}
{202}{}{Táta je dobrý horník, ale chtìl by se stát kouzelníkem.}
{203}{}{Tátovo umìlecké jméno je, Melchior Vznešený.}
{204}{}{Jeho nejvìtším èíslem byla krysa z klobouku.}
{205}{}{Odešel s nìjakými muži odìnými do plechové výstroje.}
{206}{}{Doufám, že se táta brzy vrátí. Je mi smutno po jeho kouzlech.}
{207}{}{Chci se stát velkým kouzelníkem, jako táta.}