#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Nomád.}
{101}{}{Buï zdráv. Zdá se, že jsi tady nový.}
{102}{}{Mìl by sis promluvit s náèelníkem.}
{103}{}{Myslím, že není takové horko, jako vèera.}
{104}{}{Tak co, jak jde život ve mìstì?}
{105}{}{Neznaboh!}
{106}{}{Proè na nás útoèíte?}
{107}{}{Budu bránit svùj kmen do poslední kapky krve!}
{108}{}{Jak ses mohl opovážit zneužít naší pohostinnosti!}
{109}{}{Zmiz!}
{110}{}{Nechej nás na pokoji.}
{111}{}{Jsme mírumilovný kmen.}
