#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Nomád.}
{101}{}{Náèelník nomádù.}
{102}{}{Podle toho, co má na sobì a zpùsobu, jakım se nese, to musí bıt nìjakı vùdce.}
{103}{}{Ah, poutník. Vítej v mém skrovném stanu. Spoèiò ve stínu a ulev si od nekoneèného vedra.}
{104}{}{Dìkuji. S povdìkem pøijímám nabídku stínu.}
{105}{}{Musím odmítnout tvoji nabídku. Jenom jdu kolem.}
{106}{}{Ooga.}
{107}{}{Buï vítán. U dlouho jsme odøíznuti od civilizovanıch konèin. Potøebovali bychom urèité zboí. Snad bychom mohli nìco vymìnit.}
{108}{}{Co máš k obchodování?}
{109}{}{Nemám nic, co bych mohl smìnit. Je mi líto.}
{110}{}{Tak snad nìkdy jindy. A jsou tvé cesty prosty nebezpeèí.}
{111}{}{Sbohem.}
{112}{}{Jaká nešastná náhoda. Buï vítán v mém táboøe a odpoèiò si.}
{113}{}{Sbohem.}
{114}{}{Moje nabídka stínu pro tebe pøišla pøíliš pozdì. Slunce ti asi vypálilo mozek. Musím bıt pøívìtivı k tìm, kteøí v ivotì nemají tolik štìstí. Zùstaò v mém táboøe, jak dlouho budeš chtít, zabednìnèe.}
{115}{}{Sbohem.}
{116}{}{Bezvìrec!}
{117}{}{Proè na nás útoèíš?}
{118}{}{Budu bránit náš kmen dokud nepadnu!}
{119}{}{Jak jsi se mohl opováit zneuít mé pohostinnosti.}
{120}{}{Zmiz!}
{121}{}{Nechej nás.}
{122}{}{Jsme mírumilovnı kmen.}
