#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Nomád.}
{101}{}{Nomádskı šaman.}
{102}{}{Z jeho obleèení je cítit silná vùnì bylin.}
{103}{}{Buï zdráv cizinèe. Jsem šamanem kmene. Ovládám umìní léèitelské.}
{104}{}{Znovu tì zdravím.}
{105}{}{Potøebuji vyléèit.}
{106}{}{Umíš smísit koøen Xanderu s kvìtem Brocy?}
{107}{}{Sbohem.}
{108}{}{Ooga.}
{109}{}{Stùj klidnì a já tì vyšetøím.}
{110}{}{[Pokraèování]}
{111}{}{Objevil jsem následující choroby.} #continue at 136
{112}{}{Mùeš mi pomoci?}
{113}{}{Následující èinnosti provádím za úplatu:} # continue at 140
{114}{}{Dostaò jed z mého tìla, prosím.}
{115}{}{Prosím, uzdrav mì.}
{116}{}{Podívej se co bys mohl udìlat s tou zlomeninou.}
{117}{}{Sbohem.}
{118}{}{Byl jsi vyléèen.}
{119}{}{Byl jsi vyléèen.}
{120}{}{Byl jsi vyléèen.}
{121}{}{Potøebuji lépe vyuít tvıch schopností.}
{122}{}{Dìkuji. Cítím se o hodnì lépe. Sbohem..}
{123}{}{Mé schopnosti jsou omezené. Více ti s tím u prostì nemùu pomoci.}
{124}{}{[Pokraèování]}
{125}{}{Nepotøebuješ tento typ léèení.}
{126}{}{[Pokraèování]}
{127}{}{Ahh...Ty znáš léèebné úèinky tìchto dvou rostlin. Bude tì to stát jenom } # continue at 150
{128}{}{Smíchej pro mì prosím tyto dvì rostliny.}
{129}{}{Snad pozdìji. Sbohem.}
{130}{}{[Díváš se, jak opatrnì drtí a mísí dvì rostliny a podává ti pøesnì odmìøené dávky prášku.]}
{131}{}{Sbohem.}
{132}{}{Zdá se, e nemáš dost penìz. Vra se a bude tvoje penìenka naditìjší.}
{133}{}{[KONEC]}
{134}{}{Nemám èas na takové hlouposti. Odejdi!}
{135}{}{[KONEC]}
{136}{}{[Otráva]}
{137}{}{[Zranìní]}
{138}{}{[Ozáøení]}
{139}{}{[Ochromení]}
{140}{}{Léèení otrav,}
{141}{}{Napravení zmrzaèenıch konèetin,}
{142}{}{Uzdravování $}
{143}{}{Neznaboh!}
{144}{}{Proè na nás útoèíš?}
{145}{}{Budu bránit svùj kmen do poslední kapky krve!}
{146}{}{Jak jsi se mohl opováit zneuít naší pohostinnosti.}
{147}{}{Zmiz!}
{148}{}{Nechej nás na pokoji.}
{149}{}{Jsme mírumilovnı kmen.}
{150}{}{ a já je pro tebe smíchám.}