#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Tohle zvíøe by mìlo bıt utraceno, aby u se dál netrápilo.}
{101}{}{Vzdálenì pøipomíná psa. Chlupy z jeho zbídaèeného tìla odpadávají po chuchvalcích.}
{102}{}{Vidíš ošklivého, zbìdovaného psa. Líbíš se mu.}

{110}{}{Haf}
{111}{}{Hauuíííí úúúúúúhhhh ffff}
{112}{}{hafff ffffaaffff}
{113}{}{vrrr vrrr ffff}
{114}{}{HHHaaúúúúú}
{115}{}{uhhhh hafff}

{200}{}{Teï, kdy je pes mrtvı, cítíš se daleko bezpeènìji.}
{201}{}{Pro to zvíøe u toho moc udìlat nemùeš. Smrtící kulka má zøejmì vìtší cenu.}
{202}{}{Jejda, opravdu vypadá uboze. Mimo to se ho opravdu nechceš dotıkat.}
