#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Zlatokop}
{101}{}{Stùj cizinèe! Nejsem zvyklı pøepadat cizince, ale potøebuji zásoby a nemohu opustit své území. Nechceš udìlat malı obchod?}
{102}{}{Jasnì.}
{103}{}{Nemám nic, s èím bych mohl obchodovat. Je mi líto.}
{104}{}{Booga.}
{105}{}{Jaké štìstí. Nemùeš mluvit, je to tak? Kdy nemùeš mluvit, nemùeš nikomu øíct, kde je moje území. Pojïme obchodovat.}
{106}{}{[Obchod]}
{107}{}{Dobrá, a je po tvém. Jenom nikomu neøíkej, kde je moje území.}
{108}{}{[Konec]}
{109}{}{Myslím, e bys mìl pokraèovat.}
{110}{}{U nemáme o èem mluvit.}
{111}{}{Jak chceš!}
{112}{}{Chytej.}
{113}{}{Nemùu tì nechat, abys nìkomu vyzradil, kde je moje území.}
{114}{}{Proè na mì útoèíš?}
{115}{}{Teï tì musím zabít.}
{116}{}{Chtìl jsem jenom nìjaké zásoby.}
{117}{}{Mùeš mít moje území!}
{118}{}{Milost!}