#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Ach! Další rekrut.}
{101}{}{Podepiš nebo zemøi!}
{102}{}{Buï vším, èím mùžeš být.}
{103}{}{Hrdí, výjimeèní žoldáci.}
{104}{}{Pøidej se k nám!}
{105}{}{4F.}
{106}{}{Èas poohlédnout se jinde.}
{107}{}{Pøidej se k námoønictvu.}
{108}{}{Sakra!}
{109}{}{Ach! Podívej, kolik je hodin. Musím už jít!}
{110}{}{Rekrut.}
{111}{}{Seržant.}