#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Teplouši jsou hrdí!}
{101}{}{Pryè s heterosexuály!}
{102}{}{Vetøelci nejsou vítaní!}
{103}{}{Jsem pyšná, že jsem lesbièka!}
{104}{}{Dívèí síla!}
{105}{}{Nepotøebujeme chlapy!}
{106}{}{Spoleèenství Duhy bude žít dál.}
{107}{}{Stáhni se do Love Shacku.}
{108}{}{Jednou budeme dál!}
{109}{}{Vítej ve Spoleèenství Duhy.}
{110}{}{Takoví jako ty, jsou u nás vítáni.}
{111}{}{Jsi jedním z nás.}
{112}{}{Kolonizátoøi.}
{113}{}{Osadník.}
{114}{}{Homouši.}
{115}{}{Buzíku.}
{116}{}{Teplouši.}
{117}{}{Lesbo.}
{118}{}{Lesbo.}
{119}{}{Vypadá, že to je }
