#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Ten èlovìk se trochu potácí.}
{101}{}{Vidíš barmana.}
{102}{}{Zdá se, e u ochutnal nìco ze svého zboí.}
{202}{}{Zdá se, e u ochutnala nìco ze svého zboí.}
{103}{}{C...cco...cco ssi dáš. (Škyt.)}
{104}{}{Nuka Cola [$6]}
{105}{}{Pivo [$15]}
{106}{}{Chlast [$30]}
{107}{}{Dnes nic. Díky.}
{108}{}{Ug.}
{109}{}{Ohhhh...nesnáášim pití. (Podává ti tvùj drink.)}
{110}{}{[Konec]}
{111}{}{Tumáš. Je to toošku teplé, prootoe se tooo nestihoo vychladit. Vyyypje seee to rychlejš ne udjìlám novej driink. (Je to teplé, je to luté... jsou to....)}
{112}{}{[Konec]}
{113}{}{(Dáš si velkı hlt a cítíš, jak se ti rozleptává aludeèní stìna.)}
{114}{}{[Konec]}
{115}{}{Ach... (Škyt) Myslim, sess u njeco pil.}
{116}{}{[End]}
{117}{}{Ahhh èloujeèee! Ty nemaašš dost peòez! Pøiï, a njejake budeš mit..}
{118}{}{[Konec]}
{119}{}{Divoce se na sebe podíval.}
{120}{}{Vidíš závisláka.}
{121}{}{Trochu se klepe.}
{122}{}{Cochceš? Fšeckomaam!}
{123}{}{Mentats [$560]}
{124}{}{Buffout [$400]}
{125}{}{Psycho [$800]}
{126}{}{Dnes nic. Díky.}
{127}{}{Ug.}
{128}{}{Tojesuper! Navalprachyavypadniodsuï. Mamnjakoupraci.}
{129}{}{[Konec]}
{130}{}{Jakøikapøislovi. Bezpenìzdohospodynelez. Oh. Tojeprosex. Cotakhleádnépenízeádnáláska.
 Pøiïabudešmítpenize.}
{131}{}{[Konec]}
{132}{}{Heheheh! Zdaseemuešuítmentats. Dejmi $1000.}
{133}{}{(Dej tomu mui $1000)}
{134}{}{Já jdu.}
{135}{}{OHYEAH! Totìpovznese!}
{136}{}{[Konec]}

#Drunk: sets the sex flag
{150}{}{Hej, vypadáš mile. Jak se jmenuješ?}
{151}{}{A'lil vıše. Jooo.}
{152}{}{Pøipraven... rajcuje tì to?}
{153}{}{Naw..naw..naw..naw nuh naw.}
{154}{}{Takhle se dívej. Jo.}
#Drunk: the sex flag is set and you got some
{155}{}{Teï jdi.}
{156}{}{Nechej mì se tady opít.}
{157}{}{Ne... bjì njekam jinam.}
#prop Drunk
{158}{}{Co kdybychom odsud vypadli?}
{159}{}{Jo, pojïme!}
{160}{}{Nee, Jsem satı.}
{161}{}{(Grg) ::úsmìv::}

#Addict: set the sex flag
{170}{}{Hej, nešel bys tam za to køoví?}
{171}{}{U's nìkdy byl na vrcholu a dìlal to?}
{172}{}{Mohl bych ti ukázat ráj, bejby.}
{173}{}{Víš, chtìl bych trochu nìnosti.}
{174}{}{Doufala jsem, ze narazím na nìkoho, kdo bude chtít.}
#Addict: the set flag is set and you got some
{175}{}{U toho na mì bylo dost.}
{176}{}{Hele, nemáš cigáro?}
{177}{}{Hele, moc se na mì neupni. Já mám rád svoji svobodu.}
#prop Addict
{178}{}{Jsi štíhlı jako panter a já tì chci.}
{179}{}{Pøipraven?}
{180}{}{Teï ne. Musím si šlehnout.}
{181}{}{Drte si klobouky. Jedeme z kopce.}

{200}{}{Nebuï blbej!}
{201}{}{Bì nìkam jinam.}
{202}{}{Kdo tì sem pustil?}

{203}{}{To není moc super!}
{204}{}{Vychladni frajere.}
{205}{}{Klídek chlape!}
