#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš skupinu dobøe ozbrojených pocestných.}
{101}{}{Jsou to poøád dobøe vyzbrojení cizinci.}
{102}{}{Mají vyèištìné a dobøe naleštìné zbranì a na hrudi mají nìjaké znaky.}
{103}{}{Hledáme otrokáøské hlídky. Nevidìl jsi nìjaké cizinèe?}
{104}{}{Buï zdráv cizinèe. Jenom doufám, že nejsi otrokáø. Je to ve tvém zájmu.}
{105}{}{Rádi tì potkáváme, cizinèe. Nestarej se o nás a všechno bude v poøádku.}
{106}{}{Jsme NCR Rangeøi. Dìláme ze svìta lepší místo. No nic, jenom jsem myslel, že bys to rád vìdìl.}
{107}{}{Jsme Rangeøi. Zabíjet otrokáøe je naše práce.}
{108}{}{Zatracený zastánèe otrokáøù. Zemøeš krutou smrtí!}
{109}{}{Do prdele! Varoval jsem tì!}
{110}{}{Takové jako jsi ty tady nepotøebujeme. Proto zemøi.}
{111}{}{Vždycky pøijdou na øadu zbranì. Cožpak už se nikdo nevzdá jenom tak?}
{112}{}{Tak a je to -- nastala doba lovu!}
{113}{}{Uh -- Dojdu pro posily. Ani se nehni!}
{114}{}{Øíkal, že si je mùžeme vzít. Jasnì...}
{115}{}{Au-au-au-au-au!}
{116}{}{Do prdele. Mizím odsud!}
{117}{}{Kvùli tomu nehodlám umøít!}
{118}{}{Vidím že máš tetování. Je to znak otrokáøù. Ty nejsi otrokáø, že ne?}
{119}{}{Ano.}
{120}{}{Ne.}
{121}{}{To máš dost zlý. Jsme NCR Rangeøi. Už si o nás slyšel? Vraždíme otrokáøe.}
{122}{}{Jsi zasraný lháø. Sejmìte ho!}
{123}{}{Buï zdráv cizinèe. Jsem Ezekiel od NCR Rangerù. Kdo ráèíš být ty?}
{124}{}{Po tom ti je prd.}
{125}{}{Øeknìme, že už jsem to jméno zaslechl. Jsi Ranger, je to tak?}
{126}{}{Ano.}
{127}{}{Po tom ti je úplný kulový.}
{128}{}{Dobrá, buï nepøíjemný. Aspoò, že nejsi otrokáø. Sbohem.}
{129}{}{Rád jsem tì poznal. Dbej na poøádek. Nashle.}