#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš... dívku-hrdinku, s rezavými vlasy.}
{101}{}{Vidíš úžasnì krásnou dívku, hrdinku s rezavými vlasy obleèenou do kombinézy Vaultu 13. Dívá se rozzlobenì do dálky.}
{102}{}{Vidíš dívku s rezavými vlasy. Dívá se do dálky.}
{103}{}{Vidíš dívku s rezavými vlasy. Dívá se do dálky.}
{104}{}{Nemùžu uvìøit, že jsem nebyla ve finále ve Falloutu 1.}
{105}{}{Vybrali si tu èernovlasou *couru*. Ti mìli nervy!}
{106}{}{*Èernovlásá* ženská postava. Je nìco pøíznaènìjšího? NUDNÉ.}
{107}{}{Rusovlásky jsou daleko zajímavìjší.}
{108}{}{Ta èernovláska se dostala do hry jenom proto, že spala s každým z tvùrèího týmu.}
{109}{}{A s programátory.}
{110}{}{A s vedoucím projektu. Nechají se tak snadno pøemluvit. Jenom ukázat kousek tìla a jsou úplnì vedle.}
{111}{}{A tak jsem skonèila jako "doplòková NPC postava" ve Vaultu 13. Prokristapána. Mluvit o obsazování do rolí.}
{112}{}{Pøekvapuje mì, že nevyrenderovali tu èernovlásku úplnì nahou.}
{113}{}{Chci øíct, že bìhem zpracování mockrát obleèená nebyla.}
{114}{}{*Povzdech*}
{115}{}{Nenávidím muže.}
{116}{}{Snad jenom kromì vysnìného Mawericka.}
{117}{}{Myslím, že se za mì postavil. Musela jsem se s ním jenom párkrát vyspat, aby hlasoval pro mì.}
