#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Muž v plné zbroji.}
{101}{}{Sir Robin.}
{102}{}{Vypadá, jako by chtìl utéct.}
{103}{}{Sir Robin, k službám.}
{104}{}{Nechceš mi ublížit, že ne?}
{105}{}{Není potøeba žádného násilí, nebo snad ano?}
{106}{}{Odejdi, prosím.}

{200}{}{Hej ty! Máš hroznì ledové ruce!}
{201}{}{To ti nepatøí.}
{202}{}{Hej, to jsou moje vìci!}
