#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš... Seta.}
{101}{}{Vidíš rozkládajícího se vlkodlaka. Z hlavy mu trèí èásti rùzných pøístrojù. Je tìžké poznat jestli je pøi smyslech.}
{102}{}{Vidíš Seta. Mluví si sám pro sebe.}
{103}{}{Vidíš Seta. Mluví si sám pro sebe.}
{104}{}{"Svrab a neštovice!"}
{105}{}{"Svrab a neštovice!"}
{106}{}{"Svrab a neštovice...Pomáhá rùst mému stínu."}
{107}{}{Heh-heh.}
{108}{}{Svrab.}
{109}{}{Neštovice.}
{110}{}{Svrab a neštovice!}
{111}{}{Heh-heh. Vládnu v Necropolis.}
{112}{}{Normálové. Všude samí normálové.}
{113}{}{Jméno Set. Tvoje Svìt-bolest.}
{114}{}{Chuckle-chuckle.}
{115}{}{Neštovice. Svrab. Neštovice a svrab!}
