#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Za tyhle dostanu na trhu dobrou cenu.}
{101}{}{Zkus nepoškodit zboží.}
{102}{}{Z tebe bude osvícený otrok.}
{103}{}{To není dobrý.}
{104}{}{Ústup!}
{105}{}{Asi budu radši prodávat nábytek.}
{106}{}{Otrokáøi by na sebe nemìli navzájem útoèit.}
{107}{}{V cechu se o tom dozví!}
{108}{}{Co to dìláš?}
{109}{}{Mìl jsi štìstí?}
{110}{}{Sehnals nìjaké dobré otroky?}
{111}{}{Hledáme nové otroky.}
{112}{}{Tohle je naše území.}
