#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš alostnì vyhlíejícího spammera.}
{110}{}{Nevidíš absolutnì nic zajímavého.}

# Grim's Floats
{120}{}{Bude taky verze pro Mac?}
{121}{}{Chtìl bych multi-player!}
{122}{}{Všechny vás nenávidím!}
{123}{}{Ahhh!}
{124}{}{Mnì nemùeš ublíit!}
{125}{}{Jsem Grim Reaper, nemùeš mì zabít. Nejsem zábavnı.}
{126}{}{Chci tank!}
{127}{}{Kde je moje motorová pila?}
{128}{}{Neubliuj mi.}
{129}{}{Nechtìl jsem vypadat jako kretén.}
{130}{}{Nemyslel jsem ty vıhruky smrtí vánì.}
{131}{}{Promiò, Buffy!}
{132}{}{Promiò, Humusáku! Jen jsem chtìl, aby si mì nìkdo všiml.}
{133}{}{Chtìl bych síovou verzi!}
