#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš...Tandi.}
{101}{}{Vidíš roztomilou èernovlasou holèièku s bezstarostným výrazem. Zasnìnì hledí do dálky.}
{102}{}{Vidíš Tandi. Hledí zamyšlenì do dálky.}
{103}{}{Vidíš Tandi. Hledí zamyšlenì do dálky.}
{104}{}{Ahoj! Takže ty jsi potomek hrdiny z Falloutu 1. Super! Jsem Tandi. Ahoj!}
{105}{}{Nechtìla jsem to tenkrát øíkat, ale tvùj dìda byl moc hezkej! *Povzdech*}
{106}{}{Ian? Myslím, že poøád nìkde je i ve Falloutu 2. Nebo, že by tu lokaci zrušili?}
{107}{}{Vlastnì jsem slyšela, že jsem nìkde i ve Falloutu 2. Ale nechci, abys mì hledal... bylo by to pro nás oba zklamání.}
{108}{}{Mrzí mì, že ve Falloutu 1 jsem nemìla lepší bojové dovednosti. Myslím, že jsem tam v boji nebylo moc užiteèná.}
{109}{}{Øekni mi. Ještì udržuješ nìjaké kontakty s Tychem?}
{110}{}{Tak tam byla chyba, když jsi mì zachránil pøed bandity a odvedl mì k otci a on se strašnì vytoèil. Jo, to byl prùšvih!}
{111}{}{Pøidala bych se k tobì, ale èekám na otce, Aradeshe, až se tu objeví. Mìl tu už dávno být.}