#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš muže v nìjaké zbroji.}
{101}{}{Vidíš muže v nìjaké zbroji.}
{102}{}{Jeho zbroj je ponìkud rezavá.}
{103}{}{Plechovka oleje.}
{104}{}{Vøelé díky. Ani nevíš, jak dlouho už jsem tady byl zaseknutý. A to máš za to, že ses obtìžoval. Musím jít.}
{105}{}{Uhh, díky.}
{106}{}{Promiò, už musím bìžet. Uvidíme se jindy.}
