#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Chceš slyšet novı recept?}
{101}{}{Jakı?}
{102}{}{Krysí pøekvapení.}
{103}{}{Dobrı. Jak já udìlám?}
{104}{}{Chy krysu. Opatrnì; moc nezmáèknout.}
{105}{}{Jak? Moc nezmáèknout? Kdy bacit klackem, vdycky prasknout. Hroznı binec.}
{106}{}{Chceš slyšet recept nebo ne? Chytit krysu tvùj problém.}
{107}{}{Promiò.}
{108}{}{Jak já øíkal, chytit krysu. Povìsit za ocas na zeï.}
{109}{}{Nechat viset, a ocas odpadnout. Pak hotovo.}
{110}{}{Jíst rychle, kdy nechat sedìt dlouho, pøekvapení vylézt a uletìt.}
{111}{}{To asi bıt mòamka.}