#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš špinavého, neoholeného muže.}
{200}{}{Vidíš špinavou, vychrtlou ženu.}
{101}{}{Lovec.}
{102}{}{Nejlepší bude nejít moc blízko. Nìkterá zvíøata v jeho obleèení nevypadají moc èistì.}
{103}{}{Ahojky. Tudy pøes Lovcovo území moc èasto lidi neprochází. Co bys rád?}
{104}{}{Máš nìjaké kùže geckù na prodej?}
{105}{}{Jenom procházím.}
{106}{}{Ug.}
{107}{}{Mnoo, když si to tak spoèítám, tak ti mùžu prodat moje kùže. Aspoò to vyøeší mùj problém tahat se s nimi do mìsta.}
{108}{}{Co máš?}
{109}{}{Nevadí.}
{110}{}{Ug.}
{111}{}{Tady je co mám:}
{112}{}{Pravé gecko kùže.}
{113}{}{Kùže ze zlatého gecka.}
{114}{}{Vezmu si všechno co máš.}
{115}{}{Možná pøíštì. Nashle.}
{116}{}{S tebou se dìlají dobré obchody. Snad se uvidíme.}
{117}{}{Nashle.}
{118}{}{Vypadá to, že seš bez penìz. Co kdyby sis se mnou užila 5 minut. Já ti za to udìlám dobrou cenu.}
{119}{}{Vypadá to, že seš bez penìz. Co kdybych si s tebou na 5 minut užil chlape. Víš, co myslím. Mùžu ti zato dát výmìnou nìjaký kùže.}
{120}{}{Vypadá to, že seš bez penìz. Øekni co chceš, jestliže mì chytíš, ale v tìchhle lesích už žiju hodnì dlouho. Udìlám Ti dobrou cenu.}
{121}{}{Jistì.}
{122}{}{Nemáš šanci. Nashle.}
{123}{}{[Miria ti odpustí...nakonec. Ale na druhou stranu, pytlák ti dá nìjaké kùže.]}
{124}{}{[Po tomto zážitku se zdá, že Davin neutrpìl žádnou újmu na svém odìvu.]}
{125}{}{[Cítíš se špinavý a tvé pocity by se daly vyjádøit více slovy - ale dostal jsi nìjaké kùže geckù.]}
{126}{}{Nashle.}
{127}{}{[Zvedá nahoru svou pravou ruku a øíká] Jak. Sem mocný lovec. Lovím velké gecky. Nemám v úmyslu vstoupit na tvùj pozemek. Odejdi v míru. [Podává Ti kùže z geckù jako dar.]}
{128}{}{[KONEC]}
{129}{}{Už s tebou nebudu obchodovat.}
{130}{}{Ty zbabìlý prolhaný hajzle!}
{131}{}{Tohle je moje lovný teritorium. Vypadni odsud!}
{132}{}{Stáhnu z Tebe kùži zaživa!}
{133}{}{Nechám si tvojí hlavu jako trofej.}

{134}{}{Jedna kùže z pravého gecka: $}
{135}{}{Jedna kùže ze zlatého gecka: $}

{136}{}{OK, správèe. Vyhrál si.}
{137}{}{Pøeju Ti hodnì štìstí, musím jít zkontrolovat moje pasti na gecka.}
{138}{}{Myslím, že sem zaslechl, že mì volá Mom.}