#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Pocestný.}
{101}{}{Stùj! Bratøe pocestný.}
{102}{}{Potøebuju ukázat cestu. Pomùžeš mi?}
{103}{}{Kam máš namíøeno?}
{104}{}{Èím se zabýváš?}
{105}{}{Ug.}
{106}{}{No... nevím. Jsem tady prvnì. Už jsem byl na následujících místech.}
{107}{}{New Reno}
{108}{}{Vault City}
{109}{}{Redding}
{110}{}{The Den}
{111}{}{San Francisco}
{112}{}{New California Republic}
{113}{}{Nìjaký opuštìný dùl.}
{114}{}{Ne, už jsem tam byl. Každopádnì díky.}
{115}{}{New Reno -- to je super místo, kam se vydat. Sex, drogy a sázky. Co víc si èlovìk mùže pøát? Hned ti ukážu, kde to je.}
{116}{}{Díky.}
{117}{}{Vault City -- to je mìsto hlupákù. Naroste ti extra prst a hned se na tebe dívají jako na nìjakou zrùdu. Nikdy jsem tam nebyl, ale vím, kde to je.}
{118}{}{Díky.}
{119}{}{Redding... moc toho o tomhle mìstì nevím. Snad jenom to, že je to staré hornické mìsto. Rozprostírá se na severu. Malá teèka uprostøed tìch nejdivoèejších hor, které jsi vidìl.}
{120}{}{Díky.}
{121}{}{Držel bych se stranou od Denu, být tebou. Je to magnet na všechen póvl v okolí. Ukážu ti, kde to je, ale nedoporuèuju ti tam chodit.}
{122}{}{Díky.}
{123}{}{San Francisco. Hm... jediné co mùžu øíct je, že lidé tam jsou...divní. Nachází se na pobøeží.}
{124}{}{Díky.}
{125}{}{The New California Republic... tak to je hezké místo. Rád bych se tam jednou usadil. Èisté, pøíjemní lidé a dobøe udržované místo. Je to na tvé mapì právì tady.}
{126}{}{Díky.}
{127}{}{Jo a nedávno jsem narazil na opuštìný dùl. Myslel jsem že tam tak den dva zùstanu, ale pak se objevili vlci a já jsem usoudil, že bude lepší zmizet. Byla to smùla. Zdá se, že horníci odešli ve spìchu. Nechali tam po sobì hodnì vìcí. Nemám v úmyslu se tam vrátit, takže ti mùžu ukázat, kde to je.}
{128}{}{Díky.}
{129}{}{Oh... to nevadí. Jednoho dne jsem se rozhodl, že budu cestovat, a tak jsem tady.}
{130}{}{Možná bys mi mohl pomoci. Potøebuju ukázat cestu.}
{131}{}{Èím se zabýváš?}
{132}{}{Bylo pøíjemné si s tebou povídat.}
{133}{}{Sem tam dìlám pøíležitostnou práci. Ale vìtšinou jenom cestuju.}
{134}{}{Možná bys mi mohl pomoci. Potøebuju ukázat cestu.}
{135}{}{Kam máš namíøeno?}
{136}{}{Bylo pøíjemné si s tebou povídat.}
{137}{}{Tak teï už opravdu budu muset jít. Bylo pøíjemné si s tebou povídat.}
{138}{}{Možná se ještì potkáme.}
{139}{}{Chtìl bych do veèera dorazit do nejbližšího mìsta. Radši vyrazím.}
{140}{}{Radši už bych šel.}
{141}{}{Pøepad!}
{142}{}{Dneska už nemùžeš nikomu vìøit.}
{143}{}{Porušil jsi nepsaný zákon cestovatele.}
{144}{}{Je èas jít.}
{145}{}{Už jsem tady déle než je zdrávo.}
{146}{}{Musím vyrazit.}
