#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Obchodník.}
{101}{}{Willy.}
{102}{}{Uhlazenı potulnı obchodník.}
{103}{}{Buï pozdraven pøíteli. Jsem Willy a mám pro tebe urèitou nabídku.[Zdá se, e ète z nìjaké karty a po chvíli usneš.]}
{104}{}{Zzzzzzz...}
{105}{}{[Ospale otevíráš oèi a zjišuješ, e do tebe nìkdo kope.] Tak co? Máš zájem nebo ne?}
{106}{}{Zájem o co?}
{107}{}{Co?}
{108}{}{Tak tedy. Mùeš s tím krájet na plátky, na kostky a mùe se ti hodit na rùzné potvory. Je to skoro zadarmo a pro tebe by to bylo ještì levnìjší a pøišlo by tì to jenom na }
{109}{}{Je vyroben z toho nejlepšího døeva. Mùeš se s ním ohánìt po rùznıch potvorách a dret je tak v šachu. Pokud jsi dost šikovnı, mùeš s ním i házet. Je velmi aerodynamickı a pøi nárazu se nezlomí. Tak co na to øíkáš? Mùe bıt tvùj za pouhıch }
{110}{}{Tato zbraò je vyrobena z té nejlepší recyklované oceli. Jen si zkus , jak dobøe padne do ruky. A nemìj obavy. Naši konstruktéøi ji dobøe otestovali, aby byla bezpeèná a spolehlivá. ádnı zlodìj se zdravım rozumem se tì nepokusí okrást, kdy mu s ní zamáváš pøed nosem. A stál by tì pouze }
{111}{}{Tento malı skvost je vskutku jedineènı. Z dalekıch konèin...Jenom s tím takhle zamíøíš- Podívej, já nevím co to je. Chceš to nebo ne? Cena je }
{112}{}{Tenhle malı švihák jenom køièí. "Nezahrávej si se mnou!" Jenom pouhı pohled zaene tvé nepøátele. Je to skoro zadarmo za }
{113}{}{Vidím, e jsi typ, kterı si to s tou chátrou rád vyøizuje pìknì osobnì a zblízka. A tenhle malı pupínek je pøesnì to, co bys mohl potøebovat. Bude tvùj za }
{114}{}{Beru to.}
{115}{}{Nemám zájem.}
{116}{}{Jo, jasnì. Toho nebudeš litovat. Dobøe se s tebou obchodovalo. Mìj se.}
{117}{}{[Konec]}
{118}{}{Do prdele! Jaká ztráta èasu. No tak, ber to!}
{119}{}{[Konec]}
{120}{}{Zbyteènì jsem øeènil. $} #continue on 152
{121}{}{Jo.}
{122}{}{Ne.}
{123}{}{Hej. To jsi zase ty? Mám nìjaké zboí. Nemáš zájem?}
{124}{}{Jasnì. Poslechnu si co máš.}
{125}{}{Bez šance, Willy.}
{126}{}{Jo.}
{127}{}{Ne.}
{128}{}{Ber to! Nemám èas.}
{129}{}{Pøijï, a budeš mít nìjaké peníze.}
{130}{}{Bì pryè!}
{131}{}{ádné vracení penìz.}
{132}{}{ádná vımìna.}
{133}{}{ádnı úvìr.}
{134}{}{Zmiz! Nemám èas.}
{135}{}{ádnı chytrı pohyby.}
{136}{}{Bastarde!}
{137}{}{Pomùe tohle, abych dostal lepší cenu?}
{138}{}{Dobrá, sníím cenu.}
{139}{}{Co takhle 20% sleva?}
{140}{}{Co takhle 40% sleva?}
{141}{}{Co takhle 80% sleva?}
{142}{}{Dobrá, zadarmo. Vezmi si to!}
{143}{}{Willy}
{144}{}{George}
{145}{}{Mike}
{146}{}{Walter}
{147}{}{Charlie}
{148}{}{Freddy}
{149}{}{Mick}
{150}{}{Smitty}
{151}{}{Jack}

{152}{}{. Máš zájem nebo ne?}
{200}{}{.}