#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Za Jednotu!}
{101}{}{Odrazte je, chlapi!}
{102}{}{Zabte vetøelce!}
{103}{}{Braòte mìsto!}
{104}{}{Pohyb! Pohyb! Pohyb!}
{105}{}{Pozor! Rangeøi!}
{106}{}{Vyžeòme je odsud!}
{107}{}{Ach... právì, když jsem si myslel, že už jsme v bezpeèí. Už nejsme! Už nejsme!}
{108}{}{Jdeme na to!}
{109}{}{Jednej s lidmi s respektem.}
{110}{}{Neporušuj zákon.}
{111}{}{Pokud by tì napadlo dìlat potíže, vzpomeò si na nás. Chovej se slušnì a Markus se tak bude chovat taky.}
{112}{}{U nás v Broken Hills žijí mírumilovní lidé, ale umíme i bojovat.}