#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Je tøeba varovat Lynette!}
{101}{}{Je tøeba varovat Vault City!}
{102}{}{Cizácký zmetci...}
{103}{}{Zvrhlá špína...}
{104}{}{Je èas vyplít tu cizáckou špínu... Chcípnìte cizáci!}
{105}{}{Co pohledáváš v blízkosti Vault City?}
{106}{}{Co máš na práci v blízkosti Vault City?}
{107}{}{Tohle je poøád ještì území Vault City.}
{108}{}{Dávej si pozor.}
{109}{}{Vault City není útoèištìm pro každého. * Takže pokraèuj.}
{110}{}{Pro takové, jako jsi ty je dobrý Den.}
{111}{}{Radím ti, aby ses tam hned vydal.}
{112}{}{Buï zdráv, obèane.}
{113}{}{Mùžeme pro tebe nìco udìlat, obèane?}
{114}{}{Potøebuješ doprovod do Vault City?}
{115}{}{Co dìláš tak daleko od Vault City, obèane?}
{116}{}{Báli jsme se, že by ti mohl nìkdo ublížit, obèane.}
