#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš Buffy, èlenku Humusákù.}
{101}{}{Vidíš Doombot, èlenku Humusákù.}
{102}{}{Vidíš Panoply, èlenku Humusákù.}
{103}{}{Vidíš Lerk, èlenku Humusákù.}
{104}{}{Vidíš Ymir, èlenku Humusákù.}
{105}{}{Vidíš Iguana Eater, èlena Humusákù.}
{106}{}{Vidíš Night Owl, èlena Humusákù.}
{107}{}{Vidíš Shadow Dancer, èlena Humusákù.}
{108}{}{Vidíš Amish Commando, èlena Humusákù.}
{109}{}{Vidíš Alexand the Killer Bee, èlena Humusákù.}
{110}{}{Vidíš Hatchetman, èlena Humusákù.}
{111}{}{Vidíš BlueCross, èlena Humusákù.}

# Examines
{113}{}{Vidíš Buffy, velmi krásnou, inteligentní a sebejistou dívku. První enu Humusákù.}
{114}{}{Vidíš Doombot. Je to uèinìná bohynì a sestra Buffy. Vypadá skoro jako Marie Osmond.}
{115}{}{Vidíš Panoply. Vypadá šibalsky. Její oèi prozrazují lehkı pøípad demence.}
{116}{}{Vidíš Lerk, Vùdkyni SWAT tımu Humusákù - Umìlkyni Humusákù - Mluví se stromy.}
{117}{}{Vidíš Ymir, básníøku od protinocù a spoluzakladatelku Vyvrhelù poezie - uèitelka  Humusákù.}
{118}{}{Vidíš Iguana Eater, Vysokı reprezentant  Smeet Lite.}
{119}{}{Vidíš Night Owl, Toho, kterı dohlíí nad spícími - spoluzakladatel Vyvrhelù poezie.}
{120}{}{Vidíš Shadow Dancer, pøedstavitele gotiky v klubu Vyvrhelù poezie - kupodivu je hodnì podobnı Kevinu Baconovi.}
{121}{}{Vidíš Amish Commando, komisaøe z Blunt Force Trauma, zástupce velitele SWAT tımu Humusákù.}
{122}{}{Vidíš Alexanda the Killer Bee, Je jemnı a inteligentní -Vrchní písaø Humusákù.}
{123}{}{Vidíš Hatchetman, Zbrojíøe Humusákù -Zakladatel ohòù - Správce vìdìní Shadowrun.}
{124}{}{Vidíš BlueCross, Niší duchovní Humusákù - Øeditel vıroby.}

# UV Leaving Floats
{200}{}{Humusáci opìt spasí den!}
{201}{}{Smrt je pro nìj pøíliš dobrá.}
{202}{}{A zùstaò v hrobì!}
{203}{}{Vesnice je opìt bezpeèná!}
{204}{}{Chráníme nevinné a bráníme mír.}
{205}{}{Odcházíme hlídat odpad. Musíme je chránit pøed spamery.}
{206}{}{Pøidej se k nám!}
{207}{}{Rozkouskování je prima odplata...}
{208}{}{A pøišel Ïábel a vidìl jak je dobro ošklivé...}
{209}{}{Odplata je kurevská, viï?}
{210}{}{Grim našel vyuití - hnojivo.}
{211}{}{To je za pouívání mıdla...}
{212}{}{Mizíme!}
{213}{}{'Tento dùm je èistı.'}
{214}{}{Mùu do nìj pro jistotu šouchnout klackem?}
{215}{}{Neèekej na nás!}
{216}{}{Je to špinavá práce, kterou dìlám opravdu rád!}
{217}{}{Zpìt na patrolu!}
{218}{}{Humusáci. Záruka míru v proklaté pustinì.}
{219}{}{Dostal, co si zaslouil.}
{220}{}{Já tì dohoním!}

# UV Combat Floats
{300}{}{Mıdlo? Nepotøebujeme!}
{301}{}{Povstaòte humusáci! Zniète Spammera!}
{302}{}{Smrt Spammerovi!}
{303}{}{To je za ohroování lidí!}
{304}{}{Teï zemøeš Grim Reaper.}
{305}{}{Vrátíš se do hrobu!}
{306}{}{Genová líheò potøebuje trochu chlóru.}
{307}{}{Èas odplaty!}
{308}{}{Teï to schytáš.}
{309}{}{Humusák je tady, aby ochránil ostatní pøed takovım svinstvem, jako jsi ty!}
{310}{}{Nechejte lidi na pokoji!}
{311}{}{Ve ŠPÍNÌ je síla!}
{312}{}{Jsme Nemytí, ale jsme tady abychom se oèistili!}
{313}{}{Tentokrát nám  nemùeš uniknout!}
{314}{}{Ochraòte Vyvoleného pøed Spammerovou pitomostí!}
{315}{}{Vyvolenı! Pøipoj se k nám!}
{316}{}{HUMUSÁCKÁ ODPLATA!}
{317}{}{Nikdy nebudeš 'humusácky' dìtinsky hloupı!}
{318}{}{Nemáš šanci!}
{319}{}{Ještì nejsme hotovi!}
{320}{}{Na tento den jsem èekal stráááášnì dlouho..}

# 1 Buffy Personal Floats
{400}{}{To je za vyhroování!}
{401}{}{To je tutovka. Ty bys neublíil dívce, e ne?}
{402}{}{'Odplatu je nejlepší servírovat za studena.'}
{403}{}{Jsem Buffy... tvùj toast.}

# 2 Doombot Personal Floats
{405}{}{Nikdo nebude vyhroovat Doombot!}
{406}{}{Grim Buster!}

# 3 Panoply Personal Floats
{410}{}{Jenom guanabana se mùe srovnávat s pocitem z tohoto vítìzství...}

# 4 Lerk Personal Floats
{415}{}{Vesnice je v pohodì, ale ty jsi mì velmi, velmi rozèílil.}

# 5 Ymir Personal Floats
{420}{}{Svım jednáním jsi zostudil svou zemi naposled!}

# 6 Iguana Eater Personal Floats - None

# 7 Night Owl Personal Floats
{430}{}{Uspím tì navìky!}

# 8 Shadow Dancer Personal Floats
{435}{}{Jsme na cestì do horoucích pekel a já vás vedu.}
{436}{}{Pojï sem mé dítì, a ti ulevím od tvé bolesti.}
{437}{}{Jsi mrtvı. Jenom o tom ještì nevíš.}

# 9 Amish Commando Personal Floats
{440}{}{Vezmi si!}
{441}{}{Nedáš si?}
{442}{}{Ne do oblièeje, ne do oblièeje!}

# 10 Killer Bee Personal Floats
{445}{}{Dante nepopsal peklo, které na tebe posílám...}

# 11 Hatchetman Personal Floats
{450}{}{Zbranì! Zbranì! Zbranì! Kde jsou moje zbranì!}
{451}{}{Jo. Jsem blázen. Vypoøádej se s tím.}

# 12 BlueCross Personal Floats - None
