#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš... bílého hrdinu.}
{101}{}{Vidíš svalnatého bìlocha v overalu Vaultu 13. Vypráví pøíhodu a smìje se.}
{102}{}{Vidíš bílého hrdinu. Smìje se.}
{103}{}{Vidíš bílého hrdinu. Smìje se.}
{104}{}{Bylo skoro nemožné udržet ve Falloutu 1 naživu psa; hlavnì ke konci.}
{105}{}{Prostì nebyl na konec hry dost tvrdý!}
{106}{}{Mìl jsem toho psa rád. Byl bych ho rád vidìl v závìreèném filmu.}
{107}{}{Jeden z pøekladatelù Falloutu 2, nìjaký Hightower, mìl následující taktiku, jak udržet psa naživu.}
{108}{}{Zamkl ho v místnosti se silovým polem, aby ho udržel mimo boj.}
{109}{}{Blbý bylo, dìlat to v každý úrovni, aby na nìj nemohli mutanti.}
{110}{}{Myslím, že uspìl.}