#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš... bílého hrdinu.}
{101}{}{Vidíš svalnatého bìlocha v overalu Vaultu 13. Vypráví své záitky a smìje se.}
{102}{}{Vidíš bílého hrdinu. Smìje se.}
{103}{}{Vidíš bílého hrdinu. Smìje se.}
{104}{}{Jo.. to mùj hráè byl TAK pitomej, e...}
{105}{}{Vem tohle, vem tohle -- myslí si, e náboje do brokovnice jsou vodní èip a odnese je Správci...}
{106}{}{Jakı idiot!}
{107}{}{Jednou za mì hrál jeden z tìch zabednìnıch násilníkù. A øeknu vám...}
{108}{}{Na chvilku to byla zábava, ale brzo to omrzí. Není tam moc zabíjení ne se unavíš.}
{109}{}{Strávili jsme skoro tøi hodiny nastavováním charakteru, ne se mùj hráè KONEÈNÌ rozhodl hrát.}
{110}{}{Ian byl pro mì nebezpeènìjší, ne nepøátelé, proti kterım jsme bojovali. Doufám, e je mrtvej, a je kde je.}
{111}{}{Podívej na ty svaly co mám jako postava. Je to tak strašnì pøehnanı, e je to a smìšnı!}