#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Zabíjení je forma umìní.}
{101}{}{Zemøít je tvùj osud.}
{102}{}{Život a smrt jsou stejné.}
{103}{}{Zemøi se ctí!}
{104}{}{Pøišel mùj èas umøít.}
{105}{}{Zemøít v bitvì je pocta. Jo je to tak!}
{106}{}{Je tøeba víc studovat.}
{107}{}{Utéct je potupné. Zemøít by bylo horší.}
{108}{}{Lepší živý zbabìlec, než mrtvý hrdina.}
