#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš osobu v legraèním pyamu.}
{101}{}{Vidíš Shi, mìstského obyvatele.}
{102}{}{Tato osoba vypadá jinak ne kdokoliv jinı, koho jste vidìli pøedtím. Nevypadá, e se o vás nìjak zajímá.}
{103}{}{Nejsi vyzvìdaè, e ne?}
{104}{}{Kdo jsi?}
{105}{}{Ryby a moøské øasy. To je vše, co máme.}
{106}{}{Hehe, koukni se na ty legraèní kulaté oèi!}
{107}{}{Vypadáš jako hubologista.}
{108}{}{Nech nás v klidu.}
{109}{}{Dlouhé ití Lo Panovi!}
{110}{}{Dolù s Dragonem!}
{111}{}{Lo Pan je hrdina.}
{112}{}{Pozor na Dragona. Má problém.}
{113}{}{Ti pankeøi jsou vdycky tak hlasití.}
{114}{}{Práce, práce a práce. Rıe, rıe a rıe. ::povzdech::}
{115}{}{Není v ivotì víc ne tohle?}
{116}{}{Jsme chytøejší ne si myslíš.}
{117}{}{Podívej! Lao wai!}
{118}{}{Vítej v San Franciscu.}
{119}{}{Vypadáš jako osoba s rovnou hlavou.}
{120}{}{Lo Pan mùe vyuít tvojí pomoci.}
{121}{}{Neubliuj lidem v èerveném, lao wai.}
{122}{}{Lao wai znamená "cizinec".}
{123}{}{Jsi na naší stranì, správnì?}
{124}{}{Zabij pro nás Dragona, ano?}
{125}{}{Tvoje pøítomnost je nám ctí.}
{126}{}{Náš vùdce! Sklíèenı!}
{127}{}{Musíme se pomstít za Lo Pana!}
{128}{}{Kdo nás povede k velikosti, kdy Lo Pan zemøe?}
{129}{}{Co bychom mìli dìlat nyní?}
{130}{}{Jsme neèestní. Mìli bychom bıt mrtví jako Lo Pan.}
{131}{}{ivot nemá ádnı vıznam.}
{132}{}{Jestli Lo Pan zemøe, naše sny budou znièeny.}
{133}{}{Lo Pan byl poslední velkı vùdce.}
{134}{}{Dragon je mrtvı! Lo Pan je vítìz!}
{135}{}{Smìjte se poraenım!}
{136}{}{Dragon padl!}
{137}{}{Lo Pan! Lo Pan! Lo Pan!}
{138}{}{Jsme vítìzi!}
{139}{}{Dragon je mrtev. Jé!}
{140}{}{Práce, práce a práce. Rıe, rıe a rıe. ::povzdech::}
{141}{}{Není v ivotì víc ne tohle?}
{142}{}{Jsme chytøejší, ne si myslíš.}
{143}{}{Podívej! Lao wai!}
{144}{}{Císaøùv mluvèí! Mrtev! Mìsto se rozpadne!}
{145}{}{Co se stane nyní?}
{146}{}{Doufám, e nás teï nepøedbìhnou divoši.}
{147}{}{Dobré vdy umírá mladé.}
{148}{}{Doufám, e mùeme pøeít bez Kena Lee.}
{149}{}{Slyším, e Ken Lee byl jedinı, kdo Císaøe usmìrnit.}
{150}{}{Slyším, e Císaø byl pouhou loutkou Kena Lee. }
{151}{}{Moná Lo Pan by mohl vzít flek Kena Lee...}
{152}{}{Práce, práce a práce. Rıe, rıe a rıe. ::povzdech::}
{153}{}{Není v ivotì víc ne tohle?}
{154}{}{Jsme chytøejší, ne si myslíte.}
{155}{}{Podívej! Lao wai!}

{163}{}{Zabils AHS-9? Jé!}
{164}{}{Ti hubologisti mi nahání husí kùi.}
{165}{}{Prokázal jsi nám velkou slubu.}
{166}{}{Smrt hubologistùm!}
{167}{}{Toto zaene ty hubologisty odsud.}
{168}{}{Pitomí hubologisti, neumí si ani ochránit svého vùdce.}
{169}{}{Hubologisti, radìji se nám nepokoušejte mstít.}
{170}{}{Domnívám se, e nejsi vyzvìdaè.}
{171}{}{Praseèí synu! Zemøi!}
{172}{}{Zahanbil jsi svou rodinu!}
{173}{}{Opus nás, lao wai!}
{174}{}{Copak jsi u neudìlal dost zkázy?}
{175}{}{Nenávidím Tì!}
{176}{}{Opus toto mìsto!}
{177}{}{Jdi domù ke svım lidem!}
{178}{}{Nezastiòuj mùj ivot svım oblièejem!}
{179}{}{Co mì bude stát, abych se tì zbavil?}
{180}{}{Pomoc! Pomoc!}
