#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš pankáèe s polovièním úsmìvem.}
{101}{}{Vidíš Badgera.}
{102}{}{Vidíš pankáèe s polovièním šklebem na jeho oblièeji.}
{103}{}{:::Øve nahlas:: Cóó chceeš?}
{104}{}{::øev:::}
{105}{}{Kdo ty?}
{106}{}{Kdo jsi?}
{107}{}{Mùeš mi øíct nìco o tomhle tankeru?}
{108}{}{Co tu dìláš?}
{109}{}{Rád bych, aby ses mi dostal do poèítaèe.}
{110}{}{Jak to jde?}
{111}{}{Nic. Hezké krknutí.}
{112}{}{::Vyrobil další mohutné krknutí::}
{113}{}{::Krknutí nahlas::}
{114}{}{Sprosák.}
{115}{}{::Vychrlí šílené krknutí, které ve své hlasitosti a hloubce vzdoruje i nebi::}
{116}{}{::Potlesk::}
{117}{}{Jmenuju se Badger. Míval jsem kapelu. ::povzdech:: Jmenovali jsme se  "Tam jsme èadili". Teï dìlám poèítaèovıho technika tady v San Fran.}
{118}{}{Dìkan!}
{119}{}{Do jakého poèítaèového odvìtví dìláš?}
{120}{}{Vsadím se, e ta vaše kapela stála za hovno.}
{121}{}{Byla vùbec dobrá?}
{122}{}{Dík. Èau.}
{123}{}{Dobøe.}
{124}{}{Ahoj!}
{125}{}{Mìl by sis o tom promluvit s Markem nebo Kapitánem.}
{126}{}{Kde najdu Marka?}
{127}{}{A kde najdu kapitána?}
{128}{}{Jsem místní poèítaèovı génius.}
{129}{}{Do jakıch poèítaèù dìláš?}
{130}{}{Díky. Nashle.}
{131}{}{Neotravuj mì. ::Prdí:: Pracuji na tom, staèí?}
{132}{}{V poøádku. Dej mi vìdìt, a to bude.}
{133}{}{Øeknìme, e jsem informaèní záchrannı specialista.}
{134}{}{Mùeš pro mì zachránit nìjaké vìci?}
{135}{}{Co to znamená?}
{136}{}{Vyser si voko.}
{137}{}{Hej!}
{138}{}{Taky si naser.}
{139}{}{To ti povím! Poøádnì jsme to roztoèili! Náš zpìvák byl... ehm... kus "chlapa", a Aaron se poøád potil, a všechno ostatní byla Toddova chyba. Ale byli jsme dobøí.}
{140}{}{To je zlı, e u nehrajete. Rád bych si vás poslechl.}
{141}{}{Ehm. Jistì. Mám více otázek.}
{142}{}{Vsadím se, e jste chlastali.}
{143}{}{Obvykle mùeš najít Marka dole v baru.}
{144}{}{Díky. Mám více otázek.}
{145}{}{Díky. To je vše.}
{146}{}{Kapitán je obvykle na mùstku. Prostì jdi nahoru po schodech vedle baru.}
{147}{}{Díky. Mám víc otázek.}
{148}{}{Díky. To je vše.}
{149}{}{Ano, ale bude tì to nìco stát.}
{150}{}{Jaká je tvoje cena?}
{151}{}{Ano, jasnì. Musím jít.}
{152}{}{To znamená, e mùu najít údaje, které potøebuješ.}
{153}{}{Mùeš pro mì nìco udìlat?}
{154}{}{Aha. Skvìlé. Mám více otázek.}
{155}{}{Vidím. Díky.}
{156}{}{Jo, to klidnì mùeš. Ale teï tu mám práci.}
{157}{}{Poèkej. Mám více otázek.}
{158}{}{Díky. Ahoj.}
{159}{}{Myslím, e tì mám rád natolik, e to pro tebe teï mùu udìlat. Koho chceš abych navštívil?}
{160}{}{Hubologisty.}
{161}{}{Shi.}
{162}{}{Ani jednoho. Jenom zkouška.}
{163}{}{Pro tebe to udìlám zdarma, za záchranu mé dívky. Bude to chvíli trvat, myslím. Na koho chceš, abych zaútoèil?}
{164}{}{Hubologisty.}
{165}{}{Shi.}
{166}{}{Ani na jednoho. Jen tì zkouším.}
{167}{}{Musíš mi mi nejdøív udìlat laskavost. Má dívka se ztratila nìkde tady v tankeru. Najdi mi jí a já to udìlám.}
{168}{}{Máš to mít. Nashle.}
{169}{}{Zapomeò na to. Ahoj.}
{170}{}{To je jako ukrást dìcku lízátko. Nikdy mì nenajdou. Co od nich chceš?}
{171}{}{Super. Mám více otázek.}
{172}{}{Skvìlé. Vrátím se.}
{173}{}{Mùu je dostat. Ale a moc dobøe si chrání své informace a mají i slušnı pátrací systémy. Oprvadu chceš, abych po nich šel?}
{174}{}{Dobrá, hodnì štìstí. Mám více otázek.}
{175}{}{Mnoho štìstí. Vrátím se pozdìji.}
{176}{}{Jo, ale najdi mou dívku a pak si popovídáme.}
{177}{}{Dobrá, dobrá.}
{178}{}{Je mrtvá? Je MRTVÁ? Jak zemøela? Ne, poèkej... neøíkej mi to. Dej mi pár hodin, abych se dal dohromady.}
{179}{}{Jistì, jistì.}
{180}{}{Kašli na to. Máme hovno na práci.}
{181}{}{V poøádku. Teï je mi líp.}
{182}{}{Dobrá. Potøebuji se tì nìco zeptat.}
{183}{}{Dobrá pro tebe. Nechtìl sem si s tebou povídat.}
{184}{}{Dìkuji ti, dìkuji ti, dìkuji ti. Nemohu ti dost dobøe podìkovat za to, es jí zachránil. Co chceš?}
{185}{}{Mám nìjaké otázky.}
{186}{}{Tvá vdìènost mi staèí. Nashle.}
{187}{}{OK, dostal sem se do poèítaèù Shiù. Nevím, ale jestli jsem to zvládl nepozorovanì. Myslím, e nejlíp bude kdy se na nìjakı èásek schovám. Chceš nìco jiného?}
{188}{}{Ano.}
{189}{}{Ne. Ahoj.}
{190}{}{Dostal jsem Hubologisty. ádnı problém. Potøebuješ nìco jiného?}
{191}{}{Ano.}
{192}{}{Ne. Ahoj.}
{193}{}{Právì jsi udìlal velkou chybu, kámoši. Právì jsem proti tobì skrz jejich poèítaèe poštval Shi i Hubologisty. V San Franciscu jsi skonèil. }
{194}{}{Hádám, e bych tì tedy mìl oddìlat.}

{195}{}{Dej mi pár hodin, abych se dal dohromady.}
{196}{}{Chceš, abych sem se dostal do zformátovaného poèítaèe? Informace jsou pryè. To se nemìlo stát.}

{197}{}{Chystám se odsud vypadnout.}
{198}{}{Rád tì zas vidím.}

{199}{}{Hledám nìjaké palivo.}
{200}{}{Slyšel jsem, e Hubologisti mají nìjaké palivo a mohl bych se ti podívat do jejich poèítaèe.}
{201}{}{Shi vlastní všechno palivo v okolí. Mohl bych trochu zamotat bilanci jejich hlavnímu poèítaèi.}
{202}{}{Mùeš?}

{203}{}{Co chceš?}
{204}{}{Badger od pankáèù, pøedpokládám?}
{205}{}{Zahanbil jsi našeho Císaøe naposledy!}
{206}{}{Myslím, e pùjdu do mìsta sehnat nìjaké pamlsky pro Lao Chou.}
{207}{}{Tolik pro spravedlivé soudní pøelíèení. Hmmm...}
{208}{}{Trotle, prober se. Jenom jsem chtìl nìjaké sladkosti.}

{209}{}{Mùeš pøemístit palivo z jejich vesmírné lodì do tankeru?}
{210}{}{Mùeš mi sehnat kopii jejich vertibird plánu?}
{211}{}{Mùeš pøemístit palivo a sehnat mi ty plány?}
{212}{}{Ano, potøebuji to co mají.}
{213}{}{Ále, pøijdu na nìjakı jinı zpùsob.}
{214}{}{V poøádku, ale pro fanouška to není problém.}
{215}{}{Mùeš pøemístit palivo z jejich zásob do tankeru?}
{216}{}{Nevadí, udìlám to jinım zpùsobem.}
{217}{}{Nevadí.}
{218}{}{V poøádku. Zastav se tu za den nebo dva a já ti dám vìdìt.}
{219}{}{Dostal jsi, co potøebuju?}
{220}{}{Jo, mám palivo.}
{221}{}{Jo, mám plány vertibirdu.}
{222}{}{Jo, mám palivo a ty plány.}
{223}{}{Díky moc. Nashle.}