#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš plešatého pankáèe.}
{101}{}{Vidíš Chipa. Vypadá lépe.}
{102}{}{Vidíš plešatého pankáèe. Vypadá víc odpoèinutì.}
{103}{}{Oh, má støeva... au, au, au.}
{104}{}{Duts?}
{105}{}{Owie?}
{106}{}{Co to s tebou je?}
{107}{}{Bolí tì nìco? Ha ha ha.}
{108}{}{Kdo jste?}
{109}{}{Máte pro mì nìjaké informace o mıch lidech?}
{110}{}{Och, moje støeva. Strašnì trpím. Prosím, nechte mì o samotì.}
{111}{}{Dobøe.}
{112}{}{Co to se mnou je? Já ti to povím: To je jak jsem se opil minulı tıden, zaèal jsem hrát s Lao Chou a prohrál. Byl jsem tak opilı, e jsem vsadil mou slezinu. Teï ji má on a já ji potøebuji zpátky.}
{113}{}{Tys PRODAL tvoji slezinu?}
{114}{}{To je pøíliš zlé.}
{115}{}{Ty musíš bıt pìknı hlupák.}
{116}{}{Jé, potøebuji nìjaké informace místo tvého vzdychání.}
{117}{}{::lapá po dechu:: Jdi do prdele.}
{118}{}{::lapá po dechu:: Seru na tebe.}
{119}{}{Jo, cokoliv.}
{120}{}{Hej, zmìnil jsem rozhodnutí. Chci ti pomoct.}
{121}{}{Ee, prodal jsem to. Byl jsem opilı! Navíc si myslím, e Lao Chou dal nìjakı Jet do mého pití. Potøebuji mou slezinu zpátky, protoe chytám nákazy.}
{122}{}{Hej, tys ji ztratil. Je to tvùj problém. Vypoøádej se s tím.}
{123}{}{Dobøe, sakra, podívám se ti.}
{124}{}{Ano, to je to. Potøebuji mou slezinu zpátky, protoe teï chytám nákazy.}
{125}{}{Hej, tys ji ztratil. Je to tvùj problém. Vypoøádej se s tím.}
{126}{}{Dobøe, zatracenì, podívám se po tom.}
{127}{}{To opravdu oceòuji. Jdi a promluv s Lao Chouem, obchodníkem a øekni mu, e potøebuji mou slezinu zpátky.}
{128}{}{Vrátím se.}
{129}{}{Jsem Chip. A strašnì trpím.}
{130}{}{Co to s tebou je?}
{131}{}{Trpíš? He, he, he.}
{132}{}{To je pøíliš špatné. Zatím.}
{133}{}{Informaci? Je mi zle a ty chceš informaci?}
{134}{}{Co to s tebou je?}
{135}{}{Trpíš? He, he, he.}
{136}{}{Zapomeò na to.}
{137}{}{Našel u jsi mou slezinu?}
{138}{}{Ano. Dr. Wong Yi Tze ji má a dá ti ji zpìt. Jdi si s ním o tom promluvit.}
{139}{}{Jo. Jdi zkontrolovat sbor Dr. Wonga.}
{140}{}{Tak trochu. Dr. Wong Yi Tze ji má. Nechce mi ji dát.}
{141}{}{Našel jsem, kde je, ale myslím, e Dr. Wong ji snìdl.}
{142}{}{Ne, ještì ne. Ale sní ji.}
{143}{}{Ne, vlastnì, já se nedívám.}
{144}{}{V poøádku. ::supìní:: Ne to udìlám, moná bychom mìli najít zpùsob, jak bych ji dostal zpìt. Promluv s Dr. Fung o tom, ano? Díky.}
{145}{}{V poøádku.}
{146}{}{Ne.}
{147}{}{Opravdu si cením toho, co pro mì dìláte. Já to nezapomenu.}
{148}{}{ádnı problém.}
{149}{}{Dude, opravdu nemohu sehnat místa bez vynaloení námahy. Jestli mi nepomùeš, budu znièenı.}
{150}{}{Dobrá. Pùjdu a promluvím s Fungem.}
{151}{}{Dobrá. Stejnì mì ani trochu nezajímáš.}
{152}{}{Jestli v tom mùeš nìco udìlat... zabij ho, nebo do nìj nahusti nìjakı rozumy nebo nìco... bez sleziny umøu.}
{153}{}{Uvidím, co se dá dìlat.}
{154}{}{Lituji, chlape. Myslím, e jsi zkonèil. Nemohu pomoci.}
{155}{}{Bez sleziny umøu. Stejnì ti dìkuji za pomoc.}
{156}{}{Našel jsem ji. Jdi domù k Dr. Wongovi.}
{157}{}{Oh, já to zatáhnu. Jdi k Fungovi.}
{158}{}{ádnı problém. Mnoho štìstí.}
{159}{}{Mluvil jsi s Fungem?}
{160}{}{Jo, øíká, e ti jí pøišije zadarmo.}
{161}{}{Jo a chce po mnì $1,000.}
{162}{}{}
{163}{}{Skvìle. Máš nìjaké váné známosti. Pøijï zítra a uvidím, jak ti mohu pomoci.}
{164}{}{Máš to.}
{165}{}{Mùeš mì zaloit?}
{166}{}{Jo, asi jo.}
{167}{}{Ne.}
{168}{}{Opravdu to oceòuji. Pøijï zpátky zítra a uvidím, jak ti mohu pomoci.}
{169}{}{Ty lépe.}
{170}{}{Nemohu si to sám dovolit. Domnívám se, e umøu.}
{171}{}{Och, dobrá, zaplatím to za tebe.}
{172}{}{Drsné. Jsem na dnì.}
{173}{}{Nemohu ti vylíèit, jak se cítím. Je to mnohem lepší. Take, co bylo to, co jsi ode mì poslednì chtìl?}
{174}{}{Jak øídíš tenhle èlun?}
{175}{}{Víš, kde jsou mí lidé?}
{176}{}{Potøebuji udìlat nìjakou práci na poèítaèi.}
{177}{}{Teï zrovna nic, díky. Ahoj.}
{178}{}{Promluv s Kapitánem. Bydlí v kanceláøi nahoøe.}
{179}{}{Díky. Více otázek...}
{180}{}{Díky. Ahoj.}
{181}{}{Vzali to na západ, pøes vodu. Nejlíp se tam dostaneš, kdy rozbìhneš tenhle škopek.}
{182}{}{Díky. Víc otázek...}
{183}{}{Díky. Ahoj.}
{184}{}{Práce na poèítaèi? Kdy to nemùeš sehnat od Shi nebo hubologistù, promluv si s Badgerem. Je to sviš.}
{185}{}{Díky. Více otázek...}
{186}{}{Díky. Ahoj.}
{187}{}{Hovno. Promluv s hubologisty nebo Shi. Je-li Badger mrtev, nemám ponìtí.}
{188}{}{Díky. Více otázek...}
{189}{}{Díky. Ahoj.}
{190}{}{Scumbag.}
{191}{}{Budeš potøebovat nìjaké oblbováky na bolest.}
{192}{}{Dirtball. Já Tì pøepracuji.}
{193}{}{Vidíš plešatého pankáèe.}
{194}{}{Vidíš Chipa. Vypadá, e hodnì trpí.}
{195}{}{Vidíš plešatého pankáèe. Drí se na boku a lapá po dechu pøi bolesti.}

{196}{}{V poøádku. Promluvím s Fungem.}
{197}{}{ádné štìstí ohlednì mé sleziny?}
{198}{}{Jo a chtìl $1000 -- ale já jsem za tebe zaplatil.}
{199}{}{Díky za tvou pomoc, kámo.}
{200}{}{Kámo, slyšel jsem, e jsi našel mou slezinu. Mluvil jsi s Dr. Fung o navrácení sleziny zpìt do mého tìla?}
