#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš muže Shi, který se mraèí.}
{101}{}{Vidíš Dr. Jing Tie Gahnga}
{102}{}{Vidíš Shi muže s laboratorním pláštìm.}
{103}{}{Kdo jste? Co chcete?}
{104}{}{Có?}
{105}{}{Kdo JSTE?}
{106}{}{Jsem }
{107}{}{Po tom ti je úplný hovno.}
{108}{}{Nic. Teï odcházím.}
{109}{}{Nepatøíš sem, pokud jsi hloupý. Utíkej pryè, než zavolám stráže.}
{110}{}{Ty mi opravdu nerozumíš, viï? Možná, že budeš rozumìt strážným. Stráže! Vetøelec!}
{111}{}{-hotovo-}
{112}{}{Jsem Jing Tie Gahng. Jsem odpovìdný za chemickou laboratoø Ocelový Palác... a vy jste pøerušil dùležitou práci. Odejdìte prosím. TEÏ -- než zavolám stráže.}
{113}{}{Jdi napøed a zavolej je, starochu.}
{114}{}{Dobrá, dobrá. Odcházím.}
{115}{}{Dobøe,}
{116}{}{Ano. Jsem tady, abych získal palivo pro Poseidon Oil tanker.}
{117}{}{Rád bych vìdìl, co tady dìláte.}
{118}{}{Jsem tady, abych získal palivo pro hubologisty.}
{119}{}{Ne. Právì odcházím.}
{120}{}{Ach, ale vidíš, tohle je moje práce. To je má laboratoø. Nyní objasnìte, co chcete.}
{121}{}{Jsem tady, abych získal palivo pro Poseidon Oil tanker.}
{122}{}{Rád bych vìdìl, co tady dìláte.}
{123}{}{Jsem tady, abych získal palivo pro hubologisty.}
{124}{}{Ne. Právì odcházím.}
{125}{}{Chceš palivo pro tanker? A já chci zase tvrzenou energo zbroj. Chápu Hubologisty, ale jeden z nich jménem Crocket má postup, kterým mùže upgradovat obvyklou soupravu energo brnìní. Sežeò mi takovou soupravu a já ti palivo nasmìruji kam budeš chtít.}
{126}{}{Udìlám to.}
{127}{}{Nemùžu nic slíbit.}
{128}{}{Mám zde jedno právo.}
{129}{}{Vytváøím chemické slouèeniny a prostøedky pro Císaøe a pro Císaøského rádce, Kena Lee. Právì teï pracuji na palivových derivátech a polymerech, které budou schopny odolat velkému nátlaku. Samozøejmì, tohle tì nemùže zajímat, z vìtší èásti teoretiky.}
{130}{}{Vlastnì mì to zajímá. Chci palivo pro Poseidon Oil Tanker.}
{131}{}{Vsadím se, že to bude zajímat hubologisty. Ti chtìjí palivo.}
{132}{}{Ještì ne, není. Ale já se vrátím.}
{133}{}{Chtìjí palivo, že ano? Dobøe, jsou tak rozzlobeni, mají své použití. Slyšel jsem, že rozvinuli postup, kterým vyrábí soupravu mocných zbraní, dokonce více nepøemožitelných. Když mi oni upgradují takovou sadu zbraní, pošlu jim palivo našim potrubím. Domnívám se, že je to pro jejich hraèku vesmírnou loï. To je ten Crocket, se kterým budeš chtít mluvit.}
{134}{}{Udìlám to.}
{135}{}{Nemohu nic slíbit.}
{136}{}{Mám zde jeden nárok.}
{137}{}{Dokonce i kdybych ti chtìl pomoci, nemohl bych. Naše palivové rezervy byly vyèerpány. Možná bys udìlal lépe, kdybys požádal hubologisty o pomoc. Sbohem.}
{138}{}{Dobøe, to je tedy vše.}
{139}{}{To bude dosti nemožné. Naše palivová zásoba se už vypaøila. Dokonce, i kdybych chtìl pomoci hubologistùm, což nechci, nemohl bych. Dobrý den.}
{140}{}{Dobrá. Ahoj.}
{141}{}{Dobrá. Teï mì nech, abych se vrátil ke své práci.}
{142}{}{-hotovo-}
{143}{}{To nemùžeš udìlat? Pak Ti ale nemohu prodat palivo. Teï jdi pryè. Mám práci.}
{144}{}{-hotovo-}
{145}{}{Zakalil jsi zbranì? Výbornì. Teï chceš, abych ti zaplatil?}
{146}{}{Koryto paliva hubologistùm.}
{147}{}{Koryto paliva pro Poseidon Oil tanker.}
{148}{}{Co nìjaké peníze? Myslím $}
{149}{}{Rozhodl jsem se, že si je radìji nechám.}
{150}{}{Považuj to za hotové. Úpravy udìlám brzy. Nyní, jestli mì omluvíš, bych se vrátil k práci.}
{151}{}{Díky. Èau.}
{152}{}{Tolik? Vlastnì pro takovou soupravu zbraní ke studiu... velmi dobøe. Tady jsou tvé peníze.}
{153}{}{Díky. Zatím.}
{154}{}{Chceš si to nechat? Velmi dobøe. Kdybys zmìnil rozhodnutí, dej mi vìdìt.}
{155}{}{Dám. Ahoj.}
{156}{}{Tuèná šance. Ahoj.}
{157}{}{Stráže! Stráže! Ten hajzl je zpátky! Zabijte ho! }
{158}{}{Mluvils s hubologistou, který sám sebe nazívá Crocket a má zbroj?}
{159}{}{Ne, ještì ne.}
{160}{}{Tak proè tedy se sem stále vracíš a otravuješ mì?}
{161}{}{Protože mám nìjaké otázky.}
{162}{}{Nemám ponìtí. Ahoj.}
{163}{}{Nepokoušej mou trpìlivost.}
{164}{}{Co chcete?}
{165}{}{Co tady dìláte?}
{166}{}{Jsem tady, abych získal palivo pro Poseidon Oil Tanker.}
{167}{}{Jsem tady, abych získal palivo pro hubologisty.}
{168}{}{Nic. Lituji.}
{169}{}{Teï jsme všichni bez paliva. Nemohu Ti pomoci s nièím jiným. Jsem pøíliš zamìstnán tìmi zbranìmi. Nashle.}
{170}{}{-Ahoj-}

{171}{}{. Jen se rozhlížím kolem.}
{172}{}{, máš tady vlastnì nìjakou práci?}
{173}{}{ bylo by hezké.}
{174}{}{Mám vše, co potøebuji. Promluv s Wongem, jestli musíš.}
