#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíte docela mladého, plešatícího vìdce. Vypadá, že je zaujatý svou prací.}
{101}{}{Vidíte Crocketa, hubologistického vìdce.}
{102}{}{Vidíte pomìrnì mladého, plešatícího vìdce. Vypadá jako neupravený geek.}
{103}{}{Jé? Cóó chcéš?}
{104}{}{Agh. Um. Duur.}
{105}{}{Dr. Jing mì posílá. Chce nìjaký zpevnìný energo brnìní.}
{106}{}{Chcete vylepšit energo brnìní?}
{107}{}{Kdo jste?}
{108}{}{Co tady dìláte?}
{109}{}{Nic, díky.}
{110}{}{Pøísahám, každý další den je tu více podøízených živých bytostí, bìhajících kolem. Kšá! Kšá!}
{111}{}{Auuu.}
{112}{}{Joo, mùžu to udìlat. Ale co za to žádáte výmìnou?}
{113}{}{Dr. Jing pravdìpodobnì bude žádat o prodej paliva pro Vaši vesmírnou loï.}
{114}{}{Mùžu za to zaplatit.}
{115}{}{Nechám vás žít.}
{116}{}{Nic. Zapomeò na to.}
{117}{}{Jsem Crocket. Jsem vìdec a chlap opraváø. Mohu se k tomu vrátit zpìt?}
{118}{}{Ne. Mám více otázek.}
{119}{}{Jo, jistì.}
{120}{}{Vyvinul jsem novou ztvrzující technologii, jestli mi rozumíš.}
{121}{}{Takže nejste hubologista?}
{122}{}{Mám to. Mám více otázek.}
{123}{}{Ne. Co myslíte?}
{124}{}{Jakou novou technologii jste vyvinul?}
{125}{}{Nahlas a zøetelnì. Nashle.}
{126}{}{Dobøe... Já se *domnívám*, že se to bude muset udìlat. To je obchod. Máte zbroj, která by se zpevnila na vás?}
{127}{}{Ano.}
{128}{}{Ne.}
{129}{}{Skvìlé. To vás bude stát $10,000. A peníze, žádná výmìna. Potøebuji nìjaké nové zaøízení.}
{130}{}{$10,000? To je násilné! Nemám tolik penìz!}
{131}{}{V poøádku. Tady.}
{132}{}{Vrátím se k vám zpìt.}
{133}{}{::Vypadá pobavenì::
Vyhrožujete mi opravdu kvùli tomu?}
{134}{}{Ano. Udìlej to nebo zemøi.}
{135}{}{Ne, jenom sem si dìlal legraci.}
{136}{}{Nech to tady den a já to udìlám. Než pùjdete, mìl byste vìdìt, že mám materiál pouze na dvì sady brnìní.}
{137}{}{Jistá vìc. Mám více otázek.}
{138}{}{Vrátím se zpátky pro zbroj.}
{139}{}{Nemohu na tom moc udìlat kouzlo, když to nemáš. Pøijï zpátky, až to budeš mít.}
{140}{}{Mám více otázek.}
{141}{}{Zdar.}
{142}{}{::Krèí kameny::
Chceš tuhle zbroj nebo ne? Je to $10,000 koneèná cena.}
{143}{}{Vrátím se k tobì zpìt.}
{144}{}{Skvìle. Tady.}
{145}{}{Dálnièní loupež. Žádným zpùsobem.}
{146}{}{::On se ti dívá do oèí a rozhoduje se, že jsi vážný::
Máš tu zbroj tady?}
{147}{}{Ano.}
{148}{}{Ne.}
{149}{}{::dívá se Ti do oèí a pøemýšlí, zda blafuješ::
Zkus to, buzno. Budeš mít stráž za prdelí a nikdy už se nenauèíš jak vytvrdit zbroj.}
{150}{}{Dobøe. Zemøi, chcípáku.}
{151}{}{Hovno. Nazval si mì podvodníkem.}
{152}{}{Podvodník. Myslím, že uvidíme, co k tomuhle øekne stráž.}
{153}{}{Zatracenì!}
{154}{}{Tihle hoši neznají opravdovou vìdu -- pomáhám jim ospravedlnit jejich výstøednost výmìnou za nìjaký èas s jejich panièkami a poøádnej plat.}
{155}{}{Hmm. Mám více otázek, na které bych se chtìl zeptat.}
{156}{}{Ne, úplnì špatné. Nashle.}
{157}{}{Uvidíme... Postavil jsem nukleární reaktor pro vesmírnou loï. Vytvoøil jsem vytvrzující proces pro silné zbroje a opravuji vìci, které jsou rozbité.}
{158}{}{Vidím. Dobrá, mám více otázek.}
{159}{}{Hmm. Musím jít. Zdar.}
{160}{}{Hej, nic sem ti neudìlal. Jenom mi neubližuj.}
{161}{}{Mám pro tebe nìjaké otázky.}
{162}{}{Jsem tu pro svou zbroj.}
{163}{}{Pøíliš pozdì.}
{164}{}{Sbohem.}
{165}{}{Ještì to není pøipravené. Musíš mi dát èas!}
{166}{}{Super. Mám nìjaké otázky.}
{167}{}{Dobøe. Vrátím se.}
{168}{}{Mám to tady zrovna pro tebe. Vezmi si to, vezmi si to.}
{169}{}{Díky. Mám otázky.}
{170}{}{Díky.}
{171}{}{Díky. TEÏ mùžeš umøít.}
{172}{}{Nemùžu, jsem mimo dosah chemikálií. Lituji.}
{173}{}{Tak mi tedy mùžeš odpovìdìt na pár otázek.}
{174}{}{Pak mùžeš umøít.}
{175}{}{Sakra. Zdar.}
{176}{}{Tak kde je moje palivo? Slíbil jsi mi palivo, sráèi.}
{177}{}{Dostaneš ho, dostaneš ho. Teï mi odpovìz na pár otázek.}
{178}{}{Jasnì, jebu na tebe.}
{179}{}{A naposledy taky. STRÁŽE!}
{180}{}{Chcípni, sráèi.}
{181}{}{Hovno. Mizím.}
{182}{}{Dobøe, co tedy teï chceš?}
{183}{}{Jsi už teï pøipraven zaplatit $10,000?}
{184}{}{Nech to tedy tak den a já to udìlám. Pamatuj si, že tohle je poslední sada, kterou mùžu udìlat.}
{185}{}{Hej, mám pro tebe další výstroj.}
