#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš mue s pískovou barvou vlasù.}
{101}{}{Vidíš Dava H.}
{102}{}{Vidíš mue s pískovou barvou vlasù se slibnım zábleskem v jeho oèích.}
{103}{}{Proè nám chceš ublíit?}
{104}{}{Pozdravy, Osvícenı.}
{105}{}{Chystám se pøimìt Vikki... hmm... brzy.}
{106}{}{Jak ti mùu pomoci?}
{107}{}{Co chceš?}
{108}{}{Chceš... ó...}
{109}{}{Kdo jsi?}
{110}{}{Co tady dìláte?}
{111}{}{Povídal jsem si s Vikki. Ona a Juan si z tebe dìlali srandu a povídali, e nejsi poøádnı mu.}
{112}{}{Povídal jsem si s Vikki. Øekla, e jsi vášnivı a e po tobì èasto touí.}
{113}{}{Chceš, abych tì pøed Vikki vychvalovala?}
{114}{}{Vùbec ne. Díky.}
{115}{}{Hmmm... dobráá. Cokoliv. Øekni, co je to tam?
(jak se otáèíš, aby ses podíval, on se zase zaène vìnovat tomu co dìlal pøed tím a ignoruje tì)}
{116}{}{-hotovo-}
{117}{}{Jsem Dave Handy. Jsem z Kanady.}
{118}{}{Tak co tady dìláš?}
{119}{}{Co tì sem pøitáhlo?}
{120}{}{Díky. Sbohem.}
{121}{}{Ukazuju tìmto chlapcùm, jak se pøemisují jejich informace a odpovídám celı den na pitomé otázky.}
{122}{}{Jsi schopnı dostat se do Shi databáze?}
{123}{}{Jaké pitomé otázky?}
{124}{}{Dobrá, mám pro tebe další otázky.}
{125}{}{To zní dobøe. Èau.}
{126}{}{Slib mi, e se nebudeš smát.}
{127}{}{Dobrá.}
{128}{}{Ne, zapomeò na to.}
{129}{}{Verbíø od "Hubù", Vikki Goldmanová. Vidìl jsem jeden z jejích filmù tam v Kanadì a právì sem se dozvìdìl, e se do mì zamiluje. Ještì se to nestalo, ale pracuji na tom.}
{130}{}{Schovám si to pod klobouk. Mám více otázek.}
{131}{}{Hehe, co jsi to za hlupáka! Ona je pornohvìzda, kamaráde. Ona tì nechce.}
{132}{}{Zjistíš, e se bude chovat jako e jí zajímáš, aby se ujistila, e zùstaneš dobrım hubologistou, rozumíš?}
{133}{}{Dobrá, hm... ale stojí to za to v pøípadì, e se nìco stane!}
{134}{}{Kdy to... kdy to øíkáš. Mám více otázek.}
{135}{}{Cokoliv. Ahoj.}
{136}{}{::sedá si ve strnulém tichu na moment::
::bolest vytvoøí køeè na jeho oblièeji::
Dobrá.
::Otáèí hlavou pryè::}
{137}{}{Vsadím se, e se chceš dostat zpátky za ní.}
{138}{}{Lituji. Mám více otázek.}
{139}{}{Doruèil zprávy... tak dlouho!}
{140}{}{Vsadím se, e já ano. Co potøebuješ?}
{141}{}{Potøebuji plány vertibirdu z tvého poèítaèe.}
{142}{}{Potøebuji, abys zformátoval hubologistickı hard disk.}
{143}{}{Chci, abys ses dostal do Shi databází a pøemístil nìjaké palivo do tankeru Poseidon.}
{144}{}{Chci, abys pøemístil palivo z vesmírné lodi do tankeru Poseidon.}
{145}{}{Nic. Zatím.}
{146}{}{Tady jsi. Teï odsud odejdi. Budu formátovat poèítaè a zmizím.}
{147}{}{Potøebuji plány vertibirdu z tvého poèítaèe.}
{148}{}{Chci, aby ses dostal do Shi databází a pøemístil nìjaké palivo do tankeru Poseidon.}
{149}{}{Chci, abys pøemístil palivo z vesmírné lodi do tankeru Poseidon.}
{150}{}{Dobøe, opravdu jsem jenom ertoval. Ona to vlastnì neøekla.}
{151}{}{Hodnì štìstí. Nashle!}
{152}{}{Nauè tyhle zmetky, co znamená vyuít mì a potom odmítnou. Sbohem.}
{153}{}{Dobøe, opravdu jsem jenom ertoval. Ona to vlastnì neøekla.}
{154}{}{Sbohem.}
{155}{}{Neøekla to. Dobrá.}
{156}{}{Take jsem udìlal všechnu tu škodu pro nic. Teï Tì zabiju.}
{157}{}{Zkus to.}
{158}{}{Ona to udìlala? Opravdu? Super. :: na jeho oblièeji se pomalu objevuje úsmìv:: Díky! Co pro Tebe mohu udìlat?}
{159}{}{Potøebuji plány vertibirdu z tvého poèítaèe.}
{160}{}{Potøebuji zformátovat hubologistickı hard disk.}
{161}{}{Chci, aby ses dostal do Shi databází a pøemístil nìjaké palivo do tankeru Poseidon.}
{162}{}{Chci, abys pøemístil palivo z vesmírné lodi do tankeru Poseidon.}
{163}{}{Á nic. Bì a uij si nìjakou legraci.}
{164}{}{Tady jsi. Nìco dalšího?}
{165}{}{Potøebuji plány vertibirdu z tvého poèítaèe.}
{166}{}{Potøebuji, abys zformátoval hubologistickı hard disk.}
{167}{}{Chci, abys pøemístil palivo z vesmírné lodi do tankeru Poseidon.}
{168}{}{Chci, aby ses dostal do Shi databází a pøemístil nìjaké palivo do tankeru Poseidon.}
{169}{}{Ne. Zatím!}
{170}{}{Zformátovat hard disk? Dìláš si srandu? V ádnım pøípadì! Nìmùu to udìlat!}
{171}{}{To je obvyklı úklid. Stejnì u jsem všechno zálohoval.}
{172}{}{Ano, v poøádku. Mám více otázek.}
{173}{}{Ano, v poøákdu. Èau.}
{174}{}{Hm. Dobøe, já to udìlám, kdy jsi všechno u zálohoval. ::Poklepe na klávesnici:: Tak tedy.}
{175}{}{Díky! Zatím!}
{176}{}{Jen jsem tì zkoušel jako dùvìøivce. Mìj se!}
{177}{}{Zkontroluji to sám. Nemyslím si, e je bezpeèné formátovat poèítaè.}
{178}{}{V poøádku. Mám více otázek.}
{179}{}{V poøádku. Èau.}
{180}{}{Ne, ne... pøíliš bych se stydìl.}
{181}{}{Skvìle, skvìle. Mám více otázek.}
{182}{}{Skvìle, skvìle.}
{183}{}{Mìl bych toho bıt schopen. Ale jen, pokud máš na mysli urèitı úkol.}
{184}{}{Pøemísti palivo do tankeru Poseidon.}
{185}{}{Nemohu pøijít na nic urèitého právì teï. Dám ti vìdìt.}
{186}{}{Ó, rád:}
{187}{}{"Má mùj terminál podporu 3D-karty?"}
{188}{}{"Proè nemohu dostat multiuser hookup?"}
{189}{}{"Myslím, e bychom mìli zmìnit vzájemnı vztah, i kdy ten dosavadní funguje vıbornì!"}
{190}{}{"Proè nemohu pouít meè nebo motorovou pilu na mé obrazovce?"}
{191}{}{"Mìl bych bıt schopen pouívat dvì zbranì. Proè je nemohu pouít zároveò?"}
{192}{}{"Vıstup na mém terminálu je pomalı a trhanı. Myslím, e to je tvá chyba".}
{193}{}{Jako co.}
{194}{}{Aha. Ti lidé vypadají jako by se dobøe bavili. Mám více otázek.}
{195}{}{Vidím. Dobøe, mìj se.}
{196}{}{Mohl bych to udìlat. Ale potøeboval bych k tomu dobrı dùvod a ten prostì nemám. Lituji. Nìco jiného?}
{197}{}{Ano, mám více otázek.}
{198}{}{Ne, domnívám se, e ne.}
{199}{}{Lituji, jejich systém na chvíli pøestal reagovat. Není zde ádnı zpùsob, jak bych se tam dostal.}
{200}{}{Chystám se pøesvìdèit Vikki... hmm... brzy. S èím mohu pomoci?}
