#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš dítì.}
{101}{}{Vidíš dítì z pøístavu.}
{102}{}{Vidíš dítì.}
{103}{}{Tohle místo se mi nelíbí.}
{104}{}{Na plái je velká mrtvá a smradlavá ryba.}
{105}{}{Ó! Co to je?}
{106}{}{Tady zvláštnì voní vzduch.}
{107}{}{Chceš jít plavat?}
{108}{}{Jdu hrát.}
{109}{}{Kde je moje maminka?}
{110}{}{ijeme na plái!}
{111}{}{Já se nudíím.}
{112}{}{Jéé!}
{113}{}{Pomoc!}
{114}{}{Ale ne! Strašidloooo!}
{115}{}{Mammííííííííí!}
{116}{}{Utíkej pryè! Pøíšera!}
