#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš špinavého, nemocnì vypadajícího èlovìka.}
{101}{}{Vidíš èlovìka, jenž se bezprávnì nastìhoval do cizího domu.}
{102}{}{Vidíš špinavého, nemocnì vypadajícího èlovìka.}
{103}{}{Tohle je jeden z nejlepších bejvákù, jaký už jsme léta nemìli!}
{104}{}{Hmm... moøský vzduch!}
{105}{}{Tohle je život, co? Žádní šéfové, žádná vláda... jenom èistá moøská bríza.}
{106}{}{Tam v moøi je auto. Rozbité a prorezivìlé.}
{107}{}{Vsadím se, že dìti to tady milují.}
{108}{}{Èerstvá moøská jídla každou noc! Chutné, dokonce i když to mìlo dvì hlavy.}
{109}{}{Naši sousedi jsou jistì "zajímaví."}
{110}{}{My už se nìkdy rozhoupeme, jsem si jist.}
{111}{}{Líbí se ti naše domovy?}
{112}{}{Miluju život na pláži.}
{113}{}{Prosím, neubližujte mi!}
{114}{}{Ne! Neubližujte mi!}
{115}{}{Nechte mé dìti být!}
{116}{}{Stùj! Neubližuj nám!}
{117}{}{Udìlám cokoliv!}
{118}{}{Pomoc!}
{119}{}{Ale ne! Utiskovatel!}
{120}{}{Ach, kdybychom tam mìli stráže!}
{121}{}{Teï lituji, že jsem se vzdal ochrany spoleènosti...}
