#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš rybáøe Shi.}
{101}{}{Vidíš pøístavního dìlníka.}
{102}{}{Vidíš dìlníka Shi, jeho obleèení je špinavé od šupin ryb, dehtu a soli.}
{103}{}{Dnes je poèasí hezké k pobytu na moøi.}
{104}{}{Já jsem mìl vdycky rád vlny.}
{105}{}{Máš rád rybí šávu?}
{106}{}{Slunce, èerstvı vzduch a moøská strava. Co by mohl nìkdo chtít jiného, ne koupel?}
{107}{}{Z ryb je mi na zvracení.}
{108}{}{Bolí mì záda.}
{109}{}{Áh, podívejme... Další turista.}
{112}{}{Pozor na pøíšery v tankeru. Ó, poèkej... Myslím, e u jsi to stejnì udìlal.}
{113}{}{Take sis prošel tanker, ano?}
{114}{}{Ten tanker je drsné místo. To øíkají i pankáèi.}
{115}{}{Chceš se nìkam dostat?}
{116}{}{Dnes je hezké poèasí k vıletu na oceán.}
{117}{}{Já mìl vdycky rád vlny.}
{118}{}{Máš rád rybí šávu?}
{119}{}{Slunce, èerstvı vzduch a moøské jídlo. Co by mohl kdokoli chtít jiného ne koupel?}
{120}{}{Z ryb je mi na zvracení.}
{121}{}{Bolí mì záda.}
{122}{}{Áh, podívejme... další turista.}
{125}{}{}
{126}{}{}
{127}{}{}
{128}{}{}
{150}{}{Teï je èas zemøít, turisto.}
{151}{}{Myslíš, e zvládneš pøístavní rvaèku?}
{152}{}{Nemyslím si, e bys byl takovej tvrïas.}
{153}{}{Uvidíme, jak se ti bude líbit naštvanej pøístavní dìlník!}