#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš scvrklého starého mue, jen má na sobì bílou pracovní zástìru.}
{101}{}{Je to Dr. Fung.}
{102}{}{Vidíš scvrklého starého mue, jen má na sobì bílou pracovní zástìru.}
{103}{}{Chceš s nìèím pomoct?}
{104}{}{Auvej! Jau! Auuuu!}
{105}{}{Ach -- jsem zranìn a zdá se mi, e vy jste doktor.}
{106}{}{Ano. Potøebuji doktora pro mého pøítele.}
{107}{}{Máte nìjaké stimpaky? Rád bych si nìjaké koupil.}
{108}{}{Kdo jste?}
{109}{}{Mám pøítele, kterému chybí slezina. Mùete mu pomoci?}
{110}{}{Co mi mùete øíci o tomto místì?}
{111}{}{Nashle.}
{112}{}{Dovolte, abych se na to podíval. Hmm.... Ano. Budete mi muset zaplatit, samozøejmì.}
{113}{}{Kolik?}
{114}{}{Zapomeòte na to.}
{115}{}{Mohu ho vyléèit... ale za peníze, rozumíte.}
{116}{}{Kolik?}
{117}{}{Zapomeòte na to.}
{118}{}{Kdo jsem? Jsem Dr. Fung. Uèím a léèím.}
{119}{}{Dr. Fung? Znáte Doc Hollidaye?}
{120}{}{Tìší mì. Potøebuji vyléèit.}
{121}{}{Mùj pøítel potøebuje uzdravit.}
{122}{}{Vidím. Díky. Sbohem.}
{123}{}{Holliday? Ano! Nauèil jsem ho všemu, co teï zná! Kde je teï?}
{124}{}{ije v Broken Hills.}
{125}{}{Šel domù, e ano. Doufám, e tam našel klid.}
{126}{}{Myslím, e ano. Mám více otázek.}
{127}{}{Pravdìpodobnì. Musím jít. Nashle.}
{128}{}{To vás bude stát $100.}
{129}{}{Zaplatím.}
{130}{}{Zapomeòte na to.}
{131}{}{Tohle vypadá vánì. To bude stát $200.}
{132}{}{Zaplatím.}
{133}{}{Zapomeòte na to.}
{134}{}{Toto jsou pùsobivá zranìní. $300 bude staèit na zaplacení mıch slueb.}
{135}{}{Zaplatím.}
{136}{}{Zapomeòte na to.}
{137}{}{Za tolika práce se obávám, e budu muset poadovat $400.}
{138}{}{Zaplatím.}
{139}{}{Zapomeòte na to.}
{140}{}{Sednìte si. Budete to potøebovat, a uslyšíte èástku, kterou pooaduji. Zmrzaèené údy stojí $600.}
{141}{}{Zaplatím.}
{142}{}{Zapomeòte na to.}

{158}{}{Co? Nemáte peníze? Z èeho myslíte, e budu ít, kdy po mnì poadujete práci zadarmo?}
{159}{}{Máte stimpaky?}
{160}{}{Ne, dìkuji.}
{161}{}{Bylo mi potìšením s vámi pracovat.}
{162}{}{Díky.}
{163}{}{Bohuel, vaše nabídka není pøijatelná.}
{164}{}{Co tøeba tohle?}
{165}{}{To je vše, co mohu nabídnout. Zatím.}
{166}{}{Jste zranìn? Tsk, tsk. Starovìkı léèebnı prostøedek to vyléèí.}
{167}{}{Dobøe!}
{168}{}{}
{169}{}{Jsme hotovi. Teï jdìte a buïte opatrnı!}
{170}{}{Dík!}
{171}{}{Potøebujete více?}
{172}{}{Potøebuji vyléèit.}
{173}{}{Mám pøítele, kterı potøebuje léèení.}
{174}{}{Kdo jste?}
{175}{}{Øeknìte mi nìco o tomhle místì.}
{176}{}{Mám pøítele, kterému chybí slezina. Mùete mu pomoci?}
{177}{}{Ne. Díky.}
{178}{}{Musíte jít k nìkomu jinému. Chtìl byste slyšet radìji dlouhı pøíbìh nebo ten krátkı?}
{179}{}{Dlouhı.}
{180}{}{Krátkı.}
{181}{}{ádnı. Mám další otázky.}
{182}{}{Naši lidé sem pøipluli na ponorce Shih-huang-ti, kdy rakety explodovaly na zemìkouli. Za pomoci kultu, jsme pak my, lidé Shi, pøestavìli San Francisko. Toto je zkrácená verze.}
{183}{}{Jak zní tedy dlouhá verze?}
{184}{}{Díky. Mám více otázek.}
{185}{}{Díky.}
{186}{}{Dlouhá verze zní: Jsme tady, protoe naši lidé jsou potomci posádky nukleární ponorky, jen se nazıvá Shih-huang-ti. Kdy støely dopadly na Velkou Potopu, systémy vnì ponorky se porouchaly a my jsme byli unášeni, neznámo kam, po mnoho dní.}
{187}{}{-více-}
{188}{}{Nakonec jsme se dostali na bøeh, ke zbytkùm San Franciska. Vìtšina mìsta byla ponièena válkou. Museli jsme znovu vybudovat základy spoleènosti zaloené pouze na nìkolika lidech, co pøeili a dobelhali se zpìt do mìsta.}
{189}{}{-více-}
{190}{}{Stavìli jsme z materiálu, kterı jsme mìli po ruce. Mìli jsme tu i vìdce a technologii, kterou by nám mohl celı svìt závidìt. Rozvíjíme civilizaci, ale ne takovou, jakou ji pøed námi vytvoøil šílenı Mistr.}
{191}{}{Vidím. Mám více otázek.}
{192}{}{Díky. Èau.}
{193}{}{Samozøejmì, ano. A ponìvad jste známí Doc Hollidaye... Udìlám to kvùli pøátelství. Øeknìte svému kamarádovi, co je bez sleziny, a pøijde sem, e mu ji dám zpìt.}
{194}{}{Dìkuji! Mám více otázek.}
{195}{}{Dìkuji!}
{196}{}{Ano. To mohu udìlat. Budì vás to stát $1000 dolarù. Na ruku. Pøijímáte?}
{197}{}{Ano.}
{198}{}{Ne.}
{199}{}{Øeknìte vašemu kamarádovi, aby sem pøišel. Já mu to vymìním.}
{200}{}{Dìkuji. Mám více otázek.}
{201}{}{Dìkuji.}
{202}{}{Nemohu pro nìj nic udìlat, ne dáte dohromady $1000. Mìjte se.}
{203}{}{Nashle.}
{204}{}{Neošetøuji nepøátele mıch lidí. Omlouvám se.}
{205}{}{Velectìnı pane, doporuèuji vám najít vašeho kultovního doktora.}

{206}{}{Co mi mùete øíci o armor implantátech?}
{207}{}{Publikoval jsem nìkolik èlánkù o armor implantátech. Vše, èeho bude tøeba, jsou mé znalosti a vaše materiály. Jakı druh implantátu si pøejete?}
{208}{}{Jaké druhy existují?}
{209}{}{Podkoní implantáty.}
{210}{}{Zesílené podkoní implantáty.}
{211}{}{Phoenix implantáty.}
{212}{}{Zesílené Phoenix implantáty.}
{213}{}{Hmm... na to zapomeòte. Mám jiné otázky.}
{214}{}{ádnı, vlastnì. Nashle.}
{215}{}{Máme podkoní implantáty, které chrání pøed fyzickım ponièením. Jestli se vám to líbí, mùeme vám dát tento implantát v jednoduchém i upgradovaném provedení. Také máme Phoenix implantáty, které chrání pøed ohnivımi napadeními. Ty samozøejmì mohou bıt také ještì upgradovány. Jestli vás zajímají jenom upgrady, budete si muset poèkat na to, a budete mít instalovánu jednu ze základních souprav. A pøedtím ne se ještì zeptáte -- ano, MUETE mít všechny ètyøi operace.}
{216}{}{Super. Vezmu si podkoní implantáty.}
{217}{}{Chci podkoní implantáty.}
{218}{}{Dej mi zesílené podkoní implantáty.}
{219}{}{Rád bych si vzal Phoenix implantáty.}
{220}{}{Èas pro zesílené Phoenix implantáty.}
{221}{}{Hmm... na to zapomeòte. Mám jiné otázky.}
{222}{}{ádnı, vlastnì. Neshle.}
{223}{}{Vıbornì. Vıbornì. Budu potøebovat jeden komplet kevlarového brnìní a ehm $5500. No a vy budete potøebovat dva dny na doléèení. A schopnost moc nekrvácet.}
{224}{}{Jdeme na to.}
{225}{}{Zapomeòte na to. Zatím.}
{226}{}{Zesílené podkoní implantáty, hm? To vás bude stát nìkolik dní vašeho ivota, $33000, bojovou zbroj a nìkolik jizev, které u vám nikdy nezmizí, a ijete jak dlouho chcete.}
{227}{}{Nu a? To vše si mohu dovolit.}
{228}{}{Hmm. Nemyslím si, e bych chtìl tolik zaplatit. Zatím.}
{229}{}{Jestli vám nevadí, e pøijdete o $8500, nìkolik dní ivota a bojovou zbroj, mùeme zaèít u teï.}
{230}{}{Svate mì, doktore. Jsem pøipravenı.}
{231}{}{To je malı kopec. Dovolte, abych k vám pøišel.}
{232}{}{Tohle je závaná operace. Bude vás to stát váš "hezkı vzhled", bojovou zbroj a $49000. Pøejete si tohle všechno do toho vloit?}
{233}{}{Jo. Pojïme na to.}
{234}{}{Hmm. Je to... nároèné. Vrátím se k tobì.}
{235}{}{::On potøásá svou hlavou:: Nehrajte si se mnou. Schází vám nezbytné poloky. Pøíštì mì poøádnì poslouchejte. Teï jdìte a vrate se, a vám budu moci pomoct.}
{236}{}{Ok.}
{237}{}{Tady jste! Jste ... obohacen. Pamatujte... nechyte svrab, pokud nechcete odporné jizvy na své vizái.}
{238}{}{Díky, doktore. Zatím.}

{239}{}{Mám ty peníze na slezinu.}
{240}{}{Zase se zajímáte o implantáty?}
