#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš malého, tlustého Shi mue.}
{101}{}{Vidíte Dr. Wong Yi Tze.}
{102}{}{Vidíte malého, tlustého Shi mue.}
{103}{}{Mohu vám s nìèím pomoci?}
{104}{}{Daghi nu?}
{105}{}{Kdo jste vy?}
{106}{}{Slyšel jsem, e máte nìèí slezinu.}
{107}{}{Kdo jste?}
{108}{}{Co tady dìláte?}
{109}{}{Ne, dìkuji. To je vše.}
{110}{}{Musím se pøiznat, e nehovoøím vaší øeèí. Moná byste si mìl pohovoøit s Kenem Lee, ten umí mnoho jazykù.}
{111}{}{Aha!}
{112}{}{Jsem Dr. Wong. Jsem hlavní vìdec tohoto zaøízení.}
{113}{}{Více otázek, prosím.}
{114}{}{Díky. Ahoj.}
{115}{}{Dohlíím na vìdecké pokusy, jen se zde provádìjí. Jsem také zodpovìdnı za poèítaèovou sí.}
{116}{}{Co plánujete?}
{117}{}{Jak bych si mohl získat pøístup do poèítaèové sítì?}
{118}{}{Mám další otázky.}
{119}{}{Aha. Nashle.}
{120}{}{Hm, ale kdy vám øeknu naše plány, pak je bude vìdìt kadı. Obávám se, e prozatím jsou tajné.}
{121}{}{Dobøe, dobøe. Mám další otázky.}
{122}{}{Díky. Nashle.}
{123}{}{A co kdybych vám strèil pistoli pod rypák a pøinutil vás mi to øíct?}
{124}{}{Jasnì, nìkdo vás mùe nauèit, jak se do toho hacknout nebo jak se spøátelit s jedním z mıch poskokù. Samozøejmì, o tom hackování ertuji -- kdybys to udìlal, poslal bych nìkoho, aby tì zabil. (Usmívá se, aby dokázal, e to nemíní jako uráku.)}
{125}{}{Opravdu byste mì zabil?}
{126}{}{Take byste nemìl ádné námitky k tomu, abych se dostal do poèítaèe?}
{127}{}{Mám jiné otázky.}
{128}{}{Jistì. Nashle.}
{129}{}{Pak na to ovšem musím hledìt jako na hrozbu a varuji vás, e takovı postup by mohl bıt na škodu vašemu zdraví.}
{130}{}{Zkusme to.}
{131}{}{Jenom jsem si dìlal legraci. Mám jiné otázky.}
{132}{}{(Usmívá se) Musíme si chránit vlastní èest, cizinèe.}
{133}{}{Hm, správnì. Take byste nemìl ádné námitky k tomu, abych se dostal do poèítaèe?}
{134}{}{Sprááávnì. Mám další otázky.}
{135}{}{Vsadím se. Nashle.}
{136}{}{Jestli dokáøete pøesvìdèit mé podøízené, aby do toho šli... Ale já urèitì nepùjdu.}
{137}{}{A co kdybych vám strèil pistolku do pusinky?}
{138}{}{Skvìlı. Dobøe, mám více otázek.}
{139}{}{Hmm. Vidím. Dobøe, zatím.}
{140}{}{Ach, ano! Vskutku. Pøipravím to s fazolemi a dobrım kianti.}
{141}{}{Poøád to máte? Dobrı. Chip to potøebuje vrátit.}
{142}{}{To je lidská slezina, ty prašivej bastarde!}
{143}{}{Vy pøece víte, e byste mìl podávat na stùl s vínem játra místo sleziny, e ano?}
{144}{}{To je lidská slezina, víte.}
{145}{}{Kdo je ten Chip? To je teï moje slezina a já ji mám k veèeøi.}
{146}{}{Chip je pùvodní vlastník sleziny. Byl opilı a prodal ji Lao Chouovi.}
{147}{}{Potøebuje ji, aby pøeil, víte. Je z jeho tìla.}
{148}{}{Tak moná bych vás za to mìl radìji zabít.}
{149}{}{Smlouva je smlouva. Nemùe ji mít. Lituji, ale udìlali jsme spolu dohodu a to, e Chip toho teï lituje, neznamená, e mùe couvnout od dohody.}
{150}{}{-více-}
{151}{}{Je to lidská slezina? Lao Chou mi to neøekl!}
{152}{}{A právì kvùli neurvalosti posla bych dodrel všechny èásti té dohody. Udìlám na tom místo toho pokus.}
{153}{}{Øeknìte vašemu kamarádovi, aby si sem pro to pøišel bìhem pøíštího dne a já mu ji rád vrátím zpìt. Jenom doufám, e najdete zpùsob, jak mu slezinu voperovat vèas zpátky.}
{154}{}{Velmi dobøe.}
{155}{}{He, he! Ano, taky jsem vidìl ten starı film.
Poèkej... Co to øíkáte? Øíkáte, e...?}
{156}{}{Ano, je to lidská slezina.}
{157}{}{Vlastnì, proti tomu protestuji. Nedokázal jste, e máte dobrı charakter. Vskutku, vùbec nevím, proè se s vámi bavím. Nashle.}
{158}{}{-hotovo-}
{159}{}{A jé je! Stráe! Utiskovatel od lao wai je tady!}
{160}{}{Máte mi pøedat jistá schémata?}
{161}{}{Ken Lee mi øekl, abych vám je pøedal.}
{162}{}{Ano. Teï co tu tedy mám?}
{163}{}{Ne, ještì ne.}
{164}{}{Promluv s Kenem Lee a on projedná tvou budoucnost. Dìkuji vám. Mìli bychom bıt schopni ovìøit si nìkteré z našich testovacích údajù s tìmito. Dobrı den.}
{165}{}{Mìl jsem vlastnì ještì další otázky.}
{166}{}{Zatím.}
