#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš mue od Shi s odhalenım trupem.}
{101}{}{Vidíš Dragona, hrdinu mnoha Shi rolníkù.}
{102}{}{Vidíš mue s odhalenım trupem, hezky svalnatého, jeho ruce vypadají jako nebezpeèné zbranì.}
{103}{}{Jak mohu bıt nápomocen?}
{104}{}{Dinkle humper doo!}
{105}{}{Kdo ty?}
{106}{}{Kdo to byl, ten, s kım ses pral?}
{107}{}{Kdo jsi ty?}
{108}{}{Nauè mì jak se bojuje.}
{109}{}{Pøeji si tì zocelit.}
{110}{}{Na to zapomeò.}
{111}{}{Obávám se, e nerozumím tvému jazyku. ::uklání se:: Dobrı den.}
{112}{}{Ahóój!}
{113}{}{Jsem Dragon, pøíteli. Bojuji s utlaèitelem a mım nepøítelem, Lo Panem, kterı si troufá vládnout tomuhle mìstu. Bojuji a uèím další bojovat.}
{114}{}{Uè mì!}
{115}{}{Dìkuji Ti.}
{116}{}{Pak zaèneme.}
{117}{}{-hotovo-}
{118}{}{::dívá se na tebe zblízka:: Nevìøím, e bys pouil tyto poznatky k dobru. Dobrı den.}
{119}{}{Vrrr!}
{120}{}{Prosím, omluv mou neurvalost. Nemohu s tebou právì teï mluvit.}
{121}{}{Áhhh... dobrá!}
{122}{}{To byl Lo Pan. On je mùj nepøítel na ivot a na smrt. Jestli nade mnou zvítìzí, tak se budu strachovat o blaho lidí.}
{123}{}{Lidé jsou ovce. Mìl bys slouit sám sobì.}
{124}{}{Pak musíš zvítìzit.}
{125}{}{Vidím. Mám více otázek.}
{126}{}{Ty tomu opravdu vìøíš? Pak bys moná mìl vyjednávat s Lo Panem. Dobrı den.}
{127}{}{-hotovo-}
{128}{}{To musím. Nebo se budeme poøád utkávat, obávám se. Dokonce se potıkáme i v našich následnících. Bude to chtít jednoho èlovìka, kterı by to udrel v rovnováze.}
{129}{}{Jsem ta osoba.}
{130}{}{Vidím. Dobøe, mám více otázek.}
{131}{}{Vidím. Dobøe, zatím.}
{132}{}{Ano? Moná bychom tì mìli vyzkoušet. Já ho jenom zlepším v poctivém boji.}
{133}{}{Hej, on umøe tak nebo onak. Jakı rozdíl to èiní?}
{134}{}{To se mi zdá spravedlivé. Jak funguje ten test?}
{135}{}{Hm. Dobøe, v tom pøípadì u musím jít.}
{136}{}{Ti, kteøí bojují beze cti jsou horší ne zvíøata!}
{137}{}{Dobrá, Pollyanno. Odpoèívej.}
{138}{}{Nazıvám to chytrım bojem. "Ctnost" je slovo vynalezené k oslavì zabijákù.}
{139}{}{Mám to. Mám více otázek.}
{140}{}{V poøáádku. Ahoj.}
{141}{}{Nejprve rozhodneme, zda si pøeješ aby toto byl boj vedenı do konce nebo test tvıch schopností proti mım.}
{142}{}{Do konce. Vyaduji to.}
{143}{}{Test schopností. Nechci tì zabít.}
{144}{}{Já taky ne. Zapomeò na to.}
{145}{}{Nejsi ten pravı pro tuto povinnost. Nashle.}
{146}{}{-hotovo-}
{147}{}{Kdy myslíš? Válka a bojování se zdají nevyhnutelnımi. Radìji bychom mìli bojovat podle pravidel a zákonù ne boj pouívat k nièení. }
{148}{}{Zvítìzím jakımkoli zpùsobem, kdy budu moci.}
{149}{}{Jestli musíme bojovat, pak bychom mìli bojovat o pøeití. Kdy se nìkdo pokusí mì zabít, budu sám sebe chránit všemi monımi zpùsoby i nemonımi.}
{150}{}{Hm. Máš bod. Dobøe, mám více otázek.}
{151}{}{Jé, ano. Ahoj.}
{152}{}{Velmi dobøe. Vstupme do ringu a bojujme dokud se jeden z nás nebude moci hıbat.}
{153}{}{- nyní útok se zbrojí a zbranìmi -}
{154}{}{- vstupte do ringu, odstraòte zbroj a zbranì a bojujte rukama -}
{155}{}{Á, váleèník. Mìl bych tì strèit proti mım muùm, abych vidìl jak dobøe bojuješ. Zaènìme.}
{156}{}{-zaèni-}
{157}{}{Avšak ve formálním bojovém prostøedí nemùeš diskutovat, e jsi vstoupil do této arény z vlastního vıbìru. Jak u jsi tam jednou vstoupil, nemìl bys bıt vìrnı jejím pravidlùm?}
{158}{}{Ano, pravdìpodobnì. Ale v situaci, kdy jde o ivot, musíš udìlat vše, abys pøeil.}
{159}{}{Ne, to si nemyslím.}
{160}{}{Máš bod. Dobøe tedy. Jestli si pøeješ bojovat s Lo Panem, budeš ozbrojenı a neozbrojenı? Jestlie budeme potøebovat tvoji pomoc v tomhle, budeme poadovat, abys byl vìrnı našim pravidlùm.}
{161}{}{Ano, udìlám to vaším zpùsobem.}
{162}{}{Ne. Zapomeò na to.}
{163}{}{Vıbornì. Tak nám tedy uka, zda jsou tvé schopnosti dost silné k boji s Lo Panem.}
{164}{}{Pojïme.}
{165}{}{Právì teï ne. Vrátím se pro to pozdìji.}
{166}{}{Jsem Dragon, ochránce lidí a nepøítel na ivot a na smrt s Lo Panem. On a já jsme posledními mistry našeho bojového stylu.}
{167}{}{Nejsem tak špatnı v boji pìstmi. Chceš mì vyzkoušet?}
{168}{}{To je zajímavé. Musí bıt odmìnìno. Mám více otázek.}
{169}{}{Díky. Èau.}
{170}{}{Pokusil ses zneuctít mé lidi, tak tì teï musím zabít. Omlouvám se za monou bolest pøi tvém umírání.}
{171}{}{-hotovo-}
{172}{}{Nemluv na mì, ovce od Hubù. Nemám ádné vyuití pro tvùj druh.}
{173}{}{-hotovo-}
{174}{}{Máš èest prasete a mravy ryby. Nepøeji si stıkat se s tebou.}
{175}{}{-hotovo-}
{176}{}{Tvé bojové schopnosti jsou opravdu skvìlé. Budeš bojovat s Lo Panem?}
{177}{}{Ano. Právì teï jdu na to.}
{178}{}{To není opravdu mùj boj.}
{179}{}{Jistì. Ale mám nìjaké otázky.}
{180}{}{Rozumím. Mìl bys zmìnit své rozhodnutí, víš, kde ho najdeš. Prostì mu øekni jménem Dragona, aby pøišel.}
{181}{}{Správnì. Mám otázky.}
{182}{}{Hmm... dobrá. Nashle.}
{183}{}{Právì jsem se vrátil z poselství cti. Tu noc jsme byli silní.}
{184}{}{Skvìle. Mám otázky.}
{185}{}{Super. Nashle.}
{186}{}{Lo Pan je mrtev! Tobì dìkuji. Nyní jsem pøesvìdèen, e škola povede náš bojovı styl do budoucnosti.}
{187}{}{Dobrá. Mám otázky.}
{188}{}{Dobrá. Èau.}
{189}{}{Tvé kung fu se sem nehodí.}
{190}{}{Jednou tì porazím, Dragone.}
{191}{}{Poèkám si na tebe, Lo Pane.}

{200}{}{Dragon odhaluje tvou vıhodu a ty kolem nìj proklouzneš.}
{201}{}{Zlodìj nemá ádnou èest mezi Shi. Teï odejdi.}
{202}{}{Varoval jsem tì, abys odešel. Teï bys mìl zaplatit.}
{203}{}{Zdá se, e u nepotøebuješ ode mì ádnı trénink.}

{204}{}{Lekce jsou více ne fyzické, kobylko luèní. Pøemıšlej o tom a vra se zítra.}

{205}{}{Jsem Mistr Ziggy, Tvùj poslední test.}
{206}{}{Jsem Zurak. Buï pøipraven.}
{207}{}{Jsem Jimmy. Pøiprav se.}
{208}{}{Jsem Herb. Nedostaneš se dál.}
{209}{}{Jsem Jobe. Je èas rozmašírovat ti drku.}
{210}{}{Jsem Mistr Rube. Jsi vyøízenej.}
{211}{}{BOJ!}
{212}{}{Trénink je poøád ve tvé budoucnosti.}
{213}{}{Jdeme do toho!}
{214}{}{Vyøídil jsi Dragona v boji na ivot a na smrt. Aèkoliv to byl fér zápas, jeho ztráta bude pocítìna mnoha lidmi.}
{215}{}{U jsi vyøídil i mé mue a prošel jsi mım testem. Jsi pøipravenı bojovat s Lo Panem.}
{216}{}{Tvé schopnosti budou jenom vıhodou pøi jejich pouití. U ti nemohu dát více k tvému studiu.}

#tréninkové zprávy
{217}{}{Zaènìme. Následuj mì.}
{218}{}{Trénování bylo u dneska dost.}
{219}{}{Dragon je velmi dobrı, ale tys nauèenej dobøe bojovat.}

{220}{}{Ji jsi vyøídil mé mue. Nikdo další u si nepøeje s tebou mìøit síly.}


{221}{}{I kdy jsi to nevìdìl, pomohl jsi naší záleitosti odstranìním Lo Pana. Máš naše díky.}
{222}{}{Bylo mi potìšením. Sbohem.}
{223}{}{Vítej. Sbohem.}
{224}{}{Ty vítej. Mohu se zeptat?}
{225}{}{Vítej. Zeptat mì?}

{226}{}{Tys ZVÍTÌZIL!}
{227}{}{Tys PROHRÁL!}
{228}{}{Další Protivník!}

{230}{}{Nejprve, musíš prokázat, e to dokáeš. Budu tì muset postupnì postavit proti pìti mım bojovníkùm. Kdy je porazíš, dostaneš svùj poslední test.}
{231}{}{Co to je?}
{232}{}{Vypadá to jako pøíliš mnoho problémù. Sbohem.}
{233}{}{Humbly, sám otestuji tvé schopnosti. Jakkoliv, ádná z tìchto bitev nebude smrtící.}
{234}{}{Ok, dáme se do toho.}
{235}{}{Mùeš se sám postarat o Lo Pana.}
{236}{}{(Dragon tì studuje) Bohuel tì nemohu nechat vyuít tvé schopností, abys jim neublíil.}
{237}{}{Ok, ale mùu se ještì na nìco zeptat?}
{238}{}{Dobrá. Nashle.}
