#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš dobøe ozbrojenou strá.}
{101}{}{Vidíš strá Hubologistù.}
{102}{}{Vidíš dobøe ozbrojenou osobu s krutım pohledem v oèích.}
{103}{}{Vetøelec!}
{104}{}{Chyte vetøelce!}
{105}{}{Tady! Tady!}
{106}{}{Èas zemøít, neznabohu! Velkı Kruh tì rozdrtí!}
{107}{}{Jsme stráe. Teï zemøeš.}
{108}{}{Hvìzdnı Otèe, dej a se mi podaøí zasáhnout mùj cíl.}
{109}{}{Tys porušil naše zásady!}
{110}{}{I kdy právníci nebudou pracovat, naše zbranì ano.}
{111}{}{Jsme dlouhá ruka práva Hubologistù.}
{112}{}{Høíšníku!}
{113}{}{Dej pozor na svùj krok.}
{114}{}{Našlapuj zlehka, cizinèe.}
{115}{}{Nedotıkej se nièeho.}
{116}{}{Kdy ukroèíš stranou, tak z tebe udìláme sekanou.}
{117}{}{Buï velmi, velmi opatrnı.}
{118}{}{Jsme zákon Hubologistù. Nepøekraèuj jej.}
{119}{}{Jsem AHS-4.}
{120}{}{Já tì "srovnám", kdy se nebudeš chovat poøádnì.}
{121}{}{Mám to schválené Velkım Kruhem.}
{122}{}{Zdravím, spolucestující.}
{123}{}{ Zdravím, }
{124}{}{Jsem rád, e jsi tu s námi.}
{125}{}{Jdi si po svém.}
{126}{}{Neotravuj ty, co se snaí soustøedit.}
{127}{}{Tvá pøítomnost je vítána... tam.}
{128}{}{HUB nás povìøil, abychom sledovali jeho stádo.}
{129}{}{Hvìzdnı Otec se o tebe stará. Proto nám tì dal.}
{130}{}{Jsme vìrni AHS-9.}
{131}{}{Uposlechni.}
{132}{}{Spi.}
{133}{}{Jez.}
{134}{}{Máme na srdci tvé nejlepší zájmy.}
{135}{}{.}