#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš nìkoho v rouchu.}
{101}{}{Je to další hubologista v rouchu.}
{102}{}{Zdá se, že je to nìkdo obleèený v rouchu.}
{103}{}{Kdo jsi? Co tady dìláš?}
{104}{}{Nemìl bys tady být, že ne?}
{105}{}{Dívej! Odøezky masa!}
{106}{}{Hej! Kdo jim dovolil vejít?}
{107}{}{Nemìl by ses potulovat bez ochranného doprovodu.}
{108}{}{Ach! Dìláš mi zmatek v mých neurodynech!}
{109}{}{Jdi pryè, neznabohu!}
{110}{}{Nemluv na mì -- jsem zaneprázdnìný èlovìk.}
{111}{}{Hej! Vymíláš mé neurodyny!}
{112}{}{Možná bych tì mìl radìji, kdybys srovnal.}
{113}{}{Hvìzdný Otec tì bude milovat, když mu to dovolíš.}
{114}{}{Nechceš vidìt Quetzela? Pøidej se k nám!}
{115}{}{Jdi si promluvit s AHS-7 a pøidej se!}
{116}{}{Máme slavné osobnosti, kteøí jsou hubologisti, víš.}
{117}{}{Juan Cruz a Vikki Goldmanová jsou slavní! Proto jsem se pøidal.}
{118}{}{Vsadím se, že si s tebou popovídají, když budeš hodný a správný.}
{119}{}{Miluji Hub.}
{120}{}{Jsem rád, že jsem hubologista.}
{121}{}{Chci uvést do pohybu mé možnosti.}
{122}{}{Abych øekl pravdu, poøád se uèím hantýrce.}
{123}{}{Chvalte Hub!}
{124}{}{Chvalte Velký Kruh!}
{125}{}{Jdeme ke Quetzelovi!}
{126}{}{Tìším se až pùjdu domù ke hvìzdám.}
{127}{}{Prosím, neobtìžuj mì; soustøedím mé neurodyny.}
{128}{}{Prosím, nerozpojuj mé neurodyny.}

{138}{}{Ale ne! Pronásledovatel!}
{139}{}{Ten nepouèitelný!}
{140}{}{Drž se dál od mne, Ïáblovo maso!}
{141}{}{Máš zøejmì nìjaké špatné neurodyny!}
{142}{}{Ne! Neposkvrò mì svou nenávistí!}
{143}{}{Stráže! Stráže! Barbar je tady!}
{144}{}{Nedotýkej se mì!}
{145}{}{Pomoc! Stráže!}
{146}{}{Nepøíteli našeho lidu!}
{147}{}{Èerné èasy jsou zase pøed námi!}
{148}{}{Hvìzdný Otèe! Ušetøi mì pohany!}
{149}{}{Nìkdo tì znièí za tvou zradu!}

{150}{}{Miluji Hub.}
{151}{}{Jsem rád, že jsem hubologista.}
{152}{}{Chci uvést v chod mé možnosti.}
{153}{}{Abych øekl pravdu, poøád se uèím hantýrce.}
{154}{}{Chvalte Hub!}
{155}{}{Chvalte Velký Kruh!}
{156}{}{Jdeme ke Quetzelovi!}
{157}{}{Tìším se na cestu domù ke hvìzdám.}
{158}{}{Jsem zpùsobilý k zaøazení do øady.}
{159}{}{Èekám, abych si poslechl AHS-9, až bude zase mluvit!}
{160}{}{Doufám, že mé neurodyny jsou v poøádku.}
{161}{}{Chci být výše zaøazený Hub Uchazeè!}
{162}{}{Je èas, abych se soustøedil na mùj vlastní rùst.}
{163}{}{"Skuteèná" vìda je jenom balík lží.}
{164}{}{Neposlouchej to, co ti "vìdci" øeknou.}
{165}{}{Jenom Hub a AHS-9 mají odpovìï.}

{178}{}{Chvalte Hvìzdného Otce! Jedeme koneènì ke hvìzdám!}
{179}{}{Planeto Quetzel, tady jsme!}
{180}{}{Všechna ta døina se nakonec vyplatila!}
{181}{}{Mé neurodyny jsou naprosto odpoèinuté nyní!}
{182}{}{Radìji se zaøadím pøed tím než odstartujeme.}
{183}{}{Ach! Hvìzdný Otèe! Hvìzdný Otèe!}
{184}{}{Celý se tøesu na to, až vzlétneme!}
{185}{}{Kdy odlétáme?}
{186}{}{Vsadím se, že vysocí AHS nejsou takhle nervózní.}
{187}{}{Aach... hvìzdy. Koneènì.}
{188}{}{Nebudu už muset nosit staniolovou èepici!}
