#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš pankaèku.}
{101}{}{Vidíš punkerku.}
{102}{}{Vidíš pomìrnì hezkou, cynicy se tváøící mladou enu.}
{103}{}{Vsadím se, e ti mùj pøítel nabídl, abyste se o mì podìlili.}
{104}{}{Nìkdy je mi z toho houpání zle.}
{105}{}{ít tu by mohlo bıt prima.}
{106}{}{Myslím, e bysme si mohli pìknì uít.}
{107}{}{Byl jsi na západì, za tou vodou?}
{108}{}{Flirtovala bych s tebou, ale nezajímáš mì.}
{109}{}{::sarkasticky:: Je tu okolo spousta silnıch holek, co?}
{110}{}{Snad ode mì neèekáš, e se kvùli tobì pøetrhnu? Buï v reálu.}
{111}{}{Jsem unikátní! Asi jako kadı jinı!}
{112}{}{Nìkdy mì nudí svìtovì unudìnı cynizmus.}
{113}{}{Pøíštì chci najít kmen Gótù.}
{114}{}{Slyšela jsem, e Císaø Shi je nelidsky chytrej.}
{115}{}{Ti Shiové vypadají hroznì legraènì.}
{116}{}{Jsem pro tebe dost nepøedpojatá?}
{117}{}{Podívej na všechny ty nové pankáèe. Jsoui s nima jen problémy.}
{118}{}{AHS-9 nás podvedl a tebe podvede taky, jestli mu to dovolíš.}
{119}{}{Dalšího oralu, kterı mì øekne "dìvko" ugriluju.}
{120}{}{Tak jakı to bylo s mutantem?}
{121}{}{Ublíil ti ten silnı mutant Francis?}
{122}{}{Pøekvapuje mì, e mùeš chodit po tom, co ti ten Francis udìlal.}
{123}{}{Myslela bych, e budeš poøád ještì krvácet.}
{124}{}{Nemohu uvìøit, e bys nepomohl Chipovi.}
{125}{}{Sobeckı parchante. Vsadím se, e by ti Chip bıval pomohl.}
{126}{}{Kadı má rád Chipa. Teï tì nikdo nemá rád.}
{127}{}{Jsi fakticky trhlej, e jo?}
{128}{}{Vdycky nemyslíš na nikoho jenom na sebe?}
{129}{}{Áh, podívej, to je "hrdina".}
{130}{}{Hej, všichni! Je to sobeckej sráè!}
{131}{}{Áh, zase ty? Kadı s tebou teï chce mluvit.}
{132}{}{Ty, co nenávidíš Chipa!}
{133}{}{To kolem té sleziny je moc špatnı.}
{134}{}{Vsadím se, e nìkdo snìdl Chipova játra.}
{135}{}{Zajímalo by mì, jestli Chip bude vùbec nìkdy v poøádku.}
{136}{}{Myslím, e Chip je nejlepší!}
{137}{}{Dokonce, i kdy nemá ádnou slezinu, udìlala bych ho ve vteøinì!}
{138}{}{Dìkuji ti za snahu dostat zpátky Chipovu slezinu.}
{139}{}{Udìlal jsi pro Chipa, co jsi jen mohl.}
{140}{}{Další fráze o Chipovi.}
{141}{}{Zajímalo by mì, jak ta slezina chutnala...}
{142}{}{Jaj! Teï mùu mít Chipa a jeho slezinu!}
{143}{}{Zrovna teï jdu navštívit Chipa!}
{144}{}{Chip je nejlepší!}
{145}{}{Mám tì rád. Jsi dobrák.}
{146}{}{Jsem tak šastná kvùli Chipovi.}
{147}{}{Nyní je Chip úplnı mu.}
{148}{}{Chceš si se mnou a s Chipem uít?}
{149}{}{Udìlal jsi to dobøe s tou Chipovou slezinou.}
{150}{}{Jak to od tebe velmi nesobecké!}
{151}{}{Suze je zpátky! Skvìlı!}
{152}{}{Suze je zpátky... Zatracenì!}
{153}{}{Suze na mnì byla vdycky hodná.}
{154}{}{Mám rád Suze.}
{155}{}{Dìkuju ti za její záchranu.}
{156}{}{Nìkteøí lidé se potøebují nauèit, aby se netoulali.}
{157}{}{Kdo ví?}
{158}{}{Chudák Badger. Moná potøebuje nìkoho, kdo by ho utìšil.}
{159}{}{Radìji se pùjdu pøesvìdèit, e je Badger v poøádku.}
{160}{}{Badger je roztomilı, ale není to ádnı snílek.}
{161}{}{Zajímalo by mì, proè Badger poøád tak prdí a krká.}
{162}{}{Badger tak prdí asi proto, e je smutnı.}
{163}{}{Chudák Badger.}
{164}{}{Je to drsnej svìt, v nìm ijeme.}
{165}{}{Suze by to mìla vìdìt nejlíp.}
{166}{}{Jestli si bereš loï, mìli bysme jí asi opustit.}
{167}{}{Omlouvám se za to, v jakém je tahle loï stavu.}
{168}{}{Take si vezmeš loï, ehm?}
{169}{}{PMV Valdez je dobrı plavidlo -- byl to dobrı domov.}
{170}{}{Myslím, e u je èas, abych si sbalila svoje vìci.}
{171}{}{Uij si tıhle lodì.}
{172}{}{Mnoho štìstí pøi hledání tvıch lidí.}
{173}{}{Já teï pùjdu.}
{174}{}{Doufám, e najdeme jiné místo k bydlení.}
{175}{}{Chudák Badger. Byl skuteènì roztomilı.}
{176}{}{Kdo by chtìl zabít Badgera?}
{177}{}{Badger legraènì smrdìl, ale líbil se mi.}
{178}{}{Slyšela jsem, e Badger byl døív teplouš, ale pak si našel dívku.}
{179}{}{Vdycky jsem si myslela, e je Badger hrubı. Ale takovım roztomilım zpùsobem.}
{180}{}{Vsadím se, e to teï Badger válí se svıma kámošema.}
{181}{}{Badger... ::èuchej::}
{182}{}{Badger byla opravdová pohádková princezna.}
{183}{}{Ty sráèi. Proè jsi ho zabil?}
{184}{}{Myslíš, e se teï pøidáme k hubologistùm?}
{185}{}{Ty pitomèe pitomej.}
{186}{}{Hubologisti tì taky podvedou.}
{187}{}{Jdi do pekla! Jdi do pekla a chcípni!}
{188}{}{Nenávidím tì.}
{189}{}{Ty cucáku.}
{190}{}{Ovce, ovce! Pitomá ovce!}
{191}{}{Bláznivej okultisto!}
{192}{}{Nìkterı lidi jsou prostì blbí od pøírody. Nemyslíš?}
{193}{}{Hele! To je ten idiot, co nedokáe myslet sám za sebe!}