#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš nadšeného Shi.}
{101}{}{Vidíš Mai Da Chianga, majitele Èervenıch 888 Zbraní.}
{102}{}{Tohle je kulatı Shi, kterı vypadá, jako by byl na jetu.}
{103}{}{Ahoj! Vítej u Èervenıch 888 Zbraní! Jsem Mai Da Chiang, majitel. Jak Ti mohu pomoci?}
{104}{}{Grokken di ma!}
{105}{}{Koupím!}
{106}{}{Hledal jsem nìjaké zbranì.}
{107}{}{Øekni mi o tom místì.}
{108}{}{Zapomeò na to.}
{109}{}{Lituji! Nemluvím tvou øeèí! Mìj hezkı den!}
{110}{}{Rrr?}
{111}{}{Ah, zbraò, hm? Dobøe, to je co mám.}
{112}{}{-více-}
{113}{}{Super, super. Dík za tvou práci. Brzy se vra zpìt!}
{114}{}{Více otázek!}
{115}{}{Sbohem!}
{116}{}{Ne, to není dosti dobré. Lituji. Moná nìco jiného?}
{117}{}{Více otázek.}
{118}{}{Ne. Nashle.}
{119}{}{Potøebuješ nìco jiného?}
{120}{}{Koupím!}
{121}{}{Ne. Sbohem.}
{122}{}{Hledal jsem nìjaké zbranì.}
{123}{}{Øekni mi o tom místì.}
{124}{}{Zapomeò na to.}
{125}{}{ijeme tu léta, ale ne vdy jsme tady ili. Dr. Fung zná úplnou historii. Vsadím se, e hledáš to, co teïka hledáme i my.}
{126}{}{Jasòaèka.}
{127}{}{Ne, vlastnì jsem chtìl vìdìt historii. Najdu Funga. Zatím.}
{128}{}{Teï jsme pøevánì rybáøi a vìdci. Naši rybáøi chytají ryby. Naši vìdci pracují na projektu, o nìm prohlašují, e zmìní svìt.}
{129}{}{Zmìní svìt, jak?}
{130}{}{Co dalšího se dìje ve mìstì?}
{131}{}{Hmm. Zajímavé. Mám více otázek.}
{132}{}{Díky. Sbohem.}
{133}{}{Nevím. Oni svoje tajemství nevyzrazují.}
{134}{}{Aha. Co jiného se dìje ve mìstì?}
{135}{}{Aha. Mám více otázek.}
{136}{}{Díky. Nashle.}
{137}{}{Máme dva soky váleènıch umìní ve mìstì. Jsou to Lo Pan, èlovìk zamilovanı sám do sebe a Dragon, kterı miluje ostatní. Øíká se, e kdo zvítìzí, ten rozhodne o budoucnosti váleènıch umìní.}
{138}{}{Aha. Nìco jiného ve mìstì?}
{139}{}{Aha. Mám více otázek.}
{140}{}{Díky.}
{141}{}{Je tu gang tulákù, kteøí se pøestìhovali do tankeru Poseidon Oil 
na molu. Uvnitø ila rùzná individua, ale tito tuláci je zavøeli v
niším podpalubí. Aèkoli jsou to outsideøi, jsme za
tenhle úkol únoscùm vdìèní.}
{142}{}{Nìjaké jiné zprávy?}
{143}{}{Aha. Mám více otázek.}
{144}{}{Díky. Sbohem.}
{145}{}{Vìdci øíkali, e se nìkdo dostal pøes jejich poèítaèovou ochranu a ukradl jejich tajemství.}
{146}{}{Nìjaké jiné zprávy?}
{147}{}{Aha. Mám více otázek.}
{148}{}{Díky. Nashle.}
{149}{}{To je prozatím vše. Mìj se.}
{150}{}{Ty taky.}
{151}{}{Jsi zlodìj, vrah a nièema. Obávám se, e ti budu muset ustøelit prdel, chlapeèku.}

