#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš osobu v legraèním pyamu.}
{101}{}{Vidíš osobu z mìsta Shiù.}
{102}{}{Tato osoba vypadá odlišnì od kterékoliv osoby, jen jsi vidìl pøedtím. Nevypadá to, e by se o tebe pøíliš zajímala.}
{103}{}{Nejsi špeh, e ne?}
{104}{}{Kdo jsi?}
{105}{}{Ryby a moøské øasy. To je vše, co máme.}
{106}{}{Ha ha! Podívej se na ty legraèní kulaté oèi!}
{107}{}{Vypadáš jako Hubologista.}
{108}{}{Odejdi v míru.}
{109}{}{Dlouhı ivot Dragonovi!}
{110}{}{Dolù s Lo Pan!}
{111}{}{Dragon je hrdina.}
{112}{}{Pozor na Lo Pan. Má potíe.}
{113}{}{Ti pankeøi jsou vdy tak hlasití.}
{114}{}{Práce, práce, práce. Rıe, rıe, rıe. ::povzdech::}
{115}{}{Je ivot víc ne tohle?}
{116}{}{Jsme chytøejší, ne si myslíš.}
{117}{}{Dívej! Lao wai!}
{118}{}{Nemyslím, e tì mám rád.}
{119}{}{Dìsíš mì.}
{120}{}{Neubliuj mi, prosím.}
{121}{}{Vsadím se, e Lo Panovi by ses líbil.}
{122}{}{Prosím, nedìlej potíe.}
{123}{}{Mám rád ivot. Neudìlal bych nic, èím bych ho ztratil.}
{124}{}{Odpadkù je èím dál více.}
{125}{}{Pane... ano, pane... sbohem, pane.}
{126}{}{Ha ha! Ten parchant Lo Pan je mrtev!}
{127}{}{Pomohls nám!}
{128}{}{Lo Pan je mrtev!}
{129}{}{Nyní Hubologisté!}
{130}{}{Podívej se na ty legraèní kulaté oèi!}
{131}{}{Vypadáš jako Hubologista.}
{132}{}{Odejdi v míru.}
{133}{}{Dlouhı ivot Dragonovi!}
{134}{}{Dlouhı ivot Císaøi!}
{135}{}{Práce, práce a práce. Rıe, rıe a zase rıe. ::povzdech::}
{136}{}{Je ivot více ne tohle?}
{137}{}{Dragon... je mrtev...}
{138}{}{Ach ne. Dragon je mrtev!}
{139}{}{ivot nemá ádnı vıznam.}
{140}{}{Mìli bychom pøeít... sotva.}
{141}{}{Kdo teï bude náš hrdina?}
{142}{}{A s Dragonem odcházejí i naše sny.}
{143}{}{To nemá smysl.}
{144}{}{Nechte nás uèit naše dìti, aby byly jako Dragon.}
{145}{}{Nyní si musíme vytvoøit nové sny.}
{146}{}{Císaøùv mistrovskı kousek! Mrtev!}
{147}{}{Co se stane teï?}
{148}{}{Doufám, e nás divoši nepøedbìhnou!}
{149}{}{Dobro vdy umírá mladé.}
{150}{}{Doufám, e zimu pøeijeme bez Kena Lee.}
{151}{}{Slyšel jsem, e Ken Lee byl jedinı, kdo drel Císaøe v øadì.}
{152}{}{Slyšel jsem, e Císaø byl jenom "fasáda" pro Kena Lee. }
{153}{}{Práce, práce a práce. Rıe, rıe a zase rıe. ::povzdech::}
{154}{}{Je ivot víc ne tohle?}
{155}{}{Jsme chytøejší, ne si myslíte.}
{156}{}{Podívej. Venkovan!}

{164}{}{Zabils AHS-9? Dobrá práce!}
{165}{}{Tihle hubologisti mì pìknì serou.}
{166}{}{Velectìnı návštìvníku, prokázal jsi nám velkou slubu.}
{167}{}{Smrt hubologistùm!}
{168}{}{Tohle moná urychlí odchod hubologistù odsud.}
{169}{}{Pitomí hubologisti, dokonce si neumí ani ochránit vlastního vùdce.}
{170}{}{Jen doufám, e hubologisti po nás nepùjdou kvùli odplatì.}
{171}{}{Nakonec se domnívám, e pøeci jen nejsi vyzvìdaè.}
{172}{}{Praseèí synu. Zdechni!}
{173}{}{Zostudil jsi svou rodinu!}
{174}{}{Odejdi, lao wai!}
{175}{}{Co u jsi nezpùsobil dost škody?}
{176}{}{Nenávidím tì!}
{177}{}{Opus tohle mìsto!}
{178}{}{Jdi domù ke svım lidem!}
{179}{}{Nezastiòuj mi mùj ivot tvım oblièejem!}
{180}{}{Co bude stát zbavit se tì?}
{181}{}{Pomoc! Pomoc!}
