#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš zdravı pár.}
{101}{}{Vidíš Juana Cruze a Vikki Goldmanovou, dva z New Reno, velice známé filmové hvìzdy.}
{102}{}{Vidíš tmavovlasého mue a plavovlasou enu. Oba jsou velmi atraktivní. Vyzaøují nadšenou víru ve vyšší ideály.}
{103}{}{On: Ahoj! Jsem Juan Cruz! Ona: A já jsem Vikki Goldmanová! Oba: Jsme slavní lidé! A oba dva schvalujeme hubologisty! Oba: Prosím pamatuj, e kadá podobnost mezi námi a lidmi nebo institucemi, ivımi nebo mrtvımi, je èistì náhodná.}
{104}{}{Ah? Cluz? Doldnin?}
{105}{}{Slavní? Co vás èiní slavnımi?}
{106}{}{Podobnost? Co máš na mysli?}
{107}{}{Chci bıt hubologista. Jak se mohu pøidat?}
{108}{}{Hej, Vikki, Dave H. tì miluje.}
{109}{}{Skvìlı. Musím jít.}
{110}{}{On: Ubohé dítì pustiny. Ona: Moná, e by pomohlo zaøazení? On: Ano. Ty, líbilo by se ti zaøazení?}
{111}{}{Ano!}
{112}{}{Ne!}
{113}{}{Ona: Doufám, e to pomohlo. Hodnì štìstí na cestách!}
{114}{}{Sbohem!}
{115}{}{To opravdu ano!}
{116}{}{On: Kdy nepøijmeš naši pomoc... Ona: ... pak ti nemùeme pomoci. Sbohem.}
{117}{}{Sbohem!}
{118}{}{On: Vidíš? Vıuka Hubu potvrdila jejich hodnotu!}
{119}{}{Mám nìjaké otázky.}
{120}{}{Díky. Nashle!}
{121}{}{Ona: Proè? Byli jsme ve filmovém prùmyslu v New Renu. Udìlali jsme stovky filmù, mnoho z nich bylo klasickıch, jako "Top Bun," "Frisky Bizness," a "Days of Rubber".  Kvùli tomu jsme slavní.}
{122}{}{On: Ale pak, jakoto èlen prùmyslu, jsi to skoro nevìdìla.}
{123}{}{Je to hezké koneènì nazıvat vìci pravımi jmény.}
{124}{}{Koho zajímá, jestli TY to schvaluješ? Copak se nemùu sám rozhodnout?}
{125}{}{Dobrá. Mám pro tebe více otázek.}
{126}{}{Díky. Ahoj.}
{127}{}{Ona: Ano, mìl by ses definitivnì rozhodnout. On: A s Hubovou poslední knihou se mùeš nauèit, jak udìlat PRAVÉ rozhodnutí!}
{128}{}{Jeho poslední knihou? On není mrtev?}
{129}{}{"Správnı" vıbìr. Jistì. Co tøeba svobodná vùle?}
{130}{}{Zní skvìle. Jak se mohu pøidat?}
{131}{}{Jistì. Mám více otázek.}
{132}{}{Správnì. Èau.}
{133}{}{On: Více otázek? Pak my máme odpovìdi! Poskytnuté milostí Velkım Kolem, samozøejmì.}
{134}{}{Jak se mohu pøidat?}
{135}{}{Co vás èiní slavnımi?}
{136}{}{Co se nemohu sám rozhodnout spíš, ne nechat slavné, aby rozhodovali za mì?}
{137}{}{Jak se mohu pøidat?}
{138}{}{Hej, Vikki, Dave H. tì miluje.}
{139}{}{Ne, ne, více otázek.}
{140}{}{Ona: [prázdnı ledovı pohled] On: Dìkuji ti.}
{141}{}{Hm... Mám nìjaké otázky.}
{142}{}{To vše je pro mì! Zatím!}
{143}{}{On: Mrtvı? He, he! Moná. Rádi bychom si mysleli, e zapojil všechny své neurony a šel následovat Hvìzdného Otce. Ona: Máme obsáhlé vyuití z jeho trochy zpráv a sotva èitelnıch rukopisù o rozšíøení svìta Hubu. On: Napøíklad, jsme našli útrek, kde se píše: "2 doz. vejce/mléko/TP". Toto je zøejmì vıznamné. Musí to bıt vyslyšeno.}
{144}{}{Hm...správnì. Mám více otázek.}
{145}{}{Jenom proto, e nìjakı suchar nìco napsal, cítíš potøebu uveøejnit VŠECHNO?}
{146}{}{Ano! Velebnı Hub! Vidím záøi! Jak se mohu k vám pøidat?}
{147}{}{Dobøe. Ano.}
{148}{}{On: Ano. Nìkdo si mùe myslet, e napodobujeme jisté lidi. Ona: Ale pravda je, e to je zcela náhodné.}
{149}{}{Ach tak. No, tím se to vysvìtluje. Øekni, mám více otázek.}
{150}{}{Mám to. Zatím.}
{151}{}{Ona: Samozøejmì máš svou svobodnou vùli. Máš monost vıbìru poskytnout své neurony k naplnìní špínou svìta. On: Máš volbu buï ít bezradostnì, bezvıznamnì jako krysa. Oba: Nebo mùeš pøijít na skvìlé pochopení ivota skrz Velké Kolo.}
{152}{}{Neurony? Co jsou zaè?}
{153}{}{Zní skvìle. Jak se mohu pøidat?}
{154}{}{Hm. Myslím, e radši budu ít jako krysa.}
{155}{}{Správnì. Dobøe, musím bìet.}
{156}{}{Ona: Ty se opovauješ nazıvat Huba (veleb jeho vznešenosti) Sucharem? Tady? V pevnosti oddané jeho uèení? On: Vypadni odsud. Jestli s nìkım po cestì odsud promluvíš, budeš napaden. Nevìrèe. Oba: Koneènì jsme se ho zbavily.}
{157}{}{Moná bych na vás mìl asi skoèit. Vdycky jsem nenávidìl vaše filmy. Podívejme se, jak umíte zahrát mrtvé scény.}
{158}{}{Vaše filmy jsou pìknej brak. Nashle.}
{159}{}{Ahoj.}
{160}{}{Ona: Neurony jsou podstatou duší znièenıch ve Velké Válce, zneèišující tvou duševní podstatu a snaící se, abys zbloudil. On: Jestli chceš vìdìt více o naší vıuce, budeš muset navštívit náš kostel.}
{161}{}{Ano, to zní skvìle.}
{162}{}{Slyšel jsem, e to byla science fiction, ale nevìdìl jsem, jak moc. Hub musel bıt tak trochu suchar.}
{163}{}{Dobøe, jsem nesmírnì zvìdavı na to, co máme. Poèítej tam se mnou.}
{164}{}{Hm. Teï právì ne. Mám více otázek.}
{165}{}{Hm... musím jí. Èau.}
{166}{}{On: To je od tebe velmi pøedvídavé myšlení. Ona: Velmi osvícené. On: Nabízíme náš názor lidem -- a kdy naši slavní lidé mohou pøitáhnout více vìøících, snaíme se to pouít.}
{167}{}{Mám další otázky.}
{168}{}{Zajímá mì pøijetí.}
{169}{}{Vidím. Dobrá. Zatím.}
{170}{}{On: Dobøe, je to velmi prosté. Dáme ti prostì informaèní holodisk. Ona: ... ty zasedáš ohlednì krátkého filmu... On: ...a pak si jdi promluvit s AHS-7! Lehké, e ano?}
{171}{}{Dejme se do toho.}
{172}{}{Nemyslím si, e jsem na to pøipraven.}
{173}{}{Ona: To je tvé vısadní právo. On: A já doufám, e pochopíš, e se nebudeš moci potulovat na naší základnì. Ona: tak radìji odejdi -- stráe by po tobì pravdìpodobnì vystøelili, kdyby ses tu poflakoval.}
{174}{}{Gee, dík. Pozvou mì, abych se k nim pøidal a zastøelí mì, kdy nepodepíšu? Dost dobrá hláška.}
{175}{}{Moná bych tì mìla nejprve zastøelit.}
{176}{}{Jsem odsud.}
{177}{}{On: Toto je tvá poslední šance, abys zmìnil rozhodnutí. Ona: Nevidìli bychom rádi, kdyby se ti nìco špatného stalo.}
{178}{}{Jebu tì.}
{179}{}{Fajn. Jak se mohu pøidat?}
{180}{}{Nìco špatného by se TI mohlo stát.}
{181}{}{Nic. Zkusím své šance. Zatím.}
{182}{}{On: Udìlali jsme vše, co jsme mohli. Ona: Hodnì štìstí na cestách.}
{183}{}{Èau!}
{184}{}{Ona: Dave? Kluk od poèítaèù? On: Ha ha! To je ztroskotanec! Vikki je má, je celá moje - ádnım zpùsobem on nebude... omluvte mì, toto je negativní energie, které èelím. Musel jsem zašpinit své neurony. Ona: (šeptá ti) myslím, e Dave je roztomilı, ale nic s ním  nemùu mít, kdy je Juan poblí. On: Ach. Neurony u jsou zase èisté.}
{185}{}{Dobøe. Mám více otázek.}
{186}{}{To je vše. Èau.}
{187}{}{Ona: To nebylo tak špatné, e ne? On: Teï si jdi promluvit s AHS-7 a budeme kamarády v Hubologii. Ona: Jsem tak povznesena! On: Poøizování novıch rekrutù je namáhavé. Ona: Ó, miláèku... On: Ó, miláèku...}
{188}{}{Vrátím se asi pozdìji.}
{189}{}{On: Pøíliš špatné. Ona: Jsi teï zavázanı.}
{190}{}{-hotovo-}
{191}{}{On: Udìlal jsi ivotní rozhodnutí. Ona: A bohuel, bylo to špatné rozhodnutí. Oba: Stráe! Stráe!}
{192}{}{Sakra.}
{193}{}{On: blahopøeji,}
{194}{}{Tak co teï budu dìlat, kdy jsem hubologista?}
{195}{}{Jak s vámi mohu navázat kontakt, hoši?}
{196}{}{Je toho moc, co jsem chtìl. Zatím!}
{197}{}{}
{198}{}{}
{199}{}{On: Mohl jsi promluvit s Harry Rocketem na place. Tøeba potøebuje nìjakou pomoc. Ona: Nebo Tys mohl promluvit s AHS-7 nebo AHS-9. Ti mají vìtšinou nápady. On: Nebo jsi mohl sledovat vysílání modliteb. Ona: Nebo jsi mohl zpùsobit škodu mezi nepøáteli Kola.}
{200}{}{Díky. Jak s vámi mohu navázat kontakt, hoši?}
{201}{}{Díky. To je vše, co jsem chtìla vìdìt.}
{202}{}{Ona: Je to smutné -- protoe Hvìzdnı Otec ví, e jsi milı -- ale mi to nevíme. On: Ale jsme oba lichotníci! Ona: Moná nìkdy bychom mohli všichni jít do New Rena a udìlat spolu film.}
{203}{}{V poøádku. Co jiného lze zde dìlat jako hubologista?}
{204}{}{V poøádku. Zatím.}
{205}{}{Ona: Lhaní je špatné pro tvé neurony. On: To je pravda. Ona: Proto musím bıt upøímná a øíkám ti, e nejsi pøitalivı. On: Ale my tì poøád milujeme jako kamaráda - následovníka Hubu!}
{206}{}{Gee, díky. Tak co jiného se tady dá dìlat jako hubologista?}
{207}{}{Cokoliv. (mumlá a trhne sebou)}
{208}{}{Blahopøeji, noví rekruti!}
{209}{}{Jsem Vikki Goldmanová!}
{210}{}{A já jsem Juan Cruz!}
{211}{}{Jsme slavní lidé, jak u jistì víte.}
{212}{}{Myslíme, e Hubologie je cesta spásy.}
{213}{}{Víme, e Hubologie je cesta, po které se má jít.}
{214}{}{Mohu usmait brouky pouhou myšlenkou!}
{215}{}{Vypadám dobøe ve staniolovıch èepicích!}
{216}{}{Moná, kdybys tvrdì pracoval na vylepšení sebe sama, mohl bys s námi vycházet.}
{217}{}{To bychom uvítali.}
{218}{}{Ano. My vdy hledáme pøátele...}
{219}{}{... pokud jsou oni schopni se pøizpùsobit.}
{220}{}{A pokud jsou natolik zkaeni jako my.}
{221}{}{Jsme AHS-5.}
{222}{}{Nìkdy mùeš bıt AHS-5.}
{223}{}{Kdy pøispìješ hodnì penìz, mùeš bıt AHS-5 dokonce rychleji.}
{224}{}{Ale nemysli si, e tì chceme jenom pro peníze.}
{225}{}{Ne, my ti chceme POMOCI.}
{226}{}{A o tom všem je Hubologie.}
{227}{}{[potlesk]}

{228}{}{Doufám, e tvé osvícení jde dobøe. Ona: Máme takovou... velkou... nadìji pro tebe.}

{229}{}{Lekce 1: Zde máme vìènost Velkého Kola. (ukazuje na nìco) A tady mi stojíme. (ukazuje na nìco) Teï jediné, co musíme udìlat je, jít velmi daleko a setkat se tam s našimi hvìzdnımi bratry.}
{230}{}{Mui, budeme potøebovat mnoho párù bot.}

{231}{}{On: Teï si jdi promluvit s AHS-7 a budeme kamarádi v Hubologii! Ona: Jsem tak povznesena! On: Získávání novıch rekrutù je namáhavé. Ona: Ó, miláèku... On: Ó, miláèku...}
