#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš rozeného Shi mue, kterı vypadá, jako by vìdìl vše.}
{101}{}{Vidíš Kena Lee, císaøského poradce.}
{102}{}{Vidíš rozeného Shi mue s brılemi, jen se usmívá.}
{103}{}{Co bys rád, pøíteli?}
{104}{}{Co chceš?}
{105}{}{Co pro tebe mohu udìlat?}
{106}{}{Ty?}
{107}{}{Kdo jsi?}
{108}{}{Co je tohle místo?}
{109}{}{Hledám nìjaké ztracené vesnièany.}
{110}{}{Potøebuji palivo.}
{111}{}{Rád bych mluvil s Císaøem.}
{112}{}{Hubologisté mi poruèili, abych zabil Císaøe.}
{113}{}{Nic. Díky. Èau.}
{114}{}{Jsem Ken Lee, poradce Císaøe. A ty, mùj pøíteli, jsi trochu prostoduchı, tak si pamatuj tohle: Jestli hledáš Enklávu, pak si musíš vzít na to tanker Poseidon. Budeš potøebovat palivo pro tanker. Máš mé poehnání.}
{115}{}{Díky!}
{116}{}{Jsem Ken Lee. Jsem poradce Císaøe. Císaø mi radí, abych s tebou nehovoøil a tak tedy nebudu. Nashle, blázne.}
{117}{}{Vrrr!}
{118}{}{Ach cestovateli, nemohu ti pomoci. Moná, e bys našel odpovìdi na své otázky jinım zpùsobem. Nashle.}
{119}{}{Nashle!}
{120}{}{Jsem Ken Lee. Jsem poradce Císaøe Shi. Pøedevším šíøím Císaøovu moudrost. A kdo jsi ty?}
{121}{}{Rád bych vidìl Císaøe.}
{122}{}{Jsem.}
{123}{}{Pøipadáš mi spíš jako pøerostlı poskok.}
{124}{}{Nikdo dùleitı. Sbohem.}
{125}{}{Tohle je Ocelovı Palác Císaøe. Toto je srdce Shi-mìsta.}
{126}{}{A kde je Císaø?}
{127}{}{Jakı druh vızkumu tady provádíte?}
{128}{}{Jaké jsou dìjiny tohoto místa?}
{129}{}{Aha. Zatím.}
{130}{}{Jestli si pøeješ vidìt Císaøe, pak mi musíš øíct své jméno.}
{131}{}{V poøádku. Jsem}
{132}{}{Jistì. Mé jméno je}
{133}{}{Ano.}
{134}{}{Zapomeò na to.}
{135}{}{Ne kadı má šanci vidìt Císaøe. Nejprve musíš dokázat, co jsi zaè. Pøeješ si to dokázat?}
{136}{}{Ano.}
{137}{}{Ne. Mìl jsem dost testù za posledních pár mìsícù, ty mi staèí na celı ivot.}
{138}{}{Nevìøím, e by tì Císaø rád vidìl. Bylo mi øeèeno, abych zakázal vstup tìm, kteøí mì urazili nebo tìm, kteøí èiší zlobou. Ty dìláš obojí, cestovateli. Nashle.}
{139}{}{-hotovo-}
{140}{}{Uráky tì nikam nedovedou, cestovateli, vyjma vyhození z Ocelového Paláce. Kontroluj laskavì svùj jazyk.}
{141}{}{Polib mi.}
{142}{}{Dobrá.}
{143}{}{Císaø zùstává skryt od modlících se oèí. Protoe mım úkolem je fungovat jako Císaøova obrazovka, nemùu a nepovím ti, kde je.}
{144}{}{Dobrá. Mám více otázek.}
{145}{}{Dobrá. Èau.}
{146}{}{Provádíme vızkum, kterı zmìní svìt. Abys dostal více odpovìdí na své otázky, mìl bys vyhledat Dr. Wong Yi Tzea.}
{147}{}{To udìlám. Mám více otázek.}
{148}{}{Ano. Èau.}
{149}{}{Pøeili jsme ztroskotání ponorky. Kdy jsme byli u toho, rozebrali jsme ponorku a z ní jsme vytvoøili Palác. Nìkdo tomu nevìøí.}
{150}{}{Hm. To zní témìø, jako byste se chtìl s nìkım o nìco vsadit.}
{151}{}{Aha. Díky. Èau.}
{152}{}{Jo. Vidìl jsem nìkteré tvé filmy. Tohle jistì není tvé pravé jméno?}
{153}{}{Jistì, e je.}
{154}{}{Ne. Mé pravé jméno je}
{155}{}{Jméno je vše, co potøebuješ, starochu.}
{156}{}{To bude takøka nemoné. Dobrı den.}
{157}{}{-hotovo-}
{158}{}{Jistì, musíš mi více vìøit ne doposud. Vím, jak "biz" pracuje. Byl jsem v New Reno pøedtím.}
{159}{}{Dobøe, jmenuji se}
{160}{}{To je mé opravdové jméno! Teï mì nech, a si promluvím s Císaøem!}
{161}{}{Vıbornì. Tohle po tobì poaduji: na sever odtud je malá vojenská základna, jmenuje se Navarro. Je tam mnoství vertibirdù. Potøebujem plány a nákresy na vırobu nìkterıch našich vlastních. Jdi a pøines je a budeš moci jít navštívit Císaøe.}
{162}{}{Máš to.}
{163}{}{Zapomeò na to.}
{164}{}{Rozmyslíš si, zda podstoupíš náš test?}
{165}{}{Ne.}
{166}{}{V poøádku. Udìlám to.}
{167}{}{Ztracení vesnièané? O tom sem nic neslyšel. Moná Císaø by o nich vìdìl.}
{168}{}{Mám více otázek.}
{169}{}{Dík. Udìlám to.}
{170}{}{Musíš dokonèit druhı test: Hubologisté jsou našimi nepøáteli. Jejich vùdce, AHS-9, nechává unášet a potom vymıvat mozky našich dìtí. Zabij ho pro dobro Shi a já ti poradím, jak se dostat k Císaøovi.}
{171}{}{Je dobrej ivej, stejnì jako mrtvej.}
{172}{}{Myslím, e ne.}
{173}{}{Ne? Sklièuje mì to, ale rozumím. Hodnì štìstím. Kdy se rozhodneš jinak, víš, kde mì najít.}
{174}{}{Jistì, e ano. Mám více otázek.}
{175}{}{Jo. Èau.}
{176}{}{Jsem celı nervózní ohlednì tvého pokusu. Nashle.}
{177}{}{Nashle.}
{178}{}{Vsadit se s nìkım? Kdekdo, kdo provádìl vızkum mìsta Shi, by mohl vìdìt, e jeho základ je troska téhle ponorky. Nemá cenu dohadovat se s tìmi, kteøí budou tvrdit, e tady není ádná ponorka.}
{179}{}{To ti asi moc nezvedne náladu.}
{180}{}{To jistì ano. A já jsem s tìmito lidmi v kontaktu kadı den. Alas!}
{181}{}{Dobøe, mám více otázek.}
{182}{}{Jé, chudáku. Nashle.}
{183}{}{Jsi jistì hoden pøijmout naše palivo. Vìøím, e se ti mohu svìøit s naším tajemstvím. V zadní místnosti najdeš silové pole k velkému poèítaèi, kterı byl vypnutı. Zadej heslo "CSPDMSHR-Shih-huang-ti-X9372" a dostaneš spojení na Císaøùv poèítaè. Císaø bude schopen pøenést naše palivo tam, kam ho potøebuješ.}
{184}{}{Dík.}
{185}{}{Stráe! Je mezi námi nepøítel! stráe!}
{186}{}{Opravdu oni? Mohu ti zaruèit naši pomoc, kdy slíbíš, e zabiješ AHS-9. }
{187}{}{Je tak dobrı ivı jako mrtvı.}
{188}{}{Ne.}
{189}{}{Vıbornì. Doufám, e brzy uslyším o tvém úspìchu.}
{190}{}{To uslyšíš. Mám více otázek.}
{191}{}{To ano. Nashle.}
{192}{}{V takovém pøípadì mùeš bıt pouze nepøítel. Nashle.}
{193}{}{Nashle.}
{194}{}{Smrtí AHS-9, Velkého a Hrozného, hubologisté nebudou pøedstavovat ádnou hrozbu nám a našim badatelùm. Dobøe provedené. Máš naši vdìènost. Chtìl by sis promluvit s Císaøem?}
{195}{}{Ano.}
{196}{}{Právì teï ne. Mám další otázky.}
{197}{}{Prokázals, e jsi pøítel Shi. Vìøím, e ti mohu svìøit tajemství. V místnosti vzadu najdeš silové pole k velkému poèítaèi, kterı byl vypnut. Zadej heslo "CSPDMSHR-Shih-huang-ti-X9372" a dostaneš spojení s poèítaèem Císaøe. Doufám, e tohle se ti bude hodit.}
{198}{}{Císaø je POÈÍTAÈ?}
{199}{}{Mám to. Díky.}
{200}{}{Ano. Zásobuje naše dìjiny, vızkum a projektové monosti pro budoucnost. Je to daleko lepší ne nìjakı chybující èlovìk -- jeho podnìty pak jenom dolaïujeme s našimi vlastními zkušenostmi lidské rasy.}
{201}{}{Já... vidím. Dobøe, dìkuji za tvùj èas. Budu zachraòovat vesnici.}
{202}{}{Naši zvìdové øíkali, e jsi dal plány vertibirdu hubologistùm. Ukradni je pro nás a my tì odmìníme.}
{203}{}{Máš to. Mám více otázek.}
{204}{}{Vùbec ne.}
{205}{}{Dìkuji za plány vertibirdu, cestovateli. Co pro tebe mohu udìlat?}
{206}{}{Mám otázky.}
{207}{}{Hm... Nic.}
{208}{}{A obdríš plány vertibirdu, dej je Dr. Wongovi Yi Tze. On se u postará o jejich dobré vyuití.}
{209}{}{Dobøe. Mám další otázky.}
{210}{}{Dobøe. Èau.}

{211}{}{. Rád bych vidìl Císaøe.}
{212}{}{.}

{213}{}{Nezapomeò, musíš vzít plány k Dr. Wongovi Yi Tze.}
{214}{}{Jsi tady, abys mì zase uráel? Myslím, e ne.}
{215}{}{Jak u jsem vysvìtlil, budu potøebovat znát tvé jméno.}
{216}{}{V poøádku, to je }
{217}{}{Zapomeò na to, ty idiote!}
{218}{}{Nezapomeò, Císaø oèekává smrt AHS-9.}
{219}{}{Lituji. Ale nemohu ti nabídnout palivo, které máme. Moná, kdybys pohovoøil s Císaøem?}
{220}{}{Jak to mohu udìlat?}
{221}{}{Mohu se jen zeptat na jinou otázku?}
{222}{}{Pøeji si, abych ti mohl nabídnout palivo, ale bohuel naše sklady jsou prázdné. Byly rozptıleny nìjakımi prostøedky hubologistù. Je moné, e bys byl schopnı najít nìkoho, aby se zase vrátily zpìt.}
{223}{}{Mohu nyní vidìt Císaøe?}
{224}{}{Zdvoøile ti pøipomínám, e pokud jsi nedodal plány vertibirdu Dr. Wongovi Yi Tze, pak ti nemohu zaruèit pøísup k Císaøi. Doufám, e rozumíš.}

#Ken Lee's guard floats
{500}{}{Okamitì odejdìte nebo zavolám stráe.}
{501}{}{Odejdìte nyní. Toto je druhé varování.}
{502}{}{Tohle je poslední varování.}
