#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš muže, který vypadá spíše jako prodavaè.}
{101}{}{Vidíš Lao Chou, prodavaèe.}
{102}{}{Vidíš muže v pìkném, komfortním obleku.}
{103}{}{Dobrý den! Vítej v mém obchodì zvaném Flying Dragon 8.}
{104}{}{Co pro tebe mohu udìlat?}
{105}{}{Hyperbola, parabola - základ života je škola!}
{106}{}{Vìcièky!}
{107}{}{Kdo jsi?}
{108}{}{Hledám nìjaké vybavení.}
{109}{}{Poohlížím se po nìjakých informacích.}
{110}{}{Nashle.}
{111}{}{Chceš nìco koupit?}
{112}{}{::kývneš hlavou::}
{113}{}{::zavrtíš hlavou::}
{114}{}{To je všechno co tu máme.}
{115}{}{- konec -}
{116}{}{No, obávám se, že tohle je všechno co jsem pro tebe mohl udìlat. Pìkný den.}
{117}{}{-hotovo-}
{118}{}{Jmenuju se Lao Chou. Øídím tenhle podnik Flying Dragon 8. Jsem známý tím, že obchoduji i... s informacemi.}
{119}{}{S jakými informacemi?}
{120}{}{Aha. Chtìl bych nìjaké vybavení.}
{121}{}{V tomhle mìstì se stane málo vìcí, o kterých bych nevìdìl. Samozøejmì mi taky musíš položit ty správné otázky. Co teda potøebuješ vìdìt?}
{122}{}{Hledám nìjaká upgrady pro mé vybavení.}
{123}{}{Kde bych mohl najít plány vertibirdu?}
{124}{}{Potøebuju najít palivo pro PMV Valdez.}
{125}{}{Pochopil jsem, že potøebuju nìjaký FOB k pøístupu do poèítaèe Valdezu.}
{126}{}{Potøebuju nìjaké souèásti do poèítaèe PMV Valdezu.}
{127}{}{Ještì poøád hledám slezinu.}
{128}{}{Slyšel jsem, že nìjaké létající stroje odvezli náklad vesnièanù tím smìrem.}
{129}{}{Už nic. Nashle.}
{130}{}{Promluv si s Crocketem, tam v táboøe Hubologistù. Je to jejich hlavní vìdec.}
{131}{}{Díky. Chci více informací.}
{132}{}{Díky. Nashle.}
{133}{}{Podívej se na sever, do Navarra. Je tam skrytá základna blízko benzínové pumpy.}
{134}{}{Díky. Chci více informací.}
{135}{}{Díky. Nashle.}
{136}{}{Zkoušel si se podívat do tìch starých Vaultù? Slyšel jsem, že jsou bohaté starobylých informací a technologií.}
{137}{}{Díky. Chci více informací.}
{138}{}{Díky. Nashle.}
{139}{}{A slezinu? Ha ha! Ano, Chip z Valdezu prohrál svojí slezinu v kartách. Prodal jsem jí Dr. Wongovi. Byl jí fascinován.}
{140}{}{Dr. Wongovi? Kde bych ho mohl najít?}
{141}{}{Jak si mohl prodat slezinu?}
{142}{}{Díky. Mám další otázky.}
{143}{}{Aha, takhle. Nashle.}
{144}{}{Dr. Wong je hlavním vìdcem v Ocelovém Paláci. Tam ho zastihneš.}
{145}{}{Jak mimochodem ztratil tu slezinu?}
{146}{}{Díky. Potøebuju více informací.}
{147}{}{Díky. Nashle.}
{148}{}{Byl opilej. Velmi, velmi opilej. Celej veèer se chlubil svojí slezinou. A pak jí vsadil.}
{149}{}{Takže ty sis vzal jeho SLEZINU?}
{150}{}{Aha. Dobøe, mám ještì nìjaké otázky.}
{151}{}{Ano. Byl to dluh. Je to èestný muž.}
{152}{}{Aha. Potøebuju více informací.}
{153}{}{Jsi nemocnej, nevychovanej bastard, že jo?}
{154}{}{Dobøe. Nashle.}
{155}{}{Jsi neèestnej chlap. Nechci tì mít teï ve svým krámu. Pøijï nìkdy jindy.}
{156}{}{Kdykoliv.}
{157}{}{Ne. Pøiletìli ze severu, proletìli nám nad hlavami a letìli dále smìrem k moøi.}
{158}{}{Tamhle za obzor? Ale jak se tam sakra dostanu?}
{159}{}{Ano. Øekni mi kde jsou nebo tì otevøu jako konzervu sardinek.}
{160}{}{Mno... žádná z našich lodí není schopná urazit tuhle vzdálenost. Ledaže...}
{161}{}{Ledaže...?}
{162}{}{Díky za tvojí "pomoc". Vezmu si tvé rady k srdci.}
{163}{}{... ledaže by se použil ten starý tanker v doku, tím by to snad šlo. Je to stará loï, ale možná je stále funkèní, kdyby se na ní udìlalo pár oprav. Zeptej se v pankáèù v pøístavu, mají víc informací.}
{164}{}{Díky. Chci více informací.}
{165}{}{Díky. Nashle.}
{166}{}{Øíká se, že Hubologisti pøišli nedávno k velkému množství paliva. Domluv se s nimi.}
{167}{}{Díky. Chci více informací.}
{168}{}{Díky. Nashle.}
{169}{}{Mìl bys zkusit nìjakého z Shi vìdcù v Ocelovém paláci. Snad ti mohou pomoci s tvojí potøebou paliva.}
{170}{}{Díky. Chtìl bych více informací.}
{171}{}{Díky. Nashle.}
{172}{}{Jsi nepøítel mého lidu. Chcípni!}
{173}{}{Vykonal jsi hodnì pro mùj lid, když jsi zabil AHS-9. Doufám, že ti budu nìèím nápomocen.}
{174}{}{Kdo jsi?}
{175}{}{Hledám nìjaké vybavení.}
{176}{}{Hledám nìjaké informace.}
{177}{}{Nashle.}
{178}{}{Ty už jsi je dal hubologistùm. Ne?}
{179}{}{Jo... Mùžu se zeptat na nìco jiného?}
{180}{}{Jo... Nashle.}