#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš stráného v lehkém obleku, kterı se lehce nudí.}
{101}{}{Vidíš stráného z Paláce.}
{102}{}{Vidíš Palácového stráného.}
{103}{}{Pokraèuj dál v chùzi a nic se ti nestane.}
{104}{}{Máš tady nìjakou práci?}
{105}{}{Hlídáme tì.}
{106}{}{Nepokoušej se o nic smìšného.}
{107}{}{Chovej se k našim lidem s úctou.}
{108}{}{Nedotıkej se toho, to je poslední varování.}
{109}{}{Straò se tohoto místa.}
{110}{}{Ustup, lao wai, nebo do tebe nastøílím tolik eleza, e budeš pøi chùzi cinkat.}
{111}{}{Ustup pomalu od toho. Udìlej krok k tvım zbraním a jsi mrtvı.}
{112}{}{A na to ani nepomyslíš.}
{113}{}{Pøestaò s tím. HNED!}
{114}{}{Chcípni, nepøíteli lidu!}
{115}{}{Posílám tì do pekla roztaveného kovu!}
{116}{}{Mùe mít Buddha slitování s tvou duší!}
{117}{}{Trp, nepøíteli!}
