#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš arogantního Shi gangstera.}
{101}{}{Tohle je Lo Pan, pánovitı a bezcitnı mu.}
{102}{}{Vidíš Shi gangstera, v hedvábném obleèení. Jeho ruce jsou mozolnaté a tvrdé. Vypadá nebezpeènì.}
{103}{}{Co chceš?}
{104}{}{Daggle aggle aggle!}
{105}{}{Kdo ty?}
{106}{}{S kım jsi to bojoval?}
{107}{}{Kdo jsi?}
{108}{}{Chci umìt bojovat jako ty. Nauè mì to.}
{109}{}{Chci tì vyzvat.}
{110}{}{Zapomeò.}
{111}{}{Táhni odsud, idiote. Nemám si s tebou co øíct.}
{112}{}{GRR!}
{113}{}{Jsem Lo Pan. Nejlepší bojovník ve mìstì, kromì Dragona. Ale jednoho dne i on umøe. A se to stane, zaènu uèit ostatní mùj styl.}
{114}{}{Nauè mì to!}
{115}{}{Dekju.}
{116}{}{Chceš se uèit? Víš co to obnáší? Mrkneme se na to.}
{117}{}{-hotovo-}
{118}{}{Uèit tì? To si nemyslím. Vypadáš a pøíliš sebejistì. Vypadni.}
{119}{}{Co to... ?}
{120}{}{Oh, podívejte, idiot. Nechci s tebou mluvit. Jdi pryè.}
{121}{}{Duhhh...}
{122}{}{On? Dragon. Je to slaboch kterı peèuje o svou slabost.}
{123}{}{Lidi jsou ovce. Obslu se sám.}
{124}{}{Co? Jsi tak zkaenı?}
{125}{}{Vidím. Mám ještì nìjaké otázky.}
{126}{}{Zkaenı? Tìko. Jenom chytrı. Moná jestli se tak zajímáš o dobro mezi lidmi, navštiv Dragona. Má rád prosáèky a slabochy, jako jsi ty.}
{127}{}{-hotovo-}
{128}{}{Ano, to udìlám. Bohuel, pøekáí mi Dragon. Náš vzájemnı boj je a pøíliš vyrovnanı. Potøebuji nìkoho schopného, kdo mi pomùe.}
{129}{}{Já jsem váš èlovìk.}
{130}{}{Aha. No, mám ještì nìjaké otázky.}
{131}{}{Aha. No, nashle.}
{132}{}{Opravdu? Umíš bojovat pìst proti pìsti, noha proti oblièeji, bez spoléhání se na brnìní a zbranì?}
{133}{}{Umím, ale proè?}
{134}{}{To zní poctivì. Co se vlastnì bude dít?}
{135}{}{Oh. Tak, v tom pøípadì, u musím jít.}
{136}{}{Protoe jinak mì budou venkovani nenávidìt a bude mì stát o mnoho více úsilí vydìsit je, a porazím Dragona.}
{137}{}{Chápu. Tak jdeme na to.}
{138}{}{Chápu. Ale mám ještì otázky.}
{139}{}{Aha. Jasnì. Zatím.}
{140}{}{Budeme bojovat na smrt, nebo chceš jenom vidìt, kdo je lepší?}
{141}{}{A do konce. V pohodì tì sejmu.}
{142}{}{Jenom zkoušku umìní. Nechci tì zabít.}
{143}{}{Nijak. Zapomeò na to.}
{144}{}{Vıbornì. Doufám, e u máš pøipravenı hrob. To tì poslal Dragon?}
{145}{}{Ano. Dìlám to pro Shi.}
{146}{}{Ne. Dìlám to, protoe si myslím e jsi hajzl.}
{147}{}{Aha, tvrïák, co? Napøed se utkáš s mımi mui, a potom uvidíme, jestli jsi zaslouíš bojovat se mnou.}
{148}{}{-zaèít-}
{149}{}{Jsem Lo Pan. Jsem také "zapøísáhlı nepøítel" Dragona. Nechápu, proè trvá na tom, e budeme nepøátelé. Jenom bojuji tak dobøe jako on, a myslím si, e on je slaboch, kterı nechává ít ostatní ve svém stínu. Jsme nepøátelé, protoe bojujeme stejnım stylem, a ten kdo vyhraje, se stane dìdicem tradic.}
{150}{}{V pìstním souboji taky nejsem nejhorší. Nechceš to zkusit?}
{151}{}{To je zajímavé. Musí bıt vdìènı. Mám ještì nìjaké otázky.}
{152}{}{Díky. Zatím.}
{153}{}{Moná jsem hajzl, ale tohle si pøed mımi lidmi nikdo dovolovat nebude. Tohle tì bude bolet, ne umøeš.}
{154}{}{-hotovo-}
{155}{}{Potom jsi hlupák, pes kterı skáèe jak nìkdo jinı píská. Jenom se ti vysmìji a budeš umírat.}
{156}{}{- zaútoèit nyní, s brnìním a zbranìmi -}
{157}{}{- vstoupit do ringu, odloit brnìní a zbranì, a bojovat holıma rukama -}
{158}{}{Dobøe. Alespoò jsi svım vlastním pánem. Opravdu si troufneš bojovat bez brnìní a beze zbraní?}
{159}{}{- zaútoèit nyní, s brnìním a zbranìmi -}
{160}{}{- vstoupit do ringu, odloit brnìní a zbranì, a bojovat holıma rukama -}
{161}{}{Beee, oveèko, beee! Bì zpátky ke svému páníèkovi. Nemám ti u co øíct.}
{162}{}{-hotovo-}
{163}{}{Neøekl jsem ti, e si máš o svıch vıèitkách svìdomí promluvit s Dragonem? Ten tì pochopí. Já ne. Teï odejdi.}
{164}{}{-hotovo-}
{165}{}{Musím pøipustit, e bojuješ dokonce lépe ne já sám. Nechceš zkusit Dragona?}
{166}{}{Ano. Udìlám to teï hned.}
{167}{}{Ale to není mùj boj.}
{168}{}{Jistì, Ale mám ještì nìjaké otázky.}
{169}{}{Ne, to není. Ale Dragon mì poráí. jestli máš nìjakou èest, sejmeš ho. Ale vlastnì, nikdy jsem neoèekával hrdost od lao wai.}
{170}{}{Dobøe. Mám otázky.}
{171}{}{Jasnì, kdy myslíš. Zatím.}
{172}{}{Právì jsem se vrátil. Nìjakı lao wai se snail ukrást naše tajemství. Dragon a já jsme ho zabili. Musím uznat, e nám to spolu šlo dobøe.}
{173}{}{Vıbornì. Mám otázky.}
{174}{}{Vıbornì. Zatím.}
{175}{}{Dragon je mrtvı. Nejsem nijak nadšen, ale alespoò se nám teï ty trapné tradice nemotají do cesty na kadém kroku. Díky.}
{176}{}{Vıbornì. Mám otázky.}
{177}{}{Vıbornì. Zatím.}

{200}{}{Lo Pan odhalil tvùj postup ale podaøilo se ti uniknout.}
{201}{}{Podívej, nemám rád, kdy se mi nikdo hrabe ve vìcech, take si jdi krást nìkam jinam. Odejdi.}
{202}{}{Vyzval jsem tì k odchodu, ne ke smrti. Tak dobøe.}
{203}{}{Dragonùv test je u splnìn!}

{204}{}{Pro dnešek trénink skonèil. Vra se zítra.}

{205}{}{Jsem Mistr Khung, tvá poslední zkouška.}
{206}{}{Jsem Imbot. Mìj se na pozoru.}
{207}{}{Jsem Wejungh. Pøiprav se.}
{208}{}{Jsem Loopal. Dál se nedostaneš.}
{209}{}{Jsem Smitty. Je èas na vıprask.}
{210}{}{Jsem Mistr Krall. Je po tobì.}
{211}{}{BOJ!}
{212}{}{Potøebuješ víc trénovat.}
{213}{}{Pøiprav se!}
{214}{}{Porazil jsi Lo Pana v souboji. Z nìjakého dùvodu vypadá slunce o nìco jasnìjší.}
{215}{}{Moji mui u byli poraeni. Zkouška je sloena. Jdi a bojuj s Dragonem.}
{216}{}{U jsi dost dobrı. Jdi se nauèit støílet nebo nìco jiného.}

#training messages
{217}{}{Zaèneme. Následuj mùj pøíklad.}
{218}{}{Pro dnešek trénink skonèil.}
{219}{}{Uèení ti jde dobøe.}

{220}{}{U jsi porazil moje mue. Nikdo jinı tì nechce vyzvat.}

{221}{}{Pomohl jsi mi, ani bys nìco tušil. Kdy je Dragon mrtvı, nemusím se øídit tìmi zastaralımi morálními tradicemi.}
{222}{}{Bylo mi potìšením. Zatím.}
{223}{}{Rádo se stalo. Nashle.}
{224}{}{Rádo se stalo. Mùu se ještì zeptat?}
{225}{}{Prosím. Já ptát?}

{226}{}{Vyhrál jsi!}
{227}{}{Prohrál jsi!}
{228}{}{Další protivník!}

{229}{}{Hej, podívej co jsem našel.}

{230}{}{nejdøíve musíš dokázat, e to svedeš.  Utkáš se postupnì s pìti mımi bojovníky.  Kdy je porazíš, sloíš poslední zkoušku.}
{231}{}{Co to je?}
{232}{}{Vypadá to jako velké potíe. Nashle.}
{233}{}{Budeš muset porazit mì.  Avšak, ádnı z tìchto soubojù nebude na smrt - samozøejmì kvùli bezpeèí mıch muù. [zašklebí se]}
{234}{}{Jdeme na to!}
{235}{}{O Dragona se postarej sám.}
{236}{}{(Lo Pan  si tì prohlíí. Najednou se jeho ruka mihne a udeøí tì do oblièeje døív, ne stihneš zareagovat.) Nejsi dost dobrı.}
{237}{}{Ok, Ale mùu se na nìco zeptat?}
{238}{}{Dobøe. Zatím.}
