#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš tankerového tuláka.}
{101}{}{Vidíš pankáèe.}
{102}{}{Vidíš velmi hezkého, cynicky se tváøícího mue, kterı má na sobì potrhané obleèení.}
{103}{}{Nic se nedìje.}
{104}{}{Z toho rybího smradu je mi na blití.}
{105}{}{Èím døíve se pohneme, tím líp.}
{106}{}{Nejlepší vìc na tom bıt koèovníkem je ta svoboda.}
{107}{}{Ve skuteènosti radši umøu, ne bych nìkomu dovolil mi vládnout.}
{108}{}{Nikdo neøídí mùj ivot! Jsem svım vlastním pánem!}
{109}{}{Jsem svùj vlastní šéf.}
{110}{}{Jsem unikátní! Tak jako kadı jinı!}
{111}{}{Nìkdy mì ten celosvìtovì nošenı cynismus nudí.}
{112}{}{Pøíštì chci najít kmen Gótù.}
{113}{}{Vidìl jsem Selmyho a Barru torn hned vedle schodù.}
{114}{}{Slyšel jsem, e Shi Císaø je nelidsky chytrı.}
{115}{}{Ti Shiové vypadají legraènì.}
{116}{}{Jsem nepøedpojatı, ha?}
{117}{}{Budu sdílet mou dívku s tebou, kdy ty budeš tu svou sdílet se mnou.}
{118}{}{Podívej se na tyhle nové pankáèe. Jsou jak modely.}
{119}{}{AHS-9 nás šidil a bude šidit i tebe, kdy se necháš.}
{120}{}{Ovce. Nejsi nic jiného ne zabijácká ovce.}
{121}{}{Øekni tìm parchantùm Hubologistùm, e my se nikdy nevzdáme.}
{122}{}{Nikdy nepøejdu k Hub.}
{123}{}{Doufám, e jsi na sebe pyšnı.}
{124}{}{Copak si nikdy neuvìdomí, e zabití našeho "vùdce" z nás neudìlá jejich následovníky?}
{125}{}{Jsi hajzl.}
{126}{}{Baah! Baah!}
{127}{}{Tak jaké to bylo, dostat to od mutanta?}
{128}{}{Ublíil Ti ten velkı, silnı muouš Francis?}
{129}{}{Francis hraje s tebou?}
{130}{}{Francis je poøádnì velkı chlapec.}
{131}{}{Sterej velkej Francis, co?}
{132}{}{}
{133}{}{Hej! Je to dìvka!}
{134}{}{Hej, jestli od nás potøebuješ nìjakou pomoc, neobtìuj se poádat.}
{135}{}{Jaj. Mluvící hajzl!}
{136}{}{To jsi opravdu takovej hajzl?}
{137}{}{Obìtuješ našeho malıho Chipa, e ano?}
{138}{}{Ubohı Chip.}
{139}{}{Jé, podívej. To je "hrdina".}
{140}{}{Podívejte. Je to mizernı sobec!}
{141}{}{Kadı s tebou chce teï mluvit.}
{142}{}{Ty, co nenávidíš Chipa!}
{143}{}{Mohu pro tebe nìco udìlat? Pøíliš špatné!}
{144}{}{Nemluv na mì.}
{145}{}{To je od tebe hezké, e ses snail kvùli Chipovì slezinì.}
{146}{}{Alespoò ses pokusil.}
{147}{}{Ubohı Chip.}
{148}{}{Chudák starej Chippie...}
{149}{}{Chip je na tom hùø. To je moc špatnı.}
{150}{}{Se slezinou jde vše dobøe!}
{151}{}{Jupí... hrdina a nálezce sleziny.}
{152}{}{Nevìdìl jsem, e se sleziny vyrobìjí.}
{153}{}{Dìkuji za záchranu Chipa.}
{154}{}{Haló tam, ty milovníku Chipa!}
{155}{}{Jsme šastni za Chipa.}
{156}{}{Dìkuji za záchranu Chipa.}
{157}{}{Nyní se bude s Badgerem ít líp.}
{158}{}{Vdycky jsem mìl Suze rád. Jsem rád, e není mrtvá.}
{159}{}{Zajímalo by mì, jestli bude Suze chùvou i mıch dìtí?}
{160}{}{Zabij pøíšeru, zachraò pøítelkyni... existuje taky nìjakej hrdinskej kousek, do kterıho nefušuješ?}
{161}{}{Mùeš zachránit i mojí holku? He, he!}
{162}{}{Moná, e se s tebou Badger vyspí, aby zachránil svou dívku.}
{163}{}{Vsadím se, e Badger je nyní opravdu šastnı.}
{164}{}{Moná mùeš poádat Badgera o nìjakou laskavost.}
{165}{}{Ubohı Badger. Ubohá Suze.}
{166}{}{Varoval jsem ji, aby tam nechodila...}
{167}{}{... hnusnı pøíšery...}
{168}{}{Teï je mi Badgera opravdu líto.}
{169}{}{Smrt na lodi. Ubohá Suze.}
{170}{}{Èlovìèe... bude to nìkdy trochu lepší?}
{171}{}{Tam je to nebezpeèné!}
{172}{}{Jeiši... proè ona tam jen chodila?}
{173}{}{Mìli bysme zvednout kotvu.}
{174}{}{Mìli bysme z tıhle lodi vypadnout.}
{175}{}{Chystáš se vzít tanker na západ?}
{176}{}{Hádám, e je tak doba na to, z tıhle lodi zmizet.}
{177}{}{Jsem pøipravenej odsud vypadnout.}
{178}{}{U mám všechno sbalenı.}
{179}{}{Nemyslím si, e bych chtìl jet na západ.}
{180}{}{}
{181}{}{}
{182}{}{}
{183}{}{Znáš nìjaká dobrá místa, kde by se dalo usadit?}
{184}{}{Chci se ujistit, e to místo je v pohodì, døív ne se tam usadím.}
{185}{}{Co takhle šou nana parníku?}
{186}{}{Jeišikriste... u ádnej Badger.}
{187}{}{Kdo ho mohl zabít?}
{188}{}{O poèítaèích vím hovno. A ty?}
{189}{}{Èlovìèe... Badger znal všechny ty skvìlá místa, kam se dalo zajít.}
{190}{}{U nikdy tu kapelu neuslyším hrát!}
{191}{}{Pitomí zabijáci... zabít Badgera... pitomci.}
{192}{}{Jsem tak plnej nenávisti.}
{193}{}{Chci se za Badgera pomstít!}
{194}{}{ivot bez Badgera nemá cenu.}