#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš pøátelsky vypadajícího pankáèe.}
{101}{}{Vidíš Marca.}
{102}{}{Vidíš pøátelsky vypadajícího pankáèe.}
{103}{}{Ty èubèí synu -- jak si nám to mohl udìlat?}
{104}{}{Co pro tebe mùu udìlat, mama-jamma?}
{105}{}{Co pro tebe já mùu udìlat, mama-jamma?}
{106}{}{Ooh! Ooh! Aah!}
{107}{}{Kdo jsi?}
{108}{}{Co je tohle za místo?}
{109}{}{Kdo to tu má na starosti?}
{110}{}{Nic. Mìj se.}
{111}{}{Hmm. Promiò, s tímhle ti nemùu píchnout. Mìl bys zkusit nìkoho jinıho.}
{112}{}{Anks?}
{113}{}{Jsem Marc. Jsem absolutní chytrák a vím úplnì všecko.  ::usmívá se::}
{114}{}{Oh. Mám jinou otázku.}
{115}{}{Èauky.}
{116}{}{Tohle je Poseidon Marine Vessel Valdez - taky zvanı jako PMV Valdez. Jestli chceš vìdìt více informací o Valdezu, nejlépe se mùeš zeptat kapitána.}
{117}{}{Kapitán? Kdo to je?}
{118}{}{Mám další otázky.}
{119}{}{Èaudy.}
{120}{}{Na starosti? Nikdo z nás to tady nevede.}
{121}{}{Odkud jste všichni pøišli?}
{122}{}{Mám další otázky, na kterı se chci zeptat.}
{123}{}{Èaudy.}
{124}{}{Kapitán je ostrej vyslouilej vojenskej chlapík. Sedí támhle nahoøe a pozoruje okolí. On ví hodnì o téhle lodi.}
{125}{}{Díky. Mám více otázek.}
{126}{}{Díky. Mìj se.}
{127}{}{Oh, všichni pøes pouš. Slyšeli jsme mnoho vìcí o San Franciscu od našich poutníkù. Pøedkové nìkterıch z nás zde ili pøed Velkou válkou. Chceš vìdìt více?}
{128}{}{Ano.}
{129}{}{Ne, ale chtìl jsem se tì zeptat na nìco jiného.}
{130}{}{Ne, to je všechno.}
{131}{}{Jsme skupina muzikantù, poulièních kejklíøù a umìlcù. Mysleli jsme, e se vrátíme na místo, které je velmi známé svobodou umìní, ale i svobodou jako takovou. Pøišel jsem sem, abych se tu usadil. Chceš slyšet ještì víc?}
{132}{}{Ano.}
{133}{}{Ne, ale chtìl jsem se tì zeptat na nìco jiného.}
{134}{}{Ne, to je všechno.}
{135}{}{Mnoo, kdy jsme se sem dostali, rozhodli jsme se, e tu budeme kempovat, dokud nezjistíme, jak znovu zprovoznit tento tanker. Nebo dokud nevymyslíme nìco jiného.}
{136}{}{Zjistili jste, jak zprovoznit tanker?}
{137}{}{Øekni mi nìco o hubologistech.}
{138}{}{Øekni mi nìco o Shi.}
{139}{}{Mám další otázky.}
{140}{}{Díky. Mìj se.}
{141}{}{Myslím si, e kapitán zjistil, jak to udìlat -- ale k tomu potøebujeme nejdøíve nìkolik vìcí. V podstatì jsme se vzdali této myšlenky, a øeknu ti pravdu -- teï u máme jiné plány.}
{142}{}{Co jsou zaè?}
{143}{}{Kde bych našel kapitána?}
{144}{}{Chtìl jsem se zeptat na nìco jiného.}
{145}{}{Èaudy.}
{146}{}{Jsou bláznivı. Vùbec jim nevìø -- to bys musel bıt mentálnì postienej anebo blázen. Je zajímají pouze tvoje peníze a duše. Kvùli tomu jsou schopni znièit jeden druhého. U mnohokrát jsem vidìl, e se to stalo.}
{147}{}{Zjistili jste, jak zprovoznit tanker?}
{148}{}{Øekni mi nìco o Shi.}
{149}{}{Mám další otázky.}
{150}{}{Èaudy.}
{151}{}{Je to dobrá partie, kdy s nima kámošíte. Jsou to sice takovı malı nedùvìøiví outsajdøi, ale kvùli tomu na nì nemùete mìnit svùj názor. Mají opravdu hrozné zvyky a mluví srandovnì, ale jinak jsou v pohodì.}
{152}{}{Zjistili jste jak zprovoznit tanker?}
{153}{}{Øekni mi nìco o hubologistech.}
{154}{}{Mám další otázky.}
{155}{}{Èaudy.}
{156}{}{Chceš vìdìt, jakı máme plány? Chystáme se najít místo, které by nebylo postiené a znièené lidskou hrabivostí a kde bychom mohli znovu ít lepší ivot.}
{157}{}{A u víš jak to udìláš?}
{158}{}{Mám další otázky.}
{159}{}{Díky. Èaudy.}
{160}{}{Doufáme, e se mùeme vyhnout omylùm této spoleènosti. Sakra, u to nemohlo bejt fakt horší, ne to je.}
{161}{}{Zjistili jste jak zprovoznit tanker?}
{162}{}{Øekni mi nìco o hubologistech.}
{163}{}{Øekni mi nìco o Shi.}
{164}{}{Mám další otázky.}
{165}{}{Díky. Mìj se.}

{166}{}{Vidìl jsi tu nìkde Badgerovu pøítelkyni nìkde kolem?}
{167}{}{Myslím, e sem jí vidìl jít támhle dolù. Je tam díra na severní stranì paluby.}
