#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš obchodníka.}
{101}{}{Vidíš obchodníka.}
{102}{}{Vidíš velice živého obchodníka ze Shi. Jako všichni ostatní, vypadá, že je plný vìtru.}
{103}{}{Kupte si chobotnièku! Je velice chutná!}
{104}{}{Máš rád ryby? Máme ryby!}
{105}{}{Hej! Hej! Kup to! Kup to!}
{106}{}{Nekupuj u nìho nic! Je to obyèejný zlodìj!}
{107}{}{Pojï sem a podívej na tohle! Bude se ti to moc líbit!}
{108}{}{Prohlédni si to! Prohlédni si to!}
{109}{}{Hej, lao wai! Chceš obchodovat? Dìlám obchody!}
{110}{}{Pojï sem! Pojï sem!}
{111}{}{Myslíš si, že je to dobrý? Tak si to prohlídni!}
{112}{}{Máme ryby, máme moøské rostliny, máme rýži, máme... ehm...}
{113}{}{Nemáme tu toho moc, jen to, èemu se tu daøí, ale zato toho máme zásoby!}
{114}{}{Jdi domù! Jdi domù, lao wai!}
{115}{}{Nechceme s tebou obchodovat!}
{116}{}{Odejdi! Odejdi!}
{117}{}{Tvoje peníze tu nechceme! Hned odejdi!}
{118}{}{Hned odejdi!}
{119}{}{Nemáš rád boj? Mai Da Chiang má pro tebe zbranì!}
{120}{}{Jsi milovník a ne bojovník, eh?}
{121}{}{Hej, ty žravá kobylko!}
{122}{}{Pojï si koupit chobotnièku! Je velice chutná!}
{123}{}{Máš rád ryby? Máme ryby!}
{124}{}{Hej! Hej! Kup to! Kup to!}
{125}{}{Nekupuj nic u nìho! Je to obyèejný zlodìj!}
{126}{}{Pojï sem a podívej se na tohle! Bude se ti to líbit!}
{127}{}{Prohlídni si to! Prohlídni si to! Prohlídni si to!}
{128}{}{Hej lao wai! Chceš obchodovat? Dìlám obchody!}
{129}{}{Pojï sem! Pojï sem! Pojï sem!}
{130}{}{Myslíš si, že je to dobrý? Tak si to prohlídni!}
{131}{}{Máme ryby, máme moøské rostliny, máme rýži, máme... ehm...}
{132}{}{Nemáme tu toho moc, jen to, èemu se tu daøí. Toho ale máme zásoby!}
{133}{}{Obchodní poradce zemøel!}
{134}{}{Chlape... dá nám nový vùdce nové taxy?}
{135}{}{Chudák Ken Lee.}
{136}{}{Mìsto Shi už nikdy nebude to samé bez starého Ken Lea.}
{137}{}{Máš rád ryby? Máme ryby!}
{138}{}{Hej! Hej! Kup to! Kup to!}
{139}{}{Nic od nìho nekupuj! Je to obyèejný zlodìj!}
{140}{}{Pojï sem a koukni na tohle! Bude se ti to líbit!}
{141}{}{Prohlédni si to! Prohlédni si to! Prohlédni si to!}
{142}{}{Hej lao wai! Chceš obchodovat? Dìlám obchody!}
{143}{}{Pojï sem! Pojï sem! Pojï sem!}
{144}{}{Myslíš si, že je to dobré? Tak si to prohlédni!}
{145}{}{Máme ryby, máme moøské rostliny, máme rýži, máme... ehm...}
{146}{}{Nemáme tu toho moc, jen to, èemu se tu daøí, ale zato toho máme zásoby!}
