#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš velmi dobøe obleèeného mue.}
{101}{}{To je AHS-9, Velikı a Strašlivı.}
{102}{}{Vidíš velmi dobøe obleèeného mue.}
{103}{}{Rouháš se ve jménu Hubu! Musíš zemøít!}
{104}{}{Tvá vìrolomnost nezná hranic!}
{105}{}{Velkı Kruh tì znièí!}
{106}{}{Jsi v pøítomnosti AHS-9, Velikého a Strašlivého. O co jej ádáš?}
{107}{}{Agh a nu, AHS!}
{108}{}{Hledám své lidi. Slyšel jsem, e sem pøišli v létajících lodích.}
{109}{}{Mám pro tebe mnoho otázek, AHS-9.}
{110}{}{Osvícená z NCR chtìla, abych doruèil dopis. Øíkala nìco o odmìnì?}
{111}{}{Osvícená z NCR chtìla, abych doruèil dopis. Tady ho máš.}
{112}{}{Oh, AHS-9, pøišel jsem a pøinesl dopis od tvého zástupce v NCR. Skláním se pøed tvou slávou.}
{113}{}{Jsi mrtvı. Sbohem, starı mui.}
{114}{}{Nic, sorry.}
{115}{}{Ano, mé dítì?}
{116}{}{Hinchoaf? (Rozumíš mi?)}
{117}{}{Tralala chrb gany. (Oh, bohudík. Hledám své lidi. Potøebuji se dostat pøes velkou vodu.)}
{118}{}{Poopy pants! (No, díky za tvùj èas. U bych mìl jít. Je radost s tebou mluvit.)}
{119}{}{Nerozumím ani slovo z toho, co øíkáš. Snad bys mìl navštívit Juana nebo Vikki a promluvit s nimi.}
{120}{}{Díky!}
{121}{}{Samozøejmì, dítì. Spojení vyèistilo tvé neurodyny a spojilo je s mımi a s pøáními Velkého Kruhu. Co potøebuješ?}
{122}{}{Aagga diggle doodle doo! (Oh, bohudík. Hledám své lidi. Potøebuji se dostat pøes velkou vodu.)}
{123}{}{B-b-b-enny (Nic, dìkuji. Je hezké, e si s tebou mùu popovídat. Zatím!)}
{124}{}{Jestli budeš souhlasit a prokáeš mi laskavost, mohu ti pomoci, dítì.}
{125}{}{Oik? (O co jde? Rád pomohu.)}
{126}{}{Ne!}
{127}{}{Mùj protivník, Císaø mìsta Shi, mi znepøíjemòuje ivot. Chci, abys ukonèil ten jeho. Jako protislubu zajistím, e se dostaneš tam, kam potøebuješ.}
{128}{}{Ays! (Udìlám to.)}
{129}{}{Ne!}
{130}{}{Jestli si to rozmyslíš, dej mi vìdìt. Pamatuj si, já mohu bıt jediná cesta k tomu, jak se znovu shledat s rodinou.}
{131}{}{Opke? (Co je ta laskavost?)}
{132}{}{Didgeroo! (Díky, Radìji nikomu nic nedluím. Sbohem!)}
{133}{}{Dobøe. A skonèíš, dej mi vìdìt, a já zaènu podnikat kroky k tomu, abychom našich cílù dosáhli spoleènì. Sbohem, dítì.}
{134}{}{Nota knazdar! (Sbohem, AHS-9. Jsi skvìlı mu.)}
{135}{}{Je tvùj úkol splnìn? Tvá budoucnost a budoucnost Kruhu na této planetì na tom závisí.}
{136}{}{Unh-uh (Ještì ne. Jen jsem tì pøišel pozdravit)}
{137}{}{Pracuji na tom. Mám nìjaké otázky.}
{138}{}{Ještì ne. Vrátím se zpìt.}
{139}{}{Také tì zdravím. Nyní, prosím, dokonèi svou práci, a ti i já mohu pomoci.}
{140}{}{Ng! (Ano, pane!)}
{141}{}{Z tvého vzezøení je patrné, e se ti podaøilo zbavit svìt zneèišujících neurodynù Císaøe.}
{142}{}{Jirsa! (Ano, podaøilo. A jak to vypadá s tvou èástí naší dohody?)}
{143}{}{Ano, podaøilo. Nyní ádám o tvou podporu a pomoc mım lidem.}
{144}{}{Kdy pùjdeš do mìsta Shi do dokù, najdeš tam PMV Valdez. Vstup do lodi. Vydej se vpravo, a nahoru na kapitánskı mùstek. Stiskni tlaèítko Go a tanker tì dopraví k tvému cíli.}
{145}{}{Anks! (Bylo mi potìšením, AHS-9. Pøeji ti všechno nejlepší. Zatím.)}
{146}{}{Létající lodì? To musíš mluvit o Enklávì a jejich vertibirdech.}
{147}{}{Ano, myslím.}
{148}{}{Enkláva? Jaká enkláva?}
{149}{}{Vìø mi, dítì, mluvíš o Enklávì.}
{150}{}{Ano, dobøe. Jak je najdu?}
{151}{}{Enkláva je zbytek minulosti -- neurodyn, kterı bude teprve pøipojen. Mají skryté základny po celém povrchu staré Kalifornie a jejich nejsilnìjší pevnost je daleko na západì za vodami.}
{152}{}{Jak se tam dostanu?}
{153}{}{Jak tohle všechno víš?}
{154}{}{To u, mé dítì, musíš objevit sám. Zeptej se po okolí a mìl bys objevit pravdu.}
{155}{}{Velmi pouèné. Mám další otázky.}
{156}{}{Jak tohle všechno víš?}
{157}{}{Kdy myslíš. Zatím.}
{158}{}{Dítì, já jsem AHS-9. Vidím mnoho vìcí, které se dìjí v reálném svìtì. Máš ještì další otázky, nebo se mohu vrátit ke svım meditacím?}
{159}{}{Další otázky.}
{160}{}{Vra se ke svım meditacím. Jsem hotov.}
{161}{}{Zabil jsi Císaøe a znièil jeho oblíbence?}
{162}{}{Ano.}
{163}{}{Pak u není nikdo, kdo mi mùe stát v cestì! Nevidím potøebu bıt zavázán pouhému nástroji. Sbohem -- a dobøe e je pryè!}
{164}{}{Proè, ty svinì. Teï tì zabiju.}
{165}{}{Oh. No, jestli to tak má bıt. Sbohem.}
{166}{}{Dopis od Osvícené? Takhle si teï øíká? Bah. (bere si od tebe dopis) A slíbila odmìnu? Tady je odmìna -- moje vdìènost. Hezkı den.}
{167}{}{Tak takhle? Staøíku, u teï jsi tuhej.}
{168}{}{Err, Mám nìjaké otázky.}
{169}{}{Gee, bezva. Zatím.}
{170}{}{S otázkami se obra na AHS-7. Já jsem AHS-9 Velikı a Strašlivı, a mám na starosti mnoho vìcí. Neobtìuj mne, zvíøe.}
{171}{}{Kdy neodpovíš na moje otázky, odpovíš na moje zbranì.}
{172}{}{Kdy myslíš.}
{173}{}{Ahh, dopis od mého jednatele. Škoda e si øíká "Osvícená" -- ukazuje to, e opravdu není osvícená. Máš moji vdìènost.}
{174}{}{ádnı problém. Pøesto, mám otázku nebo dvì.}
{175}{}{Vıbornì. Zatím.}
{176}{}{Ano, mé dítì?}
{177}{}{Kdy odlétá vesmírná loï?}
{178}{}{Máš pro mne nìjaké úkoly?}
{179}{}{Kam jdou všechny peníze, které poskytujeme?}
{180}{}{Ale, nic. Zapomeò na to.}
{181}{}{Mùj protivník, Císaø mìsta Shi, mi znepøíjemòuje ivot. Chci, abys ukonèil ten jeho. Jako protislubu zajistím, e se dostaneš tam, kam potøebuješ.}
{182}{}{Jistì, šéfe. Zatím.}
{183}{}{Radìji ne.}
{184}{}{Najdi Badgera, jeho pøítomnost drí tankerové tuláky pohromadì. Zbav naše mìsto jeho pøítomnosti. A to vykonáš, navštiv AHS-7.}
{185}{}{Jistì, šéfe. Zatím.}
{186}{}{Radìji ne.}
{187}{}{Nejsem si vìdom toho, e bych o nìco ádal, dítì. Zabij ho!}
{188}{}{Ne.}
{189}{}{Oh, tak dobøe. Udìlám to.}
{190}{}{Odmítáš poslouchat rozkazy AHS-9, Velikého a Strašlivého? Potom tedy zemøi.}
{191}{}{Tak pojï.}
{192}{}{Poèkej, rozmyslel jsem si to.}
{193}{}{Pøíliš pozdì, zvíøe. Ukázal jsi, e se ti nedá vìøit. Zemøi!}
{194}{}{-hotovo-}
{195}{}{Dítì, jsou urèité vìci, kterım není urèeno, abys je znal. [Blahosklonnì se usmál.]}
{196}{}{Tak dobøe. Mám další otázky.}
{197}{}{Hm. Zatím.}
{198}{}{ESS Quetzel odstartuje, a budou hvìzdy pøipraveny. }
{199}{}{Dobøe. Mám ještì otázky.}
{200}{}{Díky. Zatím.}
{201}{}{Tvá narušená aura mi øíká, e zde nemáš èestné úmysly. Povìz mi, dítì, chceš nìco vytìit ze svého riskování?}
{202}{}{Ano.}
{203}{}{Ne.}
{204}{}{Ne, jenom chci, abys zemøel.}
{205}{}{Tedy, toto je má nabídka: vra se k Shiùm a odstraò Ken Leeho a Císaøe. Zaplatím ti více penìz, ne o kolika se ti kdy snilo.}
{206}{}{Ne, to si nemyslím.}
{207}{}{Plácneme si, tlusochu.}
{208}{}{Pak tedy jdi a zniè ty otravné duše. Èekám zprávu o tvém úspìchu. (Blaenì se usmál.)}
{209}{}{Zatím.}
{210}{}{Ne, poèkej, rozmyslel jsem si to. Chci tì mrtvého.}
{211}{}{Ach, dítì, jak jenom mùeš takto sejít z cesty pravdy? Z tvé aury vidím, e se mne chystáš zabít. Jsem hoøce zklamán. Hoøce. No dobøe. Pøejdìme k tomu.}
{212}{}{Ano, Jdeme na to. Pojdi.}
{213}{}{Pamatuj si, musíš navštívit AHS-7 a splníš svùj úkol.}
{214}{}{Všechny naše potøeby jsou splnìny. Je èas pro mojí meditaci.}
