#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš hubologistu v kápi. Nìjak, tenhle vypadá odlišnì.}
{101}{}{Vidíš AHS-7, druhého velitele.}
{102}{}{Vidíš hubologistu v kápi.}
{103}{}{Stráže! Vetøelec! Zabijte to!}
{104}{}{Ty. Proè jsi tady.}
{105}{}{Aaagh! Nu! Nee!}
{106}{}{Mám zprávu pro AHS-9 od Osvícené z NCR.}
{107}{}{Jdu si promluvit s Crocketem o nìjakém brnìní.}
{108}{}{Chci se tu porozhlédnout.}
{109}{}{Pøípadnì bych se k vám pøidal.}
{110}{}{Kdo jsi?}
{111}{}{Pøišel jsem vás všechny zabít.}
{112}{}{Ah, ubohé dítì. Chtìl by ses pøidat?}
{113}{}{Jo!}
{114}{}{Ne!}
{115}{}{Ubohé dítì. Už jsi byl pøijat, teï nemluv. Pojï dál.}
{116}{}{Dik!}
{117}{}{Jdi dovnitø a vyhledej Juana a Vikki. Oni ti pomohou. Hodnì štìstí, dítì.}
{118}{}{Dik!}
{119}{}{::jeho hlas ztvrdnul:: Potom nevidím jediný dùvod, proè bys mìl být vpuštìn. Nashle.}
{120}{}{'Ej!}
{121}{}{Tak dobøe. Ale rychle, protože on je zaneprázdnìný, opravdu zaneprázdnìný muž.}
{122}{}{Dobøe.}
{123}{}{Tohle není místo, které je otevøené pro náhodné výletníky. Nashle.}
{124}{}{-hotovo-}
{125}{}{Výbornì! Vejdi, jen vejdi. Promluv si s Juanem Cruzem a Vikki Goldmanovou - jsou to sice osobnosti, ale budou s tebou mluvit.}
{126}{}{Kdo jsou?}
{127}{}{Ooh! Osobnosti!}
{128}{}{Jsem AHS-7, druhý velitel tohoto zaøízení.  Než se zeptáš: AHS znamená Alokovaný Hledaè Smyslu, což by se dalo vysvìtlit tak, že jsem vyèistil sedm úrovní neurodynù z mé duše. Z tohoto dùvodu jsem mnohem osvícenìjší a sem blíže støedu pohybu Velkého Kruhu, než jsi ty. A to znamená, že mi øekneš, co tu chceš. Hned teï.}
{129}{}{Mám dopis pro AHS-9 od Osvícené z NCR.}
{130}{}{Jdu si promluvit s Crocketem o nìjaké zbroji.}
{131}{}{Chci se tu porozhlédnout.}
{132}{}{Pøípadnì bych se k vám pøidal.}
{133}{}{Pøišel jsem vás všechny zabít.}
{134}{}{Jsou to hvìzdy z New Rena. Pochopili smysl našich evangelií a pøišli si proèistit své neurodyny.}
{135}{}{Kde je mohu najít?}
{136}{}{No, zapomeò na to. Jdu pryè.}
{137}{}{Najdeš je v modlitebnì, jak ukazují našim nováèkùm a ostatním jak pøínosné je být hubologistou.}
{138}{}{Tak se na nì pùjdu podívat!}
{139}{}{Já budu porotce. Ukaž mi tu show.}
{140}{}{Zapomeò na to. Jdu pryè.}
{141}{}{Tak, už jsi mluvil s Juanem a Vikki. Pøipojíš se tedy k našim pøátelùm v hledání osvícení Velkého Kruhu?}
{142}{}{Oh ano. Ano, ano, ano.}
{143}{}{Jistì.}
{144}{}{Ne, teï ještì ne. Mohu se k vám ještì vrátit?}
{145}{}{Nemyslím si, že mì to zajímá. Sorry.}
{146}{}{Sakra nikdy. Váš šílený kult by zasloužil srovnat se zemí.}
{147}{}{::usmál se:: Nebudeš toho litovat. Staneš se souèástí naší komunity. Oh... jsi èlovìk který umí používat zbranì. Chceš ty své použít ke službì Velkému Kruhu?}
{148}{}{Ano.}
{149}{}{Možná pozdìji.}
{150}{}{Neotálej pøíliš dlouho, než se vrátíš s odpovìdí. Tvoje neurodyny budou zaplòovány zneèištìním více a více, dokud nezahájíme oèistný proces.}
{151}{}{Rozmyslel jsem si to. Pøipojím se.}
{152}{}{Máš pravdu. Popovídáme se pozdìji.}
{153}{}{Mùžeš z komunity bezpeènì odejít, poutníku, ale nedoporuèoval bych vracet se. Jestli nepracuješ s námi, potom pracuješ proti nám -- a já bych tì velice nerad vidìl trpìt.}
{154}{}{Díky za zájem. Zatím.}
{155}{}{Nemyslím si, že já bych byl ten, kdo by trpìl. Sbohem.}
{156}{}{Srovnat se zemí? SROVNAT SE ZEMÍ? STRÁŽE! ZABIJTE NEVÌØÍCÍHO!}
{157}{}{-hotovo-}
{158}{}{Tak. Mìl jsi èas pøemýšlet o svém rozhodnutí. Pøipojíš se k nám?}
{159}{}{Ano.}
{160}{}{Ne.}
{161}{}{Potøebuji více èasu.}
{162}{}{Nemáš více èasu. Rozhodni se teï.}
{163}{}{Dobøe, pøidám se.}
{164}{}{Zapomeò na to. nemám rád vedení pevné ruky.}
{165}{}{Tyranští Shiové soutìží s naší mocí a zasévají zmatek mezi naše bratry tím, že znají zpùsob, jak ovlivnit neurodyny. Vìøíme, že když bude jejich Císaø mrtvý, spatøí omyly své cesty. Zabiješ Císaøe?}
{166}{}{Jistì, udìlám to.}
{167}{}{Ne, Shiové mi nikdy nic neudìlali.}
{168}{}{Možná si to rozmyslíš. Jestli ano, dej mi vìdìt. Nyní, je zde nìco, co ti Hub mùže poskytnout, rekrute?}
{169}{}{Ano, mám nìjaké otázky.}
{170}{}{No, v tomto okamžiku ne, díky.}
{171}{}{Pøemýšlel jsi o pomoci v našem boji proti utiskovatelùm Shi? Hvìzdný Otec ti požehná, jestli se zúèastníš naší køížové výpravy.}
{172}{}{Stále nevím, jestli to chci udìlat.}
{173}{}{Udìlám to.}
{174}{}{Snad mohu pomoci tvé utrápené duši. Co potøebuješ?}
{175}{}{Kde mohu získat palivo pro tanker Poseidon?}
{176}{}{Kde mohu najít význam všech vìcí, které øíkáš?}
{177}{}{Kdy odlétá loï?}
{178}{}{Kde je Crocket?}
{179}{}{Nic, dìkuji. Zatím.}
{180}{}{Dej nám vìdìt, až splníš úkol.}
{181}{}{Ano. Mám ještì otázky.}
{182}{}{Jasnì. Zatím.}
{183}{}{Odstranil jsi císaøskou skvrnu z této reality?}
{184}{}{Ještì ne.}
{185}{}{Ano, AHS-7. Už je mrtvý.}
{186}{}{Opravdovým vùdce tulákù na tankeru je prý nìjaký Badger. Když bude mrtvý, pochopíš naši pozici. Odstraníš ho?}
{187}{}{Udìlám to.}
{188}{}{Nièím mi neublížil. Radìji ne.}
{189}{}{Tak... rozmyslel sis tu vìc s tím Badgerem?}
{190}{}{Udìlám to.}
{191}{}{Ne, nemohu to udìlat.}
{192}{}{Odstranil jsi toho "Badgera"?}
{193}{}{Ještì ne.}
{194}{}{Ano. Je po nìm.}
{195}{}{Jeho lidé by mìli uvítat Hub! Všechno bude v poøádku! Tvé služby zasluhují pochvalu!}
{196}{}{Díky! Mám další otázky.}
{197}{}{Všechno dìlám pro Kolo. Sbohem.}
{198}{}{Vlastnì, tebe teï zabiju také.}
{199}{}{Nyní, když je loï naplnìna palivem, èekáme pouze na pokyn od AHS-9 Velikého a Strašlivého, a odstartujeme.}
{200}{}{Urèitì. Mám nìjaké otázky.}
{201}{}{Díky. Zatím.}
{202}{}{Na druhou stranu potøebujeme k našemu startu už tak vzácné palivo, abychom mohli letìt k naší planetì Quetzel, ale odkud ho vzít. Snad u Shiù?}
{203}{}{Huh. Mám další otázky.}
{204}{}{Ano, možná.}
{205}{}{Vím, že Shi mají velké zásoby paliva. Možná jim mùžeš nìjaké ukrást.}
{206}{}{To je nápad. Ale mám dotazy.}
{207}{}{Možná. Díky.}
{208}{}{Staèí použít holodisk, kerý ti dali Juan a Vikki. V nìm najdeš vše potøebné.}
{209}{}{Díky. Další otázky?}
{210}{}{Díky.}
{211}{}{Až AHS-9 obdrží svou vizi z Hubu, odejdeme, a pøipojíme se k nìmu v nebeské slávì!}
{212}{}{Jasnì, chvála Kruhu nebo tak nìco. Mám další otázky.}
{213}{}{Velmi informativní. Díky.}
{214}{}{Obyèejnì je ve své laboratoøi, kde pracuje na zpùsobu, jak zlepšit naše tìla a naše duše.}
{215}{}{Díky. Chci se zeptat na nìco jiného.}
{216}{}{Díky.}
{217}{}{Než se opravdu staneš jedním z nás, musíme provést poèáteèní zeta scan - propojení. Jsi pøipraven na scan?}
{218}{}{Ne! Žádný scan!}
{219}{}{Jistì. Jdeme na to.}
{220}{}{Bez scanu se k nám nemùžeš pøidat. Jsi si jistý, že chceš odmítnout?}
{221}{}{Absolutnì jistý. Nechci se nechat upravovat vašimi stroji.}
{222}{}{Oh, tak dobøe. Scanujte mì.}
{223}{}{Odstranili jsme nìkteré tvé neèisté neurodyny. Nyní jsi klasifikován jako AHS-1. jsi pøipraven pøipojit se k našemu vznešenému spolku?}
{224}{}{Oh ano.}
{225}{}{Ne. Teï už nechci.}

{226}{}{Lekce 1: Zde máme vìènost. Tady, tady je Quetzel. (na nìco ukazuje) A zde jsme my. (ukazuje jinam) Nyní, vše co musíme udìlat, je vydat se na dlouhou cestu odtud tam.}
{227}{}{Teda, to budeme potøebovat hodnì bot.}

{228}{}{Mohu o tom stále pøemýšlet?}
{229}{}{Opìt ty? Co?}
{230}{}{Je zde ještì nìco, co mám udìlat?}
{231}{}{Tvá pøítomnost zde je nežádoucí. Prosím, odejdi.}