#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš nìkoho s kapitánskou èapkou.}
{101}{}{Vidíš kapitána A. Ron Meyerse.}
{102}{}{Vidíš pankáèe v potrhaných šatech a kapitánskou èapkou.}
{103}{}{Co tu sakra chceš? S nikým se nebavím, jenom s pøáteli a dobrými lidmi. Nejdøív udìlej nìjakou službu jednomu z mých mužù a pak si pøijï promluvit.}
{104}{}{-hotovo-}
{105}{}{Slyšel jsem, co jsi udìlal pro mé muže. Díky. S èím ti mohu pomoci?}
{106}{}{Ty si kdo?}
{107}{}{Slyšel jsem, že jsi jediný, kdo ví o téhle lodi všechno.}
{108}{}{Proè ti øíkají kapitán?}
{109}{}{Jak chceš tuhle vìc dát do provozu?}
{110}{}{Nic.}
{111}{}{Jsem kapitán. Øídím tuhle loï. Jestli máš nìjaké otázky, jdi si promluvit s nìkým v Shi nebo Badgerem anebo s nìkým jiným. Nemám na tebe èas.}
{112}{}{-hotovo-}
{113}{}{Tahle loï je tanker Poseidon. Je vybavena technikou, která pøežila Velkou válku. Je potøeba FOB, který dovoluje pøístup k místnosti s navigaèním poèítaèem a dále obsahuje IFF radarovou rušièku, který ochraòuje pøed støelami na Poseidon.}
{114}{}{Jak to všechno víš?}
{115}{}{Co to je IFF radarová rušièka?}
{116}{}{Jak tuhle loï rozbìhneš?}
{117}{}{Díky. Nashle.}
{118}{}{Já jsem pracoval s Enklávy. Pak jsem pøišel na to, že to není USA, za co bojuju; ale za ty bohatý starý bastardy, kteøí nechtìli pøijít o svojí moc. Dezertoval jsem a teïka žiji tady s mnohem èestnìjšími lidmi, než byli v Enklávì.}
{119}{}{Mnohem èestnìjší lidé? Tihle hoši?}
{120}{}{Co pøesnì je Enkláva?}
{121}{}{Jak chceš zprovoznit tuhle vìc?}
{122}{}{Nashle.}
{123}{}{Jak budeš øídit tuhle bárku? Naplò jí nejdøíve palivem -- zkus sehnat nìjaké u hubologistù nebo u Shi a až budeš mít i ostatní vìci -- zmáèkneš knoflík. Poèítaè se postará o všechno ostatní, jestli to ovšem ještì bude fungovat. Loï popluje pøímo k ropné plošinì, a oni po tobì nebudou støílet, protože tahle loï má IFF radarovou rušièku. Ujisti se, že máš všechno co budeš potøebovat k pøístupu: FOB, funkèní navigaèní poèítaè a palivo. Jasný, jak facka, ne?}
{124}{}{Jasnì. Jak tohle všechno víš?}
{125}{}{Co je to IFF transponder a ten FOB?}
{126}{}{Co je ropná plošina?}
{127}{}{Ano. Nashle.}
{128}{}{IFF: rušièka -- to znamená, že tato loï nepøátelé vidí jako svou vlastní, stejnì jako další vìci Poseidonu, øeknìme ropnou plošinu, a tak na ní nebudou støílet, když se dostaneš na dostøel. Jo a FOB je druh Enklávské technologie, která ti dovoluje otevøít elektronicky zamèené dveøe. Možná, že by si ho mohl najít v jednom z jejich starých základen nebo na takových podobných místech.}
{129}{}{Jak tohle všechno víš?}
{130}{}{Co je ropná plošina?}
{131}{}{Díky. Nashle.}
{132}{}{Jo, s tìmito lidmi pøesnì víš, na èem jsi. Vìechno berou smrtelnì vážnì. Jsou jako hyeny -- ve vteøinì se na tebe sebìhnou.}
{133}{}{Co pøesnì je Enkláva?}
{134}{}{A jak si jim utekl?}
{135}{}{Enkláva je zbytek starých èasù. Jestli dostaneš tuhle vìc pøes vodu k plošinì, zjistíš to sám.}
{136}{}{Jak ho mùžu øídit?}
{137}{}{Jaká plošina?}
{138}{}{Bylo to jednoduché. Jednoho dne sem prostì opustil Navarro a zamíøil sem dolù. Vìdìl jsem, že tohle je poslední místo, kde by mì nìkdo hledal. Kromì toho, nejsem pro Enklávy dost dùležitej, aby mì hledali. Jsem pro nì prostì ztracenej.}
{139}{}{Co pøesnì je Enkláva zaè?}
{140}{}{Díky. Nashle.}
{141}{}{Je tam na vodì velká ropná plošina pro Poseidon. Je to koneèná základna Enklávy, a moc bych za to nedal, že tam jsou taky tví pøátelé.}
{142}{}{Jak to všechno víš?}
{143}{}{Jak jinak se dá dostat tam na tu plošinu?}
{144}{}{Díky. Nashle.}
{145}{}{Øíká se to.}
{146}{}{Aha. Jak jinak se dá dostat tam na tu plošinu?}
{147}{}{Aha. Nashle.}
{148}{}{Tøeba mì zbij. Byl jsem technik v Navarru, ne operátor plošiny. Mluvili jsme s nimi po drátech a to bylo jediné spojení s nimi.}
{149}{}{Aha. Øekni mi ještì jednou, jak se tahle loï ovládá?}
{150}{}{Díky. Nashle.}
{151}{}{Udìlal si chybu povídat si s kapitánem a jeho pøáteli...}
{152}{}{Jak budeš øídit tuhle bárku? Koukám, že jsi jí už naplnil palivem. Až budeš mít i ostatní vìci -- zmáèkneš knoflík. Poèítaè se postará o všechno ostatní, jestli to ovšem ještì bude fungovat. Loï popluje pøímo k ropné plošinì, a oni po tobì nebudou støílet, protože tahle loï má IFF radarovou rušièku. Ujisti se, že máš všechno co budeš potøebovat k pøístupu: FOB, funkèní navigaèní poèítaè a palivo. Jasný, jak facka, ne?}
{153}{}{Ach, joo. Mìl by si dát dohromady navigaèní poèítaè. Vsadím se, že bys na nìj našel souèástky nìjakým z tìch starých Vaultù.}
{154}{}{Zase tì rád vidím. Co potøebuješ?}
