#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš znièenì vypadajícího holohlavého mue.}
{101}{}{Vidíš Harryho, raketového specialistu.}
{102}{}{Vidíš znièenì vypadajícího holohlavého mue.}
{103}{}{Aiee! Nepøátelé osvìty! Pomoc! Stráe!}

{107}{}{Hej! Flákoto masa! Kdo jsi? Co tu dìláš?}
{108}{}{Duh?}
{109}{}{Mám dopis pro AHS-9. Kde ho mám pøedat?}
{110}{}{Jsem}
{111}{}{Nic co by tì mohlo zajímat.}
{112}{}{Chci se pøidat k hubologistùm.}
{113}{}{Kdo JSI? A co tu DÌLÁŠ?}
{114}{}{Nic. Nashle.}
{115}{}{Ohromné, idiot. Hele, podívej se, jdi támhle po schodech dolù a moná tam napraví tvoje neurodyny a udìlají pro tebe nìco uiteèného. Take do té doby sbohem, protoe na tebe nemám èas. A teï vypadni.}
{116}{}{Oh-tay!}
{117}{}{Odevzdej ho dole v pøízemí. Uka ho AHS-7, kterı má právì teï slubu u brány, ten ho od tebe vezme nebo tì pošle za AHS-9. Mùu se teï vrátit k práci?}
{118}{}{Jistì.}
{119}{}{Ty nejsi jedním z bratrù a proto nemáš povolení bıti tady. Ledae by ses chtìl k nám pøidat -- co mùeš udìlat vyslovením tvého zájmu AHS-7, kterı je právì teï ve slubì. Take teï jdi po schodech dolù nebo odtud vypadni.}
{120}{}{Fajn, fajn. Nikdo nechce bıt naštvanej.}
{121}{}{Vlastnì je to moje práce. Tohle je moje loï a tohle je moje strá - teï, kdo jste a co tu dìláte?}
{122}{}{Jsem }
{123}{}{Nic co by tì mìlo zajímat.}
{124}{}{Chci se pøidat k hubologistùm.}
{125}{}{Kdo JSI? A co tu DÌLÁŠ?}
{126}{}{Nic. Nashle.}
{127}{}{Já jsem Harry. Jsem šéf raketovıch technikù.}
{128}{}{Jsem }
{129}{}{Nic co by tì zajímalo.}
{130}{}{Chci se pøidat k hubologistùm.}
{131}{}{Nic. Nashle.}
{132}{}{Nechceš spolupracovat, eh? Stráe! Zabijte tohohle vetøelce!}
{133}{}{Tvı stráe jsou u teï mrtví.}
{134}{}{Sjeï dolù vıtahem a promluv si s AHS-7 na stanovišti. On se potom rozhodne, co s tebou.}
{135}{}{Díky. Èaudy.}

{170}{}{Potøebuju pomoci, chlapèe. Mùeš?}
{171}{}{Stále potøebuji pomoci, chlapèe. Mùeš?}
{172}{}{Kdo jsi?}
{173}{}{Co tu dìláš?}
{174}{}{Mám kopii plánù vertibirdu z Shi.}
{175}{}{Mám plány vertibirdu.}
{176}{}{V Shi mají plány vertibirdu.}
{177}{}{Co pro tebe mùu udìlat?}
{178}{}{Zapomeò na to. Nashle.}
{179}{}{Já jsem Harry, AHS-5. Jsem hvìzdnı bratr, kterı má na starosti raketu. Chystáme se jí pouít na cestu ke Quetzelu.}
{180}{}{Mùu se zeptat na nìco jiného?}
{181}{}{Mám to. Nashle.}
{182}{}{Co já dìlám, je pøíprava lodi na velkou cestu k Hvìzdnému Otci. Nyní u jsme velmi blízko.}
{183}{}{Mùu se zeptat na nìco jiného?}
{184}{}{Mám to. Nashle.}
{185}{}{Máš plány? Vıbornì! Teï u jediné, co potøebujeme, je palivo! V Shi mají dost paliva. Podívej se, jestli bys mohl nìjaké pro nás sehnat. Hodnì štìstí, rekrute!}
{186}{}{-hotovo-}
{187}{}{Pak je tedy musíš pro nás sehnat, ano? A teï mì prosím omluv, kamaráde -- musím pokraèovat v pøípravì lodi na náši velkou cestu.}
{188}{}{Mám plány vertibirdu.}
{189}{}{Jasòaèka.}
{190}{}{Máme vše, co potøebujeme pro naší cestu! Skvìle! A nyní u èekáme pouze na slovo AHS-9 - a jsem si jistı, e bude souhlasit, abys letìl s námi. Jdi si zaøídit, co potøebuješ - pak se sem vra a pøipoj se k naší cestì za Hvìzdnım Otcem!}
{191}{}{Uvidíme se pozdìji!}
{192}{}{Nejdøíve, potøebujeme plány vertibirdu k ujištìní, e máme aerodynamiku v poøádku. Jestlie to mùeš pro nás udìlat, podívej se do Shi nebo jdi do té staré základny v Navarru.}
{193}{}{Zapamatuj si, e musíš pro nás najít plány vertibirdu. Zkus Shi nebo tu starou základnu v Navarru.}
{194}{}{Nikdo nebyl schopen plány vertibirdu od Shi nebo z té staré základny v Navarru pro nás získat. Nerozmyslel sis pomoci nám?}
{195}{}{Zapamatuj si, rekrute! Nenávidìní Shi mají plány vertibirdu.}
{196}{}{Mám plány vertibirdu.}
{197}{}{Zapomeò na to.}
{198}{}{Oukej, udìlám to.}
{199}{}{Take u víš, co potøebujeme? Benzín. Hodnì benzínu. Shi mají nìjakı. Zkus to pro nás sehnat.}
{200}{}{Zapamatuj si, e máš pro nás sehnat benzín pro naší velikou vesmírnou loï.}
{201}{}{Oh, oukej. Nashle.}

{161}{}{. Jenom se dívám kolem.}
{162}{}{. Jenom se dívám kolem.}
{163}{}{. Jenom se dívám kolem.}
