#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš pankáèe s napùl vyholenou hlavou.}
{101}{}{To je Ryan, pramen veškeré moudrosti.}
{102}{}{Vidíš pankáèe, který má výraz nafoukanosti a smíchu.}
{103}{}{Pøes ty sraèky se musíš dostat, sakra.}
{104}{}{Tohle místo je hrozná prdel.}
{105}{}{Udìlám tì, že budeš krvácet. Sorry, to jsem øekl nahlas?}
{106}{}{Ay carumba! Nalgas con queso!}
{107}{}{Jee hee hee hee hee!}
{108}{}{Jdu odsud.}
{109}{}{Znal jsem Velkýho Ježíše Mordina když byl ještì malý Ježíš.}
{110}{}{Svatá Ježíšova matko Marie!}
{111}{}{Jsem výrobce. Dìlám hry. Hry jsou zábava. Zahraj si moje hry.}
{112}{}{Kup plamenomet pro žhavièe.}
{113}{}{Øíkají mi... LESKLÉ KLADIVO.}
{114}{}{Pøišel jsem do San Fran udìlat nìjaký hry a nakopat nìjaký zadky.}
{115}{}{Letní lásky...}
{116}{}{Hola, seòore! Nebo je to seòorita?}
{117}{}{Tee hee!}
{118}{}{Chlape... tohle místo je jako slib ve Stocktonu -- vítr a žádná akce.}
{119}{}{Mùj pøítel Scott si myslel, že hlavní mìsto státu Old California je Stockton. Fakt!}
{120}{}{Chci nìco fouknout pro Chipa.}
{121}{}{Kámo!}
{122}{}{Oooo, no tak!}
{123}{}{Aggro-suuuuuuuuuurge!}
{124}{}{Nechtìj abych nasadil zlej oblièej.}
{125}{}{Fakt, opravdu?}
{126}{}{Pøesnì, pane. Heh heh heh.}
