#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš stráného v lehkém obleku, kterı se trochu nudí.}
{101}{}{Vidíš palácového stráného}
{102}{}{Vidíš palácového stráného drícího nebezpeènì vypadající zbraò.}
{103}{}{Prostì pokraèuj v chùzi a nic se ti nestane.}
{104}{}{Máš tu nìco na práci?}
{105}{}{Sledujeme tì.}
{106}{}{Nepokoušej se o nic smìšného.}
{107}{}{Chovej se k našim lidem s úctou.}
{108}{}{Nesahej na to. To je poslední varování.}
{109}{}{A u tì tady nevidím.}
{110}{}{Ustup, ty nulo.}
{111}{}{Ustup pomalu od toho.}
{112}{}{A tì to ani nenapadne.}
{113}{}{Pøestaò s tím. Hned.}
{114}{}{Chcípni, nepøíteli lidu!}
{115}{}{Posílám tì do pekla hoøícího kovu!}
{116}{}{Mùe mít Buddha slitování s tvou duší?}
{117}{}{Trp, nepøíteli!}
