#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš dítì.}
{101}{}{Dìcko.}
{102}{}{Toto dítì vypadá skoro jako ostatní dìti.}
{103}{}{Vypadáš špatnì.}
{104}{}{Neubližuj mi, oukej?}
{105}{}{Co se ti stalo s oèima?}
{106}{}{Je to lao wai?}
{107}{}{Co jsi zaè?}
{108}{}{Má tì nìkdo rád?}
{109}{}{Nechystáš se ublížit mojí mamince a tatínkovi, že jo?}
{110}{}{A teï si jdu hrát.}
{111}{}{He, he! Ètyøi oèi!}
{112}{}{Poplach! Poplach!}
{113}{}{::oèi dítìte se rozšíøily když Marcus slavnostnì pøipochodoval::}
{114}{}{To je velký zelený pán.}
{115}{}{Proè ten muž nosí sukni?}
{116}{}{Chce se ten muž stát dívkou?}
{117}{}{Eeek! Barbar!}
{118}{}{Hej, pane! Vy máte kùstku v nose!}
{119}{}{Eeeek! Zombie!}
{120}{}{Mami, je ten muž nakažlivý?}
{121}{}{Cute doggy! Dobrý chlapec!}
{122}{}{Eeeee! Pøíšera!}
{123}{}{Koukejte, nemotora!}
{124}{}{To je tvoje máma?}
{125}{}{Pomoc! Jde po mì robot!}
{126}{}{Pomoc! Jde po mì robot!}
{127}{}{Zaèíná tu být horko? Haló? Mùžeš mì poslouchat?}
{128}{}{Co jsi zaè? Jsi èlovìk?}
{129}{}{Jsi strašnì velkej.}
{130}{}{Tyyyyy jo!}
{131}{}{Neubližuj mi!}
{132}{}{::pláè::}
{133}{}{Pomoc, maaamiiii!}

