#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš obèana z Shi v bílém obleku.}
{101}{}{Vidíš laboratorního specialistu z Shi.}
{102}{}{Vidíš obyvatele z Shi v bílém obleku ve vìdecké laboratoøi.}

{103}{}{Chlape... Wong je jistì otrockı øidiè.}
{104}{}{Práce, práce a zase práce. Pro tu jsme byli stvoøeni.}
{105}{}{Zmìníme tuto pustinu tímto experimentem!}
{106}{}{Podívej, pustina! Nìco pro tebe mám!}
{107}{}{Chci znovu uvidìt slunce.}
{108}{}{Namixuju toto. Namixuju tamto. Nìkdy jsem tak otrávenı.}
{109}{}{Vidìl jsi nejnovìjší vısledky našeho velkého experimentu! Velmi potìšující!}
{110}{}{Omluv mì.}

{116}{}{A se ti špehové pokusí nalogovat znovu!}
{117}{}{Hackeøi u TO nikdy znovu nezkusí.}
{118}{}{Jestlie je nemùeme porazit vìdou, porazíme je s pomocí našich bojovníkù.}
{119}{}{Lo Pan a Dragon spoleènì. To je hrozná myšlenka.}
{120}{}{Ten hacker tu nebyl dlouho.}
{121}{}{Práce, práce a zase práce. Pro tu jsme byli stvoøeni.}
{122}{}{Zmìníme tuto pustinu!}
{123}{}{Podívej, pustina!}
{124}{}{Chci znovu vidìt slunce.}

{127}{}{Sheng Ming je hroznej slimák.}
{128}{}{V tìchto dnech bychom mìli bıt hotovy.}
{129}{}{Za vítìzství Císaøe. Jasnì.}
{130}{}{Slyšel jsi? Nìkdo se nám naboural do poèítaèù!}
{131}{}{Vsadil bych se, e to byl nìkdo z hubologistù, kdo to udìlal.}
{132}{}{Mìli bychom hubologistùm poslat virus.}
{133}{}{Chci pomstu za to hacknutí!}
{134}{}{Jednoho dne zjistíme, kdo se nám dostal do poèítaèe.}
{135}{}{Práce, práce, práce. Pro tu jsme byli stvoøeni.}

{144}{}{Dìláme tu dobrou práci! Take nám ji neka!}
{145}{}{Pokoušíme se zachránit pustinu, ty idiote!}
{146}{}{Ne! Ne naši vìdci!}
{147}{}{Pomoc! Stráe!}
{148}{}{Prosím! Tomu nerozumíš!}
{149}{}{Ne! Naše experimenty!}
