#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš ženu s ustrašeným výrazem ve tváøi.}
{101}{}{Vidíš Suze.}
{102}{}{Vidíš ženu s ustrašeným výrazem ve tváøi.}
{103}{}{Jeee! Pomoz mi!}
{104}{}{Zachraò mì! Prosím!}
{105}{}{Oni mì chtìjí zabít!}
{106}{}{Prosím! Oni mì chtìjí zabít!}
{107}{}{Zastav je! Jeee!}
{108}{}{Badger tì posílá? Vím, že urèitì ano. To se mi ale ulevilo.}
{109}{}{Aagggh.}
{110}{}{Co jsi dìlala tam dole?}
{111}{}{Jo. Pojï za mnou.}
{112}{}{Oh, ty malá chudinko. Radiace a ta pustina nejsou vùbec pøíjemné, že? Doufám, že ti nìkdo bude schopen pomoci.}
{113}{}{Já vím, je to opravdu hloupé. Právì sem to tu prozkoumávala, protože Badger byl u poèítaèe, takže jsem šla dolù po schodech a ztratila jsem se. A další vìc, jak už sem ti øíkala bylo to, že jsem byla obklopená tìmi pøíšerami. Ještì, že jsi pøišel.}
{114}{}{Mám více otázek.}
{115}{}{No to teda jo. Našla jsi nìco zajímavého?}
{116}{}{No, to teda jo. Pojï.}
{117}{}{Našla jsem místnost, ve které jsem byla. Našla jsem taky místnost, která vypadá jako palivová místnost. Dál jsem se nedostala kvùli tìm pøíšerám.}
{118}{}{Mám více otázek.}
{119}{}{Odkud jsi?}
{120}{}{Dobøe. To je pro tuto chvíli zatím vše.}
{121}{}{Jsem z místa, které je jižnì od Boneyardu a jižnì od Glow. Není to daleko od moøe. Bývala jsem chùva, ale pak zaèali dìti mutovat v monstra.}
{122}{}{Mám více otázek.}
{123}{}{Jak jsi potkala Badgera?}
{124}{}{Fascinující. To je pro tuhle chvíli vše.}
{125}{}{Pøišel k nám na jih a pøišel do klubu, kam sem chodívala. A když jsem se cítila osamìlá, tak sem si øekla, to je to místo, kam bych mìla jít.}
{126}{}{Mám více otázek.}
{127}{}{To je všechno. Díky.}
{128}{}{Zachránil jsi mi život. Odpovím Ti na jakoukoliv otázku, kterou mi položíš.}
{129}{}{Joooo.}
{130}{}{Co si dìlala tam dole?}
{131}{}{Našla jsi nìco zajímavého?}
{132}{}{Odkud jsi?}
{133}{}{Jak jsi potkala Badgera?}
{134}{}{Teï už nic. Nashle.}
{135}{}{Ó mùj bože... Badger je mrtvý ... Já nevím co teï budu dìlat... Teï už tu nemám žádné pøátele... celá moje rodina je mrtvá... ó mùj Bože...}
{136}{}{Mockrát ti dìkuju za tvojí pomoc. Jdu najít Badgera.}
