#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš obchodníka.}
{101}{}{Vidíš Jenna, obchodníka.}
{102}{}{Vidíš hezkou majitelku obchodu.}
{103}{}{Ahoj! Jsem Jenna. Mohu vám pomoci?}
{104}{}{Chci informaci.}
{105}{}{Co máte?}
{106}{}{Ne, jdu.}
{107}{}{Chci nìjakou informaci.}
{108}{}{Jistì, ukaž mi, co máš.}
{109}{}{Právì teï ne.}
{110}{}{Nauèil jsem se, že èím ménì víš, tím déle žiješ. Nemám pro tebe žádnou další informaci. Chtìl bys vidìt mé zboží?}
{111}{}{Ano.}
{112}{}{Ne.}
{113}{}{Skvìle. Podívej se.}
{114}{}{}
{115}{}{Ok.}
{116}{}{Nìco jiného?}
{117}{}{Ano.}
{118}{}{Ne.}
{119}{}{Dobøe, mìj se fajn.}
{120}{}{}
{121}{}{Ok.}
{122}{}{Zdravím, zase ty ? Je nìco, s èím ti mohu pomoci?}
{123}{}{Ano.}
{124}{}{Ne.}
{125}{}{Promiò, ale mám zavøeno. Otevøu v osm; prosím pøijï pozdìji.}
{126}{}{}
{127}{}{Oukej.}
{128}{}{Kvùli tobì nebudu otvírat. Vypadni z mýho obchodu!}
{129}{}{}
{130}{}{Oukej.}
{131}{}{Doufám, že zboží pøijde brzo.}
