#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš obchodníka.}
{101}{}{Vidíš Slima, obchodníka.}
{102}{}{Vidíš obchodníka. Má na sobì zástìru a drží v ruce sklenici, kterou vytírá do sucha špinavým ruèníkem. Vypadá, jako kdyby si od nikoho nenechal nic líbit.}
{103}{}{Jsem Slim. Co bys rád?}
{104}{}{Chci informaci.}
{105}{}{Co máš?}
{106}{}{Ne, už jdu.}
{107}{}{Chci nìjaké informace.}
{108}{}{Jistì, ukaž mi co máš.}
{109}{}{Nic, jdu pryè.}
{110}{}{Informaci? Nemám tu žádnou knihovnu ani poèítaè. Buï chceš nìco k pití nebo vypadni. Chceš nìjakej chlast nebo ne?}
{111}{}{Ano.}
{112}{}{Ne.}
{113}{}{Fajn. Jestli tì tohle svinstvo nezabije, tak už potom fakt nic.}
{114}{}{}
{115}{}{Ok.}
{116}{}{To je pro tebe?}
{117}{}{Ano.}
{118}{}{Ne.}
{119}{}{Pak tedy pozdìji.}
{120}{}{}
{121}{}{Oukej.}
{122}{}{Vítej zpátky. Potøebuješ více chlastu?}
{123}{}{Ano.}
{124}{}{Ne.}
{125}{}{Mám zavøeno. Jdi pryè.}
{126}{}{}
{127}{}{Oukej.}
{128}{}{Nebudu kvùli tobì otvírat. Vypadni z mýho obchodu!}
{129}{}{}
{130}{}{Oukej.}
