#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš obchodníka.}
{101}{}{Vidíš Cala, obchodníka se zbranìmi.}
{102}{}{Vidíš unudìného, ale pøátelsky vypadajícího muže.}
{103}{}{Dobrý den, pane. Jak vám mohu pomoci?}
{104}{}{Dobrý den, paní. Jak vám mohu pomoci?}
{105}{}{Chci informaci.}
{106}{}{Co máš zajímavého?}
{107}{}{No, už jdu.}
{108}{}{Chci nìjaké informace.}
{109}{}{Jistì, ukaž mi, co máš zajímavého.}
{110}{}{Tak nic.}
{111}{}{Nemám informace na prodej. Obchoduji pouze se zbranìmi. Chceš vidìt moje zboží?}
{112}{}{Ano.}
{113}{}{Ne.}
{114}{}{Myslím si, že budeš potìšen mým výbìrem. Máš dost èasu si všechny vìci prohlédnout.}
{115}{}{Oukej.}
{116}{}{Chceš ještì nìco jiného?}
{117}{}{Ano.}
{118}{}{Ne.}
{119}{}{Pak ti tedy pøeji pìkný den.}
{120}{}{Oukej.}
{121}{}{Zase zpátky. Chceš nìco dalšího koupit?}
{122}{}{Ano.}
{123}{}{Ne.}
{124}{}{Je mi líto, ale mám zavøeno. Otevøu okolo 8 hodiny. Jestli nìco budeš potøebovat, tak pøijï pozdìji.}
{125}{}{Oukej.}
{126}{}{Nic Ti neprodám. Vypadni z mého obchodu!}
{127}{}{Oukej.}
{128}{}{Doufám, že zboží pøijde brzo.}
