#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš poèítaèový terminál.}
{101}{}{Tohle je biologická pracovní stanice.}
{102}{}{Vidíš funkèní poèítaèový terminál.}
{103}{}{Zdravím. Prosím potvrïte vaši identitu.}
{104}{}{(Jééé! Bliká tu spousta svìtýlek!)}
{105}{}{::vložit heslo::}
{106}{}{INTLVR-Dnky-Pnch-98790}
{107}{}{::dostat se do poèítaèe::}
{108}{}{Odhlásit se}
{109}{}{Vyhledat data: -Botanický program- -Genetický program- -Xeno program-}
{110}{}{Botanický program.}
{111}{}{Genetický program.}
{112}{}{Xeno program.}
{113}{}{Poznámka pro osazenstvo.}
{114}{}{Vypnout stanici.}
{115}{}{Nesprávné heslo. Prosím promluvte si se systémovým administrátorem. Nashledanou.}
{116}{}{::dostat se do poèítaèe::}
{117}{}{::odejít::}
{118}{}{Vetøelec! Aktivován poplach. Systém se vypíná. Pøeji hezký den.}
{119}{}{-hotovo-}
{120}{}{(po dvaceti minutách jsi objevil toto: Poèáteèní výsledky rušení radiace pomocí rostlin se ukázaly jako málo slibné. Dr. Sheng vyvinul rostlinný život odolný proti radiaci -- následují nepøíjemné vedlejší úèinky. Výsledný rostlinný život je považován za pøíliš nebezpeèný. Sheng trvá na dalším zkoumání v kombinaci s genetickým programem.)}
{121}{}{Genetický program.}
{122}{}{Xeno program.}
{123}{}{Nové poznámky.}
{124}{}{Back.}
{125}{}{(po dvaceti minutách jsi poskládal dohromady tuto informaci: Po použití báze FEV viru, se Dr. Long Wang pøesvìdèil o úspìchu pøi vytváøení mutantních vojákù. Vytvoøil sérum, které pøi pokusech s hlodavci poskytuje zajímavé výsledky. Pøi aplikaci séra na sobì se zmìnil na rozplizlou mazlavou hmotu. Dr. Sheng ukonèil tuto oblast výzkumu. V dùsledku smrti Dr. Longa, je Dr. Sheng vedoucí. Sheng požaduje soustøedit prostøedky na výzkum rostlinného života pohlcujícího radiaci.)}
{126}{}{Botanický program.}
{127}{}{Xeno program.}
{128}{}{Nové poznámky.}
{129}{}{Zpìt.}
{130}{}{"Subjekt na kterém jsme chtìli provést sérii významných pokusù zmizel. Pøedpokládá se, že je buï znièen, nebo zcizen hubologisty. Další výzkumy se ukázaly jako marné. Dokud neobdržíme další exempláøe, tato databáze zùstane mimo provoz." - Dr. Sheng}
{131}{}{Botanický program.}
{132}{}{Genetický program.}
{133}{}{Nové poznámky.}
{134}{}{Zpìt.}
{135}{}{Dr. Wong: Nový vedoucí Biologického Projektu, mimo to i Fyzikálního Výzkumu.
Dr. Sheng: Vedoucí Biologického Projektu do doby pøed dvìma mìsíci. Jeden mìsíc volna kvùli odpovìdnosti za "rostlinné sérum podporující vnímavost" ; další nìpøítomnost je záhadou. Dr. Wong pøevzal øízení Biologického Programu.
Dr. Long: Nedávno skonal kvùli FEV séru.}
{136}{}{Botanický program.}
{137}{}{Genetický program.}
{138}{}{Xeno program.}
{139}{}{Zpìt.}
{140}{}{Stanice deaktivována.}
{141}{}{Aktivovat stanici.}
{142}{}{-odejít-}
{143}{}{(Tvùj nešikovný pøístup pøes klávesy aktivoval správné heslo... tvoje štìstí je neuvìøitelné!)}
{144}{}{-více-}


{145}{}{Poèítaè neodpovídá na žádné vstupy.}
{146}{}{Nemùžeš najít nic, kam to vložit.}
