#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš poèítaèovı terminál.}
{101}{}{Vidíš chemickou pracovní stanici.}
{102}{}{Vidíš poèítaèovou pracovní stanici.}
{103}{}{Zdravím. Prosím napiš svoje heslo pro ovìøení tvojí totonosti.}
{104}{}{? Nerozumím velkım slovùm.}
{105}{}{TIUASPO-Lo-Shi-S12908}
{106}{}{::dostat se do poèítaèe::}
{107}{}{Odlogovat se.}
{108}{}{Chemická databáze: -Paliva a deriváty- -Polymery-}
{109}{}{Paliva a deriváty.}
{110}{}{Polymery.}
{111}{}{Deaktivovat pracovní stanici.}
{112}{}{Odlogovat se.}
{113}{}{Prosím zkontaktujte správce systému. Nashledanou.}
{114}{}{::dostat se do poèítaèe::}
{115}{}{::odejít::}
{116}{}{Zaznamenán nepovolenı pøístup. Automatické vypnutí. Pøeji hezkı den.}
{117}{}{-hotovo-}
{118}{}{(Po prosetí tun chemickıch vzorcù a laboratorních poznámek, jsi došel k pøesvìdèení, e Shiové vytvoøili novı druh paliva z extraktù rostlin a moøskych ivoèichù. Podle všeho transportují toto palivo pomocí ji existujících potrubí, take mohou palivo smìrovat na rùzná místa)}
{119}{}{(Prošel jsi obrovské mnoství chemickıch vzorcù a laboratorních poznámek. Nejsi si vùbec jistı, co toto všechno znamená.)}
{120}{}{Nasmìrovat palivo k tankeru Poseidon.}
{121}{}{Nasmìrovat palivo k hubologistùm.}
{122}{}{Zpìt.}
{123}{}{(Kdy jsi ještì jednou prošel zmì symbolik a technickıch poznámek, objevil jsi, e Shiové pracují na novém typu polymerického bojovém obleku, kterı by mìl bıt odolnı vùèi ohni a prùbojnosti. Bude to ještì trvat nìjakı ten rok, ne se tento projekt dokonèí. Vidíš také zmínku o novıch zbraních a také novıch stavitelskıch monostech. Podle všeho mají Shiové nìjaké plány do budoucna.)}
{124}{}{Zpìt.}
{125}{}{Palivo pøesmìrováno. Zásobní nádre = prázdné. Program se zavírá.}
{126}{}{-hotovo-}
{127}{}{Palivo pøesmìrováno. Zásobní nádre = prázdné. Program se zavírá.}
{128}{}{-hotovo-}
{129}{}{Stanice deaktivována.}
{130}{}{Aktivovat stanici.}
{131}{}{-odejít-}
{132}{}{(Divíš se, e se ti to podaøilo... jsi v poèítaèi!)}
{133}{}{-více-}

{134}{}{Poèítaè nereaguje na nic.}
{135}{}{Nevypadá to, e bys našel zpùsob, jak to udìlat.}

{136}{}{::odhadnout heslo::}
{137}{}{Nasmìrovat palivo potrubím.}
{138}{}{Cíl musí bıt zadán.}
