#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš poèítaèovı terminál.}
{101}{}{Vidíš poèítaè hubologistù.}
{102}{}{Vidíš poèítaè. Aèkoliv je primitivní, vypadá, e je v provozu.}
{103}{}{Tato jednotka nepøijímá pøíkazy. Nashledanou.}
{104}{}{(A se snaíš jakkoliv, nemùeš prolomit šifru k ovládání tohoto poèítaèe.)}
{105}{}{Odlogovat se.}
{106}{}{Vítej v HubLinku.}
{107}{}{Prosím zadej pøíkazy.}
{108}{}{Vstoupit do databáze.}
{109}{}{Vstoupit do øízení.}
{110}{}{Odlogovat se.}
{111}{}{Vyber databázi.}
{112}{}{Vızkum.}
{113}{}{Cíle do budoucnosti.}
{114}{}{Finance.}
{115}{}{Zpìt.}
{116}{}{(Po projití náboenskıch nesmyslù to vypadá, e Hubologisté vytvoøili prostøedky k vytvrzení a zlepšení energo brnìní. Také pøišli na zpùsob, jak spoèítat trajektorii odpalu na obìnou dráhu. Dále to vypadá, e pracují na ovládání poèasí.)}
{117}{}{Zpìt.}
{118}{}{Odlogovat se}
{119}{}{(Strávil jsi asi pùl hodiny ètením, jakıch cílù se AHS-9 snaí dosáhnout. Kromì osvícení a spojení s Hvìzdnım Otcem to vypadá, e nemá ádné vıèitky svìdomí ohlednì zabíjení lidí, kteøí s ním v nìèem nesouhlasí. Je trochu šílenı.)}
{120}{}{Zpìt.}
{121}{}{Odlogovat se.}
{122}{}{(Vypadá to, e církev Hubologistù je velmi zámoná. Standardní postup je poádat nováèka, aby daroval všechen svùj svìtskı majetek církvi, jako dùkaz své víry. Kdy o toto není nìkdo poádán, oèividnì to vypadá, e Hubologisté nezamıšlejí jednat s ním na rovinu. Obrovské mnoství koøisti mají ukryto nìkde v poušti. Bohuel nemùeš pøesnì zjistit souøadnice.)}
{123}{}{Zpìt.}
{124}{}{Odlogovat se.}
{125}{}{Øízení zpøístupnìno. Vyberte operaci.}
{126}{}{Formátovat pevnı disk.}
{127}{}{Pøekontrolovat status systémù.}
{128}{}{Zpìt.}
{129}{}{Odlogovat se.}
{130}{}{Zakázaná operace. Poraïte se se správcem systému. Odhlašuji se. Nashledanou.}
{131}{}{-hotovo-}
{132}{}{Vypadá to, e pro tohle tam není rozhraní.}

{133}{}{ESS Quetzel natankována a pøipravena ke startu.}
{134}{}{ESS Quetzel je bez paliva.}
{135}{}{Sálovı poèítaè funguje. Vedení funguje. Vızkumné stanice fungují. Opravárenské centrum funguje. Kamery fungují.}
{136}{}{Zpìt.}
{137}{}{Odlogovat se.}
