#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
#{100}{}{Vidíš mocnı poèítaè.} //This is for the computer object itself
#{101}{}{Vidíš císaøskı poèítaè.}
#{102}{}{Vidíš velkı, bzuèící, plnì funkèní poèítaè, kterı má na spodní èásti oznaèení "Císaø v8.8".}
{100}{}{Vidíš poèítaèovı terminál.}
{101}{}{Vidíš císaøskı poèítaèovı terminál.}
{102}{}{Vidíš poèítaè se zabudovanou dotykovou obrazovkou. Na stranì má vyryto "Císaø v8.8 Poèítaèovı Terminál".}
{103}{}{Zdravím. Prosím vlote své heslo pro potvrzení vaší identity.}
{104}{}{::vloit heslo::}
{105}{}{CSPDMSHR-Shih-huang-ti-X9372}
{106}{}{KSLJKJ:Ken-Lee-97313}
{107}{}{TIUASPO-Lo-Shi-S12908}
{108}{}{::dostat se do poèítaèe::}
{109}{}{Odlogovat se.}
{110}{}{Identita potvrzena.}
{111}{}{Ke které funkci si pøejete pøistoupit?}
{112}{}{Diagnostické funkce.}
{113}{}{Databáze.}
{114}{}{Pøedpovìdi.}
{115}{}{ádné.}
{116}{}{Prosím, promluvte si se systémovım administrátorem. Nashledanou.}
{117}{}{::dostat se do poèítaèe::}
{118}{}{::odejít::}
{119}{}{Vetøelec! Aktivován poplach. Poèítaè se vypíná. Pøeji hezkı den.}
{120}{}{-hotovo-}
{121}{}{Diagnostické funkce?}
{122}{}{Procházet sí.}
{123}{}{Formátovat disk.}
{124}{}{Zkontrolovat integritu pevného disku.}
{125}{}{Zpìt.}
{126}{}{Kterou databázi se pøejete provìøit?}
{127}{}{Biologie.}
{128}{}{Chemie.}
{129}{}{Fyzika.}
{130}{}{Historie.}
{131}{}{Zpìt.}
{132}{}{Dìti mìsta Shi jsou v nebezpeèí. 50% šance, e se mezi nimi pohybuje vrah.}
{133}{}{Ve mìstì Shi se objevilo nebezpeèí. 75% pravdìpodobnost, e nìkdo pøijde k úrazu.}
{134}{}{Hubologistickı start do vesmíru z 95% zkrachuje. Faktory: bez paliva, nevhodné tìsnìní, špatné vedení, nedostatek iniciativy.}
{135}{}{15% šance, e urèenı "Vyvolenı" uspìje ve svém úkolu.}
{136}{}{Vstupy ukazují, e "Enkláva" je mnohem mocnìjší, ne se pùvodnì pøedpokládalo; nepøibliovat se.}
{137}{}{Šance, e se v této høe znovu objeví ponorka: 0%}
{138}{}{Tankeroví tuláci mají šanci 0% e vyèistí zamoøení cizími bytostmi bez vnìjší pomoci. Zpracovávám vhodnost poskytnutí pomoci.}
{139}{}{Vstup: Naftovı tanker Poseidon nevhodnı pro cestu. Vyaduji více vstupù.}
{140}{}{Bez procesù. Vyaduji vstup.}
{141}{}{-více-}
{142}{}{Zpìt.}
{143}{}{Biologická stanice: Aktivní}
{144}{}{Biologická stanice: Neaktivní}
{145}{}{Chemická stanice: Aktivní}
{146}{}{Chemická stanice: Neaktivní}
{147}{}{Fyzikální stanice: Aktivní}
{148}{}{Fyzikální stanice: Neaktivní}
{149}{}{Deaktivovat Biologickou Stanici.}
{150}{}{Deaktivovat Chemickou Stanici.}
{151}{}{Deaktivovat Fyzikální Stanici.}
{152}{}{Pøistoupit k Biologické Stanici.}
{153}{}{Pøistoupit k Chemické Stanici.}
{154}{}{Pøistoupit k Fyzikální Stanici.}
{155}{}{Aktivovat Biologickou Stanici.}
{156}{}{Aktivovat Chemickou Stanici.}
{157}{}{Aktivovat Fyzikální Stanici.}
{158}{}{Zpìt.}
{159}{}{Formátování disku: Všechna data budou znièena. Jste si jist?}
{160}{}{Ano.}
{161}{}{Ne.}
{162}{}{Funkèní integrita tohoto systému je 92%. Zaštítìné jádro císaøského poèítaèe je 100%. Integrita dat je 100%. Pøedpovìdní uzel trpí menším zpoïováním energie - navrhovanı èas oprav 6 dní. Pøedpovìdi z 15% aplikovatelné.}
{163}{}{Zpìt.}
{164}{}{Opravdu si pøejete zformátovat tuto jednotku? Toto je nevratnı proces.}
{165}{}{Ano.}
{166}{}{Ne.}
{167}{}{Formátuji... formátuji... formátování skonèilo. Opìtovné nastartování vyaduje plnou instalaci. Poèítaè se vypíná. Vypnutí... poèítaèe... dokonèeno...}
{168}{}{-hotovo-}
{169}{}{Vyhledat data: - Botanickı program  - Genetickı program - Xeno program}
{170}{}{Botanickı program.}
{171}{}{Genetickı program.}
{172}{}{Xeno program.}
{173}{}{Zpìt.}
{174}{}{(po dvaceti minutách jsi objevil toto: Poèáteèní vısledky rušení radiace pomocí rostlin se ukázaly jako málo slibné. Dr. Sheng vyvinul rostlinnı ivot odolnı proti radiaci - následují nepøíjemné vedlejší úèinky. Vıslednı rostlinnı ivot je povaován za pøíliš nebezpeènı. Sheng trvá na dalším zkoumání v kombinaci s genetickım programem.)}
{175}{}{Genetickı program.}
{176}{}{Xeno program.}
{177}{}{Zpìt.}
{178}{}{(po dvaceti minutách jsi poskládal dohromady tuto informaci: Pouitím báze FEV viru, se Dr. Long Wang pøesvìdèil o úspìchu pøi vytváøení mutantních vojákù. Vytvoøil sérum, které pøi pokusech s hlodavci poskytuje zajímavé vısledky. Pøi aplikaci séra na sobì se zmìnil na rozplizlou mazlavou hmotu. Dr. Sheng ukonèil tuto oblast vızkumu. V dùsledku smrti Dr. Longa, je Dr. Sheng vedoucí. Sheng poaduje soustøedit prostøedky na vızkum rostlinného ivota pohlcujícího radiaci.)}
{179}{}{Botanickı program.}
{180}{}{Xeno program.}
{181}{}{Zpìt.}
{182}{}{"Subjekt, na kterém jsme chtìli provést sérii vıznamnıch pokusù, zmizel. Pøedpokládá se, e je buï znièen, nebo zcizen hubologisty. Další vızkumy se ukázaly jako marné. Dokud neobdríme další exempláøe, tato databáze zùstane mimo provoz." - Dr. Sheng}
{183}{}{Botanickı program.}
{184}{}{Genetickı program.}
{185}{}{Zpìt.}
{186}{}{Chemické Databáze: Palivo a deriváty - Polymery}
{187}{}{palivo a deriváty.}
{188}{}{Polymery}
{189}{}{Zpìt.}
{190}{}{(Po prostudování sloitıch chemickıch vzorcù a laboratorních zápiskù jsi nabyl dojmu, e Shi vytvoøili novı druh paliva z rostlinnıch a moøskıch extraktù. Oèividnì se napojili na døíve existující potrubí, take mohou palivo dopravovat do velkého mnoství lokací.)}
{191}{}{(Narazil jsi na veliké mnoství sloitıch chemickıch vzorcù a laboratorních zápiskù. Nejsi si úplnì jistı, co má všechno tohle znamenat.)}
{192}{}{Pøesmìrovat palivo do tankeru Poseidon.}
{193}{}{Pøesmìrovat palivo k hubologistùm.}
{194}{}{Zpìt.}
{195}{}{(Po projití podkladù a technickıch diskusí jsi objevil, e Shi pracují na novém polymerickém brnìní, které je odolné jak proti plamenometnım tak i prùbojnım útokùm. Dokonèení je však stále v daleké budoucnosti. Také vidíš zmínku o novıch zbraních a konstrukèních monostech. Oèividnì Shi mají nìjaké plány do budoucnosti.)}
{196}{}{Zpìt.}
{197}{}{Palivo pøesmìrováno podle poadavku. Skladovací cisterny = Prázdné. Uzavírám program.}
{198}{}{-hotovo-}
{199}{}{Palivo pøesmìrováno podle poadavku. Skladovací cisterny = Prázdné. Uzavírám program.}
{200}{}{-hotovo-}
{201}{}{Fyzikální databáze: Vızkum - Teorie}
{202}{}{Vızkum}
{203}{}{Teorie}
{204}{}{Zpìt}
{205}{}{"Díky nedávnému získání plánù na vertibird , monost sestrojení praktického létajícího stroje zaznamenala velikı skok kupøedu. Oèekáváme, e koncem roku budeme mít funkèní prototyp a do dvou let budeme moci zahájit hromadnou vırobu." -Dr. Wong}
{206}{}{::zkopírovat plány:: Zpìt.}
{207}{}{Zpìt.}
{208}{}{"Stále pøipravujeme pracovní model vzdušného vozidla. ádnı z našich návrhù se neosvìdèil jako bezpeènı a ideálnì aerodynamickı. Moná kdybychom mìli pøístup ke starodávnım plánùm..." -Dr. Wong}
{209}{}{Zpìt.}
{210}{}{(Po proètení úvodu a matematiky jsi objevil, e se Shiové znovu snaí vyvíjet nukleární energii, a znovu budují teorie dávnıch vesmírnıch letù - a zatímco tak èiní, vysmívají se hubologistùm - a vyuívají energii slunce, vìtru a moøe.  Alespoò toto vyplıvá z poznámek.)}
{211}{}{Zpìt.}
{212}{}{Stanice aktivována.}
{213}{}{Zpìt.}
{214}{}{Poèítaèovı terminál pro tohle nemá rozhraní.}
{215}{}{Poèítaèovı terminál vypadá, e není v provozu.}

{216}{}{V systému byla ochrana. Pøíkazy jsou zaútoèit!}
{217}{}{Zaútoète na vetøelce!}
{218}{}{Je èas zaplatit za své èiny, lao wai!}
{219}{}{Mezi námi je zrádce!}

{220}{}{Zemìpisná lokace.}
{221}{}{Co si pøejete lokalizovat?}
{222}{}{Vesnièany z mého domova.}
{223}{}{97% souhrnná šance - vesnièané lokalizováni na souøadnicích komplexu Enklávy.}
