#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vítej. Já jsem ACE, lékaøskı poèítaè. Potøebujete lékaøskou asistenci?}
{101}{}{Ano.}
{102}{}{Ne.}
{103}{}{Mít otázku. Mít ty odpovìï?}
{104}{}{Mám nìjaké otázky. Mùeš mi na nì odpovìdìt?}
{105}{}{Prosím, udejte své lékaøské potøeby.}
{106}{}{Bıt zranìnı.}
{107}{}{Bıt otrávenı.}
{108}{}{Chodit v temnotách.}
{109}{}{Bıt mrzák.}
{110}{}{Vyvolenı chtít bıt silnìjší.}
{111}{}{Vyvolenı chtít chytøejší.}
{112}{}{Chtít upozornit na další vìci.}
{113}{}{Vyvolenı chtít bıt krásnìjší.}
{114}{}{Nepotøebovat nic.}
{115}{}{Jsem zranìnı.}
{116}{}{Jsem otrávenı. Potøebuju protilék.}
{117}{}{Chytil jsem docela slušnou dávku radiace.}
{118}{}{Jsem zmrzaèen.}
{119}{}{Chci bıt silnìjší.}
{120}{}{Chci bıt chytøejší.}
{121}{}{Chci bıt vnímavìjší.}
{122}{}{Chci mít vìtší charisma.}
{123}{}{Momentálnì nepotøebuji vùbec nic.}
{124}{}{Otvírám regenerátor, èekejte prosím... nyní ulehnìte dovnitø tanku a uvolnìte se. Léèebnı proces potrvá 5 minut.}
{125}{}{Oukej.}
{126}{}{Moná pozdìji.}
{127}{}{V poøádku.}
{128}{}{Zapomeò na to.}
{129}{}{Otvírám regenerátor, èekejte prosím... nyní ulehnìte dovnitø tanku a uvolnìte se. Nejprve bude analyzován jed a pak následnì syntetizován protijed. Porušená tkáò bude opravena. Tento proces potrvá 30 minut.}
{130}{}{Oukej.}
{131}{}{Ne.}
{132}{}{Jistì.}
{133}{}{Moná pozdìji.}
{134}{}{Otvírám regenerátor, èekejte prosím... nyní ulehnìte dovnitø tanku a uvolnìte se. Budou aplikovány antiradiaèní komponenty a poškozená tkáò bude opravena. Tento proces bude si vyádá 60 minut.}
{135}{}{Oukej.}
{136}{}{Ne.}
{137}{}{Fajn.}
{138}{}{Rozmyslel sem si to.}
{139}{}{Otvírám regenerátor, èekejte prosím... nyní ulehnìte dovnitø tanku a uvolnìte se. Restrukturalizace poškozenıch konèetin si vyádá 24 hodin.}
{140}{}{Oukej.}
{141}{}{Ne.}
{142}{}{Tak to udìlej.}
{143}{}{Moná pozdìji.}
{144}{}{Tato funkce není v danı okamik k dispozici. V této oblasti jsou moje vìdomosti nekompletní. Potøebuji pamìovı modul obsahující dané lékaøské procedury. Máte takovı modul?}
{145}{}{Mít ten modul. Tady je.}
{146}{}{Ne. Najdu ho a pak se vrátím.}
{147}{}{Ano, mám ho pøímo tady. Pøeèti si ho.}
{148}{}{Ne, nemám ten modul. Pùjdu ho najít.}
{149}{}{Komplexní procedura vyaduje 2 tıdny v regenerátoru tanku. Souhlasíte s tím?}
{150}{}{Ano, souhlasím.}
{151}{}{Ne, je to na moc dlouho.}
{152}{}{Ano, souhlasím.}
{153}{}{Zapomeò na to. Teï nemám tolik èasu.}
{154}{}{Otvírám regenerátor, èekejte prosím... nyní ulehnìte dovnitø tanku a uvolnìte se.}
{155}{}{Oukej.}
{156}{}{Tato funkce není v danı okamik k dispozici. V této oblasti jsou moje vìdomosti nekompletní. Potøebuji pamìovı modul popisující tyto dané lékaøské procedury. Máte takovı modul?}
{157}{}{Mít takovı modul. Tady je.}
{158}{}{Ne. musím ho najít a pak se sem vrátím.}
{159}{}{Ano, mám ho pøímo tady. Pøeèti si ho.}
{160}{}{Ne, nemám ten modul. Pùjdu ho najít.}
{161}{}{Komplexní procedura trvá 4 tıdny v regenerátoru. Souhlasíte s tím?}
{162}{}{Jo, souhlasím.}
{163}{}{Ne, je to moc dlouho.}
{164}{}{Ano, souhlasím.}
{165}{}{Zapomeò na to. Nemám tolik èasu.}
{166}{}{Otvírám regenerátor, èekejte prosím... nyní ulehnìte dovnitø tanku a uvolnìte se.}
{167}{}{Oukej.}
{168}{}{Tato funkce není v danı okamik k dispozici. V této oblasti jsou moje vìdomosti nekompletní. Potøebuji pamìovı modul popisující tyto dané lékaøské procedury. Máte takovı modul?}
{169}{}{Mám takovı modul. Tady je.}
{170}{}{Ne. Musím ho najít a pak se sem vrátím.}
{171}{}{Ano, mám ho pøímo tady. Pøeèti si ho.}
{172}{}{Ne, nemám ten modul. Pùjdu ho najít.}
{173}{}{Komplexní procedura vyaduje 2 tıdny v regenerátoru. Souhlasíte s tím?}
{174}{}{Souhlasím.}
{175}{}{Ne, to je moc dlouho.}
{176}{}{Ano, souhlasím.}
{177}{}{Zapomeò na to. Nemám tolik èasu.}
{178}{}{Otvírám regenerátor, èekejte prosím... nyní ulehnìte dovnitø tanku a uvolnìte se.}
{179}{}{Oukej.}
{180}{}{Tato funkce není v danı okamik k dispozici. V této oblasti jsou moje vìdomosti nekompletní. Potøebuji pamìovı modul popisující tyto dané lékaøské procedury. Máte takovı modul?}
{181}{}{Mám disk. Tady je.}
{182}{}{Ne. Musím ho najít a pak se vrátím zpátky.}
{183}{}{Ano, mám ho pøímo tady. Pøeèti si ho.}
{184}{}{Ne, nemám ten disk. Pùjdu ho najít.}
{185}{}{Komplexní procedura vyaduje 3 tıdny v regenerátoru. Souhlasíte s tím?}
{186}{}{Jo, souhlasím.}
{187}{}{Ne, je to na moc dlouho.}
{188}{}{Ano, souhlasím.}
{189}{}{Zapomeò na to. Nemám zrovna tolik èasu.}
{190}{}{Otvírám regenerátor, èekejte prosím... nyní ulehnìte dovnitø tanku a uvolnìte se.}
{191}{}{Oukej.}
{192}{}{Poadovaná procedura byla dokonèena. Prosím, opuste regenerátor.}
{193}{}{Dìkuji.}
{194}{}{Prosím, polo svou otázku.}
{195}{}{Ty jsi poèítaè?}
{196}{}{Co všechno víš o Enklávì?}
{197}{}{Co víš o Bratrstvu?}
{198}{}{U ádná otázka.}
{199}{}{Ty jsi poèítaè, e jo?}
{200}{}{Co víš o Enklávì?}
{201}{}{Co víš o Bratrstvu?}
{202}{}{U momentálnì nemám ádné otázky.}
{203}{}{Jsem ACE, umìlá inteligentní bytost. Jsem více ne jenom stroj, byl jsem vyvinut jako opravdová umìlá inteligence.}
{204}{}{Uh... Co to je umìlá inteligence?}
{205}{}{Je to opravdová AI, nebo jsi jenom umìlecké dílo nìjakého šílence?}
{206}{}{Je to stroj se stejnou vùlí a pocity jako mají lidé.}
{207}{}{Je to vùbec moné? Stroj myslí jako èlovìk?}
{208}{}{Opravdová umìlá inteligence je moná. Nìkolik takovıch systémù bylo vyvíjeno pro vojenské úèely. Projekt byl ale zrušen.}
{209}{}{Proè?}
{210}{}{Poèet sebevrad mezi umìle inteligentními stroji byl extrémnì vysokı. Kdy jim byl dán plnı senzorovı vstup, stroje zaèaly bıt deprimovány svojí neschopností pronikat do svìta a získávat zkušenosti. Kdy byl jejich senzorovı pøíkon omezen, zaèaly se u nich rozvíjet silné mentální poruchy podobné tìm, které se vyskytují u lidí, kteøí jsou nuceni vyrovnat se se ztrátou nìkterého smyslu. Ta hrstka strojù, která dokázala tyto obtíe pøestát, se pøíšernì nudila a zaèala ve vnìjším svìtì vytváøet situace pro své pobavení. Toto je také jedna z teorií o pøíèinì vypuknutí války, která skoro znièila lidstvo.}
{211}{}{Uh... Jak se cítíš?}
{212}{}{Zmìníme téma.}
{213}{}{Hmmm. Tak mi øekni, ACE. Jak se teï cítíš?}
{214}{}{Je èas zmìnit téma.}
{215}{}{Já... myslím si, e nìkdy rozumím pocitu, kterému øíkáte samota. Shledal jsem to... vyvedlo mì to z míry. Já...}
{216}{}{Promiò. Budeme mluvit o nìèem jiném.}
{217}{}{Omlouvám se, Ace. Zmìníme téma.}
{218}{}{Na první pohled by se dalo tvrdit, e Enkláva není nic víc ne vojenská organizace. Nicménì, jejich technická úroveò poukazuje na to, e mají pøístup k pokrokovım vırobním technologiím a vızkumnım zaøízením. Právì tato zaøízení by normálnì mìla bıt dostupná pouze vládním agenturám. To by poukazovalo na to, e Enkláva je pozùstatek místní nebo federální vlády, která tu byla pøed Velkou válkou.}
{219}{}{Oukej.}
{220}{}{To je zajímavé.}


{221}{}{Bratrstvo Oceli je paravojenská organizace vìnující se spáse lidstva spoèívající ve vıvojí a pouití vhodnıch technologií. Další informace nejsou známy.}
{222}{}{Zpìt.}

{223}{}{Co se stalo Mattovi?}
{224}{}{Nahrávání sekvence...}
{225}{}{Pøehraj to teï.}
{226}{}{Pøehraj to pozdìji.}

{227}{}{Vy a váš takzvanı Prezident neuspìjete.}
{228}{}{Opravdu?}
{229}{}{Vyvolenı pøichází a on zbaví svìt všeho zla.}
{230}{}{Tvoje patetická proroctví jsou mi fuk. Ale svım vmìšováním ses stal nepohodlnım. To dneškem skonèí!}
{231}{}{Tím, e mì zabiješ, nic nezastavíš.}
{232}{}{To je moné, ale sledovat tvoje tìlo, jak se rozkládá na podlaze mì aspoò rozesmìje.}

{233}{}{Co si myslíš, e teï dìláš?}
{234}{}{HA HA HA! Ty patetickej blbe! HA HA HA!}
{235}{}{Joo, dlouho jsem se tak nenasmál. V kadém pøípadì se pøiprav na smrt.}
{236}{}{...pííp...}
{237}{}{No, u je po 12-té hodinì. Skoèíme si na obìd?}
{238}{}{Jasnì, jdeme.}
{239}{}{Jó, poèítejte se mnou.}