#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš vstupní systém bez klíèe. Na ceduli píší "Zde použij Tanker FOB".}
{101}{}{Vidíš vstupní systém bez klíèe. Na ceduli píší "Zde použij Tanker FOB".}
{102}{}{Tato konzole má pøipevnìnou èernou desku s èerveným svìtlem nahoøe. Na ceduli stojí "Zde použij Tanker FOB".}
{103}{}{Tato konzole má pøipevnìnou èernou desku se zeleným svìtlem nohoøe. Na ceduli stojí "Zde použij Tanker FOB".}

{104}{}{[kliknutí] Svìtlo na èerné desce zezelenalo.}
{105}{}{[kliknutí] Svìtlo na èerné desce zèervenalo.}
{106}{}{Nic se nedìje.}
{107}{}{Nepracuje to.}

{108}{}{Je to dálkovì ovládaný elektronický systém dveøí. Toto obvykle vyžaduje magnetický klíè urèitého druhu.}
