#tento soubor pøeloil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš poèítaèovı terminál.}
{101}{}{Vidíš fyzickou stanici.}
{102}{}{Vidíš funkèní poèítaèovı terminál.}
{103}{}{Zdravím. Prosím potvrïte vaši totonost.}
{104}{}{[Oooh! Podívej na blikající svìtla!]}
{105}{}{::vlo heslo::}
{106}{}{KSLJKJ:Ken-Lee-97313}
{107}{}{::dostat se do poèítaèe::}
{108}{}{Odlogování.}
{109}{}{Fyzikální databáze: -Prùzkum- -Teorie-}
{110}{}{Prùzkum...}
{111}{}{Teorie...}
{112}{}{Deaktivovat stanici.}
{113}{}{Nekorektní heslo. Obrae se prosím na systémového administrátora. Nashledanou.}
{114}{}{::dostat se do poèítaèe::}
{115}{}{::odejít::}
{116}{}{Zjištìn narušitel. Program se zavírá. Pøeju hezkı den.}
{117}{}{-hotovo-}
{118}{}{"S nedávnım ziskem vertibird plánù, pokroèila monost vytvoøení praktického létacího stroje o notnı skok dopøedu. Oèekáváme, e budeme mít pracující prototyp koncem roku a budeme schopni masové produkce takovıch strojù bìhem dvou let." -Dr. Wong}
{119}{}{::Zkopíruj plány:: Zpìt.}
{120}{}{Zpìt.}
{121}{}{"Poøád pøipravujeme funkèní model vzdušného stroje. ádnı z designù, jen jsme stvoøili, se neosvìdèil jako bezpeèenı nebo aerodynamickı. Moná, kdybychom mìli pøístup ke starım plánùm..."-Dr. Wong}
{122}{}{Zpìt.}
{123}{}{(Po tìkém pøekonání zaèátkù souvisejících s matematikou zjišuješ, e se Shiové zase uèí rozvíjet nukleární síly, pøedìlávají teorie vesmírnıch cest starého vìku - zatímco hubologisté se jim posmívají - a vyuívají energie slunce, vìtru a moøe. Tak se to alespoò traduje.)}
{124}{}{Zpìt.}
{125}{}{Stanice deaktivována.}
{126}{}{Aktivovat stanici.}
{127}{}{-odejít-}
{128}{}{Nìjak, náhodnì si namaèkal nìjaké klávesy a dostal si se do poèítaèe! Jak sem toho dosáhnul?}
{129}{}{-více-}
{130}{}{Poèítaè nereaguje na ádnı pokyn.}
{131}{}{Nevypadáš, e bys našel nìjaké místo, kam to odloit.}

{132}{}{Kopírování plánù..... kopíruj kompletnì... Navracející se k... I/O error... GPF... Terminál se deaktivuje.}
