#tento soubor pøeložil Mawerick - megaboy@iol.cz, http://rpg.game-star.cz
{100}{}{Vidíš poèítaè PoseidonNet.}
{101}{}{Vidíš poèítaè PoseidonNet.}
{102}{}{Vidíš poèítaè PoseidonNet.}


{103}{}{::pííp:: Terminál selhává. Požaduj NavComp instalaci. ::pííp::}
{104}{}{-hotovo-}
{105}{}{Vítej v PoseidonNet. Tento terminál je limitován pøenosem mezi tankerem - PMV Valdez - a pøístavištìm. Rozkaz?}
{106}{}{Jdi.}
{107}{}{Zkus status.}
{108}{}{Odlogovat.}
{109}{}{-Palivová nádrž: prázdná- -Nákladový prostor: prázdný- -Navigaèní Computer: nefunkèní- -Kotevní lana: pøipevnìna-}
{110}{}{-zpìt-}
{111}{}{Odlogování.}
{112}{}{-Palivová nádrž: plná- -Nákladový prostor: prázdný- -Navigaèní Computer: nefunkèní- -Kotevní lana: pøipevnìna-}
{113}{}{-zpìt-}
{114}{}{Odlogování}
{115}{}{ERROR: Palivová nádrž prázdná.}
{116}{}{ERROR: Navigaèní Computer nefunkèní.}

{117}{}{-Palivová nádrž: prázdná- -Nákladový prostor: prázdný- -Navigaèní Computer: funkèní- -Kotevní lana: pøipevnìna-}
{118}{}{-Palivová nádrž: plná- -Nákladový prostor: prázdný- -Navigaèní Computer: funkèní- -Kotevní lana: pøipevnìna-}

{119}{}{Vidíš navigaèní poèítaè PoseidoNet.}

{129}{}{(Rychle spouštíš sekvenci pro uvolnìní kotevních lan a opuštìní pøístavu.)}
{130}{}{-hotovo-}
{131}{}{Navigaèní computer zapnutý.}
