#tento soubor pøeloil Mawerick - mawerick@mybox.cz, http://rpg.game-star.cz
{100}{}{Vidíš ghoula, kterı vypadá obzvláš konatì a vysušenì.}
{101}{}{Vidíš Harolda.}
{102}{}{Vidíš velmi starého, ale poøád ještì èilého ghoula.}

{103}{hld1a}{Musím ti øíct, starej Harold u je trošièku pomalejší. Ale kdy tu budeme my dva takhle kecat, moc toho neudìláme.}
{104}{hld1b}{Ah, ty jsi prostì miláèek. Bohuel nemám zrovna èas na to, abych se tì snail pochopit.}
{105}{hld1c}{He he, jsi bourák, co? }

{106}{hld2a}{Nazdárek, hezounku. Mı jméno je Harold. Pomáhám udrovat tohle mìsto v chodu.}
{107}{hld2a1}{Tak co potøebuješ, štìnì?}

{108}{hld2b}{No, sakra jemináèku, hezoune. Fakt jsi nám hodnì píchnul s naší elektrárnou. Jmenuju se Harold. Pomáhám udrovat tohle mìsto v chodu.}
{109}{hld2c}{Je od tebe fakt hezkı, es nám pomohl s atomovou elektrárnou. Jsme tvoji dluníci. Teï, co pro tebe mùe tahle skoro-zdechlina udìlat?}
{110}{hld2d}{Ty jsi ale èíslo. Pøesnì jako originál. Co pro tebe mùe starej Harold udìlat, Zakladateli? }
{111}{hld2e}{Nezkazil jsi u toho dost, hezoune? Co chceš teï?}
{112}{}{Hezoun? Proè mi tak øíkáš?}
{113}{}{Zakladateli? Nejsem Zakladatel.}
{114}{}{Ahoj, Harolde. Co pøesnì tu dìláš?}

{115}{}{Je tu nìkde místo, kde mùu obchodovat a sehnat zásoby?}
{116}{}{To je strom, co ti roste z hlavy?}
{117}{}{Ty musíš urèitì vìdìt, jestli je tady nìco, èemu se øíká GECK.}
{118}{}{Harolde, Zajímalo by mì, jestli je tu doktor, nebo tak nìco.}
{119}{}{Vím, e se poøád zlobíš, ale øíkal jsi nìco o Mistrovi. To mùj pøedek ho zabil.}
{120}{}{Nazdar, Harolde. Jenom procházím. Mìj se.}

{121}{hld3}{Co...cokoliv je potøeba k tomu, aby tohle místo vydrelo pohromadì.}
{122}{}{Tohle místo by se rozpadlo?}
{123}{}{Nezní to moc dobøe.}

{124}{hld3a}{Jasnì, ale na mrtvolu si vedu dost dobøe! Nikdy mì neomrzí ty pohledy, kdy tohle øeknu.}
{125}{}{Tak dobøe... Take ty øíkáš, e se tohle místo rozpadá?}
{126}{}{Mrtvola øíkáš? Tak, v tom pøípadì ti to jde fakt vıbornì. Tak dobøe, e mi odpovíš i na další otázku.}

{127}{hld4a}{No, trošièku. Náš atomovı reaktor je malièko... citlivı. Lidi co se o to starají to myslí dobøe, ale... no, ale nejsou to zrovna štiky v rybníce. Jestli víš co myslím.}
{128}{hld4b}{Vlastnì, teï kdy je reaktor opravenı to jde dobøe. Nemyslel jsem si, e by nìkdo dokázal pøesvìdèit ty idioty ve Vault City, aby nám pomohli.}
{129}{hld4c}{Víš, teï to není tak špatnı. Opravíš elektrárnu, a pak seeneš informace kterı potøebujeme, aby byla jako nová. Doprèic, jsi fakt tøída!}
{130}{}{Co tím myslíš?}
{131}{}{Nechtìl jsem se dívat, jak Vault City znièí vaše mìsto.}
{132}{}{No, nechtìl jsem se dívat jak Vault City znièí vaše mìsto. Mimochodem to bylo taky v jejich zájmu, aby byla elektrárna v poøádku.}
{133}{}{Vlastnì, protoe je ve vlastním zájmu Vault City, aby byl reaktor opravenı, nebylo moc tìké získat od nich Optimalizaèní informace.}
{134}{}{Nerad nechávám vìci napùl rozdìlané.}
{135}{}{No, hroznì rád bych zùstal a pokecal, ale mám spoustu práce a tak... Hodnì štìstí.}

{136}{hld5}{No, technicky... je to taková vìcièka.}
{137}{}{Oukej, a co to dìlá?}

{138}{hld6}{Taky obèas potøebuješ trochu popostrèit, co? Myslím tím, e to nejsou zrovna géniové. Tak napøíklad. Jednou se mi dostala do ruky technická zpráva. A v ní je, e by se mìl vypnout hlavní uzávìr chladícího sytému. To by zpùsobilo takovou paseku, vedle kterı by Grand Kaòon vypadal asi jako bahništì pro prasata.}
{139}{}{To zní fakt špatnì.}

{140}{hld7}{Vlastnì, jo, to by bylo špatnı. Teï u se to vyøešilo, ale jen tak tak. Potøebujou nìkoho, kdo na nì dohlídne.}
{141}{}{Je dobøe, e tu jsi a pomáháš jim.}

{142}{hld8}{Kdo by si pomyslel e budu muset øešit takovı vìci?  Ale jestli hodnì rychle neseeneme hydroelektrickı regulátor magnetosféry, tak budou potíe.}
{143}{}{Co to sakra je hydra-magna-cokolivátor?}
{144}{}{Hmm, to zní fakt jako problém. Zeptám se na nìco jinıho.}
{145}{}{Potíe? Jakı potíe?}
{146}{}{Víš, u jsem tì pøipravil o hodnì èasu. Nashle.}

{147}{hld9}{Hej, nebıt tebe, ty zadìlanı idioti z Vault City by nám zaøídili rychlı ubytování v hlínì.}
{148}{}{Nemohl jsem nechat Vault City, aby vás pozabíjeli.}
{149}{}{Rád pomáhám, Harolde. Ale zeptám se tì ještì na nìco.}

{150}{hld11a}{To je od tebe hezkı. Není hodnì hezounù, co by tohle udìlali pro mìsto plnı ghoulù. Trochu mi pøipomínáš hezouna, kterıho jsem kdysi znával.}
{151}{hld11b}{Víš, jsi hodnì podobnı Zakladateli.}
{152}{}{Jinej hezoun? Koho tím myslíš?}
{153}{}{Díky. Doufám, e budu ít jako mùj pøedek. Ještì se tì na nìco zeptám, dokud tu jsem.}
{154}{}{Rád pomáhám. Ale zeptám se ještì na nìco.}
{155}{}{Vlastnì, je to moje kadodenní práce. Ale u musím jít. Zachraòovat lidi, zabíjet pøíšery, zabraòovat katastrofám a takovı podobnı vìci. Mìj se.}

{156}{hld14}{Krájíš tupou stranou noe, e jo?  Nevypadáš jako pomeranèová kùra, kterou nìkdo nechá pøes den na slunci. Máš ještì poøád mìkkou a èistou kùi. }
{157}{}{Dostal jsi mì. Zkusím aby další otázka byla rozumnìjší.}
{158}{}{Oh. Jasnì. Take, zeptám se na nìco jinıho.}
{159}{}{Radši u nedìlej na mojí kùi další fórky, jasnı?}
{160}{}{Uh, vlastnì bych u mìl jít. Zatím.}

{161}{hld15}{Fórky? Myslíš jako stáhnout tì zaiva rezavım, tupım, starım noem a potom si naroubovat tvoji ještì teplou, vlhkou, blıskavou, a tak jemnou kùi pøes ten mùj ztvrdlej ohoz?}
{162}{}{Hej! Sakra dr se ode mnì dál. Padám odsud, dokud jsem ještì ve svojí kùi!}
{163}{}{Jasnì, pøesnì tohle jsem myslel. Dobrej odhad.}

{164}{hld16}{Vlastnì se nemusíš nièeho bát... nemùu najít svùj kapesní noík.}
{165}{}{Nezmìníme radši téma?}
{166}{}{Radši na mì tìma umounìnıma prackama nehrabej. Sbohem.}

{167}{hld17}{Víc kùe! ... Potøebuju víc kùe! (chechtá se) Co je s tebou? Ztratil jsi smysl pro humor na cestì do mìsta?}
{168}{}{Mám toho spoustu na starosti, jasnı? Potøebuju informace.}
{169}{}{Asi ho pùjdu hledat. Sbohem.}

{170}{hld18}{Zrovna jsem si prdnul, ale tvùj smrad to prostì nepøebije. Proè se odtud neodvalíš?}
{171}{}{Fajn, ale napøed se chci omluvit za to, jak jsem se choval.}
{172}{}{Tak tam klidnì narvi ponoku, starej smradlavej ghoule. Jdu pryè.}

{173}{hld19}{To je koneènì zaèátek, ale budeš se muset polepšit.}
{174}{}{Nevím co na to mám øíct. Myslím, e si s neznámıma vìcma nevím napoprvé rady. Omlouvám se.}
{175}{}{Fajn, a co tøeba tohle? Kdybych mìl mršinu která vypadá z pùlky tak blbì, jako ty, radši bych ji spálil, aby se mrchorouti neotrávili. Sbohem.}

{176}{hld20a}{No, dobøe. Ale radši se pøestaò chovat jako tupoun. }
{177}{hld20b}{Nìco ti povím, štìnì. Hezkej pokus, ale poøád jsi idiot. Moná, e právì tohle je lekce, kterou potøebuješ. Vypadni.}
{178}{}{Omlouvám se. Teï kdy jsme to urovnali. Na nìco se tì zeptám.}
{179}{}{Fajn, sbohem.}

{180}{hld21a}{Radši vypadám takhle, ne abych vypadal, jako ty a choval se tak. Jsi tupoun. A teï kurva vypadni. }
{181}{hld21b}{Jsi jak ten hnusnej hemr, co ho nemùeš setøást z prstu. Ale já poøád tøepu.... A hele, u povoluje!}
{182}{hld21c}{Podívejme, co nám vítr pøivál. Mùj oblíbenı prd. Proè odtud prostì nevymajzneš?}
{183}{hld21d}{Chceš vìdìt, jak udret idiota v nejistotì?}
{184}{hld21e}{Hej, doufal jsem e se ukáeš. Vyhrál jsi cenu pro nejvìtšího kreténa. Ve mìstì deset mil severnì odtud je párty na tvoji poèest. Radši si pospìš.}

{185}{hld26}{V jejich zájmu? Co tím myslíš?}
{186}{}{No, s ohledem na nìjaké ekonomická data, tìm z Vault City se hodnì vyplatí, kdy vám pomùou vaši elektrárnu opravit.}
{187}{}{Myslím, vdycky je lepší snait se se sousedy vycházet.}
{188}{}{Vlastnì nic.}
{189}{}{Jo, je u hodnì pozdì. Radši pùjdu. Mìj se.}

{190}{hld27}{Ekonomická data? Nedal jsi jim snad ty informace, o kterıch poøád dokola mele Gordon, e ne?}
{191}{}{Uh, jo dal. Proè?}
{192}{}{Uh, ne, samozøejmì e ne.}

{193}{hld28}{Jasnì, no, nìjakej tupoun, asi jako ty, øíkal o Mistrovi to samı.}
{194}{}{To zní, jako bezva pøíbìh. Kdybych tak mìl èas si to poslechnout. Ale musím jít.}
{195}{}{Mistr? Mùj pøedek ho zabil!}

{196}{hld29}{Nic, jo? Na to neskoèím. Tak teï jsme v tom. Teï to si budu muset promyslet, co dál.}
{197}{}{Uh, sorry.}
{198}{}{Jo, jasnì. Tak proè to prostì neudìláš. Hehe, zkus pomoct pár lidem....}

{199}{hld30}{Proè?! Teï Vault City ví, jak moc potøebujeme uranovou rudu z Broken Hills. Mùou odøíznout dodávky a my budeme vyøízení.}
{200}{}{Oh, pøece nemùe bıt tak zle. Mnì pøipadají jako rozumní lidé.}
{201}{}{Nevìdìl jsem, e tohle je zpùsob, jakım ty informace zneuijí. Je mi to líto. Nashle.}

{202}{hld31}{No, doufám e ne. Ti idioti z Vault City nenávidí ghouly. Mohli by odøíznout naše zásilky z Broken Hills v jediné minutì. A pak si nadiktujou podmínky. Nebude to trvat dlouho a z Gecko bude koncentrák.}
{203}{}{Oh, tohle urèitì neudìlají. Vypadají, jako slušní lidé.}
{204}{}{Tak v tom pøípadì je dobøe, e jsem jim nic takového neøekl. Cha, cha. Zeptám se na nìco jiného.}
{205}{}{No a co, stejnì se hovno stane. Nìkdy se prostì všechno posere. Mìjte se.}

{206}{hld32}{Rozumní? Rozumní! Jsem si jistı, e lidé øíkali, e Vùdce byl taky rozumnı. Boe, to je ale kretén. Vypadni. Teï hned!}
{207}{}{Moná e mají pravdu. Moná je èas koneènì zatoèit s blbounama jako jste vy. Nashle.}
{208}{}{Uh, no, já ehm.... tak jo. Nashle.}

{209}{hld33}{Tak to si promluv s Woozem. Nemùeš ho minout -- je to támhle pøes cestu.}
{210}{}{Díky. Zajímá mì ještì nìco.}
{211}{}{Díky, to je všechno co teï potøebuju vìdìt. Mìj se.}

{212}{hld34}{árlíš? Jmenuje se Herbert. Kdy je mi smutno, povídám si s ním... Ha, ha. Kecám... Jmenuje se Bob.}
{213}{}{Dobøe... Moná ty nebo Bob budete znát odpovìï na tohle.}
{214}{}{Dík, to je daleko víc, ne teï potøebuju vìdìt. Mìj se.}

{215}{hld35}{GECK? Vzpomínám si, e Vaulty mìly nìco takového. Nevím, kde by se dnes dalo najít nìco takového. }
{216}{}{Díky. Zajímá mì ještì nìco.}
{217}{}{Díky, to je všechno, co teï potøebuju vìdìt. Mìj se.}

{218}{hld36}{Promluv si s mım asistentem Lennym. Urèitì tì bude schopnı dát do poøádku.}
{219}{}{Díky. Zajímá mì ještì nìco.}
{220}{}{Díky, to je všechno, co teï potøebuju vìdìt. Mìj se.}

{221}{hld37}{Další hezoun. Toho bych si mìl hodnì váit.}
{222}{}{Kdo to byl?}

{223}{hld38}{Moná bych si to pamatoval, kdybych nebyl mrtvı. Ten vtip mì nikdy neomrzí. }
{224}{}{Moná e...}

{225}{hld38a}{Abych byl upøímnı, nepamatuju si jeho jméno. Ale nosil srandovní oblek. Jako ten, co máš teï ty.}
{226}{}{Tohle je oblek z Vaultu, kterı nosil mùj pøedek. Je to symbol mojí svaté vıpravy.}
{227}{}{Coe, jako tahle staroitnost?}

{228}{hld38b}{Nekecáš?}
{229}{}{Tohle je oblek z Vaultu, kterı nosil mùj pøedek. Je to symbol mojí svaté vıpravy.}
{230}{}{Nelu, Harolde.}

{231}{hld39}{Dobrá, dobrá, dobrá. Tak tím se pár vìcí vysvìtluje. Divil jsem se, jak to, e vypadáš tak povìdomì. Take neztrácím ten zbytek mozku, co ještì mám.}
{232}{}{Opravdu vypadáme podobnì?}
{233}{}{Øekni mi, jakı byl ten Zakladatel?}

{234}{hld40}{Urèitì, vypadal pøesnì takhle. Kdy o tom pøemıšlím, taky mìl na sobì èíslo 13. }
{235}{}{Vlastnì, tohle je oblek mého pøedka, Zakladatele.}

{236}{hld41}{Je tu jistá podoba. Nakolik si vzpomínám. Víš, e tvùj pøedek hodnì z nás zachránil.}
{237}{}{Zakladatel zachránil všechny ghouly?}
{238}{}{Díky. Je fajn to vìdìt. Podívej, potøebuju si odbìhnout. Pøijdu pozdìji.}

{239}{hld42}{Pøeskakuješ na závìr, štìnì. Jednou ti nìkdo kvùli tomu ustøelí zadek. Všechny z nás. Zachránil kadıho tvora na tıhle blbı planetì. }
{240}{}{To jsem si neuvìdomil.}
{241}{}{Myslím, e pro tentokrát jsem u slyšel dost. Nashle.}

{242}{hld43}{No. A teï zase ty. A co se stalo pak? Jako díky, ti zatracení velicí Vauláci Zakladatele vyhnali. Vdycky mì zajímalo, co se stalo potom.}
{243}{}{Mùu ti vyprávìt, co se pak stalo.}
{244}{}{Konec vzpomínání, zajímá mnì nìco jiného.}

{245}{hld44}{Rád bych si to poslechnul.}
{246}{}{Legenda Zakladatele zaèíná, jak ho z Vaultu vyhnali do Pustiny.... [Povídáš Haroldovi pøíbìh svého pøedka]...a proto teï hledám Vault 13.}

{247}{hld45}{Díky za pøíbìh. Všechny ty roky jsem byl zvìdavı. To máš teda opravdu nìco na práci. Ehm, víš....}
{248}{}{Víš co?}
{249}{}{U jsem tì pøipravil o dost èasu. Radši pùjdu. Mìj se.}

{250}{hld46a}{Vlastnì, tohle jsem si schovával pro nìjakı deštivı den, ale vypadá to, e ty je teï potøebuješ víc, ne kdy já budu. Tady, vem si tohle.}
{251}{hld46b}{Chtìl jsem ti nìco dát, ale sakra, jestli já jsem to u neudìlal. Øeknu ti, to stárnutí nedìlá pamìti dobøe.}
{252}{}{Díky. Zajímá mì ještì nìco.}
{253}{}{Díky za všechno. Radši u pùjdu. Mìj se.}

{254}{hld48a}{Bez funkèního Hydroelektrického regulátoru magnetosféry nám prosakuje radioaktivní chladicí kapalina do podzemních vod. To znamená, e kdokoliv pouije tu vodu, nebude potøebovat baterku a pùjde o pùlnoci na záchod. Taky potøebujeme víc paliva, protoe ho elektrárna nespaluje efektivnì.}
{255}{hld48b}{Potøebujeme Hydroelektrickı regulátor magnetosféry a potøebujeme ho nainstalovat brzo, nebo budeme mít vánı problémy.}
{256}{}{To zní špatnì. A kde seenete to Hydro magnetonìco-nebo-tamto?}
{257}{}{A co se stane, kdy to nebudete mít?}
{258}{}{Od koho kupujete palivo?}
{259}{}{To mì mrzí. Ale zajímá mì ještì nìco.}
{260}{}{Myslím, e vás zatím budu muset nechat s vašim problémem. Nashle.}

{261}{hld49}{Jsem si jistı, e ty bastardi ve Vault City jeden mají. Ne, e by nám ho dali. Sakra, i kdybychom tu vìcièku mìli, nejsem si jistı, jestli by to Festus umìl nainstalovat.}
{262}{}{Vault City vám tu souèástku nedá? I kdy by to vyøešilo problémy se zneèištìním vody?}
{263}{}{Vypadá to, e máš hodnì starostí. Nashle.}

{264}{hld50}{Jestli to neseeneme, mùeš se vsadit, e nám ti tupouni z Vault City pøijdou zavøít krám, úplnì a navdy.}
{265}{}{A co budete potom dìlat?}

{266}{hld51}{Palivo máme z Broken Hills. To je tìaøská komunita jinì odtud.}
{267}{}{Zajímavé. A kde vezmete ten Hydro magnetonìco-nebo-tamto?}
{268}{}{Co se stane, kdy neseenete tu Hydro-souèástku?}
{269}{}{Hmm, asi vás nechám, abyste si to vyøešili sami. Nashle.}

{270}{hld52}{Prdìt do hlíny. Vault City se s tím nepáøe. Jestli tu souèástku neseeneme, tak prostì pøijdou a všechny nás pobijou. Já bych mìl aspoò stromeèek místo pomníku.}
{271}{}{Jake se ta souèástka jmenuje?}
{272}{}{Vypadá to, e tu Hydro-vìc fakt nutnì potøebujete. Ale rád bych ještì na nìco zeptal.}
{273}{}{To vypadá jako prùser. Potøebuju nìkam zabìhnout a zjistit, co mùu udìlat. Zatím.}

{274}{hld53}{Oni by nám pomohli, jenom kdyby to bylo v jejich vlastním zájmu. Huh. A není velká šance, e se tak stane..}
{275}{}{Hmm, asi máš pravdu. Ale stejnì, kdyby je nìkdo pøesvìdèil, e vám mají pomoct....}

{276}{hld54}{Ghouly støílí, jen co je uvidí. To je pak tìká konverzace.}
{277}{}{A co kdyby jim to øekl nìkdo jinı.}
{278}{}{Jasnì. Ale teï mám ještì otázky.}
{279}{}{Hej, nikdy nevíš. uvidíme se pozdìji.}

{280}{}{Na sever}
{281}{}{Na severozápad}
{282}{}{Na západ}
{283}{}{Na jihozápad}
{284}{}{na jih}
{285}{}{Na jihovıchod}
{286}{}{Na vıchod odtud}
{287}{}{Na severovıchod}
{288}{}{Nerozumím.}
{289}{}{Nevím.}
{290}{}{To bolí.}
{291}{}{To fakt bolí.}
{292}{}{To musí bolet.}
{293}{}{O tom nic nevím.}
{294}{}{Ano}
{295}{}{Ne}
{296}{}{Proè se mnou takhle mluvíš?}
{297}{}{Nejsi hezkı.}
{298}{}{Díky.}
{299}{}{To je fajn.}
{300}{}{To není dobré.}
{301}{}{Mám z toho dobrı pocit.}
{302}{}{Mám z toho špatnı pocit.}
{303}{}{Ti lidi jsou šílení.}
{304}{}{Nic jsem se nenauèil.}
{305}{}{Nìco jsem se nauèil}
{306}{}{To jsou tu všichni šílenci?}
{307}{}{Musí tu bıt jiná cesta.}
{308}{}{Pojï za mnou.}
{309}{}{Zkus tohle.}
{310}{}{pojï sem.}
{311}{}{Mám strach.}
{312}{}{Mám starosti.}
{313}{}{Nìco jsem našel.}
{314}{}{Mám štìstí.}
{315}{}{Musíš to spravit.}
{316}{}{Musíš to zapnout.}
{317}{}{Musíš to odemknout.}
{318}{}{Musíš to otevøít.}
{319}{}{Moná bychom se mìli vrátit.}
{320}{}{Ujistím se, e reaktor bude v poøádku. A tak nebo jinak. Hmm,
 zajímalo by mì, jestli Festuse pøesvìdèím, aby to udìlal. Tak jo, zatím èau.}
{321}{}{Hej Harolde. Mám tu souèástku na opravu reaktoru. Myslím, e by se mìla nìjak nainstalovat.}
