#tento soubor pøeloil Mawerick - mawerick@mybox.cz, http://rpg.game-star.cz
{100}{}{}
{101}{}{}
{102}{}{}

{103}{powr1}{Tady ENKLÁVA. Proè nepracuje váš videokanál?}
{104}{}{No, všechno je v poøádku. Já vás vidím.}
{105}{}{Je rozbitı.}
{106}{}{Právì dìláme na optickém vedení. Chtìl jsem to vyzkoušet.}
{107}{}{(Odpojení.)}

{108}{powr2}{Kdo to sakra je?}
{109}{}{Tady jsme všichni v poøádku. Jak jste na tom vy?}
{110}{}{Tady caau, rit, sss, pu-, -lyšíš. Pøepínám.}
{111}{}{Jsem Vyvolenı, tak radìji vol svá slova.}
{112}{}{Hlásí se jednotka tøi.}

{113}{powr3_c}{Poøád vám to ještì nefunguje kámo. Kdo je tam?}
{114}{powr3a}{To je pøece sakra úplnì jedno. Poøád ještì kruci nic nechytám. Kdo je tam?}
{115}{}{Opakujte, prosím. Pøepínám.}
{116}{}{To bych ti øíct mohl, ale pak bych tì musel zabít.}
{117}{}{Jsem Vyvolenı.}
{118}{}{No to není nic neobvyklého. Nic u tady nefunguje tak jak by mìlo.}
{119}{}{Já to vím a ty si to musíš zjistit. Sbohem.}

{120}{powr3b_b}{O èem to mluvíš? Kdo-kdo jsi?}
{121}{}{To bych ti øíct mohl, ale pak bych tì musel zabít.}
{122}{}{Jsem Vyvolenı.}
{123}{}{No to není nic neobvyklého. Nic u tady nefunguje tak jak by mìlo.}
{124}{}{Já to vím a ty si to musíš zjistit. Sbohem.}

{125}{powr4a_a}{President! Já, eh...}

{126}{powr4b_b}{Aha? Pan chytrı, co? Tak sleduj; právì tì zamìøuju, kámo. Uvidíme jak se vypoøádáš s vnitøní ochrankou u tvıho posranıho zadku. Zmrde!}
{127}{powr4c_a}{Tak teï u mám tìch tvıch sraèek právì tak dost. Co bys øek na to trochu si zahrát s Pøepadovım drustvem a jejich plasmomety na honìnou? Ha?}
{128}{}{Moment, nechtìl jsem tì rozzlobit.}
{129}{}{Tady mám pro tebe tu tvoji stopu a ukáu ti, kam si ji mùeš strèit.}
{130}{}{Tak ty mì zamìøuješ? No tak to já tì zamìøuju taky, kámo.}
{131}{}{Hroznì rád bych se tady ještì zdrel a trochu s vámi poklábosil o vašich plánech, ale mám na práci uiteènìjší vìci. Sbohem.}
{132}{}{Tak, já, hmm, já u budu muset jít. Sbohem.}

{133}{powr5_a}{Zkus upravit zisk.}
{134}{}{Tady to je... teï u by to mìlo jít. Je to lepší?}
{135}{}{Zisk? Co bych mìl získat? Jsem dost aktivní, nemyslím, e bych mohl nìco získat.}
{136}{}{Zkusím to pozdìji. Sbohem.}

{137}{powr6_a}{Vyvolenı, jo? No promiò, e ti zrovna nelezu do zadku, ale nemám teï èas, abych poslouchal takovı sraèky.}
{138}{}{Padni pøede mnou na kolena a já moná ušetøím tvùj ivot. Jeíš, to se dobøe poslouchá.}
{139}{}{Netrvám u na padání na kolena. Myslím, e malá poklona a políbení mého prstenu bude staèit.}
{140}{}{No, chtìl jsem øíct, e jsem *vyvolenı* k tomu, abych opravil komunikaèní jednotku. Zdá se, e u nic nefunguje.}
{141}{}{Myslím, e tìch uráek u bylo právì tak akorát. Sbohem, balíku.}

{142}{powr7_a}{Jednotka tøi? Myslel jsem, e jste ještì na základnì Navarro?}
{143}{}{Základnì Navarro? No, jasnì; základna Navaro. To je, kde právì jsme. Jasnì. Vìdìl jsem to.}
{144}{}{Ne, musíme se odtamtud dostat.}
{145}{}{Váš signál se ztrácí. Sbohem.}

{146}{powr8_a}{No a není to pravda? Jenom a se to nedoslechne nikdo z presidentovıch poskokù. Do smrti bys honil dobytek do New Rena, kámo.}
{147}{}{Prezident?}
{148}{}{Mám jenom dvì nohy. Ne bych se tam dostal, byl bych dost utahanı.}
{149}{}{ádnı odpoèinek høíšníkùm. Radši to pùjdu opravit. Sbohem.}

{150}{powr9_a}{No tak ten jsem ještì neslyšel. Protoe mùj videokanál funguje, mùeš vidìt, jak se tu válím po zemi. Zdá se, e je všecko zatracenì tajnı, co? Všecky ty speciální operace na pevninì. Vùbec nevím, jak to všecko probíhá.}
{151}{}{Na pevninì? Proè? Kde jsi?}
{152}{}{No a tak to je poøád dokola.}

{153}{powr10_a}{No, víš jak je vdycky nešastnı, kdy si lidi stìují. Bere si to osobnì, jako by to byl nìjakı projev vìrnosti. Snad to patøí k prezidentùm Spojenıch Státù. Nebo, k tomu, co z nich zbylo.}
{154}{}{Prezident Spojenıch Státù?}
{155}{}{Já ho nevolil. Zdálo se mi, e ho nejvíc zajímá, jak by si dobøe zaøádil s enskou. Dávám pøednost kandidátovi, kterı u je starı na to, aby se mu ještì postavil.Víc pak myslí na svou práci.}
{156}{}{Snad máš pravdu. Víš, asi se vrátím ke své práci. Sbohem.}

{157}{powr11}{Ó, jak zábavné. Ale budeš se ze svého útìku zotavovat na skvìlém místì. Alespoò podle toho, co jsem slyšel.}
{158}{}{Take ty teï nejsi v New Reno?}
{159}{}{Radši se vrátím ke své práci. Musím opravit to spojení. Sbohem.}

{160}{powr12}{Prezident zasranıch Spojenıch Státù Americkıch pøece. O kom sis myslel, e jsem mluvil? Kdo do pr- Kdo je- Co- Mìl bych tì nakopat do tı tvı prdele. Kdo jsi?}
{161}{}{Jsem Vyvolenı. Teï mi polib... nohy.}
{162}{}{Jsem Vyvolenı.}
{163}{}{Jsem Prezident. Jsi v pìkném prùšvihu.}
{164}{}{Na takovou informaci nejsi dost dùleitı.}
{165}{}{Snad abych radši šel. Mám ještì hodnì práce. Sbohem.}

{166}{powr13}{Tady hlavní komunikaèní centrum ENKLÁVY. ...Ale to bys mìl vìdìt. Kdo jsi?}
{167}{}{Já jenom...hej, u sis všiml, e vaøenı geckon chutná skoro jako brahmíní prdel.}
{168}{}{Jsem Vyvolenı a nauèím tì, aby sis to pamatoval.}
{169}{}{Nikdo dùleitı. Sbohem.}

{170}{powr14}{Tak, ještì chvilku a chytím tì za tu tvoji prdel. Hej, poèkej chvilku. To snad není pravda... Zachytil jsem tì nìkde na pevninì.}
{171}{}{Správnì, koøene. Jsem pøesnì tam, kde mì nemùeš dostat.}
{172}{}{To nemùe bıt pravda. Jsem pøesnì naproti tobì pøes halu, u spojovacího terminálu.... To se na to podívejme. No to je ale køupan.}
{173}{}{Jo, Jsem v bloku èíslo 12, elektrárny Poseidon Oil. Pojï si pro mì.}

{174}{powr15}{Mám tì, v Poseidon Oil, reaktor èíslo 5. No tak, proè chvilku neposedíš. Uspoøádám pro tebe malou oslavu. I s ohòostrojem.}
{175}{}{Jo to je super. Ohòostroje prostì zboòuju. Tak a stojí za to.}
{176}{}{Jsem Vyvolenı. To co øíkáš, øíkej radši pìknì s úsmìvem.}
{177}{}{Nejsem nikdo dùleitı. A teï u pùjdu. Sbohem.}

{178}{powr16_a}{A jsi kdo jsi. Právì jsem na tebe poslal vısadkové komando. Pøeju hezkı zbytek dne.}
{179}{}{No tohle, kdyby fungoval videokanál vidìl bys, jak se celı tøesu.}
{180}{}{No a co hodlají dìlat?}
{181}{}{Tak já snad radši pùjdu. Nerad bych, aby pøišli ještì pøedtím, ne pøipravím uvítací ceremoniál a rozvinu èervenı koberec na uvítanou. Sbohem.}

{182}{powr17}{Obvykle nìkam vtrhnou a všecko tam vystøílejí. Po nich pøijdou jiní, kteøí se prohrabávají popelem, aby zjistili co se stalo.}
{183}{}{Mì nedostanou.}
{184}{}{Oho, teï jsi mnì vystrašil. Musím si vymìnit spodní prádlo.}
{185}{}{Nelíbila by se mi pøedstava, e jsem vèera celı den èistil zbraò pro nic za nic.}
{186}{}{No jasnì. U jsem zabíjel lépe. Sbohem.}

{187}{powr18}{Sbohem. Dál u o tobì budu èíst jenom ve zprávì o akci.}
{188}{}{Coe? Ty umíš èíst!}
{189}{}{Jo, jasnì. Jak chceš.}
{190}{}{Hej, právì ses dostal na mùj seznam.}

{191}{powr19_a}{Musel jsi pryè? Proè? Jsi pøece na pobøeí. Mìl jsi tu nejlepší ochranu. Neslyšel jsem nic o... Hej, kdo vlastnì jsi?}
{192}{}{Jsem velkı a mocnı Willie. Poklekni pøede mnou a pros za odpuštìní a pak tì snad ušetøím.}
{193}{}{Nikdo dùleitı. Kde, e je to Navarro?}
{194}{}{Jo, dobyli jsme Navarro a našel jsem tam nahı fotky tvé matky. Nebo to byl zase jenom tvùj otec pøestrojenı za enskou? Není divu, e si tak odpornì hnusnej. Sbohem, hajzle.}

{195}{powr20}{Jo, mùeš to zopakovat. Všechno je tady v ENKLÁVÌ pøísnìjší a ten zatracenı prezident nás sleduje jako jestøáb.}
{196}{}{Prezident?}
{197}{}{Tady? Kde pøesnì jste?}
{198}{}{No a tak to chodí. Ale teï se musím vrátit ke své práci. Sbohem.}
