#tento soubor pøeloil Mawerick - mawerick@mybox.cz, http://rpg.game-star.cz
{100}{}{Vidíš malého ghoula.}
{101}{}{Vidíš Percyho Crumpa, úspìšného ghoulského obchodníka.}
{102}{}{Vidíš menìího a spíše silnìjšího ghoula. Na ghoula je dost slavnostnì odìn.}
{103}{}{U všech hromù. Nemùu ti dost podìkovat za záchranu mého pøítele. Zachránèe. Musím ti nìco dát za tvé potíe.}
{104}{}{Jsem rád, e jsem mohl pomoci.}
{105}{}{A co za to dostanu?}
{106}{}{Mnoo, mìlo by se to ocenit. Stálo mì to hodnì námahy a hodnì cestování. A bylo to hodnì nebezpeènı. Mohl sem bıt zranìnı.}
{107}{}{Ty, takovej pomocník, nechceš pomoci starımu Percymu s jeho problémem? Urèitì bys mohl pomoct.}
{108}{}{Uh, nech mì o tom trochu déle pøemıšlet. Jen tak mimochodem, máš nìjakı vìci na vımìnu?}
{109}{}{Dobøe, proè mi o tom nepovíš ještì jednou.}
{110}{}{Nevìdìl jsem, e mì tím budeš obtìovat vdycky, kdy sem pøijdu. Nashle.}
{111}{}{U jsi našel Woodyho? Zaèínám si o nìj dìlat starosti. Nikdy pøedtím neodešel na tak dlouhou dobu.}
{112}{}{Hm, ne, ještì ne, ale ještì se po nìm podívám. Hele, máš nìco na vımìnu?}
{113}{}{Ne, nenašel jsem ho. Radši pùjdu zpátky ven a podívám se po nìm.}
{114}{}{Ahoj ty tam, já jsem Percy Crump, Mistr obchodník v tıhle èásti svìta. Ale ty mi mùeš ze starı známosti øíkat starej Percy. Ano, ty mùeš. Vlastnì, všichni mi tak øíkají. No a co teï pro Tebe mùu udìlat?}
{115}{}{Co pro Tebe mùe starej Percy udìlat?}
{116}{}{Zrovna jsem zjišoval, co se dìje ve mìstì.}
{117}{}{Rád bych vìdìl, jestli máš nìco, co bych mohl koupit nebo vymìnit?}
{118}{}{Uh, opravdu nic, jenom jsem se díval kolem. Nashle.}
{119}{}{Vımìna?}
{120}{}{Jít? Musím jít.}
{121}{}{Chtìl bych ti pogratulovat k tomu, e náš reaktor bìhá mnohem lépe. Teï reaktor pøede jako koèièka. Nicménì, z jiného soudku, mùj pøítel Woody je nezvìstnı.}
{122}{}{Mìl bych ti podìkovat za opravu atomového reaktoru. Ten blboun Festus by Ti nikdy nepodìkoval.
 Nicménì, z jiného soudku, mùj pøítel Woody je nezvìstnı.}
{123}{}{Není tu ve mìstì moc novejch lidí. Slyšel jsem, e Wooz podvedl nìjakıho nováèka v kartách o Èernou Orchidej. He, he, heee.
 Nicménì, z jiného soudku, mùj pøítel Woody je nezvìstnı.}
{124}{}{Dobøe, øekni mi o tom trochu víc.}
{125}{}{Oh, to je špatnı. Nenávidím smutnı historky. Nechám tì samotného s tvım alem. Nashle.}
{126}{}{Proè vdycky prodám moje zboí tak pod cenou.}
{127}{}{Mùeš mít všechno, co potøebuješ nebo chceš ještì nìco víc?}
{128}{}{Chci nìjakı vybavení?}
{129}{}{Hmm, podíváme se, co máš.}
{130}{}{Nech mì znovu podívat se na tvoje zboí.}
{131}{}{Take to mi pro tuhle chvíli staèí. Díky, Percy. Nashle.}
{132}{}{Oog. Já mizím, èau, èau.}
{133}{}{Tahle velká stará bedna plná antiradiaèních medikamentù mi nedìlala dobøe. U více, jak sto a nìco let je pozdì, abych to pouíval. He, he, heee. Tady to máš, zjišuji, e pøátelství je pro mnì cennìjší kadım rokem. Díky... pøíteli.}
{134}{}{Jsem rád, e jsem ti a Woodymu mohl pomoci. Díky za medikamenty.}
{135}{}{Vıbornì, lehkej úkol a hodnì koøisti. To mám rád.}
{136}{}{Vıbornì ty víš, e mám pøítele, kterej se jmenuje Woody. Tenhle Woody spí tak tvrdì, jako jsem ještì nikdy nevidìl. A co je horší, miluje cestování. Opravdu miluje seknout sebou do písku a chrnìt.}
{137}{}{Oukej.}
{138}{}{Jako by tìch problémù nebylo málo, tak ještì zmizí Woody. Naposled, co jsem zaslechl, bylo, e se Woody vydal na vılet do Denu. Víš, kde je Den?}
{139}{}{Jo, já vím, kde je Den. Jdu na to.}
{140}{}{Momentálnì, nevím, kde je Den.}
{141}{}{Oh, to je opravdu jednoduché dostat se tam. Tady ti to oznaèím do tı tvojí vìci, kde se to nachází.}
{142}{}{Hej, buï opatrnej! Oukej, jdi na to.}
{143}{}{V kadém pøípadì já jsem øíkal, e v okolí Gecka není tolik problémù. Ale, jak vidíš, lidé v jinıch èástech nevidí to samé.}
{144}{}{Tak?}
{145}{}{Neumíš si dát dvì a dvì dohromady? Dìlám si starosti, e si tam Woody dá v Denu šlofíka -- nakonec je to celkem dlouhı vılet -- a mohli by ho pohøbít zaiva! Potøebuju nìkoho, aby se tam po nìm podíval.}
{146}{}{A...?}
{147}{}{Mnoo, hodnì mi chybí. Proto ho hledám. (Percy na tebe mrká) Oh, Aha, ty chceš vìdìt, co za to dostaneš?}
{148}{}{Tohle je obvykle èást, která mì hodnì zajímá. Take povídej.}
{149}{}{Mnoo, dal bych ti vìtší mnoství pøedváleènıch zásob opravdovıho Rad-X a RadAwaye. Mnì u to nedìlá dobøe, ale øíkám si, e pro hezouna, jako jsi ty to bude mít velkou cenu. Vezmeš ode mì tu prácièku nebo ne? Zaplatím pouze, a budu s urèitostí vìdìt, e Woody je v bezpeèí.}
{150}{}{Kolik u tebe znamená "mnoho"?}
{151}{}{Ano, udìlám to. Brzy se sem vrátím.}
{152}{}{Ne, nemyslím si, e bych ti teï chtìl zrovna pomoci.}
{153}{}{Budu o tom pøemıšlet. Nashle.}
{154}{}{Je to zatracenì èernej kout zemì, ne kdy bych chtìl kdy poznat. Udìláš to pro mì?}
{155}{}{Ano, udìlám to. Brzy se sem vrátím.}
{156}{}{Ne, nemyslím si, e bych ti teï chtìl zrovna pomoci.}
{157}{}{Nech mì o tom pøemıšlet. Nashle.}
{158}{}{Díky, e jsi našel mého kamaráda Woodyho. Co pro tebe mùe starej Percy udìlat?}
