#tento soubor pøeloil Mawerick - mawerick@mybox.cz, http://rpg.game-star.cz
{100}{}{Osoba, kterou vidíš, je zesláblá z velkého ozáøení. Její kùe vypadá, e byla škaredì popálena.}
{101}{}{Vidíš Ozáøeného, obèana Gecka.}
{102}{}{Vidíš nìkoho, kdo byl vystaven tak vysoké radiaci, e je celı zesláblı. Tak vysoká radiace by ho mìla zabít, ale vypadá to, e mu to moc nevadí.}

{110}{}{Takhle vysoká radiace mi zajišuje jistou práci.}
{111}{}{Podívej na ten ár. Vidíš to?}
{112}{}{Miluju chodit do práce kadı den.}
{113}{}{Budeme zase potøebovat více uranu.}
{114}{}{Øekl bych, e jsme tady všichni atomovì nabití.}

{120}{}{Miluju tady to teplo.}
{121}{}{Cítím se tu bájeènì.}
{122}{}{Nevím, co bych dìlal, kdybych musel ít nìkde jinde.}
{123}{}{Miluju po ránu cítit radiaci.}
{124}{}{Aspoò sem nikdy v noci nepotøeboval baterku.}
{125}{}{(ukazuje svım opálenım prstem od tebe) Zavolej domù.}
{126}{}{Víš, jestli zavøeš ty dveøe, u se víckrát neopálím.}
{127}{}{Tohle je opravdu místo, kde cítím, e patøím.}
{128}{}{Nemùu uvìøit tomu, e ti lidé z Vault City chtìjí znièit mùj domov.}
{129}{}{Reaktore, mùj sladkı reaktore.}
{130}{}{Jsi vdycky tak skromnı.}
{131}{}{Tohle atomovı vyhøátí... zaèínám to milovat.}

{140}{}{Dìkuju za opravu reaktoru. Je tu trochu více chladnìjší, ale ne zas tolik.}
{141}{}{Brrr... díky za opravu reaktoru.}
{142}{}{Pøál bych si, abychom dostali tu souèástku.}
{143}{}{Díky za všechnu tvojí pomoc.}
{144}{}{Moná ty lidi z Vault City nakonec nejsou tak špatní.}

{150}{}{U si nevzpomenu, kdy reaktor naposled pracoval dobøe.}
{151}{}{Dneska je tu vyloenì pìkná kosa.}
{152}{}{Brrrr, já tu zmrznu.}
{153}{}{Myslím, e mám omrzliny nebo nìco takového.}
{154}{}{Je Ti zima?}
