#tento soubor pøeložil Mawerick - mawerick@mybox.cz, http://rpg.game-star.cz
{100}{}{Vidíš robota.}
{101}{}{Vidíš místnost pro údržbu reaktoru a dále vidíš robota OPRAVÁØE.}
{102}{}{Vidíš robota. Vypadá to, že je funkèní.}

{200}{}{Robot opravil jaderný reaktor.}

{300}{}{Naprogramoval jsi robota, aby znièil reaktor.}