#tento soubor pøeložil Mawerick - mawerick@mybox.cz, http://rpg.game-star.cz
#############################################################
#  Message File: GeckSetl.msg                               #
#                                                           #
#  Created: August 14, 1998                                 #
#                                                           #
#  Updated:                                                 #
#############################################################

{100}{}{Nacházíš se v osadì jménem Gecko.}