#tento soubor pøeložil Mawerick - mawerick@mybox.cz, http://rpg.game-star.cz
#############################################################
#  Message File: GeckJunk.msg                               #
#                                                           #
#  Created: August 14, 1998                                 #
#                                                           #
#  Updated:                                                 #
#############################################################

{100}{}{Vstupuješ do další èásti Gecka.}