#tento soubor pøeložil Vachy - http://vachy.moje.cz
{100}{}{Vidíš celkem pøitažlivou ženu støedního vìku.}
{101}{}{Vidíš Aileen, jednu z mìstských technièek.}
{102}{}{Vidíš celkem pøitažlivou ženu støedního vìku. Vypadá fakt schopnì, až na ty skvrny od kyseliny na rukou.}
{103}{}{Díky za pomoc.}
{104}{}{Jsem ráda, že patøíš k nám.}
{105}{}{My tìm mutantùm ukážeme.}
{106}{}{Máme stejná práva jako vy, soudruhu ...ee.. pane.}
{107}{}{Máš tu správnou vìc.}
{108}{}{Vodprejskni odsud.}
{109}{}{Hnutí CEZZ, ochránce mutací.}
{110}{}{Synu, na tvém místì bych radši držela klapaèku.}
{111}{}{Bláznivý ochránce mutantù.}
{112}{}{Proè se nevrátíš ke svým zmutovaným kámošùm?}
{113}{}{Lidská solidarita, soudruhu .. ee .. pane.}
{114}{}{Máme to proti nim.}
{115}{}{Vybral jsi vítìznou stranu.}
{116}{}{Tito mutanti vypadají na vymøení.}
{117}{}{Ukážeme mutanárkùm, kdo je tady pánem.}
{118}{}{Ani mutanti nemùžou dýchat jed.}
{119}{}{Èas èlovìèenství se blíží.}
{120}{}{Miluji myšlenku zardousit všechny mutanty.}
{121}{}{Naše vítìzství se blíží!}
{122}{}{Už brzy bude Broken Hills naše!!!}
{123}{}{Zatracený ochránce mutantù.}
{124}{}{Vystøel odsud, ty figuro.}
{125}{}{Jsi obyèejný kolaborant z øíše mutantù.}
{126}{}{Tak teï jsi teda nevybral zrovna nejlíp.}
{127}{}{Toho co's tady udìlal, budeš litovat.}
{128}{}{Vypadni nakažený idiote.}
{129}{}{Ty už musíš taky mutovat.}
{130}{}{Odstup, neèistý ïáble.}
{131}{}{Hloupý blázne, zmiz odsud.}
{132}{}{Nemám èas tì obdivovat.}
{133}{}{Jestli nìco chceš, zeptej se Jacoba.}
{134}{}{Mùj manžel Jacob se o Vás postará.}
{135}{}{Mohl bys mì pøestat otravovat ?}
{136}{}{Já ti moc nepomùžu, ale mùj manžel Jacob by mohl.}
{137}{}{Teï mì nechej o samotì.}
{138}{}{Díky za návštìvu, ale teï už jdi.}
{139}{}{Proè tì zajímá tahle špína?}
{140}{}{Chceš to udìlat po svém, co, .. stan?}
{141}{}{Prosím, nechej mne teï samotnou.}
{142}{}{Nevím co po mì chceš, ale radìji odejdi.}
{143}{}{Byli jsme nahoøe. Ty lidi v katakombách jsme nezabili!}
