#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš velkého mutanta se smyslem pro vìc, kouká mu to z oèí.}
{101}{}{Vidíš jednoho ze strácù zákona, velkého a svalnatého mutanta.}
{102}{}{Vidíš dobøe ozbrojenou a pozornou strá. Mutanta s nepøíjemnì nedoèkavou zbraní.}

{103}{}{Mohu pomoci?}
{104}{}{Levá pravá seno sláma!}
{105}{}{Chci do toho baráku! Ooooh!}
{106}{}{Nic, dobøe, dobøe, jen tak se dívám.}
{107}{}{Err... ne, opravdu ne.}
{108}{}{Jo, chci mluvit s tìmi vìzni.}
{109}{}{A co kdy tady dríte ty vìznì tak trochu nezákonnì?}

{110}{}{Vıbornì ještì jeden. Prosím.}
{111}{}{Aaaaahn!}
{112}{}{Ou-kej!}

{113}{}{Fajn, jdi o dùm dál. Tady máme zloèince, tak bì.}
{114}{}{Jo. V poøádku.}

{115}{}{Mùeme pomoci kadému, kdo sem pøijde v pravou chvíli. Jestli Ti nepomùeme, pøicházíš moc brzy.}
{116}{}{Udìláš mì?}
{117}{}{Zaøiï to.}

{118}{}{Chceš s nimi mluvit, co? Mùeš mluvit klidnì s námi. Øekni, co potøebuješ.}
{119}{}{Nikdy Vás nenapadlo, e je tady dríte ilegálnì?}
{120}{}{Muti, vem si ho!}
{121}{}{Eh, nic. Radìji pùjdu.}

{122}{}{Err... co si myslíš?}
{123}{}{Chci tím øíct, e nemáte ádné dùkazy kromì 'Jedna paní povídala'. Kdy u je tady chcete vìznit, tak jim ty zloèiny alespoò dokate, ne ?!}
{124}{}{Síla a moc je zákon. JÁ jsem zákon. Pohleïte ... }

{125}{}{Ne, nechceme, jene oni jsou fakt nebezpeèní.}
{126}{}{Dokud nìco neudìlají, jsou nevinní. Dokud nemáte jejich plán a oni jej nezaèali provádìt, jsou nevinni. Jasné?}
{127}{}{Nebezpeèní? Já jsem nebezpeènı, vy jste nebezpeèní a pøesto nejsme za møíemi.}
{128}{}{Take co?}

{129}{}{Ale ..ale ..tak jo. A si jdou, na Tvou odpovìdnost. Snad máš pravdu, tady je klíè.}
{130}{}{A je to. Pøesnì podle mıch pøedstav. Díky, a .. sbohem.}

{131}{}{No jo, ale mohli bychom bıt. A oni jsou. A zùstanou, dokud se nenajde dùvod je pustit. A teï .. odejdi v pokoji.}
{132}{}{Nee.}
{133}{}{Tak jo.}

{134}{}{Zùstanou ve vìzeni a basta. Musíme chránit okolí. A nyní odejdi v pokoji.}
{135}{}{Ne.}
{136}{}{Tak jo.}

{137}{}{Co to dìláš, vole. Okamitì toho nechej! Vypadni od tamtud!}

{138}{}{Schovej si tu støíkaèku, dokud je èas, pøíteli.}

{139}{}{Tak ty si nedáš pokoj? Co furt chceš?}
{140}{}{Klídek, jen se dívám kolem. Nepovede tudy dálnice?}
{141}{}{Err... ne, opravdu ne.}
{142}{}{Noo, chci si promluvit s tìmi vìzni.}
{143}{}{Nikdy vás nenapadlo, e je vìzníte tak trochu ilegálnì?}

{144}{}{Moc se tady nepoflakuj a koukej vypadnout.}
{145}{}{Jestli zjistím, e ti vìzòové zdrhli, tak si to nìkdo pìknì odskáèe!}
