#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš pøicáplého èlovìka ve špinavıch hadrech.}
{101}{}{Není to náhodou Brian? Je to Brian.}
{102}{}{Vidíš pricáplého èlovìka ve špinavıch hadrech. Mezi zuby má párátko pokryté mastnotou. A navíc má špinavé nehty.}
{103}{}{Hele, vypadá jako asociální trhan.}
{104}{}{Co chceš?}
{105}{}{Hmeh cobyt.}
{106}{}{Co jsi zaè?}
{107}{}{Co je tohle za místo?}
{108}{}{Slyšel jsi nìkdy o GECKu ?}
{109}{}{Eric øíkal, e potøebuje upravit dodávku energie do domu. Nìjak moc se potí.}
{110}{}{Hej, Eric je fakt spokojenej ve svém hezkém klimatizovaném domì a dodávka energie do mìsta je taky v pohodì.}
{111}{}{Právì jsem šel kolem a mluvil s Ericem. Øíkal, e to tady pozoruje a e v uranovém odpadu je ještì tolik energie, e by jí nikdy nemìl bıt nedostatek.}
{112}{}{Nic. Èau.}
{113}{}{Já? Jmenuji se Brian. Obsluhuji generátor dodávající energii tomuhle koutu zemì.}
{114}{}{Tak tebe zrovna hledám. Øíkal mi Eric, e mu není moc fajn a e potøebuje zvıšit dodávku energie pro svou klimatizaci.}
{115}{}{No, to je opravdu zajímavé. To musí bıt dobøe placenı kšeft.}
{116}{}{Dobøe, mám pár dalších otázek.}
{117}{}{Toto je elektrárna pro Broken Hills. A já se tady starám ... aby to fungovalo. A chodí to bezvadnì .. jen na uranovı odpad.}
{118}{}{To je teda fakt super. Øekni mi, .. mám ještì pár otázek.}
{119}{}{Uranovı odpad?}
{120}{}{Zajímavé. Mìj se.}
{121}{}{GECK, jo? V ivotì jsem o tom neslyšel. Ani si neumím pøedstavit, e by snad nìkdo jinı jo. Zní to jako nìjaké zvíøe nebo pøíšera s paøáty.}
{122}{}{Ne, opravdu ne. Ale chci se ještì zeptat.}
{123}{}{Není za co, ahoj.}
{124}{}{Eric chce víc energie? Ale on nemùe dostat víc energie. Je to všechno pøesnì vyváené, a kdy mu dám víc, tak pøestane fungovat nemocnice nebo svìtla nebo taky dùl. To si nemùeme dovolit.}
{125}{}{Jestli ten generátor pracuje na uran, tak máte dost vıkonu pro tuhle díru a ještì i pro New Reno. Pøidej Ericovi a nediskutuj.}
{126}{}{Ale .. ale ... on trpí.}
{127}{}{Take, nelze provést ani malou úpravièku ?}
{128}{}{[dívá se zasmušile na ciferník a øíká slabım hlasem:] Jak myslíš.}
{129}{}{Bingo. Èau!}
{130}{}{Hej! Nièeho se nedotıkej! To je choulostivì zaøízení! Ven! Vypadni! Bì pryè! Bì domù!}
{131}{}{Ooooh! Butunz!}
{132}{}{Ani ne, opravdu. Vìtšinou tady sedím a dávám pozor na ciferníky, aby drely správné hodnoty. Sem tam nìco upravím, nìkdy pøepnu spínaè. To je všechno. Zvládl by to kadı.}
{133}{}{Tak øíkáš, pøidat Ericovi do baráku?}
{134}{}{Kadı, jo? Hmmm... mám další otázky?}
{135}{}{Díky. Mìj se.}
{136}{}{No, s tím uranovım dolem a atomovou energii, která se zda bıt velmi progresivní, se dríme s dobou. Moná jsem malí, ale technicky vyspìlí.}
{137}{}{Hmm. Tak jo. Chci se jen zeptat.}
{138}{}{Dobøe. Mìj se.}
{139}{}{To teda jo, technicky to vypadá dobøe, ale ...}
{140}{}{Ale nic. Pohni sebou, lenochode.}
{141}{}{O tom nepøemıšlej. [sklopí hlavu a otoèí se k ciferníkùm] Tady. Øekni mu, a si pøestane stìovat.}
{142}{}{Ty jsi tady pánem, synu.}
{143}{}{Dostaneš do drky a hubu ti natrhnu a k uším. Nedìlej to tìší ne u to je.}
{144}{}{Moná by se mìl èastìji koupat. Pøíjemnı den pøeji.}
{145}{}{Bye.}
{146}{}{Ne, nebojím se. Potøeby mìsta daleko pøevyšují potøeby jednotlivce.}
{147}{}{No, mám ještì pár dalších otázek.}
{148}{}{To je alibismus. Øeknu mu, e není tak dùleitı, aby se tím nìkdo zabıval. Nashle.}
{149}{}{Hmm... coo... huh?}
{150}{}{Zzzzzz... vrèení èerpadla...}
{151}{}{Co chceš...? Hmm...? ::vrèí èerpadlo::}
