#tento soubor pøeložil Vachy - http://vachy.moje.cz
{100}{}{Vidíš chemickou soupravu.}
{101}{}{To je Malý chemik.}
{102}{}{Vidíš Malého chemika, soupravu, se kterou mùžeš namíchat pìkný svinstva.}

{103}{}{Kde chceš zaèít? Máš ètyøi plné lahvièky: Èervenou, modrou, žlutou, a èirou.}
{104}{}{Èervená.}
{105}{}{Modrá.}
{106}{}{Žlutá.}
{107}{}{Èirá.}
{108}{}{Radìji nic.}

{109}{}{Bereš si Èervenou. S èímpak to chceš smíchat?}
{110}{}{S Modrou... to udìlá Fialovou.}
{111}{}{Se Žlutou... to udìlá Oranžovou.}
{112}{}{S Èirou... to asi zùstane Èervený.}
{113}{}{Vypít to.}
{114}{}{Modrá, jak víš, udìlá drogu Jet... teda když dodržíš správné dávkování.}
{115}{}{Žlutá. Tvoje vìdomosti ti prozradily, že pøi správném míchání vznikne kyselina chlorovodíková.}
{116}{}{Èirá. Tvùj trénovaný zrak rozpoznal silný vitamín... ale nemìlo by se to moc míchat.}
{117}{}{Nechat toho.}

{118}{}{Bereš si Modrou. S èímpak to chceš smíchat?}
{119}{}{S Èervenou... to udìlá Fialovou.}
{120}{}{Se Žlutou... to udìlá Zelenou.}
{121}{}{S Èirou... to asi zùstane Modré.}
{122}{}{Modrá, jak víš, udìlá drogu Jet... teda když dodržíš správné dávkování.}
{123}{}{Žlutá. Ještì pøed zamícháním ti došlo, že vznikne nitroglycerin, silná výbušnina.}
{124}{}{Èirá. To udìlá neškodnou toxickou látku, vykazující jistou známku antiradiace.}
{125}{}{Vypít to.}
{126}{}{Nechat toho.}

{127}{}{Bereš si Žlutou. S èímpak to chceš smíchat?}
{128}{}{S Modrou... to udìlá Zelenou.}
{129}{}{S Èervenou... to udìlá Oranžovou.}
{130}{}{S Èirou... to asi zùstane Žluté.}
{131}{}{Vypít to.}
{132}{}{Modrá. Ještì pøed zamícháním ti došlo, že vznikne nitroglycerin, silná výbušnina.}
{133}{}{Èervená. Tvoje vìdomosti ti prozradily, že pøi správném míchání vznikne kyselina chlorovodíková.}
{134}{}{Èistá. Víš, že když budeš pokraèovat, vytvoøíš slabý jed.}
{135}{}{Nechat toho.}

{136}{}{Bereš si Èirou. S èímpak to chceš smíchat?}
{137}{}{Modrá, aby to udìlalo Modrou.}
{138}{}{Èervená, aby to udìlalo Èervenou.}
{139}{}{Žlutá, aby to udìlalo Žlutou.}
{140}{}{Vypít to.}
{141}{}{Žlutá. Víš že když budeš pokraèovat vytvoøíš slabý jed.}
{142}{}{Modrá. To udìlá neškodnou toxickou látku, vykazující jistou známku antiradiace.}
{143}{}{Èervená. Tvùj trénovaný zrak rozpoznal silný vitamín... ale nemìlo by se to moc míchat.}
{144}{}{Nechat toho}

{145}{}{Vznikla ti zajímavá Fialová tekutinu. Co s tím chceš udìlat?}
{146}{}{Vypít to.}
{147}{}{Dát to do inventáøe.}

{148}{}{Hmmm. Zajímavá oranžová barvièka, copak s tím asi udìlám?}
{149}{}{Vypít to.}
{150}{}{Dát to do inventáøe.}

{151}{}{Tmavì rudá barva. Co teï?}
{152}{}{Prohnat to hltanem.}
{153}{}{Dát to do inventáøe.}

{154}{}{Lehce zelená tekutina. Co s ní?}
{155}{}{Vypít to.}
{156}{}{Dát to pryè.}

{157}{}{Zajímavý odstín modré. Co teï?}
{158}{}{Vypít to.}
{159}{}{Nechat na pozdìji.}

{160}{}{Tahle žlutá vypadá velmi zajímavì. Co s ní udìlám?}
{161}{}{Vypít.}
{162}{}{Schovat, mùže se hodit.}

{163}{}{A hrome, dobrá práce. Máme Jet. Za to mùžeš být velmi populární v New Renu. Co s tím udìláš?}
{164}{}{Vypít to.}
{165}{}{Nechat to na horší èasy.}

{166}{}{Uhhhhhh! Vznikl z toho malý toxický mrak! Odfouklo tì to pryè. Seš z toho docela na sraèky.}
{167}{}{-dál-}

{168}{}{Tak to vypadá docela mocnì. Co s tím udìláš?}
{169}{}{Vypít to.}
{170}{}{Schovat to.}

{171}{}{Och ne! Koncentrace je moc silná, zaèalo se to prožírat skrz sklo do tvého tìla! Auuuuuu!}

{172}{}{Je z toho opravdu výbušnina!}
{173}{}{Vypít to.}
{174}{}{Schovat do inventáøe.}

{175}{}{A špetku sem, špetku tam a je ...to ...BOOM!}

{176}{}{Oh ne! Ty blbe! Právì si vypil explosivní látku!}

{177}{}{Cítíš se trochu smìšnì. Ne, cítíš se hodnì trapnì. Ve skuteènosti, se cítíš, jako když se tvoje srdce maximálnì zrychlí a svìt kolem maximálnì zpomalí a ty nevíš, co se dìje a nemùžeš nikomu pomoct, protože nevíš, co je to, co je za tebou! AAAAAAH! TO JE HRÙZA!!!}

{178}{}{Tvoje grimasa se zmìnila v závislosti na chuti nápoje, který v tobì jakoby hoøí. Ouch. OUCH. OUCH!! Pomalu tì zaèíná rozežírat zevnitø! }

{179}{}{Máš trochu zamlžený zrak a tøesou se ti kolena. Ale jinak už se cítíš trochu lépe.}

{180}{}{Ahh, Co to k èertu je. Zaèaly se ti vaøit vnitønosti. Zvracíš a pliveš krev. To je z ozáøení!}
{181}{}{-konec-}

{182}{}{Dobrá... takže. Vzpomínáš si, co jsi pil jako dítì a obracíš tu lahvièku do sebe. Trochu se ti zvedá žaludek. Je ti, jako když tì uštkne radškorpión.}

{183}{}{Hele, to vypadá jako voda, asi to nebude špatné, heh? Ještì døív, než nápoj dorazil do hrdla, jsi poznal, žes to byla chyba. Tohle pìknì PÁLÍ. Kroutíš se bolestí. Dlouho, pìknì dlouho.}

{184}{}{Trochu toho a trochu toho... chvíli poèkat... proè se z tý lahvièky kouøí... co je asi špatnì...  OH NÉÉ! Láhvièka ti explodovala do oblièeje!}

{185}{}{Mícháš jemnì ingredience dohromady, doufaje, že tak vytváøíš správné složení chemikálií. Potom si sedáš a èekáš až to bude. A èekáš. A èekáš. Látka trochu ztmavla a vzala na sebe hnìdou barvu....  Asi už je to nanic.}

{186}{}{Vznikl ti slušný vitamín. Co s ním teï budeš dìlat?}
{187}{}{Vypít to.}
{188}{}{Schovat na pozdìji.}

{189}{}{Vytváøíš toxin! Co s ním teï?}
{190}{}{Vypít to.}
{191}{}{Uložit na pozdìji.}

{192}{}{Úspìšnì vytváøíš látku, snižující úèinky radiaèního otrávení. Co s tím chceš udìlat?}
{193}{}{Vypít to.}
{194}{}{Schovat do inventáøe.}
