#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš pøátelsky vypadajícího, hubeného mue.}
{101}{}{Vidíš Chada od karavan.}
{102}{}{Vidíš hubeného mue s roztomilım úsmìvem. Má na sobì nìco nepopsatelného a vypadá, e ví co dìlá.}

{120}{}{Jak to jde kámo, co pro tebe mùu udìlat?}
{121}{}{Víc otázek? Uvidíme jaké.}
{122}{}{Všiváku prašivej!}
{123}{}{Co jsi zaè?}
{124}{}{Marcus chtìl o tobì nìco vìdìt.}
{125}{}{Je tu dost dùkazù o tom, e jsi ztopil prachy pro Broken Hills, mùeš za to jít za katr. Jsi fakt v prdeli.}
{126}{}{Jsou tu nìjaké dùkazy o tom, es ukrad prachy pro Broken Hills, z èeho plyne, e mùeš jít do basy. Naval $1000 a zajistím ti bezpeènı útìk z mìsta.}
{127}{}{Kdo jsi?}
{128}{}{Povìz mi nìco o tomhle místì.}
{129}{}{Nic. Ahoj.}

{130}{}{Podívejme, jakej prosáèek sem pøišel! Sorry, kámo, nemùu ti pomoct.}
{131}{}{Uij si to!}

{132}{}{Sem Chad.}
{133}{}{Podívej, mám moc práce, zkus si najít nìkoho jinıho na kecání.}
{134}{}{Sem šéf karavan tohohle mìsta. Dávám bacha na obchod a na vımìnu na koncích cest. Teïka jsem se trochu zamìøil na Gecko.}
{135}{}{Buï v pohodì!}
{136}{}{Chci s tebou pracovat.}
{137}{}{To zní skvìle.}
{138}{}{To zní nudnì.}
{139}{}{Ještì mám otázky.}
{140}{}{Dík. Èau.}

{141}{}{Povìdìt ti o Broken Hills? Dobrá... Pøišel jsem sem pøed nìkolika léty. Mìl jsem práci s Billem -- to je ten vetešník - a zùstal jsem tu. Všechno hlásím Marcusovi a Billovi, ale jsem odpovìdnı za ivot ve mìstì.}
{142}{}{Ještì mám otázky.}
{143}{}{Na vidìnou.}

{156}{}{Promluv si s Billem. Pomùe ti.}
{157}{}{Mùu se zeptat.}
{158}{}{Dík. Ahoj.}

{159}{}{Ano, to je ono. To nemùeš znát, ale vezmu tì sebou. Aspoò poznáš svìt... a taky pochopíš, proè pøispívám na tohle mìsto. Je to skvìlı ivot.}
{160}{}{To vypadá dobøe. Takovouhle práci beru.}
{161}{}{Asi to bude pìkná nuda.}
{162}{}{Máš ještì nìjaké drby?}
{163}{}{Ahoj.}

{164}{}{ivot by byl krásnìjší, kdyby po svìtì nechodili takovı hovòousové jako ty.}
{165}{}{No jo, co naplat. Mám ještì otázeèku.}
{166}{}{Ha, ha, ha, ha! Dobrá. Uvidíme co v tobì vìzí... prde.}

{167}{}{Nìkdy za to zaplatíš, vole.}

{168}{}{Zmiz mi z oèí, hovnoroute.}

{169}{}{Opravdu na to nemáš, èlovìèe. Je to víc, ne si mùeš dovolit.}
{170}{}{Opravdu se k nám nedostaneš, pøíteli. Hodnì štìstí s nìkım jinım z Broken Hills.}
{171}{}{Dobrá práce. Tady máš svıch $200.}

{172}{}{Ztra se. Tvojí pomoc tady nepotøebujeme.}

{173}{}{Mìj své oèi radìji otevøené.}
{174}{}{Budu si tì hlídat.}
{175}{}{Nenechám se sebou zametat takovejma bastardama.}
