#tento soubor pøeložil Vachy - http://vachy.moje.cz
{100}{}{Vidíš špinavého, zarostlého a ospalého muže.}
{101}{}{XXX}
{102}{}{Vidíš špinavého a ospalého muže. Jeho šaty vypadají velice, ale opravdu VELICE staøe.}
{103}{}{::protírá si oèi:: Co... áááh? Kde to jsem? Jak dlouho jsem spal?}
{104}{}{Grrr?}
{105}{}{Kdo jsi?}
{106}{}{Nemám ponìtí, jak dlouho jsi spal, ale jsi v Broken Hills, nedaleko od New California Republic.}
{107}{}{Oh ne! Spal jsem pìknì dlouho a svìt se zatím zbláznil! Aieeeeeeee! ::zaèíná panikaøit::}
{108}{}{-dál-}
{109}{}{Jmenuju se Somnambulus. Pracoval jsem na pøekladu Falloutu 2 a abych si trochu odpoèinul, vyšel jsem si na procházku. Pøitom jsem náhodou objevil tuhle jeskyni a trochu jsem si tu zdøíml...}
{110}{}{To zní neuvìøitelnì. Skoro jako nìkterá z tìch starých kreslených grotesek.}
{111}{}{New co? CALIFORNIA? SVÌT SE ZMÌNIL TAK HODNÌ? AIEEEEEEEEEEEEEEEEE! :: zaèíná panikaøit::}
{112}{}{Hej poèkej chvíli...}
{113}{}{Jo to je fakt. Jdu se mrknout, co se stalo se svìtem. Hodnì štìstí, pøíteli!}
{114}{}{Vám také, pane Somnambule!}
{115}{}{Odkryl jsi další záhadu zmizelého svìta.}
{116}{}{Chrrrrrrrr.}
