#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš ustaraného èlovìka.}
{101}{}{Vidíš Dana, ustaraného manela.}
{102}{}{Vidíš dobøe obleèeného èlovìka, jeho oblièej jeví známky hysterie.}
{103}{}{Kdo jsi? Co dìláš v mém domì?}
{104}{}{He. Ty vogo?}
{105}{}{Jsem.}
{106}{}{Nikdo dùleitı.}
{107}{}{Klídek, jen tì chci okrást.}
{108}{}{Nic. Nikdo. Bye.}
{109}{}{Ne v mém domì prosím. Venku na ulici si chrápej a dìlej co chceš, jako všichni lidi "tvého" raení.}
{110}{}{Thppt!}
{111}{}{Dobøe, dobøe. Teší mì, e tì vidím. [Vypadá nervóznì.] Ty, poslyš, ty jsi dost dobrodrunı tıpek, co?}
{112}{}{Jo.}
{113}{}{Nepoznal jsi Vyvoleného?}
{114}{}{Ne.}
{115}{}{Co tady chceš?}
{116}{}{Ptám se proto, e mi nìkam zmizela moje ena. Nemùu ji najít. Odešla pøed nìkolika dny. Ptal jsem se u kdekoho a nikdo ji nevidìl. Pomùeš mi ji najít?}
{117}{}{Co je mnì potom?}
{118}{}{Mrknu se po ní. Jak vypadá?}
{119}{}{Ne. Mám moc práce.}
{120}{}{Dám ti 500 babek. To jsou mé ivotní úspory.}
{121}{}{To by šlo, podívám se ti po ni.}
{122}{}{Ne, fakt to nejde.}
{123}{}{Prosím, prosím ... má ena je pro mì vším.}
{124}{}{Seš hluchej? Øek sem e ne!}
{125}{}{Dobøe, dobøe, pøestaò kòuèet.}
{126}{}{Tady máš peníze. A teï prosím, PROSÍM... najdi mou enu a øekni mi, kde je. Moná ije s nìkım jinım, tøeba mì opustila .. ale musím to vìdìt.}
{127}{}{Dobrá, máš to mít. Jak vypadá?}
{128}{}{Rozumnı nápad, udìlám co budu moct.}
{129}{}{::na chvíli neovládl svùj pláè:: Tak jo, bì a zjisti mi to, co zlomí srdce.}
{130}{}{Uvidíme se pozdìji, nešastníku.}
{131}{}{Je to blondınka, docela sexy a má fantastickı hlas... Naposled jsem jí vidìl támhle. Nemá ráda mutanty a ghouly, take mezi nimi jí nehledej. Nikdo neví, kam šla. Prostì zmizela.}
{132}{}{Je toho dost.}
{133}{}{Tak co, u nìco víš? Srdce mì stále bolí.}
{134}{}{Ještì ne, pracuju na tom.}
{135}{}{Našel jsem ji.}
{136}{}{Zatím nic. Ale nevzdávám to.}
{137}{}{Sakra, moje srdce. Øekni mi, kde je.}
{138}{}{No jo, je to tak.}
{139}{}{Vlastnì, u v tom nemíním pokraèovat.}
{140}{}{Našli, moji rádcové, našli? ::oèi mu zasvítily:: Kde?}
{141}{}{Nevyšla si jen tak, nalehko? Bez nohou?}
{142}{}{V chodbách pod mìstem je mnoho mrtvıch tìl. Byla mezi nimi. Je mi líto.}
{143}{}{Ne, proboha. Má poøádné nohy.}
{144}{}{No, blbı. Teï nemá ádné nohy. Byla surovì napadena a je bez nohou. Je mrtvá a pøed smrtí si dost vytrpìla.}
{145}{}{Nue, byla v chodbách pod mìstem. Je bohuel mrtvá, je mi líto.}
{146}{}{Dekuji za pomoc. Myslím, e se pùjdu vybreèet.}
{147}{}{Tak bì, jelimane.}
{148}{}{Promiò, pøíteli.}
{149}{}{Nenávidím tì! Všichni tì nenávidí! ::vzlyká::}
{150}{}{Našel jsem dopis, u tvé eny. Vypadá to, e podílela na tajném plánu k vyvradìní mutantù v Broken Hills.}
{151}{}{To snad...! Já ..já ..nemùu tomu uvìøit [Hluboce vzdychá]. Myslím, e by to tak mohlo bıt. Nenávidìla všechny mutanty a ghouly, které vidìla. Èert ví proè.}
{152}{}{Jestli to tak bylo, pak bys mìl uváit, e to nemusí skonèit u tvé eny. Jestli do toho byla zapletená, proè ne i ty?}
{153}{}{Chceš tím snad øíct, e mùj ivot je také v nebezpeèí? A sakra. To mì nenapadlo. V noci jsem pøed domem slyšel nìjaké divné zvuky. Asi šeptání a kroky.}
{154}{}{Co takhle vzít nohy na ramena? Dej na sebe pozor. Hodnì štìstí.}
{155}{}{Díky za pomoc. U tady nezùstanu ani minutu.}
{156}{}{Dan byl informován o vradì své eny.}
{157}{}{.}
