#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš scvrklého starce v doktorském plášti. }
{101}{}{To je MUDr Holliday.}
{102}{}{Vidíš scvrklého mue v lehce zkrvaveném doktorském pláštíku. Je na nìm vidìt, e je to bedna. Ale nevypadá zdravì.}
{103}{}{::sípavım hlasem:: Vítám tì. Jsem doktor Mengele .. éé vlastnì Holliday. Co mi chceš?}
{104}{}{A co teda chceš?}
{105}{}{Ouchie!}
{106}{}{Jsem zranìn a potøebuji pomoc.}
{107}{}{Nìkdo z mıch kámošù je zranìn a potøebuje pomoc.}
{108}{}{Èímpak se zabıváš?}
{109}{}{Øekni mi nìco o tomto mìstì.}
{110}{}{Nìjaké drby?}
{111}{}{Prodej mi nìjaké stimpaky.}
{112}{}{Zapomeò na to. To nic.}
{113}{}{Podívám se ti na to, ale zadarmo to nebude, nemám smlouvu s VZP.}
{114}{}{No jo, tak kolik?}
{115}{}{Ale nic.}
{116}{}{No, to se dá léèit... ::sípavì:: za malı obnos.}
{117}{}{Tak kolik?}
{118}{}{Tak nic.}
{119}{}{Cím se zabıvám? Jsi v nemocnici, já mám doktorskı pláš a kolem je spousta krve. Taky jsou tu noe a jiné nástroje. Take jsem buï úspìšnı zabiják nebo slušnı doktor. Vyber si.}
{120}{}{Asi ti budu øíkat doktore.}
{121}{}{Nehraj si se mnou, staøíku.}
{122}{}{Opravdu dobrı doktor by se netopil v krvi.}
{123}{}{Podívej, pøed lety jsem se tady narodil. Zrovna se to zaèínalo rozjídìt. Kdy jsem byl ještì mladı, potloukal jsem se kolem a potkal jsem enu. Zamiloval jsem se. Jene onemocnìla a zemøela a já se rozhodl bıt doktorem.}
{124}{}{Jo? Pokraèuj.}
{125}{}{Mìl jsi mluvit o Broken Hill, ne o tvém mládí.}
{126}{}{Divil by ses, co umí lidi øíct, kdy jsou nemocní.}
{127}{}{Jo? A co jako?}
{128}{}{Rozmyslel jsem si to. Radši se zeptám na nìco jiného.}
{129}{}{Bude to za $50.}
{130}{}{No co mám s tebou dìlat.}
{131}{}{Ale nic.}
{132}{}{Tak tohle zranìní tì pøijde na $100.}
{133}{}{Co mi zbıvá, tady to máš.}
{134}{}{Tak to teda ne.}
{135}{}{To je ale pìkné zranìníèko, take to máme ... $150. A nedostaneš doklad!}
{136}{}{Tady to máš, vydøiduchu.}
{137}{}{Radši nic.}
{138}{}{Hmm, to bude fuška, dát tì dohromady. To bude za dobrıch $200.}
{139}{}{Tady to máš, ty vydìraèi.}
{140}{}{Radši chcípnu.}
{141}{}{No pøíteli, nachystej si prkenici... $300 babek a budeš jako novı.}
{142}{}{Ale jo, to beru.}
{143}{}{Nejsem Bill Gates, magore. To radši chcípnu.}
{144}{}{Bude se cítit jako znovuzrozenı... ::sípavì:: za smìšnıch $50.}
{145}{}{Máš to mít.}
{146}{}{To je moc.}
{147}{}{Byli jste snad na Global Street Party? Eh, taky jsem byl mladı a pár jich koupil. Bude to za $100.}
{148}{}{Lidová cena, beru to.}
{149}{}{Ani náhodou.}
{150}{}{Poslyš, ty jsi jejich chùva ? ::zakašlání:: Jestli jsou to tví komplicové, zapla mi $150.}
{151}{}{Máš je mít, kdy je v tom i DPH.}
{152}{}{To je moc.}
{153}{}{Musíš bıt fakt dobrı èlovìk, kdy jsou ti kámoši tak oddaní. Doufám e jo...protoe tì to pøijde na ::zakašlání:: $200.}
{154}{}{To je penìz ..tady to máš.}
{155}{}{Mor na tebe, nic ti nedám.}
{156}{}{Tìká vìc, jak øíkám, snad kdybych ...pouil své nejlepší znalosti z Chicago Hope, dalo by se za $300 nìco dìlat.}
{157}{}{Taková pálka, vydìraèi, ...ber.}
{158}{}{Hmm, to teda ne! A piš si e se o tom dozví lékaøská komora.}
{159}{}{Jsi švorc, nemáš dost penìz. Take jestli chceš, prodám ti nìjakı stimpaky, protoe s tím co máš, si moc vyskakovat nemùeš.}
{160}{}{Dej sem stimpaky.}
{161}{}{Ne, díky.}
{162}{}{Je mi potìšením..}
{163}{}{Díky.}
{164}{}{S tím nesouhlasím.}
{165}{}{A co tohle?}
{166}{}{To je vše, co mohu nabídnout. Bye.}
{167}{}{::sípavì:: Jsi zranìn?  Uka, podivám se na to. Máš nìjaké peníze?}
{168}{}{Penis-e?}
{169}{}{Dzjo!}
{170}{}{Uka mi svùj batoh. (hledá v batohu a nìco vytahuje)  Tak.
 Myslím, e teï ti to bude ubliovat daleko ménì.}
{171}{}{Ubliovat?}
{172}{}{Ehm, tak. Tady! Jsme hotovi. Hodnì štìstí a dávej na sebe pozor!}
{173}{}{Díky!}
{174}{}{Bingo, jsem doktor. Jsem rád, e jsou na svìtì v tomhle post-jaderném humusu inteligentní bytosti.}
{175}{}{Tak ty chceš ubliovat starému nebohému doktorovi?.}
{176}{}{Hele dìdku, stejnì si od tebe ádnı sraèky nevezmu}
{177}{}{Ummm.. Hmm. Chci se zeptat.}
{178}{}{Bye.}
{179}{}{Vyhroovat jedinému doktorovi ve mìstì, ...teda ::kašlaje:: Pøíteli, jestli mi nìco chceš,
 mluv se mnou slušnì. Jinak vypadni a táhni si tøeba ke všem èertùm.}
{180}{}{Sereš mì, doktùrku. Asi tì zruším, dìdulo.}
{181}{}{Jo. Cokoliv.}
{182}{}{Promiò, dnes je špatnı den.}
{183}{}{Byla to jen legrace.}
{184}{}{Máš se ještì hodnì co uèit, ohlednì slušného chování.}
{185}{}{Dítì, ještì se máš hodnì co uèit o humoru.}
{186}{}{Jo, v poøádku.}
{187}{}{Dobøe, teï's mì nasral. A uzdrav se jak chceš.}
{188}{}{(V jeho oèích jsou vidìt záblesky smíchu) Dnes u neuvidíš mnoho podobnıch míst jako za starıch dob...}
{189}{}{Hej!}
{190}{}{Starochu, moc do mì nerıpej.}
{191}{}{...jsou vìci, které znali naši pøedkové...}
{192}{}{Jo, jo... Tak já pùjdu.}
{193}{}{Klid, dítì, jen tak vtipkuji.}
{194}{}{Jo, no. Hmm ... já vím. No. }
{195}{}{... a které vám prostì neøekneme, vy malí bastardi! (bouølivı smích) Jo, a a mì pøíštì budeš
 potøebovat, tak zase zajdi.}
{196}{}{Mám pár otázek.}
{197}{}{Díky. Zaskoèím, a pùjdu nìkdy kolem.}
{198}{}{Jsi zranìn? Uka, ošetøím tì.}
{199}{}{Hmm...}
{200}{}{Díky. Zas nìkdy!}
{201}{}{Kdo je zranìn? Postavte se do øady a já se na vás podívám.}
{202}{}{Ještì nìco...}
{203}{}{Diky! Bye!}
{204}{}{Pøekvapivì málo. Promiò, ale kdy se soustøedím na nìèí léèbu, nevìnuji obvykle
 pozornost jeho nejintimnìjším tajemstvím.}
{205}{}{Mùeš mi zodpovìdìt další otázky?}
{206}{}{Pak jsem šel do San Francisca a studoval v Èínské ètvrti medicínu u mistra Funga,
 a ten mne nauèil všemu, co o medicínì vím. A nauèil mì i nìkterım tajnım umìním.}
{207}{}{A co se stalo pak?}
{208}{}{A jak to souvisí s Broken Hills?}
{209}{}{Poèkej, k tomu se dostanem! Vy mladí jste tak netrpìliví.}
{210}{}{Promiò. Pokraèuj.}
{211}{}{To staèí, odcházím.}
{212}{}{Potom jsem pøisel sem a sledoval Marcuse, jak z pár chatrèí budoval mìsto. Pamatuju si, jak se
 rodilo mìsto, které vidíš pøed sebou. Vidìl jsem, jak sem pøicházeli lide za vidinou bohatství, vidìl
 jsem, jak lidé dospívají i umírají. Znám celou historii mìsta.}
{213}{}{Aha, to znamená...}
{214}{}{To znamená, e mnoho novıch lidi u ani neznám. Mnoho z toho, co jsem vyprávìl, jsou u jen vzpomínky.}
{215}{}{Dìkuji za pøíbìh.}
{216}{}{Ty magore, chceš mi øíct, e mì tady zdruješ jen kvùli tomu?}
{217}{}{Ne. Díky, za vyslechnutí mıch blábolù. Pøíštì a budeš chtít vyléèit, pøijï ke mì.}
{218}{}{Dík! Tak zase nìkdy...}
{219}{}{Dík. Nashle!}
{220}{}{Tak jo. Snad to k nìèemu bylo.}
{221}{}{Ne, opravdu ne. Teï zas o nìèem jiném..}
{222}{}{Ne, ty starı seschlı šupáku. Èau.}
{300}{}{Kdo potøebuje uzdravit?}
{301}{}{Vic.}
{302}{}{Myron.}
{303}{}{Marcus.}
{304}{}{MacRae.}
{305}{}{Sulik.}
{306}{}{Lenny.}
{307}{}{Cyberdog.}
{308}{}{Doktor.}
{309}{}{Goris.}
{310}{}{Davin.}
{311}{}{Miria.}
{312}{}{Robobrain.}
{313}{}{Zapomeò na to.}
{314}{}{Jsi zranìn? Uka, mrknu se na to a na tvé kámoše taky.}
{315}{}{Tak jdem.}
{316}{}{[pokraèovat]}
{400}{}{rádlo pro psy.}
{401}{}{K9.}
