#tento soubor pøeložil Vachy - http://vachy.moje.cz
{100}{}{Vidíš znudìného maníka v kožených hadrech.}
{101}{}{Vidíš (x), strážce karavany.}
{102}{}{Vidíš zaprášeného znudìného maníka v kožených hadrech. Podle zápachu krav a dùvìrnì známé chùze
 je jasné, že je to strážce karavan.}
{103}{}{Mohu s nìèím pomoci?}
{104}{}{Urg?}
{105}{}{Pìkná práce!}
{106}{}{Co jsi zaè?}
{107}{}{Co kdybys mi povykládal o Chadovi?}
{108}{}{S idioty se nebavím. Sorry, ale musíš si najít nìkoho jiného.}
{109}{}{::škyt::}
{110}{}{Jsem (x), jeden ze strážcù karavan.}
{111}{}{Nevíš nìco o Chadovi?}
{112}{}{Dik. Èau.}
{113}{}{Chad je správný kolík. Drsòák, ale fér. Štìdrý ke všem, co dìlají dobøe svou práci. }
{114}{}{Kdo jsi?}
{115}{}{Dik. Èau.}
{116}{}{Diky. Ne, opravdu. Díky za zvýšení prémií. Chad stejnì obchoduje jen s lidmi, kterým ublížil. On nám pomohl a ty se v tom vrtáš. Blázne!}
{117}{}{Èau.}
{118}{}{Je to nepøítel! Chcípni!}
{119}{}{Oops.}
