#tento soubor pøeložil Vachy - http://vachy.moje.cz
{100}{}{Vidíš osobu v èerné zbroji z kùže, v rukou tøímá pìkný kanón a vypadající znaènì vztekle.}
{101}{}{Vidíš }
{102}{}{Vidíš zpoceného a zaprášeného strážce karavany. Øíkáš si, že obchodní cesty jsou dnes
 opravdu velmi nebezpeèné. }
{103}{}{Mohu pomoci?}
{104}{}{Cožeto!}
{105}{}{Mohu pomoci?}
{106}{}{Ano, hledám vùdce karavany.}
{107}{}{Byl bych velice rád, kdybych se mohl zeptat na Chada.}
{108}{}{Kdo jsi?}
{109}{}{Omlouvám se za Chada. Kdo je nový šef?}
{110}{}{Ne, díky.}
{111}{}{Jestli hledáš práci, mùžeš promluvit s Billem, uvnitø. Možná ti bude
 rozumìt. Hodnì štesti! }
{112}{}{Duhhhh...}
{113}{}{Snad jo }
{114}{}{Ano.}
{115}{}{Ne.}
{116}{}{Dostal jsi otázku, možná se doèkám odpovìdi. Chceš nìco vìdìt?}
{117}{}{Jak vypadá?}
{118}{}{Je dùvìryhodný?}
{119}{}{Kde dostane peníze?}
{120}{}{Co je to zaè?}
{121}{}{Tak nic, zase nìkdy.}
{122}{}{Já? Hmm.}
{123}{}{Je ti líto Chada? Ha! Slušný výdìlek, co øíkáš? Novým šéfem jsem já!}
{124}{}{Bye.}
{125}{}{V tom pøípadì, dej øeè s Billem, obchodníkem z Broken Hills. Mùže ti pomoct.}
{126}{}{Diky.}
{127}{}{Dobøe. Tak nashle.}
{128}{}{Jak vypadá? No, je pøátelský, ale drsòák. Je dobrý šéf a obvykle je k nám spravedlivý. 
 Nejedná s námi zle, jestli ti jde o tohle. Další otázky?}
{129}{}{Vždycky vím, co nám pøinese -- je toho spousty. To není to, na co se ptáš. Další otázky?}
{130}{}{Je trochu zvláštní, ale ... kdo dnes není. Další otázky?}
{131}{}{Nic o nìm nevím. Chci tím øíct, že my strážci sem pøicházíme odkudkoliv a hledáme
 tady práci. Pøedstav si, že musel pøenechat místo nìkomu jinému. Další otázky?}
{132}{}{Protože já jsem nový šéf, jsem asi jediný, kdo k tobì necítí nenávist. Co pro Tebe
 mùžu udìlat?}
{133}{}{Hledám práci.}
{134}{}{Ztratil jsi vedení?}
{135}{}{Kdy odjíždí další karavana?}
{136}{}{Nic, diky.}
{137}{}{Zeptej se Billa.}
{138}{}{Fajn.}
{139}{}{Potom, co se stalo Chadovi? Nemyslím. Ještì nìco?}
{140}{}{Jsme tady, tu mas svých $500. Kdyby ses chtìl vrátit, odjíždíme na sklonku dne.  Mùžeš dostat
 peníze i na zpáteèní cestu, když budeš chtít. Tak èi tak, my odjíždíme.}
{141}{}{Zase nìkdy.}
{142}{}{Mùžeme vyrazit?}
{143}{}{Dík. Tady máš $500. Na další job se zeptej Billa.}
{144}{}{Nemáš dobrý den, chcípni!}
{145}{}{Umm...}
{150}{}{strážce karavany.}
{151}{}{Jsem stražce Billových karavan. Ještì nìco?}
{152}{}{.}
{153}{}{Nìkde tady musí být, hledáš práci?}
{154}{}{Hodnì štìstí v práci.}
{200}{}{Chad}
{201}{}{Hatch}
{202}{}{Stark}
{203}{}{Darin}
{204}{}{Michael}
{205}{}{Harry}
{206}{}{Jake}
{207}{}{Matt}
{208}{}{Ted}
{209}{}{Clay}
{210}{}{Scott}
{211}{}{Prentiss}
{212}{}{Eddie}
{213}{}{John}
{214}{}{Max}
{301}{}{Tawni}
{302}{}{Kim}
{303}{}{Urs}
{304}{}{Susan}
{305}{}{Cindy}
{306}{}{Jen}
{307}{}{Lisa}
{308}{}{Buffy}
{309}{}{Heather}
{310}{}{Cathy}
{311}{}{Lori}
{312}{}{Mary}
{313}{}{Julie}
{314}{}{Sarah}
