#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš upoceného zamaštìného mue.}
{101}{}{Vidíš Erica.}
{102}{}{Vidíš upoceného zamaštìného mue. Vypadá fakt bídnì.}
{103}{}{Tohle mìsto u nepotøebuje vìtší smùlu. Stejnì jako já.}
{104}{}{Tak u vejdi. A zavøi za sebou dveøe, a sem nevletí mouchy.}
{105}{}{Vyschne? F-f-f!}
{106}{}{Dobøe dobøe, není potøeba køièet.}
{107}{}{Køièíš snad na mì?}
{108}{}{Pustím dovnitø všechny smradlavı mouchy, protoe chci. Magore.}
{109}{}{Dobøe, tak zas nìkdy.}
{110}{}{Zavøi dveøe prosím! Vypadni a všechny ty mouchy si vem s sebou!}
{111}{}{Hjo!}
{112}{}{Sorry, jsem trochu nervózní. Všechny ty hnusné mouchy a klimatizace nefunguje. Kdybych mìl jen o trochu víc proudu, zamával bych s nima, ale nemám, no.}
{113}{}{Kdo jsi?}
{114}{}{Jak mùeš získat energii?}
{115}{}{Proè je tady tolik much?}
{116}{}{Chtìlo by to obèas zajít do koupelny.}
{117}{}{Hodnì štìstí, pøíteli. Ahoj.}
{118}{}{Hmm, dost špatné. Èau.}
{119}{}{Pøívod energie do mìsta øídí rozvodná stanice s generátorem. Hele, co takhle tam zajít a získat povolení k vìtšímu odbìru energie pro mou klimatizaci? Byl bych ti velmi zavázán.}
{120}{}{Jak zavázán? Hotovost, nebo vıbava?}
{121}{}{Jo, zkusím to pro tebe.}
{122}{}{Nemám èas, moná nìkdy pozdìji.}
{123}{}{Jsi blázen? Není to moné. Snad kdyby Ti bylo na umøení. Co bys neudìlal pro lepší svìt.}
{124}{}{Lítají sem proto, e jim chutná mùj pot. Celé moje tìlo je pro nì pochoutka a to pocení to ještì zhoršuje.}
{125}{}{To je pìknı hnus. Proè se neumyješ, nebo tak nìco?}
{126}{}{Hmm, pak ho teda zlepším tím, e Tì zabiju.}
{127}{}{Diky, to je víc, ne potøebuju vìdìt. Nashle.}
{128}{}{Zkusil jsem to. Zkusil jsem všechno. Jediná vìc, která mi od much pomáhá, je nebıt zpocenı... Jene kdy nemám energii pro klimatizaci, tak to nejde.}
{129}{}{Hmm. Chci se ještì zeptat.}
{130}{}{Hmm. Nashle.}
{131}{}{Ano?}
{132}{}{Mluvil jsem s Brianem a ten mi øekl, e odbìr energie je tak na hranici. O nìjakém zvyšování nemùe bıt ani øeè.}
{133}{}{Odkud jsou ty mouchy?}
{134}{}{Zkusil ses vykoupat?}
{135}{}{Kde je ta rozvodna?}
{136}{}{Kdo jsi?}
{137}{}{Je tady mnohem lépe? Co?}
{138}{}{Ale nic, to jen tak.}
{139}{}{Mohl bych pro Tebe vyškrábnout nìjaké zbytky, kdy jsi to udìlal. Nemùu slíbit moc, ale mìlo by to staèit, na zlepšení nálady.}
{140}{}{Mùeš si vybrat. Kdy Ti dám energii, musíš pro mne nìco udìlat.}
{141}{}{Udìlám to pro Tebe zadarmo, jen tak.}
{142}{}{Ne, zapomeò na to. Nechci to udìlat.}
{143}{}{Musím si to rozmyslet.}
{144}{}{Ani nemùu øíct, jakou mám radost. Dej mi prosím okamitì vìdìt, a budu moct zapnout klimatizaci a vykoupat se.}
{145}{}{Udìlám, ale mám pár otázek.}
{146}{}{Udìlám, nashle.}
{147}{}{Moc s tím prosím neotálej, protoe ty mouchy mì fakt štvou.}
{148}{}{Dobøe, chtìl bych se ještì zeptat.}
{149}{}{Dobøe, dám Ti vìdìt.}
{150}{}{Díky moc za slitování. Mimochodem, je to sarkastické, e nejsi informován. Jdi k èertu z mého domu.}
{151}{}{Proè nejdeš k èertu a nechcípneš?}
{152}{}{Tak se mìj, chlapèe!}
{153}{}{Rozvodná stanice s generátorem je po levé ruce, kdy pøicházíš do Broken Hills. Øídí to tam Brian, línı zkurvysyn, kterı se fláká jak mùe.}
{154}{}{Vypadá to na pìknou práci. Dík, ještì mám nìjaké otázky.}
{155}{}{Hmm, to prozatím všechno.}
{156}{}{Jsem Eric. Mám tady ve mìstì hotel, ale prodávám ho kvùli problému s mouchama. Taky jsem mìl hospodu, ale to bylo to samé. Nakonec jsem provozoval generátor, ale mouchy se tam taky dostaly.}
{157}{}{Pìkná kopa práce, ...mám pár otázek.}
{158}{}{Hm, tak nashle.}
{159}{}{Øekl to, e jo? No, tak mu øekni e palivem generátoru je uran a to minimum potøebné energie nepùjde vùbec poznat. A øekni mu, e trvám na svém!}
{160}{}{Jo, fajn proslov.}
{161}{}{Vyøídím mu to, ale mám ještì pár otázek.}
{162}{}{Dobøe, tak já jdu.}
{163}{}{Tak hotovo, s generátorem? Fakt moc díky, ani nevím, jak podìkovat.}
{164}{}{Obvyklá cesta vyjádøení díkù vede pøes penìenku, nebo mi nìco dej do vıbavy.}
{165}{}{Ne, to ne. Staèí mi tvoje díky.}
{166}{}{Mutant Francis má Energo Pìst. Pomùe ti v kontaktním souboji. Ten problém je vìtší ne jeho. Kdybys mìl zájem, mùu ti dát pár pilulek, které tì trochu zvıhodní.}
{167}{}{Dobrá vìc.}
{168}{}{Radši bych prachy, pokud mono.}
{169}{}{Nechci odmìnu.}
{170}{}{Pilulím se øíká Buffout. Hodnì tì posílí, ale za cenu oslabení mysli. Neber toho moc, jinak chytíš závislost. Hodnì štìstí!}
{171}{}{Dík. Nashle.}
{172}{}{Myslíš, e mi mùeš pomoci s mouchama? To by bylo fajn.}
{173}{}{Já vdìènı?}
{174}{}{Dobøe.}
{175}{}{Chci si to rozmyslet.}
{176}{}{Neznám cestu.}
{177}{}{Tady máš, všechny prachy... $150. Dík.}
{178}{}{Ne, dìkuji. Sbohem.}
{179}{}{Tisíceré díky. Hm, slyšel jsem, e hledáš GECK. Zkus se zeptat v NCR, je to na jinì odsud.}
{180}{}{Díky, nashle!}
{181}{}{Ano, mouchy mizí, mám tady pøíjemnì, u se nepotím. Je mi fajn!}
{182}{}{U jsem øekl, všechno je fajn, nashle!}
{183}{}{Vidíš zpoceného umaštìného chlápka. Vypadá docela slušnì.}
