#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš enskou.}
{101}{}{Je místní.}
{102}{}{Vidíš enskou z mìsta. Její ohoz nevypadá nejlíp, ale vypadá hrdì.}

{147}{}{To fakt nikde není bezpeèno?}
{148}{}{Odkdy je zlodìjina bìnım povoláním?}
{149}{}{Pøemıšlím silnì o zmìnì místa, nevypadá to tady moc bezpeènì.}
{150}{}{Slyšela jsem, e Franc a Manson nenávidí mutantíky.}
{151}{}{Tìší mì, e vypadli... Divím se, kde jsou teï.}
{152}{}{Franc a Manson jsou zmetci. Toto mìsto nebude jako døív, dokud nebudou chyceni.}
{153}{}{Kdo zabil ty stráné? Jak nehumánní...}
{154}{}{Nemùu uvìøit, e toto mìsto je tak mírumilovné.}

{155}{}{Jak si pøedstavuješ, e pøesvìdèíš stráe, aby ty dva bastardy pustili?}
{156}{}{Dík es pomohl Frankovi a Mansonovi. U by pro nás nemìli pøedstavovat hrozbu.}
{157}{}{Kde jsou Frank a Manson teï? Doufám, e u jsou zpátky ve vìzení.}
{158}{}{Nìkteøí z mıch nejlepších pøátel jsou mutanti a ghoulové...}
{159}{}{Chtìla bych mít nìjaké árovky.}
{160}{}{Co to tak smrdí?}
{161}{}{Mám strach, e nás z NCR zkusí zase vochcat.}
{162}{}{Myslím si, e New Reno by mohlo bıt pìkné místo k ivotu?}
{163}{}{Nemám nic proti mutantùm, ale kdy oni vypadají tak legraènì.}

{164}{}{Øekla bych ti "pìkná práce," ale fakt si mì nasral.}
{165}{}{Jacob a Aileen nesnášeli mutanty, heh? A to byli docela pøíjemní.}
{166}{}{Ale no tak... Aileen?}
{167}{}{Nemùu uvìøit, e by mezilidmutantské vztahy byli tak nahnuté.}
{168}{}{Marcus musí bıt na lidi docela nasranej.}
{169}{}{Všichni lidé by teï udìlali líp, kdyby si dali na chvíli voraz.}
{170}{}{Slyšela jsem, e se teï mutanti pøipravují na odvetu proti lidem!}
{171}{}{A co si o tom asi myslí ghoulové?}

{172}{}{Dùl...je znièen... naše domovy budou zatraceny.}
{173}{}{Jsme ztraceni.}
{174}{}{To je konec Broken Hills.}
{175}{}{Pøichystám se na cestu do NCR.}
{176}{}{Kdo by mohl takovou vìc?}
{177}{}{Mùj boe, ...dùl.}
{178}{}{Je na svìtì nìjaká spravedlnost?}
{179}{}{Asi si to pùjdu hodit, bez dolu jsme v kıblu.}
{180}{}{Mmm, no jo, ivot je jako ebøík do kurníku, krátkı a posranı.}

{181}{}{Ou, neznám nikoho silnìjšího, kdo by porazil Francise.}
{182}{}{Oh, seš tak silnı!}
{183}{}{Hmm, seš fakt tvrïák, co?}
{184}{}{Nìkdy si pøipadám jak kouzelnı míè. Obèas pronesu nìjakou vìtièku a zmizím.}
{185}{}{Zápasil jsi nìkdy s deathclawem?}
{186}{}{Jsi stejnì tak chytrı jako silnı?}

{187}{}{Francis v poslední dobì vypadal docela šastnì.}
{188}{}{Fransis byl nìjakı klidnı. Vy spolu nìco máte?}
{189}{}{Hej ty, kámo!}
{190}{}{Ještì poøád jdeš za svım cílem?}
{191}{}{Nevydìsil Tì Francis?}
{192}{}{Trochu se motáš.}
{193}{}{Jak mùeš bıt tak blbej, prát se kvùli tomu s Francisem?}
{194}{}{Doufám, e ses pobavil víc ne Francis.}

{195}{}{Špatní lidé.}
{196}{}{Kdo spustil Jakobùv ebøík?}
{197}{}{Co to zase plácám.}

{198}{}{Dobøe, e jsi ve mìstì.}
{199}{}{Zùstaneš tady na chvíli?}
{200}{}{Snad se Ti tady líbí!}
{201}{}{To byla skvìle odvedená práce, nechceš bıt šerifem?}
{202}{}{V poslední dobì je ve mìstì líp.}
{203}{}{Vypadá to, e se vìci koneènì daly do pohybu.}

{204}{}{Zmiz ode mì, slize.}
{205}{}{Neuznávám tvùj názor.}
{206}{}{Kdo tì pustil dovnitø?}
{207}{}{Nevím, proè Tì nechtìjí pustit z mìsta.}
{208}{}{Prosím, nech mì bıt.}
{209}{}{Neotravuj.}
{210}{}{Nemùu Ti pomoct, odejdi.}
{211}{}{Chcípni v poušti, smrade.}
{212}{}{Odejdi.}

{213}{}{Pomoc!}
{214}{}{Je tady!}
{215}{}{Aaaaaaaaaaaaah!}
{216}{}{Zrádce!}
{217}{}{Slize!}
{218}{}{Nechej mì!}
{219}{}{Ne! Ne! Ne!}
{220}{}{Nedotıkej se mì!}
{221}{}{Neubliuj mi!}

{250}{}{Tihle chudí lidé.}
{251}{}{Kdo spustil Jakobùv ebøík?}
{252}{}{Podívej, co zpùsobila pouš.}
{253}{}{Mám mezi ghouly a mutanty velmi dobré pøátele...}
{254}{}{Potøebuji víc svìtla.}
{255}{}{Co je to za smrad?}
{256}{}{Obávám se, e nás NCR mùe pohltit.}
{257}{}{Co myslíš, je New Reno dobré místo k ití?}
{258}{}{Nemám nic proti mutantùm, kdy oni jsou ale tak smìšní.}
{259}{}{ivot je pes. Philùv "Rot gut" ne.}
{260}{}{Tomu zkurvysynovi se nedá vìøit.}
{261}{}{Mùj dech smrdí jako koèièí rádlo.}
