#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš dobøe stavìného mutanta. Asi se nudí.}
{101}{}{Vidíš Francise, mutanta-zápasníka.}
{102}{}{Vidíš dobøe stavìného mutanta. Má èernı koenı ohoz a v jeho tváøi je vidìt jak moc se nudí.}
{103}{}{Chceš s nìèím pomoct?}
{104}{}{Ook! Ook! Eep orp ook!}
{105}{}{Kto e si?}
{106}{}{Hej, kámo. Kdo jsi?}
{107}{}{Kdo jsi a co tady dìláš?}
{108}{}{Pøipraven na zápas, elezná tykvo?}
{109}{}{Pøíteli, netuším, co to meleš. Sorry.}
{110}{}{Jsem Francis. Jsem mistr zápasník tohoto mìsta. Vsadil jsem se,
 e mì nikdo neporazí.}
{111}{}{Jsem Francis, pamatuješ? Mistr-zápasník tohoto mìsta. Vsadil jsem se, e mì nikdo neporazí.}
{112}{}{Dostanu Tì! Há! Há!}
{113}{}{Dostanu Tì jako ostatní.}
{114}{}{Dostanu koho chci.}
{115}{}{Dobrı, ne?}
{116}{}{Co se tady dá dìlat? No tak, podívej... máme tady hospodu, dùl, rafinerii, a tábor
 obchodníkù. Na zábavu moc èasu teda není, ale co si nenecháme vzít, je chlastání.
 A taky pracujeme na vztazích mezi lidmi a mutanty.}
{117}{}{Jak... skvìlé.}
{118}{}{Dík, v pohodì.}
{119}{}{Vztahy lidí a mutantù? Co tím myslíš?}
{120}{}{Jsem vdy pøipraven... a Ty?}
{121}{}{Ne, jenom se ptám na zdraví.}
{122}{}{Umm, ne.}
{123}{}{Jasnì e jo.}
{124}{}{[mìøí si Tì pohledem a zkoumá Tvé svaly] Myslím e ne, pøíteli. Jenom marníš mùj èas. Odprejskni.}
{125}{}{Myslíš si, e mì pøemùeš? Dobøe. Vyhraješ-li, tak ti dám Energo pìst. Vyhraju já, budeš mi celou noc slouit. Chceš se do toho pustit, nebo potøebuješ nabrat síly?}
{126}{}{Odpoèinek! Time out!}
{127}{}{ádné štráchy, jdem na to!}
{128}{}{Chci si trochu odpoèinout.}
{129}{}{Rozdáme si to hned.}
{130}{}{Rozmyslel jsem si to, nechám tì na pokoji.}
{131}{}{To je pravda. Vypadá to, e není nikdo na této bohem opuštìné zemi, kdo by se toho odváil.}
{132}{}{Škoda. Podívám se po nìkom, a pošlu ho sem. Zdar.}
{133}{}{To, e jsi silnı, neznamená, e jsi taky chytrı. Pamatuj na to.}
{134}{}{Brácho, kdy se ti tady nelíbí, mùeš jít nìkam jinam.}
{135}{}{Bez problému. Cokoliv budeš potøebovat, zeptej se obchodníka Phila nebo nìkoho jiného.}
{136}{}{Brácho, tak chceš zápasit nebo ne? Nemíním ztrácet èas s posmìváèky a provokatéry nebo zbabìlci.}
{137}{}{Tak jo, pojïme na to.}
{138}{}{Ne, myslím e ne.}
{139}{}{A budeš pøipraven, vra se sem. Budu nìkde poblí.}
{140}{}{Vypadni døív, ne mi hrkne v bednì a rozbiju ti drku.}
{141}{}{Vzdát to? Zbabìlec. To teda ne.}
{142}{}{Dobøe dobøe, tak teda jo.}
{143}{}{Jo, cokoliv, èau.}
{144}{}{Dobøe pøíteli, To je poprvé, co mì nìkdo porazil v øádném souboji. Vyhrál jsi, ber.
 Hotovo.}
{145}{}{Prohrál jsi. Nic nového, jdeš se mnou domù.}
{146}{}{Øíkal jsem ti, barde, ještì nikdy jsem nepotkal nìkoho tak dobrého. Vyuij svou sílu v prospìch dobra, uij si tu rukavici!}
{147}{}{Nemáš dost? Chceš ještì? Co vsadíš?}
{148}{}{Jo, jdeme na to.}
{149}{}{Nee, sorry.}

{150}{}{Slyšel jsem o Tobì. Se šmejdama se nepaktuju.}
{151}{}{Brácho, díky e's zavítal do našeho mìsta a zachránil ho. Koupím Ti drink.}
{152}{}{Howdy, hrdino!}
{153}{}{Šmejde! Chcípni!}
{154}{}{Mùete si povšimnout, e v našem mìstì spolu ijí lidé i cikáni, ehm... mutanti. ijeme tady spolu v míru.
 No, jenome vdycky se najde nìkdo, kdo se pokouší nás proti sobì poštvat. Náš šéf Marcus byl spoluzakladatelem mìsta. ...Chceš vìdìt ještì víc?}
{155}{}{Jasnì, pokraèuj.}
{156}{}{Ne, nemám zájem.}
{157}{}{Tak na rovinu, vy mutanti jste šmejdi a lidi co s váma spolupracují jsou zrádci.}
{158}{}{Nìkdy mám tady o ty lidi starosti... pro nìkteré je velice tìké pøekonat strach. Z nìkterıch øeèí je cítit, e je tady prùser na spadnutí, ale mùe to bıt blbost.}
{159}{}{Dík. Ahoj.}
{160}{}{Dobøe. A se budeš chtít zas nìco dozvìdìt, víš kde mì najdeš.}
{161}{}{Tak jo, dík a ahoj.}
{162}{}{Opravdu? Opravdu úchvatnı názor na vìc. Škoda e jsme nerozdrtili vaši vesnici, kdy jsme rozhodovali o této zemi. Zmizni mi z oèí, èerve.}
{200}{}{-konec-}
{201}{}{Nashle.}
{202}{}{Dík. Ahoj.}
{203}{}{-dále-}
{204}{}{Fajn. Dík a èau.}
{300}{}{Kámo, nejsem si jistı, jestli jsi schopen správnì vyuít moji nabídku. Vra se, a budeš mít více 
 zkušeností.}
{301}{}{Vidíš silného mutanta. Je obleèenı do mundùru z èerné kùe a v ksichtì má fest znudìnı vıraz. Vypadá to, e se s nìjakou rukavicí prohrabává v báglu.}
{302}{}{Všechno tì bolí. Po setkání s Francisem vypadáš jak reklama na mlátièku.}
{400}{}{Urrggghh!}
{401}{}{Arrrrr!}
{402}{}{Aiiigggggg.}
{403}{}{Rnnrnrnrnnrrr.}
{404}{}{Hagggahhhaaaggga.}
{405}{}{Hominahominahomina.}
{406}{}{Eeeeeccchhhh.}
{407}{}{Chrocht!}
{408}{}{Do øiti!}
{409}{}{Ouvej!}
{410}{}{Oh! Moje ruce !}
{411}{}{Ha ha! Mám tì, dostal jsem tì!}
{500}{}{Vyhrál jsem Francisi, vyhrál!}
{501}{}{Chlapèe, tomu øíkám správnı náøez! Hahahah!}
{502}{}{Hmmm, mohl bys vstoupit do naší armády!}
{503}{}{Dostal jsem Tì. Zbyteènì mrháš silami, kdy chceš porazit Francise!}
{504}{}{Ouch! Natáhl jsem si šlachu, ale furt lepší ne drátem do oka!}
{505}{}{Hej, Francisi! Potøeboval bys vìtší triceps do ramena, abys mìl dost síly.}
{506}{}{Tehle souboj je fakt na pìsti! Hahaha!}
{507}{}{Máš v øiti klíèní kost Francisi!}
{508}{}{Uh oh... Radši bych se mìl dret mimo dosah tvıch pìstí! Ha ha ha!}
{509}{}{Podívej na ty bicepsy!}
{510}{}{Mám dojem, e jsem slyšel rupnout šlachu...}
{511}{}{Jednoduchá úvaha nám øíká, e Francis bude favoritem.}
{512}{}{Francis! Fran-CIS! FRAN-CIS!}
{513}{}{Zpráskej ho, Francisi!}
{530}{}{Dobøe Francisi!}
{531}{}{Dìlej Francisi!}
{532}{}{Ou! Ještì nikdy se mi to nestalo!}
{599}{}{V tunelu jsem našel nìjakou poznámku se jmény Francis and Vachy. Asi to nìjak souvisí se tìma špinavostma.}
{600}{}{Ser na to. Vachy si zas vymıšlí, co? Fajn, èlovìèe, øeknu Ti toto: Vìdìl jsem, e v tomto mìstì ijí lidé, kteøí chtìjí zabíjet mutanty, a taky vím, e je Marcus zavøel za katr a mìl dùkazy. Chtìl jsem to zvládnou a zabránit tomu s co nejmenšími obìtmi.}
{601}{}{Take jsi zabil nevinné, co?}
{602}{}{Hmm. Tak co teda navrhuješ?}
{603}{}{Nevinné? Ha! Ty lidi se mì pokusili zabít! Jenom jsem se bránil
  a jejich smrt bude vıstrahou pro ostatní... k udrení smíru.}
{604}{}{Jene s tìmito zpùsoby nejsi nic jiného, ne obyèejnı vrah, a Tvá slova mì pøipadnou jako spiknutí.}
{605}{}{K míru vede jedinì cesta spravedlnosti a všichni vrahové musí bıt potrestáni.
 Ujmu se èásti odpovìdnosti a zabiju tì.}
{606}{}{Pokud jsi s nìkım z mìsta mluvil o nenávisti k cikánùm... vlastnì mutantùm,
 nemùeš mluvit o spiknutí. Já vím, dvì chyby jsem udìlal, ale byla to sebeobrana. Nìco jsem udìlal špatnì, pøipouštím. Nemùu tady zùstat. Musím najít cestu, jak odèinit své konání... Uspokojí to tvé cítìní pro spravedlnost?}
{607}{}{Ano.}
{608}{}{Ne. Zabiju tì.}
{700}{}{Porazil jsi Francise v pìstním souboji.}
{701}{}{Vyslechni Francise ohlednì Vachyho poznámky.}
{800}{}{(S pohledem na obrovského mutanta ti koneènì došlo, e nemáš
 vùbec ádnou šanci. Je èas zmizet, dokud je èas.)}
