#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš špinavého a rozzlobeného chlapa.}
{101}{}{Vidíš Franka, kterı nenávidí mutanty}
{102}{}{Vidíš špinavého a rozzlobeného chlapa, kterej vypadá, e by nejradìji kadımu vpálil kulku mezi oèi. Jeho chùze pøipomíná králièí skoky.}
{103}{}{Co cheš?}
{104}{}{Aggggg! ::slintá::}
{105}{}{Ty! Já! Poï na to!}
{106}{}{Kdo seš?}
{107}{}{Co dìláš v base?}
{108}{}{Co mi povíš o tomhle místì?}
{109}{}{Co mi povíš o Marcusovi?}
{110}{}{Vùbec nemám ponìtí, vo èem to plácáš, srabe. Jdi mi z voèí.}
{111}{}{Oooooh...}
{112}{}{Sem Frank. Kdo k èertu seš ty, vobejdo.}
{113}{}{A helemese tvrïák, eh?}
{114}{}{To je v poøádku. Z tebe se neposeru.}
{115}{}{No jo, co dìlat. Mìj se.}

{116}{}{Sem tady, protoe velkej šéf mi nevìøí a nemá rád kecy, kterı roznáším po mìstì. Øíkám lidem pravdu o mutantech a to Marcus nemá rád.
 Pro pravdu musí bıt èlovìk umlèen.}
{117}{}{To zní drsnì.}
{118}{}{Nebo moná je to pro to, e seš drbna, která zkouší pomlouvat lidi z mìsta, kterı nenávidí?}
{119}{}{Jo, to je zajímavı. Co mi mùeš øíct o Broken Hills?}
{120}{}{Jistì. Co víš o Marcusovi?}
{121}{}{No jo. Èau.}

{122}{}{Tohle místo má prej bejt "ráj". Kdy sem ty mutantskı sráèi pøídou a zaènou tady makat. No a teï sme všichni v prdeli, máme se tváøit e jsme zapomìli na minulost a ít s nima v míru. JÁ ale ne! ivot bez nich nebo smrt!}
{123}{}{No není to co hledám, ale stejnì dík. Víš nìjakı drby o Marcusovi?}
{124}{}{Umm, No dobøe. Uvidíme se pozdìji.}

{125}{}{Marcus všem vykládá, e pomohl objevit mìsto, ale to není pravda. První tu byli lidé a von s tou svojí zavšivenou bandou sem pøitáhli a zaèali plácat nìco vo tom, e chtìj s náma ít. To von je principál celıho tohohle cirkusu.}
{126}{}{Myslím, e seš fakt blázen.}
{127}{}{Zasranı mutanti. A ijou drsòáci.}

{128}{}{Jasnì, sem drsòák. Kdybych nebyl ve vìzení, vyzkoušel bych tì. Myslíš, e seš taky drsnej?
 Seš pøipravenej na zkoušku, srabe?}
{129}{}{Jistì.}
{130}{}{Nemám zájem o tvoje poslintanı kecy, vyli mi.}

{131}{}{Táhni k èertu, ty degenerovanej poíraèi šnekù! A dostanu šanci, seš mrtvej!}
{132}{}{Zbohem, òoumo.}

{133}{}{Tenhlecten systém je zaloen na lásce k mutantùm. Nenávidíš je?}
{134}{}{Jo.}
{135}{}{Ne.}

{136}{}{Urèitì? Tak bì za chemikem Jacobem. Uvidíme se pozdìji.}

{137}{}{Ty milovníku mutantù! Vypaø se vodsaï! Nebudu dıchat stejnej vzduch jako ty!}

{138}{}{Zase ty? Co zas chceš?}
{139}{}{Øekni mi o Broken Hills?}
{140}{}{Øekni mi o Marcusovi.}
{141}{}{Proè si ve vìzení?}

{142}{}{Mluvils s Jacobem? Tak na co èekáš? Zmizíme odsud!}

{143}{}{Dík es mì otamtud dostal. Škoda, e kdy jsme zdrhali, tak sme nikoho nezabili.}

{144}{}{Hurá! Zabít ty zrùdy, to byla ta nejlepší vìc pod sluncem!}

{145}{}{Jen nastavim tu vıbušninu a pak si dáme pauzu, máš kitekat?}

{146}{}{Dobrá práce paráku. Zmizíme z mìsta. Seš fakt bourák, tak se mìj!}

{147}{}{Teï u tì mám fakt dost! Pøiprav se na smr, sráèi!}

{148}{}{Zmizíme vodsaï.}

{149}{}{No nic. Èau.}
{150}{}{Tak jo. Mìj se.}

{151}{}{Tohle je dungle bez práva. Mìl by ses stydìt.}

{152}{}{Dobrá práce kámo. Zajdi za Jacobem a Aileen.}

{153}{}{Úspìšnì otevíráš vìzení.}

{154}{}{Dík za pomoc v naší vìci, cizinèe.}
{155}{}{ádnı problém.}

