#tento soubor pøeložil Vachy - http://vachy.moje.cz
{100}{}{Vidíš zvláštní vìc, se zajebákovanou kùží a pøíšerným úsmìvem.}
{101}{}{Vidíš mìstského ghoula.}
{102}{}{Vidíš ghoula. Vidíš ghoula, jeho kùže vypadá stažená z nìjakého zvíøete. Taky to vypadá, že ho ostatní lidé jakž takž akceptují.}
{103}{}{Práce na rafinérii je tìžká.}
{104}{}{Mutanti a lidé se pøed nedávnem ještì nesnášeli.}
{105}{}{Nerad dìlám v blízkosti kyseliny.}
{106}{}{Zdá se, že se tohle mìsto zaèíná plnit.}
{107}{}{Všichni lidé nejsou špatní.}
{108}{}{Vítej v Broken Hills.}
{109}{}{Kam šel Hank? Nevidìl jste ho nìkdo?}
{110}{}{Museli jsme tvrdì pracovat, aby Broken Hills vypadalo tak, jak vypadá.}
{111}{}{Kdy bude další bufet, sakra?}

{112}{}{Chad je zavøenej? To už se lidi navzájem takhle zahanbujou?}
{113}{}{Né, všichni mají Chada rádi.}
{114}{}{O Chadovi de moc nevykecávej, chlapèe.}
{115}{}{Jednou bych se chtìl pøidat ke karavanì...}
{116}{}{Kde je Hank? Nevidìl jste Hanka?}
{117}{}{Museli jsme tvrdì pracovat, aby Broken Hills tak jak vypadá.}
{118}{}{Kdy bude další jídlo?}
{119}{}{Nepotøebuješ vìdìt jaký je poèasí, abys poznal jakým smìrem vítr vane.}
{120}{}{Pøestaò! Hej... co je to za zvuk?}

{121}{}{Pryè s tyrany!}
{122}{}{Jak si mohl zabít Chada?}
{123}{}{Cožeto, Chad byl násilnì dopraven do vìzení nebo co?}
{124}{}{Vidím temné dny v Broken Hills.}
{125}{}{Chad dostal co mu patøí.}
{126}{}{Nechme potrestat kriminalitu.}
{127}{}{Chudák Chad. Ještì že nemá rodinu.}
{128}{}{Lidi na Chada serou.}
{129}{}{Mutanti to mìli zvážit... lidi se možná budou chtít za Chada pomstít.}

{130}{}{Kdo by chtìl dìlat takhle odporné vìci?}
{131}{}{Když budou mutanti pryè, tak se banditùm sami neubráníme.}
{132}{}{Marcus... Vachy... Francis... všichni jsou pryè... ale jdi...}
{133}{}{Budoucnost je pøíšerná.}
{134}{}{Byli to lidi, co to udìlali? Byl to Cameron?}
{135}{}{Kdo nás teï povede, když je Marcus pryè?}
{136}{}{Kde se teï schováme?}

{137}{}{Tyhle hajzlové z NCR. Udìlali by líp, kdyby sem už nelezli. Teda pokud nechtìj dostat pøes fròák.}
{138}{}{Byl bych pøekvapen, kdyby za tím nebyli NAŠI lidé...}
{139}{}{Díky za záchranu mutantù.}
{140}{}{Mìli bychom vyprášit kožich tìm, kteøí se pokusili otrávit naše mutanty.}
{141}{}{Hodnì se toho stalo... docela mi to zamotalo hlavu...}
{142}{}{Asi bychom se mìli vrátit k práci.}

{143}{}{Kdo pomohl tìm dvoum praseèím rypákùm ven? Zabil stráže, ccc... Marcus musí pìknì øádit.}
{144}{}{Ve mìstì se dìje nìjaká neplecha.}
{145}{}{Øíkal jsi, že to tady zaèíná docela smrdìt?}
{146}{}{Myslel jsem si, že to bude klidné místo na "stará kolena". Vypadá to, že jsem se mýlil.}
{147}{}{Kdo k ïasu zatáhl to násilí do Broken Hills?}
{148}{}{Frank a Manson... nìkdo hraje píseò smrti pro všechny mutanty.}

{149}{}{Kdo mohl ty dva pustit z vìzení?}
{150}{}{Musíš se cítit docela zahanbený.}
{151}{}{Myslím, že máš pravdu, že Frank a Manson nepøedstavují hrozbu... ale mutanti tì za to obviní.}
{152}{}{Frank a Manson... zpátky ... do prdele. Možná opustím mìsto.}
{153}{}{Ve mìstì nastanou krvavé èasy.}
{154}{}{Øíkal jsi, že to tady zaèíná docela smrdìt?}

{155}{}{Udìláme líp, když to všechno pøedáme právu!}
{156}{}{Vždycky jsem tvrdil, že je Jacob trochu divnej.}
{157}{}{To nauèí lidi, že se nemaj ohánìt zákonem.}
{158}{}{Ale no tak... Aileen? Nevìøím, že by to udìlala.}
{159}{}{Takové pohádky o lidech! Musí se cítit docela zahanbeni. Docela hodnì.}
{160}{}{Bude Broken Hills vùbec pøipraveno srovnat pranice mezi lidmi a mutanty.}
{161}{}{Ty svinì, Jacob a Aileen, mì vždy mìli za podøadného obèana. Tohle je nauèí.}

{162}{}{Nemyslím si, že by se Broken Hills nikdy nevzpamatovalo ze ztráty dolu...}
{163}{}{Všichni mutanti ... jsou... mrtví...}
{164}{}{... teï už se nikdy nedozvíme, jestli by to klapalo mezi mutanty a lidmi...}
{165}{}{Je èas zmizet a zjistit co nabízí okolní svìt... jakou hodnotu má kopání mimo dùl.}
{166}{}{Byl by zázrak, kdyby nìkde v Kalifornii potøebovali horníky?}
{167}{}{Asi se teï vrátím do Gecko...}

{168}{}{Ty hnijící èerve.}
{169}{}{Ty neznáš hanbu, slušné vychování?}
{170}{}{Proè si chtìl znièit naše mìsto?}
{171}{}{To's nevìdìl, že když se znièí dùl, znièí nás to všechny?}
{172}{}{Nechci se s tebou bavit.}
{173}{}{Jdi pryè.}

{174}{}{Dobrá práce.}
{175}{}{To je špatné, že ti lidé zemøeli pod mìstem.}
{176}{}{Jsem pøekvapen, jak dokázali vykopat tunely potají.}
{177}{}{Teï víme, kam zmizeli Frank a Manson.}
{178}{}{Ti ubozí lidé. Jejich chudé rodiny.}

{180}{}{Neubližuj mi.}
{181}{}{Nech mì být.}
{182}{}{Ne! Ne! Ne!}
{183}{}{Už pùjdu.}
{184}{}{Vypadni z našeho mìsta!}