#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš shrbeného mue obleèeného v laboratorním plášti.}
{101}{}{To je chemik Jacob.}
{102}{}{ Vidíš shrbeného mue obleèeného v laboratorním plášti. Ruce má obarvené a popálené od chemikálií.}

{103}{}{Vítej. Jsem Jacob, chemik z laboratoøe. Co pro tebe mùu udìlat?}
{104}{}{Co chceš?}
{105}{}{Ále, ahoj! Copak potøebuješ tentokrát?}
{106}{}{Vítej zpìt. Co si pøeješ?}
{107}{}{Da yagga! Eep oop op!}
{108}{}{Rabolatoøe? Dlaboøatoøe?}
{109}{}{Mám nìjakou rudu, co potøebuji rafinovat a nechci platit ceny v rafinérii.}
{110}{}{Copak mi povíš o Broken Hills?}
{111}{}{Chci si nìco namíchat.}
{112}{}{Chci s tebou mluvit o jisté vìci tıkající se mutantù.}
{113}{}{Ahoj.}

{114}{}{::Podívá se s odporem na tebe:: Zmiz odsud, nemám na tebe èas.}
{115}{}{-dále-}

{116}{}{Laboratoø. Tohle je laboratoø. Podívej, chceš nìco?}
{117}{}{Zase ty? Chceš nìco?}
{118}{}{Ano!}
{119}{}{Nene.}

{120}{}{Dobrá. Podíváme se co chceš.}
{121}{}{-dále-}

{122}{}{Potom zmiz.}
{123}{}{-dále-}

{124}{}{Tady. Dík za tip. Teï zmiz.}
{125}{}{Jasòaèka!}

{148}{}{Proè mi radìji nejprve nepovíš, co cítíš k mutantùm?}
{149}{}{Nenávidím je.}
{150}{}{Nevím jistì.}
{151}{}{Jsou úasní!}

{152}{}{V tom pøípadì ti to øeknu popravdì.}
{153}{}{Èlovìk, co se jmenoval Jacob - Mám jméno po nìm - našel tohle místo. Ten mutant Marcus pøišel chvíli po nìm a zaèal kadému nutit svoje zákony.}

{154}{}{To staèí, seš blázen. Sbohem.}
{155}{}{Povìz mi víc.}

{156}{}{Moná, kdy ti øeknu pravdu, zmìníš názor.}
{157}{}{Dobrá. Povídej.}
{158}{}{No, ani mì to nìjak nezajímá.}

{159}{}{V tom pøípadì, je tu skvìlı ivot. Tohle mìsto má vše, co si mùeš pøát... mutantskıho šerifa, uranovı dùl, nemocnoci, skladištì... dostaneš tu vše. Ještì nìco?}
{160}{}{Jo.}
{161}{}{Ne.}

{162}{}{Dobrá. Sbohem.}
{163}{}{Nashle.}

{164}{}{Kdy byl Vùdce znièen, zaèal tady rozkazovat. Kadıho, kdo s ním nesouhlasí stáhne dolù... nebo prostì "zmizí." Pokud se na to díváš jako cizinec, tak tohle mìsto vypadá civilizovanì. Ale pravda je taková, e to je útoèištì pro krvelaèné mutanty. Jsou tady pøátelé mıch pøátel, kteøí zmizeli, sotva promluvili.}
{165}{}{Nelblázni..}
{166}{}{To staèí, seš kripl. Zdar.}

{167}{}{Všichni pøedstíráme, e je tu klid a civilizace... ale ijeme ve strachu pøed mutantskım terorem. Kadım dnem je nás míò a míò.}
{168}{}{Vdy všichni mutanti tady vypadají staøe a sešle.}
{169}{}{Proè nebojujete?}

{170}{}{To protoe se tì snaí oklamat pøíteli. Dìlají si z tebe blázny.}
{171}{}{Proè proti nim teda nebojujete?}
{172}{}{Pìknì krmíš, co? Uvidíme. Dobrá, musím jít.}

{173}{}{Samozøejmì, e to zkoušíme. Já a mí pøátelé v dolech plánujeme útok za úèelem vyèištìní mìsta od mutantù, ale potøebujeme k tomu pár pøátel z vìzení. Seš s náma?}
{174}{}{Ne.}
{175}{}{Ne. A nelíbí se mi to. Jste blázni.}
{176}{}{Jistì!}

{177}{}{Urèitì? Tohle je šance vymanit se z vlády tìchhle krvelaènejch sráèù.}
{178}{}{Poøád mi to nic neøíka.}
{179}{}{No dobrá. Pøesvìdèil jsi mì. }

{180}{}{Potom je to na tobì, bì. Škoda, tvrïáku.}
{181}{}{Ano. Sbohem.}

{182}{}{Ty ..eh.. myslím e nejseš zrádce.}
{183}{}{Co?}

{184}{}{Mám pro tebe prácièku. Naši pøátelé, Manson a Frank, jsou zavøeni v base. Musíš je dostat ven. Pokud to pùjde, udìlej to tiše. Nechtìj mít v patách celı mìsto.}
{185}{}{Co kdy nìkoho zabiju?}
{186}{}{Jasnì. Mám ještì otázku.}
{187}{}{Zapomeò na to, to se mi nelíbí.}
{188}{}{To zmáknu, uvidíme se.}

{189}{}{Bez problému. Jsou tam jen samı mutanti. Ale hlavnì to udìlej tiše.}
{190}{}{Tak jo. Ještì se chci zeptat...}
{191}{}{Jdu na to...}

{192}{}{Máš otázky?}
{193}{}{Mám nìjakou rudu, co bych chtìl rafinovat a nechci platit ceny v rafinérii.}
{194}{}{Co mi ještì povíš o Broken Hills?}
{195}{}{Chtìl bych si nìco namíchat.}
{196}{}{Nic. Ahoj.}

{222}{}{Asi to máš v palici pomíchanı ty mutantomile. Jak si to mohl udìlat Chadovi? Seš ostuda lidstva.}
{223}{}{Ahoj.}

{224}{}{Dobrá práce s tím vìzením!}
{225}{}{Dík.}

{226}{}{Opravdu jsi všechny pobil? Teï budeme mít víc starostí. No nevadí.}
{227}{}{Promiò.}

{228}{}{No, jsou venku. Byl to dùleitı úkol. Samozøejmì, e teï kadı ve mìstì ví o tvém spojenectví s Mansonem a Frankem. No, budi.}
{229}{}{Promiò.}

{230}{}{Teï si myslím, e u se ti dá vìøit. Co takhle - další malá prácièka?}
{231}{}{Co pro tebe ještì mohu udìlat, kámo?}
{232}{}{Další práce? Jako co?}
{233}{}{Potøebuju si vyrafinovat nìjakou rudu.}
{234}{}{Ne teï ne, potøebuju nìjaké chemikálie.}
{235}{}{Dík, nemám èas, mìj se.}

{258}{}{Je to takhle: Nenávidíme mutanty.. chceme je zabít.. nejlepší cesta, jak to udìlat je vyhodit dùl do povìtøí, kdy budou vevnitø. Tím si upevníme pozice.}
{259}{}{Udìlám to!}
{260}{}{Ne, to nemùu.}

{261}{}{Skvìlé, pøíteli! Tady. Vezmi si ten vıbušnı spínaè. Zavìs ho na èistiè vzduchu a zmiz otamtud co nejdøív. Spustíme to, jakmile budou mutanti v dole.}
{262}{}{Jen mi dej vìdìt, kdy budete pøipraveni.}
{263}{}{Jdu na to.}
{264}{}{To nejde.}

{265}{}{Proè ne? Bojíš se nebo co? Udìláš to nebo ne?}
{266}{}{Ano.}
{267}{}{Ne, øíkám NE.}

{268}{}{Asi ti nerozumím. Ale doufám, e ty mì jo, kdy ti øeknu: zmiz mi z oèí ty kolaborante.}
{269}{}{-dále-}

{270}{}{Jdeš do toho s námi?}
{272}{}{Ano. Jdu na to.}
{273}{}{Mìním názor, tohle fakt nechci.}

{274}{}{Dobrá. Na tohle jsme dlouho èekali, vem si tenhle vıbušnı spínaè a dej ho na èistiè vzduchu. Bude to mohutná exploze. Uvidíme se potom!}
{275}{}{Tak jo! SMRT mutantùm!}
{276}{}{Radìji to pøece jen neudìlám.}

{277}{}{Jsi pìknı ZRÁDCE.}

{278}{}{Odvedl's dobrou práci. Škoda, e ses obrátil proti nám.}

{279}{}{Koneènì jsme se vymanili z nadvlády mutantù. Opravdu ti moc dìkujeme. Je tu malé skladištì zbraní pod Lizinım obchodem. Vem si dole, co uznáš za vhodné.}

{280}{}{Opouštíme mìsto. Tobì doporuèuju to samé.}

{281}{}{Pojï, pokecáme proè jsem tady.}

{282}{}{Tvoje ruda je èistá. Tady máš.}
{283}{}{Dík!}

{284}{}{Ještì to nemám. Dej mi chvíli.}
{285}{}{Mám tedy ještì otázku.}
{286}{}{V pohodì. Èau.}

{287}{}{Jsi pøipraven na zábavu?}
{288}{}{Chceš zkusit znovu nìjakou kratochvíli?}
{289}{}{Máš to. Chceš mi pomoct s rozptılením?}

{290}{}{Chci koupit nìjakou... uh... medicínu.}
{291}{}{Nìco jiného?}
{292}{}{Ano.}
{293}{}{Ne, dìkuji. Sbohem.}

{294}{}{Teï vidíš, jak jsou mutanti zrádní. Škoda, es neprohlédl døíve.}

{295}{}{Kdy pomùeš nám, pomùeme my tobì.}
{296}{}{Co tady postáváš a chytáš lelky. Musíme zachránit ještì pár vlastencù!}
{297}{}{Oh.. To je pravda.}

{298}{}{Øíkal jsem ti: "Dostaò je z vìzení" a né abys je zabil. Co se to s tebou k èertu dìje?}
{299}{}{Omlouvám se... Já jen...}

{300}{}{A u tím míníš cokoli, tvoje neschopnost zhatila všechny naše plány. Teï je èas platit.}

{301}{}{Sorry, pøíteli, ale... ztratil jsem své dva nejlepší kamarády. Ty hroznı mutanti je zabili ve vìzení.}
{302}{}{Urrggg. Mooooc špatnééé. Sbohem.}
{303}{}{Uh... Upøímnou soustrast. Sbohem.}
{304}{}{No a?}

{305}{}{No a? Øíkáš 'No a?' Je ti to úplnì putna, e jo?}
{306}{}{Byla to nehoda, pøísahám!}
{307}{}{Ale ne. Jenom nešlo nic dìlat! Zasranı mutanti!}

{308}{}{Leda moje prdel to byla, ádná nehoda! Tady máš ty teplej mutantofile!}

{309}{}{Tak, dobrá... jejich dny pøijdou.}

{310}{}{U jsem ti øekl všechno co vím, tak co chceš ještì vìdìt?}
{311}{}{Mám ještì pár otázek...}
{312}{}{Nic. Zapomeò na to.}

{313}{}{Dík.}
{314}{}{[pokraèovat]}

{315}{}{Hele kámo. Oceòuji tvou pomoc mım pøátelùm. Vdy na tebe budu vzpomínat v dobrém.}
{316}{}{Dík.}
