#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš mraèící se enu.}
{101}{}{To je Liz, majitelka obchodu.}
{102}{}{Vidíš enu støedních let, které se mraèení vepsalo do tváøe. Vypadá jako jeden z tìch lidí, co mají ze ivota perverzní potìšení.}

{103}{}{Ahoj. Jsem Liz. Co by sis pøál?}
{104}{}{Co teï?}
{105}{}{Nggg! Nnnnnng!}
{106}{}{Já chtít záááásoby!}
{107}{}{Chci nakoupit pár vìcí.}
{108}{}{Co mi povíš o tomhle mìstì?}
{109}{}{Chci zkrátit èas zabíjením. Šlo by to tu nìkde?}
{110}{}{Tak co je s tìmi zbranìmi v suterénu?}
{111}{}{Prı máš nìjaké pøebyteèné zbranì. Nìjaké by se mi hodily.}
{112}{}{Nic.}

{113}{}{O boe... další postiené mutanátko. Kdypak koneènì nìkdo postøílí tyhle vìci?}
{114}{}{Škyt.}

{115}{}{Mluv jasnì a srozumitelnì a uvidíme co pro tebe budu moci udìlat.}
{116}{}{Já! Potøebovat! Zásoby!}
{117}{}{Naskledanou!}#schválnì 

{118}{}{Chceš nìco koupit?}
{119}{}{Jasnì!}
{120}{}{Ne ne ne.}

{121}{}{V poøádku co chceš?}
{122}{}{Obchod.}

{123}{}{Nezapomeò na pravidelnou údrbu.}
{124}{}{Dekújú!}#schválnì

{125}{}{Chceš nìco koupit? V pohodì, mám asi tohle.}
{126}{}{Ještì jednu vìc...}
{127}{}{Dík. Navidìnou.}

{128}{}{Jsme malé tìební mìsto, ale ještì nejsme poøádnì rozvinutí. Chceš-li prohlídku mìsta s prùvodcem, promluv se Stevem nebo s nìkım.}
{129}{}{A helemese mrzutka. Ještì se chci zeptat.}
{130}{}{Nashledanou.}

{131}{}{Kohopak máš na mysli tím zabíjením?}
{132}{}{Radškorpióny, krysy, atd...}
{133}{}{Oh, sem tam nìjakıho humanoida.}
{134}{}{Co tøeba tebe... Štìtko.}
{135}{}{Špatòáky.}
{136}{}{To byl fór, zapomeò na to.}

{137}{}{Kdopak ti o tom øekl?? O tom jsem v ivotì neslyšela!}
{138}{}{Nezmatkuj, vím to od Jacoba.}
{139}{}{Ale no tak, vdy to ví všichni ve mìstì.}
{140}{}{Neboj se, mám to z bezpeèného zdroje.}

{141}{}{Co tøebas zkusit jeskynì v okolí domkù? Myslím, e tam jsou nìjaké pøíšery.}
{142}{}{Dìkuji ti, na vidìnou.}

{143}{}{Humanoidy, eh? A jaké máš na mysli?}
{144}{}{Lidi.}
{145}{}{Ghouly.}
{146}{}{Mutanty.}
{147}{}{Jenom ertuji.}

{148}{}{Jaká je tvoje definice špatòáka?}
{149}{}{Kadı, kdo se mi nelíbí. Tøeba, humanoidi.}
{150}{}{Kadı, kdo mi stojí v cestì.}
{151}{}{To je moje vlastní definice.}

{152}{}{Tak, ty to máš ze spolehlivého zdroje? A chceš ukonèit nadvládu mutantù ve mìstì?}
{153}{}{Ale jistì.}
{154}{}{Ne.}

{155}{}{Tak to bych si asi mìla vybavit celı svùj ivot.}
{156}{}{-dál-}

{157}{}{V tomhle obchodì se zabíjet nebude, zmiz.}
{158}{}{No co se dá dìlat. Kurvo.}

{159}{}{Ghoulové jsou dobøí otroci. Jsou hloupí, s lidmi jsou v pohodì a neznají cenu vradìní. Zabíjení ghoulù nebudu podporovat.}
{160}{}{Dobrá. Mùu ještì nìco?}
{161}{}{Co dìlat. Nashle.}

{162}{}{Jestli se opravdu zajímáš o vybíjení mutantù, tak to by sis mìl promluvit s chemikem Jacobem.}
{163}{}{Jacobem, eh? Tak jo.}

{164}{}{Tak na to zapomeò, teï zmiz.}
{165}{}{Jistì.}

{166}{}{V tom pøípadì se podívej do mého tajného skladištì zbraní, je to támhle pod podlahou.}
{167}{}{Dìkuji.}

{168}{}{Ráda se zbavím všech zbraní, které tady vidíš. Potøebuješ ještì s nìèím pomoci?}
{169}{}{Ano.}
{170}{}{Ne.}

{171}{}{S tebou nebudu obchodovat, ztra se.}
{172}{}{-dál-}

{173}{}{Krám je zavøenı. Otvíráme a v 8:00.}
{174}{}{Hele! Vypadni odtamtud!}
{175}{}{To je to, na co si se ptal!}
{178}{}{To je mi jedno, jestli to máš tøeba od Boha! Jen se musím pøesvìdèit.}
{179}{}{Hej! Nelez tam!}
{180}{}{U ti no nebudu opakovat. Nesna se tam dostat!}
{181}{}{Tak u se vypaø!}
{182}{}{Máš ještì nìco jiného, s èím mne chceš otravovat?}

{183}{}{Dík.}
{184}{}{[pokraèovat]}

{185}{}{haló! Kdo tam k èertu je?}
{186}{}{Nevím kdo jsi, ale jdu si pro tebe.}
