#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš mue, èlena rodu homo sapiens.}
{101}{}{To je místní obèan.}
{102}{}{Vidíš domorodce. Je špinavı, ale umí se nosit.}

{131}{}{Všichni mutanti... mrtví... Tomu nevìøím.}
{132}{}{Kdo mohl spáchat takovou vìc?}
{133}{}{Odkud se vzal ten jed?}
{134}{}{Jestlie jsou mutanti mrtví, budeme potøebovat ochranu NCR.}
{135}{}{Pomstu všem kdo za to mùou.}
{136}{}{Koho teï mùeme na oplátku zabít?}
{137}{}{Doufám, e mají v NCR vojsko! Kdo jinı nás teï ochrání?}
{138}{}{U se nemusíme bát ádnıch mutantskıch protiopatøení...}
{139}{}{Chudák Marcus... kdo nás teï povede?}

{147}{}{Nikde není bezpeèno?}
{148}{}{Kdy tu koneènì bude klid na denním poøádku?}
{149}{}{Pøemıšlím o tom, e se pøestìhuji... u tu není bezpeèno.}
{150}{}{Slyšel jsem, e Frank a Manson opravdu nenávidí mutanty.}
{151}{}{Jsem skuteènì rád e oba vypadli... Rád bych vìdìl, kde jsou teï.}
{152}{}{Frank a Manson jsou jed. V tomhle mìstì nebude klid, dokud je znovu nechytí.}
{153}{}{Kdo mohl zabít ty stráe, to je nelidské.}
{154}{}{Nemùu uvìøit tomu, e tohle mìsto bylo nìkdy mírumilovné.}

{155}{}{Jak si pøedstavuješ, e pøesvìdèíš stráe, aby ty dva bastardy pustili?}
{156}{}{Dík es pomohl Frankovi a Mansonovi. U by pro nás nemìli pøedstavovat hrozbu.}
{157}{}{Kde jsou Frank a Manson teï? Doufám, e u jsou zpátky ve vìzení.}
{158}{}{Nìkteøí z mıch nejlepších pøátel jsou mutanti a ghoulové...}
{159}{}{Chtìl bych mít nìjaké árovky.}
{160}{}{Co to tak smrdí?}
{161}{}{Mám strach, e nás z NCR zkusí zase vochcat.}
{162}{}{Myslím si, e New Reno by mohlo bıt pìkné místo k ivotu?}
{163}{}{Nemám nic proti mutantùm, ale kdy oni vypadají tak legraène.}

{164}{}{Øekl bych ti "pìkná práce," ale fakt si mì nasral.}
{165}{}{Jacob a Aileen nesnášeli mutanty, heh? A to byli docela pøíjemní.}
{166}{}{Ale no tak... Aileen?}
{167}{}{Nemùu uvìøit, e by mezilidmutantské vztahy byli tak nahnuté.}
{168}{}{Marcus musí bıt na lidi docela nasranej.}
{169}{}{Všichni lidé by teï udìlali líp, kdyby si dali na chvíli voraz.}
{170}{}{Slyšel jsem, e se teï mutanti pøipravují na odvetu proti lidem!}
{171}{}{A co si o tom asi myslí ghoulové?}

{172}{}{Dùl...je znièen... naše domovy budou zatraceny.}
{173}{}{Jsme ztraceni.}
{174}{}{To je konec Broken Hills.}
{175}{}{Pøichystám se na cestu do NCR.}
{176}{}{Kdo by mohl, takovou vìc?}
{177}{}{Mùj boe, ...dùl.}
{178}{}{Je na svìtì nìjaká spravedlnost?}
{179}{}{Asi si to pùjdu hodit, bez dolu jsme v kıblu.}
{180}{}{Mmm, no jo, ivot je jako ebøík do kurníku, krátkı a posranı.}

{181}{}{Ou, neznám nikoho silnìjšího, kdo by porazil Francise.}
{182}{}{Oh, seš tak silnı!}
{183}{}{Hmm, seš fakt tvrïák, co?}
{184}{}{Nìkdy si pøipadám jak kouzelnı míè. Obèas pronesu nìjakou vìtièku a zmizím.}
{185}{}{Zápasil jsi nìkdy s deathclawem?}
{186}{}{Jsi stejnì tak chytrı, jako silnı?}

{187}{}{Francis v poslední dobì vypadal docela šastnì.}
{188}{}{Fransis byl nìjakı klidnı. Vy spolu nìco máte?}
{189}{}{Hej Ty, kámo!}
{190}{}{Ještì poøád jdeš za svım cílem?}
{191}{}{Nevydìsil Tì Francis?}
{192}{}{Trochu se motáš.}
{193}{}{Jak mùeš bıt tak blbej, prát se kvùli tomu s Francisem?}
{194}{}{Doufám, e ses pobavil víc ne Francis.}

{198}{}{Dobøe e jsi ve mìstì.}
{199}{}{Zùstaneš tady na chvíli?}
{200}{}{Snad se Ti tady líbí!}
{201}{}{To byla skvìle odvedená práce, nechceš bıt šerifem?}
{202}{}{V poslední dobì je ve mìstì líp.}
{203}{}{Vypadá to, e se vìci koneènì daly do pohybu.}

{204}{}{Zmiz ode mì, slize.}
{205}{}{Neuznávám tvùj názor.}
{206}{}{Kdo tì pustil dovnitø?}
{207}{}{Nevím, proè Tì nechtìjí pustit z mìsta.}
{208}{}{Prosím, nech mì bıt.}
{209}{}{Neotravuj.}
{210}{}{Nemùu Ti pomoct, odejdi.}
{211}{}{Chcípni v poušti, smrade.}
{212}{}{Odejdi.}

{213}{}{Pomoc!}
{214}{}{Je tady!}
{215}{}{Aaaaaaaaaaaaah!}
{216}{}{Zrádce!}
{217}{}{Slize!}
{218}{}{Nechej mì!}
{219}{}{Ne! Ne! Ne!}
{220}{}{Nedotıkej se mì!}
{221}{}{Neubliuj mi!}

{250}{}{Tihle chudí lidé.}
{251}{}{Kdo spustil Jakobùv ebøík?}
{252}{}{Podívej, co zpùsobila pouš.}
{253}{}{Mám mezi ghouly a mutanty velmi dobré pøátele...}
{254}{}{Potøebuji víc svìtla.}
{255}{}{Co je to za smrad?}
{256}{}{Obávám se, e nás NCR mùe pohltit.}
{257}{}{Co myslíš, je New Reno dobré místo k ití?}
{258}{}{Nemám nic proti mutantùm, kdy oni jsou ale tak smìšní.}
{259}{}{ivot je pes. Philùv "Rot gut" ne.}
{260}{}{Tomu zkurvysynovi se nedá vìøit.}
{261}{}{Mùj dech smrdí jako koèièí rádlo.}
