#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš mohutného starého mutanta.}
{101}{}{Vidíš Marcuse, šerifa z Broken Hills.}
{102}{}{Vidíš mohutného starého mutanta s vyèerpanım vırazem ve tváøi. Ale i pøes to vypadá stále silnì a tvrdì.}

# node 1
{103}{mcs1a}{A hele, co to k èertu je? Tak tenhle oblek z tøináctky u jsem nevidìl hodnì, hodnì dlouho. Uka.}
{104}{mcs1b}{Copak si pøeješ, èlovíèku?}
{105}{mcs1c}{A nìjaká jiná pøání?}
{106}{}{Brrrr.}
{107}{}{Kdo jsi?}
{108}{}{Jakı je pøíbìh tohoto místa?}
{109}{}{Proè na mnì mutanti vlastnì neútoèí?}
{110}{}{Máš nìjaké novinky?}
{111}{}{Nìco dùleitého ti chci øíct.}
{112}{}{Nechtìl bys se mnou cestovat?}
{113}{}{Tak na vidìnou.}

{114}{mcs3}{Jistì, jsem velkı zlı mutant. Taky tady na to dávám pozor. Nìco se ti snad nelíbí?}
{115}{}{Nenaparuj se.}
{116}{}{Dnes ne!}

{117}{mcs4}{Chceš rozbít ciferník?}
{118}{}{Nedìlej ramena.}
{119}{}{Urèitì ne!}

{120}{mcs5}{Pøiprav se na pìknou nakládaèku, èlovíèku.}

{121}{mcs6a}{Dobøe.}
{122}{mcs6b}{Nestrkej svùj nos do problémù a nedostaneš pøes nìj.}
{123}{}{Urèitì?}

{124}{mcs7}{Jsem Marcus. Pomáhal jsem to tady vlastníma rukama stavìt. A teï tu dìlám šerifa.}
{125}{}{Ty jsi to tady pomohl postavit? To u musí bıt hodnì dávno...}
{126}{}{To sou kecy. Jak dlouho bys tady asi vydrel?}
{127}{}{Zatím èau.}

{128}{mcs8}{To je dlouhı pøíbìh. Chceš slyšet celou nebo zkrácenou verzi?}
{129}{}{Zajímala by mì ta krátká.}
{130}{}{Nu co, teï zrovna není co dìlat, tak povídej.}
{131}{}{Ani jedno. Mùu se tì ještì na nìco zeptat?}
{132}{}{Ani jedno. Zatím...}

{133}{mcs9}{Dobøe. Já a èlovìk zvanı Jacob jsme postavili tohle místo kolem támhleté staré banky pøed takovımi 60 lety. Kadı je zde vítán a mùe zùstat tak dlouho, jak jen chce, ale nesmí dìlat ádné potíe.}
{134}{}{Skvìlé. Mùu se ještì zeptat?}
{135}{}{To mi staèí. Mìj se.}

{136}{mcs10}{Dobrá...Po znièení Vùdce a Nádrí jsem se poflakoval po svìtì. Nebylo kam jít. Jednoho dne mì napadl blázen v Energo zbroji.}
{137}{}{Vánì?}

{138}{mcs11}{Byl to Jacob, z Bratrstva. Sloil pøísahu, e znièí všechny mutanty. Asi tak den, moná dva, jsme se snaili navzájem dostat. A potom jsme se tomu najednou zaèali smát. Chceš znát pointu?}
{139}{}{Povídej?}

{140}{mcs12}{Stali se z nás pøátelé. Zaèali jsme spolu cestovat a postupnì se k nám pøidávali další lidé. Dostali pocit, e s mutantem a rytíøem jsou v bezpeèí. V bezpeèí byli, to ano, ale nebyli šastní. }
{141}{}{Tak jste se usadili tady. Proèpak?}

{142}{mcs13}{Uranovı dùl. Jeden z té spousty na mapách. A teï je zde kadı vítán tak dlouho, dokud se chová slušnì. Ostatní mìsta si o nás myslí své, ale nikdo nemá tolik volnosti co mi. A tak to je.}
{143}{}{Moment... ty znáš nìkoho z Bratrstva?}
{144}{}{Coe, to u jsi potom nikdy nezabíjel lidi?}
{145}{}{Tak díky. Zatím pùjdu. Mìj se.}

{146}{mcs14}{Oh, z jakıpak díry si to vylezl? Mutanti u pìknì dlouhou dobu ijí v míru.}
{147}{}{Jsem z vesnice, kterou zaloil Zakladatel.}
{148}{}{Z vesnice na severozápadì.}
{149}{}{Promiò, moje chyba. Kadopádnì moc dìkuji, na vidìnou.}

{150}{mcs15a}{Novinky... jaképak novinky...}
{151}{mcs15b}{Dobøe, mám trochu strach o jednoho maníka od karavan, Chada. Mohl by bıt v nìèem zapletenı. Mùeš ho provìøit?}
{152}{}{A co z toho bude?}
{153}{}{Tak jo. Udìlám to.}
{154}{}{Mám teï moc práce.}
{155}{}{Nemáš nìco jiného?}

{156}{mcs16}{Mé vìèné díky. Staèí?}
{157}{}{To mi nestaèí.}
{158}{}{To né, nìco jiného bys nemìl?}
{159}{}{A co ještì nìjaké otázky, ne si to rozmyslím?}
{160}{}{Popøemıšlím o tom. Ahoj.}

{161}{mcs17}{Coe to je pro tebe málo? Vypaø se odsud, ne mi sele prst na spoušti.}
{162}{}{No jo, u jdu.}

{163}{mcs18}{Máme tady menší problém s dolem, jestli nám s tím chceš pomoct, zajdi za dùlmistrem Vachym.}
{164}{}{Kdepak ho najdu?}
{165}{}{A nemìl bys pro mì nìco jiného?}
{166}{}{Mám ještì otázky.}
{167}{}{Moná pozdìji. Mìj se.}

{168}{mcs19}{Na 100% v dolech, obèas taky bejvá v salonu.}
{169}{}{Nìco jiného?}
{170}{}{Mùu se tì ještì na nìco zeptat?}
{171}{}{Sbohem.}

{172}{mcs20}{Nìjakım záhadnım zpùsobem utekli z basy v bance dva vìzni. Najdi je, øekni mi kde jsou a já je dokopu zpátky.}
{173}{}{Co ještì máš?}
{174}{}{Mám otázeèku.}
{175}{}{Zatím ahoj.}

{176}{mcs21}{Co pøesnì chceš? Dobrá. Pár lidí zmizelo. Nemám ponìtí co s nimi je, najdi je a dostaneš $500.}
{177}{}{Udìlám to zadarmo.}
{178}{}{$500? To zní dobøe.}
{179}{}{Nemám èas.}
{180}{}{Ještì mám nìjaké otázky.}
{181}{}{Tak èau a zase pøíštì....}

{182}{mcs22}{Vıbornì. Dej mi vìdìt, hned jak nìco najdeš, dobrá?}
{183}{}{Jistì. Mùu se ještì zeptat.}
{184}{}{Provedu. Uvidíme se.}

{185}{mcs23}{Ano? Copak?}
{186}{}{Chtìls, abych našel nìjaké lidi. Našel jsem nìjaké tunely pod mìstem, mohli by tam bıt.}
{187}{}{Koneènì jsem našel ty lidi. Jsou v tunelech pod mìstem.}
{188}{}{Ohlednì tìch dvou uprchlíkù... Jsou spolèeni s Jacobem a Aileen. Schovávají se u Jacoba.}
{189}{}{Jacob a Aileen se mì ptali, jestli nemùu ty dva vysvobodit z vìzení. Myslím, e mají plán, jak to provést.}
{190}{}{Jacob a Aileen chtìli, abych vyhodil dùl do vzduchu, asi bys to mìl vìdìt.}
{191}{}{Jeden vìdec z NCR chtìl, abych na mutantech vyzkoušel experimentální pøípravek. Dávej si bacha co piješ a jíš.}
{192}{}{Chad obral obchodního cestujícího z Gecka o $6000. Ten si stìoval na cenu... øíkal, e u se tu neukáe.}
{193}{}{Chad si strèil do kapsy $1000 z posledního vıvozu uranu. Plánuje zmizet z mìsta.}
{194}{}{Nic. Zapomeò na to.}

{195}{mcs24}{Chodby pod mìstem? S tìmi doly kolem to pro mì není ádné pøekvapení, podívej se tam po tìch ztracenıch lidech, ano? }
{196}{}{V poøádku.}

{197}{mcs25a}{K ïasu jsou mrtví... Budu to muset osobnì øíci jejich rodinám. }
{198}{mcs25b}{Tady máš svoji odmìnu. $500. Moc ti dìkuji.}
{199}{mcs25c}{Hej, poèkej, myslím e jsi øíkal, e to udìláš zadarmo, ale vem si alespoò tohle.}
{200}{}{Jistì.}

{201}{mcs26}{Dík. Já a moji zástupci je odtamtud vyzvedneme... A dìkuji, na takovéhle vìci já nezapomínám.}
{202}{}{ádnı problém. Mìj se.}

{203}{mcs27}{Co mají ti lidé proti mutantùm? Budeme je holt lépe hlídat. Dìkuji, mìsto ti hodnì dluí a já nikdy nezapomenu.}
{204}{}{To nic. Na vidìnou.}

{205}{mcs28}{Mùeš ho prosím tì sledovat? Chceme ho chytit pøi èinu.}
{206}{}{V pohodì.}

{207}{mcs29}{Aha, v tom pøípadì bude lepší ho hned zastavit. Zvládneš to?}
{208}{}{Jistì.}
{209}{}{V ádném pøípadì.}

{210}{mcs30}{Chceš, abych šel s tebou? K èertu jsem ještì moc starej na to abych se usadil. Dobrá, tak jdeme!}
{211}{}{Ano.}
{212}{}{Ne, teï ještì ne.}

{213}{mcs31}{Zrovna teï mám ještì moc práce. A se to tu trochu uklidní, potom moná.}
{214}{}{Jistì, ještì otázeèku.}
{215}{}{Mìj se.}

{216}{mcs32}{Do prkennı ohrady, nejlepší pøítel jakıho sem kdy mìl.}
{217}{}{Jasnì, urèitì si ho chtìl nechat pøedìlat.}
{218}{}{Tak pøíštì.}

{219}{mcs33}{K èertu ano, chtìl. Mohl z nìj bıt fakt skvìlej mutant.}
{220}{}{Myslím, e by nebyl rád, kdyby tì to slyšel øíkat.}
{221}{}{Ahoj.}

{222}{mcs34}{<smích> O tohle jsme se spolu vdycky pøeli. <povzdech> Ten blázen mi fakt chybí.}
{223}{}{Co víš o Vùdcovì nenávisti k lidem?}
{224}{}{Myslím, e osud je nìkdy pìkná svinì.}
{225}{}{Ahoj.}

{226}{mcs35}{Mluvíš o starıch èasech, ale svìt se hodnì zmìnil. Chceš slyšet ten starı pøíbìh?}
{227}{}{Jistìe.}
{228}{}{Teï ne. Mám jiné otázky.}
{229}{}{Nemám èas, promluvíme si pozdìji.}

{230}{mcs36}{Nue, nikdy jsme k lidem necítili nenávist, jen jsme pro nì mìli lepší cestu. Tyhle nové vlády... myslej si, e maj na všechno odpovìï. Kecy. Bıl jsem u toho, vidìl jsem to a mám z toho jizvy na duši.}
{231}{}{Jaká je tedy lepší cesta?}

{232}{mcs37}{Vùdce chtìl všechny pozvednout na stejnou úroveò aby u nikdy na svìtì nebyly války. Byl pøesvìdèen, e to zvládneme v klidu a pokoji, ale nešlo to. Byli jsme pøinuceni bojovat.}
{233}{}{Ty s tím souhlasíš?}

{234}{mcs38}{Kdy ještì il Jacob, myslel jsem, e se Vùdce mılil. Ale zdá se, e jen nìkolik málo lidí tu myšlenku pochopilo. Vìtšina se od ní odvrátila.}
{235}{}{Take teï si myslíš e mìl Vùdce pravdu?}

{236}{mcs38a}{Jacob tu myšlenku pochopil a šel za ní. Zakladatel vlastnì taky. Ale bez ohledu na to kolik lidí se povznese, nevìdomé lidské masy je nakonec vdycky znièí, víš?}
{237}{}{Moná.}

{238}{mcs39}{Vùdce chtìl, aby kadı prohlédl, ale Zakladatel ten sen ukonèil.}
{239}{}{Vypadá to, e jsi Zakladatele obdivoval a nenávidìl zároveò.}
{240}{}{I ty jsi byl èlovìk. To ti nevadí, co s tebou Vùdce udìlal?}
{241}{}{Take myslíš, e Vùdcùv plán byl správnı?}
{242}{}{Já jsem potomek Zakladatele.}

{243}{mcs40}{Máš pravdu. Kdyby všichni lidé bojovali za to v co vìøí, jako on, nepotøebovali bychom Vùdcùv plán.}
{244}{}{Ale Vùdce chtìl zotroèit všechny lidi!}
{245}{}{Pìkná báchorka. Musím jít.}

{246}{mcs41}{Nezapomínej, e já znal celé to hnutí. Nabízelo jen nové perspektivy lidskosti. Vaši lidé ten pøíbìh asi vypráví trochu jinak, e?}
{247}{}{Ehmm.. .moná. Umm, mám ještì otázky.}
{248}{}{Špatnì!}

{249}{mcs42}{"Pravı Zakladatel"? Myslíš ten, kterı znièil Vùdce a jeho nádre?}
{250}{}{Ummm... Ano.}
{251}{}{Zatracenì správnì. Nìco se ti na tom nelíbí, mutante?}
{252}{}{Nooo... tohle je nìkdo jinej. Vùbec nevím o kom to mluvíš.}

{253}{mcs43}{ádnı problém. Jak øíkám, bylo to u hodnì dávno.}
{254}{}{Nemíním se ti taky omlouvat.}
{255}{}{Proè jsi tenkrát nenávidìl lidi?}

{256}{mcs44}{To by nemìl bıt problém, pokud nezkøííš cestu mì nebo nìkomu z mìsta. Chovej se civilizovanì, to je vše co ti øeknu.}
{257}{}{Budu si to pamatovat, ještì otázeèku.}
{258}{}{Dobøe, vím o tom, tak zas nìkdy.}

{259}{mcs45}{Tohle si zapiš za uši: Nic se ti nestane, kdy si nezaèneš. U nás ve mìstì máme rádi poøádné lidi.}
{260}{}{Dobøe, v poøádku. Ještì se chci zeptat.}
{261}{}{Dobøe, dobøe, mìj se.}

{262}{mcs46}{Moje vzpomínky na dbou, kdy jsem byl èlovìk, u nejsou tak jasné jako døív, ale pamatuji se na útrky. Nenávist, zlobu a árlivost... Radìji jsem mutantem.}
{263}{}{Take myslíš, e Vùdce mìl pravdu?}
{264}{}{Ehm. V tomhle jsi trochu nepøíjemnı. Ahoj.}
{265}{}{Pokoj s tebou. Sbohem.}

{266}{mcs47}{To jediné bylo špatné. Mìli jsme vybírat jen ty nejlepší. Podívej se kolem. Spousta mutantù je hloupá nebo nemá chu nìco tvoøit. (povzdech) Kdybychom jen volili lépe...}
{267}{}{A ty jsi chtìl pøedìlat Jacoba? Nebo Zakladatele?}
{268}{}{To je smutné. Nech tì provází síla..}

{269}{mcs48}{Vdycky se tam mùeš vrátit a øíct jim, e válka u skonèila, e u je jí dlouho konec.}
{270}{}{Ummm. Dobrá. Máš mi ještì co øíct?}
{271}{}{Správná vìc. Sbohem.}

{272}{mcs49alt}{Dìkuji ti za pomoc. U by mìl bıt klid, zabrali jsme skladištì zbraní a zneškodnili bomby.}
{273}{}{Skvìlé! Mám ještì otázku...}

# Not using
{274}{}{Hele, nìco jsem našel.}

# Not using
{275}{}{To ses nic nenauèil.}

# I'm leaving you responses
{276}{mcs103a}{Je vás moc. S takovou bandou nebudu cestovat.}
{277}{mcs103b}{Myslím, e seš dobrej, ale já s tebou nemùu jít.}
{278}{mcs103c}{Teï s tebou nemùu jít. Promiò. [Kriticky si tì prohlíí odshora dolù.]}
{279}{}{V poøádku.}

# 104. Fear/Defeat Floats, are we using?
{280}{}{Z toho leknutí sem si málem støík do textilu.}
{281}{}{Na takovıhle móresy nejsem zvyklej... seru na vás, jdu domù.}

# 105. Victory Floats, are we using?
{282}{}{Asi si moc rozumu nepobral, kdy se se mnou chceš prát.}
{283}{}{Pøipravte si zadky... jdeme na to.}
{284}{}{Tak tohle zvládnu s prstem v pr.. teda v nose.}

# 106. Combat Taunt Floats, are we using?
{285}{}{Tak kde máš tu partu hic, aby ses z toho dostal?}
{286}{}{Ty ses vánì nikdy nepral se smrtí?}

# 107. Skill use Success Confirm Float, are we using?
{287}{}{A je to v pohodì.}

# 108. Skill use Failure Confirm Float, are we using?
{288}{}{Kurva. Nìco se posralo.}

# 109. Rejoin Party, NEEDED. Waiting for Voc file.
{289}{mcs109}{Chceš mì zase zpátky?}
{290}{}{e váháš.}
{291}{}{Ne, ještì ne. Zatím.}

# 110. NPC in party
{292}{mcs110}{Co chceš?}
{293}{}{Jak se cítíš?}
{294}{}{Mùeš se uzdravit?}
{295}{}{Potøebuju, abys tu zùstal, ne se vrátím.}
{296}{}{To je asi vše.}

# 111. Heal Yourself
{297}{mcs111a}{Tak sem v pohodì.}
{298}{mcs111b}{U nemám nic, co by nás zpomalovalo.}
{299}{mcs111c}{Potøebuješ s nìèím helfnout?}
{300}{mcs111d}{Tak na tohle se asi budeš muset podívat.}
{301}{}{Pouij svoje schopnosti k léèení.}
{302}{}{Nevadí.}
{303}{}{OK}

# 112. Wait here
{304}{mcs160}{Poèkám tady a trochu si srovnám svá stará bolavá záda.}
{305}{}{Nevadí.}
{306}{}{OK}

# Prases, Not using any but 2 and those are duplicated at the bottom
# Lines 317 is now 20,000 and 315 is 20,001
# Lines 307 through 348
{307}{}{Sever.}
{308}{}{Severozápad.}
{309}{}{Západ.}
{310}{}{Jihozápad.}
{311}{}{Jih.}
{312}{}{Jihovıchod.}
{313}{}{Vıchod.}
{314}{}{Severovıchod.}
{315}{}{Neptej se mì na to, tomu fakt nerozumím.}
{316}{}{Jasnì.}
{317}{}{V poøádku.}
{318}{}{Ne, ne.}
{319}{}{Proè se mnou mluvíš z patra?}
{320}{}{Ne, dìkuji.}
{321}{}{Dík.}
{322}{}{To je dobøe.}
{323}{}{To není dobøe.}
{324}{}{Tohle mám moc rád.}
{325}{}{Mám z toho špatnı pocit.}
{326}{}{S tìmahle lidma bude asi problém.}
{327}{}{Nic jsem se nenauèil.}
{328}{}{Nìco jsem se nauèil.}
{329}{}{Jsou tam všichni v poøádku?}
{330}{}{Moná, e je i jiná cesta.}
{331}{}{Následuj mì.}
{332}{}{Zkus to.}
{333}{}{Pojï sem.}
{334}{}{Našel jsem nìco, co moná budeš chtít vidìt.}
{335}{}{Odsud je kamkoliv daleko, radìji se tu utáboøíme.}
{336}{}{Nebylo by dobré tady spát.}
{337}{}{Mùeme si dáchnout tady.}
{338}{}{Dneska mám svùj šastnej den.}
{339}{}{Jestli chceš, tak ti to opravím?}
{340}{}{Zapni to.}
{341}{}{To asi bude potøeba odemknout.}
{342}{}{Chceš to otevøít?}
{343}{}{Vrátíme se sem pozdìji.}
{344}{}{Nerozumím.}
{345}{}{Já parchant.}
{346}{}{Ow.}
{347}{}{To fakt bolelo.}
{348}{}{To fakt nemùe dopadnout dobøe...}

# Player responces leading to pregnancy
{349}{}{Uh... kdy jsme byli v Koèièí Pacce v New Reno a ty jsi øíkal 'Doufám, e nebude tìhotná', cos tím myslel?}

# 113. Waiting for Vocs.
{350}{mcs113}{Copak ti TO rodièe nevysvìtlili?}
{351}{}{Ne, myslím, e všichni mutanti jsou sterilní.}
{352}{}{Nevadí.}

# 114. Waiting for Vocs.
{353}{mcs114}{Coe? Odkud tohle máš?}
{354}{}{Coe ...ty nejsi sterilní?}
{355}{}{Nech to bejt.}

# 116. Waiting for Vocs.
{356}{mcs116}{NE, teï u ne, ubìhlo hodnì èasu po mém pøedìlání, ne se ve mì zase zaèaly probouzet hormony. Proè se ptáš?}
{357}{}{O, ale jen tak.}

# Exp description
{360}{}{Povedlo se ti odhalit spiknutí proti mutantùm v Broken Hills.}
{361}{}{Markus se k tobì pøidal.}

# Additional Player responses
{400}{}{O tìch ztracenıch lidech...}
{410}{}{O Jacobovi a Aileen...}
{420}{}{O Chadovi...}
{430}{}{O tìch uprchlících...}
{440}{}{O vìdci z NCR...}

# Float, Pissed
{500}{}{Máš docela kurá, kdy se tady zase ukazuješ.}

# Player additional responses
{501}{}{Zapomeò na to. Mùu se tì ještì zeptat?}
{502}{}{Ale nic. Mìj se.}

# Marcus floats
{600}{}{Šéfe, neni mi moc dobøe.}
{601}{}{Proè se o mì tak otíráš, radìji to nedìlej.}
{602}{}{Nemyslíš, e je to tady trochu strašidelnı?}
{603}{}{Doufám, e máš pampersky... vypadá to na pìknı sraèky.}
{604}{}{Nemám rád pohled na tohle místo.}
{605}{}{Ta zlomená kost mùe otravovat, kdy jí nechám bıt, šéfe.}
{606}{}{Ahh, lidství.}
{607}{}{Tohle je pìkná ukázka toho, e Vùdce mìl pravdu.}
{608}{}{Tys myslel, e jsou mutanti nemocní.}
{609}{}{Opatrnì, šéfe. Tihle tıpci vypadaj hustì.}
{610}{}{Teda... vy lidi mì neustále pøekvapujete.}
{611}{}{Doufám, e víš kam jdeme...}
{612}{}{Nakopem jim kaïáky, šéfe.}
{613}{}{Ty joudové dìlaj to co mì dokáe nasrat.}
{614}{}{Ahh, opìt doma.}
{615}{}{Nezapomeò... pomáhal jsem to tady tvoøit. Chovej se slušnì.}
{616}{}{Je pìkné vidìt svùj rodnı dùm.}
{617}{}{Vdycky jsem to tady nenávidìl.}
{618}{}{Kdy pùjdem?}
{619}{}{Vypadnem odsud.}
{620}{}{Nemyslím, e by sem tam chtìl, šéfe.}
{621}{}{Tak tady to všechno zaèalo, eh?}
{622}{}{Je tady nìkde doktor, huh?}
{623}{}{Chceš aportovat?}
{624}{}{Jak dìlaj pánièky, pejsku! Hraj mrtvého!}
{625}{}{Azore trhej!}
{626}{}{Hele Lenny! Pøijdeš nìkdy k nám, do Broken Hills?}
{627}{}{Lenny! Zapaøíme, né!}
{628}{}{Je dobrı mít v partì nìkoho civilizovanıho, Lenny.}
{629}{}{Hej Myrone! Chceš se prát?}
{630}{}{Nemìj strach, malı Myrone. Dám na tebe pozor.}
{631}{}{Vyzkoušíme Myronùv velkej mozek!}
{632}{}{Phwheew!!! Kdo mi dá koláèek?}
{633}{}{[pískání] U mi lásko není 20 let... [zpívání]}
{634}{}{Sakra, u mi líe trenky.}
{635}{}{V mém vìku je vhodné se obèas zastavit.}
{636}{}{Jenom koukám na mraky...}
{637}{}{Zzzzzzzzz.}
{638}{}{Dík, bossy.}
{639}{}{Uh... dík, kámo.}
{640}{}{Err... dík.}
{641}{}{Dìkuji. Mìl jsem ízeò.}
{642}{}{Whoa...Cítím se trapnì.}
{643}{}{Pøedpokládám, e mìl Francis pravdu s Jacobem. Ten zoopedonekrofil u tady nebude dìlat problémy.}
{644}{}{Dostal jsi loveckou pušku se zamìøovaèem.}
# End of Floats

# Marcus Dialog, in party response
{1100}{mcs43alt}{ádnı problém.}

# Player responses
{3000}{}{Tak jdem.}
{3100}{}{Zapomeò e jsem se ptal, øiko.}
{3200}{}{Potom to nevadí. To je tvùj boj.}
{3300}{}{Krucinál. Moná pozdìji.}

# Player responses, that should have been replaced by new party format. Keeping just to be safe
{9999}{}{Chtìl bych se tì na nìco zeptat...}
{10001}{}{Pouij stimpaky ke svému zotavení.}
{10002}{}{Marcusi, potøebuji abys tu poèkal, ne se vrátím.}
{10003}{}{Schovej zbraò.}
{10004}{}{Dr se pøi mnì.}
{10005}{}{Nechoï moc daleko.}
{10006}{}{Mìli bychom trochu rozestoupit.}
{10100}{}{Dìlej, Marcusi. Je èas zmizet.}
{10007}{}{Tak potom jdem.}


# New Marcus dialog for new party structure, waiting for Vocs, from Phrases 81 and 79
{20000}{mcs81b}{V poøádku.}
{20001}{}{Heh. Umím pouívat jakoukoli velkou zbraò, jako tøeba raketomety nebo miniguny a taky velké energické zbranì. S pìstmi taky nejsem špatnı a s granátem nadìlám docela velkou paseku. Bohuel neobleèu ádné brnìní, jeliko jsou mi všechna malá.}
