#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš mue v chatrném obleèení.}
{101}{}{To je Manson, jeden z èlenù protimutantského hnutí.}
{102}{}{Vidíš mladého mue se strništìm vousù, v otrhanıch šatech a s urèitou nenávistí ve vırazu jeho tváøe.}

{103}{}{Co?!}
{104}{}{Duhhh... gabba gabba hej?}
{105}{}{Vás vychcánky já znám?}
{106}{}{Kdo jsi?}
{107}{}{Co dìláš ve vìzení?}
{108}{}{Co mi povíš o Broken Hills.}
{109}{}{Ale nic, zapomeò na to.}

{110}{}{Vùbec nerozumím o èem to plácáš, a radìji zmiz, ne mì taky nakazíš stupiditou.}
{111}{}{Och!}

{112}{}{Manson. Vzbouøenec proti spoleènosti.}
{113}{}{A proti èemu bojuješ?}
{114}{}{Jasnì! Pryè s tyranií!}
{115}{}{Vyvrhnut ze spoleènosti, to se fakt máš.}
{116}{}{Manson?}
{117}{}{Já ... vidím. Sbohem!}

{118}{}{Já a tady Frank jsme proti tomu, v co se spoleènost snaí vìøit.}
{119}{}{A to jako...}
{120}{}{Ano! Pryè s mocí!}

{121}{}{Broken Hills? il jsem tu celı mùj ivot. A taky proto vím, co se tu ve skuteènosti dìje. Mutanti jsou zlí a vykoøisujou nás, ale je dobré, e vìtšina z nás u prohlédla.}
{122}{}{Jasnì, jak øíkám. Pryè tyranií?}
{123}{}{Máš zastøenou mysl, podle mì to není pravda.}
{124}{}{Moná by sis mìl uvìdomit, e jenom zaslepenci jako vy to dìlaj ostatním horší a ty tvoje kecy o nenávisti z tebe dìlaj pìkného hlupáka.}
{125}{}{Samo. Sbohem.}

{126}{}{Spoleènost chce, abychom vìøili, e lidi a mutanti mùou spolu ít bez problémù. Ale mutanti nás chtìj vybít! A to jsou pøesnì Frankova slova.}
{127}{}{Koukám, e máš Franka fakt rád?}
{128}{}{Tak to je podle mì ta nejblbìjší vìc.}
{129}{}{Tak si to hoï. Èau.}

{130}{}{To je pravda! Mìli bychom... umm... myslet sami na sebe! To øíká Frank a Jacob!}
{131}{}{Ty seš na tìch dvou asi fakt závislej. Proè nezkusíš myslet sám za sebe, místo toho abys poslouchal vlasteneckı øeèi ostatních?}
{132}{}{Seš s tím Frankem nìjakej divnej?}
{133}{}{Tak si to uij.}

{134}{}{A co bys chtìl vìdìt ty špíno? Mìl by ses odsud rychle ztratit, ne se ti náhodou nìco stane!}

{135}{}{Kdysi dávno tady byl èlovìk, co nás nauèil myslet sami za sebe. Moje matka a otec mi øíkali, e jsem s ním byl pøíbuznı. Zemøel ve vìzení, ale stejnì mìl na mì velkı vliv. Lidé øíkají, e byl hodnì chytrı a myslím, e mìli pravdu. Tím chci øíct, aby ses na mì podíval!}
{136}{}{No... Tak uka, co to tady máme. Mrknu se na tebe.}
{137}{}{Ty? Chytrák? Nenech se vysmát!}
{138}{}{No jo. Tak ahoj.}

{139}{}{Co to?}
{140}{}{Nic.}

{141}{}{Jasnì. Myslím, e to byl nejchytøejší èlovìk jakého jsem znal. Jacob je chytrej, ale tak jako Frank.}
{142}{}{Frank je jen pytel sraèek a chce tì zatáhnout do kadıho maléru.}
{143}{}{No jo, potkal jsem ho. Je docela dobrej.}
{144}{}{Nemìl jsem pøíleitost se s ním seznámit, take nemùu soudit.}
{145}{}{Tak dík. Navidìnou.}

{146}{}{Tak co bys ještì chtìl?}
{147}{}{Kdo jsi?}
{148}{}{Proè jsi v base?}
{149}{}{Co mi povíš o Broken Hills.}
{150}{}{Máš rád Franka?}
{151}{}{Proè se jmenuješ Manson?}
{152}{}{Nejsi takhle náhodou blbec?}
{153}{}{Ale nic. Nech to plavat.}

{154}{}{Ty jsi s námi? Tak nás odsud dostaò!}
{155}{}{Pracuju na tom, uvidíme se.}

{156}{}{Dík za pomoc. Je dobré následovat èlovìka, co nás vyvedl ze tmy!}
{157}{}{No jo. To rád slyším.}

{158}{}{Take co pro tebe ještì mùu udìlat?}
{159}{}{Jaké máš teï plány.}
{160}{}{Jaké je tvoje jméno?}
{161}{}{Ale nic. Jen se rozhlíím.}

{162}{}{Tak a teï se pokusíme znièit dùl, a budou mutanti uvnitø. A kadıho, kterej uteèe umlátíme.}
{163}{}{To by se mi líbilo.}
{164}{}{Tak s tím nepoèítej.}
{165}{}{Boí. Hodnì štìstí.}

{166}{}{Lidé vìøili, e to byl kazatel nebo tak nìco. Ale jsem pojmenovám po nìkom, kdo zaèal v nìco vìøit a byl pro to zabit. Nìco jako muèednik. Moná, e se jím taky stanu.}
{167}{}{To zní... zajímavì. A dál...}

{168}{}{U jsem o tom mluvil s Jacobem. Jem si jistı, e s tou tvojí pomocí s útìkem, budeš vítán.}
{169}{}{Skvìlé. Uvidíme se.}

{170}{}{Chtìl bych s tebou pracovat. No jo.. tak nashledanou!}

{171}{}{Ty sráèi! A my tak vìøili e nám pomùeš!}

{172}{}{Wow... tak tahle brutálního zabijáka jsem ještì nikdy nevidìl. A teï jsme volní a bez mutantù. To je booííí!}

{173}{}{Chystáme se vypadnout z mìsta. Radìji pojï taky... mutanti budou potøebovat na nìkoho ukázat prstem.}

{174}{}{Jdeme za tebou.}

{175}{}{Otevøel jsi Mansonovi oèi.}

{176}{}{Svobodu! Svobodu!}

{177}{}{Dik za pomoc pøíteli. Bì si promluvit s Jacobem a Aileen.}

{178}{}{Podaøilo se ti vloupat do vìzení.}

{179}{}{Hodnì štìstí v dole, bratøe.}
