#tento soubor pøeložil Vachy - http://vachy.moje.cz
{100}{}{Vidíš mutanta s krumpáèem ve špinavých hadrech.}
{101}{}{Vidíš mutantského horníka.}
{102}{}{Vidíš mutanta s krumpáèem ve špinavých hadrech. Podle mozolù na jeho rukou jsi poznal, že to bude asi horník. Vypadá unavenì a trochu rozhozenì.}

{103}{}{Co chceš?}
{104}{}{Ag-ag! Ooo!}
{105}{}{Ork! Ooky!}
{106}{}{Dallo?}
{107}{}{Dallo!}
{108}{}{Co se tu dá dìlat?}
{109}{}{Kdo jsi?}

{110}{}{A bože zase další blázen zasaženej rakovinou mozku. Já ti vùbec nerozumím, co pro tebe mùžu udìlat.}

{111}{}{Øíkám, že ti nemùžu pomoct! Jdi pryè a zkus srát nìkoho jinýho!}

{112}{}{Co se tu dá dìlat? Dobrá, z dolování nic nebude, protože nefunguje èistiè vzduchu. Taky je tu salón. Máme tu taky nìjaké karavany a taky hlavní obchod. A to je asi všechno.
 poèkej... o èem se to vlastnì bavíme?}
{113}{}{S kým si mùžu popovídat o dole?}
{114}{}{Kde je tady salon?}
{115}{}{Kde najdu nìkoho od karavan?}
{116}{}{Kde je tu hlavní obchod?}
{117}{}{Díky. Nashle.}

{118}{}{Jenom jeden z horníkù. Máš nìco dùležitého?}
{119}{}{Jo.}
{120}{}{Ne.}
{121}{}{Mìj se.}

{122}{}{Hlavní postavièky v tomhle mìstì jsou Marcus, to je nìco jako starosta a šerif, Vachy, to je hlavní dùlmistr a Chad, ten jezdí s karavanama. Barman Phil je šéf ghoulù, Alespoò doufám...
jestli vùbec maj nìjakýho vùdce. Tak co?}
{123}{}{Kde najdu Marcuse?}
{124}{}{Kde najdu Vachyho?}
{125}{}{Kde najdu Camerona?}
{126}{}{Kde najdu Chada?}
{127}{}{Kde najdu Phila?}
{128}{}{Díky. Nashle.}

{129}{}{Jestli máš ten neodbytnej pocit, že nám mùžeš pomoct s opravou, tak si promluv s Vachym. On tomu tady velí a kanceláø má támhle u dolu. Ale má špatnou náladu, kvùli tomu èistièi vzduchu. Ještì nìco?}

{130}{}{Phil je ghoul a patøí mu salon. Je nìco jako místní ghoulí šéf. Toho najdeš kousek od banky. Chceš ještì nìco?}

{131}{}{Chad øídí chod karavan a mìl bys ho najít na jihozápadì mìsta. Co ještì?}

{132}{}{Liz, to je jeden z mála slušných lidí. Patøí jí obchod na západ od banky. Ještì nìco?}

{133}{}{No jo. Uvidíme se pozdìji.}
{134}{}{Cameron je vùdce všech normálních lidí ve mìstì. Nemá sice moc rád mutanty nebo ghouly, ale jinak je v pohodì. Je to takový jejich politik, takže ho najdeš v bance a nebo v salonu. Obèas ho taky najdeš v kovárnì. Tak staèí ti to? A kdo jsem já? No to nech plavat?}

{135}{}{Marcus je náš šéf. Pomohl vybudovat Broken Hills. Urèitì ho najdeš nìkde kolem Banky. Tak co ještì?}

{136}{}{Chamtivej skrblíku. Víš jak tìžce musíme pracovat? Doufám že víš.}

{137}{}{Dìkuju za rudu!}

{138}{}{Poøád nemùžu uvìøit tomu, že je dùl zavalen. Vypadá to, že tu všichni umøeme. Ten dùl byl to jediný, co udržovalo mìsto pøi životì. Asi už budu opravdu muset do dùchodu...}

{139}{}{Zemøeš za strašných muk!}

{140}{}{Díky tobì máme zpátky svoji práci. Vdìèíme ti hodnì, jak ti mùžu pomoci?}
{141}{}{Kdo jsi?}
{142}{}{Co se dá dìlat ve mìstì?}
{143}{}{Nic.}

{144}{}{Jsme ti vdìèní za záchranu pøed tìma krysama z NCR. Opravdu dík. Je nìco, co pro tebe mùžu udìlat?}
{145}{}{Kdo jsi?}
{146}{}{Co se dá dìlat ve mìstì?}
{147}{}{Nic.}
