#tento soubor pøeložil Vachy - http://vachy.moje.cz
{100}{}{Vidíš starého mutanta.}
{101}{}{Starý mutant z Broken Hills.}
{102}{}{Po bližší prohlídce, vidíš pøestárlého mutanta. Jeho svaly vypadají poøád dobøe, stejnì jako charisma, která z nìj èiší.}

{103}{}{Myslím... že... ten radonový plyn nechává horníky mladé.}
{104}{}{Už si toho moc nepamatuju... ale všechno se to pomalu vrací... poèkej...}
{105}{}{Víš o tom, že nás lidé chtìjí zabít?}
{106}{}{Pøál bych si, aby nás lidé akceptovali. Stejnì jsme taky lidé.}
{107}{}{Co se vlastnì dìje ve svìtì? Dopøej pár vìt mému sluchu.}
{108}{}{Nìkdo øíká, že FEV co nás stvoøil, nás dìlá senilními.}
{109}{}{Všechny vzpomínky jakoby prokluzovaly. Býval jsem silný a rychlý... teï jsem trochu jako èlovìk.}
{110}{}{Co vlastnì zbude ze života, když to všechno skonèí?}

{132}{}{Kdo nechal ty psy utéct? Já je pøetrhnu!}
{133}{}{Frank a Manson udìlaj líp, když budou nìkde zašitý... Až je chytím, srazím jim hlavy dohromady.}
{134}{}{Frank. Manson. Pìkný skunci.}
{135}{}{Ty prdele, jsou na svobodì, aby mohli zase vraždit?}
{136}{}{Sháníme maníky na ty dva.}
{137}{}{Nebudu klidnì spát, dokud nebudou mrtví.}
{138}{}{Tady jde o vlastní bezpeèí.}
{139}{}{Dobrá... ummm... A kdo byl?}

{140}{}{Frank a Manson se budou chovat slušnì? Jestli jsem nìkdy neslyšel vìtší blbost.}
{141}{}{Chci abys vìdìl, že ti moc nepodìkujem, jestli udìlaj ještì nìjakej prùser.}
{142}{}{V pohodì... Budu se snažit dát jim ještì šanci...}
{143}{}{Jak se dostanu domù?}
{144}{}{Nechtìj jsem s tebou jen mluvit?}
{145}{}{Nebudu klidnì spát, dokud nebudou mrtví.}
{146}{}{Tady jde o vlastní bezpeèí.}
{147}{}{Dobrá... ummm... A kdo byl?}

{148}{}{Vìdìl jsem to! Znám tyhle budižknièemy co maj nìco proti nám!}
{149}{}{Nikdy jsem nevìøil tomu hajzlovi Jacobovi.}
{150}{}{Tak... Lidi nás chtìj povraždit. No aby to nebylo spíš naopak.}
{151}{}{Né všichni lidi to chtìj udìlat, že jo?}
{152}{}{Dobrá, dobrá, dobrá... ještì více lidských intrik?}
{153}{}{Ztratil jsem mnoho dní... moje vzpomíny a mùj boj za humanitu jsou pryè.}
{154}{}{Seš docela pašák, že jo.}

{162}{}{Francis je zaujatej. Stejnì jako já.}
{163}{}{Jak mùže èlovìk zmlátit mutanta holejma rukama? Tys podvádìl?}
{164}{}{Tak jak využiješ naší cenu?}
{165}{}{Silný. Velmi silný.}

{166}{}{Jak jednou poznáš mutanta, nikdy se nevrátíš.}
{167}{}{Slyšel jsem na tebe chválu - jojo... od Francise.}
{168}{}{Rád tì zase uvidím.}
{169}{}{Heh... Francis je možná starej, ale stále na to má!}

{170}{}{Tihle ubozí lidé.}
{171}{}{Být chycen pod zemí...}
{172}{}{Jak jsem vždycky øíkal, "Jacob a Aileen sou problém. Stejnì jako Frank a Manson." Ale nikdo mì neposlouchal. Nikdo.}
{173}{}{Chodby, eh? Vždycky jsem v nich vidìl jen krysy a èervy.}
{174}{}{Tyhle mrtvoly jsou to co tu smrdí, huh?}

{175}{}{Proè nás biješ?}
{176}{}{Lidi mi nikdy nevìøí.}
{177}{}{Nech mì být.}
{178}{}{Proè jsi ještì nechcíp?}
{179}{}{Proè se lidé vždycky bojí svého stínu?}
{180}{}{Seš hajzl.}
{181}{}{Tvùj život je pomíjivý.}
{182}{}{Ty... Znám lidi jako ty...}
{183}{}{Jsem už moc starý na to abych tì nenávidìl.}
