#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš plnoštíhlého zaprášeného mue.}
{101}{}{Vidíš vetešníka Billa.}
{102}{}{Vidíš tlustšího mue pokrytého prachem. Smrdí jako kdyby mìl nìco s brahmínami.}

{103}{}{Ahoj, parde. Co pro tebe mùu udìlat?}
{104}{}{Nimma ardle ah!}
{105}{}{Ty mít práci?}
{106}{}{Hledám práci.}
{107}{}{Chci nìco koupit.}
{108}{}{Co mi øekneš o Chadovi?}
{109}{}{Omluv Chada. Má toho moc.}
{110}{}{Myslím, e Chad je teï docela na dnì.}
{111}{}{Kdopak jsi?}

{112}{}{Promiò brachu, ale nìjak nemùu pochopit co øíkáš. Tu máš lízátko.}
{113}{}{Oooh!}

{114}{}{Jistì mám tady nìjakej brahmínní hnùj. Kdy ho budeš celı den kydat dám ti $100. Dohodnuto?}
{115}{}{Chceš práci? Dobrá, máš na vybranou: Pøeházet hromadu hnoje za $100 nebo jet s nìjakou karavanou za $200. Jezdíme do  Gecka, New California Republic a Vault City.}
{116}{}{OK!}
{117}{}{Sakra.}
{118}{}{Budu pøehazovat ty kravskı hovna.}
{119}{}{Pojedu do Gecka.}
{120}{}{Co takhle do NCR.}
{121}{}{Chci do Vault City.}
{122}{}{A radìji ne. Chci nìco jiného.}
{123}{}{Nashle!}

{124}{}{Jistì? Co chceš koupit?}

{125}{}{Zajímá tì Chad? A co chceš vìdìt?}
{126}{}{Nevybírá si náhodou to nejlepší?}
{127}{}{Vìøíš mu?}
{128}{}{Co mi o nìm mùeš øíct?}

{129}{}{Já? Sem Bill. Jsem, jak lidé øíkají, Bill kterému dluíš. To je ale jen tak, spíš platím já ostatním. Jsem plánovaè karavan pro tohle místo. Dávám dohromady obchodní cesty taky marketing. Najímám lidi pro práci a samozøejmì e jsem taky v Mìstské hlídce.}
{130}{}{Práci? Jakı druh práce?}
{131}{}{Dík. Uvidíme se!}

{132}{}{Tak jo. Zaènem.}

{133}{}{Nemáš zájem? V pohodì. Pøijï a budeš mít èas.}
{134}{}{OK!}
{135}{}{No spíš se zajímám o nìco jiného.}
{136}{}{Nashle.}

{137}{}{Tak jo vybral sis Gecko. Vra se prvního v mìsíci a vyrazíme. Chceš ještì nìco?}
{138}{}{Jo.}
{139}{}{Ne.}

{140}{}{Tak jo vybral sis NCR. Vra se jedenáctého v mìsíci a vyrazíme. Chceš ještì nìco?}
{141}{}{ Tak jo vybral sis Vault City. Vra se jednadvacátého v mìsíci a vyrazíme. Chceš ještì nìco?}

{142}{}{Co chceš?}
{143}{}{Hledám práci.}
{144}{}{Chci nìco koupit.}
{145}{}{Co mi povíš o Chadovi?}
{146}{}{Omluv Chada. Má toho dost.}
{147}{}{Myslím, e šéf tvojí ochranky je v pìknejch sraèkách.}
{148}{}{Kdopak jsi?}

{149}{}{Docela dobøe se s tebou obchoduje, chceš ještì nìco?}
{150}{}{Promiò ale to by nestaèilo, chceš ještì nìco?}
{151}{}{Ani ne, mìj se!}

{152}{}{U to máš? No paráda, tady je tvıch $100 a kdy budeš nìco potøebovat, dej mi vìdìt.}

{153}{}{Chlape pøijï zpátky za hodinu, dvì a rád s tebou nìco smìním. Teï mám bohuel práci s brahmínami. Ještì nìco chceš?}

{154}{}{Jestli je v tom háèek? Nic o èem bych vìdìl. Za jednu dodávku uranu si poèítáme $5,000. Zpátky dostaneme taky $5,000. Co vím, tak v tom není ádnı háèek. Má pìkné místo a vdycky dostal dobøe zaplaceno, ale nìco sem mohl zanést pøi svém pøíchodu.}
{155}{}{Ještì mám pár otázek.}
{156}{}{Chci nìjaké jiné vìci.}
{157}{}{Uvidíme. To je asi vše. Dík.}

{158}{}{Jestli mu vìøím? Samozøejmì ... a docela hodnì. Vìøím e dokáe øídit chod karavan. Moná má nìjaké mouchy, ale dokud mi nedá dùvod, bude to v pohodì.}
{159}{}{Mám trochu víc otázek.}
{160}{}{Chci nìjaké jiné vìci.}
{161}{}{Dìkuji ti za tvùj èas.}

{162}{}{Pøišel do Broken Hills z pouštì. Moc toho nemìl, ale vypadal chytøe. Vypadalo to, e ho nìkdo honil, ale nikdy neøekl kdo to byl. O svojí minulost vlastnì vdycky mlèel. A vùbec... je to nejlepší vedoucí karavan. To vše.}
{163}{}{Ještì otázeèku.}
{164}{}{Chci nìco jiného.}
{165}{}{Dík.}

{166}{}{Teï mám práci. Pøijï a budu v obchodì.}

{167}{}{e toho má dost? Ty hovòousi, prachy zabíjej, to bys mìl vìdìt.Okamitì odsaï zmiz.}
{168}{}{Tak se mìj.}

{169}{}{Jestli má nìjaké problémy, mùe si za nì sám. To je špatné... byl to opravdu dobrej vedoucí. Chceš ještì nìco?}

{170}{}{Vypadni odsud, nechci tì tu.}

{171}{}{Mùeme vyrazit na tu cestu do Vault City?}

{172}{}{Mùeme vyrazit na cestu do NCR?}

{173}{}{Mùeme vyrazit na cestu do Gecko?}

{174}{}{Teï nejezdíme. Tam do toho pekla nikoho nepošlu, dokud bude kdokoli chtít zabít moje lidi. Ještì nìco?}

{175}{}{Sereš na moje karavany?}
{176}{}{Ne, jen ještì musím zaøídit pár vìcí.}
{177}{}{Chci vymìnit karavanu.}

{178}{}{Potøebuješ víc èasu? Dobrá, máš ho mít. Pøijï, a si splníš svoje povinnosti.}

{179}{}{Zmìna? A jakoupak bys chtìl? Do Gecka prvního, do NCR jedenáctého nebo do Vault City dvacátého prvního.}
{180}{}{NCR.}
{181}{}{Gecko.}
{182}{}{Vault City.}

{183}{}{Coe, tak to odsud zmiz. Vra se, a nebudeš mít sraèky kolem huby.}

{184}{}{Vıbornì. Potom jdeme.}
{185}{}{Nejdøív ještì nìco chci.}
{186}{}{V poøádku.}

{187}{}{Víc pro tebe nemohu udìlat pøíteli. Kdy jsou mutanti mrtví, tak doly u nebudou pracovat. Tohle mìsto se za rok dva vylidní a nic tady nezbude. Tak se mìj.}

{188}{}{U pro tebe nic nemám pøíteli. Ten hnùj jsem si nakydal sám.}
{189}{}{Chceš práci? No uvidíme co v tobì vìzí, buï nakydej hnùj a nebo se mùeš vypravit na cestu s karavanou. Mùeš nám pomoct dìlat ochranu za $200. Jezdíme jednou tıdnì do Gecka, New California Republic a Vault City.}
{190}{}{Ráád hnojíèek, ráád hovíínka. Ahoj.}
{191}{}{Chceš práci? No uvidíme co v tobì vìzí, buï nakydej hnùj a nebo se mùeš vypravit na cestu s karavanou. Mùeš nám pomoct dìlat ochranu za $200. Jezdíme jednou tıdnì do Gecka, New California Republic a Vault City.}
{192}{}{Chceš práci? Dobrá, máš na vybranou: Pøeházet hromadu hnoje za $100 nebo jet s nìjakou karavanou za $200. Jezdíme do to Gecka, New California Republic, a Vault City. Vyjídíme kadı tıden.}

{193}{}{Stal se z tebe expert pøes vıkaly!}
{194}{}{Tvoje umìní øeèi se zvedlo o 5%.}

{195}{}{Chci jet s karavanou.}
{196}{}{Øíkal jsi, e do Gecka jezdíte kadého prvního v mìsíci.}
{197}{}{Øíkal jsi, e do NCR jezdíte kadého jedenáctého v mìsíci.}
{198}{}{Øíkal jsi, e do Vault City jezdíte kadého jednadvacátého v mìsíci.}

{200}{}{Chci zmìnit cestu.}
{201}{}{To je v poøádku. Nevadí.}
{202}{}{Ty parchante! Ty si budeš ještì vymejšlet! Vypadni odsud!}
{203}{}{V pohodì. Klidnì s tou karavanou pojedu.}

{204}{}{Dobrá. Jedem do Gecka. Karavana odjídí dnes. Mùeme vyrazit?}
{205}{}{Dobrá. Jedem do NCR. Karavana odjídí dnes. Mùeme vyrazit?}
{206}{}{Dobrá. Jedem do Vault City. Karavana odjídí dnes. Mùeme vyrazit?}
{207}{}{Jasnì jsem v pohodì, jedem.}
{208}{}{Ještì bohuel ne, dám ti vìdìt, a budu moct.}
{209}{}{Zatím ještì ne. Mám pár otázek.}

{210}{}{Dík.}
{211}{}{[pokraèovat]}

{212}{}{Je mi líto, ale bez Chada, kterej mi to tady øídil, nemùu nabízet práci. Ten hajzl mi fakt chybí. Umøel nìkde na planinách jako prašivej vlk.}
{213}{}{To je mi líto. Mìj se.}
