#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš ghoula v zástìøe.}
{101}{}{To je barman Phil. Myje sklenice.}
{102}{}{Vidíš ghoula v zástìøe myjícího sklenice. Podle toho, jak stojí za pultem, jsi poznal, e to je místní barman.}

{103}{}{Nazdárek cizinèe, vítej u nás ve mìstì. Jakpak se jmenuješ?}
{104}{}{Eh..ehb?}
{105}{}{!}
{106}{}{.}
{107}{}{To nejni tvoje vìc, kámo.}
{108}{}{Teï jsem trochu zaneprázdnìn.}

{109}{}{Jmenuješ se Ehehb? Ha! Jen ertuješ. Tady, vem si Nuka-Colu a zkus nevyrušovat ostatní zákazníky.}
{110}{}{Dìkovat!}

{111}{}{, ano? No tak tedy - rád tì poznávám. Chceš nìco k pití?}
{112}{}{Pití, to si dát.}
{113}{}{To ne. Ne ne ne ne.}

{114}{}{, potìšení je na mé stranì. Jsem Phil. Patøí mi to tu. Tak... co si dáš?}
{115}{}{Nuka-Colu.}
{116}{}{Pivo.}
{117}{}{Rotgut.}
{118}{}{Nic.}
{119}{}{Dneska nic, promiò. Mìj se!}

{120}{}{Fajn, pøíteli. Vlastním tuhletu putyku a jmenuju se Phil. Tak co to bude?}

{126}{}{Zaneprázdnìnı, jo? No tomu asi nerozumím. Jsem Phil, co si dáš?}

{132}{}{Chceš pivo? Rot gut? Nuka-Colu?}
{133}{}{Blivo!}
{134}{}{Bláto but!}
{135}{}{Njúkakolu!}

{136}{}{Dobrá, dej mi vìdìt, kdybys cokoli potøeboval a udìláme co bude tøeba, pøíteli. Pokus se nevyrušovat ostatní štamgasty, jo?}
{137}{}{A-ch-no!}

{138}{}{Tak tady to máš. To bude $3, plus vysokohorská pøiráka $1. To dìlá $4, chapèe.}
{139}{}{Tadyhlenc!}
{140}{}{Nemám.}

{141}{}{Silnej chlast, miláèku! To bude $5, plus DPH $1, to dìlá $6.}
{142}{}{Samohonka, dìvèe! To bude $5, plus pøiráka za mùj èas $1, to dìlá $6.}

{145}{}{Tak tohle ti udìlá dobøe na ple. To bude $2. Na tomhle se nedá nic pøirazit. Necháme to za $2.}

{148}{}{. Kdy budeš potøebovat cokoli k pití, pøijï a nìco s tím udìláme.}
{149}{}{V poádku!} #citoslovce 

{150}{}{! Dáš si nìjakej chlast?}
{151}{}{Plast jo!} #citoslovce 
{152}{}{Radìji nic!}

{153}{}{Ahoj, Ehehbe! Vítej zpìt. Tvoje idle se ani nestaèila ochladit od minule, sedni.}
{154}{}{Kuju!} #citoslovce 

{155}{}{To bude $2.}
{156}{}{Chci $4.}
{157}{}{$5 to spraví.}
{158}{}{Tady máš.}
{159}{}{[Dáváš Philovi spropitné $1] Tady máš, Phile.}
{160}{}{[Dáváš Philovi spropitné $2] Díky, Phile.}
{161}{}{Sakra, to je na mì asi moc.}

{162}{}{Nic? Ha. Ha. Nemùeš tady bejt, kdy nechceš pití, pøíteli. Taky z nìèeho musím platit úèty. Zkus to znova. TAK! Co bude?}
{167}{}{Zapomeò na to. Mizím.}

{168}{}{Nebudu mluvit, dokaï nic nekoupíš. Tak jaké máš pøání?}
{173}{}{Zapomeò na to a svùj prašivej chlast si bì nìkam zahrabat!}

{174}{}{Dík. Ještì nìco?}
{175}{}{Hele, dìkuju! Co jiného?}
{176}{}{Wow! Dìkan! Ještì nìco, co pro tebe mùu udìlat?}
{177}{}{Chci víc pití.}
{178}{}{Co se dìje tady ve mìstì?}
{179}{}{Dìje se nìco kolem?}
{180}{}{Nìjaké novinky?}
{181}{}{Nic. Nech to plavat.}

{182}{}{Pøehnal, eh? To je špatnı. Mùeš se tu ještì motat, ale neotravuj hosty. Ještì mám nìjakou práci, take se uvidíme.}
{183}{}{Sbo-škyt-hem!}

{184}{}{Hle! Vítej zpìt. Co to bude?}
{185}{}{Nazdárek, èlovìèe. Tak co to bude?}
{186}{}{Zase ty? Co si dáš?}
{187}{}{Opìt ty? Co chceš?}
{192}{}{Øekni mi moje jméno. To je }
{193}{}{Nic, promiò. Sbohem!}

{194}{}{Dobrá, v poøádku! Co to bude?}

{198}{}{Co se dìje ve mìstì? Dobrá... pár bláznù bylo zavøeno za roznášení pomluv. Odešel nám èistiè vzduchu v dole. Karavany dojely kam mìly. Ale to je úplnì normální.}
{199}{}{Dík. Ještì mám otázky. }
{200}{}{Dík. Mìj se.}

{201}{}{Co se dá dìlat... co se dá dìlat...no podíváme se }
{202}{}{- dále - }

{203}{}{Nìkdo pomohl tìm anarchistùm z vìzení!}
{204}{}{Nìkdo znièil dùl! Mìsto je v koncích!}
{205}{}{Všichni mutanti jsou mrtví!}
{206}{}{To bys chtìl vìdìt co.}
{207}{}{Ještì mám otázky.}
{208}{}{Ale dík. Uvidíme se.}

{209}{}{Vypadáš jako pìknì statnı chlapík. Vsadím se s tebou, e nezmlátíš Francise. Je to támhleten mutant. Podle všeho na to bude mít svùj vlastní názor. Máš zájem? Bì si s ním pokecat.}
{210}{}{Dìkuji moc. Ještì nìco jiného?}
{211}{}{Moc dík. Tak zas.}

{212}{}{Ztratilo se pár lidí a nemáme vùbec ádnou pøedstavu, kde by mohli bıt. Myslím, e by to mohlo bıt nìco pro tebe, zkusit je najít. Chtìl bys s tím zaèít? Bì si promluvit s Marcusem.}
{213}{}{Dík. Nìco jiného?}
{214}{}{Tak jo! Pokecáme si pozdìji.}

{215}{}{Hmm. Èistiè vzduchu v dole je rozbitı. Moná by sis o tom mìl promluvit s Vachym, vrchním dùlmistrem.}
{216}{}{V poøádku. Ještì nìco?}
{217}{}{Dík, uvidíme se.}

{218}{}{Rozumím, e se teï motáš kolem dolù. Jestli nìco najdeš, mìl by sis to radìji nechat pro sebe.}
{219}{}{Máš ještì nìco jiného?}
{220}{}{Dík.}

{221}{}{K èertu ano! Zkus, kam se ty dva bastardi Frank a Manson ztratili!}
{222}{}{Jsem tomu na stopì.}
{223}{}{Tak jo, uvidíme.}

{224}{}{Kadou chvíli odsud odjídí nìjaká karavana. Jestli se chceš k nìjakı pøidat zajdi si promluvit s Billem, vetešníkem. Jinak to bude asi všechno, co se dá u nás dìlat. Promiò.}
{225}{}{Dík! Ještì mám pár otázek.}
{226}{}{V pohodì. Mizim odsud, uvidíme se.}

{227}{}{Jo? Jako co?}
{228}{}{Ještì nìco k pití.}
{229}{}{Coe se dìje ve mìstì?}
{230}{}{Co je tady kolem?}
{231}{}{Nìjaké novinky?}
{232}{}{Nic. Zapomeò na to.}

{233}{}{Nechtìl jsem ti to øíkat, ale nìkteøí lidé tady nejsou rádi, e sis schoval trochu uranové rudy pro sebe. To bylo varování. Tak jako tak... co piješ?}
{234}{}{Ano.}
{235}{}{Ne. Ale ještì mám otázky.}

{236}{}{Nìkteøí lidé tady jsou naštvanı kvùli tı vìci s Chadem. Tak si to pamatuj. Chceš nìco napít?}
{237}{}{Ano.}
{238}{}{Ne. Ale ještì mám otázky.}

{239}{}{Všichni mutanti jsou mrtví. Nìkdo vyhodil dùl do povìtøí, kdy byli uvnitø. Nìkdo uvnitø volal o pomoc a oni mu bìeli na pomoc. Nìkterım lidem prostì nerozumím. Do pekla... Chceš nìco k pití?}
{240}{}{Ano.}
{241}{}{Ne. Ale ještì mám otázky.}

{242}{}{Zmiz z mıho baru, ty OPOÈÁKU.}#schválnì
{300}{}{!}
{301}{}{.}
{302}{}{Dobrá, }
{303}{}{Díky, }
{304}{}{Znovu ahoj, }
{305}{}{Hej, }
{306}{}{Zas ty, }

{307}{}{ádnı problém kámo. Tady je tvoje pití. Ještì nìco pro tebe mùu udìlat?}
{308}{}{Hele pøíteli, dík za spropitné. Tady máš nìco za to. Slyšel jsem, e Liz, majitelka hlavního obchodu, schovává nìkde ve svım skladu nìjakı dobrı bouchaèky. Ale já jsem to neøekl.}
{309}{}{Mé nekoneèné díky Phile. Nechám si to pod svım... uh... kloboukem nebo tak nìco.}
