#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš zmateného mue v laboratorním plášti.}
{101}{}{To je profesor. Vypadá, jako kdy nad nìèím usilovnì pøemıšlí.}
{102}{}{Vidíš zmateného mue v laboratorním plášti obklopeného laboratorními pomùckami. Má jiskru v oku.}
{103}{}{Zase ty?}
{104}{}{Co chceš, ztra se, jsem zamìstnanı mu!}
{105}{}{Nezamìstnanııı?}
{106}{}{Test!}
{107}{}{Kdopak jsi? A co je s tím škorpiónem?}
{108}{}{Chci zkusit nìjakı z tvıch testù.}
{109}{}{Ale nic. Sbohem.}
{110}{}{Ach, objekt k testování! Chceš si zkusit test, pøíteli?}
{111}{}{Ano!}
{112}{}{Ne!}
{113}{}{Tak testování se ti zachtìlo? Co chceš otestovat ruce, oèi nebo mozek?}
{114}{}{Ruèièky!}
{115}{}{Voèièka!}
{116}{}{Mozeèek!}
{117}{}{Nic!}
{118}{}{Tak proè potom plıtváš mım èasem? Nevidíš, e jsem zamìstnanı mu, nemám èas stát tady a plkat s cizími lidmi... a proè s tebou vlastnì ještì mluvím? Sbohem!}
{119}{}{Naschedanouuuu!}
{120}{}{Ehh... no jo. Sbohem.}
{121}{}{Chceš zkusit nìkterı z testù, co? Mùeš zkusit svoji manuální zruènost, své vnímaní anebo svou inteligenci.}
{122}{}{Tak tøeba tu zruènost.}
{123}{}{Zkusíme, jak jsem na tom s oèima.}
{124}{}{Vyzkouším si svoji chytrost.}
{125}{}{Hmm. Nic z toho. Zapomeò.}
{126}{}{Dobrá. Budeš zápasit proti škorpionovi. Mùeš zkusit odemknout tyto bedınky. Hodnì štìstí.}
{127}{}{Start!}
{128}{}{Smìle do toho.}
{129}{}{Dobrá. Postavíte se se škorpiónem támhle za tu èáru a budete èíst písmena, seshora dolù a zleva doprava.}
{130}{}{Start!}
{131}{}{Smìle do toho.}
{132}{}{Ty a škorpión budete hrát hru, kterou jsem vynalezl. Nazıvám jí "šachy". Mùeme?}
{133}{}{Ano!}
{134}{}{Jistì. Jsem v pohodì.}
{135}{}{Jsem profesor. Zkouším aplikovat testování inteligence. Vytvoøil jsem nìkolik chemickıch slouèenin k zvıšení inteligence. Hodnì u jsem toho vyzkoušel na tomhle radškorpiónovi, hned po mé chybì s kvìtinou.}
{136}{}{Vy jste nìco testoval na kytkách?}
{137}{}{Chci zkusit test.}
{138}{}{U jste udìlal nìco co funguje?}
{139}{}{Vidím. To je vše, co jsem potøeboval vìdìt. Sbohem.}
{140}{}{Samozøejmì, e jsem to zkoušel na kvìtinì! Zkoušel jsem zvıšit její inteligenci od základu!}
{141}{}{Vidím. Udìlal jste taky nìco, co by fungovalo?}
{142}{}{Chci zkusit test.}
{143}{}{To je prozatím asi vše.}
{144}{}{Ano, dìkuji ti mnohokráte! Øíká ti nìco pojem "Mentat"? Pomohl jsem objevit metodu na jednoduchou masovou produkci té drogy! Ale i jiné vìci! Mnoho!}
{145}{}{No tak dobrá, chci si vyzkoušet své schopnosti proti tvému škorpiónu.}
{146}{}{No jo, tak ti vìøím, u musím jít.}
{147}{}{Jak... jak si jen mohl zabít mého škorpióna? U jsem byl blízko... tak blízko...}
{148}{}{Vodprejsni}

# Agility Test
{200}{}{Coeto! Porazit tohohle pana bezpáteøního.}
{201}{}{Cooooooo Toooo!}
{202}{}{Krucinál!}
{203}{}{Grrrr!}
{204}{}{::klik klak::}
{205}{}{Jak si to mohl otevøít klepetama?}
{206}{}{Jaks to dokázal jen s klepety?}
{207}{}{::píp::}
{208}{}{Dobrá, to bylo tak tak.}
# The following 4 strings are used in the phrase:
# "You lose. Scorpion: [SCORE], [Player Name]: [SCORE]."
{209}{}{Prohráváš. Škorpión: }
{210}{}{, }
{211}{}{: }
{212}{}{.}
{213}{}{Jùùùù?}
{214}{}{Zjišuješ, e jsi hbitìjší ne radškorpión.}
{215}{}{Tady, vem si ten Mentat. Vypadáš, e ho potøebuješ.}

# Perception Test
{300}{}{E...Z...W...T...O...D...F...E..R...T...F...P...Y...J...M}
{301}{}{Ano, to je správnì.}
{302}{}{B...u...u...Buu?}
{303}{}{Uh...ne. Je mi líto, seš úplnì vedle.}
{304}{}{::píp písk:: ::klik klak:: ::cvrliky (step s noièkama)::}
{305}{}{Správnì! Hodnı! Hodnı chlapec! Umíš opravdu dobøe pouívat morseovku.}
{306}{}{Zjišuješ, e jsi vnímavìjší ne radškorpión.}

# Intelligence Test
{400}{}{Šach-mat ::klik::}
{401}{}{Coe? Ty jsi podvádìl!}
{402}{}{Mat?}
{403}{}{Èlovìèe nezlob se.}
{404}{}{a...šach-mat!}
{405}{}{Šaaach-mat!}
{406}{}{::píp:: Zabít KYTKU! ::klik-klak-klik::}
{407}{}{Zjišuješ, e radškorpión je chytøejší ne ty a e pøed ním neobstojíš.}
