#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš tajuplnou mutantí vìc se skvrnitou kùí a pøíšernım úsmìvem.}
{101}{}{To je šéf rafinérie.}
{102}{}{Vidíš ghoula. Jeho kùe vypadá jako staená z nìjakého zvíøete. Taky to vypadá, e ho ostatní lidé jak tak akceptují.}

{103}{}{Tady nemáš co dìlat!}
{104}{}{Co chceš?}
{105}{}{Da yagga! Eep oop op!}
{106}{}{Dunno.}
{107}{}{Mám tady nìjakou rudu k rafinaci.}
{108}{}{Kdo jsi?}
{109}{}{Co je tohle za místo?}
{110}{}{Chci nìjakı uran.}
{111}{}{Nic.}
{112}{}{Nech to plavat. Nashle.}

{113}{}{Podívej, synku, je mi docela líto, e jsi slabomyslnı, ale tady nemùeš bıt. Utíkej odsud.}
{114}{}{-dál-}

{115}{}{Tady nemùeš bejt, je to nebezpeèné, mazej odsud.}
{116}{}{-dále-}

{117}{}{Skvìlé to bude za $1000, bez smlouvání. Mùeš si myslet, e to je pøedraenı, ale uva co by za hotovı produkt dal jinı zájemce.}
{118}{}{Ujednáno.}
{119}{}{$1000? To je docela hodnì. Zapomeò na to.}

{120}{}{Jsem šéf rafinérie. Co si pøeješ?}
{121}{}{Co je to za místo?}
{122}{}{Chci rafinovat nìjakou rudu.}
{123}{}{Sháním nìjakej uran.}
{124}{}{Nic.}

{125}{}{Tohle je Brokenhillská rafinerie. Tady proèišujme rudu vytìenou v dole. Co chceš?}
{126}{}{Co je to za místo?}
{127}{}{Chci rafinovat nìjakou rudu.}
{128}{}{Sháním nìjakej uran.}
{129}{}{Ale nic.}

{130}{}{Nemáš dost penìz, vra se, a budeš mít.}
{131}{}{-dál-}

{132}{}{V poøádku. Dej nám den, dva a my to pro tebe budeme mít pøipraveno.}
{133}{}{Skvìlé. Na vidìnou.}

{134}{}{Pøeji hodnì štìstí nìkde jinde. Ten proces je nebezpeènı - a mìl by to dìlat jen profesionál. Chceš to nebo ne?}
{135}{}{Jo.}
{136}{}{Ne.}

{137}{}{Dobrá, mám tady ještì nìjakou práci. Prosím tì pøijï a budu mít èas.}
{138}{}{Nashle.}

{139}{}{To je smìšné. Nedostaneš nic.}
{140}{}{Potom si zaèni kopat hrob.}
{141}{}{Fajn. Mìj se.}

{142}{}{Hej! Hned odsud zmiz nebo z toho budeš mít velkou bolest!}

{143}{}{Okamitì zmiz z mojí rafinérie!}

{144}{}{Stále na tom dìláme. Dej nám ještì èas. To není jako chovat vèely.}
{145}{}{Chtìl bych se tì na nìco zeptat.}
{146}{}{Fajn. Za chvíli.}

{147}{}{ Tvoje ruda je hotová. Pøedtím, ne si jí vezmeš, poslouchej - naše mìsto tuhle rudu opravdu potøebuje. Pokud jí navrátíš mìstu, dostaneš zpìt své peníze. Co mi na to povíš?}
{148}{}{Ale nepøehánìj.}
{149}{}{Tak dobrá.}

{150}{}{Tak dobrá, tady máš svoji rudu. A teï odsud zmiz.}
{151}{}{Èau.}

{152}{}{Dìkuji! Tady máš zpìt své peníze.}
{153}{}{To je boí. Dík.}
