#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš a kytku.}
{101}{}{To je kvìtina Seymour.}
{102}{}{Vidíš kvìtinu, ze které sem tam vyzaøuje inteligence.}
{103}{}{Ahoj! Dneska máme pìkné poèasí,e?}
{104}{}{Tııı mluvíííš?}
{105}{}{RRR?}
{106}{}{Promiòtee, ale není to náhodou ta mluvící kvìtina?}
{107}{}{Máš nìjaké spojení s tamtím vìdcem?}
{108}{}{Nashledanou.}
{109}{}{Ale ano, umím mluvit. Nejlíp mi to jde s lidmi. Usmála bych se na tebe, ale nemám ádná ústa. [smìje se] Povìz, mohl bys pro mì nìco udìlat?}
{110}{}{Ale jo.}
{111}{}{Radìji ne.}
{112}{}{Hledám lepší místo pro ivobytí. Tady je sice moc hezky, ale není tu s kım pokecat a já si hroznì ráda povídám. Myslela jsem na nìjaké místo blízko budov, tøeba támhle, kde jsou ti staøí ghoulové... Mùeš mì pøesadit?}
{113}{}{Jo!}
{114}{}{Ne!}
{115}{}{Jistì.}
{116}{}{Myslím, e ne.}
{117}{}{Tak to je skvìlé! Jedinı co potøebuješ, je najít nìjakou lopatu, vykopat mì a zasadit nìkde támhle. Kdy to udìláš, povím ti tajemství.}
{118}{}{Tak jo!}
{119}{}{A just ne.}
{120}{}{V pohodì. Take, um... Já tu na tebe poèkám, stejnì nemùu dìlat nic jiného. Navidìnou!}
{121}{}{Sbohemmm!}
{122}{}{Jestli náhodou zmìníš názor, víš kde mì najdeš. Zapustím tady koøeny. Ha ha ha! Jen trochu kvìtinového humoru, tak nezapomeò na mì. Ahoj!}
{123}{}{Nashledanou.}
{124}{}{Dobøe øeèeno! Jak delikátnì umí homo sapiens pouívat svùj mozek. Mùj drahı pøíteli, chtìl bys pro mì nìco udìlat?}
{125}{}{Jo.}
{126}{}{Ne!}
{127}{}{Co øíkáš, vùbec ti není rozumìt, zkus mluvit tak jak tì to uèili ve škole, pìknì spisovnì a tak aby ti bylo rozumìt! Mùj pøechytralı kamaráde, nevadilo by ti, kdybys pro mì nìco udìlal?}
{128}{}{Jistì.}
{129}{}{Nemyslím.}
{130}{}{Jak okouzlující! Jsem velmi potìšena. Nejdøív najdi sám sebe a pak lopatu a vra se sem. Kdy to udìláš, moná ti povím tajemství. Doufám, e ti nebude vadit, takové malé pøátelství s kvìtinou.}
{131}{}{Um, Tak jo. Navidìnou.}
{132}{}{Zmìnil jsem názor.}
{133}{}{Óoo ano, profesor. Vychoval a hıèkal mì od malého semínka... jene od ranného vìku jsem dìlala chytøejší ne ve skuteènosti jsem, a tak, aby mì znièil, mì chtìl rozsekat na malé kousky. A tak jsem radìji hrála hloupou a skonèila jsem tady. Je tu pìknì... ale chtìla bych se trochu víc rozrùst. Moná, kdybych byla nìkde jinde...}
{134}{}{"Rozrùst." povídáš.}
{135}{}{A co by sis pøála?}
{136}{}{Hmm...radìji pùjdu. Tak zas nìkdy.}
{137}{}{Ještì má toho škorpióna? Ta vìc docela obstojnì ovládá šachy... je trochu vznìtlivı a neumí prohrávat, jestli rozumíš o èem mluvím... ale vím jak ho porazit. Kdy po mì nìco udìláš, øeknu ti jak.}
{138}{}{Vánì? Jak?}
{139}{}{To je úasné. Kytka co hraje šachy. To jsem asi ve snu. Navidìnou.}
{140}{}{Mùj milı pøíteli, kdy mì zasadíš blízko támhletoho domu s ghoulama, budu šastná a na oplátku ti svìøím svou nejtajnìjší šachovou taktiku.}
{141}{}{Ujednáno.}
{142}{}{Ne dík. Porazím ho i bez cizí pomoci.}
{143}{}{O pøíteli, vrátil ses. Tohle místo je prostì skvìlé. Ten stín je tu perfektní a spoleènost skvìlá. Ten Typhon je obstojnı vtipálek! Opravdu si tady zvıším svoje IQ!}
{144}{}{Šachy?}
{145}{}{A co ta tvoje zmínka o šachách?}
{146}{}{Sbohem.}
{147}{}{Dobrá, nyní si popovídáme o tom jak zdrtit profesorova škorpióna v šachách. Je ti jednoduché jako facka. Ten degenerovanı poíraè broukù vdycky skoèí na Útok letících jater - pøímo do toho vpochoduje a pak se nemùe vyplést. Garantuju ti 100% úspìch.}
{148}{}{Dík moc! Mìj se!}
{149}{}{Oceòuji tvé informace! Sbohem!}
{150}{}{Pøíteli! Doufám e slunce svítí na kadı tvùj krok? Není náhodou den kvìtin? Jsi pøipraven na pochod? Já ano!}
{151}{}{Jo!}
{152}{}{Ne! ádnı pohyb!}
{153}{}{Jdem.}
{154}{}{U ti nechci pomoct.}
{155}{}{Jsem dokonale vzrušená, kdyby ses podíval blí, vidìl bys mrak semen kolem mì! Tak jdem!}
{156}{}{-dále-}
{157}{}{Tak to je docela smùla. Doufám, e nìkdy zmìníš svùj názor. Doufám, e se naše cesty nìkdy zase zkøíí. Nashledanou.}
{158}{}{Uf.}
{159}{}{Dobrı den pøeji.}
{160}{}{Oooh... pùda tady je taková... jiná. Èistší, nebo tak nìco. Asi pro to, e jsem zde úplnì sama. Ahhh. Málem bych zapomnìla! Jestli se nìkdy utkáš s profesorovım škorpiónem, zapamatuj si tenhle šachovı manévr: Jmenuje se Útok letících jater a on proti tomu neobstojí.}
{161}{}{Dík!}
{162}{}{Dìkuji, to budu muset vyzkoušet. Nashledanou!}
{163}{}{Moná by se ti líbilo, kdybych ti øekla e Typhon uvnitø téhle chajdy poøád plácá nìco o nìjakém pokladu. Moná by se ti to mohlo nìkdy hodit.}
{164}{}{Dìkuji, uvidíme se!}
{165}{}{U si se rozmyslel? Chceš mi tedy pomoct?}
{166}{}{Jo!}
{167}{}{Ne!}
{168}{}{Jistì.}
{169}{}{Nemyslím si.}
{170}{}{Sbohem a šáteèek, nezdá se mi, e máš u sebe lopatu. Neudìláme s tím nic, dokud nìjakou nenajdeš. Budu èekat, a se vrátíš ze svìta.}
{171}{}{Sbohem.}
{172}{}{Psst! Halo! Halo, pøíteli! Tady!}
{173}{}{Pojï ke mnì blí! Slibuji, e ti neublíím.}
{174}{}{Ale, takovı velkı chlapák a bál by se kytky?}
{175}{}{Tady! Jdem na to!}
{176}{}{Ano, jsem mluvící kvìtina. Zkus to a promluv se mnou.}
{177}{}{Pøíteli, momentíèek. Døív ne zaèneš kopat, mìli bychom upøesnit naší strategii.}
{178}{}{Zasazuješ Seymour u ghoulského domova dùchodcù.}
{179}{}{Lopata tady! Kytka tam!}
{180}{}{No co se nestalo, jdu takhle po poušti a najednou vidím.. hele lopata. Tak jdem na to.}
