#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš usmìvavého mue, obleèeného v koeném brnìní.}
{101}{}{To je Steve, místní uvítací vıbor.}
{102}{}{Vidíš pøátelského chlapíka v koeném brnìní. Vypadá, jako kdy tu èeká celı den, jen aby s nìkım pokecal.}

{103}{}{Vítej! Jsem Steve. Mohu ti øíci co a jak u nás ve mìstì. Mohu tì nìkam nasmìrovat nebo nìjak jinak pomoci?}
{104}{}{Co e to...}
{105}{}{Boken Hils?}
{106}{}{Øekni mi o tomhle místì.}
{107}{}{Kdo tu ije?}
{108}{}{Kdo je tu šéf?}
{109}{}{Nìjaké novinky?}
{110}{}{Máte tu nìjaké sluby?}
{111}{}{Nic. Dík.}

{112}{}{O boe, další dítì z pustin. Dobrá, vítej. Brzy zjistíš, e jsme asi nejlepší mìsto v okolí.}
{113}{}{Dobrééé!}

{114}{}{Opravdu. Mnoho štìstí, poutníku. Nashle.}
{115}{}{Nahle!}

{116}{}{Broken Hills. Jsme hornické mìsto. Dobıváme vìci v zemi a pak je prodáváme.}
{117}{}{Dobıvat?}
{118}{}{Dávat!}

{119}{}{Správnì, máme vlastní dùl. Ale nemyslím, e by se v nìm pro tebe našla práce. Jestli chceš makat, jdi za vetešníkem.}
{120}{}{O-kej.}
{121}{}{Prodávat zboí?}

{122}{}{Prodáváme co vykopeme ostatním mìstùm. Jim se to hodí. Kdy chceš nìco koupit, mùeš si promluvit se spoustou obchodníkù co tady máme. Jinak se musím vrátit do práce. Mìj se a dávej si bacha?}
{123}{}{O-kej!}

{124}{}{Musím se vrátit do práce. Mìj se dobøe a dávej si tady bacha!!}
{125}{}{Zase ty? Víš co máš dìlat -- nezlobit. Opatruj se!}
{126}{}{O-kej!}

{127}{}{Schovej tu bouchaèku, paráku. Asi nechceš nic vìdìt, kdy se tu potuluješ takhle s prstem na spoušti.}

{128}{}{Jsme malá tìební komunita. Tohle místo našel pøed mnoha lety náš šerif Marcus spoleènì s muem jménem Jacob. Tihle dva vybrali tohle místo, protoe je to blízko loisek uranu. Chceš o tom slyšet víc?}
{129}{}{Ano.}
{130}{}{Ani ne.}

{131}{}{Jsme skupinka lidí, mutantù a ghoulù. Nemáme proti sobì ádné rasové pøedsudky, jako tøeba v tom pobláznìnım Vault City; pro nás jsou si všichni rovni.}
{132}{}{ijete dohromady s mutanty? A nemyslíte si, e jsou zlí?}
{133}{}{Rovni?}
{134}{}{To mi staèí. Mìj se.}

{135}{}{Náš šerif Marcus je povìøenı dbát na poøádek ve mìstì. Dal tomu všemu vzniknout a taky nám pomohl s našimi problémy. No a taky - kadı ve mìstì, má hlas.}
{136}{}{To vypadá neproveditelnì.}
{137}{}{To zní opravdu jako velmi dobrı pokus.}
{138}{}{Ale no tak.}
{139}{}{Èlovìk co stvoøil mìsto je stále ve slubì? To mu muselo opravdu pøidat na létech.}
{140}{}{Dík. Nashle.}

{141}{}{Bez ohledu na to, e by všichni mutanti byli mrtví a tohle mìsto by bylo znièeno...}
{142}{}{Bez ohledu na to, e by všichni mutanti byli mrtví a náš jedinı zdroj ivobytí znièen...}
{143}{}{Bez ohledu na to, e by ses stal hrdinou za to, e jsi odkryl korupci...}
{144}{}{Bez ohledu na to, e nìkdo z našich obèanù má nìco spoleèného s Frankem a Mansonem...}
{145}{}{Bez ohledu na Chadovu zradu mìsta a náš zákon - kterı je pro kadého skvìlı -- }
{146}{}{V souèasné dobì se nedìje nic zvláštního.}
{147}{}{Mám ještì pár otázek.}
{148}{}{Nashle.}

{149}{}{Ale, zase ty.}
{150}{}{Zdravím.}
{151}{}{Vítej zpìt.}
{152}{}{Chceš vìdìt více?}
{153}{}{Nìjaké novinky?}
{154}{}{Kdo tu šéfuje?}
{155}{}{Povìz mi o tomhle místì.}
{156}{}{Kdopak tu ije?}
{157}{}{Máte tu nìjaké sluby?}
{158}{}{Ale nic.}

{159}{}{Náš ivot je spojen s dobıváním rudy z nedalekıch kopcù, tu pak prodáváme do nejbliších mìst jako jsou tøeba Vault City, Gecko a New California Republic. Trochu taky vyuíváme pro vlastní spotøebu. Chceš vìdìt víc?}
{160}{}{Ale jo.}
{161}{}{Radìji ne.}

{162}{}{Všichni jsou si rovni. Všichni jsme vznikli z èlovìka; pod vnìjší slupkou se skrıvá stejné jádro. Øíkat o nìkom, e je zlı jen podle toho jak vypadá, mùe jen ignorant.}
{163}{}{Ty mì nazıváš ignorantem?}
{164}{}{To je pravda.}
{165}{}{To nemusí bıt pravda. Kdo mùe vìdìt, co udìlal virus, kterı jim zmutoval jejich mysl?}
{166}{}{Neudìláš nic. Mìj se.}

{167}{}{Zjistili jsme, e pro naše úèely to funguje skvìle. Navíc je Marcus pozoruhodnì férovı.}
{168}{}{Kde najdu Marcuse?}
{169}{}{Nashle.}

{170}{}{Je starı. Ale stále vypadá dobøe. To víš, je mutant a ti vydrí ít o trochu déle ne my.}
{171}{}{Necháte MUTANTY øídit tohle místo? To jste cvoci nebo co?}
{172}{}{Vánì? Mám takovı pocit, e vìtšina z nich vymøela.}
{173}{}{A mutantskı šerif, heh? To musí fungovat skvìle. Hodnì lidí tady musí dodrovat zákon.}
{174}{}{Sbohem.}

{175}{}{Jsme tady trochu stranou od normálního ivota, vytvoøili jsme si vlastní styl civilizace a dìláme co nejvíc, abychom se vyhnuli chybám Vault City nebo NCR - nepotøebujeme princip jejich vlády. A to je asi vše.}
{176}{}{No to je skvìlé. Chci se ještì na pár vìcí zeptat.}
{177}{}{Dík. Tak zase nìkdy.}

{178}{}{Jestli vìøíš, e mùeš soudit mysl nìkoho, podle toho co vidíš navenek, tak jo. Potom jsi neuvìøitelnı ignorant.}
{179}{}{Táhni do pekla, drzoune. SÁM jsi ignorant.}
{180}{}{Ale, no tak. Jaká pak to zajímavá pointa.}

{181}{}{Tak to je asi vše, co jsem ti chtìl øíct, vítej v Broken Hills.}
{182}{}{Poèkej.}
{183}{}{Mìj se.}

{184}{}{Jak pro nás mutanti mùou pøedstavovat zlo, kdy sem pøišli s námi. Nikdo z nich tu nebyl první a ve skuteènosti je vìtšina z nich u stejnì senilní. Dokonce bychom to tady bez jejich znalostí a pomoci ani nepostavili.}
{185}{}{Zajímavá úvaha.}
{186}{}{Jsou stále zlí.}
{187}{}{Naschle.}

{188}{}{Èlovìèe, èím víc s tebou mluvím, tím víc na mì pøelézá tvoje blbost. S takovıma názorama u nás dlouho nevydríš. A teï mì omluv, mám ještì nìjakou práci.}
{189}{}{Mìl by sis dávat pozor na jazyk, ne nìkomu selou nervy.}
{190}{}{Je èas zemøít, pitomeèku.}

{191}{}{Máme dùl, rafinérii, hospodu, hotel - jeho majitel ale zmizel, take v nìm necháváme lidi zadarmo -- nemocnici, hlavní obchod a chemika. Taky si pìstujeme vlastní jídlo.}
{192}{}{To je skvìlé. Mám ještì otázky.}
{193}{}{Navidìnou.}

{194}{}{Spousta mutantù je neplodnıch... nebo tomu alespoò vìøím ... a pomalu umírají. Jedinı, kdo vypadá, e je opravdu v pohodì, je Marcus. Ten má stále šmrnc.}
{195}{}{Kde ho najdu?}
{196}{}{Mám další otázky.}
{197}{}{Uvidíme se.}

{198}{}{Marcusi, jsi si jistı, e nás tu necháš o samotì? Teï tu nebude nikdo, kdo by nás vedl a hlídal.}
{199}{}{Marcus: O to strach nemám. Teï vám to tu pùjde i beze mne.}
{200}{}{-dál-}

{201}{}{Èlovìèe, nejsi tu vítán. U si toho dost zjebal.}
{202}{}{-dále-}

{300}{}{Marcuse urèitì najdeš blízko Banky - ta nám slouí souèasnì jako vìzení - a nebo v ní. Nìkdy taky bıvá v hospodì nebo doma, ale stejnì neustále pracuje.}

{301}{}{Bambule!}
{302}{}{Do pr..ahy!}
{303}{}{Huráá!}
{304}{}{Krleš!}
{305}{}{Ten zparchantìlej hajzl!}