#tento soubor pøeloil Vachy - http://vachy.moje.cz
#teda Vachy tohle jsi pøeloil pøíšernì... by Somnambulus
{100}{}{Vidíš vysokého prošedivìlého mue s korbelem piva.}
{101}{}{Vidíš John L. Sullivana. Zápasníka.}
{102}{}{Vidíš vysokého starého mue se svalnatımi paemi a šedivım, dobøe udrovanım, knírkem.}
{103}{}{Teï u jsi na tom trochu líp.}
{104}{}{Sakra, nejsi náhodou tak trochu blbej?}
{105}{}{To s tím Torrem, to byla dobrá práce.}
{106}{}{Nazdar, mròousku.}
{107}{}{Ach jo, další domorodec se slámou v botách.}
{108}{}{(Kriticky tì pøejede pohledem odzdola nahoru) Podívejme, copak to tu máme? Zdá se, e ty toho o sladkı vìdì moc nevíš, co?}
{109}{}{Kdy si pohneš tím svım línym zadkem, moná tì mùu ledacos nauèit.}
{110}{}{O èem to mluvíš?}
{111}{}{No jo, jasnì, mistøe. Nashle. Moná...}
{112}{}{No je to jen mùj odbornı názor, ale vidím na tobì, e se máš ještì dost co uèit.}
{113}{}{Uèit? A co?}
{114}{}{Nemyslím, starouši. Pochybuju e *ty* mì mùeš nìco nauèit. Sbohem.}
{115}{}{O tı sladkı vìdì. O sportovním umìní.}
{116}{}{Umìní? Ty mluvíš o magii!?! Mùeš mì nauèit nìjaká kouzla?}
{117}{}{O èem to mluvíš?}
{118}{}{(ušklíbne se) No jistì, mùu ti ledacos povìdìt o skøítcích, vílách a upírech a tak. Máš zájem?}
{119}{}{To zní skvìle. Pouè mì.}
{120}{}{Box, to je umìní pìstního boje. To je to, co mám na mysli.}
{121}{}{Box, je muskı, uh, a i enskı zpùsob boje beze zbranì. To je to co mám na mysli.}
{122}{}{Dobrá, moná e s tímhle potøebuju trochu pomoct.}
{123}{}{No mám takovı dojem, e u mì zrovna ty nemùeš nic nauèit.}
{124}{}{(obrátí se k ostatním) Slyšeli jste to? U tady iju dlouho, ale tohle jsem ještì nezail. Chce slyšet o bludièkách a goblinech. (Hoho, hahaha, haha-hehehe ::smìje se èím dál víc::) Tady, chlapèe dej si na mì panáka, to je tvùj lístek do nevìdomí.}
{125}{}{(obrátí se k ostatním) Slyšeli jste to? U tady iju dlouho, ale tohle jsem ještì nezail. Chce slyšet o bludièkách a goblinech. (Hoho, hahaha, haha-hehehe ::smìje se èím dál víc::) Tady, dìvèe dej si na mì panáka, to je tvùj lístek do nevìdomí.}
{126}{}{Všechno co potøebuju je chlast? To je skvìlé, dík za tip.}
{127}{}{Mám takovı zvláštní pocit, jako kdyby sis ze mì dìlal srandu.}
{128}{}{No, ten chlast je jen zaèátek. Co takhle pokusit se najít kouzelnı kolo? (mrká na okolosedící štamgasty)}
{129}{}{A jak?}
{130}{}{No to si sedneš na zadek a èekáš, dokud neuvidíš kouzelnej kruh z rosy. A kdy pak skoèíš do toho kouzelnıho kruhu, budeš muset tancovat a do rozbøesku. A kdy to pøeiješ, potom tì víly odnesou do svı zemì. (heee, hah, hah, hah)}
{131}{}{jùva, a jak jsi to dokázal ty?}
{132}{}{Se mi zdá, e si ze mnì dìláš prdel.}
{133}{}{Oho, já to mám v krvi. Hej, ještì jednoho panáka! (otoèil do sebe jeden pùllitr)}
{134}{}{Jasnì. Dík za tip. Hele, mùu se tì zeptat na nìco jinıho?}
{135}{}{Se mi zdá, e si ze mnì dìláš prdel.}
{136}{}{No jo, vidím, e jsi zamìstnanı mu. Uvidíme se pozdìji. Na vidìnou.}
{137}{}{(Prohlíí si tì) No uvidíme. Uvidíme. Tak si odlo.}
{138}{}{Udìlám to. Sbohem.}
{139}{}{No moná, e jo. Ale vypadá to, e ty to bereš sportovnì. Dej si na mì pivko.}
{140}{}{Dìkuju. Tak cos to povídal o tı sladkı vìdì?}
{141}{}{Nechci od tebe ádné pivo. Vím toho víc, ne by si mì mohl nauèit ty, ty starej voralo.}
{142}{}{Dobrá, pojï ven a uvidíme, co bych tì mohl nauèit. Uvidíme, jak se umíš otáèet...}
{143}{}{Eh, dobøe.}
{144}{}{Teï na to bohuel nemám èas. Sbohem.}
{145}{}{(o nìkolik upocenıch hodin pozdìji) Tak teï u chápeš, v èem byly tvoje hlavní nedostatky?}
{146}{}{Ano, vidím. Dík, e jste obìtoval èas, abyste mi pomohl, pane Sullivane.}
{147}{}{To bylo úasné. Chci vám nechat $10 jako vyjádøení mého obdivu. Je to maximum, co vám mùu dát.}
{148}{}{Ano a dìkuji. Sbohem.}
{149}{}{Bylo mi potìšením. Opatruj se. A kdy se tì kdokoli zeptá... øekni mu, e takhle bojovat, tì nauèil staroch John Sullivan.}
{150}{}{Udìlám to, Johne. Dìkuji. Sbohem.}
{151}{}{Ne, ne, ne. Nechci od tebe ádné peníze. Bylo pro mì potìšením pøedat ti své znalosti. Dávej na sebe pozor, nìco v tobì je.}
{152}{}{To je skvìlé, mùu se tì na nìco zeptat. Kde ses nauèil takhle bít?}
{153}{}{Díky Johne. Sbohem.}
{154}{}{To u je pìknì dávno. Kdy jsem ještì byl mlíèòák a moc jsem toho v hlavì nemìl. Na místì co se jmenuje Reno. Radìji se od nìj dr dál a zùstaneš v pohodì.}
{155}{}{Kde je to Reno?}
{156}{}{OK a dík Johne. Nashledanou.}
{157}{}{To ti radši nepovím. Jsi na tom docela dobøe, jen si dej pozor, a nesejdeš na špatnou cestu. Sbohem.}
{158}{}{Ještì jednou dík a na vidìnou, Johne.}
{159}{}{Zkus se vyhıbat prùserùm. Nauèil jsem tì všechno, co jsem umìl.}
{160}{}{Dík. Pøedtím jsi øíkal nìco o nìjakém umìní?}
{161}{}{Dík Johne. Opravdu to oceòuji. Sbohem.}
{162}{}{Mìl jsem na mysli umìní pìstního boje. S tamtìma vìcma jsem si z tebe dìlal jen legraci. A teï se asi zase radši vrátím ke svı sklenici. Hodnì štìstí.}
{163}{}{Tak jo, dík, Johne. Sbohem.}
{164}{}{John Sullivan ti pomohl zvıšit tvoje schopnosti v boji zblízka a v boji chladnımi zbranìmi.}