#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš starého ghoula.}
{101}{}{To je Typhon, uctívaè Seta.}
{102}{}{Vidíš starého ghoula, ze kterého vyzaøuje inteligence.}
{103}{}{Ahoj, prcku, vítej v "Ghoulském domovì dùchodcù"!}
{104}{}{Coe? Ghul?}
{105}{}{"Ghoulském domovì dùchodcù"?}
{106}{}{Kdo jsi?}
{107}{}{Hele, u si nìkdy slyšel o GECKu?}
{108}{}{Ahoj.}
{109}{}{Další dítì divoèiny, co? Hele, chceš slyšet tajemství?}
{110}{}{Samo!}
{111}{}{Ani ne.}
{112}{}{Je tomu u hodnì dávno, co jsem závodil ... a vyhrával. Je tomu u hodnì dávno co jsem celou svou vıhru ukryl nedaleko odsud. Kdy mi nìkdo prokáe jednu, dvì laskavosti, moná mu povím, kde to je.}
{113}{}{Povídej!}
{114}{}{Ale no tak.}
{115}{}{Jakıpak druh pokladu?}
{116}{}{Jakou laskavost?}
{117}{}{Ještì mám otázky.}
{118}{}{Mìj se!}
{119}{}{Heh. Dobrá, ale potom pro tebe nic nemám, padej.}
{120}{}{Nashle.}
{121}{}{Potøebuji od tebe nejprve nìjakou slubu.}
{122}{}{V pohodì!}
{123}{}{Tak na to zapomeò!}
{124}{}{Co je to?}
{125}{}{Zapomeò na to.}
{126}{}{U jsem starı mu a nepotøebuji toho moc. A navíc u nemám ani šanci si uít, jestli víš co myslím? Take bych chtìl èasopis Koèièí Packa. Pøines mi nìjakı.}
{127}{}{Na! [podáváš Koèièí Packu Typhonovi]}
{128}{}{OK!}
{129}{}{Ne!}
{130}{}{Uij si to. [podáváš Typhonovi Koèièí Packu]}
{131}{}{V poøádku. Já se vrátím.}
{132}{}{Zapomeò na to.}
{133}{}{Dík za ten èasák, dítì. Teï mì nech a vra se za pár hodin.}
{134}{}{V pohodì!}
{135}{}{Sakra, ještì jsem neskonèil! Copak nemùu mít trochu soukromí?}
{136}{}{-dál-}
{137}{}{Jakı druh pokladu? Prachy, dítì, moc penìz. Dost na to, aby to kohokoli uspokojilo.}
{138}{}{A vo co jako de?}
{139}{}{Nepotøebuji prachy.}
{140}{}{U si zpìt? Chceš vìdìt, kde je pokládek, dítì?}
{141}{}{Jo, jo, jo!}
{142}{}{Ani ne.}
{143}{}{Jakı druh pokladu to je?}
{144}{}{Ano, povídej.}
{145}{}{Nejdøív mám nìjaké otázky.}
{146}{}{No.}
{147}{}{Jako co?}
{148}{}{Tohle je "Ghoulskı domov dùchodcù"?}
{149}{}{U si slyšel nìco o GECK?}
{150}{}{Kdo jsi?}
{151}{}{Ještì nìco mi mùeš øíct?}
{152}{}{Je to takovı vtípek, tady toti jsou jen staøí ghoulové. Všichni jsme sterilní a ijeme u pìknì dlouho. Jsme první a poslední generace ghoulù. Tohle je místo pro ty z nás, kteøí u chtìjí jen odpoèívat.}
{153}{}{Hmmm. Mám další otázky.}
{154}{}{U vím dost. Ahoj.}
{155}{}{Jsem Typhon. U ti nìkdy nìkdo vyprávìl o Setovi? Kdysi dávno byl uctíván ve mìstì Necropolis. Jsem jeho syn. Narodil jsem se pøed tím, ne nás zasáhla radiace, teprve potom jsem zmutoval. Nikdy pro mì nebyla lepší cesta.}
{156}{}{Povìz mi o Setovi.}
{157}{}{Set? To prı byl pìknej hajzl!}
{158}{}{Uvidíme. Teï mám další otázky.}
{159}{}{Tak nic. Navidìnou.}
{160}{}{Ale jo. Kdysi dávno jsem jeden mìl, ale hrozní lidé mi ho ukradli, aby jej pouili pro sebe. Nejlepší by bylo zkusit to ve Vault City. Anebo snad ještì v NCR na jihu.}
{161}{}{Sakra. No, mám ještì pár otázek.}
{162}{}{K ïasu. Tak se mìj.}
{163}{}{"Pìknej hajzl"... hmmm, to je asi fakt nejlepší øíct o starım chlapovi, co u neije a pøitom ho vùbec neznat. A bejt promìnìnı v ghoula díky pùsobení radiace ti moc na autoritì nepøidá. Spíš k smíchu. Hele poslouchej, nìco ti povím, protoe pøece jen mùj mozek toho ví víc ne tvùj - myslím si, e jako ghoulovi se mi ije lépe.}
{164}{}{Dobrá. Ještì mám otázky.}
{165}{}{Dík. Ahoj.}
{166}{}{Tak co, u máš mojí Koèièí Packu?}
{167}{}{Ale jo. (Typhon od tebe dostal Koèièí Packu)}
{168}{}{Zatím ne.}
{169}{}{Ale no jo, tady. [Dáváš Typhonovi Koèièí Packu]}
{170}{}{Ještì ne. Chci se ještì zeptat...}
{171}{}{Ne.}
{172}{}{Dobrá, tak si pospìš! Jsem starı ghoul a øíkám ti e potøebuju odpoèinek! Teï bì!}
{173}{}{-dále-}
{174}{}{Dítì, ten èasák mi rozproudil krev v ilách a pøipomnìl mi, e kvùli pokladu 'o kterém jsem mluvil' bych potøeboval ještì nìco. Pøines mi nafukovací pannu. Urèitì nìjakou najdeš v New Renu.}
{175}{}{Tak jo! Uvidíme se!}
{176}{}{To teda ne!}
{177}{}{Tady je! [podáváš Typhonovi nafukovací pannu]}
{178}{}{V pohodì. Ještì jednu otázeèku.}
{179}{}{Tak jo. Ahoj.}
{180}{}{Zapomeò na to.}
{181}{}{Mám jí právì tady. (Typhon od tebe dostal nafukovací pannu)}
{182}{}{Tak tohle, dítì, dokáe vzpruit. Dej mi trochu èasu a pak si promluvíme. Teï jdi. [V jeho oèích se zraèí chtíè]}
{183}{}{-dál-}
{184}{}{To nemùu mít trochu soukromí! Mlask! Mlask!!}
{185}{}{-dál-}
{186}{}{Tak jsem se poøádnì "utahal" a kdy mi pøineseš lahvinku Rot Gutu, pokecáme si o pokladu. Obchodník Phil moná bude mít nìjakou schovanou.}
{187}{}{Nashle ty vydìraèi!!}
{188}{}{Ne!}
{189}{}{Vezmi si to! [dáváš Rot Gut Typhonovi]}
{190}{}{Tady máš. (Typhon dostal Rot Gut)}
{191}{}{Tak o to ti šlo?}
{192}{}{V pohodì. Mìj se.}
{193}{}{Zapomeò na to.}
{194}{}{Ještì bych chtìl... nìjakou vìc. Øeknu ti co chceš slyšet, kdy mi pøineseš lahvinku Rot Gutu, OK?}
{195}{}{V poøádku. Udìlám to.}
{196}{}{Tak na to zapomeò kámo.}
{197}{}{Tak to mi fakt pomohlo dítì. Chtìl jsem po tobì ještì nìjakou kytku, ale u ti dám pokoj.}
{198}{}{Dík moc!}
{199}{}{Dìkuju. Ještì mám otázky.}
{200}{}{Je to trochu nejasné, ale stejnì dík. Uvidíme se.}
{201}{}{U máš ten poklad, dítì?}
{202}{}{Byl nadosah.}
{203}{}{Ještì ne.}
{204}{}{Ne. Mám otázeèku.}
{205}{}{Ne, ne. Ahoj.}
{206}{}{Ještì ho hledám. Jen aby to nedopadlo jak ve Štìchovicích.}
{207}{}{Jistì.}
{208}{}{Myslím si to taky. Ahoj.}
{209}{}{Tak máš nìco, dítì?}
{210}{}{Pìknı hovno! Zátky!}
{211}{}{Všechno to byly víèka od flašek! Úplnì bezcennı!}
{212}{}{Ha, ha. Vtipe vylez... Ještì mám otázky.}
{213}{}{Zapomeò na to.}
{214}{}{Buliky. Mìj se.}
{215}{}{Copak dneska u se zátkami neplatí? Tím chceš øíct e to všechno schraòování, schovávání a strachování bylo "na <CENSURED>"? e sem se na to nevysral! Promiò, e si se kvùli tomu musel tak snait. Kdybych to bıval vìdìl...}
{216}{}{To je v pohodì. Nashle!}
{217}{}{Prominout? To byla tvoje poslední chyba. Napiš si závì...}
{218}{}{Coe tys øekl "na píèu"? Ale no tak, to se mùe stát kadému. Mùu se ještì zeptat?.}
{219}{}{No, no, Tak jo. Mìj se.}
{220}{}{To byla ale pìkná blbost. Sbohem.}
{221}{}{No dobrá, ale kde sou prachyyyyy?}
{222}{}{Nasrat, Typhone, na to seš moc vychcanej. Tak, kde je vata?}
{223}{}{Tak jo. Matnì si vzpomínám, e sem ty prachy schoval nìkde dolním mìstì. U je to moc let a budovy se neustále pøestavovaly, take nemám ponìtí, kde to je. Pokud ti to trochu pomùe, tak si vzpomínám, e jsem to dal nìkam kde se to nedá roztrhnout ani odtáhnout. Myslím, e nìkde na nìjakém "nenaleznutelném místì"? Pøeju ti hodnì štìstí.}
{224}{}{Koneènì z Typhona vypadlo nìco o lokaci jeho bohatství.}

# Typhon/Seymour Floats.
{300}{}{Ale Hegel na tohleto nemá vstup.}
{301}{}{Hegel, Hegel, Hegel! Poøád jen samá Hegel!}
{302}{}{A proè enskı øikaj, "To ale není králík, otèe!"}
{303}{}{Ha, ha, ha, ha!}
{304}{}{A první proton vdycky øíká, "Ano, jsem pozitivní!"}
{305}{}{(vzdech) Tak to je špatnı, u mi to nejde tak, jako za starıch èasù.}
{306}{}{Není jednoduché, bıt zelenı.}
{307}{}{Povìz mi o tom.}
{308}{}{Ale je zøejmé, e to je pouze filosofickı konec!}
{309}{}{To je jenom proto, e nemáš všechno vyzkoušeno. Teï, kdy dovolíš...}
{310}{}{Chceš nìjaké ovoce?}
{311}{}{Seymour, má hlad.}
{312}{}{Mozky... mooooozky... promiò, starı zvyk.}
{313}{}{To je v pohodì. Stejnì ádnı nemám, vzpomínáš?}
{314}{}{Hnojení je rozhodnì nejlepší vìc, není nic lepšího ne hnijící hromada mrtvol na kompostu.}
{315}{}{Tak to je to proè chceš odsud zmizet! Lehká sklizeò.}
{316}{}{Øeknu ti, e nic není lepšího ne rychlı bìh, vítr ti èechrá vlasy..}
{317}{}{Opravdu cítíš, jak ti vítr èechrá vlasy?}
{318}{}{U roky jsem nemìl poluci!}
{319}{}{Pøedstav si mít tohle tìlo! ádná akce!! ádnı pohyb.}
{320}{}{Moná, kdy dáš šanci fotosyntéze...}
{321}{}{Já nemùu za svoje pøedky, ty zelenej bastarde!}
{322}{}{To nevím, moná bys mohla zkusit methan}
{323}{}{Moje tìlo! Mé ubohé tìlo! Aaaaagh!}
{324}{}{Mám to tady ráda. Myslím, e tady zùstanu.}
{325}{}{Tak dost s tìma vtípkama, kámo.}
{326}{}{Chtìla bych vìdìt, jak se má moje pøíbuzenstvo v Arroyu? Doufám, e dobøe.}
{327}{}{Ale to víš e jo! Škoda jen, e je nìjakej hazl všechny porazil.}
{328}{}{Asi pùjdu otevøít dveøe, nebo tak nìco...}
{329}{}{Myslím si, e mám poøádnì napnuté nervy.}
{330}{}{A ne, e pùjdeš ven zlobit...}
{331}{}{Aaaaaaaaaaaaaagh! U ádné fóry!}
{332}{}{Podívej, jakı mají ta stébla zrna! Bùù, bùù!}
{333}{}{Zchladni! Nemyslím, e to vstøebáš s tím tvım minimozeèkem.}
{334}{}{Chceš abych ti pøeèetl pohádku?}
{335}{}{Co tøeba O karkulce? Jacku rozparovaèi? Magickém prazdroji?}
{336}{}{GECK? Ano, byl tady chlap, kterı...}
{337}{}{Shhh! Shh! Nìkdo poslouchá!}
{338}{}{Vidíš, to je velkı kolobìh ivota... ivá semena na ivá semena na ivá...}
{339}{}{Nic nebude. Ale dy u si dostal hnùj. Ach jo... zahrádkáøská filosofie...}
{340}{}{Nìkdy si pohraju s tvojí Energo zbrojí.}
{341}{}{Myslíš ten starı oblek, co jsem dal do skøínì? Hledej šmudlo...}
{342}{}{No jo no na opilování sem amatér.}
{343}{}{Nìco s tím není v POØÁDKU.}
