#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš tvrdì vypadajícího starého mutanta.}
{101}{}{To je Vachy, vrchní dùlmistr.}
{102}{}{Po bliší prohlídce zjišuješ, e je to starı mutant s tvrdım vırazem v oèích a s krumpáèem a hornickou pøilbou.}

{103}{}{Jsi tu ve mìstì nováèek?}
{104}{}{Eee, coetóó!}
{105}{}{Novı.. Já! Ve mìstì!}
{106}{}{Jo to sem.}
{107}{}{Jistì, právì se vracím z cest.}
{108}{}{Ne asi, chytráku, iji tu od té doby co to tady stojí a tebe vùbec neznám.}
{109}{}{Prı máte nìjaké problémy s dolem.}
{110}{}{Co mi mùeš povìdìt o tomhle místì?}

{111}{}{Ummm... doobráá. Øíkej si co chceš. Tady je trochu doláèù. Bì do salónu a kup si nìjakej chlast.}
{112}{}{Cink? Bzum? ululu!}

{113}{}{Nerozumíš, chlape. Proè odsud nezmizíš? Sakra, moná e chceš od Francise zmalovat prdel.}
{114}{}{Rvaèka? Dem na to!}

{115}{}{Nu dobrá, jsem Vachy. Teï jsme tak trochu bez práce... Ty prı máš obì ruce pravé, jsem slyšel? Máme tu takovej problémeèek s èistièem vzduchu ve spodním podlaí dolù, a bohuel nemáme souèástky, kterejma bychom to spravili a ani ochranou vıstroj, kterou bychom se chránili pøed radonem.}
{116}{}{Nejsem nadèlovìk. Sorry.}
{117}{}{Mùu pomoci. Co bys potøeboval?}

{118}{}{Dobrá, doufám, e se tu u nás v Broken Hills chvíli zdríš.}
{119}{}{(více)}

{120}{}{Ha. Ha. Není nic lepšího, ne chytrej chlap, kterej ví co dìlat s problémy.}
{121}{}{Chytøejší ne jakejkoli jinej buran v tomhle mìstì?}
{122}{}{Oh? Máte problém? O co GO?}
{123}{}{Hlavní problém je v tom, e jsem tu s idiotem.}
{124}{}{To sem já. Chytrák. Jakej máte problém?}

{125}{}{Náš èistiè vzduchu šel do sraèek. Je to ve spodním patøe dolù. Bohuel nemáme ani náhradní díly a ani ochrannou vıstroj. Bez dílù jsme ztraceni a ten radioaktivní plyn by nás zabil. Seš teda ten Kutil TIM, co nám pomùe?}
{126}{}{Tuhle práci beru.}
{127}{}{No. Ještì ne.}

{128}{}{Zase ty, eeh?}
{129}{}{Èichám èichám èlovìèinu!}
{130}{}{Ahoj! Ahojky!}

{131}{}{Èlovìèe, u jsem ti dal prachy. Bì otravovat nìkoho jiného, slyšíš?}

{132}{}{Znovu ty. Proè nejdeš tøeba do ...pr... umm... mìstské banky? Jsem si jistı, e jsou tam pár lidí, kterı by s tebou rádi pokecali.}

{133}{}{Co všechno se vlastnì mùe stát, kdy se nevypaøíš. Nech mì hádat.}

{134}{}{Opravdu? Opravdu bys to pro mì udìlal... a hlavnì pro Broken Hills?}
{135}{}{Co z toho kápne?}
{136}{}{Dobøe udìlám to.}
{137}{}{Né teï né.}

{138}{}{Tak co? Dobrá chytráku, proè neopravit èistiè vzduchu tam dole? Potøebuješ akorát náhradní souèástky a najít cestu jak dıchat jedovatı plyn. Kdy mi dokáeš, e to jde, zváím, jestli máš svaly i nìkde jinde, ne jen kolem huby.}
{139}{}{Co za to nabídneš?}
{140}{}{Jistì, udìlám to.}
{141}{}{Ty si ze mì snad dìláš prdel?}

{142}{}{Zákys je v tom, e jsem idiot. Opakuji to jen proto, abych si byl jistı, e si nesedíš na uších. Schválnì jestli zmizíš ne napoèítám do 10.}

{143}{}{Mimo ty vtípky, kterıma mì rušíš, ti povím e máme problém s èistièem vzduchu v dolech. Je rozsekanej a navíc nemáme nic, s èím bychom dıchali radon a taky nemáme náhradní díly na opravu. Myslíš, e na to máš anebo to tak jenom vypadá?}
{144}{}{Kápne z toho nìco?}
{145}{}{Jistì, udìlám to.}
{146}{}{Dìláš si blázny? Poèkej.}

{147}{}{. Jak ti to zní?}
{148}{}{Pìknı hovno. Chci víc.}
{149}{}{To zní dobøe.}
{150}{}{Zapomeò na to. Mizím odsud.}

{151}{}{Skvìlé! Budeš samozøejmì potøebovat nìjaké náhradní díly. Zajdi do New Rena a najdi Renesca. Má obchod s náøadím. Øekni mu, e tì poslal Vachy a taky heslo, "Kanárek nakopl kyblík." Bohuel nevím, èím se budeš chránit pøed plynem. Asi budeš moct jít dovnitø i nalehko, ale to se neobejde bez zranìní. Ještì jednou ti dìkuji.}
{152}{}{ádnı problém, nashle.}

{153}{}{Ne? Dobrá, a zmìníš názor, víš kde mì najdeš.}
{154}{}{Jistá vìc. Sbohem.}

{155}{}{Dobrá tedy. Pùlku dostaneš teï a druhou a bude vše hotovo. Jdi do New Rena a najdi Renesca. Vlastní obchod s náøadím. Moná ti bude moct pomoci.}
{156}{}{Uvidíme se.}

{157}{}{Promiò. To je vše. Ber nebo nech bejt.}
{158}{}{Vezmu si to.}
{159}{}{Nepotøebuju to.}

{160}{}{Potom odejdi v pokoji.}
{161}{}{Co dìlat.}

{162}{}{Buï zdráv pøíteli!}
{163}{}{O boe zase ty.}
{164}{}{Jejky.}
{165}{}{Vìdìl jsem, e ty bastardi Frank, Manson, Jacob, a Aileen proti nám nìco maj. Dobrá tedy! Take...}
{166}{}{Doufám, e víš, jak by se ta ruda dala vrátit zpìt do mìsta... Tak...}
{167}{}{Dìkuji ti, e jsi prodal rudu. Nám by byla asi nanic. Tak...}
{168}{}{Moc ti dìkuji, es jí našel. Ani nevíš jak tìce jsme kvùli tomu museli pracovat.}
{169}{}{Copak si pøeješ?}
{170}{}{Co mi povíš o mìstì?}
{171}{}{Zaslechl jsem, e máte nìjaké problémy s dolem.}
{172}{}{Jak to jde?}
{173}{}{Ty jsi s lidmi zadobøe?}

{174}{}{U si zmìnil názor?}
{175}{}{Kápne z toho nìco?}
{176}{}{Udìlám to.}
{177}{}{Ještì ne.}
{178}{}{Ne.}

{179}{}{Jak to jde? Doufám, e se na to hodnì brzy podíváš...}
{180}{}{No co s tebou mám dìlat.}
{181}{}{Mám moc práce. Na poflakování není èas.}
{182}{}{Dám ti vìdìt, a budu mít èas.}

{183}{}{U máš ty díly? No vıbornì... Snad máš taky nìco na ochranu, vıpary by tì mohli sloit.}
{184}{}{Mùu se do toho dát.}
{185}{}{Hupnu na to za chvíli.}

{186}{}{U máš ty díly? No vıbornì... Snad máš taky nìco na ochranu, vıpary by tì mohly sloit.}
{187}{}{Mùu se do toho dát.}
{188}{}{Hupnu na to za chvíli.}

{189}{}{Opraveno? Vıbornì! Sice vím, e jsi za to nic nechtìl, ale... já a kluci jsme se sloili na dárek pro tebe. Je to bojová brokovnice. Hodnì štìstí a uij jí ve zdraví. Ještì jednou dík.}
{190}{}{ádnı problém. Dìkuji!}

{191}{}{U je to vánì opraveno! To je skvìlé. Podle naší dohody, máš tady ode mì nìjakou vìc jako odmìnu.}

{192}{}{Ty hovnoroute. Pøišel sis pro smrt.}

{193}{}{Dobrá, pospìš si... naše mìsto potøebuje to, co nám z nìj vyrvali.}
{194}{}{Jistá vìc. Uvidíme se.}
{195}{}{Nepøehánìj to, jsem zamìstnanı mu.}

{196}{}{No dobrá pane Velkomonı, ale myslel jsem e nejdùleitìjší je pøeití mìsta, mùeš si teda pospíšit?}
{197}{}{No to mì poser na holı kozy. Udìlám co budu moct, uvidíme se.}
{198}{}{Tak to byla poslední kapka. Sbohem, mrtvolko.}

{199}{}{Pospìš si,dùl je naše ivobytí.}
{200}{}{No jo, no jo.}

{201}{}{No nejlepší bude promluvit si s Marcusem pøed bankou, anebo se Stevem, u mìstské brány.}
{202}{}{Hmm. Tak jo, dík.}
{203}{}{Pùjdu se jich zeptat.}

{204}{}{Mohl bych øíct, e to šlape  v pohodì. Ale... vdycky mùe bejt líp.}
{205}{}{Heh. Dík za informace.}

{206}{}{No mutanti nejsou jen staøí a senilní - plyn je udruje v pohodì, nebo tak nìco - øekl bych spíš, e se máme fajn. A co pamatuji, mutanti u nikdy nechtìli vradit. Lidé u o nás smıšlejí docela dobøe. Samozøejmì, e to nezahrnuje ty štváèe z okolních mìst... no a teï jsou nìkteøí z nich i tady.}
{207}{}{Tak jo. Nazdar.}

{300}{}{. Co na to øíkáš?}
{301}{}{. Jak se ti to líbí?}
{302}{}{$}
{381}{}{Jsem zamìstnaná ena, a ještì jsem se tu moc nerozhlédla.}
{382}{}{Neotravuj mám práci.}
{383}{}{No dobrá pane Velkomonı, ale myslel jsem e nejdùleitìjší je pøeití mìsta, mùeš si teda pospíšit?}

{400}{}{Mám nìjakı papírek s tvım jménem. Leel u jedné mrtvé eny v chodbách. Co mi o tom mùeš øíct?}
{401}{}{Hele já to jen dostal. Bì si o tom pokecat s Francisem. Je jeden z tìch, co to psali.}
{402}{}{Jestli máš prsty v tìch vradách, tak to chci vìdìt.}
{403}{}{Dobrá. Navidìnou.}

{404}{}{Ne! Jenom se chráníme pøed tím spiknutím. Marcus vìøí v právo a poøádek. A vdycky vìdìl, e jsou tihle lidé nebezpeèní, ale nikdy nezjistil, kdo to je -
 a na to aby vzal právo do vlastní ruky je moc vznešenı. Ten lísteèek mi dal Francis, protoe se bál naší pomsty.}
{405}{}{To zní zajímavì. Pùjdu si poslechnout Francisovu verzi.}

{406}{}{Vím, e Francis není vznìtlivı. Znal dùsledky toho, co dìlá, ale domnívám se e nepoèítal s tím, e by byl chycen. Myslím si, e bude v poøádku a doufám, e to samé se stane s Broken Hills.}
{407}{}{Doufám e máš pravdu. Ještì se chci zeptat...}
{408}{}{Já taky. Sbohem.}
