#tento soubor pøeložil Vachy - http://vachy.moje.cz
{100}{}{"Vachy: Marcus neudìlá nic s tím kriplem Jacobem a jeho prokletým povstáním. Nejdøív znièil èistiè vzduchu ...a dál co? Našel jsem jejich tajný tunel kde se scházej. Jedna z tìch postav vevnitø byl urèitì Jacob. Když bys chtìl vìdìt víc, víš, kde mì najdeš. Až si tuhle zprávu pøeèteš, tak ji zniè!" - Napsal Francis}
{101}{}{Krucinál, když o tom øeknu Marcusovi celý mìsto stane v plamenech. Radìji si o tom promluvím nejprve s Vachym nebo Francisem!}