# tenhle fajl pøelouskal: Mıval (myval@writeme.com). Naposledy editováno: 31/05/1999
# 0. QUICK LOOK
{100}{}{Vidíš dobøe vyzbrojeného oldáka.}

# 0. LOOK
{150}{}{Vidíš drsòáka obleèeného do koeného brnìní. Tìlo má pokryto èetnımi jizvami a støelnımi ranami. Ovšem
 jeho brnìní i zbranì vypadají udrovanì, skoro jako nové.}
{151}{}{Vidíš dobøe vyzbrojeného jezdce. Peèlivì prohlíí okolí a ruce má na zbrani.}

# 1. FLOAT DIALOGUE: INTRUDER (WTG)
{200}{}{Podívejme se na brnìní tohodle zkurvysyna...}
{201}{}{Kontakt!}
{202}{}{Oblast byla narušena!}
{203}{}{Máme nezvaného hosta, chlapci!}
{204}{}{Rychle, chlapci, máme tu vetøelce!}
{205}{}{Dobrá, uvidíme kdo vydrí dıl naivu...}
{206}{}{Zatracenì! Nìkdo nás našel!}
{207}{}{Máme tu nìjakıho odválivce...}
{208}{}{Jsi na *špatnım* místì, hajzle.}
{209}{}{Hele, podívejme jak se ten hajzl naparuje...}

# 2. FLOAT DIALOGUE: NORMAL (WTG)
{250}{}{Chlastali jsme a on si chtìl 'vymìòovat názory', tak sme mu nakopali prdel.}
{251}{}{Musím zkontrolovat ty skupiny v jeskyni...}
{252}{}{Je èas znovu zkontrolovat rajón...}
{253}{}{Èlovìèe, tenhle domorodec *smrdí*. A všichni ostatní taky.}
{254}{}{Zatracenı laserovı kanóny ve Vault City...}
{255}{}{U mì nebaví jen leštit mojí bouchaèku... a to mám dokonce dvì.}
{256}{}{Jak dlouho tu budeme èekat?}
{257}{}{Mìli bysme bìhem nìkolika dní vypadnout...}
{258}{}{Nemùu se doèkat, a se vrátím do Rena. *Zvláš* se tìším na Koèièí Packu.}
{259}{}{Škorpióni u zase mají hlad. Vèera v noci bylo slyšet jejich... *cvak* *klap* *cvak*}
{260}{}{Zkontroloval jsi ty miny u vchodu, jak jsem ti *øíkal* ?}
{261}{}{Kapitán u po mnì zase jde, protoe mi málem utekl jeden obchodník...}
{262}{}{Zajímalo by mnì, jak se dostanu z tıhle posranı vıpravy.}
{263}{}{Lynette je koèka. Svım zpùsobem.}
{264}{}{... a pak *øekne*, 'to je mùj pupek, do prdele!' Cha Chá! Tenhle kameòák mì *vdycky* dostane.}
{265}{}{Pùjdeme.}
{266}{}{Kapitán mi nakope prdel...}
{267}{}{Mám pocit, jako kdybych tu stál vìènì a jen èekám, a se nìkdo ukáe.}
{268}{}{Chtìl bych jít nìkam jinam, kdybych mìl kam...}
