# tenhle fajl pøelouskal: Mýval (myval@writeme.com). Naposledy editováno: 31/05/1999
# 0. QUICK LOOK
{100}{}{Vidíš vùdce žoldákù.}

# 0. LOOK
{150}{}{Vidíš drsného chlapa v bojovém brnìní. Jeho výstroj a zbranì jsou dobøe udržované, témìø nové.}
{151}{}{Vidíš žoldáckého vùdce. Se zbraní v rukách si prohlíží okolí.}

# 1. FLOAT DIALOGUE: INTRUDER (WTG)
{200}{}{Hele, podívej na toho oplechovanýho zkurvysyna...}
{201}{}{Kontakt!}
{202}{}{Je tu vetøelec, chlapi!}
{203}{}{Máme nezvaného hosta, chlapci!}
{204}{}{Dobrá, uvidíme kdo vydrží dýl naživu...}
{205}{}{Zatracenì! Nìkdo nás našel!}
{206}{}{Máme tu nìjakýho odvážlivce...}
{207}{}{Jsi na *špatným* místì, hajzle.}
{208}{}{Hele, podívej jak se ten hajzl naparuje...}

# 2. FLOAT DIALOGUE: NORMAL (WTG)
{215}{}{Nejlepší bude zavolat co nejdøív speciální zabijácká komanda.}
{216}{}{Myslím, že druhý tým je kousek na jih od Vault City... stále hledají ten karavan.}
{217}{}{Ta pouštní tøešeò by se už mìla objevit...tahle vìc se tady tak èasto nevyskytuje.}
{218}{}{Je èas vyslat muže na hlídku...}
{219}{}{Kdybychom jen mohli nìjak zneškodnit laserové kanóny ve Vault City...}
{220}{}{Stále èekám na zprávu od Bishopa...}
{221}{}{Od té doby, co Bishop vyslal kurýra, ubìhl už týden.}
{222}{}{Poèítám, že další karavan pojede z NCR do Vault City...}
{223}{}{Musíme být pøipraveni k okamžitému pøesunu.}
{224}{}{Doufám, že chlapci zkontrolovali pasti.}
{225}{}{Už se sešel první a druhý tým?}
