# tenhle fajl pøelouskal: Mýval (myval@writeme.com). Naposledy editováno: 31/05/1999
# 0. QUICK LOOK
{100}{}{Vidíš Stín_který_chodí.}

# 0. LOOK
{150}{}{Vidíš svalnatého primitiva s èernými jizvami na tváøi. Tiše tì pozoruje.}
{151}{}{Vidíš Stín_který_chodí. Jeho tváø je plná rituálních tetování.}

# 1. CLICK ON HIM (WTG)
{200}{}{Tiše na tebe zírá.}
{201}{}{Tiše tì pozoruje.}

# WABBITS
{300}{}{Pšššt... Louím králíèky.}
