# tenhle fajl pøelouskal: Mýval (myval@writeme.com). Naposledy editováno: 31/05/1999
# 0. LOOK
{100}{}{Vidíš ohromný èerný ocelový sejf.}
{101}{}{Vidíš èernou hranatou vìc s velkým kolem.}

# 2.  EXAMINE SAFE, CLOSED (WTG, 10)
{200}{}{Vidíš ohromnou èernou, kovovou, hranatou vìc s kolem vpøedu.}
{201}{}{Vidíš ohromný èerný, ocelový sejf, který se zdá být pøíliš težký, než aby s ním šlo pohnout. Je na nìm 
 èíselný zámek.}
{202}{}{Sezame otevøi se. Já jsem }
{203}{}{. A ty?}
{204}{}{Otoèit kolem.}
{205}{}{Vypadnout.}
{206}{}{Hmmmm. Možná, že èísla na tìchhle tøech psích známkách mohou otevøít sejf...}
{207}{}{Otáèet èíselníkem a poslouchat cvakání.}
{208}{}{Náhodnì otáèet èíselníkem.}
{209}{}{Prozkoumat, zda v sejfu nejsou nástrahy.}
{210}{}{Nechat sejf na pokoji.}

# 3.  SAFE IS OPEN (WTG, 2, 4, 5, 6, 7, 8)
{220}{}{CVAK! Sejf se otevøel.}
{221}{}{Sejf je otevøený.}
{222}{}{Kolo ve tvé ruce se otoèilo! Zdá se, že by dveøe mohly jít otevøít.}

{223}{}{Zdá se, že se ta velká hranatá vìc dá teï otevøít.}
{224}{}{Otevøít dveøe.}
{225}{}{Odejít.}
{226}{}{Sebrat vìci v sejfu.}
{227}{}{Nechat sejf na pokoji.}

# 4.  TRAPS, SUCCESS . . . ? (2, 6)
{235}{}{Peèlivá prohlídka sejfu odhalila èerný drát vedoucí do prachu pod sejfem. Po odstrannìní prachu vidíš
 spínaè pøipojený k dynamitové náloži s èasovým spínaèem.}
{236}{}{Hmmmm. Možná že èísla na tìch tøech psích známkách mohou otevøít sejf...}
{237}{}{Zkusit zneškodnit past.}
{238}{}{Nechat sejf na pokoji.}

# 5.  CLICKING (2, 5, 6, 8)
{250}{}{Nìkolik minut pomalu otáèíš knoflíky, ale nic se nestalo.}
{251}{}{Hmmmm. Možná, že èísla na tìch tøech psích známkách mohou otevøít sejf...}
{252}{}{Otáèet èíselníkem a poslouchat cvakání.}
{253}{}{Náhodnì otáèet èíselníkem.}
{254}{}{Nechat sejf na pokoji.}

# 6.  TRAPS . . . ? (2, 6)
{275}{}{Na sejfu neshledáváš žádné pasti.}
{276}{}{Hmmmm. Možná, že èísla na tìch tøech psích známkách mohou otevøít sejf...}
{277}{}{Otáèet èíselníkem a poslouchat cvakání.}
{278}{}{Náhodnì otáèet èíselníkem.}
{279}{}{Znovu zkontrolovat, zda nejsou v sejfu pasti.}
{280}{}{Nechat sejf na pokoji.}

# 7.  SPIN RANDOM, SUCCEED (2, 5, 6, 8, 9)
{290}{}{Otáèíš knoflíkem... a v tom se najednou ozvalo CVAK. Sejf je odemèený!}
{291}{}{Otáèíš náhodnì èíselníkem, a najednou se èíselník zastavil... CVAK!  Sejf je odemèený.}
{292}{}{Hééj, haló. Být nìkdo doma?}
{293}{}{Tuhne ti úsmìv a sundaváš si košili...}
{294}{}{Ano! Mám to...}

# 8.  SPIN RANDOM, FAIL (2, 5, 6, 8, 9)
{305}{}{Otáèíš knoflíkem, ale dveøe se neotvírají!}
{306}{}{Otáèíš èíselníky už nìkolik minut ale nic se nestalo.}
{307}{}{Halóóó? Haló bedýnko...}
{308}{}{Dál otáèet kolem.}
{309}{}{Odejít!}
{310}{}{Hmmmm. Možná, že èísla na tìch tøech psích známkách mohou otevøít sejf...}
{311}{}{Otáèet èíselníkem a poslouchat cvakání.}
{312}{}{Pokraèovat v náhodném otáèení èíselníky.}
{313}{}{Nechat sejf na pokoji.}

# 9.  HELLO? (2, 8, 9)
{320}{}{Ta vìc neodpovídá.}
{321}{}{Èerná kovová hranatá kostka si tì nevšímá.}
{322}{}{Kovová bedna tì ignoruje.}
{323}{}{Heeej? Já }
{324}{}{. Halóóó?}
{325}{}{Otoèit kolem.}
{326}{}{Vypadnout.}


# 10.  TRAP DISARMED . . . ? (4)
{340}{}{S chirurgickou pøesností zneškodòuješ roznìtku a vytahuješ dynamit z prachu. Past je nyní zneškodnìna.}
{341}{}{Teï je tøeba rozlousknout sejf...}
{342}{}{Nechat sejf na pokoji.}

# During Combat
{343}{}{Pøi boji nemáš èas zkoumat sejf.}

# Safe opening Message
{344}{}{Sejf žoldákù byl úspìšnì zdolán.}
