#tento soubor prelozil RadaR - rd@zbrojovka.com
#
#############################################################
#  Message File: kcitizen.msg                               #
#                                                           #
#       Body Type:  NAROBE                                  #
#       Combat AI: Flee                                     #
#       Weapons: None                                       #
#       HP: 20                                              #
#       Skills to note: None                                #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: January 13, 1998                                #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{Vidíš jednoho z obyvatelù Klamathu.}
{101}{}{Vidíš jednoho z obyvatelù Klamathu.}

#############################################################
#  The following lines are floaters for citizens            #
#############################################################

{150}{}{Proè se nevrátíš zpìt ke svému kmeni?}
{151}{}{Dám ti hezkı korálky, jestli mì necháš bıt.}
{152}{}{Hodnej barbar, dobrej barbar. Neublííš mi, e ne?}
{153}{}{Nìkdy si pøeju, abychom mìli okolo mìsta zeï.}
{154}{}{Nemám nic na ukradení; jdi pryè.}
{155}{}{Proè si mne tak prohlííš?}
{156}{}{Bezvadnı, další barbar.}
{157}{}{Proè nezapadneš zpátky ke Zlatému geckonovi?}
{158}{}{Radìji se ode mne dr dál.}
{159}{}{Nemusíš tu dávat podnìt k problémùm.}
{160}{}{Musíš pocházet odnìkud ze severu.}
{161}{}{Poslední co tu potøebujeme, je víc takovıch jako jsi ty.}

{170}{}{Zdravím, cizinèe.}
{171}{}{Jsem si jist, e je vhodné roèní období na lov.}
{172}{}{V poslední dobì postrádám hodnì brahmín.}
{173}{}{(Køup, køup) Duntonovic sušené maso je òam-òam.}
{174}{}{Pøišel jste sem tajnì obchodovat s ohnivou vodou?}
{175}{}{Myslel jsem, ze všichni vaši lidé si dávají skrz nos kost.}
{176}{}{Bìte omrknout krysy v Lovecké ètvrti.}
{177}{}{Kam jsem si zaloil své kouzelné fazole?}
{178}{}{Geckoni chutnají jako kuøata, pokud se správnì pøipraví.}
{179}{}{Chystám se jít uvonit do lázní.}
{180}{}{Sledujte bratry Duntonovic.}
{181}{}{U Bucknerové mi vdycky dobøe zaplatí za mé zboí.}
{182}{}{Dnes je hezkı den.}
{183}{}{Vypadáte jako Sulik.}
{184}{}{Kam zase ten blbec Torr šel?}
{185}{}{Velké tajemství je... - hej, kam to zmizelo z mı kapsy?!?}
{186}{}{Pro spodinu ádnı odpoèinek.}
{187}{}{Bolí mne klouby, asi bude zmìna poèasí.}
{188}{}{Snaím se popadnout dech.}

{190}{}{Pìkné vás vidìt.}
{191}{}{Ještì nìco, abyste se tu cítil jako doma?}
{192}{}{Doufám, e se vám Klamath líbí.}
{193}{}{Kdybychom tu tak mohli mít více lidí vašeho kalibru.}
{194}{}{Copak, pøíteli?}
{195}{}{Hodnì štìstí pøeji.}
{196}{}{Jestlie budete cokoliv potøebovat, zajdìte do hospody U Bucknerové.}
{197}{}{V nièem se nepodobáte Sulikovi.}
{198}{}{Jste nejvíce civilizovanı barbar s jakım jsem se zatím setkal.}
{199}{}{Nauète se rozlišovat geckony podle barev.}
{200}{}{Helou, cestovateli.}
{201}{}{Jsme rádi, e vás máme v Klamathu.}
{202}{}{Teší mì, cizinèe.}
{203}{}{Bacha na ty Duntonovi; zdají se nebezpeèní.}
{204}{}{Lovecká ètvr je plná krys.}

#############################################################
#  TELL ME ABOUTS WILL BE REMOVED                           #
#############################################################
{1000}{}{Elder}
{1001}{}{Founder}
{1002}{}{Vault Dweller}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Vault}
{1006}{}{Chosen One}
{1007}{}{Shaman}
{1008}{}{Hakunin}
{1009}{}{Healing Powder}
{1010}{}{Bridge}
{1011}{}{Mynoc}

{1100}{}{The Elder is your mother and our leader.}
{1101}{}{Our great ancestor who gave us knowledge.}
{1102}{}{The first to fight and win over chaos.}
{1103}{}{That would be our beautiful village.}
{1104}{}{That's trading outpost a few days east of here.}
{1105}{}{The Vault is heaven.}
{1106}{}{You are the Chosen One.}
{1107}{}{He heals us with his herbs and magic. He is in the north part
 of our village.}
{1108}{}{He heals us with his herbs and magic. He is in the north part
 of our village.}
{1109}{}{It is a magic powder which will heal you, but will make you
 sleepy.}
{1110}{}{The Great Bridge exits our village in the south.}
{1111}{}{He guards the bridge leading into our village.}
