# tenhle fajl pøelouskal: Mýval (myval@writeme.com). Naposledy editováno: 31/05/1999
{100}{}{Vidíš hlídacího psa.}
{101}{}{Vidíš divokého psa.}

{120}{}{Vidíš hlídacího psa.}
{121}{}{Vidíš divokého psa.}

{200}{}{:: VRRR ::}
{201}{}{:: GRRR ::}
{202}{}{:: RRAF ::}

{205}{}{Haf}
{206}{}{Haf Haf}

{210}{}{Pes je dobøe vycvièen pro ostrahu kùlny.}
{211}{}{Pejsek mì nemá rád.}
{212}{}{Hóódnej pejsek!}

{250}{}{Zdá se, že kdyby chtìl, mohl by tì ten pes roztrhat na kusy.}