# tenhle fajl pøelouskal: Mıval (myval@writeme.com). Naposledy editováno: 31/05/1999
{100}{}{Svalnatı mu obleèenı do koené zástìry.}
{101}{}{Balthas - koeluh.}
{102}{}{Vysokı, svalnatı mu, kterı páchne kùí.}

{151}{}{Mùj syn byl nešastnì zabit v souboji.}
{152}{}{Nechci u bez Jonnyho dál ít.}
{153}{}{[vzlyk]}
{154}{}{Setkáme se na Farmì Duchù. Zatoèíme s tìma duchama.}
{155}{}{Zdravím, jmenuju se Balthas. Vedu koelunu tady v Modocu. Mùu ti nìjak pomoct?}
{156}{}{Vypadáš ponìkud roztritì; dìje se nìco?}
{157}{}{Mohu vidìt tvé zboí?}
{158}{}{Nevidìl jsi nìkde leet zlaté hodinky?}
{159}{}{Za chvíli budu zpátky.}
{160}{}{Hledám vìc, která se jmenuje GECK. Netušíš, kde by se dalo nìco takového získat?}
{161}{}{GECK?}
{163}{}{Jak ti mohu pomoci?}
{168}{}{Jen se dívám, díky.}
{171}{}{Máš nìjaké nové zprávy ohlednì nalezení Jonnyho?}
{172}{}{Tohle leelo na dnì vyschlé studny. Èást studny se zøítila dovnitø a tohle bylo v sutinách. Je mi to líto, ale myslím, e Jonny je mrtev.}
{173}{}{Ne, zatím nic.}
{175}{}{Díky za záchranu chlapce. Nevím, jak bych se ti mohl odvdìèit, ale vezmi si prosím tuhle koenou zbroj jako podìkování. Vynalezl jsem novı zpùsob vydìlávání kùí; tahle zbroj je velmi odolná - a kromì toho, urèitì ti skvìle padne.}
{176}{}{Díky za záchranu mého syna!}
{177}{}{Prosím, nech mì s mım zármutkem samotného.}
{178}{}{Jonny je naivu! Nìkteøí lidé øíkali, e ho Svìtloplachové zachránili. Kdy ještì chvíli vydríš, najdu zpùsob, jak vrátit Jonnyho domù.}
{179}{}{Jonny byl unesen. Drí ho duchové na farmì a chtìjí ho obìtovat svému temnému bohu.}
{180}{}{Já nechápu... Ach, promiò, e obtìuji.}
{181}{}{Co? Podívej, nebudu se bavit s cizincem o svım soukromım ivotì. Chceš nìco koupit, nebo ne?}
{182}{}{Omlouvám se, jmenuji se }
{183}{}{. Tak jsme se pøedstavili. Zdá se, e máš problémy.}
{184}{}{Ano, zajímám se o nìjaké koené zboí.}
{186}{}{Myslím, e ne.}
{187}{}{Øíkáš  }
{188}{}{? Ano, myslím, e jsem o tobì u slyšel. Jeden ze stráí v projídìjícím karavanì o tobì pochvalnì mluvil. Vím, e jsme se teprve seznámili, ale opravdu bych potøeboval tvoji pomoc.}
{189}{}{Proè mi radìji neøekneš o svém problému, tøeba mùu pomoci?}
{190}{}{Mám svıch problémù dost.}
{191}{}{[Bere ocelovou tyè a zuøivì ji uchopí. K tvému úasu se ocelová tyè se kroutí, jako by byla z gumy. Ten chlap má ale sílu!] Mùj chlapeèek, Jonny, schází mi! Pøed nìkolika dny si šel ven hrát a u se nevrátil. Hledali jsme ho všude, ale jako by se po nìm zem slehla.}
{192}{}{Kde si Jonny vìtšinou hrával? A hrál si ještì s nìkım jinım?}
{193}{}{Je mi líto tvého chlapce, mùu pro tebe nìco udìlat?}
{194}{}{To je strašné! Ale zajímaly mne pouze tvoje koené vırobky. Mùeš mi ukázat své zboí?}
{195}{}{Oooh! U je moc hodin, musím jít.}
{196}{}{Znamená to, e mi pomùeš? Díky! Naposledy vidìli Jonnyho hrát si na kovboje a indiány s jeho psem Laddie. Byli to dva nerozluèní pøátelé; a vlastnì díky ní, kdy se vrátila domù bez nìho, jsme zjistili, e je Jonny pryè. Hledali jsme ho pak všude. Vezmi si Laddii s sebou; moná e Jonnyho spoleènì najdete.}
{197}{}{Vypadáš jako zkušenı cestovatel. Se svımi zkušenostmi moná mého syna najdeš.}
{198}{}{Ano! Jsem obratnı stopaø, aspoò si to o sobì myslím. Dobrá, pomohu ti.}
{199}{}{Lichotky nikam nevedou. Podívej, potøebuji zodpovìdìt pár otázek.}
{200}{}{Mé modlitby byly vyslyšeny! Vezmi si Laddie s sebou, pomùe ti. Prosím, pospìš si!}
{201}{}{Dobrá, moná máš pravdu. Díky za vyslechnutí.}
{202}{}{Slyšel jsem o tobì. Podívej, my nechceme ádné problémy; jsme mírumilovná spoleènost. Bavme se jen o obchodu, OK?}
{203}{}{Mám na tebe nìkolik otázek.}
{204}{}{Tak to ti nepomohu. Sbohem.}
{205}{}{Mám velkou starost o našeho synka Jonnyho. Hledali jsme ho všude, ale nemùeme ho nikde najít. Bojím se, e ho roztrhala divoká zvìø.}
{206}{}{Moná ti mohu pomoci. Hodnì cestuji, budu pøitom hledat tvého syna.}
{208}{}{To bych byl moc rád. Kadá pomoc je vítaná. Mimochodem, nekoupíš si u mì nìco?}
{210}{}{Ne, ne, díky. U musím jít.}
{211}{}{Je mi líto, o tom jsem nikdy neslyšel.}
{214}{}{Hehehe. Tak tebe taky ten staroch Cornelius navezl do hledání tìch hodinek? Ne, tady je nenajdeš. Ten starej trouba je zøejmì nìkde zapomnìl a neví kde.}
{215}{}{Stejnì dìkuju. Budu ho hledat.}
{216}{}{[Zblízka se na tebe podívá a usmìje se.] Proè nejsi poslušnı chlapec a nejdeš si hrát ven?}
{217}{}{[Zblízka se na tebe podívá a usmìje se.] Proè nejsi poslušná holèièka a nejdeš si hrát ven?}
{218}{}{Prosím, hledej ho dál. Vím e ije, já to cítím!}
{219}{}{To je Jonnyho pistolka. Neeeeeeeeeeeeeeeeeeee! [Balthas se zhroutí a zaène neovladatelnì plakat.]}
{220}{}{Já vìdìl, e Jonny není mrtvı! Øíkáš, e musím èekat... tomu nerozumím! Je zranìnı? Cítím, e
 chceš pomoci mému synkovi co nejlépe. Prosím, pospìš si a pøiveï mi mého syna.}
{221}{}{Neee! U ádní duchové! Já øíkal, abychom to místo vypálili a srovnali se zemí. Nenechám jim svého syna... dostanu Jonnyho zpìt za kadou cenu. Doufám, e mi obyvatelé Modocu pomohu dostat syna zpìt! Setkáme se na Farmì Duchù. Všechny je pobijeme!}
{230}{}{Jonny byl v poøádku vrácen zpìt do Modocu.}
