# tenhle fajl pøelouskal: Mýval (myval@writeme.com). Naposledy editováno: 31/05/1999
# Before Jonny Found
{100}{}{Vzlyk...}
{101}{}{Jonny...}
{102}{}{Smrk...}
{103}{}{Schází mi mùj synek.}

# Player accepts find Jonny Seed
{110}{}{Prosím, najdi Jonnyho.}

# After Jonny Found
{120}{}{Prosím, pøiveï Jonnyho zpátky.}

# Jonny Returned
{121}{}{Mnohokrát ti dìkuji za nalezení Jonnyho.}

# looks
{150}{}{Vidíš Balthasovu ženu.}
{151}{}{Vidíš Balthasovu ženu. Je ponìkud rozèilená.}
{152}{}{Vidíš Balthasovu ženu. Zdá se, že má dobrou náladu.}
