# tenhle fajl pøelouskal: Mıval (myval@writeme.com). Naposledy editováno: 31/05/1999
# 0. Look
{100}{}{Podle nápisu na chomoutu se jmenuje Bess.}
{101}{}{Vidíš Bess.}

{110}{}{Zdá se, e tato brahmíní samice byla asi napadena nìjakım divokım zvíøetem. Je vánì zranìna.}
{111}{}{Na takovou brahminu by mohl bıt kadı pyšnı.}

# 1. Bubble text
{120}{}{Bùùùùùùùùù!}
{121}{}{[Ta nebohá brahmína je vánì zranìna.]}

# 2. Jerky
{130}{}{Bùùùùùùùùù.}
{131}{}{[Bess hluboce a smutnì zabuèí.]}
{132}{}{Chudinko - dávat tì øezníkovi asi nebude nejlepší nápad. Chtìla bys odsud utéct?}
{133}{}{Jupí! Bude z tebe vynikající sušenı maso.}

# 3. Escape? (2)
{140}{}{Bùùùùùùù.}
{141}{}{[Teï buèí o hodnì veseleji.]}
{142}{}{OK, tak pojï odsud pryè.}
{143}{}{Jen si dìlám legraci. Víš, potøebuju tvoje maso víc ne tebe.}

# 4. Bubble message
{150}{}{Bùùùùù.}

{200}{}{Na poskytnutí pomoci brahmínì jsou tvé znalosti první pomoci nedostaèující.}

{300}{}{Podaøilo se ti uzdravit brahmíninu zlomenou nohu.}
{310}{}{Nepodaøilo se ti uzdravit brahmíninu zlomenou nohu.}
