# tenhle fajl pøelouskal: Mýval (myval@writeme.com). Naposledy editováno: 31/05/1999
{100}{}{Další zbytky pro Rózu.}
{101}{}{Huh! Nikdy si na to nezvyknu.}
{102}{}{Miluju svojí práci.}
{103}{}{Balthas zaplatí pìkný prachy za tyhle vnitønosti.}
{104}{}{Prý dìláte výborný dezert z vymaèkaných oèních bulv.}
{105}{}{Maso je pøipraveno k vyuzení.}

{120}{}{To je stará Bessy.}

{200}{}{Uhnìte, pane; mám tu brahmínu na porážku.}
{201}{}{Táhni z cesty.}
{202}{}{Mùžete se prosím uhnout? Mám nìjakou práci.}
{203}{}{Hej dámo, rozumíte slovu "uhnout"? Mám tu brahmínu na porážku.}

{250}{}{Vidíš øezníka.}
{251}{}{Je to øezník-specialista.}
{252}{}{Je to øezník z jatek. Jeho obleèení je nasáklé krví z mrtvých brahmín.}
{253}{}{Ten hrozný zápach je cítit až k tobì.}

{275}{}{Sakra, budeme potøebovat další brahmíny.}
{276}{}{Jóó, to byl den. Už nemáme další brahmíny. Joooo!!! JE ÈAS ZAJÍT NA PIVO!!!}
{277}{}{Kruci! Už nemám co zabíjet! Možná bych mìl zajít za Miriou.}

{280}{}{Áaah, už je èas jít domu a odpoèinout si.}
{281}{}{Je èas jít domu a dát si pìkný propeèený steak.}
{282}{}{Byl to dlouhý den. Doufám, že už se ráno neprobudím, abych to nemusel dìlat zas.}

{300}{}{Sušený maso je dobrý na kosti.}
{301}{}{Sušený maso je dobrý na vlasy.}
{302}{}{Sušený maso je dobrý na plíce.}
{303}{}{Sušený maso je dobrý na žaludek.}
{304}{}{Sušený maso je dobrý na ledviny.}
{305}{}{Sušený maso je vynikající.}
{306}{}{Sakra, co tu dìlá to hovno?}
{307}{}{Myslím, ze jsem si ušpinil kabát. HA! HA! HA!}
{308}{}{Dávej pozor, kam šlapeš. Podlaha je plná nechutných hromádek.}
{309}{}{Chutná vám sušený maso?}
{310}{}{Mám rád sušený maso i ke snídani.}
{311}{}{Mlíko, zmrzlinu, to miluju. Ale SUŠENÝ MASO!!!}
{312}{}{Hej! Poslyšte, SUŠENÝ MASO!!! HA! HA! HA!}
