# tenhle fajl pøelouskal: Mýval (myval@writeme.com). Naposledy editováno: 31/05/1999
#############################################################
#  Message File: mcChild.msg                                 #
#                                                           #
#       Body Type: CHILD                                    #
#       Combat AI: Flee                                     #
#       Weapons: None                                       #
#       HP: 20                                              #
#       Skills to note: None                                #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: January 13, 1998                                #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{Malý chlapec.}
{101}{}{Malé dìvèe.}

{120}{}{Malý chlapec. Je ponìkud rozpustilý.}
{121}{}{Malé dìvèe. Je ponìkud rozpustilé.}
#############################################################
#  The following lines are floaters for children            #
#############################################################
{150}{}{Nesnìzte mì!}
{151}{}{Eééé! Strašná obluda!}
{152}{}{Tatínek øíkal, že jste zlí lidé.}
{153}{}{Jééé! Utíkejte!}
{154}{}{Nestrašte mì.}
{155}{}{Nedívejte se na mì.}
{156}{}{Neèekal jsem, že budu mluvit s domorodci.}
{157}{}{Ty jsi ale balvan.}
{158}{}{Maminka øíkala, že mì sníte, když budu zlobit.}
{159}{}{Já se tì nebojím!}
{160}{}{Pomoooc!}
{161}{}{Je po mnì!}
{162}{}{Prosím, neubližujte mi!}
{163}{}{Nechoïte ke mnì!}
{164}{}{Jeeeeeeee!}
{165}{}{Nenávidím vás!}
{166}{}{Mamíí, mamíí, maminkoo!}
{167}{}{Nechte mnì na pokoji!}
{168}{}{Smrdíš!}

{170}{}{Ahooj.}
{171}{}{Chcete si hrát?}
{172}{}{Opravdu si dokážete prostrèit kost skrz nos?}
{173}{}{Proè vypadáte tak legraènì?}
{174}{}{Maminka øíkala, že jste primitivové.}
{175}{}{Už váš kmen pøestal jíst lidi?}
{176}{}{Kdo vás tak legraènì oblékl?}
{177}{}{Vsadím se, že ve skuteènosti jste docela hodní.}
{178}{}{Pojïme si hrát na babu. Máš ji.}
{179}{}{Nepáchnete zas tak strašnì.}
{180}{}{Vidìli jsi mého neviditelného pøítele?}
{181}{}{Až budu velký jako vy, chci procestovat celý svìt.}
{182}{}{Jste hodní domorodci, ne jako ostatní.}
{183}{}{Vsadím se, že se myjete.}
{184}{}{Jste chytøejší než Torr.}
{185}{}{Je ten nùž OPRAVDU ostrý?}
{186}{}{Až vyrostu, chci být jako vy.}
{187}{}{Mùj pes miluje syrové maso.}
{188}{}{Dostal jsem blýskavý kamínek.}
{189}{}{Vidìl jste mého neviditelného pøítele?}

{190}{}{Mohu se pøidat k vašemu kmenu?}
{191}{}{Líbíte se mi.}
{192}{}{Vypadáte legraènì.}
{193}{}{Co to nesete?}
{194}{}{Chci se povozit na brahmínì!}
{195}{}{Jste z daleka?}
{196}{}{Jeeee! Ha, ha, ha!}
{197}{}{Neodcházejte!}
{198}{}{Máte nìco k jídlu?}
{199}{}{Obtìžuji vás?}
{200}{}{Kam jdete?}
{201}{}{Mùžu jit s vámi?}
{202}{}{Jak jste starý?}
{203}{}{Jak se jmenujete?}
{204}{}{Mate rád dìti?}
{205}{}{Co je to?}
{206}{}{Chcete si hrát?}
{207}{}{Co dìláte?}
{208}{}{Nevidìl jste tu nìjaké brouky?}
{209}{}{Odkud to máte?}
{210}{}{Dáte mi to?}
{211}{}{Co to dìláte?}
{212}{}{Umím bìhat rychle. Chcete vidìt?}
{213}{}{Koukej! Koukej!}
{214}{}{Maminka øíká, ze pøíliš mluvím.}
{215}{}{Kde bydlíte?}
{216}{}{Heeééj! Heeééj!}
{217}{}{Zùstanete tady?}
{218}{}{Máte dìti?}
{219}{}{Proè jste sem pøišel?}
{220}{}{Mám vás rád.}
{221}{}{Líbím se vám?}
{222}{}{Jste ženatý?}
{223}{}{Raz, dva, tøi... Už jdu!}

{300}{}{Cizinec!}
