# tenhle fajl pøelouskal: Mıval (myval@writeme.com). Naposledy editováno: 31/05/1999
{100}{}{Starı mu.}
{101}{}{Cornelius.}
{102}{}{Kromì neklidného vırazu ve tváøi vypadá úplnì obyèejnì.}

{150}{}{Vítej v Rosinì penziónu. Já jsem Róza -- chci øíct, Cornelius -- vedu tenhle penzion. Mohu ti pomoci?}
{151}{}{Jestli vám to tu patøí, tak proè se tenhle podnik jmenuje RÓZIN penzion?}
{152}{}{Hledám zlaté hodinky.}
{153}{}{Co tu dìláš?}
{154}{}{Kdo je Róza?}
{155}{}{Chci si pronajmout pokoj.}
{156}{}{Otázky? Ptal jsem se tì na nìco? Jmenuji se Cornelius.}
{162}{}{Mìl by ses léèit, starouši}
{163}{}{Farrel mìl ty hodinky doma v sejfu. Poøádnì ho zmáèkni.}
{164}{}{Ty tvoje hodinky byly ve Farrelovì domì. Mìl jsi pravdu, Farrel je tím zlodìjem.}
{165}{}{Zdá se, e jedna hodnì šikovná krysa ti sebrala hodinky. Tady jsou.}
{166}{}{Ahoj! Nevidìli jsme se u?}
{176}{}{Mùj boe! Nìkdo zabil mého nejlepšího pøítele, Farrela! Celé mìsto hledá vraha. A ho najdeme, bude viset!}
{177}{}{Ano. To je moje práce. Copak s tím nadìláš, ty starej dìdku?}
{178}{}{A jé! U je moc hodin. Budu muset jít.}
{179}{}{Róza je moje ena; pojmenoval jsem to tady po ní. Víš vùbec, e jsem enatı?}
{180}{}{Mùu se ještì na nìco zeptat?}
{181}{}{TAK PROÈ SE NEZEPTÁŠ FARRELA!? MONÁ TI PRODÁ HODINKY, KTERÉ MI UKRADL!
 Poslyš, mám teï dost práce. Musím ostøíhat brahmíny.}
{182}{}{Tenhle motel mi patøí. Nebıt mì, všechno by se tu u rozpadlo. A co øíkáš na moji stodolu? Vsadím se, e nikde nenajdeš èistší. No, však je to moje práce.}
{183}{}{A co má spoleèného provoz penzionu a èistá stodola?}
{184}{}{Róza je moje ena. Stará se o kuchyni. Vaøí nejlepší jídla široko daleko. Róza je tak skvìlá. Jednou si ji urèitì vezmu za manelku.}
{185}{}{Mám dojem, e jsi øíkal, e Róza u je vaše ena.}
{186}{}{Mám pro tebe místo. Já spím támhle. Kde chceš spát ty?}
{187}{}{Asi jsi mi nerozumìl. Chci si najmout pokoj na noc.}
{188}{}{Byl to mùj nejlepší pøítel 30 let... nebo to bylo 40 let? Na tom nezáleí, dùleité je, e ukradl moje pøesné zlaté kapesní hodinky. Patøily mojí rodinì pìt, ne... šest, .. vlastnì ètyøi generace. Ještì to vidím jasnì pøed sebou, jak jsem je poloil na stùl. A kdy jsem se tam podíval za chvilku, byly pryè.}
{189}{}{OK, pøinesu ti ty hodinky.}
{190}{}{Zkusil jsi je hledat na svém stole?}
{191}{}{Pomùete mi? To je skvìlé! Natluè Farrelovi a pøines mi moje hodinky zpátky. Asi je nìkde dobøe schoval. Radìji poøádnì prohledej jeho dùm.}
{192}{}{O èem to mluvíš?}
{193}{}{Podívejte, s tím nechci nic mít.}
{194}{}{Zabiju Farrela, a pøinesu vám ty hodinky zpátky, jo?}
{195}{}{Zabít Farrela? Proè zabíjet Farrela? Je to mùj nejlepší pøítel! Osobnì povìsím kadého, kdo by se pokusil zabít Farrela.}
{196}{}{Tu práci beru. Doufám, e odmìnu dostanu hned po dokonèení práce.}
{197}{}{Hmm... tak nic. Stejnì odjídím.}
{198}{}{Samozøejmì ti zaplatím. Hned jak zlikviduješ ten chlív a vrátíš se.}
{199}{}{Mìl jsem hodinky. Zlaté hodinky. Rád bych vìdìl, kam jsem je mohl dát...}
{200}{}{Ano, ano, ano. Hledal jsem i v prádelníku. Ale ani tam nejsou.}
{201}{}{A budu ve mìstì, podívám se po nich.}
{202}{}{Nevím, proè pomáhat takovımu bláznovi, jako jsi ty. Nezajímá mì to.}
{203}{}{Vìdìl jsem, e mu nemùu vìøit. Povìsím ho za uši, dokud mi nevrátí moje hodinky.}
{204}{}{Tady nic není. Šerif Jo a já jsme to všechno prohledali.}
{206}{}{Udìlal to? Já to tušil! Dám mu lekci, na kterou nezapomene. Radši se dr dál...}
{207}{}{To jsou moje hodinky! Odkud je máš? Vra mi je! [Vytrhne hodinky z tvıch rukou.] Tak. A radši vypadni. Zlodìje tu nemáme rádi.}
{208}{}{Prosím, není zaè. Rádo se stalo. [Dìdku jeden.]}
{209}{}{U jsi ochutnal Róziny omelety? Jsou vynikající.}
{210}{}{Vidìl jsem Jonnyho, jak si hraje u studny se svım psem Laddie. Hezkı chlapec.}
{211}{}{Nechoï na Farmu Duchù, jestli tì ivot neomrzel...}
{212}{}{Miria je pìkné dìvèe. Kdy byla malá, hráli jsme si na doktora.}
{213}{}{Davin je pìknı chlapec. Jen by mì zajímalo, proè se nepodobá svému otci?}
{214}{}{Jednou jsem sedìl na záchodì a z odpadu vylezl velkı pes. Vydìsil mì k smrti.}
{215}{}{Grisham je dobrı chlapík. Prodává nám odpad pro krmení obøích kuøat.}
{216}{}{Drte se dál od jejich kurníku! Pøi krmení mi skoro seraly ruku.}
{217}{}{Rózini psi jsou zlí, ale staèí jim hodit pár kouskù sušeného masa a dají pokoj.}
{218}{}{Farrel je mùj nejlepší pøítel na celém svìtì.}
{219}{}{Laddie je chytrı pes. Vdycky mi rozumí.}
{220}{}{Slyšel jsem o Grishamovi, e se snaí provdat svoje dìti. Zdalipak by mìla Róza pochopení, kdybych si pøivedl jinou enu?}
{222}{}{Pog? Co se vlastnì stalo s touhle hrou, hmm? Dobrá, musím jít. Moná si zahrajeme pozdìji.}
{223}{}{NAŠEL JSEM VRAHA! PØIZNÁVÁ SE K FARRELOVÌ VRADÌ! ZAVØETE HO!}
{224}{}{NAŠEL JSEM VRAHA! PØIZNÁVÁ SE K FARRELOVÌ VRADÌ! ZAVØETE JI!}
{225}{}{Já zabít Farrel.}

{300}{}{[Hmmm... Zdá se, e nìkterá slova na nìj pùsobí.] Róza... Pokoj... Hned...}
{301}{}{Joj.}

{501}{}{Já to vìdìl, e jsi zlodìj!}
{502}{}{Jak mùeš nìco takového udìlat? Svému nejlepšímu pøíteli!?}
{503}{}{Zabiju tì!}
{504}{}{Napíchnu tvoji hlavu na kùl!}

{550}{}{Zdá se bıt zaneprázdnìn.}

{600}{}{Hodinky byly vráceny Corneliovi.}
{650}{}{Spor mezi Corneliem a Farrelem byl vyøešen.}
