# tenhle fajl pøelouskal: Mýval (myval@writeme.com). Naposledy editováno: 31/05/1999
{100}{}{Hezký mladý muž.}
{101}{}{Vidíš Davina.}
{102}{}{Mladý, asi dvacetiletý muž. Je podobný Grishamovi.}

{150}{}{Jestli chceš, mùžeš mì mít.}
{151}{}{Uff! Miria není v posteli tak dobrá.}
{152}{}{Nevìøím, že bys mi mohl dìlat pasáka.}
{153}{}{Pøíštì to zkusíme ve tøech.}
{154}{}{Ooo... je to zajíèek.}
{155}{}{Zeptej se jí.}
{156}{}{Bylo to skvìlý; kdo další?}
{157}{}{Ahoj! Jmenuju se Davin; pomáhám svému otci na jatkách v Modocu.}
{158}{}{Hledám Corneliovy zlaté hodinky. Nevidìl jsi je nìkde?}
{159}{}{Co na jatkách pøesnì dìláš?}
{160}{}{Kolují tady nìjaké povídaèky o tom, co dìláš s brahmínami.}
{161}{}{Povìz mi nìco o svém otci.}
{162}{}{Ještì jednou tì zdravím.}
{163}{}{Vìdìl jsem, že se ke mnì vrátíš.}
{168}{}{Neposadíme se?}
{171}{}{Zùstaò tady.}
{172}{}{Jistì, mám èas. Ptej se.}
{178}{}{Nikde jsem je nevidìl.}
{179}{}{Mùžu se zeptat ještì na nìco?}
{180}{}{No... tedy, vlastnì, chci øíct, jen se starám o materiál. Konec koncù, jsem syn majitele a zdìdím to všechno po mém otci.}
{182}{}{To je lež. V noci chodím do stájí abych... se pøesvìdèil, že je zamèeno. To víš, všude kolem je plno divoké zvìøe.}
{184}{}{Otec provozuje jatka. Je to dobrý táta. A dám ti jednu radu, jestli s ním chceš nìco mít. Jeho obchody ho zajímají víc, než je ochoten pøipustit.}
{186}{}{Pøijdi za mnou zas, když si budeš chtít... popovídat.}
{187}{}{Teda. Nikdy bych nevìøil, že mì bude svádìt taková krasavice, jako jsi ty. Poèkat! Ty nejsi ženská! Nemìj obavy, jsi kus, a jestli si to budeš pøát, neøeknu ani slovo.}
{188}{}{To se mi jen zdá. Nemùžu uvìøit tomu, že mì svádí taková krasavice. Že mì chceš sbalit?}
{189}{}{Pohled tvých oèí je tak andìlský. Nekaž kouzlo tohoto okamžiku nìjakými slovy. Pojïme na vìc.}
{190}{}{Buï zticha; kazíš nám to. Jen seï a vychutnávej.}
{191}{}{Špatnì si to vysvìtluješ; chci se jen na nìco zeptat.}
{192}{}{Díky za nabídku, ale radìji ne. Ehmm... radši už pùjdu.}
{193}{}{Bože! Vezmi si mì! Chci tì teï hned! [Strhá ze sebe svoje obleèení, pak tvoje... a pak... to už si
 dokážeš pøedstavit]}
{194}{}{[Hihòá se] "Jsem hotovej"! Ty mùžeš být pøíštì.}
{195}{}{[O dvì hodiny pozdìji... svìt se s tebou toèí.]}
{196}{}{[O hodinu pozdìji... prožíváš nejlepší orgasmus svého života.]}
{197}{}{[O pùl hodiny pozdìji, ležíš úplnì vyèerpaná.]}
{198}{}{[Za patnáct minut a pár vzdychù pozdìji.]}
{199}{}{[Udìlal jsi to, ani sis', nesundal košili.]}
{200}{}{Musím jít. Ahoj.}

# wedding script dialog
{400}{}{Otèe!}
{401}{}{Jejky!}
{402}{}{ANO!}

{410}{}{Ehm...}
{411}{}{Eh... pokraèuj, prosím...}
{412}{}{No jasnì...}
{413}{}{No... dám na nìj pozor.}

{450}{}{Ehmm, se mnou bys nemìl mluvit.}

{500}{}{Chlapèe, bude to mít všechno na starost.}

{1000}{}{Ano, moje zlato?}
{1001}{}{Co pro tebe mùžu udìlat, miláèku?}
{1100}{}{Už se cítím úplnì zdráv a fit.}
{1200}{}{Není na mnì ani škrábnutí.}
{1300}{}{Jsem témìø zdravý, ale budu potøebovat další léky, až bude pøíležitost.}
{1400}{}{Jsem poøád dost zranìný a potøebuji další léèení.}
{1500}{}{Ne, bejby; chci jít s tebou.}
{1600}{}{Jasná vìc, dám to pryè.}
{1700}{}{OK, jsem poøád hned za tebou.}
{1800}{}{Pak tì ale nemùžu chránit. Ne, radìji budu poblíž.}
{1900}{}{Tak je to? V žádném pøípadì. Nespustím tì z oèí, moje malá buchtièko.}
{1005}{}{Nerozumíš tomu. Jen nechci, aby ses na mì tak vìšel, když nìkam jdeme.}
{1006}{}{Tvoje chyba je, že bych potøeboval, abys mi nedejchal na záda...}
{1007}{}{Ale... Ale... Co dìlám špatnì?}
{1008}{}{Copak bys ráda, moje nejmilejší?}
{1009}{}{Dík, stejnì se to zaèínalo podìlávat. A co teï, lásko??}
{1010}{}{Na jatkách jsem stahoval kùži z brahmín, takže umím pracovat s nožem. 
 Táta mì taky jednou nechal umlátit brahmínu palicí. Kdybych to potøeboval, dokážu zacházet s kyjem. Joó, a jednou mì táta nechal i støílet z pistole, ale tak jsem se polekal, že jsem ho málem zastøelil.}
{1020}{}{Potøebuju trochu místa, Davine.}

