# tenhle fajl pøelouskal: Mıval (myval@writeme.com). Naposledy editováno: 31/05/1999
{100}{}{Starı mu. Proti nìmu je i sušená køíala èerstvá.}
{101}{}{Farrel.}
{102}{}{Pøi kadém jeho pohybu je slyšet praskání kloubù.}

{150}{}{Hej, jdi pryè!}
{151}{}{Nech toho!}
{152}{}{Zlodìj!}
{153}{}{Já jsem ty hodinky neukradl, tak za mnou nechoïte a neotravujte starého chudáka Farrela!}
{154}{}{Ale Cornelius øíká, e jste ukradl jeho zlaté hodinky.}
{155}{}{Kde jste vzal peníze na nové náøadí?}
{156}{}{Mùete mi øíci nìco o Modocu?}
{157}{}{Co tady dìláte}
{158}{}{Hodinky? O èem to mluvíte?}
{159}{}{A teï co!?}
{162}{}{Copak to schováváte v sejfu ve zdi?}
{165}{}{Mùete mi ukázat vaši zahradu?}
{166}{}{Všechna ta malá havì z vaší zahrady je pryè.}
{167}{}{Pøedtím jste se zmínil o hodinkách.}
{168}{}{Jsou to ty hodinky, které hledáte?}
{169}{}{Všechny bestie mrtvé!}
{170}{}{Za-hra-da?}
{171}{}{U dost! Kolik lidí chce za mnou Cornelius ještì posílat kvùli svım hodinkám? Já jsem to neudìlal! Vlastnì jsem obì stejného zlodìje. V tu dobu, kdy zmizely hodinky, mi ukradli nìkteré z mıch nástrojù. Urèitì mi to nevìøíš, take se tady klidnì porozhlédni, jinak se tì nezbavím. No... do toho!}
{172}{}{Myslím, e se tady porozhlédnu.}
{173}{}{To vám øíkala Miria? Budu jí muset nabanèit, aby si pøíštì nevymıšlela! Podívejte, jsem moná chudı, ale mám svou hrdost. Pomohl jsem jednomu obchodníkovi opravit jeho vùz a on mi za to dal nìjaké nástroje.}
{174}{}{Pøiznejte se - udìlal jste to!}
{175}{}{A jak dokáete, e mluvíte pravdu?}
{176}{}{A to vám mám vìøit?}
{177}{}{Mohu nabídnout jen svoji èest. Nemám nic jiného.}
{178}{}{Kdy jste je nevzal vy, tak kdo si myslíte, e to byl?}
{179}{}{Mám podezøení, e ty hodinky vzal zlodìj, kterı pøijel do mìsta a u je zase pryè. Ale vùbec nechápu, na co by mu mohly bıt moje staré nástroje...}
{180}{}{A to vám mám vìøit?}
{181}{}{Ne, ale je to jediná teorie, která mì napadla. Protoe vím, e já jsem to neudìlal.}
{182}{}{Mùu mít ještì pár otázek?}
{183}{}{HA! Kdy si myslíte, e za to mùu já, proè mì rovnou nezastøelíte. Tak pojï a dostaò mì!}
{184}{}{He? To není moné!!? Schoval jsem ten sejf tak, aby ho nikdo nenašel. Musíte bıt profesionální zlodìj. Kde jste byl, kdy ty zlaté hodinky zmizely? Radìji hned odejdìte; a a nic neschází v sejfu, jinak na vás zavolám šerifa. Jo. Tak... vypadni!}
{185}{}{Modoc je malá osada farmáøù a chovatelù dobytka. Dodáváme vìtšinu jídla pro okolní mìsta a vesnice. Za naši sklizeò získáváme nejrùznìjší suroviny. Je to velmi dobrá úmluva. Ale všechno se to mùe zmìnit v období sucha. Potom máme sotva dost jídla pro sebe.}
{187}{}{Vìtšinou døu na zahradì a snaím se pìstovat ty proklaté rostliny i bez vody. Teï to nejde, protoe se mi do zahrady nastìhoval nìjakı škùdce a já se ho nemùu zbavit. A navíc - nikdo mi nepomùe, protoe si myslí, e jsem Corneliovi ukradl jeho zlaté hodinky.}
{188}{}{Vìtšinou døu na zahradì a snaím se pìstovat ty proklaté rostliny i bez vody. Teï to nejde, protoe se mi do zahrady nìco nastìhovalo a já se toho nemùu zbavit. Bez potravin z mé zahrady umøu hlady.}
{189}{}{Moná e vám mohu pomoci, za menší odmìnu.}
{190}{}{Pomohu vám.}
{191}{}{Pøiznejte se ke krádei tìch hodinek a já vám pomohu.}
{193}{}{Rozhlédni se! Jsem starı, chudı mu. Nemám dost jídla ani pro sebe, a ty ještì chceš odmìnu.}
{194}{}{Dobrá. Stejnì vám i tak pomohu.}
{195}{}{To je mi líto, nemohu vám pomoci.}
{196}{}{To by bylo skvìlé. Ani ti za to všechno nemohu podìkovat. Moje zahrada leí kousek vıchodì. Pojï se mnou, ukáu ti cestu.}
{197}{}{Díky! Jsi opravdovı hrdina. Jen málo lidí by riskovalo svùj ivot pro úplného cizince. Díky! Díky! Díky! [Máš zas ten neurèitı pocit]}
{198}{}{Mùu se vás ještì na nìco zeptat?}
{199}{}{To radìji umøu, ne abych pošpinil své dobré jméno! Táhni k èertu!}
{200}{}{Kadı mì obviòuje z krádee zlatıch hodinek mého nejlepšího pøítele Cornelia. Já a Cornelius jsme byli vdy pøátelé; nikdy bych to neudìlal. Všude jsem je hledal, abychom mohli bıt opìt dobøí pøátelé, ale neuspìl jsem.}
{201}{}{Kdy na to pøijdu, dám vám vìdìt.}
{202}{}{To je opravdu špatné. Mohu se ještì na nìco zeptat?}
{203}{}{Opravdu? Nikdo mi nechce pomoci, protoe si myslí, e jsem ukradl ty hodinky. Bylo by to skvìlé, mít na chvíli spojence. U jsem se na to ptal snad kadého, a nic. Tvrdí, e si vymıšlím. Moná, e vám øeknou nìco, co mnì øíct nechtìli. Taky nebude na škodu porozhlédnout se okolo Rózina penzionu; Cornelius je známı tím, e všude zapomíná svoje vìci.}
{205}{}{Poèkej, podívám se! Ano, to jsou ony! Øíkáš, e ty hodinky ukradla krysa z kanalizace? A vy jste se tam vydal a našel je? Skvìlé! Musím je dát okamitì Corneliovi! Mùeme bıt zase pøátelé. Díky.}
{206}{}{OK. Mùete udìlat pro starého Farrela malou slubu, mùj drahı pøíteli? Mám problém se škùdci v zahradì. Zniète je a dostanete odmìnu.}
{207}{}{Ne, ne, ne... já neudìlat to.}
{208}{}{Jo, udìlat to.}
{209}{}{Pá pá!}
{210}{}{Tak potom vypadni, ty zabednìnı tupèe!}
{211}{}{To je od tebe milé, chlapèe. [Bere tì za ruku a vede do zahrady.] Nechtìl bych tì ztratit. Pøijï za mnou, a vyhubíš ty škùdce.}
{212}{}{Drahoušku. Jsi tak laskavá ke starému mui. [Bere tì za ruku a vede do zahrady.] Nechci o tebe pøijít. Pøijï za mnou, a vyhubíš ty škùdce.}
{213}{}{Fantastické! Tady je tvoje odmìna. [Zaboøil ruce do kalhot a našel napùl snìdenou sušenku.] Tak tady to je, vezmi si svou sušenku a jdi si hrát ven.}

{300}{}{Zabiju toho hajzla.}
{301}{}{Nenávidím ho...}
{302}{}{Grrr...}

{501}{}{Neukradl jsem ty pitomı hodinky!}
{502}{}{Øíkám ti, jsem nevinnı!}
{503}{}{Ty netrefíš ani vrata od stodoly!}

{550}{}{Nestará se o to, co øíkáš.}

{600}{}{Dlouhotrvající spor mezi Farrelem a Corneliem byl ukonèen usmíøením.}
