# tenhle fajl pøelouskal: Mıval (myval@writeme.com). Naposledy editováno: 31/05/1999
{100}{}{Velmi èilı starı mu.}
{101}{}{Grisham.}
{102}{}{Nemùeš si ho rychle nikam zaøadit, ale vypadá pøátelsky.}

{151}{}{Øíkal jsem, e tì dostanu!}
{152}{}{Chachachacha!}
{153}{}{Vypadni!}
{154}{}{Mám práci!}
{155}{}{Vìdìl jsem, e moje dcera je divná.}
{156}{}{Nìkdo má rád holky, jinı zase vdolky...}
{157}{}{Je mi zle.}
{158}{}{Vìdìl jsem, e mùj syn je divnı.}

{159}{}{Øekl bych, e jste docela pìknı páreèek.}
{160}{}{Dobøe se o moji dceru starej...}
{161}{}{Dobøe se o mého syna starej...}

# Node 0
{162}{}{Jmenuji se Grisham. Vítej na mıch jatkách. Zdríš se?}
{163}{}{Jen na chvíli. Chci nakoupit nìjaké zásoby na cestu.}
{164}{}{Èistì náhodou, nevidìl jsi tu nìkde leet zlaté hodinky?}
{350}{}{[vrhneš pohled na Bessy] Odcházím.}

# Node 1
{165}{}{Co pro tebe mohu udìlat?}
{166}{}{Chci koupit to povìstné sušené maso.}
{168}{}{Mùeš mi øíct nìco o vašich jatkách?}
{169}{}{Koukám, e sucha nemají vliv na obchody.}
{360}{}{Neudìlal bys pro mne trochu sušeného masa?}

# Node 2
{170}{}{Vìdìl jsem, e to zvládneš. Dobrá, dluím ti $1000 za odvedenou práci. Kolik e jsi to omylem pobil brahmín?}
{171}{}{. No to je teda pìknı. Take po $100 za brahmínu, to potom dìlá
$}
{172}{}{. Jo, a nezkoušej mi lhát o poètu zabitejch brahmín -- jeden z mıch chlapcù tì tajnì sledoval.}
{173}{}{Nikdy jsi nemluvil o poplatku za mrtvı brahmíny!}
{174}{}{Ty intrikánskej, vyschlej starej dìdku. Dost! Dobøe si pamatuj - tohle je naposledy, co jsi mne tak podvedl!}
{175}{}{Díky, tako; je radost s vámi obchodovat.}

# Node 3
{176}{}{Jak se tady opovauješ ukazovat? Díky tvojí zbabìlosti jsem pøišel o deset brahmín. Jestli se mi chceš omluvit, $1500 bude staèit na pokrytí mejch ztrát.}
{177}{}{Vdy ty brahmíny nemìli vìtší cenu jak $1000?}
{178}{}{Tolik penìz nemám, a i kdyby, nedám je takovımu podvodníkovi, jako jsi ty.}
{179}{}{Mám své peníze v pokoji; musím pro nì dojít.}

# Node 10
{180}{}{Aha! Samozøejmì, samozøejmì. Take na cesty ti mohu doporuèit skvìlé sušené plátky z brahmíny. Na cestách se nezkazí a jsou dobré. Jen $10 za balíèek. Máš zájem?}
{181}{}{To zní dobøe; dejte mi jedno balení.}
{182}{}{Ne, díky, moná pozdìji. Ale chci se vás na nìco zeptat.}
{183}{}{Rád poslouím. Chceš ještì nìco jiného?}
{185}{}{Poèkej! Zdá se, e máš velkı zkušenosti. Nechceš si vydìlat nìjakı prachy?}
{186}{}{Opravdu si nechceš pøivydìlat? Myslím, e to snadno zvládneš.}
{187}{}{No... pøijde na to... jak a co mám dìlat... a hlavnì taky - KOLIK ZA TO DOSTANU?}
{188}{}{Tak chytrost ti nechybí - jako vopice! Pøipomínáš mi, jakej jsem byl za mlada. Je to jednoduchı; stahujou se sem z hor nìjakı divokı psi a hledají jídlo. Pro psy jsou brahmíny snadná koøist a v noci napadají moje stáda. Pobij je a dostaneš $1000 jako odmìnu.}
{189}{}{Mám pocit, e pøede mnou ještì nìco skrıváš, dìdo. Tak o co jde?}
{190}{}{Haha, jsi jako liška, nic ti neujde. Vìdìl jsem, e to na tebe nemám zkoušet. Háèek je v tom, e za kadou zabitou brahmínu ti strhnu $100. Platím dobøe za dobrou práci a za chyby zase platíš ty. To je risk.}
{191}{}{Dobøe! Jdi v noci na pastviny a zabij smeèku divokejch psù, co napadají moje brahmíny. Vra se, a bude práce hotová.}
{192}{}{No skvìlı. Nadrenej èmuchal! Tak Cornelius poøád hledá svoje hodinky? Proè se nesmíøí s tím, e jsou prostì pryè? Ty mizernı hodinky stejnì nikdy nešly a sním celou brahmínu, jestli byly opravdu zlatı. Vzdej to, nikdy je nenajdeš.}
{193}{}{Vlastnì ano, dohodli jsme se s Farrelem, e se po nich podívám.}
{194}{}{Mohu mít nìjaké otázky?}
{195}{}{Díky, ale radši budu hledat dál.}
{196}{}{Ne? Fakt ne? Urèitì? Pøísahal bych, e sem ti... hmm, moná si pøíštì dáš pozor, ne vezmeš nìjakou práci. Ale jestli ti to nevadí, mìl bych pro tebe jinou práci.}
{197}{}{Hehehe. No, pøijde na to. Zùstaneš ve mìstì déle? Buahahaha!}
{198}{}{Vidím, e nejsi ádnı hlupák. OK - $1000 a jsme vyrovnanı. Ruku na to.}
{199}{}{[POTØESEŠ SI RUKOU S GRISHAMEM]}
{200}{}{Tak poèkejte. Kdy o tom tak pøemıšlím, ty brahmíny byly pìknì vyzáblı. Co takhle $750 ?}
{201}{}{Ale ne, mìním názor - nezaplatím vám nic.}
{202}{}{[Široce se na tebe usmìje] Rád vidím takovıho charakterního èlovìka.}
{203}{}{[Grisham zrudne a procedí skrz zaaté zuby.] OK, tak teda $750. Dej sem prachy!}
{204}{}{Víte, $750 je poøád trochu moc. Ty brahmíny by stejnì chcíply, i kdyby je psi neserali. Ale nejsem úplnı lakomec; dám vám $50.}
{206}{}{FAJN! DEJ MI PRACHY A VYPADNI!}
{207}{}{[ODCHÁZÍŠ BEZ ZAPLACENÍ]}
{208}{}{Zapamatuj si, nìkdo tì sejme. Kdy ne já, tak nìkdo jinı.}
{209}{}{[Grisham se smìje tak, e radši o krok ustoupíš.] Proè si radši nevezmeš peníze? Mám pocit, e je budeš potøebovat.}
{210}{}{Hmmm, a co chceš vlastnì slyšet? Provozuju jatka tady v Modocu. Prostì - chceš nìco porazit, pøivedeš to ke mnì, zabiju to a vyudím nejlepší sušenı maso široko daleko.}
{211}{}{A co s vnitønostmi a ostatními zbytky zvíøete?}
{213}{}{Vlastnì mi to dokonce pomáhá. Nikdo nemá dost potravy pro svoje brahmíny, a tak se jejich poèet poøád sniuje. Ale je to jen doèasné; musíš to vidìt komplexnì. Se sniováním stavu brahmín pùjdou moje obchody z kopce.}
{215}{}{[Grisham prochází kolem tebe, rıpne do tebe, pak ti otevøe ústa a prohlíí zuby.] Ale! Pìknı, zdravı exempláø. Budeš dobrej. Sleduj... zlí pejskové zabíjí hodné brahmíny. Jdi a pobij zlé pejsky pro kamaráda Grishama.
 Grisham ti dá velkou odmìnu. OK?}
{216}{}{Ne, pejsky já mít rád. Zlí lidé nemít rádi pejsky. Já jít pryè od zlı mu.}
{217}{}{Ano, udìlat to. Jít!}
{218}{}{Dobøe! Pamatuj si - ti zlí dìlají 'Haf! Haf!', dobrá zvíøátka dìlají 'Bùùù.' A nezabiješ hodná zvíøátka.}
{219}{}{Zdá se, e nemáte moc penìz. Na dluh nedávám a zadarmo u vùbec ne.}
{221}{}{To je domluva jak s neandrtálcem. Zmiz odsud!}
{222}{}{Uh... Vezmi si peníze, buï hodnı neandrtálec a u jdi.}
{223}{}{Chytrá hlava! Dobøe, povím ti to, kdy se ptáš. Prodávám i zbytky zvíøat. Balthus si obvykle bere vnitønosti a Róza koupí cokoliv, co u nepotøebuju. Dìlá z toho polívku pro svoje psy.}
{225}{}{Dìláš si legraci? Kadej ví, e Farrel sebral ty hodinky. Proè by tì jinak pobízel v jejich hledání, kdyby je sám neukradl!?! Nebo je to trik, aby kadıho pøesvìdèil, e to neudìlal. Musím o tom pøemıšlet.}
{228}{}{Hele, ani se mi to nepokoušej vysvìtlit. Nechci o tom slyšet. Seenu si knìze, co má na starosti všechny ty oficiální vìci a tak...; a ty si vezmeš s sebou mého synka, a pùjdeš.}
{229}{}{Nemùu øíct, e by mì to tak trápilo, ale nemùu jí nechat ít v tomhle domì, potom, co jsem vidìl... Musíte se vzít a odejít z mìsta.}
{230}{}{Nechceš mi vysvìtlit, co tu dìláš s mojí dcerkou?}
{231}{}{Nechceš mi vysvìtlit, co tu dìláš s mım synkem?}
{232}{}{Vysvìtlím ti to, tako. Víš, jsou ptáèkové, vèelièky...}
{233}{}{Jsem lékaø a jen jsem jí dìlal kompletní prohlídku.}
{234}{}{Jsem lékaøka a jen jsem mu dìlala kompletní prohlídku.}
{235}{}{Není to tak, jak si myslíte.}
{236}{}{To je skvìlı. Rád budu mít za zetì takovıho chytráka. Tak pojï, synku... Skonèeme s tím.}
{237}{}{To je skvìlı. Rád budu mít za snachu takovou chytraèku. Tak pojï, dcerko... Skonèeme s tím.}
{238}{}{Já to vidím tak, e jste si s mojí dcerou hráli na brahmíny v dobì páøení.}
{239}{}{Já to vidím tak, e jste si s mım synem hráli na brahmíny v dobì páøení.}
{240}{}{OK, moná e to tak bylo. Ale byl to jen sex, ádná láska nebo nìco takového.}
{241}{}{Rozumím moc dobøe. Hormony, roèní období a tak... }
{242}{}{Jsem rád, e mì chápete.}
{243}{}{Rozumím. Je ti doufám jasnı, e se teï musíte vzít. Nemùeme si tu dovolit pomluvy. Teï pùjdeme za knìzem. Nechtìj, abych do tebe musel nasypat broky.}
{244}{}{Opravdu? Tak proè jste byli oba nazí?}
{245}{}{Mikrobi! Mám na mysli MIKROBY! Pøi takovıch vyšetøeních je tøeba zachovat absolutní èistotu.}
{246}{}{Tak jestli jsi doktor, tak je to OK. Ale radši se oblíkni. Z nedorozumìní vznikají rùznı pomluvy. Kdy u tu jsi, podívej se na moji øi... mám tam nìjakı problémy. Hned si sundám kalhoty...}
{247}{}{Err... podívám se pozdìji. Teï na mnì èeká další pacient. Sbohem.}
{248}{}{Jo. Tak teï pùjdeš s mnou sehnat knìze. A nedìlej hlouposti, nebo budeš TY potøebovat doktora.}

{260}{}{Bezva. Vìdìl jsem, e to zvládneš. Myslím, e ti dluím $1000 za dobøe odvedenou práci. Tady jsou.}

# rape script dialog
{300}{}{O co tady, sakra, jde?}
{301}{}{Uhhh... pane, jen sem...}
{302}{}{Okamitì z ní sundej ty svoje špinavı pracky...}

#define wedding script dialog
{400}{}{O co tu jde?}
{402}{}{Do prdele! Já vìdìl e s }
{452}{}{ není nìco v poøádku. Teï u zbıvá jen jedinı zpùsob, jak to napravit!}
{403}{}{Jak se opovauješ pošpinit èest }
{453}{}{?! Je jedinı zpùsob, jak to napravit!}
{404}{}{Hernajs nemùeme tu pøísahu prostì pøeskoèit?}
{406}{}{Chlapèe...}
{407}{}{Holèièko...}
{410}{}{Nechtìj abych udìlal z }
{460}{}{ vdovu.}
{461}{}{ vdovce.}
{412}{}{Mirie}
{413}{}{Davina}

{220}{}{Nikam nepùjdeš, chlapèe!}
{221}{}{Nikam nepùjdete, sleèinko!}

# Node 4
{500}{}{To je pìknı zviøátko, co tady máš s sebou. Bylo by z nìj fajnovı sušenı maso. Hele, já to udìlám a nechám si z nìj pár kouskù jako odmìnu. Co ty na to?}
{501}{}{Nikdy! Miluju Bess. Nikdo z ní nebude dìlat sušenı maso.}
{502}{}{To zní dobøe. Kdy se mùu zastavit pro maso?}
{503}{}{Zapomeòte na to, dìdo. Já odcházím.}

# Node 5
{510}{}{Aha... ty tu brahmínu nemáš jenom tak... Nechtìl jsem ti brát tvoje 'potìšení'. Noci v poušti by bez ní byly tak hroznì osamìlı, co? Tak, a dost u øeèí; mám nìjakou práci.}

# Node 6
{515}{}{Vıbornì! Pøijï za tıden. Maso si mùeš si vyzvednout v udírnì hned za jatkami. Nechám ho tam pro tebe v pytli. Dobrı obchod.}

# Node 50
{600}{}{Nazdar }
{1600}{}{. Doufám, e se dobøe staráš o mojí dcerku Miriu. Ona je svìtlo mého ivota a zlomilo by mi srdce, kdyby se jí nìco stalo. Mimochodem, kde je teï? Doufal jsem, e ji uvidím.}
{601}{}{Ááá, jestlipak to není }
{1601}{}{. Tak jak se ti zamlouvá ivot enatého? Vidím, e Davin s tebou necestuje. Postrádám ho. Tøeba a pøijdeš pøíštì na návštìvu, vezmi ho sebou. Potìší to starého mue, kdy zase uvidí svého synka.}
{602}{}{Ehmm, je mrtvı.}
{603}{}{Ehmm, je mrtvá.}
{604}{}{Miria byla naivu, kdy jsem ji opustil, ale myslím, e teï je mrtvá.}
{605}{}{Davin byl naivu, kdy jsem ho opustila, ale myslím, e teï je mrtvı.}
{606}{}{Davin...ehm, nemohl se mnou jít, ale vyøídím mu váš pozdrav, a ho zase uvidím.}
{607}{}{Miria...ehm, nemohla se mnou jít, ale vyøídím jí váš pozdrav, a ji zase uvidím.}

# Node 51
{700}{}{Arggg... [Grishamova tváø se zraèí pøekvapením, pak se najednou chytil za prsa a zhroutil se na podlahu.]}

# Node 52
{750}{}{Musím zpátky do práce. Uvidíme se potom.}

{800}{}{Grishamovy brahmíny byli ochránìny.}