# tenhle fajl pøelouskal: Mıval (myval@writeme.com). Naposledy editováno: 01/06/1999
{101}{}{Prùmìrná osoba, prùmìrné vıšky, prùmìrného vzhledu. Nic mimoøádného.}
{102}{}{Jo.}
{103}{}{Obchodník Jo.}
{104}{}{Šerif Jo.}
{105}{}{Starosta Jo.}
{106}{}{Smírèí soudce Jo.}

{150}{}{Zabili jsme všechny. (povzdech) I dìti.}
{151}{}{Setkáme se na Farmì Duchù. Okamitì zaútoèíme.}
{152}{}{Díky za záchranu obèanù Modocu.}
{153}{}{Co to dìláš?}
{154}{}{Hej! Nech to na pokoji!}
{155}{}{Zlodìj!}
{156}{}{Je mi líto, ale kvùli suchu je tohle trištì doèasnì uzavøeno.}
{157}{}{A kdo øíká, e jsem tu kvùli obchodu?}
{158}{}{Jsem tu prvnì. Co mi mùeš øíct o tomhle mìstì?}
{159}{}{Nemáš náhodou zlaté hodinky na prodej?}
{160}{}{GECK!}
{161}{}{Co pro tebe mùu udìlat?}
{162}{}{Hledám jednu vìc a zajímalo by mne, jestli bys ji nedokázal sehnat.}
{164}{}{Chci koupit zlaté hodinky. Nevíš, kde mohu nìjaké sehnat?}
{165}{}{Máš nìco na prodej?}
{166}{}{Mùeš mi nìco povìdìt o tomhle mìstì?}
{167}{}{Co tady dìláš?}
{168}{}{GECK!}
{169}{}{Ty jsi zpátky?! Tak co víš o farmì?}
{170}{}{Problém s Farmou Duchù je vyøešenı. Mùete se tam kdykoliv nastìhovat.}
{171}{}{Mám pro tebe zprávu od vùdce Svìtloplachù.}
{172}{}{Z-P-R-Á-V-A.}
{173}{}{Far-ma?}
{174}{}{Špatné zprávy!}
{175}{}{Já jít pryè.}
{176}{}{Vrátím se zpìt, a budu mít víc informací.}
{179}{}{V Denu je jeden opilec, na kterého se hodí Karlùv popis. Øíká o sobì, e bıval farmáø.}
{180}{}{Ti duchové jsou jen atrapy, loutky obalené vnitønostmi z brahmín. Svìtloplachové vás chtìli odehnat od své úrody.}
{181}{}{Co mám dìlat dál?}
{182}{}{Co? Hmm... nováèek. Vítej v Modocu. Jmenuji se Jo, patøí mi trnice tady v Modocu.}
{183}{}{Mám úkol. Hledám svatı GECK. Nevíš, kde se dá sehnat?}
{186}{}{Máš štìstí. Vím, kde je. Moná bychom mohli udìlat obchod.}
{187}{}{Obchod? Jen mi øekni, kde najdu GECK a já pùjdu svojí cestou.}
{188}{}{Koukej mi rychle øíct, kde najdu GECK, nebo špatnì skonèíš.}
{189}{}{Co chceš za tuhle informaci?}
{190}{}{Ach ano, co jsem to chtìl... jestli to nevíš, tak naše osada proívá jedno z nejhorších období sucha. Období dešù bylo letos neobvykle krátké a naše úroda usychá. Na rovinu, naše úroda je prakticky znièená.}
{191}{}{Hmm... snad neèekáš, e dokáu pøivolat déš?!?}
{192}{}{[Zasmìje se] Ne, ne... samozøejmì ne. Nìco tak nesplnitelného bych po tobì nikdy nechtìl. To bys asi opravdu nedokázal. Ale jak øíkám, potøebujeme nìjak pomoci.}
{193}{}{OK, poslouchám.}
{194}{}{Na kraji mìsta leí farma, která by tam nemìla bıt. Pøed nìkolika lety se tam prostì najednou objevila - odnikud.}
{195}{}{Chceš øíct, e ta farma prostì vyrostla pøes noc?}
{196}{}{Skupina našich lidí byla na lovu, kdy jsme si všimli nové farmy. Ale to nebylo divné. Brzy potom se nìkolik našich lidí vydalo na návštìvu nového souseda, jen abychom se seznámili.}
{197}{}{Dál.}
{198}{}{Po nìkolika mìsících neúspìšného hledání majitelù jsme došli k závìru, e farma musí bıt opuštìna. A tak ne abychom nechali úrodu shnít, poslali jsme tam Karla.}
{199}{}{Hmm...}
{200}{}{A pak se to pokazilo. Karl zaèal vyprávìt o divnıch svìtélkujících postavách, které v noci dohlíejí na úrodu a krmí zvíøata. Všichni jsme se smáli jeho historkám. Jednoho dne se ale Karl nevrátil do mìsta.}
{201}{}{Co se mu stalo? Hledali jste ho?}
{202}{}{Samozøejmì! Hned jsme se tam vydali. [Divoce se mu roztøásl hlas.] Hrùza a dìs. Lidská tìla rozeseta kolem dokola. Nìkterá ukøiována, jiná zase hnijící na slunci. Stále se v noci budím hrùzou a vidím to pøed oèima.}
{203}{}{Nech mì hádat. Mám jít na farmu a zjistit, co se tam dìje.}
{204}{}{Za jinıch okolností bychom nechali to proklaté místo bıt, ale z nìjakého neznámého dùvodu se tam skvìle daøí obilí, navzdory tìm hroznım vedrùm. Jestli se nám nepodaøí sehnat potravu, brzy zahyneme. Pomùeš nám ty duchy vyhnat?}
{205}{}{A co z toho budu mít?}
{206}{}{Jako odmìnu za tvoji pomoc ti prozradím, kde najít GECK.}
{207}{}{OK, domluveno. Na potvrzení úmluvy si odøízni malíèek.}
{208}{}{Dobrá, souhlasím. Uka mi, kde je Farma Duchù.}
{209}{}{CO?!? Takhle u vás potvrzujete smlouvy? Jsme ale zoufalí a vìøíme, e jedinì ty nám mùeš pomoci. Take si myslím, e je to malá obì, jestlie zachrání celé mìsto. [Jo vyndává nù a chystá se uøíznout svùj pravı malíèek!]}
{210}{}{[Zastavíš ho právì vèas.] Poèkej! Vidím, e mluvíš pravdu a skuteènì potøebuješ pomoc. Pomohu vám.}
{211}{}{Teï vezmi prst a namoè ho do jemné èesnekové omáèky. Vynikající chu!}
{212}{}{Farma duchù leí jeden den cesty severovıchodnì odsud. [Vytahuje mapu a ukazuje na bod severovıchodnì od Modocu.] Vra se, a na nìco narazíš.}
{213}{}{[Jo klidnì zaloví rukou v batohu a vytahuje brokovnici!] Tak co budeš øíkat na tohle, ty osle!}
{214}{}{[BOOM!]}
{215}{}{Dìláš si srandu?! Proè bych si sekal prst. Jsem zoufalı, ale nejsem hlupák! Tak ještì jednou: chceš tu práci nebo ne?}
{216}{}{OK, udìlám to pro vás. Kde leí ta farma?}
{217}{}{Zøejmì na tom ještì nejste tak špatnì. Odcházím.}
{218}{}{Co, co? Øíkáš GECK?}
{219}{}{Jo. Øíkat GECK.}
{220}{}{Já jít pryè.}
{222}{}{Jmenuju se Jo. Jasnı? To je jedno; hele, vidíš tamhletu hranatou vìc? Tak to jsou dveøe. Jdi a zvenku je zavøi.}
{223}{}{[Nerozumíš, co pøesnì po tobì chce, ale ušklíbneš se a radìji odcházíš.]}
{224}{}{[Chvilku o nìèem pøemıšlí a pak se na tebe usmìje.] Moná se pøece jenom dohodneme. Jmenuji se Jo; patøí mi místní trnice. Mám nìjaké informace o GECKu. Máš zájem?}
{225}{}{[Souhlasnì pøikıvneš.]}
{226}{}{[Zápornì zavrtíš hlavou.]}
{227}{}{Vıbornì! Máme tu Farmu Du... ehm, farmu. Leí jeden den cesty na severovıchod. Dìjí se tam divné vìci. Postarej se o to a a se vrátíš, dám ti informace o GECKu.}
{228}{}{Dob-rá. Já jít.}
{229}{}{Nemáme spolu o èem mluvit. Tam jsou dveøe.}
{230}{}{Hohó. To je na tebe ještì moc velkej krajíc. Proè radši nepøijdeš a ten krajíc bude o trochu menší? Mìj se pìknì a pozor na dveøe, a budeš odcházet.}
{231}{}{Dobrá, vítej v Modocu. Já jsem Jo a patøí mi místní trnice. Nemáme toho moc; jen pár farem, jatka, Rózin penzión a koeluna, abychom mohli vyrábìt zboí na prodej. Ale tyhle sucha mohou všechno znièit.}
{232}{}{Povìz mi nìco o jatkách.}
{233}{}{Rózin penzión?}
{234}{}{Povìz mi o trnici.}
{235}{}{Kde je koeluna?}
{236}{}{Mùu se ještì na nìco zeptat?}
{237}{}{Na jatkách pracuje Grisham a jeho syn Davin. Je to smìrem na vıchod. Dìlají nejlepší sušené maso na téhle stranì hor.}
{242}{}{Rózin penzión je na severu mìsta. Všichni pocestní tam chodí, aby ochutnali její svìtoznámé omelety. Nìkdo dokonce tvrdí, e ty omelety mají léèivé schopnosti. Na rovinu, myslím si, e je to hromada nesmyslù.}
{247}{}{Jdi rovnou za nosem. Cítíš ten odpornı zápach? Tak to je koeluna na severu. Kdy pomineš ten smrad, nenajdeš lepší místo, kde koupit koené zboí. Balthus umí z kùe udìlat hotové zázraky.}
{252}{}{Jak u jsem øekl, jmenuji se Jo a patøí mi trnice v Modocu. Organizuji obchod mezi Modocem a dalšími mìsty. Prodáváme jídlo a koené vırobky. Ale za tohohle období sucha bude brzy se vším konec. Jsme z toho zoufalí.}
{257}{}{O èem chceš povídat? Jatka, Rózin penzión, koeluna nebo trnice?}
{262}{}{Takhle ne. Nemohu ti pomoci, pokud nebudeš konkrétnìjší. Nejsem jasnovidec.}
{263}{}{Hledám svatı GECK.}
{264}{}{To nevadí.}
{265}{}{Kromì vırobkù od lidí z Modocu nic nemám. To víš, ty sucha... ještì máš zájem?}
{266}{}{Chci se podívat.}
{267}{}{Ne díky, ale mám ještì nìjaké dotazy.}
{268}{}{Ne, moná pozdìji. Teï u musím jít.}
{269}{}{To je dobrá otázka. Vìtšinu èasu se starám o trh, ale obèas jsem šerif, starosta nebo i soudce.}
{270}{}{Jóó; to teda musíš bıt mezi spoluobèany velmi oblíbenı.}
{271}{}{Díky za informace; teï u pùjdu.}
{272}{}{Pche... hodili to na mnì. Jednou jsem byl mimo mìsto pro nìjaké zásoby, a kdy jsem se vrátil, zjistil jsem, e mì obèané zvolili. Nikdo jinı to nechtìl dìlat. Ale v podstatì nemusím stejnì nic dìlat, a to mi vyhovuje.}
{273}{}{Mùu se ještì na nìco zeptat?}
{274}{}{CO!? Chceš mì napálit? Kadı ví, e starej Cornelius svoje hodinky ztratil. Dokonce chtìl, abych prohledal dùm jeho nejlepšího pøítele. Radši do toho nestrkej nos! Sbohem!}
{275}{}{[Pøevezme vzkaz od Svìtloplachù.] Co je to? Vzkaz od lidí ijících na Farmì Duchù. To je úasné; èetl jsi... vlastnì... já vím e ne. Je zde ještì pár vìcí, které je nutné projednat mezi Svìtloplachy a lidmi z Modocu, ale to je na tebe pøíliš sloité, take se o to nemusíš starat.}
{276}{}{GECK, hned teï!}
{277}{}{Inu, to bude trochu sloitìjší. Víš, já vlastnì nevím, co je GECK. Ale znám jedno místo, které se jmenuje Gecko. Nikdy jsem tam nebyl, ale je to nìkde na vıchodì. Mrzí mnì, e jsem tì musel podvést. Pøál bych si ti dát nìco lepšího jako odmìnu, ale mùu nabídnout jen slevu na naše zboí. Nejsem teï zrovna dobøe
 zásoben, ale doufám, e se to brzy zlepší a budu tì moci vybavit všemi zásobami.}
{278}{}{Sa-kra!}
{280}{}{Chápu, e se zlobíš, ale nebudu se omlouvat. Potøebovali jsme nìjakıho èlovìka a na tebe to zrovna padlo. Mùu ti øíct jedinı: "Moc díky a sbohem".}
{282}{}{Ano... farma. Farma na severovıchodì. Jdi tam. Zbav nás tìch starostí.}
{283}{}{To je vıborné! Hned tam pošlu lidi, aby sklidili úrodu. Díky tobì jsme zachránìni.}
{284}{}{KDE JE GECK?!}
{285}{}{Svìtloplachové? Kdo je to? Co je to? [Jo otevírá a ète zprávu.] To je neuvìøitelné! ili celou tu dobu pod zemí. Øíkají, e chtìjí vymìnit jídlo za léky a další vybavení. Ale nevím, zda jim mùeme vìøit. Konec koncù, zabili Karla a všechny ostatní lidi. Co si myslíš vy?}
{286}{}{Všechna ta tìla byla falešná. Jen panáci obalení do vnitøností z brahmín. Chtìli vás odradit od krádeí úrody.}
{287}{}{Jsou velmi citliví na svìtlo. Myslím, e pár lidí s pochodnìmi by je mohlo zlikvidovat.}
{288}{}{Karl byl v Denu. Odešel, protoe mu tady nikdo nevìøil, e duchové existují.}
{289}{}{Drí Jonnyho jako rukojmí! Musíme ihned zaútoèit!}
{290}{}{Podvod! Ale já ty tìla vidìl na vlastní oèi. V kadém pøípadì, Karl je poøád nezvìstnı. Jak tohle vysvìtlí? Nemohu jim vìøit, dokud se nepøesvìdèíme, e nic neskrıvají.}
{292}{}{Øíkali, e èlovìk, kterı se tam pøed nìkolika lety nastìhoval, najednou zmizel.}
{293}{}{Karl by to neudìlal. Urèitì ho zabili! Ne, dokud nezjistíme, co se stalo Karlovi, jim nemùeme vìøit. Doufal jsem, e to nebudeme muset udìlat, ale je tøeba zabrat jejich farmu. Buï my, nebo oni.}
{294}{}{Ne, poèkej! Zjistím, co se stalo Karlovi. Musí existovat nìjaké vysvìtlení, proè zmizel.}
{295}{}{Souhlasím s útokem! A jejich oèi - to je jejich slabé místo.}
{296}{}{S tím nesouhlasím. Vím, co se stalo na Farmì Duchù. Teï mi øekni, kde najdu svatı GECK.}
{297}{}{Máš mìsíc na to, zjistit, co se stalo Karlovi. Jestlie se do té doby nevrátíš, seberu všechny obyvatele Modocu a zaútoèíme na farmu silou.}
{298}{}{OK, jeden mìsíc! Do té doby nic nedìlejte. Já se vrátím.}
{299}{}{Potøebuju víc èasu. Za tak krátkou dobu nemùu nic zjistit.}
{300}{}{Mìsíc, ani o den déle! U jsem ti øíkal, e jsme v zoufalé situaci. Naše zásoby se neustále ztenèují a moc u nezbıvá. Máme potraviny na mìsíc; potom zemøeme hlady. Zaènu hned shánìt všechny obyvatele. Radìji si pospìš!}
{301}{}{Prosím, nedìlejte nic unáhleného, ne se vrátím!}
{302}{}{[Pøekvapenì] Den! Já-já si hned myslel, e jsme na nìj byli pøíliš tvrdí. Dokáu si pøedstavit, èím vším musel projít, kdy mu nikdo nevìøil, co se stalo na Farmì Duchù. Øíkáš, e je z nìj teï opilec v Denu? Budu ti velmi vdìènı, kdy mu vzkáeš, e u mu vìøíme a e se mùe vrátit. Mezitím bychome se mohli lépe seznámit se Svìtloplachy.}
{303}{}{Tak. Z mé strany byla dohoda splnìna. Teï mi øekni, kde najdu GECK.}
{304}{}{[Rozpaèitì] Um... no, víš, vlastnì nevím nic o GECKu, kterı hledáš. Pochop: byli jsme zoufalí! Ale vím aspoò o místì, které se jmenuje Gecko. Leí na vıchodì. Kdybych byl sázkaø, vsadil bych se, e ten tvùj pøístrojek GECK je tam. Rád bych ti dal víc, ale jsme velmi chudí a moc toho nemáme. Ještì ti mohu
 nabídnout nìjaké zboí za vırobní cenu. Ale bude mi potìšením tì zásobit na cesty, a toho budu mít více, a jsem si jist, e ostatní obyvatelé Modocu také. Díky! Díky za naši záchranu.}
{305}{}{Take oni zabili Karla stejnì jako ty ostatní lidi nabodnuté na kùly pøed jejich farmou. OK, udìláme to. Víš, kde je jejich úkryt a mùeš nám ukázat cestu. Povedeš nás proti tìm zrádnım Svìtloplachùm?}
{306}{}{Samozøejmì! Pomohu vám porazit Svìtloplachy.}
{307}{}{Moná to není moc dobrı nápad; zkusme vymyslet nìco jiného.}
{308}{}{To je vıborné; seenu lidi z mìsta a setkáme se tady.}
{309}{}{On je tam Jonny!? Hledali jsme ho všude. Ty zrùdy kradou naše dìti. Nebudeme v bezpeèí, dokud nebudou všichni mrtví. Seenu obyvatele mìsta a vypálíme to jejich hnízdo. Setkáme se na Farmì Duchù co nejdøív.}
{310}{}{Divím se, e sneseš sám sebe! My tu máme krizi a ty myslíš jen na svoje sobecké zájmy. Dobøe, tak si jdi do Gecka; je to smìrem na vıchod. Kdyby nìkdo vìdìl nìco o GECKu, urèitì by to øekl. Teï, kdy dovolíš, musím jít za ostatními a domluvit se, co budeme dìlat.}
{311}{}{To je vıborné. Mimochodem, co to bylo zaè?}
{312}{}{Jen spolek mutantù. Jestli to pøedtím nebyli duchové, tak teï u urèitì jsou.}
{313}{}{Byli to duchové. Teï jsou pryè. Víc nepotøebuješ vìdìt. Teï mi øekni, kde najdu svatı GECK.}
{314}{}{Chceš øíct, e jsi je všechny pozabíjel?! To pøece od tebe nikdo nechtìl. Poslali jsme tì zjistit, co se stalo na farmì, a pøinést nám informace. Radìji odejdi, prosím.}
{315}{}{Zaútoèíme na nì, ale jen v pøípadì nouze. Máme zásoby jen na mìsíc. Do té doby musíte zjistit, co se tam dìje. Nebudu s nimi jednat, dokud nebudu pøesnì vìdìt, co se stalo Karlovi.}
{316}{}{Zaútoèíme na nì, ale jen v pøípadì nouze. Máme zásoby jen na mìsíc. Do té doby musíš zjistit, co se tam dìje. Nechci s nimi jednat, dokud si nebudu jistı, e neudìlali nic Karlovi a taky by mì zajímalo, proè nabodávají lidská tìla pøed svojí farmou. Nebudu vyjednávat s divochy.}
{317}{}{Na mùj vkus se ti pøíliš líbí zabíjení. Radši odejdi.}
{318}{}{[Pøekvapenı] Den! Já-já si myslel, e jsme na nìj byli pøíliš tvrdí. Dokáu si pøedstavit, èím musel projít, kdy mu nikdo nevìøil, co se stalo na Farmì Duchù. Øíkáš, e je z nìj teï opilec v Denu? Budu ti velmi vdìèen, jestli mu vzkáeš, e u mu vìøíme a e se mùe vrátit.}
{319}{}{Taky musím øíct, e ta nabodnutá tìla pøed Farmou Duchù jsou jen atrapy. Panáci pokrytí vnitønostmi z brahmín.}
{320}{}{Promluvíš si teï s vùdcem Svìtloplachù?}
{321}{}{To je vše, co prozatím vím.}
{322}{}{Atrapy! To není moné... vidìl jsem je na vlastní oèi. Krev a vnitønosti. Ale... asi je to moné, nedívali jsme se... chci øíct... vlastnì [Jo se zaèíná èervenat.] Jsme zbabìlci, a kdy jsme uvidìli tìla, utekli jsme. Nikdo ty støeva zblízka nezkoumal.}
{326}{}{Ano, vìøím tomu, e Svìtloplachové a obyvatelé Modocu se dokáou domluvit a uzavøou vıhodnou dohodu. Díky za záchranu obyvatel Modocu.}
{327}{}{Tohle e má bıt moje odmìna? Sliboval jsi, e mi povíš, kde je GECK.}
{328}{}{Musíš zjistit, kdo jsou ti lidé nabodnutí pøed Farmou Duchù. }
{329}{}{Karl pøed èasem zmizel z farmy. Zjisti, co se s ním stalo.}
{330}{}{OK, zkusím nìco zjistit.}
{331}{}{Takové, jako jsi ty, tu nechceme.}

{400}{}{[Poèkáš, a si usekne prst] OK, tak já ti teda pomohu.}
{410}{}{Co je ta velká bílá budova uprostøed mìsta?}

{500}{}{Ach, to je náš mìstskı kostel. Postavili ho obyvatelé Modocu na dùkaz svojí víry. Pozdìji ale nebylo moc dùvodù vìøit v Boha, a tak se o kázání u nikdo nestará.}

# wedding script dialog
{600}{}{Drazí pøítomní: Setkáváme se tady...}
{602}{}{[Jo otáèí nìkolik stránek ve své knize.]}
{603}{}{Tak jo, ehm... ne zaèneme, je zde nìkdo, kdo by znal dùvod, proè by tito dva nemìli vstoupit do svazku manelského?}
{604}{}{Bere si }
{605}{}{ tady }
{606}{}{ za }
{607}{}{Podle zákona vás prohlašuji za manele. Teï mùete políbit nevìstu.}
{608}{}{Podle zákona vás prohlašuji za manele. Teï mùete políbit jeden druhého.}
{609}{}{Podle zákona vás prohlašuji za manele. Teï mùete políbit jeden druhého.}

{625}{}{manela?}
{626}{}{manelku?}
{627}{}{Uhhh... druhého? Ano, právoplatnì oddaného partnera?}
{628}{}{druhého?}

{629}{}{Miria}
{630}{}{Davin}

{800}{}{Zaútoèíme na Svìtloplachy za }
{801}{}{ dní, jestlie mì nepøesvìdèíš.}
{802}{}{Zaútoèíme na Svìtloplachy zítra, jestlie mì nepøesvìdèíš.}
{803}{}{Zaútoèíme na Svìtloplachy ihned! Jsi s námi, nebo proti nám?}
{804}{}{Se mnou mùeš poèítat!}
{805}{}{U toho mám dost, jdu s vámi!}
{806}{}{Zaútoèíme ihned. Svìtloplachové dokázali, e jim nemùeme vìøit.}

{820}{}{Jak ti mohu pomoci?}
{821}{}{U tím nechci nic mít. Z mé strany je dohoda splnìna. Je øada na tobì. Povìz mi, kde je GECK.}

{850}{}{Vrátím se, jakmile zjistím, co se stalo Karlovi.}

{900}{}{Díky, mùj pøíteli, zachránil jsi naše mìsto.}
{925}{}{Není zaè. Nashledanou pøíštì.}

{1000}{}{Díky tobì byl Modoc zachránìn.}
