# tenhle fajl pøelouskal: Mıval (myval@writeme.com). Naposledy editováno: 01/06/1999
{100}{}{Orala. [Má ceduli s nápisem: "Budu pracovat za stravu."]}
{101}{}{Vidíš Karla, špinavého opilce.}
{102}{}{Je tak zaneøádìnı, e mu ve vlasech roste nìjakı plevel...}

{150}{}{Tady máš pivo.}
{151}{}{Tady máš láhev chlastu.}
{152}{}{Tady máš Nuka-Colu.}
{153}{}{Hej.}
{154}{}{Hej!}
{155}{}{HEJ!!}
{156}{}{Duchové mì u nenajdou... [smrk]}
{157}{}{To je dobøe, e jsem zase doma.}
{159}{}{To je Karl; je mimo.}
{160}{}{Chce se poøádnì vyspat.}
{161}{}{Aááá! Duchové z farmy mì chtìjí dostat!}
{162}{}{Nemáte nìjakı drobnı (škyt) pro vyslouilıho farmáøe?}
{163}{}{Jasnì, kámo; kolik potøebuješ?}
{164}{}{Nechceš tøeba koupit nìjaké teplé jídlo?}
{165}{}{Je mi líto, nemám peníze.}
{166}{}{Co tu vlastnì dìláš?}
{167}{}{DROBNİ?}
{168}{}{Heeee.}
{169}{}{Oóó, štìdrı èlovìk. (škyt) Mùe se ti Karl nìjak odmìnit? (škyt) [Sundává si èepici a nabízí ti ruku.]}
{170}{}{Tady. Tady máš $100.}
{173}{}{Sorry, nemám pro tebe nic. Sbohem.}
{174}{}{Nevíš, kde bych našel vìc zvanou GECK?}
{175}{}{Pøed chvílí jsi se zmínil o zahradì. Povìz mi o tom více.}
{178}{}{Já jdu.}
{179}{}{Hej, lakoto! (škyt) No tak, ja vím, e máš prachy (škyt). Jen pár drobnejch... (škyt) Nìco, cokoliv! Slituj se.}
{180}{}{Na. Tady máš $25.}
{184}{}{Na. Tady máš $1.}
{185}{}{Na.}
{186}{}{Nemám peníze.}
{187}{}{Co chceš?}
{188}{}{[Povìz Karlovi, co øíkal Jo.]}
{189}{}{Duchové, Karle... jsou tu všude. Podívej, tady je taky jeden!}
{190}{}{Neeeee, slint...}
{191}{}{Chceš si (škyt) dìlat legraci z chudáka Karla? (škyt) Dobøe, tak na co èekáš? (škyt) U s tím pøestaò!}
{198}{}{[Zastøenım hlasem.] Takovı zámonı èlovìk jako ty... (škyt) $1000 by se mi hodilo.}
{199}{}{Jistì, samozøejmì.}
{200}{}{Jo? A na jak dlouho, na rok? V ádném pøípadì; tady máš $25.}
{201}{}{Máš mì za blázna? Odcházím.}
{202}{}{[Karlovi pøekvapením spadne èelist] Díky! Jsi (škyt) velmi štìdrı èlovìk... (škyt) Pokud budete nìco (škyt) potøebovat, pøijdi za mnou. Mimochodem, (škyt) já sem Karl.}
{203}{}{Jistì, Karle; zmínil ses' o nìèem, co hledám - vìc, která se jmenuje GECK. Netušíš, kde se dá nìco takového najít?}
{204}{}{Budu si to pamatovat. Dávej na sebe pozor, Karle.}
{205}{}{Co si zaè? (škyt) Zkoušet takovı triky na chudáka bezdomovce, farm-(škyt)-áøe. Dej mi pokoj!}
{206}{}{Jóóó... (škyt) Òákej geckon (škyt) - u sem to slyšel. Ale nikdy sem ádnıho nevidìl.}
{207}{}{Ne, hledám GECK, ne geckona.}
{208}{}{To je jedno. Dík za informace.}
{209}{}{Joo! Myslíš geckona... (škyt) Jóó, to je veelká ješ-(škyt)-tìrka. [Karl roztahuje ruce a ukazuje, jak je velká. To moná ani nevíš, ale geckon mùe bıt a 3 stopy dlouhı.]}
{210}{}{O tom nemluvím. Nehledám geckona, ale vìc, která se jmenuje GECK.}
{212}{}{Proè to neøekneš hned? (škyt) Vim, kde je... (škyt) Rajská zahr... [Karl nedokonèí vìtu a usne.]}
{213}{}{[Moná, e a se Karl probudí, poví ti nìco dalšího.]}
{214}{}{Bùh ti ehnej! (škyt) Za záchranu mého ivota.}
{215}{}{Hledám GECK; mùeš mi pomoci?}
{216}{}{Nezapomeò na to, Karle. Já si tì najdu.}
{217}{}{Um... (škyt) Teï nemám hlad (škyt) Heleï... dej mi radši prachy, co øíkáš? (škyt)}
{219}{}{Ty lháøi. Vsadím se, e potøebuješ peníze na drogy, co?}
{220}{}{Lha... Lah... háø... Co..cod... coe? (škyt) Odvolej to (škyt) A to znamená cokoliv, urèitì to nebude nic dobrıho.}
{221}{}{[Ne staèíš odpovìdìt, Karl zase spí.]}
{222}{}{Toooo je oukej... (škyt) Neèekal jsem, e budeš mít nìjakı tekutı obèer-(škyt)-stvení. V noci tu bude pìkná (škyt) zima.}
{224}{}{Seš muj (škyt) nejlepší kamarád na tomhle zatr-(škyt)-acenım svìtì. [Karl si lokl z láhve, a zase odpadl]}
{225}{}{Moná budeš moci mluvit s Karlem pozdìji.}
{226}{}{Seš muj (škyt) nejlepší kamarád na tomhle zatr-(škyt)-acenım svìtì. [Karl otevøel láhev a napil se - a zaèal prskat kolem sebe.] Fuj! Co to je?! Chceš mnì otrávit?! Vypadni!}
{227}{}{Dík-(škyt)-y, taková šlechetnost (škyt). Proè ti nepomoct s tak tìkım mìšcem? [Karl šmátrá v tvém mìšci a bere si polovinu penìz.] Si moc hodnej (škyt), jestli budeš nìco potøebovat, klidnì se na mì obra.}
{228}{}{GECK?}
{229}{}{Já pùjdu.}
{230}{}{Joooky... škyt...}
{231}{}{Moná pozdìji.}
{232}{}{Gee (škyt)... díky. Moná bych si mohl koupit nábojnici a (škyt) zastøelit se. (škyt) Spíš bych si mìl (škyt) nìco pøidat a koupit pistoli.}
{233}{}{Chceš øíct... Mùu jít domù? Je konec s duchama? [Karl padne na zem a pláèe. Boe, dospìlı mu a takhle breèí.] Díky, koneènì mùu jít zas domù!}
{234}{}{Kde?! Neeeeeeeeeee! Našli mnì!}
{235}{}{Proè ne, mám tu nejvìtší zahradu, jakou (škyt) si èlovìk mùe pøát. Tam (škyt) odkud pocházím, jsme tomu øíkali farma...}
{236}{}{Nevzpomínáš si? Mluvili jsme o GECKu a ty ses zmínil o zahradì.}
{237}{}{Zapomeò na to, nikam to nevede.}
{238}{}{Hej! (škyt) Zdáš se bıt OK! Zkusíme to spolu ještì jednou (škyt) a líp se poznáme. Mùu zaplatit... mám $1000. [Karl na tebe lišácky pomrkává.]}
{239}{}{Chápeš, e mluvíš s chlapem?}
{240}{}{Jistì, ale bude tì to stát $1000.}
{241}{}{Díky za nabídku, ale radìji si promluvme o GECKu.}
{242}{}{Ani za nic!}
{243}{}{Seš takovı neviòátko... (škyt) Kdy chceš, budu zticha. (škyt)}
{244}{}{[Nemùeš se ubránit smíchu.] Budu muset jít.}
{245}{}{OK, $1000.}
{246}{}{[Ty a Karl se vypaøíte na jednu rychlovku. K tvımu pøekvapení to nebylo špatnı.]}
{247}{}{[Rychle vystøízlivìl a zaèal povídat.] Byl jsem poèestnı obèan, ne jsem pøišel sem. Byl jsem mírumilovnı farmáø, kterı pracoval na polích stejnì jako všichni ostatní - dokud se nezaèali v noci objevovat. Všichni svìtélkující, s bledımi tváøemi... Vydìsili mì k smrti. Objevovali se jednu noc za
 druhou a kradli mi úrodu i dobytek; nemohl jsem je nijak zastavit. Vím, co chcete øíct - proè jsem nepoádal o pomoc? Øíkám vám e jo! Ale nikdo mi nevìøil, mysleli si, e jsem blázen. Nakonec toho bylo na mì moc. U JSEM TO NEMOHL VYDRET! Vzdal jsem to a pøišel sem - a od té doby iju tady. [Karl zaène
 plakat. Rozhodneš se odejít a nechat ho i s jeho utrpením.]}
{248}{}{Aááno. Musel jsem ztratit peníze nìkde po cestì. Tady máš $}
{249}{}{.}

{250}{}{Chrr}
{251}{}{Chrrrrr}
{252}{}{Chrrrrrrr}
{253}{}{Chrrrrrrrrr}
{254}{}{Chrrrrrrrrrrr}
{255}{}{*frk* *chrocht* *frk*}

{260}{}{O áno. Musel jsem ztratit peníze nìkde po cestì. Tady je $}
{261}{}{. To je vše co mám.}
{262}{}{O áno. Musel jsem ztratit peníze nìkde po cestì. Sorry, ale stejnì to bylo zábavné.}

{300}{}{Jdu domù, díky!}

{400}{}{Poslal jsi Karla zpátky do Modocu.}
