# tenhle fajl pøelouskal: Mýval (myval@writeme.com). Naposledy editováno: 01/06/1999
{100}{}{Pes. Vypadá jako kólie.}
{101}{}{Laddie.}
{102}{}{Tenhle pes je opravdu inteligentní a ostražitý.}
{103}{}{Ten pes je urèitì chytøejší než ty.}

{150}{}{HAF!}
{151}{}{HAF! HAF!}
{152}{}{HAF! HAF! HAF!}
{153}{}{[Ten pes je opravdu rozrušený.]}
{154}{}{Hezký pejsek.}
{155}{}{Víš, kde je Jonny?}
{156}{}{Zùstaò tady, Laddie}
{157}{}{Najdi Jonnyho.}
{158}{}{Myslíš, že se Jonny propadl do té studnì, Laddie?}
{159}{}{Copak pejsku, chceš mi nìco øíct?}
{160}{}{Grrrr! [Laddie tì zlomyslnì kousne.]}
{161}{}{[Hmm... z nìjakého dùvodu tì nemá rád.]}
{162}{}{HAF! HAF! HAF! [Laddie na tebe skáèe a líže tvoji tváø.]}
{163}{}{[Pìkný pejsek.]}
{164}{}{HAF? [Skoro jako kdyby se ti ten pes smál.]}
{165}{}{[Nikdo nemá rád chytráky.]}
{167}{}{Je Jonny nìkde poblíž Modocu?}
{168}{}{Odešel Jonny z Modocu?}
{169}{}{Unesli Jonnyho vetøelci?}
{170}{}{Teï si nemùžeme hrát, Laddie; nejprve musíme najít Jonnyho. Pojï.}
{171}{}{Blízko jatek?}
{172}{}{Blízko koželužny?}
{173}{}{Blízko tržištì?}
{174}{}{Blízko studny?}
{175}{}{Možná ještì nìkde jinde?}
{177}{}{Blízko Rózina penziónu?}
{180}{}{Šel na sever?}
{181}{}{Šel na jih?}
{182}{}{Šel na východ?}
{183}{}{Šel na západ?}
{186}{}{HAF?}
{187}{}{Dobrá, dobrá...  možná nìkde jinde?}

{190}{}{Hrál si na kovboje a indiány a pøitom náhodou spadl do studnì a ty po mnì chceš, abych vzal provaz a spustit se dolù pro nìj. OK, tak jdeme, Laddie. [Úžasné!]}
{191}{}{Hrál si na kovboje a indiány a pøitom náhodou spadl do studnì a ty po mnì chceš, abych vzala provaz a spustila se dolù pro nìj. OK, tak jdeme, Laddie. [Úžasné!]]}
{195}{}{OK, vezmu si lano a slezu dolù pro Jonnyho.}
{196}{}{OK, mùžu použít svoje lano a vlézt do studnì pro Jonnyho.}
