# tenhle fajl pøelouskal: Mıval (myval@writeme.com). Naposledy editováno: 01/06/1999
{100}{}{Pìkná, velmi pohledná a svùdná ena.}
{101}{}{Miria.}
{102}{}{Trochu váháš, ale míry 96-60-92 jsou lákavé.}

{150}{}{Kurva!}
{151}{}{Jak se opovauješ se tady vùbec ukazovat!}

{152}{}{To je hnusné!}
{153}{}{Doufám, e vy dva spolu budete šastní.}

# Node 0
{154}{}{Ahoj, cizinèe. Já jsem Miria.}
{155}{}{Jsem ráda, e jsi zpátky. Co budeme probírat teï?}
{156}{}{Co tady dìláš?}
{157}{}{Co mi mùeš povìdìt o jatkách?}
{158}{}{Znáš nìjaké nové drby?}
{159}{}{Hezká! Hezká!}

# Node 2
{160}{}{No tak se teda ptej.}

# Node 10
{164}{}{Øíká se, e Farrel ukradl hodinky.}
{165}{}{Proè by Farrel kradl hodinky?}
{166}{}{Není Farrel nejlepší Corneliùv pøítel?}
{167}{}{Povìzte mi ještì nìjaké drby.}

# Node 11
{168}{}{Protoe chudí lidé mají sklony ke krádeím. A Farrel urèitì patøí k tìm chudákùm. No a taky by to vysvìtlovalo, za co si koupil nové nástroje, potom co zmizely Corneliovy hodinky.}
{170}{}{Mùu se ještì na nìco zeptat?}

# Node 12
{171}{}{Ano, ti dva byli døíve dobøí pøátelé. Proto si myslím, e ty hodinky ukradl Farrel. Kdo jinı ne Farrel k tomu mìl pøíleitost?}

# Node 13
{174}{}{Co ti budu vykládat. Prostì, moje rodina øídí místní jatka. Lidé z celého okolí sem pøivádí své brahmíny na poráku. Kdy jsou zvíøata poraena, je maso zpracováno a prodáno obchodníkùm, kteøí je dále prodávají kupcùm ve mìstech. Pro mì je to nuda.}

# Node 14
{176}{}{To je ale hloupá otázka! Tohle mìsto je tak hroznì nudnı. Nedá se tu dìlat nic jinıho ne tlachat se sousedy a civìt na... [a mluví a mluví a mluví...]}
{177}{}{Chceš vìdìt ještì nìco?}
{178}{}{Co víš o hodinkách, které ukradli Corneliovi?}
{179}{}{Zmínila jsi se o Róze?}
{180}{}{Co se povídá o zmutovanıch brahmínách?}
{181}{}{Povìz mi nìco o Davinovi.}
{182}{}{Mluvme o nìèem jiném.}

# Node 15
{183}{}{Jóó, Róza, majitelka 'Rózina penzionu'. Podívej, nic jsem ti neøekla, ale napadlo tì nìkdy, proè je její 'kurník' tak dobøe chránìnı? Ona øíká, e je to na ochranu jejich slepic pøed dravci, ale kdy se podíváš blí, vypadá to, e spíš chce, aby se nic nedostalo ven! Navíc, kdo kdy slyšel o slepicích,
 kterı snáší 12 librovı vejce?}
{184}{}{Povìz mi ještì nìjaké místní drby.}

# Node 16
{186}{}{Je to opravdu divnı, ale nìkteøí farmáøi tvrdí, e se brahmínám obèas narodí tele s jednou hlavou. A pak e v tom nejsou kouzla!}

# Node 17
{189}{}{Ten je z rodiny; nerozšiøuju klepy o vlastní rodinì.}

# Node 18
{192}{}{Kdo, já? Já dìlám jen pøíleitostnou práci, chvíli tady, chvíli támhle. Nestojí to za øeè. [Svùdnì na tebe pomrkává.]}
{193}{}{Chci se toho o tobì dozvìdìt víc.}
{194}{}{Máš pravdu, dost øeèí. Pojï na to! Vím, e to chceš!}

# Node 19
{196}{}{Jsem dojatá. Nikdo se mì nikdy nesnail pochopit. Chtìjí jenom sex, sex, sex! U mì to unavuje, poøád jen souloit. Jsem ráda, e nejsi jako ostatní.}
{197}{}{Ty couro! Chvíli se mi zdálo, e jsi jiná.}
{198}{}{Víš, jsem úplnì normální chlap jako ostatní. Moji pøátelé øíkají: "}
{199}{}{ všichni tì berou, protoe jsi jako všichni ostatní." A mají pravdu, jsem úplnì normální.}
{200}{}{Jsi velmi zajímavá, to se jen tak nevidí.}

# Node 20
{202}{}{Co to mìlo bıt? Co tím chceš øíct?}
{203}{}{Myslím, e dobøe víš, o èem mluvím, bejby. Vím, e to chceš taky. [S úsmìvem se zaèínáš svlékat]}
{204}{}{Zapomeò na to; omlouvám se. Nebylo tím myšleno nic špatného.}

# Node 21
{205}{}{Jak se mnì opovauješ øíkat couro! Náhodou si dobøe vybírám, ne se s nìkım vyspím. Tenhle mìsíc jsem spala jen s 20 chlapama! A tímhle náš rozhovor skonèil!}

# Node 22
{206}{}{Jsem zklamaná. Jsi jako všichni ostatní.}

# Node 23
{208}{}{Tak to né. Tahle konverzace mì u nudí. Sbohem!.}

# Node 24
{209}{}{[Èervená se] Brzdi, pøivádíš mì do rozpakù, cukroušku. Proè nejdeš blí a neposadíš se ke mnì?}
{210}{}{Myslím, e zacházíme pøíliš daleko. Nemùeme si jen povídat?}
{211}{}{Och, to zní hezky. Proè si neudìlat TROCHU VÍC pohodlí, e?}
{212}{}{OK! Však ty víš, co chci, bejby!}
{213}{}{Jsi dìvka!}

# Node 25
{214}{}{U to nevydrím! Jsi dokonalost sama. [Strhá ze sebe svoje šaty, pak tvoje, a potom... ]}
{215}{}{[Tvùj ivot se zmìnil.]}

# Node 26
{216}{}{Doufám, e to neznamená to, co si myslím.}
{217}{}{Jo, znamenat!}
{218}{}{Ne... egh?}

# Node 27
{219}{}{Jo! Tak zrovna to jsem si myslela. Je legraèní, jak se tady pravìká a civilizovaná øeè støetává. [Sotva šlo postøehnout, jak se k tobì blíí. Doufáš však, e èervenı obtisk ruky na tvé tváøi brzy zmizí]}

# rape script dialog
{250}{}{Pomooc, tatínku! A mì pustí!}
{251}{}{Zmiz!}
{260}{}{Pomóóc, tatínku! A mì nechá bıt!}

# wedding script dialog
{400}{}{Tatínku!}
{401}{}{Ehm... jejda!}
{402}{}{A..ANO!}

{410}{}{Ehm...}
{411}{}{Ehh... pokraèujte prosím...}
{412}{}{Jasnì, krucinál...}
{413}{}{Hmm... dám na ni pozor.}

{450}{}{Uhhh, myslím, e byste si mìli promluvit taky s tatínkem.}

{500}{}{Vıbornì. Myslím, e to znamená, e mám z téhle díry vypadnout.}

# in party dialog
{1000}{}{A co budeme dìlat teï, brouku?}
{1001}{}{A co budeme dìlat teï, zlatíèko?}
{1002}{}{A co budeme dìlat teï, lásko?}
{1003}{}{A co budeme dìlat teï, miláèku?}
{1004}{}{A co budeme dìlat teï, cukrouši?}
{1005}{}{Ne, ne, ne... Nemyslím tenhle druh vzdálenosti! Chci jen øíct, e bychom mìli bıt trochu dál od sebe.}
{1006}{}{V klidu brouku, jen mi dej trochu víc prostoru, kdy se procházíme.}
{1007}{}{Budu se víc snait, zlato, ale prostì není tak jednoduchı udìlat si na tebe èas.}
{1008}{}{Co je moje, je i tvoje.}
{1009}{}{Oukej, èumáèku, ale opravdu si myslíš, e by nás ta zbroj v nìèem zastavila?}
{1010}{}{Ostré zbranì, jako tøeba noe, mì vzrušují, aèkoliv v nouzi dokáu pouít i SMG. Ale neèekej, e se do nìèeho trefím.}
{1020}{}{Chci probrat vzdálenost mezi námi.}
{1100}{}{U mi nic není, všechna zranìní vyléèena - mùeme jít.}
{1200}{}{Nezùstalo na mnì ani škrábnutí.}
{1300}{}{U mi skoro nic není -- ale potøebuji další léèení, a to bude moné.}
{1400}{}{Léèila jsem se, jak to jen šlo, ale jsem poøád dost poranìná.}
{1500}{}{Ne, brouku; chci jít s tebou.}
{1600}{}{Jasná vìc, dám to pryè.}
{1700}{}{}
{1800}{}{Ne, ne, rùièko. Potøebuju tì mít nablízku.}
{1900}{}{Ale to bych nemohla bıt s tebou, cukroušku.}
