# tenhle fajl pøelouskal: Mýval (myval@writeme.com). Naposledy editováno: 01/06/1999
{100}{}{Vidíš obyvatele mìsta.}

# General
{200}{}{Urèitì bude brzy pršet.}
{201}{}{Naše úroda usychá kvùli nedostatku vody.}
{202}{}{I naše studny vysychají.}
{203}{}{Na obloze není ani mráèek.}
{204}{}{Asi se odsud odstìhuju.}
{205}{}{Modoc bývalo prosperující mìsto.}
{206}{}{Tady v Modocu se nic nedìje. A mì to vyhovuje.}

# Ghost Farm Seed Active
{220}{}{Slyšel jsem, že na Farmì Duchù vidìli lidé v noci svìtélkující postavy.}
{221}{}{Slyšel jste? Našli nìjakýho idiota, co pùjde prohlídnout Farmu Duchù.}
{222}{}{Byl jsem na Farmì Duchù. Hrùza!}
{223}{}{Na Farmu Duchù se dá jít jen za dne.}
{224}{}{Karl døív žil na Farmì Duchù. Teï tam asi straší.}
{225}{}{Lidé by si nemìli zahrávat s vìcmi nadpøirozenými.}
{226}{}{Proè by duchové pìstovali obilí?}

# If player delivered message from slags to Jo - Delivered=yes
{240}{}{Našli lidi, kteøí žijí na Farmì Duchù. Øíkají si Svìtloplaši.}
{241}{}{Stìtloplaši... co je to za jméno?}
{242}{}{Svìtloplachùm nevìøím.}
{243}{}{Možná že bych Svìtloplachùm vìøil, kdybych vìdìl, co se stalo Karlovi.}

# If Player Agrees to help Modoc to Attack the Ghost Farm
{260}{}{Setkáme se na Farmì Duchù.}
{261}{}{Pobijeme pár nièemných Svìtloplachù.}
{262}{}{Doufám, že dìláme správnou vìc.}
{263}{}{Mìli bychom je napadnout ve dne, když spí.}

# If the player and the town wipeout the Slags
{280}{}{Svìtloplaši jsou jako my...}
{281}{}{Pobili jsme dokonce i ženy a dìti Svìtloplachù.}
{282}{}{Cítím se hroznì.}
{283}{}{Nemohu smýt krev z mých rukou!}
{284}{}{Doufám, že nikdo nikdy nezjistí, co jsme udìlali.}
{285}{}{To, co jsme udìlali Svìtloplachùm, nebylo správné.}

# If the player kills the Slags by himself
{300}{}{Už to víte? Mocný knìz vymítil duchy z Farmy.}
{301}{}{Sklizeò z Farmy Duchù nás uživí celý rok.}
{302}{}{Na Farmì Duchù není ani kapka vody.}
{303}{}{Možná že pùda na Farmì Duchù je zakletá. Jak by klasy mohly rùst bez vody?}
{304}{}{Možná že k zalévání používali duchové KREV.}
{305}{}{Myslím, že duchové kradli naši vodu.}
{306}{}{Vsadím se, že teï, když jsou duchové pryè, bude zase všechno v poøádku.}

# If the player successfully completes the Ghost Farm seed. Best ending.
{320}{}{Budeme se Svìtloplachy obchodovat.}
{321}{}{Svìtloplaši nabízejí dodávky vody do Modocu v dobì sucha.}
{322}{}{Díky za naši záchranu. Hrdino!}
{323}{}{Díky vám byl Modoc zachránìn.}
{324}{}{Vždy vás v Modocu rádi uvítáme.}
