# tenhle fajl pøelouskal: Mýval (myval@writeme.com). Naposledy editováno: 01/06/1999
{100}{}{Vidíš stráž Svìtloplachù.}

# surrender
{150}{}{Vzdej se, nebo zemøeš!}
{151}{}{Vzdávám se.}
{152}{}{Chcípni!}
{153}{}{Ugh!}
{154}{}{Jestli potøebuješ vidìt Vegeira, mùžeme tì k nìmu doprovodit.}
{155}{}{Teï ne. Sejdu se s Vegeirem pozdìji.}
{156}{}{Ano, potøebuji ihned vidìt Vegeira.}

{160}{}{Ty jsi ale hlupák! Když chceš vidìt Vegeira, najdi si ho.}

# caves
# - general
{200}{}{Nevìøím Nadzemníkùm.}
{201}{}{Vegeir si pøeje, aby se ti nic nestalo...}
{202}{}{Odpovídáme za ochranu našich lidí.}
{203}{}{Sleduju tì.}

# - mission complete
{220}{}{Myslím, že jsi OK... na Nadzemníka.}
{221}{}{Možná bychom mohli spolupracovat s Nadzemníky.}
{222}{}{Jsem rád, že jsem se ve vás mýlil.}
