# tenhle fajl pøelouskal: Mıval (myval@writeme.com). Naposledy editováno: 01/06/1999
{100}{}{Veselá baculka.}
{101}{}{Róza.}
{102}{}{Její šedé vlasy jsou staené do drdolu a pøi chùzi se trochu kolébá. Nemùeš si pomoci, ale cítíš se u ní uvolnìnì.}
{150}{}{Je mi líto, ale máme zavøeno. Máme úmrtí v rodinì. [smrk]}
{151}{}{Hej! Do krabice ztrát a nálezù smím jenom já.}
{152}{}{Zaèínám si myslet, e jsi zlodìj!}
{153}{}{Zlodìj! Zlodìéj! Zlodìééj!}
{154}{}{Vítejte v Rózinì penziónu. Boínku, vy jste ale urostlı mladík. Co pro vás mùe Róza dneska udìlat?}
{155}{}{Vítejte v Rózinì penziónu. Paneèku, jaká jste pìkná sleèinka. Co pro vás mùe Róza dneska udìlat?}
{156}{}{Mám docela hlad! Copak tu máte k jídlu?}
{157}{}{Chci si pronajmout pokoj na jednu noc.}
{158}{}{Kdy tady pracujete, musela jste slyšet zajímavé vìci. Nevadilo by vám pár otázek?}
{159}{}{[Hlasitì mlaskneš]}
{160}{}{Ráda vás zase vidím! Co pro vás mohu udìlat?}
{165}{}{Oh! To jste vy. Kadı povídá o tom, jak jste kvùli nám riskoval svùj ivot a odhalil tajemství Farmy Duchù. Samozøejmì vás tu vdy rádi uvítáme a všechno jídlo a pití jde na náš úèet. A jako speciální odmìnu si mùete
 prohledat naší krabici ztrát a nálezù a vzít si, co budete chtít.}
{166}{}{To je náš hrdina z Modocu! Vítejte zpátky.}
{167}{}{Mám hroznou chu na jednu z vašich vıteènıch omelet.}
{168}{}{To ráda slyším. Mladı dospívající èlovìk musí poøádnì jíst, a to vy nedìláte. Koukejte si pìknì sednout a podívejte se na jídelní lístek.}
{169}{}{Kdy jste naposledy jedla nìco poøádného, mladá dámo? Jste hubená jako lunt. Teï se pìknì posaïte, podívejte se na jídelní lístek a øeknìte Róze, co si dáte k jídlu.}
{170}{}{Smaená brahmína. [$5]}
{171}{}{Omeleta z Pustin. [$25]}
{172}{}{Voda. [$1000]}
{173}{}{Brahmína ála pes. [$5]}
{174}{}{Pes-burger. [$7]}
{175}{}{Dušené ovèí maso. [$3]}
{176}{}{Ne, dìkuji; teï nemám hlad.}
{177}{}{Bohuel to vypadá, e máte málo penìz. Pøijïte, a na tom budete líp.}
{178}{}{Ale já hladovím! Mùu si objednat nìco levnìjšího?}
{179}{}{Poèkejte! Mùu mít pár otázek?}
{180}{}{Vy si to chcete dát znovu? Páni, musíte krokety z brahmín opravdu milovat. Je mi ale líto. Dokud dríte rekord, nemùete pokraèovat v soutìi. Jedinì a nìkdo jinı pøekoná váš rekord.}
{181}{}{Jsou to vlastnì kroket z brahmín. Máme tady soutì v pojídání kroket; rekord je zatím 36. Kdy rekord pøekonáte, nemusíte platit to, co sníte. A jak se tak na vás dívám, vy asi nebudete mít problém s pøekonáním rekordu. Chcete to zkusit?}
{182}{}{Dobøe, zaplatím, za vaše vynikající smaené krokety.}
{183}{}{Mám takovı hlad, ze klidnì váš rekord zdvojnásobím. Noste na stùl...}
{184}{}{Ne, dìkuji; dám si to jen jednou, prosím.}
{185}{}{Oh, to je skvìlé. Kadı chod obsahuje 10 kouskù. Musím vás ale nejprve poádat o peníze. Jakmile zlomíte rekord, dostanete je zpìt. Dìlá to $20, prosím.}
{186}{}{Tolik nemám. Zkusím pøekonat rekord pozdìji. Teï si dám jen jednu porci. Díky.}
{187}{}{Doufám, e to dostanu zpátky, a pøekonám rekord.}
{188}{}{[Róza si bere peníze a vrací se s obrovskou mísou kroket. Mno... mohly bıt aspoò trochu menší. Jsou velké skoro jako golfovı míèek, obalené v tìstíèku a smaené na oleji do zlatohnìda. Bereš si sousto na ochutnání. Jsou vynikající! 
 Nadšenì se pouštíš do jídla.]}
{189}{}{[U 34. krokety cítíš, e u máš dost. Okolo se shromádil velkı dav, aby všichni vidìli, jak pøekonáš rekord. Chceš získat ztracenou rovnováhu a tak se pokoušíš konverzovat s Rózou.]}
{190}{}{[Strkáš další kroketu do úst.] 'Mmff... mfvakı... chro...' Nemluv s plnou pusou, drahoušku. [Polykáš.]}
{191}{}{Jakı máte recept? Tedy jestli to není tajemství. Mé pøátele by to velmi zajímalo.}
{192}{}{Ó ne, to není tajemství. Musíte je obalit v tìstíèku, osolit a smait na tuku. [Nacpeš si další kroketu do úst.]}
{193}{}{A jak pøipravujete maso z brahmín? Má jedineènou barvu. [Polykáš další kroketu. VYNIKAJÍCÍ!]}
{194}{}{To je 37. kroketa! Rekord je tímto pøekonán! [Dav okolo tleská!]}
{195}{}{[Chytáš druhı dech a polykáš další kroketu.]}
{196}{}{[Dav okolo køièí: "38!"] Take; ta chu je tak vynikající, protoe maso odøezáváme z brahmín ZAIVA. Popadnu brahmíního samce za varlata a ušmiknu všechny ètyøi jedním øezem. Musíte bıt ale opatrnı; vùbec se jim to nelíbí.}
{197}{}{[38. lahùdku vyplivuješ rychlostí svìtla.]}
{198}{}{Ten poslední nemùeme poèítat, ale i tak byl s neuvìøitelnımi 37 kousky rekord zlomen! Tady jsou vaše peníze. GRATULUJI!}
{199}{}{[Je ti na zvracení.]}
{200}{}{Ah, to je moje specialita. Doufám, e máte hlad; zaruèuju vám, e takovouhle omeletu jste ještì nikde nejedl. [Vrací se s nejvìtší zatracenou omeletou, jakou kdy vidìl svìt.]}
{201}{}{[Po takovém poøádném jídle se ti zaèínají vracet síly.]}
{202}{}{[Rychle mizí za pultem a za chvíli se vrací s tvojí objednávkou.]}
{203}{}{Mohu mít pár dotazù?}
{204}{}{Je mi líto, drahoušku, musím obsluhovat ostatní zákazníky. Kdy si ale objednáte nìjaké jídlo, moná si udìlám chvíli èas na otázky.}
{205}{}{V tom pøípadì mám poøádnı hlad. Co máte k jídlu?}
{206}{}{Jasnì, ale hoï sebou, brouku. Nemùu nechat ostatní zákazníky èekat.}
{207}{}{Mùete mi øíct nìco o zmizelıch Corneliovıch hodinkách?}
{208}{}{Slyšela jste nìkdy vìci zvané GECK?}
{209}{}{Co víte o Farmì Duchù?}
{210}{}{To je ale velká omeletu, to snad není moné. Jaké zvíøe snáší tak velké vejce?}
{211}{}{Z èeho je ten pes-burger?}
{212}{}{Oh, zlato! Mluvil jste s mım manelem Corneliem? Celá ta vìc s jeho hodinkami je hrozná. Celé mìsto si myslí, e mu ty hodinky sebral Corneliùv nejlepší pøítel - Farrel. No, moná e u víte, e Farrel je jaksi... jak bych to øekla... no, není úplnì v poøádku. Jsem si témìø jistá, e je ten chudák nìkde zapomnìl a teï neví kde...}
{213}{}{Tak teï snad víte všechno a já pùjdu obsluhovat další zákazníky.}
{214}{}{Ještì pár otázek, prosím.}
{215}{}{Chvileèku. Mám poøád hlad.}
{216}{}{Øíkáte GECK? Ne, tak to neznám. Znám jeden dobrı recept na omáèku z geckonù. Ale nikdy jsem neslyšela o GECKu.}
{217}{}{[Mimodìk se otøese.] Tam nechoïte! Od cestovatelù jsem slyšela, e tam jsou hnijící tìla nabodnutá na sloupy a v noci se tam pohybují svìtélkující stíny. Nevím, kolik z toho je pravda, ale vím, e tam Karl odešel a u ho nikdo nevidìl.}
{218}{}{Ach, mívali jsme pouštní omelety. Bıvaly vynikající. Nìkteøí lidé tvrdili, e mìly uzdravující úèinky. [Vypadá trochu nervóznì.] Oh! Pøišli noví zákazníci. Za chvíli budu zpátky. [Hmm... na otázku u neodpovìdìla.]}
{220}{}{Naše burgery jsou z nejlepších, vybíranıch, prvotøídních psù. Jejich maso potom krájíme na pùl-librové placky. A tu skvìlou uzenou chu, tu získáváme pomalım grilováním nad hnojem z brahmín.}
{221}{}{Ty chudáèku. Vdy hlady umíráš. Posaï se a Róza ti pøinese nìco k jídlu. [Za chvíli se vrací s velkou omeletou.] Teï se nehneš z místa, dokud to nesníš do posledního drobeèku.}
{222}{}{Bohuel, máme obsazeno. Všechny pokoje jsou pronajaty.}
{225}{}{Opravdu!? Musíte mít fakt velkou ízeò. Trochu jsem zvedla cenu, aby to odradilo zákazníky. Pitná voda je to nejluxusnìjší zboí, co tu máme, protoe skoro neprší a studny vysychají. Skuteènì ji chcete?}
{226}{}{Ano! Zoufale potøebuji vodu.}
{227}{}{Teï mám poøádnı hlad.}
{228}{}{Je mi líto, omelety u nepodáváme. Nìjakı šílenec se vloupal do kurníku a zabil naše... ehm, slepice.}
{229}{}{Mám opravdu velkı hlad, tak ukate, co máte k jídlu.}
{230}{}{Jéé škoda, e si nemohu dát vaše vìhlasné omelety. Asi tedy zùstanu hlady.}
{231}{}{Aááách!}

{300}{}{[Rychle se vrací se sklenicí nahnìdlé tekutiny. Pøipadá ti, e ve sklenici je víc smetí ne tekutiny. Ale máš takovou ízeò, e to stejnì vypiješ.] Pøinesu ti k tomu koláèky, zlato.}
