# tenhle fajl pøelouskal: Mýval (myval@writeme.com). Naposledy editováno: 31/05/1999
# Description
{100}{}{Vidíš ošlehaného èeledína, který peèuje o brahmíny.}
{101}{}{Vidíš stájového èeledína.}
# Examine:
{150}{}{Má dost práce.}

# General
{200}{}{Je mi líto, stáje jsou plné. Zkuste to nìkde jinde.}
{201}{}{Teï mám opravdu hodnì práce.}

# If shitter is exploded
{250}{}{Zápach? Je tu nìco cítit?}
{251}{}{Nesmrdí to tak strašnì.}
{252}{}{Myslím, že letos nemá význam hnojit pole. Díky.}

# General Stable Comments
{300}{}{Tenhle potøebuje èerstvou slámu.}
{301}{}{Je zapotøebí další vody.}
{302}{}{Houu! Je naèase chopit se lopaty.}
{303}{}{Takhle vypadá všechno OK.}
{304}{}{Podívej se poøádnì na tohohle. Nevypadá zdravì.}

# trying to sleep
{350}{}{Zzz... Spím ... Zzz...}
{351}{}{*Zíív* Musím brzy vstávat.}
{352}{}{Hej, ještì nejsem dospìlý. Potøebuju se vyspat.}
{353}{}{Jdìte si povídat s nìkým jiným.}
{354}{}{Hele, rád bych spal. Kdyby mì nìkdo poøád nevyrušoval.}
