# tenhle fajl pøelouskal: Mıval (myval@writeme.com). Naposledy editováno: 01/06/1999
# Flee
{100}{}{Bì!}
{101}{}{Pomoc!}
{102}{}{Napadli nás Nadzemníci.}
{103}{}{Nechte nás na pokoji.}
{104}{}{Nemùeme mezi sebou jednoduše spolupracovat?}

# Attack
{150}{}{Vrate se tam, odkud jste pøišli.}
{151}{}{Nejste zde vítáni.}
{152}{}{Vy Nadzemníci jste všichni stejní.}
{153}{}{Neuniknete!}

# General Dialogue (above ground)
{200}{}{Øach!}
{201}{}{Bum!}
{202}{}{Auuuuuuu.}
{203}{}{*Tøesk*}
{204}{}{*Bøink*}

# General Dialogue (below ground)
{250}{}{ili jsme døív nad zemí.}
{251}{}{Jaké to je, nad zemí?}
{252}{}{Je to tam VELKÉ?}
{253}{}{Jak vypadá Slunce?}
{254}{}{Hej, Nadzemníku.}

# General Dialogue when Seed is completely done
{300}{}{Vìdìli jsme, e ti mùeme vìøit.}
{301}{}{Díky za vaši pomoc.}
{302}{}{Rád tì zase vidím.}
