# tenhle fajl pøelouskal: Mýval (myval@writeme.com). Naposledy editováno: 01/06/1999
# 0. Look
{100}{}{Zøejmì je to strážce.}
{101}{}{Ochránce.}

{150}{}{Kdyby nemìl sinavou tváø a rozšíøené zornièky, vypadal by jako normální èlovìk.}

# 1. Floats - When player first falls down hole
{200}{}{No teda!}
{201}{}{Oooh! To muselo zatracenì bolet.}

# 2. ( ) Floats - When player falls down hole other times.
{210}{}{Víš, že mùžeš použít druhý vchod...?}
{211}{}{Chachachacha!}
{212}{}{Neøeknu ani slovo.}
{213}{}{Bože! Ty mì znièíš. Tohle udìlat znovu!}
{214}{}{To je ale idiot!}
{215}{}{Hahahaha!}

# 3. ( ) First Time Talk
{220}{}{Dostali jsme instrukce odvést všechny Nadzemníky k Vegeirovi. Nic se ti nestane. Pojï prosím s námi.}
{221}{}{Táhnìte k èertu, nikam s vámi nepùjdu.}
{222}{}{Chci se na nìco zeptat.}
{223}{}{He?}

# 4. ( ) Go to hell
{224}{}{Chtìl bych ti to trochu ujasnit. Nic se ti nestane, pokud NEBUDEŠ klást ODPOR. Máš nìco proti tomu?}
{225}{}{Jasnì že jo, nikdy s vámi nepùjdu.}
{226}{}{Ne, je mi jasné, že odpor je marný. Pùjdu s vámi.}

# 5. ( ) Questions
{230}{}{Vegeir odpoví na všechny tvé otázky. Pojï prosím s námi.}
{231}{}{OK, pùjdu s vámi dobrovolnì.}
{232}{}{Ne, dokud nedostanu odpovìdi na pár otázek, tak s vámi nikam nepùjdu.}

# 6. ( ) You're dumb!
{240}{}{Ehmm... myslím, že ani ty nejsi výjimka. Hmm... Vegeir øekl VŠECHNY Nadzemníky, i kdyby to mìl být bùhvíjaký idiot. Pojï se mnou.}
{241}{}{[Jít se strážemi.]}
{242}{}{[Všechny pozabíjet. Jejich bohové si je potom pøeberou.]}

# 7. ( ) General Floats
{250}{}{Je mi líto; tudy nemùžeš jít.}
{251}{}{Tento vstup je pouze pro zamìstnance.}
{252}{}{Kvùli jednomu èlovìku se tu nevyplatí stavìt nìjakou skluzavku.}
{253}{}{Jestli chceš odejít, zeptej se nejprve Vegeira.}

# goes in node 3
{260}{}{Ojoj!}
