# tenhle fajl pøelouskal: Mýval (myval@writeme.com). Naposledy editováno: 01/06/1999
{500}{}{Vidíš obchodníka.}

# General (Roses B&B)
{100}{}{Róza dìlá nejlepší omelety.}
{101}{}{Psst... Drž se stranou od smažených kroket z brahmín.}
{102}{}{Zastavím se u Rózy, vždycky když mám pøíležitost.}
{103}{}{Chutnají vám Róziny omelety?}

# If player blows up the shitter (Roses B&B)
{110}{}{Necítíš nìco?}
{111}{}{Dobrý bože! K èertu, co v tom bylo?!}
{112}{}{Mohl byste prosím jít trochu dál? Pokouším se jíst.}

# Bedroom (Rose's B&B)
{120}{}{Nemùžeš dát pozor? Chtìl bych se vyspat.}
{121}{}{Hej, co dìláš v mém pokoji?!}
{122}{}{Vypadni!}

# If player let the chicken out of the coop (Roses B&B) overrides above text
{130}{}{Róze už došly omelety.}
{131}{}{Zabiju toho, kdo nechá to kuøe utéct.}
{132}{}{Proè bych tam chodil, když nemají omelety.}

# Pre Ghost General
{140}{}{Nevím, proè tu ještì zùstávám...}
{141}{}{Tohle mìsto umírá.}
{142}{}{Bývala to prosperující farmáøská osada.}

# If player kills Slags by himself
{150}{}{Slyšel jsem, že Modoc 'získal' prosperující farmu na severovýchodì.}
{151}{}{Nevím, jestli bych chtìl nakupovat potraviny z Farmy Duchù.}
{152}{}{Plodiny z Farmy Duchù jsou urèitì prokleté.}

# If town slaughter ghost farm
{160}{}{Slyšel jsem, že vraždí nevinné ženy a dìti.}
{161}{}{Nechci obchodovat s bezohlednými zabijáky.}
{162}{}{Potom co jsem slyšel, že dìlají, jsem se málem pozvracel.}
{163}{}{Myslím, že v Modocu už obchodovat nebudu.}
{164}{}{Lidé z Modocu jsou zabijáci.}

# If the player completes ghost farm seed - best ending.
{170}{}{Zdá se, že to bude dobré.}
{171}{}{Budu si muset najmout další lidi, aby odsud odnesli všechny potraviny.}
{172}{}{Nakonec to vypadá, že Modoc bude OK.}
