# tenhle fajl pøelouskal: Mıval (myval@writeme.com). Naposledy editováno: 01/06/1999
{100}{}{Vidíš vùdce Svìtloplachù.}
{101}{}{Vidíš Vegeira.}
{102}{}{Vysokı, statnı mu. Jeho pohyby ti pøipomínají koèku èíhající na svou koøist.}
{150}{}{Mùeš odejít padacími dveømi v zadní èásti budovy.}
{151}{}{Prosím, pøedej vzkaz do Modocu.}
{152}{}{Modoc leí na jihu.}
{153}{}{Jih.}
{154}{}{Ne, ten jinı jih.}
{155}{}{Návštìvník, právì vhod. Uvaoval jsem o zpùsobu, jak kontaktovat lidi na povrchu, ale teï u se tím nemusím zabıvat -- díky tvému pøíchodu. Vítej v sídle Svìtloplachù.}
{156}{}{Rád vidím tvùj návrat. Pøedpokládám, e zpráva byla doruèena do Modocu. Jak byla pøijata?}
{157}{}{Potøebují èas na rozmyšlenou.}
{158}{}{Mají nìjaké vıhrady.}
{159}{}{Chci vzít Jonnyho domù k rodièùm.}
{160}{}{Chceš nám tedy pomoci?}
{161}{}{Nejprve mám pár otázek.}
{162}{}{Odpovìï je stále NE.}
{163}{}{Moje rozhodnutí je, e vám pomohu.}
{165}{}{Díky za pomoc. Vdy tì tu rádi uvítáme. A za tvé sluby ti nabízím tuto odmìnu. [Vegeir ti podává samopal.]}
{166}{}{Díky za pomoc. Vdy tì tu rádi uvítáme.}
{167}{}{Mohl by se Jonny vrátit domù k rodièùm?}
{168}{}{Omlouvám se za nepøíjemné okolnosti, za kterıch se potkáváme. Normálnì by se tì snaili Ochránci zastrašit. Chøestìní øetìzù a zoufalı náøek vìtšinou kadého zaene pryè, ale teï mají pøíkazy, aby ke mnì pøivedli kadého ze shora, na koho narazí.}
{169}{}{To je v poøádku. Já u pùjdu.}
{170}{}{Co se mnou chcete udìlat?}
{171}{}{Duchové?}
{172}{}{Pùjdeš, a to dovolím. NE døív.}
{173}{}{Je to jednoduché. Potøebujeme se spojit s mìstem na jihozápadì; domnívám se, e se jmenuje "Modoc". Udìláš to pro nás?}
{174}{}{Jak se odsud dostanu?}
{175}{}{Chci se ještì zeptat na mnoho vìcí, ne pøijmu tento úkol.}
{176}{}{Dobrá tedy. Ani bych neoèekával, e od cizince jen tak pøijmeš úkol, a pøitom o nìm vlastnì nic nevíš. Ptej se, povím ti všechno, co vím.}
{177}{}{Proè nepošlete nìkoho z vašich lidí, aby doruèil zprávu?}
{178}{}{Povìz mi o vašich lidech.}
{179}{}{Jaká je vaše obrana?}
{180}{}{To u mi staèí. Mohu se rozhodnout.}
{181}{}{Ptej se.}
{190}{}{Proè se chcete vrátit na povrch?}
{191}{}{Proè ta velká maškaráda s duchy ???}
{192}{}{Co obsahuje ta vaše zpráva?}
{194}{}{Od UZAVØENÍ jsme se zmìnili. Jen málo z nás mùe snést pobyt na povrchu, protoe nejsme zvyklí mít nad sebou modroèerné moøe nicoty. Hrùza z pádu vzhùru je pro nás tak silná, e leíme úplnì pøimrazení k zemi, neschopni pohybu. Ale to není hlavní dùvod. Nikdo z nás nemùe vydret to jasné svìtlo, které vy nazıváte Slunce; díky dlouhodobému ivotu pod zemí jsou naše oèi pøíliš citlivé na svìtlo. Nemùeme cestovat daleko od bezpeèí našich domovù pod zemí.}
{195}{}{Mohu mít ještì další otázky?}
{197}{}{Kdysi dávno jsme byli jako lidé na povrchu. Také jsme ili nad zemí, dokud poár nezachvátil svìt. Naši pøedci, je byli souèástí tajné domobrany, se uzavøeli se svımi rodinami tady dole, aby se zachránili. Celé generace jsme ili zde, bezpeènì skrytí v lùnì Matky Zemì.}
{200}{}{Poèet našich obyvatel od UZAVØENÍ stále stoupal. Brzy bylo jasné, e nemùeme dále pøeít bez dalších zásob. Tak byla PEÈE rozlomena a my jsme se znovu vydali na povrch, abychom pøeili.}
{203}{}{Pøed lety se nìkdo pokoušel pøevzít naše farmy, sklízet plodiny a krást naše zvíøata. My nejsme násilníci, ale bylo nutné s tím nìco udìlat. Vdy na tìchto sklizních záleelo naše pøeití. A tehdy jsme si vymysleli
 duchy. Po natøení se svìtélkujícími houbami jsme mohli krásnì odstrašit zlodìje a další slídivé sousedy. Bohuel to bylo a pøíliš úèinné. Pozdìji, kdy jsme se chtìli kontaktovat s lidmi ijícími na povrchu, nikdo se k farmám nepøiblíil, protoe - mìl strach z duchù. Naštìstí jsi tu teï ty.}
{206}{}{U dost. ádné další otázky. Rozhodni se hned!}
{207}{}{Bohuel vám nemohu pomoci.}
{208}{}{Dobrá, nevidím v tom problém. Donesu vaši zprávu do Modocu.}
{209}{}{Mrzí mì to co slyším. Prosím, zatím ber na vìdomí, e jsi host Svìtloplachù. A se nám podaøí navázat kontakt s lidmi na povrchu, budeš moci odejít. Do té doby se nepokoušej opustit jeskynì - následky by byly nepøíjemné.}
{210}{}{S dokonèením novıch zavlaovacích systémù, produkce potravin pøekraèuje naše potøeby. Pøejeme si zaloit obchod s lidmi nahoøe a vymìòovat pøebytky potravin za mnohem potøebnìjší léky.}
{213}{}{Prosím, sdìl nám své rozhodnutí.}
{216}{}{Vìdìl jsem, e nás pochopíš. Zde je zpráva obsahující naše poadavky. Prosím, doruè ji do Modocu a pøedej pøíslušné osobì. A dokonèíš úkol, vra se zpìt. Øeknu Ochráncùm, aby oèekávali tvùj návrat. Dìkujeme ti za tuto slubu.}
{217}{}{Jak typické pro lidi z povrchu. Nikdy neudìlají nic pro druhého, jestlie z toho nemají osobní prospìch. Zøejmì nemùeme vìøit èlovìku, jako jsi ty. Najdeme tedy nìkoho jiného, kdo doruèí zprávu. Aèkoliv nejsme násilné povahy, nepokoušej se opustit jeskynì, nebo toho budeš litovat.}
{218}{}{Hmm, chápu. Takové rozhodnutí není jednoduché. Informuj mì prosím o veškerém dalším postupu.}
{219}{}{Tak mì u neobtìujte.}
{220}{}{Co?}
{221}{}{Oni vám nevìøí. Pøece jenom, zabíjíte kolemjdoucí a nabodáváte jejich tìla na kùly pøed farmou.}
{222}{}{Chtìjí vìdìt, co se stalo farmáøovi, kterı zde il.}
{223}{}{My jsme mírumilovní lidé a nikoho jsme nezabili. Ty tìla jsou pouze loutky, které jsme vyrobili, abychom zastrašili zlodìje. Kdy si pozornì prohlédneš ty tìla, zjistíš, e to jsou jen slepièí vnitønosti
 a figuríny.}
{224}{}{A co chudák Karl? Ten farmáø, kterı il na farmì?}
{225}{}{Tak se jmenoval, Karl? My jsme ho jen vystrnadili z farmy, nic víc. Pøedpokládám, e se vrátil domù, kdy zjistil, e na farmì straší. Ochránci zjistili, e odešel na západ. Mùeš ho tam zkusit hledat.}
{226}{}{Dobrá, budu vás informovat o dalším.}
{227}{}{My jsme ho jen vystrnadili z farmy, nic víc. Pøedpokládám, e se vrátil domù, kdy zjistil, e na farmì straší. Ochránci zjistili, e odešel na severozápad. Mùeš ho tam zkusit hledat.}
{231}{}{Vidím, e jsi potkal Jonnyho. Nalezli jsme ho, kdy bloudil v temnotách jednoho z našich nejhlubších tunelù. Øíkal, e spadl do vyschlé studny u jejich domu a pak se ztratil v dlouhıch tunelech a jeskyních. Postarali jsme se o nìj jako o vlastního a všichni ho zde milují - pochop, e jsem obezøetnı, kdy ho mám svìøit cizinci, kterı mi ještì nedokázal svoji dùvìryhodnost. Vrátím Jonnyho, a se ujistím, e se mùe dostat bezpeènì domù.}
{232}{}{Mám v tebe ji plnou dùvìru. Take - pøestoe zde budeme malého Jonnyho velmi postrádat, pøipravili jsme pro tebe a Jonnyho doprovod do Modocu.}
{233}{}{Èlovìèe! ádnı div, e tì naše malé triky nevydìsily. Jsi pøíliš tupı, ne aby tì to vydìsilo. Jsem velmi nerad, e se musím spoléhat na takto racionálnì zaloené individuum, ale potøebujeme tvoje sluby. Doruè tuto
 zprávu do Modocu. Pøedej ji vùdci Modocu a pokus se pøi tom neztratit.}
{300}{}{U pùjdu.}
{301}{}{Co ode mnì chcete?}
{302}{}{Sbohem.}
{303}{}{Eh, duchové?}
{400}{}{Zpráva byla pøijata kladnì. Obyvatelé Modocu chtìjí obchodovat s vašimi lidmi.}
