#tento soubor pøeloil Vachy - http://vachy.moje.cz
# QUICK LOOK
{100}{}{Vidíš pornohereèku.}

# EXAMINES
{150}{}{Vidíš atraktivní enu. Vypadá, e mluví sama se sebou.}
{151}{}{Vypadá, e si opakuje text. Pøesnìji øeèeno, nadskakuje, dìlá z jejich úst "O" a prohrabuje si vlasy.}
{152}{}{Vidíš pornohereèku. Docela chladnì tì ignoruje.}

# 1. [MALE, ENCLAVE IS DESTROYED]
{200}{}{Asi bych ti mìla podìkovat za to, e jsi zachránil svìt. Bohuel nic nemám, take se budeš muset spokojit pouze s divokım sexem. Staèí to?}
{201}{}{Slyšela jsem, e jsi ten, kdo nakopal Enklávì prdel.}
{202}{}{Ten chlap, co rozsekal zlou vládu Enklávy mì docela rajcuje.}
{203}{}{Slyšela jsem, e tì hledají Korsiètí bratøi. Chtìjí natoèit film na základì tvého pøíbìhu.}

# 2. [FEMALE, ENCLAVE IS DESTROYED]
{210}{}{Asi bych ti mìla podìkovat za to, e jsi zachránila svìt. Uh...dík.}
{211}{}{Slyšela jsem, e jsi ta co nakopala Enklávì prdel. Jsem unesena.}
{212}{}{Slyšela jsem, e tì hledají Korsiètí bratøi. Chtìjí natoèit film na základì tvého pøíbìhu. Uh, nenašla by se pro mnì malá role...?}

# 3. [POWER ARMOR]
{220}{}{Mohl bys tady PROSÍM pøestat poskakovat jako eleznej pták. Snaím si zapamatovat text.}
{221}{}{Vra se do hry, ze které jsi pøišel! Tohle není Quake!}
{222}{}{U s tím koneènì pøestaneš?}

# 4. [PORN STAR]
{230}{}{Jak si dneska stojíš, }
{231}{}{Vypadáš dobøe, }
{232}{}{Hele, zlato! Dej na sebe pozor.}
{233}{}{Ještì jsem nedostala poøádnì zaplaceno.}
{234}{}{No uvidíme... "O boe"... "ještì..." Krucinál! Zapomnìla jsem text?!}
{235}{}{Ano, ale jakou pro mì za to máte MOTIVACI?}
{236}{}{Podívejme...(Studuje text)... vejdu a pak budeme šukat jako králíci. Tak jo.}
{237}{}{Nejradìj mám, kdy se jde pøímo na vìc.}
{238}{}{Díky bohu, koneènì èalounìná pelest.}
{239}{}{Vùbec nevím, co na ní Korsiètí bratøi VIDÍ...}
{240}{}{Bude lepší kdy odejde.}
{241}{}{Kazí mi styl.}
{242}{}{Oh, ona je chlapo-rout, no hotovı kanibal.}
{243}{}{Hmmpph. Dobrı odpad.}
{244}{}{Má asi tolik talentu jako kámen a je dvakrát tak špinavá.}

# 5. [PRIZEFIGHTER]
{250}{}{Jak si dneska stojíš, }
{251}{}{Tak tohle jsou pøesnì ty problémy, co jsem fakt chtìl.}
{252}{}{Koukáš na mì?}
{253}{}{Proè se tu neukáeš èastìji?}
{254}{}{Mám dírku, kterou bys mohl vyplnit.}
{255}{}{Správnımu chlapovi nezáleí na èase...}
{256}{}{No uvidíme... "O boe"... "ještì..." Krucinál! Zapomnìla jsem text?!}
{257}{}{Ano, ale jakou pro mì za to máte MOTIVACI?}
{258}{}{Podívejme...(Studuje text)... vejdu, budem šukat jako králíci. Tak jo.}
{259}{}{Nejradìj mám, kdy se jde pøímo na vìc.}
{260}{}{Díky bohu, koneènì èalounìná pelest.}

# 6. [MADE MAN]
{265}{}{Jak si dneska stojíš, }
{266}{}{Tak tohle jsou pøesnì ty problémy, co jsem fakt chtìl.}
{267}{}{Koukáš na mì?}
{268}{}{Proè se tu neukáeš èastìji?}
{269}{}{Mám dírku, kterou bys mohl vyplnit.}
{270}{}{Správnımu chlapovi nezáleí na èase...}
{271}{}{No uvidíme... "O boe"... "ještì..." Krucinál! Zapomnìla jsem text?!}
{272}{}{Ano, ale jakou pro mì za to máte MOTIVACI?}
{273}{}{Podívejme...(Studuje text)... vejdu, budem šukat jako králíci. Tak jo.}
{274}{}{Nejradìj mám, kdy se jde pøímo na vìc.}
{275}{}{Díky bohu, koneènì èalounìná pelest.}

# 7. [NO REP]
{280}{}{Co to tak smrdí?}
{281}{}{Skvìlé. Další vyznavaè análu.}
{282}{}{Nemluv na mì.}
{283}{}{No uvidíme... "O boe"... "ještì..." Krucinál! Zapomnìla jsem text?!}
{284}{}{Ano, ale jakou pro mì za to máte MOTIVACI?}
{285}{}{Podívejme...(Studuje text)... vejdu, budem šukat jako králíci. Tak jo.}
{286}{}{Nejradìj mám, kdy se jde pøímo na vìc.}
{287}{}{Díky bohu, koneènì èalounìná pelest.}
{288}{}{A poøád se neptej, co máš dìlat. Mysli si to tiše pro sebe, potom ti klidnì budu pøiráet.}
{289}{}{Kdo jsi?}
{290}{}{Ty jsi jeden z vyznavaèù sado-maso?}

# 8. [POWER ARMOR]
{295}{}{Nejsi trochu malı na Stormtroopera?}
{296}{}{Aighhhhhh! Co zas zkoušíš? Chceš abych dostala infarkt?!Vypadni odsud!}
{297}{}{Na JAKİ film to proboha zkoušíš? Na Konec Všech Dní Zemì? Ztra se!}
{298}{}{Mohl bys tady PROSÍM pøestat poskakovat jako eleznej pták. Snaím si zapamatovat text.}
{299}{}{U s tím koneènì pøestaneš?}

# 9. [MALE, PORN STAR]
{305}{}{Jak si dneska stojíš, }
{306}{}{Chceš mi pomoct pøezkoušet si text naostro?}
{307}{}{Nechceš jít se mnou na chvíli do sprchy, døív ne pùjdem na scénu?}
{308}{}{Miluju to, co umíš s jazykem}
{309}{}{Øíkají o mì, e v orálu jsem ještì student.}
{310}{}{V dalším zábìru jsi lokaj nebo dveøník?}
{311}{}{Nemohla bych se nabudit trochou Jetu?}
{312}{}{Tyhle scény mì vzrušujou... ehm, zaèínám se rozehøívat.}
{313}{}{Myslím, e KONEÈNOU scénu budem dìlat spolu.}
{314}{}{Mùj kluk neví, e to dìlám. A doufám, e se to ani nedozví.}
{315}{}{Nejsou tady nìkde Korsiètí bratøi...moná budou v kanclu?}
{316}{}{Ani mì nezajímá, co se pak s tím filmem dìje, hlavnì e kamera bìí.}
{317}{}{Ty jsi mu vášnì a tajemství. Prostì chlípník.}
{318}{}{Dobrá, kdy jsi tak línej, klidnì to budu dìlat na konì.}
{319}{}{Na další scénu budu pøipravená, teprve a si dá dlouhou a horkou sprchu.}
{320}{}{Mùj klín je otevøen pro všechny, co chtìjí lásku.}
{321}{}{Jednou budu hvìzda. Velká, jasná a záøící hvìzda.}
{322}{}{Støíkáš asi jako kdy má sopka svı špatnı dny.}
{323}{}{Miluju, kdy mluvíš se španìlskım pøízvukem.}
{324}{}{Vypadáš skvìle, zlato.}

# 10. [PORN STAR, FEMALE]
{330}{}{::Ignoruje tì::}
{331}{}{V další scénì hraješ Francouzku nebo Rusku?}
{332}{}{Pøála bych si, abys ten orgasmus hrála trochu víc pøirozenì.}
{333}{}{Neukradla jsi mi náhodou podvazky?}
{334}{}{Jsem asi unavená... nemáš trochu Jetu?}
{335}{}{Hmphhh!}
{336}{}{Je mi líto, drahoušku. Nevím kde Bratøi jsou.}
{337}{}{Ukáu ti cestu ven.}
{338}{}{U ses byla váit?}
{339}{}{Mùeš prosím tì trochu poodstoupit. Tvoje... malièkost... mì trochu rozrušuje.}
{340}{}{Slyšela jsem, e tì Korsiètí bratøi chtìj nechat vyhodit, to je mi ale smùla.}
{341}{}{I kdy nemáš talent, tak se to urèitì pùjde dát vypilovat, tím jsem pøesvìdèená.}
{342}{}{Máš fakt velkou prdel, jak roztomilé!}
{343}{}{Øeknu ti, e není tìké pracovat v tomhle byznysu.} #businnesu 
{344}{}{*Já* jsem o tobì nikdy neøíkala e jsi tlustá nebo špinavá. To musel bıt urèitì nìkdo jinı.}
{345}{}{Slyšela jsem, e s tebou nikdo nechce dìlat.}
{346}{}{Doufám, e pøedtím, ne ses oholila, ses taky vykoupala?}

# 11. [MALE, PRIZEFIGHTER OR MADE MAN]
{350}{}{Jak si dneska stojíš, }
{351}{}{Pøímo z boxu do porno-byznysu? Stejná vìc, jiné jevištì.}
{352}{}{Nechceš si to se mnou rozdat, šampióne?}
{353}{}{Chceš si zaboxovat, šampióne?}
{354}{}{Dej si bacha na Masticatora. Je fakt blbej. U mi pøi tom nìkolikrát málem utrhl ucho.}
{355}{}{Chceš mi pomoct pøezkoušet si text naostro?}
{356}{}{Nemohla bych se nabudit trochou Jetu?}
{357}{}{Tyhle scény mì vzrušujou... ehm, zaèínám se rozehøívat.}
{358}{}{Pøijï si prohlídnout nìjakı èasáky.}
{359}{}{Koukám, pìkná vıbavièka.}
{360}{}{Mùj kluk neví, e to dìlám. A doufám, e se to ani nedozví.}
{361}{}{Jestli hledáš spoleènost, tak nepoèítej e pak nìco bude.}
{362}{}{Tak co pøejdeš k nám? Vítej.}
{363}{}{Máte tu dobré zaøízení.}
{364}{}{Mohl bys klidnì dìlat porno. Máš na to figuru.}
{365}{}{Koukám, pìkná vıbavièka.}
{366}{}{Jestli hledáš spoleènost, tak nepoèítej e pak nìco bude.}
{367}{}{Slyšela jsem o tobì. Ty jsi }
{368}{}{Šéf tì pro mì poslal?}
{369}{}{Ty by sis se mnou chtìl píchnout? Ale no tak.}
{370}{}{U se o mì šéf zmínil?}

# 12. [FEMALE, PRIZEFIGHTER OR MADE MAN]
{380}{}{A co je vlastnì na boxu?}
{381}{}{Dej si bacha na Masticatora. Je fakt blbej. Jednou si mi pokusil ukousnout ucho.}
{382}{}{Miluju ten oblek. Opravdu ti sekne.}
{383}{}{Ty hadry na tobì vypadaj skvìle.}
{384}{}{Co zase chce... oh! enská! Vítejte ve studiu.}
{385}{}{Mùj kluk neví, e to dìlám. A doufám, e se to ani nedozví.}
{386}{}{Um...nemohla bys mì rozehøát trochou Jetu, prosím?}
{387}{}{Tyhle scény mì vzrušujou... ehm, zaèínám se rozehøívat.}
{388}{}{e potom nic nebude? Er... no, tím bych si nebyl tak jistı.}
{389}{}{Jakı to je dìlat pro šéfa?}
{390}{}{U se o mì šéf zmínil?}

# 13. [LEATHER]
{395}{}{Podívej, bondage a S&M dìláme jen ve støedu. A teï pohni tou svojí koenou prdelí a zmiz odsud.}
{396}{}{Opravdu pochybuju o tom, e by Bratøi chtìli natoèit další koenou show po tom fiasku se Šastnou Hodinou Kùe.}
{397}{}{Pøestaò mì prosím tì otravovat. Pokouším se zapamatovat si text.}
{398}{}{MYSLÍM e cítím kùi. Asi to bude gauè.}
{399}{}{Podívej, koenej králíèku, jestli nemáš vlastní biè, Bratøí se s tebou nebudou ani bavit.}

# 14. [MALE, NO REP]
{410}{}{Ty? Né dík. To si to radìji rozdám se svojí rtìnkou.}
{411}{}{Proè se radìji nezkosíš pobavit s oøezávátkem na tuky?}
{412}{}{Nemám èas na to, abych tu s tebou právì teï vedla nezávaznou konverzaci.}
{413}{}{Vùbec mì nedojímá, e umíš s penisem zatloukat desítky høebíky. A teï zmiz.}
{414}{}{Sex? Ne, jsem vdaná a i kdyby ne, stejnì nechci.}
{415}{}{S bìlochama nechodím.}
{416}{}{Nemùeš bıt lepší ne mùj masání strojek.}
{417}{}{Nemáš na to, abys mì poøádnì rozehøál.}
{418}{}{Zlato, se mnou si to asi nerozdáš.}
{419}{}{Hledám jenom toho správného chlapa. Dík, e mi dìláš spoleènost, ne pøijde.}
{420}{}{V ádném pøípadì se do mojí svatynì nedostaneš. Tam je místo jenom pro jednoho.}
{421}{}{Promiò, udìlala jsem chybu. Myslela jsem, e vypadáš líp.}
{422}{}{Ty? Promiò, NIKDY nebudu tak zoufalá.}
{423}{}{Bratry v triku jsem tu nikde nevidìla... a teï pøestaò otravovat. Jsem hereèka.}
{424}{}{Prosím... ádné autogramy.}
{425}{}{Opravdu chci jít pøímo na to.}
{426}{}{Kadé úterı tancuju v kasínu. Pøijï se klidnì podívat a vem sebou nìjakou škváru.}
{427}{}{Nedokáeš si vybavit, co všechno musím podstoupit.}
{428}{}{Mùj kluk neví, e to dìlám. A doufám, e se to ani nedozví.}
{429}{}{Prosím pøestaò mì vyrušovat. Snaím se zapamatovat si text.}
{430}{}{Hledáš práci, promluv si s Bratry v triku.}
{431}{}{Ty jsi novı uklízeè?}
{432}{}{Ty jsi novı vrátnı? Nic jiného bys asi dìlat nemohl.}
{433}{}{Jestli jsi novı vrátnı, tak mi mùeš vylízat prdel.}
{434}{}{Bratry v triku jsem tu nikde nevidìla dìvèe... a teï pøestaò otravovat. Jsem hereèka.}
{435}{}{Prosím dìvèe... ádné autogramy.}
{436}{}{Moná bys mohl umıt nejdøív sám sebe, ne tu budeš uklízet.}
{437}{}{Promiò, lesbickou lásku dìlám za 200 babek. Pro tebe za 300.}
{438}{}{Kadé úterı tancuju v kasínu. Pøijï se klidnì podívat a vem sebou nìjakou škváru.}
{439}{}{Dìvèe, vùbec netušíš, co všechno musím podstoupit.}

{1230}{}{?}
{1231}{}{.}
{1250}{}{?}
{1265}{}{?}
{1305}{}{?}
{1350}{}{?}
{1367}{}{, e jo?}
