# Tento soubor pøeložil Radim "HIGHTOWER" Brix , hightower@angelfire.com
{100}{}{Vidíš mrzutou brahmínu.}

# 0. LOOK
{150}{}{Vidíš obrovskou, mrzutou brahmínu. Její bøicho vypadá nafoukle, a oèi má podlité krví.}
{151}{}{Vidíš obrovskou, mrzutou brahmínu. Její bøicho vypadá nafoukle, a oèi má podlité krví. Vypadá velmi nemocnì. Možná je tu nìjaká možnost jak jí pomoci.}

# 2.  FLOAT/CLICK
# success doctor skill
{198}{}{::Rnnnrrrrr?::}
{199}{}{::Hrrnnnnr?::}
# any
{200}{}{Muu}
{201}{}{Muuuuuuuuu}
{202}{}{Muuuu}
{203}{}{::Rnnr::}
# failed doctor skill
{204}{}{::Rnnnrrrrr!!!::}
{205}{}{::Gnnnnnrrrr!!!::}
{206}{}{::Hrrnnnnr!!!::}

# 3.  DESCRIPTION: GOOD DOCTOR SKILL
{225}{}{To co mìla brahmína zaklínìno ve støevech, jsi úspìšnì vytáhl.}

# 4.  DESCRIPTION: FAIL DOCTOR ROLL
{235}{}{To co má brahmína zaklínìno ve støevech, jsi nedokázal vytáhnout.}
