# Tento soubor pøeložil Radim "HIGHTOWER" Brix , hightower@angelfire.com
{100}{}{Dámy a pánové!}
{101}{}{Vážení pøítomní!}
{102}{}{Dnešní zápas vám pøináší...}

{103}{}{...ROTGUT!}
{104}{}{Když opravdu MUSÍTE mít nìco k pití a je vám celkem fuk, co to je ...}
{105}{}{Vyberte si Rotgut!}

{123}{}{...Pivo Gamma Gulp !}
{124}{}{Když má vaše kùže nedostatek "speciálního plamene"...}
{125}{}{Vyber si pivo Gamma Gulp !}

{143}{}{...Koèièí Packa!}
{144}{}{Když vás nìco svìdí a potøebujete NUTNÌ podrbat..}
{145}{}{Jdìte po hlavì do Koèièí Packy!}

{163}{}{...New Reno Arms!}
{164}{}{Když chcete nìkoho zabít z bezpeèné vzdálenosti...}
{165}{}{Stavte se u New Reno Arms!}

{106}{}{V tomhle rohu, zápasník, vážící }
{1106}{}{ liber, èerstvý z pustiny a nový v New Reno, }
{2106}{}{!}
{107}{}{A v tomhle rohu...vážící }
{1107}{}{ liber, ZNÁTE ho, MILUJETE ho... }
{2107}{}{!}
{108}{}{Takže, bez dalšího prodlužování...}
{109}{}{Šou ZAÈÍNÁÁÁ!}

{200}{}{A vítìzem se stávááááá...}
{201}{}{...stylem k.o....}
{202}{}{...technickým k.o....}
{203}{}{...po diskvalifikaci soupeøe...}
{204}{}{...na body }
{205}{}{ k }
{206}{}{...}

{210}{}{!!!}
