# Tento soubor pøeložil Radim "HIGHTOWER" Brix , hightower@angelfire.com
{100}{}{Vidíš barmana.}

# EXAMINE
{150}{}{Vidíš tlustšího muže peèujícího o bar. Kýve na tebe hlavou.}

# 1. FLOAT DIALOGUE: ENCLAVE DESTROYED IS TRUE (WTG)
{200}{}{Hej! }
{201}{}{! Cesta k nakopání prdele Enklávì! Chceš drink?}

# 2. FLOAT DIALOGUE: PLAYER = FEMALE/MALE, MADE MAN, FA = SAME CASINO (WTG)
{206}{}{! Co se dìje?!}

# 3. FLOAT DIALOGUE: NORMAL (WTG)
{210}{}{Jedna sklenka rotgutu pøijde vhod...}
{211}{}{To budou 3$...}
{212}{}{Další, kamaráde?}
{213}{}{Tady je propustka, jestli ji potøebuješ.}
{214}{}{Nevdechuj ten Jet celý najednou... trochu potáhni, hluboce se nadýchni a dej tomu èas než ti to 
 projde celým tìlem.}
{215}{}{Chceš to do balíku nebo do plechovky?}
{216}{}{Extra sklenka na Jet...}
{217}{}{Nech mì hádat: Napíšeš to na tvùj úèet?}
{218}{}{Jednu atomovku na žaludek, dìlej.}
{219}{}{Nedovolujeme zákazníkùm brát tady Buffout, kamaráde.}

# 4. CLICK DIALOGUE: THREAT (WTG)
{225}{}{Radìji odsaï odejdi døív než ti toho donesu víc než zvládneš, rozumíš?}
{226}{}{Slyšíš... vypadni. Nechceme tu žádné potíže.}
{227}{}{Jsou schopni tì zabít pokud odsaï neodejdeš. Vypadni.}
{228}{}{Všechno nám už došlo. Takže odejdi, ožralo.}

# 5. INTRO (WTG)
{236}{}{! Co piješ?}
{237}{}{Heeee, chlape! Co to piješ za svinstvo?}
{238}{}{Co piješ, kamaráde?}
{239}{}{Co piješ, drahoušku?}
{240}{}{Alko-hul zní dobøe.}
{241}{}{Alkohol?! Já chci alkohol!}
{242}{}{Co se dneska èepuje?}
{243}{}{Jaké druhy drog tady máš?}
{244}{}{Kdo je ten dìdek u toho posraného automatu na prachy?}
{245}{}{Kdo je ten chlápek s nožem u baru?}
{246}{}{Dnes si nedám nic, dìkuji.}

# 6. WHAT'S WITH McGEE? (5)
{250}{}{Oh, ty myslíš starého McGee? On je vìtšinou neškodný. Svùj osud zpeèetil s tímhle
 starým automatem na prachy. V každém pøípadì... mùžu ti nìco nabídnout?}

# 7.  WHAT'S WITH LIL' JESUS? (5)
{260}{}{To je Jesusùv malý chlapec, Malý Jesus. On a jeho nùž jsou nejlepší
 pøátelé... Vidìl jsem ho jak sním udìlal pár hrozných vìcí. V každém pøípadì, mùžu ti
 nìco nabídnout?}
