# Tento soubor pøeložil Radim "HIGHTOWER" Brix , hightower@angelfire.com
{100}{}{Vidíš Frenchyho.}
{101}{}{Vidíš Paina.}
{102}{}{Vidíš Simse.}

# 0. MALE (WTG)
{150}{}{Vidíš rozcuchaného a otrhaného muže. Nachází se vedle sudu s ohnìm, zpívá. Má velmi pìkný hlas.}
{151}{}{Vidíš zpìváka. Nachází se vedle sudu s ohnìm, zpívá.}

# 1. CLICK (WTG)
{200}{}{Hej... }
{1200}{}{! Velký hrdino! Jak ti mùžeme pomoci? Zazpívat ti nìco speciálního, eh?}
{1201}{}{. Mùžeme ti nìjak pomoci?}
{1202}{}{. Pomoct ti s nìèím, šampióne?}
{203}{}{Moh bych ti s nìèím pomoci synu?}
{204}{}{Moh bych s nìèím pomoci madam?}
{205}{}{Znáš píseò 'Láska je láska?', zpívala to kdysi nìjaká Bílá?}
{206}{}{Kene... Kene zahraješ Flašky piva na zdi?}
{207}{}{Neeee, právì odcházíme}
{208}{}{Byl sem poctìn. Díky, chlapci.}
{209}{}{Tady je pár drobných. Mùžete zahrát nìco jiného?}
{210}{}{Ne, jenom poslouchej, díky.}

# 2. SURE (1)
{300}{}{Dobrá tedy... slyšeli jste tohodle chlapce, pøátelé. Takže zkusme taky nìco jiného.}
{301}{}{Dobrá tedy... slyšeli jste tuhle sleènu, pøátelé. Takže zkusme taky nìco jiného.}
{302}{}{Dìkuji}
{303}{}{Díky, pánové.}

# 3. FLOAT (SONG] (WTG)
{400}{}{Oooooh}
{402}{}{Má láska se nevrací domù...}
{405}{}{Má láska už mì asi nemá rááááda...}
{408}{}{Má láska odešla a já zùstal tak sáááám...}
{409}{}{}

# 4. FLOAT (SONG] (WTG)
{500}{}{Jdi na to}
{501}{}{Zkus bolest}
{502}{}{Zkus to znova tøeba další den}
{503}{}{}

# 6. FLOAT (SONG] (WTG)
{600}{}{ Flašky piva na zdi...}
{601}{}{ Flašky piva...}
{602}{}{Sejmi jednu dolù...}
{603}{}{Nechej je tam ležet a projdi se kolem (To je ale blbý text pisnièky pozn. Hightower)...}
{605}{}{}

# 7. FLOAT (SONG] (WTG)
{700}{}{Láska je láska...}
{701}{}{Když chodìj kluci s klukama...}
{702}{}{A holky s holkama...}
{703}{}{Mácha má štìstí, že je kamennej...}
{706}{}{Jinak by už nestál, smíchy by øval a byl by v pase zlomenej ...}
{707}{}{}

# 8. FLOAT (HERO SONG] (WTG)
{800}{}{Nepotøebujeme dalšího hrdinu...}
{801}{}{Nepotøebujeme vìdìt cestu zpìt domù...}
{802}{}{Vše co potøebujeme je to co je na druhé stranì...}
{803}{}{Metadon}
{804}{}{}

# 5. FLOAT (SONG] (WTG)
{900}{}{Dej mi}
{901}{}{Polibek po kterém zaèneš snít}
{902}{}{A moje pøedstavivost}
{903}{}{Zaène hned, pøi tomto polibku, naplno pracovat}
{904}{}{Mmmmm}
{905}{}{Zlatíèko,}
{906}{}{Neptám se tì na víc než na tohle:}
{910}{}{Políbíš mì na rozlouèenou}
{912}{}{Naplníš mé hladové srdce}
{913}{}{Ponechej mi aspoò jednu vìc døív než se...}
{915}{}{Když jsem sám}
{916}{}{S mými pøedstavami}
{917}{}{Budu s tebooou}
{918}{}{Prožívat romantiku}
{919}{}{Vìøit, že vše je pravdivé}
{920}{}{Oh, pøibliž své rty aspoò na chvíli}
{921}{}{A díky mé pøedstavivosti se tento okamžik stane skuteèností...}
{923}{}{Dej mi to co mi mùžeš dát}
{925}{}{::Trumpeta::}
{930}{}{Budu... s tebooou}
{933}{}{Ohhhh}
{935}{}{rty aspoò na chvíli}
{937}{}{udìlají tento okamžik skuteèností}
{941}{}{}
