# Tento soubor pøeloil Radim "HIGHTOWER" Brix , hightower@angelfire.com
{100}{}{Vidíš Velkého Jeíše Mordina.}

# 0. LOOK
{150}{}{Vidíš tlustého mue s èernıma praseèíma oèima. Tìce dıchá a je celı zpocenı.}
{151}{}{Vidíš Velkého Jeíše Mordina. Tìce dıchá a je celı zpocenı.}

# 1. WARNING FLOAT (WTG)
{200}{}{Jdi od tama pryè.}
{201}{}{Tohle... tohle ti nepatøí.}
{202}{}{Ještì jednou se toho dotkni, a skonèíš... mrtvı v Golgothì.}

# 2. FLOAT (WTG)
{210}{}{::Sípání::}
{211}{}{*kašel* *kašel*}
{212}{}{::Utøe si pot z èela.::}

# 3. MADE MAN: MORDINO (WTG)
{220}{}{Jsi... *kašel*... jeden z mıch nejlepších muù.}
{221}{}{Projevují ti lidé v New Reno... *kašel*... dostateènı respekt?}

# 4. MORDINO HEART ATTACK (WTG)
{230}{}{Urgggg...}
{231}{}{...Dios mio...}
{232}{}{...moje srdce...}
{233}{}{hurrkkkk}

# 5.  NORMAL INTRO (WTG)
{240}{}{(Mu se k tobì otoèil. Vypadá e má horeèku: Pot mu stéká dolù po jeho tváøi a vytváøí mokré skvrny na obleèení. }
{241}{}{Tebe ignoruje a upøenì se dívá na Myrona; (vypadá jako by èekal, a si s ním bude moci promluvit.)}
{242}{}{Upøenì se na tebe dívá; vypadá to jako by èekal, a si s tebou bude moci promluvit.)}
{243}{}{Podíval ses na nìho protivnım pohlede.}
{244}{}{Podíval ses na nìho s mírnım nezájmem.}
{245}{}{Podíval ses na nìho s vısmìvnım pohledem}
{246}{}{Podíval ses na nìho s pøedstíranım nezájmem}
{247}{}{Asi jsem se zatoulal}
{248}{}{Kdo jste?}
{249}{}{Jste Jeíš Mordino?}
{250}{}{Pardon. Asi jsem vlezl do špatné místnosti.}

# 6. STARE BACK AT HIM (WTG, 5, 19, 22, 28, 30, 33)
{260}{}{Ty. (Kdy vešel Myron Mordino se na nìj upøenì podíval, v oèích se mu zablısklo.) Ty jsi... opustil pevnost. Moje trpìlivost je u... konce. (Dal svım muùm pokyn a oni hned vytasili zbranì.)}
{261}{}{(Mu se otoèil a podíval se na své stráce. Dal jim pokyn a oni hned vytasili zbranì.)}
{262}{}{(Velkı Jeíš se otoèil a podíval se na své stráce. Dal jim pokyn a oni hned vytasili zbranì.)}
{263}{}{Aieeeeeeee!}
{264}{}{Hrej si jinde!}
{265}{}{Utíkej!}
{266}{}{Huaa! Huaa...!}
{267}{}{Hej! Zastav se na chvíli...!}
{268}{}{Chceš TOHLE, *Tlusochu?!* Já ti ukáu kdo JE to }

# 7. WHO ARE YOU? (WTG, 5)
{275}{}{(Mu zaèal mluvit skøípavım hlasem.) Já... jsem Jeíš Mordino. Ty mì oslovuj... Seòore Mordino. (Kapka potu mu stekla z èela.)
  Copak... potøebuješ?}
{276}{}{Ty ses... vrátil. (Kapka potu mu stekla z èela.) Copak... potøebuješ?}
{277}{}{Hledám práci.}
{278}{}{Mluvil jsem s vaším synem, seòore Mordino. Hledám práci.}
{1278}{}{Mluvil jsem s vaším synem, seòore Mordino. Jsem otrokáø a hledám práci.}
{279}{}{Mluvil jsem s vaším synem, seòore Mordino. Jsem otrokáø a chtìl bych vám prodat nìjaké otroky.}
{280}{}{Nevíte nìco o smrti Wrightova syna?}
{281}{}{Nemáte potíe s tím horkem tady? Nepøipadá vám to... nepohodlné?}
{282}{}{Dnes nic. Radìji odejdu.}

# 8. I'M LOOKING FOR WORK [REFUSE] (7, 12)
{290}{}{(Dlouho si tì prohlíí a pak zakroutí hlavou.) Ty... nejsi pro mì dost SILNİ. Nemám pro tebe práci.}
{291}{}{(Dlouho si tì prohlíí a pak zakroutí hlavou.) Ty jsi... ENA. Tahle práce není pro eny, prostì to není enská práce.}
{1291}{}{Dobrá. Nemáte zájem koupit nìjaké otroky?}
{292}{}{Dejte mi šanci. Dejte mi práci -- jakoukoli -- udìlám všechno co si budete pøát.}
{293}{}{Dejte mi šanci, seòore Mordino. Dejte mi práci, jakoukoli, udìlám všechno co si budete pøát.}
{294}{}{Tak si mì vyzkoušejte. Udìlám všechno co si budete pøát.}
{295}{}{Tak si mì vyzkoušejte, seòore Mordino. Udìlám všechno co si budete pøát.}
{296}{}{Tak dobøe. Nìkdy pøíštì.}

# 9. I'M LOOKING FOR WORK [SECOND TIME REFUSE] (8, 25, 50)
{305}{}{(Kapka potu stekla Mordinovi po tváøi. Jeho vıraz v tváøi znejasnìl.) Øeknu ti... NEMÁM pro tebe práci. Odejdi... a u se NEVRACEJ.}
{306}{}{No tak, Velkı Jeíši... aspoò jednu šanci...}
{307}{}{Dobrá tedy. Nashledanou.}

# 10. BAD NEWS (9, 17, 33, 47)
{315}{}{(Mordino byl chvíli potichu a pak zaèal mluvit.) Já jsem Jeíš Mordino. Hlava Mordinovy rodiny. Vstoupil jsi do
 ... mého kasína. Mého domova. Neprojevil jsi mi ani trochu... úcty. Já tì NAUÈÍM.}
{316}{}{Myslím, e to budeš TY, kdo se bude muset nauèit jednu nebo dvì vìci...}
{317}{}{Zadr... pojïme si o tom promluvit! No tak, teï...}
{318}{}{Zaèít utíkat ke dveøím.}
{319}{}{::Utíkáš aby ses schoval, strašnì pomalu vytahuješ zbraò.::}

# 11. QUESTION NODE (12, 13, 14, 15, 16, 46, 47, 48, 49)
{325}{}{(Mordino èeká. Jak se tak na nìho díváš, vidíš jak další mu další kapka potu stéká dolù po tváøi.)}
{326}{}{Chtìl bych prodat pár otrokù...}
{327}{}{Co víte o smrti Richarda Wrighta?}
{329}{}{Nevadí.}

# 12. SLAVER (7, 11)
{335}{}{(Prohlíí si tì.) Sice tì... neznám, ale... poslouchám. (Utøe si pot z èela.) }
{336}{}{Ty máš otroky na prodej?}
{337}{}{Ano, jsou tu se mnou. Podívejte se a udìlejte mi nabídku.}
{338}{}{Ne, nemám. Vlastnì jsem se zmılil. Hledám práci a nechci prodat ádné otroky.}
{339}{}{Ne... vlastnì, mám na vás otázku.}
{340}{}{Ne, pardon. Teï jsem si vzpomnìl, e bych mìl bıt nìkde jinde.}

# 13. SLAVE DEALINGS? (12, 16)
{345}{}{(Mordino si prohlíí tvé spoleèníky. Jeho pohled strnul na Mirii, olízl si rty.) Tvá prostitutka vypadá èerstvì... Dám ti za ni 250 babek.}
{346}{}{(Mordino si prohlíí tvé spoleèníky. Jeho pohled strnul na Davinovi.) Vzal bych si támhle toho chlapce, tøebae vypadá slabì. Nabízím ti za nìho 200 babek.}
{347}{}{(Mordino si prohlíí tvé spoleèníky. Jeho pohled strnul na Sulikovi... podíval se na jeho nos a párkrát ho zmáèknul.) Domorodec... smrdí, ale
 vypadá silnì. Nabízím ti za nìho 100 babek.}
{348}{}{(Mordino si prohlíí tvé spoleèníky. Jeho pohled strnul na Vicovi.) Vzal bych si tady toho staøíka... vypadá, e u nìco odpracoval. Mùe se mi na ledacos
 hodit. Nabízím ti za nìho 100 babek.}
{349}{}{(Mordino si prohlíí tvé spoleèníky. Jeho pohled strnul na Cassidym.) Vzal bych si toho staršího chlápka... vypadá dost zkušenì a mohl
 by se mi hodit. Nabízím ti za nìho 100 babek.}
{350}{}{(Mordinùv pohled ihned strnul na robotovi.) Ten stroj tam. Nabízím ti za nìj 500 babek.}
{351}{}{(Mordinùv pohled ihned strnul na robopsovi.) Tamto koupím... toho mechanického psa. Nabízím ti za nìj 500 babek.}
{352}{}{(Mordino si prohlíí tvé spoleèníky, pak zakroutí hlavou.) Nemáš nic co bych potøeboval.}
{353}{}{Seòore Mordino, prosím... tenhle otrok má VÌTŠÍ cenu, ne tu kterou nabízíte. Urèitì vám budou slouit hodnì dlouho.}
{354}{}{To je férová cena. Mùete si toho otroka vzít.}
{355}{}{Vlastnì, tohodle otroka ještì nechci prodat. Mìl bych pár otázek na které bych se vás rád zeptal...}
{356}{}{Popravdì, nechci prodat ádné otroky. Snad uzavøeme nìjakı obchod pøíštì.}
{357}{}{Dobrá. Mám na vás otázku, nicménì...}
{358}{}{Dobrá. Tak nìkdy pøíštì, a budu mít lepší zboí.}

# 14. SLAVE DEALINGS 2, BARTER FAIL (13)
{370}{}{Ne. Je na ní vidìt, e hodnì cestovala a vypadá dost unavenì... 250 babek nebo nic.}
{371}{}{Ten chlapec vypadá zenštile a slabì. Nedám ti za nìho víc jak 200 babek.}
{372}{}{Ne. Ten domorodec zapáchá a vypadá, e je... tìko zvládnutelnı. Bude tìké ho nauèit móresùm. 100 babek.}
{373}{}{Ten mu je starı. Dám ti za nìho 100 babek.}
{375}{}{Ne. 500 babek.}
{377}{}{Seòore Mordino, prosím... vy mì chcete oebraèit. Tohle je prvotøídní zboí, urèitì má vìtší cenu ne nabízíte.}

# 15. SLAVE DEALINGS 2, BARTER SUCCEED (13)
{390}{}{(Mordino se prošel kolem Mirie, poøádnì si prohlédl její tváø, potom jí plácnul po zadku.) Hmmmm. Dám ti za ní 500 babek.}
{391}{}{(Mordino se prošel kolem Davina, vyhrnul chlapci rukáv a prohlédl si jeho svaly, podíval se do jeho oèí, aby zjistil jestli není pod vlivem nìjakıch drog.) Hmmmm. Vypadá dobøe. Dám ti za nìho 400 babek.}
{392}{}{(Mordino se prošel kolem Sulika, zamraèil se.) Hmmmm. Vypadá silnì... a kdy vidím tu jeho kost v nose soudím, e asi dobøe snáší bolest. Dám ti za nìj 200 babek.}
{393}{}{(Mordino se prošel kolem Vice, zamraèil se.) Hmmmmm. Dám ti za nìho 200 babek. Víc ne.}
{394}{}{(Mordino se prošel kolem Cassidyho, zamraèil se.) Hmmmmm. Dám ti za nìho 200 babek. Víc ne.}
{395}{}{(Mordino si chvíli prohlíel robota.) Nabízím tisíc babek.}
{396}{}{(Mordino si chvíli prohlíel robopsa.) Nabízím tisíc babek.}

# 16. SLAVE DEALINGS 2, BARTER SUCCEED (13, 14, 15)
{410}{}{(Mordino si odvedl Miriu pryè a mezitím napoèítal peníze.) Tady.}
{411}{}{(Mordino si odvedl Davina pryè a mezitím napoèítal peníze.) Tady.}
{412}{}{(Mordino si odvedl Sulika pryè a mezitím napoèítal peníze.) Tady.}
{413}{}{(Mordino si odvedl Vice pryè a mezitím napoèítal peníze.) Tady.}
{414}{}{(Mordino si odvedl Cassidyho pryè a mezitím napoèítal peníze.) Tady.}
{415}{}{(Mordino si odvedl robota pryè a mezitím napoèítal peníze.) Tady.}
{416}{}{(Mordino si odvedl robopsa pryè a mezitím napoèítal peníze.) Tady.}
{417}{}{Nechcete se ještì podívat co nabízím?}
{418}{}{Dìkuji, seòore Mordino. Kdy u jsme u toho, rád bych se vás zeptal na nìjaké otázky...}
{419}{}{Dìkuji, seòore Mordino. Doufám, e vám budou otroci dobøe slouit. Nashledanou.}

# 17. SLAVE DEALINGS 2, PUSH TOO FAR (14, 15)
{430}{}{(Kapka potu stekla Mordinovi po tváøi a zachmuøil se.) Ty svinì, zkurvysynu jeden. Od takovıch lidí, jako si ty,
 nic nekupuju. Odejdi... a u se NEVRACEJ.}
{431}{}{Seòore Mordino, prosím... uvate znovu...}
{432}{}{(Tiše odejít.)}

# 18. I'M LOOKING FOR WORK [AGREE] (8, 7, 12)
{440}{}{(Mordino si tì prohlíí.) Dobrá. Mám... pro tebe práci. Take... (Hluboce se sípavì nadechl, kapka potu mu stekla po tváøi.)
 ...tenhle balík... dones do *stájí* severnì od Rena. Dej jo ho mui jménem... Ramirez a pak se vra.}
{441}{}{Ok. To bude hraèka.}
{442}{}{Hned se vydám na cestu, seòore Mordino.}
{443}{}{Co je v tom balíèku?}
{444}{}{Uh, zmìnil jsem názor. Myslím, e konèím.}

# 19. WHAT'S IN THE PACKAGE? (18)
{450}{}{Já tì... neplatím za to... abys kladl otázky.}
{451}{}{No, rád bych vìdìl co ponesu, kdybych to náhodou upustil... Je to nebezpeèné?}
{452}{}{Pak teda nevadí. Odcházím.}

# 20. I'LL DO THE DROP (18, 19)
{460}{}{Bì nahoru na sever po Ulici panen, kolem kasina... sleduj pìšinu, která vede z mìsta. Na konci pìšiny... dojdeš
 k stájím. Teï bì.}
{461}{}{(Postupuješ podle jeho instrukcí...)}

# 21. HAVE YOU DONE AS I ASKED (WTG)
{470}{}{Udìlal si... všechno jak jsem tì ádal?}
{471}{}{Ne, ještì jsem ten balíèek nedoruèil.}
{472}{}{Ano, doruèil jsem to Ramirezovi, pøesnì jak jste chtìl.}
{473}{}{Ano, byl jsem ve stájích a odevzdal jsem balíèek... víte co tam DÌLAJÍ? Oni tam pouívají otroky jako pokusné 
 králíky.}
{474}{}{Ano, dal jsem balíèek hlídaèi Ramirezovi... víte, e ten chlápek je závislák na Jetu? INHALOVAL vıpary z jetu.}

# 22. HAVE YOU DONE AS I ASKED (21)
{480}{}{Pak... proè jsi tady? (Velkı Jeíš si utøel èelo a zhluboka se sípavì nadıchl.) PROÈ jsi ještì nedoruèil ten balík?}
{481}{}{Dobrá, ale nejdøív bych se vás rád zeptal na pár otázek...}
{482}{}{Jdu to hned zaøídit.}
{483}{}{Uh, co ty víš? Myslím, e se na to hned vrhnu...}

# 23. HAVE YOU DONE AS I ASKED - YES (21, 24, 51, 52)
{490}{}{(Pøikıvnul.) Velmi dobøe. Tady je... tvoje vıplata. Sto... babek. Za... pouhé doruèení... je to 
 a moc.}
{491}{}{Je to lepší ne nic.}
{492}{}{Dìkuji, seòore Mordino.}

# 24. I'VE BEEN TO THE STABLES (21)
{500}{}{(Rozzlobenì pøimhouøil oèi. Krùpìj potu mu stekla dolù po tváøi.) Oni jsou... dobytek. Nic víc.}
{501}{}{Ty zrùdo... právì sis podepsal rozsudek smrti.}
{502}{}{Uh... chtìl jsem zkontrolovat, jak je to s mou vıplatou...}

# 25. NO MORE WORK (23, 31, 41)
{510}{}{Nemám pro tebe více... práce. (Kıvnul na dveøe.) Teï chci bıt sám. Odejdi... a NEVRACEJ se.}
{511}{}{Ah, no tak. Urèitì je NÌJAKÁ práce, která by se pro mì hodila...}
{512}{}{Ok.}

# 26. MISSION 2 (23)
{520}{}{Mám... pro tebe další práci. Potøebuju nìkoho... (Hluboce se sípavì nadıchl a kapka potu mu stekla z èela.) ... aby vybral
 mùj podíl od... Korsickıch bratrù. Trochu se OPOZDILI s platbou.}
{523}{}{Myslím, e konèím. Díky nìkdy pøíštì.}

# 27. MISSION 2, AGREE (X)
{530}{}{Bì na sever po Ulici panen. Jsou naproti tìlocviènì... pokud budou dìlat problémy... pokud budou mít vımluvy... tak jim uka, co je to BOLEST.}
{531}{}{OK. Jdu do toho.}
{532}{}{Jistì, seòore Mordino.}

# 28. CORSICAN BROS DEAD (WTG)
{540}{}{Øekl jsem, e... mùeš Korsické bratry postrašit a ukázat jim, co je to BOLEST. Nedal jsem ti povolení k tomu,... abys je ZABIL.}
{541}{}{Hej, podívejte... oni si zaèali a já jsem se pouze bránil...}
{542}{}{Øíkali špatné vìci o vaší matce, seòore Mordino. Pøece jsem to tak nemohl nechat, tak jsem je ZABIL.}
{543}{}{Och. Asi jsem se pøeslechl.}

# 29. HAVE YOU DONE AS I ASKED (WTG)
{551}{}{Uf... ano, ale nemám ty peníze u sebe. Dejte mi ještì trochu èasu a já je donesu.}
{552}{}{Ano, tady jsou ty peníze.}
{553}{}{Ne, ještì ne.}
{554}{}{Ne, uf, ale u jdu na to.}

# 30. HAVE YOU DONE AS I ASKED (29)
{560}{}{Tak... proè jsi tady? (Utøel si èelo a pak se zhluboka sípavì nadechl.) PROÈ nemáš ty prachy?}
{561}{}{Hned to bude, ale nejdøív bych se chtìl zeptat na pár vìcí...}
{562}{}{Dobrá otázka. Hned to jdu zaøídit.}

# 31. HAVE YOU DONE AS I ASKED - YES (29)
{570}{}{(Kdy mu dáváš peníze tak hlavou pøikyvuje.) Tady. Polovina... ta je tvoje. Heh. Oni u mi tento mìsíc zaplatili, ale
 chci, aby vìdìli... kdo je tady pánem.}
{571}{}{Hej, díky, Velkı Jeíši.}

# 32. I'M LOOKING FOR WORK [AGREE] (31)
{580}{}{(Seòor Mordino se na tebe dlouze podíval, pak jemnì kıvnul.) Mám pro tebe poslední prácièku. Je zde... (Hluboce
 a sípavì se nadıchl, utøel si pot z èela.)... MU, kterı musí zemøít.}
{581}{}{Ten mu je u teï mrtvı. Jak se ta mrtvola jmenuje?}
{582}{}{Kdo je ten mu?}
{583}{}{Kdo je ten mu, kterého mám zabít, pane Mordino?}
{584}{}{Sakra, nikdo mì pøedem neinformoval, e se bude i vradit. Zapomeòte na to.}
{585}{}{Tak tuhle práci nemohu vzít seòore Mordino, promiòte. Nashledanou.}

# 33. REFUSE JOB (18, 19, 26, 32, 35, 36, 52)
{595}{}{Pøišel si za mnou pro práci. Já jsem ti dal... práci a ty naøíkáš jako male DÌCKO. (Zhluboka a s obtíemi se nadıchl a hned zaèal kašlat.)
 Ty... u tady nejsi vítanı... v mém kasínu. Odejdi.}
{596}{}{Pøišel si za mnou pro práci. Odmítáš mou... nabídku. (Zhluboka a s obtíemi se nadıchl a hned zaèal kašlat.)
 Ty... u tady nejsi vítanı... v mém kasínu. Odejdi.}
{597}{}{Ne odejdu, mìl bych nìjaké otázky na které bych se vás rád zeptal...}
{598}{}{Nechci u s váma mluvit "Velkı Jeíši."}
{599}{}{Má omluva, seòore Mordino. Hned odcházím.}
{600}{}{Proè chcete abych odešel?}

# 34. THE CORPSE GOT A NAME? (32)
{610}{}{Tenhle mu, Louis Salvatore... zabil mnoho mıch muù... mnoho HRDİCH muù Mordinovy rodiny. On... zmasakroval je
 na ulici jako... prašivé psy. (Ruku sevøel v pìst.) Moje pøání je, aby byl ten mu mrtvı.}
{611}{}{Jestli dobøe zaplatíte tak ten mu je u mrtev.}
{612}{}{Poèkejte chvíli. Louis Salvatore, ten kterı ovládá Salvatorovic rodinu? Ten kterı má tu zbraò, která
 umí èlovìka rozpùlit?}
{613}{}{Pomstím se za Mordinovic rodinu, seòore Mordino. Vrátím se hned jak ten úkol splním.}
{614}{}{Tenhle úkol nemùu pøijmout. Odcházím.}
{615}{}{Dobrá tedy. Udìlám to.}

# 35. THE CORPSE GOT A NAME 2? (X)
{620}{}{Rád ti zaplatím, ale a... Salvatore nebude dıchat.}
{621}{}{Poèkejte chvíli. Louis Salvatore, ten, kterı ovládá Salvatorovic rodinu? Ten kterı má zbraò, která
 umí èlovìka rozpùlit?}
{1621}{}{No... dobrá tedy. Udìlám to.}
{623}{}{Nebudu riskovat svùj krk pro nic. Odcházím.}

# 36. WHOA. SALVATORES? (34, 35)
{630}{}{(Mordino pøikyvuje, sleduje tvùj vıraz.) Máš obavy... nebo snad strach? Jestli ano, tak odejdi. (Ukazuje na dveøe.) V Mordinovic rodinì
 není místo pro zbabìlce.}
{631}{}{Ne, udìlám to.}
{633}{}{Øíkej mi tøeba zbabìlec, ale já chci na tomhle svìtì ještì chvíli zùstat. Tuhle práci vzdávám.}

# 37. I'LL DO IT (34, 35, 36)
{640}{}{(Pøikyvuje.) To je dobøe. Ten mu je starı... mrzák... schovává se ve svém baru, "Salvatore's," vedle Bishopova kasína.
 Je to... zbabìlec a nikdy nevychází ze svého pokoje. A bude mrtvı... tak se vra.}
{641}{}{Mrzák?}
{642}{}{Dobrá.}

# 38. CRIPPLE? (37)
{650}{}{(Pøikyvuje.) Jeho nohy... jsou slabé. (Jeíš si utøel èelo a poté se opìt zhluboka nadıchl.)
 Taky má... potíe s... dıcháním. Dıchá jenom pomocí... kyslíkové bomby.}
{651}{}{Kyslíková bomba, huh? Hmmmm. Dobrá.}
{652}{}{A ho zabiju, tak se vrátím, seòore Mordino.}

# 39. KILL SALVATORES (WTG)
{660}{}{Louis Salvatore ije. Tak proè ses vrátil?}
{661}{}{(Kapka potu stekla Mordinovi dolù po tváøi.) Splnil si úkol co jsem ti zadal? Je Louis Salvatore mrtev?}
{662}{}{Je mrtev. Tvá rodina je pomstìna, seòore Mordino.}
{663}{}{Ne, musím se vrátit a zabít ho.}
{664}{}{Salvatore je velmi dobøe hlídán. Chci odstoupit od naší úmluvy.}

# 40. TRY AND QUIT SALVATORE JOB (39)
{670}{}{Jestli... uteèeš od tohodle úkolu budu tì muset... ZABÍT.}
{671}{}{Jestli to myslíš takhle, tak to se radìji vrátím a bude Salvatore mrtvı.}
{672}{}{Jestli nìco zkusíš, tak si budeš moci promluvit se svımi mui, které zmasakroval Salvatore.}

# 41. SALVATORE JOB, SUCCEED (39)
{680}{}{No slyšel jsem. (Pøikyvuje s respektem.) Ty si to dokázal... take. Moje dùvìra v tebe nebyla pošetilá. Tady je... tvá
 vıplata. Pìt set... babek. }
{681}{}{Díky.}
{682}{}{To pro teï... vše.}
{683}{}{A... zbroj a zbraò se ti mohou... hodit.}

# 42. YOU HAVE DONE AS I ASKED. . . (41)
{690}{}{(Pøikyvuje.) Tvùj úspìch... mì potìšil. Chtìl bych tì pøivítat do rodiny Mordinù. (Obejmul tvá ramena.) Staneš
 se èlenem naší rodiny? Tvá síla bude... naší silou.}
{691}{}{Bude mi potìšením stát se èlenem rodiny Mordinù.}
{692}{}{Nemohu se stát èlenem rodiny. Ale nezlobte se seòore Mordino: bylo mi potìšením pro vás pracovat.}
{693}{}{Nechci se stát èlenem rodiny, díky. Musím teï nejdøíve zachránit svou vesnici.}

# 43. YOU HAVE DONE AS I ASKED. . . (42)
{700}{}{(Pøikyvuje.) Je mi líto, ale je to tvá volba. Jak jsem øekl, tvùj úspìch mì potìšil,... ale nechci aby tvé schopnosti
 vyuíval nìkdo jinı, jako tøeba... mí nepøátelé. (Dal svım muùm pokyn a oni hned vytasili zbranì.)}

# 44. YOU HAVE DONE AS I ASKED. . . (42)
{710}{}{To je dobøe. Máš nìjaké... jméno kterım bychom tì pojmenovali? Všichni Mordinové... celé Reno... bude znát tohle jméno.}
{711}{}{Jasnì, co takhle...}

# 45. CALL ME. . . (44)
{720}{}{... to je dobré jméno. (Pøikyvuje.) Mordinovic jméno má... svou váhu v New Reno. Navštiv... Koèièí Packu... New Reno Arms... a
 øekni jim, e patøíš do rodiny... budou s tebou zacházet jako v rukavièkách.}

# 46. WHAT ABOUT RICHARD? (7, 11)
{730}{}{(Dlouho se na tebe upøenì díval a pak zmatenì pøimhouøil oèi.) Proè... se mì ptáš na tohle? SLYŠEL jsem... co se stalo. (Otøel
 si èelo.) Ten chlapec si vzal moc Jetu a zemøel.}
{731}{}{To je ten problém. Mordionovi jsou nejvìtším dodavatelem Jetu v New Reno. To vás dìlá jednìmi z podezøelıch.}
{732}{}{Nevíte náhodou kde získal Jet?}
{733}{}{Dobrá. Jenom se ptám. Mám další otázky...}
{734}{}{Jasnì. Myslím, e radìji pùjdu.}

# 47. YOU'RE GONNA TAKE THE BLAME (46)
{740}{}{(Sípá a pak si utøe trochu více potu z èela.) Jestli má Wrighte... zdravı rozum, stejnı s jakım se narodil, tak musí... vìdìt, e
 nejsme jediná rodina, která vlastní Jet, v New Reno. Já... NEZABÍJÍM dìti.}
{741}{}{Pouze dospìlé, huh? Myslím, e Jet nezabije èlovìka hned, potøebuje trochu èasu, ale funguje, nemám pravdu?}
{742}{}{Kdokoli jinı mohl a moná chtìl oèernit jméno Mordino. Nevíte, kdo mohl Richardovi prodat tolik Jetu, kterı ho zabil?}
{743}{}{Jasnì. Podívejte, mìl bych ještì pár dalších otázek...}
{744}{}{Díky za informace, seòore Mordino. U musím jít.}

# 48. YOU KNOW WHO MIGHT HAVE SOLD IT TO HIM? (46, 47)
{750}{}{(Zatøepal hlavou.) Já... vím málo o ivotì chlapù v Renu. (Zhluboka a sípavì se nadıchl, lehce zakašlal.) Ty... mùeš se zeptat mého syna... najdeš ho dole v kasínu.}
{751}{}{Zeptám se. Mám ještì další otázky...}
{752}{}{Zeptám se. Dìkuji seòore Mordino.}

# 49. I HAVE A HEART CONDITION . . . (7, 11)
{760}{}{Teplota... mám s ní èasto problémy. Moje dıchání je... nìkdy obtíné. Kdy se nervuji nebo pøi psychické námaze
 se rychle unavím. Nìkdy mám strašné bolesti na prsou.}
{761}{}{Opravdu. Take, bude pro vás nejlepší, kdy pøestanete brát jakékoli metaamfetaminy nebo stimulanty. Mìl bych ještì nìjakou otázku...}
{762}{}{Jasnì. No radìji u pùjdu.}

# 50. I HAVE A HEART CONDITION . . . (7)
{770}{}{Neznám tì... pøišel jsi ke mnì... bez jakékoli nabídky, která by mìla nìjakou... váhu. (Utøel si èelo a pak se zhluboka 
 a sípavì nadıchl.) NEMÁM PRO TEBE PRÁCI.}
{771}{}{No tak, dejte mi šanci. Dejte mi jakoukoli práci... udìlám všechno.}

# 51. RAMIREZ IS A JET HEAD (24)
{780}{}{Ne všichni ve stájích... VÌDÍ, e jsou testovací objekty.}
{781}{}{Uh... nìjak mi to nedochází.}
{782}{}{Oh. Uh, ohlednì mé vıplaty...}

# 52. COME AGAIN? (51)
{790}{}{Ramirez zaèal... minulı mìsíc utekli ètyøi otroci. (Zaèal tøást pomalu hlavou.) To není dobré. (Bìhem 
 hodiny zaèal pùsobit ten Jet, co jsi dal Ramirezovi, jeho srdce... pøestalo bít.) Tohle je TREST.}
{792}{}{Vyuil jsi mì k ZABITÍ toho chlapa? Tak to je Jeíši, radši vypadnu.}

{850}{}{Vybral jsi poplatek pro Velkého Jeíše.}
{875}{}{Zavradil jsi Velkého Jeíše.}
{900}{}{Stal ses èlenem rodiny Mordinù.}
{925}{}{Dokonèil jsi kontrakt pro Velkého Jeíše.}

# END LINES
{5268}{}{?!! Tak POJÏ, TY TLUSTİ ZKURVYSY--}