# Tento soubor pøeloil Radim "HIGHTOWER" Brix , hightower@angelfire.com
# QUICK LOOK
{100}{}{Vidíš pana Bishopa.}

# EXAMINES
{150}{}{Vidíš vlivnì vypadajícího mue ve støedních letech.}
{151}{}{Vidíš pana Bishopa. Vypadá pochmurnì.}

# 1. CLICK: MADE MAN, ANY OTHER FAMILY (2, 3, 4, 9, 11, 13, 14, 16, 17, 18, 22, 24, 25, 26, 27, 28, 29, 31, 33, 35, 36, 37, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 51, 57, 59, 62, 63)
{200}{}{Ztratil jsi nìco, kdy jsi tady pøišel. }
{201}{}{Ztratil jsi nìco. }
{202}{}{Proè sis rovnou nepøipíchl na hruï nápis, 'debilní zkurvysyn?'}
{203}{}{Co chceš }
{204}{}{ bastarde.}
{205}{}{Co chceš, ty stupidní zkurvysynu.}
{206}{}{Co chceš, dìvko.}
{207}{}{Nemám rád nevychované a tupé lidi}
{208}{}{Vypadni}
{209}{}{Jestli je tohle to, co chceš mít napsané na náhrobku, tak budi...}
{210}{}{Špatná volba posledních slov.}
{211}{}{(Utíkat.)}

# 2. MAIN DIALOGUE: NORMAL (WTG)
{220}{}{Co to--? Kdo jsi a co tady SAKRA chceš?}
{221}{}{Já }
{222}{}{.}
{223}{}{Já Kdoo?}
{224}{}{Asi jsem se zatoulal}
{225}{}{Jsem váleèník na posvátné cestì za získáním GECKu. Nevíte, kde bych ho mohl najít?}
{226}{}{Hledám GECK. Mùete mi pomoci?}
{227}{}{Hledám místo s názvem Vault 13. Neslyšel jste nìkdy o nìm?}
{228}{}{Myslel jsem, jestli byste pro mì nemìl nìjakou práci.}
{229}{}{Promiòte -- špatná místnost.}

# 3. BOYS SAID YOU GOT A BRIEFCASE FOR ME (WTG)
{240}{}{(Prohlíí si tì.) Pod tím vším vypadáš jako jeden z tìch domorodcù... (Zasupí.) Chlapci mi øekli, e máš pro mì kuføík s dokumenty, od našeho spoleèného "známého." Tak uka, podívám se na nì.}
{241}{}{Tady.}
{242}{}{Eh...to je legrace, to...vypadá jako by nìkdo zpoza dveøí zde, asi jsem zabloudil.}
{243}{}{Vlastnì právì to jsem chtìl zaøídit. Za chvíli je donesu.}

# 4. HERE YOU GO. . . (3)
{250}{}{(Otevøe kuføík, zkontroluje obsah, rychle ho zavøe.) Je to od Moora, v poøádku. Vèetnì tohoto dopisu, ve kterém píše, e se ti nedá vìøit. Vešel jsi do ŠPATNÉ místnosti domorodèe.}
{251}{}{(Otevøe kuføík, zkontroluje obsah, rychle ho zavøe.) Je to od Moora, v poøádku. Øíká, e si tì provìøil, domorodèe. Máš štìstí...(Usmívá se.)...pøišel jsi tady se špatnou reputací a hned bys chtìl to nejlepší.}
{252}{}{Moná, ale budu jedinı kdo odtud odejde.}
{253}{}{Dobøe, doruèil jsem vám kuføík pøesnì jak mì poádal Moore... teï si promluvme o odmìnì... .}
{254}{}{Co je v tom kuføíku? Jsem zvìdavı.}
{255}{}{Vypadá to, e je vše v poøádku... podívejte, musím u jít.}

# 5. HERE YOU GO. . . (4)
{265}{}{Zkro své konì domorodèe... ještì jsme se nedohodli na odmìnì. }
{266}{}{Zkro své konì domorodèe... mám na tebe ještì nìjaké otázky. }
{267}{}{(Prohlíí si tì.) Take...odkud znáš Moora? Snaí se teï dìlat politiku tìm primitivùm? Ha! Ten chlap se minul povoláním.}
{268}{}{Potkal jsem ho ve Vault City, vysvìtluješ. Nabídl jsem se mu, e vám doruèím ten kuføík.}
{269}{}{Narazil jsem na nìho pøi mıch cestách. Nabídl jsem se mu, e vám doruèím ten kuføík.}

# 6. HERE YOU GO. . . (5)
{275}{}{Heh... zatracená práce... pro samá veøejná kázání si starı lišák Moore neumí sám nic vyøídit. Heh... stále se vùbec neliší od tìch chlápkù z NCR.}
{276}{}{Poøád dìlá veøejná kázání. Stále si myslí, e to má smysl.}
{277}{}{Je velmi vıøeènı ve svıch veøejnıch kázáních.}
{278}{}{Jasnì, ano, v jistém smyslu mìla bıt ta práce udìlána a on mi øekl, a dohlédnu na to, aby se ten kuføík dostal k vám.}

# 7. HERE YOU GO. . . (6)
{285}{}{(Pro sebe.) Samozøejmì, bıt schopnı pøivést dav lidí do varu a k šílenství nemusí bıt špatné, obzvláš pokud chce èlovìk dìlat politiku...
 (Podezøívavì si tì prohlíí.) Ty nejsi taky jeden z NCR, nebo ano? Tomcat je jedinı koho momentálnì strpím.}
{286}{}{Ano, jsem taky z NCR. Není to zrovna nejlepší, ale takovı je ivot. Jsem vlastnì takovı volnı agent.}
{287}{}{Ne, jsem pouze cestovatel. Souhlasil jsem, e pomùu Moorovi pouze proto, e jsem potøeboval práci.}

# 8. HERE YOU GO. . . (7)
{295}{}{(Kıvne na aktovku.) No, tahle aktovka za to stála. Je tam nìco málo o Vault City, nìjaké ty drahé technické vıkresy,
 se kterımi se ta frigidní dìvka Lynette nechce s nikım podìlit...ale hej domorodèe, ještì jsem ti vlastnì nezaplatil. Tady je tvá odmìna.}
{296}{}{Jak to øíct...zrovna teï nemám nic dalšího na práci. Nemìl byste pro mì nìjakou práci?}
{297}{}{Super...díky. Podívejte já u musím jít.}

# 9. I'VE GOT TO GO . . . NO JOBS (8, 34, 49)
{305}{}{Ne...nemám pro tebe u ádnou další práci...ale díky za všechno. }
{306}{}{Ne...nic pro tebe nemám. Trocha úmrtí, dole v NCR, v poslední dobì udìlala mùj ivot trochu snadnìjší...ale hej, díky
 za to doruèení. }
{307}{}{(Hlavou kıve na vıchod.) Teï u odsaï odejdi. Mám taky dùleitìjší vìci na práci.}
{308}{}{Doruèil jsem vám tu blbou aktovku a z Vault City a vy mì takhle odmítáte? Myslím, e
 si vezmu zbytek odmìny pøímo od vás.}
{309}{}{Ne, nemyslím, e právì teï odejdu. Stále jsi ještì neskonèil se mnou...ty svinì.}
{310}{}{Dobrá tedy. Odcházím.}

# 10. I'VE GOT TO GO . . . JOB OFFER (8)
{315}{}{Poèkej chvíli, domorodèe...(Pousmál se, poklepal na kuføík.) Starı Tomcat Moore øíkal, e jsi tımovı hráè. Takové lidi já potøebuju. Mìl bych pro tebe práci jestli máš zájem.}
{316}{}{Poslouchám.}
{317}{}{Ne, radìji vyrazím.}

# 11. MISSION ONE (8, 10, 33, 59, 63)
{325}{}{(Chvíli si tì kontroluje a pak pøikıvne.) Ano...mám pro tebe práci. }
{326}{}{Mám takovı..."problém" dole na jihu v NCR. Jde o to, e jeden chlápek, Westin, mluví a moc. Chci, aby u nikdy nepromluvil...u nikdy.
 Lehká práce, lehce vydìlané peníze.}
{327}{}{ádnı problém. Ten Westin je u teï mrtvı.}
{328}{}{Nemám zájem. Na tuhle práci si najdìte nìkoho jiného.}

# 12. WESTIN: (11)
{335}{}{Poèkej. Ještì jsem ti NEØEKL vše. Chci, aby ten chlápek byl mrtvı, ale je tady podmínka. Nesmí to vypadat jako VRADA. Ne abys mu prohnal kulku lebkou, ne abys ho zapíchnul, neudìlej nic co by mohlo JAKKOLI
 vypadat jako vrada.}
{336}{}{Co? Jak  --}
{337}{}{Tak to bude stát extr --}
{338}{}{Protoe...?}

# 13. WESTIN: (12)
{345}{}{Protoe jedinì tak to jde udìlat. A tì ani nenapadne aby se tam dole nìkdo dovìdìl, e mám s tou vradou toho zkurvysyna COKOLI spoleèného,
 jinak ti pøísahám, e u nikdo nebude moci identifikovat tvoji mrtvolu.}
{346}{}{Do prdele jak mám nìkoho zabít tak, aby to nevypadalo jako vrada?}
{347}{}{Zapomeòte na to... tohle není mùj styl. Budete si muset najít nìkoho jiného. Odcházím.}

# 14. HOW THE HELL AM I SUPPOSED . . . (13, 17, 18, 19, 23, 24, 25, 26, 27, 28, 29)
{355}{}{To je tvùj problém synu, ne mùj. Udìlej tøeba mumbo-jumbo, namíchej mu nìjakı jed do drinku, udus ho ve spánku, a na nìho tøeba spadne barák, je mi to jedno. Pouze si dej pozor na to, aby to nevypadalo jako vrada.}
{356}{}{Dobrá... take ještì jednou a si v tom udìlám jasno: má to vypadat jako nehoda, jinak to bude se mnou špatné.}
{357}{}{Jasnì. Vrátím se, a se Westinovi stane nìjaká... "nehoda."}
{358}{}{Rozumím. Vrátím se, a se Westinovi stane jeho malá... "nehoda."}
{359}{}{Jestli nechcete, abych mu prohnal kulku hlavou, tak to bude tøeba trochu zvıšit odmìnu.}
{360}{}{Take vy po mì chcete, aby to vypadalo jako nehoda, eh? V takovém pøípadì budu potøebovat více informací o tom 'Westinovi.'}
{361}{}{Nejsem ta pravá osoba pro tuhle práci. Zapomeòte na to.}

# 15. DONE. I'LL BE BACK . . . (14)
{370}{}{Dobrá tedy. Oèekávám tì tady co nejdøíve. A zapamatuj si domorodèe, neznáš mì a nikdy jsme nevedli tento rozhovor. Prozradíš-li jenom jediné slovo, tak tì zabiju.}
{371}{}{Nedìlejte si o MÌ starosti pane Bishope. Ty peníze èekají pouze na mnì.}
{372}{}{ádnı problém. Já se vrátím.}

# 16. WELL, IF YOU DON'T WANT ME TO PUT A BULLET . . . (14)
{380}{}{Platím ti více ne dost, více ne je cena TVÉHO ivota domorodèe. Tak na mì nenaléhej.}
{381}{}{Tisíc nebo nic. Tohle je speciální práce a proto budu mít speciální vydání. Musím nìjak dorazit do NCR, naaranovat 'nehodu',
 a nejvìtší èást penìz spotøebuji na speciální vìci, které budu potøebovat k té 'nehodì'. Take vy na MÌ nenaléhejte, jasné?}
{382}{}{Dejte rovnou tisíc a našel jste svého mue.}
{383}{}{750 babek by mìlo vše pokrıt.}
{384}{}{500 babek. Westin je mrtvola.}
{385}{}{Tak na to zapomeòte. Najdìte si nìkoho jiného. Já odcházím.}

# 17. NEGOTIATED UP, BAD DEAL (16)
{390}{}{CO chceš? Domorodèe, mìl by si bıt šastnı, e dostaneš tolik kolik dostaneš.}
{391}{}{Podívejte, naposledy vám øíkám: bude vás to stát více ne 500 babek.}
{393}{}{Tak na to zapomeòte. Najdìte si nìkoho jiného. Já odcházím.}

# 18. NEGOTIATED UP, DONE (16)
{400}{}{Dobrá tedy!  Radìji to proveï poøádnì, domorodèe. Jestli ne, nebo jestli se KDOKOLI doví o naší dohodì tak ti pøísahám, e vezmu ten nejostøejší nù a za
 kadé slovíèko, co vykecáš, ti udìlám na tìle jeden záøez.}
{401}{}{ádnı problém. Westin je u teï mrtvı mu.}
{402}{}{Tak takhle? No tak to si najdìte nìkoho jiného, aby vám vyøešil ten problém. Já odcházím.}

# 22. YOU WANT ME TO MAKE IT LOOK LIKE AN ACCIDENT, THEN I'LL NEED TO KNOW MORE . . . (14, 23-29)
{410}{}{Hmmmm. Dobrá, to je fér nabídka...co potøebuješ vìdìt?}
{411}{}{Jako...?}
{412}{}{Kde NAJDU toho chlapa? A dorazím do NCR, tak ho tam nechci hledat jako nìjakou zatoulanou slepici.}
{413}{}{Má ten chlápek nìjaké pøíbuzné, nìjakou rodinu? Nìjací svìdci o kterıch bych mìl vìdìt?}
{414}{}{Jak je na tom ten chlápek se zdravím? Nìjaké nemoci?}
{416}{}{Co ten Westin vlastnì DÌLÁ? Jakı má pracovní rozvrh?}
{417}{}{Nechci tuhle práci. Najdìte si nìkoho jiného.}

# 23. YOU WANT ME TO MAKE IT LOOK LIKE AN ACCIDENT, THEN I'LL NEED TO KNOW MORE . . . (22)
{425}{}{Má ranè v NCR. Pokud pùjdeš za smradem z brahmín, tak ten ranè nemùeš minout.}
{426}{}{Mìl bych ještì nìjaké otázky ohlednì Westina...}
{428}{}{Èím víc o nìm vím, tím míò se mi to líbí. Zapomeòte na to.}

# 24. ANY KIN, ANY FAMILY . . . (22)
{435}{}{ádné dìti, ádná ena, ádná rodina, nikdo o koho by ses mìl zajímat. Moná tam budou nìjací pomocníci na ranèi, ale ti by nemìli bıt velkı problém.}
{437}{}{Poèkejte chvíli... "pomocníci na ranèi?" Jsou OZBROJENI? A KOLIK jich vlastnì je?}
{438}{}{Dobrá, tohle mi staèí. U vím všechno, co potøebuju. Westin je u mrtvı mu.}

# 25. ANY KIN, ANY FAMILY . . . (22, 24)
{445}{}{Pravdìpodobnì ozbrojeni... nevím kolik jich je pøesnì, já jsem je nepoèítal. Vím, e má najaté nìjaké dìlníky a s nejvìtší pravdìpodobností jich bude více ne jenom jeden nebo dva.
 Jak to s nimi udìláš je èistì tvùj problém domorodèe.}
{446}{}{Vıbornì tohle byla uiteèná rada. Mìl bych ještì další otázky ohlednì Westina...}
{447}{}{Dobrá, tohle mi staèí. U vím všechno, co potøebuju. Westin je mrtvı mu.}

# 26. ANY KIN, ANY FAMILY . . . (22)
{455}{}{No... øíká se, e ven moc nevychází. Myslím, e jsem slyšel nìco o tom, e má srdeèní problémy, take se moc nenamáhá. (Odfrkne.) Také jsem slyšel, e nemá rád slunce.}
{456}{}{Hmmmm. Mìl bych ještì další otázky ohlednì Westina...}
{457}{}{Srdeèní problémy, huh? Má nìjakého doktora? Uívá na to srdce nìjaké léky?}

# 27. TAKE ANY MEDICATION . . . (26)
{465}{}{(Usmìje se.) Líbí se mi jak uvauješ, domorodèe... dobrá, nevím jestli bere na to srdce nìjaké prášky, ale vím, e si sakra dává pozor na to s kım o svıch srdeèních problémech mluví.}

# 28. WHAT DOES HE DO? . . . (22)
{475}{}{(Zamraèí se.) Je to chovatel brahmín. Pasák zvíøat. Take?}
{476}{}{Dobrá. Mìl bych ještì další otázky ohlednì Westina...}
{477}{}{Ne, on je urèitì nìco VÍCE. Jinak bychom tento rozhovor nevedli.}

# 29. WHAT DOES HE DO? . . . (WTG)
{485}{}{(Upøenì se na tebe podíval.) Je také poradcem v kongresu NCR. VYSTRAŠILO tì to domorodèe? Nemìlo by. Udìlej svou práci a
 nemusíš se nièeho bát. Pokud se na to teï vysereš, tak to, e je Westin poradcem, bude a ta poslední co tì bude trápit.}
{488}{}{"Poradce v kongresu NCR?" No tak to si najdìte nìkoho jiného...nìkoho se sebevraednımi úmysly.}

# 30. NO WAY, BISHOP. I'M OUTTA HERE . . . (10, 11, 13, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 33, 34, 35, 36, 37, 38, 39, 40, 42, 43, 44, 45, 46, 47, 48)
{495}{}{Dobrá tedy. Teï nemusíš bıt hrdina...vdycky mám práci pro nìkoho kdo umí ukázat vısledky.}
{496}{}{Budu to mít na mysli. Nashledanou.}

# 31. YOU DONE THE HIT YET? . . . (WTG)
{500}{}{U si se postaral o Westina?}
{501}{}{Radìji bys pro mì mìl mít nìjaké dobré zprávy. Je Westin mrtvı nebo ne?}
{502}{}{Domorodèe u mi dochází trpìlivost. UDÌLAL jsi tu zatracenou práci nebo ne?}
{503}{}{Vlastnì...taková legraèní vìc, musíte uznat, e je to a ironické...dostal jsem protinabídku. Hned vám ukáu co to je za nabídka.}
{504}{}{Westin mìl...nehodu, ano. Hrozná smùla, mu jako on zemøel tak náhle. Teï pøejdeme k odmìnì, kterou mi dluíte...}
{505}{}{Ještì ne. Mám ještì pár vìcí, které musím vyøídit.}
{507}{}{Vrátil jsem se, abych vám sdìlil, e tu práci neudìlám. Zapomeòte na to.}

# 32. FUCKED UP WESTIN (WTG)
{515}{}{Ty stupidní bastarde...}
{516}{}{Ty zasraná dìvko...}
{517}{}{to byl špatnı nápad vracet se tady zpìt po tom, co jsi to tak zkurvil v NCR. Proè sis rovnou na sebe nepøipíchnul ceduli 
 "zavradím Westina". Budeš dlouho umírat.}
{519}{}{Špatnì zvolená slova, Bishope...}

# 33. YOU RECONSIDER? (WTG)
{525}{}{Hej, domorodèe. Ta nabídka stále trvá...jestli máš zájem. Slušná odmìna. Máš zájem?}

# 34. SUCESSFULLY KILL WESTIN (31)
{536}{}{Tady je tvá odmìna.}
{537}{}{Nemáte pro mì další práci?}
{538}{}{Mezi námi jsou teï všechny vìci vyøešené? Jestli ano, tak odcházím.}
{539}{}{Dobrá. Je radost s vámi pracovat.}

# 35. I'VE GOT TO GO . . . JOB OFFER (34)
{545}{}{Zastav se chvíli, domorodèe... odvedl si dobrou práci. Mìl bych pro tebe další práci, JESTLI máš zájem.}
{547}{}{Ne, dìkuji. Nemám zájem.}

# 36. MISSION 2 (8, 10, 33, 34, 35, 59, 63)
{550}{}{(Chvíli si tì kontroluje a pak pøikıvne.) }
{551}{}{Jasnì...mìl bych pro tebe práci. }
{552}{}{Mám další..."problém" dole v NCR. Øeknu to rovnou, je tøeba vyøídit dalšího. Ten mrtvı mu se jmenuje Carlson. Ještì neví, e u je mrtev. }
{553}{}{Mám takovı malı... "problém" dole na jihu v NCR. Ten mrtvı mu se jmenuje Carlson. Ještì neví, e u je mrtev. }
{554}{}{Jestli to pro mì udìláš, tak si pøijdeš na 500 babek.}
{555}{}{ádnı problém. Tenhle Carlson je u nyní mrtev.}
{556}{}{DALŠÍ vrada?}

# 37. ANOTHER FUCKING MURDER? (36)
{565}{}{ádná vrada. Vrada je ošklivé slovo. Tohle je byznys. Politika, jestli chceš. Chceš tu práci nebo ne?}

# 39. CARLSON 2: (36, 37, 40, 41, 43, 44, 45, 46, 47)
{575}{}{Ještì jedna vìc: je mi jedno jestli na Carlsona vlítneš a rozmašíruješ ho všema zbranìma, co máš. Je teï nedobytnì schovanı ve svém sídle poté,
  co to Westin koupil, take to, jak ho vyøídíš, nemusí bıt tak dokonalé, ale hlavnì to musí BİT, kapišto?}
{576}{}{Je mi jedno jestli na Carlsona vlítneš a rozmašíruješ ho všema zbranìma, co máš. Je teï nedobytnì schovanı ve svém sídle, take to, jak ho vyøídíš, nemusí bıt tak dokonalé, ale hlavnì to musí BİT, kapišto?}
{577}{}{Take ještì jednou, abych si to srovnal: nemusím brát ohled na to, JAK toho zkurvysyna vyøídím, hlavnì a je mrtvı.}
{578}{}{Rozumìl jsem. Jdu do toho.}
{579}{}{Dobøe...rozumìl jsem. Jdu do toho.}
{580}{}{Jestli to tak mám udìlat...teï si pojïme promluvit o té odmìnì.}
{581}{}{Døív ne nìco udìlám, tak potøebuju vìdìt pár informací o tom Carlsonovi.}
{582}{}{Oh, take TEÏ je v poøádku vyøídit vše zbranìma? TOHLE by mi tak bylo platné u Westina. Zapomeòte na to.}
{583}{}{Nemám zájem. Najdìte si nìkoho jiného.}

# 40. WE STILL NEED TO NEGOTIATE CARLSON PRICE. (39)
{590}{}{Co to to s tebou kurva je? ØEKL jsem cenu. Nehodlám dále o tom smlouvat. Konec pøíbìhu...kapišto?}
{591}{}{Podívejte pane Bishope. Vyøídil jsem Westin. Nebyl to zrovna jednoduché, ale UDÌLAL jsem to. Nikdo z vašich chlapù si na to ani netroufl, nebo jste radìji ani ádného neposlal
 . Chcete vidìt vısledky? Tak to mluvte se MNOU a radìji øeknìte cenu, kterou chci slyšet.}
{592}{}{1000 babek. To je vše co chci za to, e Carlson odejde na pøedèasnı odpoèinek.}
{593}{}{500 babek tedy. Carlson je mrtvı mu.}
{594}{}{Pak na to zapomeòte. Najdìte si nìkoho jiného.}

# 41. 1000 chipS OKAY . . . (40)
{600}{}{Take...tisíc babek. A u nechci slyšet další pièoviny. Další slovo, které teï vyslovíš a je "ano pane Bishope, udìlám to."}
{601}{}{Ano pane Bishope. Udìlám to.}
{602}{}{Protentokrát se spokojím s 1000 babkami.}
{603}{}{1000 babek? Vy si dìláte srandu? Zvednìte to na 1500 a pak to beru.}
{604}{}{Zapomeòte na to. Nechci mít další problémy.}
{605}{}{Zapomeòte na to. Nepotøebuji to.}

# 42. I NEED TO KNOW MORE ABOUT CARLSON . . . (39, 43, 44, 45, 46, 47)
{615}{}{(Zapøemıšlel a pak lehce pøikıvnul.) Fér nabídka...co potøebuješ vìdìt?}
{616}{}{Jako...?}
{622}{}{Co tenhle Carlson dìlá? Jakı je jeho pracovní program?}

# 43. YOU WANT ME TO MAKE IT LOOK LIKE AN ACCIDENT, THEN I'LL NEED TO KNOW MORE . . . (42)
{630}{}{Schovává se v presidentském sídle v NCR. Nejde to minout. Jak se dostat dovnitø a vyøídit všechny chlápky je u tvoje vìc.}
{631}{}{Mìl bych ještì další otázku ohlednì Carlsona...}
{632}{}{Dobrá, tohle mi staèí, abych mohl vyrazit. Carlson je mrtvı mu.}

# 44. ANY KIN, ANY FAMILY . . . (42)
{640}{}{Jeho ena je mrtvá, ale má syna, kterému je pouze sedm nebo osm let, ten s ním ije v sídle...(Pøemıšlí.)...to místo
 je oploceno a je velmi dobøe hlídáno nìkolika stráci, take si dávej dobrı pozor.}
{642}{}{Moment...KOLIK strácù?}

# 45. ANY KIN, ANY FAMILY . . . (44)
{650}{}{Není mi známo kolik pøesnì. Trochu jsme to místo obhlíeli a mám pocit, e jich tam je nìkolik. Pøesnı poèet nevím. Samozøejmì, jak se s nima vypoøádáš to je èistì
 tvùj problém domorodèe.}
{651}{}{Vıbornì, tohle mi opravdu pomohlo. Podívejte, mìl bych ještì další otázku ohlednì Carlsona...}
{652}{}{Dobrá, tohle mi staèí. Carlson je u nyní mrtvı mu.}

# 46. ILLNESSES . . . (42)
{660}{}{Ne, nic takového...pokud já VÍM. Je to paranoidní bastard, jistì, ale nemyslím, e je nìjak nemocnı. (Svraští èelo.)
 Dále však musím øíct, e u je to trochu STARİ chlapík, take jeho zdraví nebude nejlepší.}

# 47. WHAT DOES HE DO? . . . (42)
{670}{}{(Upøenì se na tebe podíval.) On je více prezidentem NCR. To by tì nemìlo nìjak vzrušovat...jedna dobøe míøená støela a mùou mu brát míry na rakev. Pouze si dávej pozor,
 abys byl SCHOPNİ vystøelit tu jednu dobøe míøenou støelu.}
{671}{}{Dobrá tedy. Mìl bych ještì další otázku ohlednì Carlsona...}
{673}{}{"Více president NCR ?". Tak na tuhle práci si najdìte nìkoho jiného...nìjakého sebevraha.}

# 48. YOU DONE CARLSON HIT YET? . . . (WTG)
{680}{}{U ses postaral o Carlsona?}
{681}{}{Radìji bys pro mì mìl mít dobré zprávy. Je Carlson mrtvı nebo ne?}
{682}{}{Domorodèe, má trpìlivost je u konce. Zabil jsi Carlsona nebo ne?}
{683}{}{Právì teï berou Carlsonovi míry na rakev.}

# 49. SUCESSFULLY KILL CARLSON (WTG)
{695}{}{(Usmívá se.) Dobrá práce, domorodèe. Jsem ohromen...musíš vìdìt, e mì jen tak nìco neohromí. }

# 50. SUCESSFULLY KILL CARLSON (49)
{705}{}{Ne tak docela... (Usmívá se.) To co pro tebe mám je NABÍDKA: Co takhle stát se èlenem rodiny? Mám velké plány a mohl bych tvé zkušenosti vyuít
 : jsi dùmyslnı, houevnatı a svou práci dìláš perfektnì. Tohle je typ vojáka, kterého potøebuju.}
{706}{}{To mì zajímá. Co z toho budu mít?}
{707}{}{Dìkuji, ale budu muset odmítnout...moje vesnice a mí lidé na mì spoléhají.}

# 51. KILL PLAYER (34, 49, 50, 52, 53)
{715}{}{Poèkej...snad si nemyslíš, e tì pustím jenom tak, se vším co o mì víš? Heh. Nechat tì bìhat po svìtì jenom tak...to by byla špatná taktika.}
{716}{}{Poèkej...snad si nemyslíš, e tì jen tak pustím?! Heh. No tak...z mého pohledu mi máš stále DOST co splácet. A taky tì pøece nemùu jen tak pustit se vším co víš...špatná taktika.}
{717}{}{Nemluvte hlouposti, pane Bishope. Nechte mì jít nebo promìním vaše kasíno v peklo. "Rozumíte?"}
{718}{}{To má smysl. Dovolte mi ukázat moji 9mm taktiku.}
{719}{}{"Špatná taktika?" Já vám ukáu ŠPATNOU TAKTIKU, TY ZKURVySY--}

# 52. TAKEN CARE OF? HOW? (51)
{725}{}{Dobrá tedy: }
{726}{}{Chceš okusit nìnost en? Mùu ti zajistit, e u NIKDY nebudeš sám. Moná nemáš rád dìvky, to nevadí, seenu ti nìjaké mladé chlapce.}
{727}{}{Máš pøedstavy jak to dìláš s mladımi hochy? Zaøídím ti všechny chlapce které budeš chtít. Nebo to radìji dìláš s druhou pùlkou, eh? Postarám se o to, e budeš mít partnera na kadı den v tıdnu.}
{728}{}{Pokraèuj.}

# 53. TAKEN CARE OF? HOW? (52)
{735}{}{Rád lítáš, vıše a rychleji? Všechno ti dám. Chceš zbranì, nové vybavení, nìjaké vìci na vylepšení?
 Všechny tyhle nesmysly...jsou tvoje. JESTLI... (Zvednul ukazováèek.) JESTLI se pøidáš k naší rodinì.}
{736}{}{To zní dobøe. Chci se k vám pøidat... šéfe.}

# 54. TAKEN CARE OF? HOW? (53)
{740}{}{Dobrá tedy...! Vybral sis jméno jakım chceš bıt nazıván?}
{741}{}{...}

# 55. TAKEN CARE OF? HOW? (54)
{745}{}{...to se mi líbí, líbí, líbí. Teï, jestli chceš utratit na moji poèest nìjaké peníze tak sejdi ze schodù a stav se u baru nebo bì rovnou po ulici Panen do Koèièí Packy. Jestli chceš nìjaké zbranì tak bì rovnou do New Reno Arms.}
{746}{}{Udìlám...šéfe.}

# 56. TAKEN CARE OF? HOW? (WTG)
{750}{}{Hej... }
{751}{}{. Zacházejí s tebou všichni dobøe?}
{752}{}{Všechno jde dobøe, pane Bishope. Trochu jsem to provìøil, zda je pro vás vše v poøádku. Uvidíme se pozdìji.}
{753}{}{Všechno jde vıbornì. VAŠE rodina mi projevuje zdvoøilost. (Usmál ses a potom si odešel.)}

# 57. NO WAY, BISHOP. I'M OUTTA HERE (WIFE/DAUGHTER) . . . (8, 10, 11, 13, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 33, 34, 35, 36, 37, 38, 39, 40, 42, 43, 44, 45, 46, 47, 48, 56)
{755}{}{Hej, døív ne odejdeš...nechceš se znovu zastavit u mojí eny, domorodèe? }
{756}{}{Hej, døív ne odejdeš...nechceš se znovu zastavit u mojí dcery a znovu si zalítat, domorodèe? }
{757}{}{Udìlat nìjaké muf-òuf? He? (Bishop se usmál, ale je vidìt, e v tom není ani špetka humoru.)}
{758}{}{To co se stalo mezi mnou a Leslie...gr, paní Bishopovou...nic neznamenalo. Všechno co se mezi námi stalo bylo jenom...potøepání rukou.}
{759}{}{Hej...podívejte, nic se nestalo.}
{760}{}{Co s tím pane Bishope?}
{761}{}{Moná kdybyste se obèas podíval a chvíli si popovídal s Angelou, tak by urèitì nehledala pozornost...nìkde jinde.}
{762}{}{Byl byste pøekvapen jak moc to 'muf-òuf' potìšilo vaší enu. Urèitì s vámi nemìla NIKDY lepší sex.}
{763}{}{Tohle je NAPOSLEDY co jste vyslovil slovíèko domorodec. Pøipravte se na smrt.}

# 58. NO WAY, BISHOP. I'M OUTTA HERE (WIFE/DAUGHTER) . . . (57)
{770}{}{Co si o sobì myslíš ty hajzle. e mùeš jen tak vyšukat MOJÍ enu v MÉM domì a øíkat mi do oèí 'NE', kdy se tì ptám na laskavou odpovìï?}
{771}{}{Co si o sobì myslíš ty hajzle. e mùeš jen tak vyšukat MOJÍ dceru v MÉM domì a øíkat mi do oèí 'NE', kdy se tì ptám na laskavou odpovìï?}
{772}{}{Nic se nestalo! Pøísahám! Mì nezajímá co øíkala! Já jsem byl oralı! A zkouøenı! Byl to urèitì nìjakı jinı mu, ne já!}
{773}{}{K vìci, pane Bishope.}
{774}{}{K vìci, pane Bishope. Nemám èas na ty vaše árlivé kecy, jasné?}
{775}{}{Co takhle kdybych takhle udìlal celé rodinì laskavost a na místì vás zabil?}

# 59. NO WAY, BISHOP. I'M OUTTA HERE (WIFE/DAUGHTER) . . . (58)
{785}{}{Moje ena náleí MNÌ. Cokoliv, co do sebe moje ena strèí, patøí MNÌ. Máš na vıbìr, domorodèe: buï mi dáš odpovídající kus svıho masa, nebo vezmeš práci a jsme vyøízení.}
{786}{}{Moje ena náleí MNÌ. Cokoliv, co do sebe moje ena strèí, patøí MNÌ. Máš na vıbìrm domorodèe: buï mi dáš odpovídající kus svıho masa, nebo vezmeš práci a jsme vyøízení.}
{787}{}{Moje dcera je MÁ. Cokoli, co do sebe moje dcera strèí, náleí MNÌ. Máš na vıbìr, domorodèe: buï mi dáš odpovídající kus svıho masa, nebo vezmeš práci a jsme vyøízení.}
{788}{}{To maso mùeš mít... jen pojï si ho vzít.}
{789}{}{Dobrá tedy. Udìlám to...}
{790}{}{Vaše ena takovou CENU nemá.}
{791}{}{Vaše dcera takovou CENU nemá.}

# 60. NO WAY, BISHOP. I'M OUTTA HERE (WIFE/DAUGHTER) . . . (8, 10, 11, 13, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 33, 34, 35, 36, 37, 38, 39, 40, 42, 43, 44, 45, 46, 47, 48, 56)
{800}{}{Hej, ale døív ne odejdeš...rád bych se podíval na tvoje zbranì, domorodèe...slyšel jsem o nich nedávno úplné povìsti.}
{801}{}{Povìsti?}

# 61. IF PLAYER WIPED OUT RAIDERS, THREAT 1 (60)
{805}{}{Ano...povìsti, v pustinì je nìkdo kdo odpovídá tvému popisu a kterı znièil ty oldáky jinì od Vault City. }
{806}{}{Cestuje s ním mutant. }
{807}{}{Cestuje s ním domorodec, kterı má nos propíchlı kostí. }
{808}{}{Cestuje s ním robot, kterı má mozek usazenı v kopuli. }
{809}{}{Co mi na to mùeš øíct?}
{810}{}{Øíct co?}
{811}{}{Och to jsem JÁ! JÁ! Já jsem to udìlal!}
{812}{}{Ano, jsem to já.}
{813}{}{Co bych mìl na to øíct? Nic. Proè?}
{814}{}{Velká pustina, mnoho banditù. Mohl jste se splést.}
{815}{}{Velká pustina, mnoho lidí, kteøí vypadají jako já. Mohl jste se splést.}

# 62. THAT'S ME/RAIDER THREAT 2 (61)
{820}{}{Tedy, ty musíš bıt nìjakı debilní parchant, kdy jsi zbyteènì z nudy zabil tolik chlapù. }
{821}{}{Tedy, ty musíš bıt nìjaká zkurvená dìvka, kdy jsi zbyteènì z nudy zabila tolik chlapù. }
{822}{}{Nelíbí se mi, co jsi tam udìlal. V tom kempu jsem mìl pár svıch nejlepších lidí.}
{823}{}{Pokud by tu nìkdo vytasil zbraò, vidìl byste osobnì, co se tìm banditùm stalo.}
{824}{}{Moná jste je mìl vycvièit lépe. Bylo to jako støílet do hromady geckonù. ORALİCH geckonù.}
{825}{}{Nevìdìl jsem, e pracují pro vás. Vlastnì nechtìli vùbec mluvit.}

# 63. RAIDER THREAT 3. . . (61, 62)
{835}{}{Tak takhle? Myslím, e jsi tam byl. Myslím, e jsi za to odpovìdnı. }
{836}{}{Jak to tak vypadá, tak mi DLUÍŠ hodnì domorodèe. Udìláš teï práci za 20 muù, abys mi to splatil. }
{837}{}{Vezmeš práci, pak to...moná...mùeme nazvat za vyøízené.}
{838}{}{Myslím, e jedna kulka do tvé hlavy vyrovná naše dluhy.}
{840}{}{Oni MÌ napadli, pane Bishope. Nic vám nedluím a ádnou špinavou práci pro vás nebudu dìlat. Rozumíte?}
{900}{}{Doruèil jsi kuføík od Thomase Moora.}
{925}{}{Zavradil jsi Westina.}
{950}{}{Vyøídil jsi Carlsona.}
{975}{}{Stáváš se èlenem Bishopovy rodiny.}