# Tento soubor pøeloil Radim "HIGHTOWER" Brix , hightower@angelfire.com
{100}{}{Vidíš jednoho z Bishopovıch bodyguardù.}

# EXAMINE
{150}{}{Vidíš drsnì vypadajícího chlápka obleèeného v koené zbroji. Na jeho tìle je vidìt mnoho jizev a starıch støelnıch
 zranìní.}
{151}{}{Vidíš jednoho z Bishopovıch muù. Rozhlíí se po okolí a ruce má pøipraveny na kohoutku zbranì.}

# 1. FLOAT DIALOGUE: ENCLAVE DESTROYED IS TRUE (WTG)
{200}{}{Hej! }
{201}{}{! Cesta jak nakopat Enklávì prdel!}

# 2. FLOAT DIALOGUE: POWER ARMOR (WTG)
{205}{}{Sakra, jak ses dostal s touhle vìcí a do koupelny?}

# 3. FLOAT DIALOGUE: PLAYER = FEMALE/MALE, MADE MAN, FA=BISHOP [ARMED] (WTG)
{210}{}{Pan Bishop tì oèekává, }
{211}{}{? Jdi nahoru. Ale pamatuj nevytahuj pøed ním ádnou zbraò.}

# 4. FLOAT DIALOGUE: PLAYER = FEMALE/MALE, MADE MAN, FA=BISHOP [SNEAK] (WTG)
{215}{}{Uh, podívej... Pan Bishop tì oèkává, jasné, }
{216}{}{? Bì nahoru. Ale stejnì vypni plíení.}

# 5. FLOAT DIALOGUE: PLAYER = FEMALE/MALE, MADE MAN, FA=BISHOP [NORMAL] (WTG)
{221}{}{? Jdi nahoru.}

# 6. FLOAT/CLICK DIALOGUE: MADE MAN, FA=NOT BISHOP (WTG)
{225}{}{Právì jsi vešel na špatné místo, svinì.}
{226}{}{Podívej se na mıho boxera, zkurvysyne... odejdi chlapèe, døív ne tì zabijem jako prašivou koèku.}
{227}{}{Tihle chlapci si øíkají o trable...}
{228}{}{Radìji odejdi, }
{229}{}{Dobøe, jestli to musí bıt }
{230}{}{Slyším }
{231}{}{Nemyslíš, e nejsi èlenem rodiny }
{232}{}{Právì jsi vlezl na špatné místo, hajzle.}
{233}{}{Dobøe se podívejte na tu dìvku, jak se tu naparuje...}
{234}{}{Odejdi dìvèe. Døív ne tì zastøelíme.}
{235}{}{Tahle dìvka si øíká o problémy...}
{236}{}{Slyším }

# 8. FLOAT DIALOGUE: MALE, PRIZEFIGHTER [ARMED] (WTG)
{245}{}{Ty, šampióne. Tady ádné zbranì, rozumíš?}
{246}{}{Ty, šampióne! Odlo tu zbraò.}
{247}{}{Hej, }

# 9. FLOAT DIALOGUE: MALE, PRIZEFIGHTER AND MALE PORN STAR [SNEAK] (WTG)
{255}{}{Proè se tady kolem plííš?}
{256}{}{Snaíš se vyhnout svım fanouškùm?}
{257}{}{Uh, proè ty tajnosti?}

# 10. FLOAT DIALOGUE: MALE/FEMALE, PRIZEFIGHTER (WTG)
{265}{}{Ty, }
{266}{}{Ty, }

# 11. FLOAT DIALOGUE: MALE/FEMALE, PORN STAR [ARMED] (WTG)
{275}{}{Ty, fešáku. Tady ádné zbranì, rozumíš?}
{276}{}{Hej, }
{277}{}{Ty, }
{278}{}{Miláèku, tady nemùeš nosit ádné zbranì. Heh-heh... ty bys stejnì dokázala zabít i bez nich.}
{279}{}{Hej, }

# 13. FLOAT DIALOGUE: [PORN STAR, FEMALE] [SNEAK] (WTG)
{285}{}{Miláèku, s takovımhle tìlem se nikde neskryješ.}

# 14. FLOAT DIALOGUE: [PORN STAR] (WTG)
{290}{}{Miluji filmy, }
{291}{}{Perfektní byl film "Anální Nikita".}
{292}{}{Perfektní byl film "Oral Hills 90210 ".}
{293}{}{Jsem velkı fanoušek tvé práce v pornofilmech.}
{294}{}{::píská na tebe::}

# 16. FLOAT DIALOGUE: SLAVER [ARMED] (WTG)
{300}{}{Nechceš náhodou zaplnit jedno místo na høbitovì v Golgotì, otrokáøi? Tak dej tu vìc pryè.}
{301}{}{Odlo tu zbraò otrokáøi, nebo si z tebe udìlám svùj cviènı cíl.}
{302}{}{Otrokáøi, radìji tu zbraò HNED schovej.}

# 17. FLOAT DIALOGUE: SLAVER [SNEAK] (WTG)
{305}{}{Nechceš náhodou zaplnit jedno místo na høbitovì v Golgotì, otrokáøi? Pøestaò se tu kolem plíit.}
{306}{}{Pøestaò se tu plíit otrokáøi, nebo si z tebe udìlám svùj cviènı cíl.}
{307}{}{Otrokáøi moná by ses mìl vrátit do školy pro ninji - tak hned se tu pøestaò plíit.}
{308}{}{Otrokáøi radìji se tu HNED pøestaò plíit nebo mùeš skonèit špatnì.}

# 18. FLOAT DIALOGUE: MALE/FEMALE, NO REP [ARMED] (WTG)
{315}{}{Nechceš náhodou zaplnit jedno místo na høbitovì v Golgotì, domorodèe? Tak dej tu vìc pryè.}
{316}{}{Odlo tu zbraò domorodèe, nebo si z tebe udìlám svùj cviènı cíl.}
{317}{}{Domorodèe, radìji HNED schovej tu zbraò.}

# 19. FLOAT DIALOGUE: MALE/FEMALE, NO REP [SNEAK] (WTG)
{325}{}{Nechceš náhodou zaplnit jedno místo na høbitovì v Golgotì, barbare? Pøestaò se tu kolem plíit.}
{326}{}{Pøestaò se tu plíit domorodèe, nebo si z tebe udìlám svùj cviènı cíl.}
{327}{}{Domorodèe moná by ses mìl vrátit do školy pro ninjy - tak hned se tu pøestaò plíit.}
{328}{}{Domorodèe radìji se tu HNED pøestaò plíit nebo mùeš skonèit špatnì.}

# 20. FLOAT DIALOGUE: COMPANION: ROBOBRAIN (WTG)
{335}{}{Vem si toho robota okamitì pryè! Hned.}
{336}{}{Vem si toho robota okamitì pryè nebo si tu z nìho udìláme pìknı ohòostroj.}
{337}{}{Z toho robota udìlám náhradní díly, jestli tady zùstane ještì chvíli.}

# 21. FLOAT DIALOGUE: COMPANION: MARCUS (WTG)
{345}{}{*Myslím*, e cítím mutanta. Radìji si tu lutou prdel odsud odveï.}
{346}{}{Ty a tvùj pøítel mutant si koledujete o to, abych vás sejmul! Radìji sním odejdi.}
{347}{}{Ten mutant by mi mìl okamitì zmizet z oèí, nebo si jeho hlavu povìsíme na zeï jako trofej.}

# 22. FLOAT DIALOGUE: COMPANION: LENNY (WTG)
{355}{}{*Myslím*, e tady smrdí hniloba. Vem si toho ghoula a vypadni odsaï.}
{356}{}{Odveï si odsaï toho páchnoucího ghoula. Hned.}
{357}{}{A je ten ghoul do minuty pryè, nebo bude mrtvìjší, ne je teï.}

# 23. FLOAT DIALOGUE: MALE/FEMALE, NO REP (WTG)
{365}{}{Po práci ètu Koèièí Packu.}
{366}{}{Po práci prolézám všechny hospody a bary.}

# 24. CLICK DIALOGUE: MALE/FEMALE, MADE MAN: BISHOP, BISHOP = DEAD (WTG) !!!! nebo si zahrát kuleèník teï nevím
{370}{}{Mùeš jít nahoru jestli chceš. Pan Bishop je stejnì vyèerpanı, take si taky mùeš vlézt do bazénu.}

# 25. INTRO (WTG)
{375}{}{Co potøebuješ, kamaráde? Ale rychle.}
{376}{}{Co potøebuješ, miláèku? Ale rychle.}
{377}{}{Zase ty. Do prdele co zase chceš?}
{378}{}{Já chci svìtovı mír}
{379}{}{Chci jít nahoru po schodech}
{380}{}{Hoo Joo}
{381}{}{Zatoulal jsem se}
{382}{}{Co je tam nahoøe?}
{383}{}{Jsem tady, abych vidìl pana Bishopa.}
{384}{}{Jsem tady, abych vidìl pana Bishopa. Mám pro nìho kuføík od pana Moorea.}
{385}{}{Pardon, patrnì jsem se spletl. Radìji odejdu.}

# 26. TRY TO GO UPSTAIRS (WTG)
{390}{}{Copak chceš dìlat nahoøe, kamaráde?}
{391}{}{Copak chceš dìlat nahoøe, miláèku?}

# 27.  RETARD (25, 26, 29, 30, 32, 33)
{405}{}{Chlapèe, ty jsi ale zkurvysyn, nemám pravdu? }
{406}{}{Holka, ty jsi ale dìvka, nemám pravdu? }
{407}{}{Podívej, vypadni odsaï døív, ne ti vystøelíme zbytek tvého mozku.}
{408}{}{CHCI SVÌTOVİ MÍR, JÁ CHCI SVÌTOVİ MÍR}
{409}{}{ØÍKÁM, E CHCI JÍT NAHORU}
{410}{}{HOO YOO}
{411}{}{Dobelhat se}
{412}{}{Puste mì.}
{414}{}{Dobrá. U odcházím.}

# 28. LOUD RETARD (27)
{420}{}{Šmejde, právì jsi získal lístek do svìta bolesti.}
{421}{}{Dìvko, právì jsi získala lístek do svìta bolesti.}
{422}{}{VYYY TEN KDO ZABÍJÍ}
{423}{}{ pouze já sám chci zùstat, ale IVOT je plnı bolesti }
{424}{}{ take }
{425}{}{ ZNIÈIT SLABÉ MRÒAVÉ LIDI}
{426}{}{Køièet a utíkat se schovat}
{427}{}{Buïte ticho, posilnìte se a buïte pøipraveni na to, e utríte nìjaké rány.}
{428}{}{Chcete nìco z TOHODLE, chlapci?! CHCETE NÌCO?! Tak mi dejte nìco, vy patetiètí 
 ZKURVYSY --}

# 29. WHAT'S UP THOSE STAIRS? (25, 26)
{435}{}{Jestli nevíš, pak ani NEPOTØEBUJEŠ vìdìt. Teï zmiz.}

# 30.  BISHOP DEAD (25, 26, 27, 29)
{445}{}{Take, je to špatné, pan Bishop se nedávno odebral na vìènou cestu do nebe. Teï zmiz.}
{446}{}{Jsi hluchı? John Posranı Bishop je zasranì MRTVİ, chápeš? Take u koneènì vypadni, nebo se k nìmu pøidáš.}
{447}{}{Podívej, potøebuji jít nahoru, staèí jenom na chvilku.}
{448}{}{OK, odcházím.}

# 31. I'M HERE TO SEE BISHOP (25, 26, 27)
{455}{}{Ne, znám pracovní program pana Bishopa a naprosto pøesnì vím, e v nìm nejsi.}
{456}{}{On mì oèekává. Øeknìte mu, e jsem zde.}
{458}{}{Dobrá tedy. Nashledanou.}

# 32. HE'S EXPECTING ME. (31)
{465}{}{Fajn, kamaráde. Jak se jmenuješ? Ovìøím si to u šéfa.}
{466}{}{Fajn, miláèku. Jak se jmenuješ? Ovìøím si to u šéfa.}
{467}{}{Jsem }
{468}{}{.}
{469}{}{Nepotøebuješ vìdìt moje jméno. Prostì mì za ním pus.}
{471}{}{Zapomeò na to. Nemusíš si nic ovìøovat...odcházím.}

# 33. HE'S EXPECTING ME (REFUSE) (32)
{475}{}{(Stráce na chvíli kousek popošel, otevøel jeden panel na zdi a cosi zašeptal. Chvíli èekal, poslouchal, pak se otoèil zpìt na tebe.) }
{476}{}{Øíkal, e tì nezná. Take zmiz, kamaráde. Akorát plıtváš naším èasem.}
{477}{}{Øíkal, e tì nezná. Take zmiz, miláèku. Akorát plıtváš naším èasem.}
{478}{}{Dovolte mi ho vidìt. Hned.}
{479}{}{Øeknìte mu, e mám pro nìho kuføík... od pana Moorea.}
{480}{}{Zapomeò na to.}

# 34. HE'S EXPECTING ME (AGREE) (25, 26, 27, 28, 29, 33)
{490}{}{(Stráce na chvíli kousek popošel, otevøel jeden panel na zdi a cosi zašeptal. Chvíli èekal, poslouchal, pak se otoèil zpìt na tebe a pokrèil rameny.) Øekl, e mùeš jít nahoru.}
{491}{}{Dobrá.}

# 35. MADE MAN: BISHOP (WTG)
{495}{}{Ty, }
{496}{}{! }
{497}{}{Pan Bishop tì oèekává?}
{498}{}{Ano. Mohl bych jít nahoru? Musím s panem Bishopem prodiskutovat nìjaké obchodní záleitosti.}
{499}{}{Ne, nyní ne. Dávejte pozor, chlapi.}

# 36. MADE MAN (35)
{505}{}{Jistì, bì nahoru, }
{506}{}{. }
{507}{}{Pøíštì, a budeš chtít jít nahoru, tak se nemusíš tak hezky ptát...prostì bì nahoru.}
{508}{}{Díky.}

# END LINES
{1228}{}{. Teï.}
{1229}{}{. Nepostrádá tì tvoje rodina?}
{1230}{}{ rodina je jako smeèka koèek. Co si o tom myslíš?}
{1231}{}{ mìl víc èasu na dìlání jinıch vìcí ne lozit šéfùm do zadku.}
{1236}{}{ rodina je jako smeèka koèek. Teï vím, e je to pravda.}
{1247}{}{! Tady nemùeš ukazovat své zbranì, rozumíš?}
{1265}{}{. Dáváš na sebe pozor?}
{1266}{}{. Co se dìje?}
{1276}{}{! Tady nemùeš ukazovat své zbranì, rozumíš?}
{1277}{}{! Odlo tu zbraò pryè.}
{1279}{}{! Svoje kozy tady ukazovat mùeš, ale zbranì ne, rozumíš?}
{1290}{}{!}