# Tento soubor pøeloil Radim "HIGHTOWER" Brix , hightower@angelfire.com
{100}{}{Vidíš jednoho z Bishopovıch muù.}

# EXAMINES
{150}{}{Vidíš drsnì vypadajícího chlápka obleèeného v koené zbroji. Na jeho tìle je vidìt mnoho jizev a starıch støelnıch
 zranìní.}
{151}{}{Vidíš jednoho z Bishopovıch muù. Rozhlíí se po okolí a ruce má pøipraveny na kohoutku zbranì.}

# 1. FLOAT DIALOGUE: ENCLAVE DESTROYED IS TRUE
{200}{}{Hej! }
{201}{}{::dìkovaèka::}
{202}{}{::tleskání::}
{203}{}{::hvízdání::}

# 2. FLOAT DIALOGUE: POWER ARMOR
{205}{}{Sakra jak ses dostal s touhle vìcí a do koupelny?}

# 3. FLOAT DIALOGUE: PLAYER = FEMALE/MALE, MADE MAN, FA=BISHOP [ARMED]
{210}{}{Pìknı kousek tam máš, }

# 4. FLOAT DIALOGUE: PLAYER = FEMALE/MALE, MADE MAN, FA=BISHOP [SNEAK]
{215}{}{Uf, proè tady kolem slídíš, }
{216}{}{Uf, hej, }

# 5. FLOAT DIALOGUE: PLAYER = FEMALE/MALE, MADE MAN, FA=BISHOP [NORMAL]
{220}{}{Ty, }
{221}{}{Hej, }
{222}{}{Hej, }

# 6. FLOAT/CLICK DIALOGUE: MADE MAN, FA=NOT BISHOP
{225}{}{Právì si vešel na špatné místo, svinì.}
{226}{}{Podívej se na mıho boxera, zkurvysynu... odejdi chlapèe, døív ne tì zabijem jako prašivou koèku.}
{227}{}{Tihle chlapci si øíkají o trable...}
{228}{}{Slyším }
{229}{}{Radìji odejdi, }
{230}{}{Dobøe, jestli to musí bıt }
{231}{}{Nemyslíš, e nejsi èlenem rodiny }
{232}{}{Právì jsi vlezl na špatné místo, hajzle.}
{233}{}{Dobøe se podívejte na tu dìvku, jak se tu naparuje...}
{234}{}{Odejdi dìvèe. Døív ne tì zastøelíme.}
{235}{}{Tahle kurva si øíká o problémy...}
{236}{}{Slyším }

# 8. FLOAT DIALOGUE: MALE, PRIZEFIGHTER [ARMED]
{250}{}{Šampióne. Tady ádné zbranì, jasné?}
{251}{}{Šampióne! Dej tu zbraò pryè.}
{252}{}{Hej, }

# 9. FLOAT DIALOGUE: MALE, PRIZEFIGHTER AND MALE PORN STAR [SNEAK]
{255}{}{Po èem tady slídíš?}
{256}{}{Snaíš se uniknout svım fanouškùm?}
{257}{}{Uf, na co tolik tajností?}

# 10. FLOAT DIALOGUE: MALE/FEMALE, PRIZEFIGHTER
{260}{}{Ty, }
{261}{}{Ty, }

# 11. FLOAT DIALOGUE: PORN STAR [ARMED]
{265}{}{Ty, fešáku. Tady nesmíš nosit ádné zbranì, rozumíš?}
{266}{}{Hej, }
{267}{}{Ty, }
{268}{}{Miláèku, tady nemùeš nosit ádné zbranì. Heh-heh... ty bys stejnì dokázala zabít i bez nich.}
{269}{}{Hej, }

# 13. FLOAT DIALOGUE: [PORN STAR, FEMALE] [SNEAK]
{275}{}{Miláèku, s takovımhle tìlem se nikde neskryješ.}

# 14. FLOAT DIALOGUE: [PORN STAR, NORMAL]
{280}{}{Miluji filmy, }
{281}{}{Perfektní byl film Velké koule na prodej.}
{282}{}{Perfektní byl film Krásné velké kopce.}
{283}{}{Jsem velkı fanoušek tvé práce v pornofilmech.}
{284}{}{Miluji film "Vault Sex-Teen." Byl hodnì inspirativní. Úplná filmová Tour-de-France.}
{285}{}{::pískání::}

# 16. FLOAT DIALOGUE: SLAVER [ARMED]
{295}{}{Nechceš náhodou zaplnit jedno místo na høbitovì v Golgotì, otrokáøi? Tak dej tu vìc pryè.}
{296}{}{Odlo tu zbraò otrokáøi, nebo si z tebe udìlám svùj cviènı cíl.}
{297}{}{Otrokáøi, radìji tu zbraò HNED schovej.}

# 17. FLOAT DIALOGUE: SLAVER [SNEAK]
{300}{}{Nechceš náhodou zaplnit jedno místo na høbitovì v Golgotì, otrokáøi? Pøestaò se tu kolem plíit.}
{301}{}{Pøestaò se tu plíit otrokáøi, nebo si z tebe udìlám svùj cviènı cíl.}
{302}{}{Otrokáøi moná by ses mìl vrátit do školy pro ninjy - tak hned se tu pøestaò plíit.}
{303}{}{Otrokáøi radìji se tu HNED pøestaò plíit nebo mùeš skonèit špatnì.}

# 18. FLOAT DIALOGUE: MALE/FEMALE, NO REP [ARMED]
{305}{}{Nechceš náhodou zaplnit jedno místo na høbitovì v Golgotì, domorodèe? Tak dej tu vìc pryè.}
{306}{}{Odlo tu zbraò domorodèe, nebo si z tebe udìlám svùj cviènı cíl.}
{307}{}{Domorodèe, radìji HNED schovej tu zbraò.}

# 19. FLOAT DIALOGUE: MALE/FEMALE, NO REP [SNEAK]
{310}{}{Nechceš náhodou zaplnit jedno místo na høbitovì v Golgotì, domorodèe? Pøestaò se tu kolem plíit.}
{311}{}{Pøestaò se tu plíit, domorodèe, nebo si z tebe udìlám svùj cviènı cíl.}
{312}{}{Domorodèe moná by ses mìl vrátit do školy pro ninjy - tak hned se tu pøestaò plíit.}
{313}{}{Domorodèe radìji se tu HNED pøestaò plíit nebo mùeš skonèit špatnì.}

# 20. FLOAT DIALOGUE: COMPANION: ROBOBRAIN
{315}{}{Vem si toho robota okamitì pryè! Hned.}
{316}{}{Vem si toho robota okamitì pryè nebo si tu z nìho udìláme pìknı ohòostroj.}
{317}{}{Z toho robota udìlám náhradní díly, jestli tady zùstane ještì chvíli.}

# 21. FLOAT DIALOGUE: COMPANION: MARCUS
{320}{}{*Myslím*, e cítím mutanta. Radìji si tu lutou prdel odsud odveï.}
{321}{}{Ty a tvùj pøítel mutant si koledujete o to abych vás sejmul! Radìji sním odejdi.}
{322}{}{Ten mutant by mi mìl okamitì zmizet z oèí, nebo si jeho hlavu povìsíme na zeï jako trofej.}

# 22. FLOAT DIALOGUE: MALE/FEMALE, NO REP
{325}{}{Stihnul jsi tu bitvu minulou noc?}
{326}{}{Po práci prolézám všechny hospody a bary.}

# 23. CLICK DIALOGUE: ENCLAVE DESTROYED IS TRUE
{330}{}{Myslím, e prezident byl mıtus,	èernoch kterı strašil dìti.}
{331}{}{Vypadáš, jako bys zrovna prošel peklem a vrátil se. Odpoèiò si. Zaslouíš si to.}
{332}{}{Oni chtìli vzduch zamoøit nìjakım novım virem? Bastardi. Doufám, e jsi jich pár sejmul za mì.}
{333}{}{Mohl bys hru zaèít znovu s jinou postavou, která bude mít jiné vlastnosti.}
{334}{}{Musely ti pìknì narùst svaly, kdy ses vypoøádal s tou zkurvenou Enklávou.}
{335}{}{Take teï, kdy jsi to dokonèil, se tu jenom procházíš kolem a sbíráš zkušenostní body, huh? Dobrá, prosím nezabíjej mì
 , ano?}
{336}{}{New Reno bylo vytvoøeno Chrisem Avellonem a scriptováno Tomem Frenchem. Jedná z fám øíká, e se brzo vezmou :)).
 No a tuhle èást pøeloil Radim "HIGHTOWER" Brix.}
{337}{}{Doufám, e budu hlavní postava ve Falloutu 3, jako Tandi nebo Ian. Budu zabíjet všechny ty vrahy, lupièe ...}
{338}{}{Jistì, jednou jsem se vyspal s Tandi. Kdy byla ještì mladá, teda aspoò myslím.}
{339}{}{Lynette, drobeèek, potøebuje trochu nìhy a lásky, chápeš co tím myslím?}
{340}{}{Slyšel jsem, e ses vypoøádal s tou Enklávou na jihu. To bylo odváné.}

# 24. CLICK DIALOGUE: MALE/FEMALE, MADE MAN, SAME FAMILY
{350}{}{Hej, }
{351}{}{Ty, }
{352}{}{Hej, }
{353}{}{Slyšel jsem, e se Tommy the Balls vrátil do mìsta. Zkontroluj si vìci.}
{354}{}{Vidíš Tommyho the Ballse, radìji se mu neple do cesty.}
{355}{}{Kdy budeš mluvit s panem Bishopem, mohl by ses o mì zmínit?}
{356}{}{Pìknì sis to u šéfa polepšil. Pøál bych si abych to mìl u šéfa taky tak dobré jako ty.}
{357}{}{Nemáš nìjaké finty o které by ses se mnou mohl podìlit?}
{358}{}{Bishopova rodina je pro mì nejlepší.}
{359}{}{John Bishop vládne tomuto mìstu.}
{360}{}{Dneska je tu pomìrnì klid.}
{361}{}{Pøichází bouøe.}
{362}{}{Ten zápach z Golgothy byl dnes v noci pøíšernı.}
{363}{}{Kdy pùjdeme dát nakládaèku jedné z rodin v New Reno?}
{364}{}{S tebou na naší stranì nemají ostatní rodiny šanci, šéfe.}
{365}{}{Máš nìco šéfe?}
{366}{}{Máš nìjaké informace na další rodiny?}
{367}{}{Hmm, máte nìjakı Jet?}
{368}{}{Jistì e bych se napil...}
{369}{}{Paní Bishopová si mì znovu kontrolovala. Je mi to nepøíjemné.}
{370}{}{Paní Bishopová si mì hlídá jako øízek z hovìzího. Pøeju si, abys uvìdomila, e se nechci
 vázat.}
{371}{}{Bishopova dcera je jedná velká šoustaèka.}
{372}{}{Bishopova holka zpùsobuje jenom problémy.}
{373}{}{Slyšel jsem, e jeden chlápek oral Bishopovu dceru, a Bishop ho za to skalpoval.}
{374}{}{Jestli budeš mluvit s panem Bishopem, tak se dr dál od jeho eny a dcery... nic ne trable.}

# 25. CLICK DIALOGUE: PRIZEFIGHTER
{380}{}{Slyšel jsem, e se líbíš paní Bishopové. Dej si pozor kamaráde.}
{381}{}{Slyšel jsem, e se líbíš Bishopovì dceøi. Dej si pozor, ona znamená problémy.}
{382}{}{Nevypadáš nìjak zvláš silnı pane Profesionální Boxer.}
{383}{}{Moná víš, e Bishopova rodina by mohla vyuít slueb takového svalovce jako si ty. Silného. Nekompromisního.}
{384}{}{Mìl by sis promluvit s panem Bishopem, jestli pro tebe nemá nìjakou práci.}
{385}{}{Mìl by sis rozmyslet jestli se k nám nepøidáš. Já ovládám celé New Reno.}
{386}{}{Získal jsem $20, protoe jsem si na tebe vsadil!}
{387}{}{Hej, šampióne! Ta poslední bitka byla ohromná!}
{388}{}{Vidìl jsem tì bojovat v ringu. Sakra ten tvùj pravı hák je vraednı.}
{389}{}{Neslábneš náhodou? Prohrál jsem $30, kdy jsem na tebe vsadil.}
{390}{}{Kolik zvedneš na benè?}
{391}{}{Kde ses tak vypracoval?}
{392}{}{Dávej si bacha na Masticatora. Chutnají mu uši.}
{393}{}{Koupil bych ti drink, ale všechny prachy jsem prohrál, kdy jsem sázel na tvoje soupeøe.}
{394}{}{Dáme si zápas?}
{395}{}{Nevypadáš nìjak zvláš silnì, sleèno Levı Hák.}
{396}{}{Mùu vidìt tvoje zatnuté bøišní svaly?}

# 27. CLICK DIALOGUE: PORN STAR
{400}{}{Slyšel jsem, e se po tobì ptala paní Bishopová. Mìj se na pozoru, kamaráde.}
{401}{}{Dáš si se mnou èíslo, abych se nìco pøiuèil? No tááák. Uèím se velmi rychle.}
{402}{}{Miluji filmy, }
{403}{}{Perfektní byl film Velké koule na prodej.}
{404}{}{Perfektní byl film Krásné velké kopce.}
{405}{}{Jsem velkı fanoušek tvé práce v pornofilmech.}
{406}{}{Miluji film "Vault Sex-Teen." Byl hodnì inspirující. Úplná filmová Tour-de-France.}
{407}{}{Slyšel jsem, e se po tobì ptala Bishopova dcera. S ní tì èekají jenom problémy.}
{408}{}{Máte nìkdy ve studiu dny otevøenıch dveøí?}
{409}{}{Miluji film "Vault Sex-Teen." Byl hodnì inspirující. Úplná filmová Tour-de-France.}
{410}{}{Slyšel jsem, e Tommy the Balls by ti chtìl udìlat podrobnou prohlídku v soukromí.}
{411}{}{Miluji tvùj poslední film. Mùu ti pomoct nazkoušet další?}
{412}{}{Dej mi práci a já ti ukáu nìkterı z mıch filmù.}
{413}{}{Nechceš se nìkdy na chvíli zastavit a kouknout se na mì?}
{414}{}{Hej, ty jsi tady dneska v noci tanèila?}
{415}{}{Vypadáš nebezpeènì, cukroušku.}
{416}{}{Paní Štìstìna bude árlit, jestli se tady budeš ještì chvíli procházet.}

# 29. CLICK DIALOGUE: [SLAVER]
{420}{}{Tak co je nového v Denu?}
{421}{}{Bolelo to, kdy ti vypalovali to znamení otrokáøe?}
{422}{}{Pøemıšlel jsem, e bych se taky mohl stát otrokáøem, ale nenávidím všechno to cestování.}
{423}{}{Hledáš chlévy? Je to tam kde zadrují vìtšinu otrokù.}
{424}{}{Bıt èlenem Bishopovy rodiny je dobrá práce.}
{425}{}{Pøivezl jsi novou dodávku otrokù, nebo jsi tu jenom s karavanou?}
{426}{}{Chlapi, potøebovali byste nìjaké nové zboí... ta poslední dodávka otrokù byla strašnì ubohá.}
{427}{}{Chlapi, ještì chytáte ty domorodé otroky?}
{428}{}{Jaké jsou v dnešní dobì ceny otrokù?}
{429}{}{Otrokáøi, brahmíny, to je to samé.}

# 30. CLICK DIALOGUE: MALE/FEMALE, NO REP (Good Reaction)
{440}{}{Jestlie se poohlííš po nìjaké práci, tak právì potøebujeme nìkoho jako jsi ty. Promluv si s panem Bishopem.}
{441}{}{Potøebuješ práci? Mohl by sis promluvit s panem Bishopem.}

# 31. CLICK DIALOGUE: MALE, NO REP (Bad Reaction)
{445}{}{Vypadni, domorodèe.}
{446}{}{Nemám pro tebe ádné drogy, domorodèe.}
{447}{}{Bì a vykuø si dımku míru, domorodèe.}
{448}{}{NEMÁM náladu si s tebou povídat. Vypadni.}
{449}{}{Zmizni, domorodèe.}
{450}{}{Víš kdo jsem? Jsem jeden z Bishopovıch muù. Take hned odprejskni.}
{451}{}{Nechceš mì náhodou rozzuøit? Radìji mì nechtìj vidìt, jak se vztekám.}
{452}{}{Táhni, døív ne si z tebe udìlám cviènı cíl.}
{453}{}{Vyhledáváš problémy? Tak ještì chvíli do mì huè a uvidíš co se stane.}

# 32. CLICK DIALOGUE: FEMALE, NO REP (Bad Reaction)
{460}{}{Teï nemám chu se dívat na domorodé prdele. Pøijï nìkdy pozdìji.}
{461}{}{Teï na tebe nemám èas, domorodkynì. Proè nepøíjdeš pozdìji?}
{462}{}{Ne, nevím kde to je. Teï odprejskni! ::Debilní domorodci.::}
{463}{}{Zmizni domorodkynì.}
{464}{}{Pan Bishopnemluví s domorodım odpadem, máme lepší vìci na práci.}
{465}{}{Nemám pro tebe ádné drogy domorodkynì.}
{466}{}{Bì si vykouøit dımku míru, domorodkynì.}
{467}{}{NEMÁM náladu si s tebou povídat. Vypadni.}
{468}{}{Vypadni, domorodko.}
{469}{}{Víš kdo jsem? Jsem jeden z Bishopovıch muù. Take hned odprejskni.}
{470}{}{Nechceš mì náhodou rozzuøit? Radìji mì nechtìj vidìt jak se vztekám.}
{471}{}{Táhni, døív ne si z tebe udìlám cviènı cíl.}
{472}{}{Vyhledáváš problémy? Tak ještì chvíli do mì huè a uvidíš co se stane.}
{473}{}{Ještì nejsem tak hodnì oralı, abych s tebou mluvil. Táhni.}
{474}{}{Ty jsi nejhnusnìjší domorodka jakou jsem kdy vidìl.}
{475}{}{Vypadni odsaï, døív ne z tebe udìlám ohyzdnìjší potvoru ne jsi teï.}
{476}{}{Bì štìkat na nìkoho, kdo je více oralı ne já, dìvko.}

# 34. FLOAT DIALOGUE: COMPANION: LENNY
{490}{}{*Myslím*, e tady smrdí hniloba. Vem si toho ghoula a vypadni odsaï.}
{491}{}{Odveï si odsaï toho páchnoucího ghoula. Hned.}
{492}{}{A je ten ghoul do minuty pryè, je smrtelnìjší ne on sám.}

# END OF LINES
{1200}{}{! Cesta jak nakopat Enklávì prdel!}
{1210}{}{.}
{1215}{}{?}
{1216}{}{... proè ty tajnosti?}
{1220}{}{, co se tu probírá?}
{1221}{}{, co se ti stalo?}
{1222}{}{! Vyhıbáš se problémùm?}
{1228}{}{ rodina je jako hromada koèek. Co si o tom myslíš?}
{1229}{}{. Nyní.}
{1230}{}{. Nepostrádá tì tvoje rodina?}
{1231}{}{ mìl víc èasu na dìlání jinıch vìcí ne lozit šéfùm do zadku.}
{1236}{}{ rodina je jako hromada koèek. Teï vím, e je to pravda.}
{1252}{}{! Tady nemùeš ukazovat své zbranì, rozumíš?}
{1260}{}{. Dáváš na sebe pozor?}
{1261}{}{. Co se dìje?}
{1266}{}{! Tady nemùeš ukazovat své zbranì, rozumíš?}
{1267}{}{! Odlo tu zbraò.}
{1269}{}{! Tady mùeš ukazovat akorát svoje kozy, ale ne zbranì, rozumíš?}
{1280}{}{!}
{1350}{}{. Co se dìje?}
{1351}{}{. Co se tu probírá?}
{1352}{}{. Vyhıbáš se problémùm?}
{1402}{}{!}
