# Tento soubor pøeložil Radim "HIGHTOWER" Brix , hightower@angelfire.com
{100}{}{Vidíš jednoho z bodygardù Korsických Bratrù.}

# 1. LOOK (WTG)
{150}{}{Vidíš tvrdì vypadající ženu se zeleným kabátem. Opatruje svùj kulomet jako by to bylo její dítì.}
{151}{}{Vidíš jednoho z bodygardù Korsických Bratrù.}


# 2. FLOAT (ANY) TO [FLAG: ENCLAVE DESTROYED] (WTG)
{200}{}{Zachránil jsi svìt, huh? Velký zasraný úkol.}
{201}{}{Oh, jééé, ty jsi mùj hrdina. A teï odprejskni.}

# 3. What, you too good for me or what?
{300}{}{Nažïár?}
{301}{}{Víš, že tam je tahle rozkošná blondýnka...}
{302}{}{Co, jsi moc dobrý na to, aby si se mnou mluvil?}
{303}{}{Øekni nìco. Cokoli!}

# 4. Prick
{400}{}{Èuráku.}
{401}{}{Svinì.}
{402}{}{Parchante.}
{403}{}{Ano, pokraèuj idiote.}
{404}{}{Doufám, že už nikdy nebudu mít to "potìšení" setkat se znovu s takovým kreténem.}
{405}{}{Tenhle ptáèek potøebuje nìjaké vìtrové bonbóny, táhne mu z huby jak z kanálu.}
{406}{}{Kurvo.}

# 5. Nothing
{500}{}{Rozpaèitì se na tebe podívala.}
{501}{}{Oèividnì neví co øíct.}

# 6. Porn Star
{600}{}{Ráda bych si ho vzala do postele a zahrála bych si "míèové hry".}
{601}{}{Mohla bys mì s ním nìkdy spojit?}
{602}{}{Hmmm...}
{603}{}{Mohl bys mì s ní nìkdy spojit?}
{604}{}{Opravdu bych si s ní rád zašukal.}
{605}{}{Mám *nejvìtší vìc* na píchání žen, ale je mi líto, nic neøeknu.}
