# Tento soubor pøeložil Radim "HIGHTOWER" Brix , hightower@angelfire.com
{100}{}{Vidíš zuøivé boxerské fanoušky. }

# examine
{150}{}{Vidíš divokého a odvázaného muže. Kvùli nìèemu strašnì vyøvává.}
{151}{}{Vidíš rozzuøeného boxerského fanouška. Øve a žádá si krev.}
{152}{}{Vidíš divokou a odvázanou ženu. Mùže si vyøvat hlasivky, ale není jí rozumìt.}
{153}{}{Vidíš rozzuøenou boxerskou fanynku. Øve a žádá krev.}

# 1. FLOAT DIALOGUES [FAN=MALE, PC NOT A PRIZEFIGHTER]
{200}{}{Jooooooooooo!}
{201}{}{::øev:: ::buèení:: ::øev::}
{202}{}{Zabij ho, }
{1202}{}{!}
{203}{}{Jsi nejlepší, }
{1203}{}{!}
{204}{}{Dostaò ho, }
{1204}{}{!}
{205}{}{Joooo! Nandej mu to!}
{206}{}{}
{1206}{}{ je NEJLEPŠÍ. NEJLEPŠÍ.}
{207}{}{}
{1207}{}{!!!}
{208}{}{}
{1208}{}{, ty jsi ale chlap!}
{209}{}{}
{1209}{}{ je nejlepší boxerský šampión, kterého jsem kdy vidìl.}
{210}{}{}
{1210}{}{ taky je opravdu pohotový. Opravdu ví jak nìkoho poranit.}
{211}{}{}
{1211}{}{ má starost o své fanoušky. Nezabíjí je jako ostatní boxeøi.}
{212}{}{}
{1212}{}{ je hoooodnì obratný.}
{213}{}{}
{1213}{}{ je hoooodnì odvážný.}
{214}{}{Miluji }
{1214}{}{ Iiiiaaaaaaaaaa!}
{215}{}{::vøískot:: ::vøískot::}
{216}{}{}
{1216}{}{ je laskavý a vychovaný. Tohle je to co mi øekl minulou noc.}

# 2. FLOAT DIALOGUES [FAN=MALE, PC = FEMALE OR MALE PRIZEFIGHTER]
{250}{}{}
{1250}{}{, ty jsi ale chlap!}
{251}{}{}
{1251}{}{ taky je opravdu pohotový. Opravdu ví jak nìkoho poranit.}
{252}{}{}
{1252}{}{ má starost o své fanoušky. Nezabíjí je jako jiní boxeøi.}
{253}{}{Slyším }
{1253}{}{ byl skoro neznámý, døív než zaèal boxovat v New Reno.
 Záhadný! Vražedný!}
{254}{}{O mùj Bože! }
{1254}{}{! Dej mi autogram!}
{255}{}{Dej mi ránu! Dej mi ránu! Budu vykládat svým dìtem, že jsi mi dal ránu!}
{256}{}{Jsi nejlepší, }
{1256}{}{! Pošli ho do pekla!}
{257}{}{Zabij ho, }
{1257}{}{!}
{258}{}{Jsi nejlepší, }
{1258}{}{!}
{259}{}{Dostaò ho, }
{1259}{}{!}
{260}{}{Anooo! Nandej mu to!}
{261}{}{}
{1261}{}{, jsi NEJLEPŠÍ. NEJLEPŠÍ.}
{262}{}{}
{1262}{}{!!!}
{263}{}{Jeeeaaaaahhhhh!}
{264}{}{::øev:: ::buèení:: ::øev::}
{265}{}{}
{1265}{}{ je nejlepší šampión v boxu jakého jsem kdy vidìl.}
{266}{}{}
{1266}{}{, jsi nejhouževnatìjší žena na svìtì!}
{267}{}{Jsi houževnatìjší než Robbin Givens!}
{268}{}{}
{1268}{}{, ty jsi ale žena!}
{269}{}{}
{1269}{}{ taky je opravdu pohotová. Opravdu ví jak nìkoho poranit.}
{270}{}{}
{1270}{}{ má starost o své fanoušky. Nezabíjí je jako jiní boxeøi.}
{271}{}{Slyším }
{1271}{}{ byl skoro neznámá, døíve než zaèala boxovat v New Reno.}
# 3. FLOAT DIALOGUES [FAN=FEMALE, PC = PRIZEFIGHTER]
{280}{}{Polibek pro štìstí?}
{281}{}{}
{1281}{}{, ty jsi ale chlap!}
{282}{}{}
{1282}{}{ je opravdu zruèný.}
{283}{}{}
{1283}{}{ má postavu jako tank!}
{284}{}{}
{1284}{}{ taky je opravdu pohotový. Opravdu ví jak nìkoho poranit.}
{285}{}{}
{1285}{}{ má starost o své fanoušky. Nezabíjí je jako jiní boxeøi.}
{286}{}{Slyším }
{1286}{}{byl skoro neznámý, døív než zaèal boxovat v New Reno. Obdivuhodný! Vražedný!}
{287}{}{O mùj Bože! }
{1287}{}{! Podepiš se mi!}
{288}{}{Dej mi ránu! Dej mi ránu! Budu vykládat svým dìtem, že jsi mi dal ránu!}
{289}{}{Jsi nejlepší }
{1289}{}{! Pošli ho do pekla!}
{290}{}{Zabij ho, }
{1290}{}{!}
{291}{}{Jsi nejlepší, }
{1291}{}{!}
{292}{}{Dostaò ho, }
{1292}{}{!}
{293}{}{Anooo! Nandej mu to!}
{294}{}{}
{1294}{}{, jsi NEJLEPŠÍ. NEJLEPŠÍ.}
{295}{}{}
{1295}{}{!!!}
{296}{}{Aiiiieeeeeeeee!}
{297}{}{::vøískot:: ::vøískot::}
{298}{}{}
{1298}{}{ je nejlepší boxerský šampión jakého jsem kdy vidìl.}
{299}{}{}
{1299}{}{, jsi nejhouževnatìjší žena na svìtì!}
{300}{}{Jsi houževnatìjší než Robbin Givens!}
{301}{}{}
{1301}{}{, ty jsi ale žena!}
{302}{}{}
{1302}{}{ taky je opravdu pohotová. Opravdu ví jak nìkoho poranit.}
{303}{}{}
{1303}{}{ má starost o své fanoušky. Nezabíjí je jako jiní boxeøi.}
{304}{}{Slyším }
{1304}{}{ byl skoro neznámá, døíve než zaèala boxovat v New Reno. Je opravdu obdivuhodná!}

# 4. CLICK DIALOGUES [FAN=FEMALE OR MALE, PC NOT A PRIZEFIGHTER]
{320}{}{ zabije každého, kdo se mu postaví do cesty!}
{321}{}{ je NEJLEPŠÍ. NEJLEPŠÍ.}
{322}{}{!!!}
{323}{}{ je muž!}
{324}{}{ je nejlepší boxerský šampión, jakého jsem kdy vidìl.}
{325}{}{ taky je opravdu pohotový. Opravdu ví, jak nìkoho poranit.}
{326}{}{ má starost o své fanoušky. Nezabíjí je jako jiní boxeøi.}
{327}{}{ je hoooodnì obratný.}
{328}{}{ je laskavý a vychovaný. Tohle je to co mi øekl minulou noc.}

# 5. CLICK DIALOGUES [FAN=MALE, PC = PRIZEFIGHTER]
{350}{}{}
{1350}{}{, ty jsi ale muž!}
{351}{}{Doma mám trochu tvého potu schovaného v láhvi.}
{352}{}{O mùj Bože! }
{1352}{}{! Podepiš se mi!}
{353}{}{Dej mi ránu! Dej mi ránu! Budu vykládat svým dìtem, že jsi mi dal ránu!}
{354}{}{Jsi nejlepší }
{1354}{}{! Pošli ho do pekla!}
{355}{}{Jsi nejlepší, }
{1355}{}{!}
{356}{}{Jdi a dostaò ho, }
{1356}{}{!}
{357}{}{}
{1357}{}{, jsi NEJLEPŠÍ. NEJLEPŠÍ.}
{358}{}{}
{1358}{}{!!!}
{359}{}{Jeeeaaaaahhhhh!}
{360}{}{}
{1360}{}{, je nejlepší boxerský šampión jakého jsem kdy vidìl.}
{361}{}{}
{1361}{}{, opravdu víš jak nìkoho poranit.}
{362}{}{}
{1362}{}{, opravdu máš starost o své fanoušky. Nezabíjíš je jako jiní boxeøi.}
{363}{}{Slyšel jsem, že jsi byl neznámý, døív než jsi zaèal boxovat v New Renu. Odkud jsi?}
{364}{}{}
{1364}{}{, jsi nejhouževnatìjší žena na svìtì!}
{365}{}{Jsi houževnatìjší než Robbin Givens!}
{366}{}{}
{1366}{}{, ty jsi ale žena!}

# 6. CLICK DIALOGUES [FAN=FEMALE, PC = PRIZEFIGHTER]
{380}{}{Polibek pro štìstí?}
{381}{}{}
{1381}{}{, ty jsi ale muž!}
{382}{}{}
{1382}{}{, jsi hoooodnì obratný.}
{383}{}{::Když s ní zaèneš mluvit, tak úplnì omdlévá::}
{384}{}{Doma mám trochu tvého potu schovaného v láhvi.}
{385}{}{Panebože! }
{1385}{}{! Podepiš se mi prosím tì!}
{386}{}{Dej mi ránu! Dej mi ránu! Budu vykládat svým dìtem, že jsi mi dal ránu!}
{387}{}{Jsi nejlepší }
{1387}{}{! Pošli ho do pekla!}
{388}{}{Zabij ho, !}
{1388}{}{!}
{389}{}{Ty jsi nejlepší, }
{1389}{}{!}
{390}{}{Dostaò ho, }
{1390}{}{!}
{391}{}{.}
{1391}{}{, ty jsi NEJLEPŠÍ. NEJLEPŠÍ.}
{392}{}{}
{1392}{}{!!!}
{393}{}{Aiiiieeeeeeeee!}
{394}{}{}
{1394}{}{, jsi nejlepší boxerský šampión jakého jsem kdy vidìl.}
{395}{}{}
{1395}{}{, opravdu víš jak nìkoho poranit.}
{396}{}{}
{1396}{}{, opravdu máš starost o své fanoušky. Nezabíjíš je jako jiní boxeøi.}
{397}{}{Slyšel jsem, že jsi byl neznámý, døív než jsi zaèal boxovat v New Renu. Odkud jsi?}
{398}{}{}
{1398}{}{, jsi nejsilnìjší žena na svìtì!}
{399}{}{Jsi tvrdší než Mike Tyson!}
{400}{}{}
{1400}{}{, ty jsi ale žena!}
