# Tento soubor pøeloil Radim "HIGHTOWER" Brix , hightower@angelfire.com
{100}{}{Vidíš boxera.}

# examine
# black
{150}{}{Vidíš velkého svalnatého èernocha. Vypadá jako kdy právì dokonèil svou "práci".}
{151}{}{Vidíš velkého èernocha. A tím myslím OBROVSKÉHO.}
{152}{}{Vypadá jako kdy právì dokonèil svou "práci".}
{153}{}{Málem sis ho spletl s malou horou.}
{154}{}{Je obrovskı. Strašnì obrovskı.}
{155}{}{Bezzubì se na tebe šklebí.}
{156}{}{Vypadá jako kdy právì dokonèil svou "práci".}
{157}{}{Málem sis ho spletl s malou horou.}
{158}{}{Je obrovskı. Strašnì obrovskı.}
{159}{}{Bezzubì se na tebe šklebí.}
# generic
{160}{}{Mluví s neviditelnım protivníkem a bruèí rùzné vıhruky po okolí.}
{161}{}{Momentálnì vypadá zmatenì, jako kdyby zapomnìl, kdo je, poté se usmìje
 a poškrábe se na hlavì.}
{162}{}{Dìlá døepy.}
# white
{163}{}{Vidíš obrovského bílého chlapa. Jeho ruce vypadají jako kmeny stromu.}
{164}{}{Vidíš velkého svalnatého bìlocha. Rùznì se prohıbá a pøitom si nadává.}
{165}{}{Vidíš velkého svalnatého bìlocha. Dívá se na tvojí hlavu jako by to byl boxovací pytel.}
{166}{}{Mluví s neviditelnım protivníkem a bruèí rùzné vıhruky po okolí.}
{167}{}{Momentálnì vypadá zmatenì, jako kdyby zapomnìl, kdo je, poté se usmìje
 a poškrábe se na hlavì.}
{168}{}{Dívá se na tvoji hlavu jako by to byl boxovací pytel.}

# random float
{200}{}{Hffff}
{201}{}{Hrggg}
{202}{}{::Napnutí::}

# player has power armor or is prizefighter
{203}{}{::Boxer se na tebe dívá s vystrašenıma oèima::}
{204}{}{AAAAAnnno, pane?}
{205}{}{Mùu si pùjèit nìjaké vìci?}
{206}{}{Nepotøebuješ sparingpartnera?}
{207}{}{Uf-huh.}
{208}{}{::Stupidnì pøikyvuje na všechno co øekneš::}
{209}{}{Ty jsi vysoká osoba. Já jsem malı.}
{210}{}{Ty jsi robustní. Já jsem slabı.}
{211}{}{Jsem hladovı.}

# talk female
{212}{}{Nerad mluvím.}
{213}{}{Hezky voníššš.}
{214}{}{Voníš jako moje máma.}
{215}{}{Dost bylo mluvení. Je èas jít do postele.}
# talk shared
{216}{}{::Bezzubı smích::}
{217}{}{::Škrábání se::}
{218}{}{::Napnutí::}
{219}{}{Bruèet}
# talk male
{220}{}{Chceš se mnou bojovat?}
{221}{}{Pojï blázne pojï blázne.}
{222}{}{Fajn pokus, fajn pokus.}
{223}{}{Dostals kritickı zásah.}
{224}{}{Bojuješ jako hovno které leze z prdele!}
{225}{}{Potøebuji sparing partnera.}
{226}{}{Ty malá osobo.}
{227}{}{Nemám rád mluvení.}

# boxing boxers messages

# punch
# hit noise
{300}{}{Ernhhh}
{301}{}{Ufff}
{302}{}{Hrghhh}
{303}{}{Nfff}
{304}{}{Hrggg}
{305}{}{Ooou}

# dodge
{310}{}{To bylo moc pomalé!}
{311}{}{To nebylo do tváøe!}
{312}{}{Boxuješ jako moje nemocná babièka!}
{313}{}{Neboxuj pod pás!}
{314}{}{Nejsi špatnı.}
{315}{}{To je všechno, co umíš?}

# knock down
{320}{}{A zùstaò leet!}
{321}{}{Knokautoval jsi to hovno!}
{322}{}{Kdo je tvùj otec?}
{323}{}{Jestli zemøe, tak a zemøe.}

{330}{}{Mohl by bıt soutìící!}
{331}{}{Jak by mohl takovı... geggghhh...}
{332}{}{*Huuuuurrrrllllll*}
{333}{}{Ooo, ta boles...}
{334}{}{Myslím, e si tady ještì chvilku poleím.}
{335}{}{Bolest ne, bolest ne, bolest ne...}

# punching
{340}{}{Tumáš!}
{341}{}{Chceš nìco z tohodle?!}
{342}{}{Dìvko!}
{343}{}{A teï jsi mùj.}
{344}{}{Zelené barety eru ke snídani.}
{345}{}{Huaaaaaaa.}
{346}{}{A nyní zemøeš.}
{347}{}{SUPER... NUKLEÁRNÍ... TORNÁDO... PÌST...}

# taunt
{350}{}{Adriane! Adriane!}
{351}{}{Padáš na zem!}
{352}{}{Udìlám z tebe dìvku...}
{353}{}{Musím tì zastavit.}
{354}{}{Bojuješ jako vandrák!}
{355}{}{Nemáš ádnou odvahu!}
{356}{}{Jsi flákaè! Flákaè!}
{357}{}{Zmlátím tì jako prašivého psa...}

# corner
{360}{}{ádná odveta!}
{361}{}{Dáváš rány jako motıl...}
{362}{}{Dr ruce nahoru...}
{363}{}{Zùstaò ostraitı!}
{364}{}{Bojuješ jako hovno, které leze z prdele!}
{365}{}{Dostals kritickı zásah!}
{366}{}{Rozsekej mì, Micku.}
{367}{}{Pamatuj, ádné rány!}
{368}{}{Vidìl jsem tøi z nich!}