#tento soubor pøeložil Vladimir "SIR QWERTY" Sojka - http://qwerty.moje.cz
# QUICK LOOK
{100}{}{Vidíš vyhazovaèe.}

# LOOK
{150}{}{Vidíš vyhazovaèe. Fakt VAZBA.}
{151}{}{Vidíš vyhazovaèe. Vypadá obrovsky. A k tomu ještì naštvanì. Grrrau !.}
{152}{}{Vidíš vyhazovaèe. Podezøívavì si tì prohlíží.}
{153}{}{Vidíš vyhazovaèe. Až doteï sis myslel, že jenom mutanti jsou TAKHLE velcí.}

# 1. FLOAT DIALOGUE: POWER ARMOR
{200}{}{Eh... budete si muset sundat to brnìní... vlastnì, no nevadí.}
{201}{}{Eh, pane... nebo sleèno... to brnìní tady nemùžete ...vlastnì asi jo.}
{202}{}{Pane... sleèno... tohle nemùžete nosit v kasinu... eeh, jenom pokud vážnì chcete.}

# 2. FLOAT DIALOGUE: MALE, MADE MAN, SAME CASINO, SNEAK
{205}{}{Eh, proè se tady tak KRADETE, pane?}
{206}{}{Eh, hledáte snad nìco, pane?}

# 3. FLOAT DIALOGUE: FEMALE, MADE MAN, SAME CASINO, SNEAK
{210}{}{Eh, proè se tady tak plížíte, sleèno?}
{211}{}{Eh, hledáte snad nìco, sleèno?}

# 4. FLOAT DIALOGUE: MALE, MADE MAN, SAME CASINO, NIGHT
{215}{}{Dobrý veèer, pane.}
{216}{}{`brej veèír, pane.}

# 5. FLOAT DIALOGUE: FEMALE, MADE MAN, SAME CASINO, NIGHT
{220}{}{Dobrý veèer, sleèno.}
{221}{}{`brej veèír, sleèno.}

# 6. FLOAT DIALOGUE: MALE, MADE MAN, SAME CASINO
{225}{}{Dobrý den pøeji, pane.}

# 7. FLOAT DIALOGUE: FEMALE, MADE MAN, SAME CASINO
{230}{}{Dobrý den pøeji, sleèno.}

# 8. FLOAT DIALOGUE: MALE, MADE MAN, NOT SAME CASINO
{235}{}{Myslím, že jste nevstoupil do toho správného kasina, pøíteli.}
{236}{}{Mìl bys radìji odejít. Hned.}
{237}{}{Tohle není místo, kde bys mìl hazardovat se svým životem. Radìji odejdi.}

# 9. FLOAT DIALOGUE: FEMALE, MADE MAN, NOT SAME CASINO
{240}{}{Ty èubko, lezeš do špatnýho kasina.}
{241}{}{Radši odejdi. Hned.}
{242}{}{Tohle není místo pro hazardování se svým životem. Radši odejdi.}

# 10. FLOAT DIALOGUE: MALE, PRIZEFIGHTER/PORN STAR (ARMED)
{245}{}{Je mi to líto pane, ale tu zbraò budete muset dát pryè.}

# 11. FLOAT DIALOGUE: FEMALE, PRIZEFIGHTER (ARMED)
{250}{}{Je mi to líto sleèno, ale tu zbraò budete muset dát pryè.}

# 12. FLOAT DIALOGUE: PORN STAR, FEMALE (ARMED)
{255}{}{Do tohohle kasina nemùžeš se zbranìmi, zlato. He-he... Už tak jsi dost smrtící.}

# 13. FLOAT DIALOGUE: PORN STAR, FEMALE (SNEAK)
{260}{}{S takovouhle figurou se nikam neproplížíš, zlato.}

# 14. FLOAT DIALOGUE: MALE, NO REP (ARMED)
{265}{}{Radši bys mìl tu zbraò schovat, burane.}

# 15. FLOAT DIALOGUE: MALE, NO REP (SNEAK)
{270}{}{Hej burane, pøestaò se tu tak zasranì plížit.}

# 16. MYRON, MORDINO
{275}{}{Hej, hej... Myrone! Už jsem tì dlouho nevidìl vylízt z laboratoøe. Vypnuli ti elektriku nebo co?}
{276}{}{Jdeš vyzkoušet nìjaký nový 'zboží', Myrone?}
{277}{}{Hej! Pojï dovnitø, Myrone.}

# 17. MARCUS
{280}{}{Mutantùm vstup zakázán. Musí poèkat venku.}
{281}{}{Uvaž si svýho mutantskýho kámoše venku.}
{282}{}{Tu mutantskou vobludu tu nechci.}

# 18. ROBOBRAIN
{285}{}{Droidùm vstup zakázán.}
{286}{}{Droidy neobsluhujeme.}
{287}{}{Žádní droidi. Musí poèkat venku.}

# 19. CLICK DIALOGUES: MADE MAN, SAME CASINO
{290}{}{Vítejte v kasinu, pane.}
{291}{}{Jako doma, pane.}
{292}{}{Dneska žádné problémy, pane.}
{293}{}{Máte nìjaký problém pane? Nebo jenom procházíte?}
{294}{}{Tom Hill se nechá porouèet.}
{295}{}{Pøimluvíte se za mì u šéfa?}
{296}{}{Vítejte v kasinu, sleèno.}
{297}{}{Jako doma, sleèno.}
{298}{}{Dneska žádné problémy, sleèno.}
{299}{}{Máte nìjaký problém sleèno? Nebo jenom procházíte?}

# 21. CLICK DIALOGUE: MALE, PRIZEFIGHTER/PORN STAR
{310}{}{Vítejte v kasinu, pane}
{311}{}{Jako doma, pane.}
{312}{}{Kdy máte pøíští zápas, pane?}

# 22. CLICK DIALOGUE: FEMALE, PRIZEFIGHTER
{315}{}{Vítejte v kasinu, sleèno.}
{316}{}{Jako doma, sleèno.}
{317}{}{Kdy máte další zápas, sleèno?}

# 24. CLICK DIALOGUE: FEMALE, PORN STAR
{320}{}{Kdy se u mì hodláš zastavit?}
{321}{}{Vítej v kasinu! Zatanèíš si dnes veèer?}
{322}{}{Vypadáš skvìle, puso.}
{323}{}{Lady Štìstìna zaène brzo žárlit, pokud sem budeš dál chodit.}
{324}{}{Øíká se, že Tommy the Balls ti chce udìlit soukromou audienci.}

# 25. CLICK DIALOGUE: MALE, NO REP
{330}{}{Kasino je vevnitø. Nemluv na mì.}
{331}{}{Kasino je vevnitø. VEVNITØ. Blbý divoši.}

# 26. CLICK DIALOGUE: FEMALE, NO REP (CUTE/UGLY)
{335}{}{Jdi si vejrat na nìkoho jinýho, køupane.}
{336}{}{Kasino je vevnitø. VEVNIØ. Divoši blbý.}
{337}{}{Nehledám zrovna žádnýho vidláka. Padej.}
{338}{}{Vystøel, otrapo. Mám práci.}
{339}{}{Jdi votravovat nìkoho vožralejšího, ksichte.}

# 28. FLOAT DIALOGUE: FLAG: ENCLAVE DESTROYED IS TRUE
{345}{}{Nesmím se vykecávat pøi práci, ale jsem rád, ze Enklávì koneènì nìkdo nakopal prdel.}
{346}{}{Jsi správnej chlap, divochu. Teï si odpoèin od toho všeho zachraòování svìta a užívej si.}
{347}{}{Slyšel jsem, že se po tobì shání Tommy the Balls. Dávej si bacha.}

# 29. CLICK DIALOGUE: FLAG: ENCLAVE DESTROYED IS TRUE
{350}{}{Musíš mít sakra nìjakou odvahu, když jsi vymlátil celou Enklávu.}
{351}{}{Soudím, že zrušit celou Enklávu tímhle zpùsobem vyžadovalo víc odvahy, než má celý New Reno dohromady.}
{352}{}{Znièením Enklávy se z tebe stal skoro stejnej bourák jako je Tommy the Balls.}
{353}{}{Nesmím se vybavovat pøi práci, ale teší mì, že Enklávì koneènì nìkdo nakopal prdel.}
{354}{}{Fakt si tì vážím. Odpoèiò si od zachraòování svìta a užij si trochu srandy.}
{355}{}{Teda takový nebezpeèí v Enklávì... jak se øíká - to tì fakt muselo asi svìdìt na koul...  no tak tam teda asi zrovna né, ale urèitì víš jak to myslím.}
{356}{}{Poèítám, že zrušit celou Enklávu tímhle zpùsobem vyžadovalo víc odvahy, než má celý New Reno dohromady.}
{357}{}{Myslíš, že by ses mohla zahazovat s èlovìkem jako jsem já? Nejsem sice Superman, ale jsem taky silnej a mám dobrý srdce.}

# 30. FLOAT/CLICK DIALOGUE: LENNY
{360}{}{Jestli ten ghoul pøijde sem, chcípne podruhý.}
{361}{}{Ten ghoul zùstane venku.}
{362}{}{Ghouly sem nepouštíme. Odveï ho zpátky do Gecka, kam všechna tahle verbež patøí.}
