#tento soubor pøeloil Vladimir "SIR QWERTY" Sojka - http://qwerty.moje.cz
# quick look
{100}{}{Vidíš hazardního hráèe.}

# examines
{150}{}{Vidíš hazardního hráèe. Vypadá unavenì.}
{151}{}{Vidíš hazardního hráèe. V oèích se mu zlatì blıská.}
{152}{}{Vidíš hazardního hráèe. Má hlavu v dlaních.}
{153}{}{Vidíš hazardního hráèe. Vypadá trošku nakropenì.}
{154}{}{Vidíš hazardního hráèe. Zamourá tvım smìrem a pak se vypotácí ven.}
{155}{}{Vidíš hazardního hráèe. Snaí se upoutat pozornost servírky.}
{156}{}{Vidíš hazardní hráèku. Vypadá unavenì.}
{157}{}{Vidíš hazardní hráèku. V oèích má zlatı lesk.}
{158}{}{Vidíš hazardní hráèku. Má hlavu v dlaních.}
{159}{}{Vidíš hazardní hráèku. Vypadá pøiopile.}
{160}{}{Vidíš hazardní hráèku. Zamourá tvım smìrem a pak se vypotácí ven.}
{161}{}{Vidíš hazardní hráèku. Snaí se upoutat pozornost servírky.}

# float
{200}{}{::Tleská::}
{201}{}{::Raduje se::}
{202}{}{Tak se na ty bastardy v Enklávì musí! Jen tak dál!}
{203}{}{Tak se na Enklávu musí, }
{204}{}{Gratuluju ke znièení Enklávy, }
{205}{}{Gratuluju ke znièení Enklávy, }
{206}{}{A jéiš. Jdi mi z cesty.}
{207}{}{Jenom pøi pohledu na nìj... na ní... na to... a u je to *cokoliv*, mì mrazí v zádech.}
{208}{}{Myslíš, e nìkoho ušetøí?}
{209}{}{Má teda pekelnı maso. Eh, ještì k tomu pod brnìním.}
{210}{}{Radši se vyhni.}
{211}{}{Mluvím o nebezpeènì vypadajícím...}
{212}{}{*Gulp*}
{213}{}{Myslím, e tvùj kámoš pan Robotík si mì skenoval.}
{214}{}{Myslím, e ten pochodující tank nám ukázal tváø smrti. Padám odsud.}
{215}{}{Slyšel jsem, e ta vìc vèera vyøídila tøi ranaøe.}
{216}{}{Jenom pohled na nìj mi rozklepe kolena.}
{217}{}{Myslíš, e nìkoho ušetøí?}
{218}{}{Tomu chlápkovi se radši vyhni.}
{219}{}{Myslím, e se na mì díval.}
{220}{}{Myslim, e díky jemu jsem pohlédl smrti do úsmìvu. Padám odsud.}
{221}{}{Slyšel jsem, e vèera rozstøílel tøi ranaøe.}
{222}{}{A jéje. Jdi z cesty.}
{223}{}{Z pekla maso.}
{224}{}{Mluvím o nebezpeènì vypadajícím...}
{225}{}{*Gulp*}
{226}{}{Brutální Nikita.}
{227}{}{Jen pøi pohledu na ní mì mrazí v zádech.}
{228}{}{Myslíš, e nìkoho ušetøí?}
{229}{}{Myslím, e se na mì právì podívala.}
{230}{}{Myslím, e mi právì dala pohlédnout smrti do tváøe. Padám odsud.}
{231}{}{Slyšel jsem, e vèera zastøelila tøi ranaøe.}
{232}{}{Jeiš to je blb! Fakt totál.}
{233}{}{Nevypadáš moc drsnì, ty Vítìzi.}
{234}{}{Vsadil jsem na tebe a vyhrál 20 šlupek!}
{235}{}{Hej šampióne! Ten poslední zápas byl skvìlej!}
{236}{}{Vidìl jsem tì zápasit v ringu. Zatracenì dobrej pravej hák!}
{237}{}{Prohraješ? Vsadil jsem na tebe 30 šlupek.}
{238}{}{Kolik uzvedneš na bench-press?}
{239}{}{Kde trénuješ?}
{240}{}{Hele, dej si bacha na dímaèku. Má rád uši.}
{241}{}{Zaplatil bych ti panáka kdybych nevsadil všechny prachy na tvıho soupeøe a neprohrál je.}
{242}{}{Nevypadáte moc tvrdì, sleèno s levım hákem.}
{243}{}{Mùu vidìt tvoje bøišní svaly?}
{244}{}{Ty bláho. Koukni na tohle.}
{245}{}{Podíval by ses na *tohle*?}
{246}{}{::Brblá si poøád 'zatracenì, zatracenì'::}
{247}{}{VÌDÌL JSEM, e jsem se mìl dneska oholit.}
{248}{}{Pojï dát øeè, prcino.}
{249}{}{Všude se tu flákaj ti divoši!}
{250}{}{Kouknìte jakı má ten divoch nádobíèko.}
{251}{}{Tak tohle je nejlepší klisna mıho pasáka.}
{252}{}{Tak kvùli tıhle enskı bych se tøeba i vykoupal.}
{253}{}{Svojí zlatou ílu mám právì tady.}
{254}{}{Hobluj!}
{255}{}{Jdi na to!}
{256}{}{::Píská::}
{257}{}{Roztanoka?}
{258}{}{Zatracenìììììììì.}
{259}{}{Kdo vás tohle sleèinko nauèil?}
{260}{}{Moná e dneska veèer bude tancovat.}
{261}{}{Vidìls její poslední film? Rajcovní, èéèe, fakt RAJCOVNÍ.}
{262}{}{Omluvte mì. Musím jít do koupelny a em, chvilku si tam èesat vlasy.}
{263}{}{Chtìl bych bejt jejíma kalhotkama.}
{264}{}{Chtìl bych bejt jejím spodním prádlem.}
{265}{}{Rád bych pøivonìl k jejím kraáskùm.}
{266}{}{To je rajcovní lištièka.}
{267}{}{Zatracenì. Všechny ty zatáèky a já bez brzd.}
{268}{}{Juj, ahoj høebèe.}
{269}{}{Takovej samec a potøebuje sedlo? Zítra ráno jsem volná, fešáku.}
{270}{}{Copak dìláš potom, námoøníku?}
{271}{}{Smím si vyzkoušet tvé svaly?}
{272}{}{To je Browning v tvojí kapse nebo jsi rád, e mì vidíš?}
{273}{}{Nechceš ke mnì zaskoèit na sklenièku?}
{274}{}{Ráda bych se na tobì naveèeøela, co ty na to?.}
{275}{}{Nepotøebuješ paráka do pøíštího filmu?}
{276}{}{::Nepøítomnì zírá na tvé bicepsy::}
{277}{}{To je nìjakej druh pinballu, co za tebou poøád chodí?}
{278}{}{To je robo-pinball?}
{279}{}{Umí tvùj dìlat tvùj robot triky? Ehm... myslím kouzelné triky.}
{280}{}{To zní divnìjc ne liška ve skautu s kuøetem.}
{281}{}{Jedem jedéém.}
{282}{}{Teda moje dítì by potøebovalo novı botky...}
{283}{}{Zatracenı flákaèi...}
{284}{}{Zatracenì krám! U jsem mìl *53* babek}
{285}{}{Zasranı štìstí.}
{286}{}{Takovej kousíèek!}
{287}{}{Vyhrabu ten jackpot stùj co stùj.}
{288}{}{Já? Vyberu to do posledního halíøe. Mrkej.}
{289}{}{Všechno proti mnì.}
{290}{}{Štìstìna na mì sere z vejšky.}
{291}{}{Oh má Štìstìno, prosím nezraï mì.}
{292}{}{Bez šance.}
{293}{}{Mezi sázkama a poøádnì divokejma paøbama.}
{294}{}{Ještì takhle sázej a brzo budeš øikat krchovu 'mùj domov'.}
{295}{}{Èíšníèe, ještì šòaps!}
{296}{}{Vrchní, piš to tam hrábìma!}
{297}{}{Tahle brnda chutná... pøinejmenším prapodivnì.}
{298}{}{Tohle mì vánì dostává!}
{299}{}{To u jsem fakticky všechno prohrál?}
{300}{}{Štìstìna je nespolehlivá dìvka, zrovna tak jako moje tchınì.}
{301}{}{Nedávno tu asi procházeli otrokáøi.}
{302}{}{Teda co se dìje v tìch stájích za mìstem... to bych rád vìdìl.}
{303}{}{Další kolo mùe zaèít.}
{304}{}{Zatracenı Všudybylové, furt se tady flákaj...}
{305}{}{Skvìle, další pelešník.}
{306}{}{Sem samı prachy... kouknìte, teèou mi i z kapes.}
{307}{}{A úplnì umøu, tak budu poøádnì spát.}
{308}{}{Kdy paøim, tak paøim to co zrovna je a panáky si nalejvám a po vokraje...}
{309}{}{Èéèe, musim jít vymaèkat hada.}
{310}{}{Kruci, voni tu nechaj bejt úplnì kadıho.}
{311}{}{JO! Prosim sedmièku!}
{312}{}{Teda ty máš kurá.}
{313}{}{A kdo je velkej vítìz dneska veèír? Majk!}
{314}{}{Nedrkuj a pojï!}
{315}{}{Nìco tu mám a to je materiál... to je megastór, né koloniál.}
{316}{}{Takovı KECY!}
{317}{}{Prohrál jsem jen 60 šmrdlíkù... jene u za prvních pìt minut, to je to.}
{318}{}{Èervená 23! Toè to tam!}
{319}{}{50 frflákù na patnáctku èernou}
{320}{}{Chodí Pešek okolo, nedívej se na nìho...}
{321}{}{Takhle se musí na ty parchanty z Enklávy!}
{322}{}{Vdycky jsem vìdìl, e nás chtìl Prezident všechny povradit.}
{323}{}{Prezident byl naivu? Kdye byly poslední volby?}
{324}{}{Enkláva znièena? Dovol mi koupit ti panáka.}
{325}{}{Tak to je zpùsob, jak zlikvidovat Enklávu, }
{326}{}{Znièením Enklávy jsi z tohoto kasina udìlal mnohem lepší a bezpeènìjší místo pro naše dìti. Jak jen ti podìkujeme?}
{327}{}{Ty z Enklávy mì vdycky nechali bıt, ale jsem rád, e u je to za námi.}
{328}{}{Nemùu uvìøit, e Enkláva stále vedla válku po takové dobì. Tupci.}
{329}{}{Cítil jsem velké vyrušení... skoro jako kdyby stovka pekelnıch bastardù na ropné plošinì najednou zaøvalo v agónii a rázem utichlo.Divné.}
{330}{}{Gratuluji k rozmašírování Enklávy, }
{331}{}{Gratuluji k rozmašírování Enklávy, }
{332}{}{Hledáš svıho bráchu Robbyho? Jako teda Robota? Ále, nech to plavat.}
{333}{}{Promiòte. Stál jsem vám v cestì? Hnedle opustím mìsto.}
{334}{}{Promiòte, dıchal jsem váš vzduch? Moment, hned pøestanu.}
{335}{}{Nedivím se, e udìlali tak širokı futra. To asi kvùli vám.}
{336}{}{::Zaklepe na zbroj:: Haló? Je tam nìkdo?}
{337}{}{'Pozor, Will Robinson! Pozor, Will Robinson!' Hehe... Takovı dobrı vtip.}
{338}{}{Pìkné brnìní. Má to taky klimatizaci?}
{339}{}{Nepeèeš se v tom trochu?}
{340}{}{Mùu si tyhle hrací kostky otøít o vaše brnìní? Pro štìstí...}
{341}{}{Potratil jsi srdce, plechovko?}
{342}{}{Ah, dobrı den, pane... sleèno... nebo co vlastnì jste.}
{343}{}{Pozdravuj toho, kdo ti dal tuhle zbroj.}
{344}{}{Nìco není v poøádku, pane... sleèno... eh nebo co vlastnì jste?}
{345}{}{Jste náš novı vyhazovaè nebo prototyp chodícího hracího automatu?}
{346}{}{Ne, VÁNÌ ti nebudu mazat tvoje klouby.}
{347}{}{Umí se tvoje brnìní promìnit v raketu a vylítnout tisíc metrù vysoko? Jsem jen zvìdavı.}
{348}{}{Jó jó, taky tì zdravim - 'cink-vhrrrt-cink'.}
{349}{}{Jestli si tedy myslíš, e mì tvoje zbroj vystraší, tak teda jo.}
{350}{}{Ty musíš bıt jedna z tìch pøedváleènıch herních konzolí... PSX?}
{351}{}{Podívejte, nechci mít ádné problémy... Jsem tu jen na den.}
{352}{}{Podívejte, nechci mít ádné problémy...}
{353}{}{Promiòte, stál jsem vám v cestì? Hnedle odejdu z mìsta.}
{354}{}{Promiòte, dıchal jsem váš vzduch? Moment, hned pøestanu.}
{355}{}{Pozdravuj svıho šéfika.}
{356}{}{Uh...*gulp*...je nìco špatnì?}
{357}{}{Podívejte, nechci mít ádné problémy... Jsem tu jen na den.}
{358}{}{Podívejte, nechci mít ádné problémy.}
{359}{}{Tys prodavaè?}
{360}{}{Mùu koupit tvé obleèení? Myslím teï hned?}
{361}{}{JÁ VÌDÌL e jsem se mìl ráno oholit.}
{362}{}{Pojï na kus øeèi, prsatice.}
{363}{}{Pojï se se mnou kousek projít, beruško.}
{364}{}{Mrštná rajcka, co?}
{365}{}{Kvùli tobì bych se i vykoupal.}
{366}{}{Svojí zlatou ílu mám právì TADY.}
{367}{}{Roztanoka?}
{368}{}{Zatanèíme si veèer?}
{369}{}{Omluvte mne, musím jít do koupelny a em... trošku se uèesat.}
{370}{}{Chtìl bych bıt tvım spodním prádlem.}
{371}{}{Chtìl bych pøivonìt k tvım kalhotkám.}
{372}{}{Jsi fakt pìkná lištièka.}
{373}{}{Oprav mì, jestli se mılím drahoušku, ale nechceš mne políbit? Poøádnıho lomcováka?}
{374}{}{Tak tohle fakt eru.}
{375}{}{Víš co by na tobì opravdu dobøe vypadalo? Já.}
{376}{}{Tvoje kalhotky asi nebudou nejlepší vìc na svìtì, ale dost se tomu blíej.}

{503}{}{!}
{504}{}{! Jsi jednièka! Jsi NEJLEPŠÍ!}
{505}{}{! Seš k nezaplacení!}
{625}{}{!}
{630}{}{! Jsi jednièka! Jsi NEJLEPŠÍ!}
{631}{}{! Jsi k nezaplacení!}