#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
# 0. QUICK LOOK

# 0. LOOK
{150}{}{Vidíš vysokého mladíka. Je navleèenı v kùi a ovìšenı øetìzy.}
{151}{}{Vidíš Chrise Wrighta.}
{152}{}{Vidíš Chrise Wrighta. Vypadá znudìnı k smrti.}

# 1. FLOAT DIALOGUE: ENCLAVE DESTROYED IS TRUE (WTG)
{200}{}{Hej! }
{201}{}{Jedu, }
{202}{}{Skvìlı, }
{203}{}{::zdraví tì::}
{204}{}{::tleskání::}
{205}{}{::pískání::}

# 2. FLOAT DIALOGUE: POWER ARMOR (WTG)
{215}{}{Zajímalo by mnì, jak to s tím tvım brnìním dìláš na záchodì?}

# 3. FLOAT DIALOGUE: WARNING - PLAYER IS MADE MAN (WTG)
{220}{}{Nazdárek, }
{221}{}{Zatracenej hic, ejo, }
{222}{}{Zdárec, }

# 4. FLOAT/CLICK (DAD IS DEAD) (WTG)
{230}{}{Poøád nemùu uvìøit, e je táta mrtvej. Je toho tolik, co jsem mu chtìl øíct...}

# 5. FLOAT/CLICK [MALE, MADE MAN, FA = WRIGHT, NORM] (WTG)
{235}{}{Odpal.}
{236}{}{Odpal. Myslím to vánì.}
{237}{}{Nemám ti co øíct.}

# 6. INTRO (NORMAL) (WTG)
{245}{}{Jo?}
{246}{}{Hej! Jak to jde, }
{1246}{}{? Všichni se k tobì chovají dobøe? Potøebuješ nìco?}
{247}{}{Hej, jsem ti vdìènej, e jsi zjistil, kdo zabil Richarda, }
{248}{}{. Jsem tvùj velkej dluník, a Wrightova rodina vdycky svoje dluhy platí. Co pro tebe mùu udìlat?}
{249}{}{Mattah. Chlap je Mattah!}
{250}{}{gdo ty?}
{251}{}{Kliï se}
{252}{}{Kdo seš?}
{253}{}{Vlastnì ano. Hledám práci. Nabírají Wrightovi?}
{254}{}{Hele, potkal sem tvou matinu.}
{255}{}{Mùeš mi øíct nìco o Richardovi?}
{256}{}{Nic, díky. Sorry, e jsem otravoval.}
{257}{}{Mùeš mi øíct nìco o rodinì Wrigtù?}

# 7.  RETARD (6)
{265}{}{Zmizni, postiáku. Nemám èas poslouchat tvoje hıkání.}

# 8.  WHO ARE YOU? (6)
{275}{}{Já jsem Chris. Chris Wright. Z rodiny  Wrightù.}
{277}{}{Rodina Wrightù? To je jako kdo?}
{278}{}{Chris Wright jo? Hele, potkal jsem tvou matku.}
{279}{}{Mùeš mi øíct, co se stalo tvojemu bráchovi Richardovi?}
{280}{}{Nic, díky. Sorry e sem otravoval.}

# 9. FAMILY WRIGHT? WHO'S THAT? (8, 10, 12)
{290}{}{Tys neznáš rodinu Wrightovıch? Musels bıt v poušti òák moc dlouho. Rodina Wrightova Je nejvìtší kriminální rodina v  Renu. Brzo budeme šéfovat celımu mìstu.}
{291}{}{Fakt? Zní mi to, e Wrightovi maj všecky esa. Nepøibíraj lidi?}
{292}{}{Nóóó, mì pøipadá, e jsou nejslabší rodina...Tím myslím e kšeftujou jenom s chlastem, nemají ani kasíno ani fet, a do kupy je jich mnohem míò ne v ostatních rodinách.}
{293}{}{Kdy u mluvíme o rodinì, potkal jsem tvoji matku.}
{295}{}{Fakt? Zajímavı...no, já bych mìl padat.}
{296}{}{Wrigtovi jsou nevìtší rodina ve mìstì. Brzy tady budeme vládnout.}

# 10. QUESTIONS (15, 16, 17, 18, 19, 20, 22, 25, 26, 28)
{305}{}{Jako co?}
{306}{}{Mùeš mi øíct nìco o rodinì Wrightovıch?}
{307}{}{Pøibírají Wrightovi lidi?}
{308}{}{Pøednedávnem jsem potkal tvoji mámu. Fajn pani.}
{310}{}{Ne, ádné další otázky. Radši bych u mìl jít.}

# 11. INTRO (SLAVER) (WTG)
{315}{}{(Mladík se k tobì otoèil a prohlídl si tì od hlavy k patì. Jeho oèi se zastavily na tetování na tvém èele.) No. (Odrfkl si, potom ti plivnul na nohu.) Proè se nesnaíš bıt uiteènı a neslíeš to, otrokáøské prase?}
{316}{}{(Mladík se k tobì otoèil a prohlídl si tì od hlavy k patì.) No.(Odrfkl si, potom ti plivnul na nohu.) Proè se nesnaíš bıt uiteènı a neslíeš to, ty psí }
{317}{}{sraèko?}
{318}{}{Kopni ho botou, na kterou ti plivl.}
{320}{}{Vykašli se na nìj a nech ho bıt. Tentokrát. }

# 12. I'M LOOKING FOR A JOB . . . [GOOD RESPONSE] (6, 8, 9, 10)
{325}{}{No...já...teda, Wrightova rodina... moje rodina... by mohla mít volnı flek. 
Nic ti neslibuju, ale zajdi si do toho baráku na jih odtud. Najdi mıho bráchu Keitha 
a øekni mu, e tì posílám já. Jmenuju se Chris. Chris Wright.}
{326}{}{Uh, Wrightova rodina? To je kdo?}
{327}{}{Wright, jo? Potkal jsem tvou mámu.}
{329}{}{Díky.}
{330}{}{Díky. Mùu se tì na nìco zeptat?}

# 13. I'M LOOKING FOR A JOB . . . [BAD RESPONSE] (6, 8, 9, 10)
{335}{}{Nee... Vìtšinou nebereme lidi, kteøí nejsou z rodiny. Mùeš se zeptat táty,
 ale nejspíš øekne ne.}
{336}{}{Tak fajn.}

# 14. I RAN INTO YOUR MOM (NORMAL) (6, 9, 10, 11, 12)
{345}{}{Oh, sqìlı. Drela ti pøednášku?}
{346}{}{Tak trochu. Ty nemáš rád svoji matku?}
{347}{}{Ne. To nìkdy dìlává?}
{348}{}{Vlastnì ne. No, já musím jít. }

# 15. I RAN INTO YOUR MOM (INSULT) (9, 16)
{355}{}{Dìláš si *srandu?* Jestli jo, tak se ti ten fórek ani TROCHU nepovedl. Zkoušíš si nìco zaèínat s  Wrightovıma, chytráku?}
{356}{}{Zaèínat si nìco? Ne, jenom *dokonèit*.}
{357}{}{Ne, promiò. Tak jsem to nemyslel. Hele, Mám ještì nejakı otázky...}
{358}{}{Ne, vùbec ne. No, mìl bych jít. }

# 16. DO YOU NOT LIKE YOUR MOM? (14)
{365}{}{Ona se zkrátka nezajímá o vìci, co se dìjou kolem. Mám ji rád, ale obèas je slepá jako netopejr a blbá jako kráva.}
{366}{}{No, není to ani moc dlouho, vletìla nám tady do palírny a zlikvidovala tam celotıdenní práci! Mám ji rád, ale obèas je slepá jako netopejr  a blbá jako kráva.}
{367}{}{Ha-ha. A taky tak vypadá.}
{368}{}{Slepá? Jak to myslíš?}
{369}{}{Oh. No, já bych se chtìl zeptat ještì na nìco...}
{370}{}{Hmm. No, já pùjdu. }

# 17. WHAT DO YOU MEAN? (16)
{380}{}{Chodí kolem a blekotá o høešení a tak, ale ani neví, co vlastnì táta dìlá.
 Buï, anebo to ignoruje.}
{381}{}{A co tvùj táta dìlá?}
{382}{}{Hmmmm. No, já mám ještì nìjakı otázky...}
{383}{}{Zajímavı. No, já bych mìl padat. }

# 18. WHAT DOES YOUR DAD DO? (17)
{390}{}{Pálí chlast, prodává kvéry, mlátí lidí, kteøí s ním chtìjí vymrdat...typickı rodinnı záleitosti. Matka by byla nasraná,
 kdyby si všímala, co vlastnì dìláme . A zvláš, kdyby našla tady tu palírnu.}
{391}{}{Jak moc nasraná by byla?}

# 19. HOW PISSED? (18)
{400}{}{Asi dost nasraná, aby to tady rozkopala. Nejmíò. A pak by nám nadávala a nutila modlit se aspoò tıden.
  Heh.}
{401}{}{Zajímavı. No, ještì bych se chtìl na nìco zeptat.}
{402}{}{Hmmmmm. Díky. }

# 20. WHAT ABOUT RICHARD? (6, 8, 9, 10, 12)
{410}{}{Rik? No víš, našli ho jako jednoho ze zkrachovalejch feákù, mrtvıho v kanále. Myslíme si,
e ho nìkdo napumpoval drogama, dokud neumøel. }
{411}{}{'Nìkdo' mu dal moc? Jak víte, e se nepøedávkoval sám?}
{412}{}{Kdo si myslíte, e to udìlal?}
{413}{}{To je mi líto. Mám ještì nìjakı otázky...}
{414}{}{Hloupı. No, já musím jít. }

# 21. GAVE HIM TOO MUCH? (20)
{420}{}{Protoe byl èistej...Matka ho to nauèila. A jestli na to máš jinı názor, mùeme to spolu 
 vyøešit hned na místì.}
{421}{}{Tak jsem to nemyslel. Sorry.}
{422}{}{Nenech se zaslepit pøehnanou vírou ve svıho bráchu. Klidnì to mohl brát. Jet je dìsnì návykovej .}
{423}{}{Hele, chlapèe, jestli víš, co je pro tebe dobrı, pøestaneš zavírat oèi pokadı, kdy kolem projde nìjaká 
 nehezká skuteènost a kopne tì do prdele.}
{425}{}{Nestojím o problémy. Pùjdu. }

# 22. I'M SORRY. I DIDN'T MEAN IT LIKE THAT (21)
{435}{}{Jo, jo, jen si dej pozor. To jsou slova, kterı se nelíbí ádnımu Wrightovi, take je z huby radši nepouštìj, okej?}
{437}{}{Hele, chlapèe, nerej do mnì. Jestli víš, co je pro tebe dobrı, pøestaneš zavírat oèi pokadı, kdy kolem projde nìjaká 
 nehezká skuteènost a kopne tì do prdele.}
{438}{}{Sorry, bez uráky. Chtìl bych se ještì zeptat...}
{439}{}{Jasnı. Radši pùjdu. }

# 23. APOLOGY FAILED (15, 21, 22)
{445}{}{Odpal, nebudu se s tebou bavit.}
{446}{}{Poèkej, jenom jednu otázeèku...}
{447}{}{U jdu, u jdu. }

# 24. IMPLY RICH KEPT TAKING DRUGS (15, 21, 22, 23)
{455}{}{(Chris na tebe chvíli zíral, pak se na tebe vrhnul!)}
{456}{}{Take takhle, jo? NO FAJN, TAK POJÏ TY ZMRD---}

# 25. WHO DO YOU THINK DID IT? (20, 21)
{465}{}{Øekl bych Mordinové, buï nìkterej z jejich dealerù nebo pøímo jeden z Mordinovic famílije. Ti hajzlové mají tuny Jetu.}
{466}{}{Jasnı. Hele, ještì otázeèku...}
{467}{}{Kterı z dealerù?}
{468}{}{Aha. Tak já pùjdu. }

# 26. WHO DO YOU THINK SOLD IT? (25)
{475}{}{Mohl to bıt kterıkoli z nich: Poøezanej Jimmy J, ten zjizvenej zkurvysyn na rohu Panenskı ulice, nebo
 Renesco 'Rakeák,' ten posranej tchoø, co prodává Jet z tı svı pevnosti na West Side.}
{476}{}{Nìjací další dealeøi?}

# 27. WHO DO YOU THINK SOLD IT? (28)
{485}{}{Hej, kámo, DÍKY.}
{486}{}{Hej, dámo, DÍKY.}
{487}{}{Díky tobì víme, kdo zabil Rika a celá rodina Wrigtù ti dìkuje. A to nejsou ádnı malı díky, jasnı?}
{488}{}{Jasnı. Èau Chrisi. }

# 28. ANYBODY ELSE? (26)
{495}{}{Jules na zaèátku mìsta taky prodává Jet, ale vìtšinou prodává turistùm...pak je tady Malej Jeíš Mordino:
moh do Rika nacpat drogy, kdy byl Rik venku sám. Potuluje se kolem Desperáda.}
{497}{}{Poøezanej Jimmy J, Renesco Rakeák, Jules a Malej Jeíš...Podívám se na nì. Dík za info, Chrisi. }


# end lines
{1200}{}{! Nakopat Enklávì prdel!}
{1201}{}{! Seš boí!}
{1202}{}{!}
{1220}{}{. Na co se chystáš?}
{1221}{}{?}
{1222}{}{. Jak to jde?}
