#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
# 0. LOOK
{150}{}{Vidíš umaštìného mechanika.}
{151}{}{Vidíš jednoho z mechanikù.}
{152}{}{Vidíš unaveného mechanika. Kvùli  vrstvì oleje a špíny se jeho oblièej skoro nedá rozeznat.}

# 1. FLOAT OR CLICK DIALOGUES [POWER ARMOR] (WTG)
{200}{}{Do prdele. *Polk* Podívejte se, kdo pøišel.}
{201}{}{No, jestli pak to není pan Zkurvená Plechovka osobnì.}
{202}{}{Je nìkdo v tı vìci?}
{203}{}{Mùem ti nìco donıst? Pivo? Vodu?}
{204}{}{Doufám, e je všechno v poøádku, uh, pane...nebo madam. Kdokoli je tam uvnitø.}
{205}{}{A je špatnì cokoli, mùe za to T-Ray. Promluvil bych si s ním.}
{206}{}{To je nìjakı novı auto?}
{207}{}{Nechceme ádnı problémy.}
{208}{}{Moná hledáte T-Raye. Je vzadu.}

# 2. FLOAT/CLICK TEXT [PORN STAR/CHR > 5, FEMALE] (WTG)
{220}{}{No, ahóóój, krásná dámo. Zatracenì skvìlı pøedstavení.}
{221}{}{Wow. Nemíváme moc návštìvníkù. Co pro vás mùeme udìlat, sleèno }
{5221}{}{?}
{222}{}{Jak jsi dokázala dát si nohy tak pøes hlavu, kotì?}
{223}{}{Jsou ty kozy pravı? Mùu se pøesvìdèit?}
{224}{}{Mohl bych se vám podívat pod kapotu?}
{225}{}{A sakra. Tı špíny si nevšímejte.}
{226}{}{Hledáte novej talent? T-Ray je vzadu, take tam chodit nemusíte.}
{227}{}{Vìdìl jsem, e se mám osprchovat...}
{228}{}{Mám ti zkontrolovat olej? Haha.}
{229}{}{Chcete vidìt mojeho ochoèenıho ptáèka?}
{230}{}{::písk::}
{231}{}{Teda, mám chu postavit se do pozoru. My OBA se asi postavíme do pozoru. (sklopil pohled dolù)}
{232}{}{No ahój, sleèinko.}
{233}{}{Joj. Nemíváme moc návštìv. Co pro vás mùeme udìlat, sleèno?}
{234}{}{Hledáte nìkoho pro horkou lásku? T-Ray  je vzadu, take tam se obtìovat nemusíte.}

# 3. FLOAT/CLICK DIALOGUES [PRIZEFIGHTER] (WTG)
{245}{}{Vidìl jsem tì v ringu. Zatracenì skvìlı pravı háky.}
{246}{}{Budeš zase boxovat? Potøeboval bych vyhrát nìjaké peníze.}
{247}{}{Na zápasníka moc tvrdì nevypadáš.}
{248}{}{Kolik kilo uzvedneš?}
{249}{}{Kde tì trénovali?}
{250}{}{Bacha na dímaèku. ere uši.}
{251}{}{Chceš pivo? Vìtšinou si je šetøíme, ale pro tebe....}
{252}{}{T-Ray øíkal, e nejseš tvrdej,dám ti bùra, jestli mu jednu šlehneš.}
{253}{}{T-Ray øek, e máš hubu ze skla. Jestli s ním chceš mluvit, je vzadu.}
{254}{}{Ten dímaèka je sráè. Uh, ale já to neøek!}

# 4. FLOAT/CLICK DIALOGUES [MADE MAN] (WTG)
{265}{}{Doufám, e je všechno v poøádku, madam.}
{266}{}{Nechtìli jsme se vás dotknout, madam.}
{267}{}{Do prdele. *Polk* Podívejte se, kdo pøišel.}
{268}{}{Co pro vás mùeme udìlat, }
{5268}{}{?}
{269}{}{Mùem ti nìco donıst? Pivo? Vodu?}
{270}{}{A je špatnì cokoli, mùe za to T-Ray. Promluvil bych si s ním.}
{271}{}{Pozdravte svého šéfa od nás ode všech.}
{272}{}{Moná hledáte T-Raye. Je vzadu.}
{273}{}{Doufám, e je všechno v poøádku, pane.}
{274}{}{Nechtìli jsme se vás dotknout, pane.}

# 5. FLOAT OR CLICK DIALOGUES [CAR RECOVERED] (WTG)
{300}{}{Sorry za to nedorozumìní s auákem.}
{301}{}{Nevìdìli jsme, e je to auto vaše.}
{302}{}{Jo,  Highwayman není špatná kára, ale já bych mìl radši Omni.}
{303}{}{Nechcete prodat auto?}
{304}{}{Bì, namydlenı blesku, bì.}
{305}{}{Tády dády dááá...}
{306}{}{Highwayman je sladkı autíèko; v Chryslus rozhodnì vìdìli, jak je dìlat.}
{307}{}{T-Ray "pracuje" vzadu. Zatracenı lenoch.}
{308}{}{U je mi blbì z makání za T-Raye.}
{309}{}{T-Ray zase oèumoval moji starou.}
{310}{}{T-Ray chrápal s mojí sestrou. A mou matkou. A psem.}
{311}{}{T-Ray je nadrenìjší ne bık na tvrdolínu.}
{312}{}{T-Ray je vzadu. Urèitì chrápe, prase.}
{313}{}{Motor poøád jede.}
{314}{}{Vevnitø to smrdí, jako by tam nìkdo zakládal smetištì.}
{315}{}{Interiér smrdí jako gecko.}
{316}{}{Slušná kára, ale já bych mìl radši Omni.}
{317}{}{Highwayman má plnì analogovı systém, pøes 800 koòskıch sil, z nuly na sto pod jednu sekundu.}
{318}{}{Rychlı? Highwayman rozmaká z nuly na sto pod jednu sekundu!}
{319}{}{Highwayman má pøes osmset koòskıch sil, fakt.}
{320}{}{Máš tu nìco na práci?}
{321}{}{Je mi líto idiota, kterı nechal to auto jenom tak leet.}
{322}{}{Highwayman má plnì analogovı systém a ádnı poèítaèe..}

# 6. FLOAT DIALOGUES [WARNING] (WTG)
{330}{}{Ruce pryè, nebo tvı ruce budou pryè. Rozumíš?}
{331}{}{Odpal sakra od toho auta.}
{332}{}{Tvùj ivot nemá zdaleka ani takovou cenu, jako jediná pneumatika z toho auta. Dotkni se ho ještì jednou a uvidíš.}
