#tento soubor pøeložil Vladimir "SIR QWERTY" Sojka - http://qwerty.moje.cz
{100}{}{Vidíš komika.}
{150}{}{Vidíš mizernýho poulièního komika. Je nervózní a je to na nìm vidìt.}

{200}{}{Je pøíliš zamìstnán svým výstupem, než aby s tebou mluvil.}

{1000}{}{Takže... aha... proè chtìl ten radškorpion pøejít ulici?}
{1001}{}{Aby už nemusel poslouchat ty tvoje dementní vtipy!}
{1002}{}{Bude mít nìkdo nìco proti tomu, když tohohle chlápka zabiju?}
{1003}{}{Protože... protože chtìl utýct pøed radioaktivním spadem...}
{1004}{}{Seš kretén!}
{1005}{}{JDI DO PRDELE!}
{1006}{}{No, víš, vtip je v tom, že pøece, když už byl mutant, nemusel pøecházet ulici, takže, no...}
{1007}{}{}

{2000}{}{He he. Ty potvory z Gecka, ghoulové, smrdìj jak kopa hnoje.}
{2001}{}{Ty smrdíš!}
{2002}{}{Tohohle chlápka by mìli dávat jenom v sobotu veèer!}
{2003}{}{Eh... he he... takže, ty ghoulové fakt dost smrdìj. Totiž...}
{2004}{}{Už jsem øíkal, ze ghoulové smrdìj?}
{2005}{}{Takže jsem potkal toho ghoula a povídám, 'Nezávidíte nám vy ghoulové to, že my lidi nesmrdíme ?'}
{2006}{}{A on: "Ne, proè se ptáš ?"}
{2007}{}{Protože jste celý zelený, povídám já.}
{2008}{}{Hahá... zelený závistí. Chápeš?}
{2010}{}{Húúú!}
{2011}{}{}

{3000}{}{Takže jsem potkal takovou prostitutku, že jo, takovou hnusnou kurvu...}
{3001}{}{Tvoje matka je kurva!}
{3002}{}{"Kurva?" Rozmlátim ti držku hned, jak to tady skonèim!}
{3003}{}{Kde jsem to... aha... takže ona mi povídá, že jo, 'to máš v kapse geckona nebo seš jenom trochu nadrženej?'}
{3006}{}{Eh... už jsem vám øikal, že ten geckon plival oheò? He-he.}
{3007}{}{}

{4000}{}{Vertibirdi?}
{4001}{}{Verti- co?}
{4002}{}{O èem to ten èlovìk proboha mluví?}
{4003}{}{Nejsou to ty pytlíky burákù, co se rozdávají v letadle bìhem letu?}
{4004}{}{Neni to náhodou ta sraèka, co žereš?}
{4005}{}{A... co je s nima?}
{4006}{}{}

{5000}{}{Zvláštní schopnosti?}
{5001}{}{*Zíííív, mlask mlask*}
{5002}{}{Víš, jako takový ty chvaty. Znáš nìjaké?}
{5003}{}{Vidìl nìkdo v poslední dobì tvojí "speciální zbraò"?}
{5004}{}{Uhhh... Myslíš, že existuje nìkdo, kdo øíká "Hej, myslím, že chci víc totálních neúspìchù?"}
{5005}{}{Co to je za lidi?}
{5006}{}{Tak tenhle už jsem nìkde slyšel.}
{5007}{}{}

{6000}{}{Rad-škorpióni?}
{6001}{}{Co je na nich tak RADostnýho?}
{6002}{}{RAD jako RADioaktivní, tupèe.}
{6003}{}{Co to je za lidi, který mùžou vymyslet zmutovaný škorpiony...}
{6004}{}{Jsou tak RADostný?}
{6005}{}{Jdi už do hajzlu!}
{6006}{}{}

{7000}{}{Krtèí potkan?}
{7001}{}{Panejo...}
{7002}{}{A co je s nima?}
{7003}{}{Je to krtek...}
{7004}{}{Nebo...}
{7005}{}{Je to potkan?}
{7006}{}{A co takhle praseèí krtek?}
{7007}{}{Co je s nim?}
{7008}{}{Uhhh... jo, co je s nim?}
{7009}{}{}

{8000}{}{Super mutanti?}
{8001}{}{Pøestane tenhle sráè taky nìkdy vyprávìt ty svoje pøiblblý fóry?}
{8002}{}{Co je na nich tak SUPER?}
{8003}{}{Kdy jsi ty naposledy vidìl nìjakýho super mutanta...}
{8004}{}{Sundali snad nìkdy koèku dolù ze stromu?}
{8005}{}{Nikdy! Víte proè?}
{8006}{}{*Zííív*}
{8007}{}{Protože... protože super mutanti nezachraòují koèky...}
{8008}{}{Oni jenom bezbolestnì zabíjejí!}
{8009}{}{Kdyby tak tebe nìkdo zabil tebe... a hodnì bolestivì.}
{8010}{}{Tak kdo jim teda øiká SUPER mutanti?}
{8011}{}{Co je to teda za lidi?}
{8012}{}{Asi stejný blbci, který si najali tebe!}
{8013}{}{}

{9000}{}{A co ten blb Myron?}
{9001}{}{To mluví o mnì?}
{9002}{}{Šašek jeden! Musel strávit celej svùj zablbanej život ve sklepì svejch rodièù.}
{9003}{}{*Ha* *Ha* *Ha*}
{9004}{}{Hej!}
{9005}{}{Teda, Myrone, ty jsi ale VÁŽNÌ vylízanej.}
{9006}{}{Nic si z toho nedìlej Myrone. Chce bejt jenom hroznì vtipnej.}
{9007}{}{Jo, máš velký štìstí, že ti nerozkopu ksicht!}
{9008}{}{}

{10000}{}{Už jste slyšeli to o tý Bishopovì dceøi, že se nechala zbouchnout?}
{10001}{}{*Potlesk*}
{10002}{}{::Hvizd::}
{10003}{}{Bravo!}

{11000}{}{He-he. Slyšeli jste ten o tom divochovi, co vymlátil celou Enklávu?}
{11001}{}{Ten divoch byl tak blbej, buran jeden... uh, že je vyhodil všechny do luftu.}
{11002}{}{BUMM!}
{11003}{}{Už jsem øíkal, jak blbej ten divoch byl?}
{11004}{}{Ten nejvìtší blbec seš tu TY!}
{11005}{}{}