#tento soubor pøeloil Vladimir "SIR QWERTY" Sojka - http://qwerty.moje.cz
# 0. QUICK LOOK
{100}{}{Vidíš Korsické bratry.}

# 0. LOOK
{150}{}{Vidíš dobøe obleèeného mue, kterı je silnì cítit vazelínou. Z nìjakého dùvodu ti pøipomíná slizkého hada.}
{151}{}{Vidíš Martyho, jednoho z Korsickıch bratrù. Vlasy má ulízané dozadu a jeho tváø se jemnì blıská krùpìjemi potu.}
{152}{}{Vidíš Sida, jednoho z Korsickıch bratrù. Na hlavì má pøipitomìlou paruku a na nose tmavé brıle.}

# 1. FALLOUT2 = ENCLAVE_DESTROYED (WTG)
{200}{}{Hej, }
{201}{}{}
{202}{}{Ty, }

# 2. POWER ARMOR (WTG)
{210}{}{Jak se s takovou vìcí koupeš?}
{211}{}{To je nìjakej novej vibrátor nebo co?}
{212}{}{To je asi novej obøí kondom, e jo?}

# 3. PORN STAR (WTG)
{220}{}{Teda ty jsi ještì rozhicovanìjší ne sopka ve "svejch dnech"}
{221}{}{Teda ty seš hvìzda. Støíkající hvìzda.}
{222}{}{Jsi fakt hvìzda. Explodující hvìzda.}
{223}{}{Jsi vánì tøída - umíš do toho poøádnì "bušit", to se musí nechat.}
{224}{}{Ty vydáš za tisíc "povstalcù" - hehe, jestli víš, co tím myslím}
{225}{}{}
{226}{}{Ty jsi fakt hvìzda.}
{227}{}{Hej! Vítej zpátky!}
{228}{}{Pojï, dáme øeè.}
{229}{}{Nepromluvíme si o píchaèkách? Myslím tím o "píchacích hodinách" samozøejmì.}
{230}{}{Nechceš to udìlat?}
{231}{}{Víš, na co èumím? Na tu nejrajcovnìjší fenku na svìtì.}
{232}{}{}
{233}{}{Vítej zpátky, prcino.}

# 5. MADE MAN (WTG)
{245}{}{Jejej, šampión. Všichni vám fandíme.}
{246}{}{Ahoj, }

# 6. PRIZEFIGHTER (WTG)
{250}{}{Èau, ty sexuální Herkule!}
{251}{}{Hleïme toho machra.. párkrát u to vyhrál.}
{252}{}{U jsi nìkdy uvaoval o kariéøe ve kšeftì, }
{253}{}{Mùu ti zajistit dobrej kšeft. Pøemejšlej o tom, OK?}
{254}{}{Bojovej styl máš skvìlej. A co v posteli?}
{255}{}{Jsi zde vdy vítán. Kdykoliv budeš potøebovat práci, pøijï...}
{256}{}{Povìz, }
{257}{}{Ještì jednou!}
{258}{}{Bojuj, Xeno.}
{259}{}{Krásnı bøíško! Jak ehlicí prkno!}

# 8. SLAVER (WTG)
{270}{}{Všechno zaplnìno, otrokáøi.}
{271}{}{Tihle otroci jsou moji. Sleduj.}

# 9. FLOAT/CLICK [COMPANION: ROBO-DOG] (WTG)
{275}{}{Eh, fajn robo-pes, ale s takovejma filmy netoèíme. Moná za pár let.}
{276}{}{Ten pes je kradenej z domácnosti?}

# 10. FLOAT/CLICK [COMPANION: ROBOBRAIN] (WTG)
{280}{}{Hele, u má ten robot na podvozku letní dezén?}
{281}{}{Hele, není to náhodou jeden z tìch robotickejch vibrátorù? U jsem o tom nìco slyšel.}
{282}{}{Nechtìla by si ta plechovka zahrát ve filmu?}

# 11. FLOAT/CLICK [COMPANION: MARCUS] (WTG)
{290}{}{Podívej se, odveï si toho svıho mutanta. S takovejma ještì filmy netoèíme.}
{291}{}{Tak na rovinu - nemyslím si, e by nìkterá z našich hereèek tohohle mutanta "zvládla".}
{292}{}{U jsme jeden film s mutantem natoèili - mutant všechny hereèky "odrovnal". Jestli víte, co tím myslím.}

# 12. FLOAT/CLICK [COMPANION: LENNY] (WTG)
{300}{}{Jéiš! Koukej toho smradlavıho ghoula odvést, ne se tady ten puch usadí nadobro.}
{301}{}{Tak s ghoulama fakt filmy netoèíme. Pìknì šupem ho odsud vyveï.}
{302}{}{*Fíha* Ten ghoul smrdí a na pùdu! Rychle pøineste osvìovaè, nebo tu padnu udušením!}

# 13. FLOAT DIALOGUES (WTG)
{310}{}{Dobrá, veškeré osvìtlení vypnout...}
{311}{}{A ne aby tam nìkdo strèil do zábìru mikrofon!}
{312}{}{Mùeme se prosím soustøedit na natáèení?}
{313}{}{Tak na takovıhle bøídily se mùu vykašlat...}
{314}{}{COE chce? Tak mu vyøiï, e si má jít klidnì hodit mašli!}
{315}{}{Všechno bylo lepší v dobách implantátù...}
{316}{}{Ti nahoøe nás jednou zabijou.}
{317}{}{Toho chlápka Digglera jsem mìl rád.}
{318}{}{Ten chlapík je sexuální bomba!}
{319}{}{No tak tebe asi nepicnu.}
{320}{}{Von je jak raketa! Horkej projektil! Teda Side, øeknu ti, ten právì startuje, to je perspektiva!}
{321}{}{Zasranì dobrej!}
{322}{}{Øekni tomu bastardovi, e má táhnout tøeba do pekel!}
{323}{}{Podívej, jestli se ten zasránek ještì bude poflakovat okolo, tak...}
{324}{}{Pam-pam-tıda-pam dám si ruce do kapes...}
{325}{}{No jestli tohle není nejlepší, tak nevím...}
{326}{}{Mnì nikdo za fusekli tahat nebude.}
{327}{}{Tak to mu øekni, tohleto, tomu zaflusanımu zkurvysynovi...}
{328}{}{U mu nemám co øíct, hajzlovi.}
{329}{}{Myslí si o sobì, e je bùhví co.}
{330}{}{20 minut, puso.}
{331}{}{Tak si to ještì sjedem: (Koukne do scénáøe.) Vchází Markétka, on a Sylvie jdou na to... Kristına jde do koupelny, Péa se k ní pøidá, jdou na to. Vchází Ron...}

# 14. INTRO (NORMAL) (WTG)
{345}{}{Korsiètí bratøi, k vašim slubám... (Vzhlédne, pøièem se mu pomalu rozsvítí ve škebli..) Hej... tebe u známe? Chceš bejt nová 'nabíjeèka'?}
{346}{}{Korsiètí bratøi, k vašim slubám... (Vzhlédne, pøièem se mu pomalu rozsvítí ve škebli..) Tak bereš to místo 'nabíjeèky'?}
{347}{}{Korsiètí bratøi, k vašim slubám... (Vzhlédne, pøièem se mu pomalu rozsvítí ve škebli..) Hej... tebe u známe? Ty jsi naše nová 'nabíjeèka'?}
{348}{}{Korsiètí bratøi, k vašim slubám... (Vzhlédne, pøièem se mu pomalu rozsvítí ve škebli..) Hej... tebe u známe? Ty si 'nabíjeèka'?}
{349}{}{Já nabíjeèka}
{350}{}{Já nenabíjet! Já vyvíjet!}
{351}{}{Odchází}
{353}{}{Jasnì e jo.}
{354}{}{Vlastnì moje lepší polovièka je...}
{356}{}{Ne, jsem tu pro prachy Velkıho Jeíše Mordina.}
{357}{}{Ne, promiòte. Nechci vás rušit.}
{358}{}{Ne-e. Promiòte. Nechci vás rušit.}

# 15. ME fluff (UGLY) (14, 58)
{370}{}{Dobrá, ty mozkovno. Plat je 5... ehm, 3 babky za 'èíslo'. Padej dozadu a koukej tomu frajerovi namastit to jeho kopí.}
{371}{}{Kopí prej... ten zasr--}
{372}{}{Udìláš, co øíká.}

# 16. SHAFT 2 (15)
{380}{}{Dej si bacha na pusu.}
{381}{}{Mluvim o Kopí!}

# 17. SHAFT 3 (16)
{390}{}{(Dríš mu ruce.) Já to vytáhnu.}
{391}{}{Padej mu tam dozadu 'nabít'.}

# 18. ME fluff (GOOD-LOOKING) (14, 51, 54, 58)
{400}{}{Hmmmm. kolik vydríš, kámo?}
{401}{}{Hmmmm. Vydríš tolik, nakolik vypadáš, zlato?}
{402}{}{Já vydrím}
{403}{}{Dìlám do enskejch}
{404}{}{Peníze sem.}
{405}{}{Jdu na to.}

# 19. ME BENCH/ME NO DO BENCH (18)
{415}{}{Faajn kámo, vím odkud jsi a PØESNÌ taky vím, kam jdeš. Chceš si zahrát ve filmu?}
{416}{}{Fajn puso, vím odkud jsi a PØESNÌ taky vím, kam jdeš. Chceš si zahrát ve filmu?}
{417}{}{Beru kadej kšeft.}
{418}{}{Hrát jako co?}

# 20. ME LIKE STUFF (19)
{425}{}{Fakt? Tak to já taky! Máme toho tolik spoleènıho! Koukni, my jsme studio a dìláme tu zázraky. Ty jsi...}
{426}{}{...jo, ty, kámo, ty mùeš bejt souèástí toho zázraku!}
{427}{}{...jo, ty, zlatíèko, ty mùeš bejt souèástí toho zázraku!}
{428}{}{Jasná páka}
{429}{}{Zázraky! Kouzla! Chtít zázraky!}

# 21. ACT LIKE WHAT (19)
{435}{}{Opøi se do toho - jako ZVÍØE. Jako divokej høebec. Jako úplnej ivoèich, stavìnej k uspokojování davù svejma vıkonama!
 KOUZLA, CHLAPÈE, JAKO KOUZELNÍK! TO JE TO, o èem tady furt mluvím!}
{436}{}{Opøi se do toho - jako ZVÍØE. Jako divoká šelma. Primitivní zvíøe s touhou ohromit davy svıma vıkonama! KOUZLA, HOLKA, JAKO KOUZELNÍK! TO JE TO, o èem tady furt mluvim!}

# 22. MAGIC! MAGIC! ME LIKE MAGIC! (20, 21)
{445}{}{X-celentní! Teï si tì trochu vyzkoušíme. Potøebuju se kouknout, jak seš na tom s 'naèasovánim'.}
{446}{}{Pøipravenej, kámo?}
{447}{}{Pøipravená, pusinko?}
{448}{}{Dobe!}

# 23. OKEE-DOKEE!/SURE! (22, 44, 59)
{455}{}{Tak se do toho opøi! Není èasu nazbyt! A to lítá!}
{456}{}{Tak fajn, chlape, rozbal to na plnı koule...}
{457}{}{Tak jo, holka, rozjeï to na plnı pecky...}
{458}{}{Udìláš, jak si pøeje...}
{459}{}{Vsaï boty. Tos ještì NIC nevidìl.}

# 24. POOR AGILITY (23)
{465}{}{Promiò kámo, nejsi dostateènì PRUNEJ na tuhle makaèku. Pracuj na sobì, moná e si promluvíme pozdìjc, jo?}
{466}{}{Promiò beruško, nejsi dostateènì PRUNÁ na tuhle makaèku. Pracuj na sobì, moná e si promluvíme pozdìjc, jo?}
{467}{}{TODLE já rád... Já vrátit brzy}
{468}{}{*Snffff* Dobe. *Snffff* Hlavnì kdy mùu pomoct.}
{469}{}{Pokusím se zapracovat na svı kondici. Ještì se stavím.}
{470}{}{Moná e ještì dorazím.}

# 25. POOR CON (23)
{475}{}{Promiò chlape, jsi sice celkem frajer a dost obratnej, ale moc dlouho nevydríš... Trochu na sobì zapracuj a pak se ozvi, fajn?}
{476}{}{Promiò pusinko, jsi sice poøádná kost a dost obratná, ale moc dlouho nevydríš... Trochu na sobì zapracuj a pak se ozvi, fajn}
{479}{}{Zamakám na svı vıdri. Ještì se ozvu.}

# 26. POOR SEX EXPERIENCE (23)
{485}{}{Promiò chlapèe, jsi sice celkem frajer, dost obratnej navrch a máš vıdr brahmíny... jene ti oèividnì chybí zkušenosti a my tì tu nemám èas trénovat. Trochu na sobì zapracuj a pak se ozvi, fajn?}
{486}{}{Promiò zlato, jsi sice celkem dobrá kost, dost obratná navrch a máš vıdr brahmíny... jene ti oèividnì chybí zkušenosti a my tì tu nemám èas trénovat. Trochu na sobì zapracuj a pak se ozvi, fajn?}
{489}{}{Jo, vydám se ještì na 'zkušenou'. Snad pøíštì.}

# 27. PLAYER IS A STAR! (23)
{495}{}{Teda chlape, to bylo neuvìøitelnı! }
{496}{}{Teda zlato, to bylo neuvìøitelnı! }
{497}{}{Teda to byl naprosto ryzí materiál, to nejlepší z Rena! Tenhle vıkon byl lepší ne všechny postavenı, kterı sem kdy vidìl! Chceš natoèit s náma film? No tak! Promluvíme si o tom!}
{498}{}{Dobrá teda... chci to dìlat poøád a furt.}
{499}{}{Ne-e. Chci jít. Necítit se to vevnitø dobe.}
{500}{}{No to vypadá dobøe. Moje cena: 200 šlupek za... èíslo.}
{501}{}{To vypadá dobøe. Ale mám pár podmínek. Zajedno: pracuju jen s ÈISTEJMA hercema, zadruhı: oèekávám minimálnì 500 šlupek za èíslo, 20% podílu, A ádnı PODRAZY, jasnı? Já jsem hvìzda a ty to víš.}
{503}{}{Nezájem. Jdu se projít. Hodnì daleko.}

# 28. OKEE DOKEE . . . ME TALK WITH YOU . . . (27, 29)
{515}{}{(Vytáhne kousek papíru z bundy a ty mu tam napíšeš velké 'X'.) Hotovo! Mùem zaèít toèit! Zaprvı, musíš si vybrat pseudonym, nìco co prostì køièí "SEM HVÌZDA". Napadá tì nìco?}
{516}{}{(Vytáhne kousek papíru z bundy a ty mu tam vyšiješ jeden podpis.) Hotovo! Mùem zaèít toèit! Zaprvı, musíš si vybrat pseudonym, nìco co prostì køièí "SEM HVÌZDA". Napadá tì nìco??}
{517}{}{Dobrá - a co jiné jméno?}

# 29. I'M INTERESTED, BUT . . . (SMART) (28)
{525}{}{...hmmmm...Já ...hmmmm. Koukni se, budu ti platit tìch 500 babek, ale na podíl zapomeò. Jasnı?}
{526}{}{Dobøe.}
{527}{}{To ne. Ještì se uvidíme.}
{528}{}{Nebudou podíly? Pak nebude ani }
{5528}{}{. Padám z tıhle slepièí prdele.}

# 30. INPUT LINE: X = NOT RECOGNIZED. (28)
{535}{}{Tak fajn! "}
{5535}{}{!" TO SE MI LÍBÍ! KRUCINÁL TO SE MI LÍBÍ! Tak jdeme na to...}
{6535}{}{! Svìtla! Kamera! Akce!}
{536}{}{Achtung! Achtung!}
{537}{}{Pus se do toho.}

# 31. INPUT LINE: X = RON JEREMY. (28)
{545}{}{Eh... TOHLE jméno zrovna ne, jo? Lidi by si to mohli vykládat všelijak. Myslím, e nikdo nechce vidìt v pornu èlovìka s takovım jménem. Vyber si jinı, OK?}
{546}{}{OK...}
{547}{}{Ale todle já CHCI.}
{548}{}{Ale tohle se mi vánì líbí.}

# 32. INPUT LINE: X = DIRK DIGGLER. (28)
{555}{}{Tak TOHLE je tak záøící a údernı jméno, jen jen VYBUCHNOUT - taková je to síla! Skvìlej vıbìr, kámo, skvìlej vıbìr. A teï, jdeme na vìc! Svìtla! Kamera! Jedem!}
{556}{}{Tohle jméno má svı kouzlo a stane se legendou. Skvìlej vıbìr, kámo, skvìlej vıbìr. A teï, jdeme na vìc! Svìtla! Kamera! Jedem!}
{557}{}{Tohle jméno má svı kouzlo a stane se legendou. Skvìlej vıbìr, puso, skvìlej vıbìr. A teï, jdeme na vìc! Svìtla! Kamera! Jedem!}

# 33."FILMING" FADE. (30, 31, 32)
{565}{}{Tak fajn! Fajn! Jdeme na to lidi! Rozjeï to! Trochu ivota! Všechno pøipraveno?}
{566}{}{e váháš, strejdo.}
{567}{}{'Ready' je moje druhı jméno.}

# 34. FILMING DONE (STUPID) (33, 48)
{575}{}{Tak, a hotovo, pøíteli. Dneska padla. Miliónovej vıkon! MILIÓNOVEJ! Ty polohy! Perfektní! Jestli si to chceš zopakovat, pøijï nás navštívit za mìsíc, domluveno?}
{576}{}{Tak, a hotovo, zlatíèko. Dneska padla. Miliónovej vıkon! MILIÓNOVEJ! Ty polohy! Perfektní! Jestli by sis to chtìla zopakovat, pøijï nás navštívit za mìsíc, domluveno?}
{577}{}{Dobráá... zatím èágo!}

# 35. FILMING DONE (SMART) (33, 48)
{585}{}{Klapka! Dobrá, kámo. }
{586}{}{Klapka! Tak skvìlı, puso. }
{587}{}{To byl vıkon. Za MILIÓN! }
{588}{}{A to jak ses udìlal! }
{589}{}{A to sténání! }
{590}{}{Perfektní! Tady máš vejsluku: }
{591}{}{200 šlupek. }
{592}{}{500 šlupek. }
{593}{}{Jestli si to chceš zopakovat, pøijï nás navštívit za mìsíc, domluveno?}
{594}{}{Domluveno.}

# 36. UH, WHAT'S A fluffER? (UGLY) (14, 58)
{610}{}{Ty tu chceš makat? Hele, tak kdy u se ptáš, tak NEJSI osoba, kterou hledáme do tohohle kšeftu. Tak co chceš?}
{612}{}{Kšeft, huh? Tak dobrá, JÁ JSEM nabíjeèka. Nejlepší nabíjeèka v celym okolí.}
{613}{}{Ale nic. Tohle neni nic pro mì.}

# 37. UH, WHAT'S A fluffER? (ATTRACTIVE) (14, 58)
{620}{}{Teda kam já koukám? Ty sem pøijdeš, rozená hvìzda, a já tu plácám jak idiot! Koukni, kámo, omlouvám se. Øekni, hledáš nìjakou práci? ádnı takovıto 'nabíjení'. Mluvím o NATÁÈENÍ, rozumíš?}
{621}{}{Teda kam já koukám? Ty sem pøijdeš, rozená hvìzda, a já tu plácám jak idiot! Koukni, zlato, omlouvám se. Øekni, hledáš nìjakou práci? ádnı takovıto 'nabíjení'. Mluvím o NATÁÈENÍ, rozumíš?}
{622}{}{Tak zaprvnı, co tady dìláte?}
{623}{}{Jestlie v tom hraje roli pani Tuèná Odmìna, tak mì to zaèíná zajímat.}

# 38. SURE AM. (UGLY) (14, 36, 40, 41, 42, 43)
{630}{}{Tak jo. Bì dozadu a pìknì je tam pøiprav. Tady máš 5 penìz.}
{631}{}{Bereš to.}
{632}{}{Hmm, vlastnì to ani moc dìlat nechci. Ne díky. Úplnì nejlepší bude, kdy vypadnu.}

# 39. MY SPOUSE IS. (14, 58)
{640}{}{Tvoje lepší polovièka, øíkáš? Hmmmmm. Dobrá. Vezmi svého ivotního partnera, jdi dozadu a zaèni poøádnì mastit. Tady máš 3 šlupky.}
{641}{}{Udìlej, co ten pán øíká, Davine. A mùe bıt }
{5641}{}{ pyšná.}
{642}{}{Udìlej co øíká, Mirie. TEÏ.}

# 40. WHAT'S THIS PLACE? (14, 36, 37, 47, 48, 58, 59)
{650}{}{Tohle místo? Ale jdi,dìláš si snad srandu? Tohle to je FILMOVÉ studio Golden Globes, jediné v Renu a moná jediné, které na tomhle svìtì STOJÍ.}
{651}{}{Tohle místo? Ale jdi, dìláš si snad srandu? Tohle to je FILMOVÉ studio Golden Globes, jediné v Renu a moná jediné, které na tomhle svìtì STOJÍ, jasnı? Tak co, budeš tu jen tak kecat, nebo chceš práci?}
{652}{}{Tohle místo? Ale jdi, dìláš si snad srandu, zlato? Tohle to je FILMOVÉ studio Golden Globes, jediné v Renu a moná jediné, které na tomhle svìtì STOJÍ, jasnı? A teï, budeš tu jen tak kecat, nebo chceš práci?}
{653}{}{Tohle starı místo? Ale jdi, dìláš si snad srandu? Tohle to je FILMOVÉ studio Golden Globes, jediné v Renu a moná jediné, které na tomhle svìtì STOJÍ, jasnı?. Ale to staèí... hledáš práci, kámo? POTØEBEJEME talenty, jako jsi ty.}
{654}{}{Tohle starı místo? Ale jdi, dìláš si snad srandu? Tohle to je FILMOVÉ studio Golden Globes, jediné v Renu a moná jediné, které na tomhle svìtì STOJÍ, jasnı?. Ale to staèí... hledáš práci, puso? POTØEBEJEME talenty, jako jsi ty.}
{655}{}{Jak jako - "natáèíte"? Myslím, ale jdìte, to byste museli mít kamery, film, promítaèky... Kde byste to jen mohli sehnat?}
{657}{}{Ne, dík. Musím jít.}
{658}{}{Jen se dívám. Zajdu se nìkam napít. Zatím!}

# 41. WHERE DO YOU GET THE STUFF (ATTRACTIVE) (40, 52, 55)
{670}{}{Vykoumali jsme to jinak... nepotøebujeme ádnı ty krámy z doby kamennı. Tady se jede porno NAIVO... em, holo...grafickı projektor. ádnı velkı krámy, ádnı sloitı obskakování... a ádná fušeøina.}
{671}{}{Vááánì... co je to za projektory?}
{672}{}{Rozumím... podívejte se, zajímá mì ta práce, jestli ještì nabízíte.}
{673}{}{Fajn pokec, ale musím u jít.}

# 42. SPECS (41)
{680}{}{No... ještì jsme poøádnì ani nezjistili pøesnou kapacitu QEWB mechaniky - mùu øíct, e je to nìco jako 300 GB vysokokapacitní pamìová kostka s hustım zápisem. Aèkoliv nám 70-75% seere operaèní systém Wembloudz 57, stále ještì tam mùeme uloit øádovì stovky let filmu.}
{681}{}{A kde je ta kostka teï? Mùu jí vidìt?}
{683}{}{Fíha. To je HODNÌ prasárnièek. Myslím, e o tom zaènu uvaovat.}

# 43. CUBE (42)
{690}{}{To ne, snaíme se nikoho nepouštìt do místnosti s technikou... kadı tam chce hodit dva centy pro štìstí. Nìkdy sou to dva centy kamení nebo písku. Mimoto je to pro nás celkem dost dùleitá vìcièka - nic se s ní nesmí stát.}
{692}{}{Tak vám pøeju hodnì štìstí a nashle!}

# 44. I'll TAKE A JOB . . . (ATTRACTIVE) (37, 40, 41, 42, 43)
{700}{}{X-celentní! Teï si tì trochu vyzkoušíme. Potøebuju se kouknout, jak seš na tom s 'naèasovánim'. Pøipravenej, kámo?}
{701}{}{X-celentní! Teï si tì trochu vyzkoušíme. Potøebuju se kouknout, jak seš na tom s 'naèasovánim'. Pøipravená, puso?}
{702}{}{Jistì.}
{703}{}{Eh, radìji ne. Myslím, e to nechám radši bejt. Snad jindy.}

# 45. FUCK OFF! (50)
{710}{}{Tak to koukej pìknì rychle vodsud vypadnout, ty sraèièko! Tebe my nepotøebujeme! Ztra se! V tıhle brani si u ani neškrtneš!}
{711}{}{Nechci! JEŠTÌ SE UVIDÍME!}
{712}{}{Jdi se vysrat! Nejsi mùj šéf. To teda ne! Víš èí já jsem šéf? }
{5712}{}{!}

# 46. BROS. PISSED (WTG)
{720}{}{Vypadni a ztra se. Není o èem mluvit.}
{721}{}{Nemáme si co øíct. Vodprejskni.}

# 47. PORN STAR, LESS THAN 30 DAYS (WTG)
{730}{}{Vítej zpátky, ty jsi pøeci }
{5730}{}{! Dneska zrovna ádnı maso nemlátíme, ale zkus to za pár dní. }
{732}{}{Mùete mi pøedtím øíct nìco více o studiu?}
{733}{}{Jsem rád, e to øíkáte. Heleïte se, jsem tu pro prachy a zlato Velkıho Jeíše Mordina.}
{734}{}{Dobrá. Vrátím se pozdìji.}

{735}{}{(Mrkne.) Ty jsi zlato, nic ne zlato!}

# 48. PORN STAR, MORE THAN 30 DAYS (WTG)
{740}{}{Korsiètí bratøi, k vašim slubám... (Vzhlédne, pøièem se mu pomalu rozsvítí ve škebli..) Hej... vítej zpátky, ty jsi }
{5740}{}{! Ještì nìjakej film?}
{743}{}{Jasnì. Hupnem rovnou na vìc.}
{745}{}{Ne tak docela. Jsem tu pro prachy Velkıho Jeíše Mordina.}
{746}{}{Ne, dík.}

# 49. NO THANKS (48)
{755}{}{No tı blááho... tak ty to NECHCEŠ dìlat?! Nejsme pro tebe dost DOBRİ? Ty jsi pøece '}
{5755}{}{!' A to jsme z tebe udìlali MY! Tak na to nezapomeò!}
{756}{}{Nejsem zpìt, jen vás je pìt, a budu chtít, dám ti vì-dìt}
{758}{}{Ignoruješ ho a odcházíš}
{759}{}{Hele, vychladni. Dneska prostì na to nemám náladu, OK? Tı jo. Zkrátka se vrátím, a se trochu uklidníš.}
{760}{}{Jdìte se bodnout. Takovıhle sraèky já vùbec nemám zapotøebí. Já jsem hvìzda! A to ne nìjaká vobyèejná!}

# 50. DRUGS . . . (48)
{765}{}{Hej...jsi v poøádku? Vypadáš trochu mimo. Nejsi na drogách, e ne? Protoe v tomhle stavu s tebou prostì nemùeme poèítat.}
{766}{}{Já CHCI toèit teï, èlobrdíku.}
{768}{}{Nejsi mùj šéf! Chci teï píchat, je to moje péro, take kadej se TEÏ pøipraví na poøádnou šukaèku.}
{769}{}{Nejsi ádnej mùj šéf! Chci si zapíchat právì teï, je to moje píèa, take kadej se TEÏ pøipraví na poøádnou šukaèku.}
{770}{}{Dobrá. Vrátím se v trochu støízlivìjším stavu.}

# 51. PRIZEFIGHTER, BUT NOT PORN STAR (WTG)
{780}{}{Korsiètí bratøi, k vašim slubám... (Chlápek zvedne hlavu, pøièem pøekvapením zamrká.) A dopr...}
{5780}{}{?! Jakto e seš tu teprve teï? Mimochodem, skvìlej boj! Vánì skvìlej! Co pro tebe mùu udìlat?}
{781}{}{Pro mì! Pro mì!}
{782}{}{Nic}
{783}{}{Co je tohle za místo?}
{784}{}{Mùete mi øíct více o tomhle studiu?}
{785}{}{Máte nìjakı volnı místa...?}
{786}{}{Nemìli byste nìjakou práci pro osobu jako jsem já?}
{787}{}{Pøišel jsem pro prachy Velkıho Jeíše Mordina.}
{788}{}{Nic. Nechci rušit.}

# 52. PRIZEFIGHTER: WHAT IS THIS PLACE? (51)
{795}{}{Golden Globes studio, studio pro všechny talenty v... tom, co zbylo ze svìta. A ty, ty mùeš bıt HVÌZDA, na to já mám èuch? Chceš hrát?}
{797}{}{No jasnì. Jste si jist?}
{799}{}{Hmm, teï zrovna ne. Nechci obtìovat.}

# 53. ANY OPENINGS? (51, 52)
{805}{}{No to teda zatracenì JO! Hnedle si tì vyzkoušíme! Pøiprav se, pùjdeme dozadu!}
{806}{}{Udìláš, co chce...}

# 54. MADE MAN, BUT NOT PORN STAR (WTG)
{810}{}{Korsiètí bratøi, k vašim slubám... (Chlápek zvedne hlavu, pøièem pøekvapením zamrká.) A kruci... eh... hele, to jsi ty, }
{5810}{}{?! Jak se má }
{6810}{}{? Posaï se u nás! Take, co pro tebe mùu udìlat?}
{812}{}{Nic}
{813}{}{Co je tohle za místo?}
{814}{}{Mùete mi vyhovìt. Povìzte mi nìco o tomhle studiu.}
{815}{}{Dobrá otázka. Máte nìjaké... volné místo... které mùu vyplnit?}
{816}{}{Dobrá otázka. Máte práci pro nìkoho, jako jsem já?}

# 55. MADE MAN: WHAT IS THIS PLACE? (54, 57)
{825}{}{Golden Globes studio, studio pro všechny talenty v... tom, co zbylo ze svìta. Take co pro tebe mùu dneska udìlat?}
{827}{}{Máte pro mì èas? Myslím, e mùu bıt hvìzda, jestli víte, co tím myslím?}
{829}{}{Dneska nic. Snad pøíštì.}

# 56. MADE MAN: AUDITION ME? (54, 55)
{835}{}{No jasnì. Fajn, fajn. Em, dáme ti šanci. Podíváme se, jestli máš talent. Myslím tím, e máme docela nával a kdekdo chce hrát, ale mùeme tì vyzkoušet, OK? Tak se pøiprav, rychle!}
{836}{}{Udìláš, co øíká.}

# 57. I'M HERE FOR THE MONEY (14, 47, 48, 51, 52, 54, 55, 58, 59)
{845}{}{Ale jistì, jistì! Tady... vem si to. 250 babek. A, ehm, pozdravuj ode mì Velkıho Jeíše, OK?}
{846}{}{Ale jistì, jistì! Promiò, e jsem to hned nepochopil. Tady... vem si to. 250 babek. A, ehm, pozdravuj ode mì Velkıho Jeíše, OK?}
{847}{}{Ne mì odsud vyenete svinskım krokem, proè mi nepovíte nìco o té vaší malé operaci, chytráci?}
{848}{}{Jo, snad. Èasem, kámo.}

# 58. SECOND TIME (WTG)
{855}{}{Korsiètí, k vašim slubám... (Vzhlédne) Zase ty. Chceš ještì práci, pane Nabíjeèi?}
{856}{}{Korsiètí, k vašim slubám... (Vzhlédne) Zase ty. Chceš ještì práci, sleèno Chci-furt-nabíjet?}
{857}{}{Korsiètí, k vašim slubám... (Vzhlédne) Ty! Co se to s tebou STALO? Teda myslím, jako e je to dobrı, dobrı... kam jsem pøedtím dal jen voèi. Nabíjet?}
{861}{}{Eh, co je to Nabíjeèka?}
{862}{}{Jasnì. Mìl byste pro mì nìjakou práci?}

# 59. SECOND TIME (WTG)
{875}{}{Korsiètí, k vašim slubám... (Vzhlédne) Hele! U máš rozmyšleno? Co?}
{876}{}{Korsiètí, k vašim slubám... (Vzhlédne) Hele! Ty to chceš zkusit znovu, e jo?}
{877}{}{Korsiètí, k vašim slubám... (Vzhlédne) Hele! U máš rozmyšleno? Chceš ještì, e jo. Zkusit si ještì svoje KOUZLO?}
{879}{}{To jo.}
{881}{}{Ano. Rozmyslel jsem se. Mám ho hned vytáhnout...?}
{882}{}{Ano. Rozmyslela jsem se. Mám hned roztáhnout...?}

# 60. ENCLAVE_DESTROYED (WTG)
{895}{}{... Slyšel jsem to tvı akci... takhle pøeblafnout celou Enklávu. To chce teda kachní aludek.}
{896}{}{No}
{897}{}{Ne-e}
{899}{}{Podívejte se, ádnı pøablafnutí ani kouøení, jak si myslíte. Tam se dìlo úplnì nìco jinıho --}
{900}{}{Radši pùjdu.}

# 61. ENCLAVE_DESTROYED, PT 2 (60)
{910}{}{Ale tak se neupejpej. To musela bejt fakt jízda. Spousta lidí by to 'nespolkla'. Ale ty umíš pıchu spolknout a udìlat to kadımu, kdo to potøebuje. TO JE síla.}
{911}{}{Jo}
{914}{}{Podívejte se, ádnı pøablafnutí ani kouøení, jak si myslíte. Tam se dìlo úplnì nìco jinıho --}
{915}{}{Radši pùjdu.}

# 62. ENCLAVE_DESTROYED, PT 3 (61)
{920}{}{U to vidím, }
{5920}{}{v hlavní roli. Trhák podle tohohle dobrodruství. Jmenovalo by se to 'Pullout: Post-Nukleární hra na zajíèky.' Jdeš do toho taky? Co ty na to?}
{921}{}{Ty jsi hrdina, ty jsi, }
{5921}{}{. Ryzí matroš. Nikdy ti to nezapomeneme. Jéiš, toho šmejdu co musel jeden serat.  Ale a podle toho natoèíme film, lidi nám utrhaj ruce.}
{922}{}{Jo}
{924}{}{Jouky jo-o. Èau}
{926}{}{Krucinál! To teda jo!. U mám tuhle hru vyøešenou. Tak jdeme na to.}
{927}{}{Super. Díky...}
{928}{}{No, nejdøív si uloím pozici, jestli dovolíš. Pak pøijdu.}

# 63. CUBE GONE (WTG)
{935}{}{V hajzlu. Všechno je v hajzlu.}
{936}{}{Bez tı kostky...všechno šlo do kopru.}
{937}{}{Oh, krutí, krutí bozi sexu! Èím jsme si zaslouili tento krutı osud? Proè jste nám tu kostku sebrali?}
{938}{}{::Vzdecho:: S tou kostkou jsem mohl dobıt celı filmovı svìt.}

# Display Messages
# stupid dude
{1000}{}{Je mi blbì v bøiše.}
# regular dude
{1100}{}{Ack! ::flus, fluso:: To byl teda HNUS!}
{1101}{}{Máš hnusnou, zkaenou chu v ústech a je ti zle od aludku. Ale jen pova, 5 šlupek je 5 šlupek!}
# spouse
{1200}{}{Já...Necítím se moc dobøe.}
{1201}{}{Pravá láska opìt zvítìzila. Tvoje drahá polovièka je mrtvolnì bledá, ale aspoò jste o 3 babky bohatší!}

{1250}{}{Je z tebe hvìzda. Ta nejzáøivìjší hvìzda na nebi slávy.}

# END-LINES
{5200}{}{! Pøesnì ten hrdina, kterého jsme chtìli vidìt!}
{5201}{}{, náš hrdino, máme pro tebe spešl nabídku!}
{5202}{}{! Slyšeli jsme o tom kšeftu v Enklávì! Teï si mùeme promluvit o tom, co mùeme udìlat MY pro TEBE...}
{5225}{}{ je zlato. Ryzí kov.}
{5232}{}{! Srdíèko! Zlato!}
{5246}{}{. Pìkné poèasí, co?}
{5252}{}{?}
{5256}{}{, Jestli chceš, mùeme støihnout ještì jeden film...}
