#tento soubor pøeložil Vladimir "SIR QWERTY" Sojka - http://qwerty.moje.cz
# examine
{150}{}{Vidíš chlapíka v ošuntìlých šatech. Mne si nos a nenápadnì se rozhlíží kolem.}
{151}{}{Vidíš drogového dealera.}
{152}{}{Vidíš drogového dealera. Vypadá to, že èeká na zákazníka.}

# float
{200}{}{Hej, pøíteli! Hledáš trochu toho nejlepšího Jetu? Mám pøesnì to co potøebuješ!}
{201}{}{Pìknì si Enklávì nakopal prdel! Nechceš toho zachraòování svìta na chvíli nechat a oslavit to trochou toho nejèistšího Jetu?}
{202}{}{::Usmìje se::}
{203}{}{::Hvízdne::}
{204}{}{Není nic lepšího, než si vyhodit z kopejtka po tak namáhavý práci, jakou hra na Zlýho chlápka urèitì je, že jo?}
{205}{}{Mám matroš, kterej tì dostane až do nebe.}
{206}{}{Už jsi to nìkdy zkusil?}
{207}{}{Kdykoliv budeš chtít trochu tý dobroty do mozku, pøijï za mnou. Dám ti speciální slevu, jenom pro tebe.}
{208}{}{Vím co hledáš pøíteli a mohu ti pomoci. Mám tolik Jetu, kolik jen mùžeš spotøebovat.}
{209}{}{Proè chodit po zemi když se mùžeš vznášet?}
{210}{}{Mám ten nejèistší Jet v okolí. Není zrovna levný, ale rozhodnì stojí za to.}
{211}{}{Chceš nauèit lítat? Máš peníze? Pak jsem tvùj èlovìk.}
{212}{}{Mam nìco, po èem se budeš cítit jako v sedmém nebi, kámo.}
{213}{}{Mám Jet. Hodnì Jetu. Promluvme si.}

# click dialogue
{214}{}{Øekni mi jak ti mùžu pomoci. Øekni mi co chceš a já ti dám takovou cenu, jakou ti nedá nikdo jinej široko daleko.}
{215}{}{Takže si chceš dát trochu do nosu? Tak to seš na správném místì. PRO TEBE je všechno se slevou.}
{216}{}{To nejmenší, co pro tebe mùžu udìlat, je dát ti slevu na všechno. Mùj zpùsob, jak podìkovat za záchranu našich životù.}
{217}{}{Není nic lepšího, než si vyhodit z kopejtka po tak namáhavý práci, jakou hra na Zlýho chlápka urèitì je, že jo? Dobrá, udìlám ti cenu jakou jsi ještì nevidìl.}
{218}{}{Mám zboží, který tì dostane do ráje. A speciálnì pro tebe mám pøíjemnou slevu. Co tomu øíkáš?}

{219}{}{Máš dobrotu? }
{220}{}{Odejdeš}
{221}{}{Co tu máš?}
{222}{}{Nic nechci, díky.}

# player great
# male
{230}{}{Bude mi ctí. Pro tebe, kamaráde, mám zvláštní slevu. Jo, a øekni o mnì všem svým známým, platí?}
{231}{}{Takže ty si chceš dát trochu do nosu, co? Tak to jsi na správný adrese. PRO TEBE je všechno se slevou.}
{232}{}{Mám dost zboží, aby tì to dostalo do ráje, kamaráde. A speciálnì pro tebe mám fajnovou slevu. Tak co, dohodnem se?}
{233}{}{Mám matroš, po kterym vyletíš až do nebe kámo. A speciálnì pro tebe mám supr slevu. Co tomu øíkáš?}
{234}{}{To nejmenší, co pro tebe mùžu udìlat, je dát ti slevu na veškeré zboží. Mùj zpùsob, jak být pøátelský.}
# generic
{235}{}{Seš tøída, víš to? Fakt tøída. A když je nìkdo taková tøída jako ty, dostane u mì parádní slevu, chápeš?}
{236}{}{Øekni, jak ti mohu pomoci, pøíteli. Øekni co potøebuješ, a já ti udìlám tu nejlepší cenu.}
{237}{}{Po tak namáhavym dni je èistej Jet to nejlepší, že jo? No nemám pravdu? Pro tebe je všechno se slevou.}
# female
{238}{}{Bude mi ctí. Pro tebe mám holka zvláštní slevu. Jo, a øekni o mnì všem svým známým, platí?}
{239}{}{Takže si chceš dát trochu do nosu, holka? Tak to seš na správném místì. PRO TEBE je všechno se slevou.}
{240}{}{Mám zboží, který tì dostane do ráje, holka. A speciálnì pro tebe mám pøíjemnou slevu. Tak co, dohodnem se?}
{241}{}{Mám matroš, který tì dostane do ráje, holka. A speciálnì pro tebe mám pøíjemnou slevu. Co tomu øíkáš?}
{242}{}{To nejmenší, co pro tebe mùžu holka udìlat, je dát ti slevu na veškeré zboží. Mùj zpùsob, jak být pøátelský.}

{247}{}{Vím co hledáš, otrokáøi a mohu ti pomoci. Tolik Jetu, kolik budeš potøebovat.}
{248}{}{Proè chodit po zemi, když se mùžeš vznášet v oblacích. Ty máš škváru, já mám zboží.}
{249}{}{Mám nejèistší Jet v okolí, otrokáøi. Neni zrovna levný, ale stojí za to.}
{250}{}{Chceš umìt létat, otrokáøi? Máš prachy? Jsem tvùj èlovìk.}
{251}{}{Mám matroš, kterej tì dostane až do nebe, otrokáøi.}
{252}{}{Mám Jet. Hodnì Jetu. Dáme øeè.}
{253}{}{Mám dost Jetu na cestu do ráje, otrokáøi. Dohodnem se na cenì?}
{254}{}{Jestli se trochu vyznáš otrokáøi, uvidíš, že mám ten nejlepší Jet široko daleko.}
{255}{}{Sháníš nìjakej Jet? Vypadá to, mistøe otrokáøi, že se dohodneme.}
{256}{}{Sháníš nìjakej Jet? Promluvme si, mistøe otrokáøi.}

{261}{}{Vím co hledáš, pøíteli a o nìèem bych vìdìl. Mám tolik Jetu, kolik budeš potøebovat.}
{262}{}{Proè chodit po zemi, když mùžeš létat?}
{263}{}{Mám nejèistší Jet v okolí, otrokáøi. Není zrovna levný, ale stojí za to.}
{264}{}{Chceš umìt létat? Máš prachy? Jsem tvùj èlovìk.}
{265}{}{Mám matroš, kterej tì dostane až do nebe, pøíteli.}
{266}{}{Mám Jet. Hodnì Jetu. Promluvme si.}
{267}{}{Mám dost Jetu na cestu do ráje, kámo. Dohodnem se na cenì?}
{268}{}{Jestli se trochu vyznáš, uvidíš, že mám ten nejlepší Jet široko daleko.}
{269}{}{Sháníš nìjakej Jet? Obchod mùže zaèít.}
{270}{}{Sháníš nìjakej Jet? Promluvme si.}

{519}{}{ Jak bonbónek!}
