#tento soubor pøeloil Vladimir "SIR QWERTY" Sojka - http://qwerty.moje.cz
# 0. QUICK LOOK
{100}{}{Vidíš Eldridge.}

# 0. LOOK
{150}{}{Vidíš po zuby ozbrojenıho chlapa špinavıho od vazelíny. Upøenì hledí na svou sbírku zbraní na zdi a zasnìnì se usmívá.}
{151}{}{Vidíš Eldridge. Upøenì hledí na svou sbírku zbraní na zdi a zasnìnì se usmívá.}

# 1. FALLOUT2 = ENCLAVE_DESTROYED (WTG)
{200}{}{Gratuluji, hrdino! Vıteènì provedeno!}
{201}{}{::Vystøelí do vzduchu a zaène øvát a vıskat:: Enkláva je v luftu! KONEÈNÁ! VYSTUPOVAT! JUCHÚUÚUÚUÚ.}
{202}{}{::Ding-dong, Enkláva je mrtvá, Enkláva je mrtvá... ::}
{203}{}{Enkláva je dost dobrej dùvod pro kadıho obèana, aby u sebe drel zbraò.}
{204}{}{Pøíštì se tu stav, a pùjdeš na Enklávu... Rád se ujistím, e máš palebnou sílu, jakou bys mìl OPRAVDU mít.}

# 2. POWER ARMOR (WTG)
{210}{}{U všech Svatejch! Energo zbroj!}
{211}{}{Fííííííí-ha. ::Otøe si èelo:: TA energo zbroj?!}
{212}{}{Nìkdo mì štípnìte. Fakt energo zbroj?!}
{213}{}{Dupáka na mym hrobì a a ho ještì pochèije pes! Energo zbroj! V Renu!}
{214}{}{Prodáváš energo zbroj, kámo?!! Hej! Je nìkdo doma?!! Myslíš vùbec?}

# 3. NORMAL FLOATS (WTG)
{220}{}{9mm je v pohodì, ale .233 zastaví i stádo medvìdù...}
{221}{}{Teda jestli nìco vánì chci, tak je to Red Ryder vzduchovka.}
{222}{}{Nerad bych se nìkdy stál ocitl na tom špatnym konci namíøenı turbo-plasmovı pušce.}
{223}{}{Rád bych vìdìl, kde ti Salvátoøi sebrali energetické zbranì...}
{224}{}{Minulou noc se mi zas zdálo o energetickıch zbraních...}
{225}{}{Mìli bychom dostat tu zásilku nábojù do brokovnice pro Wrightovy...}
{226}{}{Teï u jen aby mìli Mordinové peníze na zaplacení svojí objednávky...}
{227}{}{Tahle zbraò? Udìlá díru do palcovıho pancíøe, jako prd.}
{228}{}{Ten kluk se nezdá, ale je to génius...}
{229}{}{Radši si bì vyvenèit ty svoje psy, ne tu všechno dokola oznaèkujou.}
{230}{}{Ty køupani si dìlaj poøádnı zásoby zbraní... je to banda tvrdejch hochù.}
{231}{}{Chtìl bych, aby mì nìkdo vykradl. Nacvièil bych palbu na pohyblivı cíl.}
{232}{}{Brzy budu muset ty fochy trochu vypucovat...}
{233}{}{Hon na ty gangstery u nelze odkládat... pøíští tejden jdeme na to.}
{234}{}{Mám tady eSeMGéèka, pistole, dynamit, granáty... a poøád jsou ještì lidi, kterı chtìj meèe a samostøíly.}

# 4. INTRO (WTG)
{240}{}{Vítej, hrdino! Zatracenì fajnová práce na Enklávì... zachránils nám ivot... Já jsem Eldridge. Pøišel sis naplnit baoh municí? Pouzdra kvérama?}
{241}{}{Vítej, hrdino! Zatracenì fajnová práce na Enklávì... zachránils nám naší kùi... Já jsem Eldridge. Pøišel sis naplnit baoh municí? Pouzdra kvérama?}
{242}{}{Vítej, poutníèe... Já jsem Eldridge. Pøišel sis naplnit baoh municí? Pouzdra kvérama?}
{243}{}{Ernnnnh? Pow-zdra na bow-chaatschky?}
{244}{}{Záleí na tom, co prodáváš.}

# 5. INTRO, FALLOUT 2 (WTG, 4)
{250}{}{Vítej zpátky, borèe!  Fajn práce v Enklávì... zachránils nám kùi a já ti za to dìkuji. }
{251}{}{Jestlie se ti tu nìco líbí, øekni si, a já ti dám *speciální* slevu, jou?}
{252}{}{Vııııbordelnì}
{253}{}{Odejdeš}
{254}{}{Skvìlé! Mohu vìdìt, co máte skladem?}
{255}{}{Nevím, jestli mi mùete pomoci... hledám takovou speciální vìcièku.}
{256}{}{Mùj šéf... }
{262}{}{Excelentní... mohu vidìt vaše specialitky?}
{257}{}{Jules mi øekl, abych se za vámi stavil, kdy budu potøebovat vyzbrojit. Tak jsem tu.}
{258}{}{Kupují Salvátoøi svoje prskavky u vás?}
{259}{}{Mám tady tu laserovou pistoli, jak jste si pøál.}
{260}{}{Umìl byste vylepšit nìjaké zbranì?}
{261}{}{Trošièku se tady porozhlídnu.}

# 6. INTRO (WTG, 9, 10, 11, 12, 13, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26)
{270}{}{Vítej! Tady mám ty nejlepší a nejpopulárnìjší prostøedky efektivní ochrany vaší velectìné holé kùe. S nimi se nemusíte bát ani do sklepa pro brambory. (Kruácky se zašklebí.)}
{272}{}{Vítej, pøíteli. Co pro tebe mohu udìlat?}
{273}{}{Jako tøeba?}
{274}{}{Nìjakı zboí?}
{276}{}{Jste pøesnì èlovìk, kterého hledám. Copak vedete za sortiment?}
{277}{}{Co máte skladem právì teï?}
{286}{}{Nemáte nìjaké speciality?}
{283}{}{Umíte vylepšit nebo upravit kvéry?}
{284}{}{Hmm, teï nemám zájem. Dík.}
{285}{}{Dneska ne, díky.}

# 7. RETARD (4, 5, 6, 19, 20)
{300}{}{Líbí se ti nìjaká ta nablejskanost? No tak, nìco tì pøece muselo zaujmout.}
{301}{}{Aha... jasnì, jasnì. (Kriticky si tì prohlíí.) Pøipomínáš mi mıho otroka, Algieho. Chceš vìdìt co máme na skladì, kámo?}
{302}{}{Jo-o}
{303}{}{Já chtít nìco nìcíèko.}
{304}{}{Nuh}

# 8. JULES (5, 6)
{310}{}{Ahá, tak Jules tì za mnou poslal.}
{311}{}{Tak ten línej bastard, øíkáš... take co pro tebe mohu udìlat, pøíteli?}
{312}{}{Tak ten línej bastard, øíkáš... mérd... omluv mou Francouzštinu. Co pro tebe mohu udìlat, dìvèe?}

# 9. CAN YOU UPGRADE WEAPONS, ALGERNON DEAD (5, 6, 8)
{330}{}{Ne, ne... tyto úpravy jsme kdysi dìlali, ale... (zatváøí se zhrzenì)... stala se strašná nehoda... zkrátka u to nedìláme. Èím jinım mohu poslouit?}
{331}{}{Dobrá tedy. Zajímalo by mne nìco jiného...}

# 10. CAN YOU MODIFY OR UPGRADE WEAPONS? (5, 6, 8, 11, 12, 13, 17)
{340}{}{No to tedy u všech ïasù umíme! Co bys tak potøeboval vylepšit?}
{1340}{}{Jasná páka. (Omrkne tvoje vybavení.) Ale nevypadá to, e máš nìco, s èím bych si mohl pohrát. Pøines mi nìjaké neposkvrnìné... eh, "normální" pistole nebo pušky a já se na to mrknu.}
{341}{}{Svedete nìco s tìmihle mımi pistolemi?}
{342}{}{Jedna moje puška by snesla jisté úpravy.}
{343}{}{Svedete nìco s pastıøskım obuškem?}
{344}{}{No tak nevadí. Zajímalo by mì nìco jiného...}
{345}{}{Vlastnì dneska nic.}
{1345}{}{Dobrá. Zajímalo by mì nìco jiného...}
{1346}{}{To zvládnu. S pánem bohem.}

# 11. PISTOLS MENU (10)
{350}{}{(Zahlédne tvùj Magnum.) Urèitì bych zvládl namontovat ti na tuhle hraèku rychlonabíjení za $}
{351}{}{Tamten Desert Eagle... jestli chceš, rozšíøím ti zásobník za $}
{352}{}{Namontujte mi na Magnuma to zrychlené nabíjení.}
{353}{}{Rozšiøte mi ten zásobník na Eaglovi.}
{354}{}{Vlastnì jsem mìl na mysli jinou zbraò...}
{355}{}{Nevadí. Chtìl jsem nìco jiného...}
{356}{}{Vlastnì ádné. Musím u jít.}
{357}{}{Mám dost hluboko do kapsy. Vrátím se, a budu mít víc penìz.}

# 12. RIFLES MENU (10)
{365}{}{(Prohlíí si tvé pušky, mávne rukou.) }
{366}{}{Zvládl bych pøidat optickı zamìøovaè na tu loveckou pušku za $}
{367}{}{Ta útoèná puška, co se ti blemcá na zádech... rozšíøím ti zásobník za $}
{368}{}{Vzadu ve fochu mám infraèervenı zamìøovaè pro noèní støelbu - namontuju ti ho na tvoji FN FAL za $}
{369}{}{Dobrá tedy... Pøidejte mi tu optiku na loveckou pušku.}
{370}{}{Rozšiøte mi zásobník na útoèné pušce.}
{371}{}{Pøipojte infrahled na FN FAL.}

# 13. MELEE MENU (10)
{385}{}{Chceš pøidat šávu tomu obušku? Nadupu ti ho za $}
{386}{}{Jasnì.}

# 14. RETURN ITEMS MENU (11, 12, 13)
{395}{}{(Eldridge si to vezme, znalecky pøedmìt prohlíí.) Dobrá tedy... chvilku poseèkej, Podívám se, co se dá dìlat. (Zmizí do zadní èásti budovy.)}
{396}{}{Okej.}

# 15. RETURN ITEMS MENU (14)
{400}{}{(Èekáš...)}
{401}{}{Èekáš...}

# 16. RETURN ITEMS MENU (15)
{405}{}{(A ještì chvilku...)}
{406}{}{Dum de dum de dum...}

# 17. RETURN ITEMS MENU (16)
{410}{}{(U u chceš odejít, kdy v tom se Eldridge vrací.) Promiò mi to zdrení... Tady to je. Tohle by mìlo udret v bezpeènı vzdálenosti všechny hajzly, kterı by ti chtìli stoupnout by jenom do tvıho stínu.}
{411}{}{Díky. Umìl byste vylepšit ještì nìjakou mojí zbraò?}
{412}{}{Díky. Ještì jsem potøeboval nìco jiného...}
{413}{}{Díky. Hned to pùjdu vyzkoušet do mìsta.}

# 18. I'M LOOKING FOR SOMETHING SPECIAL (5, 6, 7, 8)
{420}{}{No, èas od èasu skrz mìsto prochází rùznı zboí... podívej se tøeba na tohle. (Vytáhne zpod pultu nìco... divného.) Ryzí pøedváleèná technika. Je ti to k nìèemu?}
{423}{}{Tedy... to je "nìco", fajn. Mùu se podívat blíe?}
{424}{}{Nevim. Myslím, e potøebuji nìco jiného...}
{425}{}{Tohle nechci. Kadopádnì díky.}

# 19. MODULE 2 (18)
{430}{}{(Je to celkem pìknı plastikovı ètverec s dírami a kovovımi linkami natištìnımi všude okolo. Jsou tam také nakreslené jakési legraèní symboly. Pøipomíná ti to mechanickou oplatku, zaèínají se ti sbíhat sliny.)}
{431}{}{(Vypadá to jako obvod s tištìnımi spoji. Aèkoliv je docela zaprášen, vypadá, e je v celkem slušném stavu. Vypadá to jako souèást... nìèeho. Na destièce je napsáno : 'Vault Tec ovládací hlasovı modul.')}
{432}{}{(Je to spletitı obvod na kuprexidové desce. Je do nìj zasazen pamìovı èip a po stranách je mnoství poèítaèovıch pøípojek vèetnì vstupu a vıstupu. Na zaøízení je napsáno: 'Vault Tec ovládací hlasovı modul.')}
{433}{}{Já chtít hranatou dobrotu tudle}
{434}{}{Já chci nìco jinıho}
{435}{}{Já chci jít pryè}
{436}{}{"Vault Tec?" Tohle *musí* bıt dùleité. Kolik za to chcete?}
{437}{}{V poslední dobì... kolik chcete za tento modul?}
{438}{}{Ne díky, chci se zeptat na nìco jiného...}
{439}{}{Ne dnes, díky.}

# 20. BUY IT (19, 20)
{450}{}{Tøi tácy na ruku. Ber nebo nech bìet.}
{451}{}{Tak teï právì... tøi tácy. Ber nebo nech bejt.}
{452}{}{Jasná páka!}
{454}{}{Zatrhni mu tipec a vezmi si tu oplatku}
{455}{}{Nechat bejt}
{457}{}{Uh, trochu drahá sranda. Co tøeba... 1500?}
{458}{}{Ne dík. Chci se optat na nìco jiného...}
{459}{}{Radši to nechám bejt.}

# 21. BUY IT (20)
{470}{}{$2500. A to je moje poslední nabídka.}
{471}{}{Fajn, fajn. Tady je máte.}
{472}{}{Tak na to zapomeòte. Chci nìco jinıho...}
{473}{}{Ne, tak to dík. Ještì se uvidíme.}
{474}{}{Tak to je i na mì moc. Promluvíme si o tom, a se enu nìjakı peníze.}

# 22. BUY IT (20, 21)
{480}{}{(Usmívá se a mne si ruce, jak pokládáš peníze na stùl.) Vıbornì, tady to je. Ještì nìco? }
{481}{}{(Pøemıšlí o tom chvilku, prohlédne si tì a pak mávne rukou.) No tak jo... A jsem škodnej, vezmi si to. (Podává ti modul, bere peníze.) }
{482}{}{Ještì nìco jiného?}
{485}{}{Jo, ještì by se mi nìco hodilo...}
{486}{}{U nic, díky.}

# 23. CAN I BUY LASER PISTOLS HERE? (5, 6, 8)
{495}{}{(Zamrká pøekvapením a pak se rozesmìje.) HOHÓ! Ne, kdepak... ty zbranì jsou o nìèem jinım, ne? Jasnì e bych CHTÌL nìjakı dostat do rukou... jen pova - ten dostøel, síla, kadence...(Zírá do prázdna a vzdychá.)}
{496}{}{Co kdybyste mohl ode mì nìjakou dostat?}
{497}{}{Dobøe, poohlídnu se vám po nìjaké. Ještì se chci zeptat na nìco jinıho...}
{498}{}{No, jen jsem se ptal. Díky, Eldridgi.}

# 24. WHAT IF I GOT YOU ONE? (23)
{505}{}{(Podívá se na tebe úkosem, jako by se rozhodoval, jestli ti má vìøit nebo ne.) Neøekl bych ne. Zaplatil bych ti za tvou námahu... (Zamraèí se.)... ale ádnı podfuky, to ti øíkám!}
{506}{}{Není problém... Jednu s sebou mám. Tady jí máte.}
{507}{}{Hmm, poohlídnu se. Ale ještì pøed tím se chci zeptat...}
{508}{}{Hmm, pak tedy nic. Moná e mi mùete pomoci s nìèím jinım...}
{509}{}{Dobrá. Jednu pro tebe èmajznu a pak se vrátím.}
{510}{}{To nemùu slíbit... vypadá to, e já a neštìstí cestujeme spolu. Uvidím se pozdìji, Eldridgi.}

# 25. LASER PISTOL RETRIEVED? (5, 6, 8, 24)
{520}{}{Vıbornì, klidnì mi nachèij na záda a øekni, e prší! }
{521}{}{Zatracenì dobøe! Abych dostál svému slovu, tady máš odmìnu... }
{522}{}{(Dává ti hrst penìz, bere si pistoli.) Krucinál... divnì vypadá tahle vìcièka, co? (Prohlíí hlaveò.) Hmmm...}
{523}{}{Potøebuji ještì nìco jiného...}
{524}{}{Bylo mi potìšením s vámi obchodovat, Eldridgi. Pìknì si to uijte.}

# 26. REP: MADE MAN (5, 6, 8)
{530}{}{(Eldridge si tì sjede od hlavy k patì, pøièem nabere trochu respektu.) Ale jistì, samozøejmì. Dovolte mi, abych vám ukázal naše speciální zboí... vše se slevou, pochopitelnì.}
{532}{}{Vlastnì potøebuji nìco jiného...}
{533}{}{No nic. Ještì se vrátím.}

# 27. AFTER HOURS (Dogs Barking)
{545}{}{Zavøete ty drky vy èoklové, slyšíte?}
{546}{}{Sklapnout tam, vy uštìkanı ksichti!}
{547}{}{Noèní bestie... pøestaòte tam vyvádìt!}
{548}{}{Rexi! Pajdo! Fifinko! Radši tam sklapnìte nebo tam na vás vlítnu!}
{549}{}{Zatracenı psi!}
{550}{}{Teda ale u ani MUK! e tam pùjdu a seøeu vás!}

# 28. DOOR
{560}{}{Snad si nemyslíš, e jsem slepej?}
{561}{}{Dej ty pracky vod tìch dvéøí!}
{562}{}{Nech ty dveøe smrdìt!}
{563}{}{Ještì se tìch dveøí dotkneš a bude to poslední vìc, kterı se tvı prašivı ruce dotkly.}
{564}{}{Poslední èlovìk, kterej se dotkl tìch dveøí, je teï zakopanej v Golgotì. U na nì nesahej.}

# 29. ROOM:
{575}{}{Co tu dìláš?! Vypadni! Vypal vodsud!}
{576}{}{Vzadu nemáš co dìlat! Vypal!}
{577}{}{Vypadni ze skladu nebo budeš chytat olovo!}
{578}{}{Ještì chvilku tam zùstaò a pocvièim si støelbu na pohyblivej cíl!}

{600}{}{Máme zavøeno, chlapèe... }
{601}{}{Máme zavøeno, sleèinko... }
{610}{}{Doporuèuju ti vypadnout, sic ti ustøelim makovici pryè.}

{700}{}{Zatrápenı psi! Jdu si lehnout.}
{701}{}{Pitomı psi! Zejtra vás pìknì pochovám. Ale do hrobu.}
{702}{}{Mohli byste sklapnout, vy zatracenı èuby! Nikdo pøece neni tak blbej, aby se vloupal do kšeftu s kvérama!}

{800}{}{Doruèil jsi laserovou pistoli Eldridgeovi.}

# END LINES
{5256}{}{...mi øekl, abych se zastavil a e mì "vybavíte"}
{5500}{}{.}
