#tento soubor pøeložil Vladimir "SIR QWERTY" Sojka - http://qwerty.moje.cz
# QUICK LOOK
{100}{}{Vidíš nabíjeèku.}

# 1. LOOK (PLAYER IS MALE)
{150}{}{Vidíš prùmìrnì atraktivní ženu. Vypadá to, že tì pozoruje.}
{151}{}{Vidíš nabíjeèku. Vypadá to, že váhá, jestli si tì má vùbec nìjak všímat.}

# 2. LOOK (PLAYER IS FEMALE)
{160}{}{Vidíš prùmìrnì atraktivní ženu. Dívá se na tebe, jako bys byla její rival.}
{161}{}{Vidíš nabíjeèku. Dívá se na tebe jako na sokyni.}

# 3. [ENCLAVE DESTROYED]
{200}{}{Oh mùj... to je on. }
{201}{}{Jsi ten nejlepší høebec na svìtì.}
{202}{}{::Omdlévá::}
{203}{}{Slyšela jsem, že tì hledají Bratøi. Chtìjí natoèit film podle tvého dobrodružství.}
{204}{}{Jasnì, }
{205}{}{::Tleská::}
{206}{}{::Pokøikuje::}
{207}{}{Oh mùj... to je ona. }
{208}{}{Fandím ti, holka!}
{209}{}{::Dává ti znamení vztyèeným palcem::}

# 4. [POWER ARMOR]
{225}{}{Neexistuje, tohle já 'nabíjet' nebudu}
{226}{}{Jak chceš jít do koupelny s touhle vìcí na sobì?}
{227}{}{To je jako nìjaký druh vibrátoru?}
{228}{}{Nìjaká nová OCHRANA?}

# 5. [MALE, PORN STAR]
{235}{}{Potøebuješ nìco, }
{236}{}{Hej tady, }
{237}{}{Podívejte! To je on!}
{238}{}{To je }
{239}{}{Nìkdy bych chtìla, aby se mnou hrál }
{240}{}{Z toho chlápka vlhnu.}
{241}{}{Vyspat se s nim a umøít.}
{242}{}{Zatracenì mlsná kobra, tam mezi tvejma nohama.}

# 6. [PORN STAR, FEMALE]
{245}{}{Potøebovala bys nìco, }
{246}{}{Ještì jednoho herce dneska a asi vrhnu.}
{247}{}{Bejt nabíjeèka není žádná sranda.}
{248}{}{Slyšela jsem, že mezi Rodinama to zaèíná bejt dost na nože.}
{249}{}{Minulej tejden jsem nakopala Julese do jeho orgánù. Víš kterejch, že jo.}
{250}{}{Chtìla bych, aby mì Bratøi nechali si zahrát.}
{251}{}{Nevím, co na ní ti Bratøi vidí...}

# 7. [MALE, PRIZEFIGHTER]
{255}{}{Ach bože... to je on. }
{256}{}{Podívejte se na jeho svaly! Asi to se mnou švihne...}
{257}{}{Je stavìnej jako tank. Mrkejte holky na tu jeho hlaveò.}
{258}{}{Podívejte se na tu hlaveò...}
{259}{}{Je celej mùj...}
{260}{}{::Vzdych::}
{261}{}{Ten teda dovede ženskou rozjet.}
{262}{}{Zatracenì mlsná kobra, tam mezi tvejma nohama.}

# 8. [FEMALE, PRIZEFIGHTER]
{270}{}{Ah bože... To je ona.}
{271}{}{Vítejte ve studiu, madam.}
{272}{}{Vypadá tak... (otøepe se)... nebezpeènì.}
{273}{}{Je dost sexy.}
{274}{}{Ahoj. Dej mi vìdìt, kdybys nìco potøebovala.}

# 9. [MALE, MADE MAN/BERSERKER]
{280}{}{Oh bože...To je on.}
{281}{}{Vítejte ve studiu, pane.}
{282}{}{Vypadá tak... (otøepe se)... nebezpeènì.}
{283}{}{To je ten drsòák - koneènì ho poznávám.}
{284}{}{Ten teda dovede ženskou rozhicovat.}
{285}{}{Zatracenì mlsná kobra, tam mezi tvejma nohama.}

# 10. [FEMALE, MADE MAN/BERSERKER]
{290}{}{Ah bože... To je ona.}
{291}{}{Vítejte ve studiu, madam.}
{292}{}{Vypadá tak... (otøepe se)... nebezpeènì.}
{293}{}{Je dost sexy.}
{294}{}{Ahoj. Dej mi vìdìt, kdybys nìco potøebovala.}

# 11. [MALE, NO REP + MYRON]
{300}{}{A doprdele! To je Myron! Utíkejte!}
{301}{}{A je to v hajzlu! To je Myron. Zklidni to... smrdí to prùserem.}
{302}{}{Radši drž Myrona dál ode mì.}
{303}{}{Myrone, radši se ke mnì ani DOPRDELE nepøibližuj.}
{304}{}{Tak jestli tady Myron zaène pracovat, konèim.}
{305}{}{Myrone, už jsi pøekroèil pìtivteøinovou hranici panicù?}
{306}{}{Myrone, radši odsud vypadni, než tì Bratøi zblejsknou.}

# 12. FLOAT/[LEATHER]
{315}{}{Tyhle kožený obludky snad nevìdi, že tu maj bejt jenom ve støedu?}
{316}{}{Skvìlé. Další S&M na obzoru.}
{317}{}{Oooooh. Èerná kùže. Tak TOHLE tu ještì nebylo.}
{318}{}{Do pøíštího tejdne nemáme žádnou kùži nebo svazování v plánu.}
{319}{}{Skvìlé, další slaïouš v kùži.}
{320}{}{Podívej se, zlato, v kùži si tu mùžeš zahrát až ve støedu, fajn?}

# 13. [NO REP + BONENOSE]
{325}{}{Ještì jednoho herce dneska a asi vrhnu.}
{326}{}{Bejt nabíjeèka není vùbec snadný.}
{327}{}{Slyšela jsem, že mezi Rodinama to zaèíná bejt dost na nože.}
{328}{}{Minulej tejden jsem nakopala Julese do jeho orgánù. Víš kterejch, že jo.}
{329}{}{Ten mladík s kostí v nose se vypadá celkem sladce. Z pohledu sadomasochisty.}
{330}{}{Kdo je ten chlapík s kostí v nose?}
{331}{}{Vyzkoušejte toho divocha s kostí v nose. Vypadá, že vydrží dlouho.}
{332}{}{Fíha, už jsem vidìla hodnì úrazù na scénì, Ale ještì ne chlapíka, kterej by se napích na kost nosem.}
{333}{}{Chtìla bych, aby mì Bratøi vzali do filmu.}
{334}{}{::Upøenì na tebe zírá::}
{335}{}{Skvìlý. Zas DALŠÍ nabíjeèka. Ta bude pracovat aspoò za polovièní cenu, to se pozná už od pohledu.}
{336}{}{Kdo je to?}
{337}{}{Kdo jsi?}

# 14. [NO REP]
{345}{}{Ještì jednoho herce dneska a asi vrhnu.}
{346}{}{Bejt nabíjeèka není vùbec snadný.}
{347}{}{Slyšela jsem, že mezi Rodinama to zaèíná bejt dost na nože.}
{348}{}{Minulej tejden jsem nakopala Julese do jeho orgánù. Víš kterejch, že jo.}
{349}{}{Chtìla bych, aby mì Bratøi vzali do filmu.}
{350}{}{Skvìlý. Zas DALŠÍ nabíjeèka. Ta bude pracovat aspoò za polovièní cenu, to se pozná už od pohledu.}
{351}{}{::Zírá na tebe::}
{352}{}{Kterápak to je?}
{353}{}{Kdo jsi?}

# 15. [ENCLAVE DESTROYED]
{360}{}{Enkláva? Prezident? Povìz mi o tom všechno.}
{361}{}{Tom Hill je fakt frajer.}
{362}{}{Oni poøád vedli VÁLKU?! No vážnì! Díky bohu, že s nima zatoèil nìkdo takovej, jako jsi ty.}
{363}{}{Teda jsi vážnì bourák. Teda jako že zaèal jako divoch s holym zadkem - bez urážky - a jen tak se vydal zachránit celej svìt. Vážnì jsi sekáè. Šmitec.}
{364}{}{Mìl by sis tuhle hru zahrát taky za jinou postavu.}
{365}{}{Povìz mi všechno o tvém boji v Enklávì... Koupim ti pivko.}
{366}{}{Myslím, že tì hledají Bratøi. Chtìjí natoèit film podle tvého dobrodružství.}

# 16. [PORN STAR]
{370}{}{Jejky. Upustila jsem nìco do tvých trenýrek. Dovol mi to vylovit.}
{371}{}{Ehm, nezašel bys na pár panákù nìkam do hospody, co? A co trocha nezávazného sexu?}
{372}{}{Co že jsi tak fit? Trénuješ?}
{373}{}{Mùžeš se mi podepsat? Na prsa?}
{374}{}{Jsi naše pomoc, }
{375}{}{Budu potøebovat trošku pomoct s tou tvojí "zbraní".}
{376}{}{Slyšela jsem, že je dost... tvrdý s tebou pracovat.}
{377}{}{Prej to vydržíš dlouho. To se mi líbí.}
{378}{}{Fakt jsem ráda, že tì znám! Tedy, jéje, ty jsi }
{379}{}{Eh, já vím, že se nic nebude natáèet, ale nechtìl bys, abych tì trošku 'nabila'?}
{380}{}{Hledáš nabíjeèku?}
{381}{}{Hledáš ïolík pro svùj kolík, }
{382}{}{Hroznì ses mi líbil v Pelíškách.}
{383}{}{Fakt jsi to dobøe zahrál ve filmu Sex noci svatojánské.}
{384}{}{Skvìle hraješ.}
{385}{}{Vidìla jsem tì ve filmu "Prci, prci, prcièky". Fakt skvìlý, inspirace.}
{386}{}{Nikde jsem tu Bráchy nevidìla... možná mùžeš zkusit kanceláø?}
{387}{}{Mùžeš se za mnì u Korsických pøimluvit? Ráda bych si zahrála ve filmu.}
{388}{}{Nabíjeèky mají dùležitou funkci - udržují herce v kondici.}
{389}{}{Mohla bych si zahrát v tvém dalším filmu?}
{390}{}{Vážnì nechci být nabíjeèka celej svùj život... To opravdu ne.}
{391}{}{Dìlám to jenom proto, abych si mohla zaplatit školu.}
{392}{}{Mùj kluk neví, že tu pracuju.}
{393}{}{Nìkdy ti povyprávím, co tu všechno musíme dìlat.}
{394}{}{Mùj kluk neví, že tu pracuju.}
{395}{}{Nìkterý herci by se mìli povinnì sprchovat. A né jenom použít kolínskou. Tfujtajxl.}
{396}{}{Hroznì bych si chtìla zahrát.}
{397}{}{Moje holka neví, že tu pracuju.}
{398}{}{Mùžeš se mi podepsat?}
{399}{}{Zajdeš na panáka? Ovšem pokud jsi na holky, samozøejmì.}
{400}{}{::Ignoruje tì::}

# 17. [PRIZEFIGHTER]
{420}{}{Tak co, šampióne? Neskoèíme spolu do ringu?}
{421}{}{Máš fajn "dìlo".}
{422}{}{Potøebuješ nìkoho, kdo by se o tebe postaral, borèe?}
{423}{}{Konèíš s boxem, zaèínáš s pornem? Stejná makaèka, jiný jevištì.}
{424}{}{Taky zaèínáš s timhle kšeftem? Vítej na palubì, borèe.}
{425}{}{Taky zaèínáš s timhle kšeftem? Hmm, aspoò nemusíš zaèínat ze stejnýho postavení tak jako já.}
{426}{}{Já? Já jsem nabíjeèka. Nìkdy.}
{427}{}{Nabíjeèky mají dùležitou funkci - udržují herce v kondici.}
{428}{}{Bratøi øíkají, že jsem k nezaplacení. Asi proto se mnou tak èasto spìj.}
{429}{}{Mìl bys zaèít s pornografickým prùmyslem. Máš na to postavu.}
{430}{}{Chceš si zazápasit?}
{431}{}{Nìkdy ti povyprávím, co tu všechno musíme dìlat.}
{432}{}{Dej si bacha na toho Ždímaèku. Je vážnì ujetej. Totál. Jednou mi chtìl ukousnout ucho.}
{433}{}{Ahoj krásko. Mùžu ti s *nìèím* pomoct?}
{434}{}{Nehledáte spoleènost, madam?}
{435}{}{Chcete to obvyklým zpùsobem nebo nìco extra, madam?}

# 18. [MADE MAN]
{450}{}{Ahoj frajere. Mùžu ti s... *nìèím* pomoci?}
{451}{}{Nehledáš spoleènost?}
{452}{}{Chceš to obvyklým zpùsobem nebo nìco extra?}
{453}{}{Potøebuješ nìkoho, kdo by ti vypomáhal?}
{454}{}{Mùžeš za mì ztratit dobrý slovo u šéfa?}
{455}{}{Taky se chceš angažovat?}
{456}{}{Mìl bys zaèít s pornografií. Máš na to postavu.}
{457}{}{Nìkdy ti povyprávím, co tu všechno musíme dìlat.}
{458}{}{Zdravíèko, madam. Mùžu vám s *nìèím* pomoci?}
{459}{}{Ehm, jestli hledáte spoleènost, sleèno...}
{460}{}{Chcete to obvyklým zpùsobem...?}

# 19. [BONE-NOSE]
{465}{}{Ne díky. To si to snad radši si to udìlám sama... kaktusem.}
{466}{}{Ty? Promiò, ale tak špatnì na tom zas nejsem.}
{467}{}{Ehm, tvùj kámoš si tou kostí v nose kompenzuje nìjakej nedostatek?}
{468}{}{Co ten tvùj kámoš sleduje tou kostí v nose?}
{469}{}{Tvùj kámoš by se mohl líbit naší støedeèní zamìstnankyni. Zamìøuje se na sado-maso.}
{470}{}{Co je to za roztomilýho køováka, ten chlapík s kostí?}
{471}{}{Øekni svými pøíteli s kostí v nose, že to dotáhne daleko v tomhle prùmyslovym odvìtví.}
{472}{}{Fíha, už jsem vidìla hodnì zranìní na scénì, ale zaraženou kost v nose ještì ne.}
{473}{}{Nikde jsem tu Bratry nevidìla... co zkusit kanceláø?}
{474}{}{Nabíjeèky mají dùležitou funkci - udržují herce v kondici.}
{475}{}{Hroznì si chci zahrát.}
{476}{}{Vážnì nechci být nabíjeèka celej svùj život... To opravdu ne.}
{477}{}{Mùj kluk neví, že tu pracuju.}
{478}{}{Potøebuješ s nìèím píchnout?}
{479}{}{Jestli hledáš práci, promluv si s Korsickými.}
{480}{}{Tohle dìlám jenom proto, abych zaplatila nájem na koleji.}
{481}{}{Klidnì bych tomu jednomu vrazila jednu pìstí. Zadarmo.}
{482}{}{To není tím, že bych s tebou prostì nechtìla mluvit.. moment, to JE tim.}
{483}{}{Potøebuju si dát dvacet.}
{484}{}{Nìkdy ti povyprávím, co tu všechno musíme dìlat.}
{485}{}{Nemáš náhodou nìjaký brouèky, co? To bychom to museli oholit.}
{486}{}{Jsi nová nabíjeèka?}
{487}{}{Nemáš náhodou kapesník? Jeden z hercù nevydržel... mìl nehodu.}
{488}{}{Jenom nám do hercù nekousej a bude to v pohodì.}
{489}{}{Nìkterý herci by se mìli povinnì sprchovat. A né se jenom napatlat kolínskou.}
{490}{}{Jsi tu novì?}
{491}{}{Lízání? Už jsem si zvykla.}

# 20. [NO REP]
{500}{}{Ne, díky. Radši si to udìlám násadou od krumpáèe.}
{501}{}{Ty? Tak špatnì na tom zase nejsem.}
{502}{}{Nikde jsem tu Bratry nevidìla... co zkusit kanceláø?}
{503}{}{Nabíjeèky mají dùležitou funkci - udržují herce v kondici.}
{504}{}{Hroznì si chci zahrát.}
{505}{}{Vážnì nechci být nabíjeèka celej svùj život... To opravdu ne.}
{506}{}{Mùj kluk neví, že tu pracuju.}
{507}{}{Potøebuješ s nìèím píchnout?}
{508}{}{Jestli hledáš práci, promluv si s Korsickými.}
{509}{}{Tohle dìlám jenom proto, abych zaplatila nájem na koleji.}
{510}{}{Klidnì bych tomu jednomu vrazila jednu pìstí. Zadarmo.}
{511}{}{To není tím, že bych s tebou prostì nechtìla mluvit.. moment, to JE tim.}
{512}{}{Potøebuju si dát dvacet.}
{513}{}{Nìkdy ti povyprávím, co tu všechno musíme dìlat.}
{514}{}{Nemáš *problémy* s kùží, že ne?}
{515}{}{Jsi nová nabíjeèka?}
{516}{}{Nemáš náhodou kapesník? Jeden z hercù nevydržel... mìl nehodu.}
{517}{}{Jenom nám do hercù nekousej a bude to v pohodì.}
{518}{}{Nìkterý herci by se mìli povinnì sprchovat. A né se jenom napatlat kolínskou.}
{519}{}{Jsi tu novì?}
{520}{}{Lízání? Už jsem si zvykla.}

{1200}{}{. Takhle nakopat Enklávì prdel.}
{1204}{}{! Takhle se na Enklávu musí!}
{1207}{}{. Takhle nakopat Enklávì prdel. Supr.}
{1235}{}{?}
{1236}{}{!}
{1238}{}{!}
{1239}{}{.}
{1245}{}{?}
{1255}{}{.}
{1270}{}{.}
{1280}{}{.}
{1290}{}{.}
{1374}{}{?}
{1378}{}{!}
{1381}{}{?}
