#tento soubor pøeloil Vladimir "SIR QWERTY" Sojka - http://qwerty.moje.cz
# quick looks
{100}{}{Vidíš zápasníka.}
{101}{}{Vidíš Evana Hollyfielda.}

# examines
{150}{}{Vidíš zavalitého èernocha s hranatou èelistí. Vypadá, jako by mu nìkdo strèil uši do mlejnku na maso.}
{151}{}{Vypadá, jako by mu nìkdo strèil uši do mlejnku na maso.}
{152}{}{Vypadá, jako by mu nìkdo strèil uši do mlejnku na maso.}

# FLOAT DIALOGUES
{200}{}{Hnffff}
{201}{}{Hnrrgggg}
{202}{}{::Cosi si brblá a mne si své ponièené placháky::}
{203}{}{::Zírá::}

# CLICK DIALOGUE
# MALE, PRIZEFIGHTER
{300}{}{::Pøikládá ruce k uším a upøenì tì pozoruje::}
# other
{301}{}{Já se rád peru}
{302}{}{S Majkem se vdycky pereme}
{303}{}{Jednou jsem já Mika pøepral, on mi za to uši seral}
{304}{}{Majk mi ukousnul obì uši, protoe mìl velkej hlad}
{305}{}{Špatnì slyšim}
{306}{}{::Drbe se za tím, co døíve bıvalo uchem::}
{307}{}{He?}
{308}{}{Coe? Není tì slyšet.}
{309}{}{Tak dlouho se zápasí, a se ucho utrhne}
# FEMALE, ANY BUT PRIZEFIGHTER
{310}{}{Koušeš?}
{311}{}{Zdravíèko, panáèku}
{312}{}{Zdravíèko, sleèinko}
{313}{}{Chceš se prát?}
{314}{}{Já se rád peru}
{315}{}{S Majkem se vdycky pereme}
{316}{}{Jednou jsem já Majka pøepral, on mi za to uši seral}
{317}{}{Majk mi ukousnul obì uši, protoe mìl velkej hlad}
{318}{}{Špatnì slyšim.}
{319}{}{::Drbe se za tím, co døíve bıvalo uchem::}
{320}{}{He?}
{321}{}{Coe? Není tì slyšet.}
{322}{}{Tak dlouho se zápasí, a se ucho utrhne}
