#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
# 0. QUICK LOOK
{100}{}{Vidíš Poøezanıho Jimma J.}

# 0. LOOK
{150}{}{Vidíš nepokojného mue. Po tváøi se mu táhne dlouhá, rozeklaná jizva, která mu zpùsobuje drobné tiky.}
{151}{}{Vidíš Poøezanıho Jimma J. Vyhlíí dálšího zákazníka.}
{152}{}{Vidíš Poøezanıho Jimma J. Kıvnul na tebe, kdy zachytil tvùj pohled.}
{153}{}{Vidíš Poøezanıho Jimma J. Zachytil tvùj pohled a mává na tebe, a pøíjdeš blí.}

# 1. FLOAT (ENCLAVE DESTROYED = TRUE) (WTG)
{200}{}{Hej, no esli to není }
{201}{}{Hej, }
{202}{}{Támdle de jeden tvrdej bouchaè...a Jimmy J pozná tvdrıho bouchaèe, dy òákıho vidí.}
{203}{}{Né kadej den nìkdo píchne prezidenta v jeho vlastním bejváku, co?.}
{204}{}{Nechceš si voslavit vítìzství s trochou extra špica Jetu vod  starıho paráka Poøezanıho Jimma, hrdino?}
{205}{}{Zachraò svìt, a Poøezanej Jimmy ti DÁ  svìt, Supermane. Všecek Jet, kerej zvládneš napíchat.}
{206}{}{Sem slyšel, e se po tobì ptali Korsiètí bráchové, hrdino...}

# 2. FLOAT DIALOGUES (WTG)
{220}{}{Poøezanej Jimmy sem já, a mám všecek JET co POTØEBUJEŠ, kámo.}
{221}{}{Chceš se prolítnout? Poøezanej je tvùj èlovìk, kámo.}
{222}{}{Chceš se vznášet? Poøezanej Jimmy tu má pro tebe lísteèek, chceš?.}
{223}{}{Chceš bejt super, dej si Jet vod Poøezanıho Jimma.}
{224}{}{Nebaví tì to na zemi, šéfe? Poøezanej Jimmy tu má øešení.}
{225}{}{Tentokrát je to spešl kvalitka, jen pro tebe, dej si.}
{226}{}{Mùeš si koupit sraèku, ze kterı ti bude akorát blbì, ale u Poøezanıho Jimma máš vdycky da best.}
{227}{}{Jimmy má dycky votevøíno, kámo.}
{228}{}{Chceš lítat jak tryskáè? Tak si dej Jimmyho Deáè!.}

# 3. INTRO, FIRST TIME (WTG)
{240}{}{(Tento mu má lehkı tik ve tváøi a dlouhou jizvu pøes tváø. Jizva vypadá jako po noi.) }
{241}{}{Brácho, všim sem si tì sotvas vyšlápnul na ulici. Víš co vidim?}
{242}{}{Ségro, všim sem si tì sotvas vyšlápnul na ulici. Víš co vidim?}
{243}{}{Vidíš mnì}
{244}{}{Co vidíš?!Co vidíš?!}
{245}{}{Já muset  --}
{246}{}{Co vidíš?}
{247}{}{Dr hubu ty--}
{248}{}{Sorry, nezájem --}

# 4. SPIEL 1 (3)
{260}{}{Vidim pilota. Vidim, nìkoho, kdo chce lítat. Potøebuješ akorát trochu píchnout, trochu JETU.}
{261}{}{Hunh? Jet? Na nebi? Kam?}
{263}{}{Jet, huh? Chci se zeptat--}
{264}{}{Hele, já -}

# 5. SPIEL 2 (4)
{270}{}{A mùj pilotní kámoši, kdy se jedná vo JET, Poøezanej Jimmy J je tvùj MU Mám nejlepší zboí v Novım Renu, èistej
 Jet, silnej Jet, BEZPEÈNEJ Jet.}
{271}{}{Kdo jet? Na nebi nic?}
{272}{}{Já muset JÍT--}
{273}{}{Poøezanej Jimmy J, jo? Hele, mám otázku--}
{274}{}{Hele mì nezajímá --}

# 6. SPIEL 3 (5)
{280}{}{OSTATNÍ dıleøi, ty nezajímá kvalita, ale já, já si dávám pozor, aby všici mí klienti mìli dostatek a kvalitku,
 jasan? To je mùj zpùsob, kámo. Zpùsob Jimma J.}
{281}{}{Ja nevidìt nikoho jet. Ty le }
{5281}{}{ Ty leš }
{6281}{}{ o jetu?}
{282}{}{PUS JA CHTÍT--}
{283}{}{Hej,Jimmyho zpùsob zní skvìle, ale já se chci na nìco ze--}
{284}{}{Ne, nemyslím e -}

{5200}{}{! Poï si od J-J vzít svùj JET...}
{5201}{}{! Jestli chceš oslavovat s JETem, promluv si se starım Jimmym J...}
#related
# 7. 2nd TIME, PLAYER GOT THE BULLSHIT SPEECH (WTG)
{290}{}{Vìdìl sem, e se vrátíš, vìdìl sem to! Neøíkal to snad Poøezanej Jimmy J? Udruj je šastnı a voni tì nezklamou.
 Take mùj leteckej kámo...co pro tebe mùe Poøezanej Jimmy J spáchat dneska?}
{291}{}{No no no, jestli pak to není mùj "pøítel"...pøišels, ponìváè POTØEBUJEŠ nìco vod Poøezanıho Jimma?}
{292}{}{Um...Já zapomìt co ja chtiti  mluvit. Já jít}
{294}{}{My kšefty kšefty? Já CHTÍT}
{295}{}{Máš Jet? No, tak tedy obchodujme....kamaráde.}
{296}{}{Kde jsi pøišel k té jizvì, Jimmy?}
{297}{}{Odkud bereš Jet, Jimmy?}
{298}{}{Víš kdo dál tomu  Wrightovic dìcku Jet, kterı ho zabil?}
{299}{}{Pøedtím jsi øíkal, e tvùj Jet je "nejbezpeènìjší". Copak se tady vyskytuje nìjakı ... nebezpeènı?}
{300}{}{Dneska nic, dík, Jimmy.}

# 8. SPIEL 4 (6, 10, 12, 13, 14, 15, 16, 17, 18, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 33, 36, 39, 40, 41, 42, 43, 44, 45)
{310}{}{Tak co povíš, kámo? Co pro tebe mùe Poøezanej Jimmy J udìlat dneska?}
{311}{}{Jo, co chceš? Vymáèkni se, nemám celej den.}
{312}{}{Máš chutì, máš otázky...s èím ti mùe Poøezanej J J píchnout?}
{314}{}{Já zapo- vzpome - zapomnìt! Já koneènì vzpomnìt a zas zapo- zapomnìt! }
{5314}{}{ ZABÍT TÌ}

# 9. JIMMY FINALLY RECOGNIZES CHARACTER (7, 8, 9)
{330}{}{Hej...ty seš mì nìjakej povìdomej. Znám tì, kámo?}
{331}{}{Pøísahal bych na plesnivou nohu, e u jsem tì vidìl. ten tvùj ksicht je mi nìjakej povìdomej...}
{332}{}{JA MOC VELKA HRDINA, DOHRAT HRA A NAKOPAT PRDEL A VYHODIT BENZIN VÌ DO LUFT A CHRANIT SVÌT}
{333}{}{Ja bít v ringu a moc øvacích lidi èumìt a øvát zabij hajzla tak ja mlatit dokud on nepad na zem celej vod krev}
{334}{}{Já kšefty z lidi co øvou na bùh}
{335}{}{Já MAFIAN. Ja dulete-dule- duleité chlap v Reenu}
{336}{}{Jak mùe nìkdo znát DOOPRAVDY druhého, Jimmy? Je to vùbec moné na tomto svìtì, nebo a tehdy, kdy se osvobodíme od
 svıch fyzickıch tìl?}
{337}{}{Já CHTÍT mluvit, ale ty mluvit sám tak èau}
{338}{}{No, zastavil jsem plány Enklávy na zabití všech na tomto svìtì, porazil Prezidenta,
 vyhodil do vzduchu jejich základnu a taktak unikl s holım ivotem.}
{339}{}{Bojoval jsem v boxerském ringu.}
{340}{}{Natoèil jsem pár filmù. Slyšel jsi o }
{5340}{}{?}
{341}{}{Mám úzké vztahy s rodinou }
{5341}{}{ .}
{342}{}{Ne,nemyslím, Jimmy. Kšeftujem nebo ne?}
{343}{}{Ne, nemyslím. Hele, chci se zeptat...}
{344}{}{Ne, mìl bych jít. Pozdìji, Jimmy.}

# 10. JIMMY FINALLY RECOGNIZES CHARACTER, VOL 2 (9)
{360}{}{To je vono! Já vìdìl, e sem tì u nìkde vidìl! Kaskru, proès to nìøek hned a nechal Jimma lámat si kebuli?!
 Co pro tebe mùu udìlat?}
{361}{}{Um...ja zapomìt. Jít.}
{363}{}{No, sháním nìjakı Jet...}
{364}{}{Hej, chci nìco jinıho...}
{365}{}{Musím jít. Pozdìji, Jimmy.}

# 11. PHILOSOPHY (9)
{375}{}{(Jimmy upadl do uaslého mlèení. Asi jsi mu zparalyzoval mozek.)}
{376}{}{(Vezmi mu všechno, co má.)}
{377}{}{ To by staèilo.}

# 12. SCAR (7, 8)
{385}{}{Poøezanej Jimmy J je plnej lásky, kámo, ale svìt né dycky miluje Poøezanıho Jimma, víš?}
{386}{}{Mì to povídej.}
{387}{}{Jako bych to nevìdìl. Nìkdy je svìt krutá potvora.}
{388}{}{To je skvìlej pøíbeh. Ale já se chci ještì na nìco zeptat...}
{389}{}{Dobrej pøíbìh. Teï - ty máš Jet, já mám prachy...domluvíme se?}
{390}{}{Dobrej pøíbìh. Ale já musím mizet, Jimmy.}

# 13. SCAR 2 (12)
{400}{}{(Ukazuje na svou jizvu.) Tohle sem dostal, kdy sem mlátil jednoho HNUSNİHO zkurvysyna, protoe ten parchant byl hrubej
 na jednu mou kámošku, jasnı?}
{401}{}{Fakt? Co se stalo?}
{402}{}{Vánì? Teda, chlapi co bijou enskı by zaslouili povìsit za koule do prùvanu.}

# 14. SCAR 3 (13)
{415}{}{Staví se do bojového postoje.) Tak jsem k nìmu pøišel, jo, a von vytáh KUDLU proti mejm holejm rukám, jasnı? Take se mu poved šastnej zásah, ne sem ... *BUM!* nakopal jeho prdel!}
{416}{}{Jo, fakt? Jules øíká, e jsi lítal na Jetu a poøezal sis ksicht, kdy ses snail oholit si hubu bojovım noem}
{417}{}{Nekecáš? Nemyslím, e by to se mnou dopadlo tak dobøe. Ty vole, ten chlap tì moh ZABÍT!}
{418}{}{SQÌLEJ pøíbìh. Hele, ještì se chci zeptat...}
{419}{}{Jo...hele, mám nìjakı peníze...domluvíme se?}
{420}{}{Dobrej pøíbìh...tak dobrej, e u musím jít.}

# 15. TRUTH ABOUT SCAR REVEALED (14)
{430}{}{Cooooo...? Jules mi mùe políbit moji pøírodnì èernou øi, a to je jediná prdel ve mìstì, kterou nevylízal. Neví ani HOVNO. 
 Nemá vodvahu øíct mi to do voblièeje. TY se rozhodni, kdo z nás dvou kecá.}
{431}{}{Jo jo..... hele, ty máš JET ja prachy...kšeft?}
{432}{}{Jo jo....Jimmy, chci se ještì zeptat...}
{433}{}{Hele pane Velká Hubo, jdeme obchodovat, nebo si mám sednout a poslouchat tvı kecy celej den?}
{434}{}{U jsem slyšel dost, Jimmy. Dej si bacha, a se budeš holit, okej?}
{435}{}{Tak dobøe. Nashle, Jimmy.}

# 16. GO ON, JIMMY, TELL THE STORY 1 (14)
{445}{}{Skoro to udìlal! Víš, kdy jsem se do toho dostal, nemysle jsem si 'Já sem pan tvrïák a tak dál' ale...}
{446}{}{Udìlal jsi to, co je podle tebe pøirozenı, ejo?}
{447}{}{Uh-huh. Hele, ještì se chci zeptat...}
{448}{}{Musím jít. Èau, Jimmy.}

# 17. GO ON, JIMMY, TELL THE STORY 2 (16)
{455}{}{Jó...jó...Vidìl jsem, e to nejní správnı, a musel jsem nìco UDÌLAT, ejo? 
 Nemoh sem pøece dopustit takovı vìci ve svı blízkosti, ne?}
{456}{}{Musíš bıt odvánı, kdy dìláš takovı vìci. Vìtšina lidí by se jenom dívala stranou.}
{457}{}{Rozumím, hele chci se tì zeptat...}

# 18. GO ON, JIMMY, TELL THE STORY 3 (17)
{465}{}{Já mám lidi RÁD, a nemám rád nìkoho, kdo do lidí rejpá. To není SPRÁVNİ.}
{466}{}{Jsi stateènı mu, Jimmy, stateènı mu. Nos svou jizvu s pıchou. Hele, co máš na skladì?}
{467}{}{To máš pravdu. Chci se tì ještì zeptat...}

# 19. SO SHALL WE GET DOWN TO BUSINESS? (18)
{475}{}{Hele, mùj pilotní kámo, ty se mi líbíš, take nevytahuj tu kšeftovací obrazovku s tìma drátkama a pojistkama.}
{476}{}{Uh...okay...ale jak se teda domluvíme...?}

# 20. SO SHALL WE GET DOWN TO BUSINESS? (19)
{480}{}{Hele, tohle je špatnej kšeft a tak, take ani muk, ale nech mì, a ti dám nìjakej JET
 jako pøátelskej dárek, jo? Pøíštì bueš muset zaplatit, ale tenhle je na Poøezanıho Jimmyho, okej?}
{481}{}{Díky, Jimmy. Hele, mùu se podívat, co máš ještì na skladì?}
{482}{}{Hej, díky. Chci se ještì zeptat...}
{483}{}{Tak fajn. Díky, Jimmy.}

# 21. WHERE DO YOU GET YOUR JET, JIMMY? (7, 8)
{490}{}{Jsem rád, e se ptáš, kámo. Hele, OSTATNÍ dıleøi, víš, voni maj svı zboí z druhı ruky,
 øedìnı, vokoøenìnı všelijakım sajrajtem.}
{491}{}{Ale tvùj JET, na druhou stranu...}
{492}{}{Vlastnì, zapomeò na to, protoe se chci zeptat na nìco jinıho...}

# 22. WHERE DO YOU GET YOUR JET, JIMMY? (COMPANION: MYRON, NOT IN PARTY) (7, 8)
{500}{}{Døív sem míval zboí vod samotnıho boha Myrona, víš, ale von se napakoval a zmizel...nebo to slíznul. Teïkonc vìtšinou beru
 pøímo vod Mordinù.}
{501}{}{No, døív jsem míval zboí vod starıho Myrona, ne se na to vykašlal a prásknul do bot....e jo, Myrone? Ha!
 Teï mám vìtšinou JET vod Mordinù.}
{502}{}{Zajímavı, ale já se chci zeptat na nìco jinıho...}

# 23. WHERE DO YOU GET YOUR JET, JIMMY? VOL. 2 (8, 22)
{510}{}{Já? Já mám kontakty se samotnım STVOØITELEM, mùj pilote. Mám Jet pøímo od mozkovny, ivıho boha chemickejch slouèenin,
 MYRONA.}
{511}{}{Myron?}
{512}{}{Zajímavı, ale já se chci zeptat na nìco jinıho...}
{513}{}{Myron jo? Mohl bych se setkat ...s tímhle ivım bohem?}
{514}{}{Fakt? No, tak to se musím nìkdy stavit a koupit si trochu. Díky, Jimmy.}

# 24. WHO'S MYRON? (23)
{520}{}{Myron je zlatej hošík Mordinovcù. On DÌLÁ jet. Kupovat vod Poøezanıho Jimma je jako brát pøímo vod Myrona, jasnı?
 To je zdroj, odkud J-J bere èistej JET. NEJLEPŠÍ jet.}
{521}{}{To zní dobøe. Dohodnìme se.}
{523}{}{Myslíš, e bych se mohl seznámit s tímhle Myronem?}

# 25. CAN YOU TAKE ME TO MYRON? (23, 24)
{530}{}{Kurva, ne! Mordivé mají toho chlapce zamèenıho na sedm západu líp ne poslední panu v Novım Renu. V ádnım pøípadì nenechají nikoho, aby se jejich
 ivıho pokladu jenom voèkem dotkl, víš co tím myslí, ne?}
{531}{}{Rozumím. Take jak dobøe je ten chlapec hlídanej?}
{532}{}{A na to, e jsem slyšel o spoustì jeho...pøítelkyò. Jak je monı, e jich má tolik, kdy je tak dobøe zamèenı?}
{533}{}{Rozumím. Hele chci se ještì zeptat...}
{534}{}{Zajímavı. Dík za inforamce, Jimmy.}

# 26. SECURITY? (25)
{540}{}{Hlídaèi, hlídaèí a ještì další hlídaèi. Plus nejsilnìjší elektronickej bezpeènostní systém v Novım Renu.
 Èlovìk mùe bıt šastnej, kdy jenom USLYŠÍ o nìkom, kdo ho potkal. Tak dobøe je hlídanej.}
{541}{}{Dobøe hlídanej, jo? Kde pøesnì?}
{543}{}{Aha. Hele mùeš mi odpovìdìt ještì na jednu otázku...}

# 27. STABLES? (26)
{550}{}{Mají ho schovanıho ve  "Stájích" na severu, mimo mìsto. Byl jsem tam jenom jednou - 
 nikdy mì nenechali porojít pøes brány a to pro Rodinu PRACUJU.}
{551}{}{No tak, musí bıt pøece nìjakı zpùsob, jak ho vidìt.}
{554}{}{Stáje jo? Mimo mìsto na sever...(Hned si to zapíšu do  Pip Boye)...dík za 
 info, Jimmy.}

# 28. HOW COULD I GET TO SEE MYRON? NO (27)
{560}{}{nemám tušáka, kámo. Já pro toho chlapce PRODÁVÁM, a i já ho vídám jenom obèas a ještì na pár set metrù.
 Velkej Jeíš Mordino k nìmu nepustí nikoho, kdo nepatøí k Rodinì.}
{561}{}{tak fajn, èas na kšeft.}
{564}{}{Tak fajn. Díky, Jimmy. Já pùjdu.}

# 29. ANY WAY I COULD GET TO SEE MYRON? (25, 26, 27, 28)
{570}{}{No tak to je u ouplnì jinej pøíbìh, kámo.}
{571}{}{Myslím, e to je pøíbìh, kterı bych si rád poslechnul. No tak,  Jimmy...}
{572}{}{Nevadí, stejnì se chci zeptat na nìco jinıho...}
{573}{}{Nemyslím, e ten pøíbìh chci slyšet. Musím padat.}

# 30. ANY WAY I COULD GET TO SEE MYRON 2? (29)
{580}{}{Víš, o Myrona se dobøe starají...Mordinové mu dávaj k dispozici nejlepší ivé zboí z Rena.}
{581}{}{Tím mysliš...?}
{582}{}{Myslíš prostitutky, e jo? Jen tak ze zajímavosti, kde berou Mordinové ty holky  a jak je vybírají?}
{584}{}{Aha. Díky Jimmy, já pùjdu.}

# 31. ANY WAY I COULD GET TO SEE MYRON 2? (30)
{590}{}{Mordinové kurvy vodí do Stájí osobnì, a pak je odvádìjí pryè. He-he. Myronovi je devatenáct, ale hormony
 má jako dvacet - dvacet chlapù myslím.}
{592}{}{Zajímavı....Jen tak ze zajímavosti, kde berou Mordinové ty holky  a jak je vybírají?}

# 32. HOW DOES MORDINO SELECT THESE PROSTITUTES? (30, 31)
{600}{}{(Pokrèil rameny.) Jeden z Mordinovıch chlapcù se projde Koèièí Packou, aspoò jsme to tak slyšel, a vybere jednu ze zásoby sleèny Kitty, která by se Myronovi mohla líbit. (Jimmy najednou pøestal mluvit. Dívá se na tebe a mraèí se.) Poèkej chvilku...}
{601}{}{Co je špatnì?}
{602}{}{Uh...to nic. Chci se tì ještì na nìco zeptat...}
{603}{}{No fajn, dík za informaci, Jimmy.}

# 33. HOW DOES MORDINO SELECT THESE PROSTITUTES? (32)
{610}{}{Proè chceš vìdìt takovı sraèky? Já mám Jet, to je všechno co potøebuješ vìdìt. Nepotøebuješ vìdìt nic o Myronovi, ani co mìl na obìd, ani s kım bude v noci v posteli.}
{611}{}{Proè tì to zajímá... (Zarazil se, pak se usmál a prohlíí si tì od hlavy k patì.) Ahá, u je mi to jasnı.
 Chceš si najít vlastní zdroj JETu, e jo ségro?}
{612}{}{Uka co máš, Jimmy.}
{613}{}{Tak na to zapomeò. Co máš?.}
{614}{}{Zapomeò na to, zajímá mì ale...}
{615}{}{Moná. Ale chtìla bych ještì vìdìt...}
{616}{}{Ne, jsem jenom zvìdavá. Mìj se Jimmy.}
{617}{}{Musím letìt, èau Jimmy.}

# 36. YOU SAYING HE SELLS SHIT THAT KILLS PEOPLE? (7, 8, 43)
{625}{}{Sakra, všecko co øíkám je, e  Jimmy má rád svı kupce šastnı a IVİ. Domysli si zbytek, kámo.
 Je pro tebe dùleitìjší vlastní dech, nebo ušetøit pár drobnejch na další dávce?}
{626}{}{Rozumím. Ukáeš mi, co máš?}
{627}{}{Nevíš náhodou nìco o téhle prázdné piksle od Jetu?}
{628}{}{Nemyslím, e se ten kluk pøedávkoval. Podle mnì ho otrávili.}
{629}{}{Chci se zeptat na nìco jinıho...}

# 37. YOU KNOW ABOUT WRIGHT KID'S OD? (7, 8)
{635}{}{Aha, tak takhle?! Chceš vìdìt jestli starej Jimmy nemá pracky v tomhle prùseru, co?!}
{636}{}{Ne, jenom se chci zeptat --}
{637}{}{Okej, zapomeò na to. Máš nìco na prodej?}
{638}{}{Hele chci se zeptat --}
{639}{}{Díky za tip, Jimmy ale já u musím jít --}

# 38. YOU KNOW ABOUT WRIGHT KID'S OD? (37)
{645}{}{MRDÁM TÌ! Já prodávám ÈISTEJ fet! Jestli chceš vìdìt, kdo otrávil malıho Wrighta, bì se zeptat toho starıho ksindla Renesca,
nebo toho tchoøe Jula a uvidíš, co z nich vypadne!}
{646}{}{Okay, okay. Uklidni se --}
{648}{}{Dobøe dobøe, Hele chci se ještì zep --}

# 39. TRY AND LEAVE (38)
{655}{}{Poslouchej, a našpicuj uši.  Jestli uslyším, jak vykládáš, e mám nìco spoleènıho se smrtí  Wrightovic kluka,
 zajistím ti hrob na Golghotì hned vedle nìj.}
{656}{}{Renesco øíká, e prodáváš JET vylepšenı arsenikem.}
{659}{}{ádnej problém. Hele chci se ještì zeptat na...}
{660}{}{Tak v hrobì, jo?Skonèím jako Richard, co?}
{661}{}{Nevyhrouj MI, ty malej hajzlíku. Neser do mì, nebo ti utrhnu hlavu a naseru ti do krku.}
{662}{}{Klídek, Jimmy. Nikdo nebude roznášet ádné drby.}
{663}{}{Já neøeknu nic jasnı? A teï jdu pryè.}

# 40. CANISTER 1 (36, 39)
{675}{}{(Bere si nádobu, prohlíí si ji.) No já... (Oèichal ji, pak se zamraèil.) Do prdele. Tenhle Jet mìl v sobì šávu z radškorpióna.
 A si z nìj cucl kdokoli, u si nezatancuje... (Vrací ti nádobu.)}
{676}{}{Je otrávenı?}
{677}{}{Hmmm. Ještì se chci zeptat...}
{678}{}{Aha, dík.}

# 41. CANISTER 2 (40)
{685}{}{Kurva, jo! Je tøeba dávat bacha, kdy tady koluje takovı svinstvo...To Jimmy dycinky øíkával --}
{686}{}{Nenapadá tì, odkud to mùe bıt?}

# 42. ANY IDEA . . . (41)
{695}{}{Néé, já...hele, ne abys mì prásknul ale ...na tvım místì bych si prouknul Renesca a Julese
 ...ale já ti nic neøekl, jasnı?}
{696}{}{Fajn, ale ještì by mì zajímalo...}
{697}{}{Renesco a Jules, he? Poptám se. Dík za tip.}

# 43. ANY IDEA . . . (36, 39)
{705}{}{To by mì nepøekvapilo.}
{706}{}{Co e to?}
{707}{}{Hmm. Zajímalo by mnì...}
{708}{}{Tak nic.}

# 44. ANY IDEA . . . (39)
{715}{}{Jó,  on by to MOHL øíct, protoe o tom ví VŠECHNO.}
{716}{}{Co tím myslíš?}

# 45. WHAT DO YOU MEAN? (7, 8, 44)
{725}{}{Co tím myslím? Já ti øíkám, e Jimmy má svı zákazníky rád šastnı a IVİ. Renescovi je to putna,
 take...domysli si to sám, kámo}
{727}{}{Díky za tip, Jimmy. Teï u musím jít.}

{800}{}{Zjistil jsi, e  Richard Wright byl otráven.}