#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
# 0. QUICK LOOK

# 0. LOOK
{150}{}{Vidíš èerného mue v obnošeném obleku. Kdy zachytil tvùj pohled, usmál se. Jeho zlaté zuby
 se zatøpytily ve svìtle lamp.}
{151}{}{Vidíš Julese.}

# 1. FLOAT [SLAVER] (WTG)
{200}{}{Nech Jula a tì provede po okolí, otrokáøi.}
{201}{}{Bì za  Mordiny, otrokáøi. Kupují nejvíc otrokù, kterí se dostanou do New Rena.}
{202}{}{Novı v Renu, otrokáøi? Nechceš se na nìco zeptat?.}
{203}{}{Hej, otrokáøi. Pojï si na moment promluvit.}
{204}{}{Otrokáøi, kdy si nepromluvíš s Julem, nikdy se nedozvíš ani o polovinì vìcí, které se dají v Renu dìlat.}
{205}{}{Jo, otrokáøi! Máš minutku?}
{206}{}{Hledáš nìco, otrokáø? Jules ti to pomùe najít.}

# 2. FLOAT [IF PLAYER HAS NEVER SPOKEN TO JULES] (WTG)
{220}{}{Novı v Renu, pøíteli? Nechceš se na nìco zeptat?.}
{221}{}{Hej, ty. Pojï si promluvit.}
{222}{}{Kamaráde, kdy si nepromluvíš s Julem, nikdy se nedozvíš ani o polovinì vìcí, které se dají v Renu dìlat.}
{223}{}{New Reno je nebezpeèné místo, kamaráde. Nech mì, a ti vysvìtlím, co je bezpeèné a co ne.}
{224}{}{Hej! Máš minutku, kamaráde?}
{225}{}{Kamaráde, ty a já bychom si mìli promluvit. Nech Jula, a tì provede mìstem.}
{226}{}{Hledáš nìco? Jules ti to pomùe najít.}

# 3. FLOAT ENCLAVE_DESTROYED (WTG)
{240}{}{Halelujááá! Já vdycky vìdìl, e jsi hrdina! Já to vìdìl!}
{241}{}{Hrdina jde, hrdina jde! Uvolnìte místo!}
{242}{}{Pojï se pozdravit se svım starım kamarádem Julem.}
{243}{}{Nechceš se s Julem podìlit o trochu své slávy?}
{244}{}{Nechceš se s Julem podìlit o trochu svého bohatství?}
{245}{}{Jules se k tobì vdycky choval slušnì...tak všem øíkej, e mì znáš, okej?}
{246}{}{Slyšel jsem, e tì shánìjí Korsiètí bratøi...}

# 4. FLOAT [POWER ARMOR] (WTG)
{260}{}{Dó prdééle. Myslím, e my dva bychom mìli bıt kamarádi.}
{261}{}{Jak s tím sakra chodíš na záchod?}
{262}{}{Co to sakra je? Chodící auto?}
{263}{}{Téda, feácí se poserou, a tì uvidí.}

# 5. FLOAT [MADE MAN] (WTG)
{280}{}{Ztratíš za mì slovíèko u svıho šéfa, brácho?}
{281}{}{Jo, brácho, doufám e jsi pøi svım strmım vzestupu nezapomnìl na starıho kámoše Julese, co?}
{282}{}{Jo, ty seš ale zlej a nebezpeènej! Vypadá to, e ti Reno prospìlo!}
{283}{}{Kdyby tvùj šéf potøeboval nìkoho na prodej Jetu, jsem tu...}
{284}{}{Ztratíš za mì slovíèko u svıho šéfa, ségro?}
{285}{}{Jo, ségro, doufám e jsi pøi svım strmım vzestupu nezapomnìla na starıho kámoše Julese, co?}

# 7. FLOAT [MALE PRIZEFIGHTER] (WTG)
{300}{}{Jo, Šampióne! Vypadá to, e ti Reno prospìlo!}
{301}{}{Jo, šampióne, doufám e jsi pøi svım strmım vzestupu nezapomnìl na strıho kámoše Julese, co?}
{302}{}{Štìstìna se na tebe usmála, kámo, takovı bijec!}
{303}{}{Vdycky jsem vìdìl, e tvoje jméno bude záøit. Od prvního okmiku.}
{304}{}{Jo, ségro bitkáøko! Reno ti prospìlo, o není jako v poušti, co?}
{305}{}{Jo, ségro šampiónko, doufám e jsi pøi svım strmım vzestupu nezapomnìla na starıho kámoše Julese, co?}
{306}{}{Štìstìna se na tebe usmála, sestøièko bojovnice. Jsi skvìlá!}

# 9. FLOAT [MALE PORN STAR] (WTG)
{320}{}{Zatracenì, podívejte se na tu záøící hvìzdu...záøíš tak, e tì skoro nevidím, brácho!}
{321}{}{Téda kámo, ty máš ale vıdr, tolik èísel za sebou!}
{322}{}{Co kdybys mì pøedstavil nìkterım známım hereèkám, brácho?}
{323}{}{Tak co herèe, doufám e jsi pøi svım strmım vzestupu nezapomnìl na starıho kámoše Julese, co?}
{324}{}{Ty jsi šastlivec, kamaráde. Práce která tì baví a máš za ní spoustu penìz a slávy.}
{325}{}{Vdycky jsem vìdìl, e tvoje jméno bude záøit. Od prvního okamiku.}

# 10. FLOAT [FEMALE PORN STAR] (WTG)
{340}{}{No podívejte se tady na slaïounkou sestøièku.}
{341}{}{Puká mi srdce, kdy tì vidím.}
{342}{}{No tak, ségro? Co takhle pusa pro starıho Jula?}
{343}{}{Zatracenì, podívejte se na tu záøící hvìzdu...záøíš tak, e tì skoro nevidím, ségro!}
{344}{}{Jo! Vypadá to, e ty se o sebe dokáeš postarat, sestøièko!}
{345}{}{Co kdybych si s tebou zahrál v pár scénách, drahoušku?}
{346}{}{Jo, doufám e jsi nezapomnìla starıho kamaráda Jula?}
{347}{}{Byla jsi skvìlá, sestøièko, jedním slovem dokonalá.}
{348}{}{Vdycky jsem vìdìl, e tvoje jméno bude záøit. Od prvního okamiku.}
{349}{}{Vzdycháš ve skuteènosti stejnì jako ve filmu?}
{350}{}{Nedokáu pospat jak rád jsem, e tì zase vidím.}

# 11. FLOAT [COMPANION: MARCUS] (WTG)
{365}{}{To je MUTANT?}
{366}{}{Ten mutant je poøádnì velkej hajzlík.}
{367}{}{Mutanti v Novım Renu? To vypadá na poøádnou bitku...}
{368}{}{Mutanti z pouštì? Nebylo to pøed nìjakımi osmdesáti lety?}
{369}{}{Ten mutant v Renu dlouho nevydrí...}
{370}{}{To bude masakr, a si nìkdo z Rodin všimne toho mutanta...}

# 12. FLOAT [COMPANION: ROBOBRAIN] (WTG)
{380}{}{To je nìjakej Jukebox na koleèkách, ta vìc co za tebou jezdí?}
{381}{}{Hele, jukebox?}
{382}{}{Umí ten tvùj robot nìjaké triky?}
{383}{}{Nechceš prodat toho robota? Mozek si nech.}

# 13. FLOAT [COMPANION: LENNY] (WTG)
{390}{}{Ghúl...Mìl jsem dojem, e nìco cítím.}
{391}{}{Ten ohnilej chlapík v Renu dlouho nevydrí...}
{392}{}{To bude masakr, a si nìkdo z Rodin všimne toho ghúla...}

# 14. FLOAT [COMPANION: ROBODOG] (WTG)
{400}{}{Hezkej kyberpejsek, hodnej pejsek...}
{401}{}{Hezkej kyberpejsek... moná mám u sebe nìjakou kostièku...}
{402}{}{Na toho psa bys mìl mít zbrojní pas.}
{403}{}{Ten pes má nìkterı kousky ze eleza?! A já si o sobì myslel, e jsem tvrïák.}
{404}{}{Zajímalo by mnì, jak se kyberpsi rozmnoujou...}

# 15. FLOAT [NO REP] (WTG)
{410}{}{Reno si mùe dát takovıho jako ty na snídani.}
{411}{}{Reno je velkı a jeden se v nìm snadno ztratí, ale Jules ti vdycky pomùe.}
{412}{}{Pro nepøipravenı je tohle mìsto nebezpeènı...ale já tì mùu pøipravit na všechno.}
{413}{}{enskı, prachy, enskı, prachy... co víc si pøát?}
{414}{}{Jet, enskı, kvéry... všechno mám. Staèí se jenom ZEPTAT.}
{415}{}{Reno... tohle mìsto nikdy nespí.}
{416}{}{Jet, prachy, Jet, prachy...co víc si pøát?}
{417}{}{Mám fajn zboí, nemáš zájem?}
{418}{}{Jules jsou tvé OÈI, tvé UŠI v New Renu.}
{419}{}{Reno - nejvìtší malı mìsto v poušti, kamaráde.}
{420}{}{Novej ve mìstì? Vyplatí se ti promluvit si nejdøív se mnou.}
{421}{}{Jules je ten mu, kterého POTØEBUJEŠ.}
{422}{}{Chlast, enskı, jet, kvéry... všechno najdeš u Jelese, kamaráde.}
{423}{}{Reno je vzhùru celou noc, take budeš potøebovat vzpruhu..}
{424}{}{Reno si mùe dát enskou k snídani. Já taky.}
{425}{}{Samotná ena se v Renu snadno ztratí. Nech Julese a tì najde.}
{426}{}{Tohle mìsto dokáe enskou svlíknout donaha...promluv si se mnou. Ode mnì se ti to bude líbit.}
{427}{}{Jo! na slovíèko, ségro!}
{428}{}{Nová ve mìstì, ségro? Potøebuješ pøátelskou radu.}
{429}{}{Potøebuješ Jet? Potøebuješ zbranì? Ségro, mám to všechno. Staèí se ZEPTAT.}

# 16. BASIC INTRO, 1st TIME (WTG)
{450}{}{(Usmívá se a v jeho ústech se zableskne zlatı zub. Síla jeho kolínské ti vehnala slzy do oèí.) }
{451}{}{VÍTEJ do nádhernıch ulic nádherného mìsta New Rena, brácho!}
{452}{}{VÍTEJ do nádhernıch ulic nádherného mìsta New Rena, ségro!}
{453}{}{Huh? He?}
{454}{}{A ty jsi...?}

# 17. BASIC INTRO, 1st TIME, PT 2 (16)
{460}{}{Jmenuji se  Jules, a bude mi potìšením provést tì mìstem a sehnat ti cokoli, po èem
 touí tvé srdce.}
{461}{}{Jmenuji se Jules, a mùu na svou èest prohlásit, e jsem ještì nevidìl nádhernìjší enu na ulicích New Rena.
 Bude mi potìšením provést tì mìstem a sehnat ti cokoli, co by sis mohla pøít, krásná dámo.}
{462}{}{Hej, hej, hej, vítej zpátky. Potøebuješ nìco od Julese?}
{463}{}{Já hledat ehm uhm... eh hmm zapomìt}
{464}{}{Odejdi}
{465}{}{Fajn. Mùeš mi pomoct?}
{466}{}{No, zajímalo by mnì...}
{467}{}{Nevíš NÁHODOU co se stalo synovi pana Wrighta, Jule?}
{468}{}{Jule, nevidìl jsi nìkde moje auto? Bylo zaparkovanı támhle a teï je pryè.}
{469}{}{Hele..."Julesi," e ano? Nejspíš se touto konverzací snaíš nìco získat, take na rovinu:
 Co po mnì chceš?}
{470}{}{No,zajímalo by mnì...co máš z toho, kdy provádíš návštìvníky mìstem, Jule?}
{471}{}{Ne dneska, Jule, Díky.}
{472}{}{Nic, dík. Èau Jule.}

# 18.  RETARD (17, 81)
{480}{}{Eh... nenamáhej si mozeèek, bratøíèku. Hlavnì si nìjak neubli, okej?}
{481}{}{Eh... nenamáhej si mozeèek, sestøièko. Hlavnì si nìjak neubli, okej?}
{482}{}{Hi tı hi tı hi tı hou}

# 19.  HOW CAN JOU HELP? (17, 20-59, 68-77, 83, 84, 85, 86, 87, 88, 89)
{490}{}{Mùu ti sehnat COKOLI, brácho. Jestli se chceš proletìt a vznášet se v nebeskıch vıšinách, Jules ví,
 kam jít. Take moje otázka zní: Bez èeho nemùeš dál ít?}
{491}{}{Mùu ti sehnat COKOLI, ségro. Jestli se chceš proletìt a vznášet se v nebeskıch vıšinách, Jules ví,
 kam jít. Take moje otázka zní: Bez èeho nemùeš dál ít?}
{492}{}{Mùu ti sehnat COKOLI, moje sladká sestøièko. Jestli se chceš proletìt a vznášet se v nebeskıch vıšinách, Jules ví,
 kam jít. Take moje otázka zní: Bez èeho nemùeš dál ít?}
{493}{}{Jasnı, jasnı... Take co potøebuješ?}
{494}{}{Mùeš mi øíct nìco o New Renu?}
{495}{}{Kde by se daly sehnat nìjaké drogy?}
{496}{}{Sháním se po nìjaké poøádné palebné síle.}
{497}{}{Sháním zásoby.}
{498}{}{Zajímám se o ... sex??.}
{499}{}{Hledám místo, kterému se øíká Vault 13.}
{500}{}{Hledám svùj kmen. Byli uneseni.}
{501}{}{Nevíš jak opravit ropnı tanker?}
{502}{}{Hledám GECK.}
{503}{}{Dneska nic, dík.}

# 20.  CAN JOU TELL ME ABOUT NEW RENO? (19)
{515}{}{Mùe ti Jules ØÍCT nìco o New Renu? Sakra, JO! Nejdùleitìjší vìc, co potøebuješ: Reno ovládají ètyøi rodiny: Mordinové,
 Salvatorové, Bishopové a Wrightové. Kádá z rodin má pod palcem kousek Rena.}
{516}{}{Reno má ètyøi rodiny: Mordiny, Salvatory, Bishopy, Wrighty. Kadá z nich šéfuje èásti mìsta o kšeftù.}
{517}{}{Povìz mi o rodinách.}
{518}{}{A co zákony?}
{519}{}{No, vlastnì by mì zajímalo nìco jiného...}
{520}{}{Zajímavı, díky za rozhovor.}

# 21. LAW (20)
{525}{}{Není zákon, nejsou fízlové, není šerif. Jsou jenom rodiny.}
{527}{}{Tak kdo v Renu udruje poøádek?}
{528}{}{Aha. Zajímalo by mnì nìco jiného...}

# 22. ORDER? (21)
{535}{}{Rodiny udrují všechno v pohodì. Nemají rády problémy v Renu, protoe to poškozuje turistickı ruch,
 a to znamená míò penìz pro všechny. Kdy si dáš pozor a platíš dluhy, Golgotì se vyhneš.}
{537}{}{Golgota?}

# 23. GOLGOTHA? (22)
{545}{}{Jo, to je høbitov mimo mìsto. Tam odpoèívají lidi, co neplatili dluhy nebo rozzlobili Rodiny.
 Zkrátka je pøiváou a nechají je pomalu umírat na slunci. Nehezká smrt. A smrdí to tam jako v prdeli.}
{547}{}{Zajímavı, ale mì by zajímalo ještì nìco...}
{548}{}{Sqìlı, dík za informace.}

# 24. INFO'S EXPENSIVE (20-23, 26-53)
{555}{}{No, DALŠÍ vìc kterou se potøebuješ o Renu nauèit je, e nic není zadarmo.}
{556}{}{No, takové informace nejsou levné. Máš prachy? Pak máš moji pozornost.}
{557}{}{Zapla 25.}
{558}{}{Zapla 50.}
{559}{}{Zapla 75.}
{560}{}{Zapla 100.}
{561}{}{Víš, já mám ještì jiné otázky, které se rodin netıkají..}
{562}{}{Mám takovı dojem, e si tvé znalosti nemùu dovolit. Pozdìji.}
{563}{}{Budu si to pamatovat. Dík za tip, Jule.}

# 25. TELL ME ABOUT SOME MORE ABOUT THE FAMILIES (24)
{575}{}{(Jules schoval peníze tak rychle, e to vypadá, jakoby se vypaøily) Take... která z rodin tì zajímá?}
{576}{}{(Jules schoval peníze.) Take...která rodina tì zajímá?}
{577}{}{Øekni mi o Rodinì Mordinù.}
{578}{}{Øekni mi o Rodinì Salvatorù.}
{579}{}{Øekni mi o Rodinì Bishopù.}
{580}{}{Øekni mi o Rodinì Wrightù.}
{581}{}{Mám jiné otázky o Renu...}
{582}{}{No, vlastnì nic. Mìj se.}

# 26.  TELL ME ABOUT MORDINOS 1 (25)
{590}{}{(Ukazuje dva prsty.) Mordinové jsou jako dvouhlavá saò, kámo, a obì hlavy se jmenují Jeíš Mordino.}
{591}{}{Pokraèuj...}
{592}{}{Vdycky jsem si myslel, e Jeíš jede v nìjaké èernotì.}
{594}{}{No, nìco o dalších rodinách?}
{596}{}{No, vlastnì nic. Dík za rozhovor.}

# 27.  TELL ME ABOUT MORDINOS 2 (26)
{615}{}{Ti dva jsou tatík Velkej Jeíš Mordino a jeho synáèek Malej Jeíš Mordino. Oba jsou to ti nejhorší zkurvysyni, jaké kdy potkáš.
 Objevili se tu jako otroci, ale pøed pár lety se vzmohli a teï si opatrují svoji malou øíši.}
{616}{}{Jak velká je ta jejich  "øíše?"}

# 28.  TELL ME ABOUT MORDINOS 3 (27)
{625}{}{Vlastní Desperado kousek ní na téhle ulici. Nemùeš to minout. A taky mají nejvìtší zdroje Jetu v celém New Renu.
 Take kdybys cítil nutkání se proletìt...}
{626}{}{Kdy u o tom mluvíme, nevíš kde by se tady daly sehnat nìjaké drogy?}
{627}{}{Jakto e mají Mordinové nejvìtší zdroje Jetu?}
{628}{}{Povìz mi o ostatních rodinách.}

# 29.  HOW COME MORDINOS HAVE BIGGEST SUPPLY OF JET? (28, 29, 31, 32, 33)
{635}{}{Jsou úplnì na vrchu, kámo. Mají továrny, tvùrce a distributory.
 Jsou jako zkurvená letecká spoleènost, tolik Jetu mají..}
{636}{}{Jo, take co dál?}
{637}{}{Jakou továrnu?}
{638}{}{Jakého "tvùrce?"}
{639}{}{Jak rozsáhlá je jejich sí distributorù?}

# 30. WHAT FACTORY? (29)
{650}{}{Mají továrny po celém Renu, dìlají fet celı den a noc. Proto mùeš koupit Jetu kolik chceš skoro kdekoli:
  v barech, kasínech, na ulici...a pochopitelnì ode MNÌ.}
{651}{}{Mùu se podívat, co máš na skladì?}
{652}{}{Zpátky k Mordinùm a Jetu...}

# 31. MAKER? (29)
{660}{}{Jo... (Pøistoupil blí.) ...víš, Mordinové mají vlastní malı zlatı dùl jménem Myron. S ním to vyhráli...víš,
on VYMYSLEL Jet.}
{662}{}{Dost o Mordinech a ostatních rodinách. Øekni mi nìco o  Myronovi...}

# 32. DISTRIBUTION? (29)
{670}{}{Pumpují to po celém New Renu. Pak nahoru na sever do Denu a taky...uh... (Zarazil se, pak pokrèil rameny a pokraèuje..)
 ... no a dneska taky prodávají do Reddingu, co jim rozhodnì nenièí rodinnı rozpoèet.}
{672}{}{Povìz mi o  Reddingu.}

# 33. REDDING? (32)
{685}{}{O tom není moc co øíct. Hornické mìsteèko severozápadnì odtud. Øíká se, e  Mordinové tam chtìjí získat nìjakı vliv, 
 kvùli ZLATU, co se tam tìí. Take Mordino jim  posílá Jet, oni posílají nazpátky zlato a všichni jsou šastní..}

# 34.  TELL ME ABOUT SALVATORES (25)
{695}{}{Tichá banda. Vede je Louis Salvatore, stárnoucí gangster. Jejich teritorium je West Side,
 jejich hlavní flek je bar u  Salvatora na Druhé Ulici. Nedìlal bych tam problémy, bıt tebou.}
{696}{}{Proè ne?}

# 35.  WHY NOT? (34)
{710}{}{Rada zdarma: Kdy uvidíš Salvatora, skloò hlavu a dr hubu, nebo tì pøeseknou vejpùl. Mají
 nejsilnìjší zbranì na téhle stranì mìsta, a nikdo se špetkou rozumu si s nimi nic nezaèíná, jasnı?}
{711}{}{Jaké  "zbranì" mají Salvatorové?}
{712}{}{To zní, jako by mìli nìjakou poøádnou artilerii. Co to je?}
{715}{}{Aha... dík za varování.}

# 36.  WHAT KIND OF WEAPONS TO THE SALVATORES HAVE? (35)
{725}{}{Pistole...jenome støílejí SVÌTLO. Hele, Reno je mìsto svìtel, ale svìtlo, které TYHLE pistole svítí, mùou pøeseknout chlapa vejpùl, (Jules seknul rukou do vzduchu.) Pøepálí tì na dvì èistı pùlky jako nic.}
{726}{}{Støílejí svìtlo? Neøíkají jim 'laserové pistole?'}
{727}{}{Tak to abych si dal pozor. Mùeš mi øíct nìco o ostatních rodinách?}

# 37.  WHAT KIND OF WEAPONS TO THE SALVATORES HAVE? (36)
{735}{}{No teda, já vlastnì ani nevím... Nejsem si jistı, e vím o èem mluvíš. Ale øeknu ti tohle: nechoï se ptát
 Salvatorù na ty pistole. Mají takovı podivnı zlozvyk zabíjet lidi, kteøí jsou moc zvìdaví.}
{736}{}{'Laserovımi pistolemi,' Julesi, myslím pistole, které emitují paprsek koherentního svìtla. Paprsek dostateèné síly - øeknìme pár  megawattù - mùe zpùsobit vánìjší škody, pokud bude na cíl soustøedìnı nìkolik sekund, a vytvoøil by takovı efekt, kterı jsi mi popisoval.}
{737}{}{Mìli tyhle pistole vdycky?}

# 38.  WHERE ARE THEY COMIN' FROM (37)
{750}{}{Vdycky ne...jinak by u šéfovali New Renu...CELÉMU New Renu. Zatím se jenom pomalu propracovávají nahoru.
 Ty pistole se ukázaly...moná pøed pár mìsíci, nìkdy v dobì toho masakru.}
{751}{}{Masakr?}

# 39.  MASSACRE? (38)
{765}{}{Jó...dva Salvatorští kluci s tìmi pistolemi zabili hromadu Bishopovıch chlapù, potom postøíleli pár Mordinovcù, kteøí se pøedvádìli na West Side. Od té doby dávají ostatní rodiny od Salvatorù ruce pryè.}
{766}{}{To jsou urèitì lasery.Nevíš, èím Salvatorové pohánìjí své laserové pistole? Pouívají baterie,
 fùzní buòky, nebo kabelové systémy?}
{767}{}{Nenapadá tì, odkud mùou ty pistole mít?}

# 40.  ANY IDEA WHERE THEY GET THE LASER WEAPONS? (39)
{780}{}{Nemám páru, kamaráde, neptal jsem se. A ty bys taky nemìl...nech si poradit. Jestli se sháníš po zbraních, jsou 
 jiná ...bezpeènìjší...místa, kde se mùeš poptat.}
{781}{}{Jako tøeba?}
{782}{}{øekni mi ještì nìco o rodinách.}

# 41.  BY LASER PISTOLS I MEAN (37, 39)
{795}{}{Uh... no, o tom já nic nevím, a.. hmmmm. Víš, mluvíš jako jeden z bílejch plášù ze Stájí. Nejsi náhodou
 jeden z nich?}
{796}{}{Stáje?}

# 42.  STABLES? (41)
{810}{}{(Pøistoupil blí.) Noo, nechce se mi zrovna mluvit o NEPØÍJEMNÌJŠÍCH èástech Rena, ale je tady banda lidí v bílıch pláštích, kteøí mluví jako ty,
 v té budovì, Stájích, na sever od mìsta. Tìce hlídaní bandou Mordinù.}
{811}{}{Co tam dìlají?}

# 43.  WHAT DO THEY DO? (42)
{825}{}{Testují nové druhy Jetu, podle toho co jsem slyšel. Ale, mezi námi, kamaráde: nechoï tam vyzvídat
 ...Mordinové nemají rádi návštìvníky. Kromì toho...Jules ti mùe sehnat všechen Jet co budeš potøebovat.}
{826}{}{Proè Mordinové poøád testují Jet? Pøipadá mi, e u je návykovı dost.}
{827}{}{Na kom Mordinové testují ty drogy?}
{828}{}{Nevíš, jak se dostat do tìch Stájí?}

# 44.  WHO DO THEY TEST IT ON? (43, 45, 46, 47)
{840}{}{Na otrocích. Mají je tam zavøené jako dobytek. }
{841}{}{Mordinové koupili stádo od otrokáøù, kteøí procházeli mìstem. }
{842}{}{Mordinové koupili stádo od otrokáøù jako jsi ty, kdy tu naposledy procházeli. }
{843}{}{Kupují poøádnou bandu, protoe otrokùm je stále špatnì,utíkají ...nebo umírají. Vìtšinou umírají.}

# 45.  WHY DO THEY KEEP TESTING JET? (43, 44, 46, 47)
{860}{}{Nejspíš aby byl ještì lepší, øekl bych, vylepšit vırobu, zlepšit drogu. Jet je dobrı, ale jestli ho dokáou udìlat ještì LEPŠÍ
 ...tak to bude rozdíl mezi poletováním na obloze a letem na mìsíc.}

# 46.  ANY IDEA HOW I CAN GET IN THERE? (44, 45)
{880}{}{No tak moment -- na tvém místì bych o tom ani NEMYSLEL. Mordinové to místo hlídají jako vzteklí psi.
 Zapomeò na to.}
{881}{}{Musí bıt nìjakı zpùsob jak se tam dostat...}
{886}{}{Máš, pravdu, kašlu na to. Díky za informaci.}

# 47.  THERE MUST BE A WAY IN . . . (46)
{895}{}{No... kdy budeš mluvit tak chytøe jako pøedtím, moná by ses mohl vydávat za jednoho z bílıch plášù.
 No ale taky by ses mohl nechal nabrat Mordiny...}

# 48.  TELL ME ABOUT BISHOP (25)
{910}{}{Ha! John Bishop? Není toho moc k povìzení: Bishop je mazanı, tvrdı a chce mít VŠECHNO.}
{911}{}{Jo, fajn, tak to si to bude nejdøív vyøídit se mnou. Kde je jeho území?}
{912}{}{ Kde je jeho území?}

# 49.  TELL ME ABOUT BISHOP (48)
{925}{}{Vìtšinou je ve raloèím Shark klubu na Druhé ulici. Je obloenı dokoleèka hlídaèi, take na návštìvu zapomeò,
 pokud s ním nemáš OPRAVDOVİ obchod. (Zle se usmál.) A dr se pryè od jeho eny. A jeho DCERY.}
{926}{}{Uh, obchod?}
{927}{}{To nehrozí.}

# 50.  BID-NESS (49)
{935}{}{Víš co tím myslím, bratøe. Dr se od tìch dvou, jestli se nechceš dostat na Bishopovu Èernou Listinu.}
{936}{}{No moná ne, ale na tom, CO máš mezi nohama  nezáleí... alespoò pro sleènu Bishopovou. Je nadrená jako ...}
{937}{}{Uh, øekni mi nìco dalšího o rodinách.}

# 51.  TELL ME ABOUT WRIGHT (25)
{945}{}{Wrightovi? Heh. Wrightovi jsou jediná rodina, která JE rodina. Ostatní, ti mají oldáky a gangstery,
 ale Wrightovic rodina JE Wrigtovic rodina, rozumíš?}
{946}{}{Pro tebe mám varování co se tıká Wrigtovy rodiny, otrokáøi...Wrightovi jsou toti jediná rodina, která JE rodina.}
{947}{}{Jsou jedna rodina? Kolik jich je?}

# 52.  TELL ME ABOUT WRIGHT 2 (51)
{960}{}{Alespoò dvacet nebo víc Wrightù pravé krve. Zatracení parchanti a jeden škaredìjší ne druhı.}
{961}{}{Alespoò dvacet nebo víc Wrightù pravé krve,  a nemají nijak v oblibì lidi tvého øemesla. Øíká se, 
 e jim otrokáø unesl sestru a od té doby moc otrokáøe v lásce nemají.}
{962}{}{Co Wrightové ovládají v New Renu?}

# 53.  WHAT DO WRIGHTS CONTROL? (52)
{975}{}{Nemají Kasino, Vìtšinou kšeftují s alkoholem a prodávají ho ostatním rodinám. Take jestli se sháníš po poøádné flašce,
 najdeš je na vıchodní stranì mìsta ve velké vile.}

# 54.  WHERE CAN I GET SOME DRUGS? (19, 28)
{985}{}{Bratøe, nemusíš se dívat dál, ne na zde pøítomného obchodníka Julese. }
{986}{}{Sestro, nemusíš se dívat dál, ne na zde pøítomného obchodníka Julese. }
{987}{}{Sladká sestøièko, nemusíš se dívat dál, ne na zde pøítomného obchodníka Julese. }
{988}{}{Mám všechno a co nemám ty nepotøebuješ. Take?}
{989}{}{Jasnì, uka co máš.}
{990}{}{Jaké drogy se dají sehnat v New Renu?}
{991}{}{Teï ne. Mám ještì nìjaké otázky...}
{992}{}{Vlastnì se nezajímám o ádné drogy. A teï musím jít.}

# 55.  WHAT KIND OF DRUGS CAN I GET IN NEW RENO? (54)
{1005}{}{JAKÉKOLI. Mám vìci, které tì povzbudí, povzbudí tvoji starou, udìlají tì tvrïákem, pøinesou ti štìstí, sílu,
 rozum...a, pochopitelnì, mám TU drogu, tu která ti umoní lítat - Jet.}
{1006}{}{JAKÉKOLI. Mám vìci, které tì povzbudí, pøinesou ti štìstí, sílu,
 rozum...a, pochopitelnì, mám TU drogu, tu která ti umoní lítat - Jet.}
{1008}{}{Odkud pochází Jet? Byl tady v okolí vdycky?}

# 56.  WHERE DOES JET COME FROM? (55)
{1025}{}{No... uh... Jet je odtud...z Rena myslím. Neni tady dlouho, ale je po nìm velká POPTÁVKA, jestli mi rozumíš? (Mrknul.)
 Totální hit mezi turisty jako ty.}
{1026}{}{No, nìco si koupím. Uka.}
{1027}{}{Ale proè je Jet odtud?}

# 57.  BUT WHY DOES JET COME FROM HERE? (31, 56)
{1035}{}{Ah, no...víš, Mordinové vyhráli v loterii, kdy jednou našli tu mozkovnu zvanou Myron. Má talent, kdy
 pøijde na vymıšlení drog. On VYMYSLEL Jet.}
{1036}{}{Myron, jo? Kde ho najdu?}

# 58.  WHERE CAN I FIND HIM? (57)
{1045}{}{(Pøistoupil blí.)  Noo, nechce se mi zrovna mluvit o NEPØÍJEMNÌJŠÍCH èástech Rena, ale na sever od mìsta je budova,
 které øíkají Stáje. Tìce hlídané bandou Mordinù. Tam je Myron.}
{1046}{}{Stáje mimo mìsto?}

# 59.  WHERE CAN I FIND HIM? (58)
{1055}{}{Jo, Mordinové tam mají svého zlatého chlapce, dávají mu peníze, kurvy, cokoli chce, dokud dìlá drogy. Jet
 je jeho NEJLEPŠÍ. Nikdy jsem nevidìl nic tak návykového. Pøevrátil s Jetem Reno naruby, to jó.}
{1056}{}{Myslíš e by bylo moné setkat se s tímhle Myronem?}

# 60.  THINK I COULD MEET THIS MYRON? = FEMALE (59)
{1065}{}{(Jules se zastavil a prohlíí si tì od hlavy k patì.)}
{1066}{}{Jules? Hej? Ptala jsem se, jestli bych se mohla setkat s Myronem.}

# 61.  THINK I COULD MEET THIS MYRON? (59, 60)
{1075}{}{Uau, no bratøe, jedna rada zdarma: nepokoušej se setkat se s Myronem, protoe jestli to Mordinové zjistí,
 rozpárají tì a hodí na Golgotu.}
{1076}{}{Já bych to nezkoušel. Jestli potøebuješ Jet, nemusíš chodit za Myronem, protoe já ho mám dost. Jestli Mordinové
 zjistí, e se snaíš dostat k Myronovi, rozpárají tì a nechají chcípnout na Golgotì.}
{1077}{}{No...MONÁ by to šlo. Problém je, e jestli se o tom dozví Mordinové, 
 rozpárají tì jako králíka a nechají chcípnout na Golgotì.}
{1078}{}{Opravdu to nijak nejde?}
{1079}{}{Jak by to šlo?}
{1080}{}{Proè sis mì pøed chvílí prohlíel jako nìjakou sochu?}
{1081}{}{Golgota? Co je to?}
{1083}{}{Zajímavé, dík za informace.}

# 62. UH, GOLGOTHA? (61, 63, 64)
{1101}{}{Opravdu se s Myronem nedá nìjak setkat?}
{1102}{}{Proè by to moná šlo?}
{1103}{}{Proè sis mì pøed chvílí prohlíel jako nìjakou sochu?}

# 63.  WHY WOULD I BE ABLE TO SEE HIM (61, 62)
{1115}{}{Protoe jsem se díval, jestli náhodou nejsi Myronùv typ, ale nevypadáš na to. Moná kdyby ses dala trochu do parády,
 Myron by ti vìnoval jeden dva pohledy...on je hodnì na enskı. }
{1116}{}{(Šklebí se.) Protoe vypadáš DOBØE, drahoušku. A Myron má rád enskı, které vypadají DOBØE. }
{1117}{}{Chlapec je jako králíèek a pro svou mrkvièku potøebuje poøád nové jamky.}
{1118}{}{Co to bylo s tou Golgotou?}
{1119}{}{Uh, skvìlı. Dík za tip, Julesi. Ještì jedna otázka...}
{1120}{}{No, tak to abych šla.}
{1121}{}{Dokonalé, jsi úplnı básník. Mrkvièka a jamka. DÍKY ti.}

# 64.  ISN'T THERE ANY WAY I COULD SEE HIM? (61, 62)
{1130}{}{Kdybys byl hezká enská, moná, ale jinak potøebuješ povolení od Mordinu. Ani jedno není moc
 pravdìpodobné.}
{1132}{}{Aha, take ještì jedna otázka...}

# 65.  I'M LOOKING FOR SOME HEAVY FIREPOWER. (19, 40)
{1145}{}{Chceš-li zbranì, jdi za mım kámošem Eldridgem na West Endu. Má takovı vìci na zabíjení, o jakıch se ti ani nesnilo.
 Øekni mu, e tì posílám.}
{1146}{}{Slyším, kámo, slyším. Chceš-li to nejlepší, jdi za mım kámošem Eldridgem na West Endu. Má takovı vìci na zabíjení, o jakıch se ti ani nesnilo. Øekni mu, e tì posílám.}
{1147}{}{Slyším, ségro, slyším. Chceš-li to nejlepší, jdi za mım kámošem Eldridgem na West Endu. Má takovı vìci na zabíjení, o jakıch se ti ani nesnilo. Øekni mu, e tì posílám.}
{1148}{}{Sladíèko, ty u jsi ïábelsky vyzbrojená svım tìlem. Ale jestli chceš víc, jdi za mım kámošem Eldridgem na West Endu. Má takovı vìci na zabíjení, o jakıch se ti ani nesnilo. Øekni mu, e tì posílám.}
{1150}{}{Dík za tip, já pùjdu.}

# 66.  I'M LOOKING FOR SOME SUPPLIES. (19)
{1165}{}{Potøebuješ zásoby? No, MÚEŠ jít za Renescem na West End...ale je tady malı háèek: nekupuj od nìj ádné drogy,
 protoe nejsou BEZPEÈNÉ. Zásoby má fajn, ale jestli chceš drogy, stav se radìji u mnì.}
{1166}{}{Zapamatuju si to. Ještì otázku...}
{1167}{}{Jeho drogy nejsou bezpeèné, jo? Tak dík za tip, já pùjdu.}

# 67.  I WANT TO GET LAID. (19)
{1175}{}{Slyším tì, bratøe. Vìtšina turistù se projde po Panenské Ulici a nechají si za dvì babky vykouøit nìjakou napùl mrtvou kurvou. Ty vypadáš, e máš nìjakou úroveò, take si zajdi do Koèièí Packy tady pøes ulici. Øekni jim, e tì posílá Jules.}
{1176}{}{Slyším tì, sestro. Vìtšina turistù se projde po Panenské Ulici a nechají se udìlat od nìjakého nemocného plejboje.
 Ty vypadáš, e máš nìjakou úroveò, take si zajdi do Koèièí Packy tady pøes ulici. Øekni jim, e tì posílá Jules.}
{1177}{}{(Usmál se a roztáhl ruce.) Dál nehledej, má sladká sestøièko. Jules je ti k slubám!}
{1178}{}{Uh, díky, Jule, ale ne. Chci se ještì zeptat...}
{1180}{}{Uh, dík za tip, ale já budu muset jít.}
{1181}{}{Uh, díky, ale já budu muset jít.}

# 68.  VAULT 13. (19)
{1190}{}{Myslíš Vault CITY, e jo? To je na severovıchod. Nemùeš to minout, staèí sledovat stopy po karavanách.}
{1191}{}{Fajn, ještì otázku...}
{1192}{}{Díky za tip, ale já u musím jít.}

# 69.  GECK (19)
{1200}{}{GECK? To je nìjaká nová droga? Co to dìlá?}
{1201}{}{Ne, to je...ale nic, na tom nezáleí. Chci se zaptat na nìco jiného...}
{1202}{}{To nic, já stejnì musím jít.}

# 70.  MY TRIBE (19)
{1210}{}{O tom nic nevím, sorry. Nebyli to otrokáøi?}
{1211}{}{Moná. Ještì se chci zeptat...}

# 71.  TANKER (19)
{1220}{}{Coeto?}
{1221}{}{Zapomeò na to, zeptám se tì na nìco jiného...}

# 72.  RICHARD WRIGHT (17)
{1230}{}{Uh... Wrightovic kluk? Jo, slyšel jsem o tom. Zatracená smùla. Tak malej kluk by drogy brát nemìl.
 U tak mají dost tìkı ivot, nato aby jim nìkdo dal špatnej fet.}
{1231}{}{Kdy u mluvíme o špatném fetu, Renesco øíkal, e prodáváš Jet øíznutı arsenikem.}
{1232}{}{Co tím myslíš, "špatnej fet?"}
{1233}{}{Nevíš náhodou nìco o téhle nádobce na Jet?}
{1234}{}{Zajímavé, e to øíkáš. Já si myslím, e se nepøedávkoval. Podle mnì ho nìkdo otrávil.}

# 73.  IMPURE SHIT (85)
{1250}{}{(Pokrèil rameny.) Nìkterım dılerùm je jedno co prodávají, a lidi umírají. Ode mnì to nevíš, ale
 já bych si proklepnul Renesca Rakeáka a podíval se, jak dobrej fet má on.}
{1251}{}{Mluvil jsem s Renescem... a on mi øekl, e prodáváš Jet øezanı arsenikem.}
{1252}{}{Reno je velké mìsto, Jule. Nenapadá tì nìkdo?}
{1253}{}{Mám jiné otázky...}
{1254}{}{Fajn, podívám se na nìj.}

# 74.  DEALERS (73)
{1270}{}{Ve mìstì je hromada dılerù...Melej Jeíš Mordino, moná, ale proè by prodával Wrigtovi mi nedává smysl. Pak 
 je tady Poøezanej Jimmy J nahoøe na Druhı ulici, na sever odtud, ale to je malá ryba. Já bych si stejnì proklepl Rakeáka.}
{1272}{}{"Poøezanej Jimmy J?" Kdo je to?}
{1273}{}{Malej Jeíš Mordino? Kde ho najdu?}
{1274}{}{Moná. Jeìtì jedna otázka...}
{1275}{}{Malej Jeíš...Poøezanej Jimmy J...Renesco. Mám to. Dík.}

# 75.  WHAT DO JOU EXPECT? (17)
{1290}{}{(Julesùv úsmìv zmizel) Hledám lidi jako ty, co pøicházejí do New Rena. Tohle je skvìlé místo pro obchod. Plus, nìkteré podniky mi platí za to, e k nim posílám nováèky. Staèí?}
{1291}{}{Ano. Teï potøebuju odpovìdi na pár otázek...}
{1292}{}{Ptám se jenom ze zvìdavosti. Dík za upøímnost.}

# 76.  CAR STOLEN (ACT INNOCENT) (17)
{1305}{}{Tvoje AUTO? Zaparkovanı tady? Nevidìl jsem ho.}
{1306}{}{COE, nejednou jsi SLEPİ? A moji PÌST vidíš, zmrde? VIDÍŠ ji?!! A teï mi øekni ještì jednou, e jsi moje auto nevidìl.  
 ...opova se, kurva.}
{1307}{}{Jule, jestli mi neøekneš co se stalo s mım autem, øeknu Wrigtovi, e jsi to byl TY, kdo prodal jeho synovi Jet, kterı
 ho zabil. Budeš mrtvej do hodiny. Mluv.}
{1308}{}{Jsi si JISTİ, Jule?}
{1309}{}{Ano, bylo zaparkovanı TÁMHLE. Nevíš jenom tak náhodou, kde by mohlo bıt?}
{1310}{}{Tak fajn. Chci se zeptat na nìco jiného...}
{1311}{}{Jdu se po nìm podívat.}

# 77.  JOU SURE JOU HAVEN'T SEEN IT? (76)
{1320}{}{Né, brácho, nevidìl jsem ho. }
{1321}{}{Né, ségro, nevidìl jsem ho. }
{1322}{}{Zkusím se poptat, ale Reno je velké mìsto...}
{1323}{}{Jule, já mám takovı divnı pocit, e víš, kde zmizelo mé auto. Jestli mi to nepovíš, pouiju tì jako støeleckı terè.
 Mluv.}
{1324}{}{No, stejnì díky. Chci se zeptat...}

# 78.  CAR STOLEN (CAUGHT) (76, 77)
{1340}{}{Ségro, já nevím NIC o tvém autì. }
{1341}{}{Brácho, já nevím NIC o tvém autì. }
{1342}{}{NEVIDÌL jsem co se sním stalo a NEVÍM kde je. }
{1343}{}{(Nenávistnì se podíval na Codyho pøes ulici.)}
{1344}{}{Fakt? To mi zní jako pìkná hromada sraèek, KAMARÁDE.}
{1345}{}{Take? Já VÍM, e jsi s ním nìco udìlal, take mi to radši øekni, ne udìlám nìco já TOBÌ.}
{1346}{}{Tak to nic, budu hledat dál.}

# 79.  ALL RIGHT, ALL RIGHT (78)
{1360}{}{Fajn brácho, fajn! }
{1361}{}{Fajn ségro, fajn!  }
{1362}{}{...vidìl jsem nìjaké chlápky, jako ho pøed chvíli brali. Bylo jich ale moc a já, víš --}
{1363}{}{Dr hubu a zaveï mì za nima. HNED.}
{1364}{}{To nic, podívám se po nich bez tebe.}

# 80.  FOLLOW HIM (79)
{1375}{}{Okay, okay...}
{1376}{}{Mimochodem...Jule? Jestli je jenom špatnì PODÍVÁŠ na toho kluka, vrátím se zpátky
 a strávím nìkohlik hodin tvım vradìním. Jasné? A teï jdi.}
{1377}{}{Ještì jedna vìc, Jule: Jestli uslyším, e budeš zkoušet nìco na Codyho, vrátím se a zabiju tì. 
 A teï mì zaveï k mımu autu.}
{1378}{}{(Následuj ho)}

# 81. INTRO, CODY = DEAD (WTG)
{1385}{}{H...hej. (Tìce se usmál. Oblak jeho kolínskì tì málem rozkašlal.) Já jsem Jules. Co hledáš?}
{1386}{}{H...hej. Hej, vítrej zpátky! (Tìce se usmál. Oblak jeho kolínské tì málem rozkašlal.) Co potøebuješ od svého
 pøítele Jula?}
{1389}{}{Chci se zeptat...}
{1390}{}{Fajn kolínská, Jule. Byla cítit všude kolem Codyho tìla. Jsi mrtvı.}
{1391}{}{Cody je mrtvı, Jule. A já se vsadím, e za to mùeš ty. Jsi mrtvı.}

# 82.  RUN (81)
{1405}{}{H-hej, já bych ti chtìl pomoct, ale nic nevím...hele, já musím jít.}
{1406}{}{Fajn kolínská, Jule. Byla cítit všude kolem Codyho tìla. Seš mrtvej, ty zasranej zkurvysynu.}
{1407}{}{Cody je mrtvı, Jule. A já se vsadím, e za to mùeš ty. Seš mrtvej, ty zasranej zkurvysynu}
{1408}{}{Èau Jule.}

# 83.  JJJ? (74, 84)
{1415}{}{To je ten kretén, kterı si myslí e je velkı dıler. Nemùeš ho minout... má pøes oblièej velkou jizvu.
 Ten kretén jednou lítal na Jetu a zkoušel se oholit bojovım noem. Smutné je, e to pøeil.}
{1416}{}{A Malej Jeíš Mordino? Kde ho najdu?}
{1417}{}{Hmmm, ještì jednu otázku...}

# 84.  LIL' JESUS? (74, 83)
{1425}{}{No, já bych byl opatrnı a rozhodnì bych jen tak nevtrhnul k Malımu Jeíšovi a nezaèal ho z nìèeho obviòovat. Ale jestli s ním chceš DOOPRAVDY 
 mluvit, nemùu ti bránit. Vìtšinou je v Desperádu támhle pøes ulici.}
{1426}{}{A "Poøezanej Jimmy J?" Kdo je to?}
{1427}{}{Aha. Ještì se chci zeptat...}

# 85.  POISONED (72)
{1435}{}{To mì nepøekvapuje...takové vìci se stávají ÈASTO v tomhle mìstì.}
{1436}{}{Co tím myslíš?}
{1437}{}{Co mi mùeš øíct o téhle prázdné nádobce na Jet?}
{1439}{}{Aha. Dík za tvùj èas.}

# 86.  JET CANISTER (85, 72)
{1450}{}{(Dívá se na nádobu.) Jako stovky dalších, kterı dennì vidím. Ale moje není...Mohla by bıt Poøezanıho Jimmyho J nebo  Renescova.}
{1451}{}{Poøezanej Jimmy J?}
{1452}{}{Renesco?}
{1453}{}{Hmmm. Ještì by mìl zajímalo...}

# 87.  JJJ 2? (86)
{1470}{}{To je ten zkurvysyn nahoøe na Druhı ulici. Nemùeš ho minout... má pøes oblièej velkou jizvu.
 Ten kretén jednou lítal na Jetu a zkoušel se oholit bojovım noem. Smutné je, e to pøeil.}
{1471}{}{A Renesco? Kde by se dal najít?}
{1473}{}{Jasnı. Dík.}

# 88.  RENESCO? (86, 87)
{1485}{}{To je ten starej hajzlík, kterı má drogérii na Obchodní Ulici. Jdi pár ulic na sever, zatoè doleva, tam kde se
 Salvatorova a Bishopova kasína dotıkaj, a pak pokraèuj po tı ulici dál. Je to napravo.}
{1486}{}{A "Poøezanej Jimmy J?" Kde ho najdu?}
{1487}{}{Dík, ale chci se ještì zeptat...}

# 89.  ARSENIC? (72, 73, 74)
{1500}{}{Øekni tomu zmrdovi, e jestli tohle vypustí ještì jednou ze svı smrdutı drky, ZABIJU ho døív ne starej Wright. 
Vím co znamenají takovı kecy. Takhle mluví chlap, kterej je posranej STRACHY.}
{1501}{}{Aha...hele ještì otázku...}
{1502}{}{Rozumím..}

# CAR FLOATER
{2000}{}{To je AUTO? Sákryš.}