#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
# QUICK LOOKS
{100}{}{Vidíš znièeného feáka.}
{101}{}{Vidíš hyperaktivního feáka.}

# EXAMINES
# 1. [MALE, CRASH AND BURN]
{150}{}{Vidíš znièeného feáka. Pohybuje se velmi pomalu.}
{151}{}{Vidíš znièeného feáka. Vypadá nemocnı.}
{152}{}{Vidíš znièeného feáka. Je tak hubenı, e by se spadnul pøi prvním závanu vìtru.}
{153}{}{Vidíš znièeného feáka. Upírá na tebe prázdnı pohled.}
{154}{}{Vidíš znièeného feáka. Má tak krvavé oèi, e by nejpíš mohl plakat krev.}
{155}{}{Vidíš znièeného feáka. Pøi kadém pohybu bolestivì mrká, jako by do nìj nìkdo zabodával jehly.}
{156}{}{Vidíš znièeného feáka. Pod oèima má velké váèky a vıraz jeho oblièeje naznaèuje velkou bolest.}
# 2. [MALE, HIGH ON JET]
{160}{}{Vidíš feáka. Na tváøi má šílenı vıraz.}
{161}{}{Vidíš feáka. Lehce se usmívá a pohybuje se v neslyšitelném rytmu.}
{162}{}{Vidíš feáka. Zírá prázdnì do prostoru.}
{163}{}{Vidíš feáka. Usmívá se a mává na nìco za tebou.}
{164}{}{Vidíš feáka. Neustále si osahává oblièej a nìco si pro sebe mumlá.}
{165}{}{Vidíš feáka. Navzdory znièenému oblièeji se usmívá, jakoby vyhrál v loterii.}
# 3. [FEMALE, CRASH AND BURN]
{170}{}{Vidíš znièenou feaèku.Pohybuje se velmi pomalu.}
{171}{}{Vidíš znièenou feaèku. Vypadá jakoby nejedla nìkolik mìsícù.}
{172}{}{Vidíš znièenou feaèku. Je tak hubená, e by ji srazil na zem jedinı závan vìtru.}
{173}{}{Vidíš znièenou feaèku. Její oèi vypadají jako èerné díry.}
{174}{}{Vidíš znièenou feaèku. Hladovì na tebe zírá.}
{175}{}{Vidíš znièenou feaèku s krvavım pohledem.}
{176}{}{Vidíš znièenou feaèku. Pøi kadém pohybu bolestivì mrká, jako by do ní nìkdo zabodával jehly.}
{177}{}{Vidíš znièenou feaèku. Má váèky pod oèima a ve tváøi bolestivı vıraz.}
# 4. [FEMALE, HIGH ON JET]
{180}{}{Vidíš feaèku. Na tváøi má extatickı vıraz.}
{181}{}{Vidíš feaèku. Najednou pláèe a smìje se.}
{182}{}{Vidíš feaèku. Smìje se a tancuje v rytmu neviditelného zpìvu.}
{183}{}{Vidíš feaèku. Zírá do prázdna a vzdychá.}
{184}{}{Vidíš feaèku. Smìje se a mává rukama na nìkoho za tebou.}
{185}{}{Vidíš feaèku. Neustále se škrábe na pai.}
{186}{}{Vidíš feaèku. Kroutí se jako had a jenom ztìka drí rovnováhu.}
{187}{}{Vidíš feaèku. Smìje se, jakoby vyhrála v loterii.}

# FLOAT DIALOGUE:
# 5. JUNKIE=WASTED; ENCLAVE DESTROYED IS TRUE
{200}{}{::Usmívá se a mrká::}
{201}{}{::Slabì tleská a pomrkává::}
{202}{}{::Slabì píská::}
# 6. JUNKIE=STONED; ENCLAVE DESTROYED IS TRUE
{210}{}{Seš nejlepší...uh, tento. Ty seš nejlepší TENTO!}
{211}{}{::Vyje::}
{212}{}{, ty, ty seš lepší ne JET!}
{213}{}{::Divoce se smìje::}
{214}{}{::Divoce tleská::}
{215}{}{::Píská::}
# 7. JUNKIE = WASTED
{220}{}{Moje hlava}
{221}{}{Bolí a pálí...bolí a páli...}
{222}{}{Bolí to víc ne obvykle...}
{223}{}{A myslím, e to bude dlouho dlouho...}
{224}{}{::Ooooooh::}
{225}{}{::Pláèe::}
{226}{}{::Kašle::}
{227}{}{::Škrábe se::}
{228}{}{::Nìco si mumlá::}
{229}{}{Nemùu... nemuu u vydret...}
{230}{}{Nevidìl jsi Juese? Potøebuju spravit.}
{231}{}{Nevidìl jsi Poøezanıho Jimma J? Potøebuju spravit. }
{232}{}{Hledám Renesca. Renesco mi pomùe.}
{233}{}{Já vím, e Fallout 2 není 3D hra, ale stejnì by mohla podporovat moji fungl novou Rivu TNT.}
# 8. JUNKIE = HIGH
{240}{}{[Zpívá.] Já chci jenom lítat. Obejmi mì bejby, jenom mì obejmi.}
{241}{}{[Zpívá.] Rakeák si lítá po obloze, rakeák...}
{242}{}{Pozor! Rùovı deathclaw na tøech hodinách.}
{243}{}{Tolik svìtel! Pálí mì do oèí, moje oèi...}
{244}{}{Svìtla jsou tak jasná... ::Zaèíná plakat::}
{245}{}{Reeeeee-no. Reeeeee-no. Reno?}
{246}{}{Kde mám hlavu?}
{247}{}{Chlastat - pivo - kouøit - trávu}
{248}{}{Tá dı dá dy dá}
{249}{}{::šklebí se::}
{250}{}{::Smìje se::}
{251}{}{::Smìje se a kıve hlavou::}
{252}{}{Wheeeeeeee}
{253}{}{Fajn ulice. Fajn stìna. Fajn fet. }
{254}{}{Uau...kam zmizela obloha...?}
{255}{}{Jestli moje hadry nebudou koneènì dret hubu, tak si je sundám.}
{256}{}{Moje boty dıchají.}
{257}{}{Já vím, e Fallout 2 není 3D hra, ale stejnì by mohla podporovat moji fungl novou Rivu TNT.}
{258}{}{Díváš se na mnì?! Díváš se na mnì?!! Zabiju tì!}
# 9. JUNKIE=WASTED; ENCLAVE DESTROYED IS TRUE
{270}{}{Uh, poblahopøál bych ti k vítìzství na enklávou, ale bolí mì moc hlava. Pøijï jindy.}
{271}{}{::Zkouší tleskat, ale nemùe se trefit ::}
{272}{}{Jen tak dál. Byl jsem moc sjetej, abych to vidìl sám, ale urèitì to bylo super.}
{273}{}{Uh...díky za záchranu všech. Nemáš náhodou nìjakı drobnı?}
{274}{}{Já jsem taky jednou zachránil svìt. Moná, byl jsem sjetej jako prase.}
{275}{}{Nemìli v Enklávì nìjakej Jet?}
{276}{}{Ty seš ten lump, co udìlal tu velkou šupu na jihu? Dìsnì mì z toho bolela hlava.}
{277}{}{Já vím, e jsi zachránil svìt, ale my nedùleité herní postavy teï musíme nést následky.}
{278}{}{Chris Avellone mì vymyslel, Tom French mi napsal scénáø, a Birdman mì pøeloil, 
 take technicky nejsem za svou závislost  odpovìdnı, jasnı?}
{279}{}{Jo, skvìlı, e jsi dohrál tuhle blbou hru. Jenome to znamená, e teï nás smaeš z harddisku.
 Fakt dík.}
# 10. JUNKIE=STONED; ENCLAVE DESTROYED IS TRUE
{291}{}{Seš nejlepší...uh, tento. Ty jseš nejlepší TENTO!}
{292}{}{, seš lepší ne JET!}
{293}{}{Ty vole, chtìl bych vidìt tu øachu. TO muselo bejt nìco, co?}
{294}{}{Miluju tì! Jsi HRDINA. Zasranej HRDINA! Umiluju tì k smrti!}
{295}{}{A budeš pøíštì kopat prdele Enklávì, pøijï za mnou a budem to dìlat SPOLU.}
{296}{}{Nakopni jim PRDEL,  }
{297}{}{Já vím, e jsi zachránil svìt, ale my nedùleité herní postavy teï musíme nést následky.}
{298}{}{Mìl by sis zahrát ještì jednou jako narkomanskı charakter. Fakt, je to skvìlı.
Miluju to.}
{299}{}{Díky za záchranu.bylo to fakt suuuuper.}
{300}{}{Já bych taky zlikvidoval Enklávu, kdybych mìl dost Jetu.}
{301}{}{[Zpívá.] "We don't need another hero, we don't need to know the way home..."}
{302}{}{Chris Avellone mì vymyslel, Tom French mi napsal scénáø, a Birdman mì pøeloil, 
 take technicky nejsem za svou závislost  odpovìdnı, jasnı?}
{303}{}{Dejme si nìjakej JET a oslavme tvı vítìzství. Platíš.}
{304}{}{A smaeš tuhle hru z hardu, budem ještì existovat?}
{305}{}{Uh...jaké drogy to Enkláva testovala? Nebyl to Jet?}

# CLICK DIALOGUE:
# 11. JUNKIE = WASTED, PLAYER = POWER ARMOR
{320}{}{Jak se vlezeš na záchod s tou vìcí na sobì?}
{321}{}{Uh...mluvíte se mnou?}
{322}{}{Oh, ty absáky jsou èím dál tím horší. Teï na mnì mluví elezní lidi.}
{323}{}{Nìkdo na tebe nalil elezo?}
{324}{}{Hej, uh...nemáš tam uvnitø nìjakej JET?}
{325}{}{Nemáš nìjakı drobnı...? Tak nic.}
{326}{}{::uká ti na brnìní:: Haló? Nìkdo doma?}
{327}{}{Ty jsi nìjakej køíenec s lednièkou?}
{328}{}{Není v tom hic?}
# 12. JUNKIE = WASTED, PLAYER = SLAVER
{350}{}{Dej mi nìjakej Jet a já ti øeknu, kde najdeš snadnou koøist, otrokáøi.}
{351}{}{Mùeš mít moje dìcko, otrokáøi, jestli máš nìjakej Jet na zaplacení...}
{352}{}{Jenom pár drobnejch a já budu tvùj otrok, jenom mi dej nejdøív Jet.}
{353}{}{Budu tvùj otrok, jenom mi dej nìjakej Jet.}
{354}{}{Mùeš mì prodat, kdy mi dáš Jet.}
{355}{}{Ne, kámo, nejsem na drogách. Proè, chceš nìjakı koupit?}
# 13. JUNKIE = WASTED, PLAYER = PRIZEFIGHTER OR MADE MAN
{360}{}{Ty seš bojovník? Nemáš nìjakı drobnı na pùjèení?}
{361}{}{No tak, dej mi pár drobnejch.}
{362}{}{Mùeš mi pùjèit nìjakı drobnı? Vrátím ti to, mùeš se spolehnout.}
{363}{}{Hej, uh...nemáš Jet?}
{364}{}{Kámo, potøebuju *letìt,* víš co tím myslím?}
{365}{}{Opravdu potøebuju nìjaké léky pro syna. Pomozte mi.}
{366}{}{Nemáš drobnı?}
{367}{}{Potøebuju jenom pár drobnıch na jídlo...}
{368}{}{Budu ti slouit, kdy mi dáš nìjakı Jet.}
{369}{}{Mùeš mì prodat do otroctví, jenom mi dej nìjakı Jet.}
{370}{}{Ne, kámo, nejsem na drogách. Proè, chceš nìjakı koupit?}
{371}{}{Ty jsi èlen }
{372}{}{Mùu si puèit pár drobnıch...? No tak, nenech se prosit.}
{373}{}{Dìlám za Jet...}
# 14. JUNKIE = MALE, WASTED, PLAYER = NO REP OR PORN STAR
{380}{}{Hej, brácho? Pomùeš mi lítat?}
{381}{}{Udìlám cokoli pro pár drobnejch. Nebo Jet, jestli máš.}
{382}{}{Nechceš se proletìt?}
{383}{}{Tati?}
{384}{}{Kámo, potøebuju *letìt,* víš co tím myslím?}
{385}{}{Ne, kámo, nejsem na drogách. Proè, chceš nìjakı koupit?}
{386}{}{Psssst. Mùeš mi sehnat nìjakej Jet?}
{387}{}{Mùu si puèit pár drobnıch...? No tak, nenech se prosit.}
{388}{}{Dìlám za Jet...}
{389}{}{No tak, kámo, pujè mi pár babek}
{390}{}{Mùeš mi pùjèit nìjakı drobnı? Vrátím ti to, mùeš se spolehnout.}
{391}{}{Hey, uh...nemáš Jet, kámo?}
{392}{}{Opravdu potøebuju nìjaké léky pro syna. Pomozte mi.}
{393}{}{Nemáš drobnı?}
{394}{}{Potøebuju jenom pár drobnejch na jídlo...to je všechno...}
{395}{}{Vyspím se s tebou za Jet nebo pár drobnıch. Jsem èistej, slibuju.}
{396}{}{Bıval jsem nejvìtší hlavoun  tady v Renu. Za Jet tì mùu provést kolem...}
{397}{}{Mùeš mì prodat do otroctví, jenom mi dej nìjakı Jet.}
{398}{}{Mùeš mì prodat do otroctví, jenom mi dej nìjakı Jet.}
{399}{}{Hej, sestro? Pomùeš mi lítat?}
{400}{}{No tak sleèno, jenom pár drobnıch.}
{401}{}{Hej uh...nemáte drobné, sleèno?}
{402}{}{Hele, potøebuju *letìt,* víš co tím myslím?}
{403}{}{Ne, nejsem na drogách. Proè, chceš nìjakı koupit?}
{404}{}{Mami?}
# 15. JUNKIE = FEMALE, WASTED, PLAYER = MALE, NO REP OR PORN STAR
{420}{}{Hej, brácho? Pomùeš mi lítat?}
{421}{}{No tak chlapèe, jen pár babek.}
{422}{}{Vyspím se s tebou za Jet nebo pár drobnıch. Jsem èistá slibuju.}
{423}{}{Jsem levnìjší ne rodinné kurvy. Ale neøíkej o mnì, e jim lezu do kšeftu.}
{424}{}{Pro peníze udìlám cokoli, nebo pro Jet, jestli máš.}
{425}{}{Bıvala jsem královna krásy...}
{426}{}{Nechceš se s nìkım proletìt?}
{427}{}{Ne, nejsem na drogách. Proè, chceš nìjakı koupit?}
{428}{}{Tati?}
{429}{}{Psssst. Nemùeš mi sehnat Jet?}
{430}{}{Mùu si pujèit pár drobnıch...? No tak, nenech se prosit.}
{431}{}{Pracuju za Jet...}
{432}{}{Mùu si pujèit pár drobnıch...? No tak, vrátím ti to.}
{433}{}{Kámo, potøebuju *letìt,* víš co tím myslím?}
{434}{}{Opravdu potøebuju nìjaké léky pro syna. Pomozte mi.}
{435}{}{Nemáš drobnı na víc?}
{436}{}{Jenom pár drobnıch na jídlo...}
{437}{}{Budu ti otroèit, jenom mi dej nìjakı Jet.}
{438}{}{Mùeš mì prodat do otroctví, jenom mi dej nìjakı Jet.}
{439}{}{No tak sleèno, pár babek?}
{440}{}{Hej, sestro? Pomùeš mi letìt?}
{441}{}{Mùu tì potìšit...jestli máš nìjakej Jet.}
{442}{}{Hej, uh...nemáš Jet?}
{443}{}{Sestro, potøebuju letìt.}
{444}{}{Ne, sestro, nejsem na drogách. Proè, chceš nìjakı koupit?}
{445}{}{Mami?}
# 16. ANY STONED REACTION, POWER ARMOR
{450}{}{Do prdele...! Kdo jsi? Nìjakej robot?}
{451}{}{Co jsi bral, es skonèil obalenej elezem?}
{452}{}{Uau. eleznej èlovìk. A mluví se mnou.}
{453}{}{Jestli jsi z jiné planety, mìl by ses tam vrátit...tady není nic k dobıvání.}
{454}{}{Oooooh. Vidím odrazy svìtla Nového Rena na tvé pøilbì, cizinèe.}
{455}{}{Já jsem tak vysoko...uh, co jsem to øíkal?}
{456}{}{Ty vole, v tom musí bıt horko.}
{457}{}{Je tam nìkdo?}
{458}{}{No, jestlipak to není Pan Darttth Vadrrr}
{459}{}{Kámo, ty u máš dost. Vypadáš nìjak plechovì.}
{460}{}{Jsi v blbé høe, zkus Mechwarriora nebo EarthSIege.}
{461}{}{Ty jsi kosmonaut?}
{462}{}{Potøeboval bych poøádnou dávku, ne bych si na tebe nìco dovolil.}
# 17. ANY STONED REACTION, ANY SLAVER OR PRIZEFIGHTER
{470}{}{Hej otrokáøi, jak je?!}
{471}{}{Chceš mì zotroèi Huh? Zkus to! Jsem neporazitelnej!}
{472}{}{Skus si mì chytit, otrokáøi!}
{473}{}{Nechceš se podìlit o trochu Jetu, otrokáøi?}
{474}{}{Skoro na tebe nevidím, tam dolù, otrokáøi. Tak vysoko jsem.}
{475}{}{Rıpeš do mnì, otrokáøi? Jsem napumpovanej Jetem. Nakopu ti PRDEL!}
{476}{}{Necheš se mnou proletìt, otrokáøi?}
{477}{}{Proè jste dva? Dvojèata?}
{478}{}{Huh? Seš opravdovej?}
{479}{}{Já jsem tak krásnì sjetej...}
{480}{}{Chceš lítat? Promluv si s Juuuuulem...}
{481}{}{Poøezanej Jimmy J ti píchne, he he.}
{482}{}{Jestli uvidíš Renesca, øekni mu, e zaplatím zítra.}
{483}{}{Poøezanej Jimmy má nejlepší fet. }
{484}{}{Mluvíš se mnou? Mluvíš se mnou?!}
{485}{}{Chceš trochu? Nedám!}
{486}{}{::Zírá na tebe zamlenım zrakem::}
{487}{}{Chceš se proletìt?}
{488}{}{Hej, šampióne, jak je?!}
{489}{}{Nechceš si zaboxovat? Huh? Tak pojï!}
{490}{}{Rıpeš do mnì, šampióne? Jsem napumpovanej Jetem! Nakopu ti PRDEL!}
# 18. ANY STONED REACTION TO MADE MAN
{500}{}{Ho! Pozor, Boss jde!}
{501}{}{Skoro tì tam dole nevidím, gangstere. Tak jsem vysoko.}
{502}{}{Proè jste dva? To je tvoje dvojèe?}
{503}{}{Huh? Seš opravdovej?}
{504}{}{Gangstere já jsem tak sjetej...uh, coe?}
{505}{}{Chceš se proletìt, gangstere?}
{506}{}{Chceš se proletìt, gangstere? Promluv si s Julesem.}
{507}{}{Poøezanej Jimmy J ti píchne, he he.}
{508}{}{Jestli vybíráš pro Renesca, øekni mu, e zaplatím zítra.}
{509}{}{Poøezanej Jimmy má nejlepší fet. }
{510}{}{Mluvíš se mnou? Mluvíš se mnou?!}
{511}{}{Rıpeš do mnì, mafiáne? Jsem napumpovanej Jetem! Nakopu ti PRDEL!}
{512}{}{Chceš trochu, hangstere? Zapomeò!}
{513}{}{::Zírá na tebe zamlenım zrakem::}
# 19. ANY STONED REACTION TO DRUGGED PLAYER
{520}{}{Whoa...na èem to jedeš? Nechceš se podìlit?}
{521}{}{A já si myslel, e jsem v prdeli.}
{522}{}{Hej, kámo...podìl se se mnou.}
{523}{}{Chtìl jsem se tì zeptat, jestli si nechceš zalítat, ale vidím, e je to zbyteènı.}
{524}{}{Proè jste dva? To je tvoje dvojèe?}
{525}{}{Kde jsi sehnal fet?}
# 20. ROBOBRAIN OR MARCUS
{530}{}{Hele, neotáèej se, ale jede za tebou mozek v krabici.}
{531}{}{Whoa. Musel jsem brát nìjakej drsnej fet ...Vidím roboty jezdit kolem.}
{532}{}{Jestli tady uvidím toho robota jezdit ještì jednou, konèím s Jetem.}
{533}{}{Jednou jsem se cítil jako ten tvùj kamarád v plechu. Øekni mu, e bude okej, a to pøejde.}
{534}{}{Co se stalo tomu tvému kamarádovi s mozkem? Pøišel o tìlo?}
{535}{}{ØEKNI mi, e ten robotí mozek není skuteènı. Prosím.}
{536}{}{Whoa. Podívejte na ten mozek.To je mozek na drogách, nebo jsem nikdy ádnı nevidìl.}
{537}{}{Chceš se proletìt? A co tvùj pøítel robot?}
{538}{}{Rıpeš do mnì, robotofile? I Jsem napumpovanej Jetem! Nakopu ti PRDEL a pak i tomu robotovi!}
{539}{}{Chceš trochu, robotofile ?! Huh?}
{540}{}{Huh? Jsi skuteènej?}
{541}{}{Já jsem tak sjetej...uh, coe?}
{542}{}{Chceš lítat? Promluv si s Juuuuulem...}
{543}{}{Poøezanej Jimmy J ti píchne, he he.}
{544}{}{Jestli uvidíš Renesca, øekni mu, e zaplatím zítra.}
{545}{}{Poøezanej Jimmy má nejlepší fet ve mìstì. }
{546}{}{Mluvíš se mnou? Mluvíš se mnou?!}
{547}{}{::Zírá na tebe zamlenım zrakem::}
{548}{}{Hele, neotáèej se, ale jde za tebou mutant.}
{549}{}{Whoa. To byl nìjakej drsnej fet, vidím tady bìhat mutanty.}
{550}{}{Jsem tak vysoko, nebo je tvùj pøítel dvoupatrovej?}
{551}{}{::Smìje se:: Ten tvùj mutant má hovno na botì.}
{552}{}{Uh...to je mutant, nebo jsem tak sjetej?}
{553}{}{Tvùj velkej kámoš vypadá, e je  pìknì v prdeli.}
{554}{}{Ten tvùj kámoš je nìjakej lutej.}
{555}{}{Ten velkej chlápek je opravdovej? VYpadá jako mutant.}
{556}{}{Chceš se proletìt? Klidnì i s tím mutantem?}
{557}{}{Rıpeš do mnì, mutantofile? I Jsem napumpovanej Jetem! Nakopu ti PRDEL a pak i tomu mutantovi!}
{558}{}{Chceš trochu, mutantofile ?! Huh?}
# 21. STONED MALE REACTION TO COMP: SULIK OR NO REP AT ALL
{560}{}{Hele, neohlíej se, ale jde za tebou divoch.}
{561}{}{Whoa. Hele na divocha. Fakt velká kost.}
{562}{}{Whoa. Ví ten tvùj kámoš o tom, e mu z nosu roste velká kost?}
{563}{}{Whoa. Drsnej jet, vidím chlápka kterımu roste z nosu kost.}
{564}{}{Jsem tak sjetej, nebo má tvùj kámoš opravdu kost v nose?}
{565}{}{Radši øekni svımu kámošovi, e mu nìkdo vrazil do nosu kost.}
{566}{}{Jsem tak vysoko e tì skoro nevidím}
{567}{}{Proè jste dva? To je tvoje dvojèe?}
{568}{}{Huh? Seš opravdovej?}
{569}{}{Já jsem tak sjetej...uh, coe?}
{570}{}{Cheš se se mnou proletìt?}
{571}{}{Chceš lítat? Promluv si s Juuuuulem...}
{572}{}{Poøezanej Jimmy J ti píchne, he he.}
{573}{}{Jestli uvidíš Renesca, øekni mu, e zaplatím zítra.}
{574}{}{Poøezanej Jimmy má nejlepší fet ve mìstì. }
{575}{}{Mluvíš se mnou? Mluvíš se mnou?!}
{576}{}{Rıpeš do mnì? I Jsem napumpovanej Jetem! Nakopu ti PRDEL!}
{577}{}{Chceš trochu?! Huh?}
{578}{}{::Zírá na tebe zamlenım zrakem::}

# use jet on junkie dialog
{600}{}{Dík...}
{601}{}{Mmmm...}
{602}{}{Seš kámoš.}
{603}{}{j}
{604}{}{J}
{605}{}{Dej mi ee J... ummm...}

# endings for middle insertion dialogs
{796}{}{! KOPAT PRDEL! KOPAT PRDEL?!!!}
{871}{}{ rodina? Mùeš mi sehnat Jet?}