#tenhle soubor pøeložil Birdman - birdman@post.cz, http://get.to/birdman
# 0. QUICK LOOK
{100}{}{Vidíš Keitha Wrighta.}

# 0. LOOK [MALE]
{150}{}{Vidíš hubeného, bledého muže s dlouhými blond vlasy. Dívá se na tebe.}
{151}{}{Vidíš Keitha Wrighta. Dívá se na tebe.}

# 1. FLOAT DIALOGUE: WARNING (WTG)
{200}{}{Kdo jsi?}
{201}{}{Co chceš?}

# 2. FLOAT DIALOGUE: WARNING - KNOWS PLAYER BUT NOT MADE MAN (WTG)

# 3. FLOAT DIALOGUE: WARNING - PLAYER IS MADE MAN (WTG)
{220}{}{Hej, }

# 4. INTRO (WARNING) (WTG)
{230}{}{Udìlej další krok smìrem k tìm dvìøím a budeš toho litovat.}

# 5. FLOAT (DAD IS DEAD) (WTG)
{240}{}{Poøád nemùžu uvìøit, že je táta mrtvej. Je toho tolik, co jsem mu chtìl øíct...}

# 6. INTRO (NORMAL) (WTG)
{250}{}{Otrokáøi, dostal ses do špatné èásti mìsta. Jestli rychle nevyklopíš, co tady chceš, 
budeš po krk v prùseru.}
{251}{}{Já tì neznám, táta tì nezná, a jestli nezaèneš mluvit, tak na tom ani nebude záležet.}
{252}{}{Jak to jde, }
{253}{}{Díky za vypátrání Richardova vraha, }
{254}{}{Co chceš?}
{255}{}{Mattah. Chlap je Mattah!}
{256}{}{Jablaba cing cing}
{257}{}{Odejdi}
{258}{}{Hledám práci. Nabírají Wrightovi?}
{259}{}{Hledám práci. Posílá mì Chriss. Nabírají Wrightovi? }
{262}{}{Èau Keithe. Potkal jsem tvou mámu.}
{263}{}{Mùžeš mi øíct nìco o svém bráchovi Richardovi?}
{264}{}{To nic, sorry že otravuju.}

# 7. RETARD (6)
{280}{}{Vypadni odsaï, debile. Ještì jednou na mì otevøeš rypák a cedník ti bude øíkat brácho.}
{281}{}{Dírýýý dírýýý všude dírýý.}
{282}{}{Šámma Lámma DING DONG}

# 8. HOLES HOLES HOLES IN MY SOLES (7)
{290}{}{Vypadni! Poslední varování!}
{291}{}{Já ale chýýtrýýý, cink cink.}
{292}{}{DING DONG! DING DONG!}

# 9. A-GIN, MY SHIN, LOTS OF DIN-DIN (8)
{300}{}{Varoval jsem tì }
{301}{}{Hunh?}

# 10. WHO ARE YOU? (6, 11)
{310}{}{Jsem  Keith Wright z rodiny Wrightù. Tak, øekneš mi teï, co tady chceš?}
{312}{}{Chris mi øekl, abych se tady stavil. Hledám práci. Mùžeš mi pomoct?}
{313}{}{Keith Wright, jo? Potkal jsem tvou mámu.}
{315}{}{Co je to za místo?}

# 11. WHAT IS THIS PLACE (6, 10)
{325}{}{Tohle je dùm Rodiny Wrightù. Tak, øekneš mi teï, co tady chceš?}

# 12. CHRIS TOLD ME TO STOP BY . . . (6, 10, 11)
{335}{}{Chris tì poslal, jo?}
{336}{}{Pøesnì tak. Øíkal, že by se pro mì možná našla nìjaká práce.}

# 13. I'M LOOKING FOR A JOB . . . [GOOD RESPONSE] (6, 10, 11)
{345}{}{Nevím, jestli to má nìjaký smysl, ale mùžu se zeptat táty...}
{346}{}{TO bych ocenil.}

# 14. I'M LOOKING FOR A JOB . . . [BAD RESPONSE] (6, 10, 11)
{355}{}{Ne...nenabíráme svaly jako ostatní rodiny. Alespoò zatím. }
{356}{}{Ne, my se s otrokáøskou verbeží nebratøíèkujeme. }
{357}{}{Radši zmiz.}
{358}{}{Nepùjdu, dokud si nepromluvím s panem Wrigtem.}
{359}{}{Tak dobøe..}

# 15. I'M NOT LEAVING UNTIL I SEE MR. WRIGHT. (14)
{365}{}{Ne, øekl bych že odejdeš, protože vypadáš jako osoba, která ODCHÁZÍ. TEÏ!}
{366}{}{Já NEODCHÁZÍM.}
{367}{}{Dobøe.}

# 16. I'M NOT LEAVING. (15)
{375}{}{Varoval jsem tì...}
{376}{}{Tak pojï...}

# 17. TELL ME ABOUT MOM (6, 10)
{380}{}{Uh... co je s ní? Zase je v nìjakém prùšvihu?}
{381}{}{Ne. To je u ní èasté?}
{383}{}{Ne, jenom jsem byl zvìdavý. Pozdìji, Keithe.}

# 18. NO. IS THAT A COMMON OCCURRENCE? (17)
{390}{}{Nìkdy. Poøád káže o zle, které èíhá v  pití a hraní a skoro všude jinde.
Obèas se dostane do prùseru a táta je pak dìsnì naštvanej.}
{391}{}{Ví vùbec tvoje máma, co dìlá vaše rodina?}
{392}{}{Tak dík za rozhovor, Keithe, já pùjdu.}

# 19. DOES YOUR MOM HAVE ANY IDEA WHAT YOUR FAMILY DOES? (17, 18)
{400}{}{Nee, nemá o tom páru. Myslí si, že táta je èistej, a nemá dost rozumu, aby si všimla, co se dìje kolem.
  Kdyby našla tu palírnu pod nádražím, udìlala by tu peklo.}
{401}{}{Aha. Díky, Keithe.}

# 20. MOM = AFTER WRECKED STILLS (17)
{410}{}{(Vrtí hlavou.) Teï to pøehnala, s tím znièením tátovy palírny. Dìlníci mìli strach ji zastavit,
a táta jí pak jednu støelil a ona mu to vrátila. Nìjakou dobu bude trvat, než se táta
 postaví zase na nohy.}

# 21. CAN YOU TELL ME ABOUT RICHARD? (6, 10)
{420}{}{Fajn kluk. Zatracenì, jestli nìkdy pøijdeme na to, kdo mu to udìlal...}
{421}{}{Nìjaký nápad, kdo to mohl udìlat?}
{422}{}{No, doufám, že vraha najdete. Èau Keithe.}

# 22. ANY IDEAS WHO MIGHT'VE DONE IT? (21)
{430}{}{Vìtšina ostatních rodin prodává  Jet, mohl to být kdokoli z nich. Mordinové mají ale nejvíce dýlerù,
 protože dìlají nejvíce Jetu. já bych to typoval na jednoho z nich.}
{431}{}{Které dýlery podezøíváš?}
{432}{}{Mùžeš mi øíct nìco víc o Richardovi?}

# 23. WHAT DEALERS ARE SUSPECT? (22, 24)
{440}{}{Hroamdu: Poøezanej Jimmy J na druhý ulici, ten starý zkurvysyn Renesco ve West Endu...a Jules
 taky prodává na zaèátku mìsta, ale vìtšinou pitomým turistùm. No, a pak je tady Malej Ježíš Mordino.}
{441}{}{Malej Ježíš Mordino?}
{442}{}{Mùžeš mi øíct nìco víc o Richardovi?}
{443}{}{Dík za  info, Keithe.}

# 24. CAN YOU TELL ME A LITTLE MORE ABOUT RICHARD? (22, 23, 27)
{450}{}{Hodnej, èistej kluk. Držel se dál od problémù, a na Wrighta je to nìco. Pohøbili jsme ho 
 na planinách Golgotha pøed nìjakou dobou, ale i tak nechce máma, abychom dìlali nìco s jeho místností.
 Je to pro ní tìžký, víš?}
{451}{}{Který pokoj byl jeho? Myslíš, že by mìla vaše matka nìco proti, kdybych se tam porozhlédnul?}
{452}{}{Kteøí dýleøi mu mohli dát Jet?}
{454}{}{Pohøbený na Golgotì, jo? Hmmm. Dík za  info, Keithe.}

# 25. CAN I LOOK AROUND HIS ROOM? (24)
{460}{}{Jeho pokoj? Je to ten prázdnej vedle mámina, druhej dole od kuchynì. A co se týè rozhlížení... no... hele, nezùstávej
tam dlouho... a neudìlej tam nepoøádek, nebo se máma zblázní.}
{461}{}{Díky, Keithe. Bude to chvilièka.}

# 26. JOB, SUCCESS . . . (12, 13)
{470}{}{Poèkej. (Zaklepal na dveøe za sebou.) Tati? (Strèil hlavu dovnitø. Je slyšet nezøetelný rozhovor,pak se vrací a kýve hlavou ke dveøím.) Mùžeš jít dovnitø, ale dej si bacha. Táta má blbou náladu.}
{471}{}{Díky.}

# 27. LIL' JESUS (23)
{480}{}{Je to syn Velkýho Ježíše. Bastard. Mohl chytit Richarda samotného,a pak ho napumpovat Jetem.
 Kdybys ho hledal, podívej se do  Desperáda. Malej Ježíš se tam potuluje kolem svýho dìdka.}



# END LINES
{1220}{}{. Co se dìje?}
{1252}{}{ . Všichni se k tobì chovají dobøe? Mùžu ti nìjak píchnout?}
{1253}{}{. Dlužíme ti toho dost a Wrightovi svoje dluhy platí. Co potøebuješ?}
