#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
# 0. QUICK LOOK
{100}{}{Vidíš sleènu Kitty.}

# 0. LOOK
{150}{}{Vidíš úasnou enu. I pøes její...odhalující šaty se tváøí profesionálnì a obchodnì.}

# 1. FLOAT [MALE, ENCLAVE IS DESTROYED]
{200}{}{Zisky z prvního kvartálu šly trochu nahoru...a kdy pøipoèítáme zvıšenı poèet zákazníkù...}
{201}{}{Jestli ji chytím, jak bere Jet, tøeba jenom kapièku, konèí tady...}
{202}{}{Brzo dorazí další karavana, to zase bude nadrenıch zákazníkù...}
{203}{}{Potøebuju více dìvèat na tu párty u Bishopù...}
{204}{}{Zatracené Macrosoftí Dveøe...}
{205}{}{Tolik èasu trávím opravou tìch záznamù... ádná poøádná práce kvùli toho není hotová.}
{206}{}{Jules by sem mìl co nejdøív poslat nìjaké nadrené...a bohaté...lidi.}

# 2. INTRO DIALOGUE (WTG)
{215}{}{(ena pøed tebou vyniká omraèující krásou. Jakmile ji oslovíš, zvedá pohled od práce a usmívá se.)
 Ah, nová tváø! Já jsem sleèna Kitty...vítejte v Koèièí Pacce.}
{216}{}{Zdravím!}
{217}{}{No, jestlipak to není nejslavnìjší boxer v Renu!}
{218}{}{Byla jsem zvìdavá, kdy vás pan }
{1218}{}{ pošle k nám...(Mrkla.)}
{219}{}{Ale ale, jestlipak to není naše hvìzda støíbrného plátna.}
{220}{}{Èím poslouíme dnes, pane?}
{221}{}{Èím poslouíme dnes, sleèno?}
{222}{}{poslouhit?}
{223}{}{Ty hezkhé vlasavy}
{224}{}{Ty øekla 'poslhouhouit' Huh-Huh-Huh-Huh-Huh}
{225}{}{George øék e máme pùl vlastního a já bych mìla nechodit sem jinak on mi nepuèí králíèek tak já jít zas pryè}
{226}{}{Jules mi øíkal, e se mám stavit tady, kdybych hledal nìjaké...vzrušení.}
{227}{}{Hledám nìjakou... zábavu.}
{228}{}{Vlastnì, chci se na nìco zeptat....}
{229}{}{Víte, po celé poušti jsou rozházené tyhlety magazíny jménem "Koèièí Packa". Jeden mám zrovna tady.}
{230}{}{Tady je ta sbírka magazínù, kterou jste chtìla.}
{231}{}{Dneska nic, dík.}

# 3. RETARD ANSWER (2)
{240}{}{(Hezká dáma ti poloila dlaò na èelo) Oh, uboáèku...mùeš tady na chvíli zùstat a 
 schovat se pøed horkem, ale ne moc dlouho, dobøe? Slib mi to.}
{241}{}{Okayy, héézka pani dìkuju}

# 4. LOOKING FOR ACTION (2, 12)
{245}{}{(Usmála se a mrkla.) Take takhle? No, v tom pøípadì jste na správném místì. Máte-li jakékoli pøání nebo fantazii, my Vám to mùeme zajistit...a ádnou nesmìlost, slyšeli jsme tu u všechno. Take, co to bude?}
{246}{}{No, omlouvám se za upøímnost, ale nejví mì láká poøádnì do hloubky VÁS. V kolik hodin tady konèíte?}
{247}{}{Záleí...jaká je nabídka?}
{248}{}{Chci nìco speciálního pro kamaráda.}
{249}{}{Chci nìco speciálního pro jednoho z kamarádù. Má to... narozeniny.}
{250}{}{Chci se zeptat...}
{251}{}{No, vlastnì u nic. Musím jít. Nashledanou.}

# 5. ASK HER OUT (4)
{255}{}{Jsem poctìna, ale...ne. nemùu.}
{256}{}{Ale, no tak. Jenom jeden drink.}
{257}{}{Hele, jestli nemáte ráda eny, tak já to naprosto chápu. Sakra, vdy já nesnáším vìtšinu enskıch, co potkám.
 U teï máme nìco spoleèného.}
{258}{}{Hej, nebojte se...Já si to brnìní sundám!}
{259}{}{Tak dobøe, ale chci se alespoò zeptat...}
{260}{}{Sorry, nechci naléhat. Nashledanou.}

# 6. ASK HER OUT (5)
{265}{}{(Rozhlíí se, potom zašeptá.) Pøijï a udìláš to, co musíš udìlat pro záchranu svıch lidí. Pak si promluvíme okay?}
{266}{}{Tak dobøe. Chci se aspoò zeptat...}
{267}{}{Domluveno. Na vidìnou.}

# 7. MENU (6)
{275}{}{No...(Jede prstem po papíru)...máme tady sladké milování, sexuální rej a nejrùznìjší
 další exotiku. (Usmívá se) Otázka je, na co máte náladu VY?}
{276}{}{Nìjaká ...orální pøízeò?}
{277}{}{Nìjakı obyèejnı, tvrdı sex mi bohatì staèí.}
{278}{}{Chci to poøádnì, takové menší orgie.}
{279}{}{Chci si jenom popovídat, šlo by to?}
{280}{}{Mám zvláštní...dramatickou...ádost.}

# 8. & 9 BLOWJOB (7)
{290}{}{Dobrá tedy. }
{291}{}{(Mrkla.) Bude to zadarmo.}
{292}{}{Bude to }
{293}{}{Dobøe. tady jsou peníze.}
{294}{}{S tou cenou se rozhodnì hádat nebudu. Do toho.}
{295}{}{Radši nic. Stejnì se chci zeptat...}
{296}{}{Nemám dost penìz...moná jindy.}

# 10. TALK (7)
{320}{}{Jistì, proè by ne. Øíkáme tomu  "Kestingùv  speciál." }
{322}{}{Stojí jenom }
{323}{}{Jak tomu øíkáte?}
{325}{}{To zní dobøe, souhlasím.}
{326}{}{Moná jindy. Chci se ale zeptat...}

# 11. KESTING (10)
{335}{}{No...øíká se, e byl jednou jeden zamìstnanec slavné poèítaèové firmy, kterı si rád povídal
  ostatními. (Pokrèila rameny.) }
{336}{}{Shodou okolností, vydìlával jenom }
{1336}{}{ dolarù tıdnì.}
{337}{}{Shodou okolností, nemìl taky ádné peníze, take mluvení bylo jediné, co si mohl dovolit.}
{338}{}{Oh. Dobøe, jedno povídací sezení. Tady je }
{340}{}{Asi nic pro mì. Chci se ale zeptat...}

# 12. QUESTIONS (2, 4, 5, 6, 7, 8, 9, 10, 11, 13, 15, 18, 19, 20, 21, 23, 25, 28, 29, 30)
{350}{}{Ano?}
{351}{}{Dobrá, proè ne...}
{352}{}{Dobøe. (Usmívá se.) Ale odpovìdi budou nìco stát...}
{353}{}{Jistì, co vás zajímá?}
{354}{}{Nìkteré z vašich dívek prı ...navštìvují  Myrona.}
{355}{}{Jules mi øekl, e se tady mám poptat, kdybych dostal chu na nìjakou ...akci.}
{361}{}{No vlastnì, u musím jít.}

# 13. MENU (7)
{375}{}{No, je docela pravdìpodobné, e vaši ádost dokáeme vyøídit k vaší plné spokojenosti. Take vaše pøání...?}
{376}{}{Chci bıt obleèenı ve své kombinéze a všichni  mi musí øíkat Zakladateli, a já budu... zakládat."}
{377}{}{Chci bıt zajat zbìsilou mutantkou.}
{378}{}{Chci hrát roli  "Herka," mladého otroka uneseného z jeho vesnice bandou chlípnıch otrokáøek.}
{379}{}{Chci hrát roli  "Zeny,"  mladé otrokynì uneseného z jeho vesnice bandou chlípnıch otrokáøù.}
{380}{}{Chci bıt zajata vyspìlım šéf-mutantem.}
{381}{}{Nemáte nìjaké dìvèata, které vypadají jako Angela Bishopová? Potøebuju se trochu uklidnit.}
{382}{}{Nemáte nìjaké dìvèata, které vypadají jako paní Bishopová? Potøebuju se trochu uklidnit.}
{383}{}{Radši bych odpovìdi na pár otázek...}
{384}{}{Vlastnì nic. U musím jít.}

# 14. FRIEND LAID (4, 12)
{395}{}{Jistì. (Prohlíí si tvé spoleèníky.) Kterı z nich?}
{396}{}{Mohla byste se postarat o Lennyho? Myslím, e se ještì dìvèete ani nedotkl.}
{397}{}{Nemáte nìkoho, kdo by, uh, "zvládnul" Marcuse?}
{398}{}{Tady toho malého úchyláka Myrona.}
{399}{}{"Kostìnı Nos" by potøeboval trochu rozcvièit.}
{400}{}{Tady Cassidy. Myslím, e by se potøeboval trochu odreagovat.}
{401}{}{Vic. "Obchodník" Vic.}
{402}{}{Mohla by nìkterá z vašich dìvèat pøeèíst slovník Robotovi? Stimuluje to jeho mozková centra.}
{403}{}{Doc by potøeboval trochu "zahøát".}
{404}{}{Davin my mohl vyuít nìjaké nové zkušenosti.}
{405}{}{Miria si chce trochu zadivoèit.}
{406}{}{Vlastnì ádnı.}

# 15. FRIEND LAID 2 (4, 12, 14)
{420}{}{Tenhle? (Prohlíí si tvého spoleèníka.) Myslím, e to zvládneme... }
{421}{}{(Prohlíí si tvého spoleèníka.) Myslím, e to zvládneme... }
{422}{}{ dolarù.}
{423}{}{O peníze se nestarejte. Je to zdarma.}
{424}{}{Okay.}
{425}{}{S takovou cenou se nedá polemizovat. Dobøe.}
{426}{}{Moná pozdìji...chci se ještì na nìco zeptat.}
{427}{}{Hmmm. Moná jindy, a se moje finanèní situace trochu vylepší.}
{428}{}{Vlastnì, radìji ne. Nashle.}

# 16. CAT'S PAW (2, 12)
{440}{}{(Vypadá pøekvapenì.) Ukate. (Dívá se na magazíny.) No...vlastnì, slyšela jsem, e tu pøed válkou bylo   nakladatelství Koèièí Packa...vydávající pornografické materiály.}
{441}{}{Pornogru - porn-o-gra - pornu - uh, nakladatelství?}
{442}{}{Tohle místo bıvalo kniní nakladatelství?}

# 17. CAT'S PAW 2 (16)
{450}{}{Ano...místnosti se pouívaly pro fotografování modelek z celého svìta. (Vypadá, e ji magazín fascinuje.)
 Pìknı kousek historie.}
{451}{}{No, já si jenom ètu nìkteré èlánky. }
{452}{}{Aspoò e koneènì vím, co ta zatracená vìc je. Je pøíšernì irritující prozkoumávat to a dostávat poøád stejnou
 hlášku dokola. A mám takovı dojem, e ta hláška se bude objevovat  POØÁD, i kdy u je to identifikované.}

# 18. CAT'S PAW 2 (17)
{460}{}{Vlastnì...kdyby nìkdo sehnal celou sbírku...øeknìme deset èísel, koupila bych je za slušnou cenu.
 Byla by to dobrá reklama, kdybych je vystavila. Nemáte zájem?}
{461}{}{Kdy jich najdu TOLIK...ale chci se zeptat ještì na nìco jiného...}
{462}{}{Vlastnì jich mám deset u sebe.}
{463}{}{Jasnì. Kdy jich najdu tolik, urèitì se s nimi stavím.}

# 19. CAT'S PAW, SOLVED (2, 12, 18)
{470}{}{Vıbornì! Dám pìt stovek za celou sadu.}
{471}{}{Pìt set? Po takovém šíleném shánìní? Ani náhodou. Tisíc.}
{472}{}{To zní dobøe, tady jsou. Ale pozor na èíslo pìt...prostøední dvojstrana vypadá jako slepená nìjakım lepidlem èi co.}
{473}{}{Ne, asi si je nechám. Ale chci se ještì zeptat...}
{474}{}{Ne, radši si je nechám. Moná pozdìji.}

# 20. CAT'S PAW, SOLVED (19)
{480}{}{Hmmmmm. Sedm set padesát a ani o halíø víc.}
{481}{}{750? Tak dobøe. Jsou vaše.}
{482}{}{Tak to si je asi nechám...ale chci se ještì zeptat...}
{483}{}{Zapomeòte na to. Moná jindy.}

# 21. CAT'S PAW, SOLVED, 750 (20)
{490}{}{Tady jsou. (Odpoèítala peníze a podala ti je.) Ještì jednou díky.}
{491}{}{Chci se ještì zeptat...}
{492}{}{Není zaè. Nashledanou.}

# 22. CAT'S PAW, SOLVED 2 (19)
{500}{}{Vánì? (Prohlíí si èíslo pìt, potom si prohlíí ostatní èísla.) Hmmmm. No, vypadá to, e tohle èíslo je tu dvakrát,
 take si ho mùete nechat. Jenom odstraním tu skvrnu...}
{501}{}{Okay. Uh...mimochodem, ta skvrna není moje. Netuším, kde se tam vzala.}
{502}{}{Okay. Jste si jistá, e ji odtamtud dostanete? Je to slepené poøádnì.}

# 23. CAT'S PAW, SOLVED 3 (22)
{510}{}{To se stává dost èasto...(Sleèna Kitty se pustila do odstraòování skvrny.)...vìtšinou na prostìradlech.
 Tak a je to...hmm - je tady èlánek o energetickıch zbraních. Vemte si to.}
{511}{}{Chci se ještì na pár vìcí zeptat...}
{512}{}{Èlánek o energetickıch zbraních? Dík, asi si ho pozdìji pøeètu.}

# 24. ENCLAVE VICTORY SPEECH (WTG)
{520}{}{(Jakmile promluvíš, vylekanì zvedá hlavu a dívá se na tebe.) Ty! Jsi zpátky!...Myslela jsem, e je u po tobì. (Oddechla si.) Mìla jsem *takovı* strach. Riskovat ivot, porazit Enklávu...to je ta nejstateènìjší vìc, o které jsem kdy slyšela.}
{521}{}{(Jakmile promluvíš, vylekanì zvedá hlavu a dívá se na tebe.) Ty! Slyšela jsem o tobì! (Její tváø je plná obdivu k tobì.) Riskovat ivot, porazit Enklávu...to je ta nejstateènìjší vìc, o které jsem kdy slyšela.}
{522}{}{! Jsem ráda, e jsi zpìt. Hrdina jako ty dìlá s obchodem zázraky: riskuje vlastní ivot, poráí Enklávu... To je ta nejstateènìjší vìc, o které jsem kdy slyšela.}
{523}{}{Ále, sleèno Kitty. Na mım místì by to pøece udìlal kadej.}
{524}{}{Pøééésnì tak, bejby. A vo nièem odvánìjším u ani neuslyšíš, protoe já jsem THE BEST of BEST!}
{525}{}{Není nic, co by nedokázala nasraná enská, které unesli celou vesnici.}
{526}{}{A o nièem odvánìjším u ani neuslyšíš, protoe já jsem ta nejlepší v celé zatracené poušti.}
{527}{}{Díky. Jen dìlám svou práci jako hrdinka.}
{528}{}{Díky. Jen dìlám svou práci jako hrdina.}
{529}{}{Kopat záporákùm do prdelí je mùj dob.}

# 25. ENCLAVE VICTORY SPEECH (24)
{545}{}{Taková skromnost.}
{546}{}{Taková síla a sebedùvìra. }
{547}{}{Tohle na tobì miluju. V Koèièí Pacce máš dveøe vdy otevøené. A zadarmo.}
{548}{}{Take...co to rande, co jsme si kdysi dávno domlouvali?}
{549}{}{Take...co kdyby...víš, ty a já...no...však víš.}
{550}{}{Bejby, pojï ke mnì.}
{551}{}{Skvìlı! Hele, chci se nejdøív na nìco zeptat, ne se do toho vrhnu...}
{552}{}{Díky. To oceòuju, sleèno Kitty.}
{553}{}{Nic menšího ani neoèekávám. Pro svou zaslouenou odmìnu se stavím brzo.}

# 26. ENCLAVE VICTORY SPEECH (25)
{565}{}{Tak dobøe, }
{566}{}{...jenom si vezmu pláš.}
{567}{}{Není tøeba pospíchat. }
{568}{}{To je dobøe, e já mám svùj "pláš" tady v kapse.Heh-heh.}
{569}{}{Jasnì. Ale pospìš si...máme rezervace na osmou. V mojí postılce.}
{570}{}{Jasnì. Ale pospìš si...ty a mùj jazyk u máte rezervaci.}

# 27. MACHINE (25)
{575}{}{Oh, }
{576}{}{, ty divoké zvíøe...}
{577}{}{::Bwanbwan-bwan-ba-bwan oookwaka oookwaka::}

# 28. MYRON (12)
{585}{}{(Kıvla.) Ano, to je pravda. Musíme je pøipravovat pøímo pro nìj.}
{586}{}{Ráda bych ho potkala. Mohla bych se nabídnout jako další  "vıbìr?"}
{587}{}{Aha. Chci se ještì zeptat...}
{588}{}{Hmmmm. Díky za informace..}

# 29. EVALUATE (28)
{595}{}{(Prohlíí si tì, pak zakrouila prstem.) Otoète se. Hmmmm... }
{596}{}{ne, nemyslím, e byste vyhovovala. Moná kdybyste se dala trochu do poøádku...Sorry.}
{597}{}{ano... ano, myslím e budete vyhovovat. Máte zájem o práci? Všem mım dìvèatùm u se z nìj
dìlá špatnì.}
{598}{}{Jasnì.}
{599}{}{Hmmmph. Chtìla bych se zeptat...}
{600}{}{Ne, ale moná pozdìji. Chtìla bych se ještì zeptat...}

# 30. EVALUATE (29)
{610}{}{(Kıvla.) Skvìlé. Jeden z Mordinovıch muù by se mìl brzy objevit. Posaïte se, 
  pøedstavím vás jako jednu z mıch dìvèat.}
{611}{}{Dobrá...poèkám na nìj.}
{612}{}{No vlastnì, radìji ne. Chtìla bych se zeptat na nìco jiného...}
{613}{}{Radìji nic, rozmyslela jsem si to...Moná jindy.}

# 31. STRANGE REQUEST (4, 12, 13, 14)
{620}{}{(Prohlíí si tì od hlavy k patì, pak kıvne.) Myslím, e bychom pro tebe nìco našli... }
{621}{}{(Prohlíí si tvého spoleèníka od hlavy k patì, pak kıvne.) Myslím, e bychom pro tvého pøítele nìco našli... }
{623}{}{(Mrk.) Je to na úèet podniku, neotravuj s penìzi.}

# sex responses
{700}{}{Ou-jééé.}
{701}{}{Sqìlı...}
{702}{}{Wow. Tak hluboko, oh.}
{703}{}{Wow.}
{704}{}{*Fjù*}
# marcus
{705}{}{Doufám, e neotìhotní.}

{710}{}{Mluvil jsi hodiny. Dívky v  Koèièí Pacce mají neuvìøitelné schopnosti vcítit se do lidské povahy.}
{711}{}{Kápo Mordinu dorazil a vypadá, e jsi na nìj udìlal dojem. Vede tì na sever z mìsta,
 na místo, kterému øíká  "Stáje."}

# party applause
# general
{720}{}{*písk*}
{721}{}{*plesk plesk plesk*}
{722}{}{Pokraèuj!}
{723}{}{Fíha.}
# spouse
{730}{}{*smrk smrk smrk*}
{731}{}{Cítím se podvedená...}
# goris
{740}{}{*brr*}
# cyberdog
{750}{}{*Haùùùùù*}
# robobrain
{760}{}{*Bzzzt*}
# vic
{770}{}{Jedu, Šéfe! Tak dloohooo bez sexu...}

{800}{}{Donesl jsi magazíny sleènì Kitty.}
