#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
# 0. QUICK LOOK

# 0. LOOK
{150}{}{Vidíš mladého opáleného mue obleèeného v èerné kùi a øetìzech. Jeho tváø je poznamenaná jizvami po akné.}
{151}{}{Vidíš Malıho Jeíše Mordina.}
{152}{}{Vidíš Malıho Jeíše Mordina. Hraje si s jedním ze svıch noù.}

# 1. FLOAT [ENCLAVE DESTROYED] (WTG)
{200}{}{Jo! }
{201}{}{Do nich! }
{202}{}{::Mává na tebe::}
{203}{}{::Píská::}

# 2. FLOAT [POWER ARMOR] (WTG)
{220}{}{Jak sereš s tvou vìcí na sobì?}

# 3. FLOAT/CLICK [MADE MAN, SAME FAM, ARMED (WTG)
{230}{}{Hezkı elezo to máš, }

# 4. FLOAT/CLICK [MADE MAN, SAME FAMILY, SNEAK] (WTG)
{240}{}{Co se tu plazíš, co, }

# 5. FLOAT [MADE MAN: MORDINO] (WTG)
{250}{}{Jakje, }
{5250}{}{?}
{251}{}{Hééj... }
{252}{}{Kùùrva to je hic.}
{253}{}{Hej! Na co se chystáš, }
{254}{}{Tì vidím, }
{255}{}{Hej! Pojï se podívat na moji novou kudlu, }
{256}{}{Co za sraèky teï dìláš pro tatíka, }
{257}{}{Chystáme se vyrazit si, }
{258}{}{Mùj nù potøebuje trochu Bishopí krve...}
{259}{}{Rozpárám tolik Salvátorù, e mi zaènu øíkat "Øezník"...}

# 7. FLOAT [MADE MAN, NOT SAME FAMILY] (WTG)
{270}{}{Jo! Ty tam! Radši ocaï zmiz, hade!}
{271}{}{Máš teda vodvahu, smrdìt tady, }
{272}{}{Hijo de puta...}
{273}{}{Ty }
{274}{}{Jestli tady ještì budeš, a dopiju pívo, vyøeu ti svı jméno na ksicht.}
{275}{}{::Vıhrunì se na tebe dívá a pohazuje si s noem.::}
{276}{}{Hledáš tady snad nìco, }
{277}{}{Kurva, ty! Co tu chceš?}
{278}{}{Jo! Ty! Nebaví tì ivot?}
{279}{}{Sem myslel, e tì zavøeli do psí boudu.}
{280}{}{Jestli nejseš tady, aby mi vylízal prdel, }
{281}{}{Hija de puta...}

# 9. FLOAT/CLICK [MALE, ARMED, RESPECTFUL] (WTG)
{300}{}{Jo! Hombre, nemùeš tady pobíhat s tou vìci v paøátì.}
{301}{}{Jo! Hele, odlo to. Lidi sou pak nervózní.}

# 10. FLOAT/CLICK [FEMALE, ARMED, RESPECTFUL] (WTG)
{310}{}{Jo! Holèièko, nemùeš tady pobíhat s tou hraèkou v ruce.}
{311}{}{Jo! Holèièko, radši to schovej, lidi jsou nervózní.}

# 11. FLOAT/CLICK [MALE, SNEAK, PRIZEFIGHTER] (WTG)
{320}{}{Co se tu kurva plazíš, }

#12. FLOAT/CLICK [FEMALE, SNEAK, PRIZEFIGHTER] (WTG)
{330}{}{Proè se tady plííš, holèièko? S takovım pravım hákem, co máš, mùeš chodit pøímo a nemusíš se schovávat.}

# 13. FLOAT [MALE, PRIZEFIGHTER] (WTG)
{340}{}{Kde ses nauèil rvát, }
{341}{}{Máš odvahu jako Mordino.}
{342}{}{Ten poslední boj bylo teda nìco, hombre.}
{343}{}{Poletuje jako motılek, ale píchá jako vosa. Tím myslím tebe,, }
{344}{}{Víš, Mordinové by takovı svaly dokázali vyuít, }
{345}{}{Ta sázka na tebe, to byla jasná vıhra. Ty tvoje háky by zabily krávu.}
{346}{}{Vidìl jsem tì bojovat, }
{347}{}{Kolik zvedneš, }
{348}{}{Kde jsi posiloval, eh?}
{349}{}{Bacha na dímaèku. Chutnaj mu uši.}
{350}{}{Koupil bych ti drink, ale utratil jsem všecky prachy. Vsadil jsem na tvıho protivníka.}
{351}{}{Odkud seš, e se umíš tak prát? Seš fakt DOBREJ.}
{352}{}{Kde ses nauèila rvát, kotì? Jsi skvìlá!}
{353}{}{Ten poslední boj, to bylo nìco.}
{354}{}{Kde trénuješ?}

# 15. FLOAT/CLICK [ARMED, PORN STAR, FEMALE] (WTG)
{370}{}{Hej, hej, hej! Dìvèe, co kdybys to elezo schovala, hm?}
{371}{}{No tak, chceš abych ti to vzal a pak tì prohledal, kde ještì máš nìjaké zbranì? Schovej to, okej?}

# 16. FLOAT [MALE, SNEAK, PORN STAR] (WTG)

# 17. FLOAT/CLICK [SNEAK, PORN STAR, FEMALE] (WTG)
{390}{}{Mùeš se plazit jak chceš, ale s takovım tìlem mojí pozornosti neuteèeš, kotì.}

# 18. FLOAT [PORN STAR] (WTG)
{400}{}{Tvùj film nebyl špatnej, ale potøebuješ ještì trénovat. ::Smìje se::}
{401}{}{Hej, }
{402}{}{Jsem pøipravenej, jsem volnej, tak mì hoï do filmu, okej? Co ty na to, }
{403}{}{Jsem nejlepší milovník v okolí. }
{404}{}{Promluv si o mì s Bratry, }
{405}{}{Ztra za mì slovíèko u Bratrù, okej?}
{406}{}{Jo, dr se Mordinù, dìláš dobøe. My sme da best.}
{407}{}{Potøebuješ fet? Chlast? Všechno seenu a ani ne moc draho.}
{408}{}{Co kdybychom spolu natoèili film? Jsme nìnej, pravej latinskej milovník, kotì. Poznáš vìci, které jsi ještì nepoznala.}
{409}{}{Nechceš si vyrazit?}
{410}{}{Nemáš ádnı kámoše?}
{411}{}{Potøebuješ nìjakej Jet? Mùu tì zásobit, kotì.}
{412}{}{Ahoj, kotì! Co tak malou pusinku na èelíèko, hm?}

# 20. FLOAT/CLICK [ARMED, SLAVER] (WTG)
{425}{}{Nevytahuj tady to elezo, tady ho nepotøebuješ.}

# 21. FLOAT/CLICK [SNEAK, SLAVER] (WTG)
{435}{}{Nelez tady po zemi, otrokáøi. Jsi mezi kamarádama.}

# 22. FLOAT/CLICK [ARMED, NO REP] (WTG)
{445}{}{Jo! Seš blbej nebo co? Schovej tu vìc, nebo ti budu muset ublíit.}
{446}{}{Chceš lobotomii nebo jinak upravit kebuli? Schovej to!}
{447}{}{Hej, kotì! Seš blbá nebo co? Schovej tu vìc.}

# 24. FLOAT/CLICK [SNEAK, MALE, NO REP] (WTG)
{455}{}{Co se tady kurva plazíš? Chceš, aby tì nìkdo odprásknul nebo co?}

# 25. FLOAT/CLICK [SNEAK, FEMALE, NO REP] (WTG)
{460}{}{Co se tady plazíš, kotì? Chceš, aby tì nìkdo odprásknul nebo co?}

# 26. FLOAT/CLICK [COMPANION: ROBOBRAIN] (WTG)
{465}{}{Odjeï s tím odpadkáèem.}
{466}{}{ádní roboti. VYpadni.}
{467}{}{Ten robot skonèí ve šrotu, jestli tu bude ještì chvilku opruzovat.}

# 27. FLOAT/CLICK [COMPANION: MARCUS] (WTG)
{475}{}{VÌDÌL sem, e to je mutantí smrad. Vypadni s ním, nebo to blbì skonèí.}
{476}{}{Seš snad Mutantofil nebo co? Vyhoï ho nebo uvidíš.}
{477}{}{Jestli tady ten mutant bude ještì chvilku pochodovat, pocvièím se ve støelbì na ivej cíl.}

# 28. FLOAT/CLICK [COMPANION: LENNY] (WTG)
{485}{}{VÌDÌL jsem, e tu nìco hnije. Vypadni s tím ghoulem, nebo skonèí tam, kde patøí. V hrobì.}
{486}{}{Vypadni s tím smradlavım ghoulem. Hned.}
{487}{}{Jestli ten ghoul nezmizí do minuty, bude ještì mrtvìjší.}

# 29. IF KNIFE (WTG)
{495}{}{Hej ty. Pocem a uka mi ten nù.}
{496}{}{Hezká kudla.}
{497}{}{Mùeš mi na moment ukázat tu tvoji kudlu?}

# 30. INTRO (WTG)
{505}{}{Huh? }
{506}{}{Chceš nìco, amigo?}
{507}{}{Chceš nìco, kotì?}
{508}{}{Hù uh?}
{511}{}{Odejdi}
{512}{}{Kdo jsi??}
{513}{}{Sorry. Omyl.}

# 31. SECOND TIME, NORMAL (WTG)
{522}{}{Eh...? Zas ty? Co chceš teï?}
{523}{}{Héj...jak je, kámo? Potøebuješ nìco?}
{524}{}{Huh buh}
{525}{}{Aj-mí-go?}
{526}{}{Kóo-tì. Mòauuuu}
{529}{}{Chci se na nìco zeptat...}
{530}{}{Ale nic, promiò.}

# 32. PRIZEFITER (WTG)
{540}{}{}
{541}{}{}
{542}{}{Hej, hej, hej! Ty seš }
{544}{}{}
{547}{}{Díky, Malej Jeíši. Chci se tì zeptat ...}
{548}{}{Dík. Jen procházím, u musím jít.}
{549}{}{Jo, já vím kdo sem. Dej si na mì bacha.}

# 33. MADE MAN (SAME) (WTG)
{560}{}{Hééj, jak je, }
{562}{}{U tì vobsluhujou, nebo mám zavolat nìjakou osobu èíšnou?}
{563}{}{U tì vobsluhujou, nebo mám zavolat nìjakou servírku, co?}
{567}{}{Ne, dík. Hele, nemoh bys mi poradit s pár vìcma?}
{568}{}{No, dík. Èau.}

# 34. SLAVER (WTG)
{582}{}{Eh? Hledáš kšefty, otrokáøi? Máš nìjakı zboí na prodej?}
{583}{}{Já prodat prodat ja prodat ty!}
{586}{}{Jasnì. A ty kupuješ?}
{587}{}{Zrovna teï ne. Ale chci se tì na pár vìcí zeptat...}
{588}{}{Zrovna teï ne. Moná pozdìji.}

# 35. RETARD (30, 31, 32, 33, 34, 36, 63)
{600}{}{Heh. Dlouho na sluníèku, co? Fakt se z toho blbne.}
{601}{}{Eh...Jo. Dej si bacha, amigo. Èau.}
{602}{}{Eh...Jo. Dej si bacha, kotì. Èau.}
{603}{}{Heh. Bì se radši píct na sluníèko.}
{604}{}{Oukıı}

# 36. SECOND TIME (WTG)
{620}{}{Vypadni.}
{621}{}{Pøijï sem ještì jednou a cedník ti bude podobnej jako brácha, jasnı?}
{622}{}{::Vıhrunì si hraje s noem::}
{623}{}{::Plivnul ti pod nohy::}
{624}{}{Vypadáš jako nìkdo, kdo neví, e brzo chcípne.}
{625}{}{Odpal ne tì zlikviduju.}
{626}{}{Pøijï sem eštì jednou a uvidíš.}

# 37. QUESTION NODE (31, 32, 33, 34, 38, 39, 40, 41, 42, 43, 44, 45, 46, 48, 50, 51, 52, 54, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65)
{640}{}{(Èistí se nehty noem.) Otázky...KADEJ má otázky...}
{641}{}{(Èistí se nehty noem.) Jo?}
{642}{}{Chceš nìco?}
{643}{}{Coes to øíkal o rodinì Mordinù?}
{1643}{}{Kdo nebo co je to ta rodina Mordinù o kterı jsi mluvil?}
{644}{}{Hledám práci.}
{645}{}{Jak se mùe èlovìk pobavit v Novım Renu?}
{646}{}{Nevíš nìco o tom, jak se Richard Wright pøedávkoval Jetem?}
{647}{}{Mùeš mì nauèit zacházet s noem?}
{648}{}{Promiò, nic. Èau.}

# 38. WHO ARE JOU? (30, 31, 32, 33, 34, 36, 63, 64, 65)
{660}{}{Já? Kdy se musíš ptát...he. Jmenuju se Jeíš. Jeíš Mordino. Jako mùj tatík, akorát e on je VELKEJ Jeíš, hlava CELİ Mordinovy
 rodiny v Renu. Take mnì øíkají Malej Jeíš. Aby nebyl chaos, jasnı?}
{661}{}{Rodina Mordinù? Kdo je to?}
{662}{}{U jsem o vaší rodinì slyšel. Prı jste docela tvrïasi a je tøeba dávat si na vás bacha.}
{663}{}{Hledám práci. Nabírají Mordinové?}
{665}{}{Nevíš, kde by se dalo poøádnì pobavit?}
{666}{}{Aha. Hele, chci se zeptat...}

# 39. FAMILY MORDINO? WHO'S THAT? (37, 38)
{680}{}{My Mordinové budem brzo šéfovat Novımu Reno...a taky Reddingu. Uvidíš.}
{681}{}{Rodina MORDINÚ? Si bral moc Jetu, nebo ti nìkdo vytlouk mozek z kebule? Budem brzo šéfovat Novımu Reno...a taky Reddingu. Uvidíš.}
{682}{}{Rodina MORDINÚ? Si brala moc Jetu, nebo ti nìkdo vytlouk mozek z kebule? Budem brzo šéfovat Novımu Reno...a taky Reddingu. Uvidíš.}
{683}{}{To zní, jakoby nebyl špatnej nápad pøidat se k vám. Dalo by se to nìjak zaøídit?}
{684}{}{Co myslíš tím Reddingem?}
{685}{}{Redding? To je kde?}
{686}{}{Hmm, máte pøed sebou hezkou budoucnost, ale já se tì chci zeptat...}
{687}{}{Vy Mordinové kecáte ve velkım, ale jinak jste poøádní poserové. Co mi povíš na to, MALEJ Jeíši?}

# 40. REDDING? WHERE'S THAT? (39)
{700}{}{Na severozápadì, hombre. }
{701}{}{Na severozápadì, kotì. }
{702}{}{Vo nic nepøicházíš, jestli to tam neznáš. Akorát kupa horníkù, kteøí nejradši LÍTAJ, jestli mi rozumíš?}
{703}{}{Ani ne. Jak to myslíš?}
{704}{}{Banda feákù?}
{705}{}{Jo, jasnı. Hele, ještì pár otázek...}
{706}{}{Musím jít. Èau, Jeíši.}

# 41. WHAT DO JOU MEAN ABOUT REDDING? (39)
{720}{}{Banda horníkù, kteøí se hrabou v blátì, ale nejradši LÍTAJ, jestli mi rozumíš?}

# 42. NOT REALLY. WHAT DO JOU MEAN? (40, 41)
{740}{}{Vyhrabávaj zlato, ale to co MY jim dáváme, je lepší ne zlato, rozumíš? Dávají nám VŠECKO zlato,
 co vyhrabou za TROŠIÈKU Jetu a kadej je šastnej.}
{742}{}{Aha. Hele, ještì otázku...}

# 43. THEY'RE A BUNCHA DRUG ADDICTS? (40, 41, 42)
{760}{}{Jo, po první kapce Jetu. Staèí jenom jedna.}
{761}{}{Odkud je Jet?}
{762}{}{Aha. Hele, ještì otázku...}

# 44. WHERE DOES THE JET COME FROM? (43)
{780}{}{Jet? Ten je ODTUD. Hele, my nevyhrabáváme zlato, my DÌLÁME zlatou šávièku. Pro hodníky je to všecko.
 Vozíme to do Reddingu, oni si šlehnou, zalítaj a pošlou nám zpátky zlato. Primitivní.}
{781}{}{Jak dlouho to u dìláte? Pøipadá mi, e byste u šéfovali celé Kalifornii, kdyby byl Jet tak úèinnı a návykovı.}

# 45. HOW LONG HAS IT BEEN GOING ON? (44)
{800}{}{Jo, máš recht. Nemìli jsme Jet vdycky. Ale pak jsme narazili na toho kluka - hodil vokem na tu sraèku, 
 co jsme prodávali feákùm tenkrát a øek, e by dokázal udìlat 'lepší.' A udìlal. Teï  maká pro nás.}
{801}{}{Jakej kluk? Kde ho najdu?}

# 46. WHO IS THIS KID? (45)
{820}{}{Jmenuje se Myron. A co se tejká toho, KDE je, to u ty nepotøebuješ vìdìt.}
{821}{}{Jmenuje se Myron. Máme ho ve stájích, na sever od mìsta. Testuje novı drogy. Najít ho mùeš, ale nebude mít èas.
 Furt je zamìstatnej...buï s fetem nebo enskejma.}
{822}{}{Proè mi to stejnì neøekneš?}
{823}{}{Aha. Mám ještì další otázky...}
{824}{}{Myron jo? Dík, Jeíši. Èau.}

# 48. RELAX? (36, 37, 38)
{840}{}{Desperádo je plac, kterej hledáš. Máme Jet, hazard...a všecky kurvy kterı potøebuješ, nadrenı a povolnı.
 Úplnej ráj. RÁJ.}
{841}{}{Desperádo je plac, kterej hledáš, kotì. Máme Jet, hazard... U nemusíš hledat dál.}
{842}{}{Take...chceš si uít, kotì? He...tak co kdybychom si skáknuli ke mì do postılky na trošku lásky?}
{843}{}{Pokoušející, ale tak nìjak nemám tìch deset vteøin na tvou lásku, Jeíši. }
{844}{}{Oh. Dík za nabídku, ale teï ne. Chci se tì toti ještì zeptat...}
{846}{}{Hledám práci. Nevíš o nìèem?}
{847}{}{Dík za tip.}
{848}{}{Proè nezaèneš sám? Já musím jít.}

# 49. I AIN'T GOT 10 SECONDS FOR JOU RIGHT NOW . . . [BAD RESPONSE] (48, 52)
{860}{}{Eh? O èem to mlu --? (Pochopil.) Ty KURVO! Vydrím klidnì deset hodin, ty... Sbal se a vypadni, ne tì nasekám na takhle malı kousíèky!}
{861}{}{Eh? O èem to mlu --? (Pochopil.) Ty! Sbal se a vypadni,  ne se ti kudlou podepíšu na záda!}
{862}{}{Zkus to a uvidíme, MALEJ Jeíši.}
{863}{}{Zkus to, a já ti tak poøeu ksicht, e budeš vypadat jak dìtská skládaška.}
{864}{}{Klídek...to byla jenom srandièka.}
{865}{}{Klid. Chci se tì zeptat...}
{867}{}{Pohoda , klídek. Já jdu pryè.}

# 50. I AIN'T GOT 10 SECONDS FOR JOU RIGHT NOW . . . [GOOD RESPONSE] (48, 52)
{880}{}{Ha! Dobøe. Malej Jeíš si tì pohlídá a poèká, a tì zaène svìdit mezi nokama. Take, co ještì potøebuješ?}
{881}{}{Zaprvé: hlídej si sám sebe, MALEJ Jeíši. Radši si pùjdu uít do psí boudy, ne se dotknout toho tvojeho ksichtu.
U ti nìkdo øek, e vypadáš jak pizza?}
{882}{}{Hledám práci. Nevíš o nìèem?}
{883}{}{Mám ještì pár otázek...}
{884}{}{Vlastnì u musím jít. Mìj se, Jeíši.}

# 51. I'M LOOKING FOR A JOB . . . [GOOD RESPONSE] (37, 38, 39, 48)
{890}{}{(Prohlíí si tì a pøikyvuje.) Vdycky hledáme novou krev...hlavnì krev, která radši rozstøikuje cizí krev, rozumíš mi? Bì nahoru a promluv si s tátou. Øekni mu, e tì posílám já, a pak se uvidí.}
{891}{}{(Prohlíí si tì a vrtí hlavou.) Neberem enskı...a na pár vıjimek. Zkus si promluvit s tátou nahoøe, moná pro tebe bude nìco mít. Nezapomeò mu øíct, e tì posílám.}
{892}{}{Díky. Mám ještì pár otázek...}
{893}{}{Pùjdu za ním. Díky, Jeíši.}

# 52. I'M LOOKING FOR A JOB . . . [BAD RESPONSE] (37, 38, 39, 48)
{900}{}{Nevím, nevypadáš moc silnì...zkus to jinde.}
{901}{}{Néé...nic mì nenapadá. My nenabíráme a ostatní rodiny tì radši odstøelej. Smùla. }
{902}{}{Nee...o nièem nevím. Mùeš jít ven a zeptat se pasáka, moná ti dá vydìlat.}
{903}{}{MY nenabíráme, ale s takovım tìlem zkus Korsickı Bráchy vejš po ulici. (Zubí se.) Ale jestli chceš rychle vydìlat pár drobnejch,
mùj pokojík je o patro vejš...}
{904}{}{Dobøe. Mám ještì pár otázek...}
{905}{}{Uh,ne dík.  Chci se ještì zeptat...}
{906}{}{Radši ne, dík. Ale mám na tebe ještì pár otázek...}
{907}{}{Oh, vsadím se, e by to bylo RYCHLİ. Ne,dík.}
{908}{}{Tak nic. Stejnì dík.}
{909}{}{Ne dík. Já u pùjdu.}

# 53. CALM DOWN. I WAS JUST KIDDING (X)
{920}{}{A myslíš si, e se ti budu smát? (Plivnul ti na nohu.) Vypadni do prdele, ne tì rozpáøu.}
{921}{}{Zkus to a uvidíme...MALEJ Jeíši.}
{922}{}{Uklidni se...hele, chci se tì ještì zeptat...}
{923}{}{Jsu.}
{924}{}{Tys mi plivnul na nohu? Ty zmrde! Já tì nauèím, ty pojebané hovado!}

# 54. I WANNA DEAL WITH SLAVES (34)
{930}{}{Ne, já ne...jdi nahoru po schodech a promluv si s tátou.}
{931}{}{A ty jsi...?}
{932}{}{Dík. Ne pùjdu, odpovíš mi ještì na pár otázek?}
{933}{}{Díky.}

# 55. JOU'RE A REAL HUMANITARIAN/STANDARD BAD RESPONSE? (39, 46, 57, 62, 65)
{940}{}{JI DO PIÈE. Vypadni z našeho kasína, nebo ti uøíznu hlavu a naseru do krku.}
{942}{}{Nevyhrouj mi, Jeíši.}
{943}{}{Poèkej, Chci se ještì zeptat...}
{944}{}{Uklidni se, u jdu.}

# 56. WHAT ABOUT RICHARD? (36, 37, 38)
{950}{}{Ten sráè malej Wright? Ha! Zkoušíš mi to pøišít? Máš smùlu. Seru na to, e je ten malej kripl mrtvej, 
 ale nemám s tím NIC spoleènıho.}
{951}{}{Jo tak? Mordinové dodávají nejvíc Jetu v Novım Renu. A to vás dìlá hlavní podezøelé.}
{952}{}{Nevìøím ti. Myslím, e s to udìlal TY. Ty a zbytek Mordinovcù.}
{953}{}{Tak kdo by to podle tebe mohl bıt?}
{954}{}{Okej...hele, ještì jedna otázka...}
{955}{}{Tak dobøe. Jen se ptám.}

# 57. OH, YEAH? JOU'RE GONNA TAKE THE BLAME (56)
{965}{}{(Oèi se mu zúily.) Tak hele, já nemám NIC spoleènıho se smrtí toho malıho kluka. Nevím, cos slyšel,
  ale kdybych ho zabil já, byl by naøezanej na kousky, né vypálenej Jetem, JASNİ?}
{966}{}{JO? A co z toho. Né snad, e bychom to udìlali my. Ten malej sráè si toho vzal moc. Je mi to putna.
 A jestli starej Wright zaène dìlat dusno, pohøbíme ho vedle jeho feáckıho synka.}
{967}{}{Ty jsi opravdu lidumil, Jeíši.}
{968}{}{To je SKVÌLİ postoj, Jeíši.}
{969}{}{Víš kdo prodal Richardovi ten Jet?}
{970}{}{No, tak teï je mi to jasnı. Ještì pár otázek...}
{971}{}{Dík za informaci.}

# 58. ANY IDEA WHO MIGHT'VE SOLD IT TO HIM (56, 57)
{980}{}{Jo, Renesco..."Rakeák." Prodává tolik Jetu, e by tì moh vystøelit na mìsíc. Je na západní stranì, v území
 Salvátorù. Nemá rád Wrighty a jeho fet není ÈISTEJ, rozumíš?}
{981}{}{Nemùe bıt jedinı dıler v celém mìstì.}
{982}{}{Tak na západì,jo? Stavím se tam, ale nejdøív by mì zajímalo...}
{983}{}{Dík, prošetøím to. Èau, Jeíši.}

# 59. IS HE THE ONLY DEALER IN TOWN? (58)
{990}{}{Ne, sou i další, ale Renesco je ten, co to udìlal.}
{991}{}{Proè to øíkáš?}
{992}{}{Kdo jsou ti další dıleøi?}
{993}{}{Jo, tos u øíkal. Ještì otázku...}
{994}{}{Fajn, Jeíši. Dík za info.}

# 60. WHAT MAKES JOU SAY THAT? (59, 61)
{1000}{}{PROTOE je to napùl slepej hajzlík, sprostej jako prase. A protoe prodává FET ØEZANEJ bùhvíjakou sraèkou, proto, kurva.
 Bì si s ním pokecat a uvidíme, co ti øekne o tom klukovi. Pak uvìøíš.}
{1001}{}{Kteøí další dıleøi jsou ve mìstì?}
{1002}{}{Moná. Ale ještì mám otázku...}
{1003}{}{Tak fajn, Jeíši. Pùjdu si Reneska provìøit.}

# 61. WHAT OTHER DEALERS ARE THERE? (59, 60)
{1010}{}{Je tady Jules, na zaèátku mìsta, vìtšinou kšeftuje s turistama. Pak Poøezanej Jimmy J, nahoøe na Druhı Ulici u ringu...nemùeš
 ho minout, debila. Má poøezanej ksicht, jak jednou v noci poletoval na Jetu...tak poøezanej, e má ksicht jednu velkou jizvu.}
{1011}{}{Nìkdo mi øíkal, e ty taky prodáváš, Jeíši. Jak to e ses o sobì nezmínil?}
{1012}{}{Proè si myslíš, e to udìlal Renesco?}
{1013}{}{Zajímavı. Chci se ještì zeptat...}
{1014}{}{Renesco, Jules a Poøezanej Jimmy J. Jasnı. Dík za informace.}

# 62. HOW COME JOUR NAME AIN'T COME UP? (61)
{1020}{}{PROTOE, zmrde, já NEJSEM dıler. }
{1021}{}{PROTOE já NEJSEM dıler, DÌVKO. }
{1022}{}{Moná nìkdy Jet prodávám, ale já jsem Malej Jeíš MORDINO, ne nìjakej feák, kterej musí sehnat 
 deset dalších, aby mìl na vlastní dávku. Take JDI DO PIÈE.}
{1023}{}{Dej si bacha na hubu, Jeíši. Sereš mì.}
{1024}{}{Klídek, klídek. Já jen ze zvìdavosti. Mùeš mi ještì s nìèím poradit...}
{1025}{}{Tak fajn. Dík za informaci.}

# 63. GOT A KNIFE (WTG)
{1030}{}{(Malej Jeíš se dívá na nù v tvé ruce a vrtí hlavou.) }
{1031}{}{(Malej Jeíš se dívá na nù v tvé ruce a vrtí hlavou.) }
{1032}{}{*Pfff.* To ani nevíš, jak DRET kudlu, hombre? }
{1033}{}{*Pfff.* To ani nevíš, jak DRET kudlu, kotì? }
{1034}{}{Hele, takhle... (Upravuje tvoje drení.) Potøebuješ poradit.}
{1035}{}{(Podívej se na nù. Podívej se na ošklivého mue.Podívej se na nù.) Ty dotekl }
{1036}{}{Kagagùgù}
{1038}{}{Fakt? Mùeš mì to nauèit?}
{1040}{}{Vlastnì, mám pár otázek...}
{1041}{}{Moná jindy.}

# 64. CAN JOU TEACH ME? (37, 63)
{1050}{}{Hmmmmm...}
{1051}{}{Nevím, hombre. Víš, nemám moc èasu a kudly, to je UMÌNÍ, jasnı?}
{1052}{}{Nevím, kotì. Víš, nemám moc èasu a kudly, to je UMÌNÍ, jasnı?}
{1053}{}{Nevím, hombre. MONÁ bych v tvém pøípadì udìlal vıjimku, ale nemám moc èasu a kudly, to je UMÌNÍ, jasnı?}
{1054}{}{Dám ti kilo.}
{1055}{}{Dám ti dvì kila.}
{1056}{}{Moje milování je taky umìní. Nechceš navzájem pøedvést styly?}
{1058}{}{Vlastnì mám mpá otázek...}
{1059}{}{Tak moná nìkdy jindy...a budu mít pár drobnejch. Moná si to pak rozmyslíš.}
{1060}{}{Tak moná nìkdy jindy.}

# 65. CAN JOU TEACH ME? (63)
{1070}{}{Hmmmmm. Øekni dvì a dohodnuto.}
{1071}{}{Neé...Myslel jsem nìco JINİHO, víš? (Jeho oèi tì svlékají donaha. Olizuje si rty.)}
{1072}{}{Øekni mi, e tím myslíš dvì stovky. PROSÍM, øekni mi, e tím myslíš dvì stovky.}
{1073}{}{Oh, myslíš na sex? No tak myslí dál, protoe dál se nedostaneš.}
{1074}{}{Uh, okej. Do toho. Cokoli za schopnost píchat. Noem.}
{1075}{}{Dobøe. tady jsou prachy.}
{1076}{}{Radši nic. Mimochodem, kdo vlastnì jsi?}
{1077}{}{Zapomeò na to. Mám pár otázek...}
{1079}{}{Moná jindy. OPRAVDU musím jít.}

# 66. CAN JOU TEACH ME? (65)
{1090}{}{Hmmmm...dobøe, udìlám to. Myslím, e na to máš. Hele, nejdøív musíš...}
{1091}{}{Hmmmm...dobøe, udìlám to. Myslím, e na to máš. Hele, chytneš kudlui takhle a pak musíš...}
{1092}{}{(Smìje se. Úsmìv odhalil zhnilé trosky jeho zubù.) Fajn, fajn. Máš teï èas, kotì? Tak do toho...}
{1093}{}{Dobøe...}

# post-knife training
{2000}{}{Malej Jeíš ti ukázal pár trikù s noem. Jednoduchı, u to taky umíš.}
{2001}{}{Na úkor své dùstojnosti teï dokáeš dret nù v ruce lépe. A potøebuješ sprchu.}

# END LINES
{5200}{}{! Nakopat jim prdel!}
{5201}{}{, ukázals Enklávì zaè je toho loket.}
{5230}{}{.}
{5240}{}{? Mordinové chodìj hrdì.}
{5251}{}{! Que pasa?}
{5253}{}{?}
{5254}{}{. Kde se flákáš?}
{5255}{}{.}
{5256}{}{?}
{5257}{}{. Nepøidáš se?}
{5271}{}{. Tak radši zmiz, ne se ti to nevyplatí.}
{5273}{}{ Neser, nebo z tebe bude rádlo pro psy. Zmiz!}
{5276}{}{? Radši odpal.}
{5280}{}{, tak radši zmiz.}
{5320}{}{? S tím pravım hákem, co máš se mùeš naparovat jako páv.}
{5340}{}{? Seš skvìlej.}
{5343}{}{.}
{5344}{}{. Kdybys na nìkoho vybìh, hned uteèou.}
{5346}{}{. To byla vrada, né boj.}
{5347}{}{?}
{5380}{}{? No tak, choï normálnì.}
{5401}{}{! Que pasa? Domluvíš mi to u Bratrù, nebo ne?}
{5402}{}{!}
{5404}{}{...no tak. Já na to mám.}
{5542}{}{! Velkej bojovník. Brácho, seš DOBREJ!}
{5543}{}{! Princezna-Bojovnice! Seš dobrá, kotì!}
{5560}{}{? }
# these three are related
{6035}{}{NEDOTİKEJ }
{7035}{}{ JÁ}
{8035}{}{ NELÍBÍ}
