#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
# 0. QUICK LOOK

# 0. LOOK
{150}{}{Vidíš hladovì vypadajícího mue. Má divokı pohled a jeho tváø pohrıvá husté strništì.}
{151}{}{Vidíš Hezouna Lloyda.}
{152}{}{Vidíš Hezouna Lloyda. Prohlíí si tì.}

# 1. FLOAT DIALOGUES (WTG)
{200}{}{Musím vypadnout z mìsta...}

# 2. INTRODUCTIONS IN IGNORANCE (WTG)
{210}{}{Kdo seš? Co tu chceš?!}
{211}{}{Zas ty?! Co tady dìláš?!}
{212}{}{Nic drahouši}
{213}{}{Já }
{214}{}{Odejdi}
{215}{}{A co tady dole dìláš TY?}
{216}{}{Uklidni se, pøíteli, PAK si promluvíme. Všechno v poøádku?}
{217}{}{Ty jsi Lloyd? Hezoun Lloyd?}
{218}{}{Nic, jen se tak rozhlíím. Èau.}

# 3. NUTTIN' HONEY (2)
{225}{}{Fajn, vypadni ocaï. A nikomu neøíkej, es mì tu vidìl, jasnı?}
{226}{}{Já tady. A teï u ne}

# 4. ME X ME X ME X WHO U/WHO ARE YOU AND WHAT ARE YOU DOING DOWN HERE/CALM DOWN, FRIEND . . . (2, 28)
{230}{}{Po tom ti nic není... kámo. Nejlepší bude, kdy ocaï hned odejdeš a zapomeneš, e bychom se nìkdy vidìli.}

{231}{}{Ja zapomnìt ... uh ... zapomnìt co?}
{232}{}{Okı Dokı}
{233}{}{Nezajímá mì, co je podle tebe nejlepší..., kámo. Co máš za problém?}
{234}{}{Pøipadáš mi jako nìkdo, kdo má problémy. Moná by se daly vyøešit.}
{235}{}{Vypadáš jako nìkdo, kdo si cení soukromí. Pro nìkoho tak ukecaného, jak jsem já, je zapomínání dost drahá vìc.}

# 5. WHAT SEEMS TO BE THE PROBLEM HERE? [LLOYD NOT AFRAID] (4)
{245}{}{Problém? Problém stojí pøímo pøede mnou. }
{246}{}{U to nebudu opakovat, kámo. Odejdi!}
{247}{}{U to nebudu opakovat, zlatíèko. Odejdi!}
{248}{}{Ty mi *vyhrouješ"? DOBØE si to rozmysli, ne mi odpovíš.}

# 6. WHAT SEEMS TO BE THE PROBLEM HERE? [LLOYD AFRAID] (4)
{255}{}{Problém? ádnej problém, kámo, vùbec ádnej. Jenom hledám trochu soukromí.}
{256}{}{Problém? ádnej problém, zlatíèko, vùbec ádnej. Jenom hledám trochu soukromí.}
{257}{}{Problém? Ani ne. Jenom hledám trochu soukromí. Ale... bylo ode mì HRUBÉ odmítnout tak krásnou dámu.}
{258}{}{Já myslím, e MÁŠ problém. Víš, v tomhle soukromí je dost tìkı pro kohokoliv slyšet, co se tady dole dìje. Moná tì zkrátka zabiju, eh?}
{260}{}{Pro nìkoho tak ukecaného, jako jsem já, mùe bıt soukromí docela drahé.}
{261}{}{Tak dobøe.}
{262}{}{Máš, pravdu, bylo to HRUBÉ. Já jdu.}

# 7. YOU THREATENING ME? [BAD, LLOYD NOT AFRAID] (5)
{270}{}{(Oèi se mu zúily.) }
{271}{}{Jestli jsi sem pøišel hledat problémy, vyhráls jackpot, kámo. }
{272}{}{Jestli jsi sem pøišla hledat problémy, vyhrálas jackpot, zlatíèko. }
{273}{}{No, doufám...}
{274}{}{Chceš nìjakı problém? Tady máš prob --}

# 8. YOU THREATENING ME? [LLOYD SCARED SHITLESS] (5)
{283}{}{Uh...no, hele... Já nikomu nevyhrouju, a urèitì nehledám ádné problémy.}
{284}{}{Já myslím, e MÁŠ problém. Víš, v tomhle soukromí je dost tìkı pro kohokoliv slyšet, co se tady dole dìje. Moná tì zkrátka zabiju, eh?}
{285}{}{Vypadáš jako nìkdo, kdo má problémy, a já ti moná mùu pomoct. Co ty na to??}
{286}{}{Vypadáš jako nìkdo, kdo si cení soukromí. Pro nìkoho tak ukecaného, jak jsem já, je zapomínání dost drahá vìc.}
{287}{}{Tak dobøe.}

# 9. THREATEN TO KILL LLOYD... [LLOYD NEGOTIATES] (6, 8)
{295}{}{Hele... nemusíš takhle mluvit, to není nutnı. Moná bychom si mohl promluvit o nìèem JINÉM: jak moc mùe tvùj kámoš Lloyd pomoct tobì.}
{296}{}{Mám zájem, pokraèuj.}
{297}{}{Nezájem, mizím odtud.}
{298}{}{Zapomeò, Lloyde. Pøiprav se na smrt.}

# 10. THREATEN TO KILL LLOYD... [LLOYD FREAKS] (6, 8, 12)
{305}{}{(jeho tváø prudce zbledla. Polknul... pak se na tebe náhle vrhnul!)}
{306}{}{Zmrde-}

# 11. KEEP TALKING . . . (4, 5, 6, 8, 9)
{315}{}{Mám nìjakı prachy... moná by menší finanèní èástka urovnala spory mezi námi, co øíkáš?}
{316}{}{Fajn. Dej mi všechno co máš.}
{318}{}{Nech si svoje prachy, já odtud mizím.}

# 12. FINE. GIVE ME EVERTHING YOU GOT . . . (11)
{325}{}{Tak fajn, dobøe... (Sáhnul do kapsy, vytahuje pár drobnıch a podává ti je.) ... co takhle si vzít tyhle peníze, vylézt po schodech nahoru a dát si pár panákù na Lloyda, co ty na to?}
{326}{}{Ty jsi asi hluchej. VŠECHNO co máš.}
{327}{}{Okay. Dobrej nápad, ale nejdøív tì zabiju.}
{328}{}{Tak fajn. Já padám.}

# 13. I SAID, GIVE ME EVERTHING YOU GOT [LLOYD FRIGHTENED] (12)
{335}{}{Ale ne... to je všechno co mám. U fakt nemám nic víc, dal jsem ti všechno.}
{336}{}{Neser mì, Lloyde. Já VÍM, e máš víc; jsi moc práskanej hajzlík, urèitì sis nìkde nìco ulil. Poslední šance: kde je zbytek?}
{337}{}{Uvidíme, Lloyde. A prohledám tvoji hnusnou mrtvolu, urèitì najdu víc.}

# 14. DON'T FUCK WITH ME LLOYD . . . (4, 5, 6, 8, 13)
{345}{}{Já... øíkal jsem... no teï... vím, kde by se daly najít další prachy... nejsou moje, víš, a bude s nima spousta problémù, ale jestli je chceš...}
{346}{}{No, vìdìl bych, kde by se daly najít další prachy... nejsou moje, víš, a bude s nima spousta problémù, ale jestli je chceš...}
{347}{}{Mluv dál, a a je to zajímavı.}
{348}{}{Vlastnì, s tou šancí to byla jenom sranda, Lloyde. Stejnì tì zabiju.}
{349}{}{Ty tvoje posranı kecy mì u pøestaly zajímat. Jdu pryè.}

# 15. KEEP TALKING AND KEEP IT INTERESTING (14)
{355}{}{Tak dobøe... jsou na Golgotì, na jih od Rena, zakopané v jednom hrobì. Jenom já vím kde.}
{357}{}{Povídej.}
{358}{}{To jsou takovı kreténskı kecy... ale doprdele, zabiju tì Lloyde, u mì sereš.}
{359}{}{Oh, zapomeò na to. Já jdu pryè.}

# 16. TELL ME WHERE THE MONEY IS (15, 24, 25)
{365}{}{Otoè se na znaèku na Gogothském rozcestí, jdi na severozápad, dokud se nedostaneš ke tøetímu hrobu, pak jdi na severovıchod k prvnímu kùlu. Blízko je hrob, oznaèenı jako "Arch Stanton." Kopej tak dva metry a najdeš to.}
{366}{}{Podívat se ceduli, jít na severozápad pøes tøi hroby, jít na severovıchod k prvnímu kùlu, pak hledat "Arche Stantona"... fajn, pojïme, Lloyde. Snad si nemyslíš, e se budu rıpat v zemi, potøebuju kvalifikovaného kopáèe..}
{367}{}{Tak fajn, já jdu. Nìkde se zašij. (Nech Lloyda odejít.)}
{368}{}{To je všechno, co potøebuju vìdìt... zítra ráno tì do toho hrobu zahrabou, kámo}

# 17. SHOW ME WHERE THE MONEY IS (15, 16, 24, 25)
{375}{}{(Lloyd vypadá, jakoby chtìl nìco øíct, ale pak si to rozmyslel a pøikıvnul.) Tak dobøe, vypadá to, e nemám na vıbìr. Poj'dme.}
{376}{}{Mám pár vìci, o které se ještì musím postarat. Poèkej tady, jsem zpátky do hodiny. (Odejdi, schovej se venku a sleduj Lloyda.)}
{377}{}{Mám pár vìci, o které se ještì musím postarat. Poèkej tady, hned se vrátím.}
{378}{}{Jsem hned za tebou. Padej.}

# 18. YOU LOOK LIKE A MAN IN TROUBLE, AND I MIGHT BE ABLE TO HELP YOU. WHAT DO YOU SAY? (4, 5, 6, 8)
{385}{}{Hmmmmm. Neznám tì, kamaráde... ale docela se mi zamlouváš. Jmenuju se Lloyd. Nìkteøí mi øíkají Hezoun Lloyd, ale já si to nevymyslel.}
{386}{}{Hmmmmm. Neznám tì, srdíèko... ale docela se mi zamlouváš. Jmenuju se Lloyd. Nìkteøí mi øíkají Hezoun Lloyd, ale já si to nevymyslel.}
{387}{}{Hmmmmm. Nejsem takovı pitomec, abych odmítnul tak krásnou dámu. Jmenuju se Lloyd. Nìkteøí mi øíkají Hezoun Lloyd, ale já si to nevymyslel.}
{388}{}{Take, Hezoune, co udìláš s mou nabídkou?}

# 19. WHAT MISUNDERSTANDING? (36)
{395}{}{Rodina Salvatorù a já jsme mìli... menší nedorozumìní nad mım úspìchem u jednoho z jejich hracích stolù. Myslím, e jedinı zpùsob, jak to vyøešit, je dostat se tak daleko od Nového Rena, jak to jenom pùjde...}
{396}{}{Úspìch u hracího stolu, jo? Kolik jsi vyhrál, Lloyde?}
{397}{}{Jak ti mùu pomoct?}
{398}{}{Co z toho budu mít já?}
{399}{}{Nemyslím, e ti nìjak pomùu, Lloyde. Asi bude lepší, kdy na sebe zapomeneme a rozejdeme se. Èau.}

# 20. HOW CAN I HELP? (19)
{405}{}{Hmmmm...vypadáš dost tvrdì. Potøebuju bodygárda. Pomo mi z mìsta. Doveï mì na Gologthu na jih a já ti zaplatím za tvé problémy.}
{407}{}{Super. Pojïme. (Jdi za ním.)}

# 21. SUCCESS AT THEIR GAMBLING TABLES . . . ? (19, 20)
{415}{}{(Zblednul, ale pak se ovládnul.) Dost na to, aby byli šílení vzteky. Vìtšinu u jsem utratil na úplatcích, abych si udrel Salvátorovy øezníky od tìla, ne se mi podaøilo schovat tady. Mám strach ukazovat se ve mìstì...}
{416}{}{(Vypadá pøekvapenì, ale hned se ovládnul.) Dost na to, aby se rozzuøili. Vìtšinu u jsem utratil na úplatcích, abych si udrel Salvátorovy øezníky od tìla, ne se mi podaøilo schovat tady. Mám strach ukazovat se ve mìstì...}
{417}{}{Pomùu ti, ale chci polovinu penìz, které jsi vyhrál, Lloyde. A neopova se mì ošidit, to by se ti urèitì nevyplatilo.}
{418}{}{Dej mi polovièku toho, co jsi vyhrál, a já ti pomùu, Lloyde. Je to slušná cena za to, e tì z mìsta dostanu v jednom kuse.}
{419}{}{Fajn, pomùu ti. Padáme odtud. (Následuj ho.)}
{420}{}{Nemyslím, e ti mùu pomoct, Lloyde. Èau.}

# 22. GIVE ME HALF (21)
{425}{}{(Chvíli se tváøil, jako by chtìl nìco øíct, ale pak si to rozmyslel a pøikıvnul.) Asi nemám na vıbìr. Pojïme.}
{427}{}{Ne, poèkej tady, ne se vrátím. Musím si ještì nìco zaøídit, za chvíli budu tady.}

# 23. YOU LLOYD? PRETTY BOY LLOYD? (2, 4)
{435}{}{(Ztuhnul.) Moná. Kdo jsi? Urèitì jsem ještì nemìl to potìšení...?}
{436}{}{(Ztuhnul, potom zvednul oboèí.) Moná. Jsem si jistı, e bych si tì pamatoval, sleèno. Urèitì jsem ještì nemìl to potìšení...?}
{437}{}{Vyser se na kecy, Lloyde. Jsem tady pro peníze, které jsi ukradnul panu Salvátorovi.}
{438}{}{Hele, Lloyde, dej sem peníze a já MONÁ nìjakou dobu zapomenu øíct panu Salvátorovi, e se schováváš tady.}
{439}{}{Lloyde, pan Salvatore mì poslal pro své peníze. Jo, a øíkal nìco jako "udìlej z nìj názornı pøíklad, jak dopadnou ti, co chtìjí vyjebat se Salvátorem". Ale moná by to šlo zaøídit i jinak... JESTLI se my dva dohodneme..}

# 24. DISPENSE WITH THE BULLSHIT (23, 28, 29, 31, 32, 33)
{445}{}{Dobøe... dobøe... (Polknul.) Jsou na Golgotì na jih od Rena, zahrabané v jednom hrobì. Jenom já vím kde.}
{446}{}{Ukáeš mi to.}
{448}{}{To jsou takovı kreténskı kecy... ale doprdele, zabiju tì, Lloyde, a pak si ty peníze nìjak najdu.}

# 25. I MIGHT FORGET I EVER SAW YOU . . . (23)
{455}{}{Hmmmmmm. Myslím, e tomu nevìøí ani jeden z nás... (Polknul.) Ale moná ti mùu vìøit.  Peníze jsou zahrabané v jednom hrobì na Golgotì, na jih od Rena. Ale jenom já vím kde.}
{459}{}{Oh, zapomeò na to. Já jdu pryè. Nech si ty svoje prachy a pitomı tajemství a zmiz mi z oèí.}

# 26. ARRANGEMENT . . . (23, 29, 31)
{465}{}{Hmmmm. Dohodneme øíkáš... dobøe, dobøe... co chceš?}
{466}{}{Dostanu tì z mìsta za polovinu penìz od Salvátora, Lloyde.}
{467}{}{Dostanu tì z mìsta za peníze, které jsi vyhrál od Salvátora, Lloyde.}
{468}{}{Kašli na to. Nechci nic - vypadni odtud, ne si to rozmyslím. (Pøedstírej odchod, schovej se a sleduj ho.)}
{469}{}{Kašli na to. Nechci nic - vypadni odtud, ne si to rozmyslím. }

# 27. THE DEAL (26)
{475}{}{No... hmmmm... asi nemám na vıbìr. Vezmu tì k penìzùm. Pojïme.}
{476}{}{Musím si ještì nìco vyøídit. Poèkej tady, do hodiny jsem tu. (Pøedstírej odchod, schovej se a sleduj ho.)}
{477}{}{Musím si ještì nìco vyøídit. Poèkej tady, za chvíli jsem tu.}
{478}{}{Jsem pøímo za tebou. (Jdi za ním)}

# 35. I'M HERE TO SHOW YOU OUTTA TOWN (WTG)
{555}{}{(Vyskoèil.) Jdeme?}
{556}{}{Ano, pojï.}
{557}{}{Ne, musím si ještì nìco vyøídit. Poèkej, za chvíli jsem tu.}

# 36. YOU LOOK LIKE A MAN IN TROUBLE, AND I MIGHT BE ABLE TO HELP YOU. WHAT DO YOU SAY? (18)
{565}{}{A co se tıèe tvé nabídky, MOHL bych vyuít nìjakou pomoc. Víš, potøebuju se dostat z mìsta, ale vzniklo tady jisté... nedorozumìní...}
{566}{}{Jaké nedorozumìní?}

# 101. FLOAT (WTG)
{585}{}{Èas vypadnout z Rena...}
{586}{}{Zatracená bedna...}
{587}{}{Je tìší, ne si pamatuju...}

# 102. FLOAT (WTG)
{595}{}{Tak jsme tady...}
{596}{}{Je to tady tenhleten.}

# 103. HERE'S THE GRAVE (WTG)
{605}{}{A jsme tady... *uff*... peníze jsou... v tomhle hrobì.}
{606}{}{Vykopej je, Lloyde.}
{607}{}{Pus mì, a se podívám...}
{609}{}{Tak uhni, já je vyhrabu...}
{610}{}{Vypadni, Lloyde. Ty peníze jsou moje.}

# 104. DIG IT UP, LLOYD (103)
{615}{}{Kdy... u jsi mùj bodyguard, byl bych rád... kdy je vyhrabeš ty.}
{616}{}{Uh...}
{617}{}{Na tomhle svìtì jsou dva druhy lidí, Lloyde. Ti s nabitou puškou a ti, co hrabou.}
{620}{}{Tak dobøe, udìlám to...}

# 105. DIG IT UP, LLOYD (104, 109)
{625}{}{(Lloyd si nìco mumlá pod nosem a zaèíná hrabat.)}
{626}{}{(Lloyd si nìco mumlá pod nosem a zaèíná hrabat... opatrnì. Ani ne o minutu pozdìji, vytahuje z hlíny velkou minu a dává jí na bok.)}
{627}{}{Tak tááákle. Jde ti to skvìle, kopej dál. A rychleji.}
{628}{}{Hezkı, Lloyde. Hrabej DÁL. Uvidíme, co ještì vytáhneš.}

# 106. LLOYD KEEPS DIGGING (105, 108)
{635}{}{(O pùl hodiny pozdìji Lloyd vyhrabal dost hlíny, aby odkryl malı poklop.
 Lloyd se zhluboka nadechnul a otøel si zpocené èelo.) Starı...protispadovı...kryt.}
{636}{}{(O pùl hodiny je hlína odhrabaná a vidíš malı prùlez. Jakmile se narovnáš, Lloyd zaèíná mluvit.) To je starı protiatomovı kryt. Našel jsem ho náhodou minulı tıden.}
{637}{}{Fajn, tak já to otevøu, a se nezdrujeme.}
{638}{}{Otevøi to, Lloyde.}

# 107. EXAMINE THE GRAVE (103, 104)
{645}{}{(Hlína kolem hrobu vypadá, jako by tady nìkdo pøednedávnem hrabal. Vzdálenost, kterou od tebe Lloyd udruje, tì pøivedla k nepøíjemné myšlence. Není tam past?)}
{646}{}{Myslím, e bys mìl zaèít hrabat, Lloyde.}
{647}{}{Hmmmm. Nejdøív se chci na nìco podívat...}
{648}{}{Uhni, Lloyde. Jdu kopat.}

# 108. EXAMINE THE GRAVE (103, 104)
{655}{}{(Hlína kolem hrobu vypadá, jako by tady nìkdo pøednedávnem hrabal. Pochopitelnì, jestli tady Lloyd zahrabával peníze.)}

# 109. LOOK FOR TRAPS (107)
{665}{}{(Prohlídka hrobu byl dobrı nápad. Pod tenkou vrstvou hlíny leela velká mina. Vyuíváš své pyrotechnické schopnosti a za chvíli je mina v tvém batohu.)}
{666}{}{Nezapomnìl jsi náhodou na tohle, Lloyde? No, na tohle u NEZAPOMENEŠ, ty mrtvolo.}
{667}{}{Myslím, e bys mìl hrabat TY, Lloyde. Hned.}
{668}{}{Necháme to tak, Lloyde... pro tentokrát. A teï uhni, a mùu kopat.}

# 110. MANHOLE COVER (106)
{675}{}{(Poklop se otvírá s ostrım skøípáním. Pod ním je temná díra, vedoucí dolù.)}
{676}{}{Tak lez, Lloyde.}
{677}{}{Uhni, Lloyde. Jdu dovnitø.}

# 111. MANHOLE COVER, LLOYD FIRST (110)
{685}{}{(Lloyd se zamraèil, ale jakıkoli komentáø si rozmyslel. Šplhá dolù.)}
{686}{}{Makej, Lloyde.}
{687}{}{HEJ, LLOYDE, CHYTEJ! (Hoï mu minu dolù.)}
{688}{}{Jdu hned za tebou, Lloyde.}

# 112. WAIT . . . (111)
{695}{}{(Slyšíš Lloydovo mumlání.) Vydr... u to skoro mám... (Je slyšet zaskøípání kovu, potom je ticho.)}
{696}{}{Pohni sebou, Lloyde, nemáme celı den.}
{698}{}{Jdu dolù, Lloyde.}

# 113. MANHOLE COVER (111, 112)
{706}{}{...}

# 114. LLOYD, TAKE OFF (103, 107, 108, 109)
{715}{}{Fajn, fajn... je to tvoje. bez problémù. Já jdu. (Otáèí se a odchází pryè.}
{716}{}{(Nech ho jít.)}
{717}{}{(Støel ho do zad.)}

# GOLGOTHA ENTRANCE MESSAGE
{1000}{}{Po dlouhé cestì jste dorazili na Golgothu. Lloyd tì vede k jednomu z hrobù.}
{1001}{}{Sleduješ Lloyda na Golgothu. Hrabe v jednom hrobì.}
{1002}{}{Venku jsi Lloyda ztratil.}
{1050}{}{Nechal jsi Lloyda jít.}

# END LINES
{5213}{}{ Já }
{7213}{}{Kdo ty}