#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
# 0. QUICK LOOK
{100}{}{Vidíš Masona.}

# 0. LOOK
{150}{}{Vidíš velkého, nabouchaného mue støedních let s øídnoucími vlasy.}
{151}{}{Vidíš Masona. Prohlíí si tì.}

# 1. FLOAT (WTG)
{200}{}{Co tady chceš?}

# 2. FLOAT: PLAYER IS TRAVELING WITH COMPANIONS (WTG)
{205}{}{Podívejte se na tu bandu kreténù.}

# 3. FLOAT: PLAYER TOUCHES DOOR, PERMISSION = FALSE (WTG)
{210}{}{Dotkni se tìch dveøí ještì jednou a budeš plápolat jako pochodeò..}

# 4. FLOAT/CLICK: PERMISSION = TRUE (WTG)
{215}{}{Mùeš vejit...TENTOKRÁT.}

# 5. INTRO (WTG)
{220}{}{Lezeš na špatnı místo. Zmiz.}
{221}{}{Tohle není porno studio. Zmiz.}
{222}{}{Co tu chceš? Dostals do hlavy pìstí v boxerskım ringu nebo co? Ztra se.}
{223}{}{Zchytøi}
{224}{}{Oog}
{225}{}{Odejdi}
{226}{}{Co je za tìmi dveømi?}
{227}{}{Chci vidìt pana Salvatora.}
{228}{}{Mùu se zeptat, odkud máte ty lejzrovou pistole?}
{229}{}{Øíká se, e vy Salvátorové jste otrávili malého Richarda Wrighta. }
{230}{}{Fajn fajn, u jdu.}

# 6. GET SMART (5)
{240}{}{Vypal, postiáku. Nebudu to opakovat.}
{241}{}{COE to?}

# 7. I WANT TO SEE MR. SALVATORE (5, 11)
{250}{}{ivot je plnı zklamání. A teï VYPADNI, kapišto?}
{251}{}{(Sarkasticky.) Za dveømi? Za tìmito dveømi? No, to je pokoj pana SALVATORA. A teï vypadni.}
{252}{}{Chci se setkat s panem Salvatorem. Hledám práci.}
{253}{}{HELE ty debile...chceš mít zítra ráno ještì práci? Mám nìjaké informace o jiné rodinì,
 které urèitì chce pan Salvatore slyšet.  A teï mì k nìmu pus. HNED.}
{254}{}{Odkud máte ty lejzrové pistole?}

# 8. LOOK, DIPSHIT . . . (FAILED) (7)
{265}{}{}
{266}{}{Chlapeèku, ty musíš byt BLBİ JAKO PRASE, e se mnou takhle mluvíš. Jedinı slovo, JEDINİ slovo a budeš plápolat jako táborák, hajzle.}
{267}{}{Holèièko,  ty musíš byt BLBİ JAKO PRASE, e se mnou takhle mluvíš. Jedinı slovo, JEDINİ slovo a budeš plápolat jako táborák, dìvko.}
{268}{}{CHCI VIDÌT pana Salvatora. Jsi hluchı?}
{270}{}{(Dr hubu a rychle zmiz, ne splní svoji hrozbu.)}

# 9. LOOK, DIPSHIT . . . (SUCCEEDS) (7)
{275}{}{(Jeho tváø zrudla. Najednou zaèal mluvit do vzduchu.) Promiòte, pane Salvatore, tady je Mason. }
{276}{}{Tento...mu...øíká, e ví nìco, co byste mìl slyšet.}
{277}{}{Tento...ena...øíká, e ví nìco, co byste mìl slyšet.}
{278}{}{(Èekej...)}
{279}{}{(Zaútoè na Masona, ne mùe pokraèovat.)}

# 10. I WANT TO SEE MR. SALVATORE. I WANT A JOB. (7)
{285}{}{MONÁ JE TADY NÌKDO HLUCHEJ, ale tohle je místo pana Salvatora. A MOJE práce je zajistit,
 e šéfa neobtìujou prasata jako ty. A teï utíkej zpátky k té své bandì divochù a upeè si matku k veèeøi.}

# 11. WHERE DO YOU GET THOSE LASER PISTOLS? (5, 7, 10)
{295}{}{Tyhle pistole? Hm hm, sakra, no já asi zapomnìl. (Zamraèil se.) Hele. Jestli nezmizíš, ne napoèítám do tøí,
 budeš plápolat jako táborák, na kterım ti maminka opékala sestøièku. VYPADNI.}
{298}{}{Ok! U jdu, u jdu.}
{299}{}{Potichu odejdi.}

# 12. FINAL STRAW (6, 8)
{305}{}{VAROVAL jsem tì, kreténe a teï... (Mason se náhle zarazil a poslouchá nìco, co neslyšíš. Za chvíli zaskøípal zuby).
 Pan Salvatore øíká, e mùeš vejít... }
{1305}{}{.}
{306}{}{Oh, pùjdu hned. Hned, co tì zabiju.}
{307}{}{Díky, èùráku. Nezapomenu se panu Salvátorovi zmínit o tvém vybraném vychování.}
{308}{}{Tak dobøe.}

# 13. WARNING ABOUT MR. SALVATORE BEFORE GOING IN (56)
{315}{}{(Mason tì zastavil.) Hele... (Naklonil se k tobì a ztišil hlas.) ...nejdøív pravidla, chlapeèku. }
{316}{}{(Mason tì zastavil.) Hele... (Naklonil se k tobì a ztišil hlas.) ...nejdøív pravidla, holèièko. }
{317}{}{Neplıtvej èasem pana Salvatora, a nesna se mu nakecat nìjaké sraèky, jinak si to zodpovíš. Jasnı?!}
{318}{}{Rozumím.}
{319}{}{Jó, jó. Uhni.}

# 14. WARNING ABOUT MR. SALVATORE BEFORE GOING IN (13)
{325}{}{(Mason tì znovu zastavil.) JEŠTÌ jsem neskonèil. Pøedvedeš mu RESPEKT. Budeš ho 
oslovovat *Pane Salvatore*, a kdy bude mluvit, budeš *dret hubu a poslouchat.* Jasnı?}
{327}{}{Poslední šance, Masone. Uhni mi do prdele z cesty.}

# 15. WARNING ABOUT MR. SALVATORE BEFORE GOING IN (14)
{335}{}{Jednou si my dva popovídáme na téma tvého problému s autoritou.}
{336}{}{JÁ problém nemám. Všechno je v pohodì.}
{337}{}{Vyli mi prdel.}

# 16. PATIENCE = 0 (5, 7, 10, 13, 14, 15, 17, 18, 19, 20, 21, 22, 27, 30, 34, 35, 36, 42, 53, 56, 57, 58, 59)
{345}{}{Fajn. Tak u DOST, ty kriple. (Protáhnul si klouby.)...a teï tì to bude bolet.}
{346}{}{Balet? Jakı Balet?}
{347}{}{Tak pojï. Zatancujeme si.}
{348}{}{Ne, TEBE to bude BOLET! SLYŠÍŠ, MASONE?! TEBE TO BUDE BOL--}

# 17. MISSION ONE LLOYD = MASON (WTG)
{355}{}{'e ses ukázal, chlapèe. }
{356}{}{'e ses ukázala, holèièko. }
{357}{}{'Koneènì. Nevím, proè pan Salvatore najímá pornoherce, ale ptát se ho nebudu. }
{358}{}{Ten blb co ukradl peníze panu Salvátorovi, jmenuje se Lloyd. Pan Salvatore ho chce mrtvého a peníze zpátky.
 A to udìláš, ohlásíš se MNÌ, jasnı? Dokáeš to?}
{359}{}{Kde najdu toho Lloyda?}
{360}{}{Jak ten Lloyd vypadá?}
{361}{}{Kolik ukradl?}
{362}{}{Proè nehledáš Lloyda TY?}
{364}{}{Jasan. Díky, Masone.}
{365}{}{Zvládnu to. A teï uhni, a mùu pracovat.}
{366}{}{"Lloydùv problém" u je vyøešenı.}

# 18. QUESTION NODE? (19, 20, 21, 22, 23, 24, 25, 26)
{375}{}{Jo? Jako co?}
{381}{}{To všechno, co potøebuju vìdìt. Dík, Masone.}
{382}{}{To všechno, co potøebuju vìdìt. A teï uhni, a mùu pracovat, Masone.}

# 19. WHERE CAN I FIND LLOYD? (17, 18)
{390}{}{Nìkde zalezl, take najít ho je TVOJE práce, chlapèe.}
{391}{}{Nìkde zalezl, take najít ho je TVOJE práce, holèièko.}
{392}{}{Zkus bary kolem Panenskı ulice. Moná se tam zašívá.}
{393}{}{Mám ještì pár otázek...}

# 20. WHAT DOES LLOYD LOOK LIKE? (17, 18)
{400}{}{Lloyd? Sakra...prùmìrná vıška, svìtle hnìdé vlasy. Kdy jsem ho vidìl naposled, mìl na sobì lutohnìdou košili
 a tmavı šátek. Nejspíš ještì nemìl monost pøevlíknout se.}
{401}{}{Víš, to popisuje SPOUSTU lidí, které mùu potkat kdekoli.}

# 21. SIMILAR MODELS (20)
{410}{}{Ha! Mì to povídej. Dneska lidi rozpoznáš tak akorát podle jména. Èlovìk by øekl, e je na svìtì tak deset druhù lidí.
 Podle mì to vypadá, jakoby byl nìkdy v minulosti nìjakı prùser s klonováním.}

# 22. HOW MUCH DID HE STEAL? (17, 18)
{420}{}{Kolem litru. Necelá tisícovka. Podívej, pro pana Salvatora, to není nic, ale jde o princip jednání s lidmi, kteøí
 mu COKOLI vezmou bez dovolení. na tvém místì bych si zapamatoval, e pan Salvatore's chce zpátky KADİ haléø.}

# 23. WHY AREN'T YOU TRACKING DOWN LLOYD? (17, 18)
{430}{}{Mìl jsem oèi otevøené, ale Lloyd je zatracenì opatrnı a drí se z dohledu...Salvatorskıch
 oèi, alespoò. Proto tì asi boss najal, málokdo tì ve mìstì zná.}
{431}{}{Jó. Já miz --}
{432}{}{Ještì mám pár otá--}
{433}{}{Fajn, tak já--}

# 24. CHILL. I WAS JUST CURIOUS. (57)
{440}{}{Tak dobøe.}
{442}{}{To je vše co chci vìdìt. Teï uhni, a mùu jít pracovat. }

# 26. YOU FOUND LLOYD? (WTG)
{465}{}{U se  Lloyd objevil?}
{466}{}{(Mraèí se.) Doufám, e máš pro mì nìjaké DOBRÉ zprávy. Máš Lloyda?}
{467}{}{(Mraèí se.) Doufám, e máš pro pana Salvatora nìjaké DOBRÉ zprávy, nebo budeš rát hlínu.}
{468}{}{Ne, ještì ne. Mám ještì nìjaké otázky k Lloydovi...}
{470}{}{Jo, u se objevil.}
{472}{}{Ne, myslím, e utekl z mìsta i s penìzi.}
{473}{}{Ještì ne. Sorry e otravuju.}

# 27. LAST TIME (18, 19, 20, 21, 22, 24, 25, 26, 57)
{480}{}{Momentík. Je ti doufám JASNİ: Opova se otravovat, dokud nenajdeš Lloyda, nebo se opravdu naseru. A teï makej.}
{481}{}{Dobøe, dobøe...}
{482}{}{Dej mi pokoj, Masone...}

# 28. LAST TIME (26)
{490}{}{ØÍKAL jsem ti, pøijï ,a najdeš Lloyda.  (uká si na èelo.) Debil, nebo co?! Urèitì, protoe 
 tady stojíš a mluvíš se mnou. Dobrej debil, MRTVEJ debil.}
{491}{}{Tak pojï, ty sráèi.}
{492}{}{Tak pojï.}
{493}{}{Ne, TY SEŠ MRTVEJ DEBIL! SLYŠÍŠ, MASONE?! TY SEŠ MRT --}

# 29. NO, HE LEFT TOWN WITH THE CASH (26)
{500}{}{(Nevìøícnì na tebe zírá.) Dali jsme ti jednoduchou práci. A ty to tak zdupeš.}
{501}{}{Ty jsi asi NEJBLBÌJŠÍ zkurvysyn na tomhle svìtì.}
{502}{}{Ty jsi asi NEJBLBÌJŠÍ kurva na tomhle svìtì.}
{503}{}{(Odfrknul si a sahá po zbrani.) Èas chcípnout.}
{506}{}{Ne, TY seš ten, kdo CHCÍPNE! SLYŠÍŠ, MASONE?! TY CHCÍPNEŠ TY  --}

# 30. SUCCESS (26)
{514}{}{Fajn, tak proès to neøek hned, blbe? Bì to oznámit panu Salvátorovi.}
{515}{}{(Kıvnul.) Dobøe.  Bì to oznámit panu Salvátorovi.}
{516}{}{Jo TAK? Tohle jsme mìl udìlat? Díky, Masone. Bez tebe bych si asi sral do plínek. Blbe.}
{517}{}{Dobøe.}

# 31. FLOAT MESSAGE: DONE JOB? (WTG)
{520}{}{U je to hotovı?}

# 32. FLOAT MESSAGE: GO SEE THE BOSS (WTG)
{525}{}{Bì za panem  Salvatorem. Èeká na tebe.}

# 33. TRIBUTE = MASON (WTG)
{530}{}{Fajn. Bude z tebe vıbìrèí daní. Bì do Reneskovy Apatyky na Obchodní Ulici, vyber poplatek, 1000 dolarù,
 a pak se vra sem.}
{531}{}{Dobøe. Ještì nìco?}

# 34. RETURN FROM RENESCO (WTG)
{535}{}{U máš ten poplatek?}
{536}{}{(Mraèí se.) U máš ten poplatek?}
{537}{}{(Mraèí se.) U DOUFÁM máš ten poplatek, blbe? Pan Salvatore èeká.}
{539}{}{Odkud jsem to mìl vybrat?}
{540}{}{Renesco mi valí klíny do hlavy. Tvrdí, e platil pøed dvìmi tıdny a e by nemìl platit celı mìsíc.}
{542}{}{Uh...jasnı. Tady jsou prachy.}
{543}{}{Jó, ale nemám peníze u sebe...}
{544}{}{Skoro. Pøíštì to budu mít, Masone.}
{546}{}{Mám tvùj poplatek pøímo tady...mrtvolo.}

# 35. RENESCO'S? (34)
{555}{}{*Reneskova Apatyka.* Na západì. 1000. A PADEJ.}
{556}{}{To je všechno, co potøebuju. Uhni mi z cesty. Masone.}

# 36. WARNING (34, 35, 38, 39, 59)
{565}{}{Momentík. Je ti doufám JASNİ: Opova se otravovat, dokud nevybereš poplatek, nebo se opravdu naseru. A teï makej.}

# 37. LAST TIME (34)
{575}{}{ØÍKAL jsem ti, pøijï ,a vybereš poplatek.  (uká si na èelo.) Debil, nebo co?! Urèitì, protoe 
 tady stojíš a mluvíš se mnou. Dobrej debil, MRTVEJ debil.}

# 38. RENESCO'S GIVING ME SHIT. (34)
{585}{}{(Masonovy oèi se zúily.) Coeto kurva? Øekl jsi mu, pro koho pracuješ?}
{586}{}{Ano.}
{587}{}{No, vlastnì ne.}

# 39. YES. (38)
{595}{}{Tak UKÁZAL jsi mu, pro koho pracuješ?}
{596}{}{Ukázat?}
{598}{}{Uh, ne. Jdu tu udìlat,  Masone.}

# 40. NO. (38, 39)
{605}{}{CO, mám tì snad dret za RUÈIÈKU?! Nejjednodušší vìc na celım zasranım svìtì a ty dokáeš akorát pøijít za mnou a 
 a breèet - ten a ten nechce platit?'}
{606}{}{No moment...}

# 41. IF PLAYER KILLED RENESCO. (WTG)
{615}{}{(Jakmile tì zahlédnul, odfrknul si.) A tady je ta pièa, kterou hledám. }
{617}{}{Nemùeš vybírat peníze od mrtvejch lidí. (Sahá po zbrani.) Seš mrtvá liška.}
{618}{}{Jo, fajn, stejnì si mì u nudil...}
{619}{}{Ne, TY SEŠ mrtvej! CHCÍPNEŠ, MASONE, SLYŠÍŠ?! Seš ÚPLNÌ MRTVEJ TY  --}

# 42. PLAYER GOT MONEY. (34)
{625}{}{(Mason kıvnul a vypadá zklamanì.) Heh. Myslel jsem, e u jsme Reneska vycucali úplnì. 
 Fajn...odnes to šéfovi. (Mraèí se.) Jdi.}

# 43. GET THE HELL OUTTA HERE. (WTG)
{635}{}{Vypadni. Pan Salvatore u tì nechce vidìt.}

# 44. GUARD = MASON (WTG)
{640}{}{Dobøe, boss øíkal, e s náma pùjdeš na malou TRANSAKCI. Pøijï ozbrojenej
 ...a nenos si jen tak nìjakou foukaèku....naber elezo a pak pøijï ke mnì.}
{642}{}{Pan Salvatore øíkal, e mi dáš laserovou pistoli}
{643}{}{Co je to za transakce?}
{644}{}{Jsem pøipravenej. Pojïme.}
{645}{}{Dej mi chvilku na pøípravu, hned se vrátím.}

# 45. SALVATORE SAID YOU WERE GOING TO GIVE ME A LASER PISTOL. (44, 46, 49)
{655}{}{Jo, taky jsem slyšel. Tady máš...ale nehrej si s tím. Jestli s tím nìkoho poraníš,
 poraním já TEBE. Poøádnì.}
{656}{}{Mùeš mi ukázat, jak se s tím zachází?}
{658}{}{Fajn, co se mì tıèe, mùeme jít.}

# 46. WHAT IS THIS TRANSACTION WE'RE DOING? (44, 45, 49, 51, 52)
{665}{}{(Odfrknul si.) Jestli ti to boss neøekl, nemusíš to vìdìt. Tak dr mlè...a ani slovo komukoli, jinak osobnì
 dohlídnu, e u nikdy nikomu vùbec nic neøekneš.}

# 47. I'M READY TO GO RIGHT NOW. (45, 46, 49, 51, 52)
{675}{}{Tak pojï.}
{676}{}{Jdi s ním a ostatními Salvátory do pouštì...}

# 48. GIVE ME SOME TIME TO GET READY . . . (44, 45, 46, 49, 51, 52)
{685}{}{Pohni sebou. Máme ètyryadvacetihodinovı okno, take pøijï vèas. Posereš to a já ti zajistím pohodlnı vyhnilı
 místeèko na Golgotì.}
{686}{}{Nestarej se, pøijdu vèas.}

# 49. RETURN . . . (WTG)
{695}{}{Tak co? Jdeme nebo ne?}
{696}{}{O èem e je ta transakce?}
{697}{}{Jo.}
{698}{}{Potøebuju ještì chvilku.}
{699}{}{Mùeš mì nauèit, jak se zachází s tou pistolí?}

# 50. RETURN LATE . . . (WTG)
{705}{}{U DLOUHO tì chci zabít. VAROVAL jsem tì, co se ti stane, kdy pøíjdeš pozdì.}
{706}{}{No tak kurva promiò e nemám  zasrané hodinky.}
{707}{}{Ne, TY SEŠ mrtvej! To JÁ tì VAROVAL! CHCÍPNEŠ, MASONE, SLYŠÍŠ?! Seš ÚPLNÌ MRTVEJ TY  --}

# 51. WHY DO I NEED . . . (52)
{715}{}{Proè se musíš do øiti ptát na všechno? Podívej: DRUHÉ stranì tıhle transakce 
 ty svìtılka nic neudìlají, jasnı? Take si dones i nìco JINİHO. }

# 52. CAN YOU TEACH ME . . . (45, 49, 51)
{725}{}{(Zabruèel.) Doprdele...hele, nejdøív, musíš to dret takhle. (Pohıbal ti s prsty.) Tak, nabíjecí komora
 je tady...(Za slabou hodinku ti Mason vylepšil schopnosti s Energetickımi zbranìmi.)}
{726}{}{Hele, proè potøebuju i nìco jinıho? Ty pistole jsou dost silné.}
{728}{}{Fajn, jsem redy. Mùeme jít.}
{729}{}{Tak dobøe. Dej mi moment na pøípravu.}

# 53. MADE MAN. (WTG)
{735}{}{(Bruèí.) Hej, ...}
{736}{}{Vezmi si to.}

# 54. MADE MAN 2. (53)
{745}{}{A navíc, my Salvatoøi...máme speciální DOHODU se sleènou Kitty v Koèièí Pacce. A Eldridgem
 v obchodu se zbranìma...a u  Reneska. (Mrknul.) Uij si to.}
{746}{}{Díky, Masone.}
{747}{}{Jó, Masone, dík...ale pøíštì mì budeš oslovovat  "pane", jasnı? Líbí se mi to. HA HA HA HA HA HA...}
{748}{}{Jó, Masone, dík...ale pøíštì mì budeš oslovovat  "madam", jasnı? Líbí se mi to. HA HA HA HA HA HA...}

# 55. MADE MAN 2. (WTG)
{755}{}{Zdravím...pane.}
{756}{}{Zdravím...madam.}

# 56. LOOK, DIPSHIT . . . (SUCCEEDS) (9)
{765}{}{VAROVAL jsem tì, kreténe a teï... (Mason se náhle zarazil a poslouchá nìco, co neslyšíš. Za chvíli zaskøípal zuby).
 Pan Salvatore øíká, e mùeš vejít... }
{766}{}{Díky, èùráku. Nezapomenu se panu Salvátorovi zmínit o tvém vybraném vychování.}

# 57. WHY AREN'T YOU TRACKING DOWN LLOYD? (23)
{775}{}{(Oèi se mu zúily.) Pochopitelnì, jestli tvoje otázka naznaèuje, e nedìlám správnì svou PRÁCI, tak budeme mít
 osobní diskusi teï hned a tady. Pana Salvatora nebude zajímat, co se s tebou stalo.}
{776}{}{Já nic nenaznaèuju, kokote. Já ti to øíkám.}
{777}{}{Uklidni se, ptám se jenom ze zvìdavosti.}
{778}{}{U mì tahle konverzace nudí. Mizím.}

# 58. EXTORTION ASSIGNMENT (33)
{785}{}{Nenech dìdka kecat blbosti. Jestli se bude cukat, øekni mu, e pracuješ pro pana Salvatora. To mu objasní
 jakıkoli pøípadnı nedorozumìní. Jasnı?}
{786}{}{Jasnı. A teï mi uhni, a mùu jít. }

# 59. NO 2. (40)
{795}{}{Seber se, zbabìlèe, a *postarej se o to.*}
{796}{}{Bylo mi jasnı, e se nìco takovıho stane, kdy bude enská dìlat chlapskou práci. Pøestaò *brblat* a *postarej se o to.*}
{797}{}{Dobøe. Díky, Masone. Fakt si mi DÌSNÌ pomohl. Dík.}
{798}{}{Dobøe.}
{799}{}{Jó, já se o to postarám. A zaènu s tebou. }

# 60. IF SALVATORE WAS ASSASSINATED (WTG)
{805}{}{Chudák pan Salvatore...u byl pìknì starej. Stejnì je ho škoda.}
{806}{}{*snf*...pan Salvatore...byl pro mì jako táta.}
{807}{}{Mìl jsem rád toho starıho dìdka. Teï je mrtvej. Škoda e se nikdy nedozvìdìl, co k nìmu cítím.}

# 61. IF PC KILLED RENESCO BEFORE TALKING TO MASON (WTG)
{815}{}{(Odfrknul si, jakmile tì uvidìl.) Slyšel jsem, e Renesco mìl "nehodu." A taky es s tím mìl nìco spoleènıho. 
  Jen aby bylo jasnı, on patøil k NÁM. A ty nám teï zaplatíš. Krví.}
{818}{}{Ne. TY SEŠ TEN, co tady bude PLATIT KRVÍ! Slyšíš?! ZABIJU TÌ, ty JEDEN ZAS--}

# 62. ACCUSE MURDER (5, 7, 10)
{825}{}{(Masonova tváø ztuhla a pak sáhnul po zbrani.)}
{826}{}{Asi zjistíš, e zabít MÌ není tak lehké jako otrávit to dìcko...}

# 63. TRADE DISRUPTED (WTG)
{835}{}{Dob je zrušenej. Vypadni.}

# 64. GO SEE THE BOSS
{840}{}{Koneènì jsi zpátky. Boss tì chce vidìt.}


# END LINES
{5735}{}{. Pan Salvatore mi øekl o tvém povıšení. Gratuluju.  Mám tu pro tebe pár hraèek (Podává ti náruè pøedmìtù.) Dej si na to bacha...}
{5765}{}{.}