#Tenhle soubor pøeložil Birdman, Birdman@post.cz, http://www.mujweb.cz/www/birdman, 0604 540689
# quick looks
{100}{}{Vidíš boxera.}
{101}{}{Vidíš Peta "Hurikána" McKneelyho.}

# examines
{150}{}{Vidíš bílého muže obaleného svaly, který ale vypadá tak slabì, že by ho knokautovala rána kusem pizzy.}
{151}{}{Jeho èelist se leskne, jako by byla ze skla.}
{152}{}{Vypadá, že v ringu nevydrží ani sedm vteøin.}
{153}{}{Vypadá tak slabì, že by ho knokautovala rána kusem pizzy.}

# FLOAT DIALOGUE
{200}{}{*Hnffff*}
{201}{}{*Hnrggg*}
{202}{}{::protahuje se::}
{203}{}{Jsem ospalý}
{204}{}{Jsem unavený}
{205}{}{*Fjù* Tìký den}
{206}{}{Posilování mì vždycky strašnì unaví...}
{207}{}{Bojování mì vyèerpává...}
{208}{}{Asi si pùjdu leštit svoji sklenìnou èelist...}

#CLICK DIALOGUE
# (ANY PRIZEFIGHTER)
{300}{}{::Boxer se na tebe dívá a rukou si kryje èelist::}
{301}{}{::Boxer se na tebe dívá a rukou si tøe èelist::}
# (NORMAL)
{302}{}{Posilování mì vždycky strašnì unaví...}
{303}{}{Budu okej, když mùj manažér mùže vlézt do ringu a zastavit boj.}
{304}{}{Jsem Pete. Pete "Poraženej" McKneely.}
{305}{}{Mám rád pizzu, ale musím si dávat pozor na okraj, je na mì moc tvrdý...}
{306}{}{Dneska ráno, když  jsem otevøel dveøe, foukal takový vítr, že mì srazil na zem}
{307}{}{Bojování mì vyèerpává...}
{308}{}{Asi si pùjdu leštit svoji sklenìnou èelist...}
{309}{}{Když vydržím trénovat, možná jednou v ringu vydržím DESET vteøin!}
# (FEMALE)
{310}{}{V ringu možná vydržím jenom sedm vteøin, ale v posteli vydržím DESET!}
