#Tenhle soubor pøeloil Birdman, Birdman@post.cz, http://www.mujweb.cz/www/birdman, 0604 540689
# QUICK LOOK
{100}{}{Vidíš staršího mue.}
{101}{}{Vidíš starého mue jménem McGee.}

# LOOK
{150}{}{Vidíš staršího mue. Vypadá rozzlobenì a nìco si šušká.}
{151}{}{Vidíš starého McGeeho. Vypadá rozzlobenì a nìco si šušká.}

# 1. FLOAT [McGEE = JACKPOT, MALE] (WTG)
{200}{}{Ty svinì! Sebrals mi všechno mé štìstí!}
{201}{}{Zabiju tì! Teï to koupíš!}
{202}{}{Myslíš e nemám odvahu, nulo? Chápeš to!}
{203}{}{Pes a syn sviòští psi!}
{204}{}{Vyrazím ti dech, nechám tì nadechnout a vyrazím ti ho znovu.}
{205}{}{Chceš nìco po starém McGeeovi, náfuko?}
{206}{}{Mám tvoje èíslo, ty sebejistá svinì.}
{207}{}{Udìlám skrz tebe díru, skuèivı asfalte.}
{208}{}{Chceš po mì nìco, je to tak? Seøídím ti vagón.}
{209}{}{Udìlám z tebe fík, chlapèe.}
{210}{}{Vykastruju tì jako brahmíního samce.}

# 2. FLOAT (McGEE = JACKPOT, FEMALE] (WTG)
{225}{}{Ty kurvo! U jsi mi toho štìstí ukradla dost!}
{226}{}{Mám tvoje èíslo, štìtko.}
{227}{}{Chceš si šáhnout, holka?}
{228}{}{Asi tì pøefiknu, holka.}

# 3. FLOAT (SLOT MACHINE) (WTG)
{235}{}{Né, jenom trochu kravskıch hoven!}
{236}{}{Blbı jednorukı bandita! Za to zaplatíš, McGee!}
{237}{}{Nevzdoruj starımu McGeemu, zlato...}
{238}{}{I nebesa jsou proti mnì!}
{239}{}{Pojï na to dìvèe...}
{240}{}{Dej mi trochu své lásky.}
{241}{}{Fikal jfem fi o fyhru, tak do toho!}
{242}{}{Ještì jeden pohyb...}
{243}{}{Chceš moje peníze, problém je v tom, e jsem je shromaïoval celé roky...}
{244}{}{Jsi jako neštovice na kùi, ty jednorukı bandito!}
{245}{}{Mohna mam dnefka fanci...}
{246}{}{Zítra budeš mít hezèí tváø.}
{247}{}{Dnes vyhraji. Øekla mi to teta štìstí.}
{248}{}{::Kopni do stroje::}

# 4. FLOAT (McGEE WARNING] (WTG)
{255}{}{Šáhni na mùj stroj ještì jednou, a budeš leet prohnilı nìkde v Golgotì.}
{256}{}{Udìláš lépe, kdy se sakra budeš dret dál od mého stroje}

# 5. FLOAT (McGEE BROKE] (WTG)
{260}{}{Hergot! Jsem na dnì!}
{261}{}{Celı dùm je proti mì!}
{262}{}{Potøebuješ další peníze...}
{263}{}{Proklatı stroj! Seere mi všechny peníze...}

# 6. FLOAT (McGEE APOLOGIZES] (WTG)
{270}{}{Omluvil ses mi, cizinèe.  Štìstí tì provázej.}
{271}{}{Promiò, neovládl jsem se. Pouštní slunce zpùsobuje, e dìlám nepochopitelné vìci.}
{272}{}{::Pozdvihá fiktivní klobouk::}

# 7. JACKPOT, ATTACK (WTG)
{275}{}{}
{276}{}{}
{277}{}{Ty, jedinı, kterı si dokázal zasáhnout jackpot na mém stroji! Hrál jsem na nìm pìt proklatıch let, a nedostal z nìj
 ani ò}
{278}{}{Grrrrrr....}
{279}{}{Drte mì}

# 8. JACKPOT, CHANCE TO TALK (7)
{285}{}{Vrazil jsem všechny své celoivotní úspory do téhle kurvy a nedala mi jedinı den jedinı pìák.
Pak si šel kolem ty a vyhrál si všechno! }
{286}{}{Ty hajzle jeden!}
{287}{}{Ty ujetá bìhno!}
{288}{}{Boe!!! Jsem ten nejvìtší blbec na tıhle planetì.}
{289}{}{Ou šit. TY máš celı jackpot a já mám pìák.}
{290}{}{Jedinı blbec v téhle místnosti jsem já.}
{291}{}{Nejsem blbec, nejsem blbec....JSEM BLBEC!!!}
{292}{}{To chce klid, McGee. Mùeme si o tom promluvit.}
{293}{}{To chce klid, pane. Mùeme si o tom promluvit.}
{294}{}{Podívej, chci ty prachy v klidu a pohodì.}
{295}{}{Poèkej minutu. Co takhle, kdybych ti všechny ty peníze dal?}
{296}{}{Kurvo, KURVO. Budeš potøebovat chirurga, abys dostal moje boty z tvojí prdele.}
{297}{}{Zmrde, ZMRDE! Budeš potøebovat chirurga, abys dostal moje boty z tvojí prdele.}
{298}{}{Jako vdy. Odcházim.}

# 9. JACKPOT, McGEE NEGOTIATING (8)
{305}{}{Mluvit? Mluvit? O èem si kurva myslíš, e bychom mohli mluvit?}
{307}{}{Chci ty peníze èisté. NE? Tak to je tvùj problém.}
{309}{}{Zlodìj! Dìdku, radši si dávej pozor na jazyk, ne ti ho narvu do chøtánu.}
{310}{}{Zapamatuj si to. Odcházim.}

# 10. JACKPOT, McGEE COMBAT (8)
{315}{}{Synku, nebudeme mluvit o hovnu. Jediná vìc, kterou budeš dìlat je chytat kulky.}
{316}{}{Zmrde, nebudeme mluvit o hovnu. Jediná vìc, kterou budeš dìlat je chytat kulky.}
{317}{}{(Šahající si pro svou pušku a drící prst na kohoutku) Tak co...?}
{318}{}{Tak se uka.}

# 11. JACKPOT, SQUARE AND FAIR (8, 9)
{325}{}{Èisté peníze, ty zmrde! Hovado, jediná monost, jak se mùeš ospravedlnit, je smrt.}
{326}{}{Èisté peníze, ty hovado! Kriple, jediná monost jak se mùeš ospravedlnit je smrt.}

# 12. RECOMPENSATE McGEE . . .? (8, 9)
{335}{}{Co....?(usmívá se) Co takhle všech 473 chipsù?}
{336}{}{Co takhle nìco kolem 250 chipsù?}
{337}{}{Jasnì....všech 473 chipsù. Tady je máš.}
{338}{}{Promiò, nemám je tady.}
{339}{}{Zapomeò. Odcházim.}

# 13. GIVE McGEE BACK ½ (12)
{345}{}{}
{346}{}{}
{347}{}{No...nikdy to nebude tolik, co jsem do ní vrazil, ale nezní to špatnì. }
{348}{}{Dobrá, chlapèe. 250 penìz ukonèí naše rozpory v míru.}
{349}{}{Dobrá, koèko. 250 penìz ukonèí naše rozpory v míru.}
{350}{}{Dobrá.}

# 14. McGEE SAYS NO DICE (12, 9)
{355}{}{ádnı kostky, chlapèe. Svou vıhru si vezmu hned zpátky}
{356}{}{ádnı kostky, holka. Svou vıhru si vezmu hned zpátky}

# 15. PAY McGEE BACK EVERYTHING (12)
{365}{}{}
{366}{}{}
{367}{}{(Zamrká, kdy peníze mìní ruce) No...nevím co øíct. }
{368}{}{Byl to od tebe mohutnı èin, chlapèe...ehm, Pane. Já...}
{369}{}{Byl to od tebe mohutnı èin, dìvèe...ehm, Paní. Já...}
{370}{}{Ano?}

# 16. TURN BACK ON McGEE (8, 12, 9)
{375}{}{Neodvauj se ke mnì otoèit zády, chlapèe!}
{376}{}{Neodvauj se ke mnì otoèit zády, dìvucho!}

# 17. McGEE INTRO (WTG)
{385}{}{}
{386}{}{}
{387}{}{Ehm? Co bys chtìl, chlapèe?}
{388}{}{Ehm? Co bys chtìla, holka?}
{389}{}{Ehm? Co zatracenì chceš, chlapèe?}
{390}{}{Ehm? Co zatracenì chceš, holka?}
{391}{}{Ty...}
{392}{}{Chtìl by sis zahrát?}
{393}{}{Pøestaò se toulat.}
{394}{}{A ty jsi kdo?}
{395}{}{Co to dìláš?}
{396}{}{Máš námitky, kdy do toho kopnu??}
{397}{}{Nic. Promiò, e jsem tì otravoval.}

# 18. BOTHERING McGEE (17)
{405}{}{(Symboly se dotáèejí a zase nic) Proklatì! Tvrdohlavá mašina! Jednou ty peníze dostanu zpátky...}
{407}{}{Jdi! Èèèau}
{409}{}{Ehm, jak dlouho u hraješ?}
{410}{}{Promiò, e jsem tì obtìoval.}

# 19. McGEE's REASON FOR LIVING (18)
{415}{}{}
{416}{}{}
{417}{}{5 let zavøenı...Mám za to...e se jednou tahle mašina rozbije, a kdy...
Pomsta bude sladká! Ha ha ha!}
{418}{}{Oups, hodnì štìstí.}
{419}{}{Dobøe. Promluvíme si pozdìji.}

# 20. McGEE JEALOUS (17, 18)
{425}{}{}
{426}{}{}
{427}{}{(pohrdavì) Dotkni se moji mašiny! Myslíš e seš dobrej? Vypadni!}
{428}{}{Dobrá...}

# 21. RETARDED vs. McGEE (8)
{435}{}{Proklatej uslintanej invalide! Beru si ty peníze zpìt...HNED!}

# 22. McGEE LOSES TEMPER, VOL. 56 (9, 12)
{445}{}{Vypadá to, e pro ty peníze pùjdu i pøes mrtvoly, chlapèe! Pøiprav se na olovo v tvém tìle!}
{446}{}{Vypadá to, e pro ty peníze pùjdu i pøes mrtvoly, dìvèe! Pøiprav se na olovo v tvém tìle!}

# 23. JACKPOT, ATTACK 2 (7)
{455}{}{Vrazil jsem všechny své celoivotní úspory do téhle kurvy a nedala mi jedinı den jedinı pìák. Pak si šel kolem ty a vyhrál si všechno! }

# 24. PAY McGEE BACK EVERYTHING (15)
{465}{}{Pouštní slunce mùe udìlat to, e mù øíká naprosto hrozné vìci, a tady máš moji omluvu. (Uctivì kyne fiktivním kloboukem.) }
{466}{}{Štìstí tì provázej, pane.}
{467}{}{Štìstí tì provázej, paní.}
{468}{}{Dobrá. Omluva pøijata.}

# end lines
{1290}{}{.}
