#Tenhle soubor pøeloil Birdman, Birdman@post.cz, http://www.mujweb.cz/www/birdman, 0604 540689
#Herdek Birdmane! Kdybys pod tím nebyl podepsanej, nevìøil bych, es to pøekládal ty...by Somnambulus
# QUICK LOOK
{100}{}{Vidíš jednoho z Mordinovıch muù.}
# RAMIREZ
{101}{}{Vidíš Ramireze.}

# LOOK
{150}{}{Vidíš opáleného mue s mnoha pohmodìninami a s oddrolenou kùí. Pohybuje se okolo nerváka.}
{151}{}{Vidíš jednoho z Mordinovıch muù.}
{152}{}{Vidíš jednoho z Mordinovıch muù. Vypadá jako malı skokan.}
{153}{}{Vidíš jednoho z Mordinovıch muù. Vypadá nervóznì.}
{154}{}{Vidíš jednoho z Mordinovıch muù. Vypadá jako by u dlouho nespal.}
# RAMIREZ
{160}{}{Vidíš ušmudlanıho chlapíka s vlasy na jeky. Oèima tìká nervóznì dokola.}

# 1. FLOAT [ENCLAVE DESTROYED]
{200}{}{Jo! }
{201}{}{Kurva, }
{202}{}{::Dává ti znamení zdviením palce::}
{203}{}{::hvízdá::}

# 2. FLOAT [POWER ARMOR]
{205}{}{Jak chèiješ, kdy máš na sobì tu vìc?}

# 3. FLOAT/CLICK [MADE MAN, SAME FAM, ARMED
{210}{}{To je pìknej kousek ta tvoje bouchaèka, }

# 4. FLOAT/CLICK [MADE MAN, SAME FAMILY, SNEAK]
{215}{}{Co tu okolo šmejdíš, }

# 5. FLOAT [MADE MAN, SAME FAMILY]
{220}{}{Máš u sebe nìjakej Jet, kámo?}
{221}{}{Hej, }
{222}{}{Dal bych si panáka. Zatracenì...}
{223}{}{Sáákra, to je mi zápal.}
{224}{}{Nìjaké novinky tam od šéfù, eh, }

# 7. FLOAT [MADE MAN, NOT SAME FAMILY]
{230}{}{Jo! Porca Cabrona! Hledáš Andìla smrti? Zlikvidujte tenhle ksindl!}
{231}{}{Co to kur...ty! Ty, co tu dìláš?}
{232}{}{Jo! Puta! Hledáš Andìla smrti? Vypadni!}

# 9. FLOAT [MALE, ARMED, RESPECTFUL]
{235}{}{Hej! Sory hombre, ale tuhle vìcièku tu nemùeš jen tak nosit.}
{236}{}{Hej! Hombre, dej tu vìc pryè ne tu nìkterı lidi znervózníš.}

# 10. FLOAT [FEMALE, ARMED, RESPECTFUL]
{240}{}{Hej! Chica, ale tuhle vìcièku tu nemùeš jen tak nosit.}
{241}{}{Hej! Chica, dej tu vìc pryè ne tu nìkterı lidi znervózníš.}

# 11. FLOAT [MALE, SNEAK, PRIZEFIGHTER]
{245}{}{Co se tu sakra plííš, }

# 12. FLOAT [FEMALE, SNEAK, PRIZEFIGHTER]
{250}{}{co se tu plííš, èíèo? S tím pravım hákem co umíš, mùeš chodit normálnì..}

# 13. FLOAT/CLICK [PRIZEFIGHTER]
{255}{}{Kde ses uèil bojovat, }
{256}{}{Ty Mordinovskı prasata...}
{257}{}{Ten minulı boj to bylo nìco úasnıho, hombre.}
{258}{}{Dávej si bacha na dímaèku. Rád jí uši.}
{259}{}{Lítá jako motıl, bodá jako vèela. To jsi ty, }
{260}{}{Taky jsem døív boxoval, ale zranil jsem si ruku, tak teï u nemùu, víš?}
{261}{}{Mordinùm by se ty tvoje svaly hodily, }
{262}{}{Odkud jsi, e ses nauèil tak bojovat? Jsi dobrej. Tím myslím fakt DOBREJ.}
{263}{}{Radím ti promluvit si s Malım Jeíšem o práci, }
{264}{}{Vsadil jsem na tebe. Nejlíp vsazené peníze co jsem kdy vsadil. Smetls´ ho jako nic.}
{265}{}{Vidìl jsem ten tvùj zápas v ringu, }
{266}{}{Kolik to hodí, }
{267}{}{Kde pracuješ, he?}
{268}{}{Pozval bych tì na drink, nepøijít o všechny prachy, tím, e jsem vsadil proti tobì.}
{269}{}{Kde ses uèila bojovat, chica? Jsi zvrhlá. Dìlat takovı POHYBY... rukama, nohama. 
Vlasama, zádama. Hele to je mi nìjakı povìdomı.}
{270}{}{Ty máš na to bıt jedním z Mordinovcù.}
{271}{}{Minulı boj byl nìco impozantního, chica.}
{272}{}{Kde pracuješ, he? Potøebuješ prachy?}
{273}{}{Dávej si bacha na dímaèku. ere uši...je to nemocnej trotl.}

# 15. FLOAT/CLICK [ARMED, PORN STAR, FEMALE]
{280}{}{Hej, hej, hej! Chica, potøebuješ pomoct, abych z tebe tu zbraò sundal?}
{281}{}{To chceš abych tì svlíkl, prohledal tì a tak? Zastrè to elezo nebo budu zlej.}

# 16. FLOAT [MALE, SNEAK, PORN STAR]
{285}{}{Co se to tu sakra plííš, }

# 17. FLOAT/CLICK [SNEAK, PORN STAR, FEMALE]
{290}{}{Není zpùsob jak se s tìlem jako máš ty, proplíit kolem Mordinovovcù, chica.}

# 18. FLOAT [PORN STAR]
{295}{}{Tvùj film nebyl špatnı, ale oèividnì ode mne potøebuješ pár rad.}
{296}{}{Zmiò se o mnì bráchùm, jo?}
{297}{}{Hej, }
{298}{}{Jsem pøipravenej. Jsem volnej. Mùu si zahrát ve filmu? Promluvíme si v kanceláøi, }
{299}{}{Jsem poslední Latinskej milenec. ádnej jinej Latinskej milenec se mi nevyrovná.}
{300}{}{Øekni o mì Bratrùm, }
{301}{}{Slyšel jsem, e Tommy "Koule" si s tebou chce dát soukromı natáèení.}
{302}{}{Tak jak, udìláme spolu film? Já tì pìknì rozdìlám, chica. Ukáu ti co Latinskı milenec dokáe.}
{303}{}{Proè se tu po práci nezastavíš?}
{304}{}{Máš nìjakého pøítele?}
{305}{}{Dìláš dobrou vìc, es navštívila Mordiny. My tu budeme vládnout.}
{306}{}{Potøebuješ nìjakej Jet?  Mohu ti jich pár dát, chica.}
{307}{}{Chica, není nic co bych pro tebe neudìlal...vánì. Dej mi pusinku.}
{308}{}{Potøebuješ nìjaké drogy? Chlast? Prachy? Mohu tì zásobit. Mám známosti, chápeš?}

# 20. FLOAT/CLICK [ARMED, SLAVER]
{315}{}{Moc tu s tím elezem nemávej, kámo. Dej to pryè.}

# 21. FLOAT/CLICK [SNEAK, SLAVER]
{320}{}{Neplaz se tu okolo otrokáøi, OK? Jsi mezi pøáteli.}

# 22. FLOAT/CLICK [ARMED, NO REP]
{325}{}{Hej! Seš blbej nebo co? Dej tu vìc pryè, ne tì praštím.}
{326}{}{Koleduješ si o pefrontální lobotomii? Dej tu vìc pryè.}
{327}{}{Hej, chica! Jsi blbá nebo co? Dej tu vìc pryè, ne tì praštím.}

# 24. FLOAT/CLICK [SNEAK, MALE, NO REP]
{330}{}{Kam se to ksakru plííš? Chceš aby tì nìkdo sejmul?}

# 25. FLOAT/CLICK [SNEAK, FEMALE, NO REP]
{335}{}{Kam se plííš, chica? Chceš aby tì nìkdo sejmul?}

# 26. FLOAT/CLICK [COMPANION: ROBOBRAIN]
{340}{}{Odvez si tu pojízdnou popelnici pryè.}
{341}{}{Roboti sem nemají pøístup. Vypadni.}
{342}{}{Ten robot pùjde do šrotu, jestli tu zùstane dıl.}

# 27. FLOAT/CLICK [COMPANION: MARCUS]
{345}{}{MYSLÍM, e cejtím mutanta. Vem si ho ven nebo z nìj zešílíme.}
{346}{}{Jsi milovník mutantù? Jejich místo je VENKU. Prostì kdekoli jinde ne tady.}
{347}{}{Ten mutant se chce stát cviènım cílem? Tak a zmizne nebo mu to pøání splním.}

# 28. FLOAT/CLICK [COMPANION: LENNY]
{350}{}{MYSLÍM, e tu cítím nìco hnít. Odveï si toho ghoulíka pryè odtud.}
{351}{}{Odveï si toho páchnoucího ghoula pryè odtud. Hned!}
{352}{}{Jestli odsud ten ghoul do minuty nezmizí, bude ještì mrtvìjší ne je teï.}

# 29. FLOAT [ENCLAVE DESTROYED]
{355}{}{Chtìl jsem bıt jedním z hlavních NPC v tıhle høe, ale dostal jsem jenom tenhle štìk...}
{356}{}{New Reno bylo navreno Chrisem Avellonem, sescriptováno Tomem Frenchem a pøeloeno vìtšinou Birdmanem. Všichni stejnı úchylové.}
{357}{}{Hej! }
{358}{}{Kurva, }
{359}{}{Proslıchá se e tì hledají Korsiètí Bratøi.}
{360}{}{Myslel jsme, e Prezident je jenom legenda.}
{361}{}{Vypadáš jako by tì hodili do pekla a zas tì vytáhli. Trochu si odpoèiò. Zaslouíš si to.}
{362}{}{Èlovìèe, ti ti bastardi z Enklávy mìli štìstí, e se nezapletli s Mordinem.}

# 30. FLOAT [MADE MAN, SAME FAMILY]
{370}{}{Máš u sebe nìjakej Jet, kámo?}
{371}{}{Jak ti to visí? Jako kladivo, chlape a v tom to je.}
{372}{}{Heh? ::Odplivne si:: Jak se vede, }
{373}{}{Rád tì vidím, }
{374}{}{Jistì e mùeš vypít drink. Zatracenì...}
{375}{}{Ále to víš, poøád jsem stejnì starej, jó stejnì starej. Jak je s tebou,}
{376}{}{Sáákra, to píše.}
{377}{}{Velkej Mordino se má dobøe? Øekni mu, e jsm se po nìm ptal, eh, }
{378}{}{Minulou noc jsem zastøelil škorpióna. Skoro mì uštknul, hajzl jeden.}
{379}{}{Jestli se do nás Bishop zaène srát, udìláme z nìj rádlo pro èervy, e jo?}
{380}{}{Nìjaké novinky tam ze shora, eh,}
{381}{}{Kdy zas sejmeme nìjakıho toho Bishopovce, co? Moje pistole u rezaví.}
{382}{}{Ti Salvatoøi si tu kolem chodí, jako kdyby jim Reno patøilo. Potøebovali by malou lekci, co?}
{383}{}{Slyšel jsem, e Tommy "Koule" je ve mìstì. Radši si jí pøiprav.}
{384}{}{Máš u sebe nìjaké Jety, chica? Je mi na chcípnutí.}

# 32. CLICK [MADE MAN, NOT SAME FAMILY]
{400}{}{Couraj se nám tu nìjakı prasata. Asi je èas vykydat trochu kejdy.}
{401}{}{Podle tvıho ksichtu hádám, e tvoje máma pochází ze psí boudy.}
{402}{}{Vypadáš jako èlovìk, kterej neví kdy je èas umøít.}
{403}{}{Hijo de puta...}
{404}{}{To mluvíš se mnou? To mluvíš se mnou?}
{405}{}{Promluv na mì ještì jednou a nakrmím tì olovem tak, e tì ani Superman nezvedne.}
{406}{}{::Plive ti pod nohy::}
{407}{}{Myslíš si, e si mùeš jenom tak napochodovat a promluvit si s Mordinovcem? Vypadni!}
{408}{}{Promluv na mì ještì jednou a zabiju tvou rodinu, tvıho psa, a pak i tebe. Dvakrát.}
{409}{}{::Plive ti pod nohy::}
{410}{}{Myslíš si, e si mùeš jenom tak napochodovat a promluvit si s Mordinovcem? Vypadni!}
{411}{}{Promluv na mì ještì jednou holka a nakrmím tì olovem tak, e tì ani Superman nezvedne.}
{412}{}{Nebude lepší kdy se vrátíš zpìt do svı boudy, kotì?}
{413}{}{Musíš bıt to nejblbìjší stvoøení na celém svìtì, kdy se se mnou poøád snaíš mluvit.}
{414}{}{Hija de puta...}

# 34. CLICK [SLAVER]
{420}{}{Nee, já nejsem chlápek, kterej kupuje otroky. Spíš si promluv s Malım Jeíšem.}
{421}{}{Kam chodíš, na ty príma otroky? Promiò ty ztráty v minulé sezónì, otrokáøi. Blbı.}
{422}{}{Mordinovci teï nepotøebujou ádnı otroky. Ledae by ses nutnì potøeboval zbavit nìjakıho nákladu...}
{423}{}{Nejsem osoba zodpovìdná za obchod s otroky.}
{424}{}{Dìláš dobrou vìc, e to táhneš s Mordinem. My to tu vedem.}
{425}{}{Jak to jde v Denu vìci, eh?}

# 35. CLICK [MALE/FEMALE, NO REP, GOOD REACTION]
{430}{}{Hledáš práci, eh? Promluv si s Malım Jeíšem.}

# 36. CLICK [NO REP, BAD REACTION]
{435}{}{Podívej, nejsem tvùj kompadre, tak u na mì víc nemluv.}
{436}{}{Mordinovci nemaj ádné pøátele s vıjimkou Mordinovcù. Vyfiè, neandrtálèe.}
{437}{}{Vyfiè, neandrtálèe.}
{438}{}{Nemám na tebe teï èas.}
{439}{}{Kliï se odsud.}
{440}{}{Neandrtálskej odpade...}
{441}{}{Co doprdele chceš, divochu?}
{442}{}{Nemám na tebe teï èas.}
{443}{}{Zmizni.}
{444}{}{Neandrtálskej vodpade...}
{445}{}{Nedám ti ádné Jeta a je mi fuk jak budeš ebrat. Vyfiè.}
{446}{}{Podívej, NEJSEM tvùj brácha, tak u na mnì nemluv.}
{447}{}{Podívej, kdy potøebuju kurvu, tak si jí koupím. Teï vypadni, chica.}
{448}{}{Mordinovec nemá pøátele kromì Mordinovce. Vyfiè, holka.}
{449}{}{Vyhul, holka.}

# RAMIREZ UNIQUE DIALOG
# 37. CLICK [DELIVERY = ASSIGNED] (WTG)
{460}{}{(Kdy tì uvidìl, jak se blííš, ušklíbl se) Hledáš problémy, hombre?}
{461}{}{(Kdy tì uvidìl, jak se blííš, ušklíbl se) Hledáš problémy, chica?}
{462}{}{Ramirez? Velkı Jeíš mi pro tebe dal tenhle balíèek.}
{463}{}{ádné problémy. U odcházím.}

# 38. CLICK [DELIVERY = ASSIGNED] (37)
{470}{}{(Bere si krabici) No u bylo naèase. Málem nám Jet úplnì došel. (Funí, lehce kašle.) Nevím, kam se furt všechen ztrácí...}
{471}{}{Jo, dobøe, buï opatrnı --}
{472}{}{Kdy tì tak pozoruju, jak kašleš a jak se šouráš v nose, je asi zbyteèné se ptát, kam se podìl všechen ten dodanı Jet.}

# 39. CLICK [DELIVERY = ASSIGNED] (38)
{473}{}{Velkej J, podívejme, jak se o nás stará, he? Minulı tıden jsem chytil tøi otroky, kteøí byli dost pitomí na to, aby utekli. Tak jsem dostal odmìnu, víš? Hehe. A ty jsi ji nedostal. Ty jsi jen poslíèek. Já, já jsem strá}
{474}{}{Jo, bezva. Tak se opatruj.}
{475}{}{Jsem zvìdav, jestli Velkı Jeíš bude mít pochopení pro to, jak ti tøi otroci mohli utéct pøímo pod NOSEM tak všímavého, na Jetu závislého stráného, jako jsi ty.}
{476}{}{Ramirezi...dej si bacha na to, co mi øíkáš, jo? A tì tvùj jazyk nepøivede do problémù.}

# 40. CLICK [DELIVERY = ASSIGNED] (39)
{480}{}{(Mrkne) Eh...? Co øíkáš?}
{481}{}{Nic, èemu bys rozumìl nebo já mìl chu to teï opakovat. Mìj se.}
{482}{}{Øíkal jsem, "Jsem zvìdav, jestli Velkı Jeíš bude mít pochopení pro to, jak ti tøi otroci mohli utéct pod NOSEM tak všímavého, na Jetu závislého stráného, jako jsi ty."}

# 41. CLICK [DELIVERY = ASSIGNED] (40)
{490}{}{(Zamrká a zmatenì se smìje.) Eh? Jo, jo. Jsem bdìlı a...os-ostraitı...Já jsem STRÁ, chápeš?}
{491}{}{Jo, zmínil ses o tom u pøedtím. Udìlal bys lidstvu velkou laskavost Ramirezi, kdybys celou tu krabici Jetu vyšòupal najednou. Mìj se.}
{492}{}{Chlapèe, jsem rád, e nìkdo mìl tolik rozumu, aby ti dal zcela automatické zbranì. Dává mi to pocit jistoty. Nashle Ramirezi.}

# 42. CLICK [DELIVERY = ASSIGNED] (39)
{493}{}{(Mrkne) Eh...? Co øíkáš?}
{494}{}{Zapomeò na to. Strè si do tlamy pistoli a zmáèkni spouš, jo?}
{495}{}{Ale nic. Udìlal bys lidstvu velkou laskavost Ramirezi, kdybys celou tu krabici Jetu vyšòupal najednou. Mìj se.}
{496}{}{(Jít pryè.)}

# 43. CLICK [DELIVERY = ASSIGNED] (39, 40, 41, 42)
{500}{}{(Jak se chystáš jít pryè, Ramirez zachrochtá) Hej! Ta krabice je otevøená!}
{501}{}{Zahráváš si, hombre?}
{502}{}{Zahráváš si, chica? }
{503}{}{Nikdo nebude vyjebávat s Ramirezem, rozumíš?!}
{504}{}{Jo, poslouchám tì. Ale ne moc dlouho.}
{505}{}{Jako poslední slovo to nebylo nic moc, Ramirezi.}

# delivered box
{600}{}{Doruèil jsi balík od Velkého Jeíše Ramirezovi?}

# END OF LINES
{1200}{}{! Takhle se má Enklávì nakopat prdel!}
{1201}{}{, zpùsob jak nauèit ty bastardy z Enklávy, zaè je toho loket.}
{1210}{}{.}
{1215}{}{? Mordinové jsou na tebe pyšní.}
{1221}{}{! Que pasa?}
{1224}{}{?}
{1245}{}{? S tím pravım hákem co máš, máš bejt na co hrdej.}
{1255}{}{? Seš zkaenej. Máš to v ksichtì, hombre.}
{1259}{}{.}
{1261}{}{. Kdy tì ostatní rodiny vidìly pøicházet, tak se málem posraly.}
{1263}{}{.}
{1265}{}{. Tys s tím chlapíkem teda vymrdal.}
{1266}{}{?}
{1285}{}{? Sakra, to je klasa..}
{1297}{}{! Que pasa? Seznámíš mì s Bratrama?}
{1298}{}{, boxovací kanceláø!}
{1300}{}{... Jasnì. Mùu to udìlat.}
{1357}{}{! Cesta jak nakopat Enklávì prdel!}
{1358}{}{, zpùsob jak nauèit ty bastardy z Enklávy, zaè je toho loket.}
{1372}{}{?}
{1373}{}{. Kde jsi byl?}
{1375}{}{?}
{1377}{}{?}
{1380}{}{?}