#Tenhle soubor pøeloil Birdman, Birdman@post.cz, http://www.mujweb.cz/www/birdman, 0604 540689
# 0. QUICK LOOK
{100}{}{Vidíš hlídaèe.}

# 0. LOOK
{150}{}{Vidíš unudìného hlídaèe. Urèitì by byl radši nìkde úplnì jinde.}
{151}{}{Vidíš jednoho z Myronovıch unudìnıch bodygárdù.}
{152}{}{Vidíš jednoho z Myronovıch unudìnıch bodygárdù. Urèitì by byl radši nìkde úplnì jinde.}

# 1. FLOAT [TOUCH LOCKER] (WTG)
{200}{}{Šáhni mi na moje krámy ještì jednou a zabiju tì.}

# 2. FLOAT [TOUCH DOOR AND MYRON_PERMISSION = TRUE] (WTG)
{205}{}{Pokraèuj. Všechno je okej.}
{206}{}{Bì dovnitø. Všechno je v rychtyku.}

# 3. FLOAT [TOUCH DOOR] (WTG)
{210}{}{Šáhni na ty dveøe ještì jednou a budeš mít místo ruku pahejl.}
{211}{}{Vypadni odtamtud.}

# 4. COMPANION: MYRON (X)
{215}{}{Hej, Myrone! Jdeš na procházku?}
{216}{}{Dej na sebe bacha, Myrone.}
{217}{}{Dej si bacha, a se nedostaneš do nìjakıho maléru, Myrone.}
{218}{}{Nechoï radši moc daleko, Myrone.}

# 5. FLOAT [MADE MAN]
{225}{}{Hey, }
{5225}{}{! Jak je?}

# 6. FLOAT [MADE MAN, NOT MORDINO, ARMED]
{230}{}{Támhle je }
{5230}{}{! Na nìj!}

# 7. FLOAT/CLICK [MALE, MADE MAN, NOT SAME FAMILY]
{235}{}{Máš poøádnou vodvahu, e se vopovauješ strèit sem tu svoji drku. Radši zmiz.}
{236}{}{Vypadáš jako }

# 8. CLICK [FEMALE, MADE MAN, NOT SAME FAMILY]
{240}{}{Co kdyby ses radši vrátila k tı svı podìlanı rodinì }
{241}{}{Vypadáš jako }

# 9. FLOAT [ARMED, MALE, NO REP]
{245}{}{Odlo tu zbraò...nebo budeš mít VELKEJ problém!}

# 10. FLOAT [SNEAK, MALE, NO REP]
{250}{}{Vetøelec!}

# 11. FLOAT [COMPANION: ROBOBRAIN]
{260}{}{Vypadni s tou popelnicí!}
{261}{}{ádní roboti. A zmizne.}
{262}{}{Udìlám ti z toho bota šrot, jestli si ho vocaï nevodtáhneš!}

# 12. FLOAT [COMPANION: MARCUS]
{270}{}{*Vìdìl* jsem, e cítím mutantí smrad. Odveï si ho, nebo se šílenì naseru.}
{271}{}{Miluješ mutanty, jo? Tak si ho seber a jdìte si to udìlat nìkam jinam.}
{272}{}{Ten mutant si chce zahrát na cviènej cíl? A tu ještì chvíli vopruzuje a jeho sen se mu kurva rychle splní!}

# 13. FLOAT [COMPANION: LENNY]
{280}{}{Hmm, tak se mi to nezdálo, fakt tady nìco hnije. Vem si tu ghoulí sraèku a vypadnìte.}
{281}{}{Vypadni i s tím smradlavım ghoulím matkomrdem. Hned!}
{282}{}{Jestli ten ghoul vocaï hned nevypadne, tak bude ještì mrtvìjší, ne je!}

# 14. [PORN STAR, FEMALE OR FEMALE, CHR > 5] (WTG)
{290}{}{::Uau.:: Podívejte se na ni!}
{291}{}{Hej kotì, hledáš spoleènost?}
{292}{}{Nechceš s náma strávit nìjakej èásek, kotì?}
{293}{}{::Kdy tì zahlídnul, zavyl jako vlk:: Hauuuu!}

# 15. [SLAVER] (WTG)
{300}{}{Co tu ksakru chceš, otrokáøi? Otroci jsou nahoøe!}

# 16. FLOAT [MYRON_LEFT_STABLES] (WTG)
{305}{}{Co se stalo s Myronem?}

# 17. FLOAT [NORMAL] (WTG)
{310}{}{Myron ještì furt vyspává?}
{311}{}{Nuda. Nudím se.}
{312}{}{Vidìls ten boj vèera veèer?}
{313}{}{U aby ta šichta skonèila, za chvilku tady vystojím dùlek.}

# 18. INTRO (WTG)
{320}{}{Chceš s nìèím pomoct, amigo? Sem se nesmí!}
{321}{}{Ale ale, máme tady mezi náma hvìzdu. Máš schùzku s Myronem, kotì?}
{322}{}{Potøebuješ nìco, kotì? Sem se nesmí.}
{323}{}{(Hlídaè se usmívá a prohlíí si tì od hlavy k patì.) Máš schùzku s Myronem, kotì?}
{324}{}{Já chceš svjetová míra}
{325}{}{Já chceš za dveøe chodit}
{326}{}{Gdó tı seš}
{327}{}{Odejdi}
{328}{}{Nesmí se tady? Co je za tìmi dveømi?}
{329}{}{Jdu za Myronem.}
{330}{}{Jdu za Myronem. Mám prùkaz.}
{331}{}{Jdu za Myronem. Máme spolu "zvláštní schùzku", jestli mi rozumíš.}
{332}{}{Jasnì. Necháš mì tady postávat, nebo se tvoje oèi u nabaily?}
{333}{}{Coe? Jakou schùzku?}
{334}{}{Sorry, špatná místnost. U mizím.}

# 19. RETARD (18)
{350}{}{Utekl jsi ze stáje, otroku? Tak radši zvedni prdel a padej zpátky, nebo tì strèíme do klece!}
{351}{}{JÁ CHCEŠ MÍR JÁ CHCEŠ MÍR  JÁ CHCEŠ MÍR}
{352}{}{JÁ ØÍKÁŠ JÁ CHCEŠ ZA DVEØE JÍT!}
{353}{}{GDÓ Tİ}
{354}{}{Odejdi}

# 20. LOUD RETARD (19)
{360}{}{(Prohlíí si zbraò.) Pouívám to. Nezbil jsem otroka u nìjakou tu hodinu...}
{361}{}{(Pøipravuje si zbraò.) Tohle si uiju. U jsem nikoho nezabil aspoò dva dny...}
{362}{}{TY TEN KDO PO HUBA DOSTANEŠ}
{363}{}{ BUM}
{364}{}{Zkus to a uteè.}
{365}{}{Kámo, dostaneš nejvìtší náøez ve svım ivotì.}

# 21. WHAT'S BEHIND THAT DOOR? (18, 30)
{370}{}{(Odfrknul si.) Sorry. To nemusíš vìdìt. A teï se ztra...amigo.}
{371}{}{(Odfrknul si.) Sorry. To nemusíš vìdìt. A teï se ztra, kotì.}
{374}{}{Pus mì. Musím se dostat za ty dveøe.}
{375}{}{Dobøe dobøe.}

# 22. I'M HERE TO SEE MYRON (18, 21, 30)
{380}{}{Jo tak? Tak proè to ksakru neøekneš hned. Mohli jsem celej tenhle blbej rozhovor pøeskoèit,
protoe bych ti øek táhni do hajzlu hned.}
{381}{}{Myron na mì èeká. Radši mì pus dovnitø hned, nebo si to potom odskáèeš!}

# 23. MYRON'S EXPECTING ME (22, 29)
{390}{}{Nah. Nepudeš k nìmu. A teï táhni, nebo se vánì rozzuøím.}
{391}{}{Mùeš mu aspoò pøedat vzkaz?}

# 24. MYRON'S EXPECTING ME  2 (21, 22, 23)
{400}{}{Ne. A teï táhni do HAJZLU, ty hovne!}
{401}{}{Zùstanu tady, dokud mì nepustíš dovnitø. Vlastnì by mì docela zajímalo, jak bys mì odsud dostal.}
{402}{}{Zùstanu tady, dokud mì nepustíš dovnitø. Vlastnì by mì zajímalo, jak by mì takovı ranec sraèek jako ty dokázal k nìèemu pøinutit.}
{404}{}{Dobøe.}

# 25. I'M STAYING (24)
{411}{}{Já taky...}
{412}{}{Braò se.}

# 26. MYRON + BADGE (18, 21, 22, 23, 24, 29, 30)
{425}{}{Jo? Uka. Hmmmm. (Kontroluje propustku, pak pokrèil rameny.) Dobøe, ale pohni sebou. Myron má práci
 a nemá rád, kdy ho nìkdo vyrušuje.}
{426}{}{Jasné.}

# 27. SURE DO (18)
{435}{}{(Jeho oèi bláznivì jezdí po tvém tìle.) Jo jo...heh heh...i kdy, moná bych pro tebe mìl DALŠÍ prácièku pozdìji. A skonèíš uvnitø, pochopitelnì.}
{436}{}{Já...si to budu pamatovat. Mùu dovnitø.}
{437}{}{Uvidíme, dobøe?}

# 28. CAN I HEAD ON IN? (27, 31)
{445}{}{Jasnì, zlatíèko. Bì dovnitø.}
{446}{}{Jo, jdi dál.}
{447}{}{Díky.}

# 29. SKANKY REFUSAL (18)
{455}{}{Ty? Ha! Kotì, pokud Myron najednou neoslepnul, ty dovnitø nepùjdeš, jasnı? Znám jeho chutì. A k tìm nepatøí nìjaká vojetá dìvka, která chce trochu Jetu.}
{457}{}{Hele, jsem tady za Myronem. Mám propustku.}
{458}{}{Pùjdu.}

# 30. APPOINTMENT? (18)
{465}{}{Oh, sorry. S nìkım jsem si tì splet. Co chceš, kotì?}
{466}{}{Co je za tìmi dveømi?}

# 31. MADE MAN OR PERMISSION (WTG)
{475}{}{Myron tì oèekává?}
{5476}{}{! Myron je támhle za dveøma. Oèekává tì?}
{477}{}{Ano. Mùu dovnitø? Máme spolu nìjaké jednání...}
{478}{}{Ne, teï zrovna ne. Dávejte si bacha, chlapi.}

# 32. MYRON AIN'T AROUND (WTG)
{485}{}{Myron tady není.}
{5486}{}{, co je? Oh, hej...Myron tu není.}
{487}{}{Mùu jít dovnitø?}

# 33. MYRON AIN'T AROUND 2 (32)
{495}{}{(Pokrèil rameny.) To je mi jedno. Jestli na nìj chceš poèkat, jdi dál. Ale fakt nevím, kdy bude zpátky...
 nebo jestli se vùbec ještì vrátí.}

# END LINES
{5236}{}{ kterej neví, e by mohl brzo zdechnout.}
{5240}{}{ a zalezla do boudy, èubko?}
{5241}{}{ která neví, e by tu mohla brzo zdechnout..}
