#soubor pøeloen ve skvìlé spolupráci Mawericka a Somnambula :o))
#Zároveò mìl tento soubor tu èest bıt ÚPLNÌ POSLEDNÍM pøekládanım souborem z celé hru... ufff
# 0. QUICK LOOK
{100}{}{Vidíš Orvilla Wrighta.}

# 0. LOOK
{150}{}{Vidíš velmi dobøe obleèeného dentlmena. Vypadá neustále ustaranì. To asi proto, e jeho hnìdé vlasy rostou pouze na okrajích hlavy.}
{151}{}{Vidíš bruèícího Orvilla Wrighta. Vypadá, jako by chtìl roztáhnout zbytky svıch vlasù po celé hlavì.}
{152}{}{Vidíš bruèícího Orvilla Wrighta. Vypadá ustaranì a tiše vzdychá.}

# 1. THIEF WARNING MESSAGE (WTG)
{200}{}{Vypadni odsud!}

# 2. COMBAT MESSAGES (WTG)
{210}{}{Dìti, odejdìte pryè! Je to zabiják!}
{211}{}{Teï chcípneš, ty èubèí synu.}
{212}{}{Vlízt do mıho baráku, to tì bude mrz…}
{213}{}{Tak oni Tì poslali, aby si za nì udìlal tuhle špinavou práci…}
{214}{}{Ty zabijáku, tohle je tvùj poslední dob…}

# 3. FLOAT COMMENTS (WTG)
{220}{}{Manelství není ádná legrace. Je to otázka ivota.}
{221}{}{Zatracení Salvatoøi…}
{222}{}{Kde jsou ty zatracenı dìcka…}
{223}{}{Vidìl tu nìkdo okolo Christophera? Øekni tomu klukovi, e ho chci vidìt. Teï hned.}
{224}{}{Rád bych vìdìl, jestli je naše manelství legální…}
{225}{}{Tohle ètvrtletí nám zisky klesly....radši zaèneme do chlastu pøilívat víc vody.}
{226}{}{Potøebuju víc ethylalkoholu. A ménì Ethyl Wrightové…}
{227}{}{Salvatoøi bıvají tiší…}
{228}{}{Kde je k èertu ta enská? Ethyl! Ethyl!}
{229}{}{Potøebuju zastavit tu kletbu, která koluje kolem našich dìtí...}
{230}{}{Budeme muset rozšíøit distribuci, jestli budeme chtít zùstat v mapì Rena...}
{231}{}{Jestli Christopher se mnou bude ještì mluvit...}
{232}{}{Pøines mi mojí knihu.}
{233}{}{Ubohı Richard…}
{234}{}{Je trocha samoty a ticha takovej høích?!! Nech mì bıt!}

# 4. INTRO (PERMISSION = TRUE) (WTG)
{240}{}{(Vrásky v oblièeji toho starého mue...vypadá to, e jinı vıraz, ne se mraèit, ani nezná. Mezi jeho šedımi vlasy se povaluje pouze pár hnìdıch vlasù.) }
{241}{}{Tak mluv, cizinèe. Kdo jsi a co tu chceš?}
{242}{}{Zaèni mluvit, otrokáøi. Kdo jsi a co tu chceš?}
{243}{}{Já }
{244}{}{Boogity boogity}
{245}{}{Yoo Boo Hoo Yooooo}
{246}{}{Kootchie Kootchie Koooo}
{247}{}{Kdo k èertu}
{248}{}{Jsem obyèejnı pocestnı…hledající práci.}
{249}{}{Jmenuju se }
{250}{}{Zøejmì sem musel vstoupit do špatné místnosti. Radši pùjdu pryè.}

# 5. RETARD SPEAK (4)
{260}{}{(Mraèí se.) Jdi mi z oèí. Jestli sem pøijdeš ještì jednou, tak tì nechám sejmout, slyšels mì dobøe?}
{262}{}{Uh-uh}
{263}{}{Ty dávat svojí matka polibek s touhle drzá huba?}
{264}{}{Radši bys po mì NEMÌL støílet. Støílení po mì mne dovede NASRAT.}
{265}{}{Já jít pryè a najít a mluvit s nìkdo, kdo nebıt taková hajzl.}

# 6. WRIGHT ANGRY, NOT GONNA TAKE ANYMORE BULLSHIT (WTG, 5, 14, 19, 32, 34)
{275}{}{(Kdy Tì vidí, zaène Pan Wright cenit zuby a zaèíná køièet.) }
{276}{}{(Pan Wright zaèíná cenit zuby a zaèíná pokøikovat.) }
{277}{}{Chlapci! Máme tu návštìvu, která chce najít místo posledního odpoèinku v Golgotì! Pojïte sem!}
{278}{}{Pojïte sem chlapci! Budeme si hrát}
{279}{}{Hehee, a teï vytrvejte…!}
{280}{}{To je ONO! Je mi z Tebe špatnì, ty hovne. Ne se sem tvı chlapeèci dobelhají, tak u budeš dávno mrtvej.}
{281}{}{Nedostanou se sem vèas, aby Ti zachránili kùi...}
{282}{}{Promiò. Asi pùjdu hledat vıchod.}

# 7. ACTUALLY, I SEEM TO HAVE ENTERED THE WRONG ROOM. PARDON ME. (4, 8, 9, 10, 13, 14, 16, 17, 43)
{290}{}{Jo, moná by si RADŠI mìl odejít, a to svinì. Jestli tu budeš ještì za pìt sekund, tak uvidíš ten tanec, slyšel si dobøe?}
{291}{}{Jo, vypadá to, e máš ve zvyku nìkam vejít a pak odejít. Moná bychom se mìli o tenhle tvùj problém postarat.}
{292}{}{U odcházím.}
{293}{}{Co tím mysl--?}
{294}{}{Lépe bych to neøekl. Pravı èas na umírání.}

# 8. I AM A SIMPLE TRAVELER (4)
{300}{}{ádnej padouch? (usmívá se.) Dobøe, tìší mì, e tì poznávám, "obyèejnej pocestnej." Jsem rád, e ses tu zastavil, sousede. (Jeho úsmìv mizí a zaèíná se mraèit, kdy si tì zaèíná úpìnlivì prohlíet.) Hledáš práci u klanu Wrightù, jo?}
{301}{}{ádnej padouch? (usmívá se.) Dobøe, tìší mì, e tì poznávám, OTROKÁØI. Jsem rád, e ses tu zastavil, sousede. (Jeho úsmìv mizí a zaèíná se mraèit, kdy si tì zaèíná úpìnlivì prohlíet.) S takovıma, jako seš ty, nechci mít nic spoleèného, take odtud hezky rychle vypadni!}
{302}{}{Ano, já --}
{303}{}{Vypadá to, e jsem vstoupil do nìjakı špatny místnosti. Promiòte mi.}
{304}{}{Vydr minutku, ještì jsem neskonèil s Tebou rozhovor. Já…}
{305}{}{Jasnì. Vypadá to, e asi pùjdu.}

# 9. I AM (4)
{310}{}{ádnej padouch? (šklebí se.) Mnoo, tìší mì, e tì poznávám, "}
{311}{}{Ano, já --}

# 10. I'M LOOKING FOR A JOB. (8, 9)
{320}{}{To, co se stalo, se stalo Wrightovu klanu. Krev zbarví všechnu vodu. (mraèí se.) }
{321}{}{Co tì vede k myšlence, e bych chtìl do svého klanu takového cizince, jako seš ty? Mám všechny gorily, kterı potøebuju.}
{322}{}{Co tì vede k myšlence, e bych potøeboval kus takovı cizáckı dìvky, jako seš ty, v mım klanu? Mám dost kurev, kterı by vyssáli celou Severní Kalifornii.}
{323}{}{Tak mì tedy vyzkoušej. Dovol mi splnit nìjakı úkol.}
{324}{}{Vypadá to, e jsem pøišel na špatnı místo. Radši pùjdu.}

# 11. GIVE ME A TEST (10)
{330}{}{(Na chvíli Tì studuje.) Mno dobøe. Moná to, e nejsi ze ádného klanu, mùe bıt docela vıhoda. (mraèení ustupuje.) Máš dìti?}
{331}{}{Pokud vím, tak ne.}
{332}{}{Pokud vím, tak ne. Ale moná bych si vzpomnìl.}

# 12. NOT TO MY KNOWLEDGE (11)
{340}{}{Jeden z mıch synù…mùj chlapec, Richard, mì opustil. Pøedávkoval se. Jetem.}
{341}{}{Jak mùu pomoci?}
{342}{}{Ehm…já opravdu nevím, jak bych mohl po --}

# 13. HOW CAN I HELP? (12)
{350}{}{Chci vìdìt, kterej dealer dal tu sraèku Richardovi a pøinutil ho si to vzít. Pokadé, kdy jsem poslal své chlapce, aby nìco zjistili, tak se vrátili s prázdnou. Moná nìkdo, kdo nemá Wrightovskou krev, by mohl najít ty správné odpovìdi.}
{351}{}{Ehm, "pøinutili ho si to vzít?"}
{352}{}{Jo vezmu tu práci.}
{353}{}{Ne, tahle práce mi smrdí. Radši pùjdu pryè.}

# 14. FORCED HIM TO TAKE IT? (13)
{360}{}{(Oblièej zrudl.) Moji hoši jsou èistí a ví, e se od tıhle sraèky mají dret dál, protoe bych je musel zabít. Take náhodou, Richie trochu bral. Nìkdo do nìj nadopoval hromadu Jetu a to tolik, a mu z nosu byl ten Jet cítit.}
{361}{}{Dobøe…to ale neznamená, e je za to nìkdo zodpovìdnı. Váš syn si mohl vzít toho trošièku víc. Jet je hodnì návykovej.}
{362}{}{Hmmm. Vezmu tu práci.}

# 15. I'LL DO IT (13, 14)
{370}{}{(kıvá hlavou.) Dobøe tedy. Podívej: Najdeš toho zkurvysyna, kterej zabil mıho syna, ani se ho nedotkneš, jenom pøijdeš zpátky a øekneš mi jméno toho u teï mrtvıho chlapa. (v oèích mu jiskøí.) Já se o to potom odtud postarám.}
{371}{}{Nemluvili jsme ještì o cenì.}
{372}{}{Nìjaké rady?}
{373}{}{Najdu tu osobu, která mu dala ten Jet, neublíím jí, jenom pøijdu zpátky a øeknu ti, kdo to je. Chápu.}

# 16. TALKED PRICE (13)
{380}{}{Ano, správnì, nemluvili jsme o cenì, protoe jsi ještì kromì kecù nic neudìlal. Je to pro Tebe zkouška. Udìlej svojí práci a nebudeš mít o peníze nouzi. Dávam ti slovo Wrighta.}
{383}{}{Tak na to zapomeò. Jedinì blbci dìlají práci zadarmo. Já odtud padám.}

# 17. LEADS? (15, 16)
{390}{}{(v oèích se zajiskøilo.) Ne…všichni se bojí promluvit…s nìkım z Wrightù. Kdybych byl Tebou, poloil bych otázku nìkomu, kdo obchoduje s drogami v Renu a dávej dobrı pozor, co ti øeknou. e Jet pøichází ODNÌKUD.}
{391}{}{Podezøíváš nìkoho z obchodníkù s drogami?}
{393}{}{Hele, podívej, tahle práce není podle mého gusta. Radši pùjdu.}

# 18. YOU FIND OUT WHO KILLED MY SON? (WTG)
{400}{}{Zase ty. Zjistil jsi, kdo zabil mého syna?}
{401}{}{Zatím ne. Pracuju na tom.}
{402}{}{Jo, byl to Jules, dealer Jetu na zaèátku mìsta.}
{403}{}{Poøezanej Jimmy J, dealer Jetu na Druhı.}
{404}{}{Ten starej parchant, Renesco Rakeák.}
{405}{}{Malej Jeíš Mordino. On distribuuje Jet.}
{406}{}{Tvùj syn nezemøel na pøedávkování. Byl otráven.}

# 19. NAMED A KILLER, EXCEPT KILLER DEAD (18, 47)
{415}{}{Tenhle? Pøísahám, ze je ten bastard u teï MRTVEJ, ale to ti neøíkám nic nového. ØÍKAL jsem Ti, aby ses ho ani nedotkl - hajzle. Teï seš mrtvej.}
{416}{}{Poèkej --}
{417}{}{No, tak do toho --}

# 20. NAMED A KILLER, KILLER IS ALIVE (18, 47)
{425}{}{Ten bastard má dneska poslední den ivota. Pøijï ráno, u bude mrtvej. Ale bude umírat pomalouèku…}
{426}{}{No, a co nìco za dobøe vykonanou práci…}
{427}{}{Aspoò si to zaslouí.}
{428}{}{Ale, Renesco nedal ten Jet Richardovi...on nevìdìl, pro koho to mìlo bıt...to byli SALVÁTOØI, kteøí otrávili tvého syna.}

# 21. PRICE (20, 50, 51)
{435}{}{Jsem ti dlunej…jsem ti dlunej. }
{436}{}{Dobøe, ne se dostaneme k podrobnostem, nejdøíve musím vyovnat svoje úèty… }
{437}{}{Tady máš nìjaké peníze, støelivo, likér z mé soukromé vıroby… a jestli chceš, tak i další prácièku, jestli tì to zajímá.}
{438}{}{Zajímá.}
{439}{}{Ne díky. Snad se nìkdy tady ukáu.}

# 22. NOT YET (MURDER) (18, 52)
{445}{}{Jestli se sem vrátíš a nebudeš mít hotovo, oè jsem Tì ádal, uvidím Tì viset v Golgotì, cizinèe. NIKDO nebude plıtvat mım èasem. Pochopils mì?}
{446}{}{Jestli si myslíš, e mùeš se mnou takhle tøískat o podlahu, cizinèe, tak to seš teda na pìknım omylu. Nakopu Ti pìknì prdel. (Zaèíná pokøikovat.) Chlapci! Pojïte sem!}
{447}{}{Pochopil.}
{448}{}{Nejsem ten pravej na tuhle práci, pane Wrighte. Najdìte si nìkoho jinıho.}
{449}{}{Seru na tuhle zkurvenou práci, seru na tvıho zdrogovanıho synáèka a seru i na Tebe. Já odtud padám.}
{451}{}{To je ONO! Tohle mi chybìlo. Pøidáš se ke svımu chcíplımu pøedrogovanımu synáèkovi do pekla.}
{453}{}{Padám odsud.}

# 24. WHAT KIND OF PROPOSITION? (21, 29)
{465}{}{Take, pøednedávnem, dostala se mi do rukou mapa, na které je zakreslená stará vojenská základna v horách nedaleko odtud. Najdi k ní cestu a uvidím, e se mùeš postarat u o všechno…}
{466}{}{Oukeej Dokeej Pane Ordervile}
{467}{}{ jdi. }
{468}{}{Jasnì. Jdu to omrknout.}
{469}{}{Proè bych tam mìl jít? Neposílal jsi tam u nìkoho jiného?}
{470}{}{Tak tam nejdu, díky. Nashle.}
# extra 24
{471}{}{Dokázal jsem se dostat dovnitø a našel jsem mnoho starıch zbraní a rùzného vojenského materiálu, jenom to všechno sebrat.}
{472}{}{Dostal jsem se do té základny, ale stala se taková menší…nehoda…ta základna je teï kontaminovaná.}

# 25. YOU ALREADY SENT SOMEONE, DIDN'T YOU . . . (24)
{480}{}{(Vıraz pana Wrighta na moment ztuhne, pak si odfrkne.) Heh. No to ne. Ty lidi, od kterıch tu mapu mám u jsou mrtví.
 Byli to ostøí hoši, ale všichni byli zabiti, kdy se pokoušeli dostat do té základny.}
{481}{}{Oni se vùbec nedostali dovnitø?}

# 26. YOU ALREADY SENT SOMEONE, DIDN'T YOU . . . (25)
{485}{}{Mnoo, jedinej, kdo to pøeil a vyprávìl mi to…krátce pøed svojí smrtí…øíkal, e tam byli nìjaké super støílny stráící vchod, které rozprášily všechny jeho mue.}
{486}{}{Co se stalo tomu mui, co pøeil?}
{487}{}{Hmmmm. Tak to budu muset bıt opatrnı. Vezmu tu práci.}
{488}{}{Zapomeò na to. Nikdo mi neøíkal, e to bude tak nebezpeènı.}

# 27. WHAT HAPPENED TO THE ONLY SURVIVOR? (26)
{495}{}{Oh, starej Sam Pritchard? Smutnej pøíbìh. Jeden veèer se poøádnì zboural, zmínil se mému chlapci Keithovi, e tu základnu najde a jak u víš, nakreslil mi mapu a pak zemøel. Teï spí v Golgotì.}
{496}{}{Vypadá to, e Reno je v tìchto dnech plné smutnıch pøíbìhù. Tu práci beru.}
{497}{}{Víš, tyhle pøíbìhy jako je tenhle mi nahání hrùzu. Opravdu tu práci nemùu vzít. Zatím, Wrighte.}

# 28. REFUSE (21, 26, 27, 29)
{505}{}{(Kroutí hlavou.) To je špatnı. Pøijï za mnou, a si to rozmyslíš.}
{506}{}{Jasnì e.}

# 29. CHANGE YER MIND ABOUT THE BASE? (WTG)
{515}{}{(Wright se smìje, kdy tì vidí.) Rozmyslel sis to po té smutné historce, kterou jsem Ti øíkal?}
{516}{}{Jaká, e to byla ta historka?}
{517}{}{Ne, jenom jsem se tady zastavil. U zase jdu.}

# 30. AGREE CRACK OPEN BASE (24, 26, 27)
{525}{}{(Kıvá, usmívá se.) Dobøe. Vra se, a najdeš tu cestu a já tì štìdøe odmìním. No a teï teda ta základna se nalézá…jdi na sever, pak… (Zapisuje Ti koordináty vojenské základny.)}
{526}{}{Dobøe. Jdu na to. A najdu ten vchod dovnitø, tak se vrátím.}

# 31. YOU FIND THAT ARMY BASE? (X)
{535}{}{Aa, to jsi ty. Máš pro mì nìjaké novinky? Našel jsi cestu do té vojenské základny?}
{536}{}{Jestli seš tu zpátky a neudìlal jsi, oè jsem Tì ádal, pak si koleduješ o poøádnej vejprask.}
{537}{}{Ještì ne.}
{538}{}{Ano. Dokázal jsem se dostat dovnitø a našel jsem mnoho starıch zbraní a rùzného vojenského materiál. Všechno je to tøeba jenom sebrat. A teï mi zapla…}
{539}{}{Dostal jsem se do té základny, ale stala se taková menší…nehoda…ta základna je teï kontaminovaná.}
{540}{}{Sorry. Vrátím se zpìt, a se dostanu do té vojenské základny.}
{541}{}{Seru na tenhle dob a seru i na Tebe. Padám odtud.}

# 32. NOT YET. (31)
{550}{}{Jestli jsi NEUDÌLAL, oè jsem Tì ádal, tak co tu k èertu zpátky dìláš?! Potøebuju, aby ses dostal do té základny, take se nevracej, dokud tohle nedokonèíš!}
{551}{}{Jasnì. Vrátím se, a se dostanu do té vojenské základny.}

# 34. SORRY . . . (WARNING) (31)
{560}{}{Jestli se sem vrátíš a neudìláš, oè jsem Tì ádal, tak tì povìsím v Golgotì, cizinèe. NIKDO nebude plıtvat mım èasem. Rozumìls mi?}
{561}{}{Sorry? SORRY?! Tak tohle mi teda nestaèí, cizinèe. Jestli si myslíš, e mùeš takhle plıtvat mım èasem, tak to seš na pìknım omylu. Na tu práci si mùu najít nìkoho schopnìjšího. (Køièí ke dveøím.) Chlapci! Pojïte sem!}
{562}{}{Pochopil. Vrátím se a dodìlám tu prácièku.}

# 35. MADE MAN (31)
{575}{}{. To se mi líbí, to se mi fakt líbí. Má to styl a šávu. A teï se zastav v Koèièí Pacce a v obchodì se zbranìmi, tam se o tebe postarají. A jestli chceš nìjakı chlast zdarma, zajdi na eleznièní stanici. Dám jim vìdìt.}
{576}{}{Dík. udìlám to.}

# 37. REWARD/LOSS (SIERRA ARMY BASE) (31)
{580}{}{(Lesknou se mu oèi.) Dobrá práce, }
{581}{}{Nehoda?' Eh sakra, to mì nezajímá. Zmiz odsud a u se nevracej.}
{582}{}{Díky pane Wrighte. Kdy jsem teï èlenem vaší Rodiny, chci abyste mì nazıvali…}
{583}{}{Tak dobrá.}

{584}{}{Take jak chceš abychom Ti øíkali?}

# 38. REP: MADE MAN INTRO (WTG)
{590}{}{(Smìje se na tebe.) }
{591}{}{Jistì. Jak se máte, pane Wrighet?}
{592}{}{Jistì. Jen jsem vás chtìl vidìt pane Wrighte. Mìjte se pane.}

# 39. HOW ARE THINGS WITH YOU, MR. WRIGHT? (38)
{600}{}{(Pochichtává se.) Ujde to, docela to ujde. Moje paní mì láskyplnì terorizuje , ale to není nic nového. To jsou halt ty radosti manelství.}
{601}{}{Rozumím. Jen jsem vás chtìl vidìt pane Wrighte. Mìjte se pane.}

# 40. MY WIFE JUST BUSTED UP ONE OF MY CELLS (38)
{610}{}{Naštvanej? To teda jo, sakra. Ta moje bláznivá manelka v záchvatu zuøivosti roztøískala jeden z našich destilátorù. Sice nechápu jak na nìj sakra mohla pøijít, ale…}
{611}{}{Naštvanej? To teda jo, sakra. Nìjakı zkurvysyn znièil jeden z našich destilátorù. To by mì zajímalo jak ho ten bastard našel…}
{612}{}{Naštvanej? To teda jo, sakra. Moji zákazníci jaksi, øeèeno literárnì... odcházejí. Nìco se s tím alkoholem dìje a já myslím, e to zabíjí lidi. Moná, e pøi fermentaèním procesu vzniká jed...}
{613}{}{Asi na nìj narazila jen náhodou. Zatracená pitomá smùla! Nemyslím, e by jí to nìkdo vykecal. Velmi nemilé.}
{614}{}{No, ty mizernı zastaralı mašiny jsou poøád porouchanı! Nemyslím ale, e by v tom mìl nìkdo prsty. Velmi nemilé.}
{615}{}{No, ale urèitì to nemá co dìlat s radškorpióním jedem, kterı do nádrí unikl z nìkolika škorpióních bodcù, které tam spadly. Tomu nevìøím.}

# 41. MY SON GOT A GUN FROM SOMEWHERE (38)
{620}{}{Legraèní, e se na to ptáš. Mùj syn opravdu mìl odnìkud zbraò…myslím, e jí vzal nìkomu z jiné Rodiny kdo chtìl jeho nebo mì odprásknout. Kdybych toho bastarda dostal do ruky…}
{621}{}{Uh, zbraò? Opravdu? Máte pravdu pane, urèitì mu to dal nìkdo z jiné Rodiny. Ale bude tìké zjistit, kdo to udìlal. Pokusím se to zjistit.}

# 42. PROB NOTHING . . . (40, 41)
{625}{}{(Pokyvuje hlavou.) Asi nic. No…}
{626}{}{Jistì. Jen jsem vás chtìl vidìt pane Wrighte. Mìjte se pane.}

# 43. PUSHERS YOU SUSPECT? . . . (17)
{630}{}{(Mraèí se.) Jak já to vidím, tak v tom mají prsty Mordinovci…ty zatracenı hajzlíci kontrolují témìø všechen Jet v New Reno. Já bych propátral kasino Desperado a mrknul se na ty dealery co se tam okolo potloukají.}

# 44. POISONED . . . (18)
{640}{}{Co -? "Otráven?" O èem to tady k èertu mluvíš?}
{641}{}{Prohledal jsem tìlo tvého syna. Jet ho nezabil...na jeho tìle jsou stále stopy po radškorpioním jedu.}
{642}{}{Našel jsem plechovku od Jetu, kterou Richard pouívá… ehm, Richard pouíval. Jsou na ní stopy po radškorpioním jedu.}
{643}{}{Našla jsem plechovku od Jetu, kterou Richard pouívá… ehm, Richard pouíval. Jsou na ní stopy po radškorpioním jedu.}
{644}{}{Byl otráven radškorpioním jedem. Pøedávkování Jetem mìlo pouze zakrıt skuteènost, e byl otráven.}

# 45. MY SON'S BODY . . . (44, 52)
{650}{}{"Prohledal tìlo mého syna?"}
{651}{}{No jasnì, musel sem otevøít jeho rakev, abych udìlal pitvu.}
{652}{}{Ehm…to víš, e neprohledal. Já se jenom pøeøekl. "Tìlo tvıho syna?" Myslel jsem "tìlo tvıho psa." Ano, to je to, co jsem myslel.}
{653}{}{Mno, teï není nejlepší doba o tomhle diskutovat. Promluvíme si pozdìji.}

# 46. SON'S BODY, DEAD . . . (45)
{660}{}{Ty ghoulskej èubèí synu…}
{661}{}{Ty ghoulská dìvko…}
{662}{}{ právì si nacházíš místo svého posledního odpoèinku. Nikdo nikdy nenajde kousek tvıho mizernıho tìla. (Zaèíná pokøikovat.) Chlapci! Pojïte sem!
 A vemte si noe!}
{663}{}{Poèkej! Nemùeme si o tom promluvit?}
{664}{}{To budete potøebovat víc, ne jenom noe, aby jste mì dostali…}
{665}{}{Promiò. Asi budu muset rychle vypadnout.}

# 47. VENOM FOUND . . . (44)
{670}{}{Pøedpokládejme, e bych tomu na okamik uvìøil... ale neøíkám, e vìøím... tak kdo potom OTRÁVIL mého syna? A proè si dali takovou práci, e ho pøedávkovaly Jetem?}
{671}{}{Vsadím se, e to byli Salvatoøi. Nadopovali ho Jetem smíchanım s radškorpioním jedem a pak ho tu nechali, aby si ho našel.}
{672}{}{Nevím, kterı ze Salvatorù to udìlal. Renesco pro nì pøipravil dávku Jetu, nevìdouce o tom, e by to mohli pouít k otrávení tvého syna.}
{673}{}{Nevím.}

# 48. VENOM FOUND . . . (20, 47)
{680}{}{A proè by to k sakru dìlali?}
{681}{}{Jak to já vidím, Mordino ovládá vırobu Jetu v Renu. Pøirozenì bys z pøedávkování svého syna obvinil jeho... a pak by zaèala válka. Pokud byste se vy dva navzájem nevyvradili, tak byste urèitì byli bojem vyèerpáni. To by Salvatorùm náramnì usnadnilo ivot…jedinı, koho by se potom obávali, by byli Bishopovci.}
{682}{}{To nevím. Moná by ses jich mìl zeptat.}

# 49. SOLUTION . . . (48)
{690}{}{(Civí na tebe dlouhou dobu, pak se hoøce usmál.) Pšinášíš mi odpovìï, ale já s ní nemùu nic udìlat. Ti zatracení Salvatoøi. (Hluboce si oddechuje.)}
{691}{}{Co se stalo?}
{692}{}{"Ty s tím nic nemùeš udìlat?" Co tím myslíš?}

# 50. PROBLEM . . . (49)
{700}{}{Víš pøíteli, s èím jsou ti Salvatorští bastardi VYZBROJENI? Tìma zatracenıma laserovıma pistolema. Jeden SALVATOR s touhle vìcièkou mùe zabít celou mojí rodinu bez mrknutí oka. Porazit je, potøeboval bych…}
{701}{}{Co?}
{702}{}{Nedìlej si s tím starosti, u jsem od Salvatorù dostal nakopáno dost.}

# 51. SALVATORES . . . (50)
{710}{}{Ha! To jsou Ti z Rena, máš se ještì hodnì co uèit o klanech... Salvatorové se stále potloukají kolem Rena a v jeho blízkosti a dokonce, kdy potkáš jenom jednoho z nich, tak máš velkej problém. Abych je porazil, potøeboval bych...}

# 52. I DON'T KNOW . . . (47)
{720}{}{(Hluboce se mraèí.) Tohle smrdí jako hromada brahmíních hoven...}
{721}{}{Nevìøíš mi? Podívej, prohledal jsem tìlo tvého syna a to PÁCHLO po jedu z radškorpiona.}
{722}{}{Podívej, vìø mi... tvùj syn byl OTRÁVEN. Nevím, kdo to udìlal, ale ten nìkdo si dal velkou práci s tím, aby to vypadalo, jako pøedávkování Jetem.}

{750}{}{Vyøešil jsi vradu.}
{775}{}{Vyslovil jsi podezøení ohlednì smrtí Richarda Wrighta.}
{800}{}{Správnì jsi identifikoval, kdo zabil Richarda Wrighta i motiv této vrady.}
{825}{}{Stáváš se pøíslušníkem Wrightova klanu.}

# END LINES
{5243}{}{!}
{5249}{}{. Hledám èlovìka na nìjakou prácièku.}
{5261}{}{!}
{5310}{}{." Jsem rád, e se chceš vykašlat na ty ostatní bastardy. (Zamraèenì se na tebe šklebí.) Tak ty chceš pracovat pro Wrightovic Rodinu, jo?}
{5467}{}{ mizernej bastard. }
{6467}{}{ bezva!}
{5580}{}{. Zajdi do Koèièí Packy a obchodu se zbranìmi…øekni jim, e tì posílám a oni se o tebe postarají. Jsi teï èlenem naší Rodiny, tak a to ví celı New Reno.}
{5590}{}{…zacházejí s tebou všichni s úctou? Nemáš nìjaké problémy?}
