#tento soubor pøeloil Somnambulus...somnambulus@hotmail.com
# 0. QUICK LOOK (ANY)
{100}{}{Vidíš jednoho z obyvatel New Reno.}

# 1. LOOK, MALE (WTG)
{150}{}{Vidíš nìjakého otrhance. Tváøí se znudìnì.}
{151}{}{Vidíš chlápka ve špinavıch hadrech. Má tupı pohled a od koutku úst mu odkapává slina.}
{152}{}{Vidíš mue ve špinavıch cárech. Vypadá to, e má pìknou kocovinu.}
{153}{}{Vidíš mue ve špinavıch a páchnoucích hadrech. Vrávorá, asi je opilı.}
{154}{}{Vidíš mue v nìèem, co kdysi bıvalo oblekem. Vìnoval ti podrádìnı pohled a teï u jsi pro nìj vzduch.}
{155}{}{Vidíš mue v hadrech, které lze stìí nazvat odìvem. Vypadá to, e se právì pochcal.}

# 2. LOOK, FEMALE (WTG)
{160}{}{Vidíš enu v otrhanıch šatech. Tváøí se znudìnì.}
{161}{}{Vidíš dívku ve špinavıch hadrech. V oèích má prázdnı pohled.}
{162}{}{Vidíš enu ve špinavıch cárech. Vypadá to, e je duchem nepøítomná.}
{163}{}{Vidíš enu ve špinavıch a páchnoucích hadrech. Asi je opilá.}
{164}{}{Vidíš dívku v potrhanıch šatech. Zbìnì tì pøejela pohledem a teï u jsi pro ní vzduch.}
{165}{}{Vidíš enu ve zbytcích odìvu, sotva zakrıvajících holé tìlo. Kdy zachytila tvùj pohled, opovrlivì se ušklíbla.}

# 3. FLOAT (ANY) TO [FLAG: ENCLAVE DESTROYED] (WTG)
{200}{}{::Tleská ti::}
{201}{}{::Mává na tebe::}
{202}{}{Cestu pro pokoøitele Enklávy! Uvolnìte cestu!}
{203}{}{Sláva! Vivat! A ije }
{204}{}{Díky ti za znièení tìch bastardù z Enklávy, }
{205}{}{Podívejte, tamhle jde Pokoøitel Enklávy. To je }

# 4. FLOAT (ANY) TO [POWER ARMOR] (WTG)
{215}{}{Uh-oh. Hned ti uvolním cestu.}
{216}{}{Jen se na nìj... na ní... na to... nebo co tam uvnitø vlastnì je, podívejte.}
{217}{}{Myslíte, e má tahle vìc nìkde uzávìr?}
{218}{}{Prı je uvnitø tı vìci èlovìk... no jo, já si taky myslím, e je to nesmysl.}
{219}{}{Radši tı vìci ustupte z cesty.}
{220}{}{::Nìco si pro sebe ohromenì šeptá::}
{221}{}{::Nasucho polyká::}
{222}{}{Zase zemìtøesení? Jo aha, to dìlá tamhleten chodící tank.}
{223}{}{Jeišikriste, ono se to na mì podívalo. Rychle pryè odsud.}
{224}{}{Prı tahle vìc pøedevèírem roztrhala na kusy tøi zabijáky.}

# 5. FLOAT AND CLICK (FEMALE) TO [MALE, PORN STAR] (WTG)
{240}{}{Ahoj brouèku...}
{241}{}{Nechceš si zacválat høebeèku? Zítra v noci mám volno.}
{242}{}{Máš dneska veèer èas, fešáku?}
{243}{}{Mùu si sáhnout na tvoje svaly?}
{244}{}{Jak to dìláš, e nepøepadneš dopøedu, kdy se ti postaví?}
{245}{}{Nechceš zajít ke mnì domù na sklenièku?}
{246}{}{::Svùdnì na tebe mrká::}
{247}{}{Nepotøebuješ partnerku pro svùj pøíští film?}
{248}{}{::Obdivnì zírá na tvoje bicepsy.::}
{249}{}{::Tleská ti a nadšenì hvízdá::}

# 6. FLOAT (MALE) TO [FEMALE, PORN STAR] (WTG)
{255}{}{Jeiši. Vidíte to co já, hoši?}
{256}{}{Pojï blí koèièko. Nechceš se podívat na TOHLE?}
{257}{}{::mumlá si pro sebe 'sakra.'::}
{258}{}{Proè já vùl se dneska neoholil...}
{259}{}{Rád bych si s tebou na chvilku popovídal. Nebo jestli nemáš èas, tak staèí s tvıma kozama.}
{260}{}{Takovı krásnı dudy mají dneska u jen divošky!}
{261}{}{Kouknìte jak se ta divoška nese. Sááákra to jsou vlny.}
{262}{}{Hergot na tıhle koèièce bych fakt rád hledal, kde nechal tesaø díru.}
{263}{}{Kvùli tıdle enskı bych se dokonce i umyl.}
{264}{}{To je poprvé, co jí vidím s nohama u sebe.}
{265}{}{Zatøes s nima, bejby!}
{266}{}{Vidìl jsem jí ve filmu. Ta jí má snad motorovou.}
{267}{}{::Píská na tebe::}
{268}{}{Hej holka, nepotøebuješ nìkde nìco ucpat?}
{269}{}{Hej krásko, u jsi pro tu svojí kundièku našla dost velkej jazyk?}
{270}{}{Máš zítra veèer èas, krásko? Ukáu ti svojí sbírku prezervativù.}
{271}{}{Kdy budeš mít vystoupení v kasinu?}
{272}{}{Vidìl jsem tvùj poslední film, zlato. Fakt maso. Ještì teï mám erekci.}
{273}{}{Omluv mì na chvilku. Musím si odskoèit na záchod a ehm... pøeèísnout si vlasy.}
{274}{}{Jestli jsou ty její cecky zpùsobenı mutací, zaènu studovat genetiku.}
{275}{}{Chtìl bych bıt jejím spodním prádlem.}
{276}{}{Chtìl bych èichat k jejím kalhotkám.}
{277}{}{Tomuhle øíkám ENSKÁ.}
{278}{}{Doprèic. Skrz ty její zatáèky bych teda chtìl projet bez brzd.}
{279}{}{Kdybych nevìdìl, e se silikon u léta nevyrábí, nevìøil bych, e je to pøírodní!}
{280}{}{Tak k tıhle kvìtince bych si chtìl pøivonìt!}
{281}{}{Máš nádhernì velkı... oèi.}
{282}{}{Zatracenì.}
{283}{}{Sledujte ty køivky. Do hajzlu, na tıhle bych rád provedl topologickej prùzkum.}
{284}{}{Divím se, e nepøepadne dopøedu.}

# 7. FLOAT AND CLICK (ANY) TO [MALE, PRIZEFIGHTER] (WTG)
{285}{}{Nevypadáš zas a tak drsnì šampióne.}
{286}{}{Vyhrál jsi mi 20 doláèù! Díky borèe!}
{287}{}{Nazdar hrdino! Ten tvùj poslední zápas byl skvìlej!}
{288}{}{Vidìt tì v ringu, to je poezie. Máš zatracenì dobrej pravej hák.}
{289}{}{Nezklameš mì, e ne? Chci na tebe vsadit 30 babek.}
{290}{}{Kolik hodin dennì trénuješ?}
{291}{}{Kde ses tak vypracoval?}
{292}{}{Dej si bacha na dímaèku. Má slabost pro uši.}
{293}{}{Mám chu ti koupit panáka... a i bych to udìlal, nepøijít o všechny prachy sázkou na tvoje soupeøe.}
{294}{}{Jsi menší ne ses zdál v ringu.}
{295}{}{Mùu si sáhnout na tvoje svaly?}

# 8. FLOAT (ANY) TO [MADE MAN] (WTG)
{300}{}{Tomuhle èlovìku se radši kliïte z cesty.}
{301}{}{Myslím, e se na mnì podíval.}
{302}{}{Doprdele, on se na mì podíval. Rychle pryè odsud.}
{303}{}{Prı pøedevèírem sejmul jednou ranou tøi zabijáky.}
{304}{}{Staèí, kdy se na nìj podívám a rozklepou se mi kolena.}
{305}{}{Myslíte, e hledá nìjakou obì?}
{306}{}{A sakra. Radši se nìkam odklidím.}
{307}{}{::Potichu se modlí::.}
{308}{}{Zdravíèko šéfe. Jak se vede?}
{309}{}{::Drkotá zuby::}
{310}{}{Brutální Nikita byla proti ní Matka Tereza.}
{311}{}{Staèí, kdy se na ní podívám a rozklepou se mi kolena.}
{312}{}{Myslíte, e hledá nìjakej terè ke støelbì?}
{313}{}{Myslím, e se na mnì podívala.}
{314}{}{Doprdele, ona se na mì podívala. Rychle pryè odsud.}
{315}{}{Prı pøedevèírem sejmula jednou ranou tøi zabijáky.}
{316}{}{A do prdele! Uh, pardon.}

# 9. FLOAT (ANY) TO [SLAVER] (WTG)
{320}{}{Kde se tu poslední dobou všichni ti otrokáøi berou?}
{321}{}{Hele, to je nìjakej novej otrokáø...}
{322}{}{Vsadím se, e tenhle otrokáø má zamíøeno do Stájí...}
{323}{}{Divil bych se, kdyby mìl tenhle otrokáø nìjakı zboí na prodej...}
{324}{}{Hledáš Stáje, otrokáøi?}
{325}{}{DALŠÍ otrokáø. Starej Mordino si snad nìkde musel otevøít zlatej dùl...}
{326}{}{Otrokáøi jsou nejlepší dodavatelé... pro Golgothu.}
{327}{}{Minulou noc byl ten smrad z Golgothy k nevydrení...}
{328}{}{Odporní otrokáøi...}
{329}{}{Zatracená smùla...}
{330}{}{Prı má dorazit nová karavana otrokù.}
{331}{}{A hele otrokáø. Tak to urèitì brzy dostanou v bordelech èerstvou zásilku.}
{332}{}{::Stranou si uplivuje::}
{333}{}{Rozbiju jim bank.}
{334}{}{Orat se jako prase nìkdy nepomáhá.}
{335}{}{V tìch zatracenejch kasinech by mìly bejt rozcestníky...}
{336}{}{No bezva. Vidìt otrokáøe to je horší ne èerná koèka pøes cestu.}
{337}{}{Všichni se proti mnì spikli.}
{338}{}{Zasraná smùla. Kurvapráce, to byl pech.}
{339}{}{Díky Bohu, e toho chlapa narazili na kùl...}
{340}{}{Špinavej parchant...}
{341}{}{Ti otrokáøi si tu chodí, jako by jim u patøilo celı mìsto...}
{342}{}{Tam se s jedním fakt neserou. Nemáš prachy... jdeš na Golgothu. A pìknì botama napøed.}
{343}{}{Fet je drahej, dìvky samá vyráka, karta mi nepadá a i ten vzduch smrdí. Èasy jsou zlé, Kamile...}
{344}{}{Reno jde pomalu do hajzlu. Nejvyšší èas pohnout se o kus dál.}
{345}{}{Ta Bishopovic holka se chová jak utrená ze øetìzu.}
{346}{}{Jestli mì tu ti kreténi z Protialkoholickı ligy budou otravovat ještì jednou...}
{347}{}{Vèera zas vidìli Otce Tullyho, jak se úplnì oralej válí v pøíkopu.}
{348}{}{Zatracenı svinstvo. Co sem ti parchanti z Denu furt lezou?}
{349}{}{Nejvyšší èas z tohohle mìsta vypadnout.}
{350}{}{To byl pøípad ten závislák. Válel se ve vlastních sraèkách a všude 
po ksichtì mu lezly mouchy. A von se pøitom SMÁL.}
{351}{}{Mám TISÍC chutí z tohohle odpornıho mìsta vypadnout, ale...}
{352}{}{Hej otrokáøi, v tomhle mìstì si radši dobøe hlídej záda...}
{353}{}{Tohle hnusnı mìsto nenávidím. NENÁVIDÍM!}
{354}{}{U v tomhle mìstì iju dlouho... moná a pøíliš dlouho.}
{355}{}{Tohle mìsto je úasnì pohostinnı... zvláš k turistùm.}
{356}{}{Tohle mìsto je úasnì pohostinnı... zvláš k otrokáøùm.}
{357}{}{Tohle mìsto je úasnì pohostinnı... zvláš k pasákùm a dìvkám.}

# 10. FLOAT AND CLICK (ANY) TO [COMPANION: ROBOBRAIN] (WTG)
{365}{}{To je nìjakej herní automat, to co za tebou jede?}
{366}{}{Hele, má ta tvoje mašina vestavìnej i vibrátor?}
{367}{}{Umí ten tvùj robot nìjakı triky? Uh... teda kouzla, myslím.}

# 11. FLOAT (ANY) TO [COMPANION: MARCUS] (WTG)
{375}{}{Tohle pøece není doopravdickej mutant. Nebo jo?}
{376}{}{To je opravdovskej mutant?}
{377}{}{A do prdele. Mutant v New Reno. To nevìstí nic dobrıho.}
{378}{}{Tomuhle teda øíkám poøádnej mutant.}
{379}{}{Smradlavej milovník mutantù...}

# 12. FLOAT (ANY) TO [COMPANION: BONE-NOSE] OR MALE TOWNSPERSON REACTION TO [COMPANION = FEMALE SPOUSE] (WTG)
{385}{}{Hej! Víš o tom, e ten tvùj kámoš má ve fròáku kost?}
{386}{}{To si všichni ve tvı partì strkaj do nosu kost? To je místo pøijímacího pohovoru?}
{387}{}{Ten tvùj kámoš je z nìjakıho speciálního "strè-kost-skrz-nos" kmene?}
{388}{}{Ten tvùj kámoš s kostí v drce je ivım dùkazem toho, e divoch zùstane vdycky divochem.}
{389}{}{To je kost, co má ten tvùj kámoš v nose?}
{390}{}{Panenko skákavá... ta kost, co má ten tvùj kámoš v nose, je velká jak moje ruka.}
{391}{}{Radši mi ani neøíkej, jak ten tvùj pøítel tu kost do toho nosu narval.}
{392}{}{Bezva. To je zrovna jeden z tìch troglodytù, co jsme o nich vèera mluvili.}
{393}{}{Kolik dalších neandrtálcù ještì do tohohle mìsta pøijde?}
{394}{}{No vıbornì. Další opièák.}
{395}{}{Kolik kostí máš v nose, tolikrát jsi èlovìkem.}
{396}{}{Minulou noc byl ten smrad z Golgothy k nevydrení...}
{397}{}{Zasranı turisti.}
{398}{}{Zatracená smùla...}
{399}{}{Prı má dorazit nová zásilka otrokù.}
{400}{}{::Stranou si uplivuje::}
{401}{}{Rozbiju jim bank.}
{402}{}{Orat se jako prase nìkdy nepomáhá.}
{403}{}{V tìch zatracenejch kasinech by mìly bejt rozcestníky...}
{404}{}{Všichni se proti mnì spikli.}
{405}{}{Zasraná smùla. Kurvapráce, to byl pech.}
{406}{}{Díky Bohu, e toho chlapa narazili na kùl...}
{407}{}{Špinavej parchant...}
{408}{}{Tam se s jedním fakt neserou. Nemáš prachy... jdeš na Golgothu. A pìknì botama napøed.}
{409}{}{Fet je drahej, dìvky samá vyráka, karta mi nepadá a i ten vzduch smrdí. Èasy jsou zlé, Kamile...}
{410}{}{Reno jde pomalu do hajzlu. Nejvyšší èas pohnout se o kus dál.}
{411}{}{Ta Bishopovic holka se chová jak utrená ze øetìzu.}
{412}{}{Jestli mì tu ti kreténi z Protialkoholickı ligy budou ještì jednou otravovat...}
{413}{}{Vèera zas vidìli Otce Tullyho, jak se úplnì oralej válí v pøíkopu.}
{414}{}{Zatracenej ivot.}
{415}{}{Tohohle neznám.}
{416}{}{Nejvyšší èas z tohohle mìsta vypadnout.}
{417}{}{To byl pøípad ten závislák. Válel se ve vlastních sraèkách a všude 
po ksichtì mu lezly mouchy. A von se pøitom SMÁL.}
{418}{}{Mám TISÍC chutí z tohohle odpornıho mìsta vypadnout, ale...}
{419}{}{Proè dál zùstávat na takovımhle místì?}
{420}{}{Tohle hnusnı mìsto nenávidím. NENÁVIDÍM!}
{421}{}{U v tomhle mìstì iju dlouho... moná a pøíliš dlouho.}
{422}{}{Tohle mìsto je úasnì pohostinnı... zvláš k turistùm.}
{423}{}{Tohle mìsto je úasnì pohostinnı... zvláš k otrokáøùm.}
{424}{}{Tohle mìsto je úasnì pohostinnı... zvláš k pasákùm a dìvkám.}
{425}{}{Ta enská s tebou je na prodej?}
{426}{}{Kolik chceš za tu tvojí enskou?}
{427}{}{Ta enská, co s sebou táhneš, je docela hezká.}
{428}{}{Umí ta tvoje enská i vaøit? Jestli jo, tak jí koupím.}
{429}{}{Kolik chceš za tu tvojí samièku?}
{430}{}{Helemese, máme tu novıho pasáka.}
{431}{}{Á tady si nìkdo dneska v noci parádnì uije!}
{432}{}{Ta Bishopova panièka má skvìlı nohy.}

# 13. FLOAT [NO REP] (WTG)
{450}{}{Ta Bishopova panièka má skvìlı nohy.}
{451}{}{Jestli mì tu ti kreténi z Protialkoholickı ligy budou otravovat ještì jednou...}
{452}{}{No nádhera. Jako bychom tu u nemìli dost vlastních idiotù.}
{453}{}{Kolik dalších neandrtálcù ještì do tohohle mìsta pøijde?}
{454}{}{No vıbornì. Další opièák.}
{455}{}{Novı maso pro Golgothu.}
{456}{}{Minulou noc byl ten smrad z Golgothy k nevydrení...}
{457}{}{V tı pouštní bouøi èlovìk nevidìl ani vlastní prdel...}
{458}{}{Zasranı turisti.}
{459}{}{Zatracená smùla...}
{460}{}{Prı má dorazit nová zásilka otrokù.}
{461}{}{::Stranou si uplivuje::}
{462}{}{Rozbiju jim bank.}
{463}{}{Orat se jako prase nìkdy nepomáhá.}
{464}{}{V tìch zatracenejch kasinech by mìly bejt rozcestníky...}
{465}{}{Kde se tu ti ztroskotanci poøád berou?}
{466}{}{Všichni se proti mnì spikli.}
{467}{}{Zasraná smùla. Kurvapráce to byl pech.}
{468}{}{Díky Bohu, e toho chlapa narazili na kùl...}
{469}{}{Špinavej parchant...}
{470}{}{Tam se s jedním fakt neserou. Nemáš prachy... jdeš na Golgothu. A pìknì botama napøed.}
{471}{}{Fet je drahej, dìvky samá vyráka, karta mi nepadá a i ten vzduch smrdí. Èasy jsou zlé Kamile...}
{472}{}{Reno jde pomalu do hajzlu. Nejvyšší èas pohnout se o kus dál.}
{473}{}{Ta Bishopovic holka se chová jak utrená ze øetìzu.}
{474}{}{Vèera zas vidìli Otce Tullyho, jak se úplnì oralej válí v pøíkopu.}
{475}{}{Chlastat tohle svinstvo chce odvahu... ještì, e jí mám.}
{476}{}{Tebe neznám. Ty urèitì nejsi odtud.}
{477}{}{Nejvyšší èas z tohohle mìsta vypadnout.}
{478}{}{To byl pøípad ten závislák. Válel se ve vlastních sraèkách a všude 
po ksichtì mu lezly mouchy. A von se pøitom SMÁL.}
{479}{}{Mám TISÍC chutí z tohohle odpornıho mìsta vypadnout, ale...}
{480}{}{Proè dál zùstávat na takovımhle místì?}
{481}{}{Tohle hnusnı mìsto nenávidím. NENÁVIDÍM.}
{482}{}{U v tomhle mìstì iju dlouho... moná a pøíliš dlouho.}
{483}{}{Tohle mìsto je úasnì pohostinnı... zvláš k turistùm.}
{484}{}{Tohle mìsto je úasnì pohostinnı... zvláš k otrokáøùm.}
{485}{}{Tohle mìsto je úasnì pohostinnı... zvláš k pasákùm a dìvkám.}
{486}{}{Asi se mrknu do centra, jestli nedorazili nìjakı turisti...}
{487}{}{Jestli mì tu ti kreténi z Protialkoholickı ligy budou otravovat ještì jednou...}

# 14. CLICK (ANY) TO [FLAG: ENCLAVE DESTROYED] (WTG)
{490}{}{Místo pro hrdinu, kterej smetl ty bastardy z Enklávy! Uvolnìte cestu!}
{491}{}{Já to poøád øíkal, e nás chce prezident všechny zlikvidovat.}
{492}{}{Prezident pøeil Válku? Kdy byly naposled volby??}
{493}{}{Cestu pro pøemoitele Enklávy! A ije }
{494}{}{Mnì osobnì teda Enkláva nikdy nic neudìlala, ale stejnì je dobøe, e jsou pryè.}
{495}{}{Nechce se mi vìøit, e Enkláva po všech tìch letech poøád ještì vedla válku. Idioti.}
{496}{}{Cítím ve vzduchu velkou zmìnu... jako kdyby stovka ïábelskıch bastardù 
nìkde na ropné plošinì vykøikla hrùzou a pak náhle ztichla. Divné.}
{497}{}{Gratuluju ke znièení Enklávy. Kdo je nejvìtší borec? No pøece }
{498}{}{Tuhle hru ti pøinesl Fallout II CZ tım. Ale e to tìm parchantùm trvalo, co?}
{499}{}{Nekoukej tak na mì. Já za to co øíkám, nemùu. To udìlal Somnambulus. 
Tsss... jak si nìkdo mùe dát tak blbej nick?}
{500}{}{Hele mnì se na nic neptej. Nejvíc prej toho pøeloil Mawerick, ale jinak fakt nic nevím.}
{501}{}{Tu grafiku spoleènì po nocích pøedìlali Radar s Luciferem666. Prej se budou brzy brát.}
{502}{}{Vìø mi, New Reno bylo nejslušnìjší mìsto z celı hry. Ne ho dostal do pracek Birdman...}
{503}{}{Tvoje skóre je 192 bodù z 208. Mìl jsi na Horrigana pouít svùj mutovanej šestej prst.}

# 15. CLICK (ANY) TO [POWER ARMOR) (WTG)
{510}{}{Hledáš svıho brášku Robocopa? Povídám, hledáš svıch...? É, zapomeò na to.}
{511}{}{Stojím ti v cestì? Omlouvám se, neprodlenì opustím mìsto.}
{512}{}{Já dıchám tvùj vzduch? Promiò, hned toho nechám.}
{513}{}{::uká ti na brnìní:: Haló? Je tam nìkdo? }
{514}{}{Kde mám ten otvírák na konzervy? He-he. Ehm... to byl jen fór.}
{515}{}{Hezkı brnìní. Má to i klimatizaci?}
{516}{}{Není ti tam uvnitø horko?}
{517}{}{Èím se maeš elezòáku?}
{518}{}{Uh, zdravím pane...sleèno...a nebo co vlastnì jste.}
{519}{}{Je všechno v poøádku pane...sleèno...uh, nebo co vlastnì jste?}
{520}{}{Zdravím tì, rytíøi Lancelote. Ale ne, hergot, ten pøece vystupuje v jinı høe.}
{521}{}{Ty jsi ta nová herní konzole, co má teï nìkdy pøijít na trh?}
{522}{}{Ne, já ti ty tvoje klouby opravdu nenaolejuju.}
{523}{}{Ty vypadáš, jako kdy ses ztratil cestou do nìjaké té PC hry s Mechama.}
{524}{}{Jo, díky, taky ti pøeju krásnej 'skøíp-vrz-skøíp'.}
{525}{}{Jestli si myslíš, e mi to tvoje brnìní nahání strach... tak máš pravdu.}

# 16. CLICK (MALE) TO [FEMALE, PORN STAR] (WTG)
{540}{}{Jsi na prodej?}
{541}{}{Mohl bych si koupit tvoje šaty? Mám na mysli hned teï.}
{542}{}{Já to vìdìl, e se mám dneska oholit.}
{543}{}{Nedáme øeè zlato? Mám tam vzadu skoro úplnì èistou matraci.}
{544}{}{Ohni, se mnou pojï...}
{545}{}{Roztomilı kozièky, e jo?}
{546}{}{Kvùli tobì bych se klidnì i vykoupal.}
{547}{}{Jestli jsou ty tvoje kozy vısledkem nìjakı mutace, zaènu studovat genetiku.}
{548}{}{To je poprvé, co tì vidím na vlastní oèi. A s nohama u sebe.}
{549}{}{Kdy budeš mít vystoupení v kasinu?}
{550}{}{Omluv mì na chvilku. Musím si odskoèit na záchod a ehm... pøeèísnout si vlasy.}
{551}{}{Chtìl bych bıt tvım spodním prádlem.}
{552}{}{Mùu si èichnout k tvejm kalhotkám.}
{553}{}{Jsi fakt koèka.}
{554}{}{Omluv mì, jestli se pletu, drahoušku, ale nechtìlas mì náhodou políbit?}
{555}{}{Doprèic. Skrz ty tvoje zatáèky bych teda chtìl projet bez brzd.}
{556}{}{Víš, co by na tobì vypadalo nejlíp? Já.}
{557}{}{Tvoje spoïáry moná nejsou ta nejlepší vìc na zemìkouli, ale mají k tomu zatracenì blízko.}
{558}{}{Máš nádhernì velkı... oèi.}
{559}{}{Máš zítra veèer èas, krásko? Ukáu ti svojí sbírku prezervativù.}
{560}{}{Kdybych nevìdìl, e se silikon u léta nevyrábí, nevìøil bych, e je to pøírodní.}
{561}{}{Nemíváš problémy se zádama? Divím se, e nepøepadneš dopøedu.}

# 17. CLICK (ANY) TO [MALE, MADE MAN) (WTG)
{580}{}{Zdravím, pane. Jak se vede?}
{581}{}{Je všechno v poøádku pane?}
{582}{}{Stojím vám v cestì, pane? Omlouvám se, neprodlenì opustím mìsto.}
{583}{}{Já dıchám váš vzduch? Promiòte, hned toho nechám.}
{584}{}{Vyøiïte prosím moje uctivé pozdravy vašemu šéfovi.}
{585}{}{Prosím...nechci ádné potíe.}
{586}{}{Zdravím, madam. Jak se vede?}
{587}{}{Je všechno v poøádku madam?}

# 18. CLICK (ANY) TO [SLAVER] (WTG)
{600}{}{Proè je tu poslední dobou tolik otrokáøù?}
{601}{}{Tebe tu vidím poprvé...}
{602}{}{Jestli máš na prodej nìjakı otroky, zeptej se u Mordina.}
{603}{}{Hledáš Stáje? Tam odebírají vìtšinu otrokù.}
{604}{}{Uka mi svoje zboí.}
{605}{}{Jestli máš na prodej nìjakı otroky, zastav se u Mordina.}
{606}{}{Tohle hnusnı mìsto nenávidím. NENÁVIDÍM.}
{607}{}{U v tomhle mìstì iju dlouho... moná a pøíliš dlouho.}
{608}{}{Tohle mìsto je úasnì pohostinnı... zvláš k turistùm.}
{609}{}{Tohle mìsto je úasnì pohostinnı... zvláš k otrokáøùm.}
{610}{}{Tohle mìsto je úasnì pohostinnı... zvláš k pasákùm a dìvkám.}
{611}{}{Na sever od New Reno je prı nìjaká zóna, kde na otrocích testujou drogy.}
{612}{}{Golgotha je v poušti, na jih od New Reno.}
{613}{}{Moná jsem chudej, ale ne na duchu.}
{614}{}{Ale já nejsem chudej. Mìl jsem jen poslední dobou pech.}
{615}{}{Minulou noc byl ten smrad z Golgothy k nevydrení...}
{616}{}{Do hajzlu! Hele, pøedstav si to, u vedu o 53 babek a najednou...}
{617}{}{Bıt tebou, tak jsem v tıhle ètvrti opatrnej. Jinak skonèíš jako hnojivo na Golgotì.}
{618}{}{New Reno by nebylo tak špatnı místo, nebejt všech tìch zasranejch turistù.}
{619}{}{::Stranou si uplivuje::}
{620}{}{Rozbiju jim bank.}
{621}{}{Orat se jako prase nìkdy nepomáhá.}
{622}{}{V tìch zatracenejch kasinech by mìly bejt rozcestníky...}
{623}{}{Socka? No to je nìkdo, kdo pøijde do mìsta a sází tak nejvıš po jednom nebo dvou doláèích.}
{624}{}{Všichni se proti mnì spikli.}
{625}{}{Zasraná smùla. Kurvapráce, to byl pech.}
{626}{}{Díky Bohu, e toho chlapa narazili na kùl...}
{627}{}{Špinavej parchant...}
{628}{}{Co chceš?}
{629}{}{Fet je drahej, dìvky samá vyráka, karta mi nepadá a i ten vzduch smrdí. Èasy jsou zlı Kamile...}
{630}{}{Reno jde pomalu do hajzlu. Nejvyšší èas pohnout se o kus dál.}
{631}{}{Ta Bishopovic holka se chová jak utrená ze øetìzu.}
{632}{}{Jestli mì tu ti kreténi z Protialkoholickı ligy budou otravovat ještì jednou...}
{633}{}{Vèera zas vidìli Otce Tullyho, jak se úplnì oralej válí v pøíkopu.}
{634}{}{Nejvyšší èas z tohohle mìsta vypadnout.}
{635}{}{To byl pøípad ten závislák. Válel se ve vlastních sraèkách a všude po ksichtì mu lezly mouchy. A von se pøitom SMÁL.}
{636}{}{Mám TISÍC chutí z tohohle odpornıho mìsta vypadnout, ale...}
{637}{}{Pøestaò mì votravovat.}
{638}{}{Hele, zrovna teï na tebe nemám èas.}

# 19. CLICK (ANY) TO [COMPANION: BONE-NOSE] OR MALE TOWNSPERSON TO (COMPANION: SPOUSE = FEMALE) (WTG)
{650}{}{Tvùj kámoš má ve fròáku kost.}
{651}{}{To si všichni ve tvı partì strkaj do nosu kost? To je místo pøijímacího pohovoru?}
{652}{}{Ten tvùj kámoš je z nìjakıho speciálního "strè-kost-skrz-nos" kmene?}
{653}{}{Ten tvùj kámoš s kostí v drce je ivım dùkazem toho, e divoch zùstane vdycky divochem.}
{654}{}{To je kost, co má ten tvùj kámoš v nose?}
{655}{}{Panenko skákavá... ta kost, co má ten tvùj kámoš v nose, je velká jak moje ruka.}
{656}{}{Radši ani nechci, jakım zpùsobem ten tvùj pøítel tu kost do toho nosu narval.}
{657}{}{Tohle hnusnı mìsto nenávidím. NENÁVIDÍM.}
{658}{}{U v tomhle mìstì iju dlouho... moná a pøíliš dlouho.}
{659}{}{Tohle mìsto je úasnì pohostinnı... zvláš k turistùm.}
{660}{}{Tohle mìsto je úasnì pohostinnı... zvláš k otrokáøùm.}
{661}{}{Tohle mìsto je úasnì pohostinnı... zvláš k pasákùm a dìvkám.}
{662}{}{Na sever od New Reno je prı nìjaká zóna, kde na otrocích testujou drogy.}
{663}{}{Jestli hledáš Golgothu, tak ta je v poušti, na jih od New Reno.}
{664}{}{Moná jsem chudej, ale ne na duchu.}
{665}{}{Ale já nejsem chudej. Mìl jsem jen poslední dobou pech..}
{666}{}{Minulou noc byl ten smrad z Golgothy k nevydrení...}
{667}{}{Do hajzlu! Hele, pøedstav si to, u vedu o 53 babek a najednou...}
{668}{}{Bıt tebou, tak jsem v tıhle ètvrti opatrnej, jinak skonèíš jako hnojivo na Golgotì.}
{669}{}{New Reno by nebylo tak špatnı místo, nebejt všech tìch zasranejch turistù.}
{670}{}{::Stranou si uplivuje::}
{671}{}{Rozbiju jim bank.}
{672}{}{Orat se jako prase nìkdy nepomáhá.}
{673}{}{V tìch zatracenejch kasinech by mìly bejt rozcestníky...}
{674}{}{Socka? No to je nìkdo, kdo pøijde do mìsta a sází tak nejvıš po jednom nebo dvou doláèích.}
{675}{}{Všichni se proti mnì spikli.}
{676}{}{Zasraná smùla. Kurvapráce to byl pech.}
{677}{}{Díky Bohu, e toho úchyla Prùšu narazili na kùl...}
{678}{}{Špinavej parchant...}
{679}{}{Co chceš?}
{680}{}{Fet je drahej, dìvky samá vyráka, karta mi nepadá a i ten vzduch smrdí. Èasy jsou zlé Kamile...}
{681}{}{Reno jde pomalu do hajzlu. Nejvyšší èas pohnout se o kus dál.}
{682}{}{Ta Bishopovic holka se chová jak utrená ze øetìzu.}
{683}{}{Jestli mì tu ti kreténi z Protialkoholickı ligy budou otravovat ještì jednou...}
{684}{}{Vèera zas vidìli Otce Tullyho, jak se úplnì oralej válí v pøíkopu.}
{685}{}{Nejvyšší èas z tohohle mìsta vypadnout.}
{686}{}{To byl pøípad ten závislák. Válel se ve vlastních sraèkách a všude po ksichtì mu lezly mouchy. A von se pøitom SMÁL.}
{687}{}{Mám TISÍC chutí z tohohle odpornıho mìsta vypadnout, ale...}
{688}{}{Pøestaò mì votravovat.}
{689}{}{Hele, zrovna teï na tebe nemám èas.}
{690}{}{Take vona je tvoje "manelka," jo? Mùu si jí tak na hodinku nebo dvì pùjèit?}
{691}{}{Nechceš si na èásek prohodit manelky?}
{692}{}{Ta enská s tebou je na prodej?}
{693}{}{Kolik chceš za tu tvojí enskou?}
{694}{}{Ta enská, co s sebou táhneš, je docela hezká.}
{695}{}{Umí ta tvoje enská i vaøit? Jestli jo, tak jí koupím.}
{696}{}{Kolik chceš za tu tvojí samièku?}
{697}{}{Ta Bishopova panièka má skvìlı nohy.}

# 20. CLICK (ANY) TO [NO REP] (WTG)
{700}{}{Á tady si nìkdo dneska v noci parádnì uije!}
{701}{}{Na jdis si dìvku a uij si s ní.}
{702}{}{Ta Bishopova panièka má skvìlı nohy.}
{703}{}{Na sever od New Reno je prı nìjaká zóna, kde na otrocích testujou drogy.}
{704}{}{Jestli hledáš Golgothu, tak ta je v poušti, na jih od New Reno.}
{705}{}{Moná jsem chudej, ale ne na duchu.}
{706}{}{Ale já nejsem chudej. Mìl jsem jen poslední dobou pech..}
{707}{}{Kolik dalších neandrtálcù ještì do tohohle mìsta pøijde?}
{708}{}{Øekni laskavì zbytku svıho kmene, a zùstane doma.}
{709}{}{No vıbornì. Další opièák. Vy barbaøi se mnoíte jak kobylky.}
{710}{}{Minulou noc byl ten smrad z Golgothy k nevydrení...}
{711}{}{Do hajzlu! Hele, pøedstav si to, u vedu o 53 babek a najednou...}
{712}{}{Bıt tebou, tak jsem v tıhle ètvrti opatrnej, jinak skonèíš jako hnojivo na Golgotì.}
{713}{}{New Reno by nebylo tak špatnı místo, nebejt všech tìch zasranejch turistù.}
{714}{}{Prı má dorazit nová zásilka otrokù.}
{715}{}{V bordelu mají novou zásilku otrokù.}
{716}{}{::Stranou si uplivuje::}
{717}{}{Rozbiju jim bank.}
{718}{}{Orat se jako prase nìkdy nepomáhá.}
{719}{}{V tìch zatracenejch kasinech by mìly bejt rozcestníky...}
{720}{}{Socka? No to je nìkdo, kdo pøijde do mìsta a sází tak nejvıš po jednom nebo dvou doláèích.}
{721}{}{Všichni se proti mnì spikli.}
{722}{}{Zasraná smùla. Kurvapráce to byl pech.}
{723}{}{Díky Bohu, e toho chlapa narazili na kùl...}
{724}{}{Špinavej parchant...}
{725}{}{Co chceš?}
{726}{}{Fet je drahej, dìvky samá vyráka, karta mi nepadá a i ten vzduch smrdí. Èasy jsou zlé Kamile...}
{727}{}{Reno jde pomalu do hajzlu. Nejvyšší èas pohnout se o kus dál.}
{728}{}{Ta Bishopovic holka se chová jak utrená ze øetìzu.}
{729}{}{Jestli mì tu ti kreténi z Protialkoholickı ligy budou otravovat ještì jednou...}
{730}{}{Vèera zas vidìli Otce Tullyho, jak se úplnì oralej válí v pøíkopu.}
{731}{}{Nejvyšší èas z tohohle mìsta vypadnout.}
{732}{}{To byl pøípad ten závislák. Válel se ve vlastních sraèkách a všude po ksichtì mu lezly mouchy. A von se pøitom SMÁL.}
{733}{}{Mám TISÍC chutí z tohohle odpornıho mìsta vypadnout, ale...}
{734}{}{Pøestaò mì votravovat.}
{735}{}{Hele, zrovna teï na tebe nemám èas.}
{736}{}{Asi se mrknu do centra, jestli nedorazili nìjakı turisti...}
{737}{}{Díkybohu, e toho sráèe narazili na kùl...}

# endlines
{1203}{}{!}
{1204}{}{! Nakopej jim prdel! Nakopej jim PRDEL!}
{1205}{}{! Jsi samı PRACHY!}
{1493}{}{!}
{1497}{}{! Nakopej jim prdel! Nakopej jim PRDEL!}
