#Tenhle soubor pøeloil Birdman, Birdman@post.cz, http://www.mujweb.cz/www/birdman, 0604 540689
# 0. QUICK LOOK
{100}{}{Vidíš pøízemního bose kasina.}

# 0. LOOK
{150}{}{Vidíš hezky obleèeného mue. Hlídá kasino.}
{151}{}{Vidíš pøízemního bose. Hlídá kasino.}

# 1. FLOAT DIALOGUE: POWER ARMOR (WTG)
{200}{}{Uh... budete se muset zbavit toho brnìní.}
{201}{}{Uh, pane... nebo madam... budete se muset zbavit toho brnìní.}
{202}{}{Pane... madam... nemùete to mít obleèené v kasinu.}

# 2. FLOAT DIALOGUE: MALE, MADE MAN, SAME CASINO, SNEAK (WTG)
{205}{}{Uh, proè se tu okolo plííte, pane?}
{206}{}{Uh, jste tady inkognito, pane?}

# 3. FLOAT DIALOGUE: FEMALE, MADE MAN, SAME CASINO, SNEAK (WTG)
{210}{}{Uh, proè se tu okolo plííte, madam?}
{211}{}{Uh, jste tady inkognito, madam?}

# 4. FLOAT DIALOGUE: MALE, MADE MAN, SAME CASINO, NIGHT (WTG)
{215}{}{Dobrı veèer, }
{1215}{}{, pane.}
{216}{}{Veèer, }
{1216}{}{, pane.}

# 5. FLOAT DIALOGUE: FEMALE, MADE MAN, SAME CASINO, NIGHT (WTG)
{220}{}{Dobrı veèer, }
{1220}{}{, madam.}
{221}{}{Veèer, }
{1221}{}{, madam.}

# 6. FLOAT DIALOGUE: MALE, MADE MAN, SAME CASINO (WTG)
{225}{}{Dobrı den, }
{1225}{}{, pane.}

# 7. FLOAT DIALOGUE: FEMALE, MADE MAN, SAME CASINO (WTG)
{230}{}{Dobrı den, }
{1230}{}{, madam.}

# 8. FLOAT DIALOGUE: MALE, MADE MAN, NOT SAME CASINO (WTG)
{235}{}{Kámo, pøišels do špatného kasina.}
{236}{}{Bude lepší kdy vypadneš. Hned.}
{237}{}{Toto není místo na riskování ivota. Bude lepší kdy vypadneš.}
{238}{}{Feno, pøišels do špatného kasina.}

# 10. FLOAT DIALOGUE: MALE, PRIZEFIGHTER/PORN STAR (ARMED) (WTG)
{245}{}{Pane, omlouvám se, mìl byste schovat tu zbraò.}

# 11. FLOAT DIALOGUE: FEMALE, PRIZEFIGHTER (ARMED) (WTG)
{250}{}{Madam, omlouvám se, mìla byste schovat tu zbraò.}

# 12. FLOAT DIALOGUE: PORN STAR, FEMALE (ARMED) (WTG)
{255}{}{Miláèku, omlouvám se, nemùeš nosit zbraò uvnitø kasina. He,he... U tak jsi dost smrtící.}

# 13. FLOAT DIALOGUE: PORN STAR, FEMALE (SNEAK) (WTG)
{260}{}{Miláèku, s takovım tìlem ti plíení nepomùe, stejnì si tì kadı všimne.}

# 14. FLOAT DIALOGUE: MALE, NO REP (ARMED) (WTG)
{265}{}{Barbare, udìláš lépe kdy tu zbraò zajistíš. A to HNED!}

# 15. FLOAT DIALOGUE: MALE, NO REP (SNEAK) (WTG)
{270}{}{Barbare, udìláš nejlíp, kdy se tady pøestaneš plíit. A to HNED!}

# 16. MYRON, MORDINO (WTG)
{275}{}{Hej, hej... Myrone! U jsem tì dlouho nevidìl mimo laboratoø.}
{276}{}{Pøinesls ukázku novıho zboí, Myrone?}
{277}{}{Hey! Pojï dál, Myrone.}

# 17. MARCUS (WTG)
{285}{}{ádní mutanti. Poèká venku.}
{286}{}{Mì nezajímá, e je to exmanel tvého pøítele. Mutanti èekají venku.}
{287}{}{Ta mutantí zrùda sem nemá pøístup.}

# 18. ROBOBRAIN (WTG)
{295}{}{ádní droidi.}
{296}{}{Neobsluhujeme droidy.}
{297}{}{ádní droidi. Poèkají venku.}

# 19. FLOAT DIALOGUE: FLAG: ENCLAVE DESTROYED IS TRUE  (WTG)
{305}{}{Ve slubì bych nemìl kecat, ale jsem rád, e jsi nakopal Enklávì prdele.}
{306}{}{Hej, }
{1306}{}{. Odpoèiò si od záchrany svìta a trochu se pobav.}

# 20. FLOAT DIALOGUE: DAY (WTG)
{315}{}{Potøebuju trochu drobnıch na stùl tøi...}
{316}{}{Dneska je poøádná tlaèenice...}

# 21. FLOAT DIALOGUE: NIGHT (WTG)
{325}{}{Potøebuju trochu drobnıch na stùl tøi...}
{326}{}{Dneska veèer je poøádná tlaèenice...}

# 22. INTRO (WTG)
{335}{}{Hej, }
{336}{}{! Slyšel jsem, e jste ten, kdo srazil Enclávu zpátky do doby kamenné! Dostal jsem instrukce, a vám dám tyhle drobnı. Pozornost kasina. Uijte si to, pane.}
{337}{}{! Slyšel jsem, e jste ta, kdo srazil Enclávu zpátky do doby kamenné!  Dostal jsem instrukce, a vám dám tyhle drobnı. Pozornost kasina. Uijte si to, madam.}
{338}{}{. Co se stalo, šéfe? Pøejete si nìco? Drink? Èíšnici?}
{339}{}{. Nejkrásnìjší dívko v kasinu. Pøejete si nìco? Pití? Soukromı stùl?}
{340}{}{Co pro tebe mohu udìlat, kámo?}
{341}{}{Co pro tebe mohu udìlat, lásko?}
{342}{}{Fooooooo foo foo fooooo}
{343}{}{Odejdi}
{344}{}{Kdo jsi?}
{345}{}{Co je to za kasino?}
{346}{}{Mùeš mi nìco málo øíct o kasinu?}
{347}{}{Znáš nìkoho jménem Hezoun Lloyd?}
{348}{}{Kdo je ten starı chlapík u tohoto automatu?}
{349}{}{Ten komik na tom jevišti je ubohej. Nevadilo by, kdybych si zkusil?}
{350}{}{Dík. Nepotøebuješ taneènici na dnešní noc? Mohla bych dìlat na polovièní úvazek.}
{351}{}{Díky.}
{352}{}{Nic, dík. Sorry, e otravuju}
{353}{}{Jenom se tak dívám. Pokraèuj.}

# 23. PORN STAR (WTG)
{360}{}{Hej podívejte se kdo je tu! Hej, }
{361}{}{. Vítej v  [CN]. Milujem tvé filmy.}
{362}{}{Fooooooo foo foo fooooo}
{363}{}{Odejdi}
{364}{}{Kdo jsi?}
{365}{}{Co je to za kasino?}
{366}{}{Mùeš mi nìco málo øíct o kasinu?}
{367}{}{Znáš nìkoho jménem Hezoun Lloyd?}
{368}{}{Kdo je ten starı chlapík u toho automatu?}
{369}{}{Dík. Nepotøebuješ taneènici na dnešní noc? Mohla bych dìlat na polovièní úvazek.}
{370}{}{Dík, lichotíš mi. Jdu jen tak kolem.}

# 24. I HAD SOME QUESTIONS (31, 32, 33, 34, 35, 36, 37, 38)
{280}{}{Jasnì. Co chceš vìdìt.?}
{281}{}{Fooooooo foo foo fooooo}
{282}{}{Odejdi}
{283}{}{Kdo jsi?}
{284}{}{Co je to za kasino?}
{285}{}{Mùeš mi nìco málo øíct o kasinu?}
{286}{}{Víš e kdo je Hezoun Lloyd?}
{287}{}{Kdo je ten starı chlapíkat u toho automatu?}
{288}{}{Ten komik na tom jevišti je ubohej. Nevadilo by, kdybych si zkusil?}
{289}{}{Dík. Nepotøebuješ taneènici na dnešní noc? Mohla bych dìlat na polovièní úvazek.}
{290}{}{Dík.}
{291}{}{Nic, dík. Sorry, e otravuju}
{292}{}{Jenom se tak dívám. Pokraèuj.}

# 25.  RETARD (22, 23, 24)
{300}{}{Uh, radši byste mìl vypadnout, pane.}
{301}{}{Uh, radši byste mìla vypadnout, madam.}
{302}{}{Vypadni, postiáku.}
{303}{}{Máma øíkat, já vıjimešná!}
{304}{}{Odejdi}

# 26.  MOM SAYS I WAS SPESHAL (25)
{315}{}{Jo, mì to tvoje mutr taky øíkala. A teï zmiz, moná ji najdeš nìkde kolem Panenské ulice.}
{316}{}{Oh, dobro! Pa.}
{317}{}{Odejdi}

# 27.  WHO ARE YOU? (22, 23, 24, 29, 30, 31)
{325}{}{Jsem tady šéf. Co pro tebe mohu udìlat?}
{326}{}{Šéfuju tomuhle patru kasina. Jestli nìco potøebuješ, staèí øíct.}
{327}{}{Co je to za kasino?}
{328}{}{Mùeš mi nìco málo øíct o kasinu?}
{329}{}{No nic, dík. Promiò, e zdruju.}

# 28.  WHAT CASINO IS THIS? (22, 23, 24, 27)
{335}{}{Tohle je [CN]. Jestli nìco potøebuješ, staèí øíct.}
{336}{}{Tohle je [CN]. Aspoò naposled, kdy jsem kontroloval znak nad dveøma. Co pro tebe mohu udìlat?}
{337}{}{Kdo jsi?}
{338}{}{Mùeš mi nìco málo øíct o kasinu?}
{339}{}{Nic, dík. Promiò, e zdruju.}

# 29.  WHAT CAN YOU TELL ME ABOUT THIS CASINO? (22, 23, 24, 27, 28, 30)
{345}{}{Zatracenì nejlepší kasino ve mìstì. Chceš vìdìt nìco dalšího?}
{346}{}{Zatracenì nejlepší kasino ve mìstì, zatracenì nejlepší stoly...
tak proè si je nejdeš prohlídnout a vyzkoušet, co?}
{347}{}{Kdo jsi?}
{348}{}{Komu patøí tohle kasino?}
{349}{}{Okay, dík. Promiò, e zdruju.}

# 30.  WHO OWNS THIS CASINO? (29)
{355}{}{Rodina [CA]. Napumpovali sem ivot, udìlali z toho skvìlı noèní klub, úplnı klenot Novıho Rena.}
{356}{}{Rodina [CA]. Máš s tím nìjakej problém? Protoe, jestli tu nejsi kvùli høe, tak tu pro tebe není místo. Rozumíš?}
{357}{}{Kdo jsi?}
{358}{}{Mùeš mi nìco málo øíct o tomhle kasinu?}
{359}{}{Aha. Díky za tvùj èas.}

# 31.  McGEE (22, 23, 24)
{365}{}{Ten dìdek? Starı Man McGee? Bláznivej zkurvysyn... hrál na tomto automatu pár posledních let, èekal na velkı jackpot. Celı jeho ivotní vıdìlek musí bıt v té vìci, ale ta mašina mu nikdy nedala ani drobák.}
{366}{}{Ten dìdek? Starı Man McGee? Bláznivej zkurvysyn, to je jistı. Heh. Byl poøádnì nasranej, kdy si vyhrál jeho bohatství. Dával bych si na nìj bacha.}
{367}{}{Je ta mašina... upravená?}
{368}{}{Mám jiné otázky.}
{369}{}{Dík za informace.}

# 32.  IS THE MACHINE RIGGED? (31)
{375}{}{Ne, je jenom tvrdohlavá... jako on. Potøebuje malou opravu, ale my nemáme ádnıho mechanika.}
{376}{}{Mám jinou otázku.}
{377}{}{Zajímavé. Dík za informace.}

# 33.  PRETTY BOY LLOYD? (22, 23, 24)
{385}{}{Jo. Ten zmrd sem pøišel minulı tıden, vybral z jednoho stolu pár tisíc babek, pak se odporouèel. Nevím kde teï je, ale míval pokoj u Desperada.}
{386}{}{Jo. Nìjakı chlápek s tímhle jménem si najmul si jeden s horních pokojù 204. Všechno zaplatil, pøed pár dny ale zmizel a nikdo ho nevidìl odcházet.}
{387}{}{Pan Salvator se zmínil, e tu byl urèitı dealer, od kterého Lloyd vyhrál peníze. Kdo to byl?}
{388}{}{Mám jinou otázku.}
{389}{}{Dík za informace.}

# 34.  NIKKI? (33)
{395}{}{Nikki? Jo, je právì tam, u støedního stolu. Je tady nìjakı problém?}
{396}{}{ádnı problém. Jenom se chci seznámit. Mám ještì otázku.}
{397}{}{Dík za informace.}

# 35.  NIKKI DEAD (33)
{405}{}{Její jméno bylo Nikki. Pracovala tu ale dostala vıpovìï... není to tak dlouho.}
{406}{}{Hmmm. Myslíte e se mohu zeptat na nìjaké jiné otázky?}
{407}{}{Zajímavé. Dík za informace.}

# 36.  NIKKI RAN (33)
{415}{}{Její jméno BYLO Nikki. Pracovala tu, ale nedávno zmizela. Jenom si sbalila svejch pár švestek a odtáhla.}
{416}{}{Hmmm. Nevadila by ti ještì jedna dvì otázky?}
{417}{}{Zajímavé. Dík za informace.}

# 37.  NEED A DANCER (22, 23, 24)
{425}{}{Jistì, to bude dobrı pro kšeft. Šatna je vzadu...}
{426}{}{Skvìle. Budu na jevišti za pár minut...}
{427}{}{Teï ne. mám ještì jiné otázky...}
{428}{}{Teï ne, ale ještì se vrátím.}

# 38.  NEED A DANCER (22, 23, 24)
{435}{}{Ne, ještì jsme se nedostali z tvého posledního vystoupení. Zkus to jinde.}
{436}{}{Fajn, dík. Mám ještì další otázky...}
{437}{}{Okay...ale myslím, e se ještì vrátím.}

# 39.  PERFORM (37)
{445}{}{Poèítej s veèerním vyúètováním. Doláèe. Není to špatnı.}
{446}{}{Ta kùe byla dobrá na dotek.}
{447}{}{Ta finta s balónem byla taky fajn.}
{448}{}{Pøíštì to udìlám ještì lépe.}

# 40.  PERFORM (22, 24)
{455}{}{Jo, smrdí hùø ne brahmíní hovno. Ale ty...? Á, proè sakra ne? Malé zlepšení by neškodilo, ale tohle je drsná banda... radìji doufej, e to zvládneš.}
{456}{}{Oh, jsem vynikající... Jen mì sleduj.}
