#tento soubor pøeloil Somnambulus...somnambulus@hotmail.com
# quick look
{100}{}{Vidíš pasáka.}

# examine
{150}{}{Vidíš dobøe obleèeného mue. Jeho šaty tì svım leskem div neoslepí.}
{151}{}{Vidíš chlapíka v nápadnì drahém obleku.}
{152}{}{Vidíš pasáka. Vypadá fakt šmrncovnì.}
{153}{}{Vidíš pasáka. Zírá na tebe.}
{154}{}{Vidíš pasáka. Kdyby se volil Pasák roku, tak tenhle by tu cenu urèitì dostal.}
{155}{}{Vidíš ehmm... pastıøe dívek. Jeho oblek má tak øvavé barvy, e by 
na nìm mìl mít pøišitı regulátor hlasitosti.}

# 1. ENCLAVE DESTROYED (MALE)
{200}{}{Hej chlape, slyšel jsem, e jsi zlikvidoval Enklávu. Nemìl bys teï 
chu si na chvíli LEHNOUT?}
{201}{}{Ten cucák zlikviduje jednu vobyèejnou mròavou Enklávu a hned si myslí, e mu patøí celej svìt... pche.}
{202}{}{Nazdar chlape! Jediná vìc, která je ještì lepší ne sfouknout ropnou vì, je 
kdy ti nìkdo nafoukne tvojí vì, jestli teda kapíruješ vo èem mluvím.}

# 2. ENCLAVE DESTROYED (FEMALE)
{220}{}{Slyšel jsem, e jsi znièila Enklávu, dìvèe. Nemìla bys chu pracovat chvilku pro mnì?}
{221}{}{Nána pitomá. Znièí jednu mròavou nanicovatou Enklávu a hned si myslí, e jí patøí celej svìt... pche.}
{222}{}{Sexy pokoøitelka Enklávy jako ty by si v tomhle mìstì mohla vydìlat slušnı prachy...}

# 3. (MALE PORN STAR)
{230}{}{enskı mají stejnì radši moje prachy...}
{231}{}{Letošní sezóna stojí za hovno. Turisti radši fetujou a chlastaj.}
{232}{}{Moc po mnì neèum vylízanèe. Já ti nepodrím...}
{233}{}{Helemese to je naše superhvìzda. Jdi si po svejch.}
{234}{}{Chceš si zapíchat?}
{235}{}{Nechceš ve svım novım filmu obtáhnout nìjakou z mejch sleèen, brácho?}
{236}{}{Vìø mi kámo, ty pro svoje filmy potøebuješ opravdovı enskı. Vyzkoušej nìkdy moje holky.}
{237}{}{Potøebuješ òákou nabíjeèku? Mám jich tu fùru.}
{238}{}{Tohle nejsou ádnı otrokynì, to jsou profesionálky. Slyšíš co ti povídám?}
{239}{}{Kdy si spolu zahrajeme v nìjakım prima bi filmu, brouku?}
{240}{}{Dej mi pár minut pøed kamerou a já ti ukáu co je to filmová hvìzda.}
{241}{}{Tak jako TY, to já zvládnu malíkem u nohy. A narozdíl od tebe ta 
holka ani nebude muset pøedstírat orgasmus.}
{242}{}{Nemohl bys mì nauèit pár tìch svejch trikù, bráško?}
{243}{}{Pùjèím ti tuhle holku. Má fakt sladkou prdelku, schválnì jí prubni ve svım filmu.}
{244}{}{Tak bacha na vìc mladej. Já byl dva roky po sobì zvolenej Pasákem roku.}
{245}{}{V ivotì nepochopím jak se z TEBE mohla stát pornohvìzda...}

# 4. (PORN STAR FEMALE)
{260}{}{Já si radši vydìlávám svoje prachy takhle...}
{261}{}{Letošní sezóna stojí za hovno. Turisti jen chlastaj a fetujou.}
{262}{}{Moc na mì neèum dìvko...}
{263}{}{Dej si odchod èubko. Kazíš mi kšefty.}
{264}{}{Vidìl jsem tì ve filmu. Máš fantastickou prdelku, kotì.}
{265}{}{Pojï se mnou miláèku. Vymaèkám ti z tı tvı buchtièky trochu šávièky.}
{266}{}{::Hvízdá na tebe::}
{267}{}{::mumlá si pro sebe 'tomuhle teda øíkám poøádnı kozy, sakra.'::}
{268}{}{Kdy nám zatanèíš v kasinu, drahoušku?}
{269}{}{Ty k sobì potøebuješ zkušenıho partnera. Mìla bys nìkdy zkusit mnì, zlato.}
{270}{}{Kdy si spolu zahrajeme ve filmu krásko?}
{271}{}{Vlez si se mnou pøed kameru a já ti ukáu co je opravdová filmová hvìzda.}
{272}{}{Se mnou se udìláš tak jako ještì nikdy v ivotì.}
{273}{}{Hej zlato, nauè mì pár tìch svejch kouskù.}
{274}{}{Hergot, tìlo jako máš ty, by se mìlo zakázat.}
{275}{}{Divím se, e se ten asfalt pod takovıma nohama nerozpustí.}
{276}{}{Pojï dìlat ke mnì kotì. Já byl dva roky po sobì zvolenej Pasákem roku.}
{277}{}{Pojï se mnou lásko. Ukáu ti osmej div svìta.}
{278}{}{Cákryš, to jsou kozièky. Oúúú...}

# 5. (MALE, MADE MAN)
{290}{}{Já si svoje prachy radši vydìlávám takhle...}
{291}{}{Letošní sezóna stojí za hovno. Turisti jen chlastaj a fetujou.}
{292}{}{Raète ke mnì šéfe. Moje holky jsou všechny zdravı a èistı...}
{293}{}{Hledáme nìjakı potìšeníèko šéfíku?}
{294}{}{Chcete si vrznout šéfe? Pro vás bude první èíslo zdarma.}
{295}{}{Rád bych vám prokázal svojí úctu, pøíteli. Dám vám jednu z mejch holek na celou noc.}
{296}{}{Postùjte pøíteli. Mìl bych tu pro vás jednu skvìlou holku.}
{297}{}{Vaše Rodina potøebuje chlapa jako jsem já. Takovıho kterej umí enskı udret na uzdì...}
{298}{}{Vedete si skvìle... fakt bodujete.}
{299}{}{Bezva vohoz, šéfe.}
{300}{}{Øeknìte slovo pane a budu Vám dìlat osobního stráce.}
{301}{}{Kreju ti záda brácho.}
{302}{}{Koukejte holky... takhle vypadá POØÁDNEJ chlap...}
{303}{}{Moná to ještì nevíte šéfe, ale já byl dva roky po sobì zvolenej Pasákem roku.}
{304}{}{Velkej gangster pøichází...}
{305}{}{Raète zajít na návštìvu šéfe. Moje holky jsou jak pivo. Vdycky vlhkı...}

# 6. (FEMALE MADE MAN)
{320}{}{Já si svoje prachy radši vydìlávám takhle...}
{321}{}{Letošní sezóna stojí za hovno. Turisti jen chlastaj a fetujou.}
{322}{}{Raète ke mnì dámo. Všechny moje holky jsou zdravı a èistı...}
{323}{}{Kdopak je ta nádherná enská co vidím?}
{324}{}{Sakra, já miluju enskı co mají styl.}
{325}{}{Vedeš si skvìle enská... fakt boduješ.}
{326}{}{Bezva vohoz, sleèno.}
{327}{}{Udìlala jsi ze všech tìch parchantù keèup. Tvùj styl se mi líbí.}
{328}{}{Øeknìte slovo sleèno a budu vám dìlat osobního stráce.}
{329}{}{Kreju vám záda, sleèno.}
{330}{}{Kotì, ty tvoje havraní vlasy a ten zloèineckej vıraz v ksichtì prostì zboòuju.}

# 7. (MALE PRIZEFIGHTER)
{350}{}{Já si svoje prachy radši vydìlávám takhle...}
{351}{}{Letošní sezóna stojí za hovno. Turisti jen chlastaj a fetujou.}
{352}{}{Pojï si vybrat drsòáku. Moje holky jsou všechny zdravı a èistı...}
{353}{}{Hledáš nìjakı povyraení šampióne?}
{354}{}{Chceš se trochu protáhnout sportovèe? e jsi to ty, budeš mít první èíslo zdarma.}
{355}{}{To byl sakra dobrej maè, pøíteli. Dám ti jednu z mejch holek na celou noc.}
{356}{}{Postùj brácho. Mìl bych tu pro tebe jednu skvìlou holku.}
{357}{}{Tenhle chlap je jak Robin Hood. Taky radši rozdává ne pøijímá... checheche.}
{358}{}{Na tom pravım háku bys mìl ještì zapracovat brácho. Ale jinak... fakt dobrı.}
{359}{}{Nezkusíme to nìkdy spolu v ringu, kámo?}
{360}{}{Vsadil jsem na tebe 100 babek šampióne. Tak mì nezklam.}
{361}{}{Nepotøebuješ na dnešní veèer patnerku pro BOX, šampióne? Mìl bych tu 
pro tebe jednu pìknì èilouèkou.}
{362}{}{Øekni slovíèko šampióne a budu tvùj osobní stráce.}
{363}{}{Neboj, kreju ti záda šampióne.}
{364}{}{Moná to o mnì nevíš, šampióne, ale já byl dva roky po sobì zvolenej Pasákem roku.}
{365}{}{Velkej Tvrdej Marvin pøichází...}
{366}{}{Koukejte holky... takhle vypadá OPRAVDOVEJ chlap...}

# 8. (FEMALE PRIZEFIGHTER)
{380}{}{Já si svoje prachy radši vydìlávám takhle...}
{381}{}{Letošní sezóna stojí za hovno. Turisti jen chlastaj a fetujou.}
{382}{}{Radši na mì nesahej, dìvko...}
{383}{}{Copak to tu máme za nádhernou koèièku?}
{384}{}{Zboòuju enskı, kterı ví jak dostat chlapa na lopatky.}
{385}{}{Sakra, já miluju enskı co mají styl.}
{386}{}{Bezva vohoz, enská.}
{387}{}{Udìlala jsi ze všech tìch sralbotkù keèup. Tvùj styl se mi líbí.}
{388}{}{Øekni slovíèko šampiónko a budu tvùj osobní stráce.}
{389}{}{Kreju ti záda.}
{390}{}{Na tom levım háku bys mìla ještì zapracovat kotì. Ale jinak... fakt dobrı.}
{391}{}{Nezkusíme to nìkdy spolu v ringu, brouku?}
{392}{}{Vsadil jsem na tebe 100 babek fešando. Tak mì nezklam.}
{393}{}{Kotì, miluju tvoje havraní vlasy... a tvùj smrtící levej hák.}

# 9. FLOAT (COMPANION: MYRON)
{410}{}{Já si svoje prachy radši vydìlávám takhle...}
{411}{}{Letošní sezóna stojí za hovno. Turisti jen chlastaj a fetujou.}
{412}{}{Jen si pojïte vybrat vy kanci. Všechny moje holky jsou zdravı a èistı...}
{413}{}{Hledáte nìjakı povyraení?}
{414}{}{Vy dva vypadáte, e byste potøebovali nìco vlhkıho pøes oblièej... checheche}
{415}{}{Èau Myrone! Jak se vede?}
{416}{}{Èus Myrone! Hledáš spoleènost na dnešní veèer? Mìl bych pro tebe novou holku...}
{417}{}{Tak co hoši, hledáte nìco... vlhkıho?}
{418}{}{Šavnatìjší prdelky nenajdete nikde v celım New Reno.}
{419}{}{Jen pojïte a uijte si co hrdlo i jinı orgány ráèej.}
{420}{}{Vypadáte, e máte v poklopci oheò, hoši. Mám tu pár koèièek, co vám ho pomùou uhasit.}
{421}{}{Moje holky vydrej pøiráet celou noc.}
{422}{}{Vy máte prachy a já tu mám pár nadrenejch koèièek. Tak co kdybychom to dali dohromady?}
{423}{}{Jestli tì zas chytnu jak na mejch holkách dìláš ty svoje pokusy, Myrone, tak ti ho ufiknu.}
{424}{}{Ne e mejm holkám budeš zase dìlat cucfleky, Myrone.}
{425}{}{Kdy máš chu do mıch holek nìco vráet Myrone, tak a to není ádná jehla.}
{426}{}{Nepøeju si tu ádnı pøednášky o amfetaminech Myrone.}
{427}{}{Zkus ty holky pro zmìnu jen jednoduše obtáhnout Myrone. Bez všech tìch vìdeckejch vástù...}
{428}{}{Èus Myrone! Hledáš spoleènost na dnešní veèer? Mìl bych tu pro tebe nìco extra.}
{429}{}{To nejsou ádnı otrokynì ty blbe. To jsou øádnı zamìstnankynì, rozumíš?}
{430}{}{Myrone! Dluíš mi ještì za poslední víkend hochu!}
{431}{}{Mám tu jednu specialistku, co dokáe vcucnout golfovej míèek skrz zahradní hadici.}
{432}{}{Mám tu enskı co z vás udìlají skuteènı chlapy. A stojí jen pár babek.}
{433}{}{Ty nejlepší kobylky najdete v mı stáji.}
{434}{}{Co dìláš mimo Stáje Myrone? Hledáš nìjakou novou klisnièku?}
{435}{}{Starej Mordino ti dal koneènì vycházku Myrone?}

# 10. (COMPANION: SPOUSE = FEMALE)
{440}{}{Tohle je dobrej zpùsob jak si vydìlat prachy...}
{441}{}{Letošní sezóna stojí za hovno. Turisti jen chlastaj a fetujou.}
{442}{}{Dej si i s tou èubkou odchod. Kazíte mi kšefty...}
{443}{}{Zase jsem Myrona naèapal jak místo šoustání vykládá mejm holkám o endorfinech.}
{444}{}{Jestli zas chytnu Myrona jak na mejch holkách dìlá ty svoje pokusy, tak u mu ho vánì ufiknu.}
{445}{}{Nepotøebuješ na dnešní veèer spoleènost, kámo? Já ti jí obstarám.}
{446}{}{To nejsou ádnı otrokynì ty blbe. To jsou øádnı zamìstnankynì, rozumíš?}
{447}{}{Sladší prdelky nenajdete nikde v celım New Reno.}
{448}{}{Já mám ty nejlepší holky široko daleko.}
{449}{}{Vy máte prachy a já tu mám pár nadrenejch koèièek. Tak co kdybychom to dali dohromady?}
{450}{}{Ne e tuhle kurvu budeš pást v mım rajónu!}
{451}{}{Jestli uvidím nìjakı prachy mizet skrz kundu tıhle dìvky, tak si spolu popovídáme.}
{452}{}{Doporuè tı svı kurvièce a v tomhle mìstì radši drí nohy u sebe.}
{453}{}{Tıhle opotøebovanı štìtky se zbav, pøíteli. Mám tu holku co ti ho udrí "v pozoru" celou noc.}
{454}{}{Mám tu enskı co z vás udìlají skuteènı chlapy. A stojí jen pár babek.}
{455}{}{Ty nejlepší kobylky najdete v mı stáji.}
{456}{}{Jestli tì chytnu jak tuhle svojí "enušku" prodáváš v mım rajónu, vyrobím ti na krku otvor pro tracheotomii.}
{457}{}{Take ona je tvoje "ena," jo? No dobøe ty jeden "manílku". V tom pøípadì, e jí doporuèuju a si tu svojí prdelku v tomhle mìstì dobøe hlídá.}
{458}{}{Tohle je mùj rajón. Jdi si s tou svojí šlapkou jinam.}
{459}{}{Dej si bacha, a tì nechytím, e jí prodáváš na Mİ ulici.}

# 11. FLOAT (MALE SLAVER)
{470}{}{Já si svoje prachy radši vydìlávám takhle...}
{471}{}{Letošní sezóna stojí za hovno. Turisti jen chlastaj a fetujou.}
{472}{}{Moc po mnì neèum ty hovado. Já ti nepodrím...}
{473}{}{Vítej otrokáøi! Hledáš nìjakı osvìení?}
{474}{}{Jestli nìkde v New Reno dokáeš najít levnìjší holku, tak se s ní oením.}
{475}{}{Sladší prdelky nenajdeš nikde v celım New Reno.}
{476}{}{Hej otrokáøi ty vypadáš jako chlap s opravdovım ohnìm v poklopci.}
{477}{}{Na slovíèko, otrokáøi. Mìl bych tu pro tebe holku, co tì udrí vzhùru celou noc.}
{478}{}{Vy máte prachy a já tu mám pár nadrenejch koèièek. Tak co kdybychom to dali dohromady?}
{479}{}{Nepotøebuješ na dnešní veèer spoleènost, otrokáøi? Já ti obstarám tu nejfajnovìjší.}
{480}{}{Tohle nejsou ádnı otrokynì. To jsou øádnı zamìstnankynì, rozumíš?}
{481}{}{Máš nìjakı zboí na prodej, otrokáøi? Potøeboval bych trochu èerstvı krve.}
{482}{}{Mám tu jednu specialistku co dokáe vcucnout golfovej míèek skrz zahradní hadici.}
{483}{}{Moje enskı z tebe udìlají skuteènıho chlapa. A stojí jen pár babek.}
{484}{}{Ty nejlepší kobylky najdete v mı stáji.}
{485}{}{Hej otrokáøi, jestli se nìkterá z mejch holek ztratí, tak si tì podám. Je ti to jasnı?}
{486}{}{Nejsem jen tak nìkdo, otrokáøi. Já byl dva roky po sobì zvolenej Pasákem roku.}
{487}{}{Na tuhle koèièku by ses mìl mrknout zblízka otrokáøi; takovı kozy jen tak nìkde neuvidíš.}
{488}{}{Teï nemám zájem kupovat ádnı otroky. Ale moná ti jich za èásek pár prodám.}
{489}{}{Na moje holky nic nezkoušej, otrokáøi.}
{490}{}{Dej si bacha, a tì nechytím, e do mıch holek cpeš nìjakı svinstvo, otrokáøi.}
{491}{}{Ten zmrd Myron zase udìlal polovinì mıch holek cucfleky.}
{492}{}{Jestli zas nachytám Myrona jak dìlá na mejch holkách pokusy, rozkopu mu koule.}
{493}{}{Jestli nìkterá z mıch holek zmizí, tak tebe si podám jako prvního. Je ti to jasnı?}
{494}{}{Jestli nìkde v New Reno najdeš levnìjší šlapku, ne mám já, tak se s ní oením.}
{495}{}{Vítej otrokáøi! Hledáš nìjakı rozptılení?}
{496}{}{Jestli si na mnì ta èubka nepøestane otvírat hubu, tak pro tebe moná budu mít na prodej nìjakı zboí.}
{497}{}{Otrokáøi jsou v tomhle mìstì vdycky vítáni.}

# 12. (FEMALE SLAVER)
{500}{}{Já si svoje prachy radši vydìlávám takhle...}
{501}{}{Letošní sezóna stojí za hovno. Turisti jen chlastaj a fetujou.}
{502}{}{Moc na mì neèum dìvko...}
{503}{}{Sladší prdelky nenajdeš nikde v celım New Reno.}
{504}{}{Hledáš spoleènost na dnešní veèer, otrokáøko? enskı i chlapi, mladı nebo starı... mám všechno co chceš.}
{505}{}{Na tuhle koèièku by ses mìla mrknout zblízka otrokáøko; takovı kozièky jen tak nìkde neuvidíš.}
{506}{}{Nazdar otrokáøko... nepotøebuješ trochu protáhnout komín?}
{507}{}{Máš u nìkoho, kdo ti dneska veèer zahøeje postılku, otrokáøko?}
{508}{}{Hej otrokáøko, jestli nìkterá z mıch holek zmizí, tak si tì podám. Je ti to jasnı?}
{509}{}{Jestli si na mnì ta èubka nepøestane otvírat hubu, tak pro tebe moná budu mít na prodej nìjakı zboí.}
{510}{}{Teï nemám zájem kupovat ádnı otroky. Ale moná ti jich za èásek pár prodám.}
{511}{}{enská je stejnì jen zbyteènej kus masa okolo... no vdy ty víš okolo èeho.}
{512}{}{Otrokáøe v tomhle mìstì vdycky rádi vidíme.}

# 13. (MALE, NO REP)
{520}{}{Já si svoje prachy radši vydìlávám takhle...}
{521}{}{Letošní sezóna stojí za hovno. Turisti jen chlastaj a fetujou.}
{522}{}{Moc po mnì neèum vylízanèe. Já ti nepodrím...}
{523}{}{Anál, orál, klasika... tady najdeš všechno na co máš chu - staèí mít jen prachy.}
{524}{}{Hledáš nìjakı povyraení?}
{525}{}{Moje holky jsou všechny zdravı a èistı. Lepší nenajdeš v celım New Reno...}
{526}{}{Šavnatìjší prdelky nenajdeš nikde v celım New Reno.}
{527}{}{Hej chlape ty vypadáš, e bys na nìm udrel kbelík s vodou.}
{528}{}{Na slovíèko pøíteli. Dneska tu máme speciální slevy pro turisty.}
{529}{}{Ty máš prachy a já tu mám pár nadrenejch koèièek. Tak co kdybychom to dali dohromady?}
{530}{}{Nepotøebuješ na dnešní veèer spoleènost, kámo? Já ti jí obstarám.}
{531}{}{To nejsou ádnı otrokynì ty blbe. To jsou øádnı zamìstnankynì, rozumíš?}
{532}{}{Tady najdeš ty nejlepší dámy v celém New Reno. Udìlají všechno, co ti na oèích uvidí... kdy máš prachy.}
{533}{}{Mám tu jednu specialistku co dokáe vcucnout golfovej míèek skrz zahradní hadici.}
{534}{}{Moje enskı co z tebe udìlají skuteènıho chlapa. A stojí jen pár babek.}
{535}{}{Ty nejlepší kobylky najdeš jedinì v mı stáji.}
{536}{}{Nazdar mladej. Víš, e jsem byl dva roky po sobì zvolenej Pasákem roku?}
{537}{}{Mrkni na tuhle, mladej; takovı dudy nenajdeš v celım New Reno.}
{538}{}{Nesnáším, kdy nìkdo dìlá mejm holkám cucfleky.}
{539}{}{Jasnì, e to mají nejradši zezadu. Taky se pøed tím nerad zdruješ s èištìním zubù, co?}
{540}{}{Nìha? Opravdovej hlubokej cit? No jasnì, to není ádnej problém... za pøíplatek.}
{541}{}{Vidím, e jsi opravdovej znalec brácho. Tak jen si pojï vybrat.}
{542}{}{Máš chu se tøít, vokoune? U mnì si urèitì vybereš.}
{543}{}{Mám ty nejfajnovìjší dìvky v celım New Reno. Zkus je a uvidíš.}

# 14. (FEMALE, NO REP)
{550}{}{Já si svoje prachy radši vydìlávám takhle...}
{551}{}{Letošní sezóna stojí za hovno. Turisti jen chlastaj a fetujou.}
{552}{}{Moc na mì neèum dìvko...}
{553}{}{::Znalecky si tì prohlíí::}
{554}{}{Hej zlatíèko, pojï si na chvilku popovídat.}
{555}{}{Na slovíèko kotì. Mìl bych pro tebe zajímavou nabídku.}
{556}{}{Pojï blí a si mùu zblízka prohlídnout tu tvojí prdelku.}
{557}{}{Pojï se mnou miláèku. Vymaèkám ti z tı tvı buchtièky trochu šávièky.}
{558}{}{Ahoj krásko. Hledáš nìjakou lehkou a vınosnou práci na èerstvım vzduchu?}
{559}{}{Mìl bych pro tebe zajímavou práci; takovou pøi kterı mùeš skoro poøád leet.}
{560}{}{Dìlej pro mnì kotì. Volná pracovní doba, cílové prémie a zdravotní i sociální pojištìní.}
{561}{}{Zùstaò tady u mnì, brouku. Tohle je ten nejlepší plac v celım New Reno.}
{562}{}{Máš u svoje místeèko krásko? Mùeš zùstat tady u mnì.}
{563}{}{::Zkoumavì se na tebe dívá::}
{564}{}{Pìkná figura dìvèe. S tou si tu mùeš vydìlat majlant.}
{565}{}{Jestli nechceš mít na ksichtì jizvu, tak se radši hezky rychle ztra.}
