#tento soubor pøeloil Somnambulus...somnambulus@hotmail.com
# QUICK LOOK
{100}{}{Vidíš prostitutku.}

# EXAMINE
{150}{}{Vidíš...ehm, dámu veèera. Její rozedrané šaty stìí zakrıvají její tìlo.}
{151}{}{Vidíš šlapku. Mrká na tebe.}
{152}{}{Vidíš dìvku. Její oèi jsou jak roznìtky.}
{153}{}{Vidíš prodejnou holku. Voní jako kvìtiny.}
{154}{}{Vidíš prostitutku. Voní jako mámin polštáø.}
{155}{}{Vidíš dìvku. Je ti záhadou, jak ty sporé hadøíky zvládnou udret její prsa ve vıstøihu.}
{156}{}{Vidíš šlapku. Tváøí se, jako by chtìla zabít a sníst své kolegynì.}
{157}{}{Vidíš kurvu. Ohodnotila tì letmım pohledem klenotníka.}
{158}{}{Vidíš prostitutku. Její sporé šaty obepínají svádivì její tìlo.}

# 1. [MALE, ENCLAVE DESTROYED]
{175}{}{Ach boe...to je on.}
{176}{}{Jsi ten nejvìtší borec na svìtì.}
{177}{}{::Omdlévá::}
{178}{}{Podívejte holky, to je pøece }
{179}{}{::Tleská::}
{180}{}{::Zdálky tì zdraví::}
{181}{}{Ach boe...to je ona.}
{182}{}{To byla skvìlá práce, holka!}
{183}{}{::Dává ti znamení vztyèenım palcem::}

# 2. [POWER ARMOR]
{190}{}{Tsss...tolik penìz nemáš, abych to s tebou dìlala, kdy máš na sobì TOHLE.}

# 3. [MALE, PORN STAR]
{195}{}{Hele, kouknìte se, to je }
{196}{}{Podívejte! To je on!}
{197}{}{Ahoj, }
{198}{}{Ahoj cukrouši. Máš nìjaké nemravnı návrhy, na kterı bych mohla kıvnout?}
{199}{}{Kdy vyjde tvùj novı film?}
{200}{}{Mmmm-mmmm. Jsi skvìlej zlato.}
{201}{}{Nepotøebuješ od mnì nìco, bejku?}
{202}{}{Safra, upustila jsem ti nìco do kalhot. Nech mì to najít.}
{203}{}{Hroznì ses mi líbil ve "Anál Hills 90210".}
{204}{}{Nejvíc ses mi líbil v "Sexmeralda: Orgie v zeleném".}
{205}{}{Miluji tì v "Policejní dekadence 5".}
{206}{}{Byl jsi skvìlej v "Star Trek: Nová Ejakulace".}
{207}{}{Hmmmm. Jak se udruješ v kondici?}
{208}{}{Dáš mi svùj autogram? Sem na mùj hrudník...}
{209}{}{Mùu hrát v tvım dalším filmu?}
{210}{}{S tebou bych ten orgasmus ani nemusela pøedstírat, }
{211}{}{Slábnu. U to...dlouho...nevydrím. Musím...se s tebou...vyspat...}

# 4. [PORN STAR, FEMALE]
{212}{}{Není to ádná hvìzda, jenom obyèejná divošská špína...}
{213}{}{Nikdy by mì nenapadlo, e dovolí pornohvìzdám, aby byly TAK tlustı...}
{214}{}{Je hnusná.}
{215}{}{Má sexappeal mokrıho papírovıho sáèku...}
{216}{}{Ošklivá jak nespláchnutej záchod.}
{217}{}{Podle toho jak mizernì hraje, by si èlovìk myslel, e je to spíš akèní hrdinka a ne pornohvìzda.}
{218}{}{Jestli si nìco zkusí, vyškrábu jí oèi...}
{219}{}{Nevím, co na NÍ Korsickı bratøi vidí...}
{220}{}{Má talent jak paøez a je dvakrát tak hnusnìjší.}
{221}{}{Tak je to správnı, pokraèuj hezky v cestì.}
{222}{}{U jen z pohledu na ní, se mi dìlá špatnì...}
{223}{}{Koukni na ni, jak si tu vykraèuje, štìtka jedna...}
{224}{}{Jenom brahmín se mùe zamilovat do toho jejího ksichtu.}
{225}{}{A o nás øíkají, e jsme dìvky...}
{226}{}{Není to ta malá ubohá kurvièka...?}
{227}{}{Jestlipak to není ta malá pornohvìzdièka...?}
{228}{}{Hnusnìjší ne brahmíní prdel.}
{229}{}{Vypadni! Tohle je naše místo, dìvko!}
{230}{}{Ukliï tu svojí prdel nìkam, kde ji neuvidím.}
{231}{}{Jsi talentovaná, asi jako moje ponoka.}
{232}{}{Zùstaò na tıhle ulici a sejmeme tì.}
{233}{}{Mrcho.}
{234}{}{Nafoukaná dìvka...}
{235}{}{Šmejde...}
{236}{}{Tsss!}
{237}{}{Vypadni, kazíš nám kšefty.}
{238}{}{Hnusná dìvko.}
{239}{}{Nemluv na mì, mrcho.}
{240}{}{Jdi si vydìlávat prachy tím svım pomalım zpùsobem, dìvko.}
{241}{}{Které èásti z vìty "Jdi do prdele" nerozumíš?}
{242}{}{Promluv na mì znovu a vyøíznu ti jazyk.}
{243}{}{Poulièní coura.}
{244}{}{::Ignoruje tì.::}
{245}{}{::Dìlá na tebe obscénní gesto::}
{246}{}{Vypadni, "Sleèno Filmová Hvìzdo."}
{247}{}{Nakopejte tu dìvku.}
{248}{}{Zkus si tu nìco a uøíznu ti kozy...}
{249}{}{Nevím, co na NÍ Korsickı bratøi vidí...}
{250}{}{Máš talent asi jako paøez a jsi dvakrát tak hnusnìjší.}
{251}{}{Nemluvím se ŠMEJDEMA jako jsi ty.}

# 5. [MALE, PRIZEFIGHTER]
{252}{}{Èíhnìte na ty svaly! Cítím se tak slabá...}
{253}{}{Sááákra!}
{254}{}{::Píská na tebe::}
{255}{}{Má figuru jak tank. Mrknìte se na ty bicepsy.}
{256}{}{Koukejte na ty stehna...}
{257}{}{Ten musí bıt mùj...}
{258}{}{::Touebnì vzdychá::}
{259}{}{To je ale hajzlík.}
{260}{}{Kdy se na mì podívá, taju jako sníh.}
{261}{}{Není tohle náš král ringu...?}
{262}{}{Máš "nabitej" kvér, drahouši?}
{263}{}{Podívejte! To je }
{264}{}{}
{265}{}{Tady má nìkdo v poklopci problém, kterı chci vyøešit.}
{266}{}{Chceš si to se mnou rozdat v mım ringu, šampióne?}
{267}{}{Chceš si "zaboxovat", šampióne?}
{268}{}{Nikdo nemùe odolat bejkovi jako je }
{269}{}{Hledáš mì?}
{270}{}{Proè se tu nestavíš èastìji?}
{271}{}{Mám jedno pøání, kterı mi mùeš splnit jen ty.}
{272}{}{Potøebuješ spoleènost, }
{273}{}{Ty seš TAKOVEJ hajzl.}
{274}{}{Znervózòuješ mì, víš to?}
{275}{}{Máš hezkı náøadíèko, brouku.}
{276}{}{Potøebuješ, aby se ti o to nìkdo postaral, šampióne?}
{277}{}{Hej...dej si pozor na dímaèku. Je to fakt blb. Jednou se pokoušel ukousnout mi ucho.}

# 6. [FEMALE, PRIZEFIGHTER]
{278}{}{Podívejte! To je }
{279}{}{Hledáš spoleènost, }
{280}{}{}
{281}{}{To je ale mrcha. Chtìla bych umìt nakopat ty hnusnı chlapy, stejnì jako to umí ona.}
{282}{}{Á tady jde naše tvrdá enská.}
{283}{}{Vypadá opravdu...(chvìje se)...nebezpeènì.}
{284}{}{Je dìsnì sexy.}

# 7. [MADE MAN]
{285}{}{Ach boe...to je on. }
{286}{}{Vypadá opravdu...(chvìje se)...nebezpeènì.}
{287}{}{Sákryš!}
{288}{}{::Píská na tebe::}
{289}{}{To je ale hajzl.}
{290}{}{Ten kluk mì znervózòuje.}
{291}{}{Má tvrdo v poklopci, to je sakra jistı.}
{292}{}{Nazdááár, }
{293}{}{Nepotøebuješ spoleènost, }
{294}{}{}
{295}{}{Ach boe...to je ona. }
{296}{}{To je ale potvora.}
{297}{}{Tady kráèí nejvìtší mrcha z New Reno.}
{298}{}{Vypadá opravdu...(chvìje se)...nebezpeènì.}
{299}{}{Je dìsnì sexy.}

# 8. [SLAVER]
{300}{}{Moje jméno je Povolná, otrokáøi. A tvoje?}
{301}{}{Hej, otrokáøi, nepotøebuješ spoleènost?}
{302}{}{Nauèím tì pár vìcí, kterı tì mùe nauèit pouze ena.}
{303}{}{Nepotøebuješ nìkoho, kdo by ti zahøál postel, otrokáøi?}
{304}{}{Zdá se, e máš v koulích pøetlak, otrokáøi. Neulevíme jim spolu trochu?}
{305}{}{Máš tam malou neposednou kobru.}
{306}{}{Hledáš nìjakı vzrušení?}
{307}{}{Otrokáøi, dokud ses nemiloval v New Reno, nevíš, co je to láska.}
{308}{}{Chceš si dát rande?}
{309}{}{Slyšela jsem, e se nìco stalo v Obchodní ètvrti...}
{310}{}{Hledáš spoleènost?}
{311}{}{Chceš si zaskákat?}
{312}{}{Otrokáøi, dokud ses nemiloval v New Reno, nevíš, co je to láska.}
{313}{}{Ale jistìe se stanu tvojí "spoleènicí"... za pár doláèù.}
{314}{}{Zdá se, e do mìsta pøišel cizinec...}
{315}{}{Chceš si zalítat, otrokáøi?}
{316}{}{Chceš si zahrát na otrokáøe a jeho otrokyni?}
{317}{}{Chlapák...hmm}
{318}{}{Nech mì a tì rozveselím, smutnı klaune.}
{319}{}{Zabloudil jsi, otrokáøi?}
{320}{}{Máš zbraò, kterou potøebuješ vyprázdnit, otrokáøi?}
{321}{}{Tenhle chlap by mohl drtit elezo.}
{322}{}{Myron? Toho bych se nedotkla ani za milion. Zvedni to na dva miliony.}
{323}{}{Chceš pøíjemnì strávit hodinku, otrokáøi?}
{324}{}{Líbí se mi pohled na tvıho ptáka, otrokáøi. Proè ho nevyndáme z klece?}
{325}{}{To je ještìrka? To ve tvé kapse?}
{326}{}{Haló tady jsem, otrokáøi.}
{327}{}{Chceš si dát rande, otrokáøi?}
{328}{}{Kde je tvùj oheò, otrokáøi?}
{329}{}{Pojï chlapèe, udìlám z tebe mue.}
{330}{}{Chceš si zahrát na otrokáøe a otrokyni?}
{331}{}{Zahrajeme si na deathclawy v dobì páøení.}
{332}{}{Nepotøebuješ nìkde nìco rozepnout, otrokáøi?}
{333}{}{Pomùeš pannì zbavit se jejího panenství?}
{334}{}{Vdycky kdy tì vidím, zaènou mi moje biologické hodiny tikat.}
{335}{}{Jestli chceš, abych ti pøitom nenadávala, bude za to extra pøíplatek.}
{336}{}{[Zpívá.] "Jsi moje kláda, moje kláda... kterou já mám nadevše ráda."}
{337}{}{Vsaï si na mì, otrokáøi. Jsem tvùj èernej kùò.}
{338}{}{Pojï se mnou. Mám na hlavì instalovanej drák na nápoje.}
{339}{}{Ochutnávka ráje tì bude stát jen deset babek.}
{340}{}{Chceš si zahrát na otrokáøe a otrokyni?}
{341}{}{Hmm... Myron. To je spousta vosku a ádnej knot.}
{342}{}{Myron je opravdovı trdlo... kouø bez ohnì.}
{343}{}{Myron je pes, kterej štìká, ale nikdy nekousne.}
{344}{}{Co ode mne èeká, e udìlám? e se pøed ním ohnu v pase ??}
{345}{}{Potøebuješ nìkoho kdo ti olíe tu tvou tkanièku, otrokáøi?}
{346}{}{Myron poøád otravuje...}
{347}{}{Ta Bishopova holka je fakt mazlík do postele.}
{348}{}{Ta není závislá na Jetu, ale na penisech.}
{349}{}{V Koèièí Pacce jim zaèíná hoøet pùda pod nohama...}
{350}{}{Minulou noc jsem si zabìhla maraton. Kdy jsem utíkala pøed Myronem...}
{351}{}{Hledáš nìjakı vzrùšo, otrokáøi?}
{352}{}{Jsem na tripu u od vèerejška...}
{353}{}{Líbí se ti nìco z toho co vidíš, otrokáøi?}
{354}{}{Hledáš lásku, otrokáøi?}
{355}{}{Hej tady, otrokáøi! Pojï si pokecat.}
{356}{}{::Píská na tebe::}
{357}{}{Zùstaneš v Renu dlouho?}
{358}{}{Nesnáším cucfleky.}
{359}{}{Proè si mì nevezmeš s sebou do svı klícky, otrokáøi?}
{360}{}{Moje pozornost pøece stojí za tìch pár šupù, ne?}
{361}{}{Pravá New Reno láska... právì tady a právì teï.}
{362}{}{Chci si s tebou na nìco zahrát.}
{363}{}{Já jsem Filcky Spice.}
{364}{}{Já jsem Kapavka Spice.}
{365}{}{Já jsem Šlapka Spice.}
{366}{}{Já jsem Old Spice.}
{367}{}{Já jsem Syfilis Spice.}
{368}{}{Já jsem Stará Špajz.}
{369}{}{Rvaèky v prachu, to je pøesnì to co hledám.}
{370}{}{Jestli jsi bi, tak mám ochotného pøítele, otrokáøi.}
{371}{}{Pøála bych si, aby byl Myron teplej.}
{372}{}{Èerstvı maso ve mìstì...}
{373}{}{To by mì zajímalo proè se to tu jmenuje Ulice Panen...}
{374}{}{Umíš svım penisem pøibít 6-ti palcovı høebík?}
{375}{}{Nìkdy si pøeju, aby si dal pøes hlavu papírovı pytlík...}
{376}{}{Koupíš sleènì pití, otrokáøi?}
{377}{}{Vezmeš osamìlou enu do mìsta, otrokáøi?}
{378}{}{Potøebuješ pøítelkyni na noc, otrokáøi?}
{379}{}{Hledáš nìjaké nové zboí, otrokáøi?}
{380}{}{Pojï sem, otrokáøi a mùeme zaèít šou...}
{381}{}{Slyšela jsem, e nìkterı holky zabili svıho pasáka.}
{382}{}{Nejkrásnìjší enská široko daleko a musím trèet zrovna tady...}
{383}{}{Ten Jules a mì radši neotravuje.}
{384}{}{Poøád ještì mám na zádech tu odøeninu od stolu...}
{385}{}{Jsem ještì utahaná z tı minulı konference otrokáøù...}
{386}{}{Pøála bych si, aby se ty otrokáøskı sjezdy konaly v jinım mìstì.}
{387}{}{Myslela jsem, e cítím jak se Zemì pohnula, ale to bylo tìma fazolema k veèeøi.}
{388}{}{Zahøej mì, kotì.}
{389}{}{Za to, e tu udruje poøádek, by mu mìli postavit pomník...}
{390}{}{Já se o tebe postarám, otrokáøi.}
{391}{}{Jsem panna. Ale nejsem v tom moc dobrá.}
{392}{}{Julese najdeš na Druhé ulici...}
{393}{}{Hej, otrokáøi! Nepotøebuješ prùvodce?}
{394}{}{Jules chce poøád volòásky.}
{395}{}{Nepotøebuješ si vyprášit pytel, otrokáøi?}
{396}{}{Rodiny prı mají mezi sebou zase nìjakı tøenice.}
{397}{}{Byznys stagnuje. U aby dorazila ta karavana.}
{398}{}{Take on se pøevlíkl za deathclawa a pak...}
{399}{}{Potøebuju pomoc dostat se z tìchhle šatù.}
{400}{}{Zapneš mì? A pak rozepneš?}
{401}{}{Mmm-mmm. Vypadá to tu jak v období páøení.}
{402}{}{Potøebuješ pøítelkyni?}
{403}{}{Minulı víkend jsem kopla Julese pøímo do tı jeho ozdoby.}
{404}{}{Jdeš se mrknout do centra, otrokáøi?}
{405}{}{Neøíkají mi Šastná holka jen tak pro nic za nic.}
{406}{}{Miluji kondomy s vùní brahmín.}
{407}{}{Udìláš dámì dobøe, otrokáøi?}
{408}{}{Myron mì poøád otravuje. Ale ty jeho prachy se zas hodí.}
{409}{}{Všechno, co jsi kdy potøeboval, je tady.}
{410}{}{Hledáš ráj? Tak jsi ho právì našel.}
{411}{}{Ty máš prachy, otrokáøi, já zase èas.}
{412}{}{Pomùeš mi? Hledám svou ztracenou nevinnost.}
{413}{}{Jsem ještì panna. Nedìlala bych to, nepotøebovat prachy.}
{414}{}{Buï nìnı, dneska je to "poprvé".}
{415}{}{Jsem dìsnì nadrená.}
{416}{}{Ty proiješ let, já budu mít na fet.}
{417}{}{Probudím v tobì duši dítìte.}
{418}{}{Chceš si zatrsat, zlato?}
{419}{}{Hledáš kde hodit kotvu?}
{420}{}{Chceš mì slyšet sténat?}
{421}{}{::Dìlá rukama obscénní gesta::}
{422}{}{::Špulí ústa::}
{423}{}{::Posílá ti vzdušnı polibek::}
{424}{}{Chceš si vrznout?}
{425}{}{Nejsem sice nejlevnìjší, ale zato dìlám i "speciality".}
{426}{}{Za svázání si musíš pøiplatit, brouku.}
{427}{}{Kam jsem zas dala ten biè?}
{428}{}{Vstávej semínko holala, bude z tebe fiala...}
{429}{}{Mám se prı oblíknout jako vèera v noci DÁŠA pro Vencu.}
{430}{}{Vèera jsem to dìlala s Myronem. Asi 5 sekund.}
{431}{}{Ké by vynalezli nìjaké tìlové oleje vonící po Jetu...}
{432}{}{Zadek u mi málem upadl a Myron poøád nemìl dost.}
{433}{}{To proklatı Protialkoholickı hnutí tu zas opruzovalo...}
{434}{}{::Píská si nìjakou melodii::}
{435}{}{Garantuju ti, e jsem lepší, ne ta vakuová pumpa Pip Boy, kterou pouíváš.}
{436}{}{Chceš abych ti dotáhla závity, otrokáøi?}
{437}{}{Vèera jsem byla se Somnambulem. Škoda, e nemá všechno tak dlouhı jako svojí pøezdívku.}
{438}{}{Ké by tu byl Radar. Dokáe tak krásnì vyprávìt o stahování geckonù z kùe.}
{439}{}{S Raptorem jsme se k tomu ani nedostali. Celou noc vanil o nìjakım komprimovacím algoritmu.}
{440}{}{Mawerick mi pøitom vyprávìl vtipy a pak po mnì chtìl slevu. Prej e za komickou vloku...}
{441}{}{Vida, vida. Koukejte, kdo se to dovalil do mìsta...}
{442}{}{Vypadáš jak vyhonìnej z podoby.}
{443}{}{Oh! Turista!}
{444}{}{Kousání je za extra pøíplatek.}
{445}{}{Jmenuju se Kevšemusvolná, otrokáøko. A ty?}
{446}{}{Hej, otrokáøko. Sháníš enskou?}
{447}{}{Chceš zkusit jakı je to mít enskou, srdíèko?}
{448}{}{Potøebuješ "otrokyni" na dnešní noc, otrokáøko?}
{449}{}{Potøebuješ nìkoho, kdo ti zahøeje klín, otrokáøko?}
{450}{}{Potøebuješ se s nìkım podìlit o postel, otrokáøko?}
{451}{}{Chceš se pomazlit, otrokáøko?}
{452}{}{Otrokáøko, dokud ses nemilovala v New Reno, nevíš, co je to láska.}
{453}{}{Chceš si zalítat, otrokáøko?}
{454}{}{Ztratila ses, otrokáøko?}
{455}{}{Hledáš potìšení, otrokáøko?}
{456}{}{Nevìdìla jsem, e v Cechu otrokáøù mùou bıt i enskı...}
{457}{}{Jsi nadrená otrokáøko?}
{458}{}{Ta otrokáøka je pìknì mazaná.}
{459}{}{Vdycky kdy tì vidím, zaènou mi moje biologické hodiny tikat.}

# 9. (ANY) TO [COMPANION: ROBOBRAIN AND/OR MARCUS]
{460}{}{Zaruèuju ti, e moje otvory jsou mnohem teplejší a mìkèí, ne co má ten tvùj robot.}
{461}{}{Zvládne ten tvùj robot VŠECHNO?}
{462}{}{To je nìjakej druh herní mašiny, to co s tebou jde?}
{463}{}{Má ten tvùj robot nìjakı speciální otvory?}
{464}{}{Umí tvùj robot nìjakı triky? Uh...myslím tím kouzla.}
{465}{}{Øekni, e tohle není mutant.}
{466}{}{Ten mutant ho má urèitì vìtší. Mnohem vìtší.}
{467}{}{A jéje. Mutanti v New Renu. Z toho budou problémy.}
{468}{}{Tenhle mutant je teda fakt poøádnej muouš.}
{469}{}{Ten mutant vypadá, e by mì mohl jednou rukou zamáèknout jak vajgla. Hmmmnnn.}
{470}{}{Ani moc nestojím o to poznat, co mají tihle mutanti rádi.}

# 10. [COMPANION: MYRON]
{471}{}{Ahoj Myrone!}
{472}{}{Myrone! Zlato! Kdy se zase uvidíme?}
{473}{}{My-roneee. Myyyyyy-roneee.}
{474}{}{Myrone, co je zaè ten tvùj roztomilı pøítel?}
{475}{}{Myrone, zlato! Myrone! Nehledáš nìjakou zábavu?}
{476}{}{Jo-ho-ho! Myron!}
{477}{}{Chybìl jsi mi, Myrone!}
{478}{}{Myrone, jsi fakt dokonalej. No, více ménì dokonalej.}
{479}{}{Myrone, kdy se zas uvidíme?}
{480}{}{Mùeš mi sehnat nìjakı Jet, Myrone?}
{481}{}{Kdy mi doneseš Jet na pozvednutí nálady, Myrone?}
{482}{}{Pomueš mi s lítáním, Myrone?}

# 11. [PLAYER IS MALE] + [COMPANION: BONE-NOSE]
{483}{}{Moje jméno je Povolná. A tvoje?}
{484}{}{Hej, brouku, nepotøebuješ spoleènost?}
{485}{}{Nauèím tì pár vìcí, kterı tì mùe nauèit pouze ena.}
{486}{}{Potøebuješ nìkoho, kdo by ti dechem zahøál klín?}
{487}{}{Potøebuješ se s nìkım podìlit o svou postel?}
{488}{}{Zdá se, e máš v koulích pøetlak, kotì. Neulevíme jim spolu trochu?}
{489}{}{Máš tam malou neposednou kobru, co?}
{490}{}{Nehledáš nìjakou zábavu?}
{491}{}{Dokud se nepomiluješ v New Reno, nevíš, co je to láska.}
{492}{}{Chceš si dát rande?}
{493}{}{Slyšela jsem, e se nìco stalo v Obchodní ètvrti...}
{494}{}{Hledáš spoleènost?}
{495}{}{V poslední dobì je v Renu nejoblíbenìjším sportem skok pøes štìtku...}
{496}{}{Chceš si zatanèit?}
{497}{}{Zapomeò na toho robota. Moje nabídka je daleko lepší.}
{498}{}{Bylo neuvìøitelnı, kolik mìl Vachy na tom veèírku svobodnejch pánù striptérek.}
{499}{}{Zdá se, e do mìsta pøišel cizinec...}
{500}{}{Dokáeš svım penisem pøibít 6-ti palcovı høebík?}
{501}{}{Chceš si zalítat?}
{502}{}{U dlouho nebylo vidìt ádnı karavany z Reddingu.}
{503}{}{Chlapák...hmm.}
{504}{}{Nech mì a tì rozveselím, smutnı klaune.}
{505}{}{Ztratil jsi cestu, kovboji?}
{506}{}{Máš nìjakou zbraò, kterou chceš vybít, vojáèku?}
{507}{}{Tenhle chlap by mohl drtit elezo.}
{508}{}{Tolik nadrencù a tak málo èasu...}
{509}{}{Šlapu teprve od vèerejší noci...}
{510}{}{Potøebuješ spoleènost na celou noc? Nebo jen na deset minut?}
{511}{}{Hledáš potìšení?}
{512}{}{Jdeš se mrknout do centra?}
{513}{}{Líbí se mi pohled na tvıho ptáèka. Proè ho nevyndáme z klece?}
{514}{}{To je ještìrka? To ve tvé kapse?}
{515}{}{Nepotøebuješ prùvodce mìstem, cukrouši?}
{516}{}{Nemáš oheò, brouku?}
{517}{}{Pojï chlapèe, udìlám z tebe mue.}
{518}{}{Obèas mì chování en v tomhle mìstì uráí.}
{519}{}{Zahrajeme si na deathclawy v dobì páøení?}
{520}{}{Vdycky kdy tì vidím, zaènou mi tikat moje biologické hodiny.}
{521}{}{Jestli chceš, abych s tebou potom mluvila, tak si musíš pøiplatit.}
{522}{}{Mùu ti s nìèím pomoci, cizinèe?}
{523}{}{Dokud se nepomiluješ v New Reno, nevíš, co je to láska.}
{524}{}{Ten tvùj pøítel s tou velkou kostí v nose...to je prima poutaè.}
{525}{}{Umí ten tvùj pøítel s tou kostí nìjakı triky ?}
{526}{}{Moná bych si taky mìla do nosu strèit kost. Mohlo by to pøilákat zákaznice.}
{527}{}{Jeišikriste, ta kost co má ten chlap v nose je velká jako moje ruka.}
{528}{}{Radši ani nechci vìdìt jak si tam ten chlap tu kost nacpal.}
{529}{}{Pro koho tvùj pøítel s tou kostí v nosu šlape?}
{530}{}{Jakej pøíplatek si poèítá ten tvùj kámoš za tu kost v nose?}
{531}{}{Za tøicet doláèù tvımu kámošovi tu kost v nose vykouøím....}
{532}{}{Ten tvùj pøítel si tou kostí v nose kompenzuje nìjakej komplex?}
{533}{}{Zkus mnì, zlato. Mám na hlavì instalovanej drák na nápoje.}
{534}{}{Chu ráje? To bude za deset babek.}
{535}{}{Myron. To je spousta vosku a ádnej knot.}
{536}{}{Myron je opravdovı trdlo... spousta kouøe bez ohnì.}
{537}{}{Myron je pes, kterej štìká, ale nikdy nekousne.}
{538}{}{Co si myslí, e udìlám? e se pøed ním ohnu v pase?}
{539}{}{Jestli s tím nìkdo nìco neudìlá, tak ta cedule New Reno brzy na nìkoho slítne...}
{540}{}{Ta Bishopova holka je fakt mazlík do postele.}
{541}{}{Ta není závislá na Jetu, ale na penisech.}
{542}{}{Ve Vault City prej mají jen dva typy Obèanù. To mají z toho jejich klonování.}
{543}{}{Cítím se jako kdybych minulou noc ubìhla maraton...}
{544}{}{Hledáš lásku. brouèku?}
{545}{}{Ké by se Myron odstìhoval. Nìkam hodnì daleko.}
{546}{}{Udìlám ti co budeš chtít... kdy na to budeš mít prachy.}
{547}{}{Já mùu tøeba hned, kotì. A co ty?}
{548}{}{::Hvízdá na tebe::}
{549}{}{Nesnáším cucfleky.}
{550}{}{Sice jsem to zrovna dostala, ale jak tak na tebe koukám, tobì trocha krve nevadí, e ne?}
{551}{}{Hledáš zábavu?}
{552}{}{Nefalšovaná New Reno láska, právì tady a právì teï.}
{553}{}{Mùeme si spolu na nìco zahrát.}
{554}{}{Já jsem Filcky Spice.}
{555}{}{Já jsem Kapavka Spice.}
{556}{}{Já jsem Šlapka Spice.}
{557}{}{Já jsem Old Spice.}
{558}{}{Já jsem Syfilis Spice.}
{559}{}{Já jsem Stará Špajz.}
{560}{}{Rvaèky v prachu, to je pøesnì to co hledám.}
{561}{}{Jestli jsi na trojky, tak mám ochotnou pøítelkyni.}
{562}{}{Pøála bych si, aby byl Myron teplej.}
{563}{}{Èerstvı maso ve mìstì...}
{564}{}{To by mì zajímalo proè se to jmenuje Ulice Panen...}
{565}{}{Nìkdy si pøeju, aby si dal pøes hlavu papírovı pytlík...}
{566}{}{Koupíš sleènì pití?}
{567}{}{Provedeš osamìlou enu mìstem?}
{568}{}{Mùj boe! Turista!!}
{569}{}{Pojï sem zlato a rozjedem to spolu...}
{570}{}{Slyšela jsem, e nìkterı holky zabili svıho pasáka.}
{571}{}{Haló, cizinèe.}
{572}{}{Ten Jules a u mì radši neotravuje.}
{573}{}{Poøád ještì mám na zádech tu odøeninu od stolu...}
{574}{}{Jsem ještì utahaná z toho minulıho sjezdu...}
{575}{}{Pøála bych si, aby se ty sjezdy barbarù konaly v jinım mìstì.}
{576}{}{Myslela jsem, e se s náma pohnula Zemì, ale to bylo tìma fazolema k veèeøi.}
{577}{}{Zahøej mì, kotì.}
{578}{}{Za to, jak to dìlá, by mu mìli postavit pomník...}
{579}{}{To bzuèení neónu mì pøivádí k šílenství...}
{580}{}{Jsem panna. Ale nejsem v tom moc dobrá.}
{581}{}{Kdy si pomyslím, e jsem sem pøišla z Denu kvùli tomuhle...}
{582}{}{Hej cizinèe! Nepotøebuješ prùvodkyni?}
{583}{}{Jules chce poøád volòásky.}
{584}{}{Rodiny prı mají mezi sebou zase nìjakı tøenice.}
{585}{}{Byznys stagnuje. U aby dorazila další karavana.}
{586}{}{Take on se pøevlíkl za deathclawa a pak...}
{587}{}{Potøebuju pomoc dostat se z tìchhle šatù.}
{588}{}{Zapneš mì? A pak rozepneš?}
{589}{}{Mmm-mmm. Vypadá to na období páøení.}
{590}{}{Nepotøebuješ zabít èas?}
{591}{}{Minulej tejden jsem kopla Julese pøímo do tı jeho ozdoby.}
{592}{}{Neøíkají mi Šastná holka jen tak pro nic za nic.}
{593}{}{Miluji kondomy s vùní brahmín.}
{594}{}{Udìláš dámì dobøe?}
{595}{}{Kdyby tak pro Myrona vynalezli nìjakı sexuální placebo.}
{596}{}{Nechceš si domluvit rande, divochu?}
{597}{}{Chceš si zaskákat, divochu?}
{598}{}{Co takhle zatancovat si váleènı tanec v mı lonici, divochu?}
{599}{}{Všechno co potøebuješ, je jedna noc se mnou.}
{600}{}{Hledáš rajskou zahradu? Pøijï do mı lonice.}
{601}{}{Ty máš prachy, já zas èas.}
{602}{}{Pomùeš mi? Hledám svou ztracenou nevinnost.}
{603}{}{Jsem ještì panna. Nedìlala bych to, nepotøebovat prachy.}
{604}{}{Buï nìnı, dneska je to poprvé.}
{605}{}{Jsem hroznì nadrená.}
{606}{}{Ty proiješ let, já budu mít fet.}
{607}{}{Probudím v tobì duši dítìte.}
{608}{}{Chceš si zatrsat, zlato?}
{609}{}{Hledáš kde hodit kotvu?}
{610}{}{Chceš mì slyšet sténat?}
{611}{}{::Dìlá rukama obscénní gesta::}
{612}{}{::Špulí ústa::}
{613}{}{::Posílá ti vzdušnı polibek::}
{614}{}{U dvì noci jsem nespala...}
{615}{}{Nejsem sice nejlevnìjší, ale zato dìlám i speciality.}
{616}{}{Za svázání si musíš pøiplatit, brouku.}
{617}{}{Kam jsem zas dala ten biè?}
{618}{}{Vstávej semínko holala, bude z tebe fiala.}
{619}{}{Mám se prı oblíknout jako vèera v noci DÁŠA pro Vencu.}
{620}{}{Vèera jsem to dìlala s Myronem. Asi 5 sekund.}
{621}{}{Nepotøebuješ nìco rozepnout?}
{622}{}{Ké by vynalezli nìjaké parfémy vonící po Jetu...}
{623}{}{Chceš pomoct pannì zbavit se jejího panenství?}
{624}{}{Zadek u mi málem upadl a Myron poøád nemìl dost.}
{625}{}{To pitomı Protialkoholickı hnutí tu zas opruzovalo...}
{626}{}{::Píská na tebe::}
{627}{}{Kousání je za extra pøíplatek.}
{628}{}{Garantuju ti, e jsem lepší, ne ta vakuová pumpa znaèky Pip Boy, kterou pouíváš.}
{629}{}{Chceš abych ti dotáhla závity?}
{630}{}{Vèera jsem byla se Somnambulem. Škoda, e nemá všechno tak dlouhı jako svojí pøezdívku.}
{631}{}{Ké by tu byl Radar. Dokáe tak krásnì vyprávìt o stahování geckonù z kùe.}
{632}{}{S Raptorem jsme se k tomu ani nedostali. Celou noc vanil o nìjakım komprimovacím algoritmu.}
{633}{}{Mawerick mi pøitom vyprávìl vtipy a pak po mnì chtìl slevu. Prej e za komickou vloku...}
{634}{}{Vida, vida. Koukejme, kdo se to dovalil do mìsta.}
{635}{}{Hledáš rajskou zahradu? Pøijï do mı lonice.}
{636}{}{Sice jsem to zrovna dostala, ale jak tak na tebe koukám, tobì trocha krve nevadí, e ne?}
{637}{}{Jmenuju se Povolná, sleèno. A vy?}
{638}{}{Ahoj drahoušku. Sháníš holku?}
{639}{}{Chceš zkusit jakı je to mít enskou, srdíèko?}
{640}{}{Hledáš spoleènost?}
{641}{}{Holka, nech mì, a tì nauèím to, co tì mùe nauèit jen ENA.}
{642}{}{Sháníš nìkoho kdo ti zahøeje klín, dìvèe?}
{643}{}{Sháníš nìkoho, s kım se podìlit o postel, miláèku?}
{644}{}{Chceš si zatanèit, drahoušku?}
{645}{}{Zapomeò na tu pitomou mašinu, miláèku. Moje nabídka je MNOHEM lepší.}
{646}{}{Holka, dokud ses nepomilovala v New Reno, nevíš, co je to láska.}
{647}{}{Chceš si zalítat, pusinko?}
{648}{}{Ztratila ses, kotì?}
{649}{}{Potøebuješ si vybít zbraò, G.I. Jane?}
{650}{}{Hledáš zábavu, drahoušku?}
{651}{}{Hledáte cestu do centra, sleèno?}
{652}{}{Nepotøebuješ prùvodce mìstem, lásko?}
{653}{}{Nemáš oheò, dìvèe?}
{654}{}{Z tı enskı se mi roztikaly moje biologické hodiny.}

# 12. [NO REP]
{655}{}{Jmenuju se Vlhká. A ty?}
{656}{}{Hledáš spoleènost?}
{657}{}{Nauèím tì pár vìcí, kterı tì mùe nauèit pouze ena.}
{658}{}{Nepotøebuješ nìkoho, kdo by ti zahøál klín?}
{659}{}{Nechceš se s nìkım podìlit o svou postel?}
{660}{}{Zdá se, e máš v koulích pøetlak, kámo. Neulevíme jim spolu trochu?}
{661}{}{Máš tam malou neposednou kobru, co?}
{662}{}{Hledáš povyraení??}
{663}{}{Dokud se nepomiluješ v New Reno, nevíš, co je to láska.}
{664}{}{Co si dát u mnì v lonici rande?}
{665}{}{Slyšela jsem, e prı se nìco semlelo v Obchodní ètvrti...}
{666}{}{Sháníš spoleènost?}
{667}{}{V poslední dobì je v Renu nejoblíbenìjším sportem skok pøes štìtku...}
{668}{}{Chceš si zatancovat?}
{669}{}{Vykašli se na toho robota. Já ti nabízím MNOHEM víc.}
{670}{}{To je neuvìøitelnı, kolik mìl Vachy na tom veèírku svobodnejch pánù striptérek.}
{671}{}{Zdá se, e máme ve mìstì dalšího cizince...}
{672}{}{Dokáeš svım penisem pøibít 6-ti palcovı høebík?}
{673}{}{Chceš si zalítat?}
{674}{}{U dlouho tu nebylo vidìt ádnı karavany z Reddingu...}
{675}{}{Hmm... chlapák..}
{676}{}{Nech mì a tì potìším, smutnı klaune.}
{677}{}{Ztratil jsi cestu, kovboji?}
{678}{}{Potøebuješ si vybít zbraò, vojáèku?}
{679}{}{Ten chlap by mohl drtit elezo.}
{680}{}{Tolik nadrenıch lidí a tak málo èasu.}
{681}{}{Šlapu teprve od vèerejška...}
{682}{}{Hledáš pøítelkyni na noc? Nebo jen na deset minut?}
{683}{}{Hledáš zábavu?}
{684}{}{Jdeš se mrknout do centra?}
{685}{}{Líbí se mi pohled na tvıho ptáèka. Proè ho nevyndáme z klece?}
{686}{}{To je ještìrka? To ve tvé kapse?}
{687}{}{Nepotøebuješ prùvodce mìstem, cukrouši?}
{688}{}{Nemáš oheò, brouku?}
{689}{}{Pojï chlapèe, udìlám z tebe mue.}
{690}{}{Mmmmm-mmmmm.}
{691}{}{Zahrajeme si na deathclawy v dobì páøení?}
{692}{}{Vdycky kdy tì vidím, zaènou mi moje biologické hodiny tikat.}
{693}{}{Jestli chceš, abych s tebou potom mluvila, tak si musíš pøiplatit.}
{694}{}{Mùu ti s nìèím pomoci, cizinèe?}
{695}{}{Dokud se nepomiluješ v New Reno, nevíš, co je to láska.}
{696}{}{Zkus mnì, zlato. Mám na hlavì instalovanej drák na nápoje.}
{697}{}{Chu ráje? To bude za deset babek.}
{698}{}{Myron. To je spousta vosku a ádnej knot.}
{699}{}{Myron je opravdovı trdlo... spousta kouøe bez ohnì.}
{700}{}{Myron je pes, kterej štìká, ale nikdy nekousne.}
{701}{}{Co si myslí, e udìlám? e se pøed ním ohnu v pase?}
{702}{}{Jestli s tím nìkdo nìco neudìlá, tak ta cedule New Reno brzy na nìkoho slítne...}
{703}{}{Ta Bishopova holka je fakt mazlík do postele.}
{704}{}{Ta není závislá na Jetu, ale na penisech.}
{705}{}{Ve Vault City prej mají jen dva typy Obèanù. To mají z toho jejich klonování.}
{706}{}{Cítím se jako kdybych minulou noc ubìhla maratón...}
{707}{}{Hledáš lásku. brouèku?}
{708}{}{Ké by se Myron odstìhoval. Nìkam hodnì daleko.}
{709}{}{Udìlám ti co budeš chtít... kdy na to budeš mít prachy.}
{710}{}{Já mùu tøeba hned, kotì. A co ty?}
{711}{}{::Hvízdá na tebe::}
{712}{}{Nesnáším cucfleky.}
{713}{}{Sice jsem to zrovna dostala, ale jak tak na tebe koukám, tobì trocha krve nevadí, e ne?}
{714}{}{Hledáš zábavu?}
{715}{}{Nefalšovaná New Reno láska, právì tady a právì teï.}
{716}{}{Mùeme si spolu na nìco zahrát.}
{717}{}{Já jsem Filcky Spice.}
{718}{}{Já jsem Kapavka Spice.}
{719}{}{Já jsem Šlapka Spice.}
{720}{}{Já jsem Old Spice.}
{721}{}{Já jsem Syfilis Spice.}
{722}{}{Já jsem Stará Špajz.}
{723}{}{Rvaèky v prachu, to je pøesnì to co hledám.}
{724}{}{Jestli jsi na trojky, tak mám ochotnou pøítelkyni.}
{725}{}{Pøála bych si, aby byl Myron teplej.}
{726}{}{Èerstvı maso ve mìstì...}
{727}{}{To by mì zajímalo proè se to jmenuje Ulice Panen...}
{728}{}{Nìkdy si pøeju, aby si dal pøes hlavu papírovı pytlík...}
{729}{}{Koupíš sleènì pití?}
{730}{}{Provedeš osamìlou enu mìstem?}
{731}{}{Mùj boe! Turista!!}
{732}{}{Pojï sem zlato a rozjedem to spolu...}
{733}{}{Slyšela jsem, e nìkterı holky zabili svıho pasáka.}
{734}{}{Halóóó, cizinèe.}
{735}{}{Ten Jules a u mì radši neotravuje.}
{736}{}{Poøád ještì mám na zádech tu odøeninu od stolu...}
{737}{}{Jsem ještì utahaná z toho minulıho sjezdu...}
{738}{}{Kdy u se tu pøestanou courat ti divoši.}
{739}{}{Myslela jsem, e se s náma pohnula Zemì, ale to bylo tìma fazolema k veèeøi.}
{740}{}{Zahøej mì, kotì.}
{741}{}{Za to, jak to dìlá, by mu mìli postavit pomník...}
{742}{}{To bzuèení neónu mì pøivádí k šílenství...}
{743}{}{Jsem panna. Ale nejsem v tom moc dobrá.}
{744}{}{Kdy si pomyslím, e jsem sem pøišla z Denu kvùli tomuhle...}
{745}{}{Hej cizinèe! Nepotøebuješ prùvodkyni?}
{746}{}{Jules chce poøád volòásky.}
{747}{}{Rodiny prı mají mezi sebou zase nìjakı tøenice.}
{748}{}{Byznys stagnuje. U aby dorazila další karavana.}
{749}{}{Take on se pøevlíkl za deathclawa a pak...}
{750}{}{Potøebuju pomoc dostat se z tìchhle šatù.}
{751}{}{Zapneš mì? A pak rozepneš?}
{752}{}{Mmm-mmm. Vypadá to na období páøení.}
{753}{}{Nepotøebuješ zabít èas?}
{754}{}{Minulej tejden jsem kopla Julese pøímo do tı jeho ozdoby.}
{755}{}{Neøíkají mi Šastná holka jen tak pro nic za nic.}
{756}{}{Miluji kondomy s vùní brahmín.}
{757}{}{Udìláš dámì dobøe?}
{758}{}{Kdyby tak pro Myrona vynalezli nìjakı sexuální placebo.}
{759}{}{Nechceš si domluvit rande, divochu?}
{760}{}{Chceš si zaskákat, divochu?}
{761}{}{Co takhle zatancovat si váleènı tanec v mı lonici, divochu?}
{762}{}{Všechno co potøebuješ, je jedna noc se mnou.}
{763}{}{Hledáš rajskou zahradu? Pøijï do mı lonice.}
{764}{}{Ty máš prachy, já zas èas.}
{765}{}{Pomùeš mi? Hledám svou ztracenou nevinnost.}
{766}{}{Jsem ještì panna. Nedìlala bych to, nepotøebovat prachy.}
{767}{}{Buï nìnı, dneska je to poprvé.}
{768}{}{Jsem hroznì nadrená.}
{769}{}{Ty proiješ let, já budu mít fet.}
{770}{}{Probudím v tobì duši dítìte.}
{771}{}{Chceš si zatrsat, zlato?}
{772}{}{Hledáš kde hodit kotvu?}
{773}{}{Chceš mì slyšet sténat?}
{774}{}{::Dìlá rukama obscénní gesta::}
{775}{}{::Špulí ústa::}
{776}{}{::Posílá ti vzdušnı polibek::}
{777}{}{U dvì noci jsem nespala...}
{778}{}{Nejsem sice nejlevnìjší, ale zato dìlám i speciality.}
{779}{}{Za svázání si musíš pøiplatit, brouku.}
{780}{}{Kam jsem zas dala ten biè?}
{781}{}{Vstávej semínko holala, bude z tebe fiala.}
{782}{}{Mám se prı oblíknout jako vèera v noci DÁŠA pro Vencu.}
{783}{}{Vèera jsem to dìlala s Myronem. Asi 5 sekund.}
{784}{}{Nepotøebuješ nìco rozepnout?}
{785}{}{Ké by vynalezli nìjaké parfémy vonící po Jetu...}
{786}{}{Chceš pomoct pannì zbavit se jejího panenství?}
{787}{}{Zadek u mi málem upadl a Myron poøád nemìl dost.}
{788}{}{To pitomı Protialkoholickı hnutí tu zas opruzovalo...}
{789}{}{::Píská na tebe::}
{790}{}{Kousání je za extra pøíplatek.}
{791}{}{Garantuju ti, e jsem lepší, ne ta vakuová pumpa znaèky Pip Boy, kterou pouíváš.}
{792}{}{Chceš abych ti dotáhla závity?}
{793}{}{Vèera jsem byla se Somnambulem. Škoda, e nemá všechno tak dlouhı jako svojí pøezdívku.}
{794}{}{Ké by tu byl Radar. Dokáe tak krásnì vyprávìt o stahování geckonù z kùe.}
{795}{}{S Raptorem jsme se k tomu ani nedostali. Celou noc vanil o nìjakım komprimovacím algoritmu.}
{796}{}{Mawerick mi pøitom vyprávìl vtipy a pak po mnì chtìl slevu. Prej e za komickou vloku...}
{797}{}{Vida, vida. Koukejme, kdo se to dovalil do mìsta...}
{798}{}{Hledáš rajskou zahradu? Pøijï do mı lonice.}
{799}{}{Sice jsem to zrovna dostala, ale jak tak na tebe koukám, tobì trocha krve nevadí, e ne?}
{800}{}{Jmenuju se Povolná, sleèno. A vy?}
{801}{}{Ahoj drahoušku. Sháníš holku?}
{802}{}{Chceš zkusit jakı je to mít enskou, srdíèko?}
{803}{}{Hledáš spoleènost?}
{804}{}{Holka, nech mì, a tì nauèím to, co tì mùe nauèit jen ENA.}
{805}{}{Sháníš nìkoho kdo ti zahøeje klín, dìvèe?}
{806}{}{Sháníš nìkoho, s kım se podìlit o postel, miláèku?}
{807}{}{Chceš si zatanèit, drahoušku?}
{808}{}{Zapomeò na tu pitomou mašinu, miláèku. Moje nabídka je MNOHEM lepší.}
{809}{}{Holka, dokud ses nepomilovala v New Reno, nevíš, co je to láska.}
{810}{}{Chceš si zalítat, pusinko?}
{811}{}{Ztratila ses, kotì?}
{812}{}{Potøebuješ si vybít zbraò, G.I. Jane?}
{813}{}{Hledáš zábavu, dìvèátko?}
{814}{}{Hledáte cestu do centra, sleèno?}
{815}{}{Nepotøebuješ prùvodce mìstem, cukrouši?}
{816}{}{Nemáš oheò, dìvèe?}
{817}{}{Z tı enskı se mi roztikaly moje biologické hodiny.}

# 13. [ENCLAVE DESTROYED]
{818}{}{Enkláva? Prezident? Vyprávìj mi celej ten pøíbìh.}
{819}{}{Tu grafiku pøedìlal Radar. Má opravdu jemné a nìné ruce.}
{820}{}{Oni chtìli poøád ještì vést válku? Fakt!? Díkybohu, e jsi ty bastardy zlikvidoval.}
{821}{}{Jsi fantastickej. Jen si to vem, zaèal jsi - bez uráky - jako divoch s kopím v ruce  
a na konci jsi zabránil zkáze celého svìta. Jsi absolutní jednièka. Konec filmu.}
{822}{}{Mìl by sis tu hru zahrát znova. Kdy si zvolíš jinı typ postavy, tøeba si spolu pøíštì uijeme.}
{823}{}{Pojï, lehneme si spolu do mojí postele a ty mi povíš o svém boji s Enklávou...}
{824}{}{Hej, jestli chceš za tu záchranu svìta èíslo zdarma, jsem si jistá, e se domluvíme...}
{825}{}{Nechápu jak jsi dokázal mezi tìma vrahounama z Enklávy pøeít. Jsi ten nejodvánìjší èlovìk, kterıho znám.}
{826}{}{Somnambulus? Jo, to je mùj stálı zákazník.}
{827}{}{Líbej mì, ty zvíøe.}
{828}{}{Slyšela jsem, e se po tobì shání Korsiètí bratøi. Chtìjí s tebou na motivy tvıho pøíbìhu natoèit pornofilm.}
{829}{}{Mawerick toho pøeloil nejvíc. On je vùbec se VŠÍM rychle hotovej... bohuel.}
{830}{}{Lucifer666 mi slíbil, e mi ukáe svùj HARDWARE. Prı ho má pøetaktovanej....}
{831}{}{Nìkdy mám takovı zvláštní pocit. Jako bych byla jen postava v nìjaké poèítaèové høe. 
Ale ne, to je urèitì jen normální paranoia. To má ve vesmíru skoro kadı.}
{832}{}{Skoro celı New Reno pøeloil Birdman. To je frajer... chtìla bych ho za pasáka.}
{833}{}{Ach jo... vìèná škoda, e je Jirka "Markus" Petrù ještì nezletilı. To nemùu riskovat...}
{834}{}{Tvoje skóre je 192 bodù z 208. Mìl jsi na Horrigana pouít svùj šestı prst.}

# 14. [POWER ARMOR]
{835}{}{Nìjaká ena ti urèitì musela hroznì ublíit, kdy ses rozhodl, zavøít se do té konzervy. Dovol a ti pomùu.}
{836}{}{Hele Plechovko, jestli po mnì chceš, abych si kvùli tobì navlíkla pás cudnosti, tak to bude za extra pøíplatek.}
{837}{}{Hele lásko, jestli na to chceš vlítnout se mnou, tak si to musíš nejdøív sundat. Nechci se o tebe poøezat.}
{838}{}{Dá se ti to nìkde okolo poklopce odšroubovat nebo si to musíš svlíknout celı?}
{839}{}{Bolí to, kdy v tom dostaneš erekci?}
{840}{}{Zdá se, e sis s sebou pøinesl svùj vlastní kondom.}
{841}{}{To je nìjakı celotìlní kondom?}
{842}{}{Ty se fakt musíš hroznì bát pohlavních chorob, kdy na sobì nosíš tohle.}
{843}{}{Jestli chceš abych to s tebou dìlala, kdy máš na sobì tohle, tak jedinì za extra pøíplatek.}
{844}{}{Jestli to chceš dìlat v tomhle, tak na to radši rovnou zapomeò.}
{845}{}{Hmm.. a kdy pøitom zvlhnu, tak to zrezivíš?}
{846}{}{No... tak jo. Ale já budu nahoøe.}
{847}{}{Teda, jak s tímhle chodíš na záchod?}
{848}{}{A jak tì z toho svlíknu? Rozbrušovaèkou?}
{849}{}{To je nìjakı novı druh vibrátoru?}
{850}{}{Jé myslím, e nìjakou podobnou scénu jsem kdysi vidìla v Robocopovi.}
{851}{}{Nehledáš náhodou myèku aut?}
{852}{}{Lituju brouku. Jsem alergická na elezo.}
{853}{}{To je nìjaká nová antikoncepce, to co máš na sobì?}

# 15. [FEMALE, PRIZEFIGHTER]
{854}{}{Nechceš se mnou hupsnout do ringu, lásko? Vydrím nejmíò 12 kol.}
{855}{}{Hele to je }
{856}{}{Holka ty jsi opravdová potvora.}
{857}{}{No teda. Podívejte na ty její svaly. Jsou mohutnìjší ne má vìtšina chlapù co znám. A já znám HODNÌ chlapù.}
{858}{}{Zdravím tì, }
{859}{}{Hledáš mì?}
{860}{}{Proè sem nezajdeš èastìji?}
{861}{}{Potøebuješ spoleènost, }
{862}{}{Líbíš se mi.}
{863}{}{Hej...dávej si pozor na dímaèku. Je to fakt blb. Jednou se mi pokoušel ukousnout ucho.}
{864}{}{Jsi hroznì sexy, víš to?}

# 16. [MADE MAN]
{865}{}{}
{866}{}{Pokud budete chtít spoleènost, dejte mi vìdìt, šéfe...}
{867}{}{}
{868}{}{Zdravím vás, }
{869}{}{Pøimluvíte se za mì u vašeho šéfa?}
{870}{}{Hele, to je ten ïábel }
{871}{}{Udìlám VŠECHNO co budete chtít... staèí jen øíct.}
{872}{}{Pøimluvíte se za mì u vašeho šéfa?}
{873}{}{}
{874}{}{Pokud budete chtít spoleènost, dejte mi vìdìt, madam...}

# 17. [SLAVER]
{875}{}{Moje jméno je Povolná, otrokáøi. A tvoje?}
{876}{}{Potøebuješ nìkoho aby ti olízal tkanièku, otrokáøi?}
{877}{}{Proè si mì nevezmeš s sebou do svı klícky, otrokáøi?}
{878}{}{Nepotøebuješ vyprášit pytel, otrokáøi?}
{879}{}{Ty jsi hodnej otrokáø, e jo?}
{880}{}{Máš svùj vlastní ruèník, stopaøi?}
{881}{}{JO, jsou opravdovı a NE, nemùeš si sáhnout.}
{882}{}{Nemáš chu na rodeo, kovboji?}
{883}{}{Nechceš mì potopit svım rùovım torpédem, námoøníku?}
{884}{}{Nauèím tì pár vìcí, kterı tì mùe nauèit pouze ena.}
{885}{}{Nepotøebuješ nìkoho, kdo by ti zahøál klín, otrokáøi?}
{886}{}{Nechceš se s nìkım podìlit o svou postel, otrokáøi?}
{887}{}{Zdá se, e máš v koulích pøetlak. Neulevíme jim spolu trochu, otrokáøi.}
{888}{}{Copak to tam máš za malou neposednou kobru, otrokáøi?}
{889}{}{Hledáš povyraení??}
{890}{}{Dokud se nepomiluješ v New Reno, nevíš, co je to láska.}
{891}{}{Co si dát u mnì v lonici rande?}
{892}{}{Hele, u mnì se ádnı ochutnávky zdarma nevedou.}
{893}{}{Slyšela jsem, e prı se nìco semlelo v Obchodní ètvrti...}
{894}{}{Sháníš spoleènost?}
{895}{}{V poslední dobì je v Renu nejoblíbenìjším sportem skok pøes štìtku...}
{896}{}{Chceš si zatancovat, otrokáøi?}
{897}{}{Dokud se nepomiluješ v New Reno, nevíš, co je to láska, otrokáøi.}
{898}{}{To je neuvìøitelnı, kolik mìl Vachy na tom veèírku svobodnejch pánù striptérek.}
{899}{}{Moje práce? Dìlám z chlapcù chlapy.}
{900}{}{Dokáeš svım penisem pøibít 6-ti palcovı høebík?}
{901}{}{U jsem v tomhle mìstì pøíliš dlouho...}
{902}{}{Potøebuješ pøítele na dnešní noc, otrokáøi? Nebo jen na deset minut?}
{903}{}{Chceš si zalítat?}
{904}{}{U dlouho tu nebylo vidìt ádnı karavany z Reddingu...}
{905}{}{Hmm... chlapák..}
{906}{}{Zabloudil jsi, otrokáøi?}
{907}{}{Potøebuješ vybít zbraò, otrokáøi?}
{908}{}{Mùu ti s nìèím pomoci, cizinèe?}
{909}{}{Líbí se mi pohled na tvıho ptáka, otrokáøi. Proè ho nevyndáme z klece?}
{910}{}{To je ještìrka? To ve tvé kapse?}
{911}{}{Nepotøebuješ prùvodce mìstem, cukrouši?}
{912}{}{Nemáš oheò, otrokáøi?}
{913}{}{Pojï chlapèe, udìlám z tebe mue.}
{914}{}{Chceš si zatancovat, otrokáøi?}
{915}{}{Eh zdravíèko pane. Jdete...dolù?}
{916}{}{Jestli chceš, abych s tebou potom mluvila, tak si musíš pøiplatit.}
{917}{}{JO, jsou opravdovı a NE, nemùeš si sáhnout.}
{918}{}{Ten pošuk Mıval chtìl vìdìt, jestli jsou holky v tomhle mìstì èistotnı. Podivín.}
{919}{}{[Zpívá.] "Jsi moje kláda, moje kláda... kterou já mám nadevše ráda."}
{920}{}{Chceš si zahrát na otrokáøe a otrokyni?}
{921}{}{Jestli chceš abych pøitom zùstala vzhùru, tak za to je extra pøíplatek.}
{922}{}{Chceš se se mnou ponoøit do krajiny splnìnıch pøání?}
{923}{}{Vykašli se na toho robota. Já ti nabízím MNOHEM víc.}
{924}{}{Nejsem sice nejlevnìjší, ale zato dìlám i speciality.}
{925}{}{Ty jsi ta voda co mì drí nad vodou. Ehm, promiò brouku, kecám... na tohle mám Jet.}
{926}{}{Mnì budeš nìco vykládat bezpeènosti práce.}
{927}{}{Vida, vida. Koukejme, kdo se to dovalil do mìsta...}
{928}{}{Hledáš rajskou zahradu? Pøijï do mı lonice.}
{929}{}{Hledáš povyraení??}
{930}{}{Peníze zásadnì pøedem, drahouši. Pak by ti jich pøišlo líto ještì víc.}
{931}{}{Zkus mnì, zlato. Mám na hlavì instalovanej drák na nápoje.}
{932}{}{Chu ráje? To bude za deset babek.}
{933}{}{Myron. To je spousta vosku a ádnej knot.}
{934}{}{Myron je opravdovı trdlo... spousta kouøe bez ohnì.}
{935}{}{Myron je pes, kterej štìká, ale nikdy nekousne.}
{936}{}{Ta Bishopova holka je fakt mazlík do postele.}
{937}{}{Ta není závislá na Jetu, ale na penisech.}
{938}{}{Ve Vault City prej mají jen dva typy Obèanù. To mají z toho jejich klonování.}
{939}{}{Cítím se jako kdybych minulou noc ubìhla maratón...}
{940}{}{Hledáš lásku. brouèku?}
{941}{}{ádnı líbání. To je základní pravidlo.}
{942}{}{Ké by se Myron odstìhoval. Nìkam hodnì daleko.}
{943}{}{Udìlám ti co budeš chtít, otrokáøi... kdy na to budeš mít prachy.}
{944}{}{Já mùu tøeba hned, kotì. A co ty?}
{945}{}{Vykašli se na toho robota. Já ti nabízím MNOHEM víc.}
{946}{}{Nesnáším cucfleky.}
{947}{}{Vsaï na mnì, otrokáøi.}
{948}{}{Hledáš zábavu?}
{949}{}{Nefalšovaná New Reno láska, právì tady a právì teï.}
{950}{}{Mùeme si spolu na nìco zahrát.}
{951}{}{Já jsem Filcky Spice.}
{952}{}{Já jsem Kapavka Spice.}
{953}{}{Já jsem Šlapka Spice.}
{954}{}{Já jsem Old Spice.}
{955}{}{Já jsem Syfilis Spice.}
{956}{}{Já jsem Stará Špajz.}
{957}{}{Poslyš...jestli jsi na trojky, tak mám ochotnou pøítelkyni.}
{958}{}{Pøála bych si, aby byl Myron teplej.}
{959}{}{To by mì zajímalo proè se to jmenuje Ulice Panen...}
{960}{}{Nìkdy si pøeju, aby si dal pøes hlavu papírovı pytlík.}
{961}{}{Koupíš mi pití, otrokáøi?}
{962}{}{Provedeš osamìlou enu mìstem, otrokáøi?}
{963}{}{Uh... jasnì, e jsem ena. Staèí kdy si nebudeš všímat mıch koulí.}
{964}{}{Slyšela jsem, e nìkterı holky zabili svıho pasáka.}
{965}{}{Halóóó, cizinèe.}
{966}{}{Ten Jules a u mì radši neotravuje.}
{967}{}{Poøád ještì mám na zádech tu odøeninu od stolu...}
{968}{}{Jsem ještì utahaná z tı minulı konference otrokáøù.}
{969}{}{Ké by se tyhle sjezdy konaly v jiném mìstì.}
{970}{}{Ty bys mohl skály lámat, víš to?}
{971}{}{Myslela jsem, e se s náma pohnula Zemì, ale to bylo tìma fazolema k veèeøi.}
{972}{}{Zahøej mì, kotì.}
{973}{}{Jsem panna. Ale nejsem v tom moc dobrá.}
{974}{}{Nepotøebuješ prùvodce mìstem, otrokáøi?}
{975}{}{No tìbùh. Tak TOHLE bude jen za zvláštní pøíplatek.}
{976}{}{Jules chce poøád volòásky.}
{977}{}{Rodiny prı mají mezi sebou zase nìjakı tøenice.}
{978}{}{Byznys stagnuje. U aby dorazila další karavana.}
{979}{}{Take on se pøevlíkl za deathclawa a pak...}
{980}{}{Potøebuju pomoc dostat se z tìchhle šatù.}
{981}{}{Zapneš mì? A pak rozepneš?}
{982}{}{Promiò cos to øíkal? Mìla jsem moc práce s pozorováním tvıho zadku.}
{983}{}{Nepotøebuješ zabít èas?}
{984}{}{Hledáš zábavu?}
{985}{}{Minulej tejden jsem kopla Julese pøímo do tı jeho ozdoby.}
{986}{}{Jdeš se mrknout do centra?}
{987}{}{Neøíkají mi Šastná holka jen tak pro nic za nic.}
{988}{}{JISTÌ, Miluji kondomy s vùní brahmín. Mòam.}
{989}{}{Udìláš dámì dobøe, otrokáøi?}
{990}{}{Kdyby tak pro Myrona vynalezli nìjakı sexuální placebo.}
{991}{}{Dáme si rande, otrokáøi?}
{992}{}{Všechno co potøebuješ otrokáøi, je jedna noc se mnou.}
{993}{}{Hledáš rajskou zahradu? Pøijï do mı lonice.}
{994}{}{Ty máš prachy, otrokáøi a já mám zase èas. Tak proè to nedat dohromady?.}
{995}{}{Pomùeš mi? Hledám svou ztracenou nevinnost.}
{996}{}{Jsem ještì panna. Nedìlala bych to, nepotøebovat prachy.}
{997}{}{Buï nìnı, dneska je to poprvé.}
{998}{}{Jsem hroznì nadrená.}
{999}{}{Ty proiješ let, já budu mít fet.}
{1000}{}{Probudím v tobì duši dítìte.}
{1001}{}{Dìlám to jen, abych si vydìlala na studia.}
{1002}{}{Hele tak ještì jednou: NE já se nechci pøevlíknout za "Zakladatele."}
{1003}{}{Hledáš kde hodit kotvu?}
{1004}{}{Chceš mì slyšet sténat?}
{1005}{}{::Dìlá rukama obscénní gesta::}
{1006}{}{::Špulí ústa::}
{1007}{}{Pøestaò mì lechtat.}
{1008}{}{U dvì noci jsem nespala...}
{1009}{}{Zahrajeme si na deathclawy v dobì páøení?}
{1010}{}{Nejsem sice nejlevnìjší, ale zato dìlám i speciality.}
{1011}{}{Za svázání si musíš pøiplatit, brouku.}
{1012}{}{Kam jsem zas dala ten biè?}
{1013}{}{Vstávej semínko holala, bude z tebe fiala.}
{1014}{}{Mám se prı oblíknout jako vèera v noci DÁŠA pro Vencu.}
{1015}{}{Vèera jsem to dìlala s Myronem. Asi 5 sekund.}
{1016}{}{Nepotøebuješ nìco rozepnout?}
{1017}{}{Ké by vynalezli nìjaké parfémy vonící po Jetu...}
{1018}{}{Chceš pomoct pannì zbavit se jejího panenství?}
{1019}{}{Zadek u mi málem upadl a Myron poøád nemìl dost.}
{1020}{}{To pitomı Protialkoholickı hnutí tu zas opruzovalo...}
{1021}{}{Vdycky kdy tì vidím, zaènou mi moje biologické hodiny tikat.}
{1022}{}{::Píská na tebe::}
{1023}{}{Kousání je za extra pøíplatek.}
{1024}{}{Garantuju ti, e jsem lepší, ne ta vakuová pumpa znaèky Pip Boy, kterou pouíváš.}
{1025}{}{Chceš abych ti dotáhla závity?}
{1026}{}{Vèera jsem byla se Somnambulem. Škoda, e nemá všechno tak dlouhı jako svojí pøezdívku.}
{1027}{}{Ké by tu byl Radar. Dokáe tak krásnì vyprávìt o stahování geckonù z kùe.}
{1028}{}{S Raptorem jsme se k tomu ani nedostali. Celou noc vanil o nìjakım komprimovacím algoritmu.}
{1029}{}{Mawerick mi pøitom vyprávìl vtipy a pak po mnì chtìl slevu. Prej e za komickou vloku...}
{1030}{}{Za padesát babek tì vezmu do ráje a pak tì zas vrátím na zem.}
{1031}{}{Já se jmenuju Vlnitá. A ty, otrokáøko?}
{1032}{}{Sháníš nìkoho na olízání svı mušlièky, otrokáøko?}
{1033}{}{Proè si mì nevezmeš s sebou do svı klícky, otrokáøko?}
{1034}{}{Hej, otrokáøko. Sháníš enskou?}
{1035}{}{Chceš zkusit jakı je to mít enskou, srdíèko?}
{1036}{}{Chceš se pomazlit, otrokáøko?}
{1037}{}{Máš chu experimentovat, otrokáøko? Jen smìle do toho.}
{1038}{}{Chceš si zaøádit, otrokáøko?}
{1039}{}{Potøebuješ nìkoho, kdo ti zahøeje klín, otrokáøko?}
{1040}{}{Nechceš se s nìkım podìlit o svou postel, otrokáøko?}
{1041}{}{Máš moc hezkı køivky, otrokáøko.}
{1042}{}{Chceš si zatancovat, otrokáøko?}
{1043}{}{otrokáøko, dokud ses nepomilovala v New Reno, nevíš, co je to láska.}
{1044}{}{Moje práce? Dìlám z chlapcù chlapy. Sice nevím, co dìlám ze enskıch, ale ráda se to pokusím zjistit.}
{1045}{}{Zabloudila jsi, otrokáøko?}
{1046}{}{Hledáš zábavu, otrokáøko?}
{1047}{}{Dáme si rande, otrokáøko?}
{1048}{}{Nemáš oheò, otrokáøko?}
{1049}{}{Vdycky kdy tì vidím, otrokáøko zaènou mi moje biologické hodiny tikat.}

# 18. [BONENOSE]
{1050}{}{Jmenuju se Vlhká. A ty?}
{1051}{}{Trochu zvláštní chování, eh?}
{1052}{}{Máš svùj vlastní ruèník, stopaøi?}
{1053}{}{JO, opravdu jsou pravı.}
{1054}{}{JO, jsou opravdovı a NE, nemùeš si sáhnout.}
{1055}{}{Nech toho, ty magore.}
{1056}{}{Nemáš chu na rodeo, kovboji?}
{1057}{}{Nechceš mì potopit svım rùovım torpédem, námoøníku?}
{1058}{}{Nepotøebuješ nìkoho, kdo by ti zahøál klín?}
{1059}{}{Nechceš se s nìkım podìlit o svou postel?}
{1060}{}{Zdá se, e máš v koulích pøetlak. Neulevíme jim spolu trochu, kámo.}
{1061}{}{Máš tam malou neposednou kobru, co?}
{1062}{}{Hledáš povyraení?}
{1063}{}{Dokud se nepomiluješ v New Reno, nevíš, co je to láska.}
{1064}{}{Co si dát u mnì v lonici rande?}
{1065}{}{Hele, u mnì se ádnı ochutnávky zdarma nevedou.}
{1066}{}{Slyšela jsem, e prı se nìco semlelo v Obchodní ètvrti...}
{1067}{}{Sháníš spoleènost?}
{1068}{}{V poslední dobì je v Renu nejoblíbenìjším sportem skok pøes štìtku...}
{1069}{}{Chceš si zatancovat?}
{1070}{}{Dokud se nepomiluješ v New Reno, nevíš, co je to láska.}
{1071}{}{Moje práce? Dìlám z chlapcù chlapy.}
{1072}{}{Dokáeš svım penisem pøibít 6-ti palcovı høebík?}
{1073}{}{Šlapu teprve od vèerejška...}
{1074}{}{Hledáš pøítelkyni na noc? Nebo jen na deset minut?}
{1075}{}{Chceš si zalítat?}
{1076}{}{U dlouho tu nebylo vidìt ádnı karavany z Reddingu...}
{1077}{}{Hmm... chlapák..}
{1078}{}{Ztratil jsi cestu, kovboji?}
{1079}{}{Potøebuješ si vybít zbraò, vojáèku?}
{1080}{}{Mùu ti s nìèím pomoci, cizinèe?}
{1081}{}{Hledáš zábavu?}
{1082}{}{Jdeš se mrknout do centra?}
{1083}{}{Líbí se mi pohled na tvıho ptáèka. Proè ho nevyndáme z klece?}
{1084}{}{To je ještìrka? To ve tvé kapse?}
{1085}{}{Nepotøebuješ prùvodce mìstem, lásko?}
{1086}{}{Nemáš oheò, brouku?}
{1087}{}{Ty máš prachy, já mám èas.}
{1088}{}{Pojï chlapèe, udìlám z tebe mue.}
{1089}{}{Zdravíèko. Na procházce?}
{1090}{}{Jestli chceš, abych s tebou potom mluvila, tak si musíš pøiplatit.}
{1091}{}{Ten pošuk Mıval chtìl vìdìt, jestli jsou holky v tomhle mìstì èistotnı. Podivín.}
{1092}{}{Ten tvùj pøítel s tou velkou kostí v nose...to je skvìlej nápad.}
{1093}{}{Umí ten tvùj pøítel s tou kostí nìjakı kousky?}
{1094}{}{Moná bych si taky mìla do nosu strèit kost. Mohlo by to pøilákat zákaznice.}
{1095}{}{Jeišikriste, ta kost co má ten chlap v nose je velká jako moje ruka.}
{1096}{}{Radši ani nechci vìdìt jak si tam ten chlap tu kost nacpal.}
{1097}{}{Pro koho tvùj pøítel s tou kostí v nosu šlape?}
{1098}{}{Jakej pøíplatek si poèítá ten tvùj kámoš za tu kost v nose?}
{1099}{}{Za tøicet doláèù tvımu kámošovi tu kost v nose vykouøím....}
{1100}{}{Ten tvùj pøítel si tou kostí v nose kompenzuje nìjakej komplex?}
{1101}{}{Hledáš rajskou zahradu? Pøijï do mı lonice.}
{1102}{}{Hledáš povyraení??}
{1103}{}{Peníze zásadnì pøedem, drahouši. Pak by ti jich pøišlo líto ještì víc.}
{1104}{}{Nauèím tì pár vìcí, kterı tì mùe nauèit pouze ena.}
{1105}{}{Zkus mnì, zlato. Mám na hlavì instalovanej drák na nápoje.}
{1106}{}{Chu ráje? To bude za deset babek.}
{1107}{}{Myron. To je spousta vosku a ádnej knot.}
{1108}{}{Myron je opravdovı trdlo... spousta kouøe bez ohnì.}
{1109}{}{Myron je pes, kterej štìká, ale nikdy nekousne.}
{1110}{}{Ta Bishopova holka je fakt mazlík do postele.}
{1111}{}{Ta není závislá na Jetu, ale na penisech.}
{1112}{}{Ve Vault City prej mají jen dva typy Obèanù. To mají z toho jejich klonování.}
{1113}{}{Cítím se jako kdybych minulou noc ubìhla maratón...}
{1114}{}{Hledáš lásku. brouèku?}
{1115}{}{ádnı líbání. To je základní pravidlo.}
{1116}{}{Ké by se Myron odstìhoval. Nìkam hodnì daleko.}
{1117}{}{Udìlám ti co budeš chtít... kdy na to budeš mít prachy.}
{1118}{}{Já mùu tøeba hned, kotì. A co ty?}
{1119}{}{Vykašli se na toho robota. Já ti nabízím MNOHEM víc.}
{1120}{}{Nesnáším cucfleky.}
{1121}{}{Sice jsem to zrovna dostala, ale jak tak na tebe koukám, tobì trocha krve nevadí, e ne?}
{1122}{}{Hledáš zábavu?}
{1123}{}{To je neuvìøitelnı, kolik mìl Vachy na tom veèírku svobodnejch pánù striptérek.}
{1124}{}{Nefalšovaná New Reno láska, právì tady a právì teï.}
{1125}{}{Mùeme si spolu na nìco zahrát.}
{1126}{}{Já jsem Filcky Spice.}
{1127}{}{Já jsem Kapavka Spice.}
{1128}{}{Já jsem Old Spice.}
{1129}{}{Já jsem Šlapka Spice.}
{1130}{}{Já jsem Syfilis Spice.}
{1131}{}{Já jsem Stará Špajz.}
{1132}{}{Jestli jsi na trojky, tak mám ochotnou pøítelkyni.}
{1133}{}{Pøála bych si, aby byl Myron teplej.}
{1134}{}{To by mì zajímalo proè se to jmenuje Ulice Panen...}
{1135}{}{Nìkdy si pøeju, aby si dal pøes hlavu papírovı pytlík.}
{1136}{}{Koupíš mi pití?}
{1137}{}{Provedeš osamìlou enu mìstem?}
{1138}{}{Uh... jasnì, e jsem ena. Staèí kdy si nebudeš všímat mıch koulí.}
{1139}{}{Slyšela jsem, e nìkterı holky zabili svıho pasáka.}
{1140}{}{Halóóó, cizinèe.}
{1141}{}{Ten Jules a u mì radši neotravuje.}
{1142}{}{Poøád ještì mám na zádech tu odøeninu od stolu...}
{1143}{}{Jsem ještì utahaná z toho minulıho sjezdu...}
{1144}{}{Ké by se tyhle sjezdy konaly v jiném mìstì.}
{1145}{}{Ty bys mohl skály lámat, víš to?}
{1146}{}{Myslela jsem, e se s náma pohnula Zemì, ale to bylo tìma fazolema k veèeøi.}
{1147}{}{Zahøej mì, kotì.}
{1148}{}{Jsem panna. Ale nejsem v tom moc dobrá.}
{1149}{}{Nepotøebuješ prùvodce mìstem?}
{1150}{}{Tìbùh. Tak TOHLE jedinì za zvláštní pøíplatek.}
{1151}{}{Jules chce poøád volòásky.}
{1152}{}{Rodiny prı mají mezi sebou zase nìjakı tøenice.}
{1153}{}{Byznys stagnuje. U aby dorazila další karavana.}
{1154}{}{Take on se pøevlíkl za deathclawa a pak...}
{1155}{}{Potøebuju pomoc dostat se z tìchhle šatù.}
{1156}{}{Zapneš mì? A pak rozepneš?}
{1157}{}{Promiò cos to øíkal? Mìla jsem moc práce s pozorováním tvıho zadku.}
{1158}{}{Nepotøebuješ zabít èas?}
{1159}{}{Minulej tejden jsem kopla Julese pøímo do tı jeho ozdoby.}
{1160}{}{Neøíkají mi Šastná holka jen tak pro nic za nic.}
{1161}{}{Samozøejmì, e miluju kondomy s vùní brahmín. Òam.}
{1162}{}{Udìláš dámì dobøe?}
{1163}{}{Kdyby tak pro Myrona vynalezli nìjakı sexuální placebo.}
{1164}{}{Nechceš si domluvit rande, divochu?}
{1165}{}{Chceš si zaskákat, divochu?}
{1166}{}{Co takhle zatancovat si váleènı tanec v mı lonici, divochu?}
{1167}{}{Všechno co potøebuješ, je jedna noc se mnou.}
{1168}{}{Hledáš rajskou zahradu? Pøijï do mı lonice.}
{1169}{}{Pomùeš mi? Hledám svou ztracenou nevinnost.}
{1170}{}{Jsem ještì panna. Nedìlala bych to, nepotøebovat prachy.}
{1171}{}{Buï nìnı, dneska je to poprvé.}
{1172}{}{Jsem hroznì nadrená.}
{1173}{}{Ty proiješ let, já budu mít fet.}
{1174}{}{Probudím v tobì duši dítìte.}
{1175}{}{Dìlám to jen, abych si vydìlala na studia.}
{1176}{}{Chceš si zatrsat, zlato?}
{1177}{}{Hele tak ještì jednou: NE já se nechci pøevlíknout za "Zakladatele."}
{1178}{}{Hledáš kde hodit kotvu?}
{1179}{}{Chceš mì slyšet sténat?}
{1180}{}{::Dìlá rukama obscénní gesta::}
{1181}{}{::Špulí ústa::}
{1182}{}{Pøestaò mì lechtat.}
{1183}{}{U dvì noci jsem nespala...}
{1184}{}{Zahrajeme si na deathclawy v dobì páøení?}
{1185}{}{Nejsem sice nejlevnìjší, ale zato dìlám i speciality.}
{1186}{}{Za svázání si musíš pøiplatit, brouku.}
{1187}{}{Kam jsem zas dala ten biè?}
{1188}{}{Vstávej semínko holala, bude z tebe fiala.}
{1189}{}{Mám se prı oblíknout jako vèera v noci DÁŠA pro Vencu.}
{1190}{}{Vèera jsem to dìlala s Myronem. Asi 5 sekund.}
{1191}{}{Nepotøebuješ nìco rozepnout?}
{1192}{}{Ké by vynalezli nìjaké parfémy vonící po Jetu...}
{1193}{}{Chceš pomoct pannì zbavit se jejího panenství?}
{1194}{}{Zadek u mi málem upadl a Myron poøád nemìl dost.}
{1195}{}{To pitomı Protialkoholickı hnutí tu zas opruzovalo...}
{1196}{}{Vdycky kdy tì vidím, zaènou mi moje biologické hodiny tikat.}
{1197}{}{::Píská na tebe::}
{1198}{}{Kousání je za extra pøíplatek.}
{1199}{}{Garantuju ti, e jsem lepší, ne ta vakuová pumpa znaèky Pip Boy, kterou pouíváš.}
{1200}{}{Chceš abych ti dotáhla závity?}
{1201}{}{Vèera jsem byla se Somnambulem. Škoda, e nemá všechno tak dlouhı jako svojí pøezdívku.}
{1202}{}{Ké by tu byl Radar. Dokáe tak krásnì vyprávìt o stahování geckonù z kùe.}
{1203}{}{S Raptorem jsme se k tomu ani nedostali. Celou noc vanil o nìjakım komprimovacím algoritmu.}
{1204}{}{Mawerick mi pøitom vyprávìl vtipy a pak po mnì chtìl slevu. Prej e za komickou vloku...}
{1205}{}{Za padesát babek tì vezmu do ráje a pak tì zas vrátím na zem.}
{1206}{}{Jmenuju se Povolná, sleèno. A vy?}
{1207}{}{Ahoj drahoušku. Sháníš holku?}
{1208}{}{Chceš zkusit jakı je to mít enskou, srdíèko?}
{1209}{}{Hledáš spoleènost?}
{1210}{}{Holka, nech mì, a tì nauèím to, co tì mùe nauèit jen ENA.}
{1211}{}{Nepotøebuješ nìkoho, kdo by ti zahøál klín, zlato?}
{1212}{}{Nechceš se s nìkım podìlit o svou postel, cukroušku?}
{1213}{}{Chceš si zatanèit, drahoušku?}
{1214}{}{Holka, dokud ses nepomilovala v New Reno, nevíš, co je to láska.}
{1215}{}{Chceš si zalítat, pusinko?}
{1216}{}{Ztratila ses, kotì?}
{1217}{}{Hej ty tam, G.I. Jane.}
{1218}{}{Hledáš zábavu, dìvèe?}
{1219}{}{Jdeš se mrknout do centra, dìvèico?}
{1220}{}{Nepotøebuješ prùvodce mìstem, lásko?}
{1221}{}{Nemáš oheò, dìvèe?}
{1222}{}{Ty máš prachy, má milá a já zas èas.}

# 19. [NO REP]
{1223}{}{Jmenuju se Vlhká. A ty?}
{1224}{}{Trochu zvláštní chování, eh?}
{1225}{}{Máš svùj vlastní ruèník, stopaøi?}
{1226}{}{JO, opravdu jsou pravı.}
{1227}{}{JO, jsou opravdovı a NE, nemùeš si sáhnout.}
{1228}{}{Nech toho, ty magore.}
{1229}{}{Nemáš chu na rodeo, kovboji?}
{1230}{}{Nechceš mì potopit svım rùovım torpédem, námoøníku?}
{1231}{}{Nepotøebuješ nìkoho, kdo by ti zahøál klín?}
{1232}{}{Nechceš se s nìkım podìlit o svou postel?}
{1233}{}{Zdá se, e máš v koulích pøetlak. Neulevíme jim spolu trochu, kámo?}
{1234}{}{Máš tam malou neposednou kobru, co?}
{1235}{}{Hledáš povyraení??}
{1236}{}{Dokud se nepomiluješ v New Reno, nevíš, co je to láska.}
{1237}{}{Co si dát u mnì v lonici rande?}
{1238}{}{Hele, u mnì se ochutnávky zdarma nevedou.}
{1239}{}{Prı se nìco semlelo v Obchodní ètvrti...}
{1240}{}{Sháníš spoleènost?}
{1241}{}{V poslední dobì je v Renu nejoblíbenìjším sportem skok pøes štìtku...}
{1242}{}{Chceš si zatancovat?}
{1243}{}{Dokud se nepomiluješ v New Reno, nevíš, co je to láska.}
{1244}{}{Moje práce? Dìlám z chlapcù chlapy.}
{1245}{}{Dokáeš svım penisem pøibít 6-ti palcovı høebík?}
{1246}{}{Šlapu teprve od vèerejška...}
{1247}{}{Hledáš pøítelkyni na noc? Nebo jen na deset minut?}
{1248}{}{Chceš si zalítat?}
{1249}{}{U dlouho tu nebylo vidìt ádnı karavany z Reddingu...}
{1250}{}{Hmm... chlapák..}
{1251}{}{Ztratil jsi cestu, kovboji?}
{1252}{}{Potøebuješ si vybít zbraò, vojáèku?}
{1253}{}{Mùu ti s nìèím pomoci, cizinèe?}
{1254}{}{Hledáš zábavu?}
{1255}{}{Jdeš se mrknout do centra?}
{1256}{}{Líbí se mi pohled na tvıho ptáèka. Proè ho nevyndáme z klece?}
{1257}{}{To je ještìrka? To ve tvé kapse?}
{1258}{}{Nepotøebuješ prùvodce mìstem, lásko?}
{1259}{}{Nemáš oheò, brouku?}
{1260}{}{Ty máš prachy, já zas èas.}
{1261}{}{Pojï chlapèe, udìlám z tebe mue.}
{1262}{}{Zdravíèko. Na procházce?}
{1263}{}{Jestli chceš, abych s tebou potom mluvila, tak si musíš pøiplatit.}
{1264}{}{Ten pošuk Mıval chtìl vìdìt, jestli jsou holky v tomhle mìstì èistotnı. Podivín.}
{1265}{}{Jestli chceš abych pøitom neusnula, tak za to je extra pøíplatek.}
{1266}{}{Chceš se se mnou ponoøit do krajiny splnìnıch pøání?}
{1267}{}{Vykašli se na toho robota. Já ti nabízím MNOHEM víc.}
{1268}{}{Nejsem sice nejlevnìjší, ale zato dìlám i speciality.}
{1269}{}{Hej ty tam, zlatíèko.}
{1270}{}{Chceš mì obtáhnout?}
{1271}{}{Ty jsi ta voda co mì drí nad vodou. Ehm, promiò brouku, kecám... na tohle mám Jet.}
{1272}{}{Mnì budeš nìco vykládat bezpeènosti práce.}
{1273}{}{Vida, vida. Koukejme, kdo se to dovalil do mìsta...}
{1274}{}{Hledáš rajskou zahradu? Pøijï do mı lonice.}
{1275}{}{Hledáš povyraení??}
{1276}{}{Peníze zásadnì pøedem, drahouši. Pak by ti jich pøišlo líto ještì víc.}
{1277}{}{Nauèím tì pár vìcí, kterı tì mùe nauèit pouze ena.}
{1278}{}{Zkus mnì, zlato. Mám na hlavì instalovanej drák na nápoje.}
{1279}{}{Chu ráje? To bude za deset babek.}
{1280}{}{Myron. To je spousta vosku a ádnej knot.}
{1281}{}{Myron je opravdovı trdlo... spousta kouøe bez ohnì.}
{1282}{}{Myron je pes, kterej štìká, ale nikdy nekousne.}
{1283}{}{Ta Bishopova holka je fakt mazlík do postele.}
{1284}{}{Ta není závislá na Jetu, ale na penisech.}
{1285}{}{Ve Vault City prej mají jen dva typy Obèanù. To mají z toho jejich klonování.}
{1286}{}{Cítím se jako kdybych minulou noc ubìhla maratón...}
{1287}{}{Hledáš lásku. brouèku?}
{1288}{}{ádnı líbání. To je základní pravidlo.}
{1289}{}{Ké by se Myron odstìhoval. Nìkam hodnì daleko.}
{1290}{}{Udìlám ti co budeš chtít... kdy na to budeš mít prachy.}
{1291}{}{Já mùu tøeba hned, kotì. A co ty?}
{1292}{}{Vykašli se na toho robota. Já ti nabízím MNOHEM víc.}
{1293}{}{Nesnáším cucfleky.}
{1294}{}{Sice jsem to zrovna dostala, ale jak tak na tebe koukám, tobì trocha krve nevadí, e ne?}
{1295}{}{Hledáš zábavu, bejby?}
{1296}{}{To je neuvìøitelnı, kolik mìl Vachy na tom veèírku svobodnejch pánù striptérek.}
{1297}{}{Milování jako z románu najdeš u mnì. Tisíce dìkovnıch dopisù...}
{1298}{}{Mùeme si spolu na nìco zahrát.}
{1299}{}{Já jsem Filcky Spice.}
{1300}{}{Já jsem Kapavka Spice.}
{1301}{}{Já jsem Šlapka Spice.}
{1302}{}{Já jsem Old Spice.}
{1303}{}{Já jsem Syfilis Spice.}
{1304}{}{Já jsem Stará Špajz.}
{1305}{}{Jestli jsi na trojky, tak mám ochotnou pøítelkyni.}
{1306}{}{Pøála bych si, aby byl Myron teplej.}
{1307}{}{To by mì zajímalo proè se to jmenuje Ulice Panen...}
{1308}{}{Nìkdy si pøeju, aby si dal pøes hlavu papírovı pytlík.}
{1309}{}{Koupíš mi pití?}
{1310}{}{Provedeš osamìlou enu mìstem?}
{1311}{}{Uh... jasnì, e jsem ena. Staèí kdy si nebudeš všímat mıch koulí.}
{1312}{}{Slyšela jsem, e nìkterı holky zabili svıho pasáka.}
{1313}{}{Nejlepší soulo v celém mìstì. Èasovì omezená nabídka. Pouze do vyprodání zásob.}
{1314}{}{Ten Jules a u mì radši neotravuje.}
{1315}{}{Poøád ještì mám na zádech tu odøeninu od stolu...}
{1316}{}{Jsem ještì utahaná z toho minulıho sjezdu...}
{1317}{}{Ké by se tyhle sjezdy konaly v jiném mìstì.}
{1318}{}{Ty bys mohl skály lámat, víš to?}
{1319}{}{Myslela jsem, e se s náma pohnula Zemì, ale to bylo tìma fazolema k veèeøi.}
{1320}{}{Zahøej mì, kotì.}
{1321}{}{Jsem panna. Ale nejsem v tom moc dobrá.}
{1322}{}{Nepotøebuješ prùvodce mìstem?}
{1323}{}{No tìbùh. Tak TOHLE bude jen za zvláštní pøíplatek.}
{1324}{}{Jules chce poøád volòásky.}
{1325}{}{Rodiny prı mají mezi sebou zase nìjakı tøenice.}
{1326}{}{Byznys stagnuje. U aby dorazila další karavana.}
{1327}{}{Take on se pøevlíkl za deathclawa a pak...}
{1328}{}{Potøebuju pomoc dostat se z tìchhle šatù.}
{1329}{}{Zapneš mì? A pak rozepneš?}
{1330}{}{Promiò, øíkáš nìco? Mìla jsem moc práce s pozorováním tvıho fantastickıho tìla.}
{1331}{}{Nepotøebuješ zabít èas?}
{1332}{}{Minulej tejden jsem kopla Julese pøímo do tı jeho ozdoby.}
{1333}{}{Neøíkají mi Šastná holka jen tak pro nic za nic.}
{1334}{}{Jasnì! Já miluju kondomy s vùní brahmín. Òam.}
{1335}{}{Udìláš dámì dobøe?}
{1336}{}{Myslím, e tu kulku v hlavì nerozchodí.}
{1337}{}{Nechceš si domluvit rande, divochu?}
{1338}{}{Chceš si zaskákat, divochu?}
{1339}{}{Co takhle zatancovat si váleènı tanec v mı lonici, divochu?}
{1340}{}{Všechno co potøebuješ, je jedna noc se mnou.}
{1341}{}{Hledáš ráj? Je právì tady, mezi mımi stehny.}
{1342}{}{Pomùeš mi? Hledám svou ztracenou nevinnost.}
{1343}{}{Jsem ještì panna. Nedìlala bych to, nepotøebovat prachy.}
{1344}{}{Buï nìnı, dneska je to poprvé.}
{1345}{}{Jsem hroznì nadrená.}
{1346}{}{Ty proiješ let, já budu mít fet.}
{1347}{}{Probudím v tobì duši dítìte.}
{1348}{}{Dìlám to jen, abych si vydìlala na studia.}
{1349}{}{Chceš si zatrsat, zlato?}
{1350}{}{Hele tak ještì jednou: NE já se nechci pøevlíknout za "Zakladatele."}
{1351}{}{Hledáš kde hodit kotvu?}
{1352}{}{Chceš mì slyšet sténat?}
{1353}{}{::Dìlá rukama obscénní gesta::}
{1354}{}{::Špulí ústa::}
{1355}{}{Pøestaò mì lechtat.}
{1356}{}{U mì to New Reno unavuje...}
{1357}{}{Zahrajeme si na deathclawy v dobì páøení?}
{1358}{}{Nejsem sice nejlevnìjší, ale zato dìlám i speciality.}
{1359}{}{Za svázání si musíš pøiplatit, brouku.}
{1360}{}{Kam jsem zas dala ten biè?}
{1361}{}{Vstávej semínko holala, bude z tebe fiala.}
{1362}{}{Mám se prı oblíknout jako vèera v noci DÁŠA pro Vencu.}
{1363}{}{Vèera jsem to dìlala s Myronem. Asi 5 sekund.}
{1364}{}{Nepotøebuješ nìco rozepnout?}
{1365}{}{Nemáš oheò, brouku?}
{1366}{}{Pomùeš mi zbavit se mıho panenství?}
{1367}{}{Zadek u mi málem upadl a Myron poøád nemìl dost.}
{1368}{}{To pitomı Protialkoholickı hnutí tu zas opruzovalo...}
{1369}{}{Vdycky kdy tì vidím, zaènou mi moje biologické hodiny tikat.}
{1370}{}{::Píská na tebe::}
{1371}{}{Kousání je za extra pøíplatek.}
{1372}{}{Garantuju ti, e jsem lepší, ne ta vakuová pumpa znaèky Pip Boy, kterou pouíváš.}
{1373}{}{Chceš abych ti dotáhla závity?}
{1374}{}{Vèera jsem byla se Somnambulem. Škoda, e nemá všechno tak dlouhı jako svojí pøezdívku.}
{1375}{}{Ké by tu byl Radar. Dokáe tak krásnì vyprávìt o stahování geckonù z kùe.}
{1376}{}{S Raptorem jsme se k tomu ani nedostali. Celou noc vanil o nìjakım komprimovacím algoritmu.}
{1377}{}{Mawerick mi pøitom vyprávìl vtipy a pak po mnì chtìl slevu. Prej e za komickou vloku...}
{1378}{}{Za padesát babek tì vezmu do ráje a pak tì zas vrátím na zem.}
{1379}{}{Jmenuju se Povolná, sleèno. A vy?}
{1380}{}{Ahoj drahoušku. Sháníš holku?}
{1381}{}{Chceš zkusit jakı je to mít enskou, srdíèko?}
{1382}{}{Hledáš spoleènost?}
{1383}{}{Holka, nech mì, a tì nauèím to, co tì mùe nauèit jen ENA.}
{1384}{}{Nepotøebuješ nìkoho, kdo by ti zahøál klín, kotì?}
{1385}{}{Nechceš se s nìkım podìlit o svou postel, zlato?}
{1386}{}{Chceš si zatanèit, drahoušku?}
{1387}{}{Holka, dokud ses nepomilovala v New Reno, nevíš, co je to láska.}
{1388}{}{Chceš si zalítat, pusinko?}
{1389}{}{Ztratila ses, kotì?}
{1390}{}{Hej ty tam, G.I. Jane?}
{1391}{}{Hledáš zábavu, drahoušku?}
{1392}{}{Jdeš se mrknout do centra, miláèku?}
{1393}{}{Láska? Ta je pøece v šupinách ptákù, ve vìtvích mákù a na køídlech psù.}
{1394}{}{Nemáš oheò, brouku?}
{1395}{}{Ty máš prachy, lásko a já mám zas èas. Tak co to dát dohromady?}

# SPECIAL CAT'S PAW WHORE DIALOGS START
# 0. QUICK LOOK
{3100}{}{Vidíš jednu z dívek od Koèièí packy.}

# EXAMINES
{3150}{}{Vidíš...ehm, dámu veèera. Její rozedrané šaty stìí zakrıvají její tìlo.}
{3151}{}{Vidíš jednu z dívek od Koèièí packy. Mrká na tebe.}
{3151}{}{Vidíš jednu z dívek od Koèièí packy. Její oèi jsou jak roznìtky.}
{3152}{}{Vidíš jednu z dívek od Koèièí packy. Voní jako kvìtiny.}
{3153}{}{Vidíš jednu z dívek od Koèièí packy. Voní jako mámin polštáø.}
{3154}{}{Vidíš jednu z dívek od Koèièí packy. Je ti záhadou, jak ty sporé hadøíky zvládnou udret její prsa ve vıstøihu.}
{3155}{}{Vidíš jednu z dívek od Koèièí packy. Tváøí se, jako by chtìla zabít a sníst své kolegynì.}
{3156}{}{Vidíš jednu z dívek od Koèièí packy. Ohodnotila tì letmım pohledem klenotníka.}
{3157}{}{Vidíš jednu z dívek od Koèièí packy. Její sporé šaty obepínají svádivì její tìlo.}

#1. SOME OTHER RANDOM FLOAT TEXT [ANY DISTANCE] (WTG)
{3200}{}{Oh, Boe! Ach mùj Boe! OhBoeohBoeohBoe...ooooooh Bóóóínku.}
{3201}{}{Ano! Ano! Anoooooooooo AnoAnoAnoAno ANO ANO ANOOOOO! Díky. Raète si zaplatit u pokladny.}
{3202}{}{Dìlej. Bìí ti èas.}
{3203}{}{Nepotøebuješ mokrej ruèník?}
{3204}{}{Udìlej mi to, Kar...Rad...Rich...uh, promiò, jak jsi to øíkal, e se jmenuješ?}
{3205}{}{Oh mùj boe, oh boe, oh mùj boe! U jsi skonèil?}
{3206}{}{No tìpic. Tak TOHLE jen za extra pøíplatek.}
{3207}{}{Ano! Ty jsi mùj Kolumbus a já tvoje Amerika!}
{3208}{}{Ach mùj boe, to byl ten nejúasnìjší záitek, co jsem kdy mìla. A teï 
ze mì laskavì slez a zapla si u pokladny.}
{3209}{}{U je uvnitø? Boe ten je ale velkı.}
{3210}{}{Jo, to víš, e JSI Zakladatel. Jo, jasnì, to TY jsi našel vodní èip a porazil
 Vùdce. Jo to víš, e ti vìøím, e jsi hrdina.}
{3211}{}{Ty jsi drsnej jak tvrzená Energo zbroj.}
{3212}{}{*Uhhh*}
{3213}{}{*Ááách*}
{3214}{}{Ne, masku Myšáka Mickeyho si na sebe nevezmu.}
{3215}{}{Ano, ano, to víš, e máš "ohromnı koule."}

# END LINES
{2175}{}{. To je ten co zlikvidoval Enklávu.}
{2178}{}{! Cestu pro pøemoitele Enklávy!}
{2181}{}{. Ten, kterı smetl Enklávu z povrchu zemì.}
{2195}{}{!}
{2197}{}{! Mùu pracovat u tebe ve studiu?}
{2210}{}{.}
{2263}{}{! Vedeš si skvìle, hrdino!}
{2264}{}{ nakopal v tıhle høe tolik zadkù, e snad musel bıt v minulım ivotì botou.}
{2268}{}{?}
{2272}{}{?}
{2278}{}{! Boduješ, holka!}
{2279}{}{?}
{2280}{}{ nakopala v tıhle høe tolik zadkù, e snad musela bıt v minulım ivotì botou.}
{2285}{}{.}
{2292}{}{...}
{2293}{}{?}
{2294}{}{... tadyy, zlatíèko...}
{2295}{}{.}
{2855}{}{?}
{2858}{}{?}
{2861}{}{?}
{2865}{}{, ty mùj chlapáku...co dìláš dneska veèer?}
{2867}{}{! Jak se máš?}
{2868}{}{. Mùu ti pomoct s...*nìèím?*}
{2870}{}{.}
{2873}{}{, ty moje malá svùdkynì...co dìláš dneska veèer?}
