#tento soubor pøeloil Cedic.......???
# 0. QUICK LOOK
{100}{}{Vidíš Rakeáka Renesca.}

# 0. LOOK (GLASSES = DISCOUNT, FREEBIE, DONE)
{150}{}{Vidíš starého mue s obrovskımi záøivımi brılemi. Podrádìnì sleduje, jak si ho prohlííš.}

# 0. LOOK (GLASSES = NOTHING)
{200}{}{Vidíš Rakeáka Renesca. Sleduješ, jak sundává své brıle a èistí si to sklo, co není rozbité.}
{201}{}{Vidíš Rakeáka Renesca. Sleduješ, jak sundává své brıle a èistí si to sklo, co není rozbité.}

# 1. FLOAT DIALOGUES (WTG)
{210}{}{Ještì jedno sklo do brılí, to je všechno, co chci.}
{211}{}{Zkurvené brıle!}
{212}{}{Zatracené oèi!}
{213}{}{Chceš nìco koupit?}
{214}{}{Tady není jídelna. Chceš nìco koupit?}
{215}{}{Zaèínám slepnout a chci stále pracovat.}
{216}{}{Potøebuji trochu víc zásady chemtex devìt.}
{217}{}{Poadavek se pøijímá.}

# 2. FLOAT DIALOGUES (WTG)
{225}{}{Jdi do hajzlu.}	
{226}{}{Vypadni odtud pryè, nebo tì zastøelím.}
{227}{}{Vypadni!}
{228}{}{Bì! Bì! Bì! Bì! Bì!}

# 3. INTRO SPIEL (WTG)
{235}{}{(Staøec se snaí nasadit si rozbité brıle na nos a vypadá popuzenì.) ANO? Co chceš? }
{236}{}{Dìlej, chlape, ven s tím!}
{237}{}{No tak, enská, ven s tím!}
{238}{}{Dobrá. Øeknu to... radìji odstup (Mlè.)}
{239}{}{Dobrá. Potøebuji nejdøíve rozepnout podprsenku. Vydr. (Mlè.)}
{240}{}{Co mi chceš? Co máš?}
{241}{}{Znovu na nìj civí, aby se ujistil, e je skuteènı a pak se potácí pryè.}
{242}{}{Kdo jsi?}
{243}{}{Hej, mám brıle, jestli je chceš.}
{244}{}{Co chceš za ty brıle?}
{245}{}{Jsou tu známé znaèky, které chutnají tak dobøe jako skuteèné vìci.}
{246}{}{Jsme na špatném místì, chlape. Nashle.}

# 4.  RETARD (3, 5)
{255}{}{(Šokovanì zírá.)}
{256}{}{... další zkurvená troska ve znièeném svìtì plnım idiotskıch parchantù. (svírá pìsti) Vypadni z mého krámu! Okamitì zmiz! U se nevracej, slyšíš?!}
{257}{}{Mrzí mì to }
{258}{}{Nevím, jak se nasazuje podprsenka}
{259}{}{Nejásej }
{260}{}{, nenávidím tì! }
{261}{}{Jdu, hned jdu.}

# 5.  WHO ARE YOU? (3)
{270}{}{Já? Jsem veselı Santa Nick, ty hòupe jeden.}
{271}{}{Já? Jsem veselı Santa Nick. A ty musíš bıt ten idiotskı nájemnı vrah, kterı se potuloval kolem mìsta jako hladovı prašivı pes laènící po svıch vlastních vıkalech.}
{272}{}{Já? Jsem veselı Santa Nick. A ty musíš bıt ten stupidní kus ocasu šmejda z bordelu, kterımu pták visí dolù jako shnilá švestka.}
{273}{}{Já? Jsem veselı Santa Nick. A ty musíš bıt ta debilní štìtka, pro kterou si úchyláci honí péro v køoví.}
{274}{}{Vıbornì... dobøe e se nemusím pøedstavovat. Co tu dìláš "Nicku?"}
{275}{}{Santa Nick? Co je to za ïábla?}
{276}{}{Podívej dìdku, ještì jednu takovou poznámku a dám si tvé zuby okolo krku jako náhrdelník.}
{277}{}{Podívej, tu tvoji poznámku pøeslechnu... pro tentokrát. A teï: Kdo jsi?}
{278}{}{Úchvatnı slovník... "Nicku." Jsi odtud?}
{279}{}{Zapomeò na to. Jdu pryè.}

# 6. WHO ARE YOU? (3, 5)
{290}{}{(Pronikavì se na tebe dívá a funí.) Jmenuji se Renesco. Jen mi øekni co chceš, ty... eh, a jsi kdokoliv. (Úkosem se na tebe zadíval.) Vypadáš jako jeden z tìch barbarù zboòujících slunce.}
{291}{}{Pocházím z vesnice na severozápadì. Arroyo.}
{292}{}{Co zde prodáváš?}
{293}{}{Co chci? Já skuteènì nevím. Vìtšinou ignoruji svého hosta a jdu do domovù jinıch, pøes regály... oooh, jako tamhleto!}
{294}{}{Máš zajímavı slovník... Renesco. Jsi odtud?}
{295}{}{Nejsem.}

# 7. WHAT DO YOU SELL? (6, 36, 42)
{305}{}{Vìtšinou prodávám osvìující drogy. Proto mi dali tu idiotskou pøezdívku 'Rakeák' Hmmm. Také prodávám zásoby do vozù. POTØEBUJEŠ nìco, nebo se mùu vrátit k nìèemu dùleitìjšímu?}
{306}{}{Rakeák, páni. Znáš øadu písnièek od Eltona Johna, "Rakeák, spálenı tam doma?' Co tím asi chtìl øíct?}
{307}{}{Mohu vidìt, co máš ve skladu?}
{308}{}{V krámu prodáváš drogy?}
{309}{}{Neprodal jsi drogy synovi pana Wrighta?}
{310}{}{Vrame se radìji kadı ke svému.}

# 8. ROCKETMAN/IGNORE QUEST (6, 7, 32, 36)
{320}{}{(Renesco na tebe civí. Vypadá to, jako by v duchu svlékal, a pak tì kousek po kousku trhal.)}
{321}{}{No nic. Mám nìjaké další otázky.}
{322}{}{No nic.}

# 9. YOU SELL DRUGS IN THE STORE? (7)
{330}{}{(Renesco se na tebe dívá s odporem.) Ano. V obchodì. Tohle není 20. století, kde drogy prodávali na rohu ulice pøekupníci, kteøí ili neustále ve strachu pøed policií a úøady.}
{331}{}{Dobrá, pak - }
{332}{}{Ale - }
{333}{}{Myslím, mám radši - }

# 10. YOU SELL DRUGS IN THE STORE? (9)
{350}{}{Tohle je NEW RENO. ádní policajti, ádné zákony a spousta zákazníkù, kteøí nemají pøedstavu, jaké jedy kupují v lékárnì na ulici. Je to odpovìï na tvoji otázku barbare?}
{351}{}{Je, kromì jediné: Byl Richard Wright jedním z tvıch zákazníkù?}
{352}{}{Dobrá, v poøádku... co máš na skladì?}
{353}{}{Vlastnì, mám víc otázek.}
{354}{}{Ale, jak jsi øekl, drogy jsou... jedovaté. Zabíjí ducha. Není ti na obtí je prodávat?}
{355}{}{Jistì, e je. A teï u pùjdu.}

# 11. DOES IT BOTHER YOU TO SELL DRUGS IN THE STORE? (10)
{365}{}{Má mi bıt na obtí, prodávat je idiotùm, otrokáøùm, mafiánùm a primitivùm, kdy by bez nich byl svìt lepší? Barbare, tøi slova -- já vlastnì pomáhám.}
{366}{}{Dobøe. Mohu vidìt, co máš na skladì?}
{367}{}{Dobrá, v poøádku. Podívej, mám nìjaké další otázky.}
{368}{}{Drogy tady z New Rena si nacházejí cestu k dalším místùm a ubliují dalším lidem. To tì nezajímá?}
{369}{}{Právì se chystám odejít.}

# 12. YOU SELL DRUGS IN THE STORE 2? (11)
{375}{}{Tak? Co bych se o nì staral?}
{377}{}{Lidská rasa utrpìla strašnou tragédii. Snaíme se vše vybudovat znovu. A zdá se, e prodávání Jetu... zpoïuje rekonstrukci.}
{378}{}{Dobøe. Teï u musím jít.}

# 13. SOME OF THE PEOPLE BEING HARMED ARE . . . (12)
{385}{}{No a co? Nikdo pøece NENUTÍ ty idioty šòupat Jet. Není tu nikdo, kdo by chodil a cpal jim to do krku!}
{386}{}{Mohu vidìt - }
{387}{}{Ale ne - }
{388}{}{To je tvùj - }

# 14. SOME OF THE PEOPLE BEING HARMED ARE . . . 2 (13)
{395}{}{Ty osvícenı hlavy v Reddingu MOC DOBØE VÌDÍ, co berou, take k nim necítím ani špetku lítosti! Vzdálenì se mì to tıká -- Jet vyplení z lidské rasy šmejdy, take zhebnou!}
{396}{}{No dobøe. Mohu vidìt tvùj sklad?}
{397}{}{Kde je ten Redding, o kterém jsi mluvil? Proè ses o nìm zmínil?}
{398}{}{Zmiòuješ se o Reddingu. Proè je Jet tak oblíbenı v Reddingu?}
{400}{}{Kadı si mùe dìlat, co uzná za vhodné. Já u musím jít.}

# 15. REDDING 1 (14)
{410}{}{Hmm, Redding je... zvláštní pøípad. Ono, lidé v Renu mohou za to, e se Reddingu tak dobøe dodává. Konec koncù, zkusíš-li Jet jednou, jsi chycen. Tak si vydìlám na ivobytí.}
{411}{}{To, o èem mluvíš, mohu vidìt u tebe na skladì?}
{412}{}{Kdo dodává Reddingu? A proè?}
{413}{}{To vidím. Hele, mám nìjaké další otázky.}
{414}{}{Aha. U musím jít.}

# 16. WHO'S SUPPLYING REDDING? (15)
{420}{}{No, pochybuji, e ti to vùbec kdy dojde, ale tady, v New Renu, se nevyrábí nic uiteèného. Je to jako velká, jasnì osvìtlená oáza na poušti. No a na druhou stranu, Redding.}
{421}{}{... pokraèuj.}
{422}{}{... PRODUKUJE nìco uiteèného.}
{423}{}{To u mi staèí.}

# 17. . . . DOES PRODUCE SOMETHING USEFUL (16)
{430}{}{Poprvé a naposledy tì varuji: Neskákej mi do prdele do øeèi. Nemám rád "bystré" barbary, kteøí vaní, kdy mají poslouchat. Není divu, e stále všichni pouíváte oštìpy.}
{431}{}{Ne všichni z nás. Napøíklad já pouívám rùzné zbranì k zabíjení lidí. Ukái ti je.}
{432}{}{Promiò. Pokraèuj.}
{433}{}{Shnij v pekle. Jdu pryè. }

# 18. GO ON ABOUT REDDING (16, 17)
{440}{}{Redding má stálé pracovní síly. Tìí se tam suroviny, pøevánì zlato. New Reno mùe toto zlato spolehlivì upotøebit. No a nìkdo si velmi dobøe spoèítal, e kdy budou všichni tamní horníci závislí na Jetu, vznikne nekoneènı kolobìh. U chápeš?}
{441}{}{Ano... kromì jediného: Odkud je Jet?}
{442}{}{Kdo je to ten "nìkdo" ?}
{443}{}{Áno, chápu. Mám však ještì nìjaké otázky.}
{444}{}{U nechci nic slyšet. Musím u jít.}

# 19. WHERE DID JET COME FROM? (20)
{450}{}{(Ukazuje na Myrona.) Proè se nezeptáš tvého malého ošklivého ropuchovitého pøítele? Jsem si jist, e by ti to rád øekl. (Civí na Myrona.) e jo malièkı?}
{451}{}{Za Jet mùeme podìkovat jediné osobì. Doneslo se k tobì nìco o tom malım pokladu z Mordinovy rodiny -- Myronovi? Tak ten malı bastard vytvoøil Jet. A Velkı jeíš Mordino ochotnì povìdìl všem, kde se dá získat.}
{452}{}{Øekni mi o Myronovi víc.}
{453}{}{Existuje na Jet lék?}
{454}{}{Mám další otázky...}

# 20. WHERE DID JET COME FROM? (18)
{460}{}{Velkı jeíš Mordino dodává Jet do Reddingu. Dost riskantní. Jakmile se to ale jednou dalo do pohybu, u to nešlo zastavit. A horníci jsou ztracení.}
{461}{}{Odkud se Jet vzal?}
{463}{}{Aha. Podívej, mám ještì nìjaké další otázky...}

# 21. TALK ABOUT MYRON (19, 24)
{470}{}{Mozolnatı jako ropucha a absolutnì bez morálky. Nicménì, bystré dítì. Vysoké IQ. Je to plıtvání mozkem na vyrábìní drog pro jistou zkázu.}
{471}{}{Kde ho mohu najít?}
{472}{}{Aha. Ještì mám další otázky.}

# 22. WHERE CAN I FIND MYRON? (21)
{480}{}{Mordino ho nìkde dobøe schoval. Pravdìpodobnì ho dùkladnì støeí. Neví se pøesnì kde.}
{481}{}{Dìkuji za informaci. Mohu se podívat, co máš na skladì?}

# 23. ANY CURE FOR JET? (19, 20)
{490}{}{Lék na závislost! Che! Znám jen dva: Jeden je smrt. Druhı je zamknout se v kleci na rok bez Jetu a vypotit ho z tìla ven. Hmmm. "Lék," ty hlupáku! Takovı nesmysl!}
{492}{}{Musí existovat lék. Jaké je chemické sloení Jetu?}

# 24. JET COMPOSITON? (23)
{505}{}{Proè se nezeptáš svého pøítele? To je jeho práce.}
{506}{}{Já to zboí jenom prodávám. Zeptal bych se vìdcù. Nebo Myrona. On vytváøí drogy.}

# 25. TALK ABOUT VILLAGE (6, 42)
{515}{}{(Renesco na tebe tiše upøenì hledí.)}
{516}{}{(Renesco se na tebe opìt pronikavì zadíval.)}
{517}{}{Myslím, e bys chtìl slyšet o Arroyu. Je to mírumilovná vesnice. Kromì rostlin posedlıch zlımi duchy... a samozøejmì Chrámu naplnìného utrpením s pastmi plnımi oštìpù. A muem, kterı jí obrovské mravence.}
{518}{}{Hele, slyšel jsi nìkdy o GECK nebo Vault 13?}
{519}{}{Dobrá, take... jdu pryè.}

# 26. TALK ABOUT VILLAGE 2 (25)
{525}{}{(Renesco se na tebe stále upøenì dívá.)}
{526}{}{A nìkdy si Starší libuje v takovıch strašnıch blbùstkách, jako... he-he... a jedné noci, jsem porušil svoji pøísahu celibátu a uil si to s Reynou. Tou - její - nohy - by rozdrtily - silou - tisíce - hadù, v kaòonu Arroya.}
{1526}{}{A nìkdy si Starší libuje v takovıch strašnıch blbùstkách, jako... he, he... a jedné noci, jsem porušila svoji pøísahu neposkvrnìnosti a poøádnì si to uila s Korem, jen - otøásal - jako - tisíc - høebcù, v kaòonu Arroya.}

# 27. TALK ABOUT VILLAGE 2 (26)
{535}{}{(Renesco se na tebe podíval znièenım pohledem.)}
{536}{}{Jako by to bylo vèera. Reynino tìlo záøilo v mìsíèním svìtle jako støíbro, kdy tu poklekla a... hej, víš co? Mohl bys mít Starší. Je pøiblinì stejnì stará jako ty.}
{1536}{}{Jako by to bylo vèera. Korovo tìlo se tøpytilo v mìsíèním svìtle jako støíbro, kdy jsem poklekla a... hej, víš co? Mohl bys mít Starší. Je pøiblinì stejnì stará jako ty.}

# 28. WHO ARE YOU? (27)
{545}{}{(Renesco na tebe stále zírá, jako by tì chtìl udìlat neviditelnım.)}
{546}{}{Jestlipak víš, e Arroyo vzniklo díky mému pøedkovi -- Zakladateli? Vykonal legendární cestu z jihu po poráce velkého zla. (Vypneš hruï a hrdì se zadíváš do dálky.) Nyní, JÁ nìco vykonám pro svùj kmen -- najdu pro nìj svatı GECK!}
{547}{}{Dobrá, take dost pøíbìhù. Radìji zase pùjdu na cestu. Chvála Vaultu!}

# 29. GECK? (25, 26, 27, 28, 36)
{555}{}{(Renescùv pronikavı pohled mizí.) }
{556}{}{GECK? To jako 'Vytvoø si svùj vlastní Ráj?' Vybavení obsahující základní replikátorovou jednotku, ètecí zaøízení holodiskù s volbami z knihovny kongresu a malou tukovou baterku?}
{557}{}{Ano, ale to teï není dùleité. Neukonèili jsme to povídání o Arroyu.}
{558}{}{Ano! Má vesnice má velké problémy a potøebujeme GECK pro její obnovu. Víš, kde ho mohu najít?}
{559}{}{Øíká se, e je uschován ve Vaultu 13, nebo tak aspoò øíkají legendy. Znáš takové místo?}
{560}{}{Jestlie nehodláš poslouchat, kdy recituji svaté písmo, pùjdu pryè.}
{561}{}{Mùe bıt. Ale u musím jít.}

# 30. I HAVEN'T FINISHED TELLING YOU ABOUT ARROYO (29)
{570}{}{Tvá vesnice je prokletá a ty s ní. Proè barbar jako ty hledá GECK?}
{571}{}{Arroyo... rodná to vesnice... má problémy, velké problémy. Potøebujeme GECK pro její obnovu.}
{572}{}{Øíká se, e je uschován uvnitø Vault 13. Víš o takovém místì?}
{573}{}{Nemyslím, e se chci o tomhle s tebou bavit. Nashle.}

# 31. GECK NEEDED TO RESTORE VILLAGE (29, 30)
{580}{}{Hmmmmm. Jistìe by to nìjak šlo... a snadno. Kdyby se GECK našel. Ale ty nevíš, kde zaèít hledat. NCR nebo Vault City snad... ale já pochybuji, e by nìco mìli... ještì...}
{581}{}{Ještì...?}

# 32. GECK NEEDED TO RESTORE VILLAGE (31)
{590}{}{Nicménì, ti pøipitomìlí bastardi tì mohou nasmìrovat. I kdy mluví pomalu a heslovitì...}
{591}{}{NCR nebo Vault City øíkáš? Pùjdu hledat ta místa a zeptám se vesnièanù na GECK. Dìkuji ti.}
{592}{}{Proè by nemohl bıt GECK v posvátném Vault 13? Bible øíká, e je GECK ukryt uvnitø Vault 13.}
{593}{}{Velmi zvláštní. Teï mám nìjaké další otázky.}
{594}{}{Dobrá, take... Pùjdu si to ovìøit. Díky.}

# 33. GECK NEEDED TO RESTORE VILLAGE (X)
{600}{}{Sakra ne, barbare. Slyšel jsem o Vaultech, jasnì, ale ne o Vault 13. Nejuzavøenìjší je Vault City na severovıchodì... a jestlie ti nafoukaní aristokraté obıvali kdysi Vault, urèitì tam ji neijí.}
{601}{}{Vault City, øíkáš? Pùjdu nalézt Vault City a zeptám se jeho obyvatel na GECK. Dìkuji ti Renesco. Chvála Vaultu!}
{602}{}{"Vaulty?" Je víc Vaultù?}
{603}{}{Hmmm. Mám nìkolik dalších otázek.}

# 34. THANKS (32, 33, 35)
{610}{}{Jestli pùjdeš do Vault City, tak mi nedìkuj barbare. Líp na tom budeš v New Renu. Pøinejmenším ti lidé udìlají èestnı pohøeb.}
{611}{}{Dobrá, take... Jsem na cestì do Vault City. Chvála Vaultu! }
{612}{}{Aha. Díky za varování.}

# 35. MORE THAN ONE VAULT? (33)
{620}{}{Proè myslíš, e se nazıvá Vault TØINÁCT, vrhaèi oštìpù? To byl tvùj kmen tak hloupı, nebo ti ta legenda v hlavì tak propláchla mozek?}
{623}{}{Ó, zase mi lichotíš. No, stejnì díky za info. }

# 36. YOUR VOCABULARY IS IMPRESSIVE (6, 42)
{630}{}{Lidé zde v New Reno nemají rádi takovou konverzaci. A teï, co chceš?}
{632}{}{Mluvíš jako vzdìlanı mu. Slyšel jsi nìkdy o GECK nebo místì nazıvaném Vault 13?}
{634}{}{No nic, nevadí.}

# 37. GLASSES (3, 42)
{640}{}{(Renesco chòapl po tvıch brılích a nasadil si je. Jeho oèi se rozšíøily. Sladké Reno! TO JE TEN DÙVOD, proè ten zkurvenı krám vypadá takhle. (Svraštil èelo.) Takovı bordel... a co je to na policích? Vypadá to jako brahmíní lejna.}
{641}{}{Vítám tì.}
{642}{}{Tìší mì.}

# 38. YOU'RE WELCOME (37)
{650}{}{Hmmmm! Já...hmmm... ehm... odkud máš tohle?}
{651}{}{Nue, byl tu malı radškorpión, víš, a vìdec, kterı ho trénoval a... víš co? Dokonce ani já tomu nevìøím. Nech si to pro sebe, jo?}
{652}{}{Jenom si øeknìme, kde je najdu.}

# 39. YOU'RE WELCOME 2 (37)
{660}{}{Poèkej chvilku! Odkud to máš?}
{661}{}{Nue, byl tu malı radškorpión, víš, a vìdec, kterı ho trénoval a... víš co? Dokonce ani já tomu nevìøím. Nech si to pro sebe, jo?}

# 40. I GOT THEM (38, 39)
{670}{}{Dobøe, já... ehmm... jsem ti... eh, vdìènı. Myslel jsem, e budu muset trpìt s tìmi rozbitımi brılemi do konce ivota. Jestli mohu pro tebe nìco udìlat, øekni... a, uh, budu o tom PØEMİŠLET.}
{671}{}{Co takhle slevu?}
{672}{}{Zapomeò na to..., a ve zdraví si jich uij, OK?  Mám na tebe pár dalších otázek.}
{673}{}{Jednou -- a ten den moná nikdy nepøijde -- tì poádám o pomoc. Ale do té doby pøijmi tyto brıle jako svatební dar pro mou dceru. }

# 41. DISCOUNT (40)
{680}{}{Ehhh...}
{681}{}{Errr....}
{682}{}{Dobøe...}
{683}{}{Dobrá! Dobrá! Dám ti slevu! Hmphhh.}
{684}{}{Pojï sem. Trochu ti slevím. Tak pojï...}
{687}{}{Skvìlé! Podívejme se, co mùeš dostat, "kamarádíèku"}
{688}{}{Vıbornì! Teï mám další otázky.}
{689}{}{Vrátím se do obchodu pozdìji.}

# 42. QUESTIONS? (8, 10, 11, 14, 15, 18, 19, 20, 21, 22, 23, 24, 32, 33, 41, 49, 50, 51, 54, 55, 57, 65, 66, 67, 68, 71, 72, 73, 74, 75)
{700}{}{Dìlej, rychle.}
{701}{}{Podívej, jsem zaneprázdnìnı mu.}
{702}{}{Nue? Tak u ven s tím!}
{703}{}{He?}
{704}{}{U ti nìkdo povídal o mé vesnici Arroyo?}
{706}{}{Prodal jsi Jet Richardu Wrightovi?}
{707}{}{Pøicházím vybrat daò pro pana Salvatore}
{710}{}{Hledám nìjakou souèástku pro èistièku vzduchu v Broken Hills.}
{711}{}{Máš zajímavı slovník... ty jsi místní?}
{712}{}{Zapomeò na mì.}

# 43.  TOOLS: SO? (3, 42)
{725}{}{(Oèi se mu zúily.) Tak?}
{726}{}{Dobrá, potøebuji souèástky k opravì ventilace v jejich dolu. ádám tì o pomoc.}
{727}{}{Dobrá, potøebuji souèástky k opravì ventilace v jejich dolu. Vachy mì poslal. Øekl, eéé... povídal e... a do prdele!}
{728}{}{Dobrá, potøebuji souèástky k opravì ventilace v jejich dolu. Vachy mì poslal. Øekl, 'kanárek' nakopl kyblík.'}

# 44.  TOOLS: SURE. HERE'S SOME MONEY (43)
{735}{}{Ano, moná mám nìjaké souèástky, které mohou opravit ventilaci. 100 dolarù.}
{736}{}{Beru to. Dej to sem.}
{737}{}{Co takhle 50 dolarù?}
{738}{}{Nemám u sebe stovku... Vrátím se s penìzi pozdìji. }

# 45.  200 OR NOTHING (3, 42, 44)
{745}{}{Rozèilují mì lidé, kteøí chtìjí handlovat. Musím poèítat s inflací. 200, nebo nech.}
{746}{}{(Mraèí se.) 200, nebo nic.}
{747}{}{Dvì stovky?! Pøed vteøinou jsi øekl STO!}
{748}{}{Uh, Vezmu to. Dej to sem.}
{749}{}{Uh, dvì stovky u sebe nemám. Vrátím se s penìzi pozdìji.}

# 46.  HE SAID: SHIT (43)
{755}{}{Silnì pochybuji, e to øekl. Nebylo to -- 'kanárek nakopl kyblík'?}
{756}{}{Ano.}

# 47.  HE SAID: AND . . . (43, 46)
{760}{}{A...?}
{761}{}{"A?"}

# 48.  SECOND PART? (47)
{765}{}{A druhá èást toho byla...?}
{766}{}{"Druhá èást?" Neøekl nic o DRUHÉ èásti. Ten podlej bastard!}

# 49.  HE DIDN'T?! THAT BASTARD! (44, 45)
{769}{}{Klid, jen tì zkouším. Není ádná druhá èást. Dobrá, jestlie tì poslal Vachy, mám dojem, e by se NÌCO našlo. }
{770}{}{Tady máš. Neupus to.}
{771}{}{Díky. Mám další otázky...}
{772}{}{Dìkuji. }

# 50. YOU SELL DRUGS TO WRIGHT'S SON? (7, 10, 42)
{780}{}{NEPOKOUŠEJ se mì obvinit. Jestli chceš vìdìt, kdo to byl, zeptej se Køemílka a Vochomùrky jestli poøád ještì prodávají Jet, vylepšenı arsenem.}
{781}{}{'Køemílek' a 'Vochomùrka?' Kdo to je?}
{782}{}{Jules øekl, a se tì zeptám. Øíká, e prodáváš sraèky.}
{783}{}{Poøezanej Jimmy øekl, a se tì zeptám. Øíká, e prodáváš sraèky.}
{784}{}{Oni oba mi øekli, a se TÌ na to zeptám. Øekli, e prodáváš sraèky.}
{785}{}{Nemyslím si, e to byl arsen... Myslím, e byl otrávenı.}
{786}{}{Mùeš mi øíci nìco o tom prázdném kanistru Jetu?}
{788}{}{Pùjdu se jich tedy zeptat. }

# 51. WHO ARE THEY? (50)
{795}{}{Ten vydøiduch Jules a zasranej lháø 'Poøezanej Jimmy'. Jules vdy vyèkává u vstupu do mìsta a hledá pøitroublé návštìvníky, které podvede a Poøezanej Jimmy obchoduje na 2. ulici se zbytkem idiotù New Rena.}
{798}{}{Øekli, a se tì zeptám. Øíkají, e prodáváš sraèky. Sraèky, které zabíjí lidi.}
{800}{}{Jdu jim to øíct.}

# 52. THEY SAID ASK YOU. (51)
{805}{}{Podívej, barbare... ty ani nevíš, o èem vatláš.}
{806}{}{Ach, myslím, já - }
{807}{}{He? Dobøe, tak potom, proè ne - }
{808}{}{Nevadí. Mám další otázky - }
{809}{}{Koukám, e bude lepší, kdy pùjdu - }

# 53. THEY SAID ASK YOU 2. (52)
{815}{}{OTEVØI ještì jednou hubu a ZAŠEPTEJ, nebo jen NAZNAÈ a pan Wright zaøídí, e já... nebo ty... a udìláš cokoliv, naše ivoty nebudou mít ani cenu sraèek. JESTLIE se to stane --}
{816}{}{Ach? Take ty - }
{817}{}{Já?! Teï vydr jenom - }

# 54. THEY SAID ASK YOU 3. (53)
{825}{}{Jestli se to stane, sráèi, pøísahám, e zemøeš døív ne já. Teï... naposledy, to dítì ode mì nikdy nekoupilo sraèky, rozumíš?}
{826}{}{JULES øíká, e to neprodal dítìti. JIMMY øíká, e to neprodal dítìti. TY øíkáš, e jsi mu to neprodal. Jeden z vás le.}
{827}{}{JULES øíká, e to neprodal dítìti. JIMMY øíká, e to neprodal dítìti. TY øíkáš, e jsi mu to neprodal. Buï všichni lete, nebo... je za to zodpovìdnı nìkdo jinı.}
{828}{}{Mùeš mi øíct nìco dalšího o Richardu Wrightovi? Kdo se tu potloukal okolo, kdo by mohl uívat drogy?}
{829}{}{Dobrá. Teï mám další otázky.}
{830}{}{Dobrá, dobrá... u jdu.}

# 55. THEY SAID THEY DON'T KNOW. (54)
{835}{}{Mohu odpovìdìt jednoduše. Jeden z tìch dvou parchantù le, aby si chránil prdel. Oni dva prodávají 90% Jetu v Renu a je to jediné místo, kde to mohl ten chlapec, o kterém mluvíme, dostat.}
{836}{}{Nebo to nìkdo koupil od vás tøí. Kdo z tvıch zákazníkù za poslední mìsíc mohl mít kontakt s... obìtí?}
{837}{}{Mùeš mi øíct nìco dalšího o Richardu Wrightovi? Kdo se tu potloukal okolo, kdo mohl uívat drogy?}
{838}{}{Aha... mám další otázky.}
{839}{}{U jdu.}

# 56. THEY SAID ASK YOU. (55)
{845}{}{Jsi STUPIDNÍ bastard.}
{846}{}{Jsi STUPIDNÍ èubka.}
{847}{}{ØEKL jsem ti, abys tu neøíkej jeho jméno. Vypadni! Jestli tì tu ještì uvidím, ZASTØELÍM TÌ. A jestli sem pøijde pan Wright èmuchat a bude si myslet, e jsem zabil toho chlapce, ZABIJU tì jako prvního.}
{848}{}{Nevyhrouj mi, dìdku.}
{849}{}{Pane jo. U jdu.}

# 57. KILLER REVEALED! . . . (55)
{855}{}{Nemám tušení. Neznal jsem toho chlapce, take neznám jeho pøátele ani jeho zvyky. Jedinı, kdo by ti jistì mohl nìco øíct, leí na Golgotì.}
{856}{}{Golgotì?}
{858}{}{Asi to zkusím. Nashle.}

# 58. TRIBUTE (3, 42)
{865}{}{Máš to marnı. Zaplatil jsem panu Salvatorovi jeho 'daò' *pøed dvìmi tıdny* pøesnì podle soupisu. Nevím, kdo jsi, nebo co si myslíš, e dìláš, ale ze mì nic nevyrazíš. Pitomèe.}
{866}{}{Hele, dìdku. Neser mì. Vybal, co máš, nebo budeš kašlat krev.}
{867}{}{Jsem zástupce pana Salvatora. Dáš mi daò, kdy tì o to ádám, a udìláš to hned.}
{868}{}{Zkontroluji si seznam u pana Salvatora, a potom se vrátím.}

# 59. TRIBUTE 2 (58)
{875}{}{Jsi hluchı magore? }
{876}{}{Jsi hluchá krávo? }
{877}{}{ØEKL JSEM. ZAPLATIL JSEM DAÒ U PØED *dvìmi tıdny*. Jestli jsi skuteènì od Salvatora, urèitì to víš!}
{878}{}{Podívej. Naposled: naval daò.}
{879}{}{Ty jsi hluchı. Jsem zástupce pana Salvatora a ty zaplatíš daò.}
{880}{}{Varoval jsem tì dìdku. Vypadá to, e budeme mít tìkou cestu. Je èas zemøít.}
{881}{}{Zkontroluji s panem Salvatorem danì a pak se vrátím.}

# 60. SPEECH SUCCESS (59)
{890}{}{Doka, e jsi od Salvatora, a já zváím, jestli ti zaplatím. Jinak dostaneš hovno.}
{891}{}{Nemusím se prokazovat. Jsem zástupce, a to je všechno, co potøebuješ vìdìt.}
{892}{}{To si myslíš, e je ta laserová pistole jen pro parádu?}
{893}{}{Jestli mi nezaplatíš do pìti vteøin, ZABIJU tì.}

# 61. SPEECH FAILURE (59, 60)
{900}{}{Táhni do hajzlu, vydøidušskej gangstere! Ještì jednou se tì tu uvidím a zastøelím tì!}
{901}{}{Varoval jsem tì. Je èas zemøít.}

# 62. SHOW OFFICIAL, CAN'T PAY (3, 42, 60)
{910}{}{Hmmm. Na tom nezáleí, nezaplatím. Poslední vybírání mì témìø znièilo.}
{911}{}{To se mì netıká. Dáš mi teï peníze. Pan Salvator nehodlá poslouchat tvé vımluvy.}

# 63. GIVE ME MONEY EVEN THOUGH YOU CAN'T PAY (62)
{920}{}{Vyhroování ti nepomùe. Pan Salvator chce své prachy. Já je nemám. Bude na mì zuøit, ale na tebe taky. Salvator nemá rád lidi, kteøí ho zklamou... radìji si to rychle spoèítej.}
{921}{}{Mám to. Zaplatím tvùj podíl na toto období. Vymìním to za slevu v tvém obchodì.}
{924}{}{Trochu si to promyslím... vrátím se.}

# 64. IN EXCHANGE FOR FREE ACCESS TO YOUR STORE (63)
{930}{}{Vydr primitive...}
{931}{}{Nesouhlasím s tebou. Má trpìlivost je u konce. Toto jsou mé podmínky.}

# 65. THOSE ARE MY TERMS (64)
{940}{}{Já... podívej, teï, já... hmmmm... tak dobøe. Dostaneš... "slevu."}
{941}{}{Dovol, podívám se k tobì do skladu. Udìlám si 'nákup'.}
{943}{}{Teï momentálnì nic nechci, ale nedìlej si starosti, vrátím se.}

# 66. HOW'S THE GLASSES (64)
{950}{}{(Dá nohu pøes nohu.) To staèí. Jestli oèekáváš nìco jako hodného samaritána, ŠEREDNÌ se mılíš. Take... co chceš?}
{951}{}{Zatracenì, jakı obchodní øeditel tì zplodil! CHCEŠ nìco?! Tady! Tady! Vezmi si TO! Vezmi si VŠECHNO co mám! Dám ti cokoliv a NECH MÌ U O SAMOTÌ!}
{952}{}{Dovol mi prohlédnout si tvùj sklad.}
{953}{}{Mìl bych nìjaké otázky.}
{955}{}{Co je proboha tohle?}

# 67. POISONED (50)
{960}{}{Otrávenı? O èem to vatláš?}
{961}{}{Pøíznaky smrti ukazovaly na otrávení radškorpioním jedem. Myslím, e zemøel, protoe jeho Jet byl otrávenı, ne protoe by se pøedávkoval.}
{962}{}{V této místnosti jsem našel prázdnı kanistr od Jetu. Uvnitø byly známky jedu radškorpiona.}
{963}{}{Nevadí. Mám další otázky...}
{964}{}{Zapomeò na to. U musím jít.}

# 68. POISONED 2 (67, 73, 74)
{970}{}{Radškorpion? (Renesco náhle ztuhl, jako by si na nìco vzpomnìl.)}
{971}{}{Ty z kurvy synu! Tys *otrávil* dítì, co?}
{972}{}{Ty o tom nìco víš, co?}

# 69. POISONED 3 (68)
{980}{}{Fíha! Poèkej chvilku!}
{981}{}{Nemotej mì, Renesco! Vykrucuješ se a pøidáš se k Richardovi. Chápeš?}
{982}{}{Tak je to. Já a pan Wright jdeme hodit øeè. Dobrı den, Renesco... nebo bych mìl øíct, "nashledanou."}

# 70. POISONED 4 (69)
{990}{}{Poèkej chvilku! Podívej... NEPRODAL jsem to dítìti! Nikdy nic ode mì nekoupil! Já... byl jsem poádán udìlat trochu Jetu vylepšeného jedem radškorpiona, ale... ale NEPRODAL jsem to dítìti!}
{991}{}{Byl jsi POÁDÁN udìlat otrávenı Jet? Pro koho?}
{992}{}{Komu jsi to prodal?}

# 71. POISONED 5 (70)
{995}{}{Salvatoøi to ádali -- øekli, e to má bıt "speciální objednávka". Nevìdìl jsem, e se to chystají dát Wrightovu dítìti. Musíš mi vìøit... Neotrávil bych dítì!}
{996}{}{Jenom dospìlım, huh, Renesco? Promiò, ty zkurvysynu...}
{997}{}{Proè jsi otrávil Jet? Musel jsi vìdìt, e se tím chystají nìkoho zabít.}
{998}{}{Dobrá, dobrá, vìøím ti. Mám další otázky.}
{999}{}{Dr hubu! Podívej, mám další otázky.}
{1000}{}{Salvatoøi, huh? Myslím, e by o tom pan Wright rád vìdìl.}

# 72. RESPONSE (71)
{1005}{}{Salvatoøi mì vlastní, toto místo je jejich. Kdy nìco chtìjí, musím to pro nì udìlat, jinak mì zabijí a nahradí mì nìkım jinım. Nikdy by mì však nenapadlo ublíit tomu chlapci.}
{1007}{}{Dr hubu. Teï mám na tebe další otázky.}
{1008}{}{Urèitì jsi mìl ty nejlepší úmysly, kdy jsi pøidával do Jetu jed. Nashledanou, Renesco.}
{1009}{}{Pozdìji, Renesco. }

# 73. JET CANISTER (50)
{1020}{}{Je to prázdnı. To je kanistr Jetu jako stovky dalších všude v New Reno. Mohu ti ještì s nìèím pomoct?}
{1021}{}{Je to tvoje?}
{1022}{}{Víš nìco o stopách jedu radškorpiona, které jsou v tom kanistru?}
{1023}{}{No, mám jiné otázky.}

# 74. JET CANISTER (73)
{1030}{}{Ne. Mohu ti pomoci s nìèím JINİM?}
{1033}{}{Ne. Nashle.}

# 75. GOLGOTHA? (57)
{1040}{}{Golgotha? Masovı hrob za mìstem smìrem na jih. Jdi za smradem... smrdí to stejnì jako ty.}
{1041}{}{Mám nìjaké další otázky.}
{1042}{}{Snaíš se mi lichotit, Renesco a budeš dlouho umírat.}
{1043}{}{DÍKY, Renesco.}

{2000}{}{Povedlo se ti prokázat Renescovu spoluvinu na smrti Richarda Wrighta.}

# END LINES
{5257}{}{ Je tak velkı. Pùjdu }
{5259}{}{ nekøiè, PROÈ STÁLE KØIÈÍŠ, PØESTAÒ KØIÈET }
{6259}{}{ ZABIJI TÌ}
{5260}{}{ ...*èichám*... dostaò velkého bratra rozseká tì, dìdku! Potom budeme mít zmrzlinu a ... *cítím*... zákusek a velká oslava s klauny.}