#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
# 0. QUICK LOOK [FEMALE]
{100}{}{Vidíš vedoucí vızkumnici Marjorie Reedovou.}

# 0. LOOK [FEMALE]
{150}{}{Vidíš unavenì vyhlíející enu. Má dohola oholenou hlavu a na sobì bílı pláš.}
{151}{}{Vidíš Marojorie Reedovou. Plní injekèní støíkaèku a nìco si potichu mumlá.}

# 1. FLOAT (COMPANION = MYRON)
{200}{}{Zdravím, Myrone.}
{201}{}{Myrone, máte chvilku?}
{202}{}{Nemáte ponìtí, kdy koneènì dorazí ti noví otroci, Myrone?}
{203}{}{Myrone, ty nové vısledky vypadají slibnì, velmi slibnì...}
{204}{}{Myrone, na minutku?}

# 2. FLOAT (NORMAL)
{215}{}{Kde je sakra ten Myron... }
{216}{}{Pøiveïte mi Myrona. To musí vidìt.}
{217}{}{Kdyby tak ti otroci aspoò chvilku dreli hubu... }
{218}{}{Kde jsem sakra nechala tu støíkaèku? }
{219}{}{Nevidìl nìkdo èíslo 31? Byl tu ještì pøed chvilièkou.}
{220}{}{Zvyšte dávky Jetu Beta na Subjektu 17. Na dvojnásobek.}
{221}{}{Testy Jetu Beta jsou slibné, ale... }
{222}{}{"Létání" vydrí patnáct minut a hodinu... øeknìme dávku na hodinu... hmmmmnnn.}
{223}{}{Subjekt 12 stále krvácí z plic... }
{224}{}{To u je popáté, co mìl Subjekt 12 záchvat... zvyšte dávku, uvidíme, co se stane.}
{225}{}{No, take JAKÉ halucinace mìl?}
{226}{}{Zkotrolujte mu tep. Jestli je v tolerované mezi, zvyšte dávku.}
{227}{}{Proè se ta otrokynì v kotrolní skupinì zabila? Vdy jsme na ní nic netestovali!}
{228}{}{Zatracení stráci, dìlají jenom potíe...}

# 3. CLICK (COMPANION = MYRON)
{235}{}{Testy probíhají podle rozvrhu, pane Myrone.}
{236}{}{Ten novı druh Jetu vzbuzuje extrémní závislost. Otroci by se pro nìj zabíjeli navzájem.}
{237}{}{Otroci radìji berou Jet, ne jedí, tak je to silné.}
{238}{}{Kdo jsou ti lidé s vámi, pane Myrone? Nové subjekty pro testy?}
{239}{}{Tøetí testovací skupina zatím vypadá nejlépe, pane Myrone.}
{240}{}{Pane Myrone, myslím, e by další skupina mìla obsahovat alespoò tøi dìti.}
{241}{}{Myrone, pane, Subjekt 46 mìl infarkt. Omezili jsme dávky na šets dennì.}
{242}{}{Myrone? Potøebujeme novou zásobu injekèních støíkaèek z Vault City. U nemùeme stále pouívat jedny a ty samé.}
{243}{}{Myron, koneènì! Nevíte, kdy koneènì pøijdou další otroci, pane?}
{244}{}{Myrone, pane, pøesunuli jsme tøi otroky z kontrolní skupiny do testovací skupiny kvùli tìm respiraèním selháním minulı tıden.}
{245}{}{Pane Myrone... museli jsme zastøelit jednoho otroka na útìku. Potøebujeme náhradu.}
{246}{}{Pane Myrone... ten novı halucinogen, kterı jste vyvinul, je slibnı. Ale nevzniká na nìj taková závislost jako na Jet.}

# 4. INTRO (WTG)
{250}{}{(Plešatá ena ani nevzhlédla od svého zápisníku.) Ano?}
{251}{}{Ne!}
{252}{}{Ano!}
{253}{}{He, he. Plešoutá ty. Ty jak chlap.}
{254}{}{Delenn?}
{255}{}{Odejdi}
{256}{}{Kdo jste?}
{257}{}{Promiòte, omyl. Hledám jinou plešatou enu se zápisníkem. Nashle.}

# 5. RETARD (4)
{265}{}{(ena zvedla pohled a zírá na tebe.) Ty jsi jeden z testovacích subjektù? Jakoby na tom záleelo... Stráci! Zadrte toho otroka!}
{266}{}{Kde otrok? Nevidim nikoho.}

# 6. WHO ARE YOU? (4)
{275}{}{Jsem VELMI zamìstnaná, take kdyby vám to nevadilo... (Zvedla pohled od zápisníku a zamraèila se.) KDO jste? Kdo vás sem pustil?}
{276}{}{Jsem VELMI zamìstnaná, take kdyby vám to nevadilo... (Zvedla pohled od zápisníku a zamraèila se.) Zase vy? Co chcete tentokrát?}
{277}{}{Máte otevøené dveøe.}
{278}{}{Jsem novı zamìstnanec.}
{279}{}{Hledám Myrona. Kde ho najdu?}
{280}{}{To jsou vısledky testù? Bylo by moné prohlídnout si je?}
{282}{}{Promiòte e obtìuji, omyl.}

# 7. DOOR WAS OPEN (6)
{295}{}{Tenhle prostor je uzavøenı... pro návštìvníky. Odejdìte nebo zavolám stráe.}
{296}{}{Ale moment, mám nìjaké otázky...}
{298}{}{To jsou vısledky testù? Bylo by moné prohlídnout si je? Jsem novı pracovník.}
{300}{}{Dobrá.}

# 8. BUT HEY. . . (7, 24)
{310}{}{Stráe! Stráe! Zatknìte tu osobu!}

# 9. I'M ONE OF THE NEW PERSONNEL (6, 7)
{315}{}{DALŠÍ stráce. Ha! Jakoby k nìèemu byli... hele, urèitì MÁTE instrukce od toho, kdo vás sem poslal. Bavte se s ostatními stráci a neobtìujte lidi, kteøí pracují. A teï jdìte.}
{316}{}{Já nejsem stráce, mám pracovat ve vızkumu. Máte pro mì práci?}
{317}{}{Promiòte, ale tak nìjak mám dojem, e mi instrukce máte pøedat VY. Pøi prvním pohledu na vás mi to bylo jasné. A moná bychom se potom mohli stavit na veèeøi...?}
{318}{}{Díky. U vás nebudu zdrovat.}

# 10. I'M ONE OF THE NEW RESEARCHERS (6, 7, 9)
{325}{}{Tak VİZKUMNÍK? Hmmmm. Ještì jsem vás nevidìla. Kolik toho víte o farmaceutickém vızkumu?}
{326}{}{Uh, dost. Ale mám pocit, e si musím ještì nìco zaøídit...}
{327}{}{Vím toho docela dost o sloení a vırobì základních neurochemickıch slouèenin. Myslím, e mé schopnosti se tady uplatní.}
{328}{}{Musím jít.}

# 11. I'M ONE OF THE NEW RESEARCHERS (10)
{335}{}{Ha! Tak si to jdìte zaøídit... VEN! A rychle, nebo zavolám stráe.}
{336}{}{Dobøe.}
{337}{}{U jdu... ::bla bla::... ty plešatá pipko.}

# 12. I KNOW QUITE A BIT ABOUT BASE NEUROCHEMCIAL COMPOUNDS . . . (10)
{345}{}{Hmmmm. Dobøe. Take k naší práci -- testujeme efekt a sílu metamfetaminu zvaného Jet.}
{346}{}{Rozumím. Jak jde vızkum?}
{347}{}{Jasnı. No, prohlídnu si zbytek laboratoøí.}

# 13. I SEE. AND HOW IS THE RESEARCH COMING? (12, 22, 25)
{355}{}{Moc dobøe ne. Náš èasovı plán je dost tìsnı a musíme rychle vylepšit a zkvalitnit vırobu Jetu.}
{356}{}{Proè? Jet mi pøipadá dostateènì úèinnı.}
{357}{}{Proè tak tìsnı èasovı plán?}
{358}{}{Ah, to vypadá na tvrdou práci. No, nebudu zdrovat.}

# 14. WHY THE TIGHT SCHEDULE? (13)
{365}{}{Nikdo sem nepøišel a neøekl to na rovinu, ale je to nejspíše kvùli distribuci Jetu v Reddingu. Jet je *dost* silnı, ale stále je ještì co vylepšovat, a 'velení' chce zvıšit Jetovou závislost v Reddingu.}
{366}{}{Co je to s tím Reddingem?}
{367}{}{Hmm, tak hodnì štìstí, a to stihnete vèas.}

# 15. WHY? JET SEEMS ADDICTIVE ENOUGH ALREADY . . . (13)
{375}{}{Je *dost* silnı, ale ještì poøád je tady prostor pro vylepšení. 'Velení' chce rozšíøit distribuci Jetu v Reddingu, a chtìjí úroveò závislosti tak blízko 100% jak to jen jde. To nám zabere ještì hodiny tvrdé práce.}
{377}{}{Díky za informace. Na moment si odskoèím, hned se vrátím.}

# 16. WHAT'S THE DEAL WITH REDDING? (14, 15)
{385}{}{Udìlat horníky v Reddingu závisle na Jetu? A pak kdo ovládá Jet, ovládá i Redding. Typická mocenská partie.}
{386}{}{Take... kdo ovládá drogy?}

# 17. SO WHO DOES CONTROL THE DRUGS? (16)
{395}{}{Kdo ovládá drogy? Mordinové. Pochopitelnì, Myron u vytvoøil základ Jetu a zpùsob vıroby. My u po nìm jenom uhlazujeme a vylepšujeme drobné nedostatky.}
{396}{}{Myron je váš šéf?}

# 18. MYRON'S OUR BOSS? (17)
{405}{}{DALO by se tomu tak øíct. Je chytrı, to mu uznám, ale kašle na to, co se dìje tady nahoøe. Vìtšinou je ve sklepních
 prostorách. ádné návštìvy... kromì vagónù prostitutek. Typickı vedoucí projektu.}
{406}{}{Bylo by moné vidìt ho?}
{407}{}{Jo, i kdy v marketingu to bıvá ještì horší. Díky za informace, já si teï na moment odskoèím. Hned jsem zpátky.}

# 19. COULD I SEE HIM? (18)
{415}{}{Moná... dám vám doèasnı prùkaz; jen ho ukate strácùm. Ale pospìšte si, Myron nemá rád, kdy 
 ho lidé otravují dlouho.}
{416}{}{Moná... dám vám doèasnı prùkaz; jen ho ukate strácùm. Ale pospìšte si, Myron nemá rád, kdy 
 ho lidé otravují dlouho... i kdy ve vašem pøípadì moná udìlá vıjimku.}
{417}{}{Díky za prùkaz. Na vidìnou.}

# 20. EXCUSE ME FOR BEING FORWARD (FEMALE) (9)
{425}{}{Jsem opravdu VELMI zamìstnaná, take kdyby vám to nevadilo...}
{426}{}{Mám opravdu dost práce, take...}
{427}{}{Tak nic.}
{428}{}{Stejnì dík.}
{429}{}{Dík ::bla bla:: ty arogantní plešatá dìvko.}

# 21. EXCUSE ME FOR BEING FORWARD (GOOD) (9)
{435}{}{To je... hmm... Jsem VELMI polichocena, ale mám teï  spoustu práce. Take... uh... }
{436}{}{No, nevadilo by vám, kdy pøijdu pozdìji a vyzvednu vás po práci? Jenom veèeøe a trochu rozumné konverzace. Vypadáte jako nìkdo, kdo by si potøeboval trochu odpoèinout od práce. Musíte tady mít tìkou práci.}
{437}{}{No, za zeptání nic nedám.}

# 22. DO YOU MIND IF I PICKED YOU UP AFTER WORK . . .? (21)
{445}{}{Oh,  TOLIK práce zase nemám. Vìtšinou jen rutinní testy chemikálií, obèas problém s nìkterım otrokem...}
{446}{}{Co øíká na vstøikování experimentálních metamfetaminù do zotroèenıch lidí váš smysl pro humanitu?}
{447}{}{Uau. TO zní nebezpeènì. Není to... nebezpeèné? Máte mnoho obìtí mezi pacienty?}
{448}{}{Testování "chemikálií"? Vánì? Jak to jde?}
{449}{}{To zní zajímavì, ale já teï musím na chvíli pryè. Za chvíli se vrátím.}

# 23. DON'T YOU EVER QUESTION YOUR HUMANITY? (22)
{455}{}{TO byl pokus o ubohı ert?}
{456}{}{Jen se ptám. Teda, kdybyste vy byla odvleèena do otroctví, prodána sem a napumpovaná drogami, co byste tomu øekla?}
{457}{}{Uh, jo. Promiòte, musím bìet.}

# 24. PUMPED FULL OF DRUGS? (23)
{465}{}{Já jsem na TÉHLE stranì a oni jsou na té DRUHÉ. A kdy u probíráme takové hypotetické monosti, nechcete si VY vyzkoušet, jaké to je bıt na jejich místì? Máme dost volnıch míst.}
{466}{}{No tak moment...}
{467}{}{Uh, ne díky. Nashledanou, musím jít.}

# 25. PATIENT FATALTIES (22)
{475}{}{Mrtví otroci? Pár jich je. Vìtšinou nehody -- nešastné pøedávkování. Vìtšinou vina laboranta. Anebo sebepoškození. Nìkteøí do sebe dostanou Jetu pøíliš a pak chtìjí lítat DOOPRAVDY.}
{476}{}{Kromì toho, jak jde testování?}
{477}{}{Aha. Hmm, díky za informaci. Velmi jste mi pomohla.}

# 26. ACTUALLY, I WAS LOOKING FOR MYRON (6)
{485}{}{Zkuste to dole v laboratoøi. Hlídané dveøe. Pokud ho uvidíte, vyøiïte mu, aby se sem stavil. Snad nebude mít moc "práce".}

# GET BADGE MESSAGE
{1000}{}{Máš doèasnou propustku od Marjorie.}
