#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
# QUICK LOOK
{100}{}{Vidíš velkého banditu}
{101}{}{Vidíš Rica.}

# EXAMINE
{150}{}{Vidíš velkého mue s kamennou tváøí. Vypadá, jako by snídal cihly sypané cementem. }
{151}{}{Vidíš Rica, Montova bodyguarda. Vypadá, jako by chroupal kamení.}

# 1. FLOAT DIALOGUE
{175}{}{Hurggg}
{176}{}{Hnrfff}
{177}{}{Snffff}
{178}{}{Urb-luu}
{179}{}{Klurgggg}
{180}{}{Oog}

# 2. CLICK DIALOGUE
{200}{}{Já kámo vot Monte. TY kámo vot Monte?}
{201}{}{Já mlátım lydy, kerı Monte øekne aby mlátyl}
{202}{}{Mlátım lıdi}
{203}{}{Byju èlovìky pìsama jako hraju na buben, hoho}
{204}{}{Byju rád já}
{205}{}{::Bezzubì se usmívá::}
{206}{}{::Škrábe se po celém tìle::}
{207}{}{::Protahuje se::}
{208}{}{Mmm}
{209}{}{Hmmm- mmm.}
{210}{}{Nerad mluvit}
{211}{}{tı fájn vóniš}
{212}{}{Jé, ty vóniš jáko mámhinka}
{213}{}{Ty fáájò. Já nebyj ty}
{214}{}{hhh tı lıbıš hhe}
{215}{}{Uhhh...Já Rico...}