#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
# 0. QUICK LOOK
{100}{}{Vidíš Luise Salvatora.}

# 0. LOOK
{150}{}{Vidíš staršího, dobøe obleèeného gentlemana. Má u sebe kyslíkovou bombu. Zdá se, e má problémy s dıcháním.}
{151}{}{Vidíš Luise Salvatora. Má u sebe kyslíkovou bombu. Zdá se, e má problémy s dıcháním.}

# 1. FLOAT (WTG)
{200}{}{*uch*}
{201}{}{::vzzz hvízd::}
{202}{}{*uch* *ech*}

# 2. FLOAT: INTRUDER (WTG)
{210}{}{Stráe! Strá...*ech* *kch*...Stráe!}

# 3. PERMISSION = FALSE (WTG, 5)
{215}{}{(Salvatore se k tobì otoèil s kamennou tváøí. Zlomek vteøiny si tì prohlíí, pak dìlá podivnı pohyb rukou.  Okamitì se rozjeèely poplachové sirény.)}
{216}{}{Auuuuu! Zlum to! Uši bolí! UŠI BOLÍ!}
{217}{}{JÁ NEMLUVÍŠ PØES SIRÉNA. VYPNEŠ A MY MLUVÍŠ}
{218}{}{ZMRZAÈÍM TÌ, dìdku! U se nikdy nepostavíš na ty svoje noièky!}
{219}{}{Hmm, asi by bylo lepší nejdøív získat povolení...}
{220}{}{Do prdele!}
{221}{}{Uh, to asi nebyla hotelová sluba, e?}

# 4. MAIN DIALOGUE INTRO (WTG)
{230}{}{(Starší mu si tì prohlíí. Jeho tváø je vyhublá a pokrytá jaterními skvrnami. V ruce drí dıchací masku, která je pøipojená ke kyslíkové bombì u jeho boku.) Cot... po mnì chceš?}
{231}{}{Já chceš...já nevíš, co chceš}
{232}{}{Já chceš}
{233}{}{Já }
{234}{}{Odejdi}
{235}{}{Mám pro vás nìjaké informace.}
{236}{}{Mám pro vás nìjaké informace, pane Salvatore.}
{237}{}{Hledám práci.}
{238}{}{Pane Salvatore, øíká se o vás, e jste silnı a férovı. Chci pro vás pracovat.}
{239}{}{Chci vìdìt, odkud máte ty svìtelné pistole.}
{240}{}{Øíká se, e jste dal otrávit syna pana Wrighta. Proè?}
{241}{}{Špatná místnost, promiòte. Hned zmizím.}

# 5. RETARD DEATH WARRANT/TOO MANY QUESTIONS (4, 6, 7, 13, 14, 17, 19, 20, 21, 28, 29, 30, 43)
{250}{}{Øekl jsem ti dùvod, proè byl chlapec zabit. A to nesmí opustit tuto místnost.  (Salvatore dìlá podivnı pohyb rukou.  Okamitì se rozjeèely poplachové sirény.)}
{251}{}{(Salvatore si tì znechucenì po zlomek vteøiny prohlíí, pak dìlá podivnı pohyb rukou.  Okamitì se rozjeèely poplachové sirény.)}
{254}{}{Zabiju tì dìdku! Zabiju!}

# 6. INFORMATION (4)
{270}{}{(Hluboce se nadechl z masky a pak potøásl hlavou.) Nemáš nic, 
 co by mì zajímalo, }
{271}{}{Um, nevzpomínám si, e by tady u padlo mé jméno. Odkud mì znáte?}
{272}{}{Uh, dobøe. V tom pøípadì bych se chtìl zeptat, jestli pro mì nemáte náhodou nìjakou práci.}
{276}{}{Uh, vlastnì to asi vypadá, e jsem ve špatné místnosti. Promiòte...}

# 7. HOW DO YOU KNOW ME? (6)
{290}{}{(Tiše se na tebe chvíli dívá. Moná je tvou otázkou pobavenı, nebo podrádìnı....tìko øíct.)Znovu, }
{291}{}{Uh...hmmm. Hmm, teda, hledám práci.}

# 8. I'M LOOKING FOR A JOB (IMPOLITE) . . . (4, 6, 7)
{305}{}{(Zhluboka se nadechl z kyslíkové masky, a pak se lehce usmál.) Jistì.
 A PROÈ bych tì mìl najmout?}
{306}{}{No, proè ne? Øeknìte mi co, a já to udìlám. Pracuju tvrdì a mám dostateèné schopnosti a znalosti, které jsou tøeba.}
{307}{}{Uh? e hledám práci? Promiòte, pøeøekl jsem se. Vlastnì u odcházím.}

# 9. I'M LOOKING FOR A JOB (POLITE) . . . (4, 6, 7, 10)
{315}{}{(Zhluboka se nadechl z kyslíkové masky, a pak se lehce usmál.) Jistì. Ale poaduji... gesto dobré vùle. Ukázku tvé ... ochoty pracovat pro mì.}
{316}{}{Co po mì chcete?}
{317}{}{Co mám pro vás udìlat, pane Salvatore?}

# 10. I'M HARDWORKING, WELL-ARMED . . . (8)
{325}{}{(Zatøásl lehce hlavou.) Tvoje naivita... Slova nedostaèují. Chceš pracovat pro Luise Salvatora? Potom musím vìdìt, jestli se na tebe mohu spolehnout.}
{326}{}{Hele, mùete se mnou poèítat.}
{327}{}{Nechte mì, a vám to dokáu, pane Salvátore. Dejte mi nìjakı úkol.}

# 11. WHAT WOULD YOU HAVE ME DO? (9, 10)
{335}{}{(Zhluboka se nadechl z kyslíkové masky.) Je tady...jeden mu...kterı 
 zneuil své...umìní s kartami a okradl mì. Suma je...triviální. Uráka ne. Chci ho mrtvého a peníze, které ukradl, zpìt.}
{336}{}{Kdo je ten zlodìj?}
{338}{}{Kolik ukradl?}
{339}{}{To mùe bıt docela tvrdé. Mohu dostat jednu z tìch svìtelnıch pistolí, kterou vaše rodina pouívá?}
{340}{}{Uh, takovou práci nedìlám.}

# 12. ANY QUESTION FROM ABOVE (11)
{350}{}{Mason ti poví... detaily. (Kıvnul k vıchodu.) Teï jdi.}
{351}{}{Dobøe.}
{352}{}{Dìkuji vám, pane Salvatore. Jdu za Masonem.}

# 13. PUSS-OUT (8, 9, 10, 11, 12, 24, 25, 33, 34, 35, 37)
{360}{}{Potom pro mnì...nemáš uitek. Odejdi.}
{361}{}{Uh, momentíèek. Udìlám to.}
{362}{}{Tiše odejdi.}

# 14. CAN I HAVE ONE OF THOSE LASER WEAPONS? (11, 34)
{370}{}{(Zúil oèi. Jeho další slova jsou pronášena s drsnım syèením..)
 ::Ještì jsi mi nic NEDOKÁZAL:: Teï jdi za Masonem. øekne ti detaily ... tvého úkolu.}
{371}{}{Dobøe, zapomeòte prozatím na ty pistole.}
{372}{}{Rozumím, pane Salvatore. Odpuste mi mou otázku. Jdu za Masonem.}
{373}{}{Hele: jestli mì poøádnì nevyzbrojíte, nemùu pro vás poøádnì pracovat.}

# 15. MISSION IS ASSIGNED (WTG)
{380}{}{Promluv si s Masonem. øekne ti... víc o tvém úkolu.}

# 16. LLOYD MISSION ACCOMPLISHED (WTG)
{385}{}{(Salvatore se na tebe podíval a zhluboka se nadechl z masky.) Zbavil jsi...mì starostí se zlodìjem?}
{386}{}{Ne...Lloyd utekl z mìsta i s penìzi.}
{387}{}{Yo. Supi ho nìkdy touhle dobou dotrávili a teï ho serou do písku.}
{388}{}{Ještì ne.}
{389}{}{Ne, pane Salvatore. Lloyd utekl z mìsta i s penìzi.}
{390}{}{Ano. Udìlal jsem z nìj pøíklad, pane Salvatore.}
{391}{}{Ještì ne, pane Salvatore.}

# 17. LIE (16)
{400}{}{Pøesto...jsi øekl Masonovi, e jsi úkol splnil.}
{401}{}{No, ano, ale...}

# 18. AND THE MONEY? (16)
{405}{}{A ... peníze. Byly získány?}
{406}{}{Ne, nikde nebyl}
{407}{}{Ne, Lloyd je u staèil utratit.}
{408}{}{Ano.}
{410}{}{Ne, pane Salvatore, nikde se nedaly najít.}
{411}{}{Ne, pane Salvatore, Lloyd je staèil utratit.}
{412}{}{Ano, pane Salvatore.}

# 19. NO, NO MONEY (18)
{420}{}{Tvé instrukce byly získat peníze, které ukradl. Bylo to splnìno?}
{421}{}{No, ne, protoe --}
{422}{}{Uh, mám peníze --}
{423}{}{No, víte, já--}

# 20. YES (18, 19)
{430}{}{Vezmu si ty peníze.}
{431}{}{No, ale já je u sebe nemám...}
{432}{}{Dej mu 250.}
{433}{}{Dej mu 500.}
{434}{}{Dej mu 750.}
{435}{}{Dej mu 1000.}
{436}{}{Dej mu 1000. (Tolik jich bylo.)}
{437}{}{(Utéct.)}

# 21. WRONG AMOUNT (20)
{450}{}{Tato èástka...není tolik, kolik mi bylo ukradeno. Moná neznáš správnou èástku, nebo si chceš moná zbytek nechat. V kadém pøípadì...}
{451}{}{Oh, jistì, drobná numerická chybka, hned ji napravím...}

# 22. CORRECT AMOUNT (20)
{455}{}{(Salvatore kıvnul, kdy jsi mu pøedal peníze, ale nechal si jenom polovinu. Zbytek pøistrèil k tobì.) Druhá...polovina je tvá.}
{456}{}{Hej, dík.}
{468}{}{Dìkuji vám, pane Salvatore.}

# 24. I HAVE ANOTHER JOB FOR YOU (22, 23)
{475}{}{(Pan Salvatore se zhluboka nadechl z masky.) Mám pro tebe další ...záleitost, která si ádá tvé pozornosti.}
{476}{}{Jistì, proè ne. Co je to za práci - další úkol zabij a pøines?}
{477}{}{Mám zájem o práci, pane Salvatore. Co mám udìlat?}
{478}{}{Ne, u nechci dìlat takovou práci, zabíjení není pro mì.}
{479}{}{U ádnou práci pro mnì, pane Salvatore. Musím odejít.}

# 25 MISSION TWO: EXTORTION (24)
{485}{}{Osoba v mém...distriktu mi nezaplatila...poplatek...za sluby, které poskytuju. Zinkasuj ho. Jestli bude nìco namítat, informuj ho, e jsi mùj...zástupce v této otázce. Promluv si s Masonem o detailech.}
{487}{}{Ano, pane Salvatore. Pùjdu za ním.}
{488}{}{Ne dík, nedìlám do vydírání.}

# 26. CAUGHT IN LIE (16)
{495}{}{Leš mi... Vím, e ještì ije.}

# 27. TRIBUTE (WTG)
{500}{}{Je záleitost, kterou jsem tì povìøil, vyøízena?}
{501}{}{Ano, pane Salvatore, mám poplatek, kterı jste mì poslal vybrat.}
{502}{}{Jo, mám ten 'poplatek' tady u sebe.}
{503}{}{Ještì ne. Nedaøí se mi ho z toho starého dìdka.}vyrazit 
{504}{}{Ještì ne, pane Salvatore. A se vrátím, budu ho mít sebou.}

# 28. NO, NO MONEY (27, 29)
{515}{}{Mason øíkal, e jsi ho 'vybral'. Je to pravda?}

# 29. I HAVE THE TRIBUTE (27, 28)
{525}{}{Velmi dobøe. (Èeká.)}
{527}{}{Dej mu 900.}
{528}{}{Dej mu 800.}
{529}{}{Vlastnì, nemám ho SEBOU...}

# 30. WRONG AMOUNT (29)
{540}{}{Tato èástka...není tolik, kolik mi bylo ukradeno. Moná neznáš správnou èástku, nebo si chceš moná zbytek nechat. V kadém pøípadì...}

# 31. CORRECT AMOUNT (29)
{545}{}{(Salvatore kıve, kdy mu pøedáváš peníze.) Dobrá práce. Zde je tvùj 25% podíl.}
{546}{}{(Salvatore kıve, kdy mu pøedáváš peníze.) Uspokojující práce. Zde je tvùj 10% podíl.}

# 32. COLD REFUSAL (22, 23, 31, WTG)
{555}{}{(Zhluboka se nadechl z masky.) Udìlals...co jsme chtìl. U dál
 nepotøebuji tvé... sluby. (Ukazuje k vıchodu.) Teï odejdi.}
{556}{}{Uh...okay.}
{557}{}{Mohl bych dostat jednu laserovou pistoli jako èást mého platu?}

# 33. I HAVE ANOTHER JOB FOR YOU (31)
{565}{}{(Zhluboka se nadechl z masky.) Mám další...záleitost, ve které bych mohl vyuít tvé schopnosti.}
{566}{}{Jistì, proè ne? Co to je za kšeft? Další vydírání?}
{568}{}{Ne, diky. Nemám zájem pokraèovat ve vydírání.}

# 34. MISSION THREE: GUARD ASSIGNMENT (33)
{575}{}{Brzy se bude odehrávat velmi...citlivá transakce. Potøebuji další... strá, abych zajistil,  e nedojde k nìjakım zádrhelùm. Promluv si s Masonem a udìlej, co ti øekne.}
{576}{}{Co je to za transakci?}
{577}{}{Kde se bude ta transakce odehrávat?}
{578}{}{Hodila by se mi jedna z tìch laserovıch pistolí. Bylo by to moné?}
{579}{}{Nemohu se této mise zúèastnit, pane Salvátore. Musím odejít.}

# 35. WHAT IS THIS TRANSACTION (34)
{585}{}{Mason ti poví detaily. Teï jdi.}

# 36. CAN I HAVE ONE OF THOSE LASER WEAPONS? (YES) (34)
{595}{}{Ano. Teï ano. Ale budeš mít sebou i další vızbroj. Promluv si s Masonem.
Dá ti jednu z pistolí.}
{596}{}{Dobøe..}

# 37. MADE MAN? (YES) (WTG)
{605}{}{Sedni si, }
{607}{}{Bude to pro mnì pocta, pane Salvatore.}
{608}{}{Nemohu. Mám další závazky. Ale dìkuji za nabídku.}
{610}{}{Byla by to pro mì pocta, pane Salvatore, ale musím odmítnout. Mám povinnosti k další rodinì... a ke své matce.}

# 37a. MADE MAN NO
{615}{}{To je velice... nešastné. Nemohu riskovat, e by se od tebe nìkdo dozvìdìl, co se stalo v poušti. Sbohem, }
{616}{}{Hej?! Poèkejte minutku...!}
{617}{}{Jo ták?! Tak pojï! Pøiveï si celou tu svoji rodinu, a je mùu zabíjet jednoho po druhém..}

# 38. MADE MAN? (CHOOSE) (37)
{620}{}{Velmi dobøe. Musíš si vybrat jméno...}
{621}{}{Co takhle...}

# 39. MADE MAN? (CHOOSE) (38)
{630}{}{(Kıvnul) To je dobré jméno. Teï si bì promluvit s Masonem. Má pro tebe nìco.}

# 40. MADE MAN? (AFTER THE FACT) (WTG)
{640}{}{Zdravím tì, }

# 41. SALVATORE_DONE = TRUE (AFTER THE FACT) (WTG)
{645}{}{Momentálnì tvé sluby nepotøebuji, }

# 42. SALVATORE CHOKING TO DEATH (WTG)
{650}{}{...}
{651}{}{...hurkkk...}
{652}{}{...*ugh*...Já...*kch*...*hvízd*...}
{653}{}{...ne...já...*hurrkkk*}
{654}{}{...pomoz...*polk*...prodím...}
{655}{}{...slituj...se...}
{656}{}{*vzz*}
{657}{}{...já...}
{658}{}{...já...}
{659}{}{::Pøestal dıchat.::}
{660}{}{Ha ha. Miluji zabíjení starıch senilù.}

# 43. MR. WRIGHT'S SON POISONED (4, 6, 7)
{675}{}{(Pan Salvatore si tì dlouho mlèky prohlíí, potom zaèíná mluvit.) My
 Salvatorové...budeme vládnout Renu. Jestli kvùli tomu musí zemøít dítì, tak zemøe.}
{676}{}{Co má vrada Wrightova syna spoleèného s vládou Novému Renu? To nedává SMYSL.}
{677}{}{Zavradil jsi nìèího SYNA, Salvatore. A tím sis podepsal vlastní rozsudek smrti...}
{678}{}{Aha. Jen mì to zajímalo.}

{800}{}{Šéf Salvatore byl zavradìn..}
{825}{}{Šéf Salvatore byl zmasakrován.}
{850}{}{Lloydùv "pøípad" byl vyøešen.}
{875}{}{Poplatky pana Salvatora byly vybrány.}
{900}{}{Nyní jsi èlen rodiny Salvatore.}
{925}{}{Úspìšnì jsi odpozoroval tajnou transakci.}

# END LINES
{5233}{}{! Kdo ty}
{5270}{}{. Take...co ode mnì CHCEŠ?}
{5290}{}{: Co...ode mnì CHCEŠ?}
{5605}{}{. Plníš vše, oè tì poádám. Byl bych rád, kdyby ses stal jedním z rodiny Salvatorù a stal se jedním z mıch blízkıch spolupracovníkù.}
{5640}{}{.}
{5645}{}{.}
