#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
# QUICK LOOK
{100}{}{Vidíš jednoho ze Salvatorovıch muù.}

# LOOK (IF THUG HAS LASER WEAPON.)
{150}{}{Vidíš mrzutého mue. Je zamraèenı a zírá pøímo pøed sebe. V ruce drí zvláštní pistoli.}
{151}{}{Vidíš mrzutého mue. Je zamraèenı a zírá pøímo pøed sebe.}
{152}{}{Vidíš jednoho ze Salvatorovıch muù. Vypadá jakoby nemìl volno deset let.}
{153}{}{Vidíš jednoho ze Salvatorovıch muù. Zírá pøímo pøed sebe s krutım vırazem na tváøi.}
{154}{}{Vidíš jednoho ze Salvatorovıch muù. Vypadá tiše, smrtelnì, a jakoby spal ve stoje.}
{155}{}{Vidíš jednoho ze Salvatorovıch muù. Vypadá tiše, smrtelnì, a unudìného xmrti.}

# 2. FLOAT/CLICK DIALOGUE: ENCLAVE DESTROYED IS TRUE
{160}{}{::Uctivì kıvnul hlavou::}
{161}{}{Musíš mít poøádnou páru. Jinak by tì Enkláva dostala.}
{162}{}{Jsi skoro jako Tommy Tvrïák.}
{163}{}{Slyšel jsem o tobì a Enklávì. }
{164}{}{Co takhle zkusit si to znovu s jinou postavou?}

# 3. FLOAT DIALOGUE: PLAYER = FEMALE/MALE, MADE MAN, FA=SALVATORE, PRIZEFIGHTER, PORN STAR [SNEAK]
{170}{}{Co se tady plazíš?}
{171}{}{Proè ty tajnosti? Nìkdo po tobì jde?}
{172}{}{Snaíš se neupoutat pozornost?}
{173}{}{Co se tady plazíš? Nìkdo tì honí?}

# 4. FLOAT DIALOGUE: PLAYER = MADE MAN, FA=NOT SALVATORE
{180}{}{No, jestlipak to není }
{181}{}{ZTRACENEJ, kámo? Tak radši zmiz, ne tì najdu.}
{182}{}{Tady nìkdo hledá problémy...}
{183}{}{Vypadni. Teï.}
{184}{}{Jestli nechceš mít vánı problémy, radši rychle vypadni.}
{185}{}{A hele, jestlipak to není }
{186}{}{ZTRATILA SES, holèièko? Radši rychle vypadni.}
{187}{}{Zajíèek hledá problémy...}

# 6. FLOAT DIALOGUE: POLITE [ARMED]
{195}{}{ádnı zbranì, schovej to.}
{196}{}{Odlo tu zbraò.}

# 7. FLOAT DIALOGUE: FEMALE, PORN STAR, POLITE [ARMED]
{200}{}{Sleèno, obávám se, e vás budu muset poádat, abyste odloila svou zbraò.}
{201}{}{Sleèno, je mi líto, ale tady se nesmí nosit zbranì.}

# 8. FLOAT DIALOGUE: SLAVER [ARMED]
{205}{}{TY! Otrokáøi! Zajistiti tu zbraò! HNED.}
{206}{}{ádnı zbranì, otrokáøi.}
{207}{}{Schovej ten kvér, otrokáøi.}
{208}{}{Otrokáøi, chci, abys schoval tu zbraò.}

# 9. FLOAT DIALOGUE: SLAVER [SNEAK]
{210}{}{Ty! Otrokáøi! Pøestaò se tady plazit!}

# 10. FLOAT DIALOGUE: NORMAL [ARMED]
{215}{}{Hej! Schovej tu zbraò. Hned!}
{216}{}{ádné zbranì, schovej to.}
{217}{}{Odlo u zbraò. Hned.}
{218}{}{Okamitì odlo tu zbraò.}

# 11. FLOAT DIALOGUE: NORMAL [SNEAK]
{220}{}{HEJ! Pøestaò se nám tady plíit!}

# 12. FLOAT DIALOGUE: COMPANION: ROBOBRAIN
{225}{}{Robotùm vstup zakázán. Vypadnìte.}
{226}{}{ádní roboti. A zmizne.}

# 13. FLOAT DIALOGUE: COMPANION: MARCUS
{230}{}{ádní mutanti. Okamitì ho vyhoï, nebo to udìlám sám.}
{231}{}{Mutantùm vstup zakázán. Okamitì zmiznìte.}

# 15. CLICK DIALOGUE: POWER ARMOR
{235}{}{Chtìlo by mnì zajímat, jak to dìláš s tím brnìním na záchodì?}

# 16. CLICK [MADE MAN, FA = SALVATORE]
{240}{}{Pane.}
{241}{}{Dobrı den, pane.}
{242}{}{Bìhem mé sluby se nic zvláštního nestalo, pane.}
{243}{}{Potøebujete nìco, pane?}
{244}{}{Pokud vás nìkdo bude obtìovat, pane, dejte nám vìdìt a my to s ním vyøídíme raz dva.}
{245}{}{Dejte si pozor na Tomma Tvrïáka. Má dlouhé péro, ale krátkı rozum a malé sebeovládání.}
{246}{}{Pan Salvátore byl na tom se zdravím vdycky špatnì, u od tenkrát, kdy jsem se s ním poprvé setkal. U je hodnì starı.}
{247}{}{Tyhle nové pistole nám opravdu hodnì pomohly, bez nich bychom v Renu nemìli tak dobré pozice.}
{248}{}{Tyhle nové pistole jsou sice trochu divné, ale snadno se s nimi zachází.}
{249}{}{Støelil jsem toho Bishopskıho kreténa s mojí novou pistolkou a vona udìlala dírku v nìm i ve ZDI za ním.}
{250}{}{ádnı z chlapcù doopravdy neví, odkud ty nové pistole jsou. Je lepší se neptat.}
{251}{}{Ostatní rodiny se nám od Masakru vyhıbají.}
{252}{}{Ostatní rodiny se nám vyhıbají od té doby, co máme tyhle nové pistole. Je jim jasné, co se stane, kdyby nás otravovali.}
{253}{}{Tyhle pistole støílejí paprsky svìtla. A ty paprsky jsou schopné provrtat COKOLI.}
{254}{}{Rodina Salvatorù je ke mnì slušná. Nestìuju si.}
{255}{}{Bishopové mají jenom velké kecy. Salvátorové nemusí mluvit, za nì mluví èiny. }
{256}{}{Na severu je všechno klidné.}
{257}{}{Dneska jsem potkal pár Bishopù. Hned pøešli na druhou stranu ulice. Pouèili se.}
{258}{}{Dneska je všechno v pohodì.}
{259}{}{Madam.}
{260}{}{Dobrı den, madam.}
{261}{}{Bìhem mé sluby se nic zvláštního nestalo, madam.}
{262}{}{Potøebujete nìco, madam?}
{263}{}{Pokud vás nìkdo bude obtìovat, madam, dejte nám vìdìt a my to s ním vyøídíme raz dva.}

# 18. CLICK [MALE/FEMALE, MADE MAN, FA = NOT SALVATORE]
{275}{}{Radši zmiz, ne budeš mít problémy. }
{276}{}{Dej si bacha. A radši hned zmiz, ne se naštvu.}
{277}{}{Budeš mít poøádnı prùser, pokud tady budeš ještì chvíli poskakovat.}
{278}{}{Nevím, co tady chceš,  }
{279}{}{Nevím, co chceš dokázat, }
{280}{}{Doporuèuju ti opustit tohle místo. Rychle.}

# 19. CLICK [MALE/FEMALE, PRIZEFIGHTER]
{285}{}{Kdo tì uèil boxovat?}
{286}{}{Víš, Salvátorové by tì mohli potøebovat. }
{287}{}{Jestli chceš práci, promluv si s Masonem. }
{288}{}{kdyby tì boxování pøestalo bavit, vdycky se mùeš pøidat k nám.}
{289}{}{ZDAR! Díky, vyhrál jsem na tobì dvì kila! }
{290}{}{Hej, šampióne! Ten poslední boj byl vynikající!}
{291}{}{Vidìl jsem tì v ringu. Máš skvìlej pravej hák. }
{292}{}{Kolik udìláš na benèi?}
{293}{}{Kde posiluješ?}
{294}{}{Bacha na dímaèku. Chutnají mu uši.}
{295}{}{Koupil bych ti drink, ale pøišel jsem o všechny peníze. Vsadil jsem na tvıho protivníka. }

# 20. CLICK [MALE, PORN STAR]
{305}{}{Mùu pro tebe nìco udìlat?}
{306}{}{Tohle není porno studio, milovníku.}
{307}{}{Bì nìkam jinam, prokurvátore.}

# 21. CLICK [PORN STAR, FEMALE]
{310}{}{Je mi to fakt líto...opravdu...ale nemùu se teï vybavovat. Stav se, a budu mít po slubì.}
{311}{}{Láme mi to srdce, ale nemùu se s tebou bavit ve slubì. }
{312}{}{No tak, srdíèko, nemùu se soustøedit na slubu. }
{313}{}{Nemùu ti pomoct.}
{314}{}{Slyšel jsem, e Tommy Tvrïák si s tebou chce zahrát.}
{315}{}{Ne teï, zlatíèko. Business.}
{316}{}{Pokecal bych si s tebou, moná i nìco víc, ale kdyby mì chytil boss...}

# 22. FLOAT DIALOGUE: SLAVER [ARMED]
{325}{}{ádnı zbranì, otrokáøi.}
{326}{}{Schovej ten kvér, otrokáøi.}
{327}{}{Otrokáøi, chci, abys schoval tu zbraò.}

# 23. FLOAT DIALOGUE: SLAVER [SNEAK]
{330}{}{Ty! Otrokáøi! Pøestaò se tady plazit!}
{331}{}{Plazící se otrokáøi mi pøipomínají terèe na støelnici. }
{332}{}{Jestli se tady budeš ještì chvíli plazit, nìkdo tì støelí mezi oèi, otrokáøi.}

# 24. FLOAT DIALOGUE: NORMAL [ARMED]
{335}{}{Hej! Schovej tu zbraò. Hned!}
{336}{}{ádné zbranì, schovej to.}
{337}{}{Odlo u zbraò. Hned.}
{338}{}{Okamitì odlo tu zbraò.}

# 25. FLOAT DIALOGUE: NORMAL [SNEAK]
{340}{}{Pøestaò se tady plazit, nebo budeš mít problémy.}

# 26. [SLAVER, IF BAD REACTION]
{345}{}{Jestli se chceš bavit o kšeftování s otroky, jdi si promluvit s Masonem.}
{346}{}{Salvatorové mají všechny otroky, které potøebují. Tady ti pšenka nepokvete.}
{347}{}{Nemám èas se bavit, otroku... sorry, otrokáøi.}
{348}{}{Nemùu ti nijak pomoct. A i kdybych mohl...}
{349}{}{Hele, já nemám èas. Jestli se chceš vybavovat, jdi na ulici a zaèni huèet do nìjaké kurvy.}

# 27. [SLAVER, GOOD REACTION]
{355}{}{Jestli chceš koupit nebo prodat pár duší, promluv si s šéfem.}
{356}{}{Nemyslím, e by šéf potøeboval nìjaké otroky, ale mùeš to zkusit.}

# 28. CLICK [FEMALE/MALE, NO REP, GOOD REACTION]
{360}{}{Hledáš práci? Promluv si s Masonem.}
{361}{}{Jestli hledáš práci, zajdi si za Masonem.}

# 29. CLICK [NO REP, BAD REACTION]
{365}{}{Hele, já nemám èas. Jestli se chceš vybavovat, jdi na ulici a zaèni huèet do nìjaké kurvy.}
{366}{}{Nemám èas kecat.}
{367}{}{Nemùu ti pomoct. Smùla.}
{368}{}{Nemùu ti pomoct. Sorry.}
{369}{}{Teï ne, zlato. Business.}
{370}{}{Pokecal bych si, ale mohl by mì vidìt šéf nebo Mason...}
{371}{}{Nemám èas na kecání.}

# 30. CLICK/FLOAT: LENNY
{380}{}{Ten ghoul a radši vypadne. A HNED!}
{381}{}{Jestli tady ten ghoul bude smrdìt ještì chvíli, spálím ho.}
{382}{}{Ten ghoul si chce asi zaplápolat. A vypadne.}

# END OF LINES
{1180}{}{. A jestli rychle nevypadne, bude to mít svoje jméno vytesanı v kameni. Na náhrobním kameni...}
{1185}{}{. A jestli rychle nevypadne, bude to mít svoje jméno vytesanı v kameni. Na náhrobním kameni...}
{1278}{}{, ale radši to jdi hledat nìkde jinde.}
{1279}{}{, ale jdi to radši dokazovat nìkam jinam.}
