#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
# quick look
{100}{}{Vidíš vìdce.}

# examines
{150}{}{Vidíš vánì vyhlíejícího mue se zápisníkem a injekèní støíkaèkou. Ignoruje tì.}
{151}{}{Vypadá hodnì unavenı a popudlivì.}
{152}{}{Vidíš unavenou enu. Kontroluje nìco v zápisníku a rozhlíí se kolem, jakoby na nìco zapomnìla.}
{153}{}{Naplòuje injekèní støíkaèku a nìco si pro sebe mumlá.}

# FLOAT
# (COMPANION = MYRON)
{154}{}{Dobrı den, pane Myrone.}
{155}{}{Myrone...pane, máte chvilku...?}
{156}{}{Nevíte náhodou, kdy dorazí další otroci, pane Myrone?}
{157}{}{Myrone...pane, tyhle nové vısledky jsou slibující...}
{158}{}{Myrone? Máte chvíli èas, pane?}
# (NORMAL)
{159}{}{Kde je sakra Myron...}
{160}{}{Pøiveïte Myrona. Tohle musí vidìt.}
{161}{}{Kdyby tak ti otroci dreli hubu...}
{162}{}{Kde jen je ta støíkaèka...}
{163}{}{Nevidìl nìkdo Subjekt 31. Byl tady ještì pøed chvilièkou.}
{164}{}{Musíme vyzkoušet Jet Beta na dalších otrocích.}
{165}{}{Vısledky testu Jet Beta jsou slibující, ale...}
{166}{}{"Létání" vydrí patnáct minut a hodinu. ... øeknìme dávku na hodinu... hmmmmnnn.}
{167}{}{Subjekt 12 stále krvácí z plic...}
{168}{}{To u je popáté, co mìl Subjekt 12 záchvat...zvyšte dávku, uvidíme, co se stane...}
{169}{}{No, take JAKÉ halucinace mìl?}
{170}{}{Zkontrolujte mu tep. Jestli je v tolerované mezi, zvyšte dávku.}
{171}{}{Proè se ta otrokynì v kontrolní skupinì zabila? Vdy jsme na ní nic nezkoušeli!}

# CLICK
# (COMPANION = MYRON)
{200}{}{Testy probíhají podle rozvrhu, pane Myrone.}
{201}{}{Ten novı druh Jetu vzbuzuje extrémní závislost. Otroci by se pro nìj zabíjeli navzájem.}
{202}{}{Otroci radìji berou Jet, ne jedí, tak je to silné.}
{203}{}{Kdo jsou ti lidé s vámi, pane Myrone? Nové subjekty pro testy?}
{204}{}{Tøetí testovací skupina zatím vypadá nejlépe, pane Myrone.}
{205}{}{Pane Myrone, myslím, e by další skupina mìla obsahovat alespoò tøi dìti.}
{206}{}{Myrone, pane, Subjekt 46 mìl infarkt. Omezili jsme dávky na šest dennì.}
{207}{}{Myrone? Potøebujeme novou zásobu injekèních støíkaèek z Vault City. U nemùeme stále pouívat jedny a ty samé.}
{208}{}{Myron, koneènì! Nevíte, kdy koneènì pøijdou další otroci, pane?}
{209}{}{Myrone, pane, pøesunuli jsme tøi otroky z kontrolní skupiny do testovací skupiny kvùli tìm respiraèním selháním minulı tıden.}
{210}{}{Pane Myrone...museli jsme zastøelit jednoho otroka na útìku. Potøebujeme náhradu.}
{211}{}{Pane Myrone...ten novı halucinogen, kterı jste vyvinul, je slibnı. Ale nevzniká na nìj taková závislost jako na Jet...}
# NORMAL
{212}{}{Jestli máte nìjaké návrhy, napište je na papír a pak vyhoïte támhle do koše.}
{213}{}{Ano, ano. Co je?}
{214}{}{Nebudeme mít ádné vısledky, kdy nás bude poøád nìkdo otravovat.}
{215}{}{Dneska tady pouštìjí kadého, bude tøeba s tím nìco udìlat...}
{216}{}{Co chcete?}
{217}{}{Promiòte, *já* mám práci.}
{218}{}{Jestli máte nìjaké otázky, ptejte se strácù, ne mì.}
{219}{}{Ano, je mi jasné, e to, co potøebujete, je *velice* dùleité, ale já mám svou vlastní práci a povinnosti.}
{220}{}{Máte povolení tady bıt?}
{221}{}{Kdo vásse m pustil?}
{222}{}{A se Myron dozví, e nám tady lezou cizinci...}
{223}{}{Máte ty vısledky testu AX 4... ops, promiòte. Spletl jsem si vás s technikem.}
{224}{}{Nemám teï èas si povídat, sorry.}
{225}{}{Potøebujeme novou dávku otrokù...tìmhle u dochází síla.}