#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
{100}{}{Vidíš...Sheba.}

{150}{}{Vidíš vychrtlého mue obleèeného v jasnì modrém obleèení. Jako by jeho obleèení dost neupoutávalo, øve z plnıch plic.}

{200}{}{Krásky, krásky, KRÁSKY!}
{201}{}{Pojïte sem, milovníci krásy! Naše krasavice na vás èekají.}
{202}{}{Dneska máme v Koèièí Pacce polovièní slevy! Skoro zadarmo! A se picnem!}
{203}{}{Dejte nám monost, a vám nabídneme naše krásky!}
{204}{}{Máme bílé krásky, èerné krásky, jiní krásky, severní krásky...}
{205}{}{Máme havé krasavice, ledové krasavice, èerstvé krasavice, máme...::snfff::...*voòavé* krasavice...}
{206}{}{Máme divošské krásky, mutantí krásky, škorpióní krásky, robotí krásky.}
{207}{}{Máme dokonce krásky i pro krávy, ghouly a krásky pro deathclavy.}
{208}{}{No tak, nechcete krásku? Pojïte, milovníci krásy!}
{209}{}{Jestli takovou nemáme, tak takovou ani nechcete! Pojïte, milovníci krásy!}
{210}{}{Pozor, milovníci krásy! Vyuijte mimoøádné slevy!}
{211}{}{Vemte si jednu, a druhou dostanete se slevou!}
{212}{}{Levnìji ne u nás krásu neseenete. A pokud snad ano, kvalita je hrozná!}
{213}{}{Pojïte k nám obdivovat krásu našich krásek!}
