#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
# QUICK LOOK
{100}{}{Vidíš nemocného otroka.}
{101}{}{Vidíš nadrogovaného otroka.}
{102}{}{Vidíš otroka.}

# EXAMINES
# 1. [SICKLY MALE SLAVE]
{150}{}{Vidíš znièenì vyhlíejícího mue. Jeho oèi poletují po okolí, jakoby sledovaly nìjakou neviditelnou mouchu.}
{151}{}{Vidíš nemocného otroka. Je strachy témìø mrtvı. Jeho oèi se na tebe nedokáí zaostøit.}
{152}{}{Vidíš nemocného otroka. Jeho obleèení je v cárech, kùe na nìm visí, jakoby ji mìl o èíslo vìtší.}
{153}{}{Vidíš nemocného otroka. Zbìsile kašle. Jeho košile je pokrytá krvavımi fleky.}
{154}{}{Vidíš nemocného otroka. Jde od nìj silnı zápach moèi a fekálií.}
{155}{}{Vidíš nemocného otroka. Má vypadlé zuby a oèi podlité krví.}
{156}{}{Vidíš nemocného otroka. Jeho tváø pokrıvá nìjaká vyráka, take se neustále škrábe.}
# 2. [SICKLY FEMALE SLAVE]
{160}{}{Vidíš znièenì vyhlíejí enu. Zírá na zemi pøed sebou, jakoby mìla strach zvednout pohled.}
{161}{}{Vidíš nemocnou otrokyni. Je strachy témìø mrtvá. Její oèi se na tebe nedokáí zaostøit.}
{162}{}{Vidíš nemocnou otrokyni. Po tváøi jí pobíhá hmyz, ale ona tomu vùbec nevìnuje pozornost.}
{163}{}{Vidíš nemocnou otrokyni. Její obleèení je v cárech, kùe na ní visí, jakoby ji mìla o èíslo vìtší.}
{164}{}{Vidíš nemocnou otrokyni. Pøi dıchání chrèí a z nosu jí vytéká hlen.}
{165}{}{Vidíš nemocnou otrokyni. Jde od ní silnı zápach moèi a fekálií.}
{166}{}{Vidíš nemocnou otrokyni. Její tváø pokrıvá nìjaká vyráka, take se neustále škrábe.}
{167}{}{Vidíš nemocnou otrokyni. Vypadá jakoby plakala, ale z oèí jí nevycházejí ádné slzy. }
# 3. [MALE SLAVE, DRUGGED]
{170}{}{Vidíš ospale vyhlíejícího mue. Zírá pøímo pøed sebe s nepøítomnım vırazem na tváøi.}
{171}{}{Vidíš zfetovaného otroka. Jeho oèi poletují po okolí, ani na chvíli nezaostøuje pohled..}
{172}{}{Vidíš zfetovaného otroka. Právì se kousnul do ruky a strhl si z ní kus kùe. Pomalu vıká. }
{173}{}{Vidíš zfetovaného otroka. Má na tváøi lehkı úsmìv, ale oèi má kalné a bez vırazu.}
{174}{}{Vidíš zfetovaného otroka. Zírá na zem, z koutku úst mu vytékají sliny. }
{175}{}{Vidíš zfetovaného otroka. Kdy zpozoroval tvùj pohled, mrknul a bolestnì se usmál.}
# 4. [DRUGGED FEMALE SLAVE]
{180}{}{Vidíš chvìjící se enu. Zírá na zem, jakoby mìla strach, e zmizí, pokud pøestane.}
{181}{}{Vidíš zfetovanou otrokyni. Nìco si pro sebe mumlá a olizuje si krev z rozkousanıch rtù.}
{182}{}{Vidíš zfetovanou otrokyni. Na pai má stopy po pneumatice, pøekryté èerstvımi škrábanci.}
{183}{}{Vidíš zfetovanou otrokyni. Rychle pomrkává, jakoby jí nìco spadlo do oka.}
{184}{}{Vidíš zfetovanou otrokyni. Škrábe se na zádech tak zbìsile, e jí na prstech zùstávají kousky kùe a krev.}
{185}{}{Vidíš zfetovanou otrokyni. Košili má pokrytou zvratky a celá páchne jakoby po terpentınu.}
# 5. [MALE SLAVE, BEATEN]
{190}{}{Vidíš hubeného mue. Je pokrytı stopami po bièi. Zírá prázdnì do zemì. }
{191}{}{Vidíš zmláceného otroka.}
{192}{}{Vidíš hubeného otroka. Je pokrytı stopami po bièi. Zírá prázdnì do zemì. }
# 6. [DRUGGED FEMALE SLAVE]
{195}{}{Vidíš chvìjící se enu. Mezi cáry obleèení jsou jasnì viditelné èerstvé stopy po bièi. }
{196}{}{Vidíš otrokyni.}
{197}{}{Vidíš otrokyni. Lehce se chvìje. Celé tìlo má pokryté šlehanci po bièi.}

# FLOAT:
# 7. [SICKLY SLAVE]
{200}{}{::Snnnffff::}
{201}{}{::Huhhhhk::}
{202}{}{::Kašle::}
{203}{}{::Škrábe se.::}
{204}{}{::Odhání mouchy::}
# 8. [DRUGGED SLAVE]
{210}{}{::Snnnffff::}
{211}{}{*Polk*}
{212}{}{Heeeeeeee}
{213}{}{Hee heeeee hee...hee...}
{214}{}{EeeeEEEEeeeeEEEE}

# CLICK:
# 9. [SICKLY SLAVE]
{220}{}{::Zírá na tebe::}
{221}{}{::Bezhlesnì pláèe::}
{222}{}{::Vystrašenì po tobì pokukuje::}
{223}{}{::Divoce mrká::}
{224}{}{::Divoce kašle::}
{225}{}{::Mumlá nìco, èemu nerozumíš.::}
{226}{}{Hnnnnh....hnnn}
{227}{}{::Utírá si nos::}
{228}{}{Hunnnnnh}
{229}{}{Rrrurrr..rr..::kašle::}
# 10. [DRUGGED SLAVE]
{240}{}{::Tøe si oèi::}
{241}{}{::Chrochtá jako prase::}
{242}{}{::Škrábe se na krku::}
{243}{}{Hee heeeee hee...hee...}
{244}{}{Cinky linky }
{245}{}{Fù-fùùùùùùùùùù}
{246}{}{EeeeEEEEeeeeEEEE}
{247}{}{Moje oèi jsou velké èerné mouchy}
{248}{}{Bùby bù}
{249}{}{Hùù Hùù}
{250}{}{Mùùùù}
{251}{}{Dobøe špatnì dobøe špatnì dobøe špatnì}
{252}{}{Ještì!}
# 11. [BEATEN SLAVE vs. SLAVER]
{260}{}{Ano, u mám vlastníka. Mùj majitel má doklady.}
{261}{}{Nechte mì prosím bıt, patøím nìkomu jinému.}
{262}{}{Prosím vás: hledám dvì dìti, s èernımi vlasy...? Vzali je jiní otrokáøi pøed dvìmi léty a prodali na sever.}
{263}{}{Prosím...mám zakázáno s kımkoli mluvit.}
{264}{}{Prosím...nechte mì bıt. Mùj majitel se za chvíli vrátí.}
{265}{}{Jestli mì mùj majitel chytí, zmlátí mì.}
{266}{}{Já u mám paní. Nebude ráda, kdy se mnou budete mluvit.}
{267}{}{Nemùu s vámi mluvit. Mám své povinnosti.}
{268}{}{Jestli mì nìkdo uvidí, jak se s vámi vybavuju, dají mì na testování drog.}
{269}{}{Prosím odejdìte, pane otrokáø. Nechci mít problémy.}
{270}{}{Utéct? Já se nikdy nepokouším utéct. Neodváím se nesplnit pøíkazy svého pána.}
# 12. [BEATEN AND/OR GENERIC SLAVE]
{280}{}{Jestli mì nìkdo uvidí, jak se s vámi vybavuju, dají mì na testování drog.}
{281}{}{Pracovával jsem s jinım otrokem, ale umøel na pøedávkování pøed pár dny.}
{282}{}{Zkoušejí na nás nové drogy. Nìkteré jsou jedovaté. }
{283}{}{Mùj pán je ne mì hodnı.}
{284}{}{Mùj pán mi zakázal mluvit s cizími lidmi.}
{285}{}{Prosím...nemám dovoleno bavit se s vámi.}
{286}{}{Prosím, nechte mì bıt. Mùj pán se brzy vrátí.}
{287}{}{Jestli mì mùj pán chytne, jak se s vámi bavím, zbije mì.}
{288}{}{Mùj pán je hodnı. Bije mì jenom obèas.}
{289}{}{Rodina mi nechybí. Mùj pán je hodnı.}
{290}{}{Jsem z domorodé vesnice ze severu. Tady je ivot lepší.}
{291}{}{Chytili mì v Denu.}
{292}{}{Nemohu s vámi mluvit. Mám práci.}
{293}{}{Musím dokonèit svou práci, ne se vrátí mùj pán.}
{294}{}{Mluvení je proti pravidlùm.}
{295}{}{Prosím, jdìte pryè. Prosím vás. Dostanete mì do problémù.}
{296}{}{Utéct? Není KAM utéct. Pouš je plná pøíšernıch nestvùr, které by mì seraly za iva.}
{297}{}{Otroci, kteøí onemocní, jsou vìtšinou zabiti.}
{298}{}{Byl jsem jeden z mála otrokù, kteøí pøeili cestu do New Rena. Ostatní onemocnìli bìhem cesty, tak je otrokáøi zastøelili.}
{299}{}{Ano? Jak vám mohu pomoci?}
{300}{}{Slyšel jsem nìco o podzemní eleznici, ale nevím o nikom, kdo by tam byl.}
{301}{}{Julie utekla, ale chytili ji další den v Golgotì. Pøivázali ji na kùl a nechali ji umøít hlady.}
{302}{}{Otroci, kteøí uteèou, jsou chyceni a necháni na smrt v Golgotì.}
{303}{}{Ne, nevím, kde je má rodina teï. Poøád na nì obèas myslím, ale u ne tak èasto jako døíve.}
{304}{}{New Reno je...no, není tak špatné jako Den. V nìkterıch vìcech.}
{305}{}{::Vystrašenì se otáèí.::}
{306}{}{::Ignoruje tì, asi má strach.::}
{307}{}{Jakmile se nauèíš, co od tebe tvùj pán oèekává, bití u není tak èasté.}
{308}{}{Zajali mì u strašnì dávno. U si to skoro nepamatuju.}
{309}{}{Mám dvì dìti, ale odvezli je na sever. Doufám, e dopadli lépe ne já.}
{310}{}{Promiòte, ale nemám èas se bavit.}
{311}{}{Mùj pán se na mì v poslední dobì zlobí. Øekl, e mì prodá do stájí, jestli se nepolepším. }
{312}{}{Otroci, kteøí uteèou jsou rychle zase chyceni. Nechají je zemøít na Golgotì, nebo je pošlou do stájí na nìjaké testování. }
