#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
#poznámka pro Somnambula nebo jiného kontrolora: 
# nevím, co pøesnì znamenají fráze Ber èernou a Ber bílou - jedna
# z nich je ano a druhá ne, ale která ? (nejspíš night je ne, ale co já vím)
# nemám monost nahodit teï fallouta a vyzkoušet, co pøesnì udìlají, take je to na tobì

# 0. QUICK LOOK (NORMAL)
{100}{}{Vidíš vıherní automat.}
# 1. QUICK LOOK (HIGH-ROLLER)
{101}{}{Vidíš tøpytící se vıherní automat.}

# 0. LOOK (NORMAL)
{150}{}{Vidíš vıherní automat. Máš pocit, jakoby se na tebe koutkem oka díval.}
{151}{}{Vidíš vıherní automat. Lesklı pláš a zlatá páka lákavì záøí odlesky svìtel Nového Rena.}
{152}{}{Vidíš tøpytící se vıherní automat. Je urèenı pro gamblery vyšší tøídy. Minimální sázka je }
{153}{}{.}
{154}{}{Vidíš tøpytící se vıherní automat.}

# 2. FLOAT DIALOGUE (PLAYER = DRUNK OR HIGH) (WTG)
{160}{}{*Pojï sem a zahrej si se mnou na chvilku, kovboji.*}
{161}{}{*Zdárec, námoøníku. Nechceš si zahrát?*}
{162}{}{*Strè doláè dovnitø a zatáhni za páku. Uvidíš, bude se ti to líbit.*}
{163}{}{*Tik...Tik...Tiiiiik...*}
{164}{}{*No ahoj, nádherná neznámá. Nechceš si na chvíli zahrát?*}
{165}{}{*Ahoj, krásko. Co takhle trochu risku a vzrušení?*}
{166}{}{*No jestlipak ty nejsi nádherná. Co takhle pøistoupit blí a trochu si zahrát?*}

# 3. FLOAT DIALOGUE (NORMAL) (WTG)
{175}{}{*Cing*}
{176}{}{*Bing*}
{177}{}{*Tá-cink*}
{178}{}{*Zzzzzzz*}
{179}{}{*Ring-ling*}
{180}{}{*Dingity-ding*}

# 4. RETARD (WTG)
{185}{}{Vidíš divnou zlatou bednu se tøemi oèima a jednou rukou. Urèitì je to jedna z nejhezèích vìcí, jaké existují.}
{186}{}{Ja }
{187}{}{ gdoty}
{188}{}{Ja chci MÁMU. }
{189}{}{ chceš ARR-YO. Ja chceš domù}
{190}{}{Potøes mu rukou}
{191}{}{ty jeden divnej mutant}
{192}{}{Velebte Vault! Velebte Vault!}
{193}{}{Ty vodní èip?}
{194}{}{Odejdi se, podíváš se na další svítící zlaté vìci.}
{195}{}{Odejdi.}

# 5.  RETARD TALKS TO SLOT MACHINE (4, 5)
{205}{}{Podivná hezká zlatá skøínka se tøema oèima a jednou rukou ti neodpovídá.}
{206}{}{JÁ }
{207}{}{ ODPOVÌZ}
{208}{}{Potøes jí rukou}
{209}{}{Já dítì vot Zakládatél a ty mluvíš k já HNED}
{210}{}{ty divná mutant}
{211}{}{Ty vodná èip?}
{212}{}{Odejdi se, podíváš se na další svítící zlaté vìci.}
{213}{}{Odejdi.}

# 6.  RETARD PULLS HANDLE (4, 5)
{220}{}{Dríš ruku divné krabice a vøele jí potøásáš. Slyšíš nìjaké *bzzzzzzz,* a krabice mluví! Øíká "Prosím...vlote...peníze."}
{221}{}{Aighhhhh! Robot! Robot! Uteèeš!}
{222}{}{Odejdi.}

# 7.  NO MONEY (WTG, 9)
{225}{}{Nemáš dost penìz na hraní na automatu. Proklínáš svou chudobu...Moná jindy...}
{226}{}{Odejdi.}

# 8.  PLAY. . . ? (WTG, 14, 15)
{230}{}{Vidíš vıherní automat. Lesklı pláš a zlatá páka lákavì záøí odlesky svìtel Nového Rena. Slot na mince na tebe pøátelsky kıve. Cítíš, e ti tváøe rudnou v pøedtuše jasné vıhry.}
{231}{}{(Ruka se ti tøepe, jak šaháš do kapsy pro peníze. Stroj ti stále nìco šeptá.)  *Tak pojï, drahoušku...tak je to správné...pojï...neostıchej se...*}
{232}{}{(Ruka se ti tøepe, jak šaháš do kapsy pro peníze. Stroj ti stále nìco šeptá.) *Pojï, miláèku...správnì, pojï..popadni tu páku...poøádnì ji stiskni...no tak, pojï...*}
{233}{}{Máš }
{234}{}{ dolarù. Riskovat všechny?}
{235}{}{Máš  }
{236}{}{ dolarù. Vsadit }
{237}{}{ dolarù?}
{238}{}{Vsadit }
{239}{}{ dolarù}
{240}{}{Ber èernou.}
{241}{}{Ber bílou.}

# 9.  LOOOOOOSER (8)
{245}{}{Kola se toèí, toèí, toèí a... nic.}
{246}{}{NIC! NIC! Slyšíš jak se ti smìje...Vyhazovaèi musí odtrhávat tvé øvoucí tìlo z automatu.}
{247}{}{(Stroj se šklebí) *Tak, vydìlal jsem. Sorry zlatíèko, byznys je byznys. Dej si pozor, a nezakopneš, a pùjdeš pryè.Ha ha ha ha ha ha.*}
{248}{}{Zbıvá ti }
{249}{}{ dolarù. Kašlat na ztráty a hrát dál??}
{250}{}{Zbıvá ti  }
{251}{}{ dolarù. Riskovat všechny?}
{252}{}{Jsi na mizinì. Musíš vzít èernou.}
{253}{}{Jsi na mizinì. Musíš vít bílou.}
{254}{}{Ber èernou.}
{255}{}{Ber bílou.}

# 10.  WIN x1 (8)
{260}{}{Tøi dıky. ádná vıhra, ádná prohra.}
{261}{}{(Stroj ti dál šeptá.) *Tak pojï, drahoušku...kadému se to podaøí alespoò jednou...zkus to znovu...prosím...*}
{262}{}{(Stroj ti dál šeptá.) *Tak pojï, drahoušku...zkus to znovu...popadni tu páku...pevnì ji sevøi...tak pojï...*}
{263}{}{Stále ještì máš }
{264}{}{ dolarù. Hrajeme dál?}
{265}{}{Máš }
{266}{}{ dolarù. Hrajeme dál?}
{267}{}{Ber èernou.}
{268}{}{Ber bílou.}

# 11.  WIN x2 (8)
{275}{}{Tøi Kulky! Vyhráváš dvojnásobek!}
{276}{}{(Stroj se otøásl rozkoší.) *To je ono, drahouši...tahej dál za páku...rychleji, rychleji, tvrdìji...tak pojï...*}
{277}{}{(Stroj se otøásl rozkoší.) *To je ono, cukroušku...tahej dál...rychleji, rychleji, tvrdìji...tak pojï...*}
{278}{}{Máš  }
{279}{}{ dolarù! Hrajeme dál?}
{280}{}{Ber èernou.}
{281}{}{Ber bílou.}

# 12.  WIN x3 (8)
{290}{}{Tøi Granáty! Zatracenì! Máš trojnásobek!}
{291}{}{(Stroj zapištìl rozkoší a okolím se rozléhá hlasité cinkání mincí.) *Aieeeeeeee! To je ono, TO JE ONO! Oh ano, ano ano!!! Znovu! Rychleji! Silnìji! Na co èekáš?! Znovu!*}
{292}{}{(Stroj radostnì zabruèel a okolím se rozléhá hlasité cinkání mincí.) *Ennnnghhhh! To je ono! A pøíštì znovu! Dìlej, zkoušej to dál! Rychleji, silnìji! No tak, na co èekáš...*}
{293}{}{Zatancuj si tanec vítìzství, párkrát vyhoï nohama do vzduchu, pak se zhluboka nadechni a hrej dál.}
{294}{}{Tak granáty, pojïte! Potøebuju penízky na rotaèní kulomet! (Hrej dál.)}
{295}{}{Máš  }
{296}{}{ dolarù. Hrát dál?}
{297}{}{Ber èernou.}
{298}{}{Ber bílou.}

# 13. DRUNK, HIGH OR OTHERWISE FUCKED UP (WTG)
{305}{}{(Vidíš vıherní automat. Jeho lesklá skøíò a pozlacená páka lákavì záøí odraenımi svìtly Nového Rena. Slot na mince na tebe pøátelsky kıve. Cítíš, e ti tváøe rudnou v pøedtuše jasné vıhry. Tøi okınka na tebe mrkly. Ze slotu na mince se ozıvá lehce chraptivı hlas.)* Uau! Teda ty jsi ale kus chlapa. Nazdárek! Nechceš se pobavit? *}
{306}{}{(Vidíš vıherní automat. Jeho robustní skøíò a pozlacená páka záøí jako bùh slunce. Slot na mince na tebe pøátelsky kıve. Cítíš, e ti tváøe rudnou v pøedtuše jasné vıhry. Tøi okınka na tebe mrkly. Ze slotu na mince se ozıvá drsnı muskı hlas.) *Tak hezké dìvèe u jsem dlouho nevidìl, sleèno. Nechcete se se mnou trochu pobavit?*}
{307}{}{::Štípni se::}
{308}{}{Uh...ahoj?}
{309}{}{::Zhluboka se nadechni a pomalu odejdi pryè.::}

# 14. DRUNK CONVERSATION 1 (13)
{315}{}{*Jsem stále tady, krásná dámo.* (Automat ztišil hlas.) *No tak, nechcete si vsadit?*}
{316}{}{*Jsem poøád tady, zlatíèko.* (Automat ztišil hlas.) *Ty jsi ale hezkej chlapec, víš o tom? Tak pojï, nechceš do mnì vrazit...pár dolárkù?*}
{317}{}{Kdó sssešš?}
{318}{}{Jasssná p-páka! Ssádim si}
{319}{}{Myslím e bude lepší odejít, ne do tebe vrazím nìco jiného.}
{320}{}{::Zhluboka se nadechni a odejdi.::}

# 15. DRUNK 2 (14)
{325}{}{*Jsem ideální mu.* (Automat na tebe mrknul.) *Dej mi pár drobnıch, a já tì tak uspokojím, jak ti to ještì ádnı chlap neudìlal.*}
{326}{}{*jsem dokonalá ena, chlapèe. Chci od tebe jenom trochu pozornosti. Nepomùeš mi? No tak, dolárek dva?*}
{327}{}{Nem-nemhùeme si enom tak pokesat}
{328}{}{Jasssná p-páka! Ssádim si}
{329}{}{Myslím e bude lepší odejít, ne do tebe vrazím nìco jiného.}
{330}{}{::Zhluboka se nadechni a odejdi.::}

# 16. DRUNK 3 (15)
{335}{}{*Jasnì e mùeme, srdíèko, jasnì.* (Automat vypadá sympaticky.) *Co trápí tvou roztomilou hlavièku?*}
{336}{}{*Jasnì e mùeme, srdíèko, jasnì.* (Automat vypadá sympaticky.) *Co tì trápí, hezoune?*}
{337}{}{Já chybíš MÁMA a ARROYO a já ...nemueš GECK najdeš a ...*smrk*}
{338}{}{Já chceš Mámu a  Arroyo znièenej a ja...nevíš kde oni všechno oni pryš já chceš oni kde oni kde?...a...*smrk*}
{339}{}{já chceš oprvit loï velkaja ...a nevíš JAK ... a mo-moje máma PRYÈ a...*smrk*}
{340}{}{Hra ssskonèilla...a já teïsse jenom flákáš a...mám strach e je konec a...*smrk*}
{341}{}{Ále ten blllbej ej F-F-Fhalout nechce brát mojji novej trzi-tøi tøi dé kartu a já za ni tolik penez a *smrk*}
{342}{}{Chci porzádního postavu ale si sem to podupal èe sem dáváš blbì body a teï mám místo hrdiny akorát hovno...a'...*smrk*}
{343}{}{bavím ssse zzzzzz vyhernim avtomatem - sákra já u mám dost}
{344}{}{::Zhluboka se nadechni a odejdi.::}

# 17. DRUNK 4 (16)
{350}{}{*No tak, no tak...u si s tím netrap svoji milou hlavièku a nechej mì, a se o všechno postarám. No tak, klidnì se o mì opøi. Tak, tak, jen to ze sebe všechno dostaò.*}
{351}{}{*No tak, no tak...u se s tím netrap, chlapeèku a nechej mì, a se o všechno postarám. No tak, klidnì se o mì opøi. Tak, tak, jen to ze sebe všechno dostaò.*}
{352}{}{Díky, automate *smrk* ty seš tak hodnej}
{353}{}{Ty seš jedinej, kdo je na mnì hod-hodennej. Šici ostatní mi chtìjí jenom ubliovat *smrk* a zabít a vzít mi peníze a ...*béééé*}
{354}{}{::Zhluboka se nadechni a odejdi.::}

# 18. DRUNK 5 (17)
{360}{}{(Opíráš se o automat.)}
{361}{}{*Budeš v poøádku, zlatíèko? Nechci tì nìkam pouštìt v takovém stavu.*}
{362}{}{*Budeš v poøádku, zlatíèko? Nechci tì nìkam pouštìt v takovém stavu.*}
{363}{}{budu okej...díkess es se mnou pokecal, automate, milhuju thì}

# 19. DRUNK 6 (18)
{370}{}{(Vypadá to, jakoby se na jednom okınku vytváøela slza.)}
{371}{}{*Ty jsi jediná hrdinka, kterou máme v tomhle dvou bitovém svìtì plném bastardù a zlodìjù, }
{372}{}{. Dávej si na sebe pozor, dobøe, holèièko?* (Obrací se.) *Radši jdi, ne se pøestanu chovat jako chlap a rozbreèím se jako baba.*}
{373}{}{*Ty jsi jedinı hrdina, kterou máme v tomhle dvou bitovém svìtì plném bastardù a zlodìjù, }
{374}{}{. Tak...Tak...si na sebe dávej pozor, dobøe, hochu?* (Obrací se .) *Radši jdi, ne se rozbreèím.*}
{375}{}{Ahoj}

# 20.  PLAY, HIGH-ROLLING MACHINE. . . ? (WTG, 14, 15, 21, 22, 23, 24)
{380}{}{Vidíš vysokosázkovı vıherní automat  - minimální sázka je }
{381}{}{ dolarù.  Lesklı pláš a zlatá páka lákavì záøí odlesky svìtel Nového Rena. Slot na mince na tebe pøátelsky kıve. Cítíš, e ti tváøe rudnou v pøedtuše jasné vıhry.}
{382}{}{(Ruka se ti tøepe, jak šaháš do kapsy pro peníze. Stroj ti stále nìco šeptá.)  *Tak pojï, drahoušku...tak je to správné...pojï...neostıchej se...*}
{383}{}{(Ruka se ti tøepe, jak šaháš do kapsy pro peníze. Stroj ti stále nìco šeptá.) *Pojï, miláèku...správnì, pojï..popadni tu páku...poøádnì ji stiskni...no tak, pojï...*}
{384}{}{Zbıvá ti }
{385}{}{ dolarù. Riskovat všechny?}
{386}{}{Máš }
{387}{}{ dolarù. Vsadit }
{388}{}{ dolarù?}
{389}{}{Vsadit }
{390}{}{ dolarù?}
{391}{}{Ber èernou.}
{392}{}{Ber bílou.}

# 21.  LOOOOOOSER, HIGH-ROLLING (20)
{400}{}{Kola se toèí, toèí, toèí a... nic.}
{401}{}{NIC! NIC! Slyšíš jak se ti smìje...Vyhazovaèi musí odtrhávat tvé øvoucí tìlo z automatu.}
{402}{}{(Stroj se šklebí) *Tak, vydìlal jsem. Sorry zlatíèko, byznys je byznys. Dej si pozor, a nezakopneš, a pùjdeš pryè.Ha ha ha ha ha ha.*}
{403}{}{Zbıvá ti }
{404}{}{ dolarù. Nahradit ztráty a hrát dál?}
{405}{}{Zbıvá ti }
{406}{}{ dolarù. Vsadit všechny?}
{407}{}{U si nemùeš dovolit hrát dál. Musíš vzít èernou.}
{408}{}{U si nemùeš dovolit hrát dál. Musíš vzít bílou.}
{409}{}{Ber èernou.}
{410}{}{Ber bílou.}

# 22.  WIN x1, HIGH-ROLLING (20)
{415}{}{Tøi bomby. ádná vıhra, ádná prohra.}
{416}{}{(Stroj ti dál šeptá.) *Tak pojï, drahoušku...kadému se to podaøí alespoò jednou...zkus to znovu...prosím...*}
{417}{}{(Stroj ti dál šeptá.) *Tak pojï, drahoušku...zkus to znovu...popadni tu páku...pevnì ji sevøi...tak pojï...*}
{418}{}{Stále ještì máš }
{419}{}{ dolarù. Hrajeme dál?}
{420}{}{Ber èernou.}
{421}{}{Ber bílou.}

# 23.  WIN x2, HIGH-ROLLING (20)
{425}{}{Tøi Atomovky! Vyhráváš dvojnásobek!}
{426}{}{(Stroj se otøásl rozkoší.) *To je ono, drahouši...tahej dál za páku...rychleji, rychleji, tvrdìji...tak pojï...*}
{427}{}{(Stroj se otøásl rozkoší.) *To je ono, cukroušku...tahej dál...rychleji, rychleji, tvrdìji...tak pojï...*}
{428}{}{Máš teï }
{429}{}{ dolarù! Hrát dál?}
{430}{}{Ber èernou.}
{431}{}{Ber bílou.}

# 24.  WIN x3, HIGH-ROLLING (8)
{435}{}{Tøikrát Hirošima! Vyhráváš trojnásobek!}
{436}{}{(Stroj zapištìl rozkoší a okolím se rozléhá hlasité cinkání mincí.) *Aieeeeeeee! To je ono, TO JE ONO! Oh ano, ano ano!!! Znovu! Rychleji! Silnìji! Na co èekáš?! Znovu!*}
{437}{}{(Stroj radostnì zabruèel a okolím se rozléhá hlasité cinkání mincí.) *Ennnnghhhh! To je ono! A pøíštì znovu! Dìlej, zkoušej to dál! Rychleji, silnìji! No tak, na co èekáš...*}
{438}{}{Zatancuj si tanec vítìzství, párkrát vyhoï nohama do vzduchu, pak se zhluboka nadechni a hrej dál.}
{439}{}{Tak hirošimky, pojïte! Potøebuju penízky na rotaèní kulomet! (Hrej dál.)}
{440}{}{Máš teï  }
{441}{}{ dolarù. Hrát dál?}
{442}{}{Ber èernou.}
{443}{}{Ber bílou.}

# use gambling skill on table, the +1 is for high roller tables
# critical failures
{1000}{}{Šance nevypadá to moc dobøe.}
{1001}{}{šance vypadá to docela dobøe.}
# failures
{1005}{}{Nedokáeš šance jistì odhadnout.}
{1006}{}{Vypadá to docela nadìjnì.}
# success
{1010}{}{Šance vypadá dobøe.}
{1011}{}{Mmm, to nevypadá dobøe. Vypadá to docela špatnì.}
# critical success
{1015}{}{Urèitì! Jasnáı vıhra!}
{1016}{}{Moc dobøe to nevypadá. Oprava, vypadá to velice špatnì.}
