#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
# 0. QUICK LOOK
{100}{}{Vidíš docela hezkého èernocha... eeh, ne, poèkat. Vidíš T-Raye. }

# 0. LOOK
{150}{}{Vidíš svalnatého èernocha se silnımi brılemi a lehkou bradkou.}
{151}{}{Vidíš T-Raye. V tìch dínech vypadá fakt dobøe.}
{152}{}{Vidíš T-Ray. Protahuje si bicepsy a mumlá si pro sebe nìco jako "daprdele doprdle".}
{153}{}{Skoro T-Raye pøes ty svaly nemùeš poznat.}

# 1. FLOAT DIALOGUES (ENCLAVE_DESTROYED = TRUE and PLAYER HAD SEX WITH T-RAY) (WTG)
{200}{}{Hej, to není moje chyba, e ta guma, co jsme pouili, mìla v sobì díru.}
{201}{}{UAU! Já to fakt o tobì a o mnì nikomu neøekl! To musel bıt nìkdo jinej!}
{202}{}{ZATRACENÌ, enská. Zachránilas svìt, nechceš teï ještì zachránit i mnì?}

# 2. FLOAT DIALOGUES (ENCLAVE_DESTROYED = TRUE and PLAYER KNOWS T-RAY) (WTG)
{210}{}{Všem jsem øíkal, e ty a já si jsme strašnì blízcí! Ale øíkal jsem to tak, aby to vyznìlo, e ty jsi šéf!}
{211}{}{Máte štìstí, e jsem tu a zachránil vás. Jinak by si vás všechny dali borci z Enklávy k snídani.}
{212}{}{Yo, hrdino. Øíkáš doufám všem, jakı jsem tvùj dobrı kámoš!}

# 3. FLOAT DIALOGUES (ENCLAVE_DESTROYED = TRUE) (WTG)
{220}{}{Všichni do pozoru! Hrdina pøichází!}
{221}{}{Škoda, e sem ti nemohl pomoct s prezidentem. Udìlal bych to rád, staèilo jen øíct.}
{222}{}{Já bych taky šel na Enklávu, ale mìl jsem zrovna moc vìcí na vyøízení.}

# 4. FLOAT DIALOGUES (POWER ARMOR) (WTG)
{230}{}{Kolik koòskejch sil má ta vìc v tobì?}
{231}{}{Hmm. Jak proboha chodíš na záchod s tou vìcí, co máš na sobì?}
{232}{}{Asi mi to brnìní na chvíli nepuèíš, co? Chtìl bych se jenom na nìco podívat.}

# 5. FLOAT (NORMAL)
{250}{}{Hmm, zase mì jde nìkdo otravovat.}
{251}{}{Jo, Impala je fajn kára, ale není to Omni. A Škoda u vùbec ne.}
{252}{}{Hmmm, je to pìknì v háji, budeme to muset vymìnit...}
{253}{}{Zatracenì, tohle auto potøebuje vymìnit chladiè, usadily se v nìm áby.}
{254}{}{Motor ještì fachá docela dobøe.}
{255}{}{Interiér smrdí, jako kdyby tam nìkdo sral.}
{256}{}{Interiér smrdí jako psí prdel.}
{257}{}{Kdo s tím tak jezdil, které hovado?}
{258}{}{Na auto se nesmí spìchat. Kdy se ti nìkde posere, odtahovka se zavolat nedá. }
{259}{}{Moje auto není rychlı, ale moje láska je.}
{260}{}{Ach, jo, mám málo sexu. Bude s tím tøeba nìco udìlat.}
{261}{}{Jsem utahanej jako prase.}
{262}{}{Highwayman má plnì analogovı systém, pøes 800 koòskejch sil, z nuly na sto pod sekundu.}
{263}{}{Rychlej? Highwayman zrychlí z nuly na 100 ani ne za sekundu.}
{264}{}{Highwayman má pøes 800 koòskejch sil.}
{265}{}{Highwayman má plnì analogovı systém. ádné pitomé poèítaèe a tak.}
{266}{}{Highwayman je skvìlı auto, Chryslus je dokázal opravdu dobøe udìlat. I kdy Favorit Mega od Škodovky...}
{267}{}{Dám mu šanci.}
{268}{}{Dám ti šanci.}

# 6. INTRO (WTG)
{275}{}{Kdo jsi? Co chceš?}
{276}{}{Uau! Podívejte se, co to pøišlo?! Hm hm, nìco takovıho jsem naposledy vidìl v pøedváleèném Leu. Co pro tebe mùu udìlat, krásná neznámá?}
{277}{}{Zas ty? A co chceš TEÏ?}
{278}{}{Sakra, enská... zas ty? Co CHCEŠ? Nechci slyšet nic o tom, e jsi v tom...}
{279}{}{}
{280}{}{ jdeš kam }
{281}{}{ jdeš}
{282}{}{Odejdi}
{283}{}{Odkud máš toho Highwaymana? Líbí se mi.}
{284}{}{To auto v garái je moje.}
{285}{}{Ty jsi ten zkurvenec, kterej ukradnul moje auto, zmrde?}
{286}{}{Jsem zástupce pana Bishopa, }
{5286}{}{. Jdu si pro auto.}
{287}{}{Patøím k Bishopovım lidem. Jdu si pro to auto.}
{288}{}{Pøišel jsem pro baterie pana Bishopa.}
{289}{}{Mùete nìco vylepšit na tom Highwaymanovi?}
{290}{}{Máš nìjaké baterie na prodej?}
{291}{}{Nic. Jdu pryè.}

# 7. ME GO WHERE ME GO (6, 17)
{300}{}{Hele, tohle není záchod, a ty tady nemáš co dìlat, chlapeèku, take vypadni. A hned.}
{301}{}{Hele tohle není záchod, a ty tady nemáš co dìlat, holèièko, take vypadni. A hned.}
{302}{}{Chceš JÍT? Tady? Hmm... (Prohlíí si tì.)... chlap musí udìlat, to co musí. Jdeme na to.}
{303}{}{Uh-huh}
{304}{}{Ne ne}
{306}{}{Jdeme na to.}
{307}{}{Mmm, ne díky. Radši ne. Nashle.}

# 8. UH-HUH (7)
{320}{}{Tak dobøe...}
{321}{}{Uh-uh-uh}

# 9. NUH-UH (7, 17, 31, 35)
{330}{}{Aha, tak ty si s T-Rayem jenom hraješ, jo?! No nic, mám lepší èubky, které se o mnì postarají.}
{331}{}{Dóbøe ti tak.}
{333}{}{Hmm, kdy dokáeš psy chytit, dìlej si s nimi, co chceš. Mìj se.}
{334}{}{e pícháš psy mì vùbec nepøekvapuje. Mìj se.}

# 10. I LIKE THAT HIGHWAYMAN IN THE GARAGE (6)
{340}{}{Ten Highwayman? To je JASNİ, e se ti líbí. Je to slaïouèká mašinka, nedávnı pøírùstek... jenom ji trochu opucujeme, pøidáme pár vylepšení a prodáme ji starımu Bishopovi.}
{341}{}{"Vylepšení?" Jaké vylepšení?}
{342}{}{Prodat ji BISHOPOVI? Hele, debile...Bishop je mrt...er, teda, mùu vyrovnat jakoukoli Bishopovu nabídku.}
{343}{}{Prodat ji Bishpovi? Hele, mùu vyrovnat Bishopovu nabídku a pøihodit nìco navíc.}
{344}{}{To je ale náhodièka. Jsem zástupce pana Bishopa.}
{346}{}{Ne ne. Nikomu to auto neprodáš. Je moje.}
{347}{}{Hmm, to zní jako fajn kšeft. Èau.}

# 11. ADJUSTMENTS? WHAT KIND OF ADJUSTMENTS? (10)
{360}{}{Vyèistit motor, uklidit interiér, pøelakovat - a vyhodit z kufru hromadu haraburdí. A skonèíme, prodáme ji za tìké prachy starému Bishopovi.}
{361}{}{Prodat ji Bishpovi? Hele, mùu vyrovnat Bishopovu nabídku a pøihodit nìco navíc.}
{362}{}{To je ale náhodièka. Patøím mezi Bishopovy zástupce: }
{365}{}{Hm, to zní dobøe. Mìj se...}

# 12. I CAN MEET BISHOP'S OFFER (10, 11, 13)
{375}{}{Dorovnáš BISHOPOVU nabídku? To je poøádná hromada penìz, kámo, velká kupa. MOC penìz. Navíc, on je jeden z nejdùleitìjších lidí v Renu, jasnı? Za tohle autíèko si u nìj udìlám dobré oèko.}
{376}{}{Dorovnáš BISHOPOVU nabídku? To je poøádná hromada penìz, enská, velká kupa. MOC penìz. Navíc, on je jeden z nejdùleitìjších lidí v Renu, jasnı? Za tohle autíèko si u nìj udìlám dobré oèko.}
{377}{}{Poslouchám...}
{378}{}{Pomùe ti 1000 babek v rozmıšlení?}
{379}{}{Pomùe ti 750 babek v rozmıšlení?}
{380}{}{Pomùe ti 500 babek v rozmıšlení?}
{381}{}{Vlastnì, teï zrovna nemám dost...}
{382}{}{A co takhle noc se mnou, T-Rayi? K nièemu lepšímu se nedostaneš do konce ivota.}
{383}{}{Moje nabídka zní: Zùstaneš v jednom kuse, kdy mi okamitì vrátíš MOJE auto.}
{384}{}{Nic...sorry, musím jít.}

# 13. THAT'S NOT ENOUGH (12)
{395}{}{Hele, chlape, za to si nekoupím ani novı ponoky, nato abych za to šel proti Bishopovi. }
{396}{}{Hele, enská, za to si nekoupím ani novı ponoky, nato abych za to šel proti Bishopovi.}
{397}{}{Ty si asi myslíš, e auta jsou levnı.}
{398}{}{Tak to zkusme znovu.}
{399}{}{Hmm, hele, teï momentálnì ti nic víc nabídnout nemùu. Poèkej chvíli, seenu víc.}
{401}{}{Ne, ale tvùj ivot je. Zùstaneš v jednom kuse, kdy mi okamitì vrátíš MOJE auto.}
{402}{}{Na takovı kecy teï nemám èas. Sbohem.}

# 14. SLEEP OFFER REJECTED FOR BATTERIES (27, 53)
{420}{}{Ne, díky. Jak se tak na tebe dívám, vùbec by mi nestálo za to.}
{421}{}{Tvoje chyba. Tak uka, co máš. Zaplatím.}
{422}{}{Víš co? U je mi BLBÌ z tebe a tvıch kecù. Nasekám tì na tolik kouskù,
 e si budeš moct otevøít øeznictví, hajzle.}
{423}{}{Tak dobøe. Jdu pryè.}

# 15. SLEEP OFFER REJECTED FOR HIGHWAYMAN (12, 13)
{436}{}{Vyser se teda na vyjednávání. Dej mi MOJE auto zpátky. NEBO...}
{437}{}{Zapomeò na to. Nasekám tì na tolik kouskù, e si budeš moct otevøít øeznictví, hajzle.}

# 16. SLEEP OFFER CONSIDERED (12, 13)
{445}{}{(Jeho oèi se pøivøely. Pohled mu pøejídí po tvém tìle.) Nevím, jestli máš TAKOVOU cenu, enská. To je HIGHWAYMAN, o èem mluvíme...}
{446}{}{Oh, mám takovou cenu. Mnohem vìtší.}

# 17. INTRO SEX DEAL, CONSUMMATED (16)
{455}{}{Hmm, moná jsem blbec, ale... dojednáno. Já si pohraju a ty pak odjedeš Highwaymanem pryè.}
{456}{}{Tak do toho.}
{457}{}{Vyser se na to. Dej mi MOJE auto zpátky. NEBO...}
{458}{}{Rozmyslela jsem si to. Asi tì zabiju, to bude jednodušší.}
{459}{}{Zapomeò na to, jdu pryè.}

# 18. END OF DEAL (12, 13)
{470}{}{Hele, tak proè plıtváš mım èasem? Jestli nemáš prachy, tak se ti tady kšefty nepovedou. Mám na starosti dùleitìjší vìci, ne se vybavovat s takovım debilem.}
{471}{}{Hmm, mám pro tebe návrh: Zùstaneš v jednom kuse, kdy mi okamitì vrátíš MOJE auto.}
{472}{}{Mìl jsi poslední šanci a projel jsi ji. A teï tì zabiju. Jak to chceš?}

# 19. IT'S MY CAR (6, 10, 11, 12, 13, 15, 16, 17, 18)
{485}{}{TVOJE auto? }
{486}{}{Chlape, nemám tušáka, o èem to toèíš.}
{487}{}{enská, nemám tušáka, o èem to toèíš.}
{488}{}{Highwayman byl šrot, leel si tam jenom tak. A teï?  A teï je NÁŠ. Ale jestli se ti na tom nìco NELÍBÍ, mùeme si to hned na místì vysvìtlit...}
{489}{}{Jo, nelíbí se mi to. Tak pojï, debile...}
{490}{}{Co dìláš s tím autem?}
{491}{}{Ne, v pohodì. Klidnì si tu herku nech. Je to kus šrotu. ere moc proudu, smrdí jako brahmíní hovna, kufr je moc malej... ale pro tebe akorát. Èau.}
{492}{}{Ne, nemám nic proti.. zatím. Èau.}

# 20. SMELLS LIKE SHIT ANYWAY . . . (19)
{500}{}{Hej! Momentík! *Kus šrotu? Smrdí jako hovna?* }
{501}{}{Chlape, co to bereš za Jet? }
{502}{}{enská, co to bereš za Jet? }
{503}{}{To je HIGHWAYMAN. Nejenom e funguje, ale a ho upravím, bude vrnìt stejnì jako enská se mnou.}
{504}{}{Je mi z tebe blbì, kriple. Naer se olova, debile...}
{505}{}{Co budeš na autì opravovat?}
{506}{}{No jo. Já mizím.}

# 21. DON'T WANT NO TROUBLE (19)
{520}{}{Jo, pøesnì tohle jsem mìl na mysli. Radši utíkej, ne si o tebe maminka zaène dìlat starosti.}
{521}{}{Ne, ve skuteènosti si dìlá TVOJE maminka starosti, kdy nejsem nablízku, abych ji potìšil.}
{522}{}{Kašli na nìj a jdi potichu pryè.}

# 22. BOUGHT HIGHWAYMAN, STRAIGHT-UP (12)
{530}{}{Dobøe, dobøe. Domluveno. (Rychle si pøepoèítává peníze, pak je schovává do kapsy.) Highwayman je tvùj. Ale nemá ani šávu, ani další pøíslušenství, které jsem tam chtìl pøidat...}
{531}{}{Jaké pøíslušenství jsi tím myslel?}
{532}{}{U je mi z tebe blbì. Naer se olova, debile...}
{533}{}{Oh, u jsi mi toho dal TOLIK. Mizím.}

# 23. SEX FOR HIGHWAYMAN (7)
{540}{}{(T-Ray si utírá pot.) Uau, enská. Fajn, Highwayman je tvùj. Ale nemá ani šávu, ani další pøíslušenství, které jsem tam chtìl pøidat...}
{541}{}{**sakra-sakra* O jakém pøíslušenství to... **truaka-truaka*... mluvíš?}
{542}{}{U je mi z tebe blbì... **truaka-truaka*... a ani prcat poøádnì neumíš. Naer se... *síp-síp*... olova, kreténe...}
{543}{}{U... **truaka-truaka*... mám auto zpátky. U tì... **truaka-truaka *... nechci ani vidìt. Mizím.}

# 24. WHAT FIX-UPS? (6, 19, 22, 33, 54)
{550}{}{No co? Vyèistit motor, uklidit interiér, pøelakovat... vyházet z kufru zbyteènı krámy a udìlat v nìm víc místa. 500 chechtákù.}
{551}{}{Však víš. Vyèistit a seštelovat motor, uklidit interiér, trochu nablıskat karosérii... vyházet z kufru zbyteènı krámy a udìlat v nìm víc místa. Máš zájem? 500 chechtákù.}
{552}{}{Jasnì. Tady jsou 500.}
{553}{}{A co takhle 300?}
{554}{}{Tolik u sebe nemám. Co takhle pozdìji?}
{555}{}{A co takhle víc mé sladké lásky?}
{556}{}{A co moje tìlo? To tì nezajímá?}
{558}{}{U je mi BLBÌ z tebe a tvejch kecù. Naer se olova, debile...}
{559}{}{Nedovolím ti, aby ses ještì kdy dotknul mıho auta. Èau.}

# 25. END OF ADDITIONS DEAL (24, 26, 30)
{575}{}{Domluveno. (Bere si peníze.) U je o to postaráno. A kdyby ti nìkdy došly baterky, zajdi za mnou.}
{576}{}{Uka mi hned, co máš. }
{577}{}{Dobøe. Díky. Mìj se, T-Rayi.}

# 26. NO 300 (24)
{590}{}{(Zavrtìl hlavou.) Ne, to není dost. 500, nebo nic.}

# 27. CAN I COME BACK (24, 26, 30)
{615}{}{Jasnì. Pohoda. A kdyby ti nìkdy došly baterky, zajdi za mnou.}
{616}{}{Vlastnì, hodily by se mi nìjaké hned teï.}
{617}{}{Jo, nìjaké by se mi hodily, ale víš co? Nìjak se mi nechce platit hotovì... nemìl bys zájem o nìco... JINÉHO?}
{619}{}{Fajn. Tak pøíštì.}

# 28. SEX FOR BATTERIES, NO BATTERIES (27)
{630}{}{(Pokrèil rameny) Sorry, ale teï ádné zrovna nemám... stav se za tıden nebo tak. Moná se nìco objeví. Ale jestli chceš... mùeme to stejnì UDÌLAT...}
{631}{}{Dobøe.}
{632}{}{Sorry, jenom obchodnì. Mìj se, T-Rayi.}

# 29. SEX FOR BATTERIES, HAVE BATTERIES (27)
{640}{}{Sakra, dìvko! Je to sotva pìt minut a ty chceš zas? Chceš mì ZABÍT?}
{641}{}{No tak, poèkej...}
{642}{}{No tak, potøebuju to. A ty jsi jedinej, kterej mi to udìlá POØÁDNÌ.}
{643}{}{Kašli na to. Mìj se.}

# 30. REJECTION, SUPER CAR (24, 26)
{650}{}{Ne, nechci. Kdy se tak na tebe dívám, stejnì bych jenom prodìlal. 500 doláèù, nebo nic.}
{651}{}{Tak dobøe. Tady je 500.}
{653}{}{Víš co? U je mi z tebe BLBÌ. Asi tì sejmu.}

# 31. SWEET LOVE FOR BATTERIES (29, 53)
{660}{}{(Zastavil tì, ne ses staèila otoèit.) Moment. Neøekl jsem, e NECHCI.
 Pojïme na to.}
{661}{}{(Prohlíí si tì.) Chlap musí udìlat, co musí. Pojïme na to.}
{662}{}{Pojïme na to.}
{663}{}{Ne, rozmyslela jsem si to. Èau.}

# 33. ENCLAVE_DESTROYED (WTG)
{670}{}{Hej! Velkı hrdina se pøišel podívat na starıho kámoše T-Raye. Vítej, vítej... }
{671}{}{Hej, zlatíèko! Pøišla sis odpoèinout k Rayovy, kdy u jsi všechny nakopala do zadku?}
{672}{}{Hele... mám pro tvoje auto nìco, co by tì urèitì zajímalo. JESTLI ho ještì poøád máš}
{673}{}{Co je to}
{675}{}{Co máš pro mı auto?}

# 34. SWEET LOVE...AGAIN? SUPER CAR (24, 26)
{690}{}{Sakra, enská! Je to sotva pìt minut a ty chceš zas? Chceš mì ZABÍT?}
{691}{}{Chceš ZASE? Zatracenì, dáváš vùbec nìkdy nohy k sobì?}
{692}{}{No...}
{693}{}{No tak, potøebuju to. A ty jsi jedinej, kterej mi to udìlá POØÁDNÌ.}

# 35. SWEET LOVE FOR SUPER CAR (34)

# 37. I'M ONE OF BISHOP'S MEN - DON'T BELIEVE (6, 10, 11)
{710}{}{(Prohlíí si tì a mraèí se pøitom.) Jo, jasnì. Znám všechny jeho poruèíky, a ty mezi nima NEJSEŠ. (Ukázal ke dveøím.) Vypadni, ne se rozzlobím a budu zlı.}
{711}{}{JSEM jeden z Bishopovıch poruèíkù. Budeme obchodovat, nebo ne?}
{712}{}{u jdu, u jdu...}

# 38. I'M ONE OF BISHOP'S MEN - WE GONNA DEAL OR WHAT (37)
{720}{}{(Odfrknul si.) Jo, to teda budeme. Doufám, e nemáš rodinu, kterı budeš chybìt...}
{721}{}{Ty radši doufej, e máš rodinu, která do rakve posbírá všechny tvoje kousky.}

# 39. I'M ONE OF BISHOP'S MEN - BELIEVE (6, 10, 11)
{730}{}{(Prohlíí si tì.) Ty jsi jeden z Bishopovıch lidí? Ne... tvoje vıška mi teda rozhodnì nesedí, a taky nevypadáš jako ádnej... (vypadá skepticky)... tvrïák.}
{731}{}{(Prohlíí si tì.) Ty seš }
{5731}{}{?! Slyšel jsem, e }
{6731}{}{ je vo chlup vyšší a mnohem víc ... (vypadá skepticky) ... tvrïák.}
{732}{}{Jsem. Vyzıváš mì?}
{733}{}{Jsem }
{5733}{}{. Vyzıváš mì?}
{734}{}{Nevìø všemu, co slyšíš. Promluvme si o autì pana Bishopa.}
{735}{}{Zapomeò na tuhle pitomou konverzaci. Já mizím.}

# 40. I'M ONE OF BISHOP'S MEN (39)
{745}{}{(Zvedá ruce) Ne, ne, vìøím ti.}
{746}{}{Promluvme si o autì pana Bishopa.}
{747}{}{Pøíštì si radši dávej pozor. Mìj se, já mizím.}

# 41. I'M ONE OF BISHOP'S MEN (39, 40)
{755}{}{Dobøe, dobøe... take, udìláme všechny úpravy, vyèistíme a pøelakujeme kapotu a dodáme ji panu Bishopovi.  Cena... (Krèí rameny a usmívá se) ... otázka je? Jak tohohle Highwaymana ocenit?}
{756}{}{Pokraèuj.}
{757}{}{Na kecy nemám ÈAS. Vymáèkni se.}
{758}{}{Máš pravdu. Nejde to. Vezmu si auto hned a pan Bishop ti na oplátku dovolí pokraèovat ve svıch akcích na jeho území.}
{759}{}{Na tohle nemám èas. Jdu pryè.}

# 42. GO ON. (41)
{770}{}{Jak to vidím já, tenhle Highwayman... je nejspíš poslední fungující na celém svìtì... má cenu ALESPOÒ 3000 dolarù... ale víš co? (Mrknul) Jsem ochotnı rozlouèit se s tímhle bájeènım strojem za 2700 dolarù. A samozøejmì - urèitì bychom se domluvili nìkolik dalších malièkostech: èlenství v klubu, volnı vstup do nìkterıch podnikù...}
{771}{}{2700? Domluveno. Tady je to.}
{772}{}{Pan Bishop nabízí 1500 dolarù.}
{773}{}{2700? Ne, ne... pan Bishop si vezme auto za 900 dolarù.}
{774}{}{Mám protinabídku. Vezmu si auto zadarmo a pan Bishop vás na oplátku nechá pokraèovat ve vašich akcích na svém území.}
{775}{}{Povím to panu Bishopovi a pak se vrátím s jeho odpovìdí.}

# 43. OKAY, 2700 chipS. (42)
{780}{}{(T-Ray mrknul, pak se široce usmál, kdy zaèínáš vytahovat peníze.) Tak, mám rád, kdy se obchody provádìjí takhle rychle a jednoduše. Velice rád s vámi obchoduji, opravdu velice rád. A teï, co bude s tìmi malièkostmi?}
{781}{}{To si budeš muset domluvit s panem Bishopem. Pan Bishop má poslední ádost: Baterie zdarma z tvého obchodu. Budu fungovat jako kurır pro tyto dodávky.}
{782}{}{Ostatní vıhody si budeš muset domluvit pøímo s panem Bishopem. Nezapomeò jít ozbrojenı a hlasitì vyøvávej, e ti nìco dluí. Má rád mue, kteøí se nebojí a jednají ostøe.}
{783}{}{O tom si budeš muset promluvit s panem Bishopem. Mìj se.}

# 44. 1500 chipS (42)
{790}{}{Chlape, za ty peníze si nekoupím ani nové obleèení! }
{791}{}{Chlape, za ty peníze si nekoupím ani nové obleèení! }
{792}{}{Co, myslí si snad Bishop, e auta jsou LEVNÁ?!}
{793}{}{Moná se ti zdá, e se k tobì chováme...nefér?}
{794}{}{Pan Bishop ti dal VELKORYSOU nabídku 1500 dolarù. Jeho další nabídka se ti nebude líbit.}
{795}{}{Tak se ti moná 900 dolarù bude líbit víc. Pan Bishop bude rád, e ušetøí tolik penìz.}
{797}{}{Jeliko byla velkorysá nabídka pana Bishopa odmítnuta, budu pokraèovat podle jeho instrukcí. Beru si auto zadarmo.}
{798}{}{U mì to nebaví, vrátím se pozdìji.}

# 45. 900 chipS (42, 44)
{810}{}{Devìtset... chlape, ty si snad dìláš srandu?! }
{811}{}{Devìtset... enská, ty si snad dìláš srandu?! }
{812}{}{Vyser se na to! To je HIGHWAYMAN. U se nikde nedìlají, jasnı? Myslím, e OSTATNÍ rodiny s radostí zaplatí, kdy ten zkurvysyn Bishop ne...}
{816}{}{Oh, tak ty obchoduješ s cizími rodinami? Ale ale. Tohle bude pana Bihsopa VELICE zajímat.}
{817}{}{Promiò? Co es to øekl o panu Bishopovi?}
{818}{}{U mì to nebaví, vrátím se pozdìji.}

# 46. I'M TAKING THE CAR (41, 42, 44, 45)
{830}{}{(T-Ray ztuhnul. Na sekundu máš dojem, e na tebe zaútoèí, ale pak se uklidnil.) Teda, chlape, tohle je teda dohoda. }
{831}{}{(T-Ray ztuhnul. Na sekundu máš dojem, e na tebe zaútoèí, ale pak se uklidnil.) Teda, chlape, tohle je teda dohoda. }
{832}{}{Co jsem panu Bishopovi udìlal, e si zaslouím takové jednání?}
{834}{}{Vyøídím to panu Bishopovi. Pan Bishop má poslední ádost: Baterie zdarma z tvého obchodu. Budu fungovat jako kurır pro tyto dodávky.}
{835}{}{Urèitì nìco bylo. Nemá tì moc rád. Sbohem.}

# 47. PERHAPS YOU THINK YOU ARE BEING TREATED UNFAIRLY (44, 45, 46)
{845}{}{Ne, ne, nic takového! Já a pan Bishop... rozhodnì si rozumíme. ádnı problém. Chová se ke mnì správnì, vyøiï mu to, ano? A co s tìmi malièkostmi, s tìmi vıhodami, o kterıch jsem se zmiòoval?}
{846}{}{To si budeš muset domluvit osobnì s panem Bishopem. Pan Bishop má poslední ádost: Baterie zdarma z tvého obchodu. Budu fungovat jako kurır pro tyto dodávky.}
{847}{}{Ostatní vıhody si budeš muset domluvit pøímo s panem Bishopem. Nezapomeò mít v ruce zbraò a hlasitì vyøvávat, e ti nìco dluí. Má rád lidi, kteøí se nebojí a jednají ostøe.}

# 48. FREE BATTERIES . . . (43, 46, 47)
{855}{}{(T-Rayùv úsmìv pohasnul.) Dobøe... jistì, jistì... to není problém.}
{856}{}{Vıbornì, dej mi všechny baterie, co máš.}
{857}{}{(Odejdi.)}

# 49. LEAVE . . . NO FREE BATTERIES (43, 46, 47)
{865}{}{Jasnì, jasnì, hej, øekni šéfovi, e baterie ode mì mùe koupit. Co chvíli nìjakou seenu.}
{866}{}{Vánì? Uka, co máš.}

# 50. BISHOP BATTERIES, NONE (6, 33, 48, 54)
{875}{}{Teï ádné nemám, budete muset poèkat tıden dva, ne se nìjaké objeví.}
{876}{}{Dobøe, nechám to tak bıt. Protentokrát. Nashledanou.}

# 51. BISHOP BATTERIES, YES (6, 33, 51, 54)
{885}{}{(T-Rayovy ramena poklesla.) Dobøe. Tady máš. To je všechno co mám.}
{886}{}{Vıbornì. Vrátím se za dva tıdny pro další. Doufám, e je budeš mít pøipravené.}

# 52. BUY BATTERIES, NONE (6, 33, 54)
{896}{}{Okay. Zkusím to pozdìji.}

# 53. BISHOP BATTERIES, YES (6, 33, 54)
{905}{}{Jo, jasnì, pár jich mám.}
{906}{}{Ukáeš mi, co máš na skladì?}
{907}{}{No, jednu chci, ale nechce se mi platit. Není tady nìco JINÉHO, èím by se dalo zaplatit?}
{909}{}{Jen se ptám. Èau.}

# 54. RAM-PLATES (33)
{915}{}{Gravitaèní talíøe! Tyhle krásky ti umoní LÍTAT nad pouští! A mají recyklaèní energetickı èip, take neberou skoro ádnou šávu. Jak se ti to líbí? Chceš je?}
{916}{}{Líbit, já vzít}
{918}{}{To zní dobøe. Vezmu si je.}
{919}{}{Teï ne. Chci baterie zdarma pro pana Bishopa.}
{920}{}{Teï ne. Mùeš na autì nìco vylepšit, kromì tìch gravitaèních talíøù?}
{921}{}{Teï ne. Prodáš mi nìjaké baterie?}
{922}{}{Ne, teï ne. Moná pozdìji. Èau.}

# 55. RAM-PLATES (54)
{930}{}{(T-Ray strávil hodinku v dílnì. Kdy skoèil, jsou talíøe nainstalovány. )}
{931}{}{Díky, T-Rayi. Oceòuju to. Hned je pùjdu vyzkoušet.}

# 56. FLOAT (HERO)
{940}{}{Pomo si sám, hrdino.}
{941}{}{Co je moje, to je tvoje. Ale nezapomeò to všem øíct.}
{942}{}{Sakra. Zachráníš svìt a co z toho máš? Hovno!}

# 57. FLOAT (WARNING)
{950}{}{Odpal od mıch vìcí.}
{951}{}{Dotkni se toho ještì jednou a nakopu ti prdel.}

{1000}{}{Máš auto zpátky bez pouití násilí.}
{1001}{}{T-Ray byl úspìšnì oblbnut.}
{1002}{}{Máš zásobu baterií do auta zdarma.}

# EXPLODING T-RAY
{1100}{}{Pøíliš... mnoho... sexu... asi... prasknu...}

{2000}{}{Máš baterky pro Highwaymana.}
{2010}{}{Máš upgrade pro Highwaymana.}