#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
# quick look
{100}{}{Vidíš boxera.}
{101}{}{Vidíš Mikea "dímaèku."}

# examines
{150}{}{Jeho ruce vypadají jako kmeny stromù. Musí mít sílu, e by dokázal stejnì hrubé stromy lámat v prstech.}
{151}{}{Jeho pae by klidnì mohly soupeøit s tlouškou hlavnì bitevního tanku.}
{152}{}{Pozorovat jeho pohyby, to je jako sledovat rozbouøenı oceán svalù.}
{153}{}{Dívá se hladovì na tvoje levé ucho.}
{157}{}{Jeho oblièej vypadá jako syrovı naklepanı øízek masa.}

# FLOAT DIALOGUE
{158}{}{Hurgghhh.}
{159}{}{Gunhrrhh}
{160}{}{Mike bije}
{161}{}{Fakt miluju zmrzlinu. Vanilkovou.}
{162}{}{Gnarrrr}
{163}{}{Nrrrurhhh}
{164}{}{Mike rád ouška}
{165}{}{Ouška mmmmmmmòam}
{166}{}{Grrrrrr}
{167}{}{Gr. Gr? Grrrrrrr.}
{168}{}{Gr?}
{169}{}{Rrrgggg}
{170}{}{Já jíst ucho. Tvoje}
{171}{}{Uši mòam}
{172}{}{Gr...grrrgr?}
{173}{}{Snrggg}
{174}{}{Nenávidím Robbin' Givens}
{175}{}{Grrrrrgrrrrgrrr...grrr...grrr...grr! Grr! Grrr?}
{176}{}{Co znamenat  'podíl na zisku' ?}

# CLICK DIALOGUE
# (PRIZEFIGHTER)
{200}{}{::Mike se tøepe strachy, jakmile tì uvidìl::}
{201}{}{::Mike zakòuèel, kdy si tì všiml::}
{202}{}{::Mike zvedá ruky na znamení e se vzdává::}
# (FEMALE, ANY BUT PRIZEFIGHTER)
{203}{}{Ty fajn}
{204}{}{Libí mi tvoje ucha}
{205}{}{Dost kecù. Èas do postel}
{206}{}{Robin? To ty?}
