#tenhle soubor pøeložil Birdman - birdman@post.cz, http://get.to/birdman
# 0. QUICK LOOK (WTG)
{100}{}{Vidíš Williho Rakev.}

# 0. LOOK (WTG)
{150}{}{Vidíš starého, páchnoucího a strupovitého ghoula. Ty vole, to je ale SMRAD.}

# 1. DIG UP (WTG)
{200}{}{Uau. Ten hrob SMRDÍ.}
{201}{}{Oh, fajn...radši kopem dál.}
{202}{}{Co to?}
{203}{}{Koneènì, kurva! POMALEJC kopat neumíš, debile?}
{204}{}{Uhni mi z cesty, vole.}
# lenny in party
{205}{}{T'tati?}
{206}{}{Dej pokoj, Lenny, nemám náladu na kecání.}

# 2. CLICK/FLOAT (WTG)
{300}{}{Jen si zajdu do Rena na pár kapek chlastu a nìjakou tu kurvu, a ti zasranci mì vrazí do hrobu...}
{301}{}{Dobrá vìc je, že nemám nos, jináè bych se zadusil vlastním smradem.}
{302}{}{Na ghouly všichni serou.}
{303}{}{Jen sem si skáknul na drink, a ti èuráci mì pohøbìj zaživa.}
{304}{}{Nejni na svìtì nic nudnìjšího než bejt zavøenej pár mìsícù v rakvi.}
{305}{}{Uhni, vole. Musím jít.}
{306}{}{Dej ty pazoury pryè.}

# HEADSTONE
{500}{}{Na náhrobním kamenu je napsáno: "Tady leží nejblbìjší èurák, který kdy vlezl do Nového Rena."}

{550}{}{Z hrobu vane pøíšerný zápach.}

{600}{}{Hej!}
{601}{}{Já dobøe slyším, že mi tam nahoøe nìkdo šlape!}
{602}{}{Nešlapej mi po hrobì, hajzle! Tlaèíš na mì hlínu!}
{603}{}{Rychle, dones LOPATU!}
{604}{}{Tak vyhrabe mì už nìkdo? Mám už kurevskou žízeò!}
{605}{}{Hele, èervíèek? Oh...}
