#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
# 0. QUICK LOOK
{100}{}{Vidíš Wrightovo dítì.}

# 0. LOOK [ENCLAVE_DESTROYED = TRUE] (WTG)
{150}{}{Vidíš malé, èernovlasé dítì s hrncem na hlavì. Ukazuje prstem na imaginární agenty Enklávy a dìlá PRÁSK.}
{151}{}{Vidíš jedno z Wrightovic dìtí s hrncem na hlavì.}
{152}{}{Vidíš jedno z Wrightovic dìtí s hrncem na hlavì. Ukazuje prstem na imaginární agenty Enklávy a dìlá PRÁSK.}

# 1. LOOK (NORMAL) (WTG)
{200}{}{Vidíš malé, èernovlasé dítì s hrncem na hlavì. }
{201}{}{Vidíš jedno z Wrightovic dìtí s hrncem na hlavì. Bzuèí jako vosa. *Bzzzzing*}

# 2. FLOAT [ENCLAVE_DESTROYED = TRUE] (WTG)
{210}{}{Podívej se na mnì, jsem potomkem Zakladatele! Velebte Zakladatele! Velebte Vault!}
{211}{}{Chci na vıpravu do Vaultu 13!}
{212}{}{Blam blam! Zemøi, Enkláváku!}
{213}{}{Pozor, támhle je Enklávák! Bijte ho!}
{214}{}{Prásk! Bum! Tu máte, vy enklávští zlosyni!}
{215}{}{Proè já nemùu bıt Zakladatel! Ty jsi vdycky Zakladatel a já nikdy.}
{216}{}{Chceš všechny zabít virem, co? Tady máš, pane Prezidente!}
{217}{}{Dej si tohle, pane Prezidente!}
{218}{}{Pøíští hru jsem Zakladatel já!}
{219}{}{He heh! Netrefil ses, ty jeden Prezidenáku!}
{220}{}{Uh-uh! Dostal jsem tì! Seš mrtvej!}
{221}{}{Právì jsme znièil Enklávu! Buuuuum!}
{222}{}{Rychle! Všichni do tankeru!}
{223}{}{Naerte se olova, Enkláváci!}
{224}{}{Seš mrtvej, ty jeden enkláváckej chlapeèku!}
{225}{}{Enklávští hajzlové! Ochutnejte moje olovo!}
{226}{}{Ha ha, to neplatí! Já mám toti nasazené Energetické brnìní a kulka se ode mì odrazila!}
{227}{}{Zemøi, Enkláváku!}
{228}{}{Aighhhhhhhh...dostali mnì...}

# 3. FLOAT [WRIGHT CHILDREN PLAYING, NORMAL] (WTG)
{240}{}{Podívej se na mnì, jsem elezná moucha! Bzzzzzz}
{241}{}{Blam blam!}
{242}{}{Pozor, ocelová moucha na vás letí!}
{243}{}{Tumáš!}
{244}{}{Proè já nemùu bıt ocelová moucha?! Ty jsi vdycky ocelová moucha a já nikdy.}
{245}{}{Bang bang!}
{246}{}{A pøíštì jsem ocelová moucha já!}
{247}{}{Nuh-uh! Netrefil ses!}
{248}{}{Uh-uh! Dostal jsem tì! Dostal jsem tì!}
{249}{}{Bzzzzzzz}
{250}{}{Padni, seš mrtvej!}
{251}{}{Zooommmm}
{252}{}{Dostanete akorát moje olovo!}
{253}{}{To neplatí, mìl jsem zapnuté silové pole!}
{254}{}{Chcípní, Salvátoráku!}
{255}{}{Aighhhhhhhh...Dostali mnì...}

# 4. CLICK [ENCLAVE_DESTROYED = TRUE] (WTG)
{270}{}{Škoda e tady není Dogmeat z Falloutu 1. Nebo se jmenoval eryk?}
{271}{}{Myslíš, e bude Fallout 3? Jestli jo, tak si zamlouvám roli hlavního hrdiny!}
{272}{}{Fallout 2 vám pøináší písmeno Z.}
{273}{}{Enkláva mi mùe políbit moji sedmiletou prdel. Takoví kreténi.}
{274}{}{Enkláváci jsou opravdu kreténi, e jo?}
{275}{}{Je pravda, e Prezident mìl velké drápy a zuby a místo krve kyselinu?}
{276}{}{Škoda, e jsem nešel na Enklávu s tebou. Spoleènì bychom jim dali po hubì ještì víc. Já se jich vùbec nebojím!}
{277}{}{Hej! }
{5277}{}{! Povìz nám, jak to bylo v Enklávì! Prosím?!}
{278}{}{}
{5278}{}{! Yaaaaay!}
{279}{}{Díky za záchranu, }
{5279}{}{!}
{280}{}{A vyrostu, tak taky zachráním svìt jako ty. Ale já to udìlám alespoò dvakrát, heè!}
{281}{}{Mùu bıt taky hrdina, a vyrostu?}
{282}{}{Já chci bıt }
{5282}{}{ a vyrostu.}

# 5. CLICK [POWER ARMOR] (WTG)
{300}{}{Aighhhh! To je eleznej èlovìk! Uteète!}
{301}{}{To je eleznej èlovìk! Našel nás! Uteète!}
{302}{}{Promiòte! Promiòte nám to! Neposílejte na nás ocelovou mouchu! Prosím!}

# 6. CLICK [SLAVER OR BAD REP] (WTG)
{310}{}{Radši uteè, ne tì táta uvidí.}
{311}{}{Radši uteè, ne tì uvidí starší brácha uvidí.}
{312}{}{Ty jsi nehodnej èlovìk. Radši odejdi, nebo to na tebe øeknu.}

# 7. INTRO (WTG)
{320}{}{(Dítì pøestalo dìlat *bzzzzzing*. Zvedlo hrnec a dívá se na tebe.)}
{321}{}{mùeš }
{5321}{}{ taky hrát?}
{322}{}{Sorrı. Myslel e seš hrneèek èau}
{323}{}{Proè máš na hlavì hrnec?}
{324}{}{Na co si to hraješ?}
{325}{}{Kde máš rodièe?}
{326}{}{(Nech ho, a si hraje.)}

# 8. CAN [X] PLAY TOO? (7)
{330}{}{No...dobøe. (Prohlíí si tì od hlavy k patì.) Ale teï budu ocelová moucha já!}
{331}{}{Dóbr malej plecho moucho}
{332}{}{ souhlasíš.}
{333}{}{jakej mouch?}
{334}{}{Ne! }
{5334}{}{ chceš mouch bıti!}
{335}{}{Ooooh...co to kdeto?}

# 9. OKEE DOKEE/X CAN DO THAT/[X] OKAY WITH THAT (8)
{340}{}{(Malej muíèek si nechal hrnec spadnout na hlavu a pokraèuje v dìlání *bzzzzing*.)}
{341}{}{Utíkej za ním a dìlej taky *bzzzzing*.}
{342}{}{Odpajdej se pryè}
{343}{}{(Odejdi.)}

# 10. WHAT INCEST? (8)
{350}{}{MOUCHA, hlupáku! My jsem ho VIDÌLI! Na poušti, byla velká jako... (Zhluboka se nadechl.) ...velká jako BARÁK! A uvnitø byli LIDI!}
{351}{}{Ne ne}
{352}{}{Neøíkej hlupák já}
{353}{}{Neøevej }
{5353}{}{ nerad dy nìgdo øeveš.}
{354}{}{Ty leš }
{5354}{}{. Ty dìláš SRANDA z }
{6354}{}{. }
{7354}{}{ nelíbíš.}
{355}{}{ Zabil móc malejch øvanejch lídišek jak ty. Ty chceš další bıti?}
{356}{}{Odejdi.}

# 11. NUH-UH 1 (10)
{360}{}{Jo jo. Vidìli jsme ji.}
{362}{}{Uh-uh-uh-uh}
{363}{}{Huh-huh-huh-huh}
{364}{}{Odejdi dìlat uhuhuh na nìkoho jiného.}

# 12. NUH-UH 2 (11)
{370}{}{Uh-huh! Ukáu ti ho! Pár nás tam pùjde, a bude POØÁDNÁ tma!  }
{371}{}{Uh-huh! Ukáu ti ho! Pár nás tam pùjde dneska v noci. }
{372}{}{Chceš jít? (Malej èlovíèek na tebe zašilhal.) Ale musíš bıt moc moc tiše. Fakt, hódnì moc tiše!}
{373}{}{Dóbro (Jdi za ním.)}
{374}{}{Dóbro My jít támto do písek, ejo?}

# 13. DON'T SHOUT. X NO LIKE SHOUT. (10, 13, 21)
{380}{}{Nemám tì rád! Seš velkej a blbej! (Vyplazuje na tebe jazyk.) Vypadni, kreténe!}
{381}{}{NEØÍKÁŠ KRETÉN! NEØÍKÁŠ KRETÉN JÁ! TY KRETÉN TY!}
{382}{}{Neøveš! Neøveš na }
{5382}{}{! }
{6382}{}{ ROZBIJEŠ!}
{383}{}{Spolkni slzy a uteè}
{384}{}{Dobøe...tentokrát.  Zklidni se s tím Jetem, chlapeèku.}

# 14. UH-UH-UH-UH/HUH-HUH-HUH-HUH (11)
{390}{}{(Zašilhal na tebe.) Dìláš zvuky jako táta a máma, kdy jdou do postele.}
{391}{}{Kde vidíš mouch? Chceš tky vidìti!}

# 15. YOU LIE TO [X]. YOU MAKE FUN OF [X]. [X] NOT LIKE. (10)
{400}{}{Nelu, hlupáku!  Pár nás tam pùjde, a bude POØÁDNÁ tma! }
{401}{}{Nelu, hlupáku! Pár nás tam pùjde dneska v noci. }
{403}{}{NEØÍKAŠ MI HLUPÁK, TY HLÚPAK}
{404}{}{Uh-huh (Jdi za ním.)}
{405}{}{Dóbro my jít támto do písek, e jo?}

# 16. WHERE HE SEE INCEST? I WANNA SEE IT TOO (14)
{410}{}{Pár nás tam pùjde, a bude POØÁDNÁ tma!  }
{411}{}{Pár nás tam pùjde dneska v noci.  }
{412}{}{Chceš jít? (Zašilhal na tebe.) Ale musíš bıt moc moc tiše. Fakt, hódnì moc tiše!}

# 17. WHY DO YOU HAVE A POT ON YOUR HEAD? (7, 32)
{420}{}{To není hrnec, ty HLUPÁKU! To je moje HELMA!}
{421}{}{Uau, tak sorry, strašlivı bojovníku v helmì.}
{422}{}{Øekni mi ještì jednou hlupáku, ty malá sraèko, a uvidíme, jak tì ta tvoje 'helma' ochrání pøed kopaèkou do ksichtu.}
{423}{}{(Nech ho, a si hraje s 'helmou.')}

# 18. WHOA, SORRY THERE, FEARSOME HELMED WARRIOR. (17)
{430}{}{(Podezøívavì se na tebe dívá.) Co chceš?}
{432}{}{Zajímalo mì, jakou hru to tady hraješ. Vypadá to jako poøádná zábava!}
{433}{}{Uh...kde máš rodièe?}
{434}{}{Nic.}

# 19. CALL ME STUPID AGAIN . . . / NO SHOUT! NO SHOUT AT X! X SMASH! (10, 13, 17)
{440}{}{(Malej muíèek zblednul, ustoupil o pár krokù dozadu. Pak se otoèil a utíká pryè. Øve pøitom jako na lesy.)}
{441}{}{(Dítì zbledlo, ustoupilo pár krokù dozadu. Pak se otoèilo a utíká pryè. Øve pøitom jako na lesy.)}
{442}{}{Hee hee...utíkáš, malej hajzl! UTÍKAŠ!}
{443}{}{Zasranej pravej parchant...}

# 20. WHAT ARE YOU PLAYING? (7, 18, 32)
{450}{}{Na ocelovou mouchu a vojáky. }
{451}{}{(Prohlíí si tì a zpozoroval jednu z tvıch pistolí.) Mùu si chvíli hrát s tvojí pistoli?}
{452}{}{Ne, ne...je to moc nebezpeèná vìc na hraní, mladíku.}
{453}{}{Ne. Ustøelil bys nìkomu nos.}
{454}{}{Jo, jistì, hrncová hlavo. Tumáš. (Dej mu vybitou pistoli.)}
{455}{}{Jo, jistì, hrncová hlavo. Tumáš. (Dej mu nabitou pistoli.)}
{456}{}{"Ocelovou Mouchu?"}
{457}{}{Oh, okay. Ptám se jenom ze zajímavosti.}
{458}{}{Ne...Asi radìji pùjdu.}

# 21. NO, TOO DANGEROUS. NO GUN FOR YOU (20, 21)
{470}{}{(Zírá na tebe.) No tak! Já vím, jak takové vìci pouívat! Jsem Wright! Pùjè mi ji! Prosím?!}
{471}{}{Hele: Ve špatnıch rukou je pistole smrtící zbraò. Teda, VDYCKY je to smrtelná zbraò teda...zbraò...A sakra, radši zaènu od zaèátku.}
{472}{}{hele, kdyby ti rodina dùvìøovala s pistolí, dali by ti jednu. Take na to zapomeò.}
{473}{}{Nesralo by mnì, ani kdybys byl v rodinì Supermanù. Tu zbraò do pazoury nedostaneš.}
{474}{}{Tak dobøe. (Dej mu vybitou pistoli.)}
{475}{}{Tak dobøe. (Dej mu nabitou pistoli.)}
{476}{}{Zapomeò na to. Jdi si hrát s ostatními.}

# 22. METAL INSECTS? TELL ME ABOUT THE METAL INSECTS. (28)
{485}{}{Jo, OCELOVÁ MOUCHA! My jsem ho VIDÌLI! Na poušti, byla velká jako... (Zhluboka se nadechl.) ...velká jako BARÁK! A uvnitø byli LIDI!}
{486}{}{Vánì? Uau! Kde jste ho vidìli?}
{487}{}{Leš!}
{488}{}{Nevìøím ti. Leš.}
{489}{}{Zklidni se s tím Jetem. Zabije tì to. Mìj se.}
{490}{}{Vánì? To je úasnı. Taky se tam musím nìkdy podívat. Èau.}

# 23. REALLY? WOW! WHERE DID YOU SEE IT? DON'T TRUST (22)
{500}{}{V poušti. (Podezøívavì se na tebe dívá.) Ale u tam stejnì asi není.}
{501}{}{Jsi si jistı, e mi to místo nechceš alespoò ukázat?}
{502}{}{Mùeš mi to stejnì ukázat?}
{503}{}{Hm, tak dobøe. Èau.}

# 24. REALLY? WOW! WHERE DID YOU SEE IT? TRUST (22)
{510}{}{V poušti. (Opatrnì se rozhlíí a zaèíná šeptat.) Pár nás tam pùjde, a bude POØÁDNÁ tma! }
{511}{}{V poušti. (Opatrnì se rozhlíí a zaèíná šeptat.)  Pár nás tam pùjde dneska v noci. }
{513}{}{Tichost není moje vlastnost, ale protentokrát...}
{514}{}{budu tiše jako myška. Veï mì.}
{515}{}{Uh, myslím, e u ocelovou mouchu neuvidíš. On to vlastnì byl vrtulník.}
{516}{}{Dneska v noci ne, díky. Ráno brzo vstávám.}

# 25. IT WAS A HELICOPTER (24, 27)
{530}{}{Hunh? (Mraèí se a upravuje si hrnec na hlavì.) Co je to ... vrtu-látor?}
{531}{}{To je ...létající stroj. Uvnitø mùe vozit lidi.}
{532}{}{Vrtulník je...nejbliší aproximace, kterou bys mohl znát, je automobil. Vrtulník neboli helikoptéra je automobil, kterı je schopnı vznést se ze zemì a vznášet se za pouití vertikálnì rotujících listù vrtule. Motor helikoptéry otáèí vrtulí tak rychle, e se udruje ve vzduchu. Není to úasné?}
{533}{}{To nic. Jenom se nepoflakujte kolem mìsta, je to nebezpeèné.}

# 26. YOU'RE LYING! DON'T TRUST (22)
{540}{}{Já NELU! VIDÌLI JSME TO! (Mrzutì si tì prohlíí.)}
{541}{}{Hmmm. Moná øíkáš pravdu aspoò v nìèem. Mùeš mi ukázat, kde jste to vidìli?}
{542}{}{Okay, vìøím ti. Ukáeš mi, kde to bylo?}
{543}{}{Okay, okay. Nic. Jdi si hrát dál}

# 27. YOU'RE LYING! TRUST (22)
{550}{}{Nelu! Vidìli jsem to v poušti! Mùu to dokázat! (Zírá na tebe.) Pár nás tam pùjde, a bude POØÁDNÁ tma! }
{551}{}{Nelu! Vidìli jsem to v poušti! Mùu to dokázat! (Zírá na tebe.)  Pár nás tam pùjde dneska v noci. }
{552}{}{Pojï s námi a já ti to ukáu! (Odfrknul si.) Teda pokud se nebojíš!}
{556}{}{Ne dík. Jdi si hrát dál.}

# 28. SURE CAN./GIVE PISTOL (20, 21)
{560}{}{(Po chvilce pøehazování vìci v batohu vytahuješ svou nejhorší pistoli a dáváš jí dìcku. Usmívá se a hned ji zaèíná obdivovat.) MOJE vlastní pistole! Super! }
{561}{}{A vím, kde se k ní dají sehnat náboje!}
{562}{}{Uh, nemùeš si ji nechat. Jenom ti ji na chvíli pùjèuju...}
{563}{}{Yo, je tvoje. A teï mi povìz o té ocelové mouše...}
{564}{}{Nabij a støílej, kluku. Hele, proè ji nejdeš ukázat tátovi? Musíš s ní mávat a nezapomeò zmáèknout tady tu malou vìc.}
{565}{}{Jo jasnì. Uij si ji. Èau.}

# 29. UH, YOU CAN'T KEEP IT. (28)
{570}{}{Ty lumpe! Je moje! Dostal jsem ji! Je moje!}
{571}{}{naval ji zpátky, ty malá sraèko!}
{572}{}{Ne, je moje. Spousta lidí ode mnì dostala po hubì, abych ji moh mít. Dej mi ji zpátky, posííííííííím?!}
{573}{}{Oh, sakra. V tomhle pitomım svìtì se tím nic nezhorší, kdy si blbé dìcko vystøelí oko s pistolí. Tak padej, jdi zastøelit bráchu.}

# 30. GIVE IT BACK, YOU LITTLE SHIT/NO, IT'S MINE. CAN I PLEEEEASE HAVE IT BACK? (29)
{580}{}{Ne ne! (Utíká pryè i s pistolí.)}
{581}{}{Pojï zpátky, ty malej zmrde!}

# 31. WHY DON'T YOU GO POINT IT AT DADDY? (28)
{590}{}{Okay! (Utíká pryè.)}
{591}{}{No, tenhle malej akt zla bude potøebovat chvíli èasu, ne se vyklube... take radši práskneme do bot a zmizíme odtud.}
{592}{}{(Klidnì odejdi ze sousedství a nevinnì si hvízdej.)}

# 32. WHERE ARE YOUR PARENTS? (7, 18)
{600}{}{Táta je doma. Máma v kostele.}
{603}{}{Aha, dík.}

# 33. LEAVE HIM AND LET HIM PLAY./WANDER OFF. (27)
{610}{}{(Dítì si narazilo hrnec zpátky na hlavu a pokraèuje v lítání po okolí a bzuèení jako hejno èmelákù.)}

# 34. SHRUG. (24, 25, 27)
{620}{}{(Dítì pokrèilo rameny. Narazilo si hrnec zpátky na hlavu a pokraèuje v lítání po okolí a bzuèení jako hejno èmelákù.)}

# 35. "VIGOROUS" NO (23, 26)
{630}{}{(Potøásl hlavou. Nasadil si hrnec a pokraèuje v bzuèení.)}
{631}{}{Uh, okay.}
{632}{}{Ty malej hlajzle...Uvidíme, jestli tì taky zachráním, a budu zachraòovat svìt...}

# 36. GO OUT INTO DESERT (12, 15, 16, 24, 27)
{640}{}{Èekáte, dokud se poøádnì nesetmí...}
{641}{}{Èekáte, dokud se nesetmí...}
{642}{}{...potom následuješ dítì do pouštì.}

# 37. SCREAMING
{700}{}{JDI ODE MNÌ!}
{701}{}{Ahhh...}
{702}{}{Pomóc, pomóc!}
{703}{}{ZLEJ ÈLOVÌK! JDI PRYÈ!}
{704}{}{DEJ MI POKOJ! NECH MÌ BİT!}

# 38. THANKS
{710}{}{Hej, dík za tu skvìlou zbraò, pane.}
{711}{}{U jsem ti øíkal, jak miluju pistoli, co jsem od tebe dostal?}
{711}{}{Hej, dík za tu skvìlou zbraò, paní.}

# 39. LOST GUN
{720}{}{Hej! Kterej lump mi vzal tu pistoli, co mi dal tady ten pán?}
{721}{}{Kde mám pistoli?}
{722}{}{Vím, e jsem od tebe dostal pistoli, ale kde sakra je?}
{723}{}{Hej! Kterej lump mi vzal tu pistoli, co mi dala tady ta paní?}
