#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
# QUICK LOOK
{100}{}{Vidíš Wrightovo dítì. }

# LOOK (IF MALE) (WTG)
{150}{}{Vidíš èernovlasého chlapce.}
{151}{}{Vidíš èernovlasou holèièku. Má vlasy ostøíhané na krátko, take na první pohled ti pøipadala jako chlapec.}

{155}{}{Vyplazuje na tebe jazyk.}
{156}{}{Mrzutì se na tebe dívá.}
{157}{}{Vyplazuje na tebe jazyk.}
{158}{}{Má èerné vlasy ostøíhané tak nakrátko, e mùe klidnì pouívat sprajty chlapecké postavy.}
{159}{}{Mrzutì se na tebe dívá.}

# 2. FLOAT [ENCLAVE_DESTROYED = TRUE] (WTG)
{175}{}{Fallout 2 vám pøináší písmeno Z.}
{176}{}{Hej! }
{177}{}{}
{178}{}{Díky za záchranu, }
{179}{}{A vyrostu, tak taky zachráním svìt jako ty. Ale já to udìlám alespoò dvakrát, heè!}
{180}{}{Mùu bıt taky hrdina, a vyrostu?}
{181}{}{Já chci bıt  }

# 3. FLOAT [POWER ARMOR] (WTG)
{190}{}{Ty jsi robot? }
{191}{}{Jak s tou vìcí èùráš?}
{192}{}{Mùu ti jezdit na zádech? Prosím!}
{193}{}{Budeš si s námi chvíli hrát? Prosím!}

# 4. FLOAT AND CLICK [SLAVER OR BAD REP] (WTG)
{200}{}{Radši uteè, ne tì táta uvidí.}
{201}{}{Radši uteè, ne tì uvidí starší brácha uvidí.}
{202}{}{Ty jsi nehodnej èlovìk. Radši odejdi, nebo to na tebe øeknu.}

# 5. FLOAT AND CLICK [SNEAKING] (WTG)
{210}{}{Vidím tì! Vidím tì!}
{211}{}{hraješ si na schovávanou? Mùu taky?}

# 6. FLOAT COMMENTS [ROBOBRAIN + MARCUS] (WTG)
{215}{}{Hele, robot! Hele, robot!}
{216}{}{V tom robotovi, to je opravdovej mozek?}
{217}{}{Oooooooh. Podívejte se na toho robota!}
{218}{}{Podívejte, mutant! Mutant!}
{219}{}{Mutant, lulant, mutant, lulant}
{220}{}{Fuj, ten mutant je ale škaredej.}
{221}{}{Oooooooh. Podívejte se na toho mutanta!}
{222}{}{Ten mutant je VELKEJ! Vìtší ne táta!}

# 7. FLOAT COMMENTS [LENNY + DOG] (WTG)
{230}{}{Ghoul! To je ghoul!}
{231}{}{Ewwwwwww! Ghoul! Ghoul!}
{232}{}{Ghoul-eee ghoul-eee ghoul-eee!}
{233}{}{hele, eleznej pejsek!}
{234}{}{Pejsku! Pejsku, chceš kostièku?}
{235}{}{Já chci taky pejska!}


# 10. FLOAT [ENCLAVE_DESTROYED = TRUE] (WTG)
{290}{}{A vyrostu, tak taky zachráním svìt jako ty. Ale já to udìlám alespoò dvakrát, heè!}
{291}{}{Mùu bıt taky hrdina, a vyrostu?}
{292}{}{Chci bıt jako ty, a vyrostu!}
{293}{}{Proè chceš já jako bıti? Já BLBEJ}
{294}{}{Jednou nositi já na krku hlava od malá holky jako èépic}
{295}{}{Odejdi}
{296}{}{Heh-heh. Díky, malá. Ale poslechni jednu radu, co ti }
{297}{}{Následuj své sny. Mùeš je uskuteènit. Já jsem dùkaz.}
{298}{}{Jo jasnì. Je mi líto tvıho bráchy Richieho. Nevíš náhodou, co se mu stalo?}
{299}{}{Jednou jsem projel tøi státy a místo èepice jsem mìl nasazenou hlavu malı holèièky.}
{300}{}{(Nech ho, a si hraje.)}
{301}{}{(Nech ji, a si hraje.)}

# 11. WHY YOU WANNA BE ME? ME DUMB. (10)
{310}{}{Uh-uh! Ty seš CHYTREJ a HRDINA a ODVÁNEJ a já chci bıt jako ty. Díky za záchranu nás všech, }
{311}{}{Díky, hodnej malej èlovìku }

# 12. FOLLOW YOUR DREAMS. (10)
{315}{}{Okay, }
{316}{}{Dej si na sebe pozor, okej? Já mám na práci ještì pár hrdinskıch vìcí.}

# 13. I'VE GOT SOME THINGS TO DO. (12)
{320}{}{(Dítì tì zastavilo.) Um... }
{321}{}{Uh...ne. Slibuju.}
{322}{}{Uh...pokud vím tak ne.}
{323}{}{Neboj se, malièkı. Vrátím se jako jiná postava.}
{324}{}{Neboj se, nic neucítíš.}

# 14. UH, HARD DRIVE (13)
{330}{}{Budeme snít?}
{331}{}{Uh...jistì. Urèitì.}
{332}{}{Netuším. Mnì se nic nezdá, take tobì asi taky ne. ivot je svinì, co?}

# 15. POWER ARMOR 1 (WTG)
{341}{}{Co roubot?}
{344}{}{Heh-heh. Ne, nejsem robot.}
{345}{}{Ne, ne, pod tím brnìním jsem normální èlovìk. Hele, slyšel jsem o tvém bráchovi, Richiem. Nevíš, co se mu stalo?}

# 16. WATZ A ROBOT?/YER DUMB, PEE-FACE/MOOTANT? (15, 25, 27, 29, 41)
{355}{}{Ty seš ale BLBEJ.}
{356}{}{TY TAKY}
{357}{}{Ty taky, akorát víc}
{358}{}{Ty seš blbìjší}
{359}{}{blé blé, kašlu na tebe!}
{360}{}{Hrmpf}
{361}{}{S brekotem uteè}

# 17. YER DUMBERR (16)
{370}{}{Ty seš nejblbìjší! Ty seš nejblbìjší!}

# 18. POOR RESPONSE (16, 17)
{395}{}{Ne ne, KRETÉNE! (Dítì utíká pryè, jeho smích ti krutì zvoní v uších.)}
{396}{}{Já stejnì nechceš ty, já nelíbíš ty *smrk*... já... *smrk*... udìlám PÁRTY... a s moc  *smrk* cukr a zmrzliòa .. a ty nepùjdeš, nene [Odcházíš.]}

# 19. YER DUMB-ESSTT-ERR (17)
{405}{}{(Dítì mrká, otevøelo pusu a pak ji zase zavøelo. Po tváøích mu zaèaly téct slzy, které se nakonec zmìnily na pláè.)}
{406}{}{Hee hee JÁ vyhrávám.}

# 20. I'M NOT A ROBOT (15, 28)
{410}{}{Oh. (Chvíli o tom pøemıšlí, pak se na tebe zašklebilo.) Proè NEJSI robot?}
{411}{}{Uh... protoe... no, roboti a lidi mají rùzné... uh, èásti.}
{412}{}{Musím u jít.}

# 21. ROBOTS AND PEOPLE HAVE DIFFERENT PARTS (20)
{425}{}{Jo tak? (Tváøí se podezøívavì.) Jako co?}
{426}{}{Uh...no...hele, copak ti to táta s mámou ještì nevysvìtlili?}
{427}{}{Uh...no! Sakra tolik hodin! Musím letìt.}

# 22. DIDN'T MOMMY AND DADDY EXPLAIN THIS TO YOU? (21)
{435}{}{Vysvìtlili co?}
{436}{}{Uh...no...roboti...mají vevnitø olej. A lidi...no, lidi...krvácejí.}

# 23. HUMANS BLEED (22)
{445}{}{Máma a moje velké sestry krvácejí kadı mìsíc nebo tak. Jsou vdycky strašnì naštvané. Kdyby to tak byly roboti!}
{446}{}{Uh...jo. Skvìlı. hele, já musím jít. Neøíkej o mnì mamince.}

# 24. POWER ARMOR 2 (WTG)
{456}{}{Normálnì èùrám. Na ten smrad se dá zvyknout}
{459}{}{Heh-heh. Vlastnì moèím do brnìní a to všechno zrecykluje. Víš, co to znamená 'recyklovat'?}
{460}{}{No pøíjemné to není. Hele, víš nìco o tom, co se stalo tvému bráchovi Richiemu?}

# 25. I PEE IN ARMOR (24)
{475}{}{To je HNUSNİ.}
{476}{}{Ano! Recyklace znamená, e piješ moè!}
{477}{}{TY HNUSNEJ, poèùránku}
{479}{}{Uh, heh...heh. Ne, to znamená...}

# 26. NO, ACTUALLY, IT MEANS . . . (25, 26)
{485}{}{Ty piješ moè! Ty piješ moè! }
{486}{}{Uh, he...he...ztiš se trochu...recyklování neznamená, e piju m...no, ne DOSLOVA, hele}
{487}{}{Nech to malé hovno, a si hraje samo.}
{488}{}{(Odejdi.)}

# 27. CLICK [ROBOBRAIN] (WTG)
{495}{}{To je ROBOT?}
{499}{}{Robomozek? Ano, je.}
{500}{}{Myslí si to.}
{501}{}{Jo, ale nestarej se o to. Myslím, e chce vyhubit lidskou rasu.}
{502}{}{Jo, je. Hele, mùeš mi øíct nìco o tom, co se stalo tvému bráchovi, Richiemu?}

# 28. CLICK [ROBOBRAIN] (27)
{515}{}{Ty jsi raky robot?}

# 29. CLICK [MARCUS] (WTG)
{525}{}{To je opravdovej mutant?}
{526}{}{Mùtant?}
{529}{}{Ano, je. Jmenuje se Marcus. Neboj se, nekouše. Vìtšinou.}
{530}{}{Ano, JE mutant. Uh, doufám, e zase nedostal chu na malı dìti.}
{531}{}{Ano, je. Hodnì HLADOVİ mutant. Hmm hmm, zrovna je akorát èas na svaèinu. To je dobøe.}
{532}{}{Ano, je. Hele, mùeš mi øíct nìco o tom, co se stalo tvému bráchovi Richiemu?}

# 30. INTRO (WTG)
{540}{}{Dítì se zastavilo a dívá se na tebe.}
{541}{}{Ahóóój}
{544}{}{Ahoj, èlovíèku.}
{545}{}{Ahoj, holèièko.}
{546}{}{Hele, mùeš mi øíct nìco o tom, co se stalo tvému bráchovi Richiemu?}

# 31. I DROVE THROUGH 3 STATES . . . (10, 15, 24, 27, 29 30, 41)
{555}{}{Je ti špatnì? }
{556}{}{Proè se ptáš?}

# 32. WHY DO YOU ASK? (31)
{560}{}{Vypadáš nemocnì}
{561}{}{Jsem nemocnı.}

# 33. I AM SICK. (32)
{565}{}{Léèíš se?}
{566}{}{Na to, co mám, neexistuje medicína.}

# 34. THERE IS NO MEDICINE FOR WHAT I HAVE. (33)
{570}{}{Chceš si zazpívat?}
{571}{}{Zazpívat?}

# 35. SING? (34)
{575}{}{Znáš 'Prší prší, jen se leje?'}
{576}{}{Ano, znám.}

# 36. YES, I DO. (35)
{580}{}{::Zpívá::: 'Prší prší, jen se leje.Prší prší, jen se leje.' No tak, pøidej se.}
{581}{}{::Zpívej:: Prší prší, jen se leje.Prší prší, jen se leje.}

# 37. SING TOGETHER (36)
{585}{}{::Zpíváte dohromady:: Prší prší, jen se leje.Prší prší, jen se leje. ::Pokraèujete a dokonce:: Pojedeme na luka, a kukaèka zakuká.}
{586}{}{Díky za zazpívání. Moná se ještì vrátím... asi budu potøebovat novou èepici.}

# 38. HELLO, LITTLE MAN/WOMAN. (14, 37)
{590}{}{(Dítì na tebe mrklo.)}
{591}{}{Dobøe. Promluvíme si nìkdy jindy.}

# 39. TALK TO YOU LATER/LET HIM GO BACK TO PLAYING/THANKS FOR SINGING WITH ME (38)
{595}{}{(Dítì utíká pryè.}

# 40. HELLO (MALE) (30, 40, 42)
{648}{}{Oh.}
{650}{}{Vánì?}

# 41. CLICK [LENNY] (WTG)
{665}{}{To je PRAVEJ ghoul?}
{666}{}{Gùl?}
{669}{}{Ano, je. Jmenuje se Lenny. Neboj se, nekouše. Vìtšinou.}
{670}{}{Ano, JE ghoul. Uh, doufám, e zase nedostal chu na malı dìti.}
{671}{}{Ano, je. Hodnì HLADOVİ ghoul. Hmm hmm, zrovna je akorát èas na svaèinu. To je dobøe.}

# 42. HIS NAME IS MARCUS. (29, 40, 41)
{685}{}{Ahoj, Marcusi mutante. Seš fakt velkej. Hee-hee... a tvoje animace, kdy se nudíš, je fakt srandovní.}
{686}{}{Ahoj, Lenı ghoule. Pfff, je to pravda. Ghoulové fakt hodnì smrdí.}
{687}{}{Jo, to je. Take, co se dìje poslední dobou?}
{688}{}{Jo, to je. Take, co se dìje poslední dobou?}
{689}{}{no nic, já musím jít. Èau.}

# 43. MARCUS/LENNY IS HUNGRY (29, 40, 41)
{695}{}{(Dítì zbledlo a dalo se s øevem na útìk.}
{696}{}{Heh heh heh heh. "To je PRAVEJ mutant?" To jí nauèí, ptát se na takové blbosti.}
{697}{}{"Hladovej " mutant! Ssss. kadı ví, e mutanti nejedí li- uh, proè se na mì tak díváš, Marcusi?}
{698}{}{Heh heh heh heh. "To je PRAVEJ ghoul?" To jí nauèí, ptát se na takové blbosti.}
{699}{}{"Hladovej " mutant! Ssss. kadı ví, e mutanti nejedí li- uh, proè se na mnì tak díváš, Lenny?}

# 44. OD (10, 15, 24, 27, 29, 30, 40, 41)
{710}{}{Uh-uh. táta je fakt vzteklej, protoe ještì neví, kdo zabil Richieho. Øíkal, e jestli nás nìkdy chytí s Jetem, zbièuje nás.}
{711}{}{Víš, KDO dal Richiemu JET, kterı ho zabil?}
{712}{}{Víš, ODKUD mìl Richie ten Jet, kterı ho zabil?}
{713}{}{Nech dítì, a si jde hrát.}

# 45. DO YOU KNOW WHO? (44, 46)
{720}{}{Uh-uh.}

# 46. DO YOU KNOW WHERE? (44, 45)
{730}{}{Uh-uh. èasto chodil na západ mìsta, ke Komerèní ulici, jak je ten starej Rakeák. A táta nám zakázal chodit tam.}

# sleeping
{800}{}{*Šššš* Mìla bych spát.}
{801}{}{Musím se trochu vyspat. Zítra si budeme hrát na ocelovou mouchu.}
{802}{}{Jestli táta zjistí, e ještì nespím, bude fakt zlej.}

# 8/40. FLOAT [WRIGHT CHILDREN: BOYS] (WTG)
{900}{}{Cing-a-ling, Cing-a-ling.}
{901}{}{::Zvedá maketu pistole:: Ruce vzhùru, lumpové!}
{902}{}{Skákal pes, pøes oves, na velikou holku...}
{903}{}{Chci bıt pasák, a vyrostu.}
{904}{}{A vyrostu, budu šéfovat Renu, jako táta.}
{905}{}{Chci pejska. Táta øíkal, e dostanu dìvku, a vyrostu, ale nevím, co je to za plemeno.}
{906}{}{Škoda, e táta není tak fajn jako Tommy Tvrïák.}
{907}{}{Já mám penis.}
# self_is_male ^
{908}{}{::Vøísk::}
{909}{}{::Vyplazuje jazyk::}
{910}{}{Táta øíká mámì továrna na dìcka.}
{911}{}{Táta øíkal, e nás seøee, pokus se jenom dotkneme Jetu.}
{912}{}{Táta øíká, e si máme venku dávat pozor.}
{913}{}{Táta nás zbije, jestli ještì jednou uteèeme do pouštì.}
{914}{}{Táta je strašnì naštvanej od tı doby, co umøel brácha Richie.}
{915}{}{Táta zase kšeftuje.}
{916}{}{Zajímalo by mnì, proè Otec Tully nemùe chodit rovnì.}
{917}{}{Prší prší jen se leje...}
{918}{}{Poèùral jsem se.}
{919}{}{Chybí mi bráška Richie. Umøel, protoe bral moc Jetu.}
{920}{}{Christophera vidím strašnì málokdy.}
{921}{}{Vidìl jsem Mikyho, jak líbá  Mareee Mor-dino.}
{922}{}{Vidìl jsem, jak na sobì táta s mámo tancují.}
{923}{}{Škoda, e si s námi Christopher nehraje.}
{924}{}{Kyle pije vlastní èùránky!}
{925}{}{Kyle má støíkaèku.}
{926}{}{Tá dy dá dy dáááá.}
{927}{}{Podívej se na mnì! Podívej se na mnì!}
{928}{}{Mikey a Mareee sedìli za stromem a L-Í-B-A-L-I se!}
{929}{}{Milicent je lump.}
{930}{}{Cukr káva limonáda, cukr káva limonáda... }
{931}{}{Máma a táta mluvili vèera veèer v posteli s bohem.}
{932}{}{Máma breèela celı den. Asi kvùli tomu, co se stalo Richiemu.}
{933}{}{Máma je fakt smutná od tı doby, co umøel Richie.}
{934}{}{Máma je zase v kostele.}
{935}{}{Naše rodina je nejlepší!}
{936}{}{Phfttttt}
{937}{}{Hlupák! Hlupák!}
{938}{}{Strejda Nick øíká, e nadávání není nutnı. Mìl by obèas vylézt z baráku, moná by dostal rozum.}
{939}{}{Zahrajeme si na divochy a otrokáøe?}
{940}{}{Máme sedmnáct bratrù a sester.}
{941}{}{Wheeeeeeee}
{942}{}{To seš ty!}
{943}{}{Hmm, ty se mi vùbec nelíbíš!}
{944}{}{Vypadáš jako škorpión!}
# self_is_female v
{945}{}{Chci se zeptat tatínka, jestli mùu bıt kurva, a vyrostu. Øíkal, e opravdu jednu potøebuje.}
{946}{}{Chci bıt kurva, a vyrostu. Táta øíká, e jich nemá dost.}
{947}{}{Já mám vagínu.}

# line endings
{1176}{}{! Povìz nám o Enklávì! Prosííííím?}
{1177}{}{! Jaaaaaj!}
{1178}{}{!}
{1181}{}{ a vyrostu.}
{1296}{}{dá: Mùeš bıt COKOLI co chceš, a vyrosteš.}
{1310}{}{. NIKDY na tebe nezapomenu.}
{1311}{}{ rád e ty rád já. Já rád e já zachrániš ty}
{1315}{}{. Nikdy nezapomenu, i kdybych il do sta.}
{1320}{}{? Smaeš nás z harddisku, kdy u hra skonèila?}
