#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
# QUICK LOOK
{100}{}{Vidíš jednoho z Wrightovıch synù.}
{101}{}{Vidíš jednu z  Wrightovıch dcer.}

# 0. LOOK [MALE]
{150}{}{Vidíš mladého mue s rozzlobenım vırazem na tváøi. Snaí se vypadat tvrïácky.}
{151}{}{Vidíš jednoho z Wrightovıch synù. Na svùj vìk sebou tahá trochu moc zbraní. Snad si s nimi neublíí. }
{152}{}{Vidíš jednoho z Wrightovıch synù. Zírá na tebe, ale moc mu to nejde.}
{153}{}{Vidíš jednoho z Wrightovıch synù. Vypadá, e by byl radši nìkde úplnì jinde.}
# 1. LOOK [FEMALE]
{160}{}{Vidíš mladou enu s vánou tváøí. Snaí se vypadat tvrdì.}
{161}{}{Vidíš jednu z Wrightovıch dcer. Na svùj vìk sebou tahá trochu moc zbraní. Snad si s nimi neublíi. }
{162}{}{Vidíš jednu z Wrightovıch dcer. Ignoruje tì, ale ruku má tìsnì u pouzdra se zbraní.}
{163}{}{Vidíš jednu z Wrightovıch dcer. Vypadá nebezpeènìji ne nasranı chøestıš.}
{164}{}{Vidíš jednu z Wrightovıch dcer.  Vypadá nebezpeènìji ne nasranı chøestıš. Z nìjakého dùvodu tì to rajcuje.}

# 2. CLICK/FLOAT DIALOGUE: ENCLAVE DESTROYED IS TRUE
{200}{}{::Zdraví::}
{201}{}{::Tleská::}
{202}{}{::Píská::}
{203}{}{(Zpívá.) "We don't need another hero, we don't need to know the way home..."}
{204}{}{Hej! }
{1204}{}{Nakopej Enklávì prd...eh, zadky!}
{205}{}{Dostals Enklávu, }
{1205}{}{. Na to musí mít jeden fakt poøádnou odvahu.}
{206}{}{Musíš bıt tvrdìjší ne Tommy Tvrïák, jinak by to s Enklávou nedopadlo tak špatnì.}
{207}{}{Ti z Enklávy museli bıt pìknì tvrdí lumpové, co.}
{208}{}{Chtìli vypustit do vzduchu nìjakı novı VIRUS? Bastardi. Doufám, e jsou všichni mrtví.}
{209}{}{Døív jsem si myslel, e Prezident je jenom pohádka na strašení malıch dìtí.}
{210}{}{Vypadáš, jako bys pøišel z pekla. Relaxuj, odpoèiò si. Zaslouil sis to.}
{211}{}{Budeš hrát hru znova za jinou postavu? Doporuèuju skauta nebo diplomata.}
{212}{}{F.E.V.? Co je to?}
{213}{}{New Reno designoval Chris Avellone, scénáøe psal Tom French a do zatracené èeštiny pøekládal Birdman. Tom hraje v hudební skupinì, Chris si hraje sám se sebou a Birdman hraje Fallouta 3.}
{214}{}{Doufám, e ve Falloutu 3 dostanu nìjakou hlavní roli, jako tøeba Tandi nebo Ian. Bıt jenom postavièka, co stojí, øekne pár vìt a nìkdy si vystøelí, to je dost o nièem. }
{215}{}{Prı jsi znièil Enklávu. Uau.}

# 3. FLOAT DIALOGUE: POWER ARMOR
{225}{}{Jak chodíš na záchod s tou vìcí na sobì?}

# 4. FLOAT/CLICK DIALOGUE: PLAYER = FEMALE/MALE, MADE MAN, FA=WRIGHT [ARMED]
{230}{}{Nepøedvádìj se s tou zbraní pøed dìckama, okej?}
{231}{}{Neukazuj to elezo pøed dìckama, dobøe?}

# 5. FLOAT/CLICK DIALOGUE: PLAYER = FEMALE/MALE, MADE MAN, FA=WRIGHT [SNEAK]
{235}{}{Sakra, neplaz se tady tak kolem! Málem si chytl kulku!}
{236}{}{Co blbneš? Nìkdo tì hledá?}
{237}{}{Hej! Pøestaò si hrát na stín... nìkdo se splete a pošle ti kulku do hlavy!}

# 6. FLOAT/CLICK [MALE, MADE MAN, FA = WRIGHT, NORM]
{240}{}{Nazdar, }
{1240}{}{. Na co se chystáš?}
{241}{}{Zatracenı hic, co,}
{1241}{}{?}
{242}{}{Nazdárek, }
{1242}{}{. Jak se vede?}

# 7. FLOAT/CLICK [MALE, MADE MAN, FA = NOT WRIGHT, ARMED]
{245}{}{To je jeden z rodiny }
{1245}{}{! Má zbraò! Zavolejte ostatní!}

# 8. FLOAT/CLICK [FEMALE, MADE MAN, FA = NOT WRIGHT, ARMED]
{250}{}{To je jedna z rodiny }
{1250}{}{! Má zbraò! Zavolejte ostatní!}

# 9. FLOAT/CLICK [MALE/FEMALE, MADE MAN, FA = NOT WRIGHT, SNEAK]
{255}{}{To je nìkdo od rodiny }
{1255}{}{ a snaí se chovat nenápadnì! Urèitì chystá nìjakou boudu! Zavolejte ostatní!}

# 10. FLOAT/CLICK [MALE/FEMALE, MADE MAN, FA = NOT WRIGHT]
{260}{}{Vypadni odtud, nebo ti bude cedník øíkat brácho!}
{261}{}{Vypadni! Ani ty ano tvoje povedená rodina tady není vítaná!}

# 11. FLOAT/CLICK [SLAVER, ARMED]
{265}{}{Odhoï zbraò, otrokáøi, nebo zaèneme støílet!}

# 12. FLOAT/CLICK [SLAVER, SNEAK]
{270}{}{Co se tady sakra plazíš, ty otrokáøskı hajzle?! Chceš dostat kulku mezi oèi?}

# 13. FLOAT/CLICK [FEMALE/MALE, PRIZEFIGHTER/PORN STAR/NO REP, ARMED]
{275}{}{Odlo tu zbraò! Hned!}
{276}{}{Odhoï zbraò, nebo budeme støílet!}
{277}{}{Odlo zbraò, nebo budeme støílet!}

# 14. FLOAT/CLICK [FEMALE/MALE, PRIZEFIGHTER/PORN STAR/NO REP, SNEAK]
{280}{}{Proè se tady plazíš? Nìkdo tì zastøelí, jestli budeš takhle strašit lidi.}
{281}{}{Co to kur... eh sakra dìláš? Proè se tady plazíš jako zlodìj? Chceš, aby tì nìkdo støelil?}

# 15. FLOAT AND CLICK (ANY) TO [COMPANION: ROBOBRAIN]
{285}{}{To je nìjakej vıherní automat, ta vìc za tebou?}
{286}{}{To je pojízdnej automat? Uau!}
{287}{}{Hele, tam v tı jezdící bedınce je... mozek??}
{288}{}{Pojízdná piksla na mozek? Od koho je ta mozkovna?}
{289}{}{To je robot? Poprvı vidím nìco takovıho.}

# 16. FLOAT (ANY) TO [COMPANION: MARCUS]
{295}{}{Hele, není támhleto náhodou mutant?}
{296}{}{To je mutant?}
{297}{}{Hrome! Mutanti v Renu! To smrdí problémem...}
{298}{}{Ten mutant je poøádnı kus chlapa.}
{299}{}{A si ten tvùj mutant radši dává bacha, jasnı?}

# 17. FLOAT/CLICK [FEMALE/MALE, NORM]
{305}{}{Co chceš?}
{306}{}{Potøebuješ  nìco?}
{307}{}{Zatracenı hic...}
{308}{}{New Reno je kadım dnem hnusnìjší a hnusnìjší...}
{309}{}{Co tady dìláš?}
{310}{}{Jestli chceš alkohol, jdi na sever k vlakové stanici...tady se neprodává.}
{311}{}{Dávej si bacha. Jsi na území Wrightù.}

# 19. CLICK DIALOGUE: POWER ARMOR
{320}{}{Dìcka jsou z toho tvého brnìní úplnì na vìtvi.}
{321}{}{Dej si pozor, a na nìkoho v té konzervì nešlápneš, okej?}
{322}{}{Není v tom horko?}
{323}{}{Chodící lednièka. Mì u nic nepøekvapí.}
{324}{}{Hledáš myèku aut?}
{325}{}{Pøipadáš mi, e patøíš do Battletechu nebo Earthsiege. Tohle je Fallout 2. Nespustils špatnı soubor?}
{326}{}{Jak to dìláš v té vìci na záchodì?}

# 20. CLICK [FEMALE/MALE, MADE MAN, FA = WRIGHT OR PRIZEFIGHTER]
{335}{}{Jak se máš, }
{1335}{}{? ádné problémy?}
{336}{}{Je dobøe, e patøíš do rodiny, i kdy vlastnì nejsi v rodinì, uh, no však mi rozumíš.}
{337}{}{Tommy Tvrïák je prı ve mìstì. Dej si na nìj bacha.}
{338}{}{My Wrightové jsme nejsilnìjší rodina, protoe my JSME rodina.}
{339}{}{Škoda malıho bratøíèka. Byl to fajn kluk, ale Jet je všude, tìko se mu vyhıbá...}
{340}{}{Táta øíkal, e jestli se nìkdo z nás jenom dotkne Jetu, roztrhne ho jako hada.}
{341}{}{Táta je poøád naštvanej, tak si dej pozor, a ho nenaštveš ještì víc.}
{342}{}{Chris dostane náøez, jestli bude poøád chodit do bordelu. A ho táta jednou chytí...}
{343}{}{Zatracenı hic...}
{344}{}{Kde je ta máma? Kdyby na tebe náhodou natrefila, neøíkej jí nic o destilaèce, okej?}
{345}{}{Keith je chytrej kluk. Minulı tıden rozebral piáno a pak ho zase poskládal.}
{346}{}{Zítra asi pùjdeme chytat radškorpióny. Je jich èím dál víc.}
{347}{}{Jestli chceš alkohol, jdi na sever k vlakové stanici...tady se neprodává.}
{348}{}{Dávej pozor na dìcka, pletou se lidem pod nohy...}
{349}{}{Nauèíš mì bojovat?}
{350}{}{Ty jsi ten bijec, }
{1350}{}{, e jo? V ringu jsi nejlepší.}
{351}{}{Bojuješ dobøe. Zkus se zeptat táty, jestli pro tebe nemá práci.}
{352}{}{Silné ruce by se nám hodily. Jestli máš zájem, zajdi za tátou.}
{353}{}{Kdy budeš zase bojovat?}
{354}{}{Vsadit na tebe je jasná vıhra, ale kdyby mì chytla matka...}
{355}{}{Seš jako ze eleza.}
{356}{}{Pozor na dímaèku. Je to poøádnı lump. Ukousne ti ucho, kdy si nedáš pozor.}

# 22. CLICK [PORN STAR]
{360}{}{Mám øíká, e jsi nástroj ïábla. Nebo e máš nástroj ïábla? Hmm, teï nevím...}
{361}{}{Radši zmiz. Jestli tì uvidí máma, bude mít kázání...}
{362}{}{Jaké jsou tvoje filmy? Máma nám zakázala dívat se na nì.}
{363}{}{Neøíkej dìckám, co dìláš.}
{364}{}{Máma se zblázní, jestli tì tady uvidí.}
{365}{}{Jestli chceš alkohol, jdi na sever k vlakové stanici...tady se neprodává.}
{366}{}{My Wrightové jsme nejsilnìjší rodina, protoe my JSME rodina.}
{367}{}{Škoda malıho bratøíèka. Byl to fajn kluk, ale Jet je všude, tìko se mu vyhıbá...}
{368}{}{Táta øíkal, e jestli se nìkdo z nás jenom dotkne Jetu, roztrhne ho jako hada.}
{369}{}{Táta je poøád naštvanej, tak si dej pozor, a ho nenaštveš ještì víc.}
{370}{}{Chris dostane náøez, jestli bude poøád chodit do bordelu. A ho táta jednou chytí...}
{371}{}{To je ale horko...}
{372}{}{Keith je chytrej kluk. Minulı tıden rozebral piáno a pak ho zase poskládal.}
{373}{}{Zítra asi pùjdeme chytat radškorpióny. Je jich èím dál víc.}
{374}{}{Fuj! jak mùeš natáèet takové prasárny.. teda aspoò máma øíkala, e to jsou prasárny...}
{375}{}{Mámá øíká, e jsi nástroj ïábla.}
{376}{}{Máma øíká, e jsi bìhna. Drzá dìvka. Co to vlastnì znamená?}

# 24. [FEMALE/MALE/, NO REP/SLAVER, REACTION NEUTRAL +]
{385}{}{Jdeš za tátou obchodnì? No, hodnì štìstí, není zrovna v nejlepší náladì.}
{386}{}{Jestli chceš alkohol, jdi na sever k vlakové stanici...tady se neprodává.}
{387}{}{Dávej si pozor, cizinèe. Jsi na území Wrightù.}

# 25. CLICK [SLAVER, BAD REACTION]
{390}{}{Radìji zmiz... nemáme rádi otrokáøe.}
{391}{}{A tì ani nenapadne zkusit tady nìkoho odvést. Zkus si nìco a odnesou tì nohama napøed.}
{392}{}{Dávej si pozor, otrokáøi. Jestli máš s tátou nìjakı obchod, tak sebou pohni a pak rychle zmiz.}
{393}{}{Jestli máš sebou nìjaké drogy, táta tì zabije.}
{394}{}{Dávám si na tebe pozor, otrokáøi. Zkus nìco a uvidíš ten mazec.}
{395}{}{Šáhni na nìkteré dìcko a já tì prostøílím jako cedník.}
{396}{}{Šáhni na nìkteré dìcko a umøeš.}
{397}{}{Jestli chceš alkohol, jdi na sever k vlakové stanici...tady se neprodává.}
{398}{}{Udìlej nìco nìkterému Wrigtovi a rovnou si rezervuj místo na Golgotì.}
{399}{}{Co tady chceš? Neobchodujeme s otrokáøskımi svinìmi.}

# 26. [FEMALE/MALE, NO REP, REACTION < NEUTRAL]
{410}{}{Radši zmiz...bez uráky, ale táta nemá divochy moc v lásce.}
{411}{}{A tì ani nenapadne dìlat nìjaké problémy. }
{412}{}{Dávej si pozor. Jestli máš s tátou nìjakı obchod, tak sebou pohni a pak rychle zmiz.}
{413}{}{Jestli máš sebou nìjaké drogy, táta tì zabije.}
{414}{}{Dávám si na tebe pozor, take a tì ani nenapadne dìlat nìjaké problémy!}
{415}{}{Odkud jsi? Nikdy jsem tu nikoho, jako jsi ty, nevidìl.}
{416}{}{Jestli chceš alkohol, jdi na sever k vlakové stanici...tady se neprodává.}
{417}{}{udìlej nìco nìkterému Wrigtovi a rovnou si rezervuj místo na Golgotì.}
{418}{}{Jdeš za tátou obchodnì? No, hodnì štìstí, není zrovna v nejlepší náladì.}

# 27. CLICK/FLOAT: LENNY
{425}{}{Ten ghoul tady nemá co dìlat, jasnı? Pošli ho pryè, nejlíp zpátky do Gecka.}
{426}{}{A se ten ghoul nepøibliuje k dìckám. Urèitì je radioaktivní.}
{427}{}{Myslím, e by bylo vhodné, kdybyste ty a tvùj ghoulí kámoš práskli do bot, ne vás odsud vyvedeme.}
