#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
{100}{}{Vítej v Novém Renu, nejvìtším malomìstì na svìtì. Ohnì v popelnicích a neonové poutaèe zaplavují mìsto ïábelskou záøí.}
{101}{}{Pøed tebou je vyschlá planina pokrytá hroby. Zkrvavené tyèe vyènívají ze zemì a pøidrují kusy lidskıch tìl nad zemí.}
{102}{}{Vypadá to jako stará pøedváleèná nabíjecí stanice. Budova je obklopena starımi, rozbitımi vraky aut.}
{103}{}{Pøišel jsi do Stájí. Novı drátìnı plot obklopuje vstup.}

{150}{}{[Pøedchozí]}
{151}{}{[Další]}

# family name
{201}{}{Salvatore}
{202}{}{Bishop}
{203}{}{Mordino}
{204}{}{Wright}

{221}{}{Salvatore's}
{222}{}{Shark Club}
{223}{}{Desperádo}
{224}{}{}


# made man name
{300}{}{}
{301}{}{Šepot}
{302}{}{Pavouk}
{303}{}{Svaloun}
{304}{}{Kantor}
{305}{}{Tygr}
{306}{}{Bık}
{307}{}{Kapitán}
{308}{}{Mlèoun}
{309}{}{Levák}
{310}{}{Pravák}
{311}{}{Správòas}
{312}{}{Tornádo}
{313}{}{Sprosák}
{314}{}{Opièák}
{315}{}{Vazba}
{316}{}{Bouchaè}
{317}{}{Dobrák}
{318}{}{Sekáèek na maso}
{319}{}{Brocco}
{320}{}{Dolar}
{321}{}{Romeo}
{322}{}{Masakrátor}
{323}{}{Havran}
{324}{}{Umlèovaè}
{325}{}{Kladivo}
{326}{}{Vıbìrèí}
{327}{}{Lámaè kostí}
{328}{}{Zelináø}
{329}{}{Hadí oko}
{330}{}{Vlk}
{331}{}{Sekerkáø}
{332}{}{Vysmátej}
{333}{}{Tlouštík}
{334}{}{Perla}
{335}{}{Reno Jimmy}
{336}{}{Šakal}
{337}{}{Zjizvenej}
{338}{}{Diamant}
{339}{}{Eso}
{340}{}{Jednookı Jack}
{341}{}{Nikki}
{342}{}{Ledovec}
{343}{}{Sly}
{344}{}{Hezoun}
{345}{}{Karlík}
{346}{}{Opium}
{347}{}{Dıka}
{348}{}{Andílek}
{349}{}{Zøízenec}
{350}{}{ralok}
{351}{}{Ohaø}
{352}{}{Reverend}
{353}{}{Magnum}
{354}{}{Ledoborec}
{355}{}{Gina}
{356}{}{Vicki}
{357}{}{Lovec}
{358}{}{Gilotina}
{359}{}{Mráz}
{360}{}{Valentino}
{361}{}{Rakváø}
{362}{}{Limonádovı Joe}
{363}{}{Ledová Královna}
{364}{}{Knoflík}
{365}{}{Jelen}
{366}{}{Prachy}
{367}{}{Šastlivec}
{368}{}{Svìtec}
{369}{}{Èíslo}
{370}{}{Kudlanka}
{371}{}{Škorpión}
{372}{}{Tlusoch}
{373}{}{Sam}
{374}{}{Zelená Drka}
{375}{}{Tommy Kvér}
{376}{}{Kalamity Jane}
{377}{}{Èerná Vdova}
{378}{}{Popeláø}
{379}{}{Devítipalcovej Nick}
{380}{}{Deštník}
{381}{}{King}
{382}{}{Zabiják}
{383}{}{Santana}
{384}{}{Joey}
{385}{}{Imperátor}
{386}{}{Mickey}
{387}{}{Král}
{388}{}{Vrahoun}
{389}{}{Øezník}
{390}{}{Èeèenskej Mafián}
{391}{}{Kmotr}
{392}{}{X}
{393}{}{}

# prizefighter name

{400}{}{}
{401}{}{Rypadlo}
{402}{}{Rotaèní Pìst}
{403}{}{Lokomotiva}
{404}{}{Hurikán}
{405}{}{Velkej Zlej Hajzl}
{406}{}{Vyvolenı}
{407}{}{Zuøící Bık}
{408}{}{Zakladatel}
{409}{}{Kladivo}
{410}{}{Sklenìnej Joe}
{411}{}{New Reno Nancy}
{412}{}{Plešatı Bık}
{413}{}{Princezna}
{414}{}{Duke}
{415}{}{Machoman}
{416}{}{elezná Panna}
{417}{}{Trhaè}
{418}{}{Valkıra}
{419}{}{Hák}
{420}{}{Sidewinder}
{421}{}{Zlá Holka}
{422}{}{Rocky}
{423}{}{Kamenná Stìna}
{424}{}{Motorová Pila}
{425}{}{Xena, princezna boxovnice}
{426}{}{Tommy Kvér}
{427}{}{Èerná Vdova}
{428}{}{Prásk}
{429}{}{Smrokvítek}
{430}{}{Blesk}
{431}{}{Jocco}
{432}{}{Ocelová Sestra}
{433}{}{Super Kladivo}
{434}{}{Apollo}
{435}{}{Šrotovaè Ocele}
{436}{}{Tygøice}
{437}{}{Tyson}
{438}{}{Lady J}
{439}{}{Drago}
{440}{}{Clubber Lang}
{441}{}{Vévodkynì}
{442}{}{Bulldozer}
{443}{}{Grace}
{444}{}{elezná Ruka Luke}
{445}{}{Víra}
{446}{}{Doktor Pìst}
{447}{}{Létající Bomba}
{448}{}{Balboa}
{449}{}{Smr}
{450}{}{Calamity Jane}
{451}{}{Kobra}
{452}{}{Krvavı Vrah}
{453}{}{Kat}
{454}{}{Vlak}
{455}{}{Super Vixen}
{456}{}{New Reno Jim}
{457}{}{Drtiè}
{458}{}{Rico}
{459}{}{Kladivoun}
{460}{}{Ovdovovaè}
{461}{}{Bouchnimì Ajátìzabiju}
{462}{}{Butch Coolidge}
{463}{}{Silver the Kocour}
{464}{}{Bad Mojo}
{465}{}{Tank}
{466}{}{Mlátièka}
{467}{}{Mynx}
{468}{}{Škorpión}
{469}{}{Pìstiè}
{470}{}{Gepard}
{471}{}{Andìl Zkázy}
{472}{}{Soudce Hák}
{473}{}{Zabiják}
{474}{}{Aténa}
{475}{}{Vzteklı Pes}
{476}{}{}

# special stupid names
{496}{}{Velkej Stu}
{497}{}{Miami}
{498}{}{X}
{499}{}{Tvoje jméno}

# porn star name
# male
{500}{}{}
{501}{}{Barbar Onan}
{502}{}{Randy Mercury}
{503}{}{Freddy Jakošutr}
{504}{}{Dick Vášnivec}
{505}{}{Pepe Rekce}
{506}{}{Phil Chambers}
{507}{}{Rod Sweat}
{508}{}{Jack Støelec}
{509}{}{Kurt Nakládaè}
{510}{}{Rick Kapka}
{511}{}{Dick Námoøník}
{512}{}{"Naleštìnı Kladivo"}
{513}{}{Doug Holes}
{514}{}{Kohout}
{515}{}{Vinnie Lasranda}
{516}{}{Sir Lance-a-lot}
{517}{}{Dick Hladkej}
{518}{}{Jakub Høebík}
{519}{}{Pan Rùovouèkej}
{520}{}{Ricky Šukman}
{521}{}{Cuthbert}
{522}{}{Dave Zruènej}
{523}{}{Harry Jakzbíjeèka}
{524}{}{Richie Milounkej}
{525}{}{Bret Svelkım}
{526}{}{El Pích}
{527}{}{Johnson Long}
{528}{}{Ebineezer Píchaè}
{529}{}{Herc-U-Les}
{530}{}{Arnold Èernejnegr}
{531}{}{}
{532}{}{}
{533}{}{}
{534}{}{}
{535}{}{}
{536}{}{}
{537}{}{}
{538}{}{}
{539}{}{}
{540}{}{}
{541}{}{}
{542}{}{}
{543}{}{}
{544}{}{}
{545}{}{}
{546}{}{}
{547}{}{}
{548}{}{}
{549}{}{}
# female
{550}{}{}
{551}{}{Ïáblice}
{552}{}{Mable Syrup}
{553}{}{Amber Vlnitá}
{554}{}{Lucka havá}
{555}{}{Anièka Vyvinutá}
{556}{}{Maruška Kopcová}
{557}{}{Slaïoušek Kozová}
{558}{}{Patty Nadrená}
{559}{}{Ofélie Odváná}
{560}{}{Thelma Vramihotamová}
{561}{}{Alotta Fagina}
{562}{}{Carrie C}
{563}{}{Georgia O'Queef}
{564}{}{Jill Jacks}
{565}{}{Hloubka Kurtizánová}
{566}{}{Maria Jáchcijová}
{567}{}{Lady J}
{568}{}{Glenda Glenn}
{569}{}{Královna Elizabeth}
{570}{}{Jenna Jammison}
{571}{}{Bunny LaJoya}
{572}{}{Madame Butterfly}
{573}{}{Jenny X}
{574}{}{Sladká Jane}
{575}{}{Drahoušek Nikki}
{576}{}{Sharonna}
{577}{}{Suzy Q}
{578}{}{Corvega Sally}
{579}{}{Pokeahotass}
{580}{}{Dominatrish}
{581}{}{Princezna X}
{582}{}{Carlotta}
{583}{}{Líbající Mary}
{584}{}{Chcitìteï Hnedová}
{585}{}{Xena, princezna milovnice}
{586}{}{Christie Chipps}
{587}{}{Lisa Lix}
{588}{}{Opium}
{589}{}{Lady Diana}
{590}{}{Monika Zezadu}
{591}{}{Sestøièka}
{592}{}{Dášenka Veškrnová}
{593}{}{Debbie Touha}
{594}{}{Jessica Long}
{595}{}{Mynx}
{596}{}{Saša Jeïsemnou}
{597}{}{Valerie Svatá}
{598}{}{Janièka Vlhká}
{599}{}{}

# other boxer names
{700}{}{Mal Fisto}
{701}{}{Tony Gunn}
{702}{}{"Ocelovı" Mark Torrance}
{703}{}{Xander "Jasná Rána" Holyland}
{704}{}{Pavouk}
{705}{}{Hubeòour}
{706}{}{Sladkej Jones}
{707}{}{Il Roche}
{708}{}{Tito}
{709}{}{Rudy}
{710}{}{Velkej George}
{711}{}{Gooch}
{712}{}{Tlustej Johnny}
{713}{}{Nicki}
{714}{}{LaMotta}
{715}{}{Ivan}
{716}{}{Sklenìnej Joe}
{717}{}{Drago}
{718}{}{Tommy Gunn}
{719}{}{Apollo}

{750}{}{Joqq}
{751}{}{Pete McKneely}
{752}{}{Evan Holyfeld}
{753}{}{dímaèka}

# GOING TO THE CHOP SHOP
{1000}{}{Jules tì vede ponièenımi ruinami kolem New Rena. Bez nìj by bylo hledání marné. Jakmile dorazíte na místo, Jules mizí.}
{1100}{}{Stopa tì vede do ruin u Nového Rena.}

# MORDINO/MYRON STASH
{1200}{}{Objevils malou kovovou pokladnièku. Bez znalosti pøesného místa by to bylo jako hledání jehly v kupce sena.}

# CODY/CHOP SHOP
{1300}{}{Cody tì vede do ruin za New Renem, pak utíká zpátky. Bez nìj se ještì teï nìkde motáš.}

# BOXING LEVELS
{1400}{}{První protivník poraen.}
{1401}{}{Druhı protivník poraen.}
{1402}{}{Tøetí protivník poraen.}
{1403}{}{dímaèka poraena!}
{1404}{}{Jsi Šampión Tìké Váhy Nového Rena.}

{1500}{}{Podaøilo se ti pøesvìdèit paní Wrightovou, aby znièila destilaèku.}
{1550}{}{Podaøilo se ti špehovat tajnou transakci.}

{1600}{}{V áru boje ti dímaèka ukousl ucho.}
{1700}{}{Vzteky bez sebe jsi ukousl dímaèkovi ucho.}
