#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
# MAP ENTEREANCE MESSAGE
{100}{}{Dorazili jste na pouštní planinu blízko Nového Rena.}

# 0. QUICK LOOK, BOXES (WTG)
{110}{}{Vidíš nìkolik beden plnıch chemikálií.}

# 0. LOOK, BOXES (WTG)
{120}{}{Vidíš nìkolik beden naplnìnıch chemikáliemi. Nepodaøilo se ti zjistit, co je to za chemikálie, ale jsou zabalené *velice* peèlivì.}

# 1. QUICK LOOK, VERTIBIRD (WTG)
{130}{}{Vidíš vertibird.}

# 1. QUICK LOOK, VERTIBIRD (WTG)
{140}{}{Vidíš vertibird...vylepšenı druh vrtulníku. Bohuel nemáš nejmenší ponìtí o tom, jak se takovı vertibird øídí.}

# 1. QUICK LOOK, VERTIBIRD (WTG)
{150}{}{Nemáš ponìtí, jak ho ovládat.}

# 2. NORMAL ACTION SEQUENCE (WTG)
{200}{}{(Z tìch chlápkù mi bìhá mráz po zádech...)}
{201}{}{(Dr hubu. U jdou..)}
{202}{}{*Zztttt* Máte zboí, které jsme poadovali? *Zzzttt**}
{203}{}{Ano, všechny chemikálie jsou tady. Mùete se ujistit.}
{204}{}{*Zztttt* To nebude nutné. *Zzzttt**}
{205}{}{*Zztttt* Víte, co se stane, pokud chemikálie nebudou splòovat specifikace, které jsme uvedli.*Zzzttt**}
{206}{}{Pøesnì tak. A, uh, pøinesli jste ty svìtelné pistole...?}
{207}{}{*Zztttt* Laserové zbranì jsou v našem nákladovém prostoru. *Zzzttt**}
{208}{}{*Zztttt* Abychom si zajistili vaši spolupráci, pøedáme vám pro nì zbrojní kódy, jakmile budou chemikálie naloeny. *Zzzttt**}
{209}{}{Uh...no...tak dobøe. Zaènìte nakládat, chlapci --}
{210}{}{*Zztttt* Ne. *Zzzttt**}
{211}{}{*Zztttt* My naloíme zboí. *Zzzttt**}
{212}{}{Uh, dobøe...fajn. Jistì. Uhnìte jim, chlapci.}
{213}{}{Fajn, tady jsme hotoví. Zbytek vás hlídaèù...ty taky, baante...bìte zpátky do Rena. Potkáme se tam.}

# 3. FLOAT SEQUENCE: INTRUDER (WTG)
{250}{}{Hele! Nìkdo nás sleduje!}
{251}{}{Zabte je!}
{252}{}{Vypadá to, e jsme dostali špióna...!}
{253}{}{*Zztttt* Mise zrušena. Zajištìní nákladového prostoru aktivováno. *Zzzttt**}
{254}{}{*Zztttt* Zlikvidujte nepøítele a vrate se na základnu. *Zzzttt**}

# 4. FLOAT SEQUENCE: OUT OF POSITION WARNING (WTG)
{300}{}{Nechoï k tìm obrnìncùm. Oddìlají tì.}
{301}{}{Vra se zpátky na místo.}
{302}{}{Pøestaò rady poskakovat...ti chlapci to moc rádi nemají.}

# 5. FLOAT SEQUENCE: OUT OF POSITION, FINAL (WTG)
{350}{}{Do prdele! Co to dìláš, kreténe?!}
{351}{}{Vra se zpátky na místo! Co to sakra dìl --?!}
{352}{}{*Zztttt* Mise zrušena. Zajištìní nákladového prostoru aktivováno. *Zzzttt**}
{353}{}{*Zztttt* Zlikvidujte nepøítele a vrate se na základnu. *Zzzttt**}

# 6. VERTIBIRD SEQUENCE: (WTG)
{400}{}{[Vypadá to, e tam jsou dveøe. Otevøít a vlézt dovnitø?]}
{401}{}{Jo}
{402}{}{Odejdi}
{403}{}{Vlez do vertibirda.}
{404}{}{Nech to bıt.}

# 7. VERTIBIRD: TAKE OFF (7)
{450}{}{[Dveøe se za tebou zavírají a vertibird startuje! Dveøe nejdou otevøít!]}
{451}{}{Ajajaj}
{452}{}{A kurva...}

# 8. DISPLAY TEXT: BOXES (WTG)
{500}{}{Bedny jsou naplnìny tìkımi kovovımi kanystry. Podle toho, s jakou opatrností jsou zabaleny, by se dalo odhadnout, e obsahují nìjaké nebezpeèné chemikálie. }

# GENERAL TALK
{550}{}{Teï zrovna není nejlepší èas na rozhovor.}
