#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
# 0. QUICK LOOK
{100}{}{Vidíš Myrona!}

# 0. LOOK [FEMALE, CHR > 5] (WTG)
{150}{}{Vidíš mladíka s tìstovitou tváøí, kterı po tobì chtivì pošilhává. Má mastné vlasy a lehce páchne po formaldehydu. }
{151}{}{Vidíš Myrona. Kradmì po tobì pokukuje.}

# 1. LOOK, NORMAL (WTG)
{200}{}{Vidíš mladíka s tìstovitou tváøí. Má mastné vlasy a lehce páchne po formaldehydu. }
{201}{}{Vidíš Myrona. Vypadá trochu jako tchoø.}
{202}{}{Vidíš Myrona. Posmrkává, jakoby mìl rımu.}
{203}{}{Vidíš Myrona. Nudí se.}
{204}{}{Vidíš Myrona. Zívá a protírá si oèi.}

# 2. OVERHEAD COMMENTS, PC = ARMED, SNEAK INTO MYRON'S  (WTG)
{210}{}{Zvednìte prdele a pojïte sem, bando. Máme tu vetøelce!}

# 3. OVERHEAD COMMENTS (WTG)
{215}{}{Co sakra chceš?}
{216}{}{Jestli seš tady pro Jet, tak si ho vem a zmiz.}
{217}{}{Nìco tady smrdí...}

# 4. OVERHEAD COMMENTS [FEMALE, CHR > 5 OR FEMALE PORN STAR] (WTG)
{225}{}{Áhóóój, krásko.}
{226}{}{Pojï si se mnou na chvíli povídat. Neboj, já nekoušu.}
{227}{}{No tak, pojï na chvíli ke mnì.}
{228}{}{Miluju ten pohyb, kterı dìláš zadeèkem, kdy chodíš.}
{229}{}{Chodíš tady èasto?}
{230}{}{Mmmm-mmmm. Ty nohy... zajímalo by mì, jak to vypadá na místì, kde se potkávají.}

# 5. COMPANIONS (BONE NOSE + MARCUS) (WTG)
{235}{}{Co je to za smrad? Smrdí to jako divoch.}
{236}{}{Fajn kost co má tvùj kámoš. Tres chic.}
{237}{}{Ten divoch, to je tvùj otrok?}
{238}{}{Ten tvùj lidoroutskı kamarád má nìjaké komplexy nebo co?}
{239}{}{Jak se sem ta vìc sakra dostala?}
{240}{}{Skvìlı. Teï u sem pouštìjí i mutanty.}
{241}{}{Nemá ten tvùj mutant rozvázanı tkanièky na botì?}
{242}{}{Ten mutant, to je tvùj otrok?}
{243}{}{Ten tvùj hnusnej mutantí kámoš, nasere se snadno?}
{244}{}{CO je to za smrad? Smrdí to jako mutant.}

# 6. COMPANIONS (LENNY) (WTG)
{255}{}{Co to smrdí? Jako by tu nìco zdechlo...}
{256}{}{Skvìlı. Teï u sem pouštìjí i ghouly.}
{257}{}{Ten ghoul by potøeboval poøádnì provìtrat. U je poøádnì vyzrálı. }
{258}{}{Ten ghoul, není radioaktivní?}
{259}{}{Hele, nechceš pomazat toho ghoula skunkem? Vonìl by líp.}

# 7. IF MYRON IS A COMPANION (NORMAL) (WTG)
{265}{}{Pùjdeme u nìkam, nebo budeme furt tvrdnout tady?}
{266}{}{Pojïme se podívat po nìjakıch nadrenıch kurvách.}
{267}{}{Co takhle zajít nìkam, kde je víc enskıch?}
{268}{}{Mùeš dìkovat nebesùm, e jsem poøád s tebou, i pøes ty debility co vyvádíš.}

# 8. I'M HURT (WTG)
{375}{}{Hej, já tady umírám! Tak dej mi sakra stimpak!}
{376}{}{To je moje krev?}
{377}{}{Medik!}
{378}{}{Auuuuuuu. Kurva! Auuu, to bolí!}
{379}{}{Au! To štípe!}
{380}{}{Auuuuuuuuuuuu Auuuuuuu Au. Au. Au?}
{381}{}{Auuuu. Kdyby mì tak NÌKDO obvázal. Ale fakt, je zbyteènı plıtvat drahım materiálem. Já stejnì za chvilku umøu, tak co.}

# 9. I'M BADLY HURT (WTG)
{390}{}{Dej mi kurva ten zjebanej stimpak, ne ti tady zdechnu!}
{391}{}{Dej mi doprdele stimpak! Jsem v šoku!}
{392}{}{Já chci první pomoc! Rychle, ne chcípnu!}

# 10. I'M POISONED (WTG)
{400}{}{Uau...jsem nìjakej slabej...}
{401}{}{Hmm...zvedá se mi aludek...zvıšenı tep...horeèka. Asi jed.}
{402}{}{Uh...u...dlouho...nevydrím...jed...se...rozšiøuje...}
{403}{}{Nemùe mi nìkdo ten jed aspoò vysát z rány?}

# 11. I'M IRRADIATED (WTG)
{410}{}{Hele, já svítím! Pøíštì mi dej nìjakej RadX, a se zase budeme plazit v radioaktivním prachu, oukej?}
{411}{}{Potøebuju pár antiradiaèních tabletek, ne mì ta radiace rozeere na sraèky.}
{412}{}{Proè se pøíštì nenapijeme radioaktivního slizu? Aspoò si zkrátíme utrpení.}
{413}{}{S tou radiaci, co ve mnì pobíhá, bych mohl osvìtlovat celé Reno.}
{414}{}{Svítím víc ne Reno o pùlnoci. Nemá nìkdo tabletky proti radiaci?}
{415}{}{Skvìlı. Ještì chvilku, a budu svítit jako baterka.}
{416}{}{Pùjète mi pár antiradiaèních tabletek. Neseeru je všechny, fakt ne.}

# 12. I DON'T LIKE THIS PLACE (WTG)
{425}{}{Proè se nevrátíme na zaèátek, do prvního patra. Tam pobíhají jenom koboldi.}
{426}{}{Dobøe, e jsem hrával Draèí Doupì. Nauèil jsem se pár vìci o odvaze. Nic pro mì.}
{427}{}{Hoï mi Buffout. Asi ho budu brzo potøebovat.}
{428}{}{Skvìlı místo. Fakt, líbí se mi tady. Ale co kdybychom se šli podívat nìkam jinam?}
{429}{}{Oh, tohle je MNOHEM lepší, ne leet nìkde v bordelu, fakt... Pryè!}
{430}{}{Dobøe dobøe, já vím, e tam musíme, ale co kdybychom to omezili na pár sekund?}
{431}{}{Hele, nezajdeme sem radši pozdìji?}
{432}{}{Co tady sakra dìláme?}
{433}{}{Tohle místo mi likviduje morálku.}
{434}{}{A já øíkám, pošlem Kostìnıho Nosa, a to prozkoumá. Samotnıho pochopitelnì.}
{435}{}{Proè nepošlem Kostìnıho Nosa na prùzkum?}

# 13. I DON'T LIKE THIS PLACE (WTG)
{445}{}{Hele, proè nepošlem Marcuse, aby to oèíhnul?}
{446}{}{A já øíkám, pošleme tam Marcuse, a to tam proleze. Samotnıho pochopitelnì, my bychom mu jenom pøekáeli.}
{447}{}{Hoï mi Buffout. Asi ho budu brzo potøebovat.}
{448}{}{Proè se nevrátíme na zaèátek, do prvního patra. Tam pobíhají jenom koboldi.}
{449}{}{Dobøe, e jsem hrával Draèí Doupì. Nauèil jsem se pár vìci o odvaze. Nic pro mì.}
{450}{}{Skvìlı místo. Fakt, líbí se mi tady. Ale co kdybychom se šli podívat nìkam jinam?}
{451}{}{Oh, tohle je MNOHEM lepší, ne leet nìkde v bordelu, fakt... Pryè!}
{452}{}{Hele, vpadnem tam, vypadnem odtamtud a bude, ne?}
{453}{}{Hele, nezajdeme sem radši pozdìji?}
{454}{}{Co tady sakra dìláme?}
{455}{}{Tohle místo mi likviduje morálku.}
{456}{}{A já øíkám, pošlem tam Lennyho, a to prozkoumá. Samotnıho pochopitelnì.}
{457}{}{Proè nepošlem Lennyho na prùzkum?}

# 14. USE DRUGS ON MYRON (WTG)
{465}{}{Hej, díky. To bodlo.}
{466}{}{Není nic nad poøádnou dávku pøímo do íly, co?}
{467}{}{To neznamená, e jsme svoji, nebo jo?}
{468}{}{Nemáš ještì trochu trávy?}
{469}{}{Nechceš, abych ti podrel stimpaky?}
{470}{}{Ahhhhhhhhh.}
{471}{}{Ooooooohhh. Aaaaaaaah. Mmmmmm.}
{472}{}{Tohle miluju.}
{473}{}{Z drog jsme celej pixelovatej.}

# 15. USE JET ON MYRON (WTG)
{485}{}{Hej, tohle nechci! Nech si to pro závisláky!}
{486}{}{Hele, já se proletìt nechci. A ty taky ne. Radši to nìkde zahrabej. }
{487}{}{Proè to nedáš Kostìnımu Nosovi? Tomu by se to urèitì líbilo.}

# 16. USE JET ON MYRON W/MARCUS + LENNY (WTG)
{495}{}{Proè to nedáš Marcusovi? Tomu by se to urèitì líbilo.}
{496}{}{Hej, tohle nechci! Nech si to pro závisláky!}
{497}{}{Hele, já se proletìt nechci. A ty taky ne. Radši to nìkde zahrabej. }
{498}{}{Proè to nedáš Lennymu? Tomu by se to urèitì líbilo.}

# 17. USE SCIENCE SKILL (WTG)
{505}{}{Dobøe, dobøe. Jdu na to.}
{506}{}{Uhni, idiote. já na to pøijdu.}
{507}{}{To vypadá jednoduše. Uhni, okej?}
{508}{}{No problemo.}
{509}{}{Èas na mı  'kouzelnı prstíky' ...}

# 18. USE SCIENCE SKILL (SUCCESS) (WTG)
{515}{}{Bingo!}
{516}{}{Heuréka!}
{517}{}{Mám to!}
{518}{}{Myron, Myron! Dav šílí!}
{519}{}{Hej, nìco jsem našel.}
{520}{}{Hotovo. Finito.}
{521}{}{Lehèí ne jízda na kole. Nebo na tvé matce! Ha-Ha-Ha-Ha-Ha!}
{522}{}{Ano. Myron je -- Bùh Vìdy. Klaòte se, mí vìøící.}
{523}{}{Píp. Myron úspìšnì pouil schopnost VÌDA.}

# 19. USE SCIENCE SKILL (FAIL) (WTG)
{530}{}{Nic.}
{531}{}{Nada.}
{532}{}{Smùla.}
{533}{}{Sakra! Zkoušel jsem všechno...}
{534}{}{S tím nic nezvládnu.}
{535}{}{Nic jsem nenašel. Tentokrát.}
{536}{}{Moná e s nìjakıma mentatama bych to zvládl...mmmm. Mentaty.}
{537}{}{Mám nízkou schopnost. Potøeboval bych pár expíriencí, pak moná...}
{538}{}{Nic jsem nezjistil.}
{539}{}{Za takovıhle podmínek nemám šanci udìlat test inteligence úspìšnì.}
{540}{}{Píp. Myron neúspìšnì pouil schopnost VÌDA.}

# 20. GET OUT OF MY WAY (WTG)
{550}{}{Dobøe, dobøe! Pøestaò do mì sakra strkat!}
{551}{}{Pøestaò do mì strkat, nebo tì...no, radši do mì pøestaò strkat.}
{552}{}{Dobøe, tak promííííò.}
{553}{}{Dobøe. Ale pøíštì uhneš z cesty TY mnì.}
{554}{}{Já tu byl první, ale kdy na tom trváš...}

# 21. USE HEALING (WOUNDED) (WTG)
{560}{}{Nemusíš mi to øíkat dvakrát.}
{561}{}{K mımu vyléèení by se spíš hodilo trochu enskı lásky, jestli mi rozumíš.}
{562}{}{Ahhhhhhh. To je dobøe, e na stimpaky není závislost.}
{563}{}{Oooooh, jó. To je dobøe, e na stimpaky není závislost.}

# 22. USE HEALING (NOT WOUNDED) (WTG)
{570}{}{Nepíchej to do mnì, já jsem ókej.}
{571}{}{Nestarej se o mnì, já jsem v poøádku.}
{572}{}{Hej, nestarej se. Já jsem v poøádku. Ale ty stimpaky ti podrím, jestli chceš.}

# 23. WAITING (WTG)
{580}{}{Hej, chci se k tobì pøidat. No tak!}
{581}{}{Sorry, e sem byl takovı prase. Dej mi další šanci.}
{582}{}{U je mi z toho èekání blbì.}
{583}{}{Já se tak nudím. No tak, nechceš, abych to s tebou zase chvilku táhnul?}
{584}{}{Mìl jsem si vzít kníku, je tu dìsná nuda.}
{585}{}{Dál u èekat nebudu. Seberu se a vyrazím si sám.}

# 24. SPOUSE: FEMALE (WTG)
{590}{}{Take...Miria je fakt tvoje stará?}
{591}{}{Miria je docela fajn. Mohl bych...no, však víš...co ty na to?}
{592}{}{Tvoje enuška je fakt fajn kost.}
{593}{}{Take...ty a Miria. Je to s vámi váné,nebo...?}
{594}{}{Take...ty a Miria. Jste spolu nastálo, nebo je to jenom takovı volnı svazek?}
{595}{}{Nechceš si prohodit eny? Puèím ti svoji, jenom co si nìjakou najdu.}

# 25. WAITING TO JOIN, 2 (WTG)
{600}{}{Mùeme jít?}

# 26. VAULT CITY (WTG)
{605}{}{Co tady SAKRA dìláme?}
{606}{}{Všichni v tomhle mìstì by potøebovali hadici do zadku a dostat poøádnı klystır.}
{607}{}{Ve Vault City se cítím...jako v prdeli, kdy to mám øíct slušnì.}
{608}{}{Co je s Vault City, e se mi z nìj chce jít nìkam do rohu a blít?}
{609}{}{Kdy se vrátíme do Rena?}

# 101. STANDARD PARTY OPTIONS (WTG)
{615}{myn102b}{Take se vısost koneènì dostavila, co? Vìdìl jsem, e beze mì nevydríš. Potøebuješ mì.}
{616}{myn102a}{Take ses koneènì rozhodla, co kotì? Vím, e beze mì nemùeš vydret. Pøidám se k tobì.}
{617}{myn103a}{Jo, co je? Nevidíš, e pøemıšlím?}
{618}{myn103b}{Take si koneènì dostala rozum, kotì? Pochopilas, e já jsem pro tebe ten pravı?}
{619}{}{Nevypadáš moc dobøe, Myrone. Vyleè se.}
{620}{}{Poèkej tady, dokud se nevrátím.}
{621}{}{Schovej tu pistoli, ne si ublííš.}
{622}{}{Dr se blízko mnì.}
{623}{}{Asi bychom mezi sebe mìli vloit pár metrù volného prostoru, Myrone.}
{624}{}{Odstup kus,  Myrone. Bude to tak lepší pro nás oba.}
{625}{}{Mám na tebe nìjaké dotazy...}
{626}{}{Ne teï, Myrone. Mám pár otázek...}
{627}{}{Tak dobøe. Pospìš si, pùjdeme.}
{628}{}{Ne, zùstaò tady. Vrátím se pro tebe, slibuju.}
{629}{}{Nechám tì tady, a pokraèuješ v nic nedìlání.}
{630}{}{Myrone, tvoje ruka je ta "jediná" pro tebe.}

# 105. Gologatha
{640}{myn105_b}{Je to nìkde na Golgotì. Dám ti vìdìt, a pùjdeme kolem.}
{641}{}{Dobøe, Myrone.}

# 106. I HAD SOME QUESTIONS . . . (101, 108, 109, 112-131, 133-137, 143, 145-149, 151-154, 1001, 1003, 1004, 1005, 1006)
{645}{myn106}{Jo. Co chceš vìdìt?}
{646}{}{Povìz mi o Jetu.}
{647}{}{Mùeš udìlat nìjaké drogy?}
{648}{}{Nevypadáš zrovna nejlíp, Myrone. Zkus s tím nìco udìlat.}
{650}{}{Kde jsou ty Mordinovy ulitı prachy, o kterıch jsi pøed tím nìco povídal?}

# 107. TELL ME ABOUT JET (106, 244)
{655}{myn107a}{Ah, moje malé mistrovské dílko. Co s ním?}
{656}{myn107b}{To u jsme pøece probírali. Nejsem tvoje osobní databanka.}
{657}{myn107c}{To u jsme pøece probírali. Budu klidnì tvùj osobní milovník, ale ne tvoje osobní databanka.}
{658}{}{Jak jsi ho udìlal?}
{659}{}{Je na nìj nìjakı lék?}
{660}{}{Mùeš mi udìlat nìjakı Jet?}
{661}{}{Budeš mrtvola, jestli mi nepovíš, co chci vìdìt. Jak jsi udìlal Jet?}
{662}{}{Vyser se na ty kecy, Myrone. Je na Jet nìjakı lék?}
{664}{}{To radši znásilním aligátora, ne abych tì nechala se ke mnì jenom pøiblíit, Myrone.}
{665}{}{Myrone, 'osobní milovník' je ta poslední vìc, která by mì snad mohla napadnout.}
{666}{}{No, já jsem mìla spíš na mysli cviènı terè ne milovníka.}
{667}{}{To radši políbím Sulika, ne abych si vybrala tebe jako osobního milovníka. Uh...bez uráky, Suliku.}
{668}{}{To radši políbím Marcuse, ne abych si vybrala tebe jako osobního milovníka. Uh...bez uráky, Marcusi.}
{669}{}{Zapomeò na to, Myrone.}

# 108. HOW DID YOU DEVELOP IT? (107, 129, 137, 236)
{680}{myn108}{Uh, v mojí laborce. Další otázka?}
{681}{}{JAK jsi ho udìlal, chytrolíne?}
{682}{}{Zapomeò na to. Co takhle...}
{683}{}{Hmm, vidím, kam tohle vyptávání vede. Kašli na to, Myrone.}

# 109. HOW DID YOU DEVELOP IT, SMART GUY, 1? (108)
{690}{myn109}{Ah, Kriste. Dobøe. Kdy jsem pøed nìjakou dobou narazil na Mordinovce, pìstovali tady peyotlové kaktusy a prodávali to turistùm jako 'Záitek z Rena.' Totální sraèka.}
{691}{}{Pokraèuj.}
{692}{}{Zapomeò na to. Mám jiné otázky...}
{693}{}{Zapomeò na to.}

# 110. HOW DID YOU DEVELOP IT, SMART GUY, 2? (109)
{700}{myn110}{Myslím, starej pejotl? To vıkali indiáni. Nemá to ani dibec síly, jako tøeba stará kyselinka LSD.}
{701}{}{Uh, no a co Jet --?}

# 112. HOW DID YOU DEVELOP IT, SMART GUY, 3? (111)
{710}{myn112}{Navíc, pejotlovı trip je moc dlouhej. Zisky jsou v krátkım úèinku a vysokı závislosti. Jako tøeba barbituráty pøed válkou.}
{711}{}{Doufám, e tohle nìkam povede.}
{712}{}{Kdy to øíkáš.}
{713}{}{Barbituráty...jako koks, krek a tak?}
{714}{}{Myslíš barbituráty, jako tøeba koks nebo tak?}
{716}{}{Kašli na to, Myrone. Nemám èas na tvoje zdlouhavı kecy. Táhneš se jako zácpa.}

# 113a.
{725}{myn113a}{Pøesnì. Mùu pokraèovat? }
{5725}{}{Fajn. A v èem je problém s vırobou starıch dobrıch barbiturátù?}

# 113b. CONTINUE 1 . . . (112)
{726}{myn113b}{Problém je, e máme novı klima, a v tom neroste vìtšina zeleninky, ze kterıch se dìlaly nejlepší drogy.}
{727}{}{Ty se rád posloucháš, co?}
{728}{}{Pokraèuj.}
{729}{}{Zeleninka, to jako myslíš koku, mák, takovı vìci?}

# 114A.
{740}{myn114a}{Nemùeme pìstovat ani koku, ani mák -- a e jsme to zkoušeli -- take jsme pøišli na to, e nejlepší bude vsadit si na houby.}
{741}{myn114b}{Pøesnì tak, šerloku. Zkoušeli jsme to -- ani uk. Take jsme pøišli na to, e nejlepší bude vsadit si na houby.}
{5741}{}{Proè?}

# 114B. CONTINUE 2 . . . (113)
{742}{myn114c}{Mùeš jich vypìstovat kupy, kdy pouiješ brahmíní hovna jako hnojivo.}
{743}{}{Kdy mluvíš o hovnech...Pokraèuj.}
{744}{}{OK...}

# 115. CONTINUE 3 . . . (114)
{755}{myn115}{Halucinogeny jsou hezkı, ale poøád to nebylo ono. Take jsem zaèal experimentovat s kyselinou lysergovou, diethylamidovou a psilocybinem. Ale poøád...}
{756}{}{Poøád...?}

# 116. CONTINUE 4 . . . (115)
{765}{myn116}{Poøád, chtìl jsem udìlat poøádnou bombu, která by nebyla zaloená na extraktech z rostlin. Byl jsem poøádnej idiot, protoe odpovìï nebyla v rostlinách, ale v tom, v èem rostly.}
{766}{}{Tebe vùbec nezajímá, co ti øíkám, co? Ty prostì miluješ, kdy si mùeš hrát na chytráka, co?}
{767}{}{Co tím myslíš?}

# 117. CONTINUE 5. . . (116)
{775}{myn117}{Víš, starej Jeíš Mordino chtìl nìco, na èem budou horníci z Reddingu rychle závislí. A co je donutí dìlat ještì víc. Take, øek sem mu 'no problemo,' jasnı?}
{776}{}{Co to bylo s tím Reddingem?}
{777}{}{Co e to bylo s tím Reddingem?}
{778}{}{Jo. Pokraèuj.}
{779}{}{Jo, no problemo.}

# 118. CONTINUE 6 . . . (117, 120)
{790}{myn118}{No, nebylo moc tìkı najít správnı vylepšovák. Vzorek pøedváleèného proteinového extraktu, pár úprav, a BUM-- máme slušnı amfetamin.}
{791}{}{Vysvìtli mi to s tím Reddigem, okej?}
{792}{}{Uh, "proteinovı extrakt?"}

# 119. EXPLAIN TO ME ABOUT REDDING AGAIN (117, 118)
{800}{myn119}{Redding? To je mìsto plnı zlatokopù. Mordino jim chce všem šéfovat. Tak pøišel za mnou a sípá tím svım hlasem: 'Myrone, Myrone, udìlej mi nìco, co mi dá Redding.'}
{801}{}{A tys øek...}

# 120. EXPLAIN TO ME ABOUT REDDING AGAIN (119)
{810}{myn120}{A já øíkám, 'okay, kolik èasu mám?' A on øek - pochopitelnì - 'vèera bylo pozdì.' Mafiáni. Chcou všechno hned. Aspoò e nemají marketingovı oddìlení.}
{811}{}{Aha. Vra se k Jetu.}

# 121. PROTEIN 1? (118)
{820}{myn121}{Pøed válkou nìkteré spoleènosti, co kšeftovaly s masem, experimentovaly s levnım proteinovım extraktem na zvıšení produkce rádla, ale podìlali to. Jedna malá bakterie jim kontaminovala vırobní vzorku, a bylo to všechno v prdeli.}
{821}{}{V prdeli? Jakto?}

# 122. PROTEIN 2? (121)
{830}{myn122}{Kontaminovaná verze se chovala po serání jako amfetamin. Drobnı vedlejší efekt. neptej se mnì proè. Je to trochu 'technické'.}
{831}{}{Take...jak ses dostal k tomu proteinovému extraktu?}

# 123. PROTEIN 3? (122)
{840}{myn123}{Nemusel jsem ho vùbec hledat. Kdy to poprvé posrali, kontaminovali tuny tìch sraèek. A ne aby to vyhodili, nakrmili s tím brahmíny, aby se jim ztráty aspoò trochu vrátily.}
{841}{}{Uh, okay...}
{842}{}{Doufám, e to nìkam vede, Myrone.}
{843}{}{Take jsi pouíval brahmíní hovna jako hnojivo pro ty houby, a na to, e ten pøedváleènı extrakt dává houbám ...speciální pøíchu?}

# 124A. PROTEIN? (123)
{850}{myn124a}{Pøihoøívá...}
{5851}{}{Ano...?}

# 124B. PROTEIN? (123)
{851}{myn124b}{Víš, kdy jsem zaèal experimentovat s brahmíníma hovnama jako hnojivem, všimli jsme si, e otroci, kteøí pracovali u hub, byli zfetovaní z vıparù...}
{853}{}{Take ten efekt staèily vytvoøit u vıpary??}

# 125A. PROTEIN? (124)
{860}{myn125a}{Pøesnì...}
{5861}{}{To je mi jasnı.}

# 125B. PROTEIN? (124)
{861}{myn125b}{Kdy jsme do kádí nacpali tuny brahmíních sraèek, zjistili jsem, e vıpary dávají víc ne dost. Heureka. Doslova. Samozøejmì, museli jsme to testovat, abychom dostali ten správnı mix...}
{862}{}{Uh, kolik testování?}
{863}{}{Kolik pøesnì?}
{865}{}{Kašli na to, Myrone.}
{866}{}{To mi zní jako hromada sraèek...doslova. Nevypadá to, jako bys vìdìl nìco o vırobì drog. "Vıpary z brahmíních hoven?" Prosím tì. U dost kecù.}

# 126. TESTING? (125)
{870}{myn126}{Hmmm...asi stovka otrokù? Vìtšinou infarkty, krvácení do mozku, psychotické záchvaty...takovéhle vìci.}
{871}{}{Ty jsi blázen! Zabil jsi stovku lidskıch bytostí jenom kvùli testování drogy?!}
{872}{}{Aha...Jet mùe bıt poøádnì silná potvora. Sice neumøel nikdo dùleitı, ale pøece jenom, tolik mrtvıch...}
{873}{}{Aha. Hele, jiná otázka...}

# 127. YOU KILLED A HUNDRED HUMAN BEINGS . . . (126)
{880}{myn127}{No, ne schválnì. Víš, otroci jsou dost drazí. Ale naštìstí jsme ztráty vyrovnali bìhem prvního mìsíce prodeje, take Mordinové na mì nebyli moc nasraní.}
{881}{}{Myslím, e mi dva budeme spolu vycházet, Myrone. Úèel svìtí prostøedky. Ale chci se tì ještì zeptat...}
{882}{}{Myrone, ty jsi neuvìøitelnı mizera. Zabíjet lidi kvùli testování drog...to je nevìtší sviòárna jakou kdy svìt vidìl.}
{883}{}{Myrone, ty jsi zabil pøes stovku lidskıch bytostí kvùli testování drog? Svìdomí ti vyoperovali u jako malému dítìti, co?}
{884}{}{Mì to povídej. Ceny otrokù lezou nahoru. Kdyby se jenom lidi mnoili rychleji. Ale já mám ještì pár otázek...}
{885}{}{Aha. Hele, mám ještì pár otázek...}
{886}{}{To u mi staèí, víc slyšet nechci.}
{887}{}{Aháááá. Tak TAKHLE je to. Dost. Uhni, já jdu pryè.}

# 128. OBJECTION . . . (127)
{890}{myn128}{Mám se posrat kvùli bandì otrokù? Hej, museli jsme si bıt jistí, e Jet nezabije ádného platícího zákazníka.}
{891}{}{No, to je pravda. Mám ještì jednu otázku...}
{893}{}{Oh, aha. Tak kdy je to TAKHLE... Gratuluju, Myrone. Dosáhl jsi nejhlubšího morálního dna, jakého mùe lidská bytost dosáhnout. Já jdu pryè. }
{894}{}{Aha, to zní rozumnì. Moná si popovídáme pozdìji.}

# 129. IS THERE A CURE? (107, 137, 236)
{900}{myn129a}{Zajímavé. Lék. Jistì. Mùeš si jít uívat absák. Samozøejmì, postaral jsem se, aby to s Jetem byl opravdu poøádnej absák.}
{901}{myn129b}{Hele, krásko. To je závislost na drogách, ne nìjaká chøipka nebo angína. Jedinı lék je pøestat brát Jet a uívat si absák. A ten je s Jetem jako prase.}
{902}{}{Jak jsi udìlal Jet?}
{903}{}{Myrone, jsi poøádnì mazanej parchant. Ber to jako profesionální vızvu. Jak by se dala vyléèit závislost na Jetu?}

# 130. YOU'RE PRETTY SMART . . . (129)
{910}{myn130}{Ah kurva, to nejde, jasnı? Je to zatracená droga, ne nìjaká bakteriální infekce.}
{911}{}{V základì je to meta-amfetamin, kterı vzbuzuje silnou závislost, ne? Nemohl bys pouít nìjaké tlumící prostøedky nervové èinnosti, abys zlomil závislost?}
{913}{}{Kašli na to, Myrone.}

# 131. IT'S BASICALLY A HIGHLY ADDICTIVE . . . (130)
{920}{myn131}{Hezkı nápad, ale nic z toho. Jet se nedá tak snadno vyblokovat. Jakmile je jednou v tvém systému, neodejde.}
{921}{}{A co takhle pouít nìjakı blokátor endorfinù? To by potlaèilo chemickou i psychologickou závislost, ne?}
{924}{}{Tak nic.}

# 132. WHAT ABOUT AN ENDORPHINE BLOCKER 1 . . . ? (131)
{930}{myn132}{Jeíši, to je ten nejblbìjší...hmmmm...}
{931}{}{Take?}

# 133. WHAT ABOUT AN ENDORPHINE BLOCKER 2 . . . ? (132)
{940}{myn133}{Hmm...moná by to fungovalo, ale jsem si jistı, e Jet by se pøes tu sraèku stejnì pøekousal. A proè se vùbec bavíme o takovém nesmyslu, jako je lék na Jet?! K-kde by se vùbec daly sehnat endorfinové blokátory?}
{941}{}{TO mi øekni ty, Myrone. Ty jsi tady chytrák.}

# 134. YOU TELL ME . . . (133)
{950}{myn134}{Moná ve Vault City. Mají docela dobrı sklad chemikálií. A spousta pøed-holokaustovıch základen je taky mìla na skladì kvùli potlaèení závislosti na bojovıch drogách.}
{951}{}{Tak proè nezkusíme Vault City?}
{952}{}{Pøed-holokaustové základny? Kde?}
{954}{}{Dobøe. Podíváme se po nich...}

# 135. VAULT CITY? (134, 136)
{960}{myn135}{Ha! To bys spíš ukecal radškorpióna, aby si nechal uøíznout ocas, ne pøesvìdèit Vault City, aby ti nìco dali.}
{961}{}{A co ty pøed-holokaustové základny? Kde jsou?}
{962}{}{Hmm, moná. Hele, ještì otázku...}
{963}{}{Za pokus nic nedám.}

# 136. PRE-HOLOCAUST BASES? (134, 135)
{970}{myn136}{Vypadám snad jako nìjakej kartograf? Jestli chceš proèesávat pouš a hledat je, máš monost.}
{971}{}{A co Vault City?}
{973}{}{Tak dík za nic, Myrone.}
{974}{}{Moná to udìlám.}

# 137. PUT-DOWN (107)
{980}{myn137}{Oooh...s takovım rozoumkem v hlavièce urèitì dostaneš rozum a budeš mì chtít, krásko. Uvidíš.}
{981}{}{Hmm. Jak jsi udìlal Jet?}
{983}{}{Jo, to se ještì uvidí. Mùeš mi udìlat nìjakı Jet?}
{985}{}{Zapomeò na to, Myrone.}

# 139. BUZZ-OFF, MYRON (1002)
{990}{myn139}{C-c-oooo? Dìláš si kurva srandu? Hej hej...kdy mì necháš jít s sebou, dám ti dobrı tip. Co øíkáš?}
{991}{}{Jakı tip máš na mysli?}
{992}{}{Zapomeò. A teï odpal, ty otravné hovado.}
{993}{}{Zapomeò. A teï poèkej tady, ty otravné hovado.}
{994}{}{Zapomeò na to. Mùeš zùstat.}

# 140. YOU CAN STAY (139, 1002)
{1005}{myn140}{Hoh! Ach, tak to byl jenom divošskej vtípek? Ha ha ha. Fak kurva sranda.}
{1006}{}{Jo, my divoši jsme tím proslulí. Pojï.}

# 141. OKAY, I'LL WAIT/I'LL LEAVE (139)
{1010}{myn141}{Dobøe! Dobøe! Poèkám tady. Ffff. Zaslouil bych si víc respektu, víš. Já jsem pøece MYRON.}

# 142. WHAT KIND OF FAVOR . . . (139)
{1020}{myn142a}{Slyšel jsem o tajné budovì obrostlé spoustou divné vegetace. Kdy budu s tebou, mùu ti jí ukázat na mapì.}
{1021}{myn142b}{Moná vím o jednom malém finanèním úkrytù Mordinovcù. Spousta penìz. Je to na Golgotì, u Rena.  Dr mì u sebe, a já tì k tìm penìzùm zavedu.}
{1022}{myn142c}{Já...já budu nosit víc vìcí!! ádné otravování, kdy budeš chtít drogy! Jen mì dr u sebe, oukej?}
{1023}{}{Oukej. Mùeš zùstat.}
{1026}{}{Zapomeò na to, Myrone. Poèkej tady na mnì.}

# 143. I NEED SOME DRUGS (106, 145-149, 151-154)
{1035}{myn143a}{"Mùeš udìlat nìjaké drogy?" Jsem Myron. Co chceš?}
{1036}{myn143b}{Copak, u ti došly? Co chceš?}
{1037}{}{Antidotum na radškorpióní jed.}
{1038}{}{Trochu Jetu.}
{1039}{}{Nìjaké stimpaky.}
{1040}{}{Mùeš udìlat super stimpak?}
{1041}{}{Nic, chci se tì jenom zeptat...}
{1042}{}{Nic, kašli na to.}

# 145. I NEED SOME RAD-SCORPION ANTIDOTE (NO TAILS) (143)
{1050}{myn145a}{Uhm, nejdøív potøebuju nìjaké škorpióní jedové váèky. Ironie, co?}
{1051}{myn145b}{Oh, xmrti rád bych ti vyhovìl, lásko, ale potøebuju škorpióní ocas. }
{1052}{}{Mùeš udìlat nìjaké jiné drogy?}
{1053}{}{Tak na to zapomeò. Chci se zeptat...}

# 146. I NEED SOME RAD-SCORPION ANTIDOTE (TAILS) (143)
{1060}{myn146a}{Hmmm, to by nemìlo bıt tìké. Kolik chceš?}
{1061}{myn146b}{Ah, teï øveš. Nenapadlo tì, e je lehèí vyhıbat se zasranım škorpiónùm, ne pak shánìt protijed? Kolik jich chceš?!}
{1062}{myn146c}{Pro tebe cokoli, lásko. Kolik jich chceš?}
{1063}{}{Jenom jeden.}
{1065}{}{Tøi budou akorát.}
{1066}{}{Udìlej protijedy ze všech ocasù, které máme. Stejnì na nic jiného nejsou.}
{1067}{}{Zapomeò na to. Mùeš udìlat nìjaké jiné drogy?}
{1068}{}{Ale radši nic. Chci se tì zeptat...}

# 147. FINISHED RAD-SCORPION ANTIDOTE (TAILS) (146)
{1081}{myn147a}{Hotovo. Tady máš.}
{1082}{myn147b}{Tady. Ale u víc ne, jasnı? Pøíštì si najdi nìjakého medicinmana, a ti je udìlá.}
{1083}{myn147c}{Hotovo. Tady máš, lásko.}
{1085}{}{Díky. Chci se tì ještì zeptat...}
{1086}{}{Díky, Myrone. Seš fakt kámoš.}

# 148. MAKE JET (107, 129, 137, 143, 145)
{1095}{myn148}{Sorry, nemám "suroviny", které potøebuju. Ne e bych je chtìl.}
{1097}{}{Tak na to zapomeò. Mám ještì otázku...}
{1098}{}{Dobøe. Fakt dík, Myrone. MOC jsi mi pomohl.}

# 149. MAKE STIM-PACKS (143)
{1105}{myn149a}{Pohodièka bufetík. Kolik jich chceš?}
{1106}{myn149b}{Hej, génie. Nenapadlo tì, e je lehèí dávat si pozor a nestrkat nos do problémù, ne se pak látat stimama dohromady, co? Kolik jich chceš teï?}
{1107}{myn149c}{Staèí øíct kolik a kde je chceš mít, lásko.}
{1111}{}{Tolik, kolik mùeš z toho, co máme u sebe.}
{1113}{}{Mùeš udìlat nìjakı superstimpak?}
{1114}{}{Zapomeò na to. Mám ještì otázku...}

# 151. CAN'T MAKE STIM-PACKS (143)
{1125}{myn151}{Sorry, nemáme nic, z èeho by se dal udìlat stim. Potøebujeme xanderovej koøen, rockflower a prázdnou støíkaèku.}
{1126}{}{Mùeš udìlat nìjaké jiné drogy?}
{1127}{}{A superstimpak bys nedokázal?}
{1128}{}{Tak dobøe. Ale ještì by mì zajímalo...}

# 152. CAN'T MAKE SUPER STIM-PACKS (143, 151)
{1135}{myn152}{Samozøejmì e dokáu udìlat superstim, jenome nemáme všechny suroviny. Potøebuju nìjaké to zmutované jabko na kyslinu citrónovou, kapku Nuka Coly...a normální stimpak.}

# 153. MAKE SUPER STIM-PACKS (143, 151)
{1145}{myn153a}{Opakuj po mnì: Myron je génius. Kolik superstimù chceš?}
{1146}{myn153b}{A co takhle: Dávej. Si. Sakra. Pozor? Ne? Moc sloitı? Kolik jich chceš tentokrát?}
{1147}{myn153c}{Myron je pøipraven poslouchat tvé rozkazy, lásko. Kolik jich chceš?}
{1149}{}{Dej mi dva.}
{1151}{}{Udìlej jich tolik, kolik dokáeš z toho, co máme u sebe.}

# 201. INTRO (WTG)
{1170}{myn201a}{Kdo seš a kde se tady sakra bereš? Kde jsou ti kreténi, co mì mají hlídat?}
{1171}{myn201b}{Ahóój, krásko! Co ti, uh, pro tebe mùe Myron udìlat?}
{1172}{}{Nuh-uh.}
{1173}{}{Ahóój Moron. Ja }
{1174}{}{Mrtvej.}
{1175}{}{Slaby lidy u dvéøé nédychaji dy ja dìlam bum bum jim}
{1176}{}{èau èau}
{1177}{}{Tvoji stráci mají teï dost práce s posmrtnım ivotem.}
{1178}{}{Mám tady ten prùkaz. Poslala mì Marjorie.}
{1179}{}{Kdo jsi?}
{1180}{}{Ty seš Myron?}
{1181}{}{Klídek, tygøe. Zklidni hormony. Kdo jsi.}
{1182}{}{Klídek, tygøe. Zklidni hormony. Ty seš Myron?}
{1183}{}{Sorry. Špatná místnost.}

# 202. BADGE (201)
{1195}{myn202}{No. Kdo jsi? Mluv, nebo nechám hlídaèe, a to z tebe vymlátí.}
{1196}{}{Tvoji stráci mají moc práce s posmrtnım ivotem, take tì asi neposlechnou. Ještì další otázky, ty pravá sraèko?}
{1197}{}{Kdo jsi?}
{1198}{}{Ty jsi Myron?}
{1199}{}{Mám dojem, e nejlepší bude, kdy se seberu a odejdu pryè. Mìj se.}

# 203. RETARD THREATENS (201)
{1205}{myn203}{Skvìlı. Mentální pøípad utekl. Hele, moc toho tady nemám, ale mùeš si v-v-vzít, co chceš.}
{1206}{}{JÁ CHCI TY. MRTVÁ}
{1207}{}{Chci šesko. hned}
{1208}{}{kdó tı? tı kámoš vot }
{6208}{}{?}
{1209}{}{èááu}

# 204. GIVE ME EVERTHING (203, 210, 212, 214)
{1215}{myn204}{Jasnì! Tady máš, ber si to. To je všechno. A teï bì zpátky do stáje, okej?}
{1216}{}{Ne ne. zabiju.}
{1217}{}{Kdó tı? Tı kámo vot }
{6218}{}{ jít}

# 205. HOO YOO? YOU FRIEND OF [x]? (203, 204)
{1225}{myn205}{Pøesnì kurva tak! Na to si vsaï! My dva budeme nejlepší kamarádi, e jo?}
{1226}{}{Lhát? }
{6226}{}{ ZABIJEŠ}
{1227}{}{Kamrát dá šesko }

# 207. HELL-OOOOO MORON, ME [x] (201)
{1235}{myn207}{Samozøejmì e jsi. Posaï se na postel. Mùu ti pøinést nìco k pití... nebo moná trochu Jetu? }
{1236}{}{posádit. pytí.}
{1237}{}{Tı pitél?}

# 208. OKAY ME HAVE SOME OF THOSE ME GUESS ME HAVE RUFF DAY (207, 210)
{1245}{myn208}{Vıbornì...tady máš. Malı drink ti pomùe uvolnit se, jestli víš, co tím myslím?}
{1246}{}{trink}
{1247}{}{ty }
{6247}{}{kámoš?}

# 209. [x] HAVE TO GO NOW . . . (207, 208)
{1255}{myn209}{Uh, hej, hej, hej! Poèkej minutku. Zùstaò - dej si drink! Mùeme si popovídat, spøátelit se...Chceš, abychom byli pøátelé, ne?}
{6256}{}{ pít}
{6257}{}{ pítel?}

# 210. YOU BE [x]'S FRIEND (207, 208, 209)
{1265}{myn210}{Jsem si jistı, e budeme pøátelé. }
{1266}{}{Chceš pítel.}
{1267}{}{Pítel dáš šecko. Hnet.}

# 211. TAKE DRINK (208, 209)
{1275}{myn211}{Tak, a teï odpoèívej, bonbónku...}
{1276}{}{Dóbroooooo zzzz Zznnzznn Zzznnnzzzz}

# 212. TAKE DRINK (CON RESISTANT) (208, 209)
{1285}{myn212}{Hmmmm. Máš vıdr jako prase. Vypadni, holèièko. }
{6287}{}{ jít.}

# 213. ME SEE NO ASS JACKALS (201)
{1295}{myn213}{Hlídaèi dneska nestojí za nic, a pøitom stojí tolik penìz.... tak, mùj retardovanı pøíteli, byli jsme navzájem pøedstaveni, tak PROÈ SAKRA HNED NEVYPADNEŠ! }
{1296}{}{Aù UŠI. ZABIJEŠ.}
{1297}{}{Ne kámrat?}
{6298}{}{ jdeš }

# 214. YOU FRIEND? (210, 212, 213)
{1305}{myn214a}{Jo, na to si vsaï, kámo. }
{1306}{myn214b}{Jo, na to si vsaï, zlatíèko. }
{1307}{myn214c}{Ty a já - pøátele a za hrob. Nebo do další injekce. A TEÏ SAKRA VYPADNI!}
{1308}{}{ty ne pítel. ZABIJEŠ.}
{1309}{}{pítel dá šesko. Hnet}

# 215. YOU'RE GUARDS ARE TOO DEAD TO BE WATCHING DOOR (201, 202)
{1325}{myn215a}{Do PRDELE! Øíkal jsem Jeíšovi, e ti dva kreténi by nemohli hlídat ani kus hovna. Je po nich, jo? A mì chceš taky zabít?}
{1326}{myn215b}{Uau! havá a smrtící! Tak si je sejmula, jo? A mì taky sejmeš? }
{1327}{}{Uvauju o tom. Máš nìco, co by mì mohlo pøesvìdèit, e to není nutné, chlapeèku?}
{1328}{}{Ne, pokud nebudeš dìlat problémy. Kdo jsi? }
{1329}{}{Ne, pokud nebudeš dìlat problémy. Ty jsi Myron?}
{1330}{}{Jo, proè ne? U pár vteøin kolem mì nikdo nezemøel, a to je pro mì velké duševní vypìtí.}
{1331}{}{Teï ne. Moná pozdìji. }

# 216. I'M THINKING ABOUT IT . . . (215)
{1345}{myn216a}{Jo, jistì, kámo. }
{1346}{myn216b}{Jasnì, dámo. }
{1347}{myn216c}{Na to si vsaï, krásko. s}
{1348}{myn216d}{J-já... mùu ti obstarat nìjaké drogy. Nechceš se proletìt? }
{1349}{}{Ve skuteènosti chci všechno, co máš. Dej mi to, a nechám tì ít. Prozatím. }
{1350}{}{Jasnì. Dej mi všechen fet, co máš. }
{1351}{}{Teï nic nechci, ale moná si to ještì rozmyslím. }

# 217. GIVE ME EVERYTHING (216)
{1365}{myn217}{Dobøe, dobøe. Tady máš. Teï u mì necháš na pokoji?}
{1366}{}{Ne. Kdo jsi.}
{1367}{}{Ne. Ty jsi Myron?}
{1368}{}{Jasnì. Prozatím...moná se ještì vrátím.}

# 218. WHO ARE YOU? (SMART) (201, 202, 215)
{1375}{myn218a}{M-moná. K-kdo sakra jsi? }
{1376}{myn218b}{Hele, jsi nová Mordinova kurva, nebo jenom velká fanynka boského Myrona? Oh, a mohl bych vìdìt, jak se jmenuje majitelka toho páru krásnıch noek?}
{1377}{myn218c}{Kdo sakra jsi? }
{1378}{myn218d}{Já jsem nìkdo, kdo u dlouho hledá nìkoho, jako jsi ty. A ty jsi...?}
{1379}{}{.}
{6379}{}{Jsem }
{1380}{}{Jenom procházím náhodou kolem.}
{1381}{}{Jsem nìkdo, kdo je ve špatné místnosti. Pozdìji.}

# 219. I'M [x]/I'M JUST A TRAVELER PASSING THROUGH (218)
{1395}{myn219a}{Tak takhle? Proè jsi tady? No? Pøišlo nám na rozum, e bychom mohli z Myrona vytáhnout nìjakı fet zadarmo?}
{1396}{myn219b}{Cokoli, krásko. Nechceš nìjakı fet, a prolomíme ledy, nebo si rovnou dáme soutì ve skocích v posteli?}
{1397}{}{Moná, ale nemám teï zbyteènıch deset sekund nazbyt. O jakıch drogách ses to zmínil?}
{1398}{}{Fet? Jako co?}
{1399}{}{Jsem urèitì ve špatné místnosti. Promiò.}

# 220. DRUGS? LIKE WHAT? (219)
{1405}{myn220a}{Hej blbèe! Jet, zkurvenèe, Jet! Mluvíš k jeho tvùrci. Jeho stvoøiteli. Jeho...Bohovi.}
{1406}{myn220b}{Jsi blbá? Jet, krávo, Jet! Mluvíš k jeho tvùrci. Jeho stvoøiteli. Jeho...Bohovi.}
{1407}{myn220c}{Slyšelas nìkdy o Jetu, krásko? Mluvíš k jeho tvùrci. Jeho stvoøiteli. Jeho...Bohovi.}
{1408}{}{Hovno. Ty jsi ho neudìlal. }
{1409}{}{Ty jsi vynalezl Jet?}
{1410}{}{Ty jsi vynalezl Jet? Nikdy! Kvùli té vìci se na ulicích ZABÍJÍ!}
{1411}{}{Ha ha. Já jdu pryè.}
{1412}{}{To na tebe musí bıt maminka opravdu pyšná. Èau, chlapeèku.}
{1413}{}{Vánì? To je nesmírnì zajímavé, ale já má ještì nìjakou práci, take tvoø dál. }

# 221. BULLSHIT. YOU DIDN'T MAKE JET. (220)
{1425}{myn221a}{Vynalezl jsem Jet! Myslíš, e tady ta laboratoø je tady jenom pro srandu králíkùm? }
{1426}{myn221b}{Sorry, e s tebou nesouhlasím, krásko, ale rozhlédni se kolem sebe. Tahle laboratoø tady není jenom na masírku.}
{1427}{}{Dobøe. MONÁ jsi udìlal Jet.}
{1428}{}{Proè jsi vynalezl Jet?}
{1430}{}{To na tebe musí bıt maminka opravdu pyšná. Èau, chlapeèku.}

# 222. ALL RIGHT. MAYBE YOU DID MAKE JET. (220, 221)
{1445}{myn222}{Na to si sakra klidnì vsaï! Dìlám fet, po kterém všichni šílí a poøád ho nemají dost.}

# 223. WHY DID YOU MAKE JET? (221, 222)
{1455}{myn223}{"Proè?" Protoe jsem mohl. Rodina Mordinù chtìla vırobní artikl, Myron vynalezl vhodné zboí, Mordinové udrují Myrona šastného... alespoò jak jenom to dokáou. Hezkı krouek, co?}
{1456}{}{Jak dìláš Jet?}
{1457}{}{'Alespoò jak to jenom dokáou?' Ty jsi tady šastnı?}
{1458}{}{A co takhle novı krouek? Mordinové nepoznají talent, i kdyby je mlátil do hlavy kladivem - ale já ano. }
{1459}{}{Jo, jo. Fakt skvìlı. Já musím jít.}

# 224. HOW DID YOU MAKE JET? (223)
{1465}{myn224a}{Ha, to jde mimo tebe. Je to trochu sloitìjší.}
{1466}{myn224b}{Netrap si s tím svoji milou malou hlavièku, miláèku. Mùu ti dát nìco jiného, nad èím bys ji trochu potrápila.}
{1467}{}{Jsi tady šastnı?}
{1468}{}{Jo, hádám, e od idiota jako já se nedá oèekávat pochopení sloitého procesu vıroby halucinogenicko-amfetaminového hybridu, jako je Jet, co?}
{1469}{}{Jo, hádám, e od idiota jako já se nedá oèekávat pochopení sloitého procesu vıroby halucinogenicko-amfetaminového hybridu, jako je Jet, co?}
{1472}{}{Myslím, e by tì pøekvapilo, kolik toho vím o tvém amatérském halucinogenicko-amfetaminovém hybridu. Nijak si mì nepøesvìdèil, e by dìcko jako ty na nìj jenom náhodou nenarazilo, Myrone.}
{1473}{}{Hmm, tak dík za snahu, Myrone. Já musím jít.}

# 225. YOU HAPPY HERE? (223, 224, 246)
{1485}{myn225}{Ale jó. Dávají mi kurvy, prachy, drogy. Mojí vlastní laboratoø. Volnost v práci, kterou potøebuju na svoje kouzla, ale...ne, není to tady nejhorší.}
{1486}{}{Take? Chovají se k tobì dobøe?}
{1487}{}{To je dobøe, Myrone. A já teï u musím jít.}

# 226. WELL WHAT? (225)
{1495}{myn226}{No, víš, Mordinové nechovají k Myronovi R-E-S-P-E-K-T, jasnı? Já jim povím, co by mìli dìlat, a oni øeknou 'dr hubu, Myrone' nebo 'jdi zpátky do laboratoøe, Myrone.' Bastardi.}
{1496}{}{Moná by tady byla pomoc. Chceš vypadnout z mìsta? Pøidej se ke mnì, budeme chvilku cestovat, a pak si moná Mordinové uvìdomí, jakou máš cenu.}
{1497}{}{Jsi pøíliš cennı na to, aby tady sedìl. Mìl bys odejít.}
{1498}{}{To je blbı, Myrone. Já musím jít, tak se mìj.}

# 227. WELL WHAT 2 (226)
{1505}{myn227}{Zapomínají, e kvùli MNÌ ovládají Reno. A kvùli mnì budou mít za pár mìsícù v kapse i Redding. Vìtšina Mordinù má víc filcek ne mozkovıch bunìk.}
{1506}{}{Jak byla øeè pøed chvílí, moná by tady byl urèitı zpùsob...}
{1507}{}{Jsi opravdu pøíliš cennı na to, abys tady sedìl. Vánì bys mìl odejít.}
{1509}{}{Zaèínám chápat, proè tì neposlouchají.}
{1510}{}{Na to si vsaï, Myrone. Èau, já jdu.}

# 228. WELL WHAT 3 (227)
{1515}{myn228}{A další vìc: Mordinové nemùou pochopit, e já se nezajímám o èištìní Jetu. Dìlá to, co má dìlat. Já chci vynalézat NOVÉ drogy, ne pøedìlávat staré, jasnı?}
{1516}{}{Mùu ti pomoct. Proè nevypadneš a nejdeš se mnou? Moná si pak Mordinové uvìdomí, jakou máš cenu.}
{1517}{}{Máš absolutní pravdu. Jsi pøíliš cennı na to, abys tady sedìl. Mìl bys odejít.}
{1518}{}{Co jsi to øíkal o Reddingu?}

# 229. MAYBE I CAN HELP YOU . . . (228, 231)
{1525}{myn229a}{Hmm....jejich chlapeèek utíká z domova. Ha. To je probere. Jo.}
{6525}{}{Urèitì. Urèitì si uvìdomí, o co pøišli.}

# 229B. MAYBE I CAN HELP YOU . . . (228, 231)
{1526}{myn229e}{To se mi líbí.}
{1527}{myn229d}{Líbí se mi tvùj zpùsob myšlení, krásko.}
{1528}{myn229c}{Take kam míøíme?}
{1529}{myn229b}{Take kam míøíme, krásko?}
{1530}{}{Následuj mnì, Myrone.}
{1531}{}{Tak pojï se mnou.}
{1532}{}{Zadr na chvíli, ještì s tím musí souhlasit jedna osoba. Já. Co umíš, Myrone? Nemùu k sobì brát kadého. Musí mít nìjakou úroveò.}
{1533}{}{Nejdøív uka, v èem jsi dobrı, Myrone?}
{1534}{}{Ještì nikam. Chci se tì ještì zeptat...}
{1535}{}{Ještì nikam, Myrone. Ale za chvíli se pro tebe vrátím.}

# 230. JUST FOLLOW ME. (FULL UP) (229, 247)
{1545}{myn230a}{Ná, vypadá to, e je vás moc. Proè nevyrazíš toho divocha? Bere ty kosti moc vánì.}
{1546}{myn230b}{Ná, vypadá to, e je vás moc. A Myron se nezahazuje s mutantama. Eh, bez uráky, velkej kámo.}
{1547}{myn230c}{Ná, vypadá to, e je vás moc. A Myron nechodí s ghoulama. Nikdy nevíš, kdy ti z nich kousek odpadne na botu.}
{1548}{myn230d}{Ne, nechci se zaplétat s další rodinou. Mordinové mi staèili. Uber nejdøív pár lidí, a pak se stav.}
{1549}{myn230e}{Jó jó. Mouchy by za tebou nelítaly, kdybys nebyl vobalenej hovnama. Zapomeò na to.}
{1550}{}{Tak dobøe. Hele, chci se ještì zeptat...}
{1551}{}{Hmmm. Uvidíme, Myrone.}
{1552}{}{Ne, má cenu tøí Myronù. Èau chlapèe.}
{1553}{}{Kluku, tvoje ego právì podepsalo šek, které tvoje tìlo nedokáe zaplatit. Pøiprav se na smrt.}
{1554}{}{Ještì uvidíme, Myrone..}
{1555}{}{Tvoje chyba, Myrone. Sbohem.}

# 231. FAST TALK: I SUGGEST A NEW CIRCLE (223)
{1565}{myn231}{Jo? Poslouchám...}
{1566}{}{Moná bychom si mohli pomoct navzájem. Hodil by se mi nìkdo s tvımi schopnostmi. Proè se nevykašleš na tohle pitomı mìsto a necestuješ chvíli se mnou? Mordinové si rychle uvìdomí, jakou máš cenu.}
{1567}{}{Oh, zapomeò na to a radši mi odpovìz ještì na pár otázek...}
{1568}{}{Zapomeò na to. Stejnì by to nešlo.}

# 232. JUST FOLLOW ME. (FREE SLOT) (229, 231, 247)
{1575}{myn232a}{Dobøe. }
{1576}{myn232b}{Dobøe, krásko. }
{1577}{myn232c}{Proè sakra ne? Prásknem do bot.}
{1578}{}{Mizíme.}
{1579}{}{Do Arroya je to 106 mil, máme pùl fúzní buòky, pùl tuctu antiradù, je pùlnoc a já mám na sobì 50 let starou kombinézu. Pojïme.}

# 233. WHAT CAN YOU DO? (229, 247)
{1585}{myn233}{Ah! Co, chceš Myronùv ivotopis? Jsem vìdec. všechno vím, všechno znám. Nemluvì o tom, e ti dokáu vyrobit jakoukoliv drogu, která tì napadne. Se správnımi surovinami, pochopitelnì.}
{1586}{}{Tak dobøe, v ústních zkouškách jsi uspìl. Ta èást s drogami ti pomohla. Pojïme.}
{1587}{}{Popøemıšlím o tom. Mám pro tebe ještì pár otázek...}
{1588}{}{Hmm, popøemıšlím o tom...ale, víš, bez uráky, ale vìdátoøi jsou nechvalnì proslulí svou neschopností v boji.}
{1589}{}{Musím si to rozmyslet. Ještì se vrátím.}

# 234. WHAT WAS THAT ABOUT REDDING 1. . . ? (227, 228)
{1595}{myn119}{Redding? Mìsteèko plnı zlatokopù. Mordino jim chce šéfovat. Take za mnou pøišel a povídá tím svım sípavım hlasem 'Myrone, Myrone, udìlej mi nìco, co mi dá Redding.'}
{1596}{}{A tys øek...}
{1597}{}{Hmmm. Ještì mám další otázku...}

# 235. WHAT WAS THAT ABOUT REDDING 2. . . ? (234)
{1605}{myn120}{A já øek 'okay, kdy to má bıt hotovı?' A on - samozøejmì - 'vèera.' Mafiáni. Chtìjí všechno hned. Aspoò e nemají marketingové oddìlení.}

# 236. I GUESS AN IDIOT . . . (224)
{1615}{myn236a}{Jo. Proè? Chceš mi dokázat, e se pletu, kámo? }
{1616}{myn236b}{Jo. Proè? Chceš mi dokázat, e se pletu, dámo? }
{1617}{myn236c}{Jo? Ale, hele, krásko, nekecej. tak hezkı tìlo nemùe mít pøece i tak chytrou hlavinku, ne? }
{5616}{}{Vyzkoušej mnì.}
{5617}{}{Myslím, e znám pár zajímavıch vìcí.}

# 236B. I GUESS AN IDIOT . . . (224)
{1618}{myn236d}{Já jsem zapomnìl víc o farmaceutickém vızkumu, ne kdy ty budeš vìdìt.}
{1619}{}{Je na Jet nìjakı lék?}
{1620}{}{Fajn. Tak jak jsi udìlal Jet?}
{1621}{}{Nejdøív, odpovìz mi na tohle: jak jsi udìlal halucinogen-amfetaminovı hybrid? Vypadá to, e Jet má nìjaké...unikátní vlastnosti.}
{1623}{}{Zapomeò na to. Mám ještì pár dalších otázek...}
{1624}{}{Zapomeò na to, já u stejnì musím jít.}
{1625}{}{Polib mi prdel, ty arogantní sráèi. Já mizím.}

# 237. I GUESS AN IDIOT . . . (224)
{1635}{myn237}{Amatérskı? Ama-amatérskı?! Jet je práce génia, na to nezapomínej! A já na nìj jen tak nenarazil, já ho VYNALEZL.}
{1636}{}{Nevìøím ti. Doka mi to.}
{1637}{}{No jo, no jo. Mìj se, chlapeèku.}

# 238. FIRST OFF, ANSWER ME THIS ABOUT THE HYBRID . . . (236, 237)
{1645}{myn238}{Dvì slova: brahmíní hovna.}
{1646}{}{Necháváš v nich vyrùstat ten halucinogen??}
{1647}{}{Pouíváš brahmíní hovna jako hnojivo pro rostlinu, ze které dostáváš Jet, e jo?}
{1648}{}{Nechceš mi to øíct? Dobøe. Tak mi odpovìz na jinou otázku...}
{1649}{}{Tak dobøe. Vidím, kam to vede. Kašli na to.}

# 239. THAT WHAT YOU USE TO GROW THE SHIT IN . . . (238)
{1655}{myn239a}{Dobøe. A to je všechno, co se kdy dozvíš, kámo. Pøijï si na to sám.}
{1656}{myn239b}{Dobøe. A to je všechno, co se kdy dozvíš, dámo. Pøijï si na to sama.}
{1657}{myn239c}{Velmi dobøe, krásko. Ale to je všechno, co se kdy dozvíš, tak u si nad tím netrap tu svoji roztomilou hlavièku. Dost kecù. Co kdybychom ty a já...uh, hehh...}
{1658}{}{Take brahmíní hovna mají nìjaké zvláštní chemické vlastnosti, které stimulují lidskı nervovı systém?}
{1659}{}{Moná. Chci se tì ještì zeptat...}
{1660}{}{-- si ještì chvíli popovídali? Vıbornì! Mám ještì spoustu otázek...}
{1661}{}{Fajn. Musím jít.}
{1662}{}{Uh, co kdybychom si ještì popovídali pozdìji? Èau.}

# 240. SO THE BRAHMIN SHIT HAS SOME CHEMICAL PROPERTIES . . . (239)
{1675}{myn240}{Opravdu dáváš spoustu zatracenıch otázek. Odpovìï zní: jo, moná...hele, o-odkud vùbec všechno tohle znáš? Jsi z Vault City nebo co?}
{1676}{}{Odpovìï na tvou otázku zní: jo...MONÁ. Odkud to všechno znáš TY??}
{1677}{}{Ani ne. Ten povídal tohle, tam bylo napsanı tamto... je to jednoduché.}
{1678}{}{Ne. Hele, mám ještì další otázky...}
{1679}{}{Vault City. Kde to je?}
{1680}{}{Nechám tì hádat. U jsi mi øekl všechno, co potøebuju vìdìt.}

# 241. TO ANSWER YOUR QUESTION, MAYBE  (240)
{1685}{myn241a}{Jo, jen si povídej co chceš, chytráku. Já jsem pøírodní. Sám jsem se vypracoval. ádnı ty nesmysly z Vault City, jasnı?}
{1686}{myn241b}{Heh, huh, ha! Jsi chytrá, krásko. Mmm-mmm. Nauèila ses to ve Vault City nebo co?}
{1687}{}{Já to nemám z Vault City. Zkrátka to umím. Je to primitivní.}
{1689}{}{Mám ještì pár otázek...}

# 244. QUESTION NODE (108-110, 112-131, 133-137, 143, 145-149, 151-154, 229-231, 233-243, 245-247)
{1695}{myn244}{Co chceš vìdìt?}
{1696}{}{Povìz mi nìco o tomhle místì.}
{1697}{}{Povìz mi nìco o rodinì Mordinù.}
{1699}{}{U musím jít.}

# 245. TELL ME ABOUT THIS PLACE (244)
{1705}{myn245a}{Stáje? Testujeme tady nové druhy Jetu. Co o nich?}
{1706}{myn245b}{Stáje? Testujeme tady nové druhy Jetu. Co o nich, krásko?}

# 246. TELL ME ABOUT THE MORDINO FAMILY (244)
{1715}{myn246}{Jsou to moji patronové. Jsou docela správní...øekl bych.}
{1716}{}{Øekl bys? Nechovají se k tobì dobøe?}

# 247. MYRON AGAIN (WTG)
{1725}{myn247}{Zas ty. Take...mùeme jít?}
{1726}{}{Jasná vìc, Myrone. Vypadneme odtud.}
{1727}{}{Momentík. Ještì s tím musí souhlasit jedna osoba. Já. Co umíš, Myrone? Nemùu k sobì brát kadého. Musí mít nìjakou úroveò.}
{1728}{}{Nejdøív: Co umíš, Myrone?}
{1729}{}{Vlastnì ani ne. Chci se tì zeptat...}
{1730}{}{Teï ne. Proè si na chvíli neodpoèineš?}

# 248. GOT A JUMPSUIT . . . (232)
{1735}{}{Jsi divnı...To se mi líbí.}
{1736}{}{Jsi divná...To se mi líbí.}

# 1001. HEALING (101, 1001, 1003, 1004, 1005, 1006)
{1745}{myrn104a}{Nestarej se o mnì.}
{1746}{myn104b}{Owww! Bolí! To bo- oh, lí. Ne. Ne, jsem v poøádku. Jenom to trochu píchá.}
{1747}{myn104c}{Umírám! D-Dej mi Stimpak! nebo dva! Nebo tøi...}
{1748}{myn104d}{To...jsi...ty? Nevidím...ztrácím...vìdomí. *Ugh* *Eh* Pomo...mi...}
{1749}{}{Hmmmm. Zkus se znovu ošetøit.}
{1753}{}{Vzpamatuj se, Myrone}
{1756}{}{Pojïme.}
{1757}{}{Vyser se na to. Máme tady ještì nìjakou práci, Myrone, tak se vzchop.}

# 1002. WAIT FOR ME HERE. (101, 1001, 1003, 1004, 1005, 1006)
{1765}{myn138}{Eh, promiò. Poèkej? Poèkej tady? Dìláš si srandu? Øekni mi, e si dìláš srandu!}
{1766}{}{Zùstaò. Tady. Dokud. Se. Nevrátím. Jasnı?}
{1767}{}{Já se vrátím.}

# 1003. PUT WEAPON AWAY (101, 1001, 1003, 1004, 1005, 1006)
{1775}{myn1003a}{Ah, no tak...dobøe. Sice jsem si chtìl vyzkoušet tu novou techniku støelby dávkou..}
{1776}{myn1003b}{Uh, tuhle zbraò? Oh...sorry, krásko. Ona tak nìjak...sama, víš?}
{1781}{}{Moná bys mìl trochu odstoupit, Myrone.}
{1784}{}{Ne, dokud jsi se mnou, tak ne. A teï pojï.}
{1785}{}{Hmmm. A teï pojï.}

# 1004. STAY CLOSE (101, 1001, 1003, 1005, 1006)
{1795}{myn1004a}{Eh...dobøe. Nechceš mì pøece trefit, e ne?}
{1796}{myn1004b}{Cokoli pøikáeš, nádherná. Vrrrr.}
{1802}{}{Vlastnì, radši mezi námi udruj poøádnou vzdálenost. Bude to tak lepší pro oba.}
{1804}{}{A tì trefím, poznáš to. A teï pojï.}
{1805}{}{Uklidni se, Myrone. Pojïme.s}

# 1005. STAY MEDIUM (101, 1001, 1003, 1004, 1006)
{1815}{myn1005a}{No...dobøe. Ale slyšel jsem, e ten uprostøed to první slízne.}
{1816}{myn1005b}{Dobøe, bu ti hlídat prdılku...er...uh, záda jsem chtìl øíct.}
{1820}{}{Vlastnì, zapomeò na to. Zùstaò u mì.}
{1822}{}{Odsuò se ještì dál, Myrone. Bude to pro nás oba lepší.}
{1824}{}{S tím poèítám.}
{1825}{}{Vıbornì. Pojïme.}

# 1006. STAY LONG (101, 1001, 1003, 1004, 1005)
{1835}{myn1006a}{Dobøe, pohlídám to tam vzadu. Aspoò mám dost prostoru, a budu chtít støílet dávkou.}
{1836}{myn1006b}{Co - Smrdím, nebo co?! Cc.}
{1841}{}{Pojï blí, Myrone.}
{1844}{}{No jo. A teï pojï.}
{1845}{}{Kdyby to byl jenom tvùj tìlesnı pach, dalo by se to vydret. A teï pojïme.}

# 1100. REJOIN (101, 1001)
{1860}{myn232a}{Dobøe.}
{1863}{}{Kluku, tvoje ego právì podepsalo šek, které tvoje tìlo nedokáe zaplatit. Pøiprav se na smrt.}
{1866}{}{Pojïme.}

# dude floats
{1870}{}{mjé jé òák blbì.}

# misc messages
{1875}{}{Myron uznal, e by mohl existovat lék.}
{1880}{}{To je hrob, ve kterém Velkej Jeíš schoval peníze.}
{1885}{}{Myron souhlasil, e odejde ze stájí.}

# 309. GET OUT OF MY WAY (WTG)
{1957}{}{Dobøe, dobøe! Nestrkej do mnì!}
{1958}{}{Hej, uklidni se. Já svoji UI neprogramoval.}
{1959}{}{Dobøe, PROMIÒ.}
{1960}{}{Dobøe, ale pøíštì uhne TY MNÌ.}
{1961}{}{Já tady byl první. Ale jak chceš.}

# 306. I NEEDED SOME TIME TO MYSELF (WTG)
{2091}{}{Nemáš pár drobnıch? Musím zachránit pár holek od panenství.}

# 242. I PICK IT UP PRETTY EASY (240, 241, 243)
{2675}{myn242a}{Jednoduchı, jo? Já jsem nejlepší. Dvakrát lepší ne ti ocasy z Vault City.}
{2676}{myn242b}{Jó, to máš pravdu. Jednodušší ne ty blbosti, co by tì uèili kreténi z Vault City.}
{2678}{}{Chci se tì ještì zeptat...}
{2679}{}{Hmm. No nic, moná se ještì pozdìji uvidíme. Èau, Myrone.}

# 243. VAULT CITY (240, 241, 242)
{2685}{myn243}{Mìsto na severovıchod. Banda "geneticky èistıch" lidí. Kdyby namyšlenost nadnášela, všichni by tam lítali jako vzducholodì. }
{2686}{}{No, já se ve Vault City neuèil. Pochytil jsem to tak rùznì... je to fakt primitivní.}
{2687}{}{Zajímavé. Mám ještì pár otázek...}
{2688}{}{Hmmm. Ještì se uvidíme. Èau, Myrone.}

# NEW PARTY STUFF
{2004}{myn324}{O èem to sakra mluvíš?}
{2001}{myn321}{To je v prdeli.}
{2033}{myn353}{Nevím.}
{2023}{myn343}{To radši vylíu Marcusovi prdel.}
{2024}{myn344}{To radši vylíu Lennymu prdel.}
{2025}{myn345}{To radši nechám toho kyber-psa, a mi ukousne koule.}

{3000}{}{Myrone, myslím, e bychom si mìli promluvit o...vzdálenosti.}
{3001}{}{Promluvme si o tvém vybavení.}
{3002}{}{Zapomeò na to. Zùstaò, kde jsi.}
{3003}{}{Chci, aby sis sundal to brnìní.}
{3004}{}{S jakımi zbranìmi umíš zacházet, Myrone? Jakékoli? }
{3005}{}{No nic, stejnì od tebe potøebuju nìco jiného.}

{3025}{}{No jo.}
