#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
# QUICK LOOK

# EXAMINE
{150}{}{Vidíš škaredı, prorezivìlı vıherní automat.}
{151}{}{Vidíš odpornì vyhlíející vıherní automat. Je pokrytı rzí a má na nìkolika místech proraenı pláš,jakoby do nìj nìkdo bušil tìkım pøedmìtem.}

# 1. FLOAT DIALOGUE (PLAYER = MALE, DRUNK OR HIGH) (WTG)
{200}{}{*Hej ty, ...::ech ech:: ::ech:: ::uff:: ...pojï...::cvak::...si se mnou na chvíli zahrát.*}
{201}{}{*Zdárek, mlad- ::ech:: ::uff::*}
{202}{}{*Hej tam, mladej- ::kech:: ::krk:: ::pfff:: ...proè si ...nevsadíš?*}
{203}{}{*KRRRR*}
{204}{}{*Cvak*}
{205}{}{*DUM*}
{206}{}{*Ker-cink cink*}
{207}{}{*Zzzztttt*}
{208}{}{*Ka-cink-cvak*}
{209}{}{*Ka-drrrz-cvak-skvíííí*}
{210}{}{*Bum*}
{211}{}{*Cink-Cinkety-Cink*}
{212}{}{*Pitomı zvukovı efekt*}
{213}{}{*Hej tam, krásko...::ech:: ::kech:: ::zdrrr:: ...pojï...::cvak::...si zahrát.*}
{214}{}{*Ahoj, krás ::ech:: ::uch:: Sakra!*}
{215}{}{*Hoï do mì dolar a zatáhni mì za ruku. Uijeme si spolu. Heh-heh.*}
{216}{}{*No, jestlipak to není krásná mladá dám -- ::ech:: ::cvak:: ::písk: Proè...::klik::...si nejdeš zahrát?*}

# 4. RETARD (WTG)
{230}{}{Vidíš divnou eleznou bednu se tøemi oèima a jednou rukou.}

# 5.  RETARD TALKS TO SLOT MACHINE (4, 5)
{235}{}{Divná elezná bedna se tøemi oèima a jednou rukou neodpovídá.}

# 6.  RETARD PULLS HANDLE (4, 5)
{240}{}{Popadl jsi ruku a potøásl s ní. Je slyšet ostrı chøestivı zvuk!}

# PLAY. . . ? (WTG, 14, 15)
{245}{}{(Vidíš vıherní automat. Je to asi nejškaredìjší automat v Novém Renu. Jeho páka je zkroucená,  sklo je vybité a po celém plášti jsou vidìt promáèknutí a odøeniny.)}
{246}{}{Hledáš v kapse drobné. (Stroj si stále šeptá hroznım hlasem.)
 *Tak pojï...::kuch::...tak je to...*}

# LOOOOOOSER (8)
{250}{}{Zevnitø se ozıvá chøestivı zvuk...}
{251}{}{NIC! (Stroj se suše smìje.) *Pøíštì se to povede, mla -- ::kchh:: ::uch:: ::zzz::}

# WIN x1 (8)
{255}{}{(Stroj ti šeptá.) *Zkus to znovu...ještì jednou - ::uch:: ::hah:: - dokud máš štìstí.*}

# WIN x2 (8)
{260}{}{Po chvíli chøestìní... }
{261}{}{(Stroj se chichotá.) *Správnì, správnì. Mì to bylo hned jas... ::ech:: ::uch:: ...e to dokáeš.*}

# WIN x3 (8)
{265}{}{(Stroj se smìje.) *Vıbornì, hráèi, vıbornì! Vìdìl jsem, e ve mnì ještì pár ... ::vvzzzz:: ...doláèù zbylo! Heh-heh!*}

# DRUNK, HIGH OR OTHERWISE FUCKED UP (WTG)
{270}{}{(Pøed tebou je ta nejodpornìjší hromada šrotu na svìtì, která kdy mìla tu drzost øíkat si vıherní automat.
 Chvíli na ní fascinovanì zíráš, kdy najednou zaène z automatu šeptat hlubokı muskı hlas.)
  *Tebe jsem tady ješte - ::kach::
 ::uch:: nevidìl. Nechceš si ... ::kk:: ::zzz::... trochu zariskovat?*}

# DRUNK CONVERSATION 1 (13)
{275}{}{*Jsem poøád tady,* cvaká vıherní automat. *Pojï, nechceš si vsadit?*}

# DRUNK 2 (14)
{280}{}{*Jsem nejstarší jednorukı bandita v Renu. U jsem tady skoro...::ug:: ::ech::...no, skoro celou vìènost. 
 Hele, budeš hrát, nebo mì tu necháš rezivìt?*}

# DRUNK 3 (15)
{285}{}{::Uch:: ::egh:: *Nemám èas ani náladu kecat. A ty urèitì taky máš dùleitìjší vìci, ne  se mnou kecat, he?*}

# DRUNK 4 (16)
{295}{}{*Klídek. Všechno bude okej, jasnı? Dám na tebe pozor, jo?*}

# DRUNK 5 (17)
{300}{}{*Hej, no tak. Dost toho. Projdi se, proèisti si hlavu...::uch::...relaxuj. Budeš okej?*}
{301}{}{Budu okej...dikes, es se mnou pokecala, mašino}

# DRUNK 6 (18)
{305}{}{*Pah! Nemusíš dìkovat, [X]. Tak, a teï vypadni a poøádnì jim nakopej prdele. Ty seš jedinej hrdina v tomhle pitomım
 svìtì plnım bastardù a zlodìjù... ::uch:: ::zzzzz:: ::eh::...tak si dej bacha, jo?*}
{306}{}{Jásnì -- tytaky, dóbrze?}

# JACKPOT! (8)
{310}{}{(Po zatáhnutí páky ti pøipadlo, jakoby ze stroje vyšel úlevnı oddech následovanı dlouhım tichem.U se skoro chystáš k odchodu, kdy najednou slyšíš hluboko ve stroji nìco chøestit. O pár sekund pozdìji se chøestìní zmìnilo na ohlušující øev, jak z automatu vylétávají mince v cinkavé bouøi!) JACKPOT!}
{311}{}{Vyber vıhru!}

# AFTER JACKPOT (WTG)
{315}{}{(Stroj vypadá, e u ze sebe vydal všechno. Vyplacení jackpotu byl jeho smrtelnı vıkøik. Nemùeš si pomoct, ale je ti té staré trosky líto.)}

# skill use
{320}{}{Automat je prehistorickı. Je to zázrak, e ještì funguje.}
{321}{}{Nemùeš na automatu pracovat, dokud na ní ten dìdek hraje.}
{322}{}{Stroj je neopravitelnı.}
{323}{}{Není nic, co bys dokázal udìlat.}
{324}{}{Automat je prehistorickı. Je to zázrak, e ještì funguje. Chvíli si s ním pohráváš, ale kdy zaslechneš silné cvakání, které tvá akce zpùsobila, vzdáváš to.}
{325}{}{Automat je prehistorickı. Je to zázrak, e ještì funguje. Chvíli si s ním pohráváš, ale nic s ním nemùeš udìlat.}
{326}{}{Automat je prehistorickı. Je to zázrak, e ještì funguje. Chvíli si s ním pohráváš a oèišuješ nìkterá zaøízení, ale víc toho udìlat nemùeš.}
