#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
# 0. LOOK, CLOSED (WTG)
{100}{}{Ve zdi vidíš sejf na èíselnou kombinaci. Je zavøenı.}

# 1.  LOOK, OPEN (WTG)
{150}{}{Ve zdi vidíš sejf na èíselnou kombinaci. Je otevøenı.}

# 2.  EXAMINE SAFE, CLOSED (WTG, 10, 11)
{200}{}{(Ve zdi jsou malı dvíøka, hódnì malı. Tam musí ít móc moc malej èlovìk! tam ije! Uprostøed dvíøek je klika s èísilkama.)}
{000}{}{(Prozkoumáváš sejf. Je pevnì umístìnı ve zdi a má kombinaèní èíselník.)}
{000}{}{Zaukat na dveøe}
{000}{}{Otoèit klikou}
{000}{}{Odejdi}
{000}{}{[JBJBJB]}
{000}{}{Otáèej èíselníkem a poslouchej cvakání.}
{000}{}{Otáèej èíselníkem a poslouchej cvakání.}
{000}{}{Otáèej èíselníkem a poslouchej cvakání.}
{000}{}{Otáèej náhodnì èíselníkem.}
{000}{}{Podívej se po pasti, o které mluvila paní Bishopová.}
{000}{}{Prozkoumej sejf, jestli není zaminovanı.}
{000}{}{Nechej sejf bıt.}

# 3.  SAFE IS OPEN (WTG, 2, 5, 6, 7, 8)
{220}{}{(Je slyšet KLIK-CVAK a sejf je otevøenı.)}
{000}{}{(Sejf je otevøenı.)}
{000}{}{(Dvíøka se otvírají. Uvnitø malinkıho domeèku je fákt tma. A tìsno.)}
{000}{}{(Dveøe jsou otevøenı! Uvnitø je to tmavı a malı.)}
{000}{}{Podívej se, jestli tam nìkdo není}
{000}{}{Odejdi}
{000}{}{Vyber sejf.}
{000}{}{Nechej sejf bıt.}

# 4.  TRAPS, SUCCESS . . . ? (2, 6)
{230}{}{(Opatrnı prùzkum odhalil malou kostku plastické vıbušniny ve zdi tìsnì pod sejfem, která by explodovala, pokud nìkdo nastaví špatnou kombinaci. Past byla pøekrytá vrstvou plastu, take bylo dost obtíné ji najít.)}
{000}{}{Zkus odpojit past.}
{000}{}{Nastav past na jinou kombinaci.}
{000}{}{Nechej sejf bıt.}

# 5.  CLICKING (2, 5, 6, 8)
{240}{}{Pomalu nìkolikrát otáèíš èíselníkem, ale nic z toho není.}
{000}{}{[JBJBJB]}
{000}{}{Otáèej èíselníkem a poslouchej cvakání.}
{000}{}{Otáèej èíselníkem a poslouchej cvakání.}
{000}{}{Otáèej èíselníkem a poslouchej cvakání.}
{000}{}{Otáèej náhodnì èíselníkem.}
{000}{}{Nechej sejf bıt.}

# 6.  TRAPS . . . ? (2, 6)
{250}{}{(ádné pasti nenalezeny.)}
{000}{}{[JBJBJB]}
{000}{}{Otáèej èíselníkem a poslouchej cvakání.}
{000}{}{Otáèej èíselníkem a poslouchej cvakání.}
{000}{}{Otáèej náhodnì èíselníkem.}
{000}{}{Prozkoumej sejf znovu, jestli není zaminovanı.}
{000}{}{Nechej sejf bıt.}

# 7.  SPIN RANDOM, SUCCEED (2, 5, 6, 8, 9)
{260}{}{Pomalu otáèíš klikou, kdy je najednou slyšet KLIK-CVAK. Dvíøka se otevøely!}
{000}{}{Náhodnì otáèíš èíselníkem, kdy je najednou slyšet KLIK-CVAK. Sejf je otevøenı.}
{000}{}{Haló? Halóóóóó? Nìkdo dóma?}
{000}{}{Jo, já na to mám...}

# 8.  SPIN RANDOM, FAIL (2, 5, 6, 8, 9)
{270}{}{(Otáèíš klikou, ale malinkı dvíøka se nechcou otevøít!)}
{000}{}{Pár minut trávíš otáèením èíselníku, ale ádnı vısledek se nedostavil.}
{000}{}{Zaukat na dveøe}
{000}{}{Otoèit klikou}
{000}{}{Odejdi}
{000}{}{[JBJBJB]}
{000}{}{Otáèej èíselníkem a poslouchej cvakání.}
{000}{}{Otáèej èíselníkem a poslouchej cvakání.}
{000}{}{Otáèej èíselníkem a poslouchej cvakání.}
{000}{}{Otáèej náhodnì èíselníkem.}
{000}{}{Nechej sejf bıt.}

# 9.  HELLO? (2, 8, 9)
{290}{}{(Nikoho neslyšíš a nikde nevidíš zvonek. Asi není nikdo doma.)}
{000}{}{(Nikdo nejde otevøít.)}
{000}{}{(Zaèíná tì bolet ruka.)}
{000}{}{(Jestli je nìkdo doma, nechce otevøít.)}
{000}{}{ukej dál na dveøe}
{000}{}{Otoè klikou}
{000}{}{Odejdi}

# 10.  TRAP DISARMED . . . ? (4)
{300}{}{(S chirurgickou pøesností odpojuješ rozbušku a vytahuješ trhavinu ze zdi. Past je zneškodnìna.)}
{000}{}{A teï otevøít sejf...}
{000}{}{Nechej sejf bıt.}

# 11.  TRAP DISARMED . . . ? (4)
{310}{}{(S chirurgickou pøesností otvíráš rozbušku a upravuješ kombinaèní spínaè. Majitele sejfu èeká nepøíjemné pøekvapení, a se pøijde potìšit svım bohatstvím uloenım v trezoru...)}
{000}{}{A teï otevøít sejf...}
{000}{}{Nechej sejf bıt.}
