#tenhle soubor pøeložil Birdman - birdman@post.cz, http://get.to/birdman
# 0.  LOOK, CLOSED (WTG)
{100}{}{Ve zdi vidíš sejf na èíselnou kombinaci. Je zavøený.}

# 1.  LOOK, OPEN (WTG)
{101}{}{Ve zdi vidíš sejf na èíselnou kombinaci. Je otevøený.}

# LOCKPICKING
# trapped
{120}{}{Už skoro zaèínáš s otvíráním sejfu, když si náhle všimneš nìèeho nepatøièného. Tìsnì pod sejfem je vidìt rozbuška. Vypadá to, že ten hajzlík je zaminovaný.}
{121}{}{Sejf je zaminovaný.}

# successfull unlock
{150}{}{Je slyšet KLIK-CVAK. Sejf je otevøený.}

# lucky unlock
{160}{}{Náhodnì otáèíš èíselníkem, když je najednou slyšet KLIK-CVAK. Sejf je otevøený.}

# failed unlocks
{170}{}{Pomalu nìkolikrát otáèíš èíselníkem, ale nic z toho není.}
{171}{}{Pár minut trávíš otáèením èíselníku, ale žádný výsledek se nedostavil.}

# TRAPS
# disarm
{180}{}{Po objevení pasti na sejfu je otázkou nìkolika minut, než ji úspìšnì zneškodníš.}
{181}{}{Past v sejfu úspìšnì vyøazena.}

# find trap
{190}{}{Na sejfu je past, ale tobì se jí nepodaøilo odpojit.}

# fail
{200}{}{Vypadá to, že tady žádná past není.}
{201}{}{Nepodaøilo se ti odpojit past na sejfu.}

# fail critical

# CHANGING COMBO ON SAFE
# trap needs re-arming
{220}{}{Asi by bylo nejlepší nejdøív sejf znovu zaminovat dynamitem nebo plastickou trhavinou.}

# changed combination
{230}{}{Kombinace na sejfu byla úspìšnì zmìnìna... he he he...to bude nepøíjemné pøekvapení...}
{231}{}{Kombinace na sejfu byla úspìšnì zmìnìna... znovu.}

# no skills
{240}{}{Nemáš dostateèné schopnosti na zmìnu kombinace.}
{241}{}{ nemá dostateèné schopnosti na zmìnu kombinace.}

# it's open
{250}{}{Sejf je tøeba zavøít.}

# REARMING TRAP
{260}{}{Hmm, vypadá to, že na sejfu už výbušnina je.}

{270}{}{Nepodaøilo se ti zaminovat sejf.}
{271}{}{ nedokázal zaminovat sejf.}

{280}{}{Mina na sejfu je pøipravená.}

# trap_boom
{300}{}{O patro výš slyšíš tlumený výbuch.}

{400}{}{Oddìlil jsi malý panel na dnì sejfu. Asi by se ti ho nepodaøilo najít, kdyby ti o nìm neøekla paní Bishopová. Vevnitø je podivná elektronická periférie k PipBoyi.}

# critical fail
{290}{}{Pøi hledání pasti v sejfu došlo ke kritickému selhání. Past se našla, ale bohužel explodovala.}
{291}{}{Škubnutí za špatný drát pøi odstraòování výbušniny se nevyplácí. Pokus o zlikvidování miny nevyšel.}
