#tenhle soubor pøeložil Birdman - birdman@post.cz, http://get.to/birdman
{100}{}{Pøímo tady bylo zaparkovaný moje auto!}
{150}{}{Po pøiblížení k místu, kde ještì nedávno odpoèívalo tvé auto, nìco upoutalo tvé bystré oko. Vidíš stopy pneumatik vedoucí na sever.}
{151}{}{Vidíš stopy po pneumatikách, které vedou na sever.}
{152}{}{Vidíš stopy auta!}
{153}{}{(Jít po stopa!)}
{154}{}{(Kašlat na nìjaká blbá stopa.)}
{155}{}{(Jít po stopách.)}
{156}{}{(Ignorovat stopy.)}
