#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš malou štíhlou enu v modrıch sametovıch letních šatech.}
{101}{}{Vidíš vdovu Ariel.}
{102}{}{Vidíš malou štíhlou enu v modrıch sametovıch letních šatech. Vypadá dost nešastnì.}
{103}{}{Ahoj, já jsem Ariel. Myslím, e jsem tì tu ještì nevidìla. Kdo jsi?}
{104}{}{Sem já.}
{105}{}{Vypadáš smutnì, proè to?}
{106}{}{Radši u pùjdu.}
{107}{}{Ahoj Ariel, já jsem }
{108}{}{Nazdárek, vypadáš sklesle. Co ti je??}
{109}{}{Nepotøebuješ znát moje jméno, ale já chci pár informací od tebe.}
{110}{}{Promiò, teï na tebe nemám èas.}
{111}{}{Ráda tì poznávám. S èím ti mohu pomoct?}
{112}{}{Mùeš mi nìco øíct?}
{113}{}{Nic. Èau.}
{114}{}{Ty mi nemùeš pomoci. Zdar.}
{115}{}{Mùu se tì na nìco zeptat?}
{116}{}{Nerad ruším tvé rozjímání, ale mùu se tì na nìco zeptat?}
{117}{}{Mám nìjaké osobní problémy. Jsem v pohodì, opravdu.}
{118}{}{Jen se vypovídej, pomùe to.}
{119}{}{Ok. Nebudeme o tom mluvit. Zodpovíš mi pár otázek?}
{120}{}{Jsem dobrı posluchaè, Ariel, a povídaní o èemkoli, co tì trápí, mùe jen pomoci.}
{121}{}{Ok. Zapomeò na problémy. Mùu se tì na nìco zeptat?}
{122}{}{Kadı má problémy, enská. Nauè se s nimi vypoøádat.}
{123}{}{Odpus, ale nemám èas na nìkoho jako jsi ty. Pøeji dobrı den.}
{124}{}{}
{125}{}{}
{126}{}{Ok.}
{127}{}{Co chceš vìdìt?}
{128}{}{Jsi vìzen?}
{129}{}{Deathclawové s tebou zacházejí dobøe?}
{130}{}{Chceš odejít?}
{131}{}{Take, proè tak smutná?}
{132}{}{Jak jsi se sem dostala?}
{133}{}{Musím jít.}
{134}{}{Jsi tady vìznìm?}
{135}{}{Deathclawové tì berou?}
{136}{}{Chceš opustit vault?}
{137}{}{Øekni mi, Ariel, proè jsi tak smutná?}
{138}{}{Jak to, e jsi tady ve Vaultu?}
{139}{}{U musím jít.}
{140}{}{Ne, mùu odejít, kdy chci. Deathclawové mi to dali jasnì najevo. Nikoho tu nedrí proti jeho vùli, alespoò co já vím.}
{141}{}{Uh, tak jo.}
{142}{}{Mám to. Pùjdu.}
{143}{}{Vidím.}
{144}{}{Myslím, e leš, ty dìvko!}
{145}{}{Vidím. Pokud by ti to nevadilo, chci se zeptat ještì na pár vìcí.}
{146}{}{Jo. Poskytují mi jídlo, vodu, pøístøeší a ochranu. Cítím se bezpeènì, a to je vše, co potøebuju.}
{147}{}{Dobrá, musím u jít.}
{148}{}{Bezva, chci vìdìt ještì nìco.}
{149}{}{V poøádku, chci se ještì na nìco zeptat.}
{150}{}{Ok, ještì nìco.}
{151}{}{Vynikající. Ještìrkofil.}
{152}{}{Musím øíct, e ne. Cítím se tu bezpeènìji ne kdekoli jinde. Stıská se mi po spoleènosti lidí jako jsem já, ale doufám, e sem další pøijdou a bude veselo.}
{153}{}{Asi pùjdu. Pa pa páá.}
{154}{}{Øekni ještì nìco.}
{155}{}{Bezva, pro mne za mne tady klidnì shnij.}
{156}{}{Ok, myslím, e zase pùjdu.}
{157}{}{Moc jsi mi pomohla, ale musím tì ještì potrápit.}
{158}{}{Mùj manel nedávno umøel. Schází mi a nedokáu se s tím vyrovnat. To je všechno.}
{159}{}{Promiò, jak se to stalo?}
{160}{}{Jéje. Musím padat, slyším volání Starší.}
{161}{}{Upøímnou soustrast. Jak se to stalo?}
{162}{}{Aha, dobrı, ale musím jít. Ještì se uvidíme.}
{163}{}{Kurva drát, lidi chcípaj. Obvykle kdy jsem poblí já.}
{164}{}{U jsme probrali nájezd. Tehdá se to událo.}
{165}{}{Mùj manel a já jsme cestovali v karavanì do NCR. Chtìli jsme zaèít novı ivot, my a naše dcera, Sandy. Jako na potvoru byla karavana v noci pøepadena. Byli velmi brutální. Zabili kadého: mue, eny, dìti. Rand, mùj manel, umøel kdy mne a Sandy bránil. U jsme mìly na kahánku, kdy se v poslední chvíli stal zázrak. }
{166}{}{Jé.}
{167}{}{Ok.}
{168}{}{Bezva. Ahoj.}
{169}{}{Paneèku, to je vìc.}
{170}{}{To je pìknej kec....toti, musím jít.}
{171}{}{Díky bohu, e jste v poøádku.}
{172}{}{Zdravíèko, jak to jde?}
{173}{}{}
{174}{}{}
{175}{}{Vypadni grázle! Nechci s tebou nic mít.}
{176}{}{Táhni dìvko! Nemám ti co øíct.}
{177}{}{Pa.}
{178}{}{.}
{179}{}{. Jo, jsem tu chvíli.}
{180}{}{Drela jsem Sandy za sebou, chtìla jsem ji dret co nejdál od monstra, co støelilo Randa. Stál hned vedle mrtvoly mého mue a smál se, kdy mi míøil na hlavu, kdy tu se ze tmy vynoøil ten velkı paøát, chytil ho zezadu a... no, díky bohu, e Sandy nevidìla, co se stalo. Kadopádnì, banditi byli odraeni skupinou právì tìchhle deathclawù. Ten co zachránil Sandy a mne stál kousek od nás a mluvil na mne. Stále mne ujišoval, e jsem v poøádku, a e je mu líto, e nemohli pøijít døív, aby nám pomohli. Potom nás deatclawové vzali sem.}