#tento soubor pøeložil Vachy - http://vachy.moje.cz
{100}{}{Vidíš mladou ženu v kovové zbroji.}
{101}{}{Vidíš Daliu.}
{102}{}{Vidíš hezkou mladou ženu obleèenou v kovové zbroji. Prohlíží si pozornì svoji výstroj.}
{103}{}{No to je náhoda. Jak se ti daøí,} #continue to 153
{104}{}{Dalio. Pamatuji na tvou pomoc.}
{105}{}{Všechno je ok. Pùjdu.}
{106}{}{Dalio! Dìkuji ti, události se vyvinuly skvìle.}
{107}{}{Ušlo to, ale budu muset jít.}
{108}{}{Hej, ráda to slyším. Bylo mi potìšením udìlat to pro tebe. Takže, co pro tebe mùžu udìlat dnes?}
{109}{}{Mám pár otázek.}
{110}{}{Nic. Zdar.}
{111}{}{Mùžu se tì na nìco zeptat?}
{112}{}{Nic. Nic, ale je dobøe, že tì zas vidím, èau.}
{113}{}{Co chceš vìdìt?}
{114}{}{Jsi vìzeò?}
{115}{}{Mohla bys odejít, kdybys chtìla?}
{116}{}{Co víš o deathclawech?}
{117}{}{Jak jsi se sem dostala?}
{118}{}{Proè se obáváš o svoji bezpeènost?}
{119}{}{Díky, už asi pùjdu.}
{120}{}{Jsi tady jako vìzeò?}
{121}{}{Mùžeš odejít, kdykoli se ti zachce?}
{122}{}{Co mi mùžeš øíct o deathclawech?}
{123}{}{Jak jsi se sem dostala?}
{124}{}{Proè najednou potøebuješ bezpeèné místo?}
{125}{}{Díky, ještì pokecáme pozdìji.}
{126}{}{Ne, nejsem. Jsem tu ze své vlastní vùle a líbí se mi to. Myslím, že tohle je bezpeèné místo a že tu chvíli zùstanu.}
{127}{}{Ok.}
{128}{}{Èau.}
{129}{}{V poøádku.}
{130}{}{Áha. Dobrá, pak tedy pùjdu.}
{131}{}{Jo, bylo mi øeèeno, že mùžu zùstat nebo kdykoli odejít. Prozatím zùstávám.}
{132}{}{Hm, chápu.}
{133}{}{Aha, jo.}
{134}{}{Myslím, že nevím o nic víc než ty. Stále se snažím zvyknout si na to, že na mne mluví místo toho, aby mi urvali hlavu a hráli s ní kopanou. Dìsivé, nemyslíš?}
{135}{}{Jo, divný.}
{136}{}{Kdepak, pohoda.}
{137}{}{Jo, v mnoha smìrech.}
{138}{}{Ne, ještì jsem to nepøijal.}
{139}{}{Potom, co jsem opustila Squat, jsem nevìdìla, co mám dìlat.
Myslela jsem, že bych jen mìla odejít jinam a získat jinej job... takže
jsem cestovala pouští a rozmýšlela, kam pøesnì jít. Jednoho dne jsem
zrovna hledala místo pro utáboøení. Stmívalo se a já nechtìla být tak na 
ránì, až padne tma. Z dálky jsem myslela, že vidím oheò -- takže jsem se
chtìla podívat, kdo to je.}
{140}{}{Jù.}
{141}{}{Zajímavé.}
{142}{}{Když sem tì nechala projít ve Squatu, porušila smlouvu se svým zamìstnavatelem. Byla jsem si jistá, že mi pùjdou po krku. To, že tì tu teï vidím, mne pøesvìdèuje, že to mùžu klidnì pustit z hlavy. Znamená to, že mùj bývalý zamìstnavatel už není dost dobøe v kondici na to, aby se mnou dál zabýval}
{143}{}{Jsi v bezpeèí, kašli na to, Dalio.}
{144}{}{Nyní jsi v bezpeèí, Dalio. Nemusíš se obávat žádných represí.}
{145}{}{Díky,} # continue 155
{146}{}{Není zaè.}
{147}{}{Pa.}
{148}{}{Není zaè.}
{149}{}{Uvidíme se.}
{150}{}{Ahoj.}
{151}{}{Ahoj. Jak to jde?}
{152}{}{Mh, nijak, nemám co øíct. }

{153}{}{. Doufám, že se ve Squatu všechno vyøešilo.}
{154}{}{No, pøiplížila jsem se k tomu ohni a oni tam právì sedìli ti dva deathclawové a plácali o nièem. Já husa jsem trochu vyjekla pøekvapením, vyskoèila a vzala nohy na ramena -- jen abych vbìhla pøímo do náruèe dalšího deathclawa stojícího pøímo za mnou. Každopádnì, abych to uzavøela, dalo mi to chvíli pochopit, že nebudu napíchnuta na rošt a ugrilována. Místo toho mne vzali sem a pøedstavili Grutharovi. Teï tady mùžu žít, když chci.}
{155}{}{. Neuvìøitelné.}
