#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš smutného, postaršího mue.}
{101}{}{Vidíš Davea, "Pana Depresi."}
{102}{}{Vidíš mrzutého, postaršího mue zhruba kolem šedesátky. Má vìtrem ošlehanou tváø a vypadá, jako kdyby mìl starosti kvùli nìjaké hrozbì.}
{103}{}{Oh. Nevšiml jsem si vás.}
{104}{}{Nevidíš mne? Nejsem ádnı skrèek.}
{105}{}{Vypadáš smutnì. Proè to?}
{106}{}{Pùjdu, pa pa.}
{107}{}{To je v poøádku, všichni se obèas zamyslíme. Koukám, jsi nìjakı skleslı. Mùu se zeptat proè?}
{108}{}{Jo, jasnì. Proè seš takovej skleslej?}
{109}{}{Mam tì pøíštì pøetáhnout polenem, aby sis mne všiml nebo co?}
{110}{}{No jistì. Právì jsem si vzpomnìl, e mám bıt nìkde úplnì jinde.}
{111}{}{No jo, zkurvilo se to -- mnì se to kurví furt.}
{112}{}{Uh... asi e pùjdu.}
{113}{}{Jako co?}
{114}{}{Zajímavı postoj. Co je pøíèinou?}
{115}{}{Vlastnì ti chci øíct, e mám bıt jinde.}
{116}{}{Narodil jsem se pøedèasnì, o dva mìsíce.  Kdy mi byl jeden rok, upustili mne na verandì. Kdy mi byly dva, dostal jsem zápal plic. Kdy mi byly tøi, dostal jsem plané neštovice. Kdy mi byly ètyøi, spadl jsem ze schodù a zlomil si šest eber. Kdy mi bylo pìt, mùj strejda byl rozdrcen vodním melounem.  Kdy mi bylo šest, rodièe mne pøetáhli lopatou po hlavì. Kdy mi bylo sedm, moje domácí krysa mi ukousla ukazováèek.}
{117}{}{Je, myslím, e slyším nìkoho volat. U jdùù...!}
{118}{}{To je smutnı, fakt.}
{119}{}{To bylo špatnı, bez diskuse. Teï je to lepší, ne?}
{120}{}{Tı brïo! Jsem rád, e nejsem na tvém místì!}
{121}{}{Ok, u si udìlám obrázek. Co tì trápí momentálnì?}
{122}{}{Je mi strašnì líto, es zail v ivotì tolik bolesti. Doufám, e nyní je to lepší.}
{123}{}{Poèkej chvilku. Úplnì mi vypadlo, e musím jít udìlat nìco jinıho.}
{124}{}{Paneèku, to je pech -- já ho mám taky v jednom kuse.}
{125}{}{Co se ti dìje teï?}
{126}{}{U mi nìkdo øíkal. Zdar.}
{127}{}{Tak o co tu jde teï, co tì tak otravuje?}
{128}{}{Opravdu nemám zájem poslouchat nìco takového. Myslím, e radši pùjdu.}
{129}{}{Dobrá, cestoval jsem sám pøes pouš, kdy tu náhle moje brahmíny padli mrtvé k zemi. Potom mi došlo, e mám málo vody, a e jsem nepil u nìjakou chvíli. Potom mne zaèaly bolet kosti, hlava, støeva a dostal jsem tuhle vyráku, take jsem nemohl jít dál.
 Byl èas odplíit se zdechnout do houští.}
{130}{}{Ja... uh... ty... Máš dìti a enu?}
{131}{}{U ani slovo. Jdu pryè.}
{132}{}{U nechci nic slyšet. Musím se odsud dostat pryè a hlavnì daleko od tebe. Tak èau.}
{133}{}{Prosím, øekni, e jsi nemìl dìti.}
{134}{}{Ne. Kdy mi bylo dvaadvacet, tak taková divná houba zaèala rùst na mém pindík-....}
{135}{}{Arrgh! U dost! Odcházím!}
{136}{}{Zadr! Nechci to vìdìt!}
{137}{}{Oh. Ahoj. Co pro tebe mùu udìlat?}
{138}{}{Uh, cos to poslednì vykládal za historku?}
{139}{}{Promiò. Jdu pryè.}
{140}{}{Zajímalo mne, jestli mi  zopákneš svoji zkazku.}
{141}{}{Momentík, vypadals jako nìkdo jinı, omyl.}
{142}{}{Koneènì, mùj èas nadešel. Zabiješ mne?}
{143}{}{Ale jo.}
{144}{}{Ne.}

{145}{}{Kdy mi bylo osm, mého pejska Spajka zajel traktor. Kdy mi bylo devìt, matka pøišla o ruku kvùli vzteklımu brahminímu samci. Kdy mi bylo deset, moji sestru roztrhali psi. Kdy mi bylo jedenáct, mùj dìda se sám zabil, protoe byl vošklivej. Kdy mi bylo dvanáct, zabila se moje babka, protoe byla vošklivá. Kdy mi bylo tøináct, mùj táta si v opilosti vypíchl oèi vidlema.}
{146}{}{Kdy mi bylo ètrnáct, mùj brácha ztratil ruku kvùli klokanovi. Kdy mi bylo patnáct, moje teta se udusila kuøecí kùstkou. Kdy mi bylo šestnáct, mého bratrance zakousl jezevec. Kdy mi bylo sedmnáct, usekl jsem si palec na noze motykou. Kdy mi bylo osmnáct, mému tátovi ujel pravou nohu ten samej traktor, co zajel mıho pejska. Kdy mi bylo devatenáct... }

{147}{}{Take, sedìl jsem na poušti a èekal, a smrt ukonèí mojí mizernou existenci,
 kdy tu se objevila tlupa deathclawù. Hm, pomyslel jsem si, a je to tady. Teïka umøu. Ale... osud mìl ještì jeden krutı trumf v rukávu.}
{148}{}{Jak vidíš, deathclawové mì nezabili. Místo toho mi dali vodu, vzali mne sem, dali mi tuhle místnost, jídlo, umyli mne a teï mne nechtìjí nechat odejít. Já vím, e si mne šetøí z nìjakého neznámého, pøíšerného dùvodu. Stále jim opakuju, e bych asi pravdìpodobnì chutnal lépe, kdybych byl hubenı a libovı, ale oni nic. Oni se jen usmívají -- pokud to tak vùbec lze øíct -- a plácají mne po hlavì a øíkají 'ádnı strachy, èéèe, bude to lepší.' Ha! Oba víme, co tím myslí.}
{149}{}{Kadopádnì, aby to bylo co nejhorší, zaèali mi dávat nìjaké prášky. Cítil jsem se nìjak lehkı, take jsem je pøestal brát -- a to je dobøe, e jsem to udìlal. Myslím, e to byly nìjaké oblbováky, protoe jsem po nich mìl pocit, jako kdyby vìci nebyly tak špatné, jako skuteènì jsou!
 To je ale jedno, tohle je všechno. Jen èekám na zvonek k veèeøi, pak zaènou hodovat na mém tlusouèkém tìle.}