#tento soubor pøeložil Vachy - http://vachy.moje.cz
{100}{}{Vidíš deathclawa. Pozoruje tì podivnì inteligentníma oèima.}
{101}{}{Vidíš deathclawa Dara.}
{102}{}{Vidíš typického deathclawa. Je rozložitý, má silné tìlo, ostré zuby a dlouhé drápy.}
{103}{}{Zdar èlovìèe.}
{104}{}{Co potøebuješ?}
{105}{}{Ahoj. Kdo jsi?}
{106}{}{Co tady dìláš?}
{107}{}{Jsi stejnì chytrý, jako ostatní?}
{108}{}{Jsem znudìn, pùjdu.}
{109}{}{Promiò, že ruším, ale kdo jsi?}
{110}{}{Jaká je tvoje práce tady ve vaultu?}
{111}{}{Prosím neuraz se, ale jak moc jsi vzdìlaný?}
{112}{}{Hmm, jen se poflakuju.}
{113}{}{Já Dar, váleèník.}
{114}{}{Ok.}
{115}{}{Jste naprosto stejní. Odcházím.}
{116}{}{Jsem} #continue 137
{117}{}{Aha. Budu muset jít.}
{118}{}{Já jsem} #continue 138
{119}{}{Jo.}
{120}{}{Váleèník! Ha! To se povedlo. Umíš ještì nìco?}
{121}{}{Dar hlídá sál a udržuje klid. Nic víc.}
{122}{}{Slyšel jsem.}
{123}{}{Ok.}
{124}{}{Hm, dìláš to dobøe, Dare. Jen tak dál.}
{125}{}{Jo, taky bych øekl.}
{126}{}{Nic nového. Myslím, že pùjdu.}
{127}{}{Jak tu mùžeš mít klid s takovým ksichtem?}
{128}{}{Nejsi hodný. Jdi pryè.}
{129}{}{Ne moc, ale uèím se. Gruthar -- náèelník -- øíká nám všem uèit.}
{130}{}{Starší u nás ve vesnici taky.}
{131}{}{Aha.}
{132}{}{Gruthar dìlá dobøe; mìli byste se snažit sami vzdìlávat.}
{133}{}{Jo.}
{134}{}{Takže, jsi tak hloupý, že ti nìkdo další musí øíct, aby ses uèil. Nádhera.}
{135}{}{Ahoj.}
{136}{}{Grrrrrrrrr! Argggggghhhh.}

{137}{}{.}
{138}{}{, Dar.}
