#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš zahalenou postavu.}
{101}{}{Vidíš Gorise, uèence.}
{102}{}{Vidíš humanoida v hávu s dlouhımi rukávy a kapucí. Je tu nìco nepøirozeného, ale nemáš jistotu, co to pøesnì je.}
{103}{}{Ahoj, já jsem Goris. Neznám tì; jsi tady novı?}
{104}{}{Jsem} # 213
{105}{}{Jdu pryè.}
{106}{}{Jo, take co?}
{107}{}{Ahoj. Já jsem} # 214
{108}{}{Ahoj, Gorisi. Gruthar øíkal, e tì mám vyhledat. Myslí si, e znáš odpovìdi.}
{109}{}{Mùu se tì na nìco zeptat?}
{110}{}{Promiò, musím jít.}
{111}{}{Rád tì potkávám,} # 215
{112}{}{Take znáš Gruthara. Má o mne trochu zkreslenou pøedstavu. Já opravdu nevím ani polovinu z toho, co si on myslí, e vím. Kadopádnì...}
{113}{}{Take jsi z venku! U jsem vidìl nìkolik takovıch jako ty; nìkteøí jsou tady ve Vaultu, ale
 ty vypadáš jinak. Vypadáš trochu víc 'vyzrálejší,' pokud víš, co tím myslím. Sazím, e trochu cestuješ
 a vyøizuješ svoje záleitosti. Mám pravdu?}
{114}{}{Uh... 'vyzrálejší'?}
{115}{}{Jdu.}
{116}{}{Promiò, ale asi tì opustím.}
{117}{}{Ano, mám za sebou nìjaká dobrodruství. Podívej, pokud ti nebude vadit odpovìdìt mi na pár otázek, já ti povím na oplátku o svıch dobrodrustvích.}
{118}{}{Nic, co by tì mìlo zajímat.}
{119}{}{Nebude ti vadit, kdy se tì na nìco zeptám?}
{120}{}{Dohodnuto! Rád si poslechnu všechno, co mi mùeš øíct.}
{121}{}{Krom toho, nemùu odmítnout Grutharova kamaráda.}
{122}{}{Co potøebuješ vìdìt?}
{123}{}{Co tady dìláš?}
{124}{}{Jsi tu vìzeò?}
{125}{}{Jak dlouho jsi tady?}
{126}{}{Co mi mùeš øíct o deathclawech tady?}
{127}{}{Víš, co se stalo s lidmi, kteøí zde ve vaultu ili?}
{128}{}{Co mi mùeš øíct o Grutharovi?}
{129}{}{Myslíš, e deathclawové mohou bıt pro lidi hrozbou?}
{130}{}{Máš nìjaké informace o té Enklávì, o které jsi mluvil?}
{131}{}{Co víš o tomto viru?}
{132}{}{Øekl jsi, e bys rád cestoval. Co tøeba jít se mnou?}
{133}{}{Promiò, ale musím jít.}
{134}{}{Hmm... pøekvapuje mne, e ti Gruthar o mnì neøekl. Ale budi. }
{135}{}{Jsem nìco jako student. Snaím se dovìdìt co nejvíce o svìtì
 a rùznıch kulturách, které se zde formují. Právì teï studuji spoleènost, kterou
 zde vytváøejí deathclawové, a srovnávám ji s lidskou na základì spoleènıch rysù.
 U jsem zjistil všechno, co jsem potøeboval. Velice by mi pomohlo, kdybych teï mohl
 trochu cestovat a prohloubit tak svùj prùzkum, ale nerad bych cestoval sám.}
{136}{}{Zajímavé. Mùu se ještì na nìco zeptat?}
{137}{}{Take ty jsi uèenec. To je docela rarita v dnešních dobách.}
{138}{}{Jak nudné. Ale budi... je to tvùj ivot, kterım tady plejtváš. U nechci nic víc.}
{139}{}{Ne, mohu odejít kdykoli se mi zachce. Neodešel jsem, protoe nechci cestovat osamocen. Jsem celkem tvrdı,
 dokáu se o sebe postarat, ale poøád budu jen jedna osoba v poušti, pokud se nìco stane.}
{140}{}{Jasnì.}
{141}{}{Aha, trochu srábek na to, aby šel sám po svıch. Je mi to jasné.}
{142}{}{Já taky nesnáším cestování o samotì, nebudu ti nic nalhávat.}
{143}{}{Uh... asi nìkolik mìsícù. Pøišel jsem od pobøeí u pøed nìjakım èasem.}
{144}{}{Hmm, jsi tu dost novı. Pokud ti to nevadí, chci vìdìt víc.}
{145}{}{Moc jsi mi toho neøekl. Nechceš øíct víc?}
{146}{}{Hm. Mám tu ještì pár vìcí.}
{147}{}{Tihle nejsou bìní deathclawové, jak urèitì víš. Mají svoji inteligenci posílenou nìèím,
 co sami nechápou. Bylo to zpùsobeno skupinou lidi známıch jako 'Enkláva.' Zdá se, e tato Enkláva
 potøebovala vojsko, a e zvolila právì deathclawy pro jejich odolnost,fyzickou sílu a... hmm, u víš co
 mám na mysli. Kadopádnì, jediná chybka deathclawù byla jejich inteligence. Potøebovali je dostateènì chytré
 na to, aby pochopili sloité rozkazy, ale ne natolik chytré, aby ohrozili "ty u vesla".}
{148}{}{Tohle zavání jako nejpodlejší levárna pod sluncem!}
{149}{}{Neuvìøitelné. Jsi velmi vzdìlanı. Mùu se na nìco zeptat?}
{150}{}{Hmm...Ok.}
{151}{}{::vzdech::) Byli zajati Enklávou. Gruthar a jeho smeèka byli donuceni pomáhat pøi jejich zatèení. Nemìli
 na vybranou, protoe v té chvíli byli sami jen otroky. Osud lidí od té doby velmi tíí Grutharovo svìdomí. Nikdy
 si neodpustil úèast v této záleitosti. Lidé byli zajati iví, ale kdo ví, co se s nimi od té doby stalo?}
{152}{}{(Vzdech) Byli zajati skupinou zvanou 'Enkláva.' Gruthar a jeho smeèka byli nuceni pomáhat pøi jejich zajetí.
 Nemìli na vıbìr, protoe v té dobì byli sami jen otroky. Osud lidí od té doby velmi tíí Grutharovo svìdomí. Nikdy
 si neodpustil úèast v této záleitosti. Lidé byli zajati iví, ale kdo ví, co se s nimi od té doby stalo?}
{153}{}{Hmm...Chci se ještì na nìco zeptat.}
{154}{}{Tak ti zatracení deathclawové byli pøeci nìjak zodpovìdní! Pøesto chci vìdìt víc.}
{155}{}{Nìkdy se situace vymkne z rukou a my jsme nuceni dìlat nepøíjemné vìci. Gruthar by se mìl nauèit odpouštìt si.}
{156}{}{Gruthar není zrùda, jak by se mohlo zdát. Svìdomitì se tady o
 nás o všechny stará a dìlá všechno, co mùe, pro naši bezpeènost
 a pøeití. Vìøíme mu. Nevím, co víc o nìm øíct. Lepší
 bude, kdy ho nejprve poznáš a pak posoudíš dle svého.}
{157}{}{Nebudu ohlednì nìj dìlat ádné ukvapené závìry. Uvidím, jakı je.}
{158}{}{Jistì. Obrame list.}
{159}{}{On je deathclaw. Je tìké uvìøit, e by mohl mít i nìjaké kvality.}
{160}{}{Dobrá...je tu šance, specielnì kdy bereš v potaz jejich novou, inteligenci. Kadopádnì, nemyslím, e Gruthar
 a jeho smeèka pøedstavují hrozbu. Zdá se, e oni všichni respektují ivot a osobní svobodu pøed èímkoli jinım.
 Neoèekávám, e se teï spolehneš na moje slovo. Posuï to dle vlastních zkušeností. Jsou tady další, které mùeš
 vyzpovídat.}
{161}{}{Jedinì blb nedokáe v deathclawech rozpoznat potenciální hrozbu!}
{162}{}{Dìkuji za radu; poptám se kolem. Pøesto, mùu se tì ještì na nìco zeptat?}
{163}{}{Hmm...Ok, co takhle pár dalších otázek?}
{164}{}{Ne, všechno u bylo øeèeno. I kdy, poèkej, ještì jedna vìc. Enkláva projevovala jistı zájem o ruiny na západ odsud. Nevím proè. To je to.}
{165}{}{Dobøe, kadı kousek informace mùe pomoci a  já ti za to dìkuji.}
{166}{}{Taková dùleitá vìc a ty to na mne vybalíš a teï!}
{167}{}{No jo.}
{168}{}{Myslím, e se to nazıvá virus FEV. Enkláva, nebo co, to usilovnì zkoumá. Je mi líto, ale u nic dalšího nevím.}
{169}{}{To je v poøádku, jdem dál.}
{170}{}{To by mìlo. Bylo mi øeèeno, jakı jsi velkı hlavoun!}
{171}{}{Byl jsi víc ne nápomocnı, Gorisi.}
{172}{}{Dodrel jsem svou èást dohody a odpovìdìl na všechno. Nyní, co takhle ty dobrodruné historky, jak jsi slíbil?}
{173}{}{S potìšením. Dobøe se mi s tebou povídá.}
{174}{}{Slib? Jakı slib?}
{175}{}{Hmm, jistì.}
{176}{}{(Goris dramaticky mlèí a ty cítíš, e tì podrobuje podrobnému zkoumání.) Bude mi ctí tì doprovázet!}
{177}{}{(Goris dramaticky mlèí a ty cítíš, e tì podrobuje podrobnému zkoumání.) Promiò, ale myslím, e nesdílíme stejné názory. Spoleèná cesta nemusí bıt v zájmu nás obou.}
{178}{}{Bezva, tvoje mínus}
{179}{}{Chápu. Moná èasem zmìníš názor.}
{180}{}{Co? Tak já nejsem pro tebe dost dobrı, jo? Chcípni!}
{181}{}{Ok, chápu.}
{182}{}{Nemám co øíct. U mne pøíštì neobtìuj.}
{183}{}{ádal jsem tì, a mne u neotravuješ. Zdá se, e násilí je jediná øeè, které rozumíš.}
{184}{}{}
{185}{}{No jo, však víš, zcestovalı...vzdìlanı...zkušenı... Asi nevíš, o èem mluvím, co? }
{186}{}{Èert ví, já ne.}
{187}{}{Jdu.}
{188}{}{Uh huh. Dobrá, tvoje IQ asi bude menší, ne èíslo tvıch bot, ale zjevnì pro tebe nìco pracuje, kdy
 v tomhle svìtì pøeíváš tak dlouho... Ok, zkusme tohle. Chci odejít. Chci jít s tebou. Ok?}
{189}{}{Uh huh. Dobrá, tvoje IQ asi bude menší, ne èíslo tvıch bot, ale zjevnì pro tebe nìco pracuje, kdy
 v tomhle svìtì pøeíváš tak dlouho... to musí bıt ta síla, kterou v tobì cítím. Bezva. Nashledanou.}
{190}{}{Uh...Ok.}
{191}{}{Jdu.}
{192}{}{Promiò, nechci ti lézt do soukromıch záleitostí.}
{193}{}{No prima, o co, e to znovu neudìláš?}
{194}{}{Jasòaèka. Potøebuju ještì pár informací.}
{195}{}{Promiò, Gorisi. U mne dnes chytá rapl. Chci se tì ještì zeptat na pár vìcí, pokud ti to nevadí.}
{196}{}{To byly zajímavé èasy, koukám. Jsi ze stejného tìsta, z jakého bıvají hrdinové a já tì ctím. Dìkuji ti za povídání.}
{197}{}{Dobrá... pracuješ na krvavém úkolu a já asi pùjdu. Díky a zdar!}
{198}{}{Jsi vítán, Gorisi.}
{199}{}{Nazdárek, tak se zas vidíme. Co je?}
{200}{}{Pøicházíš k mnì?}
{201}{}{Uh...jsem mimo, zdar.}
{202}{}{Jen mne napadlo se tu zastavit a pozdravit tì. Uvidíme se pozdìji.}
{203}{}{Hej, hledám spoleèníka na cesty. Jdeš do toho?}
{204}{}{Co pro tebe mùu udìlat,} # 216
{205}{}{Hnusáku! Proè nic neøíkáš?}
{206}{}{Ty jsi deathclaw? Je zde nìjakı dùvod, proè jsi mi to neøekl?}
{207}{}{A jak by sis to asi vysvìtlil... Špatná vìc, co mùeš bez øeèí zabít. No a co, tak sem ti to neøekl a teï mì vidíš ve špatném svìtle. Nezabiješ-li mì, budu navdy tvùj pøítel.}
{208}{}{Promiò, e jsem tì obelstil, ale vy lidé máte zvyk støílet deathclawy na potkání. Domníval jsem se,
 e by to pro mne mohlo bıt plus skrıt mou totonost dokud sám nepøijdeš na to, e jsem na tvé stranì. Jestli chceš
 abych odešel, odejdu. Radìji bych ale zùstal a pomohl ti s tvım úkolem. Chci dokázat, e lidé a deathclawové
 mohou spolupracovat jako pøátelé a ne jako nepøátelé.}
{209}{}{Nelíbíš se mi, padej.}
{210}{}{Ok, zùstaò.}
{211}{}{Nemám rád, kdy mne nìkdo tahá za fusekli. Mìl bys jít.}
{212}{}{Rozumím, proè ti pøipadalo nezbytné skrıt svou totonost. Myslím, e mùeme pokraèovat spolu, take prosím zùstaò -- ale u mne nebalamu, Gorisi.}

# the name usually precedes these lines
{213}{}{. Jsem tu novı.}
{214}{}{. Ano, nepocházím z Vaultu.}
{215}{}{.}
{216}{}{?}
{217}{}{Enkláva zaèala machrovat s tím virem, nebo nìèím podobnım a napíchala ho deathclawùm. O tomto
 viru bylo známo, e zmutuje èlovìka v jakousi superbytost, take Enkláva byla zvìdavá, co to udìlá
 s deathclawy. Mòo, vısledkem bylo vyšlechtìní deathclawù tak chytrıch, e poznali, e nebyli stvoøeni
 pro otroctví. Take hráli hlupáky do té doby, ne se mohli dostat na svobodu. A tak jsme tady!}
{218}{}{Jsem proti ubliování deathclawùm.}
{219}{}{Najednou mám pocit, e je moje smeèka v nebezpeèí. Je mi líto, e tì musím opustit, ale musím to zkontrolovat.}
{220}{}{Ok.}
{221}{}{Bezpeèností kamery zachytily, co se stalo.}
{222}{}{Vidíš šedého deathclawa. Je to Goris.}
{223}{}{Vidíš humanoidní postavu v dlouhém hávu s kapucí. Je to Goris.}

#specific party messages
{1064}{}{Dr se mne.}
{1065}{}{Nevzdaluj se.}
{1066}{}{Jsme moc blízko, rozptylme se.}
{1073}{}{Dr se mne.}
{1074}{}{Neutíkej moc daleko.}
{1075}{}{Mìli bychom se trochu roztáhnout.}
{1001}{}{Dej se do kupy.}
{1002}{}{Poèkej tu. Za okamik budu zpìt.}
{1003}{}{Uh... ádnou zbraò. Ok?}
{1167}{}{Myslím, e by ses mìl jinak pohybovat.}
{1167}{}{Myslím, e by ses mìl jinak pohybovat.}
{1008}{}{Jsi deathclaw, proè's nic neøekl?}
{1009}{}{Hotovo.}
{1010}{}{Mìl by ses teï vyléèit.}
{1011}{}{Potøebuju, abys tu poèkal dokud se nevrátím.}
{1012}{}{Tvaø se mírumilovnì, ok?}
{1166}{}{Co takhle se trochu rozdìlit?}
{1016}{}{Jdem.}
{1017}{}{Jsi deathclaw? Je zde nìjakı dùvod, proè jsi mi to neøekl døív?}
{1018}{}{To je zatím všechno.}
{1000}{}{Ano,}
{1156}{}{? }
{1019}{}{Jsem zdravı schopnı jít dál,}
{1020}{}{U jsem skoro v poøádku,}
{1021}{}{Jsem docela v poøádku, ale pokud to bude moné, nepohrdnu pomocí,}
{1022}{}{Udìlal jsem co jsem mohl, ale stále jsem na mraky,}
{1157}{}{. }
{1041}{}{Poèkám tu na tebe,}
{1060}{}{Dìlám jak umím,}
{1079}{}{Budu se dret tak blízko, jak to jen jde,}
{1078}{}{To je zatím vše.}
{1098}{}{Trochu se projdu a nechám ti oddych,}
{1117}{}{Zabalím to a nechám ti volno,}
{1136}{}{Promiò,}
{1158}{}{, ale máš s sebou trochu moc lidí. Poèkám tu, dokud se nìjaké místo neuvolní.}
{1159}{}{Myslím, e bude lépe, kdy pùjdu po svıch.}
{1160}{}{Nepatøíš k tìm, které bych potøeboval poblí, odcházím.}
{1137}{}{Nauèil jsem se hodnì na cestách. Pùjdu s tebou rád, }
{1161}{}{Pøeju si pomstít mùj druh.}
{1162}{}{Dobrá, udìláme to.}
{1163}{}{Moná bys to mìl udìlat sám.}
{1164}{}{Máš pravdu, budeme zabíjet.}
{1165}{}{Jdi sám.}
