#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš shrbeného mue v dlouhé róbì. Vypadá hluboce zamyšlen.}
{101}{}{Vidíš Stráce Svatynì.}
{102}{}{Vidíš shrbeného mue v dlouhé róbì.  Je to ètyøiceti-padesátiletı mu s jemnımi rysy. Vypadá jako by meditoval.}
{103}{}{Vítej, poutníèe. Nazıvají mì Gordonem a jsem Stráce Svatynì. S èím ti mohu pomoci?}
{104}{}{Svatynì?}
{105}{}{Mohu se na nìco zeptat?}
{106}{}{Jo.....nevzpomínám si. Èau.}
{107}{}{Rád tì potkávám Gordone. Já jsem} # continued 177
{108}{}{Tomuhle øíkáš Svatynì? Kdokoli, komu je to zasvìceno, se musí obracet v hrobì!}
{109}{}{Ne, promiò vyrušení. Pùjdu.}
{110}{}{Tak jest. Svatynì je místo k uctívání, obvykle je zasvìcené bohu, svatému nebo jiné bytosti moci.}
{111}{}{Aha. Ok. Mùu se tì na nìco zeptat?}
{112}{}{Ok. Zdar.}
{113}{}{Samozøejmì.}
{114}{}{Co potøebuješ vìdìt?}
{115}{}{Èí je ta svatynì?}
{116}{}{Jak dlouho tu jsi?}
{117}{}{Deathclawové jsou špatní?}
{118}{}{Proè tu zùstáváš?}
{119}{}{Radši u pùjdu.}
{120}{}{Komu je tato svatynì zasvìcená?}
{121}{}{Jak dlouho jsi tu?}
{122}{}{Co mi mùeš øíct o deathclawech?}
{123}{}{Proè tady setrváváš?}
{124}{}{Díky, Gordone. Nashledanou.}
{125}{}{Tato svatynì je zasvìcena bezejmennému hrdinovi, známému pouze jako Zakladatel. On, moná ona, byl zachráncem všech, kdo zde ili v minulosti. Nevíme, co se stalo s naším zachráncem, ale on, nebo ona, ije stále v našich myslích a srdcích.}
{126}{}{Milé.}
{127}{}{Dík. Pa pa.}
{128}{}{K smíchu! Kaplièka nìkoho, koho si ani nemùeš pamatovat!}
{129}{}{Aha. No, mám tu ještì pár otázek.}
{130}{}{Kdy øíkáš, Gordone. Mùu se tì ještì na nìco zeptat?}
{131}{}{il jsem v tomhle bunkru celı ivot. Vìtšinu tìch let jsem byl Strácem Svatynì.}
{132}{}{Byl jsi tu døíve ne deathclawové?}
{133}{}{Aha. U nic nepotøebuju.}
{134}{}{Musím jít.}
{135}{}{Jsi velikı svìtec. Mùu se ještì na nìco zeptat?}
{136}{}{To je dlouhá doba. Mùeš mi odpovìdìt ještì na pár otázek?}
{137}{}{Je to tvùj ivot, kterej tady zbyteènì utrácíš, kámo.}
{138}{}{Take ty jsi tu byl, kdy to tu pøevzali deathclawové?}
{139}{}{Ne, mùj pøíteli, nebyl jsem tu. Odešel jsem pøed nìkolika mìsíci, abych se podíval na sochu Zakladatele vztyèenou na námìstí v NCR (New California Republic na vıchod odsud). Kdy jsem se vrátil do bunkru, deathclawové tu u byli. Nemùu si pomoci, ale byl jsem v šoku. Kadopádnì, jsem pøesvìdèen, e oni nejsou odpovìdni za to, co se stalo obyvatelùm. Pokud bys chtìl náhodou více informací o této záleitosti, podívej se v knihovnì po Gorisovi.}
{140}{}{Ok, dík.}
{141}{}{Ok, zdar.}
{142}{}{Budu si to pamatovat.}
{143}{}{Nepotøebuju, abys mi øíkal, kam mám chodit nebo s kım se mám seznámit.}
{144}{}{Dìkuji ti za pomoc. Pøesto mám ještì pár otázek.}
{145}{}{iju jsem s deathclavy u pár mìsícù. Jednají se mnou a ostatními lidmi, co tu ijí, èestnì a upøímnì. Vìøím jim a myslím, e ty, po èase, také budeš.}
{146}{}{Uh... Budi.}
{147}{}{Aha, hmm. U pùjdu.}
{148}{}{Hodlám jim dát šanci, ale prozatím budu pochybovat.}
{149}{}{Ty mùeš ještìrkám vìøit, kdy chceš, ale já si prozatím nechám svùj názor, pokud dovolíš.}
{150}{}{Dìkuji. Potøebuju vìdìt víc.}
{151}{}{Moje místo je zde ve Svatyni. Dobrovolnì ji neopustím.}
{152}{}{Aha.}
{153}{}{Víš, asi pùjdu.}
{154}{}{OK.}
{155}{}{Buï jsi svìtec nebo pitomec. Sázím, e spíš pitomec!}
{156}{}{Tvoje odhodlání je obdivuhodné.}
{157}{}{Jsi hrubı a sprostı. Moná, e kdyby tu byla jedna ze stráí, mluvil bys jinak.}
{158}{}{U døíve jsem tì varoval, e nebudu tolerovat tvoje vıhruky. Zjevnì jsi se rozhodl ignorovat moje varování. (Gordon se otáèí ke stráci) Stráe! Do Svatynì, prosím!}
{159}{}{Take stále volíš bıti hulvátem. (Gordon se otáèí ke stráci) Strá, prosím vyneste odpadky.}
{160}{}{Jen si volej na svoje mazlíèky! Nakopu vás všechny do øiti, ani nemrkneš.}
{161}{}{Promiò, u budu dret jazyk za zuby.}
{162}{}{Omlouvám se, Gordone. Prosím, promiò mi mùj úlet.}
{163}{}{Omlouvám se. Ujel jsem. Odpus mi.}
{164}{}{Jé, promiò.}
{165}{}{Tìším se a rozstøílím nìjakou ještìrku!}
{166}{}{Strá! Do Svatynì!}
{167}{}{}
{168}{}{}
{169}{}{Take ses vrátil. Dal jsem tì vyhodit jednou a mùu to udìlat zas. Stráe! Do Svatynì! Ten póvl je zpátky!}
{170}{}{}
{171}{}{}
{172}{}{Vítej zpìt. Co pro tebe mùu udìlat?}
{173}{}{Mùu se na nìco zeptat?}
{174}{}{U to tady znám? Promiò. Musím jít.}
{175}{}{ Chci si s tebou ještì jednou popovídat.}
{176}{}{Jen ti chci øíct ahoj.}

{177}{}{. Mùu ti poloit pár otázek?}
