#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš velikého deathclawa. Tvor má mohutné svalstvo, ostré zuby a drápy.}
{101}{}{To je Gruthar, vùdce deathclawù.}
{102}{}{Vidíš toho nejpùsobivìjšího deathclawae, jakého si jen okáeš pøedstavit. Tvor musí bıt unikátem ve svém druhu.}
{103}{}{Neboj se mne, èlovìèe, nechci ti ublíit. Jsem Gruthar, vùdce této smeèky. Proè jsi tady?}
{104}{}{Proè jste sem pøišli?}
{105}{}{Uh...}
{106}{}{Nakopat ti prdel!}
{107}{}{Jak je to moné, e deathclaw mluví...a tak dobøe?}
{108}{}{Chci vìdìt, co se stalo s lidmi, kteøí tu ili.}
{109}{}{Hledám vìc jménem GECK. Bylo mi øeèeno, e tu jeden takovı je.}
{110}{}{...}
{111}{}{Vyšetøuju nájezdy na místní brahmíní farmy. Víš o tom nìco??}
{112}{}{Myslím, e radši pùjdu.}
{113}{}{Nejsi idiot, èlovìèe. Vidím ti to na oèích. Prosím, nezkoušej mne podvést. Nemám èas na takové hry.}
{114}{}{Dobrá, pokud chceš bıt idiot, máš to mít. Vra se sem, a si to rozmyslíš.}
{115}{}{Prosím o prominutí. Vypadáš  intelektuálnì na vıši. Nejsi hrozba pro mne a moji smeèku. Vítám tì tu a mùeš povaovat toto místo za bezpeènı úkryt pøed vnìjším svìtem. Nikomu neubliuj, nedìlej problémy a vdy tu pro tebe bude místo.}
{116}{}{Promiò, nechci bıt hrubı, ale tohle není smysluplná konverzace. Dokái mluvit tvım jazykem a èíst psaná slova. Co mám víc øíct?}
{117}{}{Vidím.}
{118}{}{Nechci dìlat problémy, ale jistì pochopíš mùj zájem na celé téhle záleitosti.}
{119}{}{Aha, co kdybys to nechal na posouzení mì, co je a co není smysluplné?}
{120}{}{Ano, to bych jistì mohl. Dobrá, pokud se rozejdeme v dobrém, èlovìèe, mìl by sis promluvit s Gorisem. má vetší znalosti v tìchhle vìcech ne já. Bude patrnì v knihovnì.}
{121}{}{Díky. Tìším se na setkání s Gorisem.}
{122}{}{Nemám ádnou chu pøidávat dathclawy do seznamu mıch pøátel, nashledanou!}
{123}{}{Dobrá.}
{124}{}{Jsou pryè, èlovìèe. Nezabili jsme je a nesebrali jim jejich domov. To není náš styl, zabíjet. Já pochopím, pokud mi nebudeš vìøit, ale zároveò doufám, e mne budeš soudit na základì mıch èinù a ne dle pøedsudkù.}
{125}{}{Hele, nebude ti vadit, kdy ti nakopu prdel?}
{126}{}{Vypadáš jako èestnı mu :), Gruthare.}
{127}{}{Aha, to se dalo èekat.}
{128}{}{GECK. Není to ta malá ještìrka... ne, poèkat...to je geckon. Promiò, ale nevím, co to je GECK, ani kde by se tu v okolí dal najít.}
{129}{}{Ano, myslím, e jsi to u jednou zmínil.  Nevím, co to je GECK, ani kde se tu dá najít.}
{130}{}{Necháš mne podívat se tu po nìm?}
{131}{}{Hele, to s tou ještìrkou bylo fakt dobrı. Je to nìjakı tvùj pøíbuznı?}
{132}{}{Mluvení s tebou je zjevná ztráta èasu. Nashledanou.}
{133}{}{Mám-li bıt upøímnı, ani já pøesnì nevím, co to je.
 Bude to v poøádku, kdy se tu po nìm poohlédnu?}
{134}{}{Promiò, ale nemùu pustit jen tak nìkoho sem do tìchto prostor. Jsem zodpovìdnı za ivoty všech, co tu jsou a musím se cvièit v opatrnosti. Ale podívám se ti po tom gecku a dám ti vìdìt.}
{135}{}{Promiò, ale nemùu pustit jen tak nìkoho sem do tìchto prostor. Jsem zodpovìdnı za ivoty všech, co tu jsou a musím se cvièit v opatrnosti.}
{136}{}{Podívej, tohleto tady ti nepatøí, moná se podívám okolo bez ohledu na to, jestli se ti to líbí nebo ne!}
{137}{}{Rozumím, Gruthare, a budu respektovat tvé pøání.}
{138}{}{Chápu tvùj zájem. Neznáš mne na tolik, abys mi vìøil. Co kdybych ti s nìèím pomohl a ty mne to tu na oplátku necháš prozkoumat?}
{139}{}{(Gruthar tì chvilku se zájmem pozoruje.) Chtìl bys nám pomoci? Ano, jsi mazanı. ale dobrá, budu ti dùvìøovat.}
{140}{}{(Gruthar tì chvilku se zájmem pozoruje.) Myslím e ne, cítím v tobì ïábla èlovìèe.
 Nemùu riskovat ivoty tìch, které chráním tím, e ti dám šanci.}
{141}{}{Díky.}
{142}{}{Bezva. Myslím, e kule mezi voèi vyøeší celej problém.}
{143}{}{Je mi líto, e to bereš takhle, Gruthare.}
{144}{}{Tak tedy odcházím.}
{145}{}{Je tu mnoho strojù, strojù postavenıch lidmi. Ruce deathclawù je nemohou uívat. Kadopádnì, je tu stroj, kterı rozumí otázkám. Poádal jsem to, aby to  rozchodilo ostatní stroje a ono to tak udìlalo. Tento stroj u ale víc nereaguje. Nebude ji udrovat v chodu ostatní stroje. Dochází nám jídlo a voda. Rozkázal jsem nájezdy na lidské usedlosti okolo, take dokáeme pøeít. Nejsem na to hrdı a rád bych to ukonèil. Pokud opravíš ten stroj, budu schopen krmit své lidi dál. Rád zastavím nájezdy. Souhlasíš s tím?}
{146}{}{Promiò, ale nemám ponìtí jak opravit takovı stroj.}
{147}{}{Nejsem technik, ale mùu to zkusit.}
{148}{}{Hmm...zdá se, modul pro hlasové povely odešel. Pojïme se podívat.}
{149}{}{Rozmyslel jsem si to, radši si to ještì jednou nechám projít hlavou.}
{150}{}{Udìlám, co budu moci.}
{151}{}{Odmítám pomáhat deathclawùm.}
{152}{}{Dìkuji ti. Stroj je v øídícím centru ve tøetím patøe. Pokud to pùjde opravit, udìlej to. Vìøím ti, nezraï mne. Jsi tu vítán.}
{153}{}{Nezklamu tì, Gruthare. Máš moje slovo.}
{154}{}{Díky. Spoléhám se na to.}
{155}{}{Tady se skuteènì rodí jeden kadou minutu...}
{156}{}{Aha...deathclawové jsou od pøírody nebezpeèní a je dobré bıt velice opatrnı, kdy je potkáš v divoèinì. Kadopádnì, jak jistì vidíš, jsme vıjimka. Moje smeèka není hrozbou pro lidi. Vyvinuli jsme se nad naše pøíbuzné a chceme mít prostì klid.}
{157}{}{Uh...jo.}
{158}{}{Vaše zvıšená inteligence z vás dìlá vìtší hrozbu, ne pøedstavuje obyèejnı deathclaw,
 Gruthare.}
{159}{}{Vidím, e nejste brutální zabijáci, jak se o deathclawech øíká.}
{160}{}{Strávil jsem mnoho probdìlıch nocí, hluboce zamyšlen, uvaujíc o takovıch vìcech. A nakonec jsem došel k závìru, e uvìdomìní a povinnost spojená s darem inteligence je nevypoèitatelná. Jsou tu dvì monosti pro kadou myslící bytost. Pøijmout ivot a dìlat to nejlepší pro sebe a okolí a nebo prostì bıt. Vybral jsem si pøijmout vızvy ivota. Jestlie mne tohle èiní hrozbou pro lidstvo, pak lituji pøízemních chudákù, kteøí to tak berou ...}
{161}{}{Hmm.....moná jsem pøízemní chudák, ale mám VELIKİ kvér.}
{162}{}{Nemùu nesouhlasit. Nemyslím, e jste hrozbou, Gruthare.}
{163}{}{Aha...jo. Tak to je, pøesnì jak øíkáš.}
{164}{}{(Gruthar mlèí a zvauje dopad své reakce na tebe) Je mi líto, e jsem naøídil nájezdy na ty lidské usedlosti. Jsem zodpovìdnı za mnoho ivotù tady. Dochází nám jídlo, voda i další zásoby. Dokud se situace nezlepší, musím si já, deathclaw, brát od lidí vše, co potøebuji, bez ptaní.}
{165}{}{Nyní, kdy znám pùvodce nájezdù, tak ho prostì eliminuju!}
{166}{}{Je mi to líto. Mohu nìjak pomoci, aby se ty nájezdy zastavily?}
{167}{}{U vím dost, zatím. Potøebuji to promyslet.}
{168}{}{Vidím...}
{169}{}{Tvoje rozhodnutí se mi hnusí, ale beru ho. Mùeš odejít, ale prosím vra se, pokud si to rozmyslíš.}
{170}{}{Ujednáno.}
{171}{}{Helou,} // Goes to 231
{172}{}{Uvidíme.}
{173}{}{Je mi líto, Gruthare. Hlasovı modul odešel. Budu muset najít jinı.}
{174}{}{Nerozumím takovım vìcem, ale vìøím ti,} // 232
{175}{}{Ok.}
{176}{}{Vrátím se, máš moje slovo.}
{177}{}{Helou,} // 233
{178}{}{Ne, stále hledám.}
{179}{}{Ano a tady to je!}
{180}{}{}
{181}{}{Obnovuješ moji dùvìru v lidi. Dìkuji ti za všechno, cos udìlal pro smeèku. Mohu ti to nìjak oplatit?}
{182}{}{Øekl's, e mi dáš vìdìt, pokud najdete GECK. Máte nìjakı?}
{183}{}{Ano, hledám GECK. Bylo mi øeèeno, e by mohl bıt zde. Víte kde je??}
{184}{}{Ne. Mám všechno co potøebuju.}
{185}{}{Ano, jeden GECK je ve skladu. Je tvùj a moc ti dìkuji.}
{186}{}{Ano, jeden byl ve skladišti, ale chybí. Je mi líto, e ti ho nemùu dát jako odmìnu za tvou pomoc.}
{187}{}{Díky!}
{188}{}{Uh...to je v pohodì. Najdu si jinı.}
{189}{}{Ahoj, èlovìèe. Doufám, e mne nechceš tahat za nohu.}
{190}{}{Chci se omluvit a zaèít znova, Gruthare.}
{191}{}{Promiò, musím padat.}
{192}{}{Uh, omlouvám se.}
{193}{}{Zdravím tì, èlovìèe. Zmìnil jsi názor? Pomùeš mi?}
{194}{}{Ne, proklatì. Jen sem si tì chtìl poslechnout, jak dál przníš jazyk.}
{195}{}{Ne, nemyslím.}
{196}{}{Ano, Gruthare. Pomohu ti.}
{197}{}{Zdravím tì, pøíteli. Stroj je prozkoumán?}
{198}{}{ještì ne, ale udìlám to.}
{199}{}{Ahoj kamaráde. Zachránil jsi smeèku a my ti dìkujeme.}
{200}{}{}
{201}{}{}
{202}{}{Chcípni, zrádnı èlovìèe!}
{203}{}{}
{204}{}{}
{205}{}{Nemám s tebou nic co doèinìní, èlovìèe, a ani ádné nechci. Snaím se to s tebou vyøešit v klidu, tak se sna i ty!}
{206}{}{Dobrá, promluvme si.}
{207}{}{Jsi deathclaw a to znamená ortel smrti... pro tebe samozøejmì!}
{208}{}{Promiò, Gruthare. Promluvme si.}
{209}{}{Budi. Odcházím}
{210}{}{Ne. Já jsem tady pánem, já rozhoduji. Jestli se ti to nelíbí, vra se do zemì lidí!}
{211}{}{Trhni si!}
{212}{}{Ok, pùjdu.}
{213}{}{Jistì, Gruthare. Zapomínám se.}
{214}{}{Ujišuji tì, e se tì nesnaím podrazit. Promiò, pokud jsi mìl takovı pocit. Pomùu, pokud budu moci.}
{215}{}{Dobrá, díky.}
{216}{}{Promiò, nedìlám si z tebe blázny.}
{217}{}{Vznešená gesta stranou, kámo. Tohle na mne neplatí.}
{218}{}{(Gruthar vydává sérii zakvílení) Nemùu vlastnit tohle místo, èlovìèe, ale je to mùj domov a domov mnoha dalších, co se spoléhají na mou ochranu. Nenu mne udìlat nìco, èeho budeme oba litovat!}
{219}{}{Promiò; pøekraèuji meze slušnosti.}
{220}{}{K èertu s tebou a takovımi jako ty!}
{221}{}{Hrome! Jdu od toho.}
{222}{}{Dìkuji. Bì do øídící místnosti a oprav hlasovı modul.}
{223}{}{Provedu!}
{224}{}{}
{225}{}{Nyní tu pro tebe není místo. Odejdi.}
{226}{}{Nashledanou}
{227}{}{Nashledanou.}
{228}{}{Hotovo.}
{229}{}{Omluva pøijata, èlovìèe. Pøeji hezkı den!}
{230}{}{Hotovo.}
{231}{}{. Tak co ten poèítaè?}
{232}{}{. Budu èekat tvùj návrat.}
{233}{}{. Máš tu náhradní souèástku?}

#added later
{234}{}{Uh, ok.}
{235}{}{Doufám, e si uíváš pobyt.}
{236}{}{Naneštìstí jsem to musel udìlat. Dovolil sem mu zùstat tak dlouho, dokud nepøedstavuje hrozbu pro smeèku. Vybral si svoji cestu. Doufám, e chápeš.}
{237}{}{Hnus.}
{238}{}{Chápu, Gruthare.}
{239}{}{Ano. Matt je šmejd.}
