#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš hubeného, chytøe vypadajícího mue s tenkımi brılemi.}
{101}{}{To je Jimmy.}
{102}{}{Vidíš hubeného, chytøe vypadajícího mue s tenkımi brılemi. Jeho oboèí je neustále zamraèeno a za neustálého brblání chodí po místnosti.}
{103}{}{Oh, Nazdárek. Jsem Jim nebo Jimmy, chceš-li. Potøebuješ nìco?}
{104}{}{Dívám se.}
{105}{}{Já}
{106}{}{Uh... To mì nesere. Musím jít.}
{107}{}{Jenom se tak poflakuju.}
{108}{}{Ahoj, Jime. Jsem}
{109}{}{Do toho radìji nos nestrkej, zmiz.}
{110}{}{Jen sem se zamyslel, u musím jít.}
{111}{}{Klidnì se dívej jak chceš, ale hlavnì se prosím tì nièeho nedotıkej, je to tady samé citlivé vybavení.}
{112}{}{Jen se budu dívat a nebudu se nièeho dotıkat.}
{113}{}{Jen se dívám. U nebudu rušit.}
{114}{}{Seš horší ne hovnivál. Zmiz.}
{115}{}{Hele, promiò. Myslím e si spolu asi nepokecáme. Dìlej jak umíš.}
{116}{}{Dobrá.}
{117}{}{Rád tì poznávám,}
{118}{}{Co by si chtìl vìdìt?}
{119}{}{Co tu dìláš?}
{120}{}{Co dìlají tyhle stroje?}
{121}{}{Má Vault dozorce. Je tohle dozorèí místnost?}
{122}{}{Jsi tu, protoe tu chceš bıt?}
{123}{}{Co si myslíš o deathclawech?}
{124}{}{Poèítaè potøebuje nìjakou souèástku, víš kde jí sehnat?}
{125}{}{Vím dost, u musím jít.}
{126}{}{Co tu dìláš?}
{127}{}{Naè jsou všechny ty stroje?}
{128}{}{Není to náhodou dozorèí místnost?}
{129}{}{Jsi tu, protoe tu chceš bıt?}
{130}{}{Co si myslíš o deathclawech?}
{131}{}{Poèítaè potøebuje nìjakou souèástku, nemáš náhodou páru, kdyby se dala sehnat?}
{132}{}{Myslím, e u radìji pùjdu.}
{133}{}{Dobrá... máme tu nìjakı problém s poèítaèem. Pokoušel jsem se to opravit. Bohuel moje specializace je software a ne hardware.}
{134}{}{Jakı problém?}
{135}{}{Co je to za problém?}
{136}{}{Ano, Gruthar mi nìco u øíkal a poádal mì a se na to podívám, mohu?}
{137}{}{Hlasovı modul je poškozen, take Gruthar mu nemùe udílet pøíkazy ohlednì chodu Vaultu. Vodní a potravinovı procesor jsou bohuel vypnuty. Energetickı systém je asi další na øadì.}
{138}{}{Proè si nepouil klávesnici?}
{139}{}{Proè si nezadal nìjaké pøíkazy z klávesnice?}
{140}{}{Dobrá, jak mùeš vidìt, je asi ponièenı konektor. Systém neustále odmítá pouít klávesnici. Bohuel opravdu nevím co s tím.}
{141}{}{Dobrá, podívám se?}
{142}{}{Moná, e bych se na to podíval?}
{143}{}{Ano, Gruthar mi nìco u øíkal a poádal mì a se na to podívám, mohu?}
{144}{}{Nue... co mám dìlat, ale si jsi jistı, e tomu rozumíš? Oh, zapomeò na to. Asi u se na tom nedá víc pokazit. Tak s chutí do toho.}
{145}{}{Asi u na tom nemùeš víc pokazit. Tak s chutí do toho.}
{146}{}{Tak jo, ale nejdøív bych se na nìco zeptal.}
{147}{}{V poøádku, ale mìl bych pár otázek.}
{148}{}{Tohle je hlavní poèítaèovı systém a jeho pøídavná zaøízení. Odsud se kontroluje celı vault.}
{149}{}{Uh... co si øíkal.}
{150}{}{Ah, vidím.}
{151}{}{Hlavní dozorce pro Vault bıval umístìn zde. Vault 13 je ale plnì
 automatizován.}
{152}{}{Proè?}
{153}{}{Ok, ještì se zeptám.}
{154}{}{Proè? Myslím tím, není to neobvyklé?}
{155}{}{Vidím. Zmìòme téma.}
{156}{}{Neznám celı pøíbìh, ale v jednom okamiku probìhlo ve vaultu povstání. Dozorce byl zabit nebo sesazen, nejsem si jistı co se stalo. Tak jako tak, vùdcové povstání nechtìli, aby další dozorce ovládal ivot ve vaultu, proto nainstalovaly tenhle pøístup. Záznamy øíkají, e to bylo objednáno z... sakra, jak to jen bylo... Jo z 'Bratrstva oceli.'}
{157}{}{Øíkal jsi Bratrstvo?}
{158}{}{Co mi mùeš øíct o tom Bratrstvu?}
{159}{}{Ne, je mi líto, nevím o nich nic. Tohle všechno se událo pøed vìky, nikdy jsem o nich nenašel další záznamy kromì tohohle. Podle mého názoru bylo Bratrstvo vojenskou jednotkou a na západì jsou nìjaké ruiny, které vypadají jako bıvalá vojenská základna. To je moná jediné, co po nich asi zbylo.}
{160}{}{Aha. Chtìl bych vìdìt nìco jiného.}
{161}{}{V pohodì. Chtìl bych vìdìt ještì dalších pár vìcí.}
{162}{}{Ale ano. Mám to tady rád od prvního okamiku, co jsem tady a asi u nikdy neodejdu. Vdycky jsem byl samotáø a o lidi jsem se moc nestaral, ne schválnì.}
{163}{}{Tomu bych nevìøil.}
{164}{}{Tomu se nedá vìøit.}
{165}{}{Dobrá... Líbí se mi na nich, co jsou a èím se snaí bıt. Navíc se mì bojí víc ne èerta. A ani mi nikdy nevadilo, e nìkteøí z nich jsou chytøí jako já... no, po pravdì nìkteøí z nich jsou chytøejší.}
{166}{}{Jsou hrozbou pro lidi?}
{167}{}{Myslíš si, e jsou hrozbou pro lidské spoleèenství?}
{168}{}{Rozhodnì. Staèí na nás jak fyzicky, tak mentálnì. To z nich
 dìlá opravdu velkou hrozbu. Naštìstí jsou morálnì a eticky na vıši. }
{169}{}{Vidím.}
{170}{}{Ano, vím co máš na mysli.}
{171}{}{Ahoj. Rád tì zase vidím. S èím ti mohu pomoci?}
{172}{}{Potøebuji nìco vìdìt.}
{173}{}{Jen tì pozdravit a u zas musím bìet.}
{174}{}{Na nìco bych se potøeboval zeptat.}
{175}{}{Jenom øíct nazdar.}
{176}{}{Dobrá, poèkej chvíli... Myslím e nejlepší místo, kde bys ho mohl najít, je Vault City, jsou asi nejlépe technicky vybavenım mìstem. Moná taky v New Renu. Jsou blí a èasto obchodují s Vault City.}
{177}{}{Dík.}
{178}{}{Dìkuji ti, e si opravil poèítaè. Zachránil jsi naše ivoty.}
{179}{}{Mám lepší vìci na práci ne zabíjet uboáky, ale dobrá, kadı potøebuje ponauèení!}

{180}{}{. Chci se zeptat?}
{181}{}{. Mohu se zeptat?}
{182}{}{. Mùeš mi na nìco opovìdìt.}
{183}{}{Øekls Grutharovi, e jsi opravil poèítaè?}
