#tento soubor pøeložil Vachy - http://vachy.moje.cz
{100}{}{Vidíš malého muže, držícího knihu.}
{101}{}{To je bylinkáø Joseph.}
{102}{}{Vidíš menšího muže s knihou nesoucí název "Rostliny a byliny našich luhù a hájù."}
{103}{}{Vítej, jsem bylinkáø Joseph. S èím ti mohu pomoci?}
{104}{}{Hele boláèek.. pofoukej?}
{105}{}{Budu zvracet, pomoz mi?}
{106}{}{Hele upadla mi ruèièka.. pøišij?}
{107}{}{Mám otázky, víš?}
{108}{}{Promiò, musím jít.}
{109}{}{Jsem nìèím nakažen. Mùžeš mi pomoct?}
{110}{}{Cítím se trochu divnì, mùžeš mi pomoci?}
{111}{}{Otevøelo se mi staré zranìní. Mùžeš mi pomoct?}
{112}{}{Mám na tebe otázeèku.}
{113}{}{Ale jdu jen kolem a chtìl jsem tì pozdravit.}
{114}{}{Rozhodnì. Hmmm. Asi budeš potøebovat trochu téhle masti, vetøeme ji pìknì do rány. Teï si tady lehni a chvíli si odpoèiò.}
{115}{}{Dìkuji. Sbohem.}
{116}{}{Dík, Doktore. Cítím se lépe.}
{117}{}{Rozhodnì. Ale chvíli to zabere, budeš tady ale muset zùstat pøes noc. Vypij tenhle nápoj - A to je vše, teï se ti bude motat hlava, lehni si tady a já se vrátím ráno.}
{118}{}{Cítit se dobøe. Sbohem.}
{119}{}{Dìkuji, to mi docela pomohlo.}
{120}{}{Bohužel, ale nejsem klasický doktor a neumím provádìt chirurgické zákroky. Doporuèoval bych ti zajít si do jednoho z velkých mìst. Zkus tøeba New California Republic. Je to na východ odsud.}
{121}{}{Aha. Sbohem.}
{122}{}{V poøádku, stejnì dìkuji.}
{123}{}{Co chceš vìdìt?}
{124}{}{Jsi vìznìm?}
{125}{}{Mùžeš odsud kdykoliv odejít?}
{126}{}{Co víš o deathclawech?}
{127}{}{Kde ses tu vzal?}
{128}{}{Už musím jít.}
{129}{}{Jsi zde vìznìm?}
{130}{}{Mùžeš odejít kdy chceš?}
{131}{}{Co mi mùžeš povìdìt o deathclawech?}
{132}{}{Jak jsi se sem dostal?}
{133}{}{Dekuji za informaci. Je èas zmizet.}
{134}{}{Ne, nejsem vìzeò. Zùstávám tu, protože jsem potøeba. Nauèil jsem se respektovat fakt, že mnozí moji pacienti jsou deathclawové.}
{135}{}{Aha. Potøebuji vìdìt víc.}
{136}{}{Dík. Sbohem.}
{137}{}{To je od tebe velmi chvályhodné.}
{138}{}{Vidím.}
{139}{}{Je to tvoje rozhodnutí a konec koncù je to i tvùj život.}
{140}{}{Ano je to tak. Èas od èasu si sbírám svoje kytièky a nikdo mi v tom nebrání. Ani jsem se nedivil, když jsem jednoho dne zjistil, že mì deathclawové tajnì sledují. Asi by mi ale nebránili, kdybych chtìl odejít. A jednoho dne to nejspíš stejnì udìlám.}
{141}{}{To jsem chtìl vìdìt, musím už jít.}
{142}{}{Ještì se chci zeptat.}
{143}{}{Dostal jsi skvìlou šanci a možná jí rád využiješ.}
{144}{}{V poøádku.}
{145}{}{Dobrý nápad, to mùže být zajímavé.}
{146}{}{Hele podívej... Deathclawové vypadají, že jsou zmutování z Jacksonova Chameleóna, z jeho více rohaté verze. Mnoho podobností ji zùstalo, zároveò ale mají mnoho odlišností. Faktor mutace je zde opravdu velký. Tahle rasa je hodnì  inteligentní a i když jsou jen 8 let staøí, v nìkterých vìcech už se vyrovnají èlovìku. Kapacita jejich mozku je neuvìøitelná a navíc jsou velmi pøizpùsobiví.}
{147}{}{Uh... co to øíkáš.}
{148}{}{Asi bych mìl jít.}
{149}{}{Nepovídej.}
{150}{}{Teda, tvoje vìdomosti mì zarážejí.}
{151}{}{To zní jako pìkná blbost, co to tady plácáš.}
{152}{}{Sbíral jsem jednou v noci nìjaké bylinky a nìjaký hlas na mì z temnot zavolal. 'Už dlouho tì sleduji,' øíkal, 'a vím, že jsi léèitel. Mìl bys dost umìní k tomu léèit nìkoho jiného, než jsi ty? Nìkoho o kom se øíká, že je nepøítel?'}
{153}{}{Ugh.}
{154}{}{Díky. Už musím jít.}
{155}{}{Jak ohavné, že jsi tady, zatímco bys mohl pomáhat jiným "lidem".}
{156}{}{Jsi opravdu muž, který zasluhuje uznání.}
{157}{}{Zajímavé.}
{158}{}{Nebudu pomáhat nìkomu takovému, jako jsi ty.}

{159}{}{Odjel jsem na nìkolik dní do jiného mìsta. Když jsem se vrátil, byl jsem srdeènì pøivítán. Gruthar, vùdce klanu, pøišel a osobnì mi podìkoval za to že jsem se vrátil zpìt. Ne, jsem tu, protože tu chci být.}

{160}{}{Aèkoli nemají dobré mluvící orgány, vypadá to že deathclawové napodobují lidskou artikulaci stejnì jako tøeba papoušci. Na tohle jsem pøišel teprve nedávno a bohužel o tom zatím nemohu øíct více. Struènì vzato je to spoleèenství zvíøat s velmi vytøíbeným vkusem a striktní etikou. Jejich vedoucím je vždycky  'první muž', vylíhne se jako první a potom ovládá celý klan. Ostatní jsou extrémnì loajální ke spoleèenství, které je pro nì prvním a posledním. Nejsou jako lidé, kteøí opustí rodinu kvùli nìkomu jinému.}
{161}{}{Rozeznávají dobøe rozdíl mezi dobrým a špatným. Mají urèitý etický kodex a ten dodržují v závislosti na klanu. Jak mohu potvrdit, násilí není nikdy používáno jako øešení. Nemají problém s 'kriminalitou', ale jak to dìlají, nevím. Hmmm. A to je asi vše, co vím, doufám, že ti to pomùže.}

{162}{}{Už jsem ti øíkal, že uznávám všechen život a dìlám to nejlepší abych uzdravil nemoci nebo lehká zranìní. Byl to nìjaký zlodìj nebo bandita, který si schválnì nìco udìlal a potøeboval doktora. Urèitì by ses taky divil, kdyby ti uprostøed noci zastoupilo cestu nìkolik deathclawù se svým zranìným pøítelem. Nìkdo ho opravdu zle postøelil. Øekl jsem jim, že na louce s tím nic neudìláme a tak mì vzali sem.. no a od tý doby tady s nimi žiju.}