#tento soubor pøeložil Vachy - http://vachy.moje.cz
{100}{}{Vidíš deathclawa. Pozoruje tì podivnì inteligentníma oèima.}
{101}{}{To je deathclaw Jul.}
{102}{}{Vidíš typického deathclawa. Je rozložitý, má silné tìlo, ostré zuby a dlouhé drápy.}
{103}{}{Stop. Sem nemùžeš. Tohle místo je ti zakázáno.}
{104}{}{Tak jo, už jdu.}
{105}{}{Co je to za místo?}
{106}{}{Kdo jsi ty?}
{107}{}{Tak jo, odcházím}
{108}{}{Pùjdu tam, kam budu chtít, ještìrèí hovno!}
{109}{}{Co je to za místo?}
{110}{}{Kdo jsi ty?}
{111}{}{To je líheò. Je tam matka spoleèenství. Vajíèka a to hlídám. Jsem dùležitý.}
{112}{}{Chci mluvit s matkou.}
{113}{}{Kdo jsi?}
{114}{}{Už musím jít.}
{115}{}{Tak tedy odcházím.}
{116}{}{Kdo jsi ty?}
{117}{}{Rád bych mluvil s matkou.}
{118}{}{Jsem Jul. Kmenový váleèník. Hlídám líheò a matku.}
{119}{}{Já} #Continue 146
{120}{}{Už musím jít.}
{121}{}{Hlídání matky je dùležitá práce.}
{122}{}{Já jsem} #Continue 147
{123}{}{Hlídání matky musí být svìøeno urèitì nìkomu hodnì dùležitému a vìrohodnému, musíš být vysoký èlen kmene.}
{124}{}{To vidím, opouštím tì.}
{125}{}{Poèkej. Zeptám se matky.}
{126}{}{Ok.}
{127}{}{Matka tì chce vidìt. Vejdi. Dej si bacha na problémy, nechci ti ublížit, ale udìlám to když budu muset.}
{128}{}{Matka by tì ráda vidìla. Ale musíš jít sám; pøátelé zùstanou tady. Vyvaruj se problémù a nic se ti nestane.}
{129}{}{Dobrá.}
{130}{}{Tak to si myslíš? Tak takhle jsem se na to nikdy nedíval. To se mi líbí. Dík.}
{131}{}{Nashledanou. Musím jít.}
{132}{}{Chci mluvit s matkou.}
{133}{}{Jsi tu vždy vítán. Ale mám práci.}
{134}{}{Mohu mluvit s matkou?}
{135}{}{Ještìrèí hovno... Oh, Tak to si budu pamatovat. Ha ha! A ty si pamatuj tohle. Hlídám tady, protože jsem nejtvrdší, nejsilnìjší a nejbrutálnìjší zkurvysyn v celým vaultu. Zkus nìco a budeš mít problém. Radìji bìž, než mi ujede paøát a udìlám ti druhej úsmìv pod krkem.}
{136}{}{Tak já jdu.}
{137}{}{Ale no tak? Podíváme se, jakej si tvrïák!}
{138}{}{Zase ty. Co k sakru chceš?}
{139}{}{Jen øíct ahoj a nashle.}
{140}{}{Kdože si øíkal že seš?}
{141}{}{Co je to tady?}
{142}{}{Ale jdu náhodou kolem tak jsem ti chtìl øíct ahoj.}
{143}{}{Co je tohle za místo?}
{144}{}{A co jsi zaè?}
{145}{}{Seš už teï mrtvej. Hloupý hloupému králem.}

{146}{}{. Chci mluvit s matkou.}
{147}{}{, Jule, rád bych prohodil pár vìt s matkou, prosím.}
