#tento soubor pøeložil Vachy - http://vachy.moje.cz
{100}{}{Vidíš deathclawa.}
{101}{}{To je Kerith - matka deatclawù.}
{102}{}{Vidíš typického deathclawa. Je rozložitý, má silné tìlo, ostré zuby a dlouhé drápy. Tento vypadá, že je samice, ale nemùžeš to øíct urèitì. Zaznamenal jsi také pár jizev po zranìních na jejím tìle.}
{103}{}{Lidský návštìvník je neoèekávaná, ale vítaná událost. Jsem Kerith.}
{104}{}{S èím ti mohu pomoci?}
{105}{}{Ty jsi matka deathclawù?}
{106}{}{Kdo je otec deathclawù?}
{107}{}{Dveøe vypadají vypáèené, co se stalo?}
{108}{}{Kdo postavil toto hnízdištì?}
{109}{}{Asi bych mìl jít.}
{110}{}{Tak ty jsi matka deathclawù?}
{111}{}{Kdo je otec deathclawù?}
{112}{}{Co se stalo s dveømi? Vypadají, že byli ještì nedávno v poøádku.}
{113}{}{Kdo postavil tuto líheò?}
{114}{}{Jsem na odchodu.}
{115}{}{Ano. Jsem souèasná matka spoleèenství. Jakmile moje vajíèka dozrají, dostanou šanci i ostatní matky.}
{116}{}{Aha.}
{117}{}{Další matky?}
{118}{}{Vidím.}
{119}{}{Jsou ještì jiné matky?}
{120}{}{Ano, jsou. Jestliže se mi nìco stane, jedna z nich zaujme moje místo. Spoleèenství musí žít dál.}
{121}{}{Uh, já rozumím.}
{122}{}{Rozumím.}
{123}{}{Tyto vajíèka byla oplodnìna Grutharem, vùdcem klanu. To Gruthar rozhoduje, kdo bude pøipuštìn a kdo ne. Díky nìmu bude naše spoleèenství jednou silné.}
{124}{}{Tak to jo.}
{125}{}{Hmmm. V tom vidím selektivní pìstování za úèelem zvýšení
 schopností.}
{126}{}{To je bolestná vzpomínka. Nìjaký nenávistný èlovìk se sem vplížil když jsem spala a umístil bombu mezi vajíèka. Naštìstí pøi odchodu o nìco zavadil a já jí našla. Bohužel nebylo mnoho èasu k zneškodnìní, takže jsem jí hodila ke dveøím a vlastním tìlem jsem chránila vajíèka. Ta to naštìstí pøežila, dveøe bohužel ne.}
{127}{}{Co se s ním stalo?}
{128}{}{Jak se dostal pøes stráže?}
{129}{}{Chtìl bych se zeptat...}
{130}{}{A co se stalo èlovìku, který to udìlal?}
{131}{}{Jak se sem dostal pøes ty stráže venku?}
{132}{}{Mám ještì nìjaké otázky.}
{133}{}{Jmenuje se Matt a je zde vìznìm, osobnì bych ho ráda vidìla mrtvého - ale Gruthar to nechce dovolit. Moc tomu nerozumím, ale Grutharùv svìt je zákon a jeho dodržování. Jestli si chceš s tím vìznìm promluvit, dej si pozor, nedá se mu vìøit!}
{134}{}{Jak se dostal pøes stráže?}
{135}{}{Jo.}
{136}{}{Jak se dostal pøes ty stráže venku?}
{137}{}{Jo.}
{138}{}{Pøed tím jsme stráže nemìli, byli jsme dùvìøiví. Teï už jsme opatrnìjší.}
{139}{}{Co se s ním stalo?}
{140}{}{Jo jo.}
{141}{}{A co se stalo èlovìku, který to udìlal?}
{142}{}{Vidím.}
{143}{}{Vybudovali jsme si umìlou líheò a jeden náš lidský pøítel tu vybudoval dveøe. Mìl souèástky z usedlosti na severo-východ odsud.}
{144}{}{To je pìkné.}
{145}{}{To je pìkné.}
{146}{}{Vítej, jak se máš, s èím ti mohu pomoci?}
{147}{}{Já øíct ahoj. Já jít teï.}
{148}{}{Ale jdu náhodou kolem a chtìl jsem tì pozdravit.}
{149}{}{To mì dožralo tak, že tì asi zabiju.}