#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš menšího, štíhlého chlápka.}
{101}{}{To je Matt.}
{102}{}{Vidíš nišího, štíhlého chlápka s krátkımi vlasy a divokostí v oèích. Nechtìl bys ho mít v zádech.}
{103}{}{Je tu nìco, s èím ti mohu bıt nápomocen, cizinèe?}
{104}{}{Já se ptát?}
{105}{}{Neblázni.}
{106}{}{Ano, mám pár otázek.}
{107}{}{Ne, u musím jít.}
{108}{}{Co chceš?}
{109}{}{Kdo ty?}
{110}{}{Ty vìzeò?}
{111}{}{Já musím jít.}
{112}{}{Kdopak jsi?}
{113}{}{Jsi tu vìznìm?}
{114}{}{Právì jsem na odchodu.}
{115}{}{Jmenuji se Matt. Staèí to?}
{116}{}{Ani né.}
{117}{}{Huhly. Musím jít.}
{118}{}{Tak jo, u jdu.}
{119}{}{Neblázni.}
{120}{}{Ano, po pravdì øeèeno jsem. Zkejsl jsem na tomhle místì a byl chycen deathclawy. Dali mi svobodu s volnım pohybem po dolních podlaích Vaultu, ale nikdy nemùu jít do prvního patra, kde je vıchod.}
{121}{}{Proè?}
{122}{}{Aha.}
{123}{}{U musím jít.}
{124}{}{Proèpak?}
{125}{}{Vidím.}
{126}{}{Stejnì jsem na odchodu.}
{127}{}{Protoe na rozdíl od ostatních zde ijících ovcí jsem v nich rozpoznal hrozbu pro lidstvo. Vìdí, e kdybych se odsud dostal, budu se snait vymazat je z povrchu zemského! Podívej: Mùou samostatnì myslet, mùou se uèit, umí èíst a psát u od vajíèka. Jsou rychlí, vnímaví a smrtící. Kdy se jejich poèty dostateènì zvıší, stanou se opravdovou hrozbou pro lidstvo. Pøemıšlej o tom. Musí bıt znièeni!}
{128}{}{Hmm. To dává smysl.}
{129}{}{Myslím, e se mılíš.}
{130}{}{Moná e jsou hrozbou, ale stejnì jim vìøím.}
{131}{}{Máš recht, co podnikneme?}
{132}{}{Sám nemám moc šancí, ale spoleènì se odsud mùeme probojovat. Co ty na to?}
{133}{}{Ano.}
{134}{}{Ne.}
{135}{}{Arrgh! Ovlivnili tvoji mysl. A zmìníš názor, vra se.}
{136}{}{Sbohem.}
{137}{}{Tak u sis to rozmyslel? Pomùeš mi odsud?}
{138}{}{Ano.}
{139}{}{Ne.}
{140}{}{Aby tì ïas spral.. sraèku na tebe!}

{141}{}{Nejsem tu kvùli útìku, ale kvùli tomu, e nìkdo poškodil hlavní poèítaè. Udìlal's to?}
{142}{}{Nejsem tu, abych spøádal plány na útìk. Nìkdo sabotoval hlavní poèítaè. Nevíš o tom náhodou nìco?}
{143}{}{Aby ses z toho neposral!}
{144}{}{Ale jo. Znièil jsem hlasovı modul a zablokoval klávesnici.}
{145}{}{Proè?}
{146}{}{Bez pøístupu k potravinám a vodì, bude vault za chvíli prázdnı. Bez toho poèítaèe budou muset deathclawové zase vyrazit do pustin rabovat a nièit lidská obydlí. A potom budou koneènì polapeni a do posledního vybiti.}
{147}{}{Ale i tak. Oni potøebují potraviny a vodu, to ti jich není líto?}
{148}{}{A co ostatní, co tu ijí, i jejich osud je ti lhostejnı?}
{149}{}{To si nemyslím. Jsou to prostì obìti války.}
{150}{}{U musím jít.}
{151}{}{Nejlepší asi bude, poslat tì do vìènıch loviš.}
{152}{}{Dobrá práce.}
{153}{}{Vidím. U musím jít.}
{154}{}{Asi ti teï vystøelím mozek. Jsi hodnì nebezpeènı.}
{155}{}{Dobrá práce!}