#tento soubor pøeložil Vachy - http://vachy.moje.cz
{100}{}{Vidíš malou holèièku ve žlutých šatièkách.}
{101}{}{To je Sandy.}
{102}{}{ Vidíš malou holèièku ve žlutých šatièkách na kterých jsou kytièky. Mòouká jako koèka a má jmenovku na jméno "Sandy".}
{103}{}{Mòau... mòau... Jsem koèka. Umím co umí jen koèky. Co jsi ty?}
{104}{}{Jsem pejsek! Haf! Vrrr! Kdo jsi?}
{105}{}{Cožeto? (ustrašený pohled)}
{106}{}{Jsi divný. Musím jít.}
{107}{}{Já jsem ten, kdo ti naplácá na zadek jestli okamžitì nepøestaneš s tìma koèièíma blbostma a neøekneš mi svoje jméno.}
{108}{}{Jsem jen náhodný kolemjdoucí a chci ti ukázat chlupatou vever... teda ... Taky si rád hraju. Povíš mi, prosím, tvoje jméno?}
{109}{}{Nevadí.}
{110}{}{(Pomrkává) Vypadáš srandovnì! Mòau... Jsem Sandy. Ale neboj nejsem opravdová koèka, jen si na ní hraju.}
{111}{}{(Breèí) Mami! Mami! Mami!}
{112}{}{Jsem Sandy. Ale nejsem koèka, jenom si tak hraju.}
{113}{}{Já si taky hraju, mùžu se tì zeptat?}
{114}{}{Už musím jít.}
{115}{}{Vidím, mùžeš mi prosím nìco øíct?}
{116}{}{Tak jo, poslouchám.}
{117}{}{A na co se chceš ptát?}
{118}{}{Musíš tady být?}
{119}{}{Jsi tu ráda?}
{120}{}{Jsi tu v bezpeèí?}
{121}{}{Zapomeò. Musím jít.}
{122}{}{Ty tady musíš být?}
{123}{}{Jsi tu ráda?}
{124}{}{Je tady bezpeèno?}
{125}{}{Ale nic. Mìj se}
{126}{}{Ano. Maminka mi vždycky øíká, kam mùžu a nesmím jít. Øíká mi, kde si mùžu a nesmím hrát a taky co mám jíst a kdy mám jít spát a kde mám èùrat a kdy mám jít do školy, no prostì všechno. Nemyslím že to fér, ale udìlám všechno, co mi nakáže.}
{127}{}{Ok.}
{128}{}{Už musím jít.}
{129}{}{Vidím.}
{130}{}{Tak to by mi prozatím staèilo... Nechceš bonbónek... hmm.. mìj se.}
{131}{}{No, chybí mi tu další dìti, ale maminka øíká, že to se jednou zmìní. Myslí si, že jsem pøijdou žít další rodiny s dìtmi. Zatím si hraju s Valdisem. Je s ním sranda a dává mi legraèní otázky. Maminka øíká, abych ho nechala být, že má moc práce.. ale když mu øeknu, tak si hrajeme, ale mamince o tom prosím tì nic neøíkej.}
{132}{}{Prase... (ustrašený dìtský pohled)}
{133}{}{Musím jít.}
{134}{}{To je pìkné.}
{135}{}{Dobrá, uvidíme se.}
{136}{}{Ano. Maminka na mì dává pozor a Valdis nedovolí, aby mi nìkdo ublížil. Mám se tu dobøe.}
{137}{}{Aha. Už musím jít.}
{138}{}{Dobrá; Na vidìnou.}
{139}{}{Ahoj.}
{140}{}{Bìž pryè! Nemám tì ráda!}
