#tento soubor pøeloil Vachy - http://vachy.moje.cz
{100}{}{Vidíš deathclawa, prohlíí si tì podivnì inteligentním pohledem.}
{101}{}{To je deathclaw Thearn.}
{102}{}{Vidíš typického deathclawa. Je rozloitı, má silné tìlo, ostré zuby a dlouhé drápy.}
{103}{}{Odpus. Neumìt dobøe mluvit. Zkusit povídat s tebou.}
{104}{}{Co chtít?}
{105}{}{Kdo jsi ty?}
{106}{}{Co dìláš?}
{107}{}{Jak jsi chytrı?}
{108}{}{Já u musím jít.}
{109}{}{Kdo jsi?}
{110}{}{Co tu dìláš?}
{111}{}{Bez uráky, jak jsi chytrı?}
{112}{}{Dobrá, jenom chytám lelky.}
{113}{}{Já bıt Thearn. Ty bıt kdo?}
{114}{}{Já}
{115}{}{Já u jdu.}
{116}{}{Asi bych mìl jít.}
{117}{}{Rád jsem tì poznal, Thearne. Jsem}
{118}{}{Mám to.}
{119}{}{Tak to si myslím, e jsi pìknı hovno.}
{120}{}{Já hlídat chodbu. Bıt tu bezpeèí.}
{121}{}{Oh... Coe...}
{122}{}{Hlídat? Co jako?}
{123}{}{Ok. U jdu.}
{124}{}{Dobrá, pokraèuj. U musím jít.}
{125}{}{Odvádíš skvìlou práci!}
{126}{}{Ty a strá? Hahaha!}
{127}{}{A pøed èímpak to tu hlídáš?}
{128}{}{Vetøelec. Èlovìk, deathclaw, cokoli. Dávat pozor a útoèit.}
{129}{}{Aha.}
{130}{}{Vidím.}
{131}{}{Byl bych docela pøekvapen, kdybys rozpoznal u jenom Santa Klause od mravence.}
{132}{}{Je mi docela líto tìch nevítanıch návštìvníkù.}
{133}{}{Nevadí. Vidím tì.}
{134}{}{Jak moct posoudit? Nevím. Nìkterım vìcem rozumìt moc, nìkterım málo a nìkterım vùbec.}
{135}{}{Ty a já jsme to samı.}
{136}{}{Ano, to mì dìlá lepším.}
{137}{}{Dìláš to dobøe.}
{138}{}{Tak jako tak, stejnì jsi hlupák.}
{139}{}{Ty bıt pøítel. Ty opravit stroj.}
{140}{}{Ahoj. Poøád na strái.}
{141}{}{}
{142}{}{Arrrrrrrrrgggh! Zemøi!}

{143}{}{.}
