#tento soubor pøeložil Vachy - http://vachy.moje.cz
{100}{}{Vidíš deathclawa. Pozoruje tì podivnì inteligentníma oèima.}
{101}{}{Vidíš deathclawa Valdise.}
{102}{}{Vidíš typického deathclawa. Je rozložitý, má silné tìlo, ostré zuby a dlouhé drápy.}
{103}{}{Vítej èlovíèku.}
{104}{}{Jak ti mùžu pomoci?}
{105}{}{A ty jsi?}
{106}{}{Co dìláš?}
{107}{}{Mám na mozku zákal, pøijï pozdìji.}
{108}{}{Zdravíèko, kdopak jsi?}
{109}{}{Jaká je tvá práce?}
{110}{}{Není moc èasu na kamarádíèkování s deathclawy, ale ty vypadáš docela... vzdìlanì, øekl bych?}
{111}{}{No jo, jen tak chytám lelky.}
{112}{}{Nazývají mì Valdisem. A ty jsi?}
{113}{}{Já èlovìk.}
{114}{}{Oooo! Deset dvacet za pikolou nikdo nesmí stát. Už jdu.}
{115}{}{Hele, tady se ptám já.}
{116}{}{Mìl bych jít.}
{117}{}{Rád tì poznávám, já jsem}
{118}{}{Mám to.}
{119}{}{Jenom hlídám tento úsek vaultu proti neoprávnìnému vniknutí.}
{120}{}{Takže tady máme povìøenou osobu?}
{121}{}{No... jistì.}
{122}{}{Meleš píèoviny. Mìl bych jít.}
{123}{}{Tak já jdu, Valdisi.}
{124}{}{Uvidíme.}
{125}{}{Dobrá, vypadáš jako nìkdo, kdo své práci docela rozumí.}
{126}{}{A to ten tvùj minimozek rozezná kdo je a kdo není 'oprávnìný?'}
{127}{}{Proè jako né. Ten dokonce pozná i kdo je a kdo není debil - a zrovna teï mi øíká že ty patøíš do té druhé kategorie! Teï radìji zmiz, než mì napadne udìlat si z tvého oblièeje pøistávací plochu pro svoje drápy?}
{128}{}{V pohodì.}
{129}{}{Špatná volba. Teï tì pošlu za tvými pøedky.}
{130}{}{Ale no tak, to byl jen fórek. Už si dám pozor na jazyk.}
{131}{}{Ano. Možná nedosahujeme takového stupnì vzdìlanosti jako vy, ale budu na tom pracovat ve svém volném èase.}
{132}{}{Další zamindrákovaný blázen.. jak srandovní.}
{133}{}{Dìláš to dobøe.}
{134}{}{To je skvìlý cíl.. pokraèuj.}
{135}{}{Heh? Dobøe jsem zaznamenal že jsi èlovìk, bohužel jsem pøeslechl tvoje jméno.}
{136}{}{Na jméno si se neptal, øíkals 'ty si.' Jsem èlovìk.}
{137}{}{Ale no jo. Jen jsem tì zkoušel. Uh... pokraèuj.}
{138}{}{Nìkdo mì volá, musím jít.}
{139}{}{Vidím. No zkusíme to jinak. Ahoj, jsem Valdis. Jak zní tvé ctìné jméno?}
{140}{}{Jsem}
{141}{}{Ahoj.}
{142}{}{neoprávnìná osoba, to znamená 'èlovìk co tu nemá co pohledávat.'}
{143}{}{Aha. Už rozumím.}
{144}{}{Už mì z tebe bolí hlava. Mìl bych jít.}
{145}{}{Mým úkolem je být co možná nejvíce trpìlivý, to znamená že zaèínáš být trochu hrubý. A jestli ti to nic neøíká, tak radìji bìž.}
{146}{}{Promiò, pokusím se být víc slušný.}
{147}{}{Zkus to.}
{148}{}{Jistì.}
{149}{}{Pøeji dobrého dne.}
{150}{}{Když to bereš takhle, tak se pøiprav na smrt.}

{151}{}{.}
