#tento soubor pøeložil Vachy - http://vachy.moje.cz
{100}{}{Vidíš terminál k poèítaèi.}
{101}{}{Vidíš hlasový terminál.}
{102}{}{Vidíš standardní terminál, upravený pro hlasovou modulaci.}
{103}{}{Rozeznal jsi poèítaèový terminál, ale nevidíš, že by s ním bylo nìco špatného, co udìláš?}
{104}{}{Pomoct mu 'speciálním' úderem ruky.(To zabere vždy)}
{105}{}{Pomoct mu 'speciálním' úderem nohy.(To zabere vždy)}
{106}{}{Spustit diagnostický program.}
{107}{}{Otevøít a podívat se mu do støev.}
{108}{}{Radìji to nechat být.}
{109}{}{Rozhodl jsi se, že klávesnice bude asi nejlepší místo, kde musíš provést opravný zásah. Po té, co jsi svým nejlepším ruèním úderem typu 'to opraví vše' zasáhl kryt terminálu, monitor nìkolikrát problikl a to bylo asi vše.. takže co udìláš?}
{110}{}{Trochu ho poškádlit nohou, to zabere vždy.}
{111}{}{Spustit diagnostický program.}
{112}{}{Otevøít a podívat se mu do støev.}
{113}{}{Radìji to nechat na pokoji.}
{114}{}{Tato osvìdèená metoda mìla jen dva výsledky. Monitoru se koneènì stabilizoval obraz tím že zhasl a zaslechl jsi nìjaké zvuky padajícího kovu z útrob poèítaèe, naèež se vysypal celý panel na zem, takže co teï?}
{115}{}{Spustit diagnostický program.}
{116}{}{No alespoò se mu teï lépe podíváš na žebra.}
{117}{}{Nechat to být a zpytovat svìdomí.}
{118}{}{Rozpoznal jsi, že diagnostické programy jsou k dispozici, bohužel tlaèítka na klávesnici se nìjak zasekla. Ale jednotka mùže pøijímat jenom hlasové pøíkazy. Tak co s tím?}
{119}{}{Tak teï už se opravdu mùžeš kouknout jen dovnitø.}
{120}{}{a nebo jít pryè.}
{121}{}{Po dùkladném prolezení kabelù a prohlídnutí nìkolika souèástek typu 'Made in Taiwan' si rozpoznal, že na systémù nìkdo provedl zákeønou sabotáž. Jenom výmìna hlasového modulu by to mohla zachránit. No tak teï už bys jen potøeboval ten modul.}
{122}{}{Konec.}
{123}{}{Konec.}
{124}{}{Nainstaloval si modul do terminálu, systém je opraven.}
{125}{}{Pøedtím než terminál použiješ, bys potøeboval hlasovì rozpoznávací modul.}
{126}{}{Dál.}
{127}{}{Systém už je v pohodì.}

{128}{}{Nahrávám bezpeènostní kódy, pouštím holografický záznam...}

{129}{}{Jsi poslední, Gruthare. Ale i tvùj názor bude brzy zmìnìn.}
{130}{}{Povìz svému Prezidentovi, že za tohle shoøí v pekle.}
{131}{}{A co dìlat. Nejsi nic jinýho než mluvící zvíøe.}
{132}{}{To mùže být, ale stvoøily jste nás vy a dali jste nám život!}
{133}{}{A tobì teï patøí SMRT.}
{134}{}{Vezmìte jeho tìlo. Doktor ho chce podrobnì prozkoumat.}
{135}{}{Jejich krev poteèe jako Nil!}
