#tenhle soubor pøeloil Birdman - birdman@post.cz, http://get.to/birdman
# EXAMINES
{151}{}{}

# USE MESSAGES
{200}{}{Hezkı vıhled.}
{201}{}{Ne moc hezkı vıhled.}
{202}{}{Moje odpovìï zní ne.}
{203}{}{S tím nepoèítej.}
{204}{}{Mùeš se na to spolehnout.}
{205}{}{Zeptej se mnì pozdìji.}
{206}{}{Moná.}
{207}{}{To se teï nedá odhadnout.}
{208}{}{Ano.}
{209}{}{Ano. Urèitì.}
{210}{}{Zatím ti to radši neøeknu.}
{211}{}{Je to jisté.}
{212}{}{Pochybuju.}
{213}{}{Je to tak rozhodnuté.}
{214}{}{Soustøeï se a zeptej se znovu.}
{215}{}{Stopy naznaèují, e ano.}
{216}{}{Moje zdroje øíkají e ne.}
{217}{}{Bezpochyby.}
{218}{}{Odpovìï nejistá, zkus znovu.}
{219}{}{Jak to vidím já, tak ano.}
{220}{}{Pøestaò se mnou tak tøepat. Bolí to.}
{221}{}{Máš silnou pravou ruku.}
{222}{}{Pøíštì si prosím utøi ruce, ne se mnou zase zaèneš tøepat.}
{223}{}{Doèasnì mimo provoz.}
{224}{}{Uzavøeno z pøíkazu RPG Board.}
{225}{}{Tøes se mnou dál, a budeš mít problém.}
{226}{}{Dìlá se mi zle.}
{227}{}{Zaèíná se mi toèit hlava.}
{228}{}{Ach... ty máš tak teplé ruce...}
{229}{}{Feargus byl proti tomu, aby mì dali do hry. Je to pìknej parchant.}
{230}{}{Tvoje skóre je 23 ze 100. Ještì toho máš spoustu pøed sebou.}
{231}{}{Somnambulus z toho byl hotovej, kdy vidìl, kolik je ve høe pøedmìtù a co všechno bude muset pøeloit. Ale Birdman zase nadává e je jich málo, hlavnì zbraní. Poøád nìco mele o padesátce AE nebo o nìjaké èezetì.}
# 9 or greater luck
{232}{}{Podívej se na muské toalety v prvním patøe v Mordinovic Kasínu. Kasíno je v Novém Renu.}
{233}{}{Aktivuj znaèku v Golgotì oznaèenou 'Odpadky' , najdeš tajnou skrıš.}
{234}{}{A dohraješ hru, vra se do Nového Rena a promluv si s Otcem Tullym.}
{235}{}{Víš, e mì mùeš pouít jako zbraò?}
{236}{}{Pøestaò se mnou tak tøepat.}
{237}{}{Tvoje ŠTÌSTÍ je fakt vysokı. Ale u se mnou pøestaò tøepat, u ti nic neporadím!}
{238}{}{Ano, VÍM, e Descent to Undermountain byla pìkná blbost.}