#tento soubor pøeloil Marek "MAK" Gøešek
{100}{}{Vidíš mue v obleku strnule hledícího do nikam. Vypadá to, jako by se díval skrz tebe.}
{101}{}{Vidíš hlavu svobodného svìta, prezidenta Spojenıch státù.}
{102}{}{Vidíš hubeného, nervóznì vypadajícího staršího mue, kterı vypadá stejnì hroznì jako oblek, ve kterém je obleèen.}

{103}{prs1a}{Ty tam, co dìláš mimo regeneraèní centrum?}
{104}{prs1b}{Znám tì? Na jakém projektu pracuješ?}
{105}{prs1c}{Kdo si myslíš, e jsi, e si jen tak "pøipluješ" do mé kanceláøe?}
{106}{}{Uh?}
{107}{}{Nuh.}
{108}{}{Pá-Pá.}

{109}{prs2a}{Ach, jak vidím, pøedìlanı pokusnımi séry. Um, trošku ti pomùu. Stráe!}
{110}{prs2b}{Doktore, myslím, e jsi byl vystaven úèinku pùsobení F.E.V. toxinu. Chudáèku, budu ti muset pomoct. Stráe!}
{111}{prs2c}{Buï hodnı mutant a zùstaò stát na místì. Stráe!}
{112}{}{OK.}
{113}{}{Uh uh. Ahoj.}

{114}{}{Poèkej pøesnì tady.}
{115}{}{Uh, zùstaò zticha. Nìkdo tu hned bude. }
{116}{}{Všechno je v pohodì.}
{117}{}{Zatracenì! Mùe nìkdo pøijít a vyhodit odtud tuto...osobu?}
{118}{}{Oh, stráe! V mé kanceláøi je nìjakı idiot... Ne, to není vtip.}

{119}{prs4}{Ahoj, ty tam. Já jsem prezident Richardson a jsem zatracenì rád, e se s tebou potkávám. Uh, Vault 13, jak vidím. Poskytuješ své vlasti opravdu neocenitelné sluby.}
{120}{}{Prezident? A co jste jako zaè?}
{121}{}{Slubu své zemi? A o co tu vlastnì jde?}
{122}{}{Uh, myslím, e jsem špatnì zaboèil na své cestì do laboratoøe. Promiòte, pane. Sbohem.}

{123}{prs5a}{Ahoj, doktore. Máte vısledky? Doufám, e pøinášíte dobré zprávy. Naši záchranu má ve svıch rukách váš tım.}
{124}{prs5b}{Ty tam, nemìl by jsi pracovat na Projektu? Záchrana lidstva závisí na tobì.}
{125}{}{Kdo jste?}
{126}{}{Záchrana? A o co tu vlastnì jde?}
{127}{}{Promiòte, pane. Špatnì jsem zaboèil na své cestì do laboratoøe. Sbohem.}

{128}{prs6}{Oh, to je velice správné. Všechny ty oèkovací injekce by zmátly kadého.}
{129}{}{Oèkovací injekce? Co tím myslíte?}
{130}{}{Myslím, e jsem opravdu trošku omámenı. Ale vìdìní, e pomáhám své zemi, mì utvrzuje v tom, e to za to stojí.}
{131}{}{Mùete to zopakovat. No, bude lepší, kdy pùjdu.}

{132}{prs7}{Nech mì pøivolat nìkoho z ochranky, aby tì odvedl zpìt.}
{133}{}{To je od Vás velmi milé, ale myslím, e bych to mohl zvládnout sám. Sbohem.}
{134}{}{To by od Vás bylo pìkné. Díky.}

{135}{prs8}{To není ádnı problém. (mluví do interkomu) Haló. Potøeboval bych zde nìkoho na malou asistenci.}
{136}{}{Dìkuji mnohokrát, pane.}
{137}{}{Radìji byste nemìl volat stráe, pane. Tedy pokud ještì nìkdy hodláte opustit tento pokoj ivı.}

{138}{prs9}{Och...dobøe. Jsem si jistı, e s tím nìco mùeme udìlat. Co máš na mysli?}
{139}{}{Chci vìdìt, o co tady jde.}
{140}{}{Potøebuji se odtud v tichosti vypaøit. Dejte své pracky z alarmu pryè, dokud odtud nevypadnu. Nebo...}
{141}{}{Odejdu odtud s Vámi jako rukojmím, abych se pøesvìdèil, e se odtud mí lidé dostanou v poøádku.}

{142}{prs10}{Opravdu si myslíš, e mùeš zastrašovat prezidenta Spojenıch státù?}
{143}{}{O tom nepochybuji.}
{144}{}{Moná, e ne, ale navrhuji Vám, abyste se mi nepletl do cesty, dokud neodejdu.}

{145}{prs11a_a}{Pro tvou informaci, stráe mají rozkaz mì radìji zastøelit, ne aby nechali nìkoho nebo nìco ohrozit Projekt. Jako rukojmí bych ti nebyl nic platnı.}
{146}{prs11b}{Snad vánì neoèekáváš, e ti to projde? Cha! Kdy to zkusíš, mé stráe mají rozkaz mì radìji zastøelit, ne aby nechali nìkoho nebo nìco ohrozit Projekt. Stojím pøímo zde. A teï, chystáš se mì zastøelit, nebo ne?}
{147}{}{Moná ne, ale teï odcházím. A opovate se dotknout toho tlaèítka s nápisem "Poplach".}
{148}{}{Projekt? Jakı Projekt?}
{149}{}{Ano, zastøelím. A pìknì si to vychutnám.}

{150}{prs12}{Uh, teï, teï, teï...... Uh, C-c-co vlastnì chceš?}
{151}{}{Chci vìdìt o co tu vlastnì jde.}
{152}{}{Chci vìdìt kdo k èertu jste.}
{153}{}{Chci Vaši smrt.}

{154}{prs13}{Dobøe, dobøe, všechno co øekneš. Budu tu tiše sedìt. Rád, uh, rád jsem tì poznal. Sbohem.}
{155}{}{To by bylo pøíliš snadné. Døív ne odejdu, rád bych vìdìl, co tady dìláte.}
{156}{}{Buïte opatrnı, protoe i prezidentovi by se mohlo nìco nemilého stát.}
{157}{}{Jsem rád, e jsem Vás poznal pane prezidente. Sbohem.}

{158}{prs14}{Ahhh. Ahhh. Stráe? Stráe!}
{159}{}{Øeknìte dobrou noc, pane prezidente.}

{160}{prs15}{Já jsem prezident Spojenıch státù americkıch. Viceprezident je v kanceláøi venku. Pokud sem patøíš, mìl bys to pøece vìdìt. Kdo jsi a co tady dìláš?}
{161}{}{Jste prezident Spojenıch státù?}
{162}{}{Jste tak akorát cvok.}
{163}{}{Viceprezident? Myslíte toho slintajícího idiota z vedlejší kanceláøe?}
{164}{}{To je mi náhodièka. Já jsem vládce planety Quetzl a pøicházím si podrobit Zemi.}
{165}{}{Nechám vás pokraèovat ve vaší práci pane, uh, prezidente. Sbohem.}

{166}{prs16}{Aha. Fajn, jistì, Vaše Eminence. Nemám nìkoho poslat tøeba pro... nìjaké obèerstvení? Mùeme si o tom promluvit a nìco s tím udìlat - moná si mùeme bıt navzájem prospìšní?}
{167}{}{To zní skvìle.}
{168}{}{Dobrı pokus, pane prezidente.}

{169}{prs17}{Uh, no dobøe, jenom minutku. (mluví do intercomu) Hmmm, chtìl bych obèerstvení pro mì a pro jednoho "NEOÈEKÁVANÉHO HOSTA". Velmi dùleité - neoèekávaného - hosta. Ihned?}
{170}{}{Díky. Myslím, e nakonec nejste tak velkı hajzl, jak se zdálo.}
{171}{}{To od Vás bylo hloupé. Nìkdo tu asi bude muset dostat pøes prdel.}

{172}{prs18}{Nìkdo se tu zbláznil, dobøe. Ó! ano. Óóóóóóó ano.}
{173}{}{Nedívej se tak na mì. Netouil jsem bıt presidentem Spojenıch státù. Bylo to rozhodnuto dávno pøed tím, ne jsme se my oba narodili.}

{174}{prs19}{Byl jsem vyvolen, abych zastupoval lidi našeho národa. Spojené Státy stále existují, Bùh jim ehnej. Museli jsme se pøizpùsobit, abychom po válce pøeili.}
{175}{}{Nerozumím. Co tím myslíte?}

{176}{prs20a}{Ty to opravdu nevíš? Povím ti nìco o záchranì lidstva. Zaèal bych trochou historie...}
{177}{prs20b}{Trocha historie...}
{178}{}{Pokraèujte, pane Prezidente....}
{179}{}{Nejdøíve by mì zajímalo proè máte základnu v Navarru?}
{180}{}{Døíve ne zaènete... Vidìl jsem jeden z vašich létajících strojù dìlat nìjakı obchod s New Renem. O co tam šlo?}
{181}{}{Teï nemám èas na tyto šílenosti. Sbohem.}

{182}{prs21a}{Ahoj ty tam. Rád si udìlám èas, pro jednoho z naších skvìlıch vojákù. Ale, jsem ponìkud zaneprázdnìnı. No, uh, co pro tebe mùe udìlat prezident Spojenıch státù?}
{183}{prs21b}{Jsi zpátky? Co zase chceš?}
{184}{}{Mùete mi øíct co se tady dìje.}
{185}{}{Já, uh, já právì kontroluji tuto oblast, pane. Provìøení ochrany. Rozumím. Vše v poøádku. Uh, sbohem.}

{186}{prs22a}{Ahoj. Já jsem Prezident Spojenıch Státù Americkıch a ty jsi...?}
{187}{prs22b}{Ahoj ty tam. Já jsem Prezident Spojenıch Státù Americkıch a musím øíct, e jsem tu za celı svùj ivot nepotkal mnoho cizincù, nebo spíše zástupce smutné delegace ztracenıch existencí. Take, kdo vlastnì jsi, e jsi sem tak vtrhl?}
{188}{}{Jsem zatracenì zvìdavı, co se tıèe toho, co to tu provádíte.}
{189}{}{Já jsem Váš kat.}
{190}{}{Prezident? O èem to mluvíte?}
{191}{}{Asi jsem se ztratil. Vidím, e jste velice zaneprázdnìnı mu, pane prezidente. Právì jsem na odchodu. Sbohem.}

{192}{prs23}{To je hrùza. Rozhovor se skuteènım mutantem, jako jsi ty. Krásnì jsem si, pøi pohledu na tebe, pøedstavil jaké je to ít v tom radioaktivním pekle na pevninì.}
{193}{}{Mutant? Proè mì nazıváte mutantem?}
{194}{}{Radioaktivní peklo? Vy se ven asi moc èasto nedostanete, co?}
{195}{}{Tak to u je pøíliš. Dost mluvení. Je èas zemøít.}
{196}{}{Ano, jasnì, všichni se musíme nauèit ít se zklamáním. Sbohem.}

{197}{prs24}{Byla tu obrovská válka dlouho pøed tím, ne jsme se my oba narodili. Naši stateèní vojáci bojovali od Yukonu a k Jang-se.}
{198}{}{Jo, nìco málo o té lapálii vím. Pokraèujte.}

{199}{prs26}{Viceprezident Bird moná vypadá jako slintající idiot, ale já jsem hned vìdìl, e ten mu je lidovı hrdina.}
{200}{}{Vy moná.}

{201}{prs27}{Je to jeden z nejstateènìjších lidí co znám. Pøihlásil se dobrovolnì k vyzkoušení jedné z prvních verzí protijedu na F.E.V. toxin. (povzdech) Bohuel, to nedopadlo tak úplnì jak jsme doufali.}
{202}{}{Co myslíte tím, e to nedopadlo jak jste doufali?}

{203}{prs28}{Je to malé smìšné myšlení, stejnì jako tvé, které dokazuje nadøazenost skuteènıch lidí nad mutanty.}
{204}{}{Je to jen ukecanı pitomec.}
{205}{}{Proè mì nazıváte mutantem?}

{206}{prs29}{Moná, e se ještì vzpamatuje. U se objevily i pozitivní reakce - napøíklad jeho schopnost hláskovat se vıraznì zlepšila.}
{207}{}{Jsem šastnı za nás za oba. Ale proè mì nazıváte mutantem?}

{208}{prs30}{Protoe jím jsi. DNA tvého kmene se zmìnilo od doby, kdy tvùj pøedek opustil Vault. Nedá se nic dìlat. Byl jsi vystaven veškeré zbytkové radiaci.}
{209}{}{OK, tak jsem mutant. Jste nìjakı moc chytrı. Asi z Vás udìlám èistokrevnou mrtvolu.}
{210}{}{Tak jsme mutanti. Asi.}
{211}{}{Tvorové se neustále mìní. Øíká se tomu evoluce. Bez této zmìny bychom oba byli jen kousky bunìèné hmoty.}

{212}{prs31}{Pokoušíme se ochránit nás pøed nebezpeènou radiací. To je to, co oddìluje lidi - jako jsem já - od mutantù, jako jsi ty.}
{213}{}{Proè mì stále oznaèujete za mutanta?}
{214}{}{Dost øeèí. Je èas setkat se s vašimi volièi v nebi.}
{215}{}{Zabil jsem lidi i pro míò. Ale dnes strašnì spìchám. Sbohem.}

{216}{prs32}{A také jsme vyhrávali. A pak na nás ti zatracení Rudí bastardi vypustili všechno, co mìli. Sotva jsme stihli odpálit naše øízené støely.}
{217}{}{Zdá se, e to stejnì moc nepomohlo.}

{218}{prs33}{No,...nepomohlo. Ale alespoò jsme poslali tu proklatou Rudou hrozbu zpìt do doby kamenné.}
{219}{}{A nás taky.}

{220}{prs34}{Ne. Ne úplnì. Jak vidíš, plánovali jsme dopøedu. Byli jsme pøipravení.}
{221}{}{Co tím míníte?}

{222}{prs35}{Mìli jsme nìkolik útoèiš, která mìla naší slavné americké kultuøe umonit pøetrvat. Tato zaøízení - Vaulty  - byli èástí velkolepého plánu.}
{223}{}{Ty zatracené Vaulty nepracovaly zpùsobem, jakım jste pøedpokládali. Mnoho lidí v nich zahynulo.}

{224}{prs36}{Popravdì øeèeno, pracovaly skoro pøesnì tak, jak jsme pøedpokládali. Moná by se to dalo oznaèit za sociální experiment ve velkém mìøítku.}
{225}{}{Experiment?}

{226}{prs36a}{Vaulty byly postaveny za úèelem provìøení lidské rasy. V nìkterém byl nedostatek syntezátorù jídla, nìkteré obsahovaly pouze mue a další byly navreny tak, aby se otevøely po pouhıch 6 mìsících. Kadı mìl nastavenu jedineènou shodu okolností zamìøenıch k vyzkoušení jejich uivatelù.}
{227}{}{A co tøeba Vault 13? Jakı byl jeho úèel?}

{228}{prs37}{Ah. Vault 13 byl zvláštní pøípad. Pøedpokládali jsme, e zùstane zavøenı do té doby, ne budeme osoby uvnitø potøebovat. Vault 13 byl, vìdeckou hanırkou øeèeno, kontrolní skupina.}
{229}{}{Ale všichni by zemøeli, kdyby pro nì mùj pøedek nezískal náhradní vodní èip. To pøíliš nezapadá do vašeho plánu.}

{230}{prs38}{Nešastná a nepøedvídatelná událost. Nicménì jak se ukázalo, byla nám ku prospìchu.}
{231}{}{Co tím myslíte?}

{232}{prs39}{Poté co se venku vše zmìnilo, potøebovali jsme pokusné osoby nezasaeného, pøedváleèného, lidského pùvodu - tví pøedci z Vault 13 - a nìkolik èerstvì zmutovanıch - vesnièanù z Arroyo.}
{233}{}{Proè?}

{234}{prs39a}{Na Projekt. U je skoro hotov. Záchrana lidstva je témìø nadosah a Spojené Státy Americké budou zakladatelé tohoto znovuzrození.}
{235}{}{Znovuzrození? Co tím míníte?}

{236}{prs40a}{Jediná cesta pro zabezpeèení pravıch lidí a demokracie je oèištìní zemì od mutantù. Lidé si vezmou zpìt to co jim podle práva náleí.}
{237}{prs40b}{Projekt oèistí od všech mutantù naši pøekrásnou zemi - i zbıvající èást zemìkoule. Opìt jednou bude Amerika svìtovım stráníkem.}
{238}{}{Já jsem také pravı èlovìk.}
{239}{}{Oèištìní od mutantù? To zní trochu drasticky. Jak to chcete udìlat?}

{240}{prs41}{Asi pøed 70 lety jsme našli jedno provozuschopné vızkumné zaøízení. Byla to døívìjší vojenská základna uívaná pro vızkum speciálního viru.}
{241}{}{Viru?}

{242}{prs42}{Ano, F.E.V. virus. Byl pùvodnì vytvoøen, aby zmìnil obyèejné vojáky na super-bojovníky, ale nevyšlo to. Bojovníci sice byli tvrdí a silní, ale úplnì blbí. Nicménì, našim skvìlım chemickım vızkumníkùm se podaøilo ho pozmìnit.}
{243}{}{Pozmìnit virus? Proè?}

{244}{prs43}{Aby se z nìj stal enormnì úèinnı zabiják. Kadı humanoid, kterı nebude naoèkován protilátkou pøed jejím vypuštìním, zemøe. Toto je Projekt.}
{245}{}{To je šílené.}

{246}{prs43a}{Ne, ne. Je to poslední a zároveò nejvìtší lidská nadìje. K tomuto cíli jsme po celá ta dlouhá léta smìøovali.}
{247}{}{Skvìlé, take máte všechen ten jed a ádnı zpùsob jeho rozptılení.}

{248}{prs44}{Nevystaèili jsme s urèitımi rozhodujícími chemikáliemi. Mùeme je ale získat z narkotickıch laboratoøí z New Rena. Jestlie mutantští kriminálníci uívají naše zbranì k vybíjení sebe navzájem, vlastnì nás tím zbavují starostí.}
{249}{}{Všechno pracuje k Vašemu prospìchu, e? Øeknìte mi zbytek pøíbìhu.}

{250}{prs45}{To je jednoduché. Navarro je samostatná základna. Naše vertibirdy mají omezenı dosah doletu. Doplòují tam palivo.}
{251}{}{To dává smysl.}

{252}{prs46a}{Jsem si jistı, e si to myslíš. Ale testy provedené na tvıch kmenovıch spolubojovnících prokázaly urèité postiení mutací. Je zatracenì dobøe, e u je Projekt pøipraven.}
{253}{}{Proè?}

{254}{prs46b}{U nìkterıch z èlenù tvého kmene byli zaznamenány nìkteré neobyèejnì zajímavé zmìny. Kdyby nebezpeèí pro skuteèné lidstvo nebylo tak veliké, rád bych si je trochu prozkoumal. Ale není to moné.}
{255}{}{Není to moné? Proè ne?}

{256}{prs47}{Oh, ale F.E.V. vir má jednu fantastickou vıhodu. Mùeme ho uvolnit tøeba právì zde a pomocí rozprašovaèù ho rozprášíme do celého svìta. Bude mít dost èasu, aby se dostal do kadé dírky a skulinky na celé zemìkouli.}
{257}{}{OK. Pak ovšem nechápu, proè jste unesli mé vesnièany a lidi z Vaultu 13?}

{258}{prs48}{Potøebovali jsme pokusné osoby. Všichni tví vesnièané pochází z Vaultu a my jsme se museli pøesvìdèit, e F.E.V. toxin je stále úèinnı. Na osobách z Vaultu 13 testujeme oèkovací protilátku proti F.E.V.}
{259}{}{Vy netestujete protilátky na mıch lidech?}

{260}{prs48a}{Není to nutné. Jsem si jistı, e bychom mohli vesnièany oèkovat, ale není k tomu ádnı dùvod.}
{261}{}{Nemìl jste nìkdy pocit, e to co dìláte, je špatné?}

{262}{prs49}{Nikdy. Souèástí prezidentovy práce je èinit nelehká rozhodnutí. Mnoho témìø-lidí obìtuje své ivoty pro návrat lidstva. Lidé zvítìzí.}
{263}{}{Není tu ádnı zpùsob, jak se to peklo dá zastavit?}
{264}{}{Jen proto, e všichni tam venku nemají pøesnou kopii vaší DNA, vám nedává právo je vyhladit.}

{265}{prs50}{Nemùeš to zastavit. Pokusy jsou ji hotové a toxin je pøipraven na vypuštìní. Bìhem hodiny budou tví vesnièané jako první obìtováni. Další mutanti je budou následovat. Bude to taková pìkná teèka za tím naším pøípadem.}
{266}{}{A proè tu teèku nenahradit napøíklad vaším nekrologem, pane prezidente?}

{267}{prs51}{Oh, moc se mi nezamlouvá tvùj názor. Kdyby tady byla jiná cesta - ale není. ádná cena není pøíliš vysoká za pøeití lidské rasy. Kdybys byl èlovìk, cítil bys to stejnì.}
{268}{}{Vy tomu asi fakt vìøíte.}

{269}{prs53}{Hmm, ani má smrt by ti moc nepomohla. Nemùeš to zastavit.}
{270}{}{Moná bych vám mìl dát okusit trochu vaší vlastní medicíny.}
{271}{}{Budeme se na to muset ještì podívat. Mám ještì nìjaké vìci na práci. Sbohem, prezidente Richardsone.}
{272}{}{Nesouhlasím, pane prezidente. Myslím, e vaše smrt pomùe. Budu se toti cítit mnohem lépe.}

{273}{prs54}{Mohl bys to zkusit, to pøipouštím, ale zanedlouho bude personál Enklávy a Navarra naoèkován.}
{274}{}{A oni ještì nejsou?}

{275}{prs55}{Musíme rozmístit jednotlivé dodávky. Je to otázkou nìkolika hodin. Kromì toho, Enkláva je hermeticky uzavøenı celek. ádnı vzduch nebo zneèišující látka se nedostane dovnitø ani ven.}
{276}{}{Uvidíme. Mezitím, vás zbavím vašeho kultu osobnosti.}

{277}{prs56}{Moná zjistíš, e je to tìší, ne si myslíš. Paklie to udìláš, alespoò budu vìdìt, e jsem zemøel jako vlastenec a sluebník lidstva.}
{278}{}{Je èas zaplatit.}
{279}{}{Právì teï, vás nechám pøemıšlet o vaší blíící se smrti. Neopovaujte se zmáèknout alarm. Sbohem.}

{280}{prs57}{Velmi dojemné. Ale radikální zmìny pozorované na tvıch vesnièanech a dalších mutantech ukazují velkou rozdílnost od pozvolné pøirozené evoluce.}
{281}{}{Moná jsme se zmìnili v lepší variantu lidské rasy. Pøemıšlel jste o tom nìkdy?}

{282}{prs58}{Vskutku velmi vhodné vysvìtlení. Moná, e právì z tohoto dùvodu je naše mise ještì dùleitìjší k pøeití lidského druhu.}
{283}{}{Huh? Co tím chcete øíct?}

{284}{prs59}{Je to duch. Bùh ochraòuj Ameriku. Mìl by ses teï asi vrátit zpìt do izolace.}
{285}{}{Uh, ano, pane. Cokoliv øeknete, pane.}
{286}{}{Oh, jsem schopnı najít zpáteèní cestu sám, pane. Sbohem.}

{287}{prs60}{No, proti F.E.V. toxinu, samozøejmì. Jak stateèná obì od tebe a od dalších èlenù z Vaultu 13. Za váš prospìch vám jménem vlády Spojenıch Státù a za celé lidstvo, dìkuji. Nyní, bude lepší, kdy tì vrátíme zpìt do tvé cely.}
{288}{}{F.E.V. toxin? O èem to sakra mluvíte? Co se tady dìje?}
{289}{}{Uh, ano pane. Vše co øeknete, pane.}
{290}{}{Oh, jsem schopnı najít zpáteèní cestu sám, pane. Sbohem.}

{291}{prs61}{Asi? Jestlie bude váš druh i nadále vzkvétat, bude to znamenat konec lidské rasy jak ji známe. Nemùeme pøipustit, aby kvùli nìjakım radioaktivním zrùdám, byly lidské bytosti vyhubeny.}
{292}{}{Myslím, e jste to trochu pøehnal.}

{293}{prs62}{Vùbec ne. Jen se podívej se do budoucnosti. Nìkteøí mutanti a lidé 
by spolu moná po nìjakou dobu mohli bez problémù vycházet, 
ale jednou by kvùli poèetní pøevaha vašeho druhu mohly nastat problémy. 
Ne, to nemùeme pøipustit..}
{294}{}{Co chcete udìlat s tím, èemu øíkáte hrozba?}
{295}{}{Nemám èas poslouchat vaše fanatické, šílené blouznìní. Sbohem.}

{296}{prs63}{Vláda Spojenıch Státù Americkıch se snaí najít øešení u dost dlouhou dobu.}
{297}{}{Jak to? Co tady sakra dìláte?}

{298}{prs64}{Mohu tì ubezpeèit, e jsem zcela normální, ostatnì jako kadı, kdo pracuje na Projektu. Jsme oddáni záchranì lidské rasy. Mùeš to nazvat tøeba prostomyslnım bláznovstvím, nebo šílenstvím, ale pokud je to pravda, oznaèil bych to spíše za duchovní šílenství.}
{299}{}{O èem to mluvíte? Co tady provádíte?}
{300}{}{Radši pùjdu, ne mi mé prostomyslné bláznovství øekne, e vás mám na místì zabít.}
{301}{}{Jste blázen. A já právì teï, nemám na ty vaše šílenosti èas. Sbohem.}

{302}{prs65}{Nemyslím si, e je tato stará unavená planeta dost velká pro dva druhy. Pokud bych mìl volit mezi vámi a námi.... No, pak bych si radìji zvolil nás.}
{303}{}{A já zas nás. Máš nìjaké poslední pøání ne øekneš svìtu "sbohem a šáteèek"?}

{304}{prs66}{Jako souèást zákonodárnıch sloek, i já nesu na zádech bøemeno znamenající pøeití a blahobyt Spojenıch Státù a lidstva jako celku. Je to sice tìké bøemeno, ale znamená-li návrat zemì našim dìtem a pak jejich dìtem, ponesu jej rád.}
{305}{}{Jak to hodláte udìlat? Co tady provádíte?}
{306}{}{Nechte mì odstranit to vaše bøemeno. Navdy.}
{307}{}{Musí to bıt pìkné v té vaší dimenzi. Uvidíme se pozdìji, pane Cvoku.}

# Start of Generic Recorded Dialog - Not being used!
{308}{}{Na sever}
{309}{}{Na severozápad}
{310}{}{Na západ}
{311}{}{Na jihozápad}
{312}{}{Na jih}
{313}{}{Na jihovıchod}
{314}{}{Na vıchod}
{315}{}{Na severovıchod}
{316}{}{Ano}
{317}{}{Ne}
{318}{}{Ouch}
{319}{}{(køièí bolestí)}
{320}{}{Proè se mnou takhle mluvíte?}
{321}{}{O tom nevím vùbec nic.}
{322}{}{Nejsi pøíliš pìknı.}
{323}{}{Dìkuji.}
{324}{}{To je dobré.}
{325}{}{To není dobré.}
{326}{}{Mám z toho dobrı pocit.}
{327}{}{Mám z toho špatnı pocit.}
{328}{}{Vy lidé jste blázni.}
{329}{}{O èem to mluvíte?}
{330}{}{Jsou tady kadı jinı blázen?}
{331}{}{Musí tu bıt jinı zpùsob.}
{332}{}{Pojï sem.}
{333}{}{Nerozumím.}
{334}{}{Nevím.}
{335}{}{To bolí.}
{336}{}{To opravdu bolí.}
{337}{}{Zraníte mì.}
# End of Generic Recorded Dialog - Not being used!