#tento soubor pøeloil Somnambulus - somnambulus@hotmail.com, http://www.geocities.com/Area51/Vault/4193/
{100}{}{Vidíš statnou enu v hornickém odìvu.}
{101}{}{Vidíš "Rouhavou" Betty, horníka z dolu Morningstar.}
{102}{}{Vidíš sebevìdomì se tváøící svalnatou enu.}
{103}{}{Caminetto, jsou všichni horníci z Kokoweef jen psi, co nekoušou?}
{104}{}{Já ti ukáu kam máš jít, Rouhavá Betty.}
{105}{}{Ty bys nedokázal ukázat nic ani kdybys na to mìl mapu.}
{106}{}{Ale to jen proto, e se k tobì nechci moc pøibliovat.}
{107}{}{Moc si lichotíš ty zakrslíku.}
{108}{}{Vdy ty bys byla šastná kdybys mìla takového zakrslíka a nemusela sis tam cpát
 vrtaèku jako to normálnì dìláš.}
{109}{}{No ta vrtaèka to aspoò vydrí dıl ne tøicet sekund.}
{110}{}{Není divu, e jsou vrtáky u Morningstaru vìènì zlámány.}
{111}{}{Já ti ukáu jak je lámu ale pouiju na to pìsti!}
{112}{}{Tvoje pìsti? To není potøeba. Staèí tvùj odìr z pusy, zlato. Zkus si taky nìkdy
 vyèistit zuby.}
{113}{}{Nechápu jak ty to mùeš cítit pøes ten oblak svıho vlastního smradu.}
{114}{}{Smrad? Jen pohled na tebe mi pùsobí mnohem vìtší bolest.}
{115}{}{Ty nevíš o bolesti vùbec nic, ale já ti o ní dám pár lekcí.}
{116}{}{Ty mnì?}
{117}{}{Jo, správnì. Tvoje máma na to asi zapomnìla.}
{118}{}{Teï zaèneš mluvit o mojí mámì? To není moc originální.}
{119}{}{Jo, originálnìjší bude, kdy ti udìlám novı ksicht. Na ten starı u se nedá koukat.}
{120}{}{Ty? A kde na to vezmeš lidi?}
{121}{}{Vystaèím si sama. Vsadím se, e my z Morningstaru vás rozneseme levou zadní.}
{122}{}{Nemyslím. Tady vládne Kokoweef. Mìl bych tì o tom pouèit.}
{123}{}{To se ti bude tìko dìlat, kdy budeš v bezvìdomí.}
{124}{}{Myslíš, e budeš mít takové štìstí, huh?}
{125}{}{Na to abych tì zadupala do podlahy, nepotøebuju štìstí.}
{126}{}{No, tlustá jsi na to dost, to je fakt. Uh oh, u se bojím.}
{127}{}{Tak se uka anebo sklapni, ty skrèku.}
{128}{}{Tak jen pojï, ty imbecile.}
{129}{}{A kdo teï doufá, e bude mít kliku?}
{130}{}{U toho mám dost, za tohle tì vynesu v zubech.}
{131}{}{Zatracenì kdo to na nás èumí?}
{132}{}{To je nìkdo novı. Hej tohle je soukromá záleitost! Tak nás vynech!}
{133}{}{Pro jednou s tebou musím souhlasit. Vodpal!}
{134}{}{A kdo teï bude tìit zlato, huh, chytrolíne?}
{135}{}{Trochu zasranıho volna mi bodlo.}
{136}{}{A to budu v tı smradlavı díøe s touhle štìnicí?}
{137}{}{Caminetto, tvoje podìlanı dny jsou seèteny.}
{138}{}{Polib si prdel a øekni sbohem.}
{139}{}{Do hajzlu, koukej mì odsud pustit!}
{140}{}{Hej ty vtipálku, pust mì ven!}
{141}{}{Hej šerife! Kdy mì pustíš tak ti ho pøeblafnu.}
{142}{}{Pøíštì se na to vykašlu.}
{143}{}{Na co sakra cuèíš?}
{144}{}{Co chceš, hovòousku?}
{145}{}{Nedovolím vám, abyste se navzájem pomlátili.}
{146}{}{Jen se dívám, co se tu dìje.}
{147}{}{Tahle hospoda je plná svinstva a já a mí hoši z Morningstaru ho hodláme vymést
 ven na ulici. To nejvìtší hovno má dokonce jméno - Caminetto.}
{148}{}{Proè? Jak to zaèalo?}
{149}{}{To vidím. Jene já ti to nedovolím. Koukej rychle zabrzdit.}
{150}{}{Jen se na ty schlíplı ptáky podívej. Kdo by odolal tomu pokušení vytøít s nima podlahu?}
{151}{}{Tohle mi nepøijde jako dobrı dùvod. Nenechám vás, abyste se pomlátili.}
{152}{}{No dobøe, to vypadá jako vánı dùvod. Nebudu vás rušit. Hodnì štìstí.}
{153}{}{A co s tim jako hodláš udìlat, ty mizernej patolízale?}
{154}{}{Prvního, kdo udeøí, zabiju.}
{155}{}{No, nejdøív vás mile poádám. Potom vytáhnu bouchaèku a budu èekat, kdo první mi dá šanci
 trochu se pocvièit ve støelbì.}
{156}{}{Šerif mì poádal o pomoc do doby ne bude mít zdravou nohu. Dal jsem mu svoje slovo, e tu bude klid.}
{157}{}{Jo? Ten Marion je ale chytrák. Oukej, kvùli nìmu dám teda tìmhle nadrencùm z Kokoweef pokoj.}
{158}{}{Díky. Doufal jsem, e se na to budeš dívat stejnì. Sbohem.}
{159}{}{Co si o sobì vlastnì myslíš ty napudrovanej kovboji. Tvùj pøidrzlej tón se mi setsakramentsky nezamlouvá.}
{160}{}{Nemusí se ti líbit. Buï se mnou pùjdeš do basy dobrovolnì nebo tu zbude jen tvoje mrtvola. Je to na tobì.}
{161}{}{Oh, promiò. Opravdu jsem nechtìl bıt tak nezdvoøilı. Radši u pùjdu. Mìjte se.}
{162}{}{Jo? No dobrá, nìco ti povím. Pùjdu, kdy zabásneš i toho smrada Caminetta.}
{163}{}{Nejsi zrovna v situaci, kdy si mùeš klást podmínky.}
{164}{}{To není špatnı nápad. Kdy mezi vámi budou møíe tak snad trochu vychladnete.
 Hnìte sebou, vy dva.}
{165}{}{Kape ti na mozek? Jestli si nìco zkusíš, tak nás všechny o to víc naštveš.
 A pak tu poteèe krev. Myslíš, e se to šerifovi bude líbit?}
{166}{}{No, to asi ne.}
{167}{}{To je mi jedno. Nebude to moje krev co tu poteèe.}
{168}{}{No, moná bych si mohla trochu odfrknout. Nesedla jsem si, ani nepamatuju. (k
 ostatním) Dejte si pohov, hoši. Uvidíme se zítra v práci.}
{169}{}{To je rozumná volba.}
{170}{}{Nemìj obavy, beru Caminetta s sebou a bude ti tam dìlat spoleènost. Je to tak, Caminetto?}
{171}{}{Ty nám u toho chceš kibicovat? Jen se do toho zkus míchat a my všichni i ten
 schlíplej ocas Caminetto s tebou zametem.}
{172}{}{No tak to vás budu muset zavøít oba.}
{173}{}{No tak to vás budu muset odprásknout oba.}
{174}{}{Hmm, myslím, e mì zrovna teï potøebujou jinde ve mìstì. Budu muset jít. Sbohem.}
{175}{}{Jsi chytøejší ne vypadáš. Ale to asi musíš bıt, kdy jsi poøád ještì naivu. Teï bì ale zpátky domù k mamince
 a øekni jí, e jsme na tebe byli hroznì moc oškliví.}
{176}{}{Tak dost. U mám tìch tvıch kecù právì akorát. Poslední vızva. Pojï v klidu se mnou nebo z tebe nadìlám kousky
 do polívky.}
{177}{}{Moná to udìlám. Nechci nikomu ublíit. Sbohem.}
{178}{}{Já vím jak to chodí, ty špinavej zmetku. OK, pùjdu s tebou a Caminetto taky.
 (ke Caminettovi) Správnì, ty mùj ocásku?}
{179}{}{To se mi líbí.}
{180}{}{Ne. U je pozdì. Udìlám z vás obou rádlo pro psy. }
