#Tento soubor pøeloil Jiøí "Markus" Petrù - jpe@iol.cz
{100}{}{Vidíš spoøe obleèenou enu.}
{101}{}{Vidíš Fannie Mae, jednu z hostesek Hospody u malamuta.}
{102}{}{Tahle enská vypadá, e u má najeto pìknıch pár kilometrù. Mezi nohama.}
{103}{}{(Fannie je celá bledá a vrávorá smìrem k tobì) Nazdar drahouši. Mohl bys obìtovat trochu penìz na palivo?
 Já bych ti to nìjak vrátila (køení se).}
{104}{}{(Fannie je celá bledá a vrávorá smìrem k tobì) Nazdárek, sestro. Mohla bys obìtovat trochu penìz na pomoc
 nešastnému èlovìku? Však já u bych ti to nìjak vrátila.}
{105}{}{(Fannie nevypadá zrovna nejlépe) Ahoj slaïouši. Jsi pøipraven uít si trošku srandy s Fannie? Tobì dokonce
 slevím polovinu. (Sama k sobì:)Kam jsem jenom dala ten Jet?}
{106}{}{(Fannie nevypadá zrovna nejlépe) Nazdárek, sleèinko. Nepøebıvají ti nìjaké peníze? Nebo tøeba Jet?}
{107}{}{Fannie, vypadáš opravdu hroznì. Proè na chvíli nenecháš ten Jet na pokoji?}
{108}{}{Myslím, e u jsi okusila hodnì z mojí dobroèinnosti, take teï ti u nepomùu.}
{109}{}{U jsi mìla dost.}
{110}{}{Proè se z toho radši nevyspíš?.}
{111}{}{Jet je jediná vìc, která mi pomùe létat. ./~Pojï létat se mnou ./~ Cítím se s ním jako bohynì.}
{112}{}{Ó, koukám, e je tu nìkdo plnı ušlechtilıch myšlenek. Dobrá, nepotøebuji tì. Je spousta lidí,
 kteøí si zaplatí za Faniin pùvab. Jestli mi nedáš prachy na Jet, tak mi zmiz z oèí.}
{113}{}{Mám nìco, co dokáe vyléèit tvojí závislost na Jetu.}
{114}{}{Najdi si nìjakého závisláka, Fannie. Sbohem.}
{115}{}{Kdy pùjdeš touhle cestou, tak se sama zabiješ. Nehodlám tì pøi tom pozorovat. Sbohem.}
{116}{}{Ty jsi ale podívaná.}
{117}{}{Fannie je oblíbená u chytøejších.}
{118}{}{Vra se, a budeš mít víc penìz a Fannie tì moná nìèemu pøiuèí.}
{119}{}{Nejseš zrovna ta nejostøejší vìc pod støechou, co?}
{120}{}{Ty se mi budeš líbit jedinì jako návnada na ryby.}
{121}{}{Vyléèit? Jsi blázen? Vypadám snad, e bych chtìla vyléèit? Máš mì snad za blba? Radši mi dej další Jet.}
{122}{}{No dobrá, vypadáš, e to opravdu potøebuješ. Tady máš Jet.}
{123}{}{U jsi mìla dost Jetu. Poslední vìc, co chci vidìt, je další závislı na Jetu. Sbohem.}
{124}{}{Kdybych mìl Jet, tak bych si ho stejnì nechal. Sbohem.}
{125}{}{Jo. To je to, co potøebuju. Vıbornì. To je skvìlé. Mmmmm...}
{126}{}{No dobøe. Nechám tì, aby sis to mohla poøádnì uít. Ahoj.}
{127}{}{Zdá se, e jsi pìknì zfetovaná. Uvidíme se pozdìji.}
{128}{}{Nazdar, kámo. Moc ráda tì tu vidím. Pøišel jsi sem navštívit Fannie Mae?}
{129}{}{Zdravím, sestro. Sháníš práci?}
{130}{}{Err, ano. Pøišel jsem tì navštívit.}
{131}{}{Práci? Jakou práci?}
{132}{}{Eh, vlastnì se tu jenom rozhlíím. Sbohem.}
{133}{}{Ty jsi ale slaïouèkı. A pìknì ostıchavı. Návštìva u mì tì bude stát jen 60$, zlato.}
{134}{}{Kdy se tak na tebe dívám, asi tì u sebe nechám trošku déle. Co ty na to? Bude to jen za 60$.}
{135}{}{Pìknì popoøádku, drahouši. Zavedu tì do sedmého nebe za pouhıch 60$. Souhlas?}
{136}{}{60 babek? To je docela rozumná cena. Tady máš peníze.}
{137}{}{Díky za nabídku, ale snad u sebe pøíštì budu mít víc penìz. Zatím ahoj.}
{138}{}{60$? To u je moc i na mne. Sbohem.}
{139}{}{Byl jsi ke mnì tak milı. Cítila jsem, e to pro tebe nìco znamenalo. (vzlyk) Pøála bych si,
 aby to bylo vdycky stejné.}
{140}{}{Se mnou to takové bude pokadé.}
{141}{}{Opravdu víš, jak nenápadnì pøinutit lidi, aby pøišli znova.}
{142}{}{Nemáš pravdu. Já si to u nebudu moci víckrát zopakovat. Odcházím odsud a budu ít spoøádanım ivotem. Akorát musím
 brzo zaplatit Lou.}
{143}{}{Zaplatit Lou?}
{144}{}{Dám ti ty peníze, kdy mi ale øekneš o co jde.}
{145}{}{Víš... Dluím Lou nìjaké peníze a nemùu odjet døív, ne jí zaplatím. Ale hned jakmile to udìlám,
 (smrk) vezmu s sebou svého pøítele a zmizíme odsud tak daleko, jak to jen pùjde. Pokud se mi ale podaøí sehnat nìjaké
 peníze.}
{146}{}{Kolik penìz potøebuješ zaplatit Lou?}
{147}{}{A to ti s tìmi penìzi nemùe pomoci tvùj pøítel?}
{148}{}{Zní to velice neštastnì, ale podle mì ty peníze brzy seeneš. Pøeju ti hodnì štìstí. Sbohem.}
{149}{}{Všechno co potøebuju, je pouhıch 200$. Mùj pøítel a já odsud chceme odejít nezadluení a volní. U ádní další
 ušpinìní lidé, osahávající mì ve dne v noci. Eh, tím jsem nemyslela nic osobního. }
{150}{}{Já vím, pøece mezi takové lidi nepatøím. Mùu tì ale odsud vyplatit, tady máš 200$.}
{151}{}{Opravdu ti nezávidím. Nedokáu si pøedstavit, co bych dìlal v tvé kùi. Sbohem.}
{152}{}{Eh, dìkuju, dìkuju. Nemyslela jsem si, e nìkdo takovı existuje jinde, ne v mıch snech. Jsem ti nadosmrti
 zavázána. Poèkej ještì. Nedáme si to ještì jednou? Zadarmo?}
{153}{}{Dobrı nápad. Velice rád tvou nabídku pøijímám.}
{154}{}{To opravdu není nutné, Fannie. Radši bì hned za Lou a dej jí ty peníze. Sbohem.}
{155}{}{On by opravdu chtìl, ale pracuje jako horník a má malı plat. Sotva se uivíme, nato abysme
 ještì spláceli dluhy. Navíc, minulı tıden na nìj spadl trám a zlomil mu nohu, take teï nemùe pracovat.
 Já se mu snaím dát tìch pár penìz, které našetøím, aby se mu vedlo lépe.}
{156}{}{To vypadá, e vy dva asi nemáte moc velké štìstí. Kolik e potøebujete?}
{157}{}{Mnohokrát díky. U bìím oznámit tu radostnou novinu svému chlapci. Vypadneme odsud hned, jakmile
 se jeho noha uzdraví.}
{158}{}{To byla malièkost, Fannie. Já u asi taky pùjdu. Sbohem.}
{159}{}{Tento podnik hodnì utrpí tvım odchodem. Je to škoda. Sbohem.}
{160}{}{Vítám tì. Hodláš strávit nìjakı èas s Fannie?}
{161}{}{Nedal jsem ti peníze, abys tohle pøestala dìlat?}
{162}{}{Velice rád. Koneènì si zase trochu uiju.}
{163}{}{No, ano. Ale ukázalo se, e dluím Lou víc, ne jsem myslela.}
{164}{}{Kolik ti ještì mám dát?}
{165}{}{To u mi do hlavy nenatluèeš. Sbohem.}
{166}{}{Jsem ti opravdu vdìèná... ale bohuel dluím Lou víc, ne jsem myslela. Potøebuju další peníze.}
{167}{}{Tomu nevìøím! Kolik penìz ještì potøebuješ?}
{168}{}{U jsi ze mì dostala úplnì všechno. Sbohem.}
{169}{}{Nemusíš nic, u jsi pomohl dost. (popotahuje) Potøebuju u jenom 150$.}
{170}{}{Pomohu ti velice rád. Tady to máš.}
{171}{}{Kdy nechceš, tak já zase odejdu. Sbohem, Fannie.}
{172}{}{Vítám tì zpátky. Chceš si trošku uít, nebo ses vrátil, abys mi dal nìjaké peníze pro Lou?}
{173}{}{Pøišel jsem si uít, Fannie. Tak uka, jak ti to jde.}
{174}{}{Kolik penìz ještì potøebuješ zaplatit Lou?}
{175}{}{Jenom tak procházím. Sbohem, Fannie.}
{176}{}{Vdycky jsem ráda, kdy si to mùu zopáknout. Kvùli tobì pokadé vymìním prostìradlo.}
{177}{}{V tomhle jsi opravdová jednièka. Díky.}
{178}{}{Rozmyslel jsem si to. Uvidíme se pozdìji, Fannie. Ahoj.}
{179}{}{Ty teda umíš, brouku. Vsadím se, e s takovou figurou si tu mùeš ít pøímo královsky.}
{180}{}{Ty tedy umíš, brouku. S tou tvojí postavou si urèitì pìknì pøivydìláš. Ti horníci nejsou zrovna nároèní, já mùu
 vyprávìt.}# - To "particular" mi tam trošku nesedlo. Snad to muze bejt takhle
{181}{}{Myslíš? Teda, snad by to šlo.}
{182}{}{To není nic pro mì. Sbohem, Fannie.}
{183}{}{Víš, tìko se pracuje kdy zapácháš tak pronikavì, jako místní horníci. Ti taky nemají vodu a mıdlo pøíliš v lásce.}
{184}{}{Opravdu? To po ale není nic pro mne. Sbohem.}
{185}{}{Nechápu, jak ty horníky mùeš vystát, ale asi to nìjak jde. Hlavnì vydr. Sbohem.}
