#tento soubor prelozil MAG2
#
{100}{}{Vidíš postavu, která má na sobì kevlarovou zbroj.}
{101}{}{Vidíš strá.}
{102}{}{Vypadá to, e tu stojí a na nìco èeká.}
{103}{}{Jo, jo. Bì dál.}
{104}{}{Sna se zalíbit panu Busterovi, a nemusíme plıtvat municí.}
{105}{}{Kopu se tu do zadku a vıkám vıkaèky. Máš štìstí, mám ještì jednu.}

{106}{}{K èertu, na co èumíš? Odpal.}
{107}{}{Hej, tak takhle ne. Radši se ke mnì moc nepøibliuj.}
{108}{}{Joo, je fajn stát se takou. Nemohli bychom si pozdìji zajít na drink?}
{109}{}{Cukrouši, radši budu spát s brahmínami, ne abych tì musel znovu vidìt}

{110}{}{Nìco si kup a táhni ke všem èertùm.}
