#tento soubor prelozil MAG2
#
{100}{}{Vidíš malého umaštìného chlapíka.}
{101}{}{Díváš se na Bustera, obchodníka se zbranìmi.}
{102}{}{Jeho obleèení je roztrhané, ruce, pae i oblièej má zaèouzené od støelby. Ale pøesto vypadá spokojenì.}
{103}{}{Ahoj, vítej do Busterova zbrojního centra! Já jsem Buster. Vyber si z toho nejlepšího zboí, které vidíš tady a v policích. Prohlídni si všechno. Rád ti nìco prodám}
{104}{}{Ahoj, zase zpátky? Co pro tebe mohu udìlat?}
{105}{}{Ještì nìco?}
{106}{}{Chtít zbraò.}
{107}{}{Tak co máš?}
{108}{}{Moná bys pro mì mohl udìlat nìco speciálního?}
{109}{}{Mám pár otázek.}
{110}{}{Sbohem.}
{111}{}{Vıborná volba!}
{112}{}{Dobrá, máš to mít, paráku.}
{113}{}{Nechci tì rušit, cizinèe, ale mám spoustu práce.}
{114}{}{Jistì, cizinèe co chceš vìdìt?}
{115}{}{Øekni mi nìco o NCR}
{116}{}{Copak je s Merkem?}
{117}{}{Co mi mùeš øíct o Franku Westinovi?}
{118}{}{Chci se sejít se starım Carlsonem. Mùe mi nìkdo pomoci?}
{119}{}{Máš GECK?}
{120}{}{To je hezké cizinèe, ale s tím si jdi jinam.}
{121}{}{Moná. Mùeš mít zamìøovaè na pušku - Triveld x10 - snadno jde pøidìlat na loveckou pušku, jestli máš zájem. Je levnı -- $500.}
{122}{}{Hej, ty mì chceš sedøít z kùe.}
{123}{}{Jo, tomu øíkám obchod.}
{124}{}{Ne, díky.}
{125}{}{New California Republik - to je ono. Prezidentka Tandi a její skupina tvrdí, e zkouší zmìnit staré èasy; podle mì spíš zkouší ukrást, co sedá. K èertu, nemùu øíct, e to nezkouší, staré èasy jsem nezail. Ale je to pìkná banda, øekl bych - nemají rádi otrokáøství, hazardní hry, nic. Proto jsem odtamtud vypadl. Nesnáším naøízení - nikdy jsem je nesnášel.}
{126}{}{Aha.}
{127}{}{Sbohem.}
{128}{}{Nepotkal jsem se s panem Merkem a nemá cenu o nìm roznášet drby. Jestli máš nìjaké otázky, bì se na nìj pøeptat do Rahwide.}
{129}{}{Aha.}
{130}{}{Sbohem.}
{131}{}{Frank Westin? Máš na mysli toho kongresmana? Najdeš ho západnì od mìsta. Øíká se mu "Brahmín Man" - je velké zvíøe ve Stockmenovì asociaci. Poøád hledá schopné lidi, jestli ti jde o práci.}
{132}{}{Aha.}
{133}{}{Sbohem.}
{134}{}{Je zvláštní, e se na to ptáš, potom co se stalo Franku Westinovi. Já nic nevím, ale je tu nìkdo - Merk - dole "U nevydìlanı kùe", kdo by ti moná mohl pomoci.}
{135}{}{Aha.}
{136}{}{Sbohem}
{137}{}{Jeden z tìch pøedváleènıch dovozù? To je 14mm munice? Nemám ani kousek.}
{138}{}{Aha.}
{139}{}{Sbohem}
{140}{}{Hele, je to moné udìlat jen s loveckou puškou. Na ni je to moné namontovat, jasné?}
{141}{}{Aha.}
{142}{}{Sbohem.}
{143}{}{Mám teï zavøeno. Odejdi.}
{144}{}{Boe! Pøijï v rozumnìjší dobu, ok?}
{145}{}{Pøijï a bude otevøeno - a nevztekej se.}
{146}{}{Mám zavøeno.}
{147}{}{Hele, vypadni nebo si s tebou promluví moje zbranì!}
{148}{}{Špatnı tah, cizinèe.}
{149}{}{To je vše, co mám v téhle polici. Jestli potøebuješ nìco dalšího, zkus další police.}
