#tento soubor prelozil MAG2
#
{100}{}{Byl to takový starší, útlý muž.}
{101}{}{To je vicepresident  Carlson.}
{102}{}{Aèkoliv fyzicky sláb, jeho oèi prozrazovaly velkou morální sílu. Toto je rozhodný èlovìk.}
{103}{}{Co tady dìláš? Stráže!}
{104}{}{Ty nepatøíš k mým mužùm. Stráže!}
{105}{}{Kliï se odsud!}

{106}{}{Jsem navýsost zaneprázdnìn. Prosím, pøijï jindy.}
{107}{}{Podívej se, nechci být nepøíjemný, ale potøebuji více èasu na práci.}
{108}{}{Promiò, ale nemám teï na tebe èas.}
