#tento soubor prelozil MAG2
#
{100}{}{Vidíš usmrkané malé dítì.}
{101}{}{To je dítì viceprezidenta Carlsona.}
{102}{}{Vypadá jako nevyvedený zakrslík. A taky tlustý.}
{103}{}{Mùj tatínek je viceprezident Carlson, tak podle toho se mnou taky zacházej. Kdo jsi?}
{104}{}{[Player name]}
{105}{}{Jsem jeden ze strážcù tvého otce.}
{106}{}{Kde je tvùj tatínek?}
{107}{}{Vidíš ten nùž? Ten už zaøíznul hezèí dìti, než jsi ty.}
{108}{}{Já jsem tvá nejhorší noèní mùra, holomku.}
{109}{}{Promiò hochu, nemám èas.}
{110}{}{? To je ale mizerné jméno. Máš debilní jméno! Debilní!}
{111}{}{Tak to bys mìl být na mì extra hodný, nebo to povím tatínkovi.}
{112}{}{Och? A o mì (šeptem).}
{113}{}{Správnì, chlapèe.}
{114}{}{Je uvnitø. Ve své kanceláøi. Vždycky tam je.}
{115}{}{Kde má kanceláø?}
{116}{}{OK. Díky.}
{117}{}{Kolem zásobníku vody. Nìkdy si tam hraju. Dívám se, když pracuje.}
{118}{}{Nejsi nic než nepøíjemný malý spratek, že jo?}
{119}{}{Díky, moc jsi mi pomohl.}
{120}{}{Nejsi hodný, jsi zlý! Jdu to øíct tatínkovi!}
{121}{}{Ale, to jsi zase ty. Jak se daøí?}
{122}{}{Zeptej se otce, jestli ho mùžu navštívit.}
{123}{}{Øekni otci, že mám zprávy o panu Bishopovi. Zapamatuješ si to?}
{124}{}{Fòuk.}
{125}{}{Jsi blbý spratek! Blbý!}
{126}{}{Okej.}
{127}{}{Zprávy o panu Bishopovi. OK?}
{128}{}{Staèí.}
{129}{}{Tatínek øíká, že se s tebou nemùže vidìt.}
{130}{}{Øekl jsem to tatínkovi. Myslím, že tì nemá rád.}
{131}{}{Tatínek øíká, že mùžeš vejít do domu.}
{132}{}{Øekl jsem tatínkovi, že jsi zlý.}
{133}{}{Správnì. Jsem hroznì zlý! A sním tì.}
{134}{}{Štveš mì ty... ehm, dítì.}
{135}{}{Už s tebou nepromluvím.}
{136}{}{Mùj tatínek je mrtvý. Jak mùže nìkdo nìco takového dopustit?}
