#tento soubor prelozil MAG2
#
{100}{}{Další stráž. Nìkdo je snad musí vyrábìt èi co, protože vypadají všichni stejnì.}
{101}{}{Poøád hlídá. Asi se mu nelíbíš.}
{102}{}{Díváš se na nìj zblízka a poznáváš, že je to - hlídaè.}
{103}{}{Nemáš povolení zde být.}
{104}{}{Mohu vidìt tvoji propustku?}
{105}{}{Tohle je státní majetek. Kliï se, cizinèe.}
{106}{}{Tak ty jsi ten nový hoch, he?}
{107}{}{Jestli jsi ještì nemluvil s Carlsonem, radìji to udìlej.}
{108}{}{Pan Carlson tì oèekává.}
{109}{}{Pan Carlson tì pøijme teï.}
{110}{}{Doufám, že je to dùležité. Pan Carlson je velmi zaneprázdnìný èlovìk.}
{111}{}{Je uvnitø. Doporuèuju ti nezdržovat se pøíliš dlouho.}