#tento soubor prelozil MAG2
#
{100}{}{Další stráž. Nìkdo je snad musí vyrábìt èi co, protože vypadají všichni stejnì.}
{101}{}{Poøád hlídá. Asi se mu nelíbíš.}
{102}{}{Díváš se na nìj zblízka a poznáváš, že je to - hlídaè.}
{103}{}{Nemáš povolení zde být.}
{104}{}{Mohu vidìt tvoji propustku?}
{105}{}{Tohle je státní majetek. Kliï se, cizinèe.}
{106}{}{Ty jsi ten Merk? OK, nechte ho projít.}
{107}{}{Tohle konèí. Zùstaòte stranou, hoši.}
{108}{}{OK, v poøádku. Otevøete bránu, hoši.}
{109}{}{Ty jsi Merk? OK, nechte ji projít.}
{110}{}{Jsem ve službì. Není vhodný èas na bratøíèkování.}
{111}{}{Hej, pìkné boty.}
{112}{}{Jdi si po svým.}
