#tento soubor pøeložil Somnambulus...somnambulus@hotmail.com
{100}{}{Vidíš pana Podfukáøe.}
{101}{}{Tenhle chlap nemá v takový poctivý høe co dìlat.}
{102}{}{Hele to je podvodník.}
{103}{}{Hej! To bolí!}
{104}{}{Dobrý den, co pro Vás mohu udìlat.}
{105}{}{Podfuky kolem Westinovy osoby.}
{106}{}{Udìlej to, že pøijímám zakázku na likvidaci Westina.}
{107}{}{Udìlej to, že odmítám pøijmout zakázku na likvidaci Westina.}
{108}{}{Nastav, že je Westin po smrti.}
{109}{}{Zruš Westinovu smrt.}
{110}{}{Nastav to, že Westin nebyl zlikvidován.}
{111}{}{Nastav to, že Westin byl zlikvidován.}
{112}{}{Udìlej to, že Westin ví o drogách.}
{113}{}{Udìlej to, že Westin neví o drogách.}
{114}{}{Zpùsob Westinùv pád.}
{115}{}{Zruš Westinùv pád.}
{116}{}{Zkompletování Westinova questu.}
{117}{}{Zruš kompletaci Westinova questu.}
{118}{}{Nastav to, že Westin ví o zakázce na jeho likvidaci.}
{119}{}{Nastav to, že Westin neví o zakázce na jeho likvidaci.}
{120}{}{Podfuky kolem Carlsonovy osoby.}
{121}{}{Nastav Carlsonovu likvidaci.}
{122}{}{Zruš Carlsonovu likvidaci.}
{123}{}{Udìlej to, že je Carlson po smrti.}
{124}{}{Zruš Carlsonovu smrti.}
{125}{}{Pøidej ke Carlsonovi ochranku.}
{126}{}{Zruš tu Carlsonovu ochranku.}
{127}{}{Nastav odmítnutí Carlsonovy likvidace.}
{128}{}{Zruš odmítnutí Carlsonovy likvidace.}
{129}{}{Zkompletuj quest kolem Carlsona.}
{130}{}{Zruš kompletaci questu kolem Carlsona.}
{131}{}{Zpùsob Carlsonùv pád.}
{132}{}{Zruš Carlsonùv pád.}
