#tento soubor prelozil MAG2
#
{100}{}{Vidíš postavu obleèenou v uniformì NCR policie.}
{101}{}{Policista.}
{102}{}{Tenhle zøejmì odsuzuje i za nepøíjemnı ksicht, neèekej tady ádnı soucit.}
{103}{}{Odhoï zbraò - HNED!}
{104}{}{V tomto mìstì se nesmí nosit zbranì, cizinèe. Schovej zbraò.}
{105}{}{Schovej zbraò a nikomu nebudeš vadit.}
{106}{}{Je zákaz vycházení, cizinèe. Co tu dìláš?}
{107}{}{Bì dál. Tady není nic k vidìní.}
{108}{}{Noc není vhodná doba na procházky po ulicích.}
{109}{}{Dobrı den, cizinèe. Jsi tady nováèek?}
{110}{}{Bì dál. Tady není nic k vidìní.}
{111}{}{Jsem zamìstnán. Jestli je nìjakı problém, ohlaš to šerifovi.}

{112}{}{Hej, pøestaò se do toho plést..}
{113}{}{Nechej toho.}
{114}{}{Do toho se neple.}
{115}{}{Jestli s tìmi hloupostmi nepøestaneš, mám povolení tì zastøelit.}
