#tento soubor prelozil MAG2
#
{100}{}{Vidíš mladou enu, obleèenou v pracovním obleku.}
{101}{}{To je Dorothy, mìstskı mechanik.}
{102}{}{Z té kolomazi a špíny na ní, se dá soudit na technickı typ. Zvláštì kdy jí je všude v patách údrbáøskı robot.}
{103}{}{Och boe, nìkdo musí nìco udìlat! Co mám dìlat? Potøebuju rychle pomoc.}
{104}{}{He? Ugh?}
{105}{}{Co se dìje?}
{106}{}{To je za pìt minut dvanáct. Zastav toho zlého mue. Nesmí poškodit pøístroje. Okej?}
{107}{}{Okej.}
{108}{}{Ne, tohle neudìlám.}
{109}{}{Ach boe, jde o Jacka. Vyhrouje, e vyhodí elektrárnu do vzduchu. Nemám jak ho zastavit. Ty to zvládneš, e ano?}
{110}{}{Neztrácejme èas. Jdi napøed.}
{111}{}{To není moje starost. Najdi si nìkoho jiného.}
{112}{}{Poslouchej - Jack je uvnitø. Je rozhádanı se svojí bıvalou enou. V poslední dobì nemìl dobré èasy. Øíká, e má bombu. Jestli ano, bude pravdìpodobnì vpravo vedle dynama. Take - zkus, jestli se ti podaøí odvést jeho pozornost, ale hlavnì udìlej cokoliv, aby to neodpálil!}
{113}{}{Jak to mám udìlat?}
{114}{}{V pohodì, mám to pod kontrolou.}
{115}{}{Já nevím! Jsem jenom mechanik. Ty ho musíš zastavit!}
{116}{}{Sakra! Poškodil centrální jednotku. Musí se opravit døív, ne to všechno vyletí do vzduchu. Vyznáš se v opravách?}
{117}{}{Ugh.}
{118}{}{Jo.}
{119}{}{Ne}
{120}{}{Co jsem to chtìla?}
{121}{}{Podívej se, dìlej co umíš s generátorem. Já zkusím stabilizovat jádro. Øekla bych, e na to máš tak 30 sekund. Pak bude pozdì. Do toho, Toto.}
{122}{}{Do háje! Tak se dr zpátky. Jestli neuspìju, všechno vyletí do vzduchu. Pojïme Toto.}
{123}{}{Opraveno? Bez jakéhokoliv náhradního dílu?! To je neuvìøitelné! Musíš mít velké znalosti.}
{124}{}{Huh-huh!}
{125}{}{Prostì mám na to buòky.}
{126}{}{Áhá... Ty jsi jeden z tìch blbcù - jak se jim jenom øíká? Dobrá, podívej - idiot nebo ne, dostaneš cenu. CE-NU - ty osobnì. Dám ti pìknou kníku. Vidíš. Dej prachy. Dobøe...}
{127}{}{Podívej, není to nic moc, ale mám pár knih - staré technické pøíruèky. Jsou tvoje. Vem si je.}
{128}{}{Hej, koukni se Toto. To je ten cizinec, kterı nám pomohl. Ještì jednou díky, pane.}
{129}{}{Do háje! Spadla celá sí. To zabere celou vìènost tohle opravit. No, není èas na zbyteèné øeèi. Pojïme na to, Toto.}
{130}{}{Hele, nedávám ti za vinu to, co se stalo, ale skuteènì nemám náladu na rozhovory.}
{131}{}{Kdy jsem øíkala, e potøebuji pomoc, nemyslela jsem ho zabít! Copak, bylo tohle nutné? Nebyla jiná monost!!?}
{132}{}{Ano.}
{133}{}{Ne.}
{134}{}{Kdy ano, tak proè tohle? Zabít ho... paneboe!! Kliï se odtud ty zrùdo!}
{135}{}{To je hrozné. Nevím, co ho to popadlo? Mìsto ti dluí podìkování. Podívej se, není to nic moc, ale mám tady nìjaké technické pøíruèky. Moná se ti je podaøí prodat nebo tak nìco...}
{136}{}{Nemluv na mì ty zabijácká svinì.}
{137}{}{Není èas na øeèi, cizinèe. Mé jméno je Dorothy, jsem mìstskı mechanik a toto je Toto. Utíkejme.}
{138}{}{Nemáš náhodou modulátor Q-38, e? Je mi to jasné.}
{139}{}{Ty jsi ho pøemluvil? To je neuvìøitelné! Mìsto je teï tvım velkım dluníkem, uvìdomuješ si to? Podívej se, není to nic moc, ale mám tady nìjaké technické pøíruèky. Moná se ti je podaøí prodat nebo tak nìco...}
{140}{}{No to bylo úasné s tím Jackem. Opravdu skvìlé. Já a Toto teï musíme jít. Sbohem!}
{141}{}{Kuš! Mám jenom jednu radu - PADÁME!}

{142}{}{Hele, koukni se Toto. To je ten cizinec, kterı nám pomohl. Ještì jednou díky, pane.}
{143}{}{Ty jsi ho pøemluvila? To je neuvìøitelné! Mìsto je teï tvım velkım dluníkem, o tom ádná. Podívej, není to nic moc, ale mám tady nìjaké technické pøíruèky. Moná se ti je podaøí prodat nebo tak nìco.}

{144}{}{Neztrácej èas! Myslí to vánì.}
{145}{}{Musíš teï nìco udìlat!}
{146}{}{Nestùj tam tak -- zastav ho!}
{147}{}{Kliï se odtud, ty brahmíní lejno.}
{148}{}{Nemluv na mì, ty zbabìlèe.}
{149}{}{Co jsi zaè!?}
