#tento soubor prelozil MAG2
#
{100}{}{Vidíš svého starého pøítele.}
{101}{}{To je doktor Jubilee.}
{102}{}{Je to starı mu s bílou bradou a prázdnım strnulım pohledem.}
{103}{}{Jsem doktor Jubilee. Co se dìje mladı mui?}
{104}{}{Co se dìje mladı mui?}
{105}{}{Já mít zranìní.}
{106}{}{Potøebuju doktora.}
{107}{}{Nemùeš si vzít nìjaké pilulky nebo nìco a pøestat mì trápit tím vanìním?}
{108}{}{K èertu, silnì krvácíš.}
{109}{}{Nevím. Myslím, e ji nemùem zachránit. Asi bychom mìli tu nohu amputovat.}
{110}{}{Kecáš.}
{111}{}{Ha-ha.}
{112}{}{Tady jsi, synku.}
{113}{}{Zase.}
{114}{}{Díky, doktore. Moná mi mùeš pomoct zodpovìdìt pár otázek.}
{115}{}{Sbohem.}
{116}{}{Bude tì to stát $50.}
{117}{}{Prostì mì uzdrav.}
{118}{}{Já tu nestojím.}
{119}{}{Dìláš líp.}
{120}{}{Já jít.}
{121}{}{Kuš. Nikdy neertuju. Radši tu nohu uøíznu døív, ne se do rány dostane snì.}
{122}{}{V ádném pøípadì se nebude nic øezat, rozumíš?}
{123}{}{A je to, odcházím.}
{124}{}{Dobrá, ale jestli to zaène hnisat, tak mì potom neobviòuj.}
{125}{}{Já nedìlám zadarmo. Budeš muset zaplatit, ne pro tebe nìco udìlám.}
{126}{}{Tak co pro tebe mohu udìlat?}
{127}{}{Støílej.}
{128}{}{Vault 13?}
{129}{}{Víš, kde najdu Vault 13?}
{130}{}{Prı na tom pan Westin není dobøe. Je to pravda? Bojím se, aby se mu nìco nestalo. dluí mi peníze.}
{131}{}{Kamarád Slaneèek tvrdí, e jsi mu ukradl mapu. Co s tím udìláme?}
{132}{}{Hledám práci. Nevíš o nìjaké?}
{133}{}{Doktore, nevíš nìco o skupinì, která bojovala s tìmi otrokáøi?}
{134}{}{Nemusíš se bát, synku. Dokud nemá dokonèenı svùj systém, pravdìpodobnì nás nechá bıt.}
{135}{}{Hmm, to je dobré vìdìt. Chci vìdìt ještì nìco.}
{136}{}{Díky doktore.}
{137}{}{Ten starı opilec. Jediná vìc, kterou jsem od nìj mám je obraz mé "Velvet Elvii" - místo dluhu.}
{138}{}{Velvet Elvii? Mohu to vidìt?}
{139}{}{To není mapa, he? Dobrá, rád bych se zeptal ne nìco jiného.}
{140}{}{Dobrá, mohu jít na to.}
{141}{}{Neslyšel jsem o tom ani slovo, dokud se tu neobjevil starı Slaneèek. S úpalem. Leel v horeèkách tøi dny a celou dobu blouznil o tom, jak našel Vaul 13, jeho rodné místo.}
{142}{}{Rodné místo?}
{143}{}{Tak kde to je?}
{144}{}{Kde kryt?}
{145}{}{To nemùu øíct. Slaneèek poøád tvrdil, e má mapu, ale nikdo ji nikdy nevidìl.}
{146}{}{Slaneèek?}
{147}{}{Ptej se víc.}
{148}{}{Dobrá, je to víc, ne jsem mìl pøedtím.}
{149}{}{Velikán. Døíve to byl hledaè uranu. Teï je z nìj starı opilec. Momentálnì ije u Westina.}
{150}{}{Další otázka...}
{151}{}{Díky za ten pøíbìh.}
#CMH changing per Fergus.. Now you have to pay 1000 or steal the painting off of him.
{152}{}{Dobrá, opravdu jsem doufal, e za to dostanu nìjaké prašule. Pøenechám ti to za $}
{153}{}{Moná pozdìji, ještì otázku...}
{154}{}{Snad pozdìji, teï musím jít.}
{155}{}{Slaneèek byl døíve hledaèem uranu. Teï je to starı opilec. Momentálnì ho najdeš nìkde u Westina.}
{156}{}{Další otázka...}
{157}{}{Díky za ten pøíbìh.}
{158}{}{Nejlíp udìláš, kdy si promluvíš s prezidentkou Tandi. Slyšel jsem, e hledá nìkoho speciálního.}
{159}{}{Další otázka...}
{160}{}{Díky.}
{161}{}{Mohu... Je tu skupinka, která brojí proti otrokáøùm - taky proti spoustì dalších. Nìkdy jsou k vidìní za velkım obchodem, opravují .}
{162}{}{Další otázka...}
{163}{}{Díky.}
{164}{}{Hej, dej od toho pracky pryè, smrade !}
{165}{}{Opatrnì! I nepatrné mnoství je nebezpeèné.}
{166}{}{Dej to zpátky! Mohl by sis s tím ublíit.}
{167}{}{Ty léky jsou pro pana Westina, ne pro tebe. Dej je zpátky.}
{168}{}{Bì od toho. Musíš bıt opatrnı. Nechci, aby pan Westin dostal vadné léky.}
{169}{}{Hlídej to! právì jsem odmìøil dávku pro pana Westina}

{170}{}{Jsem doktor Jubilee. Co se dìje, dìvèe?}
{171}{}{Co se dìje, dìvèe?}
{172}{}{Tady to je, dìvenko.}
{173}{}{Nemusíš se bát. Dokud nedá dohromady svùj systém, pravdìpodobnì nás nechá v klidu.}
{174}{}{Jistì. Tady je $}
{175}{}{Dìkuju, zkoušel jsem dostat peníze ze Slaneèka, ale on nikdy ádné nemá.}
{176}{}{.}
