#tento soubor prelozil MAG2
#
{100}{}{Ty obludy pøišly ze severovýchodu. Nemìl by být problém je stopovat zpátky do jejich brlohu (únikový rastr na severovýchodì)}
{101}{}{Hmm, to je pìkná nuda. Doufám, že se nìco stane.}
{102}{}{To je hodin...}
{103}{}{Hmmm, pìkná nuda.}
{104}{}{Zzzz...Zzz... huhh, co...?}

{105}{}{Podívejme - èlovìk. Hlídá brahmíny.}
{106}{}{Gruthar øekl, že v takovém pøípadì máme odejít. Lidem nesmíme ubližovat.}

{107}{}{Podívej. Tam.}
{108}{}{. Jdeme.}

{109}{}{To je divné. Oni øíkat zlé vìci?}
{110}{}{Mluvící deathclawové? To je neuvìøitelné...}
