#tento soubor prelozil MAG2
#
{100}{}{Kdo je ten pøitloustlý plešatý chlap, co leští sklenice?}
{101}{}{To je barman.}
{102}{}{Je to tvrïák s pøeraženým nosem a rozpláclýma ušima, jako by to snad byl bývalý vysloužilý boxer.}
{103}{}{Co ti mohu nabídnout?}
{104}{}{Povìz to jsi ty, co pomohl Jackovi, že jo? Skvìlá práce. Tak èímpak posloužím?}
{105}{}{Jistì.}
{106}{}{Nìco k pití.}
{107}{}{Kdo je tamhleten velký chlapík?}
{108}{}{Co se dá dìlat v tomhle mìstì?}
{109}{}{Sbohem.}
{110}{}{To je Hoss, hoch prezidentky Tandi. Jsou s ním problémy, když se napije, tak bych se radši být tebou držel od nìj dál.}
{111}{}{To byl Hoss, syn prezidentky Tandi. Dobøe jsi mu natrhl prdel, hochu!}
{112}{}{Prezidentky Tandi?}
{113}{}{Tvrïák jo, eh? Dík.}
{114}{}{Nic moc. Jestli hledáš problémy, najdi si jiné místo k pití, tøeba jdi do "Nevydìlaný kùže". Jestli sháníš práci, tak od se ptej po Westinovi na západì mìsta. Také jsem slyšel, že prezidentka Tandi hledá odborníka.}
{115}{}{Odborníka?}
{116}{}{Prezidentka Tandi?}
{117}{}{Díky.}
{118}{}{Dcera prezidenta Aradeshe, toho který založil NCR. Je prezidentkou už dlouhá léta. A dìlá to dobøe.}
{119}{}{A ona hledá odborníka? Jakého?}
{120}{}{Kdo je ten velký chlap?}
{121}{}{Dík.}
{122}{}{Nevím. Gunther, její poboèník, ti toho snad poví více. Je na jihu mìsta v Kongresu.}
{123}{}{Kdo je ten velký chlap?}
{124}{}{Dík}
{125}{}{Dáš si nìco k pití?}
{126}{}{Samozøejmì.}
{127}{}{Ne.}
{128}{}{Máš u mì panáka. Chtìl jsem ho vypleskat už pìknì dlouho!}
{129}{}{Mám pár otázek.}
{130}{}{Dobøe! Èao.}
