#tento soubor prelozil MAG2
#
{100}{}{Vidíš rudolícího, pøátelsky vypadajícího mue.}
{101}{}{Tohle je Duppo. Pracuje ve Stockmenovì asociaci.}
{102}{}{Je zavalitı, pøátelskı se naducanım oblièejem a jemnımi svìtlımi vlasy.  Má prunou chùzi.}
{103}{}{Zdravím tì, cizinèe. Ty nejsi odsud, myslím tím, e nejsi ranèer, e? Pøicházíš si najít práci nebo tu chceš nìco nakoupit? }
{104}{}{Co to bude, cizinèe?}
{105}{}{Práci.}
{106}{}{Nakoupit.}
{107}{}{Dobrá, jmenuji se Duppo. Nabízím zde produkty z ranèe a nabízím i práci. Abych øekl pravdu, nevypadáš na honáka. Jak ti to jde s pistolema? }
{108}{}{Poøád hledám pár stránıch, jestli máš zájem. Umíš to se zbranìmi?}
{109}{}{Heh. Zabít umìt.}
{110}{}{Myslím, e dobøe.}
{111}{}{Nejsem pro násilí.}
{112}{}{Dobrá tady je mùj sklad. Prošmejdi si všechny stoly a podívej se co mám. Jestli se ti nìco nelíbí, nastav zadek Busterovi a tì mùe vykopnout. Samo, e tì nejdøív obere.}
{113}{}{Hmm, dobøe, snad umíš. Hledám honáky pro zahnání brahmín do Reddingu. Platím $2000 mínus všechny ztráty, které cestou utrpíme. Jestli máš zájem, buï zítra u brány k Westinovi. Jestli tam nebudeš, jedem bez tebe. Platí? }
{114}{}{Budu tam.}
{115}{}{Ne, nezajímá mì to.}
{116}{}{Zní to hezky.}
{117}{}{Hmh, nechci jet do Reddingu.}
{118}{}{Dobøe, ale pak tady pro tebe není práce. Venek je drsnı. Není tam místo pro mìkkoty, cizinèe.}
{119}{}{Ještì nìco?}
{120}{}{Bezva. Ještì nìco, cizinèe?}
{121}{}{Nakoupit.}
{122}{}{Práci.}
{123}{}{Wes-tin?}
{124}{}{Hledám Rogera Westina. Slyšel jsi o nìm nìco?}
{125}{}{Kde najdu Franka Carlsona?}
{126}{}{Carl-son?}
{127}{}{Sbohem.}
{128}{}{Myslíš Rogera Westona? V západní èásti mìsta.}
{129}{}{Jeden z podílníku tady. Na západì mìsta. Myslím, e nehledá vıpomoc na ranèi, jestli je to ten dùvod, proè s ním chceš mluvit. }
{130}{}{Je viceprezidentem; to je všechno, co vím. Víc ti opravdu nemohu øíct. Tráví všechen svùj èas v Prezidentském domì. Témìø nevychází, zvláš po všech tìch problémech tady. }
{131}{}{Carlson. Velkı šéf. Bydlí ve velkém domì. To je vše.}
{132}{}{Sorry - honácká sezóna skonèila. Pøijï za pár mìsícù.}

{133}{}{Hmm, hmm...je nìjaká jiná monost, jak tu ve mìstì pøijít rychle k prachùm?}
{134}{}{Byla by tu jedna monost. Ale musím øíct, e úøady by nebyly rády, kdyby se to dozvìdìly.}
{135}{}{Dobrá, klidnì zaplatím za pár informací.}
{136}{}{Aha, hmmm - kolik konkrétnì?}
{137}{}{Co takhle 500?}
{138}{}{Co takhle 300?}
{139}{}{Co takhle 200?}
{140}{}{Co takhle 100?}
{141}{}{Dobrá, nevíš to ode mne, ale heslo pro zadní vchod je GANG PROBLEM LIMB.}
{142}{}{Hmm... to není zrovna lákavá nabídka.}
{143}{}{Hmmm.. nesmíš zapomenout, e mám deset dìtí.}
{144}{}{Hmmm.. no, ena bude chtít novı koich.}
{145}{}{Hmmm.. chtìlo by to krapet víc..}
{146}{}{Ach, málo financí v tuhle dobu?}
{147}{}{Urèitì.}
{148}{}{No tak, pryè s lakomostí.}
{149}{}{U jsi blízko.}
{150}{}{Hele, potøebuju nìjakou motivaci.}
{151}{}{Pospìš, dokud se nikdo nedívá.}
{152}{}{Urèitì se nechceš zaplést se zákonem?}
{153}{}{U to je skoro ono, jen to ještì trochu pus.}
{154}{}{Je to v poøádku, ale jen krapet víc, slibuju.}

{155}{}{Jestli máš zájem, buï zítra u brány k Westinovi. Jestli tam nebudeš, jedem bez tebe, rozumíš?}
