#tento soubor prelozil MAG2
#
{100}{}{Vidíš pìknou mladou enu v bojovém úboru.}
{101}{}{To je Elise.}
{102}{}{Šíøí kolem sebe zvláštní atmosféru. Nìco jako by byla zvyklá rozkazovat a mìla radost z toho, kdy ji nìkdo poslechne.}
{103}{}{Co si pøeješ?}
{104}{}{Zase ty?}
{105}{}{Poslal mì Karl.}
{106}{}{Dr. Jubilee mi øekl, e si s tebou mám promluvit.}
{107}{}{Kdo jsi?}
{108}{}{Guh?}
{109}{}{Dávám dohromady jistou skupinu. Takovıch, co nenávidí otroctví. Øíkáme si New Californští Rangeøi.}
{110}{}{Dokáeš opravit moje auto?}
{111}{}{Uh - zdá se mi, e je to tady opuštìné.}
{112}{}{Ano? Øekl ti to?}
{113}{}{Nemnoho. e jsi fajn a mùu se na tebe spolehnout.}
{114}{}{Prı dobøe platíš.}
{115}{}{Já jsem Elise. Toto je Gond. Patøíme ke skupinì, která se snaí dìlat správné vìci.}
{116}{}{Nevypadáte jako charita nebo církev.}
{117}{}{To zní zajímavì. Kudy?}
{118}{}{Všechno co chci je mít v poøádku auto.}
{119}{}{Jen bì hezky odsud pryè. Saloon je zpátky po hlavní silnici.}
{120}{}{Nenávidíš otroctví, hmm. Zajímavé. Co udìláš, jestli dáš dohromady tu skupinu?}
{121}{}{Poádám je, aby se k nám pøipojili.}
{122}{}{Nakopu je do prdelí.}
{123}{}{Nic.}
{124}{}{To není nic pro tebe. Teï se kliï odtud.}
{125}{}{Skonèili jsme s obchodem s auty a doplòky. Máme zavøeno. Sbohem.}
{126}{}{Není. Sbohem.}
{127}{}{Dobrá, povídej. Co si myslíš o otrokáøích?}
{128}{}{Nenávidím je. Jsou hnusnı, odpornı sliz.}
{129}{}{Jestli mì nechají oni, nechám i já je.}
{130}{}{Nìkteøí z mıch nejlepších pøátel jsou otrokáøi.}
{131}{}{Prachy je vše, co tì zajímá?}
{132}{}{Jistì e ne. Vìøím v pravdu, zákon a boj proti utiskovatelùm.}
{133}{}{To je zaèátek - dokud nìkdo nenajde lepší dùvod proè bojovat.}
{134}{}{Co v tom ještì je?}
{135}{}{Nedìlej ze mì blbce. Dobøe vidím, co jsi zaè. Sbohem.}
{136}{}{Jestli nevíš, tak mì nezdruj. Sbohem.}
{137}{}{Ne, nejsme církevní organizace. Mohu se na nìco zeptat? }
{138}{}{Ne, jdi pryè.}
{139}{}{Ne tak rychle. Mùeš se pokusit pøipojit k Rangerùm.}
{140}{}{Dobrá. Dej mi vìdìt.}
{141}{}{Zkouška? Co to je - škola?}
{142}{}{Venku za mìstem je otrokáø. Moná u jsi to místo vidìl. Osvoboï otroky a pak se vra pøijï øíct, jak se ti vedlo.}
{143}{}{Ano, mohu to udìlat.}
{144}{}{V ádném pøípadì. Nechci mít problémy.}
{145}{}{Vıbornì, tohle je tvùj šastnı den.}
{146}{}{Je to urèitı zaitı názor, kterı umoòuje, aby zde existovala krutost otrokáøství. Promiò, ale není pro tebe v naší organizaci místo.}
{147}{}{Ok.}
{148}{}{Tak, co? Zmìnìn postoj? Chceš vyzkoušet své síly?}
{149}{}{Jistì.}
{150}{}{Co jsi to chtìl udìlat?}
{151}{}{Nemáš náhodou nìco udìlat? Nevracej se, dokud nedokonèíš svùj úkol.}
{152}{}{U jsem ty novinky slyšela. Otroci byli osvobozeni, hmmm. Dobrá práce. Tak tedy - vítej k Rangerùm?}
{153}{}{Ano.}
{154}{}{Ne.}
{155}{}{Slyšela jsem, e patøíš k tìm, kteøí osvobodili otroky pøed mìstem. Byla to správná vìc, a já bych ti ráda stiskla pravici.}
{156}{}{Díky.}
{157}{}{Je to prosté. Vìøíme v to, e otrokáøství je špatné a udìláme vše, abychom s ním bojovali. V NCR máme hodnì pøátel na vysokıch postech. Díky nim jsme zlikvidovali otroctví na jihu a teï se nám to doufám podaøí i na severu.}
{158}{}{Vypadá to, e Rangeøi jsou ti správní lidé, ke kterım se chci pøipojit. Napiš si mì.}
{159}{}{Zajímavé... budu pøemıšlet o tom, co jsi øekla.}
{160}{}{Pøísaháš, e budeš potírat otroctví kdekoli na svìtì a e budeš vdy pomáhat svım bratrùm Rangerùm kdykoliv budou potøebovat?}
{161}{}{Ano.}
{162}{}{Ne,}
{163}{}{Blahopøeji ti, nyní jsi Ranger.}
{164}{}{Vítej bratøe Rangere. V tuhle chvíli tu pro tebe není mnoho práce. Vìtšina našich lidí je venku na hlídce. Øeknu ostatním, e patøíš mezi z nás. Nechci, aby tì nìkdo z našich zastøelil.}
{165}{}{Kadopádnì, dobøí lidé, ochotní nám pomoci, jsou vdy vítáni. Jestli zmìníš názor, dej mi vìdìt. Opravdu nechceš vyuít monosti, se k nám teï pøipojit?}
{166}{}{Ne, opravdu ne.}
{167}{}{No, kdy o tom tak mluvíš... myslím, e chci bıt Rangerem.}
{168}{}{Aha. Zastupuji skupinu, která si øíká New Californští Rangeøi. Lidé s názory jako ty, se mohou zajímat o èlenství u nás. Máš zájem?}
{169}{}{Vıbornì! Zapiš mì.}
{170}{}{Zní to lákavì. Co mi mùeš øíct o Rangerech ?}
{171}{}{Aha. Fajn, dík za tvùj èas, ale myslím, e v tuhle chvíli si nemáme co víc øíct. Jestli zmìníš názor, vra se a navštiv mì.}
{172}{}{Ok.}
{173}{}{V tom pøípadì odejdi. Hned!}
{174}{}{Ok.}
{175}{}{Otrokáø! Rychle zmiz, døív ne ti pistolí vystøílím do tìla tetování!}
{176}{}{Jistì.}
{177}{}{Jen to zkus!}

{178}{}{Máme pár agentù a pøátel v pár mìstech na severu. Rozšiøujeme naše názory a bijem otrokáøe kdekoliv to jen trochu jde.}
{179}{}{Vítej zpátky. Chceš se k nám tedy pøipojit?}
{180}{}{Nikdy.}


{181}{}{To ti nepøísluší. Nyní odejdi, nebo ti ublíím.}
{182}{}{Nevím, co máš Gondem, ale teï za to zaplatíš!}
