#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Vidíš nápadnou enu v dlouhé róbì.}
{101}{}{To je Osvícená.}
{102}{}{Její strnulı pohled vırazu témìø šíleného by mohl vzbuzovat strach, kdyby nebyla tak klidná.}
{103}{}{Buïi pozdraven. Patøíš mezi Osvícené?}
{104}{}{<Nadšení, témìø šílené>}
{105}{}{Jistì, proè ne?}
{106}{}{Já jsem Vyvolenı.}
{107}{}{Uh, opravdu nevím, proè s tebou hovoøím.}
{108}{}{Merk chce poškrábat, co ho svrbí!}
{109}{}{Ano.}
{110}{}{Ne.}
{111}{}{Nech mne bıt.}
{112}{}{Haló? Je tu nìkdo?}
{113}{}{Guh.}
{114}{}{Nikdo tu není.}
{115}{}{Och, První Stupeò. Stále se utápíš v tom primitivním stavu. Snad by zeta-scan mohl napomoci. Chceš to zkusit?}
{116}{}{Ze-ta!}
{117}{}{Ne!}
{118}{}{Prosím, nezesmìšòuj církev Hubologistù. Je sklièující, kdy nám lidé jako ty dìlají takové vìci. Ach. Jsem teï celá pobouøená!}
{119}{}{Vyvolenı? Nemyslíš snad AHS-1? Odkud máš tento název?}
{120}{}{To je snadné. Jsem Vyvolenı, protoe to tak prostì musí bıt.}
{121}{}{AHS-1?}
{122}{}{Starší mého kmene mi tak øíká.}
{123}{}{O èem to mluvíš?}
{124}{}{Nedostaneme se a k tomu, e mne budete kropit svìcenou vodou èi tak nìco?}
{125}{}{Och. Hledáš opravdové porozumìní a vnitøní mír? Mohu ti pomoci.}
{126}{}{Ne, já hledám GECK.}
{127}{}{Pomoc? Jak?}
{128}{}{Jedinı vnitøní mír kterı potøebuji, mi poskytuje raketomet, dámo.}
{129}{}{"Porozumíš" tomuhle!? (drzé gesto rukou se vztyèenım prostøedníkem)}
{130}{}{Merk? Co ten chce?}
{131}{}{Snadné. Chce tvoji smrt. Øekni sbohem.}
{132}{}{Nevím co spolu máte, ale pro mne jsi jen další zakázka.}
{133}{}{Podivuhodné, bratøe. A na jakém jsi Stupni?}
{134}{}{Já se ptala první.}
{135}{}{Na jakém jsi Stupni?}
{136}{}{Och. Mìla jsem za to, e vidíš moji auru. Omlouvám se.}
{137}{}{Och. Mìla jsem za to, e vidíš moji auru. Omlouvám se.}
{138}{}{ }
{139}{}{Proè? Já jsem samozøejmì v Dokonalosti.}
{140}{}{Ehhh...není to opravdu nezdvoøilé, mluvit o Stupních?}
{141}{}{Pøísahám! Nemám ani páru èeho chtìjí dosáhnout tím, e se obklopí snùškou tìch vástù!}
{142}{}{Ach, takové nadšení. Pojï se mnou.}
{143}{}{"Ztraceni jsou ti, kdo nevyhledávají Smysl." Jestlie si to nìkdy rozmyslíš, vdy tì tu rádi uvítáme.}
{144}{}{Nekøiè! Právì si autorizuji neurodyny!}
{145}{}{Tedy pøedurèení? A co svobodná vùle? V tvé víøe, nemá nic co udìláš ádnı vıznam, protoe je vše u dopøedu rozhodnuto. Jsi jako šachová figurka ve høe.}
{146}{}{Nerozumíš mi. Pouze mùj potenciál jakoto Vyvoleného je pøedurèen. Ale moje rozhodnutí a mé èiny, urèují naplnìní tohoto potenciálu.}
{147}{}{Ovšem, vesmír je deterministickı! Konec koncù, byli jsme sem všichni zasazeni pro nìjakı úèel, kterıto je našemu stvoøiteli pøedem znám.}
{148}{}{Nesmysl. Není ádná organizující síla, pøedurèující naše osudy. Není ádná "vyšší moc," postavená nad námi. Vesmír je jen náhoda. Jsem Vyvolenı, protoe to jiní prostì rozhodli. To je celé.}
{149}{}{Autorizovanı Hledaè Smyslu. Ty zøejmì nebudeš Osvícenı.}
{150}{}{Primitivní víra - ale pøedvádí znaky velkıch slibù. Mùeme ti ukázat vyšší cesty. Chceš vìdìt víc?}
{151}{}{Ano.}
{152}{}{Ne.}
{153}{}{V tomto ti nemohu pomoci. Avšak, naši vìdci v San Francisku by mohli. Snad by bylo dobré, podívat se tam.}
{154}{}{Vypuzením své negativní psychické energie, se vyhneš tomu, e se dostaneš do tísnivého a depresivního stavu. A pouze pak mùeš bıt Osvícenı!}
{155}{}{Neurodyny jsou psychická místa tìla. Jsou naplnìna psi-energií lidí -  zneuctìnıch zbytkù lidí, zemøelıch ve válce. Tato psi-energie se do našich neurodynù otiskne pøi narození a drí nás v depresivním stavu. Autorizování ruší tyto otisky.}
{156}{}{Dokud je tvùj mozek ovlivòován negativní psychickou energií, tvùj pravı duševní potenciál je potlaèován. Horší však je, e deprese mohou tento potenciál úplnì rozmetat. Ledae by byla silná, velmi silná - vùle.}
{157}{}{Osvícení nastane, kdy jsou všechny tvé neurodyny autorizované. Teprve pak se mùeš stát AHS -Autorizovanım Hledaèem Smyslu- co je cílem všech Hubologistù.}
{158}{}{Neurodyny?}
{159}{}{Osvícenı?}
{160}{}{Depresivní stav?}
{161}{}{No a co je tohle proèišování zaè? Bolí to?}
{162}{}{Není to bolestivé. Pouze podstoupíš zeta-scan. Mohu ti jeden provést hned teï, jestli chceš.}
{163}{}{Jistì.}
{164}{}{V ádném pøípadì!}
{165}{}{Chrám Hubologistù existuje proto, aby uvolnil lidstvo z okovù, které zadrují jejich plnı duševní potenciál.}
{166}{}{Jak to chcete udìlat?}
{167}{}{Aha, nìco jako "Nechat svoji duši jít," e ano?}
{168}{}{V nìèem takovém ti neumím poradit. Máš nìco jiného s èím ti mohu bıt nápomocna? Tøebas nìjaké Autorizování?}
{169}{}{Dobrá, tak aspoò to Autorizování.}
{170}{}{Potøebuji pár informací. Vault 13 - co o nìm víš?}
{171}{}{Co se tu zajímavého pøihodilo?}
{172}{}{Zapomeò na to. Nic ve zlém. To je vše.}
{173}{}{ }
{174}{}{Ano!}
{175}{}{ }


{176}{}{Dokonalost? Opravdu? Jak mùete oèekávat, e budu venku roznášet vaši víru, kdy mnì tu odmítáte nejnovìjší poznatky vìdy!?}
{177}{}{(Pokraèovat)}
{178}{}{Myslím, e tu nìkdo spal pøi vysvìtlování základù, e? Hmmph - nejsi z Osvícenıch!}
{179}{}{Take ty tvrdíš, e existuje jakási vyšší moc, která nás stvoøila za nìjakım úèelem a pak nás opustí? Nemohu uvìøit, e by nìkdo mohl bıt tak otupìlı. Pojï, pøijmi víru chrámu Hubologistù. Nech nás, a ti ukáeme správnou cestu.}
{180}{}{Co je správná cesta?}
{181}{}{Ne díky.}
{182}{}{Bez monosti øízení vlastního ivota, co je pointou? Nic co udìláš, nemá ádnou cenu. Napøíklad - tvoje dnešní ranní probuzení. Byla to tvoje volba?  Ne, jsi jen loutkou vlastní filozofie. Nyní, my v chrámu Hubologistù, máme tu správnou odpovìï.}
{183}{}{A ta je?}
{184}{}{Jistì, udìlej to.}
{185}{}{Ach, jaká smutná a prázdná filozofie to je! I kdy, jestlie to je tak, chybí ti k vlastnímu rozvoji pouze cesta. To je jediná vìc, nad kterou nemáš kontrolu. Chrám Hubologistù ti mùe pomoci.}
{186}{}{Jak?}
{187}{}{Oh, jdi mi z oèí.}
{188}{}{Vault 13? Naši vìdci po nìm pátrali... nìkde na západì. To je vše co vím. Urèitì víš, e nechceš Autorizování?}
{189}{}{Jistì, proè ne.}
{190}{}{Ne díky. Je mi skvìle.}
{191}{}{Øeknu ti, e roznášení naší filozofie mezi lidmi je tìší, ne si vùbec dokáeš pøedstavit! AHS-9 právì nechápe tu obtínost zrovna nejlépe. No, mám to všechno sepsáno. Øekni, nemùeš prosím tuto zprávu doruèit AHS-9 v San Francisku? Nemohu ti slíbit ádnou odmìnu, ale vím jistì, e AHS-9 to ocení.}
{192}{}{Jistì, proè ne?}
{193}{}{Ne, promiò, ale nechci se do toho plést.}
{194}{}{Skvìlé. Zde máš tu zprávu. A teï - je nìco, co pro tebe mohu udìlat? Zeta-scan?}
{195}{}{Scan? Proè ne.}
{196}{}{To u ti musí staèit. Nashle.}
{197}{}{U jsme toho namluvili dost. Nashle.}
{198}{}{Jsem ráda, e se zase vidíme. V èem ti mùe bıt chrám Hubologistù nápomocen?}
{199}{}{<Nadšení, témìø šílené>}
{200}{}{Ty jsi to, co Merka svìdí!}
{201}{}{Uh, opravdu nevím o èem to mluvíš.}
{202}{}{Co se tu v tomhle chrámu dìlá?}
{203}{}{Ehm. Nesprávné dveøe.}
{204}{}{Má smrt nièemu neposlouí. Nejsem pro Merka hrozbou, prostì ho drádí moje víra. Doufám, e udìláš vyjímku a tuhle zakázku odmítneš.}
{205}{}{Hmm, opravdu se zdáš neškodná.}
{206}{}{Na to zapomeò. Jsi MRTVİ Hubologista.}
{207}{}{Na idioty nemám èas. Odejdi prosím.}
{208}{}{Ven, odpadlíku!}
{209}{}{Není nic, co mùeš øíci ke znovuzískání naší pøíznì, rouhaèi.}
{210}{}{Zavøi oèi. Ani trochu ti to neublíí.}
{211}{}{Skvìlé. Podaøilo se nám odstranit nìkolik špatnıch otiskù! Nyní jsi AHS-1. A teï, jestlie mì omluvíš, musím se zase chvíli vìnovat chrámu.}
{212}{}{Blahopøeji ti. U pro tebe nemohu udìlat více. Nyní musíš pokraèovat ve své cestì jakoto AHS-1.}
{213}{}{Chrám je zavøenı. Pøijdi zítra.}
{214}{}{Ráda bych ti pomohla, ale dokonce i AHS-4 musí spát. Pøijdi za denního svìtla.}
{215}{}{Nezvanı hoste! Chceš snad znesvìtit toto místo? Ven!}

{216}{}{Podivuhodné, sestro. A na jakém jsi Stupni?}
{217}{}{ }
{218}{}{Získáváš }
{219}{}{ zkušenostních bodù za zlikvidování Hubologisty pro Merka.}
