#tento soubor prelozil MAG2
#
{100}{}{Vidíš mue v koeném obleku.}
{101}{}{To je Felix, pøedák na farmì.}
{102}{}{ Dívá se pohledem studenım jako led a ve tváøi má ještì horší vıraz ne všichni ti ostatní tady kolem.}
{103}{}{Co pro tebe mohu udìlat, cizinèe?}
{104}{}{Zase ty?}
{105}{}{Hehg.}
{106}{}{Šerif mne sem poslal - øíkal toti, e by pro mì mohl mít pan Westin nìjakou práci.}
{107}{}{Chci vidìt šéfa.}
{108}{}{Hledám práci.}
{109}{}{Hledám Vault 13.}
{110}{}{Jen se tak koukám kolem.}
{111}{}{Vıbornì, další idiot. Budu hádat - chceš vidìt šéfa?}
{112}{}{Uh-heh.}
{113}{}{Neee.}
{114}{}{Fajn. Vejdi.}
{115}{}{Je pozdì. Pøijï ráno.}
{116}{}{Tak odsud vypadni.}
{117}{}{Dumont, jo? Dobrá, to mi staèí. Pan Westin je uvnitø.}
{118}{}{To je hezké, ale pan Westin nikoho nepøijímá. Máš nìco dùleitého?}
{119}{}{Hledám Vault 13.}
{120}{}{A co takhle kdy øeknu, e mì poslal Bishop z New Rena, a mám Westina zabít?}
{121}{}{Uh, ne.}
{122}{}{Ha! Další blázen. Zajdi si povykládat za Slaneèkem. Budete si rozumìt.}
{123}{}{Za kım?}
{124}{}{Nejsem zdejší.}
{125}{}{Slaneèek Bob - tamhle ve stájích. pan Westin ho tam poslal. A teï mì pøestaò otravovat.}
{126}{}{Och, díky.}
{127}{}{No tak to bych øek, e tì musíme zabít.}
{128}{}{Konec schùzky?}
{129}{}{Westin. Práce. Pro mì.}
{130}{}{Já jít.}
{131}{}{Dobøe, má pro tebe práci; Øeknu ti, co máš udìlat. Nìkdo, nebo nìco zabíjí bù-bùù. Ty jít se mnou. Ty hlídat. Hlídat bù-bùù. Udìlat šéf šastnı. Oukej?}
{132}{}{Okej.}
{133}{}{Ne. Mì ne zabít.}
{134}{}{Ještì jednou, udìláno? Práce hotovo?}
{135}{}{Ano.}
{136}{}{Ne.}
{137}{}{Jo, nechal tu pøíkaz. Oèekává tì.}
{138}{}{HEJ TY! Kliï se odsud!}
{139}{}{Okej.}
{140}{}{Jdi do hajzlu!}
#addons
{141}{}{Ano. Odkázal mne na tebe. Ohlednì tìch problémù s brahmínami.}
{142}{}{Ano. A jsem právì na odchodu.}
{143}{}{Správnì. Nìkdo, nebo nìco zabíjí brahmíny na západních pastvinách. Zavedu tì tam a budeš je hlídat. Jdeme.}
{144}{}{Tak na to zapomeò!}

{145}{}{Pan Westin tì oèekává.}
{146}{}{Ano, máme problémy s chátrou, ale slovní potyèky skonèily. Jestli chceš, mùeš vidìt pana Westina.}
{147}{}{Pøicházím za obchodem z Vault City.}

{500}{}{Dotkneš se tìch dveøí a draze za to zaplatíš. Tak co, frajírku?}
