#tento soubor prelozil MAG2
#
{100}{}{Vidíš nehezky vypadajícího, ale vkusnì obleèeného muže.}
{101}{}{To je místní recepèní.}
{102}{}{Na tom èlovìku není nic zajímavého. Vypadá jako typický zaèínající byrokrat.}
{103}{}{Vítej v Kongresu. Jak ti mohu pomoci?}
{104}{}{A hleïme, vítej znovu. Jak ti mohu pomoci tentokrát?}
{105}{}{A teï, co pro tebe mohu udìlat?}
{106}{}{Uhhh...}
{107}{}{Já vidìt Tandi?}
{108}{}{Já vidìt Tandi?}
{109}{}{Potøebuji vidìt prezidentku Tandi.}
{110}{}{Mùžeš mi pomoci najít Vault 13?}
{111}{}{Ne pokud nemáš GECK}
{112}{}{Mám pár dùležitých informací pro tvého šéfa.}
{113}{}{Potøebuji vidìt presidentku Tandi.}
{114}{}{Potøebuji vidìt presidentku Tandi.}
{115}{}{Hledám práci.}
{116}{}{Co je tohle za místo?}
{117}{}{To nemùžeš.}
{118}{}{Já jít pryè.}
{119}{}{Sorry, tohle nejsou nìjaké láznì. Bìž jinam.}
{120}{}{Ohlednì èeho?}
{121}{}{Hmmm... Proè chceš vidìt madam prezidentku?}
{122}{}{Èlovìk øíkat, Tandi najímat.}
{123}{}{Malé mìsto v poušti chce uzavøít pøátelství s Tandi.}
{124}{}{Prý vaše prezidentka shání nìjakého specialistu..}
{125}{}{Lidé z Vault 15 chtìjí uzavøít jistou dohodu.}
{126}{}{}
{127}{}{Jako tøeba?}
{128}{}{Nìkdo ji podrazil.}
{129}{}{To není tvoje vìc.}
{130}{}{To je sice hezké, ale tady není náborová kanceláø. Proè to nezkusíš ve mìstì, v centru?}
{131}{}{Toto je Kongres, tady se tvoøí zákony pro NCR.}
{132}{}{(Pokraèuje)}
{133}{}{13? Nebo máš na mysli 15?}
{134}{}{Øíkám 13.}
{135}{}{15?}
{136}{}{Ne.}
{137}{}{(Pokraèovat)}
{138}{}{Ach táák. Øekni to panu Guntherovi, vzadu.}
{139}{}{Vault 15? Chtìjí dohodu? Zajímavé. Tam vzadu - øekni to Guntherovi.}
{140}{}{Mùžeš si to vyøídit osobnì. Jen si promluv s Guntherem.}
{141}{}{To nezní dobøe. Nyní mì omluv, mám práci.}
{142}{}{Musím jí nìco øíct.}
{143}{}{Výbornì. Tak jí øekni, že má ve své kanceláøi špicla.}
{144}{}{Prostì jí øekni, že ji chci vidìt. Rozumíš?}
{145}{}{No dobrá, pak ti nemohu pomoci.}
{146}{}{(Pokraèovat)}
{147}{}{Och nic. Moje chyba. Øíkáš 13, opravdu? Hmm, ale o tom nic nevím.}
{148}{}{(Pokraèovat)}

{149}{}{Já vyøešit problém. Zabít zlý chlap. Chtít peníze.}
{150}{}{Øekni prezidentce, že problém s usedlíky je vyøešen.}
{151}{}{Darion je mrtvý? Oh, promiò. Jdi dál.}
{152}{}{Opravdu? Fajn, to je výborná zpráva. Víš ještì nìco?}
{153}{}{Ne}
{154}{}{Ano, ještì nìco - nìco o špiclovi.}
{155}{}{Co to pov- ...ehm, chci øíct - jsem rád, že s tím bude konec. Jdi dál.}

#messages for when the player is tampering with somthing he shouldn't
{500}{}{Omlouvám se, ale nemùžeš jít dál bez povolení.}
{501}{}{Malé doporuèení - pøestaò se do toho plést.}
{502}{}{Tohle je poslední varování - jdi nebo budeš mít problémy.}
{503}{}{Ochranka - prosím vyprovoïte našeho "hosta".}
