#tento soubor prelozil MAG2
#
{100}{}{Vidíš ženu ve zbrojní uniformì NCR.}
{101}{}{To je kapitán stráží.}
{102}{}{Je to sice žena, ale její puška øíká, že s ní není legrace.}
{103}{}{Budeš mì muset omluvit, jsem zaneprázdnìná žena. Nemám èas na vykecávání.}
{104}{}{Nestrkej nos, kam nemáš a budeme spolu dobøe vycházet, cizinèe.}
{105}{}{Máš otázky? Najdi šerifa Dumonta. Ten ti odpoví.}
{106}{}{Zákony jsou na vývìsce venku - žádné zbranì, žádný chlast, žádné problémy.}
{107}{}{Co pro tebe mohu udìlat, cizinèe?}
{108}{}{Zase ty?}
{109}{}{Já chtít dovnitø.}
{110}{}{Chci se dostat do NCR.}
{111}{}{Nic.}
{112}{}{Nemùžeš jít nikam, dokud neschováš zbranì.}
{113}{}{Všichni musí schovat zbranì.}
{114}{}{Hmm...dobrá. Neshledávám nic podezøelého. Jak se jmenuješ? Musím tì zapsat do knihy.}
{115}{}{}
{116}{}{No dobrá, brána bude otevøená za chvilku.}
{117}{}{Do toho ti nic není! Ihned odejdi, nebo budeš mít problémy.}
