#tento soubor prelozil MAG2
#
{100}{}{Je to velkı super mutant.}
{101}{}{To je Gond, super mutant.}
{102}{}{Je to velké, zelené a nevypadá svìtleji, ne má vypadat.}
{103}{}{Hej, øekla ti Elise, e tu máš bıt?}
{104}{}{Ty jsi Ranger, taky?}
{105}{}{Nemáš tu co pohledávat.}
{106}{}{Zdravím pøítele Rangera.}
{107}{}{Práce Rangerù nikdy nekonèí.}
{108}{}{Skvìlé. Naši bratøi Rangeøi dostali minulı tıden tábor otrokáøù.}
