#tento soubor prelozil MAG2
#
{100}{}{Vypadá jako oficír, má na sobì uniformu se znakem NCR.}
{101}{}{To je mìstský hlídaè.}
{102}{}{Podívejme - silný chlap, má zbraò, má znak, má brnìní - hmm, to mùže být stráž.}
{103}{}{Vítej do NCR. Jen pro tvoji informaci, jestli máš zbranì, nech je schované. Tohle není mìsto zbraní, cizinèe.}
{104}{}{Vítej do NCR, hlavního mìsta New California Republic, pod vládou prezidentky Tandi.}
{105}{}{Vítej cizinèe. Jdeš pracovat pro NCR, že ano?}
{106}{}{NCR tì vítá - snaž se nedìlat problémy.}
{107}{}{Hej ty, dej tu zbraò pryè! NCR nemá zájem o problémy jako je toto.}
{108}{}{Cizinèe, NCR má jistá pravidla a jedním z nich je "Žádné zbranì". Schovej je a nebudeš mít problémy.}
{109}{}{Èetl jsi co je psáno na tabuli? "Žádné zbranì," a myslíme to vážnì. Rozumíš?}
{110}{}{Vy tuláci jste všichni stejní. Tohle je mírumilovné mìsto - to znamená, že nepotøebujeme, abys tady støílel. Schovej zbranì a nebudeš mít žádný problém.}
{111}{}{Brána je v noci uzavøená. Jestli máš nìco urgentního, bìž na strážnici.}
{112}{}{Musíš promluvit s kapitánem, jestli chceš projít pøes bránu.}
{113}{}{Trochu pozdì na návštìvu mìsta. Jdi za kapitánem; možná tì pustí dál.}
{114}{}{Být tebou tak se radši otoèím a rychle upaluju pryè.}
{115}{}{O tebe a tvé zpùsoby nemáme v NCR zájem.}
{116}{}{Ještì krok a budeš toho litovat.}
{117}{}{Varovali jsme tì, tak v míru odejdi. Rozumíš?}
