#tento soubor prelozil MAG2
#
{100}{}{Vidíš brýlatého mladíka.}
{101}{}{To je Gunther, poboèník prezidentky Tandi. Alespoò je to tak napsáno na dveøích.}
{102}{}{Vypadá úøednì a zaneprázdnìnì, takový ten typ zavilého byrokrata, který nenávidí vše ostatní.}
{103}{}{Mohu nìjak pomoci?}
{104}{}{Zase ty?}
{105}{}{Uhhhh - práce. Práce Tandi.}
{106}{}{Kdo jsi?}
{107}{}{Jsem tady, protože chci požádat prezidentku Tandi o práci.}
{108}{}{Sorry, špatné dveøe.}
{109}{}{Chceš práci?}
{110}{}{Zkusme to znovu. Ty pomoci Tandi? Ty pracovat pro Tandi?}
{111}{}{Anoanoanoano!}
{112}{}{Tandi práce. Já chtít.}
{113}{}{A co umíš?}
{114}{}{Uhhhh...já zabiják, já velká dobrá zabiják!}
{115}{}{Uhhhh...já chytrý. Starší øíkat já mít mozek z dítì. Já mít 2 mozek. Já chytrý.}
{116}{}{Nemùžeš dostat práci pro prezidentku!}
{117}{}{Ne?}
{118}{}{Oh. Oukej.}
{119}{}{Ach... nevím úplnì pøesnì, koho hledá. No dobrá, øekla, že mám všechny poslat dál. 
Takže ty jít. Mluvit s Tandi teï.}
{120}{}{NE! Ty blb. Prezidentka muset být chytrá, mluvit ve víc slabika slovo! Ty ne prezidentka.}
{121}{}{Oh. Co já dìlat?}
{122}{}{Já nelíbit ty. Ty køièet. Špatná chlap.}
{123}{}{Jmenuji se Gunther, osobní asistent presidentky Tandi. A teï, co pro tebe mohu udìlat?}
{124}{}{Hledám Vault 13.}
{125}{}{Hledám GECK.}
{126}{}{Prý paní prezidentka potøebuje udìlat nìjakou zvláštní práci.}
{127}{}{Paní prezidentka neposkytuje další rozhovory na téma Vault 13. Je mi líto. Je pøíliš zamìstnaná na to, aby pøijímala všechny slídily, kteøí se tu objeví.}
{128}{}{Huh? Tomu nerozumím.}
{129}{}{A ohlednì GECK. Mìla by o nìm nìco vìdìt?}
{130}{}{Byla nìjaká øeè o práci.}
{131}{}{Jsi k nièemu. Odcházím.}
{132}{}{Pak ti doporuèuju pøeèíst si cedulku venku. A nyní ti pøeju dobrý den.}
{133}{}{Nechápu, o èem to mluvíš. Máš nìjakou opravdovou otázku?}
{134}{}{Hledám Vault 13.}
{135}{}{Prý má prezidentka nìjakou práci, kterou potøebuje zaøídit.}
{136}{}{Pak tedy nic.}
{137}{}{Ach ano. Mám pokyny pustit dál každého, kdo se na to zeptá. Mùžeš vejít. Jsou to dveøe po mé pravici.}
{138}{}{Paní prezidentka s tebou skonèila? Tak jak?}
{139}{}{Dobøe. Sbohem.}
{140}{}{Velmi dobøe. Nyní odcházím.}
{141}{}{Pøinášíš nìjaké nové zprávy ohlednì té záležitosti s Vault 15?}
{142}{}{Ano.}
{143}{}{Ne.}
{144}{}{No, je mi líto, ale paní prezidentka je velmi zaneprázdnìna. Proè nepøijdeš, až dokonèíš svoji práci?}
{145}{}{Oukej.}
{146}{}{Výbornì! Pustím tì dál.}
{147}{}{Ty bastarde! Stráže! Lupiè! Vrah!}
{148}{}{Jsi brzy zpátky! Co máš teï?}
{149}{}{Od-mì-na.}
{150}{}{Prezidentka øekla, že si mám øíct o odmìnu.}
{151}{}{Pra-chy.}
{152}{}{Jsem tady pro svoji odmìnu.}
{153}{}{Tvoje prezidentka øekla, že bys mìl vìdìt, že máš ve svém domì špióna - nìkdo zvaný Feargus.}
{154}{}{Nic.}
{155}{}{Samozøejmì, øekla mi o tom. Odmìna  $6000 a NCR ti dìkuje, øekla. A nyní mám práci. Sbohem.}
{156}{}{Podívejme se. Smlouva øíká $500. Tady jsou.}
{157}{}{Ve skuteènosti mi øekla, že mám zmìnit èástku - vypadá to, že dostaneš bonus. Tady je, $900 a NCR ti dìkuje. A teï mám práci, tak sbohem.}
{158}{}{Tvoje prezidentka øekla, že bys mìl vìdìt, že máš ve svém domì špióna - nìkdo, kdo si øíká Feargus.}
{159}{}{Sbohem.}
{160}{}{Feargus? Tomu nevìøím!}
{161}{}{Podívej se na tento disk.}
{162}{}{Cokoli. Odcházím.}
{163}{}{K èertu. Vypadá to vìrohodnì. Postaráme se o to. Tady je $4000 za informaci.}
{164}{}{Neberu krvavé peníze. Odcházím.}
{165}{}{Díky. Pøeju ti pìkný den.}
{166}{}{Oh, to jsi ty. Hele, tohle není vhodná doba. Ve skuteènosti si myslím, že paní prezidentka by byla radši, kdyby ses už do nièeho nepletl. Dìkuji ti a pøeju hezký den.}
{167}{}{Já mám èisté svìdomí. Prezidentka tì nepøijme - teï ani jindy. Zaplaceno máš. Teï prostì odejdi.}

{171}{}{Já jít.}
{172}{}{Absolutnì nic.}
{173}{}{Ty dìvko! Stráže! Lupiè. Vrah!}

{174}{}{Pøicházím z Vaultu 15 a musím o tom mluvit s tvým šéfem.}
{175}{}{Já muset øíct o Vault 15.}

{176}{}{Mìl bys vìdìt, že máš v domì špióna - jeho jméno zaèíná na F.}


#define GLOBAL Message response
{500}{}{Míváme dveøe zamèené.}
{501}{}{Musím tì požádat, abys odešel.}
{502}{}{Tohle je poslední varování. Odejdi døív, než tì nechám vyvést.}
{503}{}{Ochranka - vykopnìte toho otravu.}
