#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Svalnatý chlápek, s poøádným hrudním košem.}
{101}{}{To je Hal, velitel Brahmíních okruhù.}
{102}{}{Žvýká chuchvalec nìèeho neurèitého a ty doufáš, že to nevyplivne smìrem k tobì, protože to páchne až do nebes.}
{103}{}{Jsi zde kvùli okruhùm?}
{104}{}{}
{105}{}{Ano.}
{106}{}{Ne.}
{107}{}{Potøebuju nìkoho na cestu do Reddingu!!!}
{108}{}{No, potøebuju nìkoho na cestu do Reddingu!!}
{109}{}{Chci vìdìt, kteøí z vás potáhnou do Reddingu.}
{110}{}{Skvìlý. Tak se všichni nachystejte... a šnìrujte to na Redding hoši!}
{111}{}{Tak jo, a teï mne nech. Mám 500 brahmín, který musim zapøáhnout do vleku.}
{112}{}{Zase ty? Odejdi.}
{113}{}{No, to byli sráèi! Bojím se, že za tenhle okruh nikdo z nás žádný prachy nedostane. Mùžem bejt rádi, že sme zùstali naživu.}
{114}{}{Dobrá, ale ranèeøi z toho nejsou zrovna na vìtvi - je to jenom $1000 za okruh. To víš, je to drsný.}
{115}{}{No, táhlo se s náma trocha smùly, ale je to okej. Tady máš $2000 za pøidání se.}
{116}{}{Zatracenì, to bylo skvìlý! Tady máš $1000 navrch. To a k tomu $2000, dìlá dohromady tvùj plat. A Redding dneska zažije malý zemìtøesení!}
{117}{}{Jedeš zas na svým triko. Dobøe se nám s tebou cestovalo.}
