#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Vidíš chlápka s lesknoucí se pleší a brılemi s tlustımi skly.}
{101}{}{To je Dr. Henry}
{102}{}{Tenhle chlápek je tak mimo, a to bolí. Je to intelektuál, kterı si ije úplnì mimo reálnı svìt, to je vidìt.}
{103}{}{Jsem Dr. Henry a právì teï mám mnoho práce. Co potøebuješ?}
{104}{}{Zase ty? Co potøebuješ?}
{105}{}{Hurgh.}
{106}{}{Jsem}
{107}{}{Dost øeèí. Máš nìjaké papíry, po kterıch se shání pan Merk. Dej mi je a nikdo tu nebude zranìn.}
{108}{}{Neslyšel jsi nìkdy o místì zvaném Enkláva?}
{109}{}{Nic z tvé brane.}
{110}{}{Hmm, podprùmìrnı rùst lebeèní... mizivı intelektuální vıvoj... avšak ádné vìtší tìlesné mutace. Ne, oèividnì je to vrozené, obávám se. Pøeji dobrı den.}
{111}{}{Vyvolenı? Ovšem, to dává smysl. Zajímavé... obávám se, e ti však nemohu pomoci. Byl jsem zaøazen na cyber-genetickı vızkum, nikoli na Projekt zajištìní chodu Vaultù.}
{112}{}{O èem to mluvíš?}
{113}{}{Projekt zajištìní chodu Vaultù?}
{114}{}{Cyber-genetika? O nìèem podobném, nevím zhola nic.}
{115}{}{Bezvadnı. Jsi potrhlı jako všichni poustevníci. Nashle.}
{116}{}{Sakryš, u jsem ti toho øekl daleko víc, ne jsem smìl. Nevadí, kdyby se nìkdo ptal, nic jsem neøíkal.}
{117}{}{Nìco co se tıkalo extrémních sociologickıch podmínek. Avšak zdálo se mi to všechno jako jedna velká slátanina... nebyla v tom ádná opravdová vìda. Ale slyšel jsem nìco ohlednì 13, kdy jsem improvizoval bìhem jednoho svého experimentu. Šílená práce, mìl bych dodat.}
{118}{}{Bìhem experimentu? Jakı experiment?}
{119}{}{Co je to ta cyber-genetika?}
{120}{}{Oèekáváš snad, e ti nìèemu z toho uvìøím? Jsi cvok.}
{121}{}{Och, to jsou neprobádaná pole - velmi vzrušující. Právì teï pracuji na jednom projektu - úplnì zásadní pojetí problému mutantù. Podívej je to vlastnì docela jednoduché - mutace není trvalá a nemìnná. Je mono ji léèit.}
{122}{}{Ovšem, moji ponìkud prostoduší kolegové se ten problém snaili vyøešit tou nejjednodušší cestou. Oèista, však víš. Pøipouštím, e s tím byly hned od zaèátku potíe, ale mám je všechny vyøešeny... tedy, myslím.}
{123}{}{}
{124}{}{Pokraèovat}
{125}{}{Kdy tì tu tak vidím, myslím, e mi mùeš pomoci na poli testování. Máš zájem?}
{126}{}{Testování? Co tím myslíš?}
{127}{}{Nemáš šanci.}
{128}{}{Pøipravil jsem si malı vzorek séra, ale tento musí bıt vpraven do hostitele.}
{129}{}{Nenechám do sebe píchat ádné jehly!}
{130}{}{Tak? ...u tu nejsem.}
{131}{}{Ty? Ach, ne - sérum by nezabralo na nìkom s tak nízkım mutagením kvocientem. Lze ho pouít jedinì na super mutantech. Vpíchni sérum do super mutanta a pak se vra zpátky a nahlaš mi vısledek. Mám za to, e takové Broken Hills je jich plné.}
{132}{}{A co to udìlá?}
{133}{}{Co z toho budu mít?}
{134}{}{Tedy, mìlo by to zpùsobit zpìtnı pohyb v genetické matrici, jen vyústí v destabilizaci a pøizpùsobení zmutované DNA tak, e hostitel bude v koneèném dùsledku oné zmutované DNA zbaven. Ovšem, kdybych si tím byl úplnì jist, nebudu po tobì chtít to testovat.}
{135}{}{Co z toho budu mít?}
{136}{}{Zúèastníš se velmi dùleitého experimentu. A ve skuteènosti je nejdùleitìjší vìdecká - aha, ty máš na mysli peníze. Nue, mám Cyber-psa Mk. II, model pro Osobní ochranu. Domnívám se, e bych ho mohl uvést do stavu on-line, jakmile se vrátíš. Pøijímáš tuto nabídku?}
{137}{}{Cyber-psa? Jistì, proè ne.}
{138}{}{Jsi úplnì mimo. Naprostı blázen.}
{139}{}{Vynikající. Zde je to sérum, pøipravené v injekèní støíkaèce. Vše co musíš udìlat je, pouít ho na super mutanta a pøijít mi nahlásit vısledek. Bıt tebou, zajdu to zkusit do Broken Hills. Hodnì štìstí.}
{140}{}{Øekni tomu svému panu Merkovi, e má odpovìï zní stále stejnì. Nemám zájem se pøipojit k ádnému z jeho "riskantních podnikù." Díky a pìknı den.}
{141}{}{To nemá ádnı vıznam, nepøijdu zpátky. ádná z tvıch opìvovanıch prací nebyla øádnì dokonèena, tak se nedìlej mım pøítelem. Dìkuji mnohokrát!}
{142}{}{Dobrá, pak tedy nemáme o èem mluvit. Hezkı den.}
{143}{}{Tak co moje sérum? Bylo otestováno?}
{144}{}{Ano.}
{145}{}{Ne.}
{146}{}{Dobøe, a jestli proti tomu nic nemáš, chceš v tom pokraèovat? Já u nejsem ádnı mladík.}
{147}{}{No a... jak to funguje?}
{148}{}{Zabilo ho to! Øíkal jsi pøece, e to bude LÉÈIT mutanty!}
{149}{}{Je mrtvı, Jime.}
{150}{}{Tak to jsem si nerozumìli. Øíkal jsem pøece, e by to mìlo odtranit jejich zmutovanou èást. Hmm... zdá se, e celı proces byl pøíliš prudkı.  No, musím to ještì ponìkud doladit.}
{151}{}{A co moje odmìna?}
{152}{}{Jsi zrùda! Nechci s tebou mít u nic spoleèného.}
{153}{}{Koukám, e to má ještì nìjaké mouchy. Nue - zkoušet a zkoušet poøád znovu.}
{154}{}{A co moje odmìna?}
{155}{}{Jsi zrùda! Nechci s tebou mít u nic spoleèného.}
{156}{}{Ach samozøejmì. Cyberpes je tvùj. A teï, mám ještì spoustu práce.}
{157}{}{...take úroveò mutace se stabilizuje pøíliš rychle... - teï mne neobtìuj.}
{158}{}{Primitivní pøizpùsobení se okolnímu prostøedí. Fascinující.}
{159}{}{Nemáš oscilaèní kalibrátor? Ne, ovšem e ne.}
{160}{}{, Vyvolenı. Hledám Vault 13.}
{161}{}{Zdravíèko ty hajzlíku. Zatím ještì ve vší slušnosti - dej mi ty papíry nebo ti zaènu uráet prsty. Aspoò se podíváme, jak dobrı jsi doktor.}
{162}{}{Skvìlé, dám mu vìdìt.}
{163}{}{Eh... Ok, ty papíry jsou v mém psacím stole támhle. Vezmi si je; jenom nech mé prsty na pokoji. Ano?}
{164}{}{Polib mi prdel, kreténe! Stráe! Stráe!}
{165}{}{To bylo od tebe velice moudré. Pan Merk bude informován.}
{166}{}{Toho budeš litovat, doktùrku.}
{167}{}{Hej! Máš pøesnì deset vteøin na vrácení tìch papírù zpátky tam kde byly, ne zavolám stráe.}
{168}{}{Ty si nedáš pokoj, co? No co, teï nechám a si to s tebou vyøídí zákon. Stráe! Stráe!}
