#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Vidíš velkého, hloupì vypadajícího a až pøíliš svalnatého týpka.}
{101}{}{To je Hoss.}
{102}{}{Nevypadá to, že by byl vyzbrojen nìjakou zbraní èi dùvtipem.}
{103}{}{Hej ty... podivnej ksichte. Nemám tì rád. A mìl bys mi koupit nìco k pití.}
{104}{}{Hej kotì, pojï sem za mnou a dám ti nìco pìknýho, velkýho a vlhkýho.}
{105}{}{<Prd!>}
{106}{}{Škrábej mì.}
{107}{}{Nechci žádný problémy.}
{108}{}{Tak ty si chceš hrát na tvrïáka, jo? Tvojí prdelí vytøu celou místost, poèkej. Jedem na férovku, tady a teï.}
{109}{}{"Nechci žádný problémy!" Pche... máš to mít. Každýmu s kým jsem se rval, jsem názornì pøedvedl, jak praskají kosti. Jedem na férovku, tady a teï.}
{110}{}{Skvìlé, bude zábava.}
{111}{}{Ne opravdu, nechci.}
{112}{}{Pche! Co to je za fóry. Vypadni odsud, kašièko.}
{113}{}{Auu! Mám pøeražený nos! Dost už! Už mì nebij!}
{114}{}{Okej, omlouvám se. Byl to jen žertík. Už se mnou nebudeš mít žádné potíže...prosím, nezabíjej mne!}
{115}{}{Hele, já se stahuji. Okej? Necháš mne být?}
