#tento soubor prelozil MAG2
#
{100}{}{Vidíš bezdomovce.}
{101}{}{Vidíš Billa bezdomovce}
{102}{}{Vidíš muže støedních let v obnošených šatech.}
{103}{}{Promiò cizinèe, ale nemám èas na povídání s tebou.}
{104}{}{Proè ne?}
{105}{}{Ok, trhane.}
{106}{}{Okej, nashle.}
{107}{}{Poèkej chvilku. Proè se mnou nechceš mluvit?}
{108}{}{Jsme soukromá a velmi uzavøená spoleènost a nechceme mít problémy ani jakýkoliv kontakt s okolním svìtem. Prosím, nech nás být.}
{109}{}{Ok.}
{110}{}{Ahoj...a sbohem.}
{111}{}{Díky za všechno, co jsi pro nás udìlal.  Omlouvám se za to chladné uvítání.}
{112}{}{Polib si prdel!}
