#tento soubor prelozil MAG2
#
{100}{}{Vidíš mladého muže obleèeného v uniformì NCR policie}
{101}{}{To je Karl, zástupce mìsta.}
{102}{}{Vidíš mladík sotva odrostlého z puberty. Vypadá netrpìlivì.}
{103}{}{Vítej cizinèe. Jsem Karl a zastupuji mìsto. Co pro tebe mohu udìlat?}
{104}{}{Jako napøíklad?}
{105}{}{Uh...nugh..}
{106}{}{Jsem tu v NCR nováèek. Co mi mùžeš øíct o vašem mìstì?}
{107}{}{No, hledám Vault 13.}
{108}{}{Posílá mne prezidentka Tandi. Mám si promluvit s tvým vìznìm.}
{109}{}{Jmenuji se}
{110}{}{Hledám chlápka jménem Jack. Øíká se mu taky Whack Jack.}
{111}{}{Kde mohu najít Rogera Westina?}
{112}{}{Oukej, trochu jsme moc bumbali, co? Podívej se, tamhle je odemèená volná cela. Co takhle si tam lehnout a vyspat se z toho?}
{113}{}{Podívej se, dám ti radu - vem si své pøátele a hezky se z toho vyspìte. Pití na veøejnosti je tady trestný èin.}
{114}{}{Tohle je NCR, hlavní mìsto New California Republic. 3000 obyvatel a poèet stále roste. Žádní otroci, hazardní hry, drogy. Prezidentkou je paní Tandi, mùj šéf je šerif Dumont. Staèí to taková odpovìï?}
{115}{}{Jo, ale mám ještì pár otázek.}
{116}{}{Jo, to je vše.}
{117}{}{Ano stalo se to, když jsem byl malý. Dej mi vìdìt, jestli to najdeš!}
{118}{}{Jo, ale mám ještì pár otázek.}
{119}{}{Gee, díky.}
{120}{}{Jmenuje se Oswald. To je všechno, co jsme z nìj dostali. Pøedpokládáme, že je bezdomovec, z vaultu 15, ale... nejsem si jistý. Je trošku tvrdý. Víš co myslím?}
{121}{}{Tvrdý chlap, huh?}
{122}{}{Co s ním budeš dìlat?}
{123}{}{Už jsem o tobì slyšel, že? Jo - samé dobré vìci. Hele, slyšel jsem zvìsti, že chtìjí využít lidi, jako jsi ty. Jdi do obchodu s auty a ptej se po Elis. Øekni jí, že ji Karl pozdravuje.}
{124}{}{Práci? Asosiace Akcionáøù hledá strážce. Banditi zase podnikli útoky na dobytek. A taky jsem slyšel, že prezidentka hledá nìkoho schopného. Pomùže ti to?}
{125}{}{Jo, ale mám ještì pár otázek.}
{126}{}{Trochu. Díky}
{127}{}{Tohle je dùstojník Jack, cizinèe. Jeden z našich lidí. Ještì jsi nemluvil s Mirou, že ne?}
{128}{}{Ano.}
{129}{}{S kým? S Mirou?}
{130}{}{Ten hajzlík? Utáboøil se tady pøed mìstem. Bìž smìrem ke Stockmenovì asociaci.}
{131}{}{Moc se ti nelíbí.}
{132}{}{Jo, ale mám ještì pár otázek.}
{133}{}{Díky.}
{134}{}{Jo. Je opravdu zlý. Zabil dva z našich mužù a neøekl ani slovo.}
{135}{}{Nechte mì s ním chvíli o samotì. Snad ho pøesvìdèím, aby spolupracoval.}
{136}{}{Mohu ho teï vidìt?}
{137}{}{Povìsí ho bastarda, aspoò doufám. On a jeho banda zabili dva lidi. Nebude mì bolet, když ho uvidím viset.}
{138}{}{Mohu ho teï vidìt?}
{139}{}{Ona a Jack jsou manželé, však víš. Mìli mezi sebou divoké hádky. Nevìøil bych jí ani slovo, rozhodnì ne kdyby mluvila o Jackovi. 
Udìláš líp, když zùstaneš bokem. Jack je dobrý chlap, je teï jen kvùli tomu trochu nervózní.}
{140}{}{Oukej, pøejdìme na jiné téma.}
{141}{}{Dìkuji mnohokrát za radu, pane poslanèe.}
{142}{}{Je mimo, to je vše. Jestli není tady, mùže být v elektrárnì. Bývá tam s Dorothou.}
{143}{}{Dobrá, ale mám ještì pár otázek.}
{144}{}{Díky.}
{145}{}{To si piš. Všichni o nìm mluví, protože je poslanec, ale já ne. Myslí si o sobì, že je nìkdo, jako by pro nìho zákony neplatily. Byl bych rád, kdyby mu jednou spadl høebínek.}
{146}{}{Cizinèe, stalo se pár vìcí. Co mi k tomu øekneš?}
{147}{}{Musím jít. Prostì ven z mìsta, tak?}
{148}{}{Bez problémù. Dalších pìt minut nechci nic slyšet. Pojï za mnou.}
{149}{}{Jistì, pro dobrou vìc, proè ne.}
{150}{}{Ano, pøed pár lety byl nemocný a  doktor Jubilee mu dal nìjaké léky. Proè tì to vùbec zajímá?}
{151}{}{To nic, jen tak. Už tì nebudu zdržovat.}
{152}{}{. Hledám nìjakou poøádnou práci.}
