#tento soubor prelozil MAG2
#
{100}{}{Mutant - a jeden z tìch krotkıch.}
{101}{}{To je Lenny, vzpomínáš si? Ten otrapa.}
{102}{}{Hoo-hochu - to je tìká práce. Mimo skuteènost, e je zelenı a škaredı, má na sobì víc jizev ne stará kurva. Tenhleten je bojovník, o tom ádná.}
{103}{}{Já jsem Lenny a ty tu kalíš vodu. Kliï se odtud.}
{104}{}{Proè zlobíš Lennyho, ty malı bílı èerve?}
{105}{}{Co chceš po Lennym, ubohı èlovíèku?}
{106}{}{Ještì chvilku do mì strkej a budeš mít pøíleitost osobnì vyøídit svımu
 stvoøiteli, e tì k nìmu poslal Lenny.}
{107}{}{Rád tì vidím. Jsem Lenny - a ty musíš bıt to hovno s mozkem. Ha, ha!}
{108}{}{Vyøiï svému mutantnímu pánovi, e se jmenuju Lenny, otroku.}
{109}{}{Hej, bratøe mutantíku, Lenny je zvìdavı, proè se tady zahazuješ s tím lidskım trusem?}
{110}{}{Lenny s nikım nemluv. Dìlá z mutantù své otroky.}
{111}{}{Lenny øíká, e ty a tvùj prdolízavı mutant Tom mùete táhnout do pekla.}
{112}{}{Dávej pozor. Lenny není krotkı mutant, tak jako ten, co jsi ho teï dostal.}
{113}{}{Hej, zpátky ty malá bílá kùe!}
{114}{}{Nechej mì bıt èlovìèe.}
{115}{}{Ztra se, zmetku.}
{116}{}{Copak se dìje? Potøebuješ pomoct zmìnit názor?}
{117}{}{Ty jsi tak hustı jako hromada uhlí, èlovíèku.}
