#tento soubor prelozil MAG2
#
{100}{}{Vidíš dobøe obleèeného, skvìle upraveného èlovìka, kterı se zámìrnì pohybuje velmi pomalu.}
{101}{}{To je Merk - øíká se mu tady v okolí Chlapák.}
{102}{}{Z tohohle chlápka pøímo vyzaøuje arogantní chlad. Nìco v tom smyslu
 e pro nìj nejsi víc, ne moucha rozmáznutá mezi prsty.}
{103}{}{Hej, vidìl jsem tì ve filmu! Pøicházíš nìco pøedvést, he?}
{104}{}{Co si myslíš, chceš mì takhle vyrušovat z klidu? Kliï se odtud.}
{105}{}{Bohuel, mám práci.}
{106}{}{Estli chceš mluvit o obchodu, najdeš mì v "Nevydìlanı kùi". Jinak mì neotravuj.}
{107}{}{Vidìl jsem tì na støíbrném plátnì, e jo? Máš zajímavı...ehmm...dispozice.}
{108}{}{Máš správnı vıraz v oèích. Stav se u "Nevydìlanı kùe" - vdycky bych mohl potøebovat nìkoho jako jsi ty.}
{109}{}{Do prdele, co to smrdí? Nìco právì vešlo do pokoje.}
{110}{}{Pøines mi další whisky - rychle, hned.}
{111}{}{Teï nemám èas.}
{112}{}{Jsem tady hostem. Pøestaò mì štvát.}
{113}{}{Hej bejby, vypadáš dobøe. Ten Carlson má stále lepší a lepší vkus.}
{114}{}{Neobchoduju tady.}
{115}{}{Neznám tì. Jsem ctihodnı obchodník.}
{116}{}{Tak jestli to není nic dùleitıho, jdi a nech mne bıt.}
{117}{}{Tak, rozhodla ses mì po tom všem navštívit, eh bejby?}
{118}{}{Nevím nic o nièem, pochop to.}
{119}{}{Hostinskımu se nebude zamlouvat, e otravuješ jeho hosty.}
{120}{}{Kurva, mají tady dobrej chlast.}
{121}{}{Jdi mi z cesty!}
{122}{}{Jestli chceš s nìkım mluvit, jdi si koupit nìjakého pøítele.}
{123}{}{Nedávám rady a nedìlám zmìny. Vodpal.}
{124}{}{Co to má k sakru bıt - myslíš, e jsem linka dùvìry?}
{125}{}{Jsem Merk. Copak chceš?}
{126}{}{Zase ty?}
{127}{}{Zdvoøilost pøedevším, nebo se ti zle povede.}
{128}{}{Oort.}
{129}{}{Hledám práci.}
{130}{}{Informované zdroje øíkají, e ty jsi ten správnı chlap, u kterého hledat práci - jestli mi rozumíš.}
{131}{}{Øíká se, e ty jsi ten, kdo mi šlohnul auto.}
{132}{}{Hledám nìjaké informace.}
{133}{}{Øíká se, e bys mohl vìdìt nìco o... øeknìme, zboí ztrácejícím se z aut.}
{134}{}{Zase ty? Tak co, je práce hotová?}
{135}{}{Glub.}
{136}{}{Ne.}
{137}{}{Mám pár otázek}
{138}{}{Hmm... sílu asi máš, jinak tupounek... Jestli chceš práci, promluv si s Mirou. Rozumíš? Mi-rou. A teï táhni.}
{139}{}{Co to tu kòourá? Bude nìkdo tak laskav a vykopne odsud tohle brahmíní hovno?}
{140}{}{Jsi aspoò trochu normální? Myslíš, e budu najímat jen tak kadıho? Napøed pro mì pracuj a uka, e za nìco stojíš.}
{141}{}{Co takhle, kdy teï zastøelím Lennyho? Zaslouí si to.}
{142}{}{Vyzkoušíš si mne?}
{143}{}{Nevíš o nìkom, kdo má nìjakı Jet, he?}
{144}{}{Poslyš, jsem} //258
{145}{}{Hmmm, nìco jako e se ti mám napøed pøedvést, co? Zapomeò na to, slimáku.}
{146}{}{Byl to ten zatracenej Doofus, e jo? Ten mròavej skrèek moc vaní. Nìco ti øeknu - sejmi ho pro mnì -- nazvìme to tøebas laskavostí -- a pak se spolu mùeme dál bavit.}
{147}{}{Domluveno.}
{148}{}{Whoa - já nejsem tak chladnokrevnej!}
{149}{}{A oni by øekli, e jsi velké hovno. Hoši-}
{150}{}{Zajímavé. A teï kdo by nìco takového tvrdil?}
{151}{}{Neser mì tlusochu. Jestli nedostanu zpátky to co mi patøí, tak by ti mìl nìkdo poøídit rubáš do rakve.}
{152}{}{Dost. Odpovíš mi na otázku nebo ne?}
{153}{}{Oh, je to jenom nìco co jsem zaslechl. Jen jsem chtìl vìdìt, co na to øekneš.}
{154}{}{Øeknìme, e nic nevím. Co o tom víš?}
{155}{}{Teï, kdyby èlovìku pár vìcí chybìlo, myslíš, e by si je mohl koupit zpìt?}
{156}{}{Chci své vìci zpátky, tlustoprde!}
{157}{}{Co takhle kdy si pokecám s policií?}
{158}{}{U mì to unavuje. Hoši - postarejte se o hosta.}
{159}{}{Nemyslím si, e by se to Lennymu líbilo.}
{160}{}{Asi ne, ale já se ho nebudu ptát.}
{161}{}{A je teda po tvım.}
{162}{}{Tak mám dojem, e tu je kolem nìjak moc tupıch hlav. Asi je èas na "jeden proti jednomu" tady ve sklepì.  Lenny pojï sem, chci se podívat, jak tu sejmeš}
{163}{}{No, mám problémy, které musím vyøešit...}
{164}{}{Jako tøeba?}
{165}{}{Jet? Nabízíš mi nìco...?}
{166}{}{Mùj pøítel tady ví, jak to zaøídit. Zajímá tì to?}
{167}{}{Nìco nezákonného? Ne, to neudìlám.}
{168}{}{Zajímavé. Nabízím za jeho sluby $1000 - stále.}
{169}{}{Dohodnuto.}
{170}{}{Ne, to nemohu pøíteli udìlat.}
{171}{}{Hele, mùeme udìlat obchod, kamaráde. Tady je úkol - ve mìstì je vìdec - Dr. Henry. Má nìjaké dokumenty, které by se mi hodily. Zaplatím za nì $1000.  Jo, a nechci, aby se Henrymu nìco stalo. Je uiteènı ivı. Máš zájem? }
{172}{}{Jdu na to.}
{173}{}{Nee, to není mùj styl.}
{174}{}{Vìdomosti jsou drahé. Mám pravdu?}
{175}{}{"Cena moudrosti, je nadevše."}
{176}{}{Tady je $50.}
{177}{}{Zapomeò na to.}
{178}{}{Oh, ty jsi osobnost.}
{179}{}{Pokraèovat}
{180}{}{Dobrá, co se mne tıèe, jsi jen hromada hnoje.}
{181}{}{To sem si moh myslet, e jsi pøiposranej strachy.}
{182}{}{Oukej. ádnı problém. Nechci problémy. A víš co? Nechám dokonce svı hochy, aby vrátili to zboí tam, kde ho našli.}
{183}{}{A to je v poøádku, nebo se vrátím.}
{184}{}{Nezkoušej na mnì tyhle voloviny!}
{185}{}{Ten hoch by toho mìl bıt schopnı.}
{186}{}{A teï doporuèuju, abys šel.}
{187}{}{V kadém pøípadì, zavolej policii. Ovšem, pøedpokládám, e máš dùkaz pro svoje zmatená tvrzení.}
{188}{}{Ano, jistì.}
{189}{}{Nevadí.}
{190}{}{Jako tøeba Hubologista co je tady ve mìstì. Dìsnì mì to ere. A ten svrab znièíš, vra se sem.}
{191}{}{Okej. Udìlám ti deratizéra... kdo je to Hubologista a kde ho najdu?}
{192}{}{Jak odvánì mluvíš, vzhledem ke svım skuteènım myšlenkám!}
{193}{}{Sorry, ale nenechám se zatáhnout do církevních svárù.}
{194}{}{Jsem vzdìlanı mu. Na co se chceš zeptat?}
{195}{}{Ptej se.}
{196}{}{Hledám Vault 13.}
{197}{}{Slyšel jsi o GECKu?}
{198}{}{Co víš o lidech, kteøí si øíkají Rangeøi?}
{199}{}{Co víš o èlovìku jménem Westin?}
{200}{}{Sbírám informace o viceprezidentu Carlsonovi.}
{201}{}{To je vše.}
{202}{}{Hele, zaplacenej byl jenom jeden dotaz. Další stojí dalších $50.}
{203}{}{OK, tady.}
{204}{}{Vím vše, co jsem potøeboval.}
{205}{}{To je náhoda, mám mapu k Vaultu 13. Stojí pouhıch 1000 babek. Máš zájem?}
{206}{}{Jistì. Vezmu si ji.}
{207}{}{To urèitì. A co Karlštejn, ten náhodou neprodáváš?}
{208}{}{Moná pozdìji.}
{209}{}{To je nìjaká droga z New Reno? Nikdy jsem o tom neslyšel.}
{210}{}{Nee. Ještì mám další otázky.}
{211}{}{To je vše, co jsem potøeboval vìdìt.}
{212}{}{Ti bastardi? A se mi klidí z cesty, nebo je zpøeráím.}
{213}{}{Hmm, to bylo zajímavé. Další otázka.}
{214}{}{To je vše.}
{215}{}{Ranèeøi, eh? Jednou sem pøišli, nìco kvákali. Mìstskı doktor se hnal s nìjakıma lékama - zdá se, e Westin má potíe se srdcem. Zhatilo nám to kšefty po zbytek noci.}
{216}{}{Dík za informaci. Mám další otázku.}
{217}{}{Nic víc u nepotøebuji.}
{218}{}{Jako dobrı obèan, fandím Carlsonovì opozici proti vlivu New Reno. Teï, kdy je Westin mrtev, budu pomáhat viceprezidentu s bezpeèností.}
{219}{}{Oh, nikdy bych nevìøil, e toho mue nìkdy potkám. Hodnì jsem o nìm slyšel.}
{220}{}{To je vše, nic dalšího u nepotøebuji.}
{221}{}{Vše?}
{222}{}{Ne, ještì mám pár otázek}
{223}{}{Jo, prozatím vše.}
{224}{}{Heh, tam se zkoušelo dostat chlapù. Vault 13 je tady prakticky modla. Dokonce tu postavili sochu nìjakému maníkovi, kterı pravdìpodobnì odtamtud pøišel. To je vše co vím.}
{225}{}{Pøece jsem ti prodal mapu. Zkus ji pouít, jo?}
{226}{}{Ta mapa není pravá? Sorry. Ten chlap pøísahal, e je. Jak jsem to mohl vìdìt? Nevím kde je Vault 13.}
{227}{}{Mám víc otázek.}
{228}{}{Víc nepotøebuju vìdìt.}
{229}{}{Nìco ti øeknu. Líbí se mi jak pracuješ a Carlson by si mohl najít jiného hlídaèe. Dej mi trochu èasu a budu pro tebe mít tam dole práci.}
{230}{}{Jdeme na to, Merku.}
{231}{}{Nepotøebuju práci. Kadopádnì díky.}
{232}{}{Vıbornì. Vra se, a s tím skonèíš.}
{233}{}{To je velmi problematické.
 Hoši, zabijte ho a zajistìte dùkazy.}
{234}{}{Tvoje chabé pokusy mì zastrašit jsou smìšné, ale doporuèuju ti odejít døív, ne mì tahle hra unaví.}
{235}{}{Ach, slyšel jsem tu novinu. A co, poøád se zajímáš o práci?}
{236}{}{Jo, u mì nebaví poøád nìco dìlat zadarmo. Mùu zkusit pracovat.}
{237}{}{Ne.}
{238}{}{Co k èertu dìláš na mém místì?}
{239}{}{Poslyš, to pøedtím... nìjak mi to nemyslelo. U se to nebude opakovat. Chci jen trochu tvého èasu.}
{240}{}{Já si dìlám co chci, ty hade.}
{241}{}{Zmizni odsud šmejde!}
{242}{}{Tak co tady dìláš ty kusu hnoje? Jestli mì chceš naštvat, tak se ti to povedlo!}
{243}{}{Nebudu s tebou hovoøit, dokud nebude dokonèena tvá práce!}
{244}{}{To mì mrzí. Obyèejnì likviduji vìci, které mì mrzí. Nicménì v tvém pøípadì mohu bıt laskavı. Prostì odejdi a nevracej se a já na všechno zapomenu.}
{245}{}{Tak, je ta záleitost s Dr. Henrym vyøízena?}
{246}{}{Jo, mám dokumenty, které jsi chtìl.}
{247}{}{Ne.}
{248}{}{Dny jako jsou tyto mì dìlají šastnım. Dobrá tedy, pojïme uzavøít náš obchod.}
{249}{}{Doneslo se mi, e ten chudák geniální doktor bìhem tvé návštìvy vydechl naposledy. To bylo proti mım pøíkazùm. Aby byly nahrazeny budoucí ztráty, které z toho plynou, myslím, e je tøeba obdret náhradu.}
{250}{}{Hele, dám ti 500 babek a na celou záleitost zapomeneme.}
{251}{}{Jdi k èertu.}
{252}{}{Dobrá, tento odvánı podnik ti vyšel. Teï však nevidím ádnı dùvod pro další konverzaci}
{253}{}{Tìšilo mì.}
{254}{}{Dobrá - ale jen proto e jsi mi sympatickı. A doporuèuju ti - radìji se hned tak nevracej.}
{255}{}{Myslím, e tì prostì zabiju, dostanu zpìt své peníze a vyzvednu si odmìnu. Po tom všem se tak stanu ctihodnım obèanem.}
{256}{}{Zase ty! ZEMØI!}
{257}{}{Myslím, e jsem øekl - Nevyrušovat.}
{258}{}{ a ne nìjakı hlupák. Zeptám se jinde.}
{259}{}{ jednoho chlápka.}
{260}{}{ jedno kuøe.}
{261}{}{Hubologisté jsou praštìní náboenští fanatici. Jednoho mùeš najít v chrámu ve mìstì.}
{262}{}{Jdu na to.}

{263}{}{Nebudu s tebou mluvit, dokud nedokonèíš svou práci! Potøebuji ty dokumenty od Dr. Henryho, rychle.}
{264}{}{Ne, ale potøebuji nìjaké informace.}
{265}{}{Vím, e Lennyho smrt nebyla nehoda, ty bastarde.}
{266}{}{Hej, ta mapa byl podvod.}
{267}{}{Dobrá, a co ty peníze, co jsi za ni dostal?}
{268}{}{Rád bych se omluvil, e ti to nepomohlo.}
{269}{}{Seer tuhle kulku za moje potíe.}
{270}{}{Hmmphf.}

{271}{}{Získáváš }
{272}{}{ zkušenostních bodù za získání dokumentù Dr. Henryho.}
