#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Máš takové tušení, e tohle zelenovlasé zamraèené stvoøení je v tomhle spolku barmankou.}
{101}{}{To je Mira. Zrovna se chystá namíchat nìjakı Rad-A-Waster}
{102}{}{Co o to, je mladá a pøitalivá, ale její oèi øíkají, e se sebou nenechá kadım jen tak mávat. A navíc má na krku zavìšenı øetìz s pìknì pichlavımi ostny.}
{103}{}{Mira, jméno mé. Co to bude, cizinèe?}
{104}{}{Zdravím. Co to bude?}
{105}{}{Pití.}
{106}{}{Vault 13?}
{107}{}{GECK?}
{108}{}{Hmm, dám si tøebas místní specialitu.}
{109}{}{Dej mi pivo}
{110}{}{Informace.}
{111}{}{Hledám práci.}
{112}{}{Hel, no nejsi to ty! Pøesnì tak to mám ráda.}
{113}{}{Zase zpátky?}
{114}{}{Práce.}
{115}{}{Hezky - dostal jsi Lennyho. Úchvatné! Dej si panáka na úèet podniku.}
{116}{}{Cos to udìlal Lennymu - to bylo hroznı!}
{117}{}{Á jé, koukám, e velice zábavnı spoleèník. Co takhle si dát - Rad-A-Waster? Pouhıch deset babek.}
{118}{}{Ano.}
{119}{}{Ne.}
{120}{}{Chceš koupit drink? $10.}
{121}{}{Ano.}
{122}{}{Ne.}
{123}{}{Jeden Rad-A-Waster u se nese! $10.}
{124}{}{Okej.}
{125}{}{Deset babek? To je na mì moc drahı.}
{126}{}{Jistì, davaj mi $1.}
{127}{}{Okej.}
{128}{}{To je moc drahı.}
{129}{}{Tak zkus zajít za Merkem, v zadní místnosti.}
{130}{}{Tady není nic pro tebe, cizinèe.}
{131}{}{Díky, doufám.}
{132}{}{Tak, a co teï, cizinèe?}
{133}{}{Vault 13?}
{134}{}{GECK?}
{135}{}{Máš èas na pár otázek?}
{136}{}{Já jít bye-bye.}
{137}{}{To je vše.}
{138}{}{Tak odsud vypadni, ty balvane!}
{139}{}{Jistì, mám trochu èasu. To se vìtšinou od barmanù oèekává. Jen mì zrovna nic nenapadá.}
{140}{}{Pro tebe si udìlám èas vdycky, baby. Co chceš?}
{141}{}{Jistì.}
{142}{}{Povìz mi nìco o tomhle mìstì.}
{143}{}{Slyšela jsi nìkdy o Vaultu 13?}
{144}{}{Hledám vìc, které se øíká GECK. Nevíš o ní nìco?}
{145}{}{Vo co de s tímhle Merkem?}
{146}{}{Tady ve mìstì je polda, kterı o tobì øíká pìknì drsnı vìci. Co je na tom pravdy?}
{147}{}{Hmm, nìjak mi to vypadlo.}
{148}{}{Jmenuje se to tu NCR. Pùvodnì to vzniklo ze Shady Sands, ale po Vùdcovì poráce, Aradesh a ostatní zaloili Republiku. Teï, je NCR právì tak na hranici. Všechno od jihu a sem, je Republikou ovládáno.}
{149}{}{Jestli ti mùu radit, sna se tu do nièeho nenamoèit. Vrchnost není zrovna moc pøátelská k lidem tvıho druhu, jestli chápeš co tím naznaèuju. Obèané budou vdycky víc v právu, ne ty.}
{150}{}{Hele, to je všechno co ti k tomu mùu øíct.}
{151}{}{Hmm.}
{152}{}{Ještì pár otázek...}
{153}{}{Skvìlı, díky. Budu si to pamatovat.}
{154}{}{Cha, další hledaè ztracenejch pokladù? Tak to se urèitì nezapomeò stavit za Slaneèkem, na Westinovì ranèi. Ten taky èasto vaní o pokladu. Ale moná mu budeš napøed muset trochu provlhèit hrdlo. Hahaha...}
{155}{}{Slaneèek? Já jít.}
{156}{}{Ještì nìkolik málo otázek...}
{157}{}{Dobøe, díky. Tohle si zapamatuju.}
{158}{}{Jasnı, jenom mi øekni jak to namíchat a za chvíli to do sebe mùeš nalejvat.}
{159}{}{Ne pití. GECK je....GECK.}
{160}{}{To není pití. Jedná se o Garden of Eden Creation Kit.}
{161}{}{Ještì nìjaké otázky...}
{162}{}{Hmm, dobrá.}
{163}{}{Velkej chlápek. Mùj šéf. Co oèekáváš, e ti asi tak øeknu?}
{164}{}{Ještì pár otázek...}
{165}{}{Dobrá, díky. Tohle si zapamatuju.}
{166}{}{Ten bastard....byl to jenom takovej divokej rozvod, to je celı.}
{167}{}{Dobrá, nemùeme mluvit o nìèem jiném?}
{168}{}{Ok, myslím, e pùjdu.}
{169}{}{Oh, velmi informativní, e?  Hele, mùeš zkusit Dr. Henryho ve mìstì, ale já musím dìlat jiné vìci, tupoune.}
{170}{}{Garden of Eden Creation Kit? To zní pøetechnizovanì. Co takhle to jít zkoušet na Dorothy, mìstskou inenırku? }
{171}{}{Nìkolik málo otázek...}
{172}{}{Dobrá, díky.}
{173}{}{Hmm -- práci? Chceš práci? Pomùeš Miøe?}
{174}{}{Ano.}
{175}{}{Ne.}
{176}{}{Poslouchej -- zlı mu ubliuje Miøe. Zlı mu se jmenuje Jack. Ubli ty zlému mui. Mira tì bude mít ráda, a dá ti pìknou zbraò. Dobøe?}
{177}{}{Ano.}
{178}{}{Ne.}
{179}{}{Bezva! Mira má nachystáno za zdí lano. Jít v noci. Plíit se. Jít na velké místo pøed bránou. Podél zdi, plíit se dál. Najít lano. Najít Jacka. Zlikvidovat Jacka. Mira ti dá zbraò.}
{180}{}{Jít v noci. Plíit se. Jít na velké místo pøed bránou. Podél zdi, plíit se dál. Najít lano. Najít Jacka. Zlikvidovat Jacka. Mira ti dá zbraò.  Nyní odejít pryè. Vidìt nás nìkdo spolu - není dobré. Pomo Miøe a vra se. Rozumíš?}
{181}{}{Mira slyšet o Jackovi. Dobrá práce, tupounku. Tady je zbraò, ber. A díky.}
{182}{}{Tak mi polib. Nikdy se toho parchanta nezbavím.}
#latter additions
{183}{}{Chceš mluvit s Merkem, jenome tady není. Nakoukni sem v noci. To je spíš jeho èas.}
{184}{}{Nevím co máš s Lennym, ale nechci tì tu vidìt poflakovat. Nejseš tu teï moc populární.}
{185}{}{Hej, já tì varovala. No dobøe. ..}

{186}{}{Jsi Mira, e? Nìjakı polda o tobì nìco vykládal.}
{187}{}{Ty Mira? Jack øíkat zlé vìci.}
{188}{}{Ten bastard Jack? O èem vanil tentokrát?}
{189}{}{Jack mrtvı. Udìlat bada bùm.}
{190}{}{Já zabít. On špatná èlovìk.}
{191}{}{U se tím netøeba znepokojovat. Vyhodil sám sebe do vzduchu v elektrárnì.}
{192}{}{Tentokrát? Nic moc. Dostal to mezi oèi.}
{193}{}{Dìláš si prdel? To je ovšem hit dne! Hehe, doufám, e ten jeho mozeèek krásnì vytapetoval stìny. Zatracenì si to zaslouil. Tady máš Rad-a-Waster na mì.}
{194}{}{Rádo se stalo.}
{195}{}{Já teï jít.}
{196}{}{Tak teda - díky. Øekni, udìláš si èas na pár otázek?}
{197}{}{Díky. Poèítám, e za okamik se to dovíš.}
{198}{}{Coes udìlal? Och, kdybych nebyla v práci, vylezla bych na bar a... no, dala bych ti pusu. Ten parchant si to zaslouil. No, nikomu to neøíkej, ale doufala jsem, e se tu objeví nìjakej jouda, kterej to udìlá za mnì. Mám tu pro tebe malou odmìnu, co se mnì tıká, právem ti náleí.}
{199}{}{Tak teda - díky. Øekni, udìláš si èas na pár otázek?}

{200}{}{Dík. Myslela jsem, e bys to mìl vìdìt.}
{201}{}{Hele, tupoune, právì teï zíráš na nejšastnìjší enu široko daleko! Mám pro tebe malej dáreèek, tadyhle za barem. Všechno je tvı.}
{202}{}{Já rád Mira.}
{203}{}{Já rád zbranì. Já jít pá pá.}