#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Vidíš chlapíka ve velmi elegantním obleku.}
{101}{}{Prodavaè ještìrek na špejli.}
{102}{}{Na prodavaèe ještìrek na špejli má tenhle chlapík styl. Je èistı, dobøe obleèenı a provozuje drobnou èinnost.}
{103}{}{Máte hlad, cizinèe? Nabízím nejchutnìjší ještìrky široko daleko. Zeptejte se koho chcete!}
{104}{}{Co si dáte?}
{105}{}{Dát mi maso.}
{106}{}{Vyberu si jeden kousek, prosím.}
{107}{}{Co mi mùeš povìdìt o tomhle mìstì?}
{108}{}{Nashle.}
{109}{}{Nechte si chutnat, cizinèe!}
{110}{}{Támhle je hoøèice a cibule.}
{111}{}{Hej, kámo.}
{112}{}{Jasnì, nashle.}
{113}{}{Další!}
{114}{}{Podívej, mám jisté pravidlo. Zásadnì o nikom nic nevykládám. Je to dobré pravidlo, protoe kdy drím jazyk za zuby, drím si také od tìla potíe. Kapišto?}
{115}{}{Nic jsem neslyšel, nic jsem nevidìl, a u vùbec nic nevykládám. A teï u mne s takovımi otázkami pøestaò obtìovat.}
{116}{}{Fajn. Teï však cítím, e mám hlad.}
{117}{}{Nemáš vìc zvanou GECK?}
{118}{}{Omlouvám se, svatoušku!}
{119}{}{GECK? Ááá to je starı pøíbìh. Urèitì míníš starı Garden of Eden Kit. Mìli jsme jeden. Tedy, spíše mùj dìdeèek a babièka. Vzali ho sebou, kdy vyšli z Vaultu 15. Na tomhle místì ho pouili, øíkali. Jenome teï u je tím pádem pouitı.}
{120}{}{Ještì pociuji hlad.}
{121}{}{Hmm..., tak dìkuji.}
