#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Vypadá na takového toho týpka, co myslí spíše pìstmi než hlavou.}
{101}{}{Hmmm. Jeden z Merkových strážných.}
{102}{}{Velký. Drsný. Blbý. Bodyguard.}
{103}{}{Odstup dál. Nevstupuj do prostoru pana Merka.}
{104}{}{Uhh...}
{105}{}{Nesmím se bavit s nikým, když jsem ve službì.}
{106}{}{Jestli chceš dìlat potíže, tak kvùli tomu tu jsem. Rozumíš?}
{107}{}{Jdi o kus dál, okej?}
{108}{}{Neotravuj mì.}
{109}{}{Pan Merk nechce být vyrušován.}
