#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Vidíš mue obleèeného v uniformì NCR policie.}
{101}{}{To je Jack, asistent zástupce NCR policie.}
{102}{}{Zdá se, e je zranìn. Má pevnì sevøené èelisti, na èele nabìhnuté íly a není tu ani známky po nìjaké radosti nebo klidu.}
{103}{}{Nechci tu poslouchat nìèí problémy. Najdìte si na to nìkoho jiného.}
{104}{}{Hele, nechci se tady nikomu svìøovat - tobì, ani nikomu jinému.}
{105}{}{Zatracená ex-manelka... vzala mi všechno co jsem mìl.}
{106}{}{Víš, úplnì mne pøede všemi shodila a zesmìšnila. A to teda ne - nikdo si nebude dìlat z Jacka legraci.}
{107}{}{Teï jí ale ukáu. Všem ukáu...}
{108}{}{Na co se èumíš? Vypadni!}
{109}{}{Haló, slyšíte mì!? Jack je tady! Všichni mì dobøe poslouchejte!}
{110}{}{Mám tady bombu, take se o nic nepokoušejte!}
{111}{}{Lidi se vdycky jenom smáli Jackovi. Opovrhovali jím - a kdo se teï smìje, he?}
{112}{}{Budu poèítat do tøí a jestli tu do té doby Mira nebude, všechno tu vyhodím do vzduchu. Jedna...}
{113}{}{Dvì...}
{114}{}{Tøi....}
{115}{}{Co tady chceš? Proè na mì tak upøenì èumíš?}
{116}{}{Chci bıt sám, rozumíš?}
{117}{}{Zatracená ex-manelka - všechno je to její vina.}
{118}{}{U ani krok! Mám bombu!}
{119}{}{Nedìlej to, Jacku. Vím o lepším øešení.}
{120}{}{Eh - stùj.}
{121}{}{Jo, jasnì. Vdy, co ty o tom víš?}
{122}{}{Vím jen to, e v poslední dobì nemáš zrovna na rùích ustláno, ale odpálením bomby rozhodnì nic nevyøešíš.}
{123}{}{To máš pravdu. Co já o tom vím? No, a co kdybychom si o tom trochu promluvili?}
{124}{}{Co má tohle bıt - nìjakı trik? Chceš se mnou vykecávat, zatímco tvùj parák mì zezadu odpráskne?}
{125}{}{A kdo tì chce zabít?}
{126}{}{Klid, nikdo ti neublíí.}
{127}{}{Ta zatracená èubka, moje ex-manelka, Mira. Ona chce moji smrt.}
{128}{}{O tom a tedy rozhodne zákon. Tímhle to nevyøešíš, Jacku.}
{129}{}{Máš pravdu. Ona si mì na tebe najala. Musím tì zabít. Co na to øekneš, Jacku??}
{130}{}{Kdo je vlastnì Mira?}
{131}{}{Tak jo, svinì. Udìlej to! Do toho!}
{132}{}{Dìláš si srandu?! Já jsem zákon. A podívej, k èemu to vedlo.}
{133}{}{Jacku prosím, zapøemıšlej o tom.}
{134}{}{Take se domníváš, e odpálením elektrárny, vyøešíš problém s Mirou?}
{135}{}{Jak øíkám. Moje bıvalá. Byla mi nevìrná, já ji pøi tom pøistihl a ona pak všem navykládala, e ten špatnı jsem já. Musel jsem jí dat všechno a ona mì chce poøád vydírat.}
{136}{}{Fíha, to je teda... to je ale mrcha.}
{137}{}{To se dá napravit. Èas ty rány vyléèí. A oba na to zapomenete.}
{138}{}{Urèitì...Ne. Teda, já vlastnì nevím. Ale musím nìco udìlat. Dát lidem najevo, e Jack u se nenechá jen tak pošlapávat.}
{139}{}{Ale to oni pøece vìdí, Jacku. A øeknu ti tohle - kdy teï sám sebe vyhodíš do vzduchu, nebude si tì váit vùbec nikdo.}
{140}{}{Hele, tak víš co? Vyhoï si tady tu elektrárnu klidnì do vzduchu a jenom potvrdíš to, co o tobì vykládali.}
{141}{}{Však klídek, Sherlocku. Teï pøicházejí lidé a všechno poslouchají.}
{142}{}{Nikdo ti sem nepøijde naslouchat, dokud budeš dret v ruce bombu. Polo ji na zem, pojï ven, a mùeme to celé vyøešit.}
{143}{}{Hele, povím ti tohle - vyhoï to tu do povìtøí a lidé si øeknou, "Pche, Jack se nechal komandovat od své bıvalé a u to déle nevydrel." Ona vyhraje, ty prohraješ.}
{144}{}{Opravdu si to myslíš?}
{145}{}{Ano, Jacku. Je to tak.}
{146}{}{Ovšem. Snad si nemyslíš, e ti jenom nìco namlouvám?}
{147}{}{Kdy já nevím...}
{148}{}{Nenech ji vyhrát, Jacku.}
{149}{}{Teï máš šanci. A lidé si tì budou váit.}
{150}{}{Vùbec mì neposloucháš! Jenom to celı pøekrucuješ. A já u jí mám dost.}
{151}{}{Achjo k èertu, snad máš pravdu. Tohle asi nebylo zrovna nejlepší øešení.}
{152}{}{Chci to vyøešit, víš?}
{153}{}{Zatracená Mira, teï ji dostanu.}
{154}{}{Teï lidé vìdí, kdo je Jack, tím si buï jist.}
{155}{}{Dr se zpátky! Nechci ti ublíit!}
{156}{}{Tohle se tì netıká!}
{157}{}{Jen do toho, zabij mì. Myslíš, e se bojím?}
{158}{}{S tímhle nemáš nic spoleènıho. Nech mì bıt.}
{159}{}{Buï nás oba vyhodím do vzduchu, nebo mì zabiješ. Co mohu ztratit?}
{160}{}{Nesnaím se ti ublíit! Jen si vzpomeò...}
{161}{}{Získáváš }
{162}{}{ zkušenostních bodù za vyøešení záleitosti "Jack vs. Mira".}
