#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Vidíš špinavého muže v otrhaných, krví potøísnìných hadrech.}
{101}{}{Vìzeò, kterého chytili.}
{102}{}{Jeho oblièej a ruce jsou plné starých jizev od nožù a v oèích má napùl šílený výraz, dávající jasnì najevo, že jde o výtržníka a psance.}
{103}{}{Plýtváš tu èasem. Neøeknu tobì èi komukoliv jinému ani slovo.}
{104}{}{Vypadni a nech mne být, ty prase.}
{105}{}{To ty tu dìláš takovej smrad?}
{106}{}{Co to k èertu dìláš - chceš mì zastrašit, abych mluvil?}
{107}{}{Ty mne nezastrašíš.}
{108}{}{Co takhle mi políbit boty? }
{109}{}{Co to sakra dìláš? Ty mì chceš snad zabít! Stráže!}
{110}{}{Nìco mi povíš, nebo tì zabiju.}
{111}{}{Nikdo ti nepøijde na pomoc. Jestli chceš žít - mluv.}
{112}{}{Okej, okej! Co chceš vìdìt? Jen už mi neubližuj.}
{113}{}{Vault 15 - povídej.}
{114}{}{Co chceš vìdìt o Vaultu 15?}
{115}{}{Hele, já jsem jen obyèejnej poskok, žádný velký zvíøe - zato Darion. On je ten, kterýho chceš. Má nìjaký nevyøízený úèty se Shady Sands a tou starou dìvkou Tandi. Skrývá se ve Vaultu 15 a dokonce pøesvìdèil místní lidi, že je na jejich stranì.  To je vše co vím. Pøísahám!}
{116}{}{Opravdu, už víc nevím! Povìdìl jsem ti všechno co vím, vìø mi! Už mi víc neubližuj.}
{117}{}{Tak to ne! Nelíbí se mi tvoje triky. BANG! - zastøelen pøi útìku. Zapomeò na to!}
