#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Vidíš obyvatele mìsta.}
{101}{}{Vidíš jednoho z místních lidí.}
{102}{}{Na této osobì se u nedá nic zvláštního vypozorovat.}
#Personal Enemy
{103}{}{Aááá, nech mì bıt.}
{104}{}{Omlouvám se. U to neudìlám.}
{105}{}{U mizím.}
{106}{}{Stráe, je zpátky!}
{107}{}{Prosím, nech mne bıt.}
{108}{}{Podívejte, chci bıt od vás radìji dál.}

#Child Killer
{109}{}{Jsi ztìlesnìné zlo. Vùbec na mì nemluv.}
{110}{}{Nech naše dìti bıt.}
{111}{}{Jsi chorobomyslnı zloèinec. Doufám, e tì stráe dopadnou.}
{112}{}{Jdi zase dál, okej?}
{113}{}{Hej, nikoho nezabíjej - zvláštì dìti.}
{114}{}{Nikdo tì tu nemá rád.}

#Berserker
{115}{}{Hej, nech mì hádat, kdy to tu zmìníš v jatka.}
{116}{}{Musím u jít.}
{117}{}{Kdo si k èertu myslíš, e seš - pøijít si do tohohle mìsta?}
{118}{}{Radìji odsud vypadni, ne nìkoho napadneš.}
{119}{}{Nemáme tì tu rádi.}
{120}{}{Takovı jako ty, tady likvidujeme.}

#Low Town Rep
{121}{}{V èem je problém?}
{122}{}{Nemùeš nás prostì všechny nechat na pokoji?}
{123}{}{Nemluv na mne.}
{124}{}{A u cokoliv - jdi si to povídat nìkomu jinımu.}
{125}{}{Myslím, e nebudeš takovı tvrïák.}
{126}{}{Proè radìji nevypadneš?}

#normal
{127}{}{Musím si obstarat pár vajíèek.}
{128}{}{Nevíš jak dostat ten obkládací plech nahoru?}
{129}{}{Nazdárek.}
{130}{}{Prosím neruš mì, mám hodnì práce.}
{131}{}{Zdalipak má Dusty ještì nìjaké brahmíní koláèky?}
{132}{}{Nìkdy se sobì divím, kam to vlastnì jdu.}
{133}{}{Umm, díky, opravdu u musím jít.}
{134}{}{Moná si pozdìji dáme obídek.}
{135}{}{Ach, hleïme, máme tady nováèka.}
{136}{}{Jdi si promluvit se šerifem.}

{137}{}{Brzy se tu prı budou stavìt nové domy.}
{138}{}{Do té doby ne byl zvolen Dumont, bylo tohle docela klidné mìsto.}
{139}{}{Dobrı den, cizinèe.}
{140}{}{Máme tu docela klidné místo. Pìkné, ne?}
{141}{}{Jsi tu nováèek? Zajdi se podívat k mému bratranci Duppovi.}
{142}{}{Dole na jihu jsou prı teï tìké èasy. Kde je vláda, která by s tím nìco udìlala?}
{143}{}{Pøicházíš ze severu? Není tu mnoho lidí odtamtud.}
{144}{}{Prı kadı, kdo pøichází z pustin, je mutant nebo divoch èi nièema!}
{145}{}{Není èas na øeèi. Jdi si sehnat práci.}
{146}{}{Máte tu trbu od Duppa? Och, zapomeòte na to.}
