#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Vypadá na štamgasta.}
{101}{}{Ten samı opilec odminule.}
{102}{}{Nevypadá zrovna nejlépe, ale mít TY v sobì tolik chlastu...}
{103}{}{Hele, v klidu si tu popíjím. Nech mì bıt.}
{104}{}{Nebavím se s cizinci. A vùbec, v tomhle baru není pro tebe bezpeèno.}
{105}{}{Slyšel jsem o tobì. Ale tady seš k sakru na špatnım místì!}
{106}{}{Chceš nìco? Jdi za Merkem.}
{107}{}{Hej, ty - co dobøe vypadáš, nechceš si zajít na jedno malé místeèko a trochu si uít?}
{108}{}{Nemluv se mnou! Nemám zájem o další vıprask.}
{109}{}{Zatracená laciná whisky! Hele, pro tvou informaci - tady se podává to nejhorší pití.}
{110}{}{Doprdele! Nechtìl jsem tì tím polít. Uka, trochu ti to vyèistím. Opravdu se omlouvám.}
{111}{}{Dr se od mì dál!}
{112}{}{O tobì jsem slyšel. Prosím, nic mi nedìlej.}
{113}{}{Nováèek? Pak je tvoje heslo Merk. Hledá toti nìjaké drsnìjší chlapíky.}
{114}{}{Co jsi zaè, nìjakı ranaø? Ztra se mi z oèí!}
{115}{}{Tohle nemìli dìlat. Nìkterı den, cizinèe, a budu mít zbraò, tak jim ukáu.}
{116}{}{Jak se ti líbí mùj milı otrok? Pìknı, co?}
{117}{}{Chlastat a vanit - k èertu, nic jinıho se tady nedìje.}
{118}{}{Jdi pryè, vyrušuješ.}
{119}{}{Nevíš náhodou nìco o...}
{120}{}{Take, povídám mu, "podívej se," ...}
{121}{}{Zkus ronìnou krtèí krysu. Je to nejchutnìjší jídlo v okolí.}
{122}{}{Ahoj. Jak se jmenuješ?}
{123}{}{Jestli hledáš práci, cizinèe, zajdi si dolù ke Stockmenovì asociaci.}
{124}{}{Doprdele! Vidìli jste to?}
{125}{}{Grrk, asi pùjdu..zvracet...}
{126}{}{Mnì u ne.}
{127}{}{Hej, namíchej mi nìco z toho!}
{128}{}{Dal bych si Rad-a-Waster jako tenkrát...}
