#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Hromada hadrù, pod kterımi jakoby byl nìjakı èlovìk.}
{101}{}{Vidíš Ratche. Pravdìpodobnì si teï vybírá nìjaké vši.}
{102}{}{Mohl by to bıt èlovìk. Taky by to mohl bıt mutant. Všechno co se o nìm dá øíct je to, e páchne. Ale opravdu velmi páchne.}
{103}{}{Haraburdí na prodej, staré vìci na prodej. Mrkni na to a navrhni mi cenu.}
{104}{}{Prosím, èím mohu poslouit?}
{105}{}{Eh...heh.}
{106}{}{Tak co je na prodej?}
{107}{}{Zdá se, e máš šikovné ruce. ivíš se rukama, e?}
{108}{}{Dám ti $5. Povíš mi nìjaké èerstvé klepy?}
{109}{}{Nashle.}
{110}{}{Vidíš támhle to? To je moje favoritka - tamta Edna. Pojmenovávám všechny své vìci, víš - jsou to vlastnì moje dìti. A hroznì nerad je prodávám, ale nemám co jíst.}
{111}{}{Pošpinil jsi všechny mé dìti!}
{112}{}{Tak jo, dobrá. Tady máš pìák. Nemáš nìjaké èerstvé klepy?}
{113}{}{O-kej - nejsi jen zvláštní! Asi se poohlédnu po nìjakıch jinıch obchodnících.}
{114}{}{Ještì jednou se podívám co máš.}
{115}{}{Myslet, e my a Edna u jít.}
{116}{}{Oh, díky bohu, e si cizinec nechce vzít mé dìti...Moje zboí jsou mé dìti, víš?}
{117}{}{Ehh - jistì.}
{118}{}{Nue, myslím, e pùjdu.}
{119}{}{Mohu ti opravit èi vylepšit spousty nejrùznìjších vìcí. Namontuji ti takové dmychadlo, øíkám mu Claudia a pasuje do vìtšiny druhù aut - a získáš tak mnohem vìtší vıkon. Pouze $1000. Máš zájem?}
{120}{}{Já blbec, u jsme se o tom bavili.}
{121}{}{Samozøejmì, Claudia... to beru.}
{122}{}{Asi zmìníme téma.}
{123}{}{Slyšel jsem vykládat o doktorovi ve mìstì... prı má nìjakı zázraènı lék. Ovšem já bych to tak nevidìl...}
{124}{}{Pak tøeba Slaneèek. Ten starı blázen øíká, e našel zlatı dùl...}
{125}{}{Paní Dorothy a Toto zde poslední tıden nebyli. Vydali se hledat nìjakou souèástku k opravì elektrárny. V tomto jsem jim bohuel nemohl pomoci...}
{126}{}{Mluví se tu o tom, e to co se pøihodilo panu Westinovi, nebyla ádná náhoda. Nìkterım lidem se zdá, e tu je pøíliš mnoho podezøelıch cizincù...}
{127}{}{Dìkuji za peníze, ale nic víc u nevím.}
{128}{}{Tumáš další pìák.}
{129}{}{Mohu vidìt co nabízíš?}
{130}{}{Tak dìkuji za informace.}
{131}{}{OK. Dej mi tak šest hodin. Za tu dobu bych to mìl zvládnout...}
{132}{}{Pøedtím ne pùjdu, mohu mít pár otázek?}
{133}{}{Dobrá. Uvidíme se pozdìji.}
{134}{}{Hele, tak a budeš mít peníze, pak pøijdi. Myslím, e tu vìc budu ještì mít.}
{135}{}{To mi staèí.}
{136}{}{Nashle.}
{137}{}{Tak a je to! Claudia je instalována.}
{138}{}{Dej mi trochu víc èasu. Poøád se trápím s tou zatracenou vìcí.}
{139}{}{Ouha! Myslím, e mozek pro tebe bohuel nemám.}
