#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Vidíš cosi napùl mezi psem a napùl kovovou vìcí. Zdá se, e je to v provozu.}
{101}{}{Je to RoboPes! Pro kadého ten nejoblíbenìjší mazlíèek!}
{102}{}{Je to taková slátanina psa a stroje. Ovšem ta psí polovièka má docela hezkı kukuè. Je tìké urèit, co to pøesnì je.}
{103}{}{Vraf! <klap> Haf!}
{104}{}{...bzzzzzz...}
{105}{}{.bzíííík...Já nejsem pejsánek.}
{106}{}{Vrrrrrrrrrrrrrrrr--}
{107}{}{Haf! Ha-ha-ha-<klapk>haaf.}
{108}{}{<škrr>  Mùéé...chyba.}
{109}{}{Štìkštìkštìkštìkštìkštìk!}
{110}{}{Vrrr...}
{111}{}{Haf-bùùù! <klap-klap> Haf-bùùù!}
{112}{}{Jejda! Jejda! Jejda!}
{113}{}{Nebezpeèí! Nebezpeèí!}
{114}{}{Vrraf! <uk-uk-uk> Vrraf!}
{115}{}{<whirrr> Ani pták, ani letadlo, dokonce ani ába, jenom starı dobrı - RoboPes!<klap>}
{116}{}{Rooby-Doo!}
{117}{}{Eé-béé-déé-béé-éé-béé-déé-béé!}
{118}{}{Haf!}
{119}{}{VRRR-HAF!}
{120}{}{Òaf-òaf-òaf-òaf-òaf-òaf-òaf!}
{121}{}{OK}
{122}{}{Myslím, e u tì znovu nechci. Sbohem.}
{123}{}{VRRAF? <klap> Òaf?}
{124}{}{Jak se máš?}
{125}{}{Potøebuji abys zde poèkal, dokud se nevrátím.}
{126}{}{To je prozatím vše.}
{127}{}{<klap> kòuèí}
{128}{}{Nevadí.}
{129}{}{OK}
{130}{}{HB:}
{131}{}{Cyberpes nemùe bıt nyní opraven.}
{132}{}{Cyberpes byl zèásti opraven.}
{133}{}{Cyberpes byl úplnì opraven.}

#specific party messages
{1000}{}{Haf! Ha-ha-ha-<klap>haf?}
{1100}{}{Òaf! <cvak> Haf!}
{1200}{}{Vrraf? <klap> Òaf?}
{1300}{}{<cvak> kòuèí.}
{1400}{}{How-woooo! <click-click> How-wooo!}
{1500}{}{Eé-béé-déé-béé-éé-béé-déé-béé!} //Wait here resoponse
{1600}{}{Ano jistì, dám to pryè.}  //Put weapons away
{1700}{}{Haf-haf vzdálenost nastavena blízká.} //Close
{1800}{}{Haf-haf vzdálenost nastavena støední.} //Medium
{1900}{}{Haf-haf vzdálenost nastavena velká.} //Far
{2000}{}{.bzíík...Já nejsem pejsánek.}
{2100}{}{VRRR-HAF!}
{2200}{}{Haf! Ha-ha-ha-<klap>haaf?}

{2204}{}{Ok, tvoje vzdálenost je momentálnì vyhovující.}