#tento soubor prelozil MAG2
#
{100}{}{Vidíš muže v umaštìných šatech, zøejmì mechanika.}
{101}{}{To je Rondo, majitel tohoto místa.}
{102}{}{Myslíš si, že je mechanik, ale on má umìlou ruku. To ho dìlá trochu nesoumìrným.}
{103}{}{Vítej tuláku. Doufám, že se ti daøí.}
{104}{}{Jednou to tady od tìch otrokáøù vyèistíme.}
{105}{}{Potøebuju chytit ještì pár otrokáøù..}
{106}{}{Promiò, ale už máme zavøeno.}
{107}{}{Toto je soukromý majetek. Rozumíš?}
{108}{}{Já teï neberu žádnou další práci, okej?}
{109}{}{Bastarde, poèkej až potkáš Rangery.}
{110}{}{Zkus se jenom dotknout nìkteré z mých vìcí a já ti ukážu, zaè je toho loket.}
