#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Vidíš starého umounìného mue se splstnatìlımi vlasy.}
{101}{}{Tenhle chlápek si øíká Slaneèek Bob}
{102}{}{Má asi tak tøi zuby a oblièej protkanı drobnımi ilkami opilce. Velmi zapáchá.}
{103}{}{Zdravím tì, cizinèe!}
{104}{}{Hrmm?}
{105}{}{Jak se jmenuješ?}
{106}{}{Jmenuju se Bob. Anebo mi øíkej Slaneèek Bob. A jak ty?}
{107}{}{Ještì jednou to tvı jméno, cizinèe? Já jsem Slaneèek Bob.}
{108}{}{[Jméno hráèe]}
{109}{}{Slaneèek? Co to je za jméno?}
{110}{}{A co tady dìláš?}
{111}{}{To jméno ti docela skvìle padne, fakt. Heleï, nenapijeme se spolu, co?}
{112}{}{Ano.}
{113}{}{Ne.}
{114}{}{Jdi ode mì, dìdku smradlavej!}
{115}{}{Dobrá, nemusíš se kvùli tomu hned èertit. Víš, myslel jsem jen pár douškù, chápeš? Uklidnit se trochu...}
{116}{}{Hohó-jedem! Mluvíš jako po poøádném loku dobré koøalky! Øekni, nepodìlíš se? Jenom malı doušek.}
{117}{}{Chlast! Bezva!}
{118}{}{Øííííh!}
{119}{}{V klidu, kámo! Pøece mi nebudeš vyèítat, e jsem se jen ptal? Radìji tì tedy nechám.}
{120}{}{(Glg, glg, glg) Aaaach! To je od tebe moc hezké, cizinèe! Jsi fajn èlovìk, víš to? Takového èlovìka bych rád, jako svého pøítele. (Glg)
 e jsem ti ještì nepovídal o svém velkém ivotním úspìchu?}
{121}{}{Ne.}
{122}{}{Hele, pøestaò u pít z mé lahve!}
{123}{}{Rahhhg!}
{124}{}{Bylo to v '78 a já a Bessie - nejlepší 'bot, jakého mohl èlovìk chtít - jsme tenkrát provádìli u-ra-ni-ovı prùzkum západnì odsud. Ještì jsme nenarazili ani na kousek uranu co by za to stálo, kdy mezi nás skoèilo pìt - ne, jsem si jist, e deset - deathclawù.}
{125}{}{Zaèal lítı boj. Støílel jsem tak, e se moje brokovnice úplnì rozhavila a musel jsem šáhnout po noi, kdy stará Bessie navdy roztavila svùj poslední obvod. Samozøejmì, zkoušel jsem ji zachránit, ale bylo ji pøíliš pozdì. Musel jsem se sebrat a zachránit aspoò sebe, tím, e jsem vlezl do skal po cestì.}
{126}{}{No, vypadalo to se mnou špatnì, kdy jsem se dopotácel do jeskynì. Byl jsem úplnì vyøízenı. A navíc jsem byl pøímo v jejich doupìti - ale mìl jsem pochodeò, tak jsem šel dál dovnitø. Fíha, byla to hluboká jeskynì. A to mne zachránilo.}
{127}{}{Narazil jsem na obrovské vstupní dveøe, takové jaké jsem vidìl ve starıch filmech. Veliké a celé ze eleza. A na nich se skvìla veliká 13!}
{128}{}{Bylo mi jasné, e jsem našel nìco dùleitého, Vault 13. Sedl jsem si a udìlal mapku. Zatracenì blízko smrti, dostal jsem se odtam, proplíil se kolem deathclawù a pak se vydal na sluncem zalitou pouš, bez kapky vody.}
{129}{}{Ani sám poøádnì nevím, jak jsem se doplazil do Shady Sands. Byl jsem témìø mrtev. Vzali mne k doktorovi, kterı mì ošetøil, ale ukradl mi moji mapku. Vím to a to je celé.}

# took this out -- Got anymore o' that drink, stranger?
{130}{}{(Pokraèovat)}
{131}{}{Sakra, je to dobré a poctivé jméno, to je to! Pus mì tady poblí do nìjaké kuchynì a uvidíš. A jestli tu ádná není, urèitì tì uèili, jak se chovat ke starším lidem.}
{132}{}{Promiòte, starı pane nemínil jsem vás rozèílit.}
{133}{}{Dobrá, dej mi co proto, dìdku!}
{134}{}{Rozèílit? Rozèílit mì! Zatím ještì nejsem rozèílenı! A teï se mi ztra z oèí, ne opravdu vypìním! Pryè! Zmiz!}
{135}{}{No, to bych asi špatnì dopad. Ale teï si pojïme rozumnì promluvit. Neber od nikoho nic doslovnì, kámo, jasnı?!
 Povìz, nemáš trochu koøalky nazbyt? Jenom malı doušek?}
{136}{}{Ano.}
{137}{}{Ne.}
{138}{}{Jdi ode mì, dìdku smradlavej!}
{139}{}{Ha, ha, ha! Je teï moje. Budeš si muset najít svou vlastní!}
{140}{}{Šéf mne zde nechal. Vedu tento chlév! Dohlíím tu na èistotu a mám pod sebou i kousek pastvin.}
{141}{}{Slaneèek? Co je tohle za jméno?}
{142}{}{Pìkné setkání. Jsem}
{143}{}{Hromy a blesky, zase ty? Ztra se mi hned z oèí!}
{144}{}{Tak se na mì zkus vrhnout!}
{145}{}{Jsi jenom staøík, co dìlá ve chlévì, co mi mùeš?}
{146}{}{To sakra jo, to jsem! Hele, nemáš trochu chlastu nazbyt, e bychom si dali? Mìj soucit se starım muem.}
{147}{}{Ano.}
{148}{}{Ne.}
{149}{}{Jdi ode mì, dìdku smradlavej!}
{150}{}{.}
