#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Vidíš šedovlasého muže v uniformì NCR policie.}
{101}{}{Šerif NCR.}
{102}{}{Tento muž je názorná ukázka toho, co pøedstavuje policie - vlasy na ježka, hranatá èelist - opravdu absurdní druh èlovìka.}
{103}{}{Vítej v NCR, cizinèe. Jmenuji se Dumont - Šerif Dumont. Doufám, že zde bude bìhem tvého pobytu vše probíhat v míru a poklidu.}
{104}{}{Pøijmi malou radu od šerifa Dumonta, cizinèe - v tomhle mìstì nemáme rádi týpky jako jsi ty. Jakékoliv potíže a jdu tvrdì po tobì. A teï - mohu pro tebe nìco udìlat?}
{105}{}{Zdravím. Mohu pro tebe nìco udìlat?}
{106}{}{No, tak to ze sebe vyplivni.}
{107}{}{Heegh.}
{108}{}{Hledám Vault 13. Nevíš kde by se mohl nacházet?}
{109}{}{Nevíš, nedá se tu sehnat GECK?}
{110}{}{Hledám nìjakou poctivou práci. Mùžeš mi v tom poradit?}
{111}{}{Och, skvìlé. Všechno je bájeèné.}
{112}{}{Primitiv, což? Hmm. Otázky? Ptej se.}
{113}{}{Vault 13?}
{114}{}{GECK?}
{115}{}{Ok-ej.}
{116}{}{Ne, to nevím. Tohle je nìco, co by dokonce i presidentka Tandi ráda vìdìla. A to je jen jeden, z mnoha problémù.}
{117}{}{Problémù? Jakých problémù?}
{118}{}{Presidentka Tandi?}
{119}{}{Skvìlé. Štìstí pro mne. Díky.}
{120}{}{Poslyš, vedu prospìšný život a mám èistý rejstøík! Nemám žádný GECK nebo cokoliv takového.}
{121}{}{So-rry! Nevíš nìco o Vaultu 13?}
{122}{}{Zapomeò na mé otázky. Už odcházím.}
{123}{}{Mìl bych pár tipù, jestli tì to opravdu zajímá.}
{124}{}{Dìláš si srandu, ne? Po té události s Jackem? Myslím, že tu jistì najdeš stálou práci.}
{125}{}{No a konkrétnì?}
{126}{}{Ne, zmìòme téma.}
{127}{}{Zapomeò na to, odcházím. Nashle.}
{128}{}{Ne Vault 13. Vault 15, ano.}
{129}{}{Pat-náct?}
{130}{}{Ne. Tøi-náct!}
{131}{}{Ano, 15! Promluv si s Tandi. Velký šéf NCR. Tandi zná Vault. Hledá pomoc. Jdi za Tandi.}
{132}{}{Tandi?}
{133}{}{Nepùjdu. Já hledat 13!}
{134}{}{Po-slou-chej. Žádný Vault 13. Neznám. Nevidìl jsem. Ne 13. Vault 15 - lidé našli. Lidé žijí ve Vaultu 15. Rozumíš mi?}
{135}{}{Ne tøi-náct? Pat-náct?}
{136}{}{NE. JA HLEDAT TØINÁCT!}
{137}{}{Arrgh! NEVÍM O 13, TY TUPEJ ZABEDNÌNÈE! Žádný 13. Nenalezen. Vùbec! Nikdy!}
{138}{}{Tandi je velký šéf. Tandi hledá pomoc. Promluv si s Tandi. Jdi do kon-gresu. Okej?}
{139}{}{GECK?}
{140}{}{Ok-ej.}
{141}{}{Nepotøebuji GECK. Jsem zdráv. Ne nemocen.}
{142}{}{Vault 13?}
{143}{}{Ok-ej.}
{144}{}{Rozhlédni se kolem sebe. NCR je stále se rozrùstající místo. Potøebujeme souèástky, poèítaèe, všechno možné. Jenomže máme problém s usedlíky, kteøí se pøistìhovali k Vaultu 15.}
{145}{}{Vault 15? Usedlíci? No a dál?}
{146}{}{Co je zaè tahle prezidentka Tandi?}
{147}{}{Dìkuji za informace.}
{148}{}{Pøece prezidentka NCR, kdo jiný? Nyní musí mít opravdu velké problémy, protože mne dokonce žádala, abych jí pùjèil jednoho ze svých zástupcù na speciální misi. Velmi nerad jsem to musel odmítnout, protože lidí nemám nazbyt.}
{149}{}{A co tøeba já? Možná bys mì mohl doporuèit.}
{150}{}{Hmm. Tìžký život, koukám.}
{151}{}{Tebe? Hmmm... ale takhle by to nešlo. Na rovinu - vlastnì tì poøádnì neznám. Musíš jít za ní a promluvit si o tom. Její kanceláø je v Kongresu.}
{152}{}{Díky. Udìlám to.}
{153}{}{Nevíš nìco o vìci zvané GECK?}
{154}{}{Hmm, to je od tebe zatracenì hezký, cizinèe - a taky zatracenì sebevìdomý. Nevím jestli vùbec pocházíš z Adama a Evy a ani trochu se mi nelíbí tvùj pohled! Já nedoporuèuju jen tak každýho. A teï, mám nìjakou práci.}
{155}{}{Nuže, je zde Duppo ve Stockmenovì asociaci. Najímá na Brahmíní okruhy.  Pak je zde pan Westin. Jestli s ním budeš mluvit, povìz mu, že tì posílám. A dokonce i prezidentka Tandi nìkoho hledá.}
{156}{}{Duppo ve Stockmenovì asociaci shání lidi, ohlednì Brahmíních okruhù. Jdi to zkusit za ním.}


{157}{}{Westin?}
{158}{}{Presidentka Tandi?}
{159}{}{Pùjdu se poohlédnout.}
{160}{}{Roger Westin. Jeho pozemky se nacházejí v západní èásti mìsta. Má potíže s nìjakými neøády.  Je na sebe teï velmi opatrný, protože jeho zdraví není to co bývalo. Jak øíká doktor Jubilee, koupil si špatný lístek.}
{161}{}{Nó?}
{162}{}{Je v tomto mìstì nìjaká práce?}
{163}{}{Zapomeò na to. Odcházím.}
{164}{}{A tak to zùstane. Nashle.}
{165}{}{To je zatracenì dobrý kus práce co se ti povedlo se starým Jackem, cizinèe. Jako šerif, tì odsud dostanu.}
{166}{}{Tohle všechno je tvý.}
{167}{}{Co takhle nìjaká odmìna?}
{168}{}{No, nemohu øíct, že si nezasloužíš peníze. Jediné co ti však mohu dát, je mùj dík.}
{169}{}{Poèkej. Mám nìjaké otázky.}
{170}{}{Och, rozumím, v poøádku.}
{171}{}{Promiò, nemohu si s tebou teï vykládat. Už tak pøijdu pozdì k soudnímu ohledání mrtvého. Mì to pøipadá zcela jasný.}
{172}{}{Promiò, není zloèin, není èas.}
{173}{}{Pouštní krysy jsou to. A kvùli lepšímu porozumìní:     Koøeny tohoto mìsta sahají až k Vaultu 15. Zdá se, že pøed dávnými èasy, tam mìli lidé nìjaké potíže a ti co pøežili, založili Shady Sands. Takže po právu je Vault 15 jejich majetkem. Pøed nìkolika lety tam však pøitáhli nìjací usedlíci a zaèaly zase problémy. Nejlepší bude, když si o tom pùjdeš promluvit pøímo s Tandi.}
{174}{}{Tandi?}
{175}{}{Pùjdu se poradit.}
{176}{}{Není zde žádná práce o které bych vìdìl.}
{177}{}{Duppo ve Stockmenovì asociaci shání lidi, ohlednì Brahmíních okruhù. Prezidentka Tandi se shání po nìjakém šikovném èlovìku.}
{178}{}{Kdokoliv jiný tvé velikosti by opustil mìsto, mnohem obyèejnìjší hledají práci.}
{179}{}{Duppo ve Stockmenovì asociaci shání lidi, ohlednì Brahmíních okruhù. Jdi to zkusit za ním.  Pak je zde pan Westin. Jestli s ním budeš mluvit, povìz mu, že tì posílám.}
