#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Vidíš slabouèkého mue.}
{101}{}{To je Doofus, posluha a poskok kolem aut.}
{102}{}{Tenhle malı potrhanı chlápek, má jškubání a tiky. Urèitì bere nìjaké drogy.}
{103}{}{Tohle je nìco pro vás, èlovìèe, opravdu vıborné! Oh èlovìèe, já jsem pro vás ten pravı - pohlídám Vaše auto a budu od nìj odhánìt všechny dotìry. Pìt niklákù, nic víc. Pìt niklákù a Doofus je váš! Nikdy nespím - 24 hodin, poøád na místì, èlovìèe.}
{104}{}{Já se starám o auta, èlovìèe. A za $5 - Vám ho dobøe pohlídám. Zaruèuju Vám, e nikdo nešáhne na vaše auto, dokud ho má na starosti Doofus.}
{105}{}{Správnì, jistì èlovìèe.}
{106}{}{Tak èlovìèe, chcete moje sluby?}
{107}{}{Dobrá. Mùeš..}
{108}{}{Ne. Ani na nìj nesáhneš.}
{109}{}{Neøíkej mi èlovìèe!}
{110}{}{Co je tohle za místo?}
{111}{}{Domluveno. $5 - a hlídej mi ho dobøe.}
{112}{}{Ztra se, skrèku!}
{113}{}{Oh èlovìèe, jakı velikán to ke mnì promlouvá! Tak to je skvìlé?}
{114}{}{Gurg?}
{115}{}{Neøíkej mi èlovìèe!}
{116}{}{Co je tohle za místo?}
{117}{}{Tak je to správnì. Jsem opravdu mocnı velikán! Budeš mì poslouchat.}
{118}{}{Bezvıznamná nulo - ztra se!}
{119}{}{Co potøebujete od Doofuse, èlovìèe?}
{120}{}{Ááá my u se vidìli, e? Èím poslouím?}
{121}{}{Ano jistì, èlovìèe.}
{122}{}{Aehm?}
{123}{}{Neøíkej mi poøád èlovìèe!}
{124}{}{Co tu dìláš?}
{125}{}{Co je tohle za místo?}
{126}{}{Nic. To je omyl. Nashle.}
{127}{}{Jo, èlovìèe, varoval jsem tì. Špatné místo. Špatní lidé všude kolem. Slyšel jsem, e si na váš konvoj vyšlápli.}
{128}{}{Brak?}
{129}{}{Jak to víš?}
{130}{}{Skvìlé. Díky. Bezva.}
{131}{}{Doofus bude spolehlivì hlídat, èlovìèe. Dokonce ani moucha si netroufne pokálet váš au-to-mo-bil!}
{132}{}{Co je tohle za místo?}
{133}{}{Dobøe. A u mlè.}
{134}{}{Jestli nemáš prachy, tak vodsud táhni nìkam! Mám na starosti dùleitìjší vìci.}
{135}{}{Hej èlovìèe, Doofus Vás varoval.}
{136}{}{Polib mi. Nebudu odpovídat na tvoje otázky.}
{137}{}{Co je tohle za místo?}
{138}{}{Nashle}
{139}{}{Báj-báj.}
{140}{}{No teda, snaha o komunikaci! Pozvednu ti tvoje duševní myšlení! Oukej, nech mne zkusit... uhhh.... Uhhh...}
{141}{}{Ano?}
{142}{}{Ne?}
{143}{}{Tvoje hlava je ztracenı pøípad. Odcházím.}
{144}{}{Tohle je NCR - vznešená, mocná, spravedlivá, absolutnì a vdy správná New California Republic. Jsou tu lidé, je vedou ztroskotance, jako jsem tøeba já, z pustiny smìrem k lepší budoucnosti. Chápete to?}
{145}{}{Nue, vrame se zpátky k tvojí nabídce.}
{146}{}{Díky. Nashle.}
{147}{}{Gurg, ladal spaf!}
{148}{}{TAK!}
{149}{}{Doof? Ganya kulk zar!}
{150}{}{Správnì - poslouchat velikána, èlovìèe. Tohle jsem pøedpokládal. Co mohu pro Vás udìlat, ó velikáne?}
{151}{}{Chlape, to je nìco. Bomba, já jsem Doofus a mám na starosti hlídání aut, co sem lidi pøivezou, ale, no víš, obèas... potøebuju nìjakı vìci a trochu penìz navíc, chápeš?}
{152}{}{Jo, jasnì. No, obèas jsem švorc a mám svı potøeby, rozumíš, tøeba, kdy se cejtím pod psa, tak musím vyrazit na pár panákù a pokecat si s Merkem.}
{153}{}{Øeknu ti, Merk je fakt borec. Je u nìj k dostání spousta zajímavejch vìcièek. Nìkdy mì nechá pøespat v "Nevydìlanı kùi" po zavíraèce. Ale pak za to ode mnì vdycky nìco chce.}
{154}{}{No dìlám to - hele, ty barvy, hele!  Merk po mnì chce obèas nìjakı vìci z aut, kterı mám hlídat. Ale já si s ním pohrávám!}
{155}{}{Hele, beru to jenom z aut, za jejich hlídání jsem nedostal zaplaceno. Myslí si, e okrádám svoje zákazníky, ale to není pravda. Hele, u musím skonèit tlachat Rád vidím vìci...záøit, jo kámo. Všechno je to o záøení.}
{156}{}{Dej mi všechny své vìci.}
{157}{}{Øekni mi všechno, co víš.}
{158}{}{To staèí, u nic dalšího nepoberu.}
{159}{}{Och, jenom u dr hubu, ty tupoune!}
{160}{}{Báj-báj.}
{161}{}{Ach, to víte. Obèas ledacos zaslechnu. Zaslechnu toho ale hodnì; nemohu si to všechno správnì pamatovat.}
{162}{}{$50 doláèù ti to v hlavì jistì správnì poskládá.}
{163}{}{Vzpomeò si nebo ti urazím tvou blbou hlavu.}
{164}{}{Vymáèkni se. Nemám èas se zahazovat s takovou troskou.}
{165}{}{To je správné èlovìèe. Zajdìte za Merkem. Ten vdycky dostane co chce.}
{166}{}{Jdi báj-báj!}
{167}{}{Oh èlovìèe, to jste šláp vedle! Merk nebude tímhle zrovna nadšen a to uslyší.}
{168}{}{Nashle, ty jedna feácká palice}
{169}{}{Okej! Hele byli to Merkovi lidé. Vèera v noci kradli auta. Poptejte se kolem a moná na nì narazíte.}
{170}{}{Vy lete a zabijete mne.}
{171}{}{Nelu vám. Klidnì se vrate, jestli to nebude pravda.}
{172}{}{Jistì.  Jsem z Vás celı vystrašenı.}
{173}{}{$50 doláèù ti to v hlavì jistì správnì poskládá.}
{174}{}{Vyli mi, hlupáku.}
{175}{}{Dej mi pokoj. Odcházím.}
{176}{}{Potøebujete ohlídat auto? ádnı problém. Od toho tu jsem.}

{177}{}{Jóó, jóó, já HLídám auta, jóó, AUTA...AUTA..jóó, auta...!}
{178}{}{LA LA LA LA AUTA, hej svìøte mi auto a BUDU HO HLÍDAT..}
{179}{}{HLÍDÁM hlídám hlídám HLÍDÁM hlídám HLÍdám HHHLÍÍÍDÁÁÁM hlídám}
{180}{}{Napíšu píseò o tom, jak tu hlídám auta}
{181}{}{Auta AAUTA AUTA auta KÁÁRY KKKÁRY vozy kozy}
{182}{}{Kozy?! A proè ne, kozy mùu hlídat taky. Kadı má pøece nìjakou KOZU!!}
{183}{}{MÁM RÁD KOZY, TO SLOVO SE VYSLOVUJE SKORO STEJNÌ JAKO VOZY A OBOJE JE MOHU HLÍDAT!}
{184}{}{Máte rádi svoje auta a já vám je STØEÍM jako jestøáb.}
{185}{}{Nikdy neopustím svoje místo a poøád hlídám. Lidé sice nìkdy remcají, ale já stále støeím}
{186}{}{Jóó, jsem ádanı. JÓÓ, JSEM ÁDANİ, jóó, jo.}

{187}{}{Jistì, frájo, ber vše.}