#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Velký chlápek, velká zbraò - stále tu postává. Stráž.}
{101}{}{Nehybná stráž.}
{102}{}{Má na èele otrokáøské tetování, které ho nedìlá o mnoho veselejším.}
{103}{}{Promluv si s panem Vortisem, ne se mnou.}
{104}{}{Uhh...}
{105}{}{Máš otázky? Promluv si s Vortisem.}
{106}{}{Jestli chceš dìlat potíže, tak ty tu øeším já. Rozumíš?}
{107}{}{Dobøe, jak chceš - hééj, máme zde vetøelce.}
{108}{}{Zvoòte na poplach! Vetøelec v našich prostorách!}
{109}{}{Pane Vortisi - banditi!}
{110}{}{Och, tak tohle byla velká chyba.}
