#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Vidíš muže s chladným pohledem. Pod paží má zavìšený samopal.}
{101}{}{Otrokáøský dozorèí.}
{102}{}{Podle jeho tetování vidíš, že se jedná o otrokáøe. Vypadá to, že má dozor nad strážemi tady kolem.}
{103}{}{Co jsi k èertu zaè? Nìjaký lupiè?}
{104}{}{Tak NCR už zaèíná vysílat reformátory! Na takový tu mám speciální lék.}
{105}{}{Vortisi, máme tu vetøelce!}
{106}{}{Stráže! Poplach!}
{107}{}{Co tu chceš?}
{108}{}{Kurg?}
{109}{}{Co je tohle za místo?}
{110}{}{Posílají mì Rangeøi.}
{111}{}{Hledám majitele.}
{112}{}{Klaním se bratøe, mám jen nìkolik otázek.}
{113}{}{Sorry, špatòáku.}
{114}{}{Pokraèuj v chùzi a vypadni. Takových tupých strážcù tu mám hromady!}
{115}{}{Máš nìco s hlavou, nebo blbì vidíš? Tohle je ohrada pro otroky. Jestli chceš vìdìt víc, promluv si s Vortisem.}
{116}{}{Tak ty tak, jo? OK, odsud tì ale vynesou v pytli.}
{117}{}{Tak to chtìj Vortise, takový starý chlápek.}
{118}{}{Díky. Podívej, pøipadáš mi jako celkem chytrý chlap. Vsadím se, že mi odpovíš na pár otázek}
{119}{}{Starý chlápek, jo? Okej.}
{120}{}{No, když už spolu mluvíme, nemohu øíct ne. Co potøebuješ?}
{121}{}{Díky, cizinèe.}
{122}{}{Jen pro tvou informaci - vím toho víc, než nakolik si mì Vortis cení.}
{123}{}{Udìlal jsem toho daleko víc, než by mohlo mnoho lidí jen tušit. Mám rád tuhle práci. Je pohodlná a snadná.}
{124}{}{Cokoliv.}
{125}{}{Kdy se míníte vypoøádat s tìmi Rangery?}
{126}{}{Hledám Vault 13. Neslyšel jsi o nìm nìkdy?}
{127}{}{Neslyšel jsi nìkdy o vìci zvané GECK?}
{128}{}{Nevíš nìco o organizaci zvané Enkláva?}
{129}{}{Sháním práci. Nevíš o nìkom kdo najímá?}
{130}{}{Zapomeò na to. Už tì nechci zdržovat.}
{131}{}{Ti bastardi mi zabili bratra a pak øekli, že to bylo pro dobro ostatních lidí!  Chci je všechny dostat. Jestli ti mùžu pomoci, promluv si s Vortisem.}
{132}{}{To mi zní jako dobrý nápad.}
{133}{}{Vortis, ano? Jsi pramen moudrosti. Co ještì víš?}
{134}{}{Správnì. Myslím, že to pùjdu udìlat hned teï.}
{135}{}{Asi každý slyšel o Vaultu 13. Když jsem byl ještì malé dítì, tak jsme po nìm s kamarády mockrát pátrali. Pøedpokládali jsme, že je na východ odsud, ale nikdy jsme ho nenašli.}
{136}{}{Hmmm, jistì jste pøitom hodnì zkusili. Mám spousty dalších otázek, když toho tolik víš.}
{137}{}{No, už budu muset jít.}
{138}{}{GECK? Když se vrátím do dob svých studií o Vault technologiích, vzpomínám si, že jsem o nìèem takovém èetl. Pravdìpodobnì každý Vault tehdy jeden dostal a poèítalo se, že až lidé vyjdou zpìt na povrch, tak ho použijí. Napøíklad v Shady Sands zaèali také - s GECKem. Tak, pomohlo ti to k nìèemu?}
{139}{}{Ty jsi studoval Vault technologie? Zajímavé. Mám na tebe další otázky.}
{140}{}{Well, I got to go.}
{141}{}{Enkláva...hmmm. No, máme tu ve mìstì doktora, Henry si øíká. Jednu noc, když byl opilý, zaèal cosi blábolit o nìjakých chlápcích a øíkal jim nìjak jako... Enklávové.}
{142}{}{To je asi tak vše co mne zajímalo. Jsi opravdu skvìle informovaný èlovìk.}
{143}{}{To je všechno. Už tì nebudu obtìžovat. Díky.}
{144}{}{Já, já jsem tu odjakživa na hlídání - potíž je v tom, že nikdo už nechce najímat otrokáøe. Vortis, mùj šéf, má však nìco velmi tajného.  A jinak, ve mìstì, ranèeøi ve Stockmenovì asociaci, vždycky rádi nìkoho pøijmou.  Dorothy také ráda pøijme pomocnou ruku v elektrárnì, pokud máš potøebné zkušenosti. A slovy prezidentky Tandi - "sháním specialistu".}
{145}{}{Teda, víš toho hodnì. Celý den by se tì dalo zpovídat.}
{146}{}{Jo, zaøídím se pøesnì podle tìch rad.}
{147}{}{Dej toho... však víš... ode mì pryè, oukej?}
{148}{}{Bez problémù. Je zde však ještì nìco jiného, co chci vìdìt.}
{149}{}{Dám si pozor, neboj.}