#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Vidíš nebohé, zuboené tìlo.}
{101}{}{Stále nevidíš nic jiného ne nebohé a zuboené tìlo.}
{102}{}{A se díváš sebelíp, opravdu nevidíš nic ne nebohé zuboené tìlo. Proè tak strnule hledíš?}
{103}{}{Pomoz mi! Prosím, neotáèej se ke mnì zády.}
{104}{}{Mùj pán mi øíká, e se nemám vybavovat s kadım.}
{105}{}{Nìco ti povím - mùj pán je opravdu hajzl.}
{106}{}{Opravdu, nevím proè nebıt otrokem. Je to dobrı ivot - dostanu najíst a nìkdy mì i pochválí paní.}
{107}{}{Vypadni! Nech mì bıt!}
{108}{}{Ty! Musíš nám pomoci! Pøemoci tyrany!}
{109}{}{Nebav se se mnou! Nemám zájem o další bití.}
{110}{}{Otroctví je jenom takovı pojem. Konec koncù, je èlovìk opravdu volnı?}
{111}{}{U ne! Prosím, nechci Dùm Bolesti!}
{112}{}{Dr se ode mne dál!}
{113}{}{Zrùdo! Ty a tobì podobní mi tohle udìlali!}
{114}{}{Soud nejvyšší o tobì rozhodne!}
{115}{}{Poslouchám kadé tvoje slovo.}
{116}{}{Budu pokornım dìdicem zemì.}
{117}{}{Nedìlám potíe. Jsem dobrı otrok.}
{118}{}{Svoboda! Sladká, poehnaná svoboda!}
{119}{}{Podívej co máš na svìdomí - mám úplnì znièenı ivot!}
{120}{}{Nepøestanu s tím. Uteèu. Nikdo mì nemùe chytit.}
{121}{}{Sakra! Selhal jsem - tak pojï a dora mì, naè èekáš.}
{122}{}{Kam se to øítím? Co teï udìlám?}
{123}{}{Mnohokrát dìkuji. Teï zase já proliji krev nìjakého otrokáøe.}
{124}{}{Stále tomu nemohu uvìøit - svoboda!}
