#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Vidíš vychrtlého starého mue s tukou za uchem a brılemi na špièce nosu.}
{101}{}{To je Vortis, majitel této ohrady pro otroky.}
{102}{}{Má asi tak tøi zuby. Jeho prsty a košile jsou potøísnìny modrım inkoustem. Na èele se mu tkví hodnì zašlé otrokáøské tetování.}
{103}{}{Take, co tu chceš?}
{104}{}{Bratøe, vítej ve Vortisovì rezidenci. Mohu ti bıt s nìèím nápomocen?}
{105}{}{Zaèínáš mnì jít na nervy.}
{106}{}{Tohle místo je mùj pozemek a já, Vortis, tu vedu poèestnı a zákonem schválenı podnik, bez ohledu na to, co ti o tom kdokoliv v NCR navykládal. Protoe uvnitø NCR není otrokáøství povoleno, hlídám tu otroky jejich pánùm dokud si nevyøídí svı kšefty ve mìstì.}
{107}{}{Pomalu chápeš nebo co? Tohle je ohrada pro otroky. Povolení mám.}
{108}{}{}
{109}{}{Mám jenom nìkolik otázek.}
{110}{}{Hledám práci.}
{111}{}{Eh?}
{112}{}{Toto nebıt kùlna? My tedy jít.}
{113}{}{Co je tohle za místo?}
{114}{}{Nic. Tady jsem špatnì.}
{115}{}{Ó, podívejme - uèinìná dobrota na dvou nohách, se k nám zašla podívat. Hoši, vyprovoïte tohodle svatouška pryè z mıho dohledu!}
{116}{}{Seru na to.}
{117}{}{Nue?}
{118}{}{Hedám Vault 13.}
{119}{}{Nemáte tu GECK?}
{120}{}{Co mi mùete øíct o tomto mìstì?}
{121}{}{Ty otrokáøkej sviòáku! Øekni mi jedinı dùvod, proè tì nemám hned oddìlat?}
{122}{}{Povídá se tu o nìjakıch chlápcích - New Californští Rangeøi - si prı øíkají. Nemáte s nimi nìjaké potíe?}
{123}{}{Myslíte, e se mohu porozhlédnout?}
{124}{}{Práci? Mno...nìco by se moná našlo. Øíká ti nìco pojem "New Californští Rangeøi"?}
{125}{}{Ano.}
{126}{}{Ne.}
{127}{}{Seru na tebe. Hoši, vyprovoïte toho otrapu.}
{128}{}{Vyli mi...!}
{129}{}{Vault 13!? Vypadni odsud. To zatracenı místo je vımysl. Vault 13, je leda v mı prdeli.}
{130}{}{Další otázka...}
{131}{}{Hmm, dìkuju za nic.}
{132}{}{E? Coe? A u je to cokoliv. nemám to.}
{133}{}{Další otázka...}
{134}{}{Tak dìkuju za nic.}
{135}{}{New California Republic - nic ne ukáznìní tıpkové a obchodníci. Vlezlo jim nìjak na mozek otrokáøství a otroci, ale co k èertu, aspoò mám kšeft.}
{136}{}{Další otázka...}
{137}{}{Díky, u pùjdu.}
{138}{}{Máš špatné informace. Nemám potíe s nikım - a u vùbec ne s Rangery. A všechno tady kolem co vidíš je legální, take na mì nemùeš nic mít.}
{139}{}{Další otázka...}
{140}{}{Kdy to øíkáte vy. Pùjdu.}
{141}{}{Jo, moná mám nìjaké potíe ohlednì Rangerù. Hledáš práci?}
{142}{}{Ano.}
{143}{}{Ne.}
{144}{}{Ne, nebudeš tady èmuchat kolem, zasranej chytráku! Tady nejsi v muzeu!}
{145}{}{Další otázka...}
{146}{}{Jsi na mì moc nedùtklivı. Radìji pùjdu.}
{147}{}{Dobrá tedy. Víš, existuje urèitá skupina lidí, která by mi mohla zpùsobit nemalé potíe. A hroznì by nám pomohlo, kdybychom mìli mapu jejich skrıší smìrem na sever - New Reno, Klamath, a tak dál. Jsem ochoten dát i øeknìme, $500, za tu mapu. Co ty na to? Seeneš mi ji?}
{148}{}{Jistì.}
{149}{}{To si nemyslím.}
{150}{}{Pak ti to tedy povím. Tihle Rangeøi si usmysleli, e naprosto vymítí otrokáøství a otroky - násilím. A zpùsobili tak u tìce pracujícím lidem hodnì potíí.}
{151}{}{Pracují tajnì, zvláštì na severu.}
{152}{}{ANO, musím ti to snad hláskovat? Chytají otrokáøe, a pak je enou v houfech a dopravují je dolù na jih do NCR, kde je otroctví zakázáno. Máš zájem?}
{153}{}{Tohle není o nìjakém "a"! Bereš tu práci nebo ne?}
{154}{}{A?}
{155}{}{A co mám pøesnì udìlat?}
{156}{}{Bezva. Seeò mi tu mapu, budu zde.}
{157}{}{Kde bude nejlepší po té mapì zaèít pátrat?}
{158}{}{Okej, ale mám ještì pár otázek.}
{159}{}{Jdu na to. Uvidíme se pak.}
{160}{}{Jak to mám k èertu vìdìt!? Kdybych to vìdìl, tak u ji dávno mám, nemyslíš? Hele, ve mìstì je myslím vìzení. Najdi ho a tøeba tì to navede co dál.}
{161}{}{Jen nìkolik málo otázek.}
{162}{}{Dobrá. Vrátím se.}
{163}{}{Á jsi zpátky. Máš tu mapu?}
{164}{}{Ano.}
{165}{}{Ne}
{166}{}{Poøád èekám a dodìláš svùj první úkol!}
{167}{}{Oh ano, zapomeò na to}
{168}{}{Ne, od té doby co máš za sebou svùj job, fakt ne. Díky.}
{169}{}{Jenom otázeèku nebo dvì.}
{170}{}{Bez problému. Nashle.}
{171}{}{Dobrá práce. Teï bude pro tebe lepší se nenápadnì vypaøit, ne to tìm Rangerùm dojde.}
{172}{}{Skvìlı kšeft.}
{173}{}{Nepotloukej se tu poøád, blbèe! Všichni budeme podezøelí.}
{174}{}{Dobøe, díky za radu.}
{175}{}{Co to má doprdele znamenat? Stráe! Máme tu vetøelce!}
{176}{}{Jdi ještì o kus dál a provìtrám ti faldy. Rozumíš?}
