#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Vidíš stráž.}
{101}{}{Vidíš Granta, stráž.}
{102}{}{Vidíš stráž. Jeho zbroj a zbranì jsou ve výteèném stavu.}
{103}{}{Soukromý pozemek, jdi prosím dál.}
{104}{}{Kdo tady bydlet?}
{105}{}{Ok, my jít...}
{106}{}{Promiòte prosím, kdo zde žije?}
{107}{}{Ano, odcházím.}
{108}{}{Chceš odejít?}
{109}{}{Ano, chtít odejít.}
{110}{}{Ne, zùstat.}
{111}{}{Ano, potøebuji hned jít.}
{112}{}{Ne, budu se tu ještì chvíli potloukat.}
{113}{}{Tohle je Westinùv Ranè, domov radního Westina.}
{114}{}{Potøebovat ho vidìt.}
{115}{}{Ok. Nashle.}
{116}{}{Potøebuji vidìt radního, prosím.}
{117}{}{Aha. Dobøe, že to vím.}
{118}{}{Co pøesnì chceš od pana Westina?}
{119}{}{Potøebovat práci.}
{120}{}{Promluvit s ním.}
{121}{}{Ée...}
{122}{}{Ale... nic.}
{123}{}{Hledám nìjakou práci a prý zde najímáte.}
{124}{}{Chci si promluvit s panem Westinem.}
{125}{}{Už nic, pøijdu nìkdy jindy.}
{126}{}{Hmm... mám takový dojem, ...ano byla by tu nìjaká práce. Dobøe, mùžeš jít dovnitø. Ale bìda, jestli s tebou budou nìjaké potíže. Budu tì mít stále na oèích.}
{127}{}{Dìkovat.}
{128}{}{Díky.}
{129}{}{Pan Westin si rozhodnì nemíní vykládat s každým, kdo se jen tak vynoøí z ulice. Jestli s ním nemáš dohodnutou nìjakou konkrétní záležitost, pak ti navrhuji odejít.   Øíkal jsem odejít, prosím.}
{130}{}{Vyøízeno.}
{131}{}{(vzdych) Pan Westin má prý slabost pro lidi jako jsi ty. Mùžeš vejít.}
{132}{}{Dìkovat ti.}
{133}{}{Áno, áno. Jsem tak nìco mezi tím.}
{134}{}{Hej, vypadni odsud!}
{135}{}{Napøed se zeptej, než si zaèneš hrát s vìcmi co ti nepatøí.}

{136}{}{Zdravím. Potøebuješ vidìt znovu pana Westina?}
{137}{}{Ano.}
{138}{}{Ne.}

{139}{}{Mít pro pana Westina nìjaká vìc z Vault City.}
{140}{}{Mám pro pana Westina nìco z Vault City.}
{141}{}{V poøádku, mùžeš jít. Ale žádné potíže, rozumíš. Budu tì pozorovat.}
{142}{}{Bez øádné obchodní záležitosti nemáš na ranèi co dìlat.}
