#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Vidíš muže obleèeného v bohatì zdobených farmáøských šatech.}
{101}{}{To je radní Westin.}
{102}{}{Støíbrné prsteny, støíbrná pøezka na opasku, za pasem dobrá pistole, tenhle chlápek má jistì hodnì penìz a je sám sobì svým pánem.}
{103}{}{Jmenuji se Roger Westin. Nemùžeš si sem jen tak pøijít a motat se tu. Co chceš?}
{104}{}{Zase ty? Co chceš?}
{105}{}{Co chceš?}
{106}{}{Uuh...}
{107}{}{My hledat Vault 13? Pomoci?}
{108}{}{Hledám Vault 13. Mùžete mi pomoci v mém pátrání?}
{109}{}{Ta špinavá práce pro vás, je hotova.}
{110}{}{Špatná vìc pøicházet. My postrašit je pryè. Bù-bùù v bezpeèí.}
{111}{}{Co se týká toho vašeho problému s brahmínami -- všechno co musíte udìlat, je zøídit tam hlídku. Staèí jeden muž a nemusí vùbec nic dìlat, staèí jen, že tam bude. Vím, že to zní divnì, ale vìøte mi, bude to fungovat. Ehmm...nemluvil jste pøedtím o nìjaké odmìnì?}
{112}{}{Jsem tu kvùli práci.}
{113}{}{První Obèanka Lynett posílá srdeèné pozdravy. Nìco pro vás má.}
{114}{}{Posílá mne Bishop.}
{115}{}{Pardon.}
{116}{}{To má být vše? Promluv si s mým pøedákem, Felixem.}
{117}{}{Nerozumíte mi. Jsem zde kvùli práci.}
{118}{}{Šerif øíkal, že si mám promluvit s vámi osobnì.}
{119}{}{Tak dobrá. Udìlám to.}
{120}{}{Budu hádat. Co ti nasliboval - peníze, drogy, nebo sex? Nevadí. Nikdy nic z toho nedostaneš.}
{121}{}{Co tím myslíš?}
{122}{}{Zmlkni.}
{123}{}{Och - prostoduchý chudáèek. To je smutné. Musí být tìžké nosit tento køíž. 
Poslouchej - jdi si promluvit s Fe-li-xem. Dá ti nìjakou práci. Rozumíš?}
{124}{}{Eh-heh.}
{125}{}{No, co myslíš? Už teï toho o nìm víš pøíliš. Co když pùjdeš do NCR a zradíš ho - nebo ho zaèneš vydírat? Pro nìj máš cenu jen jako mrtvola. Ale možná mám pro tebe lepší nabídku.}
{126}{}{To jako co?}
{127}{}{Nevìøím ti.}
{128}{}{Bishopa z toho radìji vynechme. Zaplatím ti hotovì tolik co nabízel, plus 50% navrch. Kolik to bylo?}
{129}{}{(potøebuju informace od Chrise)}
{130}{}{(Avellona, tak je to)}
{131}{}{Skvìlé.}
{132}{}{Dohodnuto.}
{133}{}{To je pro tebe moc špatné, staøíku.}
{134}{}{Tìším se až si to od tebe poslechnu. Teï si jdi odkud pøicházíš.}
{135}{}{Výbornì. Hned jsem vìdìl, že budeš ta správná osoba. Nuže, slíbil jsem ti zaplatit a nemíním porušit naši dohodu. Zde jsou peníze.}
{136}{}{Ještì nìco, co pro tebe mohu udìlat?}
{137}{}{Díky. Možná mi mùžete poradit. Snažím se najít Vault 13.}
{138}{}{Nashle.}
{139}{}{Doporuèuje tì Dumont? Tak to je potom jiná. Nìco nebo nìkdo mi v noci plení moje brahmíny. Potøebuji vypátrat co se dìje. Zajdeš se tam podívat a prošetøíš o co jde? Pøípadné škody ti uhradím.}
{140}{}{Zní to snadnì. Udìlám to pro vás.}
{141}{}{Jsem proti.}
{142}{}{Nìco nebo nìkdo mi v noci plení moje brahmíny. Potøebuji vypátrat co se dìje. Zajdeš se tam podívat a prošetøíš o co jde? Pøípadné škody ti uhradím.}
{143}{}{Zní to jako dobrý nápad. Zjistím vám to.}
{144}{}{Ne díky. Radìji si sednu na poli a budu se dívat jak vylézají krtci.}
{145}{}{Skvìlé. Felix ti øekne co a jak. A teï, mne prosím omluv.}
{146}{}{No, možná mohu. Slyšel jsem hodnì pøíbìhù o Tandi a Zakladateli. Zdá se, že jí, dávno pøed vznikem NCR, zachránil život. V každém pøípadì, legenda øíká, že strávil mnoho èasu prùzkumem Vaultu východnì odsud. A jestli to není pøímo Vault 13, pak tam možná aspoò nalezneš stopu, co tì povede dál.}
{147}{}{Ooooch. Skvìlé.}
{148}{}{Díky!}
{149}{}{Dobrá, možná mohu. Ale napøed chci nìco já od tebe. Nìco nebo nìkdo mi v noci plení moje brahmíny. Potøebuji vypátrat co se dìje. Zajdeš se tam podívat a prošetøíš o co jde? Za tu službu ti zaplatím a ještì ti povím co vím.}
{150}{}{To zní snadnì. Udìlám to.}
{151}{}{Ne díky. Døepìt na poli a èekat, až se objeví nìjakej požíraè, mi zavání nudou.}
{152}{}{Pak tedy jdi. Bylo to pìkné setkání, cizinèe.}
{153}{}{Nevím jestli ti mám vìøit... dobøe, zde je odmìna. Ale jestli k èertu lžeš, mí hoši si tì najdou. A abych se vrátil k pùvodní otázce, tak dobøe poslouchej. Slyšel jsem hodnì pøíbìhù o Tandi a Zakladateli. Zdá se, že jí, dávno pøed vznikem NCR, zachránil život. V každém pøípadì, legenda øíká, že strávil mnoho èasu prùzkumem Vaultu východnì odsud. A jestli to není pøímo Vault 13, pak tam možná aspoò nalezneš stopu, co tì povede dál.}
{154}{}{My dìkovat tobì!}
{155}{}{Díky.}
{156}{}{První Obèanka? Skvìlé, na tohle jsem už dlouho èekal. A ty jsi Obèan?}
{157}{}{Ano.}
{158}{}{Ne.}
{159}{}{A jsi dobrý Obèan, jsem si jist. Vezmi teï prosím tento holdisk a dones ho zpátky První Obèance. Je to velmi dùležité. Obsahuje informace které potøebuje, aby odhalila plány mezi NCR-New Reno.}
{160}{}{Mám pár otázek.}
{161}{}{Ano, pane.}
{162}{}{Nuže, to je vše.}
{163}{}{Mám pár otázek.}
{164}{}{Cokoliv.}
{165}{}{Práce. Myslíte--}
{166}{}{Posílá mne Bishop. Mám pro vás od nìj malou zprávièku.}
{167}{}{Mìj se a spi sladce, staøíku.}
{168}{}{Prachy, že ano. Podívej, udìláš práci a já ti za ni zaplatím. Øekneš ne a ponesou tì ven nohama napøed. Rozumíš?}

{169}{}{Ach tak. No, mìl jsem potíže s nìjakou chamradí, ale pøestali s tím. Bohužel. Zkus zajít za Felixem, jestli by pro tebe nìco nemìl.}
{170}{}{Ok, díky.}

{171}{}{Echhh.... Mám špatné srdce... nemohu popadnout...}
{172}{}{Musím ..... øøøíííci Feeellliixxoovi.}
{173}{}{Hmmm, asi mìl potíže se srdcem.}

{174}{}{AHHAHH!!! AHAHAHHAH!!! AHHAHAH!!! TO PÁLÍ!!!}
