#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Vidíš osobu v prachem pokrytých pracovních šatech.}
{101}{}{Jeden z Westinových pomocníkù na ranèi.}
{102}{}{Mùže to být jen pomocník na ranèi, ale také to mùže být nájemný vrah. Každopádnì buï pøipraven i na problémy.}
{103}{}{Domníváš se, že se tu mùžeš jen tak procházet?}
{104}{}{Jdi si promluvit s Felixem, jestli hledáš práci, cizinèe.}
{105}{}{Ach jo, ty brahmíny už mne tak nudí.}
{106}{}{Slyšel jsem, že Bishop to slíznul od našeho šéfa.}
{107}{}{Jestli si chceš s nìkým povídat, jdi za naším pøedákem, Felixem.}
{108}{}{Ty nejsi s Bishopem, nebo ano?}
{109}{}{Víme, že to byla vražda. Když chytíme hada, jeho smrt nebývá rychlá.}
{110}{}{Felix pøísahá, že za tím vším byl Bishop. Øíká, že z toho má nìkdo prachy.}
{111}{}{No, je èas se hnout dál. Všechno se tu øítí do pekla.}
