#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Vidíš seschlou enu, shrbenou stáøím.}
{101}{}{Vidíš Tandi, prezidentku NCR.}
{102}{}{Vidíš houevnatou, sebevìdomou enu. Je na první pohled jasné, e má u ostatních respekt a úctu.}

{103}{tand1}{Jsem Tandi, prezidentka NCR. Mí hoši mi øekli, e hledáš práci. Co mùeš nabídnout?}
{104}{}{Já umìt to se zbranìmi. Bıt jedním z nejlepších.}
{105}{}{Já umìt mluvit s lidmi.}
{106}{}{Já dobrá bojovník. Nakopávat zadky.}
{107}{}{Já umìt se plíit. Dostat kde potøeba. Neslyšet mne èi nevidìt.}
{108}{}{Já umìt mnoho vìcí.}
{109}{}{Uh, chtít jenom nìjaké zboí.}
{110}{}{Skvìle to umím se zbranìmi. Mohu se smìle zaøadit mezi ty nejlepší.}
{111}{}{Mohu Vám øíci jedno, madam Prezidentová - umím si vyhovoøit cestu slovy.}
{112}{}{Ovládám pìstní souboje. Rána zprava, zleva - a je to vyøešeno.}
{113}{}{Umím se dostat kamkoliv a pøitom mne nikdo neuvidí a neuslyší.}
{114}{}{Mám mnoho talentù a všechny Vám je nabízím k dispozici.}
{115}{}{Myslím, e mám zájem jen o nìjaké zboí.}

{116}{tand2}{Hmmm. Nejsi pøesnì ten typ, kterı potøebuji. Jaké mi mùeš dát záruky?}
{117}{}{Já nevìdìt. Co ten práce?}
{118}{}{Pevnì v sebe vìøit. Zvládnout to!}
{119}{}{To závisí na tom, jakou práci mi nabídnete.}
{120}{}{Ano, dùvìøuji svım schopnostem, i v sebe sama.}

{121}{tand3}{Vypadá to, e budeš pøesnì ten koho hledám.}
{122}{}{Dobrá. Jak moci pomoct?}
{123}{}{Vıbornì, v èem Vám mohu pomoci?}

{124}{tand4}{Potøebujeme nìjaké souèástky do poèítaèe z naší staré základny - Vaultu 15. Problém je v takzvanıch samozvanıch usedlících, kteøí nikomu nedovolí vstoupit. Je potøeba nìkoho pøesvìdèit, aby nás vpustil dovnitø - nebo nám pøinesl ty souèástky. Pøijímáš tu práci?}
{125}{}{Mì nelíbit se to. Radìji jít.}
{126}{}{Já udìlat to.}
{127}{}{Já tam bıt. Usedlíci chtít vyjednávat. Vy uèit, vy pomoci, oni pak dát Vault.}
{128}{}{Já tam bıt. Já získat souèástky.}
{129}{}{Já tam bıt. Usedlíci chtít vyjednávat. Vy uèit, vy pomoci, oni pak dát Vault. Zde pøinést ty souèástky.}
{130}{}{Promiòte, ale tohle se mi zrovna moc nezamlouvá.}
{131}{}{Bude mi potìšením, Vám pomoci.}
{132}{}{Zajímá mne to, ale jaká bude odmìna?}
{133}{}{Mnoho z tìchto záleitostí s nimi mám ji probráno. Jsou ochotni vyjednávat. Pomùete jim stát se sobìstaènımi a oni vám na oplátku poskytnou pøístup do Vaultu.}
{134}{}{Ji jsem tam byl a mám souèástky, které potøebujete.}
{135}{}{Mnoho z tìchto záleitostí s nimi mám ji probráno. Jsou ochotni vyjednávat. Pomùete jim stát se sobìstaènımi a oni vám na oplátku poskytnou pøístup do Vaultu. Souèástky však ji mám.}

{136}{tand5}{Hromy a blesky... tvoje volba - ale jestlie si to rozmyslíš...}
{137}{}{Ok.}

{138}{tand6a}{Dobrá tedy. Udìlej vše jak máš, a odmìna tì nemine.}
{139}{tand6b}{Ach boe, vím, e moná nedìlám dobøe, ale... udìlej to - pokud rozumíš tomu, o èem jsem tu mluvila.}
{140}{}{Ok. Já jít.}
{141}{}{Já mít otázky.}
{142}{}{V poøádku. Jdu na to.}
{143}{}{Mám na Vás pár otázek.}

{144}{tand7a}{Dobøe, udìlám si na tebe trochu èasu.}
{145}{tand7b}{Co chceš vìdìt?}
{146}{}{Co mi moci povìdìt o Vaultu 15?}
{147}{}{Proè nevyjednávat s usedlíky?}
{148}{}{Víte kde Vault 13?}
{149}{}{Já hledat GECK. Mít?}
{150}{}{Co vìdìt o New Renu?}
{151}{}{Co vìdìt o Franku Westinovi?}
{152}{}{Co vìdìt o Carlsonovi?}
{153}{}{Starší vykládat pøíbìh. Povídat o Zakladateli, Tandi. Ty ona Tandi?}
{154}{}{Tohle bıt to Šejdısendz o kterém mluvit Starší?}
{155}{}{To bıt vše. Nyní já jít.}
{156}{}{Co mi mùete povìdìt o Vaultu 15?}
{157}{}{Proè jste u dávno nezkoušeli s usedlíky vyjednávat?}
{158}{}{Nevíte kde je Vault 13?}
{159}{}{Hledám GECK. Nevíte o nìjakém?}
{160}{}{Co mi mùete povìdìt o New Renu?}
{161}{}{Co mi mùete povìdìt o Franku Westinovi?}
{162}{}{Co mi mùete povìdìt o Carlsonovi?}
{163}{}{Starší mi vykládala pøíbìh o Zakladateli a nìjaké Tandi. Vy jste ta Tandi?}
{164}{}{Je tohle Šejdısendz o kterém mluvila Starší?}
{165}{}{To je zatím vše. Pùjdu.}

{166}{tand8}{Leí vıchodnì odsud. Je to bıvalı váleènı kryt. Mnoho rodin v NCR pochází odtamtud, take je po právu náš.}
{167}{}{Povìzte víc.}
{168}{}{Pokraèujte.}

{169}{tand9}{Nìkolik let pøedtím se tam pøistìhovalo pár cizincù a vybudovalo si na povrchu pár chatrèí. Øíkají si "Usedlíci". Nejsou ale nic víc ne psi u labu. Oni sami se do Vaultu dostat nemohou, ale nás do nìj taky nepustí.}
{170}{}{Já mít další otázky.}
{171}{}{Hmm, uvidíme. Potøebuji se Vás zeptat na pár dalších vìcí.}

{172}{tand10}{Zkoušela jsem. Vyslala jsem tam postupnì nìkolik lidí, ale s vıjimkou nìkolika prvních, se po èase pøestali vracet. Nemohu však nijak prokázat, e za to mohou Usedlíci. Mí hoši dokázali jednoho z nich chytit, ale nechce mluvit. Je zavøenı v centru.}
{173}{}{Potøebovat vìdìt další.}
{174}{}{Pár dalších otázek, prosím.}

{175}{tand11}{Dobrá, do toho. Nemùu si tu s tebou vykládat celı den.}
{176}{}{Ok, já spìchat.}
{177}{}{Ano, jen v rychlosti, prosím.}

{178}{tand12}{Víš, s tím oblekem co máš na sobì, jsem se u jednou setkala.}
{179}{}{Oblek bıt ve vesnici dlouho, moc dlouho. Patøit Zakladateli, zakladateli kmene.}
{180}{}{Tento oblek byl v naší vesnici od zaèátku. Patøil Zakladateli, zakladateli našeho kmene.}

{181}{tand13}{Jsi jen pøelud nebo jsi skuteènı? Jestli tu oba mluvíme o tom samém èlovìku, tak ten mi zachránil ivot. (povzdech) Pak zmizel. Vdycky, kdy si zaènu myslet e to byl jen sen, jdu se podívat na tu sochu tam venku.}
{182}{}{Sochu?}

{183}{tand14a}{Ano sochu. Za pomoc proti nájezdníkùm. Vyhnuli se Shady Sands poté, co jsme získali èas se na nì pøipravit. Stal se naším hrdinou... i kdy jsme mu nevìøili, e pochází z Vaultu 13.}
{184}{}{Já pamatovat. Moci vìdìt další?}
{185}{}{Budu si to pamatovat. Mohu se zeptat na další?}

{186}{tand15}{Vault 13? Proè se na nìj ptáš?}
{187}{}{Zajímat mne.}
{188}{}{Já Vyvolenı. Potomek Zakladatele.}
{189}{}{Eh... jenom tak. Já ptát se na jiné otázky.}
{190}{}{Povídá se o nìm mnoho pøíbìhù a zajímá mne to.}
{191}{}{Jsem Vyvolenı mé vesnice. A jsem potomek Zakladatele.}
{192}{}{Zapomeòte na to. Jenom mne to tak zajímalo.}

{193}{tand16}{Je to jen hloupı mıtus jako tøeba uranové doly. Já se kdysi opravdu setkala s cizincem, kterı tvrdil, e je odtamtud. Mnoho lidí ale zemøelo, kdy potom zkoušeli ten Vault najít.}
{194}{}{Zakladatel opravdovı. Já bıt potomek.}
{195}{}{Já potøebovat vìdìt jiné vìci.}
{196}{}{Zakladatel opravdu il. Jsem jedním z jeho potomkù.}
{197}{}{Hmmm. Chci se zeptat na nìco jiného.}

{198}{tand17}{Geck? Jako ta ještìrka? Ty tu máme všude.}
{199}{}{Ne ještìrky... ech, zapomenout na to. Já se ptát ještì na nìco jiného.}
{200}{}{Ne, ne ty zatracenı ještìrky... eh, zapomeòte na to. Chci se zeptat na nìco jiného.}

{201}{tand18}{New Reno? To je s odpuštìním zatracenı kıbl brahmíních plivancù. Místo vší neøesti. Budeme s nimi mít potíe, protoe my chceme tuto zemi sjednotit. Kongres je s tím srozumìn.}
{202}{}{Co vìdìt o Bishopovi?}
{203}{}{Povìdìt nìco o Kongresu?}
{204}{}{Já chtít ptát se nìco jiného.}
{205}{}{Co víte o Bishopovi?}
{206}{}{Povìzte mi nìco o Kongresu.}
{207}{}{Mohu se zeptat ještì na nìco jiného?}

{208}{tand19}{No, jsem ochotna s hadem mluvit, ale nechtìj po mnì, abych si ho høála na prsou. A jestli ho nìkdy uvidíš, klidnì mu to mùeš øíct.}
{209}{}{Já slyšet, e NCR jednat s Bishopem.}
{210}{}{Ok. Já chtít vìdìt víc.}
{211}{}{Povídá se, e NCR jedná s Bishopem.}
{212}{}{Ok, a teï k dalším vìcem.}

{213}{tand20}{My tu nemáme ádná tajemství. Dohodli jsme s New Reno spojenectví v NCR. Mìlo by to pomoci pøitáhnout i další místa, jako tøeba Vault City.}
{214}{}{Dob-rá.}
{215}{}{V poøádku.}

{216}{tand21}{Hodnì lidí by rádo, abychom spolupracovali s New Reno a je jim jedno jakım zpùsobem. Ale lidé jako Westin a ostatní ranèeøi obviòují New Reno z napadání obchodních karavan.}
{217}{}{Humph.}
{218}{}{Kdo Westin?}
{219}{}{Aha.}
{220}{}{Co je zaè tenhle Westin?}

{221}{tand22}{Kongresman Westin? Jeden z nejvìtších chovatelù dobytka široko daleko. Jeho pozemky se nacházejí v západní èásti mìsta. Jenom, a s ním budeš mluvit, nenaráej nijak na New Reno - to ho vdycky nadzvedne. Jestlie si chceš najít stálou práci... ale to není tvùj pøípad, nebo ano?}
{222}{}{Ne díky.}

{223}{tand23}{Tvrdohlavı jako mezek... ale dobrı èlovìk. Proè?}
{224}{}{Já zajímat o práci.}
{225}{}{Já zajímat o práci.}
{226}{}{Zajímám se o práci.}
{227}{}{Zajímám se o práci.}

{228}{tand24}{Zdá se mi, e sis toho nabral u dost.}
{229}{}{OK. Zapomeòte.}
{230}{}{No, to máte pravdu.}

{231}{tand25}{Kdy Westin zemøel, Carlson se zavrtal v jeho kanceláøi. Nejspíš ho vùbec neuvidíš, ale mùeš si promluvit s jeho hochy.}
{232}{}{Ok.}

{233}{tand26}{Poslouchej. Mnoho lidí, vèetnì mne, má starého Carlsona rádo. Dokonce i kdy s ním nesouhlasíme v otázce New Reno. Pokud se mu nìco stane, nebude nám to lhostejné. Kadı kdo si myslí, e by se mu ilo lépe, kdyby bylo po nìm, dìlá velkou, moc velkou chybu. Je ti to jasné?}
{234}{}{Ah. Já rozumìt.}
{235}{}{Ano, rozumím.}

{236}{tand27}{Ach, to bylo tak dávno! Sotva si pamatuji, kdo jsem byla - jen naivní holka.  Take vy mu øíkáte Zakladatel - je ještì stále naivu?}
{237}{}{On mùj pøedek. Jeho duch s námi. ít ve mnì.}
{238}{}{Zakladatel je mùj pøedek. ije ve mnì.}

{239}{tand28}{Ano... je tu jistá podoba - také z tebe vyzaøuje jeho oheò. Vdycky jsem se bála, e skonèil jako kostra nìkde v poušti.}
{240}{}{Já chtít slyšet Váš pøíbìh.}
{241}{}{Chci slyšet Váš pøíbìh.}

{242}{tand29}{(vzdych) To jsem ještì byla pìkná a mladá, kdy jsme se setkali. Tenkrát moji vesnici ohroovala banda nájezdníkù - øíkali si Khanové - a ti mne unesli. Vypadalo to se mnou moc špatnì, kdy tu se náhle objevil cizinec, kterı mì zachránil. Váš Zakladatel.}
{243}{}{Zakladatel zaít hodnì takovıch dobrodruství.}
{244}{}{Zakladatel zail mnoho takovıch dobrodruství.}

{245}{tand30}{Vdycky jsem mu to závidìla. Chtìla jsem ivot plnı dobrodruství, ale zùstala jsem zde a pøevzala starostování po svém zemøelém otci. Znamenalo to vedení tohoto místa a pozdìji vybudování NCR. Myslím, e ten mùj ivot za tohle pøece jenom stál.}
{246}{}{Starší by velmi šastná vìdìt, e Vy poøád naivu. Prominout, ale muset se ptát na další.}
{247}{}{Starší by byla velmi šastná, vìdìt, e jste stále naivu. Omlouvám se, ale potøebuji vìdìt další vìci.}

{248}{tand31}{Bylo to Shady Sands. Mnoho lidí teï øíká tomuto místu NCR. New California Republic - pùsobivı název, e?}
{249}{}{Povìdìt o NCR.}
{250}{}{Chtít vìdìt nìco jiného.}
{251}{}{Povìzte mi nìco o NCR, prosím.}
{252}{}{Chci se zeptat na nìco jiného.}

{253}{tand32}{Jéje, to bych mohla mluvit donekoneèna a tolik èasu já nemám. Tady, vezmi si holodisk s historíí NCR. Je to tam sepsáno mnohem obšírnìji, ne bych ti to kdy povìdìla já.}
{254}{}{Uh, dìkuji.}

{255}{tand33}{Tak koneènì dostali rozum. No, mohu popohnat Kongres, ohlednì dodávek a technického vybavení. Urèitì se tedy mùeme dostat do Vaultu?}
{256}{}{Já potvrdit. Já všechny odtam vykopat.}
{257}{}{Docela urèitì. Byli tam nìjací nezvaní nájemníci, ale teï si nejspíš líou rány.}

{258}{tand34}{Stále tvrdím, e za dobøe odvedenou práci se má i dobøe zaplatit. Mùj poboèník to s tebou vyøídí.}
{259}{}{Já najít problém. Podívat vy se na disk. Bıt tu špión v NCR.}
{260}{}{Chtít vìdìt jednu vìc. Co kdyby já øíct, e najít Vault 13?}
{261}{}{Obávám se, e tu je další problém. Kdy se podíváte na tento holodisk, zjistíte, e máte v NCR zvìda.}
{262}{}{Ještì jedna vìc. Co kdy Vám øeknu, e jsem našel Vault 13?}
{263}{}{Díky.}

{264}{tand35}{Zatracenì, jediná osoba, která o tom vìdìla všechno byl Feargus! Nic mne teï zrovna nenapadá, ale moná Gunther by mohl nìco vìdìt.}
{265}{}{Já si promluvit. Já nyní jít.}
{266}{}{Chtít vìdìt jednu vìc. Co kdyby já øíct, e najít Vault 13?}
{267}{}{Ještì jedna vìc. Co kdy Vám øeknu, e jsem našel Vault 13?}
{268}{}{Pùjdu si s ním promluvit. Nashle.}

{269}{tand36}{Všechno je obchod, co? Dobøe. Pìt stovek, kdy všechno zvládneš jak máš. A ádné smlouvání - ber nebo nech bıt.}
{270}{}{Já to brát, ale mít dotazy.}
{271}{}{Já nezajímat se.}
{272}{}{Beru to, ale mám nìkolik otázek.}
{273}{}{Nezájem.}

{274}{tand37a}{Jsem Tandi, prezidentka NCR. Tak to ty jsi srovnal mého chlapce, Hosse, u Dustyho? Hmm, moná, e zrovna ty budeš ten správnı mu na správném místì. Máš zájem o práci?}
{275}{tand37b}{Jsem Tandi, prezidentka NCR. Tak ty jsi ta dívka, co srovnala mého chlapce Hosse? Ty jsi mìla bıt moje dcera! Mìla bych pro tebe práci, kdybys chtìla. Máš zájem?}
{276}{}{Moná. Jaká to bıt práce?}
{277}{}{Moná ano. O jakou práci se jedná?}

{278}{tand38}{Jsem, prezidentka New California Republic. Vítej v Shady Sands. Slyšela jsem o tobì velmi zajímavé zvìsti. Mám nìjaké záleitosti, které s tebou chci projednat.}
{279}{}{Uh, ok.}
{280}{}{Skvìlé, co pro Vás mohu udìlat?}

{281}{tand39}{Ach, jsi zpátky. Tak, máš zájem o tu práci nebo ne?}
{282}{}{Ne.}
{283}{}{Ok.}

{284}{tand40}{Tak jsi zpátky, cizinèe? Co ta práce, hotovo? Máme ji pøístup do Vaultu?}
{285}{}{Já pracovat na tom. Nashle.}
{286}{}{Já bıt tam. Usedlíci chtít vyjednávat. Vy uèit, vy pomoci, oni pak dát Vault.}
{287}{}{Já bıt tam. Já získat souèástky.}
{288}{}{Já bıt tam. Usedlíci chtít vyjednávat. Vy uèit, vy pomoci, oni pak dát Vault. Zde pøinést ty souèástky.}
{289}{}{Stále na tom pracuji. Uvidíme se.}
{290}{}{No, mám to s nimi ji probráno. Jsou ochotni vyjednávat. Pomùete jim stát se sobìstaènımi a oni vám na oplátku poskytnou pøístup do Vaultu.}
{291}{}{Mám zde ty souèástky, které potøebujete.}
{292}{}{No, mám to s nimi ji probráno. Jsou ochotni vyjednávat. Pomùete jim stát se sobìstaènımi a oni vám na oplátku poskytnou pøístup do Vaultu. Souèástky však ji mám.}

{293}{tand41}{Zatracenì! Tak mne pøestaò okrádat o èas!}
{294}{}{Pardon.}

{295}{tand42}{Vault 13 - a nalezen? To vyøeší všechny naše problémy! Kde je?}
{296}{}{Eh, ne to øíci, bıt tu malı problém.}
{297}{}{Já nakreslit mapu. Tady.}
{298}{}{Pøedtím, ne Vám to povím... je tu jeden malı problém.}
{299}{}{Nakreslím Vám mapu... tady. Tady je.}
{300}{}{Nerozdávám jen tak zadarmo zlaté doly. Chci dvacet tácù, nebo na to rovnou zapomeòte.}

{301}{tand43}{Copak?}
{302}{}{Bıt plnı deathclawù. Oni chytøí. Oni mluvit.}
{303}{}{Je plnı inteligentních deathclawù. Dokonce i mluví.}

{304}{tand44a}{Dobrá. (vrtí hlavou) Pak tedy, pøestaòme navzájem plıtvat svım èasem. (vzdych) Tam jsou dveøe.}
{305}{tand44b}{Dobrá. (vrtí hlavou) Pak tedy, pøestaòme navzájem plıtvat svım èasem. (vzdych) Tam jsou dveøe.}
{306}{}{Já odcházet.}
{307}{}{Tak dobrá. Já odcházím.}

{308}{tand45}{Zaslouíš si prémii. Mùj poboèník to s tebou vyøídí.}
{309}{}{}
{310}{}{Díky.}

{311}{tand46}{Ty jsi úplnı koòskı handlíø. Dobrá, jdi za Guntherem. On s tebou vyøídí tyhle záleitosti.}
{312}{}{Díky.}

{313}{tand47}{Chlapci, odstraòte tohle brahmíní lejno z mojí kanceláøe! Je èas jít otravovat nìkam jinam, cizinèe.}
{314}{}{Ok}

{315}{tand14b}{Mùj otec a Seth pátrali po Vaultu 13 mnoho let. Zemøeli pøi jeho hledání - a vdycky øíkali, e leí západnì odsud. Jestli se objeví nìkdo, kdo Vault 13 najde, prospìje nám víc ne s Vaultem 15.}

# Float
{316}{}{O tom si musíš promluvit s mım poboèníkem, Guntherem.}
