#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Vidíš knihovnu užívanou k ukládání nejrùznìjších spisù.}
{101}{}{Stará knihovna. Zdá se dostateènì dobøe stavìná na to, aby udržela všechny vìci uložené na policích.}
{195}{}{Nezdá se, že by na této knihovnì byly nìjaké pasti.}
{200}{}{ si nemyslí, že by na této knihovnì mohly být nìjaké pasti.}
{206}{}{Hele, nestùj tu tak.}
{207}{}{Nech být tu zatracenou knihovnu na pokoji. Napøed musím vyøídit pár dùležitých jednání s tvojí prdelí!}
{208}{}{Nedìlej to.}
