#tento soubor prelozil RadaR - rd@zbrojovka.com
#
#############################################################
#  Message File: Door.msg                                   #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the information      #
#           concerning doors in a locked state, trapped     #
#           state, locked and trapped state.                #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#                                                           #
#  Created: September 26, 1997                              #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for description of the door. The #
#  first lines, line 100-1, are for the look_at_proc. The   #
#  remainder until the next block are for description_proc  #
#  based one skill and perception success.                  #
#############################################################

# look_at_proc
{100}{}{Vidíš døevìné dveøe.}
{101}{}{Vidíš kovové dveøe.}

# description_proc

# Perception Check Critical Success
{102}{}{Vidíš bytelné dveøe se zámkem, který mùže být zdolán
 paklíèi, a vysoce explozivní výbušninu narafièenou v rámu dveøí. Snad
 máš na to, je otevøít.}
{103}{}{Vidíš bytelné dveøe se zámkem a vysoce explozivní výbušninu
 narafièenou v rámu dveøí. Snad máš na to,
 je otevøít.}
{104}{}{Vidíš bytelné dveøe na kterých není patrný žádný zamykací mechanismus.
 Ve dveøním rámu je narafièena vysoce explozivní výbušnina. Snad máš
 na to, je otevøít.}
{105}{}{Vidíš bytelné dveøe se starým a rezavým zámkem. V rámu dveøí je
 narafièena vysoce explozivní past. Snad máš na to,
 je otevøít.}

{106}{}{Vidíš bytelné dveøe se zámkem, který mùže být zdolán
 paklíèi. Ve dveøním rámu je nìjaká past. Snad máš na to,
 je otevøít.}
{107}{}{Vidíš bytelné dveøe se zámkem.
 Ve dveøním rámu je nìjaká past. Snad máš na to, je otevøít.}
{108}{}{Vidíš bytelné dveøe na kterých není patrný žádný zamykací mechanismus.
 Ve dveøním rámu je nìjaká past. Snad máš na to, je otevøít.}
{109}{}{Vidíš bytelné dveøe se starým a rezavým zámkem. V rámu dveøí je
 nìjaká past. Snad máš na to, je otevøít.}

{110}{}{Vidíš bytelné dveøe se zámkem, který mùže být zdolán
 paklíèi. Ve dveøním rámu vidíš nìjaký drátek. Snad máš na to,
 je otevøít.}
{111}{}{Vidíš bytelné dveøe se zámkem. Ve dveøním rámu je vidìt nìkolik
 drátkù. Snad máš na to, je otevøít.}
{112}{}{Vidíš bytelné dveøe na kterých není patrný žádný zamykací mechanismus.
 V rámu dveøí je vidìt nìkolik drátkù. Snad máš na to,
 je otevøít.}
{113}{}{Vidíš bytelné dveøe se starým a rezavým zámkem.
 Ve dveøním rámu je vidìt nìjaký drátek. Snad máš na to, je otevøít.}

{114}{}{Vidíš bytelné dveøe se zámkem, který mùže být zdolán
 paklíèi. Snad máš na to, je otevøít.}
{115}{}{Vidíš bytelné dveøe se zámkem. Snad máš
 na to, je otevøít.}
{116}{}{Vidíš bytelné dveøe na kterých není patrný žádný zamykací mechanismus.
 Snad máš na to, je otevøít.}
{117}{}{Vidíš bytelné dveøe se starým rezavým zámkem.
 Snad máš na to, je otevøít.}

# Perception Check Success

{118}{}{Vidíš bytelné dveøe se zámkem, který mùže být zdolán
 paklíèi. V rámu dveøí je narafièena vysoce explozivní výbušnina.}
{119}{}{Vidíš bytelné dveøe se zámkem. V rámu dveøí je narafièena
 vysoce explozivní výbušnina.}
{120}{}{Vidíš bytelné dveøe na kterých není patrný žádný zamykací
 mechanismus. Ve dveøním rámu je narafièena vysoce explozivní výbušnina.}
{121}{}{Vidíš bytelné dveøe se starým rezavým zámkem. Ve dveøním rámu
 je narafièena vysoce explozivní výbušnina.}

{122}{}{Vidíš bytelné dveøe se zámkem, který mùže být zdolán
 paklíèi. V rámu dveøí je nìjaká past.}
{123}{}{Vidíš bytelné dveøe se zámkem. V rámu dveøí je
 nìjaká past.}
{124}{}{Vidíš bytelné dveøe na kterých není patrný žádný zamykací mechanismus.
 Ve dveøním rámu je narafièena nìjaká past.}
{125}{}{Vidíš bytelné dveøe se starým rezavým zámkem. Ve dveøním rámu je
 narafièena nìjaká past.}

{126}{}{Vidíš bytelné dveøe se zámkem, který mùže být zdolán
 paklíèi. Ve dveøním rámu vidíš nìjaký drátek.}
{127}{}{Vidíš bytelné dveøe se zámkem. Ve dveøním rámuje vidìt
 nìkolik drátkù.}
{128}{}{Vidíš bytelné dveøe na kterých není patrný žádný zamykací mechanismus.
 V rámu dveøí je vidìt nìkolik drátkù.}
{129}{}{Vidíš bytelné dveøe se starým rezavým zámkem. V rámu dveøí vidíš
 nìjaký drátek.}

{130}{}{Vidíš bytelné dveøe se zámkem, který mùže být zdolán
 paklíèi.}
{131}{}{Vidíš bytelné dveøe se zámkem.}
{132}{}{Vidíš bytelné dveøe na kterých není patrný žádný zamykací mechanismus.}
{133}{}{Vidíš bytelné dveøe se starým rezavým zámkem.}

# Perception Check Critical Failure

{134}{}{Vidíš poškozené dveøe se zámkem, který mùže být zdolán
 paklíèi, a vysoce explozivní výbušninu narafièenou v rámu dveøí.}
{135}{}{Vidíš poškozené dveøe se zámkem a vysoce explozivní výbušninu
 narafièenou v rámu dveøí.}
{136}{}{Vidíš poškozené dveøe na kterých není patrný žádný zamykací mechanismus.
 Ve dveøním rámu je narafièena vysoce explozivní výbušnina.}
{137}{}{Vidíš poškozené dveøe se starým a rezavým zámkem. V rámu dveøí je
 narafièena vysoce explozivní past.}

{138}{}{Vidíš poškozené dveøe se zámkem, který mùže být zdolán
 paklíèi. Ve dveøním rámu je nìjaká past.}
{139}{}{Vidíš poškozené dveøe se zámkem. V rámu dveøí je
 nìjaká past.}
{140}{}{Vidíš poškozené dveøe na kterých není patrný žádný zamykací mechanismus.
 Ve dveøním rámu je narafièena nìjaká past.}
{141}{}{Vidíš poškozené dveøe se starým rezavým zámkem. Ve dveøním rámu je
 narafièena nìjaká past.}

{142}{}{Vidíš poškozené dveøe se zámkem, který mùže být zdolán
 paklíèi. Ve dveøním rámu vidíš nìjaký drátek.}
{143}{}{Vidíš poškozené dveøe se zámkem. Ve dveøním rámuje vidìt
 nìkolik drátkù.}
{144}{}{Vidíš poškozené dveøe na kterých není patrný žádný zamykací mechanismus.
 V rámu dveøí je vidìt nìkolik drátkù.}
{145}{}{Vidíš poškozené dveøe se starým rezavým zámkem. V rámu dveøí vidíš
 nìjaký drátek.}

{146}{}{Vidíš poškozené dveøe se zámkem, který mùže být zdolán
 paklíèi.}
{147}{}{Vidíš poškozené dveøe se zámkem.}
{148}{}{Vidíš poškozené dveøe na kterých není patrný žádný zamykací mechanismus.}
{149}{}{Vidíš poškozené dveøe se starým rezavým zámkem.}

# Perception Check Failure

{150}{}{Vidíš staré dveøe se zámkem, který mùže být zdolán
 paklíèi, a vysoce explozivní výbušninu narafièenou v rámu dveøí.}
{151}{}{Vidíš staré dveøe se zámkem a vysoce explozivní výbušninu
 narafièenou v rámu dveøí.}
{152}{}{Vidíš staré dveøe na kterých není patrný žádný zamykací mechanismus.
 Ve dveøním rámu je narafièena vysoce explozivní výbušnina.}
{153}{}{Vidíš staré dveøe se starým a rezavým zámkem. V rámu dveøí je
 narafièena vysoce explozivní past.}

{154}{}{Vidíš staré dveøe se zámkem, který mùže být zdolán
 paklíèi. Ve dveøním rámu je nìjaká past.}
{155}{}{Vidíš staré dveøe se starým zámkem. Ve dveøním rámu je
 narafièena nìjaká past.}
{156}{}{Vidíš staré dveøe, na kterých není patrný žádný zamykací mechanismus.
 Ve dveøním rámu je narafièena nìjaká past.}
{157}{}{Vidíš staré dveøe se starým rezavým zámkem. Ve dveøním rámu je
 narafièena nìjaká past.}

{158}{}{Vidíš staré dveøe se zámkem, který mùže být zdolán
 paklíèi. Ve dveøním rámu vidíš nìjaký drátek.}
{159}{}{Vidíš staré dveøe se zámkem. Ve dveøním rámuje vidìt
 nìkolik drátkù.}
{160}{}{Vidíš staré dveøe, na kterých není patrný žádný zamykací mechanismus.
 V rámu dveøí je vidìt nìkolik drátkù.}
{161}{}{Vidíš staré dveøe se starým rezavým zámkem. V rámu dveøí vidíš
 nìjaký drátek.}

{162}{}{Vidíš staré dveøe se zámkem, který mùže být zdolán
 paklíèi.}
{163}{}{Vidíš staré dveøe se zámkem.}
{164}{}{Vidíš staré dveøe na kterých není patrný žádný zamykací mechanismus.}
{165}{}{Vidíš staré dveøe se starým rezavým zámkem.}

#############################################################
#  The following lines are for damage done to the player or #
#  critter who tried to open the door, or failed a traps    #
#  roll.                                                    #
#############################################################

# The following sets of lines are to be translated as:
# You set off the trap and were hit for [x] points of damage.
# NPC sets of the trap and was hit for [x] points of damage.

# Player sets off the trap
{166}{}{Tvým neopatrným poèínáním se past aktivovala a stálo tì to }
{167}{}{ hit bodù.}

# NPC sets off the trap
{168}{}{ aktivoval past a byl zasažen za }
{169}{}{ hit bodù.}

#############################################################
#  The following lines are for when the player uses skills  #
#  on the door.                                             #
#############################################################

# Player uses a skill on the door
# Unlock Door
{170}{}{Se svojí zkušeností úspìšnì zdoláváš zámek na dveøích.}
{171}{}{Tvojí neobratností se zámek na dveøích zasekl.}
{172}{}{Nepodaøilo se ti zdolat zámek na dveøích.}

# Lock Door
{189}{}{Úspìšnì zamykáš dveøe.}
{190}{}{Nepodaøilo se ti zamknout dveøe.}

# Find Trap on the Door
{194}{}{Shledáváš, že na dveøích je past.}
{195}{}{Nepodaøilo se ti na dveøích najít žádnou past.}

# Disarm the Trap on the Door
{196}{}{Zkušenì zneškodòuješ past na dveøích.}
{198}{}{Nepodaøilo se ti zneškodnit past.}

# NPC uses a skill on the door
# The following lines are prepended by the NPC's name

# Unlock Door
{173}{}{ zkušenì zdolává zámek na dveøích.}
{174}{}{ svojí neobratností zasekl zámek na dveøích.}
{175}{}{ nedokázal zdolat zámek na dveøích.}

# Lock Door
{191}{}{ úspìšnì zamknul dveøe.}
{192}{}{ nedokázal zamknout dveøe.}

# Find Trap on the Door
{199}{}{ shledal, že na dveøích je past.}
{200}{}{ nedokázal na dveøích najít žádnou past.}

# Disarm the Trap on the Door
{201}{}{ zkušenì zneškodòuje past na dveøích.}
{202}{}{ nedokázal zneškodnit past.}

#############################################################
#  The following lines are for when the player tries to     #
#  use items on the door which are not lockpicks.           #
#############################################################

# Player uses an item on the door
{176}{}{Podaøilo se ti vyrazit dveøe.}
{177}{}{Pøi vyrážení dveøí si pøíliš napínáš záda a to
 tì stojí jeden hit bod.}

# The following set of lines is to be translated as:
# You strain your back while trying to bust the lock and
# take [x] points of damage.

{178}{}{Pøi vyrážení dveøí si pøíliš napínáš záda a to
 tì stojí }
{179}{}{ hit bodù.}
{180}{}{Na vyražení dveøí nemáš dostatek síly.}

# NPC uses an item on the door
# The following lines are prepended by the NPC's name
{181}{}{ vyráží dveøe.}
{182}{}{ si pøi vyrážení dveøí pøíliš napínal záda a stálo ho to
 jeden hit bod.}

# The following line set of lines is to be translated as:
# NPC strains his back while trying to bust the lock and
# takes [x] points of damage

{183}{}{ si pøi vyrážení dveøí pøíliš napínal záda a stálo ho to }
{184}{}{ hit bodù.}

{185}{}{ je na vyražení dveøí pøíliš slabý.}
{186}{}{ si pøi vyrážení dveøí pøíliš napínal záda a stálo ho to
 jeden hit bod.}

# The following line set of lines is to be translated as:
# NPC strains her back while trying to bust the lock and
# takes [x] points of damage

{187}{}{ si pøi vyrážení dveøí pøíliš napínal záda a stálo ho to }
{188}{}{ hit bodù.}

#############################################################
#  Damage done to the door due to explosives.               #
#############################################################

{193}{}{Vybušnina udìlala na dveøích pár škrábancù.}

#############################################################
#  Reporting Door Status should it be used.                 #
#############################################################

{203}{}{Dveøe se zdají být zamèené.}
{204}{}{Všímáš si ve dveøích nìjaké pasti.}

# NPC finds trap
# The following line is to be translated as:
# NPC notices a trap in the door jam.

{205}{}{ si na dveøích všiml nìjaké pasti.}

#############################################################
#  Setting traps on a door and whether the door is open or  #
#  closed to set the trap.                                  #
#############################################################

# Player tries to set a trap on an open door
{206}{}{Dokud jsou dveøe otevøené, nemùžeš na nì
 umístit žádnou past.}

# NPC tries to set a trap on an open door
{207}{}{ nemùže umístit na dveøe žádnou past,
 dokud jsou otevøené.}

# Player tries to set a trap on a closed door
{208}{}{Podaøilo se ti nalíèit na dveøním rámu past.}
{209}{}{Nepodaøilo se ti nalíèit past na dveøní rám.}

# NPC tries to set a trap on a closed door
{210}{}{ úspìšnì líèí na dveøním rámu past.}
{211}{}{ nedokázal nalíèit na dveøním rámu past.}

# This is used specificly for this door
{212}{}{Dveøe se tady odemknout nedají.}
{213}{}{Dveøe se ani nepohnou.}
