#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Vidíš dveøe.}
{101}{}{Vypadají velice bytelnì.}
{102}{}{Ty dveøe se ani nehnou.}
{103}{}{(Všímáš si malé dírky ve dveøích, ze které jakoby vycházel nìjaký hluk.) Haló?}
{104}{}{Ehm, haló?}
{105}{}{Odkdy dveøe mluví?}
{106}{}{Ehm, nazdárek.}
{107}{}{GANG PROBLEM LIMB.}
{108}{}{Cvak... (Dveøe odemèeny.)}
{109}{}{Sorry, nepotøebujeme tu nìkoho takového.}
{110}{}{Dveøe mají zamykací mechanismus z druhé strany. Nezdá se, že by tu bylo nìco, co se dá zkusit páèit.}
{111}{}{Dveøe jsou zapuštìny v rámu a nezdá se, že by tu bylo možno umístit nìjakou past.}
{112}{}{Dveøe pod tím nátlakem vržou a praskají.}
{113}{}{Dveøe jsou již odemèeny.}
{114}{}{Dveøe z tebe necítí žádnou výzvu.}
