#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Vidíš oznamovací tabuli.}
{101}{}{Vidíš oznamovací tabuli se stanovenými právy NCR.}
{102}{}{Typická vývìsní tabule s nìkolika pøišpendlenými papíry. Nejnápadnìjší jsou papíry uprostøed a to práva NCR.}
{103}{}{Vítejte v New California Republic! Pøedtím, než vstoupíte do našeho krásného mìsta, udìlejte si prosím èas k obeznámení se s následujícími pravidly a naøízeními.}
{104}{}{Uvnitø mìsta nesmìjí být nošeny žádné zbranì.}
{105}{}{Osoby, které budou shledány pod vlivem alkoholu nebo drog budou zatèeny.}
{106}{}{Otrokáøství, hazard, a prostituce jsou uvnitø mìsta zakázány.}
{107}{}{Neznalost zákona neomlouvá. Hlupáci budou vyhoštìni stejnì tak rychle, jako chytráci.}
{108}{}{Jestli nemíníte akceptovat tyto práva a naøízení- táhnìte k èertu!}
{109}{}{Bude lepší, když schovám zbranì. Tak je to nejspíš mínìno.}
{110}{}{Podrobit se zákonùm je obèanská povinnost.}
{111}{}{Zpìt}
{112}{}{Nic dalšího už èíst nepotøebuji.}
{113}{}{Tohle neveští nic dobrého, pro mé tradièní návyky.}
{114}{}{Prima, aspoò tam nebudou žádní opilci nebo žebráci, kteøí jenom tahají z èlovìka peníze.}
{115}{}{Zpìt}
{116}{}{Nic dalšího už èíst nepotøebuji.}
{117}{}{Nuže, je tu pár nesporných výhod, které však nestojí za øeè.}
{118}{}{Hmm... zdá se, že se tu nìkdo snaží vytvoøit poèestné a slušné spoleèenství.}
{119}{}{Zpìt}
{120}{}{Nic dalšího už èíst nepotøebuji.}
{121}{}{Pìknì drsná slova. Ale snad se èlovìk mùže aspoò podívat, dá-li se tady za tìchto podmínek žít.}
{122}{}{Rovnost všech pøed zákonem - to není špatný nápad.}
{123}{}{Zpìt}
{124}{}{Nic dalšího už èíst nepotøebuji.}
{125}{}{Nauèit tyhle chlápky respektu, nabývá na mým seznamu, co je tøeba udìlat, vyšších priorit.}
{126}{}{Hmm...tohle je ponìkud pøihlouplé, ale... dostávají za to bodík k dobru.}
{127}{}{Zpìt}
{128}{}{Nic dalšího už èíst nepotøebuji.}