# Tento soubor pøeloil Radek "Sengaia" Friedrich.......Level
{100}{}{Vidíš Amandu.}
{101}{}{Vidíš udøenou enu. Zdá se, e nedávno plakala.}
{102}{}{Vidíš Amandu.}
{103}{}{Vidíš sedøenou enu. Vypadá to, e nedávno plakala.}
{104}{}{Vidíš Amandu. Teï kdy je Joshua volnı, vypadá mnohem šastnìjší.}
{105}{}{Vidíš Amandu.}
{106}{}{Vidíš Amandu. Teï kdy je Joshua volnı, vypadá mnohem šastnìjší.}
{107}{}{Ach, mùj Joshuo...}
{108}{}{Co si mám poèít?}
{109}{}{Všechny peníze u mi došly...}
{110}{}{Kdyby ho jen Obèané nechali jít...}
{111}{}{Joshuo, jsem tak šastná, e jsi volnı. Tolik jsem se bála...}
{112}{}{Promiò, nemám nic, co bych ti mohla dát.}
{113}{}{Prosím, nech mì bıt, nebo zavolám stráe.}
{114}{}{Co chceš?}
{115}{}{Jsi v poøádku? Vypadáš rozèilenì.}
{116}{}{Tak nic. Promiò, e ruším.}
{117}{}{Já...no, mùj... jde o mého manela Joshuu. On... dostal se do potíí v...tom baru. Nechtìnì udeøil Obèana a oni ho zavøeli. On to tak nemyslel, ale byl opilı a...}
{118}{}{Zavøeli ho? A kde je teï?}
{119}{}{Pokud se opil a nìkoho napadl, tak je ve vìzení právem.}
{120}{}{To je mi moc líto. Doufám, e ho propustí.}
{121}{}{Ve mìstì, v Centru rozdìlování sluebníkù... øíkají, e si svùj trest mùe odpracovat jako sluha, ale to mùe trvat léta!}
{122}{}{Dá se nìco dìlat?}
{123}{}{Pokud se opil a nìkoho napadl, tak je ve vìzení právem.}
{124}{}{To je mi moc líto. Doufám, e ho propustí.}
{125}{}{Ale to byla nehoda! Já... on urèitì nechtìl!}
{126}{}{Kde je teï?}
{127}{}{Nechtìl nikoho napadnout? To urèitì. Snad to pro vás oba bude dobrá lekce.}
{128}{}{To je mi moc líto. Doufám, e ho propustí.}
{129}{}{Moc penìz mi nezbylo a kdy nebudeme mít na zaplacení za ochranu, tak budeme muset brzo odejít. Øíkají, e pokud tu chceme s Joshuou zùstat, tak jen jako sluhové...}
{130}{}{To zní jako rozumné øešení. Ve Vault City se chovají ke slouícím pomìrnì slušnì, nebo ne?}
{131}{}{Zjistím, co se s tím dá dìlat, OK? Zkusím promluvit s nìkım v Centru rozdìlovaní sluebníkù.}
{132}{}{Pomùu ti, ale bude tì to nìco stát.}
{133}{}{To je mi moc líto. Doufám, e ho propustí.}
{134}{}{Nechci, aby mùj syn vyrùstal jako otrok! Pøišli jsme do Vault City, protoe jsme slyšeli, e je to svobodné mìsto... ale kdy jsme pøišli... samé zákony, naøízení, placení stráím... všechno jinak, ne nám tvrdili.}
{135}{}{Zjistím, co se s tím dá dìlat, jo? Zkusím promluvit s nìkım v Centru rozdìlovaní sluebníkù.}
{136}{}{To je mi moc líto. Doufám, e ho propustí.}
{137}{}{Velí tam Barkus, dùstojník Barkus. Nemohla jsem se ani dostat do mìsta, abych s ním promluvila. Nevím, jestli je Joshua vùbec v poøádku! Já...}
{138}{}{Nemìj strach, zjistím, co se dá dìlat.}
{139}{}{Ale já nemám skoro ádné peníze a...}
{140}{}{Nemìl jsem na mysli peníze.}
{141}{}{To nic. Zkusím promluvit s nìkım v Centru rozdìlovaní sluebníkù.}
{142}{}{To je mi moc líto, vánì. Doufám, e ho propustí. Sbohem.}
{143}{}{Co tím myslíš...? Ach, ne. To... nejde. Já.. ne...}
{144}{}{Chceš, aby manela pustili, nebo ne? A on se to nemusí nikdy dovìdìt.}
{145}{}{To nic. Zkusím promluvit s nìkım v Centru rozdìlovaní sluebníkù.}
{146}{}{To je mi moc líto. Vypadá to, e tvùj manel u se nikdy na svobodu nedostane. Sbohem.}
{147}{}{Kdy slíbíš, e ho osvobodí, já...já...dobrá. Já...zavøu stanovı vchod. Myslím, e syn si hraje venku... take nás tu nevyruší.}
{148}{}{Bez obav, tvého mue osvobodím. A dostanu svojí odmìnu.}
{149}{}{Zapomeò na to. Zkusím promluvit s nìkım v Centru rozdìlovaní sluebníkù.}
{150}{}{No nic. Zapomeò, e jsme se potkali.}
{151}{}{Hej, a co já?!}
{152}{}{Prosím, zachraò Joshuu. Je ve mìstì ve Centru rozdìlování sluebníkù.}
{153}{}{Díky za záchranu mého mue! Prosím... pøijmi to jako odmìnu. Není to moc, ale...}
{154}{}{Ještì jednou díky za záchranu mého mue. Brzy se odstìhujeme.}
{155}{}{Uf... díky za záchranu mého mue... prosím, neøíkej mu, co se mezi námi odehrálo.}
