# Tento soubor pøeloil Radek "Sengaia" Friedrich.......Level
{100}{}{Vidíš...dalšího...funkcionáøe Vault City.}
{101}{}{Vidíš Barkuse, velitele Centra rozdìlování sluebníkù Vault City.}
{102}{}{Co to sak--?! Mutant! Ve Vault City! Stráe! Stráe!}
{103}{}{Co to sak--?! Ghoul! Ve Vault City! Stráe! Stráe!}
{104}{}{Umm...ehrmmm?}
{105}{}{Jestli je boj to, co chceš...}
{106}{}{Støedisko rozdìlování sluebníkù je zavøeno. Vra se, prosím, ráno.}
{107}{}{Ano, Kapitáne?}
{108}{}{Ano, Obèane?}
{109}{}{No, co se dìje? Jsem pozadu v plnìní svıch úkolù.}
{110}{}{Ehmm...Já hledat Valt!}
{111}{}{Vypadni}
{112}{}{Co je to za barák?}
{113}{}{Hledám Vault.}
{114}{}{Hledám konkrétního sluebníka...Joshuu, myslím. Je tu nìkde?}
{115}{}{Hodláš nakupovat otroky...chci øíct sluebníky?}
{116}{}{Dneska nic, díky.}
{117}{}{Tenhle? Tohle je Centrum rozdìlování sluebníkù. Máš zájem o slouícího?}
{118}{}{Tohle je Centrum rozdìlování sluebníkù.}
{119}{}{Centrum rozdìlování sluebníkù? Co je to?}
{120}{}{Hledám konkrétního sluebníka...Joshuu, myslím. Je tu nìkde?}
{121}{}{Rozdìlování sluebníkù, jo? Kupujete tu otroky,...chci øíct sluhy?}
{122}{}{Ne, jsem jen zvìdavı. Díky.}
{123}{}{Jsem jen zvìdavı. Díky.}
{124}{}{Vault? To je ta obøí díra v horách na vıchod od mìsta. Vyjdi ze vstupních dveøí, otoè se doleva a jdi poøád rovnì. Nemùeš to minout.}
{125}{}{Co je tohle za barák?}
{126}{}{Mùe se tam nìkdo dostat?}
{127}{}{Mìl bych ještì jeden dotaz.}
{128}{}{Díky za instrukce. Na vidìnou.}
{129}{}{Coe dopr -? Jsi nìjakı novı sluebník?}
{130}{}{Jo}
{131}{}{Uch-uch já teï odejít}
{132}{}{Musíš tu bıt novı. Vysvìtlím ti to...pomalu.}
{133}{}{Obèané, kteøí potøebují pomoci s podøadnımi pracemi, si zajdou do Centra a na den dostanou pøiøazeného sluebníka.}
{134}{}{To zní skoro jako otroctví.}
{135}{}{Aha, tak tady se skladují otroci? Proè jsi to neøekl?}
{136}{}{Kde jste získali tolik sluebníkù?}
{137}{}{Hledám konkrétního sluebníka...Joshuu, myslím. Je tu nìkde?}
{138}{}{Nemáš zájem koupit nìjaké otroky...chci øíct sluebníky?}
{139}{}{Fajn, byl jsem jenom zvìdavı, díky. Nashle.}
{140}{}{U mì unavuje posílání sluebníkù bez øádného povolení... *povzdech*... hele, øíkal jsi, e hledáš Vault? To musí bıt tvoje denní zaøazení. Fajn. Pošlu tam s tebou nìjakı doprovod.}
{141}{}{Valt! Valt!}
{142}{}{Dával bych si pozor na to, jak mluvíš, bıt tebou. Toto NENÍ otroctví. Staráme se o tyhle ztroskotance, nemají se špatnì... rozhodnì líp, ne by se mìli v pustinách venku.}
{143}{}{Kde je získáváte?}
{144}{}{Hm, mám ještì další otázky...}
{145}{}{To je vše, co jsem chtìl vìdìt, díky. Hezkı den.}
{146}{}{Ne, musíš bıt Obèanem, abys dostal povolení do Vaultu. No, a teï, jestli dovolíš, mám dost vlastní práce, take kdybys mì omluvil...}
{147}{}{Jen jedinou otázku...}
{148}{}{Fajn. Sbohem.}
{149}{}{Naši sluebníci jsou vìtšinou uprchlíci pøed útoky banditù nebo smluvní vìzni, kteøí se rozhodli odpracovat svùj trest èinorodou prací.}
{150}{}{Ty myslíš textaøe? Znával jsem jednoho chlapíka jménem Kordík, kterı...}
{151}{}{Za cenu vlastní svobody, co?}
{152}{}{Je tu ve vazbì mezi smluvními vìzni nìkdo jménem Joshua?}
{153}{}{Hodláš teï nìkdy kupovat nìjaké otroky...chci øíct sluebníky?}
{154}{}{Hmmm. Mám ještì další otázku...}
{155}{}{Aha. Díky za informaci.}
{156}{}{Ne, ádní textaøi, ty magore.}
{157}{}{Magor? Musel jsem tìce makat, abych to dotáhnul aspoò na 9 Inteligence a Vnímání a dostal se a do tohohle bodu. A o èeme jsi to mluvil?}
{158}{}{Ty seš ten pravej na vynášení morálních soudù, otrokáøi. Ztra se mi z oèí.}
{159}{}{Mluvíš úplnì stejnì jako ten idiot Moore...pøesnì to Vault City potøebuje. Hele, a jsi kdokoli, já mám dost práce, take kdyby ses laskavì ztratil...}
{160}{}{Fajn, fajn, no jo...}
{161}{}{Proè mì nenecháš jít?}
{162}{}{Joshua? Ano, máme sluebníka toho jména, ale urèitì ho nebudeš chtít najmout. Trénovat ho bylo... obtíné. Nejsem si jist, zda je tréninku schopen.}
{163}{}{Joshua? Myslím, e jsem tu nìkoho takového mìl, kdysi...ale u dávno tu není.}
{164}{}{Musím se ho zeptat na nìco ohlednì bezpeènosti Vault City. Nechte ho ihned poslat na pøedmìstí.}
{165}{}{Pøesto bych si ho chtìl najmout.}
{166}{}{Obtíné?}
{167}{}{Ach, nechci ho najmout pro sebe. To vùbec ne. Obávám se, e by mohl bıt nakaenı.}
{168}{}{Hmmm. Ještì jednu otázku...}
{169}{}{Dobrá. Sbohem.}
{170}{}{Nemyslím, e je to dobrı nápad. Poèkám, ne prodìlá trochu více tréninku, a potom se rozhodnu.}
{171}{}{Øekl jsi, e to bylo sloité?}
{172}{}{Jen ještì jednu otázku...}
{173}{}{Fajn, sbohem.}
{174}{}{Jo, je mnohem vzpurnìjší, ne kterıkoli slouící, jakého jsme tu dosud mìli. Kdybych ho neznal tak dobøe, myslel bych, e jeho otec musel bıt brahmín.}
{175}{}{Víš, tohle chování a vzdor by mohl bıt problém. Co kdyby se ostatní sluebníci rozhodli následovat jeho pøíkladu?}
{176}{}{Mohl bych si ho najmout a zbavit tì ho. Pøijímá Centrum..."sponzorské dary?"}
{177}{}{Ještì jednu otázku...}
{178}{}{Fajn. Sbohem.}
{179}{}{To je pravda. Musel jsem ho separovat od ostatních... a zrovna vèera mìl dokonce jeden ze sluebníkù tu drzost zpochybòovat jeden z mıch poadavkù.}
{180}{}{Mìl bys ho radìji propustit, døív ne bude pozdì.}
{181}{}{Joshua? Ano, takového sluebníka tu tedy máme. Právì byl pøesunut do Nápravného centra. Tvùj zájem o nì je jakého druhu...?}
{182}{}{Chtìl bych vyjednat jeho propuštìní.}
{183}{}{Mám podezøení, e je nakaen nakalivou chorobou. Mìl by bıt propuštìn døív, ne nakazí další sluebníky.}
{184}{}{ádnı zájem, mám jen pár dalších otázek...}
{185}{}{Fajn. Sbohem.}
{186}{}{Ach, vánì? A proè si myslíš, e bych ho mìl propustit?}
{187}{}{Co tøeba velmi slušnı dar na provozní fond Sluebnického centra?}
{188}{}{Mám podezøení, e je nakaen nakalivou chorobou. Mìl by bıt propuštìn døív, ne nakazí další sluebníky.}
{189}{}{ádnı zájem, mám jen pár dalších otázek...}
{190}{}{Fajn. Sbohem.}
{191}{}{Ne, mìl jsem na mysli mnohem slušnìjší èástku.}
{192}{}{Hmm. Dary jsou velmi vítány, aby byl zajištìn plynulı provoz Centra. Ale bude to vyadovat hodnotnı dar, abych mohl vydat Joshuu do tvıch rukou.}
{193}{}{A takhle $1000?}
{194}{}{A takhle $750?}
{195}{}{A takhle $500?}
{196}{}{A takhle $250?}
{197}{}{Promyslím to. Mìl bych ještì pár otázek...}
{198}{}{Aha. Moná se vrátím pozdìji.}
{199}{}{Aha. Vrátím se, a budu mít dost penìz na dotaci.}
{200}{}{Dobrá...není to takovı dar, jakı jsem si pøedstavoval, ale budi. Musím zkontrolovat, aby Joshuu vyslali k Soudu, jak sis pøál. Hned se do toho dám.}
{201}{}{Bezva.}
{202}{}{Hotovo. Joshua u není sluebníkem ve Vault City a byl pøesunut na pøedmìstí spolu se zbytkem cizincù.}
{203}{}{Díky, mìl bych ještì otázku...}
{204}{}{Perfektní. Tak já si ho tam dojdu vyzvednout.}
{205}{}{To není blbı. Snad se nevrátí zpátky do mìsta.}
{206}{}{Vánì? Uvìdomuješ si, e kadı sluebník projde velmi podrobnou prohlídkou, ne je zaøazen do Centra?}
{207}{}{Moná se pletu. Pøesto chci vyjednat jeho propuštìní.}
{208}{}{Tušíš nìco o syndromu }
{209}{}{????????? Nezachytí ho vìtšina z lékaøskıch pøístrojù a jeho pøíznaky mohou bıt skryté po nìkolik mnoho tıdnù.}
{210}{}{V pustinách je nemoc zvaná syndrom }
{211}{}{, znáš to? Moná jsi zpozoroval sníenou vıkonnost sluebníkù v poslední dobì. Tu celkovou nevrlost?}
{212}{}{To je totální kravina. No, pokud u jsi skonèil s mrháním mého èasu svımi vımysly...}
{213}{}{Dobrá, zapomeò na ten syndrom " }
{214}{}{." Pøesto chci vyjednat propuštìní Joshuy.}
{215}{}{Hmmm. Mám ještì další otázku...}
{216}{}{V tom pøípadì odcházím, sbohem.}
{217}{}{Infikovanı? Infikovanı èím?}
{218}{}{Pøíznaky? Jakı druh pøíznakù?}
{219}{}{Moná jsi zpozoroval sníenou vıkonnost sluebníkù v poslední dobì? Nepozornost? Jejich neschopnost poslouchat rozkazy a správnì je plnit? A to je teprve poèáteèní stádium.}
{220}{}{Uf...}
{221}{}{'syndrom. Má ho spousta lidí z vnìjšího svìta. Mezi symptomy patøí i, ehm, mluvení bez vyzvání a pouívání sprostıch slov.}
{222}{}{Hmmmm. To se nesmí stát, aby Obèané hlásili problémy se sluebníky...dobrá, propustím Joshuu hned. Poèkej, musím udìlat pár nezbytnıch opatøení...}
{223}{}{Ano...v poslední dobì jsem si toho u sluhù všimnul. Nakalivé, øíkáš? Hmmm. No, pokud je Joshua pøenašeè, mìl bych ho radìji okamitì propustit. ZA moment, jen provedu nìjaké nezbytnosti...}
{224}{}{V poøádku. Bude lepší, kdy Joshua zmizí s ostatními lidmi z vnìjšku.}
{225}{}{Jistì, Kapitáne. Hned se o to postarám.}
{226}{}{Vıbornì, dìkuji ti Obèane.}
{227}{}{Moná, máte nìjaké, které chcete prodat?}
{228}{}{Ano, mám tu zrovna jednoho. Prohlídni si ho a nabídni cenu.}
{229}{}{Ano, mám jich tu zrovna pár. Prohlídni si je a nabídni cenu.}
{230}{}{No, vlastnì ne. Mám ještì pár otázek...}
{231}{}{No, dneska asi ne. Sbohem.}
{232}{}{Hmmm. Tahle enská, Miria, co? Má celkem silné pae...a pìkné boky. Beru jí od tebe za $250.}
{233}{}{Hmmm. Ten hošík, Davin, e? Vypadá celkem nezasaen kontaminací z venku. Beru ho od tebe za $250.}
{234}{}{Hmmm. Ten barbar, co máš. Silnì...páchne. Ale vypadá zdravì. Vzal bych ho za $100.}
{235}{}{Hmmm. Tamten chlapík...Vic, ne? I kdy je dost starı, vypadá jako šikovnı chlap. Vzal bych ho za $100.}
{236}{}{Moná bys mìl pøijít, a budeš mít nìco, co bys mi mohl nabídnout. Tvoje souèasná nabídka je...nezajímavá.}
{237}{}{No tak, ten otrok má vìtší cenu ne tohle.}
{238}{}{To je dobrá cena. Všichni sluebníci jsou tví.}
{239}{}{No, toho bych zrovna teï prodat nechtìl, ale mám ještì pár otázek, na které se tì chci zeptat...}
{240}{}{No, toho bych zrovna teï prodat nechtìl. Provedeme ten obchod jindy.}
{241}{}{Perfekt. No, mìl bych na tebe ještì pár otázek...}
{242}{}{Tak jo. Nìkdy, a budu mít lepší nabídku pøijdu.}
{243}{}{Ne, to asi ne...250 nebo nic.}
{244}{}{Ne, ten hoch vypadá, e pùjde tìko trénovat...200 nebo nic.}
{245}{}{Hele, potrvá tıden, ne z toho barbara smyjeme ten zápach, take buï 100 nebo nic.}
{246}{}{Ale vdy mi ani nezaruèíš, e nedostane infarkt, jakmile odejdeš. Je pøece starı. 100 nebo nic.}
{247}{}{Tak fajn, to zní fér. Všichni sluebníci jsou tví.}
{248}{}{Zapomeò na to. No, mìl bych na tebe ještì pár otázek...}
{249}{}{Take teda nic. Nemohu si dovolit propustit sluebníka za takovou cenu. Snad nìkdy jindy.}
{250}{}{Hmmmm...Vypadá jako zdravı kousek...moná bych tu pro ní našel nìjakou práci. $500. A je to koneèná nabídka.}
{251}{}{Hmmmm. Je to zdravı jedinec. $400 za nìj, víc ne.}
{252}{}{Hmmmm. Dobrá. Tak $200. A u bez smlouvání.}
{253}{}{Hmmmmmmm. $200. Ani o babku víc.}
{254}{}{To zní fér. Všichni sluebníci jsou tví.}
{255}{}{No, toho bych zrovna teï prodat nechtìl, ale mám ještì pár otázek, na které se tì chci zeptat...}
{256}{}{No tohohle otroka teï prodat nechci. Provedeme ten obchod jindy.}
{257}{}{Vıbornì. Tady máš ty peníze. Nechám ji odeslat na lékaøskou prohlídku a k zaèlenìní. }
{258}{}{Vıbornì. Tady máš ty peníze. Nechám ho odeslat na lékaøskou prohlídku a k zaèlenìní. }
{259}{}{Vıbornì. Tady máš ty peníze. Nechám barbara odeslat na lékaøskou prohlídku a k zaèlenìní. }
{260}{}{Vıbornì. Tady máš ty peníze. Nechám starocha odeslat na lékaøskou prohlídku a k zaèlenìní. }
{261}{}{Dej mi trochu èasu na vyøízení té záleitosti...}
{262}{}{Jasnì. Poèkám tady.}
{263}{}{Fajn. Tvùj slouící byl pøemístìn k lékaøské prohlídce a rekondicionování. Zvláštní... ten sluebník se zdál bıt velmi pøekvapenı. Musel dostat pár uklidòujících støel, aby vše mohlo probìhnout hladce. Vše, co mìl sluebník u sebe, jsem dal do krabice v mé kanceláøi.}
{264}{}{No, sluebníci zùstanou vdy sluebníky. Chtìl jsem se tì zeptat...}
{265}{}{Vánì? No, jsem si jistı, e èasem bude mnohem poslušnìjší. Zajímají tì ještì nìjací další spoleèníci?}
{266}{}{no jo, bude to pro nì zpoèátku tìké, ale oni si èasem zvyknou. Sbohem.}
{267}{}{Co tady zase dìláš? Poslal jsem tì do Vaultu! Ke všem èer... no dobrá, budu tì tam muset nìkım nechat dopravit zpátky.}
{268}{}{Ou-kéééééj}
{269}{}{Pøesvìdèil jsi Barkuse, aby propustil Joshuu.}
