# Tento soubor pøeloil Radek "Sengaia" Friedrich.......Level
{100}{}{Vidíš postaršího mue s oblièejem plnım vrásek. Pokud si všimnul, e na nìj civíš, nedává to nijak znát.}
{101}{}{Vidíš Cassidyho.}
{102}{}{Vidíš postaršího mue s oblièejem plnım vrásek. Kıvá na tebe hlavou.}
{103}{}{No dobrá. Nikdy jsem tì tu ještì nevidìl, cizinèe. Jsem Cassidy. Vlastním tenhle podnik. Co pro tebe mohu udìlat?}
{104}{}{A hele, jestli tohle není ten tajemnı cizinec. Co pro tebe mohu udìlat tentokrát?}
{105}{}{Ug Nog?}
{106}{}{Vypadni}
{107}{}{Pátrám po Vaultu.}
{108}{}{Ty u se odsud chystáš zmizet?}
{109}{}{Co tady nalejváte?}
{110}{}{Stalo se tu v okolí nìco, co by stálo za øeè?}
{111}{}{Tentokrát nic, dík.}
{112}{}{Mlátili tì do hlavy moc èasto, co? Lituji, nemluvím imbecilštinou.}
{113}{}{Béé-cil?}
{114}{}{Vault? Jedinı Vault, kterı znám, je ten ve mìstì. Velká pitomá díra...to nemùeš minout, fakt.}
{115}{}{Co tu máte k pití?}
{116}{}{Dìje se tu v okolí nìco zajímavého?}
{117}{}{Díky za radu, porouèím se.}
{118}{}{Pivko za $20, panák whisky za $30. Nic zvláštního. No, dáš si nìco?}
{119}{}{Pátrám po Vaultu.}
{120}{}{Dám si pivo.}
{121}{}{Dám si panáka.}
{122}{}{Dìje se tu v okolí nìco zajímavého?}
{123}{}{Asi nic. Kadopádnì díky.}
{124}{}{"Zajímavého?" Hehe. Kámo, Vault City není vùbec "zajímavé" místo...tedy do té doby, ne se zaènou strání nudit, to je pak lepší nìkam zalézt. Proè se ptáš?  Hledáš snad nìco v tıhle páchnoucí díøe?}
{125}{}{Co tady máte k pití?}
{126}{}{No, vlastnì hledám Vault.}
{127}{}{Nemùe to tu bejt tak špatnı.}
{128}{}{Asi nic. Kadopádnì díky.}
{129}{}{Tady je to. Kopni to do sebe. Obèas to pomùe zapomenout, kde jsi.}
{130}{}{Tady to nemùe bejt tak zlı.}
{131}{}{Díky za pití, pomalu budu muset jít.}
{132}{}{Jo, vánì? No, sakra, musel jsem se splést, nìjak jsem si nevšim, e TY jsi opravdová autorita, nebo co. Tu razii minulı tıden tady asi asi nìkdo prochrápal, co?}
{133}{}{Razii?}
{134}{}{No jó, byl to perfektní pohled. Vrazila sem strání hlídka a hledali tu "ilegální chemické látky." Rozmlátili dveøe, rozmlátili všechno zboí, a pak taky zabásli pár mıch zákazníkù.}
{135}{}{A co se stalo pak?}
{136}{}{To je mi líto. Promluvíme si pozdìji.}
{137}{}{Potom, co odsud odtáhli jednoho chlapíka, Joshuu, za kladení odporu pøi zatıkání, mi napaøili pokutu za nález -teï poslouchej- OPRAVDOVÉ whiskey. Co na tom, e jsem dostal od Starka pøed tøemi mìsíci povolení. Jsou to parchanti.}
{138}{}{jùva. Bez legrace.}
{139}{}{To je mi líto. Promluvíme si pozdìji.}
{140}{}{Ještì líp to pokraèuje. Teï stránım dluím za pokutu a musím nakoupit nové zásoby alkoholu od obchodníka za trojnásobnou cenu ne obvykle. No a pøedpokládám, e se tu strání zase brzo objeví, jen aby mi dali po hubì. }
{141}{}{To se tady dìje poøád?}
{142}{}{Snad se ti povede líp, èasem. Zatím nashle.}
{143}{}{Ani v dobrıch èasech to nestojí za nic. Obèané moc nepijou, take tady trèím a nalévám obchodníkùm. Jestli se ještì objeví nìjakej podìlanej mátijeb a bude smlouvat o panáka, udìlám mu z jeho vlastního zadku parádní klobouk.}
{144}{}{Proè tu zùstáváš, kdy to tu tak nenávidíš?}
{145}{}{To je mi líto. Hledám Vault. Mùeš mi nìjak pomoct?}
{146}{}{To je mi líto. No, snad bude líp.}
{147}{}{Mám nemocné srdce. Potøebuju dávky na podporu srdeèní èinnosti. A mìsto je jediné místo s opravdovou lékaøskou péèí, take jsem se tu rozhodl usadit a zkusit ít.}
{148}{}{Zdá se, e toho tady máš plné zuby.}
{149}{}{Aha. No, já hledám Vault. Mùeš mi nìjak pomoct?}
{150}{}{Snad se ti povede líp, èasem. Zatím nashle.}
{151}{}{Chce se mi to tady zavøít a nechat tohle mìsto a si shnije ve vlastních špínì. Srát na to na všechno.}
{152}{}{Tak proè neodejdeš?}
{153}{}{To je mi líto. Snad se to èasem zlepší.}
{154}{}{Odejít sám do pustin? Cha. Tohle místo mì sere, ale nejsem blázen.}
{155}{}{Brzy zase vyráím na cesty. Nechceš se pøipojit?}
{156}{}{Dobrá, tak ti pøeju hodnì štìstí.}
{157}{}{Nechci tì urazit nebo tak, ale nevypadáš, e bys mohl nìkoho vést. Mám dojem, e v pustinách si z tebe udìlají obìd.}
{158}{}{Ne, necestuju s otrokáøi. Mají takovı nepìknı zvyk prodat tì, kdy jim dojdou peníze. Bez uráky.}
{159}{}{Ne, vypadáš na èlovìka s jednou nohou v hrobì a druhou v pekle. Nemyslím, e bych ještì potøeboval sniovat svou, u tak dost chabou povìst.}
{160}{}{Ne...zdá se, e u kolem sebe máš obstojnej hlouèek.}
{161}{}{Tak fajn. Hodnì štìstí.}
{162}{}{Tak na tu nabídku zapomeò, pitomèe. Vra se k vedení svıho baru v tomhle podìlanım zapadákovì.}
{163}{}{No tak nic, tvoje chyba.}
{164}{}{He. Myslíš to vánì?}
{165}{}{Jasnì. Proè sakra ne? Vypadáš na èlovìka, kterej se vyzná v boji a dokáe se o sebe postarat.}
{166}{}{No, kdy se nad tím ještì zamyslím, venku je to docela tvrdı, zvláš pro nìkoho se srdeèními problémy. Radši tady zùstaò.}
{167}{}{Tak jo, jdu s tebou.}
{168}{}{Tak mùeme vyrazit.}
{169}{}{}
{170}{}{}
{171}{}{Co se dìje? Máš zase ten pohled typu "Musím ti øíct nìco, co se ti moná nebude líbit ".}
{172}{}{Jo?}
{173}{}{Co se dìje? Máš zase ten pohled "já jsem tady boss".}
{174}{}{Chtìl jsem se tì zeptat na pár otázek...}
{175}{}{Zdá se, e jsi pøišel trochu k úhonì. Pouij pár stimpakù a uzdrav se.}
{176}{}{Cassidy, poèkej tady, dokud se nevrátím.}
{177}{}{Odlo zbraò.}
{178}{}{Dr se co nejblí mì.}
{179}{}{Moc ne nevzdaluj.}
{180}{}{Musíme se trochu rozestoupit.}
{181}{}{No tak, Cassidy. Je èas se rozejít.}
{182}{}{Nic, nic nechci.}

{261}{}{Urèitì chceš, abych Myronovi vpálil kulku do hlavy, e jo? To nebude problém. Jen øekni a já to rád udìlám.}
{262}{}{Co máš na mysli?}
{263}{}{Proè chceš sejmout Myrona?}
{264}{}{Jaké zbranì preferuješ?}
{265}{}{No, chtìl jsem ti ještì nìco jiného...}
{266}{}{No, chtìl bych, abys nìco udìlal...}
{267}{}{Nic, pokraèujeme.}
{268}{}{Neo, neubliuj Myronovi. Ne dneska, kadopádnì. Dám ti vìdìt.}
{269}{}{No, hlavnì brokovnice a pušky...tìm dávám pøednost. Ale s pistolemi taky nejsem nejhorší.}
{270}{}{Ještì nìco?}
{271}{}{Fajn. Mám ještì pár otázek...}
{272}{}{V poøádku. Jenom kontrola.}
{273}{}{Pokud budeš nìkdy potøebovat nìkoho nauèit poøádnì slušnım mravùm, pùjè mi mosazného boxera a já mu to vtluèu do ksichtu vlastními pìstmi.}
{274}{}{Skvìle. Ještì nìco?}
{275}{}{Fajn. Mám ještì pár otázek...}
{276}{}{V poøádku. Jenom kontrola.}
{277}{}{No, hmm...jen mezi námi dvìma, dokáu se taky dobøe ohánìt s oštìpem. Spolu s kamarády jsem lovíval radškorpióny pomocí oštìpù, ale...no, já jsem naivu a oni u ti nic neøeknou.}
{278}{}{Na oštìpu není nic špatného.}
{279}{}{Fajn. Mám ještì pár otázek...}
{280}{}{V poøádku. Jenom kontrola.}
{281}{}{Øíkáš ty. Jenom mi neøíkej barbare a bude to mezi námi v pohodì.}
{282}{}{Nechtìl bych, aby si mì lidi pletli támhle se starım Kostinosem. He-he. Ještì v ivotì jsem nevidìl barbara, kterej by udìlal takovou blbost a strèil si do nosu kost.}
{283}{}{Jistì, e není. Oštìp je fajn zbraò. Spousta mıch barbarskıch pøátel ho pouívá.}
{284}{}{Víš, e já jsem taky "barbar?"}
{285}{}{Hmmm. Mám ještì pár otázek...}
{286}{}{Tak fajn. Díky za podrobnı rozbor.}
{287}{}{Ale. Nehraj si se starım Cassidym. Nejsi ádnej barbar.}
{288}{}{Jo, jsem.}
{289}{}{No jasnì. Hele, mám pár otázek...}
{290}{}{Nech toho. Nechci to s tebou rozebírat zrovna teï.}
{291}{}{Uch, dobøe...sakra práce. Omlouvám se vám všem tady a teï. Nechtìl jsem nikoho urazit.}
{292}{}{Jasnì, e ne. Mám ještì pár otázek...}
{293}{}{Zapomeò na to. Pokraèujeme.}
{294}{}{Podívej, ne budeme pokraèovat, chtìl bych nìco vìdìt. Co tady vlastnì dìláme? Zdá se, e to tady v okolí všechno prohledáváme, jako bychom nìco hledali. Máme nìjakı plán, nebo tak nìco?}
{295}{}{Hledáme GECK - Soupravu pro vytvoøení rajské zahrady. Má vesnice to potøebuje, aby bylo co jíst.}
{296}{}{Jdeme do Vaultu, pak pøineseme GECK do mé vesnice.}
{297}{}{Má vesnice byla vyplenìna, snaím se zjistit, co se jim stalo.}
{298}{}{Ty vìcièky v sadì, jo? Hele, v knihách se o tom nepíše, co? No, dobrá. Dáme se do toho.}
{299}{}{Uf. Tak fajn, jenom kontroluju.}
{300}{}{Nejsem proti udìlat øešeto z pár únoscù. Trocha soudce Lynche nikdy není na škodu...aspoò podle mne.}
{301}{}{Fajn, tak jdeme.}
{302}{}{To, co øíká ten malı sprosák, se nehodí pro slušné uši.}
{303}{}{Obzvláštì pro enské.}
{304}{}{Vánì, Cassidy, pøekvapuje mì, e se staráš. Mé srdce se vznáší.}
{305}{}{No? Co øíkáš?}
{306}{}{Víš, ty taky pìknì kleješ, Cassidy.}
{307}{}{Povídej mi o tom. Pokraèujme.}
{308}{}{Jo, ale já mám styl. On je jenom malá nevymáchaná huba.}
{309}{}{A vùbec se mi nelíbí, jak na tebe civí.}
{310}{}{Vánì, Cassidy, nevìdìla jsem, e se tak staráš. Mé srdce se vznáší.}
{311}{}{No? Co øíkáš?}
{312}{}{Povídej mi o tom. Pokraèujme.}
{313}{}{Klid, klid, nemyslel jsem to tak.}
{314}{}{Jenom tím chci øíct, e nastane den, kdy tu bude jen ten malej parchant, já a hluboká jáma nìkde v poušti.}
{315}{}{No, ivot sám dokáe bıt tvrdá škola. Mám ještì pár otázek...}
{316}{}{No, je na nejlepší cestì k tomu, aby ho to potkalo. Nebudu se tím trápit.}
{317}{}{Uklidni se, Cassidy. Nech Myrona bıt.}
{318}{}{Nenávidím to tady.}
{319}{}{Doufal jsem, e odsud odejdeme v dobrém.}
{320}{}{Mìsto tuhıch prdelí...}
{321}{}{Tady to vypadá hùø, ne ve Vault City.}
{322}{}{Dobøe, e jsem si staèil pøekontrolovat zbranì.}
{323}{}{Pokud by mì dostali, nepohøbívejte mì tady.}
{324}{}{Dávejte tu velkı pozor. Místní nevypadají moc pøátelsky.}
{325}{}{He. Nevìøil jsem, e nìkdy spatøím San Francisco.}
{326}{}{Nevìøil jsem, e bys vytáhnul starocha jako já na takovou cestu. Udìlejme, co musíme a vrame se domù.}
{327}{}{Redding je tìební mìsto. Tìí se tu hlavnì zlato. Do Vault City odsud pøijídí hodnì karavan.}
{328}{}{Broken Hills je tìební mìsto. Tìí se tu hlavnì uranová ruda. Mùe to tu bıt docela drsné, take radši bacha.}
{329}{}{Jsem nìjakı pøiotrávenı, nemáte nìkdo protijed?}
{330}{}{Svítím jak támhleten neon. Máte nìkdo protiradiaèní tablety?}
{331}{}{Tady mì to strašnì bolí. Máte nìkdo stimpaky?}
{332}{}{Dávej si pozor, Myron. Sleduju tì.}
{333}{}{Udìlej falešnej krok, Myrone a rozseknu tì vedví.}
{334}{}{Fuj, Lenny, potøebuješ vykoupat. Nebo nìjakou desinfekci.}
{335}{}{Ghoulíku, radši si udruj odstup. Fùùùùùj, ty ale páchneš.}
{336}{}{To je ten nejzlejší pes, co jsem kdy vidìl.}
{337}{}{Klídek, pejsku.. Cassidy je tvùj kámoš, ne?}
{338}{}{Co asi takovej kyberpes jí. Pravdìpodobnì lidi.}
{339}{}{Jestli mì ten kyberpes kousne do nohy, na místì ho odprásknu.}
{340}{}{Ahhhh. Hochu, mám takovou radost, e vyrobili miliony tìchhle vìcí, ne spadly bomby.}
{341}{}{Díky, kámo.}
{342}{}{Snad to nijak neublíí mému srdci, kdy si vezmu tyhle stimpaky...}
{343}{}{Co sakr--?! Ne, moje srdce! Já...*hrrrkkk*}
{344}{}{Pardon, Jen jsem se kochal vıhledem.}
{345}{}{Sakra, prostì si stoupnu támhle.}
{346}{}{Omlouvám se. Pøíteli. Nechtìl jsem ti stát v cestì.}
{347}{}{Ahhhhh. To je pøesnì ono. Díky moc.}
{348}{}{*Hic* He-he. Není nic lepšího na rozproudìní krve, ne stará dobrá ohnivá voda..}
{349}{}{Díky. Sakra, nedáš si taky?}
{350}{}{Támhleto je Vault. Obrovská pitomá vìc, co?}
{351}{}{Chceš, abych se k tobì zase pøidal?}
{352}{}{Pùjdu kamkoli pùjdeš ty.}
{353}{}{Urèitì nepotøebuješ mou pomoc?}
{354}{}{U se tøesu na cestu.}
{355}{}{Jasnì, e mùeme vyrazit.}
{356}{}{Táta mì pojmenoval podle postavy z nìjakého pøedváleèného komiksu. Øíkal, e to byl taky pìknej parchant.}
{357}{}{Je to fajn, bıt zase na cestách. Ze ivota ve Vault City u jsem mìl vøedy.}
{358}{}{Doufám, e srdce mì na cestách nebude zlobit...}
{359}{}{Dal bych si panáka.}
{360}{}{Radìji si ještì zkontroluju vıbavu.}
{361}{}{Podìlaná artróza...}
{362}{}{Bıt mi o dvacet míò, vyrazil bych na vıchod a prozkoumal Støedozápad. Ale mám pocit, e u je pozdì.}
{363}{}{Slyšel jsem, e na Støedozápadì mají tornáda o prùmìru pøes míli. Je z nìj teï obrovská radioaktivní pánev.}
{364}{}{Jestlipak Texas pøeil válku...}
{365}{}{Díky, pøíteli. Já...jejda. Nìjak se mi najednou kalí zrak.}
{366}{}{Slyšel jsem, e tohle vyvolává halucin...jéje! Odkud se tu vzali všichni ti hadi?!}
{367}{}{Kdykoli si tohle dám, vrací se mi vzpomínky.}
{368}{}{Nic se nevyrovná troše barbarského léèitelského umìní...}
{369}{}{Asi si tu pùjèím nìjaké berle a vozík.}
{370}{}{Cassidy umøel na zástavu srdce.}
{371}{}{Pøesvìdèil jsi Cassidyho, aby se k tobì pøidal.}

{1000}{}{Dobøe...tak teda jo. Poèkám tu, ne se vrátíš. }
{1100}{}{Jasnì. Nemùu ale slíbit, e ji nevytasím, kdy zas nastanou potíe..}
{1200}{}{Fajn, budu ti co nejblí, asi nastanou potíe, co.}
{1300}{}{Jo, budu si udrovat odstup. Mám tak mnohem lepší vıhled.}
{1400}{}{Jasnì, budu ti krıt záda. Pokud budeš v problémech, zaøvi, a já hned pøiklušu.}

{2000}{}{Nechci tì urazit nebo tak, ale nevypadáš, e bys mohl nìkoho vést. Mám dojem, e v pustinách si z tebe udìlají obìd.}
{2100}{}{Ne, necestuju s otrokáøi. Mají takovı nepìknı zvyk prodat tì, kdy jim dojdou peníze. Bez uráky.}
{2200}{}{Ne, vypadáš na èlovìka s jednou nohou v hrobì a druhou v pekle. Nemyslím, e bych ještì potøeboval sniovat svou, u tak dost chabou povìst.}
{2300}{}{Ne...zdá se, e u kolem sebe máš obstojnej hlouèek.}
{2400}{}{Tak fajn, jo.}

{2999}{}{Fajn, dej na sebe pozor.}
{3000}{}{Mùeme vyrazit.}
{3100}{}{Zapomeò na to pitomèe.}
{3200}{}{No tak nic, tvoje mínus.}

{4100}{}{Fajn, jsem v poøádku. Mùeme jít.}
{4200}{}{Fajn, skoro všechno je v poøádku.}
{4300}{}{U je to lepší, ale potøeboval bych ještì pár stimpakù.}
{4400}{}{Pouil jsem, co jsem mohl, ale jsem na tom poøád dost špatnì. Mùu sice chodit, ale pokud máš nìjaké stimpaky, urèitì by se mi hodily.}

{9999}{}{Chtìl jsem se tì na nìco zeptat...}
{10001}{}{Vezmi si pár stimpakù a uzdrav se.}
{10002}{}{Cassidy, poèkej tady, ne se vrátím.}
{10003}{}{Schovej zbraò.}
{10004}{}{Dr se mi poblí.}
{10005}{}{Moc se nevzdaluj.}
{10006}{}{Zvìtšíme trochu rozestup.}
{10100}{}{No tak, Cassidy. Musíme se rozejít.}
{10007}{}{Tak pojïme.}

# NEW TOM PARTY MEMBER ADDITIONS

# NODE 1007 WE NEED TO CHANGE DISTANCE
{20000}{}{Tak jo, poslouchám.}

# NODE 1008 TALK ABOUT GEAR
{20001}{}{Moje vıbava? Co je s ní?}

# NODE 1009 REMOVE ARMOR
{20002}{}{V pohodì. Stejnì je tu na to moc horko. Potím se v tom jako dìvka z New Reno.}

# NODE 1010 WHAT WEAPONS CAN YOU USE -- DAN NEEDS TO REPLACE THIS.

# NODE 1100 CAN'T JOIN PARTY BECAUSE LOW CHR -- DAN NEEDS TO REPLACE THIS.

# We need to change our distance from one another
{20003}{}{Zkusíme jiné rozestavìní.}
# I need to talk to you about your gear.
{20004}{}{Musíme si promluvit o tvé vıstroji.}
# On second thought, I think this distance is OK for now.
{20005}{}{Nebo ne. Necháme rozestavìní, jaké bylo doposud.}
# Actually, I guess there's nothing I need to really know right about your gear.
{20006}{}{Vlastnì nic. Teï o tvé vıstroji nepotøebujeme mluvit.}
# I need to remove the armor that you're wearing.
{20007}{}{Potøebuju, abys sundal tu zbroj, co máš na sobì.}
# I need to know what kind of weapons you can use. Transplant original comment from Question Node Line: 264
