#tento soubor prelozil Tomas "LOCKHEAR" Jurecka
{100}{}{Vidíš Charlieho.}
{101}{}{Vidíš vyzáblého muže. Vlasy má v rùznì velkých chomáèích pøiplácnuté k hlavì a kùže mu volnì plandá na tìle.}
{102}{}{Vidíš Charlieho.}
{103}{}{Vidíš vyzáblého muže. Vlasy má v rùznì velkých chomáèích pøiplácnuté k hlavì a kùže mu volnì plandá na tìle.}
{104}{}{Vidíš vyzáblého muže... vypadá, že prošel jedovatým ozáøením.}
{105}{}{Vidíš Charlieho.}
{106}{}{Vidíš vyzáblého muže... vypadá, že prošel nìjakým jedovatým ozáøením.}
{107}{}{Vidíš Charlieho... Vypadá že pøibral na váze a klidnì dýchá.}
{108}{}{Vidíš Charlieho.}
{109}{}{Vidíš Charlieho... Vypadá že pøibral na váze a klidnì dýchá.}
{110}{}{Tento muž má otravu z ozáøení. Tvé schopnosti mu nemohou pomoci. Potøebuje léky.}
{111}{}{Tento muž vypadá, že je ve strašném stavu. Nevíš jistì, co by mu mohlo být.}
{112}{}{Díky, ale jsem v poøádku, opravdu. Ten RadAway mi pomohl.}
{113}{}{Našel jsi žílu a skrz ní napumpoval RadAway Charliemu do tìla.}
{114}{}{*Urhkkkk*...}
{115}{}{3 Vteøiny}
{116}{}{Unhhhhh...*škyt* *škyt*...}
{117}{}{3 Vteøiny}
{118}{}{Hrnnhhhh...eh...ahhhhh}
{119}{}{3 Vteøiny}
{120}{}{Co se stalo? Cítím se mnohem lépe.}
{121}{}{Vyléèil jsi Charlieho.}
{122}{}{*Errhhhhhh*}
{123}{}{*Hvízd*}
{124}{}{*Škyt-Škyt*}
{125}{}{*Urhkkkk*}
{126}{}{Naposledy jsem pil tu zatracenou vodu v tomhle pøedmìstí, to je jistá vìc.}
{127}{}{Jsem pøekvapený, že ještì nesvítím...}
{128}{}{Bezva, ten RadAway mì opìt rozhýbal...}
{129}{}{Díky cizinèe. Vážím si Tvé pomoci... Nemohu si totiž dovolit AutoDok.}
{130}{}{Chtìl bych se ti odmìnit, ale nemám ani dvì babky po hromadì.}
{131}{}{To je naposled jsem v tomhle pøedmìstí pil tu zatracenou vodu, to pøísahám.}
{132}{}{Jsem pøekvapený, že ještì nesvítím...}
{133}{}{No do pytle, ten Rad-Away mì opìt rozhýbal...}