#tento soubor prelozil Tomas "LOCKHEAR" Jurecka
{100}{}{Vidíš Cheta, šéfa nedovolenıch akcí.}
{101}{}{Vidíš chytøe vypadajícího mue obleèeného v kombinéze Vaultu 13.}
{102}{}{Vidíš Cheta, šéfa nedovolenıch akcí.}
{103}{}{Vidíš chytøe vypadajícího mue obleèeného v kombinéze Vaultu 13.}
{104}{}{Vítám Tì. Jsem šéf nedovolenıch akcí... ale mùeš mi øíkat Chet. Co bys rád?}
{105}{}{Ještì nìco jiného?}
{106}{}{Ukonèi hru, Chete. Se vším jsem ji hotov.}
{107}{}{Udìlej ze mne kapitána stráí. Hned.}
{108}{}{Jestli Tì mohu poprosit,  tak ze mne udìlej rovnocenného obèana.}
{109}{}{Udìlej ze mne falešného obèana a dej mi doklady.}
{110}{}{Udìlej ze mne vyhostìného obèana.}
{111}{}{Pozmìò mou reputaci.}
{112}{}{(Nefunguje) Potøebuju kámoše do party.}
{113}{}{Nic.}
{114}{}{Heee?}
{115}{}{Chci bıt otrokáø.}
{116}{}{Zabiják dìtí taky není špatnı.(Zvláš po jejich celodenním hlídání).}
{117}{}{Celkem nic... jenom mi sni karmu o 100.}
{118}{}{Nevadí...Chci nìco jiného}
{119}{}{Nic.}
{120}{}{Kdo?}
{121}{}{Marcus.}
{122}{}{Lenny.}
{123}{}{Vic.}
{124}{}{Myron.}
{125}{}{Nikdo. Potøebuji jich víc.}
{126}{}{Nevadí... mìj se..}
