# Tento soubor pøeložil Petr "Lee" Bulíø.......Level
{100}{}{Vidíš špinavého, silnì vypadajícího chlápka.}
{101}{}{Vidíš Connara.}
{102}{}{Hej ty! Co to dìláš!}
{103}{}{Zùstaò kde jsi, cizinèe. Co tady pohledáváš?}
{104}{}{Vyvražïuju tady všechny potvory.}
{105}{}{Proè, co ti je po tom?}
{106}{}{Proè øveš!}
{107}{}{Vsadil bych se, že tì poslali ty bastardi z Vault City. Radìji bys mìl jít a nechat tu všechno ostatní žít.}
{108}{}{No, na to už je trochu pozdì.}
{109}{}{Proè?}
{110}{}{Promiò, mám nìjakou práci.}
{111}{}{Tyhle potvory jsou jedinou vìcí, která brání lidem z Vault City udìlat si z nás takzvané služebníky.}
{112}{}{Ale oni mì platí za to, abych je tìch potvor zbavil, a to je pøesnì to, co hodlám udìlat.}
{113}{}{To mi neøekli.}
{114}{}{Zaplatili mi, abych je všechny vybil, a teï je to hotovo.}
{115}{}{Ty idiote! Proè si to k èertu udìlal!}
{116}{}{Potøebuju peníze.}
{117}{}{Víš, jestli si to opravdu udìlal, pøijdou si pro nás.}
{118}{}{To není mùj problém.}
{119}{}{Doufám, že jsi to poøádnì ucpal. Brzo si pro nás pøijdou.}
{120}{}{Nevìdìl jsem, že to chtìjí udìlat kvùli tomu.}
{121}{}{Jo, stejnì s takovými, jako jsi ty, nejednám.}
{122}{}{Bohužel ti nemùžeme dovolit to udìlat.}
{123}{}{Udìlej, co udìlat máš.}
{124}{}{Takže ty jsi jim uvìøil pro jejich dobré oèi? Ještì sem musíš hodnì uèit, pøíteli.}
{125}{}{Je tu nìco, s èím bych mohl pomoci?}
{126}{}{Chlapci z Vault City nepatøí k nejstateènìjším. Když budeme jen trochu bojovat, uteèou daleko do kopcù. Kdybychom mìli pár zbraní, mohli bychom se jim postavit.}
{127}{}{Jaký druh zbraní?}
{128}{}{No, já to umím s brokovnicí a pak tu máme pár lidí, kteøí si rozumí s puškou. Myslím, že tøi by urèitì staèili.}
{129}{}{Uvidím, co se dá dìlat.}
{130}{}{Nejsi tu vítán. Odejdi.}
{131}{}{Rozmyslel jsem si to. S èím vám mohu pomoci?}
{132}{}{Dobrá, stejnì tu nebudeš pøíliš dlouho.}
{133}{}{Jako kdybych se o to postaral sám.}
{134}{}{Vrátil ses! Máš pro nás ty zbranì?}
{135}{}{Co že jsi to vlastnì potøeboval?}
{136}{}{Jo, tady to je.}
{137}{}{Potøebujeme tøi pušky a brokovnici. Èím døív nám je pøineseš, tím líp.}
{138}{}{Ok.}
{139}{}{S tímhle už tady bìhem pár mìsícù mùžeme nìco udìlat. Kdyby sis potøeboval nìkdy odpoèinout, vždy tu budeš vítán.}
{140}{}{Není zaè.}
{141}{}{Vítej zpátky. Jde to docela dobøe. Právì teï hodláme rozšiøovat vesnici.}
{142}{}{Zdravíèko! Jak vidíš, šlo to celkem dobøe. Jestli máš èas, porozhlédni se okolo.}
{143}{}{Poøád ještì stavíme. Doufáme, že pøíští mìsíc znovu zvýšíme obranné zdi.}
{144}{}{Zdravím! Jak jsme doufali, vesnice se znovu rozšíøila. Jsi vítán, jako vždy.}
{145}{}{Teï už se lidí z Vault City nemusíme bát a mùžeme tu žít v klidu a míru.
 Ještì jednou díky cizinèe.}
{146}{}{Jen už tam venku nic nezabíjej ty naivko.}
