# Tento soubor pøeloil Petr "Lee" Bulíø.......Level
{100}{}{Vidíš barmana.}
{101}{}{Vidíš vysokého mue v elegantním obleku. Zírá pøímo pøed sebe a vùbec nevìnuje pozornost patronùm okolo sebe.}
{102}{}{Vidíš barmana.}
{103}{}{Tenhle chlap vypadá kamennì. Jestli tì zpozoruje, nedá to na sobì znát.}
{104}{}{Co takhle nìco k pití hrdino?}
{105}{}{Vítej hrdino. Prosím, vezmi místo na baru.}
{106}{}{Prosím! Posaï se a chvíli si odpoèiò!}
{107}{}{Dobrı den, Kapitáne.}
{108}{}{A ije Vault City, Kapitáne.}
{109}{}{Dobrı den Obèane.}
{110}{}{A ije Vault City, Obèane.}
{111}{}{Mutant! Stráe! Stráe!}
{112}{}{Ghoul! Stráe! Stráe!}
{113}{}{Lituji, ale bar se na veèer zavírá.}
{114}{}{Bar je zavøenı. Pùjdu domù, a tady dodìlám práci s tím seznamem.}
{115}{}{Nemáš snad, kam bys šel?}
{116}{}{Vítej! Všichni jsme tady slyšeli o tvıch hrdinskıch èinech proti Enklávì. Mùu ti nabídnout nìco k pití?}
{117}{}{Ehmm - Ehmm}
{118}{}{Odpal}
{119}{}{Jakı tu máte toèenı?}
{120}{}{Shánìl jsem nìjakou informaci.}
{121}{}{Dneska nic, díky.}
{122}{}{Heh-heh, "Ehmm-Ehmm" tobì taky. Prosím, dávej na sebe tam venku v pustinì pozor.}
{123}{}{Oh ne- Oh ne!}
{124}{}{Odsockuj}
{125}{}{Co pro vás mohu udìlat, Kapitáne?}
{126}{}{Co pro vás mohu udìlat, Obèane?}
{127}{}{Ano? Mùu vám nìjak pomoci?}
{128}{}{Awnt-awnt}
{129}{}{Zmizni}
{130}{}{Jakı tu máte toèenı?}
{131}{}{Shánìl jsem nìjakou informaci.}
{132}{}{Dneska nic, díky.}
{133}{}{Ano, "ehmm - ehmm" tobì taky. Poèkej chvíli, ne ti zavolám stráe "ehmm - ehmm" k pøední bránì.}
{134}{}{Urnt? Urnt-urnt.}
{135}{}{Shamble off}
{136}{}{"Toèenı?" Jak... pùvabné.}
{137}{}{Máme minerálku, destilovanou vodu a vodu s bublinkama. Taky máme nìkolik druhù syntetického alkoholu.}
{138}{}{Uh... a jaké druhy teda máte?}
{139}{}{Uh, máte nìjaké opravdové pití?}
{140}{}{Nìjaká ta voda by staèila.}
{141}{}{Nevadí. Shánìl jsem se po nìjaké informaci.}
{142}{}{Dneska nic, díky.}
{143}{}{Velmi dobøe, pane.}
{144}{}{Velmi dobøe, paní.}
{145}{}{Kterou byste rád? Minerální? Destilovanou? Nebo s bublinkama? Cena je mírná, pìt dolarù za sklenici.}
{146}{}{Minerálku prosím.}
{147}{}{Dal bych si trochu destilky.}
{148}{}{No, kopnu do sebe trochu té s bublinkama.}
{149}{}{Jaké druhy syntetického alkoholu máte?}
{150}{}{Nevadí. Shánìl jsem nìjakou informaci.}
{151}{}{To mi moc nepomùe. Vrátím se, a budu mít víc penìz.}
{152}{}{Myslím, e to nechám bıt, díky.}
{153}{}{Máme syntetické deriváty H a T a právì teï jsme uvaøili velmi populární mix, "Alkohol-Z," kterı má bohatou mikro-pivní chu. Cena je mírná. Dvacet dolarù za sklenici.}
{154}{}{Jak tenhle syntetickı alkohol vyrábíte?}
{155}{}{Uh, máte nìjaké opravdové pití?}
{156}{}{Dám si ještì nìjakou vodu, myslím.}
{157}{}{Hmmm. Zkusím trochu toho delikatesního Alkoholu-Z.}
{158}{}{Co se dá dìlat. Shánìl jsem se po nìjaké informaci.}
{159}{}{To mi nestaèí. Vrátím se, a budu mít víc penìz.}
{160}{}{Dnes nic, díky.}
{161}{}{Chtìl bys nìco jiného?}
{162}{}{Dal bych si ještì trochu vody, díky.}
{163}{}{Jaké druhy syntetického alkoholu máte?}
{164}{}{Shánìl jsem se po nìjaké informaci.}
{165}{}{Dneska nic, díky.}
{166}{}{Je vám dobøe pane? Vypadá to, jako kdyby na vás nechalo pití Alkoholu-Z vedlejší následky. Jste si jist, e chcete další?}
{167}{}{Je vám dobøe pane? Vypadá to, jako kdyby na vás nechalo pití Alkoholu-Z vedlejší následky. Jste si jist, e chcete další?}
{168}{}{Ještì nìco jiného?}
{169}{}{Necítím se pøíliš dobøe...Musím teï na chvíli pøestat mluvit a zkontrolovat svoje hit body.}
{170}{}{Ne, ne, cítím se skvìle! Musím jen na chvíli pøestat mluvit a zkontrolovat svoje hit body.}
{171}{}{Dám si jen nìjakou vodu, myslím}
{172}{}{Dám si ještì trochu toho delikatesního Alkoholu-Z.}
{173}{}{Jak tyhle syntetické alkoholy vyrábíte?}
{174}{}{Vlastnì, pídil jsem se po nìjaké informaci.}
{175}{}{Dneska u nic dalšího, díky.}
{176}{}{AutoDok ve Vault City je schopen destilovat syntetické substance pro substance aditivní. Z toho, co jsem pochopil, byly tyto látky pouívány jako placeba v lécích pøed válkou.}
{177}{}{Vidím, e ti díky syntetikùm skvìle kvete obchod.}
{178}{}{Uh, máte nìjaké skuteèné pití?}
{179}{}{Oh. Dobrá, dal bych si tedy nìjakou vodu.}
{180}{}{Hmmm. Zkusím trochu toho Alkoholu-Z.}
{181}{}{Zajímavé. Hledám tady nìjakou informaci...}
{182}{}{Rozumím. Dík za info. Nashle.}
{183}{}{Pomáhal jsem nìkolik málo mìsícù Dr. Troyovi, ne mì sem pøidìlili. Vyadoval, abych dokonale znal zdravotnickou databázi Vault City.}
{184}{}{"Znal?" To znamená, e tì mùe poprosit, aby ses legálnì hrabal v poèítaèi?}
{185}{}{Zdravotnická databáze?}
{186}{}{Zajímavé. Sháním tu nìjakou informaci...}
{187}{}{Rozumím. Dík za informaci. Nashledanou.}
{188}{}{Uh..."znal" To znamená, e se v tom vyznáš.}
{189}{}{Huh. No dobrá, kdy ti to udìlá dobøe, tak jo. Co to bylo s tou zdravotnickou databází?}
{190}{}{Hledal jsem trochu nìco jiného...}
{191}{}{Jestli ti odmítnutí udìlá dobøe, pochopím to. Promluvím si s tebou pozdìji.}
{192}{}{Ano, pár poèítaèù v prvním patøe Vaultu obsahuje široké spektrum zdravotnickıch informací. To je opravdu fascinující, aèkoliv, pokud nemáte zdravotnické vzdìlání, mùe bıt argon trochu zmateènı.}
{193}{}{argon? To je ten co má na starosti poèítaèe?}
{194}{}{Zajímavé. Potøebuji získat jednu informaci...}
{195}{}{Hmmmm. Moná bych je mìl potom zkontrolovat.}
{196}{}{Ale ne. "argon" je hantırka nebo terminologie, pouívaná v souvislosti s urèitou profesí.}
{197}{}{Uh, ale jistì, samozøejmì. Jen jsem tì zkoušel. Øíkal jsem, e sháním nìjakou informaci...}
{198}{}{Kdy to øíkáš. Jen dej tomu chlápkovi vìdìt, e si s ním potøebuji promluvit? Zatím.}
{199}{}{Jestli máš na mysli alkohol, kterı je bìnı v pustinì, tak ne.}
{200}{}{Nikdy jsme nepodlehli potøebì zamoøit náš systém bakteriálním èistícím roztokem. Ten bar na pøedmìstí by mìl bıt ménì... diskriminován.}
{201}{}{Dám si jen nìjakou vodu.}
{202}{}{Poèkej chvilku. Jaké syntetizované pití máte?}
{203}{}{Shánìl jsem nìjakou informaci.}
{204}{}{Pak se na to mrknu, díky.}
{205}{}{Tak to snad pùjdu radìji jinam.}
{206}{}{Tak to bys moná potom mìl navštívit naše informaèní centrum ne tenhle ústav. Je to v centru. Teï u bì... mám další zákazníky.}
{207}{}{Poèkej, Dal bych si nìco k pití. Jakı pivo tady toèíte?}
{208}{}{Ne, nejdøív my øekni ty, co já chci vìdìt a odpustíš si pøitom tón svého hlasu, jestli si rozumnı a víš, co je pro tebe dobré.}
{209}{}{Tak jo. Mìj se.}
{210}{}{Samozøejmì. Co chcete vìdìt, pane?}
{211}{}{Samozøejmì. Co chcete vìdìt, madam?}
{212}{}{Samozøejmì. Co chcete vìdìt, Kapitáne?}
{213}{}{Samozøejmì. Co chcete vìdìt, Obèane?}
{214}{}{Mùeš mi øíci, kdo je ve Vault City šéfem?}
{215}{}{Mùeš mi øíct nìco o zdejším otroctví?}
{216}{}{Chtìl jsem nìco k pití. Co máte za pivo?}
{217}{}{Dneska nic, díky.}
{218}{}{Proè, samozøejmì první Obèan Lynette. Je prvním Obèanem ji druhım obdobím. Zodpovídá se sice mìstské radì, ale je nejvíce zodpovìdná za legislativní jádro zdejšího Vault City.}
{219}{}{Mìstské Radì?}
{220}{}{Mùeš mi øíci nìco o zdejším otroctví?}
{221}{}{Chtìl bych nìco k pití. Co se tu toèí?}
{222}{}{Zajímavé. Dík za informaci. Nashledanou.}
{223}{}{Ano, je zde taky mìstská rada. Její mluvèí je radní senátor McClure. (Naklání se.) Ve skuteènosti, se ale McClure s první Obèankou nemají moc v lásce.}
{224}{}{Opravdu...?}
{225}{}{Mùeš mi povìdìt nìco o zdejším otroctví?}
{226}{}{Chtìl jsem nìco k pití. Jakıho tu máte zrzka?}
{227}{}{Zajímavé. Díky za informace. Na shledanou.}
{228}{}{Oh, ano. Nedávno, nìkolik obèanù písemnì poádalo McClura a mìstskou radu, aby zrušili nìkterá rozhodnutí první Obèanky. Udìlalo to slušnej zmatek, to ti teda øeknu.}
{229}{}{Hmmm. Zajímalo mì trochu nìco jiného...}
{230}{}{Aha. Dobrá, dal bych si nìco. Co se tu toèí?}
{231}{}{Zajímavé. Díky za informaci. Nashle.}
{232}{}{Oh, ne, ne...to není otroctví. Ti lidé, které vidíš pracovat ve mìstì jsou sluebníci...vèetnì mì. Zacházejí s námi velmi dobøe, uèí nás èíst, psát, máme kde bydlet a máme i jídlo a lékaøskou péèi.}
{233}{}{Všechno kromì vaší svobody, huh?}
{234}{}{Pokud ty sám nemáš ádné námitky, pak to není problém. Zapomeò, e jsem se ptal.}
{235}{}{Dal bych si nìco k pití. Co se tu toèí?}
{236}{}{Chápu. No, dík za tvùj èas. Nashledanou.}
{237}{}{Madam, jestli si neobjednáte nic k pití, asi byste mìla odejít.}
{238}{}{Pane, jestli si neobjednáte nic k pití, asi byste mìl odejít.}
{239}{}{No, jestli nemáš nic proti svému...nevolnictví, pak to není problém. Zapomeò, e jsem se ptal.}
{240}{}{Dám si nìco k pití, co vám tu protejká pípou?}
{241}{}{Snad radši pùjdu. Nashle.}
{242}{}{Jasnì. Je tu nìco s èím bych mohl pomoci?}
{243}{}{Tak si dám nìco k pití. Jakı pivo tu toèíte?}
{244}{}{Dnes ne. Nashledanou.}
{245}{}{Chrrrrrrr.}
