# Tento soubor pøeloil Petr "Lee" Bulíø.......Level
{100}{}{Vidíš Curtise.}
{101}{}{Vidíš malého chlapce s hnìdımi vlasy. Vypadá to, e ještì pøed chvílí plakal.}
{102}{}{Vidíš Curtise.}
{103}{}{Vidíš malého chlapce s hnìdımi vlasy. Vypadá to, e ještì pøed chvílí plakal.}
{104}{}{Vidíš malého chlapce s hnìdımi vlasy. Vypadá, e je mnohem šastnìjší ne pøed tím}
{105}{}{Vidíš Curtise.}
{106}{}{Vidíš malého chlapce s hnìdımi vlasy. Vypadá, e je mnohem šastnìjší ne pøed tím.}
{107}{}{*smrk smrk*}
{108}{}{Dal byste si èaj, pane Nixone?}
{109}{}{"Proè ne, velmi rád, Curtisi."}
{110}{}{Tady to je. Na vaše zdraví!}
{111}{}{"Díky, Curtisi."}
{112}{}{Já dìkuju VÁM, pane Nixone.}
{113}{}{"Chceš jít vykopat tátùv francouzák?"}
{114}{}{Ne, pane Nixone. Táta se zblázní, a zjistí, e jsme ho zakopali.}
{115}{}{"Ale je zakopanı pod tìmi kameny, pøesnì za barem. Mùeme na to jít hned teï."}
{116}{}{Ne. Táta se zblázní. Je lepší lhát, pøesnì jak jste mi radil, pane Nixone.}
{117}{}{Ztratil jsem pøítele, kdy jsem si hrál na pøedmìstí. Jeho jméno je pan Nixon.}
{118}{}{Pan Nixon má modrou košili a velkı nos a je hroznì, ale opravdu hroznì malı.}
{119}{}{Vidìl jsi pana Nixona? Ztratil se mi.}
{120}{}{Díky es mi našel pana Nixona. On ti také vzkazuje své díky.}
{121}{}{Jù ten mutant je strašidelnı.}
{122}{}{Jù ten ghoul je strašidelnı.}
{123}{}{Jù ten kovovı pes, vypadá jako kdyby mì chtìl serat.}
{124}{}{Ztratil jsem pana Nixona. U ani nevím, kde jsem ho nechal.}
{125}{}{Teeeennnhle Nixxson?}
{126}{}{Zmizni}
{127}{}{Je to on? Taky u se po tobì shánìl.}
{128}{}{Mám pana Nixona právì tady. Ale víš ty co? Myslím, e pan Nixon by mìl potrestán za to, e odešel bez dovolení. Podle øádu musím vykonat takovı rituál. Take mu nejdøíve odstraním obì ruce a potom...}
{129}{}{Ani já ne.}
{130}{}{Našel jsi ho! Našel jsi pana Nixona!}
{131}{}{Nashlee panee Nixxson}
{132}{}{Jistìe ano. Neodešel daleko. Dávej na nìj odteïka trochu pozor, jo?}
{133}{}{NE! NEEEEEE! Nedìlej to! Zastav to! Zasta--}
{134}{}{Ouha. Vypadá to, e pan Nixon byl trochu køehèí, ne se mi zdálo. Sorry chlapèe.}
{135}{}{Pan Nixon jednou povstane z hrobu a zabije tì}
{136}{}{Pan Nixon tì bude pronásledovat do konce ivota. Myslím to vánì.}
{137}{}{A vyrostu, tak ty budeš starı, a já ti pak udìlám to, co jsi ty provedl panu Nixonovi.}
{138}{}{Vrátil jsi pana Nixona Curtisovi.}
{139}{}{Nauèil jsi Curtise, e ivot je krutı a nespravedlivı.}
