#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Vidíš Lıdii.}
{101}{}{Vidíš hnìdovlasou enu, odìnou v hnìdém pracovním odìvu a kovovém brnìní. Vypadá na barmanku.}
{102}{}{Vidíš Lıdii.}
{103}{}{Vidíš hnìdovlasou enu, odìnou v hnìdém pracovním odìvu a kovovém brnìní. Vypadá na barmanku.}
{104}{}{Vítej! Dáš si sklenku, Vyvolenı?}
{105}{}{Vítej Vyvolenı! Prosím, posaï se u baru.}
{106}{}{Prosím! Vezmi místo a chvíli se pozdr!}
{107}{}{To je Vyvolenı! Kadı pozvednìte èíši na HRDINU Falloutu 2!}
{108}{}{Dobrı den, kapitáne.}
{109}{}{Vault City má vdy navrch, kapitáne.}
{110}{}{Dobrı den, Obèane.}
{111}{}{Vault City má vdy navrch, Obèane.}
{112}{}{Mutant! Stráe! Stráe!}
{113}{}{Ghoul! Stráe! Stráe!}
{114}{}{Máme zavøeno. Pøijïte ráno.}
{115}{}{Sorry, poslední návštìvy právì skonèily. Pøijï ráno.}
{116}{}{Máme zavøeno. Jen co dodìlám to svoje papírování, zavírám.}
{117}{}{Hej, to je Vyvolenı! Právì jsme si vykládali o tvıch dobrodrustvích... mùu ti koupit nìco k pití?}
{118}{}{Kdo whisky nepije, ten se poblije}
{119}{}{Belhám se pryè}
{120}{}{Co tu èepujete?}
{121}{}{Chci nìjaké informace.}
{122}{}{Mám tu pro tebe tu zásilku alkoholu.}
{123}{}{Dnes nic, díky.}
{124}{}{Uch... tak já páchnu. Ehm, znovu díky za záchranu svìta a nás všech.}
{125}{}{A kdo pivo nepije, ten a se pochèije!}
{126}{}{Belhám se pryè}
{127}{}{Podívej, moná jsi zachránil svìt a nás všechny, ale dobrı vypravìè zrovna nejsi. Radši toho nech.}
{128}{}{Brum, brum, brum zboøím celej dùm!}
{129}{}{Belhám se pryè}
{130}{}{Heleï poslechni moji radu a jdi odsud, okej? A radìji nechej svou hubu chvíli zavøenou.}
{131}{}{Díky ti, ty mùj pumprïouši}
{132}{}{Belhám se pryè}
{133}{}{Uh...pro vás mohu udìlat, kapitáne?}
{134}{}{Co pro tebe mùu udìlat, Obèane?}
{135}{}{Ano? S èím ti mohu pomoci?}
{136}{}{Ty? Thıı? Jóó? Jo. To mì snad šálí vokóo}
{137}{}{Belhám se pryè}
{138}{}{Co tu èepujete?}
{139}{}{Chci nìjaké informace.}
{140}{}{Mám tu pro tebe tu zásilku alkoholu.}
{141}{}{Dnes nic, díky.}
{142}{}{To jsou asi ty nejpodivuhodnìjší vìci, jaké jsem kdy slyšela. Vydr chvilku... chci aby si to poslechli i strání.}
{143}{}{Joo? Ty prïo. A co teprvá to co mám ve slipech}
{144}{}{Belhám se pryè}
{145}{}{Máme tu syntetická piva a lihoviny...vodku-H, deriváty tequily W a W2. Jo, a vodu. A brahmíní mléko. Pivo èi lihoviny jsou za $10, voda a mléko stojí $3.}
{146}{}{Jako tøeba...?}
{147}{}{Ale... to nemáte nìjakı opravdovı alkohol?}
{148}{}{Dám si syntetické pivo.}
{149}{}{Syntetická vodka by fakt bodla.}
{150}{}{Tequila W2 by byla vıborná.}
{151}{}{Voda by byla vıborná.}
{152}{}{Brahmíní mléko.}
{153}{}{Momentálnì chci nìjaké informace.}
{154}{}{Pøijdu a budu mít více penìz.}
{155}{}{Myslím, e zase pùjdu, díky.}
{156}{}{Brahmíní mléko neèepujeme... toti, ne tak docela. Musela bych jít ven a rychle nìjaké sehnat.}
{157}{}{To je hezkı. Nemíním však èekat. Nechám si zajít chu, na sklenici èerstvého mléka. Mmmmm-mmm. Ale bodlo by.}
{158}{}{Myslím, e tedy zkusím nìco jiného.}
{159}{}{No nic. Chci tedy aspoò nìjaké informace...}
{160}{}{Zapomeò na to. No, nìkdy se zase stavím.}
{161}{}{Tady to je. Ještì nìco?}
{162}{}{Ehm... a to nemáte nìjakı opravdovı alkohol?}
{163}{}{Dám si syntetické pivo.}
{164}{}{Syntetická vodka by fakt bodla.}
{165}{}{Tequila W2 by byla vıborná.}
{166}{}{Voda by byla vıborná.}
{167}{}{Brahmíní mléko.}
{168}{}{Momentálnì chci nìjaké informace.}
{169}{}{Pøijdu a budu mít více penìz.}
{170}{}{Myslím zase pùjdu, díky.}
{171}{}{Tak? Co konkrétnì?}
{172}{}{Kdo má na starosti Vault City?}
{173}{}{Kde je Vault?}
{174}{}{Mùeš mi povìdìt o otroctví ve Vault City?}
{175}{}{Má Vault City nìjaké kontakty se okolním svìtem?}
{176}{}{Co tu èepujete?}
{177}{}{Mám tu pro tebe tu zásilku alkoholu.}
{178}{}{Nic u nepotøebuji. Pøeji hezkı den.}
{179}{}{No, První Obèanka Lynett pøece. Poslyš... jsi ty Obèan, nebo ne?}
{180}{}{První Obèanka Lynett. Je v radnici, smìrem na sever, jestli s ní potøebuješ mluvit.}
{181}{}{Chci ještì nìco vìdìt...}
{182}{}{Dobrá. Pùjdu si s ní promluvit.}
{183}{}{No, to je pøece ten velkı otvor ve skále, na vıchod odtud... øekni mi, jsi Obèan nebo ne?}
{184}{}{Je to ten velkı otvor v hoøe na vıchod odsud. Nemùeš to minout. Ale dovnitø se nedostaneš, pokud nejsi Obèan.}
{185}{}{Chci ještì nìco dalšího...}
{186}{}{Ale já jsem Obèan.}
{187}{}{Jasnì, jenom se tak ubezpeèuji, díky. Pùjdu si to ovìøit.}
{188}{}{Hmmm. Díky za informace.}
{189}{}{Jistìe jsi. Jenom bych si dala pozor, komu øíkat "Obèan." Nìkdo pøišel s tím, e ten vydìraè Skeev krade papíry na doklady a naèerno je komukoliv prodává. Take - pozornì sledovat, chápeš?}
{190}{}{Uh, okej. Chci ještì nìco...}
{191}{}{Och. Dobrá, dìkuji za upozornìní.}
{192}{}{Podívej, mìla bych ti asi øíct, e tady v okolí bude lepší nepouívat vıraz "otroctví", pokud se nechceš dostat do potíí. Tady takovım øíkáme "sluhové", ne otroci. Ber to jako dobrou radu.}
{193}{}{Hmm... budi. Chci ještì nìco jiného...}
{194}{}{Díky. Budu si to pamatovat.}
{195}{}{Moc ne. Nejvíce kontaktù máme s venkovany. Jsou to karavany obchodníkù dìlajících Velkı okruh z Broken Hills, New Rena, a Reddingu. Jediné další místo o kterém vím, a se kterım sice neobchodujeme ale máme kontakt, je Gecko.}
{196}{}{Povìz mi o Broken Hills.}
{197}{}{Povìz mi o New Renu.}
{198}{}{Povìz mi o Reddingu.}
{199}{}{Povìz mi o Gecku.}
{200}{}{Chci ještì nìco jiného...}
{201}{}{Dìkuji za informace.}
{202}{}{Je to tìební komunita stejnì jako Redding, akorát e leí daleko na jihu. Máme odtamtud mnoho dováek urania.}
{203}{}{Povìz mi o New Renu.}
{204}{}{Povìz mi o Reddingu.}
{205}{}{Povìz mi o Gecku.}
{206}{}{Chci ještì nìco jiného...}
{207}{}{Dìkuji za informace.}
{208}{}{Najdeš ho smìrem na jihozápad. Ale slyším odtamtud jenom o samıch potíích. Nìkteøí obchodníci, a zvláštì otrokáøi, si tam však velice libují. Ostatní obchodníci... moc ne. Je to takové mìsto co se napovrch tøpytí... a uvnitø je skrznaskrz shnilé.}
{209}{}{Povìz mi o Broken Hills.}
{210}{}{Povìz mi o Reddingu.}
{211}{}{Povìz mi o Gecku.}
{212}{}{Chci ještì nìco jiného...}
{213}{}{Dìkuji za informace.}
{214}{}{Takové tìební mìsto na západì. Od nich jsme však v poslední dobì nevidìli pøíliš mnoho zásilek, zaèínáme mít tak trochu obavy. Zvláštì radní Senior McClure.}
{215}{}{Povìz mi o Broken Hills.}
{216}{}{Povìz mi o New Renu.}
{217}{}{Povìz mi o Gecku.}
{218}{}{Chci ještì nìco jiného...}
{219}{}{Dìkuji za informace.}
{220}{}{Mìsto ghoulù, ne déle ne den na severovıchod, opravdu kousek. Øíká se, e mají zhoubnı vliv na kohokoliv, kdo se zdruje na jejich území. Radìji se dret dál.}
{221}{}{Povìz mi o Broken Hills.}
{222}{}{Povìz mi o New Renu.}
{223}{}{Povìz mi o Reddingu.}
{224}{}{Chci ještì nìco jiného...}
{225}{}{Dìkuji za informace.}
{226}{}{Proè? Hledáš snad nìco ještì více šmrncovního ne tohle syntetické pití?}
{227}{}{Snad. Víš, pití syntetického alkoholu se opravdu nedá porovnat s pitím skuteèného.}
{228}{}{Opravdu ne. Spíš by mne zajímaly nìjaké informace...}
{229}{}{Dnes ne.}
{230}{}{To je jistì pravda. Uívala jsem si s... vlastnì, znala jsem jednoho obchodníka, kterı mi dal láhev Maddogu 30/30. Fakt opravdovı, drsnı pití...vùbec jsem po tom necítila jazyk, ale na druhou stranu - mìla jsem z toho takovı nezvyklı pocit.}
{231}{}{A víš o tomhle obchodníkovi nìco blišího?}
{232}{}{Chci nìjaké informace.}
{233}{}{Hmm. Dobrá, moc hezky se mi s tebou povídalo.}
{234}{}{Povím ti co jsem slyšela. Sem do Vault City pøicestovalo nìkolik dalších "pøátel" za tímto obchodníkem a s nìèím mu pomáhali. On jim pak nabídl k prodeji tohle opravdovı pití. A byli ochotní zaplatit i fakt velmi vysoké ceny, jen aby mìli trochu "zmìnu". Víš, dá se z toho krásnì opít.}
{235}{}{Hele, nìco ti povím. Myslím, e by pro mne nebyl pøíliš velkı problém sehnat vìtší mnoství opravdovıho alkoholu. Moje cestování vedla i pøes místa, kde dostat se k alkoholu, není nic tìkého.}
{236}{}{Chci pár informací.}
{237}{}{No nic. Dobrá, hezky se mi s tebou povídalo.}
{238}{}{Ach opravdu? Dobrá, a nemùeš se mi tedy po nìjakém tom opravdovém alkoholu podívat, co? Samozøejmì bych ti to dobøe zaplatila. Ale o naší dohodì musíš mlèet. A také to nìjak propašovat skrz bránu.}
{239}{}{A kolik bys toho alkoholu chtìla?}
{240}{}{No øeknìme bedınku deseti lahví tvrdého alkoholu, a deset lahví piva. Ale ne e mi sem dotáhneš tu radioaktivní bøeèku z Gecka. Jenom starı dobrı "chlast", chápeš?}
{241}{}{Tak zrovna takové mnoství mám právì u sebe.}
{242}{}{OK... myslím, e pro tebe mùu nìco sehnat. A teï mám ještì nìjaké otázky...}
{243}{}{Hmmmm. Na èas teï zmizím a a budu nìco mít, pøijdu zpátky k tobì.}
{244}{}{Bezvadnı! Tady je nìco pro tebe... vynese mi to aspoò dvojnásobek. A nemusím ti doufám pøipomínat, e tahle transakce se nikdy neuskuteènila, e?}
{245}{}{Není problém. Heleï, teï potøebuji nìjaké informace...}
{246}{}{Díky. S tebou je radost obchodovat.}
{247}{}{Ne, takovéhle bøeèky bùhvíodkud, kterım se nìkdo snaí øíkat alkohol, jsou zde ve Vault City ilegální. A u vùbec mne nezajímá, jak se vyrábìjí. A teï, dáte si nìco k pití, kapitáne...?}
{248}{}{Nevidím nic špatného na tom, dát si tu a tam opravdovı alkohol. Jistìe vnímání tím trpí, ale pokud si vezmeš pøíliš moc léèivıch práškù, tak trpí také.}
{249}{}{Chci ještì nìco jiného.}
{250}{}{No nic. Mám pár jinıch dotazù...}
{251}{}{Uvidíme. Kadopádnì dìkuji.}
{252}{}{Tak o tomhle nic nevím. Podávám pouze syntetickı alkohol. Jestli by se vùbec kdy do Vault City nìjakı opravdovı alkohol dostal, nevìdìla bych o tom.}
{253}{}{No nic. Chci se zeptat na nìco jiného...}
{254}{}{Uvidíme. Kadopádnì dìkuji.}
{255}{}{No... uvidíme. Dobrá, a teï buï opatrná. Okej?}
{256}{}{Thankie wankie my stankie}
{257}{}{Belhám se pryè}
{258}{}{Zzzzzzzz.}
