#tento soubor prelozil RadaR - rd@zbrojovka.com
#
{100}{}{Vidíš prokonsula Gregoryho.}
{101}{}{Vidíš byrokrata s pevnım pohledem, ostøe øezanımi rysy a hustım oboèím.}
{102}{}{Vidíš prokonsula Gregoryho.}
{103}{}{Vidíš byrokrata s pevnım pohledem, ostøe øezanımi rysy a hustım oboèím.}
{104}{}{Za svùj stateènı èin, získáváš úplnı pøístup do Vault City. Jo... První Obèanka øíkala, e by tì chtìla vidìt.}
{105}{}{Vetøelec! Stráe! Stráe!}
{106}{}{Kd-?! Mutant! STRÁE! STRÁE!}
{107}{}{Kd-? Ghoul! STRÁE! STRÁE!}
{108}{}{Dobrı den, kapitáne.}
{109}{}{Vault City má vdy navrch, kapitáne.}
{110}{}{Dobrı den, Obèane.}
{111}{}{Vault City má vdy navrch, Obèane.}
{112}{}{Seznamy, seznamy, seznamy... jak já miluji seznamy!}
{113}{}{Zavádím formuláø 5632 do rozesílacího serveru...}
{114}{}{Sepisuji seznam 43A skrze 121B... pak jej zavedu do archívu...}
{115}{}{Je pøekrásnı den k sepisování seznamù.}
{116}{}{Poøád ještì musím stihnout dokonèit tyhle seznamy, ne bude veèer a pùjdu spát...}
{117}{}{Pøijï ráno, prosím. Musím dodìlat tyhle seznamy.}
{118}{}{Špinavej mutant...}
{119}{}{Nechápu, jak se nìkdo takovı jako ty mohl stát Obèanem. Pro mì nejsi nic ne mutant. Jene kdy mì nikdo neposlouchá...}
{120}{}{Nechápu, jak se nìkdo takovı jako ty mohl stát kapitánem. Pro mì nejsi nic ne mutant. Jene kdy mì nikdo neposlouchá...}
{121}{}{Promiò... mohu ti s nìèím pomoci?}
{122}{}{Pomoc tobì?}
{123}{}{Belhat se pryè.}
{124}{}{Kdo jsi?}
{125}{}{Jen se rozhlíím, dìkuji.}
{126}{}{ZASE další sluha co tu chodí v bludném kruhu?! Podám hlášení Barkusovi, jestli je tu jen tak nechá bloumat kolem... a teï zmiz ty... vystøel! Vystøel pryè!}
{127}{}{Støílet? Ou-kej.}
{128}{}{Belhat se pryè.}
{129}{}{*Tsts* Tihle sluhové jsou den ode dne hloupìjší.}
{130}{}{Jsem prokonsul Gregory. Je tento úøad ten kterı hledáš, nebo...?}
{131}{}{"Prokonsul?" Co to k èertu je "prokonsul?"}
{132}{}{Co tu máš na práci?}
{133}{}{Jenom se tu tak rozhlíím, dìkuji.}
{134}{}{Jsem ASISTENTEM První Obèanky. Plánuji jí schùze, vedu testy udìlování Obèanství pro pøípadné uchazeèe, a udruji aktuální všechny seznamy na serveru Vault City. Nic jednoduchého, to tì mohu ujistit.}
{135}{}{Testy pro udìlení Obèanství?}
{136}{}{Zmiòuješ se o testech pro získání Obèanství; chci je znovu zkusit.}
{137}{}{Mohu mít nìjaké otázky?}
{138}{}{Hmm. Dobrá, pùjdu.}
{139}{}{Ano, SPRÁVNÁ cesta jak se stát Obèanem, je jít a udìlat test Obèanství.}
{140}{}{Ano, všechno co se tıká testù Obèanství spadá pode mne. Kdokoliv je mùe zkusit udìlat a v pøípadì úspìchu se stát Obèanem Vault City.}
{141}{}{Co konkrétnì je to za test?}
{142}{}{Chci zkusit znovu udìlat test.}
{143}{}{Jaké z toho budu mít vıhody, kdy budu Obèan?}
{144}{}{Mohu mít pár otázek?}
{145}{}{Hmm... moná si promluvíme nìkdy jindy.}
{146}{}{Vıhody? Jen se podívej kolem... Vault City je nejbezpeènìjší a nejprosperující mìsto široko daleko. Obèané mají zdarma lékaøské ošetøení, vody a jídla je dost, a slovo kriminalita tu vùbec neznáme.}
{147}{}{Co konkrétnì je to za test?}
{148}{}{Zní to dobøe. Chci zkusit ten test znovu udìlat.}
{149}{}{Mohu mít nìjaké jiné otázky?}
{150}{}{Hmm...moná si promluvíme nìkdy jindy.}
{151}{}{Jedná se vlastnì o test, rozdìlenı do nìkolika èástí... pokroèilá matematika, prostorové vnímání, deduktivní uvaování, jazykové znalosti... och, a také dùkladné vyšetøení fyzického stavu.}
{152}{}{Co... pokroèilá mat-ko-tika? Ehm... a není tu nìjaká jiná monost jak získat nebo vybojovat Obèanství?}
{153}{}{Zní to... komplikovanì. No, mohu ten test zkusit?}
{154}{}{Zní to obtínì. Pøesto, chci ten test zkusit udìlat.}
{155}{}{Na tom nic není. Chci podstoupit ten test Obèanství.}
{156}{}{A to netestujete zrak a logické uvaování? Hmmm. Snad byste o tom mìli do budoucna uvaovat... dobrá, i tak to beru.}
{157}{}{Uvidíme. Mohu mít nìjaké jiné otázky?}
{158}{}{Zajímavé. Dìkuji za tvùj èas.}
{159}{}{Dobøe, jestli zvládneš úkol pro První Obèanku, získáš Obèanství... i kdy takhle by to bıt nemìlo. Ale asi má pro to své dùvody.}
{160}{}{Ne. Jestli chceš bıt Obèanem, musíš udìlat test.}
{161}{}{Zamítáš její nabídku pro získání Obèanství?}
{162}{}{Zkusím ten test tedy udìlat.}
{163}{}{Chci ten test zkusit znovu.}
{164}{}{Hmmm. Mohu mít jiné otázky?}
{165}{}{Dìkuji za tvùj èas. Nashle.}
{166}{}{Pøeješ si podstoupit test? Vıbornì, vıbornì! Nic mi nedìlá vìtší radost, ne testování uchazeèù... ale musím tì varovat, test potrvá nìkolik hodin. Pøeješ si ho podstoupit hned?}
{167}{}{Nue, kdokoliv mùe podstoupit test. Avšak mám takovı dojem... myslím si, e v tomto pøípadì to bude plıtvání èasem... pro nás pro oba. Obèas se prostì vyskytnou i tací co nejsou na nìco takového vhodní.}
{168}{}{Jistì.}
{169}{}{Teï ne. Mohu se zeptat na pár dalších vìcí?}
{170}{}{Snad nìkdy jindy.}
{171}{}{Chci ten test podstoupit ihned.}
{172}{}{Tak u mi dej ten zatracenej test.}
{173}{}{Zapomeò na to. Mohu mít nìjaké otázky?}
{174}{}{Já rozumìt. Já jít odcházet.}
{175}{}{Dobrá.}
{176}{}{Dobrá, je to tvé právo, i kdy pochybuji, e to dopadne jinak, ne poslednì.}
{177}{}{Tady máš formuláøe 5028, 6112, a doplòovací konzoli pro Pip Boye. Ujisti se prosím, e máš všechny kolonky KOMPLETNÌ a øádnì vyplnìny. A teï si prosím sedni támhle...}
{178}{}{OK.}
{179}{}{Hotovo? Urèitì si nechceš ještì jednou zkontrolovat své odpovìdi?}
{180}{}{Nue, èas vypršel. Podíváme se na to.}
{181}{}{Ano hotovo. Tady to je.}
{182}{}{Poèkej! Jenom minutku... och, no nic. Tady to máš.}
{183}{}{Hmmm... tak to ne... tohle je špatnì... tohle není dobøe, ani jedno... tady zas dìlíš nulou... hmmm... potøebuješ k nošení dva... mùj boe, vidím, e tvoje slovní zásoba je velmi nedostateèná.}
{184}{}{Tak se podíváme... vidím, e tady máš vynechány nìjaké rovnice... zøejmì nemáš ani potuchy o hlavním vıznamu paragrafu sedm, to se tıká obou èástí...  a jehlan v tomto schématu mùe bıt pøekøíen osmkrát, nikoliv tøikrát.}
{185}{}{Take. Tvé odpovìdi, co jsi stihl napsat, se zdají bıt v poøádku... asi by to chtìlo více èasu... ovšem tady máš neomluvitelné gramatické chyby a...}
{186}{}{Take...?}
{187}{}{S politováním musím oznámit, e ti nemohu udìlit Obèanství.}
{188}{}{Abych byl upøímnı, nemáš dostateènou inteligenci pochopit vyšší matematiku. }
{189}{}{Jestli mohu nìco øíci, tak tvoje chápání prostorového vnímání je naprosto nedostateèné.}
{190}{}{Tentokrát se ti testy pøíliš nepovedly. Snad budeš mít více štìstí pøíštì.}
{191}{}{Snad nìkdy pøíštì.}
{192}{}{Dobrá podívám se... nejprve jestli... och, velmi dobøe, tohle ti jde... nue ano, ...dva, velmi chytré, velmi chytré... ale proè tohle... aha, pouíváš odvození z #5... brilantní}
{193}{}{Jooo. Paráda.}
{194}{}{Nue... tohle máš úspìšnì za sebou! Gratuluji.}
{195}{}{Bezvadné. Take jsem Obèan?}
{196}{}{Ještì musím prohlédnout tvùj zdravotní stav. Naštìstí jsem tu na to vybaven. Myslím, e bude lépe kdy si zuješ boty.}
{197}{}{Okej.}
{198}{}{Ty... ty máš šest prstù! Vdy jsi mutant! Jak si vùbec troufáš se vetøít mezi nás... ty... ty zrùdo! Zmiz! Vypadni! A u se nevracej!}
{199}{}{Nyní pøichází chvíle, kdy ztrácím trpìlivost. Tak a teï zabiju kadıho Obèana ve Vault City - jen tak pro radost. A zaènu s tebou.}
{200}{}{U mizím, u mizím!}
{201}{}{Tvùj krevní tlak je v poøádku, ádné nakalivé nemoci taky nenacházím... gratuluji, Obèane. Vítej ve Vault City.}
{202}{}{Díky. Je dobré tu bıt.}
{203}{}{Zase ty. S èím ti mohu pomoci?}
{204}{}{Pøedpokládám... e chceš nìco vìdìt?}
{205}{}{Mohu se ještì jednou zeptat co tu máš na práci?}
{206}{}{Mohu podstoupit test Obèanství?}
{207}{}{Mohu znovu podstoupit test Obèanství?}
{208}{}{Co mi mùeš povìdìt o Gecku?}
{209}{}{Nic. Moná si promluvíme pozdìji.}
{210}{}{Dobøe, jestli zvládneš úkol pro První Obèanku, získáš Obèanství... i kdy takhle by to bıt nemìlo. Ale asi má pro to své dùvody.}
{211}{}{Není nìjaká jiná cesta, jak získat Obèanství?}
{212}{}{Zamítáš její nabídku pro získání Obèanství?}
{213}{}{Mohu mít nìjaké jiné otázky?}
{214}{}{Hmm. Nashle.}
{215}{}{Tady není místo, kde se ptát na jednání První Obèanky.}
{216}{}{Je nìjakı jinı zpùsob jak se stát Obèanem?}
{217}{}{Mohu mít nìjaké jiné otázky?}
{218}{}{Nevadí.}
{219}{}{Gecko? To je špinavé mìsteèko na sever odsud, zabydlené takovımi tvory, no tìmito... "ghouly." Jsou odpovìdní za otrávení našich podzemních zdrojù vody, víš! Zøejmı akt záškodnictví vùèi Vault City!}
{220}{}{Jak mohli otrávit podzemní zdroje vody?}
{221}{}{Hmmm. Mohu se zeptat na nìco jiného?}
{222}{}{Dìkuji ti, nashle.}
{223}{}{To jejich mìsto je toti zbudováno poblí zbytkù staré atomové elektrárny... a oni tu elektrárnu NÌJAK uvedli znovu do chodu, jenome z ní vychází spousta radiace! Tyhle obyvatele musíme vyrazit a elektrárnu vypnout!}
{224}{}{Hmmm. Mohu mít nìjaké další otázky?}
{225}{}{Dìkuji za informace. Nashle.}
{226}{}{Za úspìšné zvládnutí testu Obèanství se stáváš Obèanem Vault City.}
