#tento soubor prelozil Tomas "LOCKHEAR" Jurecka
{100}{}{Vidíš vánì vypadající enu v tenkıch brılích, na sobì má kombinézu Vault City. Podle jejího chování je to asi dùleitá osoba.}
{101}{}{Vidíš První Obèanku Lynette. Vypadá to, e nad nìèím pøemıšlí.}
{102}{}{Vidíš První Obèanku Lynette. Vypadá to, e nad nìèím pøemıšlí.}
{103}{}{Je pozdì. Sjednej si schùzku  na zítøejší ráno, pak Tì mohu pøijmout.}
{104}{}{Jak jsem ji ØEKLA, nepøijímám návštìvníky v tak pozdní dobu. Vìtšina Obèanù je touto dobou ji v posteli.}
{105}{}{Sjednej si schùzku  na zítøejší ráno. Pak Tì mohu pøijmout.}
{106}{}{Mohu s Tebou mluvit ZÍTRA.}
{107}{}{Nevím sice, jak ses dostal pøes stráe a do mıch soukromıch pokojù, ale bude pro Tebe nejlepší kdy odejdeš.}
{108}{}{Nevím co si myslíš, e získáš, kdy na mnì budeš neustále klikat, ale nehodlám to déle tolerovat.}
{109}{}{Moná se Ti zdá to klikání na mnì... zábavné. Je rovnì pravdìpodobné, e shledáš pobyt v nápravném zaøízení taky tak humornım.}
{110}{}{Oceòuju Tvou  pozornost, ale taky dokáu bıt velmi nebezpeèná.}
{111}{}{Já jsem První Obèanka! A chci se taky nìkdy v klidu vyspat!}
{112}{}{Jdi pryè!}
{113}{}{Odpal!}
{114}{}{Ven! Ven! Ven!}
{115}{}{Obdivuji Tvou vytrvalost. Myslím, e ji ale budu obdivovat z dálky.}
{116}{}{Je to snad nìjakı neohrabanı zpùsob, jak mi ukázat e se Ti líbím?}
{117}{}{Líbí se ti mé kudrlinky? To Scott Rodenhizer má takovı opravdu zvláštní druh humoru.}
{118}{lyn002}{Zvìsti o Tvıch hrdinskıch èinech se šíøí rychle. Je to pravda? Poøád vláda hrozí válkou?}
{119}{}{Hur? Huhr rur?}
{120}{}{Ano. Chtìli pouít virus, kterı by znièil veškerı ivot. Chtìli ho vypustit... vše co se vám zde podaøilo vybudovat by zmizelo v propadlišti dìjin.}
{121}{}{Slyšela jste to špatnì. Jsem pouhı cestovatel, nic víc... a zcela urèitì ne hrdina. Jediná vìc, kterou si pøeji je, aby mì všichni nechali na pokoji, chci putovat nekoneènou pouští a hledat své místo v tomto novém svìtì. Nashledanou, První Obèanko...navdy.}
{122}{lyn003}{I z lidí s malım mozeèkem - tys toho dùkazem - se mohou stát velikáni. Dávej na sebe pozor, mùj sladkı imbecilku... celé Vault City Ti dìkuje.}
{123}{}{Obejmi ji.}
{124}{}{Oo. Pa pá.}
{125}{lyn004}{Hrrmmm... dobrá, dobrá. Vdy kdy ti huèí v kládì, tak jdeš za tetièkou Lynette, e jo?}
{126}{}{Jupííí, ukıııı.}
{127}{}{Pa-pá.}
{128}{lyn005}{Jak bezcitné! Jak kruté! Copak si neuvìdomili vıznam komunity, kterou jsem zde vytvoøili?}
{129}{}{Snad to pro Tebe byla pouèná lekce, Lynette. Oddìleni od svìta jste vùbec netušili, e vláda se Vás pøipravuje znièit, ani by vìdìla, jakı systém jste si ty vytvoøili. Moná by se Vault City mìlo podívat pøes vrcholky svıch zdí na okolní svìt... a pokusit se do nìho zaèlenit.}
{130}{}{Bezcitné, kruté... moná. To co vím jistì, je to, e jsem mìl mohutnìjší palebnou sílu. Nashledanou, První Obèanko.}
{131}{lyn006}{To bude ta správná cesta. Pøíštì musíme vynaloit více úsilí abychom nalezli pozùstatky vlády a udìlali z nich naše spojence. Slyšela jsem, e mají vıborné energozbroje.}
{132}{}{Ale... ach, zapomeò na to. Hodnì štìstí, První obèanko.}
{133}{}{Nevíš z toho ani polovinu! Posilovaè chùze, recyklace tìlesnıch šáv, hrozivı vzhled... VELMI dobré chlazení.}
{134}{}{Nashledanou, První Obèanko. Musím se vrátit zpìt do vnìjšího svìta...a najít v nìm své místo.}
{135}{lyn007}{Prosím, øíkej mi Lynette. Cestuj opatrnì... mùj pøíteli. Nikdy na Tebe nezapomeneme. Vdy budeš mít domov tady, mezi zdmi Vault City.}
{136}{}{Díky... Lynette.}
{137}{}{Joo, fajn, je LEPŠÍ mít domov tady. Mnì a mım malım ocelovım pøátelùm bude trvat asi pìt vteøin ne si zaènete vzájemnì prohlíet své vnitønosti. Spi sladce, Lynette. Ha Ha Háááa Ha Háá.}
{138}{lyn008}{Ty na sobì máš kombinézu Vaultu! Nikdy jsem nedoufala, e potkám obyvatele jiného Vaultu. Kde se nachází ten....Vault 13?}
{139}{}{Hummmhh?}
{140}{}{Volt! Volte zelené, Vaši *záøivou* budoucnost!}
{141}{}{Ge ge suandááá.}
{142}{}{Pa-pá}
{143}{}{Není toto Vault, ze kterého pocházejí mí pøedkové?}
{144}{}{Nevím. Pøicházím z vesnice na západì.}
{145}{}{Nevím. Zkouším najít Vault, ze kterého pocházejí mí pøedkové... mùeš mi pomoci?}
{146}{}{Bohuel nemám èas Ti teï objasnit celou podstatu pøíbìhu. Pøeji hezkı den.}
{147}{lyn009}{To numero na Tvé kombinéze asi hlásí jaké máš IQ a ne èíslo Vaultu.}
{148}{}{Hrnnnn?}
{149}{}{Èíís-loo}
{150}{}{Šu šuš úúú!}
{151}{}{Odprejskni}
{152}{lyn010}{Nevím jak se Ti podaøilo vybudit Tvùj mozeèek aby ses dostal do mìsta, ale ujistím se, e se u tady nebudeš potulovat...stráe! Eskortujte tohoto imbecila za hradby mìsta!}
{153}{}{NE!}

# player's name prepended to line 154
{154}{}{ bì s elezòáky}
{155}{lyn011}{Pøeji Ti dobrı den, cizinèe. Jsem první obèanka Lynette. Mohu se zeptat, zda hledáš v našem mìstì nìco konkrétního?}
{156}{}{Práci? Prci-prci?}
{157}{}{Fujííííí!}
{158}{}{Pa-pá.}
{159}{}{Hledám GECK.. Nemáte náhodou jeden navíc?}
{160}{}{Pátrám po  GECKu, První Obèanko. Nemá Vaše mìsto jeden kus, kterı by mohlo postrádat?}
{161}{}{Ty jsi... Správce tohoto Vaultu?}
{162}{}{Promiòte mi mou nezdvoøilost, První Obèanko... znamená snad tento titul "První Obèanka", e jste Správcem tohoto Vaultu?}
{163}{}{Toto je Vault City? Tak proè neijete ve Vaultu?}
{164}{}{Dnes tu nemám co na práci. Moná pøíštì.}
{165}{}{Dnes nic. Omlouvám se za to obtìování, První Obèanko. Hezkı den.}
{166}{lyn012a}{Kde nìkdo takovı jako TY slyšel o GECKu.?}
{167}{lyn012b}{Taková technologie nebyla urèena pro cizince.}
{168}{}{Máte PROBLÉMY s cizinci, paní?}
{169}{}{Máte problémy s cizinci?}
{170}{}{Omlouvám se... ale je snad špatné bıt cizinec, První Obèanko?}
{171}{}{Jsem potomek Velkého Zakladatele. Má vesnice mì poslala pro GECK.}
{172}{}{Jsem potomek Velkého Zakladatele, První Obèanko. Potøebuji GECK. k záchranì mé vesnice}
{173}{}{eno, dej mi GECK. Ihned, nebo si ho vezmu násilím.}
{174}{}{Dej mi GECK. Hned, nebo si ho vezmu silou.}
{175}{}{Tak to ji nemáme o èem mluvit. Pøeji hezkı den.}
{176}{lyn013}{Problém je v tom, e skoro všichni cizinci se chtìjí pøidat k našemu spoleèenství, co není tak jednoduše proveditelné. Nepochybnì bychom toti byli znièeni tou samou epidemií anarchie, která ovládla vnìjší svìt.}
{177}{}{To vidím. Pøeji si hovoøit s Správcem tohoto Vaultu. Mùete mne k nìmu zavést?}
{178}{}{Jakpak se  èlovìk mùe stát jedním z tìch Tvıch Zakladatelù?}
{179}{}{Jestlie tak nesnášíš vnìjší svìt, proè teda iješ na povrchu a ne ve Vaultu?}
{180}{}{To mi staèí. Nashle.}
{181}{}{Já... rozumím. Díky za Váš èas, První Obèanko.}
{182}{lyn014}{Ze svıch zkušeností vím, e Vy cizinci jste hodnì útoèní. Jste nekulturní a primitivní. Nejste nic ne zvíøata! Teï odejdi. Nebo Tì odsud nechám vyvést.}
{183}{}{Ne! Se mnou nic nehne, dokud  nedostanu pár odpovìdí!}
{184}{}{"Budu vyveden?" Jen to ZKUS. Urèitì se mi to bude líbit.}
{185}{}{Dobrá, v klidu odejdu...tentokrát.}
{186}{}{U jdu, u jdu.}
{187}{lyn015a}{"Správce?" Proè.., ne. Posledních sto let tu ji Správci neexistují. Jak se k tobì dostala informace o Správcích Vaultù?}
{188}{lyn015b}{Ji jsem Ti to øíkala. Správci pocházejí z dávné minulosti.}
{189}{}{Jsem potomek Prvního Zakladatele. Bylo mi vyprávìno... mnoho pøíbìhù o Správci.}
{190}{}{Co se Správci stalo? Musím s ním mluvit.}
{191}{}{Ty zcela URÈITÌ nejsi ta, se kterou potøebuji mluvit. Dojdi koneènì pro Správce, eno.}
{192}{}{Ty zcela URÈITÌ nejsi ta, se kterou potøebuji mluvit. Dojdi koneènì pro Správce.}
{193}{}{Nevadí. Musím u jít. Pøeji hezkı den.}
{194}{lyn016}{"Potomek Zakladatele?" Co tím myslíš?}
{195}{}{Já jsem vnuk Prvního Zakladatele.}
{196}{}{enská, jenom tady plıtvám svùj drahocennı èas tlacháním s Tebou. Pøiveï koneènì Správce.}
{197}{}{Jenom tady plıtvám svùj drahocennı èas tlacháním s Tebou. Pøiveï koneènì Správce.}
{198}{}{Ale nic, nevadí. Budeme v našem rozhovoru pokraèovat pozdìji.}
{199}{lyn017a}{Ty se tady vevalíš do mého pokoje jako nìjakı balvan a máš ještì tu drzost uráet mnì, Lynette, První Obèanku Vault City?!}
{200}{lyn017b}{Ty se tady vevalíš do mého pokoje jako nìjakı balvan a máš ještì tu drzost dìlat návrhy mnì, Lynette, První Obèance Vault City?!}
{201}{lyn017c}{Odejdi. U nejsi v tomto mìstì vítán.}
{202}{}{Já NEODEJDU, dokud nedostanu pár odpovìdí.}
{203}{}{Pùjdu... protentokrát.}
{204}{lyn018}{Ne, ne, neijeme ve Vaultu. To bylo pouze doèasné útoèištì urèené k ochranì nìkolika z nás pøed válkou. Aby poté mohli zaèít budovat novı svìt.}
{205}{}{Jak jste se ale dozvìdìli, e mùete opìt vyjít na povrch? Øíká se, e Vaulty byly naprosto izolované od vnìjšího svìta.}
{206}{}{Je velmi dùleité, abych si promluvil s Správcem. Mùete mne k nìmu zavést?}
{207}{}{Jenom tady plıtvám svùj drahocennı èas tlacháním s Tebou. Pøiveï koneènì Správce, enská.}
{208}{}{Jenom tady plıtvám svùj drahocennı èas tlacháním s Tebou. Pøiveï koneènì Správce.}
{209}{}{To vše. Nashledanou.}
{210}{}{Díky za Tvùj èas, První Obèanko. Pøeji hezkı den.}
{211}{lyn019}{Zde není ádnı "Správce." Kdy jsem opìt vyšli na povrch, zformovala se nová vláda. Pozice Správce ji byla zbyteèná.}
{212}{}{Nová vláda? Povìz mi o ní.}
{213}{}{Take Ty jsi vùdce pùvodních zakladatelù?}
{214}{}{Chytré. Zbavit se zkorumpovaného Správce.}
{215}{}{To vidím. Díky za informace. Pøeji hezkı den.}
{216}{lyn020}{To, co jsi slyšel, nebylo správnì. Naše archívy o tom bohuel mlèí, ale jedno je jisté: náš Vault obdrel signál "Bezpeèí" dva roky po jeho zapeèetìní.}
{217}{}{Signál "Bezpeèí"? A odkud?}
{218}{}{Kde jsou ty archívy?}
{219}{}{Kde je Správce? Musím s ním mluvit.}
{220}{}{No, legendy mého kmene vypráví, e náš Vault byl uzavøen po mnoho let... a ádnı signál "Bezpeèí" nikdy nepøišel.}
{221}{}{Ty leš! Signál "bezpeèí" nikdy neexistoval!}
{222}{}{To vidím. Díky za informace. Pøeji hezkı den.}
{223}{lyn021}{Proè... z monitorù povrchu, pøedpokládám. Jsem si jistá, e mìli nìjaké senzory monitorující povrch a ovzduší. Jak by se jinak mohl Správce dozvìdìt o tom, e je ji bezpeèné opustit podzemí?}
{224}{}{Existují stále tyto monitory? Mohu je vidìt?}
{225}{}{Take... pøíkaz k opuštìní Vaultu vydal Správce?}
{226}{}{Chci mluvit s Správcem, kde je? Chci hovoøit pouze s ním.}
{227}{}{Ty leš! Signál "Bezpeèí" nikdy neexistoval!}
{228}{}{To není tak zcela jisté... zatím. Pøeji hezkı den.}
{229}{lyn022}{Zcela urèitì byly rozebrány a pouity na zdokonalení jinıch systémù.}
{230}{}{Hmmm. Ale Správce byl ten, kdo vydal rozkaz k opuštìní Vaultu?}
{231}{}{Kde je Správce? Musím s ním o tom mluvit.}
{232}{}{Nevìøím Ti. Povídám, signál "Bezpeèí" nikdy neexistoval!}
{233}{}{To vidím. Díky za informace. Pøeji hezkı den.}
{234}{lyn023}{Ano... alespoò toto si pamatuju z archívu. Nicménì si jsem jistá, e za monitorování povrchu bylo odpovìdno mnoho Obèanù.}
{235}{}{Máte ponìtí, kde jsou ty povrchové senzory teï?}
{236}{}{Kde jsou tyto archívy?}
{237}{}{Kde je Správce? Musím s ním mluvit.}
{238}{}{Ty leš! Signál "Bezpeèí" nikdy neexistoval!}
{239}{}{To vidím. Díky za informace. Pøeji hezkı den.}
{240}{lyn024}{Zamysli se nad svımi argumenty a  brzy na povrch vyplynou zcela zøejmé trhliny. Archívy netrpí chybovostí jako  ty tvé... "kmenové legendy".}
{241}{}{Kde jsou ty archívy?}
{242}{}{Kde je Správce? Musím s ním mluvit.}
{243}{}{Podívej, vdy ti to øíkám... signál "Bezpeèí" nikdy neexistoval!}
{244}{}{To mi staèí. Pøeji hezkı den.}
{245}{lyn025}{Ty máš tu smìlost obvinit mnì, Lynette, První Obèanku Vault City, ze LI?! Odejdi! Èlovìk jako Ty ji není v tomto mìstì vítán.}
{246}{}{Ne! Se mnou nic nehne, dokud  nedostanu pár odpovìdí!!}
{247}{}{Dobrá, tedy odejdu... protentokrát.}
{248}{lyn026}{Archívy jsou v nitru našeho Vaultu. Jenom Obèané k nim mají pøístup... naše archívy NEJSOU pro cizince.}
{249}{}{V poøádku. Kde je Správce? Zeptám se ho na archívy.}
{250}{}{Ale já jsem Obèan.}
{251}{}{Jak se jeden mùe stát Zakladatelem?}
{252}{}{Jak se mohu stát Obèanem?}
{253}{}{To mi staèí. Pøeji hezkı den.}
{254}{lyn027}{U se nepovaujeme za "obyvatele Vaultu"... nazıváme se "Obèany". Jestli chceš bıt èlenem naší komunity, tak si tuto poctu musíš nejprve zaslouit.}
{255}{}{Zaslouit? Jak?}
{256}{}{Jsem potomek Zakladatele -- to musí staèit.}
{257}{}{Budu o tom pøemıšlet. Pøeji hezkı den.}
{258}{lyn028}{To je nedorozumìní... nebyl to svìt, na kterı jsem se zamìøili, byli to lidé v nìm. Rozhlédni se kolem sebe -- mezi tìmito zdi je vše co zbylo z pøedváleèné civilizace.}
{259}{}{Kde je Správce? Musím s ním mluvit.}
{260}{}{Není to správné, e se nechceš rozdìlit. Je tvou odpovìdností pomoci všem... ne jenom Tìm, co ijí v tìchto zdech.}
{261}{}{To vidím. Díky za Tvùj èas. Pøeji hezkı den.}
{262}{lyn029}{Vy cizinci jste opravdu ti praví, kteøí mají co øíkat o "odpovìdnosti." Neustále ebráte o pomoc, ale neudìláte nic pro to, abyste se stali lepšími. Náš rozhovor je u konce... odejdi døív, ne pøivolám stráe.}
{263}{}{Radši pøivolej stráe hned, další šanci toti mít nebudeš.}
{264}{}{Neodejdu, dokud neuvidím Správce!}
{265}{}{Odejdu... protentokrát.}
{266}{}{Velmi dobøe. Dìkuji za rozhovor. Pøeji hezkı den.}
{267}{lyn030}{"Zakladatel?" Coe? To urèitì znáš jinı Vault! Nikdy jsme nebyli v kontaktu s jinım Vaultem! Kde se nachází?}
{268}{}{Myslím, e TOTO byl Vault, ze kterého pøišli mí pøedkové.}
{269}{}{Já neiju ve Vaultu. Pocházím z domorodé vesnice na západì.}
{270}{}{To nevím... podívej, pokouším se najít Vault, ze kterého pocházejí mí pøedkové.}
{271}{}{Jakmile ho najdu, tak Vám dám urèitì vìdìt. Pøeji hezkı den.}
{272}{lyn031}{Opustili jsme Vault pøed 120-ti lety a s pomocí našeho GECKu zaèali budovat Vault City. O deset let pozdìji odešel Správce do ústraní a byla ustanovena mìstská rada Obèanù. Tato rada zavedla funkci Prvního Obèana.}
{273}{}{Kdy u mluvíme o GECKu, nemáte ještì jeden, kterı byste mi mohli poskytnout?}
{274}{}{Take Vy jste vùdce tohoto mìsta?}
{275}{}{Pøed 120-ti lety? To bylo 70 let pøed tím, ne Zakladatel vyøídil Vùdce. Toto nemùe bıt Vault kterı hledám.}
{276}{}{To vidím. Pøeji hezkı den.}
{277}{lyn032}{Správnì... Já jsem První Obèanka Vault City.}
{278}{}{První Obèanko, mám naléhovou ádost: Má vesnice VELICE nutnì potøebuje GECK. Nemáte náhodou jeden kus, kterı byste mohli postrádat?}
{279}{}{Tak potom jsi TA, kterou hledám. Pøicházím jménem lidí vesnice Arroyo, abych uplatnil nárok na to, co je právoplatnì naše: svatı GECK.}
{280}{}{To vidím. Dìkuji za rozhovor. Pøeji hezkı den.}
{281}{lyn033}{Chybovost?! Správce byl velkı mu a bezchybnı vùdce. Jeho uèení a vìdomosti dodnes uplatòujeme v našem denním ivotì.}
{282}{}{Nezní to jako e by Správce znal Zakladatele.}
{283}{}{Po záchranì Vaultu byl Zakladatel vypovìzen Správcem. Jaké z toho plyne ponauèení?}
{284}{}{U blázníš. Neplıtvej mım èasem, eno. Pøiveï nìkoho, kdo mi mùe pomoci.}
{285}{}{U blázníš. Neplıtvej mım èasem. Pøiveï nìkoho, kdo mi mùe pomoci.}
{286}{}{To je nešastné. Pøeji hezkı den.}
{287}{lyn034a}{Promluv si s prokonzulem Gregorym. On má pravomoc provádìt testy Obèanství. Vìtšinou bıvá k nalezení ve schùzovací místnosti, v dolní chodbì budovy.}
{288}{lyn034b}{Nebo... je tu ještì jedna monost, jak se stát Obèanem...}
{289}{}{Další monost? Jsem jedno ucho!}
{290}{}{Myslím, e si popovídám s prokonzulem. Nashledanou.}
{291}{}{Take si jdu pohovoøit s prokonzulem.}
{292}{}{Jdu si pohovoøit s Gregorym. Díky za Váš èas, První Obèanko.}
{293}{lyn035}{Zcela nemoné. Ve století, kdy u neijeme ve Vaultu, nebyl nikdo donucen aby nás opustil. A na dva Obèany, které jsme pøed dávnou dobou vyslali do exilu... jako trest za jejich zloèiny.}
{294}{}{Ty jsi ta, kdo donutil Zakladatele ODEJÍT! Já si jdu pro to, co je právoplatnì mé!}
{295}{}{Co mohli ti Obèané udìlat?}
{296}{}{Jestli toto není správnı Vault, pak musím najít ten, ze kterého pocházejí mí pøedkové.}
{297}{}{Musím jít. Pøeji hezkı den.}
{298}{lyn036a}{Vesnice? Ale máš na sobì kombinézu Vaultu... co je to za vesnici, o které mluvíš? Mluv jasnì: nemám moc velkou trpìlivost.}
{299}{lyn036b}{Vesnice? Nejprve mi øekneš, e pøicházíš z Vaultu, teï z vesnice. Tak odkud?! Má trpìlivost s tvım dvojsmyslnım vyjadøováním je u konce.}
{300}{}{Poèkejte, neporozumìla jste mi. Zakladatel byl ten, kdo zaèal ít v místì naší nynìjší vesnice.}
{301}{}{Má trpìlivost s TEBOU je u konce, eno. Pøiveï nìkoho jiného... nìkoho, kdo mi mùe pomoci.}
{302}{}{Má trpìlivost s TEBOU je u konce. Pøiveï nìkoho jiného... nìkoho, kdo mi mùe pomoci.}
{303}{}{Myslím, e pøijdu pozdìji. Pøeji hezkı den.}
{304}{lyn037}{Ach... nyní tomu rozumím. Ale jakı máš dùkaz, e Tví pøedkové pocházejí z Vaultu?}
{305}{}{Pøíbìhy, vyprávìné Starší naší vesnice.}
{306}{}{Mám posvátné artefakty Zakladatele... tuto kombinézu Vaultu a svatou láhev.}
{307}{}{Mám tento oblke Vaultu a tuto láhev. Patøily mım pøedkùm.}
{308}{}{Z tìch Vašich otázek se u zaèínám unavovat. Odcházím najít nìkoho jiného, kdo mi bude mùe pomoci.}
{309}{}{Musím jít. Pøeji hezkı den.}
{310}{lyn038}{Hmm... moná jsou nìjaké zmínky o Tvém Vaultu v našich poèítaèovıch archívech.}
{311}{}{Dobrá, mùeme se jít podívat?}
{312}{}{První Obèanko, je pro mne velmi dùleité abychom zjistili umístìní Vaultu mıch pøedkù. Bylo by fajn, kdyby bylo moné projít Vaše archívy.}
{313}{}{Hmmmm. Díky za informace. Pøeji hezkı den.}
{314}{lyn039}{Je mi líto, ale naše jsme pouili pøi vıstavbì Vault City a nemyslím, e by nám nìjakı zbyl. Ale mùeš se zeptat v Obchodním centru. Najdeš ho blízko vstupu do našeho Vaultu.}
{315}{}{Dìkuji. Mám pár jinıch otázek...}
{316}{}{Nevíte kde je Vault 13?}
{317}{}{Super! Take jdu tam. Pøeji hezkı den.}
{318}{lyn040}{Špinavá kombinéza Vaultu a oprıskaná èutora? Toto jsou Tvé dùkazy? Kdo ví, odkud jsi vyšáral ty Tvé "relikvie"... nebo kdo musel kvùli tomu Tvou rukou zemøít a pak bıt okraden.}
{319}{}{Prosím... podívejte se na to ještì jednou. Vše je pravé.}
{320}{}{Kvùli tomu se mé tìlo trmácelo velmi dlouhou cestu. Tak se na to PODÍVEJ, enská!}
{321}{}{Kvùli tomu se mé tìlo trmácelo velmi dlouhou cestu. Tak se na to PODÍVEJ!}
{322}{}{Jestlie to vše je málo pro Vaše pøesvìdèení, tak nemám u co øíci. Pøeji hezkı den.}
{323}{lyn041a}{Máš vùbec ponìtí jak jsem zaneprázdnìná? Já øídím toto mìsto a mám velice málo èasu na to, abych ho promarnila s Tebou a Tvımi bláznivımi povídaèkami.}
{324}{lyn041b}{Máš vùbec ponìtí jak jsem zaneprázdnìná? Já øídím toto mìsto a mám velice málo èasu na to, abych ho s Tebou promarnila.}
{325}{lyn041c}{Nyní u koneènì odejdi, nebo budu muset zavolat stráe.}
{326}{}{Tak bì a zavolej je. Nepøijdou vèas aby stihli zachránit Tvùj ivot.}
{327}{}{Fajn. Odcházím.}
{328}{}{Vıbornì, První Obèanko. Pøeji hezkı den.}
{329}{lyn042}{Take domorodá legenda? Budeš potøebovat nìco více hmotného ne... domorodı MİTUS jestli chceš, aby nìkdo uvìøil Tvım bláznivım povídaèkám.}
{330}{}{Ale já mám pøece posvátné artefakty našeho Zakladatele... tuto kombinézu Vaultu a svatou láhev.}
{331}{}{Mám tuto kombinézu a èutoru. Patøily mım pøedkùm.}
{332}{}{Co mám udìlat abych prokázal své dìdictví, kdy nevìøíte tomu co øíkám?!}
{333}{}{Fajn. Odcházím.}
{334}{}{V poøádku, ji nemáme o èem diskutovat. Pøeji hezkı den, První Obèanko.}
{335}{lyn043}{Mohli bychom prozkoumat poèítaèové archívy Vaultu. Mohly by tam bıt uloeny informace, které hledáš. Ale k tìmto archívùm mají pøístup pouze Obèané.}
{336}{}{Ale já jsem Obèan.}
{337}{}{Je tu nìjaká monost, jak se stát Obèanem?}
{338}{}{Myslím, e u nemám štìstí. Pøeji hezkı den.}
{339}{lyn044}{Radìji ne plnìním testu mùeš prokázat svou pøíslušnost k Vaultu více... konkrétním zpùsobem. Jako cizinec jsi v jedineèné pozici rozøešit....naši sloitou situaci.}
{340}{}{O jakou situaci jde?}
{341}{}{Samozøejmì. Cokoliv si Vault ádá, je mojí povinností splnit.}
{342}{}{Nevím... není Obèanskı test standardním postupem?}
{343}{}{Nevím, jestli tahle práce je pro mne to pravé... nashledanou.}
{344}{}{Díky, ale ne, radìji pùjdu. Pøeji hezkı den, První Obèanko.}
{345}{lyn045}{Byli to vrahové, oba dva. Boyarsky byl vyhoštìn pøed deseti lety a Richard Moreau krátce po tom, co jsme opustili Vault. Obèanství nesmí bıt poskvrnìno -- zloèin v tìchto zdech nebude trpìn.}
{346}{}{Jestli toto není správnı Vault, pak musím najít ten, ze kterého pocházejí mí pøedkové.}
{347}{}{Jak se mùe bìnı èlovìk stát Obèanem?}
{348}{}{To je vše. U pùjdu.}
{349}{}{To vidím. Take Vám dìkuji za námahu, První Obèanko. Pøeji hezkı den.}
{350}{lyn046}{O èem to mluvíš? Urèitì se pleteš. Ale... "Zakladatel" ..to vypadá jako e pocházíš z JINÉHO VaultU.}
{351}{}{Jestli je to pravda, tak musím tento další Vault najít .}
{352}{}{Ty leš! TOTO je Vault mıch pøedkù!}
{353}{}{Snad. Díky, e jste si se mnou promluvila. Nashledanou.}
{354}{lyn047}{Je tu mìsteèko... jestli ho tak chceš nazıvat... severovıchodnì od našeho mìsta. Je plné...kreatur které kontaminují naši podzemní vodu nebezbeènou radiací.}
{355}{}{Jak zneèišují Vaši podzemní vodu?}
{356}{}{A co si myslíte, e s tím mám udìlat?}
{357}{}{Po zralém uváení to nezní jako nìco, co by mne mohlo zajímat. Nashledanou.}
{358}{lyn048}{Odpoj jejich elektrárnu, napoøád, aby ji nemohla zpùsobit ádné škody.}
{359}{}{Zní to jako snadná vìc. Vrátím se, a tuto situaci... "vyøeším."}
{360}{}{A jak tato elektrárna uvolòuje radiaci?}
{361}{}{Nechte mne o tom chvíli pøemıšlet. Vrátím se.}
{362}{lyn049}{Tyto... vìci... provozují poškozenou atomovou elektrárnu. Jak uvidíš, JSOU k radiaci imunní...nedìlají si problémy s tím, e nás všechny pomalu zabíjejí.}
{363}{}{Beru si ten problém na starost. Vrátím se, a tuto situaci... "vyøeším."}
{364}{}{Vypadá to, e prokazují svìtu velkou slubu. Najdìte si jiného "Cizince" na Vaši špinavou práci.}
{365}{}{Nechte mne o tom chvíli pøemıšlet. Vrátím se.}
{366}{lyn050}{Dobrá, podíváme se na to... Tyto... tyto jsou autentické! Neuvìøitelné... Ty jsi pøeivší jedinec z jiného Vaultu! Vítej v našem mìstì... pustina Tì urèitì zcela vysílila.}
{367}{}{Musím najít Vault, ze kterého pocházejí mí pøedkové.}
{368}{}{Potøebuji GECK. Nemáte jeden?}
{369}{}{Ach, take teï mne vítáte ve Vašem mìstì? Zapomeòte na to... Padám odsud.}
{370}{}{Nemáte o tom ani pøedstavu... ale o chrámu zkoušek Vám povím nìkdy jindy. Nashle.}
{371}{lyn051}{Dávám Ti pøíleitost, kterou dostane jen málo cizincù. Mùeš projít testem, jestli si to pøeješ. Ale vyøešení této situace bude taky patøiènì ohodnoceno. Rozumíš mi?}
{372}{}{Take v poøádku. Copak je to za situaci?}
{373}{}{Rozumím. Cokoliv si Vault ádá, je mojí povinností splnit.}
{374}{}{Nemyslím si, e tahle práce je pro mne to pravé... nashledanou.}
{375}{}{Myslím, e u musím opravdu jít. Pøeji hezkı den, První Obèanko.}
{376}{lyn052}{Oh... to je pravda. Prokonzul se zmínil o novém Obèanovi. Buï zde vítán, Obèane. A k tìm archívùm...najdeš je uvnitø našeho Vaultu. Prohlédni si je dle libosti.}
{377}{}{Ne odejdu prozkoumat archívy, tak se chci zeptat na pár otázek...}
{378}{}{Jak získat GECK?}
{379}{}{Vıbornì! Díky.}
{380}{}{Dìkuji Ti, První Obèanko.}
{381}{lyn053a}{Ano? A s èím Ti mohu pomoci?}
{382}{lyn053b}{Ano? Co je to?}
{383}{}{Huhhh?}
{384}{}{Valt! Valt!}
{385}{}{Blbıı voèííí!}
{386}{}{Pa-pá}
{387}{}{Mám pár otázek na které se chci zeptat.}
{388}{}{Mám pár otázek na které se chci zeptat.}
{389}{}{A jak se jeden mùe  stát Obèanem Vault City?}
{390}{}{Mám znovu uváenou vaši nabídku Obèanství.}
{391}{}{A co se tıèe elektrárny Gecko...}
{392}{}{Mám nìjaké informace o banditech, kteøí útoèili na Vaše mìsto.}
{393}{}{Mám zjištìny nìjaké informace o banditech, kteøí útoèili na vaše mìsto.}
{394}{}{Podaøilo se mi najít v Bishopovì trezoru nìco, co by Vás mohlo zajímat.}
{395}{}{Vìøím, e Dr. Troy je zapleten do nìèeho ilegálního.}
{396}{}{Musím s Vámi mluvit o dodávce holodisku.}
{397}{}{Zmìnil jsem názor. Doruèím tento holodisk místodrícímu do NCR.}
{398}{}{Nic. Omlouvám se za to vyrušení.}
{399}{lyn054a}{Samozøejmì. S èím Ti mohu pomoci, Obèane?}
{400}{lyn054b}{Samozøejmì. S èím Ti mohu pomoci, kapitáne?}
{401}{}{A copak mi mùeš øíci o útocích banditù na naše mìsto?}
{402}{}{Mé kroky zkøíil Obèan jménem Thomas Moore. Co je zaè?}
{403}{}{Máte GECK?}
{404}{}{Hledám Vault 13.}
{405}{}{Toto je Vault City? Tak proè neijete ve Vaultu?}
{406}{}{Proè je to Vaše rádobyotrokáøství?}
{407}{}{Dnes nic, díky.}
{408}{lyn055}{Na neobèana si dìláš skuteènì velké nároky na mùj èas.}
{409}{}{Ale JÁ JSEM Obèan.}
{410}{}{Máte GECK?}
{411}{}{Hledám Vault 13.}
{412}{}{Co potøebuji k tomu stát se Obèanem?}
{413}{}{Toto je Vault City? Tak proè neijete ve Vaultu?}
{414}{}{Proè je to Vaše rádobyotrokáøství?}
{415}{}{Tak nevadí. Pøeji hezkı den.}
{416}{lyn056}{Co je to?! Na Tvé nesmysly nemám èas!}
{417}{}{Mùu mít nadìji na pár dalších otázek.}
{418}{}{Omlouvám se za své døívìjší øeèi, První Obèanko. Mùu mít ještì pár otázek ohlednì Vault City?.}
{419}{}{Víš, jsou zde vìci, co fungují jako ve skuteènosti.}
{420}{}{Nevadí.}
{421}{}{Omlouvám se, První Obèanko. Promiòte mé vyrušování.}
{422}{lyn057}{Co je to? Nedával sis u na to pozor?}
{423}{}{Je to ponìkud více komplikované. Jak vidíš, tak tito chlápci nebyli potulná parta banditù....byli to oldáci.}
{424}{}{Nevadí. Nashle.}
{425}{lyn058}{Nìjak si na to nemohu vzpomenout. Uka mi Tvé doklady.}
{426}{}{Tady je máš. Mìly by bıt v richtiku.}
{427}{}{Umm... Nemám doklady zrovna u sebe.}
{428}{}{Mé doklady? Ještì nejsou vyhotoveny. Bìhem pár dnù je budete mít na stole.}
{429}{}{Mé doklady? Ještì nejsou vyhotoveny. Bìhem pár dnù je budete mít na stole.}
{430}{lyn059}{Nehraj si se mnou, "Obèane," nebo se ujistím, aby Tvé nohy ji více nekráèely po ulicích Vault City. Teï odejdi.}
{431}{}{Jasnì...U odcházím. Nashledanou.}
{432}{}{Pøeji hezkı den, První Obèanko.}
{433}{lyn060}{Máš mì za blázna? Jestlie by mìl nìkdo poznat padìlky, tak bych to mìla bıt já! Kdo Ti dal ty doklady?! Jestli mi to øekneš, tak ti povolím denní propustku.}
{434}{}{Byl to Obèan jménem Skeev u vstupní brány.}
{435}{}{Já, uh, nepamatuju si.}
{436}{}{Budeš si mì muset nejdøív chytit.}
{437}{lyn061}{Hmmmm... tak dobøe. Ale neukazuj se døíve, ne budeš mít platné doklady Obèanství. Hezkı den.}
{438}{}{Nashledanou.}
{439}{}{Dobrı den, První Obèanko.}
{440}{lyn062}{Ach, opravdu? To potvrzuje mé tušení. Tvùj pøístup do Vault City je s okamitou platností zrušen. Odevzdej jednodenní propustku a odejdi se stráemi ke vstupní bránì.}
{441}{}{Coe? Øekla jste, e budu mít povolenu jednodenní propustku!}
{442}{}{Nikam neodcházím. Chceš jednodenní propustku? Pojï si ji vzít.}
{443}{}{Tak dobøe, jdu. Nechci ádné potíe.}
{444}{lyn063}{Opravdu? Mùeš zamezit kontaminování vody v Gecku? Bez pouití JAKÉHOKOLIV násilí?}
{445}{}{Ano, mohu -- vımìnou za Obèanství a pøístup do Vašich poèítaèù ve Vaultu.}
{446}{}{Ne, ne docela. Jen se pøesvìdèuji, zda nabídka stále platí.}
{447}{lyn064}{Take domluveno. Informuj mne hned jak skonèíš svùj dob a já Ti udìlím Obèanství.}
{448}{}{Mohu mít ještì pár otázek ne odejdu?}
{449}{}{V poøádku. Vrátím se a bude situace pod kontrolou.}
{450}{lyn065}{Je u situace OK?}
{451}{}{Pátráním v Gecku se mi podaøilo zjistit, e vše co potøebují k ekologicky èistému provozu je hydroelektrickı regulátor magnetosféry.}
{452}{}{Elektrárna byla znièena. Bıt Vámi, tak se jdu pøesvìdèit, zda ještì existují vaše pastviny brahmín na jihozápadì.}
{453}{}{Postaral jsem se o elektrárnu v Gecku. U nebudete mít problémy s unikající radiací.}
{454}{}{Ne, ještì ne. Stále na tom pracuji.}
{455}{lyn066}{Tak neplıtvej mım èasem. Vra se a mne budeš mít o èem informovat.}
{456}{}{Jasnì. Vrátím se pozdìji.}
{457}{}{Tak jo. Pøeji hezkı den, První Obèanko.}
{458}{lyn067a}{Take na ten problém KAŠLEŠ?}
{459}{lyn067b}{Jestli máš stále zájem o Obèanství, tak na tom radši zapracuj.}
{460}{}{Jak je mi známo, tak tu souèástku k opravì elektrárny máte pøímo zde ve skladech Vault City.}
{461}{}{V poøádku. Vrátím se pozdìji.}
{462}{}{V poøádku. Pøeji hezkı den, První Obèanko.}
{463}{lyn068}{A co kdy mùem? Je to jenom doèasné øešení. Dej prosím do poøádku tento problém, NE jejich elektrárnu. Øíkám to jasnì?}
{464}{}{První Obèanko, nechci zpochybòovat Vaše rozhodnutí, ale je tu monost jak vyøešit Váš problém bez zabíjení ghoulù nebo vypínání reaktoru. A teï, kde si mohu vyzvednout tu souèástku...?}
{465}{}{Øekla jste, e po mnì chcete opravu elektrárny a ne masakr v Gecku.}
{466}{}{Jako køišál. Vrátím se pozdìji.}
{467}{}{Ano. Pøeji hezkı den, První Obèanko.}
{468}{lyn069a}{Co to je s Tebou za... kreaturu?! Tyhle... bytosti uvnitø Vault City nejsou tolerovány! Stráe! Eskortujte všechny ty vetøelce za vstupní bránu!}
{469}{lyn069b}{Oh, já? Ruším Tvou ádost o udìlení Obèanství. Ji Ti není dovoleno déle pøebıvat v prostorách Vault City. Mé stráe Tì eskortují ke vstupní bránì.}
{470}{lyn069c}{Má dost tìch Tvıch hloupostí! Ji Ti není dovoleno déle pøebıvat v prostorách Vault City. Mé stráe Tì eskortují ke vstupní bránì.}
{471}{}{Zemøi ètyøoèko!}
{472}{}{Uh-huh}
{473}{}{Nevypadáš jako mùj pøítel, hu? To je velmi špatné. Asi si tì dám... k VEÈEØI.}
{474}{}{Stráe se sem nedostanou vèas aby zachránili Váš ivot... "První Obèanko."}
{475}{}{Není tøeba volat stráe -- odejdu v klidu.}
{476}{lyn070}{Coe? Elektrárna je znièena?! Ta kontaminace! Ty IDIOTE. Ale aspoò, e ghoulové jsou pryè... Zmiz mi z oèí.}
{477}{}{Ale! A co je s mım slíbenım Obèanstvím?}
{478}{}{Podívej, docílení takové destrukce nebylo vùbec lehké! Chci alespoò NÌJAKOU náhradu...}
{479}{}{V poøádku, v poøádku. Odcházím.}
{480}{}{Hezkı den, První Obèanko.}
{481}{lyn071}{Nehraj si se mnou, nebo se ujistím, aby tvé nohy u nikdy nekráèely ulicemi Vault City.}
{482}{}{Opatruj se, "První Obèanko." Nashledanou.}
{483}{}{Dobrı den, První Obèanko.}
{484}{lyn072a}{Dokázal jsi to! Skvìle! Prokázal jsi Vault City velice cennou slubu. Pøijmi prosím toto jako projev našeho uznání.  Ta banda nám dìlala opravdu velké potíe...}
{485}{lyn072b}{Excelentní. Nic jiného si nezaslouili. Tato banda nám dìlala opravdu velké potíe...}
{486}{}{Ve skuiteènosti nebyli obyèejnou potulnou bandou banditù... byli to oldáci.}
{487}{lyn073}{Take je elektrárna mimo provoz?}
{488}{}{Ne, je opravena. Starší rada McClure mi dal souèástku potøebnou pro bezproblémovı chod elektrárny.}
{489}{}{Všechno je v cajku.}
{490}{lyn074}{Coe?! To e udìlal?! Pøedpokládám, e ti taky udìlil Obèanství! Opravení elektrárny v Gecku nic navyøešilo. Ty... kreatury! Nedá se jim vìøit! Co se stane, kdy zaène z elektrárny znovu unikat radiace?!}
{491}{}{Já nevím... moná jim to POMÙEM opravit?}
{492}{}{Podívejte, podzemní voda ji nebude nikdy znovu kontaminována, nikdo se u nenakazí. Problém byl vyøešen.}
{493}{}{Vrátím se pozdìji, a trochu vychladnete.}
{494}{}{Musím odejít, První Obèanko. Pøeji hezkı den.}
{495}{lyn075}{Lépe støe své kroky tímhle mìstem, "Obèane." Budu tì sledovat. Jeden chybnı krok a tvou odmìnou bude exil.}
{496}{}{Tak dost. Nikdo mi nebude vyhroovat, zvláštì ne nìjaká nafoukaná dìvka. Je èas zemøít.}
{497}{}{Hrej si se mnou, drahá Lynette a Vault City bude potøebovat nového Prvního Obèana. Rozumíš?}
{498}{}{Tak? Pùjdu si za McClurem zpìt pro své Obèanství. To on vypadá spíš jako vhodnı materiál na Prvního Obèana.}
{499}{}{Vrátím se pozdìji, a trochu vychladnete.}
{500}{}{Hezkı den, První Obèanko.}
{501}{lyn076a}{Vıbornì. Ukázal ses jako pravı Obèan Vaultu.}
{502}{lyn076b}{Je mi potìšením udìlit Ti Obèanství, se všemi privilegii a pøístupem k našim zaøízením.}
{503}{}{Hej, doufal jsem spíš v nìjaké ty prašule.}
{504}{}{Bez problémù. Dìlám jen svùj dob. Nashledanou.}
{505}{}{Bylo mi potìšením, První Obèanko. Hezkı den.}
{506}{}{Skvìle, díky. Hned to jdu zjistit.}
{507}{}{Váím si všeho cos pro mne udìlala, První Obèanko. Hezkı den.}
{508}{lyn077ab}{U jsi dostal dost, cizinèe. Obèanství je samo o sobì odmìnou.}
{509}{lyn077b}{Obèanství je samo o sobì odmìnou.}
{510}{}{Kurva! Radši hned vysol nìjaké prachy, nebo si bude Vault City muset hledat nového Prvního Obèana.}
{511}{}{Jasnì... to jenom má zvìdavost. Nashledanou.}
{512}{}{Tak jo, První Obèanko. Pøeji hezkı den.}
{513}{lyn077_a}{Absolutnì ne.}
{514}{}{Rád bych vìdìl, kdo bude mít navrch po tvé smrti... to jest asi tak za minutu od teïka.}
{515}{}{Není problém... Jen jsem to zkoušel. Nashledanou.}
{516}{lyn078}{Dr. Troy?! Co to øíkáš?}
{517}{}{Poádal mne o propašování nìjakıch ilegálních drog do Vault City.}
{518}{}{On jenom poskytuje ošetøení Obèanùm.}
{519}{}{Ale nic... spletl jsem se. Pøeji hezkı den.}
{520}{lyn079}{Kdo jsi, abys tu obviòoval Obèany ze zloèinù? Stráe! Vyveïte tohoto cizince za bránu!}
{521}{}{Stráe se sem nedostanou vèas, aby stihli zachránit Tvùj ivot... "První Obèanko."}
{522}{}{Není tøeba volat stráe -- Odcházím v klidu.}
{523}{}{Ale je to pravda! Musíte mi vìøit! Já --!}
{524}{lyn080}{To je velmi váné obvinìní. Kdy u jsi Obèanem, tak musím Tvá slova brát v úvahu...ale jsi si absolutnì jistı? Jestli je to pravda, tak jeho Obèanství bude zrušeno a bude vyhnán do exilu.}
{525}{}{Podívejte, já vím, e je tomu tìké uvìøit, ale poádal mne o propašování drogy "Jet" do Vault City.}
{526}{}{A není to trochu tvrdé? Nemùete jo tøeba jenom rehabilitovat a ponechat ho doktorem?}
{527}{}{Och. Uh...Spletl jsem se. Chtìl jsem øíci, e Dr. Troy je zapojen v PARALEGÁLNÍCH aktivitách, ne v ilegálních.}
{528}{}{Hmmmm. Jdu se podívat, zda se nedá zjistit nìco dalšího.}
{529}{lyn081}{Nemohu uvìøit tomu, e Obèan takového postavení mùe bıt závislı na drogách. Díky za tvou upøímnost, Obèane. Ihned si to vezmu na starost.}
{530}{}{Mám pár jinıch otázek...}
{531}{}{Fajn. Tato situace mne zaujala. Nashle.}
{532}{}{Dìkuji Ti, První Obèanko. Chci jenom vidìt, jak tady funguje spravedlnost.}
{533}{lyn082a}{Informuj mne, a toho zjistíš víc.}
{534}{lyn082b}{Sláva Vault City, Obèane.}
{535}{}{Mám pár jinıch otázek...}
{536}{}{Jistì. Nashledanou.}
{537}{}{Rozumím. Dìkuji Vám, První Obèanko.}
{538}{lyn083}{Zákon je zákon. Jestli budeme dìlat vıjimky, tak nejsme o nic lepší ne venkovani. Ptám se tì znovu, jsi si absolutnì jistı tím obvinìním?}
{539}{}{A uplácení mne formou získání Obèanství za vyøešení Vašeho problému v Gecku ... to je legální?}
{540}{}{Ano. Poádal mne o propašování drogy "Jet" do Vault City.}
{541}{}{Och. Uh...Spletl jsem se. Chtìl jsem øíci, e Dr. Troy je zapojen v PARALEGÁLNÍCH aktivitách, ne v ilegálních.}
{542}{}{Hmmmm. Jdu se podívat, zda se nedá zjistit nìco dalšího.}
{543}{lyn084a}{Radši si dávej pozor na to, co øíkáš.}
{544}{lyn084b}{Radši si dávej pozor na to, co øíkáš, cizinèe.}
{545}{lyn084c}{Jestli uslyším, e dìláš Dr. Troyovi nebo jinım Obèanùm potíe, tak se u nikdy nebudeš procházet ulicemi Vault City. Rozumíš?}
{546}{}{Uh...j jistì. Promiòte. Mám pár jinıch otázek...}
{547}{}{Jako sklo. Musím u jít.}
{548}{}{Omlouvám se, První Obèanko. Pøeji hezkı den.}
{549}{lyn085}{SAMOZØEJMÌ e pouze léèí Obèany. Nemá èas ošetøovat cizince... na to máme AutoDok na pøedmìstí.}
{550}{}{Moná byste chtìla vìdìt, e mne doktor poádal o propašování nìjakıch ilegálních drog do mìsta.}
{551}{}{Ach. Mám pár jinıch otázek...}
{552}{}{Ano, pro ty kdo zaplatí... a není taky jisté, e vyjdou z toho AutoDoku v jednom kuse.}
{553}{}{Dobrá, nevadí. Nashledanou.}
{554}{}{Omlouvám se, První Obèanko. Pøeji hezkı den.}
{555}{lyn086}{Domnívám se, e je èas na odchod. Chci Ti jenom naznaèit, a se ve Vault City moc dlouho nezdruješ.}
{556}{}{Ne pùjdu, mám pár jinıch otázek...}
{557}{}{V poøádku. U jdu.}
{558}{lyn087}{Moore? Je to buøiè. TO je to správné slovo.}
{559}{}{Máš pravdu. Zabıvá se... vnìjšími zájmy.}
{560}{}{Proè øíkáte e je buøiè?}
{561}{}{Mùu mít další otázku?}
{562}{}{Rozmlouval jsem s ním... a mnoho z toho co øekl dává smysl.}
{563}{}{Souhlasím. Chcete abych...si ho vzal na starost?}
{564}{}{Pak ale mùete zrušit jeho Obèanství.}
{565}{}{Dobøe. Budu se snait mu vyhıbat. Hezkı den.}
{566}{lyn088}{Vytrvale pøesvìdèuje Obèany, aby nastolili ve Vault City..."demokracii,"jak tomu øíkají, kde by mìl kadı co mluvit do zákonù a zúèastòovat se rùznıch usnesení. Já to nazıvám vládou lùzy.}
{567}{}{"Demokracii?"}
{568}{}{A jak pøesvìdèuje Obèany?}
{569}{}{To zní jako problém. Jak se o to mohu... postarat?}
{570}{}{Nemùete ho prostì vykopnut?}
{571}{}{Mám pár jinıch otázek...}
{572}{}{Oh. Tak díky za informace. Hezkı den.}
{573}{lyn089}{Archívy øíkají, e mnoho národù ve starém svìtì mìlo nìco jako vlády. Dovedeš si pøedstavit jak dlouho trvá v takové spoleènosti ne do sebe zaènou zapadat koleèka systému? To je nepochopitelné.}
{574}{}{Nepochopitelné? Proè?}
{575}{}{A jak Moore zkouší pøesvìdèovat Obèany?}
{576}{}{Mám pár jinıch otázek...}
{577}{}{Domnívám se. Musím u jít.}
{578}{}{Díky za Váš èas, První Obèanko. Hezkı den.}
{579}{lyn090}{Vláda potøebuje silného, schopného vùdce, kterı dokáe dìlat rychlé rozhodnutí a taky je prosazovat. Takovı národní vıbor není vládou.}
{580}{}{A jak Moore zkouší pøesvìdèovat Obèany o tom, e ve Vault City mùe bıt demokracie?}
{581}{}{Mám pár jinıch otázek...}
{582}{}{Domnívám se. Musím u jít.}
{583}{}{Díky za Váš èas, První Obèanko. Hezkı den.}
{584}{lyn091}{Nejèastìji øeènìním na veøejnosti a dìláním ze sebe blázna. Zkouší to na nás s povídaèkami o problémech v NCR, jako bychom se mìli starat o zbytek svìta.}
{585}{}{To zní jako opravdovı problém. Chcete abych... si ho vzal na starost?}
{586}{}{Víte moná, e má pravdu:  pravdìpodobnì mùete. Vaše lékaøská technologie je opravdu obdivující.}
{587}{}{Nemùete ho prostì vykopnut?}
{588}{}{Och. Dobrá, to jen moje zvìdavost. Pøeji hezkı den.}
{589}{lyn092}{Ty také? Obèané mùou mít jakékoliv názory, ale tohle...TOHLE! Moná nejsi schopen nést odpovìdnost, kterou s sebou nese Obèanství!}
{590}{}{Húúùù... promiòte! Podívejte, to nevadí... Mám pár jinıch otázek, na které se Vás chci zeptat...}
{591}{}{Jestli to znamená, e se s Vámi musí vdycky slepì souhlasit, tak moná VY NEJSTE schopna nést odpovìdnost Obèanství.}
{592}{}{Thomas Moore je Obèan a on je vùdcem tohoto hnutí.}
{593}{}{Toto je nová epocha, je èas zmìn.}
{594}{}{Je mi líto, e se vydáváš touto cestou. Nashle.}
{595}{lyn093}{Ne. On není OPRAVDOVİ Obèan... ne více. Kdy k nám pøed dvìma lety pøišel, tak splòoval vše co jsme od Obèana oèekávali. Ale v minulém roce se... zmìnil. Obrátil se proti nám.}
{596}{}{Ty víš, e to mùe znamenat pár vìcí. Moore moná jenom nìco chvíli hraje.}
{597}{}{Moná je èas na zmìnu.}
{598}{}{Je mi líto, e nepovaujete Moora za "opravdového" Obèana. Moná byste mìli pøehodnotit co znamená bıt Obèanem.}
{599}{}{Moná se pøidal ke svìtlu. Pøeji hezkı den.}
{600}{lyn094}{Prosperujeme v tomto svìtì, kde jiní selhali a ty mi navrhuješ zmìny? Podívej se na vnìjší svìt! Anarchie, mravní zkáza, choroby...Vault City je ráj!}
{601}{}{To je právì to, PROÈ je zmìna nevyhnutelná. Mìli byste se o vısledky vašeho snaení podìlit s ostatními .}
{602}{}{Pro nìkoho moná ráj. Ale myslím si, e vaši otroci by asi nesouhlasili.}
{603}{}{Ji se o tom nebudu více pøít. Nashledanou.}
{604}{lyn095}{Vault City bylo vybudováno díky tvrdé práci a utrpení mnoha Obèanù. Venkovní svìt si z nás mùe vzít pøíklad a následovat ho a ne sedìt u našich zdí a ebrat o almunu.}
{605}{}{Tvrdá práce Obèanù? Kdekoliv ve mìstì pøijdu, tak vidím pouze dobøe odvedenou práci otrokù.}
{606}{}{Ji se o tom nebudu více pøít. Nashledanou.}
{607}{lyn096}{Proè to provozujem? Tento systém spolehlivì funguje mnoho let. Vyplıvají z toho vıhody.}
{608}{}{To vidím. Mohu mít další otázku?}
{609}{}{Vaši otroci by jistì nesouhlasili.}
{610}{}{Ale... Vy kupujete a prodáváte lidské bytosti jako brahmíny. Netrápí Vás to vlastnìní otrokù?}
{611}{}{Slyšel jsem dost. Nashledanou.}
{612}{}{Díky za Váš èas, První Obèanko. Pøeji hezkı den.}
{613}{lyn097}{Oni nejsou otroky, Jsou pouze naši "sluebníci." Dáváme jim bydlení, jídlo, obleèení. Dáváme jim ivot.}
{614}{}{Jistì. Proè by mìli bıt volní, kdy pro Vás mohou døít?}
{615}{}{Podívejte, není dùleité, jak sladké slovíèka pouíváte k zakrytí toho svinstva, poøád je to otroctví.}
{616}{}{Uh... jistì. Mám pár jinıch otázek...}
{617}{}{Ji se o tom nebudu více pøít. Nashledanou.}
{618}{}{Hmmmm. Takhle jsem o tom ještì neuvaoval. Jdu o tom popøemıšlet.}
{619}{lyn098}{To ty své pokrytectví neschováš. Máš na èele znamení otrokáøské gildy a pøesto nesouhlasíš s otroctvím.}
{620}{}{Ne e nesouhlasím s otroctvím, jenom poukazuji na vısledky tvrdé práce vzniklé právì díky tomuto zacházení.}
{621}{}{Podívejte se, nechal jsem si vytetovat toto znamení pouze proto, aby se mi podaøilo získat urèité informace... Já nejsem otrokáø.}
{622}{}{Byl jsem mladı... Potøeboval jsem peníze...}
{623}{}{U se o tom nebudu víc pøít. Nashledanou.}
{624}{lyn099}{Co tím myslíš?}
{625}{}{Moore teï pracuje pro NCR..}
{626}{}{Nevadí. Mám pár jinıch otázek...}
{627}{}{Nic.  Musím u jít. Nashledanou.}
{628}{}{Nic. Byla to mılka. Pøeji hezkı den, První Obèanko.}
{629}{lyn100}{Zabít ho?! Vrada není v ádném pøípadì forma nebo zpùsob povolenı ve Vault City -- i kdy je to v tom nejlepším úmyslu. Nikdy o tom znovu nemluv.}
{630}{}{Rozumím. Mohu mít pár jinıch otázek?}
{631}{}{Podívej, 'vrada' je hnusné slovo. Mohu naznaèit pár pøípadù nešastnıch náhod. . . pøedávkování drogami, rozmašírování brahmínou...jakákoliv z øady vìcí se mùe stát v tomto nebezpeèném svìtì.}
{632}{}{V poøádku. Odcházím.}
{633}{}{Dobrá, První Obèanko. Pøeji hezkı den.}
{634}{lyn101}{Takhle se Obèan nechová! Ruším Tvé Obèanství. Moje stráe Ti ukáou kudy se dostaneš ven.}
{635}{}{Stráe se sem nedostanou vèas aby zachránili Váš ivot... "První Obèanko."}
{636}{}{Není tøeba volat stráe. V klidu odejdu.}
{637}{lyn102}{Tøebae by to poslouilo zájmùm Vault City, nemohu s tím nic dìlat... Dokud neporuší ádné zákony, mùe si Moore øíkat co chce.}
{638}{}{Chcete... abych si ho vzal na starost?}
{639}{}{Och, ale ano. Moore není obyèejnı Obèan...pracuje ještì pro nìkoho jiného.}
{640}{}{Mùu se zeptat na další otázku?}
{641}{}{Jo, kdy to bude takhle pokraèovat, pohøbí se sám. Promluvíme si pozdìji.}
{642}{}{Rozumím. Nue, díky, e jste si na mne udìlala èas, První Obèanko.}
{643}{lyn103}{Špeh z NCR? To... to... by vysvìtlovalo spoustu vìcí. Dìkuji Ti, Obèane. Hned to jdu vyøídit.}
{644}{}{Mám pár jinıch otázek...}
{645}{}{Skvìle, díky. Nashledanou.}
{646}{}{Dìkuji Ti, První Obèanko.}
{647}{lyn104}{Zaèalo to pøed nìkolika mìsíci. Laserové ostøelovací vìe je zatím vdycky dokázaly zahnat, ale nevíme jak dlouho ještì budou schopny odolávat útokùm.}
{648}{}{Co jsou zaè, ti banditi?}
{649}{}{Mám pár jinıch otázek...}
{650}{}{Musím u jít. Nashledanou.}
{651}{}{To je mi líto; moná odtáhnou nìkam jinam hledat snazší koøist. Pøeji hezkı den, První Obèanko.}
{652}{lyn105}{Venkovní svinstvo. Ji déle ne století se pokoušejí cizinci vyplenit naše mìsto... vdy odtáhli s nepoøízenou. Nakonec i tuhle bandu jednou rozprášíme.}
{653}{}{Ech... "jednou?" Proè jste jim ještì nenakopali ty jejich posrané zadky?}
{654}{}{Mùu mít další otázku?}
{655}{}{Musím u jít. Nashledanou.}
{656}{}{Musím jít. Pøeji hezkı den, První Obèanko.}
{657}{lyn106}{Nalezení jejich základny je tìší, ne se pùvodnì zdálo. A k tomu ještì disponují opravdu velkou palebnou silou. Nicménì jsem zatím odrazili všechny jejich útoky... s minimálními ztrátami.}
{658}{}{Mùu mít další otázku?}
{659}{}{Musím u jít. Nashledanou.}
{660}{}{Díky za Váš èas. Pøeji hezkı den, První Obèanko.}
{661}{lyn107}{Co to je? }
{662}{}{Našel jsem tu jejich základnu. Byli zalezlí v jeskyních pøi úpatí kopcù na jihu.}
{663}{}{Nakopal jsem jim zadky. Byli zalezlí v jeskyních pøi úpatí kopcù na jihu.}
{664}{}{Informace mají svou cenu.}
{665}{}{Nevadí. Musím u jít.}
{666}{lyn108}{Ano? To je skvìlé! Ale mìstské stráe jsou u úplnì vysílené... Zvládneš to sám? Vypoøádáš se s tìmi útoky? Dostaneš zaplaceno.}
{667}{}{Ne, teïka mám moc jiné práce.}
{668}{}{Podívám se, co s tím mùu udìlat.}
{669}{lyn109}{Dobrá. Jestli mne omluvíš, mám teï mnoho práce. Cestu ven znáš.}
{670}{}{Nejprve mám ale pár otázek na které se chci zeptat...}
{671}{}{Jasnì, u jdu.}
{672}{}{Dobrá. Pøeji hezkı den, První Obèanko.}
{673}{lyn110a}{oldáci? Kdo je najal?}
{674}{lyn110b}{Ano, u ses o tom zmiòoval. Víš kdo je najal?}
{675}{}{Vsadím se, e to byla Bishopova rodina z New Rena. }
{676}{}{Bishopova rodina z New Rena.}
{677}{}{Ještì si nejsem jistı. Pracuju na tom.}
{678}{lyn111a}{Coe?! Jak to víš? Jaké máš dùkazy?}
{679}{lyn111b}{Máš nìjaké dùkazy?}
{680}{}{Nemám ádné konkrétní dùkazy, ale v New Renu se šeptá, e za tím stojí Bishopova rodina.}
{681}{}{Tuto úèetní knihu, ve které jsou záznamy o platbách Bishopovy rodiny oldákùm za tøímìsíèní terorizování vašeho mìsta..ach, a jeden mìsíc navíc, pokud budete neústupní, jsem nalezl v trezoru oldákù.}
{682}{}{Poøád ještì nemám ádné konkrétní dùkazy. Pracuji na tom. }
{683}{lyn112}{To mnì nepøekvapuje. Bishop nedávno navštívil Vault City a vnucoval nám spojenectví. Samozøejmì jsem odmítla. Nespolupracujeme s kriminálníky.}
{684}{}{Moná to byl jeho zpùsob, jak Vás k tomu spojenectví donutit.}
{685}{lyn113}{Chtìla jsem brzy poádat NCR o pomoc. Jakmile narazíš na nìjakı konkrétnìjší dùkaz o Bishopovì zapojení do té špíny, tak mi ho hned pøedlo.}
{686}{}{To staèí. Mám pár jinıch otázek...}
{687}{}{Jakmile cokoliv zjistím, tak ti dám vìdìt.}
{688}{}{Ano, První Obèanko. Pøeji hezkı den.}
{689}{lyn114}{To mnì nepøekvapuje. Bishop nedávno navštívil Vault City a vnucoval nám spojenectví. Samozøejmì jsem odmítla. Nespolupracujeme s kriminálníky.}
{690}{}{Myslím, e to pøedpokládal. Tento holodisk jsem našel v Bishopovì trezoru. NCR ho najalo, aby pøimìl Vault City pøipojit se k republice. Kdy jste odmítli jeho nabídku, tak najal oldáky aby na vás útoèili a donutili vás poádat NCR o pomoc.}
{691}{}{Moná to byl jeho zpùsob, jak vás k tomu spojenectví donutit.}
{692}{lyn115}{To je moné... ale nikdy to nemohlo fungovat. Brzy jsem chtìla poádat NCR o pomoc. Prokázal jsi Vault City velkou slubu. Pøijmi prosím toto jako projev našich díkù.}
{693}{}{Díky. Mám pár dalších otázek...}
{694}{}{Jestlie se dozvím víc, tak Vám dám vìdìt.}
{695}{}{Bylo mi potìšením, První Obèanko. Pøeji hezkı den.}
{696}{lyn116}{Je to jasné. Poslali oldáky vradit mé lidi, protoe jsem odmítla pøipojit se k jejich vládì? Já... Já tomu poøád nemohu uvìøit.}
{697}{}{Je to trochu komplikovanìjší. Thomas Moore je do toho také zapleten.}
{698}{}{Je tu ještì nìco s èím mohu pomoci?}
{699}{}{Je to drsnı svìt. A co bude s vyrovnáním --? }
{700}{lyn117}{Takhle se Obèan nechová. Ale já tu informaci potøebuji. Jaká je tvá cena?}
{701}{}{100 dolarù}
{702}{}{200 dolarù}
{703}{}{400 dolarù}
{704}{}{500 dolarù}
{705}{}{Nevadí. Podìlím se o tu informaci s Vámi zdarma.}
{706}{lyn118}{Velmi dobøe, zde jsou tvé peníze. A teï mi povìz, co víš.}
{707}{}{Našel jsem tu jejich základnu. Byli zalezlí v jeskyních pøi úpatí kopcù na jihu.}
{708}{}{Nakopal jsem jim zadky. Byli zalezlí v jeskyních pøi úpatí kopcù na jihu.}
{709}{}{Doopravdy, o nièem moc nevím.}
{710}{}{Díky za hotovost. Musím jít.}
{711}{lyn119}{Potøebuji, abys okamitì vyrazil do NCR. a našel tam kancléøe Westina, Rogera Westina. Dej mu tento holodisk. To by mìlo zajistit, e u ádní "banditi" nebudou najímáni.}
{712}{}{Uh... neslyšela jsi? Westin je mrtev. Myslím, e mìl nehodu. Smrtelnou. Je to dlouhı pøíbìh.}
{713}{}{Poèkejte minutku. Jít do NCR? Nejsou za to všechno odpovìdní právì oni?}
{714}{}{V poøádku, jdu na vìc. }
{715}{}{Díky, ne. Nemám na to èas.}
{716}{lyn120}{Roger Westin byl asi jedinı èestnı mu v té jejich republice, kterı nám byl naklonìn... jeho smrt je pro nás strašnou ztrátou.}
{717}{}{No jo, na takovıho starıho prïolu byl docela tuhej. Bylo za nìj spousta zkušenostních bodù. Take... dostanu odmìnu za všechny ty informace co jsem pro vás získal, nebo...?}
{718}{}{Jasnì, mi je to taky líto. Je to jako bych ho vidìl vèera.}
{719}{lyn121a}{Pøipomínám ti, e jsi u dostal zaplaceno za vyøízení "banditù." Jsme u vyrovnáni. Teï odejdi.}
{720}{lyn121b}{Ano, ano... vedl sis velmi dobøe. Prosím... pøijmi toto jako svou odmìnu.}
{721}{}{ádná odmìna?! Nebylo jednoduché vyhrabat všechny ty politické sraèky. Myslím, e si zaslouím nìco zvláštního, nemyslíš?!}
{722}{}{Zadr, to není vše. Mám pár dalších otázek...}
{723}{}{V poøádku, odcházím.}
{724}{}{Díky. Mám pár jinıch otázek...}
{725}{}{Skvìle! Díky...radši u pùjdu.}
{726}{}{Dìkuji Vám, První Obèanko.}
{727}{lyn122}{Roger Westin je asi jedinı èestnı mu v té jejich republice, kterı nám je naklonìn.}
{728}{}{Dobrá, ten disk mu doruèím.}
{729}{}{Ne, díky. Teï mám moc práce.}
{730}{lyn123}{Tvé vlastenectví nezùstane neodmìnìno. Teï rychle. Èasu není nazbyt.}
{731}{}{Ne pùjdu, tak mám ještì pár otázek...}
{732}{}{Dìlám na tom.}
{733}{}{Na mnì se mùeš spoolehnout, První Obèanko. Vrátím se a doruèím tenhle disk Westinovi.}
{734}{lyn124}{Nicménì, Vault City pøesto obstálo. Prokázal jsi cennou slubu... pøijmi, prosím, toto jako projev našich díkù.}
{735}{}{Díky. Mám pár jinıch otázek...}
{736}{}{Supr! Díky... U musím jít.}
{737}{}{Dìkuji Vám, První Obèanko.}
{738}{lyn125}{Doruèil jsi to?}
{739}{}{Ne. Rád bych vìdìl, co je to ta odmìna, o které jste mluvila.}
{740}{}{Ne, mám moc jiné práce.}
{741}{}{Ne, zatím ne. Ale mám pár otázek...}
{742}{}{Disk jsem doruèil kancléøi Westinovi.}
{743}{}{Zatím ne. Vrátím se a budu hotov.}
{744}{}{Zatím ne, První Obèanko. Vrátím se, a to doruèím Westinovi.}
{745}{lyn126}{Udìláš to?! Skvìle! Vem tedy ten disk, co máš od Bishopa, a pospìš si. Èasu není nazbyt.}
{746}{}{Ne pùjdu, tak se chci ještì zeptat na pár otázek...}
{747}{}{Pracuji na tom.}
{748}{}{Mùeš se mnou poèítat, První Obèanko. Vrátím se, a to doruèím Westinovi.}
{749}{lyn127}{Vìø mi, nebudeš zklamanı. A teï prosím doruè tehle holodisk.}
{750}{}{Ne pùjdu, tak mám ještì pár otázek...}
{751}{}{V poøádku. Pracuji na tom.}
{752}{}{Mùeš se mnou poèítat, První Obèanko. Vrátím se, a to doruèím Westinovi.}
{753}{lyn128}{Vidím, e naše dohoda pro Tebe nic neznamená. Take dobrá; Tvá privilegia ve Vault City jsou zrušena. Mé stráe tì eskortují ke vstupní bránì.}
{754}{}{Zabiju ty stráe... po tom, co zabiju Vás.}
{755}{}{Jasòaèka! Tady, vem si ten disk a já pùjdu. }
{756}{lyn129}{Díky! Prokázal jsi velkou slubu! Poslal Westin nìco zpìt?}
{757}{}{Ano, zaèínám se cítit jako pošák. Tady. Chtìl, abych vám pøedal tento disk.}
{758}{}{Ne, ztratil jsem to.}
{759}{}{Ne, nic jsem nedostal.}
{760}{lyn130a}{Vıbornì. Nech mnì, abych se na nìj podívala.}
{761}{}{tøívteøinové ticho}
{762}{lyn130b}{Teï nebudeme mít s NCR hezky dlouhou dobu ádné problémy.}
{763}{}{To jsou dobré zprávy.}
{764}{lyn131}{A teï... odpovídající mzda: Hlas se u Randala, šéfa obchodního centra. Øekni mu, e jsem tì poslala pro tvou odmìnu a dostaneš malı dárek. Ještì jednou ti dìkuji.}
{765}{}{Ne pùjdu, tak mám ještì pár otázek...}
{766}{}{V poøádku. Odmìna, to je ono.}
{767}{}{Dìkuji Vám, První Obèanko. Pøeji hezkı den.}
{768}{lyn132}{Tvá sluba jsou pøímo ukázková. Je mi ctí jmenovat tì Kapitánem stráí. Gratuluji, kapitáne. Zaslouil sis to.}
{769}{}{Uh... díky.}
{770}{}{Dìkuji Vám, První Obèanko.}
{771}{lyn133}{Dodateènì se hlas u Randala, šéfa obchodního centra. Vyøiï mu, e jsem tì poslala a vyzvedni si svou odmìnu. Jsme tví dluníci... kapitáne.}
{772}{}{Ne pùjdu, tak mám ještì pár otázek...}
{773}{}{V poøádku. Odmìna, to je ono!}
{774}{}{Dìkuji Vám, První Obèanko. Pøeji hezkı den.}
{775}{lyn134}{Tys to ztratil?! To bylo ale nesmírnì dùleité! Take... tady máš nìco za doruèení disku. A teï, jestli mne omluvíš... }
{776}{}{Jenom minutku. Ne pùjdu, tak mám ještì pár otázek...}
{777}{}{Uvidíme se pozdìji.}
{778}{}{Pøeji hezkı den, První Obèanko.}
{779}{lyn135}{Nic Ti nedal? Zvláštní... v kadém pøípadì, tady je tvá platba za doruèení disku. A teï, jestli mne omluvíš...}
{780}{}{Jenom minutku. Ne pùjdu, tak mám ještì pár otázek...}
{781}{}{Uvidíme se pozdìji.}
{782}{}{Pøeji hezkı den, První Obèanko.}
{783}{lyn136}{Co to je?}
{784}{}{Tenhle holodisk jsem našel v Bishopovì trezoru. NCR ho najalo, aby pøimìl Vault City pøipojit se k republice. Kdy jste odmítli jeho prvotní nabídku, tak najal oldáky, aby na vás útoèili a donutili Vás poádat NCR o pomoc.}
{785}{lyn099}{Co tím myslíš?}
{786}{}{Moore teï pracuje pro NCR..}
{787}{lyn138}{Špeh z NCR? To... to... by vysvìtlovalo spoustu vìcí. Dìkuji ti, Obèane. Hned ten problém jdu vyøídit.}
{788}{}{A teï k problému s NCR... mohu s nìèím pomoci?}
{789}{}{To je fajn. Pøesto, za zjištìní všech tìch drbù o Renu a NCR, poèítám, e by to chtìlo odm -- }

# Generic line from 790 to 846 are not used. If this changes, we will need to do the lip-syncing and attach voc files.
{790}{}{Stráe!}
{791}{}{Prosím, bì za prokonzulem. On má to, co potøebuješ.}
{792}{}{Prosím, bì za starším mìstskım radou McClurem. On má to, co potøebuješ.}
{793}{}{Prosím, navštiv mého asistenta. On má to, co potøebuješ.}
{794}{}{Sever}
{795}{}{Jih}
{796}{}{Vıchod}
{797}{}{Západ}
{798}{}{Severozápad}
{799}{}{Severovıchod}
{800}{}{Jihozápad}
{801}{}{Jihovıchod}
{802}{}{Na sever}
{803}{}{Na jih}
{804}{}{Na vıchod}
{805}{}{Na západ}
{806}{}{Na severozápad}
{807}{}{Na severovıchod}
{808}{}{Na jihozápad}
{809}{}{Na jihovıchod}
{810}{}{Já to nechci.}
{811}{}{Dìkuji.}
{812}{}{Díky za Tvùj èas.}
{813}{}{Stráe!}
{814}{}{Miluji Scotta Rodenhisera.}
{815}{}{Moje malé kudrlinky jsou krásné.}
{816}{}{Trochu více thetapaprskù.}
{817}{}{To jsou dobré zprávy.}
{818}{}{V poøádku.}
{819}{}{Hezkı den.}
{820}{}{Dobrı den, Obèane.}
{821}{}{Beru to.}
{822}{}{Dej mi to.}
{823}{}{Nic o tom nevím.}
{824}{}{Já nevím.}
{825}{}{Ano.}
{826}{}{Ne.}
{827}{}{Samozøejmì.}
{828}{}{Jistì.}
{829}{}{Správnì.}
{830}{}{Pøesnì.}
{831}{}{Správnì.}
{832}{}{Hmpphhh.}
{833}{}{Vysvìtli mi znovu, proè nemá Fallout 2 ádné záporné hrdiny?}
{834}{}{Sláva Vault City.}
{835}{}{Sláva Vault City, Obèane.}
{836}{}{Och, chlapèe! Spi! Tam já jsem Vikingem!}
{837}{}{Degene!}
{838}{}{Cizinec}
{839}{}{Venkovní svinstvo...}
{840}{}{*Frrrk*}
{841}{}{*Zzzzzzzzzzz*}
{842}{}{To co je obsaeno na tom disku, je mùe zastavit. Bandité budou odhaleni. A jestli se obsah sdìlení tohoto disku roznese po pøedmìstích NCR, tak u jim nikdo nikdy nebude vìøit.}
{843}{}{Mí informátoøi v Gecku mne informovali, e tam jsou stále ghoulové. Tvé Obèanství závisí na vyøešení této situace... do konce. Mluvím dost jasnì?}
{844}{}{Je mi líto, myslím, e jsem je všechny zabil.}
{845}{}{To je dobrı zaèátek, ale naše podzemní voda je stále kontaminována. Musíš odpojit jejich elektrárnu.}
{846}{}{Pomùe to, ale nevyøeší to náš hlavní problém: kontaminaci podzemní vody. Musíš zastavit únik radiace z elektrárny.}
# End of Unused Dialog

{847}{}{Starší naší vesnice mi dala láhev na vodu, ale nemám ji u sebe. Ale i tak, staré pøíbìhy vyprávìjí o tom, e naši pøedkové pocházejí z Vaultu.}
{848}{}{Myslíš ghouly? Jo, zjistil jsem, co se jim na elektrárnì poškodilo.}
{849}{}{Elektrárna potøebuje hydro-magnet, uch, vìcièku která ji dokáe pomoci opravit. Ghoulové øíkají, e jednu takovou máte, take já ji potøebuji a uèiním tak elektrárnu znovu èistì fungující.}
{850}{}{Potøebují hydroelektrickı magnetosférickı regulátor k opravení elektrárny a tím i zamezení zneèišování podzemní vody. Øíkají, e nìco takového máte zde, ve Vault City. Kdybych mohl tu souèástku dostat...}
{851}{}{Nevadí. Promluvíme si o tom nìkdy jindy.}
{852}{lyn047b}{A co kdy ano? To je jenom doèasné øešení.}
{853}{}{Uch, dobrá, neznám podrobnosti, ale znìlo to jako e magneto-vìcièka mùe pomoci Gecku a Vault City. Mohu tu souèástku dostat?}
{854}{}{Doopravdy. Ten regulátor mùe zajistit bezproblémovı a èistı chod elektrárny po mnoho let. Take, kde bych mohl dostat tu souèástku...?}
{855}{}{Nevadí. Moná najdu nìkoho jiného, kdo mi pomùe.}
{856}{}{Správnì, První Obèanko. Uvidím, co mohu s tímto problémem udìlat.}
{857}{}{Nevím, jestli tomu rozumím. Je tu nìjakı problém s Geckem... nebo s ghouly?}
{858}{}{První Obèanko, prosím vyslyš mnì... je problém získat tu souèástku? Mùe to vyøešit Vaše problémy s Geckem a také pomoci ghoulùm...}
{859}{}{Nevadí. Moná najdu nìkoho jiného, kdo mi pomùe.}
{860}{}{Promiòte, e jsem vyrušoval, První Obèanko.}
{861}{}{Oni nechtìjí nikomu ublíit. Jenom nemají tu souèástku, která dokáe zajistit èistı chod elektrárny. Take, jestli Vás mùu poprosit DEJTE mi tu souèástku...}
{862}{}{Nevadí. Moná najdu nìkoho jiného, kdo mi pomùe.}
{863}{}{Dobrá. Promiòte, e jsem vyrušoval, První Obèanko.}
{864}{lyn017b}{Vevalíš se do mıch pokojù a máš ještì tu drzost ádat o nìco mnì, Lynette, První Obèanku Vault City?!}
{865}{lyn041c}{Koneènì u odejdi, jinak zavolám stráe.}
{866}{}{Tak. Asi potøebuješ velice bolestnou lekci.}
{867}{}{Nevadí. Moná najdu nìkoho jiného, kdo mi pomùe.}
{868}{}{Promiòte, e jsem vyrušoval, První Obèanko.}
{869}{}{Potøebuji jednu souèástku na opravu elektrárny v Gecku.}
{870}{}{Doruèil jsi Westinùv holodisk Lynette.}
{871}{}{Doruèil jsi Westinùv holodisk Lynette a stal ses kapitánem stráí.}
{872}{}{Nandal jsi to oldákùm a pomohl jsi Vault City.}
{873}{}{Odhalil jsi Moora jako špeha NCR.}
{874}{}{Dokázal jsi, e Bishop najal oldáky.}
{875}{}{Dokázal jsi, e Bishop byl najat NCR.}
{876}{}{Potøebuji nìkoho, kdo by zachránil --}
{877}{}{Poèkej vteøinu --}
{878}{}{Zapomeò na to. Odcházím.}
{879}{}{Vypadá to, e s tebou marním svùj èas. Moná by bylo lepší, kdybyste šla pøivést nìkoho, kdo mi mùe pomoci.}
{880}{}{Omlouvám se za nepøíjemnosti. Nashle.}
{881}{}{To je fajn slyšet. Take...?}
{882}{}{Dìkuji Vám, První Obèanko.}
{883}{}{Ach, to byla moje mılka... Nechci bıt sprostı --}
{884}{}{Omlouvám se, První Obèanko. Já --}
{885}{}{Stráe!}