#tento soubor prelozil Tomas "LOCKHEAR" Jurecka
{100}{}{Vidíš Val. Nebo Valerii. Nebo jak chceš.}
{101}{}{Vidíš hnìdovlásku obleèenou v koené zástìøe, na které má kovové brnìní. Vypadá jako mechanik.}
{102}{}{Vidíš Val. Nebo Valerii. Nebo jak chceš.}
{103}{}{Vidíš hnìdovlásku obleèenou v koené zástìøe, na které má kovové brnìní. Vypadá jako mechanik.}
{104}{}{Ach, nazdar, "tati."}
{105}{}{-- 1 vteøina --}
{106}{}{Valerie. Rád Tì zase vidím.}
{107}{}{Oh, uh, ahoj, tati. Ráda tì zase vidím. Fakt.}
{108}{}{-- 1 vteøinu --}
{109}{}{Ahoj, Valerie. Taky Tì zase rád vidím.}
{110}{}{Radši bys mìl vzít toho mutanta pryè, ne ho zpozorují stráe.}
{111}{}{Radši bys mìl vzít toho ghoula pryè, ne ho zpozorují stráe.}
{112}{}{Zase stupidní, nudné elezo...}
{113}{}{Ten soustruh by u potøeboval naolejovat...}
{114}{}{Musím udìlat seznam tìchto nadbyteènıch souèástek pro První obèanku.}
{115}{}{Rozbìhni se, ty zasranı kuse šrotu!}
{116}{}{Jsem obklopena idioty...}
{117}{}{Kdybych tak mìla to správné náøadí!}
{118}{}{Mám chu jít zabít toho holohlavého opièáka v obchodním centru...}
{119}{}{Je pøíliš pozdì. Vra se ráno.}
{120}{}{Obchod je zavøenı. A dokonèím ten seznam pro První Obèanku, tak pùjdu domù.}
{121}{}{Nemám teï èas. Dej mi jeden den èasu. Snad to u budu mít hotovo.}
{122}{}{Mám toho ještì spoustu na opravování. Vra se za jeden nebo dva dny.}
{123}{}{Dobøe, jestlie to není "šéf" mého táty.}
{124}{}{Ano?!}
{125}{}{Ty snad nìco CHCEŠ, nebo tady chceš postávat jako slabomyslnı blbec?}
{126}{}{Bllll-béééc}
{127}{}{Vypal}
{128}{}{Jupíí, klídek. Jenom jsem se zašel podívat, co to tu je.}
{129}{}{Mìj se na pozoru. Nemám dnes náladu na nìjaké srandièky.}
{130}{}{Hledám Vault. Mùeš mi øíct, kde bych ho našel?}
{131}{}{Doopravdy u odcházím.}
{132}{}{Je to velkı otvor ve vıchodní skále, mezi tìmi dvìma nebezpeènì vypadajícími maníky. Chceš ještì nìco, nebo se mùu vrátit ke své práci?}
{133}{}{Co to je za místo?}
{134}{}{Mìj se na pozoru. Nemám dnes náladu na nìjaké srandièky.}
{135}{}{Díky za radu. Nashle.}
{136}{}{Jestlie Vault City nemá dostatek lidskıch brahmín... podívej, ty tu ZÙSTAT NEMÙEŠ,JE TO JASNÉ? Mohlo by Ti to ublíit! TEÏ VYPADNI! BÌ!}
{137}{}{*mmllask* Ty velkíí meníí... *mlasky*... já cíí mít klaunííí... *srrk*... a zmrzlinúúú...a kafíí...a necíí tak chytréé lidièkii jako tııı!}
{138}{}{Vypal}
{139}{}{Vysmahni odsud. Nebo pùjdu najít stráe a TY tì odsud *vysmahnou*.}
{140}{}{Zkus to. Mnì se to líbí.}
{141}{}{V poøádku, jdu pryè.}
{142}{}{Tohle je údrbáøská dílna pro Vault City. Nebo jsi snad PØEHLÍDL ten obravskı nápis na zdi budovy?}
{143}{}{Ne, promiò. Zdálo se mi, e to je nìjakı jinı krámek.}
{144}{}{Zapomeò na to. Omlouvám se za vyrušení.}
{145}{}{Jsi tady "u nìjakého krámku" správnì. Podívej, potøebuješ nìco opravit, nebo se chceš zeptat na nìjaké hloupé otázky?}
{146}{}{Co dokáeš opravit?}
{147}{}{Mìj se na pozoru. Nemám dnes náladu na nìjaké srandièky.}
{148}{}{Dnes vlastnì jenom hloupé otázky. Promluvíme si pozdìji.}
{149}{}{Syntetické alkoholové rozprašovaèe, vysílaèky, palné zbranì, èásti laserovıch vìí, poèítaèové monitory, staèí jen øíci název...ale jen kdy budu mít své náøadí.}
{150}{}{Náøadí?}
{151}{}{Zní to jako tvrdı oøíšek. Radìji Ti ho pøenechám.}
{152}{}{Teï u soustruh trochu funguje, ale mùj francouzskı klíè je fuè... U ZASE... a kleštì jsou celé ošoupané.}
{153}{}{Mohu Ti s nìèím pomoci?}
{154}{}{Je snad nìjakı problém sehnat nové náøadí?}
{155}{}{Tak dobøe. Pøeji hezkı den.}
{156}{}{Ty? O tom pochybuji.}
{157}{}{No, mám francouzák a nìkolik kleští pøímo u sebe.}
{158}{}{Pomùe Ti úplnì novı francouzskı klíè a sada kleští?}
{159}{}{Je snad nìjakı problém sehnat nové náøadí?}
{160}{}{Asi nechceš mou pomoc. Ale nevadí.}
{161}{}{PROBLÉM je v tom, e já nemohu jít jen tak ven a koupit si nové náøadí, tady ve Vault City musím podat oficiální ádost. To pøedstavuje vyplnìní asi 5 biliónù formuláøù, jejich následné odeslání ve tøech kopiích a pak samozøejmì ÈEKÁNÍ.}
{162}{}{Ale proè--?}
{163}{}{To je mi l--}
{164}{}{Do prdele, objednala jsem si Super náøadí pøed nìkolika MÌSÍCI, ale jako obvykle se ukáe a ve chvíli, kdy u ho nebudu potøebovat. Takové vìci se tu dìjí neustále...}
{165}{}{Moná Ti mohu pomoci.}
{166}{}{Ach. Dobøe, to je mi líto. Moná se vrátím.}
{167}{}{Ano. A jak?}
{168}{}{No, mám francouzák a nìkolik kleští pøímo u sebe.}
{169}{}{Moná bude lepší, kdy vyrazím nìco takového najít a pak Ti to pøinesu.}
{170}{}{Je snad nìjakı problém sehnat nové náøadí?}
{171}{}{Oh. Dobrá, dík za radu.}
{172}{}{Já nechci zadrovat tak dlouho dech, ale jestli Ti to udìlá dobøe, tak bì. Je to Tvùj èas. Ne mùj. Moná Ti budu moci dát nìjakou malièkost jako odmìnu za nenadálé problémy.}
{173}{}{Jestli se mi podaøí najít nìjakı francouzák a kleštì, tak je sem donesu.}
{174}{}{Fakticky?}
{175}{}{Jasan.}
{176}{}{Umm... dìkuji. Vím, e to není ádná sláva, ale aspoò nìco. A kde jsi to seb....ale, nevadí. Není to dùleité. Tady máš nìco málo za snahu.}
{177}{}{Díky. Mám ještì pár otázek...}
{178}{}{Moná to mùeš pouít na zdokonalení své figury.}
{179}{}{ádnı problém. Kdykoliv pomùu, staèí øíci.}
{180}{}{Jistì, jistì... podívej, mám nìjakou práci. Vra se za jeden nebo dva dny, jo? Pak budu mít èas na pokec.}
{181}{}{Uvidíme se teda zítra.}
{182}{}{Nu dobrá. Vrátím se za jeden, nebo dva dny. Nashle.}
{183}{}{Tomu nebudeš vìøit. Ani ne den po tom, co jsem od tebe dostala to náøadí, mi pøišel ten mùj dávno objednanı Super náøadít . Ale ne jeden. Poslali mi jich hned PÌT. Co se do hajzlu dìje s tou objednávkovou kanceláøí?!}
{184}{}{Mohla bys postrádat jednu z tìch souprav?}
{185}{}{Proè ne?! Co bych dìlala s PÌTI?! Tu máš, vem si! Pøísahám, e pùjdu udìlat cirkus tìm pošukùm co to spískali.}
{186}{}{Díky. Mám ještì pár otázek...}
{187}{}{Váím si toho. Pouiji to jen k dobrım vìcem.}
{188}{}{To vidím. Fajn, co teda chceš?}
{189}{}{Co? Nemám èas proklevetit celı den.}
{190}{}{Ano? Co?}
{191}{}{Mùeš opravit nìco z toho co mám u sebe?}
{192}{}{Tak co mi nabídneš?}
{193}{}{Tak co se dìje mezi Tebou a Tvım otcem?}
{194}{}{Nevadí. Nechám Tì pracovat.}
{195}{}{Ale celkem nic dùleitého. Jenom sem pøed dvaceti lety s jednou karavanou pøijel, vyšukal mámu a zase odjel. Ne se tu teï ukázal, tak jsem ho tu pìt let nevidìla. ádná škoda.}
{196}{}{Zní to jako e si máte asi spolu co povídat.}
{197}{}{Och. Tak tedy, ehm, mám pár jinıch otázek...}
{198}{}{Nevadí. Nebudu Tì u rušit.}
{199}{}{Ne, to teda nemáme. Co jsme potøebovali, to jsme si u vyøíkali dávno. }
{200}{}{Jsi si jistá?}
{201}{}{Tak dobrá. Mám nìkolik jinıch otázek...}
{202}{}{Nechám Tì teda pracovat.}
{203}{}{Ano, to teda JSEM. A... na to, e vypadá jako by mohl shodit pár kilo. Asi má moc volného èasu. Mohl by pøestat putovat pustinou a skonèit s tím prodejem haraburdí domorodcùm. To by bylo fajn.}
{204}{}{Podívej, mìl velké problémy s otrokáøi, jenom zkouší dohnat ztracenı èas. Ale máš pravdu, mohl by trochu shodit.}
{205}{}{Och. Tak tedy, ehm, mám pár jinıch otázek...}
{206}{}{Nevadí. Nebudu Tì u rušit.}
{207}{}{Heh-heh. Ty máš teda jízlivı tón. Líbí se mi. Jako pro starého tauldu... dobrá... hmmm. Zkusím bıt zdvoøilejší. Ale jenom na chvíli.}
{208}{}{Uhh... urèitì u nemá ádné trable, fakticky?}
{209}{}{Paráda. Podívej, chci se Tì zeptat na nìco jiného...}
{210}{}{Dìlám jak nejlíp umím. Chci se Tì zeptat na nìco jiného...}
{211}{}{To je vše co jsem chtìl vìdìt. Nechám Tì teï pracovat.}
{212}{}{Zkusím. Najdem to, a se vydáme kamkoliv. Na vidìnou, Valerie.}
{213}{}{Tak podívej, já nemám nic "na skladì." Tohle není skladištì. Vìtšina vìcí, které zde opravím, konèí v obchodním centru... najdeš to, kdy vyjdeš ze dveøí a dáš se doleva.}
{214}{}{Jak u jsem Ti to jednou ØEKLA, tohle není skladištì. Bì do obchodního centra, jestli chceš zbraò. Tady vìci pouze OPRAVUJU.}
{215}{}{Dobøe, mùeš teda opravit nìco z toho, co mám u sebe?}
{216}{}{Mùeš opravit nìco z toho, co mám u sebe?}
{217}{}{V poøádku, v poøádku. Nashle.}
{218}{}{No... moná. Uka co máš.}
{219}{}{Uka jí své pistole.}
{220}{}{Uka jí své pušky.}
{221}{}{Uka jí svou základní vıbavu.}
{222}{}{Nevadí. Chci znát nìco jiného...}
{223}{}{Moná nìkdy jindy.}
{224}{}{Mohla bych namontovat urychlovaè nabíjení na tvùj magnum, stálo by to $800.}
{225}{}{Hmmmm. Ten Tvùj pouštní orel... mùu mu pøidat rozšíøenı zásobník, jestli chceš. Stojí $1000.}
{226}{}{Uprav mi magnum.}
{227}{}{A co takhle $650 za tu úpravu magnumu?}
{228}{}{Uprav mi pouštního orla.}
{229}{}{A co takhle $850 za úpravu pouštního orla?}
{230}{}{Zapomeò na pistole. Mùeš vylepšit nìjaké jiné z mıch zbraní?}
{231}{}{Chci znát nìco jiného...}
{232}{}{Vrátím se, a budu mít vìtší hotovost.}
{233}{}{Hmmm. Moná nìkdy jindy.}
{234}{}{Tvoje lovecká puška... mùu jí dát rozšíøenı zásobník za $1500.}
{235}{}{Hmmmm. Mám jeden zesilovaè svìtla, mùu ho namontovat na tvou FN FAL za $3500.}
{236}{}{Rozšiø zásobník na AK-112 útoèné pušce.}
{237}{}{Promluvme si o $1350 za úpravu útoèné pušky.}
{238}{}{Namontuj mi ten zesilovaè svìtla na FN FAL.}
{239}{}{Promluvme si o $3100 za zesilovaè svìtla.}
{240}{}{Mohla bys vylepšit nìjaké jiné z mıch zbraní?}
{241}{}{Nevadí. Chci nìco jiného...}
{242}{}{Momentálnì, ádnou z nich. Musím jít.}
{243}{}{Vrátím se, a budu mít více prašulí na útratu.}
{244}{}{Myslím, e bych mohla dodat více šávy pro Tvùj elektroobušek. Bude to stát $750.}
{245}{}{V poøádku. }
{246}{}{A co takhle $650?}
{247}{}{Mohla bys vylepšit nìjaké jiné z mıch zbraní?}
{248}{}{Nevadí. Chci nìco jiného...}
{249}{}{Momentálnì, ádnou z nich. Musím jít.}
{250}{}{Pro mne je to pøíliš drahé. Vrátím se, a budu mít více penìz.}
{251}{}{Vidím, e u máš od mého otce pochyceny nìkteré smlouvaèské triky. Dej mi hodinu a bude to hotovo...}
{252}{}{Jasnì, jasnì. Smlouváš jako mùj otec. Dej mi hodinu a bude to hotovo...}
{253}{}{V poøádku, dej mi hodinu a bude to hotovo...}
{254}{}{V poøádku.}
{255}{}{Tady to máš. Ještì nìco?}
{256}{}{Mám pár jinıch otázek...}
{257}{}{Mùeš vylepšit ještì nìco z toho, co mám?}
{258}{}{Dnes u nic. Dík.}
{259}{}{Tak co bys... uh... Tati?}
{260}{}{Promiòte?}
{261}{}{Ach, ne, já ne. Myslím, myslím e urèitì ne.}
{262}{}{Tati?!}
{263}{}{-- 2 vteøiny --}
{264}{}{Valerie?! Miláèku, jsi to ty?}
{265}{}{-- 2 vteøiny --}
{266}{}{Kde jsi u všech trojokıch koèek byl?! Poøád se couráš pustinou a prodáváš lesklé cetky domorodcùm?}
{267}{}{-- 4 vteøiny --}
{268}{}{Ehm, he-he... neber ji vánì, šéfe, ona neví co mluví... Val, miláèku... víš, byli zde otrokáøi a...}
{269}{}{-- 4 vteøiny --}
{270}{}{Pøestaò plácat, tati. POØÁD øíkáš kadému koho potkáš "Šéfe?", vdycky jsem to nesnášela.}
{271}{}{-- 4 vteøiny --}
{272}{}{Valerie, miláèku, prosím... nech mnì to vysvìtlit... poslouchej...}
{273}{}{-- 2 sekundy a hovor se ztrácí...}
{274}{}{... a tak jsme opustili Den.}
{275}{}{-- 2 vteøiny --}
{276}{}{To je ale pìkná hromádka brahmíního trusu.}
{277}{}{-- 2 vteøiny --}
{278}{}{To je pravda!}
{279}{}{-- 2 vteøiny --}
{280}{}{Nezaèínej. Jsem ráda, e tu není máma aby to slyšela.}
{281}{}{-- 2 vteøiny --}
{282}{}{Coe? Co se stalo tvé matce?}
{283}{}{-- 2 vteøiny --}
{284}{}{Mozková horeèka. Chytla to nìkde v pustinì. Moná jak hledala TEBE.}
{285}{}{-- 2 vteøiny --}
{286}{}{Ach. Já... ehm... Je mi to moc líto, Val.}
{287}{}{-- 2 vteøiny --}
{288}{}{Dìlám si jenom prdel.}
{289}{}{-- 2 vteøiny --}
{290}{}{Co-?!}
{291}{}{-- 2 vteøiny --}
{292}{}{Doopravdy zemøela na otravu radiací. Lokla si pár douškù nepøefiltrované vody z pøedmìstské studny.}
{293}{}{-- 4 vteøiny --}
{294}{}{Co... coe?!}
{295}{}{-- 2 vteøiny --}
{296}{}{To nebyla Tvá chyba. Jejím tìlem prošlo pøíliš mnoho jednotek záøení, ne aby ji mohl doktor Troy zachránit. Svítila jako lampa.}
{297}{}{-- 2 vteøiny --}
{298}{}{Och. Já... no, já...}
{299}{}{-- 2 vteøiny --}
{300}{}{Nedìlej si starosti. Byla pøedtím pìknì oralá, jako vdycky. trvalo to jenom chvíli.}
{301}{}{-- 3 vteøiny --}
{302}{}{I tak je mi moc líto, e jsem nemìl pøíleitost ji znovu vidìt.}
{303}{}{-- 2 vteøiny --}
{304}{}{Ne, tobì ne. Volal jsi na ni pøece ty 'pouštní zmije,' nepamatuješ?}
{305}{}{-- 2 vteøiny --}
{306}{}{Ale... ano. Ale Ty tak své matku neøík--}
{307}{}{-- 2 vteøiny --}
{308}{}{Proè ne? Byla to pravda. Byla to pìkná dìvka, kdy chtìla.}
{309}{}{-- 2 vteøiny --}
{310}{}{Uh... jak je vidìt, zaøídila ses dobøe. Asi jsi zdìdila otcovu schopnost opravovat rùzné vìci, jak vidím.}
{311}{}{-- 2 vteøiny --}
{312}{}{Tati... ty si sotva pøilepíš podráky, nato opravit nìco, co má pohyblivé souèástky.}
{313}{}{-- 2 vteøiny --}
{314}{}{Co-?! Co to k sakru povídáš!}
{315}{}{-- 2 vteøiny --}
{316}{}{Zeptej se svého "šéfa."}
{317}{}{-- 2 vteøiny --}
{318}{}{Nooo... umí spravovat vysílaèky. A nìjakou veteš.}
{319}{}{Ub glg ub}
{320}{}{-- 2 vteøiny --}
{321}{}{Jestli mu dáš ale VŠECHNY souèástky, e jo?}
{322}{}{Vidím, e cestuješ s lidmi, kteøí jsou jenom trošilinku chytøejší ne ty.}
{323}{}{-- 2 vteøiny --}
{324}{}{Nu, ano.}
{325}{}{Ub glg ub?}
{326}{}{-- 2 vteøiny --}
{327}{}{Ha! To znám. Lok, lok.}
{328}{}{Tvùj "šéf" je v opravování vìcí lepší ne jsi Ty.}
{329}{}{-- 2 vteøiny --}
{330}{}{Nue, Val, kdy já Tì naposled vidìl, tak jsi stìí dokázala o dlátu øíct "baci bebe fuj fuj .}
{331}{}{-- 2 vteøiny --}
{332}{}{Ale Tati, neøíkej, Ty to dláto budeš potøebovat, abys dostal moje boty ze svého zadku.}
{333}{}{-- 2 vteøiny --}
{334}{}{Och, ano?! Dobøe, "miláèku," bude lepší, kdy si dáš poz-}
{335}{}{-- 2 vteøiny --}
{336}{}{Dr hubu! Drte huby oba dva! Zašlo to PØÍLIŠ DALEKO! Teï, jdeme Vicu.}
{337}{}{UGRGHH! JDEME! U ANI SLOVO! JDEME!}
{338}{}{-- 3 vteøiny --}
{339}{}{Promluvíme si pozdìji, Val.}
{340}{}{-- 2 vteøiny --}
{341}{}{Ale samozøejmì, tati.}
{342}{}{-- 2 vteøiny --}
{343}{}{bìhem tøí vteøin hovor upadá do ztracena}
{344}{}{Hej! Je fajn, e jsi zpátky. Kolují tu zvìsti, e jsi cestoval hluboko na jih, tam jsi prı nièil staré tankery a rozbíjel ropné plošiny.}
{345}{}{Vrátil ses, abys našel trochu klidu a míru, velkı hrdino?}
{346}{}{Vrátil ses, abys našel trochu klidu a míru, velkı závislı hrdino?}
{347}{}{HE-hu? Híí-híí! Kuk!}
{348}{}{Vypal}
{349}{}{Chtìl jsem se vrátit a na chvíli zase pod nohama cítit dlabu Vault City. Ten klid a mír je balzám na mou duši. Potøebuji nejprve nìco vyøídit...}
{350}{}{Dnes nic, díky. Ale budu si to pamatovat.}
{351}{}{Podívej, musíš tu bıt opatrnı, rozumíš? Jestli nám chceš pomoci, tak nám neboø Vault City. A... hej, díky za záchranu nás všech.}
{352}{}{Jasan! Pa-Pá!}
{353}{}{Vypal}
{354}{}{Nevadí. Promluvím si s tebou pozdìji.}
{355}{}{Podaøilo se ti Valerii obstarat nové náøadí.}
{356}{}{Podaøilo se ti pøesvìdèit Val, aby dala tátovi šanci.}
{357}{}{ ***DO NOT DELETE THE NEXT LINE (#358)! IT'S NEEDED FOR THE SCRIPT. DON'T BOTHER TRANSLATING THIS, EITHER***}
{358}{}{}
{359}{}{Hej, mám to náøadí cos chtìla.}
{360}{}{Nevypadá to, e bys mìla nìjaké zboí, do kterého fušuju. Zajímají mnì pušky, pistole a podobné hraèièky.}
