#tento soubor prelozil Tomas "LOCKHEAR" Jurecka
{100}{}{Vidíš staršího senátora McClura.}
{101}{}{Vidíš postaršího úøedníka Vault City. Má u prošedivìlé kouty vlasù.}
{102}{}{Vidíš staršího senátora McClura.}
{103}{}{Vidíš postaršího úøedníka Vault City. Má u prošedivìlé kouty vlasù.}
{104}{}{Ji jsem slyšel o tvıch hrdinskıch èinech. Jsme ti všichni zavázáni... Vyvolenı.}
{105}{}{Musím si ještì udìlat poøádek v tìchto papírech. Vra se sem ráno a promluvíme si.}
{106}{}{Ghoul?! Stráe! Stráe!}
{107}{}{Mutant?! Stráe! Stráe!}
{108}{}{Nemám ti co øíci. Odejdi, nebo zavolám stráe.}
{109}{}{Dobrı den... Kapitáne, je to tak správnì? Hodnì jsem o tobì slyšel. Je zde nìco, s èím bych ti mohl pomoci?}
{110}{}{Dobrı den... Obèane, je to tak správnì? Ji jsem slyšel o novém èlenovi naší komunity. Je zde nìco, s èím bych ti mohl pomoci?}
{111}{}{Zdravím... mohu Ti pomoci?}
{112}{}{Dobrı den, Kapitáne. Vše je v poøádku, jak doufám?}
{113}{}{Dobrı den, Obèane. Mohu ti pomoci?}
{114}{}{Ano? Chtìl jsi ještì nìco jiného?}
{115}{}{Sa-tan Klaus?}
{116}{}{Vypal}
{117}{}{Mohu se Vás zeptat na pár otázek?}
{118}{}{Kdo jste?}
{119}{}{Jenom se rozhlíím kolem, díky. Pøeji hezkı den.}
{120}{}{Jak se Ti podaøilo dostat do našeho mìsta? Stráe! Máme tu cizince, kterı potøebuje eskortovat k branám mìsta!}
{121}{}{Ne e e e nic  nepudúú}
{122}{}{Achhh... Nepudúúú? No tak nezlob.}
{123}{}{Jistì, Kapitáne.}
{124}{}{Jistì, Obèane.}
{125}{}{Tak co bys rád vìdìl?}
{126}{}{Jaké zde máte postavení?}
{127}{}{Hledám GECK.}
{128}{}{Co mi mùete øíci o První Obèance?}
{129}{}{Chci se Vás zeptat na pár vìcí ohlednì osady Gecko.}
{130}{}{Co mi mùete øíci o mìstì Redding?}
{131}{}{Potøebuji si s Vámi promluvit o Reddingu.}
{132}{}{Jak se jeden mùe stát Obèanem?}
{133}{}{Myslím, e byste mohl sehnat souèástku, která je nutná k opravì elektrárny v Gecku.}
{134}{}{Elektrárna v Gecku je opravena.}
{135}{}{Mám datadisk s ekonomickımi údaji, které by Vás mohly zajímat.}
{136}{}{Znám zpùsob, jak optimalizovat reaktor v Gecku.}
{137}{}{Tady je datadisk s údaji o reaktoru v Gecku. Mohl byste tyto údaje optimalizovat?}
{138}{}{Dnes nic, díky.}
{139}{}{Já jsem starší senátor McClure. A ty...?}
{140}{}{To není Vaše vìc.}
{141}{}{. Je potìšení s Vámi jednat.}
{142}{}{Doopravdy musím jít. Necháme to na nìkdy jindy.}
{143}{}{Takové hulvátství bych èekal od nìjakého cizince, ne od Obèana. Já jsem èlen senátu Vault City a ty mi budeš prokazovat patøiènı respekt, nebo zruším tvé Obèanství. Rozumìl jsi mi?}
{144}{}{Nepovídej, starochu.}
{145}{}{To je nevídané. Ale i pøesto s Tebou budu mluvit.}
{146}{}{Promiòte. Nechci Vás urazit.}
{147}{}{A je to tady, pøesnì takové drzé jednání jsem od cizince oèekával! Odevzdej mi svou jednodenní propustku a jdi se stráemi. V našem mìstì není místo pro tıpky, jako jsi Ty.}
{148}{}{Tobì nedám nic. Chceš to? Tak pojï a vem si to.}
{149}{}{Já NEJSEM cizinec. Jsem Obèan.}
{150}{}{Oukej, oukej, u jdu.. pøece se nepo...}
{151}{}{Tomu je tìké uvìøit. Uka mi své doklady.}
{152}{}{Tady, moje doklady!}
{153}{}{Chceš je? Pojï si je vzít.}
{154}{}{Nechápu, jak se nìkdo takového podøadného vychování mùe stát obèanem, ale tyto doklady vypadají e jsou v poøádku. Zvláštní... Nemohu si vzpomenout, e bych tì tu ji døíve vidìl. Co se dá dìlat, budu respektovat tvé Obèanství.}
{155}{}{To máš teda zatracenou pravdu, e bys mìl respektovat mé Obèanství!}
{156}{}{Jo, dobøe. U jdu.}
{157}{}{Neopova se na mnì ještì nìkdy promluvit. Jestli to zkusíš, tak zruším tvé Obèanství. Pøeji hezkı den.}
{158}{}{Dobrı den.}
{159}{}{Jen si zkus zrušit mé Obèanství, bude tì to mrzet.}
{160}{}{Jsi u slabı, starochu. Nejsi pro mnì soupeø. Leda, e bych si tì povìsil za uši na strop a pouil tì jako boxovací pytel.}
{161}{}{A dost! A jsi Obèan nebo ne, vypadni odsud. Stráe, ukate tady tomu degenerovanému jedinci, kde je brána!}
{162}{}{Odcházím. Je to ale zasrané místo.}
{163}{}{Nejdu nikam.}
{164}{}{Co pro tebe mohu udìlat?}
{165}{}{Ještì nevím, starochu. Povìz, co pro mne MÙEŠ udìlat?}
{166}{}{Hledám GECK.}
{167}{}{Mohu se Vás zeptat na pár otázek?}
{168}{}{Dnes u ne. Musím ještì udìlat pochùzku po budovì (a zkontrolovat zda zamìstnanci úøadu nesouloí v pracovní dobì).}
{169}{}{GECK? Pokud je mi známo, tak jeden tady mìli. Èetl jsem, e to byl na dlouhou dobu jeden z posledních, ale porouchal se mnoho let pøed mım narozením. Ale zdá se mi, e bylo poádáno o druhı kus...}
{170}{}{Poádáno?}
{171}{}{... Ale stará vláda oèividnì zpackala zásobování a my jsme dostali vìci, které náleely Vaultu... tøináct, takhle to myslím bylo. Take oni Tím pádem asi obdreli náš náhradní GECK.}
{172}{}{Co bylo v zásilce urèené Vaultu 13?}
{173}{}{Co se stalo s rozbitou soupravou GECK?}
{174}{}{Mùu mít další otázku?}
{175}{}{To vidím. Díky za informace.}
{176}{}{Vodní èipy, asi sto nebo víc. Nevím, proè jich poslali tak hodnì... ten náš nikdy nepøestal fungovat. Máme poøád ten jeden pùvodní, kterı je v provozu od doby, kdy lidé zaèali ít v podzemních Vaultech.}
{177}{}{Co se stalo s rozbitou soupravou GECK?}
{178}{}{Mùu mít další otázku?}
{179}{}{Zajímavé. Díky za vše.}
{180}{}{iletka byla hodnì ostrá. Moná bychom si mohli promluvit a pøestanu krvácet.}
{181}{}{Byl rozebrán a jeho souèástky byly pouity k jinım úèelùm.}
{182}{}{Co bylo v zásilce urèené Vaultu 13?}
{183}{}{Mùu mít další otázku?}
{184}{}{To vidím. Díky za vše.}
{185}{}{Je to èelní pøedstavitel všech našich obyvatel. Obèané Vault City k ní vzhlíejí jako ke svému vùdci, ale v dùleitıch vìcech koneèné slovo mají ústy Senátu vdy Obèané. V tìchto nelehkıch èasech je pilíøem naší spoleènosti.}
{186}{}{"Nelehkıch èasech?" Co tím myslíte?}
{187}{}{A co ty?}
{188}{}{Mùu mít další otázku?}
{189}{}{Díky za vše. Nashledanou.}
{190}{}{Gecko? Co bys rád vìdìl?}
{191}{}{Kde je Gecko?}
{192}{}{Co je Gecko?}
{193}{}{Mùu mít další otázku?}
{194}{}{Díky za vše. Nashledanou.}
{195}{}{Není co øíci, A na fakt, e naše zásilky rudy jsou èím dál tím menší a interval mezi dodávkami se neustále prodluuje.}
{196}{}{A ví se proè?}
{197}{}{Kde je Redding?}
{198}{}{Mùu mít další otázku?}
{199}{}{Díky za vše. Nashledanou.}
{200}{}{Jsem starší senátor. Øídím schùze senátu.}
{201}{}{A co teda potom dìlá První Obèanka?}
{202}{}{Mohu se Vás zeptat na další otázku?}
{203}{}{Díky za vše. Nashledanou.}
{204}{}{Take, Obèanství není jen tak pro kadého, tomu rozumíš. Mnì spíše pøipadáš jako dobrodruh... Opravdu nevím, jestli budeš moci bıt Obèanem.}
{205}{}{Hu, rychle... jenom mi povìzte co vše je nutné k získání Obèanství.}
{206}{}{I pøesto se chci poøád stát Obèanem.}
{207}{}{Mohu se Vás zeptat na další otázku?}
{208}{}{Tak nevadí.}
{209}{}{Pøeješ si stát se Obèanem? Nue dobrá. To, co potøebuješ udìlat, je zajít k prokonzulovi Gregorymu a on tì podrobí Obèanskému testu.}
{210}{}{Kde najdu prokonzula Gregoryho?}
{211}{}{Mohu se Vás zeptat na další otázku?}
{212}{}{Díky. Jdu se po nìm podívat. Nashledanou.}
{213}{}{Velmi dobøe. To, co potøebuješ udìlat, je zajít k prokonzulovi Gregorymu a on Tì podrobí Obèanskému testu.}
{214}{}{Kde najdu prokonzula Gregoryho?}
{215}{}{Mohu se Vás zeptat na další otázku?}
{216}{}{Tak jo. Teï se jdu podívat za prokonzulem.}
{217}{}{Najdeš ho ve vıchodním køídle budovy. Jeho kanceláø je poblí kanceláøe První Obèanky.}
{218}{}{Mohu se Vás zeptat na další otázku?}
{219}{}{Díky za vše. Nashledanou.}
{220}{}{Poslední dva roky nebyly pøíliš jednoduché. NCR je stále agresivnìjší ve svıch pokusech pøipojit Vault City ke své republice.}
{221}{}{Øekli nám, e jestli se pøipojíme, tak potom budou moci chránit naše mìsto pøed nájezdy banditù. S postupem èasu jsou útoky banditù stále brutálnìjší.}
{222}{}{Tak v první øadì je to fakt, e v Gecku jsou ghoulové, kteøí kontaminují naši podzemní vodu.}
{223}{}{Kde najdu Gecko?}
{224}{}{Co to je Gecko?}
{225}{}{Nelehké èasy, no jistì. Mùu mít další otázku?}
{226}{}{To je mi líto. Díky za vše. Nashledanou.}
{227}{}{Je to pøímo na severovıchod, ale jestli tam chceš jít, tak Ti doporuèuji si sehnat nìjaké antiradiaèní pøípravky . Jestlie kontaminují naši vodu, tak jejich osada bude urèitì ozáøením svítit jako vıbojka.}
{228}{}{Co to je Gecko?}
{229}{}{Mùu mít další otázku?}
{230}{}{Díky za varování. Nashledanou.}
{231}{}{Je to lidmi opuštìné místo, osada z chatrèí vybudovaná na pozùstatcích staré atomové elektrárny.}
{232}{}{Kde leí Gecko?}
{233}{}{Mùu mít další otázku?}
{234}{}{Díky za vše. Nashledanou.}
{235}{}{Ne. Pøesnì tomu nerozumím. Platíme dolary za jejich rudu, ale kdykoliv si o tom chceme promluvit, zaènou bıt vyhıbaví. Kdybych tak vìdìl, co se k èertu dìje...}
{236}{}{Mùu to pro Vás zkusit vypátrat.}
{237}{}{Kde je Redding?}
{238}{}{Díky za vše. Nashledanou.}
{239}{}{Myslíš, e by to šlo? Není v mé pravomoci nechat Ti za to zaplatit, ale Tvá pomoc bude jistì vysoce ohodnocena.}
{240}{}{Kde je Redding?}
{241}{}{Jasná vìc. Jdu se pustit do pátrání a vrátím se, a zjistím co se dìje.}
{242}{}{Redding je asi tıden cesty na západ. Nikdy jsem tam nebyl. Nikdy jsem neopustil zdi Vault City. Z doslechu vím, e Redding je prı centrum zábavy v nekoneènıch pustinách.}
{243}{}{Máte nìjakou teorii, co zpùsobuje zpoïování zásilek?}
{244}{}{To vidím. Díky za informace.}
{245}{}{Copak to je? Cokoliv øekneš, mi mùe hodnì pomoci.}
{246}{}{Co víš o Reddingu?}
{247}{}{Zjistil jsem, e valná vìtšina obyvatel Reddingu je závislá na droze nazıvané Jet. Horníci, aby nepøestali dostávat dávky, prodají vìtšinu vydolované rudy do New Rena.}
{248}{}{Dr. Troy vyrobil protilátku na  Jet.}
{249}{}{Doruèil jsem protilátku do Reddingu.}
{250}{}{Co je zaè ten "Jet", na kterém jsou všichni závislí?}
{251}{}{Povím Vám to pozdìji a toho vypátrám více.}
{252}{}{Je to droga se 100%-ní návykovostí a je témìø nemoné ji pøestat uívat.}
{253}{}{O všem mne prosím informuj.}
{254}{}{Mohu se zeptat na pár dalších otázek?}
{255}{}{Jistì.}
{256}{}{To jsou mrzuté zprávy, musíme najít zpùsob, jak to zastavit. Jestli to takhle pùjde dál, tak naše zásoby rudy zmizí. Prosím, pomoz nám.}
{257}{}{Uvidím, co se dá dìlat.}
{258}{}{Opravdu? Tak na co tady ještì èekáš? Doruè ji Doc Johnsonovi do Reddingu! On u bude vìdìt, jak to horníkùm naoèkovat.}
{259}{}{Já vím, u jsem to od tebe slyšel. Vem ji do Reddingu a sleduj, jestli jim pomùe.}
{260}{}{Mùu mít ještì pár otázek, ne vyrazím na cestu?}
{261}{}{Oukej, nashledanou.}
{262}{}{Dìkuji ti! Teï mùeme jenom èekat. Máme nadìji, e to vyøeší náš problém. Dìkuji ti ještì jednou za všechnu tvou pomoc.}
{263}{}{Jsi tu vítán. Rád Ti poslouím.}
{264}{}{Bez problému. Mùu se zeptat na pár otázek?}
{265}{}{Uááá... nedostanu vùbec nic za mou snahu?}
{266}{}{Jestli peníze jsou to, co chceš, tak je teda dostaneš. Tady máš 500 dolarù za snahu. Pøeji hezkı den.}
{267}{}{DÌKUJI Ti.}
{268}{}{Pìt s--? Tìch penìz vyklop trochu víc a rychle, jinak Tvùj ivot nebude stát ani 2 dolary.}
{269}{}{Co si myslíš?}
{270}{}{Kdyby se našel hydroelektrickı regulátor magnetosféry, tak dokáu ,e jejich elektrárna nebude zneèisovat vodu a vzduch.}
{271}{}{Ale nic. Promiò za ty trable.}
{272}{}{To je pøijatelné øešení. Zastavení radiaèního záøení je vše, co chci.}
{273}{}{Mám strach, e kdy opravím tu elektrárnu, tak mi Lynette odepøe Obèanství.}
{274}{}{Jooo! Kde si mùu vyzvednout tu souèástku?}
{275}{}{Budu na to myslet.}
{276}{}{Kdy opravíš elektrárnu, udìlím ti Obèanství a ona u s tím nic nebude moci udìlat.}
{277}{}{To je paráda! Kde si mùu vyzvednout tu souèástku?}
{278}{}{Navštiv Randala, šéfa obchodního centra. Mìl by mít tu souèástku ve skladu.}
{279}{}{Díky. Hned jdu za ním.}
{280}{}{Je tu ještì jedna vìc. Moná vás bude zajímat tento datadisk s ekonomickımi údaji.}
{281}{}{Excelentní! Dìlal jsem si starosti, e nás stále sílící radiace donutí opustit toto místo. Na tuto prácièku jsi byl doporuèen skvìle.}
{282}{}{Sláva Vault City, Obèane.}
{283}{}{Sláva Vault City, Kapitáne.}
{284}{}{Tady máš své doklady prokazující tvé obèanství. Kdykoliv budeš nìco potøebovat, tak pøijï za mnou.}
{285}{}{Sláva Vault City , senátore.}
{286}{}{Díky.}
{287}{}{Ano, ji jsem to od tebe slyšel.}
{288}{}{Vıbornì, Kapitáne.}
{289}{}{Vıbornì, Obèane.}
{290}{}{Vıbornì.}
{291}{}{Mám pár dalších otázek...}
{292}{}{Díky.}
{293}{}{Promiò... datadisk s ekonomickımi údaji? Co tím myslíš?}
{294}{}{Tady, podívejte se na to.}
{295}{}{Je to datadisk s ekonomickımi provozními údaji elektrárny Gecko, s hodnotami, které elektrárna produkovala pøed válkou... a mohla by produkovat znovu.}
{296}{}{Nevadí. Mám pár jinıch otázek.}
{297}{}{Ale nic. Promiòte za to vyrušení.}
{298}{}{Vıbornì. Malı moment...}
{299}{}{V poøádku.}
{300}{}{Hmmm. Kde byl tento datadisk?}
{301}{}{Já... podaøilo se mi ho najít.}
{302}{}{Byl zapadlı v archívech knihovny Vault City.}
{303}{}{Dal mi ho nìkdo v Gecku.}
{304}{}{Dal mi ho ghoul v Gecku. Jmenuje se Gordon Gecko. Zajímá ho zvıšení vıkonu elektrárny a o energii se chce podìlit s Vault City... vımìnou za Vaši lékaøskou technologii.}
{305}{}{Já... vidím. Take. Co to má se mnou spoleèného?}
{306}{}{Dobrá, jestli tomu dobøe rozumím, tak generátor elektøiny ve Vault City dokáe vyrobit energii jen pro urèitı poèet obyvatel. Ve skuteènosti se tento poèet u brzy naplní.}
{307}{}{Nebudu se ptát, jak se ti podaøilo tuto informaci získat, ale kdy je pravdivá, tak co navrhuješ?}
{308}{}{Kdyby byla elektrárna v Gecku opravena, tak by produkovala, jak dokazuje tento datadisk, dostatek energie i pro Vault City. Nejprve se ale musí optimalizovat vıkon samotného reaktoru.}
{309}{}{Tento disk dokazuje, e elektrárna v Gecku... jestlie bude optimalizována... bude produkovat spoustu energie. Mnohem víc, ne dokáe osada Gecko spotøebovat. Vault City by tuto energii mohlo taky vyuívat.}
{310}{}{Naznaèuješ, e bychom se mohli ZMOCNIT Gecka a zabrat jim elektrárnu? To teda NEBUDU poslou--}
{311}{}{Ne, ne... jestlie Gecko dostane optimalizaèní data pro svou elektrárnu, Tak ruku na to, e Vám nabídnou svou nadbyteènou energii vımìnou za lékaøskou pomoc od Vás .}
{312}{}{Hmmm. Kdy se jedná o lékaøskou pomoc, tak v zásadì nejsem proti domluvì s ghouly. Jsou dostateènì spolehliví... ale jak mùeme optimalizovat jejich elektrárnu?}
{313}{}{Já nevím. Moná je zde nìkdo, s kım si mohu promluvit a bude elektrárna opravena.}
{314}{}{Já nevím. Moná si mùu promluvit s nìkım v elektrárnì}
{315}{}{Potøebuji získat pøístup k poèítaèi Vault City. Ten dokáe optimalizovat datadisk reaktoru elektrárny a tím zvıšit její vıkon.}
{316}{}{K Tvému návrhu nemám námitek. Jestli zjistíš jak optimalizovat elektrárnu, tak mi dej vìdìt.}
{317}{}{Dobrá. Jdu si k Randalovi pro tu souèástku a podívám se na reaktor.}
{318}{}{Velmi dobøe, Kapitáne.}
{319}{}{Velmi dobøe, Obèane.}
{320}{}{Máš mé povolení pouít poèítaè Vault computer a optimalizovat datadisk reaktoru. Poèítaè je v tøetím podlaí Vaultu, blízko operaèního pokoje.}
{321}{}{Vıbornì. Dìkuji Vám, senátore. U jdu na to.}
{322}{}{Hotovo. Bì.}
{323}{}{Vezmu si ten ekonomickı datadisk a prostuduji ho... Moná se mi podaøí pøesvìdèit senát, abychom zaèali jednat s osadou Gecko o dodávkách jejich energie. Tento datadisk je sám o sobì velmi silnım argumentem.}
{324}{}{Akceptuji to. Díky.}
{325}{}{Hmmm. Dobrá, já Ti sice nemohu povolit pøístup do Vaultu, ale mùu optimalizovat datadisk reaktoru za Tebe.}
{326}{}{V poøádku. Nemám ale ten datadisk u sebe. Vrátím se s ním.}
{327}{}{To by bylo fajn.}
{328}{}{Vıbornì!}
{329}{}{V poøádku.}
{330}{}{Dej mi ten datadisk reaktoru, a já ho nechám v centrálním poèítaèi Vault City zoptimalizovat.}
{331}{}{Fajn. Díky.}
{332}{}{Co to je?}
{333}{}{Mám tady datadisk reaktoru z Gecka. Podle.... ech, technikù z elektrárny, poèítaè ve Vault City dokáe optimalizovat datadisk reaktoru a tím znaènì vylepšit i zvıšit vıkon elektrárny.}
{334}{}{Stráe! Stráe!}
{335}{}{}
{336}{}{Podaøilo se Ti objasnit McClurovi Reddingovskı problém s velmi návykovou drogou Jet.}
{337}{}{Pøedáváš ekonomickı datadisk McClurovi.}
{338}{}{Stále hledám zpùsob jak optimalizovat elektrárnu.}
{339}{}{Stále hledám zpùsob jak optimalizovat elektrárnu.}
{340}{}{Pøál bych si pomoci, ale bojím se, e mé znalosti jadernıch reaktorù jsou ponìkud... omezené. Moná nìkterı z elektrárenskıch technikù Gecka bude znát postup optimalizace?}
{341}{}{Moná. Mám pár jinıch otázek...}
{342}{}{Moná ano. Jdu se podívat.}
{343}{}{Informuješ McClura o dodávce protilátek na Jet.}
