#tento soubor prelozil Jarda "PIZDUCH" Skarda
{100}{}{Vidíš místní zdravotní sestru, Phyllis.}
{101}{}{Vidíš štíhlou mladou enu. Je slabì cítit dezinfekcí.}
{102}{}{Vidíš zdravotnici Phyllis.}
{103}{}{Vidíš štíhlou mladou enu. Je slabì cítit dezinfekcí.}
{104}{}{Riskoval jsi vlastní ivot, abys nás všechny zachránil. Jsi nejstateènìjší èlovìk, kterého jsem poznala.}
{105}{}{Vetøelec! Pomóóóccc! Stráe!}
{106}{}{Mutant! Pomóóóccc! Stráe!}
{107}{}{Ghoul! Pomóóóccc! Stráe!}
{108}{}{Potøebuji okopírovat Gregorovy mapy...}
{109}{}{Pojï se podívat. Máme tøi otroky oèkované dle rozpisu za 1400...}
{110}{}{Všechno to pípání mì dohání k šílenství...}
{111}{}{Pøísahám, e lékaøské údaje hovoøí o...}
{112}{}{Nech mì podívat se... tøi podkoní, dezinfekèní, tøi ampule RadXu...}
{113}{}{Lépe pøipravit Dr. Troye na zítøejší pøednášku...}
{114}{}{Ach, opìt budeme pracovat pøesèas. Vìtšinou vyplòujeme seznamy.}
{115}{}{Mùeš se vrátit ráno zpìt.}
{116}{}{Myslím si, e vyzvednu seznam zítra ráno, jestlie je to naléhavé.}
{117}{}{Nemohu èekat, musím jít domù. Vyplò mi tyto seznamy, odnesu si je.}
{118}{}{Bude nejlepší, kdy se vrátíš. Musím vyplnit tyto seznamy.}
{119}{}{Nešastnı Dr. Troy. Nemohl nic udìlat!}
{120}{}{Proè poslali Dr. Troye do vyhnanství?}
{121}{}{Doufám, e Dr. Troy bude v poøádku ve vnìjším svìtì...}
{122}{}{Hmm. Mám moc práce, ne abych si teï s tebou mohla povídat. Jestlie nìco potøebuješ, jdi navštívit Dr. Troye.}
{123}{}{Áá! Vítej tady. Nikdy jsem tì tady nevidìla... jsi novı Obèan?}
{124}{}{Áá! Vítej zpìt.}
{125}{}{Op-èan?}
{126}{}{A-gin?}
{127}{}{Jauvajs... *fòuk*... ouvej BOLEST}
{128}{}{Vlastnì, já jsem novı Kapitán stráí.}
{129}{}{Jo, jsem obèanem jen chvíli.}
{130}{}{No jo, jsem obèanem jen chvíli.}
{131}{}{Omlouvám se, myslela jsem si, e jsi nìkdo jinı. Hezkı den.}
{132}{}{Ach jo, jsi zranìn, mám pravdu? Omlouvám se, Mìla jsem dávat vìtší pozor. Jdi za Dr. Troyem. On se o tebe postará.}
{133}{}{U...kej? Jup-jup.}
{134}{}{Mohu se nejprve na nìco zeptat?}
{135}{}{Díky. Pùjdu se za ním podívat. Hned.}
{136}{}{Oh! Ty musíš bıt jeden z otrokù, pøidìlenı sem na práci pøes den. Musíš bıt... uh, hmmm. JDI K MARTINOVI.}
{137}{}{Uh... hmmm. Ještì jednou poslouchej, je zavøeno: JDI K MARTINOVI.}
{138}{}{DI K MARTINOVI.}
{139}{}{Au, to to bolí... *AU...*... to je bolest...}
{140}{}{Vypadni}
{141}{}{ANO, MARTIN. JDI NA SPODNÍ ÚROVEÒ.}
{142}{}{ANO, MAR-TIN. JDI NA SPODNÍ ÚROVEÒ.}
{143}{}{Au, to to bolí... *AU...*... to je bolest...}
{144}{}{Vypadni}
{145}{}{SPODNÍ ÚROVEÒ. ÚROVEÒ - TØI. TEÏ.}
{146}{}{JSEM TEÏ NA SPODNÍ ÚROVEÒI TØI.}
{147}{}{Au, to to bolí... *AU...*... to je bolest...}
{148}{}{Vypadni}
{149}{}{Moná, e otrok trpí jakımsi syndromem nedostatku inteligence...}
{150}{}{Oh! Tak, vítejte ve Vault City, Kapitáne.}
{151}{}{No, vítejte ve Vault City, Obèane.}
{152}{}{Není nám dopøáno spatøit mnoho novıch tváøí. Jmenuji se Phyllis. Jak se jmenuješ ty?}
{153}{}{Jmenuji se }
{154}{}{Jsem }
{155}{}{Kdy ti budu chtít øíct své jméno, tak ti ho øeknu, "Si-filis"... nebo jak se sakra jmenuješ.}
{156}{}{Omlouvám se, ale mám moc práce, ne abych si teï s tebou mohla povídat.}
{157}{}{Proè jen...! Nikdy jsen nepotkala nikoho tak nízkého jako jsi ty. Bude lepší kdy pùjdeš. Hned.}
{158}{}{Buï budu muset tón tvého hlasu pøehlíet, nebo budou problémy.}
{159}{}{Proè vlastnì. V kadém pøípadì si tady s tebou povídám.}
{160}{}{Stráe ! Dr. Troyi! Pomoc!}
{161}{}{Tak o co tady jde, no? Pak tedy dobøe...}
{162}{}{Jsem zdejší zdravotní sestra. Pracuji pro Dr. Troye.}
{163}{}{Jaké máš mínìní o Dr. Troyovi?}
{164}{}{Mohu se na nìco zeptat?}
{165}{}{Vıbornì. Zrovna potøebuji nìjakou zdravotní pomoc.}
{166}{}{Omlouvám se, ale mám moc práce, ne abych si teï s tebou mohla povídat.}
{167}{}{Vítej nazpìt. Potøebuješ s nìèím pomoct?}
{168}{}{Zajisté. Co chceš vìdìt?}
{169}{}{Jaké máš mínìní o Dr. Troyovi?}
{170}{}{Mùeš mi øíct kde je centrální poèítaè?}
{171}{}{Potøebuji uzdravit.}
{172}{}{Co tady dìláš?}
{173}{}{Mùeš mi vyprávìt o Vault City?}
{174}{}{Opravdu, to nevadí. V kadé pøípadì díky.}
{175}{}{Oh, Dr. Troy je nìkdy pìknì pøísnı, ale celkem vzato je do dobrej chlap. Vault City je šastné, e ho tady má.}
{176}{}{No, ptal se mì jestli mohu do mìsta propašovat nìkaké drogy.}
{177}{}{Mohu se ještì na nìco zeptat?}
{178}{}{Díky za tvùj èas. Nashle.}
{179}{}{}
{180}{}{}
{181}{}{Jsi si jistı? To vùbec nevypadá na Dr. Troye. Stále... poslední dobou velmi tvrdì pracoval... ne, ne, to je nemoné. Musíš se mılit.}
{182}{}{Nemyslím si. Zdálo se e má zcela jasno èeho chce dosáhnout.}
{183}{}{Hmmmm. Mohu se ještì na nìco zeptat?}
{184}{}{Nevadí.}
{185}{}{Budu si dávat velkı pozor na to co øíkáš o Dr. Troyovi ve Vault City. Je váenı èlen naší spoleènosti.}
{186}{}{Dobrá, tedy. Mohu se ještì na nìco zeptat?}
{187}{}{Dìkuji za upozornìní. Moná bych si mìl jít popovídat s nìkım jinım}
{188}{}{Je to dole na tøetí úrovni, jestlie jsi to pamatuji dobøe. U jsem dole nebyla celou vìènost.}
{189}{}{Proè ne?}
{190}{}{Mohu se ještì na nìco zeptat?}
{191}{}{Dìkuji za radu. Nashle.}
{192}{}{Oh, nevím. Není mnoho dùvodù proè chodit dolù do Vaultu. V souèasné dobì je pøevánì vyuíván jako skladovací prostor. Je pouze jedinı èlovìk, kterı je dole. Je to Martin... a je právì tady. Nepatøí mezi nejlepší spoleèníky.}
{193}{}{Uhh.... Proè z nìho udìlali kašpara, jestlie mu tato práce nesedí?}
{194}{}{Mohu se ještì na nìco zeptat?}
{195}{}{Chápu. Díky za informace.}
{196}{}{Uh... moná by bylo nejlepší si s ním jít pohovoøit. Vy dva mùete mít mnohem více spoleèného ne se mi zdálo na první pohled.}
{197}{}{Mohu se ještì nejdøíve na nìco zeptat?}
{198}{}{Tak dobøe. Pùjdu si s ním popovídat.}
{199}{}{Vault City? No, ve skuteènosti, tady není co vyprávìt. Myslím si, e jsem byla Obèan celı svùj ivot... ale tady ve Vault City není mnoho co dìlat. Skoro.}
{200}{}{Vypadá to jako ostuda, e taková pøekrásná mladá ena jako jsi nemùe najít vùbec nic na práci ve Vault City.}
{201}{}{Vùbec nic? Tak pojï.}
{202}{}{Mohu se ještì na nìco zeptat...}
{203}{}{Oh, dobøe. Teï jsem si vzpomnìl co jsem chtìl.}
{204}{}{Podívej se, vím, e jsi novı Obèan a tak se ti tu vše zdá nové. Nechci tì zrazovat od tvıch nadìjí, ale toto mìsto umí bıt obèas pøíšernì nudné.}
{205}{}{Nudné? Jak je to moné?}
{206}{}{Tak to je hodnì špatné. Mohu se ještì na nìco zeptat...}
{207}{}{No co. Je smutné o tom slyšet.}
{208}{}{Mám pocit, všiml sis, jak jsou si všichni podobní? A jak jsou staøí? Vìtšina pøednášek a spoleèenskıch akcí se orientuje na osmdesátníky. Je mi skoro dvacet pìt let a tohle mìsto zpùsobuje, e se cítím na padesát.}
{209}{}{Uh... osmdesátníky? Máš na mysli stráe?}
{210}{}{Kdy pøišla øeè na stáøí - všiml jsem si, e ve mìstì není ani jedno dítì.}
{211}{}{Všiml jsem si podobnosti mezi Obèany.}
{212}{}{Oh, dobøe. Teï jsem si vzpomnìl co chci.}
{213}{}{Uh ne... "osmdesátníci" je to pøídavné jméno, které se vztahuje na osoby, kteøí jsou osmdesát let staøí.}
{214}{}{No, jasnì. Mohu se ještì na nìco zeptat?}
{215}{}{Dobrá tedy. Moná si popovídáme pozdìji.}
{216}{}{No... ano. Ve skuteènosti nejsou. Zatím. Nevím zda u ti to nìkdo povídal, ale Vault City je plánovaná spoleènost. Nemáme právo ještì nìkolik pøíštích let na další tìhotenskı cyklus.}
{217}{}{Uh... tìhotenskı cyklus?}
{218}{}{Mohu se ještì na nìco zeptat?}
{219}{}{Chápu. No, díky za informace.}
{220}{}{Ano. Gravidita je povolená jen v urèitıch letech. Bylo to zavedeno mìstskou radou.}
{221}{}{Co se stane jestlie pøijdeš do jiného stavu nìkdy jindy?}
{222}{}{Oh. Mohu se ještì na nìco zeptat...}
{223}{}{Chápu. No, díky za informace.}
{224}{}{Jak by se to mohlo stát?}
{225}{}{Uh, kdysi jsem slyšela, e SEX mùe zpùsobit otìhotnìní.}
{226}{}{Zapomnìl jsem, u jsem se ptal. Podívej, rád bych se na nìco zeptal...}
{227}{}{Nevadí. Radìji u pùjdu.}
{228}{}{Hmmm, ty asi myslíš pohlavní styk? Pohlavní styk je venku stále uznávanı zpùsob jak otìhotnìt.}
{229}{}{Nedìlá eny tìhotné?}
{230}{}{Oh. Mohu se ještì na nìco zeptat...}
{231}{}{Oh, dobøe. Teï jsem si vzpomnìl co jsem chtìl.}
{232}{}{Oh, ne, ne... pochop, naše otìhotnìní není následek pohlavního styku.}
{233}{}{Obával jsem se zeptat, ale stejnì se zeptám.}
{234}{}{Víc u nechci vìdìt. Aèkoliv, mohu se ještì na nìco zeptat..?}
{235}{}{Myslím si, e jsem slyšel dost.}
{236}{}{Mui-Obèani "vìnují" automatickımu doktorovi zde ve Vaultu svoje ... a nejvíce vhodnı dárce je vybrán poèítaèem. Potom je vhodná ena-Obèanka oplodnìna automatickım doktorem.}
{237}{}{Mohu taky "vìnovat"?}
{238}{}{Proè u eny nejsou oplodòovány pohlavním stykem? A co pøi náhodnım otìhotnìní?}
{239}{}{Víš, velmi rád bych se zeptal na nìco jiného.}
{240}{}{Mùeš mì omluvit? Musím se jít podívat, jestli mùu svoje obèanství zrušit. Je to tady jako inseminaèní stanice.}
{241}{}{Myslím si, e musím jít nìkam za roh, kde se budu moci v klidu vyzvracet. Sbohem.}
{242}{}{Samozøejmì. Uvítáme tvùj pøíspìvek. Vault City bude moci pouít èerstvı genetickı potenciál.}
{243}{}{Pak tedy dobøe...}
{244}{}{Øekni mi, mùu dostat nìjakı èasopis nebo nìco podobného?}
{245}{}{Tvùj pøíspìvek je pùsobivı... zdá se, e jsi docela nadanı. Jak se cítíš?}
{246}{}{Vıbornì! Díky.}
{247}{}{Hmmm. Moná, e tvùj pøíspìvek není tak hodnotnı, jak jsem si myslela. V kadém pøípadì dìkujeme, alespoò myslím.}
{248}{}{Mohu namouduši øíct, e jsem nikdy nepostrádal primitivní kouzlo boha lásky víc, ne v tuto chvíli.}
{249}{}{Nikdy jsem necítila potøebu bıt drena víc, ne v tuto chvíli.}
{250}{}{Ne, dìkuji ti.}
{251}{}{No, ve skuteènosti... uvidíš, je to nìco o èem jsem pøed nedávnem pøemıšlela, ale Obèanky to nepovaují za vhodnı zpùsob otìhotnìní. Za úspìšné otìhotnìní je povaováno pouze otìhotnìní pomocí automatického doktora.}
{252}{}{Víš, pùvodní radiace mùe mít za následek sterilitu nebo dokonce ještì v horším pøípadì poškození chromozómù. Musí se to zkontrolovat.}
{253}{}{Moná, e právì to je ta pøíèina, proè tady kolem není mnoho pøirozeného sexu.}
{254}{}{Oh, dobøe. Teï jsem si vzpomnìl, co jsem chtìl.}
{255}{}{Víš, myslel jsem na stejnou vìc. Moná bude lepší to probrat s Dr. Troyem. Poslední dobou je pøíliš zamìstnán, ale pøíští ovulaèní cyklus tu bude co nevidìt, tak...}
{256}{}{Mohu se ještì na nìco zeptat?}
{257}{}{Zmínit se o tom pøed Dr. Troyem je dobrı nápad. Hodnì štìstí.}
{258}{}{Je to jako by všichni byli... zkøíení, jako králíci. Všichni se obleèou stejnì, budou se chovat stejnì, a to nejhorší na tom je, e kadı bude vypadat šastnı. A nìkdy... nìkdy se bojím, e skonèím jako oni. Je to pravdìpodobnì nesmysl, e jo?}
{259}{}{Ne ve všem. Tlak pøizpùsobit se musí bıt tady poøádnì silnı, zvláštì s ohledem jak osamocená spoleènost je Vault City.}
{260}{}{Oh, dobøe. Teï jsem si vzpomnìl co jsem chtìl.}
{261}{}{Jo, obèas to mùe dát ohromující vısledky. Ale jsem zde, abych svrhnul váš názor ve Vault City. Nerozumìjte mi špatnì. Je to nejlepší místo k ivotu.}
{262}{}{Je to jen návrh, ale mùeš cestovat trochu ven z Vault City. Dokonce mùeš mluvit i s nìjakımi kupci na pøedmìstí. Oni mohou rozšíøit o trochu tvùj horizont poznání.}
{263}{}{Má to nepochybnì své pøednosti. Mohu se ještì na nìco zeptat?}
{264}{}{Mám radost, e jsi šastná. Moná si ještì popovídáme.}
{265}{}{No, jsem v pokušení jít se podívat ven za bránu, ale ostatní Obèané mì pøed tím varovali...}
{266}{}{Je tady ještì jeden dùvod, proè to udìlat. Ty nechceš dìlat to, co dìlají ostatní Obèané, je to pravda? Oni vše podøizují svım zvyklostem.}
{267}{}{No, venku to mùe bıt nebezpeèné. Øekni mi, mohu se ještì na nìco zeptat?}
{268}{}{Mají pravdu. Pravdìpodobnì to není dobrı nápad. Radìji pùjdu.}
{269}{}{Hel, máš pravdu. Moná budu jen krok venku, kdy dostanu šanci. Ráda bych se dozvìdìla víc o venkovním svìtì.}
{270}{}{Vıbornì. Øekni, mohu se ještì na nìco zeptat?}
{271}{}{Bude to jen dobøe. Buï opatrná.}
{272}{}{Prosím?}
{273}{}{Nemohu ti pomoct, ale jsi atraktivní mladá ena, která by nemìla zùstávat sama venku moc dlouho. Co takhle ty, já a veèeøe?}
{274}{}{Nikdy. Mohu se ještì na nìco zeptat?}
{275}{}{Oh, dobøe. Teï jsem si vzpomnìl co jsem chtìl.}
{276}{}{Oh. Já... a ty víš, Mìla bych tì ráda, ale nemohu.}
{277}{}{Oh. No, Já... já taky.}
{278}{}{Au, dì-lej. Jsem jako znovuzrozená. Chci to, a jsou potíe, jestlie je to takové...}
{279}{}{V poøádku. Mohu se ještì na nìco zeptat?}
{280}{}{Oh, dobøe. Teï jsem si vzpomnìl co jsem chtìl.}
{281}{}{Vıbornì! Jdeme na to.}
{282}{}{Dìkuji za pøekrásnı veèer.}
{283}{}{Uh... jistì. Moná, e pùjdeme ven ještì nìkdy. Urèitì... uh, zavolám ti. Nashle.}
{284}{}{Omlouvám se, ale ne.}
{285}{}{V poøádku. Mohu se místo toho ještì na nìco zeptat?}
{286}{}{Oh, dobøe. Teï jsem si vzpomnìl, co jsem chtìl.}
{287}{}{No, je hezké vidìt, e ten starı dobrı sex není pøedsudek a zaèíná oívat ve Vault City. Nashle.}
{288}{}{. Co tady budeš dìlat?}
{289}{}{. Nebude vadit, jestlie ti poloím nìjaké otázky?}
{290}{}{No jo, myslím si, e tady nemají ádné dìti, protoe mùou bıt jen v US verzi Fallout 2. Nashle.}
{291}{}{Dal jsi Vault City dar a pøedstavuje to vhodnı genetickı materiál do jejich spoleènosti.}
{292}{}{Dal jsi Vault City dar a pøedstavuje to èistı genetickı materiál do jejich spoleènosti.}
{293}{}{Dal jsi Vault City dar... kadopádnì se vyplatí.}
{294}{}{Pøesvìdèil jsi Phyllis, aby si promluvila s Dr. Troyem o moné neplodnosti ve Vault City.}
{295}{}{Pøesvìdèil jsi Phyllis, aby se podívala ven na okolní svìt.}
{296}{}{Rychle jsi objevil, e Phyllis je spíš nezajímavá a uzavøená do sebe. Rozhodl ses, e se nebudeš zajímat o nìkoho, jako je ona.}
{297}{}{Mluví o osmdesátnících - fuj, o starcích a staøenách, Všiml jsem si, e ve Vault City nejsou ádné dìti. Je to zvláštní...}