#tento soubor prelozil Jarda "PIZDUCH" Skarda
{100}{}{Vidíš staøíka, v jehož oèích probleskují známky šílenství.}
{101}{}{Vidíš starýho Joea, místního šíleného vìdce.}
{102}{}{Ahoj. Nìjaký èas jsme se nevidìli.}
{103}{}{Mìl bych tì znát?}
{104}{}{No, ano. Je to chvilka. Co jsi dìlal?}
{105}{}{Dobøe, byla to chvilka. Kam až jsi se dostal?}
{106}{}{To a ono. Odkud mì znáš?}
{107}{}{Podívej, staøíku, nevím kdo, sakra jsi.}
{108}{}{Jsem si jist. No..., Získával jsem zkušenosti a nakonec jsem skonèil tady, na tomto bohem zapomenutém místì. Už to není takové jako za mých mladých let. Ne kamaráde.}
{109}{}{Jo, staré dobré èasy. Vzpomínám si, že jsme tenkrát...}
{110}{}{Sejnì to nemohlo být nedávno, to je jisté. Tak... co jsme podnikli spoleènì?}
{111}{}{Nevzpomínám si na tebe, ty jo? No, zdá se, že jsi trochu mladší než jsem si pùvodnì myslel.}
{112}{}{Co se mi snažíš øíct?}
{113}{}{Vypadáš jako jeden mùj starý známý... i když. Ach, moje oèi už nejsou to co bývaly. Nu, hezký den ti pøeju.}
{114}{}{Jo... sbohem.}
{115}{}{Jo, urèitì jsme udìlali Vùdci ze života peklo, nebo ne? Když jsi odešel tak se ten srágora rozpadl. Musel jsem se pøestìhovat a zmìnit si jméno. A kde jsi skonèil ty?}
{116}{}{Užíval jsem si života v jedné malé vesnièce.}
{117}{}{No, je lepší být opatrný než mrtvý. Nic není tak jako døív. Nejlepší by bylo mít ještì jeden pár oèí vzadu. Kryj si záda.}
{118}{}{Dobøe, díky.}
{119}{}{Jo, chvíli jsem hledal tvùj Vault, ale nikdy jsem ho nenašel. Iane vyprávìj, starému pøíteli, nìjaké staré dobré pøíbìhy.}
{120}{}{Iane?}
{121}{}{Jo, Ian. Nepamatuješ jsi mì? Už je to pár let. Pøece si nemyslíš, že bych mohl zapomenout na svého nejlepšího kámoše. Škoda, že už to nejde vrátit nazpìt.}
{122}{}{Promiò, ale ty si asi myslíš, že já jsem Zakladatel. Moje vesnice byla založena nìkým kdo pøišel z Vaultu.}
{123}{}{No, tak teï to dává trochu vìtší smysl. Pìknì se poslouchá, že se mému pøíteli dobøe vedlo. Dobøe, starý Ian mi dal nìjaké rady a já ti je prozradím. Tam venku buï opatrný. Tohle místo není tak dobré jak se mùže zdát.}
{124}{}{O co tady jde?}
{125}{}{Dobøe, Obèané Vaultu si hodnì myslí a zakládají na své rase... a lidi jako ty a já je moc nezajímají. Vezmi si tuto zbraò. Ochrání tì jestliže se ti vìci malinko vymknou z rukou. Pravdìpodobnì by tì nemìli vidìt mluvit se starým šílencem. Nejlepší bude, pùjdeš li svou cestou.}
{126}{}{Díky ti za tvou pomoc.}
{127}{}{Nech starého muže odpoèívat.}
{128}{}{Jak nenucený...}
{129}{}{Nech mì o samotì.}
{130}{}{Bude lepší když pùjdeš.}
{131}{}{Budou tì podezøívat, jestliže si budeme nadále povídat.}
{132}{}{Bìž, už. Jsem na tebe hrdý.}
