#tento soubor prelozil Jarda "PIZDUCH" Skarda
{100}{}{Vidíš Randala, šéfa obchodního centra.}
{101}{}{Vidíš chlapíka ve støedních letech s øídkımi èernımi vlasy.}
{102}{}{Vidíš Randala, šéfa obchodního.}
{103}{}{Vidíš chlapíka ve støedních letech s øídkımi èernımi vlasy.}
{104}{}{Gratuluji, }
{105}{}{To byl nápad napadnout je a znièit. Znièit ty hlupáky, v jejich brlohu!}
{106}{}{Slyšel jsem, e jsi dole na jihu nakopal do zadku nìjakı vıznamnı špehy. To je zpùsob jak pøeít.}
{107}{}{Vetøelec! Stráe! Stráe!}
{108}{}{Có?! Mutant! Stráe!}
{109}{}{Có? Ghoul! Stráe!}
{110}{}{Dobrı den, Kapitáne.}
{111}{}{Vault City vydrí, Kapitáne.}
{112}{}{Dobrı den, Obèane.}
{113}{}{Vault City vydrí, Obèane.}
{114}{}{Musím poslat rozdìlovník do podøízenıch koloniálù A a B...}
{115}{}{Musím sestavit nejnovìjší soupisy majetku a zadat je do poèítaèe...}
{116}{}{Schází mi DOS. S tímto novım operaèním systémem je zadávání dat sloitìjší.}
{117}{}{Paní starostka stále potøebuje tyto vıpisy...}
{118}{}{Promiò, máme zavøeno, protoe je veèer. Vra se zpìt ráno.}
{119}{}{Máme zavøeno. Jen posbírám tady ty papíry a pùjdu domù.}
{120}{}{Vítej, cizinèe. Je pøíjemné vidìt novou tváø. Jmenuji se Randal... Jsem šéf obchodního centra. Potøebuješ nìco?}
{121}{}{Geck}
{122}{}{Neee}
{123}{}{Vypadni}
{124}{}{Dobøe, Jak se to vezme. Co je to za místnost?}
{125}{}{Dnes nic, skuteènì.}
{126}{}{GECK? To je souprava pro vytvoøení zahrady ráje, jakısi šedivı kuføík, e jo? Nikoho jsem neslyšel zmínit se o nìm... dobøe, no... u skoro vìky.}
{127}{}{Potøebuju Gechkkk}
{128}{}{Vypadni}
{129}{}{Nemáte jeden?}
{130}{}{Nebude vadit, kdy se zeptám na nìco jiného?}
{131}{}{No, nevadí.}
{132}{}{Nerad tì zklamu, pøíteli, ale my u ádnı nemáme. Byl pouit k vytvoøení Vault City...*ufff.* Všechen je pryè.}
{133}{}{Potøebuju Gechkkk.}
{134}{}{Vypadni}
{135}{}{Oh...dobøe, znáš nìjaké místo, kde by mohli mít ještì jeden?}
{136}{}{Nebude vadit, kdy se zeptám na nìco jiného?}
{137}{}{No, nevadí.}
{138}{}{Dobøe, hmmm. Jak to vidím já, tak tvùj problém je: GECK byly staré kusy techniky... ve skuteènosti u pøedváleèné. Nemùeš je u nikde "najít." Byly umístìny do Vaultù.}
{139}{}{Potøebuju Valt.}
{140}{}{Vypadni}
{141}{}{Víš kde bych našel ostatní Vaulty?}
{142}{}{Nebude vadit, kdy se zeptám na nìco jiného?}
{143}{}{No, nevadí.}
{144}{}{Mìl bys prozkoumat databázi centrálního poèítaèe, uvidíš, jestli získáš nìjaké souøadnice ostatních Vaultù. Osobnì tomu nevìøím, ale za pokus to stojí.}
{145}{}{No, kdybys mìl pøístup k našemu centrálnímu poèítaèi, mohl bys získat nìjaké zmínky o ostatních Vaultech. Ale pouze obèané mìsta mohou vstoupit do Vaultu.}
{146}{}{Díky}
{147}{}{Nebude vadit, kdy se zeptám na nìco jiného?}
{148}{}{Díky za informace.}
{149}{}{Hej, vítej nazpìt. Mùu pro tebe nìco udìlat?}
{150}{}{Jistì. Na co myslíš?}
{151}{}{Gechkk?}
{152}{}{Vypadni}
{153}{}{Co je to za místo?}
{154}{}{Náhodou nemáte na skladì GECK?}
{155}{}{Valerie by mìla pouít na údrbu pøístøeší novı hasák a nìjaké kleštì.}
{156}{}{Èlen rady McClure øekl, e bys mìl mít... uf, jakousi hydro-magneto-vìcièku, kterou bych mìl dostat pro elektrárnu v Gecku.}
{157}{}{Èlen rady McClure øekl, e bys mìl mít hydroelektrickı regulátor magnetickıho pole na skladì a e bych ho mìl dostat.}
{158}{}{Starostka mì poslala sem, abych se pøihlásil o odmìnu.}
{159}{}{Dnes ne, skuteènì.}
{160}{}{Toto je obchodní centrum. Máme standardní zboí... základní ivotní potøeby, nìjaké knihy, pøíruèky "Jak na to..", nìjaké nástroje, stimpaky, lékaøské potøeby, to a ono.}
{161}{}{Zní to dobøe. Mohu vidìt co máte na skladì?}
{162}{}{Máte GECK?}
{163}{}{Valerie by mìla pouít na údrbu pøístøeší novı hasák a nìjaké kleštì.}
{164}{}{Èlen rady McClure øekl, e bys mìl mít... uf, hydro-magneto-vìcièku, kterou bych mìl dostat pro elektrárnu v Gecku.}
{165}{}{Èlen rady McClure øekl, e bys mìl mít hydroelektrickı regulátor magnetickıho pole na skladì a e bych ho mìl dostat.}
{166}{}{Starostka mì poslala sem, abych se pøihlásil o odmìnu.}
{167}{}{Nebude vadit, kdy se zeptám na nìco jiného?}
{168}{}{Moná se vrátím pozdìji.}
{169}{}{Dobøe, promiò, e tì pøerušuju, ale jsem oprávnìnı uzavírat obchod jen s Obèany. Bez uráky, ale je to zákon, chápeš. Mùeš zkusit obchod Happy Harryho venku na pøedmìstí.}
{170}{}{Dobøe, promiò, e tì pøerušuju, ale jsem oprávnìnı uzavírat obchod jen s Obèany. Bez uráky, ale je to zákon, chápeš. Mùeš zkusit obchod Happy Harryho venku na pøedmìstí.}
{171}{}{Jak se mohu stát Obèanem?}
{172}{}{Ale... uf, já jsem Obèan. Nepamatuješ se na mì?}
{173}{}{Podívej, moje peníze jsou právì tak dobré jako od Obèanù.}
{174}{}{Èlen rady McClure øekl, e bys mìl mít hydroelektrickı regulátor magnetickıho pole na skladì a e bych ho mìl dostat.}
{175}{}{Starostka mì poslala sem, abych se pøihlásil o odmìnu.}
{176}{}{Nebude vadit, kdy se zeptám na nìco jiného?}
{177}{}{Vıbornì. Nashle.}
{178}{}{Mùeš zkusit test obèanství. Proconsul Gregory ho dává kadımu cizinci, kterı se chce stát Obèanem. Pravdìpodobnì bys mìl nejdøív pohovoøit se starostkou Lynett. Ona øídí bìh okolního svìta.}
{179}{}{Dobøe. Kde jí najdu?}
{180}{}{Uvidím. Nebude vadit, kdy se zeptám na nìco jiného?}
{181}{}{Díky za informaci. Podívám se po ní.}
{182}{}{Je na radnici... a vyjdeš z budovy, dej se doprava a pak stále rovnì kolem parku. Je to co bys dohodil kamenem...}
{183}{}{Uvidím. Nebude vadit, kdy se zeptám na nìco jiného?}
{184}{}{Díky za informaci. Podívám se po ní.}
{185}{}{Skuteènì? Nemùu øíct, e si tì pamatuju. Máš nìjaké doklady? Mùeme to vyjasnit.}
{186}{}{Ne, nemám je tady u sebe.}
{187}{}{Ano. Tady jsou.}
{188}{}{Nevadí. Popovídáme si pozdìji.}
{189}{}{Dobøe, projeï je skrz snímaè, a my provìøíme vše vıš. Bude to trvat jen chvilku.}
{190}{}{Có?! Coe! Vra mi doklady!}
{191}{}{Uh... skuteènì, Právì teï nemám èas cokoliv nakupovat. Vra mi zpìt moje doklady a já pùjdu svou cestou.}
{192}{}{Dobøe. Jsem si jist, e je všechno v poøádku.}
{193}{}{Dobøe... uf, dobøe.}
{194}{}{Nebude vadit, kdy se zeptám na nìco jiného?}
{195}{}{Uvidíme se pozdìji}
{196}{}{Vše je provìøeno. Tady jsou tvoje doklady. Co pro tebe mohu udìlat?}
{197}{}{Ukate mi co máte na skladì.}
{198}{}{Vlastnì, nebude vadit pokud se místo toho zeptám na nìjaké otázky?}
{199}{}{Dnes vlastnì nic.}
{200}{}{Tak... ty jsi Obèan }
{201}{}{Jo, øekl, e se zastavíš... }
{202}{}{Dobøe.}
{203}{}{Vlastnì, nevadí, vrátím se pro to pozdìji.}
{204}{}{Dobøe, tady jsi. Jeden Hy-Mag. Vypadá to jako árovka, e jo? Ó, neupus to... je to hodnì køehké.}
{205}{}{Øekni, co jiného máte ještì na skladì?}
{206}{}{Nebude vadit, kdy se zeptám na nìco jiného?}
{207}{}{Díky. Mùu do toho civìt nìkolik hodin pøedtím, ne to odnesu do elektrárny v Gecku.}
{208}{}{Mám to. Díky za èást.}
{209}{}{Jo, starostka øíkala, e se zastavíte... Kapitáne. (Zamrkání.) Musím øíct, Kapitáne, PÌKNÌ sis poèkal.}
{210}{}{Jo, starostka øíkala, e se zastavíte. No, musím øíct, pøíteli, PÌKNÌ sis poèkal.}
{211}{}{Co je to?}
{212}{}{Vlastnì, schovej to pro mì. Vyzvednu si to pozdìji.}
{213}{}{Nic míò ne Heckler&Koch G11, jedna z nejlepších útoènıch zbraní, která byla kdy vyrobena...(vezme zbraò, podá ti ji)...náboje 4.7 mm, 50rannı zásobník. Kdy zpívá, lidi poslouchají.}
{214}{}{To je tip. Díky.}
{215}{}{ádnı problém. A tady... máš ode mì pár granátù. Ber to jako podìkování za likvidaci banditù.}
{216}{}{Vıbornì. Mohu se podívat, co máš na skladì?}
{217}{}{Mohu se zeptat ještì na nìco jiného?}
{218}{}{Díky. Budu je pouívat jen pro dobré vìci.}
{219}{}{Tak co dál s tebou?}
{220}{}{Nebude vadit, kdy se zeptám na nìco jiného?}
{221}{}{Jo, to bude pro dnes.}
{222}{}{Jo, vím. Stále èekám na písemnı seznam abych vyèistil sklad, ale u to chvíli trvá. Nevím co si o tom mám myslet. Trvá to dlouho.}
{223}{}{Uvidím. Nebude vadit, kdy se zeptám na nìco jiného?}
{224}{}{Pak moná pùjdu najít ty nástroje nìkam jinam.}
{225}{}{!}
{226}{}{, có? Poèkej chvíli a dám ti ten hydroelektrickı Magneto...uh, Hy-Mag.}
{227}{}{, v poøádku? Poèkej chvíli a dám ti to hydroelektrickı Magneto...uh, Hy-Mag.}
{228}{}{Díky.}
{229}{}{[pokraèování]}
