#tento soubor prelozil Jarda "PIZDUCH" Skarda
{100}{}{Vidíš pomocníka Wallace, Skeeva.}
{101}{}{Vidíš šlachovitého mladíka. Jeho pohled poskakuje z místa na místo.}
{102}{}{Vidíš pomocníka Wallace, Skeeva.}
{103}{}{Vidíš šlachovitého mladíka. Jeho pohled poskakuje z místa na místo.}
{104}{}{Hej, nedostali jste ádné Horrigany? Mùu je prodat po padesáti, sto samcù k odstøelu, dám ti 10% po akci.}
{105}{}{Ztra se.}
{106}{}{Vypadni. Nemám ti co øíct.}
{107}{}{Oh, uh, hej, Kapitáne. Hezkı den, co?}
{108}{}{Dobøe, jestlie to není novı Obèan.}
{109}{}{Hej tady, "Obèane."}
{110}{}{Nemùeš sem pøivést mutanty.}
{111}{}{Nemùeš sem pøivést ghouly.}
{112}{}{Zavíráme, blíí se noc. Vra se sem ráno.}
{113}{}{Podívej, vydìdìnèe, jestlie máš nìco k proclení, Wallace se vrátí, jasnı? Pøipraví ti všechny formuláøe, které budeš potøebovat.}
{114}{}{Formuláøe potøebuji?}
{115}{}{Vypadni!}
{116}{}{Uh... co je to za místo?}
{117}{}{Dobøe. Díky.}
{118}{}{Toto je CELNÍ úøad. Jak øíká cedule pøed dveømi. Jestlie nemáš nic k proclení, co tady vlastnì dìláš?}
{119}{}{Hledám Vault.}
{120}{}{Rád bych se podíval do mìsta.}
{121}{}{Vzhledem k tomu, e jsi celník, se divím, e nemáš ádnou "radu" jak pøinést do mìsta jistı druh zboí.}
{122}{}{Nic. Promiò e obtìuju.}
{123}{}{Vault? Je ve mìstì. Proè? Chceš se podívat za bránu?}
{124}{}{Ano.}
{125}{}{Ne, jen se procházím. Díky.}
{126}{}{Dobøe, mohl bys jít za mım šéfem, Wallacem, a ZKUSIT dostat povolení ke vstupu, ale je to zbyteèná ztráta èasu. Nikdy nikoho nenechal vejít dovnitø. Jistì, jsou ještì jiné zpùsoby...}
{127}{}{Jaké jiné zpùsoby?}
{128}{}{Díky. Pùjdu za Wallacem.}
{129}{}{Rada? No, rada je drahá, vydìdìnèe. Máš nìjaké peníze?}
{130}{}{Dát mu $50.}
{131}{}{Dát mu $75.}
{132}{}{Dát mu $100.}
{133}{}{Pravdìpodobnì ne tolik, aby tì to zajímalo. Vrátím se zpátky a budu mít víc.}
{134}{}{Nevadí. Moná si pohovoøíme pozdìji.}
{135}{}{Dobøe, je nìkolik vìcí co mùeš udìlat. Jedna je stát se Obèanem mìsta. Nikdy nehledají Obèany. Samozøejmì, šance stát se obèanem je skoro nulová, ale není to nemoné.}
{136}{}{Proè?}
{137}{}{Co jiného mùu dìlat?}
{138}{}{Nevadí. Moná si popovídáme nìkdy jindy.}
{139}{}{Jestlie jsi se nenarodil jako Obèan, pak musíš pøijmout test, aby ses stal Obèanem. Poèet vydìdìncù, kteøí udìlali test a stali se Obèany? Nula. Tvé šance? MÍÒ nì nula.}
{140}{}{Jakı je to test?}
{141}{}{Jak ještì mùu obejít celnici?}
{142}{}{Nevadí. Moná si pohovoøíme pozdìji.}
{143}{}{Gregory, Prokonzul, dá "test" jakımukoliv vydìdìnci, kterı se chce stát Obèanem. Zmìøí tak jejich inteligenci a postøeh, a musíš mít zatracenou kliku, abys to udìlal. Vìtšina Obèanù by s tím mìla potíe.}
{144}{}{Tak proè je to tak tìkı?}
{145}{}{Jak ještì mùu obejít celnici, ne se stanu Obèanem?}
{146}{}{Nevadí. Moná si pohovoøíme pozdìji.}
{147}{}{Jeliko vìtšina vydìdìncù neumí èíst, neví nic o trigonometrii, nebo neumí vyhláskovat "Australopithecus"... sleduješ mì. Je to jen zpùsob jak zabránit vydìdìncùm, aby se nestali Obèany.}
{148}{}{Jak ještì mùu obejít celnici, ne se stanu Obèanem?}
{149}{}{Nevadí. Moná si pohovoøíme pozdìji.}
{150}{}{Mùeš schovat zboí u svıch otrokù... svého "sluebnictva". Vidíš, zpùsob myšlení ve Vault City je takovı, e jim pøipadá nepochopitelné nechat nést sluebnictvo nìco dùleitého... nebo problematického.}
{151}{}{Nìjaká jiná monost?}
{152}{}{Pak tedy dobøe. Díky.}
{153}{}{No, mùeš se stát Obèanem... neoficiálnì.}
{154}{}{O èem jste to mluvil?}
{155}{}{Nevadí. Moná si pohovoøíme pozdìji.}
{156}{}{Jestlie máš peníze, øeknu ti detaily. Jinak...}
{157}{}{Mám peníze. Kolik to bude stát?}
{158}{}{Nevadí. Moná si pohovoøíme pozdìji.}
{159}{}{$200 a papíry jsou tvoje.}
{160}{}{Za dvì stì dolarù, z tebe mohu udìlat plnohodnotného Obèana. Budeš mít volnı prùchod skrz bránu, ádnı potíe. Mohu vytisknout doklady, registrovat sériové èíslo a jít svou cestou mùeš za pìt minut.}
{161}{}{Co jestlie nìkomu øeknu, e padìláváš doklady Obèanù?}
{162}{}{Zní to dobøe. Tady je $200.}
{163}{}{No, dvì stì je pomìrnì pøemrštìná cena. Mám u sebe pouze $150.}
{164}{}{Nemám u sebe tak velkou èástku v hotovosti. Moná nìkdy jindy.}
{165}{}{Ne díky. Moná nìkdy jindy.}
{166}{}{Jednoduché. Nebudou ti vìøit. Jsi vydìdìnec a já jsem Obèan. Hádej komu budou vìøit.}
{167}{}{Koupím tedy doklady o obèanství.}
{168}{}{Koupím doklady o obèanství... ale za $150, ne za $200.}
{169}{}{Dobøe, $200 je pro mì docela dost. Vrátím se a seenu více penìz.}
{170}{}{Nevadí. Moná si pohovoøíme pozdìji.}
{171}{}{Hmmm. No, dobøe... Cítím se dnes jako velkı dobrotivec, ale nevyprávìj nikomu z ostatních vydìdìncù, e jsi je získal tak lacino.}
{172}{}{Dobøe.}
{173}{}{Tak dej mi ty prokletı papíry.}
{174}{}{Dobøe, vytištìní je hotovo. Tady jsou..."Obèane." A neøíkej nikomu o tom, zvláštì Wallacovi, je to jasné?}
{175}{}{ádnı problém. Nikdy bych nepomyslel takovou vìc provést poctivımu Obèanu jako jsi ty, zvláštì, kdy mám dùkaz o tvé nezákonné èinnosti uschovám ve své kapse.}
{176}{}{Nestarej se. ádnı problém.}
{177}{}{Co e...?! Nikdo ti nebude vìøit, vydìdìnèe! Bude to moje slovo proti tvému!}
{178}{}{Obvykle by bylo, ale tyto dokumenty mluví za mì proti tobì. A tak dlouho budou mluvit dokud nezaplatíš za jejich mlèenlivost.}
{179}{}{Ovšem budou. Zatím se mìj.}
{180}{}{Já... ty špinavej...}
{181}{}{Pozor... na jazyk pøede mnou.}
{182}{}{Sladké øeèi ti moc nepomùou, Skeeve.}
{183}{}{Dobøe, mám malou hotovost uschovanou stranou. Tady. Vezmi si to... tøi sta dolarù.
 Tak, budete u mlèet?}
{184}{}{Pokud vím. Zatím se mìj.}
{185}{}{ádnı problém. Máš moje mlèení.}
{186}{}{Dvì stì nebo nic, vydìdìnèe. Existuje pouze tento zpùsob jak se dostat skrz bránu.}
{187}{}{Myslím, e zkusím oficiální cestu.}
{188}{}{Ne dìkuji.}
{189}{}{Ha ha! Hodnì štìstí, cizinèe. Jedinı zpùsob jak získat denní propustku od Wallace je vlézt mu do prdele, mrtvı práskaèi.}
{190}{}{Tak jako tak to zkusím.}
{191}{}{Jestlie je to zpùsob, co zabere...}
{192}{}{Zváil jsi to?}
{193}{}{Jsi zpátky. Co chceš?}
{194}{}{Chci? Chci!}
{195}{}{Vypadni}
{196}{}{Co je to za místo?}
{197}{}{Rád bych se dostal dovnitø do mìsta.}
{198}{}{Rád bych koupil falešné doklady o Obèanství jak jsi mi je nedávno nabízel.}
{199}{}{Rozhodl jsem ti vrátit nazpìt ty falešné doklady o Obèanství.}
{200}{}{Vzhledem k tomu, e jsi celník, se divím, e nemáš ádnou "radu" jak pøinést do mìsta jistı druh zboí..}
{201}{}{Nevadí.}
{202}{}{Podívej, hlupáku, vypadni odsud nebo zavolám stráe.}
{203}{}{Podívej, hlupáku, vypad-- Mmmm. Poèkej chvíli. Moná...}
{204}{}{Hurnh?}
{205}{}{Odprejskni}
{206}{}{Pojï se mnou podøadnı hlupáku. Mám tu nìkoho, kdo se s tebou chce seznámit.}
{207}{}{Okej-koukej}
{208}{}{Nuh-uh zùstaò}
{209}{}{Našel jsem tohodle potulnıho cizince v pustinì, Barkusi. Vypadá jako dobrı materiál na otroka.}
{210}{}{Našel jsem tuto potulnou skupinu cizincù v pustinì, Barkusi. Tenhle vypadá jako dobrı materiál na otroka.}
{211}{}{2 vteøiny}
{212}{}{Musíš se mılit. Je oèividnì zaostalı.}
{213}{}{1 vteøina, neber Barkusovi nadìji.}
{214}{}{Za-o-stalı!}
{215}{}{2 vteøiny}
{216}{}{Pojï. Potøebuješ nìkoho na práci ve Vaultu, nemám pravdu?}
{217}{}{1 vteøina, neber Barkusovi nadìji.}
{218}{}{Vault! Geckk!}
{219}{}{2 vteøiny}
{220}{}{Dobøe...hmmm. Pøedpokládám, e èekáš na nálezné?}
{221}{}{2 vteøiny}
{222}{}{Jí snad cizinci své vlastní vıkaly? Samozøejmì, e chci nálezné.}
{223}{}{1 vteøina, Neber Skeevovi nadìji}
{224}{}{Feeee? Peeeeeeee!}
{225}{}{1 vteøina}
{226}{}{Velmi dobøe. Pak ho tedy pošlu do Vaultu. Moná mùe vyèistit sklady.}
{227}{}{Ouha. Jak jsi uprchl?}
{228}{}{Ouha. Jak jsi uprchl? Bude lepší se vrátit zpìt pøed tím ne Barkus zešílí. Jdeme...}
{229}{}{Oh-keeee}
{230}{}{Odprejskni}
{231}{}{Jak jsem u øekl, mohu z tebe udìlat plnohodnotného Obèana za $200. Budeš mít volnı prùchod skrz bránu, ádnı potíe. Mohu vytisknout doklady, registrovat sériové èíslo a jít svou cestou mùeš za pìt minut.}
{232}{}{Co musím udìlat, abych se stal skuteènım Obèanem?}
{233}{}{A co kdy já...? Pùjdu jim hned øíct, e prodáváš falešné doklady o Obèanství.}
{234}{}{Urèitì doufám. Umím bıt pìknì pøesvìdèivı.}
{235}{}{Zaøídíme to.}
{236}{}{Ha ha! Chtìl bych vidìt jak to budeš zkoušet. Wallace ti nikdy neuvìøí.}
{237}{}{Oh, Myslím si, e uvìøí jakmile uvidí falešné doklady, které jsi mi dal. Jestlie náhodou máš nìjaké drobné, mùe to bıt naše malé tajemství.}
{238}{}{Postaráme se.}
{239}{}{Vezmu si tedy doklady o obèanství.}
{240}{}{No, $200 je pro mì docela dost. Vrátím se jakmile seenu nìjaké peníze.}
{241}{}{Ne, dìkuji. Moná nìkdy jindy.}
{242}{}{Co musím udìlat, abych se stal skuteènım Obèanem?}
{243}{}{Hmmmm. Znovu, kolik za dokumenty o Obèanství?}
{244}{}{Jestlie pro nìj budu muset slídit, udìlám to.}
{245}{}{Jak jsi se stal skuteènım obèanem?}
{246}{}{Nic, nevadí.}
{247}{}{Ne, díky. Moná se vrátím pozdìji.}
{248}{}{Jestlie jsi se nenarodil jako Obèan, pak musíš pøijmout test, aby ses stal Obèanem. Poèet vydìdìncù, kteøí udìlali test a stali se Obèany? Nula. Tvé šance? MÍÒ nì nula.}
{249}{}{Co je to za test?}
{250}{}{Vidím. Znovu, kolik za ty dokumenty?}
{251}{}{Nevadí. Moná se zastavím pozdìji a pak si popovídáme.}
{252}{}{Gregory, prokonzul, dá "test" jakımukoliv vydìdìnci, kterı se chce stát Obèanem. Zmìøí tak jejich inteligenci a postøeh, a musíš mít zatracenou kliku, abys to udìlal. Vìtšina Obèanù by s tím mìla potíe.}
{253}{}{Tak proè je to tak tìkı?}
{254}{}{Vidím. Znovu, kolik za ty dokumenty?}
{255}{}{Hmmmm. Moná se vrátím pozdìji.}
{256}{}{Jeliko vìtšina vydìdìncù neumí èíst, neví nic o trigonometrii, nebo neumí vyhláskovat "Australopithecus"... sleduješ mì. Je to jen zpùsob, jak zabránit vydìdìncùm, aby se nestali Obèany.}
{257}{}{Vidím. Znovu, kolik za ty dokumenty?}
{258}{}{Hmmm. Moná se zastavím pozdìji a pak si popovídáme.}
