#tento soubor prelozil Jarda "PIZDUCH" Skarda
{100}{}{Vidíš Wallace.}
{101}{}{Vidíš hubeného chlapíka s uhrovitou tváøí. Je obleèen v naehlené uniformì Vaultu.}
{102}{}{Vidíš Wallace, celníka Vault City.}
{103}{}{Vidíš hubeného chlapíka s uhrovitou tváøí. Je obleèen v naehlené uniformì Vaultu.}
{104}{}{Slyšeli jsme o tvıch hrdinskıch èinech. Podle rozkazu Senátu, jsi ty... i kterıkoliv z tvıch spoleèníkù... kdykoliv vítanımi hosty v našem Vault City.}
{105}{}{Celnice je u zavøená. Vrate se ráno.}
{106}{}{Celnice je u zavøená. A a vyplním všechny tyhle seznamy, jdu okamitì domù.}
{107}{}{Nebudu se bavit s nìkım, kdo cestuje s... ghouly. Ti patøí na pøedmìstí.}
{108}{}{Nebudu se bavit s nìkım, kdo cestuje s... mutanty. Ti patøí na pøedmìstí.}
{109}{}{Buï zdráv Kapitáne. Je tu nìco s èím bych mohl pomoci?}
{110}{}{Zdravíèko Obèane. Je zde nìco s èím bych mohl pomoci?}
{111}{}{Buï zdráv poutníku. Vítej ve Vault City. Potøebuješ s nìèím poradit?}
{112}{}{Frazz-urb-luuw!}
{113}{}{Vypadni odsud.}
{114}{}{Kdo jsi?}
{115}{}{Co je to za místo ?}
{116}{}{Myslí, e tvùj asistent Skeev je zapleten do ilegální èinnosti.}
{117}{}{Dnes ne, díky.}
{118}{}{No, jak vidím budu si muset opravdu vánì popovídat se stráemi na pøedmìstí. Oni si snad vánì myslí, e v dnešní sloité dobì mohou nechat projít KADÉHO venkovana do Vault City!}
{119}{}{Dej. Dej? Daisy.}
{120}{}{Vypadni odsud.}
{121}{}{Idiote.}
{122}{}{"Daisy," øíkáš? Úasné. Fascinující! Proè se nevrátíš zpìt na pøedmìstí a nedovyprávíš svım rodnım vydìdìncùm zbytek této historky?}
{123}{}{Anoo!}
{124}{}{Vlastnì, jak o tom tak pøemıšlím, bude lepší, kdy tu zanecháš své zbranì a svojí vıstroj. Jen pro bezpeènost Vault City.}
{125}{}{Uh-kuh}
{126}{}{Lepší bude zaèít brnìním a co.. co.. co to máš na sobì pod svojí zbrojí?}
{127}{}{Hnuh?}
{128}{}{Jak--? Jake... ty nosíš originální uniformu vaultu!}
{129}{}{Javor.. jasan.. Jasnì. Uniforòa z Valt Sytı teplá jako mamièka.}
{130}{}{Ano nosím a to bys nevìøil, èím jsem musel projít abych tuhle zatracenou vìc získal --}
{131}{}{Na. Tady si vezmi jednodenní propustku do mìsta a zajdi si pohovoøit s naší starostkou mìsta. Jsem si jist e, se budete mít o èem bavit.}
{132}{}{Uh-kuh.}
{133}{}{Díky. Myslím si, e se jí potøebuju na pár vìcí zeptat.}
{134}{}{Ty, co vlastnì chceš?}
{135}{}{Mìstoo? Já mám jít do mìsta?}
{136}{}{Hewooo?}
{137}{}{Vypadni odsud.}
{138}{}{Chci se vrátit zpátky do mìsta.}
{139}{}{Chci se zeptat na pár otázek...}
{140}{}{Zapomeò na to.}
{141}{}{Ty jeden blázne, pøestaò mì otravovat.}
{142}{}{Nejsem blázon. Ty si blázon.}
{143}{}{Vypadni odsud.}
{144}{}{Podívej, moná bychom mohli nìco vymyslet...?}
{145}{}{Uf, pak tedy nashledanou.}
{146}{}{Soud rozhodl o tvém vyhoštìní z Vault City cizinèe. ádnou druhou šance nemáš.}
{147}{}{Druhou? Co se stalo s tou první šancí?}
{148}{}{CHCI JÍT DOVNITØ. HNED.}
{149}{}{Plosím?}
{150}{}{Vypadni odsud.}
{151}{}{Podívej, to všechno bylo jedno velké nedorozumìní.}
{152}{}{Hele, já u jí nemám. Mùu dostat ještì jednu?}
{153}{}{Tak na to zapomeò.}
{154}{}{Zapomeò na to.}
{155}{}{To by šlo, ale za kadou další propustku den je poplatek $50.}
{156}{}{Dobøe. Tady jsou ty prachy.}
{157}{}{Nevadí. Nepotøebuji to tak nutnì.}
{158}{}{Tak se na to vzatím vykašleme. Vrátím se jakmile seenu nìjakı peníze.}
{159}{}{Tak tady to máš. PROSÍM pokus se dodret dobu pobytu. Nemohu sledovat délku pobytu všech lidí, kteøí vstoupili do mìsta.}
{160}{}{Mùu se zeptat na nìkolik otázek?}
{161}{}{Rozumím. Díky.}
{162}{}{Jmenuji se Wallace. Jsem vrchní celník Vault City. Vycházím vstøíc tìm, kteøí chtìjí provozovat svojí ivnost v našem bájeèném mìstì.}
{163}{}{Chci vstoupit do mìsta.}
{164}{}{Øíkáte e vycházíte vstøíc? Co tím myslíte?}
{165}{}{Rozuím. Dìkuju za informace.}
{166}{}{Pokud chceš vstoupit do Vault City, potom musíš mít dobrı dùvod. Pouze Obèané Vaultu mají právo vstupovat do mìsta jak chtìjí. Všichni ostatní musí si musí opatøit denní propustku do mìsta.}
{167}{}{Co to je ta denní propustka?}
{168}{}{Musím si promluvit s vaším vùdcem. Je to velmi dùleité.}
{169}{}{Ale já jsem Obèan. Tady, podívejte se.}
{170}{}{Chápu. Dìkuji za poskytnuté informace.}
{171}{}{Toto je celní úøad mìsta Vault City. Jsme odpovìdní za kontrolu všeho zboí, které je dováeno karavanami a dohlííme na všechen obchod. Všichni obchodníci musí pøed vstupem do mìsta projít celní prohlídkou.}
{172}{}{Chci vstoupit do mìsta.}
{173}{}{Jaké zboí dováíte do mìsta?}
{174}{}{Rozumím. Dìkuji za informaci.}
{175}{}{Ach... jste si jist?}
{176}{}{Kdo? Kdo si myslíte e jste, e obviòuje z nìèeho Obèana mìsta Vault?}
{177}{}{Podívejte, prodal mi tento padìlanı Obèanskı glejt. Tady je.}
{178}{}{Zapomeò na to. Chybièka se vloudila.}
{179}{}{Ti kteøí potøebují jednat pøímo s kupci nebo naší starostkou dostanou denní propustku do mìsta. Pouze ti, kteøí vlastní denní propustku mohou vstoupit do mìsta.}
{180}{}{Vıbornì! Zdá se mi, e právì tebe hledám. Potøebuji mluvit s vaší starostkou. Je to dùleité.}
{181}{}{Mno.. , Potøebuji mluvit s vaší starostkou.}
{182}{}{Kdo je starostkou vašeho mìsta?}
{183}{}{Co pøesnì dìláte?}
{184}{}{Dík za informace. Nashledanou.}
{185}{}{Ale jistì. Kadı si pøeje audienci u naší starostky. Bohuel, má ale èas pouze na záleitosti nejvyššího vıznamu.}
{186}{}{Obávám se, e tvé informace nejsou dostateènì dùleitì, aby tì opravòovaly jí navštívit.}
{187}{}{Je ivotnì dùleité, abych s ní mohl mluvit. Buï si jist, e se jí nezapomenu zmínit o tom jak jsou celníci zdatní. Ale jestli mi nemùete pomoc, pak ....}
{188}{}{Informace, kterou jí chci sdìlit je opravdu zajímavá.}
{189}{}{Kdybych byl tebou, dával bych si pozor na to co øíkám. Øíkám, e jí musím vidìt. Hned.}
{190}{}{Ále nic.}
{191}{}{Tak mluvte. Osobnì hned vyøídím zprávy První obèance.}
{192}{}{Dobøe, neøekl jsem, e vám nepomohu. Já jen.... no .. jakı je úèel vaší návštìvy?}
{193}{}{Hmm... Mám informaci, která... která by mohla pomoci vybudovat sí... hmm, všech existujících Vaultù v celé zemi.}
{194}{}{Nemohu vám to sdìlit, dùstojníku, i kdybych chtìl. Ta informace je urèena pouze pro uši První obèanky. Je ivotnì dùleité, abych s ní mohl mluvit.}
{195}{}{Dobøe... je to opravdu, ale opravdu dùleitá informace. To jsem ještì neøekl jak je to dùleité?}
{196}{}{Øíkáte... sí Vaultù?}
{197}{}{Hmmmm. Dobøe... hmmmm. To je velmi nezvyklé...}
{198}{}{Ano. SÍ... Vaultù. Jak vidíte, málokdo ví, e... Vault City není jedinı Vault, kterı pøeil. Jsou i jiné. Jak øíkám - sí.}
{199}{}{Neotravoval bych vás, dùstojníku, kdyby to nebyla extrémnì urgentní vìc. Jistì se zmíním, jak nápomocen jste mi byl, kdy jsem chtìl mluvit se starostkou.}
{200}{}{Nevadí. Chci se zeptat na pár otázek...}
{201}{}{Zapomeòte na to. Vrátím se jindy.}
{202}{}{Dobøe... tato informace je urèitì dùleitá pro naší starostku. Tady máš denní propustku. Platí pouze pøes den. V noci budeš vyzván k opuštìní mìsta. Obèané mají právo kdykoliv zrušit vstupní vısadu, tak se chovej slušnì.}
{203}{}{Rozumím. Mohu se zeptat ještì na nìjaké vìci?}
{204}{}{Dík.}
{205}{}{Neplıtvej mım èasem, venkovane. Odejdi.}
{206}{}{Doporuèuju ti okamitì vypadnout ne zavolám ochranku.}
{207}{}{Ne heee ty ODEJÍT nebo já praštit tì.}
{208}{}{Vypadni.}
{209}{}{Nikam nepùjdu. Jen si se mnou zkus pohnout. Jsem jako skála.}
{210}{}{V poøádku, tak dobøe.}
{211}{}{A kde, smím-li se zeptat, jsi pøišel k tomu falešnımu Obèanství? Ta sériová èísla dokladù jsou stejná jako ta, která byly odcizeny minulı mìsíc.}
{212}{}{Kdy ti to povím, dáš mi denní propustku?}
{213}{}{Byl to váš pomocník, Skeev. Prodal mi je.}
{214}{}{Nevím o èem mluvíte. Jsem Obèanem mìsta.}
{215}{}{Hmmmm... tak dobøe. Jestlie mi to øekneš, dám ti denní propustku.Tak kde jsi dostal tyhle doklady?}
{216}{}{Byl to váš pomocník, Skeev. Prodal mi je.}
{217}{}{Rozmyslel jsem si to. Nic vám neøeknu.}
{218}{}{Ty jeden degenerovanej balíku. Nejsem z tìch co nìco berou na lehkou váhu! U nikdy nevstoupíš do našeho mìsta! Vypadni, ne zavolám ochranku!}
{219}{}{Tak dìlej, zavolej je. Rád si s nima popovídám. Hned jak tì rozsekám do tlaèenky.}
{220}{}{Odcházím. Pro tentokrát.}
{221}{}{Skeev? To mám za to, e jsem ho mìl jako za vlastního! Ujišuju tì, e za tohle zaplatí.}
{222}{}{Dostanu denní propustku za svojí námahu?}
{223}{}{Jistì. Mohu se ještì na nìco zeptat?}
{224}{}{Nìma problema. Nashle.}
{225}{}{Skeev? Ta nevdìèná veš! Za to se mi bude zodpovídat!}
{226}{}{ádnı problém. Mohu se ještì na nìco zeptat?}
{227}{}{Óóh, Jsem zdìšen. Dík za denní propustku, kamaráde.}
{228}{}{Chápu a.. dìkuji.}
{229}{}{Velmi dobøe, zaslouíš si jí. Tady máš denní propustku. Je to pouze denní vstupenka. V noci budeš vyzván k opuštìní mìsta. Obèané mají právo kdykoliv zrušit vstupní vısadu, tak se chovej slušnì.}
{230}{}{Jasnì. Mohu se ještì na nìco zeptat??}
{231}{}{Rozumím a dìkuji.}
{232}{}{Promiò. Jestlie nemáš urgentní dùvod, nemohou ti pomoci.}
{233}{}{Uh... ale já mám neodkladnı dùvod. Skuteènì.}
{234}{}{Dobøe, pak se tì musím na nìco zeptat...}
{235}{}{Ale já jsem pøímı potomek Zakladatele!}
{236}{}{To je jedno. Nashledanou.}
{237}{}{Proè, Jak jsem starej tak jsem blbej. Mìl bych poznat, e nás jeden z LEPŠÍ rasy, z rodu zakladatelù pøišel poctít svojí návštìvou. Fuj! Neplıtvej mım èasem, venkovane.}
{238}{}{Pust mì dovnitø! A pustíš mì dovnitø hned nebo s tebou ušpiním podlahu.}
{239}{}{V poøádku, odcházím.}
{240}{}{Velmi dobøe. Co chceš vìdìt?}
{241}{}{Buï zdráv Kapitáne. Je zde nìco s èím bych mohl pomoci?}
{242}{}{Zdravíèko Obèane. Je zde nìco s èím bych mohl pomoci?}
{243}{}{Jsi tu zase?! Co tu vlastnì hledáš... ?}
{244}{}{Jistì, Kapitáne. Co jiného chceš vìdìt?}
{245}{}{Jistì, Obèane. Co jiného chceš vìdìt?}
{246}{}{Co jiného chceš vìdìt?}
{247}{}{Frazz-urb-luuw!}
{248}{}{Vypadni.}
{249}{}{Co je to za místo?}
{250}{}{Jakı druh zboí se sem dováí?}
{251}{}{Tvùj pomocník, Skeev, je zapletenı do ilegální èinnosti.}
{252}{}{Mohu dostat další denní propustku?}
{253}{}{Objevil jsem pøíèinu toho, proè je pøeprava nákladù z Reddingu tak pomalá.}
{254}{}{Našel jsem táboøištì banditù.}
{255}{}{Našel jsem táboøištì banditù a srovnal jsem ho se zemí.}
{256}{}{Co mi mùeš øíct o vašem vùdci?}
{257}{}{Dnes nic, díky.}
{258}{}{Dnes nic víc, díky.}
{259}{}{Závisí na tom odkud jsou karavany. Dostáváme náklady z mnoha míst... sluebníkky z Denu, uran z Broken Hills a eleznou rudu z Reddingu.}
{260}{}{Co mi mùeš øíct o Denu?}
{261}{}{Co mi mùeš øíct o Broken Hillsu?}
{262}{}{Co mi mùeš øíct o Reddingu?}
{263}{}{Mùu se ještì na nìco zeptat?}
{264}{}{Chápu. Dík za informace.}
{265}{}{Je to... komunita je na západ odsud. Èasto nakupujeme pomocné sily od jejich kupcù. Je to celkem drsné místo, co jsem se dozvìdìl z vyprávìní.}
{266}{}{Jsem si jist e, ..dodavatel "sluebníkù"... jako jsi ty má mnohem vìtší znalosti o takovém místì ne já.}
{267}{}{Rozkošné místo, skuteènì. Zabijáci, zlodìji... normální ráj vydìdìncù. Místo kde se nìkdo jako ty bude cítit jako blecha v koichu.}
{268}{}{Co mi mùeš øíct o Broken Hills?}
{269}{}{Co mi mùeš øíct o Reddingu?}
{270}{}{Mám ještì jinou otázku. Mohu se zeptat?}
{271}{}{Dík za informace.}
{272}{}{Myslím e se zeptám nìkde jinde. Sbohem.}
{273}{}{*Díík.* Sbohem.}
{274}{}{Broken Hills je hornické mìsto na jihu. Mutanti tam tìí uran a sem ho dopravují karavanami.}
{275}{}{Jsou trochu záludní, ale dost slušní... v kadém pøípadì dost dobøí pro vydìdìnce. Nic ve zlım.}
{276}{}{Ze zvìdavosti, kolik platíte za ten uran?}
{277}{}{Co mi mùeš øíct o Denu?}
{278}{}{Co mi mùeš øíct o Reddingu?}
{279}{}{Jó, ano... poslouchej, ještì bych se na nìco zeptal...}
{280}{}{To je vše. Sbohem.}
{281}{}{Je to hornické mìsto daleko na západì. S karavanami z tohoto mìsta je vìtšinou radost obchodovat, ale v poslední dobì jsou náklady rudy znaènì zpodìné. Trocho nás to znepokojuje,.. jsme na jejich rudì znaènì závislí.}
{282}{}{Vím proè jsou náklady z Reddingu zpodìné.}
{283}{}{Co mi mùeš øíct o Denu?}
{284}{}{Co mi mùeš øíct o Broken Hills?}
{285}{}{Chápu vás. Ještì na nìco bych se rád zeptal...}
{286}{}{Dík za informace. Sbohem.}
{287}{}{Ty to víš? To je senzaèní zpráva! Prosím jdi to hned povìdìt radnímu McClurovi.}
{288}{}{Ty to víš? To je senzaèní zpráva! Nech mì abych ti vystavil denní propustku do mìsta, abys to mohl probrat s radním McClurem. Je to pouze denní vstupenka. V noci budeš vyzván k opuštìní mìsta. Bì u.}
{289}{}{Mohu se ještì na nìco zeptat ne pùjdu?}
{290}{}{Dobøe u jdu.}
{291}{}{Dobøe, pùjdu k nìmu okamitì.}
{292}{}{Zajímavé, e se o tom zmiòuješ. Ceny v poslední dobì hodnì vzrostly... ale není to nic, co bychom si nemohli dovolit. Samozøejmì dostáváme lepší cenu ne Gecko. Ti špinaví bufeáci potøebují uran mnohem víc nì my.}
{293}{}{Co mi mùeš øíct o Denu?}
{294}{}{Co mi mùeš øíct o Reddingu?}
{295}{}{Chápu vás. Ještì na nìco bych se rád zeptal...}
{296}{}{Hmmm. Zajímavé. Dík za informace.}
{297}{}{Naše starostka se jmenuje Joanne Lynette. Udìlala pro naše mìsto mnoho dobrého za tìch deset let, co je hlavou mìsta.}
{298}{}{Jako napøíklad?}
{299}{}{Udruje naše mìsto èisté a neposkvrnìné na rozdíl od okolního svìta. Dokonce pøes tlak NCR pøipojit nás k republice a pøes útoky banditù, udruje naše mìsto silné. Teï navíc ty problémy s Gecko....}
{300}{}{Co je to NCR?}
{301}{}{Kdo jsou ti banditi?}
{302}{}{Jaké máte problémy s Gecko?}
{303}{}{Mohu se zeptat ještì na jiné otázky?}
{304}{}{Je smutné to poslouchat. Moná si to poslechnu nìkdy jindy.}
{305}{}{NCR je "New California Republic." Prohlašují, e se pokusí sjednotit celou Kalifornii pod jednu vládu, ale my jsme prohlédli jejich alostnı trik.}
{306}{}{"Trik?" Vlastní NCR nìjaké zbranì...?}
{307}{}{Trik? Jste si jistí?}
{308}{}{Dokonce jestlie jsou upøímní, proè bychom mìli se dìlit o naše zdroje se zabijáky a zlodìji, kteøí ijí venku za tìmito zdmi? Myslím si, e *ne.*}
{309}{}{Chápu vás. Co jsi pøedtím øíkal o banditech?}
{310}{}{Jaké problémy jsou ve Vault City s Gecko?}
{311}{}{Mohu se zeptat ještì na jiné otázky?}
{312}{}{Je toho trochu víc co potøebuji vìdìt. Sbohem.}
{313}{}{Nedávno jsme vydreli zvláštì prudkı a brutální útok banditù. Byli jsme pod tlakem tak jako nikdy pøed tím. Bál jsem se banditù, vdy nakonec mohlo dojít k poruše naší laserové vìe v opevnìní.}
{314}{}{Nemusíte se tìch banditù u obávat. Vyhubil jsem je jako krysy.}
{315}{}{Mùeš mi øíct nìco víc o tìch banditech?}
{316}{}{Uf, je smutné to poslouchat. Co jste chtìl øíct o NCR?}
{317}{}{Jaké problémy jsou ve Vault City s Gecko?}
{318}{}{To zní jako skuteènı problém. Zlomte vaz.}
{319}{}{Ne moc. Zdá se, e nemùeme najít odkud útoèí. Náš Obèan serant Stark toho ví víc, ale zrovna je v øídícím centru uvnitø mìsta.}
{320}{}{Jestlie vypátrám sídlo banditù, pustíš mì do mìsta?}
{321}{}{Mìl bych ještì nìjaké otázky...}
{322}{}{Pùjdu se podívat co zjistím o tìch banditech.}
{323}{}{Díky za poskytnuté údaje.}
{324}{}{Samozøejmì. Jestlie najdeš základnu banditù, udìlím ti denní propustku.}
{325}{}{Uvidím co budu moci udìlat. Ale nejdøív, mám ještì nìjaké jiné otázky...}
{326}{}{Platí. Nashle.}
{327}{}{Ty to víš? To je senzaèní zpráva! Prosím jdi to hned povìdìt starostce.}
{328}{}{Ty to víš? To je senzaèní zpráva! Nech mì, abych ti vystavil denní propustku do mìsta, abys to mohl probrat se starostkou. Tak tady je.Je to pouze denní vstupenka. V noci budeš vyzván k opuštìní mìsta. A bì u.}
{329}{}{Mohu se ještì na nìco zeptat ne pùjdu?}
{330}{}{Dobøe u na to jdu.}
{331}{}{Díky. Nashledanou.}
{332}{}{Oh, uh, moje zamìstnání není mluvit. O tìchle vìcech si bì pohovoøit s naší První obèankou.}
{333}{}{Cos to øíkal oNCR?}
{334}{}{Cos to øíkal o banditech?}
{335}{}{Uh, dobøe... mohu se zeptat ještì na nìjakou otázku?}
{336}{}{Chápu. Tak, dìkuji za poskytnuté informace.}
{337}{}{GECK? Ten termín mi nic neznamená...a jestlie neznamená nic pro mì, urèitì nebude dùleitı ani pro starostku. Tak proè si pøeješ vidìt starostku? Nebo je za tím nìco jiného?}
{338}{}{Hledám GECK. K záchranì mé vesnice.}
{339}{}{Podívej, nech mì vejít dovnitø a já tì nechám dıchat. }
{340}{}{Nikdy. Moná bude lepší kdy pøijdeš pozdìji.}
{341}{}{Dík za tvou pomoc, venkovane.}
{342}{}{Dobøe, jak jsem slíbil, tak taky udìlám, zde je tvoje vstupenka... ale jakmile porušíš pravidla, vezmu si jí zpìt. Rozumíš?}
{343}{}{Oh, uh... dobøe, jsem obchodník. Zamıšlím obchodovat s ostatními kupci ve vašem mìstì. Mohu nyní dostat denní propustku?}
{344}{}{Ty jsi obchodník? Skuteènì. A co budeš chtít prodávat? Rudu? Nebo nìjaké ty špinavé ještìrèí kùe? }
{345}{}{(Pøelítne pohledem tvé spoleèníky.) Nebo hodláš prodávat sluebníky?}
{346}{}{Ano, Chci prodat ve mìstì nìjaké otroky.}
{347}{}{Mám na prodej nìjaké ty... uh... špinavé kùe geckonù.}
{348}{}{Vlasnì, mám na prodej nìjaké pìkné kùe zlatıch geckonù. }
{349}{}{Prodávám nìjakou zlatou rudu.}
{350}{}{Mám na prodej trochu uranu.}
{351}{}{Zatím nemám na prodej ádnou z uvedenıch vìcí. Ale já se vrátím.}
{352}{}{Vlastnì jsem se pøeøekl. Promiòte, e jsem vás obtìoval.}
{353}{}{Hmmmm. Dobøe, uka co máš. Jakmile zkontroluji tvé zboí, mohu postrèit papírování pro udìlení tvé propustky.}
{354}{}{Dobøe. Áá, vše co mám tady je toto zboí tady. Zbytek nákladu je v... uh, mém pøívìsu. Venku za mìstem. }
{355}{}{Hmmmm. Tak dobøe.}
{356}{}{Dobøe, ten vzorek je dostateènı.}
{357}{}{Tady máš denní propustku pro kupce. Pìt set dolarù. Zabezpeèí ti celodenní obchodní privilegium v rámci zdí Vault City a je platná po dobu pìti let od datumu jejího vydání.}
{358}{}{V poøádku. Vezmu si jí.}
{359}{}{Hmmm... Je to jen malı krùèek dopøedu. Mohu projít.}
{360}{}{Pìt stovek je trochu víc, ne si mùu pro tentokrát dovolit. Moná nìkdy jindy.}
{361}{}{Vıbornì. Tady máš... a ještì jednou, platí pouze bìhem dne - v noci budeš vyzván k opuštìní mìsta. Plus Obèané mají právo kdykoliv zrušit vstupní vısadu, tak se chovej slušnì.}
{362}{}{Rozumím. Dostanu odpovìï ještì na nìjaké otázky?}
{363}{}{Díky.}