#tento soubor prelozil Patrik "GENIE" Lipina
{100}{}{Vidíš nápadnou hromadu kamení.}
{101}{}{Vidíš malou hromádku kamení. Vypadají, jako by tady byly naskládány za nìjakým úèelem}
{102}{}{Prostì hromada kamení.}
{103}{}{Hej! Tady pod tìmi kameny je klíè.}
{104}{}{A nic víc.}
