#tento soubor prelozil Patrik "GENIE" Lipina
{100}{}{Vidíš výukový terminál Vault City.}
{101}{}{Tohleto vypadá jako nìjaký výukový program. Sympatický Pip Boy vidíš po stranì.}
{102}{}{Vidíš výukový poèítaèový systém Vault City.}
{103}{}{Chvíli si pohráváš s poèítaèem, ale chtìlo by to vìdìt trošku více o vìdì. Pak by se s tímhle dalo nìco udìlat.}
{104}{}{Nìjaký èas padl na studium archivù tohoto terminálu.}
{105}{}{Nìjaký èas padl na studium archivù tohoto terminálu, ale nic nového tam není.}
