#tento soubor prelozil Patrik "GENIE" Lipina
{100}{}{Tyto dveøe asi neotevøeš. Zdá se, že jsou ovládány odnìkud jinud.}
{101}{}{Na tìchhle dveøích není žádný konvenèní zámek.}
{102}{}{Vidíš dveøe od výtahu.}
{103}{}{Tyhle dveøe jsou ovládány z jiného místa.}
