#tento soubor prelozil Patrik "GENIE" Lipina
{100}{}{Poèítaèový terminál.}
{101}{}{Je aktivní spoøiè obrazovky.}
{102}{}{Nemùžeš pøeèíst, co je na obrazovce.}
{103}{}{Skynet - Bezpeènostní systémy
                                     Vetøelec - patro 1
                                     Aktivace protiopatøení patro 1
                                Protiopatøení - Konec pøenosu
                        Aktivace Automatického opravného systému}
{104}{}{Skynet - Bezpeènostní systémy
                                   Vetøelec - patro 1
                                         Aktivace protiopatøení patro 1
                              Pokouším se pøevést energii do generátoru silových polí...}
{105}{}{Skynet - Bezpeènostní systémy
                                   Vetøelec - patro 1
                                         Aktivace protiopatøení patro 1}
{106}{}{Ukonèit poplach na patøe 1 - planý poplach}
{107}{}{[Všímáš si klávesy oznaèené nápisem "HELP"]. Zkoušíš ji stisknout.}
{108}{}{Nabourat se do bezpeènostních systémù}
{109}{}{Konec}
{110}{}{Argh! [Klávesnice se lehce zdeformovala pod úderem tvé pìsti...]}
{112}{}{Skynet - Bezpeènostní systémy
                                   Zjištìn vetøelec - vnìjší oblast
                       Aktivován Automatický opravný systém
                         Hlavní dveøe - porucha
                                            Znovuzavedení...
                                                     Jistící mechanismus hlavních dveøí stále na místì
              Návrat do úsporného režimu}
{113}{}{Aktivovat poplach - patro 1}
{114}{}{Spustit diagnostický program.}
{115}{}{Konec}
{116}{}{Aghh! [Klávesnice se lehce zdeformovala pod úderem tvé pìsti...]}
{118}{}{Skynet - Bezpeènostní systémy
                                   Pøístup k tomuto terminálu zamítnut.}
{120}{}{Konec}
{122}{}{Chyba 29
                                                          Nebylo možno navázat spojení se serverem
                 Prosím restartujte}
{124}{}{Konec}
{125}{}{Analýza pøíkazu, prosím èekejte..
                                 Ovìøeno
                                                             Ukonèení poplachu na patøe 1}
{126}{}{[S takovýmhle bezpeènostním systémem není divu, že se vyhodili do vzduchu navzájem]  Konec.}
{127}{}{[Objevilo se menu]
                                                  Pro deaktivaci poplachu stisknìte 1
                               Pro diagnostiku stisknìte 2
                                     Konec - stisknìte 3}
{128}{}{Stisknout 1}
{129}{}{Stisknout 2}
{130}{}{Stisknout 3}
{131}{}{Varování! Pro optimální bìh tohoto programu se doporuèuje ukonèit všechny ostatní úlohy. Pøejete si toto nyní udìlat?}
{132}{}{Ano}
{133}{}{Ne}
{134}{}{Konec}
{135}{}{Ukonèení všech úloh
                                        Ukonèení bezpeènostního programu - patro 1
                   Èas poslední analýzy: 15. Srpen 1990
                       Analyzuji systém...
                                             Odhadovaný èas do konce operace: 99:24:60:60}
{136}{}{[Tak tohle asi hned tak hotové nebude]  Konec.}
{137}{}{Pøístup zamítnut
                                                 Pøístup zamítnut
                                                 Prrosup tamitnut
                                                 Pppppup zammmnut
                                                 Pøístup povolen
                                                 Ukonèení poplašných systémù - patro 1}
{138}{}{Konec}
{139}{}{Neovìøený pøístup
                                            Inicializuji bezpeènostní opatøení pro pøístup
                  Pøístup k tomuto terminálu byl UKONÈEN}
{140}{}{Konec}

{200}{}{Poèítaè v diagnostickém režimu. Prosím vyèkejte, dokud proces neskonèí.}