#tento soubor prelozil Patrik "GENIE" Lipina
{100}{}{Vidíš aktivní poèítaèový terminál.}
{101}{}{Pøi bližším pohledu ti padlo do oka logo "I*tel Inside".}
{102}{}{Nemùžeš pøeèíst, co je na monitoru.}

#NPC is unable to read what is on the monitor
{200}{}{ nemùže pøeèíst, co je na monitoru.}

{103}{}{Hlavní zdroj = Vypnut
                                           Záložní zdroj = Zapnut
                                           Znovuzavedení bezpeènostního programu
                  Upozornìní! - Nedostatek energie - Silová pole na 50%
       Konec zavádìní...
                                                     Skynet - Bezpeènostní kontrola 1
                                 Prosím zadejte heslo:_}
{104}{}{Skynet - Bezpeènostní kontrola 1
                             Prosím zadejte heslo:_}
{105}{}{Tchaikovsky}
{106}{}{Otevøít!}
{107}{}{Sierra}
{108}{}{Armageddon}
{109}{}{Nabourat se do systému}
{110}{}{Nemáš tušení. Opustit.}
{113}{}{Silová pole deaktivována - Patro 1}
{115}{}{Konec}
{117}{}{Pøístup k tomuto terminálu byl ukonèen.}
{119}{}{Konec}
{121}{}{Chyba 29
                                                            Není možno se spojit se serverem
                                Prosím restartujte}
{123}{}{Konec}
{124}{}{Pøístup povolen
                                                 Silová pole Patro 1: deaktivována}
{125}{}{Konec}
{126}{}{Nesprávné heslo
                                                       Pøístup zamítnut
                                                     Prosím zadejte heslo:_}
{127}{}{Tchaikovsky}
{128}{}{Øíkám otvírej!}
{129}{}{Sierra}
{130}{}{Armageddon}
{131}{}{Nabourat se do systému}
{132}{}{Nemáš tušení. Opustit.}
{133}{}{[Po zmáèknutí <Ctrl><Alt><C> program zhavaroval. Doufáš, že i zbytek systému nebude složité dostat.]}
{134}{}{Konec.}
{135}{}{Nabourání do systému - Patro 1
                                  Aktivace bezpeènostního protokolu
                              Pøístup k tomuto terminálu byl ukonèen
                     Konec pøenosu}
{136}{}{Konec.}
{137}{}{Tvoje troufalost a neznalost vyvrcholily spuštìním poplašného systému.}
{138}{}{Tak tady už nic nezmùžeš, program je na tebe moc složitý.}
{139}{}{Konec.}

{300}{}{Zdá se, že poèítaè má jakýsi obranný mechanismus.}
{301}{}{Ztrácíš }
{302}{}{ je zasažen a ztrácí }
{303}{}{ hit bodù.}