#tento soubor prelozil Patrik "GENIE" Lipina
{100}{}{Poèítaèový terminál.}
{101}{}{Spoøiè obrazovky je aktivní}
{103}{}{Skynet - Bezpeènostní systémy
                                  Vetøelec Patro 2
                                                   Aktivuji protiopatøení Patro 2
                                  Protiopatøení: konec pøenosu!
                                  Aktivuji automatický opravný systém}
{104}{}{Skynet - Bezpeènostní systémy
                                  Vetøelec Patro 2
                                                   Aktivuji protiopatøení Patro 2
                                  Pokus o pøesmìrování energie do generátoru silových polí}
{105}{}{Skynet - Bezpeènostní systémy
                                  Vetøelec Patro 2
                                                   Aktivuji protiopatøení Patro 2}
{106}{}{Ukonèit poplach na Patøe 2 - planý poplach}
{107}{}{[Všímáš si tlaèítka nadepsaného HELP]. Stisknout ho.}
{108}{}{Nabourat se do bezpeènostních systémù}
{109}{}{Pokus o vypnutí poplachu.}
{110}{}{Konec.}
{111}{}{Arrrrgh! [V zuøivosti mlátíš do klávesnice...]}
{113}{}{Skynet - Bezpeènostní systémy
                                   Pozor!!! Vetøelec detekován na Patøe 1
                          Scanner sítnice aktivován
                                   Scannování...
                                                    Prohledávám databázi...}
{300}{}{ - ID Potvrzeno}
{301}{}{                     Poslední pøístup: }
{302}{}{Uvolòuji zámek výtahu}

{303}{}{ Plukovník Dixon}
{304}{}{ Generál Clifton}
{305}{}{5. Prosinec, 2120}
{306}{}{ dní.               }

{114}{}{                             Skynet - Bezpeènostní systémy
                                 Pozor!!! Vetøelec detekován na Patøe }
{307}{}{                             Skynet - Bezpeènostní systémy
                                 Pozor!!! Vetøelec detekován na Patrech: }
{115}{}{Aktivace poplašného systému - Patro 2}
{116}{}{Spustit autodiagnostický program.}
{117}{}{Konec}
{118}{}{Arrrgh! [V zuøivosti mlátíš do klávesnice...]}
{120}{}{Skynet - Bezpeènostní systémy
                                  Pøístup k tomuto terminálu zakázán}
{122}{}{Konec.}
{124}{}{Chyba!
                                                               Žádné programy nejsou dostupné
                            Prosím restartujte}
{126}{}{Konec}
{127}{}{Analyzuji pøíkaz, prosím èekejte...
                              Uživatelský pøíkaz ignorován
                              Pøístup odepøen}
{128}{}{[Více]}
{129}{}{K deaktivaci poplachu prosím 1
                                    Pro diagnostický program prosím 2
                             Pro ukonèení prosím 3}
{130}{}{Zmáèknout 1}
{131}{}{Zmáèknout 2}
{132}{}{Zmáèknout 3}
{133}{}{Konec}
{134}{}{Varování! Tento program pracuje nejlépe, pokud budou ukonèeny všechny jiné aktivní programy. Pøejete si toto nyní uèinit?}
{135}{}{Ano.}
{136}{}{Ne.}
{137}{}{Konec}
{138}{}{Ukonèení Skynet - Bezpeènostního programu
                    Analýza datové struktury...
                                  Diagnostika pøerušena
                                  Diagnostický program ukonèen
                                  Reinicializace bezpeènostního programu
                          Vynulování poplachu
                                         Skynet - Bezpeènostní program - Pøipraven}
{139}{}{Konec}
{140}{}{Pøístup odepøen...
                                                  Pøístup odepøen...
                                                  Pøístup povolen
                                                  Ukonèení poplachu Patro 2}
{141}{}{Konec}
{142}{}{Neautorizovaný pøístup
                                              Inicializace bezpeènostního odpojovacího systému}
{143}{}{Konec}
{144}{}{Analyzuji pøíkaz, prosím èekejte...
                           Ukonèit vše...
                                                      Pøerušeno kódem 667 - Skynet
                                  Pøístup k tomuto terminálu byl ukonèen.}
{145}{}{Konec}
{146}{}{Ukonèení diagnostického programu.}
{147}{}{[Více]}
