#tento soubor prelozil Patrik "GENIE" Lipina
{100}{}{Poèítaèovı terminál.}
{101}{}{Na rùznıch místech poèítaèe jsou nalepeny obrázky spoøe odìnıch dívek.}
{102}{}{Nemùeš pøeèíst, co je na monitoru.}
{103}{}{Zbrojní pøístupovı terminál
                                        Silová pole - Vypnuta
                                           Energetické pláty - Vypnuty}
{104}{}{Zbrojní pøístupovı terminál
                                        Silová pole - Vypnuta
                                     	   Energetické pláty - Zapnuty}
{105}{}{Zbrojní pøístupovı terminál
                                        Silová pole - Zapnuta
                                           Energetické pláty - Vypnuty}
{106}{}{Zbrojní pøístupovı terminál
                                        Silová pole - Zapnuta
                                           Energetické pláty - Zapnuty}
{107}{}{Vypnout energetické pláty}
{108}{}{Vypnout silová pole}
{109}{}{Èíst poštu}
{110}{}{Konec}
{111}{}{[A se snaíš jak se snaíš, tento shluk písmen ti nedává praádnı smysl.]}
{112}{}{Vypnout energetické pláty
                                           Prosím zadejte heslo:}
{113}{}{Nabourat se do bezpeènostních systémù}
{114}{}{Hádat heslo}
{115}{}{Zpìt do hlavního menu}
{116}{}{Konec}
{117}{}{[Tenhle program je pro tebe pøíliš sloitı.]}
{118}{}{Zpìt do hlavního menu}
{119}{}{Konec}
{120}{}{[Podaøilo se ti obejít pøístupové heslo a deaktivovat energetické pláty.]}
{121}{}{Zpìt do hlavního menu}
{122}{}{Konec}
{123}{}{Vypnout silová pole
                                           Prosím zadejte heslo:}
{124}{}{Nabourat se do bezpeènostních systémù}
{125}{}{Hádat heslo}
{126}{}{Zpìt do hlavního menu}
{127}{}{Konec}
{128}{}{[Sobory jsou šifrovány a bez dekodéru z tohoto moc mít nebudeš.]}
{129}{}{Zpìt do hlavního menu}
{130}{}{Konec}
{131}{}{[Tak tohle byla celkem hraèka... silová pole jsou nyní vypnuta.]}
{132}{}{Zpìt do hlavního menu}
{133}{}{Konec}
{134}{}{[Nìkdo zapomnìl zavøít svùj mailbox.]
                     Potvrzení objednávky
                                              Pokyny k evakuaci
                                                   Pøátelskı pozdrav
                                                   Obchodní mail}
{135}{}{[Vyber si soubor k pøeètení:]}
{136}{}{Èíst Potvrzení objednávky}
{137}{}{èíst Pokyny k evakuaci}
{138}{}{Èíst Pøátelskı pozdrav}
{139}{}{Èíst Obchodní mail}
{140}{}{Zpìt ho hlavního menu}
{141}{}{Konec}
{142}{}{Tato zpráva vám potvrzuje vaši objednávku videa "Debbie jde do armády" a "Hluboké hrdlo, díl 1059". Tituly by vám mìly bıt doruèeny poštou do dvou tıdnù. Dìkujeme, e jste vyuili našich slueb.}
{143}{}{Èíst další mail}
{144}{}{Konec}
{145}{}{Evakuace Armádního skladu Sierra byla posunuta o jeden tıden dopøedu. Všechna bezpeènostní naøízení musí bıt splnìna do tohoto data. To vše na pøíkaz Generála Cliftona, v.r.}
{146}{}{Èíst další mail}
{147}{}{Konec}
{148}{}{[Slyšíš zvuk jiskøení nìkde z útrob terminálu. Zaèíná se z nìj kouøit... S mírnım odstupem sleduješ, jak se z klávesnice stává cosi neurèitého tekutého. Hmm... to musí bıt jeden z tìch virù, co se o nich psalo v knihách.]}
{149}{}{Konec}
{150}{}{Tady Klinger z 8063. NUTNÌ potøebujeme souèástku ev. èíslo 102-53B. Mám tady bedınku Chateau Lafayette, roèník 2155, pokud by se ti zadaøilo to nìjak vyøešit. Dík a ozvi se!}
{151}{}{Èíst další mail}
{152}{}{Konec}
{153}{}{[Teda tohle je neuvìøitelné štìstí! Ani nevíš jak se ti podaøilo uhádnout heslo "Hooters"]
                         	                      Deaktivuji energetické pláty}
{154}{}{Zpìt ho hlavního menu}
{155}{}{Konec}
{156}{}{[Je úplnì jedno, jak dlouho se budeš snait... To heslo stejnì neuhádneš.]}
{157}{}{Zpìt ho hlavního menu}
{158}{}{Konec}
{159}{}{[Myšlenkové pochody toho, kdo zadával hesla asi nikdy nepochopíš. Správné heslo je "bradavky"]
                               				Deaktivuji silová pole}
{160}{}{Zpìt ho hlavního menu}
{161}{}{Konec}
{162}{}{[Je úplnì jedno, jak dlouho se budeš snait... To heslo stejnì neuhádneš.]}
{163}{}{Zpìt ho hlavního menu}
{164}{}{Konec}
{165}{}{[Tvoje vrtání do tohohle bez znalosti terminálù zpùsobilo, e explodoval pøímo pøed tebou.]}
{166}{}{Konec}

{200}{}{[Tento terminál u pracovat nebude... NEBUDE!]}
