#tento soubor prelozil Patrik "GENIE" Lipina
{100}{}{Poèítaèovı terminál.}
{101}{}{No, celkem zastaralı terminál. Frekvence procesoru jen 500Mhz.}
{102}{}{Nemùeš pøeèíst text na monitoru.}
{103}{}{Automatická Opravná Stanice
                                  Poadavek na opravu - provádí se
                               Povolány opravárenské jednotky}
{104}{}{}
{105}{}{}
{106}{}{Pokusit se deaktivovat opravnou stanici.}
{107}{}{Vytrhnout poèítaè ze zdi.}
{108}{}{Zmáèknout VELKÉ èervené tlaèítko s nápisem OFF.}
{109}{}{Konec}
{110}{}{[Ani náhodou netušíš, jak by se dal tento program ukonèit.]}
{111}{}{Konec}
{112}{}{[Naukání slovíèka "OFF" se zdá bıt tím pravım oøechovım na tento systém. Ten je nyní vypnut.]}
{113}{}{Konec}
{114}{}{[Èistì náhodou si všímáš kabelu el. vedení, vedoucího z poèítaèe do zdi.
 Obrazovka poèítaèe zèernala ve chvíli, kdy šòùra pøestala spojovat poèítaè s el. sítí.]}
{115}{}{Konec}
{116}{}{[Stisknout tlaèítko nadepsané "OFF" bylo dílem okamiku. Jak se dalo oèekávat, obrazovka zèernala.]}
{117}{}{Konec}
{118}{}{[Ve chvíli, kdy se tvé prsty dotkly klávesnice, zaèaly klávesy vypadávat na zem. Asi u je toho na tento terminál moc.]}
{119}{}{Konec}
{120}{}{Automatickı Opravnı systém je ji mimo provoz.}
{121}{}{Nelze pouít tento terminál. Nìkdo rozbil klávesnici.}
