#tento soubor prelozil Patrik "GENIE" Lipina
#############################################################
#  Message File: ZCBrahmn.msg                               #
#                                                           #
#       Body Type:  Brahmin                                 #
#       Combat AI: None                                     #
#       Weapons: None                                       #
#       HP: ?                                               #
#       Skills to note: None                                #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: December 01, 1997                               #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{Vidíš bìžný domestikovaný dobytek.}
{101}{}{Dùvod, proè má dvì hlavy, je to, že byl vystaven dávce radiace kdysi dávno - dávno, kdy tomuto øíkali kráva.}
{102}{}{Nevidíš nic zvláštního na tomhle dobytku.}
{103}{}{Brahmíny nejsou nic moc, tedy co se konverzace týèe.}
{104}{}{To nemáš nic jiného na práci, než tu tvrdnout a kecat s dvouhlavou krávou?}
{105}{}{Je to brahmína. Má dvì hlavy.}

{201}{}{Bùù...}
{202}{}{Bùù Bùù Bùù...}
{203}{}{Bùù...}
{204}{}{Bùùùùù...}
{205}{}{Bùùùùùùùù...}
{206}{}{:: PRD ::}
