#tento soubor prelozil Patrik "GENIE" Lipina
{100}{}{Vidíš muže s bystrýma oèima. Vypadá, že rozumí byznysu.}
{101}{}{Vidíš krupiéra.}
{102}{}{Má shrabovací tyè a spoustu prachù. Možná by se dalo vyzkoušet tvé štìstí.}

{103}{}{Vaše sázky, prosím. Máme nového hráèe.}
{104}{}{Kolik vsadíš na PASSLINE?}
{105}{}{Kolik vsadíš na DON'T PASSLINE?}
{106}{}{Kolik vsadíš na COMELINE?}
{107}{}{Kolik vsadíš na DON'T COMELINE?}
{108}{}{Kolik vsadíš na FIELD?}
{157}{}{Kolik vsadíš na PLACEBET?}
#options
# 2 3 12 crap out. 7 11 win auto..

{109}{}{Vsadit na }

{110}{}{Pass line.}
{111}{}{Don't Pass line.}

{112}{}{Come line.}
{113}{}{Don't Come line.}

{114}{}{Nabízejte sázky...}
{115}{}{Umísti sázky ...}
{116}{}{Dej sázku do pole}
{118}{}{Házím}

{119}{}{Pass line bet urèeno na:}
{120}{}{Don't pass line bet urèeno na:}
{121}{}{Come line bet urèeno na:}
{122}{}{Don't come line urèeno na:}

{123}{}{7:}
{124}{}{d3s:}
{125}{}{d4s:}
{126}{}{d5s:}
{127}{}{d2s:}
{128}{}{1a2:}
{129}{}{5a6:}
{130}{}{1a1:}
{131}{}{6a6:}
{132}{}{Kostky:}

{133}{}{Pls 4:}
{134}{}{Pls 5:}
{135}{}{Pls 6:}
{136}{}{Pls 8:}
{137}{}{Pls 9:}
{138}{}{Pls 10:}

{139}{}{Na 4:}
{140}{}{Na 5:}
{141}{}{Na 6:}
{142}{}{Na 8:}
{143}{}{Na 9:}
{144}{}{Na 10:}

{145}{}{Odds 4:}
{146}{}{Odds 5:}
{147}{}{Odds 6:}
{148}{}{Odds 8:}
{149}{}{Odds 9:}
{150}{}{Odds 10:}

{151}{}{Field bet urèeno na:}

{152}{}{Kterou sázku?}
{153}{}{Kolik?}
{154}{}{Sázky na jeden hod...}
{155}{}{Drsnìjší sázky...}
{156}{}{Typ sázky ?}

#proposition bets
{200}{}{hodit 7 (kurz 5 ku 1)}
{201}{}{dvì trojky (kurz 10 ku 1)}
{202}{}{dvì ètyøky (kurz 10 ku 1)}
{203}{}{dvì pìtky (kurz 8 ku 1)}
{204}{}{dvì dvojky (kurz 8 ku 1)}
{205}{}{1 a 2 (kurz 15 ku 1)}
{206}{}{5 a 6 (kurz 15 ku 1)}
{207}{}{1 a 1 (kurz 30 ku 1)}
{208}{}{6 a 6 (kurz 30 ku 1)}
{209}{}{Další kostky (kurz 8 ku 1)}

#place bets
{299}{}{Kterou sázku?}
{300}{}{na 4 (kurz 1.8)}
{301}{}{na 5 (kurz 1.4)}
{302}{}{na 6 (kurz 1.16)}
{303}{}{na 8 (kurz 1.16)}
{304}{}{na 9 (kurz 1.4)}
{305}{}{na 10 (kurz 1.8)}

{400}{}{Zpìt...}

{500}{}{$}
{501}{}{.}

#reward messages
#pass line strings
{600}{}{Sedm vyhrává.}
{601}{}{Jedenáct vyhrává.}
{602}{}{Dvì, prohrává.}
{603}{}{Tøi, prohrává.}
{604}{}{Dvanáct, prohrává.}

#don't pass line strings
{610}{}{Sedm prohrává.}
{611}{}{Jedenáct prohrává.}
{612}{}{Dvì, vyhrává.}
{613}{}{Tøi, vyhrává.}
{614}{}{Dvanáct, remíza.}

#proposition begs
{620}{}{Prop bet 7}
{621}{}{Prop bet dvì trojky}
{622}{}{Prop bet dvì ètyøky}
{623}{}{Prop bet dvì pìtky}
{624}{}{Prop bet dvì dvojky}
{625}{}{Prop bet 1 a 2}
{626}{}{Prop bet 5 a 6}
{627}{}{Prop bet 1 a 1}
{628}{}{Prop bet 6 a 6}
{629}{}{Prop bet Craps 2,3,12}
{630}{}{Prohrava!}
{631}{}{Vyhrava!}

#place bets
{650}{}{Place bet 4}
{651}{}{Place bet 5}
{652}{}{Place bet 6}
{653}{}{Place bet 8}
{654}{}{Place bet 9}
{655}{}{Place bet 10}

#field bets
{660}{}{Field bet 2 dvojnásobná výhra.}
{661}{}{Field bet 3 vyhrává.}
{662}{}{Field bet 4 vyhrává.}
{663}{}{Field bet 9 vyhrává.}
{664}{}{Field bet 10 vyhrává.}
{665}{}{Field bet 11 vyhrává.}
{666}{}{Field bet 12 trojnásobná výhra.}
{667}{}{Field bet prohrává.}

#flat bet
{670}{}{Flat bet 4}
{671}{}{Flat bet 5}
{672}{}{Flat bet 6}
{673}{}{Flat bet 8}
{674}{}{Flat bet 9}
{675}{}{Flat bet 10}

{680}{}{Odds bet 4}
{681}{}{Odds bet 5}
{682}{}{Odds bet 6}
{683}{}{Odds bet 8}
{684}{}{Odds bet 9}
{685}{}{Odds bet 10}

{700}{}{Chybný hod odds vráceny.}
{701}{}{Hraju}
{702}{}{Nehraju}

{710}{}{Kostka1:}
{711}{}{Kostka2:}

{712}{}{Sorry, musím skonèit.}
{713}{}{Sorry, tuhle sázku neuzavøu.}
{714}{}{Odebírám.}

#odds bet stuff
{800}{}{Vem Odds na hraných èíslech.}
{801}{}{Vyber odds násobitel. Odds:}
{802}{}{x odds.}
{803}{}{momentálnì na:}
{804}{}{Odds bet na 4.}
{805}{}{Odds bet na 5.}
{806}{}{Odds bet na 6.}
{807}{}{Odds bet na 8.}
{808}{}{Odds bet na 9.}
{809}{}{Odds bet na 10.}
{810}{}{Na které èíslo sázíš?}

{1100}{}{Vidíš ostrookou ženu. Vypadá, že rozumí byznysu.}
{1102}{}{Má shrabovací tyè a spoustu prachù. Možná bys mìl vyzkoušet své štìstí.}
