#tento soubor prelozil Patrik "GENIE" Lipina
#############################################################
#  Message File: ZClScorp.msg                               #
#                                                           #
#       Body Type:  Lesser Scorpion                         #
#       Combat AI: Scorpion AI                              #
#       Weapons:                                            #
#       HP: ?                                               #
#       Skills to note: None                                #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: December 01, 1997                               #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{Vidíš škorpióna.}
{500}{}{Všichni škorpióni, kteøí sužovali dobytek jsou již mrtví... tvou zásluhou.}
