#tento soubor prelozil Patrik "GENIE" Lipina
# EXAMINES
{151}{}{}

# USE MESSAGES
{199}{}{Co to je za zasranou otázku?}
{200}{}{Vypadá dobøe.}
{201}{}{Nevypadá moc dobøe.}
{202}{}{A moje odpovìï je ne.}
{203}{}{Nespoléhej na to.}
{204}{}{Mùeš se na to spolehnout.}
{205}{}{Zeptej se pozdìji.}
{206}{}{Nejpravdìpodobnìji ano.}
{207}{}{To teï nemùu odhadnout.}
{208}{}{Ano.}
{209}{}{Ano. Stoprocentnì.}
{210}{}{Není vhodné ti to teï øíci.}
{211}{}{To je jisté.}
{212}{}{Velice o tom pochybuji.}
{213}{}{Je tak rozhodnuto.}
{214}{}{Koncentruj se a zeptej se znova.}
{215}{}{Zaškrtni si ano.}
{216}{}{Cítím v kostech, e ne.}
{217}{}{Bezpochyby.}
{218}{}{Znovu a pomalu, jasné?}
{219}{}{Kdy o tom tak pøemıšlím, tak ano.}
{220}{}{Netøepej se mnou tak. To bolí.}
{221}{}{Máš silnou pravou ruku...}
{222}{}{Laskavì si utøi ruce, ne do se mnou budeš tøepat.}
{223}{}{Doèasnì mimo provoz.}
{224}{}{Zavøeno na pøíkaz rady RPG.}
{225}{}{Ještì jednou se mì dotkni a máš problém.}
{226}{}{Cítím se špatnì.}
{227}{}{Cítím se docela zle.}
{228}{}{Máš horké ruce.}
# 9 or greater luck
{229}{}{Feargus byl proti tomu, abych hrál. To je ale trouba.}
{230}{}{Vaše skore je 23 ze 100. Ještì stále máte rezervy, kudy stoupat vıše.}
{231}{}{Somnambulus se tváøil dost nešastnì, kdy uvidìl, kolik je vìcí v inventáøi ve høe...}
{232}{}{Podívej se do toalety v prvním patøe v koupelnì v kasínu pana Mordina v New Renu.}
{233}{}{Nìkdo zakopal poklad pod køíem nadepsanım 'Odpadky' v místì zvaném Golgotha.}
{234}{}{A dokonèíš hru, jdi zpìt do New Rena a promluv si s Otcem Tullym.}
{235}{}{Nìkde v New Renu je velikonoèní vejce.}
{236}{}{Pøestaò se mnou tak tøepat!}
{237}{}{Tvé ŠTÌSTÍ je velice vysoké. Zatøes a uvidíš.}
{238}{}{Ano, my VÍME, e Descent to Undermountain byl brak.}
{239}{}{Kdy prodáš Bessie øezníkùm v Modocu, mùeš ji znova osvobodit.}
{240}{}{Dej si pozor na to, co øekne Curtis kdy se k nìmu vrátíš s Mr. Nixonem ve Vault City.}
{241}{}{Pøi hádce s manelem v Broken Hills, ena opravdu vyhodila Koèièí Packu do odpadkù.}
{242}{}{Potøebuješ vysokou SÍLU *A* VİDR abys mìl šanci porazit Francise v pìstním souboji.}
{243}{}{Kód k aktivaci prvního terminálu ve Vaultu Vault City je 3PCF186.}