#tento soubor prelozil Patrik "GENIE" Lipina
# 0. QUICK LOOK
{100}{}{Vidíš krupiéra.}
{101}{}{Vidíš stùl na kostky.}
# has no gambling skill messages
{110}{}{Vidíš dìvèe.}
{111}{}{Vidíš stùl.}

# 0. EXAMINES
# table
{140}{}{Vidíš stùl pro hru v kostky.}
# no skill
{141}{}{Vidíš stùl s vìcmi na nìm.}

# dealer
{150}{}{Vidíš jednu z krupiérek v kasínu.}
{151}{}{Vidíš jednu z krupiérek v kasínu. Kıvá na tebe a si jdeš zahrát.}
{152}{}{Vidíš jednu z krupiérek v kasínu. Její obleèení jen zlehka zakrıvá její tìlo.}
{153}{}{Vidíš jednu z krupiérek v kasínu. Má docela pìkné náramky.}
{154}{}{Vidíš jednu z krupiérek v kasínu. Usmívá se na tebe.}
{155}{}{Vidíš jednu z krupiérek v kasínu. Voní opravadu krááásnì.}
# no skill
{160}{}{Vidíš krásnou enu.}
{161}{}{Mává na tebe, abys pøišel blíe.}
{162}{}{Její obleèení není nijak veliké.}
{163}{}{Má docela pìkné náramky.}
{164}{}{Mrká na tebe.}
{165}{}{Voní opravdu kráááásnì.}

# use gambling skill on dealer
# dealer dice amounts are screwed up
{175}{}{NENÍ KOSTKA!!!}
{176}{}{NÌJAK MOC KOSTEK!!!}
# dealer has loaded dice planted by player
{177}{}{Tvé šance vypadají docela nadìjnì od té doby, co byly kostky tebou "náhodou" vymìnìny.}
{178}{}{Šance nevypadají nic moc.}
{179}{}{Tvé šance mùeš jen stìí odhadnout.}
# dealer has regular dice
{185}{}{Šance vypadají docela slibnì.}
{186}{}{Tvé šance mùeš jen zteí odhadnout.}
{187}{}{Šance nevypadají nic moc.}

# 2. FLOAT [ENCLAVE_DESTROYED == TRUE]
{200}{}{::Na zdravíííí::}
{201}{}{::Cink::}
{202}{}{::Píííísk!!!::}
{203}{}{}
{204}{}{Jsem si myslel, e u jsi na nás zapomnìl, kdy si teï zachraòoval ten svìt.}

# 3. FLOAT [MADE MAN, SAME CASINO] (WTG)
{215}{}{Ahoj, }
{216}{}{Kdyby tady byl zájem o nìjakou spoleènost...}
{217}{}{Héj, ty...[mrká]...dáš si partièku?}
{218}{}{Vypadá tak...[tøese se]...nebezpeènì.}
{219}{}{Vítej v kasínu, }
{220}{}{Nedalo by se za mnì pøimluvit u šéfa?}
{221}{}{zdravíèko madam. Kdyby bylo jakkoli tøeba pomoci, jsem zde.}
{222}{}{Zahrajeme si, madam?}
{223}{}{Vypadá tak...[tøese se]...nebezpeènì.}

# 5. FLOAT [MADE MAN, WRONG CASINO] (WTG)
{235}{}{Tak to tak vypadá, e tu nìkdo riskuje svùj ivot.}
{236}{}{Uff, se mi zdá, e si nìkdo spletl kasíno...}
{237}{}{Jestli nevypadne døív, ne ho hoši zahlédnou...}
{238}{}{Uh-oh. A problém...}
{239}{}{Tak to tak vypadá, e tu nìkdo riskuje svùj ivot.}
{240}{}{Uff, se mi zdá, e si nìkdo spletl kasíno...}
{241}{}{Jestli nevypadne døív, ne ji hoši zahlédnou...}

# 7. FLOAT [MALE, PRIZEFIGHTER] (WTG)
{250}{}{Hej, borèe. Co tak to tady rozotèit?}
{251}{}{Hej, šampióne...[mrká]...dáš si nìco?}
{252}{}{Hej, šampióne...[usmívá se]...chceš dostat šanci?}
{253}{}{Kdyby tady byl zájem o nìjakou spoleènost...}
{254}{}{Kdybych si tak s ním mohl promluvit...}
{255}{}{Hej, }
{256}{}{Jestli máš chu vyhrát nìjaké peníze, tak jsi na správném místì!}
{257}{}{Štìstìna nás navštívila!!! Dnes jen samí vítìzové!}
{258}{}{Jen pojï dále, }
{259}{}{Ještì nìjakı drink?}
{260}{}{Vítejte v kasínu, }
{261}{}{Ahoj, }
{262}{}{Partièku, }
{263}{}{Vítej v kasínu, }

# 9. FLOAT [PORN STAR] (WTG)
{270}{}{Hej ty, hvìzdo. Co tak to tady rozotèit?}
{271}{}{Hej, }
{272}{}{Hej, }
{273}{}{Jestli máš chu vyhrát nìjaké peníze }
{274}{}{Štìstìna nás navštívila!!! Dnes jen samí vítìzové!}
{275}{}{Jen pojï dále, }
{276}{}{Ještì nìjakı drink?}
{277}{}{Vítejte v kasínu, }
{278}{}{Hej ty, paní héreèko. Utrácíš vıplatu?}
{279}{}{Tanèíte dnes?}

# 11. FLOAT [MALE, NO REP] (WTG)
{290}{}{Hej ty, zlatíèko. Nechceš utratit nìjakı kroupy?}
{291}{}{Hej, zlatíèko...[mrká]...zahraješ si?}
{292}{}{Hej, zlatíèko...[usmívá se]...chceš dostat šanci?}
{293}{}{Jestli máš chu vyhrát nìjaké peníze, tak jsi na správném místì.}
{294}{}{Štìstìna nás navštívila!!! Dnes jen samí vítìzové!}
{295}{}{Jen pojï dále, vydìlej si nìjaké peníze.}
{296}{}{Ještì nìjakı drink zlatíèko?}
{297}{}{Vítejte v kasínu, zlatíèko!}
{298}{}{Tady u stolu je volno, jestli máš chu si trochu zariskovat...}
{299}{}{Hele, zlatíèko. Nechceš utratit nìjakı kroupy?}
{300}{}{Zariskuješ si, zlatíèko?}
{301}{}{Vítej v kasínu, zaltíèko.}

# 13.  PLACE YOUR BETS (WTG)
{320}{}{[Krupiérka se na tebe nervóznì dívá a pøevykuje.] Um, vaše sázky, prosím... minimální vklad je $}
{321}{}{Vaše sázky prosím, pane. Minimum je $}
{322}{}{Vaše sázky prosím, madam. Minimum je $}
{323}{}{Vaše sázky prosím. Minimum je $}
{324}{}{Já bıt lepší ne ty}
{325}{}{Já hrát u jako dítì}
{326}{}{Co to je za hru? A mùe se sázet kùe Gecka? Já mám géééé ... éééé sakra. [Zmizet.]}
{327}{}{[Máš $}
{328}{}{Vsadit $}
{329}{}{Juuu, tak na to já nemám.}
{330}{}{Já dnes nesázím, dík.}
{331}{}{Uhhh, promiòte. Tyhle bláznivé hry mi moc neøíkají.}

# 14.  RETARD (14)
{340}{}{Um...jsem slyšel, e se prı budou dávat mozky. To abych to zase zkontroloval...}
{341}{}{Uh, bezva, pane. Brzy nás navštivte znovu.}
{342}{}{Uh, bezva, madam. Brzy nás navštivte znovu.}
{343}{}{Paaa paaaa}
{344}{}{Faaaajn...}
{345}{}{Uf...coe...co to zas je?! Já muset vidìt!}

# 15. POOR MAN (13)
{350}{}{Vıbornì pane, pøijïte brzy zase.}
{351}{}{Vıbornì madam, pøijïte brzy zase.}
{352}{}{[Krupiér pozvedl zrak.] $}
{354}{}{Tak, tak, dìkuji.}
{355}{}{Moná.}

# 16. LOOOOOOSER (13)
{400}{}{Je mi líto, mnoho štìstí pro pøíštì.}
{401}{}{Je mi líto pane, mnoho štìstí pro pøíštì.}
{402}{}{Je mi líto madam, mnoho štìstí pro pøíštì.}

{410}{}{Rovnost.}
{411}{}{Rovnost. Ještì jednou, pane?}
{412}{}{Rovnost. Ještì jednou, madam?}

{420}{}{Vítìzíte! Dvojnásobíte vklad!}
{421}{}{Vítìzíte! Dvojnásobíte vklad! Vıbornì, pane!}
{422}{}{Vítìzíte! Dvojnásobíte vklad! Vıbornì, madam!}

{430}{}{Vítìzíte! Trojnásobíte vklad!!!}
{431}{}{Vítìzíte! Trojnásobíte vklad!!! Máte ale dnes štìstí, pane.}
{432}{}{Vítìzíte! Trojnásobíte vklad!!! Máte ale dnes štìstí, madam.}

{440}{}{Øeknìme pøes den.}
{441}{}{Øeknìme pøes noc.}

#17. TABLE TAMPER
{450}{}{Promiòte, tento stùl je zavøen. Nìkdo nám tady dìlá nepoøádek s kostkama.}
{451}{}{Promiòte pane, tady se nehraje. Nìkdo nám tady "manipuluje" s kostkama.}
{452}{}{Par don madam, tady se nehraje. Nìkdo nám tady "manipuluje" s kostkama.}
{453}{}{Uhhh, OK.}
{454}{}{Tak to mi je líto. Ale dík.}

# message parts
{2203}{}{! Vítej v kasínu, hrdino!}
{2215}{}{. Mohu *jakkoli* pomoci?}
{2219}{}{.}
{2255}{}{. Co takhle prohrábnout prkenici?}
{2258}{}{, pojï nìco vyhrát.}
{2260}{}{.}
{2261}{}{. Dìj mi vìdìt, jestli mùu nìjak pomoci.}
{2262}{}{?}
{2263}{}{.}
{2321}{}{. Vaše sázky, prosím...}
{2327}{}{.] }
{2328}{}{.}
{2344}{}{ mùe vdy vytáhnout nìco zajímavého nového z inventáøe. [Opustit.]}
{2352}{}{? 'Tohle a moc drahé?' [Diví se.] Èlovìèe, tak to seš ve špatném mìstì.}
{2353}{}{? 'Tohle a moc drahé?' [Diví se.] Dìvèe, tak to seš ve špatném mìstì.}
