#tento soubor prelozil Patrik "GENIE" Lipina
#############################################################
#  Message File: ziGenGrv.msg                               #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the dialog for a     #
#           new character from which is used by the         #
#           design tool. It will be updated using the       #
#           the tool. This is just a tool file, and not     #
#           meant to be used in the game.                   #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#                                                           #
#  Created: January 15, 1998                                #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the item when     #
#  glanced and and examined.                                #
#############################################################

# 100-199 are for grave site messages
{100}{}{Vidíš hrob.}
{101}{}{Vidíš otevøenı hrob.}
{102}{}{Hrob.}
{103}{}{Tento hrob je otevøenı.}
{150}{}{Tento hrob je zasypanı.}
{151}{}{Tento hrob je otevøenı.}

# 200 on are all for headstones
{200}{}{Vidíš náhrobek.}
{201}{}{Vidíš náhrobní køí.}

# 250 + long descriptions
# generic no name sites
{250}{}{Na tomto náhrobku není nic vyryto.}
{251}{}{Jméno na tomto náhrobku je seškrábáno.}
{252}{}{Na náhrobku je jméno John Doe.}
{253}{}{Jméno a data na tomto náhrobku zašla vlivem poèasí.}
# for crosses
{260}{}{Na tomto køíi není nic vyryto.}
{261}{}{Jméno na tomto køíi je seškrábáno.}
{262}{}{Na køíi je jméno John Doe.}
{263}{}{Jméno a data na tomto køíi zašla vlivem poèasí.}

# leader
{275}{}{Na náhrobku stojí: }
{276}{}{Na køíi stojí: }

# specific cases
{300}{}{"Zde leí Chris Avellone, Král parketu."}
{301}{}{"Chris Jones. Noèní pták."}
{302}{}{"Christopher Michael Holland, neboli 'Chris Holland', neboli 'Chris': Ke ètení tohoto náhrobku jsou dva a pùl dùvodu... Obvykle se èeká, e budou takové dùvody uvedeny."}
{303}{}{"Colin McComb: Další nesmyslnı ivot"}
{304}{}{"David Hendee: Nejhlasitìjší mezi mrtvımi. A odpoèívá v pokoji, a tiše."}
{305}{}{"Ed Hyland. Øekl svìtu, a mu políbí...'"}
{306}{}{"Eric Demilt. OPRAVDOVİ bojovnı hoch."}
{307}{}{"Feargus Urquhart: Jeden zatracenı seznam byl pro nìj moc."}
{308}{}{"Fred Hatch. Zemøel pøi nahrávání Myronova hlasu."}
{309}{}{"Gary Platner. Zabit protoe nevyrábìl více modelù obyvatel Vaultu."}
{310}{}{"Jason Anderson: u ne ivoucí bùh."}
{311}{}{"Jason G. Suinn."}
{312}{}{"Jason Taylor."}
{313}{}{"Jeremy Barnes. Odvánı vùdce smeèky Black Isle."}
{314}{}{"Jesse Reynolds. Mìl rád zázvorové placky. A pøíliš."}
{315}{}{"John Deiley."}
{316}{}{"John Price."}
{317}{}{"Leonard Boyarski. Vyhnán z Vault City."}
{318}{}{"Rupert Dinkos, zemøel v zimì '00."}
{319}{}{"Matt Norton. Moh bejt kdokoli. Moh bejt rváè, a pøitom to byl takovej lempl."}
{320}{}{"Nick Kesting." [Písmo je místy obloeno mìdí]}
{321}{}{"Robert Collier. Tichı. Smrtelnı. Chmaták."}
{322}{}{"Robert Hertenstein 2. Jeho doktor mu to chtìl øíct, ale on trval na tom, e 'by toho bylo u moc.'"}
{323}{}{"Scott Cambell. Ne ta polévka."}
{324}{}{"Zde leí Scott Everts. Pozdì na práci. Pozdì na ivot."}
{325}{}{"Scott Rodenhizer. Vytvoøil 3D hlavy."}
{326}{}{"Thomas French:  Zemøel pøi pokusu ovládnout padající gilotinu."}
{327}{}{"Tim Cain. Zakladatel, Milenec, Bojovník, Programátor."}
{328}{}{"Tramell Ray Isaac: Zde leí jeden z nejpilnìjších lidí v brani. Neobyèejnı animátor. Myslím. Odpoèívej v pokoji, Treamelle Rayi"}
{329}{}{"Zeb -- starší ne hlína sama"}
{330}{}{"Dennis Presnell. Jako bychom ho slyšeli øíkat : 'Tomu øíkáte pohøeb?! Kurvárna! Kluci, vy jste k!@oti! U radši nikdy nezemøu! Bla bla bla...'" Pod tím je naèmáráno : "Odpoèívej 'ukøièenı' Dennisi, a dr u zobák."}
{331}{}{"Rupert Diukos, zemøel 24.9.96"}
{332}{}{"Sal De Ban, zemøel 24.9.96"}
{333}{}{"Greg Zeschule, podzim '99"}
{334}{}{"Ray Muzyka, léto '98"}
{335}{}{"Evan Chantland, 74-??: Nebyl to paranoik. Vánì po nìm šli."}
{336}{}{"Zde leí Moose, mrtvı a studenı. Našli jsme ho tu - nemìl hlavu."}
{337}{}{"Amy Presnell"}
{338}{}{"Stephen Bokkes, vìk 25. Nechal se probodat støelami a šípy rozkácené sudby." }
{339}{}{"R.I.P. Doug "Lebkoun" Finch (Datum není dùleité) Zabit za kouøení ve French Market. Jeho poslední slova : `Aby vás osel nakopl!'"}
{340}{}{"Zde leí Donnie Cornwell, dobrı a mrtvı mu.  Ve speciální rakvi, do které se vešla jeho supervelká makovice."}
{341}{}{"Chmaták Giampa il svùj ivot stejnì jako miloval eny: rychle, levnì, snadno."}
{342}{}{"T. D. Hamilton: Zde leí ten parchant, kterı mìl umøít mnohem, mnohem døíve. Táhni do pekla, SMRADE!"}
{343}{}{"Další z obìtí termínu odevzdání."}
{344}{}{"Pes je mrtev. A ije Pes."}
{345}{}{"Kris Snider: Pøíliš soutìivı"}
{346}{}{"Dìláš se svım ivotem nìco uiteèného?"}
{347}{}{"Proè se prostì nezabiješ?"}
{348}{}{"Charles Cuevas: Jednou øekl : 'Chci hokej nebo smrt!' Ten hokej nedostal."}
{349}{}{"William Lebus"}
{350}{}{"Reg Arnedo: v sálech stále slyšíme jeho hlas."}
{351}{}{"Shanna SanPaolo"}
{352}{}{"Brahmin Wrangler"}
{353}{}{"Josh Walters, 1971-2011.  Zemøel na následek komplikací pøi jeho páté transplantaci jater."}
{354}{}{"Doug Avery. Nesnášel válku za to, e znièila ivotní styl obytnıch pøívìsù."}
# joke ones
{355}{}{"Zde leí Ezekial Aikle, vìk 102. Dobøí umírají mladí."}
{356}{}{"Zde leí Anna Muzat - ila jako stará panna a zemøela jako stará muatka. Dec. 8, 1767"}
{357}{}{"Dìti Izraele chtìli chléb a Pán jim seslal manu. Starı úøedník Wallace chtìl enu a ïábel mu seslal Annu."}
{358}{}{"To je Johnny Yeast. Omluvte ho, e pøi vašem pøíchodu zùstane leet."}
{359}{}{"Zde leí tìlo Jonathana Ozdy - sešlápl plyn místo brzdy."}
{360}{}{"Zde leí Butch, úspìšnı alkoholik, neúspìšnı støelec."}
{361}{}{"Na památku mého manela Johna Barnese, kterı zemøel 3. ledna 1803. Milá a mladá vdova, vìk 23, která dovede bıt dobrou manelkou, hledá nìkoho, kdo by ji utìšoval."}
{362}{}{"Sir John Strange. Zde leí upøímnı právník, a to je neobvyklé."}
{363}{}{"Byl jsem nìkdo. Kdo, po tom ti nic není."}
{364}{}{"Zde leí Lester Moore, ètyøi prùstøely .44, nic míò, nic víc."}
{365}{}{"Øíkal jsem, e jsem nemocnı!"}
{366}{}{"Touíš-li mít spoustu penìz a bıt z toho upachtìnı, kopej 4 stopy dolù a moná tam najdeš penny."}
{367}{}{"Vdycky øíkala, e jí ty nohy snad zabijou, ale nikdo jí nevìøil."}
{368}{}{"Dvaadvacátého èervna spadl Johny mezi bøevna."}
{369}{}{"Zde leí tìlo naší Anny, jen dojela na banány. Šla do obchodu, beela do vršku, sklouzla na slupce, rozbila si drku."}
{370}{}{"Tom Dalekı je dnes tak daleko, e se u nevrátí."}
{371}{}{"Na památku malého Chrise Woody: Oh, jak je nám líto Woody. Dali jsme ti tvoje chùdy, a netrpí tvoje údy. Škoda, es spadl z té pùdy.}
{372}{}{"Zde pod oblohou a pod stromy leí tìlo Viléma Pohromy. Za ivota to byl klasa. Bùh je nyní jeho spása."}
{373}{}{"Neznámı mu - zcela spálen 21. bøezna 1870 po explozi lampy naplnìné "R.E. Danforthovım nevıbušnım svítícím roztokem.""}
{374}{}{"Narozen 1903 -- Zemøel 1942. Díval se do vıtahové šachty, aby zjistil, jestli u jede kabina. Jela."}
{375}{}{"Zde leí ateista. Bùh ho ochraòuj."}
{376}{}{"Vilém Mucha: Vystudoval práva na W&M univerzitì. Zemøel jako Vilém Mrcha"}
{377}{}{"Sarah Smart: Øeèník, Autorka, Profesorka, Bosorka."}
{378}{}{"Tim Winkle - I neuznávám ádného pokrytectví kromì svého"}
{379}{}{"Dutá hlava - Král Svìta královny Pavouènatky"}
# new additions
{380}{}{"R.I.P Casey Donahue zemøel 6.8.98  Zabit zmutovanım a naštvanım moøskım okounem."}
{381}{}{"Christopher 'Noèní pták' Jones: správce houbové modøiny"}
{382}{}{"Jay "Bramborová noha" Nielson.  Hudebník.  Zemøel ve vìku 104 let, pøi bubnovém sólu."}
{383}{}{"Nitsa - pøíèina toho, e Charles nedostal ten hokej."}
{384}{}{"Thuy Dang. Bùh buï milostiv jeho jménu."}

# trapping the grave
{500}{}{Zkušenì umisuješ past na hrob.}
{501}{}{Nepovedlo se ti umístit správnì past na hrob.}

{510}{}{ zkušenì umisuje past na hrob.}
{511}{}{ nezvládl umístit správnì past na hrob.}

# Find Trap on grave
{515}{}{Na hrobì jsi objevil past.}
{516}{}{Na hrobì jsi neobjevil ádnou past.}

{520}{}{ objevil na hrobì past.}
{521}{}{ neobjevil na hrobì ádnou past.}

# Disarm the Trap on grave
{525}{}{Zkušenì odstraòuješ past.}
{526}{}{Nepovedlo se ti odstranit past.}

{530}{}{ zkušenì odstraòuje past.}
{531}{}{ nezvládl odstranit past.}