#tento soubor prelozil Patrik "GENIE" Lipina
# lockpick
# dude
{100}{}{Úspìšnì se ti podaøilo odemknout zámek.}
{101}{}{Nezdaøilo se. Zámek je stále zamèen.}
{102}{}{Úspìšnì jsi zamkl tento zámek.}
{103}{}{Nepodaøilo se zamknout zámek.}
# other critter
{200}{}{ odemknul zámek.}
{201}{}{ nebyl úspìšný pøi odemykání.}
{202}{}{ zamknul zámek.}
{203}{}{ nebyl úspìšný pøi pokusu o zamèení.}

# explosion
{300}{}{Exploze znièila tenhle zámek.}
{301}{}{Ani exploze neodstranila tenhle zámek.}

# pry
# dude
{400}{}{Podaøilo se ti vypáèit zámek.}
{401}{}{Nepodaøilo se ti vypáèit zámek.}
# other critter
{500}{}{ byl úspìšný pøi páèení zámku.}
{501}{}{ nebyl úspìšný pøi páèení zámku.}
