#tento soubor prelozil Patrik "GENIE" Lipina
# quick looks
# unknown
{100}{}{Vidíš podivnı pøístroj. }
# normal
{101}{}{Vidíš hrací automat. }
# high roller
{102}{}{Vidíš nablıskanı hrací automat. }
# jackpot
{103}{}{Vidíš svítící hrací automat. }

# examines
# unknown
{130}{}{Má to tøi oèi a jednu pai.}
# bet amount
{140}{}{Minimální vklad je $}
{141}{}{.}
# normal
{150}{}{Dáš krk na to, e se to na tebe koutkem oka dívá. }
{151}{}{Jeho naleštìnı kryt a pozlacená páka pod blikajícími svìtly svádivì záøí. }
# high roller
{165}{}{Je to urèeno pro lidi, kteøí se nebojí sázet. }
# jackpot
{180}{}{Moná vıše vıhry vypadá velice lákavì. }

# slot machine first play message
{200}{}{(Dríš mince a ruka se ti chvìje. Automat ti stále šeptá.) *No tak, zlato ... to je
 ono ... jdem na to ... neškádli mì ...*}
{201}{}{Vidíš hrací automat. Jeho naleštìnı kryt a pozlacená páka pod blikajícími svìtly svádivì záøí. Štìrbina na mince tì pøitahuje a ty cítíš, jak ti tváøe hoøí oèekáváním.}
{202}{}{(Dríš mince a ruka se ti chvìje. Automat ti stále šeptá.) *No tak, miláèku ... to je
 ono ... chytni tu páku ... chytni ji pevnì ... jdeme na to ... *}

# insert coin messages
{250}{}{Vlo $}
{251}{}{. }
{252}{}{Poslední $}
{253}{}{.}
{254}{}{Blbej den.}
{255}{}{Jsi na dnì. Blbej den.}
{256}{}{Blbá noc.}
{257}{}{Jsi na dnì. Blbá noc.}
{258}{}{A dost! Konèím!}
{259}{}{A dost! Konèím!}

# this is the message for when the machine is played
{500}{}{V automatu se míhají obrázky}
# this goes between every symbol, example:   "cherry... orange... melon... "
{599}{}{... }

# pay off types
{600}{}{Nic. }
{601}{}{Jedna tøešnièka. }
{602}{}{Dvì tøešnièky. }
# Three [symbol].
{603}{}{Tøi }
{613}{}{. }
{604}{}{JACKPOT! }
{605}{}{DVOJITİ JACKPOT!!! }

# payoff amount message
{700}{}{Vıhra èiní $}
{701}{}{.}
# symbol types
# singular
{1001}{}{tøešnièka}
{1002}{}{pomeranè}
{1003}{}{švestka}
{1004}{}{zvoneèek}
{1005}{}{møíka}
{1006}{}{meloun}
{1007}{}{sedmièka}
# plural
{1101}{}{tøešnièky}
{1102}{}{pomeranèe}
{1103}{}{švestky}
{1104}{}{zvoneèky}
{1105}{}{møíky}
{1106}{}{melouny}
{1107}{}{sedmièky}

# float messages
{2000}{}{*Pojïme si dát další hru, drsòáku.*}
{2001}{}{*Ahoj, námoøníku.*}
{2002}{}{*Vítej. Budu k tobì hodnı.*}
{2003}{}{*Tik... Tik... Tíííík...*}
{2004}{}{*Bing*}
{2005}{}{*Bang*}
{2006}{}{*Klik-cvak*}
{2007}{}{*Zzzzzzz*}
{2008}{}{*Cinkylink*}
{2009}{}{*Dindading*}
{2010}{}{*Hej, nádhero. Pojïme si dát další hru.*}
{2011}{}{*Ahoj zlato.*}
{2012}{}{*Vypadáš správnì drsnì. Proè si nejdeš zahrát?*}

# 3.  NO MONEY (WTG, 9)
# no money to play
{2175}{}{(Jak tak zíráš na automat, uvìdomuješ si, e nemáš co vsadit, a proklínáš svou chudobu. Moná nìkdy jindy...)}
{2176}{}{Pryè.}
# won jackpot block
{2185}{}{(Na pøístroji poblikává svìtılko oznaèené 'MIMO PROVOZ'.)}
{2186}{}{Pryè.}

# 4. RETARD (WTG)
{2100}{}{Vidíš podivnou kovovou pozlacenou pixlu s tøema oèima a jednou paí. Je to jedna z
 nejkrásnìjších vìcí, které kdy pošly tvım ivotem.}
{2101}{}{Jáá }
{2102}{}{ ty kdo ?}
{2103}{}{Já chci MÁMU. }
{2104}{}{ stıská se po AR-JOJO. Chci domù jít}
{2105}{}{(Potøesme si rukama)}
{2106}{}{ty divnı mutant}
{2107}{}{Chvalte Vault! Chvalte Vault!}
{2108}{}{Ty jsi vodní èip?}
{2109}{}{Chodím a hledám lesklé vìci.}
{2110}{}{Pryè.}

# 5.  RETARD TALKS TO SLOT MACHINE (4, 5)
{2130}{}{Ta divná pozlacená kovová krabice s tøema oèima a jednou paí neodpovídá.}
{2131}{}{JÁ }
{2132}{}{!ODPOVÌZ MNÌ!}
{2133}{}{(Potøesme si rukama)}
{2134}{}{Já dítì Zakladatele. Ty se mnou TEÏ mluvit.}
{2135}{}{ty divnı mutant}
{2136}{}{Ty jsi vodní èip?}
{2137}{}{Chodím a hledám lesklé vìci}
{2138}{}{(Pryè.)}

# 6.  RETARD PULLS HANDLE (4, 5)
{2151}{}{Uchopíš jeho pai a jemnì si s ní potøeseš. Slyšíš nìjaké *bzzzzzzz,* a krabice
 promlouvá! "Prosím... vlote... peníze."}
{2152}{}{Ajajaj! Robot! Robot! Honééém pryè}
{2153}{}{(Pryè.)}

# slot machine taunts loss
# male
{2200}{}{(Slyšíš, jak se ti ta mašina smìje.)}
{2201}{}{*Hehehe, proè toho nenecháš, zlato.*}
{2202}{}{*Proè k tomu nepustíš nìkoho, kdo to umí?*}
# any
{2204}{}{(Slyšíš, jak se ti ta mašina smìje.)}
{2205}{}{(Automat se smìje pod vousy.)}
{2206}{}{*Smùla. No tak, nevzdávej to.*}
# female
{2207}{}{*Dostal jsem co jsem chtìl, bejby. Proè to nevzdáš ?*}
{2208}{}{*Odpad...*}
{2209}{}{*A ti dveøe od casina nepøiskøípnou zadek, a odsud pobeíš.*}

# slot machine taunts win
# male [3X - 1X]
{2247}{}{*Aj! To je ono, cukrouši! Ó, boe! Ano! Ještì! Rychleji! Více! Na co èekáš?! Ještì!*}
{2248}{}{*To je ono, cukrouši... tahej za tu páku... rychleji, více, rychleji... pojï na to...*}
{2249}{}{*No tak, zlato... tohle se kadému aspoò jednou stane... zkus to ještì ... prosím...*}
# any
{2250}{}{*Ještì to nezdávej bejby, prosím! Potøebuju tì jako ještì nikdy!*}
# female [1X - 3X]
{2251}{}{*No tak, zlatíèko... zkus to ještì... chytni tu páku... pevnì ji stiskni... jdem na to...*}
{2252}{}{*To je ono, zlato... tahej dál za tu páku... rychleji, více, rychleji... pojï na to...*}
{2253}{}{*Áách! To je ono, miláèku! Ještì jednou! Tentokrát tahej víc! Víc!*}

# 13. DRUNK, HIGH OR OTHERWISE FUCKED UP (WTG)
{2280}{}{(Vidíš hrací automat. Jeho naleštìnı kryt a pozlacená páka pod blikajícími svìtly New Rena svádivì záøí. Štìrbina na mince tì pøitahuje a ty cítíš, jak ti tváøe hoøí oèekáváním. Jak na ten pøístroj zíráš, jedno z jeho tøí oken na tebe mrkne. Slyšíš jemnı hlas vycházející ze štìrbiny na mince.) *Nuue! Nazdáááek, cukrouši. Nechceš zabavit chudou sleènu?*}
{2281}{}{(Vidíš hrací automat. Jeho hrubı, drsnı rám a zlacená páka záøí pod svìtly New Rena jako sluníèko. Štìrbina na mince tì pøitahuje a ty cítíš, jak ti tváøe hoøí oèekáváním. Jak na ten pøístroj zíráš, slyšíš drsnı muskı šepot linoucí se ze štìrbiny na mince.) *Takovouhle koèku jsem tady ještì nevidìl. Chceš se pobavit?*}
{2282}{}{::Jdi se bodnout::}
{2283}{}{Ehm...ahoj?}
{2284}{}{::Zhluboka se nadechneš a jdeš pryè.::}

# 14. DRUNK CONVERSATION 1 (13)
{2300}{}{*Jsem poøád tu, krásko.* (Automat sniuje hlas.) *Tak pojï, jdem na to ... chceš si vsadit?*}
{2301}{}{*Joo, jsem tu poøád, cukrouši.* (Automat sniuje hlas.) *Víš, e jsi poøádnì velikı chlap? Tak pojï ... nechceš do mì strèit nìjaké mince?*}
{2302}{}{Kdó jsí ?}
{2303}{}{Hic  Vššak jjá si hned vssadíím.}
{2304}{}{Myslím, e toho radši nechám, ne udìlám nìco èeho bych mohl litovat. (Pryè.)}
{2305}{}{::Zhluboka se nadechneš a jdeš pryè.:: (Pryè.)}

# 15. DRUNK 2 (14)
{2320}{}{*Jsem tvùj ideální partner.* (Automat na tebe mrkne.) *Dej mi pár mincí a já ti zpùsobím takové potìšení jako nikdo pøedtím.*}
{2321}{}{*Jsem tvùj ideální partner, drahoušku. Jediné co chci je trochu pozornosti. Pomùeš mi? No ták, jen pár mincí?*}
{2322}{}{Co takhle si jen povídat?}

# 16. DRUNK 3 (15)
{2340}{}{*Jistì zlato, mùeme.* (Automat se soucitnì zatváøí.) *Copak trápí tvou nádhernou hlavièku?*}
{2341}{}{*Ale jistì, cukrouši, mùem.* (Automat se soucitnì zatváøí.) *Co tì trápí, krasavèe?*}
{2342}{}{Chybí mi MÁMA a ARROYO a ... nemùu najít GECK a ... *smrk*}
{2343}{}{Chybí mi MÁMA a Arroyo rozmašírovali a ... ani nevím kde všichni jsou ... a ... *smrk*}
{2344}{}{Musím spravit véélikou loï ... a vùbec nevím JAK ... a m-m-moje máma je pryè a ... *smrk*}
{2345}{}{Jsem skonèil tuhle hru ... teï se jen ochomejtám kolem ... se bojím, e je PO VŠEM a ... *smrk*}
{2346}{}{Já jenom e Folaut dvì nepodporuje mojí tøi dé efix kartu za kterou jsem vyhodil tolik p-penìz a *smrk*}
{2347}{}{Chtìl jsem si udìlat dobrou p-p-postavu, ale nìjak jsem to zblbnul s tím rozdìlováním ... teï mám takovouhle zasranou postavu ... *smrk*}
{2348}{}{Si tady povídám s hracím auto-ma-matem, u jsem to-ta-tálnì mimo}

# 17. DRUNK 4 (16)
{2370}{}{*Tak ... tak u tím netrap svoji roztomilou hlavièku ... já se o všechno postarám. No tak, odpoèiò si a vypovídej se. Neboj se.*}
{2371}{}{*Tak ... tak u se tím netrap ... já se o všechno postarám. No tak, opøi se o mì svımi velkımi rameny a vypovídej se. Neboj se.*}
{2372}{}{Díky, hraccí automate *smrk* jssi tøída.}
{2373}{}{Ty jsi ten nejlepší chlápek, kterı se tu kdy ukázal, kadı mì zkouší jenom zabít nebo okrást o peníze a ... *smrk*}

# 18. DRUNK 5 (17)
{2380}{}{*Budeš v poøádku, e jo, zlato? Nerad bych tì tu nechal ve stavu, v jakém jsi teï.*}
{2381}{}{(Opøeš o automat svou tìkou hlavu.)}
{2382}{}{*Budeš v poøádku, e jo, cukrouši? Nerad bych tì tu nechal ve stavu, v jakém jsi teï.*}
{2383}{}{Já budu v pohodì ... dík za rozhovor, automate, já tì miluju}

# 19. DRUNK 6 (18)
{2400}{}{*Jsi asi jediná hrdinka v tomhle dvoubitovém svìtì zlodìjù a vrahù! Dej na sebe pozor, ano zlato?* (Otáèí se.) *Radìji u jdi, ne se zaènu chovat negentlemansky.*}
{2401}{}{(Zdá se ti, e se v jednom z jeho oken zaleskla slza.) }
{2402}{}{*Jsi asi jedinı hrdina v tomhle dvoubitovém svìtì zlodìjù a vrahù! Ehm ... dávej na sebe pozor, ano cukrouši?* (Otáèí se.) *Radìji u jdi, ne zaènu plakat.*}
{2403}{}{Sbóóóhééém}

# rollin' messages
{3000}{}{No tak, }
{3001}{}{! zlatíèko potøebuje nové botièky!}
{3002}{}{! tatínek potøebuje novou plazmovou pušku!}

# can't play
{4000}{}{Zdá se, e nìkdo blokuje automat.}