#tento soubor prelozil Patrik "GENIE" Lipina
{100}{}{Tohle auto nevypadá jako funkèní kousek. Pøeci jen ale vypadá lépe, než ty ostatní okolo. Možná by se dalo spravit.}
{101}{}{Tohle vozítko není zrovna schopno provozu. Chce to palivový regulátor.}

{200}{}{Podaøilo se ti opravit auto montáží palivového regulátoru.}
{210}{}{Ani montáží palivového regulátoru se ti nepodaøilo opravit auto.}

{300}{}{Nepodaøilo se ti opravit auto. Možná mít ten palivový regulátor, o kterém mluvil Smitty, tak by se dalo dát dohromady.}

{400}{}{Bylo by to pøíliš nápadné otevøít kapotu a zaèít makat na autì.}
