#tento soubor prelozil Patrik "GENIE" Lipina
{100}{}{Plakát s jednoduchým náèrtem hledané osoby. Osoba na tomto obrázku se ti zdá povìdomá.}
{101}{}{Na popisce èteš.}
{102}{}{Hledá se mrtvý nebo živý jakožto Zabiják dìtí a krysí bastard. Odmìna $10,000 - mrtvý nebo $5,000 - živý.}
{103}{}{Hledá se mrtvý nebo živý jakožto Zabiják dìtí a krysí bastard. Odmìna $10,000 - mrtvý nebo $5,000 - živý.}
{104}{}{Hledá se mrtvý nebo živý jakožto Zabiják dìtí a krysí bastard. Odmìna $10,000 - mrtvý nebo $5,000 - živý.}
