{100}{}{Tu vois un garde.}
{101}{}{Tu vois un garde en SuperArmure.}
{102}{}{Tu vois quelqu'un vêtu d'une SuperArmure quelque peu inhabituelle. Son plastron porte un insigne que tu n'a jamais vu avant.}

{103}{}{Rien à signaler.}
{104}{}{Rien à signaler de mon côté et toi ?}
{105}{}{Tu devrais pas être à ton poste, soldat ? Ce n'est pas bien de traîner par ici.}

{106}{}{Tu ne portes pas ton uniforme.}
{107}{}{Tu ferais mieux d'aller retrouver le Sergent et de te mettre en tenue.}
{108}{}{Tu prends des gros risques en te promenant sans uniforme. Tu ferais mieux d'aller à la réserve.}

{109}{}{Mais qui vous êtes, vous... ?! Alerte ! Des envahisseurs !}
{110}{}{La base a été infiltrée ! Alerte !}
{111}{}{Un groupe d'envahisseurs ! Sonnez l'alarme !!}

{112}{}{Alerte de sécurité !! Condamnez la base !!!}
{113}{}{Fermez toutes les stations ! Nous sommes en état alerte !!}
{114}{}{Alerte envahisseur ! Activez le code rouge !!!}

{115}{}{On va t'exterminer !!}
{116}{}{L'Enclave régnera sur le monde !}
{117}{}{Ta mort permettra à l'Enclave de survivre !}

{200}{}{...Enfoiré...}
{201}{}{...Ouais, tu ferais MIEUX de foutre le camp...}
{202}{}{... Quel trou du cul...}
{203}{}{...Oui, m'sieur ! Enfoiré de m'sieur !...}
