{100}{}{Tu vois un homme bien habillé.}
{101}{}{Tu vois AHS-9, le Grand et le Terrible.}
{102}{}{Tu vois un homme bien habillé.}
{103}{}{Tu blasphèmes le nom d'Hubol ! Tu dois mourir !}
{104}{}{Ta nature perfide ne connaît pas de limite !}
{105}{}{La Grande Roue te roulera dessus !}
{106}{}{Tu es en présence d'AHS-9, le Grand et le Terrible. Que veux-tu de lui ?}
{107}{}{Agh gnan, AHS !}
{108}{}{Je cherche mon peuple. J'ai entendu dire qu'il était venu ici dans des vaisseaux volants.}
{109}{}{J'ai de nombreuses questions à te poser, AHS-9.}
{110}{}{L'Eclairée de la RNC voulait que je te remette cette lettre. Elle a parlé d'une récompense ?}
{111}{}{L'Eclairée de RNC voulait que je te remette cette lettre. La voici.}
{112}{}{AHS-9, j'ai une lettre de ton agent de la RNC. Je m'incline devant ta gloire.}
{113}{}{Que la mort t'emporte. Au revoir, vieil homme.}
{114}{}{Rien, pardon.}
{115}{}{Oui, mon enfant ?}
{116}{}{Hinchoaf ? [Tu me comprends ?]}
{117}{}{Aagga da gou dou ! [Oh, dieu soit loué ! Je cherche mon peuple. Je dois passer au dessus de la grande eau.]}
{118}{}{Pou papi ! [Eh bien, merci de m'avoir accordé un peu de ton temps. Je dois continuer maintenant. Ce fut un plaisir de parler avec toi.]}
{119}{}{Je ne comprends pas un mot de ce que tu racontes. Tu devrais peut-être voir avec Juan ou Vikki pour un alignement.}
{120}{}{Merci !}
{121}{}{Bien sûr, mon enfant. L'alignement a effacé tes neurodines de base et les a alignées aux miennes et aux rayons de la Grande Roue. De quoi as-tu besoin ?}
{122}{}{Aagga da gou dou ! [Oh, dieu soit loué ! Je cherche mon peuple. Je dois passer au dessus de la grande eau.]}
{123}{}{B-b-b-enèssi [Rien, merci. Mais ça fait du bien de pouvoir te parler. Au revoir !]}
{124}{}{Si tu acceptes de me rendre un service, je pourrai t'aider, mon enfant.}
{125}{}{Quoui ? [De quoi s'agit-il ? J'aimerais beaucoup t'aider.]}
{126}{}{Non !}
{127}{}{Mon homologue, l'Empereur de Shitown, a fait de ma vie un désastre et j'aimerais mettre fin à la sienne. En échange de ce service, je veillerai à ce que tu puisses te rendre où tu le souhaites.}
{128}{}{Aouh ! [Je vais le faire.]}
{129}{}{Non !}
{130}{}{Si tu changes d'avis, préviens-moi. N'oublie pas que je suis probablement le seul capable de t'aider à retrouver ta famille.}
{131}{}{O-kayyy ? [Quel est ce service ?]}
{132}{}{Nannenni ! [Merci, mais je ne veux rien devoir à personne. Au revoir !]}
{133}{}{Bien. Dis-moi quand tu auras terminé, et en même temps, je tâcherai de trouver un moyen qui nous permetta d'atteindre ton objectif. Au revoir, mon enfant.}
{134}{}{'Voir ! [Au revoir, AHS-9. Tu es un grand homme.]}
{135}{}{As-tu mené à bien ta tâche ? Ton avenir et celui de la Roue sur cette planète en dépendent.}
{136}{}{Euh nalut. [Pas encore. Je voulais juste dire bonjour.]}
{137}{}{Je m'en occupe. Mais dis-moi...}
{138}{}{Pas encore. Je vais revenir te voir.}
{139}{}{Bienvenue à toi aussi. Maintenant termine ton travail pour que je puisse t'aider.}
{140}{}{Ng ! Ng ! [Oui, m'sieur !]}
{141}{}{Tes émanations me disent que tu as réussi à débarrasser le monde des neurodines polluantes de l'Empereur.}
{142}{}{Jirsi ! [Oui, j'ai réussi. Comment vas-tu faire pour remplir ta part du marché ?]}
{143}{}{Oui, j'ai réussi. Maintenant, tu vas devoir aider mon peuple.}
{144}{}{Sur les quais de Shitown, tu trouveras le PMV Valdez. Une fois à bord du navire, dirige-toi vers la droite et monte au bureau du capitaine. Appuie sur le bouton Go et le pétrolier t'emmènera à destination.}
{145}{}{'Esi ! [Ce fut un plaisir, AHS-9. Je te souhaite tout ce qu'il y a de meilleur. Au revoir.]}
{146}{}{Des vaisseaux volants ? Tu dois parler de l'Enclave et de ses hélicos.}
{147}{}{Ouais, ça doit être ça.}
{148}{}{L'Enclave ? L'Enclave, qui ?}
{149}{}{Tu peux me croire, mon enfant, tu fais référence à l'Enclave.}
{150}{}{Ouais, d'accord. Comment faire pour les trouver ?}
{151}{}{L'Enclave est le vestige d'un passé révolu - une neurodine qui ne s'est jamais alignée. Elle possède des bases cachées partout dans l'ancienne Californie et son principal bastion se trouve à l'ouest, par-delà les eaux.}
{152}{}{Comment dois-je faire pour y aller ?}
{153}{}{Comment tu sais tout ça ?}
{154}{}{Ca, mon enfant, tu devras le découvrir par toi-même. Demande autour de toi et tu trouveras la vérité.}
{155}{}{Cela m'aide vraiment. J'ai d'autres questions.}
{156}{}{Comment tu sais tout ça ?}
{157}{}{Allez va, salut.}
{158}{}{Mon enfant, je suis AHS-9. Je vois beaucoup de choses qui se passent dans le monde charnel. As-tu d'autres questions ou puis-je retourner à mes méditations ?}
{159}{}{J'ai d'autres questions.}
{160}{}{C'est bon, tu peux retourner à tes méditations.}
{161}{}{Tu as tué l'Empereur et neutralisé ses larbins ?}
{162}{}{Oui.}
{163}{}{Eh bien, maintenant, plus personne ne peut rester en travers de mon chemin ! Mais je ne veux être redevable de personne. Adieu et bon débarras.}
{164}{}{Eh, ordure. Je vais te tuer !}
{165}{}{Oh. Eh bien, si c'est comme ça que ça doit se passer, au revoir.}
{166}{}{Une lettre de l'Eclairée ? C'est comme ça qu'elle se fait appeler désormais ? Bah. [Il te prend la lettre.] Et elle a promis une récompense ? Voilà ma récompense : ma gratitude. Au revoir.}
{167}{}{Quoi ? T'es mort mon vieux.}
{168}{}{Euh, j'avais des questions.}
{169}{}{Super. Au revoir.}
{170}{}{Pose tes questions à AHS-7. Je suis AHS-9 le Grand et le Terrible et j'ai beaucoup de préoccupations dans la tête. Ne me dérange pas, infidèle.}
{171}{}{Si tu ne réponds pas à mes questions, tu répondras à mes armes.}
{172}{}{Ouais ouais.}
{173}{}{Ahh, une lettre de mon agent. Quel dommage qu'elle se fasse appeler " l'Eclairée " ! Cela prouve qu'elle n'est vraiment pas éclairée. Je te remercie.}
{174}{}{Pas de problème. J'ai une ou deux questions à te poser.}
{175}{}{Formidable. Au revoir.}
{176}{}{Oui, mon enfant ?}
{177}{}{Quand le vaisseau spatial décolle-t-il ?}
{178}{}{As-tu du travail pour moi ?}
{179}{}{Ou va tout l'argent que l'on offre ?}
{180}{}{Oh, rien. Laisse tomber.}
{181}{}{Mon homologue, l'Empereur de Shitown, a fait de ma vie un désastre et j'aimerais mettre fin à la sienne. En échange de ce service, je veillerai à ce que tu puisses te rendre où tu le souhaites.}
{182}{}{Oui chef. A plus tard.}
{183}{}{Je ne préfère pas.}
{184}{}{Va voir Badger, sa présence caustique rassemble ces vagabonds minables à bord du pétrolier. Débarrasse-nous de lui. Et ensuite, va voir AHS-7.}
{185}{}{Oui chef. A plus tard.}
{186}{}{Je ne préfère pas.}
{187}{}{Je ne savais pas que c'était une demande, mon petit. Tuez-le !}
{188}{}{Non.}
{189}{}{Très bien, je le ferai.}
{190}{}{Tu désobéis aux ordres d'AHS-9 le Grand et le Terrible !?! Alors, tu vas mourir !}
{191}{}{Vas-y.}
{192}{}{Attends, j'ai changé d'avis.}
{193}{}{Trop tard, infidèle. Tu as prouvé qu'on ne pouvait pas te faire confiance. Va au diable !}
{194}{}{-terminé-}
{195}{}{Il y a des choses que tu ne dois pas savoir pour le moment, mon enfant. [Il sourit.]}
{196}{}{Très bien. J'ai d'autres questions.}
{197}{}{Hum. Au revoir.}
{198}{}{L'HSS Quetzel décollera lorsque les étoiles seront bien alignées.}
{199}{}{Très bien. J'ai d'autres questions.}
{200}{}{Merci. Au revoir.}
{201}{}{A en juger par ton aura, tu es ici avec l'intention de me nuire. Dis-moi, mon enfant, veux-tu tirer parti du risque que tu as pris ?}
{202}{}{Oui.}
{203}{}{Non.}
{204}{}{Non, je veux juste te tuer.}
{205}{}{Bon alors, voilà ce que je te propose. Retourne chez les Shi et élimine Ken Lee et l'Empereur. Pour te récompenser, je te donnerai plus d'argent que tu n'en as jamais rêvé.}
{206}{}{Non, je ne crois pas.}
{207}{}{Marché conclus, gros lard.}
{208}{}{Alors, va anéantir ces âmes gênantes. J'attends des nouvelles de ta réussite. [Il sourit béatement.]}
{209}{}{Au revoir.}
{210}{}{Non, attends, j'ai changé d'avis. Je veux te tuer.}
{211}{}{Ah, mon enfant, comment as-tu pu t'éloigner autant du chemin de la vérité ? Je vois à ton aura que tu envisages de me tuer. Je suis extrêmement déçu. Extrêmement. Allez ! Laisse-nous continuer.}
{212}{}{Oui, allez, va au diable.}
{213}{}{N'oublie pas que tu devras aller voir AHS-7 après avoir mené à bien ta tâche.}
{214}{}{Tous nos besoins ont été satisfaits. Il est maintenant temps pour moi de méditer.}
