{100}{}{Tu vois un chien de garde.}
{101}{}{Tu vois un chien sauvage.}

{120}{}{Tu vois un chien de garde.}
{121}{}{Tu vois un chien sauvage.}

{200}{}{:: GRONDEMENT ::}
{201}{}{:: GROGNEMENT ::}
{202}{}{:: ABOIEMENT ::}

{205}{}{Ouaf}
{206}{}{Ouaf Ouaf}

{210}{}{Les chiens semblent avoir été dressés pour protéger la cabane.}
{211}{}{Le toutou m'aime pas.}
{212}{}{Gentil le toutou, gentil !}

{250}{}{Ce chien pourrait sûrement te mettre en morceaux.}

