{100}{}{Un costaud qui porte un tablier en cuir.}
{101}{}{Balthas le tanneur}
{102}{}{Un homme très musclé qui a l'odeur et l'aspect du cuir.}

{151}{}{Mon fils a été tué par erreur pendant le combat.}
{152}{}{Je ne pourrais jamais vivre sans Jonny.}
{153}{}{[Sanglots]}
{154}{}{Retrouvez-nous à la ferme perdue. On va attaquer les fantômes.}
{155}{}{Bonjour, je m'appelle Balthas. Je dirige la tannerie à Modoc. Puis-je vous aider ?}
{156}{}{Vous avez l'air préoccupé. Il y a quelque chose qui ne va pas ?}
{157}{}{J'aimerais voir vos articles.}
{158}{}{Vous n'auriez pas vu une montre en or traîner dans le coin ?}
{159}{}{Je reviendrai plus tard.}
{160}{}{Je cherche un objet appelé J.E.K. En avez-vous entendu parler ? Sauriez-vous par hasard où je pourrais m'en procurer un ?}
{161}{}{Un J.E.K. ?}
{163}{}{En quoi puis-je vous être utile ?}
{168}{}{Je jette juste un coup d'œil, merci.}
{171}{}{Alors, vous avez trouvé Jonny ?}
{172}{}{J'ai trouvé ceci au fond du vieux puits à sec. Une partie du puits s'est effondrée et voilà ce qu'il y avait dans les gravats. J'ai bien peur que Jonny soit mort.}
{173}{}{Non, rien encore.}
{175}{}{Merci de m'avoir ramené mon fils. Je crois que ne pourrai jamais vous remercier assez, mais prenez cette armure en cuir en gage de ma reconnaissance. J'ai expérimenté un nouveau traitement et je crois que ce cuir vous durera très longtemps. En plus, cette armure vous va très bien.}
{176}{}{Mille fois merci d'avoir sauvé mon fils !}
{177}{}{Laissez-moi seul avec mon chagrin !}
{178}{}{Jonny est vivant ! Des gens qu'on appelle les Slags l'ont secouru. Essayez de patienter encore un peu, je vais trouver un moyen de vous ramener Jonny.}
{179}{}{Jonny a été enlevé. Les fantômes de la ferme l'ont pris et se préparent à le sacrifier à leur Dieu des Ténèbres.}
{180}{}{Je comprends, excusez-moi de vous déranger.}
{181}{}{Hein ? Ecoutez, j'ai pas l'habitude de discuter de mes problèmes personnels avec des étrangers. Vous voulez faire affaire, oui ou non ?}
{182}{}{Pardon, je m'appelle }
{183}{}{. Maintenant que nous avons été présentés... vous m'avez l'air troublé.}
{184}{}{Oui, je cherche des articles en cuir.}
{186}{}{Finalement non.}
{187}{}{Vous avez dit }
{188}{}{? Oui, je crois que j'ai entendu parler de vous. Un des gardes d'une caravane qui passait par là a dit du bien de quelqu'un dont la description vous ressemble. Je sais que nous venons à peine de nous rencontrer, mais j'ai vraiment besoin de votre aide.}
{189}{}{Pourquoi ne me dites-vous pas quel est votre problème et je pourrais peut-être vous aider.}
{190}{}{Excusez-moi mais j'ai assez à faire avec mes problèmes.}
{191}{}{[Il ramasse un ciseau en métal et dans son anxiété commence à le tordre entre ses mains. A votre grande surprise, le ciseau commence à plier comme du mastic. Ce gars, quelle force !] Mon fils Jonny a disparu ! Il est sorti jouer il y a quelques jours, et il n'est jamais revenu. On l'a cherché partout, mais on l'a pas retrouvé.}
{192}{}{Où Jonny joue-t-il en général ? A-t-il l'habitude de jouer avec quelqu'un d'autre ?}
{193}{}{C'est moche pour votre gosse. Mais je ne vois pas ce que je pourrais y faire...}
{194}{}{C'est terrible ! Euh, mais moi je suis juste là pour regarder quelques articles en cuir. J'imagine que je pourrais jeter un coup d'œil à vos marchandises.}
{195}{}{Oooh ! Vous avez vu l'heure ! Il faut que j'y aille.}
{196}{}{Ca veut dire que vous allez m'aider ? Merci ! La dernière fois que nous avons vu Jonny, il jouait aux cow-boys et aux indiens avec son chien Laddie devant la maison. Ces deux-là son inséparables, en fait c'est comme ça que j'ai su qu'il était arrivé quelque chose. Un jour, Laddie est revenue sans Jonny. Depuis nous le cherchons sans arrêt. Prenez Laddie avec vous, peut-être qu'à vous deux vous arriverez à le trouver.}
{197}{}{Bon, vous avez l'air d'avoir une grande expérience des voyages. Grâce à vos talents, vous pourrez peut-être retrouver mon fils.}
{198}{}{Eh bien, oui ! Si je peux me permettre, j'ai une excellente capacité à retrouver les gens. C'est d'accord, je vais vous aider.}
{199}{}{Vous n'obtiendrez rien par la flatterie. Ecoutez, il faut que je vous pose quelques questions.}
{200}{}{Mes prières ont été exaucées ! Prenez Laddie avec vous, peut-être qu'il pourrait vous aider. Mais je vous en prie, faites vite !}
{201}{}{Eh bien, peut-être que vous avez raison. Merci de m'avoir écouté.}
{202}{}{J'ai entendu parler de vous. Ecoutez, je ne veux pas d'ennuis. Nous formons une communauté paisible. Restons en aux affaires, d'accord ?}
{203}{}{J'ai quelques questions à te poser.}
{204}{}{Je n'ai rien à faire avec vous pour le moment. Au revoir.}
{205}{}{Eh bien... Je suis inquiet parce que mon fils Jonny a disparu. Nous l'avons cherché partout, mais il reste introuvable. J'ai bien peur qu'il soit tombé entre les griffes d'animaux sauvages.}
{206}{}{Je peux peut-être vous aider. Comme je voyage beaucoup, je pourrais chercher votre garçon.}
{208}{}{Ce serait vraiment gentil. Il ne faut négliger aucune aide dans ces cas-là. En attendant, vous vouliez quelque chose ?}
{210}{}{Non, pas vraiment. Je dois partir maintenant. Merci.}
{211}{}{Désolé, mais j'en ai jamais entendu parler.}
{214}{}{Hé hé. Le vieux Cornélius vous aurait-il aussi demandé de chercher sa montre de gousset ? Non, vous ne la trouverez pas ici. Ce vieux fou l'a sûrement oubliée quelque part.}
{215}{}{Merci quand même. Je continuerai à chercher. Au revoir.}
{216}{}{[Il vous examine de près, puis il sourit.] Allez, soit un gentil petit garçon et va jouer dehors.}
{217}{}{[Il vous examine de près, puis il sourit.] Allez, soit une gentille petite fille et va jouer dehors.}
{218}{}{Continuez à chercher, je vous en prie. Je sais qu'il est encore vivant. Je le sens !}
{219}{}{C'est bien la carabine à air de Jonny. Noooooooonnnnn ! [Les nerfs de Balthas lâchent et il éclate en sanglots.]}
{220}{}{Je savais que Jonny n'était pas mort ! Vous dites que je dois attendre... je ne comprends pas ! Est-il blessé ? Mon instinct me dit d'aller vers mon fils, mais j'ai le pressentiment qu'avec vous, son sort est entre de bonnes mains. Dépêchez vous et ramenez-le moi.}
{221}{}{Oh non, pas les fantômes ! Je savais bien que nous aurions dû tout faire brûler. Je ne les laisserai pas prendre mon fils, je retrouverai mon petit Jonny, coûte que coûte. Je suis sûr que les habitants de Modoc m'aideront à retrouver mon fils ! Rendez-vous à la ferme perdue. Nous les tuerons tous !}

{230}{}{Tu as ramené Johnny sain et sauf à Modoc.}
