{100}{}{Un homme totalement ivre. [Il a une petite pancarte où l'on peut lire : « Je travaille en échange d'un repas ».]}
{101}{}{Karl.}
{102}{}{Il est tellement sale que des fleurs sauvages lui poussent dans les cheveux.}

{150}{}{Tiens, prends une bière.}
{151}{}{Tiens, prends cette bouteille de bibine.}
{152}{}{Tiens, prends un nuka cola.}
{153}{}{Hé.}
{154}{}{Hé !}
{155}{}{HE !!}
{156}{}{Les fantômes ne pourront pas me trouver ici... [sanglot]}
{157}{}{C'est bon d'être de retour chez soi.}
{159}{}{C'est Karl. . Il s'est évanoui.}
{160}{}{'Faut qu'il cuve son vin.}
{161}{}{Ah ! Les fantômes de la ferme, ils viennent me prendre !}
{162}{}{Vous n'auriez une p'tite pièce pour... hic... un fermier sans travail ?}
{163}{}{Bien sûr mon gars. Combien il te faut ?}
{164}{}{Et si je te payais un bon repas bien chaud ?}
{165}{}{Malheureusement je n'ai pas d'argent sur moi.}
{166}{}{Que vous est-il arrivé ?}
{167}{}{Des pièèèèèces ?}
{168}{}{Coca !}
{169}{}{Oh ! Une personne bonne et généreuse... Hic... Qu'est ce que Karl peut faire pour votre service ? [Il enlève sa casquette et tend la main.]}
{170}{}{Tenez, voici 100 $.}
{173}{}{Je m'excuse, je n'ai rien à vous donner. Au revoir.}
{174}{}{Savez-vous où je peux trouver un J.E.K. ?}
{175}{}{Vous avez parlé d'un jardin. J'aimerais en savoir plus à ce propos.}
{178}{}{Moi partir.}
{179}{}{Hé Picsou ! Hic... Allez, je sais bien qu'vous avez d'l'argent. Hic... Juste quelques p'tites pièces alors... Hic... quelque chose, quoi. Soyez pas égoïste !}
{180}{}{Tenez, voici 25 $.}
{184}{}{Tenez, voici 1 $.}
{185}{}{Argent.}
{186}{}{Pas d'argent.}
{187}{}{Qu'est-ce que vous voulez ?}
{188}{}{[Répétez à Karl ce que Jo a dit]}
{189}{}{Karl, les fantômes, ils sont partout... Regardez, en voilà un !}
{190}{}{Umbaba.}
{191}{}{Vous venez... Hic... pour vous moquer du pauvre Karl, hein ?... Hic... Alors, qu'est-ce que vous attendez... Hic... allez-y !}
{198}{}{[Il parle d'une voix inarticulée.] Très gentil à vous... Hic. 1000 $ ça devrait faire mon affaire.}
{199}{}{Bien sûr. Tenez.}
{200}{}{Et puis quoi encore ? Allez tenez, voilà 25 $.}
{201}{}{Vous me croyez stupide ou quoi ?! Je m'en vais.}
{202}{}{[Karl est béat d'étonnement] Merci ! Vous êtes une, Hic... personne très généreuse... Hic. Si y'a quoi que ce soit que j'peux faire, Hic... N'hésitez pas, venez me trouver. Hic... Ah au fait, euh... moi c'est Karl.}
{203}{}{Bien sûr, Karl. Mais maintenant que vous en parlez, je recherche un objet que l'on appelle un J.E.K. Vous sauriez pas par hasard où je pourrais en trouver un ?}
{204}{}{Je ne l'oublierai pas. Prenez soin de vous Karl.}
{205}{}{Qui êtes-vous donc... hic... pour vous moquer d'un pôv' fermier SDF ? Allez, foutez-moi la paix !}
{206}{}{Ouais... hic... une espèce de lézard.... hic... j'en ai entendu parler... hic... Mais j'en ai jamais vu.}
{207}{}{Non, je cherche un J.E.K, pas un gecko.}
{208}{}{Tant pis, merci du renseignement.}
{209}{}{Oh ! Vous voulez dire un gecko... Hic... yah, c'est un léz... Hic... ard gros comme ça. [Karl montre la taille avec ses mains d'un geste vague. Impossible de savoir si le lézard fait 10 cm ou un mètre de long.]}
{210}{}{Bon je recommence : je ne cherche pas un lézard qu'on appelle gecko. Je cherche un objet qu'on appelle un J.E.K.}
{212}{}{Oh, mais... fallait le dire tout de suite... Hic. Je sais où y'en a. Hic... Le paradis... Hic [Karl s'écroule face contre terre et s'évanouit.]}
{213}{}{[Peut-être que tu pourras continuer à lui parler quand il se réveillera.]}
{214}{}{Que Dieu vous bénisse ! Hic... vous m'avez sauvé la vie !}
{215}{}{Je cherche un J.E.K. Vous pouvez m'aider ?}
{216}{}{De rien. Allez, à plus tard.}
{217}{}{Hem... là tout de suite, euh, j'ai pas vraiment faim... Hic... et si vous me donniez l'argent et que je mange après ?}
{219}{}{Espèce de bonimenteur ! Je parie que l'argent qu'on vous donne vous sert à acheter des stimulants !}
{220}{}{Boni... bo... bonimen... C'est quoi déjà qu'vous avez dit ? Hic... Des excuses tout de suite... ch'sais pas ce que ça veut dire, mais chuis sûr que c'est pas gentil !}
{221}{}{[Tu n'as pas le temps de répondre : Karl tombe en avant et s'évanouit.]}
{222}{}{T... Tout va ... Hic... vien... ...bien. Vous n'auriez pas un liquide rafr... Hic...fraichissant. La nuit il fait terri... Hic... blement froid ici.}
{224}{}{Vous êtes vrai... Hic... ment mon meilleur ami sur cette Hic...maudit planète. [Karl commence à boire. Encore une fois, il s'évanouit.]}
{225}{}{Eh bien, tu pourras peut-être lui parler plus tard.}
{226}{}{Vous êtes vrai... Hic... ment mon meilleur ami sur cette Hic... maudit planète. [Karl ouvre la bouteille et commence à boire, puis vous recrache tout dessus.] Pfuit ! Qu'est-ce... que... vous essayez de m'empoisonner ou quoi ? Allez ! Foutez-moi l'camp !}
{227}{}{Ca alors, merci... hic... vous, vous êtes tellement ...hic... sympathique. Attendez, j'vais vous aider, votre porte-monnaie est trop lourd. [Karl plonge la main dans ton porte-monnaie et t'allège de la moitié de ton argent.] C'est très gentil... Hic... si vous avez besoin de quoi... qu'ce soit, hic..., y'a qu'à demander.}
{228}{}{J.E.K.?}
{229}{}{J'y vais.}
{230}{}{« Coca »... Hic... C'est une fête dans une bouteille.}
{231}{}{Alors, plus tard peut-être.}
{232}{}{Ooooh... hic... merci. P't-être qu'avec ça j'vais... hic... pouvoir acheter une balle pour m'en tirer une... hic... Pour sûr, faudrait que j'éco ... Hic... que j'économise pour le revolver.}
{233}{}{Hein ? J'peux rentrer chez moi ? 'Y a p'us d'fantômes ? [Karl s'effondre et pleure. Eh ben, y a rien de plus triste qu'un homme qui pleure...] Merci, je peux enfin rentrer chez moi !}
{234}{}{Où ça ?! Noooonnnn ! Ils m'ont retrouvé !}
{235}{}{Ben oui, j'vivais dans le jardin le plus grand... hic... qu'il pouvait exister... Sauf que... hic..., d'où je viens, ça s'appelle une ferme... }
{236}{}{Vous ne vous souvenez pas ? Nous parlions d'un J.E.K. et vous avez parlé d'un paradis.}
{237}{}{Ah, laisse tomber va.}
{238}{}{Hé... hic... Vous êtes plutôt pas mal ! Vous et moi, on peut aller à l'arrière ... hic... et faire plus ample connaissance. Je peux payer ... J'ai 1000 $. [Karl vous dévisage d'un air suggestif.]}
{239}{}{Vous avez remarqué que vous parlez à un homme, n'est-ce pas ?}
{240}{}{Bien sûr, mais ça vous coûtera 1000 $.}
{241}{}{Merci de votre proposition, mais je préférerais parler du J.E.K..}
{242}{}{Jamais de la vie !}
{243}{}{V... vous z'êtes tellement adorable... hic... si vous ne dites rien, je ne dirai rien non plus. Hic...}
{244}{}{[Vous sentez des hauts le cœur vous envahir.] Il faut que je m'en aille.}
{245}{}{OK, 1000 $.}
{246}{}{[Vous et Karl passez à l'arrière pour un petit coup rapide. A votre surprise, vous aimez ça.]}
{247}{}{[Il dessaoule rapidement et commence à raconter son histoire.] J'étais un citoyen respectable avant de venir ici, un fermier paisible qui travaillait ses champs aussi dur qu'un autre, jusqu'à ce qu'ils commencent à venir la nuit. Leur peau était blanche, pâteuse, comme fluorescente. Je n'ai jamais eu aussi peur de ma vie. Nuit après nuit, ils venaient me voler mes récoltes, mon bétail et je ne pouvais rien faire pour les arrêter. Je sais bien ce que vous allez dire. « Pourquoi n'êtes-vous pas allé chercher de l'aide ? » Eh bien je l'ai fait. Mais personne ne m'a cru. Ils ont pensé que j'étais fou. Finalement, je n'en pouvais plus. JE NE POUVAIS PLUS LE SUPPORTER ! J'ai fait ma valise et je suis venu ici. Je suis ici depuis ce jour-là. [Karl commence à pleurer sans retenue. Vous décidez de le laisser seul avec son chagrin.]}
{248}{}{Oh bon sang ! J'ai dû perdre mon argent en chemin. Tiens, voilà $ }
{249}{}{ .}

{250}{}{Zzz}
{251}{}{Zzzzzz}
{252}{}{Zzzzzzzzz}
{253}{}{Zzzzzzzzzzzz}
{254}{}{Zzzzzzzzzzzzzzz}
{255}{}{*reniflement* *grognement* *reniflement*}

{260}{}{Oh bon sang ! J'ai dû perdre mon argent en chemin. Tiens, voilà $ }
{261}{}{ . C'est tout ce que j'ai.}
{262}{}{Oh bon sang ! J'ai dû perdre mon argent en chemin. Dommage, on s'est bien marré quand même.}

{300}{}{Je vais rentrer chez moi. Merci !}

{400}{}{Tu as renvoyé Karl à Modoc.}
