{100}{}{Tu vois un garde Slag.}

# surrender
{150}{}{Rends-toi ou c'est la mort !}
{151}{}{Je me rends !}
{152}{}{Alors meurs !}
{153}{}{Arg !}
{154}{}{Si tu dois voir Vegeir, nous allons t'escorter jusqu'à lui.}
{155}{}{Pas là. Je verrai Vegeir plus tard.}
{156}{}{Oui, il faut que je voie Vegeir tout de suite.}

{160}{}{T'es bête à bouffer du foin, hein ? Si tu veux voir Vegeir, tu as qu'à le trouver toi-même.}

# caves
# - general
{200}{}{Les « gens de surface », j'ai pas confiance.}
{201}{}{Vegeir a dit de pas te faire de mal... PAS ENCORE !}
{202}{}{On est chargés de protéger notre peuple.}
{203}{}{Je te regarde.}

# - mission complete
{220}{}{Tu as l'air correct... pour un de la « surface ».}
{221}{}{On peut peut-être s'entendre avec ceux de la « surface ».}
{222}{}{Tant mieux si j'ai eu tort sur ton compte.}
