# QUICK LOOK
{100}{}{Tu vois un esclave à l'air maladif.}
{101}{}{Tu vois un esclave intoxiqué.}
{102}{}{Tu vois un esclave.}

# EXAMINES
# 1. [SICKLY MALE SLAVE]
{150}{}{Tu vois un homme à l'air agité. Ses yeux bougent dans tous les sens, comme s'il suivait le vol d'un insecte invisible.}
{151}{}{Tu vois un esclave à l'air maladif. Il a l'air terriblement effrayé et son regard ne semble pas pouvoir se poser sur toi.}
{152}{}{Tu vois un esclave à l'air maladif. Ses vêtements sont en lambeaux et sa peau est toute flasque.}
{153}{}{Tu vois un esclave à l'air maladif. Il tousse violemment et sa chemise en lambeaux est couverte de sang.}
{154}{}{Tu vois un garde à l'air maladif. Il dégage une odeur d'urine et de fèces séchés.}
{155}{}{Tu vois un esclave à l'air maladif. Il n'a plus de dents et ses yeux sont injectés de sang.}
{156}{}{Tu vois un esclave à l'air maladif. Son visage et son cou sont couverts de boutons et il se gratte de temps à autre.}
# 2. [SICKLY FEMALE SLAVE]
{160}{}{Tu vois une femme à l'air agité. Elle fixe le sol avec une vive attention, comme si elle avait peur de lever la tête.}
{161}{}{Tu vois une esclave à l'air maladif. Elle a l'air terriblement effrayée et son regard semble ne pas pouvoir se poser sur toi.}
{162}{}{Tu vois une esclave à l'air maladif. Elle ne semble pas remarquer les mouches qui se posent sur son visage et ses bras.}
{163}{}{Tu vois une esclave à l'air maladif. Ses vêtements sont en lambeaux et sa peau est toute flasque.}
{164}{}{Tu vois une esclave à l'air maladif. Elle a du mal à respirer et des mucosités s'écoulent de son nez.}
{165}{}{Tu vois une esclave à l'air maladif. Elle dégage une odeur d'urine et de fèces séchés.}
{166}{}{Tu vois une esclave à l'air maladif. Elle gratte les boutons qui recouvrent son visage et son cou.}
{167}{}{Tu vois une esclave à l'air maladif. Elle semble vouloir pleurer, mais aucune larme ne peut couler.}
# 3. [MALE SLAVE, DRUGGED]
{170}{}{Tu vois un homme à l'air apathique. Il regarde droit devant lui, dans le vague.}
{171}{}{Tu vois un esclave intoxiqué. Ses yeux bougent dans tous les sens, sans jamais se poser.}
{172}{}{Tu vois un esclave intoxiqué. Lorsque tu le regardes, il mord son avant-bras et détache la peau avec ses dents, puis la mâche lentement.}
{173}{}{Tu vois un esclave intoxiqué. Il sourit vaguement, mais son regard est vitreux et vide.}
{174}{}{Tu vois un esclave intoxiqué. Il regarde vaguement en l'air. De la bave sort de sa bouche.}
{175}{}{Tu vois un esclave intoxiqué. Au moment où il te voit, il tressaille et sourit péniblement, comme s'il était ébloui.}
4. [DRUGGED FEMALE SLAVE]
{180}{}{Tu vois une femme tremblante. Elle fixe le sol, comme si elle avait peur qu'il disparaisse si elle arrêtait de le regarder.}
{181}{}{Tu vois une esclave intoxiquée. Elle ricane toute seule et il y a des traces de sang aux coins de sa bouche.}
{182}{}{Tu vois une esclave intoxiquée. Ses bras sont couverts de marques, ainsi que de bleus et de traces de fouet.}
{183}{}{Tu vois une esclave intoxiquée. Elle cligne rapidement des yeux, comme s'ils étaient secs.}
{184}{}{Tu vois une esclave intoxiquée. Elle se gratte le dos des mains, au point qu'elle s'arrache la peau.}
{185}{}{Tu vois une esclave intoxiquée. Sa chemise est couverte de taches de vomi et elle dégage une légère odeur de térébenthine.}
# 5. [MALE SLAVE, BEATEN]
{190}{}{Tu vois un homme mince. Son corps est couvert de marques de coups de fouet et il fixe humblement le sol, comme s'il attendait des ordres.}
{191}{}{Tu vois un esclave battu.}
{192}{}{Tu vois un esclave mince. Son corps est couvert de marques de fouet et il fixe humblement le sol, comme s'il attendait des ordres.}
# 6. [DRUGGED FEMALE SLAVE]
{195}{}{Tu vois une femme tremblante. Son corps est couvert de marques de fouet et ses vêtements sont en lambeaux.}
{196}{}{Tu vois une esclave.}
{197}{}{Tu vois une esclave. Elle tremble légèrement et son corps est couvert de marques de fouet.}

# FLOAT:
# 7. [SICKLY SLAVE]
{201}{}{::Huhhhhk::}
{202}{}{::Tousse::}
# 8. [DRUGGED SLAVE]
{213}{}{Héé hééééé héé...héé...}
{214}{}{AaaaaAAAAaaaaAAAA}

# CLICK:
# 9. [SICKLY SLAVE]
{220}{}{::Te regarde avec des yeux vides::}
{221}{}{Rrrurrr..rr..::Tousse::}
# 10. [DRUGGED SLAVE]
{240}{}{::Se frotte les yeux::}
{241}{}{Héé hééééé héé...héé...}
{242}{}{AaaaaAAAAaaaaAAAA}
# 11. [BEATEN SLAVE vs. SLAVER]
{261}{}{Laisse-moi tranquille. J'appartiens déjà à quelqu'un.}
{262}{}{S'il te plaît, va-t'en, l'esclavagiste. Je ne veux pas d'ennuis.}

# 12. [BEATEN AND/OR GENERIC SLAVE]
{280}{}{S'ils me voient en train de te parler, il vont tester des stimulants sur moi.}
{282}{}{Ils testent des stimulants sur nous. Certains sont toxiques.}
{281}{}{Je t'en prie... je n'ai pas le droit de te parler.}