{100}{}{Tu vois un bébé Griffemort.}
{101}{}{Tu vois un bébé Griffemort.}
{102}{}{On dirait un Griffemort miniature, avec des griffes et tout.}
{103}{}{Sqwiii... Rrr}
{104}{}{Maaamaa}
{105}{}{patater...}
