{100}{}{Tu vois un terminal d'ordinateur.}
{101}{}{Tu vois le terminal d'interface vocale.}
{102}{}{Tu vois un terminal d'ordinateur standard modifié pour les commandes vocales.}
{103}{}{Tu examines le terminal d'ordinateur, mais tu ne trouves rien d'anormal. Que fais-tu ?}
{104}{}{Tu le frappes d'une manière très " spéciale ".}
{105}{}{Tu lui donnes un coup dans un endroit " spécial ".}
{106}{}{Tu lances le programme de diagnostic.}
{107}{}{Tu l'ouvres et tu regardes à l'intérieur.}
{108}{}{Tu ne t'en occupes pas.}
{109}{}{Tu observes la console pendant un moment et tu choisis le meilleur endroit pour lui donner un coup. Après lui avoir donné un coup bien placé, le moniteur clignote quelques instants, puis se stabilise. Il ne se passe rien d'autre. \nQue fais-tu ?}
{110}{}{Tu lui donnes un coup dans un endroit " spécial ".}
{111}{}{Tu lances le programme de diagnostic.}
{112}{}{Tu l'ouvres et tu regardes à l'intérieur.}
{113}{}{Tu ne t'en occupes pas.}
{114}{}{Cette méthode de réparation bien connue produit deux résultats. Premièrement, le moniteur semble se détraquer pendant quelques secondes avant de se stabiliser. Deuxièmement, tu entends un bruit métallique et le panneau sur lequel tu ascogné tombe par terre. Que fais-tu ?}
{115}{}{Tu lances le programme de diagnostic.}
{116}{}{Bon sang, cette saleté de truc s'est ouverte. Tu devrais regarder à l'intérieur.}
{117}{}{Tu ne t'en occupes pas.}
{118}{}{Tu sais parfaitement que le système devrait disposer d'un ensemble de routines de diagnostic. Mais les entrées de clavier semblent désactivées. L'unité n'accepte que les commandes vocales. Que fais-tu ?}
{119}{}{La seule chose qui reste à faire est de regarder à l'intérieur.}
{120}{}{Tu ne t'en occupes pas.}
{121}{}{En observant la masse de câbles et de cartes de circuit, tu comprends que le système a été volontairement saboté. Une des cartes de circuit, le module de reconnaissance vocale, est irréparable et doit être remplacée. Il ne te reste plus qu'à trouver un module de remplacement.}
{122}{}{Terminé.}
{123}{}{Terminé.}
{124}{}{Tu installes le module dans le terminal. Le système est réparé.}
{125}{}{Le terminal requiert un module de reconnaissance vocale pour fonctionner.}
{126}{}{Terminé.}
{127}{}{Le système fonctionne bien maintenant.}

{128}{}{Accès aux séquences de sécurité, chargement de l'affichage holographique...}

{129}{}{Tu es le dernier, Gruthar. Ton engeance malsaine va bientôt dire amen.}
{130}{}{Dis à ton soi-disant président qu'il brûlera pour cela.}
{131}{}{Bref. Tu n'as jamais été rien d'autre qu'un animal qui parle.}
{132}{}{Possible, mais nous sommes issus de vos expérimentations. Vous nous avez donné la vie !}
{133}{}{Et maintenant, je te donne la mort.}
{134}{}{Prenez son corps. Le médecin voulait un spécimen.}
{135}{}{Leur sang coulera tel le Nil !}
