{100}{}{Tu vois un voyageur qui a l'air couvert de poussière.}
{101}{}{Tu vois un client du bar.}
{102}{}{Tu vois un voyageur qui a l'air couvert de poussière.}
{103}{}{Hé ! Les gars ! C'est la personne qui a foutu la pâtée aux mecs de l'Enclave !}
{104}{}{Félicitations !! Bravo !}
{105}{}{Hé là ! J'te paie un coup à boire, ça marche ?}
{106}{}{On dirait que le Capitaine s'encanaille...}
{107}{}{Tiens, ce serait pas le lèche-bottes de la Première Citoyenne...}
{108}{}{Tiens, ce serait pas le « Capitaine »...}
{109}{}{Faites gaffe, tous. La Loi vient d'entrer !}
{110}{}{On s'encanaille, Citoyen ?}
{111}{}{Tu devrais pas être dans ta cité, « Citoyen » ?}
{112}{}{Foutus Citoyens, ils se baladent comme ça, quand ça leur chante...}
{113}{}{Ouaoh ; ça, un mutant ?!!}
{114}{}{Dégagez, les gars ! 'Y a du mutant dans la maison !}
{115}{}{Va y avoir du grabuge si les gardes voient ce mutant...}
{116}{}{Ils laissent rentrer les *mutants* maintenant ?}
{117}{}{Ce mutant va se retrouver au Centre de détention...}
{118}{}{Me dites pas que c'est un goule !}
{119}{}{C'est quoi, ce *bordel ? !* Foutez-moi ce goule dehors !}
{120}{}{Virez-moi cette saloperie de goule du bar !}
{121}{}{Si l'goule perd des morceaux de peau ici, je l'étripe.}
{122}{}{Ce goule va servir de cible d'entraînement si les gardes le voient.}
{123}{}{On peut à peine s'acheter un passe pour un jour, ces temps-ci...}
{124}{}{Le prix des brahmines n'arrête pas de monter...}
{125}{}{On va avoir une mauvaise saison si cette sécheresse continue...}
{126}{}{Alors, Capitaine, on s'encanaille ?}
{127}{}{Ecoutez, moi j'ai rien fait, Capitaine. Je m'occupe de mes oignons, c'est tout.}
{128}{}{Je sais rien, Capitaine. Laissez-moi tranquille, à la fin !}
{129}{}{Va t'faire, « Capitaine » !}
{130}{}{On dirait qu'avec Lynette n'importe qui devient Citoyen, maintenant !}
{131}{}{Laisse-moi tranquille ! J'ai déjà donné aux gardes la redevance pour leur protection.}
{132}{}{On s'encanaille, Citoyen ?}
{133}{}{Tu ferais peut-être mieux de rentrer dans ta Cité !?}
{134}{}{Casse-toi !}
{135}{}{Va te faire voir !}
{136}{}{On dirait qu'avec Lynette n'importe qui devient Citoyen, maintenant !}
{137}{}{Ce Smith, c'est un brave type.}
{138}{}{Je crois que je n'arriverai jamais à avoir un passe pour un jour.}
{139}{}{Bois pas l'eau du coin. Elle affole les compteurs geiger.}
{140}{}{Quand ces foutus Citoyens viennent dans le coin, 'y en a pas un qui te ferait signe ou qui te dirait bonjour !}
{141}{}{Peut-être que la Cité de l'Abri ne nous aime pas, mais, au moins, elle nous protège.}
{142}{}{Fais gaffe à cet Autodoc. En principe, il soigne... mais pas toujours. Joue pas à la roulette russe !}
{143}{}{Ed, le marchand de brahmines, a encore dû augmenter ses tarifs pour faire face à la redevance mensuelle des gardes.}
{144}{}{Grâce à Skeev j'ai pu passer un peu de gnôle en ville contre un pourcentage.}
{145}{}{'Passé toute la semaine sur la route. J'venais de la RNC, là-bas, tout au sud.}
{146}{}{J'ai des amis qui sont allés à Reno... depuis, on les a pas revus.}
{147}{}{Il paraît qu'à Reno, ça recommence à être tendu. Les familles, là-bas, elles se haïssent.}
{148}{}{On dit que ces goules, là-bas, à Gecko, ils ont l'intention d'attaquer la ville.}
{149}{}{Je te conseille pas de croiser le chemin d'un Citoyen, si tu veux pas te retrouver au Centre de détention.}
{150}{}{Cette Lynette, c'est pas une sentimentale !}
{151}{}{La Cité de l'Abri, c'est pas ce qu'on pourrait appeler une ville « libre ». Mais enfin, c'est pas mal.}
{152}{}{La Cité de l'Abri, c'est mieux que la Fosse. Mais ça rigole moins.}
